### ISSUE TITLE
Example uses deprecated verison of authentication.authenticate()

### ISSUE THREAD

**Issue by mscherotter** [MicrosoftDocs/msteams-docs#10059]
The non-promise version of authentication.authenticate() is used in this example.  That version is deprecated as per the latest API.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b608448b-3dd7-d5be-128c-da2859067140
* Version Independent ID: b608448b-3dd7-d5be-128c-da2859067140
* Content: [Use external OAuth providers - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-oauth-provider)
* Content Source: [msteams-platform/tabs/how-to/authentication/auth-oauth-provider.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/tabs/how-to/authentication/auth-oauth-provider.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **surbhigupta**

**Comment by ChetanSharma-msft** [comment]
Hello @mscherotter - Thanks for raising your query.

@Doc Team - Please help to update the JavaScript example in below documentation:
https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-oauth-provider

Currently, provided example is **not using promise (.then)**, so please update it as per below sample code:
https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/main/samples/tab-external-auth/nodejs/src/components/Tab.js#L48
