### ISSUE TITLE
The problem occurs after re-registering with the same Teams ID.

### ISSUE THREAD

**Issue by yoohyojun** [MicrosoftDocs/msteams-docs#10066]
The same problem is occurring with images when uploading to the Teams app.

Other users can upload apps normally.
So I think there's a problem with my account, but I don't know what it is.

I recently created a new account and the email address I used before is the same. I think this is the problem. How do I solve it?

![1](https://github.com/MicrosoftDocs/msteams-docs/assets/80876813/837bf6a5-b64e-4a6b-bd9d-b8b671abbc1a)
![2](https://github.com/MicrosoftDocs/msteams-docs/assets/80876813/c01b9c2a-e0d3-4b59-b744-9a02b5a394c4)

**Comment by Prasad-MSFT** [comment]
@yoohyojun - Could you please let us know what issue you are facing? From the description and screenshot its not quite clear.

**Comment by yoohyojun** [comment]
I am developing a Teams app. An error like the image occurs when uploading, but I do not know the cause.

If I upload to someone else's Teams account, it runs normally.

In the second picture, a 400 error code and the message CreateUserAppDefinitionFailed are generated in the appPackage request, but I have no idea what the cause is.

**Comment by yoohyojun** [comment]
> - 어떤 문제가 발생하고 있는지 알려주시겠습니까? 설명과 스크린 샷에서 명확하지 않습니다.

I am developing a Teams app. An error like the image occurs when uploading, but I do not know the cause.

If I upload to someone else's Teams account, it runs normally.

In the second picture, a 400 error code and the message CreateUserAppDefinitionFailed are generated in the appPackage request, but I have no idea what the cause is.

**Comment by Prasad-MSFT** [comment]
> > * Could you please let us know what issue you are facing? From the description and screenshot its not quite clear.
> 
> I am developing a Teams app. An error like the image occurs when uploading, but I do not know the cause.
> 
> If I upload to someone else's Teams account, it runs normally.
> 
> In the second picture, a 400 error code and the message CreateUserAppDefinitionFailed are generated in the appPackage request, but I have no idea what the cause is.

@yoohyojun - Could you please let us know what error message is showing up on the screen? (Translating in English)

**Comment by yoohyojun** [comment]
> > > * Could you please let us know what issue you are facing? From the description and screenshot its not quite clear.
> > 
> > 
> > I am developing a Teams app. An error like the image occurs when uploading, but I do not know the cause.
> > If I upload to someone else's Teams account, it runs normally.
> > In the second picture, a 400 error code and the message CreateUserAppDefinitionFailed are generated in the appPackage request, but I have no idea what the cause is.
> 
> @yoohyojun - Could you please let us know what error message is showing up on the screen? (Translating in English)

It displayed " Something went wrong "

**Comment by Prasad-MSFT** [comment]
@yoohyojun - Could you please share the manifest zip, so that we can investigate at our end?

**Comment by yoohyojun** [comment]
> - 우리가 끝낼 때 조사할 수 있도록 매니페스트 zip을 공유해 주시겠습니까?

공유드립니다

[manifest.dev.json](https://github.com/MicrosoftDocs/msteams-docs/files/13577831/manifest.dev.json)
[manifest.local.json](https://github.com/MicrosoftDocs/msteams-docs/files/13577833/manifest.local.json)
[manifest.prod.json](https://github.com/MicrosoftDocs/msteams-docs/files/13577834/manifest.prod.json)

**Comment by yoohyojun** [comment]
> @yoohyojun - Could you please share the manifest zip, so that we can investigate at our end?

The problem was resolved by uploading the app file of the past version and then uploading the app file of the current version again.

**Comment by Prasad-MSFT** [comment]
Thanks for informing @yoohyojun . Glad that it is resolved.


We are closing this issue for now. Please feel free to reopen if required. Thanks!
