### ISSUE TITLE
When there's no chat history, we can't search others except herself/himself in peoplePicker

### ISSUE THREAD

**Issue by AmyLi0728** [MicrosoftDocs/msteams-docs#10068]
Please see the below video:
[2023-12-06_14-16-00 2.mp4.zip](https://github.com/MicrosoftDocs/msteams-docs/files/13577184/2023-12-06_14-16-00.2.mp4.zip)

**Comment by Prasad-MSFT** [comment]
@AmyLi0728 - Could you please share the sample code which you referred along with the repro steps, so that we can investigate at our end?
