### ISSUE TITLE
Old meeting event in New Teams version issue.

### ISSUE THREAD

**Issue by AnnaBondar4** [MicrosoftDocs/msteams-docs#10071]
Hi Team!

When the user switches to the new Teams version and joins meeting event that was previously created in old Teams version
Then the user doesn’t see the Breakthru app in a meeting even though the Breakthru app was added to this event before.

And he has no option to add any app to the meeting.
 
This also happens with the repeating events. When the event was initiated (in the old Teams version) to happen every Monday and Breakthru app was added to these repeating events (a series), then the users do not see Breakthru in meetings in New Teams, even the organizer doesn’t see the app in the meeting and can’t start Live Share.

<img width="1078" alt="Screenshot 2023-12-07 at 01 47 01" src="https://github.com/MicrosoftDocs/msteams-docs/assets/149601695/6d8829bc-3c8f-49f2-b8af-e8d6e0bcb521">

In the meantime 
When the user creates meeting event from scratch in a New Teams version and attaches the Breakthru app
Then it works properly and the Breakthru app is available for the users in the meeting, as well as he can add other apps to the meeting.

<img width="1080" alt="Screenshot 2023-12-07 at 02 14 52" src="https://github.com/MicrosoftDocs/msteams-docs/assets/149601695/425e5167-748e-4b09-90e0-68eb8b3e4252">

https://github.com/MicrosoftDocs/msteams-docs/assets/149601695/edcb7229-e1c5-4250-9be5-7a5311d7acf3

This issue is of the highest priority as our clients who pay for the product do not see Breakthru app installed in scheduled and repeated meetings (a series) anymore when they start using the New Teams version.

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 19ddf42e-0a47-7717-52d4-e549155480a2
* Version Independent ID: 4bbe9beb-233f-cfd5-097b-f280aab5fde8
* Content: [Microsoft Teams developer community support and feedback - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/feedback)
* Content Source: [msteams-platform/feedback.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/feedback.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Meghana-MSFT** [comment]
@AnnaBondar4 - We checked this issue in Teams web client. We created meeting and added Breakthru app to the meeting. Switch to new Teams and joined the meeting. We are able to see add apps and Breakthru app as well in the meeting.

We checked this in Windows. Meanwhile we check in Mac machine, could you please confirm if users are facing issue only in Mac or Windows as well?

**Comment by Meghana-MSFT** [comment]
@AnnaBondar4 - Apologies for the delay, could you please let us know if you are still facing this issue? We checked in Windows machine, and issue does not repro.
