### ISSUE TITLE
Link to book a feedback interview doesn't work

### ISSUE THREAD

**Issue by aosolis** [MicrosoftDocs/msteams-docs#10078]
Leads to a Bad Request message

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 19ddf42e-0a47-7717-52d4-e549155480a2
* Version Independent ID: 4bbe9beb-233f-cfd5-097b-f280aab5fde8
* Content: [Microsoft Teams developer community support and feedback - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/feedback)
* Content Source: [msteams-platform/feedback.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/feedback.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **surbhigupta**

**Comment by ChetanSharma-msft** [comment]
Hello @SurbhiAgarwal12 - "book a slot" link is breaking in below section:
https://learn.microsoft.com/en-us/microsoftteams/platform/feedback#feature-request-and-general-help

![image](https://github.com/MicrosoftDocs/msteams-docs/assets/59052547/c2419abb-db59-4c03-b003-937f75a0a4e8)

Please help to update the link with appropriate.

**Comment by surbhigupta12** [comment]
This issue is resolved.
