### ISSUE TITLE
incorrect information about newlines

### ISSUE THREAD

**Issue by bzuidgeest** [MicrosoftDocs/msteams-docs#10086]
Look at https://github.com/microsoft/AdaptiveCards/issues/1984
newlines in text require \n\n not \n as this page tells you.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 001a12ea-30fa-d626-18a9-02a518bfb37f
* Version Independent ID: e5f5f69e-66e9-d1b2-e19a-485d0ffcd6fa
* Content: [Text formatting in cards - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?tabs=adaptive-md%2Cdesktop%2Cconnector-html)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-format.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/task-modules-and-cards/cards/cards-format.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **surbhigupta**

**Comment by ChetanSharma-msft** [comment]
Hello @bzuidgeest - Thanks for raising your query.
We will look into it and let you know the updates.

**Comment by Meghana-MSFT** [comment]
@bzuidgeest - This section mentions to use \n\n for newlines in the TextBlock - https://learn.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?tabs=adaptive-md%2Cdesktop%2Cconnector-html#newlines-for-adaptive-cards

![image](https://github.com/MicrosoftDocs/msteams-docs/assets/81138249/b562df25-d33f-4364-8fff-4797823eaa44)

**Comment by bzuidgeest** [comment]
You are right, I must have missed that last sentence. Sorry for the inconvenience.
