### ISSUE TITLE
HTTP example in send message is wrong

### ISSUE THREAD

**Issue by aosolis** [MicrosoftDocs/msteams-docs#10084]
https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-messages?tabs=dotnet1%2Capp-manifest-v112-or-later%2Chttp%2Cdotnet3%2Cdotnet4%2Cdotnet5%2Cdotnet#send-a-message

The HTTP example is for creating a conversation, not posting a message to a conversation!!!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: afbc5b84-5be5-b5c4-30c0-58782a748a03
* Version Independent ID: ef6b8aee-52e7-f5d4-7dfa-8f34a1698330
* Content: [Messages in bot conversations - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-messages?tabs=dotnet1%2Capp-manifest-v112-or-later%2Cjson2%2Cdotnet3%2Cdotnet4%2Cdotnet5%2Cdotnet)
* Content Source: [msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/bots/how-to/conversations/conversation-messages.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **anclear**

**Comment by Meghana-MSFT** [comment]
Thank you for reporting this, we will check this and update the document.

**Comment by Meghana-MSFT** [comment]
@surbhigupta12 - Could you please help to update this HTTP request and body of https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-messages?tabs=dotnet1%2Capp-manifest-v112-or-later%2Chttp%2Cdotnet3%2Cdotnet4%2Cdotnet5%2Cdotnet#send-a-message

HTTP Request : `{Service URL of your bot}/v3/conversations/{conversationId}/activities`

Body : 
```
{
    "type": "message",
    "from": {
        "id": "28:c9e8c047-2a34-40a1-b28a-b162d5f5327c",
        "name": "Teams TestBot"
    },
    "conversation": {
        "id": "a:17I0kl8EkpE1O9PH5TWrzrLNwnWWcfrU7QZjKR0WSfOpzbfcAg2IaydGElSo10tVr4C7Fc6GtieTJX663WuJCc1uA83n4CSrHSgGBj5XNYLcVlJAs2ZX8DbYBPck201w-",
        "name": "Convo1"
   },
   "recipient": {
        "id": "29:1XJKJMvc5GBtc2JwZq0oj8tHZmzrQgFmB25ATiQWA85gQtHieVkKilBZ9XHoq9j7Zaqt7CZ-NJWi7me2kHTL3Bw",
        "name": "Megan Bowen"
    },
    "text": "My bot's reply"
}
```
