### ISSUE TITLE
[Documentation Bugs] Guidelines to create or upgrade a message extension plugin for Copilot for Microsoft 365

### ISSUE THREAD

**Issue by ChetanSharma-msft** [MicrosoftDocs/msteams-docs#10082]
Please verify and update the doc accordingly.

1) Please verify if it should be Keyworks or Keywords?
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/59052547/9276cf31-fa20-4c09-abd7-b4267670bd16)

2) I think, below highlighted content should be Desktop Client rather than Win32?
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/59052547/e75f8bb0-76af-407b-9806-408d7b192c9c)

3) Looks like provided JSON for Adaptive Card Response is based on the API based ME but for traditional ME what should be the JSON.
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/59052547/0a8fe260-f621-4351-b1f7-01059681bb33)

Also, there is no explanation and code mentioned for how to configure the Message Extension content and preview card to return result like below:
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/59052547/761b5a9b-7780-41ad-a636-a55e90639b91)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1d9e7d3e-f334-2862-3e44-e4db9d1a4fb3
* Version Independent ID: 1d9e7d3e-f334-2862-3e44-e4db9d1a4fb3
* Content: [Bot-based message extension plugin guidelines - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/high-quality-message-extension?context=%2Fmicrosoft-365-copilot%2Fextensibility%2Fcontext&tabs=tasks)
* Content Source: [msteams-platform/messaging-extensions/high-quality-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/messaging-extensions/high-quality-message-extension.md)
* Service: **msteams**
* GitHub Login: @v-preethah
* Microsoft Alias: **surbhigupta**

**Comment by ChetanSharma-msft** [comment]
Hello @surbhigupta12 - Could you please help to verify and update the documentation, if needed?

**Comment by v-ypalikila** [comment]
Asks 1 and 2 are updated as part of PR [9998](https://github.com/MicrosoftDocs/msteams-docs/pull/9998). 

Ask 3, connected with the PM, need to verify the ask with Chetan and get back.

**Comment by ChetanSharma-msft** [comment]
Hello @v-ypalikila - I have tried one sample and getting below JSON:
Sample link: https://github.com/OfficeDev/Copilot-for-M365-Plugins-Samples/tree/main/samples/msgext-multiparam-ts

`{
  "composeExtension": {
    "type": "result",
    "attachmentLayout": "list",
    "attachments": [
      {
        "contentType": "application/vnd.microsoft.card.adaptive",
        "content": {
          "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
          "type": "AdaptiveCard",
          "version": "1.5",
          "body": [
            {
              "type": "Container",
              "items": [
                {
                  "type": "TextBlock",
                  "text": "Fictitious Technologies Inc.",
                  "size": "Medium",
                  "wrap": true,
                  "style": "heading"
                },
                {
                  "type": "TextBlock",
                  "text": "Nasdaq Global Select: FTI",
                  "isSubtle": true,
                  "spacing": "None",
                  "wrap": true
                },
                {
                  "type": "TextBlock",
                  "text": "{{DATE(2019-05-03T20:00:00+00:00, SHORT)}} {{TIME(2019-05-03T20:00:00+00:00)}}",
                  "wrap": true
                }
              ]
            },
            {
              "type": "Container",
              "spacing": "None",
              "items": [
                {
                  "type": "ColumnSet",
                  "columns": [
                    {
                      "type": "Column",
                      "width": "stretch",
                      "items": [
                        {
                          "type": "TextBlock",
                          "text": "132.50 ",
                          "size": "ExtraLarge",
                          "wrap": true
                        },
                        {
                          "type": "TextBlock",
                          "text": "▲ 3.12 USD (2.54%)",
                          "color": "good",
                          "spacing": "None",
                          "wrap": true
                        }
                      ]
                    },
                    {
                      "type": "Column",
                      "width": "auto",
                      "items": [
                        {
                          "type": "FactSet",
                          "facts": [
                            {
                              "title": "Open",
                              "value": "130.42 "
                            },
                            {
                              "title": "High",
                              "value": "133.43 "
                            },
                            {
                              "title": "Low",
                              "value": "130.25 "
                            }
                          ]
                        }
                      ]
                    }
                  ]
                }
              ]
            }
          ]
        },
        "previewCard": {
          "contentType": "application/vnd.microsoft.card.hero",
          "content": {
            "title": "Fictitious Technologies Inc.",
            "text": "FTI"
          }
        }
      },
      {
        "contentType": "application/vnd.microsoft.card.adaptive",
        "content": {
          "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
          "type": "AdaptiveCard",
          "version": "1.5",
          "body": [
            {
              "type": "Container",
              "items": [
                {
                  "type": "TextBlock",
                  "text": "Imaginary Software Corp.",
                  "size": "Medium",
                  "wrap": true,
                  "style": "heading"
                },
                {
                  "type": "TextBlock",
                  "text": "Nasdaq Global Select: ISC",
                  "isSubtle": true,
                  "spacing": "None",
                  "wrap": true
                },
                {
                  "type": "TextBlock",
                  "text": "{{DATE(2019-05-03T20:00:00+00:00, SHORT)}} {{TIME(2019-05-03T20:00:00+00:00)}}",
                  "wrap": true
                }
              ]
            },
            {
              "type": "Container",
              "spacing": "None",
              "items": [
                {
                  "type": "ColumnSet",
                  "columns": [
                    {
                      "type": "Column",
                      "width": "stretch",
                      "items": [
                        {
                          "type": "TextBlock",
                          "text": "125.90 ",
                          "size": "ExtraLarge",
                          "wrap": true
                        },
                        {
                          "type": "TextBlock",
                          "text": "▲ 1.85 USD (1.53%)",
                          "color": "good",
                          "spacing": "None",
                          "wrap": true
                        }
                      ]
                    },
                    {
                      "type": "Column",
                      "width": "auto",
                      "items": [
                        {
                          "type": "FactSet",
                          "facts": [
                            {
                              "title": "Open",
                              "value": "124.42 "
                            },
                            {
                              "title": "High",
                              "value": "126.43 "
                            },
                            {
                              "title": "Low",
                              "value": "124.25 "
                            }
                          ]
                        }
                      ]
                    }
                  ]
                }
              ]
            }
          ]
        },
        "previewCard": {
          "contentType": "application/vnd.microsoft.card.hero",
          "content": {
            "title": "Imaginary Software Corp.",
            "text": "ISC"
          }
        }
      },
      {
        "contentType": "application/vnd.microsoft.card.adaptive",
        "content": {
          "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
          "type": "AdaptiveCard",
          "version": "1.5",
          "body": [
            {
              "type": "Container",
              "items": [
                {
                  "type": "TextBlock",
                  "text": "Phantom Industries Ltd.",
                  "size": "Medium",
                  "wrap": true,
                  "style": "heading"
                },
                {
                  "type": "TextBlock",
                  "text": "Nasdaq Global Select: PIL",
                  "isSubtle": true,
                  "spacing": "None",
                  "wrap": true
                },
                {
                  "type": "TextBlock",
                  "text": "{{DATE(2019-05-03T20:00:00+00:00, SHORT)}} {{TIME(2019-05-03T20:00:00+00:00)}}",
                  "wrap": true
                }
              ]
            },
            {
              "type": "Container",
              "spacing": "None",
              "items": [
                {
                  "type": "ColumnSet",
                  "columns": [
                    {
                      "type": "Column",
                      "width": "stretch",
                      "items": [
                        {
                          "type": "TextBlock",
                          "text": "127.90 ",
                          "size": "ExtraLarge",
                          "wrap": true
                        },
                        {
                          "type": "TextBlock",
                          "text": "▲ 2.45 USD (2.03%)",
                          "color": "good",
                          "spacing": "None",
                          "wrap": true
                        }
                      ]
                    },
                    {
                      "type": "Column",
                      "width": "auto",
                      "items": [
                        {
                          "type": "FactSet",
                          "facts": [
                            {
                              "title": "Open",
                              "value": "126.42 "
                            },
                            {
                              "title": "High",
                              "value": "128.43 "
                            },
                            {
                              "title": "Low",
                              "value": "126.25 "
                            }
                          ]
                        }
                      ]
                    }
                  ]
                }
              ]
            }
          ]
        },
        "previewCard": {
          "contentType": "application/vnd.microsoft.card.hero",
          "content": {
            "title": "Phantom Industries Ltd.",
            "text": "PIL"
          }
        }
      }
    ]
  }
}`

Please verify with respective PM and check we can add this type of response as well for Bot based ME.
