### ISSUE TITLE
Embed Microsoft Stream Video is not working in Task Module on Teams Desktop

### ISSUE THREAD

**Issue by sanketdixit2013** [MicrosoftDocs/msteams-docs#10087]
Hello,
We have a Teams bot application in which we are trying to play a Microsoft stream video inside a task module using the embed link for the video which we can get from https://web.microsoftstream.com. We are facing an issue where in the video is getting played when we open the task module on Teams web but it is not working on Teams Desktop application.

1. Screenshot from Teams Web(Working Scenario):
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/62757731/35f05b32-43a6-496c-a235-ef088bcb0692)

2. Screenshot from Teams Desktop App(Not Working Scenario)
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/62757731/d52021d2-45bc-4649-8270-06b08a08ef1c)

In Teams Desktop when we are trying to click on sign in button nothing is happening a pop up appears for a second and then disappears. We have tried logging out and logging in to teams desktop and also tried to delete the Teams cache and test but it is still not working.

Note: Some texts in the screenshots are hidden due to privacy.

Could you please help on this issue?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 800b748d-fb81-8f4d-adc2-3ee610394346
* Version Independent ID: b1ebd031-c5cd-ffeb-d9b2-d752511900db
* Content: [Use Task Modules in Microsoft Teams bots - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/task-modules/task-modules-bots?tabs=nodejs)
* Content Source: [msteams-platform/task-modules-and-cards/task-modules/task-modules-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/task-modules-and-cards/task-modules/task-modules-bots.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **surbhigupta**

**Comment by Prasad-MSFT** [comment]
@sanketdixit2013 - Thanks for raising your issue. We will check this at our end and will update you accordingly.

**Comment by sanketdixit2013** [comment]
Hi @Prasad-MSFT 
[Botmanifest.json](https://github.com/MicrosoftDocs/msteams-docs/files/13675615/Botmanifest.json)
PFA for the manifest file. I have removed some private details from this manifest.
Below is the embed URL I have hidden the ID of the video.

<iframe width="640" height="360" src="https://web.microsoftstream.com/embed/video/{videoid}?autoplay=false&showinfo=true" allowfullscreen style="border:none;"></iframe>

**Comment by Prasad-MSFT** [comment]
Thanks for sharing this @sanketdixit2013. We will repro this issue and will update you with our findings.

**Comment by Prasad-MSFT** [comment]
We did repro the issue using this sample (https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/bot-task-module) and observed that the Microsoft Stream Video is playing without any issue in both MS Teams desktop/web client.
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/62237649/b8813e5d-29a2-4873-8947-ce8793af70cf)

Below is the embed URL:

`<iframe width="640" height="360" src="https://web.microsoftstream.com/embed/video/{videoid}?autoplay=false&showinfo=true" allowfullscreen style="border:none;"></iframe>`

**Comment by sanketdixit2013** [comment]
Hi @Prasad-MSFT ,

Thanks! We will check this and get back to you.

**Comment by sanketdixit2013** [comment]
Hello @Prasad-MSFT,

We have a query, if my windows device is connected to multiple Access work or school account will this not work?

As we have a observation where in our issue is not getting reproduced when we are trying it on a personal laptop where I have logged in with my client domain credentials on Teams desktop app and there is only one Access work or school account but when I try it on my official laptop it has two work accounts one of my company and the other of clients domain. So when I try to login into teams desktop with my client domain credentials it shows the sign in option on the video and when I try to click on sign in button nothing happens.

Could you please help on this?

Thanks!

**Comment by Prasad-MSFT** [comment]
> Hello @Prasad-MSFT,
> 
> We have a query, if my windows device is connected to multiple Access work or school account will this not work?
> 
> As we have a observation where in our issue is not getting reproduced when we are trying it on a personal laptop where I have logged in with my client domain credentials on Teams desktop app and there is only one Access work or school account but when I try it on my official laptop it has two work accounts one of my company and the other of clients domain. So when I try to login into teams desktop with my client domain credentials it shows the sign in option on the video and when I try to click on sign in button nothing happens.
> 
> Could you please help on this?
> 
> Thanks!

If your Windows device is connected to multiple work or school accounts, it is possible that this could be causing issues with embedding Microsoft Stream videos in a Task Module on the Teams Desktop app. When you are signed in to multiple accounts, the app may not be able to determine which account to use to authenticate the request to access the video, resulting in the sign-in option being displayed on the video. When you click on the sign-in button, nothing may happen if the app is unable to authenticate the request.

**Comment by Prasad-MSFT** [comment]
We are closing this issue for now. Please feel free to reopen if required. Thanks!
