### ISSUE TITLE
[Doc-Enhancement] replyToId is empty, So, ID can be used for Card replacement

### ISSUE THREAD

**Issue by SubbaReddi** [MicrosoftDocs/msteams-docs#10098]
Hi Team,
Documentation helped to update the adaptive card by using replyToId. But we get replyToId only when user clicks on adaptive card button. My need to explain additional case of explaining to update the card without button click.

If we send adaptive card using bot  as follows: var response = await turnContext.SendActivityAsync(MessageFactory.Attachment(cardAttachment), cancellationToken);
response will get Id value.

So, the same "Id" can be used as replyToId to replace card. So, please add to the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 293d28d8-bd82-299a-05b3-4f798e485542
* Version Independent ID: 2f747d61-5ff7-be26-d55d-fdc715f4293d
* Content: [Update and delete messages sent from your bot - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/update-and-delete-bot-messages?tabs=dotnet)
* Content Source: [msteams-platform/bots/how-to/update-and-delete-bot-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/bots/how-to/update-and-delete-bot-messages.md)
* Service: **msteams**
* GitHub Login: @WashingtonKayaker
* Microsoft Alias: **anclear**

**Comment by SaiPratap-MSFT** [comment]
@SubbaReddi  - Thanks for reporting your issue. We will check and update the document accordingly.

**Comment by ChetanSharma-msft** [comment]
Hello @SubbaReddi - 

Looks like it is already documented here: https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/update-and-delete-bot-messages?tabs=dotnet#update-messages

However, could you please confirm whether we can add like below?

// Send initial message
var response = await turnContext.SendActivityAsync(MessageFactory.Attachment(card.ToAttachment()), cancellationToken);
var activityId = response.Id; // Fetch activity id.

// MessageFactory.Text(): Specifies the type of text data in a message attachment.
var newActivity = MessageFactory.Text("The new text for the activity");
newActivity.Id = activityId;

// UpdateActivityAsync(): A method that can participate in update activity events for the current turn.
await turnContext.UpdateActivityAsync(newActivity, cancellationToken);

Reference section:

**Comment by SubbaReddi** [comment]
@ChetanSharma-msft : 

Above given documentation have all the details other than the syntax to get activity id

So, adding the note as you mentioned will address the requirement.

**Comment by ChetanSharma-msft** [comment]
NodeJS Code:

```
// Send initial message
var message = await context.sendActivity("<Your Message>");
var activityId = message.id; // Fetch activity id.

// MessageFactory.Text(): Specifies the type of text data in a message attachment.
const newActivity = MessageFactory.text('The new text for the activity');
newActivity.id = activityId;

// A method that can participate in update activity events for the current turn.
await turnContext.updateActivity(newActivity);
```

**Comment by ChetanSharma-msft** [comment]
Python Code:

```
# Send initial message
message = await turn_context.send_activity("<Your Message>")
activityId = message.id # Fetch activity id.

# MessageFactory.Text(): Specifies the type of text data in a message attachment.
new_activity = MessageFactory.text("The new text for the activity")
new_activity.id = activity_id

# A method that can participate in update activity events for the current turn.
update_result = await context.update_activity(new_activity)
```
