### ISSUE TITLE
Sometimes I receive "ReflectionTypeLoadException" error when I post a msg by Incomming Webhook.

### ISSUE THREAD

**Issue by kains4** [MicrosoftDocs/msteams-docs#1009]
The error msg is as below.
------------------------------------------------------------------------------------------------------
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.

I don't know why this error was happend. 
Incomming Webhook was okay and I didn't change any source in my source.
But I recevied that msg suddenly.
Most interest things is that other channel connect is okay.

**Comment by dneduva** [comment]
This has been happening for the last week!
I have been in contact with Microsoft as well. Waiting on the Dynamics Engineer to get back to me..
