### ISSUE TITLE
Markdown syntax for hyperlinks doesn't work if link is formatted

### ISSUE THREAD

**Issue by bigtrout3** [MicrosoftDocs/msteams-docs#10106]
### Problem

When composing a message, the markdown hyperlink syntax `[Display Text](Link Text)` does not trigger if the link text is formatted as a link already such as when pasting from a browser.

Markdown syntax for hyperlinks _does_ work if link text is in plain text, such as pasting an incomplete URL (e.g. `ttps://www.google.com` rather than `https://www.google.com`) or clearing all formatting from the URL text.

### Steps to Reproduce Failure

1. Navigate to any URL in a browser.
2. Copy link from address bar.
3. Type `[Display Text](`
4. Paste URL after opening parenthesis.
5. Type closing parenthesis followed by a space.

Resulting text:
![Unformatted-markdown-hyperlink](https://github.com/MicrosoftDocs/msteams-docs/assets/8105393/3103738e-383e-4d1b-ae5b-1099d9f0d5d4)

### Expected Behavior

Markdown syntax triggers regardless of the format of link text.

### Note

While macOS supports pasting and matching formatting via _Paste and Match Style_ (`Cmd + Opt + Shift + V`), this doesn't prevent link formatting when pasting.

### Versions

macOS Sonoma 14.1.1
New Microsoft Teams: Version 23320.3107.2575.3762

**Comment by Prasad-MSFT** [comment]
@bigtrout3 - We are also able to repro this issue. We have added appropriate tag, so that concerned team can help further. 
Thanks!

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, please feel free to reopen it, if required.

**Comment by NigelDevs** [comment]
This issue still persists.

**Comment by DiskreetDev** [comment]
Issue still persists

**Comment by Rimann91** [comment]
Why was this closed if you were able to reproduce it? I see no explanation or resolution

**Comment by markthwain1797** [comment]
This is still a problem!

**Comment by violog** [comment]
2026, no fix will ever be there

**Comment by nickwalkmsft** [comment]
(Sorry, previous message was in reference to agent capabilities, not the compose box for users; I can't speak to the latter).
