### ISSUE TITLE
Can't set webhook in the new Team (use workflow) 

### ISSUE THREAD

**Issue by kravee** [MicrosoftDocs/msteams-docs#10102]
The document did not describe the solution for new teams 2023, how to set WEBHOOCK in Workflow
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 90ff2a84-a8bc-9259-d37d-622b102df75b
* Version Independent ID: e3b53e27-2946-189c-623b-9df704ea8f12
* Content: [Create an Incoming Webhook - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-incoming-webhook?tabs=dotnet)
* Content Source: [msteams-platform/webhooks-and-connectors/how-to/add-incoming-webhook.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/webhooks-and-connectors/how-to/add-incoming-webhook.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **surbhigupta**

**Comment by Meghana-MSFT** [comment]
Engineering team is working with the docs team to roll out a new article on how the customers can find the new Connector option under the Channel Settings section.

**Comment by Meghana-MSFT** [comment]
@kravee - Document has been updated with steps to create incoming webhooks in new Teams - https://learn.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-incoming-webhook?tabs=newteams%2Cdotnet#create-an-incoming-webhook

We are closing this issue, please feel free to reach out to us if you have any queries. Thank you.
