### ISSUE TITLE
Code snippets of TeamsJs V2 not working for getLocation and showLocation API

### ISSUE THREAD

**Issue by Jegadeesh-MSFT** [MicrosoftDocs/msteams-docs#10138]
Code snippets of TeamsJs V2 not working for getLocation and showLocation API,

**getLocation :**
It has incorrect closing brackets, using the code giving error like there is no callback function for getLocation and **output()** seems to be an irrelevant method for this snippet. Please replace with below code.

import {location} from "@microsoft/teams-js"

let locationProps = {"allowChooseLocation":true,"showMap":true};
if(location.isSupported()) {
    microsoftTeams.location.getLocation(locationProps, (error, location) => {
    // If there's any error, an alert shows the error message/code
    if (error) {
       if (error.message) {
           alert(" ErrorCode: " + error.errorCode + error.message);
       } else {
           alert(" ErrorCode: " + error.errorCode);
       }
    }
    console.log(JSON.stringify(location));
    });
}
else {/*Handle case where capability isn't supported */}

**showLocation:**
Using the code giving error like there is no callback function for showLocation and **output()** seems to be an irrelevant method for this snippet. Please replace with below code.

import {location} from "@microsoft/teams-js"

let location = {"latitude":17,"longitude":17};
if(location.isSupported()) {
    microsoftTeams.location.showLocation(location, (error, result) => {
                if (error) {
                      if (error.message) {
                             alert(" ErrorCode: " + error.errorCode + error.message);
                       } else {
                             alert(" ErrorCode: " + error.errorCode);
                       }
                }
            });
}
else {/*Handle case where capability isn't supported */}

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 37c38166-ea97-76c3-3c8a-ba32cd9a8f53
* Version Independent ID: 44bfd3b4-9b6a-f33e-3cb2-cf88fda01b84
* Content: [Integrate location capabilities - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?tabs=mobile%2Cteamsjs-v2#code-snippets)
* Content Source: [msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/device-capabilities/location-capability.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **surbhigupta**

**Comment by ChetanSharma-msft** [comment]
Hello @surbhigupta12 - Please help to update the documentation.
