### ISSUE TITLE
How to deal with inline pasted images?

### ISSUE THREAD

**Issue by ericrrichards** [MicrosoftDocs/msteams-docs#1013]
Something has changed with the way that this works.  In the past, I could use the Teams client to contact my bot, and then copy/paste a screenshot image into the chat, and the bot would receive a media attachment that could be downloaded.  

As of the past two weeks, when I do this, the contentUrl value in the attachment that is sent to my bot, for example https://smba.trafficmanager.net/amer/v3/attachments/0-eus-d6-e92d3c6069d8c5e73e95c8b8776c512e/views/original, doesn't work at all, and returns a 403 or a 401 error when I try to access it.

I've noticed that there is also a sibling text/html attachment, which has an img tag embedded within it, pointing to a different endpoint e.g. https://us-api.asm.skype.com/v1/objects/0-eus-d6-e92d3c6069d8c5e73e95c8b8776c512e/views/imgo\ .  This url only works if I happen to be in a browser that has the proper cookies cached for the user that pasted the image into the chat, and is also unavailable to my bot.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5307fe5c-a6f0-59e2-d125-69051ab58595
* Version Independent ID: ca3f41d9-1c2a-6cde-b780-61fec8f0fcb6
* Content: [Sending and receiving files from a bot - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/bots/bots-files)
* Content Source: [msteams-platform/concepts/bots/bots-files.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/bots/bots-files.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by nayanshah** [comment]
I don't have the documentation handy but Skype & MS Teams attachment URLs are secured by a JwtToken. So you need to pass the token to access those attachments (usually hosted on *.trafficmanager.net, *.skype.com)

```
var token = await new MicrosoftAppCredentials().GetTokenAsync();
httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
```

**Comment by ericrrichards** [comment]
Thanks Nayan, that was exactly what I was missing
