### ISSUE TITLE
Manifest v1.16 with option supportsAnonymousGuestUsers is not supported in Classic Teams

### ISSUE THREAD

**Issue by ChetanSharma-msft** [MicrosoftDocs/msteams-docs#10135]
Please add a note in the documentation that: "Manifest v1.16 with option supportsAnonymousGuestUsers is not supported in Classic Teams."

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2c5bc94a-3c95-aecc-a34d-d9771dc5e9bb
* Version Independent ID: 2c5bc94a-3c95-aecc-a34d-d9771dc5e9bb
* Content: [Build apps for anonymous user - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/build-apps-for-anonymous-user?tabs=javascript)
* Content Source: [msteams-platform/apps-in-teams-meetings/build-apps-for-anonymous-user.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/apps-in-teams-meetings/build-apps-for-anonymous-user.md)
* Service: **msteams**
* GitHub Login: @v-sdhakshina
* Microsoft Alias: **v-sdhakshina**

**Comment by Prasad-MSFT** [comment]
Hi @surbhigupta12 - Could you please help here to update the doc?
