### ISSUE TITLE
Unclear/deprecated examples

### ISSUE THREAD

**Issue by Jonatas4ndrade** [MicrosoftDocs/msteams-docs#10131]
Incoming webhook example still using "version"": ""1.0". It has been so far extremely confusing to find the correct format when sending
an adaptative card through an incoming webhook connection: I could not yet find if it should be a JSON format sending only the formated payload (as in the example, resulted on Bad Request) or a message with an AdaptiveCard attachment. please make it clear on example the correct format for the latest version.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 90ff2a84-a8bc-9259-d37d-622b102df75b
* Version Independent ID: e3b53e27-2946-189c-623b-9df704ea8f12
* Content: [Create an Incoming Webhook - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-incoming-webhook?tabs=dotnet)
* Content Source: [msteams-platform/webhooks-and-connectors/how-to/add-incoming-webhook.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/webhooks-and-connectors/how-to/add-incoming-webhook.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **surbhigupta**

**Comment by ChetanSharma-msft** [comment]
Hello @Jonatas4ndrade - Thanks for raising your query.
We will look into it and let you know the updates.
