### ISSUE TITLE
Document the lifetime of the authId? 

### ISSUE THREAD

**Issue by kafka-yu** [MicrosoftDocs/msteams-docs#10144]
I heard that "AuthId" param has max 2 mins lifetime, can you write it down in this wiki page?
Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b608448b-3dd7-d5be-128c-da2859067140
* Version Independent ID: b608448b-3dd7-d5be-128c-da2859067140
* Content: [Use external OAuth providers - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-oauth-provider)
* Content Source: [msteams-platform/tabs/how-to/authentication/auth-oauth-provider.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/tabs/how-to/authentication/auth-oauth-provider.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **surbhigupta**

**Comment by Prasad-MSFT** [comment]
@kafka-yu - Thanks for raising this. We will check this with engineering team and will update the doc accordingly.

**Comment by Prasad-MSFT** [comment]
Hi @surbhigupta12 - Could you please help here to add a note in [this](https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-oauth-provider) documentation mentioning that "The auth ID param is valid for the lifetime of the auth session which has a default timeout of 120 seconds (i.e. 2 minutes)"
