### ISSUE TITLE
Authentication does not work in teams app with tabs on mobile using v1.5.2(latest)

### ISSUE THREAD

**Issue by JanOnGit** [MicrosoftDocs/msteams-docs#1015]
Hi there,
I just created an Azure Web-App application (.NETCore 2.2.0, MVC) with tabs for teams with authentication. I implemented a silent authentication and SSO like in this example (https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/authentication/auth-silent-aad). On teams desktop the authentication works as expected. On teams mobile the authentication fails (same application). The mobile client goes to login page (adsf) but never closes and it doesn't return the notifySuccess result. I created the application exactly for the silent authentication and SSO on mobile, to test how it works. I use MicrosoftTeams SDK v1.5.2 with ADAL v1.0.17. Desktop client Microsoft Teams Version 1.2.00.26774 (64-bit). It was last updated on 10/8/19. Mobile client Version 1416/1.0.0.2019092603 / Calling Version 2019.32.01.7.

thanks

**Comment by Gousia-MSFT** [comment]
@JanOnGit Thanks for reporting it. We have raised a bug for this and we are tracking it internally.

**Comment by arpitgupta19** [comment]
@JanOnGit Please confirm if this issue is happening on both android and iOS ?

**Comment by VikrantSingh01** [comment]
@JanOnGit : Hey, Do you see this on both iOS and Android ?  Also can you share the App Manifest ?
