### ISSUE TITLE
Feedback - Teams adaptive cards only supports up to v1.5 while this requires v1.6 for choices.data property

### ISSUE THREAD

**Issue by v-preethah** [MicrosoftDocs/msteams-docs#10155]
Validate the feedback and confirm if "Teams adaptive cards only supports up to v1.5 while this requires v1.6 for choices.data property"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c8cc6c1f-7946-e074-e2c3-da2d24e0acc6
* Version Independent ID: c8cc6c1f-7946-e074-e2c3-da2d24e0acc6
* Content: [People Picker in Adaptive Cards - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/people-picker?tabs=desktop)
* Content Source: [msteams-platform/task-modules-and-cards/cards/people-picker.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/task-modules-and-cards/cards/people-picker.md)
* Service: **msteams**
* GitHub Login: @Rajeshwari-v
* Microsoft Alias: **surbhigupta**

**Comment by ChetanSharma-msft** [comment]
Hello @v-preethah - Thanks for raising the issue for the anonymous feedback.
We will look into it and take the action accordingly.

**Comment by v-preethah** [comment]
Hi @Meghana-MSFT 

Can you please confirm if choices.data property requires v1.6 of Teams Adaptive cards, or if it's supported in v1.5 as well?

As per the feedback, the user raised the concern on v.15 not supporting choices.data property.

Awaiting your response.

Thank you!

**Comment by Meghana-MSFT** [comment]
It is supported for v1.5 as well.

**Comment by v-preethah** [comment]
[like]  Preetha H (LTIMINDTREE LIMITED) reacted to your message:
________________________________

**Comment by v-preethah** [comment]
Hi Meghana,

Can you please confirm if the support is extended for v1.6?

**Comment by Meghana-MSFT** [comment]
Adaptive card is no longer dependent on the schema version so it will work with 1.2, 1.5 and 1.6 as well. The document will be updated accordingly.

**Comment by v-preethah** [comment]
@Meghana-MSFT As confirmed with Wajeed, no doc update required as of now. Could you please confirm on the same?

**Comment by Meghana-MSFT** [comment]
We are closing this issue for now, please feel free to reach out to us if you have any queries.

**Comment by areis422** [comment]
The documentation on Msft says Teams supports 1.5 and below, but when you set a card version to 1.5, you get the "We're sorry, this card couldn't be displayed" error

**Comment by Meghana-MSFT** [comment]
@areis422 - Similar issue is being tracked here https://github.com/MicrosoftDocs/msteams-docs/issues/9801
