### ISSUE TITLE
Feedback - Connector configuration in demo tenant public ring not working

### ISSUE THREAD

**Issue by v-preethah** [MicrosoftDocs/msteams-docs#10160]
When tested in demo tenant public ring of New Teams, we are getting the following error while configuring the connector.

![image](https://github.com/MicrosoftDocs/msteams-docs/assets/117343020/4ec909e2-6da6-48f9-86b0-504cdd38d1a2)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 90ff2a84-a8bc-9259-d37d-622b102df75b
* Version Independent ID: e3b53e27-2946-189c-623b-9df704ea8f12
* Content: [Create an Incoming Webhook - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-incoming-webhook?tabs=dotnet)
* Content Source: [msteams-platform/webhooks-and-connectors/how-to/add-incoming-webhook.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/webhooks-and-connectors/how-to/add-incoming-webhook.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **surbhigupta**

**Comment by Prasad-MSFT** [comment]
Hi @v-preethah - When we are trying to create an incoming webhook connector in New Teams, we are only getting options to create workflows as below:
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/62237649/bef74620-0980-47b6-9901-ffcd625c727b)

![image](https://github.com/MicrosoftDocs/msteams-docs/assets/62237649/2e92f7fe-5123-4bcb-8068-00355dd5da50)

Could you please let us know the steps via which you tried to configure the connector?
