### ISSUE TITLE
Feedback - There is no up-to-date learn documentation

### ISSUE THREAD

**Issue by v-preethah** [MicrosoftDocs/msteams-docs#10165]
Feedback received - There is no up-to-date learn documentation

Help validate if there are any updates to the docs.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 41c93c1e-c426-148c-a545-f8bd5b3763ff
* Version Independent ID: afcc83c4-12c0-bab6-1cec-61ac463b4f60
* Content: [Add Teams tab to SharePoint - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/tabs-in-sharepoint)
* Content Source: [msteams-platform/tabs/how-to/tabs-in-sharepoint.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/tabs/how-to/tabs-in-sharepoint.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **surbhigupta**

**Comment by ChetanSharma-msft** [comment]
Hello @v-preethah - Thanks for raising this anonymous feedback.
We will look into it and let you know the updates.

**Comment by ChetanSharma-msft** [comment]
Raised the documentation bug for this issue.

**Comment by v-preethah** [comment]
As per the discussion with doc PM closing the issue.
