### ISSUE TITLE
Personal Tab - Context

### ISSUE THREAD

**Issue by icelandgrecian** [MicrosoftDocs/msteams-docs#1017]
We are looking at implementing our personal tabs so it works on a mobile device, however we are seeing issues with the context in the preview mode, where many of the properties set on the desktop/web version are coming back as null or are missing (we are checking on iOS).

The properties set on the web version that are null on the mobile device are entityId, subEntityId, sessionId, loginHint, 

The properties set on the web version that are missing on the mobile device are isFullScreen, tenantSKU, userLicenseType, appSessionId, userPrincipalName

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f5dd248-ec28-4bc2-32e6-2e6072a5eedf
* Version Independent ID: 4c45b690-0a35-d460-54fb-c0b61a2c5e8c
* Content: [Tabs on mobile - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/design/framework/tabs-mobile)
* Content Source: [msteams-platform/resources/design/framework/tabs-mobile.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/resources/design/framework/tabs-mobile.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Gousia-MSFT** [comment]
@icelandgrecian This is a known issue. We have raised a bug for this and we are looking into this internally.
