### ISSUE TITLE
How to  add new Tab from the direct teams app from the Teams Site/desktop

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#10179]
Copied bug from: https://github.com/OfficeDev/TeamsFx/issues/10642 

**Details from original post:**
I have successfully published an app on Teams, which currently features four tabs.
Now, I'd like to add a new tab directly from the Teams site. How can I go about adding this new tab?---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b743e43d-95cc-3d1e-b142-31a16369f97e
* Version Independent ID: b743e43d-95cc-3d1e-b142-31a16369f97e
* Content: [Teams Toolkit Overview - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/toolkit/teams-toolkit-fundamentals)
* Content Source: [msteams-platform/toolkit/teams-toolkit-fundamentals.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/teams-toolkit-fundamentals.md)
* Service: **msteams**
* GitHub Login: @zyxiaoyuer
* Microsoft Alias: **zhany**

**Comment by Vaibhav-MSFT** [comment]
Thanks for raising your issue. We will check this at our end and will update you accordingly.

**Comment by Vaibhav-MSFT** [comment]
Hi, as of now the ability to add a tab directly to teams app from teams site might not be available, process can be achieved by adding directly through teams app. 
To add a tab directly to an app on Teams, you typically follow these steps:
Open Teams: Open the Teams desktop application or access Teams through the web version.
1) **Navigate to the app**: Locate and select the app to which you want to add a tab.
2) **Select a Channel or Chat:** Depending on the app, navigate to a specific channel or chat where you want to add the tab.
3) **Click on the '+' icon:** Look for the '+' icon, usually near the top of the channel or chat interface. Click on it to add a new tab.
4) **Choose a tab type:** Select the type of tab you want to add from the available options.
5) **Configure the tab:** Provide the necessary information or configure settings for the tab, depending on the type you selected.
6) **Save or Add:** After configuring the tab, save or add it to complete the process
Please refer to the [documentation](https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs?tabs=desktop%2Cdesktop1%2Cpersonal) for more details.
