### ISSUE TITLE
This page has no documentation for how to trigger configuration in response to Dialog submission

### ISSUE THREAD

**Issue by AE-MS** [MicrosoftDocs/msteams-docs#10174]
When I raised issue #9632, it highlighted that the link to the documentation for how configuration responses should work was incorrect. That issue was resolved with PR #10150, which I suppose technically does resolve it in that the link is no longer incorrect. However, that PR removed the reference to configuration responses altogether -- can you add documentation describing how configuration responses should work with Message Extensions?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8fb0c2d8-f880-c260-d0be-6b9467e47f8c
* Version Independent ID: 7820ffc9-5260-c818-f5fb-672801a67d00
* Content: [Respond to the dialog submit action - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/action-commands/respond-to-task-module-submit?tabs=dotnet%2Cdotnet-1)
* Content Source: [msteams-platform/messaging-extensions/how-to/action-commands/respond-to-task-module-submit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/messaging-extensions/how-to/action-commands/respond-to-task-module-submit.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **anclear**

**Comment by Prasad-MSFT** [comment]
Thanks @AE-MS  for raising this issue. We will check this at our end and will update the page accordingly.

**Comment by Prasad-MSFT** [comment]
Hi @surbhigupta12 - Could you please help here?
