### ISSUE TITLE
Incoming Webhook Failing with Webhook message delivery failed with error: Microsoft Teams endpoint returned HTTP error 403 with ContextId

### ISSUE THREAD

**Issue by tcitsoftware** [MicrosoftDocs/msteams-docs#10178]
The incoming webhook on another tenant seems to work fine with exactly the same code but fails in another tenant with the message below.

Error message: 

`Webhook message delivery failed with error: Microsoft Teams endpoint returned HTTP error 403 with ContextId tcid=0,server=msgapi-production-cin-azsc4-1-64,cv=h3ya2/H5Fk6NjffrwlaWTQ.001=2..`

Test code used for functionality.

```
var options = new RestClientOptions("https://XXXX.webhook.office.com")
{
  MaxTimeout = -1,
};
var client = new RestClient(options);
var request = new RestRequest("/webhookb2/XXXX/IncomingWebhook/XXX", Method.Post);
request.AddHeader("Content-Type", "application/json");
var body = @"{""text"": ""This is a test""}";
request.AddStringBody(body, DataFormat.Json);
RestResponse response = await client.ExecuteAsync(request);
Console.WriteLine(response.Content);```
```[tasklist]
### Tasks
```

**Comment by Vikram-MSFT** [comment]
Hii @tcitsoftware Thanks for raising the issue. we will create all the repro steps and get back to you.

**Comment by ChetanSharma-msft** [comment]
Hello @tcitsoftware - Could you please confirm if same webhook URL is working from Postman or not?

**Comment by tcitsoftware** [comment]
The code is being tested from postman and is working for one instance but not for the other.

**Comment by Vikram-MSFT** [comment]
Hello @tcitsoftware we can only run one incoming webhook url will run only with one tenant, but won't works with another tenant.

**Comment by tcitsoftware** [comment]
Hi, I am aware. What I was referring to was that the when I run the payload using the incoming web hook for the other tenant it works. Running the same payload using the incoming web hook generated for the other tenant does not work. For the purposes of this issue we can ignore the other tenant since I was mentioning it to indicate that there is a working example with the same payload except for the difference in URL.

**Comment by ChetanSharma-msft** [comment]
> The code is being tested from postman and is working for one instance but not for the other.

Hello @tcitsoftware - Could you please verify if the webhook URL is properly configured for the tenant where you are getting the error. We have tried from postman but it's working for us.

**Comment by tcitsoftware** [comment]
> > The code is being tested from postman and is working for one instance but not for the other.
> 
> Hello @tcitsoftware - Could you please verify if the webhook URL is properly configured for the tenant where you are getting the error. We have tried from postman but it's working for us.

Hi, It is since the same call  using a different webhook URL on another instance is working.

**Comment by tcitsoftware** [comment]
[Desktop.zip](https://github.com/MicrosoftDocs/msteams-docs/files/13896552/Desktop.zip)


Powershell export from Postman with a working and non working sample. you can run these in powershell to see the difference.

**Comment by NutelsGleb** [comment]
I also have a problem with webhooks. Today I created a new channel  and set webhook, I tested and it works after few hours same request has status 200 but response contain text: _Webhook message delivery failed with error: Microsoft Teams endpoint returned HTTP error 403 with ContextId tcid=0,server=msgapi-production-weu-08-0,cv=KeE88Z+420eDjuR4YmQqLg.001=2.._

**Comment by Vikram-MSFT** [comment]
Hello @tcitsoftware  ICM has been raised for this issue, once we get the updates we will  let you know.

**Comment by tcitsoftware** [comment]
> Hello @tcitsoftware ICM has been raised for this issue, once we get the updates we will let you know.

@Vikram-MSFT - Tried with a private channel and it's working. Do the incoming webhooks only with private channels and not with standard channels?

**Comment by tcitsoftware** [comment]
Turns our deleting the entire webhook and creating it again sorted the issue for all three types of channels.
