### ISSUE TITLE
Failed to upload custom app: Error code: UnknownTeamsAppManifestExceptionType

### ISSUE THREAD

**Issue by dhilip-tdk-hms** [MicrosoftDocs/msteams-docs#10188]
Failed to add app from developer portal and upload custom app. shows below error 
 
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/143158959/b5a47701-7586-4f13-983e-78b8bb085839)

Teams App ID : 61c7dda6-7970-490d-b322-7e3008280101

**Comment by Prasad-MSFT** [comment]
Hi @dhilip-tdk-hms , thanks for raising your issue. Could you please provide the app manifest zip package which you are trying to upload along with repro steps (whether you are using developer portal to upload app zip/ did you create the app within dev portal itself)?

**Comment by dhilip-tdk-hms** [comment]
Yes, I created App in dev portal itself.

I tried both. I tried preview in Teams in MacBook Pro M1 chip, It installed the app and then crashes frequently when I go to the installed app's Personal Tab.

Still I am facing the above issue from Developer portal in Teams Web app
Ubuntu 22.04.3 LTS Chrome Version 120.0.6099.129 (Official Build) (64-bit)

**Comment by dhilip-tdk-hms** [comment]
Regarding the ZIP file Can I upload here or Can you pull it from your end 
using Teams App ID : 61c7dda6-7970-490d-b322-7e3008280101

**Comment by Prasad-MSFT** [comment]
> @Prasad-MSFT Regarding the ZIP file Can I upload here or Can you pull it from your end using Teams App ID : 61c7dda6-7970-490d-b322-7e3008280101
> 
> **update:** one more thing is this was working fine till last Friday (Jan 5)

Could you please upload here?

**Comment by dhilip-tdk-hms** [comment]
Hi @Prasad-MSFT , I am not sure why,how but outline image had 0 byte file that caused the issue, uploaded again and now it is working. Thanks :sweat_smile:

**Comment by Prasad-MSFT** [comment]
Thanks for informing, glad to hear that it is working fine now. We are closing this issue for now. Please feel free to reopen if required. 

Thanks!
