### ISSUE TITLE
Attached Manifest app package in the documentation is not working

### ISSUE THREAD

**Issue by ChetanSharma-msft** [MicrosoftDocs/msteams-docs#10185]
Attached Manifest app package in the documentation is not working.

Tried in v-id:

![image](https://github.com/MicrosoftDocs/msteams-docs/assets/59052547/d95cc099-2a40-4aa3-843f-45aeea1c2b56)

Tried in Demo tenant: 
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/59052547/6d002c64-5d1a-44a9-8dbc-a9fcf50d511f)

Also, if we try to access below link, we are getting error:
https://YOUR_TENANT_NAME.sharepoint.com/sites/apps/AppCatalog/Forms/AllItems

![image](https://github.com/MicrosoftDocs/msteams-docs/assets/59052547/255a1e0e-6009-4208-8675-061343c88175)

Reference doc link: 
https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/tabs-in-sharepoint#use-teams-tab-in-sharepoint

Is there any prerequisites to access it?

3) There is no step by step guide (SBS) mention to create the sample code. (Sample code is linked)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 41c93c1e-c426-148c-a545-f8bd5b3763ff
* Version Independent ID: afcc83c4-12c0-bab6-1cec-61ac463b4f60
* Content: [Add Teams tab to SharePoint - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/tabs-in-sharepoint)
* Content Source: [msteams-platform/tabs/how-to/tabs-in-sharepoint.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/tabs/how-to/tabs-in-sharepoint.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **surbhigupta**

**Comment by ChetanSharma-msft** [comment]
Gone through as the part of this feedback: https://github.com/MicrosoftDocs/msteams-docs/issues/10165

**Comment by v-preethah** [comment]
This issue is being tracked via [Pull Request #10317](https://github.com/MicrosoftDocs/msteams-docs/pull/10317)
