### ISSUE TITLE
Teams Bot Not Responding

### ISSUE THREAD

**Issue by Cbeddall** [MicrosoftDocs/msteams-docs#10190]
Hello, 

I followed the documentation and have everything implemented successfully however in the documentation it provides a challenge where the bot responds to commands like "Show Welcome" - My bot simply does not do anything when ask it any of the suggested commands, am i doing something wrong ? 

Any Help would be highly appreciated 

Thanks

**Comment by Vikram-MSFT** [comment]
Hello @Cbeddall   - Thanks for raising your query.
Please make sure that whatever the commands you have added to your Manifest file are properly handled in your code side.
Once you send any command, it will call on message activity, there you need to write switch case to handle all configured commands. For the reference you can go through this documentation https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/command-bot-in-teams?tabs=jsts1%2Cjs%2Cjsts2
