### ISSUE TITLE
[Microsoft Toolkit] CI/CD template page is refering to a restricted Github repo access

### ISSUE THREAD

**Issue by michaelmaillot** [MicrosoftDocs/msteams-docs#10195]
Hello,

In the [Prepare credential](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/use-CICD-template.md#prepare-credentials) part of the article, the note below the table is refering to a restricted Github repo access:

>Currently, service principal for Azure is used in CI/CD workflows, and to create Azure service principals for use, refer to [here](https://github.com/devdiv-azure-service-dmitryr/teamsfx-docs/blob/main/V5-doc-update/cicd.md#how-to-create-azure-service-principals-for-use).

**Comment by Prasad-MSFT** [comment]
Hi @surbhigupta12 - Could you please help here?

**Comment by yukun-dong** [comment]
@v-vanisreeth   Changing the link from (https://github.com/devdiv-azure-service-dmitryr/teamsfx-docs/blob/main/V5-doc-update/cicd.md#how-to-create-azure-service-principals-for-use) to (#how-to-create-azure-service-principals-for-use) should fix this issue.
