### ISSUE TITLE
Message extension action preview sample app doesn't work

### ISSUE THREAD

**Issue by a1exwang** [MicrosoftDocs/msteams-docs#10209]
Steps:
1. Downlaod the nodejs sample app from here https://learn.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/action-commands/respond-to-task-module-submit?tabs=dotnet%2Cdotnet-1#code-sample
1. Open in Teams Toolkit 
2. F5
3. Input some text in the form and click submit
4. Click Send
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/9698542/48793d7b-b39c-40dc-b91e-98fbd4b210be)
5. There is an error:
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/9698542/67a10cc2-ffab-4609-8440-87c828606f2b)

The "Edit" button works so the problem shouldn't be my bot crashing or similar reasons. When the error appears, my bot doesn't receives and HTTP request

Tried multiple times and cannot solve the problem.

**Comment by Vaibhav-MSFT** [comment]
Hello @a1exwang,
Thanks for reporting your issue. We will test this and update you soon.

**Comment by Vaibhav-MSFT** [comment]
We are able to repro that issue, we have raised bug for the same. We will inform you once we get any update.

**Comment by Pawank-MSFT** [comment]
We have tested this sample and it is working fine in Teams channel scope, documentation is already specify we'll move this into top. Could you please check this into Teams channel scope.
