### ISSUE TITLE
Message extension SSO config sample app doesn't work

### ISSUE THREAD

**Issue by a1exwang** [MicrosoftDocs/msteams-docs#10208]
I want to try the configuration feature in message extension and tried the `Teams Message extension auth and config` Node.js sample app in [this document](https://learn.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/search-commands/respond-to-search?tabs=dotnet#code-sample). It seems to me the app doesn't work. The document doesn't mention what is the expected behavior so I'm not sure whether it is the app's issue or my understanding is wrong.

Steps:
1. Download the sample app and open with Teams Toolkit
2. F5
3. Input something in the search ME
4. Click "Sign in"
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/9698542/1a2da115-795e-4dd6-846c-74c019e3509a)
And nothing happens. This is the first issue.

5. Then click "Compose" action button.
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/9698542/f8ae3b7b-a840-4ad6-bf13-671824e6e32a)
This is the second issue.

Could you help me understand

1. How to trigger the display of configuration page. Is it triggered from an action command or search command or what?
1. How to render a configuration page?
1. What user interaction triggers my `handleTeamsMessagingExtensionConfigurationSetting` callback?

**Comment by ChetanSharma-msft** [comment]
Hello @a1exwang - Thanks for raising your query.
We will look into it and let you know the updates.

Meanwhile, could you please with below manual steps?
https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/msgext-search-sso-config/nodejs#run-the-app-manually-uploading-to-teams

**Comment by a1exwang** [comment]
Tested with the manual steps (The manual steps are too complicated and maybe I configured something wrong)

The bot reports an error when I click "Compose" button or search something
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/9698542/ae92fa14-c86a-4f90-9c8a-047040a0f835)

**Comment by Prasad-MSFT** [comment]
Yes @a1exwang - We are able to repro this issue at our end using Teams toolkit. We are checking this internally with team and will raise bug accordingly and will update you on the same. Thanks!

**Comment by Prasad-MSFT** [comment]
Hi @a1exwang - We tested [this sample](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/msgext-search-sso-config/nodejs#run-the-app-manually-uploading-to-teams) locally by making additional change in configuration as below and it worked successfully.
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/62237649/d5926844-35e3-4d24-bf30-b3919866fcf2)

Results:
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/62237649/8a848256-5b19-4936-b465-2f44bdb69e6d)

![image](https://github.com/MicrosoftDocs/msteams-docs/assets/62237649/34f65766-d020-47f7-a675-70a71da67541)

![image](https://github.com/MicrosoftDocs/msteams-docs/assets/62237649/7876d2b1-2a47-41f8-ad4c-521967baecff)

Could you please try the same and let us know if it works?
