### ISSUE TITLE
User consent popup not showing

### ISSUE THREAD

**Issue by sschoeb** [MicrosoftDocs/msteams-docs#10218]
In our effort to start using SSO in out teams bot, we figured out that whenever we request a new Token using an oauthCard, we run into the following UX issue:

We see the following consent request in teams:
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/2493698/14f4e6af-bfa8-4c70-9064-0e9ec03d15e9)

When clicking on "Weiter", the button gets disabled but nothing else happens and the user is lost. So there is no popup (as we see when using the web version). 

I'm using the following Teams-Desktop client: 23320.3027.2591.1505.
Client-Version: 49/23113028720

**Comment by ChetanSharma-msft** [comment]
Hello @sschoeb - Thanks for raising your query.
We will look into it and let you know the updates.

**Comment by Meghana-MSFT** [comment]
Apologies for the delay, we checked this at our end using https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/bot-conversation-sso-quickstart/js. By clicking on continue button, the login is successful.

![image](https://github.com/MicrosoftDocs/msteams-docs/assets/81138249/574b4c82-1454-4b54-84ea-592e8b65af04)
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/81138249/e877193c-90a1-4c5e-948a-0fccfbb4d1a9)

Could you please let us know if you are still facing this issue?

**Comment by sschoeb** [comment]
@Meghana-MSFT yes we do still face this issue. Do you need a video or any other information to work on this issue? make sure you do not try it only once but multiple times.

Could you reopen this issue?

**Comment by Meghana-MSFT** [comment]
We did check this multiple times, could you please share video of this.

**Comment by Meghana-MSFT** [comment]
Could you please share video of this issue.
