### ISSUE TITLE
User consent request does disappear after a certain time

### ISSUE THREAD

**Issue by sschoeb** [MicrosoftDocs/msteams-docs#10217]
In our effort to start using SSO in out teams bot, we figured out that whenever we request a new Token using an oauthCard, we run into the following UX issue:

As the user needs to give consent, in teams the following message is shown:
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/2493698/f6050c50-7236-48e0-8d46-7f77dec36899)

This message is fine (even though it is a bit small), but it disappears after a certain amount of time. This leaves the user in a confusing state as he does not have any option to click. 

You should not remove this message as long as the user does not actively refuses to give consent. 

I'm using the following Teams-Desktop client: 23320.3027.2591.1505.
Client-Version: 49/23113028720

**Comment by Meghana-MSFT** [comment]
Thank you for reporting this, we will check this and get back to you.

**Comment by Meghana-MSFT** [comment]
Apologies for the delay, we checked this at our end using https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/bot-conversation-sso-quickstart/js and please note that the consent request disappears after few minutes. However, if you send a login prompt or try to login again, the consent request reappears.

**Comment by sschoeb** [comment]
@Meghana-MSFT thanks for your reply. Based on your reply, could you tell me how a perfect UX should look like?

For me see something like this:
1. The bot does inform the user that as a next step we have to authenticate (as you cannot just throw in this authentication.. a normal, not techi-user, will not understand it...). 
2. The bot sends the Authentication Request
3. teams shows the message and the button the user has to click

It is absolutely a usecase that the user does right away click that button (for whatever reason, maybe he wants to ask a coworker if this is normal, maybe he just want to grab a coffee...). And after a while the button is gone. We do not have any chance to know that and the user is just there with the information that he should authenticate, but there is nothing how he could authenticate. How is that a good UX? 

Would be great if you could explain us, how microsoft thinks we should build that, so that also a user without any technical background will understand it in every case (think about breaks in between the convesration!)

**Comment by Meghana-MSFT** [comment]
We will share above query with engineering team and get back to you.

**Comment by Meghana-MSFT** [comment]
We got below response from engineering team - 

Yes, the bot can post a message explaining that they should finish SSO before sending the OAuthCard request. 
There is a timeout for the consent request prompt of 120s or 2 minutes, after which it clears. Unless user interacts with the bot again/send a message to the bot, Bot SSO request would not trigger. 
Would recommend suggesting option provided above first and if that does not help,
another (more involved) option is to hold the conversation reference for each user on first user interaction, and if the user token is not received for more than 2 minutes, bot can try re-sending OAuth card to that conversation.

**Comment by sschoeb** [comment]
@Meghana-MSFT Is this what the engineering team thinks is the perfect UX? So the conversation would look something like this:

Bot: "You'll see a small popup you have to click to give consent. But hurry up, it will be gone in 2 minutes. If you need to see the message again, just write me again". 

If you compare this to:
Bot: "You'll see a small popup you have to click to give consent.". 

So what do you think is the better UX and is easier to understand for the user? 

Then the second solution: 
Sure I can keep the reference and go into an endless loop of sending an OAuth card every 120 seconds... but I guess every engineer should know without any further explanation, that this is not a solution. Please tell me if you seriously think otherwise.

I would really appreciate if you could get back to the engineering team and ask again, how the expected UX/conversation should look like and maybe also for the reason on why this message clears after 120 seconds (I absolutely do not see a reason for that).

Thanks.

**Comment by Meghana-MSFT** [comment]
We have the following input from engineering team if the UX is a deal breaker and if you're fine with requiring consent every time user token is needed, you can send the regular Sign in card, The Bot Fx and/or AI SDK would send Sign in card if you leave the Token Exchange URL field blank in the Azure Bot's OAuth Connection.

**Comment by sschoeb** [comment]
@Meghana-MSFT thanks for your feedback and the additional input.

Could you ask back to the engineering team, how "requiring consent every time" is considered a good UX? Guess that should already answer the question if this is an option right? :-)

So my initial question remains: What would be the recommended solution of the engineering team to have the best possible UX and what exactly is the idea of this disappearing message (as it just adds confusion but nothing else...)? 

Thanks for asking back again.

**Comment by Meghana-MSFT** [comment]
We have below response from engineering team

If they're following public samples and using Bot Fx SDK for Auth, then acquiring user token from Teams client after the first time, should be rarely needed. This is because the Bot Framework token service manages the exchanged token and refreshes it as well.
 
`what exactly is the idea of this disappearing message (as it just adds confusion but nothing else...)? ` 
SSO requests are ephemeral by design and user would be able to decide and respond within 2 minutes for taking the simple action of clicking the Continue button.

**Comment by sschoeb** [comment]
I totally agree with the engineering team that this request is not shown a lot and that clicking it is a easy/simple/fast task. 

But still my questions remain:

- Why this request is only shown for 2 minutes? I think the request (from the user point of view) does start with the click on this message, which then shows the popup (actually the same as if you click on a website on a "Sign in with Microsoft Login"-Button).
- Having this message disappearing after a while adds a lot more complexity to the conversation which is a worse experience for everyone (also the once that click within 2 minutes). 

I'm totally aware, that most of the people will click immediately on this message. But you have to understand that your tool is also used by a lot of people that are not engineers or otherwise technical. There may questions arise like "Why I have to do that here?".. then they maybe ask someone else just to make sure they are not doing something wrong and voila.. message gone.. confusion here. 

Other example would be that someone starts the bot, then switches the task (he just gets a phone call or whatever...).. voila.. message gone - user lost.

So again: 
If we want to build something bulletproof, we would need to add an explanation message that if the message is not there anymore he can click again a button to get the message which I think all of us agree is not a user experience we would expect within microsoft teams, right?

**Comment by Meghana-MSFT** [comment]
Please find the below response - 

This is a valid concern, and we will be revisiting with our design team. Meanwhile, we still recommend the bot to post a message initially before sending the OAuthCard request, explaining that user will be getting an SSO request and should finish SSO to proceed to using the bot.

**Comment by Jocelynncanzoneri** [comment]
There is a user of apple phone that ip address is always here with me.
Then there is an apple phone that lingers picking up my data.  Filling up
my phone wheres my account.  And why do you allow.  Can you tell.
