### ISSUE TITLE
User consent request does not always appear

### ISSUE THREAD

**Issue by sschoeb** [MicrosoftDocs/msteams-docs#10219]
In our effort to start using SSO in out teams bot, we figured out that whenever we request a new Token using an oauthCard, we run into the following issue:

We would expect to behave every platform exactly the same. But this is what we figured out in our tests:

Teams Desktop Client:
User consent request only sometimes appears

Teams Web Client:
User consent request always appears

Teams Android Client:
User consent request never appears

I'm everywhere on the latest version using the same app and the same tenant.

**Comment by Meghana-MSFT** [comment]
Thank you for reporting this, we will check this and get back to you.

**Comment by Meghana-MSFT** [comment]
Apologies for the delay, we checked this at our end using https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/bot-conversation-sso-quickstart/js. We see that the consent request always appears in web/desktop. Could you please confirm if you are still facing this issue?

**Comment by sschoeb** [comment]
@Meghana-MSFT Have you also tried it on android and ios? On the desktop client it just sometimes does not appear. Do you need a video which proves that?

Could you please reopen this issue. Kind of hard not having a feedback from you for 2 months and then after 3 days right away closing the issue.

**Comment by Meghana-MSFT** [comment]
Could you please share the video.

**Comment by Meghana-MSFT** [comment]
Could you please share video of this issue.
