### ISSUE TITLE
Are we able to add customized attributes to the iframe that opens the Tab app?

### ISSUE THREAD

**Issue by kafka-yu** [MicrosoftDocs/msteams-docs#10214]
Hi team,
Are we able to add customized attributes to the iframe that opens the Tab app? For example for the 3rd party cookie blocking change in Chrome, we consider adding some attributes to the iframe. Is it feasible?

<img width="553" alt="image" src="https://github.com/MicrosoftDocs/msteams-docs/assets/3942409/068ca990-240d-4737-aad6-bf4a55613d8e">

**Comment by Meghana-MSFT** [comment]
We will check this and get back to you.

**Comment by Meghana-MSFT** [comment]
Could you please let us know what attributes are you trying to add? If it's allow-storage-access-by-user-activation, then it's being already discussing here - https://github.com/OfficeDev/microsoft-teams-library-js/issues/1460#issuecomment-1884755439
