### ISSUE TITLE
Targeted notifications no longer working for anonymous users 

### ISSUE THREAD

**Issue by Hans-Zietsman** [MicrosoftDocs/msteams-docs#10215]
Targeted notifications have stopped working for anonymous users in Teams meetings. 

I can consistently repo this in 'scheduled' and 'meet now' meetings. There is no error returned from the API, it just does not do anything. Here are some test results:
 
Invalid IDs return "Failed to decrypt user id"
IDs for users in another meeting return '{"error":{"code":"ServiceError","message":"Unknown"}}'
IDs for non-anonymous users in the meeting return "{}" and open the targeted notification.
IDs for anonymous users in the meeting return "{}", but DO NOT open the targeted notification.

The first three are what I would expect, but the fourth one suggests that there is something wrong with the API.
 
Meeting id: 'MCMxOTptZWV0aW5nX016aGlPRFUwWWpBdE56YzJZaTAwTmpNekxUazJZMll0T1RBMU1qbGtPR1k1TldVeUB0aHJlYWQudjIjMA=='
Tenant id: '714d06c7-372c-488b-83fb-dd1b1fe3724a'

This is an experience that used to work. The anonymous user experience continues to deteriorate with apps not working in the side panel either.  

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2c5bc94a-3c95-aecc-a34d-d9771dc5e9bb
* Version Independent ID: 2c5bc94a-3c95-aecc-a34d-d9771dc5e9bb
* Content: [Build apps for anonymous user - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/build-apps-for-anonymous-user?tabs=javascript)
* Content Source: [msteams-platform/apps-in-teams-meetings/build-apps-for-anonymous-user.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/apps-in-teams-meetings/build-apps-for-anonymous-user.md)
* Service: **msteams**
* GitHub Login: @v-sdhakshina
* Microsoft Alias: **v-sdhakshina**

**Comment by ChetanSharma-msft** [comment]
Hello @Hans-Zietsman - Could you please provide repro steps and code snippets you have used, so that we can try to repro it.

**Comment by Hans-Zietsman** [comment]
Hello

Please see the recording link<https://share.cleanshot.com/kswDm9lr> for steps to repro with the Kunjani app. In this case, the anonymous user was meant to receive the same targeted popup notification but got nothing. As long as the targeted user is anonymous, you will be able to repro it using the steps and code sample here<https://learn.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/in-meeting-notification-for-meeting?tabs=desktop>.

From: ChetanSharma-MSFT ***@***.***>
Date: Tuesday, 16 January 2024 at 17:48
To: MicrosoftDocs/msteams-docs ***@***.***>
Cc: Hans Zietsman ***@***.***>, Mention ***@***.***>
Subject: Re: [MicrosoftDocs/msteams-docs] Targeted notifications no longer working for anonymous users (Issue #10215)

Hello @Hans-Zietsman<https://github.com/Hans-Zietsman> - Could you please provide repro steps and code snippets you have used, so that we can try to repro it.

**Comment by Hans-Zietsman** [comment]
Hello

Thank you. I am aware and have implemented all of the above. Targeted notifications to Anonymous users used to work in live published app, but not working anymore. Are you able to receive a targeted notification as an anonymous user using the steps/ documentation shared?

From: Vikram-MSFT ***@***.***>
Date: Wednesday, 17 January 2024 at 11:03
To: MicrosoftDocs/msteams-docs ***@***.***>
Cc: Hans Zietsman ***@***.***>, Mention ***@***.***>
Subject: Re: [MicrosoftDocs/msteams-docs] Targeted notifications no longer working for anonymous users (Issue #10215)

Hello @Hans-Zietsman<https://github.com/Hans-Zietsman> Targeted in-meeting notifications are not supported for anonymous users in Teams meetings. Anonymous users can only interact with existing apps in a meeting and cannot acquire or manage apps themselves. They also cannot directly use apps in meetings unless an app sends an adaptive card in the chat, which allows them to interact with the card.
If you want to send targeted in-meeting notifications, you need to retrieve the user IDs of the participants through the Get participant API and Get members API. However, it's important to note that targeted in-meeting notifications do not support user IDs in the Azure Active Directory (Azure AD) user ID format. For further assistance please go through with this documentation https://learn.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/meeting-apps-apis?tabs=channel-meeting%2Cguest-user%2Cone-on-one-call%2Cdotnet%2Cparticipant-join-event%2Cparticipant-join-event1#targeted-meeting-notification-and-app-icon-badging-api

**Comment by Vikram-MSFT** [comment]
Hello @Hans-Zietsman There is no specific information or steps provided in the documentation about targeted notifications not working for anonymous users. If you are experiencing issues with targeted notifications for anonymous users, I can recommend checking the Teams platform documentation for any updates or reaching out to Microsoft support for further assistance.

**Comment by Hans-Zietsman** [comment]
Yes, I am reporting a bug that targeted notifications are not working for anonymous users. It is meant to and did used to work

From: Vikram-MSFT ***@***.***>
Date: Wednesday, 17 January 2024 at 11:24
To: MicrosoftDocs/msteams-docs ***@***.***>
Cc: Hans Zietsman ***@***.***>, Mention ***@***.***>
Subject: Re: [MicrosoftDocs/msteams-docs] Targeted notifications no longer working for anonymous users (Issue #10215)

Hello @Hans-Zietsman<https://github.com/Hans-Zietsman> There is no specific information or steps provided in the documentation about targeted notifications not working for anonymous users. If you are experiencing issues with targeted notifications for anonymous users, I can recommend checking the Teams platform documentation for any updates or reaching out to Microsoft support for further assistance.

**Comment by Vikram-MSFT** [comment]
Hello @Hans-Zietsman Yes, this the correct platform to raise your Queries.

**Comment by Hans-Zietsman** [comment]
Then I am confused. I have raised an issue of a bug/ broken feature (confirmed) but am being redirected to check documentation or contact Microsoft support?

I would expect:

  1.  Bug to be acknowledged
  2.  Raised internally
  3.  Share estimated timelines to fix
  4.  Update limitations on documentation for other developers
  5.  Update when it has been fixed and rolled out

From: Vikram-MSFT ***@***.***>
Date: Thursday, 25 January 2024 at 09:21
To: MicrosoftDocs/msteams-docs ***@***.***>
Cc: Hans Zietsman ***@***.***>, Mention ***@***.***>
Subject: Re: [MicrosoftDocs/msteams-docs] Targeted notifications no longer working for anonymous users (Issue #10215)

Hello @Hans-Zietsman<https://github.com/Hans-Zietsman> Yes, this the correct platform to raise your Queries.

**Comment by ChetanSharma-msft** [comment]
Hello @Hans-Zietsman - Sorry for the confusion here.
We have already raised the bug and informed engineering team.
Once we get any update from engineering team, we will let you know.

**Comment by Prasad-MSFT** [comment]
@Hans-Zietsman - This issue seems to be fixed. (Both in Teams Desktop/Web client) Please do verify.
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/62237649/da156adf-62c7-4020-b1b1-b10ddc25314b)

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, please feel free to reopen it, if required.
