### ISSUE TITLE
Confusion regarding proactive messaging

### ISSUE THREAD

**Issue by swarajchavan98** [MicrosoftDocs/msteams-docs#10229]
Hi,
I want to send a proactive message to users in personal chat. The app has been added to a channel in a team. I followed the article on [proactive messaging](https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/send-proactive-messages?tabs=dotnet), where it is mentioned that:

> For a user to receive proactive messages, install the app for the user or make the user a part of a team in which the app is installed.

which I think means that once the app is installed in a team, and if the user is part of that team, then it is possible for me to send a proactive message.
I then followed the steps mentioned in the same above link, created the conversation and got the conversation id. But when I try to send a message to the user, I get a **_ConversationBlockedByUser_** error.

`{
    "error": {
        "code": "ConversationBlockedByUser",
        "message": "User blocked the conversation with the bot."
    }
}`

I have tried uninstalling the app, re-creating the conversation and then sending the message again, but to no avail. Could you please help me in resolving this issue?

**Comment by Vikram-MSFT** [comment]
Hello @swarajchavan98 This error denotes that "User has blocked the bot in personal chat or a channel through moderation settings."
Could you please follow below steps as mentioned in [this doc](https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-messages?tabs=dotnet1%2Capp-manifest-v112-or-later%2Cdotnet2%2Cdotnet3%2Cdotnet4%2Cdotnet5%2Cdotnet#:~:text=been%20added%20again.-,403,-Code%3A%20ConversationBlockedByUser)?
Delete the conversation from cache. Stop attempting to post to conversations until interaction with bot is explicitly initiated by a user in the conversation, indicating that the bot is no longer blocked.
