### ISSUE TITLE
Instructions for enabling Sideloading are incomplete

### ISSUE THREAD

**Issue by chrisbuttacavoliadec** [MicrosoftDocs/msteams-docs#10246]
When developing with Teams Toolkit and sideloading is disabled, VSCode links to this page. After following the instructions, sideloading was still not enabled after 24 hours.

I came across this page which shows another step in the 'Allow users to upload custom apps' section. The resolution is to update the Org-wide app setting under **Teams apps** --> **Manage apps** --> **Org-wide app settings**.

Please update the document to include this instruction.

![image](https://github.com/MicrosoftDocs/msteams-docs/assets/86005274/b835aebc-f7ff-41da-8688-4b3aeaaf1630)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b3530b55-59c8-6eec-b257-b7a5f2ed046b
* Version Independent ID: 022f7eff-f6c2-9a73-afa9-74e887b761e1
* Content: [Prepare your Microsoft 365 tenant - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/prepare-your-o365-tenant#enable-custom-teams-apps-and-turn-on-custom-app-uploading)
* Content Source: [msteams-platform/concepts/build-and-test/prepare-your-o365-tenant.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/build-and-test/prepare-your-o365-tenant.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **surbhigupta**

**Comment by Prasad-MSFT** [comment]
Hi @surbhigupta12 - Could you please help here to update the document as suggested?
