### ISSUE TITLE
Form changes dirty form functionality within microsoft teams personal tab breaks

### ISSUE THREAD

**Issue by raguravindran** [MicrosoftDocs/msteams-docs#10284]
- When there is a form change and user is getting redirected to a different page, browser usually throws an alert "Cancel or Leave"
- In case of Microsoft Teams app, personal tab context, redirection is not happening, it seems broken. Neither the alert is shown.

<img width="359" alt="Screenshot 2024-01-24 at 12 33 36 PM" src="https://github.com/MicrosoftDocs/msteams-docs/assets/36010645/002026ae-6ff6-4270-a681-4c657a95d402">

in desktop APP this alert does not come (which is understandable, but the redirection is broken too)

Is there an API in SDK that can help understand the event and control this within the tab??

**Comment by ChetanSharma-msft** [comment]
Hello @raguravindran - Thanks for raising your query.
Could you please share the repro steps and let us know how you have implemented it?

**Comment by raguravindran** [comment]
1. Create a personal tab (staticTab) point it to a webpage, upload this app to teams.
2. Open teams in browser (chrome/edge) and within the page have a form, a dropdown (choice list)
3. When choosing the choice list, simply redirect the page. something like, window.open("https://microsoft.com")
4. Now the form has edited fields then it tried to redirect the page in browser you will get an window alert "Changes made may not be saved"
5. Load the same app in desktop TEAMS client, try the same steps 2,3, you will not see the window alert nor page redirecting to a new url. Redirection is basically broken.

**Comment by raguravindran** [comment]
@ChetanSharma-msft Please find the steps above.

**Comment by raguravindran** [comment]
> Hello @raguravindran - Thanks for sharing the information. Would it be possible for you to share the app package, so that we can quickly test it?

No I do not have the package, since I am using our company's webpage, I cannot share it across

**Comment by ChetanSharma-msft** [comment]
Could you please share the code snippets you are using?

**Comment by raguravindran** [comment]
> Could you please share the code snippets you are using?

it is our internal portal.

as I said it is just a dropdown when selected, should call a JS client script which will call windows.open() API

**Comment by raguravindran** [comment]
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Redirect Example</title>
    <script>
        function redirectToMicrosoft() {
            // Get the selected option from the dropdown
            var dropdown = document.getElementById("redirectDropdown");
            var selectedOption = dropdown.options[dropdown.selectedIndex].value;

            // Check if an option is selected
            if (selectedOption) {
                // Open a new window and redirect to Microsoft.com
                window.open("https://microsoft.com", "_blank");
            } else {
                alert("Please select an option from the dropdown.");
            }
        }
    </script>
</head>
<body>
    <h1>Redirect Example</h1>
    
    <form>
        <label for="redirectDropdown">Select an option:</label>
        <select id="redirectDropdown" onchange="redirectToMicrosoft()">
            <option value="" selected disabled>Select an option</option>
            <option value="redirectOption1">Option 1</option>
            <option value="redirectOption2">Option 2</option>
            <option value="redirectOption3">Option 3</option>
        </select>
    </form>
</body>
</html>

```

**Comment by raguravindran** [comment]
@ChetanSharma-msft  please try the above, make sure `window.open("https://microsoft.com", "_self");` is "**_self**" and not "**_blank**"

**Comment by raguravindran** [comment]
> Hi @raguravindran, We tried to use the repro steps shared by you, but on selecting the option from dropdown I am getting error **"https://microsoft.com"** refuses to connect.
> 
> ![Screenshot (63)](https://private-user-images.githubusercontent.com/152403425/299310241-21d717b6-2c7f-41f7-8315-d40e09c0889b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxMTE4NTQsIm5iZiI6MTcwNjExMTU1NCwicGF0aCI6Ii8xNTI0MDM0MjUvMjk5MzEwMjQxLTIxZDcxN2I2LTJjN2YtNDFmNy04MzE1LWQ0MGUwOWMwODg5Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyNFQxNTUyMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZDQ4ZWY3Mjk3MzVjYzNjMjc0MTNlMzE4YmQwMDk5ZDhlNTQ3Yjc5NDQxOTJhMDAwMDVlYTk3ZGRmNDhjYmRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hPDdKpXtc8ujynMHzmLHvBDZIcWrISHc59wBT6lZWvA) ![Screenshot (64)](https://private-user-images.githubusercontent.com/152403425/299310246-f79f2567-9655-49dc-9425-888bcb4fa1fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxMTE4NTQsIm5iZiI6MTcwNjExMTU1NCwicGF0aCI6Ii8xNTI0MDM0MjUvMjk5MzEwMjQ2LWY3OWYyNTY3LTk2NTUtNDlkYy05NDI1LTg4OGJjYjRmYTFmZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyNFQxNTUyMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNGUxYzkyNGYxMmUxYjA0ZDM3ZDE5ZmQ2MjE5M2JmNjY3MmIwMzJkODc0MmY5OTllYjM0NDAwYWY2Y2FkODE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.f924iWcYSs0mz6MknQ7b6O_PFgYwxSZ40XIfhV_HTd4) Can you please let us know how it's fixed from your side?

it maybe due to cross scope restriction, you see that the browser version of TEAMS app is working perfectly.

but try the same with your DESKTOP TEAMS APP please

**Comment by raguravindran** [comment]
@Vaibhav-MSFT @ChetanSharma-msft Ignore the error, it seems like it works right? the redirection happens, but error it maybe due to cross scope restriction. You see that the browser version of TEAMS app is working fine.

but try the same step with your DESKTOP TEAMS APP please!

**Comment by raguravindran** [comment]
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Redirect Example</title>
    <script>
      // Enable navigation prompt
      window.onbeforeunload = function () {
        return true;
      };
      function redirectToMicrosoft() {
        // Get the selected option from the dropdown
        var dropdown = document.getElementById("redirectDropdown");
        var selectedOption = dropdown.options[dropdown.selectedIndex].value;

        // Check if an option is selected
        if (selectedOption) {
          // Open a new window and redirect to Microsoft.com
          window.open("https://microsoft.com", "_self");
        } else {
          alert("Please select an option from the dropdown.");
        }
      }
    </script>
  </head>
  <body>
    <h1>Redirect Example</h1>

    <form>
      <label for="redirectDropdown">Select an option:</label>
      <select id="redirectDropdown" onchange="redirectToMicrosoft()">
        <option value="" selected disabled>Select an option</option>
        <option value="redirectOption1">Option 1</option>
        <option value="redirectOption2">Option 2</option>
        <option value="redirectOption3">Option 3</option>
      </select>
    </form>
  </body>
</html>

```

**Comment by raguravindran** [comment]
@Vaibhav-MSFT @ChetanSharma-msft 

Please take the latest code snippet, I have added one more simulation to generate a navigation prompt, which is needed for this issue to be reproduced.

**Comment by raguravindran** [comment]
@Vaibhav-MSFT @ChetanSharma-msft  any update?

**Comment by ChetanSharma-msft** [comment]
Hello @raguravindran - Sorry for delay in response.
We will look into it and let you know the updates.

**Comment by Vaibhav-MSFT** [comment]
Hello @raguravindran, 
We tested the latest code snippet, the error still persists in Teams desktop app using `_self` and redirection seems to be broken.
Try using `_blank` with `window.open()` since the redirection is working fine in both Teams Web App and Teams Desktop Client.
Thanks!!

**Comment by Vaibhav-MSFT** [comment]
@raguravindran, 
We have raised bug for the same. We will inform you once we get any update.

**Comment by ChetanSharma-msft** [comment]
Hello @raguravindran - Sorry for delay in response.
We got an update from engineering team that this is working as designed. 

We do not let apps block navigation within the Teams Client because we want to ensure that the user can always get to their chat/call/meeting without interruption. Guidance is to persist any uncommitted data in local storage or server-side so no data loss occurs. 

Apps can also register a beforeUnload handler that delays their destruction by up to 15 seconds giving them time to save any unsynced state
https://learn.microsoft.com/en-us/javascript/api/@microsoft/teams-js/teamscore?view=msteams-client-js-latest#@microsoft-teams-js-teamscore-registerbeforeunloadhandler
