### ISSUE TITLE
this App Cannot be Found - Teams, any new app

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#10283]
Copied bug from: https://github.com/OfficeDev/TeamsFx/issues/10733 

**Details from original post:**
**Describe the bug**
Create new tab or other app in vs.net and run it so that it launches Teams. This message pops up when it tries to load the new manifest.

**To Reproduce**
1. Create a new Teams app (any kind) in Vs.net
2. Right Click and follow the instructions to Prepare Teams App Dependencies
3. Press F5.
4. Contrary to the instructions you don't get an add button, you just get the above error message.

**Expected behavior**
Should work according to the instructions

**Screenshots**
![image](https://github.com/OfficeDev/TeamsFx/assets/1868147/946f89ad-0010-4b56-ace7-951825ed4ed9)

**VS.NETExtension Information (please complete the following information):**
 - OS: Windows 11.
 - Version: 17.9.71.48084

**CLI Information (please complete the following information):**
 - OS: Windows
 - Version 3.0.0-alpha.ec50e3de8.0

**Additional context**
It did work the first time a while ago, but now does not, although periodically one attempt will work but then it fails again.
We are using the developer sandbox for deployment and the new app experience.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b743e43d-95cc-3d1e-b142-31a16369f97e
* Version Independent ID: b743e43d-95cc-3d1e-b142-31a16369f97e
* Content: [Teams Toolkit Overview - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/toolkit/teams-toolkit-fundamentals)
* Content Source: [msteams-platform/toolkit/teams-toolkit-fundamentals.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/teams-toolkit-fundamentals.md)
* Service: **msteams**
* GitHub Login: @zyxiaoyuer
* Microsoft Alias: **zhany**

**Comment by Prasad-MSFT** [comment]
Hi @JohnGalt1717 - Could you please let us know if this issue happening in New Teams or Teams Classic?

**Comment by JohnGalt1717** [comment]
> Hi @JohnGalt1717 - Could you please let us know if this issue happening in New Teams or Teams Classic?

New teams. It appears to be fine in classic teams.  That being said, in classic teams, the app, despite being installed with a manifest that has it's capable, doesn't show up anywhere else it can be added when you do add it. I.e. if you just add it to the company, the tab works, but then to add it to a team or channel you have to install it a second time from developer portal, you can't selected it from the team apps tab which seems non-sensical. It should be available everywhere the manifest says it's available.
