### ISSUE TITLE
Chrome Third Party Cookies phase-out alternative steps of tab authentication

### ISSUE THREAD

**Issue by egm0121** [MicrosoftDocs/msteams-docs#10291]
Since [storage partitioning](https://developers.google.com/privacy-sandbox/3pcd/storage-partitioning) breaks the current OAuth authentication flows for ms teams apps and browsers will start enforcing partitioned cookies this year, some pointers are needed on how to handle this type of authentication going forward

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3b1dcd0d-471b-2d33-54b5-39a93dfba2a8
* Version Independent ID: 5bd44149-777e-b449-bd2e-f20b9bd04038
* Content: [Configure third party OAuth authentication - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-tab-aad?tabs=teamsjs-v2)
* Content Source: [msteams-platform/tabs/how-to/authentication/auth-tab-aad.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/tabs/how-to/authentication/auth-tab-aad.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **surbhigupta**

**Comment by Dinesh-MSFT** [comment]
Hi @egm0121 - Thanks for raising your query.
We will check on it and let you know the updates.

**Comment by egm0121** [comment]
@Dinesh-MSFT Thank you for the update!

**Comment by Dinesh-MSFT** [comment]
Hi @egm0121 - Could you please confirm which app you building/own? We're looking for some apps that are broken by the 3P cookie deprecation so that engineering team will further look into this issue.

**Comment by egm0121** [comment]
@Dinesh-MSFT I'm part of the 8x8 team, we have 8x8 Work for Teams Tab app that uses the third party auth flow steps and presents our login page inside the teams sdk created popup. The flow will break with cookie storage partitioning enabled.

**Comment by Dinesh-MSFT** [comment]
Hi @egm0121, we have the below recommendation from engineering team - 
 
our current recommendation for apps that will be impacted by the 3P cookie deprecation is to apply for the third-party cookie deprecation trial so their apps can be exempt for the rest of this year:
https://developers.google.com/privacy-sandbox/3pcd/temporary-exceptions/third-party-deprecation-trial

We will also share updated guidance once we have a solution in place.

**Comment by egm0121** [comment]
@Dinesh-MSFT Thanks for the update. I assume the documentation will be updated once you have a compatible solution on your side.

**Comment by aderici** [comment]
> Hi @egm0121 - Could you please confirm which app you building/own? We're looking for some apps that are broken by the 3P cookie deprecation so that engineering team will further look into this issue.

Manifestly Checklists app on the MS Teams App store is a client of mine and i can confirm they seem to be impacted by this change. Currently if i switch to the "new teams" on a windows machine i can not use the app.

**Comment by Dinesh-MSFT** [comment]
Hi @aderici - Thanks for raising query.
We are checking this with engineering team and let you know the updates.
