### ISSUE TITLE
MsTeam open message in random chat while using deeplink 

### ISSUE THREAD

**Issue by RitekRitek** [MicrosoftDocs/msteams-docs#10305]
Hi Team,

We are utilizing the task module in Microsoft Teams to open a custom HTML page. On this page, users can select a prompt and their selection is sent to the Microsoft Teams chat. Users have the option to edit their selection before sending it to the bot.

![image](https://github.com/MicrosoftDocs/msteams-docs/assets/155973611/9241e32f-2125-4796-b9c2-667bf4a05643)

 We are using Microsoft deeplink approach to send this message to chat. (https://teams.microsoft.com/l/chat/0/0?users=UserID&message=Chat%20Test) 

**Issue :**   The message is sent to the bot as well as to other random chats.
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/155973611/53a4a222-774d-4fd1-bafc-62c530b5898b)

Could you please provide us any help regarding that issue?

**Comment by ChetanSharma-msft** [comment]
Hello @RitekRitek - Thanks for raising your query.
Could you please make sure that you are passing proper user id's.
**The comma-separated list of user IDs representing the participants of the chat. The user that performs the action is always included as a participant. 

Currently, the User ID field supports the Microsoft Entra UserPrincipalName, such as an email address only.**

**Comment by RitekRitek** [comment]
@ChetanSharma-msft  Thank you for the response.

We are passing ID in format 28: BotID in case of bot and message is successfully passed to expected chat but with this deep link approach it sends message to some random chat as well.

**We have tried deeplink with specific user email address as well e.g. https://teams.microsoft.com/l/chat/0/0?users=ritek.ritek@yourdomain.com&message=Test. In this scenario, the message is not only delivered to the correct user, but it's also sent to other random chats.**

**Comment by ChetanSharma-msft** [comment]
Hello @RitekRitek - Could you please confirm how are you executing the deep link?

I have just tried via pasting this deep link with proper user mail and it is working fine for me.

**Comment by RitekRitek** [comment]
Hello @ChetanSharma-msft ,  We are using deep link approach as per below url:

![image](https://github.com/MicrosoftDocs/msteams-docs/assets/155973611/954f1c69-966e-40de-a63f-28a8bbbb8f01)

In this scenario,  Message is sent to multiple chat either by clicking url or by executing deep link method.

Actual User message:
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/155973611/35487692-f39e-43b3-a2f4-c8061231f775)

Other chat:
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/155973611/462b09fb-c087-4a3d-867e-67edf71bdc87)

We are using Microsoft Teams version 23320.3027.2591.1505.

**Comment by ChetanSharma-msft** [comment]
Hello @RitekRitek - Thanks for sharing the information.
Could you please share the code snippets you are using from your Task module to execute it?

Also, let us know if you are facing this issue in Classic Teams or New Teams Desktop or Web client?

**Comment by RitekRitek** [comment]
@ChetanSharma-msft  Please find code below ;

microsoftTeams.initialize();
    function submitData(gridText) {
      let encodedGridText = encodeURIComponent(gridText);
      console.log("entered submit-" + gridText);
      let result = { value: gridText };
      var deepLink = 'https://teams.microsoft.com/l/chat/0/0?users=${UserID}&message=' + encodedGridText;
      microsoftTeams.executeDeepLink(deepLink);
    }
We are facing this issue in new Ms Team app

**Comment by ChetanSharma-msft** [comment]
Hello @RitekRitek - Thanks for sharing the information.
We will try this code from our end and let you know.

Meanwhile, could you please confirm whether it is working for you in Classic Teams?

**Comment by ChetanSharma-msft** [comment]
Hello @RitekRitek - I executed below deep link from my tab app application and please find my observations.
microsoftTeams.executeDeepLink('https://teams.microsoft.com/l/chat/0/0?users=xxx@xxxt.com&message=Test');

Teams Web/Desktop clients: => **It's properly navigating to my chat with message "Test"**
New Teams client version (Web): 1415/23113028724.
![Screenshot 2024-01-30 174305](https://github.com/MicrosoftDocs/msteams-docs/assets/59052547/481ac255-3710-4fa7-8219-0c1e5699164d)


Classic Teams desktop client: (Web client also has same behavior)  => **It is actually not redirecting to my chat but trying to create the new chat.**
You have Microsoft Teams Version 1.7.00.1907 (64-bit)-E. It was last updated on 1/30/2024.
![Untitled](https://github.com/MicrosoftDocs/msteams-docs/assets/59052547/cea98b53-801f-49ae-9f05-7abf7a30dae9)

Conclusion: 
Deep link is working fine in New Teams client but as per your inputs it's not working in New Teams client.

Could you please reverify once and let me know whether you are also facing same issue?

**Comment by RitekRitek** [comment]
Hello @ChetanSharma-msft,

We are still facing same issue. Message is sent to random chat as well.

**Comment by ChetanSharma-msft** [comment]
Hello @RitekRitek - It would be better if you can share the short video of your scenario including code and UI testing?
