### ISSUE TITLE
Create an Incoming Webhook documentation is outdated

### ISSUE THREAD

**Issue by fasifas** [MicrosoftDocs/msteams-docs#10304]
There is no option called "Connectors" as described [here](https://github.com/MicrosoftDocs/msteams-docs/blob/6d2871d0634bd191d5d1386a661e09bb576f49c5/msteams-platform/webhooks-and-connectors/how-to/add-incoming-webhook.md?plain=1#L165) in the dropdown menu in a Teams channel. At least not in my version.

This begs the question: how does one remove a webhook in the new version of Teams?

This is how it looks in my client:
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/137314763/00e6f6ce-0dda-419b-a073-b161d2cc0881)

Teams version 23335.232.2637.4844.
Client version is 49/23113028724.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 90ff2a84-a8bc-9259-d37d-622b102df75b
* Version Independent ID: e3b53e27-2946-189c-623b-9df704ea8f12
* Content: [Create an Incoming Webhook - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-incoming-webhook?tabs=dotnet)
* Content Source: [msteams-platform/webhooks-and-connectors/how-to/add-incoming-webhook.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/webhooks-and-connectors/how-to/add-incoming-webhook.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **surbhigupta**

**Comment by Prasad-MSFT** [comment]
Hi @fasifas - Now in New Teams from Manage Channel section we can create/edit any connector as below:
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/62237649/7f5f0e55-315c-482b-8688-bbce48ecc904)
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/62237649/f5d1d02d-7ec6-4eb7-9ab0-457972015799)
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/62237649/bdaaf646-b34a-4b3c-9a77-18e391de5611)

**Comment by fasifas** [comment]
> Hi @fasifas - Now in New Teams from Manage Channel section we can create/edit any connector as below...

In that case the doc should be updated.

**Comment by Prasad-MSFT** [comment]
Yes @fasifas - We have already discussed this with documentation team. Once the document is updated, we will close this issue.


Thanks!

**Comment by Prasad-MSFT** [comment]
@fasifas - The document has been updated.
Ref: https://learn.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-incoming-webhook?tabs=newteams%2Cdotnet#create-an-incoming-webhook

We are closing this issue for now. Please feel free to reopen if required. Thanks!
