### ISSUE TITLE
Send message using application level permission 

### ISSUE THREAD

**Issue by Vignesh-s-s** [MicrosoftDocs/msteams-docs#10318]
I've been trying send a chat message to individual user in application mode, I mean, without each user being required to authenticate and grant access to the application. The idea is to make it transparent to them.

So I send this request to get access token:

POST https://login.microsoftonline.com/{tenant-id}/oauth2/v2.0/token
grant_type=client_credentials,
client_id={app id registered in azure portal},
client_secret={registered app key},
scope=https://graph.microsoft.com/.default
Sending this request, I got the token.

Using this token, I try to send a message to the user using this request:

POST https://graph.microsoft.com/beta/chats/{chat-id}/messages
With this payload in JSON:

{
  "body": {
    "content": "Hello World"
  }
}
The problem is that I got this error message:

{
    "error": {
        "code": "Unauthorized",
        "message": "Message POST is allowed in application-only context only for import purposes. Refer to https://docs.microsoft.com/microsoftteams/platform/graph-api/import-messages/import-external-messages-to-teams for more details.",
        "innerError": {
            "date": "2023-05-18T17:49:24",
            "request-id": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
            "client-request-id": "xxxxxxxxxxxxxxxxxxxxxxxx"
        }
    }
}
An interesting point is that I can create a Chat, using the same logic explained. I send this request with the token that I got:

https://graph.microsoft.com/v1.0/chats
Payload in Json:

{
  "chatType": "oneOnOne",
  "members": [
    {
      "@odata.type": "#microsoft.graph.aadUserConversationMember",
      "roles": ["owner"],
      "user@odata.bind": "https://graph.microsoft.com/beta/users('user1')"
    },
    {
      "@odata.type": "#microsoft.graph.aadUserConversationMember",
      "roles": ["owner"],
      "user@odata.bind": "https://graph.microsoft.com/beta/users('user2')"
    }
  ]
}
To create Chat it works fine, but to send a message, I got an error.

I have all application permissions.

My usecase is to send message to teams from an application, using application level permissions.

**Comment by Vaibhav-MSFT** [comment]
Hello @Vignesh-s-s ,
Thanks for reporting your issue. We will test this and update you soon

**Comment by Vaibhav-MSFT** [comment]
Hi @Vignesh-s-s,
Please make sure this is enabled
 Appregistraion -> Authentication
Advanced settings
**Allow public client flows**
Enable the following mobile and desktop flows: **Yes**

**Comment by Vignesh-s-s** [comment]
Hi @Vaibhav-MSFT 
This configuration is enabled already, The problem is not with the authentication. 
The authentications works, and chat is created. The issue is about posting the messages with 'application-level' permission

**Comment by Vaibhav-MSFT** [comment]
Hello @Vignesh-s-s ,
Make sure your application has the required permission to send messages in a chat. In this case, the required permission is **Chat.Create** for delegated (work or school account) and **Chat.Create**
for application permissions.
Also please let us know if you are still facing the issue.

**Comment by Vignesh-s-s** [comment]
@Vaibhav-MSFT 
My application already has Chat.Create permissions both delegated and application. 
The issue is not with creating a chat, the issues is with posting a message to a chat after creating it. Please look into the error response below

{
    "error": {
        "code": "Unauthorized",
        "message": "Message POST is allowed in application-only context only for import purposes. Refer to https://docs.microsoft.com/microsoftteams/platform/graph-api/import-messages/import-external-messages-to-teams for more details.",
        "innerError": {
            "date": "2024-02-07T05:32:35",
            "request-id": "b6f21b55-77b0-45b3-be71-9474c1714b9e",
            "client-request-id": "b6f21b55-77b0-45b3-be71-9474c1714b9e"
        }
    }
}

**Comment by Vignesh-s-s** [comment]
Can I get an update?

**Comment by ChetanSharma-msft** [comment]
Hello @Vignesh-s-s - Sorry for delay in response.
As per error, it's clearly mentioned that 
**"Message POST is allowed in application-only context only for import purposes. Refer to https://docs.microsoft.com/microsoftteams/platform/graph-api/import-messages/import-external-messages-to-teams for more details."**

**Comment by vigneshsathisrikumar** [comment]
@ChetanSharma-msft 
Yes, I understand that infact that has been my question since the beginning. 
When creating a chat using application-level permission is supported, why not support sending the chat? 
I can create a conversation between two users using the application-level permissions, but I am not able to post a message to that conversation.

**Comment by Vaibhav-MSFT** [comment]
Hello everyone,
To achieve your requirements, we recommend you give your feedback in 
[Teams Feedback Portal](https://feedbackportal.microsoft.com/feedback/forum/ad198462-1c1c-ec11-b6e7-0022481f8472)

**Comment by purvasanap2001** [comment]
Using delegate permission, i can send message using the the authenticated user. But is there any way to send a message using anyone's identity?

I know there was a doc for application permission and i tried it. But it seems it is for import use and not for sending messages.
