### ISSUE TITLE
Tab order error of adaptive card

### ISSUE THREAD

**Issue by qjkobe** [MicrosoftDocs/msteams-docs#10325]
Card json:
```
{
    "type": "AdaptiveCard",
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.6",
    "body": [
        {
            "type": "ActionSet",
            "actions": [
                {
                    "type": "Action.Submit",
                    "title": "Action.Submit"
                }
            ]
        }
    ]
}
```
Put it in task module of Teams.
Press tab into button. Then press tab. The focus should go to close button of task module, but it go to the another place.

**Comment by Vikram-MSFT** [comment]
Hello @qjkobe  we will investigate the issue and get back to you soon

**Comment by Meghana-MSFT** [comment]
@qjkobe - We checked this at our end and pressing on tab key, focus is going to close button. 


https://github.com/MicrosoftDocs/msteams-docs/assets/81138249/b0e98057-be7c-48f8-b7c1-110675ab24ae


Could you please share more details so that we can have a local repro of this issue.
