### ISSUE TITLE
Confusion in sending proactive msg to the team members without requiring them to install bot

### ISSUE THREAD

**Issue by pranitamg** [MicrosoftDocs/msteams-docs#10321]
Issue description:
I want to send a message to the team members of my team without requiring them to install the bot explicitly.

In the [link](https://techcommunity.microsoft.com/t5/teams-developer/how-to-send-dm-even-if-the-user-has-not-installed-the-app-in/m-p/4016763) , it is mentioned that, **for a user to receive a proactive message, the user should be part of the team**. 

I installed the bot in a team and it was also installed proactively for me too. But for other team members, the conversation was not created i.e the bot was not installed for them.
Also I don't want to ask for graph permissions to install the app.

Please guide me through installing app for other team members and retrieving conversation id for them.

**Comment by Vikram-MSFT** [comment]
Hello @pranitamg It is possible to send a proactive message to members of a team without requiring them to explicitly install the bot. However, for a user to receive a proactive message from the bot, the bot must be installed in the team and the user must be a member of that team. If the bot is installed in a team, it should be automatically installed for all members of the team, and a conversation should be created between the bot and each member.
There could be several reasons for the bot not being installed for all team members,  it is possible that the bot installation process has not completed for all members, or there could be an issue with the bot's configuration or permissions. You may want to check the bot's installation status and ensure that it has the necessary permissions to send proactive messages to team members.

**Comment by pranitamg** [comment]
Hello,
I think, if there are only two members in a team then the bot installation must not take so much time for completion.

Regarding permissions, what kind of permissions are you talking about? Delegated or Application? 
I have added few permissions in my bot which require admin consent. So, is this preventing the bot from getting installed for other team members?

Also, plz let me know, how can i check the bot's installation status?

**Comment by pranitamg** [comment]
Hello,
It will be really helpful if you revert for the above query asap.

It will allow me to move further accordingly.

**Comment by Vikram-MSFT** [comment]
Hello @pranitamg 
Sorry for the delay in response,
Could you please refer this sample:
https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/graph-proactive-installation/nodejs
