### ISSUE TITLE
Tab Product Inspection sample doesn't work in Android device.

### ISSUE THREAD

**Issue by Mohammed-MSFT** [MicrosoftDocs/msteams-docs#10337]
Sample is working fine with IOS Device 
**IOS Device - Working.**
Both the functionalities **Product Inspect** and **View Product Status**.
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/109147706/2b73afd8-7b92-4dbd-a814-74ae09f21b01)
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/109147706/4530b217-edd3-416d-bef9-02f8ba9eecf2)
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/109147706/77b3ecfb-945d-4398-91ba-159978b139f6)
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/109147706/893344f9-ce31-42e1-a874-e736faecdaf4)
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/109147706/ff9881b1-e9f0-4c75-b6bc-583f463396bf)
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/109147706/1d1506db-7f49-43f1-992c-966c3e755373)
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/109147706/84463d69-b703-4533-86d3-e6465083a816)

**Android Device - Not Working. **
Whereas this sample is **not working in Android Device**.
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/109147706/59ee10e7-fdb2-4d5f-a1d5-93d5fb6eaf69)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ae58c607-2fb2-a4a1-c4fa-bef19e6c1309
* Version Independent ID: 458b2292-0ed1-3c5b-d0f3-63ef338720d2
* Content: [Integrate QR or barcode scanner capability - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/qr-barcode-scanner-capability)
* Content Source: [msteams-platform/concepts/device-capabilities/qr-barcode-scanner-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/device-capabilities/qr-barcode-scanner-capability.md)
* Service: **msteams**
* GitHub Login: @Rajeshwari-v
* Microsoft Alias: **surbhigupta**

**Comment by Prasad-MSFT** [comment]
Thanks for raising this issue. We will check it at our end and will raise bug for this.
