### ISSUE TITLE
Files cannot be downloaded from new teams’ custom app

### ISSUE THREAD

**Issue by takeungrae** [MicrosoftDocs/msteams-docs#10342]
let blob = new Blob([data], { type: 'application/octet-stream' });
                                    var url = window.URL.createObjectURL(blob);
                                    var a = document.createElement('a');
                                    a.href = url;
                                    a.download = decodeURIComponent(filename);
                                    document.body.appendChild(a);  
                                    a.click();  
                                    window.URL.revokeObjectURL(url);

It works very well in Classic Teams. However, in new teams, it only works once for the first time, and you have to log out and log in again for it to work. However, it also works only once for the first time. What's the problem? Is it a bug?

**Comment by takeungrae** [comment]
> 안녕하세요 - [여기에](https://github.com/MicrosoftDocs/msteams-docs/issues/10334) 언급 된 것과 동일한 문제인지 알려주시겠습니까?

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Multiple File Download</title>
</head>
<body>
  <button id="downloadButton">Download Files</button>


<script
  src="https://res.cdn.office.net/teams-js/2.19.0/js/MicrosoftTeams.min.js"
  integrity="sha384-h+MoYshcGDPMLlXjHLt2dSgsgYyWQ+yHd4Ob13htDsu8trGPea8Vooa8+tLtRzU7"
  crossorigin="anonymous"
></script>

  <script>
  
         microsoftTeams.initialize();
        microsoftTeams.appInitialization.notifySuccess();
        microsoftTeams.appInitialization.notifyAppLoaded();
		
  
    document.getElementById('downloadButton').addEventListener('click', function() {
      for (let i = 1; i <= 10; i++) {
        // Create a blob with the file content
        let data = i + '2345'; // Example content
        let blob = new Blob([data], { type: 'text/plain' });

        // Create a download link for the blob
        let url = window.URL.createObjectURL(blob);
        let a = document.createElement('a');
        a.href = url;
        a.download = i + '.txt';
        document.body.appendChild(a);

        // Trigger the download
        a.click();

        // Clean up the URL and the anchor element
        window.URL.revokeObjectURL(url);
        document.body.removeChild(a);
      }
    });
  </script>
</body>
</html>

Try running this source

In new teams, only one file is downloaded and there is no response after that.

You must completely close the app and log in again to download only one file.

**Comment by takeungrae** [comment]
Try running this source

In new teams, only one file is downloaded and there is no response after that.

You must completely close the app and log in again to download only one file.

**Comment by takeungrae** [comment]
Try running this source

In new teams, only one file is downloaded and there is no response after that.

You must completely close the app and log in again to download only one file.






<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Multiple File Download</title>
</head>
<body>
  <button id="downloadButton">Download Files</button>


<script
  src="https://res.cdn.office.net/teams-js/2.19.0/js/MicrosoftTeams.min.js"
  integrity="sha384-h+MoYshcGDPMLlXjHLt2dSgsgYyWQ+yHd4Ob13htDsu8trGPea8Vooa8+tLtRzU7"
  crossorigin="anonymous"
></script>

  <script>
  
         microsoftTeams.initialize();
        microsoftTeams.appInitialization.notifySuccess();
        microsoftTeams.appInitialization.notifyAppLoaded();
		
  
    document.getElementById('downloadButton').addEventListener('click', function() {
      for (let i = 1; i <= 10; i++) {
        // Create a blob with the file content
        let data = i + '2345'; // Example content
        let blob = new Blob([data], { type: 'text/plain' });

        // Create a download link for the blob
        let url = window.URL.createObjectURL(blob);
        let a = document.createElement('a');
        a.href = url;
        a.download = i + '.txt';
        document.body.appendChild(a);

        // Trigger the download
        a.click();

        // Clean up the URL and the anchor element
        window.URL.revokeObjectURL(url);
        document.body.removeChild(a);
      }
    });
  </script>
</body>
</html>

**Comment by Prasad-MSFT** [comment]
Hi @takeungrae - Could you please share a repro video along with repro steps, so that we can raise a bug for this?

**Comment by samuel-weber** [comment]
Hi @Prasad-MSFT  - Any news? This is critical to our teams app...

**Comment by takeungrae** [comment]
> Hi @Prasad-MSFT - Any news? This is critical to our teams app...

me too

**Comment by samuel-weber** [comment]
@takeungrae It worked for me, when I do not provide the download attribute:

```ts
const link = document.createElement('a');
link.href = url;
try {
  document.body.appendChild(link);
  link.click();
} finally {
  document.body.removeChild(link);
}
```

**Comment by takeungrae** [comment]
> @takeungrae It worked for me, when I do not provide the download attribute:
> 
> ```ts
> const link = document.createElement('a');
> link.href = url;
> try {
>   document.body.appendChild(link);
>   link.click();
> } finally {
>   document.body.removeChild(link);
> }
> ```

Just as the browser asks for the option to allow multi-downloading, the same applies to web views. Since the web view of the Teams app does not allow multi-downloading, it is downloaded only once for the first time and does not download after that.

**Comment by Prasad-MSFT** [comment]
@samuel-weber , @takeungrae - Apologies. At the moment, we have not received any updates from the engineering team. However, we are actively communicating with them to stay updated on the progress. We have also made them aware of the seriousness of the issue. As soon as we receive any updates from them, we will notify you in this thread. 

Thank you!

**Comment by bciernia** [comment]
Hello, do you have any news about this issue? In classic teams everything works fine, but old version will be disabled soon and this is critical to our custom add in.

**Comment by Prasad-MSFT** [comment]
@bciernia - Apologies. Currently there is no ETA to share. We are following up with engineering team about this issue. We will update this thread once we hear from them. Thanks!

**Comment by Prasad-MSFT** [comment]
Hi @takeungrae , @samuel-weber , @bciernia - according to latest update from engineering team the fix has been released publicly. Please do verify and let us know.
