### ISSUE TITLE
MS Teams - Unable to open 'Connector' window for a Chat (Channel)

### ISSUE THREAD

**Issue by Sameen1234567** [MicrosoftDocs/msteams-docs#1035]
- Windows 10 / MAC High Sierra 10.13
- Login to MS office365
- Navigate to MS Teams
- Open any Chat -->Channel --> Connectors

Error will be shown in its windows

<img width="1680" alt="Screen Shot 2019-10-10 at 2 52 31 PM" src="https://user-images.githubusercontent.com/56390521/66559349-ae04f080-eb6e-11e9-8de0-012e74d3fcce.png">

**Comment by Gousia-MSFT** [comment]
@Sameen1234567 Thanks for reaching out! We are looking into this.

**Comment by Gousia-MSFT** [comment]
@Sameen1234567 This has been fixed now. Could you please check and confirm once?

**Comment by Gousia-MSFT** [comment]
#1034
