### ISSUE TITLE
[iOS] App activities are missing in the activity feed on Teams Store App

### ISSUE THREAD

**Issue by borislink12** [MicrosoftDocs/msteams-docs#10354]
### Premise
We are using the **TeamsActivity.Send** application permission to send activity notifications to users from our application. 

### Development progress
During development all of the activities have been delivered to the activity feeds including iOS.

**Microsoft resources on activity notification implementation**
https://learn.microsoft.com/en-us/microsoftteams/platform/sbs-graphactivity-feedbroadcast

### Current status with missing app activities on iOS Teams app
After the approval and the subsequent update of our app via the Teams App Store activities are delivered to the Desktop and Android activity feeds of the Teams app. The activity feed of iOS devices on the Teams app for the same users of the Desktop version are not included. 

At the end of this post I attached two screenshots taken at the same time of the respective activity feeds filtered for App activities.
Both are from my personal account. All other activities match but the iOS activity feed is missing the mentioned app activities.

Note: All other activity notifications like mentions are present on all devices and versions of the Teams app.

### Activities vs Notifications
We checked all Settings of both the Teams iOS and the general iOS settings regarding notifications. Also reinstalling... Details on what we tried can be found here: https://answers.microsoft.com/en-us/msteams/forum/all/teams-feed-notifications-are-not-showing-up-on-ios/c9b98401-a0e3-4269-9fa4-b32ac89c0a01

Because of the fact that activities of mentions, etc. can also be seen in the feed with notifications having been turned off. We strongly belief that it must be specifically the iOS teams app blocking app activities from being listed.

### Screenshots
<img width="663" alt="Screenshot 2024-02-08 at 09 30 30" src="https://github.com/MicrosoftDocs/msteams-docs/assets/84346358/fa602e1f-1383-44ce-b1dd-db9d799802ef">

![IMG_4490](https://github.com/MicrosoftDocs/msteams-docs/assets/84346358/14fa7e41-bc4a-4627-af96-73f3da63d8da)

**Comment by Prasad-MSFT** [comment]
@borislink12 - Thanks for raising your issue. We will check this at our end and will update you accordingly.

**Comment by Prasad-MSFT** [comment]
Hi @borislink12 - We have raised an ICM for this issue and engineering team is looking into it. We will inform you once we have further update. 

Thanks!

**Comment by borislink12** [comment]
Thank you Prasad for forwarding this issue and looking into it! 

We are very much interested in your findings. 

Have a great weekend!

**Comment by borislink12** [comment]
Anything I can help you with to reproduce?
And what is an ICM if I may ask? I do not know the abbreviation.

**Comment by Prasad-MSFT** [comment]
Thanks @borislink12 - Currently we don't need any other information, if we require anything later will definitely update you. FYI, ICM normally gets raised when number of developers face the same issue and need quick resolution.

**Comment by Prasad-MSFT** [comment]
@borislink12, this issue seems to be fixed. We tested in `iOS 17.6.1` with below MS Teams version and observed that activity feed notifications are being delivered successfully.
![image](https://github.com/user-attachments/assets/50c6e889-2121-4835-b2dd-d33fff66a7fc)

![image](https://github.com/user-attachments/assets/84496f3b-0ec1-4d95-833e-99c63ce12503)

**Comment by Flaysh** [comment]
I also have that, i dont get see notifications on my iOS device but i do see them on browser/mac/android
(The Blue Apono app) app from the teams app store.
![CleanShot 2024-10-11 at 23 04 19@2x](https://github.com/user-attachments/assets/82d8867b-47fb-462d-bf84-7154b481b073)
![image](https://github.com/user-attachments/assets/aa7b5794-f09b-49b4-b5fa-e6745181c4cb)
