### ISSUE TITLE
Is there people picker control available? 

### ISSUE THREAD

**Issue by anomepani** [MicrosoftDocs/msteams-docs#1036]
Is there people picker control available in teams app studio control? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c181f8cb-871f-09f5-1210-352afeaf0271
* Version Independent ID: 2a62e83d-0dd5-0cff-e45f-73d451f10b63
* Content: [Get started with App Studio for Microsoft Teams - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/get-started/get-started-app-studio)
* Content Source: [msteams-platform/get-started/get-started-app-studio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/get-started/get-started-app-studio.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Gousia-MSFT** [comment]
@anomepani App Studio is mainly used for creating and integrating the apps into Teams. Could you please elaborate more on your scenario and what are you trying to achieve?

**Comment by Ky7m** [comment]
@anomepani you can take a look at preview components https://docs.microsoft.com/en-us/graph/toolkit/components/people?context=graph%2Fapi%2F1.0&view=graph-rest-1.0

**Comment by anomepani** [comment]
Thanks, @Ky7m  and @Gousia-MSFT I will take a look and If I have any issue I will let you know.
