### ISSUE TITLE
Unexpected Tab Behavior in Microsoft Teams both Classic and New Teams

### ISSUE THREAD

**Issue by NarenderSingh** [MicrosoftDocs/msteams-docs#10368]
An unexpected behavior observed in Microsoft Teams. Upon refreshing a tab within the Teams app, instead of simply performing or executing a browser refresh on the current tab, a new tab is generated. This is evidenced by the disappearance of session storage and a change in the TabId as shown in the video below

**New Teams version:** 24004.1307.2669.7070(preview)
**Classic Teams version:** 1.7.00.3653.

**MS Teams Error on Windows:**

https://github.com/MicrosoftDocs/msteams-docs/assets/12576426/4b262054-378c-4942-8a17-24f94cc4a0a9

**MS Teams Error on iOS:**

https://github.com/MicrosoftDocs/msteams-docs/assets/12576426/c69d3556-9326-4502-9068-7692bf1eedcf

**Comment by ChetanSharma-msft** [comment]
Hello @NarenderSingh - Thanks for raising your query.
Could you please share the repro steps including the code snippets and manifest file?

Kindly share the version details of Teams client and confirm whether you are facing this issue in Desktop/Web/Mobile all places?

**Comment by NarenderSingh** [comment]
Hi @ChetanSharma-msft.

**To replicate the issue:**

1. Open the custom app tab within Microsoft Teams.
2. Navigate to a specific record within that tab.
3. Proceed to refresh the tab using the provided refresh button.

**Expected behavior:** The record that was previously accessed should remain displayed within the tab.
**Actual behavior:** Instead of retaining the previously accessed record, the contentUrl link provided within the tab is displayed after the refresh operation.

**manifest.xml file:**
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/12576426/b1a1012e-7bf7-4ba6-8a3c-3a51a13e4ddc)

In both desktop and web, this behavior occurs consistently. However, this behavior is not observed in iOS; in iOS, the current record remains visible even after the tab is refreshed.

**Comment by Vaibhav-MSFT** [comment]
Hello @NarenderSingh ,
We are able to repro this issue. We have raised a bug for the same. We will inform you once we get any further update from engineering team. Thanks!

**Comment by NarenderSingh** [comment]
Hi @Vaibhav-MSFT,

Thank you for updating on the issue. We appreciate your efforts in raising the bug report.

Regarding the completion timeline for the bug resolution, could you please provide an estimate based on your experience and insights into the current situation? 

We understand that the timeline may vary depending on several factors, but having an approximate timeframe would help us manage expectations and plan accordingly.

We look forward to hearing from you regarding this matter.

**Comment by ChetanSharma-msft** [comment]
Hello @NarenderSingh - Sorry to say but looks like it is not the bug but a by design behavior.
Teams web/desktop: If you refresh/reload the tab, it will show the main page contents.

iOS: if you refresh/reload, it will show the last viewed contents.

You need to handle this behavior in your application.
You can refer this documentation: https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/app-caching

**Comment by NarenderSingh** [comment]
Hello @ChetanSharma-msft and @Vaibhav-MSFT . 

Thank you for your response and clarification regarding the behavior we encountered. We appreciate your guidance on handling this issue and will refer to the documentation provided to implement tab app caching accordingly. We will proceed to close the ticket.

**Comment by ChetanSharma-msft** [comment]
Hello @NarenderSingh - Thanks for the confirmation.
Please share your valuable feedback for us via [Microsoft Teams Developer Community Response Feedback ](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR7iCOpS5_b9Nqmwx43u5rtZUOThVR081SllSR05aSDQxQ0tUMDVPTVIxTi4u)link
