### ISSUE TITLE
[Doc Update] Update the doc and code snippets

### ISSUE THREAD

**Issue by ChetanSharma-msft** [MicrosoftDocs/msteams-docs#10360]
1) Remove highlighted content from the doc:
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/59052547/27ca7405-fcfc-432c-85be-915a66f3af73)

Section to be updated: 
https://learn.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/action-commands/respond-to-task-module-submit?tabs=json%2Cdotnet-1#respond-to-botmessagepreview-send

2) Update C# code and add NodeJS code snippets:
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/59052547/5da592e0-0dd2-4888-b708-b115846c75b6)

C# code to be updated:
`channelData: {
    onBehalfOf: [
        {
            itemId: 0,
            mentionType: 'person',
            mri: context.activity.from.id,
            displayName: context.activity.from.name
        }
    ]
}`

Add below nodeJs code:
`channelData: {
                    onBehalfOf: [
                        {
                            itemId: 0,
                            mentionType: 'person',
                            mri: context.activity.from.id,
                            displayName: context.activity.from.name
                        }
                    ]
                }`

![image](https://github.com/MicrosoftDocs/msteams-docs/assets/59052547/174cb09a-7f53-444f-b5fc-6242c86ba0f1)

Section to be updated: 
https://learn.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/action-commands/respond-to-task-module-submit?tabs=dotnet%2Cdotnet-1#user-attribution-for-bots-messages

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8fb0c2d8-f880-c260-d0be-6b9467e47f8c
* Version Independent ID: 7820ffc9-5260-c818-f5fb-672801a67d00
* Content: [Respond to the dialog submit action - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/action-commands/respond-to-task-module-submit?tabs=json%2Cdotnet-1#respond-to-botmessagepreview-send)
* Content Source: [msteams-platform/messaging-extensions/how-to/action-commands/respond-to-task-module-submit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/messaging-extensions/how-to/action-commands/respond-to-task-module-submit.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **anclear**

**Comment by ChetanSharma-msft** [comment]
Hello @surbhigupta12 - Please help to update the documentation.

**Comment by Wajeed-msft** [comment]
@ChetanSharma-msft - could you please give C# and Node.js code with additional code snippet on usage? Currently it's not very helpful.

**Comment by ChetanSharma-msft** [comment]
Hello @Wajeed-msft - We already have code written in the documentation here:
https://learn.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/action-commands/respond-to-task-module-submit?tabs=dotnet%2Cdotnet-1#respond-to-botmessagepreview-send

Above code is only for ChannelData  object.

Please let me know if my understanding is wrong here?
