### ISSUE TITLE
There is no SDK for this that uses a Microsoft programming language?

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/msteams-docs#1037]
This SDK doesn't seem to be aligned with the customer base without it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aadca17b-de5c-0d06-caa6-d7bafd04f99b
* Version Independent ID: 91035790-5d36-067e-4400-04bb51cb03e3
* Content: [Microsoft Teams client SDK - Teams](https://docs.microsoft.com/en-us/javascript/api/overview/msteams-client?view=msteams-client-js-latest#feedback)
* Content Source: [nodejs/overview/msteams-client.md](https://github.com/OfficeDev/msteams-client-docs-ref-typescript/blob/live/nodejs/overview/msteams-client.md)
* Product: **msteams**
* GitHub Login: @charlesprakash
* Microsoft Alias: **o365devx**

**Comment by Trinetra-MSFT** [comment]
Could you please tell us more, what actually you are looking for?

**Comment by StingyJack** [comment]
Not JavaScript;  VB, c#, power shell, etc.

**Comment by Trinetra-MSFT** [comment]
@StingyJack , As of now Microsoft Teams Client SDK is written in Javascript only. It makes it easy to integrate your own services with Teams, whether you develop custom apps for your enterprise or SaaS applications for teams around the world.

**Comment by clearab** [comment]
This is a client-side SDK that runs inside of an Electron shell, which is essentially a browser. JavaScript is essentially the only language that makes sense in this context. This SDK cannot be run outside of the context of a web browser.

**Comment by StingyJack** [comment]
Microsoft makes a significant use program using a non-MSFT tech (a really crummy one that has all kinds of graphical and is OS incomplete/incompatible), and then only makes it extensible via a non-MSFT programming language. 

This is not the best way to reward and foster the investment your long time customers have made in MSFT tech.

Why not use blazor or have this be a pilot for the netcore 3 UI stuff?

**Comment by billbliss** [comment]
Microsoft Teams is a web-based application. It runs on the desktop via Electron and it runs in the browser directly. Browsers only support JavaScript, so that's what the SDK is written in. That's not going to change.

If you prefer a Microsoft language, you can use TypeScript.

I started at Microsoft in 1987, so I've been through the "not invented here" days. Now, we focus on using what works.

**Comment by SHAGGAR** [comment]
I think the problem here is we don't want a web application.  We want something that has decent performance, which is not something you can create with javascript and electron.  I get that it lets you dedicate your summer interns to writing the teams client, but that has come at the cost of an extremely poor user experience.  The teams client is really awful.  

If you were to release a c# client sdk, or at the very least give us access to some websocket APIs so we can get notifications, we can write a decent teams client for you.

**Comment by StingyJack** [comment]
.net, wpf, winforms, all these things _just work right_ on a Windows desktop.  No crazy graphic artifacts, my OS accessibility settings are honored, etc.

I'd say let them who don't want to use windows use the electron crap, but I don't think they like it much either. Its like settling for the lowest common denominator when you could have built a better xplat UI tech based on netcore 3.x. I feel the pain of the "use what works" choice every day I have to use this program and the regret because _I_ suggested we try it a year ago and now it's entrenched.

I could live with less pain and regret and without the hundred crummy UX choices and unfixed bugs in this app, which are the bigger problems I'd like to avoid by having a different teams client app. Which is what im really after. (Thanks @SHAGGAR  for reminding me.)

**Comment by SHAGGAR** [comment]
The thing that makes it even worse is that its so obviously a cost cutting thing and not at all some "open source!/open tools!" thing.  Supporting multiple platforms with high quality clients is hard and expensive.  Electron/javascript gives you an equally poor experience across all platforms at a much lower maintenance cost.  

An actual "open" approach would be providing the tools and APIs to allow people to use the services how they want.  There are now endpoints for chat messaging in the beta version of the graph API, but theres no way to have desktop clients subscribe to get new chat notifications.  This means you'd be stuck doing polling for new messages which would suck. I think that still might be better than using the official teams client.
