### ISSUE TITLE
[SBS Guide] "Provision you app" step is not correct and it's not automatically provisioning if we Run and debug the code directly.

### ISSUE THREAD

**Issue by ChetanSharma-msft** [MicrosoftDocs/msteams-docs#10370]
1) "Provision you app" step is not correct and it's not automatically provisioning if we Run and debug the code directly.
Manifest build folder is also not creating.

So, please add a step to manually provision the application via clicking on below:
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/59052547/bea5f535-02be-4e87-9d62-ff5b94f940aa)

2) Also, please check why after searching contents we are getting NA/NA in result:
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/59052547/ac5a1cb4-8e9d-4055-8c87-9521bc928927)

Doc link: https://learn.microsoft.com/en-us/microsoftteams/platform/sbs-api-me-ttk?tabs=vscode%2Cviscode&tutorial-step=2

3) .yaml file is showing error in VS Code due to it's version:
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/59052547/4658a6fb-1b90-42e0-b900-0cca85c77160)

If we update it to 3.1.0, error is going away.
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/59052547/005591b6-7e18-4814-a2b9-dbe50d6949b6)

So, please check with engineering team and update it accordingly.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 603a9bb4-cf1b-aa8d-ccba-834925d3a39e
* Version Independent ID: 603a9bb4-cf1b-aa8d-ccba-834925d3a39e
* Content: [Build API-based message extension - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/sbs-api-me-ttk?tabs=vscode%2Cviscode)
* Content Source: [msteams-platform/sbs-api-me-ttk.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/sbs-api-me-ttk.yml)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **surbhigupta**

**Comment by Prasad-MSFT** [comment]
Hi @surbhigupta12 - Could you please help to update this?
