### ISSUE TITLE
"Declare custom tab in app manifest" needs more info

### ISSUE THREAD

**Issue by clbecker** [MicrosoftDocs/msteams-docs#10398]
The section "Declare custom tab in app manifest" doesn't give an example or show the specifications for how the custom tab needs to be declared in the app manifest.  Where in the manifest does it need to be declared?  What parameter name(s) need to be used?  What configuration options can be set for it in the manifest?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 62b12649-8660-975a-87f6-2f7486b5dc79
* Version Independent ID: c1b86714-5b2e-79a8-5761-0fb2fd5746c0
* Content: [Microsoft Teams tabs - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs?tabs=desktop%2Cdesktop1%2Cpersonal#declare-custom-tab-in-app-manifest)
* Content Source: [msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/tabs/what-are-tabs.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **surbhigupta**

**Comment by Meghana-MSFT** [comment]
Thank you for reporting this, we will check this and get make necessary changes in the document.
