### ISSUE TITLE
"You don't have permissions to add Hello World to this team."

### ISSUE THREAD

**Issue by norachuga** [MicrosoftDocs/msteams-docs#1040]
When I click Install under Test and Distribute, this is what I see:

![Teams_Hello_World_denied](https://user-images.githubusercontent.com/4997476/66601135-2969a080-eb75-11e9-86d2-8d851081ba4b.PNG)

The dialog UI appears to have changed since this tutorial was written, so I'm not quite sure of the issue. There is no option for "Add for you", nor is there even a place to search for a team. "This team" implies that I chose a team, but I didn't.

**Comment by Gousia-MSFT** [comment]
@norachuga Are you trying to upload the app from App Studio? Could you please try downloading the manifest and [sideload it](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/apps/apps-upload)? 

> There is no option for "Add for you", nor is there even a place to search for a team

![image](https://user-images.githubusercontent.com/45553518/66627049-0d6b0b00-ec18-11e9-85be-f998ec13dc85.png)
Clicking on Add directly adds the app in your personal scope. If you want to add the app to a team, you could choose "Add to a team" from the dropdown and you will get an option to search for the team you want to add the app to.
![image](https://user-images.githubusercontent.com/45553518/66627123-4e631f80-ec18-11e9-8e90-fac54d3a47d2.png)

![image](https://user-images.githubusercontent.com/45553518/66627135-5ae77800-ec18-11e9-9b84-464f0cf367ce.png)

**Comment by norachuga** [comment]
Yes, I was trying to add through the Apps Studio. 


My UI does not match what is shown in the sideload doc either, and I do not have the options it offers.

In the [first option](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/apps/apps-upload#upload-your-package-into-a-team-or-conversation-using-the-store), there is not a Store icon. Instead, it says Apps (as well as Help instead of a Feedback option). As you can also see, there is no "Upload a custom app" option.
![Teams_NoAppStore](https://user-images.githubusercontent.com/4997476/66656155-6c765300-ec0b-11e9-859f-d3039bea9085.PNG)
The screenshot is from the desktop app (1.2.00.26774), but the same is true of the webapp as well.

In the [second option](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/apps/apps-upload#upload-your-package-into-a-team-using-the-apps-tab), there is no "Upload a custom app" option on the Apps tab either.
![Teams_NoAppsTab](https://user-images.githubusercontent.com/4997476/66656504-21107480-ec0c-11e9-9e3b-20af14cb2ae2.PNG)

**Comment by Gousia-MSFT** [comment]
@norachuga Could you please check if Sideloading is enabled in Setup Policies?
![image](https://user-images.githubusercontent.com/45553518/66734572-43f78e80-ee81-11e9-8cf5-68c3bc861940.png)
Please follow this document to enable [sideloading ](https://docs.microsoft.com/en-us/microsoftteams/platform/get-started/get-started-tenant)if you haven't done it already.

**Comment by norachuga** [comment]
There appears to be a **very** long delay between enabling/disabling "Allow uploading custom apps" and the functionality appearing/disappearing.

The features eventually showed up with no further action from myself, but I did not keep track of how long it took. It could be more than a day.

I have now disabled sideloading, but the features remain completely available. It has been 2 hours since I disabled it, and I was still able to upload a new custom app, as well as update an existing one. 

I have made note of when I disabled it and will be keeping an eye on it. I will update when it actually becomes disabled.

**Comment by norachuga** [comment]
It seems that the features appear to appear/disappear at different rates from each other as well.

6 hours after disabling: 

- Teams > Apps tab - _Upload a custom app_ option is no longer visible
- App Studio > Test and Distribute > Install > Add is disabled

23 hours after disabling:
- Apps > _Upload a custom app_ is still available. I was able to upload a new app using it.

**Comment by Gousia-MSFT** [comment]
@norachuga App setup policies usually take some time to update. Were you able to add the app to the Team? Is your issue resolved?

**Comment by norachuga** [comment]
Sure, I guess my issue is resolved.

I feel like it should probably be made clear on any or all of these pages that it takes more than entire day for a change in settings to take effect. Otherwise, a reasonable person would assume the documents are wrong, they have done something wrong, or there was a bug.

https://docs.microsoft.com/en-us/microsoftteams/platform/get-started/get-started-dotnet-app-studio
https://docs.microsoft.com/en-us/microsoftteams/platform/get-started/get-started-configure-teams
https://docs.microsoft.com/en-us/microsoftteams/platform/get-started/get-started-tenant

**Comment by Gousia-MSFT** [comment]
@norachuga Thanks for the feedback!

**Comment by Afshin1980** [comment]
Same problem here

**Comment by PranavJoshi1070** [comment]
I have same issue and tried to enable Sideloading in Setup Policies. However the toggle button is disabled in the "First Line Worker" policy section. I am logged in with tenant admin credentials.
(I was able to to enable the upload custom apps to ON for "Global (Org-wide default)" policies).
Am I missing something here? please guide. Thank you.
 
![Teams](https://user-images.githubusercontent.com/57978307/69212559-b39b2080-0b87-11ea-8d1d-9724d11b358f.png)

**Comment by acmcg** [comment]
Many of the policies in Teams take hours to be enforced. This seems to be atypical for M365 services. Is there are reason, and considering that many of these would be deemed as security related should it be so?

**Comment by Zalutskiy** [comment]
Maybe someone will help this link.
[https://techcommunity.microsoft.com/t5/teams-developer/you-don-t-have-permissions-to-add-for-adding-a-bot/m-p/918612](url)

**Comment by abpatel** [comment]
> When I click Install under Test and Distribute, this is what I see:
> 
> ![Teams_Hello_World_denied](https://user-images.githubusercontent.com/4997476/66601135-2969a080-eb75-11e9-86d2-8d851081ba4b.PNG)
> 
> The dialog UI appears to have changed since this tutorial was written, so I'm not quite sure of the issue. There is no option for "Add for you", nor is there even a place to search for a team. "This team" implies that I chose a team, but I didn't.

For following a tutorial , this is way too involved, not sure why a walkthrough would be posted without vetting that it's working properly

**Comment by Jio-AL** [comment]
I am having the same message "you don't have permissions to add MyApp to this teams". I have system administrator role. I have created a policy with "Upload custom apps" turned on and wait for about half day and still I am having the same issue. Some advise please. Thanks.

**Comment by Jacko1394** [comment]
Im having this issue too.

**Comment by davidgv88** [comment]
I have the same problem

**Comment by yiannismanatos4Innexys** [comment]
Same here..

**Comment by jyothsnag29** [comment]
I'm having the same issue.

**Comment by m-dayoub** [comment]
Please how do you watch the live sessions?
