### ISSUE TITLE
Add link to existing NodeJS sample as well.

### ISSUE THREAD

**Issue by ChetanSharma-msft** [MicrosoftDocs/msteams-docs#10401]
We can add this sample link as well here:
https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/graph-activity-feed/nodejs

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ff77fffb-75a2-3ae3-c5ca-122bacca96d5
* Version Independent ID: ff77fffb-75a2-3ae3-c5ca-122bacca96d5
* Content: [Send activity feed notifications - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/send-activity-feed-notification?tabs=desktop#authorization-update)
* Content Source: [msteams-platform/tabs/send-activity-feed-notification.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/tabs/send-activity-feed-notification.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **surbhigupta**

**Comment by Prasad-MSFT** [comment]
Hi @surbhigupta12 - Could you please help here to add this sample link as well in this [section](https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/send-activity-feed-notification?tabs=desktop#code-sample)?
