### ISSUE TITLE
TeamsJS version for Teams-only apps

### ISSUE THREAD

**Issue by MajaEffenberg** [MicrosoftDocs/msteams-docs#10406]
Which version of the Teams JavaScript client library should we use in our Teams-only Angular app? Our app appears in Teams Tabs as an iFrame.

This is confusing in your documentation because the best practices differ from the recommended version and it is unclear which version we should use.
Related part of the documentation:  [Teams-only apps](https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/using-teams-client-library?tabs=javascript%2Cmanifest-teams-toolkit#teams-only-apps)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4ae8187e-a7e4-4b5a-6f38-da6bfa30f2d2
* Version Independent ID: 4ae8187e-a7e4-4b5a-6f38-da6bfa30f2d2
* Content: [Teams JavaScript client library SDK - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/using-teams-client-library?tabs=javascript%2Cmanifest-teams-toolkit#teams-only-apps)
* Content Source: [msteams-platform/tabs/how-to/using-teams-client-library.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/tabs/how-to/using-teams-client-library.md)
* Service: **msteams**
* Sub-service: **m365apps**
* GitHub Login: @erikadoyle
* Microsoft Alias: **mosdevdocs**

**Comment by erikadoyle** [comment]
@MajaEffenberg thanks for reporting! That is indeed contradictory advice. Best practice for Teams apps, regardless if they're Teams-only or extended to run in Outlook and M365 (Office) app, is to use latest TeamsJS version. TeamsJS v1 is no longer under active development.

I'm creating a PR to revert the recent change that introduced the contradictory guidance.

**Comment by ChetanSharma-msft** [comment]
Thanks @erikadoyle for raising the PR.
PR changes looks fine, so I approved it from my end.
