### ISSUE TITLE
Stage view for images works even for base64 encoded images, contra documentation

### ISSUE THREAD

**Issue by aosolis** [MicrosoftDocs/msteams-docs#10428]
Highlighted part doesn't appear to be correct, at least in New Teams.
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/767208/9ea84324-cb10-4405-813e-0b28219d5876)

First image was specified as a URL, second image a data URI. Both behave the same (which is what I would expect, since we convert the base64 image to a URL).
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/767208/e49990f5-e426-4d4f-b3a9-a89d4d975e24)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 001a12ea-30fa-d626-18a9-02a518bfb37f
* Version Independent ID: e5f5f69e-66e9-d1b2-e19a-485d0ffcd6fa
* Content: [Text formatting in cards - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?tabs=adaptive-md%2Cdesktop%2Cconnector-html)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-format.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/task-modules-and-cards/cards/cards-format.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **surbhigupta**

**Comment by Prasad-MSFT** [comment]
Hi @surbhigupta12 - Could you please help here?
