### ISSUE TITLE
[Critical] iOS 6.3.0 issues (Pined app (isExternal=true) not working), HTML button click is not responding

### ISSUE THREAD

**Issue by kafka-yu** [MicrosoftDocs/msteams-docs#10427]
Hi team, we met a problem after the Teams app upgraded to 6.3.0 on an iOS device. (Take the RingCentral app as an example)

Problem statement:
Given:

On iOS Teams mobile v6.30 and later,
The RingCentral app had been pinned on the main nav bar
The RingCentral tab had been opened.
The user navigated to other tabs(e.g. to the Chat), then navigate back to the Pined app
When clicking the "Sign In" button, then no reactions. (Expected: It should open in-app popup browser-view)
And then pull to refresh the page, it will then open the login page via the system browser (instead of the in-app browser view, since we have set "isExternal=true")

Some other links that are using the SDK method: app.openLink are also not responding. We will provide more logs if we can collect them.

Workarounds we found:

Unpin the app, and then terminate the Teams client, and reopen it to make everything work as usual.

Note, it is an app that is published on the MS Teams app marketplace. https://teams.microsoft.com/l/app/2f285d77-896a-4c5f-901e-0902316003b5?source=app-details-dialog

The app works well until the MS Teams client upgrades to 6.3.0 on iOS.

More info:

When the app is Pined to the bottom nav bar, and then you navigate to Chat and then back to the app, then click on the HTML button, you will see it is not responded (Or in another word, it seems like the event is not fired, the event-handler of the "click" is not able to handle it).

You can have a try on other apps, like Zoom, 8x8 apps as well. This may ask the MS Teams client app team to have a look?

**Comment by kafka-yu** [comment]
If app is pined to the bottom, above issues occurred.

![IMG_6172](https://github.com/MicrosoftDocs/msteams-docs/assets/3942409/2bcefdb1-adc7-4b89-a7e8-7e72d4cdcd7c)

**Comment by Dinesh-MSFT** [comment]
Hello @kafka-yu - Thanks for raising the query.
We will look into it and let you know the updates.

**Comment by ChetanSharma-msft** [comment]
Hello @kafka-yu - Could you please confirm whether you are trying to develop your own app as well or just referring/using the existing apps published in store?

If you are just using the existing application, then it's the part of Teams product issue.

**Comment by kafka-yu** [comment]
Also developing our own app (RingCentral), this issue is reported by our QA.

**Comment by ChetanSharma-msft** [comment]
We are mainly responsible for Microsoft Teams app development related issues. 

For Microsoft Teams product issues/failures your tenant Admin can reach out to [Microsoft 365 Product Support](https://docs.microsoft.com/en-us/microsoft-365/admin/contact-support-for-business-products?view=o365-worldwide&tabs=online). 

For general questions about Microsoft Teams please post your question on [Microsoft Teams Community](https://answers.microsoft.com/en-us/msteams/forum).

**Comment by Meghana-MSFT** [comment]
We are closing this issue as a duplicate.
