### ISSUE TITLE
Is there any MS Graph API or Powershell available to hide teams for specific owner?

### ISSUE THREAD

**Issue by anomepani** [MicrosoftDocs/msteams-docs#1043]
Currently, we have 1000s Microsoft teams and on a daily basis, 10 to 15 teams are created based on contract and in that special Security group's owners(Company Admin and Other Stakeholders) added as an owner for security reasons in groups.
As this owner is added to every team, their Teams app is too slow and unresponsive due to this all teams loaded in their app.

Is there any Microsoft Graph API or Powershell script available which runs for all teams and hide team for a specific user.
As Hide and UnHide Team feature is available but I didn't find any Graph API.
If you guys can help with this issue it is very helpful to us.
Thanks In Advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38f8810b-ac90-1258-a025-0fb37dc7f48d
* Version Independent ID: 807f4d11-6331-17db-ee65-a9f9ccca65da
* Content: [Concepts - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/concepts-overview)
* Content Source: [msteams-platform/concepts/concepts-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/concepts-overview.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Gousia-MSFT** [comment]
@anomepani Currently there is no API available to hide teams. The only possible way to hide teams is to do it manually from the Teams UI:
![image](https://user-images.githubusercontent.com/45553518/66729645-5f0ad400-ee6a-11e9-95b8-a1e438ea9f54.png)
Please try the Graph API for [Archive team](https://docs.microsoft.com/en-us/graph/api/team-archive?view=graph-rest-1.0) and see if that works in your scenario.

**Comment by anomepani** [comment]
Thanks for reply @Gousia-MSFT. Actually Archive team feature not work for us for moderating and security purposes we are adding security group owner to Microsoft team as an owner. So all this team is active.

Let us know if we can hide somehow automated way for all teams for a specific users with other possible API.
Your suggestion much appreciated.

**Comment by Gousia-MSFT** [comment]
@anomepani Currently there is no automated way to hide teams. The only way to do it is from the Teams UI.
