### ISSUE TITLE
Can an app that uses teams bot and tab be fixed as the first page in a mobile environment?

### ISSUE THREAD

**Issue by minces92** [MicrosoftDocs/msteams-docs#10439]
I created an app using the Teams developer portal. Then, I created a chatbot using a bot and connected it to the bot.

I also discovered that tabs were added when I set up [Personal App] in the Teams Developer Portal, so I added web pages as tabs.

And although I placed the [Chat] tab connected to the bot at the top, the first tab is displayed on the first page on mobile.

Can I pin the first page through chat?

[Capturing the ‘Personal App’ setting value in the developer portal]
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/96893117/dbbe9eee-d1b8-42ad-b492-dcb5b41210d9)

[When running the app on a PC, the first screen is captured as ‘Chat’]
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/96893117/23d8f233-d357-40e2-b293-2e834be40952)

[When running the app on mobile, the first screen is captured as a ‘tab’]
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/96893117/b9f79e36-1c35-4ab2-94d2-0445f2c63cce)

**Comment by minces92** [comment]
안녕하세요 Meghana-MSFT

나는 고객에게 설명해야하기 때문에 공식 답변이 필요합니다.
따라서 한번더 확인겠습니다. 

해당 팀즈 봇 버튼은 팀즈 기본 설계를 따른 것이기 때문에 저렇게 나타나는 것이 정상이며
해당 버튼을 탭으로 내리는 방법은 없다.  라고 고객에게 전달해도 됩니까 ?

**Comment by minces92** [comment]
@Meghana-MSFT Yes, I understand. Thank you for guiding me.

![image](https://github.com/MicrosoftDocs/msteams-docs/assets/96893117/e8330c73-fc36-4740-b2f4-5434660979ee)
So, you can think of the image where the bot icon is exposed as a chat tab as incorrect as per https://learn.microsoft.com/ko-kr/microsoftteams/platform/bots/design/bots.

thank you for response

**Comment by Meghana-MSFT** [comment]
Here the image is correct https://learn.microsoft.com/en-us/microsoftteams/platform/bots/design/bots#mobile-10. Bot icon is in the same place as yours.

**Comment by minces92** [comment]
I understand. Thank you for explaining.

However, other images may be misleading.

thank you

**Comment by minces92** [comment]
> Apologies for the delay in response, this is a by design behavior, we cannot fix chat as the first page in a mobile environment.
> 
> You can click on bot icon to go to the bot chat. ![image](https://private-user-images.githubusercontent.com/81138249/320408267-8eb511c2-4a0d-4a76-a073-4e98cf04af8e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNDUzMTAsIm5iZiI6MTcxMzE0NTAxMCwicGF0aCI6Ii84MTEzODI0OS8zMjA0MDgyNjctOGViNTExYzItNGEwZC00YTc2LWEwNzMtNGU5OGNmMDRhZjhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE1VDAxMzY1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3ODhkN2JjOTZkMGYwMGJlMjVhZGRkNDA1YmYxNjMwMjQ2YjkyOTM2ZWFjODZhMzMyZmU5ZTExMWI4M2IwNzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NbidVjYAxO1-mh2dmfApj33k1lk_XC0CGGvFQWy8-BA)

I am re-reading your response and writing a report.
I'm contacting you with a question about your response.

Is it fixed if it is not the first page?
After testing several times while changing the order of the chat tabs, the mobile chat tab was only exposed as a bot button icon at the top.

thank you

**Comment by Meghana-MSFT** [comment]
Yes, chat tab is exposed as a bot icon at the top.
