### ISSUE TITLE
 Personal static tabs aren't supported in one-on-one conversations with bots in the new Teams client. However, users can open their app from the app bar in Teams and view the personal static tabs.

### ISSUE THREAD

**Issue by GauravES** [MicrosoftDocs/msteams-docs#10449]
[Enter feedback here]
>>The following Teams features aren't currently supported (will be available soon) in the new Teams client:

>> Personal static tabs aren't supported in one-on-one conversations with bots in the new Teams client. However, users can open their app from the app bar in Teams and view the personal static tabs.

With the looming March 31, 2024 deadline for cut over, this bug is crippling many LOB applications that have both chat and Static Tabs that need to work together, i.e CRM apps.     

What is the status of this feature in the new Teams Client?  

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4c405ed3-f304-ff58-d32d-108fc725bb6a
* Version Independent ID: 4c405ed3-f304-ff58-d32d-108fc725bb6a
* Content: [Introducing the new Microsoft Teams client - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/resources/teams-updates)
* Content Source: [msteams-platform/resources/teams-updates.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/resources/teams-updates.md)
* Service: **msteams**
* GitHub Login: @v-ypalikila
* Microsoft Alias: **lajanuar**

**Comment by ChetanSharma-msft** [comment]
Hello @GauravES - Thanks for raising your query.
We will check on the updates and let you know.

**Comment by ChetanSharma-msft** [comment]
Hello @GauravES - This issue is fixed and released.
Kindly verify and let us know if you are still facing this issue.
