### ISSUE TITLE
Reading the Teams Activity feed

### ISSUE THREAD

**Issue by nicojdejong** [MicrosoftDocs/msteams-docs#1044]
Hi content writers,

I can see in the documentation descriptions of posting to the activity feed but not reading it. Is that possible? I also checked Graph API 1.0 documentation and it is not there under team work and under activity feed there it seems not to refer to MS teams but to Windows 10 TimeLine etc. Can you be more explicit about reading the Team activity feed programmatically? Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd0d8d78-1ad5-5a99-3ef9-b03124476ebf
* Version Independent ID: 64505c8a-4f08-0454-2602-8821ca29c218
* Content: [Activity feed - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/activity-feed#feedback)
* Content Source: [msteams-platform/concepts/activity-feed.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/activity-feed.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Gousia-MSFT** [comment]
@nicojdejong Currently there is no way to read the activity feed of a user. You can only send notifications through activity feed but not read.
