### ISSUE TITLE
Is there any full working demo for Silent SSO Authentication in Teams Tab with different clientId

### ISSUE THREAD

**Issue by anomepani** [MicrosoftDocs/msteams-docs#1045]
Is there any full working demo for Silent SSO Authentication in Teams Tab with different clientId?
Using adal.js I am able to redirect in Microsoft Teams Web Version using clientId but Desktop Microsoft teams app not returning back only showing a blank screen.
Redirection not working in Desktop MS Team App.
Does code available in C# or javascript langauge ?

Thanks In Advance

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be314181-4800-4d02-cf62-fb276dc7cdd2
* Version Independent ID: 259e41a3-0607-c3f8-f635-f6bce767ad2b
* Content: [Silent authentication and SSO - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/authentication/auth-silent-aad)
* Content Source: [msteams-platform/concepts/authentication/auth-silent-AAD.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/authentication/auth-silent-AAD.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Ky7m** [comment]
@anomepani did you check this project https://github.com/OfficeDev/msteams-sample-contoso-hr-talent-app, specifically 
https://github.com/OfficeDev/msteams-sample-contoso-hr-talent-app/blob/master/TeamsTalentMgmtApp/src/TeamsTalentMgmtAppV4/StaticViews/OpenPositionsPersonalTab.html

**Comment by anomepani** [comment]
@Ky7m Thanks for the reply. Let me take a look. I want to create an app for ms teams that will work for multi-tenancy based on Microsoft graph delegated permission. I am stuck with redirection in the Microsoft Team Desktop version installed app.

**Comment by Trinetra-MSFT** [comment]
Please take a look at [msteams-sample-contoso-hr-talent-app](https://github.com/OfficeDev/msteams-sample-contoso-hr-talent-app) which have SSO implementation for tabs. Let us know if you need any assist on that.

**Comment by anomepani** [comment]
@Trinetra-MSFT  Thanks for the reply. I will take a look and let you know if it works or not.

**Comment by anomepani** [comment]
Thank you @Trinetra-MSFT and @Ky7m I am able to integrate and test provided solution reference for SSO Login with ClientID in Web version of Microsoft Teams.

If I am logged into **Microsoft Teams Desktop App** and Go to my app in teams app and open my app it will not auto-login. It is showing **"Sign In"** Button.

When I Sign In it will redirect to Microsoft login page in popup and prompting credential.

Can you provide way to resolve this issue?

**Comment by infact** [comment]
In teams users are already logged in.Then why asking to authenticate again? The bot should be able to silently identify the user and move on ?

**Comment by anomepani** [comment]
I am not sure why it's asking credential but it is asking credential and it is prompting Microsoft login popup.

**Comment by Trinetra-MSFT** [comment]
Currently there is only Silent Authentication supported in Microsoft Teams. For any third party app, you needs to Sign In at least once to consent. If you logout from Teams client then it clears out the cache and your needs to Sign In again. Please try out [Auth Sample manifest](https://github.com/OfficeDev/microsoft-teams-sample-auth-node/blob/master/manifest/AuthBot.zip) to see the experience.

**Comment by anomepani** [comment]
Thanks, @Trinetra-MSFT  for feedback and I will look into provided Auth Sample Manifest and get back to you if I need help.
Thanks again for the support.
