### ISSUE TITLE
Will tabs of bot apps be opened inside Teams or in an external browser (starting April 2024)?

### ISSUE THREAD

**Issue by sueess** [MicrosoftDocs/msteams-docs#10458]
Hi there

I do not find any information, if the announcement "MC708500" (https://petri.com/microsoft-changelog/m365-changelog-changes-to-the-website-tab-in-the-new-teams-client/) has any impact on the tabs of bot apps (https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs?tabs=desktop%2Cdesktop1%2Cpersonal)?

Will tabs defined in the manifest still open as a tab or will it open a window in the web browser? Thanks for some information.

**Comment by Prasad-MSFT** [comment]
Hi @sueess - Microsoft Teams will be retiring the ability to load websites inside the new Teams client when using the **Website tab**. These website links will open in a new browser tab instead.
https://m365admin.handsontek.net/changes-to-the-website-tab-in-the-new-teams-client/
This is only applicable to [Websites tab](https://devblogs.microsoft.com/microsoft365dev/upcoming-updates-to-loading-websites-in-teams-tabs/#:~:text=The%20Website%20tab%20allows%20you%20to%20pin%20and,your%20tab%20a%20name%20and%20enter%20a%20URL.) as mentioned. Tabs defined in the manifest still open as a tab.

**Comment by sueess** [comment]
Thanks for the link and the clarification!

**Comment by Prasad-MSFT** [comment]
@sueess - Could you please share your valuable feedback via [Microsoft Teams Developer Community Response Feedback](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR7iCOpS5_b9Nqmwx43u5rtZUOThVR081SllSR05aSDQxQ0tUMDVPTVIxTi4u) link?
