### ISSUE TITLE
can't get webhook event for OneDrive share event

### ISSUE THREAD

**Issue by ComSheep** [MicrosoftDocs/msteams-docs#10467]
### Type of issue

Missing information

### Feedback

Hi
I am integrating with OneDrive. I can get webhook event when Drive File Owner edit/create a file. But I can't get webhook event when file owner share his/her file to another person. How can I get share webhook event ? Thanks for you reply!

### Page URL

test

### Content source URL

https://NA

### Author

colinblacktea@sina.com

### Document Id

test

**Comment by Vaibhav-MSFT** [comment]
Hello @ComSheep, 
Thanks for reporting your issue. We will test this and update you soon.

**Comment by ComSheep** [comment]
Hi @Vaibhav-MSFT 
Thank you. Look forward to your reply.

**Comment by ComSheep** [comment]
Hi @Vaibhav-MSFT 
do you have any update on this issue ? Thanks!

**Comment by ChetanSharma-msft** [comment]
Hello @ComSheep - Could you please share repro steps and documentation so that we can try it from our end?
Also, please let us know if you are developing any Teams application.

**Comment by ComSheep** [comment]
Hi @ChetanSharma-msft  Thanks!
I am following this wiki (https://learn.microsoft.com/en-us/onedrive/developer/rest-api/api/subscription_post_subscriptions?view=odsp-graph-online) to subscribe webhook event.  the resource is /me/drive/root.
But I can't get webhook event when someone else shares a file to me.

**Comment by ComSheep** [comment]
can you please help instruct how can I receive webhook event when I am shared with files ?

**Comment by Vaibhav-MSFT** [comment]
Hello @ComSheep ,
Can you let us know if you are developing Teams application?

**Comment by ComSheep** [comment]
Hi @Vaibhav-MSFT 
No. I am not developing Teams application. But I wonder is this related to the issue ?

**Comment by ComSheep** [comment]
Hi @Vaibhav-MSFT @ChetanSharma-msft 
Hi, do we have any update on this issue ? Thanks!

**Comment by ChetanSharma-msft** [comment]
Hello @ComSheep,
We are mainly responsible for Microsoft Teams app development related issues. 

For Microsoft Teams product issues/failures your tenant Admin can reach out to [Microsoft 365 Product Support](https://docs.microsoft.com/en-us/microsoft-365/admin/contact-support-for-business-products?view=o365-worldwide&tabs=online). 

For general questions about Microsoft Teams please post your question on [Microsoft Teams Community](https://answers.microsoft.com/en-us/msteams/forum).

Please raise your issue [here](https://github.com/onedrive/onedrive-api-docs/issues/new?title=&body=%0A%0A%5BEnter%20feedback%20here%5D%0A%0A%0A---%0A%23%23%23%23%20Document%20Details%0A%0A%E2%9A%A0%20*Do%20not%20edit%20this%20section.%20It%20is%20required%20for%20learn.microsoft.com%20%E2%9E%9F%20GitHub%20issue%20linking.*%0A%0A*%20ID%3A%20f0409421-4fe0-6f2b-1a68-e7bb707cb51e%0A*%20Version%20Independent%20ID%3A%205c43e484-ba8e-48d1-0501-c75a6d35e38c%0A*%20Content%3A%20%5BCreate%20a%20webhook%20subscription%20-%20OneDrive%20API%20-%20OneDrive%20dev%20center%5D(https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fonedrive%2Fdeveloper%2Frest-api%2Fapi%2Fsubscription_post_subscriptions%3Fview%3Dodsp-graph-online)%0A*%20Content%20Source%3A%20%5Bdocs%2Frest-api%2Fapi%2Fsubscription_post_subscriptions.md%5D(https%3A%2F%2Fgithub.com%2FOneDrive%2Fonedrive-api-docs%2Fblob%2Flive%2Fdocs%2Frest-api%2Fapi%2Fsubscription_post_subscriptions.md)%0A*%20Service%3A%20**one-drive**%0A*%20GitHub%20Login%3A%20%40JeremyKelley%0A*%20Microsoft%20Alias%3A%20**JeremyKe**).

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, please feel free to reopen it, if required.

**Comment by ComSheep** [comment]
@ChetanSharma-msft 
Thank you!
