### ISSUE TITLE
Outdated layout examples and tags.

### ISSUE THREAD

**Issue by Terningen** [MicrosoftDocs/msteams-docs#10468]
### Type of issue

Outdated article

### Feedback

```
{
	"@type": "MessageCard",
	"@context": "http://schema.org/extensions",
	"themeColor" : "00FF00",
	"summary" : "AAAA",
	"sections" : [{
		"activityTitle" : "BBB",
		"activitySubtitle" : "CCC",
		"activityImage" : "https://image.png",
		"facts" :[{
			"name" : "Pull Request / Commit",
			"value" : "Merged PR 17388: Font Awesome"
		},{
			"name" : "Branch",
			"value" : "refs/heads/develop"
		},{
			"name" : "environment",
			"value" : "enviromentName"
		}]
	}],
	"markdown": true,
	"potentialAction": [
    {
      "@type": "OpenUri",
      "name": "Go to build",
      "targets": [
        {
          "os": "default",
          "uri": "https://google.dk"
        }
      ]
    },
    {
      "@type": "OpenUri",
      "name": "Go to another build",
      "targets": [
        {
          "os": "default",
          "uri": "https://www.google2.com"
        }
      ]
    }
  ]
}
```

This markup does not work with colors
This markup "facts", are not tabbed in as show in examples (making it easy to read). 
(name not fat, missing indentation)

Something is wrong with how teams reads the json, evnetho its a MessageCard. 
Also it looks differencet on mac, pc and android phone.

### Page URL

https://learn.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?tabs=adaptive-md%2Cdesktop%2Cconnector-html

### Content source URL

https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/task-modules-and-cards/cards/cards-format.md

### Author

@surbhigupta

### Document Id

e5f5f69e-66e9-d1b2-e19a-485d0ffcd6fa

**Comment by Vikram-MSFT** [comment]
Hello @Terningen Could you please provide some more information on the issue ?

**Comment by Prasad-MSFT** [comment]
@Terningen - We tried with the JSON provided and this is how it is getting rendered in Teams Desktop and Android client respectively.
Desktop:
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/62237649/8cfedbbc-ec78-4e63-9866-2e402b563f36)

Android:
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/62237649/5e889081-8a9d-4983-9987-55d08a3863f9)


Is this what you are also encountering?
