### ISSUE TITLE
Additional Clarity Needed on Compliance Boundaries

### ISSUE THREAD

**Issue by jpalarchio** [MicrosoftDocs/msteams-docs#10466]
### Type of issue

Missing information

### Feedback

This statement in the article could use more clarity:  "By adding your chatbot to Microsoft Teams, some of the data, such as bot content and user chat content, is shared with Teams. It means that your data flows outside of your organization’s compliance and geographic or regional boundaries."

Are we talking about data at rest, data in transit?  Can you provide some examples of when this would occur?  Is this mitigated by publishing the PVA in a region that matches the M365 tenant region?

### Page URL

https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/add-power-virtual-agents-bot-to-teams

### Content source URL

https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/bots/how-to/add-power-virtual-agents-bot-to-teams.md

### Author

@surbhigupta

### Document Id

dddc2210-7f53-fbfb-7905-a52d9acd0e23

**Comment by Vikram-MSFT** [comment]
Hello @jpalarchio, we are checking with engineering team and once we get any response, we will inform you back.

**Comment by ChetanSharma-msft** [comment]
Hello @jpalarchio - Could you please refer this documentation: https://learn.microsoft.com/en-us/microsoft-copilot-studio/data-location?tabs=web#customer-data
