### ISSUE TITLE
Good article

### ISSUE THREAD

**Issue by chenxizhang** [MicrosoftDocs/msteams-docs#1047]
Good writing

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c8cce1c-c091-090d-82de-13a57834e240
* Version Independent ID: 13f73468-3c62-d612-dd69-82b43ec31e95
* Content: [Add tabs to Microsoft Teams apps - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/tabs/tabs-overview)
* Content Source: [msteams-platform/concepts/tabs/tabs-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/tabs/tabs-overview.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Gousia-MSFT** [comment]
@chenxizhang Thanks for the feedback!
