### ISSUE TITLE
[Meta OS - Outlook] The adaptive card action button containing a deeplink to the Teams app is not displaying.

### ISSUE THREAD

**Issue by PjPraveenkumar** [MicrosoftDocs/msteams-docs#10475]
### Type of issue

Missing information

### Feedback

Hello Team,
Currently, we are utilizing a Messaging Extension (ME) to invoke an adaptive card in Outlook. While Outlook displays the adaptive card, it does not render the action button.
Action button containing deep link to teams app with encoded URI (e.g., https://teams.microsoft.com/l/entity/0fefc099-ff7d-45ce-ad27-fa798ed6e8f5/com.microsoft.teams.taskmodule.statictab?context=%7B%22subEntityId%22:%20%22topic1%22%7D). 
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/161592567/2da394b4-beb3-4169-8495-476af54665f5)
"Deeplink to tab" action button in teams:
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/161592567/265dad31-275d-4e58-b6a9-12b15d5fbd0b)

"Deeplink to tab" action button is missing in outlook:
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/161592567/6a86cf37-c4d6-4cb4-a346-b91c792f522c)

Initially, we considered the possibility of a bug or an unsupported scenario for Outlook. However, after an internal discussion with the Meta OS Outlook team, it was confirmed that this scenario of deeplink to Teams app with encoded URI is currently not supported in Meta OS Outlook. Therefore, please update the document with the respective notes reflecting this information.

### Page URL

https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-link-application?tabs=teamsjs-v2

### Content source URL

https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/build-and-test/deep-link-application.md

### Author

@v-npaladugu

### Document Id

059b1a94-8235-8801-b9e0-ac6fbc485a7c

**Comment by Dinesh-MSFT** [comment]
Hi @PjPraveenkumar - Thanks for raising the query.
We will look into it and let you know the updates.

**Comment by Dinesh-MSFT** [comment]
Hi @surbhigupta12 - Please update the doc https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-link-application?tabs=teamsjs-v2 with the following note - deep link to Teams app with encoded URI is currently not supported in Meta OS Outlook

**Comment by SubbaReddi** [comment]
@surbhigupta12 : Can you assist with above document update?
