### ISSUE TITLE
Response format table does not have link and have TODO: 

### ISSUE THREAD

**Issue by ChetanSharma-msft** [MicrosoftDocs/msteams-docs#10478]
### Type of issue

Missing information

Please check and update the details.
![image](https://github.com/MicrosoftDocs/AdaptiveCards/assets/59052547/a6f6d94b-7b27-4e0a-a9cb-9c1c0266f16d)

### Page URL

https://learn.microsoft.com/en-us/adaptive-cards/authoring-cards/universal-action-model#response-format

### Content source URL

https://learn.microsoft.com/en-us/adaptive-cards/authoring-cards/universal-action-model#response-format

### Author

@surbhigupta

### Document Id

fcfc4f00-f3c3-1cf0-2a4a-c7fda27be1a1

**Comment by Prasad-MSFT** [comment]
Hi @surbhigupta12 - Could you please help here to update the document?

**Comment by surbhigupta12** [comment]
@Prasad-MSFT, we do not have access to this repo. Can you please raise an issue on the AC repo. Hence, removing the label.

**Comment by ChetanSharma-msft** [comment]
Raised this issue here: https://github.com/MicrosoftDocs/AdaptiveCards/issues/542

**Comment by ChetanSharma-msft** [comment]
Closing this issue as it's a duplicate.
