### ISSUE TITLE
calendar.isSupported returns false with Teams host

### ISSUE THREAD

**Issue by alexisconia** [MicrosoftDocs/msteams-docs#10474]
### Type of issue

Code doesn't work

### Feedback

The documentation has the following code:
```javascript
// Open a scheduling dialog from your tab
if(calendar.isSupported()) {
   const calendarPromise = calendar.composeMeeting({
      attendees: ["joe@contoso.com", "bob@contoso.com"],
      content: "test content",
      endTime: "2018-10-24T10:30:00-07:00",
      startTime: "2018-10-24T10:00:00-07:00",
      subject: "test subject"});
   calendarPromise.
      then((result) => {/*Successful operation*/}).
      catch((error) => {/*Unsuccessful operation*/});
}
else { /* handle case where capability isn't supported */ }
```
It's ok if the behavior with Teams Host is to return false but the documentation tells "You can also use TeamsJS library 2.0 in your Teams app to open the meeting scheduling dialog without having to manually prepare the link."
It could be helpful to remove Teams app reference and avoid confusion.

### Page URL

https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-link-workflow?tabs=teamsjs-v2#configure-deep-link-using-teamsjs-library-to-open-a-meeting-scheduling-dialog

### Content source URL

https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/build-and-test/deep-link-workflow.md

### Author

@v-npaladugu

### Document Id

98d88f26-f11f-4810-162a-40ca552be3e3

**Comment by Dinesh-MSFT** [comment]
Hi @alexisconia - Thanks for raising the query.
We will look into it and let you know the updates.
