### ISSUE TITLE
Incorrect tabbing order observed on the new tile card appeared in the page and not focusable through tab key after the message was sent

### ISSUE THREAD

**Issue by liuguangyicao** [MicrosoftDocs/msteams-docs#10485]
### Steps to reproduce

# Description
With Voice - When user navigate to the input field and type "request feedback", he would get a message card.-> Observe that, new tile card appeared on the page after the message was sent, but keyboard focus is not moving to the new tile card's actionable element which is incorrect tabbing order. Also it did not announce the title of the card and missed the 'Request Feedback' label name when getting the message card.

# Video
https://github.com/MicrosoftDocs/msteams-docs/assets/25132507/05da27aa-7d51-476b-8571-1d57ef8a6776

# Card Json
```
{
          "$schema":  "http://adaptivecards.io/schemas/adaptive-card.json",
          "type":  "AdaptiveCard",
          "version":  "1.5",
          "body":  [
                    {
                              "type":  "TextBlock",
                              "text":  "I found this quick action for you to proceed with the task:",
                              "wrap":  true,
                              "size":  "Medium"
                    },
                    {
                              "type":  "ActionSet",
                              "spacing":  "ExtraLarge",
                              "actions":  [
                                        {
                                                  "type":  "Action.Submit",
                                                  "tooltip":  "Request Feedback",
                                                  "title":  "Request Feedback",
                                                  "data":  {
                                                            "msteams":  {
                                                                      "type":  "task/fetch"
                                                            },
                                                            "ref":  "REQUEST_FEEDBACK",
                                                            "requestType":  "command",
                                                            "namespace":  "worktech-feedback",
                                                            "selectUserId":  "802989",
                                                            "step":  "requestFeedbackFormStep",
                                                            "command":  "RequestFeedback"
                                                  }
                                        }
                              ]
                    }
          ],
          "msteams":  {
                    "width":  "Full"
          }
}
```

### Expected behavior

Ensure that tabbing order should be in the logical reading order. After the message sent, focus should move to new tile card's actionable element and should be accessible with keyboard and read out by screenreader along with the label name,

### Actual behavior

Keyboard focus is not moving to the new tile card's actionable element which is incorrect tabbing order and the title of the card 'Request Feedback' is announced when getting the message card.

**Comment by ChetanSharma-msft** [comment]
Hello @liuguangyicao - Thanks for raising your query.
We will look into it and let you know the updates.

**Comment by Vaibhav-MSFT** [comment]
Hello @liuguangyicao 
Sorry for the delay in response,
We have raised a bug for the same. We will inform you once we get any further update from engineering team.
Thanks!!

**Comment by Prasad-MSFT** [comment]
Hi @liuguangyicao, we got update from engineering team stating that, they are able to navigate through the card via tabbing and there is no title to the card - additionally, we only honor the `speak` property for narration if developer wants to add specific text to be read out when the card receives focus.
