### ISSUE TITLE
Important typo in note

### ISSUE THREAD

**Issue by limp15000** [MicrosoftDocs/msteams-docs#10480]
### Type of issue

Typo

### Feedback

Documentation states Message extensions are available in GCC, but I assume it was indented to say ARE NOT supported. 
Thank you in advance for fixing :)

### Page URL

https://learn.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/what-are-messaging-extensions?tabs=desktop&source=docs

### Content source URL

https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/messaging-extensions/what-are-messaging-extensions.md

### Author

@surbhigupta

### Document Id

d5c2d24a-def4-af2e-7983-c73cf7f22934

**Comment by Dinesh-MSFT** [comment]
Hi @limp15000 - Thanks for raising the query.
We will look into it and let you know the updates.
