### ISSUE TITLE
Please make it clear on the page that an app must call setValidityState(true) in order to light up the "Remove" button and in order for their remove handler to get invoked.

### ISSUE THREAD

**Issue by FelicityRooting** [MicrosoftDocs/msteams-docs#10482]
### Type of issue

Outdated article

### Feedback

https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/removal-page?tabs=teamsjs-v2#see-also
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/21963958/e5d6a044-5968-49d8-954e-0d2a0aacb196)
The text here is not accurate, users are confused here https://github.com/OfficeDev/microsoft-teams-library-js/issues/1825#issuecomment-1714228220

We need to make it clear on the page that an app must call setValidityState(true) in order to light up the "Remove" button and in order for their remove handler to get invoked.

### Page URL

https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/removal-page?tabs=teamsjs-v2#see-also

### Content source URL

https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/tabs/how-to/create-tab-pages/removal-page.md

### Author

@surbhigupta

### Document Id

54aca1c7-403d-6da6-0e25-98194da71d65

**Comment by Vikram-MSFT** [comment]
Hello @FelicityRooting 
Could you please help us with the documentation as suggested?
