### ISSUE TITLE
Teams bot app is not showing in mobile (iOS/Android)

### ISSUE THREAD

**Issue by SubbaReddi** [MicrosoftDocs/msteams-docs#10481]
### Type of issue

Missing information

### Feedback

If the manifest has empty command list as shown below, the respective bot app is not showing in mobile. It shows and works fine in web/desktop teams.
It seems this is expected behavior in mobile. So, mentioning note in documentation will be helpful.

"bots": [{
			"botId": "",
			"needsChannelSelector": false,
			"scopes": [
				"personal", "team", "groupchat"
			],
			**"commandLists": [{
					"scopes": [
						"personal"
					],
					"commands": []
			}
		],**
		"isNotificationOnly": false
	}

### Page URL

https://learn.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema#bots

### Content source URL

https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/resources/schema/manifest-schema.md

### Author

@surbhigupta

### Document Id

7b3413f4-9ade-accf-5cb2-83fead11a32a

**Comment by Dinesh-MSFT** [comment]
Hi @SubbaReddi - Thanks for raising the query.
We will look into it and let you know the updates.

**Comment by ChetanSharma-msft** [comment]
@surbhigupta12 - Please help to update the documentation.
