### ISSUE TITLE
Static tabs are now extended to chats, meetings and channels. "Channels" is missing from the text on the page.

### ISSUE THREAD

**Issue by richa008** [MicrosoftDocs/msteams-docs#10497]
### Type of issue

Missing information

### Feedback

The title "Extend static tabs to group chat and meetings" should say "Extend static tabs to group chat, meetings and channels". The text in the paragraph below should also include channels. The title "Customizing your static tab in chats or meetings" should also include Channels. The static tabs feature is now supported in chats. meetings and channels.

### Page URL

https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?tabs=vs&pivots=node-java-script#extend-static-tabs-to-group-chat-and-meetings

### Content source URL

https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/tabs/how-to/create-personal-tab.md

### Author

@laujan

### Document Id

6d43a761-19e0-541e-ba06-170099411ac1

**Comment by Dinesh-MSFT** [comment]
@surbhigupta12 - Could you please help to update the document to include channel as well.
