### ISSUE TITLE
List Card : Icon Images were not loading in New Teams

### ISSUE THREAD

**Issue by Vena-Kanavi** [MicrosoftDocs/msteams-docs#10496]
I'm experiencing a problem where images are loading in Classic (old) Teams but not in New Teams, but when I click somewhere inside teams images were loading but loads same image for both tasks. Can you please assist me with resolving this issue?

images are not loading in new teams
![Capture](https://github.com/MicrosoftDocs/msteams-docs/assets/72905178/45a0df7d-8478-4400-ac1b-6a330c3ea7f0)

images are loading properly in classic teams
![Capture1](https://github.com/MicrosoftDocs/msteams-docs/assets/72905178/f36ab72c-1080-4091-95c9-1c65c56d9a91)

**Comment by Vena-Kanavi** [comment]
@Vaibhav-MSFT No still we are facing the same issue, but if we click anywhere inside card or outside card image is flickering.

FYR
https://github.com/MicrosoftDocs/msteams-docs/assets/72905178/22460431-1a67-494d-a681-106fd5ecbe04

**Comment by Vaibhav-MSFT** [comment]
Hello @Vena-Kanavi 
Sorry for the delay in response.
We tested this and observed that the Icon Images are not loading New Teams Web Client, whereas working fine in Classic Teams and New Teams Desktop Client.
Can you please confirm if you are also this issue only in New Teams Web Client?
Thanks!!

**Comment by Vena-Kanavi** [comment]
Hi @Vaibhav-MSFT 
Thank you for the update. It seems that the issue is occurring in both the New Teams Web Client and the New Teams Desktop Client for us.

**Comment by Vena-Kanavi** [comment]
@Vaibhav-MSFT  I have tried it in Teams Desktop client, still I see flickering of image.

**Comment by Vaibhav-MSFT** [comment]
Hello @Vena-Kanavi ,
Thanks for the confirmation. We are able to repro the issue in both New Teams Web and desktop client, we have raised the bug for the same and will keep you posted on the updates. Thank you!!

**Comment by Prasad-MSFT** [comment]
@Vena-Kanavi, we got update from engineering team that the issue is fixed. Please do verify.
