### ISSUE TITLE
Typeahead + Adaptive Cards - submit button doesn't work

### ISSUE THREAD

**Issue by CodeABao** [MicrosoftDocs/msteams-docs#10493]
### Steps to reproduce

I build a bot function with typeahead, it works fine since 2023-10-01. 
these few days many users told me it doesn't works well, the submit button not working.

Card json：
{
  "type": "AdaptiveCard",
  "actions": [
    {
      "type": "Action.ShowCard",
      "title": "Details",
      "card": {
        "type": "AdaptiveCard",
        "body": [
          {
            "type": "Input.Text",
            "id": "comment",
            "placeholder": "Case Title",
            "isRequired": true
          },
          {
            "choices": [],
            "id": "casetype",
            "type": "Input.ChoiceSet",
            "placeholder": "Case Type",
            "style": "filtered",
            "isRequired": true,
            "choices.data": {
              "type": "Data.Query",
              "dataset": "casetypes"
            }
          }
        ],
        "actions": [
          {
            "type": "Action.Execute",
            "title": "Submit",
            "data": "${data}",
            "verb": "SendWithComments"
          }
        ],
        "$schema": "https://adaptivecards.io/schemas/adaptive-card.json"
      }
    }
  ],
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "version": "1.4"
}

### Expected behavior

submit data to bot

### Actual behavior

no response

### Error details

Microsoft Teams version 24033.807.2716.7297.

**Comment by Prasad-MSFT** [comment]
@CodeABao - Thanks for raising your issue. We will check this at our end and will update you accordingly.

**Comment by Prasad-MSFT** [comment]
@CodeABao - We tried to repro this issue using below sample: 
https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/bot-type-ahead-search-adaptive-cards/nodejs
and it was working fine in both Teams Classic and New Teams as follows:
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/62237649/e57dfb75-a7ff-4657-af7c-cadaac6fb9ca)
However, when we added required field to the scenario, static search worked, but dynamic search didn't work as below (Both in New Teams and Classic Teams):
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/62237649/f4747792-d6d5-405f-91c2-c86a29d38b7a)
JSON Used:
```
{
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.2",
    "type": "AdaptiveCard",
    "body": [
      {
        "text": "Please search for npm packages using dynamic search control.",
        "wrap": true,
        "type": "TextBlock"
      },
      {
        "columns": [
          {
            "width": "auto",
            "items": [
              {
                "text": "NPM packages search: ",
                "wrap": true,
                "height": "stretch",
                "type": "TextBlock"
              }
            ],
            "type": "Column"
          }
        ],
        "type": "ColumnSet"
      },
      {
        "columns": [
          {
            "width": "stretch",
            "items": [
              {
                "choices": [
                  {
                    "title": "Static Option 1",
                    "value": "static_option_1"
                  },
                  {
                    "title": "Static Option 2",
                    "value": "static_option_2"
                  },
                  {
                    "title": "Static Option 3",
                    "value": "static_option_3"
                  }
                ],
                "isMultiSelect": false,
                "style": "filtered",
		"isRequired": true,
                "choices.data": {
                  "type": "Data.Query",
                  "dataset": "npmpackages"
                },
                "id": "choiceselect",
                "type": "Input.ChoiceSet"
              }
            ],
            "type": "Column"
          }
        ],
        "type": "ColumnSet"
      }
    ],
    "actions": [
      {
        "type": "Action.Submit",
        "id": "submitdynamic",
        "title": "Submit"
      }
    ]
  }
```
Could you please let us know if you are encountering the same behaviour?

**Comment by CodeABao** [comment]
@Prasad-MSFT  Yes, great, same behaviour. it works when i remove the required field. This method temporarily solves my problem. but i think this is a bug not by design,right?  
The engineer who developed this feature should have his bonus deducted. Encountered this feature error twice.

**Comment by Prasad-MSFT** [comment]
@CodeABao - Thanks for confirming. We have raised a bug for the same. We will inform you once we get any further update from engineering team.

**Comment by Prasad-MSFT** [comment]
Hi @CodeABao , This issue is fixed. Please do verify.
We tested with `Microsoft Teams version 24130.2000.2868.6769.`
`The client version is 49/24050922000.`

**Comment by CodeABao** [comment]
> Hi @CodeABao , This issue is fixed. Please do verify. We tested with `Microsoft Teams version 24130.2000.2868.6769.` `The client version is 49/24050922000.`

it's works, thanks.
