### ISSUE TITLE
Point out manifestVersion for DevPreview

### ISSUE THREAD

**Issue by afrischk** [MicrosoftDocs/msteams-docs#1050]
Please make it more clear what manifestVersion is needed for the DevPreview.
For parsing the DevPreview schema it is necessary to use 'devPreview' as the manifestVersion.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 379bdae4-b9d3-bc6e-ecbd-264108d76cd2
* Version Independent ID: b40d773f-d0fd-983f-f063-b3409bdedcef
* Content: [Registering a calling and meeting bot for Microsoft Teams - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/calls-and-meetings/registering-calling-bot#feedback)
* Content Source: [msteams-platform/concepts/calls-and-meetings/registering-calling-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/calls-and-meetings/registering-calling-bot.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Trinetra-MSFT** [comment]
If you want your IDE to properly validate the manifest.json schema for your calling and meeting bot than using Dev preview version is necessary as documented.

**Comment by afrischk** [comment]
> 
> 
> If you want your IDE to properly validate the manifest.json schema for your calling and meeting bot than using Dev preview version is necessary as documented.

Maybe I misunderstood the comment, but what I meant was: If you want to side-load the bot in Teams with the manifest.json schema Dev preview (e.g. with added supportsCalling property), then you also have to set the manifestVersion property in the manifest.json to the value 'devPreview'. This is not documented and causes issues like [this](https://github.com/microsoftgraph/microsoft-graph-comms-samples/issues/14#issuecomment-510734676)

**Comment by clearab** [comment]
Hi - You can find the documentation for the Developer Preview program here: https://docs.microsoft.com/en-us/microsoftteams/platform/resources/dev-preview/developer-preview-intro

I'll update that section to include a link to the full developer preview documentation
