### ISSUE TITLE
Unable to show adaptive card inside outlook popup when clicked to share to outlook in MS teams

### ISSUE THREAD

**Issue by Utsav101** [MicrosoftDocs/msteams-docs#10500]
### Steps to reproduce

Steps to reproduce:

1. logon Teams
2. Open one chat with one person
3. Post a link which will generate an adaptive card.

<img width="1296" alt="Screenshot 2024-03-05 at 09 37 58" src="https://github.com/MicrosoftDocs/msteams-docs/assets/37326500/c16c8c76-aafa-48d5-9c02-34e4fe7ec918">

4. Hover over the chat. In the reaction popover, click on '...'
5. From the options available, click on Share to Outlook.
6. Outlook pop-up come up. Check if an adaptive card is created inside the email body.

### Expected behavior

Adaptive card should have been created inside outlook popup.

### Actual behavior

Adaptive card is not created inside outlook popup.

<img width="808" alt="Screenshot 2024-03-05 at 09 38 47" src="https://github.com/MicrosoftDocs/msteams-docs/assets/37326500/f3907774-bfb3-4af0-9094-f03b70867df9">

**Comment by Dinesh-MSFT** [comment]
We are also able to repro this issue, we will check this internally and get back to you.

**Comment by Dinesh-MSFT** [comment]
Hi @Utsav101 - Currently Adaptive cards are not supported in Share to Outlook.

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, please feel free to reopen it, if required.
