### ISSUE TITLE
Update document to include support to msteams:// protocol for deep links.

### ISSUE THREAD

**Issue by cadasi** [MicrosoftDocs/msteams-docs#10518]
### Type of issue

Missing information

### Feedback

We need to include information about the support of the msteams:// protocol for Deeplinks. T1 supported that and T2 not, but because of parity and customers escalations as a blocker to their business, a fix was released to make sure msteams:// is supported. Our article does not mention that and does not leave that clear, which can cause issues with customer escalations in the future without a reference to documentation saying that this is a supported usage. If there's desire to deprecate msteams:// in the future, that should still be mentioned in the article and information should be given for clarity. Announcement would need to be made to make sure customers are aware of future deprecation.
The fix is currently rolling out, reference [work item:](https://domoreexp.visualstudio.com/MSTeams/_workitems/edit/3635678)
Please reach out to Pulkit Sharma and Yuri Dogandjiev to discuss this and identify the PM responsible for helping in updating the documentation as I cannot provide all the details that are needed to make sure for correctness.  

### Page URL

https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-link-workflow?tabs=teamsjs-v2#configure-deep-link-manually-to-start-audio-video-call-with-users

### Content source URL

https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/build-and-test/deep-link-workflow.md

### Author

@v-npaladugu

### Document Id

98d88f26-f11f-4810-162a-40ca552be3e3

**Comment by Prasad-MSFT** [comment]
@cadasi -  Thanks for raising this. We will discuss internally and will take necessary action.
