### ISSUE TITLE
Is it possible to create a deep link to chat in Task Module?

### ISSUE THREAD

**Issue by paul-cheung** [MicrosoftDocs/msteams-docs#1051]
According to [deep-linking-to-a-chat](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/deep-links#deep-linking-to-a-chat).

i am building a deep link to a chat in my Teams Tab like below:
https://teams.microsoft.com/l/chat/0/0?users=xx@xxx.com&topicName=Prep%20For%20Meeting%20Tomorrow&message=Hi%20folks%2C%20kicking%20off%20a%20chat%20about%20our%20meeting%20tomorrow
 
Tab Page:
![image](https://user-images.githubusercontent.com/4626647/66761542-d0806c00-eed6-11e9-8d16-d307828a4291.png)
When i click the link, it shows the following screen.
![image](https://user-images.githubusercontent.com/4626647/66761473-acbd2600-eed6-11e9-9b9e-18c4a271dd21.png)

The real senario is:
1. a button/link in **Task Module**.
2. clicking the button/link will take me to a chat.

I have tried deep link to chat in Task Module, And the result is same as that in Tab page.

So, is it possible to meet this requirement now?

**Comment by Ky7m** [comment]
@paul-cheung, did you try `microsoftTeams.executeDeepLink(/*deepLink*/);`?
https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/deep-links#deep-linking-from-your-tab

**Comment by Trinetra-MSFT** [comment]
@paul-cheung , Could you please take a look at [Task module deep link syntax](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/task-modules/task-modules-overview#task-module-deep-link-syntax)? Let me know if you face any issue.

**Comment by paul-cheung** [comment]
@Ky7m @Trinetra-MSFT thanks, maybe i am picking the wrong thing to do this. i will try it later.

**Comment by paul-cheung** [comment]
@Trinetra-MSFT i want to build a link in Task Module, and clicking that link will take me to chat screen.
The docs link you provided is for building a link to open a Task Module instead. so they are not the same thing, thanks all the same.

@Ky7m You helped, thanks.
