### ISSUE TITLE
Test and Distrubute Fail - You don't have Permissions

### ISSUE THREAD

**Issue by rneal4** [MicrosoftDocs/msteams-docs#1052]
I've followed through all the steps of the tutorial several times, but once I reach the "Test and Distribute" step I get an error.
When attempting to install the app, the "Add" button is grayed out with a message below it saying "You don't have permissions to add Hello World to this team."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98cd21c7-e87c-3c5b-7574-998a355f9f08
* Version Independent ID: 5e312707-facc-03fc-af59-90267d0c7b8a
* Content: [Get started with C#/.NET - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/get-started/get-started-dotnet-app-studio)
* Content Source: [msteams-platform/get-started/get-started-dotnet-app-studio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/get-started/get-started-dotnet-app-studio.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Trinetra-MSFT** [comment]
Could you please download your app manifest and try side loading in teams? 
![image](https://user-images.githubusercontent.com/50989436/66800114-a27c4580-ef31-11e9-83bd-90ec6e8cb912.png)

**Comment by rneal4** [comment]
Thank you. This allowed me to test my app and run through the rest of the tutorial.
