### ISSUE TITLE
Retrieve context in private channels is missing information about channel.ownerGroupId

### ISSUE THREAD

**Issue by SubbaReddi** [MicrosoftDocs/msteams-docs#10525]
### Type of issue

Missing information

### Feedback

This is regarding Retrieve context in private channels.
channel.ownerGroupId is populated for private channels. For private channel the value will be the host team groupId.

Above information is missing in the documentation. So, please add the same.

### Page URL

https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/access-teams-context?tabs=Json-v2%2Cteamsjs-v2%2Cdefault#retrieve-context-in-private-channels

### Content source URL

https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/tabs/how-to/access-teams-context.md

### Author

@surbhigupta

### Document Id

c68181e1-151b-fc78-2671-fe9b397b702e

**Comment by Meghana-MSFT** [comment]
@surbhigupta12 - Could you please help to add below point in this doc section : https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/access-teams-context?tabs=Json-v2%2Cteamsjs-v2%2Cdefault#retrieve-context-in-private-channels

channel.ownerGroupId: Set to the host team groupId.
