### ISSUE TITLE
[Android] Failed to load the WebView when sharing to the meeting stage

### ISSUE THREAD

**Issue by jg-s24** [MicrosoftDocs/msteams-docs#10524]
### Steps to reproduce

We use Android Emulator to test our Teams tab app on Android. We tested on Android API 32, 33 and 34. When sharing our App from a meeting sidebar to the meeting stage we get the following error on Android devices: "Failed to load webview. Please check if the specified app is available". Before sharing we can interact with the app as expected in the sidebar.

### Expected behavior

Sharing from a sidebar to the meeting stage should also work on Android devices as it does on Teams Desktop, Browser or iOS.

### Actual behavior

We see an error page with the error message: "Failed to load webview. Please check if the specified app is available".  

<img width="257" alt="Screenshot 2024-03-08 at 11 42 33" src="https://github.com/MicrosoftDocs/msteams-docs/assets/162726153/1d5d317e-3fbc-4795-80f8-e83396f674d9">

### Error details

We get the following logs in Android Studio when sharing to the meeting stage:

`START u0 {flg=0x14000000 cmp=com.microsoft.teams/com.microsoft.skype.teams.views.activities.InCallActivity (has extras)} from uid 10157
ProcessId: 7621, Thread: main, Activity paused: com.microsoft.skype.teams.views.activities.TeamsJsHostActivity 201990625
app_time_stats: avg=55.66ms min=9.39ms max=725.00ms count=18
ProcessId: 7621, Thread: main, Activity started: com.microsoft.skype.teams.views.activities.InCallActivity 150948112
ProcessId: 7621, Thread: main, getUserObjectIdForCall called from logCallOrMeetupButtonSubmitEvent, Unable to find user for call ID 0, guid: 5817a7b0-3c4c-456e-a1e0-7bc4ce7f821d
ProcessId: 7621, Thread: main, updateParticipantList count: 0
ProcessId: 7621, Thread: main, updateParticipantList: Participant list updated updating MainStage
ProcessId: 7621, Thread: main, Updating mainStage for stageType : 1
ProcessId: 7621, Thread: main, loadLayout for stageType : 1,
ProcessId: 7621, Thread: main, getAvailableVideoDevices:[/FRONT/1, /BACK/0]
ProcessId: 7621, Thread: main, updateStageLayout for stageType : 1, participantsCount: 0
ProcessId: 7621, Thread: main, updateStageLayout ignored layout update since its the same layout : stageType : 1
ProcessId: 7621, Thread: Pool-ViewData-Thread-4, setUsers() called on non Ui Thread, Thread:Pool-ViewData-Thread-4, Stacktrace:java.lang.Exception: setUsers() called on non Ui Thread
	at com.microsoft.skype.teams.views.widgets.UserAvatarViewAdapter.setUsers(Unknown Source:54)
	at com.microsoft.teams.contributionui.useravatar.UserAvatarView.setUsers(Unknown Source:2)
	at com.microsoft.teams.feed.R$id.setUser(Unknown Source:17)
	at com.microsoft.teams.chats.data.ChatsViewData$7$$ExternalSyntheticLambda0.run(Unknown Source:450)
	at com.microsoft.teams.androidutils.tasks.TaskUtilities$4.call(SourceFile:2)
	at com.microsoft.teams.androidutils.tasks.TaskUtilities$4.call(SourceFile:1)
	at bolts.Task$4.run(Unknown Source:1990)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
ProcessId: 7621, Thread: Pool-BoltsBackground-Thread-105, requestRefreshData
ProcessId: 7621, Thread: main, isLobbyInPreJoinEnabled: true
ProcessId: 7621, Thread: main, Activity resumed: com.microsoft.skype.teams.views.activities.InCallActivity 150948112
ProcessId: 7621, Thread: main, onResumeBridge() called..
Moving LazyLifecycle state to Active
ProcessId: 7621, Thread: main, onResume: isUserObjectIdNull: false
ProcessId: 7621, Thread: main, onResume2131428723
ProcessId: 7621, Thread: main, isLobbyInPreJoinEnabled: true
ProcessId: 7621, Thread: main, Notification notify request [Id: -1, Type: 20]
ProcessId: 7621, Thread: main, Notification is reported
ProcessId: 7621, Thread: main, sending notify
ProcessId: 7621, Thread: main, Starting service
ProcessId: 7621, Thread: main, Using service binding to start foreground service and foreground notification
ProcessId: 7621, Thread: main, subscribe view changes from adapter
No layout manager attached; skipping layout
No layout manager attached; skipping layout
No layout manager attached; skipping layout
ProcessId: 7621, Thread: main, Calling: layout update for icons and borders callID: 107
Moving LazyLifecycle state to Rest
ProcessId: 7621, Thread: main, Handling call in progress and updating allow video to true
ProcessId: 7621, Thread: main, Handling call in progress and updating isPstnCallWithOCMUser to false
ProcessId: 7621, Thread: main, CallForegroundService Service is connected
ProcessId: 7621, Thread: main, Reporting foreground notification for CallForegroundService
ProcessId: 7621, Thread: main, setupCompanionBanner: Banner is not supported, returning.
ProcessId: 7621, Thread: main, Calling: subscribeForSLAParkedCallsBanner: returning as its not initialized
ProcessId: 7621, Thread: main, Activity stopped: com.microsoft.skype.teams.views.activities.TeamsJsHostActivity 201990625
ProcessId: 7621, Thread: main, Activity destroyed: com.microsoft.skype.teams.views.activities.TeamsJsHostActivity 201990625
tagSocket(171) with statsTag=0xd83ddc19, statsUid=-1
ProcessId: 7621, Thread: main, handleUiRequiredError feature not enabled; nothing to unsubscribe.
ProcessId: 7621, Thread: Pool-BoltsBackground-Thread-103, User left the activity, therefore cancelling all auth related calls
Window{246474c u0 com.microsoft.teams/com.microsoft.skype.teams.views.activities.TeamsJsHostActivity}: Setting back callback null
endAllActiveAnimators on 0xb400006e585fbe20 (StateListDrawable) with handle 0xb400006d68505e60
Input channel object '246474c com.microsoft.teams/com.microsoft.skype.teams.views.activities.TeamsJsHostActivity (client)' was disposed without first being removed with the input manager!
ProcessId: 7621, Thread: CL--1671533392, Calling: onObjectPropertyChangeWithValue CALL, Propkey.CALL_ROSTER_VERSION
ProcessId: 7621, Thread: CL--1671533392, Calling: onObjectPropertyChangeWithValue ignored; event not whitelisted : ObjectType : CALL, Propkey : CALL_ROSTER_VERSION
ProcessId: 7621, Thread: CL--1671533392, Calling: onObjectPropertyChangeWithValue CALL, Propkey.CALL_ROSTER_VERSION
ProcessId: 7621, Thread: CL--1671533392, Calling: onObjectPropertyChangeWithValue ignored; event not whitelisted : ObjectType : CALL, Propkey : CALL_ROSTER_VERSION
ProcessId: 7621, Thread: CL--1671533392, Calling: onObjectPropertyChangeWithValue CONTENTSHARING, Propkey.CONTENTSHARING_STATUS
ProcessId: 7621, Thread: Pool-BoltsBackground-Thread-106, Calling: ContentSharing Status: PRESENTING
ProcessId: 7621, Thread: Pool-BoltsBackground-Thread-106, startExtensibleAppContentSharingSession : starting remote extensible app sharing session
[ERROR:aw_browser_terminator.cc(154)] Renderer process (11687) crash detected (code -1).
ProcessId: 7621, Thread: main, Calling: Handling action: notify notificationId: -1
ProcessId: 7621, Thread: main, CallForegroundService reporting foreground for id : -1, at : 1709894733627
`

**Comment by Meghana-MSFT** [comment]
Thank you for reporting this, we will check this and get back to you.

**Comment by julian-datawrk** [comment]
@Meghana-MSFT Can you give any updates on this issue?

**Comment by carasaffi** [comment]
I am also experiencing the same issue when attempting to share from the meeting sidebar to the meeting stage on Android devices. I receive the error message: "Failed to load WebView. Please check if the specified app is available."

Like others have mentioned, the app works fine in the sidebar, but when trying to share to the meeting stage, the WebView fails to load on Android devices, while it works as expected on Teams Desktop, Browser, and iOS.

Has anyone found a workaround or solution for this?
