### ISSUE TITLE
Can you please provide example for "resource" in SSO using Teams App Studio

### ISSUE THREAD

**Issue by anomepani** [MicrosoftDocs/msteams-docs#1053]
Can you please provide an example for "resource" in SSO using Teams App Studio?
I am having difficulty understanding the supported value for "resource" can you please provide a demo for this.
I am assuming it also requires redirection handling with popup URL as well otherwise it will never return to the main landing page.

If workable demo is available it is very helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f94a488-d636-92b3-21eb-c88744c8f272
* Version Independent ID: 7b3413f4-9ade-accf-5cb2-83fead11a32a
* Content: [Manifest schema reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema)
* Content Source: [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/resources/schema/manifest-schema.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Gousia-MSFT** [comment]
@anomepani Resource value is currently not supported here. We are working on updating the docs to reflect the expected behaviour.
