### ISSUE TITLE
Dead link in the first sentence

### ISSUE THREAD

**Issue by hobpet** [MicrosoftDocs/msteams-docs#1055]
https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/resources/calls-api-overview link is dead!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89db73b2-18ba-b362-ae8e-e03d78da936f
* Version Independent ID: 9bf981e3-389e-e10e-f63b-76be3a164756
* Content: [Calls and Online Meetings Bots - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/calls-and-meetings/calls-meetings-bots-overview)
* Content Source: [msteams-platform/concepts/calls-and-meetings/calls-meetings-bots-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/calls-and-meetings/calls-meetings-bots-overview.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by clearab** [comment]
fixed
