### ISSUE TITLE
No AddMentionToText(,) for Activity[class]

### ISSUE THREAD

**Issue by IdiotLeon** [MicrosoftDocs/msteams-docs#1057]
There is no such a method for `AddMentionToText()` for Activity class. The Nuget package is `Microsoft.Bot.Connector.Teams 4.3.0-beta1` for .NET Core 2.1.

Were there not any by design, how can I at-mention users?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14392b78-c698-ab2e-b7c2-60680cba3b7f
* Version Independent ID: 4c42d4eb-9235-31bf-6b17-8a0c11da5016
* Content: [Channel and Group chat conversations with bots - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/bots/bot-conversations/bots-conv-channel#feedback)
* Content Source: [msteams-platform/concepts/bots/bot-conversations/bots-conv-channel.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/bots/bot-conversations/bots-conv-channel.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by clearab** [comment]
You can see an example of that here: https://github.com/OfficeDev/BotBuilder-MicrosoftTeams-dotnet/blob/622f88cccc5339b85129cb3cd0b39a31867dd6f7/CSharp/Samples/Microsoft.Bot.Builder.Teams.AuditBot/MessageActivityHandler.cs#L57

The documentation is targeted the latest GA version of the SDK, not the 4.3 preview SDK.
