### ISSUE TITLE
Actionable messages are not working for user who don't EXO license

### ISSUE THREAD

**Issue by SubbaReddi** [MicrosoftDocs/msteams-docs#10577]
### Type of issue

Missing information

### Feedback

Actionable messages can be posted using incoming webhook in Teams. But actions will work only when user Exchange online license. Otherwise, Actionable messages will not work for user. So, please mention the same as prerequisite in documentation.

It was mentioned in outlook related documentation, but it helps to mention in teams documentation as well: https://learn.microsoft.com/en-us/outlook/actionable-messages/#outlook-version-requirements-for-actionable-messages

### Page URL

https://learn.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-using?tabs=cURL

### Content source URL

https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/webhooks-and-connectors/how-to/connectors-using.md

### Author

@laujan

### Document Id

8a250e46-2a30-af86-839d-9f83a8b48041

**Comment by ChetanSharma-msft** [comment]
Hello @surbhigupta12 - Please help to update the documentation.
