### ISSUE TITLE
Microsoft Copilot Plugin doesn't give the OAuth token

### ISSUE THREAD

**Issue by vigneshsathisrikumar** [MicrosoftDocs/msteams-docs#10575]
### Steps to reproduce

We have created a bot with search command message extension, we get a token from Microsoft bot framework This token comes on individual user chats when the search command extension is performed, and not on the M365 chat where we use Copilot plugin (same is the case with Copilot for Microsoft 365 App). 

### Expected behavior

The OAuth token is to come in M365 chat as it comes in individual user chats

### Actual behavior

The OAuth token doesn't come in M365 chat as it comes in individual user chats

**Comment by Vikram-MSFT** [comment]
Hello @vigneshsathisrikumar Thanks for raising your query, we will repro it and get back to you soon.

**Comment by ChetanSharma-msft** [comment]
Hello @vigneshsathisrikumar - Could you please confirm whether you have implemented bot SSO or ME SSO.
If you have use ME SSO then it should work fine.

Please refer this sample: 
https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/msgext-search-sso-config

Other sample repo:
https://github.com/OfficeDev/Copilot-for-M365-Plugins-Samples/tree/main
