### ISSUE TITLE
Adding bot to a team does not fire event to bot

### ISSUE THREAD

**Issue by ykamo001** [MicrosoftDocs/msteams-docs#10589]
### Steps to reproduce

1. Add Sentry bot to MSteams
2. Try to add Sentry bot to a team

### Expected behavior

An "installationUpdate" event with a "add" action is received to the bot

### Actual behavior

No event is received

**Comment by ykamo001** [comment]
Even the "teamMemberAdded" event is not firing as per the docs here: https://learn.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bots-notifications#schema-example-bot-added-to-team

**Comment by ChetanSharma-msft** [comment]
Hello @ykamo001 - Thanks for raising your query.
Could you please refer this documentation: 
https://learn.microsoft.com/en-us/microsoftteams/platform/bots/bot-basics?tabs=csharp

**Comment by ykamo001** [comment]
Sorry about this, the problem was on our infra, the events are actually coming through consistently
