### ISSUE TITLE
[Accessibility] Close button is unlabelled, button do not have discernible text

### ISSUE THREAD

**Issue by Terry-Shi** [MicrosoftDocs/msteams-docs#10580]
### Steps to reproduce

adaptive card example:
{
"type": "AdaptiveCard",
"version": "1.5",
"body": [
{
"type": "TextBlock",
"text": "didn't have tool tip for close button at right up side"
}
],
"$schema": "http://adaptivecards.io/schemas/adaptive-card.json"
}

### Expected behavior

Close button has tooltip to indicate it's function

### Actual behavior

no tool tip

### Error details

![image](https://github.com/MicrosoftDocs/msteams-docs/assets/2841857/c3a8b77d-626a-4d5f-92c5-3d2ee2c40b79)

**Comment by Prasad-MSFT** [comment]
Hi @Terry-Shi - Could you please let us know which close button is this? Is this a close button to dismiss a task module/pop up dialog? Because the adaptive card JSON shared doesn't indicate much.

**Comment by Prasad-MSFT** [comment]
**Update:**

We have raised a bug for the same. We will inform you once we get any further update from engineering team. 
Thanks!

**Comment by Prasad-MSFT** [comment]
@Terry-Shi, this issue is fixed now. Please do verify.

![image](https://github.com/user-attachments/assets/8429c040-b83d-464e-9132-72999070a75d)

**Comment by Prasad-MSFT** [comment]
We are closing this issue for now. Please feel free to reopen if required. Thanks!
