### ISSUE TITLE
[Accessibility] On accessing 'Email' and 'Rating star' icons, the announcement "graphic" is made twice

### ISSUE THREAD

**Issue by Terry-Shi** [MicrosoftDocs/msteams-docs#10582]
### Steps to reproduce

On accessing 'Email' and 'Rating star' icons, the announcement "graphic" is made twice.
Please check details in the video file.

### Expected behavior

Repetitive announcements should be avoided.

### Actual behavior

On accessing 'Email' and 'Rating star' icons, the announcement "graphic" is made twice.

**Comment by Terry-Shi** [comment]
https://github.com/MicrosoftDocs/msteams-docs/assets/2841857/a9f430ec-1ec7-4143-9f41-d15672316b10

[viewEmailAddress.json](https://github.com/MicrosoftDocs/msteams-docs/files/14686602/viewEmailAddress.json)

**Comment by Dinesh-MSFT** [comment]
Hi @Terry-Shi - Thanks for raising the query.
Please share the JSON Card, so that we can repro this issue and let you know the updates.

**Comment by Terry-Shi** [comment]
JSON file is already in the above comments, under the video clip. [viewEmailAddress.json](https://github.com/MicrosoftDocs/msteams-docs/files/14686602/viewEmailAddress.json)

**Comment by Dinesh-MSFT** [comment]
Hi @Terry-Shi, 
Sorry for delay in response. We tried to repro this issue, but we see broken images instead email and rating icons in adaptive card.
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/154973237/b04aadac-2dd6-49db-8433-c8840a4e9156)
