### ISSUE TITLE
Validate - Share to Teams from web apps

### ISSUE THREAD

**Issue by v-vanv** [MicrosoftDocs/msteams-docs#10586]
### Type of issue

Other (describe below)

### Feedback

This is w.r.t the testing of [Share to Teams from web apps](https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/share-to-teams-from-web-apps).
 
Requesting to test and validate the technical information in the content and share the inputs with doc team if any.
 
PR: [#10484](https://github.com/MicrosoftDocs/msteams-docs/pull/10484)
Review site: [Share to Teams from web apps](https://review.learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/share-to-teams-from-web-apps?branch=pr-en-us-10484)

### Page URL

https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/share-to-teams-from-web-apps

### Content source URL

https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/build-and-test/share-to-teams-from-web-apps.md

### Author

@surbhigupta

### Document Id

9cb013cb-3a19-2142-5286-692ff9b32ea6

**Comment by ChetanSharma-msft** [comment]
Hello @Prithvi-MSFT  - Kindly check this issue once.

**Comment by v-preethah** [comment]
@ChetanSharma-msft @Prithvi-MSFT Can you please help with the updates on the issue?

**Comment by Dinesh-MSFT** [comment]
Hi @v-preethah,
Sorry for the delay in the response. Changes looks fine in the document. We have approved it.
