### ISSUE TITLE
Teams-only Apps code snippet needs update

### ISSUE THREAD

**Issue by erinha** [MicrosoftDocs/msteams-docs#10597]
### Type of issue

Typo

### Feedback

A code snippet is provided for app developers to check if their app is running in Teams. https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/using-teams-client-library?tabs=javascript%2Cmanifest-teams-toolkit#teams-only-apps

This snippet needs to be updated to include checking for app host name with value `microsoftTeams.HostName.teamsModern`.

BEFORE UPDATE (i.e., current code on doc page):
```
// Ensure that you initialize the TeamsJS once, regardless of how often this is called.
let teamsInitPromise;
export function ensureTeamsJSInitialized(){
    if (!teamsInitPromise) {
        teamsInitPromise = microsoftTeams.app.initialize();
    }
    return teamsInitPromise;
}

// Function returns a promise which resolves to true if we're running in Teams
export async function inTeams(){
  try {
    await ensureTeamsJSInitialized();
    const context = await microsoftTeams.app.getContext();
    return (context.app.host.name === microsoftTeams.HostName.teams);
  }
  catch (e) {
    console.log(`${e} from Teams SDK, may be running outside of Teams`);
    return false;
  }
}
```

AFTER SUGGESTED FIX:
```
// Ensure that you initialize the TeamsJS once, regardless of how often this is called.
let teamsInitPromise;
export function ensureTeamsJSInitialized(){
    if (!teamsInitPromise) {
        teamsInitPromise = microsoftTeams.app.initialize();
    }
    return teamsInitPromise;
}

// Function returns a promise which resolves to true if we're running in Teams
export async function inTeams(){
  try {
    await ensureTeamsJSInitialized();
    const context = await microsoftTeams.app.getContext();
    return (context.app.host.name === microsoftTeams.HostName.teams || context.app.host.name == microsoftTeams.HostName.teamsModern);
  }
  catch (e) {
    console.log(`${e} from Teams SDK, may be running outside of Teams`);
    return false;
  }
}
```

### Page URL

https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/using-teams-client-library?tabs=javascript%2Cmanifest-teams-toolkit#teams-only-apps

### Content source URL

https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/tabs/how-to/using-teams-client-library.md

### Author

@erikadoyle

### Document Id

4ae8187e-a7e4-4b5a-6f38-da6bfa30f2d2

**Comment by erikadoyle** [comment]
Thanks @erinha! The consensus across Teams/Taos PM was to remove the snippet entirely. Update is staged and ready for merge: https://github.com/MicrosoftDocs/msteams-docs/pull/10588
