### ISSUE TITLE
Files added as tab using URL with "Website" option don't open in Office desktop app from New Teams app.

### ISSUE THREAD

**Issue by mshaikh14** [MicrosoftDocs/msteams-docs#10601]
### Steps to reproduce

The New Teams app doesn't open files that were added as tab using URL with "Website" option. Below steps were followed to add the files as tab from Classic Teams app by several users in our organization.

Add File as tab using URL with Website:
1. Click "Add a tab" on a chat and select "Website".
2. Enter "Tab name" and "URL"
3. Click "Save"

![Teams - add file URL as Tab - 01](https://github.com/MicrosoftDocs/msteams-docs/assets/164949853/c3dd7a80-f472-46a2-922a-2ace34963f75)

![Teams - add file URL as Tab - 02](https://github.com/MicrosoftDocs/msteams-docs/assets/164949853/c9922d87-236b-4a9c-af73-74909ec16e34)

![Teams - add file URL as Tab 03](https://github.com/MicrosoftDocs/msteams-docs/assets/164949853/7e0d2679-317f-4213-bf0d-b414c51c10c0)

Open the file within Tab & Desktop app from Teams:
1. Click the newly added tab and it loads the file within the Tab.
2. Further, select "Editing" then click "Open in Desktop App"

![Teams - Tab view of file added via URL](https://github.com/MicrosoftDocs/msteams-docs/assets/164949853/b058ca42-4fd9-44db-8c8d-39a8415680ec)

Users have switched to New Teams app as Classic Teams app is going to be deprecated by March 31, 2024.  The files that were added as tabs using URL with "Website" no longer open within the Tab and/or "Open in Desktop App".

### Expected behavior

In Classic Teams app, files added as tab via URL using "Website" option loads the file within the tab. Users could further select "Editing" then "Open in Desktop App" and file gets launched in respective office app (Word, Excel, Powerpoint, etc.)

![Teams - open file in desktop app from Tab](https://github.com/MicrosoftDocs/msteams-docs/assets/164949853/b23a1377-5471-4a3d-a5f4-34b5b8c95c13)

### Actual behavior

In New Teams app, the files added using URL with "Website" option no longer open within the Tab and/or "Open in Desktop App".  In some instances, the tab was loading the file but when trying to "Open in Desktop App" it never launches the file in respective office app (Word, Excel, Powerpoint, etc.)

### Error details

The file tab added as tab via URL using "Website" option now reports following message:

You're viewing content from <website URL removed for privacy>.... Be sure you trust this site before using it. If the site doesn’t load properly, open it in a browser.

![New Teams - Tab view of file added via URL](https://github.com/MicrosoftDocs/msteams-docs/assets/164949853/cb7046c0-4669-4e5d-a6d8-78cc7edeec3e)

**Comment by Meghana-MSFT** [comment]
The Website tab is not going to work the same in the New Teams Client as it did in the Classic Teams Client. Customers who currently depend on the Website tab should switch to using apps and if an app is not available, they will need to add a configurable tab to their Teams App in order to support these scenarios.
