### ISSUE TITLE
Failure to run Prepare Teams App Dependencies

### ISSUE THREAD

**Issue by scabrera** [MicrosoftDocs/msteams-docs#10603]
### Type of issue

Feature doesn't work (bug)

### Feedback

Below I present evidence of the process carried out.

I create a Teams project for Tab
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/2765002/4529d4a9-323c-407e-88a4-aad26fc0ab97)

Ejecuto Prepare Teams Apps Dependencies
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/2765002/8ea75d6a-e3c6-435e-9118-c95ebb4af940)

I select a 365 Work Account
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/2765002/7b828232-2a6b-4176-ba8d-1bb34de8f627)

Prepare Teams Apps Dependencies is executed
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/2765002/57af325a-2b48-4f99-8617-b4f561cd28c9)

and as shown in the image it has an error.

Below I present development environment

![image](https://github.com/MicrosoftDocs/msteams-docs/assets/2765002/5158b456-52e5-44fe-818a-8c64a8a5fcab)

As I mentioned before, I have used the same Office 365 work account in Visual Studio Code and Teams Toolkit and it has been configured and run correctly. I mention this to rule out setting up an Office 365 account.

![image](https://github.com/MicrosoftDocs/msteams-docs/assets/2765002/5ccab25b-cdb5-480a-92d9-d63642a67aea)

### Page URL

https://learn.microsoft.com/en-us/microsoftteams/platform/toolkit/toolkit-v4/explore-teams-toolkit-vs?source=recommendations&tabs=prj

### Content source URL

https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/toolkit-v4/explore-Teams-Toolkit-vs.md

### Author

@zyxiaoyuer

### Document Id

58c22237-ad50-5cee-45fe-bcfe8cbc7238

**Comment by Nivedipa-MSFT** [comment]
@scabrera - Thanks for reporting your issue. We will check this and update you soon.

**Comment by Nivedipa-MSFT** [comment]
@scabrera - Its working fine at our end. Have you tested this with the updated Visual Studio and checked?
