### ISSUE TITLE
[New Teams Bug] Refresh button is not visible in tab of new Teams client

### ISSUE THREAD

**Issue by qjkobe** [MicrosoftDocs/msteams-docs#10612]
### Steps to reproduce

Open new Teams client. Find a bot app such as jira cloud.
Choose the issues tab.
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/16449598/3462757d-34ac-480b-8010-d36a414fd206)
The refresh button is missing.
But If you open it not in conversation but a full screen mode, the refresh button will display.
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/16449598/a6d90fb0-fbe7-4649-b8f6-624aeead53e8)

### Expected behavior

Refresh button should always display.

### Actual behavior

Refresh button miss in some scenarios.

**Comment by Vaibhav-MSFT** [comment]
Hello @qjkobe ,
Thanks for reporting your issue. We will test this and update you soon.

**Comment by Vaibhav-MSFT** [comment]
Hello @qjkobe ,
We are able to repro the issue in both New Teams desktop and web client. We will raise the bug for the same and update you accordingly.

**Comment by Prasad-MSFT** [comment]
@qjkobe, we got update from engineering team that, Conversation "Chat" tab will not have reload button. It is by design.

**Comment by qjkobe** [comment]
It's not the Chat Tab, but the tab of apps. Below are the screenshots of each tab:
Chat Tab:
![image](https://github.com/user-attachments/assets/a9a73c5f-bcef-42e2-b6be-e933af3ff072)
Apps custom tab:
![image](https://github.com/user-attachments/assets/030046d8-0a74-4c53-a4e0-5323409abda6)

**Comment by Prasad-MSFT** [comment]
What it means that, if you open the app as Personal app, then the reload button will show
![image](https://github.com/user-attachments/assets/f2a1a109-4662-4144-bff4-f01192939141)


If you open the app from chat section, reload button will not show, which is by design.

**Comment by qjkobe** [comment]
Oh. That's fine. If this is by design, I'll close this ticket.
