### ISSUE TITLE
Feedback: Map the matched recordings and transcripts from onlineMeeting APIs

### ISSUE THREAD

**Issue by author-spirit** [MicrosoftDocs/msteams-docs#10613]
### Type of issue

Missing information

### Feedback

I am trying to get recordings and transcripts on an onlineMeeting, I am getting responses but two major issue I found using the APIs are:

There is no way to map each recordings with its transcripts when recorded multiple times using same meeting link
There is no option to sort the response by createdtime
transcripts returns createdTime in descending order
recordings returns createdTime in ascending order

### Page URL

https://learn.microsoft.com/en-us/graph/api/onlinemeeting-list-recordings?view=graph-rest-beta&tabs=http

### Content source URL

https://learn.microsoft.com/en-us/graph/api/onlinemeeting-list-recordings?view=graph-rest-beta&tabs=http

### Author

NA

### Document Id

NA

**Comment by Vaibhav-MSFT** [comment]
Hello @author-spirit ,
Thanks for reporting your issue. We will test this and update you soon.

**Comment by Vaibhav-MSFT** [comment]
Hello @author-spirit, unfortunately there is nothing provided by Microsoft as per documentation.
We suggest you to give feedback here- [Microsoft Graph | Support](https://developer.microsoft.com/en-us/graph/support)
