### ISSUE TITLE
How to return a pure image (without card wrapper) in message extension?

### ISSUE THREAD

**Issue by NewFuture** [MicrosoftDocs/msteams-docs#1062]
I what to it render an image just like the Giphy does.
```html
<img src="...">
```
But, it says `composeExtension.attachments` can only be 4 kinds of cards. 
What should it return?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88ff3777-49c4-8cdc-089e-8612a8774ffb
* Version Independent ID: 0d927000-0b55-2129-cbbb-6630c1ec481e
* Content: [Search with messaging extensions - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/messaging-extensions/search-extensions#feedback)
* Content Source: [msteams-platform/concepts/messaging-extensions/search-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/messaging-extensions/search-extensions.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Gousia-MSFT** [comment]
@NewFuture In order to return plain images from Message Extension, please try setting the `composeExtension.attachmentLayout` to grid as described [here ](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/messaging-extensions/search-extensions#respond-to-user-requests)and send thumbnail images. 
```
var response = new ComposeExtensionResponse(new ComposeExtensionResult("grid", "result"));
response.ComposeExtension.Attachments = attachments;
return response;
```
Each attachment will only contain a thumbnail image. Please try sending a thumbnail image and let me know if you face any issues.

**Comment by NewFuture** [comment]
@Gousia-MSFT thank you. 
Yes, it will insert a `thumbnailCard` as an image, which has a fixed width and height.

And I also have tried the `Adaptive card`.
But. they have two problems:
1.  fixed width and height ,I want to insert images with different width and height.
2. The GIF can not play in mobile teams (iOS).

so I want to send a HTML img tag from the extension， which works in bots response.
it's there any way to send `<img>` tag in message extension?

**Comment by Gousia-MSFT** [comment]
@NewFuture It is not possible to send a HTML tag from a message extension. You could use [TaskModule ](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/task-modules/task-modules-overview)if you want to open Html content from bots.

**Comment by NewFuture** [comment]
@Gousia-MSFT  thanks.

> It's impossible to insert an **image** instead of a **card** into the input box at now.

is it right?

**Comment by Gousia-MSFT** [comment]
@NewFuture You can insert an image but that should be a thumbnail image as described earlier. You cannot use <img> tags to insert image. Here is how you could send a thumbnail image:
```
var previewCard = new ThumbnailCard
{
 Images = new System.Collections.Generic.List<CardImage> { new CardImage("http://lorempixel.com/640/480?rand=" + DateTime.Now.Ticks.ToString()) }
};
 return previewCard.ToAttachment().ToComposeExtensionAttachment();
```

**Comment by NewFuture** [comment]
@Gousia-MSFT thanks, but the `ThumbnailCard` has some different behaviors with pure `img`

**Comment by Gousia-MSFT** [comment]
@NewFuture Could you please help me understand what difference you are talking about? Please share a screenshot of what you are expecting it to be like.

**Comment by Gousia-MSFT** [comment]
Please re-open of you still face any issues.

**Comment by NewFuture** [comment]
@Gousia-MSFT, sorry for my late reply. 
Could you contact me in Microsoft Teams (just search `New Future`)?
I will show you the difference.
