### ISSUE TITLE
[Accessibility] Heading level not provided for 'Phone Information'

### ISSUE THREAD

**Issue by Terry-Shi** [MicrosoftDocs/msteams-docs#10629]
### Steps to reproduce

Adaptive card Accessibility issue.
please check card json content in error details.
the issue is:
Heading level not provided for 'Phone Information'

### Expected behavior

visually apparent headings should be programmatically identified as headings and vice versa.

### Actual behavior

Heading level not provided for 'Phone Information'

### Error details

[phoneNumbers.json](https://github.com/MicrosoftDocs/msteams-docs/files/14799279/phoneNumbers.json)

**Comment by Terry-Shi** [comment]
![Heading level not provided for 'Phone Information'](https://github.com/MicrosoftDocs/msteams-docs/assets/2841857/86004bfd-b421-4f4f-b846-26597d15a9c9)

**Comment by Meghana-MSFT** [comment]
Thank you for reporting this, we will check this and get back to you.
