### ISSUE TITLE
Teams admin center: change of behaviour in blocking an app with new app centric management functionality

### ISSUE THREAD

**Issue by raguravindran** [MicrosoftDocs/msteams-docs#10635]
### Steps to reproduce

Make sure the teams admin center is utilizing the new feature "app centric management" doc [here](https://learn.microsoft.com/en-us/microsoftteams/app-centric-management#mapping-between-old-permission-policies-and-new-app-assignments)
1. Create a bot app that is working and responding
2. Create another app with staticTabs and make sure to point to the the BOT (app id) created in **STEP 1**. install the app
3. Make sure the app is working and BOT is responding to messages
4. Now, block the app created in **STEP 1** from manage apps module
5. Make sure the bot app created in **STEP 1** has "assignments" as "everyone"
6. Now go to the app created in **STEP 2** (wait for 24hrs until changes reflect) try to communicate with bot, the BOT does not respond

Previously with "manage apps -> permissions policies" doc [here](https://learn.microsoft.com/en-us/microsoftteams/teams-app-permission-policies) the above steps worked, blocking the app **STEP 1** never caused issue to the app **STEP 2**. the communication in BOT always worked.

### Expected behavior

Bot should respond

### Actual behavior

Bot does not respond

**Comment by Prasad-MSFT** [comment]
Thanks for raising your issue. We will check this at our end and will update you accordingly.

**Comment by Prasad-MSFT** [comment]
@raguravindran - We have raised a bug for the same. We will inform you once we get any further update from engineering team. Thanks!

**Comment by raguravindran** [comment]
> @raguravindran - We have raised a bug for the same. We will inform you once we get any further update from engineering team. Thanks!

Thank you

**Comment by raguravindran** [comment]
@Prasad-MSFT  its been 2 weeks, could you please let me know if there any update?

**Comment by Prasad-MSFT** [comment]
Hi @raguravindran - We got update from engineering team saying, "we do not support multi app bots for this reason. The behavior is non-deterministic and thus can change at any time."
