### ISSUE TITLE
How to refresh token

### ISSUE THREAD

**Issue by chenxizhang** [MicrosoftDocs/msteams-docs#1063]
Since this authentication flow can return an accesstoken to call the GraphService, how can we refresh token for the next time?

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 7d939a56-d1be-f2a2-3454-0f0c5144bc27
* Version Independent ID: ec4d5574-ddeb-9408-ad82-d86507a5111b
* Content: [Authentication for tabs using Azure Active Directory - Teams](https://docs.microsoft.com/zh-cn/microsoftteams/platform/concepts/authentication/auth-tab-aad?view=msteams-client-js-latest)
* Content Source: [msteams-platform/concepts/authentication/auth-tab-AAD.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/authentication/auth-tab-AAD.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Trinetra-MSFT** [comment]
Could you please take a look at [Use the refresh token to get access token](https://docs.microsoft.com/en-us/graph/auth-v2-user#5-use-the-refresh-token-to-get-a-new-access-token)?

**Comment by Gousia-MSFT** [comment]
Please re-open if you still face any issues.
