### ISSUE TITLE
Upload a custom app is not an option for me

### ISSUE THREAD

**Issue by salmanmkc** [MicrosoftDocs/msteams-docs#1064]
I have no option to upload the custom app, whether it's from the app configuration or store page
![image](https://user-images.githubusercontent.com/32169182/67159770-45253180-f341-11e9-9b7c-bef29fe85c4f.png)
![image](https://user-images.githubusercontent.com/32169182/67159774-4f473000-f341-11e9-9c88-e474a2066d94.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 328c86a9-1384-3f07-0b68-947f5ad9b5ab
* Version Independent ID: 9a8e000a-87ed-1357-0b28-feee59311149
* Content: [Upload your custom app in Microsoft Teams - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/apps/apps-upload#feedback)
* Content Source: [msteams-platform/concepts/apps/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/apps/apps-upload.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Gousia-MSFT** [comment]
@salmanmkc Could you please check if Sideloading is enabled in Setup Policies?
![image](https://user-images.githubusercontent.com/45553518/67176705-cc79b000-f3e8-11e9-9704-14627cbb693d.png)
Please follow this document to enable [sideloading ](https://docs.microsoft.com/en-us/microsoftteams/platform/get-started/get-started-tenant)if you haven't done it already.

**Comment by Gousia-MSFT** [comment]
Please re-open if you still face any issues.
