### ISSUE TITLE
Deeplink to meeting schedule dialog not working on mobile

### ISSUE THREAD

**Issue by rafi4242** [MicrosoftDocs/msteams-docs#10645]
### Steps to reproduce

In this article: https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-link-workflow?tabs=teamsjs-v2#configure-deep-link-manually-to-open-a-meeting-scheduling-dialog

When creating a deep link to teams meeting dialogue it works fine on desktop but on Teams mobile (Adnroid and IOS) it's not getting the dates and time.

### Expected behavior

When creating a deeplink to teams meeting, it should insert the participants, date and time of meeting into the dialog.

### Actual behavior

It's inserting participants but keeps the date and time of the moment you open the dialog instead of the date you gave in the deeplink url.

**Comment by Meghana-MSFT** [comment]
Thank you for reporting this, we will check this and get back to you.

**Comment by Meghana-MSFT** [comment]
We are able to repro this issue, we raised a bug for the same. We will keep you posted on the updates. Thank you.

**Comment by Meghana-MSFT** [comment]
Update : Engineering team has looked into the above bug and said that this is a known gap. This feature is not yet implemented.
