### ISSUE TITLE
[Accessibility] Teams Home Frames do not have an accessible name

### ISSUE THREAD

**Issue by wanghe2015** [MicrosoftDocs/msteams-docs#10652]
### Steps to reproduce

When we go to Teams Home, Frames do not have an accessible name.
<img width="1207" alt="image" src="https://github.com/MicrosoftDocs/msteams-docs/assets/13779512/25dcff35-21ad-4aca-9fba-a7f25451f441">

### Expected behavior

Frames must have an accessible name.

### Actual behavior

Frames do not have an accessible name.

**Comment by Vaibhav-MSFT** [comment]
Hello @wanghe2015 ,
Thanks for reporting your issue. Can you please share repro steps so that we can test this from our end?
