### ISSUE TITLE
Share to Teams from web app is not working

### ISSUE THREAD

**Issue by edwin-bh** [MicrosoftDocs/msteams-docs#10654]
### Type of issue

Feature doesn't work (bug)

### Feedback

Hi Team,
I tried to integrate the Share to Teams feature in our application by following the steps given in the site - [Share to Teams from web app](https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/share-to-teams-from-web-apps).
The web chat window is not loading properly, going into a login loop.
This issue is occurring intermittently.

I have attached images below that may help.
![Error Image](https://github.com/MicrosoftDocs/msteams-docs/assets/133978632/a1046e4a-9812-4148-8912-4cefd61c09b3)

![image](https://github.com/MicrosoftDocs/msteams-docs/assets/133978632/e2fad31d-fd63-49cd-b2b4-db61dc10fb1a)

### Page URL

https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/share-to-teams-from-web-apps

### Content source URL

https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/build-and-test/share-to-teams-from-web-apps.md

### Author

@surbhigupta

### Document Id

9cb013cb-3a19-2142-5286-692ff9b32ea6

**Comment by Vaibhav-MSFT** [comment]
Hello @edwin-bh ,
Thanks for reporting your issue. We will test this and update you soon.

**Comment by Vaibhav-MSFT** [comment]
Hello @edwin-bh ,
We have tested the share to teams feature and it is working fine from our end and we are able to the info.
Sample used- https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/app-link-unfurling-in-share-to-teams/nodejs
