### ISSUE TITLE
Commas (&#39;) in Adaptive Card Input.ChoiceSet

### ISSUE THREAD

**Issue by Mark-Bailey-SingleWire** [MicrosoftDocs/msteams-docs#1065]
I am creating an input.ChoiceSet on an Adaptive Card for our bot. If the "value" is set to something with an apostrophe it shows the HTML encoded value, but the real value in the drop-down. Anyone have any ideas? E.g. "Foo's" will show in my card as "Foo&\#39;s\". Does the request need to be submitted with a Content-Type other than "application/json"? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8a3bcf2-332a-8d24-a8d1-7e3816897745
* Version Independent ID: 68fb9551-ce95-0112-2703-721a1af01f23
* Content: [Cards Reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/cards/cards-reference#feedback)
* Content Source: [msteams-platform/concepts/Cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/Cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Mark-Bailey-SingleWire** [comment]
Turns out this is happening in the web client (Chrome) and the OS X client. The Android and iOS client show the apostrophe correctly.

**Comment by Gousia-MSFT** [comment]
@Mark-Bailey-SingleWire Thanks for reporting this. We have raised a bug for this and we are tracking it internally.
