### ISSUE TITLE
[Accessibility]Teams Title Document has more than one main landmark

### ISSUE THREAD

**Issue by wanghe2015** [MicrosoftDocs/msteams-docs#10653]
### Steps to reproduce

MS Teams Home title Document has more than one main landmark
<img width="1173" alt="image" src="https://github.com/MicrosoftDocs/msteams-docs/assets/13779512/0eece6ed-bcbe-4e4f-b680-969548ce6baf">

### Expected behavior

Ensure the document has at most one main landmark.

### Actual behavior

Document has more than one main landmark.

**Comment by ChetanSharma-msft** [comment]
Hello @wanghe2015 - Thanks for raising your query.
We will look into it and let you know the updates.

**Comment by Meghana-MSFT** [comment]
@wanghe2015 - Could you please let us know what tool are you using to check the above issue?
