### ISSUE TITLE
Doc needs to be updated for Bot SDK v4

### ISSUE THREAD

**Issue by jiruss** [MicrosoftDocs/msteams-docs#1066]
The code in the referenced document only works for SDK v3 bots which is deprecated. Customers need to know how to code this for Bot SDK V4.

https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/scenarios/limited-tenant.md

**Comment by clearab** [comment]
Hi - v3 is most definitely not deprecated! You may be referring to a blog post that announced that you would no longer be able to create a v3 bot from a template on the Azure portal, but the actual SDK will continue to work just fine.

However, Teams functionality will be included in the 4.6 release of the Bot Framework SDK, and we're updating samples and documentation to reflect that. You can see some early examples here: https://github.com/microsoft/BotBuilder-Samples/tree/master/experimental/teams

**Comment by jiruss** [comment]
@clearab there's a big difference in still working and deprecated. Perhaps you should check your information before using exclamation points on  your assertion. 

![image](https://user-images.githubusercontent.com/20343098/67233285-e9c27480-f410-11e9-8366-cd9ce6719be6.png)

Ref here. 
https://github.com/microsoft/BotBuilder-V3

I work in Bot Framework support and the majority of customers building bots and who need this functionality are customers using V4. I had to write this code for a customer just this week and hence the request.
