### ISSUE TITLE
Can't access New Teams

### ISSUE THREAD

**Issue by AmyLi0728** [MicrosoftDocs/msteams-docs#10678]
### Steps to reproduce

<img width="1534" alt="image" src="https://github.com/MicrosoftDocs/msteams-docs/assets/144102521/c0b681dc-5f1d-4ede-b5e8-1a595cf26ae9">
platform: linux
chrome: 111
except the highlight user, all of the user can't access new teams and no new teams switch toogle
<img width="1430" alt="image" src="https://github.com/MicrosoftDocs/msteams-docs/assets/144102521/aa6c2858-cc09-4535-aced-f8ab694c84ad">

### Expected behavior

all users should access to new teams

### Actual behavior

only one user can access to  new teams, and I think all the users have same configuration and permission, could you please help us look into why our other user can't access to new teams?

**Comment by ChetanSharma-msft** [comment]
Hello @AmyLi0728 - Thanks for raising your query.
Please confirm if it is working in Web or other Teams clients?

Also, please confirm if you are developing any Teams app or just Teams client issue?

**Comment by AmyLi0728** [comment]
> Hello @AmyLi0728 - Thanks for raising your query. Please confirm if it is working in Web or other Teams clients?
> 
> Also, please confirm if you are developing any Teams app or just Teams client issue?

Hi Team,
We are just using the Web chrome teams to run automation tests, our testing app is SAP SuccessFactors.
Thanks.

**Comment by ChetanSharma-msft** [comment]
Hello @AmyLi0728 - We are mainly responsible for Microsoft Teams app development related issues. 

For Microsoft Teams product issues/failures your tenant Admin can reach out to [Microsoft 365 Product Support](https://docs.microsoft.com/en-us/microsoft-365/admin/contact-support-for-business-products?view=o365-worldwide&tabs=online). 

For general questions about Microsoft Teams please post your question on [Microsoft Teams Community](https://answers.microsoft.com/en-us/msteams/forum).

**Comment by Wajeed-msft** [comment]
Please update the password for this account [sftest@0nxh0.onmicrosoft.com](mailto:sftest@0nxh0.onmicrosoft.com) and do not share it on any community forums.

**Comment by Wajeed-msft** [comment]
@AmyLi0728 - Please update the password for this account [sftest@0nxh0.onmicrosoft.com](mailto:sftest@0nxh0.onmicrosoft.com) and do not share it on any community forums.
