### ISSUE TITLE
Bot-Configuration Doc issue

### ISSUE THREAD

**Issue by Pawank-MSFT** [MicrosoftDocs/msteams-docs#10677]
### Type of issue

Missing information

### Feedback

1. Need to change from  "The adaptiveCardForContinue and adaptiveCardForSubmit are functions that return the JSON"  to "The adaptiveCardForContinue and adaptiveCardForSubmit are custom functions that return the JSON"
2. Need to change from  "These functions are used to generate Adaptive Cards for different scenarios based on the user’s interaction with the bot." to "Need to change from  "These functions are used to return Adaptive Cards for different scenarios based on the user’s interaction with the bot."
3. "config/continue" and "config/auth" looks cofusion it should "type: continue" and "type: auth".
4. Need to merge both c# tabs and both Javascript tabs into single for Config/continue.
5. use SDK document instead of code sample.
6. To reconfigure the bot highlight the setting button in the image.
7. Need to change from "You can also request the user to authenticate as a response to config/continue request." to "You can also request the user to authenticate as a response to config/auth request."

### Page URL

https://review.learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/bot-configuration-experience?branch=pr-en-us-10675&tabs=JS2%2CJS3

### Content source URL

https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/bots/how-to/bot-configuration-experience.md

### Author

@surbhigupta

### Document Id

415c2389-14be-5efd-9542-a58bf8a03900

**Comment by Vaibhav-MSFT** [comment]
Hello @Pawank-MSFT ,
The document has been updated.
Thanks!!

**Comment by v-deabira** [comment]
Closing the issue as it has been addressed in PR 10123.
