### ISSUE TITLE
Required Code Snippet - Get Share to Teams for Education Document

### ISSUE THREAD

**Issue by Mohammed-MSFT** [MicrosoftDocs/msteams-docs#10686]
### Type of issue

Missing information

### Feedback

Hi
 
Regarding document  : [Share to Teams from web apps - Teams | Microsoft Learn](https://review.learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/share-to-teams-from-web-apps?branch=pr-en-us-10484)
 
We have tested as per the document, One scenario is working fine and able to see the output.
<img width="529" alt="image" src="https://github.com/MicrosoftDocs/msteams-docs/assets/109147706/3addd7aa-2288-452c-85cd-ea381e0d8893">

 **Share to Teams for Education**
Share to Teams for Education is not working as expected after adding html attributes to a given span as mentioned in doc, the behavior is same as first Scenario.

<img width="529" alt="image" src="https://github.com/user-attachments/assets/5ce30ef4-c219-4a00-b8d4-9a3eeaa349b5">

The given attributes were not displayed in the popup 
<img width="482" alt="image" src="https://github.com/user-attachments/assets/4f7629bd-0fab-480e-914f-b434e593b42d">

**Given Image in the document**
<img width="942" alt="image" src="https://github.com/user-attachments/assets/89309ce0-705f-493e-b17b-a7995625e8b3">

And in the doc, it is given **shareToMicrosoftTeams.renderButtons**(options) but not given proper code snippet of this method how and where to use this line of code.
 
Can you please confirm from Doc-Team/Engg-Team and provide us code snippet to get expected output?
 
**Thanks !!**

### Page URL

https://review.learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/share-to-teams-from-web-apps?branch=pr-en-us-10484

### Content source URL

https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/build-and-test/share-to-teams-from-web-apps.md

### Author

@surbhigupta

### Document Id

9cb013cb-3a19-2142-5286-692ff9b32ea6

**Comment by v-preethah** [comment]
@ChetanSharma-msft Do we have any updates w.r.t the issue?

**Comment by v-preethah** [comment]
@Mohammed-MSFT was able to test Share to Teams for Education successfully.

<img width="453" alt="image" src="https://github.com/user-attachments/assets/4e1a48f2-df63-48f6-bca2-087f451554d0">
