### ISSUE TITLE
No tab in bot chat window for our APP in New Teams

### ISSUE THREAD

**Issue by AmyLi0728** [MicrosoftDocs/msteams-docs#10685]
### Steps to reproduce

There's no tab for our app when we access it from chat in new teams:
<img width="1788" alt="image" src="https://github.com/MicrosoftDocs/msteams-docs/assets/144102521/7f92ac69-8b1d-43c8-9773-6c434712c9b2">

### Expected behavior

There should be "Home" tab and "About" tab 
<img width="1788" alt="image" src="https://github.com/MicrosoftDocs/msteams-docs/assets/144102521/24b2988a-938f-4db5-94d7-8f34e3723f5b">

### Actual behavior

No expected tabs now

**Comment by ChetanSharma-msft** [comment]
Hello @AmyLi0728 - Thanks for raising your query.
We will look into it and let you know the updates.

**Comment by Dinesh-MSFT** [comment]
Hi @AmyLi0728 - We are able to see "About" tab in both chat section and left navigation section from our end.
However, there is no 'Home' tab in both the sections.

Chats in New Teams:
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/154973237/f690c6f8-2124-451b-8079-7255d57ea757)

Left Navigation in New Teams:
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/154973237/7bff614f-7825-45bc-9337-29b9b28fffce)
