### ISSUE TITLE
the documentation for python contains errors and doesent seem functional

### ISSUE THREAD

**Issue by DeanHnter** [MicrosoftDocs/msteams-docs#10692]
### Type of issue

Code doesn't work

### Feedback

The code contains both errors in terms of referenced variables and the update_activity function also seems to always result in a service error unknown.

### Page URL

https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/update-and-delete-bot-messages?tabs=python

### Content source URL

https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/bots/how-to/update-and-delete-bot-messages.md

### Author

@WashingtonKayaker

### Document Id

2f747d61-5ff7-be26-d55d-fdc715f4293d

**Comment by Meghana-MSFT** [comment]
Similar issue is being tracked here https://github.com/OfficeDev/Microsoft-Teams-Samples/issues/1226. Please follow that thread for further updates.

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, please feel free to reopen it, if required.
