### ISSUE TITLE
It looks like the images in this document need to be replaced.

### ISSUE THREAD

**Issue by minces92** [MicrosoftDocs/msteams-docs#10701]
### Type of issue

Other (describe below)

### Feedback

Currently, when accessing a mobile phone in an app containing a bot, clicking the bot icon takes you to chat.
They say that chat should not be displayed on the tab shown in the mobile example photo.
Please change the image as there is a risk of misunderstanding.

### Page URL

https://learn.microsoft.com/ko-kr/microsoftteams/platform/bots/design/bots

### Content source URL

https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/bots/design/bots.md

### Author

@heath-hamilton

### Document Id

3725c141-86f1-b815-6568-16758d948fac

**Comment by Dinesh-MSFT** [comment]
Hi @minces92 - Thanks for raising the query.
We will look into it and let you know the updates.
