### ISSUE TITLE
NodeJS code sample links broken

### ISSUE THREAD

**Issue by ullasholla** [MicrosoftDocs/msteams-docs#10702]
### Type of issue

Outdated article

### Feedback

Most of the links to the Node.js sample code does not work.
Example:
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/212316/85a280c8-389c-474c-a105-c0f8fc6cbd92)

### Page URL

https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/teams%20conversational%20ai/teams-conversation-ai-overview

### Content source URL

https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/bots/how-to/Teams conversational AI/teams-conversation-ai-overview.md

### Author

@michaelmaillot

### Document Id

56a54b92-6f7c-0fcc-6689-d84794bb25bc

**Comment by Vikram-MSFT** [comment]
Hello @surbhigupta12 
Could you please help here as per document suggested?

**Comment by ChetanSharma-msft** [comment]
Hello @SurbhiAgarwal12 - below sample does not exists in repo, so please either remove it or we need to check who owns this repo:
https://github.com/microsoft/teams-ai/tree/main/js/samples/04.ai.c.actionMapping.lightBot

**Comment by ChetanSharma-msft** [comment]
Hello @ullasholla - Sorry for delay in response.
This issue is fixed. Kindly verify and let us know.

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, please feel free to reopen it, if required.
