### ISSUE TITLE
Feedback - UI changes - Manage channel option not available

### ISSUE THREAD

**Issue by v-preethah** [MicrosoftDocs/msteams-docs#10729]
### Type of issue

Other (describe below)

### Feedback

Tested internally and Manage channel option isn't available. The docs were updated for recent UI, however, there seems to be an update further to it. 

Help validate the channel option, in order to update the docs.

<img width="243" alt="image" src="https://github.com/MicrosoftDocs/msteams-docs/assets/117343020/e9344b9c-8f59-40a7-ba62-e4b54f01293d">

<img width="140" alt="image" src="https://github.com/MicrosoftDocs/msteams-docs/assets/117343020/4e78f567-8e1c-4d7d-bd76-8adafd90febd">

Feedback received from external users on change in UI.

- Feedback 1: I don't see Manage Teams link for a channel I created.
- Feedback 2: Functionality of incoming webhook connector is completely different in the new MS teams and viewing configurations on existing webhooks is impossible 

### Page URL

https://learn.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-incoming-webhook?tabs=newteams%2Cdotnet

### Content source URL

https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/webhooks-and-connectors/how-to/add-incoming-webhook.md

### Author

@surbhigupta

### Document Id

e3b53e27-2946-189c-623b-9df704ea8f12

**Comment by Prasad-MSFT** [comment]
Thanks for raising your issue. We will check this at our end and will update you accordingly.

**Comment by Prasad-MSFT** [comment]
Hi @v-preethah - We checked in New Teams client with `Microsoft Teams version 24107.2200.2822.6470.`
`The client version is 49/24031414714.`

1. Manage channel option is available
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/62237649/696d707f-090d-466a-be60-e8c245d51969)

2. Managing connector configuration UI also seems correct only.
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/62237649/28a4699d-8f68-4fce-beca-62c29372a154)

**Comment by v-preethah** [comment]
@Prasad-MSFT Do we have any updates on this issue? Can you please help us understand if only Admins can view Manage channel?

**Comment by Prasad-MSFT** [comment]
Hi @v-preethah, we can add a point in [this](https://learn.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-incoming-webhook?tabs=newteams%2Cdotnet#create-an-incoming-webhook) section after point 3 stating that, for members of the team (non-admin users), the 'Manage channel' option is available in channel sidebar as shown below:

![image](https://github.com/user-attachments/assets/f1baa6fd-76cf-4e42-9e1c-36216a514060)
