### ISSUE TITLE
Highlighted links in wiki destroys entire wiki section --> markup problem

### ISSUE THREAD

**Issue by davegr99** [MicrosoftDocs/msteams-docs#1073]
Hi everyone,

looks like there's a bug in MS Teams Wiki.
Everytime I try to highlight a link to a document from the team in a wiki section, it opens the document but also deletes the section from wiki where the link was located.

To reproduce:
1. Copy a link from a document located in Teams
2. Paste the link into a wiki section
3. Highlight it with the text marker
4. Click on the link
5. Watch how the section is gone

Anyone with the same experience?

**Comment by Trinetra-MSFT** [comment]
We are not able to reproduce this issue. Are you pasting the link in wiki page content section and highlighting? Could you please share some screenshots?

**Comment by davegr99** [comment]
Exactly.

Firstly, copying the link to an alternate text. The link opens a Word file, which is located in the channel "general". Wiki is in "general" as well.

![image](https://user-images.githubusercontent.com/56866638/67361309-8186a680-f568-11e9-9ddc-2bc14aa6ee07.png)

After that, use the highlight option to highlight the alternate text for the link.
![image](https://user-images.githubusercontent.com/56866638/67361205-3ff5fb80-f568-11e9-92bf-75bca84a2c6f.png)

After you click on the link, the wiki section should be removed.

**Comment by Trinetra-MSFT** [comment]
@davegr99, We still could not able to repro this issue. After you highlight a alternate text which have a link associated with it, clicking on that text should navigate to the  inserted link. Please find the attached screenshot. 
![image](https://user-images.githubusercontent.com/50989436/67541522-da8c4100-f706-11e9-99ff-8cd43952773e.png)
If you are still facing this issue, Please record a video and attach the same here. We will look into thi.

**Comment by davegr99** [comment]
Yes, the link takes me to the document, but after that, when I close the document, the wiki section is empty. Here's the video you asked for:


[Teams issue.zip](https://github.com/MicrosoftDocs/msteams-docs/files/3770514/Teams.issue.zip)

Thanks for your help!

**Comment by davegr99** [comment]
Hello again,
how's the progress with this issue after two weeks?
Could you replicate it?

**Comment by Trinetra-MSFT** [comment]
@davegr99 , We still could not able to repro this issue. It is working fine on our end.

**Comment by davegr99** [comment]
That's problematic.
But you see in the video, that it's not working.
Right? So I'm not hallucinating 🤐
