### ISSUE TITLE
Fix url links 

### ISSUE THREAD

**Issue by corinagum** [MicrosoftDocs/msteams-docs#10747]
### Type of issue

Outdated article

### Feedback

We updated our nodejs samples to a new set of directories and the links need to be updated.

### Page URL

https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/teams%20conversational%20ai/teams-conversation-ai-overview#code-samples

### Content source URL

https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/bots/how-to/Teams conversational AI/teams-conversation-ai-overview.md

### Author

@michaelmaillot

### Document Id

56a54b92-6f7c-0fcc-6689-d84794bb25bc

**Comment by ChetanSharma-msft** [comment]
Hello @corinagum - Thanks for raising the feedback.
We will look into it and let you know the updates.
