### ISSUE TITLE
Sample file deep link has a typo causing developer confusion

### ISSUE THREAD

**Issue by ydogandjiev** [MicrosoftDocs/msteams-docs#10746]
### Type of issue

Typo

### Feedback

There is a typo in the sample deep link show in the [Generate deep links to a file in a channel](https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-link-teams#generate-deep-links-to-a-file-in-a-channel
) section of this doc. The `objectURL` parameter should actually be `objectUrl`.

So instead of this:
```
https://teams.microsoft.com/l/file/<fileId>?tenantId=<tenantId>&fileType=<fileType>&objectURL=<objectURL>&baseUrl=<baseURL>&serviceName=<Name>&threadId=<threadId>&groupId=<groupId>
```

The doc should show:
```
https://teams.microsoft.com/l/file/<fileId>?tenantId=<tenantId>&fileType=<fileType>&objectUrl=<objectUrl>&baseUrl=<baseUrl>&serviceName=<Name>&threadId=<threadId>&groupId=<groupId>
```

### Page URL

https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-link-teams#generate-deep-links-to-a-file-in-a-channel

### Content source URL

https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/build-and-test/deep-link-teams.md

### Author

@v-npaladugu

### Document Id

b6687ceb-6d67-b0b7-0797-b16d14e4bd97

**Comment by Prasad-MSFT** [comment]
PR has been raised to fix the issue.
