### ISSUE TITLE
Unable to re-enter login credentials

### ISSUE THREAD

**Issue by melli79** [MicrosoftDocs/msteams-docs#1074]
Problem:
I have changed my (company) Microsoft login credentials today.  Since then teams reports that I have to re-login.  Whenever I click on this popup, teams restarts, but after 10s the same popup re-appears.

(I have already restarted the computer, same behavior.)

Expected behavior:  After a failed auto-login attempt I get the possibility to re-enter my credentials (maybe even switch the user)
Actual behavior: The program tries login with the same (expired) credentials until I forcefully terminate it.

version: teams 1.4.4.0 from office365 (windows programs & updates reports: 1.2.00.26774 from Oct 17. 2019)
OS Version: win 10 Enterprise

**Comment by melli79** [comment]
Problem seems resolved after the second reboot. (I assume that we have problems with updating the SSO tokens.) Now I could re-enter the credentials (and even the user).

Therefore you can reduce the priority.

Nevertheless it would be nice to have an option to overrule the auto login.

**Comment by Trinetra-MSFT** [comment]
Closing this issue as problem is resolved
