### ISSUE TITLE
Mac Teams app -can't access settings

### ISSUE THREAD

**Issue by dkubes** [MicrosoftDocs/msteams-docs#1075]
If you click on the gear icon on the Mac app, instead of opening "settings" it opens up "manage teams"

**Comment by Trinetra-MSFT** [comment]
Could you please share some screen shots?

**Comment by dkubes** [comment]
Sure! 
![IMG_0485](https://user-images.githubusercontent.com/56885111/67355643-c63d1e00-f525-11e9-8af1-4828cff85e82.jpeg)

**Comment by dkubes** [comment]
Shouldn't this open settings, as it does on other versions of Teams, rather than Manage Teams? There are no settings (light/dark mode etc.) within the menu system.

**Comment by Gousia-MSFT** [comment]
@dkubes You could open Teams settings by clicking on the profile picture and choose Settings:
![image](https://user-images.githubusercontent.com/45553518/67357110-dda5f680-f579-11e9-9d4e-23a82b170984.png)
You will be able to change the light/dark mode from here:
![image](https://user-images.githubusercontent.com/45553518/67357148-fca48880-f579-11e9-9b71-f18889a040e1.png)
