### ISSUE TITLE
Teams launcher is not able to launch personal teams app for long URL in windows system if desktop app is selected for launch 

### ISSUE THREAD

**Issue by kumarUtsav-01** [MicrosoftDocs/msteams-docs#10761]
### Steps to reproduce

We are experiencing a problem with MS Teams desktop app in windows system. We have created a MS teams app which allows a user to share any long content to any user in his/her organization through MS teams. The content is passed as a query parameter to the Deeplink of the teams app. 

As the content can be long, so, the Deeplink containing this content also increases in length. While such Deeplinks work fine in MAC machines whether I choose browser or desktop app to launch the app, in Windows, they only work if I choose browser app. In case of choosing desktop app, the application does not launch. There is no error thrown at the launcher page as well.

Example of launcher link with 3300 characters in URL:
[MSLink](https://teams.microsoft.com/dl/launcher/launcher.html?url=%2F_%23%2Fl%2Fentity%2Fb10b9797-db6a-42cb-9677-e79af0862da8%2Ftab%3F%26context%3D%257B%2522subEntityId%2522%253A%257B%2522url%2522%253A%2522%2522%252C%2522appTitle%2522%253A%2522DETAILS%2520ON%2520PRODUCT%2522%252C%2522subTitle%2522%253A%2522%2522%252C%2522mode%2522%253A%2522summary%2522%252C%2522message%2522%253A%2522But%2520I%2520must%2520explain%2520to%2520you%2520how%2520all%2520this%2520mistaken%2520idea%2520of%2520denouncing%2520pleasure%2520and%2520praising%2520pain%2520was%2520born%2520and%2520I%2520will%2520give%2520you%2520a%2520complete%2520account%2520of%2520the%2520system%252C%2520and%2520expound%2520the%2520actual%2520teachings%2520of%2520the%2520great%2520explorer%2520of%2520the%2520truth%252C%2520the%2520master-builder%2520of%2520human%2520happiness.%2520No%2520one%2520rejects%252C%2520dislikes%252C%2520or%2520avoids%2520pleasure%2520itself%252C%2520because%2520it%2520is%2520pleasure%252C%2520but%2520because%2520those%2520who%2520do%2520not%2520know%2520how%2520to%2520pursue%2520pleasure%2520rationally%2520encounter%2520consequences%2520that%2520are%2520extremely%2520painful.%2520Nor%2520again%2520is%2520there%2520anyone%2520who%2520loves%2520or%2520pursues%2520or%2520desires%2520to%2520obtain%2520pain%2520of%2520itself%252C%2520because%2520it%2520is%2520pain%252C%2520but%2520because%2520occasionally%2520circumstances%2520occur%2520in%2520which%2520toil%2520and%2520pain%2520can%2520procure%2520him%2520some%2520great%2520pleasure.%2520To%2520take%2520a%2520trivial%2520example%252C%2520which%2520of%2520us%2520ever%2520undertakes%2520laborious%2520physical%2520exercise%252C%2520except%2520to%2520obtain%2520some%2520advantage%2520from%2520it%253F%2520But%2520who%2520has%2520any%2520right%2520to%2520find%2520fault%2520with%2520a%2520man%2520who%2520chooses%2520to%2520enjoy%2520a%2520pleasure%2520that%2520has%2520no%2520annoying%2520consequences%252C%2520or%2520one%2520who%2520avoids%2520a%2520pain%2520that%2520produces%2520no%2520resultant%2520pleasure.At%2520vero%2520eos%2520et%2520accusamus%2520et%2520iusto%2520odio%2520dignissimos%2520ducimus%2520qui%2520blanditiis%2520praesentium%2520voluptatum%2520deleniti%2520atque%2520corrupti%2520quos%2520dolores%2520et%2520quas%2520molestias%2520excepturi%2520sint%2520occaecati%2520cupiditate%2520non%2520provident%252C%2520similique%2520sunt%2520in%2520culpa%2520qui%2520officia%2520deserunt%2520mollitia%2520animi%252C%2520id%2520est%2520laborum%2520et%2520dolorum%2520fuga.%2520Et%2520harum%2520quidem%2520rerum%2520facilis%2520est%2520et%2520expedita%2520distinctio.%2520Nam%2520libero%2520tempore%252C%2520cum%2520soluta%2520nobis%2520est%2520eligendi%2520optio%2520cumque%2520nihil%2520impedit%2520quo%2520minus%2520id%2520quod%2520maxime%2520placeat%2520facere%2520possimus%252C%2520omnis%2520voluptas%2520assumenda%2520est%252C%2520omnis%2520dolor%2520repellendus.%2520Temporibus%2520autem%2520quibusdam%2520et%2520aut%2520officiis%2520debitis%2520aut%2520rerum%2520necessitatibus%2520saepe%2520eveniet%2520ut%2520et%2520voluptates%2520repudiandae%2520sint%2520et%2520molestiae%2520non%2520recusandae.%2522%257D%257D&type=entity&deeplinkId=88a168ef-9d48-4de4-9575-2d6d0900fce1&directDl=true&msLaunch=true&enableMobilePage=true&suppressPrompt=true)

Launcher opened on click of link and desktop app is selected for launch:
<img width="1728" alt="Screenshot 2024-04-19 at 4 50 01 PM" src="https://github.com/MicrosoftDocs/msteams-docs/assets/74456536/cbe27ddf-9d27-4912-ae40-e7df440e453b">

In MAC system, the teams desktop app is launched. 
<img width="1728" alt="Screenshot 2024-04-19 at 4 50 39 PM" src="https://github.com/MicrosoftDocs/msteams-docs/assets/74456536/598ddd59-ae34-4d5d-82ab-2ecaf341b09f">

In case of windows, teams desktop is not launched if selected. No error is thrown.
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/74456536/683f4e24-229e-496c-9f82-0b8e60c83045)

### Expected behavior

The teams application should launch in desktop application in windows system.

### Actual behavior

The teams application does not launch in desktop application in windows system.

### Error details

There is no error thrown.

**Comment by Meghana-MSFT** [comment]
@kumarUtsav-01 - Could you please let us know which document are you following to construct the above deeplink? Here is the document for creating deeplinks https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links.

**Comment by kumarUtsav-01** [comment]
Hi @Meghana-MSFT , 
We are using the same document for generating deeplink. We are using the deeplink to manually link to a MS Teams tab application that we have created. We are adding some extra query parameters at the end to pass some data to the tab application. 
Once we launch the link, it goes to teams launcher page that I have attached as screenshots.

**Comment by Meghana-MSFT** [comment]
Are you following this https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-link-application?tabs=teamsjs-v2#configure-deep-link-to-browse-within-your-app-manually section? 



> Example of launcher link with 3300 characters in URL:
> [MSLink](https://teams.microsoft.com/dl/launcher/launcher.html?url=%2F_%23%2Fl%2Fentity%2Fb10b9797-db6a-42cb-9677-e79af0862da8%2Ftab%3F%26context%3D%257B%2522subEntityId%2522%253A%257B%2522url%2522%253A%2522%2522%252C%2522appTitle%2522%253A%2522DETAILS%2520ON%2520PRODUCT%2522%252C%2522subTitle%2522%253A%2522%2522%252C%2522mode%2522%253A%2522summary%2522%252C%2522message%2522%253A%2522But%2520I%2520must%2520explain%2520to%2520you%2520how%2520all%2520this%2520mistaken%2520idea%2520of%2520denouncing%2520pleasure%2520and%2520praising%2520pain%2520was%2520born%2520and%2520I%2520will%2520give%2520you%2520a%2520complete%2520account%2520of%2520the%2520system%252C%2520and%2520expound%2520the%2520actual%2520teachings%2520of%2520the%2520great%2520explorer%2520of%2520the%2520truth%252C%2520the%2520master-builder%2520of%2520human%2520happiness.%2520No%2520one%2520rejects%252C%2520dislikes%252C%2520or%2520avoids%2520pleasure%2520itself%252C%2520because%2520it%2520is%2520pleasure%252C%2520but%2520because%2520those%2520who%2520do%2520not%2520know%2520how%2520to%2520pursue%2520pleasure%2520rationally%2520encounter%2520consequences%2520that%2520are%2520extremely%2520painful.%2520Nor%2520again%2520is%2520there%2520anyone%2520who%2520loves%2520or%2520pursues%2520or%2520desires%2520to%2520obtain%2520pain%2520of%2520itself%252C%2520because%2520it%2520is%2520pain%252C%2520but%2520because%2520occasionally%2520circumstances%2520occur%2520in%2520which%2520toil%2520and%2520pain%2520can%2520procure%2520him%2520some%2520great%2520pleasure.%2520To%2520take%2520a%2520trivial%2520example%252C%2520which%2520of%2520us%2520ever%2520undertakes%2520laborious%2520physical%2520exercise%252C%2520except%2520to%2520obtain%2520some%2520advantage%2520from%2520it%253F%2520But%2520who%2520has%2520any%2520right%2520to%2520find%2520fault%2520with%2520a%2520man%2520who%2520chooses%2520to%2520enjoy%2520a%2520pleasure%2520that%2520has%2520no%2520annoying%2520consequences%252C%2520or%2520one%2520who%2520avoids%2520a%2520pain%2520that%2520produces%2520no%2520resultant%2520pleasure.At%2520vero%2520eos%2520et%2520accusamus%2520et%2520iusto%2520odio%2520dignissimos%2520ducimus%2520qui%2520blanditiis%2520praesentium%2520voluptatum%2520deleniti%2520atque%2520corrupti%2520quos%2520dolores%2520et%2520quas%2520molestias%2520excepturi%2520sint%2520occaecati%2520cupiditate%2520non%2520provident%252C%2520similique%2520sunt%2520in%2520culpa%2520qui%2520officia%2520deserunt%2520mollitia%2520animi%252C%2520id%2520est%2520laborum%2520et%2520dolorum%2520fuga.%2520Et%2520harum%2520quidem%2520rerum%2520facilis%2520est%2520et%2520expedita%2520distinctio.%2520Nam%2520libero%2520tempore%252C%2520cum%2520soluta%2520nobis%2520est%2520eligendi%2520optio%2520cumque%2520nihil%2520impedit%2520quo%2520minus%2520id%2520quod%2520maxime%2520placeat%2520facere%2520possimus%252C%2520omnis%2520voluptas%2520assumenda%2520est%252C%2520omnis%2520dolor%2520repellendus.%2520Temporibus%2520autem%2520quibusdam%2520et%2520aut%2520officiis%2520debitis%2520aut%2520rerum%2520necessitatibus%2520saepe%2520eveniet%2520ut%2520et%2520voluptates%2520repudiandae%2520sint%2520et%2520molestiae%2520non%2520recusandae.%2522%257D%257D&type=entity&deeplinkId=88a168ef-9d48-4de4-9575-2d6d0900fce1&directDl=true&msLaunch=true&enableMobilePage=true&suppressPrompt=true)

The above shared example link does not seem to be in the format mentioned in the doc. It has https://teams.microsoft.com/dl/launcher/launcher.html format which is different from the ones documented.

**Comment by kumarUtsav-01** [comment]
Correct, we are using that section only.

The URL that I shared is the launcher link (contains [https://teams.microsoft.com/dl/launcher/launcher.html](https://teams.microsoft.com/dl/launcher/launcher.html)) which automatically comes up when we launch the deeplink URL. This is the deeplink URL, that we are using
[MSDeepLink](https://teams.microsoft.com/l/entity/b10b9797-db6a-42cb-9677-e79af0862da8/tab?&context=%7B%22subEntityId%22%3A%7B%22url%22%3A%22%22%2C%22appTitle%22%3A%22DETAILS%20ON%20PRODUCT%22%2C%22subTitle%22%3A%22%22%2C%22mode%22%3A%22summary%22%2C%22message%22%3A%22But%20I%20must%20explain%20to%20you%20how%20all%20this%20mistaken%20idea%20of%20denouncing%20pleasure%20and%20praising%20pain%20was%20born%20and%20I%20will%20give%20you%20a%20complete%20account%20of%20the%20system%2C%20and%20expound%20the%20actual%20teachings%20of%20the%20great%20explorer%20of%20the%20truth%2C%20the%20master-builder%20of%20human%20happiness.%20No%20one%20rejects%2C%20dislikes%2C%20or%20avoids%20pleasure%20itself%2C%20because%20it%20is%20pleasure%2C%20but%20because%20those%20who%20do%20not%20know%20how%20to%20pursue%20pleasure%20rationally%20encounter%20consequences%20that%20are%20extremely%20painful.%20Nor%20again%20is%20there%20anyone%20who%20loves%20or%20pursues%20or%20desires%20to%20obtain%20pain%20of%20itself%2C%20because%20it%20is%20pain%2C%20but%20because%20occasionally%20circumstances%20occur%20in%20which%20toil%20and%20pain%20can%20procure%20him%20some%20great%20pleasure.%20To%20take%20a%20trivial%20example%2C%20which%20of%20us%20ever%20undertakes%20laborious%20physical%20exercise%2C%20except%20to%20obtain%20some%20advantage%20from%20it%3F%20But%20who%20has%20any%20right%20to%20find%20fault%20with%20a%20man%20who%20chooses%20to%20enjoy%20a%20pleasure%20that%20has%20no%20annoying%20consequences%2C%20or%20one%20who%20avoids%20a%20pain%20that%20produces%20no%20resultant%20pleasure.At%20vero%20eos%20et%20accusamus%20et%20iusto%20odio%20dignissimos%20ducimus%20qui%20blanditiis%20praesentium%20voluptatum%20deleniti%20atque%20corrupti%20quos%20dolores%20et%20quas%20molestias%20excepturi%20sint%20occaecati%20cupiditate%20non%20provident%2C%20similique%20sunt%20in%20culpa%20qui%20officia%20deserunt%20mollitia%20animi%2C%20id%20est%20laborum%20et%20dolorum%20fuga.%20Et%20harum%20quidem%20rerum%20facilis%20est%20et%20expedita%20distinctio.%20Nam%20libero%20tempore%2C%20cum%20soluta%20nobis%20est%20eligendi%20optio%20cumque%20nihil%20impedit%20quo%20minus%20id%20quod%20maxime%20placeat%20facere%20possimus%2C%20omnis%20voluptas%20assumenda%20est%2C%20omnis%20dolor%20repellendus.%20Temporibus%20autem%20quibusdam%20et%20aut%20officiis%20debitis%20aut%20rerum%20necessitatibus%20saepe%20eveniet%20ut%20et%20voluptates%20repudiandae%20sint%20et%20molestiae%20non%20recusandae.%22%7D%7D%27)

**Comment by Meghana-MSFT** [comment]
We are also able to repro this issue, we will check this internally and get back to you.

**Comment by Meghana-MSFT** [comment]
@kumarUtsav-01 - We checked this with engineering team and have the following recommendation-

There are maximum URL limits at the Windows level that Teams has no control over. App developer should limit their URL length to something that works. The app should call their backend to get the data rather than trying to pass it all through the deep link.

**Comment by kumarUtsav-01** [comment]
Yeah, I understand the link is long, but, the same link works in a MAC system. Please correct me if I am wrong, but, ideally shouldn't the link work either in both MAC and Windows or none of them?
if it is a windows level restriction it shouldn't have worked on browser on windows.
It works even for the windows browser app as well, just only windows desktop app has the issue. 
I urge you to recheck this.

**Comment by Meghana-MSFT** [comment]
We will check this internally and get back to you.

**Comment by ydogandjiev** [comment]
@kumarUtsav-01, the limitation comes from the Windows ShellExecuteEx API which the browser uses to launch the Teams Desktop Client to handle the deep link. ShellExecuteEx paths are limited by INTERNET_MAX_URL_LENGTH which is 2048 characters (and that needs to also include the path to the Teams executable).

You can find more details in these posts:
https://devblogs.microsoft.com/oldnewthing/20031210-00/?p=41553
https://stackoverflow.com/questions/26427286/passing-parameters-to-a-custom-uri
https://stackoverflow.com/questions/2916865/how-to-get-around-the-command-line-length-limit

Passing large amounts of data via deep links is not a good idea. You should instead pass a unique identifier the deep link that your app then uses to fetch the data from your backend service.

**Comment by kumarUtsav-01** [comment]
@ydogandjiev , our use-case does not allow storing of data as the data will be passed to the user in real time through our custom app for collaboration post a button click. Once, it is passed to the user, there is no point of holding that data for us. Can we try to communicate with Windows ShellExecute API service and ask them to increase the limit if that is possible?
