### ISSUE TITLE
Create Incoming Web Hooks article is only relevant for the deprecated old teams client

### ISSUE THREAD

**Issue by seth-lenvi** [MicrosoftDocs/msteams-docs#10764]
### Type of issue

Outdated article

### Feedback

Would like to know how to create an incoming webhook in the new teams but article is this one which is for this old teams. Can the article be updated to know how to create an incoming webhook in new teams (assuming using workflow)?

### Page URL

https://learn.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-incoming-webhook?tabs=newteams%2Cdotnet

### Content source URL

https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/webhooks-and-connectors/how-to/add-incoming-webhook.md

### Author

@surbhigupta

### Document Id

e3b53e27-2946-189c-623b-9df704ea8f12

**Comment by Prasad-MSFT** [comment]
Hi @seth-lenvi - To add an Incoming Webhook to a Teams channel in New Teams is explained here:
https://learn.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-incoming-webhook?tabs=newteams%2Cdotnet#create-an-incoming-webhook

However, this option is available for users who has admin privileges. Not to non-admin users.
We are tracking this limitation [here](https://github.com/MicrosoftDocs/msteams-docs/issues/10729).

**Comment by seth-lenvi** [comment]
Alright, that makes sense. Thank you for the update.
Seth



Classification Confidential

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, please feel free to reopen it, if required.

**Comment by martinvaner** [comment]
Hi, I think it would be better to mark documentation related to incoming webhook as deprecated as it will stop working on 1.10.2024. This information is provided just in one article that is not linked to documentation, or after setting up webhook and posting message.
Thank you.
