### ISSUE TITLE
Manifest v1.17 | Change log must be updated

### ISSUE THREAD

**Issue by surbhigupta12** [MicrosoftDocs/msteams-docs#10765]
### Type of issue

Missing information

### Feedback

https://github.com/OfficeDev/microsoft-teams-app-schema/releases

The manifest v1.17 related information must be updated in the change log

### Page URL

https://learn.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema

### Content source URL

https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/resources/schema/manifest-schema.md

### Author

@surbhigupta

### Document Id

7b3413f4-9ade-accf-5cb2-83fead11a32a

**Comment by surbhigupta12** [comment]
@AkJo , @srinidyMSFT, Charles Ji

**Comment by Prasad-MSFT** [comment]
Hi @AkJo , @srinidyMSFT - Could you please help here?

**Comment by v-sdhakshina** [comment]
This isn't a document issue, hence removing the doc enhancement label.
