### ISSUE TITLE
Custom URL won't open in MS Teams

### ISSUE THREAD

**Issue by GarethHJ** [MicrosoftDocs/msteams-docs#10766]
### Steps to reproduce

Hi Team,

We use a custom URL handler for our Windows software. The schema for the url is `iecm:` and this works nicely in other applications like Outlook, but it doesn't work in MS Teams (classic and new).

This is important for the integration of our software in the office suite and it would be great if Teams would support our url.

### Expected behavior

The link should be opened when you click on it using our custom url handler.

### Actual behavior

We can paste the url into a chat and it is displayed as a link (underlined in blue), but nothing happens when you left click on the link and no open command is shown when you right click on the link.

**Comment by Prasad-MSFT** [comment]
Hi @GarethHJ - Thanks for raising your issue. Could you please share the complete URL, so that we can check also from our end?

**Comment by GarethHJ** [comment]
@Prasad-MSFT - Yes, of course. Here are a couple of example URLs in full:

iecm://2cda1a23-6179-48bb-82db-9600a390afe1@swt-c-dev-csb1:8080/2b80a3d4-81b6-4b70-a82f-ca47ff490fbf/SD03DB1249f471ac6-c954-42cc-bf0f-f8ce80d9ed7b182024-04-18T17%3a35%3a23.995Z011.csb

iecm://sst-wfl-csb30.swtdev.local:8080/d5d32d3a-162b-4eda-b7a3-372f6dd363f3/ERP_100;Search_Project_Folder;ProjectNo=22A-10082.bas

**Comment by Prasad-MSFT** [comment]
@GarethHJ - Thanks for sharing these details. We will check this with engineering team whether its supported or not and will revert back.

**Comment by Prasad-MSFT** [comment]
Hi @GarethHJ - We got update from engineering team saying that there is plan to address this in the future but do not yet have a timeline we can publicly share.

Once we have an ETA, we will inform in this thread. Thanks!

**Comment by GarethHJ** [comment]
@Prasad-MSFT Great, thanks for the update! I'm looking forwarding to hearing when the problem wil be adressed...

**Comment by ChetanSharma-msft** [comment]
Hello @GarethHJ - I would suggest you to raise the feature request here: 
[Teams Feedback Portal](https://feedbackportal.microsoft.com/feedback/forum/ad198462-1c1c-ec11-b6e7-0022481f8472)

**Comment by GarethHJ** [comment]
Hello @Prasad-MSFT and @ChetanSharma-msft ,
Sure I can do that, but does that mean you won't be addressing the problem here? I thought the engineering team already have plans for this?

**Comment by ChetanSharma-msft** [comment]
Hello @GarethHJ - Engineering team has planned to consider this feature but we don't have any exact ETA to share with you.
Also, generally engineering team considers a feature if it's relevant and if there are lots of feature requests raised by different developers.

**Comment by GarethHJ** [comment]
Hi @ChetanSharma-msft
Thanks for the info and your prompt answers. I've raised the issue in the feedback portal: https://feedbackportal.microsoft.com/feedback/idea/f1e4b9a7-690b-ef11-a73d-6045bd7e894e
