### ISSUE TITLE
Deeplink is not working

### ISSUE THREAD

**Issue by pnumber** [MicrosoftDocs/msteams-docs#10770]
### Type of issue

Feature doesn't work (bug)

### Feedback

Suddenly, when I create a group chat with the API, the Teams chat shows a list. However, when I access the chat with a deep link, an error occurs as if the chat room does not exist. If I turn off Teams and turn it back on, it works fine. In web Teams, when I refresh it works fine.

### Page URL

https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-link-teams#deep-link-to-navigate-to-a-chat

### Content source URL

https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/build-and-test/deep-link-teams.md

### Author

@v-npaladugu

### Document Id

b6687ceb-6d67-b0b7-0797-b16d14e4bd97

**Comment by Prasad-MSFT** [comment]
Hi @pnumber - Could you please confirm whether our understanding of the issue correct or wrong?
1. You created a chat using Graph API.
2. Then you formed a deep link to navigate to the chat
3. On clicking of that deep link, you are not able to navigate anywhere, it throws some error message.

Now please let us know if this is happening in New Teams client or Classic Teams? And what exact error message you are getting?

**Comment by Prasad-MSFT** [comment]
We tested using below deep link and observed that it works perfectly fine in both MS Teams Desktop and Web client.
`https://teams.microsoft.com/l/chat/19:23xxb5efbe06xx568xxxx3aa5xxxxdac@thread.v2/conversations`

```
Microsoft Teams version 24114.1000.2834.1395.
The client version is 49/24031414720.
```
