### ISSUE TITLE
Feedback - More validation on Copilot plugin

### ISSUE THREAD

**Issue by v-preethah** [MicrosoftDocs/msteams-docs#10787]
### Type of issue

Other (describe below)

### Feedback

Hi,
As per the Validation feedback received, we need information on more information w.r.t validation on Copilot plugin to update docs.

https://teams.microsoft.com/l/message/19:f644a5a5a4014455bfbce837a9da18e5@thread.skype/1711545550388?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=a52e1950-7711-4c1f-8550-dd4a00dbeb43&parentMessageId=1711545550388&teamName=Customer%20%26%20Partner%20Team%20(CaPT)&channelName=App%20Validation&createdTime=1711545550388

### Page URL

https://learn.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/high-quality-message-extension?tabs=tasks

### Content source URL

https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/messaging-extensions/high-quality-message-extension.md

### Author

@v-preethah

### Document Id

1d9e7d3e-f334-2862-3e44-e4db9d1a4fb3

**Comment by Prasad-MSFT** [comment]
Hi @v-preethah - Could you please provide more details on the issue? Its not quite clear what needs to be documented.

**Comment by v-preethah** [comment]
Hi @Prasad-MSFT 

We have received the below feedback, where the user wants more information w.r.t validation on Copilot plugins.

<img width="394" alt="image" src="https://github.com/MicrosoftDocs/msteams-docs/assets/117343020/e670f13f-7d6e-48f0-87e4-fbe10ace07c1">

Do we have any more validation checks on Copilot plugins apart from those information provided in the article?

**Comment by Prasad-MSFT** [comment]
@v-preethah - Currently the ones available are described already in documentation. 
https://learn.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/high-quality-message-extension?tabs=tasks
