### ISSUE TITLE
Deeplink to static tab breaks navigation in app - New Teams only

### ISSUE THREAD

**Issue by milcem** [MicrosoftDocs/msteams-docs#10797]
### Steps to reproduce

https://github.com/OfficeDev/Microsoft-Teams-Samples/issues/1227 

Every step and code we use as well as the behavior is outlined multiple times in the issue I opened in the Microsoft-Teams-Sample branch. I have not gotten close to getting any help or advice on the matter, and as this is severely affecting our user experience for our SaaS application, we have an internal team that is still spending time and resources trying to figure out what is wrong with deeplinking with context to static tab in Teams V2. Would really really appreciate any indication on whether this is our issue and how we can go ahead to fix it, or if it is a Teams bug. Much appreciated.

### Expected behavior

We have a custom Teams app that is a bot and static tabs. They use the same external app id. The bot sends a link as a button in an adaptive card in the Chat tab of the app, and when the user clicks on it, it opens the Static tab it points to with the subEntityid context. In Old Teams, everything worked as expected.

### Actual behavior

On New Teams, when we click on the deeplink pointing to a static tab with context, it opens the static tab, and the right context, but the Chat tab disappears, the rest of the static tabs remain, if you click on any of them, or refresh the existing tab, or try to click on the application on the sidebar of teams, it will prompt the Teams App Store dialog to open the app. So navigation in app seems broken when we use a deeplink. The same behavior happens when we used a deeplink in one static tab, that is supposed to navigate to another static tab, so it is not just the bot or adaptive cards sending the deeplink.

**Comment by Vikram-MSFT** [comment]
Hello @milcem
This issue will be tracked here could you please refer this thread:
https://github.com/OfficeDev/Microsoft-Teams-Samples/issues/1227

**Comment by milcem** [comment]
> Hello @milcem This issue will be tracked here could you please refer this thread: [OfficeDev/Microsoft-Teams-Samples#1227](https://github.com/OfficeDev/Microsoft-Teams-Samples/issues/1227)

Sure, I figured to post it here in case it is more connected to the Documentation as well, as potentially getting other MSFT support people's eyes on it. Would really appreciate a response, I would assume you could check at least whether you could reproduce the issue and let me know? I have been asking for some indication on that because we are spending company resources on figuring it out and can't stop until Microsoft confirms it is a bug and they will take care of it. It is a bit frustrating as I've asked this question since 3 weeks ago, with a detailed breakdown of the app scenario, the code, and somehow get answers that have nothing to do with what I am asking? 

I do appreciate any helpful support on the matter.

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, please feel free to reopen it, if required.
