### ISSUE TITLE
How can we achieve SSO Authentication in Teams Tab With server side using ADAL.NET  Instead of adal.js

### ISSUE THREAD

**Issue by anomepani** [MicrosoftDocs/msteams-docs#1080]
I am exploring SSO Authentication in Teams Tab which provides the use of adal.js which is client-side.
How can we achieve SSO Authentication in Teams Tab With server side using ADAL.NET  Instead of adal.js
Thanks in advance.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be314181-4800-4d02-cf62-fb276dc7cdd2
* Version Independent ID: 259e41a3-0607-c3f8-f635-f6bce767ad2b
* Content: [Silent authentication and SSO - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/authentication/auth-silent-aad)
* Content Source: [msteams-platform/concepts/authentication/auth-silent-AAD.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/authentication/auth-silent-AAD.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Trinetra-MSFT** [comment]
Currently SSO authentication in teams tab uses only adal.js library which creates a hidden iframe for OAuth 2.0 implicit grant flow and set `prompt=none`. But you can also configure msal.js library for Single-sign on Please take a look at [Single-sign-on with MSAL.js](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-js-sso).

**Comment by anomepani** [comment]
@Trinetra-MSFT Thank you. I will take look for sure. Actually I want to use ADAL.NET or MSAL.NET to store cache token on the server-side instead of client-side. Can you advise on how to achieve SSO Authentication in MS Teams In tab With Adal.Net or MSAL.NET

**Comment by Trinetra-MSFT** [comment]
@anomepani , Please take a look at [SSO in Tabs](https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/19.a.single-sign-on-for-enterprise-apps).

**Comment by Gousia-MSFT** [comment]
Please re-open if you still have any queries.

**Comment by KaushalKhamar** [comment]
@Trinetra-MSFT  Example you have provided is not available. Can you please check?

> @anomepani , Please take a look at [SSO in Tabs](https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/19.a.single-sign-on-for-enterprise-apps).
