### ISSUE TITLE
I am using teams tabs and I am navigating to web app on click of button, Once Navigated to browser when we come back to teams desktop app , page goes blank.

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#10805]
### Type of issue

Feature doesn't work (bug)

### Feedback

Copied From: https://github.com/OfficeDev/TeamsFx/issues/11447

I am using teams tabs, and I am navigating to web app on click of button, Once Navigated to browser when we come back to teams desktop app , page goes blank.This happens only in desktop version of teams and on browser teams its working fine.

function openInNewTab(url) {
const win = window.open(url, '_blank');
win.focus();
}

I am using the above function to open url.It uses default browser and opens the link. but when we go back to tab , screen goes white.

You have Microsoft Teams version 24074.2323.2827.4973.

![image](https://github.com/MicrosoftDocs/msteams-docs/assets/31851992/4f8ab524-d021-4f61-b471-1421d08e1da8)

### Page URL

https://learn.microsoft.com/en-us/microsoftteams/platform/toolkit/teams-toolkit-fundamentals

### Content source URL

https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/teams-toolkit-fundamentals.md

### Author

@zyxiaoyuer

### Document Id

b743e43d-95cc-3d1e-b142-31a16369f97e

**Comment by Vaibhav-MSFT** [comment]
@VKZycus, We tested this from our side in teams desktop client, using the code shared but we are not getting any blank screen while navigating back to teams from browser.
Sample used- https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/tab-sso/nodejs
Teams version- 24091.214.2846.1452.
