### ISSUE TITLE
Suggested actions display limit in Microsoft Teams

### ISSUE THREAD

**Issue by SubbaReddi** [MicrosoftDocs/msteams-docs#10808]
### Type of issue

Outdated article

### Feedback

Hi Team,
Documentation referring to following note related to number of suggested actions: 
imBack is the only supported action type and Teams display up to **three** suggested actions.

But Teams can display up to Six suggested actions. So, Please update the note.

### Page URL

https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-messages?tabs=dotnet1%2Capp-manifest-v112-or-later%2Cdotnet2%2Cdotnet3%2Cdotnet4%2Cdotnet5%2Cdotnet#send-suggested-actions

### Content source URL

https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/bots/how-to/conversations/conversation-messages.md

### Author

@surbhigupta

### Document Id

ef6b8aee-52e7-f5d4-7dfa-8f34a1698330

**Comment by ChetanSharma-msft** [comment]
Hello @surbhigupta12 - Please help to add a note in the documentation like:
Teams display up to **six** suggested actions
