### ISSUE TITLE
Closing the main window makes Teams unusable

### ISSUE THREAD

**Issue by ngrigoriev** [MicrosoftDocs/msteams-docs#1081]
Environment Mac OS X 10.14.6
Teams: 1.2.00.28258.

It happened to me several times, accidentally clicking Cmd+W and closing the main Teams window. After that there seems to be no way to reopen it from the Teams app. Other apps like Slack etc (or even Outlook) have the shortcuts to reopen the windows, such as Cmd+1 in Outlook. When I accidentally close Teams window, the only way to get back is to restart the app.

**Comment by Gousia-MSFT** [comment]
@ngrigoriev Thanks for reaching out. We are looking into this?

**Comment by Gousia-MSFT** [comment]
@ngrigoriev Could you please share a video recording of the issue?

**Comment by Gousia-MSFT** [comment]
Please re-open with requested information.

**Comment by ngrigoriev** [comment]
I have found a work-around for your problem - teams window can be reopen by launching it again (while the app is still running with the main window closed) or by clicking Teams icon in the dock. If you do not want to spend 30 seconds reproducing it as per my clear description, why should I spend 5 minutes recording and posting the video?
