### ISSUE TITLE
Property name should not be color32x32

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#10825]
### Type of issue

Other (describe below)

### Feedback

This will create an issue if we decide to change the resolution of icon. 

### Page URL

https://review.learn.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema-dev-preview?branch=pr-en-us-10437

### Content source URL

https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/resources/schema/manifest-schema-dev-preview.md

### Author

@surbhigupta

### Document Id

b2536bbc-eb27-547d-d7f5-bab3ded3bedf

**Comment by Vikram-MSFT** [comment]
Hello @surbhigupta12 
Could you please help here as per document suggested?

**Comment by surbhigupta12** [comment]
This is not a doc bug. Need to raise it to the manifest team.
