### ISSUE TITLE
High Contrast Color Ramp

### ISSUE THREAD

**Issue by beauzeaux** [MicrosoftDocs/msteams-docs#1082]
Can we get a "High Contrast" color ramp as well? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab4100d3-1a06-29b9-dedc-d0eaed0b4718
* Version Independent ID: 3c582b5e-e654-458d-62da-95706b3370fc
* Content: [Design Guidelines Reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/design/components/color#feedback)
* Content Source: [msteams-platform/resources/design/components/color.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/resources/design/components/color.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by KirtiPereira** [comment]
Issue closed based on update received from Heath (03/16) about the  design team (Cristian) confirming that there are no plans to add this to any docs since the Teams client will handle the color changes automatically.
