### ISSUE TITLE
"Context" link is broken

### ISSUE THREAD

**Issue by nkramer** [MicrosoftDocs/msteams-docs#1083]
should be https://docs.microsoft.com/en-us/javascript/api/@microsoft/teams-js/microsoftteams.context?view=msteams-client-js-latest

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 525acdf7-3f72-b657-63ea-ddb95c4fb247
* Version Independent ID: c5d9575a-ace3-8441-4516-ad2c7adb3d99
* Content: [Get context for your tab - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/tabs/tabs-context#feedback)
* Content Source: [msteams-platform/concepts/tabs/tabs-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/tabs/tabs-context.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by clearab** [comment]
fixed!
