### ISSUE TITLE
Feedback link not working.

### ISSUE THREAD

**Issue by Vaibhav-MSFT** [MicrosoftDocs/msteams-docs#10830]
### Type of issue

Typo

### Feedback

1) "European" is misspelled as "Europen".
2) Feedback link not working, giving 404 error while accessing.

### Page URL

https://learn.microsoft.com/en-us/azure/bot-service/bot-builder-concept-regionalization?view=azure-bot-service-4.0#register-regional-azure-bots

### Content source URL

https://learn.microsoft.com/en-us/azure/bot-service/bot-builder-concept-regionalization?view=azure-bot-service-4.0#register-regional-azure-bots

### Author

Vaibhav-MSFT

### Document Id

https://learn.microsoft.com/en-us/azure/bot-service/bot-builder-concept-regionalization?view=azure-bot-service-4.0#register-regional-azure-bots

**Comment by Vaibhav-MSFT** [comment]
Hello @surbhigupta12 ,
Could you please help here updating the document for typo and fixing the link not working?

**Comment by surbhigupta12** [comment]
Hi @Vaibhav-MSFT, @ChetanSharma-msft, 

We do not have access to this repo. You'd have to reach out to the concerned team:

**Comment by ChetanSharma-msft** [comment]
Hello @JonathanFingold - Could you please help us on this issue?
