### ISSUE TITLE
App catalog URL changed

### ISSUE THREAD

**Issue by SubbaReddi** [MicrosoftDocs/msteams-docs#10846]
### Type of issue

Outdated article

### Feedback

We see app catalog URL is changed from https://YOUR_TENANT_NAME.sharepoint.com/sites/appcatalog/AppCatalog/Forms/AllItems.aspx
to 
https://YOUR_TENANT_NAME.sharepoint.com/sites/apps/AppCatalog/Forms/AllItems.aspx

So, please update the same in documentation.

### Page URL

https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/tabs-in-sharepoint#use-teams-tab-in-sharepoint

### Content source URL

https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/tabs/how-to/tabs-in-sharepoint.md

### Author

@surbhigupta

### Document Id

afcc83c4-12c0-bab6-1cec-61ac463b4f60

**Comment by Vikram-MSFT** [comment]
Hello @surbhigupta12 
Could you please help here in app catalog URL Getting updated- from https://your_tenant_name.sharepoint.com/sites/apps/AppCatalog/Forms/AllItems.aspx to https://your_tenant_name.sharepoint.com/sites/appcatalog/AppCatalog/Forms/AllItems.aspx
