### ISSUE TITLE
URL Returns 404

### ISSUE THREAD

**Issue by bmedenwald** [MicrosoftDocs/msteams-docs#10849]
### Type of issue

Outdated article

### Feedback

Instructions mention https://your_tenant_name.sharepoint.com/sites/apps/AppCatalog/Forms/AllItems.aspx, but this URL once fixed up returns a 404. Speaking with developer support, the URL should be https://your_tenant_name.sharepoint.com/sites/appcatalog/AppCatalog/Forms/AllItems.aspx

### Page URL

https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/tabs-in-sharepoint#use-teams-tab-in-sharepoint

### Content source URL

https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/tabs/how-to/tabs-in-sharepoint.md

### Author

@surbhigupta

### Document Id

afcc83c4-12c0-bab6-1cec-61ac463b4f60

**Comment by Vikram-MSFT** [comment]
Hello @surbhigupta12 
Developer is getting error 404 whenever he is using this https://your_tenant_name.sharepoint.com/sites/apps/AppCatalog/Forms/AllItems.aspx, 
Could you please help here to update the document as per suggested?

**Comment by Vikram-MSFT** [comment]
Hello @bmedenwald 
This document has got updated with the new URL as per your suggestions.
