### ISSUE TITLE
How to redirect user from one of custom tab in Microsoft teams app to specific team

### ISSUE THREAD

**Issue by anomepani** [MicrosoftDocs/msteams-docs#1085]
How to redirect user from one of custom tab in Microsoft teams app to specific team?
I have seen in feature like get team link and you can sent it to chat message and of you click on that link it will automatically redirect to that specific team. 

I am not clear how we can do it programatically to generate link to team and redirect to that team in tabs(custom app)  using microsoft team sdk

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a891841a-a110-d18e-25c1-fc29e7d4a5e3
* Version Independent ID: c1a11eb8-00d1-e1d2-1e9d-71d059a6478a
* Content: [Create deep links - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/deep-links)
* Content Source: [msteams-platform/concepts/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/deep-links.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Gousia-MSFT** [comment]
@anomepani Could you please try [Deeplinking from Tab](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/deep-links#deep-linking-from-your-tab). You could use microsoftTeams.executeDeepLink() method to deeplink from your tab. Here is an example to open deeplink on button click from tab:
`<button type="submit"onclick="microsoftTeams.executeDeepLink('deeplinkurl')">Go To DeepLink</button>`

**Comment by anomepani** [comment]
@Gousia-MSFT thanks for quick reply I will definitely try for sure and get back to you  if I  need help. 
Thanks

**Comment by anomepani** [comment]
Any updates on this which provide working demo on this

**Comment by Subhasish-msft** [comment]
The URL format you used is correct. You need to provide different channeId and groupId in each deeplink.
Below is the valid deeplink URL format:
`https://teams.microsoft.com/l/team/<ChannelId>/<ChannelName>?groupId=<TeamId>&tenantId=</TenantId>`

**Comment by anomepani** [comment]
@Subhasish-msft thanks for the reply redirection worked for me. However, in-browser `unknown` text is appended and in-browser console  `postMessage` not allowed error is occuring not sure what is the reason for that

**Comment by Subhasish-msft** [comment]
@anomepani, Are you still facing this issue? Can you please share screenshot of browser console error that you are getting. Sorry for the late response?

**Comment by anomepani** [comment]
Getting error in console but I  am able redirect to specific team.so Closing this issue.
