### ISSUE TITLE
Unexpected behavior of notification text and summary

### ISSUE THREAD

**Issue by sschutten** [MicrosoftDocs/msteams-docs#1086]
The docs say:

> When constructing your message, the following fields should be populated so that the correct preview content can be shown in the feed:
> - message.text, which shows up as the activity title
> - message.summary, which shows up as the activity text

However, I notice a different behavior when using the Microsoft Bot Framework SDK.

In the following sample I've set message.text to `This is the activity text` and message.summary to `This is the summary text`. Notice it doesn't show the summary in the activity feed.

![image](https://user-images.githubusercontent.com/10097564/67577028-fbbd5380-f73f-11e9-93c2-2bd63d50a2d8.png)

Now, when I add a HeroCard as an attachment to the same message, I see the following. The text property of the HeroCard is set to 'This is the HeroCard text'. Notice that this time it does show the summary. Even more surprising, it uses the text of the HeroCard as the title.

![image](https://user-images.githubusercontent.com/10097564/67576997-eba57400-f73f-11e9-87ce-a8781a52f5ea.png)

It appears there's more going on than just setting the text and summary properties.
1. How can I get the summary to show for just a plain text activity?
2. When does the activity feed use the text property of an attachment?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd0d8d78-1ad5-5a99-3ef9-b03124476ebf
* Version Independent ID: 64505c8a-4f08-0454-2602-8821ca29c218
* Content: [Activity feed - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/activity-feed)
* Content Source: [msteams-platform/concepts/activity-feed.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/activity-feed.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Gousia-MSFT** [comment]
@sschutten Are you trying this in personal scope or channel scope? The activity feed customization only applies to 1:1 messages between a bot and a user, as called out in the [page](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/activity-feed):
Note
This applies to one-to-one messages between a bot and a user. Messages inserted into a channel generate a notification in the activity feed based on the user's notification settings for that channel.
In the case of a post to a channel, the fields in the activity feed notification are standard (action, location, text).

**Comment by sschutten** [comment]
@Gousia-MSFT I'm sorry I haven't been clear on that. Yes, I'm trying this in the personal scope, where it should work. I'm aware that it doesn't work in the channel scope.

**Comment by Subhasish-msft** [comment]
@sschutten, Currently summary property is considered for activity-feed only if the message contains an attachment. Otherwise, it is derived form message text and summary is ignored. That's why in this case Hero card summary is working fine but not the text message.
We are updating same in the document shortly.

**Comment by laujan** [comment]
The activity feed notification behavior is now documented here: https://docs.microsoft.com/microsoftteams/platform/bots/how-to/conversations/conversation-basics?tabs=dotnet#adding-notifications-to-your-message
