### ISSUE TITLE
Example for native mobile app?

### ISSUE THREAD

**Issue by butchmarshall** [MicrosoftDocs/msteams-docs#1087]
I've implemented this flow and it works perfectly in the website and fails miserably in the Android/iOS apps.

Can documentation be added here that implements the authentication flow in those environments as well?

Below is the message contained in the hash.

![image](https://user-images.githubusercontent.com/339763/67578601-ca795f00-f710-11e9-8604-90a4cb29d48e.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be314181-4800-4d02-cf62-fb276dc7cdd2
* Version Independent ID: 259e41a3-0607-c3f8-f635-f6bce767ad2b
* Content: [Silent authentication and SSO - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/authentication/auth-silent-aad)
* Content Source: [msteams-platform/concepts/authentication/auth-silent-AAD.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/authentication/auth-silent-AAD.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Gousia-MSFT** [comment]
@butchmarshall Are you doing this in Tab? Currently SSO is only supported in Tabs. Support for SSO in bots is something we are working on.

**Comment by Trinetra-MSFT** [comment]
@butchmarshall, Are you trying SSO in Message extension? if this is the scenario currently SSO is only supported in tabs, we are working on support for Bot and Message Extension too.

**Comment by butchmarshall** [comment]
Hi @Trinetra-MSFT - yes I'm doing SSO in a messaging extension.

The [OAuth 2.0 code grant flow](https://docs.microsoft.com/en-us/azure/active-directory/develop/v1-protocols-oauth-code) seems to work for me in both web and native app without any authorization prompts!

Is this expected?  Can I rely on this in the foreseeable future to authentication my users?  If not - how is user authentication supposed to work in 3rd party messaging extensions?

I'm using the `@microsoft/teams-js` packages getContext function to retrieve the `loginHint`.

```
GET
https://login.microsoftonline.com/[tenant id]/oauth2/authorize?

login_hint: [getContext.loginHint]
response_type: code
client_id: [azure app id]
redirect_uri: [messaging extension URL]
response_mode: fragment
scope: offline_access https://graph.microsoft.com/.default
state: ...
nonce: ...
```

**Comment by butchmarshall** [comment]
Just an update.

It looks like the above works in Android but iOS forces a login on first view.

Androids login (from initially logging into the app) also expires after a few days after initial login and eventually forces another login...
