### ISSUE TITLE
Opening Teams Deeplink in iOS presents 'link not supported' error

### ISSUE THREAD

**Issue by shootex20** [MicrosoftDocs/msteams-docs#10871]
### Steps to reproduce

When attempting to open a link using the teams deeplink, we are presented with the following error in iOS:

![image](https://github.com/MicrosoftDocs/msteams-docs/assets/19786531/e8933e0d-2bcb-47a2-9c64-f721870ddc7e)

This has worked previously with no issues and seems to be in a recent update. we are able to reproduce consistently with an iPhone 11, and iOS 17.4.1

### Expected behavior

Link should redirect properly using the supplied teams deeplink

### Actual behavior

Error popup that says 'Link not supported'

**Comment by Prasad-MSFT** [comment]
Hi @shootex20 - Could you please share the deep link url on clicking of which you are getting this error in New Teams in iOS devices?

**Comment by shootex20** [comment]
> Collaborator

Hello, sure. See below one of the links with issues: https://teams.microsoft.com/l/entity/3c3fd877-1803-4b62-9057-a9ab49263c5d/66f115d3-dded-496c-a5e3-7499f3c3202f?context=%7B%22subEntityId%22%3A%22post%7Cd3d38c21-4c3b-4733-bef2-e7804efb1b8b%7C%22%7D

**Comment by Prasad-MSFT** [comment]
@shootex20 - Thanks for sharing this. We will check and will get back to you.

**Comment by shootex20** [comment]
> @shootex20 - Thanks for sharing this. Could you please let us know what this deep link does? Does it redirect to any app? Also share the official document link you followed to get the deep link format.

Hi, this deep link does redirect to an app. This would be the guide https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-link-application?tabs=teamsjs-v2

The deep link works on android and teams desktop / browser perfectly fine just not ios

**Comment by Prasad-MSFT** [comment]
Hi @shootex20 , we tried to repro this issue using the deep link to navigate to any app and observed that it works fine in both desktop/web and android/iOS clients. It redirects to desired tab app.

Also, we observed that the deep link format you used doesn't  match any format being used here:
https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-link-application?tabs=teamsjs-v2

**Comment by shootex20** [comment]
> Hi @shootex20 , we tried to repro this issue using the deep link to navigate to any app and observed that it works fine in both desktop/web and android/iOS clients. It redirects to desired tab app.
> 
> Also, we observed that the deep link format you used doesn't match any format being used here: https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-link-application?tabs=teamsjs-v2

Sorry for the delay, the format is similar as it looks like it's missing the tenant id which we do not use. But, I can't see this being the issue, we do have custom context in order to redirect the user to the specified tab and open data using the specified guid. I'll attempt a re-test on our end and let you know. This is just affecting iOS 17.4.1 all other platforms work perfectly fine.
