### ISSUE TITLE
Schema url should be V1.17 instead of V1.16

### ISSUE THREAD

**Issue by Pawank-MSFT** [MicrosoftDocs/msteams-docs#10889]
### Type of issue

Other (describe below)

### Feedback

"$schema": "https://developer.microsoft.com/json-schemas/teams/v1.16/MicrosoftTeams.schema.json",
    "manifestVersion": "1.17",
    "version": "1.0.0",
    "id": "%MICROSOFT-APP-ID%",

### Page URL

https://learn.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema

### Content source URL

https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/resources/schema/manifest-schema.md

### Author

@surbhigupta

### Document Id

7b3413f4-9ade-accf-5cb2-83fead11a32a

**Comment by Prasad-MSFT** [comment]
Hi @surbhigupta12 - Could you please help here updating the document as suggested?
