### ISSUE TITLE
App Deeplinking issue on New Teams

### ISSUE THREAD

**Issue by venkatx5** [MicrosoftDocs/msteams-docs#10882]
### Type of issue

Feature doesn't work (bug)

### Feedback

https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-link-application?tabs=teamsjs-v2#configure-deep-link-manually-using-your-app-id

This app deeplinking option not works well now Teams now shows popup with "Switch to new teams" option. When pressing that button, it navigates to v2 url and don't remember the app.

### Page URL

https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-link-application?tabs=teamsjs-v2

### Content source URL

https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/build-and-test/deep-link-application.md

### Author

@v-npaladugu

### Document Id

059b1a94-8235-8801-b9e0-ac6fbc485a7c

**Comment by ChetanSharma-msft** [comment]
Hello @venkatx5 - Thanks for raising your query.
We will look into it and let you know the updates.

**Comment by Vikram-MSFT** [comment]
Hello @surbhigupta12 
Could you please help here in document get updated as suggested?

**Comment by Prasad-MSFT** [comment]
Hi @venkatx5 - Is this issue happening for you in Teams classic client? If my understanding of issue is correct, could you please let us know if this is the issue you are encountering?
1.You are using this deeplink `(https://teams.microsoft.com/l/app/<your-app-id>?tenantId=<tenantId>`) to navigate to app in Teams classic
2.On clicking of the button, it shows you the message saying, "Switch to new teams" and on clicking that its not opening the desired app

Please let me know if my understanding is correct or not
