### ISSUE TITLE
Recording in Teams

### ISSUE THREAD

**Issue by MattEngler** [MicrosoftDocs/msteams-docs#1088]
When I hit the record button it says there was an issue and it actually started recording.

**Comment by dwtuts** [comment]
Could you get the logs and past them to this issue? 
https://docs.microsoft.com/en-us/microsoftteams/log-files

**Comment by Gousia-MSFT** [comment]
@MattEngler Could you please share a video recording of the issue along with the logs captured during the repro? You could get the logs by clicking Ctrl+Alt+Shift+1 with Teams app in focus.

**Comment by Gousia-MSFT** [comment]
Please re-open with requested information.
