### ISSUE TITLE
Unconventional ampersand and value in deep link parameter table for "openInMeeting" parameter

### ISSUE THREAD

**Issue by AE-MS** [MicrosoftDocs/msteams-docs#10892]
### Type of issue

Typo

### Feedback

In the table of query parameters listed here:
https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-link-application?tabs=teamsjs-v2#configure-deep-link-to-browse-within-your-app-manually

They all follow a pattern in the parameter name: they are just a parameter name. All of them follow this except "openInMeeting" which additionally includes an ampersand and a value assignment. It seems like this parameter should just be a name, like the others.

### Page URL

https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-link-application?tabs=teamsjs-v2#deep-link-to-open-application-install-dialog

### Content source URL

https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/build-and-test/deep-link-application.md

### Author

@v-npaladugu

### Document Id

059b1a94-8235-8801-b9e0-ac6fbc485a7c

**Comment by Meghana-MSFT** [comment]
Thank you for reporting this, we will check this and update the documentation.
