### ISSUE TITLE
Passing PowerApps Parameters

### ISSUE THREAD

**Issue by IQof20** [MicrosoftDocs/msteams-docs#1089]
What I'm not finding clear here is the passing of URL parameters into PowerApp tabs.  I've attempted a number of methods to get "inline variables" passed into a PowerApp tab and it does not seem to work (e.g. https://...&name=value).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a891841a-a110-d18e-25c1-fc29e7d4a5e3
* Version Independent ID: c1a11eb8-00d1-e1d2-1e9d-71d059a6478a
* Content: [Create deep links - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/deep-links#feedback)
* Content Source: [msteams-platform/concepts/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/deep-links.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Trinetra-MSFT** [comment]
@IQof20, In Powerapps parameters can be sent in URL like `https://...?Name=xyz`
You can achieve this even by setting up value to the variable by using Set function and access that variable whereever it required. Please check the documents.
https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-set

**Comment by IQof20** [comment]
That works (of course if you have a tenantID already in your PowerApps URLs then it's &Name=xyz), but what I'm really talking about is heavily outlined on my blog here:  http://persnicketypowerapps.blogspot.com/2019/10/you-cannot-pass-web-parameters-into.html
