### ISSUE TITLE
The link to the pages.navigateToApp() documentation on this page is broken

### ISSUE THREAD

**Issue by AE-MS** [MicrosoftDocs/msteams-docs#10894]
### Type of issue

Feature doesn't work (bug)

### Feedback

In this section:
https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-link-application?tabs=teamsjs-v2#configure-deep-link-to-a-tab-using-teamsjs
...there is this text:
"For more information about using the pages capability, see [pages.navigateToApp()](https://learn.microsoft.com/en-us/javascript/api/@microsoft/teams-js/pages?view=msteams-client-js-latest#@microsoft-teams-js-pages-navigatetoapp&preserve-view=true) and the [pages](https://learn.microsoft.com/en-us/javascript/api/@microsoft/teams-js/pages?view=msteams-client-js-latest&preserve-view=true) namespace..."

The pages.navigateToApp() link goes here:
https://learn.microsoft.com/en-us/javascript/api/@microsoft/teams-js/pages?view=msteams-client-js-latest#@microsoft-teams-js-pages-navigatetoapp&preserve-view=true

That does not actually direct you to the documentation for that function. Instead, it only takes you to the top of the page. The working link is:
https://learn.microsoft.com/en-us/javascript/api/@microsoft/teams-js/pages?view=msteams-client-js-latest#@microsoft-teams-js-pages-navigatetoapp

That's a very similar URL, but it does not have the `&preserve-view=true` part tacked on to the end. That part seems to be what is breaking the direct navigation.

### Page URL

https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-link-application?tabs=teamsjs-v2#configure-deep-link-to-browse-within-your-app-manually

### Content source URL

https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/build-and-test/deep-link-application.md

### Author

@v-npaladugu

### Document Id

059b1a94-8235-8801-b9e0-ac6fbc485a7c

**Comment by AE-MS** [comment]
This same problem seems to exist with many of the direct-to-function link attempts on that page. Did the docs navigation system used to support `&preserve-view=true` and now it doesn't?

**Comment by ChetanSharma-msft** [comment]
Hello @AE-MS - Thanks for raising your query.
We will look into it and let you know the updates.

**Comment by Vaibhav-MSFT** [comment]
Hello @surbhigupta12  , 
Can you please help here in updating the document as suggested. We also found that the navigation is broken and does not point to the exact section for pages.navigateToApp().

**Comment by AE-MS** [comment]
@v-ramyas5 @surbhigupta12 
This issue is not completely fixed. In my comment above, I said:

"This same problem seems to exist with many of the direct-to-function link attempts on that page."

However, the fix to which you linked only fixed the problem for the specific `pages.navigateToApp()` link. There are many other deep links on the page that are still broken. If this issue is not tracking fixing the whole page, which issue is?

**Comment by surbhigupta12** [comment]
@AE-MS, apologies for the oversight. We have reopened the issue and are working on resolving it.
