### ISSUE TITLE
The syntax coloring is broken in part of the code on this page

### ISSUE THREAD

**Issue by AE-MS** [MicrosoftDocs/msteams-docs#10895]
### Type of issue

Feature doesn't work (bug)

### Feedback

In this section:
https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/tab-navigation#navigate-between-tabs
...most of the syntax coloring in the first JavaScript code box is missing/broken:

<img width="648" alt="image" src="https://github.com/MicrosoftDocs/msteams-docs/assets/36546967/c2fee5b1-0771-4d09-a015-6af5d9f812d7">

A few keywords are blue, but not all of them (e.g., `else` is not) and none of the comments are green. The subsequent code box doesn't seem to have the same problem:

<img width="648" alt="image" src="https://github.com/MicrosoftDocs/msteams-docs/assets/36546967/eb39a958-16dc-43c7-a5c4-dbe1fcac3083">

I'm seeing this behavior on both Edge and Chrome.

### Page URL

https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/tab-navigation

### Content source URL

https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/tabs/how-to/tab-navigation.md

### Author

@JoshuaPartlow

### Document Id

3e6d3496-cd0e-36a7-d262-978dbb95fe13

**Comment by Prasad-MSFT** [comment]
Hi @surbhigupta12 - Could you please help here updating the document as suggested?
