### ISSUE TITLE
Share to Teams in platform isn't functioning - either infinite loading or blocked

### ISSUE THREAD

**Issue by abduljabbarH** [MicrosoftDocs/msteams-docs#10942]
### Steps to reproduce

1. Embed the Share teams button to the web app
2. click on the button that opens the teams share
3. Infinitely loads with no results

### Expected behavior

The ability to share link

### Actual behavior

It infinitely loads with no results

or

when I clicked on the link to share via Teams I got a pop  up message to enter names but saw a brief message at the top saying “Redirect blocked” and when it gave me the full sharing screen it couldn’t find anyone I entered

![image](https://github.com/MicrosoftDocs/msteams-docs/assets/64799818/8b9be066-fd84-4cb0-bb2c-ddaaf297607a)

### Error details

[teams.microsoft.com-1716320383050.log](https://github.com/MicrosoftDocs/msteams-docs/files/15394769/teams.microsoft.com-1716320383050.log)

**Comment by Nivedipa-MSFT** [comment]
@abduljabbarH - The issue you're encountering with the "Redirect blocked" message when trying to share via Teams could be related to several factors, including browser settings, network configurations, or even the way the Teams app is handling redirects. 

Here are some steps and considerations that might help resolve the issue:
1. Check Browser Settings: Ensure that your browser allows pop-ups and redirects from the Teams app. Sometimes, browsers can block redirects as a security measure.

2. Cross-Origin Resource Sharing (CORS): The "Redirect blocked" message can also occur if CORS policies are not properly configured. The Teams app needs to be allowed to access resources from different origins during the authentication process.

3. Network Configuration: Verify that your network settings, including any firewalls or proxy servers, are not blocking the Teams app from functioning correctly.

4. App Permissions: Make sure that the Teams app has the necessary permissions to perform redirects and access the required resources.

5. Update Teams App: Ensure that you're using the latest version of the Teams app, as updates often include fixes for known issues.
