### ISSUE TITLE
Share to teams web app doesnt work

### ISSUE THREAD

**Issue by abduljabbarH** [MicrosoftDocs/msteams-docs#10941]
### Steps to reproduce

Embed share to teams button in an Angular application following the steps outlined in this doc [https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/share-to-teams-from-web-apps](url) 

### Expected behavior

teams button should appear were div was inserted, where

### Actual behavior

Nothing happens script provided doesnt seem to work for angular/SPAs, I suspect the docs are wrong referencing another open issue [https://github.com/MicrosoftDocs/msteams-docs/issues/10586](url)

**Comment by Nivedipa-MSFT** [comment]
@abduljabbarH - Thanks for reporting your issue. We will test this and update you soon.

**Comment by Nivedipa-MSFT** [comment]
@abduljabbarH - We have tested this scenario at our end and its working.
We have created one angular application and added below script on web page as mentioned in [this](https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/share-to-teams-from-web-apps) doc.
`<script async defer src="https://teams.microsoft.com/share/launcher.js"></script>`

Please refer below demo gif.
![ShareToTeams](https://github.com/MicrosoftDocs/msteams-docs/assets/92150070/b3f9b480-18ab-4319-a1d6-576067fcd8fb)

Could you please inspect the webpage and check below script is loaded on your webpage or not?
`<script async defer src="https://teams.microsoft.com/share/launcher.js"></script>`

Please let us know if you are facing any further issue here?

**Comment by Nivedipa-MSFT** [comment]
@abduljabbarH - Could you please confirm whether your issue has been resolved or if you are still experiencing it?
