### ISSUE TITLE
Clarification on Deep Links Usage

### ISSUE THREAD

**Issue by Nivedipa-MSFT** [MicrosoftDocs/msteams-docs#10955]
### Type of issue

Other (describe below)

### Feedback

In this page it would be better to add a note stating that : 
Deep links in Microsoft Teams do not directly support creating a temporary tab or a popup. Deep links are primarily used for navigation within Teams and Teams apps.

### Page URL

https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links

### Content source URL

https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/build-and-test/deep-links.md

### Author

@surbhigupta

### Document Id

6b4203f0-2844-06c9-eaa3-9cc03e6f76c0

**Comment by Prasad-MSFT** [comment]
Hi @surbhigupta12 - Could you please help here updating the doc?
