### ISSUE TITLE
@Everyone mention is not supported with the bot in group chat

### ISSUE THREAD

**Issue by SubbaReddi** [MicrosoftDocs/msteams-docs#10968]
### Type of issue

Other (describe below)

### Feedback

@mention of user with the bot will work. But @Everyone mentioning is not supported with the bot. Please add note for the same.

### Page URL

https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/channel-and-group-conversations?tabs=dotnet#work-with-mentions

### Content source URL

https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md

### Author

@surbhigupta

### Document Id

f9877c67-43d2-78a5-dcf2-fd0ca4de2339

**Comment by ChetanSharma-msft** [comment]
Hello @surbhigupta12 - Please help to update the documentation.
