### ISSUE TITLE
"Prepare a Developer Tenant for testing" - Outdated or info missing

### ISSUE THREAD

**Issue by qneville** [MicrosoftDocs/msteams-docs#10978]
### Type of issue

Outdated article

### Feedback

Steps have been followed, but the Debug In Teams process still fails - see bottom of this issue.

In docs:
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/3282562/99465729-9b49-4866-9528-c3186b8be2e1)

Current:
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/3282562/2e919549-7a79-432b-a547-d21365fa0e62)

"Upload Custom Apps" App Setup Policy:
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/3282562/baf03362-408d-44d9-9486-47a67ddc150a)

Issue from MS Teams:
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/3282562/8d72fddc-a777-49f5-aaf1-a34f994651d9)

### Page URL

https://learn.microsoft.com/en-us/microsoftteams/platform/m365-apps/prerequisites

### Content source URL

https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/m365-apps/prerequisites.md

### Author

@erikadoyle

### Document Id

5e17314b-09a2-197f-da9e-3a50697c182e

**Comment by Prasad-MSFT** [comment]
@qneville - Thanks for raising your issue. We will check this at our end and will update you accordingly.

**Comment by Prasad-MSFT** [comment]
Hi @surbhigupta12 - We also observed same behaviour. Could you please help here?

**Comment by qneville** [comment]
@Prasad-MSFT @surbhigupta12 This was down to my user's assigned Setup Policy and my misunderstanding of how setup policies worked. After assigning my user the correct role with "Custom App Uploads" enabled, things worked more-or-less as expected.

The screenshots in the documentation may just need an update, but I have troubleshooted the issue on my end.

Thank you for the quick acknowledgement on this.
