### ISSUE TITLE
If external users are members of group chat, messaging extension flyout will not be displayed

### ISSUE THREAD

**Issue by SubbaReddi** [MicrosoftDocs/msteams-docs#10983]
### Type of issue

Missing information

### Feedback

If external users are members of group chat, messaging extension flyout is not displaying. It is an expected behavior.
As this information is not available in documentation, please add the same.

### Page URL

https://learn.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/what-are-messaging-extensions?tabs=desktop

### Content source URL

https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/messaging-extensions/what-are-messaging-extensions.md

### Author

@surbhigupta

### Document Id

d5c2d24a-def4-af2e-7983-c73cf7f22934

**Comment by Prasad-MSFT** [comment]
Hi @surbhigupta12, please help here to update the document as described above.

**Comment by julesvirallinen** [comment]
Is this expected behaviour? We have a reporting extension that is crucial to work in external chats, and noticed this behavior started appearing earlier this month. We cannot find any documentation or changelogs on this, or how to fix them dissapearing.
