### ISSUE TITLE
[Document Update Request] How to deploy a Bot developed with Teams Toolkit (5.x) to a self-managed server or Host bot on-premises?

### ISSUE THREAD

**Issue by ChetanSharma-msft** [MicrosoftDocs/msteams-docs#10988]
### Type of issue

Typo

### Feedback

There are multiple request from developers like how to deploy a Bot developed with Teams Toolkit (5.x) to a **self-managed server** or Host bot **on-premises**?

Developers issues:
https://techcommunity.microsoft.com/t5/teams-developer/how-to-deploy-a-bot-developed-with-teams-toolkit-5-x-to-a-self/m-p/3870356#M8050

https://stackoverflow.com/questions/78270265/host-bot-on-premise-bot-needs-to-communicate-with-another-program

Please help to check and update the documentation.

### Page URL

https://learn.microsoft.com/en-us/microsoftteams/platform/toolkit/deploy#deploy-teams-apps-using-teams-toolkit

### Content source URL

https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/deploy.md

### Author

@MuyangAmigo

### Document Id

24348657-f892-77bc-a995-2de777c21c1b

**Comment by Prasad-MSFT** [comment]
Thanks for raising this. We will check this internally with engineering team and will update accordingly

**Comment by Prasad-MSFT** [comment]
The bot registration is required for all Teams bots. To use bot on onpremises-server you need to register a bot with type "multi tenant" or "single tenant", please check this doc [Create an Azure Bot resource in the Azure portal - Bot Service | Microsoft Learn](https://learn.microsoft.com/en-us/azure/bot-service/abs-quickstart?view=azure-bot-service-4.0&tabs=multitenant).
