### ISSUE TITLE
Present now option is not displayed as expected

### ISSUE THREAD

**Issue by Mohammed-MSFT** [MicrosoftDocs/msteams-docs#10984]
### Type of issue

Feature doesn't work (bug)

### Feedback

Hi Team,
We have tested one scenario, Share to Teams from web apps as per the document after adding this property **data-allow-share-in-meeting="true"**  it doesn't seems to work as expected.

**Doc Link :** https://review.learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/share-to-teams-from-web-apps?branch=pr-en-us-10824&tabs=method-1

<img width="429" alt="image" src="https://github.com/MicrosoftDocs/msteams-docs/assets/109147706/65cc4107-811d-4cc4-a93b-bdb2bf3f8534">

<img width="530" alt="sharetoTeams" src="https://github.com/MicrosoftDocs/msteams-docs/assets/109147706/482eba93-50f2-4c58-90e2-63efa1ed76f0">

Kindly help on this issue/bug.

**Thanks!!**

### Page URL

https://review.learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/share-to-teams-from-web-apps?branch=pr-en-us-10824&tabs=method-1

### Content source URL

https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/build-and-test/share-to-teams-from-web-apps.md

### Author

@surbhigupta

### Document Id

9cb013cb-3a19-2142-5286-692ff9b32ea6

**Comment by Prasad-MSFT** [comment]
Thanks for raising your issue. We will check this internally with engineering team and will get back to you.

**Comment by Prasad-MSFT** [comment]
We got below update from engineering team
"This feature is only enabled in early rings now and not available in dev preview or prod for testing. We will hold-off on releasing the docs until the feature is available."
