### ISSUE TITLE
Code example language mismatch and Teams toolkit language mismatch. 

### ISSUE THREAD

**Issue by ggilmoreAtWork** [MicrosoftDocs/msteams-docs#10989]
### Type of issue

Other (describe below)

### Feedback

Regarding the section 'Use Azure AI Search index data source', it seems that the code is typescript and not javascript, although javascript is specified and typescript isn't even an option for this section of the page.  Seeing that the teams toolkit for VS Code requires Node.JS, which doesn't natively support typescript it really throws a wrench in folks trying to learn and implement these technologies as rapidly as one would like.  The teams producing the product and the learn documentation need to sync up, otherwise these are great examples and technologies - care and though was obviously put into the product. 

### Page URL

https://learn.microsoft.com/en-us/microsoftteams/platform/toolkit/build-a-rag-bot-in-teams?tabs=javascript%2Cjavascript1%2Cjavascript2%2Cjavascript4%2Cjavascript3

### Content source URL

https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/build-a-RAG-bot-in-teams.md

### Author

@surbhigupta

### Document Id

933feadd-483a-5562-81a3-38908b697a5a

**Comment by Nivedipa-MSFT** [comment]
@ggilmoreAtWork - Thanks for reporting your issue. We are checking this internally, we will update you soon.
