### ISSUE TITLE
This article is supposed to be about SSO for Teams Tabs but it's only addresses SSO for BOTs.  

### ISSUE THREAD

**Issue by appalliance** [MicrosoftDocs/msteams-docs#11024]
### Type of issue

Other (describe below)

### Feedback

This article is supposed to be about SSO for Teams Tabs but it's only addresses SSO for BOTs.  

### Page URL

https://learn.microsoft.com/en-us/microsoftteams/platform/sbs-tabs-and-messaging-extensions-with-sso?tabs=dev%2Cvs2019

### Content source URL

https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/sbs-tabs-and-messaging-extensions-with-sso.yml

### Author

@surbhigupta

### Document Id

7a0eb8f0-586e-b698-b21b-10cfb522de93

**Comment by Nivedipa-MSFT** [comment]
@appalliance - Thanks for reporting your issue. We are checking this internally, we will update you soon.
