### ISSUE TITLE
Custom Together Mode scenes shipped as apps

### ISSUE THREAD

**Issue by v-kushals** [MicrosoftDocs/msteams-docs#11020]
### Type of issue

Missing information

### Feedback

"A scene only app is created and you can view the app and app package.json file in **Apps** page in the Teams Developer Portal. A screen opens in your Teams to add the scene app created." - Are scenes shipped as apps? What app capabilities are used by scenes? Can these be managed as apps by admins?

### Page URL

https://learn.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/teams-together-mode

### Content source URL

https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/apps-in-teams-meetings/teams-together-mode.md

### Author

@surbhigupta

### Document Id

278c15ae-7d16-091a-8320-90b3e15aacfc

**Comment by Prasad-MSFT** [comment]
Hi @v-kushals - Scenes are not shipped as standalone apps but are part of scene-only apps within Teams. The app capabilities used by scenes are focused on creating immersive Together Mode scenes, and admins can manage the behavior of scene apps through app setup policies.

**Comment by v-kushals** [comment]
Thanks for clarifying, @Prasad-MSFT. We'll discuss this internally and revert about the update needed for documentation.
