### ISSUE TITLE
"Valid domain cannot use tunnel site" error again

### ISSUE THREAD

**Issue by uwekolsch** [MicrosoftDocs/msteams-docs#1102]
I get the same error as in the message from March 13 - "Valid domain cannot use tunnel site" - but  "sideloading of external app" is enabled. I tried the pro version of ngrok so that I can use a non ngrok URL, this got me around the error but now I have a invalid SSL cert and I can't use the http version. How do I get around this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33cdb816-f2b6-31a4-0e4c-d730435d0a6b
* Version Independent ID: c111eaef-ac66-e245-b2bc-623c1801a7db
* Content: [Get started with App Studio and Node.js - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/get-started/get-started-nodejs-app-studio?view=msteams-client-js-latest#feedback)
* Content Source: [msteams-platform/get-started/get-started-nodejs-app-studio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/get-started/get-started-nodejs-app-studio.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by clearab** [comment]
Hi - Is the message an error, or a warning? App Studio should still allow you to install the app for dev/test purposes.

**Comment by uwekolsch** [comment]
Seems to be a warning, because now I can ignore it and just install the app. But I'm pretty sure when I tried this last night it did not work, it never got me to the tab selector. Thanks for your quick response.
