### ISSUE TITLE
[Doc Bug] Wrongly mentioned submit/messageAction rather than message/submitAction

### ISSUE THREAD

**Issue by ChetanSharma-msft** [MicrosoftDocs/msteams-docs#11037]
### Type of issue

Typo

### Feedback

Kindly update below section with **message/submitAction**
https://review.learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/format-ai-bot-messages?branch=pr-en-us-10798&tabs=after%2Cbotmessage#error-handling-2

![image](https://github.com/MicrosoftDocs/msteams-docs/assets/59052547/561f7943-d677-41ff-9311-4ab464b9996c)

### Page URL

https://review.learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/format-ai-bot-messages?branch=pr-en-us-10798&tabs=after%2Cbotmessage

### Content source URL

https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/bots/how-to/format-ai-bot-messages.md

### Author

@surbhigupta

### Document Id

1de6f2d1-f7ee-b07c-fd5a-dc6661aa0696

**Comment by ChetanSharma-msft** [comment]
Hello @surbhigupta12 - Please help to update the documentation.

**Comment by v-ypalikila** [comment]
Updated submit/messageAction to message/submitAction as requested in PR #10798 .
