### ISSUE TITLE
Sensitivity label: Property table is confusing

### ISSUE THREAD

**Issue by ChetanSharma-msft** [MicrosoftDocs/msteams-docs#11039]
### Type of issue

Typo

### Feedback

Sensitivity label: Property table is confusing for **usageInfo.@id**
This is required only if we add sensitivity label to the citation.

So, we should have 2 tables based on two tabs (Bot Message & Citation)
With Bot Message code snippets, we need to show only usageInfo.@type, usageInfo.name, usageInfo.description & with Citation tab code snippets we can show usageInfo.@id as well:

![image](https://github.com/MicrosoftDocs/msteams-docs/assets/59052547/0b8ac3c2-718c-4c9a-8ee9-f586e49a685f)

https://review.learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/format-ai-bot-messages?branch=pr-en-us-10798&tabs=after%2Cbotmessage#add-sensitivity-label

### Page URL

https://review.learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/format-ai-bot-messages?branch=pr-en-us-10798&tabs=after%2Cbotmessage#add-sensitivity-label

### Content source URL

https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/bots/how-to/format-ai-bot-messages.md

### Author

@surbhigupta

### Document Id

1de6f2d1-f7ee-b07c-fd5a-dc6661aa0696

**Comment by Meghana-MSFT** [comment]
@surbhigupta12 - Could you please add a note to the
[usageinfo.@id](mailto:usageinfo.@id) field to say that "it's required only for citations within a message and not elsewhere".

https://review.learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/format-ai-bot-messages?branch=pr-en-us-10798&tabs=after%2Cbotmessage#add-sensitivity-label
