### ISSUE TITLE
Citation SDK methods value related limits are not mentioned in documentation. 

### ISSUE THREAD

**Issue by ChetanSharma-msft** [MicrosoftDocs/msteams-docs#11036]
### Type of issue

Typo

### Feedback

Citation SDK methods:

**• citation.position**
Please add a note in the documentation about the supported range of values. If we give more than ~9-10 digits, it's throwing below error: 
 
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/59052547/df4858bc-6592-4de1-9cf1-7c98a6d9d98d)

**• citation.appearance.abstract**
Please add a note in the documentation that how many characters are supported. If we give 1000 characters, we are getting below error:
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/59052547/d373ab1e-4cf3-4e19-b06a-7d6668881a8f)

**• citation.appearance.keywords** 
Please add a note in the documentation that how many keywords are supported.
Currently if we try more than 3 keywords it is giving us the error:
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/59052547/7de39fea-3740-44ee-b590-fd28bfc68993)

### Page URL

https://review.learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/format-ai-bot-messages?branch=pr-en-us-10798&tabs=after%2Cbotmessage

### Content source URL

https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/bots/how-to/format-ai-bot-messages.md

### Author

@surbhigupta

### Document Id

1de6f2d1-f7ee-b07c-fd5a-dc6661aa0696

**Comment by Dinesh-MSFT** [comment]
Hi, 
Thanks for raising the query.
We will look into it and let you know the updates.
