### ISSUE TITLE
Bot won't allow HeroCard in MessagingExtensionResponse

### ISSUE THREAD

**Issue by rich14au** [MicrosoftDocs/msteams-docs#11034]
### Steps to reproduce

I am trying to return a HeroCard from data collected in a messaging extension web view. 

```
MessagingExtensionActionResponse response = new MessagingExtensionActionResponse
{
	ComposeExtension = new MessagingExtensionResult
	{
		AttachmentLayout = "list",
		Type = "result",
	},
};

HeroCard card = new HeroCard
{
	Title = "Your task has been created!",
	Subtitle = taskDescription,
	Text = "The \"" + taskName + "\" was created",
};

List<MessagingExtensionAttachment> attachments = new List<MessagingExtensionAttachment>();
attachments.Add(new MessagingExtensionAttachment
{
	Content = card,
	ContentType = HeroCard.ContentType,
	Preview = card.ToAttachment(),
});
response.ComposeExtension.Attachments = attachments;

return response;
```

### Expected behavior

I expect the HeroCard to be placed into the compose message box for the user to submit it to the channel and for the message extension dialog to be closed. 

### Actual behavior

The bot is retuning the following error:

<BotError>Error when processing invoke response: Task or Task Type is missing in Task Module response

### Error details

<BotError>Error when processing invoke response: Task or Task Type is missing in Task Module response

**Comment by Nivedipa-MSFT** [comment]
@rich14au - Thanks for reporting your issue. We are checking this internally, we will update you soon.
