### ISSUE TITLE
Why are these templates not targeting .NET Core?

### ISSUE THREAD

**Issue by markthiessen** [MicrosoftDocs/msteams-docs#1104]
It seems strange that these examples are all targeting NET4x and using jQuery... is there a dependency issue or are these just out of date?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98cd21c7-e87c-3c5b-7574-998a355f9f08
* Version Independent ID: 5e312707-facc-03fc-af59-90267d0c7b8a
* Content: [Get started with C#/.NET - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/get-started/get-started-dotnet-app-studio)
* Content Source: [msteams-platform/get-started/get-started-dotnet-app-studio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/get-started/get-started-dotnet-app-studio.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by markthiessen** [comment]
Going down the internet rabbit holes to find useful info to get started and found https://stackoverflow.com/a/56174075/56128

Apparently 3.x doesn't support .NET Core, while 4.x does. But there's also no migration path for 3.x to 4.x so I'd like to start with 4.x so whatever I build isn't obsolete in a few months. Maybe this documentation should mention this and help people get started on the next version.

**Comment by clearab** [comment]
The 4.6 version of the Bot Framework SDK was just published today, with full 1st party support for Teams. Documentation and samples will be updated to reflect over the next few days - with additional sample and documentation support to follow.
