### ISSUE TITLE
Access to process.binding('http_parser') is deprecated

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#11059]
Copied bug from: https://github.com/OfficeDev/teams-toolkit/issues/11678 

**Details from original post:**
**Describe the bug**
Any link that is clicked inside the chat of the Development Toolkit team will cause the whole module to freeze and break with this error "Access to process.binding('http_parser') is deprecated". The whole application freezes.

**To Reproduce**
1. Run the teams tooklit to exceute the script. Make sure that the script produces a link inside the chat window.
2. Click on the click
3. This will freeze the whole window with an error message. 
Error Message: 
(node:2884) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)

**Expected behavior**
The link opens to a new tab and the application continues to function normally.

**VS Code Extension Information (please complete the following information):**
 - Version : 1.89.1
- Node.js: 18.18.2
- OS: Windows_NT x64 10.0.19045

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b743e43d-95cc-3d1e-b142-31a16369f97e
* Version Independent ID: b743e43d-95cc-3d1e-b142-31a16369f97e
* Content: [Teams Toolkit Overview - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/toolkit/teams-toolkit-fundamentals)
* Content Source: [msteams-platform/toolkit/teams-toolkit-fundamentals.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/teams-toolkit-fundamentals.md)
* Service: **msteams**
* GitHub Login: @zyxiaoyuer
* Microsoft Alias: **zhany**

**Comment by Dinesh-MSFT** [comment]
Hi, thanks for raising the query.
We will look into it and let you know the updates.

**Comment by Dinesh-MSFT** [comment]
Hi @Ashlytom,
Could you please share the exact repro steps along with the code. So, we look into it and let you know the updates.
