### ISSUE TITLE
Participants of the Channel are not able to join the Meeting

### ISSUE THREAD

**Issue by dhruvp29** [MicrosoftDocs/msteams-docs#1107]
I created an online meeting using graph API in my one of the channel in the Teams.

I am following the example given here. [Create Online Meeting in the channel of the team](https://github.com/paywuAtMicrosoft/microsoft-graph-docs/blob/paywu/3323-calling-onlinemeeting-update/api-reference/beta/api/application-post-onlinemeetings.md)

Below are the API request and its body.

Request: `https://graph.microsoft.com/beta/me/onlineMeetings/`

Body:

```
{
  "startDateTime":"2019-10-30T06:45:00Z",
  "endDateTime":"2019-10-30T06:50:00Z",
  "subject":"Test Meeting",
  "chatInfo": {
    "threadId":"19:b4d5de0853d945ccb6eaf691fc0caa74@thread.skype"
  },
  "accessLevel":"everyone"
}
```
The meeting is created successfully and it is also shown on the channel. However, users are not able to join the meeting by clicking on it as nothing happens when the user clicks on the meeting.

![OnlineMeeting](https://user-images.githubusercontent.com/18227071/67926528-3f9ad780-fbdc-11e9-8c4a-6815bb85d923.png)

Can anyone let me know what am I missing here?

**Comment by Trinetra-MSFT** [comment]
Could you please try to set your `AcceeLevel ` parameter to `SameEnterprise` and test the same?

**Comment by dhruvp29** [comment]
Hi @Trinetra-MSFT , Tried as per your feedback but still facing the same issue.

**Comment by Trinetra-MSFT** [comment]
@dhruvp29 , Thanks for trying out, We are looking into the issue.

**Comment by Gousia-MSFT** [comment]
@dhruvp29 Participants joining depends on the policy of the channel. Could you please tell us if it was a private channel or a public channel?
Also what was the message that was shown to the participant who was trying to join? Like were they in lobby?

**Comment by dhruvp29** [comment]
Hi @Gousia-MSFT  It is a public channel.
Participants are not getting any error messages. as they are not able to click the meeting. If we create any meeting from teams UI,  we are able to see the view meeting details option as per the below screenshot.
![MeetingDetailsOptionMissing](https://user-images.githubusercontent.com/18227071/70036191-44d3b380-15da-11ea-9349-039d2db0808f.png)

the above option is not available when the meeting is created using GRAPH API.

Kindly let me know if you require more information from my end.

**Comment by Gousia-MSFT** [comment]
@dhruvp29 This is a known client issue. You can only join such created meeting using the join url.

**Comment by dhruvp29** [comment]
@Gousia-MSFT Thanks for the update. Is there any API using which we can achieve the Meet Now functionality available in teams UI?
OR
we can initiate a call in teams channel?

**Comment by Trinetra-MSFT** [comment]
@dhruvp29 , You can use `meetNow `a MeetingType. Please see the request body here:

> POST https://graph.microsoft.com/beta/app/onlineMeetings

```
{
  "meetingType": "meetNow",
  "participants": {
    "organizer": {
      "identity": {
        "user": {
          "id": "[myUserId-Guid]"
        }
      }
    }
  },
  "subject": "MeetNow from Graph API"
}
```

From the response you can isolate easily the most important information

-  joinURL

Send that joinURl into participants you want to add into a meeting. But there is more in that meeting.

**Comment by dhruvp29** [comment]
@Trinetra-MSFT Thanks for the answer but, in my case, I do not want to send the meeting URL separate.
I want that, it should send the notification in the channel similarly it is being sent when we perform Meet Now using Teams UI.

**Comment by Trinetra-MSFT** [comment]
@dhruvp29 , Please take a look at [Create an online meeting in a Microsoft Teams Channel with a user token](https://docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&tabs=csharp#example-3-create-an-online-meeting-in-a-microsoft-teams-channel-with-a-user-token).

**Comment by dhruvp29** [comment]
@Trinetra-MSFT I am already using that API and getting the issue.
Please check the question again.
