### ISSUE TITLE
The "samplePrompts" property is not visible in Copilot despite being added in the manifest JSON (manifest schema v1.17)

### ISSUE THREAD

**Issue by PjPraveenkumar** [MicrosoftDocs/msteams-docs#11081]
### Type of issue

Feature doesn't work (bug)

### Feedback

The "samplePrompts" property is not visible in Copilot despite being added in the manifest JSON. It seems this feature is not yet GA'ed and is still in a preview state. It would be better to update the documentation to indicate that it is in preview and not generally available for users.

### Page URL

https://learn.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/high-quality-message-extension?tabs=tasks#sample-prompts

### Content source URL

https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/messaging-extensions/high-quality-message-extension.md

### Author

@v-preethah

### Document Id

1d9e7d3e-f334-2862-3e44-e4db9d1a4fb3

**Comment by Nivedipa-MSFT** [comment]
@PjPraveenkumar - Thanks for reporting your issue. We will test this and update you soon.

**Comment by ChetanSharma-msft** [comment]
Hello @surbhigupta12 - We have added `samplePrompts `& `samplePrompts.text` in composeExtensions.commands but looks like it is not visible in UI.
Could you please confirm if there are in Preview?
If yes, Can we remove or add a note in the documentation because it's not working?

**Comment by Wajeed-msft** [comment]
Thank you @PjPraveenkumar for taking time to report this problem. We have removed this from documentation to avoid confusion.
