### ISSUE TITLE
Tab Removal button still gets enabled after 5secs but from commit it the text was deleted, which means it should work now.  

### ISSUE THREAD

**Issue by aniketrai** [MicrosoftDocs/msteams-docs#11096]
### Steps to reproduce

The text was removed which says that Remove button will be enabled after 5 secs. Does this means this feature is implemented ?

If so, I am still facing the issue. I am making the button disable by `pages.config.setValidityState(false);` but still it gets enabled after 5 secs.

Commit - https://github.com/MicrosoftDocs/msteams-docs/pull/10538

### Expected behavior

If using `pages.config.setValidityState(false);` the remove button should not be enabled.

### Actual behavior

Remove button is still getting enabled after 5 secs

```[tasklist]
### Tasks
```

**Comment by Meghana-MSFT** [comment]
This issue is being tracked here https://github.com/OfficeDev/microsoft-teams-library-js/issues/2363. Please follow this thread for further updates. Thank you.

**Comment by Meghana-MSFT** [comment]
Closing this issue since it is a duplicate thread. Please reach out to us if you face any issue in future.
