### ISSUE TITLE
Article doesn't appear in the table of contents

### ISSUE THREAD

**Issue by Rick-Kirkham** [MicrosoftDocs/msteams-docs#11115]
### Type of issue

Other (describe below)

### Feedback

This article isn't in the table of contents for the Teams developer docs.

### Page URL

https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/using-fluid-msteam

### Content source URL

https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/tabs/how-to/using-fluid-msteam.md

### Author

@timtwang

### Document Id

3fb7e3be-90de-3611-a18d-ce9e024811d4

**Comment by Prasad-MSFT** [comment]
Hi @surbhigupta12 - Could you please help here?

**Comment by Rick-Kirkham** [comment]
@surbhigupta12 The linked PR adds a different article to the Table of Contents, not the article I reported in this Issue.
