### ISSUE TITLE
Make it clear that the user must have the app installed for the bot to be able to create a conversation with the user

### ISSUE THREAD

**Issue by aosolis** [MicrosoftDocs/msteams-docs#11125]
### Type of issue

Missing information

### Feedback

![image](https://github.com/MicrosoftDocs/msteams-docs/assets/767208/23326727-956a-477a-b53e-d888ada464f6)
aadObjectId only works if the user has the app installed. This must be clarified.

### Page URL

https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/send-proactive-messages?tabs=dotnet#create-the-conversation

### Content source URL

https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/bots/how-to/conversations/send-proactive-messages.md

### Author

@surbhigupta

### Document Id

8097fcbd-adcc-ce49-a378-426c65af9296

**Comment by Dinesh-MSFT** [comment]
Hi @aosolis - Thanks for raising the query.
We will look into it and let you know the updates.

**Comment by v-ramyas5** [comment]
Hi @aosolis!
Thanks for raising the query.

In the document, just before the sub-heading [Create the conversation](https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/send-proactive-messages?tabs=dotnet#create-the-conversation), we have added a detailed note on 'aadObjectId'.

Do you think repeating this information in 'Create the conversation' section will add more clarity? 
Kindly clarify.
Thanks in advance.

**Comment by v-ramyas5** [comment]
> Hi @aosolis! Thanks for raising the query.
> 
> In the document, just before the sub-heading [Create the conversation](https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/send-proactive-messages?tabs=dotnet#create-the-conversation), we have added a detailed note on 'aadObjectId'.
> 
> <img alt="aadObjectId" width="452" src="https://private-user-images.githubusercontent.com/168160268/347707780-f8e03405-ebca-45c8-b227-70ae70a4828d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExOTk4NzAsIm5iZiI6MTcyMTE5OTU3MCwicGF0aCI6Ii8xNjgxNjAyNjgvMzQ3NzA3NzgwLWY4ZTAzNDA1LWViY2EtNDVjOC1iMjI3LTcwYWU3MGE0ODI4ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxN1QwNjU5MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YjNlYTY3ZWMyZmFmOGY5MzNmNmNkMTI2Y2EzZGJlNDU4NGZiZjkyYzcyMDBkMWI3MjgzZTJkYzdhNjA0M2MxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Vw6LXmO43PV8XZSJeKnxsafkI7k7eQOy3_8UKQa85sE">
> Do you think repeating this information in 'Create the conversation' section will add more clarity? Kindly clarify. Thanks in advance.

Hi @aosolis,
Gentle reminder! We are waiting for your response on this.

**Comment by Dinesh-MSFT** [comment]
> Hi @aosolis! Thanks for raising the query.
> 
> In the document, just before the sub-heading [Create the conversation](https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/send-proactive-messages?tabs=dotnet#create-the-conversation), we have added a detailed note on 'aadObjectId'.
> 
> <img alt="aadObjectId" width="452" src="https://private-user-images.githubusercontent.com/168160268/347707780-f8e03405-ebca-45c8-b227-70ae70a4828d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyMzAyNDIsIm5iZiI6MTcyMTIyOTk0MiwicGF0aCI6Ii8xNjgxNjAyNjgvMzQ3NzA3NzgwLWY4ZTAzNDA1LWViY2EtNDVjOC1iMjI3LTcwYWU3MGE0ODI4ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxN1QxNTI1NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMGZmYTJiZjYxZTUwNjZkNjkyZjg1ODEyMWYwNzE5MzYwMzdjNzU0MjUxZDgyN2NhNTU3MGViMjJlYzZkYjk5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QPbTVaW-7LQFmxo0g3YyiHCLr6e2GKeLw2EE5hgrhgc">
> Do you think repeating this information in 'Create the conversation' section will add more clarity? Kindly clarify. Thanks in advance.

Hi @aosolis,
As discussed with the team. It is already mentioned in the document. Could please confirm whether it should repeat again in the document?

**Comment by ChetanSharma-msft** [comment]
> Hi @aosolis! Thanks for raising the query.
> 
> In the document, just before the sub-heading [Create the conversation](https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/send-proactive-messages?tabs=dotnet#create-the-conversation), we have added a detailed note on 'aadObjectId'.
> 
> <img alt="aadObjectId" width="452" src="https://private-user-images.githubusercontent.com/168160268/347707780-f8e03405-ebca-45c8-b227-70ae70a4828d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI3MTI4MzEsIm5iZiI6MTcyMjcxMjUzMSwicGF0aCI6Ii8xNjgxNjAyNjgvMzQ3NzA3NzgwLWY4ZTAzNDA1LWViY2EtNDVjOC1iMjI3LTcwYWU3MGE0ODI4ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwM1QxOTE1MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMmNkODEyNjkxZDZmMTQ4OGFjZGE0Yzc2NWRhOGNmYWM5OGEzNGRkYjUzMjIwMzRlYTZlMGIxMDMzYjViZTkyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.RZOdvnFa8DWFwt4W81A3MrqV8Sz08MidGMPSdfSK_hQ">
> Do you think repeating this information in 'Create the conversation' section will add more clarity? Kindly clarify. Thanks in advance.

@v-ramyas5 - This is already documented, so let's close this issue.

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, please feel free to reopen it, if required.
