### ISSUE TITLE
Login loop when device time is off in Microsoft Teams Web

### ISSUE THREAD

**Issue by nlenlited** [MicrosoftDocs/msteams-docs#1115]
**What should happen:**
Microsoft teams to sign in OR state it cannot sign the user in because of a date/time difference.

**What happens now:**
The login is retried a bunch of times and it will simply state "Cannot sign you in" without valid reasoning.

**Steps to reproduce:**
- Log out any Teams , Office365 and/or services using a Microsoft Account or Office365 login.
- You can optionally clear your cookies and cache to ensure you are forced to login again.
- Set back the date/time of the device you're using by 1 hour. (  You may have to disable auto date/time in your OS before you are able to set it manually)
- Try to login into teams with any teams.microsoft.com address to your choosing.

**Comment by Gousia-MSFT** [comment]
@nlenlited Could you please share a video recording of the issue?

**Comment by Gousia-MSFT** [comment]
Please re-open with requested information.

**Comment by nlenlited** [comment]
@Gousia-MSFT : I'm not sure why I have to create a screen recording if you have to re-create the issue anyways.. (to verify it).. but here you go;

https://youtu.be/GwKaI84gytk

Please re-open.
