### ISSUE TITLE
`threadId` is required, but documentation indicates it is optional

### ISSUE THREAD

**Issue by erinha** [MicrosoftDocs/msteams-docs#11169]
### Type of issue

Typo

### Feedback

This section on the page describes `threadId` as optional, however the teams-js API requires that parameter be specified. 
https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/open-content-in-stageview?tabs=withchat#invoke-from-stageview-api

https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/open-content-in-stageview?tabs=withchat#stageview-api-parameters

Here 's the reference documentation: 
https://learn.microsoft.com/en-us/javascript/api/%40microsoft/teams-js/stageview.stageviewparams?view=msteams-client-js-latest

Which matches the code:
https://github.com/OfficeDev/microsoft-teams-library-js/blob/20bcabb512ae75e25e88bd76ea478adbfd1fa149/packages/teams-js/src/public/stageView.ts#L35

### Page URL

https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/open-content-in-stageview?tabs=withchat

### Content source URL

https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/tabs/open-content-in-stageview.md

### Author

@Rajeshwari-v

### Document Id

7b685a2e-18e0-a401-e44f-905a47d2415d

**Comment by Dinesh-MSFT** [comment]
Hi @erinha - Thanks for raising the query.
We will look into it and let you know the updates.
