### ISSUE TITLE
Error when uploading the app to teams

### ISSUE THREAD

**Issue by lre871** [MicrosoftDocs/msteams-docs#1116]
I've followed this steps but if i want to upload the app to teams i get an error message that this was not successful but there is no reason why. gulp serve works fine, the settings and permissions are correctly set. I did not change anything in the code. Could somebody help me please, i could not debug this without the reason for why it is not working. The error message is: "Es ist ein Fehler aufgetreten, bitte versuchen Sie es später erneut." (We use a german tenant)

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 42e0cad5-f762-c253-7d3b-b23ae3cb5b1c
* Version Independent ID: f1babe27-cbc7-f757-11b4-fc8fa1e36873
* Content: [Get started with the Yeoman generator for Microsoft Teams - Teams](https://docs.microsoft.com/de-de/microsoftteams/platform/tutorials/get-started-yeoman#feedback)
* Content Source: [msteams-platform/tutorials/get-started-yeoman.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tutorials/get-started-yeoman.md)
* Product: **msteams**
* GitHub Login: @clearab
* Microsoft Alias: **anclear**

**Comment by Trinetra-MSFT** [comment]
Could you please try to [sideload](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/apps-upload) your app manifest in teams?

**Comment by lre871** [comment]
Thanks for your answer. I've already tried this out but if i add it to a team i get the message that something went wrong. Adding it to Teams instead of an existing team works, but this is not what i need.

**Comment by Trinetra-MSFT** [comment]
This issue arises when sideloading is not enabled for your tenant. Do you see Upload a custom app for admin user or a normal user? Please share your app manifest so we can test it on our end.

**Comment by lre871** [comment]
Sideloading should be enabled... i did this with the global admin.
I dont know how to share this file so i paste it here (i changed my name and the name of the app, tab and bot):
{
  "$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.5/MicrosoftTeams.schema.json",
  "manifestVersion": "1.5",
  "id": "4a0c8f50-fedf-11e9-b5f0-bdd2e31dc28b",
  "version": "0.0.1",
  "packageName": "teamsnc",
  "developer": {
    "name": "LR",
    "websiteUrl": "https://{{HOSTNAME}}",
    "privacyUrl": "https://{{HOSTNAME}}/privacy.html",
    "termsOfUseUrl": "https://{{HOSTNAME}}/tou.html"
  },
  "name": {
    "short": "Teams_nc",
    "full": "Teams_nc"
  },
  "description": {
    "short": "TODO: add short description here",
    "full": "TODO: add full description here"
  },
  "icons": {
    "outline": "icon-outline.png",
    "color": "icon-color.png"
  },
  "accentColor": "#D85028",
  "configurableTabs": [
    {
      "configurationUrl": "https://{{HOSTNAME}}/ncTab/config.html",
      "canUpdateConfiguration": true,
      "scopes": [
        "team"
      ]
    }
  ],
  "staticTabs": [],
  "bots": [
    {
      "botId": "553377f2-1cbb-400c-b3e9-e656577c55e4",
      "needsChannelSelector": true,
      "isNotificationOnly": false,
      "scopes": [
        "team",
        "personal"
      ],
      "commandLists": [
        {
          "scopes": [
            "team",
            "personal"
          ],
          "commands": [
            {
              "title": "Help",
              "description": "Shows help information"
            }
          ]
        }
      ]
    }
  ],
  "connectors": [],
  "composeExtensions": [
    {
      "botId": "553377f2-1cbb-400c-b3e9-e656577c55e4",
      "canUpdateConfiguration": false,
      "commands": [
        {
          "id": "ncMeMessageExtension",
          "title": "nc ME",
          "description": "Add a clever description here",
          "initialRun": true,
          "parameters": [
            {
              "name": "parameter",
              "description": "Description of the parameter",
              "title": "Parameter"
            }
          ],
          "type": "query"
        }
      ]
    }
  ],
  "permissions": [
    "identity",
    "messageTeamMembers"
  ],
  "validDomains": [
    "{{HOSTNAME}}"
  ]
}

**Comment by Trinetra-MSFT** [comment]
@lre871 , Thanks for sharing the manifest, We are looking into it.

**Comment by lre871** [comment]
Thank you!

**Comment by Trinetra-MSFT** [comment]
@Ire871, We tried to sideload your manifest in teams, it working fine. Could you please confirm your host, is it local ngrok or any other domain? Please make sure you are adding your site domain inside the validDomain list of your manifest. 

**Note**: If you have enabled sideloading for your tenant recently please wait for some time, it usually take 7-8 hours to reflect the changes.

**Comment by lre871** [comment]
the host is ngrok (local) and i have enabled sideloading a view weeks ago. If i understood right, sideloading means loading the app to the store? this works fine. only adding it to the team does not work.

**Comment by Trinetra-MSFT** [comment]
@lre871 , Please confirm few things, 
1. Did you added Microsoft Teams channel while creating your bot ?
![image](https://user-images.githubusercontent.com/50989436/68139312-f0440680-ff4f-11e9-9959-996bb62c37b4.png).

2. Is your Bot working in web chat emulator?

**Comment by Trinetra-MSFT** [comment]
@Ire871, Please try to create a new bot [Create a Bot](https://dev.botframework.com/bots/new) and let me know if you still face this issue. It seems your bot is not listening on port.

**Comment by Gousia-MSFT** [comment]
Please re-open if you still face any issues.

**Comment by lsweeney2018** [comment]
I have the same error. Can't upload to Teams. Are there any variables that we have to enter in the env file? You mentioned adding the domain above "Please make sure you are adding your site domain inside the validDomain list of your manifest." Can you give instructions on this please.
I have validated the manifest in Teams and it has passed

**Comment by Minxpinx** [comment]
I have the same error. Can't upload to Teams. Are there any variables that we have to enter in the env file? You mentioned adding the domain above "Please make sure you are adding your site domain inside the validDomain list of your manifest." Can you give instructions on this please.
I have validated the manifest in Teams and it has passed
