### ISSUE TITLE
This page simply references an external page

### ISSUE THREAD

**Issue by MuyangAmigo** [MicrosoftDocs/msteams-docs#11175]
### Type of issue

Other (describe below)

### Feedback

This page simply references an external page, wouldn't it be better to move the external content inside directly?

### Page URL

https://learn.microsoft.com/en-us/microsoftteams/platform/toolkit/add-single-sign-on

### Content source URL

https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/add-single-sign-on.md

### Author

@surbhigupta

### Document Id

5555cc27-dbfc-72da-e12d-f73dec786c5d

**Comment by Prasad-MSFT** [comment]
[MuyangAmigo](https://github.com/MuyangAmigo), thanks for sharing your feedback

Hi @surbhigupta12, could you please here?
