### ISSUE TITLE
Activity feed notification cannot be synchronized in M365 or outlook 

### ISSUE THREAD

**Issue by RubyLiang24** [MicrosoftDocs/msteams-docs#11183]
### Steps to reproduce

We are working on the scenario to extend the activity feed notification functionality to our app use the activity feed notification APIs in Microsoft Graph. However, at present, users are only receiving notifications in the Teams Activity section whenever they have a new task. Unfortunately, these notifications do not appear in either Microsoft 365 or Outlook.

### Expected behavior

We would like to verify whether it's expected that our expanded activity feed notification is exclusive to the Teams App or if it's supposed to work across platforms including Microsoft 365 and Outlook.

### Actual behavior

Current implementation to extend the activity feed notification is only working in Teams App but not in M365 or outlook.

**Comment by Nivedipa-MSFT** [comment]
@RubyLiang24 - Thanks for reporting your issue. We will check and update you soon.

**Comment by Nivedipa-MSFT** [comment]
@RubyLiang24 - Activity feed notifications are exclusive to the Teams App, they are not supported to work across platforms, including Microsoft 365 and Outlook.
