### ISSUE TITLE
Set the "initialRun" property to "true" for search commands in Messaging Extension (Copilot) to enable the OAuth sign-in link in the plugin section

### ISSUE THREAD

**Issue by PjPraveenkumar** [MicrosoftDocs/msteams-docs#11199]
### Type of issue

Missing information

### Feedback

For Messaging Extension (Copilot plugin) oAuth, user will see a "sign-in" text just below the appInfo (as shown below)
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/161592567/61ab32c8-c4ab-464f-866e-002fb5f37aa6)

For AAD SSO, auth will happen silently and user will only see "Sign in" text if consent is needed or SSO fails for any reason.

To trigger the sign-in popup upon enabling the plugin (or) display the sign-in link next to the plugin name, developers need to set the 'initialRun' property to 'true' for search commands in the manifest in order to enable the OAuth sign-in link in the plugin section. However, this detail is not mentioned anywhere in the documentation. Could you please verify and update the document accordingly.

### Page URL

https://learn.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/high-quality-message-extension?tabs=tasks

### Content source URL

https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/messaging-extensions/high-quality-message-extension.md

### Author

@v-preethah

### Document Id

1d9e7d3e-f334-2862-3e44-e4db9d1a4fb3

**Comment by Prasad-MSFT** [comment]
@PjPraveenkumar - Thanks for sharing your valuable input.
Hi @surbhigupta12, could you please help here to document this?

**Comment by ChetanSharma-msft** [comment]
Hello @PjPraveenkumar,
We had tested the Message Extension with SSO with initialRun property with "false" value:

1) After enabling ME plugin and posting any prompt, we will get one card with button "Sign in to <App Name>"
![10 sso-login-page](https://github.com/user-attachments/assets/30213013-0051-4eaa-87c8-ad9856d8a650)

2) Once we click on button, it will open auth popup like below:
![12 copilot-auth](https://github.com/user-attachments/assets/80c172e4-f2a3-4f9b-ab72-74e54a2e1d19)

3) After successful login we can ask any prompt and app will work smoothly which asking Auth from next time onwards (Silent Auth)

![13 multi-param](https://github.com/user-attachments/assets/d5fa8c47-1888-4210-b19e-8cde6bf38e1f)


Reference Sample link: https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/msgext-expert-finder-js

So, we can add both behavior:
1) initialRun = true
2) initialRun = false

@surbhigupta12 - Please help to add these both behavior.
