### ISSUE TITLE
[A11y - Adaptive Card]High contrast theme and OS High contrast themes(Aquatic) are enabled, some UI colors are modified and on mouse hovering color difference observed

### ISSUE THREAD

**Issue by sherryzhao11** [MicrosoftDocs/msteams-docs#11209]
### Steps to reproduce

Adaptive card JSON
{
    "type": "AdaptiveCard",
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.5",
    "body": [
        {
            "type": "ActionSet",
            "actions": [
                {
                    "type": "Action.OpenUrl",
                    "title": "Action.OpenUrl"
                },
                {
                    "type": "Action.OpenUrl",
                    "title": "Action.OpenUrl"
                }
            ]
        }

https://github.com/MicrosoftDocs/msteams-docs/assets/132635147/5471c7d7-6e2e-48b0-8211-3af47b026fdf

    ]
}
Steps:
When set the theme to High contrast, some UI colors are modified and on mouse hovering color difference observed as the recording 

### Expected behavior

The Button's color is excepted to be changed in high contrast.

### Actual behavior

The Button's style is not changed as show in recording.

**Comment by Prasad-MSFT** [comment]
Thanks for raising your issue. We will check this at our end and will update you accordingly.

**Comment by Prasad-MSFT** [comment]
@sherryzhao11 - We have this below setting in Microsoft Teams version 24183.2200.2972.8859. The client version is 49/24053101421.
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/62237649/f812b68b-110e-424e-ad50-207dfe99c55b)

and on mouse hovering buttons the button colors are displaying as below:
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/62237649/975e3d76-6176-4aa7-be2d-62e7771d8d11)
