### ISSUE TITLE
[A11y Adaptive Card] Focus on the card is slightly cut off in the edges

### ISSUE THREAD

**Issue by sherryzhao11** [MicrosoftDocs/msteams-docs#11210]
### Steps to reproduce

Adaptive Card JSON 
{
    "type": "AdaptiveCard",
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.5",
    "body": [
        {
            "type": "ActionSet",
            "actions": [
                {
                    "type": "Action.OpenUrl",
                    "title": "Action.OpenUrl"
                },
                {
                    "type": "Action.OpenUrl",
                    "title": "Action.OpenUrl"
                }
            ]
        }
    ]
}
Steps:
Focus on the card is slightly cut off in the edges.

### Expected behavior

Focus on the card is slightly cut off in the edges.

### Actual behavior

Card should have clear focus covering the UI completely. Focus should not be cut off.
![Focus cut off](https://github.com/MicrosoftDocs/msteams-docs/assets/132635147/2c4215fb-62ab-4d44-bf26-f0ecc8889afe)
![Focus on the card is slightly cut off in the edges](https://github.com/MicrosoftDocs/msteams-docs/assets/132635147/3d4f7984-fd2b-4378-9c27-a6ad0d326fda)

**Comment by Meghana-MSFT** [comment]
Thank you for reporting this, we will check this and get back to you.

**Comment by Meghana-MSFT** [comment]
@sherryzhao11 - We checked this at our end and we are not able to repro this, we see the focus is even on all sides. 
We checked this in both Teams web(1415/24061318408) and Desktop(24187.501.2981.3768) client.
Could you please share more details which would help us in getting the repro. Thank you.

![image](https://github.com/MicrosoftDocs/msteams-docs/assets/81138249/c4de6f64-516a-4278-8125-d23314113d50)
