### ISSUE TITLE
Web hook feature deprecation in Teams

### ISSUE THREAD

**Issue by benark** [MicrosoftDocs/msteams-docs#11225]
### Type of issue

Outdated article

### Feedback

This entire feature is being removed in July-August 2024.
See: https://devblogs.microsoft.com/microsoft365dev/retirement-of-office-365-connectors-within-microsoft-teams

### Page URL

https://learn.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-using?tabs=cURL%2Ctext1

### Content source URL

https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/webhooks-and-connectors/how-to/connectors-using.md

### Author

@laujan

### Document Id

8a250e46-2a30-af86-839d-9f83a8b48041

**Comment by Prasad-MSFT** [comment]
Hi @benark , thanks for raising this. Could you please let us know what we need to update [here](https://learn.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-using?tabs=cURL%2Ctext1)? Do you want us to remove the entire page?

**Comment by benark** [comment]
I suggest you reach out to the PM for Teams and figure it out with them. I don't feel it's my place as a customer to suggest how Microsoft updates its documentation when they remove features.

From the blog post I linked to, it appears the correct person to answer this question is Connor Rodewald, Senior Product Manager, Microsoft Teams.

**Comment by Prasad-MSFT** [comment]
Hi @surbhigupta12 - Could you please help here updating the documentation?

**Comment by bbenouarets** [comment]
If other system administrators are having difficulties locating the affected teams:
I have written a small tool in Golang that uses the Graph API to output the affected teams.

[Teams Webhook Finder](https://github.com/SecNex/teams-webhook-finder)

This has helped us enormously, as Microsoft does not offer its own solution for reading the affected channels and teams. We have over 350 teams in our company, which we would otherwise have had to search through manually.

**Comment by ChetanSharma-msft** [comment]
Hello Everyone,

Microsoft has extended the retirement timeline through December 2025 to provide ample time to migrate to another solution such as Power Automate, an app within Microsoft Teams, or Microsoft Graph.
Please refer this post: https://devblogs.microsoft.com/microsoft365dev/retirement-of-office-365-connectors-within-microsoft-teams/

**Note:** We would suggest to user **workflows** in place of Office 365 connectors.

Thanks!!

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, please feel free to reopen it, if required.
