### ISSUE TITLE
Problem connecting to teams, reconnecting

### ISSUE THREAD

**Issue by ewquon** [MicrosoftDocs/msteams-docs#1122]
I'm having regular connection issues in Teams. Even with the app open, messages will push to my phone instead. There is an error message displayed at the top of the window, and I need to click on that to restart teams before new messages appear in the app. This happens daily.

I'm running OS X High Sierra.

**Comment by Trinetra-MSFT** [comment]
Could you please share some screenshot for what error you are getting?

**Comment by ewquon** [comment]
![image](https://user-images.githubusercontent.com/18267059/68420410-88610c00-0159-11ea-81b3-5bddfa18a725.png)
Clicking "refresh now" restarts Teams.

**Comment by ewquon** [comment]
> ![image](https://user-images.githubusercontent.com/18267059/68420410-88610c00-0159-11ea-81b3-5bddfa18a725.png)
> Clicking "refresh now" restarts Teams.

Note that I am connected to the internet at this point, and no other applications on my laptop are experiencing any connectivity problems.

**Comment by Trinetra-MSFT** [comment]
@ewquon, Are you still facing this issue? Can you provide som log files from the time the issue appears?

**Comment by ewquon** [comment]
Where can I find the relevant log files?

**Comment by Gousia-MSFT** [comment]
@ewquon You could get the logs by pressing Ctrl+Alt+Shift+1 with Teams app in focus.

**Comment by Gousia-MSFT** [comment]
Please re-open with requested information if you are still facing this issue.

**Comment by ewquon** [comment]
This issue still persists and requires a "refresh" (i.e. Teams restart) to fix. 

Log was saved after restarting the app, with command+option+shift+1 on Mac:
[MSTeams Diagnostics Log 12_3_2019__9_02_14_AM_chatListData.txt](https://github.com/MicrosoftDocs/msteams-docs/files/3917519/MSTeams.Diagnostics.Log.12_3_2019__9_02_14_AM_chatListData.txt)

**Comment by ewquon** [comment]
Problem persists. If I try to save a log (with command+option+shift+1, as before) before clicking "Refresh now", it doesn't work (no file is saved to ~/Downloads).
