### ISSUE TITLE
Incoming Webhook not working with AdaptiveCard

### ISSUE THREAD

**Issue by miguelc1221** [MicrosoftDocs/msteams-docs#11222]
### Steps to reproduce

Hi, not sure if this is a bug but incoming webhook is not working with adaptivecard (It works fine with MessageCard). I created an incoming webhook using the connector (I know it will be deprecated soon). Instead it is returning ```"AdaptiveCards.AdaptiveSerializationException: Property 'type' must be 'AdaptiveCard'"``` . Here is what my request looks like 

``` 
    const formatted_Card_Payload = {
        type: 'message',
        attachments: [
            {
                contentType: 'application/vnd.microsoft.card.adaptive',
                contentUrl: null,
                content: {
                    $schema:
                        'http://adaptivecards.io/schemas/adaptive-card.json',
                    type: 'AdaptiveCard',
                    version: '1.6',
                    body: [
                        {
                            type: 'TextBlock',
                            text: 'Submitted response',
                        },
                    ],
                },
            },
        ],
    };

    axios
        .post(options.webhookUrl, formatted_Card_Payload, {
            headers: { 'content-type': 'application/json' },
        })
        .then(function (response) {
            console.log(response);
        })
        .catch(function (error) {
            console.log(error);
        });
```

### Expected behavior

Should send an AdaptiveCard to channel

### Actual behavior

It's not sending an AdaptiveCard and instead returning an error message.

### Error details

```"AdaptiveCards.AdaptiveSerializationException: Property 'type' must be 'AdaptiveCard'"```

**Comment by Prasad-MSFT** [comment]
Hi @miguelc1221 - Could you please try sending the same JSON using POSTMAN or cURL and verify if that works or not? We tried sending the below JSON using POSTMAN and it worked fine.
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/62237649/4e4c8fa3-610d-4f4e-9d71-5be64f9003fa)

```
{
       "type":"message",
       "attachments":[
          {
             "contentType":"application/vnd.microsoft.card.adaptive",
             "contentUrl":null,
             "content":{
                "$schema":"http://adaptivecards.io/schemas/adaptive-card.json",
                "type":"AdaptiveCard",
                "version":"1.2",
                "body":[
                    {
                    "type": "TextBlock",
                    "text": "Submitted response"
                    }
                ]
             }
          }
       ]
    }
```

**Comment by miguelc1221** [comment]
@Prasad-MSFT Hey, I get the same error when using postman, only MessageCards work. I followed these docs to create a webhook https://learn.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-incoming-webhook?tabs=newteams%2Cdotnet. Any idea if it's possible my org has any settings not allowing this? The error message doesn't make sense if that is the case.

**Comment by Prasad-MSFT** [comment]
@miguelc1221 - This is quite strange as this works perfectly fine at our end. Also, could you please let us know if this issue is specific to this particular card JSON or is it happening with any card JSON?

**Comment by miguelc1221** [comment]
@Prasad-MSFT It happens with any AdaptiveCard Json, only works with MessageCards

**Comment by hachi1030-Allen** [comment]
Hi @Prasad-MSFT 

I encountered the same issue here.

When using Adaptive Card json, it shows that the type must be AdaptiveCard, and I changed it from "messaage" to "AdaptiveCard", and it will pop up error like there must be Summary or Text, things like that.

I was using a python script to send this post request to my incoming webhook, and it also reproduce with the REST API tools like Postman, etc.

I have changed to MessageCards but I got this warning all the time.

![image](https://github.com/MicrosoftDocs/msteams-docs/assets/32292089/f1720b51-bbc3-4f3e-8706-4255c5dcdd9d)

Thanks!

**Comment by Prasad-MSFT** [comment]
@hachi1030-Allen , this entire feature is being removed in July-August 2024.
See: https://devblogs.microsoft.com/microsoft365dev/retirement-of-office-365-connectors-within-microsoft-teams

**Comment by hachi1030-Allen** [comment]
Hi @Prasad-MSFT , so you meant that the incoming webhook will be removed totally from Teams connector is that correct?

Thanks,
Allen

**Comment by Prasad-MSFT** [comment]
None of connector will work after 1st of October. You can still use current connectors until that date. Until 15th of August there is possibility to create new connectors.

**Comment by Prasad-MSFT** [comment]
**Update:**
Microsoft has extended the retirement timeline through December 2025 to provide ample time to migrate to another solution such as Power Automate, an app within Microsoft Teams, or Microsoft Graph.
https://devblogs.microsoft.com/microsoft365dev/retirement-of-office-365-connectors-within-microsoft-teams/

**Comment by ChetanSharma-msft** [comment]
Hello Everyone,

I could see the differences in Adaptive Card version part:
We have tried with "version":"1.2" and you all are trying with "version":"1.6"
Please test once with 1. version.

You can also refer this sample:
https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/incoming-webhook/nodejs
