### ISSUE TITLE
Teams Tab app error while performing SSO

### ISSUE THREAD

**Issue by Vishnuvybhav** [MicrosoftDocs/msteams-docs#11235]
### Type of issue

Feature doesn't work (bug)

### Feedback

i have enabled SSO for my teams tab app but i am facing this error saying CAA20004 
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/123458279/0e68ebdb-9b87-4c9c-9a86-2bc33417f7b1)

### Page URL

https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/tab-sso-manifest

### Content source URL

https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/tabs/how-to/authentication/tab-sso-manifest.md

### Author

@surbhigupta

### Document Id

39428da3-d8be-43eb-80df-2b1f26ef6524

**Comment by Vishnuvybhav** [comment]
Got it

**Comment by Dinesh-MSFT** [comment]
Hi @Vishnuvybhav - Thanks for raising the query.
We will look into it and let you know the updates.
