### ISSUE TITLE
Outdated docs (deprecated webhook functionality)

### ISSUE THREAD

**Issue by alex-jitbit** [MicrosoftDocs/msteams-docs#11244]
### Steps to reproduce

This page https://learn.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-incoming-webhook?tabs=newteams%2Cdotnet describes how to create a web hook in a channel. However once you do that, you immediately get an error message that Webhook are being deprecated since August 2024!! The docs mention nothing about this, and what ARE the correct steps to create webhooks now?

### Expected behavior

Should describe the new method of setting up a webhook, not the deprecated one

### Actual behavior

Described outdated way.

**Comment by alex-jitbit** [comment]
What's even worse is there's no adequate docs on how to send a webhook for the new "workflows" way, what is the JSON format etc

**Comment by Prasad-MSFT** [comment]
Thanks for providing your valuable feedback. This below blog post describes Why are we retiring Office 365 connectors? and How do I transition from Office 365 connectors to Workflows?.
https://devblogs.microsoft.com/microsoft365dev/retirement-of-office-365-connectors-within-microsoft-teams/


We are checking internally with documentation team to update the documentation.

**Comment by alex-jitbit** [comment]
@Prasad-MSFT thanks I already found the updated docs, but it would be great if you add an info-panel saying this is being deprecated with a link to the new docs which is here by the way: https://aka.ms/TeamsWebhookConnector

**Comment by Prasad-MSFT** [comment]
Hi @surbhigupta12 , please help here to update the doc as suggested.

**Comment by surbhigupta12** [comment]
@Prasad-MSFT, please do not close this issue.

**Comment by ChetanSharma-msft** [comment]
Hello Everyone,

Microsoft has extended the retirement timeline through December 2025 to provide ample time to migrate to another solution such as Power Automate, an app within Microsoft Teams, or Microsoft Graph.
Please refer this post: https://devblogs.microsoft.com/microsoft365dev/retirement-of-office-365-connectors-within-microsoft-teams/

**Note:** We would suggest to user **workflows** in place of Office 365 connectors.
Document is also updated:
https://learn.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-incoming-webhook?tabs=newteams%2Cdotnet

Thanks!!

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, please feel free to reopen it, if required.

**Comment by ChetanSharma-msft** [comment]
Hello @surbhigupta12, @v-npaladugu,
We have updated the note in the documentation at all the places except "Create Outgoing Weebhooks":

![image](https://github.com/user-attachments/assets/20eb3d2f-4ddc-402a-a3f4-50e47fb56de9)

Could you please check and update it as well?
