### ISSUE TITLE
Bullet point formatting breaking between desktop and mobile teams

### ISSUE THREAD

**Issue by Alexees** [MicrosoftDocs/msteams-docs#1124]
I've written a fairly long list using bullet points in the desktop Teams client. Later on, I wanted to add another entry to that list from my mobile device.
First of all, pressing return for next line did not add another bullet point, but even worse, when I just added the text I wanted without it, it removed all bullet points.
I realized that a day later looking at that same list from the desktop client again, it completely lost it's bullet point formatting.
This also results in smileys being rendered large even though inlined. You need to re-type them.

**Comment by Gousia-MSFT** [comment]
@Alexees Could you please share some screenshots of the issue you are seeing on mobile?

**Comment by Alexees** [comment]
Sure:
This is the screenshot of a message I wrote on Desktop:
![image](https://user-images.githubusercontent.com/32508825/68368578-a9653500-0138-11ea-81ab-d1db360c0721.png)

This is how the message looks when viewed on mobile:
![image](https://user-images.githubusercontent.com/32508825/68368852-2db7b800-0139-11ea-9fbe-fa9f6eed323a.png)

And this is how it looks when I edit the message on mobile, simply add a new line text and submit it:
![image](https://user-images.githubusercontent.com/32508825/68368896-4922c300-0139-11ea-8e58-018267664eed.png)

**Comment by Gousia-MSFT** [comment]
@Alexees Thanks for sharing the screenshot!! We are looking into this.

**Comment by Gousia-MSFT** [comment]
@Alexees Are you seeing in this in both Android and iOS?

**Comment by Alexees** [comment]
> @Alexees Are you seeing this in both Android and iOS?

I do not own an iOS device

**Comment by Gousia-MSFT** [comment]
@Alexees Ok. We have raised a bug for this and we are tracking it internally.

**Comment by Gousia-MSFT** [comment]
This is resolved now. Please check.
