### ISSUE TITLE
Can't add Connector Incoming Webhook

### ISSUE THREAD

**Issue by anateotonio** [MicrosoftDocs/msteams-docs#11266]
### Steps to reproduce

I was following this tutorial to add the Incoming Webhook connector: https://learn.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-incoming-webhook?tabs=newteams%2Cdotnet#create-an-incoming-webhook 

1. Select a channel within a team
2. Select the three dots > manage 
3. Conectors > Edit 
4. Search for incoming webhook
5. Add > Add again
When click on add for the second time, it goes back to the search page and does not add the connector.

![image](https://github.com/user-attachments/assets/eeba287c-12a0-4cd7-998d-e30efaa3df28)

### Expected behavior

Add the connector

### Actual behavior

When click on add for the second time, it goes back to the search page and does not add the connector.

**Comment by Prasad-MSFT** [comment]
@anateotonio, thanks for raising your issue. We are also able to repro this in Microsoft Teams version 24187.501.2981.3768. The client version is 49/24053101421.
![image](https://github.com/user-attachments/assets/1c190019-77bc-406c-bdfa-691e71d5058d)

We are checking this with engineering team and after confirmation will raise bug accordingly.

**Comment by Prasad-MSFT** [comment]
Hi @anateotonio - O365 Connectors Substrate team is aware of this issue and there is an ICM raised to fix this. Once this is fixed, we will notify you in this thread. Thanks!

**Comment by dorukgunes** [comment]
Hi @Prasad-MSFT any updates on this issue ?

**Comment by Prasad-MSFT** [comment]
Hi @anateotonio , @dorukgunes , could you please share your respective tenant Ids where you are facing this issue, so that we can share those details with engineering team to fix ?

**Comment by Prasad-MSFT** [comment]
According to latest update from engineering team, you can start using teams web to create Incoming Webhook & RSS connectors. However, the fix for Teams Desktop client is under investigation.

**Comment by Prasad-MSFT** [comment]
According to latest update from engineering team, the bug has been fixed in both Teams web and desktop client. Thanks!
