### ISSUE TITLE
no metion of "Retirement of Office 365 connectors within Microsoft Teams"

### ISSUE THREAD

**Issue by martens-d** [MicrosoftDocs/msteams-docs#11275]
### Type of issue

Outdated article

### Feedback

With this article [https://devblogs.microsoft.com/microsoft365dev/retirement-of-office-365-connectors-within-microsoft-teams/]("Retirement of Office 365 connectors within Microsoft Teams") MS tells that webhooks won't work from the 1. Oct. any more.

So any further development here is fruitless. 

**SO MENTION IT EVERYWHERE MS.**

### Page URL

https://learn.microsoft.com/en-us/microsoftteams/platform/sbs-outgoing-webhooks?tabs=dev

### Content source URL

https://learn.microsoft.com/en-us/microsoftteams/platform/sbs-outgoing-webhooks?tabs=dev

### Author

?

### Document Id

?

**Comment by Prasad-MSFT** [comment]
Thanks @martens-d for raising your issue.
Hi @surbhigupta12 , could you please help here to add that message/note in documentation wherever necessary.

**Comment by Prasad-MSFT** [comment]
**Update:** Microsoft has extended the retirement timeline through December 2025 to provide ample time to migrate to another solution such as Power Automate, an app within Microsoft Teams, or Microsoft Graph.
https://devblogs.microsoft.com/microsoft365dev/retirement-of-office-365-connectors-within-microsoft-teams/

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, please feel free to reopen it, if required.
