### ISSUE TITLE
How to get list of third party apps that are developed by Microsoft

### ISSUE THREAD

**Issue by KurupatiC** [MicrosoftDocs/msteams-docs#11271]
### Type of issue

Typo

### Feedback

In teams admin center ,few apps are listed under third party apps but those apps are developed by Microsoft, 
For example, Incoming Webhooks, Github --these are developed by Microsoft, but they are classified as 3rd party app.

### Page URL

https://learn.microsoft.com/en-us/microsoftteams/apps-in-teams

### Content source URL

https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/apps-in-teams.md

### Author

@surbhigupta

### Document Id

4bbe9beb-233f-cfd5-097b-f280aab5fde8

**Comment by Nivedipa-MSFT** [comment]
@KurupatiC - Thanks for reporting your issue. We will check and update you soon.

**Comment by ashishguptaiitb** [comment]
Thanks for sharing this issue @KurupatiC . Appreciated. To address this, I want to further understand the use case. Do you want to govern apps collectively using org-wide app setting controls? Do you want to evaluate and then allow the apps based on who the developer is? Or some other use case.

If it helps, I'm sharing this info upfront (without knowing your use case). Wherever the admin center says control Microsoft-provided apps, those controls will impact only the apps that are listed at https://learn.microsoft.com/en-us/microsoftteams/apps-in-teams#list-of-apps-created-by-microsoft. 

It'll really help to know the follow-up action that you want to take to manage your apps better. Thanks in advance.

**Comment by SubbaReddi** [comment]
@ashishguptaiitb : Even app management cannot done using Org-wide app settings, customer can change the app availability under manage apps. 
To allow or restrict specific apps, customer would like to understand what are Microsoft developed apps and other. So, categorizing third party apps which are microsoft developed apps in documentation will help.
Let us know, if you need any further details.
