### ISSUE TITLE
Wiki Content went missing

### ISSUE THREAD

**Issue by tjnicolas** [MicrosoftDocs/msteams-docs#1127]
Our wiki page and section are still accessible but have empty content after we edit it. There is no deletion happened. Please help. Thank you.

**Comment by Gousia-MSFT** [comment]
@tjnicolas Could you please elaborate more on the issue you are facing? From how long are you seeing this issue?

**Comment by tjnicolas** [comment]
I just experienced it yesterday.

Suddenly, all contents of 1 section went missing.

Is there a chance I can retrieve the wiki content?

**Comment by Gousia-MSFT** [comment]
@tjnicolas I am checking this internally. Will get back to you on this. Thanks!

**Comment by tjnicolas** [comment]
OK Thanks. Just in case, I have the wikiMetadata that you can reference if necessary.

**Comment by Gousia-MSFT** [comment]
@tjnicolas If the content was ever saved before being lost, maybe it is possible to recover the raw content from the eDiscovery portal. It is saved as a html there, so some of the formating might be lost, but that is an option to explore. Could you please check if this can help?
