### ISSUE TITLE
Adaptive Card Response Requirements listed twice

### ISSUE THREAD

**Issue by alexisconia** [MicrosoftDocs/msteams-docs#11288]
### Type of issue

Typo

### Feedback

The last three requirements in paragraph "Adaptive Card Response" are listed twice :
![image](https://github.com/user-attachments/assets/6a32b5a5-34cd-43c0-a0cb-26d468ea80fc)

### Page URL

https://learn.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/high-quality-message-extension?context=%2Fmicrosoft-365-copilot%2Fextensibility%2Fcontext&tabs=tasks#compound-utterances

### Content source URL

https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/messaging-extensions/high-quality-message-extension.md

### Author

@v-preethah

### Document Id

1d9e7d3e-f334-2862-3e44-e4db9d1a4fb3

**Comment by Meghana-MSFT** [comment]
@alexisconia - Thank you for reporting this, we will get the doc updated.

@surbhigupta12 - Could you please help to remove the sentences that are mentioned twice in the "Adaptive Card Response".

https://learn.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/high-quality-message-extension?context=%2Fmicrosoft-365-copilot%2Fextensibility%2Fcontext&tabs=tasks#adaptive-card-response
