### ISSUE TITLE
documented method for creating webhooks in teams channels is no longer available in latest build earlier than depreciation schedule

### ISSUE THREAD

**Issue by MikeBakerSAV** [MicrosoftDocs/msteams-docs#11291]
### Type of issue

Outdated article

### Feedback

documented method for creating webhooks in teams channels is no longer available in latest build earlier than depreciation schedule

### Page URL

https://learn.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-incoming-webhook?tabs=newteams%2Cdotnet

### Content source URL

https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/webhooks-and-connectors/how-to/add-incoming-webhook.md

### Author

@surbhigupta

### Document Id

e3b53e27-2946-189c-623b-9df704ea8f12

**Comment by Prasad-MSFT** [comment]
Hi @MikeBakerSAV , thanks for raising your query. Could you please let us know in which Microsoft Teams version you are encountering the issue?

We checked in `Microsoft Teams version 24204.1200.3011.3935. The client version is 49/24061318413` and are able to configure following the steps.
![image](https://github.com/user-attachments/assets/01a10e81-cdaa-4560-9527-951e89162665)

**Comment by MikeBakerSAV** [comment]
You have Microsoft Teams version 24180.205.2980.1757.
You've got the latest version. It was last checked on 24/07/2024.
The client version is 49/24062724811.

Mike Baker|Head of Technology
+44 20 3435 7646
www.savannah-energy.com
________________________________

**Comment by MikeBakerSAV** [comment]
You have Microsoft Teams version 24180.205.2980.1757.
You've got the latest version. It was last checked on 24/07/2024.
The client version is 49/24062724811.

**Comment by Prasad-MSFT** [comment]
@MikeBakerSAV , could you please try upgrading the version and see if that works?
This is the link to downgrade or upgrade. But its for Windows only
[Older versions of Microsoft Teams (Windows) | Uptodown](https://microsoft-teams.en.uptodown.com/windows/versions)

**Comment by MikeBakerSAV** [comment]
No as that's not an official repo and i'm already on early access release - 24180 is latest target release

Mike Baker|Head of Technology
+44 20 3435 7646
www.savannah-energy.com
________________________________

**Comment by Prasad-MSFT** [comment]
We understand your concern.  We will inform this to engineering team internally and once we get any further update, we will notify you in this thread.

**Comment by Prasad-MSFT** [comment]
@MikeBakerSAV , could you please share the tenant is where you are facing the issue?

**Comment by MikeBakerSAV** [comment]
Again- not leaving the tenant ID in a public portal

**Comment by Prasad-MSFT** [comment]
> Again- not leaving the tenant ID in a public portal

@MikeBakerSAV , you can share via DevCommResponseTeam@microsoft.com
