### ISSUE TITLE
[FAQ Page][App validation]

### ISSUE THREAD

**Issue by surbhigupta12** [MicrosoftDocs/msteams-docs#11317]
### Type of issue

Outdated article

### Feedback

Need to check the App validation section. Update branding for MPN

### Page URL

https://learn.microsoft.com/en-us/microsoftteams/platform/teams-faq

### Content source URL

https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/teams-faq.md

### Author

@surbhigupta

### Document Id

4aa620a9-03b4-a34e-49c9-5c6b024428d0

**Comment by Nivedipa-MSFT** [comment]
@surbhigupta12 - Could you please help here?
