### ISSUE TITLE
Messaging extension created using yo generator works fine with ngrok but fails when deployed in teams.

### ISSUE THREAD

**Issue by MaheshakaMudli** [MicrosoftDocs/msteams-docs#1132]
I have created a messaging extension using yo generator which uses a task module to accept user data. I have created a web app bot and tested it in emulator and web chat as well. The bot works fine. I have installed the bot in teams as well and it is working fine. I have tested the messaging extension using ngrok server and it works fine. But when I package the solution and upload the package in teams I get below error.
![image](https://user-images.githubusercontent.com/23700986/68532583-19e0a180-0345-11ea-95fa-5e0ed4267b67.png)

and in console log this is recorded.
![image](https://user-images.githubusercontent.com/23700986/68532594-3f6dab00-0345-11ea-9d73-679a54707ae2.png)

If I deploy card in messaging extension, it works fine but not for the task module.
Is there any other configuration which needs to be done as I believe the error is because the messaging extension is not able to connect to bot.

**Comment by clearab** [comment]
If you are using a web content page for your task module, you need to add your domain to the 'validDomains' portion of you app manifest.

**Comment by MaheshakaMudli** [comment]
@clearab we tried adding my domain in valid domains section in app settings but still it did not work. we have created a simple echo bot and used it in extension. Seeing at the error it seems as if some code is required in bot which we is missing. In the task module we have created a user form and fetching some data from graph using msal.

**Comment by EricDahlvang** [comment]
It looks like the console log above shows a NotImplemented exception.

Have you tried this sample: https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/javascript_nodejs/54.teams-task-module

**Comment by MaheshakaMudli** [comment]
Finally got it working. We were using two different web app, one for the bot and the other for the solution which is why the code was not able to communicate with the bot. Moved the code in the same web app of the bot and working like a charm.
