### ISSUE TITLE
OAuth cards

### ISSUE THREAD

**Issue by v-kydela** [MicrosoftDocs/msteams-docs#1134]
Can you provide some clarity about whether OAuth cards are supported in Teams using the Bot Framework? The Bot Builder SDK contains [code](https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder.Dialogs/Prompts/OAuthPrompt.cs#L284) that suggests OAuth cards are not supported in Teams:

```c#
private static bool ChannelSupportsOAuthCard(string channelId)
{
    switch (channelId)
    {
        case Channels.Msteams:
        case Channels.Cortana:
        case Channels.Skype:
        case Channels.Skypeforbusiness:
            return false;
    }

    return true;
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Cards Reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference#signin-card)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @clearab
* Microsoft Alias: **anclear**

**Comment by Trinetra-MSFT** [comment]
@v-kydela ,There are currently some restrictions to where you can use the OAuthCard. 
    1. The card will not work with guest access.
    2. It will not work with Microsoft Teams free.
    3. It can only be used for bot authentication.
    4. It only works for bots registered in the Azure Bot Service.

Please take a look at [OAuth Card](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference#oauth-card) for more information

**Comment by v-kydela** [comment]
@Trinetra-MSFT - Yes, I can see those restrictions. The documentation still says OAuth cards are supported with the Bot Framework, yet the source code prevents the use of OAuth cards with Teams

**Comment by EricDahlvang** [comment]
**This is a documentation bug.**  Teams supports the OAuthPrompt, but only because the OAuthPrompt uses a SignIn card IF the channel is Teams: 
see: https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder.Dialogs/Prompts/OAuthPrompt.cs#L315

and 

https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder.Dialogs/Prompts/OAuthPrompt.cs#L284

This has been tested, and also verified with Jeff Derstadt in person.  Teams does not, and will not, support OAuthCard.

**Comment by clearab** [comment]
The documentation should be update shortly, our apologies for the confusion.
