### ISSUE TITLE
Need to add graph rsc helper sample

### ISSUE THREAD

**Issue by Pawank-MSFT** [MicrosoftDocs/msteams-docs#11370]
### Type of issue

Other (describe below)

### Feedback

Please add the sample (https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/graph-rsc-helper/nodeJs) in this document.

### Page URL

https://learn.microsoft.com/en-us/microsoftteams/platform/graph-api/rsc/grant-resource-specific-consent#code-sample

### Content source URL

https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/graph-api/rsc/grant-resource-specific-consent.md

### Author

@surbhigupta

### Document Id

366710c7-9697-afc3-7b1d-792d741fb9dc

**Comment by ChetanSharma-msft** [comment]
Hello @surbhigupta12 - Please help to update the sample link in the documentation.
