### ISSUE TITLE
Add the new C# sample to this document

### ISSUE THREAD

**Issue by Harikrishnan-MSFT** [MicrosoftDocs/msteams-docs#11408]
### Type of issue

Typo

### Feedback

Hi Team,

We have created a new sample. Could you please include the sample in this document.

**Sample Link -** 
     https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/v-hrajandira/tab-meeting-auto-recording/samples/tab-meeting-auto-recording/csharp 

### Page URL

https://learn.microsoft.com/en-us/microsoftteams/platform/graph-api/meeting-transcripts/fetch-id

### Content source URL

https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/graph-api/meeting-transcripts/fetch-id.md

### Author

@surbhigupta

### Document Id

d22ab715-65ae-1f44-00a4-4f37c3a81d36

**Comment by Meghana-MSFT** [comment]
@surbhigupta12 - Could you please help to add the following sample https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/v-hrajandira/tab-meeting-auto-recording/samples/tab-meeting-auto-recording/csharp here -

https://learn.microsoft.com/en-us/microsoftteams/platform/graph-api/meeting-transcripts/fetch-id#code-samples
