### ISSUE TITLE
Does Azure Bot's Tenant (Azure AD) need to be the same Tenant with Teams (O365) to enable Teams Bot Calling?

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#11419]
### Discussed in https://github.com/MicrosoftDocs/msteams-docs/discussions/8659

<div type='discussions-op-text'>

<sup>Originally posted by **namnam0610** May 18, 2023</sup>
Hi all,
After reading the Teams bot calling and meeting document. I am wondering if we can use 2 different tenants (one for hosting the Azure Bot and Azure websites that host the web hook url, and one for the O365 Tenant that MS Teams relies on) or not?</div>

**Comment by Prasad-MSFT** [comment]
Yes, it is possible to use two different tenants for hosting the Azure Bot and Azure websites that host the webhook URL, and for the O365 Tenant that Microsoft Teams relies on. This setup can be achieved by configuring your bot as a multi-tenant bot. 
1. https://learn.microsoft.com/en-us/microsoftteams/platform/bots/calls-and-meetings/registering-calling-bot
2. https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/bot-calling-meeting/csharp#register-azure-ad-application
