### ISSUE TITLE
How to send adaptive card directly into chat as a message from bot in a message extension.

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#11418]
### Discussed in https://github.com/MicrosoftDocs/msteams-docs/discussions/8879

<div type='discussions-op-text'>

<sup>Originally posted by **sn-007** June 19, 2023</sup>
Hey, I am working on an action-based messaging extension app for teams. My action can be invoked from a message. After submitting the action, currently the adaptive card I am sending is getting inserted into the chat and the user must manually click on send.

I want the message to be directly inserted into the chat. [Microsoft documentation](https://learn.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/action-commands/define-action-command#select-how-the-final-message-is-sent ) says, 

"_If the message extension is invoked from the compose box or directly from a message, your web service can insert the final response directly into the channel or chat. In this case, the Adaptive Card comes from the bot, the bot updates it, and replies to the conversation thread if needed. You must add the bot object to the app manifest using the same ID and defining the appropriate scopes._"

But I have no idea how to do this. Yes, we will add the bot to manifest, what next? Currently, I am returning my adaptive card using the following code : 

```
    async function executeActions(context, action) {
    const data = action.data;
    const flaskData = await postFlaskData("/jstack", data);
    const adaptiveCard = createAdaptiveCardJstack(flaskData, "Jstack");
    
    const attachment = {
      contentType: adaptiveCard.contentType,
      content: adaptiveCard.content,
      preview: adaptiveCard,
    };
    
    return {
      composeExtension: {
        type: "result",
        attachmentLayout: "list",
        attachments: [attachment],
      }
    };
  
  };
  
  ```
  
  
  In this code "executesActions" is a action that will be called from the handleMessagingExtensionSubmitAction like this:
  
  ```
  async handleTeamsMessagingExtensionSubmitAction(context, action) {
    switch (action.commandId) {
      case "executeActions":
        return await executeActions(context, action);
      default:
        throw new Error("NotImplemented");
    }
  }
```
  
Could someone please help how can I tweak the codes, to send messages into the chat directly?  So that, the user should not have to click on send every time. I don't mind if the message comes from a bot, into the chat.

I am thinking of something like context.sendActivity(), but not sure how to use this.

Thanks for you time.</div>

**Comment by sayali-MSFT** [comment]
@sn-007
Thanks for reporting your issue.
We will check this at our end and will get back to you.

**Comment by sayali-MSFT** [comment]
@sn-007-Here is a sample of how to send the card directly to a channel without using the compose box and sending manually:

[Sample Code](https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/7762f98e78a2bec214e826a871dac0fc0e31cf87/samples/msgext-action-preview/nodejs/bots/teamsMessagingExtensionsActionPreviewBot.js#L34)
