### ISSUE TITLE
executeDeepLink joins wrong meeting

### ISSUE THREAD

**Issue by sharmajnu** [MicrosoftDocs/msteams-docs#1142]
We had a scenario where we had two meetings at same time with same name. The first meeting is cancelled and when we call executeDeepLink  with second meeting url it joins the first cancelled meeting.

Note: If I open the url directly on browser I am joining the correct meeting (second meeting). this issue is only happening with executeDeepLink .

**Comment by Subhasish-msft** [comment]
Are you getting same join URL for both meetings? And are you using same channel for creating both meetings?

**Comment by sharmajnu** [comment]
Same channel was used to create the meeting, and we were getting join on the first cancelled meeting in teams, not in the second actual meeting.

**Comment by Subhasish-msft** [comment]
Can you please share some screenshots of the cancelled meeting and how you are executing the meeting URL

**Comment by Subhasish-msft** [comment]
@sharmajnu, We have raised a bug for this and we are tracking it internally.
