### ISSUE TITLE
Add doc to explain format of webhook URLs

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#11422]
### Discussed in https://github.com/MicrosoftDocs/msteams-docs/discussions/6452

<div type='discussions-op-text'>

<sup>Originally posted by **wroth** July 14, 2022</sup>
It would be very helpful to describe the format, syntax, and meaning of the various parts of the webhook URL.

In particular, I noticed that if I create a webhook URL for a specific MS Teams channel... when other people look at the same webhook in the same channel, the last part of the URL is different for each person.  (Part after the last forward-slash.)

It would be useful to know why that is.

(See https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-incoming-webhook)</div>

**Comment by Prasad-MSFT** [comment]
@wroth, when you create a webhook for a specific MS Teams channel, the last part of the URL (Part after the last forward-slash) denotes the AAD Object ID of that particular user.
