### ISSUE TITLE
Need to update sample

### ISSUE THREAD

**Issue by Pawank-MSFT** [MicrosoftDocs/msteams-docs#11423]
### Type of issue

Missing information

### Feedback

This sample steps little change, we have update readme, Please update the sample steps based on given Readme.
https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/main/samples/meetings-sidepanel/csharp/README.md

### Page URL

https://learn.microsoft.com/en-us/microsoftteams/platform/sbs-meetings-sidepanel?tabs=dev%2Cvs&source=docs

### Content source URL

https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/sbs-meetings-sidepanel.yml

### Author

@surbhigupta

### Document Id

c1a955d5-85bc-7efd-c991-c705cf18d0b0

**Comment by Prasad-MSFT** [comment]
Hi @surbhigupta12, could you please help here to update [this](https://learn.microsoft.com/en-us/microsoftteams/platform/sbs-meetings-sidepanel?tabs=dev%2Cvs&source=docs) SBS guide based on below sample README?
https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/main/samples/meetings-sidepanel/csharp/README.md
