### ISSUE TITLE
Universal Actions for Adaptive Cards - Action.Execute in Teams and Outlook?

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#11420]
### Discussed in https://github.com/MicrosoftDocs/msteams-docs/discussions/8445

<div type='discussions-op-text'>

<sup>Originally posted by **brianpmccullough** April  6, 2023</sup>
"You can now send the same card to both, Teams and Outlook, and keep them in sync with each other using the underlying bot. Any action taken on either platform is reflected to the other with this build once, deploy anywhere (Universal Actions for Adaptive Cards) model." - is there a sample/walkthrough/blog that shows you can use the SAME card in both Teams and Outlook to capture data from a user as outlined in the "Universal Actions for Adaptive Cards" article: https://github.com/MicrosoftDocs/msteams-docs/blob/f70fe776245e04b89703c9e60621b95134e05380/msteams-platform/task-modules-and-cards/cards/Universal-actions-for-adaptive-cards/Overview.md

As far as I can tell/test, it looks like it's still only possible to use Action.Http within Outlook?</div>

**Comment by Prasad-MSFT** [comment]
@brianpmccullough, Before the Universal Actions for Adaptive Cards, different hosts provided different action models as follows:

- Teams or bots used Action.Submit, an approach which defers the actual communication model to the underlying channel.
- Outlook used Action.Http to communicate with the backend service explicitly specified in the Adaptive Card payload.

With the Universal Actions for Adaptive Cards, you can use `Action.Execute` for action handling across different platforms. `Action.Execute` works across all hubs, including Teams and Outlook.
