### ISSUE TITLE
presence subscription created but never fired

### ISSUE THREAD

**Issue by CodeABao** [MicrosoftDocs/msteams-docs#11452]
### Steps to reproduce

graph api
`var subscription = new Subscription
{
    ChangeType = "updated",
    NotificationUrl = presenceSection["NotificationUrl"],
    IncludeResourceData = true,
    Resource = resource,
    EncryptionCertificate = Convert.ToBase64String(x509Certificate.Export(X509ContentType.Cert)),
    EncryptionCertificateId = "PresencePublic",
    ExpirationDateTime = DateTimeOffset.UtcNow.AddMilliseconds(submilliseconds),
    ClientState = "presencesfromsubscription",
    LatestSupportedTlsVersion = "v1_2"
};`

### Expected behavior

NotificationUrl  will recive the users presence  data

### Actual behavior

not response

### Error details

the subscription program built one year ago, it works well , until 2024-08-11T06:10:13+08:00

**Comment by Nivedipa-MSFT** [comment]
@CodeABao - Thanks for reporting your issue. We will check and update you soon.

**Comment by CodeABao** [comment]
> @CodeABao - Thanks for reporting your issue. We will check and update you soon.

thanks,

**Comment by Nivedipa-MSFT** [comment]
@CodeABao - Could you please check if your subscription has expired?

**Comment by CodeABao** [comment]
> @CodeABao - Could you please check if your subscription has expired?

I renew the subscription every minute.  so it is not expired. it works well untill last sunday.

**Comment by CodeABao** [comment]
auto recovery.

**Comment by Nivedipa-MSFT** [comment]
@CodeABao - Could you please share your valuable feedback via [Microsoft Teams Developer Community Response Feedback](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR7iCOpS5_b9Nqmwx43u5rtZUOThVR081SllSR05aSDQxQ0tUMDVPTVIxTi4u) link?
