### ISSUE TITLE
Access to process.binding('http_parser') is deprecated

### ISSUE THREAD

**Issue by ChetanSharma-msft** [MicrosoftDocs/msteams-docs#11464]
### Steps to reproduce

Copied bug from: https://github.com/OfficeDev/teams-toolkit/issues/11678

**Details from original post:
Describe the bug**

Describe the bug
Any link that is clicked inside the chat of the Development Toolkit team will cause the whole module to freeze and break with this error "Access to process.binding('http_parser') is deprecated". The whole application freezes.

To Reproduce

Run the teams tooklit to exceute the script. Make sure that the script produces a link inside the chat window.
Click on the click
This will freeze the whole window with an error message.
Error Message:
(node:2884) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.
(Use node --trace-deprecation ... to show where the warning was created)
/
/

### Expected behavior

The link opens to a new tab and the application continues to function normally.

VS Code Extension Information (please complete the following information):

Version : 1.89.1
Node.js: 18.18.2
OS: Windows_NT x64 10.0.19045

### Actual behavior

NA

**Comment by Nivedipa-MSFT** [comment]
@ashlytom - Could you please share the repro steps for how you are running the script and which exact script you are running?
Have your written any code and developing Teams app?

**Comment by cavalier67** [comment]
I am showing this same error when running this in debug mode:  https://learn.microsoft.com/en-us/microsoftteams/platform/sbs-gs-msgext?tabs=vscode%2Cvsc1%2Cvsc2%2Cmsgext%2Cvsc3%2Cvsc4

**Comment by Nivedipa-MSFT** [comment]
@cavalier67 - Version compatibility could be the issue. Could you please downgrade node JS version and check again?

**Comment by Nivedipa-MSFT** [comment]
@cavalier67 - Have you downgraded the Node.js version and checked?
