### ISSUE TITLE
How to add linting to your Teams Bot?

### ISSUE THREAD

**Issue by ChetanSharma-msft** [MicrosoftDocs/msteams-docs#11463]
### Steps to reproduce

Copied bug from: https://github.com/OfficeDev/teams-toolkit/issues/11727

**Details from original post:
Describe the bug**

Discussed in https://github.com/OfficeDev/teams-toolkit/discussions/11674
Originally posted by IAM5K May 21, 2024
We are creating a bot and based on our company coding standard it is mandatory that we implement coding standards or linting in our project what is the standard plugin package or linter that we use for linting bot framework applications.

I have already tried using eslint and prettier but they have some conflicts and package issues.
I found using mslint in a repository but lost it. Is there some guideline that we use to add coding standards and checks (linting) to our bot project.

### Expected behavior

NA

### Actual behavior

NA

**Comment by Prasad-MSFT** [comment]
This issue was tracked here: https://github.com/MicrosoftDocs/msteams-docs/issues/11058
