### ISSUE TITLE
Documentation for add Application Insights to Command bot or bot in general

### ISSUE THREAD

**Issue by ChetanSharma-msft** [MicrosoftDocs/msteams-docs#11460]
### Steps to reproduce

Copied bug from: https://github.com/OfficeDev/teams-toolkit/issues/12223

**Details from original post:
Describe the bug**
Is your feature request related to a problem? Please describe.
Unable to find documentation how to enable log level in command bot. How to enable Application Insights for bot app.

Describe the solution you'd like
Please provide some information how to enable

Describe alternatives you've considered
Add documentation for telemetry

### Expected behavior

Add documentation for telemetry

### Actual behavior

Unable to find documentation how to enable log level in command bot. How to enable Application Insights for bot app.

**Comment by Prasad-MSFT** [comment]
@NWH-SAmin5, thanks for your feedback. We are checking the issue and will get back to you shortly.
