### ISSUE TITLE
Documentation issues: Hresult error and Multi-Project Launch Profiles

### ISSUE THREAD

**Issue by NCW-Alithya** [MicrosoftDocs/msteams-docs#11474]
### Type of issue

Missing information

### Feedback

Couple things missing in the Visual Studio instructions that caused problems: 

- When creating the project, the instructions should mention to uncheck "**Place solution and project in the same directory.**" Not doing this will result in an error, "Hresult 0x80070003" and the project will not load correctly and will be missing _Microsoft Teams (browser)_ and _CoPilot (browser)_.

- Turn on **Enable Multi-Project Launch Profiles**. Not having this turned on will prevent _Microsoft Teams (browser)_ and _CoPilot (browser)_. Also the screen shot for these two options is different from the drop down in version 17.11.0 Preview 7.0

### Page URL

https://learn.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/build-bot-based-plugin?tabs=visual-studio

### Content source URL

https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/messaging-extensions/build-bot-based-plugin.md

### Author

@v-ypalikila

### Document Id

db8fce4c-85b3-86af-d642-48be33e13ff6

**Comment by Prasad-MSFT** [comment]
Hi @surbhigupta12, could you please help here to update the document as suggested?
