### ISSUE TITLE
typo in the page

### ISSUE THREAD

**Issue by paul-cheung** [MicrosoftDocs/msteams-docs#1147]
Should "Take advantage **_off_**" be "Take advantage of" in the first paragraph?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b081ffcd-32a2-03ed-1ca9-1d32bdeff00b
* Version Independent ID: 763faefd-c15e-4d32-78ff-9fc95e7f0c73
* Content: [Understand your use cases - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/design/understand-use-cases)
* Content Source: [msteams-platform/concepts/design/understand-use-cases.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/design/understand-use-cases.md)
* Product: **msteams**
* GitHub Login: @clearab
* Microsoft Alias: **anclear**

**Comment by clearab** [comment]
Thanks for letting us know, it will be fixed in the next release.
