### ISSUE TITLE
[Doc Issue][Page not reflecting in TOC]

### ISSUE THREAD

**Issue by v-deabira** [MicrosoftDocs/msteams-docs#11484]
### Type of issue

Other (describe below)

### Feedback

The article is not reflecting in TOC. 
https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/bot-messages-ai-generated-content?tabs=before%2Cbotmessage

### Page URL

https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/bot-messages-ai-generated-content?tabs=before%2Cbotmessage

### Content source URL

https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/bots/how-to/bot-messages-ai-generated-content.md

### Author

@surbhigupta

### Document Id

605a8486-6e6a-31d5-e8a1-021691206099

**Comment by Nivedipa-MSFT** [comment]
@surbhigupta12 - Could you please help here?

**Comment by Nivedipa-MSFT** [comment]
@v-deabira - you please share your valuable feedback via [Microsoft Teams Developer Community Response Feedback](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR7iCOpS5_b9Nqmwx43u5rtZUOThVR081SllSR05aSDQxQ0tUMDVPTVIxTi4u) link?
