### ISSUE TITLE
too many notifications 

### ISSUE THREAD

**Issue by Grand-Poobah** [MicrosoftDocs/msteams-docs#1148]
While I am in a conversation the person on the other end will reply
i get a banner and a activity alert

I would think that since i am looking at the conversation and it has focus that it would not send the notification and show the alert

Even worse is the notification location cannot be moved so it is over the interface 
Besides this the notification and alert come in after i already ready and responded

It is the same if they only give a thumbs up

I miss the skype for business Teams is so pre-alpha

**Comment by Trinetra-MSFT** [comment]
@Grand-Poobah , Thanks for reaching out to us. You can customize the notification settings, Select your profile picture at the top, right corner of teams than  select **Settings**->**Notifications** from there you can fine tune what notification you want to see and where those appears. 
![image](https://user-images.githubusercontent.com/50989436/68913607-dc837600-0781-11ea-852e-5e0a12605a9e.png)

**Comment by Grand-Poobah** [comment]
I understand that however if i am in the chat and it has focus it should not be notifying me

**Comment by clearab** [comment]
Thank you for your feedback - we've let the product team know and hopefully they will address this in a future release.
