### ISSUE TITLE
Unknown Error Response When MS-Teams Making API Request to Microsoft Teams Files API

### ISSUE THREAD

**Issue by abhishekginani-yellow** [MicrosoftDocs/msteams-docs#11491]
### Steps to reproduce

1. Send a file to the teams bot using botframework apis.
2. You will see an option in teams to upload the file to OneDrive; click on "Allow."
3. After clicking "Allow," Teams will make a request to the API, which fails with an unknown error. The HTTP status code is 500.

<img width="580" alt="image" src="https://github.com/user-attachments/assets/cb06a9db-cf17-4845-a778-852c346496c8">

```
{
    "errorCode": "Unknown"
}
```
API:
<img width="929" alt="image" src="https://github.com/user-attachments/assets/ab8ccd20-671b-4c6a-98db-60ff5c77a114">

### Expected behavior

user should be able to upload files to OneDrive that are sent by the Teams bot, and the API should process the request and return the appropriate response

### Actual behavior

Teams app unable to upload the files as API returns an Unknown error, making it difficult to diagnose the problem.

### Error details

```
{
    "errorCode": "Unknown"
}
```

**Comment by Meghana-MSFT** [comment]
@abhishekginani-yellow - We will test this at our end by setting up the following sample - https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/bot-file-upload/csharp. We will check this and get back to you.

**Comment by Meghana-MSFT** [comment]
We checked the above sample, and it is working fine at our end without any error. 
![image](https://github.com/user-attachments/assets/789088ab-2bef-43f6-96ab-4fd14729320b)

**Comment by abhishekginani-yellow** [comment]
What could be the issue in this case? We can see that the API is failing with an unknown error for us.
