### ISSUE TITLE
The Deep link to navigate to a chat is not working on the android client.

### ISSUE THREAD

**Issue by ungsdev** [MicrosoftDocs/msteams-docs#11512]
### Steps to reproduce

1. Open the Teams android client (tested on Samsung Galaxy S21).
2. Click on the deep link to navigate to a chat that created using the method suggested in the [official documentation](https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-link-teams#deep-link-to-navigate-to-a-chat).
3. Instead of navigate to the chat, a message saying "No tab available" is displayed.

### Expected behavior

It navigates to the chat successfully.

### Actual behavior

Instead of navigating to the chat, a message saying "No tab available" is displayed.

### Error details

This issue started occurring suddenly within the last week, even though it was working fine before. I suspect that a recent update might have caused this bug.

P.S. - The displayed message is translated from the Korean "탭이 없습니다" to English, so it may not be the exact message. Thank you for your understanding :)

![image](https://github.com/user-attachments/assets/18b8a099-b4e8-47c9-a556-b397378a284c)

_No response_

**Comment by ungsdev** [comment]
Additionally, I tested that it works correctly on desktop, web, and iOS clients.

**Comment by Prasad-MSFT** [comment]
@ungsdev, thanks for raising your issue. We will check this at our end and will get back to you.
Just for confirmation, you are using below deep link URL right? and is it a group chat?
`https://teams.microsoft.com/l/chat/<chatId>/conversations`

**Comment by ungsdev** [comment]
@Prasad-MSFT, thanks for reply. Yes. I use below deep link url. and it is a group chat.
`https://teams.microsoft.com/l/chat/19:1cad2f68b68844ecb39f1266daa5137e@thread.v2/conversations`

> @ungsdev, thanks for raising your issue. We will check this at our end and will get back to you. Just for confirmation, you are using below deep link URL right? and is it a group chat? `https://teams.microsoft.com/l/chat/<chatId>/conversations`

**Comment by Prasad-MSFT** [comment]
@ungsdev, we are able to repro this issue in Mobile (Android)Teams version.
![image](https://github.com/user-attachments/assets/fc4d87f0-6aa8-4d5f-861d-1dbf7f6689e3)


![image](https://github.com/user-attachments/assets/7451a65a-c7e7-4cc4-92f1-d2afc0f01fc7)

We have raised a bug for the same and engineering team is looking into it. We will inform you once we get any further update. Thanks!

**Comment by ungsdev** [comment]
@Prasad-MSFT Sorry to bother you, but this issue has been ongoing for over a month, so I wanted to check in again. Is there any updates or progress on this issue? Thank you.

**Comment by RaccoonTV** [comment]
I am experiencing the same issue. I would like to know when it will be resolved.

**Comment by Prasad-MSFT** [comment]
We are closing this issue for now. Please feel free to reopen if required. Thanks!
