### ISSUE TITLE
Can not find my bot and configure it anymore, although it exists

### ISSUE THREAD

**Issue by kurbaitis** [MicrosoftDocs/msteams-docs#11527]
### Steps to reproduce

Have a Teams bot app for a few years or create a Teams bot on Azure

### Expected behavior

I should be able to see my Teams bots at https://dev.botframework.com/

### Actual behavior

I do not see the bots over there or on Azure admin

### Error details

I have a Teams app with bot.

Recently something happened and I can't find it to edit or view.
I can't see it on https://dev.botframework.com/ and also on Azure portal.

The bot is working for many our clients. I want to gain its access again for making sure I have control if I need to edit anything within the setup.

What would be the steps to return back the bot?

**Comment by Prasad-MSFT** [comment]
Make sure that the Azure resources associated with the bot (such as the Azure Bot Service) are still active and haven't been deleted or moved.

**Comment by kurbaitis** [comment]
Thank you into looking into this @Prasad-MSFT 

I've just checked and I can't see any service within the Azure Bot service. How may I check that it is deleted or moved?

Teams tenants are able to install the Bot on their Teams setup. So I think the bot is active but unreachable for me.

Let me know please what else I could check.

Thank you very much.

**Comment by Prasad-MSFT** [comment]
@kurbaitis, could you please check with tenant admin whether or not you have the necessary permissions to access and manage the bot?

**Comment by kurbaitis** [comment]
@Prasad-MSFT I think there might be a misunderstanding.

I don't host my bot server on Azure. I have separate server from Azure that accepts bot messages to defined URL at my bot configuration.

The problem is that I can't reach my bot configuration entity. I understand the bot installation is created to clients. But I want to have ownership of the bot configuration entity which I don't have now.

So in theory if I would like for my bot to change the messaging API URL, I would not be able to do that because simply I don't have anymore access to my bot entity on Azure to change that configuration.

Does this clarifies the problem?

Thank you

**Comment by kurbaitis** [comment]
@Prasad-MSFT Thank you!

I've just filled in a case and let's see how it ends.

Thank you for your help. Closing for the moment.
