### ISSUE TITLE
Install Teams Toolkit for Visual Studio / Modify?

### ISSUE THREAD

**Issue by HannuSihvonen** [MicrosoftDocs/msteams-docs#11529]
### Type of issue

Missing information

### Feedback

I was trying to Modify my already-installed Visual Studio according to this 
https://learn.microsoft.com/en-us/microsoftteams/platform/toolkit/toolkit-v4/install-teams-toolkit-vs 
to install Teams Toolkit. 
"If you've already installed Visual Studio, select Modify." 

I never found the option Modify or list of workloads in Installer. When it should appear?

### Page URL

https://learn.microsoft.com/en-us/microsoftteams/platform/toolkit/toolkit-v4/install-teams-toolkit-vs

### Content source URL

https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/toolkit-v4/install-Teams-Toolkit-vs.md

### Author

@HannuSihvonen

### Document Id

5a0afd58-5f42-8a89-856e-9d66ffa2fcce

**Comment by Nivedipa-MSFT** [comment]
@HannuSihvonen - Thanks for reporting your issue. We will check and update the document accordingly.

**Comment by HannuSihvonen** [comment]
This issue can be closed. I was looking Teams Toolkit for Visual Studio **Code**. Not for Visual Studio.
