### ISSUE TITLE
Clarify if `ngrok` is required to debug with the Teams Tooklit

### ISSUE THREAD

**Issue by rido-min** [MicrosoftDocs/msteams-docs#11546]
### Type of issue

Typo

### Feedback

This blog post https://devblogs.microsoft.com/microsoft365dev/teams-toolkit-for-visual-studio-code-update-april-2023/ mentions the Teams Toolkit is based on `Dev Tunnels`, however this article still mentions NGrok as the tunneling tool.

Will be good to clarify if it's still required or supported.

### Page URL

https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/debug/locally-with-an-ide

### Content source URL

https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/bots/how-to/debug/locally-with-an-ide.md

### Author

@surbhigupta

### Document Id

b9e40da9-1029-f65f-18b5-f450a8ea87d2

**Comment by therealjohn** [comment]
@rido-min ngrok is not required, but a tunneling solution _is_ required to debug bots on localhost. 

Teams Toolkit for VS Code and VS use VS Dev Tunnels by default. 

If you're using the Teams App CLI, you'd need to start a tunnel yourself and update the appropriate environment variables for the endpoints and domain used by the project.

**Comment by rido-min** [comment]
> Teams Toolkit for VS Code and VS use VS Dev Tunnels by default.

Exactly !!  This is why I was asking to update the article to reflect the usage of DevTunnels, otherwise the customer will end with two similar tunneling solutions.

BTW, I'm also working to remove the NGrok dependency from the BF-Emulator. 

https://github.com/microsoft/BotFramework-Emulator/pull/2461
https://github.com/MicrosoftDocs/bot-docs-pr/pull/3205

**Comment by therealjohn** [comment]
@rido-min 

The MS Learn article you linked is not about Teams Toolkit, but we might be able to make it clearer on what options you have. Thanks!

**Comment by rido-min** [comment]
The article is about "Test and debug your bot in MSTeams". I think the tools used - with or without the TTK - should be consistent: Same tunneling solution, etc..
