### ISSUE TITLE
why custom app is not available on mobile version? 

### ISSUE THREAD

**Issue by simoneTheNewBlack** [MicrosoftDocs/msteams-docs#1155]
I have installed an app from the app store and it works fine on desktop and web version. 
but i could not find it inside the "more apps"

**Comment by Gousia-MSFT** [comment]
@simoneTheNewBlack Personal apps on mobile are still in developer preview. Could you please [enable developer preview on Mobile](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/dev-preview/developer-preview-intro#on-a-mobile-client) to see your custom apps under "More apps" on mobile?
