### ISSUE TITLE
MS Graph subscription for messages in Teams channel not reliable

### ISSUE THREAD

**Issue by laknoll** [MicrosoftDocs/msteams-docs#11558]
### Steps to reproduce

We’re using a MS Graph subscription to monitor incoming messages in a teams channel. Those subscriptions work well usually, but we got a couple of reports from customers that some messages were missing.

We thus went in to investigate and created a test channel where we have a subscription running and post a message every 3 minutes to the channel. We are usually getting a notification about the posted message, but once or twice per day it is missing. This means, that we're simply seem to not receiving a notification from MS Graph for this one message. The next message posted 3 minutes later is then just fine again.

We have checked everything on our side, that we could think of that could cause this to happen:

* We properly react to lifecycle events for the subscription
* The only lifecycle event we got during the last 36 hours was “reauthorizationRequired”. No "missed” or "subscriptionRemoved” events.
* We checked that we handle all events received from MS Graph within the time limits documented (3 seconds), which we now always do (we usually return a 200 or 202 status within a few milliseconds)

Is this a known bug, or are there additional things we need to do to reliably receive notifications for the subscription?

### Expected behavior

We get an event from MS Graph at our subscription endpoint for each message posted in the Teams channel.

### Actual behavior

Once or twice per day, we do not get notified about a new message posted in MS Teams. We do not get a 'missed' lifecycle event neither, so we have no way of knowing that we missed a message except for polling.

**Comment by sayali-MSFT** [comment]
@laknoll -Thanks for reporting your issue.
We will check this at our end and will get back to you.

**Comment by sayali-MSFT** [comment]
@laknoll - Can you share details for the message which was missed? MessageId, TeamId, ChannelId, Timestamp (of posting), SubscriptionId

**Comment by laknoll** [comment]
Sorry for coming back a bit late on this one. I’ve been on vacation.

Here are a list of events we didn’t receive just very recently:

Tenant: 93d5c58d-0714-4030-88b6-7935da85ab71
Channel: 19:62422bc01dcf45619bf3496352b1f983@thread.tacv2
Message 1728645366510: Monitor 11:16:05
Message 1728645186383: Monitor 11:13:05
Message 1728645006649: Monitor 11:10:05
Message 1728644826277: Monitor 11:07:05
Message 1728644646055: Monitor 11:04:05
Message 1728644466130: Monitor 11:01:05
Message 1728644285949: Monitor 10:58:05
Message 1728644106026: Monitor 10:55:05
Message 1728643926010: Monitor 10:52:05
Message 1728643745690: Monitor 10:49:05
Message 1728643566054: Monitor 10:46:05

The ID of the subscription is 3b833b40-1844-453f-898c-c0d9d50205b9

Can you please re-open the issue? We are still experiencing it, with sporadic failures earlier, but almost complete loss of all events in the last 24 hours.

**Comment by sayali-MSFT** [comment]
Hello @laknoll -Thank you for providing the details. We are currently checking with the engineering team and will be sure to update you as soon as we have any information.

**Comment by sayali-MSFT** [comment]
These messages from early October, it is past the 30 days time period. Do you have new messages? Otherwise were these messages edited recently?
