### ISSUE TITLE
Is App caching still not supported in the new Teams client?

### ISSUE THREAD

**Issue by boraunlu** [MicrosoftDocs/msteams-docs#11562]
### Type of issue

Typo

### Feedback

Is App caching still not supported in the new Teams client?

### Page URL

https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/app-caching

### Content source URL

https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/tabs/how-to/app-caching.md

### Author

@surbhigupta

### Document Id

b54d57c0-dcbf-461c-280e-3361280d28bc

**Comment by Nivedipa-MSFT** [comment]
@boraunlu - Thanks for reporting your issue. We will check and update you soon.
