### ISSUE TITLE
usageRights API is still in Beta and thus can't actually be used in production scenarios

### ISSUE THREAD

**Issue by senkwe** [MicrosoftDocs/msteams-docs#11566]
### Type of issue

Feature doesn't work (bug)

### Feedback

The **UsageRights** API is still in Beta and thus can't actually be used in production scenarios based on the information at https://learn.microsoft.com/en-us/graph/sdks/use-beta?tabs=csharp

In other words, this documentation is incorrect as things stand.

### Page URL

https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license

### Content source URL

https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md

### Author

@heath-hamilton

### Document Id

273416d6-635b-e334-76ed-037473249a6d

**Comment by Nivedipa-MSFT** [comment]
@senkwe - Thanks for reporting your issue. We will check and update you soon.

**Comment by Nivedipa-MSFT** [comment]
@senkwe - Could you please let us know what you mean "this documentation is incorrect as things stand"?

**Comment by senkwe** [comment]
My mistake, I was using the .Net SDK which currently does not support this API.

The REST API seems to work

**Comment by Nivedipa-MSFT** [comment]
@senkwe - Thanks for the confirmation. We are closing this issue for now, please feel free to reopen if required.
