### ISSUE TITLE
Sample code repository

### ISSUE THREAD

**Issue by nikheelneelay** [MicrosoftDocs/msteams-docs#1156]
Can you please share sample code repository to see the implementation of this feature in bot hosted on MS Teams channel?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ad9f167-7d29-f933-7b47-60bd744899b1
* Version Independent ID: 8097fcbd-adcc-ce49-a378-426c65af9296
* Content: [Send proactive messages - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/send-proactive-messages#feedback)
* Content Source: [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/bots/how-to/conversations/send-proactive-messages.md)
* Product: **msteams**
* GitHub Login: @clearab
* Microsoft Alias: **anclear**

**Comment by Gousia-MSFT** [comment]
@nikheelneelay Could you please try this [sample ](https://github.com/OfficeDev/microsoft-teams-sample-complete-csharp/blob/32c39268d60078ef54f21fb3c6f42d122b97da22/template-bot-master-csharp/src/dialogs/examples/teams/ProactiveMsgTo1to1Dialog.cs)to send a proactive message to the user?

**Comment by nikheelneelay** [comment]
@Gousia-MSFT 

Hi, this sample is for Bot framework v3. Could you please share link for Bot framework v4 sample?

**Comment by Gousia-MSFT** [comment]
@nikheelneelay Here is a sample for sending [Proactive message in v4](https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/16.proactive-messages).

**Comment by rutujlangalia** [comment]
Hi @Gousia-MSFT ,

I used ngrok and attached a debugger in the code. I access Bot contact on teams with a new user and waited if it will hit ConversationUpdate but it failed.

For reference I am attaching the files below where I made changes as you suggested on StackOverflow.

[DialogBot.txt](https://github.com/MicrosoftDocs/msteams-docs/files/3916596/DialogBot.txt)
[DialogAndWelcomeBot.txt](https://github.com/MicrosoftDocs/msteams-docs/files/3916597/DialogAndWelcomeBot.txt)
[TeamsActivityHandler.txt](https://github.com/MicrosoftDocs/msteams-docs/files/3916598/TeamsActivityHandler.txt)

Hope you can check the files and will be able to help me with the issue.

**Comment by Gousia-MSFT** [comment]
@rutujlangalia Please use the [StackOverflow ](https://stackoverflow.com/questions/59088977/how-to-get-a-welcome-message-on-teams-even-before-user-sends-any-message)question asked by you to track this. Let's use one point of communication to avoid confusion.
