### ISSUE TITLE
Teams fails to join the call with Audio Video Bot 

### ISSUE THREAD

**Issue by pavanjains** [MicrosoftDocs/msteams-docs#1157]
I compiled the sample AudioVideoPlaybackBot bot followed all the instructions, I can see messages reach the Visual studio but call does not connect. It gives following error message": "MediaControllerConversationAddParticipantFailed. DiagCode: 7112. Please help Bot Id is e8459a67-c315-445f-abf4-588c8da4bdb5

$>2019-11-21T14:51:35.2386656Z Info: LoggingMessageHandler.cs:167 SendAsync
ScenarioId: dbb24454-adb9-4ef9-bc3d-c5856dd31ca9
TransactionDirection: Incoming
TraceType: HttpResponse
ResponseTime: 15
request: POST http://custom.ngrok.io/api/calling
response: 202 Accepted
headers:
  Client-Request-Id: f16c2698-310c-44dd-99c0-1ae4d4224258
  Scenario-Id: dbb24454-adb9-4ef9-bc3d-c5856dd31ca9,dbb24454-adb9-4ef9-bc3d-c5856dd31ca9
  Connection: close
  
$>2019-11-21T14:51:35.2386656Z Info: CommunicationsClientExtensions.cs:153 LogAndCreateResponse
ScenarioId: dbb24454-adb9-4ef9-bc3d-c5856dd31ca9
AppId: xxxxxx-c315-445f-abf4-xxxxxxxxxxxx
AppName: Sample.AudioVideoPlaybackBot.FrontEnd
TransactionDirection: Incoming
TraceType: HttpResponse
ResponseTime: 15
request: POST http://custom.ngrok.io/api/calling
response: 202 Accepted
headers:
  Client-Request-Id: f16c2698-310c-44dd-99c0-1ae4d4224258
  Scenario-Id: dbb24454-adb9-4ef9-bc3d-c5856dd31ca9
  
$>2019-11-21T14:51:35.2381655Z Info: CommunicationsClientExtensions.cs:151 LogAndCreateResponse
ScenarioId: dbb24454-adb9-4ef9-bc3d-c5856dd31ca9
AppId: xxxxxx-c315-445f-abf4-xxxxxxxxxxxx
AppName: Sample.AudioVideoPlaybackBot.FrontEnd
TransactionDirection: Incoming
TraceType: HttpRequest
request: POST http://custom.ngrok.io/api/calling
headers:
  X-Microsoft-Skype-Chain-ID: dbb24454-adb9-4ef9-bc3d-c5856dd31ca9
  Scenario-ID: dbb24454-adb9-4ef9-bc3d-c5856dd31ca9
  X-Microsoft-Skype-Message-ID: f16c2698-310c-44dd-99c0-1ae4d4224258
  X-Forwarded-Proto: (redacted)
  X-Forwarded-For: (redacted)
  Accept: application/json
  Authorization: (redacted)
  Host: custom.ngrok.io
  User-Agent: Microsoft-Skype/3.0,(Calling/1.0)
  Content-Length: 512
  Content-Type: application/json; charset=utf-8
{
  "@odata.type": "#microsoft.graph.commsNotifications",
  "value": [
    {
      "@odata.type": "#microsoft.graph.commsNotification",
      "changeType": "deleted",
      "resourceUrl": "/communications/calls/461f0500-451f-4b71-ba51-b3679f88d9dd",
      "resource": "/app/calls/461f0500-451f-4b71-ba51-b3679f88d9dd",
      "resourceData": {
        "@odata.type": "#microsoft.graph.call",
        "state": "terminated",
        "resultInfo": {
          "@odata.type": "#microsoft.graph.resultInfo",
          "code": 500,
          "subcode": 9997,
          "message": "MediaControllerConversationAddParticipantFailed. DiagCode: 7112"
        },
        "tenantId": "xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
        "id": "461f0500-451f-4b71-ba51-b3679f88d9dd"
      }
    }
  ]
}

$>2019-11-21T14:51:35.2231625Z Info: LoggingMessageHandler.cs:138 SendAsync
ScenarioId: dbb24454-adb9-4ef9-bc3d-c5856dd31ca9
TransactionDirection: Incoming
TraceType: HttpRequest
request: POST http://custom.ngrok.io/api/calling
headers:
  X-Microsoft-Skype-Chain-ID: dbb24454-adb9-4ef9-bc3d-c5856dd31ca9
  Scenario-ID: dbb24454-adb9-4ef9-bc3d-c5856dd31ca9
  X-Microsoft-Skype-Message-ID: f16c2698-310c-44dd-99c0-1ae4d4224258
  X-Forwarded-Proto: (redacted)
  X-Forwarded-For: (redacted)
  Accept: application/json
  Authorization: (redacted)
  Host: custom.ngrok.io
  User-Agent: Microsoft-Skype/3.0,(Calling/1.0)
  Content-Length: 512
  Content-Type: application/json; charset=utf-8
  
$>2019-11-21T14:51:32.4721124Z Info: LoggingMessageHandler.cs:167 SendAsync
ScenarioId: dbb24454-adb9-4ef9-bc3d-c5856dd31ca9
TransactionDirection: Incoming
TraceType: HttpResponse
ResponseTime: 3
request: POST http://custom.ngrok.io/api/calling
response: 202 Accepted
headers:
  Client-Request-Id: 390c80e9-75aa-41dd-886b-88f65d828d3e
  Scenario-Id: dbb24454-adb9-4ef9-bc3d-c5856dd31ca9,dbb24454-adb9-4ef9-bc3d-c5856dd31ca9
  Connection: close
  
$>2019-11-21T14:51:32.4721124Z Info: CommunicationsClientExtensions.cs:153 LogAndCreateResponse
ScenarioId: dbb24454-adb9-4ef9-bc3d-c5856dd31ca9
AppId: xxxxxx-c315-445f-abf4-xxxxxxxxxxxx
AppName: Sample.AudioVideoPlaybackBot.FrontEnd
TransactionDirection: Incoming
TraceType: HttpResponse
ResponseTime: 2
request: POST http://custom.ngrok.io/api/calling
response: 202 Accepted
headers:
  Client-Request-Id: 390c80e9-75aa-41dd-886b-88f65d828d3e
  Scenario-Id: dbb24454-adb9-4ef9-bc3d-c5856dd31ca9
  
$>2019-11-21T14:51:32.4716123Z Info: CommunicationsClientExtensions.cs:151 LogAndCreateResponse
ScenarioId: dbb24454-adb9-4ef9-bc3d-c5856dd31ca9
AppId: xxxxxx-c315-445f-abf4-xxxxxxxxxxxx
AppName: Sample.AudioVideoPlaybackBot.FrontEnd
TransactionDirection: Incoming
TraceType: HttpRequest
request: POST http://custom.ngrok.io/api/calling
headers:
  X-Microsoft-Skype-Chain-ID: dbb24454-adb9-4ef9-bc3d-c5856dd31ca9
  Scenario-ID: dbb24454-adb9-4ef9-bc3d-c5856dd31ca9
  X-Microsoft-Skype-Message-ID: 390c80e9-75aa-41dd-886b-88f65d828d3e
  X-Forwarded-Proto: (redacted)
  X-Forwarded-For: (redacted)
  Accept: application/json
  Authorization: (redacted)
  Host: custom.ngrok.io
  User-Agent: Microsoft-Skype/3.0,(Calling/1.0)
  Content-Length: 353
  Content-Type: application/json; charset=utf-8
{
  "@odata.type": "#microsoft.graph.commsNotifications",
  "value": [
    {
      "@odata.type": "#microsoft.graph.commsNotification",
      "changeType": "updated",
      "resourceUrl": "/communications/calls/461f0500-451f-4b71-ba51-b3679f88d9dd",
      "resource": "/app/calls/461f0500-451f-4b71-ba51-b3679f88d9dd",
      "resourceData": {
        "@odata.type": "#microsoft.graph.call",
        "state": "establishing",
        "id": "461f0500-451f-4b71-ba51-b3679f88d9dd"
      }
    }
  ]
}

$>2019-11-21T14:51:32.4686117Z Info: LoggingMessageHandler.cs:138 SendAsync
ScenarioId: dbb24454-adb9-4ef9-bc3d-c5856dd31ca9
TransactionDirection: Incoming
TraceType: HttpRequest
request: POST http://custom.ngrok.io/api/calling
headers:
  X-Microsoft-Skype-Chain-ID: dbb24454-adb9-4ef9-bc3d-c5856dd31ca9
  Scenario-ID: dbb24454-adb9-4ef9-bc3d-c5856dd31ca9
  X-Microsoft-Skype-Message-ID: 390c80e9-75aa-41dd-886b-88f65d828d3e
  X-Forwarded-Proto: (redacted)
  X-Forwarded-For: (redacted)
  Accept: application/json
  Authorization: (redacted)
  Host: custom.ngrok.io
  User-Agent: Microsoft-Skype/3.0,(Calling/1.0)
  Content-Length: 353
  Content-Type: application/json; charset=utf-8
  
$>2019-11-21T14:51:31.7999780Z Info: GraphAuthClient.cs:154 SendHttpRequestAsync
ScenarioId: dbb24454-adb9-4ef9-bc3d-c5856dd31ca9
AppId: xxxxxx-c315-445f-abf4-xxxxxxxxxxxx
AppName: Sample.AudioVideoPlaybackBot.FrontEnd
CallId: 461f0500-451f-4b71-ba51-b3679f88d9dd
TenantId: xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
TransactionDirection: Outgoing
TraceType: HttpResponse
ResponseTime: 394
request: POST https://graph.microsoft.com/beta/communications/calls/461f0500-451f-4b71-ba51-b3679f88d9dd/microsoft.graph.answer
response: 202 Accepted
headers:
  request-id: b75d0f1f-350e-4ad3-bb82-9ce4d588949d
  client-request-id: 9cd358da-f387-42c9-9813-d1341e9e3578
  x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"East US","Slice":"SliceC","Ring":"5","ScaleUnit":"002","RoleInstance":"AGSFE_IN_17"}}
  scenario-id: dbb24454-adb9-4ef9-bc3d-c5856dd31ca9
  Strict-Transport-Security: max-age=31536000
  Cache-Control: private
  Date: Thu, 21 Nov 2019 14:51:31 GMT
  Content-Length: 0
  Content-Type: text/plain
  
$>2019-11-21T14:51:31.3728926Z Info: GraphAuthClient.cs:101 SendHttpRequestAsync
ScenarioId: dbb24454-adb9-4ef9-bc3d-c5856dd31ca9
AppId: xxxxxx-c315-445f-abf4-xxxxxxxxxxxx
AppName: Sample.AudioVideoPlaybackBot.FrontEnd
CallId: 461f0500-451f-4b71-ba51-b3679f88d9dd
TenantId: xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
TransactionDirection: Outgoing
TraceType: HttpRequest
request: POST https://graph.microsoft.com/beta/communications/calls/461f0500-451f-4b71-ba51-b3679f88d9dd/microsoft.graph.answer
headers:
  Scenario-Id: dbb24454-adb9-4ef9-bc3d-c5856dd31ca9
  Client-Request-Id: 9cd358da-f387-42c9-9813-d1341e9e3578
  User-Agent: GraphCommunicationsClient-Sample.AudioVideoPlaybackBot.FrontEnd/1.1.0.2027
  Authorization: (redacted)
  Content-Type: application/json; charset=utf-8
{
  "callbackUri": "https://custom.ngrok.io/api/calling",
  "mediaConfig": {
    "@odata.type": "#microsoft.graph.appHostedMediaConfig",
    "blob": "{\"mpUri\":\"net.tcp://1.custom-msteam.domain.com:11111/MediaProcessor\",\"audioRenderContexts\":[\"dfb2aa1b-f104-4b3f-96e7-c32d4e805bfc\"],\"videoRenderContexts\":[\"251a69da-3850-48ea-905b-b2a4b58503f6\",\"d7fd3830-c3f6-4dac-b621-ad826f42866a\",\"11af6fc2-2f79-4db9-93f6-fbf6852fa53e\",\"552f8655-af57-421b-b067-1e6aa8afdad0\"],\"vbssRenderContexts\":[\"873a0331-7ef1-40b7-80ca-3b366e57bbd1\"],\"audioSourceContexts\":[\"fc5b748b-7d1c-4207-afbc-1cbd8418a07d\"],\"videoSourceContexts\":[\"273e5d72-7b5a-4813-8eb2-bdc47fcb3bf1\"],\"vbssSourceContexts\":[\"0e11699c-063f-4c41-acbd-ab46d832b1a2\"],\"dataRenderContexts\":null,\"dataSourceContexts\":null,\"supportedAudioFormat\":\"Pcm16K\",\"videoSinkEncodingFormats\":[\"H264\",\"H264\",\"H264\",\"H264\"],\"vbssSinkEncodingFormats\":[\"H264\"],\"initialScreenSharingRole\":\"Viewer\",\"mpMediaSessionId\":\"64d09c6d-271d-4b1d-aa49-970320836173\",\"regionAffinity\":null,\"skypeMediaBotsVersion\":\"1.13.1.0324\",\"mediaStackVersion\":\"2019.28.1.6\",\"mpVersion\":\"7.2.0.5523\",\"callId\":\"461f0500-451f-4b71-ba51-b3679f88d9dd\"}"
  },
  "acceptedModalities": [
    "audio",
    "video",
    "videoBasedScreenSharing"
  ]
}

$>2019-11-21T14:51:29.9711123Z Info: LoggingMessageHandler.cs:167 SendAsync
ScenarioId: dbb24454-adb9-4ef9-bc3d-c5856dd31ca9
TransactionDirection: Incoming
TraceType: HttpResponse
ResponseTime: 1609
request: POST http://custom.ngrok.io/api/calling
response: 202 Accepted
headers:
  Client-Request-Id: cd70f182-7d09-4bed-bf8f-7d6b1bb52a84
  Scenario-Id: dbb24454-adb9-4ef9-bc3d-c5856dd31ca9,dbb24454-adb9-4ef9-bc3d-c5856dd31ca9
  Connection: close
  
$>2019-11-21T14:51:29.9656112Z Info: CommunicationsClientExtensions.cs:153 LogAndCreateResponse
ScenarioId: dbb24454-adb9-4ef9-bc3d-c5856dd31ca9
AppId: xxxxxx-c315-445f-abf4-xxxxxxxxxxxx
AppName: Sample.AudioVideoPlaybackBot.FrontEnd
TransactionDirection: Incoming
TraceType: HttpResponse
ResponseTime: 1483
request: POST http://custom.ngrok.io/api/calling
response: 202 Accepted
headers:
  Client-Request-Id: cd70f182-7d09-4bed-bf8f-7d6b1bb52a84
  Scenario-Id: dbb24454-adb9-4ef9-bc3d-c5856dd31ca9
  
$>2019-11-21T14:51:29.9551091Z Info: CommunicationsClientExtensions.cs:151 LogAndCreateResponse
ScenarioId: dbb24454-adb9-4ef9-bc3d-c5856dd31ca9
AppId: xxxxxx-c315-445f-abf4-xxxxxxxxxxxx
AppName: Sample.AudioVideoPlaybackBot.FrontEnd
TransactionDirection: Incoming
TraceType: HttpRequest
request: POST http://custom.ngrok.io/api/calling
headers:
  X-Microsoft-Skype-Chain-ID: dbb24454-adb9-4ef9-bc3d-c5856dd31ca9
  X-Microsoft-Skype-Caller-Region: amer
  X-Microsoft-Skype-Message-ID: cd70f182-7d09-4bed-bf8f-7d6b1bb52a84
  X-Microsoft-Skype-Original-Message-ID: d7c9f605-799b-4157-bc5c-e320edfc9975
  X-Forwarded-Proto: (redacted)
  X-Forwarded-For: (redacted)
  Accept: application/json
  Authorization: (redacted)
  Host: custom.ngrok.io
  User-Agent: Microsoft-Skype/3.0,(Calling/1.0)
  Content-Length: 1457
  Content-Type: application/json; charset=utf-8
{
  "@odata.type": "#microsoft.graph.commsNotifications",
  "value": [
    {
      "@odata.type": "#microsoft.graph.commsNotification",
      "changeType": "created",
      "resourceUrl": "/communications/calls/461f0500-451f-4b71-ba51-b3679f88d9dd",
      "resource": "/app/calls/461f0500-451f-4b71-ba51-b3679f88d9dd",
      "resourceData": {
        "@odata.type": "#microsoft.graph.call",
        "state": "incoming",
        "direction": "incoming",
        "callbackUri": "https://custom.ngrok.io/api/calling",
        "source": {
          "@odata.type": "#microsoft.graph.participantInfo",
          "identity": {
            "@odata.type": "#microsoft.graph.identitySet",
            "user": {
              "@odata.type": "#microsoft.graph.identity",
              "id": "c94f1ca4-ff5e-41c9-815a-6af65ede13b9",
              "tenantId": "xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
            }
          },
          "endpointType": "default",
          "region": "amer",
          "languageId": "en-us",
          "id": "4332df0a-cad7-49f1-8d9d-041ac8638597"
        },
        "targets": [
          {
            "@odata.type": "#microsoft.graph.invitationParticipantInfo",
            "identity": {
              "@odata.type": "#microsoft.graph.identitySet",
              "application": {
                "@odata.type": "#microsoft.graph.identity",
                "id": "xxxxxx-c315-445f-abf4-xxxxxxxxxxxx"
              }
            },
            "endpointType": "default",
            "id": "0901ee33-b9dc-4144-ab80-8b190d733421",
            "region": null,
            "languageId": null
          }
        ],
        "tenantId": "xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
        "myParticipantId": "0901ee33-b9dc-4144-ab80-8b190d733421",
        "incomingContext": {
          "@odata.type": "#microsoft.graph.incomingContext",
          "sourceParticipantId": "4332df0a-cad7-49f1-8d9d-041ac8638597"
        },
        "id": "461f0500-451f-4b71-ba51-b3679f88d9dd"
      }
    }
  ]
}

$>2019-11-21T14:51:28.3472876Z Info: LoggingMessageHandler.cs:138 SendAsync
ScenarioId: dbb24454-adb9-4ef9-bc3d-c5856dd31ca9
TransactionDirection: Incoming
TraceType: HttpRequest
request: POST http://custom.ngrok.io/api/calling
headers:
  X-Microsoft-Skype-Chain-ID: dbb24454-adb9-4ef9-bc3d-c5856dd31ca9
  X-Microsoft-Skype-Caller-Region: amer
  X-Microsoft-Skype-Message-ID: cd70f182-7d09-4bed-bf8f-7d6b1bb52a84
  X-Microsoft-Skype-Original-Message-ID: d7c9f605-799b-4157-bc5c-e320edfc9975
  X-Forwarded-Proto: (redacted)
  X-Forwarded-For: (redacted)
  Accept: application/json
  Authorization: (redacted)
  Host: custom.ngrok.io
  User-Agent: Microsoft-Skype/3.0,(Calling/1.0)
  Content-Length: 1457
  Content-Type: application/json; charset=utf-8

**Comment by Trinetra-MSFT** [comment]
@pavanjains, Thanks for reporting this , we are looking into this.

**Comment by ksikorsk** [comment]
Hi,

Thanks for the logs, helps us see what is happening under the hood.  First off, I see you're doing local runs of your bot.  While this can be done and we provide some guidance, it is not a method we officially support.

That being said, I see that our media service cannot connect to your local media processor.

```http
HTTP/1.1 500
X-Microsoft-Skype-Processing-Instance: Microsoft.Skype.MediaController.FrontEnd_IN_10
X-Microsoft-Skype-Message-ID: f1930566-2ac4-4965-b1f6-265a489fd618
X-Microsoft-Skype-Chain-ID: dbb24454-adb9-4ef9-bc3d-c5856dd31ca9
X-Microsoft-Skype-Proxy-Instance: Microsoft.Skype.MediaController.FrontEnd_IN_3
Date: Thu, 21 Nov 2019 14:51:32 GMT
Server: Microsoft-HTTPAPI/2.0,Microsoft-HTTPAPI/2.0
Content-Length: 211
Content-Type: application/json; charset=utf-8
{
  "addParticipantResponse": null,
  "debugContent": {
    "correlationId": "dbb24454-adb9-4ef9-bc3d-c5856dd31ca9"
  },
  "reason": "MP resources creation failure",
  "mpUri": "net.tcp://1.pavan-msteam.vbrick.com:25605/MediaProcessor"
}
```

I would confirm that your ports match the port ngrok opened up for you, and that your CName points to the right instance of the ngrok tcp proxy.  Specifically the highlighted values:
> **_1_**.pavan-msteam.vbrick.com:**_25605_**

**Comment by pavanjains** [comment]
Hi,
Thanks for this pointer.

I have verified that ngrok port matches also CName is correct as well, I verified it with simple TCP client server programs. Does that mean that my Bot is misbehaving? Is there Teams log that I can look to confirm what is it going on.

Regards,
Pavan

**Comment by ksikorsk** [comment]
The other common issue is not using the right certificate for your bot.  Do you have an ssl certificate for "*.pavan-msteam.vbrick.com" and are you using this to initiate the media platform?

**Comment by pavanjains** [comment]
Thanks Cert was an issue.
