### ISSUE TITLE
Personal Tab not loading in Teams i frame

### ISSUE THREAD

**Issue by sathishjsparrow** [MicrosoftDocs/msteams-docs#11576]
### Steps to reproduce

I have developed a teams personal tab which is a help tab,,it is not loading in teams iframe but it is being loaded in browser

this is the view i am returning

`<html>
<head>
    
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700|Source+Serif+Pro:700|Source+Code+Pro&display=swap" rel="stylesheet"/>
    <link rel="stylesheet" href="https://asset.surveysparrow.com/production/dist-e8c431be73decc06eea2b6887d3393bc/css/surveysparrow-microsoft-teams.bundle.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.0/normalize.min.css" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/icon?family=Material+Icons" />
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <script crossorigin src="https://static.surveysparrow.com/application/vendors/react@16.8.3/react.production.min.js"></script>
    <script crossorigin src="https://static.surveysparrow.com/application/vendors/react-dom@16.8.2/react-dom.production.min.js"></script>
</head>

<body>
    <div style="display: none;" id="ss-hydrated-data">
        {"config":{"assetPrefix":"https://asset.surveysparrow.com/production/dist-e8c431be73decc06eea2b6887d3393bc"}}
    </div>
    <div id="app-container"></div>
    <script src="https://asset.surveysparrow.com/production/dist-e8c431be73decc06eea2b6887d3393bc/teams_help_tab.app.bundle.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.0/jquery.min.js"></script>
    <script src="https://use.typekit.net/tyg1bfx.js"></script>
</body>
</html>`

In headers also i passed frame ancestors:

`default-src 'self' https: http: data: blob: ;base-uri 'self' ;object-src 'none' ;script-src 'self' 'unsafe-inline' 'unsafe-eval' https: http: ;style-src 'self' 'unsafe-inline' https: http: ;frame-ancestors 'self' teams.microsoft.com *.teams.microsoft.com ;connect-src 'self' https: http: ws: ;`

I am getting the below error in network tab, is this blocking the help tab to render inside iframe?

### Expected behavior

Should render the tab inside iframe

### Actual behavior

Help tab is not rendering

### Error details

![image](https://github.com/user-attachments/assets/3012e393-b225-4986-961f-3c9a9e0e8959)

**Comment by Nivedipa-MSFT** [comment]
@sathishjsparrow - Thanks for reporting your issue. We will check and update you soon.

**Comment by Nivedipa-MSFT** [comment]
@sathishjsparrow - Could you please share the app manifest zip along with repro video to test at our end?

**Comment by Nivedipa-MSFT** [comment]
@sathishjsparrow - We have tested your manifest zip and got the below error.
Refused to frame 'https://surveysparrow.com/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'self' *.surveysparrow.com thrivesparrow.com *.thrivesparrow.com".

![image](https://github.com/user-attachments/assets/d3aa5f47-d9da-4c51-b1d2-714d5fd1caea)

The error message indicates that the URL https://surveysparrow.com/ is being blocked because it violates the CSP directive set by an ancestor.
Could you please refer below document to follow prerequisites while building your Teams personal and channel or group tab.
https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/tab-requirements

Please let us know if you have any further query here:

**Comment by sathishjsparrow** [comment]
I believe you're using the production manifest, but those headers haven't been deployed in it yet. The issue is also occurring in my local app.
In our staging app it is working fine..in our production app
We have added all those headers in response but still is not loading in my local app

these are the headers i have added
"frame-ancestors": [
      "self",
      "teams.microsoft.com",
      "*.teams.microsoft.com"
    ]

**Comment by sathishjsparrow** [comment]
We are open for call to solve this issue

**Comment by Nivedipa-MSFT** [comment]
@sathishjsparrow - Could you please confirm that the URL https://surveysparrow.com/ is directing to the login page?

**Comment by Nivedipa-MSFT** [comment]
@sathishjsparrow - Could you please confirm that the URL https://surveysparrow.com/ is directing to the Sign-in page?
Sign-in pages don't render in iFrames as a safeguard against clickjacking. Your authentication logic needs to use a method other than redirect. For example, use token-based or cookie-based authentication.
