### ISSUE TITLE
Outdated "FindRoom" in GraphExlporer & Docs

### ISSUE THREAD

**Issue by 0xF3546** [MicrosoftDocs/msteams-docs#11582]
### Type of issue

Outdated article

### Feedback

As i know, "https://graph.microsoft.com/beta/me/findRooms" is now "https://graph.microsoft.com/beta/places/microsoft.graph.roomList".
So /me/findRooms doesn't work anymore.
![image](https://github.com/user-attachments/assets/1af95d97-839f-4ea8-8293-cdf6e9d84c77)

Needs to be changed in:
https://developer.microsoft.com/en-us/graph/graph-explorer
&
https://learn.microsoft.com/en-us/graph/api/user-findrooms?view=graph-rest-beta&tabs=csharp

### Page URL

can't submit without filling this field

### Content source URL

can't submit without filling this field

### Author

can't submit without filling this field

### Document Id

can't submit without filling this field

**Comment by sayali-MSFT** [comment]
@0xF3546 - Thanks for reporting your issue.
We will check this at our end and will get back to you.

**Comment by ChetanSharma-msft** [comment]
Hello @o365devx - Sorry for delay in response.
We have done some investigation and here are our findings:

1) findRooms API is available in Beta and its working in Graph Explorer:
https://learn.microsoft.com/en-us/graph/api/user-findrooms?view=graph-rest-beta&tabs=http

As this API is not available in V1.0 (Not documented), it's throwing expected error as below.
"code": "Request_ResourceNotFound",
 "message": "Resource 'findroom' does not exist or one of its queried reference-property objects are not present.",
        
  2) https://graph.microsoft.com/beta/places/microsoft.graph.roomList
  This API will work in Beta and V1.0 as well and required admin consent.
  
  As per our understanding, we no need to update the documentation.
  
 Just wanted to know your thoughts and let us know what exactly we can update if needed.
 
 Thanks!!
