### ISSUE TITLE
Teams App Icons Not Loading Sometimes

### ISSUE THREAD

**Issue by johnmiroki** [MicrosoftDocs/msteams-docs#11580]
### Steps to reproduce

Often, Teams app / bot icons are not loaded correctly and a generic icon is displayed instead

### Expected behavior

Icons are loaded successfully

### Actual behavior

Example: ![image](https://github.com/user-attachments/assets/a1912c9d-ede3-4e2c-bf4b-a9339ccdf661)

![image](https://github.com/user-attachments/assets/6e6c5917-ffe2-4906-9057-bc7248db9dca)

### Error details

Anything we can do to troubleshoot this?

**Comment by Meghana-MSFT** [comment]
Thank you for reporting this, we will check this and get back to you.

**Comment by Meghana-MSFT** [comment]
@johnmiroki - Could you please share the client version that you are in? There was a fix recently released to production that solved similar problem for multiple users.
