### ISSUE TITLE
MS Teams - Bot framework bot is slow 

### ISSUE THREAD

**Issue by gykung** [MicrosoftDocs/msteams-docs#11583]
### Steps to reproduce

I have a bot, written in Python, bot framework, run on a local VM, connected via ngrok to my bot app for my enterprise. User messages take about 5-7 seconds before it reaches the bot/VM. Does anyone else face a similar issue? What’s the typical latency expected?

One interesting observation: during the crowdstrike incident, the bot responded significantly faster. My enterprise was not affected by crowdstrike.

Sorry for asking this question here, I am not sure where else to ask this. 

### Expected behavior

Nearly zero lag.

### Actual behavior

5-7 seconds lag.

**Comment by Meghana-MSFT** [comment]
Thank you for reporting this, we will check this and get back to you.

**Comment by Meghana-MSFT** [comment]
@gykung - Could you please share the bot id with us at microsoftteamsdev@microsoft.com. Also, please note that

A host (and a bot is just a webapp host) not receiving a message or it's slow getting there is 999 times out of 1000 a network issue.
 
Python, like JS, is a single threaded core.  So, it's not hard to imagine in a very high load situation where the bot is just backed up.  But this is rare since, A) Very high load, B) Mostly applies to compute bound situations. i.e., The bot is running some very complex algorithm during each message.

**Comment by gykung** [comment]
Hi Meghana,

Thank you very much for your reply. The MicrosoftAppId
is "515d62a9-34b7-4f90-b213-8b4c7721951f". In case there are analytics on
your end that could help us solve the issue, feel free to share with me.

I agree it could ultimately be a network issue as it is taking several
seconds for the incoming request to reach the Python bot app. I've tried
ping but there is no lag. If there are specific Azure admin settings,
Azure-related network issues we should trace, feel free to suggest.

Thank you.

Regards,
Guangyi @gykung

**Comment by Meghana-MSFT** [comment]
@gykung - We have shared the MicrosoftAppId with engineering team, we will keep you posted on the investigation details. Thank you.

**Comment by gykung** [comment]
I presume that the traffic flows this way: User-->teams.microsoft.com-->botframework.com-->ngrok tunnel --> VM hosting the bot, and then in reverse direction to return the response to the user.

I've tried tracert with directly to my ngrok address, with teams.microsoft.com, and botframework.com.

Notably, botframework.com has the most significant lag.

![image](https://github.com/user-attachments/assets/8b5f1527-9269-40c1-9130-fd60716f6034)

**Comment by gykung** [comment]
@Meghana-MSFT I've fixed the issue. It was an unexpected issue in the app. Somehow the tracert and network tracing had been giving false clues. Thanks for the time spent on this.

**Comment by gykung** [comment]
@Meghana-MSFT I've fixed the issue. It was an unexpected issue in the app. Somehow the tracert and network tracing had been giving false clues. Thanks for the time spent on this.
