### ISSUE TITLE
Mobile client developer preview not showing up

### ISSUE THREAD

**Issue by LalitAgrawala004** [MicrosoftDocs/msteams-docs#1158]
I followed all the steps mentioned above. I am able to see developer preview option on my desktop client but on mobile client it is not visible. Can you please help me ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 008da4e2-979e-c396-db28-4acf57deb530
* Version Independent ID: f1413f77-5eb3-e1fd-9235-d322d6e4eb6c
* Content: [Developer Preview - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/dev-preview/developer-preview-intro#feedback)
* Content Source: [msteams-platform/resources/dev-preview/developer-preview-intro.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/resources/dev-preview/developer-preview-intro.md)
* Product: **msteams**
* GitHub Login: @clearab
* Microsoft Alias: **anclear**

**Comment by Gousia-MSFT** [comment]
@LalitAgrawala004 What's the Team app version you are on? Could you please try updating your teams app version to the latest one? Here is how you can enable [Developer preview on Mobile](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/dev-preview/developer-preview-intro#on-a-mobile-client).

**Comment by LalitAgrawala004** [comment]
I am having latest version of team app on my mobile. and followed the step
mentioned in the document.. As  I mentioned, I am able to see in desktop
version but not in mobile app. Attached is the screenshot from my mobile
app.

**Comment by Gousia-MSFT** [comment]
@LalitAgrawala004 Sorry I cannot view the screenshot. Could you please share it again?

**Comment by pepsikat** [comment]
I have the same issue. 

Android version: 10
Attached is the screenshot from my mobile app 
https://sun9-55.userapi.com/c855324/v855324578/1d6a1f/4q5jfUwFXWE.jpg

**Comment by Gousia-MSFT** [comment]
Are you still facing this issue?

**Comment by Nikitha-MSFT** [comment]
@LalitAgrawala004 - If you are still facing the issue, please feel free to reopen the issue. Closing the issue as of now.
