### ISSUE TITLE
"Setting up a custom incoming webhook"   doesn't work

### ISSUE THREAD

**Issue by rstrauss-logyx** [MicrosoftDocs/msteams-docs#1160]
Setting up a custom incoming webhook
says:
1. In Microsoft Teams, choose More options (⋯) next to the channel name and then choose Connectors.

There’s no “Connectors” option when I click on …  next to the channel name…
If one needs some sort of permission, 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28316a67-22fa-8a05-1ae0-fbe1c5720ef9
* Version Independent ID: 8a250e46-2a30-af86-839d-9f83a8b48041
* Content: [Sending messages to Connectors and Webhooks - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-using#feedback)
* Content Source: [msteams-platform/webhooks-and-connectors/how-to/connectors-using.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/webhooks-and-connectors/how-to/connectors-using.md)
* Product: **msteams**
* GitHub Login: @clearab
* Microsoft Alias: **anclear**

**Comment by Gousia-MSFT** [comment]
@rstrauss-logyx Could you please share a screenshot of the issue you are seeing?

**Comment by rstrauss-logyx** [comment]
The image has 2 snapshots, one of the team "..." menu and one of the channel menu...

![image](https://user-images.githubusercontent.com/37351823/69463885-c5b8c280-0d31-11ea-976c-946ce953489d.png)

**Comment by clearab** [comment]
This looks like apps are disabled for your organization. Please see https://docs.microsoft.com/en-us/MicrosoftTeams/deploy-apps-microsoft-teams-landing-page. Let us know if that is not the cause of the issue.

**Comment by rstrauss-logyx** [comment]
That's a long page.  What do you want me to look for there?  I searched for "enabled" and "disabled" and found nothing.  How do I know if they are disabled for my organization or if this is a bug?  I am in a hierarchy of organizations: Which one governs this?  Who would I speak with (name and phone number) to find out if we can get the BitBucket and GitHub apps enabled?  (Please advise MS to add this information in the app's settings info, instead of making customers waste time searching.)

**Comment by rstrauss-logyx** [comment]
Note that whatever this is set to, that information should be available in the app- both which permissions or roles I have, and which I don't have.
In the configuration for the app, there should be a way to set the email or URL for questions or issues.  Your docs clearly were wrong- citing icons I can't see.  Rather than just pointing me to a non-existent apps icon, it should also say what to do if the icon isn't there.  

Similarly for your "Let us know if that is not the cause"- you should say HOW to let you know. After I submitted my first comment after it was closed, it's still closed.

**Comment by clearab** [comment]
Hi - Sorry for not being clear, responding to this Issue was how to let us know.

**Comment by rstrauss-logyx** [comment]
I believe you meant, “responding to the email”…
I clicked on the link in the 2nd one:  “Closed #1160”
-r
Randy Strauss, desk: 650-604-0431 (Bldg N210, Rm 145, Cube 36)
PS:  I considered powering my computer off and on a few times…

**Comment by clearab** [comment]
Your organization's tenant admins control the availability of apps for your organization. If they choose to intentionally disable them they no long appear in the list of available options. I unfortunately cannot assist you in locating your administrators; I do not have access to that information. If you do not know who your administrators are, would it be possible for you to open a ticket with your IT department?

The documentation reflects the default behavior. Teams, and Office 365 in general, is highly customizable through administration policies. Unfortunately it isn't really possible to document all possible permutations (and for most users doing so would be very confusing), so we stick with documenting the default behavior.

**Comment by clearab** [comment]
I deleted your comment because it contained your email address.

**Comment by rstrauss-logyx** [comment]
I will go back through our channels.

Though I believe you that you gave MS’s rationale, but your logic is seriously flawed.
It certainly IS possible to document the effect of most options.  Documenting permutations is rarely necessary, much less “all possible” ones.
This would NOT be confusing if this information was relegated to an Exceptions section at the bottom, or a separate page.

And consider that most people will never use most of the documentation.  Mostly it’ll be used by people searching for answers about bugs or edge cases.
Having a section at the end for exceptions, even if it was very long, would help both customers and internal testers.

Plus, I’ll bet all configuration options are pretty easily available in the software, so throwing up a list of them would be pretty easy, if not pretty.
I would have easily searched through that and found out which “apps” properties were disabled.

Best wishes,
-r
Randy Strauss, desk: 650-604-0431 (Bldg N210, Rm 145, Cube 36)

**Comment by clearab** [comment]
Thank you for the feedback, we'll take that into consideration for a future iteration. The Connectors option is not available in your environment.
