### ISSUE TITLE
Link: Microsoft Graph APIs for calls and online meetings (https://docs.microsoft.com/en-us/graph/api/resources/calls-api-overview) leads to 404

### ISSUE THREAD

**Issue by slavikko** [MicrosoftDocs/msteams-docs#1163]
Microsoft Graph APIs for calls and online meetings (https://docs.microsoft.com/en-us/graph/api/resources/calls-api-overview) leads to 404, should it maybe point to this: https://docs.microsoft.com/en-us/graph/api/resources/communications-api-overview?view=graph-rest-beta ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec61ebda-d508-a503-883f-d606d1adea19
* Version Independent ID: 81812ba6-38b0-2598-e989-31284b3cab6b
* Content: [Features in the Public Developer Preview - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/dev-preview/developer-preview-features#feedback)
* Content Source: [msteams-platform/resources/dev-preview/developer-preview-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/resources/dev-preview/developer-preview-features.md)
* Product: **msteams**
* GitHub Login: @clearab
* Microsoft Alias: **anclear**

**Comment by Trinetra-MSFT** [comment]
@slavikko , Did you provided all the [Permission's](https://docs.microsoft.com/en-us/graph/api/resources/communications-api-overview?view=graph-rest-beta#authorization) which is documented?
