### ISSUE TITLE
Authentication with the Bot Connector API not passing valid keyID inside JWT headers

### ISSUE THREAD

**Issue by Chang025** [MicrosoftDocs/msteams-docs#11633]
### Steps to reproduce

doc reference: https://learn.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-authentication?view=azure-bot-service-4.0&tabs=multitenant#connector-to-bot
Authentication with the Bot Connector API not passing valid key ID inside JWT headers
We are using the above documentation to validate the bot request at our servers.
The key ID which we are receiving as part of the headers of the JWT token passed inside AUTHORIZATION header, we are not able to match that with the list of valid signing keys.

### Expected behavior

It should provide a valid keyID header so that we can authorize the request coming from auzre bot to our servers.

### Actual behavior

The keyID provided in the JWT token as part of the authorization header is not matching with any of the keys listed jwtk_uri, which we receive by following the document mentioned above.

**Comment by Meghana-MSFT** [comment]
Thank you for reporting this, we will check this and get back to you.

**Comment by Meghana-MSFT** [comment]
@Chang025 - We checked this at our end by following the above-mentioned doc.

1. We received an access token from the login service. 
![image](https://github.com/user-attachments/assets/9c6ac6d5-0b0c-466d-833e-b26928f9e26b)
2. Obtained the JWT token from the Microsoft Entra ID account login service response
![image](https://github.com/user-attachments/assets/d648e5ce-b46c-4253-ac37-1481d91ce4e5)
3. We then called the following endpoints by passing the access token received above - 

`GET https://login.botframework.com/v1/.well-known/openidconfiguration`

 and `GET https://login.botframework.com/v1/.well-known/keys` 
![image](https://github.com/user-attachments/assets/41d0f4cf-8aa2-40b9-aeea-363ecf158c21)


Could you please confirm if you are also checking the same?

**Comment by Chang025** [comment]
hi @Meghana-MSFT 
Thank you for the quick response. Yes, this is what we are also doing. If you need our azure bot details, we can send you over the email.
Thanks

**Comment by Meghana-MSFT** [comment]
Hi @Chang025 - Please share the details at microsoftteamsdev@microsoft.com.

**Comment by Chang025** [comment]
Hi @Meghana-MSFT - We are able to match the keyID now. Thank you for the quick resolution.
We can close this ticket.
