### ISSUE TITLE
Bot and/or app icons are not loading

### ISSUE THREAD

**Issue by 0x001122** [MicrosoftDocs/msteams-docs#11632]
### Steps to reproduce

Tested on macOS 14.6.1 (23G93) in Google Chrome Version 129.0.6668.58 (Official Build) (arm64)

1. Open a clean browser session (for example in a private window)
2. Connect to your Teams

### Expected behavior

Icons for bots and apps should be loaded in the Chat section.

### Actual behavior

Icons for bots and apps are not loaded and a generic blue placeholder image is displayed instead:

<img width="994" alt="" src="https://github.com/user-attachments/assets/84b408bb-61a6-47b6-8321-9fb73d5eb27c">

### Error details

In the browser console I get a lot of errors about some URLs not loading or throwing an error in some way:

<img width="1785" alt="" src="https://github.com/user-attachments/assets/804d346c-7fe3-40f1-bb6a-5403f22f019b">

```
Access to fetch at 'https://fr-prod.asyncgw.teams.microsoft.com/v1/url/content?url=https%3A%2F%2Fres.cdn.office.net%2Fteamsappdata%2Fevergreen-assets%2FThirdPartyApps%2F2f4dc505-8eae-4dad-ad92-c6fed9e4857b_largeImage.png%3Fv%3D3.1.22&v=&v=1' from origin 'https://teams.microsoft.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

```
GET https://fr-prod.asyncgw.teams.microsoft.com/v1/url/content?url=https%3A%2F%2Fres.cdn.office.net%2Fteamsappdata%2Fevergreen-assets%2FThirdPartyApps%2F2f4dc505-8eae-4dad-ad92-c6fed9e4857b_largeImage.png%3Fv%3D3.1.22&v=&v=1 net::ERR_FAILED
```

I've noticed that if I take a URL that is not loading, for example https://fr-prod.asyncgw.teams.microsoft.com/v1/url/content?url=https%3A%2F%2Fres.cdn.office.net%2Fteamsappdata%2Fevergreen-assets%2FThirdPartyApps%2F2f4dc505-8eae-4dad-ad92-c6fed9e4857b_largeImage.png%3Fv%3D3.1.22&v=&v=1, and add `/urlp` just after the domain name, for example https://fr-prod.asyncgw.teams.microsoft.com/urlp/v1/url/content?url=https%3A%2F%2Fres.cdn.office.net%2Fteamsappdata%2Fevergreen-assets%2FThirdPartyApps%2F2f4dc505-8eae-4dad-ad92-c6fed9e4857b_largeImage.png%3Fv%3D3.1.22&v=&v=1 then the URL is loading correctly in my browser.

There also seemed to be a similar issue recently that is now unfortunately closed: https://github.com/MicrosoftDocs/msteams-docs/issues/11580.

BTW we also get a lot of reports from our customer base (more than 50 reports in the last 2 months) and some of these users are using the latest version of Teams:

<img width="523" alt="" src="https://github.com/user-attachments/assets/7fa8b633-0161-4d70-8794-4dd2ce91a069">

Could you please investigate and fix the root issue? Thanks.

**Comment by Prasad-MSFT** [comment]
We tried to repro this, however at our end icons are rendering properly. (Teams Web/Desktop client)

`We have Microsoft Teams version 24267.1300.3136.8381. The client version is 49/24092313800.`

Could you please ensure that the server hosting the icons includes the Access-Control-Allow-Origin header in its response?
Check if there are any network restrictions or proxy settings that might be blocking the CORS headers.

**Comment by Prasad-MSFT** [comment]
@0x001122, could you please share the network trace showing these failing calls? Please share it at `microsoftteamsdev@microsoft.com`.

**Comment by Prasad-MSFT** [comment]
@0x001122, thanks for sharing the logs. We have raised an ICM for this issue and engineering team is looking into it. We will inform you once we have further update. Thanks!

**Comment by Prasad-MSFT** [comment]
Hi @0x001122 , according to latest update from engineering team the fix is in internal ring now. Once the fix is rolled out publicly, we will inform you in this thread. Thanks for understanding.

**Comment by Prasad-MSFT** [comment]
Hi @0x001122 , recently we got update from engineering team that the issue has been fixed and rolled out publicly. Please do verify and let us know.
