### ISSUE TITLE
[Update the note]

### ISSUE THREAD

**Issue by surbhigupta12** [MicrosoftDocs/msteams-docs#11643]
### Type of issue

Outdated article

### Feedback

Classic teams is already deprecated. Update the article.

### Page URL

https://learn.microsoft.com/en-us/microsoftteams/platform/resources/teams-updates

### Content source URL

https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/resources/teams-updates.md

### Author

@v-ypalikila

### Document Id

4c405ed3-f304-ff58-d32d-108fc725bb6a

**Comment by sayali-MSFT** [comment]
@surbhigupta12 -Could you please help us to update the document?
