### ISSUE TITLE
Doc Feedback - Doesn't show how to get Dev Tools to appear in the menu

### ISSUE THREAD

**Issue by v-preethah** [MicrosoftDocs/msteams-docs#11656]
### Type of issue

Other (describe below)

### Feedback

Hi,

We have received this as a Verbatim feedback, where the user isn't able to view the Dev Tools option as specified in the article. We tested and observed the same issue faced by the user.

Can you please check from your end and help us with a resolution or fix required here?

Thank you!

### Page URL

https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/developer-tools

### Content source URL

https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/tabs/how-to/developer-tools.md

### Author

@surbhigupta

### Document Id

a5b5782f-7031-a989-5e42-dd3010e18893

**Comment by Meghana-MSFT** [comment]
@v-preethah - We checked this at our end in Teams desktop, and we cannot see Open dev tools option. Could you please confirm if you are also checking in Teams desktop only and are you also facing the same issue? 

![image](https://github.com/user-attachments/assets/65e0a7b7-c967-4677-9957-5fd9f651f977)

**Comment by v-preethah** [comment]
Hi @Meghana-MSFT 
As specified already in the issue, I was facing the same issue as you have shared in the above screenshot.
