### ISSUE TITLE
Doc feedback - Problem when using the feedbackLoopEnabled = true

### ISSUE THREAD

**Issue by v-preethah** [MicrosoftDocs/msteams-docs#11657]
### Type of issue

Code doesn't work

### Feedback

Hi,

We have received this Verbatim feedback. Requesting you to please look into this and provide your inputs based on your testing.

**Feedback received:** I encountered problem when using the feedbackLoopEnabled = true.In mobile device Teams App, the thumbs up/down is visible, but in Desktop Teams App, some are able to view the thumbs up/down button, but most of my colleagues are not able to view.What would be the solution?Thanks.Regards,Hardono

### Page URL

https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/bot-messages-ai-generated-content?tabs=before%2Cbotmessage

### Content source URL

https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/bots/how-to/bot-messages-ai-generated-content.md

### Author

@surbhigupta

### Document Id

605a8486-6e6a-31d5-e8a1-021691206099

**Comment by Prasad-MSFT** [comment]
Hi @v-preethah, the original issue is being tracked [here](https://techcommunity.microsoft.com/t5/teams-developer/teams-bot-feedback-button-is-not-shown-to-most-of-the-user/m-p/4254898#M10857).
