### ISSUE TITLE
[Doc Update] Steps for how to Update the client secret SECRET_BOT_PASSWORD if it is expired for existing published application

### ISSUE THREAD

**Issue by ChetanSharma-msft** [MicrosoftDocs/msteams-docs#11665]
### Type of issue

Typo

### Feedback

Section can be updated: https://learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview#customize-debug-settings

Steps:
1) Create new Secret in app registration & keep it for later use
2) Update .env file for SECRET_BOT_PASSWORD and provision/deploy the application
3) If you app is already deployed, make sure your app service configuration in azure resource is also updated with newly created app/bot secret.

### Page URL

https://learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview

### Content source URL

https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/debug-overview.md

### Author

@surbhigupta

### Document Id

ade7805f-ba79-1de6-1a0d-7cc3e221c5d8

**Comment by Prasad-MSFT** [comment]
Hi @surbhigupta12 , could you please help here to update the document as suggested?
