### ISSUE TITLE
Can't logout account

### ISSUE THREAD

**Issue by KayMKM** [MicrosoftDocs/msteams-docs#1166]
Once I login with an account, it can't be log out anymore. I think Teams should have a "Clear state" feature like the emulator. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63519845-323f-be8f-ce15-d7f39e46b5a7
* Version Independent ID: 70952f91-56e9-ff08-59f6-e237d4aaeca9
* Content: [Add authentication to your Teams bot - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/authentication/add-authentication#feedback)
* Content Source: [msteams-platform/bots/how-to/authentication/add-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/bots/how-to/authentication/add-authentication.md)
* Product: **msteams**
* GitHub Login: @clearab
* Microsoft Alias: **anclear**

**Comment by Trinetra-MSFT** [comment]
@KayMKM , Could you please try to clear your team's cache and do a hard refresh?

**Comment by KayMKM** [comment]
How can I clear the cache?

**Comment by Trinetra-MSFT** [comment]
@KayMKM , 
1. Quit Microsoft Teams
2. Delete or rename the following directory/folder:

> %AppData%\Microsoft\Teams\IndexedDB
3. Start Microsoft Teams.
The folder you renamed or deleted will be recreated and a fresh cache will be downloaded from the service

**Comment by Gousia-MSFT** [comment]
Please re-open if you are still facing an issue.
