### ISSUE TITLE
Application hosted media bot can be deployed on-prem or not ?

### ISSUE THREAD

**Issue by omerv-gongio** [MicrosoftDocs/msteams-docs#11675]
### Type of issue

Missing information

### Feedback

Hi,
there are 2 sentences that contradict each other
"The bot must be deployed on a Windows Server on-premises machine or"
and later in the page -
"The bot must be developed using C# and the standard .NET Framework, and deployed on Microsoft Azure."

So not sure if it's possible to develop a bot that runs on-prem or not ..

### Page URL

https://learn.microsoft.com/en-us/microsoftteams/platform/bots/calls-and-meetings/requirements-considerations-application-hosted-media-bots

### Content source URL

https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/bots/calls-and-meetings/requirements-considerations-application-hosted-media-bots.md

### Author

@surbhigupta

### Document Id

a8b8d285-955f-1f86-1484-6a75aa8ffaf8

**Comment by ChetanSharma-msft** [comment]
Hello @omerv-gongio - Thanks for pointing out the contradiction in the documentation. 

After reviewing it, it seems that while **on-premises deployment on a Windows Server is possible**, **Azure is the recommended and more supported option** for deploying the application-hosted media bot.

If you are specifically looking for the steps to deploy it to on-promises, we will check with engineering team and let you know?

**Comment by omerv-gongio** [comment]
Hi @ChetanSharma-msft,
we would definitely prefer to deploy it in our existing data center.
If there are extra steps needed to achieve that, any information on the subject would be helpful.
Thanks

**Comment by ChetanSharma-msft** [comment]
Hello @omerv-gongio - We got inputs from engineering team that:
**"Production application-hosted media bots must be deployed on a Windows Server guest Operating System (OS) in Azure; non-production (i.e., development/testing-only) bots may be deployed on a Windows Server on-premise machine."**

We will update this content in documentation in place of below: 
"The bot must be deployed on a Windows Server on-premises machine or a Windows Server guest Operating System (OS) in Azure."

Also, we do not recommend running production app-hosted media bots on-premises.
Still, I will check with engineering team if we have any official documentation or steps to test app on-premises and let you know.

**Comment by ChetanSharma-msft** [comment]
> Hello @omerv-gongio - We got inputs from engineering team that: **"Production application-hosted media bots must be deployed on a Windows Server guest Operating System (OS) in Azure; non-production (i.e., development/testing-only) bots may be deployed on a Windows Server on-premise machine."**
> 
> We will update this content in documentation in place of below: "The bot must be deployed on a Windows Server on-premises machine or a Windows Server guest Operating System (OS) in Azure."
> 
> Also, we do not recommend running production app-hosted media bots on-premises. Still, I will check with engineering team if we have any official documentation or steps to test app on-premises and let you know.

Hello @surbhigupta12 - Please help to update the documentation here:
https://learn.microsoft.com/en-us/microsoftteams/platform/bots/calls-and-meetings/requirements-considerations-application-hosted-media-bots

![image](https://github.com/user-attachments/assets/bf38c785-3319-45b9-84b4-705b1be6075e)
