### ISSUE TITLE
Voicemail Flow Hangs App on iOS

### ISSUE THREAD

**Issue by marmstrong94** [MicrosoftDocs/msteams-docs#1168]
In iOS App version 1.0.89, call flow options the app has a chance of indefinitely hanging under the right circumstances, forcing the user to force the app closed and reopen.

To reproduce:
1. Pull out sidebar > Settings > Calling > If unanswered > If unselected, select Voicemail.
2. Press Voicemail again, the app will draw an animated loading circle indefinitely.
3. The app must be forced closed.

**Comment by Gousia-MSFT** [comment]
@marmstrong94 Is this related to Microsoft Teams? Could you please share a video recording of the issue?

**Comment by Gousia-MSFT** [comment]
Please re-open with requested information if you are still facing the issue.
