### ISSUE TITLE
Message Extensions - description is incorrect for AI and data is repeated.

### ISSUE THREAD

**Issue by Jegadeesh-MSFT** [MicrosoftDocs/msteams-docs#11680]
### Type of issue

Other (describe below)

### Feedback

1. The **Message Extensions** description only covers the Bot Framework SDK and does not include details about the changes implemented in the Teams AI library.

Link : https://review.learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/teams-conversational-ai/how-conversation-ai-core-capabilities?branch=pr-en-us-11620&tabs=dotnet6%2Cdotnet5%2Cdotnet4%2Cjavascript3%2Cdotnet2%2Cdotnet1#message-extensions

![image](https://github.com/user-attachments/assets/d7e1dd97-59c1-4f9e-854c-6c2ae78830e6)

2. The **Message Extension Query** appears to be an extension of the **Message Extensions** topic, as both refer to the same code. Please consider to merge them.

Link : https://review.learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/teams-conversational-ai/how-conversation-ai-core-capabilities?branch=pr-en-us-11620&tabs=dotnet6%2Cdotnet5%2Cdotnet4%2Cjavascript3%2Cdotnet2%2Cdotnet1#message-extension-query

### Page URL

https://review.learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/teams-conversational-ai/how-conversation-ai-core-capabilities?branch=pr-en-us-11620&tabs=dotnet6%2Cdotnet5%2Cdotnet4%2Cjavascript3%2Cdotnet2%2Cdotnet1

### Content source URL

https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/bots/how-to/teams-conversational-ai/how-conversation-ai-core-capabilities.md

### Author

@surbhigupta

### Document Id

226bf6e8-973b-b31f-1d29-510c32ff899a

**Comment by Meghana-MSFT** [comment]
Thank you for reporting this, we will check this and get back to you.
