### ISSUE TITLE
Continuation Passing Style in Sample

### ISSUE THREAD

**Issue by beauzeaux** [MicrosoftDocs/msteams-docs#1169]
Given that [Promises](https://developer.mozilla.org/en-US/docs/web/javascript/reference/global_objects/promise) have been a part of the ECMA script spec for a while now, the `authContext._renewIdToken` there should at least be a demonstration of how to wrap it in a Promise. 

E.G. 
```js
new Promise((resolve, reject) => authContext._renewIdToken((err, idToken) => !!err ? reject(err) : resolve(idToken)))
```

This would let the call integrate with the async/await from Babble/Typescript. 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2e66ffa-ec00-4a84-a43d-d47e3c138b32
* Version Independent ID: 47e9a383-ac6a-dc7d-2d91-a9e09626fdab
* Content: [Silent authentication - Teams](https://docs.microsoft.com/en-au/microsoftteams/platform/tabs/how-to/authentication/auth-silent-aad)
* Content Source: [msteams-platform/tabs/how-to/authentication/auth-silent-aad.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tabs/how-to/authentication/auth-silent-aad.md)
* Product: **msteams**
* GitHub Login: @clearab
* Microsoft Alias: **anclear**

**Comment by Trinetra-MSFT** [comment]
Thanks for your suggestion. We will look into this.
