### ISSUE TITLE
Doc Bug

### ISSUE THREAD

**Issue by surbhigupta12** [MicrosoftDocs/msteams-docs#11718]
### Type of issue

Missing information

### Feedback

Partner is trying to update the apple developer id in the partner center, and following the steps documented here: [Enable App for Teams iOS Platform - Teams | Microsoft Learn](https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/update-apple-store-team-connect-id)
 
However, they don't see the option to update. Could you please help confirm if anything has changed here as to why partner is not able to view the option to update.

![image](https://github.com/user-attachments/assets/aa877cb2-4d1d-46df-8d71-4154a81c61ce)

### Page URL

https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/update-apple-store-team-connect-id

### Content source URL

https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/deploy-and-publish/appsource/prepare/update-apple-store-team-connect-id.md

### Author

@heath-hamilton

### Document Id

172e8faf-0fb4-7e39-4c61-75be6b03d1a0

**Comment by sayali-MSFT** [comment]
Thanks for reporting your issue.
We will check this at our end and will get back to you.
