### ISSUE TITLE
Adaptive Cards - can you help me to confirm if it's support in BOTFRAMEWORK-WEBCHAT?

### ISSUE THREAD

**Issue by ChetanSharma-msft** [MicrosoftDocs/msteams-docs#11729]
### Steps to reproduce

Copied from: https://github.com/microsoft/AdaptiveCards/issues/8956
Posted by: @vponcet-sg

Details:
We are building an app and we are facing issue with adaptive cards .
adaptiveC
![image](https://github.com/user-attachments/assets/d1a0edd7-0289-42a4-ab8b-2fa4a2ced84e)
![image](https://github.com/user-attachments/assets/c825339f-494b-4bb0-b912-13e7b2c6c0c9)

![image](https://github.com/user-attachments/assets/c825339f-494b-4bb0-b912-13e7b2c6c0c9)could ![image](https://github.com/user-attachments/assets/a447ec89-9b0e-4986-b424-b0f676a1aed6)
could you explain why we are facing this issue ?
URL: https://adaptivecards.io/samples/

### Expected behavior

NA

### Actual behavior

adaptive cards - can you help me to confirm if it s support in BOTFRAMEWORK-WEBCHAT ?

**Comment by Prasad-MSFT** [comment]
Hi @vponcet-sg, could you please share the adaptive card JSON? And please let us know if it is rendering fine in MS Teams or not.
As per our understanding the card is not rendering in Webchat, are we correct?
