### ISSUE TITLE
Action based message extension with SSO

### ISSUE THREAD

**Issue by ChetanSharma-msft** [MicrosoftDocs/msteams-docs#11732]
### Steps to reproduce

Copied from: https://github.com/OfficeDev/teams-toolkit-samples/issues/1284

Details:

I'm implementing an action-based message extension (three dots on the message in a chat).

How can I add SSO in order to get the user token in the TeamsActivityHandler methods?

The example for search-based message extension shows how to do it (handleTeamsMessagingExtensionQuery and handleMessageExtensionQueryWithSSO), but there are no examples on how to do it with action based methods (handleTeamsMessagingExtensionSubmitAction).

Thanks!

### Expected behavior

NA

### Actual behavior

NA

**Comment by Meghana-MSFT** [comment]
@jamzi - Could you please let us know if this comment resolved your issue? https://github.com/OfficeDev/teams-toolkit-samples/issues/1284#issuecomment-2298031280
