### ISSUE TITLE
Feedback avenue - Code snippets in JavaScript required

### ISSUE THREAD

**Issue by v-preethah** [MicrosoftDocs/msteams-docs#11738]
### Type of issue

Other (describe below)

### Feedback

**Verbatim feedback**: I would like to see Javascript examples for the React tab I'm building (.jsx) rather than Typescript examples (.ts)

**Doc Team Ask**: Requesting to please provide code snippets in JavaScript to update the document.

### Page URL

https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/build-a-dashboard-tab-app

### Content source URL

https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/tabs/how-to/Build-a-dashboard-tab-app.md

### Author

@v-silakshmi

### Document Id

4e5ad801-f835-7e94-fe49-fab64930e662

**Comment by Prasad-MSFT** [comment]
Thanks for raising the issue. We will check this internally at our end and will update you accordingly.

**Comment by v-ramyas5** [comment]
Hi @Prasad-MSFT and @Meghana-MSFT,
Gentle reminder to update us on when can we expect the code snippets.

**Comment by V-bvishnu5** [comment]
Hi @Prasad-MSFT and @Meghana-MSFT,
Gentle reminder to update us on when we can expect the code snippets.

**Comment by Prasad-MSFT** [comment]
Hi @V-bvishnu5 , the code snippets have been shared in our internal channel thread. Please check and update.
