### ISSUE TITLE
[Dev support]: Can't debug individual function calls

### ISSUE THREAD

**Issue by ChetanSharma-msft** [MicrosoftDocs/msteams-docs#11733]
### Steps to reproduce

Copied from: https://github.com/microsoft/teams-ai/issues/2063
Posted by: @stokedout

Details:
How can I debug the function calls made by this sample? If I add breakpoints to the method body of each of the @app.ai.action("...") nothing happens
https://github.com/microsoft/teams-ai/blob/main/python/samples/04.ai.d.chainedActions.listBot/src/bot.py#L74-L123

### Expected behavior

NA

### Actual behavior

NA

**Comment by Prasad-MSFT** [comment]
Hi @stokedout, thanks for raising your issue. Could you please let us know if this issue is specific to Python sample or is it happening with others aswell?
