### ISSUE TITLE
Teams AI Library - Programming languages

### ISSUE THREAD

**Issue by macerru** [MicrosoftDocs/msteams-docs#11740]
### Type of issue

Missing information

### Feedback

Docs reference JavaSccript and C# as the programming languages for Teams AI Library, but samples are also available in Python. 

### Page URL

https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/teams-conversational-ai/teams-conversation-ai-overview

### Content source URL

https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/bots/how-to/teams-conversational-ai/teams-conversation-ai-overview.md

### Author

@michaelmaillot

### Document Id

177cc18e-15ad-7c36-3604-083914c1ceea

**Comment by sayali-MSFT** [comment]
@macerru -Thanks for reporting your issue.
We will check this at our end and will get back to you.

**Comment by sayali-MSFT** [comment]
@macerru - We are opening a new issue here, as the repository is not within our scope-
Please track it from here-
https://github.com/microsoft/teams-ai/issues/2152

We are closing this issue for now, please feel free to reopen it, if required.
