### ISSUE TITLE
Deep Link to Files Tab

### ISSUE THREAD

**Issue by vladschiop** [MicrosoftDocs/msteams-docs#1174]
How can I get the information to create a deep link to a channel's Files tab? I tried to retrieve the tabs from a channel using Graph Api (List tabs in channel), but the Files tab is missing from the response.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45541337-ecd7-5cf6-cbe4-3f0d2f39aa79
* Version Independent ID: 6b4203f0-2844-06c9-eaa3-9cc03e6f76c0
* Content: [Create deep links - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links)
* Content Source: [msteams-platform/concepts/build-and-test/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/build-and-test/deep-links.md)
* Product: **msteams**
* GitHub Login: @clearab
* Microsoft Alias: **anclear**

**Comment by Gousia-MSFT** [comment]
@vladschiop Currently we do not have this documented anywhere. This is in our backlog and we are working on it.

**Comment by vladschiop** [comment]
@Gousia-MSFT is not implemented or just not documented? Thank you!

**Comment by Gousia-MSFT** [comment]
@vladschiop It is just not documented. Here is a sample format for deeplink to files.
https://teams.microsoft.com/l/file/5E0154FC-F2B4-4DA5-8CDA-F096E72C0A80?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&fileType=pptx&objectUrl=https%3A%2F%2Fmicrosoft.sharepoint.com%2Fteams%2FActionPlatform%2FShared%20Documents%2FFC7-%20Bot%20and%20Action%20Infra%2FKaizala%20Actions%20in%20Adaptive%20Cards%20-%20Deck.pptx&baseUrl=https%3A%2F%2Fmicrosoft.sharepoint.com%2Fteams%2FActionPlatform&serviceName=teams&threadId=19:f8fbfc4d89e24ef5b3b8692538cebeb7@thread.skype&groupId=ae063b79-5315-4ddb-ba70-27328ba6c31e
This is the serialization of this object:
```
{
tenantId: “72f988bf-86f1-41af-91ab-2d7cd011db47”,
filetype: = “pptx”,
objectUrl: “https://microsoft.sharepoint.com/teams/ActionPlatform/Shared Documents/FC7- Bot and Action Infra/Kaizala Actions in Adaptive Cards - Deck.pptx”,
baseUrl: “https://microsoft.sharepoint.com/teams/ActionPlatform”,
serviceName: “teams”,
threadId: = “19:f8fbfc4d89e24ef5b3b8692538cebeb7@thread.skype”,
groupId: “ae063b79-5315-4ddb-ba70-27328ba6c31e”
}
```

**Comment by pmeripe** [comment]
Hello, is there a way to open new chat window, I mean blank window?
