### ISSUE TITLE
[Doc-Enhancement-Request] (Tabs) Enhanced Formatting, Simplified Explanations, Section Highlights etc.

### ISSUE THREAD

**Issue by ChetanSharma-msft** [MicrosoftDocs/msteams-docs#11753]
### Type of issue

Other (describe below)

### Feedback

We can do few improvements in the documentation for better readability:

1) We can add heading like Overview or Significance of Tabs:
![image](https://github.com/user-attachments/assets/baee7cf1-33f3-4c1f-85c9-099b3efd6131)
 Like below:
 
![image](https://github.com/user-attachments/assets/1cf61409-7e78-48e7-8a58-ac6e95bb2043)

2) We can add heading like: "Types of Tabs" here & Separate list items for Personal and Configurable tabs:
![image](https://github.com/user-attachments/assets/f0e1423b-5dc5-40c8-90d7-c0565c55a885)

Similar to this: 
![image](https://github.com/user-attachments/assets/36c19ac6-b4d5-4d71-b347-fea54f5e2f86)

![image](https://github.com/user-attachments/assets/7b35680f-b869-4bfa-aeb4-7dab4787b14e)

3) We can put this line as Note in the documentation:
![image](https://github.com/user-attachments/assets/4d861874-1d84-4e4b-b3a0-0d8b41cac8d9)

Note
Personal (static) tabs now support group chat, channel, and meeting scopes with a [customizable experience](https://github.com/MicrosoftDocs/msteams-docs/issues/~/tabs/how-to/create-personal-tab.md#extend-static-tabs-to-group-chat-channels-and-meetings).

4) We can put Usage scenarios as table format here:
![image](https://github.com/user-attachments/assets/6646c43e-2458-4858-a1c8-c112157a8521)

Like this:
![image](https://github.com/user-attachments/assets/53f1eacd-c4d2-4c5d-bd17-f2d9a7c4daf4)

5) This section can be come later after "Tabs user scenarios" section;
![image](https://github.com/user-attachments/assets/ef5b40e8-6e3b-48fe-8605-a67a12014132)

6) Below header can be like: "Creating Tabs"
![image](https://github.com/user-attachments/assets/5401833a-4e59-4d45-bd21-d07df0826800)

7) Below link is not working "404 NOT FOUND" Error:
![image](https://github.com/user-attachments/assets/b355346d-fa5b-4154-97d0-ddb3e6e20252)

8) What this note is indicating? it's not clear and we can add some article link to explain this:
![image](https://github.com/user-attachments/assets/86c3488d-6b81-4201-9ed5-1e13f4290621)

Also, this note can be put at top of section or bottom.

9) In below section we can separate out Static and configurable sections or as a list item while explaining it:
https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs?tabs=personal#declare-custom-tab-in-app-manifest

Something like this:
![image](https://github.com/user-attachments/assets/3bc8809f-1bb9-4327-acca-e44e13db0745)

10) This section can be updated like below: 
https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs?tabs=personal#tools-to-build-tabs
![image](https://github.com/user-attachments/assets/44bddfff-5eec-44aa-b0cc-ccacaa11781f)

11) This section can also be updated:
https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs?tabs=personal#next-step

![image](https://github.com/user-attachments/assets/63931299-2aef-4dcf-9a9f-1febd70f33f5)

12) This can also be improved:
![image](https://github.com/user-attachments/assets/b4b86517-a515-4acb-9581-32bfcf986a4f)

Can be updated as proper heading: 
![image](https://github.com/user-attachments/assets/da59141b-d666-42e0-934e-1b3c1e510d02)

13) This table of contents can also be improved after adding few more sections:
![image](https://github.com/user-attachments/assets/8ae57a5e-3d7a-4928-9d71-852ee047a835)

Ideally first link should be overview of Tabs and then Features and other section links.

### Page URL

https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs?tabs=personal

### Content source URL

https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/tabs/what-are-tabs.md

### Author

@surbhigupta

### Document Id

c1b86714-5b2e-79a8-5761-0fb2fd5746c0

**Comment by sayali-MSFT** [comment]
@surbhigupta12 -Could you please help us to update the document?

**Comment by ChetanSharma-msft** [comment]
We will be raising separate issues for these formatting's and others for all docs.
Closing this issue for now.
