### ISSUE TITLE
"post a workflow.." link is broken

### ISSUE THREAD

**Issue by Peter-Wxin** [MicrosoftDocs/msteams-docs#11752]
### Type of issue

Missing information

### Feedback

[post a workflow when a webhook request is received in Microsoft Teams.](https://prod.support.services.microsoft.com/en-us/office/post-a-workflow-when-a-webhook-request-is-received-in-microsoft-teams-8ae491c7-0394-4861-ba59-055e33f75498).
The link is broken. Could you fix it?

### Page URL

https://learn.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-incoming-webhook?tabs=newteams%2Cdotnet

### Content source URL

https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/webhooks-and-connectors/how-to/add-incoming-webhook.md

### Author

@surbhigupta

### Document Id

e3b53e27-2946-189c-623b-9df704ea8f12

**Comment by Prasad-MSFT** [comment]
Hi @surbhigupta12, this hyperlink is broken. Could you please help updating?
![image](https://github.com/user-attachments/assets/9c158fc8-57b3-449e-ade0-cc4502fdde18)



https://learn.microsoft.com/en-us/connectors/teams/?tabs=text1%2Cdotnet#when-a-teams-webhook-request-is-received

**Comment by v-ramyas5** [comment]
Hi @Prasad,
Observed that the current link in [post a workflow](https://support.microsoft.com/en-us/office/create-incoming-webhooks-with-workflows-for-microsoft-teams-8ae491c7-0394-4861-ba59-055e33f75498) **seems to be working**. Request your support to confirm whether to replace the present link with the shared link _https://learn.microsoft.com/en-us/connectors/teams/?tabs=text1%2Cdotnet#when-a-teams-webhook-request-is-received_.
In case, the present link is not working for you, kindly let us know.

**Comment by Prasad-MSFT** [comment]
Hi @v-ramyas5, the broken link is fixed now. Closing the issue as no action required further.

**Comment by surbhigupta12** [comment]
Removing the doc-bug label
