### ISSUE TITLE
[Doc-Enhancement-Request] (Message Extension) Enhanced Formatting, Simplified Explanations, Section Highlights etc.

### ISSUE THREAD

**Issue by ChetanSharma-msft** [MicrosoftDocs/msteams-docs#11760]
### Type of issue

Other (describe below)

### Feedback

We can do few improvements in the documentation for better readability:

1) This section can be updated like below:
![image](https://github.com/user-attachments/assets/f68081b2-21fd-4e44-a1d7-70d36c4f611d)

Message Extensions in Microsoft Teams
Message extensions allow users to interact with your web service directly from within the Microsoft Teams client. With these extensions, users can:

Search for information or initiate actions in an external system from various entry points, including:
The compose message area
The command box
Directly from a message
The results of these interactions can be seamlessly returned to the Teams client, appearing as richly formatted cards that enhance the user experience and provide valuable information at a glance.

![image](https://github.com/user-attachments/assets/f0f79b0b-c3ee-4288-ad86-7cb3c195beba)

2) Can we update this section as below:
https://learn.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/what-are-messaging-extensions?tabs=desktop#scenarios-where-message-extensions-are-used

![image](https://github.com/user-attachments/assets/636bbc4c-ae35-473e-b7f0-78ef6846ee0a)

Also, if we can add few more columns in it like: 
Benefits
User Interaction
Technical Requirements
Potential Use Cases

![image](https://github.com/user-attachments/assets/4556af29-d7ac-4c4f-903e-9666ed43f84b)
<html>
<body>
<h3>Scenarios Where Message Extensions Are Used</h3>
Scenario | Example | Benefits | User Interaction | Technical Requirements | Potential Use Cases
-- | -- | -- | -- | -- | --
Perform an Action in an External System | Reserve a resource and notify the channel about the reserved time slot. | Streamlines resource management and improves team awareness. | User clicks a button to reserve the resource. | API integration with resource management system. | Conference room booking, equipment reservation.
Search for Information and Share Results | Search for a work item in Azure DevOps and share the findings with the group as an Adaptive Card. | Facilitates quick access to relevant information, enhancing collaboration. | User types a query and selects a work item to share. | Azure DevOps API access and appropriate permissions. | Sharing bug reports, pulling in project status updates.
Complete a Complex Task Involving Multiple Steps | Create a bug in your tracking system based on a Teams message, assign that bug, and send a card with its details to the conversation thread. | Automates task management, ensuring accountability and clarity within the conversation. | User initiates the task through a form or button click. | API access to bug tracking system and necessary permissions. | Issue tracking, project management, customer support workflows.

</body>
</html>

3) Update below section:
https://learn.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/what-are-messaging-extensions?tabs=desktop#message-extension-commands-types

![image](https://github.com/user-attachments/assets/5d6c43e8-5dda-4647-a630-6669ace11701)
<html>
<body>
<h3>Message Extension Command Types</h3><p>There are two types of message extension commands in Microsoft Teams: <strong>Action Commands</strong> and <strong>Search Commands</strong>. Each command type defines the user interface (UI) elements and interaction flows available for your web service. Below is a breakdown of each command type along with their characteristics and use cases.</p>
Command Type | Description | UI Elements | Use Cases | Authentication and Configuration
-- | -- | -- | -- | --
Action Command | Allows users to perform specific actions, such as creating or updating content in an external service. | Forms, buttons, dialog prompts, and notification cards. | - Creating a new task in a project management tool.- Submitting a support request. | Action commands can incorporate authentication flows to validate users before performing actions.
Search Command | Enables users to search for information from an external service and return results within Teams. | Search boxes, result lists, and rich cards for displaying results. | - Searching for items in a catalog or database.- Retrieving work items from Azure DevOps. | Search commands can utilize authentication to access secure data while performing searches.

</body>
</html>

![image](https://github.com/user-attachments/assets/5f01e95c-b351-4241-9839-267e26149fe1)

Key Characteristics
User Interaction: The command type determines how users interact with the extension. Action commands typically require user input to complete a task, while search commands focus on retrieving and displaying data.

Data Handling: Each command type handles data differently. Action commands often involve sending data to an external service, while search commands retrieve and present existing data.

Common Scenarios
Action Command Example: A user may initiate a command to create a new meeting by filling out a form that collects details like time, date, and participants.

Search Command Example: A user searches for a product in an inventory system and receives a list of results that they can select and share with their team.

Authentication and Configuration
Both command types support authentication mechanisms and configuration settings that allow the web service to interact securely with users and their data. This ensures that users can only access or modify information for which they have permissions.

4) Can update below section as well:

https://learn.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/what-are-messaging-extensions?tabs=desktop#action-commands

Action Commands
Overview
Key Characteristics
Invocation Context
Example Usage

Something like this:
Action Commands
Overview
Action commands in Microsoft Teams provide a way to interactively collect or display information from users through a modal pop-up interface, often referred to as a task module. When users submit information via the form presented in the modal, the web service responds by posting a message directly into the conversation or into the compose message area, allowing the user to review and submit it later. For more complex scenarios, you can connect multiple forms to create a workflow.

Key Characteristics
User Interface: Action commands display a modal pop-up that allows users to enter data or view information. This modal can include various UI elements such as text boxes, dropdowns, and buttons.

Submission Flow: Upon submission, the data is sent to your web service, which processes it and posts the response in the appropriate context (either in the chat or in the compose message area).

Complex Workflows: You can design workflows that involve linking multiple action commands together, enabling a sequence of user interactions and data submissions.

Invocation Context
Action commands can be triggered from:

Compose Message Area: Users can invoke the command directly when composing a message.
Command Box: Users can type commands to access the action functionality.
Message Context: If invoked from a message, the initial JSON payload sent to your bot includes the entire message from which the action command was triggered.
Example Usage
Task Creation: A user invokes an action command to create a new task. They fill out a form with details such as task name, description, and due date. Upon submission, a message summarizing the task is posted in the chat.

Bug Report: A user initiates a bug reporting action command, fills out the bug details in the modal, and submits the form. The bot posts a card summarizing the bug report in the conversation for team visibility.

5) Table is not showing properly here:
![image](https://github.com/user-attachments/assets/b8d714be-00c0-432a-8554-996b7599e9a5)

ALso, we can update this table as below:
![image](https://github.com/user-attachments/assets/b54597a7-29a6-478b-83a2-79e4c86135d7)

6) We can update below section as:
https://learn.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/what-are-messaging-extensions?tabs=desktop#link-unfurling

Link Unfurling in Bot-Based Message Extensions
Feature Overview:

Purpose: Enables users to get enhanced information by unfurling URLs in the compose message area.
Supported For: Bot-based message extensions only.
Functionality: When a URL from a specified domain is pasted, it triggers a request to your web service. The service responds with a custom card that replaces the standard website preview.
Enhanced User Interaction: The unfurled card can include detailed information and interactive buttons, enabling users to take actions without leaving the Teams client.

Usage Flow:

User Action: A user pastes a URL from a monitored domain in the compose message area.
Invoke Message: Teams sends an invoke message to your bot, providing the URL and relevant context.
Service Response: Your bot returns a richly formatted card that displays additional information.
User Engagement: Buttons within the card allow users to interact directly, such as initiating workflows or accessing deeper content.

![image](https://github.com/user-attachments/assets/0695163b-e25f-4a65-850d-29a28ae50584)

### Page URL

https://learn.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/what-are-messaging-extensions?tabs=desktop

### Content source URL

https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/messaging-extensions/what-are-messaging-extensions.md

### Author

@surbhigupta

### Document Id

d5c2d24a-def4-af2e-7983-c73cf7f22934

**Comment by Nivedipa-MSFT** [comment]
@surbhigupta12 - Could you please help here to update the document here?

**Comment by ChetanSharma-msft** [comment]
We will be raising separate issues for these formatting's and others for all docs.
Closing this issue for now.
