### ISSUE TITLE
"Add AI label" to Bot Framework based bot does not work (python)

### ISSUE THREAD

**Issue by stokedout** [MicrosoftDocs/msteams-docs#11762]
### Steps to reproduce

1. Go to https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/bot-messages-ai-generated-content?tabs=before%2Cbotmessage#add-ai-label
2. Adapt the JavaScript example to Python
3. Run the bot and trigger a response.

e.g. of message sent

```
message_result = await turn_context.send_activity(
        Activity(
            type=ActivityTypes.message,
            text_format="markdown",
            text="hello",
            entities=[
                {
                    "type": "https://schema.org/Message",
                    "@type": "Message",
                    "@context": "https://schema.org",
                    "additionalType": ["AIGeneratedContent"],
                }
            ],
        )
    )
```

### Expected behavior

In Teams web the label shows on new messages

### Actual behavior

Message is sent but has no special labels

### Error details

There's no error. The label just doesn't appear.

**Comment by sayali-MSFT** [comment]
Hi @stokedout -Thank you for your inquiry about your Teams app development issue!
We will check this at our end and will get back to you.

**Comment by stokedout** [comment]
For context, my pyroject.toml file contains:

```
...
botbuilder-core = "^4.16.2"
botbuilder-schema = "^4.16.2"
botbuilder-ai = "^4.16.2"
botframework-connector = "^4.16.2"
...
teams-ai = "^1.4.1"
```

**Comment by sayali-MSFT** [comment]
@stokedout -Thank you for more information. We will try it from our end and let you know the update.
