### ISSUE TITLE
[Doc-Enhancement-Request] (Message Extension) Add Frequently Asked Questions (FAQ) on the documentation page.

### ISSUE THREAD

**Issue by ChetanSharma-msft** [MicrosoftDocs/msteams-docs#11761]
### Type of issue

Doc Enhancement

### Feedback

We can do few improvements in the documentation via adding FAQ's like below:

Frequently Asked Questions (FAQs)
**1. Why is my message extension not appearing in the Teams client?**
Solution: Ensure that the app manifest is correctly configured with your message extension’s invoke locations (e.g., compose message area, command box, message). Also, verify that your web service is registered as a bot in the Bot Framework and the necessary permissions are granted.

**2. How do I troubleshoot a failed command in a message extension?**
Solution: Check the HTTPS response sent by your web service. Ensure it contains a valid JSON payload and meets the Bot Framework schema requirements. You may also look at logs in the Bot Framework for details on failed commands.

**3. Can I use link unfurling without a bot-based message extension?**
Answer: No, link unfurling is exclusive to bot-based message extensions. Register your message extension as a bot and configure the domain URLs for link unfurling in the manifest.

**4. How can I test my message extension locally?**
Solution: Use ngrok to expose your local server to the internet, allowing the Teams client to communicate with your local service. Update the app manifest with the ngrok URL and sideload it into Teams.

**5. What should I do if the search command returns no results?**
Solution: Ensure that the API endpoint you’re calling is reachable and returns valid data. Check if your query parameters are correctly structured, and if your service uses caching, verify that cached data is not causing empty results.

**6. How do I handle authentication within a message extension?**
Answer: Both action and search commands support authentication. Use Azure AD to manage OAuth tokens for user verification, and include prompts or forms in the action command dialog to guide users through the authentication process.

**7. Is it possible to limit access to specific users or channels?**
Solution: Yes. Set specific permissions or apply Teams Graph API policies to control which users or groups have access to your message extension.

### Page URL

https://learn.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/what-are-messaging-extensions?tabs=desktop

### Content source URL

https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/messaging-extensions/what-are-messaging-extensions.md

### Author

@surbhigupta

### Document Id

d5c2d24a-def4-af2e-7983-c73cf7f22934

**Comment by Meghana-MSFT** [comment]
Hi @surbhigupta12 - Could you please add the above FAQs in the following doc - https://learn.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/what-are-messaging-extensions?tabs=desktop

**Comment by v-ramyas5** [comment]
Hi @ChetanSharma-msft,
Kindly confirm whether the all the 7 FAQs can be added as shared. Though, we will check for grammar and consistency, request your confirmation on the technical accuracy of the content present.

**Comment by ChetanSharma-msft** [comment]
We will be raising separate issues for these FAQ's for all docs.
Closing this issue for now.
