### ISSUE TITLE
Images not loading for "Create Identity Provider" in "Add Authentication for you teams bo"

### ISSUE THREAD

**Issue by rbakshi2** [MicrosoftDocs/msteams-docs#1176]
Instead of the images, there code showing up in docs

![image](https://user-images.githubusercontent.com/15854508/69764477-44906f80-1125-11ea-8f03-239c390fe4ed.png)

**Comment by Abhijit-MSFT** [comment]
Are you referring to these [documents](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-authentication?view=azure-bot-service-4.0&tabs=csharp)?

**Comment by laujan** [comment]
resolves #1176
