### ISSUE TITLE
Potential break in sequence from"Configuring idenity provider", to "Test connection string"

### ISSUE THREAD

**Issue by rbakshi2** [MicrosoftDocs/msteams-docs#1177]
![image](https://user-images.githubusercontent.com/15854508/69764655-fa5bbe00-1125-11ea-9539-a808f3d696fa.png)

So after configuring the idenitity provider with your bot, the next step mentioned is to test connection string; but right after the one hits 'save', the whole configuration tab collapeses, hence the user won't see the test connection tab anymore.

Would instead suggest to have a step to re open the Oath configuration tab, so the user has access to "test the connection" tab :)

**Comment by Abhijit-MSFT** [comment]
Are you referring to these [documents](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-authentication?view=azure-bot-service-4.0&tabs=csharp). 
After configuring the identity provider, you need to get into the newly created OAuth Connection and Test the Connection.
