### ISSUE TITLE
Page "Use external OAuth providers" needs to be noticed that "this approach is not suitable for web client"

### ISSUE THREAD

**Issue by heavenwing** [MicrosoftDocs/msteams-docs#11797]
### Type of issue

Missing information

### Feedback

Page "Use external OAuth providers" needs to be noticed that "this approach is not suitable for web client"
web client need to use another approach like window.open.

### Page URL

https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-oauth-provider

### Content source URL

https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/tabs/how-to/authentication/auth-oauth-provider.md

### Author

@surbhigupta

### Document Id

b608448b-3dd7-d5be-128c-da2859067140

**Comment by Nivedipa-MSFT** [comment]
@heavenwing - Thank you for your inquiry about your Teams app development issue! We will check and update the document accordingly.
