### ISSUE TITLE
Detect Teams Browser

### ISSUE THREAD

**Issue by bluego78** [MicrosoftDocs/msteams-docs#1180]
How can i detect if an application is loaded from teams or not?
I've tried to check te user agent, but it's Mozilla...
I can't find a solution

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8dfa1a29-bcf4-0cc5-ae3a-b185a00fd7bc
* Version Independent ID: c68181e1-151b-fc78-2671-fe9b397b702e
* Content: [Get context for your tab - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/access-teams-context#feedback)
* Content Source: [msteams-platform/tabs/how-to/access-teams-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tabs/how-to/access-teams-context.md)
* Product: **msteams**
* GitHub Login: @clearab
* Microsoft Alias: **anclear**

**Comment by Gousia-MSFT** [comment]
@bluego78 When a user sends a message in teams your bot receives an activity payload which contains the channel id. You can use that activity.channelId to see from where the application is loaded.
![image](https://user-images.githubusercontent.com/45553518/69844185-0e6ffe80-1291-11ea-8319-e92903fbe316.png)

**Comment by Gousia-MSFT** [comment]
Please re-open if you face any more issues.
