### ISSUE TITLE
Teams Approval app does not capture the reassignment, and it only captures the final approval, that info is not mentioned in the documentation

### ISSUE THREAD

**Issue by v-rajimandal** [MicrosoftDocs/msteams-docs#11812]
### Type of issue

Missing information

### Feedback

There is no documentation available related to Teams Approval app does not capture the reassignment details, and it only captures the final approval details in pdf export report.
For more details, please check the link.
https://sharepointstuff.com/2023/01/11/saving-approvals-as-pdfs-in-microsoft-teams/

### Page URL

https://learn.microsoft.com/en-us/microsoftteams/approval-admin#data-limitations

### Content source URL

https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/approval-admin.md

### Author

v-chinlana

### Document Id

c2ab90ad-0989-85f5-6b10-8ef631252e5c

**Comment by ChetanSharma-msft** [comment]
Hello @v-rajimandal,
Thanks for raising your query.

As this is a 1st part app developed by Microsoft, we recommend you raise the feedback here: https://feedbackportal.microsoft.com/feedback/forum/ad198462-1c1c-ec11-b6e7-0022481f8472

Thanks!!

**Comment by v-rajimandal** [comment]
Thanks For your response.

I have raised the query in provided URL.
In Teams Approval app, pdf export does not capture the reassignment details * Community<https://feedbackportal.microsoft.com/feedback/idea/ef945410-6fa2-ef11-95f6-0022484d7a88>

Regards,
Rajiv Mandal
Email: ***@***.******@***.***>
Active Hours: 8AM - 5:30PM IST(UTC+5.30)

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, please feel free to reopen it, if required.
