### ISSUE TITLE
what are the size limits

### ISSUE THREAD

**Issue by Josverl** [MicrosoftDocs/msteams-docs#1182]
what are the upper limits of the entity ID, Displayname and Urls ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97467996-693f-eb7b-10ed-7deaf4858718
* Version Independent ID: 8d69428f-965a-89b3-4561-f07655030397
* Content: [Settings interface - Teams](https://docs.microsoft.com/en-us/javascript/api/@microsoft/teams-js/microsoftteams.settings.settings?view=msteams-client-js-latest#entityid)
* Content Source: [nodejs/docs-ref-autogen/@microsoft/teams-js/microsoftTeams.settings.Settings.yml](https://github.com/OfficeDev/msteams-client-docs-ref-typescript/blob/live/nodejs/docs-ref-autogen/@microsoft/teams-js/microsoftTeams.settings.Settings.yml)
* Product: **msteams**
* GitHub Login: @charlesprakash
* Microsoft Alias: **o365devx**

**Comment by Trinetra-MSFT** [comment]
@Josverl, The max length for entity id is 64 and for name it is 128 
![image](https://user-images.githubusercontent.com/50989436/69844884-1e3d1200-1294-11ea-8cc6-49870cb8b816.png).

Please take a look at [Microsoft Schema Refrenece](https://developer.microsoft.com/en-us/json-schemas/teams/v1.5/MicrosoftTeams.schema.json)

**Comment by Josverl** [comment]
Thanks. Would it be possible to add a link to the schema ref to this page?

**Comment by Trinetra-MSFT** [comment]
Yes, You can provide schema reference within your app manifest. Please take a look at [Microsoft Schema Reference in manifest](https://github.com/OfficeDev/msteams-samples-hello-world-csharp/blob/master/Microsoft.Teams.Samples.HelloWorld.Web/Manifest/manifest.json)
