### ISSUE TITLE
Compliance Sample Bot VBSS no video received 

### ISSUE THREAD

**Issue by pavanjains** [MicrosoftDocs/msteams-docs#1186]
Hi, 
I am using compliance bot provided in the sample folder. I can get the video when I make video call however when just sharing content there is nothing received on vbss. Please help me how to further debug this. I am running the bot locally with *.wild.cert and ngrok tunneling the media and signaling.

Below is the logs from VS

'WaWorkerHost.exe' (CLR v4.0.30319: RdRuntime): Loaded 'C:\vbrick\microsoft-graph-comms-samples-master\Samples\BetaSamples\LocalMediaSamples\ComplianceRecordingBot\csx\Debug\roles\CRWorkerRole\approot\Microsoft.IdentityModel.Tokens.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'WaWorkerHost.exe' (CLR v4.0.30319: RdRuntime): Loaded 'C:\vbrick\microsoft-graph-comms-samples-master\Samples\BetaSamples\LocalMediaSamples\ComplianceRecordingBot\csx\Debug\roles\CRWorkerRole\approot\Microsoft.IdentityModel.Protocols.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'WaWorkerHost.exe' (CLR v4.0.30319: RdRuntime): Loaded 'C:\vbrick\microsoft-graph-comms-samples-master\Samples\BetaSamples\LocalMediaSamples\ComplianceRecordingBot\csx\Debug\roles\CRWorkerRole\approot\System.IdentityModel.Tokens.Jwt.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'WaWorkerHost.exe' (CLR v4.0.30319: RdRuntime): Loaded 'C:\vbrick\microsoft-graph-comms-samples-master\Samples\BetaSamples\LocalMediaSamples\ComplianceRecordingBot\csx\Debug\roles\CRWorkerRole\approot\Microsoft.IdentityModel.Logging.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'WaWorkerHost.exe' (CLR v4.0.30319: RdRuntime): Loaded 'C:\vbrick\microsoft-graph-comms-samples-master\Samples\BetaSamples\LocalMediaSamples\ComplianceRecordingBot\csx\Debug\roles\CRWorkerRole\approot\Microsoft.IdentityModel.JsonWebTokens.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
TraceSource Information: 0 : [SkypeBotsMediaPlatform][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] [CallId:4f1f0500-4c1f-4181-ab74-5678923bde69] Creating the RenderMediaSession for modality Audio
'WaWorkerHost.exe' (CLR v4.0.30319: RdRuntime): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Web.Extensions\v4.0_4.0.0.0__31bf3856ad364e35\System.Web.Extensions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
TraceSource Information: 0 : [SkypeBotsMediaPlatform][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] [CallId:4f1f0500-4c1f-4181-ab74-5678923bde69] Created the RenderMediaSession for modality Audio
TraceSource Information: 0 : [SkypeBotsMediaPlatform][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] [CallId:4f1f0500-4c1f-4181-ab74-5678923bde69] Created Audio Render Media Session
TraceSource Information: 0 : [SkypeBotsMediaPlatform][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] [CallId:4f1f0500-4c1f-4181-ab74-5678923bde69] Recvonly audio socket created
'WaWorkerHost.exe' (CLR v4.0.30319: RdRuntime): Loaded 'C:\vbrick\microsoft-graph-comms-samples-master\Samples\BetaSamples\LocalMediaSamples\ComplianceRecordingBot\csx\Debug\roles\CRWorkerRole\approot\Microsoft.Skype.Internal.Media.H264.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
TraceSource Information: 0 : [SkypeBotsMediaPlatform][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] [CallId:4f1f0500-4c1f-4181-ab74-5678923bde69] Creating the RenderMediaSession for modality Video
TraceSource Information: 0 : [SkypeBotsMediaPlatform][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] [CallId:4f1f0500-4c1f-4181-ab74-5678923bde69] Created the RenderMediaSession for modality Video
TraceSource Information: 0 : [SkypeBotsMediaPlatform][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] [CallId:4f1f0500-4c1f-4181-ab74-5678923bde69] Created Video Render Media Session
TraceSource Information: 0 : [SkypeBotsMediaPlatform][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] [CallId:4f1f0500-4c1f-4181-ab74-5678923bde69] Recvonly video socket created with mediaType: Video
TraceSource Information: 0 : [SkypeBotsMediaPlatform][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] [CallId:4f1f0500-4c1f-4181-ab74-5678923bde69] Creating the RenderMediaSession for modality Video
TraceSource Information: 0 : [SkypeBotsMediaPlatform][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] [CallId:4f1f0500-4c1f-4181-ab74-5678923bde69] Created the RenderMediaSession for modality Video
TraceSource Information: 0 : [SkypeBotsMediaPlatform][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] [CallId:4f1f0500-4c1f-4181-ab74-5678923bde69] Created Video Render Media Session
TraceSource Information: 0 : [SkypeBotsMediaPlatform][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] [CallId:4f1f0500-4c1f-4181-ab74-5678923bde69] Recvonly video socket created with mediaType: Video
TraceSource Information: 0 : [SkypeBotsMediaPlatform][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] [CallId:4f1f0500-4c1f-4181-ab74-5678923bde69] Creating the RenderMediaSession for modality Video
TraceSource Information: 0 : [SkypeBotsMediaPlatform][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] [CallId:4f1f0500-4c1f-4181-ab74-5678923bde69] Created the RenderMediaSession for modality Video
TraceSource Information: 0 : [SkypeBotsMediaPlatform][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] [CallId:4f1f0500-4c1f-4181-ab74-5678923bde69] Created Video Render Media Session
TraceSource Information: 0 : [SkypeBotsMediaPlatform][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] [CallId:4f1f0500-4c1f-4181-ab74-5678923bde69] Recvonly video socket created with mediaType: Video
TraceSource Information: 0 : [SkypeBotsMediaPlatform][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] [CallId:4f1f0500-4c1f-4181-ab74-5678923bde69] Creating the RenderMediaSession for modality Video
TraceSource Information: 0 : [SkypeBotsMediaPlatform][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] [CallId:4f1f0500-4c1f-4181-ab74-5678923bde69] Created the RenderMediaSession for modality Video
TraceSource Information: 0 : [SkypeBotsMediaPlatform][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] [CallId:4f1f0500-4c1f-4181-ab74-5678923bde69] Created Video Render Media Session
TraceSource Information: 0 : [SkypeBotsMediaPlatform][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] [CallId:4f1f0500-4c1f-4181-ab74-5678923bde69] Creating Video SourceProvider and attaching to consumer
TraceSource Information: 0 : [SkypeBotsMediaPlatform][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] [CallId:4f1f0500-4c1f-4181-ab74-5678923bde69] Created Video SourceProvider and attached to consumer
TraceSource Information: 0 : [SkypeBotsMediaPlatform][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] [CallId:4f1f0500-4c1f-4181-ab74-5678923bde69] Recvonly video socket created with mediaType: Vbss
TraceSource Information: 0 : [SkypeBotsMediaPlatform][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] [CallId:4f1f0500-4c1f-4181-ab74-5678923bde69] Created MPMediaSession with ID: a1b9a51b-1b43-4464-af33-16c13adf59d5
TraceSource Information: 0 : [SkypeBotsMediaPlatform][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] [CallId:4f1f0500-4c1f-4181-ab74-5678923bde69] Binding MPMediaSession Id a1b9a51b-1b43-4464-af33-16c13adf59d5 to the VideoSocket: 0
TraceSource Information: 0 : [SkypeBotsMediaPlatform][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] [CallId:4f1f0500-4c1f-4181-ab74-5678923bde69] Binding MPMediaSession Id a1b9a51b-1b43-4464-af33-16c13adf59d5 to the VideoSocket: 1
TraceSource Information: 0 : [SkypeBotsMediaPlatform][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] [CallId:4f1f0500-4c1f-4181-ab74-5678923bde69] Binding MPMediaSession Id a1b9a51b-1b43-4464-af33-16c13adf59d5 to the VideoSocket: 2
TraceSource Information: 0 : [SkypeBotsMediaPlatform][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] [CallId:4f1f0500-4c1f-4181-ab74-5678923bde69] Binding MPMediaSession Id a1b9a51b-1b43-4464-af33-16c13adf59d5 to the VbssSocket
TraceSource Information: 0 : [SkypeBotsMediaPlatform][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] [CallId:4f1f0500-4c1f-4181-ab74-5678923bde69] Binding MPMediaSession Id a1b9a51b-1b43-4464-af33-16c13adf59d5 to the media Sockets
TraceSource Information: 0 : [SkypeBotsMediaPlatform][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] [CallId:4f1f0500-4c1f-4181-ab74-5678923bde69] Adding a reference on MPMediaSession with ID: a1b9a51b-1b43-4464-af33-16c13adf59d5
TraceSource Information: 0 : [SkypeBotsMediaPlatform][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] [CallId:4f1f0500-4c1f-4181-ab74-5678923bde69] VideoSocket with Id 0 is bound to the mpMediaSession with id a1b9a51b-1b43-4464-af33-16c13adf59d5
TraceSource Information: 0 : [SkypeBotsMediaPlatform][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] [CallId:4f1f0500-4c1f-4181-ab74-5678923bde69] Adding a reference on MPMediaSession with ID: a1b9a51b-1b43-4464-af33-16c13adf59d5
TraceSource Information: 0 : [SkypeBotsMediaPlatform][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] [CallId:4f1f0500-4c1f-4181-ab74-5678923bde69] VideoSocket with Id 1 is bound to the mpMediaSession with id a1b9a51b-1b43-4464-af33-16c13adf59d5
TraceSource Information: 0 : [SkypeBotsMediaPlatform][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] [CallId:4f1f0500-4c1f-4181-ab74-5678923bde69] Adding a reference on MPMediaSession with ID: a1b9a51b-1b43-4464-af33-16c13adf59d5
TraceSource Information: 0 : [SkypeBotsMediaPlatform][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] [CallId:4f1f0500-4c1f-4181-ab74-5678923bde69] VideoSocket with Id 2 is bound to the mpMediaSession with id a1b9a51b-1b43-4464-af33-16c13adf59d5
TraceSource Information: 0 : [SkypeBotsMediaPlatform][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] [CallId:4f1f0500-4c1f-4181-ab74-5678923bde69] Adding a reference on MPMediaSession with ID: a1b9a51b-1b43-4464-af33-16c13adf59d5
TraceSource Information: 0 : [SkypeBotsMediaPlatform][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] [CallId:4f1f0500-4c1f-4181-ab74-5678923bde69] Adding a reference on MPMediaSession with ID: a1b9a51b-1b43-4464-af33-16c13adf59d5
TraceSource Information: 0 : [SkypeBotsMediaPlatform][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] [CallId:4f1f0500-4c1f-4181-ab74-5678923bde69] VideoSocket with Id 0 is bound to the mpMediaSession with id a1b9a51b-1b43-4464-af33-16c13adf59d5
TraceSource Information: 0 : [SkypeBotsMediaPlatform][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] [CallId:4f1f0500-4c1f-4181-ab74-5678923bde69] MpMediaSession a1b9a51b-1b43-4464-af33-16c13adf59d5 is bound to all the media sockets
TraceSource Information: 0 : [SkypeBotsMediaPlatform][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] [CallId:4f1f0500-4c1f-4181-ab74-5678923bde69] Created the media configuration: {{
  "mpUri": "net.tcp://pavan-media.vbrick.com:25605/MediaProcessor",
  "audioRenderContexts": [
    "ddf09ac0-56c2-4d94-ad67-60a23e44592d"
  ],
  "videoRenderContexts": [
    "b1ba9d2f-156e-4d5a-a233-bfe4ecb3751c",
    "25faa1ec-d8ab-44cf-ab5e-bd730e4e0bb9",
    "aafa8aba-5a2a-4b8a-b95b-ee19766285d4"
  ],
  "vbssRenderContexts": [
    "744ac21b-f816-4ae2-b980-7a118e499dc6"
  ],
  "audioSourceContexts": [
    null
  ],
  "videoSourceContexts": [],
  "vbssSourceContexts": [
    "a5b51576-78d7-4627-8b97-ed3d624690fa"
  ],
  "dataRenderContexts": null,
  "dataSourceContexts": null,
  "supportedAudioFormat": "Pcm16K",
  "videoSinkEncodingFormats": [
    "H264",
    "H264",
    "H264"
  ],
  "vbssSinkEncodingFormats": [
    "H264"
  ],
  "initialScreenSharingRole": "Viewer",
  "mpMediaSessionId": "a1b9a51b-1b43-4464-af33-16c13adf59d5",
  "regionAffinity": null,
  "skypeMediaBotsVersion": "1.13.1.0324",
  "mediaStackVersion": "2019.28.1.6",
  "mpVersion": "7.2.0.5523",
  "callId": "4f1f0500-4c1f-4181-ab74-5678923bde69"
}}
TraceSource Warning: 0 : [AvMP][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] TL_WARN(TF_COMPONENT) [EN-PJAIN]77864.27::12/02/2019-14:49:05.950.00000176 (AVMP,GetCapabilitiesWorkItemBegin:MediaProcessor.cs(1781)) [MP] MPProxy client's Service Contract version (63) is newer than current Service Contract Version (57).
TraceSource Warning: 0 : [AvMP][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] TL_WARN(TF_COMPONENT) [EN-PJAIN]77864.28::12/02/2019-14:49:07.045.000001F8 (AVMP,BeginCreateStream:Endpoint.cs(305)) [cid:efcb6dc8-a8f8-403f-9fe0-529131a7fe45]:[pid:5f97717f-b8d8-412d-a47a-34b2004b3ace][MP] Failed to get public ip mapping. Endpoint type  
TraceSource Warning: 0 : [AvMP][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] TL_WARN(TF_COMPONENT) [EN-PJAIN]77864.28::12/02/2019-14:49:07.416.00000270 (AVMP,BeginCreateStream:Endpoint.cs(305)) [cid:efcb6dc8-a8f8-403f-9fe0-529131a7fe45]:[pid:5f97717f-b8d8-412d-a47a-34b2004b3ace][MP] Failed to get public ip mapping. Endpoint type  
TraceSource Warning: 0 : [AvMP][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] TL_WARN(TF_COMPONENT) [EN-PJAIN]77864.28::12/02/2019-14:49:07.486.000002A7 (AVMP,BeginCreateStream:Endpoint.cs(305)) [cid:efcb6dc8-a8f8-403f-9fe0-529131a7fe45]:[pid:5f97717f-b8d8-412d-a47a-34b2004b3ace][MP] Failed to get public ip mapping. Endpoint type  
TraceSource Warning: 0 : [AvMP][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] TL_WARN(TF_COMPONENT) [EN-PJAIN]77864.28::12/02/2019-14:49:07.517.000002E2 (AVMP,BeginCreateStream:Endpoint.cs(305)) [cid:efcb6dc8-a8f8-403f-9fe0-529131a7fe45]:[pid:5f97717f-b8d8-412d-a47a-34b2004b3ace][MP] Failed to get public ip mapping. Endpoint type  
TraceSource Warning: 0 : [AvMP][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] TL_WARN(TF_COMPONENT) [EN-PJAIN]77864.28::12/02/2019-14:49:07.539.00000320 (AVMP,BeginCreateStream:Endpoint.cs(305)) [cid:efcb6dc8-a8f8-403f-9fe0-529131a7fe45]:[pid:5f97717f-b8d8-412d-a47a-34b2004b3ace][MP] Failed to get public ip mapping. Endpoint type  
TraceSource Information: 0 : [SkypeBotsMediaPlatform][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] [CallId:4f1f0500-4c1f-4181-ab74-5678923bde69] VideoSocket 0 Vbss: Not raising video receive status changed event, the VideoReceiveStatusChanged handler is null
TraceSource Information: 0 : [SkypeBotsMediaPlatform][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] [CallId:4f1f0500-4c1f-4181-ab74-5678923bde69] VideoSocket 2 Video: Not raising video receive status changed event, the VideoReceiveStatusChanged handler is null
TraceSource Information: 0 : [SkypeBotsMediaPlatform][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] [CallId:4f1f0500-4c1f-4181-ab74-5678923bde69] VideoSocket 1 Video: Not raising video receive status changed event, the VideoReceiveStatusChanged handler is null
TraceSource Information: 0 : [SkypeBotsMediaPlatform][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] [CallId:4f1f0500-4c1f-4181-ab74-5678923bde69] VideoSocket 0 Video: Not raising video receive status changed event, the VideoReceiveStatusChanged handler is null
TraceSource Warning: 0 : [AvMP][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] TL_WARN(TF_COMPONENT) [EN-PJAIN]77864.84::12/02/2019-14:49:08.125.0000058F (AVMP,ProcessMediaQualityChanged:Stream.cs(1864)) [cid:efcb6dc8-a8f8-403f-9fe0-529131a7fe45]:[pid:5f97717f-b8d8-412d-a47a-34b2004b3ace]Raising media quality changed event for Stream: cdc56851-7fe6-47b7-9b42-e95dee626493
TraceSource Warning: 0 : [AvMP][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] TL_WARN(TF_COMPONENT) [EN-PJAIN]77864.32::12/02/2019-14:49:08.165.000005BE (AVMP,ProcessMediaQualityChanged:Stream.cs(1864)) [cid:efcb6dc8-a8f8-403f-9fe0-529131a7fe45]:[pid:5f97717f-b8d8-412d-a47a-34b2004b3ace]Raising media quality changed event for Stream: 9a08bff7-199d-4010-8354-2294df96876f
'WaWorkerHost.exe' (CLR v4.0.30319: WaWorkerHost.exe): Loaded 'C:\vbrick\microsoft-graph-comms-samples-master\Samples\BetaSamples\LocalMediaSamples\ComplianceRecordingBot\csx\Debug\roles\CRWorkerRole\approot\Microsoft.Rtc.Internal.Media.MediaApi.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
TraceSource Warning: 0 : [AvMP][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] TL_WARN(TF_COMPONENT) [EN-PJAIN]77864.32::12/02/2019-14:49:08.187.000005C9 (AVMP,ProcessMediaQualityChanged:Stream.cs(1864)) [cid:efcb6dc8-a8f8-403f-9fe0-529131a7fe45]:[pid:5f97717f-b8d8-412d-a47a-34b2004b3ace]Raising media quality changed event for Stream: afdb75f6-e9c5-4175-9f06-5720bec0df23
TraceSource Warning: 0 : [AvMP][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] TL_WARN(TF_COMPONENT) [EN-PJAIN]77864.35::12/02/2019-14:49:08.213.0000060C (AVMP,ProcessMediaQualityChanged:Stream.cs(1864)) [cid:efcb6dc8-a8f8-403f-9fe0-529131a7fe45]:[pid:5f97717f-b8d8-412d-a47a-34b2004b3ace]Raising media quality changed event for Stream: 207c7c74-dbfa-46d5-a24d-833abdfa359b
TraceSource Warning: 0 : [AvMP][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] TL_WARN(TF_COMPONENT) [EN-PJAIN]77864.32::12/02/2019-14:49:08.299.00000663 (AVMP,ProcessDominantSpeakerChanged:Context.cs(3252)) [cid:efcb6dc8-a8f8-403f-9fe0-529131a7fe45]ProcessDominantSpeakerChanged: PreviousDominantAudioChannel field of RtpDominantSpeakerChangedEvent is null.
TraceSource Warning: 0 : [AvMP][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] TL_WARN(TF_COMPONENT) [EN-PJAIN]77864.32::12/02/2019-14:49:08.305.00000665 (AVMP,RaiseDominantSpeakerChangedEvent:Context.cs(3976)) [cid:efcb6dc8-a8f8-403f-9fe0-529131a7fe45][MP] Raising dominant speaker changed event. MediaSourceId: 4294967295, DSHistory is null
Microsoft.WindowsAzure.ServiceRuntime Verbose: 500 : Role instance status check starting
Microsoft.WindowsAzure.ServiceRuntime Verbose: 502 : Role instance status check succeeded: Ready
Microsoft.WindowsAzure.ServiceRuntime Verbose: 500 : Role instance status check starting
Microsoft.WindowsAzure.ServiceRuntime Verbose: 502 : Role instance status check succeeded: Ready

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, please feel free to reopen it, if required.
