### ISSUE TITLE
After app is published, a single httpRequest to the notification function take 20 seconds

### ISSUE THREAD

**Issue by lior-lew** [MicrosoftDocs/msteams-docs#11867]
### Steps to reproduce

Hi, 
I created a Teams app that sends notification to member that installed it. everything worked well until recently.
I tested it in dev, staging, on a different tenant and also Microsoft tested it before they approved it to the store.
after installing the app from the official store, I have noticed that every request might take 20-30 seconds. 
There is no logs or anywhere I know I can check it.
I will appreciate any insight on what I can do to check, please node that if I redeploy the app with more debug, my customers that are currently using it will need to reinstall it as deployment revokes access I have. 

This is very urgent as I am supposed to send thousands of notification during the holiday period and companies that work with Teams want this feature.

Also, I will appreciate a number on which I can get technical support even if I will need to pay for it. I do not get why I was able to get it from Amazon, slack but not from Microsoft.   

### Expected behavior

notification using httpRequest (code or cURL) should be fast

### Actual behavior

request takes 20-30 seconds and sometime I get I timeout. I do see that the request reached the Azure function

### Error details

no errors

**Comment by lior-lew** [comment]
I have created three identical apps, each differ only in name for different environments (dev, staging, and production). All three worked consistently before the production app was published. They were deployed using the VSCode Teams Toolkit, and I haven't made any configuration changes in Azure, except for adding a second function key.

Since the production app was published, its performance has been unstable. I am bypassing the internal logic and directly testing the Azure function using cURL. This command, which should typically take around 4-5 seconds, now fluctuates between 5 seconds and 1 minute 30 seconds.

Currently, I am the only one who has installed the app, so I doubt the issue is related to usage volume. Additionally, in the dev and staging environments, I can send 30 notifications via cURL within a few seconds without any issues.

**Comment by Prasad-MSFT** [comment]
When you upgrade your plan, it can sometimes lead to changes in the app's configuration or environment, which might inadvertently revoke the permissions granted to your app. This can happen due to discrepancies between the permissions defined in your App Registration and those applied to your Service Principal.

**Comment by lior-lew** [comment]
The problem was that the Teams toolkit generate a template for an app that stores the notification object locally. therefore, whenever an update happens that causes the Azure function to restart, all the data is lost.
in order to solve this I had to change the location of the storage to the Storage Account on my Azure resource group.

Prasad, if what you are saying is accurate, then it can be an operational nightmare. assuming that I have 100 companies that installed the app, they will think that they getting services from it, while the backend is unable to provided them unless they reinstall.
