### ISSUE TITLE
IS there any specific information about 'needsChannelSelector' property in manifest file

### ISSUE THREAD

**Issue by dtiwarATS** [MicrosoftDocs/msteams-docs#11875]
### Type of issue

Missing information

### Feedback

n/a

### Page URL

https://learn.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema

### Content source URL

https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/resources/schema/manifest-schema.md

### Author

@surbhigupta

### Document Id

7b3413f4-9ade-accf-5cb2-83fead11a32a

**Comment by Meghana-MSFT** [comment]
@dtiwarATS - It is explained here in the manifest schema - https://learn.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema#:~:text=Describes%20whether%20or%20not%20the%20bot%20uses%20a%20user%20hint%20to%20add%20the%20bot%20to%20a%20specific%20channel.%0ADefault%20value%3A%20false

Could you please let us know if you are looking for more information on this?
