### ISSUE TITLE
Video cannot be played

### ISSUE THREAD

**Issue by chi-mf** [MicrosoftDocs/msteams-docs#11885]
### Type of issue

Other (describe below)

### Feedback

The embedded video said  "Sign in to confirm you're not a bot", but there is no sign in link.

Besides, this issue form should be popped up instead navigated in place because I need to refer to original article to complete the form.

### Page URL

https://learn.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/api-based-overview

### Content source URL

https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/messaging-extensions/api-based-overview.md

### Author

@v-ypalikila

### Document Id

f1e3d44d-9e64-8332-dff8-26595726898c

**Comment by Prasad-MSFT** [comment]
@chi-mf, thank you for your inquiry! Could you please provide more details about your issue? Specifically, it would be helpful to know: 

- Reproduction Steps: What steps did you take leading up to the problem? 
- Documentation Links: Are there any specific guides or documentation you followed? 
- Teams Client Version: What version of the Teams client are you using? 
- Code Snippets: If applicable, please share any relevant code snippets. 
- Manifest Package: If you have one, could you include the manifest package for your app? 

Providing this information will help us better understand your situation and assist you more effectively.

**Comment by chi-mf** [comment]
Reproduction Steps: Just view the document at its URL.
Documentation Links: Not applicable I think, is there a help document teaching me how to read a help document?
Teams Client Version: I'm not using Teams Client to view it, what makes Teams Client special here?
Code Snippets: ???
Manifest Package: ????

See the screen shot below:
<img width="837" alt="ms-doc-bug" src="https://github.com/user-attachments/assets/87dd40ae-b122-478f-a6a8-75993c13e96d">


I see the [api-based-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/messaging-extensions/api-based-overview.md) embeds a YouTube video directly, seems YouTube is blocking me. I am able to view it by copying the video URL to another tab, but it takes time for me to learn: 1) there is no way I can login in place; 2) right click the blocked video I can get the video URL.

**Comment by Prasad-MSFT** [comment]
We are mainly responsible for Microsoft Teams app development related issues.  

For Microsoft Teams product issues/failures your tenant Admin can reach out to [Microsoft 365 Product Support](https://docs.microsoft.com/en-us/microsoft-365/admin/get-help-support?view=o365-worldwide&tabs=online).  

For general questions about Microsoft Teams please post your question on [Microsoft Teams Community](https://answers.microsoft.com/en-us/msteams/forum?sort=LastReplyDate&dir=Desc&tab=All&status=all&mod=&modAge=&advFil=&postedAfter=&postedBefore=&threadType=All&isFilterExpanded=false&page=1).

**Comment by Prasad-MSFT** [comment]
FYI @surbhigupta12, if you can help

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, please feel free to reopen it, if required.
