### ISSUE TITLE
We are not able to receive chat message without mentioning the bot.

### ISSUE THREAD

**Issue by Yavnesh** [MicrosoftDocs/msteams-docs#11898]
### Type of issue

Code doesn't work

### Feedback

[xnode.teams.bot.python.zip](https://github.com/user-attachments/files/18027778/xnode.teams.bot.python.zip)

### Page URL

https://learn.microsoft.com/en-us/microsoftteams/platform/bots/calls-and-meetings/registering-calling-bot#new-app-manifest-settings

### Content source URL

https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/bots/calls-and-meetings/registering-calling-bot.md

### Author

@surbhigupta

### Document Id

ba050a58-d98a-68f7-3190-8001d2a9d12c

**Comment by Prasad-MSFT** [comment]
@Yavnesh, thank you for your inquiry! Could you please provide more details about your issue? 
Specifically, it would be helpful to know: 

- Reproduction Steps: What steps did you take leading up to the problem? 
- Documentation Links: Are there any specific guides or documentation you followed? 
- Teams Client Version: What version of the Teams client are you using? 
- Code Snippets: If applicable, please share any relevant code snippets. 
- Manifest Package: If you have one, could you include the manifest package for your app? 

Providing this information will help us better understand your situation and assist you more effectively.
