### ISSUE TITLE
Developer preview option not showing up on android phone.

### ISSUE THREAD

**Issue by LalitAgrawala004** [MicrosoftDocs/msteams-docs#1189]
Hi
Developer preview option not showing up for me on android phone. However, on Iphone and desktop app, the option is showing up. So, I am pretty sure my account has been set up correctly. Does it work on a particular version of android?

My phone has android 8.0 and teams app version is 
 
![image](https://user-images.githubusercontent.com/17126892/70093712-00064780-15ef-11ea-9c35-baed1bd55efc.png)

Please help.

**Comment by Gousia-MSFT** [comment]
@LalitAgrawala004 Thanks for reporting this. We have raised a bug for this and we are working on fixing this.

**Comment by Gousia-MSFT** [comment]
@LalitAgrawala004 Could you please check if this is resolved now?

**Comment by LalitAgrawala004** [comment]
@Gousia-MSFT no it is still not fixed. I deleted the old app and installed it again but I am not seeing the developer preview option.

**Comment by Gousia-MSFT** [comment]
@LalitAgrawala004 The issue is fixed but it will be available in next store build soon.
