### ISSUE TITLE
Seems that https://github.com/OfficeDev/msteams-samples-hello-world-csharp.git is an old sample

### ISSUE THREAD

**Issue by fgyula17** [MicrosoftDocs/msteams-docs#1190]
I find completely different approach for message extension development with c# on this site and on this: https://docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/what-are-messaging-extensions
This site mentions "https://github.com/OfficeDev/msteams-samples-hello-world-csharp" as sample but the other one has a link to "https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore". Which one is the correct one, because "https://github.com/OfficeDev/msteams-samples-hello-world-csharp" looks older based on the dates?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f98c73d-bb68-3088-6e7d-2c576a8292f6
* Version Independent ID: 08b9df7d-4997-c681-e73a-235ec1e4fc7b
* Content: [Get started with C#/.NET - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tutorials/get-started-dotnet-app-studio#feedback)
* Content Source: [msteams-platform/tutorials/get-started-dotnet-app-studio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tutorials/get-started-dotnet-app-studio.md)
* Product: **msteams**
* GitHub Login: @clearab
* Microsoft Alias: **anclear**

**Comment by Gousia-MSFT** [comment]
@fgyula17 Both of these just use two different versions of SDK. [https://github.com/OfficeDev/msteams-samples-hello-world-csharp](https://github.com/OfficeDev/msteams-samples-hello-world-csharp) uses v3 SDK and https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore uses v4 SDK. You could try anyone of these. Both are correct.
