### ISSUE TITLE
Dev Tools on Iphone/IPad

### ISSUE THREAD

**Issue by LalitAgrawala004** [MicrosoftDocs/msteams-docs#1192]
This section only talks about Dev Tool on Desktop and Android client. I am able to enable developer preview on IPhone/Ipad but how to debug/inspect element?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3df1efbb-c6b2-a495-303d-7abf19c57f72
* Version Independent ID: a5b5782f-7031-a989-5e42-dd3010e18893
* Content: [DevTools for Microsoft Teams tabs - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/developer-tools)
* Content Source: [msteams-platform/tabs/how-to/developer-tools.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tabs/how-to/developer-tools.md)
* Product: **msteams**
* GitHub Login: @clearab
* Microsoft Alias: **anclear**

**Comment by Gousia-MSFT** [comment]
@LalitAgrawala004 Currently it is not possible to access dev tools on iOS.

**Comment by NischaiV** [comment]
@Gousia-MSFT Are there any plans for this? 
I am also facing some styling issues, only in IOS app, with my custom tab and am not able to inspect them.

**Comment by Gousia-MSFT** [comment]
@NischaiV Currently we do not have any plans for this.
