### ISSUE TITLE
2.5k 404's in the last 30 days

### ISSUE THREAD

**Issue by clearab** [MicrosoftDocs/msteams-docs#1200]
Need to research and determine where the majority are coming from. One culprit is definitely https://docs.microsoft.com/en-us/microsoftteams/add-bots (that page should just be removed entirely)

**Comment by laujan** [comment]
The page that Andrew is referencing has been removed and the link now redirects to this page: https://docs.microsoft.com/en-us/microsoftteams/platform/bots/what-are-bots. That page is up-to-date. The issue is resolved.
