### ISSUE TITLE
Teams - crashes after about 20 minutes every time. Error caa70004

### ISSUE THREAD

**Issue by fuserke1981** [MicrosoftDocs/msteams-docs#1201]
Hi

I'm not able to use Teams on my pc. After 20 min I'm getting error code - CAA70004. After that i have to restart but the same issue stays. Even clearing the cache does not help. The only thing I can do is to reinstall it but after 20 min it's the same error again. :-S

Who can help to solve this?

Greetings

**Comment by Trinetra-MSFT** [comment]
@fuserke1981 , Could you please use `Report a Problem` feature in help section of Microsoft Teams? So we can see the catch the error logs.
![image](https://user-images.githubusercontent.com/50989436/70292891-84321800-1805-11ea-8c29-74b592269a71.png)

**Comment by fuserke1981** [comment]
@Trinetra-MSFT Well when i look in the webapp i can only see:

![image](https://user-images.githubusercontent.com/58558784/70316601-5d331080-181c-11ea-9fdf-3ede726f9b08.png)

And in the desktop app i cannot do anything 
greetings

**Comment by Trinetra-MSFT** [comment]
@fuserke1981 ,  
Could you please follow below steps to get the error logs?
Please follow below steps to provide error logs when you sign in
1.	Fully exit the Microsoft Teams desktop client. To do this, either right click Teams from the Icon Tray and select ‘Quit’, or run Task Manager and fully kill the process.
2.	Go to File Explorer, and type in %AppData%\Microsoft\teams.
3.	Once in the directory, delete all files in this folder.
4.	Restart Teams and try to reproduce this issue.
5.	Right click Teams icon in system tray and click Get logs. Save the log file to your desktop and send to us

**Comment by Gousia-MSFT** [comment]
Please re-open with requested information if you are still facing the issue.

**Comment by abduldblogger** [comment]
Hi there,
I am too facing the same issue, followed the steps mentioned above, but it didn't work
