### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by pavanjains** [MicrosoftDocs/msteams-docs#1205]
How can I make calls to another organizations?

Also above page says you cannot record, what does that mean? You are not allowed to record or it is more for record API?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac64d14f-aec8-9dd6-e987-d2325de46fd6
* Version Independent ID: ba050a58-d98a-68f7-3190-8001d2a9d12c
* Content: [Registering a calling and meeting bot for Microsoft Teams - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/calls-and-meetings/registering-calling-bot#feedback)
* Content Source: [msteams-platform/bots/calls-and-meetings/registering-calling-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/bots/calls-and-meetings/registering-calling-bot.md)
* Product: **msteams**
* GitHub Login: @clearab
* Microsoft Alias: **anclear**

**Comment by Trinetra-MSFT** [comment]
@pavanjains , Please take a look at [Calling and Meeting Bot](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/calls-and-meetings/calls-meetings-bots-overview) and
[How to register your calling and meeting bot](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/calls-and-meetings/registering-calling-bot).

There is [Call Record](https://docs.microsoft.com/en-us/graph/api/call-record?view=graph-rest-beta&tabs=http) API which allow to record the call for 5 sec only.

**Comment by Gousia-MSFT** [comment]
Please re-open if you still have any queries.
