### ISSUE TITLE
App inside Team no longer sets browser cookie as of today 9 Dec 2019

### ISSUE THREAD

**Issue by borbea** [MicrosoftDocs/msteams-docs#1209]
Hello
Starting this morning, most users can no longer access our applications. No changes have been made to the application, but it appears that authorization cookies are no longer being saved in the browser. The response header contains the following value 
`set-cookie: Listy_Authentication=168f6364-81fa-43ed-ab56-e6a8d4695e49; path=/; samesite=lax` but cookie is never set in the browser.
 
We were able to save cookies as of Friday (12/6/2019).
 
Has there been any update to the Teams client that you are aware of?
 
When we run the application from Visual Studio and test via an ngrok URL the client appears to be remembering cookies and allowing authentication to flow properly.
 
Thank you very much in advance.

**Comment by jvalentovich** [comment]
Was able to resolve some of the issue by setting `SameSite = SameSiteMode.None` on the cookie (which wasn't needed as of 1/6/2019). That resolved the issue in Chrome, Edge, and Edge Beta (chromium based). However, cookies are still not being saved in the Windows Desktop Client.

**Comment by billbliss** [comment]
A few days after you posted these questions, we published this article: https://docs.microsoft.com/en-us/microsoftteams/platform/resources/samesite-cookie-update. This explains what to do for the latest versions of Chrome and Edge.

However the version of Chromium in the Teams client is not the newest version. The article referenced above mentions that you must do browser UserAgent sniffing to render the correct value for `SameSite`. Likely that's the issue for cookies not working in the desktop version.
