### ISSUE TITLE
GUID of the Connector in Teams

### ISSUE THREAD

**Issue by Gunnar-TX** [MicrosoftDocs/msteams-docs#1214]
So I created a connector for a channel in Teams and got a long string with several GUIDs, which is the link for the connector.

Where exactly can I find the required GUID?
Is it a substring of the connector link?

**Comment by Gousia-MSFT** [comment]
@Gunnar-TX Are you trying to [create an incoming webhook](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-incoming-webhook) for a channel or a [Custom connector](https://docs.microsoft.com/en-us/outlook/actionable-messages/connectors-dev-dashboard#build-your-own-connector)? If you are building your own connector, you could get the id of the connector in the link once you complete the registration.
This will be in the form: https://outlook.office.com/connectors/home/login/#/show/ConnectorId
![image](https://user-images.githubusercontent.com/45553518/70685559-c957bd80-1ccf-11ea-9dfd-e632efc9aa04.png)

**Comment by Gunnar-TX** [comment]
@Gousia-MSFT I am trying to follow this guide: https://docs.gitlab.com/ee/user/project/integrations/microsoft_teams.html

Which leads me to https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-using#setting-up-a-custom-incoming-webhook
However, I am stuck at the note:
> Replace id and connectorId in the following example with the GUID of your Connector.

**Comment by Gousia-MSFT** [comment]
@Gunnar-TX Could you please try creating a cutom connector from the [connector developer dashboard](https://outlook.office.com/connectors/home/login/#/publish)? Please follow the screenshot attached in my previous comment to get the connector id.

**Comment by Gousia-MSFT** [comment]
Please re-open if you still have any queries.
