### ISSUE TITLE
Teams Calls drop when leaving Wi-Fi

### ISSUE THREAD

**Issue by pbeiler1** [MicrosoftDocs/msteams-docs#1217]
My iOS smartphone, drops Teams-Calls, when I move off of a Wi-Fi network connection, to the cellular network connection.  Is there a setting to tweak here?

Edited this to better state the problem.

**Comment by Trinetra-MSFT** [comment]
Teams need internet connectivity to make a call. leaving network connection definitely drop your call. 
Please let me know if you face any issue while on connection

**Comment by pbeiler1** [comment]
On my other VOIP system, the call does not drop when switching from Wi-Fi connection, to a cellular connection.

**Comment by Trinetra-MSFT** [comment]
@pbeiler1 , Android does not keep the cellular connection up and running,  like ios does. So if you go kill wifi on an android, you have no network connectivity until Android spins up the cellular connection and gets it connected, which itself can take multiple seconds. If it takes long enough, this will become a call drop.

**Comment by Trinetra-MSFT** [comment]
We are unable to repro this issue. @pbeiler1 Could you please share some more light on this? Which device you are using and please try this with different network connection if connection will be slow, it will definitely drop the call.

**Comment by Gousia-MSFT** [comment]
Please re-open if you are still facing the issue.
