### ISSUE TITLE
HttpPOST on MessageCard returns ODataContentTypeException

### ISSUE THREAD

**Issue by Xolution13** [MicrosoftDocs/msteams-docs#1221]
We set up a new Microsoft Teams Connector and successfully set the settings to POST cards to the received WebhookUrl.
In the body that we send, we included the option to make HttpPost requests to a defined target URL (using ngrok.io tunnel for development). You can see the sent messageCard below:

```json
{
    "@type": "MessageCard",
    "@context": "https://schema.org/extensions",
    "summary": "Card \"Test card\"",
    "themeColor": "0078D7",
    "title": "Card created: \"Just another test\"",
    "potentialAction": [
        {
            "@type": "ActionCard",
            "name": "Add a comment",
            "inputs": [
                {
                    "@type": "TextInput",
                    "id": "comment",
                    "isMultiline": true,
                    "title": "Enter your comment"
                }
            ],
            "actions": [
                {
                    "@type": "HttpPOST",
                    "name": "Ok",
                    "target": "https://dd846f80.ngrok.io/teamshooks/actions",
                    "body": "{\"Comment\":\"This is a test\"}",
                    "headers": [
                        {
                            "Content-Type": "application/json"
                        },
                        {
                            "aw-teamid": "00000000-0000-0000-0000-000000000001"
                        }
                    ]
                }
            ]
        }
    ]
}
```

The card is displayed correctly in the channel in Microsoft Teams.
When a user clicks on this button, to make a HttpPOST to the specified url, we never receive the request on our side but can see that Microsoft returns the following response to the internal "executeAction" request:

The request was sent on: Fri, 13 Dec 2019 11:09:48 GMT

```json
{
   "status": "Failed",
   "actionId": "c520b20a-3e04-4e21-b4fd-c3a2f760c533",
   "properties":
      { 
          "displayMessage": "<p>Could not complete the requested action. Please try again later.</p>\n",
          "errorCode": "ODataContentTypeException"
      }
}
```

The following settings are set-up in the Connectors Developer Dashboard:
___

![image](https://user-images.githubusercontent.com/22793787/70794839-e0b1ac00-1d9e-11ea-86a9-38403118f035.png)
___

Can you tell us, if there is anything we are currently doing wrong or how to solve the returned ODataContentTypeException? We need to receive the request in our backend, in order to integrate Micorsoft Teams into our software.

**Comment by Gousia-MSFT** [comment]
@Xolution13 Could you please confirm if you are testing this in the same account where you have created the connector?

**Comment by Xolution13** [comment]
Yes, I created the connector with my account and am testing this with my account in my team.

**Comment by clearab** [comment]
That headers section looks off, can you send it w/o that section?

**Comment by Xolution13** [comment]
Removed the header section. Still same result unfortunately:

date: Wed, 18 Dec 2019 10:25:13 GMT

```
{
   "status":"Failed",
   "actionId":"ad011ce6-9dc8-4217-8982-bda2051955bf",
   "properties":{
      "displayMessage":"<p>Could not complete the requested action. Please try again later.</p>\n",
      "errorCode":"ODataContentTypeException"
   }
}
```

**Comment by Gousia-MSFT** [comment]
@Xolution13 Could you please check with your tenant admin If the connector is enabled in the tenant settings access list?

**Comment by Joachimzeelmaekers** [comment]
I'm getting the same issue. 
I'm using ngrok for forwarding and i'm posting this body to the incoming webhook.

Tried multiple payloads but never getting a result in my local webhook.
`{
  "@context": "https://schema.org/extensions",
  "@type": "MessageCard",
  "themeColor": "8083c0",
  "title": "Customer support",
  "text": "Support requested from Oswald chatbot X",
  "potentialAction": [
    {
      "@type": "ActionCard",
      "name": "Takeover",
      "inputs": [{
            "@type": "TextInput",
            "id": "comment",
            "isMultiline": false,
            "title": "Add a comment here for this task"
        }],
      "actions": [
        {
          "@type": "HttpPOST",
          "name": "Send Feedback",
          "target": "https://d438d16c.ngrok.io/api/v1/chats/microsoft-teams/takeover/webhook"
        }
      ]
    },
    {
      "@type": "OpenUri",
      "name": "Cancel",
      "targets": [
        { "os": "default", "uri": "https://docs.microsoft.com/outlook/actionable-messages" }
      ]
    }
  ]
}`

**Comment by Joachimzeelmaekers** [comment]
> @Xolution13 Could you please check with your tenant admin If the connector is enabled in the tenant settings access list?

Do you have any references or links that can help to find where we should exactly look?

**Comment by Xolution13** [comment]
I am not sure, if I looked in the right place. So,  @Gousia-MSFT can you please verify that I checked the "tenant settings access list":

In the Microsoft 365 Admin Center, I choose _Settings_ and then selected _Services & add-ins_. Then I clicked on _Microsoft Teams_ and checked, if my connector was listed there (**Tenant-wide settings -> Apps**).

The connector is listed and enabled in this list.

**Comment by Gousia-MSFT** [comment]
@Xolution13 Could you please try putting the targetUrl to any of the link generated in [webhook.site](https://www.webhook.site) and see if the request reaches there?

**Comment by Joachimzeelmaekers** [comment]
> @Xolution13 Could you please try putting the targetUrl to any of the link generated in [webhook.site](https://www.webhook.site) and see if the request reaches there?

I tried this and I'm not getting any requests on the generated link.

**Comment by Xolution13** [comment]
@Gousia-MSFT we tried this as well but the requests are not reaching the webhook.site url. 

However, we decided to set up a new free Microsoft Teams developer account, that is completely detached from our old accounts (new teams) and there setting up the connector and receiving the POST-actions works fine. Is it possible, that there are some issues with old/legacy accounts?

**Comment by Gousia-MSFT** [comment]
@Xolution13 Yes, it could be possible that the connector is disabled in your tenant setting access list. Good to know you got it working. Thanks!!
