### ISSUE TITLE
Mobile support?

### ISSUE THREAD

**Issue by IntranetFactory** [MicrosoftDocs/msteams-docs#1223]
&gt; Invoking a task module from JavaScript is not supported on mobile.    
    
I'm opening the Task module IFrame with an Action.Submit button from a bot in the desktop app. But the button does not even show in mobile (even in the developer preview). So are task modules from a bot not supported at all in mobile?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 501d3295-997c-d252-d458-534673b36a52
* Version Independent ID: c90dcc98-df65-b45b-4f78-64d2cab91852
* Content: [What are task modules? - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/what-are-task-modules#feedback)
* Content Source: [msteams-platform/task-modules-and-cards/what-are-task-modules.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/what-are-task-modules.md)
* Product: **msteams**
* GitHub Login: @clearab
* Microsoft Alias: **anclear**

**Comment by Gousia-MSFT** [comment]
@IntranetFactory TaskModules are supported on mobile. You should be able to open a task module from a button. You mentioned you are not able to see the buttons on card. Could you please share the json for your card?

**Comment by IntranetFactory** [comment]
The button with the label "Open" shows on the desktop app and desktop browser, but is missing in the iPhone app   

```
{"ContentType":"application/vnd.microsoft.card.adaptive","ContentUrl":null,"Content":{"Type":"AdaptiveCard","Version":{"Major":1,"Minor":0},"MinVersion":null,"FallbackText":null,"Speak":"'form' is not supported. Please use the app.","Lang":null,"Title":null,"BackgroundImage":null,"Height":{"HeightType":0,"Unit":null,"UnitXml":0},"PixelMinHeight":0,"Body":[{"Type":"ColumnSet","Columns":[{"Type":"Column","Size":null,"Width":"4","BackgroundImage":null,"Items":[{"Type":"TextBlock","Size":0,"Weight":0,"Color":0,"IsSubtle":false,"Italic":false,"Strikethrough":false,"Text":"Create a ticket","HorizontalAlignment":0,"Wrap":true,"MaxLines":0,"MaxWidth":0,"FontType":0,"Spacing":1,"Separator":false,"Speak":null,"Height":{"HeightType":0,"Unit":null,"UnitXml":0},"IsVisible":true,"AdditionalProperties":{"separation":"none"},"Fallback":null,"InternalID":null,"Id":null,"Requires":null}],"Style":null,"StyleXml":0,"VerticalContentAlignment":0,"SelectAction":null,"Bleed":false,"PixelMinHeight":0,"Spacing":0,"Separator":false,"Speak":null,"Height":{"HeightType":0,"Unit":null,"UnitXml":0},"IsVisible":true,"AdditionalProperties":{},"Fallback":null,"InternalID":null,"Id":null,"Requires":null}],"Style":null,"StyleXml":0,"VerticalContentAlignment":0,"SelectAction":null,"Bleed":false,"PixelMinHeight":0,"Spacing":3,"Separator":false,"Speak":null,"Height":{"HeightType":0,"Unit":null,"UnitXml":0},"IsVisible":true,"AdditionalProperties":{},"Fallback":null,"InternalID":null,"Id":null,"Requires":null},{"Type":"ActionSet","Actions":[{"Type":"Action.Submit","Data":[[[[[]]]],[[]]],"DataJson":"{\r\n  \"msteams\": {\r\n    \"type\": \"task/fetch\"\r\n  },\r\n  \"taskModule\": \"https://app.adenin.com/App/MsTeamsTaskFrame?cardid=3cefff1f-0afd-4cf1-a14a-6051c544fdd3\"\r\n}","Title":"Open","Speak":null,"IconUrl":null,"Style":"default","AdditionalProperties":{},"Fallback":null,"InternalID":null,"Id":null,"Requires":null}],"Spacing":0,"Separator":false,"Speak":null,"Height":{"HeightType":0,"Unit":null,"UnitXml":0},"IsVisible":true,"AdditionalProperties":{},"Fallback":null,"InternalID":null,"Id":null,"Requires":null}],"Actions":[],"VerticalContentAlignment":0,"SelectAction":null,"AdditionalProperties":{},"Fallback":null,"InternalID":null,"Id":null,"Requires":null},"Name":null,"ThumbnailUrl":null,"Properties":[]}
```

**Comment by clearab** [comment]
Hi - I think you may need to lowercase all your parameter names, i.e. "Type" becomes "type". Can you please try using the designer at adaptivecards.io to validate your card? If it parses there correctly and you're still seeing issues, please let us know.

**Comment by IntranetFactory** [comment]
It works with the desktop and android app, and only fails in iOs. Does the iOS app handle that differently?

**Comment by Gousia-MSFT** [comment]
@IntranetFactory Could you please share a snapshot of the version of your app?

**Comment by IntranetFactory** [comment]
The MS Teams connector is part of an large application. So we currently cannot share source code. Is there any logging in the C# library we can enable to provide you with the information you need?

**Comment by Gousia-MSFT** [comment]
@IntranetFactory Please let us know the version of the Teams mobile app you are using. You could get that under Settings->About.

**Comment by Gousia-MSFT** [comment]
Please re-open with requested information.

**Comment by IntranetFactory** [comment]
The version is 1.0.92 with developer preview enabled running on an iPhone.
