### ISSUE TITLE
Cannot create a Planner in private Channel

### ISSUE THREAD

**Issue by josuedepinho** [MicrosoftDocs/msteams-docs#1225]
Hello,

Thank you for the new feature "private channels". Unfortunately, creating a planner tab does not work, as it is not found anywhere in the apps hub. It is an authorized application in our business and I can create a tab for planner in any other public channel. 

Thank you

Josué

**Comment by Abhijit-MSFT** [comment]
@josuedepinho - Currently planner is not supported in the Private Channels.
