### ISSUE TITLE
Update needed for "Turn on Microsoft Teams for your organization"

### ISSUE THREAD

**Issue by ndambrosio** [MicrosoftDocs/msteams-docs#1226]
Looks like we need to update the **Turn on Microsoft Teams for your organization** section as the Teams org-wide settings have been removed from the Microsoft 365 Admin center.  Teams org-wide settings are now made using the Teams admin center.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3530b55-59c8-6eec-b257-b7a5f2ed046b
* Version Independent ID: 022f7eff-f6c2-9a73-afa9-74e887b761e1
* Content: [Prepare your Office 365 tenant - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/prepare-your-o365-tenant)
* Content Source: [msteams-platform/concepts/build-and-test/prepare-your-o365-tenant.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/build-and-test/prepare-your-o365-tenant.md)
* Product: **msteams**
* GitHub Login: @clearab
* Microsoft Alias: **anclear**

**Comment by Abhijit-MSFT** [comment]
@ndambrosio - Yes, few settings are moved to Teams admin settings. You get the proper redirection in 365 Admin center to the new settings. Are you looking for any particular settings?
![image](https://user-images.githubusercontent.com/48427340/71014285-b736ae80-2117-11ea-875d-e3e7a0616095.png)

**Comment by ndambrosio** [comment]
There is no reference to Teams or Skype in the M365 Admin Center in 4 different commercial tenants I checked again today.

**Comment by clearab** [comment]
Thanks for letting us know!
