### ISSUE TITLE
Screenshots & videos?

### ISSUE THREAD

**Issue by IntranetFactory** [MicrosoftDocs/msteams-docs#1228]
When I look at Apps which are already listed in the Teams Apps section most show screenshots and/or videos (e.g. Flow App), but I couldn't find how I can provide screenshots or videos in the manifest of our App

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f94a488-d636-92b3-21eb-c88744c8f272
* Version Independent ID: 7b3413f4-9ade-accf-5cb2-83fead11a32a
* Content: [Manifest schema reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema)
* Content Source: [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/resources/schema/manifest-schema.md)
* Product: **msteams**
* GitHub Login: @clearab
* Microsoft Alias: **anclear**

**Comment by Gousia-MSFT** [comment]
@IntranetFactory Could you please share a screenshot of the ask you have? What do you mean by adding screenshot to manifest?

**Comment by IntranetFactory** [comment]
I've uploaded the manifest of our application to MS Teams. When I add that app I see the text from the manifest. Other applications (like Flow) show images and videos above the text, and I'm wondering how I can add those as well

![image](https://user-images.githubusercontent.com/7462342/71087195-972fdb00-2169-11ea-94fd-36935159cdf3.png)


![image](https://user-images.githubusercontent.com/7462342/71087132-68b20000-2169-11ea-9f21-d9c83230826e.png)

**Comment by Gousia-MSFT** [comment]
@IntranetFactory This is added as part of your app submission. This is not something which is specified in the manifest. Please reach out to **teamsubmATmicrosoft.com** for more information on this.
