### ISSUE TITLE
How to pass large data to html in task module(a html page hosted in azure) in Messaging Extension in Teams app

### ISSUE THREAD

**Issue by MaheshakaMudli** [MicrosoftDocs/msteams-docs#1229]
We are using a task module(a html page hosted in azure) in Messaging Extension to show a custom user form. The task module is called when custom action is clicked in teams. Our requirement is to pass large data to the task module. The only option we found is through query string while calling the task module but passing large data is not possible through query string. Is there any alternate way to pass data to the task module.

**Comment by Subhasish-msft** [comment]
@MaheshakaMudli , Please refer to the documentation here for [Initial invoke request from a message](https://docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/action-commands/create-task-module?tabs=dotnet#initial-invoke-request-from-a-message) .

Here a [sample code](https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/51.teams-messaging-extensions-action) for the same.

**Comment by Gousia-MSFT** [comment]
Please re-open if you still have any queries.
