### ISSUE TITLE
Personal scoped Teams app tab does not show iFrame in Native App and mobile

### ISSUE THREAD

**Issue by MagtheRag** [MicrosoftDocs/msteams-docs#1231]
We have an app for Teams. 
The app has 2 personal scoped tabs. Each tab points to 2 different pages inside of SharePoint. 
When using the web version of Teams, not the native app, everything works fine and we have no complains. 

When using the native app _sometimes_ the iframe does not load at all, looking into the dev tools we see that it is a Cors problem. _Sometimes_ flipping between the tabs does the trick, the iframe loads and work from that point forward. Otherwise we have to navigate to a team with a tab with a SharePoint page in it. Open that tab and then go back to the app. Then the iframe will load. 

In the mobile app we get a login page. 

Does anyone know a solution to this problem?

**Comment by Abhijit-MSFT** [comment]
@MagtheRag, How are you pulling the SharePoint page inside the Teams?

**Comment by MagtheRag** [comment]
The SharePoint pages are defined in the Teams app manifest file. Like this:
"staticTabs": [
    {
      "entityId": "eXXX",
      "name": "title1",
      "contentUrl": "https://xxx.sharepoint.com/teams/d2/SitePages/xxxx.aspx",
      "websiteUrl": "https://xxx.sharepoint.com/teams/d2/SitePages/xxxx.aspx",
      "scopes": ["personal"]
    },
    {
      "entityId": "eXXX2",
      "name": "title2",
      "contentUrl": "https://xxx.sharepoint.com/teams/d2/SitePages/xxxx2.aspx",
      "websiteUrl": "https://xxx.sharepoint.com/teams/d2/SitePages/xxxx2.aspx",
      "scopes": ["personal"]
    }
  ],

**Comment by MagtheRag** [comment]
Why is this closed ??

**Comment by laujan** [comment]
@MagtheRag , sorry about that, it has been reopened.

**Comment by laujan** [comment]
@Abhijit-MSFT, please review.

**Comment by MagtheRag** [comment]
Any news about this issue ?

**Comment by Nikitha-MSFT** [comment]
@MagtheRag -Are you still facing the issue?if yes, please free to reopen the issue
