### ISSUE TITLE
Inconsistencies on mobile/desktop Feed/Activity sender name

### ISSUE THREAD

**Issue by butchmarshall** [MicrosoftDocs/msteams-docs#1233]
The desktop notification refers to itself as "TemboSocial" while the mobile notification refers to itself as "Recognition".  The mobile notification refers to itself as "TemboSocial Recognition"...

My "Bot" is set up as "TemboSocial Recognition"
My App names "Short Name" is Recognition.
My Developer information"Name" is TemboSocial.

![Screenshot from 2019-12-19 07-42-40](https://user-images.githubusercontent.com/339763/71174675-c0b53900-2233-11ea-913c-59fcfd9b20c5.png)

![Screenshot from 2019-12-19 07-44-35](https://user-images.githubusercontent.com/339763/71175041-8730fd80-2234-11ea-93bc-3872536de2ff.png)

![Screenshot from 2019-12-19 07-44-45](https://user-images.githubusercontent.com/339763/71174680-c3b02980-2233-11ea-93c9-7a52464996e7.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f83b32eb-4265-39bd-e52f-78daf388d1ad
* Version Independent ID: eacbd346-f794-3d91-2eef-227b1a126c31
* Content: [Conversation basics - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-basics?tabs=dotnet)
* Content Source: [msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/bots/how-to/conversations/conversation-basics.md)
* Product: **msteams**
* GitHub Login: @clearab
* Microsoft Alias: **anclear**

**Comment by Wajeed-msft** [comment]
@butchmarshall - Are you still facing this issue? Is your [Bot's display name](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-manage-settings?view=azure-bot-service-4.0) in Azure Bot Settings page is same as App Manifest?
