### ISSUE TITLE
Missing step for Azure subscription

### ISSUE THREAD

**Issue by maksim-pankov** [MicrosoftDocs/msteams-docs#1240]
When using Azure subscription, be sure to add Microsoft Teams as a channel from the featured channels list after creating your bot.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e52a9fa-a482-2929-c462-47da5e8b38d1
* Version Independent ID: ce956c12-2916-9d6c-4fbb-5d07556378bc
* Content: [Create a bot for Microsoft Teams - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/create-a-bot-for-teams#with-an-azure-subscription)
* Content Source: [msteams-platform/bots/how-to/create-a-bot-for-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/bots/how-to/create-a-bot-for-teams.md)
* Product: **msteams**
* GitHub Login: @clearab
* Microsoft Alias: **anclear**

**Comment by dnys1** [comment]
I had the same issue. Was very confused why I couldn't reach my bot.

**Comment by tmanOC** [comment]
Same here spent hours on this. Please update the documentation
