### ISSUE TITLE
ExtensionTabService: getAuthTokenForApp: Failed with error - App resource defined in manifest and iframe origin do not match

### ISSUE THREAD

**Issue by NischaiV** [MicrosoftDocs/msteams-docs#1244]
Hi,
I followed the steps mentioned in [this page](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-aad-sso) to get a single sign-on functionality for my custom tab in MS Teams. But I get the following error and I could not find out the reason for the same. I re-checked the resource URL used in both manifest as well as App registration page.

_**ExtensionTabService: getAuthTokenForApp: Failed with error - App resource defined in manifest and iframe origin do not match**_

**Comment by Gousia-MSFT** [comment]
@NischaiV Could you please verify the resource name you have specified in Azure settings?

**Comment by NischaiV** [comment]
@Gousia-MSFT Its "api://<App URL>/<App_ID>"
But this issue got resolved when I added **_"inTeamsSSO=true"_** in the configuration URL. I missed this because it was not mentioned anywhere in the documentation. Probably it is a good idea to add it in as this is a change when compared with MSAL/ADAL way of authentication.

**Comment by Gousia-MSFT** [comment]
@NischaiV Cool!! Thanks for letting us know.

**Comment by danvilenica** [comment]
@NischaiV hi i'm having the same problem but didn't understand your solution "inTeamsSSO=true". Can you clarify where did you add it?

**Comment by Ky7m** [comment]
@danvilenica I assume there is a reference to this flag https://github.com/ydogandjiev/taskmeow/blob/master/manifest/sso/manifest.json#L28
and following processing flow
https://github.com/ydogandjiev/taskmeow/blob/master/src/services/auth.service.js#L16
https://github.com/ydogandjiev/taskmeow/blob/master/src/services/sso.auth.service.js#L6

**Comment by NischaiV** [comment]
> @NischaiV hi i'm having the same problem but didn't understand your solution "inTeamsSSO=true". Can you clarify where did you add it?

Hi @danvilenica,
You have to add "inTeamsSSO=True" at the end of your URL to get it working.

**Comment by csnarain** [comment]
I tried to append this to my tab config url but to no vain. I'm still getting error mentioned in this issue and not getting tokens. Has something changed recently?
