### ISSUE TITLE
gulp installation

### ISSUE THREAD

**Issue by georgschwienbacher** [MicrosoftDocs/msteams-docs#1245]
The suggested installation command for gulp "npm install gulp" didn't work for me. Instead, I've used "npm install --globald gulp-cli"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4fa27cb-544f-f8a2-97a7-4b31528c1b80
* Version Independent ID: fa69cd6f-1ef4-706d-2816-aa709714b0aa
* Content: [Get started with App Studio and Node.js - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tutorials/get-started-nodejs-app-studio#feedback)
* Content Source: [msteams-platform/tutorials/get-started-nodejs-app-studio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tutorials/get-started-nodejs-app-studio.md)
* Product: **msteams**
* GitHub Login: @clearab
* Microsoft Alias: **anclear**

**Comment by Subhasish-msft** [comment]
"npm install gulp" doesn't work sometimes because of version conflicts.
We need to use "rm --global gulp" to clear out any version conflicts and then run "npm install --global gulp-cli".
