### ISSUE TITLE
How can an app be automatically uploaded to a Team through CD

### ISSUE THREAD

**Issue by TechWatching** [MicrosoftDocs/msteams-docs#1249]
I want to use Azure Pipelines to automate the upload of my teams application to Microsoft Teams. It can be useful when my manifest change and I want my CI /CD pipeline to upload the new manifest in teams without having to do it manually through App Studio. How can I do that ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54780e5a-ca3a-5277-dc84-37f85d9ea1cb
* Version Independent ID: 5f89865b-a9fd-ada5-72d2-6375357bba8c
* Content: [Upload your custom app in Microsoft Teams - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/apps-upload)
* Content Source: [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/deploy-and-publish/apps-upload.md)
* Product: **msteams**
* GitHub Login: @clearab
* Microsoft Alias: **anclear**

**Comment by Ky7m** [comment]
@TechWatching you can automate this through Microsoft Graph API https://docs.microsoft.com/en-us/graph/api/teamsapp-publish?view=graph-rest-1.0

**Comment by TechWatching** [comment]
Yes I saw that thanks but that's not exactly what I need. This API allows to publish to the tenant catalog but I just want to upload it on a Team in my tenant the same way I am doing it with App Studio but programmatically. Moreover to use the API I need to have a global administrator account of the tenant which I don't.

**Comment by Subhasish-msft** [comment]
You can take a look into this beta API https://docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-beta&tabs=csharp

**Comment by TechWatching** [comment]
The app needs to already been in the company catalog, it does not solve the original problem of updating the app manifest.

**Comment by Subhasish-msft** [comment]
You can [update the app manifest](https://docs.microsoft.com/en-us/graph/api/teamsapp-update?view=graph-rest-1.0) first and then [upgrade installed app](https://docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-beta&tabs=http) for particular user/ team. Sorry for late reply. Hope it helps.
