### ISSUE TITLE
Unable to connect O365 group with API getting error { "error": { "code": "UnknownError", "message": "404 FILE NOT FOUND", "innerError": { "request-id": "ea4d7cc5-2a83-4f70-a64c-ba209e6f92c7", "date": "2019-12-31T06:36:14" } } } 

### ISSUE THREAD

**Issue by sonam-embee** [MicrosoftDocs/msteams-docs#1250]
Hi we are migrating Microsoft Office 365 groups from an office 365 tenant to other tenant via API but getting below error when trying to connect with Graph API, please help.
{ "error": { "code": "UnknownError", "message": "404 FILE NOT FOUND", "innerError": { "request-id": "ea4d7cc5-2a83-4f70-a64c-ba209e6f92c7", "date": "2019-12-31T06:36:14" } } }

**Comment by Trinetra-MSFT** [comment]
@sonam-embee , Could you please check the permissions `Group.Read.All, Group.ReadWrite.Alls, User.Read.All, Directory. Read.All.`?

**Comment by sonam-embee** [comment]
Yes, it is there.

**Comment by Trinetra-MSFT** [comment]
@sonam-embee , Are you using any external tool for migrating office365 groups to other tenant? Currently migration to different tenant is not possible using Graph API, You can get the[ list of groups](https://docs.microsoft.com/en-us/graph/api/group-get?view=graph-rest-1.0&tabs=http#request) using below API than set the target and destination host for migration.

**Comment by sonam-embee** [comment]
We are using third party app for O365 groups migration that uses API to migrate the data but we are getting issue wile connecting to this group with Micrsoft Graph API

**Comment by sonam-embee** [comment]
We are using third party tool to migrate, it uses API to migrate data but having issue while connecting tghis group with Microsoft Graph API

**Comment by Trinetra-MSFT** [comment]
Please feel free to reopen the issue, if you still have any query
