### ISSUE TITLE
Custom tab does not work in android Teams app

### ISSUE THREAD

**Issue by NischaiV** [MicrosoftDocs/msteams-docs#1251]
Hi,

The custom tab that I built works perfectly fine in the Teams desktop client, website and IOS (13.3) app. But it fails to load the same in the android app and gives an 'IndexOutOfRangeException'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52221dd3-95ec-96b9-1da8-9478527c2602
* Version Independent ID: 32e9c2d8-733d-0865-2ea3-727d8684a10d
* Content: [Single Sign-On - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-aad-sso)
* Content Source: [msteams-platform/tabs/how-to/authentication/auth-aad-sso.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tabs/how-to/authentication/auth-aad-sso.md)
* Product: **msteams**
* GitHub Login: @clearab
* Microsoft Alias: **anclear**

**Comment by Gousia-MSFT** [comment]
@NischaiV Could you please elaborate more on what is that you are trying to load inside Tab? What is the error message you see on screen? A screenshot might help understand better.

**Comment by NischaiV** [comment]
The problem was that the same code that works in all Teams client fails in the android Teams app. I dug a little deeper into the code and found that the 'getContext().EntityId' method is returning different values. I am getting the same value from Desktop client, browser and IOS app, but when using the android app, I am getting a very different value.

microsoftTeams.getContext(function (context)
    context.EntityId      )

When using the Desktop client, website and IOS Teams app, I am getting this value as a string (as expected). And in case of android app, I am getting the value that looks more like a GUID or Unique Key.

**Comment by Gousia-MSFT** [comment]
@NischaiV I could not repro the issue. When I tried to get entityid using Teams Tab context, I get the entityid of the tab as expected. Could you please try updating your teams app to the latest version?

**Comment by NischaiV** [comment]
Hi @Gousia-MSFT ,
Sorry about the late reply. I still have the issue. I am setting the context variable from the tab configuration page as follows:
```
microsoftTeams.settings.setSettings({
                entityId: <some string value based on the entry in configuration page>,
            });
```
It returns me the string (as expected) when trying to access from the Desktop client, web browser or ios Teams app. But it returns a GUID value when accessing using android Teams app. This fails to load my custom tab. 
I also noticed that, from android, I not only see the data added in the configuration page of the custom tab, but also update the configuration. May be this is the reason why my custom tab fails to load in android Teams app.

**Comment by Wajeed-msft** [comment]
This issue is fixed and it's being rolled out.
