### ISSUE TITLE
npm install msteams-samples-hello-world-nodejs

### ISSUE THREAD

**Issue by Ed-Mar** [MicrosoftDocs/msteams-docs#1253]
when using the code from msteams-samples-hello-world-nodejs  use "npm update" then npm insatll". if you do just npm install it will fail with errors. So just update the git project so you can install it. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4fa27cb-544f-f8a2-97a7-4b31528c1b80
* Version Independent ID: fa69cd6f-1ef4-706d-2816-aa709714b0aa
* Content: [Get started with App Studio and Node.js - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tutorials/get-started-nodejs-app-studio#feedback)
* Content Source: [msteams-platform/tutorials/get-started-nodejs-app-studio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tutorials/get-started-nodejs-app-studio.md)
* Product: **msteams**
* GitHub Login: @clearab
* Microsoft Alias: **anclear**

**Comment by Trinetra-MSFT** [comment]
Feel free to reopen this. Will update you once the doc is updated.

**Comment by unicorn-devwriter** [comment]
Can we reopen this until the doc is updated? I encountered this issue very recently. As the doc was not updated, it was very confusing to me.
