### ISSUE TITLE
Get conversation paged members returns 403 

### ISSUE THREAD

**Issue by kafka-yu** [MicrosoftDocs/msteams-docs#1254]
Hi There,
This issue is the follow of #539 

First, we're also using the getConversationMembers API to get the member list of a group chat. And we have the same concern that when the group/channel members count is large, will that API work correctly? Is it fast or slow? Is there an upon limit numbers of the members it can handle?

The second question is is there any other API that we can use to get a total member count of a conversation(group/channel)? We don't find it for now.

Meanwhile, it will be greatly appreciated if pagedmembers endpoint is available for us.

Thanks for your time.

**Comment by Trinetra-MSFT** [comment]
Could you please give a try to below piece of code to fetch the member list in a channel?
```
using (var connector = new ConnectorClient(new Uri(turnContext.Activity.ServiceUrl), appId, appSecret))
      {
           var teamId = turnContext.Activity.TeamsGetTeamId();
           var members = await connector.Conversations.GetConversationMembersAsync(teamId);
}
```

Let me know if you face any issue.

**Comment by clearab** [comment]
Hi - The paged member endpoint is currently in development and will be made available soon. For group chats, the upper bound on the getMembers call is smaller than the maximum number of users you can have in a group chat, so it should always return all members. Fast and slow are pretty subjective, but in this case I believe you'll find the API to return quickly.

There is currently no way to return the count of users in a conversation w/o calling getMembers. We're looking at enabling that in the future.

**Comment by kafka-yu** [comment]
Thank you @Trinetra-MSFT @clearab 

We're looking forward to the availability of the paged member API.
