### ISSUE TITLE
getConversationMembers response is incorrect when members remove/add in a calendar group chat

### ISSUE THREAD

**Issue by kafka-yu** [MicrosoftDocs/msteams-docs#1255]
Hi There,

We found Teams can create a group chat from a scheduled meeting.

![image](https://user-images.githubusercontent.com/3942409/72035024-a66df880-32d1-11ea-8193-b3320a938dab.png)

Open the "Chat with participants" it will open a group chat, assume it has 4 people.

In this chat, then add 2 more people. We call the **TeamInfo.getMembers()** method, it seems the response only has the members who are from the initial state (the 4 people). It should return 6?

Is it a bug or by design?

Thanks for your time to help!

**Comment by kafka-yu** [comment]
@Gousia-MSFT May I ask your help to check this one? Thanks a lot!

**Comment by Trinetra-MSFT** [comment]
@kafka-yu , We have opened a bug for this and we are tracking this internally.
