### ISSUE TITLE
Microsoft Teams is now available on Linux

### ISSUE THREAD

**Issue by JessAtrust** [MicrosoftDocs/msteams-docs#1256]
Microsoft Teams can not be executed on our current Linux OS firmware, it shows no space left, therefore it seems require some space to save their data. How to specify the path of saved data?  
Our root directory is a chroot jail, and the space of root is always 100% used, therefore, we need to know how to specify the path of saved data for Microsoft Teams, or how to pass the space checking of Microsoft Teams.

**Comment by Gousia-MSFT** [comment]
@JessAtrust We don't support changing the path, but the specific path we currently use is ~/.config/Microsoft/Microsoft Teams/ ... or if you have insiders, it would be ~/.config/Microsoft/Microsoft Teams - Insiders
