### ISSUE TITLE
Teams Meeting app

### ISSUE THREAD

**Issue by solj2018** [MicrosoftDocs/msteams-docs#1259]
Hi, Can we make a teams app to capture actual attendee list for a teams meeting? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f57a31a0-e815-faa4-653d-795ae8a8e4d7
* Version Independent ID: 8f48ea3d-231b-2776-41b7-11890ea2d3c0
* Content: [Microsoft Teams developer platform - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/overview#feedback)
* Content Source: [msteams-platform/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/overview.md)
* Product: **msteams**
* GitHub Login: @clearab
* Microsoft Alias: **anclear**

**Comment by Subhasish-msft** [comment]
@solj2018, 
Yes You can make use of Graph API in an app for fetching meeting info and participant details.
https://docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-1.0&tabs=http
