### ISSUE TITLE
Bots in channel and group chat conversations require the user to @ mention the bot to invoke it in a channel

### ISSUE THREAD

**Issue by vrvrvrvrvr** [MicrosoftDocs/msteams-docs#1260]
Is it technically possible to to hear all messages in MS Teams channel that bot can reply to end user messages using QnA service? Documentation states that mentioning is obligatory or end users have to use 1:1 conversations

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f83b32eb-4265-39bd-e52f-78daf388d1ad
* Version Independent ID: eacbd346-f794-3d91-2eef-227b1a126c31
* Content: [Conversation basics - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-basics?tabs=typescript&source=docs#feedback)
* Content Source: [msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/bots/how-to/conversations/conversation-basics.md)
* Product: **msteams**
* GitHub Login: @clearab
* Microsoft Alias: **anclear**

**Comment by Gousia-MSFT** [comment]
@vrvrvrvrvr Currently it is not possible for your bot to listen to all the messages in the channel. The bot responds to messages only when it is @ mentioned.
