### ISSUE TITLE
SameSite cookie attribute 

### ISSUE THREAD

**Issue by GFoley83** [MicrosoftDocs/msteams-docs#1263]
The note above states that:
&gt;It's recommended that you set the intended use for your cookies rather than rely on default browser behavior.

but you don't provide an example of how to accomplish this. 
What changes to the code above should be made to support the SameSite cookie attribute? 

Currently when testing in Chrome with the following flags enabled:
chrome://flags/#same-site-by-default-cookies
chrome://flags/#cookies-without-same-site-must-be-secure

I can see that cookies issued from http://login.microsoftonline.com are being blocked.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b1dcd0d-471b-2d33-54b5-39a93dfba2a8
* Version Independent ID: 5bd44149-777e-b449-bd2e-f20b9bd04038
* Content: [Authentication for tabs using Azure Active Directory - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-tab-aad)
* Content Source: [msteams-platform/tabs/how-to/authentication/auth-tab-aad.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tabs/how-to/authentication/auth-tab-aad.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **anclear**

**Comment by Trinetra-MSFT** [comment]
@GFoley83 ,Here is the documentation for [Microsoft Teams and the SameSIte cookie attribute](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/samesite-cookie-update).

**Comment by GFoley83** [comment]
Thanks @TravisCragg-MSFT but that just elaborates on the issue; my original question still remains: there's no code example or steps provided on how to actually mitigate this issue.

**Comment by Trinetra-MSFT** [comment]
@GFoley83 , May this will help you [Upcoming SameSite Cookie Changes in ASP.NET and ASP.NET Core](https://devblogs.microsoft.com/aspnet/upcoming-samesite-cookie-changes-in-asp-net-and-asp-net-core/)
