### ISSUE TITLE
getMembers method works without BotNotInConversationRoster error after bot removed in group chat

### ISSUE THREAD

**Issue by kafka-yu** [MicrosoftDocs/msteams-docs#1264]
Hi there,

We find if bot installed in a group chat and then remove it.
Then the TeamInfo.getMembers() won't throw the "BotNotInConversationRoster" error.

Is it a cache there on the Teams backend?

We currently use this method to detect if the group chat has included our bot. Is there any other way to do this without calling the TeamInfo.getMembers()?

Thanks for your time to help!

**Comment by Gousia-MSFT** [comment]
@kafka-yu Thanks for reaching out to us. We could repro the issue and we are checking it internally.

**Comment by kafka-yu** [comment]
Thanks @Gousia-MSFT !

**Comment by Gousia-MSFT** [comment]
@kafka-yu We have raised a bug for this. We are tracking it internally.
