### ISSUE TITLE
Deep Link in Teams for Who Bot

### ISSUE THREAD

**Issue by Chekrii** [MicrosoftDocs/msteams-docs#1265]
Hi All,

I am able to create Deeplink to my bot with

"https://teams.microsoft.com/l/chat/0/0?users=<<MyBotID>>&message=Who am I"

but I am unable to create Deep link for who Bot in teams which is an In built bot provided by Teams.

Please help
Thanks.

**Comment by Gousia-MSFT** [comment]
@Chekrii Please try out this link to deep link to Who Bot:
https://teams.microsoft.com/l/chat/0/0?users=28:c8f1cda6-5af5-40bf-a9f3-2fa21b72adde

**Comment by Chekrii** [comment]
Thank you so much. It helped me a lot :)
