### ISSUE TITLE
Dev Tools Not Opening

### ISSUE THREAD

**Issue by HaveSpacesuit** [MicrosoftDocs/msteams-docs#1267]
Clicking Open DevTools... doesn't. The button is there in the context menu, but nothing noticeable happens when clicking it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3df1efbb-c6b2-a495-303d-7abf19c57f72
* Version Independent ID: a5b5782f-7031-a989-5e42-dd3010e18893
* Content: [DevTools for Microsoft Teams tabs - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/developer-tools#feedback)
* Content Source: [msteams-platform/tabs/how-to/developer-tools.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tabs/how-to/developer-tools.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **anclear**

**Comment by Gousia-MSFT** [comment]
@HaveSpacesuit Could you please confirm if you have enabled DevPreview? If you are still facing this after enabling developer preview, please quit Microsoft Teams and see if it's visible when you launch it again.

**Comment by HaveSpacesuit** [comment]
I had experienced some view in which the context menu only had a few items, including DevTools. Clicking the icon 7 times produces a very large context menu in which I can successfully interact with DevTools. I'm unsure how to recreate the state I saw the one time.

Thanks. 🙂
