### ISSUE TITLE
cannot prompt window inside chat window

### ISSUE THREAD

**Issue by pkueecslibo** [MicrosoftDocs/msteams-docs#1275]
I use teams and trying to talk to a bot. When click the login card for me to login to teams, it does not pop up login window.  If I type the url in browser, it can open correctly.

![44582252096632101](https://user-images.githubusercontent.com/10372089/72291511-5b6f2080-3604-11ea-8196-01c45960a20d.jpg)

**Comment by Gousia-MSFT** [comment]
@pkueecslibo Could you please try adding token.botframework.com in your valid domains of the manifest and re-upload the manifest?

**Comment by pkueecslibo** [comment]
No, this does not work. I actually tried this before, no help.











At 2020-01-13 19:52:59, "Gousia-MSFT" <notifications@github.com> wrote:

@pkueecslibo Could you please try adding token.botframework.com in your valid domains of the manifest and re-upload the manifest?

**Comment by Gousia-MSFT** [comment]
@pkueecslibo Could you please share your app-manifest with us? Please send out an email to microsoftteamsdevATmicrosoft.com if you do not want to share it here publicly.

**Comment by pkueecslibo** [comment]
Thanks for your reply. I actually share my app-manifest to another team member and they can use this with no issue. But in my teams I never  prompt a window and let me sign in.











在 2020-01-15 22:25:55，"Gousia-MSFT" <notifications@github.com> 写道：

@pkueecslibo Could you please share your app-manifest with us? Please send out an email to microsoftteamsdevATmicrosoft.com if you do not want to share it here publicly.

**Comment by pkueecslibo** [comment]
Hi @李博<mailto:libo_pku@126.com>,

Could you please share the repro steps for the issue you are seeing? What is the command to get the signin card? Please share a video recording of the issue for a better understanding.

Thanks,
Gousia.

From: 李博 <libo_pku@126.com>
Sent: Thursday, January 16, 2020 1:01 PM
To: MicrosoftDocs/msteams-docs <reply@reply.github.com>; Microsoft Teams Developer Support <microsoftteamsdev@microsoft.com>
Subject: [EXTERNAL] Re:Re: [MicrosoftDocs/msteams-docs] cannot prompt window inside chat window (#1275)

Thanks for your reply. I actually share my app-manifest to another team member and they can use this with no issue. But in my teams I never  prompt a window and let me sign in.






在 2020-01-15 22:25:55，"Gousia-MSFT" <notifications@github.com> 写道：

@pkueecslibo<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpkueecslibo&data=02%7C01%7Cv-gobegu%40microsoft.com%7C0ef66fb36ae84705e6ec08d79a5a9b56%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637147586867738594&sdata=1xORR33JspXxxjCzhJxFy5ih8uqoFjYSUeY3rHLXpWA%3D&reserved=0> Could you please share your app-manifest with us? Please send out an email to microsoftteamsdevATmicrosoft.com if you do not want to share it here publicly.

-

**Comment by Gousia-MSFT** [comment]
Please re-open with requested information.
