### ISSUE TITLE
Incoming webhook and cors policy

### ISSUE THREAD

**Issue by kkhanhluu** [MicrosoftDocs/msteams-docs#1276]
Inside a custom ms team tab app, i try to make a post request to incoming webook, but this request was blocked by cors policy. Did anyone face this problem? 
![image](https://user-images.githubusercontent.com/38130967/72337646-32619500-36c3-11ea-858f-3e769513195c.png)

**Comment by thomassvensen** [comment]
Yes, I have the same problem. I want to post to an incoming webhook from my web app, but cannot do it due to missing CORS policy support. I hope MS can add support for this?

**Comment by olivertran1** [comment]
I am seeing the CORS error but something strange happens - the post still goes through.

I can only imagine that somehow Teams (because it trusts whatever app is placed in that iframe) is somehow inserting some JS that handles XMLHTTP errors and posts message some other way.

**Comment by alexvdvalk** [comment]
I've also noticed that the post still goes through, despite the response error. In my case, I'm sending the request from a completely external page.

**Comment by JeetChaudhari** [comment]
I am also having same problem, message is received in teams however CORS error is generated at webpage.

**Comment by alcazes** [comment]
Any update on this issue ? I am facing the same issue at my side.

**Comment by Nikitha-MSFT** [comment]
Could you please follow the guide here to [Send Messages to Connectors and Webhooks](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-using). If you are still facing the issue please feel free to reopen the issue.
