### ISSUE TITLE
[Who Bot]Documentation On Who bot in Teams

### ISSUE THREAD

**Issue by Chekrii** [MicrosoftDocs/msteams-docs#1279]
Hi 

Can I get documentation regarding Who Bot.

Can I need few clarification regarding below queries:-

The card who bot is rendering below in teams. . Is this an Adaptive card 

What are the Graph API call that are doing for manager , peers and Works with.

How to show online and away status beside User Pic  and Graph API call.

<img width="396" alt="CardInWhoBot" src="https://user-images.githubusercontent.com/49824279/72521281-24597300-3881-11ea-8c6a-235b6e5ad342.PNG">

Can I also get the Deep link for Audio call and Video call for a person

Please help,
Thanks.

**Comment by Gousia-MSFT** [comment]
@Chekrii  Who Bot is a first party app and not everything implemented in Who Bot is publicly available. Here are few things that are available publicly.
1. Graph API to get manager: https://docs.microsoft.com/en-us/graph/api/user-list-manager?view=graph-rest-1.0&tabs=http
2. Graph API to get availability status:- https://docs.microsoft.com/en-us/graph/api/presence-get?view=graph-rest-beta&tabs=http
3. Currently, you can [deeplink to users chat](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links#deep-linking-to-a-chat).

**Comment by Chekrii** [comment]
* Can I get the name of card which is used in above Pic(Hero/Adaptive)

**Comment by Gousia-MSFT** [comment]
@Chekrii This is neither Hero card nor Adaptive card. Again this is a special kind of card which is not publicly available.
