### ISSUE TITLE
Teams for Linux starts typing text automatically after sharing your screen.

### ISSUE THREAD

**Issue by louisnow** [MicrosoftDocs/msteams-docs#1280]
Start a call, share your screen, After exiting the call or even before you finish the call, try typing a sentence or copy pasting text with ctrl+c ctrl+v. You should see very weird behaviour with random keys being pressed. The issue disappears if you exit teams.
OS: Linux Mint 19.3
Kernel: 5.0.0-37-generic
Teams Build No: teams_1.2.00.32451_amd64

**Comment by louisnow** [comment]
On the latest version of the build, the problem has stopped.
However it can reappear in sometimes as outlined below.
Start a call, share your screen and then end the call.
Put your computer to sleep, wake it up, on the login screen where you enter the password, the keyboard sometimes will behave erratically. I have to use the on screen keyboard to login and then problem disappears

Here are the logs from Teams around the time I put it to sleep and woke it up
```
Wed Jan 29 2020 22:03:34 GMT+0530 (India Standard Time) <3785> -- info -- Focusing main window 
Wed Jan 29 2020 22:03:34 GMT+0530 (India Standard Time) <3785> -- info -- Is foreground set to true 
Wed Jan 29 2020 22:03:35 GMT+0530 (India Standard Time) <3785> -- info -- Blur main window 
Wed Jan 29 2020 22:03:35 GMT+0530 (India Standard Time) <3785> -- info -- Is foreground set to false 
Wed Jan 29 2020 22:03:35 GMT+0530 (India Standard Time) <3785> -- event -- duration: 1.3450000286102295, name: desktop_foreground_duration, vdiMode: 0, eventpdclevel: 2,  
Wed Jan 29 2020 22:03:55 GMT+0530 (India Standard Time) <3785> -- info -- System has been suspended 
Wed Jan 29 2020 22:03:55 GMT+0530 (India Standard Time) <3785> -- info -- emit status indicator state change from Unknown to ConnectionError 
Wed Jan 29 2020 22:03:55 GMT+0530 (India Standard Time) <3785> -- info -- Added ConnectionError (current state: Unknown -> ConnectionError) 
Wed Jan 29 2020 22:05:32 GMT+0530 (India Standard Time) <3785> -- info -- System has been resumed 
Wed Jan 29 2020 22:05:37 GMT+0530 (India Standard Time) <3785> -- info -- Removing ConnectionError (current state: ConnectionError -> Unknown) 
Wed Jan 29 2020 22:05:37 GMT+0530 (India Standard Time) <3785> -- info -- Change status icon from ConnectionError to Unknown 
Wed Jan 29 2020 22:05:39 GMT+0530 (India Standard Time) <3785> -- event -- eventData: s::;m::1;a::3, inactiveTime: 0, name: machineState, vdiMode: 0, eventpdclevel: 2,  
Wed Jan 29 2020 22:05:39 GMT+0530 (India Standard Time) <3785> -- event -- eventData: s::;m::1;a::3, inactiveTime: 0, name: machineState, vdiMode: 0, eventpdclevel: 2,  
Wed Jan 29 2020 22:07:39 GMT+0530 (India Standard Time) <3785> -- info -- Machine has been idle for 0 seconds 
Wed Jan 29 2020 22:07:40 GMT+0530 (India Standard Time) <3785> -- event -- eventData: s::;m::1;a::4, inactiveTime: 0, name: machineState, vdiMode: 0, eventpdclevel: 2,  
Wed Jan 29 2020 22:07:47 GMT+0530 (India Standard Time) <3785> -- info -- Focusing main window ```

**Comment by Gousia-MSFT** [comment]
@louisnow We cannot reproduce the issue on our side. Could you please let us know the mint flavour/desktop environment you are on so that we will try it on the same system?

**Comment by louisnow** [comment]
Hi @Gousia-MSFT 
The typing error occurs without having to go to sleep even. I just had a call where another person was added to the call and after the call was over, the typing error presented itself. Quitting teams fixed it. 
I always use two monitors either external only or dual display (don't know if that could be it)
Here is the output of `inxi -Fxz` with the info about my two displays and X.Org driver 

```
System:
  Host: E480 Kernel: 5.3.0-28-generic x86_64 bits: 64 compiler: gcc 
  v: 7.4.0 Desktop: Cinnamon 4.4.8 Distro: Linux Mint 19.3 Tricia 
  base: Ubuntu 18.04 bionic 
Machine:
  Type: Laptop System: LENOVO  v: ThinkPad E480 
  serial: <filter> 
Battery:
  ID-1: BAT0 charge: 42.7 Wh condition: 42.7/45.7 Wh (93%) 
  model: SMP 01AV447 status: Full 
  Device-1: hidpp_battery_0 
  model: Logitech Wireless Mobile Mouse MX Anywhere 2S charge: 100% 
  status: Discharging 
CPU:
  Topology: Quad Core model: Intel Core i5-8250U bits: 64 type: MT MCP 
  arch: Kaby Lake rev: A L2 cache: 6144 KiB 
  flags: lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 28800 
  Speed: 1790 MHz min/max: 400/3400 MHz Core speeds (MHz): 1: 1790 2: 1588 
  3: 2294 4: 1847 5: 1701 6: 2575 7: 2716 8: 1590 
Graphics:
  Device-1: Intel UHD Graphics 620 vendor: Lenovo driver: i915 v: kernel 
  bus ID: 00:02.0 
  Display: x11 server: X.Org 1.19.6 driver: modesetting unloaded: fbdev,vesa 
  resolution: 1366x768~60Hz, 1920x1080~60Hz 
  OpenGL: renderer: Mesa DRI Intel UHD Graphics 620 (Kabylake GT2) 
  v: 4.5 Mesa 19.2.8 direct render: Yes
````

**Comment by Gousia-MSFT** [comment]
@louisnow We tried to reproduce the problem on Linux Mint but we did not see the issue. Could you please run the following command when the problem happens again?

> sudo lsof -Fn -nPd txt | sed -n '/^n\/proc/!s/^n//p' | 
> sort -u | xargs -d '\n' grep -l XTestFakeKeyEvent
> 

This will list the files that are currently open and mapped as executable to any process and greps for XTestFakeKeyEvent in them. This is a guess that some process might be generating XTestFakeKeyEvent events.

**Comment by louisnow** [comment]
I think this could be a device specific issue.
Here's exactly what I tried:
Start a video call, share screen, stop sharing screen. The problem has now started.
Open a text editor and type `asd`, the key presses won't show up for a second then suddenly start printing `a` continuously. It's as if it believes the key is being held.
I connected an external keyboard. External keyboard works and key presses are fine but not the Thinkpad's keyboard.
With the help of the external keyboard I ran the command but I'm afraid our guess was wrong about XTestFakeKeyEvents. Here's the output
```
lsof: WARNING: can't stat() fuse.gvfsd-fuse file system /run/user/1000/gvfs
      Output information may be incomplete.
lsof: WARNING: can't stat() fuse file system /run/user/1000/doc
      Output information may be incomplete.
```
Here's what else I did try though, when the other person accepts the call from teams for android, the problem does not occur. The problem occurs when we're both on Linux using the native teams app. The other system is Ubuntu 18.04.4 LTS and that has the problem as well so this isn't just limited to Linux Mint. It might be all Laptops or just Thinkpads? External/Secondary keyboards work fine. Have not tested on a desktop.

**Comment by louisnow** [comment]
I ran the command as a bash script 
```
#!/bin/bash

while true; do

    sudo lsof -Fn -nPd txt | sed -n '/^n/proc/!s/^n//p' | sort -u | xargs -d '\n' grep -l XTestFakeKeyEvent
    echo "\n"
    sleep 2

done
```

Now when the problem occurred, there still wasn't any change in the output of the log. So maybe XTestFakeKeyEvents isn't the culprit.

**Comment by RudolfTomori-MSFT** [comment]
Could it happen because the rendering process is overloaded? Do you see some other issues when the keyboard issue is active? Like resizing the GUI window would be too slow? Does mouse pointer move smoothly over the teams window? Could you check system process monitor if you see some CPU usage spike when the keyboard issue is active?

**Comment by RudolfTomori-MSFT** [comment]
What you are experiencing seems similar to https://forums.lenovo.com/t5/ThinkPad-11e-Windows-13-E-and/E480-keyboard-problems/td-p/4190409 and the bug description on launchpad https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1787782. The reporter claims the issue is gone after updating BIOS and firmware. Could you try this?

**Comment by louisnow** [comment]
Hi @RudolfTomori-MSFT,
Thanks for the quick reply. My bios is up to date so I don't think that is the problem although the description of the bug on launchpad is very similar. Installing firmware updates besides the bios will be tricky for me as I don't have windows, I'll figure something out. I'll keep you posted about the results after updating my firmware.
My mouse seems to work fine, however Teams does use comparably more CPU when the problem is occurring.

**Comment by Gousia-MSFT** [comment]
@louisnow Any update on this? Are you still facing any issue?

**Comment by Gousia-MSFT** [comment]
Please re-open if you are still facing the issue.
