### ISSUE TITLE
Could you check the typo before you publish? 

### ISSUE THREAD

**Issue by iyabchen** [MicrosoftDocs/msteams-docs#1281]
All those typo, like "Publish to you organization app catalog", makes the page looks like phishing text. Could you run spell check before publish? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73c78d6b-1600-b57a-e9b8-ef48d6e7223b
* Version Independent ID: 86b8e707-77a3-3a6e-53cc-b95e7bb2a622
* Content: [Distribute your app - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/overview)
* Content Source: [msteams-platform/concepts/deploy-and-publish/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/deploy-and-publish/overview.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **anclear**

**Comment by laujan** [comment]
👍 Thank you for the catch.  I have made the correction and pushed it to the live branch.
