### ISSUE TITLE
Deep Link to Start Meeting

### ISSUE THREAD

**Issue by PGBartlett** [MicrosoftDocs/msteams-docs#1284]
Is it possible for my app to deep link to Teams to start a scheduled meeting by phone or video?

**Comment by Subhasish-msft** [comment]
yes. if it is a tab, then you can use microsoftTeams.executeDeepLink(<meetingURL>).

You can refer this [link](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links) for more detail
