### ISSUE TITLE
Notification alert not raised in Teams User when messages are replied from bot in Teams Channel

### ISSUE THREAD

**Issue by rijaljayanta** [MicrosoftDocs/msteams-docs#1287]
I have turn on the notification in my Team's setting. As per the documentation I have set the TeamsChannelData objects Notification.Alert property to true. But the Banner and feed notifications are not raised.

I used this code snippet to turn on Notification.Alert property to true.
`  message.TeamsNotifyUser();`

For reference:
https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-basics?tabs=dotnet

**Comment by Trinetra-MSFT** [comment]
@rijaljayanta , Are you trying to set attachment in message or it is Text?

**Code snippet for sending as an attachment**
  ```
 var message = MessageFactory.Attachment(new Attachment() { },"Hey, This is Test Notification alert");
message.TeamsNotifyUser();
```

**Sending a Text**
```
var message = Messagefactory.Text("Hey, This is Test Notification alert");
message.TeamsNotifyUser();
```

Could you please give a try to above snippet and let us know if this doesn't help you.

**Comment by rijaljayanta** [comment]
@Trinetra-MSFT Thanks for your response.

I tried both attachment and text messages using the same code snippet before, but it's not working in the case of a message reply in a conversation thread of Teams Channel.

When messages are posted by a bot in Teams channel in a new thread, notification alert is raised. But when the message is replied in that thread notification alert not raised.
 
Does this mean, Notification alert doesn't work in the case of message replies on existing conversation thread?

**Comment by Trinetra-MSFT** [comment]
@rijaljayanta , It should work for existing conversation too. Could you please share some sample code what you are trying out so we can take a look?

**Comment by rijaljayanta** [comment]
@Trinetra-MSFT, I have used the below code to reply to a conversation in a channel. This code replies to the existing message thread successfully but I'm not getting notification alert. I have turned on the notification in my Teams account setting too. Is there anything I'm missing?
```
            var message = MessageFactory.Text("Test Notification alert");
            message.TeamsNotifyUser();

            MicrosoftAppCredentials.TrustServiceUrl(_serviceUrl, DateTime.MaxValue);
            var connectorClient = new ConnectorClient(new Uri(_serviceUrl), _microsoftAppCredentials);

            var conversationId = "19:xxxxxxxxxxxx@thread.skype;messageid=1579686666434";
            var activityId = "1579686666434";

            await connectorClient.Conversations.ReplyToActivityAsync(conversationId, activityId, message);
```

**Comment by Trinetra-MSFT** [comment]
Hi @rijaljayanta,  We tried your code at our end it seems you are sending the wrong conversation Id because of that it is not raised. 
Could you please try below piece of code?

```
var message = MessageFactory.Text("Test Notification alert");
            message.TeamsNotifyUser();
            MicrosoftAppCredentials.TrustServiceUrl(stepContext.Context.Activity.ServiceUrl, DateTime.MaxValue);
            var connectorClient = new ConnectorClient(new Uri(stepContext.Context.Activity.ServiceUrl), "<<AppId>>", "<<AppPassword>>");
            var conversationId = stepContext.Context.Activity.Conversation.Id;
            var activityId = "a:18xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxdt";
            await connectorClient.Conversations.ReplyToActivityAsync(conversationId, activityId, message); 
```

![image](https://user-images.githubusercontent.com/50989436/73533581-30c6f980-4445-11ea-9b1f-2390cfd4dfe8.png)

**Comment by rijaljayanta** [comment]
Hi @Trinetra-MSFT , I think my case is somewhat different than you are  expecting. Actually, I'm trying to reply the message in Teams channel instead of **private chat message**. 

As per the code snippet below, I am getting notification alert for the **firstMessage** but not in the case of the **secondMessage**. Here the secondMessage the reply message in existing conversation thread of the Teams Channel.
```
            var firstMessage = MessageFactory.Text("Hey, This is First Test Notification alert");

            var conversationParameters = new ConversationParameters
            {
                IsGroup = true,
                ChannelData = new TeamsChannelData
                {
                    Channel = new ChannelInfo(channelId),
                    Notification = new NotificationInfo() { Alert = true }
                },
                Activity = (Activity)attachmentMessage,
            };

            MicrosoftAppCredentials.TrustServiceUrl(_serviceUrl, DateTime.MaxValue);
            var connectorClient = new ConnectorClient(new Uri(_serviceUrl), _microsoftAppCredentials);

            var response = await connectorClient.Conversations.CreateConversationAsync(conversationParameters);

            var secondMessage = MessageFactory.Text("Hey, This is Second Test Notification alert");
            secondMessage.TeamsNotifyUser();

            await connectorClient.Conversations.ReplyToActivityAsync(response.Id, response.ActivityId, (Activity)secondMessage);
```

Could you please review the above code and give me a pointer where I am making mistake?

**Comment by Trinetra-MSFT** [comment]
@rijaljayanta , TeamsNotifyUser doesn't work in channel. There is a Open Bug for this. We are working on it, We will update you once it is fixed.
