### ISSUE TITLE
Is there a callback for full app uninstall?

### ISSUE THREAD

**Issue by synth** [MicrosoftDocs/msteams-docs#1288]
The tab documentation details how to handle removal of a tab by registering a `removalUrl` and `registerOnRemoveHandler`. 

However, if a user uninstalls the app, the tabs will be uninstalled along with it, but the callbacks and urls will not get called. 

Is there a handler that can be invoked when the app is uninstalled so that we can do data cleanup on all the added services (tabs, connectors, extensions, bots).

**Comment by Trinetra-MSFT** [comment]
@synth , I think we can close this as discussion for removing app is already going on another thread. Please feel free to reopen.

**Comment by synth** [comment]
Sure @Trinetra-MSFT. Thanks. My only comment is perhaps the behavior in https://github.com/OfficeDev/microsoft-teams-library-js/issues/303 should be added to the docs :) thx for your help.
