### ISSUE TITLE
Developer Preview link broken

### ISSUE THREAD

**Issue by BukeMan** [MicrosoftDocs/msteams-docs#1289]
The Developer Preview link in the first paragraph is broken. 
I assume the correct link is following: https://docs.microsoft.com/en-us/microsoftteams/platform/resources/dev-preview/developer-preview-intro

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac64d14f-aec8-9dd6-e987-d2325de46fd6
* Version Independent ID: ba050a58-d98a-68f7-3190-8001d2a9d12c
* Content: [Registering a calling and meeting bot for Microsoft Teams - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/calls-and-meetings/registering-calling-bot)
* Content Source: [msteams-platform/bots/calls-and-meetings/registering-calling-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/bots/calls-and-meetings/registering-calling-bot.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **anclear**

**Comment by Trinetra-MSFT** [comment]
This is fixed please check.

**Comment by BukeMan** [comment]
looks good now. thank you!
