### ISSUE TITLE
Fetching user's email id from Teams channel bot: TeamsInfo.getMembers() is not working/missing

### ISSUE THREAD

**Issue by Garv-Sharma** [MicrosoftDocs/msteams-docs#1290]
Required TeamsActivityHandler and TeamsInfo but the file teamsInfo.ts is missing from node modules, so getMembers() is undefined. 
I used this [link](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/get-teams-context?tabs=typescript&source=docs#fetching-the-team-roster) to fetch user profile.

**Comment by Trinetra-MSFT** [comment]
@Garv-Sharma,
Could you please try take a look at this sample for [TeamsConversationBot](https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/javascript_nodejs/57.teams-conversation-bot)?
Here is the sample code which will return the roaster of members in a channel when your bot installed in channel.
```
 this.onMessage(async (context, next) => {
            const members = await TeamsInfo.getMembers(context);
            console.log(members);
            await next();
        });
```
