### ISSUE TITLE
Knowing who clicked an action on a connector card

### ISSUE THREAD

**Issue by jmeredithklein** [MicrosoftDocs/msteams-docs#1295]
Are there any plans to add functionality to connector cards that enable you to know who clicked an action on a connector card similar to bot cards? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28316a67-22fa-8a05-1ae0-fbe1c5720ef9
* Version Independent ID: 8a250e46-2a30-af86-839d-9f83a8b48041
* Content: [Sending messages to Connectors and Webhooks - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-using)
* Content Source: [msteams-platform/webhooks-and-connectors/how-to/connectors-using.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/webhooks-and-connectors/how-to/connectors-using.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **anclear**

**Comment by Subhasish-msft** [comment]
No, we don't. This would be a good feature to consider for future connector-like functionality though.

**Comment by Trinetra-MSFT** [comment]
Please raise a [uservoice ](https://microsoftteams.uservoice.com/) so we can take this as future.
