### ISSUE TITLE
Sample code requested for Notifications in Tabs

### ISSUE THREAD

**Issue by GauravES** [MicrosoftDocs/msteams-docs#1301]
Are these notifications Web Push Notifications or something else?  Request sample code for web app to send notifications to a tab, particularly when the tab is not in focus.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce494c52-9c5f-d294-c304-53ac466fa3ea
* Version Independent ID: ebd112aa-71c4-a7d6-aa9f-6e14c50be25c
* Content: [Request device permissions for your Microsoft Teams tab - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/native-device-permissions)
* Content Source: [msteams-platform/tabs/how-to/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tabs/how-to/native-device-permissions.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **anclear**

**Comment by Gousia-MSFT** [comment]
@GauravES These are prompts that will ask the user to consent to access the device permissions your application needs. Could you please try adding these to your tab as described and see the experience.

**Comment by GauravES** [comment]
Thanks - the prompt for permissions is fine and described in the article;  There are many kind of notifications available in the web app domain.  In Safari, APNS and in Chrome, FCM.  There are web push notifs using service workers. (https://developers.google.com/web/fundamentals/push-notifications).  And there are mere desktop notifications that let a web page use native popups to show alerts.   

Perhaps this information is already somewhere in the docs, but I could not readily find it.  Before I code the back end app, I just wanted to know what capabilities are meant to work with Notifications.

Thanks

**Comment by Gousia-MSFT** [comment]
@GauravES We do not support Web Push Notifications in the Teams Desktop Client today and that's not something we plan to change. We are currently working on support for pushing notifications to users in Teams via our Graph APIs But we don't have a firm ETA to share with you.

**Comment by GauravES** [comment]
Thanks for the clarification.  If not Web Push notifications, then what kind of Notifications are these that a page can send?  And where will they appear? The page only has a code snippet for asking the user to allow/permit notifications, but no code snippets for sending a notification.

**Comment by Gousia-MSFT** [comment]
@GauravES The page talks about the steps to see these notification from within your tab. To do this, you need to update your [app's manifest page ](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/native-device-permissions#properties)by adding device permissions. Here is a [sample code](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/native-device-permissions#checking-permissions-from-your-tab) you could try out.

**Comment by GauravES** [comment]
I think we are not understanding each other. The Sample code only refers to how to ask for notification permissions.  We still dont have any sample code for how to *send* a notification, after we have the permissions.

**Comment by Gousia-MSFT** [comment]
@GauravES You could send the notification back to the web page using new Notification(). Please try the sample [here](https://www.pubnub.com/blog/sending-desktop-html5-notifications-for-web-browsers-with-pubnub/)

**Comment by Gousia-MSFT** [comment]
Please re-open if you have any further queries.
