### ISSUE TITLE
Mobile Support for Tabs

### ISSUE THREAD

**Issue by icelandgrecian** [MicrosoftDocs/msteams-docs#1302]
Any news on when mobile support for tabs is coming?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e5840ee-09e8-93a6-51d8-508eef388b0a
* Version Independent ID: 621a526e-59dd-e81a-ee89-6a714bc055c8
* Content: [Tabs on mobile - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/design/tabs-mobile)
* Content Source: [msteams-platform/tabs/design/tabs-mobile.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tabs/design/tabs-mobile.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **anclear**

**Comment by Trinetra-MSFT** [comment]
Please take a look at [Tabs on Mobile](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/design/tabs-mobile).

**Comment by icelandgrecian** [comment]
This doesn´t answer my question, it says 'Full support for tabs on mobile clients is coming soon' and it has said this since about October. When we look some times apps show on the mobile app and sometimes they don´t and the teams context doesn´t seem to provide all the information we need if we can get the app to actually show on the mobile device, for example userRoleType is missing and other values are totally different to as they appear on the desktop.

**Comment by Trinetra-MSFT** [comment]
@icelandgrecian , Full support for tabs in mobile is on our roadmap. We will update you once it will be rolled out.
