### ISSUE TITLE
[iOS -Notifications issue] - Showing only active organization notification when two or more accounts/organisations created

### ISSUE THREAD

**Issue by jauzcanga** [MicrosoftDocs/msteams-docs#1303]
I have two accounts/organizations on my iPhone's MSteams-app.

The problem is, I'm receiving notifications only from the active one, so I have to be opening and changing organizations constantly just to see if I'm missing something.

Currently on iPhone 11

**Comment by Abhijit-MSFT** [comment]
@jauzcanga, you get noticification like in the below images. Are you not getting these notification?
On Desktop -
![image](https://user-images.githubusercontent.com/48427340/73241667-b25e2380-41c8-11ea-8f2b-27dee0a8045e.png)

On Mobile -
![image](https://user-images.githubusercontent.com/48427340/73241739-f6512880-41c8-11ea-857f-689c900057d8.png)

**Comment by Trinetra-MSFT** [comment]
Please feel free to reopen if you still facing this issue.
