### ISSUE TITLE
Couldn't not trigger webhook using browser API

### ISSUE THREAD

**Issue by luizcieslak** [MicrosoftDocs/msteams-docs#1305]
Hi!

my company recently moved to Teams from Slack and we are migrating the current webhooks to it. 

Following the [documentation](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-using#setting-up-a-custom-incoming-webhook) the cURL works fine but when I put it in a browser, it gives me an `Network Error`, not returning a HTTP Status.

example:
```js
fetch("https://outlook.office.com/webhook/1e1e55d5-bd0e-4f9a-a758-777013e30caa@e0b90a4b-c4ab-46c6-8c8f-98d332fc2db0/IncomingWebhook/3a0bf00f31cf4346b3cd5f91669f6361/1cd8d6fa-aa29-47aa-9297-c4988a0c3c39", {
    method: "POST",
    headers: {
      Accept: "application/json",
      "Content-Type": "application/json"
    },
    body: JSON.stringify(examplePayload)
  })
```

I noticed that the URL has an `@`, tried to change to `%40` but the problem remains.

I uploaded a [codesandbox](https://codesandbox.io/s/youthful-breeze-jor5u) to repro the issue.

---

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28316a67-22fa-8a05-1ae0-fbe1c5720ef9
* Version Independent ID: 8a250e46-2a30-af86-839d-9f83a8b48041
* Content: [Sending messages to Connectors and Webhooks - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-using#feedback)
* Content Source: [msteams-platform/webhooks-and-connectors/how-to/connectors-using.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/webhooks-and-connectors/how-to/connectors-using.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **anclear**

**Comment by Trinetra-MSFT** [comment]
@luizcieslak , Could you please try to POST following message card to [webhook url](https://outlook.office.com/webhook/1e1e55d5-bd0e-4f9a-a758-777013e30caa@e0b90a4b-c4ab-46c6-8c8f-98d332fc2db0/IncomingWebhook/3a0bf00f31cf4346b3cd5f91669f6361/1cd8d6fa-aa29-47aa-9297-c4988a0c3c39) using fiddler? Let me know if it gives the correct result or not? 
```
{
 "@type": "MessageCard",
  "@context": "http://schema.org/extensions",
  themeColor: "0076D7",
  summary: "Larry Bryant created a new task",
  sections: [
    {
      activityTitle:
        "![TestImage](https://47a92947.ngrok.io/Content/Images/default.png)Larry Bryant created a new task",
      activitySubtitle: "On Project Tango",
      activityImage:
        "https://teamsnodesample.azurewebsites.net/static/img/image5.png",
      facts: [
        {
          name: "Assigned to",
          value: "Unassigned"
        },
        {
          name: "Due date",
          value: "Mon May 01 2017 17:07:18 GMT-0700 (Pacific Daylight Time)"
        },
        {
          name: "Status",
          value: "Not started"
        }
      ],
      markdown: true
    }
  ],
  potentialAction: [
    {
      "@type": "ActionCard",
      name: "Add a comment",
      inputs: [
        {
          "@type": "TextInput",
          id: "comment",
          isMultiline: false,
          title: "Add a comment here for this task"
        }
      ],
      actions: [
        {
          "@type": "HttpPOST",
          name: "Add comment",
          target: "http://..."
        }
      ]
    },
    {
      "@type": "ActionCard",
      name: "Set due date",
      inputs: [
        {
          "@type": "DateInput",
          id: "dueDate",
          title: "Enter a due date for this task"
        }
      ],
      actions: [
        {
          "@type": "HttpPOST",
          name: "Save",
          target: "http://..."
        }
      ]
    },
    {
      "@type": "ActionCard",
      name: "Change status",
      inputs: [
        {
          "@type": "MultichoiceInput",
          id: "list",
          title: "Select a status",
          isMultiSelect: "false",
          choices: [
            {
              display: "In Progress",
              value: "1"
            },
            {
              display: "Active",
              value: "2"
            },
            {
              display: "Closed",
              value: "3"
            }
          ]
        }
      ],
      actions: [
        {
          "@type": "HttpPOST",
          name: "Save",
          target: "http://..."
        }
      ]
    }
  ]
}
```
It should give you the card in channel.

![image](https://user-images.githubusercontent.com/50989436/73443461-b337b680-437c-11ea-95d8-0d7867d0e2db.png)

**Comment by luizcieslak** [comment]
@Trinetra-MSFT I couldn't make the request using [jsfiddle](https://jsfiddle.net/obzkt7a3/4/) because of CORS request block :/

However, the [codesandbox](https://codesandbox.io/s/youthful-breeze-jor5u) link show the error I'm receiving.

**Comment by Gousia-MSFT** [comment]
@luizcieslak The target url you are setting should be a https url. Could you please try setting a https url for target and see if that fixes the issue?

**Comment by luizcieslak** [comment]
@Gousia-MSFT Hi! All the urls are https: in the sandbox, jsfiddle and @Trinetra-MSFT example given. All of them still gives the same error.

Could you reproduce that locally?

**Comment by Gousia-MSFT** [comment]
@luizcieslak I cannot repro the issue on my side. Could you please share a screenshot of the error you are seeing?

**Comment by luizcieslak** [comment]
@Gousia-MSFT are you using the browser to make the tests or cURL? 

Here is the screenshot from codesandbox. Is not very helpful tho, the request doesn't even complete. I'm afraid that maybe it could be a CORS error as well.

<img width="1109" alt="image" src="https://user-images.githubusercontent.com/14146176/74650546-bdb9c480-5160-11ea-8b0c-2f3e9cd2f8a4.png">

**Comment by Gousia-MSFT** [comment]
@luizcieslak We could repro the issue with your code.. We are checking this internally.

**Comment by Gousia-MSFT** [comment]
@luizcieslak fetch is Browser api and default mode is CORS. Could you please try setting request mode to no-cors and see if that fixes the issue?
https://developer.mozilla.org/en-US/docs/Web/API/Request/mode

**Comment by luizcieslak** [comment]
Hi @Gousia-MSFT! with `no-cors` it worked. Note that axios can't handle that (see https://github.com/axios/axios/issues/1358).

Thanks for the help. I'm clossing the issue now.
