### ISSUE TITLE
DevTools not opening on Mac

### ISSUE THREAD

**Issue by RobDM** [MicrosoftDocs/msteams-docs#1307]
When I first enabled Developer Preview mode I was able to open the web inspector on a personal tab, but now a day later this is no longer working and apparently stuck that way.  The Developer menu no longer appears, and the usual CMD+OPT+I key combo doesn't do anything.

I've verified in the Profile > About section that the Developer preview option is checked.  I've tried closing, killing, and restarting Teams.  I've tried turning Developer preview off and back on again.  I've tried rebooting the computer.  Problem still persists.

![msteams-nodevtools](https://user-images.githubusercontent.com/4323344/73277855-f7259280-41a7-11ea-8ed8-954cbf37d2b0.jpg)

**Comment by Gousia-MSFT** [comment]
@RobDM Did you follow this documentation to open [Devtools for Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/developer-tools).

**Comment by RobDM** [comment]
@Gousia-MSFT Yes, those instructions for bringing up the dev tools for Mac were working the first day I enabled developer preview.  But they no longer work now, even though developer preview is still enabled.

**Comment by Gousia-MSFT** [comment]
@RobDM Thanks!! I am checking with with the team internally.

**Comment by RobDM** [comment]
I've verified that this is reproducible on other Mac machines, not isolated to my setup.

**Comment by RobDM** [comment]
Another update, I think I've found a partial workaround.  Once switching to Developer Preview mode, Teams must be **fully shut down and restarted** before the Open Dev Tools option will appear in the right-click menu for the Teams icon in the Mac taskbar.  So I'm able to get to the web inspector now.

So what's still broken is as follows:

- Keyboard shortcut for web inspector doesn't work on Mac desktop app as advertised in [documentation](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/developer-tools)
- Open Dev Tools option doesn't appear in right click menu on Mac desktop app after turning Developer Preview mode on until Teams is fully shut down and restarted

**Comment by Gousia-MSFT** [comment]
@RobDM Thanks for letting us know! We are looking into it.

**Comment by Gousia-MSFT** [comment]
@RobDM We have raised a bug for this and we are tracking it internally
