### ISSUE TITLE
how do i create channel conversation in python and javascript

### ISSUE THREAD

**Issue by tingyiy** [MicrosoftDocs/msteams-docs#1308]
it looks like only the C# sample does that. javascript and python creates 1 to 1 messages instead

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ad9f167-7d29-f933-7b47-60bd744899b1
* Version Independent ID: 8097fcbd-adcc-ce49-a378-426c65af9296
* Content: [Send proactive messages - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/send-proactive-messages?tabs=javascript#feedback)
* Content Source: [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/bots/how-to/conversations/send-proactive-messages.md)
* Product: **msteams**
* GitHub Login: @clearab
* Microsoft Alias: **anclear**

**Comment by Abhijit-MSFT** [comment]
@tingyiy, this [document](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/channel-and-group-conversations?tabs=python) will help you with Channel/Group conversation using python.
