### ISSUE TITLE
Why the documentation is gone

### ISSUE THREAD

**Issue by jonathanranger** [MicrosoftDocs/msteams-docs#1311]
Why can't I reach The Microsoft Bot builder SDK Teams Extensions documentation anymore ?
https://msdn.microsoft.com/en-us/microsoft-teams/bots

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cbdb8216-60c7-a0a1-7eb6-02d42d783292
* Version Independent ID: 77a75dd2-6f45-bc76-b968-0cf58c427ef5
* Content: [Requested page cannot be found. - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/redirects/bots?redirectedfrom=MSDN#feedback)
* Content Source: [msteams-platform/404.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/404.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **anclear**

**Comment by jonathanranger** [comment]
See https://www.npmjs.com/package/botbuilder-teams for the link that redirect here.

**Comment by laujan** [comment]
Hi @jonathanranger. If you are looking for current documentation, bots for Microsoft teams (v4 and above) are built on the [Microsoft Bot Framework](https://dev.botframework.com/).  *See* [Conversational Bots](https://review.docs.microsoft.com/microsoftteams/platform/bots/what-are-bots). If you are looking for documentation on bots v3, *see* [Add bots to Microsoft Teams apps](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bots-overview?branch=master).

**Comment by jonathanranger** [comment]
Pretty fast response. Thanks !

**Comment by laujan** [comment]
👍
