### ISSUE TITLE
Clarification Requested:  15000 ops in 3600 secs for the entire bot.

### ISSUE THREAD

**Issue by GauravES** [MicrosoftDocs/msteams-docs#1312]
Clarification Requested:  15000 ops in 3600 secs for the entire bot across all tenants. 

If the main activity of the bot was to respond to user messages, such as a LUIS bot or a remote advisor bot, does this mean that the bot is limited to sending 15000/3600 = ~4 messages/sec as measured over an hour?

Are there any limits on inbound messages (say from Teams end users to the bot?)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a57254c9-963d-ea1d-ecaf-dd0e7913526c
* Version Independent ID: 610c8514-bd72-46cc-75f1-991e2242019b
* Content: [Rate limiting - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/rate-limit)
* Content Source: [msteams-platform/bots/how-to/rate-limit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/bots/how-to/rate-limit.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **anclear**

**Comment by Trinetra-MSFT** [comment]
@GauravES , Yes, You understood it right. [Bot per data center limit](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/rate-limit#bot-per-data-center-limit) is 15000 operations allowed within 3600 sec.However if you concerned about the limit you can always implement the [Back-Off strategy](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/rate-limit#example-backoff) as described. Here is the [Per bot per thread limit](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/rate-limit#per-bot-per-thread-limit)

**Comment by GauravES** [comment]
As feedback, we are porting  a remote advisor solution for 100K plus employee companies from SfB Trusted Apps to Teams,  and expect 100+  support sessions to be ongoing during most of the peak shifts. That would be ~100 threads, and although the per thread limit is ok for any one of those 100 conversations, across 100 conversations and replies mediated by the bot, the 4 messages/second will easily get hit. 

Are there exception-based processes for requesting higher limits (similar to access to Protected APIs) ?

Can you clarify the meaning of "data center" in this context? What is the "data center" used for a Bot and how can the bot use multiple data centers?

Thanks

**Comment by Trinetra-MSFT** [comment]
You mentioned in the document you can implement back-off strategy for handling the exception for higher limits. The term data center represents your bot running for multiple tenants or multiple servers.
