### ISSUE TITLE
Link contentUrl to replacement token documentation

### ISSUE THREAD

**Issue by jsuddsjr** [MicrosoftDocs/msteams-docs#1314]
The URL specified in `contentUrl` for the tab can contain replacement tokens.
* `{userObjectId}` - AAD GUID for the current user
* `{theme}` - The selected theme name,  "default" (light), "dark" or "contrast"
* `{locale}` - The client locale, such as "en-us"

There may be others.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f94a488-d636-92b3-21eb-c88744c8f272
* Version Independent ID: 7b3413f4-9ade-accf-5cb2-83fead11a32a
* Content: [Manifest schema reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema)
* Content Source: [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/resources/schema/manifest-schema.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **anclear**

**Comment by jsuddsjr** [comment]
I just realized these tokens are documented, but they are not linked from this page. It would be helpful to include a link to [Get context for your tab](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/access-teams-context).

**Comment by laujan** [comment]
Updated on master, will go live this week. #1314.
