### ISSUE TITLE
How do you get the bearer token? And what's the base url for "POST /v3/conversations"

### ISSUE THREAD

**Issue by matula** [MicrosoftDocs/msteams-docs#1317]
Under the "Example" heading, it says you must have a bearer token, but how does the bot/app get that token? Then, after I get the token, what's the full endpoint to post the message? Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ad9f167-7d29-f933-7b47-60bd744899b1
* Version Independent ID: 8097fcbd-adcc-ce49-a378-426c65af9296
* Content: [Send proactive messages - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/send-proactive-messages?tabs=dotnet#examples)
* Content Source: [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/bots/how-to/conversations/send-proactive-messages.md)
* Product: **msteams**
* GitHub Login: @clearab
* Microsoft Alias: **anclear**

**Comment by clearab** [comment]
That portion is only applicable if you're not using the SDK to create and send messages (using the REST endpoints directly). If that is what you're doing you can learn more about using them here: https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-quickstart?view=azure-bot-service-4.0.

@laujan it might make sense to collapse the JSON examples (and accompanying text) into a tab with the other samples.
