### ISSUE TITLE
Scroll bar usability

### ISSUE THREAD

**Issue by michaewlewis** [MicrosoftDocs/msteams-docs#1324]
If you zoom out to 85% or lower, the horizontal scroll bar is not easily accessible in MS Teams. There is only one pixel available on the scroll bar before it switches to the window sizing pointer. Even at 100%, there is only 3 pixels available before it switches to window sizing. If side scrolling with the wheel worked consistently, it would be less of a problem, but that only works some of the time, too.
Scroll bar needs to either be a fixed size or have a minimum size, preferably not less than 10 pixels that can actually be accessed.

**Comment by Gousia-MSFT** [comment]
@michaewlewis Thanks for reaching out to us. I have forwarded this to the right team.

**Comment by bzyg7b** [comment]
@Gousia-MSFT where is the correct place to log Teams bugs?

**Comment by Gousia-MSFT** [comment]
@bzyg7b You can use the Report a problem option under Help tag.
![image](https://user-images.githubusercontent.com/45553518/73814877-4ef87500-480a-11ea-91eb-c1505def5095.png)

**Comment by Gousia-MSFT** [comment]
@michaewlewis Thanks for reporting this. We have raised a bug on this and we are tracking it internally.
