### ISSUE TITLE
Vague conditions for triggering user consent flow

### ISSUE THREAD

**Issue by beauzeaux** [MicrosoftDocs/msteams-docs#1327]
The conditions for triggering the user consent flow are currently pretty vague. Can we get a clear enumeration of what manifest changes constitute a 'new capability'?

Some examples:

- Addition of valid domains
- Adding contents to the 'webApplicationInfo' section
- Messaging Extensions added when there is already a bot? 

Also why does a version bump necessitate an upgrade? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d29cfd09-9067-d939-960a-b33931707c4d
* Version Independent ID: 6c0b95fa-b5b4-5ace-15e7-55d2b007b792
* Content: [Post publishing - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/post-publish/overview#updating-your-existing-teams-app)
* Content Source: [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/deploy-and-publish/appsource/post-publish/overview.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **anclear**

**Comment by Gousia-MSFT** [comment]
@beauzeaux A teams app mainly has 4 capabilities: [Tabs](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs), [Bots](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/what-are-bots), [Message Extension](https://docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/what-are-messaging-extensions) and [Connector](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/what-are-webhooks-and-connectors). Your app can contain any one, or all the four capabilities. All the capabilities you wish to include in your app should be listed out in the manifest file. Suppose if you have  a Tab and a bot build in your app and you have uploaded the manifest, and now you want to add Message Extension as a new capability in your app, then you need to add it in the app's manifest. Now this is a manifest change and you need to re-install the app to see your new capability.
Apart from adding a new capability, there can be other changes in the manifest:
1. Addition of valid Domains: [Valid Domains](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/content-page#valid-domains) lists out the URL domains used in your tab.
2. Adding contents to the 'webApplicationInfo' section: This section is added if you want to introduce Tabs SSO in your app.
3. Apart from these, there can be changes like change in the name of the app/ name of developer/ any other change in the manifest.

> Also why does a version bump necessitate an upgrade?

- Incrementing the version number is used to indicate the availability of a newest version of app. This is mainly used if your app is already installed by users in your tenant and you want to give a newer version to the app.

**Comment by beauzeaux** [comment]
If it is only addition of a tab/bot/messaging extension/connector, can we explicitly list those as the only flows that necessitate user consent? 

> Also why does a version bump necessitate an upgrade?

I phrased that incorrectly, I meant why does a version change require user consent? I have just tested this and it appears that a version bump _doesn't_ require the user to re-consent.

**Comment by Gousia-MSFT** [comment]
@beauzeaux Apologies on the late response here. We could repro what you reported and we are working on updating the docs to reflect the proper conditions to trigger user consent flow.

**Comment by aosolis** [comment]
The list of what triggers consent is also incorrect. Incrementing the version number does not **by itself** make the update require user consent.

**Comment by aosolis** [comment]
Changing the permissions array does not trigger consent either.

**Comment by joeyglocke** [comment]
@laujan the full list of manifest changes that trigger user consent update is here: https://docs.microsoft.com/en-us/microsoftteams/manage-your-lob-apps#end-user-update-experience 

We should update any other docs that reference this. 

@aosolis can you make sure the list on that link looks accurate to you? Another set of eyes would help.

**Comment by aosolis** [comment]
@joeyglocke 
- the list is missing change to supportsCalling and supportsVideo
- for changes to webApplicationInfo, consent is only required in team scope

**Comment by joeyglocke** [comment]
@laujan I have screenshots of the update UI, ping me when you're working on this

**Comment by Rajeshwari-v** [comment]
@joeyglocke, Could you please provide the screenshots to update the document?
