### ISSUE TITLE
Chat - Quick replies do not trigger a read receipt

### ISSUE THREAD

**Issue by derekblankmccoy** [MicrosoftDocs/msteams-docs#1329]
When using a quick reply (the one built into the notification), a read receipt for the message is not triggered. I don't know if this is by design, but surely replying to a message means it was inherently read?

**Comment by Trinetra-MSFT** [comment]
Could you please share the screenshots? Where are you facing this issue is it teams mobile or desktop?

**Comment by derekblankmccoy** [comment]
Both mobile and desktop
![image](https://user-images.githubusercontent.com/11743619/73857168-6e08fe00-482e-11ea-9ba2-955c14a4ceeb.png)

**Comment by Trinetra-MSFT** [comment]
@derekblankmccoy, Can you please check and let us know Read Receipt option is enabled in your teams settings?

![image](https://user-images.githubusercontent.com/50989436/74514323-561e3200-4f32-11ea-83dc-a1d741be6c31.png)

**Comment by Trinetra-MSFT** [comment]
@derekblankmccoy , Feel free to reopen if you still facing this issue.
