### ISSUE TITLE
The page doesn't explain how to remove command menus

### ISSUE THREAD

**Issue by dalemyers** [MicrosoftDocs/msteams-docs#1330]
If you simply remove it from the manifest, then they are continued to be rendered in the app. How can they be removed? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a982542-ae03-2ada-cf71-4d586272e0c3
* Version Independent ID: 9e1fd82b-79e4-1b8d-5367-a8de3d04b3aa
* Content: [Create a command menu for your bot - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/create-a-bot-commands-menu?tabs=dotnet)
* Content Source: [msteams-platform/bots/how-to/create-a-bot-commands-menu.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/bots/how-to/create-a-bot-commands-menu.md)
* Product: **msteams**
* GitHub Login: @clearab
* Microsoft Alias: **anclear**

**Comment by sebastianvr** [comment]
Page does also not describe how to actually handle the commands in code. The paragraph only describes how to strip mentions.

**Comment by Trinetra-MSFT** [comment]
@laujan , Could you please help to update the document?

**Comment by clearab** [comment]
Hi - If you remove the command from your manifest you'll need to redeploy your app for the changes to take effect (any changes to the manifest require this).

As far as handling the commands in code, they are sent to your bot as a regular message so you'll need to handle them as you would any other message from your users. They are purely a UI treatment that inserts pre-configured text into the text box. The user must then send that text as they would any other message.

**Comment by dalemyers** [comment]
I have removed them from my app and redeployed. However, Teams still suggests them. After a few weeks it finally started suggesting the correct ones instead, but then reverted back (all without any re-deploys inbetween). Now, 10 months later, it is still showing the original.

**Comment by clearab** [comment]
Thanks for following up - the team has been able to recreate this behavior with bot menus, and is investigating. For updates about this, please follow the Issue here: https://github.com/microsoft/botframework-sdk/issues/6101
