### ISSUE TITLE
How can I get the Teams User Id in a personal tab?

### ISSUE THREAD

**Issue by kafka-yu** [MicrosoftDocs/msteams-docs#1331]
Hi team,

Is there any away I can get the Teams User Id? Currently I can only get the AadObjectId in the tab via the getContext() method.

Thanks!

**Comment by Trinetra-MSFT** [comment]
Could you please clarify what you are looking for?

**Comment by kafka-yu** [comment]
> Could you please clarify what you are looking for? What do you mean by Teams UserId?

Oh I mean the Id some thing like:
```
29:1o8GNKB9aqj8FTmHdSSE1gNqGd92xl0TrPuVyhpA6U-4crVYlhEgY0dCdHmvAQJ3rKQH0EBdb65javry4npUS0Q
```

It is from the request via a command or msg ext.
![image](https://user-images.githubusercontent.com/3942409/73912711-2f3b7c80-48f0-11ea-88ae-3456ce6446d2.png)


Is it possible that we can get it from the Tab via the JS sdk or sth?
Thanks!

**Comment by Trinetra-MSFT** [comment]
Are you talking about [Bot context](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bots-context#fetching-the-team-roster) or [Tab Context](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/access-teams-context#getting-context-by-using-the-microsoft-teams-javascript-library)? The Id you are referring is in Bot context, it will not be available in tab context.

**Comment by kafka-yu** [comment]
> Are you talking about [Bot context](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bots-context#fetching-the-team-roster) or [Tab Context](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/access-teams-context#getting-context-by-using-the-microsoft-teams-javascript-library)? The Id you are referring is in Bot context, it will not be available in tab context.

Yeah, BotContext indeed. So I can only use the SDK's tasks.submitTask() to send a request to Bot, then I can get the BotContext info there, right?

**Comment by Trinetra-MSFT** [comment]
Yes, You are on the correct way. Once you initiate microsoftTeams.submitTask(taskInfo,submitHandler). Your bot will receive task/submit but for that you need to pass bot id within taskinfo object.

**Comment by kafka-yu** [comment]
> Yes, You are on the correct way. Once you initiate microsoftTeams.submitTask(taskInfo,submitHandler). Your bot will receive task/submit but for that you need to pass bot id within taskinfo object.

Thank you @Trinetra-MSFT
