### ISSUE TITLE
I can see a team as a guest in web Teams, but desktop app doesn't show that team at all

### ISSUE THREAD

**Issue by GauntStrelok** [MicrosoftDocs/msteams-docs#1332]
I was invited to a team as a guest, as a result I can see that team in my teams, but only in the web, when Iam on the desktop app(or the mobile app) I can't see the team i was invited into.

Ask me if you need more information.

**Comment by Gousia-MSFT** [comment]
@GauntStrelok - Could you please confirm if  you have  switched to the tenant where you were added as a guest?

**Comment by GauntStrelok** [comment]
Yeah, I didn't, so i will close this.
Now I found the way to change the tenant and to change to the other teams tenant, but the strange thing was that i was able to join the other team in my own tenant on the web...
Doesn't matter.
