### ISSUE TITLE
Android Teams app overwriting Teams context.EntityId

### ISSUE THREAD

**Issue by NischaiV** [MicrosoftDocs/msteams-docs#1335]
Hi @Gousia-MSFT ,
I still have the issue with Android Teams app. I am setting the context variable from the tab configuration page as follows:
```
microsoftTeams.settings.setSettings({
                entityId: <some string value based on the data entered in tab configuration page>,
            });
```
When I access this data (as follows), It returns me the string (as expected) when trying to access from the Desktop client, web browser or ios Teams app. 
```
 microsoftTeams.getContext(function (context) {
  <some var> = context.entityId
}
```
But it returns a GUID value when accessing using android Teams app. This fails to load my custom tab. It looks like the Teams context.EntityId is being overwritten in Android Teams app.
I also noticed that, from mobile devices Teams app, I not only see the data added in the configuration page of the custom tab (when open the tab > settings), but also update the configuration. When I try to update the tab configuration, it fails with the error "Configuration is not set". I think this is also a bug in the mobile apps.

_Originally posted by @NischaiV in https://github.com/MicrosoftDocs/msteams-docs/issues/1251#issuecomment-580208847_

**Comment by Gousia-MSFT** [comment]
@NischaiV Thanks for reporting this with detailed steps. We could repro this now and we have raised a bug for this. This is being tracked internally.

**Comment by NischaiV** [comment]
@Gousia-MSFT May I know when can I expect a fix for this bug?
I see that you have closed the issue, so was it resolved already?

**Comment by koen-vissers** [comment]
@Gousia-MSFT is someone returning here as soon as this is fixed? Or can we view the status elsewhere?

**Comment by Gousia-MSFT** [comment]
@NischaiV @koen-vissers We have raised a bug on this and it is being tracked internally. We are working on fixing this but we do not have a firm timeline to share with you.

**Comment by Wajeed-msft** [comment]
This issue is fixed and it's being rolled out.
