### ISSUE TITLE
Contact card not wide enough and truncates information

### ISSUE THREAD

**Issue by GabrielSandor** [MicrosoftDocs/msteams-docs#1336]
Contact cards that pop up when you hover the mouse pointer over a username's photo are not wide enough and cannot accommodate longer text such as the location of the person.

**Comment by Gousia-MSFT** [comment]
@GabrielSandor Thanks for sharing your feedback. This has been implemented in internal builds and should be available in public builds soon. Unfortunately, we do not have a firm timeline about this.
