### ISSUE TITLE
Mobile app (iOS) not showing name of speed dial contact when being called

### ISSUE THREAD

**Issue by GabrielSandor** [MicrosoftDocs/msteams-docs#1337]
The mobile Teams app (at least on iOS) only shows the phone number of the speed dial contact that is calling you, while the desktop app is able to show the saved name.

**Comment by GabrielSandor** [comment]
I just noticed the names don't appear in the recent list either, again just for the mobile app.

**Comment by Trinetra-MSFT** [comment]
Could you please tell us which teams client version you are using?

**Comment by GabrielSandor** [comment]
@Trinetra-MSFT 
Version: 2.0.2
Build: 1.077.2020012502 (general)
Calling version: 2019.46.01.6

**Comment by Trinetra-MSFT** [comment]
@GabrielSandor , Thanks for your information we are looking into this.

**Comment by Trinetra-MSFT** [comment]
Could you please follow these steps and let us know the if you still face this issue:
1. Save a new speed dial contact PSTN number on desktop (mac)
2. Check that it appeared under the same name on Web (chrome)
3. Call the speed dial contact on mobile (iOS)
4. See the saved name on your mobile device in your call history

Let us know your repro steps we are unable to repro this. better to provide screen shots or video recording for further investigation.

**Comment by GabrielSandor** [comment]
I saved a new speed dial contact and i can see it on the web app too, but there are no speed dial entries showing in the mobile app, so i can't call. I'd have to call the number manually, which defeats the purpose of speed dialing.

**Comment by Trinetra-MSFT** [comment]
@GabrielSandor , Currently speed dial feature on mobile in not available for mobile. This is in our Road map but we don't have ETA to share with you.

**Comment by Trinetra-MSFT** [comment]
@GabrielSandor , We will update you once it will be rolled out. Please feel free to reopen this
