### ISSUE TITLE
Second text line in first conversation with someone is lost if typed to soon

### ISSUE THREAD

**Issue by GabrielSandor** [MicrosoftDocs/msteams-docs#1338]
When i start a conversation with someone for the first time, i usually say "hello" to them on the first line. Then, i press enter and quickly start typing the 2nd line. Something happens in the meantime, seems to be a refresh of sorts, and my 2nd line is lost mid-typing, so i have to re-type it.

**Comment by Gousia-MSFT** [comment]
@GabrielSandor We could not repro the issue on our side. Are you seeing this everytime you try to chat with someoone?

**Comment by GabrielSandor** [comment]
@Gousia-MSFT I noticed this happening only the very first time I talk to someone, when there is no prior conversation history.

**Comment by Gousia-MSFT** [comment]
@GabrielSandor We could not repro the issue on our side. Do you see this happening to only you or you have noticed this with others aswell?

**Comment by GabrielSandor** [comment]
@Gousia-MSFT i'll try to find an available colleague to run this experiment it.

In the meantime i'll give a more detailed description of what happens:

The first time i'm writing a message to someone i haven't talked to before on Teams, when i press enter, for a brief moment (about 1-2 seconds) Teams says "sending...". Right after the message is sent, the chat screen seems to do a full refresh. This refresh erases whatever i was typing in the chat text box while the first message was being sent. I hope this description is more useful to you.

**Comment by Gousia-MSFT** [comment]
@GabrielSandor Were you able to check this with someone from your team? We still can't repro it.

**Comment by GabrielSandor** [comment]
@Gousia-MSFT no, i didn't manage to check with a colleague yet. How would that be useful if you can't repro it anyway?

**Comment by Gousia-MSFT** [comment]
@GabrielSandor We could not repro the issue so i wanted to check if this is a tenant specific issue if someone from your tenant is also seeing this.

**Comment by Gousia-MSFT** [comment]
We could not repro the issue on our side. Please re-open with some additional information like the number of users who are seeing this and the desktop logs if you are still seeing the issue.
