### ISSUE TITLE
No documentation on cateogory mapping

### ISSUE THREAD

**Issue by EmilyyC** [MicrosoftDocs/msteams-docs#1341]
We get questions on from ISVs on 
-	 category mapping between Partner Center & Teams store 
-	Hero category displayed in the app listing
-	Error in categories displayed in the store
but theres no documentation for these

**Comment by Mahesh2516** [comment]
Closed the issue as the categories mentioned in the content are correct. Confirmation received on 03/22 from Rashmi Mendhegiri.
