### ISSUE TITLE
Cannot set system default audio devices

### ISSUE THREAD

**Issue by GabrielSandor** [MicrosoftDocs/msteams-docs#1342]
There is no setting in Devices that allows you to set the audio devices to the system settings in Windows -> Sound settings. This means you have to remember to manually change them, as they don't pick up automatically the system default when you plug different audio devices.

**Comment by Gousia-MSFT** [comment]
Is this related to Teams? Could you please be more specific?

**Comment by GabrielSandor** [comment]
Yes, i believe it is related to Teams. Below are 2 screenshots, one from Teams devices settings and one from Windows 10 sound settings:

![teams devices](https://user-images.githubusercontent.com/3800303/75762585-9a3b7000-5d43-11ea-8af2-aee8c120a696.png)

![windows sound settings](https://user-images.githubusercontent.com/3800303/75762600-9f98ba80-5d43-11ea-9dce-c7aaeef4eb3b.png)

It would be really great if, whenever i do a change to the Windows settings, Team picked up automatically these and applied them to its device settings. Maybe have a new value in the Audio devices dropdown named "System default", i've seen many applications do this.
