### ISSUE TITLE
Teams Mobile (Android) app error when accessing the microphone on custom app tab

### ISSUE THREAD

**Issue by rizwanja** [MicrosoftDocs/msteams-docs#1343]
Is there mobile support for permissions such as microphone access? I get a runtime permissions error on the Teams mobile app in my custom app tab. It works fine on the Teams desktop app though.

> Error occurred during microphone initialization: NotAllowedError: Permission denied.

I confirmed that both Teams and the browsers on my mobile device have the use of microphone enabled.

**Comment by Gousia-MSFT** [comment]
@rizwanja Could you please try using [Request device permissions](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/native-device-permissions) from tab?

**Comment by rizwanja** [comment]
@Gousia-MSFT Yep, tried that as well. I get the permissions prompt when using the Desktop client but nothing when using mobile.

**Comment by Gousia-MSFT** [comment]
@rizwanja This feature is currently not available on Mobile. We are wokring on this but we do not have a firm ETA to share with you.

**Comment by rizwanja** [comment]
@Gousia-MSFT Thank you for the update. Is there any workaround for the time being that we can explore? Something that will allow the user to use their mic for capturing speech to text using the Teams mobile app while on a custom tab (i.e. through relaying the message somehow using a bot + messaging extension)?

**Comment by Gousia-MSFT** [comment]
@rizwanja Currently, there is no workaround to this. Support for device permissions on mobile is coming soon but we do not have a ETA to share.
