### ISSUE TITLE
Teams in Ubuntu starts on boot without permission

### ISSUE THREAD

**Issue by datakid** [MicrosoftDocs/msteams-docs#1346]
Teams is set to start at boot without permission.

**Comment by Gousia-MSFT** [comment]
@datakid This is the default behaviour for Teams desktop client. You can go to Settings and turn it off.
![image](https://user-images.githubusercontent.com/45553518/74146274-c4a77b00-4c26-11ea-99a1-b48e8b8dc03b.png)

**Comment by datakid** [comment]
How do I get to the settings?  There are no obvious "settings" links in the usual places (bottom of menus, top right corner, bottom left corner, etc). In fact, I can't see *any* settings options. Using Version: 1.3.00.958 (stable branch) on Ubuntu 19.10

**Comment by datakid** [comment]
Fascinatingly at least one likely spot - the "? Help" button - has everything you'd expect, except settings, including things I didn't know I needed. 
![Screenshot from 2020-02-11 08-27-01](https://user-images.githubusercontent.com/97304/74191850-789d1a80-4ca8-11ea-9b3b-2a8c2cd84727.png)

**Comment by datakid** [comment]
Oh don't worry, I found it. I almost deleted my posts bc embarrassment, but then I thought it might be a good example for the UI/UX team to think on.
