### ISSUE TITLE
Adding GitHub Enterprise on MS Teams getting "Something went wrong"

### ISSUE THREAD

**Issue by ii-batman** [MicrosoftDocs/msteams-docs#1349]
Hi, I am trying to install [https://appsource.microsoft.com/en-gb/product/office/WA104381552?src=wnblogmar2018](url) and I get a "something went wrong" in MS Teams....
Any ideas what could be causing this?
I have full permissions in MS Teams policies.
Thanks, ii

**Comment by Gousia-MSFT** [comment]
@ii-batman Could you please try this in browser and see if you get any console errors?

**Comment by ii-batman** [comment]
> @ii-batman Could you please try this in browser and see if you get any console errors?

Hi @Gousia-MSFT  - what should I try?

**Comment by Gousia-MSFT** [comment]
@ii-batman Please login to Teams on browser(https://teams.microsoft.com) and try to install the app. Open browser console(by pressing F12 and see if you see any console errors there?

**Comment by ii-batman** [comment]
Errors:
DevTools failed to parse SourceMap: https://teams.microsoft.com/service-worker.js.map
DevTools failed to parse SourceMap: chrome-extension://hdokiejnpimakedhajhdlcegeplioahd/sourcemaps/onloadwff.js.map
jsll-4.js:1 Cross-Origin Read Blocking (CORB) blocked cross-origin response https://web.vortex.data.microsoft.com/collect/v1?$mscomCookies=false&ext-javascript-msfpc=%27GUID%3D54703b720e5b48c3980a2eb7580aa59f%26HASH%3D5470%26LV%3D201902%26V%3D4%26LU%3D1550590097368%27 with MIME type application/json. See https://www.chromestatus.com/feature/5629709824032768 for more details.
st @ jsll-4.js:1
awa.writeEvent @ jsll-4.js:1
f @ jsll-4.js:1
o @ jsll-4.js:1
(anonymous) @ t.js?ver='2.1'&name='Ms.Webi.PageView'&time='2020-02-21T15%3A37%3A25.751Z'&os='Windows'&appId='JS%3Ateams.microsoft.com'&-ver='1.0'&-impressionGuid='1d5d8d6b-447d-4a9a-aaa7-e3672d076d90'&-pageName='launcher.html'&-uri='https%3A%2F%2Fteams.microsoft.com%2Fdl%2Flauncher%2Flauncher.html%3Furl%3D%2f_%23%2fl%2fapp%2fca319335-400e-43c1-bca4-b6c745ce3093%3fsource%3dapp-source%26type%3Dapp%26deeplinkId%3D783218da-6b89-4916-aa36-fa1952686807%26directDl%3Dtrue%26msLaunch%3Dtrue%26enableMobilePage%3Dtrue%26suppressPrompt%3Dtrue'&-referrerUri='https%3A%2F%2Flogin.microsoftonline.com%2F'&-market='en-US'&-resHeight=720&-resWidth=1280&-pageTags='{"metaTags"%3A{}}'&-behavior=0&*baseType='Ms.Content.PageView'&*cookieEnabled=true&*cookies='_mkto_trk%3Did%3A157-GQE-382%26token%3A_mch-microsoft.com-1563893223951-14651%3B'&*isJs=true&*title='Join conversation'&*isLoggedIn=false&*flashInstalled=false&ext-javascript-ver='1.1'&ext-javascript-libVer='4.2.14'&ext-javascript-domain='teams.microsoft.com'&ext-javascript-msfpc='GUID%3D54703b720e5b48c3980a2eb7580aa59f%26HASH%3D5470%26LV%3D201902%26V%3D4%26LU%3D1550590097368'&ext-javascript-userConsent=true&ext-user-localId='t%3A14140A1968486040336607186C486309'&$mscomCookies=false:1 @Gousia-MSFT

**Comment by Gousia-MSFT** [comment]
@ii-batman Could you please share a more detailed steps for repro maybe a video recording of the issue?

**Comment by Gousia-MSFT** [comment]
Please re-open with requested information.
