### ISSUE TITLE
Example is missing in Integration section

### ISSUE THREAD

**Issue by vamboda** [MicrosoftDocs/msteams-docs#1353]
Example is missing in section located at https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/design/tabs#integration

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3dd35a9c-c868-a7b9-825a-4be9419539d7
* Version Independent ID: 814c8be1-eae8-7316-8553-283ef07ffc09
* Content: [Design guidelines for tabs - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/design/tabs#integration)
* Content Source: [msteams-platform/tabs/design/tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tabs/design/tabs.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **anclear**

**Comment by Trinetra-MSFT** [comment]
@laujan , Could you please help to update the doc for this?
