### ISSUE TITLE
Teams Bot 1-1 ConversationUpdate Events

### ISSUE THREAD

**Issue by HiltonGiesenow** [MicrosoftDocs/msteams-docs#1355]
I'm struggling with the same situation in a few different Teams bots I've written, and trying to determine if I've just misunderstood the docs. When the bot is side-loaded to a test tenant, and then added to a 1-1 conversation, I'm getting two conversationUpdate/MemberAdded events. However, BOTH events contain BOTH users (i.e. end user and bot). I would have expected either one event, with both Members, or two events, one with each user, but not the SAME event 100% duplicated. Is this the correct expected behaviour? If so, how do I deal with this scenario, as there's no way to differentiate the two duplicated events. I've posted more on SO, but with no responses: https://stackoverflow.com/questions/60140079/microsoft-teams-side-loaded-app-multiple-conversationupdate-events-firing

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a6d00a4-dd28-33c4-002e-2e8e7c653ce2
* Version Independent ID: 0856927a-25f4-b1e0-5f1b-d55dc61796f3
* Content: [Subscribe to conversation events - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/subscribe-to-conversation-events?tabs=dotnet#team-members-added)
* Content Source: [msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md)
* Product: **msteams**
* GitHub Login: @WashingtonKayaker
* Microsoft Alias: **anclear**

**Comment by Subhasish-msft** [comment]
This is a duplicate question of 
https://stackoverflow.com/questions/60140079/microsoft-teams-side-loaded-app-multiple-conversationupdate-events-firing

**Comment by HiltonGiesenow** [comment]
Yes, I guess it can be closed. Is there any feedback on the bug though by any chance?

**Comment by pedroacuma** [comment]
I have been getting this error too, what is the state of this issue?

**Comment by Subhasish-msft** [comment]
@HiltonGiesenow, @pedroacuma  Thanks for following up. The bug is being assigned to engineering team. Will keep you updated once a fix is rolled out.

**Comment by HiltonGiesenow** [comment]
great stuff, thanks!
