### ISSUE TITLE
Can you please provide recent example using a front-end framework?

### ISSUE THREAD

**Issue by icatchx22i** [MicrosoftDocs/msteams-docs#1360]
It appears that only, 'OfficeDev/microsoft-teams-sample-todo' uses a front-end authentication workflow using React. Thing is, it appears that it uses very old methodology and is generally very old (typescript 2.0.3). Is there a more recent clear example on how to authenticate via SPA/front end only?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b1dcd0d-471b-2d33-54b5-39a93dfba2a8
* Version Independent ID: 5bd44149-777e-b449-bd2e-f20b9bd04038
* Content: [Authentication for tabs using Azure Active Directory - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-tab-aad#samples)
* Content Source: [msteams-platform/tabs/how-to/authentication/auth-tab-aad.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tabs/how-to/authentication/auth-tab-aad.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **anclear**

**Comment by Trinetra-MSFT** [comment]
@icatchx22i , Yes Please take a look at [Bot Builder SDK 4 samples](https://github.com/microsoft/BotBuilder-Samples/tree/master/samples) code.

**Comment by icatchx22i** [comment]
Hi @Trinetra-MSFT thank you for your reply and link. I realize from my initial question that i was not clear that im looking at the Authentication of an MSTeams Tab. I went through a few iterations with existing guides but hit all dead ends. Most of the examples i found work within a browser but not MSTeams due to the iframe limitations and all the Microsoft examples i found involve server-side templating as opposed to front-end only workflow. again, thanks!

**Comment by Trinetra-MSFT** [comment]
@icatchx22i , Thanks . Please feel free to reopen if you still have any query.

**Comment by icatchx22i** [comment]
@Trinetra-MSFT Can you please link me to a Front-end workflow TAB authentication? The link only contains bot authentication?
