### ISSUE TITLE
Automatic webhook generation for connector

### ISSUE THREAD

**Issue by abarringtonACR** [MicrosoftDocs/msteams-docs#1361]
Hi, I'm attempting to automate creation of teams and channels so that they will have a Jenkins webhook for each channel. Is there a way to configure a connector through the Teams api? I am looking to avoid doing this manually for many different channels.

**Comment by Gousia-MSFT** [comment]
@abarringtonACR Currently there is no way to configure a connector through API. We do not have any plans for this as of now. However you could [install the app using Graph API.](https://docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-beta&tabs=http)

**Comment by abarringtonACR** [comment]
Hi @Gousia-MSFT, is there a way to automatically generate webhooks for a connector? That's the only part I am trying to configure.

**Comment by Gousia-MSFT** [comment]
@abarringtonACR No there isn't any way to automatically generate webhooks for a connector.
