### ISSUE TITLE
Can you confirm the sample code on this page is correct?

### ISSUE THREAD

**Issue by tfischer** [MicrosoftDocs/msteams-docs#1362]
Hi,

I am seeing different exceptions being thrown than the ones indicated on this page.  Is it possible to confirm the instructions on this page are correct and up to date with the latest botbuilder 4?

thanks,
Tom

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a57254c9-963d-ea1d-ecaf-dd0e7913526c
* Version Independent ID: 610c8514-bd72-46cc-75f1-991e2242019b
* Content: [Rate limiting - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/rate-limit)
* Content Source: [msteams-platform/bots/how-to/rate-limit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/bots/how-to/rate-limit.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **anclear**

**Comment by laujan** [comment]
I am checking with the engineering team. I will let you know what they say.

**Comment by laujan** [comment]
Hello @tfischer. The article has been updated. Thank you!
