### ISSUE TITLE
The botbuilder-teams npm package has been deprecated

### ISSUE THREAD

**Issue by wusatosi** [MicrosoftDocs/msteams-docs#1364]
Hi! Maintainers.
Under the [Create A bot for Microsoft Teams Section](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bots-create#create-a-bot-for-microsoft-teams), the recommended npm package "botbuilder-teams", is marked as deprecated on its npm page.
Maybe give a head-up and remove the recommandation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c51ba06e-c3cd-1e39-d158-1ec668710383
* Version Independent ID: 74412de0-c5b9-632e-77be-72e044b95e9c
* Content: [Create a bot - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bots-create#create-a-bot-for-microsoft-teams)
* Content Source: [msteams-platform/resources/bot-v3/bots-create.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/resources/bot-v3/bots-create.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **anclear**

**Comment by wusatosi** [comment]
Wow this issue system is brilliant!

**Comment by wusatosi** [comment]
For more context, this is the [link](https://www.npmjs.com/package/botbuilder-teams) to corresponding npm page
![deprecated](https://user-images.githubusercontent.com/26424577/74621909-bf43b680-5179-11ea-8af8-fb3a7a773acf.png)

**Comment by laujan** [comment]
Thank you! The article has been updated.
