### ISSUE TITLE
Attach a file using webhook 

### ISSUE THREAD

**Issue by mohamedalaa33** [MicrosoftDocs/msteams-docs#1365]
Hi I am trying to develop a poweshell script to attach output file while sending a webhook to a channel so is it supported or not supported till now ?

**Comment by Gousia-MSFT** [comment]
@mohamedalaa33 Sending files using webhook is currently not supported.

**Comment by mohamedalaa33** [comment]
@Gousia-MSFT  is there any workaround ?

**Comment by Gousia-MSFT** [comment]
@mohamedalaa33 As of now you could only provide hyperlink of the file in the message. Other than that there is no way to send files using webhooks.

**Comment by mohamedalaa33** [comment]
@Gousia-MSFT is creating a bot to send and receive files can solve issue ?

**Comment by Gousia-MSFT** [comment]
@mohamedalaa33 Yes, you can use Bots to send and receive files.

**Comment by mohamedalaa33** [comment]
@Gousia-MSFT  Thank you
