### ISSUE TITLE
[MsTeams][ManifestFile][Botframework] Attachment icon is missing in mobile teams

### ISSUE THREAD

**Issue by Chekrii** [MicrosoftDocs/msteams-docs#1366]
Hi Team,

* I have created manifest file for my Bot and uploaded in teams as app.
* I have set  "supportsFiles": true.
* I am able to see Attachment options in Desktop Teams app but it is missing in mobile Teams.
* Please find the attachment 

<img width="494" alt="AttachmentIcon" src="https://user-images.githubusercontent.com/49824279/74638250-94655c80-5191-11ea-9a06-3dd3676fb445.PNG">
 

Any Solution?
Please help.

**Comment by Gousia-MSFT** [comment]
@Chekrii Sending and receiving files through Bot is not currently supported on Mobile as documented [here](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/send-and-receive-files?tabs=dotnet). We are working on this but we do not have an ETA to share.
