### ISSUE TITLE
Detect close event when a task module is invoked from a bot

### ISSUE THREAD

**Issue by PramodDeokar-ms** [MicrosoftDocs/msteams-docs#1368]
As per doc,  It is currently not possible to detect close event when a task module is invoked from a bot.
Do we have any advancement in framework to detect the close event?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 501d3295-997c-d252-d458-534673b36a52
* Version Independent ID: c90dcc98-df65-b45b-4f78-64d2cab91852
* Content: [What are task modules? - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/what-are-task-modules#feedback)
* Content Source: [msteams-platform/task-modules-and-cards/what-are-task-modules.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/what-are-task-modules.md)
* Product: **msteams**
* GitHub Login: @clearab
* Microsoft Alias: **anclear**

**Comment by Subhasish-msft** [comment]
HI @PramodDeokar-ms ,

Currently, there is no provision to capture close event of a task module invoked form bot. Whereas you can capture the close event if you invoke task module from a Tab. 

Can you please share in what scenario you need to capture the close event ?

**Comment by PramodDeokar-ms** [comment]
Thanks @Subhasish-msft
