### ISSUE TITLE
Teams mobile app (Android, iOS) can't open tel, mail links in personal app

### ISSUE THREAD

**Issue by apollon7** [MicrosoftDocs/msteams-docs#1369]
When clicking on a tel: or mailto: link in Teams mobile app (preview mode) - personal app I get forwarded to an error screen. The links are opened correctly when target="_blank" is used.

The same links are working (without target="_blank") if the SPFx solution is opened in the SharePoint mobile app, Edge mobile or on PC (Teams client/browser).

**Comment by Trinetra-MSFT** [comment]
Could you please help us to know what error you are getting , a screen shot of error will be helpful to understand the issue?

**Comment by apollon7** [comment]
@Trinetra-MSFT sure, this is the error screen I've mentioned:
![scr](https://user-images.githubusercontent.com/30493494/74728753-9a1b7a80-5243-11ea-91e7-a1b0dd3b654b.jpg)

**Comment by Trinetra-MSFT** [comment]
Could you please try this with target = "_blank"? If this works for you. it would be good

**Comment by apollon7** [comment]
Yes, as described above the tel and mailto links open correctly if target = "_blank" is used (neccessary in Teams on the web and Teams mobile app).
However it's not neccessary to use target = "_blank" in SharePoint Online, SharePoint mobile app or Teams Client (Windows).
Because I want to avoid that the user is left with an empty tab open after clicking on a phone number my application currently sets the target attribute depending on the client used. It would be great if links open the same everywhere.

**Comment by apollon7** [comment]
Now on iOS devices the links won't even work when target = "_blank" is used. The links I've tested include tel, mailto and Teams deep links.

![image](https://user-images.githubusercontent.com/30493494/75899890-685a0480-5e3c-11ea-8b8f-9d088b60469c.png)

**Comment by Trinetra-MSFT** [comment]
@apollon7. Could you please share the deep link syntax what you are trying?

**Comment by apollon7** [comment]
@Trinetra-MSFT https://teams.microsoft.com/l/chat/0/0?users=user@domain.com

**Comment by Trinetra-MSFT** [comment]
@apollon7 , We tested this for teams mobile Android platform, it works at our end. Meanwhile could you please check tel protocol is enabled in your maching

**Comment by Trinetra-MSFT** [comment]
Please feel free to reopen the issue if you have further query
