### ISSUE TITLE
Personal Notification

### ISSUE THREAD

**Issue by dastewa** [MicrosoftDocs/msteams-docs#1376]
Hi team, is there any recommended method for sending a Teams notification to a specific user without the use of a bot? Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ad9f167-7d29-f933-7b47-60bd744899b1
* Version Independent ID: 8097fcbd-adcc-ce49-a378-426c65af9296
* Content: [Send proactive messages - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/send-proactive-messages?tabs=dotnet)
* Content Source: [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/bots/how-to/conversations/send-proactive-messages.md)
* Product: **msteams**
* GitHub Login: @clearab
* Microsoft Alias: **anclear**

**Comment by Subhasish-msft** [comment]
You can send notification to an user only using proactive message from a bot. There is another way to send messages to a channel using [webhooks and connectors](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/what-are-webhooks-and-connectors)

**Comment by dastewa** [comment]
Ah, ok thank you @Subhasish-msft - I'll close :).

**Comment by clearab** [comment]
@dastewa: You can also use Power Automate (formerly Flow) to send messages to a user.

**Comment by dastewa** [comment]
Thank you for that suggestion @clearab! That's awesome, I'll be diving into that some more - cheers!
