### ISSUE TITLE
Reply to a chat works on mobile but not on desktop

### ISSUE THREAD

**Issue by TinavdV** [MicrosoftDocs/msteams-docs#1378]
It is possible to select reply in the team iOS and android applications, but there is no option to reply to a chat on the desktop version:  
![image](https://user-images.githubusercontent.com/61229190/74821814-7704cf80-5304-11ea-852d-2a1d6091ddba.png)

On iOS:
![image](https://user-images.githubusercontent.com/61229190/74822594-a700a280-5305-11ea-843b-38f9ef941ebe.png)

On the desktop version:
![image](https://user-images.githubusercontent.com/61229190/74822393-59843580-5305-11ea-8de2-e628d06f1512.png)

**Comment by Gousia-MSFT** [comment]
@TinavdV Thanks for reaching out to us. We do have a feature request on this, which we are working on but we do not have an ETA on when this will be released.

**Comment by TinavdV** [comment]
Thanks for the quick reply Gousia! I tried to find a request but didn`t know where to look. 

Is there any other place I can go to vote this up so that it can get to the front of the queue?  I find this the most annoying lacking feature in the desktop application, especially in large groups where there is no way to indicate to which person or message you are responding to.

**Comment by Gousia-MSFT** [comment]
@TinavdV This request is being tracked internally. However, you can vote for a [uservoice](https://microsoftteams.uservoice.com/forums/555103-public/suggestions/31425436-ability-to-reply-to-a-specific-message-in-a-chat-t) here.

**Comment by TinavdV** [comment]
Ok, I voted! 

Do you mean tracked internally by the Teams team, or internally within Microsoft?

**Comment by TinavdV** [comment]
Because if I can get access to track the request as a PFE, that would be great.

**Comment by Gousia-MSFT** [comment]
@TinavdV  These requests are being tracked internally by the Teams team and are being worked on. It is not possible to provide access to the users to track the request.
