### ISSUE TITLE
Files with "#" character cannot be moved in Teams

### ISSUE THREAD

**Issue by mjzwick** [MicrosoftDocs/msteams-docs#1387]
I am using the MacOS Teams application 1.3.00.362.

I have seen this multiple times today so easy to replicate. In the Files tab, upload a file that contains the pound sign character in the file name ('#'). Uploads into Teams fine. Create a Folder. Try to move the file into the folder by selecting the file, selecting Move, and picking the folder. Teams returns an error "cannot move file" without explanation. Rename the file, removing the "#" character. Now you can more the file without an error. The file can then be renamed back to the original filename with the "#" sign.

**Comment by Subhasish-msft** [comment]
@mjzwick,Thanks for reporting the issue. We have identified and logged this bug, however this is not yet prioritized and we don't have an ETA yet.
