### ISSUE TITLE
Can't determine user timezone in tab from Teams context

### ISSUE THREAD

**Issue by rizwanja** [MicrosoftDocs/msteams-docs#1390]
When accessing a Teams tab there doesn't appear to be a way that the user's time zone can be determined from the context properties. The closest property appears to be locale but that won't really work. Is there a way we can determine this?

**Comment by Gousia-MSFT** [comment]
@rizwanja You could try getting the timezone of the user using the Date functions. Please try this code below:
```
<div class="date">
    <p>date and time:</p>
    <div id="demo"></div>
    <script>
        var d = new Date();
        document.getElementById("demo").innerHTML = d;
</script>
</div>
```

**Comment by Gousia-MSFT** [comment]
Please re-open if you face any issues.
