### ISSUE TITLE
Cannot add "incoming webhook" connector - no results from search

### ISSUE THREAD

**Issue by daybarr** [MicrosoftDocs/msteams-docs#1392]
The [Add an incoming webhook to a Teams channel](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-incoming-webhook#add-an-incoming-webhook-to-a-teams-channel) section says:

> 2. Choose Connectors from the drop-down menu and search for Incoming Webhook.

But when I do that, I get...

> No results for 'Incoming Webhook'

...so I cannot continue with step 3.

![screenshot](https://user-images.githubusercontent.com/140142/75200238-1ab70b00-575d-11ea-8e35-3a7a0f5518e3.png)

It seems that there is no such connector type any more? Or maybe I don't have permission to add such a Connector, in which case it would be helpful if the documentation or the product could tell me that and point me in the right direction to get that permission issue resolved?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90ff2a84-a8bc-9259-d37d-622b102df75b
* Version Independent ID: e3b53e27-2946-189c-623b-9df704ea8f12
* Content: [Post external requests to Microsoft Teams with incoming webhooks - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-incoming-webhook)
* Content Source: [msteams-platform/webhooks-and-connectors/how-to/add-incoming-webhook.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/webhooks-and-connectors/how-to/add-incoming-webhook.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **laujan**

**Comment by Gousia-MSFT** [comment]
@daybarr Could you please check if your tenant administrator turned off access to external applications?

**Comment by Gousia-MSFT** [comment]
Please re-open if you are still facing the issue.

**Comment by joshtransient** [comment]
I also receive this on a brand new dev tenant with no restrictions on the app permission policy.
