### ISSUE TITLE
Is there a way to get the current tab instance only, instead of a list of all tabInstances owned by the app?

### ISSUE THREAD

**Issue by NischaiV** [MicrosoftDocs/msteams-docs#1393]
Is there a way to retrieve only the current tabInstance object? The getTabInstances() returns all the tabInstances owned by the app. I want to get the TabName of the current tab where my code is executing. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2f7c821-fefa-af6b-0a48-605554c0e8ff
* Version Independent ID: 100b63a0-502d-e7d3-352a-b039aa50f7db
* Content: [TabInstance interface - Teams](https://docs.microsoft.com/en-us/javascript/api/@microsoft/teams-js/microsoftteams.tabinstance?view=msteams-client-js-latest)
* Content Source: [nodejs/docs-ref-autogen/@microsoft/teams-js/microsoftTeams.TabInstance.yml](https://github.com/OfficeDev/msteams-client-docs-ref-typescript/blob/live/nodejs/docs-ref-autogen/@microsoft/teams-js/microsoftTeams.TabInstance.yml)
* Product: **msteams**
* GitHub Login: @charlesprakash
* Microsoft Alias: **o365devx**

**Comment by Trinetra-MSFT** [comment]
@NischaiV , Currently This is not possible to get only current instance of a tab, get tab instance will return all the tab instance. However you can fetch the current tab by using the Graph API. Please take a look at [Get Tab using Graph API](https://docs.microsoft.com/en-us/graph/api/teamstab-get?view=graph-rest-1.0#http-request)

**Comment by Gousia-MSFT** [comment]
Please re-open if you have any further queries.
