### ISSUE TITLE
Inconsistent behaviour for scrollable list card in desktop client and mobile app 

### ISSUE THREAD

**Issue by wasim8906** [MicrosoftDocs/msteams-docs#1399]
The scrollable list card is working fine in desktop client app with scroller but fails to load the scroller in android and iOS app, it just shows as a long list of items.

 Desktop App:
<img width="751" alt="Screenshot 2020-02-26 at 1 44 41 PM" src="https://user-images.githubusercontent.com/61415896/75325100-3a098180-589e-11ea-9c5d-df83860e051b.png">

Android App:

![Screenshot_20200226-134549_Teams (1)](https://user-images.githubusercontent.com/61415896/75325219-73da8800-589e-11ea-8fee-0bc2205d4209.jpg)

**Comment by Gousia-MSFT** [comment]
@wasim8906 Thanks for reaching out to us. We could repro this behaviour. We are checking this internally.

**Comment by Gousia-MSFT** [comment]
We have raised a bug for this and we are tracking it internally.

**Comment by Gousia-MSFT** [comment]
@wasim8906 This is currently by design. We don't have any plans to change this in the near future.
