### ISSUE TITLE
Process the return value fails due to cross origin frame access

### ISSUE THREAD

**Issue by gabbsmo** [MicrosoftDocs/msteams-docs#1401]
This code snippet from the docs will fail if there is no existing session to reuse, i.e. when testing in incognito mode and going directly to the Teams tab without signing in to the tab's app first.

```
if (authContext.isCallback(window.location.hash)) {
    authContext.handleWindowCallback(window.location.hash);
    if (window.parent === window) {
        if (authContext.getCachedUser()) {
            microsoftTeams.authentication.notifySuccess();
        } else {
            microsoftTeams.authentication.notifyFailure(authContext.getLoginError());
        }
    }
}
```

`handleWindowCallback` fails on line 1321 in adal.js 1.0.17 which looks like this: `else if (window.parent && window.parent._adalInstance) {`. `window.parent` in this case has the origin teams.microsoft.com while the tab has a different origin. Because of this the hash from Azure AD login redirect  cannot be processed and no token is stored in localStorage.

This does not happen when I am already logged in to the app since there is no need to visit the redirectUri. I guess this error will surface when it is time to renew the token.

---
#### Dokumentinformation

⚠ *Redigera inte det här avsnittet. Det krävs för docs.microsoft.com ➟ länkning till GitHub-problem.*

* ID: f2e66ffa-ec00-4a84-a43d-d47e3c138b32
* Version Independent ID: 47e9a383-ac6a-dc7d-2d91-a9e09626fdab
* Content: [Silent authentication - Teams](https://docs.microsoft.com/sv-se/microsoftteams/platform/tabs/how-to/authentication/auth-silent-aad)
* Content Source: [msteams-platform/tabs/how-to/authentication/auth-silent-aad.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tabs/how-to/authentication/auth-silent-aad.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Wajeed-msft** [comment]
Could you please try [AuthBot.zip](https://github.com/OfficeDev/microsoft-teams-sample-auth-node/blob/master/manifest/AuthBot.zip) manifest and see if you could repro this? Please share the repro steps.

**Comment by gabbsmo** [comment]
A packaged repro is going to take time but I think I fixed this, for browsers at least. I am not able to get silent authentication to work in the Windows app.

I have an existing SPA using adal-angular that I want to wrap in a team tab. When following the docs I would get an error. What I did to get it working was to skip implementing redirectUri page for teams and reuse the one that I already had.

Then I used authContext.aquireToken in my tab's content page as per the docs and redirect to my SPA in the callback. Then my SPA would automatically reuse the session created by the content page.

Is silent authentication possible in the Windows app? The error I get from ADAL in that context is "AADSTS50058: A silent sign-in request was sent but no user is signed in.". This is when attempting to get a token in tab content page. Redirect to SPA has not happened yet.

**Comment by Wajeed-msft** [comment]
@gabbsmo - For Silent Auth to work, user needs to sign in at-least once if there is no existing session available. If you are looking for SSO then please take a look at [Single Sign-On](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-aad-sso) documentation.

**Comment by Wajeed-msft** [comment]
Please re-open if you are facing any issues.

**Comment by gabbsmo** [comment]
@Wajeed-msft Thank you for your reply. I got silent auth working by implementing a separate login page.

/Teams/Login
```
microsoftTeams.initialize();

var adalConfig = {
    clientId: 'foobar',
    redirectUri: window.location.href,
    navigateToLoginRequestUrl: false,
    endpoints: {},
    cacheLocation: 'localStorage'
};

var authContext = new AuthenticationContext(adalConfig);

microsoftTeams.getContext(function (teamsContext) {
    authContext.config.extraQueryParameter = 'domain_hint=organizations&login_hint=' + encodeURIComponent(teamsContext.loginHint);

    if (authContext.isCallback(window.location.hash)) {
        authContext.handleWindowCallback();

        var user = authContext.getCachedUser();

        if (!user) {
            microsoftTeams.authentication.notifyFailure();
            return;
        }

        microsoftTeams.authentication.notifySuccess();
        return;
    }

    authContext.login();
});
```
The content page can then point to that page when manual login is required.

/Teams
```
microsoftTeams.initialize();
var loginButton = document.querySelector('#login');

var adalConfig = {
    clientId: '@WebConfigurationManager.AppSettings[DMAppSettings.ClientId]',
    redirectUri: window.location.origin + '/FrameRedirect',
    navigateToLoginRequestUrl: false,
    endpoints: {},
    cacheLocation: 'localStorage'
};

var authContext = new AuthenticationContext(adalConfig);

microsoftTeams.getContext(function (teamsContext) {
    authContext.config.extraQueryParameter = 'domain_hint=organizations&login_hint=' + encodeURIComponent(teamsContext.loginHint)

    authContext.acquireToken(adalConfig.clientId, function acquireTokenCallback (errDesc, token, err, tokenType) {
        if (err) {
            console.log(arguments);
            loginButton.style.visibility = 'visible';
            return;
        }

        // TODO: Redirect to adal.js SPA for which there should now be an existing session to reuse
    });

    loginButton.addEventListener('click', onLoginClicked);
});

function onLoginClicked () {
    microsoftTeams.authentication.authenticate({
        url: window.location.origin + '/Teams/Login',
        width: 600,
        height: 535,
        successCallback: function onTeamsAuthenticationSuccess(result) {
            console.log(result);
            redirect();
        },
        failureCallback: function onTeamsAuthenticationFailure(reason) {
            console.log(reason);
        }
    });
}
```
