### ISSUE TITLE
Use taskInfo with fetchTask to "true" and without any parameters

### ISSUE THREAD

**Issue by simiczhang** [MicrosoftDocs/msteams-docs#1404]
Document said: "If you are using a taskInfo object, be sure to also set the fetchTask parameter to false."

But for my case, my message extension command didn't contain any parameter, it only needs to load a embedded web view from url, if I set fetchTask as false, if user open this message extension, the page associated with the url would not be loaded , after I set the fetchTask to true, everything works fine. But this is against the document, so any other potential concern to use taskInfo with fetchTask: "true "? below is my manifest :

"composeExtensions": [
        {
            "botId": "xxxxxxxxxxxxx",
            "canUpdateConfiguration": true,
            "commands": [
                {
                    "id": "call",
                    "type": "action",
                    "title": " ",
                    "description": "",
                    "initialRun": false,
                    "fetchTask": true,
                    "taskInfo": {
                        "title": "Simic Test Title",
                        "url": "https://xxxxx/compose-extension",
                        "height": "medium",
                        "width": "medium"
                    },
                    "context": [
                        "compose"
                    ]
                }
            ]
        }
    ],
 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: efcdf768-1513-2249-b344-bf38ef64c70d
* Version Independent ID: 415b5d57-2d41-9540-55a7-2a33a4315e37
* Content: [Define messaging extension action commands - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/action-commands/define-action-command#feedback)
* Content Source: [msteams-platform/messaging-extensions/how-to/action-commands/define-action-command.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/messaging-extensions/how-to/action-commands/define-action-command.md)
* Product: **msteams**
* GitHub Login: @clearab
* Microsoft Alias: **anclear**

**Comment by simiczhang** [comment]
Updates, it seems after set fetchTask to true, it would still find bot endpoint to ask for taskInfo definition .

Just wonder if it is possible to let compose extension to load from static url so it won't ask bot endpoint every time ?

**Comment by tca-ms** [comment]
I've also encountered this issue. The document says

> If you are using an embedded web view, you can optionally add the taskInfo object to fetch your web view without calling your bot directly. If you choose to use this option, the behavior is similar to using a static list of parameters in that the first interaction with your bot will be responding to the task module submit action. If you are using a taskInfo object, be sure to also set the fetchTask parameter to false.

This implies that if `fetchTask` is set to `false` and a `taskInfo` object is provided, the url specified in the `taskInfo` will be loaded without having to call the bot. The behavior I've observed is that the form for the static parameter list is displayed instead. I've tried supplying an empty list for the `parameters` field, or removing it entirely, but then the manifest fails validation. Here's the relevant section of my manifest:
```
    "composeExtensions": [
        {
            "botId": "xxxxxxxxxxxxxxx",
            "canUpdateConfiguration": false,
            "commands": [
                {
                    "id": "TestCommand",
                    "type": "action",
                    "title": "Test",
                    "description": "A test command",
                    "initialRun": false,
                    "fetchTask": false,
                    "context": [
                        "commandBox",
                        "compose"
                    ],
                    "parameters": [
                        {
                            "name": "param",
                            "title": "param",
                            "description": ""
                        }
                    ],
                    "taskInfo": {
                        "title": "Test",
                        "width": "large",
                        "height": "large",
                        "url": "https://xxxxxxxxx/hello"
                    }
                }
            ]
        }
    ],
```
