### ISSUE TITLE
Error in package.lock.json

### ISSUE THREAD

**Issue by ramagirish123** [MicrosoftDocs/msteams-docs#1405]
Version of clean-css package in the dependencies pug filter was wrong. It was mentioned &gt;=4.4.11 but there was no such version.
It is working when it gets changed to 4.1.11

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4fa27cb-544f-f8a2-97a7-4b31528c1b80
* Version Independent ID: fa69cd6f-1ef4-706d-2816-aa709714b0aa
* Content: [Get started with App Studio and Node.js - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tutorials/get-started-nodejs-app-studio#feedback)
* Content Source: [msteams-platform/tutorials/get-started-nodejs-app-studio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tutorials/get-started-nodejs-app-studio.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by leeford** [comment]
Running 'npm update' before 'npm install' clears this up....

![image](https://user-images.githubusercontent.com/472320/75538090-fafb3d80-5a0f-11ea-9324-98fda8672a2c.png)

**Comment by laujan** [comment]
Corrected Line 4627 in https://github.com/OfficeDev/msteams-samples-hello-world-nodejs/blob/master/package-lock.json.

**Comment by laujan** [comment]
Thank you!
