### ISSUE TITLE
Not getting 'Member added activity'

### ISSUE THREAD

**Issue by chaitnya12** [MicrosoftDocs/msteams-docs#1406]
I am adding bot to team using ' Add app to team' api. However, I am not getting 'memberAdded' activity. I am getting 'memberAdded' activity when I add app manually.

**Comment by Gousia-MSFT** [comment]
@chaitnya12 Currently, the bot gets the conversationUpdate event only on the first installation of the app. Your bot will not get a memberaddded event during the 2nd installation. We have a bug on this but we do not have an ETA about the fix.

**Comment by chaitnya12** [comment]
@Gousia-MSFT I am facing this issue for the bots that I have created recently( a week ago). For the old bot(created in Jan) everything works fine. Is this behaviour expected?

**Comment by chaitnya12** [comment]
@Gousia-MSFT  I am facing this issue only when I add app to team using delegated permissions.

**Comment by Gousia-MSFT** [comment]
@chaitnya12 This is a known issue. We have a bug on this and we are working on it.

**Comment by Gousia-MSFT** [comment]
This is being tracked internally.
