### ISSUE TITLE
Publishing ms-teams extension to app source

### ISSUE THREAD

**Issue by yjayousi** [MicrosoftDocs/msteams-docs#1407]
Greetings,

I'm following [this documentation](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/publish) to publish a new Microsoft Teams extension to App Source. Step 5 in this page refers to [another page](https://docs.microsoft.com/en-us/office/dev/store/use-partner-center-to-submit-to-appsource) for submitting the package to App Source through Partner Center. The first step in the [second page](https://docs.microsoft.com/en-us/office/dev/store/use-partner-center-to-submit-to-appsource) dictates the following:

> On the Overview page in Partner Center, select Create a new..., and select the type of solution that you are submitting
> 
> - Office add-in
> - SharePoint solution
> - Power BI visual
> - Microsoft Teams app

However, in partner center portal, I don't see an option for Microsoft Teams App or the (new App ...) link the doc is referring to in the overview page. Here is a snapshot of what options available in the overview page in the portal:

![partner-center](https://user-images.githubusercontent.com/1314865/75448440-e10c1d00-5973-11ea-8b37-a01a1adcaeba.png)

I think either the documentation is outdated or something is missing. Please advise.

**Comment by Gousia-MSFT** [comment]
@yjayousi Please reach out to teamsubmATmicrosoft.com for help on this.
