### ISSUE TITLE
Additional explanation needed to make it work

### ISSUE THREAD

**Issue by TechWatching** [MicrosoftDocs/msteams-docs#1408]
The 3rd Step "Get an authentication token from your client-side code" does not explain where the call to getAuthToken should be done on the client side.
There is no sample for a a Teams application with a .NET backend. Is there something specific to do in the backend ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52221dd3-95ec-96b9-1da8-9478527c2602
* Version Independent ID: 32e9c2d8-733d-0865-2ea3-727d8684a10d
* Content: [Single Sign-On - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-aad-sso)
* Content Source: [msteams-platform/tabs/how-to/authentication/auth-aad-sso.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tabs/how-to/authentication/auth-aad-sso.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Gousia-MSFT** [comment]
@TechWatching Could you please try this sample to implement [SSO for Tabs](https://github.com/ydogandjiev/taskmeow)? SSO happens on Tabs and is not really specific to .Net backend. Please try out the sample and let us know if you face any issues.

**Comment by Gousia-MSFT** [comment]
Please re-open if you have any further queries.
