### ISSUE TITLE
Will the Microsoft Teams need to retrieving the new access token once old token expired.

### ISSUE THREAD

**Issue by agladboy** [MicrosoftDocs/msteams-docs#1409]
Hi There,

In OAuth case once the access token expired, will the Microsoft Teams need to issue the request to retrieve the new access token, or the Microsoft Bot Frameworks will responsible to retrieve it.

Another question is how to deal with the expiration of the verification code.

Would you please elaborate the expiration case of authentication artifacts.

Thanks!

Best regards,

Jason
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d1ce448-e51e-73db-ba9a-53faf4a16d11
* Version Independent ID: 09c2500a-3841-c6c9-82c0-5e10dc2d9c7c
* Content: [Authentication flow for bots - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/authentication/auth-flow-bot#feedback)
* Content Source: [msteams-platform/bots/how-to/authentication/auth-flow-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/bots/how-to/authentication/auth-flow-bot.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Wajeed-msft** [comment]
1. If you are using [Azure Bot Service](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/authentication/add-authentication?tabs=dotnet#create-the-identity-provider) then SDK will take care of storing the access token. Also SDK takes care of retrieving new access token. 

2. Verification code is directly passed as [signin/verifyState](https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder/Teams/TeamsActivityHandler.cs#L67) event to the Bot and SDK takes care of validating it. 

Please take a look at [C# sample code](https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/46.teams-auth) to see authentication in Bot.

**Comment by Gousia-MSFT** [comment]
Please re-open if you have any further queries.

**Comment by agladboy** [comment]
@Gousia-MSFT Thank you very much!
