### ISSUE TITLE
Refresh Token

### ISSUE THREAD

**Issue by guillaumemeyer** [MicrosoftDocs/msteams-docs#1412]
I successfully implemented SSO and I can retreive the access token. But what about the refresh token?
As far as I can understand, the generated token is a regular AD token with 1h of validity, so how could it be renewed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52221dd3-95ec-96b9-1da8-9478527c2602
* Version Independent ID: 32e9c2d8-733d-0865-2ea3-727d8684a10d
* Content: [Single Sign-On - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-aad-sso)
* Content Source: [msteams-platform/tabs/how-to/authentication/auth-aad-sso.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tabs/how-to/authentication/auth-aad-sso.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by guillaumemeyer** [comment]
OK my bad... the ```microsoftTeams.authentication.getAuthToken``` method returns an ID Token (that needs to be used server-side to get an Access Token by calling the ```https://login.microsoftonline.com/${tid}/oauth2/v2.0/token``` url), not an Access Token...

**Comment by Abhijit-MSFT** [comment]
If you still have any question on this please check this [Document](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-silent-aad).
