### ISSUE TITLE
"Add a configuration page to your messaging extension" is empty

### ISSUE THREAD

**Issue by aosolis** [MicrosoftDocs/msteams-docs#1413]
https://docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/add-configuration-page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9d17811-3418-b8a4-b540-b36ac877b406
* Version Independent ID: 03bf3f55-31c7-02ab-91e3-2ad9e8dae63d
* Content: [Add a configuration page to your messaging extension - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/add-configuration-page#feedback)
* Content Source: [msteams-platform/messaging-extensions/how-to/add-configuration-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/messaging-extensions/how-to/add-configuration-page.md)
* Product: **msteams**
* GitHub Login: @clearab
* Microsoft Alias: **anclear**

**Comment by aosolis** [comment]
@laujan I think we need a page that describes the settings and authentication protocols for a messaging extension. The sample helps, but one basically has to reverse-engineer the protocol from the sample.

**Comment by laujan** [comment]
Okay. 😃
