### ISSUE TITLE
Specify which domains need to be allowed

### ISSUE THREAD

**Issue by aosolis** [MicrosoftDocs/msteams-docs#1414]
You must allow your pages to be served in an IFrame, via X-Frame-Options and/or Content-Security-Policy HTTP response headers.
- which domains
- example Content-Security-Policy header

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9938300a-8983-2236-5d02-536b9b872225
* Version Independent ID: b336fba4-1e88-db4a-0a41-c91a57384aee
* Content: [Extend your Teams app with a custom tab - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/add-tab#host-your-app-service)
* Content Source: [msteams-platform/tabs/how-to/add-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tabs/how-to/add-tab.md)
* Product: **msteams**
* GitHub Login: @laujan

**Comment by ElliotMatthew** [comment]
We have a system that doesn't permit the use of wildcards when specifying the domain for CORS settings. Is there a full list of the subdomains under *.teams.microsoft.com *.skype.com that we need to mark as permitted for frame-ancestors?

**Comment by KirtiPereira** [comment]
Closed this issue as per inputs received from @Abhijit-MSFT  as the issue has been addressed by Loki.
