### ISSUE TITLE
OneNote integration 

### ISSUE THREAD

**Issue by drjolly1** [MicrosoftDocs/msteams-docs#1416]
I have a synced OneNote Notebook in my company's OneDrive. It is set to anyone within the company can view. When I added the Notebook as a tab inside the General channel it showed me a list of available Notebooks. I selected the corresponding Notebook and I can see it no problem. The other team members cannot and get a 'you don't have access' message. If I share the link (not add them as an invited users / shared with) and once they click on it (opens in a browser) the Notebook will show up for them inside Teams.

**Comment by Subhasish-msft** [comment]
Are they able to view the OneNote notebook outside teams (in browser ) but not in side Teams channel?

**Comment by drjolly1** [comment]
Once they open/view the Notebook in a browser, the Notebook can be seen inside Teams. The Notebook does not have to be shared directly to the user just a general view only link.

**Comment by Subhasish-msft** [comment]
I am not able to reproduce it. Can you please share some screenshot or a screen record.

**Comment by Gousia-MSFT** [comment]
Please re-open with requested information.
