### ISSUE TITLE
Missing documentation on how to couple telephone number to voice bot

### ISSUE THREAD

**Issue by wimvanhouts** [MicrosoftDocs/msteams-docs#1420]
Hi, I cannot seem to find any documentation that explains how to route a telephone number (bought via the calling plan) to a voice enabled bot. Please provide this documentation. 
One would expect documentation about the following simple use case:
- Buy a telephone number
- Create a teams bot app that has calls enable
- Allow external user to cal this telephone number and interact with the bot
This is the basic scenario of an IVR. There is described how to build an IVR, but, there is no documentation on how to make the IVR available for people that call in via PSTN

**Comment by Abhijit-MSFT** [comment]
@wimvanhouts - Check this [Document](https://docs.microsoft.com/en-us/graph/cloud-communications-phone-number).

**Comment by wimvanhouts** [comment]
Thx, figured it out also via one or two other articles. However, added some remarks from experience to that article which was giving me headaches. Maybe it saves time of other people. You can close this ticket
