### ISSUE TITLE
I think there is an error in the same provided 

### ISSUE THREAD

**Issue by Josverl** [MicrosoftDocs/msteams-docs#1422]
https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links#generating-a-deep-link-to-your-tab
in the section with the warning :
Ensure that all query parameters are properly URI encoded. 
the below seems to be an error as the url before encoding does not have a ? for the query string 

var encodedWebUrl = encodeURI('https://tasklist.example.com/123/456&label=Task 456');

so is label part of the url , or should it be specified seperately  as documented in other sections 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45541337-ecd7-5cf6-cbe4-3f0d2f39aa79
* Version Independent ID: 6b4203f0-2844-06c9-eaa3-9cc03e6f76c0
* Content: [Create deep links - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links#generating-a-deep-link-to-your-tab)
* Content Source: [msteams-platform/concepts/build-and-test/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/build-and-test/deep-links.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Subhasish-msft** [comment]
Yes, _encodedWebUrl_ and _encodedContext_ are part of the final URL _taskItemUrl_. 

final url is 'https://teams.microsoft.com/l/entity/fe4a8eba-2a31-4737-8e33-e5fae6fee194/tasklist123?webUrl=' + **encodedWebUrl** + '&context=' + **encodedContext**;
