### ISSUE TITLE
userPrincipalName or mail address

### ISSUE THREAD

**Issue by watayuk1** [MicrosoftDocs/msteams-docs#1423]
In my tenant, the email address and UPN are different, but it works fine by setting the email address to the deepkink user parameter of the chat.
Which should I set?

**Comment by Trinetra-MSFT** [comment]
@watayuk1 , Youc an use the email address as per your requirement

**Comment by watayuk1** [comment]
@Trinetra-MSFT  Thank you. I'll set mail address.
