### ISSUE TITLE
Teams desktop notifications only showing up once the application is clicked into

### ISSUE THREAD

**Issue by SnazzySnail8** [MicrosoftDocs/msteams-docs#1426]
MS Teams desktop notifications only showing up once the application is clicked into. 

I'm not getting the MS desktop notifications (though my settings are set to do so) until I click into the Teams application; then it seems I am blasted by notifications for every previous action.

**Comment by Subhasish-msft** [comment]
Are you minimizing Ms Teams or closing Ms teams ?

Can you please share screenshot of your notification settings.

**Comment by Gousia-MSFT** [comment]
Please re-open with requested information if you are still facing the issue.
