### ISSUE TITLE
Get member in Teams Messaging Extension

### ISSUE THREAD

**Issue by Dmitresky** [MicrosoftDocs/msteams-docs#1428]
Is it possible to get conversation (group) members in Teams Messaging Extension? I have tried to do it in several ways and wasn't successful.
Also, I have tried via REST API, but got the next error:
    "error": {
        "code": "BotNotInConversationRoster",
        "message": "The bot is not part of the conversation roster."
    }
}
I need something like "Schedule a meeting" pop-up in TEAMs. It is a pre-build messaging extension or something. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca47e045-6669-e130-c75a-df31ab2fa3e8
* Version Independent ID: de5e719f-c97a-0fee-c83d-f6ca176191b2
* Content: [Get Team's specific context for your bot - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/get-teams-context?tabs=dotnet)
* Content Source: [msteams-platform/bots/how-to/get-teams-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/bots/how-to/get-teams-context.md)
* Product: **msteams**
* GitHub Login: @clearab
* Microsoft Alias: **anclear**

**Comment by Gousia-MSFT** [comment]
@Dmitresky Yes, it is possible to fetch the members in the conversation using Message Extension but the bot needs to be a part of that conversation before it tries to fetch members. Could you please try [requesting to install your conversation Bot](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/messaging-extension-v3/create-extensions?tabs=typescript#request-to-install-your-conversational-bot) if fetching the list of members fails?

**Comment by Dmitresky** [comment]
@Gousia-MSFT, thank you for your answer. It looks like it for SDK v3. I didn't find something like this for SDK v4. Is it exist for SDK v4?

**Comment by Gousia-MSFT** [comment]
@Dmitresky The process would be the same for both V3 and V4. Could you please try putting a try catch while fetching the roster and do a justintimeinstall when you get an exception.

**Comment by Gousia-MSFT** [comment]
Please re-open if you are still facing any issues.
