### ISSUE TITLE
Suggested Approach for maintaining state while the user has to temporarily switch focus back to a chat?

### ISSUE THREAD

**Issue by GauravES** [MicrosoftDocs/msteams-docs#1429]
As a modal window in an iframe, any selections that the user has already made in a web form in the taskmodule is lost if the user has to switch focus momentarily to a teams chat (i.e away from the task module).  
What are suggested approach for maintaining state while the user has to temporarily switch focus back to a chat and returns to the task module, such that any inputs or selections they had made on the task module are not lost?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f40d5208-a7ae-330a-1365-9b774ca9dcaf
* Version Independent ID: a44e2980-4ed7-636c-0141-8b1e944971bb
* Content: [Using Task Modules in Microsoft Teams tabs - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/task-modules/task-modules-tabs)
* Content Source: [msteams-platform/task-modules-and-cards/task-modules/task-modules-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/task-modules/task-modules-tabs.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Subhasish-msft** [comment]
Currently on closing of task module, Teams framework does not receive any event. So it does not preserve any state. 
Teams does not keep the htlm of task module running on switching focus, it actually closes it. User has to submit the task module to save the details before closing it.

**Comment by Gousia-MSFT** [comment]
Please re-open if you have any further queries.
