### ISSUE TITLE
𝘱𝘹 or 𝘱𝘵?

### ISSUE THREAD

**Issue by RokeyKokey** [MicrosoftDocs/msteams-docs#1433]
What measure does the sizing refer to—pixels (px), points (pt) or something else?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28b26001-f33a-34e5-1f20-ecdaf45c84e2
* Version Independent ID: 1eb7cf0a-a71f-c355-64b9-97ee239b5a6c
* Content: [Design Guidelines Reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/design/components/typography#feedback)
* Content Source: [msteams-platform/concepts/design/components/typography.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/design/components/typography.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Gousia-MSFT** [comment]
@RokeyKokey It refers to pixels.

**Comment by RokeyKokey** [comment]
> @RokeyKokey It refers to pixels.

Thank you.
