### ISSUE TITLE
Chat history not pulling beyond particular date on Android Teams app

### ISSUE THREAD

**Issue by sranvi** [MicrosoftDocs/msteams-docs#1436]
I am having office 365 account and this is for office use.
I am facing an issue where for selected contact, the chat history isn't pulling beyond date feb 27 2020.
I can see the chat history for same contact on desktop teams app or web app but not in Mobile app. Tried signout, sign-in, reinstall the app, clearing cache but issue isn't fixed. When I am searching the old conversation, i can see it in search results but when selecting it, it doesn't pull that conversation, it just keeps loading.  

Is this a bug or any resolution available?

**Comment by Trinetra-MSFT** [comment]
@sranvi , Could you please tell us which teams mobile build is running on your device?

**Comment by sranvi** [comment]
Hi,

Please see attached file for full build details.
Version:1416/1.0.0.2020022503

Thank you.

**Comment by Trinetra-MSFT** [comment]
@sranvi , We are tracking this issue internally. Thanks for your patience.

**Comment by Trinetra-MSFT** [comment]
@sranvi , Could you please use Report a Problem feature within Teams help section so we can get the logs?
![image](https://user-images.githubusercontent.com/50989436/76726241-a3323580-6776-11ea-9ec2-4dcae8b1100c.png)

**Comment by sranvi** [comment]
To which email id do you want me to send logs from Teams?

**Comment by sranvi** [comment]
I have sent the mail with logs to notifications@github.com and msteams-docs@noreply.github.com

Please check

**Comment by Trinetra-MSFT** [comment]
@sranvi , Sorry for the delay in response, Could you please send the logs over `microsoftteamsdev@microsoft.com` ? This will be really helpful for us to mitigate the issue.

**Comment by Trinetra-MSFT** [comment]
@sranvi , This probably a sync issue, Could you please try to refresh cache and try again? However these are known issue with the chat history:
Observed Issues:
1. The number of chats in the Chat tab is too low and possibly missing some chat conversations
2. Cannot scroll chat message history for a given chat > than 30 days old (this issue)

Let me know if you are still facing this issue

**Comment by sranvi** [comment]
Hi, I cleared the Teams app cache and started new session of app but I am still facing issue. 
This is causing problems for me as this is business account and when m using Teams on mobile and i want to access older messages for some important content, i can not open those messages. I can search for it and it does appear in search result but I can't open that message and it says 'Couldn't find message'. Any solution available?

**Comment by Trinetra-MSFT** [comment]
@sranvi , We are unable to reproduce this issue at our end. Meanwhile could you please help to answer few questions for clarification:
	1. Is this happening for just one chat or multiple chats?
	2. For which types of chats is this happening?
	3. Are the messages they are searching for possibly deleted from the other user?
Version:1416/1.0.0.2020022503, tested:	 We have tested for the same version your teams is running on for 1:1 chats, Group chats, meeting chats

**Comment by Trinetra-MSFT** [comment]
Please feel free to reopen if you have further queries.
