### ISSUE TITLE
Mobile client personal app

### ISSUE THREAD

**Issue by dastewa** [MicrosoftDocs/msteams-docs#1443]
Pinning a personal tab app to the navigation bar on the mobile teams client requires activating developer preview mode. Is there a time line for when this will be out of preview? Or, is there a way to enable developer preview mode at a tenant level?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 008da4e2-979e-c396-db28-4acf57deb530
* Version Independent ID: f1413f77-5eb3-e1fd-9235-d322d6e4eb6c
* Content: [Developer Preview - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/dev-preview/developer-preview-intro)
* Content Source: [msteams-platform/resources/dev-preview/developer-preview-intro.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/resources/dev-preview/developer-preview-intro.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Subhasish-msft** [comment]
@dastewa , There is plan to go G.A with LOB in upcoming quarter.

**Comment by dastewa** [comment]
Awesome @Subhasish-msft , thanks for the update! Just to clarify, when this goes to GA, does it mean that activating developer preview mode will no longer be necessary for this feature?

**Comment by Subhasish-msft** [comment]
yes, You are right. Developer preview is not needed, once it goes GA

**Comment by dastewa** [comment]
Awesome, thank you! Closing.
