### ISSUE TITLE
Linux client appears to be unable to connect to gov network

### ISSUE THREAD

**Issue by PhilBax** [MicrosoftDocs/msteams-docs#1446]
Trying to use the linux client to connect to teams on the gov network, but just stalls out. Log seems to indicate an invalid url.

Steps:
- Launch preview app.
- Enter work account (<username>@<companydomain>.com).
- Enter password.
- Window closes.
- Splash screen opens with at "Loading Microsoft Teams" for about 30 seconds.
- Teams window reopens saying "We've run into an issue" for about 10 seconds.
- Asks to sign in again. Rinse and repeat.

[logs.txt](https://github.com/MicrosoftDocs/msteams-docs/files/4331100/logs.txt)

![snapshot1](https://user-images.githubusercontent.com/7528863/76650229-244bbb80-6530-11ea-88f3-838950783941.png)

**Comment by PhilBax** [comment]
Sorry, I didn't realize this was just for documentation :(

**Comment by tecandrew** [comment]
@PhilBax have you found a workaround for this? I'm having the same issue...
I've tried apps (mainly FOSS) apps and viewing the network traffic I keep getting errors like 

```json
errorCode: "BadRequest"
message: "AADSTS900382:
  Confidential Client is not supported in Cross Cloud request.......
```

**Comment by PhilBax** [comment]
I have not! However, I logged the bug in the correct place here: https://microsoftteams.uservoice.com/forums/908686-bug-reports/suggestions/39933604-linux-client-not-working-on-gov-domain

Please post your extra info there and upvote it! We almost have enough votes to get us on the first page under "all ideas"!
