### ISSUE TITLE
Unable to load package "Microsoft.Bot.Connector.4.6.2"

### ISSUE THREAD

**Issue by XimenaWang** [MicrosoftDocs/msteams-docs#1447]
Follow the Teams samples, I want to download the package, but failed and got the error 401, could you give me some suggestions, For example, do I need to join any group? Any insight you have would be greatly appreciated, thanks 
![image](https://user-images.githubusercontent.com/30890958/76750608-d1deea80-673b-11ea-8c97-c4db0f4d986f.png)

**Comment by Trinetra-MSFT** [comment]
@XimenaWang , However this doesn't seems to be a Teams specific issue. But I would suggest you to renter your credentials in visual studio and try to download the package from nuget source.
