### ISSUE TITLE
Authentication documentation - Redirecting to 404 page

### ISSUE THREAD

**Issue by anuraj** [MicrosoftDocs/msteams-docs#1448]
The Authentication documentation redirecting to https://docs.microsoft.com/en-us/concepts/authentication/authentication.md page which doesn't exist. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b294c444-a6ae-a5e7-4f65-26715b1a3cf6
* Version Independent ID: 5df1b473-c136-64f6-b818-c34d0239cd1c
* Content: [Tips and frequently failed cases - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases)
* Content Source: [msteams-platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Wajeed-msft** [comment]
@laujan - Could you please help to fix this?
