### ISSUE TITLE
Meeting Options in Dark Mode are Unreadable

### ISSUE THREAD

**Issue by mjzwick** [MicrosoftDocs/msteams-docs#1450]
I am using Microsoft Teams Version 1.3.00.4460 on MacOS 10.15.3 in Dark Mode and Firefox 73.0.1 in Dark Mode. When I click the Meeting Options link when creating or editing a meeting in the MacOS Teams App, when I use that link in Firefox (you cannot use the link in Safari) which is also in Dark Mode, the dropdown lists for "Who can bypass the lobby?" and "Who can present?" are white text against a white background, making them unreadable. If you hover over either field with the mouse, the slight graying of the dropdown box lets you barely be able to read the text in the box. Attached is an example:
<img width="910" alt="Screen Shot 2020-03-17 at 2 49 21 PM" src="https://user-images.githubusercontent.com/2848019/76892100-807c4b80-6860-11ea-89d0-77b06d7bde76.png">

**Comment by Trinetra-MSFT** [comment]
@mjzwick , We are looking into it. Meanwhile could you please test this on other devices.

**Comment by mjzwick** [comment]
The only other device I can test it on is my iPhone (iPhone 8 running iOS 13.3.1). I tried it using Firefox, and it worked in light and dark modes fine. I could not figure out how to get Chrome into dark mode (light mode is fine). The attached is for Firefox.
![CDF13DD5-6EB8-4249-A594-FB07465D85EC_1_201_a](https://user-images.githubusercontent.com/2848019/77432682-c8492880-6db4-11ea-89bd-b14439a6e56a.jpeg)
![E0736B70-4B8B-4352-B33F-1001D3767AAD_1_201_a](https://user-images.githubusercontent.com/2848019/77432684-c97a5580-6db4-11ea-821f-4cd33567b024.jpeg)

**Comment by Trinetra-MSFT** [comment]
@mjzwick , We have tested this at our end, it works fine for Android, iOS mobile devices. This works as well windows teams desktop and web verison in firefox but issue persist on Mac iOS we are discussing this internally about it.

**Comment by Trinetra-MSFT** [comment]
@mjzwick , We have opened a Bug for this. We will let you know once it is fixed.
