### ISSUE TITLE
Typing indicator sent from bot doesn't display in Teams threaded conversation

### ISSUE THREAD

**Issue by stevkan** [MicrosoftDocs/msteams-docs#1451]
When developing a bot using the BotFramework SDK (C# or Node), if a typing indicator is sent from the bot in a 1:1 or group chat, it displays to the user. However, if it's sent in a threaded conversation in a Team's channel (i.e. I've @mentioned the bot), it does not display to the user. Yet, any associated delay in the typing indicator is respected.

This is true when sending from the bot's adapter, from an activity handler (e.g. `onMessage()` or `onMessageActivityAsync()`, see below examples), or from within a waterfall step.

Node example code:
```
await context.sendActivities([
  { type: ActivityTypes.Typing },
  { type: 'delay', value: 3000 }
]);
```

C# example code:
```
await turnContext.SendActivitiesAsync(
    new Activity[] {
new Activity { Type = ActivityTypes.Typing },
new Activity { Type = "delay", Value= 3000 },
    },
    cancellationToken);
```

**Comment by Gousia-MSFT** [comment]
@stevkan Typing indicator is only supported in 1:1 and group chat. It is not supported in Teams scope. Just like, in a team there is no typing indicator shown when a user types a message.
