### ISSUE TITLE
Some things unclear in SSO docs

### ISSUE THREAD

**Issue by gabbsmo** [MicrosoftDocs/msteams-docs#1460]
**Create your AAD application in Azure**

It is not clear whether access_as_user scope is a requirement or just an example. My AD app has a scope user_impersonation already created automatically, can I use it instead?

It is not clear whether "Who can consent" is required to be "Admins and users" or if it is an example. In my case the app is always installed with admin consent.

It is not clear whether the API Permissions are required or an example.

**Get an authentication token from your client-side code**

It is not clear what type of token the getAuthToken function returns. Seems to be a id token. It is also not clear how it should be used with adal.js, if it is possible at all. 

The code below will fail to extract a user from the id token because aud is a resource url and it expects the guid specified in `authContext.config.clientId`.

```
var hash = '#id_token=' + token + '&state=' + authContext._renewStates[0];
var requestInfo = authContext.getRequestInfo(hash);
authContext.saveTokenFromHash(requestInfo);
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52221dd3-95ec-96b9-1da8-9478527c2602
* Version Independent ID: 32e9c2d8-733d-0865-2ea3-727d8684a10d
* Content: [Single Sign-On - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-aad-sso)
* Content Source: [msteams-platform/tabs/how-to/authentication/auth-aad-sso.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tabs/how-to/authentication/auth-aad-sso.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Subhasish-msft** [comment]
@gabbsmo , Could you please take a look at demo code and try it out once?

https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-aad-sso#demo-code

**Comment by gabbsmo** [comment]
@Subhasish-msft I did look at the demo code. I find that sso.auth.service defines a function getToken that gets a token using Teams SSO. I have done that successfully. What I cannot find in the example is what to do with the token to login to my adal app.

My Teams tab is just a very small page that is supposed to login the current user using adal and the redirect to another web page that is also using adal. The other web page is a SPA that is accessible from the internet and is not bundled in my Teams app, but since both use the same app id the token I get from the Teams app should be reusable.

**Comment by Subhasish-msft** [comment]
@gabbsmo ,

- No, it should be called access_as_user. In the Teams clients that use the v2.0 endpoint, the request for a token specifies scopes, so it will fail if the app doesn't have the access_as_user scope.

- If the app is always installed with the admin preconsenting to the necessary permissions, then no, the setting doesn't matter.
- "openid" is required
- getAuthToken returns a user-delegated access token to your apps's resource
	
              

  - appid/azp = the Teams client (one of the 2 app ids that were registered as known client apps)
  - sub (and related claims) refer to the user logged in to Teams
  - aud = your application
		See https://docs.microsoft.com/en-us/azure/active-directory/develop/access-tokens#claims-in-access-tokens
