### ISSUE TITLE
Bot how to send important/urgent  message to one person

### ISSUE THREAD

**Issue by XimenaWang** [MicrosoftDocs/msteams-docs#1461]
Hi All, my Bot can send proactive message to people now, but I want to mark the message as urgent, 
![image](https://user-images.githubusercontent.com/30890958/77143221-d4915680-6a3f-11ea-8d77-b87712bef7ff.png)

Are there any properties I can change? I checked the Activity class, no category I can set, could you give me some advice, thanks!
![image](https://user-images.githubusercontent.com/30890958/77143130-811f0880-6a3f-11ea-89a3-dfe893df4288.png)

**Comment by Trinetra-MSFT** [comment]
@XimenaWang , Currently, this is not possible to mark a message **!IMPORTANT**  through bot, However you can @mention user to notify them but that works within team or channel conversation.

**Comment by XimenaWang** [comment]
> @XimenaWang , Currently, this is not possible to mark a message !IMPORTANT  through bot, However you can @mention user to notify them but that works within team or channel conversation.

Hi team, we have implemented the mention feature in channel, and just want to know if ms teams can support the !IMPORTANT feature in personal conversation. if it can' t support now, would you mind tell me when this feature will be available in the future , thank you in advance!

**Comment by Trinetra-MSFT** [comment]
@XimenaWang , Thanks for the update, Currently marking a message !IMPORTANT is not possible through bot, You can directly notify the user in 1:1 conversation using bot. Please raise a [uservoice ](https://microsoftteams.uservoice.com/forums/555103-public/filters/new)so we can take this as feature request.

**Comment by XimenaWang** [comment]
ok, I created one in uservoice, waiting the new feature, thanks for your response
