### ISSUE TITLE
UPLOAD FAIL

### ISSUE THREAD

**Issue by pallagj** [MicrosoftDocs/msteams-docs#1462]
I can't upload an image to a group in Microsoft Teams. :((
I tried Chrome, Firefox, the desktop app.

**Comment by Wajeed-msft** [comment]
@pallagj - Are you trying to upload image in a group chat or setting an icon for your team? Could you please send screenshot of your issue?

**Comment by Wajeed-msft** [comment]
@pallagj - Could you please share more information here?

**Comment by pallagj** [comment]
Oh, I tried it again. Sometimes it working.

In Chorme, in the desktop application:
There is a button for upload image, it is okay, but if I click the link in the button, it doesn't work, just around the text, but I think it is guessable.

I think it is okay, now, may it be fixed, first time, when I wrote the issuse it doesn't work at all, just if I tried lot's of posiotion of the button with double klikk.

**Comment by Wajeed-msft** [comment]
Thanks for confirmation. Closing this issue.
