### ISSUE TITLE
Authentication issue in tabs (tab as a task module)

### ISSUE THREAD

**Issue by sathishreddy48** [MicrosoftDocs/msteams-docs#1463]
trying to open react page as a task module and while loading the page trying to authenticate and getting the teams channels info using logged in user-id I am getting different errors while doing this operation . Couldn't be able to fetch channels information in (task module ) page 

React *.tsx files

invalid_resource; Error description:AADSTS500011

**Comment by sathishreddy48** [comment]
few other details : Silent authentication issue

**Comment by Abhijit-MSFT** [comment]
@sathishreddy48 - Try this [Sample code](https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/javascript_nodejs/46.teams-auth). This has silent auth developed.

**Comment by sathishreddy48** [comment]
I am actually looking for something else , while opening task module I am getting this issue , issue fixed with latest updates pushed from Microsoft recently .
