### ISSUE TITLE
No desktop notification when tab active

### ISSUE THREAD

**Issue by kogaba** [MicrosoftDocs/msteams-docs#1464]
If chrome is in background but teams is the active tab, I don't get desktop notifications.
lichess.org works with the same circumstances.

Tested on:
Chrome 80.0.3987.122 (Official Build)
Chrome 80.0.3987.149 (Official Build)

**Comment by Subhasish-msft** [comment]
Have you enabled desktop notification setting ?
![image](https://user-images.githubusercontent.com/56869764/77283933-87d5a600-6cf3-11ea-80b7-deef67e74b49.png)

You need to enable chrome Notification settings as well. By default chrome blocks notifications.

**Comment by kogaba** [comment]
"When tab active" I mean, if I select other tab than teams, desktop notification are coming.

**Comment by Subhasish-msft** [comment]
@kogaba , I have shared this feedback with internal teams. Thanks for your feedback.
