### ISSUE TITLE
The sample doesn't show a option for a configuration

### ISSUE THREAD

**Issue by nastassiar** [MicrosoftDocs/msteams-docs#1469]
I tried the C# sample and there is no settings or configuration option visible. When I set a breakpoint in OnTeamsMessagingExtensionConfigurationSettingAsyncit is never hit. Does the manifest need to be updated to include something? This also means for the sample there is no way to have it go through the Email search flow. I had to change the code to force it to this. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9d17811-3418-b8a4-b540-b36ac877b406
* Version Independent ID: 03bf3f55-31c7-02ab-91e3-2ad9e8dae63d
* Content: [Add a configuration page to your messaging extension - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/add-configuration-page)
* Content Source: [msteams-platform/messaging-extensions/how-to/add-configuration-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/messaging-extensions/how-to/add-configuration-page.md)
* Product: **msteams**
* GitHub Login: @clearab
* Microsoft Alias: **anclear**

**Comment by nastassiar** [comment]
Does the configuration page related to the setting "canUpdateConfiguration": true in the app manifest at all? 

https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema

**Comment by nastassiar** [comment]
I didn't read closely enough! When I followed the instruction in the sample I was able to trigger the configuration: https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/52.teams-messaging-extensions-search-auth-config#interacting-with-the-bot-in-teams

The issue is that it always errors out. My guess is that the sample is missing searchSettings.html? But I am not sure. Either way updating this page to have more information on the configuration page would be helpful!

**Comment by Trinetra-MSFT** [comment]
@nastassiar , Thanks for following up the documentation. Here is mentioned that Once the Messaging Extension is installed, click the icon for Config Auth Search in the Compose Box's Messaging Extension menu to display the search window. Left click to choose Settings and view the Config page

**Comment by nastassiar** [comment]
Thanks for the response. For the C# sample the configuration/setting does appear to work. After running it with no code changes when I choose settings I get: "Sorry, the setting of this compose extension is not available. Please try again later."

**Comment by nastassiar** [comment]
The code is running and works just fine for doing the actual search but the Settings are inaccessible which means one flow of the code is untestable (without making changes to the code).

**Comment by clearab** [comment]
@EricDahlvang Can you take a look at this one?

**Comment by EricDahlvang** [comment]
Hi @nastassiar 

Does the appsettings.json have the publicly exposed url for `SiteUrl`?

I just tried the sample, and the settings page loads as expected.

**Comment by nastassiar** [comment]
Yeah it has the ngrok link that connects to my localhost. I double checked it.

**Comment by EricDahlvang** [comment]
Do you see a GET request for `searchSettings.html` in the ngrok window?

![image](https://user-images.githubusercontent.com/11055362/77362363-07706e80-6d0e-11ea-8bde-1ff576a7aa3f.png)

**Comment by nastassiar** [comment]
I'm not sure what I was doing wrong before but it started working now!

Thanks for the help!

**Comment by EricDahlvang** [comment]
Oh, good to hear! :)
