### ISSUE TITLE
Diagram of message flow for extensions has dark labels that do not have enough contrast when used with a dark theme

### ISSUE THREAD

**Issue by msft-ray** [MicrosoftDocs/msteams-docs#147]
In the topic [Develop messaging extensions for Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/messaging-extensions), the image named [ceflow.png](https://docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/ceflow.png) - _Diagram of message flow for messaging extensions_ - has labels that are black (or nearly black), resulting in a very low contrast with the background when viewed in a dark theme. This makes the labels practically unusable.

**Comment by billbliss** [comment]
@NormSohl - he's right - can you update this?

**Comment by NormSohl** [comment]
Thanks for the heads-up.  The image no longer has a transparent background.
