### ISSUE TITLE
Bot is unable to receive attached files in Teams

### ISSUE THREAD

**Issue by glucan1** [MicrosoftDocs/msteams-docs#1470]
I have a bot running in Teams (Bot Framework SDK v4) but when I'm trying to upload an attachment (other than an image) from a Microsoft Teams channel to my bot, the file doesn't show up anywhere in the message that the bot receives. 
In bot's session.message.attachments i receive only its mention, as below.

```
{
  "contentType": "text/html",
  "content": "<div><div><span itemscope=\"\" itemtype=\"http://schema.skype.com/Mention\" itemid=\"0\">bot_name</span>&nbsp;</div>\n</div>"
}
```
 I want to mention that I set the supportsFiles property in the manifest to true.
 Is there a way for the bot to receive files in a Teams channel?

**Reproduction Steps**
1. Attach file using paperclip in Teams
2. @-mention bot and send message

**Comment by Subhasish-msft** [comment]
Hi @glucan1 ,

Bot can only send and receive file in personal chat. It does not work in the channel or group chat context. 
Here is the [link](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/send-and-receive-files?tabs=dotnet#using-the-teams-bot-apis)

![image](https://user-images.githubusercontent.com/56869764/77416706-3b20c680-6dea-11ea-8077-c47d75275d36.png)

**Comment by Gousia-MSFT** [comment]
Please re-open if you still have any queries.
