### ISSUE TITLE
Document that some device permissions are not available on desktop client

### ISSUE THREAD

**Issue by aosolis** [MicrosoftDocs/msteams-docs#1473]
The page notes that device permissions are not available on mobile. They're also currently not available on desktop client either (only browser is working).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce494c52-9c5f-d294-c304-53ac466fa3ea
* Version Independent ID: ebd112aa-71c4-a7d6-aa9f-6e14c50be25c
* Content: [Request device permissions for your Microsoft Teams tab - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/native-device-permissions)
* Content Source: [msteams-platform/tabs/how-to/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tabs/how-to/native-device-permissions.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by slyholborn** [comment]
Same issue on linux desktop client : on fedora 31, mic and cam only works fo root user. (rpm version, no snap install)

**Comment by Wajeed-msft** [comment]
Note has been added to the docs.
![image](https://user-images.githubusercontent.com/31851992/93758084-682d2500-fc25-11ea-937e-f90386b1128c.png)
