### ISSUE TITLE
Clarify if device permissions work in task module

### ISSUE THREAD

**Issue by aosolis** [MicrosoftDocs/msteams-docs#1474]
The page is specific to tabs-- do device permissions work in task modules? If so please generalize the page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce494c52-9c5f-d294-c304-53ac466fa3ea
* Version Independent ID: ebd112aa-71c4-a7d6-aa9f-6e14c50be25c
* Content: [Request device permissions for your Microsoft Teams tab - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/native-device-permissions)
* Content Source: [msteams-platform/tabs/how-to/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tabs/how-to/native-device-permissions.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by nastassiar** [comment]
I have the same question!

**Comment by shuchauh** [comment]
The permissions work for apps hosted on Tab and Task Module alike.

Although the page has been moved to a generic location now: ((https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?tabs=desktop))
the content still talks specifically of Teams tab. Please look into it.

**Comment by nastassiar** [comment]
Even though it has been moved to a generic location there is nothing on the page to indicate that these device permissions work for anything other than a tab. An additional note or language referencing Task Modules would help as a user.
