### ISSUE TITLE
Hello, i have problem to get Teams APP to work.

### ISSUE THREAD

**Issue by michaelamar1991** [MicrosoftDocs/msteams-docs#1478]
generateWebhook() {
    microsoftTeams.initialize(() =&gt; {
      console.log("teams sdk init"); // This callback never fired back to me.
    });
    microsoftTeams.settings.setValidityState(true);

    microsoftTeams.settings.setSettings({
      websiteUrl: "https://cloudvisor.io",
      contentUrl: "https://0c2f5341.ngrok.io/teams",
      entityId: "1a408017-b1f5-447b-bd0c-b019b3955fa7",
      suggestedDisplayName: "Cloudvisor"
    });
    microsoftTeams.settings.getSettings((s) =&gt; {
      console.log(s.websiteUrl + s.contentUrl + s.entityId + s.removeUrl + s.suggestedDisplayName);
    }) // This console.log didn't print anything

    microsoftTeams.settings.registerOnSaveHandler((saveEvent) =&gt; {
      this.temp = "onSave"
      
       microsoftTeams.settings.getSettings(s =&gt; {
         console.log(s);
         document.getElementById("webhook-url").innerText = s.websiteUrl;
         this.temp = s.websiteUrl
         console.log(s.websiteUrl);
      }); // this one also not returning me anything it is not getting inside the callback.

      this.temp = saveEvent.result.webhookUrl;
      console.log(saveEvent.result.webhookUrl); // prints nothing...
      saveEvent.notifySuccess();
  });
}

This is my code, i cant get it work i wrote it with the instructions but seems that it isn't work, can you guys help me understand my problem and get it to work?

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4f41824-2d43-bb6d-399f-6a8305f8c7d1
* Version Independent ID: a5b59a6e-6486-a286-5de0-62a31a329f4c
* Content: [Building an app for Microsoft Teams - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/building-an-app#feedback)
* Content Source: [msteams-platform/concepts/building-an-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/building-an-app.md)
* Product: **msteams**
* GitHub Login: @clearab
* Microsoft Alias: **anclear**

**Comment by Gousia-MSFT** [comment]
@michaelamar1991 Could you please share more details on what you are trying to do? Please share some links that you are following and the issue you are facing.

**Comment by Gousia-MSFT** [comment]
Please re-open with requested information
