### ISSUE TITLE
Vector format for design files

### ISSUE THREAD

**Issue by janzelc** [MicrosoftDocs/msteams-docs#148]
The design references in https://github.com/MicrosoftDocs/msteams-docs/tree/master/msteams-platform/assets/downloads appear to be all bitmap, making them unsuitable for importing into Sketch, Adobe Illustrator, etc.

Please upload the vector originals so that we can put these resources to use.

**Comment by billbliss** [comment]
I asked our designers if this was practical and unfortunately it's not. Our source files have all sorts of stuff in them that's unrelated to what we published here.
