### ISSUE TITLE
CSS and color codes for the recommendations?

### ISSUE THREAD

**Issue by bealsao** [MicrosoftDocs/msteams-docs#1482]
This article is great but it's difficult to work with just pictures in terms of colors and styles.

If possible, you can provide the associated CSS or just the color codes for each example that would help would be great!

I am aware that the color codes are under the "color" document (where I have been looking for them currently) however being color blind I find it difficult to hunt and match the appropriate colors with this style guide.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8339b40d-2cc4-8f9c-a83f-433fa2eaf47e
* Version Independent ID: 9f5f6ac6-4fca-1468-d1cd-7b055cdb88b7
* Content: [Design Guidelines Reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/design/components/buttons#feedback)
* Content Source: [msteams-platform/concepts/design/components/buttons.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/design/components/buttons.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by laujan** [comment]
Hi @bealsao. I have updated the **Buttons, links, and controls** article to add a reference to the Fluent UI site where [suggested color values for buttons can  be found](https://fluentsite.z22.web.core.windows.net/components/button/definition?showCode=false&showRtl=false&showTransparent=false&showVariables=true#types-emphasis). Thank you again for bringing this issue to our attention.

**Comment by bealsao** [comment]
Thank you! I appreciate it!
