### ISSUE TITLE
Add the reference to the javascript_nodejs version

### ISSUE THREAD

**Issue by hinojosachapel** [MicrosoftDocs/msteams-docs#1487]
Please, update de document and add the reference to the **javascript_nodejs** version. Currently there are only references to Bot authentication in cs-auth-sample and Bot authentication in python-auth-sample.

https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/javascript_nodejs/46.teams-auth

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63519845-323f-be8f-ce15-d7f39e46b5a7
* Version Independent ID: 70952f91-56e9-ff08-59f6-e237d4aaeca9
* Content: [Add authentication to your Teams bot - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/authentication/add-authentication?tabs=dotnet)
* Content Source: [msteams-platform/bots/how-to/authentication/add-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/bots/how-to/authentication/add-authentication.md)
* Product: **msteams**
* GitHub Login: @clearab
* Microsoft Alias: **anclear**

**Comment by laujan** [comment]
Hi @hinojosachapel! Thank you for your feedback. The javascript references have been added to the above referenced article. Thanks again!
