### ISSUE TITLE
The link to the Office 365 Developer Program is not correct

### ISSUE THREAD

**Issue by luispb** [MicrosoftDocs/msteams-docs#1490]
In the first line of the "Just need a development environment?" paragraph, the link to the Office 365 Developer Program is not working. I believe the right link should be: https://developer.microsoft.com/en-us/microsoft-365/dev-program

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3530b55-59c8-6eec-b257-b7a5f2ed046b
* Version Independent ID: 022f7eff-f6c2-9a73-afa9-74e887b761e1
* Content: [Prepare your Office 365 tenant - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/prepare-your-o365-tenant#just-need-a-development-environment)
* Content Source: [msteams-platform/concepts/build-and-test/prepare-your-o365-tenant.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/build-and-test/prepare-your-o365-tenant.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by laujan** [comment]
Hi @luispb! The hyperlink to the Developer Program has been updated. Thank you again!
