### ISSUE TITLE
Showing "**話し言葉の bot**" (extra asterisks appears)

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/msteams-docs#1491]
ja-jp:"https://docs.microsoft.com/ja-jp/microsoftteams/platform/concepts/extensibility-points"
![extensibility-points](https://user-images.githubusercontent.com/40815708/77639229-c5f4f300-6f9b-11ea-89fb-11284683d733.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0497b303-6e14-d6bc-2580-e2392fb2815d
* Version Independent ID: 6a720518-c815-e693-6eb7-181bde9abc5a
* Content: [Extensible points in the Teams client - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/extensibility-points)
* Content Source: [msteams-platform/concepts/extensibility-points.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/extensibility-points.md)
* Product: **msteams**
* GitHub Login: @clearab
* Microsoft Alias: **anclear**

**Comment by laujan** [comment]
Hi @hyoshioka0128. I updated the above-mentioned article; please let me know if you continue to see the extra asterisks. Thank you!
