### ISSUE TITLE
Missing javascript_nodejs versions

### ISSUE THREAD

**Issue by hinojosachapel** [MicrosoftDocs/msteams-docs#1494]
Please, add javascript_nodejs versions. The initiative is fantastic but useless for the javascript_nodejs community. Even the cards definitions are not in json format so, we cannot reuse it!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 100070d1-40f9-b5eb-be0a-6199de26e0e6
* Version Independent ID: 5d1269e3-2775-ebf6-cf9a-8d1ee7038397
* Content: [Microsoft Teams app templates - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/samples/app-templates#feedback)
* Content Source: [msteams-platform/samples/app-templates.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/samples/app-templates.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Trinetra-MSFT** [comment]
@hinojosachapel , Thanks for pointing this out, Currently production ready templates are available in C# on github, Java script node js versions are not available we will take this for further enhancement.

**Comment by hinojosachapel** [comment]
Yeah, that's my point! Keep the good work on! Regards.

**Comment by laujan** [comment]
Thank you!
