### ISSUE TITLE
Formatting Message Text in a Deeplink

### ISSUE THREAD

**Issue by rlingineni** [MicrosoftDocs/msteams-docs#1495]
Let's say I want to send a list of links to a user as part of the message - how can we make sure that Teams will render it as a hyperlink. 

For example - if my draft deeplink draft message has `https://microsoft.com` - that is not being rendered by the text editor as a hyperlink. This causes pain for our customers who have to copy and paste that link. 

msft alias: @ralingin

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45541337-ecd7-5cf6-cbe4-3f0d2f39aa79
* Version Independent ID: 6b4203f0-2844-06c9-eaa3-9cc03e6f76c0
* Content: [Create deep links - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links#feedback)
* Content Source: [msteams-platform/concepts/build-and-test/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/build-and-test/deep-links.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Trinetra-MSFT** [comment]
@rlingineni , Are you talking about deep link or sending a normal link to the user in draft message? sending link to user in draft message create hyperlink too. Please take a look at below screenshot:
![image](https://user-images.githubusercontent.com/50989436/77878222-79e4cf80-7275-11ea-808f-6ee30653dd00.png)

**Comment by rlingineni** [comment]
Hey @Trinetra-MSFT , thanks for getting back. Apologies for not being clear.

Where this fails is with multiple links. Note that the first link doesn't render. If I was sending a user a list of bugs, they are unable to access them. They have to copy and paste each link individually. 

![image](https://user-images.githubusercontent.com/5509813/77944554-c71c6d80-7284-11ea-98d1-8bbb25453f91.png)


A second question is also if rich formatting is supported (e.g. can I bold some part of the deeplink message)

**Comment by Trinetra-MSFT** [comment]
We can't reproduce this issue at our end. Could you please try to send multiple links like this?
![image](https://user-images.githubusercontent.com/50989436/78328957-0bb64a80-759e-11ea-8519-872487ab2f5f.png). Please help us to know your which teams client version you are running on.

**Comment by Gousia-MSFT** [comment]
Please re-open if you are still facing the issue.
