### ISSUE TITLE
How to maintain user state?

### ISSUE THREAD

**Issue by anuraj** [MicrosoftDocs/msteams-docs#1499]
I am integrating my app to teams using Tabs feature. I am able to integrate authentication with my API. My challenge is how can I maintain state - for example - I am getting some configuration values from my API when the user is authenticated, and I want to display the content inside the tab based on these values. How or where I can store these kinds of state information? I tried with local storage in browser but it is not working in the Desktop app it seems. Is there a Microsoft recommendation available? or any API to store custom values?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b1dcd0d-471b-2d33-54b5-39a93dfba2a8
* Version Independent ID: 5bd44149-777e-b449-bd2e-f20b9bd04038
* Content: [Authentication for tabs using Azure Active Directory - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-tab-aad)
* Content Source: [msteams-platform/tabs/how-to/authentication/auth-tab-aad.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tabs/how-to/authentication/auth-tab-aad.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Abhijit-MSFT** [comment]
@anuraj - What values are you trying to send?

**Comment by anuraj** [comment]
Something like my user's tenant info, their email address, their rank, profile pic information like this. Also, authentication token, which is required for all the requests once they logged in to our app.

**Comment by Abhijit-MSFT** [comment]
@anuraj - All this information can be fetched from tab context. Check these [docs](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/access-teams-context)

**Comment by anuraj** [comment]
So if I understand correctly, as part of the response I need to set those values as query strings, and teams runtime will set it as part of context? So I can later read it from the context.

**Comment by Trinetra-MSFT** [comment]
@anuraj , No, `microsoftTeams.getContext(function(context) { /* ... */ })` uses [Teams javascript client SDK](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/access-teams-context#getting-context-by-using-the-microsoft-teams-javascript-library) which returns you users email, UPN, tenant id and much more information, while uploading the manifest within teams you need to set entity Id for your tab and the content url which you want to display within Teams tab That's it. you can get the context and save it for further use, however it doesn't return you the profile pic infomartion or token. You can get the[ photo using Graph API](https://docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-1.0)

**Comment by anuraj** [comment]
@Trinetra-MSFT Let me explain my scenario, I am authenticating with my token endpoint. I am getting a token. This token is required for all other API calls. 

As per my understanding, I need to store the token is some storage which is associated with the current user. Since the authentication is happening with Teams SDK, I won't be getting the users credentials. I tried with local storage API to store the token and all, it is working in the web app, but in the Desktop app it is not. So my question is - is there place available in teams where I can store the user state data?

I am using my API token endpoint. So I don't think I can use adal.js. 

Do you have a sample available - in which a tab is showing content after authentication? I tried to create an ASP.NET Core MVC app with Cookie authentication, and load it inside tab - But that also is not working 😢

**Comment by Trinetra-MSFT** [comment]
@anuraj , We have Bot builder SDK v4 samples for authentication. May be this will help you to solve the issue. Please take a look at [TeamsAuth ](https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/46.teams-auth)sample code.

**Comment by anuraj** [comment]
@Trinetra-MSFT I saw the content for Bots. But what about tabs? I do see a lot of applications running in the tab. Why MS doesn't have a sample for tabs with authentication? 😕

**Comment by Trinetra-MSFT** [comment]
@anuraj , Here is the sample for [Authentication in Tabs](https://github.com/OfficeDev/microsoft-teams-sample-complete-csharp). You can try this , let me know if this doesn't help you.

**Comment by anuraj** [comment]
@Trinetra-MSFT Thanks. Let me explore and will try to implement it. Will get back if there are any questions.

**Comment by Trinetra-MSFT** [comment]
Please feel free to reopen if you have further queries

**Comment by FaizanButt1997** [comment]
Please guide me if you find any solution I'm stick on same problem where I store user-credential and access-token ?
Please reply im waiting
