### ISSUE TITLE
Unable to invoke bot from Microsoft teams(web)

### ISSUE THREAD

**Issue by sathishreddy48** [MicrosoftDocs/msteams-docs#1501]
TransactionLockHelper.ts:155 Uncaught (in promise) Error: IndexedDbTransaction Aborted, Error: , History: abort-
    at e.transactionFailed (TransactionLockHelper.ts:155)
    at IDBTransaction._trans.onabort (IndexedDbProvider.ts:398)
e.transactionFailed @ sha256.js:1
_trans.onabort @ sha256.js:1
13Refused to set the document's base URI to '<URL>' because it violates the following Content Security Policy directive: "base-uri *.protection.outlook.com".

16TransactionLockHelper.ts:155 Uncaught (in promise) Error: IndexedDbTransaction Aborted, Error: , History: abort-
    at e.transactionFailed (TransactionLockHelper.ts:155)
    at IDBTransaction._trans.onabort (IndexedDbProvider.ts:398)

**Comment by Subhasish-msft** [comment]
Hi @sathishreddy48, Can you please provide more insight about the issue? In what scenario you are facing this?

**Comment by sathishreddy48** [comment]
Sure , We have created a bot with tabs (tabs with silent-authentication ) ,While trying to communicate with the bot using bot commands we are not able to get the response . till 29th March 8 PM IST we are able to communicate without any issues but after that is stopped working , when we see the logs in console we've received above error results .

logs in the browser console : 

Refused to set the document's base URI to '<URL>' because it violates the following Content Security Policy directive: "base-uri *.protection.outlook.com".

15TransactionLockHelper.ts:155 Uncaught (in promise) Error: IndexedDbTransaction Aborted, Error: , History: abort-
    at e.transactionFailed (TransactionLockHelper.ts:155)
    at IDBTransaction._trans.onabort (IndexedDbProvider.ts:398)

**Comment by Subhasish-msft** [comment]
> Refused to set the document's base URI to '' because it violates the following Content Security Policy directive: "base-uri *.protection.outlook.com".

From this error, it can be deduced that it is trying to set '' (null) as base url.

**Comment by sathishreddy48** [comment]
Could you please explain me why it is setting to Null ?? from where we need to change that value ?is this happening because of our settings ??

**Comment by Wajeed-msft** [comment]
@sathishreddy48 - Could you please share the Bot Id for which you are facing this issue? Also, are you facing this issue only on Web client?

**Comment by sathishreddy48** [comment]
Yes only in web client , I've created bot with lower version (2.1 core) and it worked .
