### ISSUE TITLE
Blank Notifications on macOS Catalina

### ISSUE THREAD

**Issue by zorro2b** [MicrosoftDocs/msteams-docs#1502]
On macOS Catalina 10.15.4, the chat notifications in the notification centre show up blank in the corner of the screen until you click on them.
This makes them not very useful.

**Comment by Trinetra-MSFT** [comment]
@zorro2b , Thanks for reporting this. This is a known issue. we are looking into this.

**Comment by AndyBehr** [comment]
This issue still exists. I wonder why the bug has been acknowledged and the closed?

**Comment by vandenbergrobin** [comment]
Same issue for me, it also freezes my video calls

**Comment by joshwhatk** [comment]
@Trinetra-MSFT, is there a bug ticket that we can watch on a different platform if this is not the correct medium?

**Comment by markgammon** [comment]
Had this issue for at least a couple of months with video freezing when notifications come in. Lots of updates along the way, but none that address this very annoying issue!

**Comment by vandenbergrobin** [comment]
@Trinetra-MSFT please re-open the issue. This has not been resolved.

**Comment by barrand** [comment]
I'm having this issue also. I get video freezing with every. single. notification. It is really annoying. 
Also, my notifications are blank. Why is this issue closed?
Teams version 1.3.00.9271
OS Catalina 10.15.5 (19F101)

**Comment by petr-ujezdsky** [comment]
It seems like this happens only on company MBP (remotely administerable) or on newer HW.
I have 2 MBP, one personal (MBP 15", 2017) and one from my company (MBP 16", 2019). Both on same Catalina (10.15.5) and with same Teams (1.3.00.9271).
I see blank notifications only on the newer one. Hope this could help to resolve the issue.

**Comment by jennasalau** [comment]
OMG Microsoft please fix your shitty software. This bug is so frustrating.

**Comment by mash1t** [comment]
Issue still exists...

**Comment by Gousia-MSFT** [comment]
The fix for this issue has been released but it is going to take some time to reach the public builds. Thanks!

**Comment by rmebjesus** [comment]
I have macOS Catalina Version 10.15.5 with Microsoft Teams Version 1.3.00.15561 installed and I still get this very same issue. It's really annoying and a detriment to the experience 😞.

**Comment by rmebjesus** [comment]
> The fix for this issue has been released but it is going to take some time to reach the public builds. Thanks!

In which build is the issue fixed?

**Comment by markgammon** [comment]
Still have the issue a couple weeks now since the update that a fix was released. It would be nice to know which build has the fix.

**Comment by jennasalau** [comment]
It's fixed on mine and clicking about I get the message `You have Microsoft Teams Version 1.3.00.15561. It was last updated on 13/07/2020.`

However, fixed is a loose term. It still appears blank for a few seconds then the message shows. I have no idea why they don't use native notifications ¯\_(ツ)_/¯ .... I know what it's doing, it's trying to fire up a browser instance in the background to show the message, ridiculous.

**Comment by noizo** [comment]
I'm on macOS Catalina 10.15.5 with Microsoft Teams Version 1.3.00.15561 and issue is still here.
Like all others, blank notification freezes video calls and presentations.
Please switch to macos native notifications.

**Comment by brosiusad** [comment]
Me too. macOS Catalina. Teams version 1.3.00.18164

**Comment by rominronin** [comment]
Any update on when this fix might be released? Thanks

**Comment by yacobwood** [comment]
Still an issue for me and has been for months. REALLY annoying having to nudge the mouse to reactivate the video call everytime a notification comes in

**Comment by rmebjesus** [comment]
Starting to doubt that anyone from the development is reading these comments as the issue status is Closed.

**Comment by AndyBehr** [comment]
yes, it is very upsetting. The issue is still here. For months and months now.

**Comment by Wajeed-msft** [comment]
Checking latest status on this. 

This issue is closed because this issue list is for [Microsoft Teams App development](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/building-an-app), product support channels are listed [here](https://docs.microsoft.com/en-us/microsoftteams/platform/feedback#product-support-channels). However, we have raised bug internally to Product team for tracking purpose.

**Comment by rmebjesus** [comment]
> Checking latest status on this.
> 
> This issue is closed because this issue list is for [Microsoft Teams App development](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/building-an-app), product support channels are listed [here](https://docs.microsoft.com/en-us/microsoftteams/platform/feedback#product-support-channels). However, we have raised bug internally to Product team for tracking purpose.

Thanks, deeply appreciated. 
When can we expect to have some feedback from the Product team regarding a fix?

**Comment by Wajeed-msft** [comment]
Could you please share your Desktop app version?

**Comment by rmebjesus** [comment]
Microsoft Teams Version 1.3.00.18164 running on macOS Catalina Version 10.15.6 (19G73).

**Comment by Wajeed-msft** [comment]
The fix has not reached general ring yet for Mac desktop. I am checking with desktop team on this.

**Comment by BrandonMathis** [comment]
Any plans to support OSXs built-in notification API? Currently Teams does not respect "Do Not Disturb" mode on my OS and notifications will pop up even though I am in DnD mode. This is a pretty big security issue because private chats will pop-up on my desktop potentially when I am screen-sharing with a client or presenting in from of an audience.

**Comment by hooper303** [comment]
Hard to believe this is still an issue.... 6 months later.

**Comment by manuros** [comment]
7 month later still....

You have Microsoft Teams Version 1.3.00.18164. It was last updated on 9/30/20.

**Comment by mash1t** [comment]
@Wajeed-msft have you already received feedback from the the desktop team?

**Comment by yacobwood** [comment]
Yeah still an issue for me too. So painful that its still an issue for this long!

**Comment by Trinetra-MSFT** [comment]
The fix has reached the public ring/R4 too. If you still see this issue please update your Teams desktop client

**Comment by vandenbergrobin** [comment]
@Trinetra-MSFT 

> You have Microsoft Teams Version 1.3.00.18164. It was last updated on 05/10/2020. 

Issue still present. Please advise on exact version number this will be available on.

**Comment by erwinc1** [comment]
Same issue on MacOS Big Sur 11.0 beta (20A5384c)

**Comment by Trinetra-MSFT** [comment]
We made a fix for macOS Catalina 10.15 meanwhile Could you please confirm what you are seeing "white" toasts or blank "purple" toasts?

**Comment by cnhx** [comment]
Having the same issue. I can only see blank purple toasts and avatars for all notifications.

**Comment by AndyBehr** [comment]
Same, the toast is now purple instead of just blank. sometimes it is half purple half white.

**Comment by vandenbergrobin** [comment]
I still get blank notifications, and it still freezes my video calls until I move my mouse over the video call window.

**Comment by simonc101** [comment]
I get blank toasts on the latest version of teams and running BigSur

**Comment by joebutnotexotic** [comment]
macOS Big Sur Beta here and getting blank purple toast notifications.  Teams version 1.3.00.26266

**Comment by Trinetra-MSFT** [comment]
Could you please do an update to latest OS (I believe Beta 10) and Teams version and and let us know if issue is still there?

**Comment by simonc101** [comment]
I am already on Beta 10 and still getting the issue

**Comment by ushaikh648** [comment]
Issue has been observed on Big Sur Beta 11 as well. @Trinetra-MSFT Any updates

**Comment by matthieugd** [comment]
Same problem Big Sur Beta 11  / Teams 1.3.00.24758

**Comment by gscott** [comment]
@Trinetra-MSFT  Blank toasts with Avatars is observed on Teams native client on Mac OS Big Sur Beta 11, Teams 1.3.00.26266.

**Comment by owellsjr** [comment]
Just wanted to add that this has been going on for **months** now. First on macOS Catalina and now on Big Sur. Notifications are just blank purple boxes. I'm running macOS Big Sur 11.0 Beta (20A5395g) and MS Teams 1.300.26266.

**Comment by ggsperring** [comment]
Also on macOS Big Sur 11.0 Beta (20A5395g) and MS Teams 1.300.26266 on MBP 16" same issues with notifications and document rendering with Teams windows.

**Comment by gscott** [comment]
This issue resolved for me with 1.3.00.28778 which installed today, 28 October.

**Comment by Trinetra-MSFT** [comment]
Can anyone confirm if this issue still persist for them?

**Comment by ggsperring** [comment]
How do I force Teams to update to the latest version 1.3.00.28778 - still on 1.300.26266 - used the Check for Updates function but no new version?

**Comment by joebutnotexotic** [comment]
I can confirm updating to 1.3.00.28778 (on Big Sur Beta 11) fixes the toast notifications.  This can only be done in developer preview right now.  You can enable Developer Preview in Office 365 Admin portal and then in Teams go to Profile (icon)>About>Developer Preview.  Once Teams restarts, it will update.

**Comment by stefanorainieri** [comment]
I'm on a MacBook Pro (15-inch, 2018) running MacOs Catalina 10.15.7 with Microsoft Teams Version 1.3.00.28778.
Still have the problem of a blank MS Teams notification window. This is annoying because I can't switch to the app using cmd+tab.
Any solution, please?

**Comment by Abhijit-MSFT** [comment]
@stefanorainieri, can you please try developer preview and let me know if issue still persists.

**Comment by stefanorainieri** [comment]
Hi @Abhijit-MSFT, issue still there.

**Comment by owellsjr** [comment]
This issue has been resolved for me in 1.3.00.28778. I don't have access to the developer preview so this must be the production release that installed automatically.

**Comment by Trinetra-MSFT** [comment]
The fix has been deployed to GA , Please feel free to reopen if you still have this issue.

**Comment by tudorPersonal** [comment]
Issue is still around with Catalina 15.6 and teams version 1.3.00.28778

**Comment by stefanorainieri** [comment]
Exactly the same for me as for @tudorPersonal

**Comment by imitov** [comment]
> I'm on a MacBook Pro (15-inch, 2018) running MacOs Catalina 10.15.7 with Microsoft Teams Version 1.3.00.28778.
> Still have the problem of a blank MS Teams notification window. This is annoying because I can't switch to the app using cmd+tab.
> Any solution, please?

Hi, for me the solution is to assign the MS Teams to all desktops (right click on the icon -> options -> assign to...). After that I'm able to use cmd+tab to switch directly to chat window, instead of the blank one.

HTH.

**Comment by stefanorainieri** [comment]
> > I'm on a MacBook Pro (15-inch, 2018) running MacOs Catalina 10.15.7 with Microsoft Teams Version 1.3.00.28778.
> > Still have the problem of a blank MS Teams notification window. This is annoying because I can't switch to the app using cmd+tab.
> > Any solution, please?
> 
> Hi, for me the solution is to assign the MS Teams to all desktops (right click on the icon -> options -> assign to...). After that I'm able to use cmd+tab to switch directly to chat window, instead of the blank one.
> 
> HTH.

Hi @imitov 
Thanks a lot for you workaround. It works also for me.
Even if it's not the best for my usual "workspace".. but probably it's only me by being obsessed in having one defined desktop for each app.
At the end, anyway , it's strange to have an blank window in MS Teams.. I hope they will fix it.
Thank you

**Comment by tudorPersonal** [comment]
> > I'm on a MacBook Pro (15-inch, 2018) running MacOs Catalina 10.15.7 with Microsoft Teams Version 1.3.00.28778.
> > Still have the problem of a blank MS Teams notification window. This is annoying because I can't switch to the app using cmd+tab.
> > Any solution, please?
> 
> Hi, for me the solution is to assign the MS Teams to all desktops (right click on the icon -> options -> assign to...). After that I'm able to use cmd+tab to switch directly to chat window, instead of the blank one.
> 
> HTH.

Unfortunately for me, it did not work. Happy that it is a solution to you and others.

**Comment by Trinetra-MSFT** [comment]
@stefanorainieri : Let me check this with team for Catalina 15.6 and teams version 1.3.00.28778. I will get back to you in sometime

**Comment by stefanorainieri** [comment]
> @stefanorainieri : Let me check this with team for Catalina 15.6 and teams version 1.3.00.28778. I will get back to you in sometime

Hi, my MS Teams Version is now  1.3.00.30874 (previously it was 1.3.00.28778).
Now the issue seems solved. 

I think there was an update yesterday, because today I can see some UI changes, more specifically call buttons changed.

Thanks to all!

**Comment by tudorPersonal** [comment]
Sorry, but it still does not work. Once a notification comes, the notification window always takes precedence - on a Mac.

**Comment by stefanorainieri** [comment]
> Sorry, but it still does not work. Once a notification comes, the notification window always takes precedence - on a Mac.

You are right, it's not working AGAIN also for me... :'(
