### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by gregmilligan** [MicrosoftDocs/msteams-docs#1504]
The "here" link at the bottom of the first section is broken.  Here's the URL:  https://education.microsoft.com/courses-and-resources/resources/microsoft-teams-moodle  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 685f497e-473f-7767-3f4e-5a0d1271a2ec
* Version Independent ID: 79dc20db-c743-8150-a660-abd9ffb03b4d
* Content: [Installing the Moodle integration with Microsoft Teams - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/moodleinstructions)
* Content Source: [msteams-platform/MoodleInstructions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/MoodleInstructions.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by laujan** [comment]
Hi @gregmilligan! The broken hyperlink in the Moodle instructions article has been updated. Thank you, again.
