### ISSUE TITLE
Bots section missing calling bot fields

### ISSUE THREAD

**Issue by clearab** [MicrosoftDocs/msteams-docs#1506]
The parameters necessary to enable a calling/meeting bot aren't documented here, but I'm fairly certain the should be. The two values needed are listed here: https://docs.microsoft.com/en-us/microsoftteams/platform/bots/calls-and-meetings/registering-calling-bot

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b449c9ba-a94c-4012-4721-cee5f87eeb8a
* Version Independent ID: b2536bbc-eb27-547d-d7f5-bab3ded3bedf
* Content: [Developer Preview Manifest schema reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema-dev-preview#bots)
* Content Source: [msteams-platform/resources/schema/manifest-schema-dev-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/resources/schema/manifest-schema-dev-preview.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Nivedipa-MSFT** [comment]
@clearab - Thanks for reporting your issue. We will check this and update the document accordingly.
