### ISSUE TITLE
Configuring Outgoing webhooks programmatically and receiving messages without @mention the outgoing webhook

### ISSUE THREAD

**Issue by EnviteDev** [MicrosoftDocs/msteams-docs#1508]
Is there any option to configure the outgoing webhook programmatically through REST API or Client SDK ? It will ease our work as it does not need user intervention as well User does not need to @mention the outgoing webhook every time to send the message.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb9c5bd5-1ac6-dcc8-4ed6-d6aad2432776
* Version Independent ID: 43e90995-bba4-86b6-1f1c-ab749e546a4b
* Content: [Add custom bots to Microsoft Teams with outgoing webhooks - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-outgoing-webhook#feedback)
* Content Source: [msteams-platform/webhooks-and-connectors/how-to/add-outgoing-webhook.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/webhooks-and-connectors/how-to/add-outgoing-webhook.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **laujan**

**Comment by Gousia-MSFT** [comment]
@EnviteDev Outgoing webhooks work similar to bots and requires an @mention to listen to the user. Currently the only way to setup an outgoing webhook is from the Teams client as documented [here](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-outgoing-webhook#create-an-outgoing-webhook).

**Comment by Trinetra-MSFT** [comment]
Please feel free to reopen the issue if you have further query

**Comment by beth-panx** [comment]
@Gousia-MSFT is this on the road map? Would be great to have webhooks configured as part of creation of a Teams team via graph api.

**Comment by EnviteDev** [comment]
@Gousia-MSFT Can you please let us know if there is plan for this webhooks in your roadmap? Appreciate if you can shed some light on this. This can simplify complexity of our applications.
