### ISSUE TITLE
CPU / RAM issue

### ISSUE THREAD

**Issue by Farcry69** [MicrosoftDocs/msteams-docs#1509]
Hello,

I have a massive issue here with Microsoft Teams. It goes crazy and take ALL my ram and ALL my CPU at least once a day.

I have a i7 8700k 4.8Ghz and 32Go of RAM.

I don't know more about the issue. Microsoft Teams was idle in the background while I was playing a game. And it crashed my PC in a second.

I tried to take a screenshot of it, but it was full lagging so I don't have everything on the screenshot, because it was taking 32Go of RAM and not 12. Also the CPU was waving between 80 and 100%.

![ram](https://user-images.githubusercontent.com/1372014/78223996-10103400-74c8-11ea-9c65-46477f441ab7.png)

As you can see there is multiple Microsoft Teams, but I launched only a single instance.
It takes an average of 10 hours for it to get crazy, it's random. But when it starts to get crazy, it takes 100% resources in a second.

I stay available if you need more informations.

Best regards,

Vincent

**Comment by Gousia-MSFT** [comment]
@Farcry69 Thanks for reaching out to us. We are looking into this.

**Comment by Gousia-MSFT** [comment]
@Farcry69 Please use the report a problem feature under "Help" to report this issue.
![image](https://user-images.githubusercontent.com/45553518/79098421-8d1c9280-7d7f-11ea-93de-84c52454d004.png)
