### ISSUE TITLE
[LOC]Inappropriate japanese "C のクイックスタート#"→"C# のクイックスタート"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/msteams-docs#1514]
ja-jp:https://docs.microsoft.com/ja-jp/microsoftteams/platform/messaging-extensions/what-are-messaging-extensions

![what-are-messaging-extensions_j](https://user-images.githubusercontent.com/40815708/78324661-40cb9880-75b0-11ea-8d66-40064d8186f4.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7fd5f91c-206f-f03c-d82e-3bf1cc81d13e
* Version Independent ID: d5c2d24a-def4-af2e-7983-c73cf7f22934
* Content: [What are messaging extensions? - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/what-are-messaging-extensions)
* Content Source: [msteams-platform/messaging-extensions/what-are-messaging-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/messaging-extensions/what-are-messaging-extensions.md)
* Product: **msteams**
* GitHub Login: @clearab
* Microsoft Alias: **anclear**

**Comment by laujan** [comment]
Hi @hyoshioka0128! Thank you for raising this issue. The above referenced article has been updated.  Thanks again!
