### ISSUE TITLE
Deep link to Voicemail Tab.

### ISSUE THREAD

**Issue by danswiser** [MicrosoftDocs/msteams-docs#1515]
Is it possible to link to the Voicemail tab where users can view their voicemails?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45541337-ecd7-5cf6-cbe4-3f0d2f39aa79
* Version Independent ID: 6b4203f0-2844-06c9-eaa3-9cc03e6f76c0
* Content: [Create deep links - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links#feedback)
* Content Source: [msteams-platform/concepts/build-and-test/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/build-and-test/deep-links.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Subhasish-msft** [comment]
@dan-wesley ,
Currently deep link to Voicemail tab is not implemented. You can deep link to App's tab.

**Comment by dan-wesley** [comment]
@Subhasish-msft you got the wrong dan I think @danswiser

**Comment by Subhasish-msft** [comment]
I am really sorry. Thanks for the correct tag.
