### ISSUE TITLE
Link is wrong

### ISSUE THREAD

**Issue by tk-contexxtai** [MicrosoftDocs/msteams-docs#1520]
Hey, 
the link to "this form" does not target to a working form....

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75dcbc89-3e4e-6ccc-aab0-49debb445e7c
* Version Independent ID: afd117d9-e02e-fa13-a858-9f6bafb61d1f
* Content: [App Certification - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/post-publish/application-certification#feedback)
* Content Source: [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/application-certification.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/deploy-and-publish/appsource/post-publish/application-certification.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by LGerrard** [comment]
Thank you for bringing this to our attention. The link has been fixed.
