### ISSUE TITLE
Mentions or notifications for Connector Messages

### ISSUE THREAD

**Issue by tmpkn** [MicrosoftDocs/msteams-docs#1521]
Is there a way to @mention individuals / channels / teams from a Connector message? It's not documented anywhere, and when I use the "at" + "team name" it's simply displayed as a text (doesn't trigger notification).

We use Connectors for high priority messages and right now have to rely on end users manually changing their channel configuration to notify them of all messages.

**Comment by Trinetra-MSFT** [comment]
@tmpkn , @mention in webhook is not supported, This feature is under review Please take a look at [UserVoice](https://microsoftteams.uservoice.com/forums/555103-public/suggestions/32313991-allow-webhooks-extensions-to-mention-individuals)
