### ISSUE TITLE
Broken link in first video

### ISSUE THREAD

**Issue by gregmilligan** [MicrosoftDocs/msteams-docs#1522]
The first video tells customers to go to https://aka.ms/TeamsMoodle, but that sends them to https://education.microsoft.com/en-us/courses-and-resources/resources/microsoft-teams-moodle, which is a broken page.  Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 685f497e-473f-7767-3f4e-5a0d1271a2ec
* Version Independent ID: 79dc20db-c743-8150-a660-abd9ffb03b4d
* Content: [Installing the Moodle integration with Microsoft Teams - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/moodleinstructions)
* Content Source: [msteams-platform/MoodleInstructions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/MoodleInstructions.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by gregmilligan** [comment]
Whoops - just realized I already reported this bug.  Sorry for the duplicate...

**Comment by Gousia-MSFT** [comment]
Closing this as this is duplicate.
