### ISSUE TITLE
Skype support?

### ISSUE THREAD

**Issue by mauricio208** [MicrosoftDocs/msteams-docs#1525]
If I understand correctly when creating a bot with Azure Subscription if I add on "Supported account types" Skype, then the bot will work also for people writing to it from Skype?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e52a9fa-a482-2929-c462-47da5e8b38d1
* Version Independent ID: ce956c12-2916-9d6c-4fbb-5d07556378bc
* Content: [Create a bot for Microsoft Teams - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/create-a-bot-for-teams#feedback)
* Content Source: [msteams-platform/bots/how-to/create-a-bot-for-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/bots/how-to/create-a-bot-for-teams.md)
* Product: **msteams**
* GitHub Login: @clearab
* Microsoft Alias: **anclear**

**Comment by Abhijit-MSFT** [comment]
@mauricio208, Yes bot will work for Skype as well.
