### ISSUE TITLE
Vague @ mentions in adaptive cards guidance

### ISSUE THREAD

**Issue by vbvbvbv** [MicrosoftDocs/msteams-docs#1526]
Hi all, there's no explanation how to get Teams User ID required for Flow adaptive cards mentions - in https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-format.md

Also, not clear how to make this for multiple users at once , for example.

**Comment by Trinetra-MSFT** [comment]
@vbvbvbv , Currently @Mention within cards is in developer preview. But However you can @mention user in Adaptive Card following way:
Adaptive card json for @mention user:
```
{
  "type": "AdaptiveCard",
  "body": [
    {
      "type": "TextBlock",
      "size": "Medium",
      "weight": "Bolder",
      "text": "Hi <at>TestUser</at> This is new feature in Adaptive Card version 1.2 Please test..."
    }
  ],
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "version": "1.0",
  "channelId": {
    "entities": [
      {
        "type": "mention",
        "text": "<at>TestUser</at>",
        "mentioned": {
          "id": "29:124124124124",
          "name": "TestUser"
        }
      }
    ]
  }
} 
```
![image](https://user-images.githubusercontent.com/50989436/79092909-0dd39280-7d70-11ea-8ef7-7757def3f9fd.png)

You can get the channel Id and other required parameters from Activity Object.

**Comment by vbvbvbv** [comment]
@Trinetra-MSFT Thanks for your reply, this is valid for Bot Builder, while for example using Power Automate Flows which post adaptive cards via MS Teams doesn't get you ability to get these values easily and having simplified way of using <at> mentions would be more beneficial. 

I managed to find a workaround by using OrgID in this format instead , which works fine on desktop version of Teama but possibly creates glitches in adaptive card rendering on mobile version of Teams :
  "id": "8:org:{ordID-of-user}

If there any way of obtaining that "29:" value outside of Bot Builder, via Graphy query for example etc?

**Comment by Trinetra-MSFT** [comment]
@vbvbvbv , This Id can be fetch through only Activity Object. There is no Graph API to get this

**Comment by Trinetra-MSFT** [comment]
Please feel free to reopen if you have further query
