### ISSUE TITLE
Not all sounds are outputted through the selected speaker

### ISSUE THREAD

**Issue by GabrielSandor** [MicrosoftDocs/msteams-docs#1530]
When i set a speaker in Devices settings (custom setup) that is not the same as the default speaker in Windows, some sounds such as the call ring are not outputted through the selected speaker but through the default one.

**Comment by Abhijit-MSFT** [comment]
@GabrielSandor, Is this query related to MS Teams? If yes, can you please provide more details on your query.

**Comment by GabrielSandor** [comment]
@Abhijit-MSFT yes, it's related to MS Teams desktop, version 1.3.00.4461. What kind of details do you need?

**Comment by Abhijit-MSFT** [comment]
@GabrielSandor, Call ring is set to default speaker. Did you observe any other sound coming from default speaker even though speaker settings are changes?

**Comment by GabrielSandor** [comment]
@Abhijit-MSFT i expected all sounds in MS Teams to be outputted to the selected speaker in the Device settings, not just the voice in the calls. Is this by design, then?

**Comment by Abhijit-MSFT** [comment]
@GabrielSandor, missed to respond you. Did you try the secondary ringer option. In my testing i found all the sounds coming from my headphone. please try it once.

**Comment by GabrielSandor** [comment]
@Abhijit-MSFT i tried that and now the ringer is not outputted through neither of the speakers.
