### ISSUE TITLE
Link broken

### ISSUE THREAD

**Issue by edireson** [MicrosoftDocs/msteams-docs#1533]
The link under Further Reading, third bullet point, "Microsoft Graph permissions for calls and online meetings bots" is a 404 Not Found.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a05d4dc-11a1-f548-15bd-8767de4d16b2
* Version Independent ID: 3a17e6f9-93c4-949b-d8a7-f2e41059ba79
* Content: [Calls and Online Meetings Bots - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/calls-and-meetings/calls-meetings-bots-overview?view=msteams-client-js-latest#feedback)
* Content Source: [msteams-platform/bots/calls-and-meetings/calls-meetings-bots-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/bots/calls-and-meetings/calls-meetings-bots-overview.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by laujan** [comment]
Hi @edireson. The broken link in the **Calls and online meetings bots** article has been fixed. Thank you again for bringing the issue to our attention!
