### ISSUE TITLE
Links to botframework doesn't work

### ISSUE THREAD

**Issue by jackygeee** [MicrosoftDocs/msteams-docs#1534]
Hey guys,

these two links doesn't seem to work:
https://dev.botframework.com/bots
https://dev.botframework.com/bots/new

**Comment by Abhijit-MSFT** [comment]
@jackygeee, Both the links work fine for me. Is there any error that you encountered?. 
You can create new bot in [Azure Portal](https://ms.portal.azure.com/) directly in case these two url's doesn't work for you.

**Comment by jackygeee** [comment]
@Abhijit-MSFT oh yeah probably a browser issue - my fault.
Thanks for your help!
