### ISSUE TITLE
misleading description about the user consent procedure

### ISSUE THREAD

**Issue by jzbuaa** [MicrosoftDocs/msteams-docs#1535]
"When you call getAuthToken - and additional user consent is required (for user-level permissions) - we will show a dialog to the user encouraging them to grant additional consent."

this is misleading as it suggests that the user consent dialog will be shown by Teams, but the fact is that developers have to do the work themselves, just as the great demo project "Task Meow" shows.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52221dd3-95ec-96b9-1da8-9478527c2602
* Version Independent ID: 32e9c2d8-733d-0865-2ea3-727d8684a10d
* Content: [Single Sign-On - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-aad-sso)
* Content Source: [msteams-platform/tabs/how-to/authentication/auth-aad-sso.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tabs/how-to/authentication/auth-aad-sso.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Subhasish-msft** [comment]
The additional consent dialog is displayed when the app required additional permission. It will be displayed by microsoft authetication dialog. User need not do that manually.

![image](https://user-images.githubusercontent.com/56869764/79211397-d514e580-7e63-11ea-8c82-8c6b87533af7.png)
