### ISSUE TITLE
How to force "Add to a Team" when installing app

### ISSUE THREAD

**Issue by matula** [MicrosoftDocs/msteams-docs#1536]
I've seen some apps that have a single "Add to a Team" button on install, instead of just "Add" with "Add to a Team" in a dropdown. What part of the manifest needs to be updated to have this happen?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f94a488-d636-92b3-21eb-c88744c8f272
* Version Independent ID: 7b3413f4-9ade-accf-5cb2-83fead11a32a
* Content: [Manifest schema reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema)
* Content Source: [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/resources/schema/manifest-schema.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by matula** [comment]
For reference, this is what I'm currently using. Thanks in advance.
```
{
  "$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.5/MicrosoftTeams.schema.json",
  "manifestVersion": "1.5",
  "version": "1.0.0",
  "id": "{appid}",
  "packageName": "{package}",
  "developer": {
    "name": "Developer",
    "websiteUrl": "https://example.com",
    "privacyUrl": "https://example.com",
    "termsOfUseUrl": "https://example.com"
  },
  "icons": {
    "color": "color.png",
    "outline": "outline.png"
  },
  "name": {
    "short": "App name short",
    "full": "app name full"
  },
  "description": {
        "short": "short desc",
        "full": "full desc"
    },
  "accentColor": "#3C2667",
  "bots": [
    {
      "botId": "{botid}",
      "scopes": [
        "personal",
        "team"
      ],
      "commandLists": [
        {
          "scopes": [
            "personal"
          ],
          "commands": [
            {
              "title": "help",
              "description": "Help"
            }
          ]
        }
      ],
      "supportsFiles": true,
      "isNotificationOnly": false
    }
  ],
  "composeExtensions": [
    {
      "botId": "{botid}",
      "canUpdateConfiguration": false,
      "commands": [
        {
          "id": "options",
          "type": "action",
          "title": "title",
          "description": "description",
          "initialRun": true,
          "fetchTask": true,
          "context": [
            "compose"
          ]
        }
      ]
    }
  ],
  "permissions": [
    "identity",
    "messageTeamMembers"
  ],
  "validDomains": [
    "{baseurl}"
  ]
}
```

**Comment by Trinetra-MSFT** [comment]
@matula , If you want to add your bot to team specific only, you need to update the scope to Team only in bot scope & remove compose extension part because compose extension have default scope as personal. Please see the attached screenshot:
![image](https://user-images.githubusercontent.com/50989436/79205228-4603cf80-7e5b-11ea-8667-4dfbd9e3f1df.png)

**Comment by Trinetra-MSFT** [comment]
Please feel free to open if you have any further queries
