### ISSUE TITLE
Using Deep Links with Action.OpenUrl within a bot message

### ISSUE THREAD

**Issue by Manish-Ghumnani** [MicrosoftDocs/msteams-docs#1539]
There is no way to identify a user who clicked on the Card Action which navigates to the tab. For a deep link shown in a bot message in a group/team.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45541337-ecd7-5cf6-cbe4-3f0d2f39aa79
* Version Independent ID: 6b4203f0-2844-06c9-eaa3-9cc03e6f76c0
* Content: [Create deep links - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links)
* Content Source: [msteams-platform/concepts/build-and-test/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/build-and-test/deep-links.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Trinetra-MSFT** [comment]
@Manish-Ghumnani , I think you can get the userInfo from the [tab context](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/access-teams-context) or [bot context](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bots-context).

**Comment by Manish-Ghumnani** [comment]
yeah but that is only for personal tabs, how to access the tab context for a team tab?

**Comment by Trinetra-MSFT** [comment]
@Manish-Ghumnani , When invoked, the [microsoftTeams.getContext((context) => {}) ](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/configuration-page#use-the-getcontext-function-to-retrieve-context)function retrieves the Context interface. You can add this function to your configuration page to retrieve context values:

**Comment by Trinetra-MSFT** [comment]
Please feel free to reopen, if you have further query
