### ISSUE TITLE
Bullet Point stays when removing infront of code snippet

### ISSUE THREAD

**Issue by Alexees** [MicrosoftDocs/msteams-docs#1541]
I use bullet points quite often as a tool for listing text. Just now I had the following issue:
Within my first bullet point, I added a code snipped and pressed enter, so I would get the followup bullet. I then decided to remove it. The first backspace did nothing. It only got rid of the caret. Pressing backspace a second time removed the code snippet and let the caret appear at the end of the first bullet. The second bullet was still there.
The same goes for pressing delete before the code snippet. first press removed the caret, the second removes the code snippet.
Every bullet in front of the snippet is ignored. Instead of removing a bullet pointed code snippet, only the snippet gets removed.

**Comment by Subhasish-msft** [comment]
@Alexees , Thank you for reporting this issue, I have shared this info with engineering team.
