### ISSUE TITLE
Phone number not showing in contact card until after re-login

### ISSUE THREAD

**Issue by GabrielSandor** [MicrosoftDocs/msteams-docs#1542]
Whenever a colleague has their phone number set in their Teams contact card, i can't see it unless i logout and login again. I believe the phone number comes from Active Directory. This looks like a synchronization issue in Teams.

**Comment by GabrielSandor** [comment]
This is probably related to https://github.com/MicrosoftDocs/msteams-docs/issues/1527.

**Comment by Subhasish-msft** [comment]
@GabrielSandor, Thanks for reporting it. We have forwarded your feedback to the dev team.
