### ISSUE TITLE
Channel disappearing

### ISSUE THREAD

**Issue by KenticoMartinS** [MicrosoftDocs/msteams-docs#1543]
Hi,
we are experiencing problems with disappearing channels. We have created a channel and when a user opens its link in a browser or re-login on his device, the channel disappears.

When he/she clicks on the link he gets the following messages: "We can't find that channel due to connectivity issues. Please try again later."

**Comment by Gousia-MSFT** [comment]
@KenticoMartinS Thanks for reporting this. We have forwarded this to the right folks who are looking into it. Will get back to you if we need any further information.

**Comment by cesarhoeflich** [comment]
I found a relationship with the browser language in Teams Web. When opened in PT-BR, all channels are visible, in EN-US some channels disappear.

**Comment by Gousia-MSFT** [comment]
@KenticoMartinS It appears that we have a livesite incident we are investigating that would explain what you are seeing. Meanwhile, could you please use the "Report a problem" feature under Help to report this:
![image](https://user-images.githubusercontent.com/45553518/79536183-0c220b80-809d-11ea-891e-e5d26a1b5077.png)

**Comment by KenticoMartinS** [comment]
Hi @Gousia-MSFT,
I'd love to report this issue, but unfortunately, I don't have that option for some reason.
![image](https://user-images.githubusercontent.com/17612117/79547293-fa883600-8093-11ea-8e93-fdac17c0a7db.png)

**Comment by Gousia-MSFT** [comment]
@KenticoMartinS This is fixed now. Please check and re-open if you are still facing the issue.
