### ISSUE TITLE
Validation Policies page click thru broken

### ISSUE THREAD

**Issue by neel-hektor** [MicrosoftDocs/msteams-docs#1544]
"Validation policies: It must pass all current AppSource validation policies for Teams tabs and bots. Please note that these policies are subject to change."

the click thru for "AppSource validation policies " redirects to https://dev.office.com/officestore/docs/validation-policies which gives "IP address could not be found error"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3df9a819-4eb0-e650-ef6b-5eeaa265c317
* Version Independent ID: ed71ed64-970d-7820-4229-c1e6896a8896
* Content: [Submission checklist - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist#feedback)
* Content Source: [msteams-platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by laujan** [comment]
Hi @neel-hektor. The broken link in the **Prepare for AppSource submission* article has been fixed. Thank you again for bringing the issue to our attention!
