### ISSUE TITLE
Post a message to the webhook using cURL

### ISSUE THREAD

**Issue by camil-o** [MicrosoftDocs/msteams-docs#1546]
The example given there does not work.
```
curl -H 'Content-Type: application/json' -d '{\"text\": \"Hello World\"}' &lt;YOUR WEBHOOK URL&gt;
```
It should be update to something like this:
```
curl -H 'Content-Type: application/json' -d '{"@context": "http://schema.org/extensions","@type": "MessageCard", "text": "Hello World"}' &lt;YOUR WEBHOOK URL&gt;
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28316a67-22fa-8a05-1ae0-fbe1c5720ef9
* Version Independent ID: 8a250e46-2a30-af86-839d-9f83a8b48041
* Content: [Sending messages to Connectors and Webhooks - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-using#feedback)
* Content Source: [msteams-platform/webhooks-and-connectors/how-to/connectors-using.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/webhooks-and-connectors/how-to/connectors-using.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by apoorvanand** [comment]
Same issues observed by trying out ths example.

**Comment by boseabhishek** [comment]
Try formatting the json without the slashes and it works! I have also put the payload with -d at the end.

**Comment by Trinetra-MSFT** [comment]
Please feel free to reopen if you have further query

**Comment by Jon889** [comment]
The documentation needs to be changed to remove the escaping slashes from the payload.

**Comment by omatron** [comment]
This fixes the issue: https://github.com/MicrosoftDocs/msteams-docs/issues/1649
----
In this documentation: https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-using#post-a-message-to-the-webhook-using-curl

// on macOS or Linux
`curl -H 'Content-Type: application/json' -d '{\"text\": \"Hello World\"}' <YOUR WEBHOOK URL>`

This returns:
Bad payload received by generic incoming webhook.

**The correct command is:**
`curl -H 'Content-Type: application/json' -d '{"text": "Hello World"}' <YOUR WEBHOOK URL>`
without the backslashes `\`

This returns:
1
