### ISSUE TITLE
images broken

### ISSUE THREAD

**Issue by xamde** [MicrosoftDocs/msteams-docs#1549]
The images under "Mobile and desktop differences for connector cards using HTML" are broken

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 001a12ea-30fa-d626-18a9-02a518bfb37f
* Version Independent ID: e5f5f69e-66e9-d1b2-e19a-485d0ffcd6fa
* Content: [Text formatting in cards - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?tabs=connector-md%2Cconnector-html#feedback)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-format.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-format.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by laujan** [comment]
Hi @xamde. The broken links in the **Format cards in Teams** article have been repaired. Thank you again for bringing the issue to our attention!
