### ISSUE TITLE
Cannot choose download folder

### ISSUE THREAD

**Issue by GabrielSandor** [MicrosoftDocs/msteams-docs#1550]
Teams does not let you choose the download folder, and downloads everything in the default Windows download folder. It would be useful to have a setting that allows you to change it.

**Comment by Trinetra-MSFT** [comment]
@GabrielSandor , Thanks for pointing this. Yes currently teams download everything in default windows folder. Please raise a [UserVoice ](https://microsoftteams.uservoice.com/)for this.

**Comment by GabrielSandor** [comment]
@Trinetra-MSFT thanks for the suggestion, but i already see at least requests on UserVoice for this feature and they seem largely ignored:
https://microsoftteams.uservoice.com/forums/555103-public/suggestions/38432071-ability-to-download-to-a-folder-of-choice-instead
https://microsoftteams.uservoice.com/forums/908686-bug-reports/suggestions/40174198-can-t-change-download-folder
https://microsoftteams.uservoice.com/forums/599053-schools-and-universities/suggestions/20580028-change-download-destination
