### ISSUE TITLE
Unable to find Teams app "App Studio"

### ISSUE THREAD

**Issue by adhoke-ava** [MicrosoftDocs/msteams-docs#1554]
When I search in Teams, I get no results for an app named "App Studio." Refining the complete app list to "Developers and IT" does not contain any apps that seem even similar to App Studio.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f98c73d-bb68-3088-6e7d-2c576a8292f6
* Version Independent ID: 08b9df7d-4997-c681-e73a-235ec1e4fc7b
* Content: [Get started with C#/.NET - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tutorials/get-started-dotnet-app-studio#feedback)
* Content Source: [msteams-platform/tutorials/get-started-dotnet-app-studio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tutorials/get-started-dotnet-app-studio.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Gousia-MSFT** [comment]
@adhoke-ava Could you please try login to Office 365 admin center, in settings for Microsoft Teams. and turn on the option "Allow external apps in Microsoft Teams" and see if that helps?

**Comment by adhoke-ava** [comment]
@Gousia-MSFT this is for my company's tenant, not a development tenant. I don't have admin access. Do I need to sign up for the O365 developer program to get a test tenant?

**Comment by gravldo** [comment]
this is not working for me - i have a E3 account and have turned on external apps for teams

**Comment by Gousia-MSFT** [comment]
@adhoke-ava Yes, could you please check with the tenant admin to allow external apps?

**Comment by adhoke-ava** [comment]
@Gousia-MSFT I work for a company with 30,000+ employees. I don't think they're going to turn on external Teams apps just for me. I'm going to close this issue as it seems there's no other resolution. Feel free to reopen it if there are other options. I will be signing up for the O365 Developer Program and using that development tenant instead.
