### ISSUE TITLE
Webhook to a specific tab in Teams channel

### ISSUE THREAD

**Issue by jovelfer** [MicrosoftDocs/msteams-docs#1555]
Hi,

We have a specific tab in a channel (planner type), and we would like to post messages to this specific tab, to add new tasks to that planner tab..., is it possible with webhooks?, and if it is, how would yo do?

Thanks a lot in advance.

**Comment by Gousia-MSFT** [comment]
@jovelfer Webhooks are only built for channels. It is not possible to add a webhook to a tab.
