### ISSUE TITLE
Broken link to azure portal 

### ISSUE THREAD

**Issue by jChapman** [MicrosoftDocs/msteams-docs#1563]
https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/create-a-bot-for-teams#with-an-azure-subscription

Appears as 

![image](https://user-images.githubusercontent.com/1152464/79605719-6da6a200-80be-11ea-81b1-969eba60412a.png)

Appears to be included in from this md file: https://github.com/MicrosoftDocs/msteams-docs/blob/8989688ef25fc367f01a5b7af608e6ffe29752ec/msteams-platform/includes/bots/azure-bot-channels-registration.md

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e52a9fa-a482-2929-c462-47da5e8b38d1
* Version Independent ID: ce956c12-2916-9d6c-4fbb-5d07556378bc
* Content: [Create a bot for Microsoft Teams - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/create-a-bot-for-teams)
* Content Source: [msteams-platform/bots/how-to/create-a-bot-for-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/bots/how-to/create-a-bot-for-teams.md)
* Product: **msteams**
* GitHub Login: @clearab
* Microsoft Alias: **anclear**

**Comment by laujan** [comment]
Hi @jChapman. The broken link in the  **Create a bot for Microsoft Teams** article has been fixed. Thank you again for bringing the issue to our attention!
