### ISSUE TITLE
Per bot per thread limit table is confusing

### ISSUE THREAD

**Issue by cpjoshi** [MicrosoftDocs/msteams-docs#1567]
It's not clear why there are four limits for "Send to Conversation", "Get Conversation Members" etc.

e.g.
Get Conversation Members	1	14
Get Conversation Members	2	16
Get Conversation Members	30	120
Get Conversation Members	3600	3600

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a57254c9-963d-ea1d-ecaf-dd0e7913526c
* Version Independent ID: 610c8514-bd72-46cc-75f1-991e2242019b
* Content: [Rate limiting - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/rate-limit)
* Content Source: [msteams-platform/bots/how-to/rate-limit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/bots/how-to/rate-limit.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Subhasish-msft** [comment]
@cpjoshi , 

Multiple entries are for rate limit of that particular range of time.
For example in 1 sec, 14 API call can be made. where as in 2 secs, 16 is the limit, not 27 (2*14).

Hope it helps.

**Comment by cpjoshi** [comment]
Thank You.
