### ISSUE TITLE
Deep link to voice/video call

### ISSUE THREAD

**Issue by itoledo** [MicrosoftDocs/msteams-docs#1569]
Hi, is there any way to call a specific user/group of users? Like "click to call"?
Tried with this URL: https://teams.microsoft.com/l/call/0/0?attendees=demo@birdie.cl and it launches a new call on desktop, but with no attendees other than me. Tried a few iterations but it seems the functionality is there, just need the correct incantation/parameters. In mobile this URL just crashes the app.
Using "callto:demo@birdie.cl" doesn't seem to work on mobile but it shows a "Would you like to call demo@birdie.cl?" on Desktop.
Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45541337-ecd7-5cf6-cbe4-3f0d2f39aa79
* Version Independent ID: 6b4203f0-2844-06c9-eaa3-9cc03e6f76c0
* Content: [Create deep links - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links#feedback)
* Content Source: [msteams-platform/concepts/build-and-test/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/build-and-test/deep-links.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Subhasish-msft** [comment]
@itoledo , Deeplink to voice/video call is not supported in teams currently. You can deeplink to the scheduling dialogue and create meeting though.

**Comment by darbid** [comment]
Landed here from google after a long time clicking on deep link links.  I understand Teams will replace Skype For Business.  It would be a great idea that as skype:+1###### will call a number it would be a really great (expected) that the replacement can do it as well.
