### ISSUE TITLE
I am mostly concerned about security for outgoing webhook. 

### ISSUE THREAD

**Issue by kvmakanna** [MicrosoftDocs/msteams-docs#1570]
Can anyone with request trigger a notification? or can I setup security constraints when doing a request to my app?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb9c5bd5-1ac6-dcc8-4ed6-d6aad2432776
* Version Independent ID: 43e90995-bba4-86b6-1f1c-ab749e546a4b
* Content: [Add custom bots to Microsoft Teams with outgoing webhooks - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-outgoing-webhook#feedback)
* Content Source: [msteams-platform/webhooks-and-connectors/how-to/add-outgoing-webhook.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/webhooks-and-connectors/how-to/add-outgoing-webhook.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **laujan**

**Comment by kvmakanna** [comment]
I need to create a record in my application and only few users should have the ability to do so. And if I have multiple sandboxes that I am working on, how do I do that?

**Comment by Subhasish-msft** [comment]
@kvmakanna , Outgoing webhooks are visible to all members of the team just like a bot. So any team member can @mention and trigger the outgoing webhook. You can add a bot in that case. Inside bot code you can add logic to validate or restrict any request before making the api call.
