### ISSUE TITLE
Finding version of the app/manifest

### ISSUE THREAD

**Issue by ndileep** [MicrosoftDocs/msteams-docs#1572]
Even after we publish a new version of a bot, all users might not upgrade it immediately. When a bot service gets a request, how can the bot service find out which version of the manifest is being used by the user?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c780d605-b1b2-716f-5888-503608769b5a
* Version Independent ID: 53c724f8-d9a2-4af6-6d75-ddeaef084137
* Content: [Bot API Changes for Team/Chat Members (2020 update) - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/team-chat-member-api-changes)
* Content Source: [msteams-platform/resources/team-chat-member-api-changes.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/resources/team-chat-member-api-changes.md)
* Product: **msteams**
* GitHub Login: @ojasvichoudhary
* Microsoft Alias: **ojchoudh**

**Comment by Trinetra-MSFT** [comment]
@ndileep , You can get the name & installedApps for user by calling [List Teams Apps](https://docs.microsoft.com/en-us/graph/api/teamsappinstallation-list?view=graph-rest-1.0&tabs=http#example-2-get-the-names-and-other-details-of-installed-apps), graph API. The API returns manifest version which is currently running.

**Comment by davidlinhares** [comment]
In that case there needs to be an extra service for interacting with Graph API. I believe the question is how can we determine which bot version is being invoked when we receive a command/request?

**Comment by Trinetra-MSFT** [comment]
@davidlinhares , Yes  it requires an extra service for graph API. User is asking for the manifest version which is running for bot. This can not be fetched from Activity.

**Comment by Trinetra-MSFT** [comment]
Please feel free to reopen if you have further query
