### ISSUE TITLE
Application crashes when selecting video background

### ISSUE THREAD

**Issue by EZ-BZ** [MicrosoftDocs/msteams-docs#1573]
Application crashes and restarts after selecting a video background before joining a meeting.  This is consistently reproduced in Windows when using Teams versions higher than 1.3.00.3564 (works fine in this version).
[Teams_logs.txt](https://github.com/MicrosoftDocs/msteams-docs/files/4518718/Teams_logs.txt)

**Comment by Gousia-MSFT** [comment]
@EZ-BZ Thanks for reaching out to us. We are looking into this.

**Comment by Gousia-MSFT** [comment]
@EZ-BZ Could you please use the "Report a problem" feature under Help to report this issue to us. 
![image](https://user-images.githubusercontent.com/45553518/83373935-a50bac80-a3e7-11ea-8cc4-cc5c46b35065.png)
