### ISSUE TITLE
Teams returns to the Team List after minutes / hours of being AFK

### ISSUE THREAD

**Issue by SlimShadys** [MicrosoftDocs/msteams-docs#1575]
I usually records online lessons and they went pretty fine so far.
I noticed one thing tho, that after about 40m/1h of recording the screen, the application automatically goes into the Team List by itself. I don't press any button, it does it all by itself, reducing the owner's screen to the top left part of the screen.
And I manually need to re-size the screen back to full-screen in order to see the owner's stream properly.

Has anyone experienced the same issue?

Thank you

**Comment by Gousia-MSFT** [comment]
@SlimShadys Are you recording the screen while on a Teams call? Is this something you have seen frequently?

**Comment by SlimShadys** [comment]
@Gousia-MSFT Very frequently. And yes, I record the screen while on a Teams call.
I wonder if it's something related to the fact I don't touch any buttons for an amount of time since I'm paying attention to the lesson, and so that Teams has this weird behaviour automatically after this fixed amount of time.

**Comment by SlimShadys** [comment]
@Gousia-MSFT I have this problem also when not recording the screen.
This is the log. Bare in mind that the problem occurred at 09:24:31s.

> Thu Apr 30 2020 09:23:40 GMT+0200 (Ora legale dell’Europa centrale) <10836> -- info -- Machine has been idle for 149.469 seconds 
Thu Apr 30 2020 09:24:31 GMT+0200 (Ora legale dell’Europa centrale) <10836> -- info -- Blur main window 
Thu Apr 30 2020 09:24:31 GMT+0200 (Ora legale dell’Europa centrale) <10836> -- info -- Is foreground set to false 
Thu Apr 30 2020 09:24:31 GMT+0200 (Ora legale dell’Europa centrale) <10836> -- event -- duration: 201.9099998474121, name: desktop_foreground_duration, vdiMode: 0, eventpdclevel: 2,  
Thu Apr 30 2020 09:24:32 GMT+0200 (Ora legale dell’Europa centrale) <10836> -- event -- panelaction: Action.Outcome: launch, Action.Gesture: click, Action.Scenario: openTrayIconMenu, Action.ScenarioType: other, DataBag.StatusIndicatorState: OnThePhone, vdiMode: 0, eventpdclevel: 2,  
Thu Apr 30 2020 09:24:32 GMT+0200 (Ora legale dell’Europa centrale) <10836> -- info -- Setting the taskbar overlay icon - Al telefono 
Thu Apr 30 2020 09:24:32 GMT+0200 (Ora legale dell’Europa centrale) <10836> -- info -- Focusing main window 
Thu Apr 30 2020 09:24:32 GMT+0200 (Ora legale dell’Europa centrale) <10836> -- info -- Is foreground set to true 
Thu Apr 30 2020 09:24:34 GMT+0200 (Ora legale dell’Europa centrale) <10836> -- info -- Blur main window 
Thu Apr 30 2020 09:24:34 GMT+0200 (Ora legale dell’Europa centrale) <10836> -- info -- Is foreground set to false 
Thu Apr 30 2020 09:24:34 GMT+0200 (Ora legale dell’Europa centrale) <10836> -- event -- duration: 1.7650001049041748, name: desktop_foreground_duration, vdiMode: 0, eventpdclevel: 2,

**Comment by Gousia-MSFT** [comment]
@SlimShadys Thanks for sharing these details. I have forwarded the report to the right folks!
