### ISSUE TITLE
User consent flow on update needs better explanation, with screenshots

### ISSUE THREAD

**Issue by aosolis** [MicrosoftDocs/msteams-docs#1579]
Please document the UX for an upgrade the requires user consent, for both personal and team scope.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d29cfd09-9067-d939-960a-b33931707c4d
* Version Independent ID: 6c0b95fa-b5b4-5ace-15e7-55d2b007b792
* Content: [Post publishing - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/post-publish/overview#when-does-updating-your-app-trigger-the-user-consent-flow)
* Content Source: [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/deploy-and-publish/appsource/post-publish/overview.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Mahesh2516** [comment]
Screenshots added for user consent flow. Issue resolved.
