### ISSUE TITLE
Can't get past the "Create bot" step.

### ISSUE THREAD

**Issue by jdeagar** [MicrosoftDocs/msteams-docs#1580]
From App Studio when I attempt to invoke the create bot step of this tutorial my teams application shows a waiting spinner for a few seconds like it is trying to do something and then it goes away and nothing happens. I don't see any feedback or errors so I am at a loss as to what to troubleshoot. Any suggestions as to what the problem might be? I have tried starting over and still notsuccess.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f98c73d-bb68-3088-6e7d-2c576a8292f6
* Version Independent ID: 08b9df7d-4997-c681-e73a-235ec1e4fc7b
* Content: [Get started with C#/.NET - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tutorials/get-started-dotnet-app-studio#feedback)
* Content Source: [msteams-platform/tutorials/get-started-dotnet-app-studio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tutorials/get-started-dotnet-app-studio.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Subhasish-msft** [comment]
@jdeagar , Is it on teams desktop app or web application ?

**Comment by jdeagar** [comment]
Desktop app.

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by SamJarmanPP** [comment]
I've also got this (referred to [here](https://github.com/MicrosoftDocs/msteams-docs/issues/1590#issuecomment-620361758).. also macosx desktop.

Did you figure it out @jdeagar? 

cc @Subhasish-msft

**Comment by Subhasish-msft** [comment]
@jdeagar, @SamJarmanPP , We are looking into the issue, thanks for your patience.

**Comment by Subhasish-msft** [comment]
@jdeagar , @SamJarmanPP - This issue is fixed now. Can you please confirm if you are still facing it.

**Comment by SamJarmanPP** [comment]
Fixed for us - thank you!

**Comment by Subhasish-msft** [comment]
thanks for the update. closing it
