### ISSUE TITLE
Use the app api to notify users of changes.

### ISSUE THREAD

**Issue by jzbuaa** [MicrosoftDocs/msteams-docs#1582]
Could someone please explain more details on how to use the api to send notification to user's activity feed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3dd35a9c-c868-a7b9-825a-4be9419539d7
* Version Independent ID: 814c8be1-eae8-7316-8553-283ef07ffc09
* Content: [Design guidelines for tabs - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/design/tabs?view=msteams-client-js-latest#feedback)
* Content Source: [msteams-platform/tabs/design/tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tabs/design/tabs.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Trinetra-MSFT** [comment]
@jzbuaa , You can @mention user to notify in activity feed or you can take a look at [Get change notification API](https://docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0).

**Comment by Trinetra-MSFT** [comment]
Please feel free to reopen you have further queries
