### ISSUE TITLE
Teams channel folder renaming not reflected in Sharepoint

### ISSUE THREAD

**Issue by Tomaeusd** [MicrosoftDocs/msteams-docs#1583]
We found a bug where if you create a channel in Teams (desktop app), when a corresponding folder is created in Sharepoint and you change the name of a channel in Teams, the folder remains the same in Sharepoint and you have to manually rename the folder there to accurately reflect Teams. It is not automatically synced/updated like the rest of the files within that folder. Please advise. Thank you!

**Comment by Nikitha-MSFT** [comment]
We could repro the issue on our side raised a bug
