### ISSUE TITLE
Just in time not documented in v4 docs

### ISSUE THREAD

**Issue by clearab** [MicrosoftDocs/msteams-docs#1584]
It looks like the just-in-time flow isn't documented in the new messaging extension docs. This should be added: https://docs.microsoft.com/en-us/microsoftteams/platform/resources/messaging-extension-v3/create-extensions?tabs=typescript#request-to-install-your-conversational-bot. I'm not sure if it really only works with action commands, I think you can use it at almost any point in a messaging extension flow. This should be verified.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5319949f-7a29-1d17-0090-5f423ae8174e
* Version Independent ID: 2d45f040-a391-ac0b-17e8-fa99e880fcf1
* Content: [Initiate actions with messaging extensions - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/messaging-extension-v3/create-extensions?tabs=typescript#request-to-install-your-conversational-bot)
* Content Source: [msteams-platform/resources/messaging-extension-v3/create-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/resources/messaging-extension-v3/create-extensions.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Rajeshwari-v** [comment]
Closing the issue with the confirmation from @Wajeed-msft  , as the required information has been added in "create a task module" page through PR#2664 and is available now.
