### ISSUE TITLE
Editing a message with a photo allows for all content to be deleted.

### ISSUE THREAD

**Issue by OhHappyDagger** [MicrosoftDocs/msteams-docs#1586]
Steps to reproduce:
1. Post a message by pasting a photo into the message field from your clipboard.
2. Edit the message
3. Click on the image itself, not outside of the image
4. Press CTRL+A to select all (I believe this is where the bug is, instead of just selecting the message content, it selects all content in the Teams window.)
4. Press Backspace

Force-quitting Teams returns it to normal.

**Comment by Gousia-MSFT** [comment]
@OhHappyDagger Thanks for reporting this. We have raised a bug for this and we are tracking it internally.

**Comment by BenedekFarkas** [comment]
Just found this myself and have a 100% repro. I had a good laugh though. :D

![image](https://user-images.githubusercontent.com/2797449/80646310-c554ee00-8a6c-11ea-8e5a-370603175cb6.png)

**Comment by Gousia-MSFT** [comment]
We have an open bug on this which is being tracked internally. Thanks for reporting it.
