### ISSUE TITLE
MS Teams Volume Control can not be set seperately

### ISSUE THREAD

**Issue by cwerner1** [MicrosoftDocs/msteams-docs#1588]
While having an meeting in MS-Teams I can't reduce volume of the meeting. It only let you control the output of main mixer. Which leaves you with an completed muted desktop on an Mac.
You don't have a seperated volume control for each application, as on windows.

**Comment by Nikitha-MSFT** [comment]
Could you please raise user voice [here](https://microsoftteams.uservoice.com/)?
