### ISSUE TITLE
When will the restriction for applications running in Azure App Services will be removed ?

### ISSUE THREAD

**Issue by TechWatching** [MicrosoftDocs/msteams-docs#1589]
The note "We also do not support applications that use the azurewebsites.net domain" indicates that this is not supported supported yet but there is no way to track progress on this feature and when to expect it.
This is really important for my company as we are running our teams application in App Service and want to use SSO. However we do not plan to purchase a specific domain for our application.
This [video](https://www.youtube.com/watch?v=fnZYb7O3PMY&t=4248s) indicates this restriction about azurewebsites.net domain will be removed but does not provide a planned date as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52221dd3-95ec-96b9-1da8-9478527c2602
* Version Independent ID: 32e9c2d8-733d-0865-2ea3-727d8684a10d
* Content: [Single Sign-On - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-aad-sso#feedback)
* Content Source: [msteams-platform/tabs/how-to/authentication/auth-aad-sso.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tabs/how-to/authentication/auth-aad-sso.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Nikitha-MSFT** [comment]
We have an active work item on this but we cannot give you an ETA on the fix.
