### ISSUE TITLE
Microsoft Teams APP Studio - messages endpoint field not found in manifest editor

### ISSUE THREAD

**Issue by shereenfathy** [MicrosoftDocs/msteams-docs#1590]
i installed bot using app studio tool in Microsoft Teams and i used it many times to change the bot messaging endpoint url and it was working fine but, i try to edit it now but the messaging endpoint field not found in both bots& messaging extension pages.
any help?
![image](https://user-images.githubusercontent.com/31906452/80309799-793d4b80-87d7-11ea-844e-b4eea4609da4.png)
![image](https://user-images.githubusercontent.com/31906452/80309817-89552b00-87d7-11ea-928f-2f35fc82ce14.png)

**Comment by Subhasish-msft** [comment]
Hi @shereenfathy , Thanks for sharing the feedback. We are looking into it.

**Comment by SamJarmanPP** [comment]
I think there are two more (possibly related) bugs here:

1. You cannot create a new bot - you get a spinner and then nothing.
2. You cannot select an existing bot - the radio button just glitches.

Any ideas would be welcome. I've tried reinstalling App Studio, reinstalling teams, trying on a fresh manifest and even tailing the log files, but nothing helpful there. 

cc @Subhasish-msft

**Comment by Wajeed-msft** [comment]
@SamJarmanPP - Are you still facing this issue?

**Comment by Subhasish-msft** [comment]
@Wajeed-msft , User has confirmed that the issue is resolved [here](https://github.com/MicrosoftDocs/msteams-docs/issues/1580#issuecomment-624279518)
