### ISSUE TITLE
Deep link needs to have a fall back

### ISSUE THREAD

**Issue by viperfx** [MicrosoftDocs/msteams-docs#1592]
I was able to test a scenario, where if you provide a weburl with a context to a channelId, see this scenario:

```
Link to a task item within the configurable tab: https://teams.microsoft.com/l/entity/fe4a8eba-2a31-4737-8e33-e5fae6fee194/tasklist123?webUrl=https://tasklist.example.com/123/456&label=Task 456&context={"subEntityId": "task456","channelId": "19:cbe3683f25094106b826c9cada3afbe0@thread.skype"}
```

When the tab does not exist in the team (it's not added by the user), the desktop app, just goes to the general channel. 

It should open the WebUrl in a browser.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45541337-ecd7-5cf6-cbe4-3f0d2f39aa79
* Version Independent ID: 6b4203f0-2844-06c9-eaa3-9cc03e6f76c0
* Content: [Create deep links - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links)
* Content Source: [msteams-platform/concepts/build-and-test/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/build-and-test/deep-links.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Nikitha-MSFT** [comment]
We are looking into this

**Comment by Nikitha-MSFT** [comment]
we could reproduce the issue on our side. There is an active feature request on this.

**Comment by viperfx** [comment]
Thanks for the update. Can you share a ticket number?

**Comment by Abhijit-MSFT** [comment]
@viperfx, This is not a bug. This is a feature ask raised in Uservoice portal. You can check this on [UserVoice](https://microsoftteams.uservoice.com/)
