### ISSUE TITLE
Fetching list of teams channels within a private chat

### ISSUE THREAD

**Issue by Manish-Ghumnani** [MicrosoftDocs/msteams-docs#1593]
Is there a way to get the list of channels the user belongs to when the bot is initially installed in a private chat ? 
The scenario is that - the user installs the bot to the private chat and then after performing some steps wants the bot to send a message to one of the teams channels, but there doesn't seem to be a way to fetch the team Id when the bot is in the private chat, maybe I missed something ?

**Comment by Gousia-MSFT** [comment]
@Manish-Ghumnani You could get the list of teams that a user is part of, using the [List Joined Teams](https://docs.microsoft.com/en-us/graph/api/user-list-joinedteams?view=graph-rest-1.0&tabs=http) graph api. Are you trying to send a [proactive message](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/send-proactive-messages?tabs=dotnet) in a channel?

**Comment by Manish-Ghumnani** [comment]
@Gousia-MSFT thanks for your reply, from what I know, the Graph API needs permissions and also an authProvider ? Is there a way to avoid that and get the info through the bot context?

**Comment by Gousia-MSFT** [comment]
@Manish-Ghumnani Yes, you would need to get an access token with the required permissions to use this Graph API. It is not possible to do this only with the Bot. The Bot can only fetch the details of the conversation where it is part of.

**Comment by Gousia-MSFT** [comment]
Please re-open if there are any other queries here.
