### ISSUE TITLE
Microsoft Teams Authentication flow for tabs document code sample still points to v3

### ISSUE THREAD

**Issue by Trinetra-MSFT** [MicrosoftDocs/msteams-docs#1595]
Microsoft Teams Authentication flow for tabs document code sample still points to v3, It should be updated to SDK v4

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d5b8b0f-3da3-8642-6edf-dc6608a830cf
* Version Independent ID: f93cdabd-f6ab-29d0-f3c9-78deb21ca521
* Content: [Authentication flow for tabs - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-flow-tab)
* Content Source: [msteams-platform/tabs/how-to/authentication/auth-flow-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tabs/how-to/authentication/auth-flow-tab.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Wajeed-msft** [comment]
Here is link to latest sample on Authentication: https://github.com/OfficeDev/msteams-tabs-sso-sample-nodejs
