### ISSUE TITLE
Read Receipts for Microsoft Teams bot Conversation Events

### ISSUE THREAD

**Issue by ExplodingCow** [MicrosoftDocs/msteams-docs#1596]
Hello there,

I would like to ask whether I am able to obtain the read receipt of the user from the Conversation Events?

**Comment by Gousia-MSFT** [comment]
@ExplodingCow Currently bot does not receive a read receipt status when a message is read by user. Here is a list of all the [events](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/subscribe-to-conversation-events?tabs=dotnet) currently available for Bots. However, sending read receipts for bots is something we are working on but we do not have an ETA on when this would be available.
