### ISSUE TITLE
some words display as '�'' when using french language in MS Teams app localization(manifest 1.5)

### ISSUE THREAD

**Issue by oliver1191** [MicrosoftDocs/msteams-docs#1599]
<ul>
<li><b>Description:</b> Teams display wrong values in app static tab and 'what can i do' input command
            For example,value 'élément' display '�l�ment',it seems that Teams can not recognize the char 'é'</li>
<li><b>Manifest Version:</b> 1.5</li>
<li><b>Teams Language:</b> Français (France)</li>
</ul>
<div>Manifest.json<div>
<pre>{
   //hide bot other message
   "localizationInfo": {
                "defaultLanguageTag": "en",
                "additionalLanguages": [            
                    {
                        "languageTag": "fr",
                        "file": "fr.json"
                    }
                ]
   }
}</pre>
<div></div>
<div>fr.json</div>
<pre>
{
  "$schema": "https://developer.microsoft.com/json-schemas/teams/v1.5/MicrosoftTeams.Localization.schema.json",
  "name.short": "Test",
  "name.full": "TestFullName",
  "description.short": "short description example",
  "description.full": "full description example",
  "staticTabs[0].name": "Nouveautés",
  "bots[0].commandLists[0].commands[0].title": "Restaurer un élément",
  "bots[0].commandLists[0].commands[0].description": "Restaurer élément for test",
}</pre>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f55e52a-5fc4-7fcb-0e1e-946bff5aaee4
* Version Independent ID: b6c559fb-8512-575b-4fed-ebe1457e890e
* Content: [Localization for Team apps - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/apps-localization)
* Content Source: [msteams-platform/concepts/build-and-test/apps-localization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/build-and-test/apps-localization.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by oliver1191** [comment]
This issue has been solved when I check the installer bot package.It seems that the App Studio can not recognize some words like  'é'. So close this issue!

**Comment by Subhasish-msft** [comment]
Thanks for the update @oliver1191 . Closing it.
