### ISSUE TITLE
UI issue in Skype For Windows

### ISSUE THREAD

**Issue by harrynharis** [MicrosoftDocs/msteams-docs#16]
Hi,
Have a look @ the Snippet below. There is a closed bracket in Skype Home Screen.
![capture](https://user-images.githubusercontent.com/34052663/33304496-14150420-d3be-11e7-8dfe-353da1152432.PNG)

**Comment by billbliss** [comment]
This repo is for Microsoft Teams developer documentation.  Does this have anything to do with Teams?
