### ISSUE TITLE
Link to "Request-a-team" app not working

### ISSUE THREAD

**Issue by Lysakers** [MicrosoftDocs/msteams-docs#1600]
The link to "request-a-team" app returns a 404 page not found.
Unable to find it when looking through on GitHub as well.

**Comment by Trinetra-MSFT** [comment]
@Lysakers , Which link you are referring, Could you please be bit more clear on the issue or provide the document where you are seeing this?

**Comment by stuartridout** [comment]
The link to GitHub at the bottom of https://docs.microsoft.com/en-us/microsoftteams/platform/samples/app-templates#request-a-team-app 

The 404 link is https://github.com/OfficeDev/microsoft-teams-apps-requestateam

**Comment by Trinetra-MSFT** [comment]
@stuartridout , @Lysakers , It seems you don't have access to that repo, it was working for me and able to navigate to following github repo : [https://github.com/OfficeDev/microsoft-teams-apps-requestateam](https://github.com/OfficeDev/microsoft-teams-apps-requestateam) after clicking on Get it on Github link in the documentation: [https://docs.microsoft.com/en-us/microsoftteams/platform/samples/app-templates#request-a-team-app](https://docs.microsoft.com/en-us/microsoftteams/platform/samples/app-templates#request-a-team-app)

**Comment by Lysakers** [comment]
It now works as intended.

**Comment by stuartridout** [comment]
This is no longer listed on the app templates page so should not be closed.

**Comment by Lysakers** [comment]
Seems the app is removed from the app template page after i closed the issue.
Reopening again.

**Comment by Trinetra-MSFT** [comment]
@stuartridout @Lysakers , The app is removed from the documentation it seems

**Comment by laujan** [comment]
Hello @stuartridout and @Lysakers. Sorry for the publication issue; the request-a-team app is now live. Thank you for your patience! [request-a-team](https://docs.microsoft.com/en-us/microsoftteams/platform/samples/app-templates#request-a-team-app)
