### ISSUE TITLE
Usage of location in deep links for meetings

### ISSUE THREAD

**Issue by markolb81** [MicrosoftDocs/msteams-docs#1601]
We require to use the location property in the meeting create deep-link. Is there any date we can expect that feature to work, or any workaround available?

Thank you very much in advance!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45541337-ecd7-5cf6-cbe4-3f0d2f39aa79
* Version Independent ID: 6b4203f0-2844-06c9-eaa3-9cc03e6f76c0
* Content: [Create deep links - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links)
* Content Source: [msteams-platform/concepts/build-and-test/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/build-and-test/deep-links.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Gousia-MSFT** [comment]
@markolb81 Could you please share the scenario here? Do you need the user's location while creating meeting through deeplink?

**Comment by markolb81** [comment]
HI, the scenario is as follows:
1. User asks a chatbot where a suitable meetingroom (time, occupation, capacity, equipment, ...) could be found. 
2. Bot answers, and within that answer the best suitable meetingroom is linked in the answer-text to create a meeting directly from that chat-message.

I see two workarounds from a process view, which I don't like very much:
1. create an ICS file and let the user download it
2. ask the user for permission to directly create the meeting via ms graph for him. Since a lot of information will be missing at that point, it is additional work for the user. 

Thanks!

**Comment by Gousia-MSFT** [comment]
@markolb81 Specifying the location in the deeplink is currently not supported. I have raised a feature ask for this but we do not have an ETA when this would be available.
