### ISSUE TITLE
Missing GitHub Repo - "Request-a-team app"

### ISSUE THREAD

**Issue by jpalarchio** [MicrosoftDocs/msteams-docs#1603]
The link to the GitHub repo for "Request-a-team" fails, it seems to be missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 100070d1-40f9-b5eb-be0a-6199de26e0e6
* Version Independent ID: 5d1269e3-2775-ebf6-cf9a-8d1ee7038397
* Content: [Microsoft Teams app templates - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/samples/app-templates#feedback)
* Content Source: [msteams-platform/samples/app-templates.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/samples/app-templates.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by laujan** [comment]
Hi @jpalarchio. The repo should be public later today. I will let you know as soon as it is available. Thank you!

**Comment by Trinetra-MSFT** [comment]
Please feel free to reopen if you have further queries
