### ISSUE TITLE
Authentication for ASP.NET Core with Graph

### ISSUE THREAD

**Issue by Markus-Wolff** [MicrosoftDocs/msteams-docs#1604]
I have currently an ASP.NET Core Application calling Graph in User Scope. It uses Microsoft.Identity.Web to obtain the tokens.
When I try to integrate this App as a Tab in Teams, then authentication does not work as it seems to use iframe.
I checked all the examples (e.g. those for bot) and most of them do the authentication either via JavaScript or use App scope.
Is there any sample app or example that shows my scenario to do the authentication directly in C# code or that shows how to pass the authentication information from JavaScript to the Microsoft.Identity.Web GraphClient in C#?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6416300-1ddf-3ffd-10d2-99ed1f4eb08c
* Version Independent ID: 335d9588-866d-bdde-f1de-6a093a091e2a
* Content: [Authenticate a user in Teams - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/authentication/authentication#feedback)
* Content Source: [msteams-platform/concepts/authentication/authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/authentication/authentication.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Nikitha-MSFT** [comment]
@Markus-Wolff - Are you trying authentication in [tab](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-flow-tab)? Could you please check the sample [here](https://github.com/OfficeDev/microsoft-teams-sample-auth-node/tree/master/src/views/tab/simple). You could use these pages in your C# sample as well.

**Comment by Markus-Wolff** [comment]
@Nikitha-MSFT - Thanks.  Yes, I saw this sample and also a similar version of it with the JavaScript-Bot in C#. However, currently, I use authentication as described here: https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/2-WebApp-graph-user/2-1-Call-MSGraph
There, I acquire the token via: tokenAcquisition.GetAccessTokenOnBehalfOfUserAsync(scopes);
Is there any sample, that shows how it is possible to pass through the token from JavaScript to the GraphClient in C#?

**Comment by Nikitha-MSFT** [comment]
Could you please try [auth providers](https://docs.microsoft.com/en-us/graph/sdks/choose-authentication-providers?tabs=CS). If that helps

**Comment by Markus-Wolff** [comment]
I also had a look there some time ago, however, it does not seems to work in combination with User Scope API calls (as Planner Graph-APIs don't allow delegated callls).

I have currently the ASP.NET Core Application with Razor Pages. With the first tabs-sample from you, I manage to successfully obtain the token in JavaScript.
The business logic that calls the Graph-API needs some logic and also SQL-Calls to obtain other tasks. That is why it needs to reside in C#. With the auth providers, I could theoretically inject there the access token, however I cannot find a way how to transfer/pass the access token, which I can obtain in JS to any of the auth providers. Is there any kind of possibility to do so?

**Comment by Nikitha-MSFT** [comment]
Currently we don't have a sample for tab authentication in C#. But we have an sample for [bot authentication](https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/46.teams-auth) in C#.Could you please try AJAX to pass token to  the graph clients.
