### ISSUE TITLE
Participant List Intermittently Disappears

### ISSUE THREAD

**Issue by NonSoliCedit** [MicrosoftDocs/msteams-docs#1605]
Teams for Mac 1.3.00.8663
MacOS 10.14.6

The right hand Participants pane intermittently will not show the list of participants even if I click on the drop down icon next to "Currently in the meeting (N)". The thumbnails are still across the bottom but if more than 12 or so people it lumps the remaining people into a single circle that says "+(N-12)"

Sometimes the list is there, sometimes it is not.  May be related to going over to a chat with another user and then coming back to the Teams meeting.  Sometimes leaving the meeting and coming back in will repopulate the list, sometimes not.

**Comment by Gousia-MSFT** [comment]
@NonSoliCedit Thanks for reaching out to us. We are looking into this.
