### ISSUE TITLE
Google auth on Microsft Teams mobile app returns 403: disallowed_useragent 

### ISSUE THREAD

**Issue by pdoich** [MicrosoftDocs/msteams-docs#1607]
Hi there,

We are trying to open Trello team tab within the MIcrosoft Teams mobile app, select the Google authentication method and got 403: disallowed_useragent back from Google. Please, see the steps to reproduce here https://softserveinc-my.sharepoint.com/:v:/p/pdoich/Ec_1z_p8SWhCpKEUm4qsUc4Bmj-OrKhp5wGF6Lz5uHM0RQ?e=dY4WBA

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e5840ee-09e8-93a6-51d8-508eef388b0a
* Version Independent ID: 621a526e-59dd-e81a-ee89-6a714bc055c8
* Content: [Tabs on mobile - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/design/tabs-mobile#feedback)
* Content Source: [msteams-platform/tabs/design/tabs-mobile.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tabs/design/tabs-mobile.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Abhijit-MSFT** [comment]
We are working on it. Thanks for reaching out to us.

**Comment by Abhijit-MSFT** [comment]
@pdoich, Google is blocking the iFrame and that is the reason you(all) are facing this issue. We have raised bug on this team is working on it.
