### ISSUE TITLE
Device buttons stopped working in latest Teams release

### ISSUE THREAD

**Issue by Bug-10** [MicrosoftDocs/msteams-docs#1609]
Previous behavior: Buttons on device could answer calls, end calls, mute/unmute both from Teams and device (status was synched between app and device)
Post release behavior: Device only works as microphone/camera, no interaction between buttons and app.

Logitech BCC950
Jabra PHS002W
Upgraded firmware on devices, no improvement.

**Comment by Trinetra-MSFT** [comment]
@Bug-10, Could you please tell us which Teams build you are running on? Are you facing issue Teams desktop/Web or mobile?

**Comment by Bug-10** [comment]
Teams Desktop, two different users (each with one of the devices listed)
Both clients are running Microsoft Teams Version 1.3.00.9267 (64-bit). It was last updated on 4/23/20 & 4/24/20.

**Comment by Trinetra-MSFT** [comment]
@Bug-10 , Could you please try to update your Build version to latest , the build you are running is not latest one, Current public build for teams is running on Microsoft Teams Version 1.3.00.11555 (64-bit) public ring. Or you can report a problem directly from help section
![image](https://user-images.githubusercontent.com/50989436/80944418-28e17180-8e07-11ea-8ad5-9aa267b51997.png)

**Comment by Bug-10** [comment]
Microsoft Teams Version 1.3.00.12058 (64-bit). It was last updated on 5/2/20

Confirmed that both devices are now working again.
