### ISSUE TITLE
Can't edit Teams Meeting Options when part of multiple organisations

### ISSUE THREAD

**Issue by dakneeul1** [MicrosoftDocs/msteams-docs#1610]
User (Meeting organizer) was unable to edit meeting options in teams app for windows, as it added an '#EXT' to their username (as they're part of another organisation), which i'm assuming doesn't equate to what the meeting options page wants (their singular username without the #EXT).

Meeting could've been created pre-joining the second organisation.

The user is part of the main organisation, and added as a guest to a second organisation.

**Comment by dakneeul1** [comment]
![organisation_bug](https://user-images.githubusercontent.com/17067700/80617905-902fa800-8a3a-11ea-8519-7427c8285c28.PNG)

**Comment by Trinetra-MSFT** [comment]
@dakneeul1 , Could you please tell us, where you are seeing this issue Teams desktop client or web version?

**Comment by dakneeul1** [comment]
Teams Desktop Client - when clicking the 'Meeting Options' it takes you to a browser page.

**Comment by Trinetra-MSFT** [comment]
@dakneeul1 , We are looking into this and discussing internally. We will get back to you on this soon

**Comment by Trinetra-MSFT** [comment]
@dakneeul1 , The workaround for this is to open the web client (teams.microsoft.com) in the same browser and switch back to the main organization using the dropdown in the top right corner.

**Comment by Trinetra-MSFT** [comment]
Please feel free to reopen if you have further query
