### ISSUE TITLE
Adaptive card formatting in MS Teams

### ISSUE THREAD

**Issue by shaikShehanaaz** [MicrosoftDocs/msteams-docs#1612]
How to format buttons in Adaptive card in MS Teams. Currently the card is getting rendered as enter image description here
![image](https://user-images.githubusercontent.com/37263235/80672700-0380fa80-8acb-11ea-8059-7b196127ea94.png)
Our aim is to render it as follows:
![image](https://user-images.githubusercontent.com/37263235/80672725-1c89ab80-8acb-11ea-8204-d134299ef9d5.png)
We would like to display the buttons without fill. Any suggestion are highly appreciated.

Here is the JSON for reference:
`{
    "type": "AdaptiveCard",
    "version": "1.0",
    "body": [
        {
            "type": "Container",
            "items": [
                {
                    "type": "TextBlock",
                    "size": "Small",
                    "text": "How can I assist you with Procurement?",
                    "wrap": true,
                    "spacing": "Small",
                    "height": "stretch"
                }
            ]
        },
        {
            "type": "Container",
            "items": [
                {
                    "type": "ActionSet",
                    "actions": [
                        {
                            "type": "Action.Submit",
                            "data": {
                                "msteams": {
                                    "type": "imBack",
                                    "value": "Invoices/Payments"
                                }
                            },
                            "title": "Invoices/Payments",
                            "style": "emphasis"
                        }
                    ]
                }
            ]
        },
        {
            "type": "Container",
            "items": [
                {
                    "type": "ActionSet",
                    "actions": [
                        {
                            "type": "Action.Submit",
                            "data": {
                                "msteams": {
                                    "type": "imBack",
                                    "value": "Purchase Order (PO)"
                                }
                            },
                            "title": "Purchase Order (PO)",
                            "style": "emphasis"
                        }
                    ]
                }
            ]
        },
        {
            "type": "Container",
            "items": [
                {
                    "type": "ActionSet",
                    "actions": [
                        {
                            "type": "Action.Submit",
                            "data": {
                                "msteams": {
                                    "type": "imBack",
                                    "value": "Supplier Information Management (SIM)"
                                }
                            },
                            "title": "Supplier Information Management (SIM)",
                            "style": "emphasis"
                        }
                    ]
                }
            ]
        },
        {
            "type": "Container",
            "items": [
                {
                    "type": "ActionSet",
                    "actions": [
                        {
                            "type": "Action.Submit",
                            "data": {
                                "msteams": {
                                    "type": "imBack",
                                    "value": "Shopping Cart (SC)"
                                }
                            },
                            "title": "Shopping Cart (SC)",
                            "style": "emphasis"
                        }
                    ]
                }
            ]
        },
        {
            "type": "Container",
            "items": [
                {
                    "type": "ActionSet",
                    "actions": [
                        {
                            "type": "Action.Submit",
                            "data": {
                                "msteams": {
                                    "type": "imBack",
                                    "value": "Goods Receipt (GR)"
                                }
                            },
                            "title": "Goods Receipt (GR)",
                            "style": "emphasis"
                        }
                    ]
                }
            ]
        }
    ],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json"
}`

**Comment by Trinetra-MSFT** [comment]
@shaikShehanaaz , I've tested this in [https://adaptivecards.io/designer/](https://adaptivecards.io/designer/) and i can see the expected output:
![image](https://user-images.githubusercontent.com/50989436/80679737-169bc680-8adb-11ea-84d2-4d0316843d6f.png)
Are you facing this issue while Bot throwing the card?

**Comment by shaikShehanaaz** [comment]
@Trinetra-MSFT .When the card is rendered in MS Teams the design is not same as the one shown in the designer.

**Comment by clearab** [comment]
If you remove the style: emphasis it should work unfilled. The best way to test how your adaptive cards will look in Teams is to use the card editor in App Studio - you can even use it to send yourself a test card so you can validate across clients.
