### ISSUE TITLE
Proofing Tools / Spell don't work within tab pages?

### ISSUE THREAD

**Issue by ShadowXVII** [MicrosoftDocs/msteams-docs#1614]
The Proofing Tools don't appear to work in the tab pages. Is this intended?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9938300a-8983-2236-5d02-536b9b872225
* Version Independent ID: b336fba4-1e88-db4a-0a41-c91a57384aee
* Content: [Extend your Teams app with a custom tab - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/add-tab)
* Content Source: [msteams-platform/tabs/how-to/add-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tabs/how-to/add-tab.md)
* Product: **msteams**
* GitHub Login: @laujan

**Comment by ShadowXVII** [comment]
Added teams bug entry as well: https://microsoftteams.uservoice.com/forums/908686-bug-reports/suggestions/40333423-bug-spell-check-does-not-work-on-personal-tabs

**Comment by Nikitha-MSFT** [comment]
Currently teams does not provide this service.
