### ISSUE TITLE
404 Page not found

### ISSUE THREAD

**Issue by gewarren** [MicrosoftDocs/msteams-docs#1616]
_From @mirandtech on Wednesday, April 8, 2020 2:14:21 PM_

**Describe the bug**
https://docs.microsoft.com/en-us/microsoftteams/platform/redirects/?redirectedfrom=MSDN

page not found.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

_Copied from original issue: MicrosoftDocs/feedback#2655_

**Comment by gewarren** [comment]
_From @welcome[bot] on Wednesday, April 8, 2020 2:14:22 PM_

Thank you for creating the issue! One of our team members will get back to you shortly with additional information. If this is a product issue, please close this and contact the particular product's support instead (see https://support.microsoft.com/allproducts for the list of support websites).

**Comment by Mahesh2516** [comment]
As per the confirmation received from the SME (Nikitha) on 01/27/2021, while migrating v3 to v4 doc and this is deprecated, hence, closing the issue.
