### ISSUE TITLE
The chat channel is not visible on the desktop client

### ISSUE THREAD

**Issue by dikdiv** [MicrosoftDocs/msteams-docs#1617]
Bug description:
User A has the Teams client version 1.3.00.9267 (64-bit) installed on the desktop (OS: Windows 7 x64), and the teams mobile client is installed on the andorid smartphone.
The Teams client on user A's desktop is turned off (the desktop is turned off).
User B creates a new chat channel with user A. User A sees a message from user B under the mobile client.
User A starts the Teams client on the desktop. The new chat channel under the Teams client on the desktop is not visible until a message is sent in the channel.

**Comment by Gousia-MSFT** [comment]
@dikdiv Thanks for reaching out to us. We have forwarded this to the right team who could look into it.
