### ISSUE TITLE
Verifying requests from Teams Tab

### ISSUE THREAD

**Issue by ndileep** [MicrosoftDocs/msteams-docs#1619]
Hi, 1) How can the backend service confirm that the initial tab load request is coming from Microsoft? 2) Even if we implement the SSO, how can the backend service confirm that subsequent requests are coming from the loaded tab?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52221dd3-95ec-96b9-1da8-9478527c2602
* Version Independent ID: 32e9c2d8-733d-0865-2ea3-727d8684a10d
* Content: [Single Sign-On - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-aad-sso)
* Content Source: [msteams-platform/tabs/how-to/authentication/auth-aad-sso.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tabs/how-to/authentication/auth-aad-sso.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Trinetra-MSFT** [comment]
@ndileep , You can check with [get context for your tab](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/configuration-page#get-context-data-for-your-tab-settings)

**Comment by ndileep** [comment]
We can get the context on the front end and send to the backend, but same information someone can send from postman also. How can the backend verify that the information is in fact coming from the Teams Client? Similarly, during the very first load or refresh of the tab within a Teams Client.

**Comment by TechWatching** [comment]
Interesting question, I was wondering the same thing. I did not try but maybe we could solve that by passing the azure ad token in the authentication header of the requests, what do you think ? Maybe this way the backend would just be configured to handle Azure AD authorization.

**Comment by ndileep** [comment]
Yes, that would work @TechWatching. I was checking if there is a way without using SSO or any other types of authorization.

**Comment by Trinetra-MSFT** [comment]
@ndileep , Could you please look at [Teams Client SDK Public API](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/using-teams-client-sdk#teams-sdk-public-api)? You can implement `getTabInstance `method to check the Tab instance.
