### ISSUE TITLE
Form link doesn't work 

### ISSUE THREAD

**Issue by vaibhavagarwaljss** [MicrosoftDocs/msteams-docs#1620]
Above page has "If you already have an app in the app store and you'd like to join the program you can contact us by filling out this form." 

This link seems expired. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75dcbc89-3e4e-6ccc-aab0-49debb445e7c
* Version Independent ID: afd117d9-e02e-fa13-a858-9f6bafb61d1f
* Content: [App Certification - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/post-publish/application-certification)
* Content Source: [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/application-certification.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/deploy-and-publish/appsource/post-publish/application-certification.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by LGerrard** [comment]
Thank you Vaibhav for bringing this to our attention. The link has been fixed.

**Comment by laujan** [comment]
Hi @vaibhavagarwaljss. Yes, the process has changed and the form reference is no longer part of the documentation. Thank you for your feedback!
