### ISSUE TITLE
[Linux] During scrolling exam screen turns black

### ISSUE THREAD

**Issue by merczan** [MicrosoftDocs/msteams-docs#1622]
Hi
As per title. I was in the middle of an exam or quiz whatever that function is called and when I was scrolling with my bluetooth mouse I was getting black screen covering exam area and I had to reenter every single answer. I was getting that black screen constantly when scrolling. At one point I was getting back every 2 or 3 minutes and my answers were saving. 

Thank you for time

**Comment by Abhijit-MSFT** [comment]
@merczan, Please share more details on this. Is it something related to Teams?
Please share screenshot if it is possible.

**Comment by merczan** [comment]
Hey, sorry for taking so long I needed footage to show you what is happening. Yes, it is on linux and it is happening on your official app release. 
Here is a link with a video for you to download, expires in 7 days or after 1 download. 

https://send.firefox.com/download/7997ef1ca053f25c/#F2H5R8KB79H9as6515

Soft installed on newest ubuntu 20.04 LTS

**Comment by merczan** [comment]
When I do nothing or scroll with side bar manually it works but when I use m scroll wheel it just shows a black screen and I have to rejoin the test.

**Comment by Abhijit-MSFT** [comment]
Provided link is expired.

**Comment by merczan** [comment]
https://vimeo.com/417510745

**Comment by Abhijit-MSFT** [comment]
@merczan - Sorry, i missed out your response. We are checking it

**Comment by Abhijit-MSFT** [comment]
@merczan, are you still facing this problem?
