### ISSUE TITLE
Document that you can size the auth popup

### ISSUE THREAD

**Issue by aosolis** [MicrosoftDocs/msteams-docs#1624]
by adding width and height parameters, like ?width=600&height=600
Also document that the actual size is capped as a percentage of the Teams client size, so if the Teams window is small the popup window will be smaller than the specified dimensions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 503e124f-2b80-d6ae-581a-ca77f0a1999f
* Version Independent ID: 66d2bd8a-536b-1a45-f71c-eb2a0199de46
* Content: [Add authentication to your messaging extension - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/add-authentication)
* Content Source: [msteams-platform/messaging-extensions/how-to/add-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/messaging-extensions/how-to/add-authentication.md)
* Product: **msteams**
* GitHub Login: @clearab
* Microsoft Alias: **anclear**

**Comment by aosolis** [comment]
This is still pending, and we get questions about this. The bot signin action, ME auth and ME config popups all support this.
https://github.com/MicrosoftDocs/msteams-docs/issues/2028
https://github.com/microsoft/AdaptiveCards/issues/4662

**Comment by surbhigupta12** [comment]
Issue resolved in PR: #3627
