### ISSUE TITLE
Asking a participant to join caused recipient to not be able to see shared content

### ISSUE THREAD

**Issue by stormtrooper1138** [MicrosoftDocs/msteams-docs#1631]
I invited a participant that accepted an invitation to join a meeting scheduled. When they weren't on, I went to the the "Show Participants, looked at their status, and then clicked on their profile and selected the option "Ask to Join".

During the first moments of the meeting, the host shared a document, but this participant I asked to join could not see the shared content. He hung up after a couple of attempts. When he joined the meeting the normal way, he was able to see the content just fine.

**Comment by Abhijit-MSFT** [comment]
@stormtrooper1138 , It could be network glitch. Are you facing any issue now?

**Comment by stormtrooper1138** [comment]
I haven’t had the meeting since Friday. The individual hung up from my invite to join and joined using the link, and had no problems. We don’t have our corporate network requiring VPN for most Microsoft 365 features since we log into the domain.

I will attempt it again in my next Teams meeting and let you know.

Jeff Gomez <mailto:jeffgomez1@churchofjesuschrist.org> | Data Analyst
Welfare & Self-Reliance Services

**Comment by Abhijit-MSFT** [comment]
Sure, Thank You
