### ISSUE TITLE
Teams Channel API returning incorrect data

### ISSUE THREAD

**Issue by RiddhiKarani** [MicrosoftDocs/msteams-docs#1634]
I am using the API - https://graph.microsoft.com/v1.0/teams/" + team_id + "/channels

this API is returning me a private channel on a team which this user is not even a part of.

when i go to teams client i dont see the private channel but the API returns to me the private channel

**Comment by Subhasish-msft** [comment]
@RiddhiKarani , Thanks for reporting the issue. We have created a bug and working on it.

**Comment by RiddhiKarani** [comment]
any update on this issue?

**Comment by Subhasish-msft** [comment]
@RiddhiKarani  This is bug is currently in our backlog and there is no ETA on this.
