### ISSUE TITLE
Call icon doesn't appear in the bot channel 

### ISSUE THREAD

**Issue by shereenfathy** [MicrosoftDocs/msteams-docs#1636]
Hello,
I have created a bot and registered it in  Bot Framework without an Azure subscription by using the legacy portal and I checked "enable calling" checkbox, but when I open the bot in teams I can't find the call icon, but when I upload manifest file in app studio tool then install the bot the icon appears.
![image](https://user-images.githubusercontent.com/31906452/81504260-977f6d00-92e8-11ea-90c3-3aede2ba0aca.png)

**Comment by Gousia-MSFT** [comment]
@shereenfathy That is the expected behaviour. The app manifest has the setting for enabling calling for Bot.

**Comment by shereenfathy** [comment]
@Gousia-MSFT  is that means I can't use the bot framework legacy portal for enabling calling in my bot?
in other words "enabling calling" checkbox in the legacy portal not enough to make Microsoft teams appear the call icon in my bot channel?

**Comment by Gousia-MSFT** [comment]
@shereenfathy Yes, you need to enable calling for the bot in the bot framework and add this setting in the manifest to be able to make calls.

**Comment by shereenfathy** [comment]
ok, thank you but please add this note to the doc to be clear for everyone.

**Comment by Gousia-MSFT** [comment]
@shereenfathy Thanks for sharing your suggestion here!.
