### ISSUE TITLE
Document that using Bot Framework actions don't work in a task module

### ISSUE THREAD

**Issue by aosolis** [MicrosoftDocs/msteams-docs#1639]
The technique described here of adding 'msteams' to data, with a bot framework action, does not work in an adaptive card task module.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 672a763d-189b-8ba0-f66e-c07f1dc0a962
* Version Independent ID: 1ac7a9bd-138b-3bf8-60a3-1842d87371fd
* Content: [Add card actions in a bot - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-actions#adaptive-cards-actions)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-actions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-actions.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Nikitha-MSFT** [comment]
Could you please share more details where you are facing issue? Also could you please share card json?
