### ISSUE TITLE
Default EULA

### ISSUE THREAD

**Issue by pgrzesik** [MicrosoftDocs/msteams-docs#1640]
Hello, 

in the description of `EULA`, it states that "AppSource requires an end-user licensing agreement (EULA), which you can provide as an attachment. If you choose not to submit a EULA, one will be provided on your behalf.". Is there a way to see how the default, provided EULA looks like? 

Regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa28e49e-3a76-729b-b1f6-d1bcb39f26aa
* Version Independent ID: 907f0205-82bf-846b-0243-6b3b311ee747
* Content: [App manifest checklist - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/app-manifest-checklist#feedback)
* Content Source: [msteams-platform/concepts/deploy-and-publish/appsource/prepare/app-manifest-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/deploy-and-publish/appsource/prepare/app-manifest-checklist.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Nikitha-MSFT** [comment]
Here is the default, provided [EULA ](https://support.office.com/client/61994a3b-2c87-41c4-a88d-a6455efa362d?omkt=en-US)link. However you can provide Terms of Service URL in case the add-in doesn't have specific EULA link. We have raised an IcM ticket for updating the [documentation ](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/app-manifest-checklist#metadata-requirement)and working on it.

**Comment by pgrzesik** [comment]
Hello @Nikitha-MSFT, thank you for your assistance :bow:
