### ISSUE TITLE
Teams Outlook add-in causing disk thrashing

### ISSUE THREAD

**Issue by greedj** [MicrosoftDocs/msteams-docs#1641]
This has been an issue for months now and is very frustrating.
When enabled, the Teams Outlook add-in causes Outlook to thrash the disk, impacting I/O and performance severely. This is happening across the organization and the only help I see online is people saying to disable the add-in. 

Outlook: 16.0.12527.20278
Teams Add-in: 1.0.20031.2
Teams: 1.3.00.8663

Note: This was happening in older builds of Teams as well.

**Comment by Trinetra-MSFT** [comment]
@greedj Could you please use report a problem feature?
