### ISSUE TITLE
Get call notification when a MS Teams user gets/make call from/to PSTN (configured through Direct Routing)

### ISSUE THREAD

**Issue by bijaykush** [MicrosoftDocs/msteams-docs#1643]
As per the document it seems like we have to use MS Calling bot endpoint to get the call notifications(i.e. the case when bot is involved in the call ). But in case, when we have used Direct Routing with own SIP Trunks in MS Teams for incoming/outgoing call to PSTN, How can we get notifications like call is being establishing, established, terminated, etc.?

Any suggestion or workaround will be appreciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63d7dc57-5cd6-e66f-8c98-dac7986487c9
* Version Independent ID: 849659d8-7320-9b27-84b2-b872a772c69a
* Content: [Technical details on handling incoming call notifications - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/calls-and-meetings/call-notifications#feedback)
* Content Source: [msteams-platform/bots/calls-and-meetings/call-notifications.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/bots/calls-and-meetings/call-notifications.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Gousia-MSFT** [comment]
@bijaykush This scenario is not supported with current APIs so far.
