### ISSUE TITLE
How to perform sign out?

### ISSUE THREAD

**Issue by abbodh** [MicrosoftDocs/msteams-docs#1645]
I am looking for a way to perform sign out? Is it even possible to logout when using SSO?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52221dd3-95ec-96b9-1da8-9478527c2602
* Version Independent ID: 32e9c2d8-733d-0865-2ea3-727d8684a10d
* Content: [Single Sign-On - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-aad-sso)
* Content Source: [msteams-platform/tabs/how-to/authentication/auth-aad-sso.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tabs/how-to/authentication/auth-aad-sso.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Nikitha-MSFT** [comment]
Currently teams does not provide a in-build sign-out function. Could you please implement your own sign-out? Also could you please go through the [sample](https://github.com/ydogandjiev/taskmeow/blob/master/src/services/auth.service.js#L36).
