### ISSUE TITLE
Can't delete meeting using API.

### ISSUE THREAD

**Issue by Digesha** [MicrosoftDocs/msteams-docs#1647]
Hello,
I created a meeting using API and now trying to delete it using API.

I am using this document https://docs.microsoft.com/en-us/graph/api/onlinemeeting-delete?view=graph-rest-beta&tabs=http  to delete meeting.

But it throws this error while deleting-
Array
(
    [error] => Array
        (
            [code] => BadRequest
            [message] => Invalid meeting id c18ea81c-263c-4511-862d-3dc0a883b0a1_19:54192ee4319d4e31b8bf07660fa758d2@thread.tacv2.
            [innerError] => Array
                (
                    [request-id] => b4492244-bf52-4454-896b-79257377774a
                    [date] => 2020-05-11T11:47:35
                )
        )

Thanks.

**Comment by Trinetra-MSFT** [comment]
@Digesha , What endpoint you are trying to call? Could you please try to call:
DELETE: https://graph.microsoft.com/beta/me/onlineMeetings/{id}
It works at our end. Let me know how it goes

**Comment by Trinetra-MSFT** [comment]
Please feel free to reopen if you have further query
