### ISSUE TITLE
Accessing a different tenants channel memberships

### ISSUE THREAD

**Issue by brandonrachal** [MicrosoftDocs/msteams-docs#1650]
I was going back and forth between two tenants when I came across a strange issue.
I got a list of members from a channel and noticed that all the display names were blanks.

```
{
    "@odata.type": "#microsoft.graph.aadUserConversationMember",
    "id": "some_id",
    "roles": [],
    "displayName": null,
    "userId": "some_id",
    "email": null
}
```

When I looked up the user I got this message:

```
{
  "error": {
    "code": "Request_ResourceNotFound",
    "message": "Resource 'some_id' does not exist or one of its queried reference-property objects are not present.",
    "innerError": {
      "request-id": "fec02c08-65bf-41a9-a870-6b53281d01cb",
      "date": "2020-05-13T19:14:44"
    }
  }
}
```

That's when I realized I had just looked up the members of a channel using a different tenants token. This should not be possible and the messages I receive for this bug are very confusing.

https://graph.microsoft.com/beta/chats/<chat_id>/members?

**Comment by Subhasish-msft** [comment]
We have created a bug and discussing this issue with internal team, will update you shortly.
