### ISSUE TITLE
Can't upload to Teams - works fine in local host

### ISSUE THREAD

**Issue by Minxpinx** [MicrosoftDocs/msteams-docs#1651]
I have the same error 0 Can't upload to Teams. Are there any variables that we have to enter in the env file? You mentioned adding the domain above "Please make sure you are adding your site domain inside the validDomain list of your manifest." Can you give instructions on this please.
I have validated the manifest in Teams and it has passed.  Sideloading is enabled on the tenant

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42e0cad5-f762-c253-7d3b-b23ae3cb5b1c
* Version Independent ID: f1babe27-cbc7-f757-11b4-fc8fa1e36873
* Content: [Get started with the Yeoman generator for Microsoft Teams - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tutorials/get-started-yeoman#feedback)
* Content Source: [msteams-platform/tutorials/get-started-yeoman.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tutorials/get-started-yeoman.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Gousia-MSFT** [comment]
@Minxpinx could you please share a screenshot the issue?

**Comment by Minxpinx** [comment]
Hi
Here are the screenshots. I have also attached the manifest. Do I need to
add details to the environm
ent env file?

[image: image.png]

env
[image: image.png]
# The domain name of where you host your application
HOSTNAME=hellopnp2.azurewebsites.net

# App Id and App Password ofr the Bot Framework bot
MICROSOFT_APP_ID=00000000-0000-0000-0000-000000000000
MICROSOFT_APP_PASSWORD=

# Port for local debugging
PORT=3007

# Security token for the default outgoing webhook
SECURITY_TOKEN=

# ID of the Outlook Connector
CONNECTOR_ID=

# Application Insights instrumentation key
APPINSIGHTS_INSTRUMENTATIONKEY=

# NGROK configuration for development
# NGROK authentication token (leave empty for anonymous)
NGROK_AUTH=
# NGROK sub domain. ex "myapp" or  (leave empty for random)
NGROK_SUBDOMAIN=
# NGROK region. (us, eu, au, ap - default is us)
NGROK_REGION=

# Debug settings, default logging "msteams"
DEBUG=msteams

MICROSOFT_APP_ID=00000000-0000-0000-0000-000000000000

**Comment by Gousia-MSFT** [comment]
@Minxpinx I cant view the screenshots. Could you please attach them here?

**Comment by Gousia-MSFT** [comment]
Please re-open with requested information
