### ISSUE TITLE
Unable to render Iframe on Task module which is having SSO in Ms teams

### ISSUE THREAD

**Issue by Chekrii** [MicrosoftDocs/msteams-docs#1652]
Hi All,

I am trying to display MS forms on the task module on the button click of an adaptive card in my chatbot which is built Using MS Bot framework.

I am using the IFrame to display the MS form on the Task module.
But if the form requires authentication then the form is not displaying on Task module. Instead, it is showing "Fill out the form".

The IFrame that I am using is : -

`<iframe  height="750px" width="700px" src= "https://forms.office.com/Pages/ResponsePage.aspx?id={ID}&embed=true" frameborder= "0" marginwidth= "0" marginheight= "0" style= "border: none; max-width:100%; max-height:100vh" allowfullscreen webkitallowfullscreen mozallowfullscreen msallowfullscreen> </iframe>
`
Please help me how to open form on Task module.
Please find the screenshot of how the form is rendering on Task module.

![tempsnip](https://user-images.githubusercontent.com/49824279/81911645-3c50c180-95eb-11ea-9590-be2637be19c4.png)

Thanks.

**Comment by Trinetra-MSFT** [comment]
@Chekrii , I tried to add MS Form in Teams task module it works as expected. I tried with your URL, it is saying form doesn't exist. 
Test Form created by me
![image](https://user-images.githubusercontent.com/50989436/82020485-cca00c80-96a6-11ea-9f0a-599544eea21c.png)
**With your Form URL:** = [https://forms.office.com/Pages/ResponsePage.aspx?id={ID}&embed=true](https://forms.office.com/Pages/ResponsePage.aspx?id={ID}&embed=true)
![image](https://user-images.githubusercontent.com/50989436/82020579-fb1de780-96a6-11ea-9dbb-ee0bda27ffe3.png)

Few quick checks:
1. Did you added `forms.office.com` in validDomain array?
2. Where you are facing this issue Teams Web or desktop client?

**Comment by Chekrii** [comment]
Hello  @Trinetra-MSFT ,

I have added "forms.office.com" in validdomain array.
This issue I am facing in Desktop client, where on Task module it is showing "Fill out the Form" option instead of form.

In the web, the form is opening properly.

```
<iframe width="640px" height= "480px" src= "https://forms.office.com/Pages/ResponsePage.aspx?id=UnUMmjM4xEa7rIvH-WDuUoB_QHdkcfJIl-jJtV0Zc-ZUNElWNk1QMzI0QkVQVEs5R1FQTjVJUDFIUi4u&embed=true" frameborder= "0" marginwidth= "0" marginheight= "0" style= "border: none; max-width:100%; max-height:100vh" allowfullscreen webkitallowfullscreen mozallowfullscreen msallowfullscreen> </iframe>

```
This is the Iframe I am using.

**Comment by Trinetra-MSFT** [comment]
@Chekrii , Thanks for sharing the information. You have SSO implemented in Form, right?
Let me check this at my end. I will get back to you soon.

**Comment by Chekrii** [comment]
Yes @TravisCragg-MSFT, I have enabled SSO on the form.

**Comment by Chekrii** [comment]
Hello @TravisCragg-MSFT , any Update on the issue because one of the important feature depends on this one. 
Thanks

**Comment by Trinetra-MSFT** [comment]
@Chekrii This is a supported embed scenario for Forms could you please reach out to the Forms team about this issue. we doesn't have much insight as to what's going on within the Forms app or why it wouldn't be able to find the right form.

**Comment by Chekrii** [comment]
@Trinetra-MSFT, But the same form is rightly displayed on Web Teams Task module but bot in the Teams Desktop app.

**Comment by Trinetra-MSFT** [comment]
@Chekrii , Could you please provide logs or screenshot of the error you are getting in Teams desktop client?
