### ISSUE TITLE
When I Open a Word Document in Teams it's Stuck on Spanish for Spellchecking

### ISSUE THREAD

**Issue by StephenClarkApps** [MicrosoftDocs/msteams-docs#1653]
When I Open a Word Document in Teams it Stuck on Spanish for Spellchecking, if I go into the menu and change this to English it has no effect and incorrect modifications are still suggested. If I go out of the application and back in it resets to Spanish corrections again. 

My environment is:
MacBook Pro (15-inch, 2017)
The version is:
Microsoft Teams Version 1.3.00.8663. 

(Which is not to mention the fact that the formatting also doesn't match what it looks like when you open it in the desktop version of word on the Mac)

**Comment by Nikitha-MSFT** [comment]
Is your document native language is English? Also could you please check teams language is set to English?

**Comment by StephenClarkApps** [comment]
Yes indeed. The native language is English, however when I go into review
and open the spelling options from within teams it will initially show as
Spanish. When I change that to English it shows as English in the settings
menu but still corrects for Spanish. When and come out of the document and
go back into it, then go back into the language setting menu it has again
reverted to Spanish.

**Comment by Nikitha-MSFT** [comment]
Is the teams settings for the user English and the Proofing settings set to English but this is showing "Spanish" suggestions? If so Could you please re-pro steps and screen shots of the issue?
