### ISSUE TITLE
Access token generated after SSO sign in is showing unauthorised while calling Graph API API with Group.Read.All permissions

### ISSUE THREAD

**Issue by v-smahaj** [MicrosoftDocs/msteams-docs#1654]
Implemented SSO on teams tab. Granted consent for Group.Read.All permission. When using token for Graph API call, it is showing Unauthorised error. Also, same token is generated when app is installed in different tenants.

**Comment by Gousia-MSFT** [comment]
@v-smahaj Could you please use [jwt.io](https://jwt.io) to confirm if the access token has all the permissions granted?

**Comment by v-smahaj** [comment]
I have checked token at jwt.io. It is only showing user_impersonation in scope. Other API permissions are not listed there.

**Comment by Gousia-MSFT** [comment]
@v-smahaj The current implementation of SSO only grants consent for user level permissions. Please check the known limitation with SSO [here](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-aad-sso#known-limitations).

**Comment by v-smahaj** [comment]
Currently, I am only getting Id token and I have to make another API call to get access token from Id token as I have to call Graph API with Group.Read.All permissions. Is there any workaround for this?

**Comment by Gousia-MSFT** [comment]
@v-smahaj This is a known limitation with SSO currently. We are working on making this experience better.
