### ISSUE TITLE
How to automatically configure this using azure cli or template ARM ?

### ISSUE THREAD

**Issue by TechWatching** [MicrosoftDocs/msteams-docs#1656]
Could you provide the azure cli sample to automatically configure everything in Azure AD for the SSO to work ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52221dd3-95ec-96b9-1da8-9478527c2602
* Version Independent ID: 32e9c2d8-733d-0865-2ea3-727d8684a10d
* Content: [Single Sign-On - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-aad-sso)
* Content Source: [msteams-platform/tabs/how-to/authentication/auth-aad-sso.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tabs/how-to/authentication/auth-aad-sso.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Abhijit-MSFT** [comment]
@TechWatching, You have many options. Here goes the [cli tool](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest) option. You can automate things in Azure using [rest api](https://docs.microsoft.com/en-us/rest/api/azure/) and [Powershell scripting](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest)

**Comment by TechWatching** [comment]
I know Azure Cli but I did not find how to create or update an app registration to expose an API like the one described in this documentation. What azure cli command should be used, with what parameter is what is missing from this documentation page. Maybe an ARM template sample could be a nice addition too. 
I successfully add SSO to my teams tab  using the azure portal but I am unable to do automate it and there is nothing in this documentation that tells how to do it.

**Comment by TechWatching** [comment]
Thanks to the help of the community I succeeded to create a Powershell script that automates that. See the microsoft Q&A issue [here](https://docs.microsoft.com/en-us/answers/questions/29893/azure-ad-teams-dev-how-to-automate-the-app-registr.html?childToView=34834#answer-34834). I think this could be a starting point for an official script to be added in the documentation.

**Comment by TechWatching** [comment]
Until the doc gets updated, I wrote an [blog post](https://www.techwatching.dev/posts/teams-sso-powershell) about configuring Teams Tab SSO using PowerShell.
