### ISSUE TITLE
Sluggish adaptive card rendering on mobile devices

### ISSUE THREAD

**Issue by stpeteparadox** [MicrosoftDocs/msteams-docs#1657]
**_Background_**

This issue follows the recommended action at the end of Issue #388.

Our current proactive bot posts an hourly notification to a Teams channel containing detailed information on various systems, including both current status and changes over time. Because of the breadth of the data, the report is converted to an image and posted to the Teams channel (actually we continue to rely on a Slack channel, but would like to switch to Teams).

This is an example of the image (with content blurred for privacy/IP reasons). The general structure of the data presentation can still be made out:

![image](https://user-images.githubusercontent.com/3724281/82118357-7962b280-97a9-11ea-82f9-640fdd4d65e8.png)

However, due to Teams not having consistent in-app expandability (ie within the app, not separate loading in a browser app) of images across devices (as mentioned in #388--though this will apparently hopefully be resolved soon), we decided to test converting the underlying data to a pure json-format adaptive card.

Attached ([card.zip](https://github.com/MicrosoftDocs/msteams-docs/files/4638259/card.zip)) is a zip of the card json. Business values and strings have been obfuscated for privacy/IP reasons. Please ignore the lack of formatting cleanliness - our intention was to only initially test structure and basic usability. Fine-tuning of formatting would come later. (With real data it actually is already quite readable - but with the random characters it looks terrible.)

When we initially tested sending this card, it failed, with a response of 
`{"error":{"code":"MessageSizeTooBig","message":"Message size too large."}}`

For reference, the http post content-length with the attached is ~97KB. This size card is only sent once per week. The normal card sent hourly is ~50-60KB as it has two less buttons with expanding content at the bottom. From what we've read on various forums, people have previously observed a 25-30KB limit on card message sizes in Teams. We replicated that limit by incrementally down-sizing our card until it finally sent through.

That said, by enabling the developer preview mode in Teams on desktop and mobile (and potentially also by changing the card to version 1.2 -- though I can't recall if we did that before or after the above msgsize error), the size limit appears to have been raised or removed, and our full-size cards are successfully getting sent through. Or perhaps our actions here are just coincidence.

**_The Main Problem_**
Rendering quality and behavior varies by device.

_Teams on iOS (iPhone 7):_
Rendering is very sluggish. The card takes 3-5 seconds to load/appear when switching into the channel. Clicking on the buttons can be quite unpredictable (sometimes they don't react; sometimes the app crashes). When clicking the button, the card re-renders in a flash, with the buttons scrolling up and then back down. Scrolling back through earlier cards causes the app to slow down to a sputter, and freeze for lengthy periods. It feels like what happens when memory utilization is very high. 

_Teams on iOS (iPad - a bit younger than the iPhone 7):_ 
Similar, but a bit better rendering to the iPhone as mentioned above.

_Teams on Win10 (3yr old thinkpad):_
Renders fine. A slight bit of sluggishness when clicking the buttons that expand the content.

_Teams on macOS (5yr old macbook air):_
Renders fine. 

_Teams in browser (modern Edge on Win10):_
Very smooth rendering.

_Teams in browser (Chrome on Win10):_
Renders fine.

A smaller issue (or design choice?) on the mobile devices is that depending on how you touch the adaptive card and its buttons, especially when it is acting sluggish, Teams will sometimes load the card in a separate window (screen shifts to the right). Similar behaviors there.

We would really like to be able to switch entirely to a fully json-based version of our adaptivecard (ie without an embedded image), but the inconsistency of rendering across mobile vs. full-size devices is too large. One might argue that we are putting too much data in our adaptivecard -- but to that we'll counter-argue that that data is precisely what is shown in the alternative image approach. The metrics have been chosen with care and designed with precision. Our users have relied on this information on a daily basis for several years now. For now we continue to share this information via Slack using an image (with in-app expandability). 

If Teams can't support this much content in raw json, then hopefully the image expandability feature will be enabled soon to bring that aspect of images to parity with Slack, and we will then move over completely.

Thank you very much for your help and advise.

**Comment by Subhasish-msft** [comment]
@stpeteparadox , Can you please share the iOS version and MS Teams build version of the device (iPhone 7). Also if you are not on latest version of MS Teams, can you please try updating it.

Regarding the earlier issue, Teams has a limitation of size 28 KB for the entire message payload, not just the Adaptive Card. Teams will add more data to your card. Here is the [doc](https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams) link

**Comment by stpeteparadox** [comment]
@Subhasish-msft 

iPhone 7 iOS version: 13.4.1
Teams iOS version: 2.0.8 (build 1.077.2020042201; calling version 2020.06.01.7)

Thanks for the link to the message payload limit documentation. Are these limits temporarily removed or raised in developer mode? Why are we able to exceed them at the moment?

**Comment by Subhasish-msft** [comment]
Thanks for the detail @stpeteparadox, I will be creating a bug for this. Can you please share the sample card json with which we can reproduce it. Previously shared card seems to be very large(353 KB) and we can not use it. 

Regarding card size, Developer preview does not remove card size limit. As per guideline, It has to be within the limit. Can you confirm the exact size of the card which got posted successfully in dev preview mode.

**Comment by stpeteparadox** [comment]
@Subhasish-msft  The card json I previously shared is precisely what we send each time, just with the property string values obfuscated (but same string length).

As for the card size, it's unfortunate to observe this, but in my experience the Microsoft Docs, in particular those for Teams, can be out-of-date. I'm not sure if that's what's happening in this case, but as I have already described above, our messages post without issue. The problem appears to be in the client-side rendering on mobile, which is sluggish.

I believe you may be looking at the on-disk json card size (353 KB) which appears to be different from the http post body content-length of 98 KB. Not sure if there's any compression going on, but I do know that the on-disk size of the non-obfuscated json card is currently ~280 KB vs. 353 KB for obfuscated on-disk card. As mentioned the string lengths are all the same, except that in the obfuscated card, the string values are all rather unique. 

If you need further proof that our 98KB messages are being successfully posted despite what the documentation may say, please see below screenshots. Sensitive values have been removed.

![image](https://user-images.githubusercontent.com/3724281/82393884-2b380280-9a7a-11ea-9e66-f7cca1dfdc32.png)

![image](https://user-images.githubusercontent.com/3724281/82393900-355a0100-9a7a-11ea-80be-71c9800a073b.png)

Perhaps if I have time later I can send another card json where the obfuscated values are all the same string value, so that in case there is compression going on, it will compress a bit better.

**Comment by Subhasish-msft** [comment]
@stpeteparadox , We have created a bug for this.

**Comment by stpeteparadox** [comment]
@Subhasish-msft 
To clarify, you mean a bug for messages exceeding the supposed card size limit, or the sluggish card behavior?

**Comment by Subhasish-msft** [comment]
@stpeteparadox ,Bug is for sluggish behavior.

**Comment by stpeteparadox** [comment]
@Gousia-MSFT why is this now closed? Remains very much open on our side... Would be ideal to have some communication from Microsoft side regarding issue resolution or what not before closing.

**Comment by Abhijit-MSFT** [comment]
@stpeteparadox, We will communicate it back in this discussion once the issue is fixed.
