### ISSUE TITLE
Creating Incoming Webhook and outgoing webhook

### ISSUE THREAD

**Issue by mdhruv1** [MicrosoftDocs/msteams-docs#1658]
The information is incomplete. What I would like a full working example step by step how I can use this. Just now I do not have all the information here.  Ideally you can say if in curl the webhook can be invoked this way this how you will configure it in teams. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90ff2a84-a8bc-9259-d37d-622b102df75b
* Version Independent ID: e3b53e27-2946-189c-623b-9df704ea8f12
* Content: [Post external requests to Microsoft Teams with incoming webhooks - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-incoming-webhook#feedback)
* Content Source: [msteams-platform/webhooks-and-connectors/how-to/add-incoming-webhook.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/webhooks-and-connectors/how-to/add-incoming-webhook.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **laujan**

**Comment by Gousia-MSFT** [comment]
@mdhruv1 Could you please check this document to see how to[ configure an incoming webhook to Team](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-incoming-webhook#remove-an-incoming-webhook-from-a-teams-channel)?

**Comment by mdhruv1** [comment]
Thanks for sharing. What I am missing is an example of the post or get of the webhook url

The document shows us the steps but not an example content . 

That is my challenge

Thanks
Dhruv

 from my iPad

**Comment by Gousia-MSFT** [comment]
@mdhruv1 Once you have the webhook url, you could use Fiddler/Postman to make a post inside Team. Could you please try [Sending messages to connectors and webhooks](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-using)

**Comment by Gousia-MSFT** [comment]
Please re-open if you still have any queries.
