### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by mdhruv1** [MicrosoftDocs/msteams-docs#1659]
Can we get example of this code in python and node. for this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a57254c9-963d-ea1d-ecaf-dd0e7913526c
* Version Independent ID: 610c8514-bd72-46cc-75f1-991e2242019b
* Content: [Rate limiting - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/rate-limit)
* Content Source: [msteams-platform/bots/how-to/rate-limit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/bots/how-to/rate-limit.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Nikitha-MSFT** [comment]
Currently we don't have examples in python/Node JS. We are discussing this with our team
