### ISSUE TITLE
Media playback not supported in MS Teams

### ISSUE THREAD

**Issue by nikosalexakis** [MicrosoftDocs/msteams-docs#1661]
Although MS announced the support on Adaptive cards 1.2, (https://developer.microsoft.com/en-us/microsoft-365/blogs/adaptive-cards-1-2-are-ga-in-microsoft-teams/)

when I tried to embed a video (which is supported in v1.1) it was not working in MS Teams
![image](https://user-images.githubusercontent.com/32068259/82207256-3112d400-9912-11ea-8b40-523dad943529.png)

You can try it with App Studio by using the example (https://adaptivecards.io/explorer/Media.html) 
```
{
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "type": "AdaptiveCard",
  "version": "1.1",
  "fallbackText": "This card requires Media to be viewed. Ask your platform to update to Adaptive Cards v1.1 for this and more!",
    "body": [
        {
            "type": "Media",
            "poster": "https://adaptivecards.io/content/poster-video.png",
            "sources": [
                {
                    "mimeType": "video/mp4",
                    "url": "https://adaptivecardsblob.blob.core.windows.net/assets/AdaptiveCardsOverviewVideo.mp4"
                }
            ]
        }
    ]
}
```
- the preview works
- sending the card throws the above error

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Cards Reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference#feedback)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Nikitha-MSFT** [comment]
Currently teams does not support media playback

**Comment by nikosalexakis** [comment]
Should it not be clearly stated in the documentation then?
"Teams supports Adaptive Cards 1.2 except of ..."

**Comment by Wajeed-msft** [comment]
Note is added to [Adaptive card](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference#adaptive-card) section.
