### ISSUE TITLE
Cannot send files with same file name

### ISSUE THREAD

**Issue by dchathu** [MicrosoftDocs/msteams-docs#1667]
A bot cannot send multiple files with the same file name (attachment name). File Consent Card will be sent to the user, but no message received by the bot if the user clicks "Allow". "OnTeamsFileConsentAcceptAsync" is not fired. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 294157df-f255-42c7-4e31-c9f0a9f0c3ea
* Version Independent ID: 25335b03-ad4a-d314-74f0-36284a922c3c
* Content: [Send and receive files - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/send-and-receive-files?tabs=dotnet#feedback)
* Content Source: [msteams-platform/bots/how-to/conversations/send-and-receive-files.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/bots/how-to/conversations/send-and-receive-files.md)
* Product: **msteams**
* GitHub Login: @clearab
* Microsoft Alias: **anclear**

**Comment by Nikitha-MSFT** [comment]
we are looking into this ssue. Get back to you soon

**Comment by TejaReddy0226** [comment]
Hi All,
I am facing the same issue can please provide the update on this as soon as possible. Previously it working fine now it is stopped working.

**Comment by Nikitha-MSFT** [comment]
Can you share console logs capturing the click on the button?

**Comment by TejaReddy0226** [comment]
Hi Nikitha,

Please find the images,

![Allow-for same file-1](https://user-images.githubusercontent.com/62458014/82536795-a676e280-9b66-11ea-86b2-a11d186c36f5.png)
![response from teams api for same file upload-1](https://user-images.githubusercontent.com/62458014/82536861-bb537600-9b66-11ea-891e-323749bd6d6a.PNG)

**Comment by TejaReddy0226** [comment]
Hi All,
Can you please give any update on this as your project is on Live and it is the high priority issue from the Users.

**Comment by Nikitha-MSFT** [comment]
We are looking into the issue, get back to you soon

**Comment by Sujit-Gaikwad** [comment]
Hi there,

I 'm also facing same issue while sending file with same name using bot can you please take look as it important feature for our bot

Thanks and regards,
Sujit Gaikwad

**Comment by vidyakdil** [comment]
Hi, we are facing the same issue with our bot.This used to work and was part of a potential feature of bot. This Could you please get us an update on the same.

**Comment by Deepti886** [comment]
Hi All,
Even I'm also facing the same issue and need to fix it on **high priority**. Please provide the solution as early as possible.

**Comment by VenkataBharghavP** [comment]
Hi there,
I 'm also facing same issue and wanted to get a resolution to it as early as possible. Ccan you please assist us in getting this done

**Comment by Nikitha-MSFT** [comment]
We have a work item for this requirement in our backlog we will be working on this next sprint.

**Comment by dchathu** [comment]
> We have a work item for this requirement in our backlog we will be working on this next sprint.

This was working! Even we had features deployed to production based on this. We had to deploy a hot fix to alleviate the issue. This is a bug.

**Comment by Sujit-Gaikwad** [comment]
@dchathu if this is bug will you consider this on high priority and resolve it. as it is effecting major functionality  in our bot we need solution as early as possible.

**Comment by Sujit-Gaikwad** [comment]
Any  Updates on this ?

**Comment by Nikitha-MSFT** [comment]
We are looking into it. We don't have ETA to share

**Comment by Sujit-Gaikwad** [comment]
Hi, 
Any updates on the above issue

**Comment by Nikitha-MSFT** [comment]
@dchathu - If you are still facing the issue, please feel free to reopen the issue
