### ISSUE TITLE
Teams Compliance Recording Application parameters not affecting

### ISSUE THREAD

**Issue by fadynag** [MicrosoftDocs/msteams-docs#1668]
We have created a Call Recording Bot and used it to evaluate Teams Compliance Call Recording Policy.
From the parameters of [New-CsTeamsComplianceRecordingApplication](https://docs.microsoft.com/en-us/powershell/module/skype/new-csteamscompliancerecordingapplication?view=skype-ps) I noticed that:
**-RequiredDuringMeeting** --> which cause, if this is set to True, the user will be ejected from the meeting if the policy-based recording application leaves the meeting or is dropped from the meeting.
**-RequiredDuringCall** --> which cause, If this is set to True, the call will be canceled if the policy-based recording application leaves the call or is dropped from the call.
So I initiated a Call / Meeting and during the session I power off the Bot bot but nothing happened.

Is it something missed in my configuration or in Bot Code?

**Comment by Subhasish-msft** [comment]
@fadynag , Did the bot drop from the call once you power off ?

**Comment by fadynag** [comment]
I didn't notice anything like that. How can I check?

**Comment by Subhasish-msft** [comment]
As per the doc : 

> If this is set to True, the call will be canceled if the policy-based recording application **leaves** the call or is **dropped** from the call.

So can you make sure that the bot drops/leaves the call when you are testing this.

**Comment by fadynag** [comment]
Actually what happened is call (users) continue in the call while we Power-off the Bot. so it seems nothing happened given that Parameters are set to True.

**Comment by Trinetra-MSFT** [comment]
@fadynag , The only entity that can detect whether a bot is alive or dead is the media processor, because it detects a lack of media packets from the bot and raises a media timeout after some time. The media timeout event then causes the bot's leg to get torn down, which then initiates the ejection of the user from the call / meeting.

**Comment by Abhijit-MSFT** [comment]
@fadynag, Please let us know if you still have any query. We will reopen the ticket
