### ISSUE TITLE
Debug your bot locally

### ISSUE THREAD

**Issue by Garviell** [MicrosoftDocs/msteams-docs#1669]
"Use the https endpoint provided by ngrok in your app manifest. "

What?  How?  There is no https endpoint in the MicrosoftTeams.schema.  Not on the root and not in bots?  This is very very unhelpful and very confusing.  Is this actually possible or do i have to deploy the thing whenever i want to test?

Everything in teams seems to revolve around the botId rather than any URLs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45ca0926-65fc-66a5-b881-5b99a589f2ec
* Version Independent ID: b9e40da9-1029-f65f-18b5-f450a8ea87d2
* Content: [Test and debug your bot locally - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/debug/locally-with-an-ide#feedback)
* Content Source: [msteams-platform/bots/how-to/debug/locally-with-an-ide.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/bots/how-to/debug/locally-with-an-ide.md)
* Product: **msteams**
* GitHub Login: @clearab
* Microsoft Alias: **anclear**

**Comment by Gousia-MSFT** [comment]
@Garviell You can locally debug your code using [ngrok](https://ngrok.com/download). Please follow the docs [here](https://docs.microsoft.com/en-us/microsoftteams/platform/tutorials/get-started-dotnet-app-studio#host-the-sample-app). This will give you a https url that you can use to connect to your application. 
![image](https://user-images.githubusercontent.com/45553518/82325428-dc965400-99f8-11ea-889d-3263f4a9a9c8.png)
You will then need to use this https url as the endpoint to your Bot. To do this please follow the steps here:
1. Login to the azure portal where you have created the bot.
2. Search for your Bot and open it.
3. Click on Settings and update your Bots messaging enpoint as: https://[Yourngrok]/api/messages and save.
![image](https://user-images.githubusercontent.com/45553518/82325704-4b73ad00-99f9-11ea-8176-fa87fd9f1668.png)
4. Add the https url in your application config file.
Your Bot will then start listening to this endpoint and you can debug it locally. You can use this ngrok url to add tabs inside your manifest as well.

**Comment by Garviell** [comment]
Yes thank you i figured that out shortly after giving that feedback.

You should probably update the docs I hightlighted though or just make them link to the other article.  Standing the way they are they are actively misleading
