### ISSUE TITLE
Question re getMembers vs fetchMembers

### ISSUE THREAD

**Issue by gmarotta** [MicrosoftDocs/msteams-docs#1670]
Looking through our code – we don’t use the TeamsInfo.getMembers method.
 
We do use fetchMembers from the botbuilder-teams NPM module
 
public fetchMembers(serviceUrl: string, conversationId: string, callback: (err: Error, result: ChannelAccount[]) =&gt; void) : void;
 
… and we use that to get the user’s name when they initiate a conversation with the bot and we don’t recognize them.  Outside of that call we don’t call any ‘get member’ type  API.
 
Is the above API analogous (or directly references) the getMembers on your backend or can we keep using it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c780d605-b1b2-716f-5888-503608769b5a
* Version Independent ID: 53c724f8-d9a2-4af6-6d75-ddeaef084137
* Content: [Bot API Changes for Team/Chat Members (2020 update) - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/team-chat-member-api-changes#feedback)
* Content Source: [msteams-platform/resources/team-chat-member-api-changes.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/resources/team-chat-member-api-changes.md)
* Product: **msteams**
* GitHub Login: @ojasvichoudhary
* Microsoft Alias: **ojchoudh**

**Comment by Trinetra-MSFT** [comment]
@gmarotta , Your can query for the list of team members and their basic profiles using [fetch members API](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bots-context#fetching-the-team-roster) & [Get Member](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/get-teams-context?tabs=typescript#get-single-member-details). could you please go through the [Bot API changes for fetching team/chat members](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/team-chat-member-api-changes)

**Comment by Trinetra-MSFT** [comment]
Please feel free to reopen if you have further query.
