### ISSUE TITLE
Still no adaptive cards

### ISSUE THREAD

**Issue by ganlbarone** [MicrosoftDocs/msteams-docs#1671]
Question 1:
For now it looks like only legacy cards are still supported over webhooks? So no adaptive still right?
Question 2:
Is there any way to add in headers into the http post so that you could do something like basic auth? I have never seen an example of that, and that would make that much more usable of an example if it was included.

thanks much.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28316a67-22fa-8a05-1ae0-fbe1c5720ef9
* Version Independent ID: 8a250e46-2a30-af86-839d-9f83a8b48041
* Content: [Sending messages to Connectors and Webhooks - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-using)
* Content Source: [msteams-platform/webhooks-and-connectors/how-to/connectors-using.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/webhooks-and-connectors/how-to/connectors-using.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Subhasish-msft** [comment]
@ganlbarone ,
1.  Connector are designed with limited functionality so it supports only message card for now. You can add a feature suggestion [here](https://aka.ms/microsoftteamsplatformsuggestions)

2. Currently there is no easy option available. If you go through the [Connector documentation](https://docs.microsoft.com/en-us/outlook/actionable-messages/security-requirements#verifying-that-requests-come-from-microsoft ), you’ll see that the ‘sub’ parameter contains the Azure AD object ID of the user who took the action. You could make use of it to validate if it is from a valid user or not by calling graph API.

**Comment by ganlbarone** [comment]
On question 2:

I was more so hoping to attach a button to an external system. Like for example ServiceNow. Close ticket or update ticket button would send a put request or post depending. But in order for that to work the cards really need to support basic auth. I think adaptive cards do no?

_______________________________
Louis Barone
Engineer II, Enterprise Client Support
Technology Support Services

[cid:image001.png@01D62E8B.B9BBC1F0]

Office: 212.715.2055
lbarone@gannett.com<mailto:lbarone@gannett.com>

Help Desk: 1-855-876-HELP
support@gannett.com<mailto:support@gannett.com>

gannett.com<http://www.gannett.com/>

Self-service password reset https://pwreset.gannett.com<https://pwreset.gannett.com/>

**Comment by Subhasish-msft** [comment]
Yes, Adaptive card has the feature. But that is currently not supported for webhooks.

**Comment by ganlbarone** [comment]
Any comment perhaps on the last part of this, taken from the below link. I read that last part as we can expect this to come to webhooks. I have been waiting for this feature for like 2 years so slightly frustrated that we still cant really utilize them. Hopefully from the below though that this is going to change sometime in the near future.

https://techcommunity.microsoft.com/t5/microsoft-teams-blog/what-s-new-in-microsoft-teams-build-edition-2020/ba-p/1394224



More powerful Adaptive Cards for Teams



Adaptive Cards with incoming webhooks are another highly requested Teams features. Full support for Adaptive Cards, including support for bot framework cards (hero, profile, lists, and more) will be available in preview coming soon.


_______________________________
Louis Barone
Engineer II, Enterprise Client Support
Technology Support Services

[cid:image001.png@01D62E8D.361A0670]

Office: 212.715.2055
lbarone@gannett.com<mailto:lbarone@gannett.com>

Help Desk: 1-855-876-HELP
support@gannett.com<mailto:support@gannett.com>

gannett.com<http://www.gannett.com/>

Self-service password reset https://pwreset.gannett.com<https://pwreset.gannett.com/>

**Comment by Subhasish-msft** [comment]
@ganlbarone , Apology for the previous comment, Adaptive card support in Incoming webhook is currently being developed and in testing phase. It will be available in **developer preview**  mode by **CY20Q3**.

**Comment by ganlbarone** [comment]
Awesome. I didn’t think id ever see the day but this is good. Thanks much.

_______________________________
Louis Barone
Engineer II, Enterprise Client Support
Technology Support Services

[cid:image001.png@01D62F4D.308D9260]

Office: 212.715.2055
lbarone@gannett.com<mailto:lbarone@gannett.com>

Help Desk: 1-855-876-HELP
support@gannett.com<mailto:support@gannett.com>

gannett.com<http://www.gannett.com/>

Self-service password reset https://pwreset.gannett.com<https://pwreset.gannett.com/>
