### ISSUE TITLE
Wrong link in MS Teams Admin Center

### ISSUE THREAD

**Issue by ediordna** [MicrosoftDocs/msteams-docs#1673]
On the page: [https://admin.teams.microsoft.com/policies/meetings/view](https://admin.teams.microsoft.com/policies/meetings/view) in the MS Teams Admin Center is a bug in the link to the further information for the section: "Participants & guests". The "further information" link should be to: [https://docs.microsoft.com/de-DE/microsoftteams/meeting-policies-in-teams?WT.mc_id=TeamsAdminCenterCSH#meeting-policy-settings---participants--guests](https://docs.microsoft.com/de-DE/microsoftteams/meeting-policies-in-teams?WT.mc_id=TeamsAdminCenterCSH#meeting-policy-settings---participants--guests). In reality it is to: [https://docs.microsoft.com/de-DE/microsoftteams/meeting-policies-in-teams?WT.mc_id=TeamsAdminCenterCSH#bkparticipantsandguests](https://docs.microsoft.com/de-DE/microsoftteams/meeting-policies-in-teams?WT.mc_id=TeamsAdminCenterCSH#bkparticipantsandguests)

**Comment by Wajeed-msft** [comment]
@ediordna - With latest dashboard, all the links seems to be up to date. Please re-open if you see any issues. 
![image](https://user-images.githubusercontent.com/31851992/93759264-81cf6c00-fc27-11ea-82f8-00d5fad4bf29.png)
