### ISSUE TITLE
App not working on teams but works fine on Teams site and on Developer Preview

### ISSUE THREAD

**Issue by Dangerous-Mind** [MicrosoftDocs/msteams-docs#1677]
I have a SPFx app on a site and created a Tab on the App studio pointing to the page the SPFx app is installed..
It works fine in Teams online (Browser) and in Teams Developer Preview.
But in the normal Teams App nothing appears on the screen.
There is no load, no call to the site to get the data... Nothing.

In the console It gives some error messages that are also in the other working versions (Developer Preview and Browser).
2020-05-20T15:41:30.136Z ChannelService: Empty threadId
2020-05-20T15:41:30.142Z ChannelService: Empty threadId

But it does nothing afterword's.

Since this is my first team app... Is this a new feature that is not yet available on App versions?

my manifest is:
```
{
    "$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.5/MicrosoftTeams.schema.json",
    "manifestVersion": "1.5",
    "version": "1.0.0",
    "id": "3a361f6c-e963-4185-9f6b-cc87cc30f58d",
    "packageName": "myTenantName.com",
    "developer": {
        "name": "My Name",
        "websiteUrl": "https://myTenantName.sharepoint.com/sites/Test251",
        "privacyUrl": "https://myTenantName.sharepoint.com/sites/Test251",
        "termsOfUseUrl": "https://myTenantName.sharepoint.com/"
    },
    "icons": {
        "color": "color.png",
        "outline": "outline.png"
    },
    "name": {
        "short": "App Name",
        "full": "App Description"
    },
    "description": {
        "short": "App Name",
        "full": "App Description"
    },
    "accentColor": "#FFFFFF",
    "staticTabs": [
        {
            "entityId": "3a361f6c-e963-4185-9f6b-cc87cc30f58d",
            "name": "App Name",
            "contentUrl": "https://myTenantName.sharepoint.com/sites/Test251",
            "websiteUrl": "https://myTenantName.sharepoint.com/sites/Test251",
            "scopes": [
                "personal"
            ]
        }
    ],
    "permissions": [
        "identity",
        "messageTeamMembers"
    ],
    "validDomains": [
        "myTenantName.sharepoint.com",
        "ServicesSupportingThisApp.azurewebsites.net"
    ]
}
```

**Comment by Trinetra-MSFT** [comment]
@Dangerous-Mind , Did you tried `Sync with Teams ` option in your sharepoint app catalog for the webpart you want load as tab in Teams desktop client?

**Comment by Dangerous-Mind** [comment]
Thanks for the reply @Trinetra-MSFT.

I had a lot off troubles making Sync to Teams. There was a bug that I as receiving stating permission denied. Also I could not see any apps on the teams Admin center. It was like this for over a month.
They managed to solve it some days ago. 

In the mean time I chose to use the app Studio to create a Tab pointing directly to the site were all the lists and libraries used by the app are. It seams to me as a better approach.

Yesterday, the Tab started working in normal teams mode. I think they made a update on to the Microsoft Teams Version 1.3.00.12058.

In a mac we still have the same problem but the user still has Microsoft Teams Version 1.3.00.9271.
We reinstalled Teams but the version still the same.

On mobile is working fine (on Android and iOS).

Is there a way to know the launched versions of Teams?

**Comment by Dangerous-Mind** [comment]
Hi, @Trinetra-MSFT,

I did some more testing.

If I'm in Developer Preview and switch to normal mode it works fine.
If I Quit teams or even restart the computer. It works fine in Normal mode also.
If I logout in normal mode the problem reappears and the Tab page is empty.

This happens both in mac and windows.

Apparently wen we login to Developer Preview we do a additional login information that is not available in Normal login. 
If we switch to Normal mode the information is still kept and used. But If we sign out this information is deleted and the problem reappears.

Can you check please?

**Comment by Trinetra-MSFT** [comment]
@Dangerous-Mind , We have forwarded your query to right channel. We will update you shortly.

**Comment by Dangerous-Mind** [comment]
Any news @Trinetra-MSFT? 

It's not a urgent matter in this app since the universe of people that will be using it is quite small and I can tell them to set the Teams do Developer Preview.

One other issue is that, in Teams mobile, the app does not appear to me unless I set it to Developer preview.

**Comment by StarfallV** [comment]
I am actually having the exact same problem like you. @Trinetra-MSFT I hope some news can be informed to us.

**Comment by Trinetra-MSFT** [comment]
@Dangerous-Mind , @StarfallV , could you please follow this document to create this app package? At first glance it's missing the webApplicationInfo section. We have pretty detailed documentation on all this here:
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/using-web-part-as-ms-teams-tab
 
And here in case you want to manually craft the manifest:
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/creating-team-manifest-manually-for-webpart

**Comment by Dangerous-Mind** [comment]
Hi @Trinetra-MSFT,

Thanks for your reply,

I'm using App Studio 1.4.0 from Microsoft to create the manifest. 
Also, I'm not pointing the manifest to the SPFx App. I'm pointing the tab directly to the site page were the app is. That's why the webApplicationInfo is not appearing. 
I don't think it needs the webApplicationInfo because it only renders the SharePoint Page. It does not know what's inside the page.
Also, it works fine on Developer preview.

Can you test with the manifest I've posted? It only has to point to a site page. In this case that's the default page of the site test251.
The "ServicesSupportingThisApp.azurewebsites.net" on the "validDomains" is a service supporting my app but you can remove it for a normal site page.

**Comment by Trinetra-MSFT** [comment]
@Dangerous-Mind , You need to add webApplicationInfo to load a sharepoint page in teams. webApplicationInfo requires your resource ULR which is basically your sharepoint URL and id which is sharepoint app_Id

```
  "webApplicationInfo": {
    "resource": "https://{teamSiteDomain}",
    "id": "00000003-0000-0ff1-ce00-000000000000"
  }

```
Could you please look at [create a Microsoft Teams manifest manually for a webpart and deploy](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/creating-team-manifest-manually-for-webpart)

**Comment by Dangerous-Mind** [comment]
Adding the webApplicationInfo didn't solve the problem.

On Teams DevTools I get some error messages on normal mode that I don't get on Developer Preview.

```
- main-855f81fc6d33ac21.js:1 AuthenticationService: Authentication - {"context":"Authentication::parseJWT","message":"Authentication::parseJWT::InvalidInput::{\"innerError\":{\"stack\":\"Error: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.\\n    at Sn (https://statics.teams.cdn.office.net/teams-modular-packages/hashed-assets/main-855f81fc6d33ac21.js:1:2927594)\\n    at https://statics.teams.cdn.office.net/teams-modular-packages/hashed-assets/main-855f81fc6d33ac21.js:1:2928615\"}}::isOnline-true","errorCode":"InvalidInput","Scenario.Status":"failure","Scenario.Step":"stop","Scenario.Name":"acquire_token"}
e.invoke @ main-855f81fc6d33ac21.js:1

- main-855f81fc6d33ac21.js:1 AuthTokenStoreService: Error occurred in keeping MT token active. Error: Authentication::parseJWT::InvalidInput::{"innerError":{"stack":"Error: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.\n    at Sn (https://statics.teams.cdn.office.net/teams-modular-packages/hashed-assets/main-855f81fc6d33ac21.js:1:2927594)\n    at https://statics.teams.cdn.office.net/teams-modular-packages/hashed-assets/main-855f81fc6d33ac21.js:1:2928615"}}::isOnline-true
    at s (main-855f81fc6d33ac21.js:1)
    at Bt (main-855f81fc6d33ac21.js:1)
    at e.createAndLogAuthError (main-855f81fc6d33ac21.js:1)
    at e.<anonymous> (main-855f81fc6d33ac21.js:1)
    at vendors-a6d39334ff0baa00.js:1
    at Object.throw (vendors-a6d39334ff0baa00.js:1)
    at u (vendors-a6d39334ff0baa00.js:1)
```

**Comment by Dangerous-Mind** [comment]
Forget it. I have the same messages on Developer Preview. It appeared on another DevTools window.

The html of the app appear like this on Normal mode. The iframe is empty.

```
<body>
  <div class="extension-tab">
    <iframe id="extension-tab-frame" class="extension-tab-frame" name="extension-tab-frame" src="https://myContoso.sharepoint.com/sites/mySIteCollection/sitepages/home.aspx" frameborder="0" sandbox="allow-forms allow-modals allow-popups allow-pointer-lock allow-scripts allow-same-origin allow-downloads" allow="geolocation *; microphone *; camera *; midi *; encrypted-media *;" allowfullscreen="">
       <html>
         <head></head>
         <body></body>
       </html>
    </iframe>
  </div>

</body>
```

**Comment by Wajeed-msft** [comment]
@Dangerous-Mind - In case if you are still stuck with this issue. Could you please check if [this answer](https://stackoverflow.com/questions/57593508/sharepoint-page-not-loading-in-personal-tab-of-static-app-ms-teams-desktop-clie/57770834#57770834) helps.

**Comment by Dangerous-Mind** [comment]
Hi @Wajeed-msft,

Yup it solved the issue.

Here is part of the manifest after the change.

```
    "staticTabs": [
        {
            "entityId": "cb6e8296-c5fc-41cf-9d9b-b6b1f3d697a7",
            "name": "Tab Name",
            "contentUrl": "https://myTenantName.sharepoint.com/sites/Test251/_layouts/15/teamslogon.aspx?spfx=true&dest=/sites/Test251/sitepages/home.aspx",
            "websiteUrl": "https://myTenantName.sharepoint.com/sites/Test251",
            "scopes": [
                "personal"
            ]
        }
    ],
    "validDomains": [
        "myTenantName.sharepoint.com",
        "ServicesSupportingThisApp.azurewebsites.net",
	"*.login.microsoftonline.com",
	"microsoft.sharepoint.com",
	"microsoft.sharepoint-df.com",
	"spoppe-a.akamaihd.net",
	"spoprod-a.akamaihd.net",
	"resourceseng.blob.core.windows.net",
	"msft.spoppe.com"
    ],
    "webApplicationInfo": {
        "resource": "https://myTenantName.sharepoint.com",
        "id": "00000003-0000-0ff1-ce00-000000000000"
    }
```

Thanks for your help.
