### ISSUE TITLE
MSAL?

### ISSUE THREAD

**Issue by aaronrogers** [MicrosoftDocs/msteams-docs#1678]
Does MSAL work as well?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2e66ffa-ec00-4a84-a43d-d47e3c138b32
* Version Independent ID: 47e9a383-ac6a-dc7d-2d91-a9e09626fdab
* Content: [Silent authentication - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-silent-aad)
* Content Source: [msteams-platform/tabs/how-to/authentication/auth-silent-aad.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tabs/how-to/authentication/auth-silent-aad.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Trinetra-MSFT** [comment]
@aaronrogers , Could you please look at[https://github.com/nmetulev/teams-msal]( https://github.com/nmetulev/teams-msal)?

**Comment by aaronrogers** [comment]
Thanks for the reference!  It seems easier and cleaner than ADAL.  The only thing lacking is a Sign Out example.

**Comment by Trinetra-MSFT** [comment]
Please feel free to reopen if you have further query.
