### ISSUE TITLE
Create Online Meeting API returns audioConferencing and videoTeleconferenceId as null

### ISSUE THREAD

**Issue by Trinetra-MSFT** [MicrosoftDocs/msteams-docs#1683]
I'm using Create Online Meeting API : https://docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-1.0&tabs=http, in the response object their is `audioConferencing `which should be populated with the appropriate meeting details as per documentation: https://docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-1.0&tabs=http#response-1 but when I'm trying to call the API in graph explorer, the same fields is getting null and also `videoTeleconferenceId`.
![image](https://user-images.githubusercontent.com/50989436/82544880-6cf8a400-9b73-11ea-91e5-d23dc126b971.png)
Does anyone know the reason for this?

**Comment by Subhasish-msft** [comment]
@Trinetra-MSFT , User need to have **Audio Conferencing license** for audioConferencing and videoTeleconferenceId coordinates. Also keep in mind, these licences take time to propagate across the tenant.

**Comment by Trinetra-MSFT** [comment]
Thanks @Subhasish-msft  for your explanation
