### ISSUE TITLE
MessageCard type

### ISSUE THREAD

**Issue by SarkhanO** [MicrosoftDocs/msteams-docs#1689]
MessageCard is in the example:
"@type": "MessageCard"
but MessageCard not listed in Types of cards. Could not find any info about MessageCard. Also Search feature does not find anything. Even this "MessageCard" in example

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28316a67-22fa-8a05-1ae0-fbe1c5720ef9
* Version Independent ID: 8a250e46-2a30-af86-839d-9f83a8b48041
* Content: [Sending messages to Connectors and Webhooks - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-using#feedback)
* Content Source: [msteams-platform/webhooks-and-connectors/how-to/connectors-using.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/webhooks-and-connectors/how-to/connectors-using.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Nikitha-MSFT** [comment]
MessageCard is not a type of card. We will use MessageCard as type for O365 card. You can see O365 card in type of cards Could you please go through the docs [here](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference#types-of-cards)?

**Comment by SarkhanO** [comment]
So "MessageCard" is a type for O365 or it is not a type?
O365 is described in the page you provided, but there is no mention of "MessageCard" value of "@type" property, and it's not clear whether I should use it and how

**Comment by Nikitha-MSFT** [comment]
Yes, "MessageCard" is a type for O365 card. Could you please go through the [O365 connector](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference#office-365-connector-card) card example?
