### ISSUE TITLE
there was a problem with reaching this app

### ISSUE THREAD

**Issue by essadji** [MicrosoftDocs/msteams-docs#1691]
I'm unable to reach my custom tabs. Whatever I try, I keep getting: "there was a problem with reaching this app". I've tried every suggestion in every FAQ I could find. Simple browser is able to reach the sites without any trouble. Please help!

**Comment by Subhasish-msft** [comment]
@essadji, Can you please try opening the tab in Teams web client and share the error you get in the developer console.

**Comment by Gousia-MSFT** [comment]
Please re-open if you still have any queries here.
