### ISSUE TITLE
again and again Message - "Try again."

### ISSUE THREAD

**Issue by MABLion** [MicrosoftDocs/msteams-docs#1692]
Opening MS Teams causes an error. The message is "Try again."
![1](https://user-images.githubusercontent.com/65893403/82798957-ee0caf80-9e81-11ea-9720-7535b47bfff3.png)

A complete reinstall did not help.
Deleted, deleted all folders Teams from % AppData%.
Fresh client from the Microsoft site. After installation - the same message.
I wonder why the error code is not displayed at the bottom left! ??? 
When this message window active I tried to press Ctrl+Alt+Shift+1, nothing happens, the download folder is empty.

How can I force detailed logs to be created?

**Comment by MABLion** [comment]
Add file logs.
[logs3.txt](https://github.com/MicrosoftDocs/msteams-docs/files/4676735/logs3.txt)

**Comment by Subhasish-msft** [comment]
@MABLion , Thanks for reporting the issue. I have created an incident for this issue. Will get back to you if more details are needed.

**Comment by Subhasish-msft** [comment]
@MABLion , Can you please share below details needed for ICM 
--------------------------------------------------------------------------------------------------------
1. Enable verbose Desktop auth Logging:
Location For Hooks File: Windows- %appdata%\Microsoft\Teams\hooks.json
Location For Hooks File: Mac - ~\Library\Application Support\Microsoft\Teams\hooks.json
If the file is not found, create a new file and name it hooks.json.

Paste the following to the hooks file.
{"enableSsoLog": true}
--------------------------------------------------------------------------------------------------------
2. OS version:
For Windows
Press Win + R and run winver to open the following window and report the OS version
--------------------------------------------------------------------------------------------------------
3. Desktop Settings and Configs

Windows
desktop configuration - %appdata%\Microsoft\Teams\desktop-config.json
settings - %appdata%\Microsoft\Teams\settings.json
local storage - %appdata%\Microsoft\Teams\storage.json

--------------------------------------------------------------------------------------------------------
4. TEAMS WEBCLIENT LOGGING
Run scenarios and press : Ctrl+Alt+Shift+1
Click on Files -> Downloads, you should see the logs there.
