### ISSUE TITLE
Deprecated example

### ISSUE THREAD

**Issue by xieofxie** [MicrosoftDocs/msteams-docs#1693]
![image](https://user-images.githubusercontent.com/2876650/82874760-03103e00-9f69-11ea-83d2-fba71e55d3e8.png)

 Microsoft.Bot.Connector.Teams is deprecated.

And in python language, it has already used updated version described here https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-proactive-message?view=azure-bot-service-4.0&tabs=csharp

We should update the C# example

Also..

Why the github plugin has changed? We used to have github issues shown under the document, and now they are gone..

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ad9f167-7d29-f933-7b47-60bd744899b1
* Version Independent ID: 8097fcbd-adcc-ce49-a378-426c65af9296
* Content: [Send proactive messages - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/send-proactive-messages?tabs=dotnet)
* Content Source: [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/bots/how-to/conversations/send-proactive-messages.md)
* Product: **msteams**
* GitHub Login: @clearab
* Microsoft Alias: **anclear**

**Comment by Trinetra-MSFT** [comment]
Similar doc-bug #1585

**Comment by KirtiPereira** [comment]
Closing this issue as confirmed by SME that the document is already updated. No updates are required.
