### ISSUE TITLE
message type for hero cards is wrong

### ISSUE THREAD

**Issue by comtom** [MicrosoftDocs/msteams-docs#1696]
"contentType": "application/vnd.microsoft.card.hero",

raises a 400 with this payload:
{
    "error": {
        "code": "BadArgument",
        "message": "Unknown activity type"
    }
}

which are the correct types? please fix your docs, is very annoying trying things described there that don't work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Cards Reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Abhijit-MSFT** [comment]
@comtom, Share your card json, let me try it. The doc example json works fine.

**Comment by comtom** [comment]
> @comtom, Share your card json, let me try it. The doc example json works fine.

How are you testing it? From app studio it works, but when I send it to the activities endpoint it gives me these errors, only text messages are working

**Comment by comtom** [comment]
hi, any news from here?

I tried to wrap the payloads that sent earlier an attachment property: 
{
        "type": "message",
        "attachments": [{
           ... }]
}

so full payload now looks like:
{
    "type": "message",
    "attachments": [
        {
            "contentType": "application/vnd.microsoft.card.hero",
            "content": {
                "title": "Hero Card",
                "subtitle": "Subtitle",
                "text": "Text",
                "images": [
                    {
                        "url": "https://statics.teams.cdn.office.net/evergreen-assets/apps/teams_dev_app_largeimage.png"
                    }
                ],
                "buttons": [
                    {
                        "type": "openUrl",
                        "title": "Button 1",
                        "value": "https://www.microsoft.com"
                    },
                    {
                        "type": "openUrl",
                        "title": "Button 2",
                        "value": "https://www.azure.com"
                    }
                ]
            }
        }
    ]
}

I'm getting 400 errors as well with these payloads. with the message {"error":{"code":"BadArgument","message":"Unknown activity type"}}

**Comment by comtom** [comment]
Example payloads should be inside an attachment element like so:

`
{
        "type": "message",
        "attachments": [{ "contentType": "application/vnd.microsoft.card.hero", "content": { "title": "Hero Card", "subtitle": "Subtitle", "text": "Text", "images": [{ "url": "https://statics.teams.cdn.office.net/evergreen-assets/apps/teams_dev_app_largeimage.png" }], "buttons": [{ "type": "openUrl", "title": "Button 1", "value": "https://www.microsoft.com" }, { "type": "openUrl", "title": "Button 2", "value": "https://www.azure.com" }] } }
]}

Please change your sample payloads, so full payloads are display in the documentation. Is so confusing if you only show a portion.
