### ISSUE TITLE
Deep link from list card not working

### ISSUE THREAD

**Issue by abbodh** [MicrosoftDocs/msteams-docs#1698]
Looks like deep-link to team channel tab does not work on ListCard button:
 

Created the action button on ListCard like below:

                  new AdaptiveOpenUrlAction
                 {
                     Title = "Title",
                     Url = new Uri("Url"),
                 });
ListCard ContentType = "application/vnd.microsoft.teams.card.list" then it is opening a new browser tab, if running teams in browser.
 

Rather than ListCard, if we create a Adaptive Card with same button action with card ContentType = "application/vnd.microsoft.card.adaptive" it is working fine.

Is this a known issue or am I missing something?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45541337-ecd7-5cf6-cbe4-3f0d2f39aa79
* Version Independent ID: 6b4203f0-2844-06c9-eaa3-9cc03e6f76c0
* Content: [Create deep links - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links)
* Content Source: [msteams-platform/concepts/build-and-test/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/build-and-test/deep-links.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Subhasish-msft** [comment]
@abbodh , For List card action, You should not use AdaptiveOpenUrlAction. Instead you shoul use below code 

```
card.content.buttons = new ListButton[] {
                new ListButton() {
                type = "openUrl",
                value = url,
                title = "Click",
            }
            }; 
```
ListButton Class

```
public class ListButton
    {
        public string type { get; set; }
        public string title { get; set; }
        public string text { get; set; }        
    }
```
You can refer to the doc [here](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference#list-card)

**Comment by aosolis** [comment]
No, please use a normal `CardAction`. Buttons on cards that are not adaptive cards all use `CardAction`.
