### ISSUE TITLE
Teams Hello World Sample not running in Desktop App

### ISSUE THREAD

**Issue by PascalS86** [MicrosoftDocs/msteams-docs#1699]
Hi,

Maybe this is the wrong repo, but Maybe you can help me.
I'm trying to get my Teams App up running in the desktop app.
I can deploy it, I can uplaod it and in the web app it's running fine.

But in the desktop app my custom tabs aren't showing content (they are there, but empty).

I started from the hello world sample and just changed some page and the js to load one specific tab instead of configuring it.

If you can give me some info, that would be awesome.

thanks.

**Comment by Abhijit-MSFT** [comment]
@PascalS86, Do you mean app is working fine in Teams web client and same app is not working on Teams Desktop client?
Please check your ngrok, if you are getting any error message when on desktop client

**Comment by PascalS86** [comment]
Hi, 
thanks for the info.

Yes, it's working fine in the web client but not in the desktop client.

But ngrok is not getting an error. 

Is there something special about the manifest, I have to consider setting it up?
```json
{
    "$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.6/MicrosoftTeams.schema.json",
    "manifestVersion": "1.6",
    "version": "1.0.0",
    "showLoadingIndicator": false,
    "id": "[valid id]",
    "packageName": "[PackageName]",
  "developer": {
    "name": "[Name]",
    "websiteUrl": "[websiteUrl]",
    "privacyUrl": "[privacyUrl]",
    "termsOfUseUrl": "[termsOfUseUrl]"
  },
    "icons": {
        "color": "color.png",
        "outline": "outline.png"
    },
  "name": {
    "short": "[Company].Teams.Demo",
    "full": "[Company].Teams.Demo"
  },
    "description": {
        "short": "short",
        "full": "This sample app provides a very simple app. You can extend this to add more content and capabilities."
    },
    "accentColor": "#60A18E",
    "configurableTabs": [
      {
        "configurationUrl": "https://13556140.ngrok.io/configure",
        "canUpdateConfiguration": true,
        "scopes": [
          "team"
        ]
      }
    ],
    "staticTabs": [
      {
        "entityId": "[Company].Teams.Demo",
        "name": "Demo Tab",
        "contentUrl": "https://13556140.ngrok.io/",
        "scopes": [
          "personal"
        ]
      }
    ],
    "permissions": [
        "identity",
        "messageTeamMembers"
    ],
  "validDomains": [
    "13556140.ngrok.io"
  ]
}
```

**Comment by PascalS86** [comment]
just to clairify, the square brakekts are just placeholders :)

**Comment by Abhijit-MSFT** [comment]
Try this manifest json

`{
  "$schema": "https://developer.microsoft.com/json-schemas/teams/v1.5/MicrosoftTeams.schema.json",
  "manifestVersion": "1.5",
  "version": "1.0.0",
  "id": "6afb1380-xxx-xxxx-xxxx-dd3286344xxx",
  "packageName": "com.contoso.helloworld",
  "developer": {
    "name": "Contoso",
    "websiteUrl": "https://www.yourcompanydomain.com",
    "privacyUrl": "https://www.yourcompanydomain.com/privacy",
    "termsOfUseUrl": "https://www.yourcompanydomain.com/termsofuse"
  },
  "name": {
    "short": "App name",
    "full": "App full name"
  },
  "description": {
    "short": "App description",
    "full": "App full description."
  },
  "icons": {
    "outline": "outline.png",
    "color": "logo.png"
  },
  "accentColor": "#60A18E",
  "staticTabs": [
    {
      "entityId": "entitiyID",
      "name": "TabName",
      "contentUrl": "https://yourdomain.com",
      "websiteUrl": "https://yourdomain.com",
      "scopes": [
        "personal"
      ]
    }
  ],
  "bots": [
    {
      "botId": "6afb1380-xxx-xxxx-xxxx-dd3286344xxx",
      "scopes": [
        "team",
        "groupchat"
      ]
    }
  ],
  "composeExtensions": [
    {
      "botId": "6afb1380-xxx-xxxx-xxxx-dd3286344xxx",
      "canUpdateConfiguration": false,
      "commands": [
        {
          "id": "you_ID",
          "description": "description",
          "title": "Title",
          "type": "action",
          "initialRun": false,
          "context": [ "message" ],
          "fetchTask": true,
          "parameters": [
            {
              "name": "Name",
              "title": "Title",
              "description": "To Do Title"
            }
          ]
        }
      ]
    }
  ],
  "permissions": [
    "identity",
    "messageTeamMembers"
  ],
  "validDomains": [ "*.ngrok.io" ]
}
`

**Comment by PascalS86** [comment]
Ok thanks, I'll give it a try.
But isn't that an older version of the schema?

**Comment by PascalS86** [comment]
Hi, this doesn't solve the problem.

In VS 2019 I can debug my teams app, when I call it from the web client. but it's not hitting the breakpoints or logs. 

Still I don't get an error in the eventlog or in ngrok or in my service.

Do I need a specific version of the desktop client? or is there anything else?

**Comment by PascalS86** [comment]
Ok, I figured it out.

It was certificate problem. I didn't use localhost for debugging, I used my hostname. and for that, the certificate wasn't valid.  I changed that and I also add a website url (but I'm sure, that's not necessary). And voila, it's running and showing up
