### ISSUE TITLE
Blank content for adaptive cards in carousel layout.

### ISSUE THREAD

**Issue by Navega** [MicrosoftDocs/msteams-docs#1701]
We use a carousel layout to send a list of pending tasks (in adaptive cards), the problem is that 1st time chat is opened the card is empty and it is fixed when you move between different chats and go back.

This is a video where you can see the problem, the platform is Google Chrome (Version 81.0.4044.138 (Official Build) (64-bit) ) but it happens in any platform (browser or native app):

- https://recordit.co/ByLVnPxC74

And this is an example of json (extracted of [this documentation](https://docs.microsoft.com/en-us/adaptive-cards/getting-started/bots)) that you can use to reproduce the problem:

```
{
        "type": "message",
	"text": "test message",
	"locale": "en-US",
	"attachments": [{
		"contentType": "application/vnd.microsoft.card.adaptive",
		"content": {
			"type": "AdaptiveCard",
			"version": "1.0",
			"body": [{
				"type": "TextBlock",
				"text": "Hello World!",
				"size": "large"
			}, {
				"type": "TextBlock",
				"text": "*Sincerely yours,*"
			}, {
				"type": "TextBlock",
				"text": "Adaptive Cards",
				"separation": "none"
			}],
			"actions": [{
				"type": "Action.OpenUrl",
				"url": "http://adaptivecards.io",
				"title": "Learn More"
			}]
		}
	}, {
		"contentType": "application/vnd.microsoft.card.adaptive",
		"content": {
			"type": "AdaptiveCard",
			"version": "1.0",
			"body": [{
				"type": "TextBlock",
				"text": "Hello World!",
				"size": "large"
			}, {
				"type": "TextBlock",
				"text": "*Sincerely yours,*"
			}, {
				"type": "TextBlock",
				"text": "Adaptive Cards",
				"separation": "none"
			}],
			"actions": [{
				"type": "Action.OpenUrl",
				"url": "http://adaptivecards.io",
				"title": "Learn More"
			}]
		}
	}],
	"attachmentLayout": "carousel"
}
```

This isn't a recent problem but, now, we know that this is the way to reproduce. Let me know if you need something else.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Cards Reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Nikitha-MSFT** [comment]
we Could not reproduce the issue on our side. Could you please share your manifest?

**Comment by Navega** [comment]
> we Could not reproduce the issue on our side. Could you please share your manifest?

I just sent the manifest to Microsoft Teams developer support (microsoftteamsdev@microsoft.com), let me know if you need something else.

And please, to reproduce the issue, notice that the issue happens when you combine a "carousel" layout with "adaptive" cards.

**Comment by Nikitha-MSFT** [comment]
We Could able to reproduce the issue, Raised a bug

**Comment by pablodiazgutierrez** [comment]
Thank you @Nikitha-MSFT for looking into this. Do you know if any progress is being made toward a fix?

**Comment by Gousia-MSFT** [comment]
@pablodiazgutierrez We are tracking this internally. Currently we do not have an ETA for the fix to share with you.

**Comment by pablodiazgutierrez** [comment]
Thanks for the heads up!

-Pablo

**Comment by Nikitha-MSFT** [comment]
@pablodiazgutierrez - Are you still facing the issue? Could you please check on the latest version and update?
