### ISSUE TITLE
[Desktop] List Card scroll option is not available

### ISSUE THREAD

**Issue by Sujit-Gaikwad** [MicrosoftDocs/msteams-docs#1702]
Hi, I am using a List card to show details of different search results, the card is getting rendered properly but I'm not able to scroll the item on desktop as there is no scroll bar available for the card.

I'm able to scroll this using the mouse scroll button.

please help

here is the card payload
[ListCard.txt](https://github.com/microsoft/AdaptiveCards/files/4503775/ListCard.txt)

**Desktop view :**
![WhoBottList_card1](https://user-images.githubusercontent.com/60354515/83096067-6661b380-a0c2-11ea-855b-3ff2f7b53e1a.PNG)

![WhoBottList_card2](https://user-images.githubusercontent.com/60354515/83096064-65308680-a0c2-11ea-8d68-c2e13b1954c9.PNG)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Cards Reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Trinetra-MSFT** [comment]
@Sujit-Gaikwad , This is by design, There is mouse scroll in the list card.

**Comment by Sujit-Gaikwad** [comment]
>>@Sujit-Gaikwad , This is by design, There is mouse scroll in the list card.
@Trinetra-MSFT ,
I didn't get you completely please correct me if I'm wrong,

1.  do you mean that as per list card design we should use mouse scroll as we won't get scroll bar
     there.
       If yes then,
       **How users who are working on laptop and doesn't have mouse suppose to scroll the card.**

or  2. you mean that there is property for list card using that we can add scroll bar to it or 
         **if I am using any related property then please can you highlight it.**

Regards,
Sujit Gaikwad
