### ISSUE TITLE
How to enable microphone in teams manifest 

### ISSUE THREAD

**Issue by rajdeep0411** [MicrosoftDocs/msteams-docs#1703]
I want to enable microphone for enabling speech in my bot in teams. How can I enable it ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f94a488-d636-92b3-21eb-c88744c8f272
* Version Independent ID: 7b3413f4-9ade-accf-5cb2-83fead11a32a
* Content: [Manifest schema reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema)
* Content Source: [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/resources/schema/manifest-schema.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Abhijit-MSFT** [comment]
@rajdeep0411 - Update your manifest by adding "devicepermission" property. Please check [documentations](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/native-device-permissions) for more details.
