### ISSUE TITLE
App Studio manifest.json import error

### ISSUE THREAD

**Issue by abpatel** [MicrosoftDocs/msteams-docs#1705]
Following along the exercises from https://docs.microsoft.com/en-us/learn/modules/msteams-conversation-bots/3-exercise-conversation-bots
When trying to import the manifest.json file generated by Yeoman, I get the following message from AppStudio "Please fix these validation errors and try importing again". The thing is that there are no errors displayed in the dialog.
The manifest file is attached (as .txt) for reference.
Not sure what I'm doing wrong.

Also, it would be super helpful to have the mslearn samples in C# and the yeoman generator to support creating csproj files for folks who work primarily in C# are not familiar with nodejs. 
[manifest.txt](https://github.com/MicrosoftDocs/msteams-docs/files/4698712/manifest.txt)

**Comment by Gousia-MSFT** [comment]
@abpatel Could you please try copying the error details and see what exactly is the error? Please share a screenshot of the issue.

**Comment by abpatel** [comment]
There are no specific errors , just this dialog.
![image](https://user-images.githubusercontent.com/3915650/83298376-2f1a0200-a1a9-11ea-9cbc-0098ea6d3bda.png)

**Comment by Gousia-MSFT** [comment]
@abpatel I could not repro the issue with your manifest. I have replaced the url's and bot id and installed it. Could you please confirm if all the URL's you are trying to add are https and also share the complete manifest if you still face the issue.

**Comment by Gousia-MSFT** [comment]
Please re-open if you still face the issue.
