### ISSUE TITLE
Mentioning something that doesn't exist in SDK

### ISSUE THREAD

**Issue by manuartero** [MicrosoftDocs/msteams-docs#1707]
This page is referencing a method called `startReplyChain()` for starting new threads instead of replying to prev. threads that doesn't exit in the SDK (i've searched in the whole `node_modules` folder and in the sample code you provide at [Github](https://github.com/Microsoft/BotBuilder-Samples/blob/master/README.md)

- Did that method (`startReplyChain()`) used to exist in older versions of the SDK?
- If so, which is the new preferred way of starting new thread chains?
- Update the doc anyway ^^

I'd like to take the chance if someone from Microsoft Teams take a look to this to refer this [question from StackOverflow](https://stackoverflow.com/questions/62080986/microsoft-bot-node-sdk-how-to-post-to-a-public-channel-without-replying-to-a) if you don't mind

thanks.

============
> Your team-added bot can post into a channel to create a new reply chain. If you're using the Node.js Teams SDK, use startReplyChain() which gives you a fully-populated address with the correct activity id and conversation id.

============
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b6940fc-c82e-4ef1-c913-976ede8a9d3f
* Version Independent ID: cbec2989-ba19-4046-21a1-72e2dca67f4d
* Content: [Proactive messages - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bot-conversations/bots-conv-proactive)
* Content Source: [msteams-platform/resources/bot-v3/bot-conversations/bots-conv-proactive.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/resources/bot-v3/bot-conversations/bots-conv-proactive.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by ChetanSharma-msft** [comment]
Hello @surbhigupta12 - Please help us to add the code snippets for NodeJS as we have added for C#:

Reference code:
https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/main/samples/app-task-module/nodejs/src/utils/MessageUtils.ts#L175

Doc section to be updated:
https://learn.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bot-conversations/bots-conv-proactive?tabs=http#examples-for-creating-a-channel-conversation
