### ISSUE TITLE
Trigger notifications

### ISSUE THREAD

**Issue by Mihael479** [MicrosoftDocs/msteams-docs#1708]
I couldn't find if msteams javascript sdk has abillity to show notifications like when you receive messages. If there is a way can someone show me example or code and if this does not exist yet, is it possible to have it in future?

**Comment by Trinetra-MSFT** [comment]
@Mihael479 , Could you please from where you want to send the notifications? is it Tab or Bot?
Sending notification through tab is not supported scenario as Teams client SDK don't support this. But you can sent notification using Bot

**Comment by Trinetra-MSFT** [comment]
Please feel free to reopen if you further query

**Comment by MihaelBlazek** [comment]
I would like to send notification from Tab. I have a chat application in tab to communicate between teams and our web apps using signal. What I want to do is show notification when message arrives to teams user just like in normal chat. Is it possible? Thank you.
