### ISSUE TITLE
Issue with version control and edits reverting in PowerPoint decks stored in Teams

### ISSUE THREAD

**Issue by ssshah621** [MicrosoftDocs/msteams-docs#171]
The root cause of this issue may lie in SharePoint or PowerPoint so apologies if its not directly Teams-related. 

When editing a slide deck in PowerPoint that is launched from Teams, an issue frequently occurs when text and images from a previous iteration of the deck (say 10-15 minutes prior) are pasted on top of the latest version. Thus, information from a previous version is superimposed on the latest version (or in some instances, replaces the text in the latest version). This makes it very difficult to determine what changes have been made in the deck when multiple people are working on it. This issue sometimes occurs when editing the slide (so you can see this old content automatically get pasted and superimposed) and sometimes occurs when you are editing a different slide. 

Additionally, slides are sometimes automatically duplicated. This interferes greatly with the process of building slide decks, given that version control is compromised.

**Comment by billbliss** [comment]
This is indeed a sync issue in SharePoint and as far as we know does not happen consistently.

**Comment by ssshah621** [comment]
Hello Bill,

Thank you for following up on this matter. I am not sure how you have reached this conclusion but I wanted to let you know that this does happen very consistently. In my organization, people report this issue on a daily basis and have tried several workarounds to no avail.

Is there an update being released to remedy this bug?
