### ISSUE TITLE
Can I do call microsoftTeams.tasks.submitTask(customerInfo, "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"); on backend C# side?

### ISSUE THREAD

**Issue by Dmitresky** [MicrosoftDocs/msteams-docs#1711]
I want to avoid pass appId on the client-side. I am looking for any possibility do submit Task Module on the backend C# side. 
Using an adaptive card is not a good choice for me. 
Do you have something like Microsoft Teams JavaScript client SDK, but for C#?
Or some API call to do that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f40d5208-a7ae-330a-1365-9b774ca9dcaf
* Version Independent ID: a44e2980-4ed7-636c-0141-8b1e944971bb
* Content: [Using Task Modules in Microsoft Teams tabs - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/task-modules/task-modules-tabs)
* Content Source: [msteams-platform/task-modules-and-cards/task-modules/task-modules-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/task-modules/task-modules-tabs.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Abhijit-MSFT** [comment]
@Dmitresky - Can you please explain me your application scenario. I will be in better position to help you.

**Comment by Dmitresky** [comment]
I am just wondering if it is possible to submit Task Module on backend side from C#. But for now, it doesn't matter because we have called `microsoftTeams.tasks.submitTask(customerInfo)` without appId and it works! Awesome!
