### ISSUE TITLE
[iPhone]Hero card action click not supporting on iOS device

### ISSUE THREAD

**Issue by Sujit-Gaikwad** [MicrosoftDocs/msteams-docs#1712]
Hi,

I am having trouble with the herocard with "imback" action click. It is not supported on the iPhone device.
It is working fine for Android and desktop teams versions.
please help

I am using 
iPhone X 
    teams version : 2.0.10
    iOS version : 13.4.1
iPhone 6
    teams version 2.0.10
    iOS version 12.4.5

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Cards Reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Trinetra-MSFT** [comment]
@Sujit-Gaikwad , We have filed a bug for this issue. We will update you once it is fixed.

**Comment by Trinetra-MSFT** [comment]
@Sujit-Gaikwad , This issue has been fixed on the latest iOS store build version 2.0.11. Please test it out there and let us know if you are still facing any issues. Also, the type is "imBack", please ensure you use the correct syntax.

**Comment by Trinetra-MSFT** [comment]
Please feel free to reopen if you have further query
