### ISSUE TITLE
Button styles are overridden as "default" outside a Container and as "positive" inside a Container

### ISSUE THREAD

**Issue by nikosalexakis** [MicrosoftDocs/msteams-docs#1714]
Hi, 

I noticed that button styles are not working for both:
 - Actions
 - Inline buttons

All buttons are using "default" styling, even if style is set to "positive" or "destructive"
Furthermore if **Inline buttons are inside a 'Container'** then their style is forced to **"positive"**.

I created 2 examples:

### Buttons outside a 'Container'
```
{
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "type": "AdaptiveCard",
  "version": "1.2",
  "body": [
    {
      "type": "Container",
      "items": [
        {
          "type": "TextBlock",
          "wrap": true,
          "text": "Cards can have action sets in the middle of their body."
        }
      ]
    },
    {
      "type": "ActionSet",
      "actions": [
        {
          "type": "Action.Submit",
          "title": "Default",
          "style": "default"
        },
        {
          "type": "Action.Submit",
          "title": "Positive",
          "style": "positive"
        },
        {
          "type": "Action.Submit",
          "title": "Destructive",
          "style": "destructive"
        }
      ]
    },
    {
      "type": "TextBlock",
      "wrap": true,
      "text": "There are also still \"actions\" at the bottom of the card"
    }
  ],
  "actions": [
    {
      "type": "Action.Submit",
      "title": "Default"
    },
    {
      "type": "Action.Submit",
      "title": "Positive",
      "style": "positive"
    },
    {
      "type": "Action.Submit",
      "title": "Destructive",
      "style": "destructive"
    }
  ]
}
```

Output in MS Teams:
![image](https://user-images.githubusercontent.com/32068259/83349447-ac767b80-a33d-11ea-9bdd-e183bd6b7c6d.png)

### Buttons inside a 'Container'
```
{
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "type": "AdaptiveCard",
  "version": "1.2",
  "body": [
    {
      "type": "Container",
      "items": [
        {
          "type": "TextBlock",
          "wrap": true,
          "text": "Cards can have action sets in the middle of their body."
        },
        {
          "type": "ActionSet",
          "actions": [
            {
              "type": "Action.Submit",
              "title": "Default",
              "style": "default"
            },
            {
              "type": "Action.Submit",
              "title": "Positive",
              "style": "positive"
            },
            {
              "type": "Action.Submit",
              "title": "Destructive",
              "style": "destructive"
            }
          ]
        }
      ]
    },
    {
      "type": "TextBlock",
      "wrap": true,
      "text": "There are also still \"actions\" at the bottom of the card"
    }
  ],
  "actions": [
    {
      "type": "Action.Submit",
      "title": "Default"
    },
    {
      "type": "Action.Submit",
      "title": "Positive",
      "style": "positive"
    },
    {
      "type": "Action.Submit",
      "title": "Destructive",
      "style": "destructive"
    }
  ]
}
```
Output in MS Teams:
![image](https://user-images.githubusercontent.com/32068259/83349465-c617c300-a33d-11ea-85bf-e2e9d493955d.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 672a763d-189b-8ba0-f66e-c07f1dc0a962
* Version Independent ID: 1ac7a9bd-138b-3bf8-60a3-1842d87371fd
* Content: [Add card actions in a bot - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-actions#adaptive-cards-actions)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-actions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-actions.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Subhasish-msft** [comment]
@nikosalexakis , Thank you for reporting it. Style property is currently not working in Teams. And there is an active bug for this.

**Comment by nikosalexakis** [comment]
Thanks @Subhasish-msft!
It would be good to have it documented (Button styles are not working in MSTeams)
Could you share a link of this bug?

**Comment by Subhasish-msft** [comment]
@nikosalexakis , Will make sure to mention it in the doc. Here is the [bug](https://domoreexp.visualstudio.com/MSTeams/_workitems/edit/901439).
