### ISSUE TITLE
Is it true that only a maximum of one (1) channel/group tab is allowed? 

### ISSUE THREAD

**Issue by YunnyChung** [MicrosoftDocs/msteams-docs#1715]
[Enter feedback here]
I quickly tried on my Teams client whether I can add maximum of one channel/group tab. 
But it seems this is not true. 
![image](https://user-images.githubusercontent.com/46677982/83358096-f489a400-a325-11ea-881c-3b12dd5bb4be.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62b12649-8660-975a-87f6-2f7486b5dc79
* Version Independent ID: c1b86714-5b2e-79a8-5761-0fb2fd5746c0
* Content: [What are custom tabs in Microsoft Teams? - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs)
* Content Source: [msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tabs/what-are-tabs.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Nikitha-MSFT** [comment]
Channel/group tab refers to the configuration tab, Which is used to add your tabs to the group/channel. You can add only one configurable tab to Your application. Could you please go through the docs [here](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/configuration-page)?
