### ISSUE TITLE
Reload personal tabs with a different URL

### ISSUE THREAD

**Issue by jaime-olivares** [MicrosoftDocs/msteams-docs#1716]
Let's assume I have a personal tab installed for certain application of my company.
This personal tab shall be pointing to some work item:  www.myapp.com/item/123
Is it possible to message that tab to change the URL to www.myapp.com/item/456, triggered from a hero card?
---

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62b12649-8660-975a-87f6-2f7486b5dc79
* Version Independent ID: c1b86714-5b2e-79a8-5761-0fb2fd5746c0
* Content: [What are custom tabs in Microsoft Teams? - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs)
* Content Source: [msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tabs/what-are-tabs.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by jaime-olivares** [comment]
sorry, I don't know why my message appeared in bold

**Comment by Trinetra-MSFT** [comment]
@jaime-olivares , You can set the content URL at dynamically with your ID. You need to call `microsoftTeams.getContext()` before tab load and update the content URL with your dynamic URL.

**Comment by Trinetra-MSFT** [comment]
Please feel free to reopen if you have further query
