### ISSUE TITLE
Is that updating some recent messages could cause rate limit exceptions

### ISSUE THREAD

**Issue by MarkLeiSource** [MicrosoftDocs/msteams-docs#1719]
I know the bot only could do 20 operations for all conversations in 1 sec. What if the bot sent 20 messages to different conversations and also update other messages (like remove the buttons of some recent cards) in 1 sec. Is that will hit the rate limit?

**Comment by Subhasish-msft** [comment]
Yes, It will hit the rate limit. This limit controls the traffic that a bot is allowed to generate across all threads in a data center (across multiple tenants). Here is the [doc link](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/rate-limit#bot-per-data-center-limit)
