### ISSUE TITLE
Removing @Mentions leaves behind <at></at> tokens

### ISSUE THREAD

**Issue by chtartMSFT** [MicrosoftDocs/msteams-docs#172]
https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/bots/bot-conversations/bots-conv-channel

When following the guidance within the this page to remove the @Mentions from the text, it still leaves behind <at></at> tokens which causes issues within LUIS, among other things.

**Comment by billbliss** [comment]
Yes, you are correct - there is a function in the Teams SDK called `GetTextWithoutMentions` which should avoid that problem.
