### ISSUE TITLE
Entire PC freezes when moving full-screen meeting

### ISSUE THREAD

**Issue by fanblade** [MicrosoftDocs/msteams-docs#1720]
This is a serious issue that renders the entire PC unresponsive. The only way to recover is to power-cycle the PC.

System configuration:
Microsoft Teams Version 1.3.00.13565 (64-bit).
Windows 10 Pro 1909
2 Monitors: primary on left

Repro steps:
1. Join a group Teams meeting in which a screen is being shared
2. Make the meeting full screen on a secondary monitor that is to the right of the primary monitor.
3. Shift the full-screen window to the main monitor using Win+shift+left.
4. The PC is now frozen, refusing to respond to user input. The cursor still moves on the screen, but no applications can be interacted with and the start menu cannot be opened with the Windows key.

**Comment by fanblade** [comment]
This is a bug report. I just realized this GitHub project is only for documentation, but I can't find the appropriate place to submit bugs for the Windows version of MS Teams.

**Comment by Nikitha-MSFT** [comment]
@fanblade, Probably you need to check your system configuration. Looks like system is running out of memory. Never such issue is reported in Teams.

**Comment by Gousia-MSFT** [comment]
Please re-open if you still have any queries here.
