### ISSUE TITLE
Incoming Webhook Security

### ISSUE THREAD

**Issue by pankajsharma2000** [MicrosoftDocs/msteams-docs#1721]
Hey,

What is the best way (or alternatives) to have a secure incoming webhook? It looks like keeping webhook url a secret is the only way. But, if someone gets hold of the url then it can be heavily spammed or misused using Action Messages? 

I see "Secure resource definitions" in the documentation and the limits to webhook posting. But is there a way to have a simple basic auth or any alternative to have this functionality in a more secure way?

Thanks,
Pankaj

**Comment by Abhijit-MSFT** [comment]
@panjkov, Answer to your question is No. Check the [documentations](https://docs.microsoft.com/en-us/MicrosoftTeams/app-permissions#connectors)

- The connector instance URL should be treated as secret/confidential: anyone who has that URL can post to it, like an email address. Therefore, there's some risk of spam or links to phishing or malware sites. If that were to happen, team owners can delete the connector instance.
- If the service that sends connector messages were to become compromised and start sending spam/phishing/malware links, a tenant administrator can prevent new connector instances from being created and Microsoft can block them centrally.

**Comment by pankajsharma2000** [comment]
@Abhijit-MSFT Thanks for this answer. Can Bot Framework be used to implement the features that we are looking for?

**Comment by Wajeed-msft** [comment]
@pankajsharma2000 - You could create a new [Office 365 Connector](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-creating) and disable actions.
![image](https://user-images.githubusercontent.com/31851992/86319288-d4654180-bc51-11ea-9fcf-6f44da4cf529.png)
