### ISSUE TITLE
MSAL support for Tabs Auth

### ISSUE THREAD

**Issue by okulygin** [MicrosoftDocs/msteams-docs#1726]
Are there any examples of using MSAL library for silent authentication in Teams tabs?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2e66ffa-ec00-4a84-a43d-d47e3c138b32
* Version Independent ID: 47e9a383-ac6a-dc7d-2d91-a9e09626fdab
* Content: [Silent authentication - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-silent-aad)
* Content Source: [msteams-platform/tabs/how-to/authentication/auth-silent-aad.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tabs/how-to/authentication/auth-silent-aad.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Nikitha-MSFT** [comment]
@okulygin, Check if [this](https://github.com/nmetulev/teams-msal) helps.
