### ISSUE TITLE
Microsoft Teams crash / lockup on Ubuntu 18.04

### ISSUE THREAD

**Issue by clarsen-007** [MicrosoftDocs/msteams-docs#1727]
Intermittent Teams on Ubuntu 18.04 crash / lockup...

This is all I see in the log "syslog" file below.

$ uname -r
5.3.0-53-generic

$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.4 LTS"

$ sudo cat /var/log/syslog.1 | grep -i "Jun  2 11:0"
Jun  2 11:01:48 Latitude kernel: [10996.921891] INFO: task kworker/1:1H:561 blocked for more than 120 seconds.
Jun  2 11:01:48 Latitude kernel: [10996.921901]       Not tainted 5.3.0-53-generic #47~18.04.1-Ubuntu
Jun  2 11:01:48 Latitude kernel: [10996.921904] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
Jun  2 11:01:48 Latitude kernel: [10996.921909] kworker/1:1H    D    0   561      2 0x80004000
Jun  2 11:01:48 Latitude kernel: [10996.922049] Workqueue: events_highpri intel_atomic_cleanup_work [i915]
Jun  2 11:01:48 Latitude kernel: [10996.922053] Call Trace:
Jun  2 11:01:48 Latitude kernel: [10996.922065]  __schedule+0x2a8/0x670
Jun  2 11:01:48 Latitude kernel: [10996.922070]  schedule+0x33/0xa0
Jun  2 11:01:48 Latitude kernel: [10996.922074]  schedule_preempt_disabled+0xe/0x10
Jun  2 11:01:48 Latitude kernel: [10996.922078]  __mutex_lock.isra.9+0x26d/0x4e0
Jun  2 11:01:48 Latitude kernel: [10996.922084]  ? __switch_to_asm+0x34/0x70
Jun  2 11:01:48 Latitude kernel: [10996.922088]  ? __switch_to_asm+0x34/0x70
Jun  2 11:01:48 Latitude kernel: [10996.922092]  ? __switch_to_asm+0x40/0x70
Jun  2 11:01:48 Latitude kernel: [10996.922097]  __mutex_lock_slowpath+0x13/0x20
Jun  2 11:01:48 Latitude kernel: [10996.922100]  ? __mutex_lock_slowpath+0x13/0x20
Jun  2 11:01:48 Latitude kernel: [10996.922103]  mutex_lock+0x2f/0x40
Jun  2 11:01:48 Latitude kernel: [10996.922197]  intel_cleanup_plane_fb+0x31/0x80 [i915]
Jun  2 11:01:48 Latitude kernel: [10996.922218]  drm_atomic_helper_cleanup_planes+0x58/0x70 [drm_kms_helper]
Jun  2 11:01:48 Latitude kernel: [10996.922306]  intel_atomic_cleanup_work+0x24/0x50 [i915]
Jun  2 11:01:48 Latitude kernel: [10996.922314]  process_one_work+0x1fd/0x3f0
Jun  2 11:01:48 Latitude kernel: [10996.922319]  worker_thread+0x34/0x410
Jun  2 11:01:48 Latitude kernel: [10996.922324]  kthread+0x121/0x140
Jun  2 11:01:48 Latitude kernel: [10996.922329]  ? process_one_work+0x3f0/0x3f0
Jun  2 11:01:48 Latitude kernel: [10996.922333]  ? kthread_park+0xb0/0xb0
Jun  2 11:01:48 Latitude kernel: [10996.922339]  ret_from_fork+0x1f/0x40
Jun  2 11:01:48 Latitude kernel: [10996.922346] INFO: task kworker/4:1H:599 blocked for more than 120 seconds.
Jun  2 11:01:48 Latitude kernel: [10996.922350]       Not tainted 5.3.0-53-generic #47~18.04.1-Ubuntu
Jun  2 11:01:48 Latitude kernel: [10996.922353] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
Jun  2 11:01:48 Latitude kernel: [10996.922356] kworker/4:1H    D    0   599      2 0x80004000
Jun  2 11:01:48 Latitude kernel: [10996.922442] Workqueue: events_highpri intel_atomic_cleanup_work [i915]
Jun  2 11:01:48 Latitude kernel: [10996.922444] Call Trace:
Jun  2 11:01:48 Latitude kernel: [10996.922449]  __schedule+0x2a8/0x670
Jun  2 11:01:48 Latitude kernel: [10996.922454]  schedule+0x33/0xa0
Jun  2 11:01:48 Latitude kernel: [10996.922457]  schedule_preempt_disabled+0xe/0x10
Jun  2 11:01:48 Latitude kernel: [10996.922461]  __mutex_lock.isra.9+0x26d/0x4e0
Jun  2 11:01:48 Latitude kernel: [10996.922466]  ? __switch_to_asm+0x34/0x70
Jun  2 11:01:48 Latitude kernel: [10996.922471]  ? __switch_to_asm+0x34/0x70
Jun  2 11:01:48 Latitude kernel: [10996.922475]  ? __switch_to_asm+0x40/0x70
Jun  2 11:01:48 Latitude kernel: [10996.922479]  __mutex_lock_slowpath+0x13/0x20
Jun  2 11:01:48 Latitude kernel: [10996.922483]  ? __mutex_lock_slowpath+0x13/0x20
Jun  2 11:01:48 Latitude kernel: [10996.922486]  mutex_lock+0x2f/0x40
Jun  2 11:01:48 Latitude kernel: [10996.922567]  intel_cleanup_plane_fb+0x31/0x80 [i915]
Jun  2 11:01:48 Latitude kernel: [10996.922585]  drm_atomic_helper_cleanup_planes+0x58/0x70 [drm_kms_helper]
Jun  2 11:01:48 Latitude kernel: [10996.922666]  intel_atomic_cleanup_work+0x24/0x50 [i915]
Jun  2 11:01:48 Latitude kernel: [10996.922672]  process_one_work+0x1fd/0x3f0
Jun  2 11:01:48 Latitude kernel: [10996.922678]  worker_thread+0x34/0x410
Jun  2 11:01:48 Latitude kernel: [10996.922682]  kthread+0x121/0x140
Jun  2 11:01:48 Latitude kernel: [10996.922687]  ? process_one_work+0x3f0/0x3f0
Jun  2 11:01:48 Latitude kernel: [10996.922690]  ? kthread_park+0xb0/0xb0
Jun  2 11:01:48 Latitude kernel: [10996.922696]  ret_from_fork+0x1f/0x40
Jun  2 11:01:48 Latitude kernel: [10996.922833] INFO: task kworker/u16:2:14111 blocked for more than 120 seconds.
Jun  2 11:01:48 Latitude kernel: [10996.922836]       Not tainted 5.3.0-53-generic #47~18.04.1-Ubuntu
Jun  2 11:01:48 Latitude kernel: [10996.922838] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
Jun  2 11:01:48 Latitude kernel: [10996.922841] kworker/u16:2   D    0 14111      2 0x80004000
Jun  2 11:01:48 Latitude kernel: [10996.922922] Workqueue: i915 __i915_gem_free_work [i915]
Jun  2 11:01:48 Latitude kernel: [10996.922924] Call Trace:
Jun  2 11:01:48 Latitude kernel: [10996.922930]  __schedule+0x2a8/0x670
Jun  2 11:01:48 Latitude kernel: [10996.922934]  schedule+0x33/0xa0
Jun  2 11:01:48 Latitude kernel: [10996.922937]  schedule_preempt_disabled+0xe/0x10
Jun  2 11:01:48 Latitude kernel: [10996.922941]  __mutex_lock.isra.9+0x26d/0x4e0
Jun  2 11:01:48 Latitude kernel: [10996.922946]  ? __switch_to_asm+0x34/0x70
Jun  2 11:01:48 Latitude kernel: [10996.922950]  __mutex_lock_slowpath+0x13/0x20
Jun  2 11:01:48 Latitude kernel: [10996.922953]  ? __mutex_lock_slowpath+0x13/0x20
Jun  2 11:01:48 Latitude kernel: [10996.922957]  mutex_lock+0x2f/0x40
Jun  2 11:01:48 Latitude kernel: [10996.923029]  __i915_gem_free_objects+0x83/0x220 [i915]
Jun  2 11:01:48 Latitude kernel: [10996.923099]  __i915_gem_free_work+0x5d/0x90 [i915]
Jun  2 11:01:48 Latitude kernel: [10996.923105]  process_one_work+0x1fd/0x3f0
Jun  2 11:01:48 Latitude kernel: [10996.923110]  worker_thread+0x34/0x410
Jun  2 11:01:48 Latitude kernel: [10996.923114]  kthread+0x121/0x140
Jun  2 11:01:48 Latitude kernel: [10996.923119]  ? process_one_work+0x3f0/0x3f0
Jun  2 11:01:48 Latitude kernel: [10996.923122]  ? kthread_park+0xb0/0xb0
Jun  2 11:01:48 Latitude kernel: [10996.923128]  ret_from_fork+0x1f/0x40
Jun  2 11:02:14 Latitude kernel: [11022.484566] traps: Watchdog[2345] trap invalid opcode ip:563eadea7724 sp:7f77fcff8aa0 error:0 in teams[563eac37d000+4bf6000]
Jun  2 11:03:49 Latitude kernel: [11117.750981] INFO: task kworker/1:1H:561 blocked for more than 241 seconds.
Jun  2 11:03:49 Latitude kernel: [11117.750988]       Not tainted 5.3.0-53-generic #47~18.04.1-Ubuntu
Jun  2 11:03:49 Latitude kernel: [11117.750991] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
Jun  2 11:03:49 Latitude kernel: [11117.750995] kworker/1:1H    D    0   561      2 0x80004000
Jun  2 11:03:49 Latitude kernel: [11117.751113] Workqueue: events_highpri intel_atomic_cleanup_work [i915]
Jun  2 11:03:49 Latitude kernel: [11117.751117] Call Trace:
Jun  2 11:03:49 Latitude kernel: [11117.751128]  __schedule+0x2a8/0x670
Jun  2 11:03:49 Latitude kernel: [11117.751132]  schedule+0x33/0xa0
Jun  2 11:03:49 Latitude kernel: [11117.751136]  schedule_preempt_disabled+0xe/0x10
Jun  2 11:03:49 Latitude kernel: [11117.751141]  __mutex_lock.isra.9+0x26d/0x4e0
Jun  2 11:03:49 Latitude kernel: [11117.751147]  ? __switch_to_asm+0x34/0x70
Jun  2 11:03:49 Latitude kernel: [11117.751151]  ? __switch_to_asm+0x34/0x70
Jun  2 11:03:49 Latitude kernel: [11117.751155]  ? __switch_to_asm+0x40/0x70
Jun  2 11:03:49 Latitude kernel: [11117.751159]  __mutex_lock_slowpath+0x13/0x20
Jun  2 11:03:49 Latitude kernel: [11117.751163]  ? __mutex_lock_slowpath+0x13/0x20
Jun  2 11:03:49 Latitude kernel: [11117.751166]  mutex_lock+0x2f/0x40
Jun  2 11:03:49 Latitude kernel: [11117.751264]  intel_cleanup_plane_fb+0x31/0x80 [i915]
Jun  2 11:03:49 Latitude kernel: [11117.751287]  drm_atomic_helper_cleanup_planes+0x58/0x70 [drm_kms_helper]
Jun  2 11:03:49 Latitude kernel: [11117.751379]  intel_atomic_cleanup_work+0x24/0x50 [i915]
Jun  2 11:03:49 Latitude kernel: [11117.751387]  process_one_work+0x1fd/0x3f0
Jun  2 11:03:49 Latitude kernel: [11117.751392]  worker_thread+0x34/0x410
Jun  2 11:03:49 Latitude kernel: [11117.751397]  kthread+0x121/0x140
Jun  2 11:03:49 Latitude kernel: [11117.751402]  ? process_one_work+0x3f0/0x3f0
Jun  2 11:03:49 Latitude kernel: [11117.751405]  ? kthread_park+0xb0/0xb0
Jun  2 11:03:49 Latitude kernel: [11117.751411]  ret_from_fork+0x1f/0x40
Jun  2 11:03:49 Latitude kernel: [11117.751418] INFO: task kworker/4:1H:599 blocked for more than 241 seconds.
Jun  2 11:03:49 Latitude kernel: [11117.751423]       Not tainted 5.3.0-53-generic #47~18.04.1-Ubuntu
Jun  2 11:03:49 Latitude kernel: [11117.751425] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
Jun  2 11:03:49 Latitude kernel: [11117.751428] kworker/4:1H    D    0   599      2 0x80004000
Jun  2 11:03:49 Latitude kernel: [11117.751517] Workqueue: events_highpri intel_atomic_cleanup_work [i915]
Jun  2 11:03:49 Latitude kernel: [11117.751520] Call Trace:
Jun  2 11:03:49 Latitude kernel: [11117.751525]  __schedule+0x2a8/0x670
Jun  2 11:03:49 Latitude kernel: [11117.751529]  schedule+0x33/0xa0
Jun  2 11:03:49 Latitude kernel: [11117.751533]  schedule_preempt_disabled+0xe/0x10
Jun  2 11:03:49 Latitude kernel: [11117.751537]  __mutex_lock.isra.9+0x26d/0x4e0
Jun  2 11:03:49 Latitude kernel: [11117.751542]  ? __switch_to_asm+0x34/0x70
Jun  2 11:03:49 Latitude kernel: [11117.751546]  ? __switch_to_asm+0x34/0x70
Jun  2 11:03:49 Latitude kernel: [11117.751550]  ? __switch_to_asm+0x40/0x70
Jun  2 11:03:49 Latitude kernel: [11117.751554]  __mutex_lock_slowpath+0x13/0x20
Jun  2 11:03:49 Latitude kernel: [11117.751557]  ? __mutex_lock_slowpath+0x13/0x20
Jun  2 11:03:49 Latitude kernel: [11117.751561]  mutex_lock+0x2f/0x40
Jun  2 11:03:49 Latitude kernel: [11117.751645]  intel_cleanup_plane_fb+0x31/0x80 [i915]
Jun  2 11:03:49 Latitude kernel: [11117.751665]  drm_atomic_helper_cleanup_planes+0x58/0x70 [drm_kms_helper]
Jun  2 11:03:49 Latitude kernel: [11117.751752]  intel_atomic_cleanup_work+0x24/0x50 [i915]
Jun  2 11:03:49 Latitude kernel: [11117.751758]  process_one_work+0x1fd/0x3f0
Jun  2 11:03:49 Latitude kernel: [11117.751764]  worker_thread+0x34/0x410
Jun  2 11:03:49 Latitude kernel: [11117.751768]  kthread+0x121/0x140
Jun  2 11:03:49 Latitude kernel: [11117.751772]  ? process_one_work+0x3f0/0x3f0
Jun  2 11:03:49 Latitude kernel: [11117.751776]  ? kthread_park+0xb0/0xb0
Jun  2 11:03:49 Latitude kernel: [11117.751781]  ret_from_fork+0x1f/0x40
Jun  2 11:03:49 Latitude kernel: [11117.751921] INFO: task kworker/u16:2:14111 blocked for more than 241 seconds.
Jun  2 11:03:49 Latitude kernel: [11117.751925]       Not tainted 5.3.0-53-generic #47~18.04.1-Ubuntu
Jun  2 11:03:49 Latitude kernel: [11117.751927] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
Jun  2 11:03:49 Latitude kernel: [11117.751930] kworker/u16:2   D    0 14111      2 0x80004000
Jun  2 11:03:49 Latitude kernel: [11117.752014] Workqueue: i915 __i915_gem_free_work [i915]
Jun  2 11:03:49 Latitude kernel: [11117.752017] Call Trace:
Jun  2 11:03:49 Latitude kernel: [11117.752022]  __schedule+0x2a8/0x670
Jun  2 11:03:49 Latitude kernel: [11117.752026]  schedule+0x33/0xa0
Jun  2 11:03:49 Latitude kernel: [11117.752030]  schedule_preempt_disabled+0xe/0x10
Jun  2 11:03:49 Latitude kernel: [11117.752033]  __mutex_lock.isra.9+0x26d/0x4e0
Jun  2 11:03:49 Latitude kernel: [11117.752038]  ? __switch_to_asm+0x34/0x70
Jun  2 11:03:49 Latitude kernel: [11117.752043]  __mutex_lock_slowpath+0x13/0x20
Jun  2 11:03:49 Latitude kernel: [11117.752046]  ? __mutex_lock_slowpath+0x13/0x20
Jun  2 11:03:49 Latitude kernel: [11117.752049]  mutex_lock+0x2f/0x40
Jun  2 11:03:49 Latitude kernel: [11117.752126]  __i915_gem_free_objects+0x83/0x220 [i915]
Jun  2 11:03:49 Latitude kernel: [11117.752200]  __i915_gem_free_work+0x5d/0x90 [i915]
Jun  2 11:03:49 Latitude kernel: [11117.752206]  process_one_work+0x1fd/0x3f0
Jun  2 11:03:49 Latitude kernel: [11117.752211]  worker_thread+0x34/0x410
Jun  2 11:03:49 Latitude kernel: [11117.752216]  kthread+0x121/0x140
Jun  2 11:03:49 Latitude kernel: [11117.752221]  ? process_one_work+0x3f0/0x3f0
Jun  2 11:03:49 Latitude kernel: [11117.752224]  ? kthread_park+0xb0/0xb0
Jun  2 11:03:49 Latitude kernel: [11117.752229]  ret_from_fork+0x1f/0x40

**Comment by Trinetra-MSFT** [comment]
@clarsen-007 , Could you please help us to know which Teams version you are running on?
