### ISSUE TITLE
Teams bot - Channel ID not identified when bot added to a specific channel

### ISSUE THREAD

**Issue by clearab** [MicrosoftDocs/msteams-docs#1728]
#Original Issue created on BF repository

## Versions
What package version of the SDK are you using.
"botbuilder": "~4.7.0"

What nodejs version are you using
v14.0.0

What os are you using
Ubuntu 18.04 LTS

## Describe the bug
Using Ms Teams, when adding the bot to a specific channel, I listen to the onMembersAdded from the TeamsActivityHandler class to send a welcome message. 
The message gets sent to "General", no matter the channel where the bot was added to. 

The TeamsInfo.getTeamDetails(turnContext) method returns the "General" channel id as well. 

## To Reproduce
Here is a minimum reproducible exemple:
```
const { TeamsActivityHandler, TurnContext, TeamsInfo } = require("botbuilder");

class Bot extends TeamsActivityHandler {
  constructor() {
    super();

    
    this.onMembersAdded(async (turnContext, next) => {

      const teamsChannelId = await TeamsInfo.getTeamDetails(turnContext);
      console.log(teamsChannelId);

      await context.sendActivity("Hello");


      await next();
    });
  }

}

module.exports.Bot = Bot;
```
And our Teams app manifest:
```
{
  "$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.6/MicrosoftTeams.schema.json",
  "manifestVersion": "1.6",
  "version": "1.0.0",
  "showLoadingIndicator": false,
  "id": "**************************",
  "packageName": "bot.teams.*******",
  "developer": {
    "name": "Company",
    "websiteUrl": "https://www.company.com",
    "privacyUrl": "https://www.company.com",
    "termsOfUseUrl": "https://www.company.com"
  },
  "icons": {
    "color": "color.png",
    "outline": "outline.png"
  },
  "name": {
    "short": "AppName",
    "full": ""
  },
  "description": {
    "short": "Company bot",
    "full": "Interact with Company"
  },
  "accentColor": "#FFFFFF",
  "bots": [{
    "botId": "**********************************",
    "needsChannelSelector": true,
    "scopes": [
      "team"
    ],
    "supportsFiles": false,
    "isNotificationOnly": false
  }],
  "permissions": [
    "identity",
    "messageTeamMembers"
  ],
  "validDomains": []
}
```

## Expected behavior
I expect the turnContext.sendActivity('Welcome') to send the message to the channel where the bot was added.

# My additional questions

What does `needsChannelSelector` actually do? My assumption is this is the expected behavior, but it would be a nice feature to add that if the channel selector is used to send the `conversationUpdate` event with the `conversationId` of the selected channel rather than just the team/general channel one.

**Comment by Trinetra-MSFT** [comment]
@clearab , We can fetch the channel id from TurnContext Here is the attached screenshot of channel data when bot was installed in channel for first time:
![image](https://user-images.githubusercontent.com/50989436/83640924-726dd980-a5ca-11ea-9846-39f8fe2eee22.png)
Could you please try below piece of code and check if you got the channel id in turnContext?
```
this.onMembersAddedActivity(async (context, next) => {
            console.log(context);
            console.log("onMembersAdded");
            await next();
        });
    }
```

**Comment by clearab** [comment]
@Trinetra-MSFT That's the wrong channel ID. I want the Id of the channel that is chosen in the channel pick-list by the user after installation to be included in the event - right now it only sends the general channel id

**Comment by Trinetra-MSFT** [comment]
@clearab , We have tested this scenario for multiple channels, We got he default channel id `General` channel. We have filed a Bug for this after reproduce.

**Comment by Trinetra-MSFT** [comment]
We will update you once bug is fixed. Please feel free to reopen if you have further query.
