### ISSUE TITLE
Teams Sharing not working with local data-href

### ISSUE THREAD

**Issue by RonakJain7** [MicrosoftDocs/msteams-docs#1730]
Not Showing preview. Could you please provide support ?

`<div
class="teams-share-button"
  data-href="http://localhost:3000/home"
  data-icon-px-size="64"
</div>`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5964e0a9-bba0-c5a3-8099-f3845037726c
* Version Independent ID: 24565c3b-2bb5-2482-a6c7-7b1f62e38abb
* Content: [Share to Teams embedded button - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/share-to-teams)
* Content Source: [msteams-platform/concepts/build-and-test/share-to-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/build-and-test/share-to-teams.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by RonakJain7** [comment]
Any update on this ?

**Comment by RonakJain7** [comment]
Any update on this ?

**Comment by RonakJain7** [comment]
Any update on this ?

**Comment by arpit107** [comment]
Hi Team, any update on this issue? I'm facing this issue too with local URLs.

**Comment by vineet00pareek** [comment]
Hey, Look like it is a common issue as I was also trying to test with the localhost but it was not working and I was thinking that something I missed. Please provide some workaround on the above-mentioned issue.

**Comment by Wajeed-msft** [comment]
@vineet00pareek, @RonakJain7 - Could you please try exposing your local endpoint [using ngrok](https://docs.microsoft.com/en-us/microsoftteams/platform/tutorials/get-started-dotnet-app-studio#tunnel-using-ngrok) and see if you are getting preview? Please let us know if this doesn't help.
