### ISSUE TITLE
Message extension is not displayed in pop out window

### ISSUE THREAD

**Issue by simiczhang** [MicrosoftDocs/msteams-docs#1734]
If user clicks "pop out chat" , our app's message extensions is NOT displayed in pop out window (and it seems all 3rd party message extension are not displayed in pop out window). 

Is this expected behavior or there is someway to enable message extension in pop out window as well ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5319949f-7a29-1d17-0090-5f423ae8174e
* Version Independent ID: 2d45f040-a391-ac0b-17e8-fa99e880fcf1
* Content: [Initiate actions with messaging extensions - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/messaging-extension-v3/create-extensions?tabs=typescript)
* Content Source: [msteams-platform/resources/messaging-extension-v3/create-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/resources/messaging-extension-v3/create-extensions.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by simiczhang** [comment]
Any update ?

**Comment by Trinetra-MSFT** [comment]
@simiczhang , Could you please provide your app manifest?

**Comment by simiczhang** [comment]
@Trinetra-MSFT  you could search Jabber in "apps" and install this app and choose to "pop out chat" and click phone icon in message extensions in any chat

**Comment by Trinetra-MSFT** [comment]
This is by design. Please feel free to reopen if you have further query on this
