### ISSUE TITLE
One Theme is missing on this docs page

### ISSUE THREAD

**Issue by JuanZMS** [MicrosoftDocs/msteams-docs#1740]
Dear La, 
I was currently looking at the documentation for the color themes in Teams and noticed that it hasn't been updated to include the High-Contrast color-theme. It would be great if this can be updated as I wanted to reference this link for a tips guide that I'm working on to get customers and ISV's to develop apps for the Ecosystem.

Feel free to let me know if you nead any extra Information.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6191356-f04e-ab08-d1dd-503eb6ec15dd
* Version Independent ID: 87b86b41-6c67-69ad-9712-cbe3a51d1ffd
* Content: [Design Guidelines Reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/design/components/color)
* Content Source: [msteams-platform/concepts/design/components/color.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/design/components/color.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Wajeed-msft** [comment]
The docs have been update: https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/design/design-teams-app-fundamentals#colors

Please feel free to re-open if you see any issues.
