### ISSUE TITLE
notification only bot is not working properly on iphone

### ISSUE THREAD

**Issue by MarwaAbuEssa** [MicrosoftDocs/msteams-docs#1742]
Hi ,
I'm developing a custom app for integration with microsoft teams . i developed and added a microsoft bot to my custom app using botframework v4 in nodejs . 

i want the bot to be a notification only bot so i had an activity tab not a chat .
it sends a proactive messages on a certain event at our api via /api/notify end point and it is working successfully at desktop , web and android mobile . 

the issue is at Iphone , if the bot is a notification only , i don't get a notification if the mobile screen is locked and no red badge at chat tab . also i can't find the bot icon at the top bar of the app too.

if I enabled the bot to send (chat not activity) , the notification displays at iphone screen lock and the bot icon is visible at the top bar of app and the red badge is working too at chat tab.

please see photo below for the difference 

![without](https://user-images.githubusercontent.com/7272394/83947412-02a05e80-a817-11ea-9284-91221e067ecf.png)
![with](https://user-images.githubusercontent.com/7272394/83947414-03d18b80-a817-11ea-91ef-37ec93abc09a.png)

please this issue is so urgent for me if you can help as fast as possible

Regards,
Marwa

**Comment by Subhasish-msft** [comment]
@MarwaAbuEssa , Are you not getting notification when Notification only bot sends message in iPhone? And it is working fine when you enable chat option?

**Comment by Subhasish-msft** [comment]
Can you also share the screenshot of the notification settings ?

**Comment by MarwaAbuEssa** [comment]
> @MarwaAbuEssa , Are you not getting notification when Notification only bot sends message in iPhone? And it is working fine when you enable chat option?

yes i'm not getting notification on iphone when Notification only bot sends and it is working fine when disable the notification only and enable chat .

**Comment by MarwaAbuEssa** [comment]
> Can you also share the screenshot of the notification settings ?

of course i'm reviewing the microsoft teams manifest.json file to verify the option exists or not
![image](https://user-images.githubusercontent.com/7272394/84035496-20e39700-a99c-11ea-9394-c45c776e5b15.png)

**Comment by Subhasish-msft** [comment]
Hi @MarwaAbuEssa , If you are still facing this issue, can you please share your iOS version and Teams Version. So that I will raise a bug for this.

**Comment by Gousia-MSFT** [comment]
Please re-open if you are still facing this issue
