### ISSUE TITLE
MS Teams Helper taking Too Much Memory

### ISSUE THREAD

**Issue by onlyabhi52** [MicrosoftDocs/msteams-docs#1743]
<img width="1440" alt="Screenshot 2020-06-08 at 9 21 51 AM" src="https://user-images.githubusercontent.com/43365450/83991205-abf76980-a969-11ea-8b4f-efc510981f3c.png">
Hi Team
The MS Teams Helper process is taking too much memory whenever we use Teams . Please can you suggest the reason for it's usage.

**Comment by Abhijit-MSFT** [comment]
I suggest you try to clear the caches of Teams and see if there is any improvement:

Go to  %appdata%\Microsoft\teams Then delete the following files. **As a side note, you can move the files to another place to avoid the data loss**.

a. In Application Cache > Cache folder, delete all files in it.
b. In Blob_storage folder, delete all files.
c. In Cache folder, delete all files.
d. In databases folder, delete all files.
e. In GPUCache folder, delete all files.
f. In IndexedDB folder, delete the .db file.
g. In Local Storage folder, delete all files.
h. In tmp folder, delete all files.

If you still see the same issue, we suggest you to vote for the feedback below via the following link. 
https://microsoftteams.uservoice.com/forums/555103-public/suggestions/17219609-teams-uses-600mb-and-is-super-slow

**Comment by onlyabhi52** [comment]
@Abhijit-MSFT  This is happening on Mac.

**Comment by Abhijit-MSFT** [comment]
@onlyabhi52 - Please vote your feedback to the following link
https://microsoftteams.uservoice.com/forums/555103-public/suggestions/17219609-teams-uses-600mb-and-is-super-slow

**Comment by onlyabhi52** [comment]
@Abhijit-MSFT  i have done that . Please can you suggest how much is eta for this resolution.

**Comment by Abhijit-MSFT** [comment]
@onlyabhi52, Can not provide eta for this.
