### ISSUE TITLE
bot profile photo

### ISSUE THREAD

**Issue by MarwaAbuEssa** [MicrosoftDocs/msteams-docs#1745]
hi, 

I'm using microsoft bot with my custom app integrated with microsoft teams . i had registered the bot at azure service and it is working. i set a bot photo from both portal.azure.com and https://dev.botframework.com and it is working but every day i found out that the photo is not loaded !! and i need to add it again from https://dev.botframework.com  !!and its working when user re-login again at microsoft team  and the next day the profile photo is missing !!. the photo size and dimension is correct and it is uploaded successfully till next day !! . i know how this is so strange but it happened during all day long .

![image](https://user-images.githubusercontent.com/7272394/84039809-175d2d80-a9a2-11ea-8f91-9bb30649f02e.png)

![image](https://user-images.githubusercontent.com/7272394/84039661-dbc26380-a9a1-11ea-938b-ba5a69b1883b.png)

Regards,
Marwa

**Comment by Subhasish-msft** [comment]
@MarwaAbuEssa, Updating the bot icon at on place should be do the job. Do you see the icon updated in Teams immediately once you add it in azure/botframework portal? And it does not appear next day ?

**Comment by MarwaAbuEssa** [comment]
after updating the icon it must re-login at teams to see the new icon either on my bot at microsoft teams or azure/botframework portal !! . but at the next day i can't see it . i don't know if this happens after a certain time/days or maybe after re-login multiple time on microsoft teams , I don't know really how this behaviour happens but I'm sure something is happening after updating the bot icon on azure/botframework and working why it is changed to default bot icon after a while ??

Regards ,
Marwa

**Comment by Subhasish-msft** [comment]
@MarwaAbuEssa , Can you please share the bot it? Is anyone else facing the same issue in your team?

**Comment by clearab** [comment]
Hi - Can you please open a support ticket from the Azure Portal? (Option should be on the bottom of the list when viewing your bot channels registration resource). That would be the fastest way to escalate this to the correct folks.

**Comment by clearab** [comment]
Take a bit of a closer look at this, it looks like you're updating the icon associated with your AAD app. I'm fairly certain that won't actually change anything. If you change only the icon at dev.botframework.com does the change stay? Have you migrated your bot registration to Azure, or can you only access it through the dev.botframework.com portal? If you have an Azure subscription, migrating your registration to Azure will probably resolve this.

**Comment by clearab** [comment]
If you're unable to open an Azure support ticket, please share your bot Id with us so that we can check our logging.

**Comment by Gousia-MSFT** [comment]
Please re-open if you still have any queries here
