### ISSUE TITLE
MSI Machine-Wide Installer Shows Only User-Context Install in InTune

### ISSUE THREAD

**Issue by bklotz-odu** [MicrosoftDocs/msteams-docs#1746]
The MSI for installing Teams is only available to be installed with the User App Install Context in InTune.  Our users are not set up as computer admins, therefore it automatically fails.  Either way, a machine-wide MSI should be installed with the Device context.  Please fix.

![Annotation 2020-06-08 110005](https://user-images.githubusercontent.com/66632149/84045815-4611de80-a977-11ea-9f55-1f167f8a9090.png)

**Comment by Subhasish-msft** [comment]
HI @bklotz-odu, User can perform machine wide install. 
These links will help.
[Windows 10 app deployment by using Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/apps-windows-10-app-deploy  )
[Install Microsoft Teams using Microsoft Endpoint Configuration Manager](https://docs.microsoft.com/en-us/microsoftteams/msi-deployment)
