### ISSUE TITLE
Activity tab in Teams App not mentioned in App studio documentation

### ISSUE THREAD

**Issue by priyank29** [MicrosoftDocs/msteams-docs#1747]
In App Studio , set up bot section has a checkbox for one-way notification only bot. I was not able to find clear documentation around it, since after selecting the option the app was only showing activity tab and took sometime to figure out the issue. Please check on this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f4a41f1-2993-7869-a1ab-b83cb6225d7e
* Version Independent ID: c000998f-9192-50fb-6a0b-ace157054292
* Content: [Get started with App Studio for Microsoft Teams - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/app-studio-overview)
* Content Source: [msteams-platform/concepts/build-and-test/app-studio-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/build-and-test/app-studio-overview.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Nikitha-MSFT** [comment]
@priyank29 - Teams contain only two type of tabs teams tab and personal tab. What activity tab refer to? Could you please explain the issue in more detail?

**Comment by priyank29** [comment]
@Nikitha-MSFT -  When you install a bot , you see sections such as Chat, Files and (+) sign to add tabs.
Now, when you install a bot which is created using App studio with "one way notifcation" option checked, only Acitivity and About section appears. There is no clear documentation around this.

**Comment by Nikitha-MSFT** [comment]
@priyank29  - When you enable "one way notification" you cannot see the files folder.  This is by design.
