### ISSUE TITLE
Malformed HTML: conversations module

### ISSUE THREAD

**Issue by radicalad** [MicrosoftDocs/msteams-docs#1748]
This page appears with exposed tags & unformatted text above the Microsoft header.

Using chromium edge.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: L2VuLXVzL2phdmFzY3JpcHQvYXBpL0BtaWNyb3NvZnQvdGVhbXMtanMvbWljcm9zb2Z0dGVhbXMuY29udmVyc2F0aW9ucw==
* Version Independent ID: L2VuLXVzL2phdmFzY3JpcHQvYXBpL0BtaWNyb3NvZnQvdGVhbXMtanMvbWljcm9zb2Z0dGVhbXMuY29udmVyc2F0aW9ucw==
* Content: [conversations module - Teams](https://docs.microsoft.com/en-us/javascript/api/@microsoft/teams-js/microsoftteams.conversations?view=msteams-client-js-latest)
* Content Source: []()

**Comment by Wajeed-msft** [comment]
[Linked page](https://docs.microsoft.com/en-us/javascript/api/@microsoft/teams-js/microsoftteams.conversations?view=msteams-client-js-latest) is auto generate and it looks fine now. 
![image](https://user-images.githubusercontent.com/31851992/93759821-8ea08f80-fc28-11ea-960a-8313eeb4e661.png)

Could you please re-open this with more details?
