### ISSUE TITLE
Search files

### ISSUE THREAD

**Issue by rdevs-official** [MicrosoftDocs/msteams-docs#1749]
Sometimes when I try to attach files from my computer into teams, and I search them up in file explorer, teams gets really slow and crashes. Why is this and how do I prevent it?

**Comment by Nikitha-MSFT** [comment]
Could you please Report a problem here as shown?

![image](https://user-images.githubusercontent.com/61688740/84230855-8786c300-ab0a-11ea-8898-a318ca9ed65d.png)

**Comment by rdevs-official** [comment]
![8A021F57-018A-4CDA-914E-AA445DAB9B92](https://user-images.githubusercontent.com/66076129/84233755-dd4b7300-aaea-11ea-97f6-ad654da6efc7.jpeg)
It just came up with this.

**Comment by Nikitha-MSFT** [comment]
I suggest you try to clear the caches of Teams and see if there is any improvement:

Go to %appdata%\Microsoft\teams Then delete the following files. As a side note, you can move the files to another place to avoid the data loss.

a. In Application Cache > Cache folder, delete all files in it.
b. In Blob_storage folder, delete all files.
c. In Cache folder, delete all files.
d. In databases folder, delete all files.
e. In GPUCache folder, delete all files.
f. In IndexedDB folder, delete the .db file.
g. In Local Storage folder, delete all files.
h. In tmp folder, delete all files.

**Comment by Gousia-MSFT** [comment]
Please re-open if you still have any queries here.
