### ISSUE TITLE
Suggestions for the Microsoft Teams SSO page

### ISSUE THREAD

**Issue by guillaumemeyer** [MicrosoftDocs/msteams-docs#1750]
1. Paragraph 11 "Navigate to API Permissions, and make sure to add the follow permissions", you should specify that these permissions are from the `Microsoft Graph` Api, or add a step in the procedure "Select Microsoft Graph".

2. In the "note" section, there is a mention to `api://subdomain.example.com/6789/c6c1f32b-5e55-4997-881a-753cc1d563b7)`, the `/6789` should be replaced by `:6789` to be consistent with the sample URL used in this document.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52221dd3-95ec-96b9-1da8-9478527c2602
* Version Independent ID: 32e9c2d8-733d-0865-2ea3-727d8684a10d
* Content: [Single Sign-On - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-aad-sso)
* Content Source: [msteams-platform/tabs/how-to/authentication/auth-aad-sso.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tabs/how-to/authentication/auth-aad-sso.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by guillaumemeyer** [comment]
Also, the js sample at the end should not have a trailing "," as it is not a good practice:
```js
var authTokenRequest = {
  successCallback: function(result) { console.log("Success: " + result); },
  failureCallback: function(error) { console.log("Failure: " + error); }
};
microsoftTeams.authentication.getAuthToken(authTokenRequest);
```

BTW, maybe all the JS samples in /docs should adhere to the [Standard](https://standardjs.com/) convention...

**Comment by Rajeshwari-v** [comment]
Point 2 of this issue was already addressed.
