### ISSUE TITLE
Minor typo : wit --> with 

### ISSUE THREAD

**Issue by Josverl** [MicrosoftDocs/msteams-docs#1751]
[Enter feedback here]

a spelling mistake in  ` See Extend you Teams app wit a custom tab`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3985d6b3-a785-5a91-8fb5-dee0cd09727a
* Version Independent ID: 5abc2e62-2ffa-15ee-5a51-d76646892d41
* Content: [Design guidelines for messaging extensions - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/design/messaging-extension-design)
* Content Source: [msteams-platform/messaging-extensions/design/messaging-extension-design.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/messaging-extensions/design/messaging-extension-design.md)
* Product: **msteams**
* GitHub Login: @EmilyyC
* Microsoft Alias: **qinch**

**Comment by laujan** [comment]
Hi @Josverl. The messaging extension design document has been updated.  Thank you for your feedback!
