### ISSUE TITLE
Move mobile info from "What are Microsoft Teams custom tabs?" to this page

### ISSUE THREAD

**Issue by aosolis** [MicrosoftDocs/msteams-docs#1755]
The information at the link below is important
https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs#mobile-clients

It belongs with the other mobile info on **this** page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e5840ee-09e8-93a6-51d8-508eef388b0a
* Version Independent ID: 621a526e-59dd-e81a-ee89-6a714bc055c8
* Content: [Tabs on mobile - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/design/tabs-mobile)
* Content Source: [msteams-platform/tabs/design/tabs-mobile.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tabs/design/tabs-mobile.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by laujan** [comment]
Hi @aosolis. The mobile design page has been updated. Thank you for your feedback!
