### ISSUE TITLE
Notification takes focus from active window on Debian GNU/Linux

### ISSUE THREAD

**Issue by r32rf** [MicrosoftDocs/msteams-docs#1756]
When I receive a notification from Teams, the notification window takes focus away from my current active window.

Suggested fix: use the native notification libraries

Environment: 
  DE: MATE 1.21
  WM: Awesome
  Teams Version: Latest as of 2020-06-11

**Comment by Gousia-MSFT** [comment]
@r32rf Please use Report a problem option under Help menu to report this problem.
![image](https://user-images.githubusercontent.com/45553518/84397781-b8571d00-ac1c-11ea-90fe-f4057efbf57c.png)

**Comment by r32rf** [comment]
That button is not there for me.
![image](https://user-images.githubusercontent.com/60923682/84465452-4eb82c80-ac77-11ea-97f4-1649f92ce878.png)

**Comment by r32rf** [comment]
Hello, is there an ETA on this?  It's really bugging me.  Can I force Teams to use the native notification library?

**Comment by Gousia-MSFT** [comment]
@r32rf We have reported the issue to the right team who is looking into it. Thanks!

**Comment by Gousia-MSFT** [comment]
@r32rf We are working on native notifications already. cannot promise any dates, but it is in our roadmap.

**Comment by r32rf** [comment]
Thanks.  I'll revert to using chrome in app mode then until this feature is implemented.  Is there an issue for the roadmap that I can set to "watching"?
