### ISSUE TITLE
"Dead-zone" on minimize/restore/close buttons when maximized

### ISSUE THREAD

**Issue by cosborne83** [MicrosoftDocs/msteams-docs#1757]
I'm running Teams version 1.3.00.13565 (32bit) on Windows 10, and there appears to be a "dead-zone" on the window's minimize, restore and close buttons when the Teams window is maximized. Clicking in this zone has no effect, despite the mouse appearing within the bounds of the button.

The dead-zone seems to be 2px high and 1px from the top of the window, as shown in red on the attached (2x enlarged) image:

![image](https://user-images.githubusercontent.com/3205779/84365418-51f4df00-abc9-11ea-9d93-58dc96d4a7f6.png)

**Comment by Gousia-MSFT** [comment]
@cosborne83 Please use "report a problem" option under Help menu to report this to the right folks.
![image](https://user-images.githubusercontent.com/45553518/84398109-27347600-ac1d-11ea-949d-f87e596d2c4f.png)
