### ISSUE TITLE
Typo in #1 last paragraph

### ISSUE THREAD

**Issue by opconWizard** [MicrosoftDocs/msteams-docs#1758]
Outgoing webhooks are scoped to the team level and are visible to all members of the team. Just like a bot, users _**ae**_ required to @mention the name of the outgoing webhook to invoke it in the channel

The above in bold/italics should be "are" instead of "ae".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb9c5bd5-1ac6-dcc8-4ed6-d6aad2432776
* Version Independent ID: 43e90995-bba4-86b6-1f1c-ab749e546a4b
* Content: [Add custom bots to Microsoft Teams with outgoing webhooks - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-outgoing-webhook)
* Content Source: [msteams-platform/webhooks-and-connectors/how-to/add-outgoing-webhook.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/webhooks-and-connectors/how-to/add-outgoing-webhook.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **laujan**

**Comment by laujan** [comment]
Hi @opconWizard. The typo in **Add custom bots to Microsoft Teams with outgoing webhooks** has been updated. Thank you for your feedback!
