### ISSUE TITLE
[Message Extensions] Actions commands invoked from ... overflow menu on a message are not available in Teams mobile app

### ISSUE THREAD

**Issue by Rishy17** [MicrosoftDocs/msteams-docs#1759]
Message extension with action command invoked from over flow menu of a message are not available in Teams mobile app, this behavior is observed on both the Android and IOS versions of teams. It works perfectly fine with Native teams app on desktop and browser versions.

![image](https://user-images.githubusercontent.com/60085862/84391983-56e07f80-ac17-11ea-8129-50f2569aa547.png)

No extensions are listed in the overflow menu, this is leading to an impact for our customer experiences when switching between platforms. 

The documentation does not indicate this type of functionality impact, can the product team clarify on this / an ETA on when this functionality would be added. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: efcdf768-1513-2249-b344-bf38ef64c70d
* Version Independent ID: 415b5d57-2d41-9540-55a7-2a33a4315e37
* Content: [Define messaging extension action commands - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/action-commands/define-action-command)
* Content Source: [msteams-platform/messaging-extensions/how-to/action-commands/define-action-command.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/messaging-extensions/how-to/action-commands/define-action-command.md)
* Product: **msteams**
* GitHub Login: @clearab
* Microsoft Alias: **anclear**

**Comment by Rishy17** [comment]
> Hi Rishy17! Thank you for bringing this issue to our attention. We will investigate and if we require further information we will reach out. Best regards, Teams Platform

is there any update on this?

**Comment by Gousia-MSFT** [comment]
@Rishy17 Message Extension actions are not currently supported on Mobile. We are working on it but we cannot give you an ETA on when this will be available.
