### ISSUE TITLE
After Click on Allow it is showing Bad Request .Login Consent is not Working in the Browser

### ISSUE THREAD

**Issue by TejaReddy0226** [MicrosoftDocs/msteams-docs#1764]
After Click on Allow it is showing Bad Request .Login Consent is not Working in the Chrome Browser.

![bad request consent login_LI](https://user-images.githubusercontent.com/62458014/84472611-20e9dc80-aca5-11ea-86a2-ac17569aac8f.jpg)

**Comment by Abhijit-MSFT** [comment]
@TejaReddy0226, Check if this works in Azure by following below steps
 - Go to your Bot Channel Registration
 - Navigate to Settings from left hand menu
 - Go oAuth setting in the page bottom
 - Click on the connection (it will take you to Service Provider Connection Settings)
 - Look for "Test Connection" and test it

For more details on how to set up authentication and trouble shoot check the [documentation](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/authentication/add-authentication?tabs=dotnet%2Cdotnet-sample).
