### ISSUE TITLE
bug: the sorting feature multiplying the items

### ISSUE THREAD

**Issue by techakhilc47** [MicrosoftDocs/msteams-docs#1765]
while clicking the sorting options under the teams 'grades' section it shows multiple instances of the same items .
video attached
[bug-misbehaving_sort_feature.zip](https://github.com/MicrosoftDocs/msteams-docs/files/4771331/bug-misbehaving_sort_feature.zip)

**Comment by Gousia-MSFT** [comment]
@techakhilc47 Could you please elaborate the scenario here? Is this tab hosted by you?

**Comment by Gousia-MSFT** [comment]
Please re-open if you still have an issue here
