### ISSUE TITLE
Audio devices are unavailable on Linux

### ISSUE THREAD

**Issue by mccarthyryanc** [MicrosoftDocs/msteams-docs#1766]
Installed on Ubuntu 18.04 via deb (Microsoft Teams Version 1.3.00.5153 (64-bit).). The Devices section under Settings only shows a "Custom Setup" for audio and won't let me select anything (cursor changes to a "prohibited" symbol):
![image](https://user-images.githubusercontent.com/997120/84526056-816f1e80-ac91-11ea-814b-fcd3d51bcf5d.png)

**Comment by Nikitha-MSFT** [comment]
Could you please provide us the logs as mentioned below?

~/.config/Microsoft/Microsoft Teams/logs.txt and whole folder 

~/.config/Microsoft/Microsoft Teams/media-stack

**Comment by mccarthyryanc** [comment]
@Nikitha-MSFT is there a way for me to inspect the `.blog` files in the `media-stack` directory before I upload them?

**Comment by Nikitha-MSFT** [comment]
@mccarthyryanc - Engineering team is asking for logs, I might not to be correct person to answer your above query. Could you please provide logs to us?

**Comment by Gousia-MSFT** [comment]
Please re-open if you still have any queries here.
