### ISSUE TITLE
Broken Link in Documentation

### ISSUE THREAD

**Issue by dcmesh** [MicrosoftDocs/msteams-docs#1767]
Where the documentation states:

"You must configure the application permissions for your bot in advance. We recommend using the Microsoft App Registration Portal as described here because that's where your bot was configured; however, you can still use the Azure portal if you prefer to use the Azure AD V1 endpoint."

The hyperlink embedded in the word "here" is broken, and leads to a 404 error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac64d14f-aec8-9dd6-e987-d2325de46fd6
* Version Independent ID: ba050a58-d98a-68f7-3190-8001d2a9d12c
* Content: [Registering a calling and meeting bot for Microsoft Teams - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/calls-and-meetings/registering-calling-bot)
* Content Source: [msteams-platform/bots/calls-and-meetings/registering-calling-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/bots/calls-and-meetings/registering-calling-bot.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by laujan** [comment]
Hi @dcmesh. The broken link has been updated. Thank you for your feedback!
