### ISSUE TITLE
PartnerCenter link is broken

### ISSUE THREAD

**Issue by gmahender** [MicrosoftDocs/msteams-docs#1770]
[Enter feedback here]
In "Localizing your AppSource listing" heading, Partner Center (https://docs.microsoft.com/en-us/dev/store/use-partner-center-to-submit-to-appsource) link is broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f55e52a-5fc4-7fcb-0e1e-946bff5aaee4
* Version Independent ID: b6c559fb-8512-575b-4fed-ebe1457e890e
* Content: [Localization for Team apps - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/apps-localization#feedback)
* Content Source: [msteams-platform/concepts/build-and-test/apps-localization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/build-and-test/apps-localization.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by laujan** [comment]
Hi @gmahender. The Partner Center links in the Localization document have been updated. Thank you for your feedback!
