### ISSUE TITLE
How to detect if the SSO feature is enabled for an MS tenant/domain?

### ISSUE THREAD

**Issue by ndileep** [MicrosoftDocs/msteams-docs#1772]
Since this feature is not yet enabled for all tenants how can we detect programmatically, during the SSO authorization request in the browser, whether the particular tenant has the SSO feature enabled or not?
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52221dd3-95ec-96b9-1da8-9478527c2602
* Version Independent ID: 32e9c2d8-733d-0865-2ea3-727d8684a10d
* Content: [Single Sign-On - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-aad-sso)
* Content Source: [msteams-platform/tabs/how-to/authentication/auth-aad-sso.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tabs/how-to/authentication/auth-aad-sso.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Trinetra-MSFT** [comment]
@ndileep Currently there is no way to detect SSO enabled programmatically at tenant level but at App level you can set inTeamsSSO=true in tab url and check for the SSO enabling
