### ISSUE TITLE
Subscribe to message reaction events of user

### ISSUE THREAD

**Issue by alaa0000** [MicrosoftDocs/msteams-docs#1773]
I want to subscribe to a message reaction of a user. According to the documentation, I can only subscribe to a message reaction of the bot.
Is this possible? If not, is there any plan on supporting it in the future?

Thank you.

**Comment by Trinetra-MSFT** [comment]
@alaa0000 , Currently this is not supported. you can only subscribe to the reactions added by user to he message sent from your bot. Please look at [message reaction events](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/subscribe-to-conversation-events?tabs=dotnet#message-reaction-events)

**Comment by alaa0000** [comment]
Thanks @Trinetra-MSFT . Is there any plan on your roadmap to support it?

**Comment by Trinetra-MSFT** [comment]
@alaa0000 . Please raise a [uservoice ](https://microsoftteams.uservoice.com/forums/555103-public/filters/new)for this

**Comment by alaa0000** [comment]
Awesome. Thank you.
