### ISSUE TITLE
Sideloaded connectors show up in section named "Sideloaded", not "Uploaded"

### ISSUE THREAD

**Issue by aosolis** [MicrosoftDocs/msteams-docs#1774]
The text in our docs is incorrect (screenshot is ok though).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54780e5a-ca3a-5277-dc84-37f85d9ea1cb
* Version Independent ID: 5f89865b-a9fd-ada5-72d2-6375357bba8c
* Content: [Upload your custom app in Microsoft Teams - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/apps-upload)
* Content Source: [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/deploy-and-publish/apps-upload.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Subhasish-msft** [comment]
@aosolis , Can you please point to exact section or text.

**Comment by laujan** [comment]
Hi @aosolis. Thank you for the callout! The document has been updated.
