### ISSUE TITLE
Broken link in FAQ Plus > Notes > Adaptive Card

### ISSUE THREAD

**Issue by medinapr** [MicrosoftDocs/msteams-docs#1777]
Broken link in FAQ Plus > Notes > Adaptive Card

**Comment by Gousia-MSFT** [comment]
https://docs.microsoft.com/en-us/microsoftteams/platform/samples/app-templates#faq-plus

**Comment by medinapr** [comment]
[cid:image001.png@01D6447E.35C6D700]

**Comment by laujan** [comment]
Thank you for your feedback. The link to adaptive cards is working.
