### ISSUE TITLE
Creating a deep link without having an App

### ISSUE THREAD

**Issue by Itaypa** [MicrosoftDocs/msteams-docs#1779]
Hi, I use an App which allows me to share content from the Channel > files with the channel conversation, this app lives outside of Teams and using the MS Graph API,
when sharing a link from the channel files I would like to create a deep link without having any app installed, is it possible? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45541337-ecd7-5cf6-cbe4-3f0d2f39aa79
* Version Independent ID: 6b4203f0-2844-06c9-eaa3-9cc03e6f76c0
* Content: [Create deep links - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links)
* Content Source: [msteams-platform/concepts/build-and-test/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/build-and-test/deep-links.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Subhasish-msft** [comment]
@Itaypa ,
There is an old way to deep links to files in a channel. But it is no where documented currently. 
```
https://teams.microsoft.com/l/file/<sourcedocId>?
tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47
&fileType=xlsx
&objectUrl=<File location link in sharepoint>
&baseUrl=https://microsoft.sharepoint.com
&serviceName=teams
&threadId=<channelId>
&groupId=<TeamId>
```

Getting these details inside the app which is not installed might be costly.

**Comment by Itaypa** [comment]
Hi,

Thanks for the awesome response! I almost got it to work, the sourceDocId
you mentioned, is it a guid? or a regular SharePoint doc id

**Comment by Subhasish-msft** [comment]
@Itaypa, Yes, It is SharePoint doc id.

**Comment by Itaypa** [comment]
Thank you!! helped me a lot 😁

‫בתאריך יום ב׳, 22 ביוני 2020 ב-9:10 מאת ‪Subhasish‬‏ <‪
notifications@github.com‬‏>:‬
