### ISSUE TITLE
Post a message to the webhook using cURL

### ISSUE THREAD

**Issue by dpolivka-medicomp** [MicrosoftDocs/msteams-docs#1782]
Note that to use the example given for "On Windows" in a **command prompt**, you have to invert the single and double quotes, otherwise it returns the following error: 
curl: (6) Could not resolve host: application
curl: (3) [globbing] unmatched close brace/bracket in column 12
Bad payload received by generic incoming webhook.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28316a67-22fa-8a05-1ae0-fbe1c5720ef9
* Version Independent ID: 8a250e46-2a30-af86-839d-9f83a8b48041
* Content: [Sending messages to Connectors and Webhooks - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-using)
* Content Source: [msteams-platform/webhooks-and-connectors/how-to/connectors-using.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/webhooks-and-connectors/how-to/connectors-using.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Trinetra-MSFT** [comment]
@dpolivka-medicomp , This is not a repro,  i tested this for windows in Git bash it works as it is is used same command as given in documentation 
// on Windows
`curl.exe -H 'Content-Type: application/json' -d '{"text": "Hello World"}' <YOUR WEBHOOK URL>`

I created incoming webhook i'm posting using git bash in Teams channel.
Please see screenshot:
![image](https://user-images.githubusercontent.com/50989436/84921854-a2e16780-b0e2-11ea-9642-b4a3016b7e14.png)

**Comment by dpolivka-medicomp** [comment]
I didn’t say it was a bug, I said “Note that to use the example given for "On Windows" in a command prompt” – meaning, if you use it in an actual Windows command prompt, where some of us still do work.  I clicked the link that said “Submit and view feedback for this page” – I guess I didn’t realize that “feedback” only meant bugs.
