### ISSUE TITLE
Code snippets show v2.0 endpoint but that cannot work with resources

### ISSUE THREAD

**Issue by svandenhoven** [MicrosoftDocs/msteams-docs#1783]
[Enter feedback here]

The code snippet where the login.onmicrosoft.com url is build uses the 2.0 endpoint together with resources. This delivers error as 2.0 endpoint does not support resources but requires scopes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b1dcd0d-471b-2d33-54b5-39a93dfba2a8
* Version Independent ID: 5bd44149-777e-b449-bd2e-f20b9bd04038
* Content: [Authentication for tabs using Azure Active Directory - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-tab-aad)
* Content Source: [msteams-platform/tabs/how-to/authentication/auth-tab-aad.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tabs/how-to/authentication/auth-tab-aad.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Subhasish-msft** [comment]
@svandenhoven ,
I have tried with 
**URL**  
`https://login.microsoftonline.com/common/oauth2/v2.0/authorize?`

**body**  
```
client_id=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
&resource=https%3A%2F%2Fgraph.microsoft.com%2FUser.Read%20openid
&redirect_uri=https%3A%2F%2fac21ab06.ngrok.io%2Ftab%2Fsilent-end
&grant_type=id_token token
&client_secret=xxxxxxxxxxxxxxxxxxxxxxxx
&response_mode=fragment
```
And it did work for me. Are you getting any error ?

**Comment by Gousia-MSFT** [comment]
Please re-open if you still have any queries here.
