### ISSUE TITLE
Use 'scope' instead of 'resource' parameter on simple-start page.

### ISSUE THREAD

**Issue by Robert1976** [MicrosoftDocs/msteams-docs#1784]
Issue concerning documentation: in my case to get the teams Tab authentication flow to work I had to replace the 'resource' parameter with 'scope' on the simple-start page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b1dcd0d-471b-2d33-54b5-39a93dfba2a8
* Version Independent ID: 5bd44149-777e-b449-bd2e-f20b9bd04038
* Content: [Authentication for tabs using Azure Active Directory - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-tab-aad)
* Content Source: [msteams-platform/tabs/how-to/authentication/auth-tab-aad.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tabs/how-to/authentication/auth-tab-aad.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Gousia-MSFT** [comment]
@Robert1976 Could you please share which particular code needs update? I see simplestart v2 page already uses the scope parameter and simple start page just works fine with resource.
