### ISSUE TITLE
[Developer Preview - Teams] The current browser is not supported

### ISSUE THREAD

**Issue by hraz-msft** [MicrosoftDocs/msteams-docs#1787]
While I do all the steps in the docs, I get this error in my Teams client:

![image](https://user-images.githubusercontent.com/66222191/84993952-a3194b80-b152-11ea-9a25-5721fa0a19b8.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 008da4e2-979e-c396-db28-4acf57deb530
* Version Independent ID: f1413f77-5eb3-e1fd-9235-d322d6e4eb6c
* Content: [Developer Preview - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/dev-preview/developer-preview-intro)
* Content Source: [msteams-platform/resources/dev-preview/developer-preview-intro.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/resources/dev-preview/developer-preview-intro.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Subhasish-msft** [comment]
@hraz-msft Are you getting above message while enabling developer preview?
Can you please share more detail about on which Teams client did you try? Desktop app/ Web app.

**Comment by hraz-msft** [comment]
Yes, I tried to enable the developer preview. I'm using the desktop app.

**Comment by Subhasish-msft** [comment]
Can you please share Teams build version that you are using.

**Comment by hraz-msft** [comment]
> You have Microsoft Teams Version 1.3.00.16364 (64-bit). It was last updated on 6/16/20.

**Comment by hraz-msft** [comment]
@Subhasish-msft any idea how toy solve it?

**Comment by Subhasish-msft** [comment]
@hraz-msft , We have done a fix for this on first of June. Can you please confirm if you are still facing this issue.

**Comment by rhalaly** [comment]
@Subhasish-msft no, I still have this issue:
![image](https://user-images.githubusercontent.com/8597700/86792748-74b4cf00-c073-11ea-812c-0f918944748b.png)

**Comment by hraz-msft** [comment]
@Subhasish-msft no, I still have this issue

![image](https://user-images.githubusercontent.com/66222191/86794120-cca00580-c074-11ea-8311-3df265e9262b.png)
