### ISSUE TITLE
The entire chat html content can be deleted

### ISSUE THREAD

**Issue by zbendefy** [MicrosoftDocs/msteams-docs#1788]
It seems that under certain conditions the applicaiton content can be deleted.
To repro:

- Under the  "Teams" tab, start typing into a reply field, or a new conversation.
- Type something with an emoticon at the end: e.g.: "something :D"
- Move the text cursor back a few characters
- Hit the 'End' key (notice that the text cursor disappears)
- Select all text (Ctrl + A) (Notice that all of the application content is highlighted)
- Hit the 'Backspace' key

This will delete everything including the conversations. To recover, close teams entirely and relaunch.

**Comment by Gousia-MSFT** [comment]
@zbendefy We could not repro the issue on our end. Could you please let us know if this happens frequently or happened just once?

**Comment by zbendefy** [comment]
I managed to took some captures, it also appears in the Chat tab.

I opened a chat tab:
![capture_005_19062020_082419](https://user-images.githubusercontent.com/9197376/85103175-7888ca80-b206-11ea-8aa9-198858b8d96f.jpg)

I entered "Something :D" into the text box:
![capture_006_19062020_082425](https://user-images.githubusercontent.com/9197376/85103176-7888ca80-b206-11ea-823b-893fe6de0d18.jpg)

I pressed the left arrow a couple of times to move the cursor:
![capture_008_19062020_082432](https://user-images.githubusercontent.com/9197376/85103178-79216100-b206-11ea-9e8d-aeaedb8ffa12.jpg)

I pressed the "End" key:
![capture_009_19062020_082438](https://user-images.githubusercontent.com/9197376/85103181-79b9f780-b206-11ea-8484-f8ed96b4b408.jpg)

I pressed "Ctrl+A":
![capture_010_19062020_082440](https://user-images.githubusercontent.com/9197376/85103183-79b9f780-b206-11ea-9014-354bdb541c00.jpg)

I pressed "Backspace":
![capture_011_19062020_082443](https://user-images.githubusercontent.com/9197376/85103174-77579d80-b206-11ea-854c-4607b74885a8.jpg)

**Comment by Gousia-MSFT** [comment]
@zbendefy I still can't repro the issue. Could you please try this in a chat with a user and not with the Bot?

**Comment by zbendefy** [comment]
I originally found the issue on a chat with a user (Actually on the teams tab), so it appears there as well.

**Comment by zbendefy** [comment]
Also this does not appear in the web version of teams, only the desktop app

**Comment by Gousia-MSFT** [comment]
@zbendefy Do you see this option to "Report a problem" from the Help menu. If yes, could you please report it directly from there. 
![image](https://user-images.githubusercontent.com/45553518/85833201-f886d580-b7ae-11ea-8e62-c4d8e3127408.png)

**Comment by Gousia-MSFT** [comment]
Please re-open if you still need any help here.
