### ISSUE TITLE
Markdown code formatting doesn't work with text containing empty lines in Notification Cards

### ISSUE THREAD

**Issue by sizmestiev** [MicrosoftDocs/msteams-docs#1790]
Hello.

My team is using Teams Channels to report application errors with Cards.

ERROR: Markdown code formatting works only with text without empty lines.

Empty lines are possible in java stak trace for nested exceptions.

First example formats message correct, second leaves ``` symbols in the message start and end without formatting to code.

EXAMPLE (success):
\`\`\`
exception1: reason1  
	at com.Example.function1(Example.java:100) at  
	at com.OtherExample.function2(OtherExample.java:200)  
\`\`\`

EXAMPLE (error):
\`\`\`
exception1: reason1  
	at com.FirstSample.function1(FirstSample.java:100)  
	at com.FirstOtherExample.function2(FirstOtherExample.java:200)  
  
caused by: exception2: reason 2  
	at com.SecondSample.function1(SecondSample.java:100)  
	at com.SecondOtherExample.function2(SecondOtherExample.java:200)  
\`\`\`

In the Card I can see some space between two parts of text in the place of empty line (by text selection in the card).

Thanks

**Comment by Abhijit-MSFT** [comment]
That is the card behavior. Try trimming the white spaces before assigning data to card fields.

**Comment by sizmestiev** [comment]
Thanks for the comment.
Would you please provide:
1. Purpose of such card behavior.
2. Some use cases where such behavior can help and cannot be changed to usual Markdown behavior.
