### ISSUE TITLE
Missing section about connector and manifest

### ISSUE THREAD

**Issue by ngcdev** [MicrosoftDocs/msteams-docs#1791]
Hello,

In the page, under the section `Post a message to the webhook using PowerShell` there are steps on how to do this, very similar to prior section using cURL. However after point 3, some new paragraph/information starts with no context.

The text goes like this:

    Include two icons, following the instructions in Icons.
    Modify the icons portion of the manifest to refer to the file names of the icons instead of URLs.

For what I gather, following the next few paragraph, this is about something else. This is about creating your own applications and registering them in Teams so you can communicate with them. But this is not clear here that we're talking about something or a whole new concept.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28316a67-22fa-8a05-1ae0-fbe1c5720ef9
* Version Independent ID: 8a250e46-2a30-af86-839d-9f83a8b48041
* Content: [Sending messages to Connectors and Webhooks - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-using)
* Content Source: [msteams-platform/webhooks-and-connectors/how-to/connectors-using.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/webhooks-and-connectors/how-to/connectors-using.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Subhasish-msft** [comment]
@ngcdev , Thanks for pointing it out. We will update it.

**Comment by laujan** [comment]
Please provide powerShell example.

**Comment by Subhasish-msft** [comment]
@laujan , Just below the PowerShell section, the content shown in the screenshot is from [this link](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-creating#including-the-connector-in-your-manifest) 
![image](https://user-images.githubusercontent.com/56869764/86875332-dde22400-c0ff-11ea-9f14-8e42e8fd6ddd.png)
