### ISSUE TITLE
Circular link

### ISSUE THREAD

**Issue by joel-g** [MicrosoftDocs/msteams-docs#1793]
This "App Studio" link just takes you back to the top of the page 
![image](https://user-images.githubusercontent.com/26105158/85071745-cfda5c80-b16c-11ea-9169-d7dd3f9d53d8.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e52a9fa-a482-2929-c462-47da5e8b38d1
* Version Independent ID: ce956c12-2916-9d6c-4fbb-5d07556378bc
* Content: [Create a bot for Microsoft Teams - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/create-a-bot-for-teams#using-app-studio)
* Content Source: [msteams-platform/bots/how-to/create-a-bot-for-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/bots/how-to/create-a-bot-for-teams.md)
* Product: **msteams**
* GitHub Login: @clearab
* Microsoft Alias: **anclear**

**Comment by Nikitha-MSFT** [comment]
@joel-g - We could not reproduce the issue on our side
