### ISSUE TITLE
Document call endpoint

### ISSUE THREAD

**Issue by shweaver-MSFT** [MicrosoftDocs/msteams-docs#1794]
The `call` endpoint deeplink should be documented. I can call it, it works, but I am not sure on the params it accepts.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45541337-ecd7-5cf6-cbe4-3f0d2f39aa79
* Version Independent ID: 6b4203f0-2844-06c9-eaa3-9cc03e6f76c0
* Content: [Create deep links - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links)
* Content Source: [msteams-platform/concepts/build-and-test/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/build-and-test/deep-links.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Trinetra-MSFT** [comment]
@shweaver-MSFT , Which deep link you are referring, is it within Tab or From Tab? Are you talking about `microsoftTeams.executeDeeplink()` method.  it takes the following URL with these params:
`https://teams.microsoft.com/l/entity/<appId>/<entityId>?webUrl=<entityWebUrl>&label=<entityLabel>&context=<context>` appId, entity ID, entityWebUrl and context.
you can check it here: [Deep link from your tab
](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links#generating-a-deep-link-to-your-tab)

**Comment by shweaver-MSFT** [comment]
Hi @Trinetra-MSFT, 

Yes, I am talking about URIs used to invoke specific states/actions in Teams. For example, calling this uri will cause Teams to display with a new *chat* message with the provided params:
https://teams.microsoft.com/l/chat/0/0?users=<user1>,<user2>,...&topicName=<chat name>&message=<precanned text>

Looking at the syntax, you will see the word `chat`. Turns out there is also a `call` endpoint, and invoking it will cause Teams to display a new audio/video call. You can click the link and see for yourself:
https://teams.microsoft.com/l/call/0/0

My team (http://aka.ms/mgt) is working on adding video/audio call deeplinking support to our PersonCard component. Only problem is that the depelink docs don't say anything about creating a new *call* via deeplink. That's what I'm looking for.
