### ISSUE TITLE
Doc refers to "Client Secrets" in left pane but there is no such section

### ISSUE THREAD

**Issue by joel-g** [MicrosoftDocs/msteams-docs#1795]
There is no "Client secrets" in the left pane as described below:

```
In the left panel, click Certificate and secrets.

Under Client secrets, click New client secret.
Add a description to identify this secret from others you might need to create for this app.
Set Expires to your selection.
Click Add.
Copy the client secret and save it to a file.
```

Here's what I see:
![image](https://user-images.githubusercontent.com/26105158/85075957-2dbe7280-b174-11ea-81a1-e4aea4e560d9.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e52a9fa-a482-2929-c462-47da5e8b38d1
* Version Independent ID: ce956c12-2916-9d6c-4fbb-5d07556378bc
* Content: [Create a bot for Microsoft Teams - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/create-a-bot-for-teams)
* Content Source: [msteams-platform/bots/how-to/create-a-bot-for-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/bots/how-to/create-a-bot-for-teams.md)
* Product: **msteams**
* GitHub Login: @clearab
* Microsoft Alias: **anclear**

**Comment by Gousia-MSFT** [comment]
@joel-g The Client Secrets option is displayed in the app registration page. Please follow the steps in the docs. Here is where you can see it:
![image](https://user-images.githubusercontent.com/45553518/85101448-0d4bf200-b220-11ea-9b23-1b35d352d968.png).

In your screen choose Settings and click on Manage option beside Microsoft App Id to add a secret.
![image](https://user-images.githubusercontent.com/45553518/85101617-66b42100-b220-11ea-9d27-04a840fa193b.png)
