### ISSUE TITLE
Microsoft Team Android App => Screen blinking issue and error message not make sense for below described scenario.

### ISSUE THREAD

**Issue by PradipDarji** [MicrosoftDocs/msteams-docs#1796]
Hello,

I observed that if someone at the organization level changes your **Microsoft Team** password and suppose user access **Microsoft Team** application in the android device, At that time user will automatically logout from there.  Meanwhile, if the user doesn't know that his/her Microsoft Team password has been changed and try to open **Microsoft Team** app at that time the behavior of the  **Microsoft Team**  app is not as expected as per the ideal user expectation. 

**Pre-condition:**
- First of all login into **Microsoft Team** app in android device
- Then change the password through some other way

**What happened exactly as I described below:** 
1) Suppose I am going to open the app 
2) App launched its initial screen 
3) After that user redirect on a black screen which has the only header "Sign in to Microsoft Teams"
4) Within a few seconds application start blinking black screen 2-4  times
5) Meanwhile, the application saw the error message like **"We've detected a slow connection. This may take a while."** Which doesn't make sense in this scenario.
6) After completion of all the above steps user redirected on the entered password screen.

So, My observation is that why the user has to face this kind of issue to reach out only to enter the password screen.

**Device Details:** 
**Device Name & Model**: vivo Y51L
**Android Version**: 5.0.2

**Please find an attached video for the same:**
[Microsoft Team Android App Issue.zip](https://github.com/MicrosoftDocs/msteams-docs/files/4805448/Microsoft.Team.Android.App.Issue.zip)

Thanks and Regards
Pradip Darji

**Comment by PradipDarji** [comment]
Sure,  I Will update you soon.

Actually it's happened 3 time with me.

No worry I will in touch with you very soon.

Thanks & Regards,
Pradeep Darji

**Comment by TaxProPam** [comment]
I am having same issue only on my Google Pixel Android phone. My Samsung is still connected to teams and working fine. My desktop is also still logged in and working fine. I've tried to enter my password on the Google Pixel, but it keeps telling me the password is incorrect. My password was not changed by admin.
