### ISSUE TITLE
Not able to loging teams bot using Android phone

### ISSUE THREAD

**Issue by Sujit-Gaikwad** [MicrosoftDocs/msteams-docs#1797]
HI ,
i am using consent flow. it is working fine on desktop teams app.
But when i'm tring to do same using mobile teams that it not giving access.

Step by step scinario i have done.:
1. I have triggered bot from mobile teams.
2. I get card of loging buttons in bot
3. I clicked yes the it redirected me to loging page.
4.I have logged in with my work id but  as my work id connected with Microsoft intune company portal it is asking me to enroll.
5. I clicked on enroll button. It's redirecting me to page to download company portal app even though i have already installed it
Even though the company app is there i'm not able to give access to bot using my id 

please Help on this 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63519845-323f-be8f-ce15-d7f39e46b5a7
* Version Independent ID: 70952f91-56e9-ff08-59f6-e237d4aaeca9
* Content: [Add authentication to your Teams bot - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/authentication/add-authentication?tabs=dotnet%2Cdotnet-sample)
* Content Source: [msteams-platform/bots/how-to/authentication/add-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/bots/how-to/authentication/add-authentication.md)
* Product: **msteams**
* GitHub Login: @clearab
* Microsoft Alias: **lajanuar**

**Comment by Subhasish-msft** [comment]
@Sujit-Gaikwad , Have you signed up to company portal and added your device?

**Comment by Sujit-Gaikwad** [comment]
>>@Sujit-Gaikwad , Have you signed up to company portal and added your device?
Yes I did

**Comment by Subhasish-msft** [comment]
@Sujit-Gaikwad , Once you enroll, You should be able to access. Are you able to access any other company resources?

**Comment by Sujit-Gaikwad** [comment]
@Subhasish-msft,  yes I'm able to access all other apps

**Comment by Subhasish-msft** [comment]
@Sujit-Gaikwad , I have shared this feedback with product team.

**Comment by Sujit-Gaikwad** [comment]
hi is there any updates on this 
I didn't get any solution on this can you please reopen it for tracking the issue above

**Comment by Subhasish-msft** [comment]
@Sujit-Gaikwad - I have shared this issue with our product team. As this is a product related issue, Tenant Admin can reach out to [Microsoft 365 Product Support](https://docs.microsoft.com/en-us/microsoft-365/admin/contact-support-for-business-products?view=o365-worldwide&tabs=online).
