### ISSUE TITLE
Share to Teams button

### ISSUE THREAD

**Issue by MarkTMcp** [MicrosoftDocs/msteams-docs#1798]
Show an example of how to set this up in Blazor.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5964e0a9-bba0-c5a3-8099-f3845037726c
* Version Independent ID: 24565c3b-2bb5-2482-a6c7-7b1f62e38abb
* Content: [Share to Teams embedded button - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/share-to-teams)
* Content Source: [msteams-platform/concepts/build-and-test/share-to-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/build-and-test/share-to-teams.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Subhasish-msft** [comment]
@MarkTMcp , Can you please share more details? Are you facing any issue while following the documentation?

**Comment by MarkTMcp** [comment]
The documentation does not show an example of how to implement Share to Teams in a Blazor app.
The give sample does not work on a blazor page. My guess is that the JS Interopt must be handled differently.

**Comment by MarkTMcp** [comment]
Is there a missing CSS reference in the documentation?
How is the class="teams-share-button" Located?

**Comment by Subhasish-msft** [comment]
@MarkTMcp , There is no CSS file missing.  "teams-share-button" class is mandatory as it is used inside the launcher.js to get the HTML document details of that particular div at run time.

**Comment by MarkTMcp** [comment]
I was able to make the Share to Teams button show up if I put the div in _Host.cshtml file, but not in any other .razor page within the app on a Blazor Server side program.

**Comment by Subhasish-msft** [comment]
@MarkTMcp , Can you please check if you are able to execute javascript code inside .razor page.

**Comment by MarkTMcp** [comment]
Yes, JS code can be executed from .razor pages using the Blazor JSI Interopt feature. However this is not an area that I have any knowledge of. I will try posting a request on one of the Blazor forums to see if anyone else can come up with a solution.
