### ISSUE TITLE
Spelling/Gramma mistake

### ISSUE THREAD

**Issue by jona8690** [MicrosoftDocs/msteams-docs#18]
Hi.

I was reading over the document https://github.com/MicrosoftDocs/msteams-docs/blob/live/msteams-platform/resources/schema/manifest-schema.md 

Under the section "staticTabs" it looks as if someone accidentally deleted parts of a word:
"without the user adding theM manually."

**Comment by billbliss** [comment]
accidentally capitalized the M - should just be them. Nothing's missing. Thanks!
