### ISSUE TITLE
SEO keywords

### ISSUE THREAD

**Issue by prkosh** [MicrosoftDocs/msteams-docs#1800]
[Enter feedback here]
This page does not surface in Google/Bing search results for "Partner Center account" or "Partner Center account verification" keywords
Can these keywords be included?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f071593-9440-5115-242d-488cf25e9256
* Version Independent ID: 746b1c6e-1bcc-21fe-e2be-149e7c10f1d5
* Content: [Microsoft Teams app approval process guidance - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/publish)
* Content Source: [msteams-platform/concepts/deploy-and-publish/appsource/publish.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/deploy-and-publish/appsource/publish.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by laujan** [comment]
Hi @prkosh! Thanks for your feedback. The document metadata has been updated with the additional SEO terms.
