### ISSUE TITLE
Bug in MS Teams App Studio

### ISSUE THREAD

**Issue by gustavf** [MicrosoftDocs/msteams-docs#1801]
The C# code showing in the Card Editor in App Studio appears to be wrong:

    var **parseResult** = **AdaptiveCards**.FromJson(card);
    var attachment = new Attachment
    {
        ContentType = AdaptiveCard.ContentType,
        Content = **parsedResult**.Card,
    };

It should be parsedResult in first line and it seems it should be without the s in AdaptiveCards.

**Comment by Subhasish-msft** [comment]
@gustavf, Thanks for pointing it out. We will update it.

**Comment by asnow003** [comment]
Thank you @gustavf I have logged a bug for this and will get this resolved.
