### ISSUE TITLE
How to read audio attachment from bot framework message extension?

### ISSUE THREAD

**Issue by eduardocampano** [MicrosoftDocs/msteams-docs#1805]
I'm trying to download an audio attachment from a message payload coming from Teams arriving to a message extension bot. The attachment part of the JSON payload has the following form:

```
"attachments": [
   {
     "id": "xxx",
     "contentType": "application/vnd.microsoft.card.audio",
     "contentUrl": null,
     "name": null,
     "thumbnailUrl": null,
     "content": "{\"duration\":\"PT13S\",\"media\":[{\"url\":\"https://eu-api.asm.skype.com/v1/objects/0-neu-d6-xxxx/views/audio\"}]}"
  }
]
```
I wasn't able to find any proper documentation about getting an access token from skype to download it. Is it possible at all?

Posted the issue here as suggested on [this question in SO](https://stackoverflow.com/questions/61921415/how-to-read-audio-attachment-from-bot-framework-message-extension)

Thanks in advance

**Comment by eduardocampano** [comment]
hi @Subhasish-msft, the audio message is recorded from the MS Teams iOS app

**Comment by Subhasish-msft** [comment]
Hi @eduardocampano , Sorry for the delayed response, Currently file download is not supported through message extension. We are discussion with platform team to consider this in future release.
