### ISSUE TITLE
Dead link in "Using the Teams client SDK" document

### ISSUE THREAD

**Issue by pierceboggan** [MicrosoftDocs/msteams-docs#1807]
In the paragraph:

> The Teams JavaScript client SDK and Teams JavaScript Library are part of the Microsoft Teams developer platform 

"Microsoft Teams developer platform" link points to:
https://msdn.microsoft.com/microsoft-teams

which returns a 404:
![image](https://user-images.githubusercontent.com/1091304/85343977-9d519c00-b4ab-11ea-9a31-84171085fc3b.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89e79849-bf25-dd0a-4680-c1074966051b
* Version Independent ID: fee94efc-fe9c-6460-1df8-f9bc97abf526
* Content: [Using the Teams client SDK - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/using-teams-client-sdk#feedback)
* Content Source: [msteams-platform/tabs/how-to/using-teams-client-sdk.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tabs/how-to/using-teams-client-sdk.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by laujan** [comment]
Hi @pierceboggan! Thank you for your feedback. The broken link in the **Using the Teams client SDK** has been updated.
