### ISSUE TITLE
Mobile tabs in Bots

### ISSUE THREAD

**Issue by bikubay** [MicrosoftDocs/msteams-docs#1809]
[Enter feedback here]
Hi unlike in desktop, the default experience in a Bot with a tab in mobile is to have the tab first and then the bot . we would like a setting to have the bot as the 'default' tab on mobile just as it is in Desktop. this inconsistent experience in Desktop v/s Mobile makes it very difficult to develop on the Teams platform

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e5840ee-09e8-93a6-51d8-508eef388b0a
* Version Independent ID: 621a526e-59dd-e81a-ee89-6a714bc055c8
* Content: [Tabs on mobile - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/design/tabs-mobile)
* Content Source: [msteams-platform/tabs/design/tabs-mobile.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tabs/design/tabs-mobile.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Gousia-MSFT** [comment]
@bikubay Thanks for reaching out to us! This is the default behaviour of apps on Mobile today. Currently we do not allow these settings to be changed and we do not have any plans for this in the near future.
