### ISSUE TITLE
Missing docs for v4 SDK : Initiating actions with Messaging Extension

### ISSUE THREAD

**Issue by adlele** [MicrosoftDocs/msteams-docs#1811]
The v4 docs don't have a page outlining how to initiate actions with messaging extensions/ how to request to install a bot from a Message extension from a composeExtension/fetchTask acttivity.

Equivalent v3 page: 
https://docs.microsoft.com/en-us/microsoftteams/platform/resources/messaging-extension-v3/create-extensions?tabs=typescript
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7fd5f91c-206f-f03c-d82e-3bf1cc81d13e
* Version Independent ID: d5c2d24a-def4-af2e-7983-c73cf7f22934
* Content: [What are messaging extensions? - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/what-are-messaging-extensions)
* Content Source: [msteams-platform/messaging-extensions/what-are-messaging-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/messaging-extensions/what-are-messaging-extensions.md)
* Product: **msteams**
* GitHub Login: @clearab
* Microsoft Alias: **anclear**

**Comment by Nikitha-MSFT** [comment]
Could you please check this [docs](https://docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/action-commands/create-task-module?tabs=dotnet)? Try if that helps.

**Comment by clearab** [comment]
Related: https://github.com/MicrosoftDocs/msteams-docs/issues/1584

**Comment by KirtiPereira** [comment]
This issue will be closed with the PR #2834. Therefore, closing this issue.
