### ISSUE TITLE
We can't get your files We're working on getting them back.

### ISSUE THREAD

**Issue by vakultech** [MicrosoftDocs/msteams-docs#1819]
Anyone encounter this issue in their microsoft team?
Also, the onedrive apps is not working.
Tried also searching in google but no solution is working.

Thank you.

**Comment by Gousia-MSFT** [comment]
@vakultech Could you please try sign out and sign in to Teams once and see if the issue is fixed? We could not repro this on our side.

**Comment by Gousia-MSFT** [comment]
Please re-open if you still have any query here.
