### ISSUE TITLE
ngrok.io redirected you too many times Error

### ISSUE THREAD

**Issue by imdat1guy** [MicrosoftDocs/msteams-docs#1820]
When I try to locally host and debug using ngrok I get an error "*****.ngrok.io redirected you too many times". The tab worked fine when it was hosted publicly, so I don't think there's an issue with the code itself? Also the ngrok link works fine when accessed regularly on a browser. I just get this error when it's loaded as a tab on Teams (This is the configuration page).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ba912c7-3f70-3406-ad5c-06b6a0fc3875
* Version Independent ID: d3717482-cd3c-32ec-c7e0-28612bf13c37
* Content: [Run and debug your app - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/debug)
* Content Source: [msteams-platform/concepts/build-and-test/debug.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/build-and-test/debug.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Nikitha-MSFT** [comment]
Could you please share the screen shot of the error you are seeing on ngrok and tab screen?

**Comment by imdat1guy** [comment]
Yeah this is what the error looks like:

![image](https://user-images.githubusercontent.com/49979350/86005496-c9c66480-ba25-11ea-89a5-6a22098ea071.png)

This is only shown in the web version of Teams. In the desktop client nothing is shown:

![image](https://user-images.githubusercontent.com/49979350/86005705-04c89800-ba26-11ea-9ec0-b97f39d4d268.png)

works normally with a broswer:

![image](https://user-images.githubusercontent.com/49979350/86005847-35a8cd00-ba26-11ea-9ddb-71dfed059624.png)

**Comment by imdat1guy** [comment]
The page works fine when hosted on the cloud instead of tunneling.

**Comment by Nikitha-MSFT** [comment]
Could you please share network trace (either using the Chromium dev tools or Fiddler)?

**Comment by imdat1guy** [comment]
It turns out there was a global redirect in our system when accessing internal resources that I wasn't aware of. We added an exception for the Teams' pages and solved this issue. Thanks for your help.
