### ISSUE TITLE
AAD Access Token Lifetime

### ISSUE THREAD

**Issue by imdat1guy** [MicrosoftDocs/msteams-docs#1821]
What is the lifetime of the Access Token here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b1dcd0d-471b-2d33-54b5-39a93dfba2a8
* Version Independent ID: 5bd44149-777e-b449-bd2e-f20b9bd04038
* Content: [Authentication for tabs using Azure Active Directory - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-tab-aad)
* Content Source: [msteams-platform/tabs/how-to/authentication/auth-tab-aad.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tabs/how-to/authentication/auth-tab-aad.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Subhasish-msft** [comment]
Default expire time of Access token is **1 hour**.

**Comment by imdat1guy** [comment]
Thank you.
