### ISSUE TITLE
Teams on mobile custom tab webview not resizing when software keyboard opens

### ISSUE THREAD

**Issue by gbarsa-astute** [MicrosoftDocs/msteams-docs#1822]
When custom tab in teams on mobile includes a text input, clicking in the intput will open the software keyboard.  The web view is not resized.  This means half of the webivew is obscured by the keyboard, possibly including the input itself.

**Comment by Subhasish-msft** [comment]
@gbarsa-astute, Can you please share a screenshot of the tab view. and also which version of MS Teams and OS you are using like android/iOs.

**Comment by gbarsa-astute** [comment]
Yes, this is happening on Android.  I am using chrome usb debugging to monitor the size of the web view.  

Here is a screenshot: ![Screenshot_20200630-072357](https://user-images.githubusercontent.com/67600815/86121173-8e6a7b00-baa3-11ea-9135-83a100f77a39.png)

As you can see the input is focused (with dashed border for emphasis) and the keyboard is open, but the web view remains full screen and the bottom half of the screen is obscured.

I understand that I can detect focus and resize the body of my page, but I have no way to tell what height is available since this has to work across iOS and Android, as well as on desktop.  

I will also say that I tried turning on the software keyboard on windows 10 and the teams app properly makes space for the keyboard.

**Comment by Subhasish-msft** [comment]
@gbarsa-astute Just to confirm, Is it a tab screen? From the screenshot, It seems like a bot chat screen. 
Can you please Teams version and OS version so that I can raise a platform issue.

**Comment by gbarsa-astute** [comment]
Yes, it is a tab screen.

Teams Version: 1416/1.0.0.2020061103
Calling Version 2020.14.01.9

Android Version: 10
Kernel version: 4.4.110-gae6d0ab37d61 #1 Fri Apr 10 23:00:09 UTC 2020
Build number: QQ3A.200605.001

Also, to be clear this happens on iOS also.

**Comment by Subhasish-msft** [comment]
@gbarsa-astute, I have share this feedback with mobile team.
