### ISSUE TITLE
Compartilhamento com um bug

### ISSUE THREAD

**Issue by CristopherCoutinho** [MicrosoftDocs/msteams-docs#1823]
Aparentemente quando você está compartilhando tela no teams se você fecha a janela que está sendo compartilhada mesmo parando, o som ainda continua a ser reproduzido.

**Comment by Abhijit-MSFT** [comment]
Can you please post your query in English with more details. 
Please explain what is happening when you close the window which is being shared in meeting.

**Comment by Gousia-MSFT** [comment]
Please re-open if you still have a query here
