### ISSUE TITLE
Not updated with latest manifest schema 1.7

### ISSUE THREAD

**Issue by prkosh** [MicrosoftDocs/msteams-docs#1825]
[Enter feedback here]
Not updated with latest manifest schema 1.7 - please help

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b449c9ba-a94c-4012-4721-cee5f87eeb8a
* Version Independent ID: b2536bbc-eb27-547d-d7f5-bab3ded3bedf
* Content: [Developer Preview Manifest schema reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema-dev-preview#webapplicationinfo)
* Content Source: [msteams-platform/resources/schema/manifest-schema-dev-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/resources/schema/manifest-schema-dev-preview.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by laujan** [comment]
This has been updated to v1.7.
