### ISSUE TITLE
Just add a stupid "Send Email Invitation to:" Button

### ISSUE THREAD

**Issue by BobH22** [MicrosoftDocs/msteams-docs#1829]
* Using Teams app.
* Using Teams Channel
* Created meeting on a calendar

So what did that accomplish?
* How do people get this to show up in their cell phones, non-outlook email, outlook email, etc.?
* How send an email invitation so they can open up Teams and join the meeting?
* Or were email invitations sent?

There is so much bad documentation on the Internet, like "sends the meeting to the calendar" - what does that mean?
When you document things, use nouns and define them. Be specific.

Now, I have some Team members, some of which do not want email invitations, and some want email invitations. Some documentation describes how to go into setups to control that but I have no such setups available in my version. Some say the user has to change something at their end.

Can you PLEASE just add a button on the calendar that says "Send Email Invitation"? When you click on it, you should be able to select any member from the team, whether they are a co-owner or not, and whether they are a member or guest or whatever. Even add an email address for a non-member as an option. Why? Not everyone logs onto Teams using their regular email account. We need to send it to their regular email account so they can be reminded to logon to Teams for a meeting.

Doesn't this make more sense than NO documentation, and NO functionality, or having to use Powershell to modify who knows what?

Just Google (or Bing) "Teams Email Invitations" to see what I mean.

Thanks,
Bob.

**Comment by Nikitha-MSFT** [comment]
@BobH22 Thanks for your suggestion. Could you please raise a user voice [here](https://microsoftteams.uservoice.com/)?

**Comment by BobH22** [comment]
Nikitha,

What does “raise a user voice” mean?

Bob.

**Comment by Nikitha-MSFT** [comment]
UserVoice is a product management and customer support tool that allows businesses to build a suggestions portal for their users to submit feature ideas, build a ticketing system for customer support and build articles knowledge base for users.
