### ISSUE TITLE
Not clear on how do i enable personal tab only for desktop and web clients as mobile is still in developer preview

### ISSUE THREAD

**Issue by naresh1990** [MicrosoftDocs/msteams-docs#1833]
Documentation is not clear on how we can add a personal tab without using developer preview manifest schema. 

we are planning to use it in our production environment and would like to have tabs only for Desktop and Web clients in addition to bot. Mobile client will just have bot.

**Comment by Subhasish-msft** [comment]
Currently tabs are supported in mobile, Web and Desktop as well. It can not be restricted in mobile. You could refer to this [updated doc](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/design/tabs-mobile).

We will update [this document](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs#mobile-clients) as it is misleading.

**Comment by Wajeed-msft** [comment]
[The docs](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs#mobile-clients) are updated.
