### ISSUE TITLE
Valid domains cannot contain a tunneling site when trying to install the MS teams app

### ISSUE THREAD

**Issue by maciej-w** [MicrosoftDocs/msteams-docs#1834]
I'm using ngrok and I get the following error: `Valid domains cannot contain a tunneling site. Please remove these in your manifest. To help to ensure the security of your app and users, domains outside of your organization's control` when trying to install the app.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4fa27cb-544f-f8a2-97a7-4b31528c1b80
* Version Independent ID: fa69cd6f-1ef4-706d-2816-aa709714b0aa
* Content: [Get started with App Studio and Node.js - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tutorials/get-started-nodejs-app-studio)
* Content Source: [msteams-platform/tutorials/get-started-nodejs-app-studio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tutorials/get-started-nodejs-app-studio.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Abhijit-MSFT** [comment]
Probably you are not adding it the way it is required. You need to add it like below code.
`  "validDomains": [
    "*.ngrok.io",
    "myapp.azurewebsites.net"
  ]`

if this does not solve your problem, please share your manifest
