### ISSUE TITLE
localization .json file has wrong JSON schema URL

### ISSUE THREAD

**Issue by follower90** [MicrosoftDocs/msteams-docs#1835]
localization .json file has wrong JSON schema URL
It seems it should be MicrosoftTeams.Localization instead of MicrosoftTeams

**Example localization .json file**
```
{
  "$shema": "https://developer.microsoft.com/json-schemas/teams/v1.7/MicrosoftTeams.Localization.schema.json",
   ...
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f55e52a-5fc4-7fcb-0e1e-946bff5aaee4
* Version Independent ID: b6c559fb-8512-575b-4fed-ebe1457e890e
* Content: [Localization for Team apps - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/apps-localization)
* Content Source: [msteams-platform/concepts/build-and-test/apps-localization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/build-and-test/apps-localization.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Subhasish-msft** [comment]
@follower90 , Thank you for pointing it out. We will update the document.

**Comment by follower90** [comment]
Thanks for fixing documentation!
I am closing the issue
