### ISSUE TITLE
Blank Notifications on macOS Catalina

### ISSUE THREAD

**Issue by vandenbergrobin** [MicrosoftDocs/msteams-docs#1836]
Hi,

The issue Teams freezing on notifications still exists and is becoming more and more frustrating. Just closing the issue is not solving it. I work in a professional environment where I have lots of video calls and receive lots of notifications. Having teams freeze every 20 seconds makes me want to pull my hair out. Please either reopen the original issue or please update us on a fix. This is ridiculous. 

Thanks.

@zorro2b , Thanks for reporting this. This is a known issue. we are looking into this.

_Originally posted by @Trinetra-MSFT in https://github.com/MicrosoftDocs/msteams-docs/issues/1502#issuecomment-609455123_

**Comment by Gousia-MSFT** [comment]
@vandenbergrobin We have an open bug on this which we are working on. I have raised this with the right folks again and they are working on fixing this. Thanks!

**Comment by Gousia-MSFT** [comment]
@vandenbergrobin The fix for this has been released but it will take some time to reach the public builds. Thanks!

**Comment by vandenbergrobin** [comment]
That would be amazing, thanks.

**Comment by viniciusferrao** [comment]
@Gousia-MSFT any insider build or something like that? It's really boring to use Teams this way. And what about a native notification framework? Why not use what's built in macOS?
