### ISSUE TITLE
Please clarify valid values for scope in RSC token acquisition

### ISSUE THREAD

**Issue by mlevay** [MicrosoftDocs/msteams-docs#1840]
Following the steps in https://docs.microsoft.com/en-us/microsoftteams/platform/graph-api/rsc/test-resource-specific-consent, I imported the Postman collection Test-RSC.
The article doesn't clarify valid values for the scope key while trying to obtain a token via https://login.microsoftonline.com/<tenant_id>/oauth2/v2.0/token. A few values I tried:

"teamsettings.read.group"
"TeamSettings.Read.Group"
"TeamSettings.Read.Group ChannelSettings.Read.Group ChannelMessage.Read.Group Member.Read.Group Owner.Read.Group TeamsTab.Create.Group TeamsTab.Edit.Group TeamsTab.Delete.Group"

No matter what values I provide, I get the same error:
{
    "error": "invalid_scope",
    "error_description": "AADSTS70011: The provided request must include a 'scope' input parameter. The provided value for the input parameter 'scope' is not valid. The scope teamsettings.read.group is not valid.\r\nTrace ID: 3ae258e1-9ce5-4b3b-9127-fa9197c87d00\r\nCorrelation ID: 34304ee5-b00c-452e-9dd6-8f88363b6e5f\r\nTimestamp: 2020-07-02 10:15:31Z",
    "error_codes": [
        70011
    ],
    "timestamp": "2020-07-02 10:15:31Z",
    "trace_id": "3ae258e1-9ce5-4b3b-9127-fa9197c87d00",
    "correlation_id": "34304ee5-b00c-452e-9dd6-8f88363b6e5f"
}

Tried passing the value ".default" for scope instead, which does get me an access token, but issuing any subsequent call in the collection with that token leads to further issues, e.g.:
GET https://graph.microsoft.com/beta/teams/71f82e73-ba45-4b89-9191-282f6428a64f
leads to:
{
  "error": {
    "code": "UnknownError",
    "message": "",
    "innerError": {
      "date": "2020-07-02T10:22:56",
      "request-id": "f48e962d-c21f-4038-bf3d-9112a07d5d7f"
    }
  }
}

I can confirm that my app has the necessary grants for that team. When executing https://graph.microsoft.com/beta/groups/71f82e73-ba45-4b89-9191-282f6428a64f/permissionGrants, I get:

{
    "@odata.context": "https://graph.microsoft.com/beta/$metadata#permissionGrants",
    "value": [
        {
            "id": "wSnW24DZ7LmqNgPHzt5RP_VGBdDKYv5fmBHU_dzbQrw",
            "deletedDateTime": null,
            "clientId": "1c935572-74b7-4532-83bc-18cfdb147d8e",
            "clientAppId": "9d01de9e-7be3-4ad2-a677-9c7c8f2c09a5",
            "resourceAppId": "00000003-0000-0000-c000-000000000000",
            "permissionType": "Application",
            "permission": "ChannelMessage.Read.Group"
        },
        {
            "id": "PNbr_QLDyowZZo5d01g5JPZWaOmoECDQFoyG67irWmE",
            "deletedDateTime": null,
            "clientId": "1c935572-74b7-4532-83bc-18cfdb147d8e",
            "clientAppId": "9d01de9e-7be3-4ad2-a677-9c7c8f2c09a5",
            "resourceAppId": "00000003-0000-0000-c000-000000000000",
            "permissionType": "Application",
            "permission": "ChannelSettings.Read.Group"
        },
        {
            "id": "jlWZXJsoXE1UMn6iX4sD_j2yLaj8ZUzXAbtFXMeyTMI",
            "deletedDateTime": null,
            "clientId": "1c935572-74b7-4532-83bc-18cfdb147d8e",
            "clientAppId": "9d01de9e-7be3-4ad2-a677-9c7c8f2c09a5",
            "resourceAppId": "00000003-0000-0000-c000-000000000000",
            "permissionType": "Application",
            "permission": "Member.Read.Group"
        },
        {
            "id": "B-eMyFYnC2GuudtDLxJumvC_4967ttASerFzwF6CdeA",
            "deletedDateTime": null,
            "clientId": "1c935572-74b7-4532-83bc-18cfdb147d8e",
            "clientAppId": "9d01de9e-7be3-4ad2-a677-9c7c8f2c09a5",
            "resourceAppId": "00000003-0000-0000-c000-000000000000",
            "permissionType": "Application",
            "permission": "Owner.Read.Group"
        },
        {
            "id": "TOcb-6cKjpNYgGmphGg6Xz7F-ieAbC6j1vsm3ed1InU",
            "deletedDateTime": null,
            "clientId": "1c935572-74b7-4532-83bc-18cfdb147d8e",
            "clientAppId": "9d01de9e-7be3-4ad2-a677-9c7c8f2c09a5",
            "resourceAppId": "00000003-0000-0000-c000-000000000000",
            "permissionType": "Application",
            "permission": "TeamSettings.Read.Group"
        },
        {
            "id": "gzthMSt3GDASadWvaj7Hn45D5WMzxegPGSybXIxFpok",
            "deletedDateTime": null,
            "clientId": "1c935572-74b7-4532-83bc-18cfdb147d8e",
            "clientAppId": "9d01de9e-7be3-4ad2-a677-9c7c8f2c09a5",
            "resourceAppId": "00000003-0000-0000-c000-000000000000",
            "permissionType": "Application",
            "permission": "TeamsTab.Edit.Group"
        },
        {
            "id": "fZ2aepRvwAJm6MbK4vCElq00PzsW3S9wPR1OxkFe4l4",
            "deletedDateTime": null,
            "clientId": "1c935572-74b7-4532-83bc-18cfdb147d8e",
            "clientAppId": "9d01de9e-7be3-4ad2-a677-9c7c8f2c09a5",
            "resourceAppId": "00000003-0000-0000-c000-000000000000",
            "permissionType": "Application",
            "permission": "TeamsTab.Create.Group"
        },
        {
            "id": "Scic1tT6HQj7OrVgas45NWf5ZSajTs3AhIABXKZglpE",
            "deletedDateTime": null,
            "clientId": "1c935572-74b7-4532-83bc-18cfdb147d8e",
            "clientAppId": "9d01de9e-7be3-4ad2-a677-9c7c8f2c09a5",
            "resourceAppId": "00000003-0000-0000-c000-000000000000",
            "permissionType": "Application",
            "permission": "TeamsTab.Delete.Group"
        }
    ]
}

Can someone please clarify the expectations for the scope key?
Thank you.

**Comment by Nikitha-MSFT** [comment]
@mlevay - Could you please try keeping Scope as default as:  https://graph.microsoft.com/.default? Also could you please check these docs [here](https://docs.microsoft.com/en-us/graph/auth-v2-service#token-request)?

**Comment by mlevay** [comment]
@Nikitha-MSFT thanks - I confirm having tried both the long and the short form of the default scope.
I furthermore confirm that the Postman collection I downloaded from https://docs.microsoft.com/en-us/microsoftteams/platform/graph-api/rsc/test-rsc-json-file issues the token request exactly as stated in https://docs.microsoft.com/en-us/graph/auth-v2-service#token-request.

**Comment by Wajeed-msft** [comment]
@mlevay - Are you still facing this issue? Could you check if your token has required permissions using https://jwt.ms/?

**Comment by mlevay** [comment]
@Wajeed-msft @Nikitha-MSFT The issue is not resolved.
A few words about architecture: 
- I have registered two apps with Azure; one app ID I use for a Teams SPA and the other one for a proprietary Web API with the custom scope "access_as_user". The latter app's manifest in Azure lists the former one as a known client.
- The SPA only makes calls to the Web API, which in turn issues calls to the MS Graph API.
- The SPA authenticates a user by using the v2.0 authorize and token access points and the custom scope mentioned above.
- Once the SPA is in possession of a valid token, it issues a request to the proprietary Web API and passes the token. The Web API validates the token and uses MSAL's ConfidentialClientApplication.acquire_token_for_client to acquire a token for the MS Graph API. That token is then used to query the Graph, using the /.default scope.
- The proprietary Web API uses a certificate (not a client secret). This certificate has of course been uploaded for the respective app registration in Azure AD.
- I have used jwt.ms to inspect all tokens and have found nothing unexpected in the values.

I have tried this setup with two different scenarios:
1) No RSC permissions listed in the SPA's Teams manifest - instead, the Group.Read.All application scope configured in Azure for both registered apps and consented by the Azure Administrator. With this scenario, the architecture described above works as expected.
2) No application permissions listed in any of the apps' Azure registrations, instead a number of RSC scopes specified in the SPA's Teams manifest (using the devPreview version of the Teams manifest per the official documentation). The Teams app does prompt for consent at installation time, and consent is granted by a team owner. However, calls made by the proprietary WebAPI to the MS Graph keep failing.

While setup 1) above works, 2) is what is required by the functional specification. I would appreciate if you could escalate this issue so it gets resolved.

Many thanks!

**Comment by Wajeed-msft** [comment]
@mlevay- Do you see your permissions listed while installing app to the team?

![image](https://user-images.githubusercontent.com/31851992/87418070-bfdc5e00-c5ee-11ea-82fc-630aeba1a541.png)

If not, two things to check:
1. Is [Developer Preview enabled](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/dev-preview/developer-preview-intro#enable-developer-preview)? 
2. Use the latest [latest manifest schema](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema) v1.7 and see if you see those permissions listed.

**Comment by mlevay** [comment]
@Wajeed-msft yes:
![image](https://user-images.githubusercontent.com/16627332/87418559-2b640280-c5d2-11ea-9196-d7b64ca63c4a.png)

**Comment by Wajeed-msft** [comment]
For your Token what values do you see in http://jwt.io/ for Roles ?

**Comment by mlevay** [comment]
I see no roles claim. Since none of the two app registrations have custom roles (the Web API has only a single custom scope defined), I didn't expect to see a roles claim.

**Comment by mlevay** [comment]
I found this now: https://docs.microsoft.com/en-us/azure/active-directory/develop/access-tokens, and it says about roles:
The set of permissions exposed by your application that the requesting application or user has been given permission to call. For application tokens, this is used during the client credential flow (v1.0, v2.0) in place of user scopes. For user tokens this is populated with the roles the user was assigned to on the target application.

Okay, so the proprietary WebAPI implements this functionality:

@router.get("/hello_app")
async def hello_app(
    authorization: str = Header(...), tenant_id: str = Query(...), team_id: str = Query(...), channel_id: str = Query(...)
):
    scope = "https://graph.microsoft.com/.default" # must be set to .default
    assertion = authorization.replace("Bearer ", "")
    app = get_confidential_client_app(assertion, tenant_id)
    if app is not None:    
        # get a new access token
        json_response = app.acquire_token_for_client(scopes=[scope])
        if "access_token" in json_response:
            access_token = json_response.get("access_token")
            print(access_token)
            url = "https://graph.microsoft.com/beta/teams/{}/channels/{}/messages".format(team_id, channel_id)
            headers = {"Authorization": "Bearer {}".format(access_token)}
            response: requests.Response = requests.get(url, headers=headers)
            return response.content
        else:
            # handle...
    else:
        raise HTTPException(401, "access_denied")

where app is a msal.ConfidentialClientApplication initialized with the assertion and the tenantId. I use the default scope. Why am I not getting the roles as you would expect?
Thanks!

**Comment by mlevay** [comment]
... and this code is always executed before get_confidential_client_app():

def requires_scope(required_scope):
    """
    Determines if the required scope is present in the access token
    Args:
        required_scope (str): The scope required to access the resource
    """

    def require_scope(f):
        @wraps(f)
        def decorated(*args, **kwargs):
            authorization = args[0]
            
            if authorization == "":
                raise HTTPException(status_code=400, detail="Invalid authorization header")
            
            public_keys_dict = _get_azure_public_keys()
            for (kid, public_key) in public_keys_dict.items():
                caller_app_id = CLIENT_APP_ID
                caller_app_id_uri = "api://example.hopto.org"
                claims_options = {
                    "aud": {
                        "essential": True,
                        "value": caller_app_id_uri
                    },
                    "appid": {
                        "essential": True,
                        "value": caller_app_id
                    }
                }
                jwt_token = JsonWebToken(algorithms=['RS256'])
                token = authorization.replace("Bearer ", "")

                try:
                    decoded_token = jwt_token.decode(token, public_key, claims_options=claims_options)
                except BadSignatureError as err:
                    # raise HTTPException(401, "bad_signature")
                    continue
                except InvalidTokenError as err:
                    print("invalid_token")
                    raise HTTPException(401, "invalid_token")
                except ExpiredTokenError as err:
                    print("token_expired")
                    raise HTTPException(401, "token_expired")
                except AuthlibBaseError as err:
                    print(err.error)
                    raise HTTPException(401, "Couldn't validate the bearer token ({})".format(err.error))
                
                if decoded_token.header["kid"] == kid:
                    if decoded_token.get("scp"):
                        print("==Found decoded token: {}, {}".format(kid, decoded_token))
                        token_scopes = decoded_token["scp"].split()
                        print("==Token valid for scopes: {}".format(token_scopes))
                        for token_scope in token_scopes:
                            if token_scope == required_scope:
                                return f(*args, **kwargs)
            raise HTTPException(403, "access_denied")

        return decorated

    return require_scope

**Comment by AkJo** [comment]
@mlevay , in your Teams App manifest, the id of which AzureADApp is specified as the webApplicationInfo.Id? Is it the app ID of your Teams SPA or the app id of your proprietary WebAPI - the confidential client in your example. 

There are two things that you need to ensure:
1. The webApplicationInfo.id in the manifest must be the app id that will be used to make the actual call into Graph. In your example, that seems to be the "proprietary WebAPI". 
2. RSC feature must be enabled for your tenant, and the Teams app with RSC permissions in its manifest must be successfully installed to at least 1 team in the tenant, and you can cross-check by reading the permission grants from https://graph.microsoft.com/beta/groups/{teamId}/permissionGrants.  Note: If RSC feature is disabled in your tenant at the moment you try to install an app that has RSC permissions, then the installation will fail.
3. The token that you get for calling into Graph must be an app only token (as opposed to an on-behalf-of) token. 

Can you please confirm that all of the three conditions have been met in your setup?

**Comment by mlevay** [comment]
Hi @AkJo - to answer your questions:
1. Confirm to be using the right ID;
2. Confirm to have activated the feature and installed the app in at least one team. The permission grants are all in place when I use https://graph.microsoft.com/beta/groups/%7BteamId%7D/permissionGrants with the ID of the team in question;
3. Confirm to be using the method described here: https://docs.microsoft.com/en-us/dotnet/api/microsoft.identity.client.confidentialclientapplication.acquiretokenforclient?view=azure-dotnet - so the user shouldn't be involved in acquiring the token. In addition, when I tried the same source code with a slightly different alternative configuration - "classic" application consent scopes+Azure admin consent instead of RSC - all worked.

Thank you,
Martina

**Comment by AkJo** [comment]
Hi @mlevay ,

Can you please provide the following details:
1) Tenant Id
2) App Id
3) Timestamp for an instance when you got a token for the above app id and it did not have Group.Selected

**Comment by mlevay** [comment]
1. The tenant ID is **5f496057-246e-47f4-bc5b-f7d5b45d3900**
2. The client ID of the app attempting to access the MS Graph is **db3cbb08-72b2-45b8-9c5f-baeb06234286**
3. Please interpret the timestamp in the GMT time zone:
```
{
	"error": {
		"code": "UnknownError",
		"message": "",
		"innerError": {
			"date": "2020-08-06T08:47:12",
			"request-id": "782c7aa8-6198-4781-9339-257bfacd3aa2"
		}
	}
}
```

Thanks and let me know if there is anything else needed.
-Martina

**Comment by AkJo** [comment]
@mlevay What is the webApplicationInfo.id specified in the app manifest?

Also, there was an issue sometime ago because of which under extreme edge cases the Group.Selected entitlement would get revoked. The issue has been fixed now. Can you please try uninstalling, and installing the app to a team once again so that the permission gets refreshed? Confirm that the permission got granted by checking  GET /groups/id/permissionGrants to see your app id removed and added back to the list. Then get a token for the app and confirm the roles stamped inside the token.

**Comment by mlevay** [comment]
@AkJo In the app manifest, I have set webApplicationInfo.id to the App ID for the app trying to access the Graph. The property webApplicationInfo.resource is set to that app's App ID URI as documented here: https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema

I just re-installed the app (and gave it a new version number in the manifest). I noticed that GET /beta/groups/id/permissionGrants returns all grants even when the app is uninstalled (and the property deletedDateTime keeps its null value for each listed grant). The app appeared to uninstall properly/without any issues in Teams: since it has both a dynamic and a static tab, I uninstalled all instances of it across teams and then uninstalled the static tab as well. Is there a better way to fully uninstall the app that I don't know of?

And, after re-installing the app (and confirming its higher version number), the result is the same - I get the same error message when trying to call the Graph API.

**Comment by mlevay** [comment]
@AkJo just managed to uninstall the app completely, confirmed the grants were gone, and once I installed it again, the issue was resolved. I can access the Graph now.
Thank you!

**Comment by AkJo** [comment]
". I noticed that GET /beta/groups/id/permissionGrants returns all grants even when the app is uninstalled"

@mlevay , there can be a propagation delay of upto 5 minutes between the app being uinstalled from a team, and its permissions from GET /beta/groups/id/permissionGrants being removed.
