### ISSUE TITLE
isFullscreen option in App details

### ISSUE THREAD

**Issue by mdanielcristian** [MicrosoftDocs/msteams-docs#1844]
I saw recently that there's a new option in App Studio -> Manifest editor -> Details -> App details, called Fullscreen Mode.
![image](https://user-images.githubusercontent.com/30260770/86449755-4bb5d680-bd21-11ea-9209-000bef24669d.png)

This looks great if it does what I think it does, and I was waiting for it for a while. But when I check that option and go to Test and distribute, I see an error, and the manifest is now invalid.
![image](https://user-images.githubusercontent.com/30260770/86449860-6c7e2c00-bd21-11ea-87ad-89c4342215fe.png)

Is this something that you're still working on, or is it supposed to be working already?
ETA if still working on it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0b75ec1-0ded-400e-7291-b7776d510ae4
* Version Independent ID: 157f3a51-42f6-f70f-a599-6775fcb34ed1
* Content: [Package your app - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/apps-package)
* Content Source: [msteams-platform/concepts/build-and-test/apps-package.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/build-and-test/apps-package.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Gousia-MSFT** [comment]
@mdanielcristian Thanks for reporting this to us. I could repro the issue. I have raised a bug for this and we are working on fixing it.

**Comment by Gousia-MSFT** [comment]
We are tracking this internally.
