### ISSUE TITLE
I am not able to see the option to upload the custom app to a particular team

### ISSUE THREAD

**Issue by lovyjain** [MicrosoftDocs/msteams-docs#1845]
I am seeing a option to upload app to my  organization but not able to see an option to upload to a particular team
Is there any setting which i need to activate or as i am using free subscription is the reason for that..?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54780e5a-ca3a-5277-dc84-37f85d9ea1cb
* Version Independent ID: 5f89865b-a9fd-ada5-72d2-6375357bba8c
* Content: [Upload your custom app in Microsoft Teams - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/apps-upload)
* Content Source: [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/deploy-and-publish/apps-upload.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Nikitha-MSFT** [comment]
You can upload a custom app  to a particular team using apps tab. Could you please go through the [Upload your package into a team using the Apps tab](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/apps-upload#upload-your-package-into-a-team-using-the-apps-tab)?

**Comment by lovyjain** [comment]
You can close down, as it takes time to reflect as i enable for the teams.
