### ISSUE TITLE
Pre-Requisite permissions to send to a WebHook

### ISSUE THREAD

**Issue by leebow55** [MicrosoftDocs/msteams-docs#1848]
Hello,

Please can the pre-requisites for permissions to send to a webhook be covered?

I have a process that sends an actionable message to a Webhook in one of our Private Teams Channels. When this process is run by my user account with an O365 license and mailbox then it sends the message ok. If I use a Service Account, which has no O365 license, or mailbox then it does not work.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28316a67-22fa-8a05-1ae0-fbe1c5720ef9
* Version Independent ID: 8a250e46-2a30-af86-839d-9f83a8b48041
* Content: [Sending messages to Connectors and Webhooks - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-using)
* Content Source: [msteams-platform/webhooks-and-connectors/how-to/connectors-using.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/webhooks-and-connectors/how-to/connectors-using.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Subhasish-msft** [comment]
@leebow55 , Are you referring incoming webhook?

**Comment by leebow55** [comment]
Hello, Yes I am.

**Comment by Subhasish-msft** [comment]
@leebow55 , incoming webhook generates a public URL and anyone can post a Json message to it. It does not require any permission to send message. Are you getting any error while sending message from service account.
 
You could also test the connector using Postman/Fiddle doing a POST request to the connector URL.
