### ISSUE TITLE
Teams blocks all audio after notification

### ISSUE THREAD

**Issue by DeDerpster** [MicrosoftDocs/msteams-docs#1849]
Quick note, I use windows 10 and headphones with a custom audio setting to allow my separate mic to work.
After a notification to the start of a meeting I have agreed to, teams will block any audio from playing (e.g. watching a video on the browser or system sound effects), as if I am in the meeting (I'm guessing this is meant to be a feature, but still would be nice for an option in the settings). This continues to happen even if I dismiss the message and not join the meeting, I must close teams completely or join the meeting and then leave to be able to continue what I had been doing.

**Comment by Trinetra-MSFT** [comment]
@DeDerpster , You can't play a video in browser while having a Team meeting, Teams Audio will block for sure as you select your audio device. This is by design , You can raise a [UserVoice ](https://microsoftteams.uservoice.com/forums/555103-public)for this

**Comment by DeDerpster** [comment]
To clarify, are you saying that Teams is meant to block audio even if you do not join the meeting?

**Comment by Trinetra-MSFT** [comment]
@DeDerpster , No if you don't join, you can still able to use your audio device without any issue. Could you please check your audio setting for this?
![image](https://user-images.githubusercontent.com/50989436/86766040-99a34500-c067-11ea-8e99-db578460f666.png)

**Comment by DeDerpster** [comment]
Okay, thanks, at the moment I don't seem to be able to re-create my original problem and it seems that I now can have audio playing in the background while in a meeting. Thank you.
