### ISSUE TITLE
[Msteams][iPhone]Hero card text is size is smaller than normal text

### ISSUE THREAD

**Issue by Sujit-Gaikwad** [MicrosoftDocs/msteams-docs#1850]
HI,

I have observed that on iPhone device HeroCard with text and button having small text size than normal message.
But in android teams, it is having the same size for both texts. 

In UI perspective it looks bad to have a different size in the bot message text and it is quite small to read the text on the device.

so can you please help me with the way to resize the text in HeroCard?

for reference please check the attached screenshot
In the screenshot below the **Green square represent the normal text** message and **Red square represent the HeroCard** message

**on iPhone Device:**

![Iphone_Herocard](https://user-images.githubusercontent.com/60354515/86604512-16301800-bfc3-11ea-94b8-b9c5b810b34d.png)

**on Android Device:**

![Android_Herocard](https://user-images.githubusercontent.com/60354515/86604691-555e6900-bfc3-11ea-8a36-737d5f2e0eee.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Cards Reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference#hero-card)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Trinetra-MSFT** [comment]
@Sujit-Gaikwad , Could you please help us to know which iPhone device you are using & what is teams version you are running?

**Comment by Sujit-Gaikwad** [comment]
I'm using **iPhone X**, Teams version: **v2.0.15**, iOS version: 13

**Comment by Trinetra-MSFT** [comment]
@Sujit-Gaikwad , We are looking into this, will get back to you in sometime

**Comment by Trinetra-MSFT** [comment]
@Sujit-Gaikwad , I've tested this for iphone 6s  for Teams 2.0.15 (1.077.2020062609)(R1) & other public ring. The font size is looking like this
![image](https://user-images.githubusercontent.com/50989436/90120766-c3434080-dd78-11ea-82c2-0b95898b0837.png)

**Comment by Sujit-Gaikwad** [comment]
@Trinetra-MSFT i'm still facing this issue. I think you are trying to test this using app studio but we are not using json to create hero card.
we are generating hero card through code like in following website
[Click Here](https://www.c-sharpcorner.com/article/getting-started-with-hero-card-design-using-microsoft-bot-framework/)
can you please check on your side and let me know once

**Comment by Trinetra-MSFT** [comment]
@Sujit-Gaikwad : The font size seems like this for iOS device 
![image](https://user-images.githubusercontent.com/50989436/94144323-9cefe500-fe8e-11ea-88e6-68992747f2a5.png)
Please feel free to reopen if you have further query.
