### ISSUE TITLE
To modify the card for an Out of Box Connector

### ISSUE THREAD

**Issue by lovyjain** [MicrosoftDocs/msteams-docs#1851]
HI team,

Is it possible to alter the OOB card(notification) received to a team channel as a part of Webhook connector,
EX: If i have configured the Jira/Azure DevOps connector a particular type of the Action card is received in notifications. So can we modify that.?

Regards
Lovy

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90ff2a84-a8bc-9259-d37d-622b102df75b
* Version Independent ID: e3b53e27-2946-189c-623b-9df704ea8f12
* Content: [Post external requests to Microsoft Teams with incoming webhooks - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-incoming-webhook)
* Content Source: [msteams-platform/webhooks-and-connectors/how-to/add-incoming-webhook.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/webhooks-and-connectors/how-to/add-incoming-webhook.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **laujan**

**Comment by Gousia-MSFT** [comment]
@lovyjain Yes, you could update the card posted in channel using the post action of a connector. Could you please try out the sample [here](https://github.com/OfficeDev/microsoft-teams-sample-connector-csharp/blob/c0aafd9af2bc28a1c76be0efb0026329b5255747/TeamsToDoAppConnector/Controllers/TaskController.cs#L56)?

**Comment by lovyjain** [comment]
@Gousia-MSFT Thanks for response but i was looking for the Change in card for the OOB connector . Like for the one of Azure devops or jira.

**Comment by Gousia-MSFT** [comment]
@lovyjain Do you mean changing the card posted by Azure/Jira connectors through Teams? That's not possible. The only way to modify the card sent in channel is to update it by using the post request.

**Comment by lovyjain** [comment]
Yes I wanted to have different actions in the card posted by Azure/jira. As these are OOB present so is there a way to modify them.
So is there a possibility we can write our own custom connectors for Azure/jira to be connected to teams??

**Comment by Gousia-MSFT** [comment]
@lovyjain Those are O365 connectors built by Azure/Jira team. Those can not be modified. You could try [creating your own Connector](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-creating) post notifications to channel.

**Comment by lovyjain** [comment]
can we create a custom connector which can copy the same work done by azure,devops connectors and then modify it as per the need.

**Comment by Gousia-MSFT** [comment]
@lovyjain It is not possible to copy the azure devops connector code since it is not open sourced but you could create your own webhook and send out the message card as per your requirement. Please check out the docs [here](https://docs.microsoft.com/en-us/azure/devops/service-hooks/services/webhooks?view=azure-devops).
