### ISSUE TITLE
Team created as "public" gets automatically changed to "Private"

### ISSUE THREAD

**Issue by CrimsonGlory** [MicrosoftDocs/msteams-docs#1853]
I created a Team as "Public (anyone in the organization can join)". Minutes later it got changed automatically to "Private (only owners can add team members)". I changed it again to public and minutes later it got reverted. (repeat N times). 

- Bug happens every time. 
- This was tested with an empty Team with only 1 owner (me)
- This was tested both with Teams app and Teams web.
- I still can't manage to get the Team stay as Public.

**Comment by Abhijit-MSFT** [comment]
How are you creating Teams, using Teams UI or API's?
can you please check if any policies are created and applied by admin.

**Comment by CrimsonGlory** [comment]
> How are you creating Teams, using Teams UI or API's?
> can you please check if any policies are created and applied by admin.

I created the Team with the Teams UI (windows "Microsoft Teams" application).
Is there a URL where I can check for policies applied by admin?

**Comment by Abhijit-MSFT** [comment]
@CrimsonGlory, Are you still facing this issue?

**Comment by CrimsonGlory** [comment]
> @CrimsonGlory, Are you still facing this issue?

yes. Nothing has changed.

**Comment by v-karapa** [comment]
could you please check is there any backgroud script changing the visibility for team.
Set-Team -GroupId 2f162b0e-36d2-4e15-8ba3-ba229cecdccf -DisplayName "Updated TeamName" -Visibility Public

**Comment by Geetha63** [comment]
Hi @CrimsonGlory, 

Please run PowerShell as administrator and run the below cmdlets to set visibility using PowerShell 
Connect-MicrosoftTeams 
(https://docs.microsoft.com/en-us/powershell/module/teams/connect-microsoftteams?view=teams-ps)
Set-Team -GroupId <String>  -Visibility <String> 
(https://docs.microsoft.com/en-us/powershell/module/teams/set-team?view=teams-ps)

Thank you,
Geetha.

**Comment by CrimsonGlory** [comment]
Not much success. The module is there though

```
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

PS C:\WINDOWS\system32> Connect-MicrosoftTeams
Connect-MicrosoftTeams : The 'Connect-MicrosoftTeams' command was found in the module 'MicrosoftTeams', but the module
could not be loaded. For more information, run 'Import-Module MicrosoftTeams'.
At line:1 char:1
+ Connect-MicrosoftTeams
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Connect-MicrosoftTeams:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CouldNotAutoloadMatchingModule

PS C:\WINDOWS\system32> Import-Module MicrosoftTeams
PS C:\WINDOWS\system32> Connect-MicrosoftTeams
Connect-MicrosoftTeams : The term 'Connect-MicrosoftTeams' is not recognized as the name of a cmdlet, function, script
file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct
and try again.
At line:1 char:1
+ Connect-MicrosoftTeams
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Connect-MicrosoftTeams:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by Geetha63** [comment]
Based on the error message , please do run  Import-Module MicrosoftTeams, if that does not work suggest you to check  PowerShell version update it to latest and uninstall (https://docs.microsoft.com/en-us/powershell/module/powershellget/uninstall-module?view=powershell-7) and install(https://docs.microsoft.com/en-us/microsoftteams/teams-powershell-install) module MicrosoftTeams
