### ISSUE TITLE
Timing/ Order:  Posts in teams

### ISSUE THREAD

**Issue by prashantNair26** [MicrosoftDocs/msteams-docs#1855]
If person A posts in Teams at 1500 (say). 
Person B posts at 1510.
Person C posts a reply to person A at 1515. 
_Then the person A's post goes below person B's post._

Though the time stamp is correct, order is now Person B post , then Person A post.

Please resolve this.

**Comment by Subhasish-msft** [comment]
Hi @prashantNair26 , 

This is by design. To display the latest conversation thread on bottom. Each new post is treated as a new conversation in Teams and A reply to a post is added as to the existing conversation thread.
