### ISSUE TITLE
How big is a data center?

### ISSUE THREAD

**Issue by johnny-linkedin** [MicrosoftDocs/msteams-docs#1857]
The document mentioned the limit for all bots in a data center. I'm curious how big a data center? or how many tenets in one data center? below 100, or 1k or 10k?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a57254c9-963d-ea1d-ecaf-dd0e7913526c
* Version Independent ID: 610c8514-bd72-46cc-75f1-991e2242019b
* Content: [Rate limiting - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/rate-limit)
* Content Source: [msteams-platform/bots/how-to/rate-limit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/bots/how-to/rate-limit.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Subhasish-msft** [comment]
@johnny-linkedin, We don't have any fixed size for any Data Center but Rate limiting on Data Center is center is certainly applied to prevent an API from being overwhelmed. Applications must also be designed with rate limiting in mind to reduce the chances of cascading failure.
