### ISSUE TITLE
Document which type of content is allowed in Deeplink when creating Meeting information

### ISSUE THREAD

**Issue by loicmitton** [MicrosoftDocs/msteams-docs#1861]
https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links#linking-to-the-scheduling-dialog
Describe how to use deeplink to create Meeting invitation but doesn't explicitly explains what type of content is allowed.

- Is it possible to use markdown ? 
- Is it possible to use breakline?

It could be really helpful for developers to know full capabilities of Deeplink and how to use them to build rich content.

**Comment by laujan** [comment]
Hi @loicmitton, 
We currently only support plain text. We don't support markdown, escaped HTML or line breaks. We understand that this is quite the limitation. Thanks for your feedback, we will consider improving this in the future but can't share any dates at this time.
