### ISSUE TITLE
Authorization error when trying to make a call from one bot to another

### ISSUE THREAD

**Issue by shereenfathy** [MicrosoftDocs/msteams-docs#1865]
Hello,

Can I make a bot able to make a call to another bot using Microsoft Graph Calling Apis? I tried this [API](https://docs.microsoft.com/en-us/graph/api/application-post-calls?view=graph-rest-1.0&tabs=csharp) but it seems to work with calling users only.

I tried to make a call with the target body for the call request

`var target = new InvitationParticipantInfo { Identity = new IdentitySet { Application = new Identity { Id = makeCallBody.ObjectId, }, }, }`

but I found this error "Message: Request authorization tenant mismatch" and the 2 bots in the same tenant

**Comment by Gousia-MSFT** [comment]
This is being tracked here: https://stackoverflow.com/questions/62812494/authorization-error-trying-to-make-a-call-from-one-bot-to-another?noredirect=1#comment111085280_62812494

**Comment by shereenfathy** [comment]
But no one answered me at least answer my first question please, is making bot call another bot using this api possible?

**Comment by Gousia-MSFT** [comment]
@shereenfathy Bot - Bot calling is not currently supported by Microsoft Graph calling API's
