### ISSUE TITLE
Where can I  get chat id?

### ISSUE THREAD

**Issue by Dmitresky** [MicrosoftDocs/msteams-docs#1866]
I have a message extension app for MS TEAMS. I am going to use "/chats/{id}/members" graph request for getting members. Where can I get {id}? My activity looks like

"activity": { 
      "type": "invoke",
      "id": "some activity Id",
      "timestamp": "2020-07-09T13:23:51.961+00:00",
      "localTimestamp": "2020-07-09T16:23:51.961+03:00",
      "localTimezone": null,
      "serviceUrl": "https://smba.trafficmanager.net/emea/",
      "channelId": "msteams",
      "from": {
        "id": "some from Id",
        "name": "FirstName LastName",
        "aadObjectId": "some aadObjectId",
        "role": null
      },
      "conversation": {
        "isGroup": true,
        "conversationType": "groupChat",
        "id": "some Id",
        "name": null,
        "aadObjectId": null,
        "role": null,
        "tenantId": "some tenantId"
      },
      "recipient": {
        "id": "some recipient Id",
        "name": "some name",
        "aadObjectId": null,
        "role": null
      },
      "textFormat": null,
      "attachmentLayout": null,
      "membersAdded": null,
      "membersRemoved": null,
      "reactionsAdded": null,
      "reactionsRemoved": null,
      "topicName": null,
      "historyDisclosed": null,
      "locale": "en-US",
      "text": null,
      "speak": null,
      "inputHint": null,
      "summary": null,
      "suggestedActions": null,
      "attachments": null,
      "entities": [
        {
          "type": "clientInfo",
          "locale": "en-US",
          "country": "US",
          "platform": "Windows"
        }
      ],
      "channelData": {
        "tenant": {
          "id": "some channelData tenant Id"
        },
        "source": {
          "name": "compose"
        }
      },
      "action": null,
      "replyToId": null,
      "label": null,
      "valueType": null,
      "value": {
        "commandId": "some command Id",
        "commandContext": "compose",
        "requestId": "84fb858068b246cdb3c7f566c97b72d1",
        "context": {
          "theme": "default"
        }
      },
      "name": "composeExtension/fetchTask",
      "relatesTo": null,
      "code": null,
      "expiration": null,
      "importance": null,
      "deliveryMode": null,
      "listenFor": null,
      "textHighlights": null,
      "semanticAction": null,
      "callerId": "urn:botframework:azure"
    }

FYI, I use Application Permissions. 

P.S.
Sorry for the formatting of json. I did get how to fix it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3985d6b3-a785-5a91-8fb5-dee0cd09727a
* Version Independent ID: 5abc2e62-2ffa-15ee-5a51-d76646892d41
* Content: [Design guidelines for messaging extensions - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/design/messaging-extension-design)
* Content Source: [msteams-platform/messaging-extensions/design/messaging-extension-design.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/messaging-extensions/design/messaging-extension-design.md)
* Product: **msteams**
* GitHub Login: @EmilyyC
* Microsoft Alias: **qinch**

**Comment by Trinetra-MSFT** [comment]
@Dmitresky , Could you please look at [List Chats](https://docs.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-beta&tabs=http) using Graph API? You will get the chat Id in response for users.

**Comment by Dmitresky** [comment]
@Trinetra-MSFT , 

Application Permissions are not supported :(

**Comment by Trinetra-MSFT** [comment]
@Dmitresky , Yes, Application permissions are not supported , You can try with the delegated one. Let me know if you face any difficulty in that.
