### ISSUE TITLE
Choice List not working on Adaptive Card (composeExtension)

### ISSUE THREAD

**Issue by shivajivarma** [MicrosoftDocs/msteams-docs#1867]
Choice list not opening on Adaptive Card, constructed as composeExtension, by a messaging extension.

<img width="686" alt="Screen Shot 2020-07-09 at 9 11 13 PM" src="https://user-images.githubusercontent.com/1388742/87060955-c2266d00-c228-11ea-86e7-167a7a4f94aa.png">

----
Same choice list working fine, if card is directly posted to channel.

<img width="720" alt="Screen Shot 2020-07-09 at 9 14 04 PM" src="https://user-images.githubusercontent.com/1388742/87061250-25180400-c229-11ea-8c0c-29a639ffaf43.png">

**Comment by Abhijit-MSFT** [comment]
@shivajivarma, can you please share card json.

**Comment by shivajivarma** [comment]
@Abhijit-MSFT  - Same card i have used to directly post to channel using bot and compose message using messaging extension response.

```js
{
  "contentType": "application/vnd.microsoft.card.adaptive",
  "content": {
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "type": "AdaptiveCard",
    "version": "1.0",
    "body": [
      {
        "type": "Container",
        "items": [
          {
            "type": "TextBlock",
            "text": "Where can I obtain updates and new releases?\n\t\t",
            "weight": "bolder",
            "size": "medium"
          }
        ]
      },
      {
        "type": "Container",
        "items": [
          {
            "type": "TextBlock",
            "text": "Where can I obtain updates and new releases for Mac OS X? ",
            "wrap": true
          },
          {
            "type": "TextBlock",
            "text": "To find updates and new releases for Mac OS X, try any of the following options:...",
            "wrap": true
          }
        ]
      },
      {
        "id": "my_input",
        "type": "Input.Text",
        "placeholder": "Placeholder text"
      },
      {
        "id": "my_choice",
        "type": "Input.ChoiceSet",
        "choices": [
          {
            "title": "Choice 1",
            "value": "Choice 1"
          },
          {
            "title": "Choice 2",
            "value": "Choice 2"
          }
        ],
        "placeholder": "Placeholder text"
      }
    ],
    "actions": [
      {
        "type": "Action.Submit",
        "title": "Read More",
        "data": {
          "kb_article": "0dd6457187032100deddb882a2e3ecb3",
          "action": "read_more",
          "msteams": {
            "type": "task/fetch"
          }
        }
      },
      {
        "type": "Action.Submit",
        "title": "Submit",
        "data": {
          "test": true,
          "msteams": {
            "type": "task/fetch"
          }
        }
      }
    ]
  }
}
```

**Comment by Nikitha-MSFT** [comment]
We could not repro the issue on our side. How did to post the the card using search command or action command? Could you please explain your scenario in more detail?

**Comment by shivajivarma** [comment]
@Nikitha-MSFT using search command.

On selecting an item from search result, the card is rendered in composition box... then posting it to chat.

**Comment by Nikitha-MSFT** [comment]
We are able to reproduce the issue. Raised a bug.

**Comment by Gousia-MSFT** [comment]
We are tracking this internally

**Comment by Wajeed-msft** [comment]
**Internal Tracker:** [Bug 1129910: Choice List not working on Adaptive Card (composeExtension)](https://domoreexp.visualstudio.com/MSTeams/_workitems/edit/1129910)

**Comment by Nikitha-MSFT** [comment]
@shivajivarma Are you still facing the issue? Could you please confirm?

**Comment by Trinetra-MSFT** [comment]
Bug is Resolved now, Could you please let us know if you still see this issue?
