### ISSUE TITLE
Is there a way to add a tab through graph api that can request mic/cam permissions? 

### ISSUE THREAD

**Issue by liangchr** [MicrosoftDocs/msteams-docs#1869]
I have a question. Is there a way to add a tab through graph api that can request mic/cam permissions? 

I know we can request enabled mic/cam permission requests through adding tab through manifest (using device permissions param), but is there a way to to enable those permission when a tab is added through graph api? 

The graph api call I am referring to is here: 
https://docs.microsoft.com/en-us/graph/api/teamstab-add?view=graph-rest-1.0

Any feedback/suggestions would be greatly appreciated.

**Comment by Trinetra-MSFT** [comment]
@liangchr , Yes you can please look at [Request device permissions for Teams Tab](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/native-device-permissions).

**Comment by eatalig** [comment]
@Trinetra-MSFT Thank you for answering, I am working with liangchr on this same issue. The link that you sent over is what we used to enable cam/mic permissions with a tab configured through manifest, but we were wondering if there is a way to get permissions for a website tab created with the graph api. In this link [https://docs.microsoft.com/en-us/graph/teams-configuring-builtin-tabs] there are instructions to configure a website tab type, but it is unclear how to add that tab type with teamsAppId being com.microsoft.teamspace.tab.web through manifest. 

Currently, the way we are adding this website tab is through an api call using graph explorer, referred to in [https://docs.microsoft.com/en-us/graph/api/teamstab-add?view=graph-rest-1.0], but can we get device permissions when adding a tab in this way? Or is the only way to get device permissions in the manifest and we'll have to somehow configure a website tab in the manifest as well? 

Please let me know if this needs clarification, any feedback would be appreciated.

**Comment by Trinetra-MSFT** [comment]
@liangchr , Currently there is no way to achieve this with graph API, you need to put these permissions in manifest.

**Comment by eatalig** [comment]
@Trinetra-MSFT Since that is the case, is there a way to configure a website tab type in the manifest? The link for configuring tab types in MS Teams I referenced above mentions a manifest schema for the different tab configurations, but I didn't find anything in the example manifest for website tabs (teamsAppId = com.microsoft.teamspace.tab.web). Is there a way to configure this tab and specify teamsAppID in the manifest? If so, is there any reference of how this is done?

**Comment by Trinetra-MSFT** [comment]
@eatalig, You can look at [Configure built-in tab in Teams](https://docs.microsoft.com/en-us/graph/teams-configuring-builtin-tabs?ranMID=24542&ranEAID=je6NUbpObpQ&ranSiteID=je6NUbpObpQ-FBQsVTVuvH8RnIEqJ_CKsw&epi=je6NUbpObpQ-FBQsVTVuvH8RnIEqJ_CKsw&irgwc=1&OCID=AID2000142_aff_7593_1243925&tduid=%28ir__zgkvpsyxbwkftzq3kk0sohzzx22xistakptliun600%29%287593%29%281243925%29%28je6NUbpObpQ-FBQsVTVuvH8RnIEqJ_CKsw%29%28%29&irclickid=_zgkvpsyxbwkftzq3kk0sohzzx22xistakptliun600#website-tabs). This requires teamsAppId which you fetch from [teams app catalog](https://docs.microsoft.com/en-us/graph/api/resources/teamsapp?view=graph-rest-1.0) but this won't be able to help you in adding device permissions in manifest. device permissions are listed in manifest schema which you have to mention while creating app manifest.

**Comment by Trinetra-MSFT** [comment]
@liangchr, Please feel free to reopen if you have further query regarding device permissions. We are happy to help you in that.
