### ISSUE TITLE
Loading website tab through manifest without loading it as iframe.

### ISSUE THREAD

**Issue by liangchr** [MicrosoftDocs/msteams-docs#1872]
I am loading a website (that does not like being loaded in an iframe) in the tab. 

I can install a website tab for a user using the graph api no problem. However I can't load the website through the manifest static/configurable tabs configuration because I get (frame-ancestors) security policy error. The website does not like being loaded in an iframe.

I still want to be install the tab through the manifest however, is there a way to side-step the iframe error this way?

**Comment by Abhijit-MSFT** [comment]
There is no way to pull website as Tab in teams which is not iframable. I trying to check if any workaround is available.
