### ISSUE TITLE
502 Bad Gateway with ngrok

### ISSUE THREAD

**Issue by summercyy** [MicrosoftDocs/msteams-docs#1873]
There seems to be some problem with the command to run ngrok.
When I run `ngrok http 3333 -host-header=localhost:3333`, and visit the url in browser, I got "502 Bad Gateway".
The correct command should be something like `ngrok http https://localhost:3333 -host-header=localhost:3333`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f98c73d-bb68-3088-6e7d-2c576a8292f6
* Version Independent ID: 08b9df7d-4997-c681-e73a-235ec1e4fc7b
* Content: [Get started with C#/.NET - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tutorials/get-started-dotnet-app-studio#host-the-sample-app)
* Content Source: [msteams-platform/tutorials/get-started-dotnet-app-studio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tutorials/get-started-dotnet-app-studio.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Nikitha-MSFT** [comment]
We could not reproduce the issue on our side. Which URL you are trying to visit in the browse?  Also Could you please share the  screen the the ngrok and error screen shot?
