### ISSUE TITLE
Found a bug in Microsoft Teams

### ISSUE THREAD

**Issue by Anad15** [MicrosoftDocs/msteams-docs#1876]
I can share my screen even though i am an attendee by minimizing the screen and then sharing it
Regards Anad Sinha
![Annotation 2020-07-11 101809](https://user-images.githubusercontent.com/68138901/87216970-2436bd80-c362-11ea-80ee-796c79922743.jpg)
![Annotation 2020-07-11 101827](https://user-images.githubusercontent.com/68138901/87216972-2567ea80-c362-11ea-85ec-f2f8481f14e4.jpg)
![Annotation 2020-07-11 101858](https://user-images.githubusercontent.com/68138901/87216973-2567ea80-c362-11ea-9683-7794693fb4b6.jpg)
![Annotation 2020-07-11 101910](https://user-images.githubusercontent.com/68138901/87216975-2731ae00-c362-11ea-9510-a778e517312a.jpg)
![Annotation 2020-07-11 101923](https://user-images.githubusercontent.com/68138901/87216976-27ca4480-c362-11ea-9ea8-53ca6a408344.jpg)

**Comment by Gousia-MSFT** [comment]
@Anad15 Thanks for reaching out to us. We could repro the issue and i have raised a bug for this. Our team is working on a fix for this.
