### ISSUE TITLE
Get-AzureADUser -Searchstring does not currently work

### ISSUE THREAD

**Issue by mpowrie** [MicrosoftDocs/msteams-docs#1879]
This command currently fails:
(Get-AzureADUser -SearchString $user.UserName).UserPrincipalName
Error:
Get-AzureADUser : Error occurred while executing GetUsers 
Code: Request_UnsupportedQuery
Message: Unsupported or invalid query filter clause specified for property 'userState' of resource 'User'.
RequestId: fd1ceb65-e193-4e18-8095-90808d1e824e
DateTimeStamp: Sun, 12 Jul 2020 09:11:18 GMT
HttpStatusCode: BadRequest
HttpStatusDescription: Bad Request
HttpResponseStatus: Completed

At line:1 char:1
+ Get-AzureADUser -SearchString 'AdeleV'
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-AzureADUser], ApiException
    + FullyQualifiedErrorId : Microsoft.Open.AzureAD16.Client.ApiException,Microsoft.Open.AzureAD16.PowerShell.GetUser
[Enter feedback here]

A workaround is:
(Get-AzureADUser -Filter "startswith(userPrincipalName,'$($user.UserName)')").UserPrincipalName

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd399165-9390-cce4-93e9-e2907f842496
* Version Independent ID: 31fa2e85-928c-5a3d-fb03-7d7a94864810
* Content: [Add test data to your Office 365 test tenant - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/test-data)
* Content Source: [msteams-platform/concepts/build-and-test/test-data.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/build-and-test/test-data.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Geetha63** [comment]
Hi @mpowrie,

Please check PowerShell version once , as command (Get-AzureADUser -SearchString $user.UserName).UserPrincipalName is working in Version 5.1.18362.145.Thank You, Geetha
