### ISSUE TITLE
Suggestion on the sample code (C#/.NET fetching roster)

### ISSUE THREAD

**Issue by tsujonathan** [MicrosoftDocs/msteams-docs#1881]
Hello,

We were wondering why you didn't use AddRange() in the code sample? 
AddRange is more efficient than Concat.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca47e045-6669-e130-c75a-df31ab2fa3e8
* Version Independent ID: de5e719f-c97a-0fee-c83d-f6ca176191b2
* Content: [Get Team's specific context for your bot - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/get-teams-context?tabs=dotnet#fetching-the-roster-or-user-profile)
* Content Source: [msteams-platform/bots/how-to/get-teams-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/bots/how-to/get-teams-context.md)
* Product: **msteams**
* GitHub Login: @clearab
* Microsoft Alias: **anclear**

**Comment by Gousia-MSFT** [comment]
```
 protected override async Task OnMessageActivityAsync(ITurnContext<IMessageActivity> turnContext, CancellationToken cancellationToken)

        {
            var members = new List<TeamsChannelAccount>();
            string continuationToken = null;

            do
            {
                var currentPage = await TeamsInfo.GetPagedMembersAsync(turnContext, 100, continuationToken, cancellationToken);
                continuationToken = currentPage.ContinuationToken;
                members.AddRange(currentPage.Members);
            }
            while (continuationToken != null);
        }
```

**Comment by Gousia-MSFT** [comment]
@tsujonathan Thanks for reaching out to us. We are working on updating the code. @laujan Please help to update the code in docs with the above one.
