### ISSUE TITLE
Placeholder Image displayed on click of teams images in chat

### ISSUE THREAD

**Issue by gondhijagapathi** [MicrosoftDocs/msteams-docs#1885]
Placeholder Image is displayed when an image is received from any chat 
previously it was functional 

[Image](https://user-images.githubusercontent.com/23327757/87385315-660e7080-c5bb-11ea-8167-92b8f33bdf3d.png)

**Comment by Nikitha-MSFT** [comment]
This is by design. If you want to get more clarity could you please post the query to [product-support-channels](https://docs.microsoft.com/en-us/microsoftteams/platform/feedback#product-support-channels)?
