### ISSUE TITLE
Screen sharing is broken in the newest Linux App version

### ISSUE THREAD

**Issue by savar** [MicrosoftDocs/msteams-docs#1891]
Using https://packages.microsoft.com/repos/ms-teams/pool/main/t/teams/teams_1.3.00.16851_amd64.deb when I try to start sharing my screen the screen is only becoming black with a red border. If I use that on the same screen as the app is running, the screen becomes "lost" until I kill teams as I cannot "stop" the sharing anymore. The previous version works fine though:
https://packages.microsoft.com/repos/ms-teams/pool/main/t/teams/teams_1.3.00.5153_amd64.deb

I am still unsure if this happens only on a multi screen or only in my setup.

OS: Debian unstable/ Linux Kernel 5.7.6-1 (2020-06-24)
Window Manager: i3

If you need more information please tell me what you want to get.

**Comment by Gousia-MSFT** [comment]
@savar Please go ahead and post this query to [Product support channels](https://docs.microsoft.com/en-us/microsoftteams/platform/feedback#product-support-channels).
