### ISSUE TITLE
getAuthToken api doc missing

### ISSUE THREAD

**Issue by koushik-shetty** [MicrosoftDocs/msteams-docs#1892]
https://github.com/OfficeDev/microsoft-teams-library-js/blob/60a3f0795dfc40b217cb86f38252fc778270a092/src/public/authentication.ts#L73

API is missing from the page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89e79849-bf25-dd0a-4680-c1074966051b
* Version Independent ID: fee94efc-fe9c-6460-1df8-f9bc97abf526
* Content: [Using the Teams client SDK - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/using-teams-client-sdk)
* Content Source: [msteams-platform/tabs/how-to/using-teams-client-sdk.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tabs/how-to/using-teams-client-sdk.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Subhasish-msft** [comment]
@koushik-shetty, Thanks for pointing it out, we ll update the doc.
