### ISSUE TITLE
Paste from clipboard operation works intermittently

### ISSUE THREAD

**Issue by osudude** [MicrosoftDocs/msteams-docs#1893]
I frequently capture screen shots either in [snagit](https://www.techsmith.com/screen-capture.html) or windows snipping tool and will attempt to paste them into teams chat or channel.  The paste operation frequently fails silently.  When this happens, I have to paste the clipboard contents to mspaint, re-copy image to clipboard, and re-paste into msteams.  This is my hacky workaround.

1.3.00.19173 64 bit
Windows 10 1809 17763.1282

**Comment by Gousia-MSFT** [comment]
@osudude Please go ahead and post your queries to [Product support channels](https://docs.microsoft.com/en-us/microsoftteams/platform/feedback#product-support-channels).
