### ISSUE TITLE
how to get / create conversation

### ISSUE THREAD

**Issue by Unders0n** [MicrosoftDocs/msteams-docs#1895]
CreateOrGetDirectConversation from client.Conversations.CreateOrGetDirectConversation is missing in regular ConnectorClient, so i've installed Microsoft.Bot.Connector.Teams and seems like it have this extension method, but i think they have some compatibility problems with regular assembly of latest version and i'm not able to create an object: 
 var convId = await connector.Conversations.CreateOrGetDirectConversation(
               new ChannelAccount("someuserid", "some user name", "User", null),
                new ChannelAccount("somebotid", "bot", "Bot", null),
                "some-tenant-id");

![изображение](https://user-images.githubusercontent.com/18035628/87686193-e3d5a600-c78c-11ea-9435-0033d0cd1084.png)

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ad9f167-7d29-f933-7b47-60bd744899b1
* Version Independent ID: 8097fcbd-adcc-ce49-a378-426c65af9296
* Content: [Send proactive messages - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/send-proactive-messages?tabs=dotnet#obtain-necessary-user-information)
* Content Source: [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/bots/how-to/conversations/send-proactive-messages.md)
* Product: **msteams**
* GitHub Login: @clearab
* Microsoft Alias: **anclear**

**Comment by Gousia-MSFT** [comment]
@Unders0n Are you trying to [send a proactive message?](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/send-proactive-messages?tabs=dotnet) Could you please try out the sample [here](https://github.com/microsoft/BotBuilder-Samples/blob/3dc68f48367a9e31d09c884aa157fc10c4bf7d33/samples/csharp_dotnetcore/57.teams-conversation-bot/Bots/TeamsConversationBot.cs#L131) and see if that helps?

**Comment by Unders0n** [comment]
> 
> 
> @Unders0n Are you trying to [send a proactive message?](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/send-proactive-messages?tabs=dotnet) Could you please try out the sample [here](https://github.com/microsoft/BotBuilder-Samples/blob/3dc68f48367a9e31d09c884aa157fc10c4bf7d33/samples/csharp_dotnetcore/57.teams-conversation-bot/Bots/TeamsConversationBot.cs#L131) and see if that helps?

this example working from bot context (and heavily using turnContext) , what i need is standalone sample, let's say function called from method of controller.

**Comment by Unders0n** [comment]
update:
i've managed to work with regular connector, only with this code (none of other examples provided in docs worked):

```
 var botAccount = new ChannelAccount(_configuration.GetValue<string>("TeamsBotId"));
            var userAccount = new ChannelAccount(userId);

            AppCredentials.TrustServiceUrl("https://smba.trafficmanager.net/emea/", DateTime.MaxValue);

            var account = new MicrosoftAppCredentials(_configuration.GetValue<string>("MicrosoftAppId"),
                _configuration.GetValue<string>("MicrosoftAppPassword"));
          
            var connector = new ConnectorClient(new Uri("https://smba.trafficmanager.net/emea/"), account);

            var conversationParameters = new ConversationParameters
            {
                Bot = botAccount,
                Members = new List<ChannelAccount> {userAccount},
                IsGroup = false,
                ChannelData = new TeamsChannelData
                {
                    Tenant = new TenantInfo(_configuration.GetValue<string>("TeamsTenantId"))
                }
            };

            var response = await connector.Conversations.CreateConversationAsync(conversationParameters);

            var message = Activity.CreateMessageActivity();
            message.From = botAccount;
            message.Recipient = userAccount;
            message.Conversation = new ConversationAccount(id: response.Id);
            message.Text = messageText;
            message.Locale = "en-Us";
            await connector.Conversations.SendToConversationAsync((Activity) message);
```

so questions: 1)is this recommended way of doing proactive messages 2)any info on how we can easily get teams userId knowing email and if those Teams Extension lib should be working? 
Thanks

**Comment by Gousia-MSFT** [comment]
@Unders0n 
1. Yes, you could use this code to send a proactive message.
2. You can get the user unique id(29:XXX id) required to send proactive message only from the Bot. We do not have any API that can fetch the user id using email id. You could also get that by [fetching the roster](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/get-teams-context?tabs=dotnet) of a team where the user is part of, if you have the team id.
