### ISSUE TITLE
302 Found ngrok debug locally hosted (Tab App)

### ISSUE THREAD

**Issue by AlexisDominguez** [MicrosoftDocs/msteams-docs#1897]
I'm trying to test an app locally hosted using ngrok with the following command:

ngrok http <port> --host-header=localhost:<port>

But when I access this url by an <iframe> or with the contentUrl property in the file manifest.json, my app doesn't run and my ngrok terminal just shows 302 Found message.

¿How can I solve this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ba912c7-3f70-3406-ad5c-06b6a0fc3875
* Version Independent ID: d3717482-cd3c-32ec-c7e0-28612bf13c37
* Content: [Run and debug your app - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/debug)
* Content Source: [msteams-platform/concepts/build-and-test/debug.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/build-and-test/debug.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Nikitha-MSFT** [comment]
Are you able to access the application on browser using ngrok URL ? Also Could you please share screen shot of the error?
