### ISSUE TITLE
How to re-show the "Almost there" popup when using the SSO?

### ISSUE THREAD

**Issue by kafka-yu** [MicrosoftDocs/msteams-docs#1898]
Hi team,

Got a question about the SSO. 

I've successfully implemented the SSO in Teams task module. Is there any way to make the "Almost done" popup show again? (this picture:
https://docs.microsoft.com/en-us/microsoftteams/platform/assets/images/tabs/tabs-sso-prompt.png)
![image](https://user-images.githubusercontent.com/3942409/87697621-e3590180-c7c4-11ea-9225-17133b925be2.png)

We want to test the flow but cannot find a way to show this popup again..

Thank you!

**Comment by Subhasish-msft** [comment]
@kafka-yu  Yes, you need to go to https://account.activedirectory.windowsazure.com/r#/applications and revoke consent for the app. Because AAD caches the token locally. it's best to then sign into Teams in an inPrivate browser session to ensure that the consent prompt is triggered again.

**Comment by kafka-yu** [comment]
@Subhasish-msft  thank you!
