### ISSUE TITLE
Is the SSO support GA already?

### ISSUE THREAD

**Issue by kafka-yu** [MicrosoftDocs/msteams-docs#1899]
Hi Team,

Is the SSO support GA already?
We can use it in production right?

Thanks!

**Comment by Subhasish-msft** [comment]
@kafka-yu , Yes it is available for web and desktop. Mobile will be available soon.

**Comment by kafka-yu** [comment]
Thank you! @Subhasish-msft 

BTW, I have another question, it is very appreciated if you can help look https://github.com/MicrosoftDocs/msteams-docs/issues/1898

Thank you!!
