### ISSUE TITLE
Away status not clearing when active on computer

### ISSUE THREAD

**Issue by bhigginsah4r** [MicrosoftDocs/msteams-docs#1905]
Good morning,

One of my users came across an issue where her status is not updating to Available even though she is currently working on the computer she has teams installed on.

We've tried reinstalling teams on the computer but the only way for her status to update to available is for her to maximize the teams window.
![ccfb7a7e-d06a-470d-a06e-af6ef418e405](https://user-images.githubusercontent.com/68560113/87967781-373d4200-ca74-11ea-8697-63bdc3c9a1ef.png)

**Comment by Gousia-MSFT** [comment]
@bhigginsah4r Please go ahead and post this query to the [Teams product support](https://docs.microsoft.com/en-us/microsoftteams/platform/feedback#product-support-channels) channel.
