### ISSUE TITLE
Compose Extension "canUpdateConfiguration" boolean preventing app pinning

### ISSUE THREAD

**Issue by liangchr** [MicrosoftDocs/msteams-docs#1906]
When I add "canUpdateConfiguration" value to my manifest the user loses the ability to pin the app. 

Can pin app: 
```
"composeExtensions": [
    {
      "botId": "XXX",
      "commands": [
            {
              "id": "Start Meeting",
              "type": "action",
              "context": ["compose", "message", "commandBox"],
              "initialRun": true,
              "description": "Command to run action to create a Card from Compose Box",
              "title": "Start Meeting",
              "fetchTask": true
            }

        ]
    }
  ],
```
**Cannot** pin app: 
```
"composeExtensions": [
    {
      "botId": "XXX",
      **"canUpdateConfiguration": true,**
      "commands": [
            {
              "id": "Start Meeting",
              "type": "action",
              "context": ["compose", "message", "commandBox"],
              "initialRun": true,
              "description": "Command to run action to create a Card from Compose Box",
              "title": "Start Meeting",
              "fetchTask": true
            }

        ]
    }
  ]
```

**Comment by Gousia-MSFT** [comment]
@liangchr We could not repro the issue. I am able to pin the app even if i have "canUpdateConfiguration" to true in my manifest:
![image](https://user-images.githubusercontent.com/45553518/88034755-c3c42f00-cb5e-11ea-8df9-0665f54db4a0.png)

Manifest:

![image](https://user-images.githubusercontent.com/45553518/88034811-d63e6880-cb5e-11ea-9411-1610d62a3e5d.png)
Could you please confirm if this is how you are trying to pin it?

**Comment by liangchr** [comment]
Yes-- That is how I am trying to pin it. I can't even right-click on the application icon. (no menu pops up.) When I have the canUpdateConfiguration toggled on. 

I will add I didn't have a message extension "settings" endpoint. (So if I click settings it was returning an error.)But I don't think they would be related.

**Comment by Gousia-MSFT** [comment]
@liangchr I could not repro the issue on my side. Could you please share your complete manifest with us?

**Comment by Gousia-MSFT** [comment]
Please re-open with requested information if you are still facing this issue
