### ISSUE TITLE
Limitations in teams markdown

### ISSUE THREAD

**Issue by masayyad** [MicrosoftDocs/msteams-docs#1909]
I found out 2 ui limitations using teams markdown
1. Image in simple bot message is always rendered as 256*256. There is no way to specify size in normal bot messages.
2. Both preformatted and link applied are not reflecting in teams whereas it is working fine in github markdown .For example: 
In github, I am able to render both link and preformat[`hello`](link). But, in teams, it is still `hello`.

Can u pls provide me an alternative to achieve this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b62aabd-f012-24c9-0edf-e840b20a9dfc
* Version Independent ID: a5c79257-d3a7-c9b5-8a98-7e1495b08a7e
* Content: [Format your bot messages - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/format-your-bot-messages)
* Content Source: [msteams-platform/bots/how-to/format-your-bot-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/bots/how-to/format-your-bot-messages.md)
* Product: **msteams**
* GitHub Login: @clearab
* Microsoft Alias: **anclear**

**Comment by Subhasish-msft** [comment]
@masayyad , 
I could able to reproduce it. with below code 
![image](https://user-images.githubusercontent.com/56869764/88168490-20dfe380-cc38-11ea-9341-47aae659e64a.png)
I get the bot message as
![image](https://user-images.githubusercontent.com/56869764/88168512-2a694b80-cc38-11ea-9ac1-06d9cf85451a.png)

I am discussing these issues with internal team. Thanks for pointing it out.

**Comment by Subhasish-msft** [comment]
@masayyad, Image rendering is currently by design. Regarding formatting, We have created a bug for this and will be tracking it internally.

**Comment by Trinetra-MSFT** [comment]
This is by design we don't assign special style for any <code> content, while all <code> just defines in unified styling. However, this link indeed is working. There's no malfunction.
