### ISSUE TITLE
Can Teams grant microphone permission for the authentication popup window in desktop client?

### ISSUE THREAD

**Issue by kafka-yu** [MicrosoftDocs/msteams-docs#1910]
Hi There,

Currently, we use the Teams JS SDK to open the authentication window as below code snippets shown.
```
microsoftTeams.authentication.authenticate({url: '<our page URL>'});
```

We meet a problem is that when our customers try to use a microphone (e.g. to make a webRTC call) in the popup window, it says the permission denied. 
![image](https://user-images.githubusercontent.com/3942409/88020635-abecab00-cb5e-11ea-92bf-a0e3603857e1.png)

Is there any chance to get the microphone permission granted in that popup window? 

NOTE: We have configured the Device Permissions in our app's manifest.

Thank you!
Rukai.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 503e124f-2b80-d6ae-581a-ca77f0a1999f
* Version Independent ID: 66d2bd8a-536b-1a45-f71c-eb2a0199de46
* Content: [Add authentication to your messaging extension - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/add-authentication)
* Content Source: [msteams-platform/messaging-extensions/how-to/add-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/messaging-extensions/how-to/add-authentication.md)
* Product: **msteams**
* GitHub Login: @clearab
* Microsoft Alias: **anclear**

**Comment by kafka-yu** [comment]
Any one can help? Thank you!

**Comment by kafka-yu** [comment]
@sabinn-msft Hi man, sorry for trouble. Would you pls help on this question? Thank you!

**Comment by sabinn-msft** [comment]
Would have loved to, but I don't own this area.

**Comment by kafka-yu** [comment]
Thanks @sabinn-msft 

@Wajeed-msft  do you know anyone from (MSFT) could help with this? Thank you very much!

**Comment by Wajeed-msft** [comment]
Somehow I missed this one. @Abhijit-MSFT  - Could you please check this issue?

**Comment by kafka-yu** [comment]
> Somehow I missed this one. @Abhijit-MSFT - Could you please check this issue?

Hello, is there any one can help?

The microphone permission is also not granting to our tab in the Popout chat window.

**Comment by mademic** [comment]
does anyone know if the problem is fixed? I'm trying to enable the microphone permission for a popout but it doesn't work
In the Main Window my App works fine.

**Comment by 1mehmood0** [comment]
I tired to use the [teams documentation for permission](https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/main/samples/tab-device-permissions/nodejs/src/components/CaptureAudio.tsx)
But in Task module of team where my web app is opening,  I am unable to use this function by calling it from the button on my main web app.
It gives the `DOMException:Permission Denied`
Any kind of help will be appreciated.

**Comment by sayali-MSFT** [comment]
@1mehmood0  @kafka-yu -Could you please confirm, have you enabled the below permission through Sheild icon?
![tab](https://github.com/MicrosoftDocs/msteams-docs/assets/93527375/479919c9-bfe1-4597-9052-12ea6f8c6762)
