### ISSUE TITLE
[Bug] verification of phone number for personal (MS 365 family) account fails

### ISSUE THREAD

**Issue by southy-j** [MicrosoftDocs/msteams-docs#1911]
Hi,

thanks for tailoring Teams to also be used in a family context. Greatly apprechiated.
It's just... it doesn't work.
iOS, current released version. 
See screenshots - the code I get texted for verification of the phone number will not be accepted.

Forums suggest I'm not the only one with this problem (in fact: 5 of 6 users seem to have this problem, see [here ](https://stadt-bremerhaven.de/microsoft-teams-neue-funktionen-fuer-privatanwender-offiziell-verfuegbar/#comment-1106348 ).

Please fix!
![teams verify](https://user-images.githubusercontent.com/67008070/88053789-ae4e0580-cb5c-11ea-9fcb-c87df3a18fd0.png)

BTW, another small Bug (?) 
In my desperate attempts to solve above problem I managed to add my personal email address somehow under my _corporate_ account. See the third account in the picture below. 
How did that happen and how do I get rid of it again?
![teams2](https://user-images.githubusercontent.com/67008070/88054278-5c59af80-cb5d-11ea-8927-5353173a22ee.jpg)

Thanks and BR,
jan

**Comment by southy-j** [comment]
It get even weirder:

If I do not use (as would be correct):
[+49] 171123456   

but  (NOT correct - note the extra zero):
[+49]  017112345 

then the verification goes through, albeit leaving me with a completely messed up number in my profile and no way to correct it:
Note the extra "49".  
Guys, your verification system and the attached RegExes are *seriously* messed up.

![image](https://user-images.githubusercontent.com/67008070/88068341-5ae5b280-cb70-11ea-9573-179304ba7060.png)

**Comment by Gousia-MSFT** [comment]
@southy-j Could you please post this query to the [Microsoft Support.](https://support.microsoft.com/) They will be able to help you better on this. Thanks!

**Comment by southy-j** [comment]
Thanks, Gousia!
