### ISSUE TITLE
Share screen BUG on desktop app allows any ATTENDEE in a meeting to present their screen without having the permission.

### ISSUE THREAD

**Issue by Acefighter371** [MicrosoftDocs/msteams-docs#1915]
This bug happens when we minimize our teams window in the middle of a meeting. It gets minimized into a small window on the bottom right on the desktop app. It contains video,audio toggle, hang up and then there is share screen. when we try sharing in a meeting while we are attendees the share screen button is grayed out. but when we minimize to the little window on bottom right. then we see a share screen button that is operational and can be used by anyone. Microsoft please look into this issue as it create a lot of meeting bombings.

**Comment by Gousia-MSFT** [comment]
@Acefighter371 Thanks for reaching out to us. This is a known issue. We have a bug on this which we are working on.  Currently we do not have an ETA for the fix to share with you.

**Comment by Acefighter371** [comment]
Hello, thank you for your attention on this bug. i am Aryaman Singh Bais
from India and i have been attending online classes regularly. during
which i found this bug by accident when i minimized my screen and noticed
the share screen button on the small window operational. i was curious so i
pressed it and it worked even though i didnt have permission. so i thought
of reporting this on the github forum. Again i thank you for your attention
and i hoped it will be resolved soon :)

Regards
