### ISSUE TITLE
Mention that manifestVersion must be set to devPreview

### ISSUE THREAD

**Issue by meum** [MicrosoftDocs/msteams-docs#1917]
I spent several hours trying to figure out why Teams would not accept my manifest, it turns out to be because of manifestVersion not being set to devPreview.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac64d14f-aec8-9dd6-e987-d2325de46fd6
* Version Independent ID: ba050a58-d98a-68f7-3190-8001d2a9d12c
* Content: [Registering a calling and meeting bot for Microsoft Teams - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/calls-and-meetings/registering-calling-bot)
* Content Source: [msteams-platform/bots/calls-and-meetings/registering-calling-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/bots/calls-and-meetings/registering-calling-bot.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Nikitha-MSFT** [comment]
Hi @meum - 

> There's a new version of the Teams app manifest with two additional settings, supportsCalling and supportsVideo. These settings are included in the Developer Preview version of the Microsoft Teams app manifest.

This  point has mentioned in the begging of the docs as shown in the screen shot:
![image](https://user-images.githubusercontent.com/61688740/88362640-eb074000-cd9a-11ea-9882-3800e14f8ca7.png)
