### ISSUE TITLE
Share button error

### ISSUE THREAD

**Issue by alinafedorchenko** [MicrosoftDocs/msteams-docs#1918]
Hello, we have this  error on your popup console when clicking share to Microsoft teams button on our site

`main-a8d2184b40e7ee6f.js:1 Core: Core Initialization: Error in authenticationUsers subscription:  Error: GraphQL error: Cannot return null for non-nullable field AuthenticationUser.id.
    at new t (vendors-a5ea4f55872d6214.js:1)
    at vendors-a5ea4f55872d6214.js:1
    at vendors-a5ea4f55872d6214.js:1
    at Set.forEach (<anonymous>)
    at vendors-a5ea4f55872d6214.js:1
    at Map.forEach (<anonymous>)
    at e.broadcastQueries (vendors-a5ea4f55872d6214.js:1)
    at vendors-a5ea4f55872d6214.js:1
    at Object.next (vendors-a5ea4f55872d6214.js:1)
    at v (vendors-a5ea4f55872d6214.js:1)
e.invoke @ main-a8d2184b40e7ee6f.js:1
main-a8d2184b40e7ee6f.js:1 ShareFormFatalError: ShareFormFatalError: undefined-undefined, Unknown, GraphQL error: Cannot return null for non-nullable field AuthenticationUser.id.
e.invoke @ main-a8d2184b40e7ee6f.js:1
vendors-a5ea4f55872d6214.js:1 TypeError: Cannot read property 'scenarioFactory' of undefined
    at pe (main-a8d2184b40e7ee6f.js:1)
    at Jo (vendors-a5ea4f55872d6214.js:1)
    at wu (vendors-a5ea4f55872d6214.js:1)
    at bc (vendors-a5ea4f55872d6214.js:1)
    at yc (vendors-a5ea4f55872d6214.js:1)
    at uc (vendors-a5ea4f55872d6214.js:1)
    at nc (vendors-a5ea4f55872d6214.js:1)
    at $c (vendors-a5ea4f55872d6214.js:1)
    at vendors-a5ea4f55872d6214.js:1
    at sc (vendors-a5ea4f55872d6214.js:1)
au @ vendors-a5ea4f55872d6214.js:1
main-a8d2184b40e7ee6f.js:1 Uncaught (in promise) Object
main-a8d2184b40e7ee6f.js:1 Uncaught (in promise) TypeError: Cannot read property 'scenarioFactory' of undefined`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5964e0a9-bba0-c5a3-8099-f3845037726c
* Version Independent ID: 24565c3b-2bb5-2482-a6c7-7b1f62e38abb
* Content: [Share to Teams embedded button - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/share-to-teams#feedback)
* Content Source: [msteams-platform/concepts/build-and-test/share-to-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/build-and-test/share-to-teams.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Trinetra-MSFT** [comment]
@alinafedorchenko , it seems the issue is with authenticating the user, Could you please try with some other user?

**Comment by alinafedorchenko** [comment]
Yep, this didn't solve the problem

**Comment by chaimann** [comment]
can confirm I'm having this error too 
![image](https://user-images.githubusercontent.com/5694393/88794693-85a2bd00-d1a7-11ea-92b1-06efb3c839bf.png)

**Comment by ChetanSharma-msft** [comment]
Hello @Everyone,
Sorry for delay in response.

Please follow below documentation and try it once from your end?
https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/share-to-teams-from-web-apps

**Please refer this sample:** https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/app-link-unfurling-in-share-to-teams/csharp
