### ISSUE TITLE
Is Teams allow pre-install the bot to the chat?

### ISSUE THREAD

**Issue by kafka-yu** [MicrosoftDocs/msteams-docs#1920]
Is Teams allow pre-install the bot to the chat?

Currently I need to invite the bot by using the justInTimeInstall to do this each chat/team.
``` 
msteams: {
            justInTimeInstall: true,
          },
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3af8496d-46be-a691-11e1-16734f71f891
* Version Independent ID: be0ff3e1-8bef-5ca7-8d9c-566e89e3fd41
* Content: [What are conversational bots? - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/what-are-bots)
* Content Source: [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/bots/what-are-bots.md)
* Product: **msteams**
* GitHub Login: @clearab
* Microsoft Alias: **anclear**

**Comment by kafka-yu** [comment]
@sabinn-msft Hi man, sorry for trouble. Would you pls help on this question? Thank you!

**Comment by Subhasish-msft** [comment]
@kafka-yu , You could to this from Teams Admin center. Here is the [doc link](https://docs.microsoft.com/en-us/microsoftteams/teams-app-setup-policies#create-a-custom-app-setup-policy)

**Comment by Wajeed-msft** [comment]
In case you are looking to [install App via Graph APIs](https://docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-beta) in group chat, currently it's supported only in personal & team scope.

**Comment by kafka-yu** [comment]
@Wajeed-msft Thank you!

I saw this solution is to install the Teams app, but not the "bot"?

Cause we see currently in each chat, I need to install the bot to the chat via the message extension first time I use it, as is described here:
https://docs.microsoft.com/en-us/microsoftteams/platform/resources/messaging-extension-v3/create-extensions?tabs=typescript#request-to-install-your-conversational-bot

So is there any way to automatically do this step? Without prompt out the install dialog?

Thanks!

**Comment by Wajeed-msft** [comment]
> I saw this solution is to install the Teams app, but not the "bot"?

Bot is one of the extensible points in the Teams App. Graph API applies for [Microsoft Teams App](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/extensibility-points) including Bot, Tab, Messaging Extension, Connector.

> So is there any way to automatically do this step? Without prompt out the install dialog?

Currently installation to group chat is not supported and would be listed [here](https://docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-beta) once it's available.
