### ISSUE TITLE
Cannot see connectors when selecting more options

### ISSUE THREAD

**Issue by petfrase** [MicrosoftDocs/msteams-docs#1921]
I am trying to setup incoming webhooks for a team channel but connectors doesn't even show up

**Comment by Gousia-MSFT** [comment]
@petfrase Could you please check if the connectors option is disabled for your team? 
![image](https://user-images.githubusercontent.com/45553518/88509293-5f8de900-cffe-11ea-9b41-734e7df9bef4.png)
You can check that under Manage Team->Settings-> Member permissions.

**Comment by petfrase** [comment]
Yes i have turned on the member permissions

**Comment by Gousia-MSFT** [comment]
@petfrase Are you a guest user in the tenant where you are seeing this? Could you please check if [Connectors are disabled](https://support.microsoft.com/en-us/office/connect-apps-to-your-groups-in-outlook-ed0ce547-038f-4902-b9b3-9e518ae6fbab?ui=en-us&rs=en-us&ad=us) by your admin for the group ?

**Comment by Gousia-MSFT** [comment]
Please re-open if you are still facing this issue
