### ISSUE TITLE
SSO third party app Microsoft Teams tabs

### ISSUE THREAD

**Issue by Bryand13** [MicrosoftDocs/msteams-docs#1924]
Hello guys
Hope all of your are doing good!

My question is: Is SSO working with third party apps in Teams?

We have an AppService under ***.azurewebsites.net** when the user goes to that page throught browser, it ask for credentials(actually credentials are not necessary already since it does SSO throught ADFS), then he access to an external bot developed with SAP.
So, our client wants this access in a MS Teams Tab. We have the custom tab in Teams, but we are keeping stuck in the ADFS login page.

We need to implement SSO. As i said, is SSO working with third party apps? If so, where can i find that info?

Thanks in advance 
Appreciate any comment

**Comment by Gousia-MSFT** [comment]
@Bryand13 Yes, SSO for tabs is now available. Could you please check [Authentication using SSO for tabs](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-aad-sso). Here is a [sample code ](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-aad-sso#sample-code)you could try out.

**Comment by Bryand13** [comment]
Hello @Gousia-MSFT 
Thank you for your response.

Will the SSO work with third party apps in MS Teams? I did could check the information, but there is not clear information about if the SSO will work with third party apps.

In other hand, with my AppService in Azure under *.azurewebsites.net, as per documentation, it won't work because isn't supported, right?

Sorry if i missed something.
Thanks in advance

**Comment by Gousia-MSFT** [comment]
@Bryand13 Yes, SSO for tabs can be used for third party apps as well. Are you facing any particular issue while implementing it?

**Comment by Bryand13** [comment]
Hi @Gousia-MSFT ,
Ok, thank you for the info. No, I'm not. Just wanted to know if the SSO functionality was working also with third party apps.

Right now the SSO functionality in mobile devices is in preview. Do you know when it will released offially? Thanks in advance

**Comment by Gousia-MSFT** [comment]
@Bryand13 Our team is working on it. It should be available on mobile soon. But we cannot give you a firm ETA on this.

**Comment by Bryand13** [comment]
Ok @Gousia-MSFT i understand. Anyway thanks for answering to my questions.
Best regards
