### ISSUE TITLE
Create 1:1 conversation api-- can a conversation be initialized without messaging?

### ISSUE THREAD

**Issue by liangchr** [MicrosoftDocs/msteams-docs#1927]
If I create a 1:1 conversation with a user (using [here](https://github.com/clearab/teamsProactiveMessaging/blob/f074be9f0377b761d62c1594ac4d090501becfd0/MessageSender.cs#L28) ) and I want to reference that conversation whenever I need to get a user's info using endpoint: {{serviceUrl}/v3/conversations/{conversationID}/members}. 

Do I first have to have the bot say something into the conversation. Or just creating it with the api call enough? I just want to make sure because without the bot saying anything I can't see the conversation popup in the conversation list in msteams, and I am unsure if I can use: {{serviceUrl}/v3/conversations/{conversationID}/members}. 

(Also I cannot test it because I already created a conversation with my testing users and I can't delete 1:1 conversations.)

Any help would be appreciated. Best

**Comment by Nikitha-MSFT** [comment]
By using [this](https://github.com/clearab/teamsProactiveMessaging/blob/f074be9f0377b761d62c1594ac4d090501becfd0/MessageSender.cs#L28) you will get the informatiom to create a conversation. You can create conversation using CreateConversationAsync method. Could you please check this [sample](https://github.com/microsoft/BotBuilder-Samples/blob/master/samples/csharp_dotnetcore/57.teams-conversation-bot/Bots/TeamsConversationBot.cs#L152)? by using this method you will get conversation id in the activity.

**Comment by liangchr** [comment]
@Nikitha-MSFT Thankyou for getting back to me. I just want to clarify one thing. Does this method alone suffice for creating a conversation? I won't need to first message in the conversation with my bot correct? (AKA, can a 1:1 conversation exist even if messages are not sent.)

**Comment by Nikitha-MSFT** [comment]
Yes when you use this method it will create a new empty chat with specified data if you don't send any message using bot. You can store conversation id for further references.

**Comment by liangchr** [comment]
Okay, thanks for the help @Nikitha-MSFT
