### ISSUE TITLE
Is this feature available on free version of Teams?

### ISSUE THREAD

**Issue by sagarpomal** [MicrosoftDocs/msteams-docs#193]
Is this feature available on free version of Teams?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5307fe5c-a6f0-59e2-d125-69051ab58595
* Version Independent ID: ca3f41d9-1c2a-6cde-b780-61fec8f0fcb6
* Content: [Sending and receiving files from a bot - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/bots/bots-files)
* Content Source: [msteams-platform/concepts/bots/bots-files.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/bots/bots-files.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by billbliss** [comment]
We are looking into this.

**Comment by billbliss** [comment]
OK sorry for the delay. It should be available, but we haven't tested it specifically. Right after you posted this we thought it didn't work, but it happened about the same time we released a "supportsFiles" feature - bots that want to do this must opt-in as per https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/bots/bots-files.

**Comment by sagarpomal** [comment]
@billbliss we have created a bot in Teams using Bot Framework and looks like this won't help us as it's taken care by Bot-Framework. Should we reach out to the Bot-Framework team?

**Comment by Wajeed-msft** [comment]
@sagarpomal - Microsoft Teams is one of the channel supported in Microsoft Bot framework. Did you try sideloading manifest file with bot having supportsFiles flag? Are you facing any problem while trying to upload files in 1:1 conversation with Bot?

**Comment by sagarpomal** [comment]
@Wajeed-msft : Yes, it's supported but we haven't tried side loading manifest file. Do you have any reference or documentation on how to do that?

**Comment by sagarpomal** [comment]
@Wajeed-msft : Thanks a lot.
