### ISSUE TITLE
Outgoing webhook app no longer available within Teams

### ISSUE THREAD

**Issue by DaveVoyles** [MicrosoftDocs/msteams-docs#1931]
The document states:

"_Select the appropriate team and select Manage team from the (•••) drop-down menu.
Choose the Apps tab from the navigation bar.
From the window's lower right corner select Create an outgoing webhook_"

Although this option for an App is longer present in Teams. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb9c5bd5-1ac6-dcc8-4ed6-d6aad2432776
* Version Independent ID: 43e90995-bba4-86b6-1f1c-ab749e546a4b
* Content: [Add custom bots to Microsoft Teams with outgoing webhooks - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-outgoing-webhook)
* Content Source: [msteams-platform/webhooks-and-connectors/how-to/add-outgoing-webhook.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/webhooks-and-connectors/how-to/add-outgoing-webhook.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **laujan**

**Comment by DaveVoyles** [comment]
I found it! 

Could I suggest making it more visible and appear like the other apps, rather than hide down there. Also, you cannot search for this in the "More Apps" section either, making it even more difficult to find.

![image](https://user-images.githubusercontent.com/1786053/88812625-f20cc480-d185-11ea-9ace-de79c04759a0.png)

**Comment by Gousia-MSFT** [comment]
@DaveVoyles Thanks for sharing your suggestion. We will consider this. You can also go ahead and raise a [uservoice ](https://microsoftteams.uservoice.com/)for Microsoft Teams.
