### ISSUE TITLE
Issues with deep linking meet now meetings

### ISSUE THREAD

**Issue by csnarain** [MicrosoftDocs/msteams-docs#1932]
We have a problem with deep linking meet now meetings in Teams.

We generate our meet now meetings using graph api (/me/onlineMeetings). When we try to deep link these meetings use it behind a button in our Teams tab app, each user who clicks the link is landing into their own isolated meeting space without being able to communicate with each other. However, if we try to use these meeting urls without deep link, it works fine. Also deep link works fine for scheduled meetings. We're facing this problem only for meet now meetings.

**Comment by Trinetra-MSFT** [comment]
@csnarain ,  Are you seeing the lobby in meeting for Meet Now, Please share the deep link Url you have tried.

**Comment by csnarain** [comment]
@Trinetra-MSFT - I'm not being made to wait in the Lobby but actually able to join though I could not see anyone else. Others who joined the same meeting also have the same experience. Unfortunately, I can't share the full URL for confidentiality reasons but I'll provide a slightly modified one. I've also provided the steps we used to generate the deep link.

```
import * as microsoftTeams from "@microsoft/teams-js";
 

const url = "https://teams.microsoft.com/l/meetup-join/.....";
 
microsoftTeams.initialize();
microsoftTeams.executeDeepLink(url)
```

**Comment by csnarain** [comment]
@Trinetra-MSFT - Were you able to reproduce this?

**Comment by csnarain** [comment]
Can anyone confirm if Microsoft could reproduce this? This is impacting our app development activity.

**Comment by Trinetra-MSFT** [comment]
@csnarain ,We tried to reproduce this. 

![image](https://user-images.githubusercontent.com/50989436/91138314-a689ff80-e6cc-11ea-9b20-b680642e3d2d.png)

When a guest users joined the meeting they will see the lobby screen unless someone from the meeting room admit them. While creating joinWebURL you can add the users in attendee list (request body) so they can directly join without waiting in room

**Comment by Trinetra-MSFT** [comment]
@csnarain , You can mention the user in attendee list with this API: Please check this documentation
[https://docs.microsoft.com/en-us/graph/api/onlinemeeting-createorget?view=graph-rest-1.0&tabs=http#request](https://docs.microsoft.com/en-us/graph/api/onlinemeeting-createorget?view=graph-rest-1.0&tabs=http#request).

**Comment by Trinetra-MSFT** [comment]
Closing this thread as actual issue is resolve. Please feel free to reopen if you have any query regarding this.
