### ISSUE TITLE
Clarification on mentions in adaptive cards?

### ISSUE THREAD

**Issue by scyto** [MicrosoftDocs/msteams-docs#1935]
Hi is it possible to do @channel mentions or @team mentions in an adaptive card?
If it is could you document that?
If it isn't could you document that?

For per user mentions in a card.

It might be worth linking to an article how to determine the user ID syntax needed to - that seems arcane, and the example is not good.

Here is a thread **https://powerusers.microsoft.com/t5/Building-Flows/Ms-Teams-Mentions-in-adaptive-cards/td-p/520520** i must admit i don't understand the answers on this - for example I would like to use power automate to look at a list, for open items extract the user name and then send them a message.

I have this working for email.

I can't work out how to use power automate to retrieve the teams user ID and other elements or how to then populate that into a card. I haven't managed to find a sample for this either.

(alternatively i can send using the power automate plug direct to the user, i have that wokring, but sometimes one wants to post a per user mention in a card on channel)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 001a12ea-30fa-d626-18a9-02a518bfb37f
* Version Independent ID: e5f5f69e-66e9-d1b2-e19a-485d0ffcd6fa
* Content: [Text formatting in cards - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?tabs=adaptive-md%2Cconnector-html#sample-adaptive-card-with-a-mention)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-format.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-format.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Subhasish-msft** [comment]
@scyto , Currently mentioning a channel/team is not supported. We will add it to the documentation.

**Comment by scyto** [comment]
@Subhasish-msft  well that will stop me from keeping bing-ing for solution to make that work, thanks!
