### ISSUE TITLE
Bot Builder Teams deprecated, use sdk 4.6+

### ISSUE THREAD

**Issue by jeubank12** [MicrosoftDocs/msteams-docs#1944]
Navigating the links for the Microsoft Teams extensions shows that this is now deprecated in favor of 4.6+ SDK.  Please update these references

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19328d23-2791-8cd0-08f3-d3fef9edaece
* Version Independent ID: 0846b472-1bc8-9bd9-39a6-1cd66ad8743d
* Content: [Get context for your bot - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bots-context)
* Content Source: [msteams-platform/resources/bot-v3/bots-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/resources/bot-v3/bots-context.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Wajeed-msft** [comment]
@jeubank12 - [Here is the V4 documentation](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/get-teams-context?tabs=dotnet) for the same. From which page were you redirected to V3 docs?

**Comment by jeubank12** [comment]
The link in this paragraph here https://docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bots-context#nodejs-example leads you to a deprecated package

**Comment by Wajeed-msft** [comment]
@jeubank12 - Thanks for sharing the link. The [whole section under Resources](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bots-overview) if for V3 bots. 
![image](https://user-images.githubusercontent.com/31851992/89892833-e8a74180-dbf4-11ea-994d-3b60ab53b93d.png)

Please use the [V4 documentation section](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/get-teams-context?tabs=dotnet) for latest code snippets.
