### ISSUE TITLE
Unable to reach app. Task Module Skill 

### ISSUE THREAD

**Issue by MariaMendietaSpur** [MicrosoftDocs/msteams-docs#1947]
I am implementing a Bot Framework Skill that uses Task Modules. By itself, the Bot works fine but when I use it as a skill within a Simple Root Bot, I get "Unable to reach app" when invoking the task modules. I am trying both, an adaptive card task module and a task module rendering an embedded iframe. Both task modules show the same error. 

![image](https://user-images.githubusercontent.com/68560830/89370163-ebee7a80-d694-11ea-9fc0-64b2c054899d.png)

**Comment by Gousia-MSFT** [comment]
@MariaMendietaSpur Could you please take a look at [responding to TaskModule](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/task-modules/task-modules-bots#submitting-the-result-of-a-task-module). Please try putting adding a bugger and see if there is some issue in the code? Also could you please check if there are any console errors while running this on web?

**Comment by MariaMendietaSpur** [comment]
@Gousia-MSFT I found this on the logs: `2020-08-05T19:22:46.364Z Err	Unhandled exception. Error: Unable to reach app. Please try again., cause: , stack: new t@https://statics.teams.cdn.office.net/hashedjs/3.2-app.min-7699799.js:3:201585 > {anonymous}()@https://statics.teams.cdn.office.net/hashedjs/3.2-app.min-7699799.js:3:207762 > f@https://statics.teams.cdn.office.net/hashedjs/0-angular-jquery.min-eee9041.js:127:115 > {anonymous}()@https://statics.teams.cdn.office.net/hashedjs/0-angular-jquery.min-eee9041.js:127:345 > {anonymous}() (m.)$eval@https://statics.teams.cdn.office...
2020-08-05T19:22:46.363Z Err	Unhandled exception. : , cause: , stack: {anonymous}(#object,null) > printStackTrace(#object)
2020-08-05T19:22:46.363Z Inf	[Scenario]ext_post_invoke [step](1)stop (615ms/615ms)
2020-08-05T19:22:46.363Z War	HTTP request DM invoke POST failed: POST "https://amer.ng.msg.teams.microsoft.com/v1/agents/28:36e77a87-99f8-4605-b466-1a0cfa838d18/invoke", status: 502, response: {"errorCode":1008,"message":"<BotError>Bot returned unsuccessful status code NotImplemented"}, errorCode: 1008, requestId: undefined, correlationId: undefined, afdCorrelationId: undefined
2020-08-05T19:22:45.747Z War	Analytics service: Panel data not present to populate panel action, falling back to main`

**Comment by Wajeed-msft** [comment]
> {"errorCode":1008,"message":"<BotError>Bot returned unsuccessful status code NotImplemented"}, errorCode: 1008, requestId: undefined, correlationId: undefined, afdCorrelationId: undefined

Could you please confirm if you have implemented [OnTeamsTaskModuleFetchAsync](https://github.com/microsoft/BotBuilder-Samples/blob/master/samples/csharp_dotnetcore/54.teams-task-module/Bots/TeamsTaskModuleBot.cs#L30) in your code? Is request reaching to your bot endpoint? Your can debug this at your end by hosting it [locally using ngrok](https://docs.microsoft.com/en-us/microsoftteams/platform/tutorials/get-started-dotnet-app-studio#tunnel-using-ngrok).

Please let me know if you are already done this.
