### ISSUE TITLE
[Enter feedback here]

### ISSUE THREAD

**Issue by transdigiware** [MicrosoftDocs/msteams-docs#195]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cbdb8216-60c7-a0a1-7eb6-02d42d783292
* Version Independent ID: 77a75dd2-6f45-bc76-b968-0cf58c427ef5
* Content: [Requested page cannot be found. - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/publishing/apps-package)
* Content Source: [msteams-platform/404.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/404.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by NormSohl** [comment]
Thanks for pointing it out. I've fixed the obsolete links and added a redirect for external links.
