### ISSUE TITLE
Is Graph API proactive installation really in preview?

### ISSUE THREAD

**Issue by jeubank12** [MicrosoftDocs/msteams-docs#1952]
Following the link (https://docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0) to GraphAPI, it does not appear that it is preview anymore. The versioning page here (https://docs.microsoft.com/en-us/graph/versioning-and-support?view=graph-rest-1.0#current-version) indicates that anything accessible in the 1.0 docs is production-ready.

Is this feature really in preview or can the warning/note go away?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 893c2c9e-10e1-dd4e-1eb4-b4e9a46a9f8d
* Version Independent ID: 5f41c382-377c-6c9b-4932-65853675c4ad
* Content: [Use Microsoft Graph to enable proactive bot installation and messaging in Teams - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/graph-api/proactive-bots-and-messages/graph-proactive-bots-and-messages?tabs=csharp)
* Content Source: [msteams-platform/graph-api/proactive-bots-and-messages/graph-proactive-bots-and-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/graph-api/proactive-bots-and-messages/graph-proactive-bots-and-messages.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Subhasish-msft** [comment]
@jeubank12 , this link that you shared (https://docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0) is a v1.0 enpoint and already in production. 

Similar endpoints are also present in Beta version(might be with added feature) which are not yet in production. [Link here](https://docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-beta)

**Comment by jeubank12** [comment]
I got the link from the content source here: https://docs.microsoft.com/en-us/microsoftteams/platform/graph-api/proactive-bots-and-messages/graph-proactive-bots-and-messages?tabs=csharp#permissions (first sentence). It just seems very confusing to have the warning at the top and so I had no idea that I could actually use graph out of beta to install an application
