### ISSUE TITLE
Screen Share button bug (for attendees in meeting)

### ISSUE THREAD

**Issue by Sharvan9** [MicrosoftDocs/msteams-docs#1954]
This bug allows the Attendees in the meeting to project their screen without the permission of the presenters or organizer in the meeting

this bug can be use by Accesing the minimized window of teams and then click on the share button of  
![bus](https://user-images.githubusercontent.com/55787219/89501161-7f809200-d7e0-11ea-9f49-92d4d7940ed2.png)
which screenshot i have attached
![BUGs](https://user-images.githubusercontent.com/55787219/89500952-29135380-d7e0-11ea-811c-eca81920401d.png)

**Comment by Gousia-MSFT** [comment]
@Sharvan9 Thanks for reaching out to us. This is a known issue and we have a open bug on this. Our team is working on a fix for this. But we do not have a firm timeline for the fix.
