### ISSUE TITLE
How to access organization id from a bot payload

### ISSUE THREAD

**Issue by liangchr** [MicrosoftDocs/msteams-docs#1962]
Is there a good way (via graph perhaps) to get something like an organization ID for a bot? I would like to be able to know what org a team/chat/channel belongs to so my bot can assign information to team based on its organization. (This way all users in an org, regardless of team or chat have the same settings with regards to my bot. For instance, all users in an org have their calendar set to the same holidays or something.) Typically only the admin would have to initiate some config command to set these values. 

Any advice would be greatly appreciated, thanks you!

**Comment by Gousia-MSFT** [comment]
@liangchr Your Bot receives the information of the tenant in the Teams channel Data. You can find this inside turnContext.Activity. Please check the docs [here](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-basics?tabs=dotnet)

**Comment by liangchr** [comment]
@Gousia-MSFT can I used the payload information to get the users organizationID though? I know there is a graph api endpoint /organization that I can get with the tenant, but some users have multiple organizations and I want to get the organization associated with the channel id. Would this be possible?

**Comment by Gousia-MSFT** [comment]
@liangchr Your Bot receives the tenant id of the tenant from where it is invoked. So if a user is part of multiple tenants/organisations, Bot will always get the tenant id of the tenant from where it is invoked.

**Comment by liangchr** [comment]
I see. Thankyou @Gousia-MSFT I didn't realize that the id from /organization was the same as the tenantID from the bot command payload! Appreciate the clarification/help Gousia.

**Comment by Gousia-MSFT** [comment]
Sure! Glad i could help.
