### ISSUE TITLE
Missing actions/types

### ISSUE THREAD

**Issue by WizX20** [MicrosoftDocs/msteams-docs#1963]
If I'm correct, new types have been introduced and are missing on this page:
- postBack
- playAudio
- playVideo
- showImage
- downloadFile
- call
- payment
- openApp

_From Microsoft.Bot.Schema.ActionTypes_

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 672a763d-189b-8ba0-f66e-c07f1dc0a962
* Version Independent ID: 1ac7a9bd-138b-3bf8-60a3-1842d87371fd
* Content: [Add card actions in a bot - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-actions)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-actions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-actions.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Abhijit-MSFT** [comment]
These types are not supported in card action.
