### ISSUE TITLE
Q&A not updated in Team Event

### ISSUE THREAD

**Issue by haimkatz** [MicrosoftDocs/msteams-docs#1978]
I created an event and forgot to check the allow Q&A check box.  I edited the event several times afterwards and clicked on the Q&A checkbox, but the Q&A was not enabled for the event.

**Comment by Nikitha-MSFT** [comment]
Where you are enabling the the checkbox? Could you please share more details?

**Comment by haimkatz** [comment]
I was able to reproduce the problem.
1.  In the teams calendar click on new Event.  
2.  Go to settings.  Leave Q&A blank (see screen shot).
3.  Join the meeting.  (do not start it).
4.  Leave the meeting.
5.  Go back to the calendar and double click on the meeting.
6.  Click on edit, then settings and check the box next to Q&A.
7.  Join the meeting,  the "Display Q&A" option does not appear.  

If I create the meeting from the beginning with the Q&A option then there is no problem.

![QA](https://user-images.githubusercontent.com/11335004/90235646-55575180-de2a-11ea-8eda-c2a8b69e28af.png)

**Comment by Nikitha-MSFT** [comment]
We cold not find the settings in teams UI for meeting in public ring. In which ring you are trying? Could you please conform?
