### ISSUE TITLE
Adaptive Cards in Messaging Extensions

### ISSUE THREAD

**Issue by pschaeflein** [MicrosoftDocs/msteams-docs#198]
The "Respond to user requests" section contains a table with the valid properties for a result. The `componseExtension.attachments` property lists the `contentType` values for Hero, Thumbnail and O365 Connector cards.

Immediately below the table, the pages lists support for Adaptive Cards.

What is the `contentType` value for Adaptive cards?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eeb9dcd0-fc2e-95a0-5238-fb67b6a27ba7
* Version Independent ID: 3adf9985-9a34-fbb4-161a-23beb753dd70
* Content: [Develop messaging extensions - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/messaging-extensions)
* Content Source: [msteams-platform/concepts/messaging-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/messaging-extensions.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by NormSohl** [comment]
Good catch - content will be updated shortly.

**Comment by billbliss** [comment]
Updated here: https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/messaging-extensions#response-example
