### ISSUE TITLE
Document not reflecting AAD management page

### ISSUE THREAD

**Issue by eilmrein** [MicrosoftDocs/msteams-docs#1988]
I am trying to put together an Web-App that uses SSO following this document,

However I cannot find the Manage tab in AAD Admin to add the API

Help please!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52221dd3-95ec-96b9-1da8-9478527c2602
* Version Independent ID: 32e9c2d8-733d-0865-2ea3-727d8684a10d
* Content: [Single Sign-On - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-aad-sso)
* Content Source: [msteams-platform/tabs/how-to/authentication/auth-aad-sso.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tabs/how-to/authentication/auth-aad-sso.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Gousia-MSFT** [comment]
@eilmrein You could see the Manage tab on the overview page after you have created the AAD app.
![image](https://user-images.githubusercontent.com/45553518/90473630-fd2d9180-e140-11ea-81f0-2ec4ccf47f7c.png)
