### ISSUE TITLE
Add method to fetch/identify team owners in Teams

### ISSUE THREAD

**Issue by clearab** [MicrosoftDocs/msteams-docs#1990]
Moved from: https://github.com/microsoft/botbuilder-js/issues/2706

**Is your feature request related to a problem? Please describe.**
Teams has two kinds of team member roles: Owner and member. There is currently no way for the bot to quickly identify an owner of a team. Having this would make it possible to support additional functionality specifically for an owner of the current team.

**Describe the solution you'd like**
TeamsInfo.getTeamOwners(context , teamId), TeamsInfo.getPagedTeamOwners(context, teamId) or similar would be great. It would work the same as TeamsInfo.getTeamMembers(context, teamId), etc.
Edit: An "isOwner" flag in the member details would also work, e.g. TeamsInfo.getTeamMember(context, teamId, userId) would return isOwner: true

**Describe alternatives you've considered**
I tried to get the teams owner via oauth but I think only tenant admins can agree to permissions (like Group.Read.All) that would allow checking if the user is an owner. It would be great to get this functionality without implementing oauth.

**Comment by VaraPrasad-MSFT** [comment]
We are working on it and we don't have any ETA to share.
Currently you can do this by calling Graph APIs using [Resource Specific Consent](https://docs.microsoft.com/en-us/microsoftteams/platform/graph-api/rsc/resource-specific-consent#resource-specific-permissions).

**Comment by Wajeed-msft** [comment]
**Internal Tracker:** [Feature 921490](https://domoreexp.visualstudio.com/MSTeams/_workitems/edit/921490): Expose a getTeamMembers API in Teams Client Js SDK (using RSC)

**Comment by ChetanSharma-msft** [comment]
Hello @clearab - Sorry for delay in response.
I will check the updates on the feature and will share the updates on this thread.

**Comment by ChetanSharma-msft** [comment]
Hello @clearab - Now we have two ways to get the team members details like:
1) Using SDK method: `getTeamMembers`
Reference doc: https://learn.microsoft.com/en-us/java/api/com.microsoft.bot.builder.teams.teamsinfo?view=botbuilder-java#method-summary

2) Using Graph API: 
Reference doc link: https://learn.microsoft.com/en-us/graph/api/team-list-members?view=graph-rest-1.0&tabs=http#example-1-get-list-of-members-in-team

Please let us know if you have any other query to discuss?
