### ISSUE TITLE
edit must be readwrite

### ISSUE THREAD

**Issue by prkosh** [MicrosoftDocs/msteams-docs#1992]
[Enter feedback here]
spotted errors -

Old | New
-- | --
ChannelSettings.Edit.Group | ChannelSettings.ReadWrite.Group
TeamsTab.Edit.Group | TeamsTab.ReadWrite.Group

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11c68c28-b6d6-ef7e-f8f9-ebebe487378b
* Version Independent ID: c5985867-3795-4280-ef0d-1d66ee30da6e
* Content: [Resource-specific consent in Teams - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/graph-api/rsc/resource-specific-consent)
* Content Source: [msteams-platform/graph-api/rsc/resource-specific-consent.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/graph-api/rsc/resource-specific-consent.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Wajeed-msft** [comment]
This is already fixed.
