### ISSUE TITLE
Programatic way to create outgoing webhooks?

### ISSUE THREAD

**Issue by quesurifn** [MicrosoftDocs/msteams-docs#1993]
This guide doesn't include a way to programmatically make outgoing webhooks. Is this even possible? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da50e4db-a713-ab8b-d27b-89aa946619d0
* Version Independent ID: 57e368e2-aaed-fa8d-ed49-cc18e594ab1d
* Content: [Office 365 Connectors - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-creating)
* Content Source: [msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Trinetra-MSFT** [comment]
@quesurifn , Teams provide the interface to create outgoing webhook to POST request over a specified callback URL (That can be an external service URL which can accept JSON as payload from Teams). Please look at [outgoing webhook sample code ](https://docs.microsoft.com/en-us/samples/officedev/msteams-samples-outgoing-webhook-nodejs/microsoft-teams-outgoing-webhook-sample/) but currently we don't support any API to create outgoing webhook

**Comment by Trinetra-MSFT** [comment]
@quesurifn , Please feel free to reopen this issue, if you have further query
