### ISSUE TITLE
[Demo] This is a test issue created for Question Tracker and Fabric bot demo

### ISSUE THREAD

**Issue by shaikhwajeed** [MicrosoftDocs/msteams-docs#1996]
Please ignore.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e52a9fa-a482-2929-c462-47da5e8b38d1
* Version Independent ID: ce956c12-2916-9d6c-4fbb-5d07556378bc
* Content: [Create a bot for Microsoft Teams - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/create-a-bot-for-teams)
* Content Source: [msteams-platform/bots/how-to/create-a-bot-for-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/bots/how-to/create-a-bot-for-teams.md)
* Product: **msteams**
* GitHub Login: @clearab
* Microsoft Alias: **anclear**

**Comment by Wajeed-msft** [comment]
Need more information to repro this.

**Comment by shaikhwajeed** [comment]
Here is additional information. Thanks.

**Comment by shaikhwajeed** [comment]
[Test] Please re-open this.
