### ISSUE TITLE
Better handling of adaptive card attachments with text

### ISSUE THREAD

**Issue by weikanglim** [MicrosoftDocs/msteams-docs#1998]
## Issue
As a bot developer, I'm trying to send an adaptive card with a text message.

Currently, sending an adaptive card with text runs into the following issues:
- **Issue 1**: Teams sends the text and adaptive card attachment as two separate activities. If the adaptive card has a submit button, and the desire is to update the existing card when the user submits. The `ReplyToId` only contains the card, and not the text. The text message cannot be updated or deleted without having this tracked separately as conversation state.
- **Issue 2**: Chat feeds will only present the last message sent, which will just say "Bot send a card"
![image](https://user-images.githubusercontent.com/2322434/90679864-6dfaa980-e226-11ea-89a9-5f5be4a74442.png)
- **Issue 3**: If you use `TeamsNotifyUser` to enable notifications, the Notifications feed present both the text and card separately, which results in noise:
![image](https://user-images.githubusercontent.com/2322434/90679933-97b3d080-e226-11ea-84b6-2474b412dd6a.png)

## Expectation
The text message should help describe the card for the notification feed, chat feed. The most ideal is if the message is presented in the same activity as the card. The notification and chat feed should display the text instead of "Send a card", or the "card" icon.

## Sample to reproduce
Message json:
```json
{
  "type": "message",
  "attachmentLayout": "list",
  "text": "Hello World Message",
  "inputHint": "acceptingInput",
  "attachments": [
    {
      "contentType": "application/vnd.microsoft.card.adaptive",
      "content": {
        "type": "AdaptiveCard",
        "version": "1.2",
        "body": [
          {
            "type": "TextBlock",
            "text": "Hello, World!"
          }
        ]
      }
    }
  ],
  "entities": []
}
```

**Comment by VaraPrasad-MSFT** [comment]
@weikanglim , This is current behavior and we don't have any plans as of now regarding the change in adaptive card.
