### ISSUE TITLE
Sample chat threads

### ISSUE THREAD

**Issue by anandh86** [MicrosoftDocs/msteams-docs#1999]
[Enter feedback here]
It would be great if the script also adds sample chat posts. Is there anything that is already available for this purpose?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd399165-9390-cce4-93e9-e2907f842496
* Version Independent ID: 31fa2e85-928c-5a3d-fb03-7d7a94864810
* Content: [Add test data to your Office 365 test tenant - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/test-data)
* Content Source: [msteams-platform/concepts/build-and-test/test-data.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/build-and-test/test-data.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by VaraPrasad-MSFT** [comment]
Could you please provide more details regarding the issue you are facing ?

**Comment by VaraPrasad-MSFT** [comment]
You need to create the chat. In case you want this to be added in future, please raise feature request in [Uservoice ](https://microsoftteams.uservoice.com/).

**Comment by anandh86** [comment]
Thanks for the info. I wanted to know if you have the ability to add sample
data for the chat messages in Microsoft Teams. Right now, the application
creates sample teams, users and channels.

**Comment by v-karapa** [comment]
Hi @anandh86 
could you please check below details can help you.
https://docs.microsoft.com/en-us/office/developer-program/install-sample-packs
 This will add users to tanant.
https://docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-1.0&tabs=http
 this will post message in channel
https://docs.microsoft.com/en-us/graph/api/user-post-messages?view=graph-rest-1.0&tabs=http
 this will post message to user
