### ISSUE TITLE
client SDK absolutely necessary to include? 

### ISSUE THREAD

**Issue by chrilian** [MicrosoftDocs/msteams-docs#200]
Some examples for tabs use sites like google.com and bing.com. I doubt those sites have the SDK library loaded in them? But it states here that loading a library is a "requirement." If I'm not wrong-- technically its not required. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bdefa23-965c-60fa-9a8c-ad528c779d57
* Version Independent ID: cd12db99-7cdb-0582-fd4f-bcda2ae3b219
* Content: [Requirements for tab pages in Microsoft Teams - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/tabs/tabs-requirements)
* Content Source: [msteams-platform/concepts/tabs/tabs-requirements.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/tabs/tabs-requirements.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by billbliss** [comment]
There are two pages that are relevant to tabs, as explained [here](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/tabs/tabs-overview#what-you-need-to-know-configurable-tabs) - the configuration page and the content page. The configuration page most definitely requires the SDK; the content page does not.
