### ISSUE TITLE
Disable Developer preview mode

### ISSUE THREAD

**Issue by cbarbier7** [MicrosoftDocs/msteams-docs#2002]
Hello, how can we disable the option to use developer preview mode at the organizational level for managed mobile devices?

**Comment by Trinetra-MSFT** [comment]
@cbarbier7 Disability the ability for the organisation to be able to enable Developer Preview is to return to Org Wide App settings within Permission Policies of Teams Apps in the Teams Admin Centre, swiping off Allow interaction with custom apps and Saving. This will remove the Developer preview option from all users desktop, web and mobile clients.
