### ISSUE TITLE
page not loading after invoking navigateCrossDomain method

### ISSUE THREAD

**Issue by chrilian** [MicrosoftDocs/msteams-docs#201]
As a test I added "https://www.google.com" as the redirect url. I made sure that the validDomains list included: "*.google.com" Unfortunately-- I get a blank page on load. When I use a URL I hosted with the client SDK loaded it works fine though. Is there something obvious I am missing? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc55e638-91cb-550f-217b-4d910a10dfa9
* Version Independent ID: f25e285d-8557-4bdc-5623-189fd4d6fad6
* Content: [Cross-domain redirects - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/tabs/cross-domain)
* Content Source: [msteams-platform/concepts/tabs/cross-domain.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/tabs/cross-domain.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by billbliss** [comment]
Haven't heard back from @chrillian so closing this.
