### ISSUE TITLE
Images not getting trimmed/fit to a fix box size leaving too much empty space for small images

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#2012]
**Issue**: The images are getting rendered in a fix size box. Any smaller image is leaving lots of blank space in the text. We tried posting image using markdown format as well as the HTML img tag.

**Workaround**: Pass the actual height and width each image.

**Reference**: https://github.com/microsoft/AdaptiveCards/issues/4601

**Internal Bug Tracker**: [1147854](https://domoreexp.visualstudio.com/MSTeams/_workitems/edit/1147854)

Please continue to follow this issue for updates/progress/questions.

**Comment by Wajeed-msft** [comment]
**Updates:** We have [feature](https://domoreexp.visualstudio.com/MSTeams/_workitems/edit/1163953) to support Support image dimensions. This change is being verified internally.

**Comment by Jagadeesh-MSFT** [comment]
Hi @apurva1112, Issue got fixed , could you please check and revert back. Adding image below for you reference.
![image](https://user-images.githubusercontent.com/73812940/123050134-fd13b780-d41d-11eb-9f32-31c30714454c.png)
