### ISSUE TITLE
Messaging extension file attachment downloadUrl

### ISSUE THREAD

**Issue by slcwebguy** [MicrosoftDocs/msteams-docs#2021]
I'm having to take a longer-than-expected and seemingly-less-reliable route to get access to a message's file attachments. It's causing some timeout issues for an action-based messaging-extension app that I'm building.

[This issue](https://github.com/microsoftgraph/msgraph-sdk-javascript/issues/200) describes what I'm running into pretty well. I took a different approach to solving it than the issue poster but it still doesn't seem great. My solution was to add an extra layer of authentication to the MsGraph api and use that to query for the attachments in OneDrive/Sharepoint. By way of extra api pulls for the team id and the drive id, I do eventually get to an endpoint that returns a `downloadUrl` property which allows me to download the files. Personally, I think it's cool that such a solution is possible via Graph and honestly it seems to be working decently well (aside from the timeout problem and path-based search uncertainty). However, it also seems less-reliable and unnecessarily circuitous.

Instead, are there some permissions, perhaps, that I could add to my app/bot to give it a publicly-accessible way of downloading the attachments? Is there supposed to be an `action.messagePayload.attachments[n].content.downloadUrl` property? If so, that would be exactly what I'm looking for. Sadly, at present, I'm getting nothing but `null` in `action.messagePayload.attachments[n].content` for the attachments that I'm testing with.

This issue seems like it might also be related to [this one](https://github.com/MicrosoftDocs/msteams-docs/issues/1805) but I'm not seeing exactly the same thing so maybe not. [This SO question](https://stackoverflow.com/questions/58238653/getting-message-attachments-from-teams-action-based-messaging-extension) also seems pretty close. Lastly, [this Graph issue](https://github.com/microsoftgraph/microsoft-graph-docs/issues/42) looks related too but again not exactly the same.

**Comment by VaraPrasad-MSFT** [comment]
@slcwebguy ,

Currently file download is not supported through message extension. when you receive an ME payload, it stores the file in different location which is currently not downloadable.

**Comment by slcwebguy** [comment]
Ok, thank you.

**Comment by kensnyder** [comment]
@VaraPrasad-MSFT Is this feature on your roadmap or is it something you don't want to allow? Our use case is that a user wants to push a file into our system. Similar to an iOS share sheet or Android share where you can send a file to another app.

**Comment by VaraPrasad-MSFT** [comment]
Currently we don't have any ETA to share , You can raise an [user voice](https://microsoftteams.uservoice.com/forums/555103-public-preview/category/182881-developer-platform) if this need to be consider as future product.
