### ISSUE TITLE
FCM Notifications being sent

### ISSUE THREAD

**Issue by edlongman** [MicrosoftDocs/msteams-docs#2024]
See below screenshot: Log available on request if required
![Screenshot_20200827-091450](https://user-images.githubusercontent.com/693456/91415505-0d7ef400-e846-11ea-90b5-c58726244b9c.png)
![Screenshot_20200827-082857](https://user-images.githubusercontent.com/693456/91415510-0eb02100-e846-11ea-8708-76c47218c3c0.png)

**Comment by Gousia-MSFT** [comment]
@edlongman Thanks for reaching out to us! We have an active ticket on this and our team is working on fixing this. We regret the inconvenience caused!!

**Comment by DragneelMC1988** [comment]
![InkedScreenshot_20200827-095645_LI](https://user-images.githubusercontent.com/58085907/91424663-6193d380-e85a-11ea-9079-2d41f33edca6.jpg)
i had the same issue today too
