### ISSUE TITLE
Per bot per thread limit - Confusion

### ISSUE THREAD

**Issue by SubbaReddi** [MicrosoftDocs/msteams-docs#2026]
Need some understanding about Threshold limits for Bot to send proactive messages.

A conversation here is 1:1 between bot and user is mentioned in site. That means bot can send 1 message to each user and must be able to send to any number of users without any issue..right?

Could you please clarify?

**Comment by Nikitha-MSFT** [comment]
Yes, you can send any number of users. Please check this [Per bot per thread limit](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/rate-limit#per-bot-per-thread-limit) docs for more Info.

**Comment by SubbaReddi** [comment]
Thank you Nikitha. As discussed, If we try to send more than 7 people in 1 sec, then we see 429 error.
