### ISSUE TITLE
Needs to add mention of the new suppotsFiles manifest setting

### ISSUE THREAD

**Issue by billbliss** [MicrosoftDocs/msteams-docs#203]
We missed that when we pushed to live.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5307fe5c-a6f0-59e2-d125-69051ab58595
* Version Independent ID: ca3f41d9-1c2a-6cde-b780-61fec8f0fcb6
* Content: [Sending and receiving files from a bot - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/bots/bots-files)
* Content Source: [msteams-platform/concepts/bots/bots-files.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/bots/bots-files.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by NormSohl** [comment]
Fixed in master, will push to live by end of day.
