### ISSUE TITLE
Teams SSO Not Working in Task Module

### ISSUE THREAD

**Issue by lauren-mills** [MicrosoftDocs/msteams-docs#2030]
Original author: 
@arya-ayush

Teams SSO is working fine in Teams Tab and task module of Messaging extension but getting below error in Teams Bot task module while fetching client token

ExtensionTabService: getAuthTokenForApp: Failed with error - Definition not found

Using below code to open task module in teams bot with help of hero card -

https://teams.microsoft.com/l/task/${appId}?url=${modalUrl}&height=${height}&width=${width}&title=${title}`

The same code is also working in the Teams Bot task module in Android Mobile Application. But getting error in browsers, desktop app of mac and windows

**Comment by lauren-mills** [comment]
Original issue: https://github.com/microsoft/botbuilder-dotnet/issues/4542

**Comment by Abhijit-MSFT** [comment]
Currently SSO is available only on Teams tab (or task module) on desktop or mobile clients.
