### ISSUE TITLE
Command parameters required for `canUpdateConfiguration`

### ISSUE THREAD

**Issue by slcwebguy** [MicrosoftDocs/msteams-docs#2033]
The compose box's right-click menu doesn't come up under the circumstance described below.

Using this first manifest (replacing the `%removed%` bits with a real bot id), right clicking the app icon in the compose box **doesn't** bring up a menu:
```
{
  "$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.6/MicrosoftTeams.schema.json",
  "manifestVersion": "1.6",
  "version": "1.0",
  "id": "%removed%",
  "packageName": "foo",
  "developer": {
    "name": "Foo",
    "websiteUrl": "https://foo.ngrok.io",
    "privacyUrl": "https://foo.ngrok.io/privacy",
    "termsOfUseUrl": "https://foo.ngrok.io/tos"
  },
  "icons": {
    "color": "color.png",
    "outline": "outline.png"
  },
  "name": {
    "short": "Foo",
    "full": "Foo"
  },
  "description": {
    "short": "Foo",
    "full": "Foo"
  },
  "accentColor": "#FFFFFF",
  "composeExtensions": [
    {
      "botId": "%removed%",
      "canUpdateConfiguration": true,
      "commands": [
        {
          "id": "test",
          "type": "action",
          "title": "Test",
          "description": "Test",
          "initialRun": false,
          "fetchTask": true,
          "context": [
            "compose"
          ]
        }
      ]
    }
  ],
  "permissions": ["identity", "messageTeamMembers"],
  "validDomains": [
      "*.ngrok.io"
  ]
}
```

However, using this second manifest, it **does**:
```
{
  "$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.6/MicrosoftTeams.schema.json",
  "manifestVersion": "1.6",
  "version": "1.0",
  "id": "%removed%",
  "packageName": "foo",
  "developer": {
    "name": "Foo",
    "websiteUrl": "https://foo.ngrok.io",
    "privacyUrl": "https://foo.ngrok.io/privacy",
    "termsOfUseUrl": "https://foo.ngrok.io/tos"
  },
  "icons": {
    "color": "color.png",
    "outline": "outline.png"
  },
  "name": {
    "short": "Foo",
    "full": "Foo"
  },
  "description": {
    "short": "Foo",
    "full": "Foo"
  },
  "accentColor": "#FFFFFF",
  "composeExtensions": [
    {
      "botId": "%removed%",
      "canUpdateConfiguration": true,
      "commands": [
        {
          "id": "test",
          "type": "action",
          "title": "Test",
          "description": "Test",
          "initialRun": false,
          "fetchTask": true,
          "context": [
            "compose"
          ],
          "parameters": [
            {
              "name": "na",
              "title": "na"
            }
          ]
        }
      ]
    }
  ],
  "permissions": ["identity", "messageTeamMembers"],
  "validDomains": [
      "*.ngrok.io"
  ]
}
```

The difference between the two manifests:
```
          "parameters": [
            {
              "name": "na",
              "title": "na"
            }
          ]
```

This appears to apply to both versions 1.5 and 1.6 of the manifest schema and, AFAICT, only is a problem under the following conditions:
1. The `canUpdateConfiguration` property = `true`
1. The first command in the `commands` array has no `parameters` property.

**Comment by VaraPrasad-MSFT** [comment]
@slcwebguy , we need to provide the parameters when fetchTask set to true so that it will open the Menu in your case. While setting the fetchTask true and not passing the parameters will not resulting you to Menu.

**Comment by slcwebguy** [comment]
@VaraPrasad-MSFT , there is no menu regardless of the `fetchTask` value. Whether it's set to 'true' or 'false' doesn't appear to make a difference for making the menu appear. The only thing that seems to work is to add in some command `parameters`.

**Comment by VaraPrasad-MSFT** [comment]
@slcwebguy ,

While fetch task is set to false and provided parameters then it will open a menu with the provided parameters. when fetch task is set to true and no parameters provided then it will hit your bot, and you need to handle it in the code. Please find [app  manifest sample for MessageExtensions](https://docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/action-commands/define-action-command#app-manifest-example) and also could you please check this [docs](https://docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/action-commands/create-task-module?tabs=dotnet#example-fetchtask-request)

**Comment by slcwebguy** [comment]
@VaraPrasad-MSFT , I have read through the sample and the documentation that you linked. Honestly, I'd already read and re-read those and many more. I have yet to read anything that addresses this particular problem, though.

Are you saying that the app's right-click menu is influenced by its fetch-task handler? If the app has no command parameters that there is something that needs to be added to the fetch-task handler to ensure that the right-click menu works correctly?

In my case, I'm handling the fetch task with `botbuilder`'s `TeamsActivityHandler.handleTeamsMessagingExtensionFetchTask`. It is not erring out and is functioning as expected when working the user through the fetch-task and submit processes. What would I need to add that also makes the right-click menu work?

**Comment by slcwebguy** [comment]
I feel like there might be a misunderstanding about which right-click menu I'm referring to. For reference, it's the one shown in this screenshot:

![image](https://user-images.githubusercontent.com/26755361/91872677-56afb900-ec35-11ea-8497-c5efe45d706d.png)

**Comment by VaraPrasad-MSFT** [comment]
@slcwebguy ,
Apologies for the confusion here. We could repro the issue. The issue is mainly due to a bug that does not allow message extension to be configured without parameters object. We have an Active bug on this which we are working on. But currently we do not have a ETA for the fix.

**Comment by slcwebguy** [comment]
Ok. Good to know. Thank you for the update.
