### ISSUE TITLE
Registering App Permissions not documented

### ISSUE THREAD

**Issue by DarraghDuffy** [MicrosoftDocs/msteams-docs#2035]
While completing the step to "Register your app in Teams", select 'Install' button, I was unable to Add the App, the following error appeared:

"You don't have permissions to add **** hello world to this team"

I found the following note that help solve the issue:

https://social.technet.microsoft.com/Forums/en-US/1caaf330-a2c1-4dc6-8877-cd68c2a84387/ms-teams-cant-install-custom-app?forum=onlineservicesadministrationcenter

I had to ensure that "Upload custom apps" was enabled in MS Teams Admin via following URL https://admin.teams.microsoft.com/policies/app-setup

**Comment by Wajeed-msft** [comment]
@DarraghDuffy - This part is documented in [Prepare your development environment](https://docs.microsoft.com/en-us/microsoftteams/platform/tutorials/get-started-dotnet-app-studio#prepare-your-development-environment) section. Could you please share the link of the docs which you are referring to?

**Comment by DarraghDuffy** [comment]
Hi @Wajeed-msft - Good Question.

MS' docs seem to have changed since I last was working with MS Teams integration. I would have been using [Build your first App](https://docs.microsoft.com/en-us/microsoftteams/platform/build-your-first-app/build-first-app-overview). 

The Document you are referencing is related to .net / c#. I am JS / NodeJS developer, I would not have been reading .net / c# requirements as I would not think them relevant. 

I did read the doc that you have referenced above, it does not reference the solution I found [here](https://social.technet.microsoft.com/Forums/en-US/1caaf330-a2c1-4dc6-8877-cd68c2a84387/ms-teams-cant-install-custom-app?forum=onlineservicesadministrationcenter)

So, from my perspective it would have been useful to have [this solution](https://social.technet.microsoft.com/Forums/en-US/1caaf330-a2c1-4dc6-8877-cd68c2a84387/ms-teams-cant-install-custom-app?forum=onlineservicesadministrationcenter) referenced [here with Build your first App](https://docs.microsoft.com/en-us/microsoftteams/platform/build-your-first-app/build-first-app-overview).  

The solution for me was to ensure that "Upload custom apps" was enabled in MS Teams Admin via [here](https://admin.teams.microsoft.com/policies/app-setup)

**Comment by Wajeed-msft** [comment]
@DarraghDuffy - We have [Set up your development account](https://docs.microsoft.com/en-us/microsoftteams/platform/build-your-first-app/build-first-app-overview#set-up-your-development-account) documentation which covers steps if you can't see the sideload option or don't have a Teams account.
![image](https://user-images.githubusercontent.com/31851992/93979598-2f16c100-fd9b-11ea-9802-b383f5992a1d.png)


I'll check if we can link [Enable custom Teams apps and turn on custom app uploading](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/prepare-your-o365-tenant#enable-custom-teams-apps-and-turn-on-custom-app-uploading) document on [Build your first App](https://docs.microsoft.com/en-us/microsoftteams/platform/build-your-first-app/build-first-app-overview).
