### ISSUE TITLE
teams-1.3.00.16851 still relies on libgnome-keyring instead of libsecret

### ISSUE THREAD

**Issue by pacho2** [MicrosoftDocs/msteams-docs#2039]
Hello,

Even if the rpm package is pulling libsecret, this file is still using libgnome-keyring
scanelf -n resources/app.asar.unpacked/node_modules/keytar3/build/Release/keytar.node
ET_DYN libgnome-keyring.so.0,libstdc++.so.6,libc.so.6

It seems teams package is using an old version of keytar not including this fix
https://github.com/atom/node-keytar/pull/53

On the other hand, skypeforlinux is including a fixes keytar version with libsecret support... maybe it's only needed to update the copy supplied in teams package

Thanks a lot

**Comment by Trinetra-MSFT** [comment]
@pacho2 , We have redirected your query to right channel. We will get back to you once we got any response from team.

**Comment by pacho2** [comment]
Thanks a lot

**Comment by Trinetra-MSFT** [comment]
@pacho2 , We have a open [Bug ](https://domoreexp.visualstudio.com/MSTeams/_workitems/edit/1179896)for this. We will let you once this got resolved. Closing this issue once once is resolved we will update you on this.

**Comment by pacho2** [comment]
Thanks, is there any way to track the other bug? It seems I have no access 

Best regards

**Comment by Trinetra-MSFT** [comment]
@pacho2 , We have internal tracking once the Bug is resolved. We will update you here.
