### ISSUE TITLE
hostClientType context property is not documented

### ISSUE THREAD

**Issue by aosolis** [MicrosoftDocs/msteams-docs#2040]
We're missing documentation for several properties in the tab context, including `hostClientType`. 
See https://github.com/OfficeDev/microsoft-teams-library-js/blob/65d0ab8e0a81245041b53145652cd724341b6340/src/public/interfaces.ts

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8dfa1a29-bcf4-0cc5-ae3a-b185a00fd7bc
* Version Independent ID: c68181e1-151b-fc78-2671-fe9b397b702e
* Content: [Get context for your tab - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/access-teams-context)
* Content Source: [msteams-platform/tabs/how-to/access-teams-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tabs/how-to/access-teams-context.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Mahesh2516** [comment]
issue resolved
