### ISSUE TITLE
'isFullScreen' field of Teams App Manifest not working correctly

### ISSUE THREAD

**Issue by wahan2019** [MicrosoftDocs/msteams-docs#2042]
[Enter feedback here]

#### Describe the bug
'isFullScreen' field of Teams App Manifest didn't work when I install app by uploading Teams App zip file or App Studio. But it works correctly if I upload zip to my test tenant catalog and then install from tenant catalog.

#### To reproduce
1. prepare
  - Teams Client
    - Web Client (Web Browser: Microsoft Edge/Chrome)
    - Windows Desktop Client(Microsoft Teams Version 1.3.00.24169 (64-bit). It was last updated on 9/1/20.)
  - Test Tenant:  Microsoft 365 Developer Program subscription
  - A app zip whose manifest set isFullScreen field to true
2. install the app via upload: Teams Client->Apps->Upload a custom app->select the zip and upload->Add
  the installed app is not full screen
3. install the app via app studio: Teams Client->Apps->App Studio->Manifest editor->Import an existing app->Install
  the installed app is not full screen
4. install the app via tenant catalog
  - login in the Teams Admin Center with test tenant admin account
  - Teams apps->Manage apps->Upload->choose the zip and upload
  - in teams client -> Apps -> Built for Contoso -> Install the app
  - the app is full screen

In addition
  - the 'isFullScreen' field worked correctly in the previous version teams client if I remember correctly
  - the field work correctly on mobile client till now

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f94a488-d636-92b3-21eb-c88744c8f272
* Version Independent ID: 7b3413f4-9ade-accf-5cb2-83fead11a32a
* Content: [Manifest schema reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema?source=docs)
* Content Source: [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/resources/schema/manifest-schema.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Gousia-MSFT** [comment]
@wahan2019 Thanks for reaching out to us! We could repro the issue and we have a bug on this which we are working on.

**Comment by wahan2019** [comment]
I took a test on Web Client just now. It is still not working correctly. Has the fix deployed to prod?

**Comment by wahan2019** [comment]
It seems to work right now after I switch my browser to private mode and re-signin.

Thanks for the quick response and action!

**Comment by wahan2019** [comment]
in app studio there is a warning like this

![image](https://user-images.githubusercontent.com/70621580/92892512-66a47580-f44b-11ea-965b-7a5613bfb09b.png)

I checked the json schema of the v1.7 manifest https://developer.microsoft.com/en-us/json-schemas/teams/v1.7/MicrosoftTeams.schema.json

the definition is still here
![image](https://user-images.githubusercontent.com/70621580/92892840-b5520f80-f44b-11ea-80a2-cbb2ebba4c38.png)

and the check box in app sudio->app details is still here

![image](https://user-images.githubusercontent.com/70621580/92892674-8cca1580-f44b-11ea-83a9-54f393e7638d.png)

fyi

**Comment by Gousia-MSFT** [comment]
@wahan2019 "isFullScreen" works only with SharePoint tabs and LoB Store Apps. We are working on updating the docs to refelect the behaviour.

**Comment by Wajeed-msft** [comment]
@v-abirade - could you please help to update this in documentation?

Note: "isFullScreen" works only with SharePoint tabs and LoB Store Apps.

Ref: https://github.com/OfficeDev/microsoft-teams-library-js/issues/445#issuecomment-722548839
