### ISSUE TITLE
@DaveVoyles Thanks for sharing your suggestion. We will consider this. You can also go ahead and raise a [uservoice ](https://microsoftteams.uservoice.com/)for Microsoft Teams.

### ISSUE THREAD

**Issue by Shakhnoza21** [MicrosoftDocs/msteams-docs#2046]
@DaveVoyles Thanks for sharing your suggestion. We will consider this. You can also go ahead and raise a [uservoice ](https://microsoftteams.uservoice.com/)for Microsoft Teams.

_Originally posted by @Gousia-MSFT in https://github.com/MicrosoftDocs/msteams-docs/issues/1931#issuecomment-666209620_

**Comment by Shakhnoza21** [comment]
Hi, 
couldn't find outgoing webhook. Is it still availible in Teams?
The document states:

"Select the appropriate team and select Manage team from the (•••) drop-down menu.
Choose the Apps tab from the navigation bar.
From the window's lower right corner select Create an outgoing webhook"

![image](https://user-images.githubusercontent.com/36479281/92117563-9de4a800-edf5-11ea-9b82-6bf1560a2e8c.png)

**Comment by falktan** [comment]
I have the same issue. It worked for me a while ago, but the button to create an outgoing webhook is no longer there.
Was this moved somewhere else?
Are there any conditions for this button to be available?

**Comment by Trinetra-MSFT** [comment]
@Shakhnoza21 , Did you tried this within different tenant, Are you the owner/member of the Team in which you are trying to create outgoing webhook?
![image](https://user-images.githubusercontent.com/50989436/92564494-e0473280-f296-11ea-8659-cfbf0608f1e0.png)

**Comment by Trinetra-MSFT** [comment]
Please feel free to reopen if you further query regarding this.
