### ISSUE TITLE
How can I add an image carousel in a Microsoft Team App manifest?

### ISSUE THREAD

**Issue by nuclearWinters** [MicrosoftDocs/msteams-docs#2047]
I need to add an image to a MS Teams App as part of the information display before the app is installed. Documentation does mention a carousel card but how can I put it on the app's manifest/info like the image below?

<img width="876" alt="Screen Shot 2020-09-03 at 1 21 08" src="https://user-images.githubusercontent.com/38480267/92121052-71159e00-edbf-11ea-821c-c530a62d6e1d.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f94a488-d636-92b3-21eb-c88744c8f272
* Version Independent ID: 7b3413f4-9ade-accf-5cb2-83fead11a32a
* Content: [Manifest schema reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema)
* Content Source: [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/resources/schema/manifest-schema.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Gousia-MSFT** [comment]
@nuclearWinters This is not part of the manifest. You can set this while submitting your app to the app store. Please reach out to teamsubmATmicrosoft.com for any further queries on this.
