### ISSUE TITLE
MS teams List card is not displaying the Mongolian letter 'м' (unicode number - 1084) on Mobile app

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#2049]
Copied from: https://github.com/microsoft/botframework-sdk/issues/6014 raised by @kbatsuren

I am using the bot framework sdk v4 on Micrsofot Teams. The main language of this app is Mongolian, and we experienced this issue of not displaying the cyrillic letter 'м' (unicode number - 1084) in MS Teams List card.

It is working fine on other platforms like Web Application or Desktop Application, but only the mobile version (here I am using IPhone 8 with the 13.3.1 ios version). Also the letter is fine with other elements such as adaptive cards, button, and text messages.

Here is the screenshots.

1. Mobile version (with error)
![](https://user-images.githubusercontent.com/50955407/91744197-abc6dd00-ebeb-11ea-9513-4387f800c8fe.jpg)
2. Desktop version (without error)
![](https://user-images.githubusercontent.com/50955407/91744630-59d28700-ebec-11ea-816c-217ca116fc7f.png)

JSON list card:
`{
	"contentType": "application/vnd.microsoft.teams.card.list",
	"content": {
		"title": "Нийт 1 ажилтан оллоо.",
		"items": [
			{
				"type": "person",
				"id": "amarsanaag@num.edu.mn",
				"title": "Амарсанаа Ганболд",
				"subtitle": "муис хшуис",
				"tap": {
					"type": "imBack",
					"value": "amarsanaag@num.edu.mn гэж хэн бэ?"
				}
			}
		]
	}
}`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Cards Reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Trinetra-MSFT** [comment]
We can repro this as Bug at our end. We have filed a Bug for this, will be tracking it internally. once it got resolved we will let you know
