### ISSUE TITLE
Blank space at the header hides the teams option

### ISSUE THREAD

**Issue by sakthiloganathan** [MicrosoftDocs/msteams-docs#205]
Windows 10
Microsoft Teams Version 1.1.00.19257 (64 bit). It was last updated on 06/08/2018.

Steps to reproduce:
Move the Teams between two monitors 

Observed the below. (Evidence attached)
1 - Black & white space at the top
2 - Not able to scroll down 
3 - Team options are hidden

![image](https://user-images.githubusercontent.com/25504657/43834769-3ebbf7b8-9b07-11e8-8335-1d1756e4226b.png)

![image](https://user-images.githubusercontent.com/25504657/43834773-437da666-9b07-11e8-8d4b-1c3ca852cbb0.png)

**Comment by billbliss** [comment]
Didn't follow up on this - we usually don't track product issues here. Assume this has been fixed in recent builds. Reopen if not.
