### ISSUE TITLE
GET v3/conversations/{conversationId}/members/ not working for GCC tenants? 

### ISSUE THREAD

**Issue by liangchr** [MicrosoftDocs/msteams-docs#2050]
There is a teams api that doesn't seem to be working for GCC tenants: https://docs.microsoft.com/en-aus/microsoftteams/platform/bots/how-to/get-teams-context?tabs=dotnet (the top api: fetching the team roster)

(Works fine with commercial tenants/conversations)
 
Here is the request (header, body) we are sending:
GET https://smba.trafficmanager.net/amer/v3/conversations/19:d2332fee207c4375bc7e8ad6335dbe47@thread.skype/members/
{"content-type":"application/json","Authorization":"Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6ImppYk5ia0ZTU2JteFBZck45Q0ZxUms0SzRndyIsImtpZCI6ImppYk5ia0ZTU2JteFBZck45Q0ZxUms0SzRndyJ9.eyJhdWQiOiJodHRwczovL2FwaS5ib3RmcmFtZXdvcmsuY29tIiwiaXNzIjoiaHR0cHM6Ly9zdHMud2luZG93cy5uZXQvZDZkNDk0MjAtZjM5Yi00ZGY3LWExZGMtZDU5YTkzNTg3MWRiLyIsImlhdCI6MTU5OTI0NTk4MywibmJmIjoxNTk5MjQ1OTgzLCJleHAiOjE1OTkzMzI2ODMsImFpbyI6IkUyQmdZUENaVjluamFNZDg3S1Y5aUhWQ3NrUWtBQT09IiwiYXBwaWQiOiJhNzljNjk1OS0wYzZkLTQzNTMtYTIyYy02ODI2MTFiODZjNWYiLCJhcHBpZGFjciI6IjEiLCJpZHAiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC9kNmQ0OTQyMC1mMzliLTRkZjctYTFkYy1kNTlhOTM1ODcxZGIvIiwicmgiOiIwLkFBQUFJSlRVMXB2ejkwMmgzTldhazFoeDIxbHBuS2R0REZORG9peG9KaEc0YkY5dUFBQS4iLCJ0aWQiOiJkNmQ0OTQyMC1mMzliLTRkZjctYTFkYy1kNTlhOTM1ODcxZGIiLCJ1dGkiOiJhZUpIQzRiZ19FeUd6cW91MnFZT0FBIiwidmVyIjoiMS4wIn0.tVDV03TcFfzpiFzesbvoUjdi8G6RsGqNCnHgQ3WwC87wIMDO7hUkr4ee0yQM0GvZ7F-Pq1bYYjse8FNbhcotH93Tb7xjg1BfJy4na8cLXSj8fOm_JUqHBFnytE4ghEJXxoQuVfn1vxOg2cgH9b8joaNgkjs2mnTj-nUSjWqZ9k6_xuFn_uTQ2V1FfUcvl3IIyeTG-q9VKRCyI26CZDwcBgQDWoVCdkeYpr9vzi4ppGbscIz1_tCduezIm9HSprRy5DHV1l9F9MQ8kpqCW9v2K4UmwCq1mLyMdZogHV7Odw1ddukgoB5b1fC-V9AA6G-KuRHJ63SLbA16eYqjEPn3DA"}
 
For commercial tenants this api works fine, but not for GCC tenants.
 
This is the response we get:
{
    "error": {
        "code": "ConversationNotFound",
        "message": "Conversation not found."
    }
}
 
Any help would be greatly appreciated!

**Comment by Trinetra-MSFT** [comment]
@liangchr , Does your bot added in any channel first from which you are trying to fetch the members?
