### ISSUE TITLE
Adding Dotnet Sample

### ISSUE THREAD

**Issue by HiltonGiesenow** [MicrosoftDocs/msteams-docs#2055]
Of course the PR might not get accepted, but I've added a dotnet sample for this, based on the node version. More info at https://github.com/OfficeDev/msteams-tabs-sso-sample-nodejs/pull/10

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52221dd3-95ec-96b9-1da8-9478527c2602
* Version Independent ID: 32e9c2d8-733d-0865-2ea3-727d8684a10d
* Content: [Single Sign-On - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-aad-sso)
* Content Source: [msteams-platform/tabs/how-to/authentication/auth-aad-sso.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tabs/how-to/authentication/auth-aad-sso.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Abhijit-MSFT** [comment]
@HiltonGiesenow, we are looking into your code.

**Comment by HiltonGiesenow** [comment]
ok great, hopefully it's of use
