### ISSUE TITLE
 Need help with deploying Company Communicator App Template

### ISSUE THREAD

**Issue by David-Liong** [MicrosoftDocs/msteams-docs#2057]
Dear MS team,

Our organisation is interested in using the company communicator app and I have exactly followed your instructions on how to deploy it at https://github.com/OfficeDev/microsoft-teams-company-communicator-app/wiki/Deployment-guide on a test tenant environment

I have completed all the steps. After the last step of running the communicator app for authors in MS Teams via web browser, I do not know why in Chrome, MS Teams is repeating asking for my login credentials. See attached 1.jpg
In IE, the company communicator app shows blank page in Teams.

I have entered my login credentials correctly, (see attached 2.jpg) but Teams pop up with the same message (see 1.jpg) again.

Can you please help me trouble shoot it and let me know what additional steps I need to check. Your trouble shooting guide https://github.com/OfficeDev/microsoft-teams-company-communicator-app/wiki/Troubleshooting does not contain solution relating to my case.

![2](https://user-images.githubusercontent.com/71060262/92686937-38e8ff00-f36d-11ea-9815-05ceff7d3278.jpg)
![1](https://user-images.githubusercontent.com/71060262/92686944-3b4b5900-f36d-11ea-8d57-f92211d92cb6.jpg)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 100070d1-40f9-b5eb-be0a-6199de26e0e6
* Version Independent ID: 5d1269e3-2775-ebf6-cf9a-8d1ee7038397
* Content: [Microsoft Teams app templates - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/samples/app-templates#company-communicator)
* Content Source: [msteams-platform/samples/app-templates.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/samples/app-templates.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Manish-MSFT** [comment]
Hi @David-Liong, Have you tried adding valid configurations? It would be better if you could provide additional details like video recording.
