### ISSUE TITLE
Need more information around "resource — the resource URL for the app."

### ISSUE THREAD

**Issue by saikumaru** [MicrosoftDocs/msteams-docs#2058]
Please can you advice what is the URL that is being referred here? Is it the bot messaging endpoint, or the botframework token endpoint(https://token.botframework.com/.auth/web/redirect)?
Because while creating the AD app for setting up the permissions I do not see any Resource URL to be referenced.

Referenced portion of the doc- https://docs.microsoft.com/en-us/microsoftteams/platform/graph-api/proactive-bots-and-messages/graph-proactive-bots-and-messages?tabs=csharp#permissions

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 893c2c9e-10e1-dd4e-1eb4-b4e9a46a9f8d
* Version Independent ID: 5f41c382-377c-6c9b-4932-65853675c4ad
* Content: [Use Microsoft Graph to enable proactive bot installation and messaging in Teams - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/graph-api/proactive-bots-and-messages/graph-proactive-bots-and-messages?tabs=csharp)
* Content Source: [msteams-platform/graph-api/proactive-bots-and-messages/graph-proactive-bots-and-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/graph-api/proactive-bots-and-messages/graph-proactive-bots-and-messages.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by saikumaru** [comment]
Thank you, just to reconfirm your inputs

{YourAppId} - This is the AAD App ID/Client Id?
{yourDomain}-  ***.on microsoft.com
{AppId}-  This is the id which is below, and was generated through the AppStudio ?
```
  "$schema": "https://developer.microsoft.com/json-schemas/teams/v1.7/MicrosoftTeams.schema.json",
  "manifestVersion": "1.7",
  "version": "1.0.0",
  "id": "%MICROSOFT-APP-ID%",
```

I looked at a sample mentioned here, which says it works, and has a different URL, so the confusion.
http://www.devjhorst.com/2020/07/simplifying-proactive-messaging-in.html

**Comment by Trinetra-MSFT** [comment]
@saikumaru , Resource URL will be your app URL for Azure AD auth, you can use this "api://{Your Bot id}"

**Comment by saikumaru** [comment]
Thank you, that helps. 

If you can refer me to some documentation where I can understand more about the Resource URL it would help. Especially to understand how "api://{yourDomain}.com/botid-{AppId}" and  "api://{Your Bot id}" are equivalent.

**Comment by Trinetra-MSFT** [comment]
@saikumaru , You can check this [manifest ](https://github.com/ydogandjiev/taskmeow/blob/master/manifest/sso/manifest.json )having Resource URL as app url

**Comment by Trinetra-MSFT** [comment]
Please feel free to reopen if you have further query on this
