### ISSUE TITLE
Show error in Console when Task Module fails to render URL because it's not added to valid domains

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#2062]
Currently failure in Task module are not properly reported in Console Log. Creating this issue to track & share updates on this. 

**Internal Bug Tracker**: [1124697](https://domoreexp.visualstudio.com/MSTeams/_workitems/edit/1124697)

Please continue to follow this issue for updates/progress/questions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 501d3295-997c-d252-d458-534673b36a52
* Version Independent ID: c90dcc98-df65-b45b-4f78-64d2cab91852
* Content: [What are task modules? - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/what-are-task-modules)
* Content Source: [msteams-platform/task-modules-and-cards/what-are-task-modules.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/what-are-task-modules.md)
* Product: **msteams**
* GitHub Login: @clearab
* Microsoft Alias: **anclear**

**Comment by Wajeed-msft** [comment]
**Updates:** This is expected to be fixed and rolled out in October 2020.

**Comment by Trinetra-MSFT** [comment]
Bug is copied to backlog item as feature request, This is expected to rolled out by end of this year.

**Comment by Wajeed-msft** [comment]
Keeping this open till bug is actually fixed and deployed.

**Comment by Wajeed-msft** [comment]
Checking latest status with engineering team on this.

**Comment by Wajeed-msft** [comment]
We will share some updates on this in first week of Jan.

**Comment by Wajeed-msft** [comment]
Still don't have updates on this. I'll keep this thread updated once I get more details.

**Comment by Saonti-MSFT** [comment]
@Wajeed-msft This bug is closed and moved as a requirement. here is the ID [1124696](https://domoreexp.visualstudio.com/MSTeams/_workitems/edit/1124696)
