### ISSUE TITLE
Launch config results in "SyntaxError: Cannot use import statement outside a module"

### ISSUE THREAD

**Issue by erinha** [MicrosoftDocs/msteams-docs#2064]
The steps described in "Update your hosted app" instruct users to create a launch.json file to set appropriate environment variables in order to enable the the bot and the messaging extension. 

I created it following the steps and when I attempt to run it, I get the following error:

```
Debugger listening on ws://127.0.0.1:56459/357500ce-0d72-4f89-8ce8-88ca37e31451
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
Waiting for the debugger to disconnect...
<repopath>\msteams-samples-hello-world-nodejs\src\app.js:4
import path from 'path';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1047:16)
    at Module._compile (internal/modules/cjs/loader.js:1097:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47
Process exited with code 1
```

Version info:
git: 2.24.1.windows.2
node: v12.16.3
npm: v6.14.4
gulp local: v4.0.2
gulp CLI: v2.3.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4fa27cb-544f-f8a2-97a7-4b31528c1b80
* Version Independent ID: fa69cd6f-1ef4-706d-2816-aa709714b0aa
* Content: [Get started with App Studio and Node.js - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tutorials/get-started-nodejs-app-studio)
* Content Source: [msteams-platform/tutorials/get-started-nodejs-app-studio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tutorials/get-started-nodejs-app-studio.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Trinetra-MSFT** [comment]
@erinha , Could you please check this working [Javascript_nodejs](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/javascript_nodejs) sample code?
