### ISSUE TITLE
Brand marketing guidelines - App name & metadata update required

### ISSUE THREAD

**Issue by ghantasalaphanidhar** [MicrosoftDocs/msteams-docs#2072]
Hi All,
Need below edits to this page.
1) Details are added in the attached document. 
[Brand marketing guidelines - App name & metadata.docx](https://github.com/MicrosoftDocs/msteams-docs/files/5224017/Brand.marketing.guidelines.-.App.name.metadata.docx)

Source of data is internal channel: https://teams.microsoft.com/l/message/19:80548b7b025e463bb6a8a26900998887@thread.skype/1599715353293?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=0fc13f25-bc6a-484b-84e5-a7e3f385883f&parentMessageId=1599667515645&teamName=CaPT%20-%20India%2BMEA&channelName=CaPT%20Apps%20Validation&createdTime=1599715353293

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22ac9894-41a6-543e-c6c9-8af314bb81c8
* Version Independent ID: 44ac7805-a6fa-a717-df85-1a7677630486
* Content: [Build a great app details page - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/detail-page-checklist#app-name)
* Content Source: [msteams-platform/concepts/deploy-and-publish/appsource/prepare/detail-page-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/deploy-and-publish/appsource/prepare/detail-page-checklist.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by ghantasalaphanidhar** [comment]
Need above updates to the below section in the documentation.
Section of Document: https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/detail-page-checklist#app-name

**Comment by KirtiPereira** [comment]
The resolved PR for this issue was merged on September 30.
https://github.com/MicrosoftDocs/msteams-docs/pulls?q=2109
