### ISSUE TITLE
Extend Share to Teams feature to provide input for the conversation subject

### ISSUE THREAD

**Issue by tdalon** [MicrosoftDocs/msteams-docs#2077]
It would be great if the feature explained here: https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/share-to-teams
could add a field for the conversation subject.

**Comment by Nikitha-MSFT** [comment]
Could you please raise a [user voice](https://microsoftteams.uservoice.com/)?

**Comment by tdalon** [comment]
The uservoice will definitely be lost. Please forward to the dev team responsible of this feature directly. It will be much faster.

**Comment by Nikitha-MSFT** [comment]
We have raised a future. We don't have ETA to share when it will be available.
