### ISSUE TITLE
USB Audio stops working on iOS when starting screen sharing

### ISSUE THREAD

**Issue by vianney** [MicrosoftDocs/msteams-docs#2079]
We are using the Apple "Lightning to USB Camera Adapter" to connect an USB Audio device to an iPhone. When starting a call in Teams, the audio is correctly routed to/from the USB Audio device. Tapping on the speaker selection button shows a dialog in the center of the screen where we can choose from the iPhone's receiver, the iPhone's speaker and the USB Audio device.

Now, when we share the iPhone's screen in Teams, the audio falls back to the iPhone's speaker and microphone. Tapping on the speaker selection button shows another dialog (popup on the bottom of the screen) where we can only choose between "iPhone", "Speaker" and "Audio off" (no USB Audio).

### Steps to reproduce

1. Connect any USB Audio device (speaker, microphone or both) to the iPhone through the "Lightning to USB Camera Adapter"
2. Open Teams on the iPhone and start a one-to-one call
3. On the iPhone, tap on the three dots, select "Share", then "Share screen"
4. Tap on "Start Broadcast"
5. Wait for the 3-second countdown

### Expected result

The iPhone's screen should be shared and audio should still go through the USB Audio device.

### Actual result

The iPhone's screen is shared, but the audio goes through the iPhone's speaker and microphone. Stopping screen sharing does not help. The only way to have audio through the USB Audio device again is to stop the call and start again.

### Version information

Device: iPhone 7
iOS version: 13.7
Teams version: 2.0.20 (build 1.077.2020082103 / calling version 2020.28.01.14)

**Comment by Trinetra-MSFT** [comment]
@vianney , Just wanted to confirm, were you able to play audio on other app like youtube etc connected speaker when you are in meeting?

**Comment by vianney** [comment]
@Trinetra-MSFT Yes, I am able to play audio in other apps (tested with youtube on safari). The output goes to the same output as Teams. So once screen sharing is started, the video plays on the iPhone speaker instead of USB.

Actually, I noticed something weird today that did not happen when I tested it yesterday: I do not always have the choice between the iPhone receiver and the speaker anymore. Here are the options I see when clicking on the speaker selection button:

|                              | Without USB                | With USB           |
|------------------------------|----------------------------|--------------------|
| Before screen sharing        | iPhone, Speaker, Audio off | Speaker, USB       |
| During/after screen sharing  | Speaker¹, Audio off        | Speaker, Audio off |

¹ Without USB connected, after starting screen sharing, there is no option anymore to switch between the iPhone receiver and the iPhone speaker. Selecting the "Speaker" option uses the output that was selected before starting screen sharing (i.e., if I was using the iPhone receiver, selecting "Speaker" after starting screen sharing still outputs audio to the receiver instead of the speaker).

I did not update anything on the iPhone, but I did update the desktop app (not sure how that can be related though).

**Comment by Trinetra-MSFT** [comment]
@vianney , Thanks for confirming, I will forward your query to right channel & update you accordingly
