### ISSUE TITLE
Adaptive Cards in Production

### ISSUE THREAD

**Issue by pschaeflein** [MicrosoftDocs/msteams-docs#208]
According to a tweet by Dan Stevenson (https://twitter.com/danspot/status/1027081245644140544), Adaptive Cards are in production. Should this page be updated to remove the "Developer Preview" clause for Adaptive Cards?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8a3bcf2-332a-8d24-a8d1-7e3816897745
* Version Independent ID: 68fb9551-ce95-0112-2703-721a1af01f23
* Content: [Cards Reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/cards/cards-reference)
* Content Source: [msteams-platform/concepts/Cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/Cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by billbliss** [comment]
We'll update this. Dan jumped the gun a little - we were planning to announce once mobile support is in the store - very soon. @NormSohl is on it.

**Comment by billbliss** [comment]
Fixed.
