### ISSUE TITLE
Incorrect number of buttons under scope

### ISSUE THREAD

**Issue by guyrleech** [MicrosoftDocs/msteams-docs#2083]
Document says:

Add a bot name such as Contoso bot, and click both the buttons under scope

Button there are 3 buttons - Personal, Team and Group Chat

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f98c73d-bb68-3088-6e7d-2c576a8292f6
* Version Independent ID: 08b9df7d-4997-c681-e73a-235ec1e4fc7b
* Content: [Get started with C#/.NET - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tutorials/get-started-dotnet-app-studio)
* Content Source: [msteams-platform/tutorials/get-started-dotnet-app-studio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tutorials/get-started-dotnet-app-studio.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Trinetra-MSFT** [comment]
@guyrleech , Yes there are three checkbox for Scope of a Bot `Personal`, `Team`, `GroupChat`,. Document needs to be updated .
![image](https://user-images.githubusercontent.com/50989436/93566145-32c8d300-f9aa-11ea-9716-8920d2d7d827.png)
