### ISSUE TITLE
i dont see any commands on the bot

### ISSUE THREAD

**Issue by asenseofh** [MicrosoftDocs/msteams-docs#2088]
when i save the commands, there's nothing change on the bot. do i have to deploy the app on teams? However, there are so many restrictions from the company if we push the deployment.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a982542-ae03-2ada-cf71-4d586272e0c3
* Version Independent ID: 9e1fd82b-79e4-1b8d-5367-a8de3d04b3aa
* Content: [Create a command menu for your bot - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/create-a-bot-commands-menu?tabs=dotnet)
* Content Source: [msteams-platform/bots/how-to/create-a-bot-commands-menu.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/bots/how-to/create-a-bot-commands-menu.md)
* Product: **msteams**
* GitHub Login: @clearab
* Microsoft Alias: **anclear**

**Comment by VaraPrasad-MSFT** [comment]
You have to sideload the app to teams to see the updated bot commands. When you made changes to the deployed manifest you need to reinstall the manifest.
