### ISSUE TITLE
Can't use example JSON payload for sending an Adaptive Card to an inbound webhook

### ISSUE THREAD

**Issue by cozimek** [MicrosoftDocs/msteams-docs#2091]
We've been following the documentation example for "The flow for sending adaptive cards via an incoming webhook is as follows" but it's still not working. In Postman, we're getting a 400 error: "Webhook message delivery failed with error: Microsoft Teams endpoint returned HTTP error 400 with ContextId...".  Might inbound webhooks not accept Adaptive Cards as of September 18, 2020?

**Comment by Nikitha-MSFT** [comment]
@cozimek - We are not able to reproduce the issue at our end. Also could you please share the requestbody and webhhok url?

**Comment by cozimek** [comment]
While the webhook URL is private for our Teams channel and works properly for O365 Connector Cards, I can at least share the body of the Adaptive Card that we're trying to send via Postman.

`{
   "type":"message",
   "attachments":[
      {
         "contentType":"application/vnd.microsoft.card.adaptive",
         "contentUrl":null,
         "content":{
            "$schema":"http://adaptivecards.io/schemas/adaptive-card.json",
            "type":"AdaptiveCard",
            "version":"1.0",
            "body":[
               {
                  "For Samples and Templates, see":"https://adaptivecards.io/samples"
               }
            ]
         }
      }
   ]
}`

**Comment by Nikitha-MSFT** [comment]
The adaptive card in the document is wrong. We are working on updating the card.
Could you please try this card:
```
{
   "type":"message",
   "attachments":[
      {
         "contentType":"application/vnd.microsoft.card.adaptive",
         "contentUrl":null,
         "content":{
            "$schema":"http://adaptivecards.io/schemas/adaptive-card.json",
            "type":"AdaptiveCard",
            "version":"1.2",
            "body":[
               {
                  
            "type": "TextBlock",
            "text": "This is Adaptive Card",
            "weight": "bolder",
            "size": "medium"
          
               }
            ]
         }
      }
   ]
}
```

**Comment by cozimek** [comment]
@Nikitha-MSFT it works! This is fantastic, thanks for the updated example.
