### ISSUE TITLE
Website URL option in teams

### ISSUE THREAD

**Issue by tbendick** [MicrosoftDocs/msteams-docs#2094]
Trying to add a website in teams that ends in .host but it comes "That isn't a valid URL"
And ideas on how to fix/override?

**Comment by Gousia-MSFT** [comment]
@tbendick What is the url you are trying to load? Are you trying to add it as a Tab? Could you please check if the URL satisfies the [Tab requirements](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/add-tab#tab-requirements)?
