### ISSUE TITLE
Max image size for inline cards is actually not 1MB

### ISSUE THREAD

**Issue by abhilashmurthy** [MicrosoftDocs/msteams-docs#2098]
We have a chatbot platform, and one of our customers uses our chatbot platform to manage their Skype bot. The documentation says that cards have an image size limit of 1 MB. However, our customer tested it and was able to upload an image of size 1.2MB (which is greater than 1MB). The image still looked fine and worked properly in the Skype bot.

Therefore, the documentation is misleading. Please do update the documentation and remove the image size limit as it has been confusing our Skype bot users.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Cards Reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by VaraPrasad-MSFT** [comment]
We are not able to repro it from our end, could you please provide more information.

**Comment by abhilashmurthy** [comment]
Hi @VaraPrasad-MSFT ,

Sure. Here are the steps to reproduce the bug:
1. Please use any file/image hosting service to upload a GIF greater than 1MB. You may also use this example which is 1.5MB: https://i.stack.imgur.com/p6tME.gif

2. Attach this GIF to a card of type `application/vnd.microsoft.card.hero` with the `image_url` property. Make the bot send this card to a user.

You will notice that the GIF displays fine in MS Teams or Skype. Technically, it should **not** display fine as the documentation explicitly states that images within cards must be at most 1MB in size. This was misleading because we restricted our users to shrinks their GIFs to a much lower quality to meet this limit, and it affected the end user's experience.

**Comment by VaraPrasad-MSFT** [comment]
@laujan : we are able to reproduce this and able upload the size of 1.5mb.
