### ISSUE TITLE
showLoadingIndicator key does not explain how to acknowledge app load.

### ISSUE THREAD

**Issue by koushik-shetty** [MicrosoftDocs/msteams-docs#2100]
[The *showLoadingIndicator* key does not explain or reference how to acknowledge app load, this leads to the assumption that teams automatically takes care of this on behalf of the user, this is confusing]---#### Document Details⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.** ID: 0f94a488-d636-92b3-21eb-c88744c8f272* Version Independent ID: 7b3413f4-9ade-accf-5cb2-83fead11a32a* Content: [Manifest schema reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema)* Content Source: [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/resources/schema/manifest-schema.md)* Product: **msteams*** GitHub Login: @laujan* Microsoft Alias: **lajanuar**

**Comment by Wajeed-msft** [comment]
@koushik-shetty - Thanks for the reporting this. Here is [existing work](https://github.com/MicrosoftDocs/msteams-docs/issues/1934) item for the same.  This should be fixed as part of [this PR](https://github.com/MicrosoftDocs/msteams-docs/pull/2082).
