### ISSUE TITLE
the notifyAppLoaded() api functionality is confusing

### ISSUE THREAD

**Issue by koushik-shetty** [MicrosoftDocs/msteams-docs#2101]
****
The *notifyAppLoaded* does not indicate that the actual app load is successful, The api used alone causes the loader to disappear and the app to show a failed message. Calling *notifySuccess/notifyFailure* is mandatory is not apparent. Adding  [this](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/content-page#show-a-native-loading-indicator) reference link would help here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e55d596b-b325-02d4-b05c-57c2b5ad60cd
* Version Independent ID: 65265f6d-25a5-b641-96ed-e8ada5323fe3
* Content: [appInitialization module - Teams](https://docs.microsoft.com/en-us/javascript/api/@microsoft/teams-js/microsoftteams.appinitialization?view=msteams-client-js-latest#notifyapploaded--)
* Content Source: [nodejs/docs-ref-autogen/@microsoft/teams-js/microsoftTeams.appInitialization.yml](https://github.com/OfficeDev/msteams-client-docs-ref-typescript/blob/live/nodejs/docs-ref-autogen/@microsoft/teams-js/microsoftTeams.appInitialization.yml)
* Product: **msteams**
* GitHub Login: @charlesprakash
* Microsoft Alias: **o365devx**

**Comment by surbhigupta12** [comment]
@v-chetsh, not in doc teams purview.

**Comment by Wajeed-msft** [comment]
This is part of auto generated documentation. I'll check if we could update the SDK code to include link.

**Comment by Wajeed-msft** [comment]
Closing this issue as we have latest SDK method `notifyAppLoaded` which hide the loading indicator.

https://learn.microsoft.com/en-us/javascript/api/@microsoft/teams-js/app?view=msteams-client-js-latest#@microsoft-teams-js-app-notifyapploaded
