### ISSUE TITLE
Deeplink to a file within a team

### ISSUE THREAD

**Issue by justdevelopment** [MicrosoftDocs/msteams-docs#2105]
How can we use executeDeepLink to send a user directly to a specific file in a Team? 

I've used these docs; https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links
and we can deeplink to events and Teams themselves, but documents keep giving errors. 

When using the URL as generated by Teams itself it works `https://teams.microsoft.com/l/file/{fileGUID}?tenantId={tenantGUID}&fileType={fileType}&objectUrl={url}&baseUrl={baseURL}&serviceName=teams`, but that contains a file ID we don't have access to (it doesn't appear to be available in any Graph call I can find). I've found #1174  this seems to use the same URL template but doesn't mention how to get the file ID. If I leave the file ID out, it will just error out and not work. 

We'd also like to be able to send a user to the default Files tab in a channel, is this possible via deeplinking? This is a nice-to-have though, whereas direct linking to a document is really a must have for our product.

**Comment by Nikitha-MSFT** [comment]
You get get file id by using Graph API. Could you please check this [docs](https://docs.microsoft.com/en-us/graph/api/driveitem-get?view=graph-rest-beta&tabs=http)? Try if that helps.

**Comment by justdevelopment** [comment]
The file ID I get from Graph is not a GUID and not accepted by teams. If I put that in, it just gives me an error / file not found. 

https://docs.microsoft.com/en-us/graph/api/driveitem-get?view=graph-rest-beta&tabs=http#response-1
```
"id": "01NKDM7HMOJTVYMDOSXFDK2QJDXCDI3WUK",

**Comment by Nikitha-MSFT** [comment]
Could you please try Putting this id: 5E0154FC-F2B4-4DA5-8CDA-F096E72C0A80 in the deeplink?

**Comment by justdevelopment** [comment]
Hi Nikitha, that ID didn't do much unfortunately, but I took another look at the docs and I found 'sharepointIds' in DriveItem which has listItemUniqueId, which is also the ID expected by teams :) Using this value I can open the files directly. 

We do still wonder if we can open the Files tab directly for a specified team, do you know if this is possible and if so how?

**Comment by Nikitha-MSFT** [comment]
Currently we cannot deeplink to files tab of a specific team. Could you please raise a [user voice](https://microsoftteams.uservoice.com/forums/555103-public-preview/category/182881-developer-platform) ?
