### ISSUE TITLE
How to use the web-based authentication flow with a conversational bot?

### ISSUE THREAD

**Issue by dejancg** [MicrosoftDocs/msteams-docs#2110]
The [section](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/authentication/authentication#web-based-authentication-flow) of the documentation states the following: 
> If you want to use the web-based authentication flow with a conversational bot, you'll need to use a task module with a bot.

Yet, as a comment on this StackOverflow question: https://stackoverflow.com/questions/62182009/is-it-possible-to-signin-from-task-module-in-teams-bot-framework-4, the Microsoft representative claims the following: 
> Sigincard is not supported in Task Module

In the first quoted sentence above, where you state that if developers want to use web-based authentication flow with a conversational bot, they will need to use a task module, instead of linking to https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/task-modules/task-modules-bots (Using task modules from Microsoft Teams bots) which doesn't provide any help on the topic, you should have linked to a documentation page or a sample explaining how to use the web-based authentication with a conversational bot.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6416300-1ddf-3ffd-10d2-99ed1f4eb08c
* Version Independent ID: 335d9588-866d-bdde-f1de-6a093a091e2a
* Content: [Authenticate a user in Teams - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/authentication/authentication)
* Content Source: [msteams-platform/concepts/authentication/authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/authentication/authentication.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by VaraPrasad-MSFT** [comment]
@dejancg , Currently we don't have sample for Auth in task module, here is the [sample for authentication](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/46.teams-auth). 
Please let us know if you need any help on this.

**Comment by dejancg** [comment]
@VaraPrasad-MSFT thank you for your response.
I know about those examples. However, they don't show how to start the authentication using that specific scenario, using the task module, which your documentation clearly references. You need to fix the documentation to clearly show how to use the web-based authentication flow from bot messages (not messaging extensions).
