### ISSUE TITLE
The outline icon of a teams app is blurry at 32x32 pixels

### ISSUE THREAD

**Issue by martinhenrysson** [MicrosoftDocs/msteams-docs#2111]
I just uploaded a new 32x32 pixels large outline icon (PNG) for a teams app and it's blurry compared to the built-in icons. The documentation clearly states that the outline icon needs to be 32x32 pixels, but I tried uploading a 64x64 icon which looks much better (not sure if it matches the built-in icons in sharpness, though). It would be great if you could update the documentation to reflect the actual limitation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0b75ec1-0ded-400e-7291-b7776d510ae4
* Version Independent ID: 157f3a51-42f6-f70f-a599-6775fcb34ed1
* Content: [Package your app - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/apps-package)
* Content Source: [msteams-platform/concepts/build-and-test/apps-package.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/build-and-test/apps-package.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Wajeed-msft** [comment]
@Gousia-MSFT - Could you please confirm if you are able to upload 64x64 size image? Please update this thread with max supported size so that same can be updated in documentation.

**Comment by martinhenrysson** [comment]
Just to clarify the 64x64px PNG was uploaded in a zipped package. The manifest editor in App Studio won't allow anything larger than 32x32px.

![image](https://user-images.githubusercontent.com/35069050/95218214-57b7a580-07f4-11eb-8dc5-17b0fe24d449.png)

**Comment by Gousia-MSFT** [comment]
@martinhenrysson We could repro the issue on our side. We have raised a bug to validate the icon size while uploading the zip package. Thanks!!

**Comment by martinhenrysson** [comment]
@Gousia-MSFT Thanks, but the 32x32px outline icon I used turned out blurry in the side panel (Windows desktop app). Could you reproduce that too?

**Comment by Abhijit-MSFT** [comment]
Could you please share your manifest to microsoftteamsdev@microsoft.com.

**Comment by Wajeed-msft** [comment]
martinhenrysson - could you please check if you are still facing this issue?

**Comment by martinhenrysson** [comment]
@Wajeed-msft Thanks! I just uploaded a manifest with a 64x64px outline icon. Still works. Or are youreferring to the blurriness when using a 32x32px icon?
