### ISSUE TITLE
Specifying Meeting Apps when creating meetings programatically

### ISSUE THREAD

**Issue by GauravES** [MicrosoftDocs/msteams-docs#2114]
[Enter feedback here]

Can you add documentation on if or when (or how) when meetings are created using Graph, will it be possible to specify the Meetings Apps that should be automatically added? The docs above seem to show manual steps when meetings are created using the Meeting scheduler wizards.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82987815-d508-d642-c1f6-b609241d4750
* Version Independent ID: 29e89cc6-c8ca-7d29-7dca-4ac4d06f5c42
* Content: [Apps to Teams meetings - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/teams-apps-in-meetings)
* Content Source: [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Trinetra-MSFT** [comment]
@GauravES , You can specify the context for your application so it will be available during the meeting. Please look at [context property ](https://docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?tabs=json#context-property)

**Comment by Wajeed-msft** [comment]
You can Install a [teamsApp](https://learn.microsoft.com/en-us/graph/api/resources/teamsapp?view=graph-rest-beta) to the specified [chat](https://learn.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta).

If the chat is associated with an [onlineMeeting](https://learn.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-beta) instance, then, effectively, the teamsApp will get installed to the meeting.

Ref: https://learn.microsoft.com/en-us/graph/api/chat-post-installedapps?view=graph-rest-beta&tabs=http

Closing this issue from tracking list.
