### ISSUE TITLE
using node js demo to build teams tab success, but can not import to team

### ISSUE THREAD

**Issue by yetsmarch** [MicrosoftDocs/msteams-docs#2116]
hello, I tried to create teams app using demo as 
https://docs.microsoft.com/en-us/microsoftteams/platform/tutorials/get-started-nodejs-app-studio guide, 
but in "Update your hosted app" chapter demo does not work successfully. while I using vs code to debug the demo as server, terminal shows "Uncaught SyntaxError: Unexpected identifier". and I tried install --save-dev @babel/core and so on as readme direct, not work as well.
my node version is 10.22.1 and npm version is 6.14.6

second, I created app and imported to teams success, the app's tab page shows normal. 
but in team channel, I wanna to search this app in "add a tab" page,  but there is nothing in search page.

what's more,  in apps, I upload the app, and choose the "add to a team", but popup a page showing "something went wrong"

I'm a newcomer, hoping an answer, thank you!

**Comment by VaraPrasad-MSFT** [comment]
@yetsmarch  For Update your hosted app , you need to provide your app details here like app Id, password which you used in the app studio. 
For the second one, you can find "Manage apps"  at the bottom right corner of the "add a tab" page , from there you can upload a custom app.
