### ISSUE TITLE
Teams docs: [build your first app/build personal tab#match-theme-styles] request for clarification.

### ISSUE THREAD

**Issue by kriszentner** [MicrosoftDocs/msteams-docs#2125]
Going through the personal tab documentation. I know quite a bit about some other languages (python, ruby, powershell, go) but nodejs is something I'm fairly new at. That said, in the section ["Match Theme Styles"](https://docs.microsoft.com/en-us/microsoftteams/platform/build-your-first-app/build-personal-tab#match-theme-styles), it would be most helpful to give further clarity on where below code in the page goes:

```javascript
const isTheme = this.state.theme
```
and
```javascript
let newTheme

if (isTheme === "default") {
  newTheme = {
    backgroundColor: "#EEF1F5",
    color: "#16233A"
  };
} else {
  newTheme = {
    backgroundColor: "#2B2B30",
    color: "#FFFFFF"
  };
}
```

I've tried multiple places (one at a time of course) in `Tab.js` under`componentDidMount(){}`, `render() {}`, and in `microsoftTeams.registerOnThemeChangeHandler(theme => {}` without getting the expected result.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29e90229-289e-2035-3b42-5cb9cce14efe
* Version Independent ID: a2aee4b8-93b9-bda7-f000-8f41b4513647
* Content: [Build a Teams personal tab - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/build-your-first-app/build-personal-tab)
* Content Source: [msteams-platform/build-your-first-app/build-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/build-your-first-app/build-personal-tab.md)
* Product: **msteams**
* GitHub Login: @heath-hamilton
* Microsoft Alias: **lajanuar**

**Comment by kriszentner** [comment]
Adding another comment for clarity, to me the documentation seems to land on the below for the `Tab.js` code (yes I added a little debug step in the return() text. Feel free to correct me.

```javascript
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

import React from 'react';
import './App.css';
import * as microsoftTeams from "@microsoft/teams-js";

/**
 * The 'PersonalTab' component renders the main tab content
 * of your app.
 */
class Tab extends React.Component {
  constructor(props){
    super(props)
    this.state = {
      context: {}
    }
  }

  //React lifecycle method that gets called once a component has finished mounting
  //Learn more: https://reactjs.org/docs/react-component.html#componentdidmount
  componentDidMount(){
    // Get the user context from Teams and set it in the state
    microsoftTeams.getContext((context, error) => {
      this.setState({
        context: context
      });
    });
    // Next steps: Error handling using the error object
    microsoftTeams.registerOnThemeChangeHandler(theme => {
      if (theme !== this.state.theme) {
        this.setState({ theme });  
      }
    });

    const isTheme = this.state.theme

    let newTheme

    // default is a light background
    // otherwise we use text for dark and high contrast modes
    if (isTheme === "default") {
      newTheme = {
        backgroundColor: "#EEF1F5",
        color: "#16233A"
      };
    } else {
      newTheme = {
        backgroundColor: "#2B2B30",
        color: "#FFFFFF"
      };
    }
  }
  
  render() {

      let userName = Object.keys(this.state.context).length > 0 ? this.state.context['upn'] : "";

      return (
      <div>
        <h1>Important Contacts</h1>
          <ul>
            <li>Help Desk: <a href="mailto:support@company.com">support@company.com</a></li>
            <li>Human Resources: <a href="mailto:hr@company.com">hr@company.com</a></li>
            <li>Facilities: <a href="mailto:facilities@company.com">facilities@company.com</a></li>
            <li>You're using {this.state.context['theme']} mode</li>
          </ul>
      </div>
      );
  }
}
export default Tab;
```

**Comment by Sw1ma** [comment]
I came across the same issue last week. But yesterday I followed this learning path ([Exercise - Create a custom Microsoft Teams personal tab](https://docs.microsoft.com/en-us/learn/modules/embedded-web-experiences/3-exercise-create-custom-teams-personal-tab)) on Microsoft Learn where it's fully clarified as part of the exercise. 

I hope this will help.

**Comment by v-sdhakshina** [comment]
Theme related content moved to Learn module https://docs.microsoft.com/en-us/learn/modules/embedded-web-experiences/3-exercise-create-custom-teams-personal-tab

**Comment by Wajeed-msft** [comment]
Please re-open if you are still facing this issue.
