### ISSUE TITLE
How do I submit an issue for this Teams excercise?

### ISSUE THREAD

**Issue by plamber** [MicrosoftDocs/msteams-docs#2126]
Hello,
I am currently validating the exercises located under https://docs.microsoft.com/en-us/learn/modules/msteams-task-modules/3-exercise-use-task-modules-tabs and found out a small issue that requires a change to the text. Unfortunately, I haven't found a channel to submit a change request to the document as you can usually do here.

Could you help me locate the location where I can do that?

Thank you

**Comment by Nikitha-MSFT** [comment]
What is the issue with the text? Could you please share more info where the documentation change is required?

**Comment by plamber** [comment]
Hi @Nikitha-MSFT,
I tried to run the exercise. In the section "Ensure the project is using the latest version of Teams manifest & SDK" you are being asked to verify the SKD version. Just by using npm i @microsoft/teams-js it does not update the package. I had to run npm u @microsoft/teams-js to make this work.

br,
Patrick

**Comment by Wajeed-msft** [comment]
This is a no longer requirement as scaffolded solution would point to latest SDK version. Closing this from doc issues list. Please feel free to reopen.
