### ISSUE TITLE
"Manifest parsing has failed" on install of app when manifest includes the "context" property

### ISSUE THREAD

**Issue by cozimek** [MicrosoftDocs/msteams-docs#2128]
I'm trying the new "context" property within the manifest, and have my Teams app in "Developer Preview" mode.  I've added the appropriate "context" property elements [from the guide](https://docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?tabs=json#update-your-app-manifest), but when I try uploading my zip file when installing my app into Teams, it shows the "Manifest parsing has failed" message.

I also notice that in VSCode, I'm seeing a problem: "Property context is not allowed."

Might the documentation for adding this to the manifest be incorrect?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b60eeacc-a71e-9644-b869-3e0a4f1506d8
* Version Independent ID: 313bf83f-5325-f9f4-5780-9bc81e315c1e
* Content: [Create apps for teams meetings - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?tabs=json)
* Content Source: [msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Wajeed-msft** [comment]
Could you please share your App Manifest? Also, did you try using [Developer preview manifest schema](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema-dev-preview)

**Comment by cozimek** [comment]
@Wajeed-msft "Also, did you try using the Developer preview manifest schema".  That was the issue!  Once we used that, we were able to get the manifest to upload successfully. We're still not able to see the right galley in the meeting experience, though, so we'll need to review that further internally.

Thank you.

**Comment by Wajeed-msft** [comment]
> That was the issue! Once we used that, we were able to get the manifest to upload successfully. 

Awesome. I am updating the docs so that others won't face the same issue. (https://github.com/MicrosoftDocs/msteams-docs/pull/2136)

> We're still not able to see the right galley in the meeting experience, though, so we'll need to review that further internally.

Please raise new issue so that it can be tracked better.
