### ISSUE TITLE
Are botid and botpassword correct?

### ISSUE THREAD

**Issue by guyrleech** [MicrosoftDocs/msteams-docs#2129]
I'm new to this, hence why I'm running through the tutorial, but shouldn't they be BotId0 and BotPassword0 since we have already set baseURL0? Also, botID0 is already populated with the correct GUID, presumably when VS Code saved the files after I created the bot ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5dbbdd70-5068-9e54-b797-7a32ea45672f
* Version Independent ID: 8719249a-face-cf09-04a2-57d7cde082a9
* Content: [Build a Teams messaging extension - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/build-your-first-app/build-messaging-extension)
* Content Source: [msteams-platform/build-your-first-app/build-messaging-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/build-your-first-app/build-messaging-extension.md)
* Product: **msteams**
* GitHub Login: @heath-hamilton
* Microsoft Alias: **lajanuar**

**Comment by Manish-MSFT** [comment]
Hi @guyrleech, Could you please let us know which environment(C# or Node.js) are you using? Also, Which sample code are you currently using?

**Comment by Gousia-MSFT** [comment]
Please re-open with requested information
