### ISSUE TITLE
Typo baseUrl10 

### ISSUE THREAD

**Issue by guyrleech** [MicrosoftDocs/msteams-docs#2130]
baseUrl10 should be baseUrl0 I believe 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5dbbdd70-5068-9e54-b797-7a32ea45672f
* Version Independent ID: 8719249a-face-cf09-04a2-57d7cde082a9
* Content: [Build a Teams messaging extension - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/build-your-first-app/build-messaging-extension)
* Content Source: [msteams-platform/build-your-first-app/build-messaging-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/build-your-first-app/build-messaging-extension.md)
* Product: **msteams**
* GitHub Login: @heath-hamilton
* Microsoft Alias: **lajanuar**

**Comment by v-rodriguezd** [comment]
Cannot find baseUrl10 anywhere in the referenced document. Please check and let me know.
