### ISSUE TITLE
Resource URL must be made required field in  webApplicationInfo section

### ISSUE THREAD

**Issue by Santhoshikumari** [MicrosoftDocs/msteams-docs#2133]
Resource URL must be made as a required field in webApplicationInfo section

![Capture](https://user-images.githubusercontent.com/53852790/94476431-19b3f380-01ee-11eb-8de9-a1bc016cb9ec.PNG)

**Comment by v-rodriguezd** [comment]
The reference links to the file are missing. Please include the document details for which the issue has been raised.

**Comment by KirtiPereira** [comment]
@laujan , @Wajeed-msft - the Details section seems to be missing here.
