### ISSUE TITLE
When will this functionality be available?

### ISSUE THREAD

**Issue by HeSteIT** [MicrosoftDocs/msteams-docs#2139]
First of all, sorry - this is not really an issue but a question - I did not find the possibility to create a question here.

In my targeted release developer tenant, I have not been able to create a team in migration mode so far.
The request used in the documentation of step 1 results in the following HTTP 400 error:

`{
    "error": {
        "code": "BadRequest",
        "message": "Required functionality is not supported.",
        "innerError": {
            "date": "2020-09-30T07:48:11",
            "request-id": "e9b89283-d66f-434e-80bd-1a4964fa6d24",
            "client-request-id": "e9b89283-d66f-434e-80bd-1a4964fa6d24"
        }
    }
}`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5687f17-f3c7-39be-5487-f24f2155191a
* Version Independent ID: ce77e760-90cf-e6b1-3cec-ae55ee50c33e
* Content: [Use Microsoft Graph to import external platform messages to Teams - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/graph-api/import-messages/import-external-messages-to-teams)
* Content Source: [msteams-platform/graph-api/import-messages/import-external-messages-to-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/graph-api/import-messages/import-external-messages-to-teams.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by bvksphub** [comment]
We are having same issue, Any update?

**Comment by Manish-MSFT** [comment]
Hi @HeSteIT , We are investigating this internally and will communicate further details.

**Comment by Manish-MSFT** [comment]
@nkramer , @laujan : Is there any roadmap for this functionality?

**Comment by Manish-MSFT** [comment]
Hi @HeSteIT, there is no ETA to share. You can please raise a user voice at [here](https://microsoftteams.uservoice.com/forums/555103-public-preview/category/182881-developer-platform)
