### ISSUE TITLE
Step Three: Import messages- Require Updates

### ISSUE THREAD

**Issue by bvksphub** [MicrosoftDocs/msteams-docs#2140]
We have tried executing calls under "step three- import messages" and unable to execute the call. Any changes to these calls that we need to be aware of ? We are basically looking to post message with back in timestamp.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5687f17-f3c7-39be-5487-f24f2155191a
* Version Independent ID: ce77e760-90cf-e6b1-3cec-ae55ee50c33e
* Content: [Use Microsoft Graph to import external platform messages to Teams - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/graph-api/import-messages/import-external-messages-to-teams#tips-and-additional-information)
* Content Source: [msteams-platform/graph-api/import-messages/import-external-messages-to-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/graph-api/import-messages/import-external-messages-to-teams.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Trinetra-MSFT** [comment]
@bvksphub , Could you please provide your request body and error response with failed request-id so we can check the logs?

**Comment by bvksphub** [comment]
Here you go. PFA screenshot as well

Request Body:
{
"@microsoft.graph.teamCreationMode": "migration",
"template@odata.bind<mailto:template@odata.bind>": "https://graph.microsoft.com/beta/teamsTemplates('standard')",
"displayName": "My Sample Team",
"description": "My Sample Team’s Description",
"createdDateTime": "2020-03-14T11:22:17.067Z"
}

Request Response:
{
"error": {
"code": "BadRequest",
"message": "Required functionality is not supported.",
"innerError": {
"date": "2020-10-05T16:49:39",
"request-id": "fe45ba05-77b3-4f88-9922-a5e3ed28d30d",
"client-request-id": "b6939769-b6c3-d7fb-0bf2-03d470ea1d0b"
}


Thanks
Vamsi

**Comment by Trinetra-MSFT** [comment]
@bvksphub , Thanks for providing the request-id , We will get back to you in sometime

**Comment by Trinetra-MSFT** [comment]
The call was made in OnBehalfOf user (delegated context). Import is supported only in application context

**Comment by bvksphub** [comment]
We will review this and get back to you.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by bvksphub** [comment]
Hi,

We have also executed the same using code/application context. We got the same error response. Please find the details below.


Code: BadRequest

Message: Required functionality is not supported.

Inner error:

        AdditionalData:

        date: 2020-10-07T17:10:10

        request-id: 7f22e8a4-fdf7-4bb0-9621-37e2b49407e0

        client-request-id: 7f22e8a4-fdf7-4bb0-9621-37e2b49407e0

ClientRequestId: 7f22e8a4-fdf7-4bb0-9621-37e2b49407e0


Thanks
Vamsi

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by Trinetra-MSFT** [comment]
@bvksphub The API is in private preview and requires whitelisting.

**Comment by bvksphub** [comment]
Can you let me know the process

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Trinetra-MSFT** [comment]
Please reach out to teamsAppPerms@microsoft.com regarding the [protected API and requesting access.](https://docs.microsoft.com/en-us/graph/teams-protected-apis)

**Comment by TonyLi2013** [comment]
Same error received with App-Only access token

**Comment by matt-wright** [comment]
Hello, I am using this body to POST a new message using the URL example with slight edits as an app only posting in postman with a valid access token:
{
   "createdDateTime":"2019-04-04T19:58:15.911Z",
   "from":{
      "user":{
         "id":"<valid tenant principal name as an email>",
         "displayName":"<display name>",
         "userIdentityType":"aadUser"
      }
   },
   "body":{
      "contentType":"html",
      "content":"Hello World"
   }
}

The response is:
{
    "error": {
        "code": "BadRequest",
        "message": "Bad Request",
        "innerError": {
            "date": "2020-10-23T13:48:10",
            "request-id": "7b8c64cf-9c33-45b0-953c-be9e9e17aeb0",
            "client-request-id": "7b8c64cf-9c33-45b0-953c-be9e9e17aeb0"
        }
    }
}

The team and channel were both created in migration mode, and the new message post time stamp is after the createdDateTime.  My user id as an email is valid in the target tenant.  Not sure if this is because I am not using my tenant user id instead of my email.  Can you comment here please?
