### ISSUE TITLE
Color values are incorrect

### ISSUE THREAD

**Issue by HaveSpacesuit** [MicrosoftDocs/msteams-docs#2145]
Many of the stated color values do not match up with the actual colors used. For example, $app-white-darktheme lists #F2F2F1 as the color code, but inspecting the element reveals the code used is actually #FFFFFF. The linked CodePen examples have similar problems. It may also be useful to mention on the page that the msteams-ui-styles-core library has the actual values coded as variables. Using these as variables will help if the colors are ever updated.

![image](https://user-images.githubusercontent.com/15036346/94844720-492c5100-03e4-11eb-9f75-de168e99d376.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6191356-f04e-ab08-d1dd-503eb6ec15dd
* Version Independent ID: 87b86b41-6c67-69ad-9712-cbe3a51d1ffd
* Content: [Design Guidelines Reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/design/components/color)
* Content Source: [msteams-platform/concepts/design/components/color.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/design/components/color.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Trinetra-MSFT** [comment]
@HaveSpacesuit , Thanks for your suggestion. I can repro this at my side
![image](https://user-images.githubusercontent.com/50989436/95075635-2aa0bf80-072e-11eb-99de-0df76d53a60b.png)
Will ask to update the documentation

**Comment by Trinetra-MSFT** [comment]
@laujan : Please add this Note in [design guidelines](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/design/components/color) document:
**Note:** The msteams-ui-styles-core library has the actual values coded as variables. Using these as variables will help if the colors are ever updated.
