### ISSUE TITLE
FileUploadCompletedAsync is missing

### ISSUE THREAD

**Issue by sashaeve** [MicrosoftDocs/msteams-docs#2147]
FileUploadCompletedAsync is missing in code sample.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 294157df-f255-42c7-4e31-c9f0a9f0c3ea
* Version Independent ID: 25335b03-ad4a-d314-74f0-36284a922c3c
* Content: [Send and receive files - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/send-and-receive-files?tabs=dotnet)
* Content Source: [msteams-platform/bots/how-to/conversations/send-and-receive-files.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/bots/how-to/conversations/send-and-receive-files.md)
* Product: **msteams**
* GitHub Login: @clearab
* Microsoft Alias: **anclear**

**Comment by clearab** [comment]
To unblock you, you can find the definition in the sample here: https://github.com/microsoft/botbuilder-dotnet/blob/a56420541365355be81ba8190b730409007e42a2/tests/Teams/FileUpload/Bots/TeamsFileBot.cs#L127
