### ISSUE TITLE
It's not working in React

### ISSUE THREAD

**Issue by roberto-ajolfi** [MicrosoftDocs/msteams-docs#2151]
Just tried to add a link using the steps from this page in a React application (scaffolded via create-react-app). No Teams icon is shown.

Steps:
1) added the reference to the launcher.js in the index.html page (public folder)
2) added the div to a React function component in the JSX returned

Nothing happened.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5964e0a9-bba0-c5a3-8099-f3845037726c
* Version Independent ID: 24565c3b-2bb5-2482-a6c7-7b1f62e38abb
* Content: [Share to Teams embedded button - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/share-to-teams)
* Content Source: [msteams-platform/concepts/build-and-test/share-to-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/build-and-test/share-to-teams.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Manish-MSFT** [comment]
Hi @roberto-ajolfi, have you once tried posting the div directly in the index.html page? Please once try and let us know.

**Comment by madebyem** [comment]
Any uptade on that?

**Comment by v-chetsh** [comment]
@roberto-ajolfi - Could you please confirm if your issue has resolved or still looking for any help?

**Comment by v-chetsh** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.
