### ISSUE TITLE
Feature: Reply to specific message in group

### ISSUE THREAD

**Issue by bbaishya** [MicrosoftDocs/msteams-docs#2152]
This is not exactly an issue. 

Description:
When in a group with multiple members, multiple messages are send some as information and some as queries. If there could be a feature where we can respond to specific message, it can be really helpful. Members in a group can easily understand  the response is to which message.

**Comment by Nikitha-MSFT** [comment]
Currently teams does not support replying to specific message in group. This feature will be available in future. Please upvote this [user voice](https://microsoftteams.uservoice.com/forums/555103-public/suggestions/37096450-able-to-reply-by-selecting-message-in-group-chat-w)
