### ISSUE TITLE
Query: Is there an option be make our status offline while still being logged in?

### ISSUE THREAD

**Issue by bbaishya** [MicrosoftDocs/msteams-docs#2153]
Require offline status to be available. This can be really helpful to keep ourselves offline after work hours especially during these times when we are working remotely.

**Comment by RamaMohanaChary** [comment]
@bbaishya: Yes, we have an option to make "Appear Offline" on top right of Microsoft Teams.

Please have a look on below screen shot:

![image](https://user-images.githubusercontent.com/71380905/95169841-224d9080-07d1-11eb-85db-e8e015df26e1.png)

**Comment by bbaishya** [comment]
Hi Rama,

I do not see it.
[image: image.png]

**Comment by bbaishya** [comment]
![image](https://user-images.githubusercontent.com/42479415/95184459-05bb5380-07e5-11eb-99bd-22c122aad22e.png)
