### ISSUE TITLE
Guest is misspelled as Guess at the bottom of the article. 

### ISSUE THREAD

**Issue by TheBluLion** [MicrosoftDocs/msteams-docs#2157]
Guest is misspelled as Guess at the bottom of the article. 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82987815-d508-d642-c1f6-b609241d4750
* Version Independent ID: 29e89cc6-c8ca-7d29-7dca-4ac4d06f5c42
* Content: [Apps to Teams meetings - Teams](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/teams-apps-in-meetings?branch=add-apps-in-meetings)
* Content Source: [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Nikitha-MSFT** [comment]
We don't see mistake at the bottom of the article. Could you please point us to exact docs?

**Comment by Wajeed-msft** [comment]
Thanks for reporting. [Public docs](https://docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/teams-apps-in-meetings) are already updated.
