### ISSUE TITLE
Documentation does not mention access token is needed.

### ISSUE THREAD

**Issue by mledom** [MicrosoftDocs/msteams-docs#2167]
The documentation does not mention that the access token must be passed in order to test the permitted grants. It also does not mention what level of permission is required. Without using the token the user receives "Access token is empty." When using the token and only the "Channel.Create.Group" RSC the user receives "Insufficient privileges to complete the operation." What is the minimum required permission to use the /permissionGrants endpoint?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11c68c28-b6d6-ef7e-f8f9-ebebe487378b
* Version Independent ID: c5985867-3795-4280-ef0d-1d66ee30da6e
* Content: [Resource-specific consent in Teams - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/graph-api/rsc/resource-specific-consent)
* Content Source: [msteams-platform/graph-api/rsc/resource-specific-consent.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/graph-api/rsc/resource-specific-consent.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Manish-MSFT** [comment]
@laujan , @nkramer : please provide your suggestions.

**Comment by Wajeed-msft** [comment]
@mledom - Access token is indeed required for calling Graph API. Please take a look at [Obtain an access token from the Microsoft identity platform](https://docs.microsoft.com/en-us/microsoftteams/platform/graph-api/rsc/resource-specific-consent#obtain-an-access-token-from-the-microsoft-identity-platform) documentation section. Follow the step to [Get a token](https://docs.microsoft.com/en-us/graph/auth-v2-service#4-get-an-access-token).

If you are still facing the issue, please share the request/response for your Graph API call.
