### ISSUE TITLE
Check if user is "Company Administrator" status through bot api

### ISSUE THREAD

**Issue by liangchr** [MicrosoftDocs/msteams-docs#2178]
Can I check if user is "Company Administrator" status through bot api? 

Through the typical payload (e.g @mention bot or composeExtension/invoke) there a way to determine through the message if the user mentioning/invoking a bot is a Company administrator?  

I know this can be done through the GRAPH API using 
POST /users/{id}/checkMemberObjects (id: "62e90394-69f5-4237-9190-012177145e10"}

But is there a BOT API that can return this information? I need to know if a user is a company admin and have the bot respond differently depending on that information. 

Appreciate the help!

**Comment by Trinetra-MSFT** [comment]
@liangchr , Bot context doesn't return the information about the roles ["owners'], You can get the user ID from context and call the memberObject graph API to get the role of user who @mention bot

**Comment by liangchr** [comment]
@Trinetra-MSFT super appreciate the clarification thanks!

**Comment by v-chetsh** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.
