### ISSUE TITLE
Selection of a emoji in chat and pressing enter crashes app on Win10

### ISSUE THREAD

**Issue by sebastianhoppemsg** [MicrosoftDocs/msteams-docs#218]
If you write a emoji in a chat window on win10 app an select the emoji by selecting "all" and press enter, the app crashes

Teams Version 1.1.00.19257 (64-Bit)

**Comment by arun-msft** [comment]
@sebastianhoppemsg: Let us know where you are trying this one and please share us the screen shot which you are getting error while sending emoji.

**Comment by billbliss** [comment]
No response from @sebastianhoppemsg - please re-open if you have repro details.
