### ISSUE TITLE
Action commands doc is missing documentation of the justInTimeInstall option

### ISSUE THREAD

**Issue by aosolis** [MicrosoftDocs/msteams-docs#2187]
https://docs.microsoft.com/en-us/microsoftteams/platform/resources/messaging-extension-v3/create-extensions?tabs=typescript#request-to-install-your-conversational-bot

This is in the v3 docs, but not the current docs. Frustrating for devs, who don't know about both options unless they know where to look.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fb0c2d8-f880-c260-d0be-6b9467e47f8c
* Version Independent ID: 7820ffc9-5260-c818-f5fb-672801a67d00
* Content: [Respond to the task module submit action - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/action-commands/respond-to-task-module-submit?tabs=dotnet%2Cdotnet-1)
* Content Source: [msteams-platform/messaging-extensions/how-to/action-commands/respond-to-task-module-submit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/messaging-extensions/how-to/action-commands/respond-to-task-module-submit.md)
* Product: **msteams**
* GitHub Login: @clearab
* Microsoft Alias: **anclear**

**Comment by Wajeed-msft** [comment]
This is now covered in [Request to install your conversational bot](https://docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/action-commands/create-task-module?tabs=dotnet#request-to-install-your-conversational-bot) section.

**Comment by Rajeshwari-v** [comment]
Closing the issue with the confirmation from @Wajeed-msft , as the required information has been added in "create a task module" page through PR#2664 and is available now.
