### ISSUE TITLE
Localization of Teams tabs is not changing after the first installation of the app

### ISSUE THREAD

**Issue by plamber** [MicrosoftDocs/msteams-docs#2188]
Hello,
we followed the localization concepts explained on this page. We are localizing a teams app with personal tabs in multiple languages.

We noticed that the localization of the tab title is applied during installation of the app. However, if the language is changing the language in the operating system or Teams app, the title of the tab is not using the correct locale. 

We are wondering if this is by design.

It would be beneficial to have a section explaining such types of limitations or how to fix scenarios. For enterprises using setup policies, it would be good to know how localization is applied when a setup policy is applied in a tenant.

Thank you for the feedback,
Patrick

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f55e52a-5fc4-7fcb-0e1e-946bff5aaee4
* Version Independent ID: b6c559fb-8512-575b-4fed-ebe1457e890e
* Content: [Localization for Team apps - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/apps-localization)
* Content Source: [msteams-platform/concepts/build-and-test/apps-localization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/build-and-test/apps-localization.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Trinetra-MSFT** [comment]
@plamber, Localization for teams app is defined in manifest, it reads the json file and applies to the teams app at the time of installation just wanted to confirm, were you able to see your tab in the same locale while adding to channel? Does your app have other locale which you are trying to set with Teams language or OS?

**Comment by plamber** [comment]
Hi @Trinetra-MSFT,
thank you for the feedback. We can see the same locale while adding to the channel. This is working fine and as expected.

However, we received multiple times feedback form customers complaining why the tabs are not changing the locale when the language context in Teams changes. 

There are some users that change the language context in Teams on the fly. You can do this for example in the language settings in Teams. The application translates to the new language. The contents of the tab are translating to the new language if handled by the application hosted behind but the tab does not reflect the definition in the app manifest.

In these situations customers think that the application does not work properly.

The expected behavior is that the tabs are considering the app manifest settings on the fly. I would expect this at least with the personal tabs.

We also thought about alternatives to "fix this problem". We were thinking of using a tab only with a generic term in the title and build our own navigation below. This, however, does not feel like a Teams application.

Please let me know if you need more context.

Thank you,
Patrick

**Comment by plamber** [comment]
Hi @Trinetra-MSFT,
not sure if this is just a coincidence but we tested this today and it works now as expected.

Do you know if some changes have been released recently to fix this problem?

Thank you again,
Patrick
