### ISSUE TITLE
No Bots tab

### ISSUE THREAD

**Issue by HaroldPutman** [MicrosoftDocs/msteams-docs#219]
Not sure if documentation is out of date or my company's setup is different. My team has an Apps tab but no Bots tab. There is a link on the Apps tab to *Create an outgoing webhook*. I provided name and URL but @mentioning the name did not post to the URL. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06c224ae-1484-408c-d17a-e7e1ba07e78a
* Version Independent ID: fac8ff1e-a127-c12a-5304-9de39b1a15c6
* Content: [Outgoing webhooks - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/outgoingwebhook)
* Content Source: [msteams-platform/concepts/outgoingwebhook.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/outgoingwebhook.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by billbliss** [comment]
Bots are a capability of an app. You list your bot ID in the app's manifest - there's more information [here](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/apps/apps-package).

Regarding the outgoing webhook - can you POST to the URL  from POSTMAN or curl? What was the format of the JSON you were posting?

**Comment by HaroldPutman** [comment]
Thanks @billbliss. My documentation issue is that in [msteams-docs/msteams-platform/concepts/outgoingwebhook.md](msteams-docs/msteams-platform/concepts/outgoingwebhook.md) it says "To create an outgoing webhook, click Manage team and then navigate to the Bots tab." But in my company's instance there is no "Bots" tab. Instead there is a link to create an outgoing web hook  on the Apps tab. Is that just us or is the doc out of date.

My application issue is that when I create a web hook using the link on the apps tab, no "bot user" gets added to the team, and I am unable to send any message to the webhook URL. (If I name the outgoing webhook `robot`, mentioning `@robot` in chat does nothing).  Yes the webhook URL is valid and accepts posts from curl or postman.

**Comment by billbliss** [comment]
That's a doc bug, we'll fix it. We changed the name but missed this one. 

I'll verify Webhook are working when I get into the office.

**Comment by billbliss** [comment]
Ok checked it. My test worked so it's not the outgoing webhooks core which is a relief.

Outgoing webooks show up in the list of apps, not in the list of users.

On the apps page, do you see "Upload a custom app" next to "create outgoing webhook"? If not, that's the bug. I'll elaborate once I get your answer.

**Comment by billbliss** [comment]
I'm pretty certain that on the Apps tab for the team settings, you just see "Create an outgoing webhook" and "Upload a custom app" is not. 

If so, that's a bug - I just verified it. Your tenant has turned off sideloading of apps - see step 6 [here](https://docs.microsoft.com/en-us/microsoftteams/platform/get-started/get-started-tenant#turn-on-microsoft-teams-for-your-organization) and the image above it.

If sideloading is turned off, outgoing webhooks do not work. But we shouldn't allow you to create something that doesn't work (I'll file that as a bug), and we don't document this on the outgoing webhooks page. We'll fix that.

**Comment by billbliss** [comment]
[Page](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/outgoingwebhook) has been updated and information clarified.

**Comment by HaroldPutman** [comment]
Thanks for your investigation into this and for the updates to the docs!

We only see "create an outgoing webhook" on our Apps Tab which I guess means that sideloading is turned off.  This is an unfortunate dependency since our IT department is reluctant to allow "Upload a  custom app". But at least now I know what to ask them for.

**Comment by billbliss** [comment]
Later this year we will be adding sideloading policies that will allow sideloading on a per-user basis as opposed to global on/off.
