### ISSUE TITLE
[/beta/me/chats?$expand=members] is not returning external user details

### ISSUE THREAD

**Issue by shivaprasadmanupadi** [MicrosoftDocs/msteams-docs#2190]
Any user with valid Microsoft domain email can be added to a group chat using deep linking even if that user doesn't belong to my domain.

Example:
https://teams.microsoft.com/l/chat/0/0?users=user1@mydomain.com,user2@mydomain.com,user3@externaldomain.com&topicName=hello

user1 = user1@mydomain.com
user2 = user2@mydomain.com
user3 = user3@externaldomain.com

Chat will be initiated even user3 is not part of my domain.

But when i get my chat conversation details using this REST API:
/beta/me/chats?$expand=members

in response JSON , we have userId of user3, but email and displayName are null.

**Comment by Manish-MSFT** [comment]
@shivaprasadmanupadi, Yes that's the default behavior since the user is guest and is administrated by other external tenant. You can't get external user data using a graph call within your tenant.

**Comment by Trinetra-MSFT** [comment]
Please feel free to reopen if you have further query on this
