### ISSUE TITLE
Hyperlink open with different tab.

### ISSUE THREAD

**Issue by rvinothrajendran** [MicrosoftDocs/msteams-docs#2197]
**Steps** 

1.	Goto the Topic: [Teams-bot-logic ](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-basics-teams?view=azure-bot-service-4.0&tabs=python#teams-bot-logic)
2.	select the tab: Python 
3.	Click the channel created (Description section)
4.	Open new page with C# tab.

**Expected behaviour**
New page open with **Python** tab

**Comment by Trinetra-MSFT** [comment]
@rvinothrajendran , This is the doc behavior for all hyperlinks But you are right it should go to respected language Tab from where it is clicked user is trying to reach, @laujan could you please help to redirect code snippet description hyperlinks to their actual language code snippet tab.
