### ISSUE TITLE
Sample for messaging extensions search authentication config is not work well on new teams version.

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#2199]
Cross posting question on Teams Repo from https://github.com/microsoft/BotBuilder-Samples/issues/2836 originally posted by @yetsmarch

hello, I create a message extension app as sample 52, I opened the message extension and select a herocard, the card never send out to the cannel. it seems that the dialog close soon before getting the search result.
my teams version is 1.3.00.28622, will you have a test

[Sample code link](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/52.teams-messaging-extensions-search-auth-config).
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4f3b627-c87b-6a19-9c26-7170a99f38ee
* Version Independent ID: a9546115-7c5d-39c9-ca8a-3cf3e02ff621
* Content: [Respond to search command - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/search-commands/respond-to-search?tabs=dotnet)
* Content Source: [msteams-platform/messaging-extensions/how-to/search-commands/respond-to-search.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/messaging-extensions/how-to/search-commands/respond-to-search.md)
* Product: **msteams**
* GitHub Login: @clearab
* Microsoft Alias: **anclear**

**Comment by Nikitha-MSFT** [comment]
This is a know bug and we are tracking it internally.

Internal Bug Tracker: [1218441](https://domoreexp.visualstudio.com/MSTeams/_workitems/edit/1218441)

**Comment by Prasad-MSFT** [comment]
Hi @weny-tang - Are you still facing this issue? We have tested this sample and it works fine at our end.
https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/msgext-search-auth-config/csharp

**Comment by Prasad-MSFT** [comment]
We are closing this issue for now. Please feel free to reopen if required. Thanks!
