### ISSUE TITLE
You missing step 3 in Match theme style

### ISSUE THREAD

**Issue by dsmeltz** [MicrosoftDocs/msteams-docs#2200]
The **Match theme styles** section has a snippet of JavaScript that is supposedly used to change the theme of a Tab.   The text above that snippet, calls out three steps.  The third step is not shown nor explained any further.  It simply states 
_3) applying the CSS to your tab content's root HTML element (&lt;div&gt;)_
which isn't shown how to do.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29e90229-289e-2035-3b42-5cb9cce14efe
* Version Independent ID: a2aee4b8-93b9-bda7-f000-8f41b4513647
* Content: [Get started - Build a personal tab - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/build-your-first-app/build-personal-tab)
* Content Source: [msteams-platform/build-your-first-app/build-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/build-your-first-app/build-personal-tab.md)
* Product: **msteams**
* GitHub Login: @heath-hamilton
* Microsoft Alias: **lajanuar**

**Comment by RamaMohanaChary** [comment]
@dsmeltz:
Could you please try by keeping breakpoint in "microsoftteams.registeronthemechangehandler" method to verify whether it is calling or not. If not please try with this "microsoftTeams.getContext" method.
For third step, it will directly apply the styles.

**Comment by Sw1ma** [comment]
You could take a look at #2125 (which in my opinion is the same issue) where you can find a solution. Or jump right into the documentation at [Microsoft Learn](https://docs.microsoft.com/en-us/learn/modules/embedded-web-experiences/3-exercise-create-custom-teams-personal-tab) with a fully working exercise.

**Comment by Wajeed-msft** [comment]
Closing this issue, please reopen if you are still blocked on this.
