### ISSUE TITLE
Deep link scheduling dialog don't support special char on Subject

### ISSUE THREAD

**Issue by rjsh1910** [MicrosoftDocs/msteams-docs#2203]
I am trying to integrate deep link schedule meeting dialog functionality (https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links#generating-a-deep-link-to-the-scheduling-dialog)  and observed below issues-
1) Deep link Subject don't support special char like &, # etc. we need to do encodeURIComponent for each query string parameter. Complete url encode don't works.
2) Deep link body don't allow formatting text as bold etc. or allow to create href links

Please review and fix this issues or let me know If I am missing any thing.

sample example for issue: 

https://teams.microsoft.com/l/meeting/new?subject=Test Subject & Remaining Text&amp;attendees=a@gmail.com,b@gmail.com&amp;content=<b>Bold body</b>

**Comment by Trinetra-MSFT** [comment]
@rjsh1910 , We have filed a Bug for this, We will let you know once it is resolved

**Comment by Nikitha-MSFT** [comment]
we do support special characters like & in the subject. the url has to be url encoded, Please check the below example for the reference. This is by design

ex; https://teams.microsoft.com/l/meeting/new?subject=my%26subject works.

**Comment by rjsh1910** [comment]
ok and what about second point -
Deep link body don't allow formatting text as bold etc. or allow to create href links

**Comment by vitaliishandra** [comment]
@rjsh1910  I am also interested in it. Created the ticket: https://github.com/MicrosoftDocs/msteams-docs/issues/2335

**Comment by Nikitha-MSFT** [comment]
@rjsh1910 we only support plain text for meeting content. This is by design.

**Comment by rjsh1910** [comment]
In body text content can we provide line break? If yes then how?

**Comment by v-chetsh** [comment]
@rjsh1910 - Could you please confirm if your issue has resolved or still looking for any help?
