### ISSUE TITLE
Adaptive Card Outgoing Webhook Support

### ISSUE THREAD

**Issue by Macman1234** [MicrosoftDocs/msteams-docs#2206]
The article talks about adaptive cards as not being supported in Connectors, and being supported in incoming webhooks. It would be good if it clarified whether they were supported in outgoing webhooks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adcfd49d-0d36-b19a-2857-395289f1c6c2
* Version Independent ID: 464b2cd8-0cd7-dd52-aef6-47e040c89c8d
* Content: [Introducing cards - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/what-are-cards)
* Content Source: [msteams-platform/task-modules-and-cards/what-are-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/what-are-cards.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Abhijit-MSFT** [comment]
Currently adaptive cards in webhooks is in public developer preview program.
