### ISSUE TITLE
Sideloaded app not rloading on code change

### ISSUE THREAD

**Issue by ceessay** [MicrosoftDocs/msteams-docs#2210]
I am following the tutorial and made changes mentioned in section 2. Customize your tab content page, but my changes are not reflected on my teams tab. Should I re-upload the the app on teams. Is there any livereload or hotreload solution ?

**Comment by RamaMohanaChary** [comment]
@ceessay :
Could you please check your manifest whether your changes are reflected or not, if not please uninstall and install your application.
There is no option of auto reload.
Could you please have a look on [reference](https://docs.microsoft.com/en-us/microsoftteams/platform/tutorials/get-started-dotnet-app-studio) document.

**Comment by Trinetra-MSFT** [comment]
marking as InActive user
