### ISSUE TITLE
Not full screen

### ISSUE THREAD

**Issue by whippingdot** [MicrosoftDocs/msteams-docs#2214]
When you press almost anything in the tab that is opened when a new meeting is joined, on Windows, the icon top right next to the X, which closes the tab, changes and becomes the restored down version. It is not actually restored down but the icon shows it like that. If you press the button again the icon stays the same, but it actually gets restored down. I hope you can fix this as I usually fall for the trick thinking it is not full. 

I don't know if this shows anything but here is a picture:
![image](https://user-images.githubusercontent.com/64354499/96540682-f0055e00-12bb-11eb-897c-eb00ac9bbe59.png)

**Comment by Trinetra-MSFT** [comment]
@whippingdot , Could you please provide more context on this issue, which icon you are talking about? I just did a quick test for Full screen meeting , I was able to see the icon as it is, It would be good if you can provide the repro steps and also how many members joined in a meeting? 
![image](https://user-images.githubusercontent.com/50989436/96671720-21476200-1380-11eb-9c9c-e540448d7f48.png)

**Comment by whippingdot** [comment]
There were 14 participants at that time, and I was talking about the maximize icon. Maybe it is only a bug for me but whenever something opens from the right side, like participants or device settings, the maximize icon changes to the minimize icon. Meaning it changes from the two tabs pic on the top to the one tab pic:
![image](https://user-images.githubusercontent.com/64354499/96672064-00334100-1381-11eb-9e74-0efe3e649d2d.png)
to:
![image](https://user-images.githubusercontent.com/64354499/96672097-180ac500-1381-11eb-82b5-638903453779.png)

**Comment by Trinetra-MSFT** [comment]
@whippingdot , We can't repro this at our end, Could you please specify your device and which teams version you are running?

**Comment by whippingdot** [comment]
I am running version 1.3.00.26064 (64-bit) on a dell PC run by Windows 10. I don't know what type of Dell PC this is, but I will get back to you. Thank you btw

**Comment by Trinetra-MSFT** [comment]
@whippingdot I'm running teams desktop client on windows 10 HP device with version 1.3.00.29017 (64-bit)-E.  Still I can't repro this issue Can you just check it once on Teams browser as well if you can repro this I will file a Bug for this

**Comment by whippingdot** [comment]
This happens during the new tab settings. In the browser I am pretty sure a new tab does not open.

**Comment by Trinetra-MSFT** [comment]
@whippingdot , When you join a teams meeting in browser it takes the browser maximize/minimize option. it can be issue with your browser setting you can try to sign out/sign in from teams and setup a new meeting and check if you can see this issue with teams in browser as well. if that doesn't help you out please update your teams version to latest

**Comment by Trinetra-MSFT** [comment]
Please feel free to reopen if you have further query
