### ISSUE TITLE
Chat tab goes missing after deep link to custom tab. Notifications then fail to open chat.

### ISSUE THREAD

**Issue by blh83** [MicrosoftDocs/msteams-docs#2217]
When clicking a deep link (in a custom chatbot) it opens a custom tab. After the custom tab opens, the chat option along the top disappears and is moved into the chat bot description. This leaves only the "Files", my custom tab, and the "About" tabs at the top. 

If a desktop notification then comes through, clicking on that notification opens the "Files" tab instead of the Chat.

As part of debugging, I noticed in the desktop app a user can choose the chat option from the chatbot's description and the tab will show back up. In the web app, simply refreshing the page will cause the chat tab to appear again. It is only on the initial click of a deep link to a custom tab that it disappears and is moved to the bot description.

**Comment by blh83** [comment]
Just checking if there has been any insight into this issue. Thanks.

**Comment by Abhijit-MSFT** [comment]
This is known issue. Currently team is working on fixing it. Should be available soon.

**Comment by blh83** [comment]
This is working for me now, so I will close this bug. Thank you.
