### ISSUE TITLE
iOS app crashes when receiving incoming calls

### ISSUE THREAD

**Issue by GabrielSandor** [MicrosoftDocs/msteams-docs#2220]
Hello,

I noticed that shortly after updating my iPhone 8 to iOS 14 the Teams mobile app can no longer receive incoming calls. If my phone is locked, i get no notification at all when i'm called. If the phone is unlocked with the Teams app in the foreground, the app freezes for a few seconds and then shuts down. Can you please help me figure out what is happening?

**Comment by v-chetsh** [comment]
@GabrielSandor - Could you please confirm if your issue has resolved or still looking for any help?

**Comment by GabrielSandor** [comment]
Hello @v-chetsh,

I have no longer noticed this issue lately, looks like it's been fixed.

**Comment by v-chetsh** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.
