### ISSUE TITLE
To include the Tab design best practices

### ISSUE THREAD

**Issue by prkosh** [MicrosoftDocs/msteams-docs#2222]
[Enter feedback here]
Personal/Static tabs should provide an affordance to share content from a personal app experience with other team members
Personal/Static tabs may aggregate content from team or group chat scoped instances of that app in a single view 
Link targets in tabs should not link to an external browser but should link to div elements contained within Teams e.g. inside 
Task Modules, tabs, etc
Tabs should be responsive to Teams' themes i.e. when the Teams theme is changed, the theme within the app should also change to reflect that theme
Tabs should where possible use Teams styled components i.e. adopting Teams fonts, type ramps, colour palettes, grid system, motion, tone of voice, etc.
Tabs should where possible use Teams interaction behaviours i.e. in page navigation, position and use of dialogs, information hierarchies, etc.
Tabs should use the standard Teams hamburger menu and/or breadcrumb for in-app navigation
Tabs should not provide an app bar with icons in the left rail that conflicts with the main Teams navigation
Tabs should not have more than 3 levels of navigation within the app
Secondary and tertiary pages in a tab should be opened in an L2/L3 view in the main tab area that is navigated via the breadcrumb
Tabs that have complex editing capabilities within the app should open the editor view in multi-window rather than a tab (for desktop and web)
--

-

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3dd35a9c-c868-a7b9-825a-4be9419539d7
* Version Independent ID: 814c8be1-eae8-7316-8553-283ef07ffc09
* Content: [Design guidelines for tabs - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/design/tabs#best-practices)
* Content Source: [msteams-platform/tabs/design/tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tabs/design/tabs.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Trinetra-MSFT** [comment]
@prkosh , We have forwarded your tab design feedback to Tabs channel for consideration.

**Comment by Mahesh2516** [comment]
Resolved
