### ISSUE TITLE
Bot design guidelines to be included

### ISSUE THREAD

**Issue by prkosh** [MicrosoftDocs/msteams-docs#2223]
[Enter feedback here]
Bot should provide relevant notifications when there has been activity
Bots must not push sensitive data to a Team, a group chat or a 1:1 conversation where there is an audience who should not be able to view that data
Bot notifications should include meaningful information to inform a user on the relevance of the notification
Bots should use the Teams tone of voice as defined in the guidelines
Bots should provide an FRE welcome message that highlights the value of the bot and what its primary functions are, this might be in the form of a "take a tour" interactive tutorial with carousel cards or "try it" buttons
Bot text must not have any spelling mistakes or grammatical errors.
Bot must provide a set of predefined bot commands that are actionable.
Bot messages should be easy to understand and actionable.

Bots must provide fallback help commands when a message is not understood.
Forms embedded in cards sent by a bot should provide deterministic form inputs that do not require sequential updating as this requires card validation and refresh with any validation errors
Bot notifications should be scoped to a Team, a group chat or a 1:1 conversation with relevant content for that audience

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87d66f12-3a20-8d6a-ed4c-90bc26f90591
* Version Independent ID: 3725c141-86f1-b815-6568-16758d948fac
* Content: [Design guidelines for bots - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/design/bots)
* Content Source: [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/bots/design/bots.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by heath-hamilton** [comment]
@prkosh this work is being tracked (cc: @laujan).

**Comment by Mahesh2516** [comment]
Resolved
