### ISSUE TITLE
Native wayland support with newest electron

### ISSUE THREAD

**Issue by nxadm** [MicrosoftDocs/msteams-docs#2229]
Sharing the desktop works well with the latest released  MS Teams Linux build (1.3.00.25560) when using Xorg. However, Linux desktops are moving to Wayland (e.g. the default in Fedora). When running MS Teams in Wayland desktop sharing is not available.

This functionality is handled by electron and [they recently added Wayland support](https://github.com/electron/electron/pull/26022). Your colleagues at VS Code [acknowledged this and scheduled to update electron when available](https://github.com/microsoft/vscode/issues/109176).

I wonder if this could be added to your roadmap as well. It will be a huge improvement for Linux users.

Upstream issue: electron/electron#10915

**Comment by RamaMohanaChary** [comment]
@nxadm:

Could you please reach out to [Product Support Channel](https://docs.microsoft.com/en-us/microsoftteams/platform/feedback#product-support-channels).

**Comment by nxadm** [comment]
@RamaMohanaChary I'll pass it on to our 365 admins so they can open a request.

**Comment by nxadm** [comment]
Microsoft 365 Case #:22554594
