### ISSUE TITLE
Import messages to a Team/Channel in migration mode fails with bad request and no other information

### ISSUE THREAD

**Issue by matt-wright** [MicrosoftDocs/msteams-docs#2230]
Hello, I am using postman with a valid access token to POST to a team/channel in migration mode.  The POST body is a copy of the page example using my valid tenant email id as the user id:
{
   "createdDateTime":"2020-10-04T19:58:15.911Z",
   "from":{
      "user":{
         "id":"<valid email id>",
         "displayName":"<display name>",
         "userIdentityType":"aadUser"
      }
   },
   "body":{
      "contentType":"html",
      "content":"Hello World"
   }
}

The response I get is:
{
    "error": {
        "code": "BadRequest",
        "message": "Bad Request",
        "innerError": {
            "date": "2020-10-28T22:05:59",
            "request-id": "efd02ed5-1c33-45ae-a53f-17e1d2cce3df",
            "client-request-id": "efd02ed5-1c33-45ae-a53f-17e1d2cce3df"
        }
    }
}
Any ideas here?

**Comment by VaraPrasad-MSFT** [comment]
@matt-wright , Could you please help us to understand the problem you are facing ?

**Comment by matt-wright** [comment]
hello, I have successfully created a team/channel in migration mode but yet when attempting to add an actual message as per the above returned json, I only get a BadRequest. Is there a way to query the request id to retrieve more details as to the exact problem with the bad request?  Excepting for the createdDateTime edited to ensure it is later than the back in time team/channel timestamp.  I am only using my valid aaduser id as my corp email.  If I change to an invalid email, I get a response to that affect that the user doesn't exist in our Teams AD instance.  So what is the problem is that it mentions bad request but I have no further information as to why that is the case.

**Comment by matt-wright** [comment]
I'd like to know why I am getting a BadRequest please?

**Comment by matt-wright** [comment]
Not much help here, why is that?  So it turns out, while the id field will indeed accept a userPrincipalName value and, complain if it isn't a valid aaduser, it will throw the BadRequest error when an attempt to POST a new message to the channel is performed.  The id value uses MUST be the user's actual retrieved id value of their AAD record using the https://graph.microsoft.com/v1.0/users/<userPrincipalName> call.
