### ISSUE TITLE
Further explicitness about webhook limitations

### ISSUE THREAD

**Issue by westyside** [MicrosoftDocs/msteams-docs#2235]
Would it be appropriate to be more explicit about webhook limitations. The intro describes the use of cards as a reply, but do all those features of cards work?

I mention this as a follow up to discovering messageBack (Card)Action functionality for Hero and Adaptive cards do not appear to work. [Ref question](https://stackoverflow.com/q/64513286/310809)

The trail of documentation can lead to the wrong conclusion.

Also, thank you, the documentation is generally pretty solid!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb9c5bd5-1ac6-dcc8-4ed6-d6aad2432776
* Version Independent ID: 43e90995-bba4-86b6-1f1c-ab749e546a4b
* Content: [Add custom bots to Microsoft Teams with outgoing webhooks - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-outgoing-webhook)
* Content Source: [msteams-platform/webhooks-and-connectors/how-to/add-outgoing-webhook.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/webhooks-and-connectors/how-to/add-outgoing-webhook.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Mahesh2516** [comment]
Closed through PR 2691.
