### ISSUE TITLE
connector.Conversations.CreateConversationAsync(conversationParams)

### ISSUE THREAD

**Issue by ShakeySnake** [MicrosoftDocs/msteams-docs#224]
This object is ambiguous in this document and should be cited. It's not clear how you create this object for starting a new conversation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba8d3979-14f5-3105-ad89-ce6f98d11df1
* Version Independent ID: e53a7d1e-0e70-ca30-9809-fda7ebe5f4da
* Content: [Proactive messages - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/bots/bot-conversations/bots-conv-proactive)
* Content Source: [msteams-platform/concepts/bots/bot-conversations/bots-conv-proactive.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/bots/bot-conversations/bots-conv-proactive.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by billbliss** [comment]
You are correct - updated with more of the sample that snippet came from as well as a reference. Sorry for the confusion.

@NormSohl will pick up the next time you push master to live.

In the meantime you can see the full source here: https://github.com/OfficeDev/microsoft-teams-sample-complete-csharp/blob/32c39268d60078ef54f21fb3c6f42d122b97da22/template-bot-master-csharp/src/dialogs/examples/teams/ProactiveMsgTo1to1Dialog.cs

**Comment by markolb81** [comment]
Thanks for your reply. The actual challenge in my use case is that there is no conversation before, so the user does not even know that the bot exists. Furthermore, there is no channel or team to live in. Teams will "just" be used as a simple 1:1 instant messaging tool.
However, I understood now that ChannelAccounts for MS Teams don't work with emails / UPNs, but with channel-specific ID's - even in a 1:1 conversation. This simply makes my use case technically impossible.
