### ISSUE TITLE
index.html, start-login.html, end-login-html, should be in the same domain, so we should remove validate domains configuration

### ISSUE THREAD

**Issue by SLdragon** [MicrosoftDocs/msteams-docs#2243]
Please look at this issue,
https://github.com/OfficeDev/microsoft-teams-library-js/issues/431

This issue mentioned that (index.html, start-login.html, end-login-html) these pages should be in the same domain, but this docs mentioned that we can use validate domains to assign different domain for these pages, which is confusing. I think we should remove validate domains configuration

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d5b8b0f-3da3-8642-6edf-dc6608a830cf
* Version Independent ID: f93cdabd-f6ab-29d0-f3c9-78deb21ca521
* Content: [Authentication flow for tabs - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-flow-tab)
* Content Source: [msteams-platform/tabs/how-to/authentication/auth-flow-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tabs/how-to/authentication/auth-flow-tab.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by RamaMohanaChary** [comment]
@SLdragon:

If we want to authenticate all the three pages in a tab then it should be in one single domain.
And, if we want to use one of the page in other tab then it should be in another domain
Then, these two domains should be placed in Validate Domains.

**Comment by SLdragon** [comment]
Thank you, just sync with Teams SDK team, the login page must in the same domain, and other pages do not have this limitation:

> The authentication pages must be in same domain and let's say you have other tab which corresponds to other domain can be added in manifest. So, overall different domains can be added in manifest but for authentication purpose all pages (index,start,end) must use same domain.  it's like if you have total 5 pages out of which 3 are auth pages and 2 are pages of different domain , so you can mention two valid domains in manifest for it to work.

**Comment by SLdragon** [comment]
I think we can update the docs to clarify this, thank you!
