### ISSUE TITLE
Missing Folders and Manifest

### ISSUE THREAD

**Issue by jeremygill** [MicrosoftDocs/msteams-docs#2245]
Hey guys, 

Ive tried following the steps however despite completing all the prerequisite steps when the framework is generated for the teams app there is no publish and therefore no manifest file so I can proceed any further.

Cheers, 

Jeremy

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f876156-cc1e-468f-4647-5143a5de03b1
* Version Independent ID: 618f43a3-3371-ad99-13aa-087b9303298c
* Content: [Get started - Build and run your first app - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/build-your-first-app/build-and-run)
* Content Source: [msteams-platform/build-your-first-app/build-and-run.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/build-your-first-app/build-and-run.md)
* Product: **msteams**
* GitHub Login: @heath-hamilton
* Microsoft Alias: **lajanuar**

**Comment by VaraPrasad-MSFT** [comment]
@jeremygill , you need to create a folder for Manifest and crate a manifest.json , here is the [sample manifest](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema) file for your reference.

**Comment by alexandresg** [comment]
@VaraPrasad-MSFT i do not think so... I am having the same issue he described:
![image](https://user-images.githubusercontent.com/1486974/97466588-2f2a5380-193b-11eb-8ade-09b15960a541.png)

**Comment by VillePellosniemi** [comment]
![image](https://user-images.githubusercontent.com/34025719/97556255-e4afe200-19e1-11eb-8369-64ceda44888f.png)
I have the same issue

**Comment by shahmharsh** [comment]
Having the same issue, were you able to create the manifest.json file?

**Comment by shahmharsh** [comment]
Seems like this broke in toolkit v1.1.0. I downgraded to v1.0.6 and the `.publish` folder is created.

**Comment by Hashiphoto** [comment]
The Microsoft Teams Toolkit extension's changelog says:

> -  Deprecation of .publish folder - all updates you do through App Studio tooling
> - Pre 1.1.0 project upgrade to new project format. We detect if they don't have a teamsAppId in the project...and if they have a .publish folder we create an app registration for them and update the project.

Please update the documentation step 4 with the new process for pointing our app at localhost.

**Comment by VaraPrasad-MSFT** [comment]
@alexandresg 
Really sorry our documentation update didn't make it out at the same time as the version update. we are working on getting that approved ASAP. It should be out today/tomorrow. Sorry about the inconvenience.

In the meantime though the .publish folder is deprecated. Once you create a new project in the toolkit all you need to do is hit F5/run and it will launch Chrome and install your package. The package is stored in App Studio and we just use its id to install it.

**Comment by heath-hamilton** [comment]
Closing this issue--docs were updated in PR https://github.com/MicrosoftDocs/msteams-docs/pull/2285.
