### ISSUE TITLE
Error: "Received error from connectors" - Unable to save connector configuration

### ISSUE THREAD

**Issue by marekmierzwa** [MicrosoftDocs/msteams-docs#2247]
I spent a lot of time trying to fix it but without any luck. Im creating custom connector following tutorial https://docs.microsoft.com/en-us/learn/modules/msteams-webhooks-connectors/7-exercise-o365-connectors
When I add connector to the channel, after clicking "save" on configuration page I get error:

"Unable to save "My connector" connector configuration. Please try again."

In console I see number of issues:
```
2020-10-28T14:20:46.829Z AppsService: getInstalledAppForTeam - Invalid teamId and/or appId specified
2020-10-28T14:21:04.123Z ngClickDecorator: value not found in enum type. value: 
2020-10-28T14:21:04.126Z ngClickDecorator: value not found in enum type. value: 
2020-10-28T14:21:04.126Z ngClickDecorator: value not found in enum type. value: 
2020-10-28T14:21:04.126Z ngClickDecorator: value not found in enum type. value: 
2020-10-28T14:21:04.126Z ngClickDecorator: value not found in enum type. value: 
2020-10-28T14:21:04.126Z ngClickDecorator: value not found in enum type. value: 
2020-10-28T14:21:04.126Z ngClickDecorator: value not found in enum type. value: 
2020-10-28T14:21:04.530Z Received error from connectors {"seq":1603787831895,"timestamp":1603894864519,"flightSettings":{"Name":"ConnectorFrontEndSettings","AriaSDKToken":"d127f72a3abd41c9b9dd94faca947689-d58285e6-3a68-4cab-a458-37b9d9761d35-7033","SPAEnabled":true,"ClassificationFilterEnabled":true,"ClientRoutingEnabled":true,"EnableYammerGroupOption":true,"EnableFadeMessage":false,"EnableDomainBasedOwaConnectorList":false,"EnableDomainBasedTeamsConnectorList":false,"DevPortalSPAEnabled":true,"ShowHomeNavigationButtonOnConfigurationPage":false,"DisableConnectToO365InlineDeleteFeedbackPage":true},"status":500,"clientType":"SkypeSpaces","connectorType":"12ce20e2-ce91-4d5a-8cb0-9f7946c01709","name":"handleMessageError"}
```
Webhook url is created though, and passed to web service. But when I try to send request to that url I get 410

I found topics describing same or similar issue: https://github.com/MicrosoftDocs/msteams-docs/issues/568 https://github.com/MicrosoftDocs/msteams-docs/issues/1738 but they don't give clear answer how to solve it, or what is the cause of it. I tried to remove and recreate connector, or to recreate everything for the scratch from App Studio, none of this worked for me.

**Comment by Trinetra-MSFT** [comment]
@marekmierzwa , Could you please check the connector configuration URL in [connector developer dashboard](https://outlook.office.com/connectors/home/login/#/publish)? Could you please also confirm if you have added your `content URL` to validDomain[] array & `setSetting()` is getting called before `setValidityState()`?

**Comment by marekmierzwa** [comment]
@Trinetra-MSFT Thanks for answer. `content_url` domain is added to `validDomains` in both manifest and Connectors Developer Dashboard, also `configurationUrl` from manifest matches the one from Connectors Dashboard. I updated script on configuration page so  `setValidityState` is called after `setSettings` (I had `setSettings` inside `registerOnSaveHandler` before) :
```
      microsoftTeams.getContext((context) => {
        microsoftTeams.settings.setSettings({
          contentUrl: location.origin,
          configName: "test-config-connector",
          entityId: `test-connector-${context.teamId}-${context.channelId}`
        });

        microsoftTeams.settings.setValidityState(true);
      });

      microsoftTeams.settings.registerOnSaveHandler((saveEvent) => {
        microsoftTeams.settings.getSettings((settings) => {
          console.log(settings);
          saveEvent.notifySuccess();
        });
      });
    }
```
still get the same issue

**Comment by Trinetra-MSFT** [comment]
@marekmierzwa , Sorry I mistakenly pressed closed and comment rather than comment.  I think there is issue with your code, Could you please with this [react sample code](https://docs.microsoft.com/en-us/learn/modules/msteams-webhooks-connectors/7-exercise-o365-connectors)? it will be good if you can provide your manifest to test

**Comment by marekmierzwa** [comment]
Hi @Trinetra-MSFT, I pasted code from other app, but I was getting the same error when I went through https://docs.microsoft.com/en-us/learn/modules/msteams-webhooks-connectors/7-exercise-o365-connectors Tested it again now with the code from example, and still have the same issue. The manifest looks like this:
```
{
  "$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.7/MicrosoftTeams.schema.json",
  "manifestVersion": "1.7",
  "version": "1.0.0",
  "id": "7ede8951-6af0-4d70-b825-8ed41ffe0cd9",
  "packageName": "teamsconnectortest",
  "developer": {
    "name": "Marek Mierzwa",
    "websiteUrl": "https://098930104a2c.ngrok.io",
    "privacyUrl": "https://098930104a2c.ngrok.io/privacy.html",
    "termsOfUseUrl": "https://098930104a2c.ngrok.io/tou.html"
  },
  "icons": {
    "color": "color.png",
    "outline": "outline.png"
  },
  "name": {
    "short": "teams connector test",
    "full": "teams connector test"
  },
  "description": {
    "short": "TODO: add short description here",
    "full": "TODO: add full description here"
  },
  "accentColor": "#D85028",
  "connectors": [
    {
      "connectorId": "7ede8951-6af0-4d70-b825-8ed41ffe0cd9",
      "configurationUrl": "https://098930104a2c.ngrok.io/teamsConnectorTestConnector/config.html?name={loginHint}&tenant={tid}&group={groupId}&theme={theme}",
      "scopes": [
        "team"
      ]
    }
  ],
  "permissions": [
    "identity",
    "messageTeamMembers"
  ],
  "validDomains": [
    "098930104a2c.ngrok.io"
  ]
}
```
the configuration page script (from example):
```
import * as React from "react";
import { Provider, Flex, Header, Dropdown } from "@fluentui/react-northstar";
import TeamsBaseComponent, { ITeamsBaseComponentState } from "msteams-react-base-component";
import * as microsoftTeams from "@microsoft/teams-js";

export interface ITeamsConnectorTestConnectorConfigState extends ITeamsBaseComponentState {
  color: IColor | undefined;
  submit: boolean;
  webhookUrl: string;
  user: string;
  appType: string;
  groupName: string;
}

export interface ITeamsConnectorTestConnectorConfigProps {}

interface IColor {
  title: string;
  code: string;
}

const availableColors: IColor[] = [
  {
    title: "Blue",
    code: "#dce6ee"
  },
  {
    title: "Orange",
    code: "#ffc300"
  }
];

/**
 * Implementation of the teamsConnectorTestConnector Connector connect page
 */
export class TeamsConnectorTestConnectorConfig extends TeamsBaseComponent<
  ITeamsConnectorTestConnectorConfigProps,
  ITeamsConnectorTestConnectorConfigState
> {
  public async componentWillMount() {
    this.updateTheme(this.getQueryVariable("theme"));

    if (await this.inTeams()) {
      microsoftTeams.initialize();

      microsoftTeams.getContext((context: microsoftTeams.Context) => {
        this.setState({
          color: availableColors.filter((c) => c.code === context.entityId)[0]
        });
        this.updateTheme(context.theme);
        microsoftTeams.settings.setValidityState(this.state.color !== undefined);
        microsoftTeams.appInitialization.notifySuccess();
      });

      microsoftTeams.settings.registerOnSaveHandler((saveEvent: microsoftTeams.settings.SaveEvent) => {
        // INFO: Should really be of type microsoftTeams.settings.Settings, but configName does not exist in the Teams JS SDK
        const settings: any = {
          entityId: this.state.color ? this.state.color.code : availableColors[0].code,
          contentUrl: `https://${process.env.HOSTNAME}/teamsConnectorTestConnector/config.html?name={loginHint}&tenant={tid}&group={groupId}&theme={theme}`,
          configName: this.state.color ? this.state.color.title : availableColors[0].title
        };
        microsoftTeams.settings.setSettings(settings);

        microsoftTeams.settings.getSettings((s: any) => {
          this.setState({
            webhookUrl: s.webhookUrl,
            user: s.userObjectId,
            appType: s.appType
          });

          fetch("/api/connector/connect", {
            method: "POST",
            headers: [["Content-Type", "application/json"]],
            body: JSON.stringify({
              webhookUrl: this.state.webhookUrl,
              user: this.state.user,
              appType: this.state.appType,
              groupName: this.state.groupName,
              color: this.state.color ? this.state.color.code : availableColors[0].code,
              state: "myAppsState"
            })
          })
            .then((x) => {
              if (x.status === 200 || x.status === 302) {
                saveEvent.notifySuccess();
              } else {
                saveEvent.notifyFailure(x.statusText);
              }
            })
            .catch((e) => {
              saveEvent.notifyFailure(e);
            });
        });
      });
    } else {
      // Not in Microsoft Teams
      alert("Operation not supported outside of Microsoft Teams");
    }
  }

  public render() {
    const colors = availableColors.map((color) => {
      return {
        header: color.title,
        onClick: () => {
          this.setState({ color });
          microsoftTeams.settings.setValidityState(color !== undefined);
        }
      };
    });
    return (
      <Provider theme={this.state.theme}>
        <Flex fill={true}>
          <Flex.Item>
            <div>
              <Header content="Configure your Connector" />
              <Dropdown items={colors} placeholder="Select card color" checkable />
            </div>
          </Flex.Item>
        </Flex>
      </Provider>
    );
  }
}
```

**Comment by Trinetra-MSFT** [comment]
@marekmierzwa , I tested the same code in VSCode, I was able to save the connector configuration page, Did you update the ngrok URL in your connector dashboard endpoint, When we ran this sample it gives us a ngrok URL, we need to update ngrok URL in connector configuration page.

**Comment by marekmierzwa** [comment]
@Trinetra-MSFT thanks for checking that, after all we decided to change the approach and create a bot. However, I will test example again, as it might be useful for us in the future

**Comment by tthigpen** [comment]
I am having this same issue.  Not sure how to trouble shoot it.  The saveEvent.notifySuccess() spins for about 30 sec then fails:   _"Unable to save "AmplifAI Connector" connector configuration. Please try again."_


**Console error (Maybe coincidental but its consistent)** :
{"seq":1606758866399,"timestamp":1606772917949,"flightSettings":{"Name":"ConnectorFrontEndSettings","AriaSDKToken":"d127f72a...7033","SPAEnabled":true,"ClassificationFilterEnabled":true,"ClientRoutingEnabled":true,"EnableYammerGroupOption":true,"EnableFadeMessage":false,"EnableDomainBasedOwaConnectorList":false,"EnableDomainBasedTeamsConnectorList":false,"DevPortalSPAEnabled":true,"ShowHomeNavigationButtonOnConfigurationPage":false,"DisableConnectToO365InlineDeleteFeedbackPage":true},"status":500,"clientType":"SkypeSpaces","connectorType":"...","name":"handleMessageError"}

**Comment by Trinetra-MSFT** [comment]
@tthigpen , Can you check your configuration URL in connector developer dashboard? This error occurs when configuration URL is not correct or `setValidityState `is not set to true

**Comment by tthigpen** [comment]
OK, Thanks for the feedback.  I have there configured correctly so thats not the issue, but what I did find is it fails using Teams in a Chrome browser but works fine using the Teams app on my Mac.  Not sure if someone else trying to use this app in a browser will have the same issue.  I'll try Edge later today.

**Comment by Trinetra-MSFT** [comment]
@tthigpen , I can repro this at my end, going to file a Bug for this. 
![image](https://user-images.githubusercontent.com/50989436/101015989-2eb25780-358e-11eb-8502-a9f217111697.png)

This used to work few weeks back when I tested.

**Comment by tthigpen** [comment]
Thanks.  Please keep me posted.

**Comment by roni-frantchi** [comment]
Facing the same issue here.

**Comment by roni-frantchi** [comment]
@Trinetra-MSFT is there some sort of workaround for this one?  
It blocks us from building our Teams app as it stands.

**Comment by Trinetra-MSFT** [comment]
@roni-frantchi , We are working on this Bug, We don't have ETA to share with you

**Comment by roni-frantchi** [comment]
Thanks @Trinetra-MSFT .  
I'm afraid even when trying to do the same on my own following the documentation - I'm getting the same errors.  
Seems to me like if one gets 500s and `ng` errors, there's a problem with the platform.

**Comment by tthigpen** [comment]
Any update?

**Comment by Trinetra-MSFT** [comment]
@roni-frantchi , [React sample code](https://docs.microsoft.com/en-us/learn/modules/msteams-webhooks-connectors/7-exercise-o365-connectors) is working fine, Can we get on the call to check the code issues? You can reachout to `microsoftteamsdev@microsoft.com` for discussion

**Comment by skrobul** [comment]
Had the same problem and spent countless hours troubleshooting it. I was also following the [very poor documentation](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-creating#integrating-the-configuration-experience) with plain javascript example (same as @tthigpen). Long story short, the problem was not with my code. During tshooting, I was trying to sideload the connector in Firefox and was watching all https requests. I have noticed that browser sends a request to an old configurationUrl that is not part of the configuration. It has been replaced both in manifest and the Connector dashboard. Said request has been followed by the request to correct (new) url, but still was producing configuration error.

As further troubleshooting, I attempted to bump the version in manifest, clicked Save in the Connector Developer dashboard several times but none of this helped. My last resort was to just create brand new connector in the dashboard, update the IDs in the manifest.json and it worked straight away!

So despite what @Trinetra-MSFT [suggested above](https://github.com/MicrosoftDocs/msteams-docs/issues/2247#issuecomment-749337306), it is a problem with platform. If MS is interested in debugging this further, I have not deleted the problematic connector yet - it's ID is `4c432a27-fffa-4261-a5ee-25f0eca8529b`.

**Comment by RamaMohanaChary** [comment]
Could you please reach out to microsoftteamsdev@microsoft.com, as this question got closed earlier.

**Comment by tthigpen** [comment]
@skrobul Thanks for your work on this.  I followed your steps and got it to load.  much appreciated.  Now I have an issue with testing the URL.

**Comment by skrobul** [comment]
@tthigpen no worries, glad it helped someone.

fwiw, I've emailed  the address @RamaMohanaChary mentioned but there was zero response and the problem still persists.
