### ISSUE TITLE
[Teams] Getting multiple notification while 1:1, group chat or channel conversation

### ISSUE THREAD

**Issue by Trinetra-MSFT** [MicrosoftDocs/msteams-docs#2251]
I am facing issue with chat/conversation toast notification. whenever I got a new message from team member teams is showing 2-3 times same notification toast for single chat thread. its confusing. 
Here is the screenshot:
![image](https://user-images.githubusercontent.com/50989436/97567510-c1e6f300-1a0c-11eb-955f-a9f55b5163bf.png)

OS: Windows 10
Microsoft Teams Version 1.3.00.30246 (64-bit)-E

**Comment by Abhijit-MSFT** [comment]
We are unable to repo this issue. Can you please provide proper repo steps.
