### ISSUE TITLE
Button contains a typo

### ISSUE THREAD

**Issue by anuraj** [MicrosoftDocs/msteams-docs#2254]
There is a typo in the text of the button - word adding is getting duplicated.

![image](https://user-images.githubusercontent.com/276411/97713367-bfa49780-1ae5-11eb-966a-8212de9145eb.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63519845-323f-be8f-ce15-d7f39e46b5a7
* Version Independent ID: 70952f91-56e9-ff08-59f6-e237d4aaeca9
* Content: [Add authentication to your Teams bot - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/authentication/add-authentication?tabs=dotnet%2Cdotnet-sample)
* Content Source: [msteams-platform/bots/how-to/authentication/add-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/bots/how-to/authentication/add-authentication.md)
* Product: **msteams**
* GitHub Login: @clearab
* Microsoft Alias: **lajanuar**

**Comment by Abhijit-MSFT** [comment]
@anuraj, Thanks for reporting this.
