### ISSUE TITLE
In-meeting Theming

### ISSUE THREAD

**Issue by ismailMSFT** [MicrosoftDocs/msteams-docs#2261]
[Enter feedback here]
In-meeting tab should apply a dark theme and should follow theming guidelines.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd677929-df88-f9d3-dbe3-14d4e9ff20fa
* Version Independent ID: 1532837b-1369-2846-15e6-332e2a0a13af
* Content: [Design an in-meeting tab - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/design/designing-in-meeting-tab#theming-1)
* Content Source: [msteams-platform/apps-in-teams-meetings/design/designing-in-meeting-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/apps-in-teams-meetings/design/designing-in-meeting-tab.md)
* Product: **msteams**
* GitHub Login: @heath-hamilton
* Microsoft Alias: **lajanuar**

**Comment by Mahesh2516** [comment]
Issue resolved
