### ISSUE TITLE
In-meeting dialog

### ISSUE THREAD

**Issue by ismailMSFT** [MicrosoftDocs/msteams-docs#2262]
[Enter feedback here]
In-meeting dialog must not use task module.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b60eeacc-a71e-9644-b869-3e0a4f1506d8
* Version Independent ID: 313bf83f-5325-f9f4-5780-9bc81e315c1e
* Content: [Create apps for teams meetings - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?tabs=json)
* Content Source: [msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Trinetra-MSFT** [comment]
@laujan , Could you please document this request from App submission Team? in Meeting dialog we should not use task Module
![image](https://user-images.githubusercontent.com/50989436/97964411-bfa2e100-1dde-11eb-9b85-e8af1cb65221.png)
Link to the highlighted task module is also broken in Notes section

**Comment by Mahesh2516** [comment]
issue resolved
