### ISSUE TITLE
In-meeting notifications

### ISSUE THREAD

**Issue by ismail0810** [MicrosoftDocs/msteams-docs#2263]
[Enter feedback here]
Exporting a result of a survey (or) polls  should notify the users stating, ‘results successfully downloaded’.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd677929-df88-f9d3-dbe3-14d4e9ff20fa
* Version Independent ID: 1532837b-1369-2846-15e6-332e2a0a13af
* Content: [Design an in-meeting tab - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/design/designing-in-meeting-tab)
* Content Source: [msteams-platform/apps-in-teams-meetings/design/designing-in-meeting-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/apps-in-teams-meetings/design/designing-in-meeting-tab.md)
* Product: **msteams**
* GitHub Login: @heath-hamilton
* Microsoft Alias: **lajanuar**

**Comment by Mahesh2516** [comment]
> [Enter feedback here]
> Exporting a result of a survey (or) polls should notify the users stating, ‘results successfully downloaded’.
> 
> #### Document Details
> ⚠ _Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking._
> 
> * ID: bd677929-df88-f9d3-dbe3-14d4e9ff20fa
> * Version Independent ID: 1532837b-1369-2846-15e6-332e2a0a13af
> * Content: [Design an in-meeting tab - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/design/designing-in-meeting-tab)
> * Content Source: [msteams-platform/apps-in-teams-meetings/design/designing-in-meeting-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/apps-in-teams-meetings/design/designing-in-meeting-tab.md)
> * Product: **msteams**
> * GitHub Login: @heath-hamilton
> * Microsoft Alias: **lajanuar**

Issue #2263 comments (Exporting a result of a survey (or) polls should notify the users stating, ‘results successfully downloaded’) to be placed under in-meeting section of #2259.

**Comment by Mahesh2516** [comment]
Added the comment under the in-meeting section of 2259.
