### ISSUE TITLE
In-meeting Message extension

### ISSUE THREAD

**Issue by ismailMSFT** [MicrosoftDocs/msteams-docs#2264]
[Enter feedback here]
Message extension should work as expected when user is in-meeting view, they should be able to post compose message extension cards. 
AppName in-meeting - Tooltip should state the app name in-meeting U-bar. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b60eeacc-a71e-9644-b869-3e0a4f1506d8
* Version Independent ID: 313bf83f-5325-f9f4-5780-9bc81e315c1e
* Content: [Create apps for teams meetings - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?tabs=json#in-meeting)
* Content Source: [msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Mahesh2516** [comment]
issue resolved
