### ISSUE TITLE
Microsoft Team App on Android: teamsContext.channelRelativeUrl contains invalid value

### ISSUE THREAD

**Issue by maxmurash** [MicrosoftDocs/msteams-docs#2268]
Hello,

I observed that teams context has an invalid value in one of its properties when I open my custom tab application in teams channel context. It is reproducible only on android devices. I tested exact same steps on IPhone and on desktop, everything works fine.

**Pre-conditions:**
- Custom teams app which can be installed as the teams channel tab.
- The app **doesn't** fill websiteUrl property during installation (mentioned as requirement here: https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/design/tabs-mobile). The app is still available on mobile devices (if it is installed by uploading package manually, not from the app store), and by default it is opened in the teams app, not in the browser, which is important.

**Steps to reproduce:**

1. Log in as a tenant admin to Teams
1. Upload your custom teams app to teams
1. Create a channel in a team (not a General channel, which is available by default)
1. Add a custom app tab to the channel. Pick "Post to the channel about this tab" checkbox on save settings
1. Open Teams app  on android phone
1. a. Try to open the tab from a link in the channel
1. b. Try to open the tab from "More" tab and selecting your tab from the list of available tabs.

**Result:**
a. channelRelativeUrl property in the teams context object is empty
b. channelRelativeUrl property in the teams context object points to the General channel folder.

**Expected result:**
channelRelativeUrl property contains actual value for the current channel

**Code to get context:**
```
microsoftTeams.initialize();
microsoftTeams.getContext((ctx: microsoftTeams.Context) => {console.log(ctx.channelRelativeUrl )});
```

**Device info:**
- Android 7, Android 10 devices
- Latest teams app from Play Store (v. 1416/1.0.0.2020100901)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 899fd20f-64f0-d255-a3d8-473313fc1a61
* Version Independent ID: b9142e64-218c-10f9-6447-3d53099ff55c
* Content: [Context interface - Teams](https://docs.microsoft.com/en-us/javascript/api/@microsoft/teams-js/context?view=msteams-client-js-latest)
* Content Source: [nodejs/docs-ref-autogen/@microsoft/teams-js/Context.yml](https://github.com/OfficeDev/msteams-client-docs-ref-typescript/blob/live/nodejs/docs-ref-autogen/@microsoft/teams-js/Context.yml)
* Product: **msteams**
* GitHub Login: @charlesprakash
* Microsoft Alias: **o365devx**

**Comment by Nikitha-MSFT** [comment]
We are able to repro the issue at our end. Raised a bug.

**Comment by AndreyButyrchik** [comment]
Small update: I recently managed to randomly reproduce this bug several times in the web client.

**Comment by ChetanSharma-msft** [comment]
Hello @maxmurash - This issue has fixed. Kindly check and let you know if you still face this issue.

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, please feel free to reopen it, if required.
