### ISSUE TITLE
fist feedback

### ISSUE THREAD

**Issue by samir1979** [MicrosoftDocs/msteams-docs#227]
this the fist feedback

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b849c477-8956-660d-eb91-263f1ecf6994
* Version Independent ID: 71eb8427-3bcf-3d83-61be-90bc1523a16f
* Content: [Get started - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/get-started/get-started)
* Content Source: [msteams-platform/get-started/get-started.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/get-started/get-started.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Wajeed-msft** [comment]
Could you please provide more details here?
