### ISSUE TITLE
small theme issue

### ISSUE THREAD

**Issue by orlavy1976** [MicrosoftDocs/msteams-docs#2270]
one thing that is missing in to add theme to the default state
second thing - the state.theme is null by default (since theme was not changing). to fix this:
itTheme = this.state.theme || this.state.context.theme

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29e90229-289e-2035-3b42-5cb9cce14efe
* Version Independent ID: a2aee4b8-93b9-bda7-f000-8f41b4513647
* Content: [Get started - Build a personal tab - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/build-your-first-app/build-personal-tab)
* Content Source: [msteams-platform/build-your-first-app/build-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/build-your-first-app/build-personal-tab.md)
* Product: **msteams**
* GitHub Login: @heath-hamilton
* Microsoft Alias: **lajanuar**

**Comment by Nikitha-MSFT** [comment]
We are able to reproduce the issue. Raised a bug.

**Comment by ChetanSharma-msft** [comment]
Hello @orlavy1976 - Engineering team is not able to repro it.
If you are still facing this issue, please let us know.
