### ISSUE TITLE
.publish folder is missing

### ISSUE THREAD

**Issue by orlavy1976** [MicrosoftDocs/msteams-docs#2271]
I followed the instructions (working on Mac with VSCode) and couldn't find .publish folder so I couldn't update manifest.json with ngrok url

to fix this I "Download" the  package from App Studio, extract it, manipulate manifest.json manually and compress it manually before uploading to MS Teams

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f876156-cc1e-468f-4647-5143a5de03b1
* Version Independent ID: 618f43a3-3371-ad99-13aa-087b9303298c
* Content: [Get started - Build and run your first app - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/build-your-first-app/build-and-run)
* Content Source: [msteams-platform/build-your-first-app/build-and-run.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/build-your-first-app/build-and-run.md)
* Product: **msteams**
* GitHub Login: @heath-hamilton
* Microsoft Alias: **lajanuar**

**Comment by Abhijit-MSFT** [comment]
Did you face any error during setup? I was able to set up with no issues.
Can you please try once again and let me know if it is still same.

**Comment by orlavy1976** [comment]
there were no errors during setup
here is the project structure after I click finish: 
![image](https://user-images.githubusercontent.com/4249410/98246452-fada1700-1f7a-11eb-9a0f-8f1a3446dcc0.png)

**Comment by Abhijit-MSFT** [comment]
I am checking it internally if there is any known issue on this.

**Comment by asnow003** [comment]
@orlavy1976 really sorry our documentation update didn't make it out at the same time as the version update.  I am working on getting that approved ASAP.  It should be out today/tomorrow.  Sorry about the inconvenience.

In the meantime though the .publish folder is deprecated.  Once you create a new project in the toolkit all you need to do is hit F5/run and it will launch Chrome and install your package.  The package is stored in App Studio and we just use its id to install it.
