### ISSUE TITLE
Document and its steps are outdated and do not match

### ISSUE THREAD

**Issue by sthigale-m** [MicrosoftDocs/msteams-docs#2275]
Document and its steps are outdated and do not match

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f876156-cc1e-468f-4647-5143a5de03b1
* Version Independent ID: 618f43a3-3371-ad99-13aa-087b9303298c
* Content: [Get started - Build and run your first app - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/build-your-first-app/build-and-run?source=docs)
* Content Source: [msteams-platform/build-your-first-app/build-and-run.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/build-your-first-app/build-and-run.md)
* Product: **msteams**
* GitHub Login: @heath-hamilton
* Microsoft Alias: **lajanuar**

**Comment by Manish-MSFT** [comment]
@sthigale-m, Could you please  mention which steps you think are aren't matching?

**Comment by sthigale-m** [comment]
For example, `.publish` folder does not get generated at all as mentioned in the steps.

**Comment by heath-hamilton** [comment]
Hi @sthigale-m--thanks for your help here. The docs were updated to reflect the latest toolkit updates in PR https://github.com/MicrosoftDocs/msteams-docs/pull/2285.
