### ISSUE TITLE
Teams integration with RUUM is not working 

### ISSUE THREAD

**Issue by karthik4621** [MicrosoftDocs/msteams-docs#2278]
When I go to a teams channel and try to add a RUUM app as a tab, the UI shows a login screen and then nothing happens on click of login. This was working till last month. This is a regression and causing issues for our team execution. Please Look into the issue with priority. 

I wasted my time trying to figure out where to raise an issue on Teams. Why is it not obvious to MS that people need a clear link to raise tickets mentioned in some help docu ??

**Comment by Trinetra-MSFT** [comment]
@karthik4621 , We can repro this issue at our end, When I tried to add RUUM app in teams channel, I can see login issue, I was getting 401 unauthorized error
 
![image](https://user-images.githubusercontent.com/50989436/98088749-d82afe00-1ea7-11eb-96e4-208642ac776d.png)

by seeing the error it seems access_token is not getting generated, Could you please check the redirect URL in azure?

**Comment by karthik4621** [comment]
@Trinetra-MSFT  I couldn't understand the request

**Comment by Trinetra-MSFT** [comment]
@karthik4621 , Could you please check the redirect URL in azure for app? There nothing happens when I click on Login button it throws error as mentioned in the screenshot. Please also check CORS is enabled in header request. This works fine in Teams browser but not in desktop

**Comment by karthik4621** [comment]
I could not follow - 'azure for app'. Also, please test in your environment if it is already reproducible. We use Teams Desktop app mainly. We need it to work in it. Thanks.

**Comment by Trinetra-MSFT** [comment]
This I can reproduce for teams desktop client but it is working fine for Teams web. But we are not getting the sign up page what Auth mechanism app have used. Page is not loading for desktop (only login button i visible) but it works for web we can signup and login in Teams web

**Comment by karthik4621** [comment]
It's not working via the browser too. I have a enterprise account and it fails to recognize it. 
![image](https://user-images.githubusercontent.com/73930521/98663092-a665db80-236e-11eb-9ce3-c3e13046d644.png)

**Comment by Trinetra-MSFT** [comment]
@karthik4621 , I tried to sign up first and tried login it is working fine for web but same is not working at desktop client
![image](https://user-images.githubusercontent.com/50989436/98664211-13c63c00-2370-11eb-828a-796fee5b12a6.png)

However it seems channel tab implementation is not done properly , The page was loading in pop window rather than saving it as [configurable tab in channel](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/configuration-page#configuring-a-channel-or-group-chat-tab)
