### ISSUE TITLE
Teams integration with MS planner does not work

### ISSUE THREAD

**Issue by karthik4621** [MicrosoftDocs/msteams-docs#2279]
Go to a teams channel
Try adding a existing MS Planner plan as a tab
The UI does not respond on click of "Use Existing plans.."

![image](https://user-images.githubusercontent.com/73930521/98090030-897e6380-1ea9-11eb-93b8-1c3a17137ed7.png)

The integration is flawed. Please set this right as it is blocking us in integrating teams with tasks being executed in planner.

**Comment by Abhijit-MSFT** [comment]
Can you please answer below queries.
Does creating new plan works for you without any issue?
Do you have any existing plan already in place to select?
Is there any error in console when you try to add existing plan?
