### ISSUE TITLE
Tabs authentication sample for C# redirects to page not found

### ISSUE THREAD

**Issue by sacheinbaala** [MicrosoftDocs/msteams-docs#228]
Tabs authentication sample for C# redirects to page not found

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d939a56-d1be-f2a2-3454-0f0c5144bc27
* Version Independent ID: ec4d5574-ddeb-9408-ad82-d86507a5111b
* Content: [Authentication for tabs using Azure Active Directory - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/authentication/auth-tab-aad)
* Content Source: [msteams-platform/concepts/authentication/auth-tab-AAD.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/authentication/auth-tab-AAD.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by NormSohl** [comment]
Removed link to C# example.  Thanks! The change should be live later today.
