### ISSUE TITLE
Links to cross-organization tabs do not resolve

### ISSUE THREAD

**Issue by HaveSpacesuit** [MicrosoftDocs/msteams-docs#2281]
For each of these scenarios, a user needs to have at least two active organizations on the desktop app that they can switch between.

**Scenario 1: Link to cross organization channel (working)**
From Organization 1, select a channel and from the channel options "Get link to channel". Switch to Organization 2. Paste the link in a browser and open in Microsoft Teams. The app asks if you want to switch to Organization 1 and then successfully redirects to the channel.

**Scenario 2: Link to cross organization tab (not working)**
From Organization 1, select a tab and from the tab options "Copy link to tab". Switch to Organization 2. Paste the link in a browser and open Microsoft Teams. The app asks if you want to switch to Organization 1. It will navigate to the channel of the link, but not the tab. (In the case of custom third-party tabs, it may take you to the info page for the app and fail to resolve anything.)

**Scenario 3: Deep link to cross organization tab content (not working)**
From Organization 1, select a custom tab with the option to deep link to content (with the channel ID) and get a link to something. Switch to Organization 2. Paste the link in a browser and open Microsoft Teams. The app's behavior is unpredictable. Sometimes it will not do anything, and sometimes it will try to open a related tab in Organization 2 if possible.

Expected behavior: If the link contains a channel ID for a channel on another organization, MS Teams should offer to switch organizations and continue resolving the link.

**Comment by Nikitha-MSFT** [comment]
We are able to reproduce the issue. Raised a bug.

**Comment by ChetanSharma-msft** [comment]
Hello @HaveSpacesuit - Could you please confirm whether you are still facing this kind of issue?
