### ISSUE TITLE
Can't create in-meeting tab with developer preview via Visual Studio Teams Toolkit

### ISSUE THREAD

**Issue by scrosoff** [MicrosoftDocs/msteams-docs#2282]
Hello,

I'm looking to create an in-meeting Teams app consisting of tabs/bot features. It looks like this functionality is available in Developer Preview, as mentioned [here](https://docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/teams-apps-in-meetings).

I followed instructions to set up an O365 tenant with privileges to enable uploading custom apps and enabling Developer Preview. I use the same tenant in Visual Studio 2019 Enterprise and when I load the Teams toolkit and add a tab, the "Meeting" scope option is unavailable (screenshot below). Is this an issue given I set up developer preview, or is there something else I need to enable?

![image](https://user-images.githubusercontent.com/50416029/98154619-e4a05e00-1e89-11eb-88da-1f9f69a381ba.png)

Thanks

**Comment by Abhijit-MSFT** [comment]
@scrosoff, Sorry for the delayed reply. My team is checking this issue and we will get back to you

**Comment by Trinetra-MSFT** [comment]
@scrosoff, Can you confirm your preview is selected? we checked this and found following for VS Code & Visual studio 
![image](https://user-images.githubusercontent.com/50989436/100420457-85122880-30ac-11eb-9206-04cba7e1edc6.png)

![image](https://user-images.githubusercontent.com/50989436/100420068-c3f3ae80-30ab-11eb-9034-d9e18607c178.png)

**Comment by Trinetra-MSFT** [comment]
Please feel free to reopen if you have further query on this.
