### ISSUE TITLE
Open a tab application when click on search result item

### ISSUE THREAD

**Issue by piyumi25** [MicrosoftDocs/msteams-docs#2291]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f57a31a0-e815-faa4-653d-795ae8a8e4d7
* Version Independent ID: 8f48ea3d-231b-2776-41b7-11890ea2d3c0
* Content: [Build apps for the Microsoft Teams platform - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/overview)
* Content Source: [msteams-platform/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/overview.md)
* Product: **msteams**
* GitHub Login: @heath-hamilton
* Microsoft Alias: **lajanuar**

**Comment by Abhijit-MSFT** [comment]
Can you please provide more information.

**Comment by piyumi25** [comment]
I have a teams application which is personal tab. In same application there is a message extension search command app also. That search extension  is invoked from command box. After search query has made then search results are shown. When click on single item I need to show the details of selected item in personal tab window .

**Comment by VaraPrasad-MSFT** [comment]
You cannot redirected to Message Extension to Tab directly , but you can provide the buttons in adaptive card and you can create a deeplink to tab.
