### ISSUE TITLE
updated: The sidepanel app is not able to be displayed on in-meeting panel.

### ISSUE THREAD

**Issue by skeletonKim** [MicrosoftDocs/msteams-docs#2300]
Without any changes except ngrok endpoint, I have tried to access my SidePanel App in Teams, currently for testing by Devpreview manifest.json. 
This is for a feasibility check of displaying the app during the meeting. It was working well till last week. but suddenly it is not able to display anymore. I have not changed any configurations from last which was working well. 

I am attaching my manifest.json after removing confidential information. As a mention for referring, I have already set on Teams Admin, Activate Teams app > Setup policies > Upload custom apps. ( https://docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?tabs=json )

And Turned on Developer Preview of User Setting.
And Delete Teams cache data in %AppData%Microsoft / Reinstall App after uninstalling. - Not solved

The Same App is visible on ChannelTab, but not visible on the unified bar (u-bar) of in-meeting panel.

![image](https://user-images.githubusercontent.com/70251740/98621685-2aa66780-234b-11eb-9c5d-9eaab3acd6cd.png)

This image is the screenshot, succeeded last time.

![image](https://user-images.githubusercontent.com/70251740/98498109-4cd7b100-2289-11eb-8907-8353e9ce93e2.png)

- Additional (2020/11/09 AM 10:00, Even further, Tab does not work anymore.)

As you notice, my manifest.json did not set configurationUrl like below. but when I access Teams by the browser. I have faced below the message. even further I could not see any message when accessing from Teams App.

![image](https://user-images.githubusercontent.com/70251740/98492348-e9468700-227a-11eb-8947-585c301075af.png)

- Additional (2020/11/09 AM 11:20, Tab is working after creating a new Team. but still not visible on the unified bar (u-bar) of in-meeting panel.) It may be caused by the internet cache has remained in the browser. 

1) Does the manifest loader in teams have any mechanism of internal cache? could you tell me how to initialize all cache data related side panel app?
2) In terms of the settings for activating Development preview, It seems to not have any omitted part. If it is not, Could you tell me any setting should be checked?
3) Is there any changes to the loading side panel in-meeting app?  

# manifest.json
```json
{
   "$schema": "https://raw.githubusercontent.com/OfficeDev/microsoft-teams-app-schema/preview/DevPreview/MicrosoftTeams.schema.json",
   "manifestVersion": "devPreview",
   "version": "1.0.0",
   "id": "aa32a7c1-45d5-455b-8752-882c58aa773c",
   "packageName": "demo.contoso.teams.extension",
   "developer": {
      "name": "skeletonKim",
      "websiteUrl": "https://45f3bbb9528c.ngrok.io",
      "privacyUrl": "https://45f3bbb9528c.ngrok.io/privacy",
      "termsOfUseUrl": "https://45f3bbb9528c.ngrok.io/termsofuse"
   },
   "icons": {
      "color": "color.png",
      "outline": "outline.png"
   },
   "name": {
      "short": "Demo App",
      "full": "Demo App"
   },
   "description": {
      "short": "Short description for Demo App.",
      "full": "Full description of Demo App for Microsoft Teams."
   },
   "accentColor": "#FFFFFF",
   "bots": [],
   "composeExtensions": [],
   "configurableTabs": [
      {
        "configurationUrl": "https://45f3bbb9528c.ngrok.io/config",
        "canUpdateConfiguration": true,
        "scopes": [
          "team",
          "groupchat"
        ],
        "context":[
          "channelTab",
          "privateChatTab",
          "meetingChatTab",
          "meetingDetailsTab",
          "meetingSidePanel"
       ]
     }
   ],
   "permissions": [
      "identity",
      "messageTeamMembers"
   ],
   "devicePermissions": [
      "media",
      "geolocation",
      "notifications",
      "midi",
      "openExternal"
   ],
   "validDomains": [ 
      "*.ngrok.io"
   ]
}
```

**Comment by skeletonKim** [comment]
updated some description

**Comment by skeletonKim** [comment]
..

**Comment by Wajeed-msft** [comment]
@skeletonKim - Is your issue resolved?
