### ISSUE TITLE
NOT SECURE - pls make page https

### ISSUE THREAD

**Issue by prkosh** [MicrosoftDocs/msteams-docs#2301]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 001a12ea-30fa-d626-18a9-02a518bfb37f
* Version Independent ID: e5f5f69e-66e9-d1b2-e19a-485d0ffcd6fa
* Content: [Text formatting in cards - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?tabs=adaptive-md%2Cconnector-html)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-format.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-format.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Manish-MSFT** [comment]
@prkosh , Can you please elaborate issue you are facing?

**Comment by prkosh** [comment]
The page referenced here is not https
Please make it https for better seo and surfacing in google search results

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
