### ISSUE TITLE
Is there any limitation to the number of search results can return in search command extension?

### ISSUE THREAD

**Issue by piyumi25** [MicrosoftDocs/msteams-docs#2302]
I am developing a search extension app and I was trying to return 150 items during initial run. I noticed that only 100 items can return in 4 times (25 items at once). Can some one help me to understand this? Is there any way to change the count and skip count properties?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4f3b627-c87b-6a19-9c26-7170a99f38ee
* Version Independent ID: a9546115-7c5d-39c9-ca8a-3cf3e02ff621
* Content: [Respond to search command - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/search-commands/respond-to-search?tabs=dotnet)
* Content Source: [msteams-platform/messaging-extensions/how-to/search-commands/respond-to-search.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/messaging-extensions/how-to/search-commands/respond-to-search.md)
* Product: **msteams**
* GitHub Login: @clearab
* Microsoft Alias: **anclear**

**Comment by Manish-MSFT** [comment]
Hi @piyumi25,  Have you tried giving queryOptions count to more than 25? If that still doesn't work the limit must be 25.

**Comment by piyumi25** [comment]
yeah I tried to increase the count but that limits to returning the results only once. As an example I changed the count in to 50 and I tried to return 100 items. First time I was able to return 50 but when scrolling down to 50th item nothing was happened.

**Comment by Manish-MSFT** [comment]
@piyumi25, I am just finding a way out to repro this issue at my end. Can you please share manifest and repro steps here this will help me to repro issue at my end and take it further.

**Comment by shash91** [comment]
@Manish-MSFT  I am having the same issue that @piyumi25  is facing. I have a search list that returns 197 values, with pagination I can load only up to 100 results. It looks like when `query.QueryOptions.Skip=75` it stops firing the method `OnTeamsMessagingExtensionQueryAsync `

**Comment by Mamatha-MSFT** [comment]
@shash91 Could you please write to us at microsoftteamsdev@microsoft.com with the detail briefing on the issue.

**Comment by gb2793** [comment]
@Trinetra-MSFT @shash91 I am using messaging extension search command from compose area and the default invoke request contains queryOptions.Count as 25. How can I update this to 100? I don't see any support for this in app manifest.json.

**Comment by Mamatha-MSFT** [comment]
Hi @gb2793 The default invoke request count is 25. Even If we change the count still it will display 25. It is by design.
