### ISSUE TITLE
Issue with profile image

### ISSUE THREAD

**Issue by avijitmondal** [MicrosoftDocs/msteams-docs#2304]
I have used one image then removed my image again I have added a new image. But still it is showing the oldest image.
![image](https://user-images.githubusercontent.com/19147970/98664427-5f78e580-2370-11eb-8bbc-6c6e80c9cbc1.png)

It should show updated image every where.

**Comment by Trinetra-MSFT** [comment]
@avijitmondal , Did you tried sign out/sign in from teams once?

**Comment by avijitmondal** [comment]
This is a company account, I have tried using restarting my system.

**Comment by avijitmondal** [comment]
@Trinetra-MSFT I have tried after sign out/sign in again.
It is working fine now.

**Comment by Trinetra-MSFT** [comment]
We are Microsoft Teams Developer Community, Please share your feedback and rating to improve developer response experience.

Thanks
