### ISSUE TITLE
Is it possible to execute the "Deep Link" rather than opening a Task Module in Action Command Extension App?

### ISSUE THREAD

**Issue by piyumi25** [MicrosoftDocs/msteams-docs#2305]
I am creating an **Action Command Extension App** which need to open a **Deep Link** without showing the **Task Module**. 
For an example: In "Azure Boards" application, If I click on "Create work item" then it will show the popup. In my case I do not want to show a popup. I just want to redirect to my tab application.

![ac-git](https://user-images.githubusercontent.com/33615108/98671534-6d336880-237a-11eb-867a-11cca47979f9.PNG)

**Comment by Abhijit-MSFT** [comment]
I think Trinetra-MSFT replied to your query. 
You can do it but I am curious to understand your complete scenario to help you with right approach.

**Comment by piyumi25** [comment]
@Abhijit-MSFT Trinetra-MSFT's response helped me to get the idea that I can open the tab application in button action after showing the search results. But my exact requirement is to open the tab application without showing the results. Currently my app is working as follows.
![issueexplain](https://user-images.githubusercontent.com/33615108/98764810-94357d00-2402-11eb-8517-1030369999d2.PNG)

According the documentation, there are 4 return types as follows.

_result: displays a list of search results
auth: asks the user to authenticate
config: asks the user to set up the messaging extension
message: displays a plain text message_

For my app I am using the response type as "results" and then then I have to return a response in following format.

```
 return new MessagingExtensionResponse
            {
                ComposeExtension = new MessagingExtensionResult
                {
                    Type = "result",
                    AttachmentLayout = "list",
                    Attachments = attachments
                }
            };
```
So my problem is, how can I return a response to execute a **Deep Link**?

**Comment by Nikitha-MSFT** [comment]
Currently you cannot execute the Deep link directly on Compose extension submit action. You can pass the adaptive card with deep link to the compose box. This is by design.
