### ISSUE TITLE
cannot import existing project

### ISSUE THREAD

**Issue by orlavy1976** [MicrosoftDocs/msteams-docs#2306]
Hi,

I am using VSCode with the Microsoft Teams Toolkit on MacOS and I can't find the **Import App Package** command.
It seems that the documentation is outdated.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5e07135-25cc-d865-2cad-b3dc6f22f750
* Version Independent ID: b1c26476-0b6a-7f6c-f64a-abd1d9ae8d21
* Content: [Build apps with the Microsoft Teams Toolkit and Visual Studio Code - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/toolkit/visual-studio-code-overview)
* Content Source: [msteams-platform/toolkit/visual-studio-code-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/toolkit/visual-studio-code-overview.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Wajeed-msft** [comment]
Hi @orlavy1976 - Could you please share screenshot of your VS Code? I'll get this checked. 

I could see it on my Windows machine like this: 
![image](https://user-images.githubusercontent.com/31851992/98677716-68bf7d80-2383-11eb-8fa3-dda1a68bde19.png)

**Comment by orlavy1976** [comment]
![image](https://user-images.githubusercontent.com/4249410/98678039-9fd36600-2366-11eb-9ec6-f2ef784e41ec.png)

**Comment by orlavy1976** [comment]
I am using v1.1.2
![image](https://user-images.githubusercontent.com/4249410/98678323-0a84a180-2367-11eb-84f8-d893c511f749.png)

**Comment by ChetanSharma-msft** [comment]
Hello @orlavy1976 - This is a very old issue, so closing it.
Please feel free to re-open it if required.
