### ISSUE TITLE
How can we include volunteers into our teams platform safely 

### ISSUE THREAD

**Issue by LouisaH1** [MicrosoftDocs/msteams-docs#2307]
Hi there Git Hub World
We are pondering since covid 19 how to use microsoft teams for our volunteers. we need need to ensure they are safe and we can create a channel so that we can share project documents have group supervisions and individual supervisions and help volunteers connect amongst themselves safely...... am i in any way in the right place to ponder find an answer??? stay safe all best

**Comment by Abhijit-MSFT** [comment]
Hi LouisaH1, You are in right place for MS Teams related queries.
Teams provide many useful features which are specially useful in the current situation where remote work is the only option available for many industries.
To know about feature please check this [documentation](https://www.microsoft.com/en-us/microsoft-365/microsoft-teams/group-chat-software?&ef_id=CjwKCAiAtK79BRAIEiwA4OskBn15geXUv0oysWhrvYGPs9jDwcvSXBDzzdmzkFKHPtu1O8lwSnapExoCyfIQAvD_BwE:G:s&OCID=AID2100233_SEM_CjwKCAiAtK79BRAIEiwA4OskBn15geXUv0oysWhrvYGPs9jDwcvSXBDzzdmzkFKHPtu1O8lwSnapExoCyfIQAvD_BwE:G:s&gclid=CjwKCAiAtK79BRAIEiwA4OskBn15geXUv0oysWhrvYGPs9jDwcvSXBDzzdmzkFKHPtu1O8lwSnapExoCyfIQAvD_BwE). 
Please check [How to use Teams](https://www.youtube.com/watch?v=CH2seLS5Wb0).

Please let me know if you have any specific question.

**Comment by Trinetra-MSFT** [comment]
Please feel free to reopen if you have further query on this
