### ISSUE TITLE
Code snippet needs update

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#2309]
Signature for _OnTeamsMembersAddedAsync()_ is changed. Please correct the code snippet as per latest SDK. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a6d00a4-dd28-33c4-002e-2e8e7c653ce2
* Version Independent ID: 0856927a-25f4-b1e0-5f1b-d55dc61796f3
* Content: [Subscribe to conversation events - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/subscribe-to-conversation-events?tabs=dotnet#team-members-added)
* Content Source: [msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md)
* Product: **msteams**
* GitHub Login: @WashingtonKayaker
* Microsoft Alias: **anclear**

**Comment by Trinetra-MSFT** [comment]
@Wajeed-msft : I'm running `Microsoft Bot Builder 4.11.1.0`, I checked the signature for `OnTeamsMemberAdeddAsync `this is still having the same signature, Can you tell us which SDK version you are talking about?
![image](https://user-images.githubusercontent.com/50989436/99960390-ab854a80-2db2-11eb-94f8-3694855b665e.png)
