### ISSUE TITLE
Rest endpoint for Sending replies is incorrect

### ISSUE THREAD

**Issue by hexonthebeach** [MicrosoftDocs/msteams-docs#231]
The endpoint to send replies is missing /v3 in front, like the endpoint for Updating messages

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 0d266eb0-2a29-db56-aeaf-dd14dfcdbe66
* Version Independent ID: d7a1fa1d-c083-9232-2259-4f8b267c7ee3
* Content: [Send and receive messages with a bot - Teams](https://docs.microsoft.com/nl-nl/microsoftteams/platform/concepts/bots/bot-conversations/bots-conversations#sending-replies-to-messages)
* Content Source: [msteams-platform/concepts/bots/bot-conversations/bots-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/bots/bot-conversations/bots-conversations.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by billbliss** [comment]
Fixed and checked in a while ago.
