### ISSUE TITLE
The sidepanel app is not able to be displayed on in-meeting panel.

### ISSUE THREAD

**Issue by skeletonKim** [MicrosoftDocs/msteams-docs#2314]
Without any changes except ngrok endpoint, I have tried to access my SidePanel App in Teams, currently for testing by Devpreview manifest.json. 
This is for a feasibility check of displaying the app during the meeting. It was working well till last week. but suddenly it is not able to display anymore. I have not changed any configurations from last which was working well. 

I am attaching my manifest.json after removing confidential information. As a mention for referring, I have already set on Teams Admin, Activate Teams app > Setup policies > Upload custom apps. ( https://docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?tabs=json )

And Turned on Developer Preview of User Setting.
And Delete Teams cache data in %AppData%Microsoft / Reinstall App after uninstalling. - Not solved

The Same App is visible on ChannelTab, but not visible on the unified bar (u-bar) of in-meeting panel.

![image](https://user-images.githubusercontent.com/70251740/98621685-2aa66780-234b-11eb-9c5d-9eaab3acd6cd.png)

This image is the screenshot, succeeded last time.

![image](https://user-images.githubusercontent.com/70251740/98498109-4cd7b100-2289-11eb-8907-8353e9ce93e2.png)

1) Does the manifest loader in teams have any mechanism of internal cache? could you tell me how to initialize all cache data related side panel app?
2) In terms of the settings for activating Development preview, It seems to not have any omitted part. If it is not, Could you tell me any setting should be checked?
3) Is there any changes to the loading side panel in-meeting app?  

# manifest.json
```json
{
   "$schema": "https://raw.githubusercontent.com/OfficeDev/microsoft-teams-app-schema/preview/DevPreview/MicrosoftTeams.schema.json",
   "manifestVersion": "devPreview",
   "version": "1.0.0",
   "id": "aa32a7c1-45d5-455b-8752-882c58aa773c",
   "packageName": "demo.contoso.teams.extension",
   "developer": {
      "name": "skeletonKim",
      "websiteUrl": "https://45f3bbb9528c.ngrok.io",
      "privacyUrl": "https://45f3bbb9528c.ngrok.io/privacy",
      "termsOfUseUrl": "https://45f3bbb9528c.ngrok.io/termsofuse"
   },
   "icons": {
      "color": "color.png",
      "outline": "outline.png"
   },
   "name": {
      "short": "Demo App",
      "full": "Demo App"
   },
   "description": {
      "short": "Short description for Demo App.",
      "full": "Full description of Demo App for Microsoft Teams."
   },
   "accentColor": "#FFFFFF",
   "bots": [],
   "composeExtensions": [],
   "configurableTabs": [
      {
        "configurationUrl": "https://45f3bbb9528c.ngrok.io/config",
        "canUpdateConfiguration": true,
        "scopes": [
          "team",
          "groupchat"
        ],
        "context":[
          "channelTab",
          "privateChatTab",
          "meetingChatTab",
          "meetingDetailsTab",
          "meetingSidePanel"
       ]
     }
   ],
   "permissions": [
      "identity",
      "messageTeamMembers"
   ],
   "devicePermissions": [
      "media",
      "geolocation",
      "notifications",
      "midi",
      "openExternal"
   ],
   "validDomains": [ 
      "*.ngrok.io"
   ]
}
```

**Comment by Wajeed-msft** [comment]
Could you please check if Developer Preview is enabled? 
![image](https://user-images.githubusercontent.com/31851992/98805999-81409e00-243e-11eb-9c65-0a4f4750902e.png)

Check if opening Microsoft Teams web client with this URL works: https://teams.microsoft.com/_?ring=ring3_6

**Comment by skeletonKim** [comment]
Thank you for your comment. As I mentioned earlier, I have already set it as enabled. this comment -> <And Turned on Developer Preview of User Setting.>

![image](https://user-images.githubusercontent.com/70251740/98883766-19d42e00-24d2-11eb-9035-3cbdd0cfa2c4.png)

I have tested this again by the scaffolding demo code which is generated by Teams Toolkit Extension of Visual code, not my code is currently proceeding. It still remains the same.

**Comment by skeletonKim** [comment]
> Could you please check if Developer Preview is enabled?
> ![image](https://user-images.githubusercontent.com/31851992/98805999-81409e00-243e-11eb-9c65-0a4f4750902e.png)
> 
> Check if opening Microsoft Teams web client with this URL works: https://teams.microsoft.com/_?ring=ring3_6

I have looked into what it is a matter. The Teams might not detect the development preview accordingly even after setting the option as enabled. Could you tell me how to activate development preview mode, not by menu, by systematically and forcibly by the setting file or something?

**Comment by skeletonKim** [comment]
Obviously, This is a teams bug, regardless of the machine and OS, it is not able to activate meetingSidePanel app.
 
I have tested again using several version of windows 10 OS on Azure by after activating Developer Preview option of client side and Admin setting of developer tenant. But it can not activate in-meeting side panel app. I assumed at the beginning, It is caused by certain environment. But by test, this is not caused by OS and Machine, I can finalize the conclusion that it is caused by Teams Defect. 

Your team would need to go through the specific reason of this issue. If you need further, please escalate this issue to development team.

**Comment by Wajeed-msft** [comment]
@skeletonKim - I'll get engineering team involved for this.  Meanwhile could you please check if it's working in [development demo tenant](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/prepare-your-o365-tenant#just-need-a-development-environment)?

**Comment by skeletonKim** [comment]
> @skeletonKim - I'll get the engineering team involved for this. Meanwhile could you please check if it's working in [development demo tenant](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/prepare-your-o365-tenant#just-need-a-development-environment)?

Thank you for your response. I already set all as an activate like belows.

1) the user custom app policy
![image](https://user-images.githubusercontent.com/70251740/99338904-79627d00-28c8-11eb-91cd-757777ac1de7.png)

2)  the team custom app setting
![image](https://user-images.githubusercontent.com/70251740/99338970-9b5bff80-28c8-11eb-8648-0ed894763d91.png)

3)  the org-wide custom app setting
![image](https://user-images.githubusercontent.com/70251740/99339083-dc541400-28c8-11eb-8e7d-9042e7f9edc1.png)

**Comment by skeletonKim** [comment]
This issue is resolved by myself.
