### ISSUE TITLE
Document deeplink behavior in various contexts

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#2319]
Check the scenarios where deeplink launches browser first before navigating and document it.

**Ex:** 
**Adaptive card** 
1. 	Deeplink in card body  - Opens in browser first
2. 	Deeplink added to OpenURL action in Adaptive Card - Directly navigates to deeplink url

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45541337-ecd7-5cf6-cbe4-3f0d2f39aa79
* Version Independent ID: 6b4203f0-2844-06c9-eaa3-9cc03e6f76c0
* Content: [Create deep links - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links?view=msteams-client-js-latest)
* Content Source: [msteams-platform/concepts/build-and-test/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/build-and-test/deep-links.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Nikitha-MSFT** [comment]
**Tab**: Directly navigates to deeplink url
 **Bot**:

       Deeplink in card body - Opens in browser first
       Deeplink added to OpenURL action in Adaptive Card - Directly navigates to deeplink url

        Hyperlink markdown text in the card -  Opens in browser first
 
Text message hyperlink markdown : Directly navigates to deeplink url
**chat:**
        Link pasted in general chat conversation - Directly navigates to deeplink url
