### ISSUE TITLE
Audio Conferencing activation mail translation is terribly wrong

### ISSUE THREAD

**Issue by uguroz** [MicrosoftDocs/msteams-docs#2320]
The Turkish version of the Audio Conferencing activiation email that end users receive says "disabled" instead of "enabled" in Turkish.
The number format shown in the email is also wrong. It is currently -> +90 (21) 2290xsxv, it should be ->+90 (212) 290fxdfs

![audioconfmail](https://user-images.githubusercontent.com/74352771/98925226-c7e9d300-24e6-11eb-9649-5f746cb0b6ed.jpg)

**Comment by Abhijit-MSFT** [comment]
Thanks for reporting this issue. We are working on correcting this.

**Comment by uguroz** [comment]
Can you please let me know how it looks after you fix the translation?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by VaraPrasad-MSFT** [comment]
Our team is currently work on updating the docs and we don't have any ETA to share .

**Comment by uguroz** [comment]
Any updates on this?

Uğur Özmen
Technical Specialist | Microsoft Teams
uguroz@microsoft.com<mailto:uguroz@microsoft.com> | +905303981086 | +902123705615
[cid:image001.png@01D6D2CF.AF3A8700] Chat with me on Teams<https://teams.microsoft.com/l/chat/0/0?users=uguroz@microsoft.com>
What is new in Microsoft Teams – Ignite 2020?<https://techcommunity.microsoft.com/t5/microsoft-teams-blog/what-s-new-in-microsoft-teams-microsoft-ignite-2020/ba-p/1665600>

**Comment by VaraPrasad-MSFT** [comment]
We don't have any ETA to share.

**Comment by uguroz** [comment]
Any updates? This should not be that hard. We have thousands of users using this service and the activation mail they receive says “Disabled” instead of “Enabled”.
