### ISSUE TITLE
Way forward guidance for meeting extensibility apps - for fetching Teams roster

### ISSUE THREAD

**Issue by ismailMSFT** [MicrosoftDocs/msteams-docs#2322]
[Guidence for fetching Teams roster]
To fetch the Teams roster partners are adding bot in Team and group chat without any functionality/use case in the bot, we would like to have a guidence/note poit for partners that they can fetch the Teams roster from bot in group chat scope itself.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b60eeacc-a71e-9644-b869-3e0a4f1506d8
* Version Independent ID: 313bf83f-5325-f9f4-5780-9bc81e315c1e
* Content: [Create apps for teams meetings - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?tabs=json&source=docs)
* Content Source: [msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Trinetra-MSFT** [comment]
@ismailMSFT , To fetch the roaster in meeting chat you need to add the bot to meeting chat, once you initiate conversation by @mention Bot_Name you can use following piece of code to get the roaster in meeting chat.
```
 var members = new List<TeamsChannelAccount>();
            string continuationToken = null;

            do
            {
                var currentPage = await TeamsInfo.GetPagedMembersAsync(turnContext, 100, continuationToken, cancellationToken);
                continuationToken = currentPage.ContinuationToken;
                members.AddRange(currentPage.Members);
            }
            while (continuationToken != null);
```
![image](https://user-images.githubusercontent.com/50989436/99223011-b74c9c00-2809-11eb-97bb-eecfce3c988c.png)
