### ISSUE TITLE
Update guidance on anonymous user to highlight more what they do/don't have access to

### ISSUE THREAD

**Issue by islubin** [MicrosoftDocs/msteams-docs#2323]
Right now the language around anonymous user says they don't have access to the meeting window - we should be more descriptive about the fact that they can access Task Modules/AC if allowed by the organization.

**Comment by v-rodriguezd** [comment]
@islubin Hi Isabella for this issue in this document 
https://docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/teams-apps-in-meetings
Anonymous user description is provided as you have mentioned. Could you please provide more details on what needs to be added further.

**Comment by v-rodriguezd** [comment]
Linked to https://github.com/MicrosoftDocs/msteams-docs/pull/3065
