### ISSUE TITLE
404 page links.

### ISSUE THREAD

**Issue by DomWill** [MicrosoftDocs/msteams-docs#2327]
On page https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist#teams-app-validation-tool 

These links lead to 404 error pages:
- Teams Visual Studio Code toolkit
- App Studio

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3df9a819-4eb0-e650-ef6b-5eeaa265c317
* Version Independent ID: ed71ed64-970d-7820-4229-c1e6896a8896
* Content: [Submission checklist - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist#teams-app-validation-tool)
* Content Source: [msteams-platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Abhijit-MSFT** [comment]
@DomWill: Thanks for reporting this. We are working on correcting this.

**Comment by v-chetsh** [comment]
@DomWill - Looks like contents are already updated.
We are closing this issue for now, Please feel free to reopen it, if required.
