### ISSUE TITLE
Preview image not showing

### ISSUE THREAD

**Issue by seanpcook** [MicrosoftDocs/msteams-docs#2328]
![Image Preview Issue](https://user-images.githubusercontent.com/64341560/99104036-6c831800-25ae-11eb-979e-42d682f11ead.jpg)

I'm having issues getting the image preview to show. I've tried many different method and not sure if it is just a TTL issue.

**Comment by Abhijit-MSFT** [comment]
Is it only url which is not showing image or none of the images are coming up?
For me it worked: 
![image](https://user-images.githubusercontent.com/48427340/99251377-3dc9a380-2833-11eb-9f4e-901a065d89fd.png)

**Comment by seanpcook** [comment]
> Is it only url which is not showing image or none of the images are coming up?
> 
> For me it worked: 
> 
> ![image](https://user-images.githubusercontent.com/48427340/99251377-3dc9a380-2833-11eb-9f4e-901a065d89fd.png)
> 
> 

Thanks for looking into this. It must have been TTL because it is working for me now too! Seems to have taken over 24 hours as I checked multiple times.
