### ISSUE TITLE
How to format messages?

### ISSUE THREAD

**Issue by sengleson-r7** [MicrosoftDocs/msteams-docs#2329]
These docs are useless. I have no idea how to format text in messages sent through the Teams API. 

"Microsoft Teams supports a subset of Markdown and XML (HTML) formatting tags." 
Great! What Markdown expressions? Which HTML tags? How do I use them? Are there any examples?

Please advise.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b62aabd-f012-24c9-0edf-e840b20a9dfc
* Version Independent ID: a5c79257-d3a7-c9b5-8a98-7e1495b08a7e
* Content: [Format your bot messages - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/format-your-bot-messages)
* Content Source: [msteams-platform/bots/how-to/format-your-bot-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/bots/how-to/format-your-bot-messages.md)
* Product: **msteams**
* GitHub Login: @clearab
* Microsoft Alias: **anclear**

**Comment by Trinetra-MSFT** [comment]
@sengleson-r7 , You can use markdown tags for text messages as well as for cards. You can try following  code snippet for markdown formatting
`  protected override async Task OnMessageActivityAsync(ITurnContext<IMessageActivity> turnContext, CancellationToken cancellationToken)
        {
            _logger.LogInformation("OnMessageActivityAsync: start" + turnContext.Activity.Value.ToString());

            var replyText = $"echo: <h3>This is Header Text with </h3><strong>Bold</strong> and <em>italic</em> font with Ordered lilst <ol><li>ListValue1</li><li>ListValue2</li></ol> also it contains <strike>strikeText</strike> and <blockquote>Bltext</blockquote>";
            await turnContext.SendActivityAsync(MessageFactory.Text(replyText, replyText), cancellationToken);

        }`
Please see the attached screenshot
![image](https://user-images.githubusercontent.com/50989436/99211258-ed7c2280-27ed-11eb-8ac1-f0e7447d0fb3.png).

For more information how to use formatting in teams bot text messages please look at : [https://docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bots-text-formats](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bots-text-formats)

**Comment by clearab** [comment]
The tables on this page outline which formatting options are available, and which platforms they are supported on.

**Comment by Trinetra-MSFT** [comment]
@clearab , Text only message don't support table formatting this is a limitation. To see the support for individual platform here is the reference: [https://docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bots-text-formats#support-by-individual-platform](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bots-text-formats#support-by-individual-platform), Here is the [formatting cards with markdown](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?tabs=adaptive-md%2Cconnector-html#formatting-cards-with-markdown) but here also it is an limitation

**Comment by clearab** [comment]
I wasn't saying anything about support for tables in markdown, I was saying the tables on the documentation page outline what is supported. You shouldn't be linking to any of the bot v3 documentation for examples, that exists for legacy purposes only. If there is information on that page that is relevant, it should be moved to the current formatting documentation.

**Comment by Trinetra-MSFT** [comment]
@clearab , Yes, will ask laujan to put examples for text message formatting in current document as v3 doc have the examples which is not in out latest document. @laujan  can you help to update [Format your Bot message](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/format-your-bot-messages) document with examples for [text message formatting](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bots-text-formats#examples-of-text-formatting)
