### ISSUE TITLE
Powerpoint presentation via iOS bug discovered

### ISSUE THREAD

**Issue by SheidaBX** [MicrosoftDocs/msteams-docs#2330]
If the filename of a powerpoint-presentation on (saved on OneDrive) contains the Character "&" (and possibly more similar chars), users are met with an error message. The same file with the same filename on the same location can be presented on a Windows 10 PC though.

Thought Id share...

**Comment by Manish-MSFT** [comment]
We tried the same at our end, but it seems working on our device. Could you please let us know the name you are trying to provide. Thanks.

![image](https://user-images.githubusercontent.com/70321016/99512915-0d5b4400-29b0-11eb-9adc-6b563590b127.png)

**Comment by SheidaBX** [comment]
Hello!

Thanks for the quick reply.
Is your test file on OneDrive?

The top file on the list is the one, which didn’t work. The error message reads “The file couldn’t be shared – an error occurred while sharing the file. Please try again later.”

After deleting the “&-Symbol” it work on the clients side and also on my side… Meanwhile, other files, shared without a problem – although we didn’t try all other below listed pptxs.


[cid:image001.png@01D6BDB2.FEFFE5A0]

Mit freundlichen Grüßen

Makan Sheida

______________________________________________
Brillux GmbH & Co. KG
Makan Sheida
IT Systemadministration
Weseler Straße 401
48163 Münster
______________________________________________
https://www.brillux.de
m.sheida@brillux.de<mailto:m.sheida@brillux.de>
Tel. +49 251 7188-451<tel:+492517188-451>
Fax +49 251 7188-59838<tel:+492517188-59838>
______________________________________________
Brillux GmbH & Co. KG, Sitz Münster, AG Münster HR A 3194
P.h.G. Brillux GmbH, Sitz Münster, AG Münster HR B 4272
GF Peter König, Ulrike Nordemann, Michael Thompson
Von: Manish-MSFT <notifications@github.com>
Gesendet: Mittwoch, 18. November 2020 10:40
An: MicrosoftDocs/msteams-docs <msteams-docs@noreply.github.com>
Cc: Sheida, Makan <m.sheida@brillux.de>; Author <author@noreply.github.com>
Betreff: Re: [MicrosoftDocs/msteams-docs] Powerpoint presentation via iOS bug discovered (#2330)


We tried the same at our end, but it seems working on our device. Could you please let us know the name you are trying to provide. Thanks.

[image]<https://user-images.githubusercontent.com/70321016/99512915-0d5b4400-29b0-11eb-9adc-6b563590b127.png>

**Comment by Manish-MSFT** [comment]
@SheidaBX, I have hosted the file on one drive via MS Teams. Are you also facing the same issue with teams? or is it just related to One Drive.

**Comment by SheidaBX** [comment]
I tried both ways to be sure…

Testfile & 1.pptx went directly to OneDrive and provoked the error.
Testfile & 2.pptx was saved locally, uploaded via Teams into a Testteam and used in a 1:1 call – it also provoked the same error message.

After deleting the “&”-Symbol, it worked out immediately.
Out of curiousity I exchanged the “&-Symbol” for “%” and it still worked out. Renaming it back, and it didn’t.

Von: Manish-MSFT <notifications@github.com>
Gesendet: Donnerstag, 19. November 2020 05:33
An: MicrosoftDocs/msteams-docs <msteams-docs@noreply.github.com>
Cc: Sheida, Makan <m.sheida@brillux.de>; Mention <mention@noreply.github.com>
Betreff: Re: [MicrosoftDocs/msteams-docs] Powerpoint presentation via iOS bug discovered (#2330)


@SheidaBX<https://github.com/SheidaBX>, I have hosted the file on one drive via MS Teams. Are you also facing the same issue with teams? or is it just related to One Drive.

**Comment by Manish-MSFT** [comment]
Thanks @ShiedaBx. We are investigating this internally.

**Comment by Manish-MSFT** [comment]
@SheidaBX , On our side we see ppt appearing correctly. Which MS Teams version are you using? Could you please test it after updating teams desktop client.
