### ISSUE TITLE
[Teams app for Win10 - contacts]

### ISSUE THREAD

**Issue by Commander238** [MicrosoftDocs/msteams-docs#2334]
Hi,
I the Windows 10 teams app, there is a section called "Calls -> Contacts"
I can add some of my work colleagues from my team, but I cannot add some others.

The error box in the App is displayed in the right bottom corner of my screen:
"Cannot add to contacts / Cannot add everyone"

When I try the same in a browser, the error is
"2020-11-16T13:53:29.234Z call-list: addMembersToBuddyGroupWithEmail failed with error: BuddyListService: addMembersToBuddyGroupWithEmail - empty attributes for addMembersToBuddyGroupViaEmail, groupId RgAAAADZ-91r2UP6QbKOvYiy-p3UBwCyP9WzTCXiS40wtC0TiLOtAAEwrAATAACyP9WzTCXiS40wtC0TiLOtAAEwrA_BAAAA0, email length 0, contactDisplayName length 11 and mri 8:orgid:75df2d35-1804-4b3f-82de-2e6a1cd341b5 "

As we figured out, this happens with every person, which doesn't have the email field specified.

If it is possible, please enable adding team members without emails to contacts.
And otherwise, please display a clearer error message.

**Comment by Trinetra-MSFT** [comment]
@Commander238 , Does the member is in your org or an external user?

**Comment by Commander238** [comment]
Yes, he is in our organisation.

**Comment by Trinetra-MSFT** [comment]
@Commander238 : I tried to add some of member in same org but could not able to reproduce this. Could you please provide repro steps for this?

**Comment by Commander238** [comment]
- First to mention, I am not the admin of our organisation, I am a basic member. 
- I open the Teams window, click on "Calls" in the left bar, click on history.
- There I can see members of my team which I have had a voice call with today, including the person with the error.
- I hover over the person's avatar circle - now I can see his name, but the e-mail field is missing/empty.
- I click on the three dots on the right of the history table, a submenu opens. Then I click "Add to contacts". Nothing happens at all, the person is not added to my contact list, probably because of the empty e-mail field in his profile.
- When I click on another history item, another person, which has got the e-mail field in his profile filled, and then the same thing works alright.
- Both people work in our organization.
- I can try the same scenario in the browser version of MS Teams. There is the same error, but additionally, I can inspect the developer console output and I see the error:
"2020-11-16T13:53:29.234Z call-list: addMembersToBuddyGroupWithEmail failed with error: BuddyListService: addMembersToBuddyGroupWithEmail - empty attributes for addMembersToBuddyGroupViaEmail, groupId RgAAAADZ-91r2UP6QbKOvYiy-p3UBwCyP9WzTCXiS40wtC0TiLOtAAEwrAATAACyP9WzTCXiS40wtC0TiLOtAAEwrA_BAAAA0, email length 0, contactDisplayName length 11 and mri 8:orgid:75df2d35-1804-4b3f-82de-2e6a1cd341b5 "
- I believe, that adding a person to my contact list, or a quick dial, should be possible for every person in the history list, regardless whether he has got an email, or is an external person, or anything.
- If you watch the previous error closely, it is clear, that Teams is trying to add the contact "via email", which is clearly impossible in this case. But surely, the contact does have another id, which could be used to add him to my contact list. I can call him, so the contact makes sense even without an email field.

**Comment by Trinetra-MSFT** [comment]
@Commander238 , Yes , When I tried to add member from my call list history who was not a Guest it was working fine but I got error for Guest/External member when i tried to add contact. Let me confirm this with our engineering team
![image](https://user-images.githubusercontent.com/50989436/101140802-78a44780-3639-11eb-8088-e509cea33821.png)

**Comment by Commander238** [comment]
At my end, there is a slightly different error.
This happens in both the Teams app from windows store, and my internet browser (Opera 73.0).
![image](https://user-images.githubusercontent.com/1488749/101143321-03277f80-3617-11eb-9f59-535ccc94f283.png)
