### ISSUE TITLE
Broken link in messaging extensions docs.

### ISSUE THREAD

**Issue by alecclarke** [MicrosoftDocs/msteams-docs#2336]
> If you're using an existing registration, make sure you enable the Microsoft Teams channel.

The "enable the Microsoft Teams channel" link used in the above line from the ["Register your web service with the Bot Framework"](https://docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/create-messaging-extension#register-your-web-service-with-the-bot-framework) section is broken and returns a `404`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7074cb5d-e8e9-b2ae-94c4-478d463ea9ab
* Version Independent ID: 4aba1156-1b6c-d2aa-f110-d60bc641dc80
* Content: [Create a messaging extension using App Studio - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/create-messaging-extension)
* Content Source: [msteams-platform/messaging-extensions/how-to/create-messaging-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/messaging-extensions/how-to/create-messaging-extension.md)
* Product: **msteams**
* GitHub Login: @clearab
* Microsoft Alias: **anclear**

**Comment by Mahesh2516** [comment]
Closing the issue based on the confirmation received from SME on 01/22/2021. No changes are required.
