### ISSUE TITLE
can't open Powerapps in task module on Teams PC Client

### ISSUE THREAD

**Issue by chenxizhang** [MicrosoftDocs/msteams-docs#2338]
We have a Teams app, which have a feature to open a website (with AAD authentication) in a Task module, like a PowerApps app as below. 

https://apps.powerapps.com/play/0a71d7d0-5325-6898-afd2-4f3498d98bf6?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47

We found that it can works on Web and mobile device, but not able in the PC client. There will be a login page as below, and if I click the Sign in button it will open the external web browser, So I just can't use the PowerApps app in Teams.

![image](https://user-images.githubusercontent.com/1996954/99366089-1b975a80-28f3-11eb-82d5-1f4c45b4333e.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 501d3295-997c-d252-d458-534673b36a52
* Version Independent ID: c90dcc98-df65-b45b-4f78-64d2cab91852
* Content: [What are task modules? - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/what-are-task-modules)
* Content Source: [msteams-platform/task-modules-and-cards/what-are-task-modules.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/what-are-task-modules.md)
* Product: **msteams**
* GitHub Login: @clearab
* Microsoft Alias: **anclear**

**Comment by Trinetra-MSFT** [comment]
@chenxizhang , Did you added 
```
"webApplicationInfo": {
    "id": "YourAppId",
    "resource": "https://apps.powerapps.com"
  }
```

in your app manifest?
