### ISSUE TITLE
Broken link to : FrameContext interface

### ISSUE THREAD

**Issue by Josverl** [MicrosoftDocs/msteams-docs#2341]
Broken link in the below paragraph:

In the meeting as well as in all scenarios, the app will be rendered in an in-meeting tab that is 320px in width. Your tab must be optimized for this. See, **FrameContext interface**

broken link:  
https://docs.microsoft.com/en-us/javascript/api/@microsoft/teams-js/microsoftteams.framecontext?view=msteams-client-js-latest&preserve-view=true

I assume this is the intended target ?
https://docs.microsoft.com/en-us/javascript/api/@microsoft/teams-js/framecontext?view=msteams-client-js-latest

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b60eeacc-a71e-9644-b869-3e0a4f1506d8
* Version Independent ID: 313bf83f-5325-f9f4-5780-9bc81e315c1e
* Content: [Create apps for teams meetings - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?tabs=json)
* Content Source: [msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Trinetra-MSFT** [comment]
@laujan , Could you please help to update the broken link for [Frame Context Interface](https://docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?tabs=json#sidepanel) in following documentation
![image](https://user-images.githubusercontent.com/50989436/99480739-b2f5bf80-297e-11eb-92c7-328199ad1556.png):

Updated Link: [https://docs.microsoft.com/en-us/javascript/api/@microsoft/teams-js/framecontext?view=msteams-client-js-latest](https://docs.microsoft.com/en-us/javascript/api/@microsoft/teams-js/framecontext?view=msteams-client-js-latest)
