### ISSUE TITLE
Personal bot for Static tab

### ISSUE THREAD

**Issue by ghantasalaphanidhar** [MicrosoftDocs/msteams-docs#2346]
[Enter feedback here]
Section: Tab Design Best practices

To improve the user experience please include a personal bot that sends a welcome message to the user on first run and responds to the ‘hi’, ‘help’, and ‘hello’ commands in addition to personal tab.

Please refer to the documentation on welcome messages at https://docs.microsoft.com/en-us/microsoftteams/platform/bots/what-are-bots#in-a-one-to-one-chat

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3dd35a9c-c868-a7b9-825a-4be9419539d7
* Version Independent ID: 814c8be1-eae8-7316-8553-283ef07ffc09
* Content: [Design guidelines for tabs - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/design/tabs#tab-design-best-practices)
* Content Source: [msteams-platform/tabs/design/tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tabs/design/tabs.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by RamaMohanaChary** [comment]
@ghantasalaphanidhar:

Could you please describe your use case briefly. This will help us to resolve your issue quickly.
