### ISSUE TITLE
Category mapping guidance

### ISSUE THREAD

**Issue by ghantasalaphanidhar** [MicrosoftDocs/msteams-docs#2347]
[Enter feedback here]
Link to App Category mapping below the partner Center FAQ.

Link to Existing content: https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases#app-category-mapping

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f071593-9440-5115-242d-488cf25e9256
* Version Independent ID: 746b1c6e-1bcc-21fe-e2be-149e7c10f1d5
* Content: [Microsoft Teams app approval submission process guidance - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/publish)
* Content Source: [msteams-platform/concepts/deploy-and-publish/appsource/publish.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/deploy-and-publish/appsource/publish.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Trinetra-MSFT** [comment]
@ghantasalaphanidhar , Do you want this link to be added in [Microsoft Teams app approval submission process guidance](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/publish) page?
