### ISSUE TITLE
MPN ID related questions

### ISSUE THREAD

**Issue by ghantasalaphanidhar** [MicrosoftDocs/msteams-docs#2348]
[Enter feedback here]

Under Tips, need to add a DL where queries related to MPN ID can be routed.

For queries related to MPN, could you please ask partner to reach out to QQTAVMPN@microsoft.com . They will provide the required assistance.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa28e49e-3a76-729b-b1f6-d1bcb39f26aa
* Version Independent ID: 907f0205-82bf-846b-0243-6b3b311ee747
* Content: [App manifest checklist - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/app-manifest-checklist)
* Content Source: [msteams-platform/concepts/deploy-and-publish/appsource/prepare/app-manifest-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/deploy-and-publish/appsource/prepare/app-manifest-checklist.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Manish-MSFT** [comment]
Thanks for for bringing corrections to us, We are investigating this internally.
