### ISSUE TITLE
Error adding Hello World sample app to a Team

### ISSUE THREAD

**Issue by jmpatrao** [MicrosoftDocs/msteams-docs#2349]
I followed the tutorial and got the sample app installed and working.

However, I cannot add the sample app to a team: the _configure_ page is not displayed, and I get an error on Teams:
"There was a problem reaching this app"

![image](https://user-images.githubusercontent.com/51779667/99654056-b9a13700-2a51-11eb-8ca3-4ac5806b186c.png)

However, I can see on the logs the app being called:
`at=info method=GET path="/configure" host=<host> request_id=<id> fwd="<ip>" dyno=web.1 connect=0ms service=3ms status=200 bytes=1314 protocol=https`

And, if I open the page on a web browser, it is correctly presented:
![image](https://user-images.githubusercontent.com/51779667/99654115-ca51ad00-2a51-11eb-8ac2-1adf644f79c8.png)

Note: I am serving the app from Heroku.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4fa27cb-544f-f8a2-97a7-4b31528c1b80
* Version Independent ID: fa69cd6f-1ef4-706d-2816-aa709714b0aa
* Content: [Get started with App Studio and Node.js - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tutorials/get-started-nodejs-app-studio)
* Content Source: [msteams-platform/tutorials/get-started-nodejs-app-studio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tutorials/get-started-nodejs-app-studio.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Nikitha-MSFT** [comment]
Did you add the URL to the valid domain? Could you please check?

**Comment by jmpatrao** [comment]
Hi Nikita,

Thank you for the prompt response.

Yes, the valid domains are configured (it's actually just 1 domain).

Everything works (sort of) fine:
* It displays the "Hello" tab, with the proper content
* I can send messages and receive the _echo_
* (Commands are not working, they are being interpreted as messages, but that is a separate issue)

And I can see on the logs that Teams is invoking the _configure_ URL on my app when I try to add it to a team.

Thank you!

**Comment by Nikitha-MSFT** [comment]
Could you please try by uninstalling all the instances of the app and reinstall the app? Try if that helps.
