### ISSUE TITLE
Donel Adams/Donadamassociates

### ISSUE THREAD

**Issue by donadam2015** [MicrosoftDocs/msteams-docs#235]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80613718-e11b-2d15-853a-9fe3aa9c01d1
* Version Independent ID: ec71ec7c-d4ef-e9fe-c9f1-60b1242b5420
* Content: [Package your app - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/apps/apps-package)
* Content Source: [msteams-platform/concepts/apps/apps-package.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/apps/apps-package.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by billbliss** [comment]
Reopen with real text if there is an issue.
