### ISSUE TITLE
Further detail the documentation

### ISSUE THREAD

**Issue by GitDruid** [MicrosoftDocs/msteams-docs#2351]
Following some feedback after a first look at the documentation after the update on 11/04/2020:

1) Both links "Get your Azure AD Application ID" and "Grant permissions for Teams" refer to a "Create service principal" page.
The page include a lot of things like "Service principal creation", "Roles assignment", "Access policies"...  
Are they really required? If no, it is possible to have a more focused documentation of the steps?

2) There is a "YourBotId" that I suppose refers to the Azure AD AppId. Is it correct?

3) It's not clear how this procedure relates to the procedure detailed [here ](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-authentication?view=azure-bot-service-4.0&tabs=aadv2%2Ccsharp) (that, I think, many users have already in place for bots sso).  
Is it possible to have a review of the doc to make uniform procedures and naming between the two documentation? 

4) Should the "access_as_user" scope be for "Admins and user" or "Admins only" ? 

5) Step 4 of "Create an Azure account" contains this sentence: "Pre-authorize Teams by selecting the Add a scope button". 
How Pre-authorize is related to the "Add scope" feature? Should "Add a client app" be used instead?
If so, do we need 3 entries with the Application ID of Teams desktop, Teams web, and Teams mobile?

6) Is "Implicit grant" required in the AAD app?

7) Regarding the OAuthCard, what's the meaning of "For the Teams channel we honor only the Id property, which uniquely identifies a token request."? It's not clear if the `OAuthPrompt` or the `MultiProviderAuthDialog` of the botframework will work for the purpose of the SSO or not.
  
8) Regarding the "Receiving the token" section, what code is supposed to be in place? I'm using a `TeamsActivityHandler` and there is no `OnInvokeActivity` method to override. There is `OnInvokeActivityAsync` instead. Also no `OnTokenResponse` available. There is a `OnTokenResponseEventAsync` with different signature instead. 
  
9) All the 3 links in the "Additional code samples" section do not work.
[C# sample using the Bot Framework SDK.](https://microsoft-my.sharepoint-df.com/:u:/p/vul/ETZQfeTViDlCv-frjgTIincB7dvk2HOnma1TLvcoeGGIxg?e=uPq62c)
[C# sample using the Bot Framework SDK to deduplicate the token request.](https://microsoft.sharepoint.com/:u:/t/ExtensibilityandFundamentals/Ea36rUGiN1BGt1RiLOb-mY8BGMF8NwPtronYGym0sCGOTw?e=4bB682)
[C# sample without using the Bot Framework SDK token store](https://microsoft-my.sharepoint-df.com/:u:/p/tac/EceKDXrkMn5AuGbh6iGid8ABKEVQ6hkxArxK1y7-M8OVPw)

10) Embedded images are way too small.

Please, can you make the documentation more straightforward and effective?

Thanks,
Alessandro.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9549caa9-99a2-2568-19a5-f21a79292e2f
* Version Independent ID: f2100d03-b88a-34b2-44a2-935231e89db0
* Content: [Single sign-on support for bots - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/authentication/auth-aad-sso-bots)
* Content Source: [msteams-platform/bots/how-to/authentication/auth-aad-sso-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/bots/how-to/authentication/auth-aad-sso-bots.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Manish-MSFT** [comment]
Hi @GitDruid, Thanks for the corrections. We will be making necessary changes.
