### ISSUE TITLE
Document that the auth popup can be sized by including width and height query string parameters

### ISSUE THREAD

**Issue by aosolis** [MicrosoftDocs/msteams-docs#2354]
Document that the size of the auth popup trigged by the ME can be controlled by including width and height query string parameters

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 503e124f-2b80-d6ae-581a-ca77f0a1999f
* Version Independent ID: 66d2bd8a-536b-1a45-f71c-eb2a0199de46
* Content: [Add authentication to your messaging extension - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/add-authentication)
* Content Source: [msteams-platform/messaging-extensions/how-to/add-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/messaging-extensions/how-to/add-authentication.md)
* Product: **msteams**
* GitHub Login: @clearab
* Microsoft Alias: **anclear**

**Comment by Manish-MSFT** [comment]
@aosolis , We will be updating it in documentation.

**Comment by Manish-MSFT** [comment]
@aosolis , I just tried to reference the sample given [here](https://github.com/microsoft/BotBuilder-Samples/blob/main/samples/csharp_dotnetcore/52.teams-messaging-extensions-search-auth-config/Bots/TeamsMessagingExtensionsSearchAuthConfigBot.cs#L57) for authentication, and I see that I can't add height and width property could you please let us know how and where to define. Sorry, if I am missing anything in this process.

**Comment by aosolis** [comment]
Value = $"{_siteUrl}/searchSettings.html?settings={escapedSettings}",
height and width can be provided as query string parameters here
