### ISSUE TITLE
Initial task invoke payload sets `channelData.team.id` and `channelData.channel.id` with the same value

### ISSUE THREAD

**Issue by alecclarke** [MicrosoftDocs/msteams-docs#2355]
From the documentation it looks like the task payload should contain the "channel id" and "teams id"  in `channelData.channel.id` and `channelData.team.id`, respectively. However, they payload I'm getting is in including the same id in both fields (I believe it's the channel id).

Is this what's expected? I assumed the values would be different and that `channelData.team.id` would include the id of the channel's team.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e04556b-f4b1-316e-bac1-ca77c6ab287f
* Version Independent ID: 2ee29289-b250-4ba3-e957-7a42122a266e
* Content: [Create and send the task module - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/action-commands/create-task-module?tabs=dotnet)
* Content Source: [msteams-platform/messaging-extensions/how-to/action-commands/create-task-module.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/messaging-extensions/how-to/action-commands/create-task-module.md)
* Product: **msteams**
* GitHub Login: @clearab
* Microsoft Alias: **anclear**

**Comment by clearab** [comment]
The channelId of the general (default) channel is the same as the Team Id. If you run this in a different channel do you get different values?

**Comment by alecclarke** [comment]
Ah, ok. When the payload was sent from a non-general channel the ids were different.

Thanks for the clarification!
