### ISSUE TITLE
Blank page

### ISSUE THREAD

**Issue by stuartridout** [MicrosoftDocs/msteams-docs#2356]
I've followed the steps to the letter and have just got a blank page.  I can't see where I've gone wrong.

How can I get help on this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f876156-cc1e-468f-4647-5143a5de03b1
* Version Independent ID: 618f43a3-3371-ad99-13aa-087b9303298c
* Content: [Get started - Build and run your first app - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/build-your-first-app/build-and-run)
* Content Source: [msteams-platform/build-your-first-app/build-and-run.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/build-your-first-app/build-and-run.md)
* Product: **msteams**
* GitHub Login: @heath-hamilton
* Microsoft Alias: **lajanuar**

**Comment by RamaMohanaChary** [comment]
@stuartridout: Are you trying to create a Tab in your Teams App, ie showing as a blank? if yes i think you need to add your domain in valid domain list in manifest.

**Comment by stuartridout** [comment]
I think I may have sorted it.  It wasn't showing in Edge but did in Chrome.
