### ISSUE TITLE
Where do we get the Teams user id?

### ISSUE THREAD

**Issue by pkg01** [MicrosoftDocs/msteams-docs#2360]
_The mention object inside of an msteams property in the card content, which includes the **Teams user id** of the user being mentioned_

Where do we get the **Teams user id**?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 001a12ea-30fa-d626-18a9-02a518bfb37f
* Version Independent ID: e5f5f69e-66e9-d1b2-e19a-485d0ffcd6fa
* Content: [Text formatting in cards - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?tabs=adaptive-md%2Cconnector-html)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-format.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-format.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by VaraPrasad-MSFT** [comment]
You can get the user id by two ways:
Get user id by using bot: When you receive the bot event you will receive the user id in turcontext.activity.from.id.
get user id using graph API: Could you please check get user [API](https://github.com/MicrosoftDocs/msteams-docs/issues/2360)

**Comment by pkg01** [comment]
Looks like the link you have given for the API above is referring to this page back. Can you please give me the correct link?

**Comment by VaraPrasad-MSFT** [comment]
here is the link for Graph API to [Get User](https://docs.microsoft.com/en-us/graph/api/user-get?view=graph-rest-1.0&tabs=http) and [List Users](https://docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&tabs=http)

**Comment by phoenixfangor** [comment]
I've tried several variations, but none of the combinations seem to notify the user. What exactly should the ID comprise of?

**Comment by Trinetra-MSFT** [comment]
@pkg01 , @mention user id comes under the entities of `turnContext `activity of Bot, if you are looking for `@mention` a user through Bot, you can refer to the following [Outgoing message with user mentioned](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bot-conversations/bots-conv-channel#example-outgoing-message-with-user-mentioned), You need to check the entities object which have Teams user mentioned id. let me know if you are looking for the same or something else

**Comment by pkg01** [comment]
Thanks for your response @Trinetra-MSFT!
I am looking for `@mention` a user. My question was regarding the Id of the user. Where do we get the if from as shown in the document you have listed. as @phoenixfangor also mentioned I have also tried different combinations but non of them work.

**Comment by Trinetra-MSFT** [comment]
@pkg01 @phoenixfangor , When you tied to `@mention` a user in teams channel, you need to fetch the members from the channel also there` IList<TeamsChannelAccount> members`  which maintains the id of each user who is part of that channel,
 You can fetch the members using below code snippet 

  ```
  MicrosoftAppCredentials.TrustServiceUrl(_config["ServiceUrl"]);
    using var connector = new ConnectorClient(new Uri(_config["ServiceUrl"]), _config["MicrosoftAppId"], _config["MicrosoftAppPassword"]);
    var members = await GetMembers(connector, _config["TeamConversationId"]);
```
You can get the user id from the channel account it also contains the userPrincipleName for that member
if you want to @mention member in that channel you can use below code snippet as well
get the user id from channel account members details
pass it the parameters
```
 var parameters = new ConversationParameters
            {
                Members = new ChannelAccount[] { new ChannelAccount(userId) },
                ChannelData = new TeamsChannelData
                {
                    Tenant = new TenantInfo(tenantId),
                    Notification = new NotificationInfo() { Alert = true }
                }
            };
              var conversation= await connectorClient.Conversations.CreateConversationAsync(parameters);
                var reply = Activity.CreateMessageActivity();
                reply.Conversation = new ConversationAccount(id: conversation.Id.ToString());
                reply.ChannelData = new TeamsChannelData() { Notification = new NotificationInfo(true) };
                reply.Text="Hi this is @mention user in channel";

                var resourceResponse = await connectorClient.Conversations.SendToConversationAsync(conversationResource.Id, (Activity)reply);
```

**Comment by phoenixfangor** [comment]
> @pkg01 @phoenixfangor , When you tied to `@mention` a user in teams channel, you need to fetch the members from the channel also there` IList<TeamsChannelAccount> members` which maintains the id of each user who is part of that channel,
> You can fetch the members using below code snippet
> 
> ```
> MicrosoftAppCredentials.TrustServiceUrl(_config["ServiceUrl"]);
>   using var connector = new ConnectorClient(new Uri(_config["ServiceUrl"]), _config["MicrosoftAppId"], _config["MicrosoftAppPassword"]);
>   var members = await GetMembers(connector, _config["TeamConversationId"]);
> ```
> 
> You can get the user id from the channel account it also contains the userPrincipleName for that member
> if you want to @mention member in that channel you can use below code snippet as well
> get the user id from channel account members details
> pass it the parameters
> 
> ```
>  var parameters = new ConversationParameters
>             {
>                 Members = new ChannelAccount[] { new ChannelAccount(userId) },
>                 ChannelData = new TeamsChannelData
>                 {
>                     Tenant = new TenantInfo(tenantId),
>                     Notification = new NotificationInfo() { Alert = true }
>                 }
>             };
>               var conversation= await connectorClient.Conversations.CreateConversationAsync(parameters);
>                 var reply = Activity.CreateMessageActivity();
>                 reply.Conversation = new ConversationAccount(id: conversation.Id.ToString());
>                 reply.ChannelData = new TeamsChannelData() { Notification = new NotificationInfo(true) };
>                 reply.Text="Hi this is @mention user in channel";
> 
>                 var resourceResponse = await connectorClient.Conversations.SendToConversationAsync(conversationResource.Id, (Activity)reply);
> ```

Is this mentioned anywhere in the documentation? If not, it's definitely a crucial piece of information that's missing.

**Comment by Trinetra-MSFT** [comment]
Sure will try to fix the document for this, I will check with document team to get it fixed

**Comment by dgajendr** [comment]
@Trinetra-MSFT The documentation is not yet fixed. And is there anyways to get this user_id through powershell teams module commands? I am not familiar with JS.

**Comment by zaneobrien** [comment]
@Trinetra-MSFT Did you end up checking with the document team?

**Comment by Trinetra-MSFT** [comment]
@zaneobrien , Document Team have this update in their list of tasks, this will be updated soon.

**Comment by Wajeed-msft** [comment]
@KirtiPereira  - could you please add following point under [constructing mentions](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?tabs=adaptive-md%2Cconnector-html#constructing-mentions) section. 
 
The `userId` is unique to your bot ID and a particular user which is used to @mention a particular user.  It can be retrieved using one of the option mentioned in [Get the user ID](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/send-proactive-messages?tabs=dotnet#get-the-user-id-team-id-or-channel-id).
