### ISSUE TITLE
Messaging extensions are not available in a meeting and chats if there are federated users

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#2362]
**Issue:**
If a meeting or group chat has federated users in the roster, Teams suppresses access to messaging extensions for all users, including the organizer.

**Workaround:**
None

**Internal Bug Tracker**: [1347603](https://domoreexp.visualstudio.com/MSTeams/_workitems/edit/1347603)

Please continue to follow this issue for updates/progress/questions.

**Comment by Wajeed-msft** [comment]
This is by design and we have backlog feature request to track the work needed to support this.

**Comment by RamaMohanaChary** [comment]
This isn't a bug as federated environments were never supported on platform. 
It's a feature requests.

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.
