### ISSUE TITLE
Add SidePane Tab in and adhoc meeting

### ISSUE THREAD

**Issue by mwerghemmi** [MicrosoftDocs/msteams-docs#2364]
Hi,

Are there any way to add a sidePane tab in adhoc meeting.
We tested, for a scheduled meeting, when we add the app in the pre-meeting stage, the app icon is displayed on the U-bar.

Are there a way to do this for adhoc/instant meetings, or in general any way to add by default an app to any meeting where a given user is involved for example ?

Thx

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82987815-d508-d642-c1f6-b609241d4750
* Version Independent ID: 29e89cc6-c8ca-7d29-7dca-4ac4d06f5c42
* Content: [Apps in teams meetings - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/teams-apps-in-meetings)
* Content Source: [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Mallipriya-MSFT** [comment]
@mwerghemmi, 
No. We have only shipped meeting extensibility for private scheduled meetings.

**Comment by Wajeed-msft** [comment]
Add note that "Apps are supported only in private scheduled meetings"
