### ISSUE TITLE
Send viewers of the page to the Postman how to link

### ISSUE THREAD

**Issue by robroyle427** [MicrosoftDocs/msteams-docs#2366]
While reading the article it states to
3. Test your adaptive card with Postman

You can test your adaptive card using **Postman** to send a POST request to the URL that you created when you setup your incoming webhook. Paste your JSON file in the body of the request and view your adaptive card message in Teams.
That link takes you to the Postman main page. Could you please add a note that send the viewers to the How to page something like https://www.guru99.com/postman-tutorial.html.  It spend about 40 minutes looking around on how to use postman page, in addition to having to create an account to use the page.  It also doesn't state that you have to use the Postman agent, which is a plug in to the browser.  I just think it would be more helpful to set the expectation of what the user is expected to do to test their adaptive cards.  Thank you for your consideration.

**Comment by Manish-MSFT** [comment]
Hi @robroyle427, The document intentionally refers to postman as API tool and assumes developer has knowledge about these tools.
