### ISSUE TITLE
Handle "User is typing" activity on MS Teams

### ISSUE THREAD

**Issue by tannguyen3** [MicrosoftDocs/msteams-docs#2376]
Hi team,
On MS Teams, can we handle the "User is typing" activity? If not, do we have plan to do it.
I see the activity is available in the [Bot Framework SDK 4.0](https://docs.microsoft.com/en-us/dotnet/api/microsoft.bot.schema.activitytypes.typing?view=botbuilder-dotnet-stable)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9da6a6eb-8756-fffd-ecc3-07cde897e709
* Version Independent ID: 72686dc8-d677-9b8d-2405-7684d537a100
* Content: [Handle bot events - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bots-notifications)
* Content Source: [msteams-platform/resources/bot-v3/bots-notifications.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/resources/bot-v3/bots-notifications.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by VaraPrasad-MSFT** [comment]
Hi @tannguyen3 :
You can implement the typing activity in teams, Could you please check the below code

```
var typingActivity = MessageFactory.Text(string.Empty);
typingActivity.Type = ActivityTypes.Typing;
await turnContext.SendActivityAsync(typingActivity);
```

**Comment by tannguyen3** [comment]
No, I don't want to send typing signal to user. But want bot to handle event that user is typing and react to it.

**Comment by VaraPrasad-MSFT** [comment]
Currently there is no event to know the user activity, Could you please raise a [user voice](url
![Uploading image.png…]()
).
