### ISSUE TITLE
Teams needs to support Enterprise-class management

### ISSUE THREAD

**Issue by KyleSchroeder** [MicrosoftDocs/msteams-docs#238]
The current state of Teams makes it feel much like Slack (installing in user-space, autoupdating, etc).  This if fine for a consumer product. But to really make inroads into the enterprise, and especially supplant Skype as the IM platform, you MUST have enterprise manageability.  Such "simple" things as:

1. GPO support to  configure various Teams options (default team/tenant, etc)
2. True enterprise configuration/deployment (i.e. system-level installation vs. user mode)
3. Ability to create a firewall exception to prevent the Windows FW warning when making a call - apparently it is not possible to do so using %localappdata% as a source, since that doesn't resolve properly at the system level.

**Comment by billbliss** [comment]
Are you writing applications for Microsoft Teams? That's what this documentation is for. If you are more interested in feedback for features and functionality for IT admins (all three of your questions above are in that category, you'd be better off posting questions here: https://docs.microsoft.com/en-us/MicrosoftTeams/Microsoft-Teams. 

That said, with respect to #2, I can point you to https://docs.microsoft.com/en-us/MicrosoftTeams/msi-deployment (sounds like what you're looking for) and (to a lesser extent) https://docs.microsoft.com/en-us/MicrosoftTeams/get-clients (which also mentions #3 but not a way to prevent it). 

If I get more information on #1 and #3 I'll post here.

**Comment by KyleSchroeder** [comment]
Thanks for the feedback and additional links Bill.  I just spent about 10 minutes reading all the responses on the msi-deployment link; there are a lot of admins there with similar concerns, including one (not sure if it is resolved yet) that allows members of the USERS group to WRITE to the C:\ProgramData\Microsoft\Teams.\update.exe file, potentially installing MALWARE for any user who logs in?  There is something to be said for doing things "the new way", and I'm fine with that...but if you're deploying in an Enterprise (and the intent is to replace Skype with Teams), as an IT Admin I expect that the software will respect Enterprise management standards and security standards.

What happens for example if a new teams.exe launches tomorrow, is deployed broadly to 14,000 (or, 100,000, or what have you) machines in my environment, and then we find out that due to either a bug or behavior change that my entire fleet can now not connect and/or if we're reliant on some functionality that updates without any notice?  There needs to be some way to control the update process, and/or allow update testing "rings" the same as the rest of the O365 suite (C2R deployment style).  Is there an "Insider" update mechanism to allow for pre-release testing by IT teams?  I'm sure (at least, I hope) that Teams utilizes the same or a similar "throttled" update mechanism as C2R O365 clients or OneDrive, whereby Microsoft can trickle out the updates over time...if not you may want to discuss with that Product team about implementing the same for Teams.

**Comment by billbliss** [comment]
Ping to refresh thread

**Comment by brandber** [comment]
Thank you for raising this feedback!

I'm happy to follow-up w/ the appropriate teams on **2** and **3** above. Additional detail would be helpful on specifics controls that would be contained in the GPO.

The best way to share product feedback of this type is to submit/up-vote feedback items via [uservoice](https://microsoftteams.uservoice.com). We actively monitor this forum, which influences how we prioritize new feature requests. If you haven't done so, kindly up-vote the following feedback items below:

[Install in Program Files directory](https://microsoftteams.uservoice.com/forums/555103-public/suggestions/33853318-install-in-program-files-directory)
[Let Admins manage updates](https://microsoftteams.uservoice.com/forums/555103-public/suggestions/18738943-let-admins-manage-updates)
[Microsoft Teams Windows Firewall pop-up](https://microsoftteams.uservoice.com/forums/555103-public/suggestions/33697582-microsoft-teams-windows-firewall-pop-up)

Once I close the loop with the teams, we'll get the status updated on these user voice items. If you have any additional questions or concerns around your feedback, please feel free to reach out. Happy to continue the conversation.

Thanks again!

**Comment by CIGAdmin** [comment]
Microsoft finally made it enterprise-friendly. I have the full Remote Desktop Server package (RDG, RDCB, RDSH), including User Profile Disk (UPD) and Software Restriction Policies (SRP) yet I got this to work today with the enterprise-friendly installation. You can read about it at https://docs.microsoft.com/en-us/microsoftteams/teams-for-vdi. There are a few items to tweak, though:

1. Installation will fail unless you create a registry key, if one doesn't already exists, for either:
a. HKLM\SOFTWARE\VMware, Inc.\VMware VDM\Agent, or
b. HKLM\Software\Citrix\PortICA

If you do not want to auto-start this for everyone (I had another group that doesn't use it at all and it annoys them every time they log in):

2. After installation, delete the registry value Teams from HKLM\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Run. Do not delete the other two TeamsMachineUninstaller* values.

3. If the user wants it to auto-start (unfortunately, Teams didn't have its own auto-start option), do these:
a. Right-click Start Menu (Windows logo key) and select "Run".
b. Enter "shell:startup" and press Enter. This opens up you your Startup folder.
c. Click Start Menu, scroll down to Microsoft Corporation, drag Teams to your Startup folder.

Enjoy!
