### ISSUE TITLE
Documentation still not fully clear

### ISSUE THREAD

**Issue by GitDruid** [MicrosoftDocs/msteams-docs#2380]
Thanks for the release of #2373 but some points of #2351 are still not fixed:

1) Under the "Create an Azure account" paragraph, may you detail how to "Get your Azure AD Application ID" and how to "Grant permissions for Teams"?
May you add an example?

5) Step 4 of "Create an Azure account" is still confusing. "Add a client app by selecting the Add a scope button" should be split in two steps: one to add the scope and one to add the client apps (that should contain the AppId of Teams for Desktop and Teams for web.

8) As written before, `OnTokenResponseEventAsync` has a different signature that accepts `ITurnContext<IEventActivity>` so the documented code, that is passing a `ITurnContext<IInvokeActivity>`, is not working.
Did you tested the code? Which botframework are you using?

9) None of the three links in "Additional code samples" are working.
Did you tested them? Are they working for you?

10) Embedded images are way too small.

---

Hi @GitDruid, Thanks for the corrections. We will be making necessary changes.

_Originally posted by @Manish-MSFT in https://github.com/MicrosoftDocs/msteams-docs/issues/2351#issuecomment-732032592_

**Comment by Wajeed-msft** [comment]
@Trinetra-MSFT - Could you help @GitDruid here with issue while SSO?

**Comment by Manish-MSFT** [comment]
@GitDruid  :Are you still facing issue with SSO?

**Comment by v-rodriguezd** [comment]
@GitDruid could you please elaborate what needs to be added as per this comment "Under the "Create an Azure account" paragraph, may you detail how to "Get your Azure AD Application ID" and how to "Grant permissions for Teams"?" as the link and example is already provided to the pages https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-create-service-principal-portal#get-values-for-signing-in. I can correct the location of the first link if that's what you are referring to?

**Comment by GitDruid** [comment]
Hi @v-rodriguezd,

My existing solution was put in place following [this documentation](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-authentication?view=azure-bot-service-4.0&tabs=aadv2%2Ccsharp), where the steps were just 4:

- Create the Azure bot registration
- Create the Azure AD identity provider
- Register the Azure AD identity provider with the bot using OAuth Connection Settings
- Set the bot's app ID and password in the bot code

There was no need for create service principal, assign a role to the application, configure access policies on resources and so on. 
So linking to [this page](https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-create-service-principal-portal#get-values-for-signing-in) seems a little misleading. It is not clear if all those steps are really required or not.  
And, also, that link contains no reference/example regarding Teams. So it's not clear why it should be useful under the link "Grant permissions for Teams".

Ciao,
Alessandro.

**Comment by GitDruid** [comment]
> @GitDruid :Are you still facing issue with SSO?

Hi @Manish-MSFT, actually I suspended the SSO implementation, waiting for the final version of the documentation.

**Comment by v-rodriguezd** [comment]
Hi @GitDruid Thank you for your response. Should I make these changes in the "Create an Azure account" section" instead of the link?
This step is similar to the tab SSO flow:
1. Create the Azure bot registration
2. Create the Azure AD identity provider
3. Register the Azure AD identity provider with the bot
4. Prepare the bot code
5. Specify the permissions that your application needs for the Azure AD endpoint and, optionally, Microsoft Graph.
6. Grant permissions for Teams desktop, web, and mobile applications.
7. Add a scope by selecting the Add a scope button.
8. In the panel that opens, add a client app by entering access_as_user as the Scope name.

**Comment by GitDruid** [comment]
I think documentation should contains all the steps, details and samples to make it a no-brainer to configure the SSO for a bot in Teams.
My feedback is that the procedure at the moment seems not so straightforward.

**Comment by v-rodriguezd** [comment]
> I think documentation should contains all the steps, details and samples to make it a no-brainer to configure the SSO for a bot in Teams.
> My feedback is that the procedure at the moment seems not so straightforward.

Thank you for your feedback. Will incorporate changes as soon as I get the screenshots and hyperlinks that need to be updated.

**Comment by Trinetra-MSFT** [comment]
@GitDruid , If you are specifically looking for implementing SSO for Tabs in your app, You can reach out to `microsoftteamsdev@microsoft.com` for further discussion, we will be happy to help you out in that

**Comment by GitDruid** [comment]
> @GitDruid , If you are specifically looking for implementing SSO for Tabs in your app, You can reach out to `microsoftteamsdev@microsoft.com` for further discussion, we will be happy to help you out in that

Thanks a lot @Trinetra-MSFT. Actually I'm focused on bots. "Normal" apps in Tabs are managed by my colleagues. I will forward the email to them. Could I write to that email also for bot sso?

**Comment by Abhijit-MSFT** [comment]
> > @GitDruid , If you are specifically looking for implementing SSO for Tabs in your app, You can reach out to `microsoftteamsdev@microsoft.com` for further discussion, we will be happy to help you out in that
> 
> Thanks a lot @Trinetra-MSFT. Actually I'm focused on bots. "Normal" apps in Tabs are managed by my colleagues. I will forward the email to them. Could I write to that email also for bot sso?

@GitDruid, Yes, You can write about any challenges you are facing to develop the app.
