### ISSUE TITLE
Chat tab is disappeared after clicking on the Adaptive card button

### ISSUE THREAD

**Issue by savissamsetti** [MicrosoftDocs/msteams-docs#2386]
We have developed a chatbot service. As part of the service it will return the cards for the given search text of the user. You can refer to the following image for the same:
![image](https://user-images.githubusercontent.com/75028216/100238654-77e32580-2f56-11eb-9344-5cdafb64537c.png)
The moment when user clicked on the "Get Started" button on the card, for now I am activating the About tab, but I can see that Chat tab is getting disappeared. Please refer to the below image:
![image](https://user-images.githubusercontent.com/75028216/100238856-af51d200-2f56-11eb-82d6-342116ad8c92.png)

**Comment by Abhijit-MSFT** [comment]
This is known issue. 
When deeplinked from bot to tab, chat window disappears. 
We are working on correcting it, Should be available soon.
