### ISSUE TITLE
Explicitly document that Connectors can post adaptive cards

### ISSUE THREAD

**Issue by aosolis** [MicrosoftDocs/msteams-docs#2388]
The section on this page is named "Send adaptive cards using an incoming webhook", with instructions specific to incoming webhooks specifically. We need to be explicit that Connectors in general support adaptive cards. Right now searching for "teams connector adaptive card" or similar does not return a definitive answer as to whether Connectors support adaptive cards.

https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-using#send-adaptive-cards-using-an-incoming-webhook

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28316a67-22fa-8a05-1ae0-fbe1c5720ef9
* Version Independent ID: 8a250e46-2a30-af86-839d-9f83a8b48041
* Content: [Sending messages to Connectors and Webhooks - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-using)
* Content Source: [msteams-platform/webhooks-and-connectors/how-to/connectors-using.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/webhooks-and-connectors/how-to/connectors-using.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Manish-MSFT** [comment]
@laujan , I think the suggestion provided above is right. We need to provide it explicitly since recently there were many queries regarding same.

**Comment by Wajeed-msft** [comment]
Currently. send adaptive cards are only supported using incoming webhook.
