### ISSUE TITLE
Need to update Note on the page "Connectors do not support adaptive cards"

### ISSUE THREAD

**Issue by Abhijit-MSFT** [MicrosoftDocs/msteams-docs#2394]
Note on this page tells that connectors do not support Adaptive card. This needs to be updated. Connectors now support Adaptive cards
<img width="482" alt="Capture" src="https://user-images.githubusercontent.com/48427340/100342323-d6b2a880-3003-11eb-8f9e-a69e9a751877.PNG">

**Comment by v-chetsh** [comment]
@Abhijit-MSFT - Could you please share the reference doc link here?

**Comment by v-chetsh** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.
