### ISSUE TITLE
Incorrect profile picture is displayed.

### ISSUE THREAD

**Issue by Onlife-Naveen** [MicrosoftDocs/msteams-docs#2397]
![image](https://user-images.githubusercontent.com/19261386/100427619-bc86d200-30b8-11eb-9555-c6c48cd4ff80.png)

The profile pic is cached and it is showing incorrect one; ex:
Say my last message was from "**X**" person and next if anyone else say "**Y**" messages, i still see "**X**" profile pic. However, name is displaying correctly.

**Comment by Trinetra-MSFT** [comment]
@Onlife-Naveen , Could you please try sign out/sign in once and clear your cache?

**Comment by enistr** [comment]
![image](https://user-images.githubusercontent.com/56319127/100784877-db010c00-33dd-11eb-9572-2ddfb084bcf4.png)
We had the same issue. Never seen this happened before. Looking at the dates, this can be a newly introduced bug.

**Comment by Trinetra-MSFT** [comment]
@enistr , This can happen due to cache issue, when we change profile pic for teams, it takes sometime to reflect, I also faced this when I changed profile picture. Can you confirm since how long you are facing this issue?

**Comment by enistr** [comment]
> @enistr , This can happen due to cache issue, when we change profile pic for teams, it takes sometime to reflect, I also faced this when I changed profile picture. Can you confirm since how long you are facing this issue?

This issue only happened once and I haven't seen it again.

I didn't change my own profile picture. This person I am talking with, changed his profile picture 2-3 weeks ago... I was seeing his old profile picture until today. Which I understand is a cache issue and it takes time to reflect latest change.

However, on top of that, I also saw a totally unrelated person's profile picture while this person was typing to me...

![image](https://user-images.githubusercontent.com/56319127/101076331-3c0d1900-3571-11eb-85a3-7044404dce8e.png)
