### ISSUE TITLE
TypeError: Cannot read property 'teams' of undefined

### ISSUE THREAD

**Issue by Shuvra17** [MicrosoftDocs/msteams-docs#2399]
Hi,
I am getting the following error when I Press F5 in the same browser and go to https://localhost:3000/tab
Could you please tell me the solution?

TypeError: Cannot read property 'teams' of undefined
Module../src/index.js
C:/Projects/TeamsProjects/MyTeamsApp/src/index.js:11
   8 | import { Provider, themes } from '@fluentui/react-northstar' //https://fluentsite.z22.web.core.windows.net/quick-start
   9 | 
  10 | ReactDOM.render(
> 11 |     <Provider theme={themes.teams}>
  12 |         <App />
  13 |     </Provider>, document.getElementById('root')
  14 | );
View compiled
__webpack_require__
C:/Projects/TeamsProjects/MyTeamsApp/webpack/bootstrap:784
  781 | };
  782 | 
  783 | // Execute the module function
> 784 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  785 | 
  786 | // Flag the module as loaded
  787 | module.l = true;
View compiled
fn
C:/Projects/TeamsProjects/MyTeamsApp/webpack/bootstrap:150
  147 | 		);
  148 | 		hotCurrentParents = [];
  149 | 	}
> 150 | 	return __webpack_require__(request);
      | ^  151 | };
  152 | var ObjectFactory = function ObjectFactory(name) {
  153 | 	return {
View compiled
1
https://localhost:3000/static/js/main.chunk.js:532:18
__webpack_require__
C:/Projects/TeamsProjects/MyTeamsApp/webpack/bootstrap:784
  781 | };
  782 | 
  783 | // Execute the module function
> 784 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  785 | 
  786 | // Flag the module as loaded
  787 | module.l = true;
View compiled
checkDeferredModules
C:/Projects/TeamsProjects/MyTeamsApp/webpack/bootstrap:45
  42 | 	}
  43 | 	if(fulfilled) {
  44 | 		deferredModules.splice(i--, 1);
> 45 | 		result = __webpack_require__(__webpack_require__.s = deferredModule[0]);
     | ^  46 | 	}
  47 | }
  48 | 
View compiled
Array.webpackJsonpCallback [as push]
C:/Projects/TeamsProjects/MyTeamsApp/webpack/bootstrap:32
  29 | 	deferredModules.push.apply(deferredModules, executeModules || []);
  30 | 
  31 | 	// run deferred modules when all chunks ready
> 32 | 	return checkDeferredModules();
     | ^  33 | };
  34 | function checkDeferredModules() {
  35 | 	var result;

---

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f876156-cc1e-468f-4647-5143a5de03b1
* Version Independent ID: 618f43a3-3371-ad99-13aa-087b9303298c
* Content: [Get started - Build and run your first app - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/build-your-first-app/build-and-run)
* Content Source: [msteams-platform/build-your-first-app/build-and-run.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/build-your-first-app/build-and-run.md)
* Product: **msteams**
* GitHub Login: @heath-hamilton
* Microsoft Alias: **lajanuar**

**Comment by Trinetra-MSFT** [comment]
@Shuvra17 , We are not able to repro this error at our end, Could you please provide repro steps?

**Comment by Trinetra-MSFT** [comment]
Please feel free to reopen if you have further query on this
