### ISSUE TITLE
Teams iOS application table view

### ISSUE THREAD

**Issue by toshitaka91164** [MicrosoftDocs/msteams-docs#240]
Team iOS for table view is not working for tables that are published by webhooks. In the iOS application, the table seems to be displayed as a image.

**Comment by billbliss** [comment]
Can you provide a screenshot? I'm not entirely sure what you mean by tables.

**Comment by toshitaka91164** [comment]
When i am using webhook to publish information. I displayed the information in HTML table and using webhook to output to my Teams Channel. Using my iOS app, i am unable to zoom into the table to see the details as the font size is too small

**Comment by billbliss** [comment]
I think this should be fixed soon. In the version of the iOS app I'm using, it zooms.

**Comment by billbliss** [comment]
We think this is fixed in recent versions. Reopen if this is still a problem.
