### ISSUE TITLE
Is it possible to automate the connector setup?

### ISSUE THREAD

**Issue by piyumi25** [MicrosoftDocs/msteams-docs#2407]
Hi,
I am creating an office365 connector app. I want my customer to set up the connector. According to the documentation, customer need to install the app and then need to select a team and do it. Is there a way to automate this process?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45541337-ecd7-5cf6-cbe4-3f0d2f39aa79
* Version Independent ID: 6b4203f0-2844-06c9-eaa3-9cc03e6f76c0
* Content: [Create deep links - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links)
* Content Source: [msteams-platform/concepts/build-and-test/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/build-and-test/deep-links.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by VaraPrasad-MSFT** [comment]
@piyumi25 : Currently this is not possible.

**Comment by piyumi25** [comment]
Thank you for you reply @VaraPrasad-MSFT
