### ISSUE TITLE
is it possible to use an adaptive card with out a bot?

### ISSUE THREAD

**Issue by piyumi25** [MicrosoftDocs/msteams-docs#2408]
I am developing a personal tab application which allow user to select a channel from the list and send a message to the selected channel with a card attachment. I am getting teams and channels using Grap API. I was able to send the message. I am trying save the response of card button click event. I am using adaptive card as attachment and button's type is "Action.Submit". So when user click on button I need to send a response to an API end point. Is it possible to do that. Currently I am sending this card attachment.

![image](https://user-images.githubusercontent.com/33615108/100843460-6511a900-34a0-11eb-81ea-4d6a5c9f70d7.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fb0c2d8-f880-c260-d0be-6b9467e47f8c
* Version Independent ID: 7820ffc9-5260-c818-f5fb-672801a67d00
* Content: [Respond to the task module submit action - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/action-commands/respond-to-task-module-submit?tabs=dotnet%2Cdotnet-1)
* Content Source: [msteams-platform/messaging-extensions/how-to/action-commands/respond-to-task-module-submit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/messaging-extensions/how-to/action-commands/respond-to-task-module-submit.md)
* Product: **msteams**
* GitHub Login: @clearab
* Microsoft Alias: **anclear**

**Comment by Manish-MSFT** [comment]
@piyumi25:  In case if you are using adaptive card using task modules, You can make a API call on client side in JavaScript on a button click. You can check [this](https://github.com/OfficeDev/microsoft-teams-sample-task-module-csharp/tree/master/) sample.

**Comment by Manish-MSFT** [comment]
@piyumi25 , How are you sending the card attachment to specific channel? are you using incoming webhook?

**Comment by piyumi25** [comment]
Thank you for your reply and I will check this example

**Comment by piyumi25** [comment]
> @piyumi25 , How are you sending the card attachment to specific channel? are you using incoming webhook?
No, I am sending the message using Graph API.
```
let cardconten3 = {
        "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
        "type": "AdaptiveCard",
        "version": "1.0",
        "body": [
          {
            "type": "Container",
            "items": [
              {
                "type": "TextBlock",
                "text": "How are you feeling?",
                "weight": "bolder",
                "size": "medium"
              },
            ]
          },
        ],
        "actions": [
          {
            "type": "Action.Submit",
            "title": "Average",
          },
          {
            "type": "Action.Submit",
            "title": "OK",
          },
          {
            "type": "Action.Submit",
            "title": "Good",
          },
          {
            "type": "Action.Submit",
            "title": "Excellent",
          }
        ]
      };
 const chatMessage = {
            body: {
                contentType: "html",
                content: "Here's the latest budget. <attachment id=\"87b2e161-3d3f-4d21-8453-249de0e2ee43\"></attachment>"
            },
            attachments: [
                {
                    id: "87b2e161-3d3f-4d21-8453-249de0e2ee43",
                    contentType: "application/vnd.microsoft.card.adaptive",
                    //contentUrl: "https://m365x987948.sharepoint.com/sites/test/Shared%20Documents/General/test%20doc.docx",
                    content:JSON.stringify(cardconten3),
                    name: "CT"
                }
            ]
        };
        let res = await this.msGraphClient
        .api(`teams/${teamId}/channels/${channelId}/messages`)
        .post(chatMessage);
        console.log("message send",res);
```

**Comment by Manish-MSFT** [comment]
So, After sending adaptive card --> User clicks on button and then api call must be made? Is my understanding correct?

**Comment by piyumi25** [comment]
yes @Manish-MSFT

**Comment by Manish-MSFT** [comment]
Adaptive card doesn't support actions(Although they are supported for outlook[here](https://docs.microsoft.com/en-us/outlook/actionable-messages/adaptive-card#actionhttp-example)). You can render a task module on click of button and then have a click action on that task module. So, the overall flow will be Adaptive card (button click) --> Task Module --> button click--> action. 

You can handle API call for task module's on client side(quite similar to generall process of handling an button event call for HTML/CSS website) and can have same layout using HTML/CSS. 

For more info on Task Module samples, Please refer [here](https://github.com/OfficeDev/microsoft-teams-sample-task-module-csharp/tree/master/).

**Comment by clearab** [comment]
Why not just add a bot to your webapp to send and handle the Adaptive Card? This will give you flexibility moving forward, and give you access to additional contextual information.

**Comment by piyumi25** [comment]
Thanks for all replies.

**Comment by piyumi25** [comment]
> Adaptive card doesn't support actions(Although they are supported for outlook [here](https://docs.microsoft.com/en-us/outlook/actionable-messages/adaptive-card#actionhttp-example)). You can render a task module on click of button and then have a click action on that task module. So, the overall flow will be Adaptive card (button click) --> Task Module --> button click--> action.
> 
> You can handle API call for task module's on client side(quite similar to general process of handling an button event call for HTML/ & CSS website) and can have same layout using HTML& CSS.
> 
> For more info on Task Module samples, Please refer [here](https://github.com/OfficeDev/microsoft-teams-sample-task-module-csharp/tree/master/).

Hi,

I have implemented a solution for my problem and now I am facing a different issue. 
My personal tab application workflow is as follows
1. get graph token
2. send message to a selected channel
This message is a hero card as follows. I have used openUrl to open a taskmodule using a deeplink. So taskmodule is opened only when that receiver has installed the application. Is there any way to implement this without installing the app.
![image](https://user-images.githubusercontent.com/33615108/101165366-8f0fca80-365c-11eb-8ecd-b727b550957b.png)

this is the deeplink for taskmodule
`let taskmoduleurl = `https://teams.microsoft.com/l/task/${appId}?url=${url}&height=${height}&width=${width}&title=${title}``

**Comment by v-chetsh** [comment]
@piyumi25 - Could you please confirm if your issue has resolved or still looking for any help?
