### ISSUE TITLE
App not found, deep links

### ISSUE THREAD

**Issue by phpmaps** [MicrosoftDocs/msteams-docs#2409]
Hi Microsoft Teams,

What is the expected experience when deep links are shared to users who do not have the app extension installed?   

Below appears to be the default experience.   

![image](https://user-images.githubusercontent.com/2159502/100941975-60082600-34af-11eb-9402-f656d4586694.png)

Some additional documentation around considerations and context for sharing deep links, I think would be helpful.  For example, (if possible) it would be nice in addition to  the cancel button to  include buttons which 

1) Take users to the AppSource App Website Landing Page
2) Download and install the needed app

Please reach out to me if any additional information is needed.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45541337-ecd7-5cf6-cbe4-3f0d2f39aa79
* Version Independent ID: 6b4203f0-2844-06c9-eaa3-9cc03e6f76c0
* Content: [Create deep links - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links)
* Content Source: [msteams-platform/concepts/build-and-test/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/build-and-test/deep-links.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by VaraPrasad-MSFT** [comment]
@phpmaps : 

When you share the deepink ,  the app should be installed in the user teams so that he can navigate to the respective path.
You have received the error message due to app not installed from user end.

**Comment by phpmaps** [comment]
One more comment I have is the App not found error message (following the deep link click) does not make mention to the name of the app extension.  

So when link opens in the App panel with this error it's unclear as to which app would need to be installed.

**Comment by VaraPrasad-MSFT** [comment]
It will not mention the app name as extension, but you can share the [manifest ](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema)to install the app.
