### ISSUE TITLE
Is it possible to use Office365 connector as a multitenant connector?

### ISSUE THREAD

**Issue by piyumi25** [MicrosoftDocs/msteams-docs#2413]
I have created an office365 connector app for teams using abcd@testdomain.com and it is working as expected for testdomain.com accounts. I tried to configure the connector app for xyz@testdomain2.com and I got the following error.

![image](https://user-images.githubusercontent.com/33615108/100965173-1facb480-3550-11eb-820e-e1abca2d5340.png)

Can some one help me to understand the issue?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da50e4db-a713-ab8b-d27b-89aa946619d0
* Version Independent ID: 57e368e2-aaed-fa8d-ed49-cc18e594ab1d
* Content: [Office 365 Connectors - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-creating)
* Content Source: [msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Manish-MSFT** [comment]
@piyumi25 , The connector limit for user per account  is 10 connectors, Could you please copy the error stack and paste it such that It's easily readable and I can discuss this internally with my team.

**Comment by piyumi25** [comment]
> @piyumi25 , Could you please copy the error stack and paste it such that It's easily readable and I can discuss this internally with my team.

This is the error

`2020-12-03T08:42:43.793Z Received error from connectors {"seq":1606968785131,"timestamp":1606984961723,"flightSettings":{"Name":"ConnectorFrontEndSettings","AriaSDKToken":"d127f72a3abd41c9b9dd94faca947689-d58285e6-3a68-4cab-a458-37b9d9761d35-7033","SPAEnabled":true,"ClassificationFilterEnabled":true,"ClientRoutingEnabled":true,"EnableYammerGroupOption":true,"EnableFadeMessage":false,"EnableDomainBasedOwaConnectorList":false,"EnableDomainBasedTeamsConnectorList":false,"DevPortalSPAEnabled":true,"ShowHomeNavigationButtonOnConfigurationPage":false,"DisableConnectToO365InlineDeleteFeedbackPage":true},"status":500,"clientType":"SkypeSpaces","connectorType":"Manage","name":"ClientError"}`

**Comment by Manish-MSFT** [comment]
Hi @piyumi25 ,I am still not getting the error as you got. Can you please provide repro steps to just see if it's also happening on my side as well. I have also forwarded the issue to respective team they need fiddler trace to verify. Could you please provide fiddler trace with repro steps at v-manisc@microsoft.com Thanks.
