### ISSUE TITLE
Adaptive cards are now supported in Teams connectors

### ISSUE THREAD

**Issue by rabwill** [MicrosoftDocs/msteams-docs#2414]
Shouldn't we remove below note as adaptive cards are now supported in Teams connectors so as to not confuse developers? Atleast in the case of the incoming webhooks connector adaptive cards work.

`Teams connectors do not currently support Adaptive Cards. However, it is possible to create a flow that posts adaptive cards to a Teams channel`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90ff2a84-a8bc-9259-d37d-622b102df75b
* Version Independent ID: e3b53e27-2946-189c-623b-9df704ea8f12
* Content: [Post external requests to Microsoft Teams with incoming webhooks - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-incoming-webhook)
* Content Source: [msteams-platform/webhooks-and-connectors/how-to/add-incoming-webhook.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/webhooks-and-connectors/how-to/add-incoming-webhook.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by KirtiPereira** [comment]
This issue has been closed through PR#2560.
