### ISSUE TITLE
Getting all corporations ids users. 

### ISSUE THREAD

**Issue by wsbdeveloper** [MicrosoftDocs/msteams-docs#2415]
Hi Everyone,

I have a problem in user data

Execute in botbuilder nodejs :

`
async messageAllMembersAsync(context) {
   const members = await TeamsInfo.getMembers(context);

   // Print members in console
   console.log(members, "Members");

   return true;
}
`

Output :

`
[ 
    { 
       id:'29:XXX',
       name: 'wwwww',
       objectId: 'www',
       givenName: 'wwww',
       surname: 'ww',
       email: 'ww',
       userPrincipalName: 'ww',
       tenantId: 'wwww',
       userRole: 'www',
       aadObjectId: 'wwwwww' 
    } 
] 'Members'
`

I need all ids my corporation, where can extract this datas (all ID 29:XXX), its possible?

**Comment by Nikitha-MSFT** [comment]
Are you trying to get all the id's of the user? If is could you please check [list user](https://docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-beta&tabs=http) API? Try if that helps.

**Comment by wsbdeveloper** [comment]
Yes, I need this ID the start is 29:xxxxxxx, it is specific when I run this code, I looked inside the AD but I don't find similar to this pattern. When I am in a group within teams and I execute this with the bot it returns from all members of that group. This ID is specific to the bot or has a base with that ID (29: sha256)

**Comment by wsbdeveloper** [comment]
@Nikitha-MSFT you can help me?

**Comment by Trinetra-MSFT** [comment]
@wsbdeveloper : if you are looking for sending message to all members, You can look at following [teams conversation Bot sample code](https://github.com/microsoft/BotBuilder-Samples/blob/6ec482808245a1ee73b4f71b72a19543e09c74e8/samples/typescript_nodejs/57.teams-conversation-bot/src/teamsConversationBot.ts#L156)?

**Comment by wsbdeveloper** [comment]
@Trinetra-MSFT Hello,

Yes, I actually need to run a script that brings all ids in this 29: xxx (sha256) format. This id appears in this code snippet that I mentioned above
`const members = await TeamsInfo.getMembers (context);
`
I was wondering if it is generated by the botbuilder within the context, or has a database with these IDs (29:sha256) of my company.

**Comment by Trinetra-MSFT** [comment]
@wsbdeveloper , These id belongs to users where bot is installed either it can be team, group chat or personal scope, GetMembers API returns list of members You can get these id (these id or Team/Chat id for the user) from the Bot Activity once you install Bot in teams channel,but there is no data base where we maintain these specific to company

**Comment by wsbdeveloper** [comment]
Hello @Trinetra-MSFT it already helped me thank you all.

**Comment by wsbdeveloper** [comment]
@Trinetra-MSFT I have more one question, as it does for a Bot that has never talked to a specific group or specific user, does it identify how to send a message for the first time to a user on teams? Its is possible.
