### ISSUE TITLE
ExtensionTabService: getAuthTokenForApp: Failed with error - App resource defined in manifest and iframe origin do not match

### ISSUE THREAD

**Issue by aycron-dev** [MicrosoftDocs/msteams-docs#2416]
I'm having this error following this tutorial https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-aad-sso?WT.mc_id=m365-blog-rogerman 
I'm using ngrok and Microsoft Teams Toolkit

**Comment by Trinetra-MSFT** [comment]
@aycron-dev , Could you please look at following [sample code](https://github.com/ydogandjiev/taskmeow/blob/master/manifest/sso/manifest.json#L28)? Could you please also confirm if your tab has `inTeamsSSO=true` appended

**Comment by aycron-dev** [comment]
> @aycron-dev , Could you please look at following [sample code](https://github.com/ydogandjiev/taskmeow/blob/master/manifest/sso/manifest.json#L28)? Could you please also confirm if your tab URL has `inTeamsSSO=true` appended

I've it working changing all references for the tabs to the ngrok url. I think a better sample code should be added to the documentation.

**Comment by Trinetra-MSFT** [comment]
@aycron-dev , Thanks for your input, We will work with document team to put necessary information in documentation, As of now closing this thread, Please feel free to reopen if you need more assistance on this issue

**Comment by aycron-dev** [comment]
Hi I'm still having the same problem

**Comment by Saonti-MSFT** [comment]
@aycron-dev We have already connected with the Documentation Team to make the necessary updates.
You can try out this [Sample Code](https://github.com/Trinetra-MSFT/teams-tab-SSO-CSharp).  As of now closing this thread. Feel free to reopen if you face any problem.
