### ISSUE TITLE
"Choose action command invoke locations" should provide the corresponding context values

### ISSUE THREAD

**Issue by aosolis** [MicrosoftDocs/msteams-docs#2417]
The "Choose action command invoke locations" section says where you can show the command, but it doesn't say how the locations map to the context values.

>Choose action command invoke locations
> The first thing you need to decide is where your action command can be triggered (or more specifically, invoked) from. By specifying the context in your app manifest, your command can be invoked from one or more of the following locations:
>
> - The buttons at the bottom of the compose message area.
> - By @mentioning your app in the command box. Note: You cannot respond with a bot message inserted directly into the conversation if your messaging extension is invoked from the command box.
> - Directly from an existing message via the ... overflow menu on a message. Note: The initial invoke to your bot will include a JSON object containing the message from which it was invoked, which you can process before presenting them with a task module.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: efcdf768-1513-2249-b344-bf38ef64c70d
* Version Independent ID: 415b5d57-2d41-9540-55a7-2a33a4315e37
* Content: [Define messaging extension action commands - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/action-commands/define-action-command)
* Content Source: [msteams-platform/messaging-extensions/how-to/action-commands/define-action-command.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/messaging-extensions/how-to/action-commands/define-action-command.md)
* Product: **msteams**
* GitHub Login: @clearab
* Microsoft Alias: **anclear**

**Comment by Wajeed-msft** [comment]
Could you please add documentation for context information in respective point ?

1. compose message area
Command context = compose
2.  command box
Commands context = commandBox
3. Existing message via the ... overflow menu
Commands context = message
