### ISSUE TITLE
M365 ‘Publisher Attestation’

### ISSUE THREAD

**Issue by ghantasalaphanidhar** [MicrosoftDocs/msteams-docs#2418]
[Enter feedback here]
New section to be created : M365 Publisher Attestation

Please complete the Publisher Attestation in Partner Center. Refer the documentation https://docs.microsoft.com/en-us/microsoft-365-app-certification/docs/attestation for more details about the program and follow the user guidehttps://docs.microsoft.com/en-us/microsoft-365-app-certification/docs/userguide#3publisher-attestation-workflow for completing the work flow. Please refer Troubleshooting guide https://docs.microsoft.com/en-us/azure/active-directory/develop/troubleshoot-publisher-verification for more details.
--

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b294c444-a6ae-a5e7-4f65-26715b1a3cf6
* Version Independent ID: 5df1b473-c136-64f6-b818-c34d0239cd1c
* Content: [Tips and frequently failed cases - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases)
* Content Source: [msteams-platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by KirtiPereira** [comment]
Closed through PR# 2419.
