### ISSUE TITLE
Cannot create incoming webhook connector

### ISSUE THREAD

**Issue by marco-gallinari** [MicrosoftDocs/msteams-docs#2423]
After entering a name for a new Incoming Webhook connector, creation failed with this message:

```
Failed to create webhook b2 URL for tenant ....
RequestId: d4741b69-4b58-4167-9480-0c83a563e53e
Server: AM5PR0701MB2657
Date: 12/4/2020 10:36:36 PM
```

Who can I ask support for this?

**Comment by Manish-MSFT** [comment]
@marco-gallinari, Can you please mention how are you creating this webhook?

**Comment by sreed101** [comment]
Having the same issue. Creating a webhook by following the instructions here: https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-incoming-webhook

[11:34 AM] Scott Reed
    

:-(

Something went wrong.


Failed to create webhook b2 URL for tenant Tedder Industries

RequestId: 0f2cdbf2-c45b-41b2-a885-17bc514a6451
Server: DM6PR13MB3675
Date: 12/8/2020 7:33:58 PM


Fewer details...

**Comment by marco-gallinari** [comment]
Hi @Manish-MSFT, I tried configuring the connector via windows client, and via the web interface, too, with the the same result. 

On another subscription it works just fine.

**Comment by wictorwilen** [comment]
I can confirm that I've seen this issue for the last month or so.

**Comment by Manish-MSFT** [comment]
@marco-gallinari, I just received confirmation from engineering team that the issue is fixed. Could you please check once again and let us know, If you still face the issue please share the request id. Thanks.

**Comment by Trinetra-MSFT** [comment]
Please feel free to reopen if you still facing this issue
