### ISSUE TITLE
Is it possible to open a task module using a deep link without installing the app?

### ISSUE THREAD

**Issue by piyumi25** [MicrosoftDocs/msteams-docs#2424]
This issue is related with the https://github.com/MicrosoftDocs/msteams-docs/issues/2408 . As per the solutions I have got I decided to create a personal tab application which send message with a card attachment to a channel. I am sending messages using MS Graph API and it works for me as expected. 
I have a requirement when any of the member in channel click on a button as shown as follows, then I need to identify which user selects the button. 

![image](https://user-images.githubusercontent.com/33615108/101232203-2fee9c00-36d6-11eb-80ca-201730b79e26.png)

So what I implemented was add a deep link to a task module and open the task module when clicking on the button and get context details. 
But to do that, that particular user need to have installed the personal tab application and if not nothing happen when click on the button. As per the knowledge I have, I think that is because deep link contain the APPID.
`let taskmoduleurl = https://teams.microsoft.com/l/task/${appId}?url=${url}&height=${height}&width=${width}&title=${title}```
Can someone help me to give a better solution for my problem?

**Comment by Mallipriya-MSFT** [comment]
@piyumi25, 
Firstly, I understood your requirement partially. As per my understanding, from a personal tab application if a message with a card attachment has to be sent to a channel, then it necessary for an user to install the personal tab application. Instead, if the tab is integrated into a channel then it is accessible to members in the channel.

Since there is no bot integrated here to fetch the context details of the user, task module is employed using deeplink.
From Adaptive card(button click) --> Task Module-->(on button click)-->submit action gets triggered. Upon submit action, you can try to hit an API for fetching details of the user. Hope This could help.

**Comment by piyumi25** [comment]
> @piyumi25,
> Firstly, I understood your requirement partially. As per my understanding, from a personal tab application if a message with a card attachment has to be sent to a channel, then it necessary for an user to install the personal tab application. Instead, if the tab is integrated into a channel then it is accessible to members in the channel.
> 
> Since there is no bot integrated here to fetch the context details of the user, task module is employed using deeplink.
> From Adaptive card(button click) --> Task Module-->(on button click)-->submit action gets triggered. Upon submit action, you can try to hit an API for fetching details of the user. Hope This could help.

Is it possible to fetch Action.Submit without a bot. Can you provide guidance for that?

**Comment by Mallipriya-MSFT** [comment]
@piyumi25,
No.  Action.submit on task module is handled by submitHandler callback and is achieved through completion logic code. If your completion logic resides on the client (i.e. if there is no bot) there is no submitHandler callback, so any completion logic must be in the code preceding the call to tasks.submitTask(). For more information [check docs](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/what-are-task-modules).

**Comment by piyumi25** [comment]
> @piyumi25,
> No. Action.submit on task module is handled by submitHandler callback and is achieved through completion logic code. If your completion logic resides on the client (i.e. if there is no bot) there is no submitHandler callback, so any completion logic must be in the code preceding the call to tasks.submitTask(). For more information [check docs](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/what-are-task-modules).

Do you think it is possible to open task module if that message receiver does not have app installed? Here issue is with opening the task module.

**Comment by Mallipriya-MSFT** [comment]
Yes, it is possible when task module is invoked using deeplink upon open.url action of an adaptive card from a channel. In such case members of the channel need not install app. There won't be any issue in opening of task module.

**Comment by piyumi25** [comment]
> Yes, it is possible when task module is invoked using deeplink upon open.url action of an adaptive card from a channel. In such case members of the channel need not install app. There won't be any issue in opening of task module.

But I was unable to open the task module if message receiver had not installed the App.

**Comment by Mallipriya-MSFT** [comment]
Sorry, for the delayed response. You need to install app once by side loading i.e [upload a custom app](https://docs.microsoft.com/en-us/microsoftteams/upload-custom-apps) and when the adaptive card gets posted in the channel members of the channel can click on the button and can interact with task module.

**Comment by v-chetsh** [comment]
@piyumi25 - Could you please confirm if your issue has resolved or still looking for any help?
