### ISSUE TITLE
Get user profile of adaptive card responder

### ISSUE THREAD

**Issue by piyumi25** [MicrosoftDocs/msteams-docs#2425]
I am sending an adaptive card to a channel using Graph API. That card contains an Action button ( Action.Submit / Action.OpenUrl). When user clicks the button Is there a way to obtain information (user profile/ user id) of the user who clicked it.

I have seen a very similar question has been asked in Power Automate https://powerusers.microsoft.com/t5/Building-Flows/get-user-profile-of-adaptive-card-responder/m-p/678336#M91443. I want to achieve the same without having to use Power Automate.

Note: I do not want to have to install any apps/bots on the responders end.

**Comment by Mallipriya-MSFT** [comment]
@piyumi25, It is not supported with adaptive card without bots or power automate or task module without bot/app .
