### ISSUE TITLE
[App Studio] doesn't display Correct UI over iPhone mobile

### ISSUE THREAD

**Issue by Trinetra-MSFT** [MicrosoftDocs/msteams-docs#2426]
App studio doesn't display correct UI for iPhone device. Please fix this Bug in App Studio.
screenshot:
![image](https://user-images.githubusercontent.com/50989436/101351826-3425df80-38b7-11eb-85aa-05a933d9948c.png)

---

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f4a41f1-2993-7869-a1ab-b83cb6225d7e
* Version Independent ID: c000998f-9192-50fb-6a0b-ace157054292
* Content: [Get started with App Studio for Microsoft Teams - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/app-studio-overview)
* Content Source: [msteams-platform/concepts/build-and-test/app-studio-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/build-and-test/app-studio-overview.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by v-chetsh** [comment]
@@Trinetra-MSFT - Could you please confirm if your issue has resolved or still looking for any help?
