### ISSUE TITLE
Leave meeting key combination doesn't work in calls with multiple people

### ISSUE THREAD

**Issue by Andreas02-dev** [MicrosoftDocs/msteams-docs#2427]
I'll get straight to the point:
When in a meeting with 1 person, using CTRL-SHIFT-B does what it should: it leaves the meeting.
However, when in a meeting with multiple people, CTRL-SHIFT-B selects the pane of one of the people in the meeting and does NOT leave the meeting.
This bug should be easily reproduceable by joining aforementioned meetings.
I am using Microsoft Teams Version 1.3.00.26064 (64 bit), which was last updated on 08/10/2020.

With kind regards,
Andreas

**Comment by Mallipriya-MSFT** [comment]
@Andreas02-dev,
For issues related to teams product, please reach out to the [Product support channels](https://docs.microsoft.com/en-us/microsoftteams/platform/feedback#product-support-channels).
