### ISSUE TITLE
Images disappear from meeting notes

### ISSUE THREAD

**Issue by thaDude** [MicrosoftDocs/msteams-docs#2428]
Hello,

Client version information: Microsoft Teams Version 1.3.00.26266 on macOS.

When embedding images into meeting notes, leaving the meeting notes, reopening them and then clicking anywhere in the document the image disappears. I am including a screen recording of these steps.

![ms_teams_meeting_notes_image_bug](https://user-images.githubusercontent.com/578631/101406832-48c79f00-38da-11eb-8100-2a9f7286ca8b.gif)

Regards,

David

**Comment by VaraPrasad-MSFT** [comment]
For issues related to teams product, please reach out to the [Product support channels](https://docs.microsoft.com/en-us/microsoftteams/platform/feedback#product-support-channels) for Microsoft Teams

**Comment by v-chetsh** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.
