### ISSUE TITLE
Fetching the Id Who removes the meeting participants 

### ISSUE THREAD

**Issue by Akashkumar201** [MicrosoftDocs/msteams-docs#2429]
After this covid epidemic, almost classes are hosted online, therefore, many video conferencing apps came into the picture but one of them is ms team my collage also started to use this amazing app where thousands of people learning every day but when its comes to share screen and provide the permission to everyone actually we cannot able to keep track of _who is removing the participants from the meeting_ which leads to the inconvenience in class it will be batter you **### will able to fetch the user id and display on-screen who is removing whom in the meeting.**

**_Lots Of Regards_**

**Comment by v-chetsh** [comment]
@Akashkumar201 - Could you please confirm if your issue has resolved or still looking for any help?
