### ISSUE TITLE
Missing step, example not working

### ISSUE THREAD

**Issue by trantako** [MicrosoftDocs/msteams-docs#2430]
This step is not explained in the doc: "3) applying the CSS to your tab content's root HTML element (<div>)"

As a consequence, "newTheme" is not used anywhere and the colors are not changed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29e90229-289e-2035-3b42-5cb9cce14efe
* Version Independent ID: a2aee4b8-93b9-bda7-f000-8f41b4513647
* Content: [Get started - Build a personal tab - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/build-your-first-app/build-personal-tab)
* Content Source: [msteams-platform/build-your-first-app/build-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/build-your-first-app/build-personal-tab.md)
* Product: **msteams**
* GitHub Login: @heath-hamilton
* Microsoft Alias: **lajanuar**

**Comment by sameera** [comment]
For non-React (or new to React) developers who run in to this missing docs, the solution is, you change the `render` method in `Tab.js` as :

```
render() {

        let userName = Object.keys(this.state.context).length > 0 ? this.state.context['upn'] : "";
        let isTheme = this.state.theme;
        let newTheme;

        if (isTheme === "default") {
            newTheme = {
                backgroundColor: "#EEF1F5",
                color: "#16233A"
            };
        } else {
            newTheme = {
                backgroundColor: "#2B2B30",
                color: "#FFFFFF"
            };
        }

        return (
            <div style={newTheme}>
                <h1>Important Contacts</h1>
                <ul>
                    <li>Help Desk: <a href="mailto:support@company.com">support@company.com</a></li>
                    <li>Human Resources: <a href="mailto:hr@company.com">hr@company.com</a></li>
                    <li>Facilities: <a href="mailto:facilities@company.com">facilities@company.com</a></li>
                </ul>
            </div>
        );
    }
```

**Comment by v-sdhakshina** [comment]
Theme related content moved to Learn module https://docs.microsoft.com/en-us/learn/modules/embedded-web-experiences/3-exercise-create-custom-teams-personal-tab

**Comment by Wajeed-msft** [comment]
Please re-open if you are still facing this issue.
