### ISSUE TITLE
Getting users through admin consent

### ISSUE THREAD

**Issue by ryfow** [MicrosoftDocs/msteams-docs#2432]
We're currently using the email addresses from the roster apis. It sounds like we're going to need to switch to the graph api by late 2021. There's a note in this document about making the end-user consent process easier. Has there been any progress on that? Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c780d605-b1b2-716f-5888-503608769b5a
* Version Independent ID: 53c724f8-d9a2-4af6-6d75-ddeaef084137
* Content: [Bot API Changes for Team/Chat Members (2020 update) - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/team-chat-member-api-changes)
* Content Source: [msteams-platform/resources/team-chat-member-api-changes.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/resources/team-chat-member-api-changes.md)
* Product: **msteams**
* GitHub Login: @ojasvichoudhary
* Microsoft Alias: **ojchoudh**

**Comment by Nikitha-MSFT** [comment]
@ryfow - About which note you are talking  we don't see any note as you reporting- could you please specify more on the document.

**Comment by ryfow** [comment]
@Nikitha-MSFT I'm looking at the final bullet point of this page: https://docs.microsoft.com/en-us/microsoftteams/platform/resources/team-chat-member-api-changes

> By late 2021, bots cannot proactively retrieve the userPrincipalName or email properties for members of a chat or team. Bots must use Graph to retrieve them. The userPrincipalName and email properties are not returned from the new GetConversationPagedMembers API starting in late 2021. Bots have to use Graph with an access token to retrieve information. It must be made easier for bots to get an access token and streamline and simplify the end-user consent process.

I want to know what the plan is for "must be made easier for bots to get an access token"?

**Comment by Nikitha-MSFT** [comment]
We are checking internally get back to you soon.

**Comment by Nikitha-MSFT** [comment]
Need to Update the note in the doc - Final bullet point of this page: https://docs.microsoft.com/en-us/microsoftteams/platform/resources/team-chat-member-api-changes. Need to change the Year in the last point from 2021 to 2022- 

> By late 2021, bots cannot proactively retrieve the userPrincipalName or email properties for members of a chat or team. Bots must use Graph to retrieve them. The userPrincipalName and email properties are not returned from the new GetConversationPagedMembers API starting in late 2021. Bots have to use Graph with an access token to retrieve information. It must be made easier for bots to get an access token and streamline and simplify the end-user consent process.

**Comment by ryfow** [comment]
Thanks!
