### ISSUE TITLE
Unclear where I paste the code snippet

### ISSUE THREAD

**Issue by mipradhan** [MicrosoftDocs/msteams-docs#2433]
In "Update the Tab Theme" section, the doc doesn't say where I should paste the code snippet - 
const isTheme = this.state.theme

& 

let newTheme

if (isTheme === "default") {
  newTheme = {
    backgroundColor: "#EEF1F5",
    color: "#16233A"
  };
} else {
  newTheme = {
    backgroundColor: "#2B2B30",
    color: "#FFFFFF"
  };
}

Please add 2 lines explaining where in the code this needs to be added. 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29e90229-289e-2035-3b42-5cb9cce14efe
* Version Independent ID: a2aee4b8-93b9-bda7-f000-8f41b4513647
* Content: [Get started - Build a personal tab - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/build-your-first-app/build-personal-tab)
* Content Source: [msteams-platform/build-your-first-app/build-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/build-your-first-app/build-personal-tab.md)
* Product: **msteams**
* GitHub Login: @heath-hamilton
* Microsoft Alias: **lajanuar**

**Comment by heath-hamilton** [comment]
Hi @mipradhan, you can paste this code snippet inside the render() function (see the following example). Does this help? Please let me know if you have questions.

```JavaScript
  render() {

      let userName = Object.keys(this.state.context).length > 0 ? this.state.context['upn'] : "";

      const isTheme = this.state.theme
      
      let newTheme

      if (isTheme === "default") {
        newTheme = {
          backgroundColor: "#EEF1F5", 
          color: "#16233A"
        };        
      } else {
        newTheme = {
          backgroundColor: "#2B2B30", 
          color: "#FFFFFF"
        };
      }
```

**Comment by mipradhan** [comment]
Yup, this helps - thank you!
Please mention the same in the docs so it can benefit all readers.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by heath-hamilton** [comment]
Of course--glad to help, @mipradhan! Doc updates will be added once PR https://github.com/MicrosoftDocs/msteams-docs/pull/2551 merges.
