### ISSUE TITLE
Code samples redirect to sharepoint

### ISSUE THREAD

**Issue by jeubank12** [MicrosoftDocs/msteams-docs#2434]
I think the code sample links are set up for the wrong location. Should this be github instead of sharepoint?

Correlation ID: 2d5c959f-e045-0000-d106-42f6aa2c24e3
Date and Time: 12/8/2020 10:21:12 AM
URL: https://microsoft-my.sharepoint-df.com/personal/vul_microsoft_com/_layouts/15/guestaccess.aspx?e=uPq62c&share=ETZQfeTViDlCv-frjgTIincB7dvk2HOnma1TLvcoeGGIxg
User: <redacted>
Issue Type: User not in directory.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9549caa9-99a2-2568-19a5-f21a79292e2f
* Version Independent ID: f2100d03-b88a-34b2-44a2-935231e89db0
* Content: [Single sign-on support for bots - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/authentication/auth-aad-sso-bots)
* Content Source: [msteams-platform/bots/how-to/authentication/auth-aad-sso-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/bots/how-to/authentication/auth-aad-sso-bots.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by arjvs** [comment]
Any update on this please, unable to access the samples

**Comment by v-ypalikila** [comment]
The code sample links for Bot framework SDK redirect to GitHub.
