### ISSUE TITLE
Saving serviceUrl best practice - using tenant as key

### ISSUE THREAD

**Issue by liangchr** [MicrosoftDocs/msteams-docs#2437]
For proactive messaging we need to save a user or team serviceUrl.

Right now my bot saves the serviceUrl for every single user/team. (using userid, and teamid as the key respectively.) 

I was wondering if it might be possible to save a serviceUrl for a tenant. (Instead of saving for every user/team.) and just retrieve the serviceUrl as needed via a tenantId. Then use that service url for proactively messaging all users/teams in that tenant,

This would ONLY work if the serviceUrl for each user/team across the entire tenant is the SAME ONE. 

I was wondering if there was any guarantee that users/teams under the SAME TENANT use the same service url. 

Any help/clarification is greatly appreciated!

**Comment by Manish-MSFT** [comment]
@liangchr : Yes, within the same tenant service URL will be same for all users across the tenant level. You don't need to keep track of service URL, if your Bot is installed on some other tenant this will result in change of  service URL. For proactive messaging, you can store the service URL for one tenant and use it accordingly.

**Comment by liangchr** [comment]
@Manish-MSFT Thanks a lot for the reply! I was wondering if you could follow up with me on two more things: 

1.) According to documentation I am told that serviceUrls are subject to change-- does this mean that its best practice to re-cache it for the user/team regularly from the incoming requests? 

2.) How might I go about changing a single users region in order to test that their serviceUrl changes with the region as well?

**Comment by Manish-MSFT** [comment]
@liangchr : Your understanding of the above question is correct, all users in a tenant belonging to particular region will have same Service URL.

**Comment by liangchr** [comment]
Thank you so much! @Manish-MSFT One more thing to clarify. Within a tenant there is no possible way for some users to be in a different region from others-- They all have to be in the same region, correct? Sorry if you've already answered this. I just want to me absolutely sure.

**Comment by Manish-MSFT** [comment]
@liangchr : Yes, In each tenant users are of same region to give best understanding please refer [this](https://docs.microsoft.com/en-us/power-platform/admin/multiple-online-environments-tenants#a-multi-tenant-deploymentl) image. This image perfectly describes tenants in azure.

**Comment by Trinetra-MSFT** [comment]
Please feel free to open if you have further query on this.
