### ISSUE TITLE
Update Sample Link to use Teams PnP SSO Sample

### ISSUE THREAD

**Issue by HiltonGiesenow** [MicrosoftDocs/msteams-docs#2439]
The sample that is linked to is Node.js only, and it also uses ADAL, so the new Teams PnP Sample might be useful to link to instead. It includes a Node.js as well as a .NET version, and uses MSAL 2.0 instead. See https://github.com/pnp/teams-dev-samples/tree/master/samples/tab-sso

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52221dd3-95ec-96b9-1da8-9478527c2602
* Version Independent ID: 32e9c2d8-733d-0865-2ea3-727d8684a10d
* Content: [Single sign-on support for tabs - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-aad-sso)
* Content Source: [msteams-platform/tabs/how-to/authentication/auth-aad-sso.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tabs/how-to/authentication/auth-aad-sso.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Trinetra-MSFT** [comment]
@laujan @KirtiPereira , Could you please help to add this link to sample code section of the Tab SSO documentation:
**Link need to be added:** [https://github.com/pnp/teams-dev-samples/tree/master/samples/tab-sso](https://github.com/pnp/teams-dev-samples/tree/master/samples/tab-sso)
