### ISSUE TITLE
Get locale for onboarding message

### ISSUE THREAD

**Issue by liangchr** [MicrosoftDocs/msteams-docs#2442]
I know that typical bot messages come with a "locale" value in the body like so: **"locale" : en-US**

I noticed, however, that the onboarding request does not include "locale" in the body. This is a problem for my product as my team would like our welcome message to be in the correct language that the user requires. Is there a way to get this locale value? 

Any help is appreciated!

**Comment by Mallipriya-MSFT** [comment]
We are looking into it. Will get back to you soon

**Comment by Mallipriya-MSFT** [comment]
@liangchr, Sorry for the delayed response. We have backlog and an active bug on this issue. Will let you know once it is resolved.

**Comment by ChetanSharma-msft** [comment]
Hello @liangchr - Are you still facing this issue?
You can localize your Teams app: https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/apps-localization
