### ISSUE TITLE
Need to move Category mapping table to the end of the page as a new section.

### ISSUE THREAD

**Issue by ghantasalaphanidhar** [MicrosoftDocs/msteams-docs#2445]
[Enter feedback here]
Need to move Category mapping table to the end of the page as a new section.
More Details in https://github.com/MicrosoftDocs/msteams-docs/issues/2347

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f071593-9440-5115-242d-488cf25e9256
* Version Independent ID: 746b1c6e-1bcc-21fe-e2be-149e7c10f1d5
* Content: [Microsoft Teams app approval submission process guidance - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/publish)
* Content Source: [msteams-platform/concepts/deploy-and-publish/appsource/publish.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/deploy-and-publish/appsource/publish.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Mahesh2516** [comment]
I have moved the App category mapping table at the bottom of the document as a new section.
