### ISSUE TITLE
Teams sharing not showing InfoPath drop down list items

### ISSUE THREAD

**Issue by CCTech-AK** [MicrosoftDocs/msteams-docs#2447]
If I share an InfoPath 2013 window in a Teams meeting, then guest can't see items in a drop down list.  If I share the entire screen, instead of just the InfoPath window, the guests can see the items.

[InfoPath-TeamsIssue.pdf](https://github.com/MicrosoftDocs/msteams-docs/files/5676224/InfoPath-TeamsIssue.pdf)

**Comment by VaraPrasad-MSFT** [comment]
Could you please reach out to [Product support channels](https://docs.microsoft.com/en-us/microsoftteams/platform/feedback#product-support-channels) for Microsoft Teams.

**Comment by v-chetsh** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.
