### ISSUE TITLE
$schema property not allowed during app submission

### ISSUE THREAD

**Issue by benpolinsky** [MicrosoftDocs/msteams-docs#245]
Although the $schema property is helpful while developing to enable Intellisense for editors, it will cause an error when uploading the manifest to the Office Store.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f94a488-d636-92b3-21eb-c88744c8f272
* Version Independent ID: 7b3413f4-9ade-accf-5cb2-83fead11a32a
* Content: [Manifest schema reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema)
* Content Source: [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/resources/schema/manifest-schema.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by billbliss** [comment]
What error are you referring to? We coordinate our versioning with them closely, or try to at least.

**Comment by benpolinsky** [comment]
I'm not the one uploading into the store, but the error received is:

'root defines property "$schema" not defined by the schema and additional properties are not allowed'

Our manifest version was outdated, so perhaps that was the issue.

**Comment by MattSFT** [comment]
Version 1.0 of the manifest schema did not allow $schema in it. Upgrade to any version higher and it should be fine (latest is 1.3)

**Comment by billbliss** [comment]
See here: https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema

**Comment by benpolinsky** [comment]
Ah - makes sense.

Thanks!
