### ISSUE TITLE
Does something need to be abled to make this feature available?

### ISSUE THREAD

**Issue by nastassiar** [MicrosoftDocs/msteams-docs#2454]
The first image on the page shows a + button at the top of a new meeting. I don't see this available in my Teams. Is this feature not available yet or is there something an admin needs to do to enable this feature? Instruction on how to do this would be helpful. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82987815-d508-d642-c1f6-b609241d4750
* Version Independent ID: 29e89cc6-c8ca-7d29-7dca-4ac4d06f5c42
* Content: [Apps in teams meetings - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/teams-apps-in-meetings)
* Content Source: [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by VaraPrasad-MSFT** [comment]
For issues related to teams product, please reach out to the [Product support channels ](https://docs.microsoft.com/en-us/microsoftteams/platform/feedback#product-support-channels)for Microsoft Teams

**Comment by VaraPrasad-MSFT** [comment]
Could you check the role , users with organizer / presenter roles can add tabs to a meeting . Please refer the [document ](https://docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?tabs=json#configure-your-app-for-meeting-scenarios)for more info.
