### ISSUE TITLE
404 link for Camera and image capabilities in Team docs

### ISSUE THREAD

**Issue by DomWill** [MicrosoftDocs/msteams-docs#2456]
On page https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/device-capabilities/native-device-permissions.md the Camera and image capabilities in Teams link leads to a 404 error

**Comment by Trinetra-MSFT** [comment]
Thanks for your concern @DomWill , I can see the link is broken, I will check this with document team and get it fixed

**Comment by Trinetra-MSFT** [comment]
@laujan , Could you please help to update the link in this [document](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/device-capabilities/native-device-permissions.md#request-device-permissions-for-your-microsoft-teams-tab)?
![image](https://user-images.githubusercontent.com/50989436/102042241-5bb90280-3df7-11eb-802e-a55e0ccee374.png)

Highlighted link Needs to be updated to this: [https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/mobile-camera-image-permissions](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/mobile-camera-image-permissions)
