### ISSUE TITLE
"Build your first Microsoft Teams app" needed for C#/Visual Studio

### ISSUE THREAD

**Issue by aosolis** [MicrosoftDocs/msteams-docs#2457]
I think we need something like this, but for Visual Studio extension. The VS and VS Code extensions are different enough that it's difficult to take this walkthrough and try to use it in Visual Studio.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ddadffa-9c95-9d7a-e609-70c31c3cafcf
* Version Independent ID: db1012ca-9813-e09d-e4dd-93fc807ada06
* Content: [Get started - Build your first app overview and prerequisites - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/build-your-first-app/build-first-app-overview)
* Content Source: [msteams-platform/build-your-first-app/build-first-app-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/build-your-first-app/build-first-app-overview.md)
* Product: **msteams**
* GitHub Login: @heath-hamilton
* Microsoft Alias: **lajanuar**

**Comment by RamaMohanaChary** [comment]
Hi @aosolis,

Could you please have a look on this [document](https://docs.microsoft.com/en-us/microsoftteams/platform/toolkit/visual-studio-overview) which creates an app with the Teams Toolkit and Visual Studio.

**Comment by Trinetra-MSFT** [comment]
@aosolis , We will work with Documentation Teams to enhance the document

**Comment by Mahesh2516** [comment]
This issue will be closed with PR 2889.
