### ISSUE TITLE
Number of conversations

### ISSUE THREAD

**Issue by beeme1mr** [MicrosoftDocs/msteams-docs#246]
The documentation says there are three different types of conversations but only lists "teams" and "personal".  Is there a third one or are the docs simply wrong?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d266eb0-2a29-db56-aeaf-dd14dfcdbe66
* Version Independent ID: d7a1fa1d-c083-9232-2259-4f8b267c7ee3
* Content: [Send and receive messages with a bot - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/bots/bot-conversations/bots-conversations#feedback)
* Content Source: [msteams-platform/concepts/bots/bot-conversations/bots-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/bots/bot-conversations/bots-conversations.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Wajeed-msft** [comment]
Third one is groupchat which is still in [Developer Preview](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/dev-preview/developer-preview-features#adding-tabs-and-bots-to-chats). We will update the documentation.

**Comment by NormSohl** [comment]
Thanks, Wajeed.  The change has been made and is now live in the docs.
