### ISSUE TITLE
Show JSON example of Receipt card

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#2462]
Please add sample card JSON for [Receipt card](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference#receipt-card) similar to [other cards](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference#example-office-365-connector-card). 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Cards Reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference#receipt-card)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Nikitha-MSFT** [comment]
Card Json:
```
{
      "contentType": "application/vnd.microsoft.card.receipt",
      "content": {
        "title": "John Doe",
        "facts": [
          {
            "key": "Order Number",
            "value": "1234"
          },
          {
            "key": "Payment Method",
            "value": "VISA 5555-****"
          }
        ],
        "items": [
          {
            "title": "Data Transfer",
            "image": {
              "url": "https://github.com/amido/azure-vector-icons/raw/master/renders/traffic-manager.png"
            },
            "price": "$ 38.45",
            "quantity": "368"
          },
          {
            "title": "App Service",
            "image": {
              "url": "https://github.com/amido/azure-vector-icons/raw/master/renders/cloud-service.png"
            },
            "price": "$ 45.00",
            "quantity": "720"
          }
        ],
        "total": "$ 90.95",
        "tax": "$ 7.50",
        "buttons": [
          {
            "type": "openUrl",
            "title": "More information",
            "image": "https://account.windowsazure.com/content/6.10.1.38-.8225.160809-1618/aux-pre/images/offer-icon-freetrial.png",
            "value": "https://azure.microsoft.com/en-us/pricing/"
          }
        ]
      }
    }
```

Image:
![image](https://user-images.githubusercontent.com/61688740/104423380-09a8ff80-55a4-11eb-8e13-3f5d5f2125db.png)
