### ISSUE TITLE
The button of the messaging extension is not displayed on android mobile device

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#2466]
**Issue:**
The button of the messaging extension is not displayed on android mobile device, but it does on the web application.

**Workaround:**
N/A

**Reference:**
https://github.com/microsoft/BotBuilder-Samples/issues/2918 posted by: @IreneG0802

**Internal Bug Tracker**: [1373069](https://domoreexp.visualstudio.com/MSTeams/_workitems/edit/1373069)

Please continue to follow this issue for updates/progress/questions.

**Comment by Mallipriya-MSFT** [comment]
@Wajeed-msft, The bug got resolved.
