### ISSUE TITLE
Code Samples Point to Invalid Locations

### ISSUE THREAD

**Issue by HiltonGiesenow** [MicrosoftDocs/msteams-docs#2468]
The "Additional Samples" link at the bottom of the article has invalid MySite links that don't seem to go anywhere.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9549caa9-99a2-2568-19a5-f21a79292e2f
* Version Independent ID: f2100d03-b88a-34b2-44a2-935231e89db0
* Content: [Single sign-on support for bots - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/authentication/auth-aad-sso-bots)
* Content Source: [msteams-platform/bots/how-to/authentication/auth-aad-sso-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/bots/how-to/authentication/auth-aad-sso-bots.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Trinetra-MSFT** [comment]
@HiltonGiesenow , Yes, We are working on updating the links, It will be done soon.

**Comment by HiltonGiesenow** [comment]
glad to hear, thanks

**Comment by v-rodriguezd** [comment]
Issue resolved as per PR #2467 https://github.com/MicrosoftDocs/msteams-docs/pull/2467 and as per inputs received from @Trinetra-MSFT
