### ISSUE TITLE
Describe payload details when invoked from various contexts

### ISSUE THREAD

**Issue by aosolis** [MicrosoftDocs/msteams-docs#2469]
The doc just says "In addition to the standard bot activity properties...". What are those? Need to describe them for actions invoked from the following places:
- 1:1 chat
- group chat
- channel (new post)
- channel (reply to thread)
- command box

The documentation is also missing channelData.source.name

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e04556b-f4b1-316e-bac1-ca77c6ab287f
* Version Independent ID: 2ee29289-b250-4ba3-e957-7a42122a266e
* Content: [Create and send the task module - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/action-commands/create-task-module?tabs=dotnet)
* Content Source: [msteams-platform/messaging-extensions/how-to/action-commands/create-task-module.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/messaging-extensions/how-to/action-commands/create-task-module.md)
* Product: **msteams**
* GitHub Login: @clearab
* Microsoft Alias: **anclear**

**Comment by Mallipriya-MSFT** [comment]
@KirtiPereira, 
Payload activity properties when invoked a task module from different places are listed below:
**1:1**
![image](https://user-images.githubusercontent.com/73868678/104317920-aae07900-5504-11eb-9bca-a6388045a822.png)

**Group Chat / Channel (new post) / Channel (reply to thread)**
![image](https://user-images.githubusercontent.com/73868678/104318126-f72bb900-5504-11eb-91a5-c02e54768669.png)

**Command Box**
![image](https://user-images.githubusercontent.com/73868678/104318304-3b1ebe00-5505-11eb-9f54-e733141fe7e4.png)
