### ISSUE TITLE
Audio source switching when joining a meeting

### ISSUE THREAD

**Issue by KondRoll** [MicrosoftDocs/msteams-docs#2476]
Sometimes when I joining a some meeting (in browser) my audio source is automatically switches to a internal sound from my device. Then I have to go to the audio settings and I must switch to microphone. This is a very problematic bug that causes a lot of unpleasantness, especially in official meetings.
Thanks for any help.
Have a nice day.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19ddf42e-0a47-7717-52d4-e549155480a2
* Version Independent ID: 4bbe9beb-233f-cfd5-097b-f280aab5fde8
* Content: [Microsoft Teams developer support and feedback - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/feedback#product-support-channels)
* Content Source: [msteams-platform/feedback.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/feedback.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Manish-MSFT** [comment]
Hi @KondRoll , Thanks for reaching out to us. We are the developer support team for Microsoft teams focused on helping developers resolve their code issues. For issues related to teams product, please reach out to the [Product support channels](https://docs.microsoft.com/en-us/microsoftteams/platform/feedback#product-support-channels) for Microsoft Teams.
