### ISSUE TITLE
Remove duplicate info and fix note formatting

### ISSUE THREAD

**Issue by heath-hamilton** [MicrosoftDocs/msteams-docs#2477]
I'm not sure the following note (on lines 24-26) is needed. It basically duplicates content under **4. Sideload your app in Teams**. The space between "> [!NOTE]" and the rest of the text is breaking the note formatting, too.

Also, if the toolkit now lets you skip the `npm install` and `npm start` steps, should we just remove those? This doc needs to reflect our fastest path to "Hello, World!"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f876156-cc1e-468f-4647-5143a5de03b1
* Version Independent ID: 618f43a3-3371-ad99-13aa-087b9303298c
* Content: [Get started - Build and run your first app - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/build-your-first-app/build-and-run)
* Content Source: [msteams-platform/build-your-first-app/build-and-run.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/build-your-first-app/build-and-run.md)
* Product: **msteams**
* GitHub Login: @heath-hamilton
* Microsoft Alias: **lajanuar**

**Comment by RamaMohanaChary** [comment]
@heath-hamilton 

It's a format issue in the document, there is not technical assistance required here. Document team will react on this question.

**Comment by heath-hamilton** [comment]
This ticket should be resolved once https://github.com/MicrosoftDocs/msteams-docs/pull/2551 has merged. Thanks!
