### ISSUE TITLE
Overlapping/Flashing Video Seams 

### ISSUE THREAD

**Issue by AdamDavidHill** [MicrosoftDocs/msteams-docs#2479]
I had a video conference call this morning.
The edges of each person's video feed were flickering and exceedingly distracting/annoying.
On closer inspection I noticed that the seams, i.e. joins between video feeds, were slightly mismatched with the overlaid black grid lines. The flicker was specific to the thin overlapped area, where one person's feed pokes into the area of another's. It's out by up to about 3 pixels. If these overlaid lines were lined up accurately it would probably hide the flicker.
Possibly relevant is that my screen resolution is 5120 x 1440. Not sure if it's maybe a precision/rounding issue in the UI / layout?
Attaching a screenshot showing the overlap...
 
![MS Teams Border Flicker](https://user-images.githubusercontent.com/4968782/102475822-468be000-4052-11eb-9917-59b8358e4751.png)

**Comment by VaraPrasad-MSFT** [comment]
For queries related to Teams Product, Could you please reach out to [Product Support Channel](https://docs.microsoft.com/en-us/microsoftteams/platform/feedback#product-support-channels).
