### ISSUE TITLE
Error in document

### ISSUE THREAD

**Issue by jaisendmehtc** [MicrosoftDocs/msteams-docs#248]
Hi there,

There is a defect in following mentioned link.
https://msdn.microsoft.com/en-us/library/microsoft.owin.security.oauth.oauthauthorizationserverprovider(v=vs.113).aspx

Please scroll to "Properties" and go to "OnGrantCustomExtension".

I believe that word "andpoint" in line "Called when a request to the Token andpoint arrives with a "grant_type" of any other value" should be written as "endpoint".

Thanks,
Jai

**Comment by billbliss** [comment]
Unfortunately the file isn't under our control so we can't fix it.
