### ISSUE TITLE
MSAL version of Silent Auth?

### ISSUE THREAD

**Issue by GauravES** [MicrosoftDocs/msteams-docs#2480]
[Enter feedback here]
ADAL is deprecated; is there an MSAL sample for Silent Auth?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2e66ffa-ec00-4a84-a43d-d47e3c138b32
* Version Independent ID: 47e9a383-ac6a-dc7d-2d91-a9e09626fdab
* Content: [Silent authentication - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-silent-aad)
* Content Source: [msteams-platform/tabs/how-to/authentication/auth-silent-aad.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tabs/how-to/authentication/auth-silent-aad.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Manish-MSFT** [comment]
@GauravES , Hi This sample has implementation of MSAL authentication [this](https://github.com/pnp/teams-dev-samples/tree/master/samples/tab-sso). Let me know if you are still facing issues.

**Comment by Trinetra-MSFT** [comment]
@GauravES , Could you please look at following [sample codes](https://github.com/Azure-Samples/ms-identity-javascript-v2) built using [MSAL library](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples)? Let me know if this helps you or not
