### ISSUE TITLE
404 on doc URL

### ISSUE THREAD

**Issue by royshea** [MicrosoftDocs/msteams-docs#2483]
Link to "Settings Interface" in the last paragraph of https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/configuration-page#configuring-a-channel-or-group-chat-tab with target of https://docs.microsoft.com/en-us/javascript/api/@microsoft/teams-js/microsoftteams.settings.settings?view=msteams-client-js-latest&preserve-view=true gives a 404.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b94a38e-82f8-45a1-8ccc-b0a96edd0404
* Version Independent ID: 6e077924-9658-cdd2-50de-0f9561d6366b
* Content: [Create a configuration page - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/configuration-page)
* Content Source: [msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Manish-MSFT** [comment]
We are creating a doc bug for this.

**Comment by Trinetra-MSFT** [comment]
@royshea , Thanks for sharing the document feedback. I will ask document team to update the link ASAP

**Comment by Trinetra-MSFT** [comment]
@KirtiPereira , Could you please help to fix the broken link in screenshot (setting interface) to below mentioned link?
![image](https://user-images.githubusercontent.com/50989436/102615110-5fcc8380-415b-11eb-96f3-41be55b95149.png)

_Link needs to be added:_ [https://docs.microsoft.com/en-us/javascript/api/@microsoft/teams-js/_settings?view=msteams-client-js-latest](https://docs.microsoft.com/en-us/javascript/api/@microsoft/teams-js/_settings?view=msteams-client-js-latest).
Please take this reference [document ](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/configuration-page#configuring-a-channel-or-group-chat-tab)which needs a link update
