### ISSUE TITLE
File upload failed in Microsoft Teams 

### ISSUE THREAD

**Issue by mMARUF** [MicrosoftDocs/msteams-docs#2486]
### OS:

Windows 10 64 Bit
Microsoft Teams Windows application and web link via any browser

### Steps to Reproduce: 

1/ Go to MS Teams Web Link (https://teams.microsoft.com/_#/conversations/) or Windows application
2/ Try to attach any file (ex- image, txt file) to send 

### Actual Result: 
Often we cannot attaching process fails.  We have to try 3/4 times to send a file successfully which is really bothering experience(see the attachment).  The problem occurs if you try drag and drop any file to send and also while trying to upload via browsing for file in the pc and then attaching.
 
### Expected Result: 
File sending process should work every time without fail like WhatsApp.  

### Attachment of the bug: 

![File upload failed](https://user-images.githubusercontent.com/45368054/102705184-c4e4be00-42ae-11eb-945a-d803dd245d04.gif)

**Comment by Trinetra-MSFT** [comment]
@mMARUF , I tried to upload file but unable to repro this issue.  
![image](https://user-images.githubusercontent.com/50989436/102740265-68000b00-4375-11eb-9259-aa0f0659f019.png), Could you please tell me which teams version you are running?

**Comment by mMARUF** [comment]
@Trinetra-MSFT, the reproducing rate is not 100%. But, I often face this problem. That is why I have attached the GIF file for better understading.

**Comment by mMARUF** [comment]
@Trinetra-MSFT, I did not try for JSON file, I tried with .txt  file and .png file. And, in both the cases, I successfully reproduced the bug.

**Comment by Trinetra-MSFT** [comment]
@mMARUF , I checked for `.txt` and `.png` as well but no luck to reproduce this
![image](https://user-images.githubusercontent.com/50989436/102763064-2a17dc80-439f-11eb-9805-fa63739c7771.png)

**Comment by Trinetra-MSFT** [comment]
@mMARUF, I'm marking this as `TeamsProduct `query where you can get the right assistance regarding this
