### ISSUE TITLE
Is there a way to save information in client side for teams apps?

### ISSUE THREAD

**Issue by piyumi25** [MicrosoftDocs/msteams-docs#2488]
In Microsoft Addins , there is office.context.roamingSettings to save information in client side. I need to know is there a way in teams also. I am creating a connector app and I do not want to show login UI in configuration page when user tries to configure connector all the time. I just want to show login UI only once and then need to have a way to save those information in client side.

Can some one help me to find solution for this?

**Comment by Mallipriya-MSFT** [comment]
@piyumi25, yes it is possible to save information. Once user logs in, using the auth token you can fetch the details of an user using [Get UserGraph API](https://docs.microsoft.com/en-us/graph/api/user-get?view=graph-rest-1.0&tabs=http)

**Comment by piyumi25** [comment]
> @piyumi25, yes it is possible to save information. Once user logs in, using the auth token you can fetch the details of an user using [Get UserGraph API](https://docs.microsoft.com/en-us/graph/api/user-get?view=graph-rest-1.0&tabs=http)

@Mallipriya-MSFT  I am not using Azure authentication. I am using our own login page. So once user login to our website I need to save the userID in clientside and if user already logged in I do not want to show login UI when reconfiguring the connector

**Comment by Mallipriya-MSFT** [comment]
@piyumi25, you can use Azure blob storage or Azure storage table to save information.
