### ISSUE TITLE
Sometime image displayed is not correct on chat.

### ISSUE THREAD

**Issue by nitdgpvijay** [MicrosoftDocs/msteams-docs#2491]
Sometime I could see image displayed is not correct, it displayed image of last person with you chat with.
It happens once , when you type new message it fixes.

Please check screen shot, I just started chat with Saurabh , but I showed image of Sukhada!.

![image](https://user-images.githubusercontent.com/25844895/102775038-1a55c380-43b2-11eb-904d-df1eabafb85b.png)

**Comment by RamaMohanaChary** [comment]
@nitdgpvijay:

Could you please contact [Product Support Channels](https://docs.microsoft.com/en-us/microsoftteams/platform/feedback#product-support-channels).
