### ISSUE TITLE
Audiodg.exe process memory utilization goes high while loading Teams meeting

### ISSUE THREAD

**Issue by jithu1980** [MicrosoftDocs/msteams-docs#2494]
Steps to follow:
- Login to teams
- Go to Calendar
- Click on a scheduled meeting
- Click on join button and a new window comes to to click on on "Join Now" button to join the meeting.
- Do not click on the button and see the task manager "audiodg.exe" process.
- The process keeps on eating RAM until it takes entire memory which makes the system unresponsive.
- This happens every time

**Comment by VaraPrasad-MSFT** [comment]
For queries related to Teams product , could you please reach out to [Product Support Channels](https://docs.microsoft.com/en-us/microsoftteams/platform/feedback#product-support-channels).
