### ISSUE TITLE
Can't find 'Upload a custom app link' in teams

### ISSUE THREAD

**Issue by avEggHead** [MicrosoftDocs/msteams-docs#2501]
I've enabled Developer Mode, but the Upload a custom app link option is nowhere to be found.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 008da4e2-979e-c396-db28-4acf57deb530
* Version Independent ID: f1413f77-5eb3-e1fd-9235-d322d6e4eb6c
* Content: [Developer Preview - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/dev-preview/developer-preview-intro)
* Content Source: [msteams-platform/resources/dev-preview/developer-preview-intro.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/resources/dev-preview/developer-preview-intro.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Manish-MSFT** [comment]
@avEggHead , Hi You need to enable custom teams apps uploading, have you followed [this](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/prepare-your-o365-tenant#enable-custom-teams-apps-and-turn-on-custom-app-uploading) link?

**Comment by avEggHead** [comment]
Thank you!  It is working now.
