### ISSUE TITLE
Styling error in the "Authentication flow for bots in Microsoft Teams" page

### ISSUE THREAD

**Issue by LordLydon** [MicrosoftDocs/msteams-docs#2502]
Steps 5-11 are shown inside the Note box.
https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/authentication/auth-flow-bot

![image](https://user-images.githubusercontent.com/9642693/103009685-22724800-4505-11eb-9934-ec572fc9ed91.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d1ce448-e51e-73db-ba9a-53faf4a16d11
* Version Independent ID: 09c2500a-3841-c6c9-82c0-5e10dc2d9c7c
* Content: [Microsoft Teams Authentication flow for bots - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/authentication/auth-flow-bot)
* Content Source: [msteams-platform/bots/how-to/authentication/auth-flow-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/bots/how-to/authentication/auth-flow-bot.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Manish-MSFT** [comment]
@LordLydon , Hi we have raised a doc bug for this with id 1425536.
