### ISSUE TITLE
App to support different data center/regions - instead of having duplicate apps with similar functionality and the difference is Data Centers. Please provide a dev documentaion with sample code for partners to make the necessary changes.

### ISSUE THREAD

**Issue by ismailMSFT** [MicrosoftDocs/msteams-docs#2516]
[ Instead of having duplicate apps with similar functionality and the difference is Data Centers, could you please look to add different region domains in the ‘welcome message/configuration screen’ within the single app where user tries to login by selecting their domain.

Ex: Zoho Projects which is available in Teams store
If you need further more details we are happy to jump into a call. Please revert with your convenient date and time including time zone so that we can setup a Teams call.]

@Wajeed-msft 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b294c444-a6ae-a5e7-4f65-26715b1a3cf6
* Version Independent ID: 5df1b473-c136-64f6-b818-c34d0239cd1c
* Content: [Tips and frequently failed cases - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases?source=docs)
* Content Source: [msteams-platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Nikitha-MSFT** [comment]
Thanks for reporting. We are looking into it.
