### ISSUE TITLE
PowerApps in Task Module not logged in when using Teams Desktop

### ISSUE THREAD

**Issue by quennethks** [MicrosoftDocs/msteams-docs#2527]
We've developed a messaging extension in Microsoft Teams that would open up a Power App we've built as a Task Module. When we use it on the browser, it works just fine and opens the app. 

However, when we use it in Teams Desktop, we're getting a prompt to sign-in. When we do click on sign-in, it opens up a browser instead and doesn't work within the Teams app.

![image](https://user-images.githubusercontent.com/20659375/103361709-3cf38500-4af4-11eb-8c4f-dbd6e9647ee9.png)

I found similar issue (https://github.com/MicrosoftDocs/msteams-docs/issues/2338) and added the webApplicationInfo in the app manifest. But doesn't seem to work.

**Comment by RamaMohanaChary** [comment]
Thank you for reaching out to us, we will investigate and if we require further information we will reach out.
Thanks, 
Rama
Teams Dev Community Response

**Comment by RamaMohanaChary** [comment]
Hi @quennethks,

Have you tried using the given [document](https://docs.microsoft.com/en-us/powerapps/user/open-app-embedded-in-teams)? if yes could you please share your manifest to try out from our end.

**Comment by quennethks** [comment]
Hi @RamaMohanaChary,

It's not actually a tab. Rather, it's part of a messaging extension and gets displayed as task module.

![image](https://user-images.githubusercontent.com/20659375/103884206-329b4180-5119-11eb-9fa3-4683fd678bb3.png)

When I click on the Create CW Ticket, it opens the task module with the url to the Powerapp with url parameters about the teams message selected.

![image](https://user-images.githubusercontent.com/20659375/103884342-62e2e000-5119-11eb-998b-d1cfa19ae7e2.png)

As for the manifest, I'm attaching it here. Hope this clarifies the issue.
[GISPowerAppBot (6).zip](https://github.com/MicrosoftDocs/msteams-docs/files/5781144/GISPowerAppBot.6.zip)

**Comment by RamaMohanaChary** [comment]
Could you please add below section,

"webApplicationInfo": {
    "id": "YourAppId",
    "resource": "https://apps.powerapps.com"
  }

in your app manifest

**Comment by ChetanSharma-msft** [comment]
Hello @quennethks - Could you please confirm whether you are still facing this issue?
