### ISSUE TITLE
Port: Outgoing WebHook Activity.ChannelData has invalid teamsTeamId

### ISSUE THREAD

**Issue by clearab** [MicrosoftDocs/msteams-docs#2550]
Ported from: https://github.com/microsoft/botframework-sdk/issues/6145

Original question (please see linked issue for additional information):

> According to the documentation and my understanding the received Activity.ChannelData should include the teamsTeamId - yet even the Example below seems to show an invalid teamId (note that it's exactly the same value as channelId).
> 
> I am experiencing the same issue when receiving such WebHook callbacks.
> 
> That value is not accepted as a valid Teams GroupId - or is my understanding of the value's meaning wrong?
> If so, how can I get the actual GroupId of the Channel (required for all Channel GraphApi calls)? It's nowhere to be found in the received Activity...
> 
> Thanks in advance

**Comment by Nikitha-MSFT** [comment]
We are not able to repro the issue at our end. when you send message to outgoing web-hook from general channel you will receive the team-id and channel id as same, for other channels you will receive the different channel-id. Could you please check [outgoing web-hook sample](https://github.com/OfficeDev/microsoft-teams-sample-outgoing-webhook)?

**Comment by dviry** [comment]
I think the confusion I referenced in the docs is that the received "team-id" is unusable for any other GraphAPI query - maybe a better distinction of what this "team-id" means is in order?

It also seems suspicious to receive the same value for "team-id" and "channel-id" (even if only for the General channel), don't you think? Still leaves the open question how an outgoing web-hook can receive the correct GraphAPI TeamId for calling any other Chat queries.

Thanks in advance

**Comment by Nikitha-MSFT** [comment]
When you create Team the general channel is created as default which will have id same id as team id. This is by design. and for other channel we are receiving the correct id for the outgoing web-hook.

**Comment by dviry** [comment]
I think the naming is misleading and the documentation is unclear on this.

When you say "correct id for the outgoing web-hook" - yet I cannot use it to make ANY GraphAPI/Teams calls it puzzles me so I'll ask again:

ALL GraphAPI/Teams methods require a "TeamId" - yet what an "outgoing web-hook" is not working, so where do I get it?

That is not specified in the Documentation nor a comment that makes it clear it's not the same "TeamId" (except they share the same name). I realize that you are probably not in charge of the implementation - maybe that should be a separate ticket/question to the MS Team (in "Teams"?) that actually develops the "outgoing web-hook".

Thanks

**Comment by Nikitha-MSFT** [comment]
Yes, you cannot use that id to call graph API. We are checking it internally.

**Comment by Nikitha-MSFT** [comment]
Currently Outgoing web-hook does not give the GUID of the group. We have raised a feature request. We don't have ETA to share when it will be available.
