### ISSUE TITLE
Deep link to configurable tab: Issue

### ISSUE THREAD

**Issue by liangchr** [MicrosoftDocs/msteams-docs#2552]
Something is wrong with my deep link to a configurable tab. I followed: https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links

Bot sends card into channel with button (type: 'Action.OpenUrl') and when I click on the link it does not send me to the correct configurable tab. Instead, it jumps to the first team on my team list and goes to the posts tab for that. It doesn't even go to the correct team. 

let encodedWebUrl = encodeURI('https://tasklist.example.com/');
let encodedContext = encodeURI('{"channelId": "19:6418b36ec8a242a48d817b08c9362a50@thread.skype"}');
let appId="a79c6959-0c6d-4353-a22c-682611b86c5f";
let entityId="notes_by_channel_christina"; (this is set with: microsoftTeams.settings.registerOnSaveHandler)
let label = "randomString"

let finalDeepLinkUrl = `https://teams.microsoft.com/l/entity/${appId}/${entityId}?webUrl=${encodedWebUrl}&label=${label}&context=${encodedContext}`;

Any help is greatly appreciated. Also, is there a working deep link sample/boilerplate somewhere?

**Comment by Nikitha-MSFT** [comment]
We are not able to repro the issue at our end. Could you please check the below example:
https://teams.microsoft.com/l/entity/565c2398-15f0-4dcc-99e2-987094e80d2c/final?webUrl=https%3A%2F%2F09763eddc368.ngrok.io%2Ffinal%0A&label=final&context=%7B%22channelId%22%3A%20%2219%3A6decf54d86d945e4b3924b63a9161a78%40thread.skype%22%7D
