### ISSUE TITLE
In which context the Tab will be available if we specify meetingStage in context.

### ISSUE THREAD

**Issue by sharmajnu** [MicrosoftDocs/msteams-docs#2554]
What is the meaning of meetingStage under configurableTabs context as shown below.

![image](https://user-images.githubusercontent.com/8476119/103664497-5aaf6700-4f98-11eb-95e9-b395ff0f96cc.png)

I couldn't find any explanation about it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f94a488-d636-92b3-21eb-c88744c8f272
* Version Independent ID: 7b3413f4-9ade-accf-5cb2-83fead11a32a
* Content: [Manifest schema reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema#configurabletabs)
* Content Source: [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/resources/schema/manifest-schema.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by RamaMohanaChary** [comment]
@sharmajnu:

Could you please have a look on this [document](https://docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/design/designing-apps-in-meetings), you will get more idea about Meeting Stage.
