### ISSUE TITLE
Can I generate deep links to website tabs? (in MSTeams)

### ISSUE THREAD

**Issue by liangchr** [MicrosoftDocs/msteams-docs#2555]
If I use graph api I can add a website tab to a team: https://docs.microsoft.com/en-us/graph/teams-configuring-builtin-tabs

Can I create deep links and send them in the channel in a card for the user to navigate to a website tab? (not a custom tab type)

**Comment by Mallipriya-MSFT** [comment]
Hi @liangchr,  yes, you can create deeplink to a tab and can navigate to it on click of button posted in a channel. Please refer to [the docs](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links#generating-a-deep-link-to-your-tab).

**Comment by liangchr** [comment]
@Mallipriya-MSFT I need to clarify something. Do website tabs even have entityId's to add to the deep link url to begin with? Not referring to custom tabs, but website tab types.

**Comment by Mallipriya-MSFT** [comment]
@liangchr, Can you help me to understand what does a website tab mean? If it is an content Url of an website, then it should be an IFrame-able one to integrate it as a tab and have to make sure that website url domain has to added in the valid domains array of the manifest. While adding a tab, it is mandatory to provide Entity ID, using which you can deeplink.

**Comment by liangchr** [comment]
@Mallipriya-MSFT 

Website tab is explained here: https://docs.microsoft.com/en-us/graph/teams-configuring-builtin-tabs#website-tabs
In other words, it is this thing: 
<img width="368" alt="Screen Shot 2021-01-07 at 5 35 39 PM" src="https://user-images.githubusercontent.com/10538763/103963718-d3d0ca80-510e-11eb-879f-ffd9f17d5838.png">

I want to be able to deep link to this

**Comment by RamaMohanaChary** [comment]
Hi @liangchr,

Yes, you can create the deeplink to website using the content URL and website URL. Could you please check these [docs](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links#generating-a-deep-link-to-your-tab).

**Comment by Trinetra-MSFT** [comment]
@liangchr , Please feel free to reopen this issue if you have further query on this.
