### ISSUE TITLE
botID??????

### ISSUE THREAD

**Issue by jxs0900** [MicrosoftDocs/msteams-docs#256]
When does the boId get created for a bot and where in the heck do you find it?  

"bots": [
		{
			"botId": "00000000-0000-0000-0000-000000000000",
			"needsChannelSelector": false,
			"isNotificationOnly": false,
			"scopes": [
				"team",
				"personal"
			]
		}
	],

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b849c477-8956-660d-eb91-263f1ecf6994
* Version Independent ID: 71eb8427-3bcf-3d83-61be-90bc1523a16f
* Content: [Get started - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/get-started/get-started)
* Content Source: [msteams-platform/get-started/get-started.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/get-started/get-started.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by billbliss** [comment]
The bot ID is the app ID you get when you create the bot. See https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/bots/bots-create for more information.
