### ISSUE TITLE
Error occurred after publish the connector app in to Azure app service

### ISSUE THREAD

**Issue by piyumi25** [MicrosoftDocs/msteams-docs#2561]
I created an office365 connector app and it worked as expected for ngrok. I published the connector app to Azure app service as a normal web application using VS Code. I am getting following error when calling "saveEvent.notifySuccess()".

![image](https://user-images.githubusercontent.com/33615108/103757833-55edc000-5037-11eb-9cf5-73b7e7a41ab2.png)

Can some one help me to fix the issue?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da50e4db-a713-ab8b-d27b-89aa946619d0
* Version Independent ID: 57e368e2-aaed-fa8d-ed49-cc18e594ab1d
* Content: [Office 365 Connectors - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-creating)
* Content Source: [msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Wajeed-msft** [comment]
@piyumi25 - Could you please confirm if your valid domains are updated in [Connector dashboard](https://outlook.office.com/connectors/publish) to reflect your deployed URL?

![image](https://user-images.githubusercontent.com/31851992/103795035-7c2d5300-506b-11eb-9cdc-4aafa3af62fd.png)

**Comment by piyumi25** [comment]
> @piyumi25 - Could you please confirm if your valid domains are updated in [Connector dashboard](https://outlook.office.com/connectors/publish) to reflect your deployed URL?
> 
> ![image](https://user-images.githubusercontent.com/31851992/103795035-7c2d5300-506b-11eb-9cdc-4aafa3af62fd.png)

Yes it is updated. But i added domain without ´https´

**Comment by piyumi25** [comment]
@Wajeed-msft Can I know what are the possible causes for getting an error as above?

**Comment by Wajeed-msft** [comment]
Could you please share your app manifest so that we can check?

**Comment by piyumi25** [comment]
@Wajeed-msft this is the manifest

```
{
  "$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.8/MicrosoftTeams.schema.json",
  "manifestVersion": "1.8",
  "id": "bd871585-4766-4cda-afc7-7b813f115030",
  "version": "1.0.2",
  "packageName": "com.CTOffice365Connector-ver 1.0.2",
  "developer": {
    "name": "Davton",
    "websiteUrl": "https://ct-office365connector.azurewebsites.net",
    "privacyUrl": "https://ct-office365connector.azurewebsites.net/privacy.html",
    "termsOfUseUrl": "https://ct-office365connector.azurewebsites.net/tou.html"
  },
  "name": {
    "short": "CTOffice365Connector-ver 1.0.2",
    "full": "CTOffice365Connector-ver 1.0.2"
  },
  "description": {
    "short": "Create webhooks for CT",
    "full": "Create webhooks for CT"
  },
  "icons": {
    "outline": "outline.png",
    "color": "color.png"
  },
  "accentColor": "#FFFFFF",
  "configurableTabs": [],
  "staticTabs": [],
  "bots": [],
  "connectors": [
    {
      "connectorId": "bd871585-4766-4cda-afc7-7b813f115030",
      "configurationUrl": "https://ct-office365connector.azurewebsites.net/ctConnector/config.html?name={loginHint}&tenant={tid}&group={groupId}&theme={theme}",
      "scopes": [
        "team"
      ]
    }
  ],
  "composeExtensions": [],
  "permissions": [
    "identity",
    "messageTeamMembers"
  ],
  "validDomains": [
    "ct-office365connector.azurewebsites.net",
    "app.customerthermometer.com",
    "api.customerthermometer.com"
  ],
  "showLoadingIndicator": true,
  "isFullScreen": true
}
```

**Comment by RamaMohanaChary** [comment]
Hi @piyumi25,

Sorry for delayed response!

microsoftTeams.settings.setSettings should be written under save event function to save the provided data. 
Please have a look on this [code](url
![image](https://user-images.githubusercontent.com/71380905/107511425-7b885f00-6bcb-11eb-9ad2-12ea823a18d1.png)
).

Could you please go through this [document](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-creating) and try this [sample code](https://github.com/OfficeDev/microsoft-teams-sample-connector-csharp/blob/master/TeamsToDoAppConnector/Views/Connector/Setup.cshtml).
