### ISSUE TITLE
Jump from one tab to another with the click of a button 

### ISSUE THREAD

**Issue by liangchr** [MicrosoftDocs/msteams-docs#2564]
Is it possible for a user to click a deep link in one tab and jump to another tab? If so how? 

Eg. using: microsoftTeams.executeDeepLink(/*deepLink*/);

**Comment by Nikitha-MSFT** [comment]
Yes, you can Redirect to user from one tab to other tab using Deeplink. Could you please check this [docs](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links#deep-linking-to-your-tab)?

**Comment by liangchr** [comment]
@Nikitha-MSFT  Thanks for the help! You answered my question perfectly. 

Would it be possible to trouble you with a second question? If it possible to deep link to a website tab type? 
e.g this: https://docs.microsoft.com/en-us/graph/teams-configuring-builtin-tabs#website-tabs
<img width="368" alt="Screen Shot 2021-01-07 at 5 35 39 PM" src="https://user-images.githubusercontent.com/10538763/103963874-1397b200-510f-11eb-84a6-481d4e82ff62.png">

is it possible to deep link to these kinds of tabs?

**Comment by Nikitha-MSFT** [comment]
To create a Deeplink, you require the entityId,contentUrl, websiteUrl. If you have these properties you can deeplink to any tab. Currently you cannt deeplink to the website tab. This is by design.
