### ISSUE TITLE
Hello world sample does not run

### ISSUE THREAD

**Issue by Navyjetfixer** [MicrosoftDocs/msteams-docs#257]
The Hello World Team App will build, but when running under Debug mode get the following error:
Could not find a part of the path 'D:\Teams_Repos\msteams-samples-hello-world-csharp\Microsoft.Teams.Samples.HelloWorld.Web\bin\roslyn\csc.exe'.  Looking at my directory, there is no roslyn directory under the bin folder

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ea2882a-b341-b29d-e2b3-b51ea47c8643
* Version Independent ID: d4807393-f610-5df6-37cf-d9975e63371c
* Content: [Get started with C#/.NET - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/get-started/get-started-dotnet)
* Content Source: [msteams-platform/get-started/get-started-dotnet.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/get-started/get-started-dotnet.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by jxs0900** [comment]
Explain the botId further please, you never explain where it comes from or how to get it.

**Comment by Wajeed-msft** [comment]
@jxs0900 :
Here is the documentation on [Creating a new bot](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/bots/bots-create). Microsoft App Id created in this process is your Bot Id. 

@Navyjetfixer :
For missing "csc.exe" could you please delete your packages folder and restore packages one more time.

**Comment by mtickle** [comment]
Navyjetfixer, 

Run this in Package Manager Console:

update-package Microsoft.CodeDom.Providers.DotNetCompilerPlatform -r

**Comment by Navyjetfixer** [comment]
Deleted packages and ran package update in Package Manager Console and it works as advertised. Thank you for your help, bug resolved.
