### ISSUE TITLE
What is the maximum size of content at incoming webhook? 

### ISSUE THREAD

**Issue by wenrongwu** [MicrosoftDocs/msteams-docs#2574]
What is the maximum size of content from incoming webhooks?  I am having issues with 15,553 bytes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28316a67-22fa-8a05-1ae0-fbe1c5720ef9
* Version Independent ID: 8a250e46-2a30-af86-839d-9f83a8b48041
* Content: [Sending messages to Connectors and Webhooks - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-using)
* Content Source: [msteams-platform/webhooks-and-connectors/how-to/connectors-using.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/webhooks-and-connectors/how-to/connectors-using.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Manish-MSFT** [comment]
@wenrongwu , could you please attach a link of file that you are trying to send?

**Comment by Manish-MSFT** [comment]
@wenrongwu : And also please add repro step to reproduce this issue.
