### ISSUE TITLE
Is there a python Teams SSO example?

### ISSUE THREAD

**Issue by lzhang-chata** [MicrosoftDocs/msteams-docs#2575]
1. Picture here (https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/authentication/auth-aad-sso-bots#bot-sso-at-runtime ) likes like need to be update. In the picture there is Azure AD V1. However, here (https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-concept-sso?view=azure-bot-service-4.0), it says: "Currently, only the Azure AD v2 identity provider is supported."

2. Do you have a python Teams bot SSO example? I can only find a C# example here (https://github.com/microsoft/BotBuilder-Samples/tree/main/experimental/teams-sso/csharp_dotnetcore). My boss asked me to create a python bot using SSO, i tried to mimical a python bot from (https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/python/46.teams-auth),  but some python libraries are different from C# thus the flow is different from C# and I was blocked.

Thank you very much.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9549caa9-99a2-2568-19a5-f21a79292e2f
* Version Independent ID: f2100d03-b88a-34b2-44a2-935231e89db0
* Content: [Single sign-on support for bots - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/authentication/auth-aad-sso-bots#feedback)
* Content Source: [msteams-platform/bots/how-to/authentication/auth-aad-sso-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/bots/how-to/authentication/auth-aad-sso-bots.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by RamaMohanaChary** [comment]
Hi @lzhang-chata,

Currently we don't have Teams SSO in Python, our development team working on it, will be available soon. At present we don't have any ETA.

**Comment by lzhang-chata** [comment]
Hi @RamaMohanaChary ,

Thank you very much for your response. 

I am not sure MS don't have Teams SSO example in Python or Python doesn't support Teams SSO yet? If python is not able to support Teams SSO now, I will let my boss know, stop my exploration and wait for your good news.

Thank you very much and regards.

**Comment by RamaMohanaChary** [comment]
Hi @lzhang-chata,

We have Teams SSO sample example in C# and in Node.js.
At present, we don't have Teams SSO sample example in Python. It's a feature request.

Could you please raise a [UserVoice](https://microsoftteams.uservoice.com/) for this.
