### ISSUE TITLE
Possible to deeplink to tab and change tab contents dynamically? 

### ISSUE THREAD

**Issue by liangchr** [MicrosoftDocs/msteams-docs#2576]
I was wondering if it is possible to add some extra parameters into the deepLink url so that when a user clicks a deepLink and goes to my tab, my tab can react and can dynamically load a webpage specified in some parameter in the deeplink

**Comment by Nikitha-MSFT** [comment]
Are you trying to Deeplink to the specific Item in the tab? if yes Could you please check this [docs](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links#showing-a-deep-link-to-an-item-within-your-tab)?

**Comment by liangchr** [comment]
@Nikitha-MSFT I am actually trying to navigate to the tab and have the javascript code in the custom tab respond to some parameter in the deeplink and redirect the page. 

So right after the user click the deep link I want two things to happen: 
1.) navigate to tab 
2.) auto-execute javascript code that redirects page 

Do you think this would be possible?

**Comment by edwardmcleodjones** [comment]
@liangchr See the docs at: https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links#consuming-a-deep-link-from-a-tab

> When navigating to a deep link, Microsoft Teams simply navigates to the tab and provides a mechanism via the Microsoft Teams JavaScript library to retrieve the sub-entity ID (if it exists).
> 
> The microsoftTeams.getContext call returns a context that includes the subEntityId field if the tab was navigated to via a deep link.

So you pass the parameter you want as the subEntityId in your deeplink, then retrieve that in the getContext call when your tab is loaded.  You can then take action based on that.

**Comment by Nikitha-MSFT** [comment]
Yes it is possible, as @edwardmcleodjones you can pass the sub entity id and redirect to the tab. Please check this docs for [get context](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/access-teams-context)?
