### ISSUE TITLE
Ability to create a group call in a chat where calling is disabled

### ISSUE THREAD

**Issue by tdranv** [MicrosoftDocs/msteams-docs#2577]
I found out (the hard way) that pressing CTRL + SHIFT + C in the gray area (not in the message box) of a chat where calling is disabled, it still creates a group call.
![image](https://user-images.githubusercontent.com/45210624/103974711-116b3d00-517b-11eb-98e1-93b893cd35a9.png)

**Comment by Jagadeesh-MSFT** [comment]
Hi @tdranv, 
Could you please reach out to product support team.
https://docs.microsoft.com/en-us/microsoftteams/platform/feedback#product-support-channels

**Comment by funnyletter** [comment]
We're also having this problem at my workplace, is there a way to resolve it?

Thanks!

**Comment by v-chetsh** [comment]
@tdranv - Could you please confirm if your issue has resolved or still looking for any help?
