### ISSUE TITLE
reply from mobile notification is not working.

### ISSUE THREAD

**Issue by iburahim786** [MicrosoftDocs/msteams-docs#2578]
"reply" function from mobile notification actually not working.

**Comment by RamaMohanaChary** [comment]
Hi @iburahim786,

Reply notification function in mobile teams app is working fine from our end.
Could you please brief more about your issue? so that we can assist you quickly.

**Comment by iburahim786** [comment]
@RamaMohanaChary , Issue is not reproducible frequently.
