### ISSUE TITLE
please remove one incorrect hyperlink from this article

### ISSUE THREAD

**Issue by ikukoyoneda** [MicrosoftDocs/msteams-docs#2579]
the hyperlink to this URL (https://docs.microsoft.com/en-us/graph/api/resources/notifications-api-overview?view=graph-rest-beta&preserve-view=true) is incorrect. Please remove the link.

I uploaded the screenshot here.
![image](https://user-images.githubusercontent.com/50646036/103984031-b7de2f00-51c9-11eb-845f-d36c16c78984.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b60eeacc-a71e-9644-b869-3e0a4f1506d8
* Version Independent ID: 313bf83f-5325-f9f4-5780-9bc81e315c1e
* Content: [Create apps for teams meetings - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?tabs=json&source=docs)
* Content Source: [msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Manish-MSFT** [comment]
@ikukoyoneda : Could you please tell what's wrong in the referenced link?, I see the notifications link is correctly linked. Sorry, If I missed something.

**Comment by ikukoyoneda** [comment]
@Manish-MSFT  that hyperlink points to Notification API page, but I believe it should be NotificationSignal API, not Notification API.

**Comment by Manish-MSFT** [comment]
@ikukoyoneda : I see that NotificationSignal API isn't available. Could you please provide doc link for the same?

**Comment by Manish-MSFT** [comment]
@ikukoyoneda : We have raised doc-bug for this issue. Thanks for notifying this to us.

**Comment by figgsoftware** [comment]
@Manish-MSFT  But it would actually be super great if we could use the MS Graph Notification API to trigger these dialogs. Then it would be much more flexible in not just being triggered from a Bot.

**Comment by v-ypalikila** [comment]
Hi,

The hyperlink for NotificationSignal API redirects to NotificationSignal [API](https://docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/api-references?tabs=dotnet#notificationsignal-api).

**Comment by surbhigupta12** [comment]
Closing this PR based on @v-ypalikila comment.
