### ISSUE TITLE
Add a graphic preview for each concepts

### ISSUE THREAD

**Issue by seaSide974** [MicrosoftDocs/msteams-docs#258]
It would be interesting to see what is apps for teams, tabs, bot, on this page ? So that the developer can explore the capabilities

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38f8810b-ac90-1258-a025-0fb37dc7f48d
* Version Independent ID: 807f4d11-6331-17db-ee65-a9f9ccca65da
* Content: [Concepts - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/concepts-overview)
* Content Source: [msteams-platform/concepts/concepts-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/concepts-overview.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by billbliss** [comment]
@NormSohl any ideas?

**Comment by NormSohl** [comment]
The reader would usually follow the links in the first column for that information. This is just a navigational topic. We could add more conceptual material here, but the risk is that it would become cumbersome and difficult to manage.  The links don't work in the github version of the docs, however they work just fine in the published version.
