### ISSUE TITLE
HeroCard's link and button bug in in-call chat 

### ISSUE THREAD

**Issue by ftamin** [MicrosoftDocs/msteams-docs#2581]
Hello,
We are currently developing an MSTeams app, using message extension to send a web link to user's conference room.

After selecting the conference room, the link will be sent to the conversation implemented using HeroCard.

We have discovered that there is a bug, for using link (direct url) and button (OpenUrl) for HeroCard when triggered within the meeting/in-call chat while using the MSTeams desktop app.

The problem does not appear in regular chat, and also it won't appear for in-call chat opened in browser (instead of the desktop app).

The bug will display an error message in the HeroCard, saying: "Something went wrong. Please try again." in red.
And the link/button clicked will open 2 new tabs instead of one, despite we only click once.

You can see the error on the attached video.
https://user-images.githubusercontent.com/20737910/103990740-48197580-51c4-11eb-9b1e-93c8c06e0752.mp4
![20210108_141707](https://user-images.githubusercontent.com/20737910/103990791-5a93af00-51c4-11eb-9a1a-66f1588ebf18.png)

The code that displayed the HeroCard is straight forward (for this example I changed link to Wikipedia):

`protected override async Task<MessagingExtensionActionResponse> OnTeamsMessagingExtensionSubmitActionAsync(ITurnContext<IInvokeActivity> turnContext, MessagingExtensionAction action, CancellationToken cancellationToken)
	{
		var meetingLink = "https://www.wikipedia.org";
		CardAction button = new CardAction(ActionTypes.OpenUrl, "Join Meeting", value: meetingLink);

		var card = new HeroCard
		{
			Title = "Please join this LoopUp meeting",
			Text = $"My Meeting Room<br><a href=\"{meetingLink}\">www.wikipedia.org</a>",
		};

		if (button != null)
		{
			card.Buttons = new List<CardAction>
			{
				button
			};
		}

		var attachments = new List<MessagingExtensionAttachment>();
		attachments.Add(new MessagingExtensionAttachment
		{
			Content = card,
			ContentType = HeroCard.ContentType,
			Preview = card.ToAttachment(),
		});

		return new MessagingExtensionActionResponse
		{
			ComposeExtension = new MessagingExtensionResult
			{
				AttachmentLayout = "list",
				Type = "result",
				Attachments = attachments,
			},
		};
	}`
	
I have looked around but seems nobody reported this error before, or is it perhaps there is problem with my implementation of HeroCard above?

Please advise. 

Thanks.

Note: I also found out that this problem exists on another application that looks like also using HeroCard, on the MSTeams desktop app and in in-call chat: the app name is Zoom, as you see on the attached screenshot.
![20210108_150517](https://user-images.githubusercontent.com/20737910/103990906-8747c680-51c4-11eb-81d7-086fe7be4d60.png)

**Comment by RamaMohanaChary** [comment]
Hi @ftamin,

Can we discuss this over a call? could you please write to us at microsoftteamsdev@microsoft.com.

**Comment by ftamin** [comment]
@RamaMohanaChary , sorry I must have missed the update notification. I have sent the email.

**Comment by ftamin** [comment]
Tested again today, apparently already fixed. Many thanks guys..
