### ISSUE TITLE
Cannot use the Teams Toolkit with my Microsoft Account

### ISSUE THREAD

**Issue by Richard-Stroker** [MicrosoftDocs/msteams-docs#2585]
When trying step 2 of [Part 1](https://docs.microsoft.com/en-us/microsoftteams/platform/build-your-first-app/build-bot#1-create-your-app-project), I get the following error message.

"Selected user account does not exist in tenant 'Microsoft Services' and cannot access the application 'aebc6443-996d-45c2-90f0-388ff96faa56' in that tenant. The account needs to be added as an external user in the tenant first. Please use a different account."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d083976-00c7-86bb-bdca-f909722eae6a
* Version Independent ID: 17fe4c29-7ac0-9091-c7ca-8286e80c0df9
* Content: [Get started - Build a bot - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/build-your-first-app/build-bot)
* Content Source: [msteams-platform/build-your-first-app/build-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/build-your-first-app/build-bot.md)
* Product: **msteams**
* GitHub Login: @heath-hamilton
* Microsoft Alias: **lajanuar**

**Comment by Nikitha-MSFT** [comment]
We are looking into the issue.

**Comment by asnow003** [comment]
@Richard-Stroker what login are you trying to use?  Is this a live/hotmail/gmail account?  Or is this an account you have created that is associated with your developer or work organization/tenant?
