### ISSUE TITLE
Document allow list for mobile tabs

### ISSUE THREAD

**Issue by aosolis** [MicrosoftDocs/msteams-docs#2587]
Tabs are enabled on mobile only after the application is added to an allow list, based on the input of the approval team. While this is in place, we need to document this, and the process

Surbhi, please contact the mobile platform team for details.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e5840ee-09e8-93a6-51d8-508eef388b0a
* Version Independent ID: 621a526e-59dd-e81a-ee89-6a714bc055c8
* Content: [Tabs on mobile - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/design/tabs-mobile)
* Content Source: [msteams-platform/tabs/design/tabs-mobile.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tabs/design/tabs-mobile.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Jagadeesh-MSFT** [comment]
Thank you for the insights on the document. We have raised a [bug](https://domoreexp.visualstudio.com/MSTeams/_workitems/edit/1450842) to the documentation team and the necessary changes are done.
