### ISSUE TITLE
Audio devices don't actually change on linux

### ISSUE THREAD

**Issue by SollyBunny** [MicrosoftDocs/msteams-docs#2591]
I'm on arch linux 64 bit, using teams git up to date. When changing the input/output devices (in teams settings/devices), they don't actually change. I was able to resolve the problem by manually changing the devices to the correct ones in pauvucontrol, however it did cause a lot of problems since I have never messed around with my audio devices since installing.

**Comment by RamaMohanaChary** [comment]
Could you please reach out to [Product Support channels](https://docs.microsoft.com/en-us/microsoftteams/platform/feedback#product-support-channels).
