### ISSUE TITLE
Page should include info about the clientInfo entity in bot messages

### ISSUE THREAD

**Issue by aosolis** [MicrosoftDocs/msteams-docs#2592]
The clientInfo entity has properties for the language and platform. We should document it here (or link to the doc from this page on bot context.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19328d23-2791-8cd0-08f3-d3fef9edaece
* Version Independent ID: 0846b472-1bc8-9bd9-39a6-1cd66ad8743d
* Content: [Get context for your bot - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bots-context)
* Content Source: [msteams-platform/resources/bot-v3/bots-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/resources/bot-v3/bots-context.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Wajeed-msft** [comment]
This is taken up by documentation team.
