### ISSUE TITLE
Sending cards example

### ISSUE THREAD

**Issue by clearab** [MicrosoftDocs/msteams-docs#2594]
This page should probably have an example of sending a simple adaptive card, and then a link to the cards documentation. It should also include documentation around message splitting - if you send an activity that contains both text and an attachment the response from Teams is different, and the message is split (causing the developer to be unable to reference that specific message in the future).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f83b32eb-4265-39bd-e52f-78daf388d1ad
* Version Independent ID: eacbd346-f794-3d91-2eef-227b1a126c31
* Content: [Conversation basics - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-basics?tabs=dotnet)
* Content Source: [msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/bots/how-to/conversations/conversation-basics.md)
* Product: **msteams**
* GitHub Login: @clearab
* Microsoft Alias: **anclear**

**Comment by Wajeed-msft** [comment]
Re-opening this issue. 
It should also include documentation around message splitting - **if you send an activity that contains both text and an attachment the response from Teams is different, and the message is split (causing the developer to be unable to reference that specific message in the future).**

**Comment by KirtiPereira** [comment]
Closed through PR https://github.com/MicrosoftDocs/msteams-docs/pull/2845
