### ISSUE TITLE
Content needs to be updated

### ISSUE THREAD

**Issue by mkchow5928** [MicrosoftDocs/msteams-docs#2605]
The content on how to add PVA bot into Teams needs to be updated as the integration now has a much easier experience for customer to deploy their bot in Teams.  For reference, PVA doc has detail on how to make bot available in Teams for end users:
https://docs.microsoft.com/en-us/power-virtual-agents/teams/publication-add-bot-to-microsoft-teams-teams

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2bf61157-d6d3-f88d-376f-b7a6ecc6199d
* Version Independent ID: dddc2210-7f53-fbfb-7905-a52d9acd0e23
* Content: [Add Power Virtual Agents chatbot to Teams - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/add-power-virtual-agents-bot-to-teams)
* Content Source: [msteams-platform/bots/how-to/add-power-virtual-agents-bot-to-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/bots/how-to/add-power-virtual-agents-bot-to-teams.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Jagadeesh-MSFT** [comment]
@mkchow5928 could you please let me know what content need to be updated ?
