### ISSUE TITLE
Deeplink to Pop out app?

### ISSUE THREAD

**Issue by edwardmcleodjones** [MicrosoftDocs/msteams-docs#2607]
Is there a way to have a deeplink send updated context to a "Pop out app" (e.g. https://www.onmsft.com/news/microsoft-teams-now-lets-users-pop-out-apps-into-separate-windows)?

Use case - I have a tab app that I want users to be able to pop out, and then when they click on various deeplinks - have the popped out app either refresh or get new context (e.g. `microsoftTeams.getContext`).

Currently the behaviour is that the deeplinks just open the app in the Teams window, so the users end up with two versions of the app - one within Teams and one popped out.

**Comment by RamaMohanaChary** [comment]
Hi edwardmcleodjones,

This item remains on the backlog in Teams UserVoice,
Microsoft will always focus on customer’s feedback and experience, some new features would be added to the services based on customers' feedback in the future, we also recommend you give your new idea in Teams UserVoice here:
https://microsoftteams.uservoice.com/

We already had a feature request for this, please have a look on this [request](https://domoreexp.visualstudio.com/MSTeams/_workitems/edit/1141196).

**Comment by edwardmcleodjones** [comment]
Thanks @RamaMohanaChary, but I don't seem to have access to that feature request.  Is it a public site?  It asks for my MS login, and then redirects to a "401 - Uh-oh, you do not have access." page - https://spsprodwus22.vssps.visualstudio.com/_signedin

**Comment by RamaMohanaChary** [comment]
Hi edwardmcleodjones, it's a public forum, could you please [login ](https://microsoftteams.uservoice.com/) and try again.
Please have a look on below screen shot,
![image](https://user-images.githubusercontent.com/71380905/107374332-7bc22500-6b0d-11eb-93c7-b17c8ade3919.png)

**Comment by edwardmcleodjones** [comment]
Yes, I can log in to the Teams UserVoice site fine, it was the other link that wasn't working, but looked like you'd added that in error.

I'll raise it in UserVoice then, thanks.

**Comment by edwardmcleodjones** [comment]
Ah, I see some kind soul already made a feature request in UserVoice based on this issue.

Adding the link for future reference: https://microsoftteams.uservoice.com/forums/555103-public/suggestions/42655459-is-there-a-way-to-have-a-deeplink-send-updated-con

**Comment by Wajeed-msft** [comment]
Please use user voice forum to track this feature request. Closing this from documentation issues page. Please feel free to re-open if you face any issues.
