### ISSUE TITLE
Is it possible to show a page before showing the configuration page when configuring the connector?

### ISSUE THREAD

**Issue by piyumi25** [MicrosoftDocs/msteams-docs#2610]
I need to know that, is there a way to show a page before showing the configure page. Can we hide the buttons (Save button) which are shown in configuration page? I have seen when configuring JIRA connector, first they are showing a popup without save button.

Can someone help me to understand this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28316a67-22fa-8a05-1ae0-fbe1c5720ef9
* Version Independent ID: 8a250e46-2a30-af86-839d-9f83a8b48041
* Content: [Sending messages to Connectors and Webhooks - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-using)
* Content Source: [msteams-platform/webhooks-and-connectors/how-to/connectors-using.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/webhooks-and-connectors/how-to/connectors-using.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Jagadeesh-MSFT** [comment]
Hi @piyumi25,
Yes we can, First set content URL in manifest as normal page URL. Once your normal page gets rendered have a button there to navigate to configuration page.

**Comment by piyumi25** [comment]
@Jagadeesh-MSFT I tried that, but the page is also loading inside configuration window. I need to is there a way to show a page which do not have "save" and "cancel" button?

**Comment by Jagadeesh-MSFT** [comment]
No, then its not possible. Since you need to just configure it and then add it to teams.

**Comment by piyumi25** [comment]
Thank you very much for your response
