### ISSUE TITLE
Activating NDI in Teams not working (Failed Error: FILE_SIGNATURE_MISMATCH)

### ISSUE THREAD

**Issue by jonasuclarity** [MicrosoftDocs/msteams-docs#2611]
I can't activate NDI in Teams, all my colleagues can activate NDI, but for me it does not work. I have tested in different versions of Teams and on different computers. Get the same error every time and everywhere.

"There was a problem downloading the file. Try turning NDI on again."

The log file says:
error - NdiBundleInstaller :: executeStep - Failed Error: FILE_SIGNATURE_MISMATCH

Any tips on what I can do?

**Comment by Mallipriya-MSFT** [comment]
Hi @jonasuclarity, You could maybe try a new policy and assign to your account but outside of that that’s only other thing I could think it could be.

**Comment by jonasuclarity** [comment]
I have now tested with a new policy, and unfortunately it does not help.

**Comment by Mallipriya-MSFT** [comment]
Could you please reach out to the [Product support channels](https://docs.microsoft.com/en-us/microsoftteams/platform/feedback#product-support-channels) for Microsoft Teams.
