### ISSUE TITLE
The developer preview setting does not appear for my admin user even though custom apps are enabled. 

### ISSUE THREAD

**Issue by nastassiar** [MicrosoftDocs/msteams-docs#2612]
I'm using the Edge web app but when I go to the About profile section I only see Legal, Privacy and Cookies and Third party notice there is no developer preview. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 008da4e2-979e-c396-db28-4acf57deb530
* Version Independent ID: f1413f77-5eb3-e1fd-9235-d322d6e4eb6c
* Content: [Developer Preview - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/dev-preview/developer-preview-intro)
* Content Source: [msteams-platform/resources/dev-preview/developer-preview-intro.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/resources/dev-preview/developer-preview-intro.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Mallipriya-MSFT** [comment]
@nastassiar, Thank you for bring this issue to out attention. Checking internally on this and will inform ASAP.

**Comment by nastassiar** [comment]
Hi I already had custom apps turned on. Last time I tried disabling and re-enabling and signing in and out and none of that worked. I've now logged in again after having custom apps enabled for over a week and the options are still not available.

**Comment by Mallipriya-MSFT** [comment]
@nastassiar, I got it working from my end in a day after enabling the upload custom apps from admin center. Could you please share some screenshots of the procedure followed by you.

**Comment by nastassiar** [comment]
![adminportalscreenshot](https://user-images.githubusercontent.com/2245717/105765215-f172a200-5f0c-11eb-8060-8c3359d7c8aa.JPG)
<img width="496" alt="aboutscreenshot" src="https://user-images.githubusercontent.com/2245717/105765216-f20b3880-5f0c-11eb-9584-760beca9627d.png">

last time I went to the Teams admin portal and enabled custom apps. Then I signed into Teams and I still don't see the option.

**Comment by Mallipriya-MSFT** [comment]
@nastassiar, Can we discuss this over a call? Could you please write to us at microsoftteamsdev@microsoft.com.

**Comment by Mallipriya-MSFT** [comment]
Hi @nastassiar, are you still facing the issue?

**Comment by SubbaReddi** [comment]
This issue is still exists

**Comment by Wajeed-msft** [comment]
closing this issue after confirming with SubbaReddi. 
@nastassiar - please let us know if you are still facing this issue.
