### ISSUE TITLE
The API doesn't work

### ISSUE THREAD

**Issue by azakharov2020** [MicrosoftDocs/msteams-docs#2616]
Microsoft graph fails on both Postman and Graph explorer

Description: I am attempting to create a Team according to this guide but it is failing https://docs.microsoft.com/en-us/microsoftteams/platform/graph-api/import-messages/import-external-messages-to-teams

POST https://graph.microsoft.com/beta/teams Content-Type: application/json { "@microsoft.graph.teamCreationMode": "migration", "template@odata.bind": "https://graph.microsoft.com/beta/teamsTemplates('standard')", "displayName": "My Sample Team", "description": "My Sample Team’s Description", "createdDateTime": "2020-03-14T11:22:17.043Z" }

{ "error": { "code": "BadRequest", "message": "Required functionality is not supported.", "innerError": { "date": "2020-11-12T01:01:19", "request-id": "942c9e90-bbb2-4a18-b9b9-0f1e45170942", "client-request-id": "942c9e90-bbb2-4a18-b9b9-0f1e45170942" } } }

There are also problems with both channels and messages
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5687f17-f3c7-39be-5487-f24f2155191a
* Version Independent ID: ce77e760-90cf-e6b1-3cec-ae55ee50c33e
* Content: [Use Microsoft Graph to import external platform messages to Teams - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/graph-api/import-messages/import-external-messages-to-teams)
* Content Source: [msteams-platform/graph-api/import-messages/import-external-messages-to-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/graph-api/import-messages/import-external-messages-to-teams.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Nikitha-MSFT** [comment]
@azakharov2020 - Are you still facing the issue? Could you please try using application permissions, If the issue still persists -  please share the request id
