### ISSUE TITLE
Document what bot should do when the token exchange fails to trigger a consent prompt

### ISSUE THREAD

**Issue by aosolis** [MicrosoftDocs/msteams-docs#2625]
This page doesn't describe that, and it's not clear what bots should do in this case.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9549caa9-99a2-2568-19a5-f21a79292e2f
* Version Independent ID: f2100d03-b88a-34b2-44a2-935231e89db0
* Content: [Single sign-on support for bots - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/authentication/auth-aad-sso-bots#request-a-bot-token)
* Content Source: [msteams-platform/bots/how-to/authentication/auth-aad-sso-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/bots/how-to/authentication/auth-aad-sso-bots.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Wajeed-msft** [comment]
This will be fixed as part of PR https://github.com/MicrosoftDocs/msteams-docs/pull/2786

**Comment by Nikitha-MSFT** [comment]
Thanks for reaching out us. Tech team will follow up here.
