### ISSUE TITLE
Message Extensions - New meeting experience 

### ISSUE THREAD

**Issue by dblig** [MicrosoftDocs/msteams-docs#2626]
New Meeting Experience under settings in Microsoft Teams enabled. when using chatbox and click on the ellipses, the messaging extensions button is not enabled. I see it, but not able to click on it.

Turn off 'New meeting experience" and the messaging extensions work normally.

Huge impact for Teaching and Learning on our EDU tenant.

**Comment by RamaMohanaChary** [comment]
Hi @dblig:

Could you please have a look on this [document](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/messaging-extension-v3/create-extensions?tabs=typescript#initiate-actions-from-messages) to know how messaging extensions will enable.

**Comment by dblig** [comment]
> Hi @dblig:
> 
> Could you please have a look on this [document](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/messaging-extension-v3/create-extensions?tabs=typescript#initiate-actions-from-messages) to know how messaging extensions will enable.

Thanks for your reply. Forgive my ignorance but how does this help our end users that are trying to delivery online lessons via teams. They try to use message extensions to use forms bot however it is greyed out. Turning off the new meeting experience enables the message extensions again. The Teams app appears to have a bug with the new meeting experience.

Other Microsoft 365 tenants do not have this issue........

**Comment by RamaMohanaChary** [comment]
Hi @dblig:

Sorry for delayed response!

We can able to see message extensions, please have a look on below screenshot.
![image](https://user-images.githubusercontent.com/71380905/107611823-de7d0300-6c6a-11eb-91db-76a2a9abe300.png)
![image](https://user-images.githubusercontent.com/71380905/107612015-47fd1180-6c6b-11eb-8cc1-59410a28c8e9.png)

Could you please share us the screen shot with repro steps?

**Comment by dblig** [comment]
Please attached screenshot just taken. The only way to enable the extensions is to turn off the new meeting experience. A backward step.

**Comment by dblig** [comment]
Please attached screenshot just taken. The only way to enable the extensions is to turn off the new meeting experience. A backward step.
![Screenshot 2021-02-11 at 09 01 37](https://user-images.githubusercontent.com/77554330/107637069-7e379280-6c65-11eb-95b6-adc602974136.png)

**Comment by RamaMohanaChary** [comment]
Hi dblig,

Could you please have a look and follow the [document](https://docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/teams-apps-in-meetings#messaging-extensions).

**Comment by Nikitha-MSFT** [comment]
@dblig - Are you still facing the issue? if yes please reopen the issue. Closing the issue for now.
