### ISSUE TITLE
Complete channel API not work

### ISSUE THREAD

**Issue by TonyLi2013** [MicrosoftDocs/msteams-docs#2628]
Hi team,

We found the complete channel API not work suddenly, we can call this API many times without any issue which is abnormal. Generally it failed with error message "Channel has already been finalized." when we tried to complete one channel twice before.
![image](https://user-images.githubusercontent.com/3928402/104863505-185f3000-5971-11eb-8f75-1a1cd8d5a873.png)
After completing channel, we try to complete the teams, but failed.
![image](https://user-images.githubusercontent.com/3928402/104863553-493f6500-5971-11eb-9281-4541b72d9d78.png)
I guess the complete channel API not work any more, so complete teams API failed with General channel not complete before. Please help check this issue, it break the migration function.

Thanks in advance,
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5687f17-f3c7-39be-5487-f24f2155191a
* Version Independent ID: ce77e760-90cf-e6b1-3cec-ae55ee50c33e
* Content: [Use Microsoft Graph to import external platform messages to Teams - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/graph-api/import-messages/import-external-messages-to-teams)
* Content Source: [msteams-platform/graph-api/import-messages/import-external-messages-to-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/graph-api/import-messages/import-external-messages-to-teams.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Mallipriya-MSFT** [comment]
Hi @TonyLi2013 , Thank you for providing the insights. Will repro from my end, check internally and get back to you ASAP.

**Comment by Mallipriya-MSFT** [comment]
@TonyLi2013, I am able to reproduce the issue from my side and raised a bug. Will keep you posted once it gets resolved.

**Comment by edwardmcleodjones** [comment]
@Trinetra-MSFT Can the `needs-author-feedback` label be removed and the issue be unmarked as stale please, as @Mallipriya-MSFT has acknowledged it as a bug and can reproduce it, so no further author feedback needs to be supplied.

I'm also facing the same issue, so would like to see when it gets resolved.  This is making migration unusable at present.

```
Error completing team migration: 
Code: BadRequest
Message: General channel must be finalized before team.
Inner error:
        AdditionalData:
        date: 2021-01-24T15:20:10
        request-id: 9b369529-8ef0-4093-aef6-c060d4f0adf6
        client-request-id: 9b369529-8ef0-4093-aef6-c060d4f0adf6
ClientRequestId: 9b369529-8ef0-4093-aef6-c060d4f0adf6
```

**Comment by Mallipriya-MSFT** [comment]
@edwardmcleodjones, The bug is still in active state and we don't have any ETA. Will keep you posted once it gets resolved.

**Comment by TonyLi2013** [comment]
@Mallipriya-MSFT  I just tested this again, looks like the bug has already been fixed, the channel and team can be completed normally, thanks for your help.

**Comment by edwardmcleodjones** [comment]
I just tried again, and am still getting the `General channel must be finalized before team.` error.  

Wonder if it's related to Resource Group location?  Maybe my one hasn't been updated yet with the fix yet.  Will try again tomorrow.

**Comment by TonyLi2013** [comment]
@edwardmcleodjones Yes, I think so. MS update M365 datacenter one by one, should work after a while.

**Comment by Wajeed-msft** [comment]
Please feel free to drop a comment if you are still facing this issue.
