### ISSUE TITLE
Where should I store my login details when I develop a teams search extension in .netcore.

### ISSUE THREAD

**Issue by shash91** [MicrosoftDocs/msteams-docs#2629]
Hi,
I am creating a team's search extension using dotnet core. Can I know what is the best way to store my login details without using a database or any other storage.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4f3b627-c87b-6a19-9c26-7170a99f38ee
* Version Independent ID: a9546115-7c5d-39c9-ca8a-3cf3e02ff621
* Content: [Respond to search command - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/search-commands/respond-to-search?tabs=dotnet)
* Content Source: [msteams-platform/messaging-extensions/how-to/search-commands/respond-to-search.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/messaging-extensions/how-to/search-commands/respond-to-search.md)
* Product: **msteams**
* GitHub Login: @clearab
* Microsoft Alias: **anclear**

**Comment by Nikitha-MSFT** [comment]
You can store the data when the user clicks on the submit button. You will receive the data in the turncontext.activity.value. You can create a JSON in the solution and store the login details when user submit the login Details.

**Comment by shash91** [comment]
@Nikitha-MSFT  I need to handle login for my application for multiple users so if I use a JSON in the solution I don't think it will handle details for each user. is there anything that I can use like local storage or sessions?

**Comment by Nikitha-MSFT** [comment]
When you submit the data , You will Receive the Message extension submit event, You can handle the code to save your data  as per the requirement.
