### ISSUE TITLE
`justInTimeInstall` is not working correctly on Android platform

### ISSUE THREAD

**Issue by kafka-yu** [MicrosoftDocs/msteams-docs#2634]
As the per the Doc shows: https://docs.microsoft.com/en-us/microsoftteams/platform/resources/messaging-extension-v3/create-extensions?tabs=typescript#request-to-install-your-conversational-bot
We are using this flag to install our conversational bot to conversations during the msg extensions open up first time.

Currently, it works fine on desktop, iPhone. But it failed on the Andoird platform when opening it first time in a chat.

Pls help check, if it is a bug on Android?

**Comment by Manish-MSFT** [comment]
We are looking into this issue, and will update you soon.

**Comment by Manish-MSFT** [comment]
Hi @kafka-yu : Can we get on call to discuss this. Please write to us at microsoftteamsdev@microsoft.com
