### ISSUE TITLE
Link new generic sample for Connector configuration

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#2637]
Link new generic sample for Connector configuration in [Connectors section](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/connector-generic/nodejs).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ebc0dbbb-a5af-6028-cb66-65cc711eb9f0
* Version Independent ID: 891b08f2-827b-c5e2-8070-4489650acff9
* Content: [Microsoft Teams code samples - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tutorials/code-samples#connectors)
* Content Source: [msteams-platform/tutorials/code-samples.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tutorials/code-samples.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by KirtiPereira** [comment]
@Wajeed-msft - Clarification required, as we have moved out the Code sample section as a link in the TOC (as per PR#2654) changes. Need to confirm where this link needs to be added.
![image](https://user-images.githubusercontent.com/70375155/107737954-b30e1d00-6d2b-11eb-97a8-b63abba9273e.png)

**Comment by Wajeed-msft** [comment]
@KirtiPereira - 
1. Please link link first two samples from [this section](https://github.com/OfficeDev/Microsoft-Teams-Samples#webhooks-and-connectors-samples) to bottom of [Creating Office 365 Connectors for Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-creating) doc under code samples sections. 
2. Please link link last sample from [this section](https://github.com/OfficeDev/Microsoft-Teams-Samples#webhooks-and-connectors-samples) to bottom of [Create outgoing webhook](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-outgoing-webhook) doc under code samples sections.
