### ISSUE TITLE
Adding a second tab/domain with Microsoft login?

### ISSUE THREAD

**Issue by maxpaj** [MicrosoftDocs/msteams-docs#2641]
### Background

I have followed the tutorial on how to set up SSO for a Teams application tab and that works perfectly. 

Recently, I've tried adding more tabs to my Teams app, which also require login with Microsoft. **This is not working.**

### Issue

My first tab is a React application hosted on domain A. I have used the same domain for my Azure AD Application, and in the apps manifest.json `webapplicationInfo`. This is working perfectly. 

The second tab I'm adding is an existing application that my organization has used for years/months. It is hosted on domain B. It uses OAuth popup method for authenticating users. That does not work when it is loaded through the Teams app. 

We tried adding `@microsoft/teams-js` to that application for authenticating. This does not work either, this is the error message we are getting in the JavaScript console:  `getAuthTokenForApp: Failed with error - App resource defined in manifest and iframe origin do not match`

I can't find any reference to this error message in the documentation.

We tried adding a third tab for an application which uses OAuth redirect method. This does not work either. The error message is: `Refused to display ‘login.microsoftonline…’ in a frame because it set ‘X-Frame-Options’ to ‘deny'`

From Google I found these:
- https://docs.microsoft.com/en-us/answers/questions/82942/teams-single-sign-on.html
- https://github.com/MicrosoftDocs/msteams-docs/issues/1244
- https://stackoverflow.com/questions/59837948/authcontext-login-causes-refused-to-display-login-microsoftonline-com-in

### Solutions?
What is the solution? Where do I start looking? I assume there is something wrong with my manifest file, but I guess it could be something that needs to be done in Azure AD and perhaps even the app that is contained in the second tab.

Is this the information I'm looking for? 
- https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-tab-aad

To boil all this down: **How can I have two tabs, on different URLs, that both work with Microsoft login in my Teams app?**

**Comment by Mallipriya-MSFT** [comment]
Hi @maxpaj, Could you please have a look at this [document](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-aad-sso#2-update-your-microsoft-teams-application-manifest) and verify that AppId provided in Resource element of webApplicationInfo property of manifest matches with Application Uri of the App in Azure.

**Comment by maxpaj** [comment]
@Mallipriya-MSFT 

They match and **SSO is working on the first tab** in my Teams app. 

The issue appears when I'm trying to add a second tab, which points to another domain.

**Comment by Mallipriya-MSFT** [comment]
@maxpaj , Could you please confirm if the domain of the second tab is added in valid domains of manifest.

**Comment by maxpaj** [comment]
@Mallipriya-MSFT I can confirm that it is.

**Comment by maxpaj** [comment]
Updated the text to better reflect the issue and what I'm missing in the documentation.

**Comment by maxpaj** [comment]
I found the solution here:

- https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-tab-aad
- https://github.com/OfficeDev/microsoft-teams-sample-auth-node

**Comment by mihristov** [comment]
@maxpaj Could you please explain what the solution was. I'm having the same issue and nothing seems to resolve it. My application URI matches with my tab's domain.

**Comment by maxpaj** [comment]
@mihristov

In my second tab application, I had to add another authentication method by using `@microsoft/teams-js`. 

While your application may already be using OAuth popup method, you have to give the "control" of opening and closing the popup to Teams, by using `microsoftTeams.authentication.authenticate`. 

Somehow you need to identify if your application is currently in a Teams `<iframe>`, then use Teams authentication if that is the case. 

Here is part of my implementation:

```
import * as microsoftTeams from "@microsoft/teams-js";

let inTeams = false;

export function initTeams() {
  return new Promise((resolve) => {
    microsoftTeams.initialize((args) => {
      inTeams = true;
      resolve(args);
    });
  });
}

export function getTeamsContext() {
  return new Promise((resolve) => {
    microsoftTeams.getContext((ctx) => {
      resolve(ctx);
    });
  });
}

export function isInTeams() {
  return inTeams || window.name === "extension-tab-frame";
}

export function successLoginTeams(data) {
  microsoftTeams.authentication.notifySuccess(data);
}

export function failedLoginTeams(reason) {
  microsoftTeams.authentication.notifyFailure(reason);
}

export function loginTeamsPopup() {
  return new Promise((resolve, reject) => {
    try {
      microsoftTeams.authentication.authenticate({
        url: `${window.location.origin}/teams-login-popup`,
        height: 500,
        width: 600,
        successCallback: (success) => {
          resolve(success);
        },
        failureCallback: (reason) => {
          reject(reason);
        },
      });
    } catch (e) {
      reject(e);
    }
  });
}
```

When Teams open the page at `/teams-login-popup`, that page should redirect immediately to Microsoft Login page.
