### ISSUE TITLE
Generalize content from Tab app to webapp

### ISSUE THREAD

**Issue by shuchauh** [MicrosoftDocs/msteams-docs#2642]
The documentation page currently only talks about device permissions in context of Tab app. The same permissions equally valid for other Teams surfaces like task module and apps that load in personal scope (Personal apps). Hence, the content needs to be generalized to state the same.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19804dba-009f-2eb1-cc7f-1e0fabbebb6b
* Version Independent ID: a9373e78-b3c9-7182-d253-5ac8d8988936
* Content: [Request device permissions for your Microsoft Teams tab - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?tabs=desktop)
* Content Source: [msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/device-capabilities/native-device-permissions.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by RamaMohanaChary** [comment]
In this document, currently only talks about device permissions in context of Tab app.
But, we have same permissions equally valid for other Teams surfaces like task module and apps that load in personal scope (Personal apps). 
So, we need to update the content which needs to be generalized to state the same.
