### ISSUE TITLE
The Display Pic is mostly different while typing in a group chat

### ISSUE THREAD

**Issue by viveksingh98** [MicrosoftDocs/msteams-docs#2649]
In a group chat when someone is typing, the name shown is always correct but the display pic before "X is typing ..." shows picture of a different group member

**Comment by Trinetra-MSFT** [comment]
@viveksingh98 , Please try to update your Teams to latest version and let me know if you still face this issue.

**Comment by v-chetsh** [comment]
@viveksingh98 - Could you please confirm if your issue has resolved or still looking for any help?

**Comment by viveksingh98** [comment]
I have not noticed this issue recently. I'll confirm on this in couple of days time though
