### ISSUE TITLE
Icon images do not respect dark mode setting

### ISSUE THREAD

**Issue by tylerjdurden** [MicrosoftDocs/msteams-docs#2658]
On this particular page, you can see the issue on the following line:

> In Visual Studio Code, select Microsoft Teams on the left Activity Bar and choose Create a new Teams app.
When prompted, sign in with your Microsoft 365 development account.

The icon after "Microsoft Teams" is difficult to see (a11y issue!). The icon itself is from Visual Studio Code, so perhaps the site could use the dark mode icons from there.

![image](https://user-images.githubusercontent.com/11760369/105404357-ddbaf900-5bf7-11eb-8424-f004a3083201.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f876156-cc1e-468f-4647-5143a5de03b1
* Version Independent ID: 618f43a3-3371-ad99-13aa-087b9303298c
* Content: [Get started - Build and run your first app - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/build-your-first-app/build-and-run)
* Content Source: [msteams-platform/build-your-first-app/build-and-run.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/build-your-first-app/build-and-run.md)
* Product: **msteams**
* GitHub Login: @heath-hamilton
* Microsoft Alias: **lajanuar**

**Comment by Mallipriya-MSFT** [comment]
I can reproduce the issue, once the browser theme is set to dark mode, the icon beside the "Microsoft Teams" is not visible.
