### ISSUE TITLE
Unable to test my own app

### ISSUE THREAD

**Issue by FrostDracony** [MicrosoftDocs/msteams-docs#2667]
Hi, it‘s my first issue report on github at all! So sorry if I make it wrong. Anyways, I just wanted to create a teams app and followed the main tutorial, until the last section, this here:

https://docs.microsoft.com/en-us/microsoftteams/platform/build-your-first-app/build-and-run#4-sideload-your-app-in-teams

I did everything, but I can‘t understand this sentence:
"Go back to Teams. In the dialog, select Add for me to install your app."
What do the tutorial means with "In the dialog"? I can‘t find any dialog. It‘s very confusing, I tried debugging for hours but am unable to understand and find a solution. So: Am just I that can‘t understand or is just the tutorial not clear enough? Because I can‘t find any tutorial so this dosen‘t help really.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29e90229-289e-2035-3b42-5cb9cce14efe
* Version Independent ID: a2aee4b8-93b9-bda7-f000-8f41b4513647
* Content: [Get started - Build a personal tab - Teams](https://docs.microsoft.com/en-gb/microsoftteams/platform/build-your-first-app/build-personal-tab)
* Content Source: [msteams-platform/build-your-first-app/build-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/build-your-first-app/build-personal-tab.md)
* Product: **msteams**
* GitHub Login: @heath-hamilton
* Microsoft Alias: **lajanuar**

**Comment by Nikitha-MSFT** [comment]
You need to configure your app using app studio as documented [here](https://docs.microsoft.com/en-us/microsoftteams/platform/build-your-first-app/build-and-run#app-id). Please check this [docs](https://docs.microsoft.com/en-us/microsoftteams/platform/tutorials/get-started-dotnet-app-studio#use-app-studio-to-update-the-app-package) to install the app? when you install the app using app studio you will receive a dialog when you will see an option to add app, after selecting add app, your app will be added and it displayed inside the teams.

**Comment by FrostDracony** [comment]
And, I forgot to mention: I am using Visual Studio Code to create my app, not app studio. So, this isn‘t the solution that I need.

**Comment by FrostDracony** [comment]
I think, I am going to switch over to use the app studio, but seriously hope that this issue still will be get fixed. So, I leave this open in the case that in the future someone wants to say something about this issue.

**Comment by Nikitha-MSFT** [comment]
When you Complete the first step in mentioned in the document You could see the below screen where it consists of App Studio to install the app in teams.
![image](https://user-images.githubusercontent.com/61688740/105945810-fe69cf80-608b-11eb-837e-1dbda37a2d30.png)
Please try installing the app using App studio in Visual studio code.

**Comment by FrostDracony** [comment]
Wow, I didn‘t know that…
I will give it a try when I can, and I still hope that they update their docs.

**Comment by FrostDracony** [comment]
https://github.com/MicrosoftDocs/msteams-docs/issues/2667#issuecomment-768035060
@Nikitha-MSFT, sorry to ping you (again, I hope it's last time...). I tested this but I have something other. I don't understand what I have to do:
![Code_hXcCYDWeP5](https://user-images.githubusercontent.com/60100684/106394275-0b741f00-63fc-11eb-85b1-04b7b085043b.png)
I lean, I am only a regular student with a office 365 account (I think this is what they meant by organization?). What do I have to do?

**Comment by Nikitha-MSFT** [comment]
The app id you mentiond was not registered in the tenant you are trying. Please check the APP id.

**Comment by FrostDracony** [comment]
I don't understand. I have the app id. Where should I register it. I am checking the teamsAppId in package.json and I can find the app id. What are you meaning?

**Comment by FrostDracony** [comment]
Nevermind, I just deleted the folder and installed it again. This time it works

**Comment by FrostDracony** [comment]
I am really near to the end, really thanks for your help. What do I need to write in Package Name? I think, do I have to leave it how it is or do I need to write something other?

**Comment by Nikitha-MSFT** [comment]
You can provide a unique name for example: com.contoso.helloworld.

**Comment by FrostDracony** [comment]
Ok, so it dosen't have to be the name of my folder location (e.g. if I create my app in the folder com -> myname -> helloworld) but I am free to choice the name that I want. Thanks a lot for helping me!
