### ISSUE TITLE
Selected search item is overlaped by StaticTab

### ISSUE THREAD

**Issue by ihorsnihur** [MicrosoftDocs/msteams-docs#2668]
I have msteams bot app with StaticTab. When i use any serach extension messages i get unexpected overllapping.

Steps to reproduce: 
1. Click on static tab
2. Use search extension message, YouTube for example
3. Select any item from found items

Expected result: card with selected item is not overlapped by StaticTab
Actual: Static tab overlap selected search item

1) Search list overlap StaticTab - expected
![image](https://user-images.githubusercontent.com/1659173/105514899-b38f3700-5cdc-11eb-9327-7b18d891c500.png)

2) Selected item is overlapped by StaticTab
![image](https://user-images.githubusercontent.com/1659173/105515105-f7823c00-5cdc-11eb-90d2-719bf30c1f85.png)

Additional information:
1) Search list Z-Index - 10001
2) Selected item Z-Index - 1001
3) StaticTab Z-Index - 2000

Maybe z-index is the reason of problem. StaticTab z-index > Selected item z-index.

**Comment by Mallipriya-MSFT** [comment]
Hi @ihorsnihur, Thank you for the insights. Will repro and will inform you as soon as possible.

**Comment by Mallipriya-MSFT** [comment]
I am able to reproduce the issue from my side and raised a bug. Will keep you posted once it gets resolved.

**Comment by ihorsnihur** [comment]
Hi @Mallipriya-MSFT, cool, thanks a lot.

**Comment by Mallipriya-MSFT** [comment]
@ihorsnihur, We are working on fixing this bug but we do not have a firm timeline to share with you. Hence, we are closing this question for now.

**Comment by Nikitha-MSFT** [comment]
Bug is Resolved now, we have tested this at our end, could you please also check and confirm?
