### ISSUE TITLE
Deep Link to "Files" Tab in Teams(Desktop)

### ISSUE THREAD

**Issue by luqmansky** [MicrosoftDocs/msteams-docs#2671]
Hi Team, 
I am facing one issue, I am trying to generate the deep link for "Files" tab of teams channel for desktop version but I am not able to succeed. I have looked into this also but this is the [link](https://github.com/MicrosoftDocs/msteams-docs/issues/1174) for file previewer only but not for Files tab itself. 
If I select the Files Tab in Teams and click on Copy Link, it generates URL for web version which is something like this: 

It works for web but not for desktop
https://teams.microsoft.com/_#/files/Products%20for%20Office%20365?groupId=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx&threadId=19%3Axxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx%40thread.skype&ctx=channel&context=Products%2520for%2520abc%2520365&rootfolder=%252Fsites%252FXYZ%252FShared%2520Documents%252FProducts%2520for%2520abc%2520365 

As mentioned in issue 1174 I am also not able to fetch the tab of "Files" in Graph API as well.
https://graph.microsoft.com/v1.0/teams/<team-id>/channels/<channel-id>/tabs

I tried to find out more information about it and found this when I click on Files tab in browser. It sends request to 
https://teams.microsoft.com/api/mt/emea/beta/channels/19:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx@thread.skype/documentlibraries

The tab itself has this track-data: {"meetingUniqueId":"19:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx@thread.skype","tabType":"files","directive":"team-files","definitionId":"xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx","appId":"xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx","newBadgeShown":false,"leftRailDirective":"teams","channelState":"shown"}

What I need is something like this 
https://teams.microsoft.com/l/channel/19:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx@thread.skype/tab%3A%3A<Tab-ID>?groupId=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx&threadId=19:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx@thread.skype&ctx=channel

This navigates to the channel but not to the Files Tab.
![image](https://user-images.githubusercontent.com/77861710/105556602-9f622e80-5d0a-11eb-9e93-8b0605117d6f.png)

**Comment by Manish-MSFT** [comment]
@luqmansky , We are investigating this internally.

**Comment by Manish-MSFT** [comment]
@luqmansky  : Can we discuss this over a call? Please write to us at microsoftteamsdev@microsoft.com

**Comment by luqmansky** [comment]
@Manish-MSFT I have sent you email.

**Comment by Manish-MSFT** [comment]
@luqmansky : we have raised a bug for this issue with id : 1509183, I will keep this thread updated about bug status.

**Comment by RamaMohanaChary** [comment]
This looks like an issue in some old version of the Files tab.
![image](https://user-images.githubusercontent.com/71380905/113819251-b0adc980-9796-11eb-8407-a1824221d10e.png)

The deep links generated by this UI do not follow our standard deep link format and so do not go through the launcher.
