### ISSUE TITLE
'Open Developer Tools' doesn't show up even thoug I'm in developer preview with a developer-subscription-account and everything

### ISSUE THREAD

**Issue by rfinster** [MicrosoftDocs/msteams-docs#2672]
Now my app works in the browser version of teams but doesn't in the os-client version. And I have no idea how to change that due to missing inspection capabilities. What can I do :(

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3df1efbb-c6b2-a495-303d-7abf19c57f72
* Version Independent ID: a5b5782f-7031-a989-5e42-dd3010e18893
* Content: [DevTools for Microsoft Teams tabs - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/developer-tools)
* Content Source: [msteams-platform/tabs/how-to/developer-tools.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tabs/how-to/developer-tools.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by rfinster** [comment]
Nevermind. Figured out: I need to spam-left-click the tray icon several times. After that everything appears on right click. Heck who thought this would be a good idea?

**Comment by Trinetra-MSFT** [comment]
Closing this User resolved his issue by himself
