### ISSUE TITLE
Reading value from the Data object is null

### ISSUE THREAD

**Issue by rvinothrajendran** [MicrosoftDocs/msteams-docs#2673]
**Respond with a card inserted into the compose message area code section**

look like issue in reading value from Data object its return always null value.

Current code

var card = new HeroCard
    {
        Title = Data["formField1"] as string,
        Subtitle = Data["formField2"]  as string,
        Text = Data["formField3"]  as string,
    };

If I used the SelectToken function I can able to get the result from the Data object.
ex :  Data.SelectToken("FormField1")?.ToString()

may be the same issue in the Respond to initial submit action section also create Content  object section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fb0c2d8-f880-c260-d0be-6b9467e47f8c
* Version Independent ID: 7820ffc9-5260-c818-f5fb-672801a67d00
* Content: [Respond to the task module submit action - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/action-commands/respond-to-task-module-submit?tabs=dotnet%2Cdotnet-1)
* Content Source: [msteams-platform/messaging-extensions/how-to/action-commands/respond-to-task-module-submit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/messaging-extensions/how-to/action-commands/respond-to-task-module-submit.md)
* Product: **msteams**
* GitHub Login: @clearab
* Microsoft Alias: **anclear**

**Comment by RamaMohanaChary** [comment]
Hi @rvinothrajendran,

Could you please go through the [sample code](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/51.teams-messaging-extensions-action) which will help you to understand task module action submission.

**Comment by rvinothrajendran** [comment]
@RamaMohanaChary 
Thank you. I understand the code but the code is written in the  “Respond with a card inserted into the compose message area code section”  msteams-docs/respond-to-task-module-submit.md at master · MicrosoftDocs/msteams-docs (github.com)  look like an issue.

**Comment by RamaMohanaChary** [comment]
Hi @rvinothrajendran,

Yes, we have raised a document bug.

**Comment by RamaMohanaChary** [comment]
Hi @rvinothrajendran,

Could you please have a look and try implementing the below code,

var createCardData = ((JObject)action.Data).ToObject<CreateCardData>();
var card = new HeroCard
{
     Title = createCardData.Title,
     Subtitle = createCardData.Subtitle,
     Text = createCardData.Text,
};

**Comment by rvinothrajendran** [comment]
Hi @RamaMohanaChary  ,
The sample code it wont work , We have to change the code like below

dynamic createCardData = ((JObject) action.Data).ToObject(typeof(JObject));
or 
dynamic  createCardData  = JObject.Parse(action.Data.ToString());

var card = new HeroCard
{
Title = createCardData.Title,
Subtitle = createCardData.Subtitle,
Text = createCardData.Text,
};
