### ISSUE TITLE
Add during a meeting

### ISSUE THREAD

**Issue by 125693** [MicrosoftDocs/msteams-docs#2677]
[Enter feedback here]

The "Add an app" option is not showing during the meeting call.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09c05a14-d442-bcd1-f233-1beeddfd4bb1
* Version Independent ID: eb958ded-39dc-c0ab-a7c8-2d5bf334ab16
* Content: [Designing your meeting extension - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/design/designing-apps-in-meetings#use-an-in-meeting-tab)
* Content Source: [msteams-platform/apps-in-teams-meetings/design/designing-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/apps-in-teams-meetings/design/designing-apps-in-meetings.md)
* Product: **msteams**
* GitHub Login: @heath-hamilton
* Microsoft Alias: **lajanuar**

**Comment by Manish-MSFT** [comment]
Hi @125693 , Could you please share a screenshot with us to just verify the bug. This will help us to file a doc bug and resolve it quickly.
