### ISSUE TITLE
'Create a bot without the toolkit' link broken at 'Build a bot for Microsoft Teams' doc

### ISSUE THREAD

**Issue by manutero** [MicrosoftDocs/msteams-docs#2678]
Last link at [Build a bot for Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/build-your-first-app/build-bot) (at [Learn More section](https://docs.microsoft.com/en-us/microsoftteams/platform/build-your-first-app/build-bot#learn-more)) says *Create a bot without the toolkit* but it's redirecting to the very same page. 

![Captura de pantalla 2021-01-26 a las 12 08 19](https://user-images.githubusercontent.com/2211052/105837810-81792000-5fcf-11eb-82d7-431ffffe58fa.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d083976-00c7-86bb-bdca-f909722eae6a
* Version Independent ID: 17fe4c29-7ac0-9091-c7ca-8286e80c0df9
* Content: [Get started - Build a bot - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/build-your-first-app/build-bot)
* Content Source: [msteams-platform/build-your-first-app/build-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/build-your-first-app/build-bot.md)
* Product: **msteams**
* GitHub Login: @heath-hamilton
* Microsoft Alias: **lajanuar**

**Comment by KirtiPereira** [comment]
Issue has been resolved.

**Comment by manutero** [comment]
NO it's not!!

**Comment by RamaMohanaChary** [comment]
Hi @manutero, issue has been resolved, tested from our end. 
1) Click on "Create a bot without the toolkit".
2) It redirects to [https://docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bots-create](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bots-create).

Could you please let us know your findings.

**Comment by manutero** [comment]
ok, im not cracy 🙃 This morning wasn't resolving to that page!

Anyway it does now. 
...
sorry for the noise 

thnks
