### ISSUE TITLE
iOS App Deep link to call team support queue

### ISSUE THREAD

**Issue by p0tvin29** [MicrosoftDocs/msteams-docs#2679]
Trying to create an iOS app that will open URL "msteams://teams.microsoft.com/l/call/0/0?users=Support@Domain.com" and call a support queue setup in teams..

This opens MS Teams on the iPAD device and shows a loading bar under Feed/My Activity but does not actually do anything. If I open this link on my Mac desktop it works fine... 

Does the iOS Teams app not support this type of deep linking?

**Comment by Trinetra-MSFT** [comment]
@p0tvin29 , I just tried this over my iPhone 6s I was able to navigate to new meeting chat, Are you still seeing this issue

**Comment by p0tvin29** [comment]
@Trinetra-MSFT Yes but trying to call someone does not work. Notice the deep link is a call not a meeting join. We need this for our client support app to join a support queue.

**Comment by Jagadeesh-MSFT** [comment]
@p0tvin29, We are unable to repro it from our end it is initiating a call to the user rather than navigating to the meeting join page.

**Comment by p0tvin29** [comment]
@Jagadeesh-MSFT In XCODE, try something like this:
```
var URL = "msteams://teams.microsoft.com/l/call/0/0?users=User@Email.com"
if let url = Foundation.URL(string: URL) {
    UIApplication.shared.open(url)
}
```

If you do not have access to XCODE, just open browser on iPhone and enter this link with a valid email address at the end:
`msteams://teams.microsoft.com/l/call/0/0?users=User@Email.com`

You will notice that it will NOT call the person (email) .  If you try that link from a PC/Mac, it DOES work and call the person.

**Comment by Jagadeesh-MSFT** [comment]
@p0tvin29, We are able to repro your issue from our, Thank you for the insights on the document. We have raised a bug for this.

**Comment by Jagadeesh-MSFT** [comment]
@p0tvin29, currently calling deeplink is not supported on all platforms. Could you please raise an [User Voice](https://microsoftteams.uservoice.com/).
