### ISSUE TITLE
Two different images for same person in active chat session in Teams

### ISSUE THREAD

**Issue by UddhavrajSYN** [MicrosoftDocs/msteams-docs#2683]
![Microsoft Team Bug](https://user-images.githubusercontent.com/78099776/106026320-b2507680-60ef-11eb-9639-a13b53f56697.PNG)

Issue -  Noticed that during active one to one chat session in Teams there are two different photos appeared
Please see attached image.
One image is with right user and another image for some different user under same name.

Please help to rectify

**Comment by Manish-MSFT** [comment]
Thanks for reaching out to us. We are the developer support team for Microsoft teams focused on helping developers resolve their code issues. For issues related to [teams product](https://docs.microsoft.com/en-us/microsoftteams/platform/feedback#product-support-channels), please reach out to the Product support channels for Microsoft Teams.
