### ISSUE TITLE
No example for how to apply newTheme as the CSS to your tab content's root HTML element (<div>).

### ISSUE THREAD

**Issue by pundj** [MicrosoftDocs/msteams-docs#2684]
[Enter feedback here]
Apply the CSS to your tab content's root HTML element (<div>).

How do I do this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29e90229-289e-2035-3b42-5cb9cce14efe
* Version Independent ID: a2aee4b8-93b9-bda7-f000-8f41b4513647
* Content: [Get started - Build a personal tab - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/build-your-first-app/build-personal-tab)
* Content Source: [msteams-platform/build-your-first-app/build-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/build-your-first-app/build-personal-tab.md)
* Product: **msteams**
* GitHub Login: @heath-hamilton
* Microsoft Alias: **lajanuar**

**Comment by Nikitha-MSFT** [comment]
To change the Theme according to the user theme, first you need to check the current theme of the user. You need to add the JavaScript code to your page as documented [here](https://docs.microsoft.com/en-us/microsoftteams/platform/build-your-first-app/build-personal-tab#match-theme-styles). Could you please share in detail what your looking for?

**Comment by pundj** [comment]
After step 3, “Apply the CSS to your tab content’s root HTML element
(<div>).”, it would be nice if you could show specifically how to do that.
I’m not familiar with React syntax and was just trying to follow along with
the tutorial and didn’t know how to apply the style created in newTheme. I
figured it out by googling that you do so like this:

<div style={newTheme}>

**Comment by Mallipriya-MSFT** [comment]
Hi @pundj,  Thank you for the insights on document. Did that work for you by adding the style to <Div> tag. If not, please try by replacing the below code in Tab.js file :

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

```
import React from 'react';
import './App.css';
import * as microsoftTeams from "@microsoft/teams-js";

/**
 * The 'PersonalTab' component renders the main tab content
 * of your app.
 */
class Tab extends React.Component {
  constructor(props){
    super(props)
    this.state = {
      context: {}
    }
  }

  //React lifecycle method that gets called once a component has finished mounting
  //Learn more: https://reactjs.org/docs/react-component.html#componentdidmount
  componentDidMount(){
    microsoftTeams.initialize();
    // Get the user context from Teams and set it in the state
    microsoftTeams.getContext((context, error) => {
      this.setState({
        context: context
      });
    });
    // Next steps: Error handling using the error object
    microsoftTeams.registerOnThemeChangeHandler(theme => {
      if (theme !== this.state.theme) {
        this.setState({ theme });  
      }
      
      
    });
  }

  render() {
    const isTheme = this.state.context.theme;
      let userName = Object.keys(this.state.context).length > 0 ? this.state.context['upn'] : "";
      let newTheme;

if (isTheme === "default") {
  newTheme = {
    backgroundColor: "red",
    color: "red"
  };
} else {
  newTheme = {
    backgroundColor: "green",
    color: "green"
  };
}
      return (
        
        <div style = {newTheme}>
        <h1>Important Contacts</h1>
          <ul>
            <li >Help Desk: <a href="mailto:support@company.com">support@company.com</a></li>
            <li>Human Resources: <a href="mailto:hr@company.com">hr@company.com</a></li>
            <li>Facilities: <a href="mailto:facilities@company.com">facilities@company.com</a></li>
          </ul>
      </div>
      );
  }
}
export default Tab; 
```

**Comment by pundj** [comment]
Yes, it worked. Thanks!
