### ISSUE TITLE
Deep link to tab added to group chat

### ISSUE THREAD

**Issue by matthiasdilger** [MicrosoftDocs/msteams-docs#2686]
[Enter feedback here]
The documentation mentions how to deep link into a configurableTab added to a channel. But how does it work for a configurableTab added to a group chat? Using chatId instead of channelId does not seem to work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45541337-ecd7-5cf6-cbe4-3f0d2f39aa79
* Version Independent ID: 6b4203f0-2844-06c9-eaa3-9cc03e6f76c0
* Content: [Create deep links to content - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links#feedback)
* Content Source: [msteams-platform/concepts/build-and-test/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/build-and-test/deep-links.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Mallipriya-MSFT** [comment]
Hi @matthiasdilger , Thank you for the insights on the document. We are checking this internally with Engineering Team and will update you soon.

**Comment by Mallipriya-MSFT** [comment]
Hi @matthiasdilger,
 Please try deeplinking to group chat with the below syntax:
https://teams.microsoft.com/l/entity/<appId>/<entityId>?context={"chatId": "<groupChatId>","contextType":"chat"} 

Will raise a bug to Document Team for the necessary changes to be made in the [document](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links#generating-a-deep-link-to-your-tab).

**Comment by matthiasdilger** [comment]
Hi @Mallipriya-MSFT 
Thanks but that's not the issue. Let's say the manifest contains this:

`"configurableTabs": [
    {
      "configurationUrl": "https://XXX",
      "canUpdateConfiguration": false,
      "scopes": [
        "team",
        "groupchat"
      ],
      "context": [
        "channelTab",
        "privateChatTab"
      ]
    }
  ]`

When the user adds the app to a channel or group chat, the tab above will be added. In case of a channel, **I can link into this tab** using the syntax described in the document:

`https://teams.microsoft.com/l/entity/fe4a8eba-2a31-4737-8e33-e5fae6fee194/tasklist123?webUrl=https://tasklist.example.com/123&label=Task List 123&context={"channelId": "19:cbe3683f25094106b826c9cada3afbe0@thread.skype"}`

The above works fine.

**My question is: How can I link into a tab that has been added to a group chat?** Something like 

`https://teams.microsoft.com/l/entity/fe4a8eba-2a31-4737-8e33-e5fae6fee194/tasklist123?webUrl=https://tasklist.example.com/123&label=Task List 123&context={"chatId": "19:cbe3683f25094106b826c9cada3afbe0@thread.v2"}`

But this does not work. How can I achieve this?

**Comment by matthiasdilger** [comment]
Hi @Mallipriya-MSFT 

Apologies, I misunderstood. This works, thank you!
