### ISSUE TITLE
Failed to access audio in pop-up opened by microsoftTeams.authentication.authenticate method

### ISSUE THREAD

**Issue by jean-wujingyi** [MicrosoftDocs/msteams-docs#2689]
We try to use`microsoftTeams.authentication.authenticate` method to open a new window and use web-rtc to call. But the console says `DOMException: Permission denied `when we try to get access to audio and without request pop-up. It only happenes in Teams desktop version, on web side it works well and pop up the request to ask user to grant the audio device.
It's very confusing, is there anyone has similar senarios?

**Comment by Nikitha-MSFT** [comment]
When you add auth to application it requires the permissions. Could you please check the required permissions?

**Comment by jean-wujingyi** [comment]
> When you add auth to application it requires the permissions. Could you please check the required permissions?

You mean the Device permissions on Teams? Yes I've added Media, Location, Notifications, Midi, Open External device. But this issue doesn't happen on Teams, it just happen on the new window opend by `microsoftTeams.authentication.authenticate` methods, and on web side the new window will ask me to grant the audio permission but desktop version will not.

**Comment by jean-wujingyi** [comment]
<img width="413" alt="Screen Shot 2021-01-28 at 15 19 30" src="https://user-images.githubusercontent.com/66811843/106103744-5f70d080-617c-11eb-8d94-9b7b60b61855.png">
It's the webSite version behavior, it works well but on desktop version only has console error says 'DOMException: Permission denied'. I wonder if there is a limitation on `microsoftTeams.authentication.authenticate` methods on desktop version like block getting access to audio ?

**Comment by Nikitha-MSFT** [comment]
We are not able to repro at our end, Could you please check this [docs ](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?tabs=desktop)to request permissions Request device permissions for your Microsoft Teams tab?

**Comment by jean-wujingyi** [comment]
Yes I've set all the permission. But this page is not inside Teams actually, it's a pop-up page and controled by Teams. My pop-up page could be opened without audio permission.  If you try to access Audio like using Web Audio API, it will return DOMException: Permission denied

**Comment by Nikitha-MSFT** [comment]
Could you please share which API are you using? Please share which document are you referring?

**Comment by jean-wujingyi** [comment]
I found 3 ways to open popup: using microsoftTeams.authentication.authenticate API, rendering a Adaptive card with `type: 'signin', url: 'xxxxx'` or just open popup page with this icon on tab. But every one I cannot get audio access 
<img width="385" alt="Screen Shot 2021-02-07 at 09 13 35" src="https://user-images.githubusercontent.com/66811843/107133588-cc2a5e80-6924-11eb-8726-eec16733eb46.png">

**Comment by Nikitha-MSFT** [comment]
To get audio access You need to add permissions. Please check this [docs](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?tabs=desktop) and add the permissions.
