### ISSUE TITLE
Calls and Meeting: error in a link

### ISSUE THREAD

**Issue by alexisconia** [MicrosoftDocs/msteams-docs#269]
Hello,

The link referenced in this page forwards to a 404 not found:
[https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/calls-and-meetings/debugging-local-testing-calling-meeting-bots](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/calls-and-meetings/debugging-local-testing-calling-meeting-bots)
The text is "end-to-end TLS issues".
Thanks

**Comment by billbliss** [comment]
Boy I mangled that link, didn't I? Fixed. Thanks!

**Comment by alexisconia** [comment]
:)
I also found a little typo error : "the bot can identify which **meeeting** participants" (https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/calls-and-meetings/real-time-media-concepts)
