### ISSUE TITLE
context.entityId not correct in Android web view of group tab

### ISSUE THREAD

**Issue by sr258** [MicrosoftDocs/msteams-docs#2690]
It looks like issue #1335, which was reported about a year ago, still isn't fixed. As it was closed by a bot and also locked down I can't add my report there or ask for the status. 

The problem is that context.entityId returns a very different value in the Android web view version of my group tab. When running in the browser, the Desktop app or the iOS app, the entityId I receive is the one I configured when the tab was created. In the Android web view I get a GUID f9d43794-c483-4952-b728-575678c3013b which I never set myself but which seems to come from the Teams core. The result is that the tab obviously doesn't work in the Android app, as I can't load the data for my tab.

If there won't be a fix for this, is there a workaround I can use? I'd be willing to save the GUID the Android app gets in my data model and have an alternative way of loading the data. But where does this GUID come from?

**Comment by Mallipriya-MSFT** [comment]
Hi @sr258, 
I have gone through the issue, we are investigating on it.
Sorry for the delay, It's been pending form long period. Will get back to you as soon as possible.

**Comment by Trinetra-MSFT** [comment]
@sr258 , We have a [Bug](https://domoreexp.visualstudio.com/MSTeams/_workitems/edit/781301) for this in our backlog, we will inform you once this sorted out

**Comment by Mallipriya-MSFT** [comment]
Hi @sr258, We have got confirmation from Engineering Team that the fix is not yet verified and the feature is not yet enabled for android. Hence, we are closing this question for now.

**Comment by Nikitha-MSFT** [comment]
Bug is Resolved now, we have tested this at our end, could you please also check and confirm?
