### ISSUE TITLE
Wrong port and scheme

### ISSUE THREAD

**Issue by ChrisKlug** [MicrosoftDocs/msteams-docs#2698]
The site is actually hosted on https://localhost:44390 if started through IIS Express, and 5000/5001 if using Kestrel. It is not available at http://localhost:3333 as said in the documentation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f98c73d-bb68-3088-6e7d-2c576a8292f6
* Version Independent ID: 08b9df7d-4997-c681-e73a-235ec1e4fc7b
* Content: [Tutorial - Create your first app using C# - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tutorials/get-started-dotnet-app-studio)
* Content Source: [msteams-platform/tutorials/get-started-dotnet-app-studio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tutorials/get-started-dotnet-app-studio.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Nikitha-MSFT** [comment]
Need to update the document with correct port number.  http://localhost:3333 should be replaced by https://localhost:44327

**Comment by ChrisKlug** [comment]
Actually it needs to be port 53719 as ngrok doesn't support TLS in the free tier... So the address is http://localhost:53719 for it to work with ngrok
