### ISSUE TITLE
Problems with the icons

### ISSUE THREAD

**Issue by ChrisKlug** [MicrosoftDocs/msteams-docs#2701]
The icons in the manifest are not available in the updated manifest after going through the App Studio unless you go in and update them in the editor. And if you do, it fails as they are the wrong dimensions...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f98c73d-bb68-3088-6e7d-2c576a8292f6
* Version Independent ID: 08b9df7d-4997-c681-e73a-235ec1e4fc7b
* Content: [Tutorial - Create your first app using C# - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tutorials/get-started-dotnet-app-studio)
* Content Source: [msteams-platform/tutorials/get-started-dotnet-app-studio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tutorials/get-started-dotnet-app-studio.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Trinetra-MSFT** [comment]
@ChrisKlug , By default if you don't update the icons for your app manifest in app studio, App studio give you default icons with full color and outline in the package:
![image](https://user-images.githubusercontent.com/50989436/107765619-304f8700-6d58-11eb-84bb-570c57041084.png)

The icons in the hello world app documentation is updated by user, App studio give options to the user to update the icons as per their need

**Comment by ChrisKlug** [comment]
But the demo includes incorrect icons that causes problems when running through it unfortunately.

**Comment by Jagadeesh-MSFT** [comment]
Hi @ChrisKlug, We have created PR[2815](https://github.com/MicrosoftDocs/msteams-docs/pull/2815) with updated images.
