### ISSUE TITLE
Wrong link

### ISSUE THREAD

**Issue by clearab** [MicrosoftDocs/msteams-docs#2705]
The "choose how to distribute your app" link at the bottom of the page goes to the submit to app source article, rather than the correct article

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b081ffcd-32a2-03ed-1ca9-1d32bdeff00b
* Version Independent ID: 763faefd-c15e-4d32-78ff-9fc95e7f0c73
* Content: [Understand your use cases - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/design/understand-use-cases)
* Content Source: [msteams-platform/concepts/design/understand-use-cases.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/design/understand-use-cases.md)
* Product: **msteams**
* GitHub Login: @clearab
* Microsoft Alias: **anclear**

**Comment by Nikitha-MSFT** [comment]
Need to replace the link in the content page - correct [link ](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/overview)

**Comment by KirtiPereira** [comment]
Closed the issue through https://github.com/MicrosoftDocs/msteams-docs/pull/2770.
