### ISSUE TITLE
Turn off device microphone when in-app microphone is disabled

### ISSUE THREAD

**Issue by petr-ujezdsky** [MicrosoftDocs/msteams-docs#2708]
Hi,

when I disable in-app microphone feature during the meeting, the application still uses device's microphone (as indicated by orange dot in status bar).
Is it possible to also disable device microphone? I am using Teams on iPad with AirPods and the microphone is draining AirPods battery really fast, because they have to transmit my noise and then the Teams app throws it away.

**Comment by Saonti-MSFT** [comment]
Hi @petr-ujezdsky please reach out to the [Teams Product Support](https://docs.microsoft.com/en-us/microsoftteams/platform/feedback#product-support-channels) for further guidance.

**Comment by petr-ujezdsky** [comment]
Created https://microsoftteams.uservoice.com/forums/555103-public/suggestions/42665989-do-not-use-microphone
