### ISSUE TITLE
Messaging extension docs aren't clear about supported features in preview cards

### ISSUE THREAD

**Issue by navzam** [MicrosoftDocs/msteams-docs#2724]
The [messaging extension documentation for responding to search queries](https://docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/search-commands/respond-to-search?tabs=dotnet#respond-to-user-requests) does not indicate which card features are supported in preview cards. It says preview cards can be either Hero Cards or Thumbnail Cards, but certain features of those cards (buttons, tap actions, etc.) don't work when used as previews. It'd be helpful if the documentation was explicit about which aspects of Hero/Thumbnail cards are supported.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4f3b627-c87b-6a19-9c26-7170a99f38ee
* Version Independent ID: a9546115-7c5d-39c9-ca8a-3cf3e02ff621
* Content: [Respond to search command - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/search-commands/respond-to-search?tabs=dotnet#respond-to-user-requests)
* Content Source: [msteams-platform/messaging-extensions/how-to/search-commands/respond-to-search.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/messaging-extensions/how-to/search-commands/respond-to-search.md)
* Product: **msteams**
* GitHub Login: @clearab
* Microsoft Alias: **anclear**

**Comment by Saonti-MSFT** [comment]
Hi @navzam, Thanks for bringing this issue to us. We will check and update the Documentation team so that necessary updates are done.

**Comment by Saonti-MSFT** [comment]
Hi @navzam, This is by design and documented in[ Respond to search command](https://docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/search-commands/respond-to-search?tabs=dotnet#response-card-types-and-previews) section. Please refer to the below screenshot:

![MicrosoftTeams-image](https://user-images.githubusercontent.com/77611683/108390491-becf7700-7236-11eb-9e62-d8b9f1f00df4.png)

**Comment by navzam** [comment]
Hi @Saonti-MSFT. I saw that section of the docs, but it isn't clear which aspects of Hero/Thumbnail cards are supported. It says:

> The `preview` attachment can only be a Hero or Thumbnail card.

But there are features of Hero/Thumbnail cards that aren't supported in the preview (for example, buttons and tap actions).

**Comment by Mamatha-MSFT** [comment]
Hi @navzam, I have tried to repro the [sample code](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/50.teams-messaging-extensions-search). In preview, the button actions are working and for tap "openUrl" action is working. Remaining actions in tap (like IamBack, invoke) are not working in preview. Will be raising a bug for remaining actions in tap if it gets confirmed from internal team.

**Comment by Mamatha-MSFT** [comment]
Please mention the below text in document as another point
 "**In the preview card, Button and tap(except invoke) actions of hero/thumbnail card are not supported.**"
 
 
![image](https://user-images.githubusercontent.com/78795357/114412335-a0e51980-9bca-11eb-83b1-351791180463.png)
