### ISSUE TITLE
The cyrillic letter "ж" (ASCII Code 166) works as enter

### ISSUE THREAD

**Issue by Zhuich** [MicrosoftDocs/msteams-docs#2728]
In Microsoft Teams version 1.4.00.2781 (64-bit), in the meeting scheduling interface (Calendar app > + New Meeting) when adding required attendees, pressing the cyrillic letter "ж" (ASCII Code 166) is recognized by the system as pressing the Enter key.

**Comment by Saonti-MSFT** [comment]
Hi @Zhuich, could you please share a screenshot or something because I am able to get the cyrillic letter "ж" as it is in the given Version. Please refer below image: 
![image](https://user-images.githubusercontent.com/77611683/106889208-b262fe80-670d-11eb-90e0-75a603f8de66.png)

**Comment by Zhuich** [comment]
> Hi @Zhuich, could you please share a screenshot or something because I am able to get the cyrillic letter "ж" as it is in the given Version. Please refer below image:
> ![image](https://user-images.githubusercontent.com/77611683/106889208-b262fe80-670d-11eb-90e0-75a603f8de66.png)

Hi @Saonti-MSFT, In your screenshot, you are trying to use the "*" symbol, which named Asterisk. In Russian, there is a letter "ж", it is very similar to Asterisk in spelling, but different.

I recorded a [short video](https://csit-my.sharepoint.com/:v:/g/personal/juykov_s_csitltd_ru/EalpjhaX0MxKk3z8f4NPJhABvRHIZ0z4wfHEQr8aaSJZRA?e=haG9vf) to make it clear.

**Comment by Saonti-MSFT** [comment]
@Zhuich this can be explained further by Product Support, so please connect to [Teams Product Support Channel](https://docs.microsoft.com/en-us/microsoftteams/platform/feedback#product-support-channels) for further information.
