### ISSUE TITLE
vscode unable to load $schema from "https://developer.microsoft.com/json-schemas/teams/v1.8/MicrosoftTeams.schema.json"

### ISSUE THREAD

**Issue by manutero** [MicrosoftDocs/msteams-docs#2740]
As [Creating a manifest](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/apps-package#creating-a-manifest) section suggests at the green-tip section, adding a `"$schema"` property on a json document would enable the IDE (and in particular VSCode) to hint and lint while editing. 

For some reason,

```json
{
  "$schema": "https://developer.microsoft.com/json-schemas/teams/v1.8/MicrosoftTeams.schema.json",
  ...
```

 does not work. Attaching an image:

![Captura de pantalla 2021-02-04 a las 12 51 24](https://user-images.githubusercontent.com/2211052/106889374-3609f480-66e8-11eb-9d75-3c1155ba4207.png)

As workaround, I've downloaded the .json file to local, and referencing the schema as relative path does the trick:

![Captura de pantalla 2021-02-04 a las 12 56 13](https://user-images.githubusercontent.com/2211052/106889508-605bb200-66e8-11eb-8f04-1645c476c9a9.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0b75ec1-0ded-400e-7291-b7776d510ae4
* Version Independent ID: 157f3a51-42f6-f70f-a599-6775fcb34ed1
* Content: [Package your app - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/apps-package)
* Content Source: [msteams-platform/concepts/build-and-test/apps-package.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/build-and-test/apps-package.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Nikitha-MSFT** [comment]
Could you please check this [sample example for manifest](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema#sample-full-manifest)?

**Comment by manutero** [comment]
yep, that's the one i was using for the screenshot:

![Captura de pantalla 2021-02-05 a las 9 32 31](https://user-images.githubusercontent.com/2211052/107009317-272d4b80-6795-11eb-9895-e1459cf3dbca.png)

**Comment by Nikitha-MSFT** [comment]
Could you please try adding the language to the schema. Please try the link given below: 
`https://developer.microsoft.com/en-us/json-schemas/teams/v1.5/MicrosoftTeams.schema.json`

**Comment by manutero** [comment]
that's it. 
so maybe, i'd say to update the example at https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema#sample-full-manifest 

and change, from:

```
"$schema": "https://developer.microsoft.com/json-schemas/teams/v1.8/MicrosoftTeams.schema.json",
```

to:

```
"$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.8/MicrosoftTeams.schema.json",
```

right?

**Comment by manutero** [comment]
Just a minor doc change at https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema#sample-full-manifest right?

**Comment by Wajeed-msft** [comment]
@KirtiPereira - could you please update the manifest schema reference URL to following in [Creating a manifest](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/apps-package#creating-a-manifest) section's tip?

https://developer.microsoft.com/en-us/json-schemas/teams/v1.9/MicrosoftTeams.schema.json
