### ISSUE TITLE
Not able to test a Teams Meeting app while the app is sideloaded and not published

### ISSUE THREAD

**Issue by ali-a-adl** [MicrosoftDocs/msteams-docs#2744]
Hello! I'm trying to sideload a Teams meeting app and test it but when I upload the app package using the "Upload a custom app" option I don't see any of my meetings in the list and I can only select from chats/teams. 

I can't add the app to a meeting the way described in [this doc](https://docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?tabs=dotnet#before-a-meeting) because the app is not published yet and it is sideloaded for testing. Is there a way to test an app for a meeting while it's sideloaded? 
(I was able to test it for chats, groupchats, teams but not meetings. The option to select a meeting when I upload the app package doesn't seem to exist).

I'd appreciate any help here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b60eeacc-a71e-9644-b869-3e0a4f1506d8
* Version Independent ID: 313bf83f-5325-f9f4-5780-9bc81e315c1e
* Content: [Create apps for teams meetings - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?tabs=dotnet#meeting-app-sample)
* Content Source: [msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Wajeed-msft** [comment]
Could you please try and follow these steps?
1. Schedule a new meeting with at least one user and send the invite. 
![image](https://user-images.githubusercontent.com/31851992/107068829-174e4f80-6807-11eb-88ef-865e8a0d9d23.png)
2. Now edit the meeting
![image](https://user-images.githubusercontent.com/31851992/107068937-3baa2c00-6807-11eb-8f3c-bde4c3f9824a.png)

3. Click on Add New Tab
![image](https://user-images.githubusercontent.com/31851992/107069043-609e9f00-6807-11eb-8224-2bafa92e3371.png)
4. Select Manage Tab from bottom right
![image](https://user-images.githubusercontent.com/31851992/107069125-7dd36d80-6807-11eb-851e-96eec704d87f.png)

5. Click on Upload a custom app to upload your app manifest.
![image](https://user-images.githubusercontent.com/31851992/107069590-2da8db00-6808-11eb-8e04-ffc38038a7f9.png)

Let me know if this helps.

**Comment by ali-a-adl** [comment]
That worked! Thank you very much, Wajeed.
