### ISSUE TITLE
change to 'Dataverse for Teams' 

### ISSUE THREAD

**Issue by Josverl** [MicrosoftDocs/msteams-docs#2753]
the page still references project oakdale , which is now GA as Dataverse for Teams 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4461ec7-b1c7-9cd9-c2c9-a308e46182f7
* Version Independent ID: c7fbd95d-d337-35a3-ea7d-c22176a863b5
* Content: [Low code solutions for Teams custom apps - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/samples/teams-low-code-solutions)
* Content Source: [msteams-platform/samples/teams-low-code-solutions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/samples/teams-low-code-solutions.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Trinetra-MSFT** [comment]
@Josverl , Thanks for letting us know, It seems this doc needs an update, could you please let us know where we can move this topic as per your suggestion, is it a good place [dataverse for teams](https://docs.microsoft.com/en-us/power-platform/admin/about-teams-environment)?

**Comment by Josverl** [comment]
in my view there are no 2 ways to use PowerApps in Teams 
 1.  Canvas Apps --> Share to Teams
     as described in this doc/page 
 2. DataVerse for Teams 
     as described in the doc you referred to 

I think it makes most sense to keep this document here , but update the 'Oakdale section'
 -  new name 
 -  change preview to GA 
 -  add a link / reference to [more information on Dataverse for Teams](https://docs.microsoft.com/en-us/power-platform/admin/about-teams-environment)

**Comment by Trinetra-MSFT** [comment]
@Josverl , Got it, Thanks , Document team will be looking into this
