### ISSUE TITLE
Any updates here?

### ISSUE THREAD

**Issue by jkovach82** [MicrosoftDocs/msteams-docs#276]
Any updates here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb21c0f9-0747-547f-a905-dc1e2b4fd68d
* Version Independent ID: a4b5053e-6887-89b2-0762-0de93d909bb2
* Content: [Set up single sign-on with tabs - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/scenarios/single-sign-on)
* Content Source: [msteams-platform/scenarios/single-sign-on.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/scenarios/single-sign-on.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by billbliss** [comment]
Legacy file, deleted it.
