### ISSUE TITLE
Messaging extension - GCC Tenant - Only first command is working

### ISSUE THREAD

**Issue by SubbaReddi** [MicrosoftDocs/msteams-docs#2761]
Hi Team,
We tried to use messaging extension in GCC Tenant and following is the observation:
When we add app to team, messaging extension is installed. But only the first command (recents) is showing and working. All other commands are not showing in messaging extension overflow. Even if we type other commands in compose area, don't see any response.

if it is the limitation in GCC tenant, Could you please add to the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: efcdf768-1513-2249-b344-bf38ef64c70d
* Version Independent ID: 415b5d57-2d41-9540-55a7-2a33a4315e37
* Content: [Define messaging extension action commands - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/action-commands/define-action-command)
* Content Source: [msteams-platform/messaging-extensions/how-to/action-commands/define-action-command.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/messaging-extensions/how-to/action-commands/define-action-command.md)
* Product: **msteams**
* GitHub Login: @clearab
* Microsoft Alias: **anclear**

**Comment by Mallipriya-MSFT** [comment]
Hi @SubbaReddi , Thank you for the insights on the document. Will check and raise bug to the Documentation Team to update the changes.

**Comment by Nikitha-MSFT** [comment]
Hi @SubbaReddi - Is this issue is resolved? Could you please conform?

**Comment by SubbaReddi** [comment]
Above mentioned issue is fixed and it is working fine now in GCC tenant.
