### ISSUE TITLE
Not clear whether schema version 1.9 is supported

### ISSUE THREAD

**Issue by siljemda** [MicrosoftDocs/msteams-docs#2763]
1.9 is available at https://developer.microsoft.com/json-schemas/teams/v1.9/MicrosoftTeams.schema.json - is 1.8 still the latest supported version?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f94a488-d636-92b3-21eb-c88744c8f272
* Version Independent ID: 7b3413f4-9ade-accf-5cb2-83fead11a32a
* Content: [Manifest schema reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema)
* Content Source: [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/resources/schema/manifest-schema.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Mamatha-MSFT** [comment]
@siljemda As mentioned in [documentation](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema), at this point the supporting version is 1.8.

**Comment by siljemda** [comment]
Ok, thanks.
