### ISSUE TITLE
App Studio is auto-converting my app to Schema 1.9, and the failing to install it into Teams

### ISSUE THREAD

**Issue by Nikitha-MSFT** [MicrosoftDocs/msteams-docs#2765]
**Issue**:
App studio auto converting the schema as 1.9.
**Workaround**:
Upload the manifest directly by updating the schema to 1.5

**Reference**:
https://stackoverflow.com/questions/66121113
https://stackoverflow.com/questions/66120464

**Internal Bug Tracker**: [1529546](https://domoreexp.visualstudio.com/MSTeams/_workitems/edit/1529546)

Please continue to follow this issue for updates/progress/questions.

**Comment by StefanoGermani** [comment]
How do you upload the manifest directly to 1.5?

I'm developing a new Teams app and I tried downloading the package, changing it manually and reimporting it, but in the "App Manifest (preview)" tab it keeps changing to 1.8 (before was 1.9). 

When I try to start my application locally I get this error:

arg0:{message: '', status: 400, errorCode: 'UnsupportedManifestVersion'}

**Comment by Nikitha-MSFT** [comment]
Bug is fixed.
