### ISSUE TITLE
Spelling mistake in the document

### ISSUE THREAD

**Issue by vivek-ealumalai** [MicrosoftDocs/msteams-docs#277]
Hi Teams - the document looks great could you pls correct the spelling for "Text Area" at the end of the document under the section **Controls**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c181f8cb-871f-09f5-1210-352afeaf0271
* Version Independent ID: 2a62e83d-0dd5-0cff-e45f-73d451f10b63
* Content: [Get started with App Studio for Microsoft Teams - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/get-started/get-started-app-studio)
* Content Source: [msteams-platform/get-started/get-started-app-studio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/get-started/get-started-app-studio.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by billbliss** [comment]
Will be fixed next time we publish. Thanks!

**Comment by billbliss** [comment]
Published in the interim.
