### ISSUE TITLE
Very difficult to understand what a config page is without an example

### ISSUE THREAD

**Issue by erinha** [MicrosoftDocs/msteams-docs#2771]
This documentation explains how to set up a configuration page, but it is very difficult to understand _what_ a config page actually is. An example (at least) would be helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b94a38e-82f8-45a1-8ccc-b0a96edd0404
* Version Independent ID: 6e077924-9658-cdd2-50de-0f9561d6366b
* Content: [Create a configuration page - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/configuration-page)
* Content Source: [msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by RamaMohanaChary** [comment]
Hi @erinha,

Could you please go through the [document](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs) which explains about Tabs.

Below image screenshot is from this [document](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs) only, 

![image](https://user-images.githubusercontent.com/71380905/107934046-8d8c4800-6fa5-11eb-97e0-c293dfd8b03a.png)

**Comment by erinha** [comment]
I can appreciate that there is a bunch of explanation around tabs on that page. I find that the Tabs page could also use an example to help convey some of the capabilities or familiarize developers with the Tab feature in Teams. As a Teams user prior to a Teams developer, I find these explanations very abstract. I think it would be helpful to include screenshots of an example Tab and, more importantly, an example configuration page to better explain to developers what they are building.

**Comment by RamaMohanaChary** [comment]
Hi @erinha,

We have raised a document bug for this. Tech team will follow up this bug.

![image](https://user-images.githubusercontent.com/71380905/108505795-f7765b80-72dd-11eb-979c-0da2cbddd8be.png)
