### ISSUE TITLE
Teams - Configuration page for messaging extensions

### ISSUE THREAD

**Issue by EneOli** [MicrosoftDocs/msteams-docs#2779]
Right at the top the documentation says:

> A configuration page is a special type of content page. The users configure some aspects of the Microsoft Teams app using the configuration page and use that configuration as part of the following:
> 
> A channel or group chat tab - Collect information from the users and set the contentUrl of the content page to display.
> **A messaging extension**
> An Office 365 Connector

But the docs don't make clear how to create messaging extension settings and how to use the settings set in the settings page in a messaging extension.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b94a38e-82f8-45a1-8ccc-b0a96edd0404
* Version Independent ID: 6e077924-9658-cdd2-50de-0f9561d6366b
* Content: [Create a configuration page - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/configuration-page)
* Content Source: [msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Nikitha-MSFT** [comment]
Message extension is different from the config tab. The config tab is used to add the tabs to channel/group. If you want to enable message extension you need to add message extension feature in manifest. Please check this [docs ](https://docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/what-are-messaging-extensions)for more info?

**Comment by EneOli** [comment]
But is it possible to set message action settings?

**Comment by Nikitha-MSFT** [comment]
You can only set settings related to tab. Please check this [docs](https://docs.microsoft.com/en-us/javascript/api/@microsoft/teams-js/_settings?view=msteams-client-js-latest&preserve-view=true)

**Comment by EneOli** [comment]
Ok, but why are explicitly message actions mentioned in the docs?

![IMG_20210215_113931](https://user-images.githubusercontent.com/23139864/107936096-8142c380-6f82-11eb-90f7-7cb49ca0aacb.jpg)

**Comment by EneOli** [comment]
--> messaging extensions

**Comment by Nikitha-MSFT** [comment]
You can use the config page while adding the AUTH to message extension. Could you please check this [example](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/52.teams-messaging-extensions-search-auth-config)?
