### ISSUE TITLE
Poor English

### ISSUE THREAD

**Issue by tonyatl2** [MicrosoftDocs/msteams-docs#2780]
[Enter feedback here]
This article is plagued with poor English. This phrase, "and none of us want to check our email" is grammatically incorrect. It should read "and none of us wants to check his email." The issue is number of pronoun, subject, and direct object. Clearly the writer never took grammar (successfully) or had to diagram sentences (correctly).

The subject is none; it is a singular pronoun. When I say singular I mean one (which is less than two). "of us" is a prepositional phrase with us being a plural object of the preposition. This is where your writer began to fall apart. A singular subject, in literate circles, takes a singular verb, which in this case is the verb "to want" - which conjugates as "wants" in this case. The number of the verb should agree with the subject - not the object of the preposition.

Since "none" is singular, and "wants" is singular, what do you think that the number of the direct object of the sentence should be? If you guessed single, then you are correct (which is doubtful). Is "none" sharing an email with other people? Highly unlikely. Therefore each person has his own email, and the modifier of it would be singular.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b081ffcd-32a2-03ed-1ca9-1d32bdeff00b
* Version Independent ID: 763faefd-c15e-4d32-78ff-9fc95e7f0c73
* Content: [Understand your use cases - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/design/understand-use-cases)
* Content Source: [msteams-platform/concepts/design/understand-use-cases.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/design/understand-use-cases.md)
* Product: **msteams**
* GitHub Login: @clearab
* Microsoft Alias: **anclear**

**Comment by clearab** [comment]
Thanks for the feedback!
