### ISSUE TITLE
Teams UI Documentation - Frustration

### ISSUE THREAD

**Issue by SimonDoy** [MicrosoftDocs/msteams-docs#2781]
Hi,
I am finding using the Teams UI Documentation so frustrating to use.
The Teams UI Sample does not seem to work or I cannot get it to work and when I click on the documentation for the sample it just displays a blank screen.

I would like to understand what I need to do to use the framework in code but there seems to be no way of viewing the code. It looks great in the examples that are provided but I am struggling to understand how I can use it.

An example is the Dashboard component it asks for a widget property to be provided but I have no way of seeing what properties I need to put on the widget JSON object.

Appreciate the work that has gone into it so far but it would be good to see some examples a little like the Angular Materials documentation (https://material.angular.io/components/button/overview)

![image](https://user-images.githubusercontent.com/3016016/107798656-5ecb6300-6d54-11eb-9bce-43466b1b879d.png)

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e739fdd6-8835-cfcd-f25c-1b4c7cb42afa
* Version Independent ID: 3bbef1d2-6427-0c7f-bfe2-57bf016629da
* Content: [Designing your app with UI templates - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/design/design-teams-app-ui-templates)
* Content Source: [msteams-platform/concepts/design/design-teams-app-ui-templates.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/design/design-teams-app-ui-templates.md)
* Product: **msteams**
* GitHub Login: @heath-hamilton
* Microsoft Alias: **lajanuar**

**Comment by RamaMohanaChary** [comment]
Currently this feature is not available, you can raise an [UserVoice](https://microsoftteams.uservoice.com/forums/555103-public/filters/new) if this needs to be consider as a future request.

**Comment by Trinetra-MSFT** [comment]
Please feel free to reopen if you have further query on this issue, i think [UserVoice ](https://microsoftteams.uservoice.com/forums/555103-public/filters/new)is the right place for this
