### ISSUE TITLE
Permissions?

### ISSUE THREAD

**Issue by mattmcknight** [MicrosoftDocs/msteams-docs#279]
What permissions are needed on a channel to see the add connectors option? I can't see it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0fd8e4d-f110-36f8-5bd3-db3325b14c01
* Version Independent ID: 717ea854-1d3a-2c15-e495-b6f170fe7aff
* Content: [Using Office 365 Connectors - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/connectors/connectors-using)
* Content Source: [msteams-platform/concepts/connectors/connectors-using.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/connectors/connectors-using.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Wajeed-msft** [comment]
@mattmcknight - Could you please confirm if [Allow External Apps](https://docs.microsoft.com/en-us/MicrosoftTeams/enable-features-office-365#apps) are enabled by your tenant admin. Also, enable _Allow sideloading of external apps_ if you want to sideload you custom apps in Microsoft Teams.

**Comment by mastef** [comment]
@Wajeed-msft I had the same issue today after creating a fresh team. The "add connector" option didn't show up on any channels. And when adding e.g. an incoming webhook or github connector manually through "apps", all connectors were erroring out when getting to the "options / configuration" screens.

This was resolved after trying half a day later.
