### ISSUE TITLE
Tutorial - Not Working

### ISSUE THREAD

**Issue by venuvedam** [MicrosoftDocs/msteams-docs#2794]
[Enter feedback here]

Unable to get the bot respond - Followed the tutorial to the T. Tried a couple of times. Also tried to manually register the bot. Still it doesn't respond when I type in Hello. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d083976-00c7-86bb-bdca-f909722eae6a
* Version Independent ID: 17fe4c29-7ac0-9091-c7ca-8286e80c0df9
* Content: [Get started - Build a bot - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/build-your-first-app/build-bot)
* Content Source: [msteams-platform/build-your-first-app/build-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/build-your-first-app/build-bot.md)
* Product: **msteams**
* GitHub Login: @heath-hamilton
* Microsoft Alias: **lajanuar**

**Comment by Mamatha-MSFT** [comment]
Hi @venuvedam, I have tested and it's working fine for me. Please follow the steps provided in the documentation. 
![image](https://user-images.githubusercontent.com/78795357/108353901-b06d6500-720e-11eb-8009-1775365fdd4e.png)

**Comment by Mamatha-MSFT** [comment]
Hi @venuvedam, Please let us know if you still persist the issue.
