### ISSUE TITLE
Documentation - Improvement Suggestion

### ISSUE THREAD

**Issue by venuvedam** [MicrosoftDocs/msteams-docs#2795]
1. From the Microsoft Teams client, open App Studio and select the Manifest Editor tab.
2. If you've already created your app package in App Studio, chose it from the list. If not, you can import an existing app package.
**3. Once imported, click on "Messaging extensions" under Capabilities section.** (This is missing in the documentation)
3. Select the Add button in the Command section.
4. Choose Allow users to query your service for information and insert that into a message.
5. Add a Command Id and a Title.
6. Select where you want your search command to be triggered from. Selecting message does not currently alter the behavior of your search command.
7. Add your search parameter.
8. Select Save.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d083976-00c7-86bb-bdca-f909722eae6a
* Version Independent ID: 17fe4c29-7ac0-9091-c7ca-8286e80c0df9
* Content: [Get started - Build a bot - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/build-your-first-app/build-bot)
* Content Source: [msteams-platform/build-your-first-app/build-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/build-your-first-app/build-bot.md)
* Product: **msteams**
* GitHub Login: @heath-hamilton
* Microsoft Alias: **lajanuar**

**Comment by Nikitha-MSFT** [comment]
Thank you for Reaching out us. Technical team will follow up here
