### ISSUE TITLE
Missing eventType in the callback payload

### ISSUE THREAD

**Issue by baole** [MicrosoftDocs/msteams-docs#2796]
My bot received events from MS Teams when I added the bot into a team on MS Teams. However, the callback payload doesn't include the "channelData.eventType" as described in https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/subscribe-to-conversation-events?tabs=json#team-members-added

Is there anything changes recently or do I miss something? I was included before (a few months back when I tested it)

Here is an example of the `teamMemberAdded` event

```
{
  "membersAdded": [
    {
      "id": "29:1YZSGx5JxZvVJTpCfTfjZjUtQ...",
      "aadObjectId": "0ce19686-..."
    },
    {
      "id": "28:79def875-6a91..."
    }
  ],
  "type": "conversationUpdate",
  "timestamp": "2021-02-17T14:20:26.0378605Z",
  "id": "f:1c7aa642-f63b....",
  "channelId": "msteams",
  "serviceUrl": "https://smba.trafficmanager.net/de/",
  "from": {
    "id": "29:1YZSGx5JxZvVJTpCfT...",
    "aadObjectId": "0ce19686-..."
  },
  "conversation": {
    "conversationType": "personal",
    "tenantId": "3ad9c09f-...",
    "id": "a:1I4SKOBkbyT0gxr40tIyZXS..."
  },
  "recipient": {
    "id": "28:79def875-6a91...",
    "name": "Bob"
  },
  "channelData": {
    "tenant": {
      "id": "3ad9c09f-ab9d-..."
    }
  }
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a6d00a4-dd28-33c4-002e-2e8e7c653ce2
* Version Independent ID: 0856927a-25f4-b1e0-5f1b-d55dc61796f3
* Content: [Subscribe to conversation events - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/subscribe-to-conversation-events?tabs=dotnet)
* Content Source: [msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md)
* Product: **msteams**
* GitHub Login: @WashingtonKayaker
* Microsoft Alias: **anclear**

**Comment by Nikitha-MSFT** [comment]
We are not able to repro the issue at our end. Please check the below screen shot. Also please check this [sample ](https://github.com/Trinetra-MSFT/84.teams-subscribe-to-conversation-events)for more info.

![image](https://user-images.githubusercontent.com/61688740/108317379-2dcfb000-71e4-11eb-904f-9f420c67459d.png)
