### ISSUE TITLE
Valid domains cannot contain a tunneling site

### ISSUE THREAD

**Issue by sipacate** [MicrosoftDocs/msteams-docs#2799]
[Enter feedback here]
Following the tutorial results in a blocking issue at the Test and Distribute step. Error:

_Valid domains cannot contain a tunneling site. Please remove these in your manifest. To help to ensure the security of your app and users, domains outside of your organization's control (including wildcards) and tunneling services cannot be included in the valid domains in your manifest._
--

It's a main focus of the tutorial to use the tunneling site. Please provide guidance on how to install the tutorial application.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4fa27cb-544f-f8a2-97a7-4b31528c1b80
* Version Independent ID: fa69cd6f-1ef4-706d-2816-aa709714b0aa
* Content: [Tutorial - Create your first app using Node.js - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tutorials/get-started-nodejs-app-studio)
* Content Source: [msteams-platform/tutorials/get-started-nodejs-app-studio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tutorials/get-started-nodejs-app-studio.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Jagadeesh-MSFT** [comment]
Hi @sipacate, actually it is not an ERROR which is just a warning. This warning won't effect your application and it won't be as a blocker.
