### ISSUE TITLE
Unable to save connector configuration. Please try again.

### ISSUE THREAD

**Issue by alexoliveirata** [MicrosoftDocs/msteams-docs#2800]
I've tried all options available here and on the internet.
I'm following the instructions and code examples from Microsoft Docs and I'm still having that issue.

My connector works once, then I stop the application, up again, upload a new package and the problem is back.

When I try to save my connector, I get this error: 

Received error from connectors {"seq":1613577868450,"timestamp":1613590486963,"flightSettings":{"Name":"ConnectorFrontEndSettings","AriaSDKToken":"d127f72a3abd41c9b9dd94faca947689-d58285e6-3a68-4cab-a458-37b9d9761d35-7033","SPAEnabled":true,"ClassificationFilterEnabled":true,"ClientRoutingEnabled":true,"EnableYammerGroupOption":true,"EnableFadeMessage":false,"EnableDomainBasedOwaConnectorList":false,"EnableDomainBasedTeamsConnectorList":false,"DevPortalSPAEnabled":true,"ShowHomeNavigationButtonOnConfigurationPage":false,"DisableConnectToO365InlineDeleteFeedbackPage":true},"status":500,"clientType":"SkypeSpaces","connectorType":"18888bdf-23fe-403f-a729-a55b3fb4dbb1","name":"handleMessageError"}

saveEvent = {"notified":false,"result":{}}

**Comment by RamaMohanaChary** [comment]
Hi @alexoliveirata,

Have you uninstall the older package of the connector, before installing the new package of the connector?
You will see this type of error when there is already a connector with the connector id in the group or team.
Could you please check and update.

**Comment by alexoliveirata** [comment]
I figure out that I need to wait at least 6 hours to use the connector, even in a development environment.
That is a problem anyway, any change or modification I need to wait and then test.
There is any solution for this?

**Comment by RamaMohanaChary** [comment]
Hi @alexoliveirata,

Have you tested it in your environment.
Still are you facing any issue? if yes cloud you please share us the repro steps and manifest to test from our end.
