### ISSUE TITLE
Documentation lacks technical details about displaying personal tabs in mobile clients

### ISSUE THREAD

**Issue by marwalsch** [MicrosoftDocs/msteams-docs#2804]
In the docs it states: "_The tab opens in a browser outside the Teams client using websiteUrl_.", regarding the behaviour of group tabs in the mobile client. However, how are tabs displayed inside the mobile device?

The desktop client presumably uses Electron's chromium engine, but the mobile clients are not built on Electron. Is a personal tab on mobile devices displayed through some sort of Android-/iOS-specific I-Frame web view or does the client always use the default browser and magically integrates the content into the native app?

I'd like to get some insight on that, and I think the technical details on how I-frame content is rendered on each client should be added to the docs. It could help figuring out compatibility issues with web technologies in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62b12649-8660-975a-87f6-2f7486b5dc79
* Version Independent ID: c1b86714-5b2e-79a8-5761-0fb2fd5746c0
* Content: [What are custom tabs in Teams? - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs)
* Content Source: [msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tabs/what-are-tabs.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Wajeed-msft** [comment]
@Jagadeesh-MSFT , @Nikitha-MSFT - Could you please check this and provide requested details?

**Comment by RamaMohanaChary** [comment]
Hi @marwalsch,

We have raised a [PR 2885](https://github.com/MicrosoftDocs/msteams-docs/pull/2885) to fix the doc enhancement.

**Comment by marwalsch** [comment]
@RamaMohanaChary 
Thanks, I've following up on this one already.
