### ISSUE TITLE
How can a user revoke given consent

### ISSUE THREAD

**Issue by abdulkareemnalband** [MicrosoftDocs/msteams-docs#2805]
How can a user revoke given consent

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52221dd3-95ec-96b9-1da8-9478527c2602
* Version Independent ID: 32e9c2d8-733d-0865-2ea3-727d8684a10d
* Content: [Single sign-on support for tabs - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-aad-sso)
* Content Source: [msteams-platform/tabs/how-to/authentication/auth-aad-sso.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tabs/how-to/authentication/auth-aad-sso.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by psignoret** [comment]
@abdulkareemnalband Under https://myapps.microsoft.com, you should be able to find the app in question. Clicking on the "..." should lead you to the page where you can revoke the access you've granted.

**Comment by abdulkareemnalband** [comment]
Just followup question
If an app is consented by admin for whole organization, individual users do not need to consent again in teams?

**Comment by psignoret** [comment]
For a teams app doing SSO with Azure AD as described in [this article](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-aad-sso), that is correct.
