### ISSUE TITLE
Search extension Sign Out

### ISSUE THREAD

**Issue by shash91** [MicrosoftDocs/msteams-docs#2811]
I am developing a search extension using .net. In there I need to do a sign out command.
I have followed sample app here 
[https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/52.teams-messaging-extensions-search-auth-config](url)

and it looks like this in commandBox
![CaptureSignOut](https://user-images.githubusercontent.com/18652869/108462909-700bf680-72a3-11eb-91f6-db6508415ed9.JPG)

Is that possible that I can change it's look and feel, to make it looks like in compose mode?

**Comment by Mamatha-MSFT** [comment]
Hi @shash91 It's not possible to change the design of message extension.

**Comment by Trinetra-MSFT** [comment]
@shash91 , Please let us know if you still have further query on this.
