### ISSUE TITLE
Private Channels not shown in filter-search

### ISSUE THREAD

**Issue by FredrikSal** [MicrosoftDocs/msteams-docs#2812]
When using the filter-function to find a specific team rather than using the navigation-bar, private channels is not shown in the result-list and not possible to access.

**Comment by Nikitha-MSFT** [comment]
Which Filter you are using? Are you using Graph API? Could you please share more details about the issue?

**Comment by FredrikSal** [comment]
In the Teams Tab in the client, I am using the filter function just above
the where the Teams is listed.
If browsing in the list, I do see my team and the private channels that I
have been granted privileges to, but when using the filter to find the Team
quicker, the private channels is not shown, just the public ones.

I have tried this with the following clients:
Teams Version 1.4.00.2879 (64-bit).
Teams Version 1.3.00.33674 (64-bit)
Web Client (https://teams.microsoft.com/)

**Comment by Nikitha-MSFT** [comment]
Which filter junction you are using? Could you please share which document you are referring too?
