### ISSUE TITLE
Scope name should be access_as_user  or it can be some other text also

### ISSUE THREAD

**Issue by abdulkareemnalband** [MicrosoftDocs/msteams-docs#2814]
Scope name should be access_as_user  or it can be some other text also

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52221dd3-95ec-96b9-1da8-9478527c2602
* Version Independent ID: 32e9c2d8-733d-0865-2ea3-727d8684a10d
* Content: [Single sign-on support for tabs - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-aad-sso)
* Content Source: [msteams-platform/tabs/how-to/authentication/auth-aad-sso.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tabs/how-to/authentication/auth-aad-sso.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Nikitha-MSFT** [comment]
It Should be access_as_user, the [docs ](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-aad-sso#1-create-your-azure-active-directory-azure-ad-application)says that you need to enter access_as_user as scope.

**Comment by abdulkareemnalband** [comment]
We have multiple urls for same application and different teams app manifest for each url
Is there how to configure  for multiple urls

**Comment by Nikitha-MSFT** [comment]
Could you please check  [this](https://devblogs.microsoft.com/cse/2017/01/10/creating-a-single-bot-service-to-support-multiple-bot-applications/)? try if that helps

**Comment by abdulkareemnalband** [comment]
Above link is about bot
My question is supporting teams sso for single application id shared between multiple urls
Thanks link  , we need that in separate task

**Comment by Nikitha-MSFT** [comment]
Are you still facing the issue?

**Comment by abdulkareemnalband** [comment]
Think this can be closed now
