### ISSUE TITLE
Unable to side load the app. Getting error App Not found. Please verify the app and its access Permission.

### ISSUE THREAD

**Issue by ajnavsun1806** [MicrosoftDocs/msteams-docs#2816]
Hello Team,

I am unable to side load hello world app in teams web client. I followed all the steps and then loaded the app first time where I got certificate warning. I moved past it and started the app again. Still I am getting same error **App Not found**.

Following tutorial: https://docs.microsoft.com/en-us/microsoftteams/platform/build-your-first-app/build-and-run

Do I need to setup ngrok for Personal tab app as well. Please help as I am unable to move forward.

Best Regards,
Ankit Jain

![image](https://user-images.githubusercontent.com/37746359/108676230-ec097700-750d-11eb-86f2-1b1997c78bbc.png)

**Comment by Jagadeesh-MSFT** [comment]
Hi @ajnavsun1806, It is not necessary to setup ngrok for Personal tab and I try to repro your issue from our end but I'm unable to repro. Could you please try once again, if you are still facing the issue, please share the error details.

**Comment by Nikitha-MSFT** [comment]
Please reopen the issue id you still face the issue
