### ISSUE TITLE
Issue with Action.OpenUrl in Edge and IE

### ISSUE THREAD

**Issue by Groude** [MicrosoftDocs/msteams-docs#282]
I'm using **bot** in MT. 
The issue is: I'm creating button with Action.OpenUrl, it opens a link in a new tab, but **Microsoft Edge** and **IE** blocking this link to open with default popup built in browser, saying that:

> Microsoft Edge blocked a pop-up from teams.micorosoft.com

I'm having this issue only in **Edge** and **IE**
In others browsers works fine, opens my link in new tab without any issues...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28d1cbcc-9670-6eb3-d65a-5c30d307784a
* Version Independent ID: 243e29b8-afbc-7d21-1d24-18f58619af60
* Content: [Add card actions in a bot - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/cards/cards-actions)
* Content Source: [msteams-platform/concepts/Cards/cards-actions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/Cards/cards-actions.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by billbliss** [comment]
What kind of card is this? An Adaptive card or a hero/thumbnail card?

**Comment by Groude** [comment]
@billbliss Adaptive card

**Comment by billbliss** [comment]
OK that's the problem. It's either a bug in adaptive cards or in our implementation of it. Once we figure out which and either file a bug or refer to an existing one, we can get an exception - you won't fail because of our bug.

**Comment by billbliss** [comment]
I've confirmed this is our bug. I've filed it and now we can refer to it as an exception so your app won't be failed because of it. 

Geez who makes those browsers anyway? :-)

**Comment by Groude** [comment]
@billbliss 🤣 

Thanks for your help!
Looking forward for a fix on this issue.
