### ISSUE TITLE
Document the response to the GetParticipant API

### ISSUE THREAD

**Issue by aosolis** [MicrosoftDocs/msteams-docs#2823]
There is no description of the response to GetParticipant.
Even the sample response body is hidden under the "JSON" Example tab.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b60eeacc-a71e-9644-b869-3e0a4f1506d8
* Version Independent ID: 313bf83f-5325-f9f4-5780-9bc81e315c1e
* Content: [Create apps for teams meetings - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?tabs=dotnet)
* Content Source: [msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Mamatha-MSFT** [comment]
Hi @aosolis, there is a response body under Json Example Tab. Here is the sample response for GetParticipant
`{
   "user":{
      "id":"29:1JKiJGPAX9TTxtGxhVo0wLx_zwzo-gG8Z-X03306vBwi9p-xMTEbDXsT6KH7-0kkTS8cD-2zkrsoV6f5WJ6_aYw",
      "aadObjectId":"e236c4bf-88b1-4f3a-b1d7-8891dfc332b5",
      "name":"Bob Young",
      "givenName":"Bob",
      "surname":"Young",
      "email":"Bob.young@microsoft.com",
      "userPrincipalName":"Bob.young@microsoft.com",
      "tenantId":"2fe477ab-0efc-4dfd-bde2-484374e2c373",
      "userRole":"user"
   },
   "meeting":{
      "role ":"Presenter",
      "inMeeting":true
   },
   "conversation":{
      "id":"<conversation id>",
      "isGroup":true
   }
}`

**Comment by aosolis** [comment]
@surbhigupta12 we should move the response documentation out of the JSON tab, and make it more obvious/accessible.

**Comment by surbhigupta12** [comment]
Hi @aosolis, we are working on content revamp for the [Build apps for teams meeting](https://docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/teams-apps-in-meetings) and would address this point along with the revamp activity. We would add you as a reviewer in that PR (2710) once ready.
