### ISSUE TITLE
Can't get to the advanced "Powered by Emoji One" flyout with ":d" ":o" ":p" ":s" ":x"

### ISSUE THREAD

**Issue by blzrdphoto** [MicrosoftDocs/msteams-docs#2827]
When you type ":a" you are presented a flyout list of alphabetically sorted hidden emojis that start with :a.  However if you try to type :d it immediately gets replaced with the smiley face and you cannot drill into the additional emojis that start with :d.

It shouldn't automatically replace it with the emoji until after you type a space or some sort of punctuation so that you can access the advanced emojis for these letters ":d" ":o" ":p" ":s" ":x".

**Comment by RamaMohanaChary** [comment]
Hi @blzrdphoto,

Could you please reach out to [Product Support Channel](https://docs.microsoft.com/en-us/microsoftteams/platform/feedback#product-support-channels).
