### ISSUE TITLE
Description of teamRestored looks questionable

### ISSUE THREAD

**Issue by JonathanFingold** [MicrosoftDocs/msteams-docs#2830]
When comparing the [Team restored](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/subscribe-to-conversation-events?tabs=dotnet#team-restored) and the [Team deleted](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/subscribe-to-conversation-events?tabs=dotnet#team-deleted) events, I would expect them to be symmetrical, but restoration talks about the bot being restored, and deletion talks about the team the bot is in being deleted.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a6d00a4-dd28-33c4-002e-2e8e7c653ce2
* Version Independent ID: 0856927a-25f4-b1e0-5f1b-d55dc61796f3
* Content: [Subscribe to conversation events - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/subscribe-to-conversation-events?tabs=dotnet#channel-deleted)
* Content Source: [msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md)
* Product: **msteams**
* GitHub Login: @WashingtonKayaker
* Microsoft Alias: **anclear**

**Comment by Mallipriya-MSFT** [comment]
Hi @JonathanFingold, Thank you for the insights. Will check from our end and will raise bug to the Documentation Team for the changes to be made in the document.

**Comment by RamaMohanaChary** [comment]
Hi @JonathanFingold,

Restoration from deletion, That's the correct thing please check this for [channel]( https://github.com/microsoft/BotBuilder-Samples/blob/a84fc747ff09efa04c1c7b134997f902d1c55f74/samples/csharp_dotnetcore/57.teams-conversation-bot/Bots/TeamsConversationBot.cs#L257).

**Comment by JonathanFingold** [comment]
This description seems to be in error:

## Team restored

> The bot receives a notification when it is restored from deletion. It receives a conversationUpdate event with eventType.teamrestored in the channelData object.

This implies that that bot had been deleted and that the bot has been restored, instead of the team the bot is installed in.

**Comment by RamaMohanaChary** [comment]
Hi @JonathanFingold,

Yes agree with you, we have raised a document bug for this.

**Comment by RamaMohanaChary** [comment]
Hi @KirtiPereira,

We need to update the text as "The bot receives a notification when the team it is restored from deletion."
![image](https://user-images.githubusercontent.com/71380905/112980007-ef2ffc80-9176-11eb-9ee7-0adf4508d5f7.png)

Document [link](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/subscribe-to-conversation-events?tabs=dotnet#team-restored).

**Comment by KirtiPereira** [comment]
@Jagadeesh-MSFT and @RamaMohanaChary - please validate and provide comments / approve PR #3032 
Thank you.
