### ISSUE TITLE
Number of members in Teams channel is 10,000 But what is the purpose of limitation mentioned below?

### ISSUE THREAD

**Issue by SubbaReddi** [MicrosoftDocs/msteams-docs#2833]
Documentation given as follows:
Channels contain threaded conversations between multiple people — potentially lots of people (**currently, up to two thousand**).

As Teams channel allows 10,000 members what is the purpose of people allowed in conversation is two thousand? As documentation is not clearly explained limitation, can you provide more details.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3af8496d-46be-a691-11e1-16734f71f891
* Version Independent ID: be0ff3e1-8bef-5ca7-8d9c-566e89e3fd41
* Content: [What are conversational bots? - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/what-are-bots)
* Content Source: [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/bots/what-are-bots.md)
* Product: **msteams**
* GitHub Login: @clearab
* Microsoft Alias: **anclear**

**Comment by Trinetra-MSFT** [comment]
@SubbaReddi , Please check this documentation for[ limits and specification for Microsoft Teams ](https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams), Members are the part of team not channel unless it is an` Private channel which has limit of 250` , but conversational bot has massive reach to 2000 people at a time if you try mention them in channel using Bot but more often we use single interaction using the Bot
