### ISSUE TITLE
SidePanel app without "meetingDetailsTab" context  could not be added to meeting

### ISSUE THREAD

**Issue by nickshen33** [MicrosoftDocs/msteams-docs#2837]
Like the issue described in https://blog.thoughtstuff.co.uk/2021/01/how-to-turn-a-teams-tab-into-a-in-meeting-side-bar/

Gotcha! – There seems to be a bug at the moment, where an application needs to have the “meetingChatTab” context added, otherwise it won’t show up in the final Add a tab dialog. So, even if you don’t want your application to interact via the chat tab, it looks like you have to add it for now. This feels like a bug so I would also keep an eye on this as I would expect this requirement to be removed in the future.

But based on my test, I have to add "meetingDetailsTab" context in my manifest... I only want to show my app during a meeting, is it possible?

{
    "$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.8/MicrosoftTeams.schema.json",
    "manifestVersion": "1.8",
    "version": "1.0.0",
    "id": "d956179b-3b56-43a3-81f7-e5529272559e",
    "packageName": "com.microsoft.powerapps.d956179b-3b56-43a3-81f7-e5529272559e",
    "devicePermissions": [
        "media",
        "geolocation",
        "notifications",
        "midi",
        "openExternal"
    ],
    "developer": {
        "name": "PowerApps",
        "websiteUrl": "https://powerapps.com",
        "privacyUrl": "https://portal.office.com/account#security",
        "termsOfUseUrl": "https://www.microsoftvolumelicensing.com/DocumentSearch.aspx?Mode=3&DocumentTypeId=31"
    },
    "name": {
        "short": "MeetingTestApp",
        "full": "MeetingTestApp"
    },
    "description": {
        "short": "MeetingTestApp is an app built using Power Apps.",
        "full": "MeetingTestApp is an app built using Power Apps."
    },
    "icons": {
        "outline": "outline.png",
        "color": "color.png"
    },
    "accentColor": "#00B0F0",
    "configurableTabs": [
        {
            "canUpdateConfiguration": true,
            "scopes": [
                "groupchat"
            ],
            "context": [
                "meetingSidePanel"
            ],
            "configurationUrl": "https://apps.powerapps.com/teams/settings/d956179b-3b56-43a3-81f7-e5529272559e"
        }
    ],
    "staticTabs": [
        {
            "scopes": [
                "personal"
            ],
            "entityId": "d956179b-3b56-43a3-81f7-e5529272559e",
            "name": "MeetingTestApp",
            "contentUrl": "https://apps.powerapps.com/play/d956179b-3b56-43a3-81f7-e5529272559e?tenantId=02aa3c03-f62c-4522-b2b7-e7af85e69c6a&source=teamstab&hint=c1bfb312-3a82-4b0a-8993-8acbf603ea30&locale={locale}&channelId={channelId}&channelType={channelType}&chatId={chatId}&groupId={groupId}&hostClientType={hostClientType}&isFullScreen={isFullScreen}&entityId={entityId}&subEntityId={subEntityId}&teamId={teamId}&teamType={teamType}&theme={theme}&userTeamRole={userTeamRole}",
            "websiteUrl": "https://apps.powerapps.com/play/d956179b-3b56-43a3-81f7-e5529272559e?tenantId=02aa3c03-f62c-4522-b2b7-e7af85e69c6a&hint=c1bfb312-3a82-4b0a-8993-8acbf603ea30"
        }
    ],
    "validDomains": [
        "*.powerapps.com"
    ],
    "webApplicationInfo": {
        "id": "9362bc14-3e81-4ef9-8b77-f1c40afe68e0",
        "resource": "https://apps.powerapps.com"
    }
}

**Comment by Trinetra-MSFT** [comment]
@nickshen33 , Yes ideally it should only work with meetingSidePanl in the tab context but i've tested it and i think in-meeting tab requires following in context
![image](https://user-images.githubusercontent.com/50989436/110432374-08dca780-80d5-11eb-94f4-ef201d46ecc5.png)

**Comment by nickshen33** [comment]
> @nickshen33 , Yes ideally it should only work with meetingSidePanl in the tab context but i've tested it and i think in-meeting tab requires following in context
> ![image](https://user-images.githubusercontent.com/50989436/110432374-08dca780-80d5-11eb-94f4-ef201d46ecc5.png)

Thanks. But our partner only want their app been shown during a meeting, not before/after a meeting, adding meetingDetailsTab in  in the tab context will break their  app scenario.  Why it is necessary to add meetingDetailsTab even they don't want the app shown in meeting detail tab?

**Comment by nickshen33** [comment]
Any other suggestions or comments?

**Comment by Jagadeesh-MSFT** [comment]
Hi @nickshen33, We are working on this, will update you soon.

**Comment by nickshen33** [comment]
If I only have below context, I can't find my app

"context": [
"meetingSidePanel"
]

![image](https://user-images.githubusercontent.com/24607793/113992771-60ae3000-9886-11eb-9515-8ac199a09cc2.png)

Only if I add "meetingDetailsTab" then I can select my app. 

            "context": [
                "meetingDetailsTab",
                "meetingSidePanel"
            ],

![image](https://user-images.githubusercontent.com/24607793/113995834-301bc580-9889-11eb-84c7-43aa82ce362e.png)

![image](https://user-images.githubusercontent.com/24607793/113995867-36aa3d00-9889-11eb-8ace-620ded761588.png)
