### ISSUE TITLE
How to have Call button appear from the top right of Teams UI?

### ISSUE THREAD

**Issue by vipwlb** [MicrosoftDocs/msteams-docs#285]
Hi Team, 
 I was using the schema above to upload my bot while it seems that call button is missing from the Teams UI. Could you please help to clarify how to do that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f94a488-d636-92b3-21eb-c88744c8f272
* Version Independent ID: 7b3413f4-9ade-accf-5cb2-83fead11a32a
* Content: [Manifest schema reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema#icons)
* Content Source: [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/resources/schema/manifest-schema.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by billbliss** [comment]
There are two new manifest.json settings, one of which controls whether the call button appears for a bot. See https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/calls-and-meetings/registering-calling-bot#new-manifest-settings for details.

**Comment by billbliss** [comment]
Assume this has been answered; reopen if not.
