### ISSUE TITLE
Error when trying to reuse an app package with Teams Toolkit for VSCode

### ISSUE THREAD

**Issue by nastassiar** [MicrosoftDocs/msteams-docs#2858]
When I try to either share my application with my teammates or just to try to reuse it myself with the Teams Toolkit I continuously get an error saying that the app Id does not exist in my current app studio 

![image](https://user-images.githubusercontent.com/2245717/110036195-79f51700-7cf1-11eb-9768-b51b1d060e73.png)

I also don't see an option to "Import app package" anywhere

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5e07135-25cc-d865-2cad-b3dc6f22f750
* Version Independent ID: b1c26476-0b6a-7f6c-f64a-abd1d9ae8d21
* Content: [Build apps with the Microsoft Teams Toolkit and Visual Studio Code - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/toolkit/visual-studio-code-overview#import-an-existing-teams-app-project)
* Content Source: [msteams-platform/toolkit/visual-studio-code-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/toolkit/visual-studio-code-overview.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Mallipriya-MSFT** [comment]
Hi @nastassiar, 
Please check and confirm if you have logged-in with the same organization twice while configuring the app through app studio using Microsoft Teams Toolkit.
I am able to reproduce the issue only in that case and attached the screenshot of the same
![image](https://user-images.githubusercontent.com/73868678/110116017-eac52d80-7ddc-11eb-8dcc-1277e14e8393.png)

**Comment by nastassiar** [comment]
Yes it was logged into the same org. What is going on in the backend of the Teams toolkit? I tried creating an app via app studio and replacing all the instances of the app ID that were not working in Visual Studio but I got the same error. Is there a reason this shouldn't work?

**Comment by RamaMohanaChary** [comment]
Hi @nastassiar,

May i know, whether you are still facing the same issue, could you please try again and let us know.
