### ISSUE TITLE
iOS & Teams issue dropping calls

### ISSUE THREAD

**Issue by teknoprep** [MicrosoftDocs/msteams-docs#2867]
Scenario 1 - phone status connected no dropped call IOS - 14.4

If you take a direct connect phone call or teams to teams call and do not touch or do anything to your phone while talking the call will stay connected

Scenario 2 - same as above

If you touch your iphone and try to browse the web or look at email while on a call. The call will randomly drop and the screen will say something like

hold on, looks like something went wrong. we’re trying to get you back on the call.

The call will never connect back on its own

I have found this to happen on all iPhone connected accounts across many of the companies we work for. 

We have tried every reinstall and clean up process we could find on the internet and nothing worked.

**Comment by RamaMohanaChary** [comment]
Hi @teknoprep,

Could you please reach out to [Product Support Channel](https://docs.microsoft.com/en-us/microsoftteams/platform/feedback#product-support-channels).

**Comment by v-chetsh** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.

**Comment by teknoprep** [comment]
Here is the reason behind this issue

From Microsoft

Teams engineering have said the issue is with iOS and regex. Certain patterns, such as those that contain “+?”, cause the underlying system to get stuck when performing matches
