### ISSUE TITLE
Record Meeting

### ISSUE THREAD

**Issue by naufalyafisusanto** [MicrosoftDocs/msteams-docs#2868]
Record Meeting can't record microsoft whiteboard in meeting.  It just record the participants. I hope this problem is resolved quickly
![image](https://user-images.githubusercontent.com/72088962/110183059-9ce21100-7e40-11eb-8421-45d32406075a.png)

**Comment by naufalyafisusanto** [comment]
In my 3rd party app personal recording
![image](https://user-images.githubusercontent.com/72088962/110183273-1d087680-7e41-11eb-9782-bbda2fef2412.png)

**Comment by Jagadeesh-MSFT** [comment]
@naufalyafisusanto, currently this feature is not available in MS Teams, this item remains on the backlog. We can expect this in near future as it suggested in the below image.
![image](https://user-images.githubusercontent.com/73812940/110588957-c03bf180-819b-11eb-9987-f6e1ded1f2b5.png)
