### ISSUE TITLE
Guideline on height of in-meeting dialog is misleading

### ISSUE THREAD

**Issue by aosolis** [MicrosoftDocs/msteams-docs#2869]
![image](https://user-images.githubusercontent.com/767208/110198195-88345780-7e05-11eb-8763-f3ff97f1d749.png)

This can be interpreted as saying that the height of the dialog automatically expands along with the content, which is NOT the case. The developer MUST specify the height of the content in the URL for the in-meeting dialog, and we will honor that up to the maximum height.

This is basically the same how we handle the width-- honor the value specified, up to the max width.

Please clarify this, and also let's try to describe the height and width in the same way, to avoid confusion.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09c05a14-d442-bcd1-f233-1beeddfd4bb1
* Version Independent ID: eb958ded-39dc-c0ab-a7c8-2d5bf334ab16
* Content: [Designing your meeting extension - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/design/designing-apps-in-meetings)
* Content Source: [msteams-platform/apps-in-teams-meetings/design/designing-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/apps-in-teams-meetings/design/designing-apps-in-meetings.md)
* Product: **msteams**
* GitHub Login: @heath-hamilton
* Microsoft Alias: **lajanuar**

**Comment by Trinetra-MSFT** [comment]
@aosolis , Yes, height and width specified for in-meeting dialog while forming the URL, we generally made them as constant and read it to update the URL, the best way to define height & width in constant file and use those values in `externalResourceURL `of in-meeting dialog

**Comment by KirtiPereira** [comment]
Closed with PR #2902
