### ISSUE TITLE
Clarify the guideline for task modules and in-meeting dialogs

### ISSUE THREAD

**Issue by aosolis** [MicrosoftDocs/msteams-docs#2870]
![image](https://user-images.githubusercontent.com/767208/110198325-874ff580-7e06-11eb-8ca4-24a11c4fe2aa.png)

I couldn't understand what this part meant. Finally I asked Manasi what this means, and what we really mean is that we don't want apps to launch a task module from the in-meeting dialog. Let's clarify.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b60eeacc-a71e-9644-b869-3e0a4f1506d8
* Version Independent ID: 313bf83f-5325-f9f4-5780-9bc81e315c1e
* Content: [Create apps for teams meetings - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?tabs=dotnet)
* Content Source: [msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Trinetra-MSFT** [comment]
@aosolis , Agree, we don't invoke taskModule in meeting dialog but we have content-bubble for it which works in different a way, coming to submit the data of content-bubble in-meeting dialog we use the taskModule `submitTask `method for sure to push data in meeting chat. I think we can improve this line by mentioning these points
