### ISSUE TITLE
Bug caused by Excel - "Close" button stops working on opened documents

### ISSUE THREAD

**Issue by brad992** [MicrosoftDocs/msteams-docs#2871]
This is a bug caused by Excel. It only seems to be an issue with Excel, seems to work fine otherwise. 

I'm using the hyperlink feature of excel using the address of a file which is stored on Teams. On Teams, I get this link by right-clicking on a file and clicking "Copy link". Now in Excel, clicking on this hyperlink, it opens in Teams as expected. However, the problem is that this also causes a bug. The bug is the document opened cannot be closed easily. The "Close" button on Teams does not work now. The only way to close the document from here is to click on one of the left-hand menu buttons. 

I can try to provide more info if needed.

**Comment by brad992** [comment]
Okay I'm pretty sure the core of the issue has something to do with the 255 character limit of the Hyperlink function in Excel. When using a link of a Teams file where the link has under 255 characters, the bug doesn't occur. It seems to only occur when the link I am trying to open is over 255 characters.

**Comment by Jagadeesh-MSFT** [comment]
Issue resolved by user itself.

**Comment by brad992** [comment]
I wouldn't use the word resolved. I discovered a workaround for the issue. The underlying bug still exists.

**Comment by Trinetra-MSFT** [comment]
@brad992 , I tried this to open Excel in teams itself following way
![image](https://user-images.githubusercontent.com/50989436/110429903-9918ed80-80d1-11eb-91cf-71ba6317d6e6.png)
 but could not able to repro it at my end, I can see the close button when Excel open in Teams and close button works fine.
it would be great if you can try to go "`Files`" tab and try to open excel from there, files shared in Teams stored in SharePoint and teams read it from there. if use the `Copy Link`  and try to open in new tab of browser it won't display close button you need to directly close the tab

**Comment by brad992** [comment]
I didn't do a good job at explain with words. So I made a video to explain the issue instead. The issue has gotten worse since I originally posted this.

https://www.youtube.com/watch?v=_45Wfn2UlFQ

**Comment by Jagadeesh-MSFT** [comment]
Hi @brad992, we are able to repro your issue from my end, will discuss with internal team and raise a bug for this.
