### ISSUE TITLE
getInstalledAppForTeam - Invalid teamId and/or appId specified, adding a bot to a team

### ISSUE THREAD

**Issue by stonesthatwhisper** [MicrosoftDocs/msteams-docs#2872]
> 6. In the app install dialog, select **Add for me**. (You could add the bot to a channel or chat, but it's less intrusive to others to test a bot in a one-on-one chat.)

I was following this guide. At this above step I only see an "Add" button, with the drop down choices to be

* Add to a team
* Add to a chat
* Add to a meeting

If I choose "Add to a team" and select the only team I have, a button "Set up a bot" is enabled. However, nothing happens after pressing the bottom. I got error message in VS-code:

2021-03-07T03:21:09.704Z AppsService: getInstalledAppForTeam - Invalid teamId and/or appId specified

Could you help with what teamId and appId should be?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d083976-00c7-86bb-bdca-f909722eae6a
* Version Independent ID: 17fe4c29-7ac0-9091-c7ca-8286e80c0df9
* Content: [Get started - Build a bot - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/build-your-first-app/build-bot)
* Content Source: [msteams-platform/build-your-first-app/build-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/build-your-first-app/build-bot.md)
* Product: **msteams**
* GitHub Login: @heath-hamilton
* Microsoft Alias: **lajanuar**

**Comment by Trinetra-MSFT** [comment]
@stonesthatwhisper , in your manifest you have App Id at the top and Bot id in Bot configuration, I hope you have that bot running , for more clarification on this please share your app manifest so i can check it
