### ISSUE TITLE
Custom app - Mobile (version 2.4) Search bar pushes down content

### ISSUE THREAD

**Issue by PieterVandendriessche** [MicrosoftDocs/msteams-docs#2878]
Hi all,

Currently, we are facing some issues with the latest update of MS Teams on iOS (version 2.4). In this update, the search bar was introduced for multiple apps (Activity, Chat, Teams, and Calendar). But we experience that for all custom apps this search bar is added as well. 

The search bar has some impact on the **innerheight** of the page, what is less than the **offsetheight** of the body element of the custom app. Performing a scroll action makes the search box disappear. As a result of scrolling and making the search box disappear, innerheight and offsetheight are equal then.

We have multiple custom apps that are currently affected by this change. Can we prevent this from happening? Thanks in advance for helping out!

To illustrate the behavior I am experiencing, I've attached 2 screenshots below. Please note the alert is to illustrate the difference that is created by the search box.

![With search box](https://user-images.githubusercontent.com/25928373/110305479-03139300-7ffd-11eb-9623-0c68e2e62fa9.png)
![Wihout searchbox](https://user-images.githubusercontent.com/25928373/110305483-0444c000-7ffd-11eb-926a-03aff5d70a26.png)

**Comment by Jagadeesh-MSFT** [comment]
Thanks for reaching out to us. We are the developer support team for Microsoft teams focused on helping developers resolve their code issues. For issues related to teams product, please reach out to the[ Product support channels](https://docs.microsoft.com/en-us/microsoftteams/platform/feedback#product-support-channels) for Microsoft Teams.
