### ISSUE TITLE
History inside tab-app broken

### ISSUE THREAD

**Issue by tauzN** [MicrosoftDocs/msteams-docs#2879]
You can no longer use use back and forward buttons on mouse, or upper left of Teams to navigate inside a tab-app, or tab-website. You will instead be sent back, out of the app.

**Comment by RamaMohanaChary** [comment]
Hi @tauzN, 

Could you please elaborate the issue and share us more information about the issue with proper screen shots.

**Comment by tauzN** [comment]
If I am inside a Tab-app in Microsoft Teams and navigate inside it, the functionality of the history has changed, and is not consistent with itself or the web-app (teams.microsoft.com)

Mouse-button 4 goes 1 step back in the tab-app's history as expected; but does not go further back. I would expect it to continue to go back in the Teams history. (as it did before the update, and still does in the web-app )

Mouse-button 5 does not do anything. I would expect it to go 1 step forward in the navigation history inside the tab-app, or in Teams history, if not inside a tab-app (as it did before the update, and still does in the web-app)

A key bound to the "Back navigation" in windows goes 1 step back in the Teams history (even though I am deep in navigation inside a tab-app). I would expect it to go 1 step back in the tab-app navigation and continue in the Teams history, if it has reached the end of the tab-app's history. (as it did before the update, and still does in the web-app)

A key bound to the "Forward navigation" in windows goes 1 step forward in the Teams history. I would expect it to also go 1 step forward in the tab-app navigation as well, if inside a tab-app, and has entries in the history. (as it did before the update, and still does in the web-app)

**Comment by tauzN** [comment]
You can reproduce this, by adding this example-url as a website-tab to a channel: https://css-tricks.com/examples/State/

If will be broken and inconsistent as describes earlier in Teams for Windows v. 1.4.00.4167
It will work as expected in the Teams Web-app (teams.microsoft.com)

**Comment by RamaMohanaChary** [comment]
Hi @tauzN,

Could you please reach out to [Product Support Channel](https://docs.microsoft.com/en-us/microsoftteams/platform/feedback#product-support-channels).

**Comment by tauzN** [comment]
@RamaMohanaChary 
I am not a M365 admin, and cannot contact support. This is clearly a bug, and should be taken more seriously than this.


I posted a [question on the community forum](https://answers.microsoft.com/en-us/msteams/forum/all/teams-navigation-history-broken-in-newest-update/50b2af01-3638-47d9-a454-845bc05c9cb2)

**Comment by tauzN** [comment]
Still not fixed in 1.4.00.7174
