### ISSUE TITLE
How to observe the effect of 'permissions'?

### ISSUE THREAD

**Issue by pavel-gatilov-epam** [MicrosoftDocs/msteams-docs#288]
Hello,

I am somewhat confused about the permissions section. Seems like it has no influence on either the user experience during app installation, or the data available in JS SDK Context (where user identity can be found for example).

For MS Graph API, the documentation specifies permissions required for each operation. It clarifies what is possible with which permissions. I cannot find something similar for the permissions listed on this page.

How do these permissions work? Are they ignored in case of 'sideloading' during development? Where can I read which operations depend on these permissions?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f94a488-d636-92b3-21eb-c88744c8f272
* Version Independent ID: 7b3413f4-9ade-accf-5cb2-83fead11a32a
* Content: [Manifest schema reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema#feedback)
* Content Source: [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/resources/schema/manifest-schema.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by billbliss** [comment]
In the past, these permissions used to govern what an an app could do or not, but that is not currently enforced. This document describes the current implementation: https://docs.microsoft.com/en-us/MicrosoftTeams/app-permissions
