### ISSUE TITLE
searchurl need and example of how to pass the query

### ISSUE THREAD

**Issue by timjordanatteck** [MicrosoftDocs/msteams-docs#2880]
Searchurl property in manifest does not give a suitable example of how to pass the search query to the uri

**Comment by Trinetra-MSFT** [comment]
@timjordanatteck , Could you please share more details about the issue? any documentation which you are referring will be helpful to mitigate this issue

**Comment by timjordanatteck** [comment]
The manifest lists searchurl as valid property on static tabs.
When you configure it and use the action from the command bar search <myapp> it is not clear how to pass the search term through to the search page behind. I would expect this url to include a variable which would be the value in the command bar, but this is not listed anywhere

**Comment by Jagadeesh-MSFT** [comment]
Hi @timjordanatteck, We are unable to repro your issue from my end, could you please share the documentation which you are referring will be helpful to mitigate this issue.

**Comment by timjordanatteck** [comment]
on schema v1.8
under staticTabs
searchurl property is listed as
"searchUrl":  "https://contoso.com/content (displayed in web browser)"

in the documentation section

searchUrl | string |   |   | The https:// URL to point to for a user's search queries.
-- | -- | -- | -- | --


When I add this to a static app I see the ability to search my app but no way to pass the search query to the search url from the command box. This means that the search box just ends up with no query
 ![image](https://user-images.githubusercontent.com/60363745/112332589-18342700-8c77-11eb-9a1b-77d1b6e2fbf7.png)

**Comment by Jagadeesh-MSFT** [comment]
Hi @t  , the feature isn't really available for third-party developers yet due to the way the search team designed it. It says "Open in SharePoint site" not "Open in browser", so it's not really something we can recommend to third-party developers.

Here's how it works:	

1. Update manifest: "searchUrl": "https://m365x970942.sharepoint.com/_layouts/15/search.aspx?q={​​​​​​​​​searchQuery}​​​​​​​​​"
2. When the user searches while on the personal app, they will see the following option to search the personal app in the browser:
![image](https://user-images.githubusercontent.com/73812940/115031435-c719fa80-9ee5-11eb-899a-9deae1638e23.png)

**Comment by timjordanatteck** [comment]
> Hi @timjordanatteck , the feature isn't really available for third-party developers yet due to the way the search team designed it. It says "Open in SharePoint site" not "Open in browser", so it's not really something we can recommend to third-party developers.
> 
> Here's how it works:
> 
>     1. Update manifest: "searchUrl": "[https://m365x970942.sharepoint.com/_layouts/15/search.aspx?q={​​​​​​​​​searchQuery}​​​​​​​​​](https://m365x970942.sharepoint.com/_layouts/15/search.aspx?q=%7B%E2%80%8B%E2%80%8B%E2%80%8B%E2%80%8B%E2%80%8B%E2%80%8B%E2%80%8B%E2%80%8B%E2%80%8BsearchQuery%7D%E2%80%8B%E2%80%8B%E2%80%8B%E2%80%8B%E2%80%8B%E2%80%8B%E2%80%8B%E2%80%8B%E2%80%8B)"
> 
>     2. When the user searches while on the personal app, they will see the following option to search the personal app in the browser:
>        ![image](https://user-images.githubusercontent.com/73812940/115031435-c719fa80-9ee5-11eb-899a-9deae1638e23.png)

This is exactly what I needed, the missing breadcrumb was the field is called searchQuery and it now passes to sharepoint search correctly!

**Comment by Jagadeesh-MSFT** [comment]
Hi @timjordanatteck, as of now we are closing this issue from our end please feel free to reopen the issue  if you have any further  queries on this.
