### ISSUE TITLE
iOS 14 only not showing CallKit features 

### ISSUE THREAD

**Issue by SpecialCharacterCar** [MicrosoftDocs/msteams-docs#2883]
When using latest iOS (all > iOS 14) and locking the screen on iPhones or iPads, it showed the iOS CallKit functions (MUTE etc.).

Since iOS 14 this is only shown when the TEAMS meeting attendee is invited to an active call via a pull and not if the attendee is e.g. hosting the meeting.

**Comment by v-chetsh** [comment]
@SpecialCharacterCar - Could you please confirm if your issue has resolved or still looking for any help?
