### ISSUE TITLE
Link to LinkedIn authentication providers is broken

### ISSUE THREAD

**Issue by kahopkin** [MicrosoftDocs/msteams-docs#2886]
In the section for Other authentication providers
LinkedIn Follow the instructions  in  Configuring your LinkedIn application [https://developer.linkedin.com/docs/oauth2] goes to a "page not found error".
Please fix the link
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1adae06-22cc-4547-f8ed-45c94e98611b
* Version Independent ID: bb807fa7-f008-4d1e-9282-e24280335a7e
* Content: [Configure OAuth 2.0 identity providers - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/authentication/configure-identity-provider?view=msteams-client-js-latest)
* Content Source: [msteams-platform/concepts/authentication/configure-identity-provider.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/authentication/configure-identity-provider.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by KirtiPereira** [comment]
Hi @Jagadeesh-MSFT, @Wajeed-msft  - please help with the updated link for the page or if there is any other step a user needs to take to view the page.
The following page appears on selecting the link:
![image](https://user-images.githubusercontent.com/70375155/110906709-57d34880-8332-11eb-933f-979abad04782.png)

Thank you.

**Comment by Mamatha-MSFT** [comment]
Hi @KirtiPereira Please refer to the updated link for [Configuring your LinkedIn application](https://docs.microsoft.com/en-us/linkedin/talent/apply-with-linkedin).
