### ISSUE TITLE
not able to download ngrok

### ISSUE THREAD

**Issue by apareek9** [MicrosoftDocs/msteams-docs#2890]
[gettign a message that 

Sorry, you don't have permission to visit this site.
--
 
Website blocked
Not allowed to browse Anonymizer category
You tried to visit:https://ngrok.com/download

 how do I create app for teams then? thanks!]

![image](https://user-images.githubusercontent.com/59700677/110739960-28e8a400-8258-11eb-89b2-8fa634b5865d.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ddadffa-9c95-9d7a-e609-70c31c3cafcf
* Version Independent ID: db1012ca-9813-e09d-e4dd-93fc807ada06
* Content: [Get started - Build your first app overview and prerequisites - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/build-your-first-app/build-first-app-overview?source=docs)
* Content Source: [msteams-platform/build-your-first-app/build-first-app-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/build-your-first-app/build-first-app-overview.md)
* Product: **msteams**
* GitHub Login: @heath-hamilton
* Microsoft Alias: **lajanuar**

**Comment by tauzN** [comment]
This is an issue in your organization. I am not able to download either. Ngrok will expose your computer on the network, which is a security risk.

The solution I went with is:
- Make a host-file-record for localhost.test to localhost (or your IP)
- use [mkcert](https://github.com/FiloSottile/mkcert) to make a certificate for https://localhost.test

**Comment by apareek9** [comment]
Thanks, could you highlight the process to execute the same

  *   Make a host-file-record for localhost.test to localhost (or your IP)
  *   use mkcert<https://clicktime.symantec.com/3ARNqFjMjHRonUxvag4xTUj7Vc?u=https%3A%2F%2Fgithub.com%2FFiloSottile%2Fmkcert> to make a certificate for https://localhost.test<https://clicktime.symantec.com/3PxQNY7MCTTHyS8q5W6czLi7Vc?u=https%3A%2F%2Flocalhost.test>


!! this is our time !!

amul

**Comment by tauzN** [comment]
- Create an entry in your host file 
- - Open the file "C:\Windows\System32\drivers\etc\hosts" as administrator
- - Add the line "localhost localhost.test"

- Install [mkcert](https://github.com/FiloSottile/mkcert)
- - Open a CMD as administrator
- - Type the following:
- - "mkcert -install"
- - mkcert localhost.test
- - This creates two new files: localhost.test.pem and localhost.test-key.pem
- - Add these files to your development server [options](https://nodejs.org/api/https.html#https_https_createserver_options_requestlistener) under key and cert
