### ISSUE TITLE
Share-to-Teams button blocked due to wrong cookie settings

### ISSUE THREAD

**Issue by NikolasEisberg** [MicrosoftDocs/msteams-docs#2894]
Hi Microsoft Team,

for lack of a better place to provide feedback, I write here feedback for the Share-To-Teams button.
Since this February Chromium has been updated to now allow cookies with `SameSite=Lax`.
When I try to include the Share-to-Teams button in my web application, Chromium based browsers throw the message:
`Indicate whether a cookie is intended to be set in a cross-site context by specifying its SameSite attribute`

I know that this is not the correct forum to provide feedback, but as this is a bug from my perspective, the feature request on uservoice.com is not correct as well.

Regards,
Nikolas

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5964e0a9-bba0-c5a3-8099-f3845037726c
* Version Independent ID: 24565c3b-2bb5-2482-a6c7-7b1f62e38abb
* Content: [Create a Share-to-Teams button - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/share-to-teams)
* Content Source: [msteams-platform/concepts/build-and-test/share-to-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/build-and-test/share-to-teams.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Pothan-MSFT** [comment]
Hi @NikolasEisberg, I am able to repro the issue from my end. Seems like it's a bug, yet need to get confirmation from the internal team. Will be raising the same as bug if it gets confirmed and will be sharing the details with you.

**Comment by Sridevi-MSFT** [comment]
Hi @NikolasEisberg, I have tested **Share-To-Teams** button from my end with latest Chromium version and it is working as expected. Could you please try in latest Chromium version. If the issue is still persisting  then please share repro steps, code snippets.

**Comment by NikolasEisberg** [comment]
Hi @Sridevi-MSFT  Sorry for the late reply.
Yes now it work also for me.
Thank you for your Help :)
