### ISSUE TITLE
Not able to download Video TMT 2.3 for skype - download link is invalid

### ISSUE THREAD

**Issue by tsaijian** [MicrosoftDocs/msteams-docs#2903]
Hi,

I tried to download Video TMT 2.3 for Skype tool. But the download link given on the below page is not valid anymore. Can you point where to download the tool?

https://docs.microsoft.com/en-us/skypeforbusiness/certification/test-spec

Thanks for your help.

**Comment by surbhigupta12** [comment]
We do have access to this repo. Sofia Lamprianou (slamprianou@microsoft.com) and team would be looking into it. 

Hence, removing the doc-bug label.

**Comment by Prasad-MSFT** [comment]
@tsaijian - As per engineering team TMT tool is not publicly available. Also we noticed that they heperlink is already removed from the doc.
So could you please let us know if you have any further queries?
