### ISSUE TITLE
By late 2021, bots will not be able to proactively retrieve the userPrincipalName or email properties

### ISSUE THREAD

**Issue by GauravES** [MicrosoftDocs/msteams-docs#2906]
[Enter feedback here]

Is there any updated guidance available on this as of March 2021?

> `By late 2021, bots will not be able to proactively retrieve the userPrincipalName or email properties for members of a chat/team and will need to use Microsoft Graph to retrieve them. Specifically, userPrincipalName and email properties won't be returned from the new GetConversationPagedMembers API starting in late 2021. Bots will have to use Microsoft Graph with an access token to retrieve this information. This is obviously a major change: We must make it easier for bots to get an access token, and we must streamline and simplify the end-user consent process.`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c780d605-b1b2-716f-5888-503608769b5a
* Version Independent ID: 53c724f8-d9a2-4af6-6d75-ddeaef084137
* Content: [Bot API Changes for Team/Chat Members (2020 update) - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/team-chat-member-api-changes)
* Content Source: [msteams-platform/resources/team-chat-member-api-changes.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/resources/team-chat-member-api-changes.md)
* Product: **msteams**
* GitHub Login: @ojasvichoudhary
* Microsoft Alias: **ojchoudh**

**Comment by v-sdhakshina** [comment]
The date is already updated to 2022 in the article https://docs.microsoft.com/en-us/microsoftteams/platform/resources/team-chat-member-api-changes @surbhigupta12

**Comment by surbhigupta12** [comment]
Closing this issue
