### ISSUE TITLE
Needs an actual link to the GitHub project in Step 1 of the 'Getting samples' section

### ISSUE THREAD

**Issue by alex--thomas** [MicrosoftDocs/msteams-docs#292]
Needs an actual link to the GitHub project in Step 1 of the 'Getting samples' section

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2b0e7e8-c51e-5715-308d-43d20ef5349f
* Version Independent ID: 43c28753-a32d-d81b-450c-a13dab27ab0b
* Content: [Microsoft Teams code samples - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/samples/code-samples#getting-samples)
* Content Source: [msteams-platform/samples/code-samples.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/samples/code-samples.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by arun-msft** [comment]
@alex--Thomas There are multiple GitHub samples which are listed under [Get started ](https://docs.microsoft.com/en-us/microsoftteams/platform/samples/code-samples#get-started) section. Which link do you want us to provide at step 1 of the 'Getting samples' section?

**Comment by billbliss** [comment]
@NormSohl since you are working on the getting started content can you double check we aren't missing something obvious here?

**Comment by NormSohl** [comment]
The introduction applies to all of the samples listed on this page.  I've updated the wording to try to make this clear.
