### ISSUE TITLE
Open meeting by link is not working

### ISSUE THREAD

**Issue by makisukurisu** [MicrosoftDocs/msteams-docs#2922]
OS: Linux Mint 20.1 Cinnamon
App version: teams_1.4.00.4855_amd64 (from official site)

Both in app and in browser I'm logged in using Microsoft account and GitHub integration.

When I use to join meeting Google Chrome prompts me to open app: 
![image](https://user-images.githubusercontent.com/49622129/111433421-f1ba3d00-8706-11eb-8e11-feb5c4051b71.png)
I click open, Microsoft Teams window opens/becomes in focus but it stays on whatever last page was.

Logs only show that window was drawn and monitoring of my hardware load. ([Part of log](https://jpst.it/2s3PW))

**Important info:**
Using same link, even same page to open meeting in browser with same login info results a success. And MS Teams app shows status right as "in meeting (DND)" 
I didn't try logging without GitHub, because, for some reason I fell like this might cause a little trouble, but log shows no interest in knowing what caused it to appear whatsoever.

Also sometimes Teams just log me out for no reason, but that's another issue, I think.

Thanks for reading, and thanks for your reply in advance.
P.S. feel sorry if there was issue for same topic, could not find it using Linux keyword. (Cause it looks like windows is fine, just as Android and Web)

**Comment by Sridevi-MSFT** [comment]
Hi @makisukurisu, Thanks for reaching out to us. We are the developer support team for Microsoft teams focused on helping developers resolve their code issues. For issues related to teams product, please reach out to the [Product support channels](https://docs.microsoft.com/en-us/microsoftteams/platform/feedback#product-support-channels) for Microsoft Teams.
