### ISSUE TITLE
Moodle Integration with Teams

### ISSUE THREAD

**Issue by chavomeneses** [MicrosoftDocs/msteams-docs#2923]
[Hi. I work for Moodle HQ. We have a large university wanting to develop an integration between Moodle and Teams. Is there a person that I can contact in Microsoft regarding this integration?
Regards,
Sal Meneses
salvador@moodle.com
]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97b74227-e4b9-c8a8-899b-c9633d5f1871
* Version Independent ID: c74e8703-d539-04af-d552-f6088bda3bb0
* Content: [Installing the Moodle integration with Microsoft Teams - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/moodleinstructions#feedback)
* Content Source: [msteams-platform/resources/moodleInstructions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/resources/moodleInstructions.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Sridevi-MSFT** [comment]
@chavomeneses, We have already started checking this issue internally and will update you.

**Comment by Sridevi-MSFT** [comment]
@chavomeneses, Here are the options to integrate Moodle within Teams.

1: mConnect app by Skooler(commercially available in the app store).

Here are the links to the resources ( Attached are few other resources as well).
1.	[Instructions for IT Admin to integrate Moodle into Teams.](https://skooler.com/mconnect/how-to/)
2.	[mConnect Product page](https://skooler.com/mconnect/)
3.	[Training by Skooler](https://skooler.com/mconnect/how-to/#moodle-get-started) (is at the fag end).

Skooler is willing to work on a sliding scale as well as negotiate on the SLA fees. They also answer every query to their support [email ](mailto:moodle.support@skooler.com)in 5 days even if not a premium customer.

Here is a student access to the demo environment: teams.microsoft.com

2: There is another offering by another partner [Enovation](https://enovation.ie/moodle/)( this has to be side loaded into the environment). For more on it.[Moodle Instructions](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/moodleinstructions)
[mConnect customer presentation.pptx](https://github.com/MicrosoftDocs/msteams-docs/files/6249179/mConnect.customer.presentation.pptx)
[mConnect Partnership Program eDM.pdf](https://github.com/MicrosoftDocs/msteams-docs/files/6249186/mConnect.Partnership.Program.eDM.pdf)
[mConnect_customer_eDM (1).pdf](https://github.com/MicrosoftDocs/msteams-docs/files/6249187/mConnect_customer_eDM.1.pdf)
[Benefits of upgrading to a Service License Agreement.docx](https://github.com/MicrosoftDocs/msteams-docs/files/6249189/Benefits.of.upgrading.to.a.Service.License.Agreement.docx)

**Comment by chavomeneses** [comment]
This is great. Thanks!
However, I cannot find anything related to **Teams Meeting**. We know [this exists](https://moodle.org/plugins/atto_teamsmeeting), but Moodle customers are looking for a deeper Teams Meeting integration, such as [BBB](https://moodle.org/plugins/mod_bigbluebuttonbn) or [Zoom](https://moodle.org/plugins/mod_zoom).

Regards

**Comment by Sridevi-MSFT** [comment]
@chavomeneses - The meeting solution for Moodle is an atto bar plugin that enables meeting scheduling https://moodle.org/plugins/atto_teamsmeeting
And there are no LTI meetings apps like zoom has as of yet.
