### ISSUE TITLE
The "Add an app" option is not showing during the meeting call.

### ISSUE THREAD

**Issue by Sheraz064-ai** [MicrosoftDocs/msteams-docs#2942]
The "Add an app" option is not showing during the meeting call.

(screenshot attached)
<img width="1440" alt="111591529-64034e00-87e9-11eb-8a5d-fde902fa2e50" src="https://user-images.githubusercontent.com/77956492/111778519-976fd680-88d6-11eb-8355-1b601208dea2.png">

**Comment by v-chetsh** [comment]
@Sheraz064-ai - Could you please confirm if your issue has resolved or still looking for any help?
