### ISSUE TITLE
Teams for Education - Different score in Teams and Forms

### ISSUE THREAD

**Issue by froland** [MicrosoftDocs/msteams-docs#2944]
Hello,

I've setup a quiz from an existing Microsoft Forms for my students.
The student has turned it in.
Teams shows a grade of 23 out of 24 but when I review the student submission, I get a grade of 24.
The correct grade is the one shown by Forms.

Here is the screenshot from the Teams assignment summary.
![image](https://user-images.githubusercontent.com/893622/111914513-95db1580-8a72-11eb-9683-2f5fbcb19de7.png)

And here is the one when reviewing in Forms.
![image](https://user-images.githubusercontent.com/893622/111914714-72649a80-8a73-11eb-84d4-5aa15a014248.png)

The student is seeing the same discrepancy.

**Comment by Sridevi-MSFT** [comment]
Hi @froland, Did all the students are facing the issue or the single student?

**Comment by froland** [comment]
Hi,
Only one student is affected.
