### ISSUE TITLE
Screen sharing API doesn't work inside the desktop Teams tab app 

### ISSUE THREAD

**Issue by adoronin** [MicrosoftDocs/msteams-docs#2945]
**Description**
We develop a Teams tab app that points to a website. The website contains communication by a WebRTC library (that library allows send\receive video, audio, and screen sharing). All functionality works perfectly in the web version of the Teams. But in the desktop client screen sharing doesn't work (library throws an error "The browser doesn't support screen sharing").  

**Teams client**
Desktop client.

This is a significant issue for us. Could you please confirm that screen sharing doesn't work in the current desktop Teams version? Or we can somehow resolve that? Thank you.

**Comment by RamaMohanaChary** [comment]
Hi @ydogandjiev/@lokimeyburg,

User develops a Teams tab app that points to a website, they have used custom library(WebRTC library), that library allows send\receive video, audio, and screen sharing. Its works perfectly in the web version of the Teams. But in the desktop client screen sharing doesn't work (library throws an error "The browser doesn't support screen sharing").

Could you please have a look on this.

**Comment by RamaMohanaChary** [comment]
Hi @adoronin,

Thanks for reaching us!
We took this as a high priority, checking internally with the engineering team and get back to you soon.

**Comment by RamaMohanaChary** [comment]
Hi @adoronin,

Could you please share us the document that you are referring about screen sharing in tab app for browser.

**Comment by adoronin** [comment]
Hi @RamaMohanaChary,

Thank you for support! 

I haven't found any documentation about screen sharing work in the Teams tab app. But I can give more details about the library which we using for that. We use the OpenTok library for WebRTC communication. OpenTok says that:

> Publishing screen-sharing videos is supported in Chrome, Firefox, the OpenTok plugin for Internet Explorer, Opera, Chromium-based versions of Edge (versions 79+), and Safari 13+. It is currently not supported in mobile browsers, Safari 12 and older on macOS, or non-Chromium versions of Microsoft Edge (versions prior to 79)

Also, the documentation says about screen sharing support in Electron apps (I assume MS Teams desktop client based on Electron):
> In Electron, screen sharing is supported if the webPreferences.contextIsolation option of the Electron BrowserWindow is set to false. (The default value of webPreferences.contextIsolation option is true in Electron 12 and false in previous versions).

The documentation link is:
https://static.opentok.com/developer/guides/screen-sharing/js/

Hope it will help for solving the issue. Could please look at that and share your thoughts? Also, we can directly ask the questions to OpenTok library developers if needed. Thank you.

**Comment by Mamatha-MSFT** [comment]
Hi @adoronin  - We have added this to our backlog bug. We will inform you once it's resolved.

**Comment by adoronin** [comment]
Hi @Mamatha-MSFT,
We're keeping our fingers crossed that the issue will be fixed soon. Thank you!

**Comment by AlexeyLapushinsky** [comment]
Hi, @Mamatha-MSFT. Do you have any updates?

**Comment by v-chetsh** [comment]
@AlexeyLapushinsky - We will check on it with engineering team and get back to you.

**Comment by v-chetsh** [comment]
@AlexeyLapushinsky - This feature is disabled by engineering team due to some other fixes.
We will let you know once it is available publicly again.

**Comment by Prasad-MSFT** [comment]
We got confirmation from engineering team that there is no secure way to expose screen sharing APIs in Electron. We currently have no plans to make this functionality work in the Teams Desktop Client.
