### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by NavidHeisenberg** [MicrosoftDocs/msteams-docs#2946]
When Windows screen is locked and Narrator is activated, when I receive new messages, Narrator reads all incoming messages out loud.

**Comment by Jagadeesh-MSFT** [comment]
Thanks for reaching out to us. We are the developer support team for Microsoft teams focused on helping developers resolve their code issues. For issues related to teams product, please reach out to the [Product support channels](https://docs.microsoft.com/en-us/microsoftteams/platform/feedback#product-support-channels) for Microsoft Teams.
