### ISSUE TITLE
How to migrate data from any of my databases to Teams?

### ISSUE THREAD

**Issue by prakharrke** [MicrosoftDocs/msteams-docs#295]
I wish to migrate data from a database to Teams. Can I accomplish that using connectors?

**Comment by Wajeed-msft** [comment]
[Office 365 Connectors](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/connectors/connectors) are a great way to push your app's rich content into Microsoft Teams. 
Could you please elaborate on what do you mean by **migrate data to Teams**?
