### ISSUE TITLE
Docs references Scheduled Messages even though the API can't do that

### ISSUE THREAD

**Issue by williamboxhall** [MicrosoftDocs/msteams-docs#2953]
The page mentions "Scheduled messages" but doesn't explain how you do this, and from looking at the API / source code I don't think this is possible (although I'd definitely love to be wrong about that)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ad9f167-7d29-f933-7b47-60bd744899b1
* Version Independent ID: 8097fcbd-adcc-ce49-a378-426c65af9296
* Content: [send proactive messages - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/send-proactive-messages?tabs=dotnet)
* Content Source: [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/bots/how-to/conversations/send-proactive-messages.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **anclear**

**Comment by Jagadeesh-MSFT** [comment]
Hi @williamboxhall, we have labeled it as a doc bug, concern team is working on it.
