### ISSUE TITLE
Problem with string escaping when joining by Browser

### ISSUE THREAD

**Issue by StayFN** [MicrosoftDocs/msteams-docs#2961]
When joining a Teams-Meeting as a Guest in the Browser there seems to be problems with string escaping. Sadly i can't exactly tell how to reproduce. Happened with different attendees with different browsers on different days it happened to different people. 

Day 1:
![grafik](https://user-images.githubusercontent.com/47352800/112126307-9be10b80-8bc4-11eb-9473-169fd867c1fe.png)

Day 2:
![grafik](https://user-images.githubusercontent.com/47352800/112126489-ca5ee680-8bc4-11eb-9280-a978bbbaf3b0.png)

**Comment by Sebachowa** [comment]
Having the same issue. 
Only happening as a guest and everytime you enter a room its add another string scape, and eventually having a name, like so: \“\”\“\”\“\”\“\”\“\”\“\”\“\”\“\”\“\”\“Name` (Guest)\“\”\“\”\“\”\“\”\“\”\“\”\“\”\“\”\“\”\“

**Comment by v-chetsh** [comment]
@StayFN - Could you please confirm if your issue has resolved or still looking for any help?
