### ISSUE TITLE
Channel's menu keep visible even after click item

### ISSUE THREAD

**Issue by enkhbatd** [MicrosoftDocs/msteams-docs#2962]
Issue
  When opening "Connectors" from channel's (meatballs) menu, menu is still on top (visible) other content, and not closed by itself.

Expectation
  After clicking item, the menu should be hidden (closed)

Version
  Teams for Mac v1.4.00.4971

**Comment by v-chetsh** [comment]
@enkhbatd - Could you please confirm if your issue has resolved or still looking for any help?
