### ISSUE TITLE
Teams custom app needs to be installed in one of the teams or in all teams?

### ISSUE THREAD

**Issue by yaniv-intlock** [MicrosoftDocs/msteams-docs#2969]
I have created a custom app for Teams and installed it in **only one team**. as described in [Install your app directly in Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/graph-api/rsc/resource-specific-consent#install-your-app-directly-in-teams) 

I'm using the REST API (beta) endpoint for [listing all channel messages within all of the teams](https://docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&tabs=http)

When not having the custom app installed, then I get 403 error for all teams - as expected.
When I install the custom app in **one of the teams** then the response is successful for **all teams** and I'm able to get all messages across all teams - **Is it the expected behavior?**

I would expect it to succeed only in the team where the custom app is installed and get 403 error for all other teams that don't have the custom app installed. As the article describes in the first paragraph:
![image](https://user-images.githubusercontent.com/17429159/112305107-fbafe300-8ca6-11eb-9c0d-af23bdfb5e71.png)

Teams custom permissions:
`"webApplicationInfo": {
        "id": "<my Azure app client ID>",
        "resource": "https://RscBasedStoreApp",
        "applicationPermissions": [
            "TeamSettings.Read.Group",
			  "ChannelMessage.Read.Group",
			  "TeamsApp.Read.Group",
			  "TeamsTab.Read.Group",
			  "Member.Read.Group",
			  "Owner.Read.Group"
        ]
    }`
Azure AD app permissions:
User.Read | Delegated
Group.Read.All | Application
User.Read.All | Application

**Comment by Nikitha-MSFT** [comment]
Are you trying to call list channel messages from application which has all permissions added to application? Could you please share the more info and repro steps?

**Comment by yaniv-intlock** [comment]
@Nikitha-MSFT 

> Are you trying to call list channel messages from application which has all permissions added to application?

Yes, and I want to get the messages for all the teams

I followed the steps in - https://docs.microsoft.com/en-us/microsoftteams/platform/graph-api/rsc/resource-specific-consent
The question is about [Install your app directly in Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/graph-api/rsc/resource-specific-consent#install-your-app-directly-in-teams) - should the app be added to each and every team that I would like to get messages for? or just to one team?

**Comment by Nikitha-MSFT** [comment]
No, it is not required to add app to all teams to get messages, Graph API is different from bot you can call API directly. But you require all the required permissions to get channel messages.
