### ISSUE TITLE
Manifest inconsistencies and bad links

### ISSUE THREAD

**Issue by tyler-wel** [MicrosoftDocs/msteams-docs#2972]
1. The sample full manifest has `"manifestVersion": "1.8",` while the explanation section reads
> manifestVersion
> Required — string
>
> The version of manifest schema this manifest is using. It must be 1.7.

2. The "id" section as a link `My Applications` which points to https://apps.dev.microsoft.com/#/appList. This link however displays an error and requires the user to click through to a separate page.
![image](https://user-images.githubusercontent.com/49186122/112406760-19895080-8d58-11eb-8937-9449dc5f19ca.png)"

The "id" section is also not very informative.
> The ID is a unique Microsoft-generated identifier for the app. You have an ID if your bot is registered through the Microsoft Bot Framework or your tab's web app already signs in with Microsoft. You must enter the ID here. Otherwise, you must generate a new ID at the Microsoft Application Registration Portal (My Applications). Use the same ID if you add a bot.

What if a bot is registered through the Azure Bot Channels Registration? What ID must be input here? Is it the same as the Application (client) Id in the Azure AAD Registered Apps?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f94a488-d636-92b3-21eb-c88744c8f272
* Version Independent ID: 7b3413f4-9ade-accf-5cb2-83fead11a32a
* Content: [Manifest schema reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema#schema)
* Content Source: [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/resources/schema/manifest-schema.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by RamaMohanaChary** [comment]
Hi @tyler-wel,

For the first question, 
           will update the document, concerned team will work on it.
   
           The sample full manifest has "manifestVersion": "1.8", while the explanation section reads
           manifest Version
           Required — string
          The version of manifest schema this manifest is using. It must be 1.7.

And for the second question,
        ID:   Yes, the same as the Application (client) Id in the Azure AAD Registered Apps.

**Comment by tyler-wel** [comment]
> Hi @tyler-wel,
> 
> For the first question,
> will update the document, concerned team will work on it.
> 
> ```
>        The sample full manifest has "manifestVersion": "1.8", while the explanation section reads
>        manifest Version
>        Required — string
>       The version of manifest schema this manifest is using. It must be 1.7.
> ```
> 
> And for the second question,
> ID: Yes, the same as the Application (client) Id in the Azure AAD Registered Apps.

Thanks for the update and response! LGTM
