### ISSUE TITLE
Share to Teams experience modal errors when you clear the ShareTo field

### ISSUE THREAD

**Issue by milandebuck** [MicrosoftDocs/msteams-docs#2977]
We are using the shareToTeams script to share content from our web-app and discovered this error while testing.

When you search for a Team or channel to share to and clear the field afterwards the app crashes.
[video of the issue](https://drive.google.com/file/d/1nTtIBEB5ei97KjqFriinxxT9mIYhf05h/view)

A react error also appears in the console.
![image](https://user-images.githubusercontent.com/17318991/112458643-48ee8c00-8d5d-11eb-81a8-754efed81207.png)

**Comment by Mamatha-MSFT** [comment]
@milandebuck  could you please share the code snippet, so that we can repro at our end.

**Comment by Mamatha-MSFT** [comment]
Hi @milandebuck I am unable to repro the issue. Could you please try once and let me know if you still persist the issue.



https://user-images.githubusercontent.com/78795357/112647474-93abf900-8e6e-11eb-8eac-4d00d9fb0ee9.mp4

**Comment by milandebuck** [comment]
Hi @Mamatha-MSFT,
It is stil reproducible on our end only seems to be happening when selecting a channel and then clearing the shareTo field.
I could reproduce it using this [code-example](https://stackblitz.com/edit/js-jizns2?file=index.html).
[video](https://drive.google.com/file/d/1l9ebXYc3ogETXB8fy1ol2mEsit41ILeJ/view)

**Comment by Mamatha-MSFT** [comment]
Hi @milandebuck I have reproduced the same code that you have provided. I am unable to repro the issue. It's working completely fine at our end. I am using chrome Version 89.0.4389.90 and Microsoft Edge Version 89.0.774.63. Could you please confirm which chrome version are you using. 

https://user-images.githubusercontent.com/78795357/112818561-4a8fbb00-90a1-11eb-849f-a74856e01022.mp4

**Comment by milandebuck** [comment]
Hi @Mamatha-MSFT, Tested again on multiple browsers (Microsoft Edge : 89.0.774.63 & Chromium: 89.0.4389.105) and with multiple microsoft accounts (developer and education) and could reproduce it in all cases.

**Comment by Mamatha-MSFT** [comment]
@milandebuck  We have raised a bug for this issue, concerned engineering team is working on it.

**Comment by milandebuck** [comment]
@Mamatha-MSFT just tested it again and issue seems to be resolved. We cannot reproduce it on our end and we made no changes to either the code-base or our Ms Teams setups we tested this on. Could it be that the bug has already been resolved in the meantime?

**Comment by Mamatha-MSFT** [comment]
@milandebuck This issue auto mitigated. Thanks for the insights. I am closing this from our end.
