### ISSUE TITLE
[Teams][Tabs on Mobile] Allow editing the application header on channel tabs

### ISSUE THREAD

**Issue by Aliandi** [MicrosoftDocs/msteams-docs#2979]
We are working on developing a Channel Tab with support for users both in web and mobile. On the mobile interface we are having some UX issues as we can't edit the default Teams application header nor we can't hide it to create our own. This makes navigation inside of the tab uncomfortable for the users as we have two back buttons at all times.

**Current experience**

![image](https://user-images.githubusercontent.com/22912283/111994134-2a3a8c00-8af6-11eb-8cd1-533bc01d0402.png)

**Desired experience** (from Microsoft's Tasks by Planner and To Do)

![image](https://user-images.githubusercontent.com/22912283/111994487-987f4e80-8af6-11eb-91d1-43fa672c621b.png)

**More information:**
* React ^17.0.1
* Testing on both iOS (iPhone 7 Plus, iOS 14.3) and Android (Samsung J8, Android 10)
* [Demo repository](https://github.com/southworks/ms-teams-mobile-header)

**Demo**
1. Run `npm install`
2. Run `gulp ngrok-serve`
It should output something like this:
![image](https://user-images.githubusercontent.com/22912283/112015621-beaee980-8b0a-11eb-8c8b-6fc047809b30.png)
3. Open MS Teams
4. On App Studio add the application generated by step 2
5. Once the application has been added to a channel, on mobile go to the new Channel Tab
6. It will open the first screen, to navigate click the _Home_ link
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/22912283/112015990-1188a100-8b0b-11eb-9856-805eeabf6263.png)
7. It will open the second screen, where you can see the app bar and test the navigation
![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/22912283/112016092-27966180-8b0b-11eb-879a-bd54db8d43c6.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e5840ee-09e8-93a6-51d8-508eef388b0a
* Version Independent ID: 621a526e-59dd-e81a-ee89-6a714bc055c8
* Content: [Tabs on mobile - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/design/tabs-mobile)
* Content Source: [msteams-platform/tabs/design/tabs-mobile.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tabs/design/tabs-mobile.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Jagadeesh-MSFT** [comment]
Hi @Aliandi, we are checking with our internal team, we will update you soon.

**Comment by Jagadeesh-MSFT** [comment]
Hi @Aliandi, I have tested this from my end and this is by design, we cannot remove/edit the default exit button of teams tab.

**Comment by Aliandi** [comment]
Trough testing we have also noted that the default header works inconsistently, which is what gave us the need of a second header. In some mobile devices, the back button navigates through the tab, but in other devices it goes back to the Teams menu.
Which is the correct behaviour?

**Comment by Jagadeesh-MSFT** [comment]
Hi @Aliandi, are you still facing the issue, we are unable to repro this issue from our end.

**Comment by Aliandi** [comment]
Yes, we can still verify this issue exists. It's not on every device though. I've had issues with iOS but not on Android. Pressing the default back navigation button takes me outside of the custom tab instead of navigating through it in some devices, while in others it lets me navigate through the tab.

**Comment by Jagadeesh-MSFT** [comment]
Hi @Aliandi, sorry for asking this again, could you please try again in iso devices with different versions, if you still facing the issue then we will raise a bug for this.

**Comment by Aliandi** [comment]
We will be testing this tomorrow and will let you know if we can still repro it. Sorry for the delay.
