### ISSUE TITLE
Teams Toolkit Bots Not Visible in Azure Bot Channel Registration

### ISSUE THREAD

**Issue by TracyGH** [MicrosoftDocs/msteams-docs#2982]
As part of the Teams Toolkit build/set-up instructions for a messaging extension, I am supposed to [enable the bot's Teams Channel](https://docs.microsoft.com/en-us/azure/bot-service/channel-connect-teams?view=azure-bot-service-4.0) (see below).  However, the new bot's I have generated within the toolkit do not appear within Azure's Bot Channel Registration (see below), so I have no way to enable that channel.  

**To confirm, I am logged into the Teams Toolkit with the same account viewing the Azure Portal in the screenshot below.**  
The only bot's available within the channel registration are those I have [manually created](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-quickstart-registration?view=azure-bot-service-4.0).  

I have found this to be true within the Teams Toolkits extensions for both Visual Studio and VSCode.  

![image](https://user-images.githubusercontent.com/38665906/112534832-d1265e80-8d68-11eb-8fff-1e77b1bfb3db.png)

![image](https://user-images.githubusercontent.com/38665906/112535355-72151980-8d69-11eb-8dda-f157c7747bde.png)

![image](https://user-images.githubusercontent.com/38665906/112535462-8f49e800-8d69-11eb-8883-338053197845.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5dbbdd70-5068-9e54-b797-7a32ea45672f
* Version Independent ID: 8719249a-face-cf09-04a2-57d7cde082a9
* Content: [Get started - Build a messaging extension - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/build-your-first-app/build-messaging-extension)
* Content Source: [msteams-platform/build-your-first-app/build-messaging-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/build-your-first-app/build-messaging-extension.md)
* Product: **msteams**
* GitHub Login: @heath-hamilton
* Microsoft Alias: **lajanuar**

**Comment by Nikitha-MSFT** [comment]
Are you using the same account in visual studio and azure. Could you please conform?

**Comment by TracyGH** [comment]
@Nikitha-MSFT - Yes, confirmed.  I mentioned that in my original post.

**Comment by Nikitha-MSFT** [comment]
When you Register bot using toolkit, the bot will be registered in https://dev.botframework.com/bots - could you please check is your bot is visible in bot-framework?

**Comment by TracyGH** [comment]
@Nikitha-MSFT - That worked - thank you!  And it looks like the Toolkit automatically adds the Teams channel.  I couldn't find any references to that https://dev.botframework.com URL, except some [legacy documentation](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bots-create).  Is that intentional?

![image](https://user-images.githubusercontent.com/38665906/115095967-253fe100-9ed8-11eb-8e89-c1c4dced9cfa.png)
