### ISSUE TITLE
Adding a bot to teams

### ISSUE THREAD

**Issue by UrjaswitSingh** [MicrosoftDocs/msteams-docs#299]
How does T-Bot can be found on search bar. It does not appear in store. Is there any way to see bot created by other user without publishing it. Here it is shown we need to add appid in the search bar, but is there any mechanism to direct search the botname in the search bar. Please provide relevent details as I am doing a project related to microsoft teams and is in urgent need.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac99cf82-194d-eb31-2d29-7368ba895edc
* Version Independent ID: aab61691-1db4-8580-53be-d4665c96e5be
* Content: [Test your bot - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/bots/bots-test)
* Content Source: [msteams-platform/concepts/bots/bots-test.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/bots/bots-test.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by billbliss** [comment]
We are updating our getting started documentation to feature App Studio more prominently but this is where to start: https://docs.microsoft.com/en-us/microsoftteams/platform/get-started/get-started-app-studio#manifest-editor. You need to create a manifest and load your bot. You can now do it directly from App Studio.
