### ISSUE TITLE
Confused consent title/description

### ISSUE THREAD

**Issue by Rick-Kirkham** [MicrosoftDocs/msteams-docs#2991]
The article suggests the following for the title and description in the consent prompt presented to the user. 

**User consent title**: Teams can access the user profile and make requests on the user's behalf.
**User consent description**: Teams can call this app’s APIs with the same rights as the user.

But referring to "the user" in 3rd person like this makes no sense (unlike the Admin consent prompt which is in the 2 bullets above what I just quoted). Since the user sees this prompt and no one else, the prompt should use 2nd person like this: 

**User consent title**: Teams can access _your_ profile and make requests on _your_ behalf.
**User consent description**: Teams can call this app’s APIs with the same rights as _you have_.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52221dd3-95ec-96b9-1da8-9478527c2602
* Version Independent ID: 32e9c2d8-733d-0865-2ea3-727d8684a10d
* Content: [Single sign-on support for tabs - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-aad-sso)
* Content Source: [msteams-platform/tabs/how-to/authentication/auth-aad-sso.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tabs/how-to/authentication/auth-aad-sso.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Nikitha-MSFT** [comment]
Tech writing team will follow up and update the docs.
