### ISSUE TITLE
You have Set the Connection Name twice in the instructions

### ISSUE THREAD

**Issue by johnkellyjr** [MicrosoftDocs/msteams-docs#2992]
Set the ConnectionName to the name of the identity provider connection appears twice, and it can only be set once.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63519845-323f-be8f-ce15-d7f39e46b5a7
* Version Independent ID: 70952f91-56e9-ff08-59f6-e237d4aaeca9
* Content: [Add authentication to your Teams bot - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/authentication/add-authentication?tabs=dotnet%2Cdotnet-sample)
* Content Source: [msteams-platform/bots/how-to/authentication/add-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/bots/how-to/authentication/add-authentication.md)
* Product: **msteams**
* GitHub Login: @clearab
* Microsoft Alias: **lajanuar**

**Comment by RamaMohanaChary** [comment]
Hi @johnkellyjr,
Thank you for reporting. Tech writing team will work and update the document.

**Comment by RamaMohanaChary** [comment]
Hi @KirtiPereira,

Could you please have a look on below screenshot, user saying that the line mentioned twice.
![image](https://user-images.githubusercontent.com/71380905/112801105-1f4fa080-908e-11eb-96f9-18387bb7d18b.png)
