### ISSUE TITLE
Clarification on what each user type can do regarding apps in Teams meeting

### ISSUE THREAD

**Issue by Benjiiim** [MicrosoftDocs/msteams-docs#2995]
Is it possible to provide some clarification on what each user type can do regarding apps in Teams meeting?

It is crystal clear in the documentation regarding anonymous users ("Anonymous users will not be able to access apps in a meeting window.") but not for Guest and External users.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82987815-d508-d642-c1f6-b609241d4750
* Version Independent ID: 29e89cc6-c8ca-7d29-7dca-4ac4d06f5c42
* Content: [Apps in Teams meetings - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/teams-apps-in-meetings)
* Content Source: [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Jagadeesh-MSFT** [comment]
Hi @Benjiiim, Thank you for reporting. Tech writing team will work and update the document.
