### ISSUE TITLE
Windows Defender blocks ngrok installation

### ISSUE THREAD

**Issue by Rick-Kirkham** [MicrosoftDocs/msteams-docs#2996]
When I run the ngrok installer, I get the following error. Should I install anyway? 

![image](https://user-images.githubusercontent.com/9088056/112775709-8750a900-8ff2-11eb-91b7-3b0eddc67a38.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ddadffa-9c95-9d7a-e609-70c31c3cafcf
* Version Independent ID: db1012ca-9813-e09d-e4dd-93fc807ada06
* Content: [Get started - Build your first app overview and prerequisites - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/build-your-first-app/build-first-app-overview)
* Content Source: [msteams-platform/build-your-first-app/build-first-app-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/build-your-first-app/build-first-app-overview.md)
* Product: **msteams**
* GitHub Login: @heath-hamilton
* Microsoft Alias: **lajanuar**

**Comment by Jagadeesh-MSFT** [comment]
Hi @Rick,This warning won't block you, you can ignore it. but, we recommend you to contact your it support team.

**Comment by Rick-Kirkham** [comment]
Yes. It does block me. It prevents ngrok from being installed and ngrok is required for making Teams bots. Please reopen this.

**Comment by Wajeed-msft** [comment]
Hi @Rick-Kirkham - ngrok is used for debugging your code locally which exposes local services to the outside world over HTTPS. You should check with your IT admin regarding the policies for installing tools and take it forward. There is alternative tool for ngrok which is [Tunnel Relay](https://github.com/OfficeDev/microsoft-teams-tunnelrelay) which uses [Azure Relay](https://docs.microsoft.com/en-us/azure/azure-relay/relay-what-is-it#hybrid-connections) to provide similar functionality. 

You can also deploy your code to public endpoint and use it directly.

**Comment by rick** [comment]
![](https://media.giphy.com/media/ubip78GsEtZeg/giphy.gif)

**Comment by Wajeed-msft** [comment]
This can be closed. Confirmed with @Rick-Kirkham.
