### ISSUE TITLE
Hello World installation fails 

### ISSUE THREAD

**Issue by Rick-Kirkham** [MicrosoftDocs/msteams-docs#2997]
When I run `npm install` I get the following error: 

![image](https://user-images.githubusercontent.com/9088056/112777931-35ab1d00-8ff8-11eb-8069-85aa063f4bff.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f876156-cc1e-468f-4647-5143a5de03b1
* Version Independent ID: 618f43a3-3371-ad99-13aa-087b9303298c
* Content: [Get started - Build and run your first app - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/build-your-first-app/build-and-run)
* Content Source: [msteams-platform/build-your-first-app/build-and-run.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/build-your-first-app/build-and-run.md)
* Product: **msteams**
* GitHub Login: @heath-hamilton
* Microsoft Alias: **lajanuar**

**Comment by RamaMohanaChary** [comment]
Hi @Rick-Kirkham,

Could you please take latest version of npm(v7.7.5) and try to install.
Please have a look on this [document](https://www.npmjs.com/package/npm/v/7.7.5).

**Comment by Rick-Kirkham** [comment]
The problem only occurs when I run the command in the terminal inside Visual Studio Code. The installation works when I run the command in an separate command prompt window. Please update the doc to tell readers not to use the terminal in VSC.

**Comment by RamaMohanaChary** [comment]
Hi @Rick-Kirkham,

We are unable to repro the issue from our end, working fine as expected. Could you please retry and let us know.

**Comment by Nikitha-MSFT** [comment]
@Rick-Kirkham - Are you still facing the issues? if yes, could you please reopen the issue with proper repro steps. Closing the issue for now.
