### ISSUE TITLE
Button for last step not enabled

### ISSUE THREAD

**Issue by Rick-Kirkham** [MicrosoftDocs/msteams-docs#2998]
The last step tells me to press the **Add for me** button. There is no such button. There is an **Add** button but it is disabled and there is a message telling me to ask my IT Admin to add the app for "this team".  Since this is my developer account, I presume that I am the IT Admin. How do I  add the app and, BTW, what team is "this team'?

![image](https://user-images.githubusercontent.com/9088056/112778974-92a7d280-8ffa-11eb-8923-e56798d727d4.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f876156-cc1e-468f-4647-5143a5de03b1
* Version Independent ID: 618f43a3-3371-ad99-13aa-087b9303298c
* Content: [Get started - Build and run your first app - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/build-your-first-app/build-and-run)
* Content Source: [msteams-platform/build-your-first-app/build-and-run.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/build-your-first-app/build-and-run.md)
* Product: **msteams**
* GitHub Login: @heath-hamilton
* Microsoft Alias: **lajanuar**

**Comment by Nikitha-MSFT** [comment]
You permissions are blocked by your organization to application. You need to add the required permissions to add an app to team could you please check this [Manage app permission policies in Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-app-permission-policies)

**Comment by Rick-Kirkham** [comment]
It's working now.
