### ISSUE TITLE
Missing upload instructions 

### ISSUE THREAD

**Issue by Rick-Kirkham** [MicrosoftDocs/msteams-docs#2999]
There is a note saying "It can take up to 24 hours before sideloading is enabled. During interim, you can use upload for <your tenant> to test your app." 

But pressing this upload link in Teams simply opens a File system navigation dialog. There are no instructions about what to navigate too. Please add a couple of sentences to the note telling readers to upload the zipped package file of the app and the path where they can find it. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3530b55-59c8-6eec-b257-b7a5f2ed046b
* Version Independent ID: 022f7eff-f6c2-9a73-afa9-74e887b761e1
* Content: [Prepare your Microsoft 365 tenant - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/prepare-your-o365-tenant#enable-custom-teams-apps-and-turn-on-custom-app-uploading)
* Content Source: [msteams-platform/concepts/build-and-test/prepare-your-o365-tenant.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/build-and-test/prepare-your-o365-tenant.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Jagadeesh-MSFT** [comment]
Hi @Rick-Kirkham, Thanks for brining up this suggestion, We will ask document team to look into this and make the document better.

**Comment by Jagadeesh-MSFT** [comment]
Hi @Rick-Kirkham, it has clearly explained in the [this](https://docs.microsoft.com/en-us/microsoftteams/upload-custom-apps#upload) link that how to upload  Zip file/manifest and location of the file is depends on user hat where his file is located.

**Comment by Rick-Kirkham** [comment]
But the reader of the article I raised this issue about (see the Document Details box above) cannot know about some other article, unless you link to it. The note in this screen shot needs to link to:

https://docs.microsoft.com/en-us/microsoftteams/upload-custom-apps#upload

![image](https://user-images.githubusercontent.com/9088056/114950781-a8920180-9e08-11eb-82f3-d8c64310ba4e.png)
