### ISSUE TITLE
Link to developer preview is broken

### ISSUE THREAD

**Issue by roppel** [MicrosoftDocs/msteams-docs#300]
Link to developer preview is broken

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86441a60-584c-73d1-d678-1c3a2c38a872
* Version Independent ID: 35ca31ef-620b-7ff4-d91c-e4aa9eacf5a1
* Content: [Overview of Microsoft Teams Task Modules - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/task-modules/task-modules-overview)
* Content Source: [msteams-platform/concepts/task-modules/task-modules-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/task-modules/task-modules-overview.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by NormSohl** [comment]
Thanks - fixed in master, will be deployed to live by end of day, pacific time.

**Comment by NormSohl** [comment]
Thanks again for pointing this out.  It is now fixed and live.  Closing the issue.
