### ISSUE TITLE
Deep links to tab not working for MS Teams Mobile apps

### ISSUE THREAD

**Issue by charliedavison** [MicrosoftDocs/msteams-docs#3007]
I am trying to use the deep link functionality to direct users from our web application to a tab within our MS Teams personal tab application.

Using the documentation here: https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/build-and-test/deep-links.md#showing-a-deep-link-to-an-item-within-your-tab

I have crafted the URL

`https://teams.microsoft.com/l/entity/4e9afe6e-9fd0-4893-899d-03fa732432b7/Dashboard`

 and this works fine on desktop, but the mobile applications this fails with the following message

![image](https://user-images.githubusercontent.com/3127181/112818956-fcb48c00-907b-11eb-910f-7847a0b53ca2.png)

I cannot see anything in the docs that suggest that these links shouldn't work for mobile apps - is this intended behavior or should the link work correctly across all platforms?

**Comment by Mamatha-MSFT** [comment]
Hi @charliedavison currently, `shareDeepLink` does not work on mobile platforms. Please go through this [documentation](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links#deep-linking-to-your-tab) for more details.

**Comment by charliedavison** [comment]
Hi @Mamatha-MSFT, thanks for getting back to me, I'm not trying to use the `shareDeepLink` function itself, I'm just creating the url myself using the format in the documentation.

I assume that the urls `shareDeepLink` creates are the same as the one I am constructing though - is the limitiation then on the URL's themselves not working on mobile platforms as opposed to the `shareDeepLink` function in the SDK?

**Comment by Mamatha-MSFT** [comment]
Use the following format for a deep link to tab
`https://teams.microsoft.com/l/entity/<appId>/<entityId>?webUrl=<entityWebUrl>&label=<entityLabel>&context=<context>`
Please try and let me know if you still persist the issue.

**Comment by charliedavison** [comment]
That is the format I have been using and is when I see this issue.

**Comment by charliedavison** [comment]
> That is the format I have been using and is when I see this issue.

**Comment by charliedavison** [comment]
@Mamatha-MSFT sorry, reopened as closed in error, see previous message. Thanks

**Comment by Mamatha-MSFT** [comment]
@charliedavison Could you please explain are you sending deepLink as a message or adding the same deep link URL into an Action.OpenUrl in cards and also Please share your mobile model and version details.

**Comment by charliedavison** [comment]
Sure - what I'm trying to do is create a flow where we can direct users to our web application to complete part of signup journey and then return them to teams.

So the flow would be - 

User opens the teams tab -> Clicks signup -> We open the web application -> They complete signup -> We then redirect the user to a teams deep link which takes them back to teams -> User is able to login.

This flow works on the desktop, the teams app is successfully opened again back to the correct tab as configured in the URL: https://teams.microsoft.com/l/entity/4e9afe6e-9fd0-4893-899d-03fa732432b7/Dashboard

It is only on the mobile platforms where I see the error.

**Comment by Mamatha-MSFT** [comment]
@charliedavison I am able to repro the issue. I think it is a bug. 
![image](https://user-images.githubusercontent.com/78795357/113110167-64a5d680-9224-11eb-8087-79e5ced10e63.png)

**Comment by Mamatha-MSFT** [comment]
@charliedavison We have raised a bug for this issue, concerned team is working on it.

**Comment by Mamatha-MSFT** [comment]
Hi @charliedavison, Could you please try to uninstall the existing app and create a new app. Make sure to enter correct entity ID https://teams.microsoft.com/l/entity/<appId>/<entityId>
Try and let me know if you still persist the issue.

**Comment by Mamatha-MSFT** [comment]
Hi @charliedavison Please let us know if you still persists the issue.
