### ISSUE TITLE
Toolkit UI is quite different from the screenshot

### ISSUE THREAD

**Issue by Rick-Kirkham** [MicrosoftDocs/msteams-docs#3017]
Step 3 implies that the user will see a simple Add capabilities page, but the actual page seen at this point is much different. Here's a screenshot: 

![image](https://user-images.githubusercontent.com/9088056/112776432-7d2faa00-8ff4-11eb-920c-262490e4e38a.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f876156-cc1e-468f-4647-5143a5de03b1
* Version Independent ID: 618f43a3-3371-ad99-13aa-087b9303298c
* Content: [Get started - Build and run your first app - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/build-your-first-app/build-and-run)
* Content Source: [msteams-platform/build-your-first-app/build-and-run.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/build-your-first-app/build-and-run.md)
* Product: **msteams**
* GitHub Login: @heath-hamilton
* Microsoft Alias: **lajanuar**

**Comment by Nikitha-MSFT** [comment]
We are looking into the issue we will get back to you

**Comment by v-rpatkur** [comment]
Hi @Rick-Kirkham, the content page mentioned provides an overview for the Get started module. Please specify the doc link.

**Comment by Rick-Kirkham** [comment]
@v-rpatkur  You've changed the file and even the file names so much since I created this issue, that I don't know where the misleading text is now.

**Comment by v-abirade** [comment]
@surbhigupta12, need your assistance.

**Comment by v-ypalikila** [comment]
Hi,

The article is updated as an step-by-step guide. The step "[Create project workspace for your tab app](https://docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-javascript?tabs=vscode%2Cvsc%2Cviscode%2Cvcode&tutorial-step=2)" allows the user to select a capability in the Teams Toolkit.

**Comment by v-chetsh** [comment]
@v-ypalikila - Could you please close the issue if it is already fixed?
