### ISSUE TITLE
Tutorial doesn't work. Missing step.

### ISSUE THREAD

**Issue by Rick-Kirkham** [MicrosoftDocs/msteams-docs#3018]
This issue is actually for the article "https://docs.microsoft.com/en-us/microsoftteams/platform/build-your-first-app/build-personal-tab, but the Feedback tool at the bottom of the page keeps creating an issue for a different article. 

When the tutorial  linked to above is complete, it does not work. It simply makes the content dark, regardless of whether the the users theme is light or dark. This is because the handler that's supposed to register the change in theme in the app's state doesn't work. And the reason it doesn't work is that there is no `theme` property in the app's state. To fix this, you have to tell the reader to add a `theme` property to state in the constructor. So you need a step that tells the reader to change the constructor to look like this:

```
constructor(props){
    super(props)
    this.state = {
      context: {},
      theme: {}
    }
  }
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f876156-cc1e-468f-4647-5143a5de03b1
* Version Independent ID: 618f43a3-3371-ad99-13aa-087b9303298c
* Content: [Get started - Build a Personal Tab - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/build-your-first-app/build-personal-tab)
* Content Source: [msteams-platform/build-your-first-app/build-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/build-your-first-app/build-personal-tab.md)
* Product: **msteams**
* GitHub Login: @heath-hamilton
* Microsoft Alias: **lajanuar**

**Comment by Mamatha-MSFT** [comment]
Hi @Rick-Kirkham Thanks for bringing up this issue, I will repro at my end and will let you know.

**Comment by Mamatha-MSFT** [comment]
@Rick-Kirkham I am able to repro the issue. I have tried with the code changes provided by you but still facing the same issue. I think it is a bug.

**Comment by Mamatha-MSFT** [comment]
Please update [Create a theme change handler ](https://docs.microsoft.com/en-us/microsoftteams/platform/build-your-first-app/build-personal-tab#create-a-theme-change-handler)code with 

  ```
microsoftTeams.registerOnThemeChangeHandler(theme => {
  if (theme !== this.state.context.theme) {
    this.setState({
      context: {
      ...this.state.context,
      theme
      }
      })   
      }
    });
```

and update [Match theme style](https://docs.microsoft.com/en-us/microsoftteams/platform/build-your-first-app/build-personal-tab#match-theme-styles) code with `const isTheme = this.state.context.theme`

**Comment by v-vrajaraman** [comment]
Fixed as part of [#2907 ](https://github.com/MicrosoftDocs/msteams-docs/pull/2907).

**Comment by Rick-Kirkham** [comment]
I haven't forgotten this. I'm trying to find time to try your suggestion and see if 2907 really did fix it. Please keep it open. Thanks.

**Comment by Mamatha-MSFT** [comment]
Hi @Rick-Kirkham,  We won't close this from our end. Once the [PR](https://github.com/MicrosoftDocs/msteams-docs/pull/2907) gets completed then the document will automatically update and this work item will close.
