### ISSUE TITLE
ngrok step not setup properly

### ISSUE THREAD

**Issue by Rick-Kirkham** [MicrosoftDocs/msteams-docs#3019]
The article tells the user to "In a terminal, run `ngrok http -host-header=rewrite 3978`." 
This generates an error saying that there's no such command as `ngrok`. 
This happens because the earlier article about prerequisites told readers to install ngrok, but did not tell them to add the path to the installed ngrok.exe to the PATH environment variable. You need to either tell the reader to add this to the PATH variable, or you need to tell to navigate to the folder where ngrok is installed and then run the command. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d083976-00c7-86bb-bdca-f909722eae6a
* Version Independent ID: 17fe4c29-7ac0-9091-c7ca-8286e80c0df9
* Content: [Get started - Build a bot - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/build-your-first-app/build-bot)
* Content Source: [msteams-platform/build-your-first-app/build-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/build-your-first-app/build-bot.md)
* Product: **msteams**
* GitHub Login: @heath-hamilton
* Microsoft Alias: **lajanuar**

**Comment by RamaMohanaChary** [comment]
Hi @Rick-Kirkham,

Checking this with internal team and will get back to you soon.

**Comment by RamaMohanaChary** [comment]
Hi @Rick-Kirkham,

Could you please share us the error that you are facing with ngrok. Meanwhile please try this
**ngrok http 3978 --host-header=localhost**

**Comment by Rick-Kirkham** [comment]
The error is in the following screen shot. As you can see in the screen shot, the alternate command you suggested gives the same error. 
![image](https://user-images.githubusercontent.com/9088056/113604131-b4581980-95f9-11eb-8580-2002a40a5f17.png)

As I noted in the original issue, I have already diagnosed the problem and told you what needs to change in the documentaiton.

**Comment by RamaMohanaChary** [comment]
Sure, thank you, will update to the concerned team.

**Comment by v-vrajaraman** [comment]
Fixed as part of [#2907 ](https://github.com/MicrosoftDocs/msteams-docs/pull/2907).

**Comment by Rick-Kirkham** [comment]
@v-vrajaraman Actually 2907 doe **NOT** fix this issue. None of the changes in that PR add the neeced missing step of adding the path to ngrok to the PATH environment variable.
