### ISSUE TITLE
Missing step for installing ngrok

### ISSUE THREAD

**Issue by Rick-Kirkham** [MicrosoftDocs/msteams-docs#3020]
The article says "Install ngrok if you plan to build a bot or messaging extension." 
This is not enough. Later articles tell the reader to run `ngrok` commands in a terminal, but these commands will fail with an error saying that there is no such command as `ngrok` unless the terminal is in the same folder where the ngrok.exe was installed. This will almost never be the case. So, you need an additional step that tells the reader to add the path to the ngrok.exe to the system PATH variable. Have links to how to do this for Windows and Mac. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ddadffa-9c95-9d7a-e609-70c31c3cafcf
* Version Independent ID: db1012ca-9813-e09d-e4dd-93fc807ada06
* Content: [Get started - Build your first app overview and prerequisites - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/build-your-first-app/build-first-app-overview)
* Content Source: [msteams-platform/build-your-first-app/build-first-app-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/build-your-first-app/build-first-app-overview.md)
* Product: **msteams**
* GitHub Login: @heath-hamilton
* Microsoft Alias: **lajanuar**

**Comment by Nikitha-MSFT** [comment]
In step it is asked to install the ngrok and provided the link to install the ngrok. Could you please check [step 1](https://docs.microsoft.com/en-us/microsoftteams/platform/build-your-first-app/build-first-app-overview#install-your-development-tools)?

**Comment by Rick-Kirkham** [comment]
@surbhigupta12  The PR you linked to does not solve this issue. It had nothing to do with the problem I found in the doc. Please reopen this issue.

**Comment by Rick-Kirkham** [comment]
@Mahesh2516 , @Nikitha-MSFT , @KirtiPereira , Will one of you please reopen this issue. The PR cited by @surbhigupta12 does not add the missing step.

**Comment by Wajeed-msft** [comment]
@surbhigupta12 - could you please help here?

**Comment by surbhigupta12** [comment]
HI @Rick-Kirkham,

We've recently revamped the get started module. The content will be merged by next week. Here is the review site and the PR link. This issue should be resolved in this PR:
**PR**: https://github.com/MicrosoftDocs/msteams-docs/pull/2907 
**Review Site**: https://review.docs.microsoft.com/en-us/microsoftteams/platform/build-your-first-app/build-first-app-overview?branch=hello-world 
We're also reaching out to you through Teams.

**Comment by surbhigupta12** [comment]
Issue resolved in PR #2907
