### ISSUE TITLE
Under Azure ADV1 confusing steps

### ISSUE THREAD

**Issue by johnkellyjr** [MicrosoftDocs/msteams-docs#3021]
The steps say this:

Select your bot channel registration link.

On the resource page, select Settings.

Under OAuth Connection Settings near the bottom of the page, select Add Setting.

But there is no "Settings"...there is a "Configuration." Under configuration, there is a Add OAuth Connection Settings. The steps are out of line with what is on the page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63519845-323f-be8f-ce15-d7f39e46b5a7
* Version Independent ID: 70952f91-56e9-ff08-59f6-e237d4aaeca9
* Content: [Add authentication to your Teams bot - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/authentication/add-authentication?tabs=dotnet%2Cdotnet-sample)
* Content Source: [msteams-platform/bots/how-to/authentication/add-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/bots/how-to/authentication/add-authentication.md)
* Product: **msteams**
* GitHub Login: @clearab
* Microsoft Alias: **lajanuar**

**Comment by Jagadeesh-MSFT** [comment]
Hi @johnkellyjr, we are working on it , if it is a bug will inform to doc team to do necessary changes in the documentation.

**Comment by Wajeed-msft** [comment]
Please change point 3 and 4 for [Azure AD V1](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/authentication/add-authentication?tabs=dotnet%2Cdotnet-sample#azure-ad-v1) and [Azure AD V2](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/authentication/add-authentication?tabs=dotnet%2Cdotnet-sample#azure-ad-v2)


3. On the resource page, select Configuration.

4. Select 'Add OAuth Connection Settings' near the bottom of the page
![image](https://user-images.githubusercontent.com/31851992/116651901-d1d29600-a9a1-11eb-9af1-33c593c799dc.png)
