### ISSUE TITLE
[Doc Bug] Portal with self signed certificate is not supported in MS teams tab 

### ISSUE THREAD

**Issue by SwathiPatti** [MicrosoftDocs/msteams-docs#3035]
It seems portal with self signed certificate is not supported in MS teams tab, please add it under the tab requirements.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b159fe6e-33d0-6174-f3c3-68aaec79ee1b
* Version Independent ID: 7037e9c7-f501-5b70-8acf-1f004a06289b
* Content: [Understanding tab requirements - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/tab-requirements)
* Content Source: [msteams-platform/tabs/how-to/tab-requirements.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tabs/how-to/tab-requirements.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by RamaMohanaChary** [comment]
Hi @SwathiPatti,

Could you please share us what exactly you are trying to implement in Tab, and also share us the document that you are referring while implementing.

**Comment by SwathiPatti** [comment]
Customer has an intranet portal, which has a self-signed certificate. They are trying to add this intranet webpage as a tab to MS teams. It seems currently teams does not support the ability to load intranet websites using their own self-signed certificates. So created this request to document this in tab requirements

**Comment by Mamatha-MSFT** [comment]
Hi@SwathiPatti, Thanks for bringing up this issue, Taking this for internal discussion with team and will let you know.

**Comment by Jagadeesh-MSFT** [comment]
Hi @SwathiPatti, Just want to know are you using iframe for rendering the webpage in tab?

**Comment by SwathiPatti** [comment]
Customer is rendering the intranet site as a tab in the personal app in MS teams. So It must treat as iFrame.

**Comment by Jagadeesh-MSFT** [comment]
Hi @SwathiPatti , could you please share the error details with us.

**Comment by SwathiPatti** [comment]
Issue is intranet site when added as a tab in the personal app of MS teams, tab is not loading in the desktop and mobile clients.
Error in Teams: This site won't load in our desktop app.
