### ISSUE TITLE
Unable to get the current login user in MS Teams Message extensions

### ISSUE THREAD

**Issue by Rajapalgiri** [MicrosoftDocs/msteams-docs#3041]
Hi Team, 

I have implemented the Teams Message Extension Search. I have a requirement where I need to display the data based on the current login user. All the time the logged-in user is getting as NULL. I have tried with both the option **'CliamsPrinicple'** and **'HttpContext'**. 'HttpContext' works fine in the controller but having an issue with the Message extension Activity Handler.

 The Teams Message extension is working on SSO authentication. The teams' message extension is working fine and I was able to get the results, only the issue is with the login user, cannot display the data based on the login user. 

ActivityHander.cs file

    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading;
    using System.Threading.Tasks;
    using AdaptiveCards;
    using Microsoft.AspNetCore.Http;

public class AuthorTeamsActivityHandler : TeamsActivityHandler
    {
         private readonly IHttpContextAccessor httpContextAccessor;
         private readonly string loggedinuser;

      public AuthorTeamsActivityHandler(
            
            IConfiguration configuration,
            IHttpContextAccessor httpContextAccessor,
            IUsersService usersService,
            IStringLocalizer<Strings> localizer)
        {
            this.configuration = configuration;
            this.usersService = usersService;
            this.httpContextAccessor = httpContextAccessor;
        }
       protected override async Task<MessagingExtensionResponse> OnTeamsMessagingExtensionQueryAsync(ITurnContext<IInvokeActivity> turnContext, MessagingExtensionQuery query, CancellationToken cancellationToken)
        {
            turnContext = turnContext ?? throw new ArgumentNullException(nameof(turnContext));
            var text = query?.Parameters?[0]?.Value as string ?? string.Empty;         
            var activity = turnContext.Activity;
            **this.loggedinuser = this.httpContextAccessor.HttpContext.User?.Identity?.Name;**
             
     }
}
`Startup.cs file

  public void ConfigureServices(IServiceCollection services)
        {
           //services.AddSingleton<IHttpContextAccessor, HttpContextAccessor>();
            **services.AddHttpContextAccessor();**
       }`

GitHub Message extension search : https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/50.teams-messaging-extensions-search

**Comment by Nikitha-MSFT** [comment]
You will receive the logged in user details under turncontext.activity.from -  Could you please try checking the data under turncontext.activity.from

**Comment by Rajapalgiri** [comment]
> You will receive the logged in user details under turncontext.activity.from - Could you please try checking the data under turncontext.activity.from

Thanks for the reply, I have already tried that. But It shows the display name of the user. I am looking current user email address.
var userName = turnContext.Activity.From.Name;

**Comment by Nikitha-MSFT** [comment]
You will receive the AAD ID in turncontext.activity.from by using that id you can get the user mail id using graph API. Could you please check this [docs ](https://docs.microsoft.com/en-us/graph/api/user-get?view=graph-rest-1.0&tabs=http).

**Comment by Rajapalgiri** [comment]
> You will receive the AAD ID in turncontext.activity.from by using that id you can get the user mail id using graph API. Could you please check this [docs ](https://docs.microsoft.com/en-us/graph/api/user-get?view=graph-rest-1.0&tabs=http).

Thanks for the reply Nikitha. I have also tried the above option as well. The accessToken is getting empty. Api permissions is alredy configured at Azure APP registrations (User.Read). I want to make sure, whether I can use the SSO authentication in messageextensionsearch or not. As I have seen OAuth connection is taken in one of the examples. 
https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/52.teams-messaging-extensions-search-auth-config
 
Please find the below code which I have tried. 

AuthorTeamActivityHandler.cs
 protected override async Task<MessagingExtensionResponse> OnTeamsMessagingExtensionQueryAsync(ITurnContext<IInvokeActivity> turnContext, MessagingExtensionQuery query, CancellationToken cancellationToken)
        {
            turnContext = turnContext ?? throw new ArgumentNullException(nameof(turnContext));
            var text = query?.Parameters?[0]?.Value as string ?? string.Empty;            
            var activity = turnContext.Activity;
            var userAAdObject = turnContext.Activity.From.AadObjectId;`
            var loginuser = await this.usersService.GetUserAsync(userAAdObject);
}
`
UserServcie.cs
`
namespace Microsoft.Teams.Apps.AuthorApp.Common.Services.MicrosoftGraph
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Net.Http;
    using System.Text;
    using System.Threading.Tasks;
    using Microsoft.Graph;
    using Newtonsoft.Json.Linq;

    /// <summary>
    /// Users service.
    /// </summary>
    internal class UsersService : IUsersService
    {
        private const string TeamsLicenseId = "";

        private readonly IGraphServiceClient graphServiceClient;

        
        internal UsersService(IGraphServiceClient graphServiceClient)
        {
            this.graphServiceClient = graphServiceClient ?? throw new ArgumentNullException(nameof(graphServiceClient));
        }

        
        /// <inheritdoc/>
        public async Task<User> GetUserAsync(string userId)
        {
            var graphResult = await this.graphServiceClient
                    .Users[userId]
                    .Request()
                    .Select(user => new
                    {
                        user.Id,
                        user.DisplayName,
                        user.UserPrincipalName,
                    })
                    .WithMaxRetry(GraphConstants.MaxRetry)
                    .GetAsync();
            var userEmail = graphResult.Mail;
            return graphResult;
        }       
}`

GraphTokenProvider.cs
`
namespace Microsoft.Teams.Apps.AuthorApp.Authentication
{
    using System;
    using System.Linq;
    using System.Net.Http;
    using System.Net.Http.Headers;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Http;
    using Microsoft.Graph;
    using Microsoft.Identity.Web;
    using Microsoft.Teams.Apps.AuthorApp.Common.Services.MicrosoftGraph;
 
    public class GraphTokenProvider : IAuthenticationProvider
    {
        private readonly ITokenAcquisition tokenAcquisition;

        
        public GraphTokenProvider(ITokenAcquisition tokenAcquisition)
        {
            this.tokenAcquisition = tokenAcquisition ?? throw new ArgumentNullException(nameof(tokenAcquisition));
        }

        public async Task AuthenticateRequestAsync(HttpRequestMessage request)
        {
            var permissionType = this.ExtractPermissionType(request.Headers);
            string accessToken = await this.GetAccessToken(permissionType);
            request.Headers.Remove(Common.Constants.PermissionTypeKey);

            // Append the access token to the request.
            request.Headers.Authorization = new AuthenticationHeaderValue(
                Common.Constants.BearerAuthorizationScheme, accessToken);
        }

        
        private string ExtractPermissionType(HttpRequestHeaders headers)
        {
            if (headers != null && headers.Contains(Common.Constants.PermissionTypeKey))
            {
                var permissionType = headers.GetValues(Common.Constants.PermissionTypeKey).FirstOrDefault();
                return permissionType;
            }

            return string.Empty;
        }
    }
}
` 

Thanks & regards,
Raja

**Comment by Rajapalgiri** [comment]
Hello @Wajeed-msft, Abhijit-MSFT, Nikitha-MSFT, 

Please update me if you have any solution. 

Thanks!

**Comment by Nikitha-MSFT** [comment]
You will not receive the user mail in teams activity handler. You will receive AadObjectId,id,name.properties, role. To get the user email details you need to implement code. Could Here is the [sample code](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/bots/bots-context#nodejs-example) to get email id from the Teams. Please try and let me know if this works for you?

**Comment by Nikitha-MSFT** [comment]
@Rajapalgiri - Are you still facing the issue? if yes please feel free to reopen the issue. Closing the issue as of now.
