### ISSUE TITLE
One endpoint per Bot ?

### ISSUE THREAD

**Issue by yusefu** [MicrosoftDocs/msteams-docs#305]
I created 2 bots pointing to the same ` Messaging endpoint `. 

1. I got the expected response for the first Bot
2. For the second I got the error below:

```
{"error":{"code":"ServiceError","message":"not member of thread"}}
```

Can we  create multiple  Bots pointing to one single endpoint through dev.botframework.com/bots/
Or is in it MS teams specifications that we can configure 1 Endpoint / 1 Bot ?

Any help would be very much appreciated.

**Comment by Wajeed-msft** [comment]
Bot endpoint is authenticated using MicrosoftAppId and MicrosoftAppPassword. For debugging you can change AppId & Password values in code/config to work with multiple bot.

Could you please elaborate on your scenario and why you want to keep single endpoint for multiple bots?

**Comment by yusefu** [comment]
Thank you for your response, @Wajeed-msft 

Do you mean this:
```ruby
bot1 => MicrosoftAppId : AppId1,  MicrosoftAppPassword: password1,
Messaging endpoint: chat_bot_url

bot2 => MicrosoftAppId : AppId2,  MicrosoftAppPassword: password2,
Messaging endpoint: chat_bot_url
```
> bot1,  bot2 were both created with botframework

response would succeed in both case.




The endpoint in this scenario is used for chat-bots, I needed to test whether multiple Ms teams bots could communicate with the same chat-bot.

**Comment by yusefu** [comment]
Thank you for replying! Appreciate it.
