### ISSUE TITLE
Fix JSON formatting for "defaultGroupCapability"

### ISSUE THREAD

**Issue by heath-hamilton** [MicrosoftDocs/msteams-docs#3067]
In the manifest sample, we should format the JSON for "defaultGroupCapability" correctly (see below):

```
  "defaultGroupCapability": {
    "meetings": "tab", 
    "team": "bot",
    "groupchat": "bot"
  }
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f94a488-d636-92b3-21eb-c88744c8f272
* Version Independent ID: 7b3413f4-9ade-accf-5cb2-83fead11a32a
* Content: [Manifest schema reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema)
* Content Source: [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/resources/schema/manifest-schema.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by KirtiPereira** [comment]
Updated and closed the issue.
