### ISSUE TITLE
ไมโคซอร์ฟ เลินนิ่ง แมทชีน

### ISSUE THREAD

**Issue by Techasit232000** [MicrosoftDocs/msteams-docs#3068]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d083976-00c7-86bb-bdca-f909722eae6a
* Version Independent ID: 17fe4c29-7ac0-9091-c7ca-8286e80c0df9
* Content: [Get started - Build a bot - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/build-your-first-app/build-bot)
* Content Source: [msteams-platform/build-your-first-app/build-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/build-your-first-app/build-bot.md)
* Product: **msteams**
* GitHub Login: @heath-hamilton
* Microsoft Alias: **lajanuar**

**Comment by Nikitha-MSFT** [comment]
Are you facing any issue? if yes could you please share more details of the issue?

**Comment by Techasit232000** [comment]
I remember my Hotmail and I want to back. My Hotmail is ***@***.***” this is my issue. 


ส่งจาก Yahoo Mail สำหรับ iPhone


ในวันที่ วันพฤหัสบดี, เมษายน 8, 2564, 3:55 PM Nikitha-MSFT ***@***.***> เขียนว่า:




Are you facing any issue? if yes could you please share more details of the issue?

**Comment by Nikitha-MSFT** [comment]
Are you facing issue with teams?

**Comment by Techasit232000** [comment]
I have no team. And I want only Thai team. Communicate in Thai language. 


ส่งจาก Yahoo Mail สำหรับ iPhone


ในวันที่ วันพฤหัสบดี, เมษายน 8, 2564, 7:21 PM Nikitha-MSFT ***@***.***> เขียนว่า:




Are you facing issue with teams?

**Comment by surbhigupta12** [comment]
Assigning to @v-shalinirobinson

**Comment by v-shalinirobinson** [comment]
The issue is wrongly raised.
