### ISSUE TITLE
What's different between userObjectId & aadObjectId?

### ISSUE THREAD

**Issue by jeffwu85182** [MicrosoftDocs/msteams-docs#3070]
The idea is that we want to provide a good experience for message extension, bot, and tab. We can get the context that includes the property `aadObjectId` from the message extension. But tab not, the context of the tab only gets the `userObjectId`.

I am not sure if we can see `aadObjectId` and `userObjectId` as the same, then we can use it as an identity detection?

Thanks.

**Comment by Nikitha-MSFT** [comment]
userObjectId = The Azure AD object ID of the current user, in the current tenant, aadObjectId = This account's object ID within Azure Active Directory. you can use it as an identity detection

**Comment by jeffwu85182** [comment]
Thanks for the clarity.
