### ISSUE TITLE
Not able to send Code Snipped in chat window during individual or group call 

### ISSUE THREAD

**Issue by mpietrusa** [MicrosoftDocs/msteams-docs#3086]
**Teams Version** 1.4.00.4167 (32-bit)

Chat during a call
![image](https://user-images.githubusercontent.com/14968464/114162098-0fa34800-9929-11eb-8b47-e822199042a8.png)
![image](https://user-images.githubusercontent.com/14968464/114162116-15992900-9929-11eb-8b59-1c12cb448b3c.png)

Chat without call
![image](https://user-images.githubusercontent.com/14968464/114162021-fac6b480-9928-11eb-86e0-bb16f8348e2c.png)

**Comment by Sridevi-MSFT** [comment]
Thanks for reaching out to us. We are the developer support team for Microsoft teams focused on helping developers resolve their code issues. For issues related to teams product, please reach out to the [Product support channels](https://docs.microsoft.com/en-us/microsoftteams/platform/feedback#product-support-channels) for Microsoft Teams.
