### ISSUE TITLE
Remove scopes from messaging extension schema

### ISSUE THREAD

**Issue by billbliss** [MicrosoftDocs/msteams-docs#309]
Missed this one - should delete it.

https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/messaging-extensions#declare-your-messaging-extension

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eeb9dcd0-fc2e-95a0-5238-fb67b6a27ba7
* Version Independent ID: 3adf9985-9a34-fbb4-161a-23beb753dd70
* Content: [Develop messaging extensions - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/messaging-extensions)
* Content Source: [msteams-platform/concepts/messaging-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/messaging-extensions.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by NormSohl** [comment]
Done, live.
