### ISSUE TITLE
"Build and run your first Microsoft Teams app" appears to be out of date (pictures don't match current flow)

### ISSUE THREAD

**Issue by andy-rsa** [MicrosoftDocs/msteams-docs#3094]
RE: https://docs.microsoft.com/en-us/microsoftteams/platform/build-your-first-app/build-and-run

The images shown in the online document are not what's seen in VS Code when starting a new project. 
![image](https://user-images.githubusercontent.com/78745601/114339804-ecd08980-9b0a-11eb-8a74-b6eeea2761f1.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f876156-cc1e-468f-4647-5143a5de03b1
* Version Independent ID: 618f43a3-3371-ad99-13aa-087b9303298c
* Content: [Get started - Build and run your first app - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/build-your-first-app/build-and-run)
* Content Source: [msteams-platform/build-your-first-app/build-and-run.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/build-your-first-app/build-and-run.md)
* Product: **msteams**
* GitHub Login: @heath-hamilton
* Microsoft Alias: **lajanuar**

**Comment by Jagadeesh-MSFT** [comment]
Hi @andy-rsa, Thank you for the insights on the document. We will ask document team to look into this and the necessary changes are done.

**Comment by v-vrajaraman** [comment]
Fixed as part of [#2907 ](https://github.com/MicrosoftDocs/msteams-docs/pull/2907)

**Comment by Jagadeesh-MSFT** [comment]
Hi @andy-rsa, This issue got fixed  as part of #[2907](https://github.com/MicrosoftDocs/msteams-docs/pull/2907).
