### ISSUE TITLE
Avoid 'azurewebsites.net' domain restriction.

### ISSUE THREAD

**Issue by marwalsch** [MicrosoftDocs/msteams-docs#3098]
Using ngrok for test scenarios is no suitable solution if one is lacking a premium subscription, and free alternatives with custom domains are practically always unreliable. However, using Azure subscriptions is also not possible as "Applications that use the `azurewebsites.net` domain are not supported as it is too common and can be a security risk"., according to the docs. The only possible alternative is purchasing a custom domain and mapping it which is just as untenable as switching the custom domain on each deploy. 
What is the recommended solution here? Are there ways to bypass the Azure domain exception or plans to remove this restriction?

**Comment by marwalsch** [comment]
It appears that this restriction is no longer applicable. The corresponding hint in the documentation should probably be removed.

**Comment by Mamatha-MSFT** [comment]
Hi @marwalsch, Can you please provide the documentation that you are referring to.

**Comment by marwalsch** [comment]
@Mamatha-MSFT Of course. [It's the last bullet point inside the not at the beginning of section 1](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-aad-sso): "Applications that use the azurewebsites.net domain are not supported as it is too common and can be a security risk.".
I vaguely recall an additional hint stating the restriction is to be removed. Is it?

**Comment by Mamatha-MSFT** [comment]
Hi @marwalsch,  **Applications that use the azurewebsites.net domain are not supported as it is too common and can be a security risk**. has been removed from documentation.

**Comment by marwalsch** [comment]
Thanks
