### ISSUE TITLE
Get Started with the Getting Started Sample App - Tech Community

### ISSUE THREAD

**Issue by jothomp** [MicrosoftDocs/msteams-docs#31]
Hi, I found what looked like a really useful article on the TechCommunity to follow in how to configure and demo all the components of an app within Teams but unfortunately the code and web services are no longer available. https://techcommunity.microsoft.com/t5/Microsoft-Teams-Blog/Get-Started-with-the-Getting-Started-Sample-App/bc-p/139772 

I can see real value in this article but it needs updating and web services/sample code providing that works. If there is another article you would advise intead then fine, but otherwise I'd be happy to contribute getting this back up to speed.

**Comment by billbliss** [comment]
I assume you found our up to date sample? This one is very out of date. I'll see if we can edit the article to reflect this.
