### ISSUE TITLE
MsTeams little bug

### ISSUE THREAD

**Issue by ozw1z5rd** [MicrosoftDocs/msteams-docs#3100]
I found that this website is the correct place where to report bugs. The post I read it's from 2018. 

There is a bug in the MsTeams macOS version 
I’m using the macOS 11.2.3 and Teams 1.4.00.7175
How to reproduce:

Start the Apple Music Player
Pause the music (  just pause it, no matter how do you do it ) 
Start a meeting
End the meeting
Unpause the music ( PLEASE PRESS THE F8 KEY on the keyboard ) 
The Teams’ calling note will play. That’s a  bug. Do you agree? 
Anything works if the music is unpaused clicking the pause button into the music player.

**Comment by Jagadeesh-MSFT** [comment]
Hi @ozw1z5rd, I'm unable to reproduce this issue from my end , could you please test it again .

**Comment by ozw1z5rd** [comment]
Are you using the same versions shown in the original request?

**Comment by Jagadeesh-MSFT** [comment]
Hi @ozw1z5rd , yes we have tested with the same versions which you have provided with us.
