### ISSUE TITLE
Enabling Forms in a Meeting

### ISSUE THREAD

**Issue by kweinham** [MicrosoftDocs/msteams-docs#3110]
The second image on this page (heading "Pre-meeting tab:") shows a meeting with a Form containing three long answer questions for a retrospective: what went well, what didnt go well, and what did you learn. I do not see a way to add this kind of form to a meeting. I can only add simple polls to a meeting.  How is this capability accessed? Thanks so much for your help!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82987815-d508-d642-c1f6-b609241d4750
* Version Independent ID: 29e89cc6-c8ca-7d29-7dca-4ac4d06f5c42
* Content: [Apps in Teams meetings - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/teams-apps-in-meetings)
* Content Source: [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by v-ypalikila** [comment]
Hi,

The steps in the [article](https://docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/meeting-app-extensibility?tabs=desktop#pre-meeting-app-experience) to allow users to add tabs to existing meeting are working correctly.

**Comment by surbhigupta12** [comment]
Closing this issue.
