### ISSUE TITLE
NameSpace issues with apps running into branding guidelines

### ISSUE THREAD

**Issue by KirtiPereira** [MicrosoftDocs/msteams-docs#3112]
We need to do better to help partners in choosing "legal" names for their app.  
Our own guidelines are confusing as to whether it is okay to use "Teams" in the app name. The example does as you can see below, but then lower down we call it out as a "Don't". The App Name Guides link doesn't go anywhere - its a reference to itself. The example we provide contradicts the usage guideline around Teams and Microsoft - is this an exception to #1?

We have partners that are following this, getting confused, putting marketing materials together with the wrong usage.
![image](https://user-images.githubusercontent.com/70375155/114656179-3ab3e000-9d0b-11eb-9137-bb1828bfeaeb.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22ac9894-41a6-543e-c6c9-8af314bb81c8
* Version Independent ID: 44ac7805-a6fa-a717-df85-1a7677630486
* Content: [Build a great app details page - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/detail-page-checklist)
* Content Source: [msteams-platform/concepts/deploy-and-publish/appsource/prepare/detail-page-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/deploy-and-publish/appsource/prepare/detail-page-checklist.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by ramendhe** [comment]
Current documentation to be soon replaced by new docs (ETA: 25th April). Issue incorporated in new set of documentation:
![image](https://user-images.githubusercontent.com/78354231/115292801-12493d00-a174-11eb-8dd0-66d6a963fbe5.png)
