### ISSUE TITLE
mediaDevices.getUserMedia returns "DOMException: Permission denied" when it is called in the pop-out-app window

### ISSUE THREAD

**Issue by kafka-yu** [MicrosoftDocs/msteams-docs#3122]
Hi there,

Not sure if this is the correct repo to ask. But I still want to have a try.

Does anyone know why the below code won't return the MediaSteam in an MS Teams pop-out-app window in desktop client of the MS Teams app?
```js
await window.navigator.mediaDevices.getUserMedia({audio: true, video:false})
```
It returns "DOMException: Permission denied".

It works in the default app window.

```js
MediaStream {id: "vDPnWRVz0V4kVgwWOMITbBPeN3KXgN9pviDg", active: true, onaddtrack: null, onremovetrack: null, onactive: null, …}
```

Is it caused by the "audio" permission is not granted to the pop-out window?

NOTE:
I've enabled the device permissions in my app's manifest, and also the MS Teams app itself.

Thank you!

Reference:
- https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?tabs=desktop#use-teams-apis-to-get-device-permissions

I posted this issue in the MS Teams JS SDK repo, it is told this is an MS Teams product issue, so I asked here again.
https://github.com/OfficeDev/microsoft-teams-library-js/issues/524

Would anyone help look? Thank you!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19804dba-009f-2eb1-cc7f-1e0fabbebb6b
* Version Independent ID: a9373e78-b3c9-7182-d253-5ac8d8988936
* Content: [Request device permissions for your Microsoft Teams app - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?tabs=desktop#use-teams-apis-to-get-device-permissions)
* Content Source: [msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/device-capabilities/native-device-permissions.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by kafka-yu** [comment]
@Wajeed-msft @Nikitha-MSFT Hello, would you pls help check? Thank you!

**Comment by v-chetsh** [comment]
@kafka-yu - Could you please confirm if your issue has resolved or still looking for any help?
