### ISSUE TITLE
Teams App Business Model lacking

### ISSUE THREAD

**Issue by extcon** [MicrosoftDocs/msteams-docs#313]
There is no information on the business model of Teams Apps. How do developers get paid? Is it though AppSource?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0f1115e-693c-25f8-e0e7-103fb63753c2
* Version Independent ID: 9726dee6-7fd2-1c98-7c2b-dfcb858e540e
* Content: [Apps for Microsoft Teams - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/apps/apps-overview)
* Content Source: [msteams-platform/concepts/apps/apps-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/apps/apps-overview.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by billbliss** [comment]
There isn't any information because it varies greatly. Developers are not paid via AppSource except inasmuch as it functions as a lead generation system (which is what it is). Generally speaking the apps are either free or require a subscription/account in a separate service that itself is freemium or paid.

**Comment by extcon** [comment]
Wow Thanks Bill, that was a really quick response👍🏻
It makes it somewhat clearer to someone like me who is a newbie in the ISV realm.
These follow up questions might or might not be appropriate for this thread. If not can you point me in the right direction?
Is publishing a Teams App to AppSource the correct way to bring a Teams App to market? Are Teams Apps surfaced in the Teams client when browsing for apps automatically or does it require a Teams App tagging in AppSource?
So the backend service that the Teams App connects to will have to have the commercia/subscription model itself, including billing capabilities? Are there any offerings from Microsoft or 3rd party that provide this capability?
And there is no fee to publish a Teams App in AppSource? Can customers buy the Teams App/Service through AppSource? (Your remark of it being nothing more than a leads generation system would contradict that but I thought it worked similarly to Apple's App Store...)

Hämta Outlook för iOS<https://aka.ms/o0ukef>

________________________________
Från: Bill Bliss <notifications@github.com>
Skickat: onsdag, november 7, 2018 12:18 fm
Till: MicrosoftDocs/msteams-docs
Kopia: extcon; Author
Ämne: Re: [MicrosoftDocs/msteams-docs] Teams App Business Model lacking (#313)


There isn't any information because it varies greatly. Developers are not paid via AppSource except inasmuch as it functions as a lead generation system (which is what it is). Generally speaking the apps are either free or require a subscription/account in a separate service that itself is freemium or paid.

**Comment by clearab** [comment]
Hi,
Is publishing a Teams App to AppSource the correct way to bring a Teams App to market?
Yes.

Are Teams Apps surfaced in the Teams client when browsing for apps automatically or does it require a Teams App tagging in AppSource?
Once you go through the approval process your app will be available in Teams.

So the backend service that the Teams App connects to will have to have the commercia/subscription model itself, including billing capabilities? Are there any offerings from Microsoft or 3rd party that provide this capability?
Yes, you would be responsible for any subscription model that you wished to employ.

And there is no fee to publish a Teams App in AppSource?
No, no fee.

Can customers buy the Teams App/Service through AppSource?
No, customers can install the app via AppSource, but any subscription model you wish to employ is your responsibility.

I would suggest getting started by registering for a Office Developer account [here](https://developer.microsoft.com/en-us/office/go-to-market).
