### ISSUE TITLE
Registering your app in the team failed with the error "Permission required..."

### ISSUE THREAD

**Issue by v-caxian** [MicrosoftDocs/msteams-docs#3132]
I think the document should mention that, we need to [enable side loading](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/prepare-your-o365-tenant#enable-custom-teams-apps-and-turn-on-custom-app-uploading) before [register-your-app-in-teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tutorials/get-started-dotnet-app-studio#register-your-app-in-teams), because this setting is disabled by default in a [developer tenant](https://docs.microsoft.com/en-us/microsoftteams/platform/tutorials/get-started-dotnet-app-studio#prepare-your-development-environment), and it will cause an error when installing the app.

<img width="835" alt="TeamsRegisterError" src="https://user-images.githubusercontent.com/29229802/115200226-8fe65c00-a126-11eb-87a1-aaca5bc2b290.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f98c73d-bb68-3088-6e7d-2c576a8292f6
* Version Independent ID: 08b9df7d-4997-c681-e73a-235ec1e4fc7b
* Content: [Tutorial - Create your first app using C# - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tutorials/get-started-dotnet-app-studio#prepare-your-development-environment)
* Content Source: [msteams-platform/tutorials/get-started-dotnet-app-studio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tutorials/get-started-dotnet-app-studio.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by v-ypalikila** [comment]
Hi,

The article was updated as a Step-by-step guide and also includes the option to enable sideloading. Please refer this [link](https://docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-csharp?tutorial-step=1#prepare-your-development-environment).

**Comment by v-ypalikila** [comment]
Hi,

The steps to enable sideloading is available in the [article](https://docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-csharp?tutorial-step=1#prepare-your-development-environment).
