### ISSUE TITLE
Bad Link 

### ISSUE THREAD

**Issue by blopez-co-slo-ca-us** [MicrosoftDocs/msteams-docs#314]
Got to this "Not found" page from https://docs.microsoft.com/en-us/microsoftteams/known-issues.  The "known workaround" link.  What a kick in the balls! 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cbdb8216-60c7-a0a1-7eb6-02d42d783292
* Version Independent ID: 77a75dd2-6f45-bc76-b968-0cf58c427ef5
* Content: [Requested page cannot be found. - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/connectors)
* Content Source: [msteams-platform/404.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/404.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by billbliss** [comment]
I left a comment on the page that was linked FROM, which is where the error is, so I'm going to close this. But based on reading that row, here's what I wrote on that comment, perhaps this will help:
>This is probably what it should link to: https://docs.microsoft.com/en-us/MicrosoftTeams/enable-features-office-365#apps based on the text above it, but given the rest of the text in that row, perhaps it really should link to something like https://answers.microsoft.com/en-us/msoffice/forum/msoffice_o365admin-mso_teams-mso_o365b/how-to-enable-or-disable-connectors-in-office-365/33d4b2c1-00eb-420a-ad83-01a2b42ad098. Not sure which.
