### ISSUE TITLE
Deeplink for guests is not working

### ISSUE THREAD

**Issue by SantiCuinas** [MicrosoftDocs/msteams-docs#3140]
When opening a deeplink to a chat with a guest user, teams cannot start the conversation properly.

![image](https://user-images.githubusercontent.com/25989581/115403214-97f3d980-a1c2-11eb-8105-fa15583cd58d.png)

Deeplink example: https://teams.microsoft.com/l/chat/0/0?users=name_externaldomain.com#EXT#@domain.onmicrosoft.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45541337-ecd7-5cf6-cbe4-3f0d2f39aa79
* Version Independent ID: 6b4203f0-2844-06c9-eaa3-9cc03e6f76c0
* Content: [Create deep links to content - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links)
* Content Source: [msteams-platform/concepts/build-and-test/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/build-and-test/deep-links.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by v-chetsh** [comment]
@SantiCuinas - Could you please confirm if your issue has resolved or still looking for any help?
