### ISSUE TITLE
AAD B2C Option?

### ISSUE THREAD

**Issue by hypertrends** [MicrosoftDocs/msteams-docs#3143]
Hello,
As a general request from developers and executives all over, can we PLEASE clearly specify here that this flow is explicitly for AAD is not available for AAD B2C. We understand the poor naming choices on these products but we have run into enough pain because of this for numerous different products where we use AAD B2C and developers end up spending hours only to find out that this is not for AAD B2C. 

Also, can we also please see if we can offer a detailed write-up on how to integrate with AAD B2C? 

Thank you again.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b1dcd0d-471b-2d33-54b5-39a93dfba2a8
* Version Independent ID: 5bd44149-777e-b449-bd2e-f20b9bd04038
* Content: [Authentication for tabs using Azure Active Directory - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-tab-aad)
* Content Source: [msteams-platform/tabs/how-to/authentication/auth-tab-aad.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tabs/how-to/authentication/auth-tab-aad.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by v-chetsh** [comment]
@hypertrends - Could you please confirm if your issue has resolved or still looking for any help?
