### ISSUE TITLE
New Webhook not working sometimes

### ISSUE THREAD

**Issue by gr8jkarthik** [MicrosoftDocs/msteams-docs#3145]
Hi,

I recently updated my connector to new webhook(as there was a security improvement from Microsoft). The web hook is not working properly and often my service errors out for below reason,

org.springframework.web.client.ResourceAccessException: I/O error on POST request for "https://[hostname]/webhookb2/[id]]@[id]/IncomingWebhook/[id]": Connection timed out (Read failed); nested exception is javax.net.ssl.SSLException: Connection timed out (Read failed) 

The same URL/webhook works perfectly when posting using CURL but when use that in a micro service to post I get that error. 

Anybody experienced this before or any idea as why it is happening? 

Thank you!

**Comment by v-chetsh** [comment]
@gr8jkarthik - Could you please confirm if your issue has resolved or still looking for any help?
