### ISSUE TITLE
App Studio 1.6.1 breaks with an "activities" section included

### ISSUE THREAD

**Issue by plamber** [MicrosoftDocs/msteams-docs#3148]
Hello,
I was trying to follow the instructions for sending teams notifications to users with a custom app in Teams [blog](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/teams-send-activityfeednotifications.md#:~:text=Send%20activity%20feed%20notifications%20to%20users%20in%20Microsoft,Graph%20to%20extend%20this%20functionality%20to%20your%20apps.). 

During the process you are required to add an "activities" section in the manifest. Once you do this, App Studio breaks when opening that specific app.

When clicking on the app you might get into the app details. On the other hand, you get a blank screen when you try to perform any activity such as clicking on different tabs.

![image](https://user-images.githubusercontent.com/18241305/115514348-4ad83c00-a284-11eb-81c0-c253da489ffa.png)

What is the proper way of reporting this issue?

Thank you for your feedback,
Patrick

**Comment by v-chetsh** [comment]
@plamber - Could you please confirm if your issue has resolved or still looking for any help?

**Comment by plamber** [comment]
Hi,
Considering that the app is deprecated from next week onwards I am no more looking for a fix.

I am using the new teams developer portal now.

Thank you

**Comment by Meghana-MSFT** [comment]
@plamber - We are closing this issue, please feel free to reach out to us if you have any issues. Thank you.
