### ISSUE TITLE
Unable to interact with bot in MS Team

### ISSUE THREAD

**Issue by jasonchuah4** [MicrosoftDocs/msteams-docs#315]
I've followed every single instruction in this guide. I can interact with my remotely hosted (using ngrok) bot through Bot Emulator but couldn't interact through Teams. Even the rich card extension also not working. Is the code sample provided here is outdated?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ea2882a-b341-b29d-e2b3-b51ea47c8643
* Version Independent ID: d4807393-f610-5df6-37cf-d9975e63371c
* Content: [Get started with C#/.NET - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/get-started/get-started-dotnet#HostSample)
* Content Source: [msteams-platform/get-started/get-started-dotnet.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/get-started/get-started-dotnet.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by billbliss** [comment]
Have you successfully loaded your app package? https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/apps/apps-upload

**Comment by dni128** [comment]
I've got the same problem, as described above.  I have definetly uploaded the app package (the *.zip file, containing the mainfest.json and the Icons) and can access it in Teams client, the Tab is working and showing the Messages, it is also configurable. I can test the Bot using the Bot Emulator, works fine, but it is not working in Teams as expected.  Question: i had to set the Option "Use version 1.0 authentication tokens" in the Emulator Settings in order to get a response (the echo) - does this need to be set in the Teams Client somewhere also?  I am new to this TeamsAPI and just want the Bot to echo my input, but it does not - the message extension does not do anything neither ;-(  ... Thank you for your help!!!

**Comment by billbliss** [comment]
Assuming these are C# bots, what version of the BotBuilder NuGet are you using?

**Comment by dni128** [comment]
Hey Bill, thank you for the answer - i am using the "Microsoft.Teams.Samples.HelloWorld.Web". The EchoBot, beeing part of the Sample is C#, that is true.  Why would i have to use the BotBuilder then? Sorry, but i dont understand.  I had figured, that the Sample would work as decribed above, so i could maybe understand more of the topic.  Acutally i am trying to get a file (in pdf format) from a message-server into a channel in Teams.  For this reason i am trying to understand the concepts of TeamsAPI.  If you have any suggestions for me to read something else, please feel free to share them with me ;) have a nice day!

**Comment by Wajeed-msft** [comment]
@dni128 - [Bot Builder](https://github.com/Microsoft/BotBuilder) is comprised of SDK and tools that enable you to build bots.  "Microsoft.Teams.Samples.HelloWorld.Web" sample uses 3.5.9.0 which you can see in [packages.config](https://github.com/OfficeDev/msteams-samples-hello-world-csharp/blob/7508bc28e1745b5286c3d15c8339e310ae9a8646/Microsoft.Teams.Samples.HelloWorld.Web/packages.config#L15) file. 

Just to be sure, few questions here:
1. Did you add Microsoft Teams as a channel from the featured channels list after creating your bot?
![image](https://user-images.githubusercontent.com/31851992/48195307-469a5b80-e375-11e8-8301-4d7144f400bc.png)

2. Did you test your bot in Web Chat from Bot Framework?
![image](https://user-images.githubusercontent.com/31851992/48195127-c70c8c80-e374-11e8-8c16-daed2fb07240.png)

**Comment by dni128** [comment]
1. yes - did add the Microsoft Teams Channel.
2. yes - but the Test returned a "couldn't send retry"

Thank you for your time, Bill - i gave up on the topic, since it doesnt actually help my problem.  I am so little of a developer, itz a shame and because of that, i dont want to get to your nerves anymore! cheers anyway, wishing you success and luck for the future  ;)

**Comment by Wajeed-msft** [comment]
@dni128 - Can you confirm that your endpoint is up and you have set correct App Id & App Password in [Web.config](https://github.com/OfficeDev/msteams-samples-hello-world-csharp/blob/7508bc28e1745b5286c3d15c8339e310ae9a8646/Microsoft.Teams.Samples.HelloWorld.Web/Web.config#L12) file?

**Comment by dni128** [comment]
@Wajeed-msft - yes, i have set AppID and AppPassword to the value i got from registering in Bot Framework. About the endpoint ngrok outputs the following: https://8b52dc41.ngrok.io -> localhost:3333 ... so i guess i can confirm.  The name of my Bot is recognized by the Teams client, but then nothing happens.  The Bot Framework Emulator though sates: "Callback URL is local" - could that maybe the problem?

**Comment by billbliss** [comment]
What is the messaging endpoint for your bot? Is it `https://8b52dc41.ngrok.io/api/messages`?

**Comment by bretesq** [comment]
We have the bot messaging working, however, the messaging extension doesn't appear to work. Is there anything special that needs to be registered for it? We just receive the "Something went wrong with this app." when trying to initiate it from the chat ellipsis.

**Comment by bretesq** [comment]
Another note, the bot messaging works only when it is a direct message. Sending the message to the bot @Hello World in a channel of a team that it was registered in does nothing. I'm not even seeing a request made to ngrok. 

Secondly, the messaging extension is making a request to ngrok endpoint, however, we are returning a 401 Unauthorized. The App Id and Password look good in the web.config, so i'm at a loss. Any idea?

**Comment by Wajeed-msft** [comment]
@bretesq - Could you please share you bot id & your bot endpoint URL? Are you using [Microsoft Teams Freemium](https://products.office.com/en-us/microsoft-teams/free) account?

**Comment by jasonchuah4** [comment]
I am facing the same problem as what @dni128 describe and already did what @Wajeed-msft suggested but it is still not working for me. I can chat with the bot in the Bot Emulator and Webchat but not in Teams. After doing some research, I found that the package for `Microsoft.Bot.Connector.Teams` is version `0.8.0`. I've updated this package through NuGet manager and finally I am able to interact with the Bot through MS Teams either personal or channel! On a side note, try to check if your `Microsoft.Bot.Builder` version is `3.5.9` as I am not sure why mine is `3.1.x` instead.

**Comment by jasonchuah4** [comment]
By the way, communication in MS Teams channel works only if I am hosting my Bot apps in localhost and publish it through ngrok. If I host my Bot apps on an external IIS server (with a valid public domain name), I could interact with the Bot via direct chat either normal chat or using the Rich Card function, but not in channel like what @bretesq mentioned.

**Comment by Wajeed-msft** [comment]
@jasonchuah4 - Could you please share your bot Id? It's hard to tell what might be wrong based on the details provided.

**Comment by bretesq** [comment]
> @bretesq - Could you please share you bot id & your bot endpoint URL? Are you using [Microsoft Teams Freemium](https://products.office.com/en-us/microsoft-teams/free) account?

Sure, i'm using appid 09163ab4-bbc3-4de7-847a-eb6b7e6e4469 and messaging endpoint is https://5a8565f6.ngrok.io/api/messages

No, i'm not using the Teams Freemium, we are using E3 license w/ Teams included

**Comment by Wajeed-msft** [comment]
@bretesq - I am not able to find bot with id **09163ab4-bbc3-4de7-847a-eb6b7e6e4469**. Could you please confirm if this is correct bot id which you got from Bot Framework portal?

**Comment by jasonchuah4** [comment]
@Wajeed-msft hi here is my Bot ID 4be277a5-6e5a-4d8d-af1f-661c5e627034
