### ISSUE TITLE
MS Teams | Accessibility Insight & Automation API | Dual Monitor

### ISSUE THREAD

**Issue by ashubabu** [MicrosoftDocs/msteams-docs#3154]
I raised a bug under Accessibility Insight project, however, I suspect MS Teams behavior under Dual Monitors at different scales is not consistent. 
I would request to take a look at https://github.com/microsoft/accessibility-insights-windows/issues/1114, please.

**Comment by ashubabu** [comment]
I received a reply from Accessibility Insight team's member that MS Teams does seem to not respond correctly. Please read it here
https://stackoverflow.com/questions/67189742/ms-teams-accessibility-insight-dual-monitor

The response is from the same person who is responsible to handle the bug https://github.com/microsoft/accessibility-insights-windows/issues/1114 

If you take a look, please or guide me to correct channel to raise this issue. I had already raised it at https://answers.microsoft.com/en-us/msteams/forum/msteams_other-msteams_topother/microsoft-teams-automation-api-accessibility/25de2afa-6b2b-4fa4-92c8-1649e414e1e3?tm=1619056663039&auth=1 

from where I was asked to move it to GitHub

**Comment by Wajeed-msft** [comment]
Please track the issue raise here: https://github.com/microsoft/accessibility-insights-windows/issues/1114
Closing this one from Microsoft Teams platform issues page.
