### ISSUE TITLE
MS Teams - Leave Button on Touch Bar not working

### ISSUE THREAD

**Issue by sgasparini** [MicrosoftDocs/msteams-docs#3155]
On MacBook Pro with Touch Bar, Teams display buttons 
"Show participants", "Show conversation", ... and the Leave Button.

Leave Button does nothing.

Microsoft Teams Version 1.4.00.8872
MacOS 11.2.3 (20D91)

**Comment by v-chetsh** [comment]
@sgasparini - Could you please confirm if your issue has resolved or still looking for any help?

**Comment by sgasparini** [comment]
it is working now
