### ISSUE TITLE
Teams bot - Hero card with open url button doesn't open task module when clicking.

### ISSUE THREAD

**Issue by kmkaliraj** [MicrosoftDocs/msteams-docs#3159]
[Enter feedback here]

---
#### Document Details
Ring0/Ring1
https://teams.microsoft.com/_?container=220527-oncdn-c63aa57-7212413#/apps/c95a45cd-91af-4f89-b138-434556e8d5b8/sections/conversations?slug=28:6f8c3a32-e4c0-4f34-a358-c8c81a0c16a2

![image](https://user-images.githubusercontent.com/23566351/115775600-f27a6a80-a367-11eb-8146-5fa8841e71fb.png)

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 800b748d-fb81-8f4d-adc2-3ee610394346
* Version Independent ID: b1ebd031-c5cd-ffeb-d9b2-d752511900db
* Content: [Using Task Modules in Microsoft Teams bots - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/task-modules/task-modules-bots)
* Content Source: [msteams-platform/task-modules-and-cards/task-modules/task-modules-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/task-modules/task-modules-bots.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Sridevi-MSFT** [comment]
Hi @kmkaliraj, I will repro this issue at my end and will get back to you.

**Comment by Sridevi-MSFT** [comment]
@kmkaliraj, Could you please confirm if you have assigned the deeplink url to the task module in open url button.
