### ISSUE TITLE
Want a link in deeplink 

### ISSUE THREAD

**Issue by shail4wrs** [MicrosoftDocs/msteams-docs#3164]
Hi Teams,

We have a script which trigger the teams app and sending the message to the user . i want to draft a message to user which has a url of a ticket in message but it not working , it sends whole url of the ticket with html tag

for Example : 

Hi caller, this is regarding ticket: <a hre =https://dev123.service-now.com/incident.do?sys_id=6040a2f21b2b24902djc5868464bcb4fed>INC1234567 /a> - Other Issues - ServiceNow

however i want below ,
Hi caller, this is regarding ticket: [INC1234567](https://dev123.service-now.com/incident.do?sys_id=6040a2f21b2b24902djc5868464bcb4fed) Other Issues - ServiceNow

Note :- in example i have edited the html tag because it making the url of the ticket , just i want to show you in text as it shows in teams message

**Comment by shail4wrs** [comment]
any update ?

**Comment by shail4wrs** [comment]
update please

**Comment by shail4wrs** [comment]
update please?

**Comment by shail4wrs** [comment]
Here is example of how i am posting msg o user from snow. but i wanted to make link to ticket "number " here , please help me    

var url = 'msteams:/l/chat/0/0?users=' + email + '&amp;amp;message=Hi ' + firstName + ', this is regarding ticket: ' + number + ' - ' + short_desc;

**Comment by v-chetsh** [comment]
@shail4wrs - Could you please confirm if your issue has resolved or still looking for any help?

**Comment by shail4wrs** [comment]
> @shail4wrs - Could you please confirm if your issue has resolved or still looking for any help?

**Comment by shail4wrs** [comment]
> <img alt="@shail4wrs" width="20" height="20" src="https://avatars.githubusercontent.com/u/83130111?s=60&amp;v=4">

**Comment by shail4wrs** [comment]
Hi @v-chetsh ,

Issue is still persist , please help me.

Thanks

**Comment by v-chetsh** [comment]
@shail4wrs - Sure, we will check on it and let you know.

**Comment by HunaidHanfee-MSFT** [comment]
Hi, 
@shail4wrs - Can you try adding your URL like this - 
[INC1234567 ](https://dev123.service-now.com/incident.do?sys_id=6040a2f21b2b24902djc5868464bcb4fed)

Please refer [Supported text formatting](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bots-text-formats#examples-of-text-formatting)

If this is not what you are looking for could you please elaborate more on this?
Thanks

**Comment by HunaidHanfee-MSFT** [comment]
Could you please confirm if your issue has resolved with above suggestion or still looking for any help?
Thanks

**Comment by shail4wrs** [comment]
> Hi, @shail4wrs - Can you try adding your URL like this - [INC1234567] (https://dev123.service-now.com/incident.do?sys_id=6040a2f21b2b24902djc5868464bcb4fed) ![image](https://user-images.githubusercontent.com/64194049/148013701-c4219c64-a688-4d2b-81bf-fc2d3f1889cc.png)
> 
> Please refer [Supported text formatting](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bots-text-formats#examples-of-text-formatting)
> 
> If this is not what you are looking for could you please elaborate more on this? Thanks

Hi,

here is my code where how i send the msg to user 

  var url = 'msteams:/l/chat/0/0?users=' + email + '&amp;amp;message=Hi ' + firstName + ', this is regarding ticket: ' + number + ' - ' + short_desc; 

"number" is incident no , here i want make "number" as incident link.

now please suggest how i can make it link

**Comment by HunaidHanfee-MSFT** [comment]
Could you please share some documentation where you are following this approach from ?

**Comment by HunaidHanfee-MSFT** [comment]
Are you trying to use - https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links#generate-a-deep-link-to-a-chat this deeplink? and want to instert text having hyperling in user compose area?

**Comment by Prasad-MSFT** [comment]
Hi @baluvijay - Directly rendering hyperlink as prefilled text doesn't seem to be possible.

**Comment by baluvijay** [comment]
@Prasad-MSFT  why did you mention me in this issue?

**Comment by ChetanSharma-msft** [comment]
Hello @baluvijay - We received a escalation from your end on this issue. So we have mentioned you. Please ignore it.

@shail4wrs - Directly rendering hyperlink as prefilled text doesn't seem to be possible.

**Comment by Prasad-MSFT** [comment]
@baluvijay - Sorry for any inconvenience. But as we got a reply as below, mentioned here.
![image](https://user-images.githubusercontent.com/62237649/186644524-8d2690a8-55b3-4c60-b5c7-be7648e28e75.png)

**Comment by baluvijay** [comment]
@Prasad-MSFT  Hi,  I made that comment on a different issue, related to MS-Teams custom connector, giving 403 forbidden error when trying to execute an actionable message, no idea which all permission has to be given by the admin for that, and no mention in the documentation regarding any special permission

**Comment by Prasad-MSFT** [comment]
Okay, thanks for updating @baluvijay .

**Comment by ChetanSharma-msft** [comment]
Hello @baluvijay - Can you please share your issue link, so that we can just investigate why that comment is added to this particular issue ?
