### ISSUE TITLE
CARD-IN-BODY header not causing cards to refresh

### ISSUE THREAD

**Issue by vimil** [MicrosoftDocs/msteams-docs#3177]
[Enter feedback here]
I have been using the CARD-UPDATE-IN-BODY header to refresh cards sent using the incoming webhook connector. This used to work flawlessly until recently. It seems like ths header is being ignored now and the card does not refresh.

Could you look into this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da50e4db-a713-ab8b-d27b-89aa946619d0
* Version Independent ID: 57e368e2-aaed-fa8d-ed49-cc18e594ab1d
* Content: [Office 365 Connectors - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-creating)
* Content Source: [msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Sridevi-MSFT** [comment]
@vimil - Could you please share the code you are trying, so that we can repro at our end.

**Comment by vimil** [comment]
Hi @Sridevi-MSFT 
Here is the json response sent from the code 

**Headers:**
CARD-ACTION-STATUS: Shelveset status updated
CARD-UPDATE-IN-BODY: true

**JSON body**

`{
    "summary": "car-api-locations",
    "themeColor": "0076D7",
    "@type": "MessageCard",
    "potentialAction": [{
            "@type": "ViewAction",
            "name": "View",
            "@context": "http://schema.org",
            "target": ["https://tfs.pacific.costcotravel.com/tfs/CostcoTravel/Source/_versionControl/shelveset?ss=car-api-locations%3BPACIFIC%5Ctestuser"]
        }, {
            "@type": "ActionCard",
            "inputs": [{
                    "isMultiline": true,
                    "@type": "TextInput",
                    "id": "comment",
                    "title": "Comment",
                    "value": "Approved Shelveset car-api-locations for checkin"
                }
            ],
            "name": "Approve",
            "@context": "http://schema.org",
            "actions": [{
                    "@type": "HttpPOST",
                    "bodyContentType": "application/json",
                    "name": "Approve",
                    "body": "{\"ownerName\":\"PACIFIC\\\\testuser\",\"approvalComment\":\"{{comment.value}}\",\"shelvesetName\":\"car-api-locations\"}",
                    "target": "https://ct-epm.servicebus.windows.net/ct-hybrid/shelvesetReviewManager/resources/teams/approveShelveset"
                }
            ]
        }, {
            "@type": "HttpPOST",
            "bodyContentType": "application/json",
            "name": "Update Status",
            "body": "{\"ownerName\":\"PACIFIC\\\\testuser\",\"shelvesetName\":\"car-api-locations\"}",
            "@context": "http://schema.org",
            "target": "https://ct-epm.servicebus.windows.net/ct-hybrid/shelvesetReviewManager/resources/teams/updateShelvesetReviewStatus"
        }
    ],
    "@context": "http://schema.org/extensions",
    "sections": [{
            "activitySubtitle": "revamped new car API locations method",
            "activityTitle": "car-api-locations",
            "activityImage": "https://static.thenounproject.com/png/104096-200.png",
            "markdown": true,
            "facts": [{
                    "name": "Created By",
                    "value": "testuser"
                }, {
                    "name": "Creation Date",
                    "value": "April 30,2021 06:05:21 PM Pacific Daylight Time"
                }, {
                    "name": "Reviewers",
                    "value": "- Development Team (<span style=\"color:red\">Pending Approval</span>)"
                }, {
                    "name": "Build",
                    "value": "[90526](https://jenkins-dev.pacific.costcotravel.com/job/Build%20-%20Personal/90526/)"
                }, {
                    "name": "Work Items",
                    "value": "- [294814](https://tfs.pacific.costcotravel.com/tfs/CostcoTravel/Work%20Items/_workitems?id=294814)\n- [294795](https://tfs.pacific.costcotravel.com/tfs/CostcoTravel/Work%20Items/_workitems?id=294795)"
                }
            ]
        }
    ]
}`

Let me know if you need additional details

**Comment by Sridevi-MSFT** [comment]
@vimil- We have raised a bug on this and it is being tracked internally.

**Comment by Sridevi-MSFT** [comment]
@vimil -We are  not able to repro with your payload when clicking on Approve button.
Could you please check if the back end service is throwing any errors? Please confirm how the HTTP post is made in your backend or Fiddler capture with the service running locally?
