### ISSUE TITLE
Card Example section is broken

### ISSUE THREAD

**Issue by Linaa** [MicrosoftDocs/msteams-docs#318]
Card Example section:
source code for both Node and .NET returns 404:
https://github.com/Microsoft/BotBuilder-Samples/tree/master/Node/cards-RichCards

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8a3bcf2-332a-8d24-a8d1-7e3816897745
* Version Independent ID: 68fb9551-ce95-0112-2703-721a1af01f23
* Content: [Cards Reference - Teams](https://docs.microsoft.com/en-gb/microsoftteams/platform/concepts/cards/cards-reference)
* Content Source: [msteams-platform/concepts/Cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/Cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by billbliss** [comment]
When they moved to SDK v4 the links broke. Norm can you fix the links? The root for the v3 samples is here: https://github.com/Microsoft/BotBuilder-Samples/tree/v3-sdk-samples.

**Comment by clearab** [comment]
Should be fixed now, thanks for letting us know.
