### ISSUE TITLE
Unable to open .docx file downloaded from SharePoint site / Azure Blob Storage in desktop app(Word) in Teams

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#3180]
Copied bug from: https://github.com/microsoft/botframework-sdk/issues/6276

Describe the bug
When I'm trying to read files from SharePoint/ Azure Blob Storage, The file from SharePoint site / Azure Blob Storage is properly downloaded in teams and uploaded in one drive as well. on clicking the three buttons and choosing different actions gives different results:-

Edit in teams: Doc.aspx is requesting access to open it and on clicking the 'Request access' button it is opening the file in the browser instead of teams.
Open in Desktop App: The file is not opening in the desktop app and the following error is coming.
Open in Browser: The file is properly opening in the browser.
To Reproduce

Download any file from SharePoint/Azure Blob Storage using a bot in Teams.
Select three dots
Click on 'Open in Desktop App'.
Expected behavior
The document should be opened in the word of the desktop.

Screenshots
![MicrosoftTeams-image](https://user-images.githubusercontent.com/51920866/115959269-04efd200-a529-11eb-955f-954a995c7ac3.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee0217c9-886a-00c7-0aca-68f7580d82fb
* Version Independent ID: 6bcc7af0-05b8-021d-0aad-8ac89e3d595c
* Content: [Send and receive files through the bot - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/bots-filesv4)
* Content Source: [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/bots/how-to/bots-filesv4.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by RajdeepRay0411** [comment]
Hi @Wajeed-msft, Do we have any update on this issue?

**Comment by RajdeepRay0411** [comment]
Hi @Wajeed-msft , @Nikitha-MSFT , do we have any updates on this issue?

**Comment by RajdeepRay0411** [comment]
Hi, @Wajeed-msft and @Nikitha-MSFT, can you please let us know the status on the issue as we are following up for the past seven days but not hearing anything from your side. As this is a big issue escalated from our client-side, we need to update them as soon as possible.

**Comment by RajdeepRay0411** [comment]
Hi, @Wajeed-msft and @Nikitha-MSFT, can you please let us know the status on the issue as we are following up for the past fourteen days but not hearing anything from your side. As this is a big issue escalated from our client-side, we need to update them as soon as possible.

**Comment by Nikitha-MSFT** [comment]
@RajdeepRay0411 - We are not able to re-pro the issue at our end. Could you please share the console logs that you receive in the developer tools.

**Comment by RajdeepRay0411** [comment]
![image](https://user-images.githubusercontent.com/51920866/119614356-d0b74c00-be1b-11eb-8960-7158cf59704e.png)

@Nikitha-MSFT, PFA for console logs for MS Teams developer tools for the issue.

**Comment by RajdeepRay0411** [comment]
@Nikitha-MSFT, Can you please look into this and take some necessary steps as early as possible as I too need to report to my client about the troubleshooting.

**Comment by Nikitha-MSFT** [comment]
@RajdeepRay0411 - Could you please share the manifest with us?

**Comment by RajdeepRay0411** [comment]
{
    "$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.7/MicrosoftTeams.Localization.schema.json",
    "manifestVersion": "1.8",
    "version": "5.0.16",
    "id": "",
    "packageName": "",
    "developer": {
        "name": "",
        "websiteUrl": "",
        "privacyUrl": "",
        "termsOfUseUrl": ""
    },
	"localizationInfo": {
    "defaultLanguageTag": "en",
    "additionalLanguages": [
      {
        "languageTag": "es",
        "file": "Spanish.json"
      },
      {
        "languageTag": "pt",
        "file": "Portuguese.json"
      },
      {
        "languageTag": "fr",
        "file": "French.json"
      },
      {
        "languageTag": "de",
        "file": "German.json"
      },
      {
        "languageTag": "it",
        "file": "Italian.json"
      },
      {
        "languageTag": "ru",
        "file": "Russian.json"
      },
      {
        "languageTag": "zh-Hans",
        "file": "Chinese.json"
      },
	  {
        "languageTag": "pl",
        "file": "Polish.json"
      },
      {
        "languageTag": "ja",
        "file": "Japanese.json"
      },
	  {
        "languageTag": "nl",
        "file": "Dutch.json"
      },
	  {
        "languageTag": "tr",
        "file": "Turkish.json"
      }
    ]
  },
    "icons": {
        "color": "",
        "outline": ""
    },
    "name": {
        "short": "",
        "full": ""
    },
    "description": {
        "short": "",
        "full": ""
    },
    "accentColor": "#F9F9FA",
    "bots": [
      {
        "botId": "",
        "scopes": [
          "personal"
        ],
        "commandLists": [
          {
            "scopes": [
              "personal"
            ],
            "commands": [
              {
                "title": "Main menu",
                "description": "Go to main menu"
              },
              {
                "title": "Discover Una",
                "description": "Find out top tips to chat with me"
              },
              {
                "title": "Share feedback",
                "description": "Share your Una experience"
              },
              {
                "title": "Change language",
                "description": "Change chat language"
              },
			  {
                "title": "Cancel",
                "description": "End the current conversation"
              }
            ]
          }
        ],
        "supportsFiles": true,
        "isNotificationOnly": false
      }
    ],
  "webApplicationInfo": 
  {
    "id": "",
    "resource": ""
  },
	"permissions": [
        "identity",
        "messageTeamMembers"
    ],
    "validDomains": [
	"token.botframework.com",
	"microsoft.com",
	"google.com",
	"*.ngrok.io"
	]
}

**Comment by RajdeepRay0411** [comment]
Hi @Nikitha-MSFT, can you please let me know the status of the issue. As this is a big issue escalated from our client side, we need to update them as soon as possible.

**Comment by RajdeepRay0411** [comment]
Hi @Nikitha-MSFT, I have already shared the manifest and waiting for some solution as I need to tell my client the same. Can you please look into the issue and help me out asap.
