### ISSUE TITLE
File deep link has a typo

### ISSUE THREAD

**Issue by ydogandjiev** [MicrosoftDocs/msteams-docs#3186]
The documentation for deep linking to a file has a typo in it. The deep link path should start with `/l/file` instead of `/I/file`. The character after the first slash should be a lower case "L" instead of an "I".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45541337-ecd7-5cf6-cbe4-3f0d2f39aa79
* Version Independent ID: 6b4203f0-2844-06c9-eaa3-9cc03e6f76c0
* Content: [Create deep links - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links)
* Content Source: [msteams-platform/concepts/build-and-test/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/build-and-test/deep-links.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Wajeed-msft** [comment]
Raised PR for the fix: https://github.com/MicrosoftDocs/msteams-docs/pull/3187
