### ISSUE TITLE
Deep links to sideloaded app do not work in some channels

### ISSUE THREAD

**Issue by Robert-F** [MicrosoftDocs/msteams-docs#3193]
We have a custom app which is manually installed by customers by publishing it in the organization's app catalog via "Manage Apps". The app is using deep links in action cards using `Action.OpenUrl` following the scheme as documented in https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/build-and-test/deep-links.md

`https://teams.microsoft.com/l/entity/${appId}/${entityId}?label=${entityLabel}&context=${deepLinkContext}`

According to the documentation, `appId` should be "The ID from your manifest" and this is also the value which we are using. In 95% of the cases, the created deep links work as expected and everything is fine. However, in the remaining 5%, clicking the deep links does not work at all and only reloads the Posts tab instead of opening our app's tab. A similar experience as when the tab has been removed. In our experience, if deep links work in a channel, they always work for every user - but in some channels they never work, regardless of the user creating or opening the deep link. We have not been able to identify a pattern in which channels deep links work and in which not.

However, if we do not use the app ID from the manifest but instead build the deep link using the app catalog's app ID, deep links always work - even in channels where they previously did not work using the manifest's app ID.

Our workaround is now to always use the app catalog's app ID after fetching it using the `/teams/[GUID]/installedApps` endpoint as described in https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/team-list-installedapps.md#example-3-get-the-app-installation-resource-based-on-the-manifest-id-of-the-associated-app

It would be great if either deep links using the manifest's app ID would work 100% reliable or the documentation would be updated that the app catalog's app ID should be used.

When searching the other issues, this one could be related to the same problem: https://github.com/MicrosoftDocs/msteams-docs/issues/2552

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45541337-ecd7-5cf6-cbe4-3f0d2f39aa79
* Version Independent ID: 6b4203f0-2844-06c9-eaa3-9cc03e6f76c0
* Content: [Create deep links - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links#feedback)
* Content Source: [msteams-platform/concepts/build-and-test/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/build-and-test/deep-links.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Mamatha-MSFT** [comment]
Hi @Robert-F - Thanks for bringing up this issue, I will repro at my end and will let you know.

**Comment by Mamatha-MSFT** [comment]
@Robert-F - In tab deeplink` https://teams.microsoft.com/l/entity/<appId>/<entityId>?webUrl=<entityWebUrl>&label=<entityLabel>&context=<context>`,  all query parameters are properly URI encoded. Please change webUrl and context  to encoded format and let me know if you still persist the issue.

**Comment by Robert-F** [comment]
@Mamatha-MSFT Yes, all query parameters properly encoded - we only use the `label` and `context` parameters, but no `webUrl`. This is the relevant code:

```
  const entityLabel = 'AppName';
  const deepLinkContext = encodeURI(JSON.stringify({ subEntityId: userId, channelId: context.channelId }));

  return `https://teams.microsoft.com/l/entity/${appId}/${entityId}?label=${entityLabel}&context=${deepLinkContext}`;
```

When using the app catalog's app ID all deep links work as expected.

**Comment by Mamatha-MSFT** [comment]
@Robert-F -webUrl  optional field with a fallback URL to use if the client does not support rendering the tab. Even though mentioned as optional add webUrl to your deeplink.
