### ISSUE TITLE
Teams design documentation links to a third party site with no instructions about what to do with the third-party content

### ISSUE THREAD

**Issue by ascott18** [MicrosoftDocs/msteams-docs#3198]
There used to be some perfectly usable guidelines in this documentation. Now, the pages that used to be here that we had linked to from our application's code to reference the style guidelines we had used are 404, seemingly replaced by links to a third party website ("Figma") that just has nothing on it but a single picture of the "Microsoft Teams UI Kit".

How are we supposed to use this new documentation? It doesn't even seem to really exist - it just links to a landing page that contains no other content.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e13fe9ac-9ae6-4f86-e800-e667ea49cd73
* Version Independent ID: d1034128-eda7-8d57-3d1d-dd862043db17
* Content: [Design your app - Understanding the fundamentals - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/design/design-teams-app-fundamentals)
* Content Source: [msteams-platform/concepts/design/design-teams-app-fundamentals.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/design/design-teams-app-fundamentals.md)
* Product: **msteams**
* GitHub Login: @heath-hamilton
* Microsoft Alias: **lajanuar**

**Comment by Sridevi-MSFT** [comment]
@ascott18 - Will check this issue at our end and will get back to you.

**Comment by heath-hamilton** [comment]
@ascott18 Thank you so much for the feedback! Sorry about the 404s; we actually had to deprecate those pages when we released our totally revamped design docs late last year. There should be redirects in place now so you won't get the errors.

The docs are a lot more extensive now, and the Figma tool is intended to make them more interactive and design-friendly. That said, can you elaborate on what you'd like to see on the docs site that isn't currently there or maybe hidden in Figma? Always looking to improve the experience.

**Comment by ascott18** [comment]
@heath-hamilton When I go to the Figma site, all I see is a picture and a short description. I don't know what I'm supposed to do with this. I see a "duplicate" button (not quite sure what it does), but that forces me to make an account. 

When the old docs were hosted by Microsoft, I didn't have to click a "duplicate" button and make an account with a third-party service so I could get spammed with more marketing emails. There are comments from other users on the Figma page that are equally confused - see the comments there by Ron, Kate, and others.

This is what I see:
![image](https://user-images.githubusercontent.com/5017521/117096020-c7572a00-ad1c-11eb-89bf-3abd72db6f0a.png)

**Comment by heath-hamilton** [comment]
@ascott18 Understood! Thanks again for the detailed feedback and input. It really helps--we're actively investigating how to make this a better experience.

**Comment by heath-hamilton** [comment]
@ascott18 We just published updated design docs, including the following link that may help:

- [Understand the design process](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/design/design-teams-app-process): We have a lot of design resources and tools now. This doc attempts to explain when and how you use all of these (including the UI kit Figma file).
