### ISSUE TITLE
Schema changes to make certain fields customizable

### ISSUE THREAD

**Issue by GauravES** [MicrosoftDocs/msteams-docs#3199]
[Enter feedback here]
It appears from https://docs.microsoft.com/en-us/MicrosoftTeams/customize-apps that developers can mark certain fields customizable in the Manifest.  Yet there is no documentation in the Schema on how the developers should indicate this ability.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f94a488-d636-92b3-21eb-c88744c8f272
* Version Independent ID: 7b3413f4-9ade-accf-5cb2-83fead11a32a
* Content: [Manifest schema reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema)
* Content Source: [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/resources/schema/manifest-schema.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Jagadeesh-MSFT** [comment]
Hi @GauravES, there is a hyper link for details about the fields that you can customize in Teams Manifest schema. could you please check the below image. 
![image](https://user-images.githubusercontent.com/73812940/116510452-9329d680-a8e2-11eb-98ca-d327f2a3a83e.png)

**Comment by GauravES** [comment]
That hyper link points to this same page about which the comment was made ; that destination page does NOT have any information on how to customize the fields.  The Teams Manifest schema page needs to be updated with this information

**Comment by NicolasMCAG** [comment]
Hi,

I'm using the developer preview manifest that includes the "configurableProperties" section (https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema-dev-preview) on a test app I'm developing, yet when I add said section to the manifest I can't upload it.

This is the manifest I have (sections collapsed to keep it short):
![image](https://user-images.githubusercontent.com/58806598/117153736-89f5a980-adbb-11eb-9aaa-4b8323b7cd59.png)


This is what I checked so far:

I have app customization enabled on my tenant (I guess)...

![image](https://user-images.githubusercontent.com/58806598/117152849-b230d880-adba-11eb-9dc4-542b7083190a.png)

I have custom app uploading enabled from a long time ago, and I tried uploading the zipped app through the Manage Apps on the Teams Admin center, and also from the Teams client using developer preview. No luck so far.

As soon as I remove the "configurableProperties" section the app uploads fine. I also tried with many combinations of properties on the array to no avail.

**Comment by Jagadeesh-MSFT** [comment]
Hi @GauravES, our document team is recently updated the document, could you please verify once again.

**Comment by Jagadeesh-MSFT** [comment]
Hi @NicolasMCAG, could you please raise a new question for better tracking with you manifest. Thank you.

**Comment by GauravES** [comment]
Thanks.   The documentation is now fixed.
