### ISSUE TITLE
The search drop down menu with Cards behind the embed app content in Teams app\web

### ISSUE THREAD

**Issue by jonmill** [MicrosoftDocs/msteams-docs#3204]
Bug transfer from Adaptive Cards: https://github.com/microsoft/AdaptiveCards/issues/5526

# Platform
- [x] .NET HTML

# Details
The search drop down menu with Cards behind the embed app content in Teams app\web

**Expected behavior**
Drop-down is visible with correct z-index property 
![image](https://user-images.githubusercontent.com/15952613/109493668-e11a8d80-7a9d-11eb-9981-d190a499f695.png)

**Screenshots**
Drop-down is not visible
![image](https://user-images.githubusercontent.com/15952613/109493473-9a2c9800-7a9d-11eb-90c5-2cb6b5ae1475.png)

**Comment by Sridevi-MSFT** [comment]
@jonmill - Thanks for bringing up this issue,  will repro at our end and will let you know.

**Comment by Sridevi-MSFT** [comment]
@jonmill - We have raised a bug for this issue, concerned engineering team is working on it.

**Comment by v-chetsh** [comment]
@jonmill - Could you please confirm if your issue has resolved or still looking for any help?
