### ISSUE TITLE
Code Sample for Responding with Another Task Module?

### ISSUE THREAD

**Issue by TracyGH** [MicrosoftDocs/msteams-docs#3205]
Can anyone point me towards a C# code sample demonstrating what's described in the highlighted text below?  
The image is referencing [this paragraph](https://docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/action-commands/respond-to-task-module-submit?tabs=dotnet%2Cdotnet-1#respond-with-another-task-module), and I'm currently working off of [this sample](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/51.teams-messaging-extensions-action).  

![image](https://user-images.githubusercontent.com/38665906/116638684-b2912580-a91b-11eb-9bb3-0778b9e270b5.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fb0c2d8-f880-c260-d0be-6b9467e47f8c
* Version Independent ID: 7820ffc9-5260-c818-f5fb-672801a67d00
* Content: [Respond to the task module submit action - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/action-commands/respond-to-task-module-submit?tabs=dotnet%2Cdotnet-1#respond-with-another-task-module)
* Content Source: [msteams-platform/messaging-extensions/how-to/action-commands/respond-to-task-module-submit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/messaging-extensions/how-to/action-commands/respond-to-task-module-submit.md)
* Product: **msteams**
* GitHub Login: @clearab
* Microsoft Alias: **anclear**

**Comment by Mamatha-MSFT** [comment]
Hi @TracyGH, Currently there is no Code Sample for Responding with Another Task Module. 

On `microsoftTeams.tasks.submitTask()` action you need to create a new new card to fetch another task module in `OnTeamsMessagingExtensionSubmitActionAsync()` method .

```
protected override async Task<MessagingExtensionActionResponse> OnTeamsMessagingExtensionSubmitActionAsync(ITurnContext<IInvokeActivity> turnContext, MessagingExtensionAction action, CancellationToken cancellationToken)
        {
            switch (action.CommandId)
            {
                ..........................
            }
            return new MessagingExtensionActionResponse();
        }
```

**Comment by TracyGH** [comment]
Thank-you for the response, @Mamatha-MSFT!  I was able to get the code in [this sample](https://docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/action-commands/create-task-module?tabs=dotnet#example-7) working, but I cannot figure out how to distinguish between the 2 submits.  The `turnContext` and `action`object parameters in the `OnTeamsMessagingExtensionSubmitActionAsync` method both appear to have identical values.  
Any recommendations?

**Comment by TracyGH** [comment]
I was able to use the `MessagingExtensionAction action.Data` content to distinguish between the calls.
