### ISSUE TITLE
Is this feature still in Developer Preview?

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#321]
[What's New](https://docs.microsoft.com/en-us/microsoftteams/platform/whats-new) section shows that the "task module" feature was released.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86441a60-584c-73d1-d678-1c3a2c38a872
* Version Independent ID: 35ca31ef-620b-7ff4-d91c-e4aa9eacf5a1
* Content: [Overview of Microsoft Teams Task Modules - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/task-modules/task-modules-overview)
* Content Source: [msteams-platform/concepts/task-modules/task-modules-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/task-modules/task-modules-overview.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by billbliss** [comment]
It's not and the docs should reflect that. If I missed a place let me know.

**Comment by Wajeed-msft** [comment]
There is a note saying it's still in Dev Preview. Could you please help to remove it?
![image](https://user-images.githubusercontent.com/31851992/48394138-58467f00-e738-11e8-8bfb-abf2b1c764df.png)
