### ISSUE TITLE
Rate limiting not resetting

### ISSUE THREAD

**Issue by BrendanAndrade** [MicrosoftDocs/msteams-docs#3217]
Hi, 

I am trying to implement a strategy to handle rate-limiting for one of my bots. I am testing in development and triggered a rate limit error (429 response) after sending multiple context.updateActivity() requests. This was expected. However, now 6 hours later, I am still receiving 429 errors. I waited a few hours before trying again. According to the docs, the limit periods are at most 1 hour. Why am I still seeing these errors and how do I get my bot working again?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a57254c9-963d-ea1d-ecaf-dd0e7913526c
* Version Independent ID: 610c8514-bd72-46cc-75f1-991e2242019b
* Content: [Optimize your bot with rate limiting in Teams - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/rate-limit)
* Content Source: [msteams-platform/bots/how-to/rate-limit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/bots/how-to/rate-limit.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by BrendanAndrade** [comment]
I'm still getting the rate limit error more than 24 hours later.

**Comment by Nikitha-MSFT** [comment]
How many request you are processing for a bot? When you receive 429 error you can use [Handle rate limits](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/rate-limit#handle-rate-limits) code to overcome the error.

**Comment by BrendanAndrade** [comment]
I figured out the issue. It was on my side. Thanks much for the quick response!
