### ISSUE TITLE
302 Moved Temporarily error

### ISSUE THREAD

**Issue by dtsoy95** [MicrosoftDocs/msteams-docs#3218]
![Screenshot_3](https://user-images.githubusercontent.com/78314727/116791720-924c9c80-aabc-11eb-930e-e4e900124a6a.png)

Have an issue with Conversation bot installation, by Microsoft toolkit.
All packages are empty with an error "302 Moved Temporarily"

May I ask you to advise what could be the reason?

Thank you in advance!

**Comment by Mamatha-MSFT** [comment]
Hi @dtsoy95 Could you please confirm are you following all the steps provided in the [documentation](https://docs.microsoft.com/en-us/microsoftteams/platform/build-your-first-app/build-bot).

**Comment by dtsoy95** [comment]
Hi Mamatha, yes I followed exactly these steps, provided in the documentation. Once i've chose the folder, all packages saved there with 1KB for some reason and all of the files contains "302 Moved Temporarily..."

**Comment by Mamatha-MSFT** [comment]
@dtsoy95 I am unable to repro the issue. Could you please try again to create a new bot by following the documentation and let me know if the issue still persists.

**Comment by dtsoy95** [comment]
@Mamatha-MSFT Unfortunately issue still persist. I've tried to disable VPN, thought that it could cause the issue, but still the same message in all files.
![image](https://user-images.githubusercontent.com/78314727/116898601-dc598d80-ac36-11eb-9f4c-9bd2dae05975.png)
![image](https://user-images.githubusercontent.com/78314727/116898654-ef6c5d80-ac36-11eb-9c54-2e173b3cc6b5.png)

**Comment by Mamatha-MSFT** [comment]
@dtsoy95 Could you please update the Microsoft Teams tool kit and VS code to latest versions.

**Comment by dtsoy95** [comment]
@Mamatha-MSFT I've uninstalled Microsoft Teams toolkit and install again. Version 1.2.3. But still the same issue... Will try with older toolkit versions and will update you.

**Comment by dtsoy95** [comment]
@Mamatha-MSFT Seems with version 1.1.8 everything was installed properly:
![image](https://user-images.githubusercontent.com/78314727/116991938-969fd200-acd5-11eb-913c-a284e75c9313.png)

**Comment by Mamatha-MSFT** [comment]
@dtsoy95 - I have tried with Version 1.2.3. I am unable to repro the issue. Could you please check once now and if you still persist the issue please share the logs.

**Comment by Mamatha-MSFT** [comment]
Hi @dtsoy95 - This looks like a network problem not an issue with teams toolkit version. If you look at the message it clearly states its an error coming from the security gateway.
