### ISSUE TITLE
Get a main process JavaScript error evey couple of weeks

### ISSUE THREAD

**Issue by TroyWalshProf** [MicrosoftDocs/msteams-docs#322]
About twice a month Teams stops working and it throws up the following message:
![image](https://user-images.githubusercontent.com/2066107/48281213-8156cf00-e41b-11e8-9a47-a8a785282c09.png)

Temporary fix:
1. Go to the web version of teams 
2. Click the get app link and download the installer
3. Reinstall teams

**Comment by Wajeed-msft** [comment]
@TroyWalshProf - Could you please share local logs (%AppData%\Microsoft\Teams\logs.txt)?

**Comment by TroyWalshProf** [comment]
Here you are:
[logs.txt](https://github.com/MicrosoftDocs/msteams-docs/files/2572173/logs.txt)

**Comment by evgenyvinnik** [comment]
@TroyWalshProf we are investigating your issue.
Our current suspicion is that you have two versions of Teams installed.
Could you confirm it for us?

1. One is under C:\ProgramData\<your_username>\Microsoft\Teams
2. Another one is under C:\Users\<your_username>\AppData\Local\Microsoft\Teams

The latter one is the official place where Teams are normally being installed.
Somehow the installation under C:\ProgramData\<your_username>\Microsoft\Teams wasn't removed during one of the updates.
Now it is trying to update itself or launch itself from time to time and you are seeing the exception reported above.
The logs you've sent are actually from new/working version of Teams.

I think the correct way would be to remove C:\ProgramData\<your_username>\Microsoft\Teams folder,
but before that make sure that teams under C:\Users\<your_username>\AppData\Local\Microsoft\Teams exist

**Comment by evgenyvinnik** [comment]
@TroyWalshProf  may I ask you one more question? Does your computer has any antivirus software?

**Comment by TroyWalshProf** [comment]
@evgenyvinnik 
This folder exists: C:\ProgramData\<your_username>\Microsoft\Teams
This one does not: C:\Users\<your_username>\AppData\Local\Microsoft\Teams

I do have antivirus, it is Microsoft System Center Endpoint Protection.

**Comment by TroyWalshProf** [comment]
@clearab - So is this fixed?
*I have confirmed with a couple of co-workers that it was still an issue last Friday

**Comment by TroyWalshProf** [comment]
@Wajeed-msft - Not sure if it is related, but I went thru my event logs and found something called SquirrelSetup correlated with the break.
Here is the log file:
[SquirrelSetup.log](https://github.com/MicrosoftDocs/msteams-docs/files/2920638/SquirrelSetup.log)

**Comment by TroyWalshProf** [comment]
This may also help, it is the Squirrel event log: 
[SquirrelEvent.zip](https://github.com/MicrosoftDocs/msteams-docs/files/2946870/SquirrelEvent.zip)

**Comment by Wajeed-msft** [comment]
@TroyWalshProf - Please re-open this if you still facing this issue with the latest update.

**Comment by TroyWalshProf** [comment]
Having the same issue again
