### ISSUE TITLE
Assignments with numbering shows always as 1. 

### ISSUE THREAD

**Issue by FloJ12** [MicrosoftDocs/msteams-docs#3221]
I assign an assignment for example "3. Homework" but in posts it shows "1. Homework". If I click on the assignment it says "3. Homework" (correctly)
I use teams for Android

**Comment by Nikitha-MSFT** [comment]
We are checking internally, get back to you soon

**Comment by Nikitha-MSFT** [comment]
Are you still facing the issue, if yes could you please share the screen shot of the issue?

**Comment by FloJ12** [comment]
Yes. Screenshots are attached.

Mit freundlichen Grüßen
Florian Jandl
Am 26. Mai 2021, 07:45 +0200 schrieb Nikitha-MSFT ***@***.***>:

**Comment by Nikitha-MSFT** [comment]
Where did you attach the screen shots?

**Comment by FloJ12** [comment]
![Screenshot_20210526-080831_Teams](https://user-images.githubusercontent.com/5287213/120897536-01229580-c627-11eb-957e-3304700ef56c.jpg)
![Screenshot_20210526-080854_Teams](https://user-images.githubusercontent.com/5287213/120897539-054eb300-c627-11eb-958e-7f35f9c04205.jpg)

**Comment by Nikitha-MSFT** [comment]
We are checking with internal team, get back to you soon.

**Comment by Nikitha-MSFT** [comment]
Could you please file a ticket at https://aka.ms/edusupport?
