### ISSUE TITLE
howto build the package?

### ISSUE THREAD

**Issue by Grunge** [MicrosoftDocs/msteams-docs#3222]
It describes howto adjust the icons, but how can I build package? 
In SPFX we would  use:
gulp bundle --ship
gulp package-solution --ship

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0b75ec1-0ded-400e-7291-b7776d510ae4
* Version Independent ID: 157f3a51-42f6-f70f-a599-6775fcb34ed1
* Content: [Package your app - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/apps-package)
* Content Source: [msteams-platform/concepts/build-and-test/apps-package.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/build-and-test/apps-package.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Jagadeesh-MSFT** [comment]
Hi @Grunge, It is clearly explaining that we required Zip file in the below image. Are you expecting the same using terminal?
![image](https://user-images.githubusercontent.com/73812940/117018742-66c2ef80-ad12-11eb-99f5-5851d71ee8e9.png)

**Comment by Grunge** [comment]
So I figured no out:

1.Zip
building the Zip goes like this: "gulp manifest"
-> The i go to Teams, Start in Teams the "App Studio", verify the Zip und import it.
-> There i did install after I changed all settings (repeated upload) so they validate.

2. Web
buolding the web wsa like "gulp build"
-> Then i went to azure portal, created a storage account
-> Activated WEB and exposed to all internet.
-> Used the Desktop Application "Azure Storage Explorer" to upload the "web" Folder into the $web in the storage app.

Is this correct are i am doing it wrong?
Seems all so complicated.

**Comment by Jagadeesh-MSFT** [comment]
Hi @Grunge, Thanks for the update, I think for all that you can fallow [this](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/build-a-hello-world-web-part) document, it explains about building the app, creating web part, connecting with web part etc.,

**Comment by Grunge** [comment]
Thank you I understand howto build an SPFX and deploy it in SharePoint App Store.
But where and how do I deploy a Teams App? Not the zipped Icon+Manifest, the part that is running on a WebServer?

**Comment by Jagadeesh-MSFT** [comment]
Hi @Grunge, here is the documentation for [deploying the App](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/serve-your-web-part-in-a-sharepoint-page).

**Comment by Jagadeesh-MSFT** [comment]
Hi @Grunge, we can deploy our application in azure from there we can use.

**Comment by Grunge** [comment]
Very good, please add the description how to add it to azure. Thank you very much and Good Luck to you and your family.

**Comment by Jagadeesh-MSFT** [comment]
Hi @Grunge, do you want the document should be updated ? now are you able to build your application ?
