### ISSUE TITLE
can't request the device permission

### ISSUE THREAD

**Issue by chenxizhang** [MicrosoftDocs/msteams-docs#3224]
[Enter feedback here]
I try to request the media permission for my app, follow the doc I can't see any prompt to request the permission, And I can't see the "App permissions" menu on the mobile app.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19804dba-009f-2eb1-cc7f-1e0fabbebb6b
* Version Independent ID: a9373e78-b3c9-7182-d253-5ac8d8988936
* Content: [Request device permissions for your Microsoft Teams app - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?tabs=desktop)
* Content Source: [msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/device-capabilities/native-device-permissions.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Mamatha-MSFT** [comment]
Hi @chenxizhang  I am able to repro the issue. Taking this for internal discussion with team, I will update you with resolution.

**Comment by Mamatha-MSFT** [comment]
@chenxizhang  could you please explain which device permission are you using and also share the code snippets?

**Comment by chenxizhang** [comment]
> @chenxizhang could you please explain which device permission are you using and also share the code snippets?

I've solved this problem, so thank you all, and I will close this issue.
