### ISSUE TITLE
Add High Contrast theme(s) to the Designer 

### ISSUE THREAD

**Issue by jonmill** [MicrosoftDocs/msteams-docs#3230]
Issue ported from Adaptive Cards repo, initial opened by @josverl in issue https://github.com/microsoft/AdaptiveCards/issues/5761

In order to make sure that cards are clearly legible and accessible I would like so see a (Teams) High contrast theme in the editor,
This would allow cards be designed with accessibility in mind from the start , and would lessen the amount of re-work than needs to be done when accessibility issues may only be found in testing.

I think this is more important then preferences for either light or dark themes.
I think it should not be much effort to include one additional HostConfig based on an existing client such as Teams.

**Comment by Jagadeesh-MSFT** [comment]
Hi @jonmill/ @josverl, we are checking this with our internal team, will update you soon.

**Comment by Jagadeesh-MSFT** [comment]
Hi @jonmill/ @Josverl, As this feature is not available at present, could you please raise an [User Voice](https://microsoftteams.uservoice.com) if this needs to be consider as a future request.

**Comment by Josverl** [comment]
@Jagadeesh-MSFT, The feature request is not for Teams , the issue/request I submitted is actually for the AdaptiveCards Team with a suggestion to use the Teams High Contrast theme as an option. 

per your request I have submitted to [uservoice](https://microsoftteams.uservoice.com/forums/555103-public/suggestions/43495434-allow-developers-to-build-and-test-adaptive-cards) as well, although I personally do not think that is the most effective routing.
