### ISSUE TITLE
Adaptive card Input.Choice set placeholder not rendering on iOS

### ISSUE THREAD

**Issue by jonmill** [MicrosoftDocs/msteams-docs#3232]
Migrated from Adaptive Cards; initially opened by @TheBluLion in issue https://github.com/microsoft/AdaptiveCards/issues/5762

# Target Platform

Please list the platform(s) that your application is targeting and remove platforms you are not targeting:
- iOS

# Target Application

MSTeams

# Problem Description

When adaptive card JSON below is posted by a bot, the card renders correctly on Teams desktop and web clients but provides an inconsistent experience on Android, and a blank card on iOS. 

If JSON payload is updated with different ordering and v1.0 card, card is displayed correctly in three locations with consistent experience. 

# Screenshot

Expected render (correctly displayed on desktop)
![image](https://user-images.githubusercontent.com/41968802/117023242-87f9f080-acbe-11eb-91b7-630815763e07.png)

Blank card on iOS
![image](https://user-images.githubusercontent.com/41968802/117020682-4a946380-acbc-11eb-971d-5cb1d42e32f0.png)

# Card JSON

```
{
	"type": "AdaptiveCard",
	"body": [
	{
	"type": "Input.Text",
	"placeholder": "Enter your name",
	"isVisible": false,
	"value": "Test",
	"id": "userName"
	},
	{
	"type": "TextBlock",
	"weight": "Bolder",
	"text": "Title Text:",
	"wrap": true
	},
	{
	"type": "Input.ChoiceSet",
	"choices": [
	{
	"title": "Choice 1",
	"value": "Choice 1"
	},
	{
	"title": "Choice 2",
	"value": "Choice 2"
	}
	],
	"placeholder": "Placeholder text",
	"isMultiSelect":true,
	"id": "PlaceholderID"
	},
	{
	"type": "ActionSet",
	"actions": [
	{
	"type": "Action.Submit",
	"title": "Submit"
	}
	]
	}
	],
	"$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
	"version": "1.2"
	}


```
# Sample Code

Please provide any relevant code samples to help reproduce the issue

Corrected card json and expected render added here for context

```
{
    "type": "AdaptiveCard",
    "body": [
        {
            "type": "TextBlock",
            "weight": "Bolder",
            "text": "This guideline helped me in the following decision support (Check all that apply):",
            "wrap": true
        },
        {
            "type": "Input.ChoiceSet",
            "placeholder": "Select at least one",
            "choices": [
                {
                    "title": "Choice 1",
                    "value": "Choice 1"
                },
                {
                    "title": "Choice 2",
                    "value": "Choice 2"
                }
            ],
            "id": "ChoiceID",
            "isMultiSelect": true
        }
    ],
    "actions": [
        {
            "id": "Submitbtn",
            "type": "Action.Submit",
            "title": "Submit"
        }
    ],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.0"
}
```

iOS render (expected)

![image](https://user-images.githubusercontent.com/41968802/117023543-d1e2d680-acbe-11eb-8eb5-f56a18c1952b.png)

# Version of SDK

Bot Composer Framework v 1.4.0

**Comment by Sridevi-MSFT** [comment]
@jonmill - Thanks for bringing up this issue, I will repro at my end and will let you know.

**Comment by Sridevi-MSFT** [comment]
@jonmill -We have raised a bug for this issue, concerned engineering team is working on it.

**Comment by Sridevi-MSFT** [comment]
@jonmill -  If isVisible property is removed from the Input.Text here, this card renders fine.
isVisible  issue will be fixed in the next SDK update.
