### ISSUE TITLE
JS DOM beforeunload events stop links from working

### ISSUE THREAD

**Issue by iComputer7** [MicrosoftDocs/msteams-docs#3245]
Microsoft Teams Desktop version 1.4.00.8872
User agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Teams/1.4.00.8872 Chrome/80.0.3987.163 Electron/8.5.5 Safari/537.36`

My application is a website that has been added as a tab to a team.
Dependencies: 
* Bootstrap version 4.6.0
* Popper.js version 1.16.1
* JQuery version 3.6.0

Relevant code from my website:
`    window.addEventListener("beforeunload", (e) => {
        e.preventDefault();
        e.returnValue = "";
    });`

After the event listener is added, all links that navigate to another page stop functioning. I think this might be due to Teams not displaying a confirmation box like Chrome does when there is a beforeunload event present.

**Comment by Sridevi-MSFT** [comment]
@iComputer7 - Thank you for the insights. will repro at our end and will let you know.

**Comment by iComputer7** [comment]
I was able to boil the event code down to its bare essentials and came up with this:
https://gist.github.com/iComputer7/e456b8ba0c5db14313e74686c3812252

All of the links work before the beforeunload event is set. While the event is set, any links that try to navigate to another page stop functioning. Links that have an onclick event or `javascript:` links still function. When the beforeunload event is removed, all links are functional again and will navigate to another page.

**Comment by iComputer7** [comment]
I noticed that Teams updated recently, and the bug is still present. Version is `Teams/1.4.00.11161`

**Comment by Sridevi-MSFT** [comment]
@iComputer7 - I have reproduced the same code that has been provided and able to repro the issue. Will be raising the same as bug if it's get confirmed from internal team and will inform you as soon as possible.

**Comment by Sridevi-MSFT** [comment]
@iComputer7 -Microsoft Team SDK have  microsoftTeams.registerBeforeUnloadHandler() method to use it in their tab content pages.

**Comment by iComputer7** [comment]
I'm not sure what you mean

**Comment by Sridevi-MSFT** [comment]
@iComputer7 - Teams won't support many JS events. So, you can use microsoftTeams.registerBeforeUnloadHandler() event in your teams tab instead of beforeunload event.
