### ISSUE TITLE
Sideloading doesn't work

### ISSUE THREAD

**Issue by bonjo** [MicrosoftDocs/msteams-docs#3246]
Hi folks
I'm following this tutorial but at the moment to sideloading the app i have the following error.
![image](https://user-images.githubusercontent.com/362653/117191630-64aa7080-ada6-11eb-8821-05c144e8c80a.png)
And in the debug console of VS Code
{message: '', status: 400, errorCode: 'CreateUserAppDefinitionFailed'}

Mi development environment is

VS Code: 1.55.2 (user setup)
Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
Date: 2021-04-13T09:35:57.887Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

Do you have any idea?
Regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f876156-cc1e-468f-4647-5143a5de03b1
* Version Independent ID: 618f43a3-3371-ad99-13aa-087b9303298c
* Content: [Get started - Build and run your first app - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/build-your-first-app/build-and-run?tabs=do-not-have-a-tenant)
* Content Source: [msteams-platform/build-your-first-app/build-and-run.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/build-your-first-app/build-and-run.md)
* Product: **msteams**
* GitHub Login: @girliemac
* Microsoft Alias: **timura**

**Comment by Nikitha-MSFT** [comment]
We are not able to repro the issue at our end could you please share your manifest?

**Comment by bonjo** [comment]
Hi @Nikitha-MSFT 
This is the content of my manifest.json
Thank you for your help.

{
    "$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.8/MicrosoftTeams.schema.json",
    "manifestVersion": "1.8",
    "version": "1.0.0",
    "id": "16a4aacf-4de1-4fde-8e1e-4d7b80807303",
    "packageName": "com.microsoft.teams.extension",
    "developer": {
        "name": "Teams App, Inc.",
        "websiteUrl": "https://localhost:3000",
        "privacyUrl": "https://localhost:3000/privacy",
        "termsOfUseUrl": "https://localhost:3000/termsofuse"
    },
    "icons": {
        "color": "color.png",
        "outline": "outline.png"
    },
    "name": {
        "short": "RRQ",
        "full": ""
    },
    "description": {
        "short": "Short description for Personal App.",
        "full": "Full description of Personal App."
    },
    "accentColor": "#FFFFFF",
    "staticTabs": [
        {
            "entityId": "index",
            "name": "Personal Tab",
            "contentUrl": "https://localhost:3000/tab",
            "websiteUrl": "https://localhost:3000/tab",
            "scopes": [
                "personal"
            ]
        }
    ],
    "permissions": [
        "identity",
        "messageTeamMembers"
    ],
    "validDomains": [
        "localhost",
        "localhost:3000"
    ]
}

**Comment by Nikitha-MSFT** [comment]
We am not able to repro the issue at our end. we are able to upload the manifest success fully. Here is the screen shot:
![image](https://user-images.githubusercontent.com/61688740/117809848-4c41c680-b27c-11eb-9b99-4f253815774f.png)
Here is the uploaded manifest
[manifest.zip](https://github.com/MicrosoftDocs/msteams-docs/files/6458878/manifest.zip)
