### ISSUE TITLE
Conversations not showing in Mac desktop app

### ISSUE THREAD

**Issue by JesusPenafiel** [MicrosoftDocs/msteams-docs#3248]
Conversations are not showing in the Mac desktop app, I can see the preview on the feed, but when I click on any of them the post page appears blank, and I cannot read the message, even if I post a new conversation it won't apper.  It also happens if I go directly to the channel conversation tab It appears that there are no messages.   If I use the web version of the app everything is working correctly. 
Attached is a screen shot with both desktop app and web app showing the error. 

![Screen Shot 2021-05-06 at 10 17 41](https://user-images.githubusercontent.com/83775306/117324283-45b6e780-ae55-11eb-9116-2449212f3abd.png)

**Comment by v-chetsh** [comment]
@JesusPenafiel - Could you please confirm if your issue has resolved or still looking for any help?
