### ISSUE TITLE
in the array, if i have an existing..

### ISSUE THREAD

**Issue by seaSide974** [MicrosoftDocs/msteams-docs#325]
you could add with SPFX 1.7 
"if i have an existing..."
=&gt; Sharepoint webpart SPFX 1.7,

In teams It can be a Tab

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: d160926a-58af-cf0a-bc9d-f9490d04be36
* Version Independent ID: e729fb32-86b3-ceca-3a66-639176e515bc
* Content: [Design apps for Microsoft Teams - Teams](https://docs.microsoft.com/fr-fr/microsoftteams/platform/concepts/apps/apps-design)
* Content Source: [msteams-platform/concepts/apps/apps-design.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/apps/apps-design.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Wajeed-msft** [comment]
@seaSide974 - Are you facing any issue with Tab? Could you please elaborate your issue?
