### ISSUE TITLE
Update Last Modified Date of this page

### ISSUE THREAD

**Issue by GauravES** [MicrosoftDocs/msteams-docs#3253]
[Enter feedback here]
The Configurable Properties section of this document seemed to have only been launched in April 2021 but doc date is still from 2019 so it is confusing.

(i.e https://docs.microsoft.com/en-us/MicrosoftTeams/customize-apps was launched in 2021 and the Configurable Properties section is for this capability)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b449c9ba-a94c-4012-4721-cee5f87eeb8a
* Version Independent ID: b2536bbc-eb27-547d-d7f5-bab3ded3bedf
* Content: [Developer Preview Manifest schema reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema-dev-preview)
* Content Source: [msteams-platform/resources/schema/manifest-schema-dev-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/resources/schema/manifest-schema-dev-preview.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Nikitha-MSFT** [comment]
@GauravES - What is confusing in the document - what need to update here? Could you please share more details on what need to be update in the document.

**Comment by Nikitha-MSFT** [comment]
Please reopen the issue with the required details. Closing the issue as of now
