### ISSUE TITLE
microsoftTeams.converstations has no meaningful documentation 

### ISSUE THREAD

**Issue by smchargue** [MicrosoftDocs/msteams-docs#3260]
How in the world are you supposed to learn anything about using microsoftTeams.converstations from the information provided here. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d120eb51-2f23-c875-9b2d-3b1f098671fe
* Version Independent ID: 2cd41da2-60f5-a0ba-e9f1-daa1ff09e634
* Content: [conversations module - Teams](https://docs.microsoft.com/en-us/javascript/api/@microsoft/teams-js/conversations?view=msteams-client-js-latest)
* Content Source: [nodejs/docs-ref-autogen/@microsoft/teams-js/conversations.yml](https://github.com/OfficeDev/msteams-client-docs-ref-typescript/blob/live/nodejs/docs-ref-autogen/@microsoft/teams-js/conversations.yml)
* Product: **msteams**
* GitHub Login: @charlesprakash
* Microsoft Alias: **o365devx**

**Comment by Jagadeesh-MSFT** [comment]
Hi @smchargue , we are checking with our internal team, will update you soon.

**Comment by Jagadeesh-MSFT** [comment]
Hi @smchargue, you can check [this ](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bot-conversations/bots-conversations)document for microsoftTeams.converstations

**Comment by smchargue** [comment]
Thanks. That’s helpful but I guess I was asking the wrong question.  Not interested in bots.  Wanted to start a chat with a person from my custom teams app I’m building.   What I really want to do is open a user profile card in my app by clicking on the name in a list.  just like you would do in chat.  Is there an api for that that you know of?

**Comment by smchargue** [comment]
Issue about conversations is closed though.  Thanks for the response.
