### ISSUE TITLE
Bot Framework SDK versions are wrong on this page

### ISSUE THREAD

**Issue by clearab** [MicrosoftDocs/msteams-docs#3268]
The current latest version of the bot framework SDK is 4.13.1 - I recommend removing references to specific "latest" versions, as the SDK is updated ~4-5 times a year.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c780d605-b1b2-716f-5888-503608769b5a
* Version Independent ID: 53c724f8-d9a2-4af6-6d75-ddeaef084137
* Content: [Bot API changes for team and chat members - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/team-chat-member-api-changes)
* Content Source: [msteams-platform/resources/team-chat-member-api-changes.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/resources/team-chat-member-api-changes.md)
* Product: **msteams**
* GitHub Login: @ojasvichoudhary
* Microsoft Alias: **ojchoudh**

**Comment by Sridevi-MSFT** [comment]
@clearab -  Could you please refer us exact documentation link where we have make changes.

**Comment by clearab** [comment]
Its the page linked in the Issue above ⬆️ . This page contains references to specific versions of the SDK, and should instead just say something like "later than version 4.8"
