### ISSUE TITLE
Images sent through web hook are not expanding even afte setting allowExpand as True. 

### ISSUE THREAD

**Issue by abhineshada** [MicrosoftDocs/msteams-docs#3279]
We are using web hook to share some images in teams channels. But, the images are not expandable in Teams desktop client or web browser. However it is working fine in mobile app. Tried enabling allowExpand but nothing worked. 

Is the 'allowExpand' feature not yet released in production? 

Sample JSON: 
`{
  "attachments": [
    {
      "content": {
        "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
        "body": [
          {
            "items": [
              {
                "horizontalAlignment": "Center",
                "msTeams": {
                  "allowExpand": true
                },
                "separator": true,
                "type": "Image",
                "url": "https://4rpm16vw6eyxvm4z05tvv4yr.blob.core.windows.net/99fpycl6ri99x2f/1000.png"
              }
            ],
            "type": "Container"
          }
        ],
        "type": "AdaptiveCard",
        "version": "1.2"
      },
      "contentType": "application/vnd.microsoft.card.adaptive",
      "contentUrl": null
    }],"type": "message"}`

**Comment by Mamatha-MSFT** [comment]
Hi @abhineshada - I have reproduced the same code that you have provided. I am unable to repro the issue. The image is expanding as expected. 
![image](https://user-images.githubusercontent.com/78795357/117940639-e6f6df80-b326-11eb-9a45-039a34482147.png)

**Comment by abhineshada** [comment]
Hi @Mamatha-MSFT Can you please confirm if you are testing this in dev mode or in production app. Also, please let me know which OS are you testing this on? I am testing it on MacOS and nothing seems to work here.

**Comment by Mamatha-MSFT** [comment]
@abhineshada - I am testing it in windows Teams desktop client. Could you please share the MacOS version details and Teams version details.

**Comment by abhineshada** [comment]
@Mamatha-MSFT 
MacOS version: Big Sur (11.2.3) 
Microsoft Teams Version 1.4.00.8872.

**Comment by abhineshada** [comment]
@Mamatha-MSFT Were you able to check the issue on MacOS? This is becoming a blocker for us. Let me know if there is any workaround for this. Our use case is : automated sharing of images in Teams channels on some scheduled time interval. 
But as most of users are on Mac OS, we can not move ahead if users are not able to enlarge/expand/zoom the image as these images have tabular data, numbers, metrics. It works fine if we upload an image manually.

**Comment by abhineshada** [comment]
@Mamatha-MSFT I am facing the same issue in windows machine as well. Can you please confirm if you tested this in dev mode or production and the feature is live in prod or not.

**Comment by Mamatha-MSFT** [comment]
Hi @abhineshada It is working only in developer preview. This feature is not yet documented. Will check this with internal team and get back to you.

**Comment by abhineshada** [comment]
@Mamatha-MSFT Thanks for the update. It would be a great help if you could confirm when the feature will be made live in prod app.

**Comment by Mamatha-MSFT** [comment]
@abhineshada -**`allowExoand`** will be enabled in R4 next week.
