### ISSUE TITLE
Invalid appId specified error Messaging Extension

### ISSUE THREAD

**Issue by YPillay** [MicrosoftDocs/msteams-docs#3280]
I created Messaging Extension search which I populate the results with thumbnail cards with 1-6 buttons depending on the context.
The buttons don't work consistently and I get the error when copying from the preview as well as clicking the buttons.

AppsService: getInstalledAppForUser - Invalid appId specified

**Comment by YPillay** [comment]
Further information, The issue occurs in my test environment where I install the app via a zip as well as where the app is available from the store(For my Org)

**Comment by Mamatha-MSFT** [comment]
@YPillay - Could you please try this [sample ](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/50.teams-messaging-extensions-search)code. 
For buttons which action method are you using, explain briefly.

**Comment by YPillay** [comment]
> @YPillay - Could you please try this [sample ](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/50.teams-messaging-extensions-search)code.
> For buttons which action method are you using, explain briefly.

I am using a CardAction list with type = "invoke".
I have used the sample code referenced previously and it works as intended.

**Comment by YPillay** [comment]
`
ThumbnailCard card = new ThumbnailCard();
            List<CardAction> buttons = new List<CardAction>();
            foreach (item in SomeList)
            {
                buttons.Add(new CardAction { Type = "invoke", Value = new CardTaskFetchValue<string> { Data =  "data"  }, Title = "title"});
            }

            card = new ThumbnailCard
            {
                Title = CommonName,
                Buttons = buttons
            };

            var attachment = new MessagingExtensionAttachment
            {

                ContentType = ThumbnailCard.ContentType,
                Content = card

            };
`

**Comment by Mamatha-MSFT** [comment]
@YPillay Could you please share the screen recording of your issue. So that it helps me to check where exactly your facing the issue.

**Comment by Mamatha-MSFT** [comment]
@YPillay If you are still facing the issue then please share the screen recording.

**Comment by YPillay** [comment]
@Mamatha-MSFT Yes, Will share shortly

**Comment by YPillay** [comment]
![image](https://user-images.githubusercontent.com/28230656/118466256-f7320480-b702-11eb-86a7-85d916c0d3cd.png)

**Comment by Mamatha-MSFT** [comment]
@YPillay Could you please share the screen recording of when you're trying it in messaging extension so that we can clearly understand what is the exact issue.

**Comment by YPillay** [comment]
![Animation](https://user-images.githubusercontent.com/28230656/118471120-af61ac00-b707-11eb-8f26-7f7b389a2ba4.gif)

**Comment by Mamatha-MSFT** [comment]
@YPillay - We are able to repro the issue. But that error does not effect the functionality. I am able to copy the the card from preview mode. We will raise a bug for this issue. 

For buttons, the `invoke `action will not work in preview mode, but it will work in chat. only `open URL` action will work in preview.

**Comment by YPillay** [comment]
@Mamatha-MSFT Great, But I have encountered that the buttons do not work consistently.
Sometimes when I click them they generate no event and sometimes they do.

**Comment by Mamatha-MSFT** [comment]
@YPillay - The invoke action will send message but it will not display in chat and will sends payload to the bot. To handle invoke action in message extension use below code .

```
 protected override async Task OnTeamsMessagingExtensionCardButtonClickedAsync(ITurnContext<IInvokeActivity> turnContext, JObject obj, CancellationToken cancellationToken)
        {       
                 var reply = MessageFactory.Text("OnTeamsMessagingExtensionCardButtonClickedAsync Value: " + JsonConvert.SerializeObject(turnContext.Activity.Value));
            await turnContext.SendActivityAsync(reply, cancellationToken);
        }
```
