### ISSUE TITLE
Teams UI Toolkit: sample app in App Studio doesn't work 

### ISSUE THREAD

**Issue by LuiseFreese** [MicrosoftDocs/msteams-docs#3285]
in App Studio in Teams, I wanted to install the sample app of Teams UI Toolkit to Teams with the **Install to Teams** button,

![image](https://user-images.githubusercontent.com/49960482/118010098-fb4ed280-b34e-11eb-833a-09f3f737d6c0.png)
but I get this error message: "We're sorry. We couldn't prepare your sample app. Please try again later". 
 
Tried later, several times, in different tenants, same result. 
![image](https://user-images.githubusercontent.com/49960482/118010139-06096780-b34f-11eb-94fa-08a639b0fd43.png)

**Comment by Nikitha-MSFT** [comment]
@LuiseFreese  Which template you are trying to install using the sample app? Could you please repro steps and app template you are trying to install?

**Comment by LuiseFreese** [comment]
1. Open Teams
2. Open App Studio
3. Select **UI Tools** 
4. Select **Install to Teams** right below **Sample App**

I get the error message that I screenshotted. Can you confirm?

**Comment by Nikitha-MSFT** [comment]
Which template you are trying to install using the sample app?
