### ISSUE TITLE
isFullScreen is not respected from side loaded app

### ISSUE THREAD

**Issue by dastewa** [MicrosoftDocs/msteams-docs#3286]
Please document that isFullScreen does not work with apps that have been side-loaded from the Teams client.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f94a488-d636-92b3-21eb-c88744c8f272
* Version Independent ID: 7b3413f4-9ade-accf-5cb2-83fead11a32a
* Content: [Manifest schema reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema)
* Content Source: [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/resources/schema/manifest-schema.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Sridevi-MSFT** [comment]
@dastewa - isFullScreen is working as expected while side-loaded from the Teams client. Could you explain where exactly your facing this issue like in desktop client/ Web application.

**Comment by Sridevi-MSFT** [comment]
@dastewa - Please provide the above mentioned details if your are still facing the issue.
