### ISSUE TITLE
Use of OAuthCard in chat unnecessary? 

### ISSUE THREAD

**Issue by fowl2** [MicrosoftDocs/msteams-docs#329]
There is enough information available to find a user in AAD in the `TeamsChannelAccount` object without having to implement all this. AAD Directory/Tenant Id is in `Properties`.

Perhaps the documentation could mention this somehow?

Unless perhaps it can be spoofed - in which case that should be documented too! =)

Thanks

Example (for a bot using LUIS):
```
        [LuisIntent("Greetings")]
        public async Task GreetingsIntent(IDialogContext context, IAwaitable<IMessageActivity> activityAwaitable, LuisResult result)
        {
            var activity = await activityAwaitable;

            var connector = new ConnectorClient(new Uri(activity.ServiceUrl));
            var memberAccounts = await connector.Conversations.GetActivityMembersAsync(activity.Conversation.Id, activity.Id);
            var fromMemberAccount = memberAccounts.AsTeamsChannelAccounts().First(o => o.Id == activity.From.Id);

            await context.PostAsync($"Hi {fromMemberAccount.GivenName}," +
                                   $"your UPN is {fromMemberAccount.UserPrincipalName}" +
                                   $"and AAD object id is {fromMemberAccount.ObjectId}");
        }
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7c810ce-b432-9135-16ee-55f461a10e78
* Version Independent ID: 70c7c1a0-b5b0-599f-a0b2-ea3e343df227
* Content: [Using the OAuthCard for authentication - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/authentication/auth-oauth-card)
* Content Source: [msteams-platform/concepts/authentication/auth-oauth-card.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/authentication/auth-oauth-card.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Wajeed-msft** [comment]
@fowl2 - If you need only information available in roaster then you don't need to use OAuthCard. If you are using something which is not provided in roaster like jobTitle, profile photo etc then you can use OAuthCard to sign in and fetch the details using [Graph API call](https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/user_get). Also, while sign in you can optionally request for various [permissions](https://developer.microsoft.com/en-us/graph/docs/concepts/permissions_reference) which gives access to respective AD resource.

**Comment by fowl2** [comment]
Good point. In our case we're using app-only Graph API calls w/ admin consent so it's much more streamlined for the end user.
