### ISSUE TITLE
Microsoft Team SSO in Personal tab with Authentication and authorization (Easy Auth)

### ISSUE THREAD

**Issue by Kristoffer88** [MicrosoftDocs/msteams-docs#3291]
Hi.

I am trying to get SSO working with  Authentication and authorization,
I have set my webapp to following authentication settings:
Require authentication
Unauthenticated requests
Return HTTP 302 Found (Redirect to identity provider)

It works perfectly in teams browser and mobile, but in desktop, it does not work.

Inside App registration i have followed the Single Sign On documentation and it seemed to work, when clearing my Microsoft Teams cache, it give me a iframe redirect error:

Refused to display 'https://login.microsoftonline.com/[TENANTID]/oauth2/v2.0/authorize?response_type=code+id_token&redirect_uri=https%3A%2F%2Fxxxxx.azurewebsites.net%2F.auth%2Flogin%2Faad%2Fcallback&client_id=xxxxxxx&scope=openid+profile+email&response_mode=form_post&nonce=xxxx&state=redir%3D%252F' in a frame because it set 'X-Frame-Options' to 'deny'.

It works if i login to the website in another way in teams (like from a Teams Channel Webview) and then access my Personal tab

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52221dd3-95ec-96b9-1da8-9478527c2602
* Version Independent ID: 32e9c2d8-733d-0865-2ea3-727d8684a10d
* Content: [Single sign-on support for tabs - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-aad-sso)
* Content Source: [msteams-platform/tabs/how-to/authentication/auth-aad-sso.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tabs/how-to/authentication/auth-aad-sso.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Jagadeesh-MSFT** [comment]
Hi @Kristoffer88, we are working on it, will update you soon.

**Comment by Nikitha-MSFT** [comment]
Is your personal tab is Iframable? Currently teams support only Iframable pages. Could you please conform?

**Comment by Kristoffer88** [comment]
Hi.

Is it a setting in teams? I am not sure i understand your question

My example is just a Azure Web App with App Service Authentication / Authorization turned on. With always authenticate on. There is no custom code added to the web app. I do not get redirected to the login screen, as i should with always authenticate on.

**Comment by Kristoffer88** [comment]
This seems to be triggered by clearing of the teams cache. If i clear the cache, then restart teams, it seems to work fine. It is only the first load of the app, after clearing the cache, that is triggering the "bug"

**Comment by Jagadeesh-MSFT** [comment]
Hi @Kristoffer88, could you please try with other [authentication ](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-flow-tab)methods, for sso its by-design.
