### ISSUE TITLE
Need for token exchange is not clear

### ISSUE THREAD

**Issue by BobGerman** [MicrosoftDocs/msteams-docs#3293]
The document gives the impression that exchanging the SSO token for an access token is optional, and really doesn't make the need clear to the reader. (The token exchange is needed in the vast majority of cases). Further, the doc implies that admin consent will solve the problem, but really that just removes the need to prompt the user for consent.

I'm looking for an authoritative doc to site from an article and find myself referencing blog articles from the community instead because they don't omit this key step. It really does confuse people; I've heled quite a number of people figure this out one at a time but it doesn't scale as well as providing complete documentation.

Is there a way to update this? Glad to help!

Examples of more complete writeups:
- https://blog.mastykarz.nl/securely-connect-microsoft-graph-teams-tabs-sso/
- https://www.wictorwilen.se/blog/microsoft-teams-tabs-sso-and-microsoft-graph-the-on-behalf-of-blog-post/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52221dd3-95ec-96b9-1da8-9478527c2602
* Version Independent ID: 32e9c2d8-733d-0865-2ea3-727d8684a10d
* Content: [Single sign-on support for tabs - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-aad-sso)
* Content Source: [msteams-platform/tabs/how-to/authentication/auth-aad-sso.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tabs/how-to/authentication/auth-aad-sso.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Wajeed-msft** [comment]
@BobGerman - 
> The doc implies that admin consent will solve the problem, but really that just removes the need to prompt the user for consent.

We have included details on on-behalf-of flow in [this section](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-aad-sso#ask-for-additional-consent-using-the-auth-api). Do you feel we should merge it with main flow? 



If you like to make specific edits, you can do it by selecting edit on the documentation page. 
![image](https://user-images.githubusercontent.com/31851992/124423355-97f78480-dd82-11eb-8350-eaee46df57bb.png)

**Comment by surbhigupta12** [comment]
@BobGerman, a gentle reminder on this.

**Comment by surbhigupta12** [comment]
@BobGerman,  gentle reminder on this.
