### ISSUE TITLE
Conflicts with Advice for  SSO for Bot/Static Web Tabs

### ISSUE THREAD

**Issue by GauravES** [MicrosoftDocs/msteams-docs#3295]
[Enter feedback here]

> To use these permissions, you must add a webApplicationInfo key to your app manifest with the following values:

We have an existing bot with a static web tab that uses SSO.  Microsoft instructions for using SSO recommends creating a dedicated "identity" app with the required permissions to interact with the Graph, rather than using the Bot's own app ID to interact with the Graph.  See advice in https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-authentication?view=azure-bot-service-4.0&tabs=aadv2%2Ccsharp

This requires the manifest to have a webApplicationInfo section which includes the app ID and resource of the identity app.

However the Self Install instructions require the bot manifest to have a webApplicationInfo section, but this time the app id should be the bot's own app ID.

To my knowledge, the manifest can have a single webApplicationInfo section.  How do we specify two apps?  One for Identity/SSO and another just for Self Install.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 893c2c9e-10e1-dd4e-1eb4-b4e9a46a9f8d
* Version Independent ID: 5f41c382-377c-6c9b-4932-65853675c4ad
* Content: [Use Microsoft Graph to authorize proactive bot installation and messaging in Teams - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/graph-api/proactive-bots-and-messages/graph-proactive-bots-and-messages?tabs=csharp)
* Content Source: [msteams-platform/graph-api/proactive-bots-and-messages/graph-proactive-bots-and-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/graph-api/proactive-bots-and-messages/graph-proactive-bots-and-messages.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Jagadeesh-MSFT** [comment]
Hi @GauravES, we are working on it , will update you soon.

**Comment by Jagadeesh-MSFT** [comment]
Hi @GauravES, If you are building an app with a bot and a tab, enter the Application ID URI as api://fully-qualified-domain-name.com/botid-{YourBotId}.
