### ISSUE TITLE
Cannot create webhook connector

### ISSUE THREAD

**Issue by ReddragonLR** [MicrosoftDocs/msteams-docs#3297]
Hi

Hope you are well. I have tried numerous times to create a an Incoming Connector Webhook but keep getting the following error

<img width="520" alt="Screenshot 2021-05-16 at 15 20 22" src="https://user-images.githubusercontent.com/2574856/118398859-b1216600-b65a-11eb-9995-7368cb0abff0.png">

No luck on multiple attempts, both with and without uploading of an image

**Comment by Jagadeesh-MSFT** [comment]
Hi @ReddragonLR, could you please try [incoming webhook](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-incoming-webhook) document, it explains creating incoming webhook.

**Comment by patelbharat001** [comment]
@Jagadeesh-MSFT 
I am also facing the same issue,
I have created a new team and in that, I tried removing permission and adding the permission for incoming webhook as you mentioned.
but it doesn't work and still giving an error as Something went wrong.

**Comment by Jagadeesh-MSFT** [comment]
Hi @ReddragonLR/ @patelbharat001, Looks to be user specific issue as no repro on our side, Could you please help with getting the network/HAR capture for the repro to help with the investigation?

**Comment by ReddragonLR** [comment]
@Jagadeesh-MSFT - Hi. I have tried again and was able to create the webhook connector without error this time around

Thank you for your time. Apologies if the search yielded wasted time. I was consistently getting errors before but today it worked

<img width="510" alt="Screenshot 2021-05-27 at 22 04 17" src="https://user-images.githubusercontent.com/2574856/119890066-a5298400-bf37-11eb-88f5-43548bd47286.png">
