### ISSUE TITLE
I should use yeoman or vscode teams toolkit to build teams app

### ISSUE THREAD

**Issue by quantrpeter** [MicrosoftDocs/msteams-docs#3298]
Hi
   I should use yeoman or vscode teams toolkit to build teams app?
thanks
Peter

**Comment by Mamatha-MSFT** [comment]
Hi @quantrpeter - You can create bot using  both yeoman and vscode teams toolkit. 
Please follow this [documentation](https://docs.microsoft.com/en-us/microsoftteams/platform/tutorials/get-started-yeoman) for creating bot using yeoman generator and for vscode teams toolkit go through [this](https://docs.microsoft.com/en-us/microsoftteams/platform/build-your-first-app/build-bot).
