### ISSUE TITLE
UI bug with options covering messages so you can't copy

### ISSUE THREAD

**Issue by harry-hathorn** [MicrosoftDocs/msteams-docs#330]
I have been using teams for 3 years now. One frustration is the difficulty of copying messages because the options drop down over a message preventing your cursor from highlighting text for copying.

e.g.
I would like to copy the text below
![image](https://user-images.githubusercontent.com/25703773/48836247-dafbb980-ed8a-11e8-9a98-ddaf75d530f9.png)

However I am unable to do so because it is covered by the options when i hover my mouse over:

![image](https://user-images.githubusercontent.com/25703773/48836281-f23aa700-ed8a-11e8-8aee-51feee4dd328.png)

**Comment by Wajeed-msft** [comment]
@harry-hathorn - Thanks for reporting. I have filed a bug for this.

**Comment by Jonyder** [comment]
Yes, I'm experiencing the same issue, super annoying, please crush this one.
MS Teams: 1.1.00.31953
MacOS 10.14.2
