### ISSUE TITLE
How to send a proactive message to a user after retrieving the chatid

### ISSUE THREAD

**Issue by GauravES** [MicrosoftDocs/msteams-docs#3302]
[Enter feedback here]
Per this document, GET https://graph.microsoft.com/beta/users/{user-id}/teamwork/installedApps/{teamsAppInstallationId}/chat will get the chatid, however it appears there is no way to send a 1:1 message FROM the bot to the user using this chatid?

The documentation for the https://docs.microsoft.com/en-us/graph/api/chat-post-messages?view=graph-rest-1.0&tabs=http   specifies that delegated permissions are needed to send a  message.  A Delegated permission implies the presence of a user, which defeats the purpose of proactive messaging in the first place, doesnt it?  Additionally, who would appear as the sender of such a message?  We need for the bot to appear as the sender in proactive messaging.

So, once an application desiring pro-active messaging has installed itself, and retrieved the chat id, how does it actually send a 1:1 message using graph?  If there is a way then the document should be updated to reflect that.

(I am aware of the Bot Framework Approach, where we wait for a memberadded event, after app installation,  to capture the Bot Framework specific ID to send a message, but that event could be lost or not captured for various reasons)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 893c2c9e-10e1-dd4e-1eb4-b4e9a46a9f8d
* Version Independent ID: 5f41c382-377c-6c9b-4932-65853675c4ad
* Content: [Use Microsoft Graph to authorize proactive bot installation and messaging in Teams - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/graph-api/proactive-bots-and-messages/graph-proactive-bots-and-messages)
* Content Source: [msteams-platform/graph-api/proactive-bots-and-messages/graph-proactive-bots-and-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/graph-api/proactive-bots-and-messages/graph-proactive-bots-and-messages.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Jagadeesh-MSFT** [comment]
Hi @GauravES, we are checking with our internal team, will update you soon.

**Comment by Jagadeesh-MSFT** [comment]
Hi @GauravES, If we send message using graph API, it will be shown sender as an user not a bot. So if you want bot as a sender we have to use [send proactive messaging](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-proactive-message?view=azure-bot-service-4.0&tabs=csharp&preserve-view=true), currently we don't have any alternative way to send 1:1 message from bot.

**Comment by GauravES** [comment]
The documentation leads up to steps to install the app, with a goal that the bot should be able to send  a message to the user who has previously not installed the app.   It then shows steps to  retrieve chatid, but it is really not usable then as this path (retrieval of chat id)  does not solve the issue of a bot sending a message to a new user.   The member added event is a hit or miss and can be easily lost, specially if bulk installing the app to  thousands of new users.

Suggest clarify this in the doc itself or add some additional guidance on how a bot can send messages as itself to an end user (even after it has permissions to install the app for end users).   Without this, it is not really "proactive messaging"

**Comment by Nikitha-MSFT** [comment]
To send a proactive message to user the bot requires the conversation reference. The conversation can be only retrieved when bot installed. Without conversation reference you cannot send a proactive message using bot. You can use [Send message in a chat](https://docs.microsoft.com/en-us/graph/api/chat-post-messages?view=graph-rest-1.0&tabs=http) API to send message to chat with delegated permissions. Could you please raise a [uservoice](https://microsoftteams.uservoice.com/forums/555103-public-preview/category/182881-developer-platform) for your case
