### ISSUE TITLE
Images from one channel to another copied with Flow.microsoft.com isn't shown to everyone. 

### ISSUE THREAD

**Issue by ghepip** [MicrosoftDocs/msteams-docs#331]
I've created a flow and used the default schematic from microsoft, so it's simply a matter of changing the teams and channels. 

Some of us can see the images copied from one channel to another.   
Others just get a grey image. 

Only difference is that those of us that can see the pictures were marked as owners of the channel before the picture and text was copied into it. 

How to replicate
Have two teams
Have one channel at least in each. 
Have a user be owner of each team
And antoher user be a member of each team

Set up a flow with:
When a new Channel-message is added (Example)
Send message (Example)

In "When" choose a team and a channel that your user is member of.
In "send" choose another team and the channel here that your user is member of. 

Post a picture with text and image in the first channel with either owner or member. 
The member will experience that in the channel copied too the picture is either grey if we use the application for Windows, and not appearing at all if using the mac version. 
The owner will see the picture if the picture was posted with the windows application and none if the mac version was used.

**Comment by arun-msft** [comment]
@ghepip We created bug for this issue and working with engg team.
