### ISSUE TITLE
Manifest version differences

### ISSUE THREAD

**Issue by OskarNet** [MicrosoftDocs/msteams-docs#3317]
Hi

I feel it's a bit unclear what has changed between versions of the manifest file.
Why isn't there a version history with changes linked on this page?

Regards,
Oskar

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f94a488-d636-92b3-21eb-c88744c8f272
* Version Independent ID: 7b3413f4-9ade-accf-5cb2-83fead11a32a
* Content: [Manifest schema reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema)
* Content Source: [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/resources/schema/manifest-schema.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Jagadeesh-MSFT** [comment]
Hi @OskarNet, Thank you for the insights on the document. We will ask document team to look into this and make the document better.
