### ISSUE TITLE
It isnt working :(

### ISSUE THREAD

**Issue by pk2068** [MicrosoftDocs/msteams-docs#333]
It does not work: When using command "Get some random text for fun" and pressing Enter, it starts loading but fails with the message "Something went wrong, try later" :(

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98cd21c7-e87c-3c5b-7574-998a355f9f08
* Version Independent ID: 5e312707-facc-03fc-af59-90267d0c7b8a
* Content: [Get started with C#/.NET - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/get-started/get-started-dotnet-app-studio)
* Content Source: [msteams-platform/get-started/get-started-dotnet-app-studio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/get-started/get-started-dotnet-app-studio.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by billbliss** [comment]
When you say “it” what do you mean?

**Comment by jg11jg** [comment]
cloned, opened in Visual Studio 2017 17.9.3.  Rebuild.  f5.  THen:
Could not find a part of the path 'C:\git\msteams-samples-hello-world-csharp\Microsoft.Teams.Samples.HelloWorld.Web\bin\roslyn\csc.exe'.

And indeed in the bin directory there is no roslyn subdirectory.

**Comment by jg11jg** [comment]
Fixed using this answer to this question (note: not the accepted answer, the "second" one, which is what I link to here). https://stackoverflow.com/a/34391473/6795110

**Comment by ovsleep** [comment]
Very helpful hello world example. But you're missing an important step on the bot setup: 
Set the "Bot endpoint address" to: https://[yourdomain].ngrok.io/api/messages 
Otherwise the bot and the messaging extension wont work. It took me an hour to figure it out.

**Comment by CameronDwyer** [comment]
I struck this issue as well. A clean and rebuild of the solution fixed it for me. I didn't need to change the version of any of the NuGet packages.

**Comment by ibigbug** [comment]
@jg11jg yes it worked for me
