### ISSUE TITLE
On disabling developer preview, all messaged in teams are lost. 

### ISSUE THREAD

**Issue by abhineshada** [MicrosoftDocs/msteams-docs#3332]
Hi,
I was testing image flow through web-hook. I was facing issue mentioned in #3279 so I enabled developer preview to test the feature. Now when I disable developer preview again, I am not able to see any of my messages. Please refer the screenshots. 

Kindly look into this and let me know how I can retrieve my messages again. 

<img width="755" alt="Screenshot 2021-05-19 at 8 11 37 PM" src="https://user-images.githubusercontent.com/12792834/118832644-6ca5fc80-b8de-11eb-8463-43b74b836593.png">
<img width="674" alt="Screenshot 2021-05-19 at 8 11 57 PM" src="https://user-images.githubusercontent.com/12792834/118832699-77f92800-b8de-11eb-9f35-494297ab98e5.png">

Please note that the messages are only lost in Team where I was testing web hook. I am able to see messages in other groups. 
Also, if I enable developer preview again, I am able to see the messages but they are gone once I disable it again.

**Comment by Jagadeesh-MSFT** [comment]
Hi @abhineshada, we are unable to repro your issue from our end , could you please try again and check if you are sill facing the issue.

**Comment by abhineshada** [comment]
@Jagadeesh-MSFT Thank you for looking into it. In our case, developer preview was disabled at org level initially. Once we enabled it and then started it in our apps, we were noticing this issue. 
However, on re-installing the app, we were able to see all the messages again in normal mode. 

This issue can be closed now.

**Comment by abhineshada** [comment]
Closing the issue.
