### ISSUE TITLE
Version 1.10 of the manifest not supported by App Studio App and many Teams tenants

### ISSUE THREAD

**Issue by GauravES** [MicrosoftDocs/msteams-docs#3333]
Version 1.10 of the manifest not supported by App Studio App and many Teams tenants

Is it possible to add a note to documentation when Manifest schema version is updated as to when the feature will be rolled out to Teams tenants, as well as synchronize the updates to App Studio to match the new versions.   Currently the App Studio only validates to 1.9

**Comment by Nikitha-MSFT** [comment]
Wr are able to repro the issue, we are checking internally get back to you soon

**Comment by Nikitha-MSFT** [comment]
Currently we have not updated our tooling yet to use 1.10.  There is currently a bug in our services that is moving its way to production.  This bug only causes issue while trying to upload your custom app to Teams.  
 
If you want to test their app with 1.10 features you can use the Dev-Preview version of the manifest.
If you want to publish your app with 1.10 features you can update your app package to 1.10 and submit it to partner centre with no issue.
