### ISSUE TITLE
Teams App Studio available in commercial tenants only

### ISSUE THREAD

**Issue by drewberrymore** [MicrosoftDocs/msteams-docs#3334]
Documentation needs to reflect that Teams App Studio is not available in GCC/GCCH/DoD tenants and at this time Microsoft has no intention of making this available in the future for government tenants. Please reference MS Support ticket Case #25228514 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f4a41f1-2993-7869-a1ab-b83cb6225d7e
* Version Independent ID: c000998f-9192-50fb-6a0b-ace157054292
* Content: [Get started with App Studio for Microsoft Teams - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/app-studio-overview)
* Content Source: [msteams-platform/concepts/build-and-test/app-studio-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/build-and-test/app-studio-overview.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Sridevi-MSFT** [comment]
@drewberrymor - Thanks for bringing up this issue, Let us investigate at our end and will inform you as soon as possible.

**Comment by heath-hamilton** [comment]
@drewberrymore this is now reflected in the Teams platform docs: https://docs.microsoft.com/microsoftteams/platform/concepts/build-and-test/app-studio-overview.
