### ISSUE TITLE
Submit happening multiple times

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#3346]
Copied bug from: https://github.com/microsoft/AdaptiveCards/issues/5842 

**Details from original post:**
I am using Adaptive card 1.0 version with one input box and submit button. I am using Teams channel. I build the json format using adaptive card designer.

When I enter text in the text box and clicking on submit button, the data is posting 2 times. I am unable to find the root cause. Can you help? And I noticed that as part of 2nd submission error is showing below the adaptive card saying, 'Unable to reach app. Please try again.'.

Note: the same adaptive card is working from web chat (same bot enabled for teams and webchat)

Help will be much appreciated.---
#### Document Details

⚠ *Do not edit this section.It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Cards reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **surbhigupta12**

**Comment by Mamatha-MSFT** [comment]
Hi @srinutamada  - I am unable to repro the issue. Could you please share the adaptive card Json.

**Comment by Mamatha-MSFT** [comment]
@srinutamada - If you are still facing the issue please share the adaptive card json.
