### ISSUE TITLE
Action.OpenUrl not working anymore

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#3347]
Copied bug from: https://github.com/microsoft/AdaptiveCards/issues/5839 

**Details from original post:**

# Target Application

Teams

# Problem Description

When clicking on the action button in Teams it should open a browser but since a few days it is not working anymore. When clicking on "open app in new tab" in Teams and then clicking the button, it somehow does work. I have tried the url in postman and it works fine. 

# Screenshot
The url in postman:

![image](https://user-images.githubusercontent.com/76207835/118620381-bfd85c00-b7c5-11eb-9d9f-b4b7ce86d8d5.png)

![image](https://user-images.githubusercontent.com/76207835/118620464-cf57a500-b7c5-11eb-9d38-2c082a7a4503.png)

The card in Teams:

![image](https://user-images.githubusercontent.com/76207835/118620782-1e053f00-b7c6-11eb-894c-ca6e362aa175.png)

# Card JSON

{
    "type": "AdaptiveCard",
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.3",
    "body": [
        {
            "type": "Image",
            "url": "https://isabot.ista.nl/api/Afrekening/GetImgDocuware",
            "size": "Large"
        },
        {
            "type": "TextBlock",
            "text": "Afrekening van object: **${user.Bewoner.content.ObjectNr}** ",
            "wrap": true,
            "size": "Large"
        },
        {
            "type": "TextBlock",
            "text": "${Straat} ${Huisnrvan} t/m ${Huisnrtm} ${Plaats}",
            "wrap": true,
            "size": "Small"
        },
        {
            "type": "TextBlock",
            "text": "${user.Bewoner.Jaar}",
            "wrap": true,
            "height": "stretch",
            "size": "Small",
            "color": "Accent"
        }
    ],
    "actions": [
        {
            "type": "Action.OpenUrl",
            "title": "Open afrekening",
            "url": "${dialog.Response.content}",
            "style": "positive"
        }
    ],
    "selectAction": {
        "type": "Action.OpenUrl"
    }
}

# Version of SDK

1.3
---
#### Document Details

⚠ *Do not edit this section.It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Cards reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **surbhigupta12**

**Comment by ysnoek2** [comment]
Fixed this by making the url smaller and redirecting. The urls before were about 221 characters long.

**Comment by Jagadeesh-MSFT** [comment]
Hi @ysnoek2, Thanks for the update, we are closing this issue for now, please feel free to reopen if you have any issue on this.
