### ISSUE TITLE
Dialog in Meetings sample?

### ISSUE THREAD

**Issue by ervingayle** [MicrosoftDocs/msteams-docs#3348]
The documentation references an in meeting ability to display a dialog box but says not to use task modules (if I am reading this properly). Is there a sample that can demonstrate how to implement this?

**Comment by Nikitha-MSFT** [comment]
You can use message extension to open a dialog. Could you please check[ Designing your Microsoft Teams meeting extension](https://docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/design/designing-apps-in-meetings#use-an-in-meeting-dialog)?

**Comment by ervingayle** [comment]
Thank you so much for the response. I took a look at the mentioned sample and tried it. While as it describes the content bubble is provided in meeting invocation and response in chat, the notification that I am looking for is the Dialog box which still is not clear to me based on the documentation and this sample.

**Comment by Nikitha-MSFT** [comment]
@ervingayle  - could you please check [this](https://docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/design/designing-apps-in-meetings?tabs=desktop#use-an-in-meeting-dialog)?

**Comment by ervingayle** [comment]
@Nikitha-MSFT . Thank you for your reply. I have read this post but I must be missing something. This is just the UI guide for how to ensure that the dialog would meet the standards set. Its referenced implementation in the content bubbles sample does display a card in an online meeting but in the chat and what I am trying to do is replicate the scenario where the dialog pop-up occurs outside of a chat window (like the images) in a meeting scenario.

**Comment by Nikitha-MSFT** [comment]
Out of the chat? could you please explain the scenario in more detail? Which images you are mentioning?

**Comment by ervingayle** [comment]
Hello @Nikitha-MSFT . Thanks for your patience. In this picture there is a dialog box that is not inline with a chat conversation as with the content bubble sample. 
![image](https://user-images.githubusercontent.com/20663596/119594489-dffdb180-bda9-11eb-87ce-530419eea8ab.png)

If we agree on that I am asking how can I accomplish this functionality. The provided links thus far unless I am missing something do not help me to understand what needs to be done

**Comment by Nikitha-MSFT** [comment]
We are checking internally get back to you soon

**Comment by Nikitha-MSFT** [comment]
Content bubble refer to the same, which will invoke a [dialog box](https://docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/design/designing-apps-in-meetings?tabs=desktop#use-an-in-meeting-dialog) using [NotificationSignal API](https://docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?view=msteams-client-js-latest&tabs=dotnet#notificationsignal-api). Could you plese try [content bubble sample](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/meetings-content-bubble/csharp)
