### ISSUE TITLE
Review for GCC caveats?

### ISSUE THREAD

**Issue by npherson** [MicrosoftDocs/msteams-docs#3349]
What are the chances that we could get the PG to review every page of the platform developer docs to update/call out caveats for GCC customers? Things like adaptive cards and the publishing process have limitations, and I'm sure a lot more. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f57a31a0-e815-faa4-653d-795ae8a8e4d7
* Version Independent ID: 8f48ea3d-231b-2776-41b7-11890ea2d3c0
* Content: [Build apps for the Microsoft Teams platform - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/overview)
* Content Source: [msteams-platform/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/overview.md)
* Product: **msteams**
* GitHub Login: @heath-hamilton
* Microsoft Alias: **lajanuar**

**Comment by Mamatha-MSFT** [comment]
Hi @npherson - Could you please explain your query briefly with more details.

**Comment by npherson** [comment]
There are several parts of the Teams platform documentation that do not work as described if the customer is using the Office 365 Government Community Cloud (GCC). As this was an emphasis item this year, and it sounds like will be an even bigger area of focus next fiscal year, having documentation that our customers can trust to reflect the product reality is incredibly important. Relying on the customers/field to 'find' all the inaccuracies for GCC has not resulted in accurate documentation, so I'm asking if the PG could review each page for accuracy for GCC customers, adding notes/callouts when features do not work as described on the page in GCC (like with adaptive cards, etc.).

**Comment by Wajeed-msft** [comment]
Thanks @npherson. @SurbhiGupta12 could you please help with this request?
