### ISSUE TITLE
tabs not working

### ISSUE THREAD

**Issue by a-shawky** [MicrosoftDocs/msteams-docs#335]
Hi,
I followed the tutorial, in the step of configuring the Bot, the app display message "We're having trouble loading your tab"
there is no message telling me what is the problem.
is there a way to know the problem?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98cd21c7-e87c-3c5b-7574-998a355f9f08
* Version Independent ID: 5e312707-facc-03fc-af59-90267d0c7b8a
* Content: [Get started with C#/.NET - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/get-started/get-started-dotnet-app-studio)
* Content Source: [msteams-platform/get-started/get-started-dotnet-app-studio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/get-started/get-started-dotnet-app-studio.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Wajeed-msft** [comment]
@a-shawky -  Could you please share the screenshot of the issue?

**Comment by chunga168** [comment]
Getting the same issue too. Not sure when did it start but it was working a month ago.
The steps for me is.
Going to App Studio from Teams. Click on "Manifest editor" tab. Click on "Create a new app".
Click on "Bots" (under "Capabilities"). Setup any bot in there. 

Works for about a second:
![image](https://user-images.githubusercontent.com/24387991/49348842-c7cddf80-f6e2-11e8-9b91-9eed1a41ecba.png)

Then will just goes into the error page:
![image](https://user-images.githubusercontent.com/24387991/49348740-22b30700-f6e2-11e8-818d-1578d83c9437.png)

Please help.
Thanks

**Comment by Wajeed-msft** [comment]
We are looking into this.

**Comment by MattSFT** [comment]
@chunga168 do you see any error logs in the console? Or failed network calls?
