### ISSUE TITLE
Images are broken if we download

### ISSUE THREAD

**Issue by Hahkarthick** [MicrosoftDocs/msteams-docs#3353]
Issue: I download the images from the "Teams" chat the downloaded image is broken.

![image](https://user-images.githubusercontent.com/22488363/119139857-1f05cd00-ba61-11eb-854d-6ccd01cc5a03.png)

Solution: After I did some analysis the I think all images seem to be downloading as "PNG" by default.  if I change it to jpeg manually it works. so teams download should maintain the image extensions to avoid the issues.

![MicrosoftTeams-image](https://user-images.githubusercontent.com/22488363/119140100-668c5900-ba61-11eb-97ac-de8925f98cd3.jpeg)

Eg: I someone shared a "jpeg"  in teams chat when I click on download the teams by default downloading as PNG that's why the image is broken if we change the format the image opens properly.

**Comment by Jagadeesh-MSFT** [comment]
Hi @Hahkarthick, Microsoft will always focus on customer’s feedback and experience, some new features would be added to the services based on customers' feedback in the future, we also recommend you give your new idea in Teams [UserVoice](https://microsoftteams.uservoice.com/).

**Comment by Jagadeesh-MSFT** [comment]
We are closing this issue for now, If you still face any issue please feel free to reopen the issue.
