### ISSUE TITLE
Changing the domain of an app

### ISSUE THREAD

**Issue by Nasicus** [MicrosoftDocs/msteams-docs#3354]
As far as I understand (and also the results from my tests) the domain used for the `webApplicationInfo.resource` and the `contentUrl` must be from the same domain.

Example manifest (omitted unnecessary stuff):

```
{
  "staticTabs": [
    {
      "entityId": "com.whatever.sub",
      "name": "Tab1",
      "contentUrl": "https://sub.whatever.com/?hideChrome=true",
      "websiteUrl": "https://sub.whatever.com",
      "scopes": ["personal"]
    }
  ],
  "validDomains": [
    "sub.whatever.com",
    "login.microsoftonline.com"
  ],
  "webApplicationInfo": {
    "id": "0e0ae51a-d657-4963-b963-cbc967d98a6e",
    "resource": "api://sub.whatever.com/0e0ae51a-d657-4963-b963-cbc967d98a6e"
  }
}
```

Now I have the case that we're changing the URL of the application from `sub.whatever.com` to `sub.new-cool-site.com`.

Does this now mean I also need to create a new AAD app so I can update the `webApplicaitionInfo`?

If so this would be quite bad, because then all users who now use our app would need to consent AGAIN, since it's now a new AAD app.

Is this correct? If so is there any solution?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52221dd3-95ec-96b9-1da8-9478527c2602
* Version Independent ID: 32e9c2d8-733d-0865-2ea3-727d8684a10d
* Content: [Single sign-on support for tabs - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-aad-sso)
* Content Source: [msteams-platform/tabs/how-to/authentication/auth-aad-sso.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tabs/how-to/authentication/auth-aad-sso.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Mamatha-MSFT** [comment]
@Nasicus - If you are changing the domain there is no need to create aad app. You can update the domain in aad app registration.

**Comment by Nasicus** [comment]
@Mamatha-MSFT don't know what you mean. For all existing teams app users the app still should work and I think if I update the existing AAD app it will break existing apps or not?

**Comment by Mamatha-MSFT** [comment]
@Nasicus - If you update the domain name in AAD app users needs to consent again.
