### ISSUE TITLE
Clearer documentation on how to detect submitting user in HttpPOST

### ISSUE THREAD

**Issue by mastef** [MicrosoftDocs/msteams-docs#337]
What is the correct process to detect the submitting user/name/email of a `HttpPOST`? The only hint I was able to find was in the Authorization JWT Bearer token. However the JWT's payload submitted by a `HttpPOST` action from an incoming webhook doesn't seem to have a "sender" field.

Is there an easier way to supply the user information in a HttpPOST "post" field instead?

These are the fields from a HttpPOST action's JWT token when testing with incoming webhooks : 
![image](https://user-images.githubusercontent.com/762297/49138365-896ea400-f321-11e8-89d2-282d8452c9f1.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0fd8e4d-f110-36f8-5bd3-db3325b14c01
* Version Independent ID: 717ea854-1d3a-2c15-e495-b6f170fe7aff
* Content: [Using Office 365 Connectors - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/connectors/connectors-using)
* Content Source: [msteams-platform/concepts/connectors/connectors-using.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/connectors/connectors-using.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by mastef** [comment]
When I run the incoming webhooks HttpPOST JWT token against the [outlook JWT verification node example](https://github.com/OfficeDev/outlook-actionable-messages-node-token-validation), I receive this result : 
```
ActionableMessageTokenValidationResult {
  sender: undefined,
  actionPerformer: '79e349e1-xxxx-xxxx-xxxx-xxxxxxxxxxxx'
}
```
Maybe the "incoming webhooks" manifest doesn't specify the `"needsIdentity": "true"` value? Or I'm doing it completely wrong?

**Comment by pschaeflein** [comment]
I know this does not answer your question, but I have a few suggestions:

1. You know the team/channel to which the card is sent, so you can add an identifier (that you capture during connector setup) as a header or “hidden” field in the body.

2. Post the card using a bot, which would then participate in the conversation, including the sender. (This requires the bot be added to the target Team, which requires more code or user intervention.)

**Comment by mastef** [comment]
@pschaeflein thank you for your answer

1. That's right. That would give us the channel, but not the user.
2. Looking right now into how to solve this with a simple webhooks implementation.

So the questions that are I guess relevant are : 
1. Can connectors ping the `actionPerformer` details from somewhere else? In absence of sender details
2. In which scenarios will actionPerformer be a guid, in which an email, and when would sender be defined?

In comparison - this is how much info I'm getting from Slack webhooks ( which we use for the exacty same connector functionality ) https://api.slack.com/interactive-messages#checking_the_action_type

The POST payload has all the information that is required for us to act on it. Original message, team, channel, user id, user name. Especially original message is nice, since I don't have to reconstruct the message to be returned/altered in a second system, and can simply alter it and return it right away.

So if these variables are available somewhere - if there's a list of what's available - that would be immensely helpful.
