### ISSUE TITLE
Documentation mismatch regarding configurationUrl in connectors

### ISSUE THREAD

**Issue by mastef** [MicrosoftDocs/msteams-docs#338]
In the [documentation for `connectors`](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema#connectors) there are only 2 allowed values : 
`connectorId`
`scopes`

In the [Sample full schema](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema#sample-full-schema), `connectors` has 3 possible values : 
`connectorId`
`scopes`
`configurationUrl`

Which one is correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f94a488-d636-92b3-21eb-c88744c8f272
* Version Independent ID: 7b3413f4-9ade-accf-5cb2-83fead11a32a
* Content: [Manifest schema reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema)
* Content Source: [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/resources/schema/manifest-schema.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by mastef** [comment]
When downloading a `manifest.json` from the Connectors Developer Dashboard, the `connectors` section has a `configurationUrl` defined.

**Comment by pschaeflein** [comment]
Have you seen this hands-on-lab for Connectors in Teams? It demonstrates the configuration experience using the configurationUrl:

https://github.com/OfficeDev/TrainingContent/blob/master/Teams/02%20Tabs%20and%20Connectors/Lab.md#exercise2

**Comment by Wajeed-msft** [comment]
@mastef - configurationUrl is used to show Connector config page. We will update the document to include configurationUrl (introduced in [manifes v1.3](https://developer.microsoft.com/en-us/json-schemas/teams/v1.3/MicrosoftTeams.schema.json)).

**Comment by NormSohl** [comment]
Updated and live.  Thanks!

**Comment by mastef** [comment]
Thanks @NormSohl. One small thing - the `configurationUrl` is not required ( as per manifest ).
