### ISSUE TITLE
Step 1 with an empty response 

### ISSUE THREAD

**Issue by TobiasAT** [MicrosoftDocs/msteams-docs#3390]
I think step 1 has currently a bug or issue. The response is always empty, reproducible in v1 and Beta API. The team was created and is visible in the Teams Admin Center, just the response is empty. In step 2 the response is ok for the channel creation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5687f17-f3c7-39be-5487-f24f2155191a
* Version Independent ID: ce77e760-90cf-e6b1-3cec-ae55ee50c33e
* Content: [Use Microsoft Graph to import external platform messages to Teams - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/graph-api/import-messages/import-external-messages-to-teams#request-create-a-team-in-migration-state)
* Content Source: [msteams-platform/graph-api/import-messages/import-external-messages-to-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/graph-api/import-messages/import-external-messages-to-teams.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Nikitha-MSFT** [comment]
We are to repro the issue, checking internally get back to you soon.

**Comment by Nikitha-MSFT** [comment]
Currently you will receive the 200 okay status with out any response. You need to pick the team id from the headers. This is by design

**Comment by TobiasAT** [comment]
@Nikitha-MSFT Thanks for the hint. 👍 I used Invoke-RestMethod which does not return a header. With Invoke-WebRequest I received the header and team guid. Closing the issue.
