### ISSUE TITLE
Duplicate sentence paragraph

### ISSUE THREAD

**Issue by JonVaillant** [MicrosoftDocs/msteams-docs#3391]
"The botActivityHandler.js file, located in the root directory of your project, is the Teams-specific handler that handles bot activities, such as how the bot responds to specific messages. The app scaffolding provides a botActivityHandler.js file located in the root directory of your project, is the Teams specific handler that handles bot activities such as how the bot responds to specific messages."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d083976-00c7-86bb-bdca-f909722eae6a
* Version Independent ID: 17fe4c29-7ac0-9091-c7ca-8286e80c0df9
* Content: [Get started - Build a bot - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/build-your-first-app/build-bot)
* Content Source: [msteams-platform/build-your-first-app/build-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/build-your-first-app/build-bot.md)
* Product: **msteams**
* GitHub Login: @girliemac
* Microsoft Alias: **timura**

**Comment by Mamatha-MSFT** [comment]
Hi @KirtiPereira - Please remove the duplicate sentence from the below paragraph. 
![image](https://user-images.githubusercontent.com/78795357/119336435-4ea81580-bcab-11eb-8149-5ae7bcd22d30.png)
