### ISSUE TITLE
SILK NB & WB are not in the list of supported media formats for audio content ?

### ISSUE THREAD

**Issue by piqueora** [MicrosoftDocs/msteams-docs#340]
question is self explanatory

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95cd14d9-9ef1-3ce9-c125-c3990e0d9032
* Version Independent ID: 321fa1ae-48de-4750-0e39-b927d37d0f54
* Content: [Supported media formats - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/general/media-formats)
* Content Source: [msteams-platform/resources/general/media-formats.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/resources/general/media-formats.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by billbliss** [comment]
The list of supported formats is correct. We apologize if the format you want isn’t supported.
