### ISSUE TITLE
localization in swedish

### ISSUE THREAD

**Issue by robertmeaplus** [MicrosoftDocs/msteams-docs#3403]
Hi im having in my teams application manifest.json

"localizationInfo": {
        "defaultLanguageTag": "en",
        "additionalLanguages": [
            {
                "languageTag": "sv",
                "file": "sv.json"
            }
        ]
    },

And in the sv.json file

{
    "$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.9/MicrosoftTeams.Localization.schema.json",
    "name.short": "APPNAME",
    "name.full": "APPNAME",
    "description.short": "short SE",
    "description.full": "full SE",
    "staticTabs[0].name": "Tab1 SE",
    "staticTabs[1].name": "Tab2 SE"
}

But it never changes. Tested both desktop on mac/windows and web on windows. 
The sv.json needs to be in the same directory as manifest.json right?

---
#### Dokumentinformation

⚠ *Redigera inte det här avsnittet. Det krävs för docs.microsoft.com ➟ länkning till GitHub-problem.*

* ID: 3f55e52a-5fc4-7fcb-0e1e-946bff5aaee4
* Version Independent ID: b6c559fb-8512-575b-4fed-ebe1457e890e
* Content: [Localization for your app - Teams](https://docs.microsoft.com/sv-se/microsoftteams/platform/concepts/build-and-test/apps-localization)
* Content Source: [msteams-platform/concepts/build-and-test/apps-localization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/build-and-test/apps-localization.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Chetana-MSFT** [comment]
We are checking this internally we will reach out you soon.

**Comment by Wajeed-msft** [comment]
@Chetana-MSFT - could you please try to repro using manifest snippets provided by @robertmeaplus ?

**Comment by robertmeaplus** [comment]
Cannot upload manifest file here should i send it or post here?

**Comment by Chetana-MSFT** [comment]
Hi @robertmeaplus Yes, You need to add both JSON files in a single folder and upload as manifest. Please go through the [sample](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/app-localization/csharp) for your reference.

**Comment by robertmeaplus** [comment]
> Hi @robertmeaplus Yes, You need to add both JSON files in a single folder and upload as manifest. Please go through the [sample](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/app-localization/csharp) for your reference.

I realised why it doesnt work. Im using visual studio and microsoft teams toolkit and it doesnt add language files when building the appPackage.zip so i have now added the sv.json to appPackage.zip and it works.

Sorry for your time

**Comment by Chetana-MSFT** [comment]
@robertmeaplus Good to hear that issue is resolved. Thanks for confirming on the same with us.
