### ISSUE TITLE
HttpPOST documentation link goes nowhere

### ISSUE THREAD

**Issue by mastef** [MicrosoftDocs/msteams-docs#341]
The text `To verify that an HttpPOST action is working correctly, use your custom incoming webhook.` links to `#setting-up-a-custom-incoming-webhook`, but that section is not present on this page.

![image](https://user-images.githubusercontent.com/762297/49208038-41b34f80-f3e9-11e8-9a19-b8aa006377e2.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c21a27c1-d01a-6cc7-c991-73af6492aad8
* Version Independent ID: b15d2142-df29-250e-9a0a-b734dcb93162
* Content: [Office 365 Connectors - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/connectors/connectors-creating)
* Content Source: [msteams-platform/concepts/connectors/connectors-creating.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/connectors/connectors-creating.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by mastef** [comment]
That's in `connectors-creating.md`. The section exists in the `connectors-using.md` document.

**Comment by NormSohl** [comment]
Thanks! Fixed now.
