### ISSUE TITLE
Unable to open AppStudio on VS code on macos

### ISSUE THREAD

**Issue by Choongkyu** [MicrosoftDocs/msteams-docs#3434]
Hello. I'm trying to follow the hello world tutorial and was wondering how I might be able to
1) get AppStudio to sideload an app, since AppStudio does not respond to my clicking on install
2) address the error `The webpage at https://localhost:3000/tab might be temporarily down or it may have moved permanently to a new web address.` when working with the F5 alternative method.

Both issues are demonstrated in the attached video. Thank you.

https://user-images.githubusercontent.com/1592194/119442625-0dc8f480-bcdd-11eb-9618-e7deadd14f2f.mp4

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f876156-cc1e-468f-4647-5143a5de03b1
* Version Independent ID: 618f43a3-3371-ad99-13aa-087b9303298c
* Content: [Get started - Build and run your first app - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/build-your-first-app/build-and-run?tabs=do-not-have-a-tenant#feedback)
* Content Source: [msteams-platform/build-your-first-app/build-and-run.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/build-your-first-app/build-and-run.md)
* Product: **msteams**
* GitHub Login: @girliemac
* Microsoft Alias: **timura**

**Comment by Sridevi-MSFT** [comment]
@Choongkyu  - We are unable to access the video you have provided. Could you please share it again.

**Comment by Choongkyu** [comment]
@Sridevi-MSFT can you advise on any alternatives that would work best for you? I've tried reloading the page and am still able to view the video on my end. Thanks.

**Comment by Sridevi-MSFT** [comment]
@Choongkyu - Please share your recording video to this microsoftteamsdev@microsoft.com.

**Comment by Choongkyu** [comment]
@Sridevi-MSFT thank you. I just sent an email.

**Comment by Choongkyu** [comment]
I also checked the website and it appears as if this page has been removed: https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/build-your-first-app/build-and-run.md

**Comment by Sridevi-MSFT** [comment]
@Choongkyu - Could you please confirm are you able to to render https://localhost:3000/tab in browser. Meanwhile we will repro the sideloading an app issue and will get back to you.

**Comment by Sridevi-MSFT** [comment]
@Choongkyu - Could you please update your Teams Toolkit to latest version and follow this updated [documentation ](https://docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-bot?tabs=vscode)for your reference.
