### ISSUE TITLE
Provide clarity on the Teams Client Platforms

### ISSUE THREAD

**Issue by Josverl** [MicrosoftDocs/msteams-docs#345]
Can you add clarity on to options / limitations of creating teams App for the different platforms ?
ie for : 
* Desktop ( Win / Mac) 
* Phones ( iOS / Android) 
* Tablet ( iOS / Android) 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0f1115e-693c-25f8-e0e7-103fb63753c2
* Version Independent ID: 9726dee6-7fd2-1c98-7c2b-dfcb858e540e
* Content: [Apps for Microsoft Teams - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/apps/apps-overview)
* Content Source: [msteams-platform/concepts/apps/apps-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/apps/apps-overview.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by billbliss** [comment]
We don't list that information centrally, and our goal is to make everything work across all platforms. That's in progress. Do you have a specific question? This one is too broad.
