### ISSUE TITLE
Messaging extenstions SDK for .Net Core / Bot Framework v4

### ISSUE THREAD

**Issue by tnsholding** [MicrosoftDocs/msteams-docs#346]
It seems this is not available when building bot using Bot Framework v4 - IsComposeExtensionQuery and other extensions not available in NuGet "Microsoft.Bot.Connector.Teams".
Any timeline for this working? - should perhaps be noted in docs that it is not yet working with v4.

---
#### Dokumentoplysninger

⚠ *Undlad at redigere denne sektion. Det er påkrævet til docs.microsoft.com ➟ GitHub-problemlinkning.*

* ID: eeb9dcd0-fc2e-95a0-5238-fb67b6a27ba7
* Version Independent ID: 3adf9985-9a34-fbb4-161a-23beb753dd70
* Content: [Develop messaging extensions - Teams](https://docs.microsoft.com/da-dk/microsoftteams/platform/concepts/messaging-extensions)
* Content Source: [msteams-platform/concepts/messaging-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/messaging-extensions.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by billbliss** [comment]
Bot Framework 4.0 is not yet supported and we do not have a date for when it will be.

**Comment by clearab** [comment]
You can find our roadmap for support of Bot Builder v4 here: https://developer.microsoft.com/en-us/microsoft-teams/blogs/preview-release-of-net-teams-bot-builder-v4-sdk/
