### ISSUE TITLE
Empty State desktop image is empty

### ISSUE THREAD

**Issue by luismanez** [MicrosoftDocs/msteams-docs#3469]
The Empty State desktop image is empty. As far as I see it points to https://raw.githubusercontent.com/MicrosoftDocs/msteams-docs/master/msteams-platform/assets/images/ui-templates/empty-state.png, but that image is empty.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e739fdd6-8835-cfcd-f25c-1b4c7cb42afa
* Version Independent ID: 3bbef1d2-6427-0c7f-bfe2-57bf016629da
* Content: [Designing your app with UI templates - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/design/design-teams-app-ui-templates?tabs=desktop)
* Content Source: [msteams-platform/concepts/design/design-teams-app-ui-templates.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/design/design-teams-app-ui-templates.md)
* Product: **msteams**
* GitHub Login: @heath-hamilton
* Microsoft Alias: **lajanuar**

**Comment by Nikitha-MSFT** [comment]
Hi @luismanez - Which image you are referring about? Is there any image in the doc that you are not able to view? Could you please explain your scenario in more detail?

**Comment by luismanez** [comment]
Hi @Nikitha-MSFT,

In this link: https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/design/design-teams-app-ui-templates?tabs=desktop

In the section "Empty state -> Top use cases", the image is not appearing, as you can see in the screenshot below:

![image](https://user-images.githubusercontent.com/9392197/119775648-3101c880-bec4-11eb-8696-d1d782e25713.png)

As far as I see in source code (github), the linked image is:
https://raw.githubusercontent.com/MicrosoftDocs/msteams-docs/master/msteams-platform/assets/images/ui-templates/empty-state.png

but that .png, is an empty image.

Hope it helps.

**Comment by Nikitha-MSFT** [comment]
Thank you for Reporting the issue. Added the required doc labels, the Tech writing team will be followup.
