### ISSUE TITLE
Microsoft Teams brand guidelines

### ISSUE THREAD

**Issue by wdoyle-lifesize** [MicrosoftDocs/msteams-docs#347]
Are there any brand guidelines for Microsoft Teams that we can place on our marketing material or sites to help our users link to our app? 
Similar to Apple App Store: https://developer.apple.com/app-store/marketing/guidelines/
and Google Play: https://developer.android.com/distribute/marketing-tools/brand-guidelines

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6adff4a9-1f94-e638-b62f-0ad205a7af54
* Version Independent ID: a04cd7b3-2d98-b08a-8a61-0ef20459130e
* Content: [Design Guidelines Reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/design/overview#feedback)
* Content Source: [msteams-platform/resources/design/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/resources/design/overview.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by clearab** [comment]
As Microsoft Teams uses the App Source for our app store, the generic guidance is the same and is available here: https://docs.microsoft.com/en-us/office/dev/store/promote-your-office-store-solution
