### ISSUE TITLE
Save button

### ISSUE THREAD

**Issue by Mosik** [MicrosoftDocs/msteams-docs#348]
Hello!

I've copied the page example above and uploaded to a website. The content load but the save button doesn't get valid. I got validdomains listed in my teams app. What could be wrong?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ffb7ac07-169d-860d-d566-e69540df600d
* Version Independent ID: 7863d671-52d9-83e3-7fcc-4eed0f3a62f9
* Content: [Create a configuration page for your tab - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/tabs/tabs-configuration)
* Content Source: [msteams-platform/concepts/tabs/tabs-configuration.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/tabs/tabs-configuration.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by billbliss** [comment]
Are you calling `microsoftTeams.settings.setValidityState(true)`? That's the most likely reason.

**Comment by Wajeed-msft** [comment]
@Mosik - Could you please confirm if Teams SDK is present in your code under _node_modules_. 
`<script src="node_modules/@microsoft/teams-js@1.3.3/dist/MicrosoftTeams.min.js"></script>`

You can also use [Microsoft Teams JavaScript API](https://docs.microsoft.com/en-us/javascript/api/overview/msteams-client?view=msteams-client-js-latest#using-the-sdk) (via CDN)
`<script src="https://unpkg.com/@microsoft/teams-js@1.3.4/dist/MicrosoftTeams.min.js" integrity="sha384-3zTjxw3msc6gKx3DseSU0lfRM129YrFjr2xgocfMIN/kBCdzJ88d+FSB1n3scUku" crossorigin="anonymous"></script>`

**Comment by Mosik** [comment]
I changed from node_modules to unpkg.com and now the save button gets active when i select one of the two options. But tapping the save button sais the settings can't be saved.

Providing you with the code

https://destinationhultsfred.com/wp-content/uploads/2018/12/teams2.html

**Comment by Wajeed-msft** [comment]
@Mosik - Are you still facing any issues?

**Comment by Mosik** [comment]
Hi Wajeed. It's working like a charm. Thank you very much for your help.
