### ISSUE TITLE
During remote session, whenever you press letter 'c' the Teams window jumps up even when it is minimized

### ISSUE THREAD

**Issue by manihere** [MicrosoftDocs/msteams-docs#3490]
Hello Folks,

When we are using Teams for remote session with customer, sometimes when you press letter 'c' the Teams window jumps up even when it is minimized.

This is especially problematic when typing on the customer environment. This has been reported by some other teammates and seems to be fixed by restarting Teams.

**Comment by Jagadeesh-MSFT** [comment]
Hi @manihere, I'm unable to repro your issue from our end, could you please let us share more details/repro steps with us.

**Comment by manihere** [comment]
Hello sorry for the delay, please find me on teams mapanwar@microsoft.com :)

**Comment by Jagadeesh-MSFT** [comment]
Thanks for reaching out us. According to your description, your issue is more related to Teams product, which we do not support. For issues related to teams product, please reach out to the Product support channels for Microsoft Teams. Thanks for your understanding and patience!
