### ISSUE TITLE
[Rendering] ios teams mobile app, entire adaptive card not showing when text (Input Text) is used after last teams update

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#3497]
Copied bug from: https://github.com/microsoft/AdaptiveCards/issues/5870 

**Details from original post:**
# Target Platform

Please list the platform(s) that your application is targeting and remove platforms you are not targeting:

- iOS

# Target Application

Microsoft Teams

# Problem Description

When you use Input.Text in an Adaptive card on IOS the entire card will not render when called from a task module.

# Screenshot

Nothing is rendered so a screenshot would be blank.

# JSON

{
    "type": "AdaptiveCard",
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.3",
    "body": [
        {
            "type": "Input.Text",
            "placeholder": "Placeholder text"
        }
    ]
}

---
#### Document Details

⚠ *Do not edit this section.It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Cards reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **surbhigupta12**

**Comment by Chetana-MSFT** [comment]
Hi @vindevries Thanks for reaching out us. I will repro at my end and will let you soon.

**Comment by Chetana-MSFT** [comment]
Hi @vindevries  You need pass `ID` for input.text array please go through below example  
```
{
  "type": "AdaptiveCard",
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "version": "1.3",
  "body": [
    {
      "type": "Input.Text",
      "id": "passid",
      "placeholder": "Placeholder text"
    }
  ]
}
```

**Comment by vindevries** [comment]
@Chetana-MSFT 
As shown in issue microsoft/AdaptiveCards#5870 we tried that already and is has no effect.

**Comment by Chetana-MSFT** [comment]
@vindevries Can I know the IOS and MS teams version.

**Comment by fgarciachipi** [comment]
@Chetana-MSFT I have the same problem that @vindevries 
I detected the problem in the MS Teams version 3.7.0 (current version is 3.7.1 with the same issue)
iOS version: 14.4.2

**Comment by vindevries** [comment]
@Chetana-MSFT I'm using IOS 12.5.3 and Teams version 3.7.0

**Comment by Chetana-MSFT** [comment]
Hi @vindevries I am able to repro the issue. I have raised a bug at our end. Our engineering team will work on it.

**Comment by SergeyGrayman** [comment]
@Chetana-MSFT It's a global problem, there are 4-5 same issues in backlog for a couple of months but none in review or in progress, can you prioritize this somehow? This feature is really sensitive for customers.

**Comment by Prasad-MSFT** [comment]
We are closing the issue for now. Please feel free to reopen if required.

**Comment by Prasad-MSFT** [comment]
We are closing the issue for now. Please feel free to reopen if required.
