### ISSUE TITLE
This page doesn't make sense to me, can add context or move it? 

### ISSUE THREAD

**Issue by ojasvichoudhary** [MicrosoftDocs/msteams-docs#3498]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9d17811-3418-b8a4-b540-b36ac877b406
* Version Independent ID: 03bf3f55-31c7-02ab-91e3-2ad9e8dae63d
* Content: [Add a configuration page to your messaging extension - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/add-configuration-page)
* Content Source: [msteams-platform/messaging-extensions/how-to/add-configuration-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/messaging-extensions/how-to/add-configuration-page.md)
* Product: **msteams**
* GitHub Login: @clearab
* Microsoft Alias: **anclear**

**Comment by Mamatha-MSFT** [comment]
@ojasvichoudhary - Thank you for the insights on the document. Our document team will work on it.
