### ISSUE TITLE
A phrasing error at "Use App Studio to update the app package"

### ISSUE THREAD

**Issue by tsahi** [MicrosoftDocs/msteams-docs#350]
The following sentence is not clear, at this section:

> App Studio can simplify the creation of an app, and really helps when adding bots, since manually these these require online registration with Microsoft Bot Framework.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98cd21c7-e87c-3c5b-7574-998a355f9f08
* Version Independent ID: 5e312707-facc-03fc-af59-90267d0c7b8a
* Content: [Get started with C#/.NET - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/get-started/get-started-dotnet-app-studio)
* Content Source: [msteams-platform/get-started/get-started-dotnet-app-studio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/get-started/get-started-dotnet-app-studio.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Wajeed-msft** [comment]
Thanks for reporting this. Docs are updated.
