### ISSUE TITLE
Don't work `Deep linking to an audio or audio-video call` in mobile device.

### ISSUE THREAD

**Issue by 1411381** [MicrosoftDocs/msteams-docs#3500]
[Enter feedback here]
Calls between users in Teams are not working well on mobile.
ex ) https://teams.microsoft.com/l/call/0/0?users=test@hogehoge.net

Is this normal behavior?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45541337-ecd7-5cf6-cbe4-3f0d2f39aa79
* Version Independent ID: 6b4203f0-2844-06c9-eaa3-9cc03e6f76c0
* Content: [Create deep links - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links)
* Content Source: [msteams-platform/concepts/build-and-test/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/build-and-test/deep-links.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Ravindra-MSFT** [comment]
HI @1411381, We are able to repro the issue, We have raised a bug and our internal team is working on it.

**Comment by 1411381** [comment]
Hi Ravindra , Thanks for checking.
Do you know when the fix for this bug will be completed?

**Comment by Ravindra-MSFT** [comment]
Hi @1411381 The concerned engineering team is working on it. We don't have any ETA to share with you.

**Comment by 1411381** [comment]
Hi @Ravindra-MSFT  Thanks for the answer.
I'm waiting for it to be fixed.

**Comment by 1411381** [comment]
Hi @Ravindra-MSFT 
Bug is fixed?

**Comment by Ravindra-MSFT** [comment]
Hi @1411381, We are tracking internally with our engineering team. Currently there is no ETA as of now. We will update you once the issue got fixed.

**Comment by toellbe** [comment]
What is the current ETA? Our app development depends on it.

**Comment by Ravindra-MSFT** [comment]
@toellbe, This feature is in the test progress on the Android now. Currently there is no ETA to share with, we will let you know once it is resolved.

**Comment by toellbe** [comment]
I hope iOS will be fixed too. Annoying that an obvious bug takes so long to fix.

**Comment by 1411381** [comment]
@Ravindra-MSFT 
When will it be fixed?

**Comment by Wajeed-msft** [comment]
Checking status on this with engineering team.

**Comment by toellbe** [comment]
@Wajeed-msft 

And what's the status? In the meantime you've at least managed to prompt an error message. A solution would meanwhile be needed.

**Comment by Wajeed-msft** [comment]
I still don't have updates to share on this. I have asked again.

**Comment by 1411381** [comment]
@surbhigupta12 @Ravindra-MSFT 

The bug is still there, but why is it "closed"?

I'm hoping for a fix.

**Comment by Meghana-MSFT** [comment]
@1411381 - Currently deeplink to call is not supported on mobile devices.

**Comment by 1411381** [comment]
@Meghana-MSFT 
I know that they changed the notation to "not supported".

What I want to know is whether you plan to fix it or not.

**Comment by Meghana-MSFT** [comment]
Currently we do not have work item for this issue. Could you please help by raising it on [Microsoft uservoice](https://feedbackportal.microsoft.com/feedback/forum/ad198462-1c1c-ec11-b6e7-0022481f8472).

**Comment by toellbe** [comment]
https://feedbackportal.microsoft.com/feedback/idea/31da2f4d-0467-ec11-a819-000d3a058885
