### ISSUE TITLE
Microsoft Teams meeting extension | Not able to see Add app + Icon during or before the meeting

### ISSUE THREAD

**Issue by ManthanGajjar** [MicrosoftDocs/msteams-docs#3504]
I tried couple of times to add custom apps to use during the meeting but not able to found that + icon to add an app.

also if any one familer with creating Teams meeting extension with react then please share any reference, thanks in advance.
 
here is the SC...

![Screenshot 2021-05-27 at 12 00 23 PM](https://user-images.githubusercontent.com/31969308/119776982-3f131180-bee3-11eb-97a5-1f2297959fc5.png)

thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09c05a14-d442-bcd1-f233-1beeddfd4bb1
* Version Independent ID: eb958ded-39dc-c0ab-a7c8-2d5bf334ab16
* Content: [Designing your meeting extension - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/design/designing-apps-in-meetings?tabs=desktop)
* Content Source: [msteams-platform/apps-in-teams-meetings/design/designing-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/apps-in-teams-meetings/design/designing-apps-in-meetings.md)
* Product: **msteams**
* GitHub Login: @heath-hamilton
* Microsoft Alias: **lajanuar**

**Comment by Mamatha-MSFT** [comment]
Hi @ManthanGajjar -  When you join a meeting or in meeting chat  **+ icon** will be there to add a custom apps as shown in below screenshot and select "add to meeting" and search the meeting name where you want to add the custom app. 
![image](https://user-images.githubusercontent.com/78795357/119809596-e6ec0780-bf02-11eb-8bd3-03f1f4263b28.png)

or you can sideload custom app from App Studio and while installing select "add to meeting" and search the meeting name where you want to add the custom app. 
![image](https://user-images.githubusercontent.com/78795357/119810104-5cf06e80-bf03-11eb-99da-5db5f8b54249.png)

**Comment by ManthanGajjar** [comment]
ok, thank you for the response :)

one questions, these tab apps are different than team apps? or it'll automatically convert my custom uploaded app to a tabs app? or I need to build another one like the customized app?

**Comment by Mamatha-MSFT** [comment]
Could you please confirm are you developing a Teams Bot or Tab application?

**Comment by ManthanGajjar** [comment]
Currently, I have a custom app that I can upload using this option...

![Screenshot 2021-05-27 at 6 12 07 PM](https://user-images.githubusercontent.com/31969308/119827693-0e4ccf80-bf17-11eb-964b-2722ab1f1c87.png)

now my question is, can I use this app as a tab application? or need to create and upload a separate application? if you've any valid references for it then please share them here.

Regards,
Manthan.

**Comment by Mamatha-MSFT** [comment]
Please go through this [documentation ](https://docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?tabs=dotnet) to build apps in teams meeting and also there are samples provided for reference.

**Comment by ManthanGajjar** [comment]
thank you :)
