### ISSUE TITLE
Upgrade Adaptive cards to version 1.3

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#3508]
Copied bug from: https://github.com/microsoft/AdaptiveCards/issues/5815 

**Details from original post:**
Hi

Hopefully this is in the correct area,  we have adaptive cards version 1.2 but we would like 1.3,  does anyone know how we can upgrade to this?

thanks
Andrew---
#### Document Details

⚠ *Do not edit this section.It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Cards reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **surbhigupta12**

**Comment by Mamatha-MSFT** [comment]
Hi @Andrewhoddie Taking this for internal discussion with team and will get back to you.

**Comment by Mamatha-MSFT** [comment]
@Andrewhoddie - Currently version 1.3 is not supported in teams. The engineering team is working on this feature and we don't have any ETA to share with you.
