### ISSUE TITLE
Microsoft.Bot.Connector.Teams Targets .NET Framework 4.6

### ISSUE THREAD

**Issue by ncsurfus** [MicrosoftDocs/msteams-docs#351]
The documentation doesn't call this out at all. This is extremely unclear because if you create a Basic Bot in Azure it targets .NET Core 2.0. It's also non trivial to fix that, since the Basic Bot also references Microsoft.AspNetCore.All (which is also deprecated in factor of App), and that doesn't have a target for .NET Framework. Am I expected to re-target to the Framework and work out which ASP.NET Core dependencies I need one-by-one? Is there a sample bot I can use?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f16f5795-7015-3a4e-2e64-d08d4a6be78d
* Version Independent ID: 6f8a9a3a-33c9-acc5-83d8-7645373bee3d
* Content: [Get context for your bot - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/bots/bots-context)
* Content Source: [msteams-platform/concepts/bots/bots-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/bots/bots-context.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by billbliss** [comment]
@ncsurfus at the very top of the README.md for https://github.com/OfficeDev/BotBuilder-MicrosoftTeams it says that. Did you miss it?

**Comment by ncsurfus** [comment]
By “this document be updated” I mean https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/bots/bots-context.

The documentation I was referencing that notes it only works on 3.0 is https://github.com/OfficeDev/BotBuilder-MicrosoftTeams

**Comment by clearab** [comment]
I'm updating the note at the top of this article.

**Comment by ncsurfus** [comment]
Awesome! I had managed to work around it, by manually implementing the functionality I needed based off the v3 SDK. I’ll take a look at the v4 preview. This should be a more supportable solution. Thank you for the update!
