### ISSUE TITLE
[MS teams] Adaptive card image partially rendered in MS Teams

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#3510]
Copied bug from: https://github.com/microsoft/AdaptiveCards/issues/5228 

**Details from original post:**
I'm generating dynamic images and include them as part of the adaptive card, the images are relatively small only 60kb, when I reply with the image for the first time, it's partially shown until I scroll up or leave the conversation I assume that triggers native update, as soon as image is cached it's loaded properly, the problem appears only with the first render

```
{
    "type": "AdaptiveCard",
    "version": "1.2",
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "body": [
        {
            "type": "TextBlock",
            "text": "Any text",
            "wrap": true
        },
        {
            "type": "Image",
            "url": "https://806168b00b02.ngrok.io/myimage"
        }
    ]
}
```

<img width="525" alt="Screen Shot 2020-12-17 at 10 57 14 AM" src="https://user-images.githubusercontent.com/27004732/103633874-5c0c6f80-4f57-11eb-8d1f-77313b12f489.png">

This is critical for us since we rely on the images while interacting with the bot, very annoying and questionable

https://stackoverflow.com/questions/65336959/adaptive-card-image-partially-rendered-in-ms-teams---
#### Document Details

⚠ *Do not edit this section.It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Cards reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **surbhigupta12**

**Comment by Nikitha-MSFT** [comment]
This is a known issue, as an alternative please specify certain dimensions for images. (BTW, "large" image isn't only defined by file size, but also defined by dimensions. 2048x2048 is way larger than suggested image size. Please keep it under 1024x1024 that may also mitigate this issue):
**Example:**
{
  "type": "AdaptiveCard",
  "version": "1.2",
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "body": [
    {
      "type": "TextBlock",
      "text": "Any text",
      "wrap": true
    },
    {
      "type": "Image",
      "height": "278px",
      "url": "https://downloader.disk.yandex.ru/preview/cd822ee5781b26835e94e77ed9e92d2285595d5ebfb02901589245db6adfbacd/60500591/2UE9Pp2COUhH4VU1rYwJk_iL3O2H09_AtmZs2uaaTNfxdb5p640e5pm0t2KjDFchjlRJbsogZxAfQpWoKHo4fg%3D%3D?uid=0&filename=teams_example.png&disposition=inline&hash=&limit=0&content_type=image%2Fpng&owner_uid=0&tknv=v2&size=2048x2048"
    }
  ]
}

**Comment by Nikitha-MSFT** [comment]
Bug is Resolved now, we have tested this at our end. Could you please test and confirm.

**Comment by Wajeed-msft** [comment]
Checking this with engineering team.

**Comment by v-chetsh** [comment]
@hdmiimdh - Could you please confirm if your issue has resolved or still looking for any help?
