### ISSUE TITLE
[Microsoft Teams Desktop][Accessibility - Usability] [MS Teams Adaptive card Multi select UX different in pop out app to normal app]

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#3511]
Copied bug from: https://github.com/microsoft/AdaptiveCards/issues/5226 

**Details from original post:**
# Platform

- MS Teams Desktop

# Author or host

Host - Adaptive card on MS Teams looks different from normal to pop out app

# Version 

Adaptive card 1.0 

# Details

MS Teams Adaptive card Multi-select UX different in pop out app to normal app. Same adaptive card designed using adapticard.io designer looks different from normal desktop MS Teams app to MS Teams desktop pop out app of the chat window.

Normal MS Teams window - Multiselect looks fine with checkboxes to multi select 

![image](https://user-images.githubusercontent.com/36985649/103547809-d8636c00-4edf-11eb-8b58-20475b2f6479.png)

Same chat window in pop out app mode, Multiselect control checbox is missing, rather it works in tag control mode which is a usability issue 
![image](https://user-images.githubusercontent.com/36985649/103547863-e913e200-4edf-11eb-8413-51352479e5c1.png)
---
#### Document Details

⚠ *Do not edit this section.It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Cards reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **surbhigupta12**

**Comment by Chetana-MSFT** [comment]
Hi @prasanthrpadharthi I am not able to repro the issue, so could you please share Adaptive card JSON file to look back in to the issue.

**Comment by Chetana-MSFT** [comment]
@prasanthrpadharthi Could you please confirm that your issue got resolved.
