### ISSUE TITLE
Action.OpenUrl cannot work when showing Adaptive Cards in Carousel format rendered in pop-out window

### ISSUE THREAD

**Issue by Mandy-Lf** [MicrosoftDocs/msteams-docs#3516]
Have several adaptive cards that contains ActionSet with Action.OpenUrl inside. In Teams, return these adaptive cards as a carousel. In normal windows, the Action.OpenUrl works as expected. If we open the chat in pop-out window, these Action.OpenUrl cannot work.
![image](https://user-images.githubusercontent.com/85094499/120145662-7866bc80-c216-11eb-9a58-b98b979ccf07.png)

**Comment by Chetana-MSFT** [comment]
Hi @Mandy-Lf Could you please share the JSON which describes your Adaptive card, So that we can repro at our end.

**Comment by Mandy-Lf** [comment]
Here are three files for three adaptive cards in the uploaded zip file. Each card are wrapped in a attachment, 
Here are sample codes we are using in C#
```
var atachment = new Attachment
            {
                Content = shareDocCard,
                ContentType = AdaptiveCard.ContentType
            };
```
and then in TeamsActivityHandler sends the attachments in the format of `MessageFactory.Carousel(attachements)` via `ITurnContext.SendActivityAsync`.

Then in the chat, we can see that the action buttons in each card can not work.
[3516.zip](https://github.com/MicrosoftDocs/msteams-docs/files/6572779/3516.zip)

**Comment by Chetana-MSFT** [comment]
Hi @Mandy-Lf, 

Could you please try with this sample code in Bot.cs file
```
 var attachments = new List<Attachment>();       
 var reply = MessageFactory.Attachment(attachments);
            reply.AttachmentLayout = AttachmentLayoutTypes.Carousel;
            reply.Attachments.Add(CreateAdaptiveCardAttachment("card1.json"));
            reply.Attachments.Add(CreateAdaptiveCardAttachment("card2.json"));
            reply.Attachments.Add(CreateAdaptiveCardAttachment("card3.json"));
```

**Comment by Mandy-Lf** [comment]
It seems that we are using the similar code.
We are using `MessageFactory.Carousel(attachements) `, and you suggest 
```
     var reply = MessageFactory.Attachment(attachments);
            reply.AttachmentLayout = AttachmentLayoutTypes.Carousel;
```
 Should they be the same?

Also for creating adaptive card, the sample code uses the following
```
            var adaptiveCardAttachment = new Attachment()
            {
                ContentType = "application/vnd.microsoft.card.adaptive",
                Content = JsonConvert.DeserializeObject(adaptiveCardJson),
            };
```
What we are using now is 
```
          var atachment = new Attachment
            {
                Content = AdaptiveCard.FromJson(adaptiveCardJson).Card,
                ContentType = AdaptiveCard.ContentType
            };
```
I didn't see any difference between my existing code vs your suggestions. Also this issue only occurs on the Teams Windows Desktop pop-out window. It seems that it's easy to reproduce on your side.

**Comment by Chetana-MSFT** [comment]
@Mandy-Lf, Could you please share your `Bot.cs `file. so, that we will repro with your code and get back to you.

**Comment by Chetana-MSFT** [comment]
Hi @Mandy-Lf  This issue got fixed in this [PR](https://domoreexp.visualstudio.com/Teamspace/_git/teams-modular-packages/pullrequest/347412) it will be available in R4/preview mode as soon as possible. Currently I am closing this bug, you can reopen if you are facing any issues.
