### ISSUE TITLE
Unable to receive channel message without mentioning bot

### ISSUE THREAD

**Issue by chialiyun** [MicrosoftDocs/msteams-docs#3531]
I followed the documentation where I added the webApplicationInfo inside manifest.json to include RSC permissions. However, I still do not receive any message activity when the bot is not mentioned in the message. 
```
"webApplicationInfo": {
    "id": "<i have updated app id here>",
    "resource": "https://AnyString",
    "applicationPermissions": [
      "ChannelMessage.Read.Group"
    ]
  }
```

Below is my code to echo the message:
```
protected override async Task OnMessageActivityAsync(ITurnContext<IMessageActivity> turnContext, CancellationToken cancellationToken)
        {
            await turnContext.SendActivityAsync(MessageFactory.Text($"Echo: {turnContext.Activity.Text}"), cancellationToken);
        }
```

I have checked against permissionGrant restful API (https://graph.microsoft.com/v1.0/groups/{groupid}/permissionGrants) and it includes "ChannelMessage.Read.Group"
```
{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#permissionGrants",
    "value": [
        {
            "id": "<id ....>",
            "deletedDateTime": null,
            "clientId": "<client id ...>",
            "clientAppId": "<client app id ...>",
            "resourceAppId": "<resource app id ...>",
            "permissionType": "Application",
            "permission": "ChannelMessage.Read.Group"
        }
    ]
}
```

Here is a screenshot of the current situation (bot still only receives the message when bot is @mentioned.)
![screenshot](https://user-images.githubusercontent.com/15521388/120338806-25305f00-c327-11eb-9a20-ff1136d9c42a.png)

Thanks in advance!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e0acfd2-0965-65f4-2200-ca06424a3976
* Version Independent ID: fd7f72fe-5dba-369a-c436-6140d232ad44
* Content: [Receive all channel messages with RSC - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/channel-messages-with-rsc)
* Content Source: [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md)
* Product: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **lajanuar**

**Comment by Jagadeesh-MSFT** [comment]
Hi @chialiyun, we are working on it, will we update you soon.
