### ISSUE TITLE
Adaptive cards as attachment

### ISSUE THREAD

**Issue by michaelwechner** [MicrosoftDocs/msteams-docs#3533]
See

"For some reason this is not documented very clearly, but what teams requires is for the "Card" to be created as an attachment, instead of just getting the response directly."

https://stackoverflow.com/questions/65849243/outgoing-webhook-what-is-the-format-of-the-response-message

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Cards reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference#adaptive-card)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Nikitha-MSFT** [comment]
Thank you for reporting the issue. The document Team will be followup and update the document.

**Comment by michaelwechner** [comment]
great, thanks!

Am 02.06.21 um 12:34 schrieb Nikitha-MSFT:
