### ISSUE TITLE
Incoming webhook @mention not work

### ISSUE THREAD

**Issue by zhouweiwei** [MicrosoftDocs/msteams-docs#3536]
#### Description

I send message  to incoming webhook with  Adaptive cards. but @mention not work .
I use json to send teams message.
but i have chinese chars in json. looks like this:
```
"msteams": {
                "width": "Full",
                "entities": [
                    {
                        "type": "mention",
                        "text": "<at>朱 晨</at>",
                        "mentioned": {
                            "id": "29:1YkwfFtLBsR3OqD_LXL9SFEbnqLGh8IPV09nPEwmcYVLLh9StMvcIxxxxxxxxGEwR8O6sLL2Ibr5mrZlnraeT8g",
                            "name": "朱 晨"
                        }
                    }
                ]
            }
```

https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?tabs=adaptive-md%2Cconnector-html#constructing-mentions

UserID is obtained through teams outgoing webhook.
![image](https://user-images.githubusercontent.com/5128051/120446287-fe703800-c3bb-11eb-9b64-961e8bb19a5f.png)

#### result 

![image](https://user-images.githubusercontent.com/5128051/120445842-9a4d7400-c3bb-11eb-8749-b2c2773a8f62.png)

### please help

**Comment by Mamatha-MSFT** [comment]
Hi @zhouweiwei -  The @mention for adaptive card will works only when you send the card from bot. Because the ms teams object will only work in bots not in incoming webhooks.
we recommend you to raise a Teams UserVoice [here ](https://microsoftteams.uservoice.com/)if this needs to be consider as a future request.

**Comment by Mamatha-MSFT** [comment]
we are closing this issue from our end and you can re open if you have further queries.
