### ISSUE TITLE
Page should be specific that Bot Framework v3 SDK is needed for Teams

### ISSUE THREAD

**Issue by aosolis** [MicrosoftDocs/msteams-docs#354]
- Link to "Bot Framework documentation" goes to v4 docs
- Page doesn't have specific guidance to use v3. Requirement is only implied by reference to Teams SDKs that require v3 as a dependency. It's a subtle point that's easy to miss.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 087ab52e-fa36-8255-1438-957f895ba583
* Version Independent ID: f19cdd18-9aef-2bb2-6c2f-e0f0f79b9ca0
* Content: [Create a bot - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/bots/bots-create)
* Content Source: [msteams-platform/concepts/bots/bots-create.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/bots/bots-create.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ericrrichards** [comment]
Is Teams support going to be moved to V4 of the Bot Framework at some point?  If so, what kind of timeline is that happening on?
As I understand it, V4 is a complete rewrite and basically involves throwing out any V3 code you may have written.

**Comment by Wajeed-msft** [comment]
@ealmeidamsft - We are working on support for v4. We don't have any timeline to share for the release.

**Comment by clearab** [comment]
You can find the roadmap for support for Bot Builder v4.x here: https://developer.microsoft.com/en-us/microsoft-teams/blogs/preview-release-of-net-teams-bot-builder-v4-sdk/

**Comment by tsahi** [comment]
Well, the road map states GA in March. We are in mid-April, and no GA yet.
