### ISSUE TITLE
Context.EntityId not populated in MS Teams webclient

### ISSUE THREAD

**Issue by koen-vissers** [MicrosoftDocs/msteams-docs#3541]
We have developed a custom tab in Microsoft Teams. Since a couple of weeks we're getting a complaints that the content on the Custom Tab is unable to load. Researching the issue, we see it is caused by the Context.EntityId being null/empty in Microsoft Teams **webclient**.

In desktop client, iOS/Android Teams App the Custom Tab works fine. The Custom Tab was working in webclient before.

(Could this be caused by recent changes for the Android Teams App #1335? The issue was raised around the time this change was rolled out).

**Comment by Mamatha-MSFT** [comment]
Hi @koen-vissers - Thanks for bringing up this issue. I will repro at my end will get back to you.

**Comment by Mamatha-MSFT** [comment]
Hi @koen-vissers  - I am unable to repro the issue. I am able to get the value of context.entityId on Teams web client. Could you please explain when exactly are you getting this issue.

**Comment by erniukas86** [comment]
Hi @Mamatha-MSFT, we are getting context using this function: microsoftTeams.getContext(), then we extracting context object and saving entityId to the session, but entityId appears to be null when using Teams from the browser (used Edge). When we are using it as a desktop app it works ok.

**Comment by Mamatha-MSFT** [comment]
@erniukas86 - Could you please share the Microsoft teams version details, SDK version and device details(windows or MAC).

**Comment by erniukas86** [comment]
@Mamatha-MSFT i'm using Windows 10 and Edge Browser for teams. 

There is my Microsoft edge version:

![image](https://user-images.githubusercontent.com/12614029/121647940-a0b8ab80-ca9f-11eb-9920-ecfb8e103e48.png)

Not sure what you mean by Microsoft teams version details since I'm using it from the browser, not a desktop app.

**Comment by Mamatha-MSFT** [comment]
@erniukas86  - We are unable to repro the issue from our end. We are able to get the entityId from static tab and channel tab. Could you please explain where exactly you're trying to get `context.entityId` (like in [configuration page](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/configuration-page#example) or channel tab).

**Comment by erniukas86** [comment]
@Mamatha-MSFT we are trying to get it from channel tab

**Comment by Mamatha-MSFT** [comment]
Hi @erniukas86  - Please check this working code 

**In configpage.cshtml** 

```
<head>
    <script src='https://statics.teams.cdn.office.net/sdk/v1.6.0/js/MicrosoftTeams.min.js'></script>
</head
 <script>
        microsoftTeams.initialize();
        microsoftTeams.settings.registerOnSaveHandler((saveEvent) => {
            microsoftTeams.settings.setSettings({
                websiteUrl: "https://7c0b9188a983.ngrok.io",
                contentUrl: "https://7c0b9188a983.ngrok.io/tab",
                entityId: "Configure",
                suggestedDisplayName: "Configure"
            });
            saveEvent.notifySuccess();
        });

        microsoftTeams.settings.setValidityState(true);

    </script>
```
    
    
    
`    
    **In tab.cshtml**
    
    
    
```
<script>
  microsoftTeams.initialize();
  microsoftTeams.getContext(function (context){alert(JSON.stringify(context));    console.log(context.entityId)});
 </script>

 <h1>Hello world</h1>

```

Please go through this sample
https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/tab-channel-group-quickstart
