### ISSUE TITLE
Missing Documentation on Outgoing Webhook Response Format

### ISSUE THREAD

**Issue by kevin-secrist** [MicrosoftDocs/msteams-docs#3551]
The example response in this document is very helpful for getting starting with a basic outgoing webhook. However, the document also mentions the different types of cards and actions that may go along with the response, but does not specifically state how to format the response in order to utilize those cards.

Another difficulty is that if you try to specify a more complicated response and do not follow the undocumented rules, you will be greeted by Teams with `Sorry, there was a problem encountered with your request` with no apparent path forward for troubleshooting this.

Please see also this [StackOverflow question](https://stackoverflow.com/questions/65849243/outgoing-webhook-what-is-the-format-of-the-response-message) along the same topic, which seems to hint at a requirement for cards to be specified as attachments.

I think some extra documentation around the acceptable responses here would be very helpful, and some potentially more "advanced" samples. For now, I've downgraded my application to just send back text responses so that I can move forward.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb9c5bd5-1ac6-dcc8-4ed6-d6aad2432776
* Version Independent ID: 43e90995-bba4-86b6-1f1c-ab749e546a4b
* Content: [Add custom bots to Microsoft Teams with outgoing webhooks - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-outgoing-webhook)
* Content Source: [msteams-platform/webhooks-and-connectors/how-to/add-outgoing-webhook.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/webhooks-and-connectors/how-to/add-outgoing-webhook.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Sridevi-MSFT** [comment]
@kevin-secrist - Could you please check this [sample ](https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/main/samples/outgoing-webhook/csharp/WebhookSampleBot/Models/SampleResponseProvider.cs) for different cards for response. Please make sure to append /api/sample to content URL while creating outgoing webhook.

**Comment by kevin-secrist** [comment]
Hi @Sridevi-MSFT, before making this issue I had come across that link in the SO post. It was not very helpful to me and I wouldn't classify it as a sample response. It also assumes you're using the `AdaptiveCards` and `Microsoft.Bot.Builder` C# packages which isn't helpful for someone who is crafting the response from scratch using the same or another language. The nodejs sample from that same repo does not give more than the basic "text" response.

It would be very helpful to have at least a rudimentary JSON schema or reference to see what allowable fields there are and the general shape of the payload to make the docs more accessible for this. For example, I think from what I've seen (like in the SO post) the response must be `text` and any cards must be specified as `attachments`, but that is not listed in the documentation anywhere - even though the docs _do_ mention that you can provide cards in the response.

This is all you get if you make a mistake:

![image](https://user-images.githubusercontent.com/1945074/120826301-4613d280-c528-11eb-915e-b5f179ce6138.png)

I think that's another problem entirely, but I'm just putting that here to reiterate why the documentation is so important.

**Comment by Sridevi-MSFT** [comment]
@kevin-secrist - The documentation team is working on this. You can track this from here.https://github.com/MicrosoftDocs/msteams-docs/issues/3533#event-4869168147

**Comment by kevin-secrist** [comment]
Closed by https://github.com/MicrosoftDocs/msteams-docs/pull/3596

Thanks all, docs for this are a lot better now 👍
