### ISSUE TITLE
Action.OpenUrl not working in Teams meeting chat for guest users

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#3553]
Copied bug from: https://github.com/microsoft/AdaptiveCards/issues/5940 

**Details from original post:**
If a person is logged into the Teams tenant with a guest user (Microsoft account or out of tenant Office 365 account ) and click a button in an Adaptive Card with an Action.OpenURL in a meeting chat, they get a strange error message: "This card action is not supported by . " It seems Action.OpenUrl is not working properly for tenant guests/anonymous users.
![image](https://user-images.githubusercontent.com/17601161/120084562-8d860300-c0d1-11eb-897e-3203628642c3.png)
---
#### Document Details

⚠ *Do not edit this section.It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Cards reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **surbhigupta12**

**Comment by Mamatha-MSFT** [comment]
Hi @figgsoftware - I have reproduced the same scenario by creating a meeting and added a guest user to that meeting. When guest user clicks on adaptive card Action.openUrl button in teams meeting chat and it's working fine as expected on Teams web and desktop client.

**Comment by figgsoftware** [comment]
Great @Mamatha-MSFT ! Let us know if you need any info from our side.

**Comment by Mamatha-MSFT** [comment]
@figgsoftware - The context from my above comment is that I am unable to repro the issue. It's working completely fine at our end. 
Could you please share your adaptive card json and also share your teams client details.

**Comment by figgsoftware** [comment]
@Mamatha-MSFT  The strange thing is that we can no longer repro it either :) I guess a fix have been rolled out...

**Comment by Mamatha-MSFT** [comment]
@figgsoftware - Good to hear that issue is resolved. Thanks for confirming on the same with us.
