### ISSUE TITLE
Messaging extensions: Missing Input.ChoiceSet options in adaptive card

### ISSUE THREAD

**Issue by clearab** [MicrosoftDocs/msteams-docs#3556]
Migrating this issue: https://github.com/microsoft/botbuilder-js/issues/3169#

Original internal bug is here: https://domoreexp.visualstudio.com/MSTeams/_workitems/edit/1437562?tracking_data=ew0KICAic291cmNlIjogIkF6dXJlRGV2T3BzVGVhbXNBcHAiLA0KICAic291cmNlX2V2ZW50X25hbWUiOiBudWxsDQp9

**Comment by Ravindra-MSFT** [comment]
HI @rmincheva Issue got resolved from our end. Please let us know if you face any issues.
