### ISSUE TITLE
Whitelist

### ISSUE THREAD

**Issue by Josverl** [MicrosoftDocs/msteams-docs#356]
is the term 'Whitelisting' not more appropriate to this scenario ?
it makes sense to whitelist or blacklist tenants bases on different business scenarios

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f51c9ae1-b874-2d55-1737-da73e292db3c
* Version Independent ID: c3d03f64-058e-6177-fff7-59bb5799a60c
* Content: [Bots for limited tenants - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/scenarios/limited-tenant)
* Content Source: [msteams-platform/scenarios/limited-tenant.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/scenarios/limited-tenant.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by billbliss** [comment]
The term whitelist and blacklist are not culturally sensitive.

**Comment by Josverl** [comment]
Understood, You have a point there

Regards,
Jos Verlinde

________________________________
