### ISSUE TITLE
Configuration steps

### ISSUE THREAD

**Issue by laurentkempe** [MicrosoftDocs/msteams-docs#3560]
Hi,

On step 1 of [Configuration steps](https://docs.microsoft.com/en-us/microsoftteams/platform/toolkit/visual-studio-overview#configuration-steps) there is a mention of "Microsoft Teams Toolkit landing page". Where can I find this? It is not obvious for people trying this for the first time, like me.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7a0c9e9-d1d1-b412-4d6c-a7f16237c8ab
* Version Independent ID: b4960863-6765-b6f2-3fd8-c9316f2cb2e8
* Content: [Build apps with the Microsoft Teams Toolkit and Visual Studio - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/toolkit/visual-studio-overview)
* Content Source: [msteams-platform/toolkit/visual-studio-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/toolkit/visual-studio-overview.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Mamatha-MSFT** [comment]
Hi @laurentkempe  - After [Teams Toolkit installation ](https://docs.microsoft.com/en-us/microsoftteams/platform/toolkit/visual-studio-overview#install-the-teams-toolkit) the Teams toolkit Icon will be added to the activity bar as shown in below image. Click on that icon to get  Microsoft Teams Toolkit landing page

![image](https://user-images.githubusercontent.com/78795357/120787816-61450900-c54d-11eb-842d-86b2c4b9191c.png)

**Comment by laurentkempe** [comment]
Hi @Mamatha-MSFT
The link I gave and that you link back with "[Teams Toolkit installation](https://docs.microsoft.com/en-us/microsoftteams/platform/toolkit/visual-studio-overview#install-the-teams-toolkit)" is about Visual Studio. The screenshot you linked is about Visual Studio Code. I am working with Visual Studio not Visual Studio Code. So, in Visual Studio where is the "Microsoft Teams Toolkit landing page"?

**Comment by Mamatha-MSFT** [comment]
Hi @laurentkempe After installing [Microsoft Teams App](https://marketplace.visualstudio.com/items?itemName=TeamsDevApp.vsteamstemplate) and [Teams Toolkit](https://marketplace.visualstudio.com/items?itemName=msft-vsteamstoolkit.vsteamstoolkit) from market place. 

- Open visual studio --> click on create a new project --> select Microsoft Teams app with quick start tool as shown in below image.

  
![image](https://user-images.githubusercontent.com/78795357/120805685-affd9d80-c563-11eb-9a96-47f401bb7308.png)

- Follow the steps provided in the [Set up a new Teams project section](https://docs.microsoft.com/en-us/microsoftteams/platform/toolkit/visual-studio-overview#set-up-a-new-teams-project) and you will get a landing page as shown in below image.

![image](https://user-images.githubusercontent.com/78795357/120807439-92313800-c565-11eb-920a-dc59f8f71d9e.png)

**Comment by laurentkempe** [comment]
Hi @Mamatha-MSFT

Ok I see the landing page now.
The documentation "[Install the Teams Toolkit](https://docs.microsoft.com/en-us/microsoftteams/platform/toolkit/visual-studio-overview#install-the-teams-toolkit)" mention the following

    The Microsoft Teams Toolkit for Visual Studio is available for download from the Visual Studio Marketplace or directly from the Extensions menu within Visual Studio.

When you navigate to the extension then you read the following

    This extension is deprecated and will be removed in the future. Please consider trying the Teams Toolkit, which is the         
    recommended way to create, debug, and deploy Teams apps directly from Visual Studio 2019 and Visual Studio Code.

    Teams Toolkit for Visual Studio Code

    Teams Toolkit for Visual Studio 2019

So, I went to the Teams Toolkit for Visual Studio 2019 and installe only that!

I think the documentation and Visual Studio Addon should better document what is needed because it is not clear at all.

Thanks @Mamatha-MSFT for your help no it is clear.
