### ISSUE TITLE
Unstable error "BadGateway" at sending activities

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#3561]
Copied from:  https://github.com/microsoft/botframework-sdk/issues/6302
Raised by: @WhiteCyClop

**Description:**
A few weeks ago I noticed that sometimes my bot throws an error "Microsoft.Bot.Schema.ErrorResponseException: Operation returned an invalid status code 'BadGateway'" when it tried to send activity to user. This is the stack of error:

```
Microsoft.Bot.Schema.ErrorResponseException: Operation returned an invalid status code 'BadGateway'
at Microsoft.Bot.Connector.Conversations.ReplyToActivityWithHttpMessagesAsync(String conversationId, String activityId, Activity activity, Dictionary`2 customHeaders, CancellationToken cancellationToken)
at Microsoft.Bot.Connector.ConversationsExtensions.ReplyToActivityAsync(IConversations operations, String conversationId, String activityId, Activity activity, CancellationToken cancellationToken)
at Microsoft.Bot.Builder.BotFrameworkAdapter.SendActivitiesAsync(ITurnContext turnContext, Activity[] activities, CancellationToken cancellationToken)
at Microsoft.Bot.Builder.TurnContext.<>c__DisplayClass29_0.<<SendActivitiesAsync>g__SendActivitiesThroughAdapter|1>d.MoveNext()
```
The strangest thing is unstable behavior of this error. For example, a bot can send several adaptive cards to the user one after one within several seconds and for 9 out of 10 there is no any problem, but for the one in the middle of this pool there is an error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f83b32eb-4265-39bd-e52f-78daf388d1ad
* Version Independent ID: eacbd346-f794-3d91-2eef-227b1a126c31
* Content: [Conversation basics - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-basics)
* Content Source: [msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/bots/how-to/conversations/conversation-basics.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **anclear**

**Comment by WhiteCyClop** [comment]
What exactly information do you need from author?

**Comment by Wajeed-msft** [comment]
Apologies  for this. Reopening the issue.

**Comment by Wajeed-msft** [comment]
@WhiteCyClop - Apologies for delays, could you please help to share recent timestamp for the issue? I already have Bot Id shared i.e. 575a5ae9-e730-416a-8c23-9704f9cb2664.

**Comment by WhiteCyClop** [comment]
@Wajeed-msft, I don't have this type of error at least last month. Perhaps the reason is the fact that I set some delay when sending messages to users - I had an assumption that there are some Azure's restrictions on sending a large number of messages at the same time. Or maybe something was changed in the MS components/infrastructure

**Comment by Wajeed-msft** [comment]
@WhiteCyClop - Throttling limits for sending messages from Bot is documented here in [Optimize your bot with rate limiting in Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/rate-limit#per-bot-per-thread-limit). 

I am closing this for now, could you please ping on this thread if you face this issue again?
