### ISSUE TITLE
Stage View - Is it available in Public dev preview?

### ISSUE THREAD

**Issue by SubbaReddi** [MicrosoftDocs/msteams-docs#3566]
Dev preview is enabled. Tried to open stage view using deep link and with adaptive card action.openURL, but the tab which opens is showing blank.
Is it available in Public dev preview?

**Comment by Nikitha-MSFT** [comment]
We are able to repro the issue at our end. Raised a bug

**Comment by Nikitha-MSFT** [comment]
We are tracking the bug internally, we don't have ETA to share when it will be fixed.  We will update once it is fixed.

**Comment by ChetanSharma-msft** [comment]
@Archish27 - We will check on it from our end and get back to you.
