### ISSUE TITLE
Are Action.Http and Action.Execute support for Adaptive Card from Incoming Webhooks?

### ISSUE THREAD

**Issue by nastassiar** [MicrosoftDocs/msteams-docs#3567]
Action.Execute was recently added for Adaptive cards is it supported?

There is also a not on the page that says: 

" All native adaptive card schema elements, except Action.Submit, are fully supported.

The supported Actions are Action.OpenURL, Action.ShowCard, and Action.ToggleVisibility"

This makes it unclear whether or not Action.Http is supported

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28316a67-22fa-8a05-1ae0-fbe1c5720ef9
* Version Independent ID: 8a250e46-2a30-af86-839d-9f83a8b48041
* Content: [Sending messages to Connectors and Webhooks - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-using)
* Content Source: [msteams-platform/webhooks-and-connectors/how-to/connectors-using.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/webhooks-and-connectors/how-to/connectors-using.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Sridevi-MSFT** [comment]
@nastassiar - Thanks for reaching out to us. Let us check this at our end and will get back to you.

**Comment by Sridevi-MSFT** [comment]
@nastassiar - Action.Http feature only works for actionable messages(outlook) whereas Action.Execute is a new feature that can be used as a replacement for Action.Submit(currently used by Bots) and Action.Http. So, these two actions won't work for Incoming Webhook.
