### ISSUE TITLE
Are mentions limited to users?

### ISSUE THREAD

**Issue by nastassiar** [MicrosoftDocs/msteams-docs#3568]
In the documentation everything to do with mentions just references users. Is it possible to @ mention  a group or channel? And if so how do you differentiate between which items in the mentions are users and which are groups or channels?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b31b49dc-2890-fbb9-1b30-a3f93469d1e6
* Version Independent ID: f9877c67-43d2-78a5-dcf2-fd0ca4de2339
* Content: [Channel and group conversations with a bot - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/channel-and-group-conversations?tabs=dotnet#constructing-mentions)
* Content Source: [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md)
* Product: **msteams**
* GitHub Login: @clearab
* Microsoft Alias: **anclear**

**Comment by Mamatha-MSFT** [comment]
Hi @nastassiar - Currently from bot  you can only @mention user.  If you want to @mention the channel or team you need to do it manually.

**Comment by clearab** [comment]
What does manually mean in this context?

**Comment by Mamatha-MSFT** [comment]
@clearab -  You need to @mention team or channel name in Compose message area.
