### ISSUE TITLE
Why I should use SDK in Bot authorisation flow

### ISSUE THREAD

**Issue by Coderast** [MicrosoftDocs/msteams-docs#3569]
I want to implement authorisation flow for MS Teams Bot and see that I should use MS Teams SDK for it (initialise and notifySuccess methods). But what is reason to do it if I will start auth flow in new tab, but not in pop-up like for tabs flow?   

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d1ce448-e51e-73db-ba9a-53faf4a16d11
* Version Independent ID: 09c2500a-3841-c6c9-82c0-5e10dc2d9c7c
* Content: [Microsoft Teams Authentication flow for bots - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/authentication/auth-flow-bot)
* Content Source: [msteams-platform/bots/how-to/authentication/auth-flow-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/bots/how-to/authentication/auth-flow-bot.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Ravindra-MSFT** [comment]
HI @Coderast We can also authorize the user in the new tab with out using any SDK in the authorization flow but, we cannot retrieve the user details from the tab context, whereas if we authorize the user through SDK we can get users details in tab context using microsoftteams.getcontext which will be used to get some access from user. Please go through the [documentation](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/authentication/add-authentication?tabs=dotnet%2Cdotnet-sample) for your reference.

**Comment by v-chetsh** [comment]
@Ravindra-MSFT - Could you please confirm if your issue has resolved or still looking for any help?
