### ISSUE TITLE
HTTP error 400

### ISSUE THREAD

**Issue by endiom** [MicrosoftDocs/msteams-docs#3571]
"INCstring(215) "Webhook message delivery failed with error: Microsoft Teams endpoint returned HTTP error 400 with ContextId tcid=0,server=msgapi-production-wuk-azsc6-1-44,cv=Bsl8E+rFTkyPhteKHUmpOQ.0,MS-CV=Bsl8E+rFTkyPhteKHUmpOQ.0.." 

loading data from json as $str to an ActionCard 

 "sections": [
    {
      "activityTitle": "text",
       "facts": $str,
       "text": $text
    }

Once the records are too many the error occurred (screenshot of json),  is there a maximum length for attribute "facts"? 
How to get rid of it?

![image](https://user-images.githubusercontent.com/17062300/120968176-d17ba680-c768-11eb-82c5-baf1d607aa08.png)

**Comment by Ravindra-MSFT** [comment]
HI @endiom Could you please provide JSON file. So that I can repro from my end and come back to you.

**Comment by endiom** [comment]
[imooc.txt](https://github.com/MicrosoftDocs/msteams-docs/files/6610019/imooc.txt)
Could not upload .json so rename to *.txt

64"INCstring(215) "Webhook message delivery failed with error: Microsoft Teams endpoint returned HTTP error 400 with ContextId tcid=0,server=msgapi-production-wuk-azsc6-2-34,cv=YLGCG9x1ZECkceTLTHjMPA.0,MS-CV=YLGCG9x1ZECkceTLTHjMPA.0.." 


If I deleted some records, make it less it works.

**Comment by Ravindra-MSFT** [comment]
Hi @endiom There is a Limit of conversation size in Teams Channel. Make sure that you can send a card size not more than 28KB approximately. You can also go through the [docs](https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams#teams-and-channels) of limitation for you reference



![image](https://user-images.githubusercontent.com/84447722/121136959-d9fcdb80-c853-11eb-9974-ad29b701af81.png)

**Comment by endiom** [comment]
noted and thanks.
btw the post size should be extended as html, css, or rich text that are literally count.
Hope we can reach to that point in future.
