### ISSUE TITLE
Teams contacts - GUI for adding people into Contacts groups is broken

### ISSUE THREAD

**Issue by maksokami** [MicrosoftDocs/msteams-docs#3574]
Since the last update in our org Teams GUI of adding contacts to groups has been broken.
When you click on Contacts, select a group and click "Add a contact to this group" the dialog appears. Previously people list appeared right under the dialog search input field as you start typing. As of the update the list of people now appears in the bottom right corner, so far that a vertical scroll bar is created in the teams window. Only the top person is visible and selectable in the list. If I click on the window scrollbar, the dialog closes and I can't select anything. There is a tiny square of a scrollbar on the list of people also, which doesn't close the search dialog, so you can actually add people. It's hard to catch and it's almost impossible to scroll it though.

Thank you

Microsoft Teams Version 1.4.00.11161 (64-bit). Updated on 5/18/2021

![teams-bug-gui-may-2021](https://user-images.githubusercontent.com/525382/121040020-32aa7680-c777-11eb-9fa8-b026b2b4b8eb.png)

**Comment by Jagadeesh-MSFT** [comment]
Hi @maksokami, we are working on it , will update you soon.
