### ISSUE TITLE
Device Permissions: allow requesting clipboard permission

### ISSUE THREAD

**Issue by tchapeaux** [MicrosoftDocs/msteams-docs#3588]
As an app developer, I would like my Tab app to be able to write to the user's clipboard. This does not seem possible currently.

Technically, this would be supported by the browser [Permissions Policy](https://w3c.github.io/webappsec-permissions-policy/), by adding an option to the `allow` attribute of the embedded `iframe`.
https://web.dev/async-clipboard/#permissions-policy-integration

I would like to be able to declare in my manifest that I use the `clipboard-write` permission, and have the `iframe` in Microsoft Teams that will embed my app to include it.

Feel free to reach out if you need more context.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19804dba-009f-2eb1-cc7f-1e0fabbebb6b
* Version Independent ID: a9373e78-b3c9-7182-d253-5ac8d8988936
* Content: [Request device permissions for your Microsoft Teams app - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?tabs=desktop)
* Content Source: [msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/device-capabilities/native-device-permissions.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Sridevi-MSFT** [comment]
@tchapeaux  - Thanks for your insights. Taking this for internal discussion with team and will get back to you.

**Comment by Sridevi-MSFT** [comment]
@tchapeaux - Microsoft will always focus on customer’s feedback and experience, some new features would be added to the services based on customers' feedback in the future, we also recommend you give your new idea in Teams [UserVoice ](https://microsoftteams.uservoice.com/)here. If this needs to be consider as a future request.

**Comment by tchapeaux** [comment]
Thanks for your reply. So to clarify, there is no way for a Microsoft Teams app to write to the user's clipboard currently? 

This feature would be useful for us as we have some "click to copy" button as part of our UI. This is also a [frequent UI element](https://www.w3schools.com/howto/howto_js_copy_clipboard.asp) that we feel many App users and developers would expect to be available.

**Comment by Sridevi-MSFT** [comment]
@tchapeaux - Could you please try this [sample](https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/d1eeeb069c04e3fc02c2b5e533f4bfe810d24a57/samples/connector-generic/nodejs/views/connectorconfig.jade#L57) code for copy to clipboard.

```
script(type='text/javascript').                                            
        function copyWebhookToClipborad() {
            var copyText = document.getElementById("webhook");
            copyText.select();
            document.execCommand("copy");
            if(copyText.value.length<=0)
            {
                alert("Some Error");
            }
        }
```

**Comment by tchapeaux** [comment]
Our current code does indeed use this method as a fallback, but it appears to be blocked on the latest version of MsTeams.

Also, the `document.execCommand` function is [deprecated and no longer recommended](https://developer.mozilla.org/en-US/docs/Web/API/document/execCommand). Some browsers may drop support in the future.

If possible, we would like to use the [Clipboard API] instead, which is the current recommended way of accessing the clipboard.

**Comment by Wajeed-msft** [comment]
@tchapeaux - I have shared this with engineering team. Could you please also Post feature suggestions on [Microsoft Teams feedback portal on UserVoice](https://microsoftteams.uservoice.com/forums/555103-public-preview/category/182881-developer-platform)?

**Comment by tchapeaux** [comment]
Thanks for sharing it with the team!

I see on UserVoice that there already was a ticket here:
https://microsoftteams.uservoice.com/forums/555103-public/suggestions/43055961-allow-clipboard-api-access-on-custom-teams-apps
So I voted for it instead of creating a new one.

We would love to hear about any news on this :)

**Comment by Wajeed-msft** [comment]
Thanks @tchapeaux- closing this from documentation issues repo. Best place to track this feature ask would be via user voice. In case if I get some update, I'll post it on this thread as well.
