### ISSUE TITLE
Can I rely to Azure user's ids for mapping and provisioning?

### ISSUE THREAD

**Issue by Coderast** [MicrosoftDocs/msteams-docs#3590]
I see that in [this page](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-messages?tabs=json#receive-a-message) I can receive `from.aadObjectId` and `channelData.tenant.id`. Will I receive these ids **always** if user authenticated in MS Teams and messaging with bot? Can I use it to map MS Teams user with inner representation of user?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afbc5b84-5be5-b5c4-30c0-58782a748a03
* Version Independent ID: ef6b8aee-52e7-f5d4-7dfa-8f34a1698330
* Content: [Messages in bot conversations - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-messages?tabs=json#receive-a-message)
* Content Source: [msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/bots/how-to/conversations/conversation-messages.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **anclear**

**Comment by Ravindra-MSFT** [comment]
HI @Coderast Yes `aadObjectId` and `channelData.tenant.id` will get always when user authorize the bot. And could you explain what exactly inner representation of user?

**Comment by Coderast** [comment]
@Ravindra-MSFT I have some user entity in my internal system and I want to match MS Teams user with user in internal system.

**Comment by Ravindra-MSFT** [comment]
@Coderast Yes, you can map Internal system  user entity with MS Teams user.

**Comment by Coderast** [comment]
@Ravindra-MSFT thanks! This info helps me.
