### ISSUE TITLE
Authorization header in events from MS teams Bot

### ISSUE THREAD

**Issue by Coderast** [MicrosoftDocs/msteams-docs#3593]
How can I validate Authorization header value when receive events [such these](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/subscribe-to-conversation-events?tabs=dotnet)? As I see I received Bearer JWT token, but how I can validate it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a6d00a4-dd28-33c4-002e-2e8e7c653ce2
* Version Independent ID: 0856927a-25f4-b1e0-5f1b-d55dc61796f3
* Content: [Conversation events - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/subscribe-to-conversation-events?tabs=dotnet)
* Content Source: [msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md)
* Product: **msteams**
* GitHub Login: @WashingtonKayaker
* Microsoft Alias: **anclear**

**Comment by Nikitha-MSFT** [comment]
Are you trying to validate the auth token? if yes could you please check [Validating tokens](https://docs.microsoft.com/en-us/azure/active-directory/develop/access-tokens#validating-tokens)?

**Comment by Nikitha-MSFT** [comment]
@Coderast - Are you still facing the issue? if yes Could you please update.
