### ISSUE TITLE
Full width Adaptive card - Wrong image example?

### ISSUE THREAD

**Issue by Fradantim** [MicrosoftDocs/msteams-docs#3594]
[Enter feedback here]
See [Sample adaptive card with full width](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?tabs=adaptive-md%2Cconnector-html#sample-adaptive-card-with-full-width)

I may be seeing it wrong, but both example images seem to be the exact same, only resized. Shouldn't this property affect how adaptive cards are rendered in ms-teams?

> "A full width Adaptive Card appears as follows:"

![image](https://docs.microsoft.com/en-us/microsoftteams/platform/assets/images/cards/full-width-adaptive-card.png)

> "If you have not set the width property to Full, then the default view of the Adaptive Card appears as follows:"

![image](https://docs.microsoft.com/en-us/microsoftteams/platform/assets/images/cards/small-width-adaptive-card.png)

Greetings.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 001a12ea-30fa-d626-18a9-02a518bfb37f
* Version Independent ID: e5f5f69e-66e9-d1b2-e19a-485d0ffcd6fa
* Content: [Text formatting in cards - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?tabs=adaptive-md%2Cconnector-html#sample-adaptive-card-with-full-width)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-format.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-format.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Sridevi-MSFT** [comment]
@Fradantim - Thanks for your insights. The documentation team will update the changes.

@v-abirade - Please update the [documentation](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?tabs=adaptive-md%2Cconnector-html#sample-adaptive-card-with-full-width) with following images.

A full width Adaptive Card appears as follows:



![Capture01](https://user-images.githubusercontent.com/80752198/121508272-0c007000-ca03-11eb-95f3-4c7fbeedef15.PNG)


If you have not set the width property to Full, then the default view of the Adaptive Card appears as follows:

![Capture02](https://user-images.githubusercontent.com/80752198/121508395-2a666b80-ca03-11eb-8027-f82bfbb086ee.PNG)
