### ISSUE TITLE
Bot command list did not change after install new manifest.

### ISSUE THREAD

**Issue by jeffwu85182** [MicrosoftDocs/msteams-docs#3598]
Hi, 

I have a question about modifying the bot command list in the manifest file.

Even I have removed some command that is no longer used; it's still displayed in the command list after installation.

I am not sure which parts are wrong or something I did not note.

Thanks,
Jeff

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5bbd808-dea0-7b88-b49d-c4e96882ebb8
* Version Independent ID: 2e744b7e-84af-4659-3a24-75faf09b52e6
* Content: [Add a bot menu - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bots-menus)
* Content Source: [msteams-platform/resources/bot-v3/bots-menus.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/resources/bot-v3/bots-menus.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Nikitha-MSFT** [comment]
We are not able to repro the issue at our end. Could you please try changing the app version also before installing new manifest please uninstall the previous instance of the application. Try if that helps.

**Comment by jeffwu85182** [comment]
> We are not able to repro the issue at our end. Could you please try changing the app version also before installing new manifest please uninstall the previous instance of the application. Try if that helps.

Could you provide more detail about that uninstall the previous instance of the application?
For uninstallation, I right-click the bot app and choose the uninstall option.

**Comment by Nikitha-MSFT** [comment]
Could you please try signin/signout?

**Comment by jeffwu85182** [comment]
> Could you please try signin/signout?

Yes, I have tried it, still no luck.

We create a bot app by App Studio on Teams, and we have a requirement that removes one of the commands in the bot command list. From my understanding, we only need to remove the command from the manifest file, then re-install the bot by click the install button in the `Test and Distribute` section. Is anything I missed?

**Comment by Nikitha-MSFT** [comment]
Is the issue is facing by everyone who has the previous version of app? Could you please conform?

**Comment by jeffwu85182** [comment]
Yes, we have tried installing the app in the testing org teams, which did not install before, and it is working fine with showing the correct command menu. But for others that have installed the previous version, even removed and reinstall the new app, the command menu is not updated.

**Comment by Nikitha-MSFT** [comment]
We are Not able to repro the issue at our end. Could you please share both the manifest, so we can test at our end.

**Comment by jeffwu85182** [comment]
Sorry for the late reply. Can we discuss this issue by email?

**Comment by Nikitha-MSFT** [comment]
Please Drop a mail to microsoftteamsdev@microsoft.com

**Comment by v-chetsh** [comment]
@jeffwu85182 - Could you please confirm if your issue has resolved or still looking for any help?
