### ISSUE TITLE
Instruction is broken, don't know how to get the mainfest file for .net

### ISSUE THREAD

**Issue by MaxMeng1985** [MicrosoftDocs/msteams-docs#3605]
The instruction is broken in step 3 of section:
**Use App Studio to update the app package**

I couldn't find any mainfest file for .Net, and I don't know how to generate one using Visual Studio.  Therefore, I have nothing to import in step 4.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f98c73d-bb68-3088-6e7d-2c576a8292f6
* Version Independent ID: 08b9df7d-4997-c681-e73a-235ec1e4fc7b
* Content: [Tutorial - Create your first app using C# - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tutorials/get-started-dotnet-app-studio)
* Content Source: [msteams-platform/tutorials/get-started-dotnet-app-studio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tutorials/get-started-dotnet-app-studio.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Mamatha-MSFT** [comment]
Hi @MaxMeng1985 - First you need to download the samples as instructed [here ](https://docs.microsoft.com/en-us/microsoftteams/platform/tutorials/get-started-dotnet-app-studio#download-the-sample) in documentation. Example if you are trying this [hello world sample](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/app-hello-world/csharp) you need to zip the [manifest folder](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/app-hello-world/csharp/Microsoft.Teams.Samples.HelloWorld.Web/Manifest) and upload.

**Comment by Mamatha-MSFT** [comment]
Hi @MaxMeng1985  - Please let us know if your issue has been resolved.

**Comment by MaxMeng1985** [comment]
Hi Mamatha,
Thanks for the follow up, yes, I guess that would work.  Please consider to edit the document for the same, it might help the others.

**Comment by Mamatha-MSFT** [comment]
@MaxMeng1985 - Thank you for the insights on the document. Our document team will work on it.
