### ISSUE TITLE
Android Teams app: App Permissions missing

### ISSUE THREAD

**Issue by oyvindam** [MicrosoftDocs/msteams-docs#3607]
Hi.

The menu for App Permissions is missing on thecurrent Teams-app on Android.
App-version: 1416/1.0.0.2021063702/0602
Android-version:  10

#3305 looks like the same exact problem , but for iOS in that case.
 
Following the docs on requesting permissions for apps on [Request device permissions for your Microsoft Teams app](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?tabs=mobile). 
 
* Any attempts to request camera using selectMedia throws Error Code 1000 PERMISSION_DENIED.  
* There are no user prompts displayed. 
* The app manifest contains `"devicePermissions": ["media"]`.

**The docs display the settings [like this](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?tabs=mobile#tabpanel_1_mobile):**

![image](https://user-images.githubusercontent.com/1383443/121688202-7973d580-cac3-11eb-8547-e1829c7721db.png)

**No App Permissions present on this version:**

![image](https://user-images.githubusercontent.com/1383443/121687285-76c4b080-cac2-11eb-8526-700f11be9199.png)

**Comment by Mamatha-MSFT** [comment]
Hi @oyvindam - Thanks for bringing up this issue. I am able to reproduce the issue. We will raise a bug and will inform you.

**Comment by Mamatha-MSFT** [comment]
@oyvindam - I have created a bug for this issue and concerned engineering team is working on this.

**Comment by oyvindam** [comment]
An update on this from my end:
Requesting camera using selectMedia/captureImage **now works fine** on version 1416/1.0.0.2021074803/0613.
User is prompted to give permissions and the in-app camera works as expected.

The app permissions menu is still missing, but that may have been removed by design afaik.

**Comment by Mamatha-MSFT** [comment]
@oyvindam  - The concerned engineering team is working on this. We will update you if the issue gets resolved. Currently we don’t have any ETA to share.

**Comment by oyvindam** [comment]
This is working now. The app permissions menu has reappeared on both iOS and Android and the camera functionality works as expected.
