### ISSUE TITLE
Changing connector name and description in manifest does not change the information in 'Connectors' list

### ISSUE THREAD

**Issue by crow-ua** [MicrosoftDocs/msteams-docs#363]
I had a following manifest for a connector:
```
"description": {
    "full": "conn1",
    "short": "conn1"
  }
"name": {
    "full": "conn1",
    "short": "conn1"
  }
```
The I've decided to rename it. I removed it from the team completely via Manage Team -&gt; Apps menu, performed logout/log in and cleared application data (I'm using web Teams version), changed `conn1` to `conn2` in manifest everywhere, re-uploaded it, and after that my connector still shows the old name in the Channel -&gt; Connectors list. 
I created a new team and uploaded new manifest there, and the connector is still displayed with the old name there. Note - when I click 'Configure' the new name is displayed in the popup.
**UPDATE**
Connector messages in chat also posted from the old "name" (conn1). It's extremely annoying.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0fd8e4d-f110-36f8-5bd3-db3325b14c01
* Version Independent ID: 717ea854-1d3a-2c15-e495-b6f170fe7aff
* Content: [Using Office 365 Connectors - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/connectors/connectors-using#setting-up-a-custom-incoming-webhook)
* Content Source: [msteams-platform/concepts/connectors/connectors-using.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/connectors/connectors-using.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Wajeed-msft** [comment]
@crow-ua - Could you please try updating the name in [Connector Dashboard Portal](https://outlook.office.com/connectors/publish)? 
![image](https://user-images.githubusercontent.com/31851992/49720696-80b59080-fc86-11e8-9b14-1e5c363e625e.png)

Please let us know if you are able to see updated name.

**Comment by crow-ua** [comment]
> Please let us know if you are able to see updated name.

Yes, I do. So it looks like connector settings are overriding the manifest. If one decides to use the same connector for different environments, it's not very convenient.
