### ISSUE TITLE
check device permission in client

### ISSUE THREAD

**Issue by NewFuture** [MicrosoftDocs/msteams-docs#3632]
When disabled the permission in the client for a  test app. the check permission status is still `granted`. 
```js
await navigator.permissions.query({ name: 'microphone' })

{state: "granted", onchange: null}
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19804dba-009f-2eb1-cc7f-1e0fabbebb6b
* Version Independent ID: a9373e78-b3c9-7182-d253-5ac8d8988936
* Content: [Request device permissions for your Microsoft Teams app - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?tabs=desktop)
* Content Source: [msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/device-capabilities/native-device-permissions.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Ravindra-MSFT** [comment]
Hi @NewFuture, Thanks for reaching out us. Could you please share more info, for which device you are trying to access the permissions (Desktop or Mobile).

**Comment by NewFuture** [comment]
@Ravindra-MSFT the Desktop Client App

**Comment by Ravindra-MSFT** [comment]
Hi @NewFuture, Currently, Microsoft Teams support for media capabilities is only available for mobile clients.
You can go through this in [docs](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?tabs=desktop#access-device-permissions).
![image](https://user-images.githubusercontent.com/84447722/122713616-98bcf080-d283-11eb-9ba2-adfd1476ddaa.png)
