### ISSUE TITLE
Contrary to this article App Studio is available in GCC

### ISSUE THREAD

**Issue by npherson** [MicrosoftDocs/msteams-docs#3638]
App Studio released to GCC a long time ago. These kinds of quality issues in the platform docs have been a significant roadblock to achieving FY21 platform scorecard metrics. Anything that can be done to get the product group to review all the Teams Platform documentation to accurately call out what is and what is not expected to work in GCC would be much appreciated - FY22 is likely to have this as an even larger emphasis item.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f4a41f1-2993-7869-a1ab-b83cb6225d7e
* Version Independent ID: c000998f-9192-50fb-6a0b-ace157054292
* Content: [Get started with App Studio for Microsoft Teams - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/app-studio-overview)
* Content Source: [msteams-platform/concepts/build-and-test/app-studio-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/build-and-test/app-studio-overview.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by asnow003** [comment]
@npherson are you using App Studio in GCC... I would like to know how this is working because we do not officially support App Studio and the services that back it in GCC.
