### ISSUE TITLE
do you test anything?  None of the Figma links will load correctly. 

### ISSUE THREAD

**Issue by smchargue** [MicrosoftDocs/msteams-docs#3639]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e13fe9ac-9ae6-4f86-e800-e667ea49cd73
* Version Independent ID: d1034128-eda7-8d57-3d1d-dd862043db17
* Content: [Design your app - Understand the design system - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/design/design-teams-app-fundamentals)
* Content Source: [msteams-platform/concepts/design/design-teams-app-fundamentals.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/design/design-teams-app-fundamentals.md)
* Product: **msteams**
* GitHub Login: @heath-hamilton
* Microsoft Alias: **lajanuar**

**Comment by Chetana-MSFT** [comment]
Hi @smchargue Thanks for reaching out us. Could you please share more details what exactly you are trying.

**Comment by smchargue** [comment]
Sorry, having a bad day and am frustrated trying to find out the most basic information about what color schemes to use to make my custom ms teams app look like a teams app.   All the links on that page to "figma" open a page that locked up the browser - edge and chrome.

**Comment by Chetana-MSFT** [comment]
@smchargue Could you please go through this [documentation](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/design/design-teams-app-ui-templates?tabs=desktop#microsoft-teams-ui-library) it will help you.

**Comment by smchargue** [comment]
> @smchargue Could you please go through this [documentation](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/design/design-teams-app-ui-templates?tabs=desktop#microsoft-teams-ui-library) it will help you.

Thanks, that is very good information - if you are building a Teams Application in react.  I am not.  I'm trying to build a html/javascript/kendo jQuery UI application that runs in Teams and looks like it belongs in Teams.  If there is a way to incorporate Fluent UI in a non-react application, i haven't found it.  

But thanks again for the link.

**Comment by v-chetsh** [comment]
@smchargue - You can use Fluent UI CDN links for developing HTML pages.
Reference docs:
https://docs.microsoft.com/en-us/fluent-ui/web-components/getting-started/quick-start
https://developer.microsoft.com/en-us/fluentui#/styles/web
https://developer.microsoft.com/en-us/fluentui#/controls/webcomponents

Also, could you please elaborate what exactly we need to update in documentation for Figma ?

**Comment by Prasad-MSFT** [comment]
@smchargue  Could you please elaborate what exactly we need to update in documentation for Figma ?

**Comment by v-chetsh** [comment]
@smchargue - Could you please elaborate what exactly we need to update in documentation for Figma ?
I think for Figma, we need a account to create the UI designs.
