### ISSUE TITLE
Something went wrong, please try again later

### ISSUE THREAD

**Issue by bezua** [MicrosoftDocs/msteams-docs#364]
When installing any dummy Teams App from zip file, I see:
"Something went wrong, please try again later"

Please extend the app and show more detailed error message.
With this humble message I don't even know where start to dig.
Nothing in log messages as well.
Cheers,

---
#### Szczegóły dokumentu

⚠ *Nie edytuj tej sekcji. Jest ona wymagana dla docs.microsoft.com ➟ Dołączanie problemu w usłudze GitHub.*

* ID: 80613718-e11b-2d15-853a-9fe3aa9c01d1
* Version Independent ID: ec71ec7c-d4ef-e9fe-c9f1-60b1242b5420
* Content: [Package your app - Teams](https://docs.microsoft.com/pl-pl/microsoftteams/platform/concepts/apps/apps-package)
* Content Source: [msteams-platform/concepts/apps/apps-package.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/apps/apps-package.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Wajeed-msft** [comment]
Could you please share your manifest file? Also, are you using [App Studio](https://docs.microsoft.com/en-us/microsoftteams/platform/get-started/get-started-app-studio) to create and install your app manifest?

**Comment by bezua** [comment]
Hi, thanks for the quick reply.



Finally, it figured out, 'installing external application' was disabled on
the administration level in my organization.

I confirmed it by creating new development tenant and it worked! So, my app
was ok.



There is a notice in the documentation saying this option shall be enabled,
however, I think that error message could be more specific, so end user
knows where to go. Actually I didn’t know if this is my app or adm settings.

Regards,

Jarek

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Wolny
od wirusów. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Wajeed-msft** [comment]
We are working on improving this experience.

**Comment by gurayyarar** [comment]
> Hi, thanks for the quick reply. Finally, it figured out, 'installing external application' was disabled on the administration level in my organization. I confirmed it by creating new development tenant and it worked! So, my app was ok. There is a notice in the documentation saying this option shall be enabled, however, I think that error message could be more specific, so end user knows where to go. Actually I didn’t know if this is my app or adm settings. Regards, Jarek <https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail> Wolny od wirusów. [www.avast.com](http://www.avast.com) <https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail> <#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Hi,
Where we can set this "'installing external application'" setting on?

**Comment by Wajeed-msft** [comment]
@gurayyarar - Here is how you can [enable sideloading for external apps](https://docs.microsoft.com/en-us/MicrosoftTeams/enable-features-office-365#apps).

**Comment by gurayyarar** [comment]
@weijuans-msft thank you so much

**Comment by Perzan** [comment]
@Wajeed-msft Despite the page you linked, I still cannot find any option that allows me to enable"installing external application" anywhere. The page does not seem to address installing external apps. Is there a step-by-step solution how to enable this?

My colleague with admin rights has already tried to upload my teams bot, but all he gets is "Something went wrong, please try again later ". I'm 99% sure my manifest is correct.
