### ISSUE TITLE
not able to make an sso authentification in tabs

### ISSUE THREAD

**Issue by Githamza** [MicrosoftDocs/msteams-docs#3644]
I would run in-meeting app sample , that requires to authenticate using sso in a tab.

When I authenticate user I get `ssoAcquireTokenRenewFailed`

 I have make the step listed in the readme file:

#### Registering your app through the Azure Active Directory portal in-depth:

1. Go to Azure Portal -> Azure Active Directory -> App Registrations.
2. Select same AAD application created in previous step (Bot registration).
3. Under **Manage**, select **Expose an API**. 
4. Select the **Set** link to generate the Application ID URI in the form of `api://{Application ID}`. Insert your fully qualified domain name (with a forward slash "/" appended to the end) between the double forward slashes and the GUID. The entire ID should have the form of: `api://fully-qualified-domain-name.com/{Application ID}` ²
    * ex: `api://subdomain.example.com/00000000-0000-0000-0000-000000000000`. Then click **save**.
    
    The fully qualified domain name is the human readable domain name from which your app is served. If you are using a tunneling service such as ngrok, you will need to update this value whenever your ngrok subdomain changes.
    * ex: `api://f631****.ngrok.io/00000000-0000-0000-0000-000000000000`.
 
5. Select the **Add a scope** button. In the panel that opens, enter `access_as_user` as the **Scope name**.
6. Set **Who can consent?** to `Admins and users`
7. Fill in the fields for configuring the admin and user consent prompts with values that are appropriate for the `access_as_user` scope:
    * **Admin consent display name:** Teams can access the user’s profile.
    * **Admin consent description**: Allows Teams to call the app’s web APIs as the current user.
    * **User consent display name**: Teams can access the user profile and make requests on the user's behalf.
    * **User consent description:** Enable Teams to call this app’s APIs with the same rights as the user.
8. Ensure that **State** is set to **Enabled**
9. Select the **Add scope** button to save 
    * The domain part of the **Scope name** displayed just below the text field should automatically match the **Application ID** URI set in the previous step, with `/access_as_user` appended to the end:
        * `api://subdomain.example.com/00000000-0000-0000-0000-000000000000/access_as_user`
10. In the **Authorized client applications** section, identify the applications that you want to authorize for your app’s web application. Select *Add a client application*. Enter either one from the following client IDs based on your needs:
    * `1fec8e78-bce4-4aaf-ab1b-5451cc387264` (Teams mobile/desktop application)
    * `5e3ce6c0-2b1f-4285-8d4b-75ee78787346` (Teams web application) <br>
Then select the authorized scope you created in the previous step, click **Add Application**.
11. Navigate to **API Permissions**. Select *Add a permission* > *Microsoft Graph* > *Delegated permissions*, then add the following permissions:
    * User.Read (enabled by default)
    * email
    * offline_access
    * OpenId
    * profile

12. Navigate to **Authentication**

    If an app hasn't been granted IT admin consent, users will have to provide consent the first time they use an app.

    Set a redirect URI:
    * Select **Add a platform**.
    * Select **web**.
    * Enter the **redirect URI** for your app. This will be the page where a successful implicit grant flow will redirect the user. This will be same fully qualified domain name that you entered in step 5 followed by the API route where a authentication response should be sent. If you are following any of the Teams samples, this will be: `https://subdomain.example.com/auth-end`

    Next, enable implicit grant by checking the following boxes:  
    ✔ ID Token  
    ✔ Access Token  
    
Congratulations! You have completed the app registration prerequisites to proceed with your tab SSO app.     

> **NOTE:**
>
> * ¹ If your Azure AD app is registered in the _same_ tenant where you're making an authentication request in Teams, the user won't be asked to consent and will be granted an access token right away. Users only need to consent to these permissions if the Azure AD app is registered in a different tenant.
> * ² If you get an error stating that the domain is already owned and you are the owner, follow the procedure at [Quickstart: Add a custom domain name to Azure Active Directory](https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/add-custom-domain) to register the domain, and then repeat step 5, above. (This error can also occur if you aren't signed in with Admin credentials in the Office 365 tenancy).
> * If you are not receiving the UPN (User Principal Name) in the returned access token, you can add it as an [optional claim](https://docs.microsoft.com/azure/active-directory/develop/active-directory-optional-claims) in Azure AD.

Any idea why I get this error ?

**Comment by Sridevi-MSFT** [comment]
@Githamza -  Thank you for the insights. Will repro and will inform you as soon as possible.

**Comment by Githamza** [comment]
Thanks , for information I'm using ms authenticator app as login security

**Comment by Githamza** [comment]
> @Githamza -  Thank you for the insights. Will repro and will inform you as soon as possible.

Any updates ?

**Comment by Sridevi-MSFT** [comment]
The issue seems to be with the azure configuration-

1. webApplicationInfo in the manifest.json
   "webApplicationInfo": { "id": "00000000-0000-0000-0000-000000000000", "resource": 
   "api://subdomain.example.com/00000000-0000-0000-0000-000000000000" }
2. Under Expose API > Application ID URI
    api://subdomain.example.com/00000000-0000-0000-0000-000000000000

**Comment by Githamza** [comment]
What is wrong with the azure configuration , what should I change ?

**Comment by Wajeed-msft** [comment]
@Githamza - Apologies for the delays, could you please share the repro steps along with the manifest? Also, are you getting any errors in console logs?

**Comment by Githamza** [comment]
I'm trying to run the in-meeting-app sample https://github.com/OfficeDev/TeamsFx-Samples/tree/main/in-meeting-app

here's my manifest 
```
{
  "$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.9/MicrosoftTeams.schema.json",
  "manifestVersion": "1.9",
  "version": "1.0.0",
  "id": "d8b3d3b5-4axxxxx",
  "packageName": "com.microsoft.teams.extension",
  "developer": {
    "name": "Teams App, Inc.",
    "websiteUrl": "https://8edcedxxxx.ngrok.io",
    "privacyUrl": "https://8edcedxxxx.ngrok.io/privacy",
    "termsOfUseUrl": "https://8edcedxxxxx.ngrok.io/termsofuse"
  },
  "icons": {
    "color": "color.png",
    "outline": "outline.png"
  },
  "name": {
    "short": "Meeting App",
    "full": "Meeting App"
  },
  "description": {
    "short": "Short description for Meeting App.",
    "full": "Full description of Meeting App."
  },
  "accentColor": "#FFFFFF",
  "configurableTabs": [
    {
      "configurationUrl": "https://8edced8xxxx.ngrok.io/config",
      "canUpdateConfiguration": false,
      "scopes": ["groupchat"],
      "context": ["meetingChatTab", "meetingDetailsTab", "meetingSidePanel"]
    }
  ],
  "bots": [
    {
      "botId": "d8b3d3b5-4a8e-4b91-b27c-xxxxx,
      "scopes": ["personal", "groupchat", "team"],
      "supportsFiles": false,
      "isNotificationOnly": false
    }
  ],
  "permissions": ["identity", "messageTeamMembers"],
  "validDomains": ["8edced8dbxxxxx.ngrok.io"],
  "webApplicationInfo": {
    "id": "d8b3d3b5xxxxxxxxxxxx",
    "resource": "api://8edced8db412.ngrok.io/d8b3d3b5-4a8e-4b9xxxx"
  }
}

```

I have hided some values .

I get only this information in logs :  `ssoAcquireTokenRenewFailed`

**Comment by Wajeed-msft** [comment]
Thanks for sharing more details on this. I'll try to repro this at my end. Meanwhile, could you please confirm if you have added [Authorized client applications](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-aad-sso#1-create-your-aad-application) (Step 12 in Create your AAD application)?

**Comment by Githamza** [comment]
Yes I added desktop app id.

**Comment by v-chetsh** [comment]
@Githamza - We are not able to repro this issue and it's working fine.

**Comment by v-chetsh** [comment]
@Githamza - Could you please confirm if your issue has resolved or still looking for any help?
