### ISSUE TITLE
Teams connector sample is broken

### ISSUE THREAD

**Issue by SnirShechter** [MicrosoftDocs/msteams-docs#3645]
I'm unsuccessfully trying to create our own connector for Teams. The configuration save button (which I really don't even need since we're in the 21st century and nobody needs to explicitly save anything) just throws an error:
`Unable to save "<APP_NAME>" connector configuration. Please try again.`

I took the simplest sample from [here](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-creating), uploaded it to Netlify and even that doesn't work (just upload the manifest below and check it yourselves).

my manifest:
```
{
  "$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.3/MicrosoftTeams.schema.json",
  "manifestVersion": "1.3",
  "id": "782543cd-f172-4e70-8289-903f688d3f80",
  "version": "1.0.4",
  "packageName": "com.Aporia",
  "developer": {
    "name": "Aporia (netlify)",
    "websiteUrl": "https://aporia.com",
    "privacyUrl": "https://www.aporia.com/privacy-policy/",
    "termsOfUseUrl": "https://www.aporia.com/terms-of-use/"
  },
  "description": {
    "full": "Aporia's Teams app allows you to display alerts and notifications from your Aporia account easily.",
    "short": "Alerts and notifications from Aporia"
  },
  "icons": {
    "outline": "outline.png",
    "color": "transparent.png"
  },
  "connectors": [
    {
      "connectorId": "782543cd-f172-4e70-8289-903f688d3f80",
      "scopes": ["team"],
      "configurationUrl": "https://vigorous-hamilton-aa2dfa.netlify.app/"
    }
  ],
  "name": {
    "full": "Aporia (netlify)",
    "short": "Aporia (netlify)"
  },
  "accentColor": "#FFFFFF",
  "validDomains": ["vigorous-hamilton-aa2dfa.netlify.app","netlify.app"]
}
```

P.S Teams has around 20 errors in the devtools when using it normally. What's going on with this product?

**Comment by Chetana-MSFT** [comment]
Hi @SnirShechter Thanks for reaching out us, will repro at our end and will update you soon.

**Comment by SnirShechter** [comment]
I just deleted the connector and created another myself.

Problem solved.
