### ISSUE TITLE
Cannot Connect to IIS Express (VS2019) [Teams Toolkit [Preview] Version 0.1.48.43394]

### ISSUE THREAD

**Issue by andydford** [MicrosoftDocs/msteams-docs#3654]
Following the instructions provided for the Teams Toolkit (preview), I created an application using the "Teams Toolkit [Preview] Version 0.1.48.43394". I then followed the guidance and ran the Project->TeamsFx->Configure for SSO... All goes fine, new registration in Azure etc however, running the app in debug mode (IISExpress) I get the error dialog with the message "Unable to connect to web server 'IIS Express'

Using VSCode is fine and works as expected.

Is there something else special I need to do in VS2019 even though I have followed the guidance, and recent YouTube https://youtu.be/Hz8i2HPSPts demo.

Thanks in advance.

**Comment by Jagadeesh-MSFT** [comment]
Hi @andydford, Thanks for reaching us, we are checking with our internal team. Will get back to you.

**Comment by andydford** [comment]
Forgot to add error info

Seems to be a permissions error but I am not an IIS Express expert!

Starting IIS Express ...
Failed to register URL "http://localhost:50086/" for site "TeamsApp01" application "/". Error description: Access is denied. (0x80070005)
Successfully registered URL "https://localhost:44357/" for site "TeamsApp01" application "/"
Registration completed for site "TeamsApp01"

![Screenshot 2021-06-18 185353](https://user-images.githubusercontent.com/79726431/122599668-a3e70500-d066-11eb-9560-c20f71396579.png)

**Comment by Jagadeesh-MSFT** [comment]
Hi @andydford, are you still facing the issue, could you please check with your it team regarding permission issues.

**Comment by andydford** [comment]
Thanks for getting back. I still have the issue but it is only on one of my machines in Visual Studio 2019. This makes me believe that it has nothing to do with the package but rather some config on that particular macine. I would close this as it is not related directly to the preview package.

Thanks for your help.

**Comment by Pothan-MSFT** [comment]
Hi @andydford, we are unable to repro your issue at our end as it works completely fine on our machine.

**Comment by andydford** [comment]
Thanks for that. It is an issue with my machine as it works fine on others. Okay to close.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
