### ISSUE TITLE
Recorded meeting shows NaNs instead of a valid duration

### ISSUE THREAD

**Issue by attauf** [MicrosoftDocs/msteams-docs#3658]
The meetings that are getting recorded, shows up the duration as "NaNs" instead of a valid duration.

Microsoft Teams Version 1.4.00.11161 (64-bit)
OS: Win10

![image](https://user-images.githubusercontent.com/59413505/122380005-0c5db580-cf85-11eb-9530-34508bba0a58.png)

**Comment by Jagadeesh-MSFT** [comment]
Hi @attauf, we are unable to repro your issue from our side. Could you please go through the below screenshots for the same.
![image](https://user-images.githubusercontent.com/73812940/122550143-f61d2b80-d050-11eb-807a-6052a2548752.png)
![image](https://user-images.githubusercontent.com/73812940/122550197-033a1a80-d051-11eb-90d4-a19ade1704b1.png)
