### ISSUE TITLE
Errors and issues on the page

### ISSUE THREAD

**Issue by SimonJHudson** [MicrosoftDocs/msteams-docs#3659]
The page refers repeatedly to *'Preview' *the scene. The feature to do this is actually labelled 'View in Teams'.
![image](https://user-images.githubusercontent.com/42973791/122381009-5c765100-cf60-11eb-926e-3de4480d13bd.png)

The page refers to the Together Mode selection menu in the top left. In all my tenants (3 of them), there is no top left selector, it is in the ellipsis menu (I suspect you are referring to a UI yet to be rolled out).

In every case, across all tenants, when I use *"View  in Teams"* I encounter a permissions error:
*"Permissions needed. Ask your IT admin to add Getting started sample to this team/chat/meeting."*
The *Add* button is greyed out and it is not possible to preview the created scene.
 I can confirm that 3rd party and custom apps are enabled by policy.

![image](https://user-images.githubusercontent.com/42973791/122380946-49638100-cf60-11eb-8a59-b3589ed98f70.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c7eb0c2-edd6-b748-f99b-11d26d0e8f47
* Version Independent ID: 278c15ae-7d16-091a-8320-90b3e15aacfc
* Content: [Custom Together Mode Scenes - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/teams-together-mode)
* Content Source: [msteams-platform/apps-in-teams-meetings/teams-together-mode.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/apps-in-teams-meetings/teams-together-mode.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Chetana-MSFT** [comment]
@SimonJHudson  Thanks for reaching out us, we are checking internally.

**Comment by Chetana-MSFT** [comment]
@SimonJHudson To add some application to your account, you need to have permissions from IT team. Could you please check this [documentation](https://docs.microsoft.com/en-us/microsoftteams/app-permissions-admin-center) for more details.

**Comment by SimonJHudson** [comment]
As stated in my original report, I have confirmed that App Permissions are globally permissive. For clarity, I hereby confirm, again, that third party apps are allowed in settings, see this screenshot.
![image](https://user-images.githubusercontent.com/42973791/122960356-3c3cfc80-d37b-11eb-960a-11705f3bf4bd.png)

The documentation link is unhelpful as it simply states what I had already checked and is not specific to Together Mode scene development. Furthermore, you have not specified _which_ app needs enabling. I can find no indication that the Together Mode Scenes development is a discrete app (at least not until it is published, which can't be done until after it is previewed); as such it is not listed in any of the hundreds of Teams apps (I checked, carefully, before sending the feedback and again just now).

Since I am the IT Team I had done all the obvious things before reaching out.

I would now be very grateful if someone would review the issues and advise, based on the specific issues with previewing custom Together Mode Scenes. I look forward to a reply.

**Comment by SimonJHudson** [comment]
Hello? Anyone? Any help? It's been two weeks and I have had zero response of value so far. @Wajeed-msft  @Nikitha-MSFT

**Comment by Wajeed-msft** [comment]
@SimonJHudson - Apologies for delays in responses. I checked your scenario and seems like custom app uploading is disabled for the tenant. 

Here is how to [Enable custom Teams apps and turn on custom app uploading](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/prepare-your-o365-tenant#enable-custom-teams-apps-and-turn-on-custom-app-uploading).

![image](https://user-images.githubusercontent.com/31851992/125201246-d82b9b00-e28b-11eb-83d4-707b861be765.png)

Please note that it can take up to 24 hours to propogate the setting changes.

**Comment by SimonJHudson** [comment]
Thanks, that did it.

Please could you ask teh team responsible to update the infomration on the page to make it clear what settings need to be enabled to allow creation of custom scenes?

**Comment by Wajeed-msft** [comment]
@SimonJHudson - Thanks for confirming. Do you feel adding hyperlink to **Upload a custom app** in [Prerequisites](https://docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/teams-together-mode#prerequisites) section would help? I'll share this with documentation team.

**Comment by SimonJHudson** [comment]
Yes, definitely, along with all the other settings that might constrain use of the feature, and clarity on other settings that need not be altered (I have tried a lot!)

Simon Hudson
07735052905

Novia Works Ltd
[Novia logo]
Noviaconsulting.co.uk<https://noviaconsulting.co.uk/>
[See the source image]<https://www.linkedin.com/in/simonjhudson/> [Twitter icon] <https://twitter.com/simonjhudson>
