### ISSUE TITLE
[iOS] Adaptive cards not rendering in Teams iOS app but show up on the desktop client.

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#3672]
Copied bug from: https://github.com/microsoft/AdaptiveCards/issues/6013 

**Details from original post:**
# Target Platform

Please list the platform(s) that your application is targeting and remove platforms you are not targeting:
- iOS

# Target Application

Microsoft Teams for iOS

# Problem Description

Microsoft Teams app on iOS is not rendering adaptive cards when sent via an inbound webhook.

# Screenshot
Desktop:
![image](https://user-images.githubusercontent.com/51809650/122465058-7158e180-cf6c-11eb-9256-ec3a5328e04d.png)
Phone:
![bug](https://user-images.githubusercontent.com/51809650/122465593-2390a900-cf6d-11eb-8303-66e845235f21.jpg)

# Card JSON

Tried it with some of the templates as well available online and none of them rendered at all.

# Sample Code

N/A

# Version of SDK

N/A
---
#### Document Details

⚠ *Do not edit this section.It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Cards reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **surbhigupta12**

**Comment by Chetana-MSFT** [comment]
Hi @ved-dave Thanks for reaching out us, will repro at our end and will get back you soon.

**Comment by Chetana-MSFT** [comment]
@ved-dave Could you please share your JSON file. So that we can repro and get back to you.

**Comment by SergeyGrayman** [comment]
Same Issue. All of the old cards not rendering too

**Comment by Wajeed-msft** [comment]
@SergeyGrayman , @ved-dave   - Are you [sending Adaptive card with incoming webhook](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-using?tabs=cURL#send-adaptive-cards-using-an-incoming-webhook)? Could you please share the card JSON to try along with the repro steps?

**Comment by SergeyGrayman** [comment]
No, we are using adaptive card with bot framework. It all works correctly in desktop app and even android app. but still not rendering in ios app.

Json and card preview:
![1](https://user-images.githubusercontent.com/9824156/124902252-6e8d6180-dfeb-11eb-9863-3cb2b072d58a.png)
**Card data:**
` {
    "Title":"Ежегодный отпуск",
    "DaysLeft": 10,
    "VacationTitle": "Ваши запланированные отпуска:",
    "UrvLink":"",
    "Vacations": [
        {
            "Id": "1",
            "StartDate": "01/01/2021",
            "EndDate": "10/01/2021",
            "Status": "Утвержден"
        },
        {
            "Id": "2",
            "StartDate": "01/01/2021",
            "EndDate": "10/01/2021",
            "Status": "Утвержден"
        }
    ]
}`

Card Json:

`{
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "type": "AdaptiveCard",
    "version": "1.2",
    "body": [
        {
            "type": "Input.Text",
            "id": "Id",
            "value": "${Id}",
            "isVisible": false
        },
        {
            "type": "TextBlock",
            "wrap": true,
            "text": "${Title}",
            "weight": "Bolder",
            "size": "Large"
        },
        {
            "type": "TextBlock",
            "text": "Ваш остаток ежегодного отпуска составляет **${DaysLeft} дней**",
            "wrap": true
        },
        {
            "type": "Container",
            "items": [
                {
                    "type": "TextBlock",
                    "text": "${VacationTitle}",
                    "wrap": true
                },
                {
                    "type": "ColumnSet",
                    "columns": [
                        {
                            "type": "Column",
                            "width": "30px",
                            "items": [
                                {
                                    "type": "TextBlock",
                                    "wrap": true,
                                    "text": "№",
                                    "isSubtle": true,
                                    "weight": "Bolder"
                                }
                            ]
                        },
                        {
                            "type": "Column",
                            "width": "100px",
                            "items": [
                                {
                                    "type": "TextBlock",
                                    "text": "Дата начала",
                                    "wrap": true,
                                    "color": "Dark",
                                    "weight": "Bolder",
                                    "isSubtle": true
                                }
                            ],
                            "horizontalAlignment": "Center"
                        },
                        {
                            "type": "Column",
                            "width": "100px",
                            "items": [
                                {
                                    "type": "TextBlock",
                                    "text": "Дата выхода",
                                    "wrap": true,
                                    "color": "Dark",
                                    "isSubtle": true,
                                    "weight": "Bolder"
                                }
                            ]
                        },
                        {
                            "type": "Column",
                            "width": "stretch",
                            "items": [
                                {
                                    "type": "TextBlock",
                                    "text": "Статус",
                                    "wrap": true,
                                    "color": "Dark",
                                    "isSubtle": true,
                                    "weight": "Bolder"
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            "type": "Container",
            "items": [
                {
                    "type": "ColumnSet",
                    "columns": [
                        {
                            "type": "Column",
                            "width": "30px",
                            "items": [
                                {
                                    "type": "TextBlock",
                                    "text": "${Id}"
                                }
                            ],
                            "horizontalAlignment": "Center"
                        },
                        {
                            "type": "Column",
                            "width": "100px",
                            "items": [
                                {
                                    "type": "TextBlock",
                                    "text": "${StartDate}",
                                    "wrap": true
                                }
                            ]
                        },
                        {
                            "type": "Column",
                            "width": "100px",
                            "items": [
                                {
                                    "type": "TextBlock",
                                    "text": "${EndDate}",
                                    "wrap": true
                                }
                            ]
                        },
                        {
                            "type": "Column",
                            "width": "stretch",
                            "items": [
                                {
                                    "type": "TextBlock",
                                    "text": "${Status}",
                                    "wrap": true
                                }
                            ]
                        }
                    ],
                    "style": "default"
                }
            ],
            "$data": "${Vacations}"
        },
        {
            "type": "TextBlock",
            "text": "Вы можете воспользоваться сервисом перейдя по [ссылке](${UrvLink}) или я могу помочь вам с этим. \n\nОтправить заявку?",
            "wrap": true
        }
    ],
    "actions": [
        {
            "type": "Action.Submit",
            "title": "Заявка",
            "data": {
                "command": "claim"
            }
        },
        {
            "type": "Action.Submit",
            "title": "Отмена",
            "data": {
                "command": "cancel"
            }
        }
    ]
}`

**Comment by Wajeed-msft** [comment]
@SergeyGrayman - Thanks for sharing the JSON with me, I'll try to repro this at my end let you know.

**Comment by SergeyGrayman** [comment]
@Wajeed-msft any suggestions? We are stuck with this and cant launch bot without ios app in our company

**Comment by SergeyGrayman** [comment]
@Wajeed-msft @Chetana-MSFT any news? Still not fixed.

**Comment by v-chetsh** [comment]
@SergeyGrayman - We are looking into it

**Comment by v-chetsh** [comment]
@SergeyGrayman - Looks like **"isVisible"** property is not supported in iOS device.
Could you please remove it from below code and test it once:
{
		"type": "Input.Text",
		"id": "Id",
		"value": "${id}",
		**"isVisible": false**
	}

There is already a bug raised for it:
https://github.com/microsoft/AdaptiveCards/issues/4335

**Comment by SergeyGrayman** [comment]
@v-chetsh yes, it helps, but now we have another problem with that. we need this property in card, and we need to hide this ID from user. It worked correctly couple of moths ago. will it be fixed in ios app?

**Comment by v-chetsh** [comment]
@SergeyGrayman - I think you can bind ID value with the action button "data" part and it will not be visible to user.
May be this issue will get resolve in future.

**Comment by jameskleinschnitz** [comment]
@v-chetsh  when you say;
**"isVisible" property is not supported in iOS devices**

what does that mean?
it will never be supported on iOS?
or is it just currently not working on iOS?
I agree with @SergeyGrayman it has worked in the past.

**Comment by v-chetsh** [comment]
@jameskleinschnitz - "isVisible" property was not supported for specific version of Adaptive Card SDK version like 1.2.
There was a bug already raised & it got fixed.
So it is now supporting in latest Adaptive Card SDK version 1.3.

@SergeyGrayman - Could you please try it once with latest version.

**Comment by jameskleinschnitz** [comment]
@vc-chetsh this is good news!
When can we get the tools updated to support 1.3 or if not 1.4 of adaptive cards (I think that is the current supported version)

like the https://adaptivecards.io/designer/ if you select 1.3 or 1.4 you get a warning?

_[Warning] The selected Target Version (1.3) is greater than the version supported by Microsoft Teams - Dark (1.2)_ 

If you try to use app studio to debug cards with 1.3+ you get:

_We're sorry, this card couldn't be displayed_

when you send the card to yourself

Thanks

**Comment by v-chetsh** [comment]
@jameskleinschnitz -  Currently SDK & other tools are compatible with 1.2 version but surely new tools will release soon to support 1.3/1.4 versions of adaptive cards.

Thanks!!

**Comment by jameskleinschnitz** [comment]
@v-chetsh just fyi switched to AC 1.3/1.4 and the first isVisible in this issue: https://github.com/MicrosoftDocs/msteams-docs/issues/3252 is still breaking our cards. We have rewritten the cards to work around this but wanted to FYI.

**Comment by v-chetsh** [comment]
@JordyGit - Could you please confirm if your issue has resolved or still looking for any help?

**Comment by JordyGit** [comment]
@v-chetsh yes the issue got resolved since my last reply automatically and also took affect on old messages that already were sent now being displayed and working correctly.

**Comment by v-chetsh** [comment]
@JordyGit - Thanks a lot for confirmation.

**Comment by v-chetsh** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.
