### ISSUE TITLE
AdaptiveCard with “mailto” Action.OpenUrl is not working for buttons with Image set as well

### ISSUE THREAD

**Issue by RajdeepRay0411** [MicrosoftDocs/msteams-docs#3677]
On Microsoft Teams, we are using a customized who bot scenario where we are sending data from Graph API in the adaptive card about the person whom the user is looking for in our bot. The adaptive card contains two icons one chat icon and one mail icon. The chat icon will open a particular person's chat in teams and the mail icon will redirect to outlook with the particular user's email id in the To column. At present on clicking the mail icon is again redirecting back in teams in Web and is not working in the desktop client. Please help me how to redirect it properly to Outlook when the mail icon is clicked.

Please find the screenshots below:
![image](https://user-images.githubusercontent.com/51920866/122595211-c0466a00-d085-11eb-810c-e0dc341e11fc.png)

**Comment by Mamatha-MSFT** [comment]
Hi @RajdeepRay0411 - Currently `openSafeUrlMT ` in adaptive card does not allow `mailto `urls. we already have a backlog feature request on this and engineering team is looking into it

**Comment by YPillay** [comment]
Hi,  On a related note.
Are all URI activations not allowed for openUrl or just mailto ?

Is there a workaround available ?

**Comment by Mamatha-MSFT** [comment]
@YPillay - Currently Adaptive card `openUrl `supports https,http,ftps and ftp Urls. There is no workaround for this.

**Comment by Mamatha-MSFT** [comment]
@YPillay  - Concerned team is working on this feature but we do not have a firm timeline to share with you. Hence, we are closing this question for now.
