### ISSUE TITLE
Microsoft Teams Takes about as much Memory as Visual Studio while Debugging

### ISSUE THREAD

**Issue by pdemro** [MicrosoftDocs/msteams-docs#368]
There are over 100 consolidated votes on uservoice to address this issue

https://microsoftteams.uservoice.com/forums/555103-public/suggestions/33643924-reduce-memory-usage

https://microsoftteams.uservoice.com/forums/555103-public/suggestions/33847345-desktop-app-should-use-much-less-system-memory

https://microsoftteams.uservoice.com/forums/555103-public/suggestions/34789129-high-cpu-time-memory-and-disk-reads-writes

https://microsoftteams.uservoice.com/forums/555103-public/suggestions/33626677-your-desktop-version-is-too-slow-and-consume-a-lot

https://microsoftteams.uservoice.com/forums/555103-public/suggestions/34941424-reduce-the-memory-footprint-work-on-app-crashes

https://microsoftteams.uservoice.com/forums/555103-public/suggestions/33038843-please-do-some-memory-manaement

https://microsoftteams.uservoice.com/forums/555103-public/suggestions/34913479-memory-leaks 

![image](https://user-images.githubusercontent.com/5431128/49883469-cd24db80-fe00-11e8-962b-0cce3afd7228.png)

**Comment by billbliss** [comment]
We continue to work on this. We are not ignoring it, and we've made some progress, but it's a lot of little things and some big things that tension ahead of us.

**Comment by pdemro** [comment]
@billbliss Thank you very much for your input!  Glad to hear it is at least on the radar.

**Comment by pdemro** [comment]
"You just got the latest updates for Teams, enjoy!"

![image](https://user-images.githubusercontent.com/5431128/55962920-ccca0f00-5c3f-11e9-8b36-f4f1d68b1b4c.png)
