### ISSUE TITLE
Instructions don't seem to work

### ISSUE THREAD

**Issue by icyfire0573** [MicrosoftDocs/msteams-docs#3682]
![image](https://user-images.githubusercontent.com/40814526/122626348-101e3480-d078-11eb-8a79-8dba4307930a.png)
Above is my view when I get to step 3 here: https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-outgoing-webhook#create-an-outgoing-webhook

it says look in the lower right, as you can see, my teams has nothing in the lower right;
I searched for outgoing webhook and that is showing the result in the image.  

has the process changed since this was last updated?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb9c5bd5-1ac6-dcc8-4ed6-d6aad2432776
* Version Independent ID: 43e90995-bba4-86b6-1f1c-ab749e546a4b
* Content: [Add custom bots to Microsoft Teams with outgoing webhooks - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-outgoing-webhook)
* Content Source: [msteams-platform/webhooks-and-connectors/how-to/add-outgoing-webhook.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/webhooks-and-connectors/how-to/add-outgoing-webhook.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Sridevi-MSFT** [comment]
@icyfire0573 - In documentation Step1 it is mentioned clearly that you need to select appropriate team. But from your image, seems like you're trying it in Apps. So, for your better understanding I have attached an image by highlighting the steps. 


![Capture](https://user-images.githubusercontent.com/80752198/122733542-e7c25000-d29a-11eb-814c-e575853e8406.PNG)

**Comment by icyfire0573** [comment]
Yep; that appears to resolve it for me. It looks like my issue was related to the initial "manage team" part. I guess the first team I created by default was pinned, so when I clicked the "..." on it, it was not the team itself but the team/channel general which didn't have the "manage teams" option, and therefore not the outgoing webhook.
