### ISSUE TITLE
How to customize the bot input field?

### ISSUE THREAD

**Issue by michaelwechner** [MicrosoftDocs/msteams-docs#3691]
When I have the "Wikipedia Search" bot/app installed and when I enter "@wikipedia" and hit return/enter, then the input field is being modified, whereas at the beginning the wikipedia logo occurs and the text "Wikipedia Search > Browse Wikipedia" and is following by an input field with a placeholder "Enter a search term".

It tried to find some documentation in order to do this for my own bot/app, but did not find any documentation. How can this be done?

Thanks for your help in advance!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87d66f12-3a20-8d6a-ed4c-90bc26f90591
* Version Independent ID: 3725c141-86f1-b815-6568-16758d948fac
* Content: [Designing your bot - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/design/bots?tabs=desktop)
* Content Source: [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/bots/design/bots.md)
* Product: **msteams**
* GitHub Login: @heath-hamilton
* Microsoft Alias: **lajanuar**

**Comment by Sridevi-MSFT** [comment]
@michaelwechner - Taking this for internal discussion with team, I will update you with resolution.

**Comment by Sridevi-MSFT** [comment]
@michaelwechner - Could you please share screen recording of your issue so that we can understand more clearly.

**Comment by michaelwechner** [comment]
> @michaelwechner - Could you please share screen recording of your issue so that we can understand more clearly.

please see the following screenshots:

<img width="1097" alt="1 mention wikipedia" src="https://user-images.githubusercontent.com/1078960/123111668-60f9a880-d43d-11eb-9490-7f1c4dd17f31.png">
<img width="1076" alt="2 mention wikipedia after hitting return:enter" src="https://user-images.githubusercontent.com/1078960/123111676-62c36c00-d43d-11eb-8101-88712a02b252.png">
<img width="1033" alt="3 wikipedia results" src="https://user-images.githubusercontent.com/1078960/123111686-648d2f80-d43d-11eb-8719-7bdac0ffcd4d.png">

**Comment by Sridevi-MSFT** [comment]
@michaelwechner - For this you can use Search Messaging Extension. Search commands allow the users to search an external system for information either manually through a search box, or by pasting a link to a monitored domain into the compose message area, and insert the results of the search into a message. Please check this [sample ](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/50.teams-messaging-extensions-search) and [documentation](https://docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/what-are-messaging-extensions#search-commands).

**Comment by michaelwechner** [comment]
Thanks for your feedback and pointers, I will give it a try :-)

**Comment by v-chetsh** [comment]
@michaelwechner - Could you please confirm if your issue has resolved with above suggestion or still looking for any help?

**Comment by michaelwechner** [comment]
I have not been able to try it yet, but I assume that it will work as you explain above

**Comment by v-chetsh** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.
