### ISSUE TITLE
Update Bot Framework SDK link

### ISSUE THREAD

**Issue by corinagum** [MicrosoftDocs/msteams-docs#3695]
Current Bot Framework SDK link directs to the archived repository:
![image](https://user-images.githubusercontent.com/14900841/122829924-77b4c980-d29c-11eb-901d-1fdbf7583e54.png)

Updated text with url should be: 

> Though you can create the web service manually, use [Bot Framework SDK](https://github.com/microsoft/botframework-sdk) to work with the protocol.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7fd5f91c-206f-f03c-d82e-3bf1cc81d13e
* Version Independent ID: d5c2d24a-def4-af2e-7983-c73cf7f22934
* Content: [Messaging extensions - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/what-are-messaging-extensions)
* Content Source: [msteams-platform/messaging-extensions/what-are-messaging-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/messaging-extensions/what-are-messaging-extensions.md)
* Product: **msteams**
* GitHub Login: @clearab
* Microsoft Alias: **anclear**

**Comment by Sridevi-MSFT** [comment]
@corinagum- Thanks for your insights. The documentation team will update the changes.
