### ISSUE TITLE
Mention a user in Input.Text Field of Adaptive Card

### ISSUE THREAD

**Issue by jaindipankar** [MicrosoftDocs/msteams-docs#3701]
I want to mention a user in Input.Text field of Adaptive Card. Whenever we type "@" in Input.Text, I want a list of all the members of channel to appear like in a normal mention.

**Comment by Sridevi-MSFT** [comment]
@jaindipankar - We have a  new feature called "People Picker" using this field we can search for users in dynamic type-ahead format and pick them directly from the Adaptive card. This feature is currently rolling in the internal rings. It will be available for public soon and we don't have any ETA to share.

**Comment by jaindipankar** [comment]
Thank you @Sridevi-MSFT for the updates.
