### ISSUE TITLE
clicking on a meeting in outlook fails to take me to meeting in teams application

### ISSUE THREAD

**Issue by scottstensland** [MicrosoftDocs/msteams-docs#3705]
starting in a browser logged into outlook email when I click on a meeting ( the Join button ) say from my calendar it launches my desktop Teams application however it fails to pull up the matching meeting ... it just launches Teams and takes me to the last location I  was in in Teams 

Because of this bug its very hard if not impossible to pull up in Teams the meeting I am supposed to attend

issue happens across any browser ( most recent chrome or firefox ) 
I am on a Ubuntu 21.04 laptop  
Teams is version 1.4.00.4855

**Comment by scottstensland** [comment]
case closed ... I purged Teams application and did a fresh install and all is well

```
dpkg -l|grep teams
ii  teams                                      1.4.00.4855                                                          amd64        Microsoft Teams for Linux is your chat-centered workspace in Office 365.

```

```

sudo apt-get purge teams  #   uninstall 

```

then I did a fresh install of the linux deb file

**Comment by scottstensland** [comment]
evidently the problem happened in between the time I did the initial teams install of version 1.3.00.30857_amd64 and teams itself did its own internal updates ... below is my Download dir of teams install deb files ( Ubuntu 21.04 )

```
-rw-rw-r--  1 eve  eve    76334658 Dec 18  2020 teams_1.3.00.30857_amd64.deb
-rw-rw-r--  1 eve  eve    83232268 Jun 23 10:01 teams_1.4.00.13653_amd64.deb
```

**Comment by Chetana-MSFT** [comment]
Thanks for reaching out us. We are the developer support team for Microsoft teams focused on helping developers resolve their issues. For issues related to teams product, please reach out to the [product support channels](https://docs.microsoft.com/en-us/microsoftteams/platform/feedback) for Microsoft Teams.
