### ISSUE TITLE
Error: Not able to get response from get chat id endpoint

### ISSUE THREAD

**Issue by mohsinhere** [MicrosoftDocs/msteams-docs#3708]
Hi,

I used to be able to hit the 

GET https://graph.microsoft.com/beta/users/{user-id}/chats?$filter=installedApps/any(a:a/teamsApp/id eq '{teamsAppId}') endpoint until 2 weeks back with Chat.Read.All permissions in application-only context.

But now I'm getting a 412 error with this response message

```
{
  "error": {
    "code": "PreconditionFailed",
    "message": "Requested API is not supported in application-only context",
    "innerError": {
      "date": "2021-06-24T07:09:47",
      "request-id": "c40ca002-96dd-4dba-8016-51643ad1506a",
      "client-request-id": "c40ca002-96dd-4dba-8016-51643ad1506a"
    }
  }
}
```

Did something change? It would be great if I can get a quick response.

Thanks!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 893c2c9e-10e1-dd4e-1eb4-b4e9a46a9f8d
* Version Independent ID: 5f41c382-377c-6c9b-4932-65853675c4ad
* Content: [Use Microsoft Graph to authorize proactive bot installation and messaging in Teams - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/graph-api/proactive-bots-and-messages/graph-proactive-bots-and-messages)
* Content Source: [msteams-platform/graph-api/proactive-bots-and-messages/graph-proactive-bots-and-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/graph-api/proactive-bots-and-messages/graph-proactive-bots-and-messages.md)
* Product: **msteams**
* GitHub Login: @AkJo
* Microsoft Alias: **lajanuar**

**Comment by Mamatha-MSFT** [comment]
Hi @mohsinhere  - We will repro at our end and will get back to you.

**Comment by Mamatha-MSFT** [comment]
Hi @mohsinhere - I am able to get the response from get chat id endpoint. Could you please add below permissions and check 
![image](https://user-images.githubusercontent.com/78795357/123380308-e94a8b80-d5ac-11eb-917a-85be07965a19.png)

**Comment by mohsinhere** [comment]
Hi,

I'm using application permissions... and it has elevated permission: Chat.Read.All. Did you try using delegated or application permissions?

**Comment by mohsinhere** [comment]
![image](https://user-images.githubusercontent.com/14170957/123381104-a18b2a80-d5d3-11eb-8e30-5830ac4c0597.png)

This is the permission set on the app registration. I cant use delegated here as it is an automated process that calls this.

**Comment by Mamatha-MSFT** [comment]
@mohsinhere - With delegated level permissions, getting response from get chat id endpoint. With application level permissions I am able to reproduce your issue. So, Taking this for internal discussion with team and will update you.

**Comment by mohsinhere** [comment]
@Mamatha-MSFT Thanks for looking into this. 

Just an FYI that this endpoint used to work with application permissions until 2 weeks back.

**Comment by Mamatha-MSFT** [comment]
Hi @mohsinhere - I have raised a bug for this issue and concerned engineering team is working on this.

**Comment by mohsinhere** [comment]
@Mamatha-MSFT  Thanks for the update. How long do you think the fix will take? I'm using this in a production bot and I will need to look at workarounds if the fix takes long.

**Comment by Mamatha-MSFT** [comment]
Hi @mohsinhere - Concerned engineering team is  working on fixing this  issue and it is being tracked internally. Currently we don't have any workaround for this, we will update you immediately if it gets resolved but we do not have a firm timeline to share with you.

**Comment by jvigneshcs** [comment]
@Mamatha-MSFT , I tried to get all chats using `Application Permission` with following code

 ```
   private func getAllChats(accessToken: String) {
        let urlSession = URLSession.shared
        let url = URL(string: "https://graph.microsoft.com/v1.0/Chats")!
        var request = URLRequest(
            url: url,
            cachePolicy: .useProtocolCachePolicy,
            timeoutInterval: 30)
        request.addValue("Bearer \(accessToken)",
                         forHTTPHeaderField: "Authorization")
        
        let task = urlSession.dataTask(
            with: request) { data, response, error in
                if let error = error {
                    print("Error: \(error.localizedDescription)")
                } else if let data = data,
                          let string = String(data: data,
                                              encoding: .utf8) {
                    print("Response: \(string)")
                }
            }
        
        task.resume()
    }
```

I got the following error,

> {"error":{"code":"PreconditionFailed","message":"Requested API is not supported in application-only context","innerError":{"date":"2021-10-07T06:47:01","request-id":"a668*********948","client-request-id":"a668**********948"}}}

Is Chat related APIs are not supported with `Application Permission`?

**Comment by v-chetsh** [comment]
@mohsinhere, @jvigneshcs - I am able to run the query in Postman using Application permission with **"Chat.Read.All"** and not getting any error:
I checked in both beta & v1.0 API versions and it's working for me.

PFB attachment:
![image](https://user-images.githubusercontent.com/59052547/137975585-fcf21488-aa8d-483d-8b24-fe59f7e85cb1.png)

Reference docs:
https://docs.microsoft.com/en-us/microsoftteams/platform/graph-api/proactive-bots-and-messages/graph-proactive-bots-and-messages#retrieve-the-conversation-chatid

**Comment by v-chetsh** [comment]
@jvigneshcs - We will check it internally and let you know

**Comment by v-chetsh** [comment]
@jvigneshcs - Could you please check on ACS for calling and chat:
Azure Communication Services 
https://docs.microsoft.com/en-us/azure/communication-services/

**Comment by jvigneshcs** [comment]
@v-chetsh We have already started exploring it and found it supports our requirement.

**Comment by v-chetsh** [comment]
Cool...Thanks a lot for your confirmation.

**Comment by v-chetsh** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.
