### ISSUE TITLE
Unable to connect to Azure when bot is installed via App Studio.

### ISSUE THREAD

**Issue by ryanwwt** [MicrosoftDocs/msteams-docs#371]
I've already installed a number of bot apps in MS Teams using App Studio. The architecture of my bot is MS Teams > Azure Bot Channel > AWS.

I've experienced a few times where I'm able to connect from Azure to AWS (Via Test in Web Chat) but unable to get a response in MS Teams. 

May I know if there is currently an existing problem with installing bots with App Studio?

**Comment by Wajeed-msft** [comment]
There was a recent announcement that [Bot Framework started requiring TLS 1.2 for all Bot Framework bots](https://blog.botframework.com/2018/11/06/announcement-azure-bot-service-enforcing-transport-layer-security-tls-1-2/). 

To detect if your bot is running TLS 1.2, you can use curl against your messaging endpoint or against the root if you have configured an HTML page to be served:

> curl -v GET https://taskmoduletest.azurewebsites.net --tlsv1.2 --tls-max 1.2
> curl -v GET https://taskmoduletest.azurewebsites.net/api/messages --tlsv1.2 --tls-max 1.2

Can you check if that's the case for you?
Could you please also share your bot id and endpoint URL?
