### ISSUE TITLE
App studio Teams

### ISSUE THREAD

**Issue by mourasss** [MicrosoftDocs/msteams-docs#3716]
Hello Everyone,

I ceated an app with appstudio in MS .teams.  i add a tabs and putted my content URL which a Qlik hub. Everythings worked fine until when i clicked on an app in the hub it opens the app in CHrome browser nor in the same canvas of teams app.

Is there an options which let us to force navigaute in teams app canvas ?

Thanks in advance

**Comment by Ravindra-MSFT** [comment]
HI @mourasss, Could you please confirm in which device you are facing this issue.

**Comment by mourasss** [comment]
Hello ,

In Teams Desktop, the web page displayed correcly only when i click on smtgh, it open the link in browser. 
In teams, mobile app i dont face this behaviour.

**Comment by Swapna-MSFT** [comment]
HI @mourasss,Please go through this [documentation](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/design/tabs-mobile), which helps you to how to connect teams in mobile.


![image](https://user-images.githubusercontent.com/85157377/123937702-11265e80-d9b4-11eb-91ba-eef54e7538c8.png)

**Comment by mourasss** [comment]
@Swapna-MSFT  Thank u for documentation. but my problème is in the desktop version not the mobile app.  
when u are in desktop version , u create a tab with the app website. it display the page but when u try to navigate throught the pageit take u to browser to continue the navigation.

**Comment by Wajeed-msft** [comment]
@mourasss - could you please add few screenshots with steps describing what you are trying and what's expected?
