### ISSUE TITLE
Bot not working

### ISSUE THREAD

**Issue by ovsleep** [MicrosoftDocs/msteams-docs#372]
Very helpful hello world example. But you're missing an important step on the bot setup:
Set the "Bot endpoint address" to: https://[yourdomain].ngrok.io/api/messages
Otherwise the bot and the messaging extension wont work. It took me an hour to figure it out.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98cd21c7-e87c-3c5b-7574-998a355f9f08
* Version Independent ID: 5e312707-facc-03fc-af59-90267d0c7b8a
* Content: [Get started with C#/.NET - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/get-started/get-started-dotnet-app-studio)
* Content Source: [msteams-platform/get-started/get-started-dotnet-app-studio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/get-started/get-started-dotnet-app-studio.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by CameronDwyer** [comment]
Came across the same key peice of info missing from the doco. I went to update this page in the Git Repo but found the page in the Master branch is significantly different and doesn't contain anywhere near as much detail? https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/get-started/get-started-dotnet-app-studio.md

**Comment by clearab** [comment]
The documentation has been updated with the missing step. Thanks for letting us know.
