### ISSUE TITLE
Pinned App in Teams shows never ending loading spinning wheel if SharePoint cookies not present

### ISSUE THREAD

**Issue by MikeMorawski** [MicrosoftDocs/msteams-docs#3725]
Our team has identified an issue with app pinning where a SharePoint page is being shown through use of a contentUrl such as the following:

```
"contentUrl": "https://tenant.sharepoint.com/_layouts/15/TeamsLogon.aspx?spfx=true&dest=/sites/mysite"
```

We noticed that some users it was working for, but for others it was not. Leading to a "spinning wheel" indicator that persisted, and not showing the SharePoint page. 

After troubleshooting the manifest, specifically validDomains, avoiding the use of tokens, uppercasing, and lowercasing, all of which led to the same issue (for some this had worked, for some not). Also, some users had seen it working on teams in the browser, but not in the desktop app, and vice versa.

_It appears that this behavior is tied to SharePoint cookies which have not been loaded yet_. This can be replicated by viewing a working pinned app leveraging TeamsLogon.aspx. This can be broken by navigating to SharePoint in a different tab and clearing the application cache, then going back to the browser tab containing the teams pinned app, it will no longer work upon refresh. But visiting any SharePoint page again, in any tab, will cause the pinned app to work again.

The same was seen with the desktop version. If a user had not visited a SharePoint page in teams, the pinned app would fail. In my case, I added a channel tab to a SharePoint page, visited the tab, then went back to the pinned app, and it worked again.

This is a major issue as expecting someone to have been into SharePoint in the last while, just to make a pinned app work, makes for a very unreliable experience.

**Comment by Ravindra-MSFT** [comment]
Hi @MikeMorawski, Thanks for reaching out. Let us investigate with our internal team and come back to you.

**Comment by Wajeed-msft** [comment]
@MikeMorawski - Need clarity on few points
1. Does this work fine for sideloaded apps?
2. Have you included webApplicationInfo in your App Manifest? [See similar question](https://stackoverflow.com/a/57770834/576503). 
3. Are you getting any errors in [console logs](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/developer-tools#access-devtools-on-the-desktop)? 
3. Could you please share the app manifest (please remove the tenant specific details)?

**Comment by 2toLeadMike** [comment]
Sorry for the late reply. the webApplicationInfo is likely the culprit and was not included in the manifest. Appreciate the support on this one

**Comment by Wajeed-msft** [comment]
### Tell us about your experience! 

Hi @2toLeadMike! This issue is closed in our system. We would like your [feedback on your experience with our support team and Platform](https://aka.ms/DevSupportFeedback). 

Best regards, 
Teams Platform
