### ISSUE TITLE
Adaptive Card or Adaptive Card bot card attachment

### ISSUE THREAD

**Issue by mercer2000** [MicrosoftDocs/msteams-docs#3739]
The sample JSON for the Adaptive Card bot card does not work when sending from Composer. 

![image](https://user-images.githubusercontent.com/18239028/123557311-dde69400-d755-11eb-9a3a-08ec98702346.png)

The JSON from the js sample linked to works as expected. Is the sample JSON above actually valid?

https://github.com/microsoft/BotBuilder-Samples/blob/main/samples/javascript_nodejs/54.teams-task-module/bots/teamsTaskModuleBot.js

```

version: '1.0.0',
            type: 'AdaptiveCard',
            body: [
                {
                    type: 'TextBlock',
                    text: 'Enter Text Here'
                },
                {
                    type: 'Input.Text',
                    id: 'usertext',
                    placeholder: 'add some text and submit',
                    IsMultiline: true
                }
            ],
            actions: [
                {
                    type: 'Action.Submit',
                    title: 'Submit'
                }
            ]
        }
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55c5e4a1-6116-ec92-36e9-b94097bd83c7
* Version Independent ID: fd843eef-73e2-7a7e-9ac4-5c20fcf1fa2f
* Content: [Invoke and dismiss task modules - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/task-modules/invoking-task-modules#the-taskinfo-object)
* Content Source: [msteams-platform/task-modules-and-cards/task-modules/invoking-task-modules.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/task-modules/invoking-task-modules.md)
* Product: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **lajanuar**

**Comment by Chetana-MSFT** [comment]
Hi @mercer2000, Thanks for reaching out to us, Let us investigate at our end will get back you soon.

**Comment by Chetana-MSFT** [comment]
@mercer2000,  The sample JSON which you have provided is not valid, So could you please go through the below sample JSON

```
{
"type": "AdaptiveCard",
"$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
"version": "1.0",
"body": [
{
"type": "TextBlock",
"text": "Here is a ninja cat"
},
{
"type": "Image",
"url": "https://pbs.twimg.com/profile_images/3647943215/d7f12830b3c17a5a9e4afcc370e3a37e_400x400.jpeg",
"size": "Medium"
}
]
}
```
