### ISSUE TITLE
deep links chat automating "send"

### ISSUE THREAD

**Issue by danilansible** [MicrosoftDocs/msteams-docs#3741]
[Hi 
Trying to automate sending a deeplinks chat to users in a group chat.

msteams:://teams.microsoft.com/l/chat/0/0?users=user1@company.com,user2@company.com&topicName=Test&message=Hi%20Test

Now I'm calling this from python(webbrowser.open()) or curl., it opens ups  teams app and shows the message to be sent "Hi test" and waiting..
I have to manually click the send button or Enter to post the chat message, is there a way to automate this "Typing Enter or clicking that sendkey"

To sump up, how to post deep links chat message directly instead of waiting for "send" to be clicked.

![image](https://user-images.githubusercontent.com/52173669/123592013-5444ce00-d80a-11eb-85e1-056407bb23fd.png)

]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45541337-ecd7-5cf6-cbe4-3f0d2f39aa79
* Version Independent ID: 6b4203f0-2844-06c9-eaa3-9cc03e6f76c0
* Content: [Create deep links - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links#deep-linking-from-your-tab)
* Content Source: [msteams-platform/concepts/build-and-test/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/build-and-test/deep-links.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Mamatha-MSFT** [comment]
Hi @danilansible  - If you want to send messages directly, you can use Graph API. Please go through this [documentation ](https://docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-1.0&tabs=http)for more info.
