### ISSUE TITLE
In Mobile Teams @Mention showing %20 when we have space in name

### ISSUE THREAD

**Issue by bikkykumar1** [MicrosoftDocs/msteams-docs#3747]
```
var mention = new Mention
    {
        Mentioned = turnContext.Activity.From,
        Text = $"<at>{XmlConvert.EncodeName(turnContext.Activity.From.Name)}</at>",
    };
```

when we use above code to show mention it is good in Desktop client Teams App, But when we see this on mobile Android app it is showing %20 in name, if there is space in User's Name.
**For Eg:**
In Android app: Bikky%20Kumar, But actually it is Bikky Kumar

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b31b49dc-2890-fbb9-1b30-a3f93469d1e6
* Version Independent ID: f9877c67-43d2-78a5-dcf2-fd0ca4de2339
* Content: [Channel and group conversations with a bot - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/channel-and-group-conversations?tabs=dotnet)
* Content Source: [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **anclear**

**Comment by Mamatha-MSFT** [comment]
Hi @bikkykumar1 - Thanks for bringing up this issue. I am able to repro the issue and will raise a bug for this.

**Comment by Wajeed-msft** [comment]
@bikkykumar1  - could you please confirm if you still see this issue?
