### ISSUE TITLE
Setup custom webhook link is broken

### ISSUE THREAD

**Issue by LanJosh** [MicrosoftDocs/msteams-docs#3748]
The `Setup a custom webhook` link is broken on this section. Perhaps it should point to https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-incoming-webhook?

![image](https://user-images.githubusercontent.com/7851950/123714321-f07ecd00-d82a-11eb-9e67-b77c72128d65.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28316a67-22fa-8a05-1ae0-fbe1c5720ef9
* Version Independent ID: 8a250e46-2a30-af86-839d-9f83a8b48041
* Content: [Create and send messages - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-using?tabs=cURL#setting-up-a-custom-incoming-webhook)
* Content Source: [msteams-platform/webhooks-and-connectors/how-to/connectors-using.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/webhooks-and-connectors/how-to/connectors-using.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Sridevi-MSFT** [comment]
Hi @LanJosh - We are not facing this issue from our side. It's redirecting properly. So, could you please check again?

**Comment by LanJosh** [comment]
Hmm, yesterday I was getting a 404 when I hit this link but not experiencing it now either. I'll close this!

**Comment by LanJosh** [comment]
Ah, it was patched already https://github.com/MicrosoftDocs/msteams-docs/pull/3745/files
