### ISSUE TITLE
Teams Android fails to open OneNote tab

### ISSUE THREAD

**Issue by bruxy70** [MicrosoftDocs/msteams-docs#375]
We are having an issue with the Teams mobile client on Android (or possibly OneDrive client on Android). 
It cannot open OneNote tabs for the team Notebook. They open fine on the Windows client, but on Android (and possibly iOS) it says

> We couldn't open this section

I have traced this to an issue with OneDrive mobile client. When I uninstall OneDrive, the Notebook opens from Teams with no problem. 
For some reason, Teams opens OneNote using OneDrive, and it fails with the error. 
I have tried to open the Notebook directly from the OneDrive client and it produces the same error.
So it probably is an issue with OneDrive. 

**But also, why is Teams client calling OneDrive to open OneNote? Should not it call the OneNote app instead?**

**Comment by Wajeed-msft** [comment]
Hi @bruxy70 - There is an option to report the issue by shaking your phone (Shake & Send). Could you please do that? This would help us to get an idea of the Teams app version and other details.
