### ISSUE TITLE
Deep link breaks task module

### ISSUE THREAD

**Issue by Noja13it** [MicrosoftDocs/msteams-docs#3753]
Hi,

I have run into an problem that occurs when a user has a task module open in the desktop client, and then proceeds to open a deep link.

When a user opens a deep link in the MS Teams desktop application (that they have received from ex. an email), and that user currently has a task module open, Teams navigates to the deep link while the task module remains open. The task module cannot then be closed, the close button is no longer working. The only solution is to restart the teams client.

I have attached a recording of the issue.

https://user-images.githubusercontent.com/9943616/123805547-744dbd80-d8ee-11eb-8f22-88019e08a3e6.mp4

**Comment by Sridevi-MSFT** [comment]
@Noja13it - Thanks for bringing up this issue, Let us investigate at our end.

**Comment by Wajeed-msft** [comment]
@Noja13it - I have raise bug to track this internally. We will keep this thread updated.

**Comment by ChetanSharma-msft** [comment]
Hello @Noja13it - Sorry for delay in response.
This issue has fixed but will check if it's publicly rolled out with engineering team and let you know the updates.

**Comment by Prasad-MSFT** [comment]
@Noja13it - This issue is fixed now. We tested the fix in MS Teams Desktop Client. 
`Microsoft Teams Version 1.6.00.2359`
Attaching the screen recording for reference. Please do verify and confirm. 

Thanks!

https://user-images.githubusercontent.com/62237649/215474708-c1abc6d5-3043-474d-8a6c-eb2e5eaab556.mp4
