### ISSUE TITLE
Bot Throttling Limit

### ISSUE THREAD

**Issue by chialiyun** [MicrosoftDocs/msteams-docs#3759]
I read about the throttling limit per bot per thread: [here][1]

  [1]: https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/rate-limit#per-bot-per-thread-limit

I am trying to understand throttling limit of creating a bot conversation per channel.

Could anyone kindly explain the throttling limits? I do not quite understand "The per bot per thread limit controls the traffic that a bot is allowed to generate in a single conversation". Based on the scenario, "Create conversation", with "Time period in seconds" of 30 has "Maximum allowed operations" of 60. Does it mean that the my bot can only send 60 new conversation to a Channel in team every 30 seconds (roughly i.e. 2 new conversation every second)?

What does a single conversation refers to? Is it 1 conversation posting by the bot on a channel? In that case, how many conversation are there in the screenshot? 6? i.e. there are 6 create conversation operations? 
![image](https://user-images.githubusercontent.com/15521388/123962959-945fa880-d9e4-11eb-999a-db3982510ed7.png)
As such, is a conversation equivalent to a message? or a conversation refers to a series of message in the whole of Channel or 1 parent together with its replies?

Also why "if the application sends one bot message to each user, the thread limit does not throttle." Is it because, it did not hit the throttling limit of max 7 operations in a second?

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a57254c9-963d-ea1d-ecaf-dd0e7913526c
* Version Independent ID: 610c8514-bd72-46cc-75f1-991e2242019b
* Content: [Optimize your bot with rate limiting in Teams - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/rate-limit#per-bot-per-thread-limit)
* Content Source: [msteams-platform/bots/how-to/rate-limit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/bots/how-to/rate-limit.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Wajeed-msft** [comment]
Hi @chialiyun - 

> What does a single conversation refers to? Is it 1 conversation posting by the bot on a channel?

A conversation is **1:1 between bot and user**, **a group chat**, or **a channel in a team**. So if my Bot is being user by three users in 1:1 scope it's considered as 3 different conversations, same applies for group chat.  In case of team scope bot, each distinct channel is considered as a conversation.

>  In that case, how many conversation are there in the screenshot? 6? i.e. there are 6 create conversation operations?

In the sceenshot you provided, there are 6 messages ([activity](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-api-reference?view=azure-bot-service-4.0#send-to-conversation)) sent to single conversation.

**Comment by chialiyun** [comment]
Hi @Wajeed-msft, thanks for the reply!

I see. 

> In case of team scope bot, each distinct channel is considered as a conversation.
hence, if I have 2 different bot in a channel, will that be considered 2 conversation?

> In the sceenshot you provided, there are 6 messages (activity) sent to single conversation.
hence, if that bot were to send out 60 messages within 30 second, I will hit the throttling limit?

Also, would it be possible if you could explain the throttling limits? Is my understanding correct that at the point of my current operation (e.g. creating of a new message in channel A), I should not have more than 7 operations in the past 1 second, not have more than 8 other operations in the past 2 seconds, and and finally no more than 60 other operations in the past 30 seconds?
![image](https://user-images.githubusercontent.com/15521388/124537975-7911f480-de4d-11eb-80c3-a34794283a1c.png)

> The thread limit of 3600 seconds and 1800 operations applies only if multiple bot messages are sent to a single user.
As such, the 3600 seconds and 1800 operations does not apply to the group chat and channel in a team context?

**Comment by Wajeed-msft** [comment]
If you keep an average of 1RPS per thread per bot it should be good. If you are concerned about approaching [the limits](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/rate-limit#per-bot-per-thread-limit), you must implement the [backoff strategy](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/rate-limit#backoff-example). The values provided in this section are for estimation only. You need to code such that bot handles 429s and retries regardless of these limits. Each channel inside a team is a different thread and all the reply chains are part of the same thread. 

Update is different than send, but the limits are the same.

**Comment by Wajeed-msft** [comment]
Please reopen if you still have any queries.
