### ISSUE TITLE
Teams Android issue opening Forms

### ISSUE THREAD

**Issue by bruxy70** [MicrosoftDocs/msteams-docs#376]
We're having an issue with the Teams mobile client on Android (and most likely iOS). When we Add tab to fill a form to the channel and try to open it from the mobile client, it does not open the form. Instead, it opens https://forms.office.com/Pages/DesignPage.aspx.
From the Windows client, it works fine.

**Comment by Wajeed-msft** [comment]
Are you able to see your form in this new browser page (https://forms.office.com/Pages/DesignPage.aspx)?

Tabs are not yet supported on Mobile clients. By default, websiteUrl is opened in browser instead.

**Comment by Wajeed-msft** [comment]
Please reopen with more details.
