### ISSUE TITLE
Adaptive Cards with invoke action sample JSON is not valid

### ISSUE THREAD

**Issue by mercer2000** [MicrosoftDocs/msteams-docs#3760]
The sample JSON is not valid. 

![image](https://user-images.githubusercontent.com/18239028/123991946-c5ae8900-d990-11eb-9d07-2e8d7a09f887.png)

Missing a comma. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 672a763d-189b-8ba0-f66e-c07f1dc0a962
* Version Independent ID: 1ac7a9bd-138b-3bf8-60a3-1842d87371fd
* Content: [Add card actions in a bot - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-actions?tabs=json#adaptive-cards-actions)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-actions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-actions.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Wajeed-msft** [comment]
Thank you so much for taking time to report this. I have raised PR to fix this.
