### ISSUE TITLE
First code sample wrongly titled

### ISSUE THREAD

**Issue by NeemaB-HCL** [MicrosoftDocs/msteams-docs#3764]
[Enter feedback here]
The first code sample in the "Samples" section is said to perform proactive app installation through graph API but I believe it is wrongly labeled. The code section only handles proactive notification messages but does not cover installation of the bot application into teams.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ad9f167-7d29-f933-7b47-60bd744899b1
* Version Independent ID: 8097fcbd-adcc-ce49-a378-426c65af9296
* Content: [Send proactive messages - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/send-proactive-messages?tabs=dotnet)
* Content Source: [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/bots/how-to/conversations/send-proactive-messages.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **anclear**

**Comment by Wajeed-msft** [comment]
@NeemaB-HCL - Thank you so much for taking time to report this. 

@surbhigupta12 - could you please help to update with following changes?
1. Update this line "The following code shows a simple code sample that proactively installs your app using Graph" to "The following code shows how to send proacive message:"
2.  Add these samples to code samples sections for following topics. 
- https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/send-proactive-messages?tabs=dotnet#code-sample
- https://docs.microsoft.com/en-us/microsoftteams/platform/graph-api/proactive-bots-and-messages/graph-proactive-bots-and-messages#additional-code-samples


<html>
<body>


 1 | Proactive installation of App and sending proactive notifications | This sample illustrates how you can use Proactive installation of app for user and send proactive notification by calling Microsoft Graph APIs. . | [View](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/graph-proactive-installation/csharp) | [View](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/graph-proactive-installation/nodejs)|
-- | -- | -- | -- | --



</body>
</html>
