### ISSUE TITLE
App Hosted Bot - missing scale and perf docs

### ISSUE THREAD

**Issue by RicardoNiepel** [MicrosoftDocs/msteams-docs#3765]
The section for [Scalability and performance considerations](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/calls-and-meetings/requirements-considerations-application-hosted-media-bots#scalability-and-performance-considerations) is missing content.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6be953e-43af-0b42-6a9f-ed7776c595bb
* Version Independent ID: a8b8d285-955f-1f86-1484-6a75aa8ffaf8
* Content: [Requirements and considerations for application-hosted media bots - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/calls-and-meetings/requirements-considerations-application-hosted-media-bots)
* Content Source: [msteams-platform/bots/calls-and-meetings/requirements-considerations-application-hosted-media-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/bots/calls-and-meetings/requirements-considerations-application-hosted-media-bots.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Meghana-MSFT** [comment]
@RicardoNiepel ,

Thanks for taking time to report this issue. The documentation team will look into it.
