### ISSUE TITLE
The Bot Framework SDK for Node.js does not currently support OAuthCard

### ISSUE THREAD

**Issue by Shon-Elias** [MicrosoftDocs/msteams-docs#377]
I would like to use the OAuthCard with my bot on Microsoft teams. According to the document, it says "**The Bot Framework SDK for Node.js does not currently support OAuthCard**"

When this should be available?

**Comment by billbliss** [comment]
As far as we know, it's not planned at all, so you can't.

There is a way to do it in Node yourself. See https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/authentication/auth-flow-bot and https://github.com/OfficeDev/microsoft-teams-sample-auth-node.

@clearab / @NormSohl we should link to these from https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/authentication/auth-oauth-card where we say "The Bot Framework SDK for Node.js does not currently support OAuthCard"

**Comment by Wajeed-msft** [comment]
@Shon-Elias - Please try this node.js sample: https://github.com/Microsoft/BotBuilder-V3/blob/master/Node/examples/basics-oauth/app.js
