### ISSUE TITLE
The thumbnail of a recorded teams meeting shows duration as NaNs

### ISSUE THREAD

**Issue by prateeksharma17** [MicrosoftDocs/msteams-docs#3776]
![IMG_20210702_234315](https://user-images.githubusercontent.com/81974731/124314075-76827700-db8f-11eb-8b1a-2dd2b970bc6e.jpg)

As shown in the screenshot, the thumbnail of a recorded teams meeting shows duration as NaNs. Ideally it should display the correct duration. But it is parsed as Not A Number (NaN).

**Comment by kingraaa** [comment]
We are also having this problem with all recordings
