### ISSUE TITLE
Add Details to allow custom app on Admin > global policy

### ISSUE THREAD

**Issue by bkakadiya** [MicrosoftDocs/msteams-docs#3777]
Hi

It took few hours to find that global policy needs to be updated to allow custom app. Please add it on this page as a pre-requisite.

Thanks,
Bakul

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33cdb816-f2b6-31a4-0e4c-d730435d0a6b
* Version Independent ID: c111eaef-ac66-e245-b2bc-623c1801a7db
* Content: [Tutorial - Create your first app using Node.js - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/get-started/get-started-nodejs-app-studio?tabs=AS)
* Content Source: [msteams-platform/get-started/get-started-nodejs-app-studio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/get-started/get-started-nodejs-app-studio.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Meghana-MSFT** [comment]
Hi @bkakadiya 

Did you get a chance to look at [setup your development environment](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/prepare-your-o365-tenant#enable-custom-teams-apps-and-turn-on-custom-app-uploading). 
Attaching a screenshot for you reference. Hope this answers your query.

![image](https://user-images.githubusercontent.com/81138249/124467599-add26d00-ddb5-11eb-8e1a-a3cd447259d7.png)

**Comment by bkakadiya** [comment]
Thanks,

I can see that link on the first teams app. Not sure how I missed it. I
would still suggest to mention the same thing in to "Register your app in
teams" section under step #4 in case if someone missed it (similar to me
and not able to find a way to publish the app)

Screenshots:
I can see it here:
[image: image.png]


I would suggest to add it

[image: image.png]


and here
[image: image.png]

Thanks,
Bakul
