### ISSUE TITLE
Looks like the timeline of extra margins removal is not executed?

### ISSUE THREAD

**Issue by kafka-yu** [MicrosoftDocs/msteams-docs#3778]
Hi team,

We're handling the tab's extra margins, and seeing the timeline for production is at 
> June 15, 2021 - Margins will be removed in production.

But, looks like for now, it still exists in production? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9e1dcae-86bf-3546-de37-f746f60ddf63
* Version Independent ID: 2a11fb54-d08d-2e06-14cc-ab3e9a4edaeb
* Content: [Removing tab margins in Microsoft Teams - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/removing-tab-margins#feedback)
* Content Source: [msteams-platform/resources/removing-tab-margins.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/resources/removing-tab-margins.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lomeybur**

**Comment by Wajeed-msft** [comment]
@kafka-yu - checking this with engineering team. We will update this thread as well as docs once we get confirmation.

**Comment by kafka-yu** [comment]
hi team, any update of this one?

**Comment by Wajeed-msft** [comment]
@lokimeyburg - we are still waiting for confiramtion on this.

**Comment by Wajeed-msft** [comment]
@kafka-yu  - we're extending the deadline till the end of the month to give developers more time. We will update the docs.

**Comment by v-abirade** [comment]
@surbhigupta12,

Please close the issue manually. The linked PR: https://github.com/MicrosoftDocs/msteams-docs/pull/3850 has been merged already.
