### ISSUE TITLE
Duplicated paragraphs - please consider deleting one.

### ISSUE THREAD

**Issue by JorgeALeitao** [MicrosoftDocs/msteams-docs#3781]
These two paragraphs seem duplicate

Currently, bot developers who want to retrieve information for one or more members of a chat or team use the Microsoft Teams bot APIs TeamsInfo.GetMembersAsync for C# or TeamsInfo.getMembers for TypeScript or Node.js APIs. For more information, see fetch roster or user profile. These APIs have several shortcomings.

Currently, if you want to retrieve information for one or more members of a chat or team, you can use the Microsoft Teams bot APIs TeamsInfo.GetMembersAsync for C# or TeamsInfo.getMembers for TypeScript or Node.js APIs. These APIs have the following shortcomings:

It looks like that there were two version and inadvertently both made to the final post. Please consider deleting the first one.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c780d605-b1b2-716f-5888-503608769b5a
* Version Independent ID: 53c724f8-d9a2-4af6-6d75-ddeaef084137
* Content: [Bot API changes for team and chat members - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/team-chat-member-api-changes?source=docs#api-changes)
* Content Source: [msteams-platform/resources/team-chat-member-api-changes.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/resources/team-chat-member-api-changes.md)
* Product: **msteams**
* GitHub Login: @ojasvichoudhary
* Microsoft Alias: **ojchoudh**

**Comment by Wajeed-msft** [comment]
@surbhigupta12 - could you please help to fix this?
