### ISSUE TITLE
Fix validation errors - error message isn't displayed

### ISSUE THREAD

**Issue by DanielLevy0705** [MicrosoftDocs/msteams-docs#3788]
Hi,
I've been importing a chatbot from the same zip file for over a year, and it worked great.
Today suddenly when I  tried to import the same zip file, I got the Fix validation errors pop up, and no errors were displayed.
What is the possible cause for this error? And how can i fix this?
Adding a screenshot, Thanks in advance!
<img width="1193" alt="Screenshot_1" src="https://user-images.githubusercontent.com/45950605/124746972-235f4a00-df2a-11eb-9d7e-a073f5fe4aa3.png">

**Comment by wilsonvolker** [comment]
Some dirty fix for me:

1. Remove `groupchat` from bots.scopes in manifest.json.
2. Zip up the manifest.json files as usual
3. Go to [Developer Portal (Preview)](https://dev.teams.microsoft.com/home)
4. Click **Apps** on the Developer Portal
5. Click **Import app** on the Apps page
6. After the successful message shown, go back to Teams --> App Studio
7. You should find your app on the Manifest editor page in App Studio
8. Click on the app to go for Edit
9. Click every single pages on the Manifest editor -> edit page of your app (i.e. all the pages shown on left hand-side menu). This action is just for triggering the manifest validation
![image](https://user-images.githubusercontent.com/40080421/124858289-582dd880-dfe0-11eb-9b45-51080ba199fe.png)
10. On the editor menu, go to **Test and distribution** 
11. Install the application for testing
12. Here you go :)

**Comment by shahid-se** [comment]
Followed the above steps but getting the error shown below:
![image](https://user-images.githubusercontent.com/85476139/124864352-6545ca00-dfd6-11eb-932f-98b01bc03927.png)

**Comment by wilsonvolker** [comment]
Is there any log or errors on the browser console? It might be hidden in Verbose

**Comment by shahid-se** [comment]
We have two finding from error logs:

1. Mustache Values in manifest.json is not replacing from .env files. For example, "{{PUBLIC_HOSTNAME}}", "{{MICROSOFT_APP_ID}}"

> Error while reading manifest.json: Invalid value(s) specified for validDomains[1]: "{{PUBLIC_HOSTNAME}}"

 2. It is showing error for Configurable tabs if I have selected two scopes.
 
> Invalid value(s) specified for configurableTabs[0].scopes.length: "2"

**Comment by DanielLevy0705** [comment]
@wilsonvolker I didn't have groupchat scope in my json, it was added manually afterwards when editing the bot in app studio.
I'll try following these steps with my current json.

**Comment by DanielLevy0705** [comment]
@wilsonvolker I already got the app installed, when importing to Developer portal (step 5) It asks me if I'd like to duplicate or replace it. Getting error messages for both actions.
Replace - `Failed to duplicate app` (console logs 404 error for action POST to `appdefinitions` API)
Duplicate - `Failed to get app definitions` (console log 404 error for action GET to the same API)

**Comment by shahid-se** [comment]
I was also getting the same error. So I have created new GUID for "id" value in manifest.json

**Comment by DanielLevy0705** [comment]
> I was also getting the same error. So I have created new GUID for "id" value in manifest.json

can you please instruct me how to do it?

**Comment by shahid-se** [comment]
Short cut to do that is in manifest.json on line number 3, you can alter last two/three number which will consider as new GUID.
![image](https://user-images.githubusercontent.com/85476139/124869310-a2ae5580-dfde-11eb-8099-e76a4f9115c0.png)

**Comment by DanielLevy0705** [comment]
Thanks, after changing the id, I got this `Failed to upload App` error message.
In the console I can see error code 500 as a response to Post action to API `https://dev.teams.microsoft.com/api/appdefinitions/apppackage`

**Comment by Meghana-MSFT** [comment]
@DanielLevy0705 ,

could you please share your manifest?

**Comment by DanielLevy0705** [comment]
![manifest_json_img](https://user-images.githubusercontent.com/45950605/124901571-cc6d7980-dfea-11eb-8fe0-811adf592c8b.png)
@Meghana-MSFT

**Comment by shahid-se** [comment]
@Meghana-MSFT , I am also facing the above same issue.

We want a bot for personal, teams and channel scope.
We want a configurable tab for teams and channel scope.
We want a static tab for personal scope.

We are facing this issue from yesterday onwards. Kindly help us to resolve this issue as soon as possible.

Manifest.json details:

> {
  "$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.9/MicrosoftTeams.schema.json",
  "manifestVersion": "1.9",
  "id": "fc9f2a14-e48e-4261-a455-294c95696633",
  "version": "2.0",
  "packageName": "com.abc.teams.extension",
  "developer": {
    "name": "ABC",
    "websiteUrl": "https://abc.com",
    "privacyUrl": "https://abc.com/privacy",
    "termsOfUseUrl": "https://abc.com/terms"
  },
  "name": {
    "short": "ABC",
    "full": "ABC"
  },
  "description": {
    "short": "Short description of ABC App.",
    "full": "Full description here"
  },
  "icons": {
    "outline": "icon-outline.png",
    "color": "icon.png"
  },
  "accentColor": "#0079bf",
  "configurableTabs": [
    {
      "configurationUrl": "https://f88958ab1092.ngrok.io/abctab/config.html?name={loginHint}&tenant={tid}&group={groupId}&theme={theme}",
      "canUpdateConfiguration": true,
      "scopes": [
        "team",
        "groupchat"
      ]
    }
  ],
  "staticTabs": [
    {
      "entityId": "bf580x80-zf2e-11eb-b64d-d37a434fc344",
      "name": "ABC",
      "contentUrl": "https://f88958ab1092.ngrok.io/abctab/",
      "scopes": [
        "personal",
        "team"
      ]
    }
  ],
  "bots": [
    {
      "botId": "63f2a7d0-a4d0-4fff-8c20-b2eb21c6c8d8",
      "needsChannelSelector": true,
      "isNotificationOnly": false,
      "supportsFiles": false,
      "supportsCalling": false,
      "supportsVideo": false,
      "scopes": [
        "team",
        "personal",
        "groupchat"
      ],
      "commandLists": [
        {
          "scopes": [
            "team",
            "personal"
          ],
          "commands": [
            {
              "title": "help",
              "description": "Shows help information"
            }
          ]
        }
      ]
    }
  ],
  "connectors": [],
  "composeExtensions": [
    {
      "botId": "63f2a7d0-a4d0-4fff-8c20-b2eb21c6c8d8",
      "commands": [
        {
            "id": "createCard",
            "context": [
                "compose"
            ],
            "description": "Command to run action to create a Card from Compose Box",
            "title": "Create Card",
            "type": "action",
            "parameters": [
                {
                    "name": "title",
                    "title": "Card title",
                    "description": "Title for the card",
                    "inputType": "text"
                },
                {
                    "name": "subTitle",
                    "title": "Subtitle",
                    "description": "Subtitle for the card",
                    "inputType": "text"
                },
                {
                    "name": "text",
                    "title": "Text",
                    "description": "Text for the card",
                    "inputType": "textarea"
                }
            ]
        }
      ],
      "messageHandlers": [
          {
              "type": "link",
              "value": {
                  "domains": [
                      "*.botframework.com"
                  ]
              }
          }
      ]
    }
  ],
  "permissions": [
    "identity",
    "messageTeamMembers"
  ],
  "validDomains": [
    "f88958ab1092.ngrok.io"
  ],
  "showLoadingIndicator": true,
  "defaultInstallScope": "personal"
}

**Comment by Meghana-MSFT** [comment]
@DanielLevy0705 , @shahid-se 

There seems to be an issue with the app studio. As a work around please try uploading your app using below options.

1. Developer portal (preview) in app studio
2. Upload a custom app from apps.

We have raised a bug and the concerned team is looking into it.

**Comment by DanielLevy0705** [comment]
@Meghana-MSFT Thank you! is there any link of an issue that we can follow its progress?

**Comment by Meghana-MSFT** [comment]
@DanielLevy0705,

We will update this thread once bug is resolved

**Comment by willblenkhornjisc** [comment]
I have had similar problems trying to follow these instructions: https://docs.microsoft.com/en-us/microsoftteams/platform/get-started/get-started-nodejs-app-studio?tabs=DP, to deploy the hello-world-app. I had unknown validation issues using app studio and then APP_ID already exists in organisation for dev portal with no explanation as to how to fix it.

**Comment by shahid-se** [comment]
> @DanielLevy0705 , @shahid-se
> 
> There seems to be an issue with the app studio. As a work around please try uploading your app using below options.
> 
> 1. Developer portal (preview) in app studio
> 2. Upload a custom app from apps.
> 
> We have raised a bug and the concerned team is looking into it.

@Meghana-MSFT 

1. Developer portal (preview) in app studio - It is creating issue of duplicate app id
2. Upload a custom app from apps. - This option is working fine. We were able add our App successfully from here.

**Comment by shahid-se** [comment]
@DanielLevy0705 @Meghana-MSFT ,
It seems like App Studio issue is resolved. Today I was able to install my App from there without any issue.

**Comment by DanielLevy0705** [comment]
Agreed, I've managed to install my app using AppStudio. Thanks! this issue can be closed.

**Comment by shahid-se** [comment]
@DanielLevy0705 @Meghana-MSFT We are getting same issue again.. Can you please check again?

**Comment by Meghana-MSFT** [comment]
@shahid-se , 
We have already raised a bug for this and the concerned team is looking into it. Currently we do not have an ETA to share but we will update this thread once bug is resolved.

**Comment by shahid-se** [comment]
@Meghana-MSFT Thank you for quick response.. Can we reopen this issue so that we can better track it?

**Comment by Meghana-MSFT** [comment]
@shahid-se 

Could you please try again and check if its working? I was able to upload the manifest without any issue. We got an update from the engineering teams saying there was an import issue last week on Friday but it was fixed the same day.

**Comment by shahid-se** [comment]
> @shahid-se
> 
> Could you please try again and check if its working? I was able to upload the manifest without any issue. We got an update from the engineering teams saying there was an import issue last week on Friday but it was fixed the same day.

Yes @Meghana-MSFT It was resolved when I have checked on Monday. You can close it as of now.
