### ISSUE TITLE
Call Notification Toast - Forwarding User Information missing for Call Queues

### ISSUE THREAD

**Issue by toellbe** [MicrosoftDocs/msteams-docs#3789]
Calls that are forwarded to another user receive information about the forwarding user.  If the agent is forwarded to a call queue, the information is not visible to the agent. It is only displayed for which queue the call is intended.

**Comment by Wajeed-msft** [comment]
@toellbe - could you please help to raise this on [call queue](https://docs.microsoft.com/en-us/microsoftteams/answer-auto-attendant-and-call-queue-calls) documentation by selecting Submit feedback? 

![image](https://user-images.githubusercontent.com/31851992/124871243-6defcd80-dfe1-11eb-9923-2cf43b69e9fa.png)
