### ISSUE TITLE
How to get the subEntityId from deep link on mobile teams client

### ISSUE THREAD

**Issue by sunnychan101** [MicrosoftDocs/msteams-docs#3796]
Hi all,

I am trying to get the subEntityId from deep link for the teams app, the teams app is built by spfx framework. It works fine on both web and desktop teams client, however when it comes on the mobile client, it didn't work anymore.

This is the way I get the subEntityId, I am using the teams javaScript client SDK
`microsoftTeams.getContext((c) => {
        this.setState({ state1: c, location: c.subEntityId });
      });`

I have also tried the deep link using https and msteams protocol, it still not working.

https://teams.microsoft.com/l/entity/d4bec247-9ece-404a-8f4a-16f275def087/tasklist123?webUrl=https://tasklist.example.com/123/456&context={%22subEntityId%22:%20%22detail%22}

 msteams://teams.microsoft.com/l/entity/d4bec247-9ece-404a-8f4a-16f275def087/tasklist123?webUrl=https://tasklist.example.com/123/456&context={%22subEntityId%22:%20%22detail%22}

May I know is deep link for subEntityId is not supported on mobile client? If not, any road map we can have this features?

Thanks all for your help

**Comment by HunaidHanfee-MSFT** [comment]
Hello,
We are closing this issue as we have already got your issue [link](https://docs.microsoft.com/en-us/answers/questions/467291/how-to-get-the-subentityid-from-deep-link-on-mobil.html) and we are looking into it.

Thanks.
