### ISSUE TITLE
Teams: Wrong value returned for Input.Time in adaptive card for certain locales

### ISSUE THREAD

**Issue by matthiasdilger** [MicrosoftDocs/msteams-docs#3806]
Scenario:
Teams locale is set to Chinese or Korean
Bot sends adaptive card to user, card contains Input.Time and Submit button
User selects an afternoon time like 2:30下午(Chinese) and submits the card
The bot receives the submitAction but the time is 02:30 (AM!), should be 14:30

See also: https://github.com/microsoft/botbuilder-js/issues/3861

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adcfd49d-0d36-b19a-2857-395289f1c6c2
* Version Independent ID: 464b2cd8-0cd7-dd52-aef6-47e040c89c8d
* Content: [Cards - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/what-are-cards)
* Content Source: [msteams-platform/task-modules-and-cards/what-are-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/what-are-cards.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Meghana-MSFT** [comment]
We are looking into the issue and will respond back to you soon

**Comment by Meghana-MSFT** [comment]
@matthiasdilger,

We were able to repro the issue. We have raised a bug and the concerned team is looking into it.

**Comment by matthiasdilger** [comment]
Just tried it again and it seems to have been fixed. Thanks! Closing.

**Comment by matthiasdilger** [comment]
Just got feedback from users that this is not fixed yet for their Windows build (1.4.00.20314). Reopening.

**Comment by Wajeed-msft** [comment]
@Meghana-MSFT - could you please check this? 

> Just tried it again and it seems to have been fixed. Thanks! Closing.

@matthiasdilger - are you also able to repro the same?

**Comment by matthiasdilger** [comment]
@Wajeed-msft Originally, I was able to reproduce the error in both browser and Mac desktop client. I tried again two days ago and it worked on both platforms, so I assumed it fixed. I sent out an email to the users that originally notified me of this issue and told them it is fixed, but the feedback was that it's not working on the above mentioned Windows build. I currently don't have access to a Windows machine to reproduce.

**Comment by matthiasdilger** [comment]
@Wajeed-msft Tried it again on browser, it's currently broken again for both Chinese and Korean. Maybe something (in the backend) was rolled back?

**Comment by Meghana-MSFT** [comment]
@matthiasdilger We are able to repro the issue. We have informed the same to concerned team.

**Comment by matthiasdilger** [comment]
Hi @Wajeed-msft @Meghana-MSFT 
I saw this has been fixed in the Teams developer preview. Any info on when this fix will become generally available? Thanks

**Comment by matthiasdilger** [comment]
Issue fixed in latest stable Teams version (1.4.00.22926). Thank you!
