### ISSUE TITLE
Continue conversation can use tenant id and conversation id but doesn't specify anywhere how

### ISSUE THREAD

**Issue by leonliang-apprentice** [MicrosoftDocs/msteams-docs#3815]
There's no documentation anywhere on how to use the tenant id and conversation id to continue a conversation.
My educated guess would be that you use 
`continueConversation(<tenantId>, <conversationId>)`

or 

```
continueConversation({
 tenantId, conversationId
})
```

But i wouldn't know nor is there a way to figure it out

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ad9f167-7d29-f933-7b47-60bd744899b1
* Version Independent ID: 8097fcbd-adcc-ce49-a378-426c65af9296
* Content: [Send proactive messages - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/send-proactive-messages?tabs=dotnet#get-the-conversation-id)
* Content Source: [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/bots/how-to/conversations/send-proactive-messages.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **anclear**

**Comment by v-chetsh** [comment]
Hello @leonliang-apprentice,
As per Microsoft.Bot.Builder 4.0, we do not have method that explicitly pass tenant id as a parameter in continueconversationasync() method.
Reference docs URL:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.bot.builder.botadapter.continueconversationasync?view=botbuilder-dotnet-stable#Microsoft_Bot_Builder_BotAdapter_ContinueConversationAsync_System_String_Microsoft_Bot_Schema_ConversationReference_Microsoft_Bot_Builder_BotCallbackHandler_System_Threading_CancellationToken_

Thanks!!

**Comment by v-chetsh** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.
