### ISSUE TITLE
Bot is not receiving messages/commands?! (GCC bot sideload. Tab works fine.) 

### ISSUE THREAD

**Issue by liangchr** [MicrosoftDocs/msteams-docs#3816]
Bot is not receiving messages?! (GCC bot sideload. Tab works fine.) 

Any idea what is causing this? it is a gcc bot on a gcc organization/user. 

Problem started ~ 3 weeks ago. Bot was working perfectly fine before. Even STRANGER is my commercial bots can be sideloaded onto my GCC user. How can this be?

**Comment by Meghana-MSFT** [comment]
@liangchr ,

Could you please share your Bot Id and timestamp information to General questions Support in [Microsoft Teams developer community channels](https://docs.microsoft.com/en-us/microsoftteams/platform/feedback)

**Comment by Meghana-MSFT** [comment]
@liangchr ,

Let us know if you are still facing the issue?

**Comment by Meghana-MSFT** [comment]
@liangchr ,

We are closing this issue due to user inactivity. Please feel free to re open this issue if you are still facing the issue.
