### ISSUE TITLE
Unable to access voice note feature for bot

### ISSUE THREAD

**Issue by aklaw09** [MicrosoftDocs/msteams-docs#3819]
I was trying to develop a bot that can transcribe user voice notes and respond accordingly using the voice note feature available in teams mobile version. Voice note option does not appear for when in bot chat window, while it is available in personal chat windows of other users. Permissions to access the user microphone have been granted, but no change was seen. 

I'm using an Android 10 phone (Samsung A20). Would like to know if there are any possible solutions to this.

**Comment by Wajeed-msft** [comment]
@aklaw09 - Microsoft Teams Bots currently do not support voice commands. Please post feature suggestions on [Microsoft Teams feedback portal on UserVoice](https://microsoftteams.uservoice.com/forums/555103-public-preview/category/182881-developer-platform).


**Alternative:** [Calls and online meetings bots](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/calls-and-meetings/calls-meetings-bots-overview) can interact with Teams calls and meetings using real-time voice, video, and screen sharing using. Please take a look at [sample code](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/calls-and-meetings/calls-meetings-bots-overview#code-sample) as well.

**Comment by aklaw09** [comment]
Thanks @Wajeed-msft for confirming this. I'll take a look at the references.
