### ISSUE TITLE
Bot api deprecation clarification 

### ISSUE THREAD

**Issue by liangchr** [MicrosoftDocs/msteams-docs#3823]
https://docs.microsoft.com/en-us/microsoftteams/platform/resources/team-chat-member-api-changes

1.) When is api deprecation going into affect? 
2.) Are the bellow two apis the new ones to rely on? (To switch to?)
3.) How does the continuationToken work and where do I get it? 
4.) LESS IMPORTANT: I do plan to stick to botkit v3 but use raw http requests module to grab team members instead of botkit. I want to confirm the feasibility of this. 
```

GET /v3/conversations/19:meeting_N2QzYTA3YmItYmMwOC00OTJmLThkYzMtZWMzZGU0NGIyZGI0@thread.v2/pagedmembers?pageSize=100&continuationToken=asdfasdfalkdsjfalksjdf
https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/get-teams-context?tabs=json#fetch-the-roster-or-user-profile

GET /v3/conversations/19:ja0cu120i1jod12j@skype.net/members/29:1GcS4EyB_oSI8A88XmWBN7NJFyMqe3QGnJdgLfFGkJnVelzRGos0bPbpsfJjcbAD22bmKc4GMbrY2g4JDrrA8vM06X1-cHHle4zOE6U4ttcc
```

Team: https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/get-teams-context?tabs=json#fetch-the-roster-or-user-profile

Single Member: https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/get-teams-context?tabs=dotnet#get-single-member-details

**Comment by HunaidHanfee-MSFT** [comment]
Hello, 
Answer 1. As of now there is no exact date to tell. Documentation says : 

> By late 2022, bots cannot proactively retrieve the userPrincipalName or email properties for members of a chat or team. Bots must use Graph to retrieve them. The userPrincipalName and email properties are not returned from the new GetConversationPagedMembers API starting in late 2022. Bots have to use Graph with an access token to retrieve information. It must be made easier for bots to get an access token and streamline and simplify the end-user consent process. 

Answer 2. Yes, you can rely on them.
Answer 3. You don't need to get continuation token from anywhere if you see example from documentation.

```
string continuationToken = null;
        do
        {
            var currentPage = await TeamsInfo.GetPagedMembersAsync(turnContext, 100, continuationToken, cancellationToken);
            continuationToken = currentPage.ContinuationToken;
            members.AddRange(currentPage.Members);
         }
         while (continuationToken != null);
```
 A continuation token is based on the data being fetched for a particular query and you can use this token to fetch the next set of data and you receive it as a response from the same query.
Answer 4. I found botkit v3 much cleaner but you should be able to that.

Thanks
