### ISSUE TITLE
Bot sends card with wrong image

### ISSUE THREAD

**Issue by liangchr** [MicrosoftDocs/msteams-docs#3824]
I've been trying to send a card with an updated image but the image isn't updating. I've cleared my MSTeams cache. 

It has been over 24 hours and the image still isn't updating. 

Developer view shows image url as: 
https://urlp.asm.skype.com/v1/url/content?url=https://teams.webexapps.com/assets/webex_icon_300ppi.png

This is wrong. Image url should be: https://teams.webexapps.com/assets/webex_icon_300ppi.png

What is going on here?

**Comment by Wajeed-msft** [comment]
@liangchr - could you please share screenshot of what you see? I could see following for both the URLs:
![image](https://user-images.githubusercontent.com/31851992/125679026-af05a7c0-8e57-4eb6-84e1-c937045d20f4.png)

**Comment by liangchr** [comment]
@Wajeed-msft I see: 
<img width="395" alt="Screen Shot 2021-07-14 at 2 31 27 PM" src="https://user-images.githubusercontent.com/10538763/125695781-3a56ad41-65ff-4e41-9413-6ef967d19995.png">
 for the first one and: 
<img width="320" alt="Screen Shot 2021-07-14 at 2 32 26 PM" src="https://user-images.githubusercontent.com/10538763/125695860-f9457694-e5b0-487d-ad95-b3ff17e8d1c6.png">
for the second one.

**Comment by liangchr** [comment]
tried native chrome, desktop, and edge. My machine is macos. The image refuses to update for me.

**Comment by liangchr** [comment]
@Wajeed-msft this is what my machine redirects to: https://urlp.sfbassets.com/urlpcdn/nus1/contentdel30/b2917c05-32fd-45d9-9b49-077744851502

**Comment by Wajeed-msft** [comment]
@liangchr - Thanks for sharing the screenshot and URLs. Team is already looking into this. I'll let you know once I have further updates.

**Comment by Wajeed-msft** [comment]
@liangchr - could you please share the card json or bot code that is sending the card and image?

**Comment by Wajeed-msft** [comment]
@liangchr - Are you still facing this issue? could you please share the card json or bot code that is sending the card and image?

**Comment by liangchr** [comment]
@Wajeed-msft fixed. had to clear browser history though. It was really annoying :) Thanks for the help!
