### ISSUE TITLE
Animated GIF is not supported (but it is!)

### ISSUE THREAD

**Issue by andersonpimentel** [MicrosoftDocs/msteams-docs#3829]
Although the docs state that Animated GIF is not supported, it seems to be. I had no problem with animated GIFs so far.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Types of cards - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference#inline-card-images)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Prasad-MSFT** [comment]
Hi  @andersonpimentel ,
We are checking internally whether its supported in all platforms or not. After confirmation we will redirect the issue to appropriate team/forum.

**Comment by Wajeed-msft** [comment]
@andersonpimentel - Currently, animated GIFs are not fully supported on mobile platform. We have backlog item to track this internally so closing this from Docs issues page.
