### ISSUE TITLE
Please add link to Device Permissions sample code to this page.

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#3841]
Link to use for NodeJs sample: https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/tab-device-permissions/nodejs

<html>
<body>

Device permissions | Microsoft Teams tab sample app for demonstrating device permissions |  <a href='https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/main/samples/tab-device-permissions/nodejs'>View</a>

<br class="Apple-interchange-newline">
</body>
</html>
---

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77abdbe7-57e8-a310-eb23-c3894c1b6a30
* Version Independent ID: 01788900-eaff-186d-53eb-b4bdfbd16055
* Content: [Device capabilities - Overview - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/device-capabilities-overview)
* Content Source: [msteams-platform/concepts/device-capabilities/device-capabilities-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/device-capabilities/device-capabilities-overview.md)
* Product: **msteams**
* GitHub Login: @Rajeshwari-v
* Microsoft Alias: **surbhigupta**

**Comment by v-chetsh** [comment]
@surbhigupta12 - Please help us here to update the contents.
