### ISSUE TITLE
Copy link is not working

### ISSUE THREAD

**Issue by mipradhan** [MicrosoftDocs/msteams-docs#3845]
[Enter feedback here]

When I try to click on the paper clip icon next to a topic to copy it, it is not getting copied to the clipboard. 

Used to work earlier. Seems to have stopped working for me

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b94a38e-82f8-45a1-8ccc-b0a96edd0404
* Version Independent ID: 6e077924-9658-cdd2-50de-0f9561d6366b
* Content: [Create a configuration page - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/configuration-page)
* Content Source: [msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Wajeed-msft** [comment]
@v-abirade - could you please help to check this issue?

**Comment by v-abirade** [comment]
@Wajeed-msft, the paper clip icon next to the topic is the link for that section. It will not copy the entire section, but if we right-click on the paper clip, then we can copy the link only. The copy option next to the codes are working fine.  It is not a doc-bug. Please remove the label.
