### ISSUE TITLE
Is outgoing webhook send request from client or server side? and how to debug outgoing webhook? 

### ISSUE THREAD

**Issue by NagleZhang** [MicrosoftDocs/msteams-docs#3856]
Hi msteams maintainer, 

I'm using ms-teams to send post requests to outgoing webhook(a internal service within company level network) .
I can use my http client (eg. curl) to do such thing, but when using @metion way I will get response `Sorry, there was a problem encountered with your request` . 

I'm wondering is this reuquest send by teams client or teams service? How can I debug it?

**Comment by HunaidHanfee-MSFT** [comment]
Hello @NagleZhang,
Whenever you @mention, request get sent to the callback URI you have mention while configuring the outgoing webhook. To debug the issue you need to get that code and debug locally or maybe you can use kudu on Azure or there are various way based on how the webhook is deployed.

Your webhook might be similar to the [sample](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/outgoing-webhook) and you can try same to debug and run locally in [.Net](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/outgoing-webhook/csharp#to-try-this-sample) or [Node.js](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/outgoing-webhook/nodejs#steps-to-run-locally).

[Let us know if you still have issue]
Thanks

**Comment by NagleZhang** [comment]
> Whenever you @mention, request get sent to the callback URI you have mention while configuring the outgoing webhook. To debug the issue you need to get that code and debug locally or maybe you can use kudu on Azure or there are various way based on how the webhook is deployed.

Hi @HunaidHanfee-MSFT , 
My question is , who send data to the callbakc URI which i configured ?  is it `Teams client` installed on my labtop? or `Teams server` host by microsoft?

**Comment by HunaidHanfee-MSFT** [comment]
Reopening issue. 
We will get back to you soon.

**Comment by HunaidHanfee-MSFT** [comment]
Hello @NagleZhang,
Outgoing webhook sends notifications to external web service, this web service is your application that can receives POST request from **Teams**. 
Follow this [article](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-outgoing-webhook?tabs=urljsonpayload%2Cdotnet#create-outgoing-webhooks).
Its mentioned there as 
![image](https://user-images.githubusercontent.com/64194049/126831893-90d4dfb8-692e-4952-aad2-955c37e29c37.png)
Its just coming from **Teams**, client or server, we do not know.

When you perform a query using @mention, Microsoft Teams issues a synchronous HTTP request to your service and your code gets five seconds to respond to the message before the connection times out and terminates. 

So here we assume that there is something on your code that takes more time and hence results in error.
So we request you to check if the code or web service meets the above time condition.

Thanks

**Comment by NagleZhang** [comment]
I've tested with `curl`, and it works.

**Comment by HunaidHanfee-MSFT** [comment]
Request is getting sent from Teams services and that's the reason endpoint should be publicly accessible. Also, your endpoint URL should be HTTPS.
Can you try with [Webhook.site](https://webhook.site/) if you are getting the request from Teams.

**Comment by NagleZhang** [comment]
> Request is getting sent from Teams services and that's the reason endpoint should be publicly accessible. Also, your endpoint URL should be HTTPS.
> Can you try with [Webhook.site](https://webhook.site/) if you are getting the request from Teams.

Got it , our services is not publicly accessible. I think this is the reason. 
Thanks a lot.
