### ISSUE TITLE
JavaScript example not working for AdaptiveCards

### ISSUE THREAD

**Issue by pauljereb** [MicrosoftDocs/msteams-docs#3861]
The provided (JavaScript) example doesn't work when returning an AdaptiveCard instead of a thumbnailCard (AdaptiveCard is not rendered in Teams, error message in console).

Found that the solution is to provide a preview in the attachment:

`const adaptiveCard = CardFactory.adaptiveCard(card);
 const heroCard = CardFactory.heroCard("card title", "card text");

 const attachment = {
    contentType: adaptiveCard.contentType,
    content: adaptiveCard.content,
    preview: heroCard
}`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59bbff2e-4b80-f980-2ade-7c7a7950801e
* Version Independent ID: e837e1fd-ec0c-2d6f-b0db-b76cb2d268a4
* Content: [Link unfurling - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?tabs=dotnet)
* Content Source: [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/messaging-extensions/how-to/link-unfurling.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **anclear**

**Comment by HunaidHanfee-MSFT** [comment]
Hello @pauljereb,
Thanks for providing the code snippet to return Adaptive card I am adding tag for document enhancement.

**Comment by Wajeed-msft** [comment]
Raised PR to add this information in page. https://github.com/MicrosoftDocs/msteams-docs/pull/3876
