### ISSUE TITLE
"isSubtle" is invalid in Teams Chat, but normal in Designer.

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#3864]
Copied bug from: https://github.com/microsoft/AdaptiveCards/issues/6095 

**Details from original post:**
designer: ![image](https://user-images.githubusercontent.com/31561654/125882601-39d8aa00-a2c7-4c9b-96ba-debc26d040c2.png)
Teams Desktop App: ![image](https://user-images.githubusercontent.com/31561654/125882618-9bab3433-f074-44ed-93e4-b157ee588ec3.png)
Microsoft.Bot.Builder:Version=4.11.1.0
FYI.

Can someBody help me? Thanks!---
#### Document Details

⚠ *Do not edit this section.It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Cards reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **surbhigupta12**

**Comment by HunaidHanfee-MSFT** [comment]
Hello, 
I have tried in both Teams web and desktop client, `isSubtle` worked fine on both.
Here are the screenshots: 

- ![image](https://user-images.githubusercontent.com/64194049/126772380-9ec6ca2f-791f-4285-b43d-9c86df6b5fe7.png)
- Screenshot showing color difference using browser's developer tools:
![image](https://user-images.githubusercontent.com/64194049/126773490-4857b5e7-b4f2-479a-a806-56c272d41d10.png)

In your attached screenshot I can see the color difference as well. 
While checking on designer make sure to change "_Select host app_" to **Microsoft Teams**
![image](https://user-images.githubusercontent.com/64194049/126774297-799a18b8-9024-45ef-937e-cf39810a2484.png)

I find that color is little different on Teams than designer but `isSubtle` is working.

Thanks
Hunaid
