### ISSUE TITLE
Meeting chat with (no title)

### ISSUE THREAD

**Issue by jiteshbutala** [MicrosoftDocs/msteams-docs#3865]
Here are the steps to recreate it -

- Let O be the originator / organizer of the meeting.
- Let P1 and P2 be the people invited to the meeting and they have accepted it.
- Options with results -
        - Either P1 or P2 starts the conversation in Teams before the meeting / call starts --> (no title)
        - O starts the conversation in Teams before the meeting / call starts --> correct title
        - Anyone starts conversation in Teams after the meeting / call starts --> correct title

Hence, issue seems only when someone other than originator starts the conversation before the meeting / call starts. We have tested these scenarios in some sample meetings and it is consistent.

**Comment by Prasad-MSFT** [comment]
Hi @jiteshbutala ,
We tried to repro the steps mentioned by you above. But everything is working fine at our end(tested the scenarios few times).
If any attendee (Other than originator) tried to start a conversation before start of meeting, he/she is able to get the Title.

Thanks!

**Comment by Prasad-MSFT** [comment]
Hey @jiteshbutala 

Could you please provide more details on this? It will be better if you add some screenshots, so that we can take a look again.

Thanks !

**Comment by jiteshbutala** [comment]
Here are some screenshots -
1. See the multiple instances of (no title) -
![screenshot1](https://user-images.githubusercontent.com/18435930/127836861-85f60ce9-1edf-4d00-a7c7-9a40594000ef.png)

2. Please check that the organizer has setup the title correctly, but it does not reflect in the chat -
![screenshot2](https://user-images.githubusercontent.com/18435930/127836872-d37e9ac8-5e15-400b-b236-ec192948cec5.png)

As I wrote earlier, this issue is seen when we follow the mentioed steps. It is appearing quite frequently in the last month or so.

**Comment by Prasad-MSFT** [comment]
@jiteshbutala , Could you please try to update your MS Teams to latest version and check ?

**Comment by jiteshbutala** [comment]
@Prasad-MSFT I think I am already on the latest Teams Version.
![image](https://user-images.githubusercontent.com/18435930/128299234-6a2f3bf8-d9c6-410d-aa66-bf13b4de11a1.png)

Also, check for updates gives me nothing and there are no available updates in Software Center also.

**Comment by jiteshbutala** [comment]
I tested it again (as I saw that the updated date was quite recent) and the issue does not seem to occur. Hence, closing the ticket.

Btw, this issue could be there with an older version of Teams. Unfortunately, I do not have the information of the previous version installed on my system.

Thanks @Prasad-MSFT for the help.
