### ISSUE TITLE
[Doc-Bug]Configurable Tabs - groupChat scope conflict

### ISSUE THREAD

**Issue by SubbaReddi** [MicrosoftDocs/msteams-docs#3868]
Hi Team,
Reference: https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema#configurabletabs
Based on below, only Teams scope is allowed
![image](https://user-images.githubusercontent.com/69682598/126778810-7e6f3915-e2c7-4b3c-a261-303845236927.png)

But based on below, group chat is also allowed.
![image](https://user-images.githubusercontent.com/69682598/126778908-62e37432-166c-4c85-8ecc-9c605d995273.png)

As both statements are contradicting, Can you correct it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f94a488-d636-92b3-21eb-c88744c8f272
* Version Independent ID: 7b3413f4-9ade-accf-5cb2-83fead11a32a
* Content: [Manifest schema reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema#configurabletabs)
* Content Source: [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/resources/schema/manifest-schema.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Prasad-MSFT** [comment]
@SubbaReddi 

Thanks for reporting this. The documentation team will look into it.
