### ISSUE TITLE
How to troubleshoot Bot in the Tutorial

### ISSUE THREAD

**Issue by Coder-Kev** [MicrosoftDocs/msteams-docs#3871]
Regarding the MS Team Development Hello World via Node JS Tutorial.  I succeeded in configuring and testing the Tab, however, had issues with the Bot.
Neither the @ mention or the ... conversation worked for me.  @ mention does not find my Bot Name and .. conversation I get the general message "Something went wrong".

The Tutorial does not give any guidance on what to do if the Tests don't work.  So would help to know how to troubleshoot this point.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33cdb816-f2b6-31a4-0e4c-d730435d0a6b
* Version Independent ID: c111eaef-ac66-e245-b2bc-623c1801a7db
* Content: [Tutorial - Create your first app using Node.js - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/get-started/get-started-nodejs-app-studio?tabs=AS#bots)
* Content Source: [msteams-platform/get-started/get-started-nodejs-app-studio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/get-started/get-started-nodejs-app-studio.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Prithvi-MSFT** [comment]
Hi, you can refer below link to debug your bot using ngrok.
https://docs.microsoft.com/en-us/azure/bot-service/bot-service-debug-channel-ngrok?view=azure-bot-service-4.0

**Comment by v-chetsh** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.
