### ISSUE TITLE
Video format and dimensions for App Preview page on Teams Store.

### ISSUE THREAD

**Issue by moirf** [MicrosoftDocs/msteams-docs#3872]
App description page - what video formats and resolution should be use while creating the video?
I see for the screen shots its clear recommendation about size and formats, but none for videos, can you please help?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3df9a819-4eb0-e650-ef6b-5eeaa265c317
* Version Independent ID: ed71ed64-970d-7820-4229-c1e6896a8896
* Content: [Prepare your store submission - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist)
* Content Source: [msteams-platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist.md)
* Product: **msteams**
* GitHub Login: @heath-hamilton
* Microsoft Alias: **surbhigupta**

**Comment by v-abirade** [comment]
Hi @ramendhe,

Please provide an update on this. My team member Deborah has been trying to get in touch with you since last week. We need to close the bug asap.

**Comment by ramendhe** [comment]
Partner is expected to add url for video (YouTube or Vimeo only). Recommended length is 60-90 sec.
Video should communicate the value of the product in narrative form and/or demonstrate how the product works.
![image](https://user-images.githubusercontent.com/78354231/130610417-58336c6e-13ec-457a-869d-863919c53bd5.png)
