### ISSUE TITLE
last update is off by 3 years

### ISSUE THREAD

**Issue by DanStevensonMSFT** [MicrosoftDocs/msteams-docs#3873]
I believe this document contains updated information on adaptive cards e.g. type-ahead, masking, full width. Maybe ping Ojasvi for info. submitted by dansteve@teams

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 001a12ea-30fa-d626-18a9-02a518bfb37f
* Version Independent ID: e5f5f69e-66e9-d1b2-e19a-485d0ffcd6fa
* Content: [Text formatting in cards - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?tabs=adaptive-md%2Cconnector-html)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-format.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-format.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by HunaidHanfee-MSFT** [comment]
Hello @DanStevensonMSFT,
I can see in history that its been updated recently. 
Thanks.

**Comment by HunaidHanfee-MSFT** [comment]
Hey @DanStevensonMSFT,
I didn't understand the issue. Can you please explain?

Thanks

**Comment by HunaidHanfee-MSFT** [comment]
Hey thanks for pointing out. 
![image](https://user-images.githubusercontent.com/64194049/128137146-b2027ee1-2020-4416-bd71-68f290896b96.png)

Assigning to doc team.
