### ISSUE TITLE
Clarify documentation on implicit grant (not required for SSO)

### ISSUE THREAD

**Issue by aosolis** [MicrosoftDocs/msteams-docs#3874]
> Navigate to Authentication.
> 
> If an app has not been granted IT admin consent, users have to provide consent the first time they use an app.
> 
> To enter a redirect URI:
> 
> Select Add a platform.
> Select web.
> Enter the redirect URI for your app. This is the page where a successful implicit grant flow redirects the user. This is the same fully qualified domain name that you entered in step 5 followed by the API route where an authentication response is sent. If you are following any of the Teams samples, this is https://subdomain.example.com/auth-end.
> Enable implicit grant by checking the following boxes: ✔ ID Token ✔ Access Token

This section in the documentation could be clearer-- can be be read to mean that implicit grant is required for tab SSO, but it is not. We should rephrase this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52221dd3-95ec-96b9-1da8-9478527c2602
* Version Independent ID: 32e9c2d8-733d-0865-2ea3-727d8684a10d
* Content: [Single sign-on support for tabs - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-aad-sso)
* Content Source: [msteams-platform/tabs/how-to/authentication/auth-aad-sso.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tabs/how-to/authentication/auth-aad-sso.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by HunaidHanfee-MSFT** [comment]
Thanks for the bringing out. Assigning to documentation team.

**Comment by HunaidHanfee-MSFT** [comment]
Issue will get closed once PR is resolved.
