### ISSUE TITLE
Would you like to include ESLint support

### ISSUE THREAD

**Issue by bkakadiya** [MicrosoftDocs/msteams-docs#3879]
Hello

There was a question asked in step "yo teams"  (about ESLint) before Azure Application Insights for telemetry which is not documented.

? Would you like personal apps to be rendered without a tab header-bar? No
? Would you like to include Test framework and initial tests? No
**? Would you like to include ESLint support No**
? Would you like to use Azure Applications Insights for telemetry? No

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61f5ca59-ab3e-b7ef-d3bc-55a88a362abf
* Version Independent ID: 6d43a761-19e0-541e-ba06-170099411ac1
* Content: [Create a personal tab - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?tabs=nodejs)
* Content Source: [msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tabs/how-to/create-personal-tab.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by HunaidHanfee-MSFT** [comment]
@bkakadiya, Thanks for the pointing it out. 
We will update the doc as:
**Would you like to include ESLint support? (y/N)**
Choose **not** to include Azure AD Single-Sign-On support for the tab. The default is yes, enter **n**.
