### ISSUE TITLE
newest manifest version? 

### ISSUE THREAD

**Issue by liangchr** [MicrosoftDocs/msteams-docs#3884]
Hi-- my app got rejected from app store submission on the grounds that it was "manifestVersion": "1.5" 

I was told to upgrade to the newest version. app studio generated a 1.9 for me but I see 1.10 is the newest according to: 
https://github.com/OfficeDev/microsoft-teams-app-schema/releases

Which am I supposed to use?

**Comment by HunaidHanfee-MSFT** [comment]
Hello,
Please go ahead and use v1.10.
Let us know if you face any issues.
Thanks
