### ISSUE TITLE
manifest error?!

### ISSUE THREAD

**Issue by liangchr** [MicrosoftDocs/msteams-docs#3885]
trying to update manifest ver from 1.5 to 1.9

I get this error when I sideload my app: 
<img width="1039" alt="Screen Shot 2021-07-27 at 5 08 01 PM" src="https://user-images.githubusercontent.com/10538763/127243094-b7084db8-2703-4de8-a5f5-8ccadc56a72c.png">

It doesn't like my composeExtension configuration. It only goes away when I add these useless/junk params. What is up with that? 

Before (not working):
<img width="429" alt="Screen Shot 2021-07-27 at 5 12 42 PM" src="https://user-images.githubusercontent.com/10538763/127243371-28cda7d6-d314-4ca7-a19f-e1c79658e57c.png">

After (working but with junk parameters): 
<img width="446" alt="Screen Shot 2021-07-27 at 5 12 29 PM" src="https://user-images.githubusercontent.com/10538763/127243524-4068fec0-1988-473f-930c-a1cfa17c5a85.png">

**Comment by Prasad-MSFT** [comment]
@liangchr 

Based on error, the issue seems like related to bot.
Could you please share your manifest ?

**Comment by liangchr** [comment]
@Prasad-MSFT Issue is not coming up anymore. Not sure why. Appreciate the help/reply!
