### ISSUE TITLE
Messaging extension action bot cannot access reference attachments

### ISSUE THREAD

**Issue by harald-thoenig** [MicrosoftDocs/msteams-docs#3887]
Hi there,
I am working on a messaging extension action bot. If I receive a message with an attachment in a teams chat I like to save it to another storage. I'm using c# .NET Core with the Botframework. I am using the OnTeamsMessagingExtensionSubmitActionAsync overload function.

I can access the attachment with following code and can get the ContentUrl:

foreach (var file in action.MessagePayload.Attachments)
{
  var url = file.ContentUrl;
}
The ContentType property of the attachment is "reference".
The Content property is null.

I tried to download the file like this:

using (HttpClient httpClient = new HttpClient())
{
httpClient.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", tokenResponse.Token);
var responseMessage = await httpClient.GetAsync(file.ContentUrl);
var contentLenghtBytes = responseMessage.Content.Headers.ContentLength;
if (responseMessage.StatusCode == System.Net.HttpStatusCode.OK)
{
Stream attachmentStream = await responseMessage.Content.ReadAsStreamAsync();
attachmentStream.Position = 0;
}
}

But I the responseMessage.StatusCode is always "Unauthorized". Is there another way to download this attachments?

**Comment by Prithvi-MSFT** [comment]
Hi, we are looking into this issue and will get back to you

**Comment by Prithvi-MSFT** [comment]
Hi can you share details on how are you accessing the attachments in messaging extension ? Are you trying to save attachments by sending them first in chat ?

**Comment by harald-thoenig** [comment]
Hi, I get a message from someone. In this message is text an two attachment (pdf and docx). An this two attachments I like to archive with the Archiv function.
![PrintScreen](https://user-images.githubusercontent.com/74297174/129191273-3c5237ab-e44a-4b3e-9dd7-664e7766d278.png)
