### ISSUE TITLE
Azure(Bot Web App) + Manifest file

### ISSUE THREAD

**Issue by alefcarlos** [MicrosoftDocs/msteams-docs#389]
I could not find informations about the manifest file's behaviour when a bot is published in Azure using Bot Web App template.
Does the manifest file work without an uploadable app package ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 087ab52e-fa36-8255-1438-957f895ba583
* Version Independent ID: f19cdd18-9aef-2bb2-6c2f-e0f0f79b9ca0
* Content: [Create a bot - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/bots/bots-create)
* Content Source: [msteams-platform/concepts/bots/bots-create.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/bots/bots-create.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Wajeed-msft** [comment]
@alefcarlos - Publishing methods do not change the way you create manifest file. Microsoft Teams app manifest just need Bot Id to be present in bots section. You can use [App Studio](https://docs.microsoft.com/en-us/microsoftteams/platform/get-started/get-started-app-studio) to create your app manifest.

Please let us know if you need any help.

**Comment by alefcarlos** [comment]
@wajeed-msft, I see. I created the file, commited it(I'm using continuous integration), but it has not affected the bot behaviour. I changed the bot name, description and these information has not updated in msteams chat. I installed msteams-build npm packet.

**Comment by Wajeed-msft** [comment]
@alefcarlos - The bot details are cached per user. Any new user would see updated details. Could you please sign out and sign in from Microsoft Teams client to see updated changes?

**Comment by Wajeed-msft** [comment]
Could you please confirm if you Bot icon is set in Azure portal? If yes, please share the icon file.
![image](https://user-images.githubusercontent.com/31851992/50513122-bc8c8a80-0abb-11e9-9693-1f125b700ac0.png)

**Comment by alefcarlos** [comment]
No, it is not.

I have followed the [msteams-samples-hello-world](https://github.com/OfficeDev/msteams-samples-hello-world-nodejs/tree/master/src) repo. Crated a static folder and put the icons in it.

Wich one has the priority: Azure Settings or manifest file ? Do I need to change the name, description, icon in both of them ?

**Comment by Wajeed-msft** [comment]
@alefcarlos - For sideloaded bots, bot details are fetched from Azure settings. Once you publish the app to Global Store, bot settings are fetched from manifest file.
