### ISSUE TITLE
Get context by inserting URL placeholder values missing meetingID

### ISSUE THREAD

**Issue by juanmicrosoft** [MicrosoftDocs/msteams-docs#3890]
In the section Get context by inserting URL placeholder values, we should include meetingID. It is supported but not included in the list within that section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8dfa1a29-bcf4-0cc5-ae3a-b185a00fd7bc
* Version Independent ID: c68181e1-151b-fc78-2671-fe9b397b702e
* Content: [Get context for your tab - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/access-teams-context)
* Content Source: [msteams-platform/tabs/how-to/access-teams-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tabs/how-to/access-teams-context.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Prithvi-MSFT** [comment]
Hi, As per the documentation the section contains only the common placeholder's and not all placeholders are included. A list of all applicable placeholders is mentioned in later part of the document

**Comment by v-chetsh** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.
