### ISSUE TITLE
Recording time is misleading when record is started in between the ongoing meeting

### ISSUE THREAD

**Issue by srgiri** [MicrosoftDocs/msteams-docs#3894]
In Teams meeting, let's say meeting started at 10:00 am and at 10:15 am recording is started. The recording time on top left corner shows as:
currentTime - meetingStartTime.
This is misleading and we think whether recording started from the beginning of meeting which may not be intended always.
When recording is completed, it is noticed that recoding is actually started when 'record' button is clicked (10:15 am in my above example).

The issue here is recording time and total meeting time may not be same always. So if recording start time is ahead of meeting start time, then some meaningful information can be shown. Like recording time: xx:xx and Meeting time: yy:yy

**Comment by HunaidHanfee-MSFT** [comment]
Thank you for bringing this. I have added product team tag.
