### ISSUE TITLE
Unable to Cancel after 'start call' fails (from a deeplink in the Teams client)

### ISSUE THREAD

**Issue by FHeemskerk** [MicrosoftDocs/msteams-docs#3899]
When starting a new call using a deeplink* in the desktop client, the client shows an overlay and modal "Start call?" (see screenshot). The cancel button for that modal is not responding. This is an issue, as it renders the client unusable, because over the overlay.
![image](https://user-images.githubusercontent.com/16295028/127844930-890e92e7-c333-43d8-b082-d27acad958ab.png)
(the screenshot shows im already in a call, but this also happens if not)

*Using a deeplink to start a call `microsoftTeams.executeDeepLink("https://teams.microsoft.com/l/call/0/0?users=4:" + encodeURIComponent(pstn));` does work in the web app, but fails in the teams client (for me at least). This is unrelated to this bug, but any info would be appreciated.

**Comment by HunaidHanfee-MSFT** [comment]
Kindly check console for errors. We are checking at our end as well and will update you.

**Comment by FHeemskerk** [comment]
@HunaidHanfee-MSFT this only is an issue in the teams desktop client and only from a deeplink. Can you give directions on how to display the console for the desktop client? thanks

**Comment by HunaidHanfee-MSFT** [comment]
If that is the case let us check at our end we will let you know the updates. 
For your second query internal BUG is already raised for call deeplink different behavior across different client. We will let you know updates.

**Comment by HunaidHanfee-MSFT** [comment]
Hello,
I cannot repro the cancel button issue at our end. 
I used this URL `https://teams.microsoft.com/l/call/0/0?users=user@example.com` and open it in Teams Desktop client.
Can you please confirm few things:
1. How are you executing the deeplink?
2. Is it happening every time and ?
3. Is it happening for other user also when they are trying to call someone using deeplink?

**Comment by FHeemskerk** [comment]
1. ` startCall(pstn) {
        microsoftTeams.executeDeepLink("https://teams.microsoft.com/l/call/0/0?users=4:" + encodeURIComponent(pstn));
    }`
(tried with and without encodeURIComponent() and email address instead of pstn)
2. Yes
3. I tried with 2 colleagues and both have it (so 3 different client, but from the same tenant at least)

**Comment by FHeemskerk** [comment]
You have Microsoft Teams Version 1.4.00.19572 (64-bit). It was last updated on 03/08/2021.

**Comment by FHeemskerk** [comment]
Oh, the call is done from a message extension pane
![image](https://user-images.githubusercontent.com/16295028/128031462-04352940-e9eb-40bb-95cf-0f4caab50fcf.png)
and from devtools (Developer preview) I see no errors in console or anything (at least, not for the cancel button)

**Comment by HunaidHanfee-MSFT** [comment]
Hey,
Thanks for the quick update let me confirm this with internal team.

**Comment by FHeemskerk** [comment]
Thanks. 
Some more info (I did some more testing), it does seem to be related to starting it from a messaging extension pane. I created a simple bot tab and from there, no issues (calling and cancel button working both)
However, the deeplink to a chat does work from there (the messaging extension).

**Comment by HunaidHanfee-MSFT** [comment]
Is the issue resolved for you?

**Comment by FHeemskerk** [comment]
No...

**Comment by HunaidHanfee-MSFT** [comment]
Thanks for updating. Internal investigation is ongoing, I will keep you updated.

**Comment by HunaidHanfee-MSFT** [comment]
Hey @FHeemskerk, I added one messaging extension action in manifest and render a custom view when invoked: 
![image](https://user-images.githubusercontent.com/64194049/128847309-5c86cf0f-6c3b-4b94-8516-ca0229199949.png)
Clicking on the button, _[executeDeepLink](https://docs.microsoft.com/en-us/javascript/api/@microsoft/teams-js/microsoftteams?view=msteams-client-js-latest#executeDeepLink_string___status__boolean__reason___string_____void_)_. 
Are you also facing the error as shown in image or just cancel button not working issue?
![image](https://user-images.githubusercontent.com/64194049/128847909-a9cbe570-07fa-4c23-8a6e-d4a760580ca4.png)

**Comment by FHeemskerk** [comment]
Hi, No i do get the start call modal as shown in the original post. So that part is different. 
From the modal i am unable to actually start a call (“Sorry, we couldn’t connect you” after clicking "start call"-button) AND the Cancel button does not respond.

**Comment by HunaidHanfee-MSFT** [comment]
Check [DevTools for Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/developer-tools) see if you get any errors.

**Comment by FHeemskerk** [comment]
Hi,
Already did so (and from devtools (Developer preview) I see no errors in console or anything (at least, not for the cancel button))
the 2 messages appear from before the modal. When clicking cancel, nothing happens
![image](https://user-images.githubusercontent.com/16295028/128880641-07bffda0-86ab-4461-8e07-90b772d37a5a.png)
When clicking start call
![image](https://user-images.githubusercontent.com/16295028/128880792-fe3b6be6-ab55-4efd-b17e-61d3208ef0de.png)

**Comment by HunaidHanfee-MSFT** [comment]
We have created a bug for this. We will keep you updated.

**Comment by FHeemskerk** [comment]
@HunaidHanfee-MSFT any news on this?

**Comment by HunaidHanfee-MSFT** [comment]
Internal team is looking into it. I don't have ETA to share but I will update you when it is fixed or if I get some information.
I am closing this issue and I will update on this same thread about any update I got.

Thanks.

**Comment by HunaidHanfee-MSFT** [comment]
@FHeemskerk - Can you confirm that it is working fine? I have tried and I am no longer able to repro it.
