### ISSUE TITLE
Starting personal conversations behave unexpectedly

### ISSUE THREAD

**Issue by baole** [MicrosoftDocs/msteams-docs#390]
I tried to start a conversation with all team members. Whilst it works perfectly with two other users, it returns below error code for my own user Id
```{"error":{"code":"ServiceError","message":"You do not have sufficient privileges to execute this operation."}}```

I'm an owner of the team. One of success user is also an owner. The other is normal user.

All three requests used the same token and only the user Id (inside members tag) was different. Do you have any idea?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba8d3979-14f5-3105-ad89-ce6f98d11df1
* Version Independent ID: e53a7d1e-0e70-ca30-9809-fda7ebe5f4da
* Content: [Proactive messages - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/bots/bot-conversations/bots-conv-proactive)
* Content Source: [msteams-platform/concepts/bots/bot-conversations/bots-conv-proactive.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/bots/bot-conversations/bots-conv-proactive.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Wajeed-msft** [comment]
@baole - Are you still facing this issue? Is bot installed for all these users which you are trying to send proactive message?
