### ISSUE TITLE
Don't work Deep linking to an audio or audio-video call parameter `withvideo`.

### ISSUE THREAD

**Issue by 1411381** [MicrosoftDocs/msteams-docs#3900]
When using the following url.
ex ) https://teams.microsoft.com/l/call/0/0?users=joe@contoso.com&withvideo=true

The camera will be turned off by default regardless of whether the parameter is true or false.
I have seen this happen on both win and mac.

**Comment by Prasad-MSFT** [comment]
Hi @1411381 
We are checking this issue internally. We will get back to you shortly
Thanks !

**Comment by Prasad-MSFT** [comment]
Hi @1411381 
Could you please try to change the deeplink url as below:

https://teams.microsoft.com/l/call/0/0?users=joe@contoso.com&withVideo=true

We tried this and the camera got turned on automatically. 

Thanks !

**Comment by 1411381** [comment]
Hi @Prasad-MSFT 
Thanks.
I was able to confirm that the camera switching parameters are enabled using the above method.
