### ISSUE TITLE
Edited message is not notified

### ISSUE THREAD

**Issue by baole** [MicrosoftDocs/msteams-docs#391]
Bot receives callback event when a personal message is sent to it. However, when a message is edited,  it's not notified. Is that intended behaviour?

**Comment by Wajeed-msft** [comment]
@baole - This is by design. Bot only receive notification for the first time. Please have a look at all the [events received by Bot](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/bots/bots-notifications).

Could you please elaborate your scenario?

**Comment by baole** [comment]
Thank @Wajeed-msft. We are building a stand-up bot in which the bot asks users in a team a few questions, and gather answers  from all users. Once every users submit their answers (or time up), the bot will send a summary to the team's channel. It's a kind of daily team update. User may update their answer (before the summary is sent to the team channel). 

I also noticed that message with attachment (ex. code snippet, image) is notified the bot, however, the event payload is not included a full attachment.

**Comment by Wajeed-msft** [comment]
Once user answers all the questions, you could post back card with provided details back to user. You could have edit button which could open [Task Module](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/task-modules/task-modules-overview) with all the values pre-populated.
