### ISSUE TITLE
typo in sentence - Rignt now groupchat is limited to developer preview, 

### ISSUE THREAD

**Issue by kencollinsCDW** [MicrosoftDocs/msteams-docs#392]
Rignt (Right) now groupchat is limited to developer preview, 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d266eb0-2a29-db56-aeaf-dd14dfcdbe66
* Version Independent ID: d7a1fa1d-c083-9232-2259-4f8b267c7ee3
* Content: [Send and receive messages with a bot - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/bots/bot-conversations/bots-conversations)
* Content Source: [msteams-platform/concepts/bots/bot-conversations/bots-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/bots/bot-conversations/bots-conversations.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by clearab** [comment]
Thanks for letting us know; PR created to fix the typo.
