### ISSUE TITLE
Deep linking to an audio or audio-video call parameter 'withvideo' doesn't open the camera

### ISSUE THREAD

**Issue by AbhijeetThakur-msft** [MicrosoftDocs/msteams-docs#3921]
Make an audio and video call with withvideo = true doesn't work as in the docs. However if we rename it to withVideo = true, i.e. change the casing, it works fine.

[Link to section](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links#deep-linking-to-an-audio-or-audio-video-call)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45541337-ecd7-5cf6-cbe4-3f0d2f39aa79
* Version Independent ID: 6b4203f0-2844-06c9-eaa3-9cc03e6f76c0
* Content: [Create deep links - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links)
* Content Source: [msteams-platform/concepts/build-and-test/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/build-and-test/deep-links.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Prasad-MSFT** [comment]
Need to rename withvideo = true to withVideo = true, i.e. change the casing in deeplink urls.

Raising doc bug
Thanks!

**Comment by v-sreekesh** [comment]
Hi i have made a pull request and changed withvideo = true to withVideo = true in the deep-links.md could you review and let me know if any further changes are required

**Comment by Prasad-MSFT** [comment]
Hi @v-sreekesh ,
I reviewed your raised PR (Which is still open), and everything seems to be alright.
Thanks !

**Comment by v-sreekesh** [comment]
Thank you is there something I should do in my end further for pull request

**Comment by v-abirade** [comment]
Hi @Prasad-MSFT,

Could you please share the PR number here, as it is not linked. We can link the PR and the close the same.

**Comment by Prasad-MSFT** [comment]
https://github.com/MicrosoftDocs/msteams-docs/pull/3930

**Comment by v-abirade** [comment]
Thank you so much. Closed with PR 3930.
