### ISSUE TITLE
People Picker should not come under device capabilities.

### ISSUE THREAD

**Issue by AbhijeetThakur-msft** [MicrosoftDocs/msteams-docs#3922]
A quick feedback, I think that the People Picker component should not come under Device capabilities.
Request some thoughts on the same.

[Integrate People Picker](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/people-picker-capability#advantages-of-integrating-people-picker-capability)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45541337-ecd7-5cf6-cbe4-3f0d2f39aa79
* Version Independent ID: 6b4203f0-2844-06c9-eaa3-9cc03e6f76c0
* Content: [Create deep links - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links)
* Content Source: [msteams-platform/concepts/build-and-test/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/build-and-test/deep-links.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by v-chetsh** [comment]
This bug is related to docs so redirected to docs-enhancement team.
