### ISSUE TITLE
[Feature Request] Accessibility Issue

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#3925]
Copied bug from: https://github.com/microsoft/AdaptiveCards/issues/6085 

**Details from original post:**
I am using adaptive cards in my Team's chatbot. When I tried to use "Immersive Read" option that Team's messages having, it didn't read what content that card is having.

Where as its working fine without any adaptive card. So, can you implement accessibility capability for adaptive cards so that it can be used in Teams or Web chat.---
#### Document Details

⚠ *Do not edit this section.It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Cards reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **surbhigupta12**

**Comment by Prithvi-MSFT** [comment]
Hi, you can raise your feature request here.
https://microsoftteams.uservoice.com/

**Comment by v-chetsh** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.
