### ISSUE TITLE
Teams Messaging Chat is changing Shake emoticon to Sad emoticon, when other person replies on sent message thread.

### ISSUE THREAD

**Issue by parul001** [MicrosoftDocs/msteams-docs#3927]
**Problem Statement:**
Teams Messaging Chat is changing Shake emoticon to Sad emoticon, when other person replies on sent message thread.

**Environment**
Teams Version(copied from About Window) : You have Microsoft Teams Version 1.4.00.20364 (64-bit). It was last updated on 02-08-2021.

**Priority**
Major

**Steps To Reproduce:**
1. Login with valid credentials as Person A.
2. Go to teams chat and compose a message containing text with Shake emoticon and send it to other person alias as B.

**Actual Result:**
When this person B replies on message sent by person A, Shake emoticon gets changed to Sad emoticon.

**Expected Result:**
Emoticon should not get changed even when other person is replies on same message thread, for more insights, please refer to screenshot

**Screenshot **
<img width="827" alt="bugScreenshot" src="https://user-images.githubusercontent.com/20571722/128544038-f67aa750-c73f-4ae5-be01-82b2e05f2f8b.png">

**Comment by v-chetsh** [comment]
@parul001 - I am also able to repro this issue.
We will check internally and raise a bug for it, if needed.

**Comment by parul001** [comment]
@v-chetsh  Can I know why this issue is closed?. I mean if its reproducible or you need more logs or something else?

**Comment by p00j4** [comment]
@v-chetsh I faced the same bug. What could be the right place to get this bug fixed. Because clearly, turning my expression of "sadness" to the expression of "joy" is not comfortable, specially if i'm empathizing with my grieving friend. 
The links mentioned by the msfbbot are for asking questions or developing apps. However, I aim to address this with the best intent. Could you please help it get checked. Happy to provide more details to reproduce and experience the pain points.

**Comment by parul001** [comment]
@msftbot
Apologies that it's the wrong place. Sure thing. I'm not going to report it again, though. And yeah, I realize I'm talking to a bot, @msftbot) the closing comment doesn't help me to find where to turn to either. :(

**Comment by v-chetsh** [comment]
@parul001 - We already have a internal bug raised for it but if you want to raise it from your end, you can go to "Help" in Microsoft Teams desktop client & can select "Report a problem" & provide relevant details in it.
Thanks!!
