### ISSUE TITLE
Bot rate limiting sample: Need to handle ErrorResponseException as well

### ISSUE THREAD

**Issue by heinrich-ulbricht** [MicrosoftDocs/msteams-docs#3934]
The sample "Detect transient exceptions example" is incomplete as it only checks exceptions of type `HttpOperationException`. But it also has to check for type `ErrorResponseException` which is used specifically [in the context of the Bot Framework](https://github.com/microsoft/botbuilder-dotnet/blob/d22ebaa8682f6cf0debf5c631cb3103ed1fc4e3b/libraries/Microsoft.Bot.Connector/Conversations.cs#L1290).

A complete sample could look like this:

```
  public static bool IsTransient(Exception ex)
  {
      if (ex.Message.Contains("429"))
          return true;

      HttpResponseMessageWrapper? response = null;
      if (ex is HttpOperationException httpOperationException)
      {
          response = httpOperationException.Response;
      }
      else
      if (ex is ErrorResponseException errorResponseException)
      {
          response = errorResponseException.Response;
      }
      return response != null && transientErrorStatusCodes.Contains((int)response.StatusCode);
  }
```

Note that `ErrorResponseException` is being handled here which is not the case in the original sample.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a57254c9-963d-ea1d-ecaf-dd0e7913526c
* Version Independent ID: 610c8514-bd72-46cc-75f1-991e2242019b
* Content: [Optimize your bot with rate limiting in Teams - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/rate-limit)
* Content Source: [msteams-platform/bots/how-to/rate-limit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/bots/how-to/rate-limit.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by v-sreekesh** [comment]
Hi i have requested for a pull request and modified the code to handle the exception
