### ISSUE TITLE
Deep link to a chat issue on a phone

### ISSUE THREAD

**Issue by shiweiwei114** [MicrosoftDocs/msteams-docs#394]
While testing the [Generating a deep link to a chat](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/deep-links#generating-a-deep-link-to-a-chat) by using __https://teams.microsoft.com/l/chat/0/0?users=<user1>,<user2>,...&topicName=<chat name>&message=<precanned text>__ **on a phone (on a web browser and in our mobile app)**, it will open the Teams chat/Conversation window, but the user is "**Unknown User**", not the userPrincipalName I passed. 

This deep link works fine in a PC web browser, but not in a phone browser. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a891841a-a110-d18e-25c1-fc29e7d4a5e3
* Version Independent ID: c1a11eb8-00d1-e1d2-1e9d-71d059a6478a
* Content: [Create deep links - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/deep-links#deep-linking-to-a-chat)
* Content Source: [msteams-platform/concepts/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/deep-links.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by shiweiwei114** [comment]
Screenshot:

![msteams_deeplink_bug](https://user-images.githubusercontent.com/15699535/50618606-ecb39f00-0ea8-11e9-81a7-bff88c570767.png)

**Comment by arun-msft** [comment]
@shiweiwei114 : We have checked this issue and this is working fine in our devpreview builds for Android version and IOS we need to test.

**Comment by vishalpachori25** [comment]
In iOS Link open in MS Teams but Only one parameter, it is able to parse from "users", "topicName" or "message".  Is there any other way we can open MS teams from a mobile app? 
Thanks

**Comment by vishalpachori25** [comment]
![screenshot_20190123-144437](https://user-images.githubusercontent.com/13977139/51595963-e8195e00-1f1d-11e9-8451-6237de5f5ee6.png)
On android Nexus 5 I am getting this error!

**Comment by oneday24** [comment]
I have the same error as above. I can not open chat with the user I specified on my phone. But with the same link, I can open it in Windows.

**Comment by oneday24** [comment]
> @shiweiwei114 : We have checked this issue and this is working fine in our devpreview builds for Android version and IOS we need to test.

But it is not working on builds I installed from google play.

**Comment by Wajeed-msft** [comment]
We discovered a regression on android. We are looking into this.

**Comment by Wajeed-msft** [comment]
This is fixed. Could you please try this with latest build and re-open if you still facing this issue?

**Comment by tosurbhisharma** [comment]
I am facing issue with this deeplink. In case if user already had a conversation with user...deeplink is able to open chat on mobile. But in case, if user is initiating chat for 1st time, it is not able to open chat window. It gives message as ' can't load chat'

**Comment by prashantsoni** [comment]
We are still facing the issue with the deep linking from android devices. 
The MS Teams client for iOs and Desktop works fine w.r.t. deep link.

We want to move user to the "team" side panel section in MS Teams and not to a particular team. 

Working link in desktop - msteam://team.microsoft.com/l/teams
Working link in desktop - msteam://team.microsoft.com

neither of these links works for android. The MS Teams crashes and reopens.
