### ISSUE TITLE
Scheduling graph api meeting with msg-ex invocation.

### ISSUE THREAD

**Issue by liangchr** [MicrosoftDocs/msteams-docs#3947]
When I invoke a message extension my service receives a payload. 
1.) Where on earth is the value for "*localTimezone*" being generated from? (refer to payload example at end of post). I assume it is either from the users MSTeams settings OR the user's browser settings
2.) Is there is list of all possible timezones somewhere? I suspect it is based on the IANA time zone database but I am not sure. Please help! I need an official list. 

I also need to know these things: 
3.) I need to timezone in order to use the graph api to schedule a meeting with my message extension. 
4.) I also need to know if the graph api accepts this timezone format. 
5.) If the graph api does not accept this timezone format how can I MAP the timezone values from MSTeams provided timezones to the timezone values the graph api accepts? 
6.) I also need to know how to get the timezone OFFSET in minutes for my scheduler to work so I'll need a map or method for that as well. 

Is time timezone based on: IANA time zone database possibly? https://www.iana.org/time-zones. I assume it is the same timezones returned by graph api: 
https://graph.microsoft.com/v1.0/me/outlook/supportedTimeZones(TimeZoneStandard=microsoft.graph.timeZoneStandard'Iana')

Here is an example body my service receives on message extension invocation: 
**localTimezone** is bolded: 

{ name: 'composeExtension/submitAction',
  type: 'invoke',
  timestamp: '2021-08-11T22:01:54.673Z',
  localTimestamp: '2021-08-11T15:01:54.673-07:00',
  id: 'f:f152e774-3563-36f0-d62c-f4f3cafe5ed0',
  channelId: 'msteams',
  serviceUrl: 'https://smba.trafficmanager.net/amer/',
  from:
   { id:
      'dsdsdsd',
     name: 'Banana Adams',
     aadObjectId: 'xxx-xxx-xxx' },
  conversation:
   { isGroup: true,
     conversationType: 'channel',
     tenantId: 'xxx-xxx-xxx',
     id: 'xxxx-xxxxx-xxx' },
  recipient:
   { id: 'xxx-xxxx-xxx',
     name: 'Marc Banana' },
  entities:
   [ { locale: 'en-US',
       country: 'US',
       platform: 'Web',
       timezone: 'America/Los_Angeles',
       type: 'clientInfo' } ],
  channelData:
   { channel: { id: 'xxx-xxx-xxx' },
     team: { id: 'xxx-xxx-xxx' },
     tenant: { id: 'xxx-xxx-xxx' },
     source: { name: 'compose' } },
  value:
   { commandId: 'Schedule a meeting',
     commandContext: 'compose',
     requestId: 'e0ad50674f4f469ba120d9a1dbef87d7',
     context: { theme: 'default' },
     data:
      { meetingTopic: 'Meeting about Bananas',
        date: '2021-08-19',
        time: '01:00',
        myColor: '1' } },
  **locale: 'en-US',**
  **localTimezone: 'America/Los_Angeles',**
  trackingID: 'c7e3eecc-3a7d-4cce-aff3-23937cf08916' }

**Comment by HunaidHanfee-MSFT** [comment]
We are looking into this, will get back to you soon. 
Thanks

**Comment by HunaidHanfee-MSFT** [comment]
Can you share the Graph API you are using to create meeting?

**Comment by liangchr** [comment]
@HunaidHanfee-MSFT 
POST https://graph.microsoft.com/v1.0/me/events

**Comment by HunaidHanfee-MSFT** [comment]
Hello @liangchr,
Answers to your questions:
> the value for "localTimezone" being generated from?

It is based on user's system time zone.

> Is there is list of all possible time zones somewhere? I suspect it is based on the IANA time zone database but I am not sure. Please help! I need an official list.

Here are the list.
1.  [Time zones currently supported by Windows](https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/default-time-zones)
2. [Time zones supported by the calendar API](https://docs.microsoft.com/en-us/graph/api/resources/datetimetimezone?view=graph-rest-1.0#additional-time-zones)

Although when I tried creating it with **Asian/Calcutta** instead Asia/Kolkata, it also works. So, you can use LocalTimezone values to create events.
[LocalTimezone](https://docs.microsoft.com/en-us/dotnet/api/microsoft.bot.schema.activity.localtimezone?view=botbuilder-dotnet-stable#Microsoft_Bot_Schema_Activity_LocalTimezone) is expressed in IANA Time Zone database format

> 3.) I need to timezone in order to use the graph api to schedule a meeting with my message extension.
4.) I also need to know if the graph api accepts this timezone format.
5.) If the graph api does not accept this timezone format how can I MAP the timezone values from MSTeams provided timezones to the timezone values the graph api accepts?

I tried with the LocalTimezone and didn't faced any issue. You don't need to change/map anything. You can use it right away. It worked for me.
>6.) I also need to know how to get the timezone OFFSET in minutes for my scheduler to work so I'll need a map or method for that as well

You can get it from **localTimestamp: '2021-08-11T15:01:54.673-07:00',** and write some custom code around it according to the language you are using.

> Is time timezone based on: IANA time zone database possibly? https://www.iana.org/time-zones. I assume it is the same timezones returned by graph api:
https://graph.microsoft.com/v1.0/me/outlook/supportedTimeZones(TimeZoneStandard=microsoft.graph.timeZoneStandard'Iana')

Yes!

**Comment by liangchr** [comment]
@HunaidHanfee-MSFT thanks for answering all the questions! That was phenomenally helpful/concise. Especially since the question was complicated and had multiple parts. Just four more questions if possible: 
**Let me know if I should just create a new issue for this instead of posting here:** 
More important questions
1.) what is the difference between value "data.localTimezone" and "from.entities[0].timezone" (based on the pasted payload)
2.) what is the difference between value "data.locale" and "from.entities[0].locale" (based on the pasted payload)

Less important questions: 
2.) Would there still be a way to map msft-tz-format -> IANA and vice versa if I wanted? 
3.) How would I find IANA offset JUST from an IANA time string as opposed to the timestamp string? I was hoping to let the users select from a list of IANA timezones and then grab the offset from that

**Comment by HunaidHanfee-MSFT** [comment]
> 1.) what is the difference between value "data.localTimezone" and "from.entities[0].timezone" (based on the pasted payload)
> 2.) what is the difference between value "data.locale" and "from.entities[0].locale" (based on the pasted payload)

@liangchr, So, I tested few scenario to find if there is a difference but it seems like there isn't they always come same. Also when you are saying `from.entities[0].timezone` I assume that it's `entities[0].timezone` (its not inside _from_). Same goes for locale didn't find any difference. Both timezone and locale always take value of the user who is interacting with bot.

> 3.) Would there still be a way to map msft-tz-format -> IANA and vice versa if I wanted?

You can try out - [TimeZoneConverter Class](https://docs.microsoft.com/en-us/dotnet/api/adaptiveexpressions.timezoneconverter?view=botbuilder-dotnet-stable)

>4.) How would I find IANA offset JUST from an IANA time string as opposed to the timestamp string? I was hoping to let the users select from a list of IANA timezones and then grab the offset from that

I don't think you can do that directly but it might be possible with combination of [TimeZoneConverter Class](https://docs.microsoft.com/en-us/dotnet/api/adaptiveexpressions.timezoneconverter?view=botbuilder-dotnet-stable)
and [TimeZoneInfo](https://docs.microsoft.com/en-us/dotnet/api/system.timezoneinfo?view=net-5.0). 

Good Luck for your work. **We would like your [feedback on your experience with our support team and Platform.](https://aka.ms/DevSupportFeedback)**
