### ISSUE TITLE
Tab SSO api deprecation?  [getAuthToken() Method used]

### ISSUE THREAD

**Issue by liangchr** [MicrosoftDocs/msteams-docs#3952]
My team got a bizarre email today about a deprecated api:
 
> Required action
> To avoid service disruptions, update your AppSource app before August 20, 2021, to no longer use any of the listed OAuth2 API functions. Instead, we recommend that you use this function:
> 
> `AcquireTokenByAuthorizationCode(ClientId: Text; ClientSecret: Text; OAuthAuthorityUrl: Text; RedirectURL: Text; Scopes: List of [Text]; PromptInteraction: Enum "Prompt Interaction"; var AccessToken: Text; var AuthCodeErr: Text)`

I want to know if my service that utilizes the tab SSO will be affected by this deprecation at all we use client sdk version: **v1.6.0** or https://statics.teams.cdn.office.net/sdk/**v1.6.0**/js/MicrosoftTeams.min.js

We use the method: getAuthToken() listed here: https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/using-teams-client-sdk

Please let us know!

**Comment by Prithvi-MSFT** [comment]
Hi, nothing was mentioned in official documents regarding the changes affecting SSO authentication using getAuthToken() method.
https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/using-teams-client-sdk

We also searched in latest sdk repo but nothing was mentioned for getAuthToken() method.
https://github.com/OfficeDev/microsoft-teams-library-js/releases/tag/1.10.0

Thanks

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, please feel free to reopen it, if required.
