### ISSUE TITLE
[Android] Image default click event is triggered 

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#3953]
Copied bug from: https://github.com/microsoft/AdaptiveCards/issues/5967 

**Details from original post:**
# Target Platform

Android
# Target Application

Teams
# Problem Description
We have a simple card with json like this:
```
{
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "type": "AdaptiveCard",
    "version": "1.2",
    "body": [
        {
            "type": "TextBlock",
            "size": "Medium",
            "weight": "Bolder",
            "maxLines": 2,
            "text": "test",
            "width": "auto",
            "wrap": true
        },
        {
            "type": "Image",
            "url": "https://contososcubademo.azurewebsites.net/assets/chicken.jpg",
            "size": "Large"
        },
        {
            "type": "RichTextBlock",
            "inlines": [
                {
                    "type": "TextRun",
                    "text": "# ",
                    "size": "Small"
                },
                {
                    "type": "TextRun",
                    "text": "test",
                    "size": "Medium"
                }
            ]
        },
        {
            "spacing": "Medium",
            "type": "ActionSet",
            "actions": [
                {
                    "type": "Action.OpenUrl",
                    "title": "View details",
                    "url": "https://adaptivecards.io"
                }
            ]
        }
    ],
    "selectAction": {
        "type": "Action.OpenUrl",
        "url": "https://adaptivecards.io"
    }
}
```
We expect when user tap the card or button, it will open the url, but on Android, when user tap on the image, it will open the image viewer instead of opening url.

# Screenshot
We have a video here:
https://user-images.githubusercontent.com/3711046/120928999-cbaaa480-c719-11eb-9b98-3183bfb51452.mp4
---
#### Document Details

⚠ *Do not edit this section.It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Cards reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **surbhigupta12**

**Comment by HunaidHanfee-MSFT** [comment]
Hello,
We are able to repro this issue. Will get back to you soon.

Thanks.

**Comment by HunaidHanfee-MSFT** [comment]
We have raised a bug. We can't share ETA but I will let you know once it is fixed.

**Comment by Prasad-MSFT** [comment]
@zsybupt, The issue has already been fixed and rolled out. Thanks.

**Comment by v-chetsh** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.
