### ISSUE TITLE
Initiate actions with messaging extensions still exists ?

### ISSUE THREAD

**Issue by jcferelloc** [MicrosoftDocs/msteams-docs#396]
According to Microsoft Documentation it is possible to initiate actions with messaging extensions 
see https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/messaging-extensions/create-extensions

To do so, (copy of sample below) the command must specify the "type" parameter with value "Action"

	"composeExtensions": [
		{
		"botId": "......",
		"canUpdateConfiguration": true,
		"commands": [
			{
			  "id": "reassignTodo",
			  "description": "Reassign a todo item",
			  "title": "Create To Do",
			  "type": "Action",
			  "fetchTask": true
			}
		]
	]
		
But according to manifest.json reference schema the "type" property doesn't exist !

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f94a488-d636-92b3-21eb-c88744c8f272
* Version Independent ID: 7b3413f4-9ade-accf-5cb2-83fead11a32a
* Content: [Manifest schema reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema)
* Content Source: [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/resources/schema/manifest-schema.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by pablodiazgutierrez** [comment]
I believe we are seeing the same issue, described in https://github.com/MicrosoftDocs/msteams-docs/issues/455

**Comment by billbliss** [comment]
Yes. See answer to #455.

**Comment by MaheshakaMudli** [comment]
How to we get the message while initiating action in messaging extension. I am using yeoman generator to create a teams project for messaging extension. The user will have a custom action to create a task using the messaging in the teams.
