### ISSUE TITLE
Activity object contains html of rich messages as an attachment for teams messages (undocumented)

### ISSUE THREAD

**Issue by TheBluLion** [MicrosoftDocs/msteams-docs#3960]
Specific to Teams messages, the html content of the message is included as an attachment to the Activity object, but this does not appear to be documented anywhere, causing some developer/customer confusion

**Comment by HunaidHanfee-MSFT** [comment]
So, this is what you are talking about right?
```
"attachments": [
        {
            "contentType": "text/html",
            "content": "<div>\r\n<div itemprop=\"copy-paste-block\">\n\r\n<div style=\"font-size:14px\"><strong>bold</strong></div>\n</div>\n</div>"
        }
    ],
```
I have found few documentation where maybe we can add this : 
1. [Supported text formatting in conversations - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bots-text-formats)
2. [Bot message format - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bots-message-format)
3. [Messages in bot conversations](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-messages?tabs=json)

**Comment by TheBluLion** [comment]
1.  Thank you- receive a message in this link might be a good location for this as it is not possible to pass html content on a send/message creation

Messages in bot conversations<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fmicrosoftteams%2Fplatform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-messages%3Ftabs%3Djson&data=04%7C01%7Ceunice.loh%40microsoft.com%7C7c202131a914481af38808d9770c3800%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637671716677766496%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=MbA78lbuBpIbsPtt58EffsuNw%2Bzj7ZzVvsXafX0tekk%3D&reserved=0>

Eu Nice

**Comment by HunaidHanfee-MSFT** [comment]
I have created a doc enhancement bug. Closing this issue here.
 Thanks
