### ISSUE TITLE
[Authoring] Most of the container styles are not display in Microsoft Teams Windows Latest Version 1.4.00.19572 (64-bit)

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#3968]
Copied bug from: https://github.com/microsoft/AdaptiveCards/issues/6178 

**Details from original post:**
# Target Application

Microsoft Teams

# Problem Description

After updating the Teams version to Windows latest version of 1.4.00.19572, the container styles of good, warning, attention and accent are not displaying the corresponding color.

# Expected Outcome

Display the corresponding color as below:

![image](https://user-images.githubusercontent.com/3744444/128798278-a07a8511-429c-4754-a9b7-bebc2db22d72.png)

# Actual Outcome

The colors of good, warning, attention and accent are all displaying the default style:

![image](https://user-images.githubusercontent.com/3744444/128798425-d92a7d1f-dc7f-410b-813f-7acc0a581057.png)

# Repro Steps

Using the card payload in https://adaptivecards.io/designer/index.html?card=/payloads/Container.Style.json, and rendering it in Teams

# Schema Version

1.2
---
#### Document Details

⚠ *Do not edit this section.It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Cards reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **surbhigupta12**

**Comment by Prasad-MSFT** [comment]
We have raised a bug for this issue and concerned team is looking into it. We will inform you once we get any update.
Thanks!

**Comment by Prasad-MSFT** [comment]
We are closing the issue for now. Please feel free to reopen if required.
