### ISSUE TITLE
nodejs

### ISSUE THREAD

**Issue by cyberf4n** [MicrosoftDocs/msteams-docs#397]
half of the packages are deprecated

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33cdb816-f2b6-31a4-0e4c-d730435d0a6b
* Version Independent ID: c111eaef-ac66-e245-b2bc-623c1801a7db
* Content: [Get started with App Studio and Node.js - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/get-started/get-started-nodejs-app-studio)
* Content Source: [msteams-platform/get-started/get-started-nodejs-app-studio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/get-started/get-started-nodejs-app-studio.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by spjpgrd** [comment]
While it doesn't solve the deprecation issue, this helped get past some errors:  
https://github.com/nodejs/node/issues/20325#issuecomment-471716630 #
