### ISSUE TITLE
Windows desktop app bug: trying to print an office file from within Tams fails

### ISSUE THREAD

**Issue by IgnitedZ** [MicrosoftDocs/msteams-docs#3977]
This issue is 100% reproducible, and affects only the desktop app and not the Teams web app.

If you open an office file inside of Teams, say a Word file, and try to print it, you will get a blank preview and no PDF file will be generated. This used to work differently in earlier versions and the file was generated correctly.

The file still gets generated correctly on the Teams Web App, but that is an ideal environment for many.

**Comment by v-chetsh** [comment]
@IgnitedZ -  This issue is not related to Microsoft Teams App development, so redirecting it to Teams Product Team.
