### ISSUE TITLE
TaskInfo JSON example and docs wrong

### ISSUE THREAD

**Issue by Stevenic** [MicrosoftDocs/msteams-docs#3988]
The docs for `TaskInfo.card` say that your return an AdaptiveCard you want shown, which is what the JSON example shows. If you try to return an AdaptiveCard though you'll get an error. It took me about 3 hours to figure out that you actually have to return an Attachment object containing the card:

```JSON
{
   "contentType": "application/vnd.microsoft.card.adaptive",
   "content": {
       "type": "AdaptiveCard"
   }
}
```

I ended up having to dig into the C# code for the SDK to figure this out.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e04556b-f4b1-316e-bac1-ca77c6ab287f
* Version Independent ID: 2ee29289-b250-4ba3-e957-7a42122a266e
* Content: [Create and send the task module - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/action-commands/create-task-module?tabs=dotnet)
* Content Source: [msteams-platform/messaging-extensions/how-to/action-commands/create-task-module.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/messaging-extensions/how-to/action-commands/create-task-module.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **anclear**

**Comment by HunaidHanfee-MSFT** [comment]
Hello,
Can you please share the minimal code explaining what you have faced and how you were trying to do? It will help us update the doc accordingly. 
Thanks

**Comment by HunaidHanfee-MSFT** [comment]
Could you please share the snippet?
