### ISSUE TITLE
Message update not working

### ISSUE THREAD

**Issue by tvanh** [MicrosoftDocs/msteams-docs#399]
The API to update message seems not working anymore. When I tried to send the update message to server, the reply is:
{"error":{"code":"BadArgument","message":"not a known activity id"}}
I check the code. Seems the activity is flushed to client rite after the next message (from user) entered, hence the server is unable to query the previous activities.
Could someone confirm this? Or send me a working sample of updating message (prefer msteam). Bests

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d266eb0-2a29-db56-aeaf-dd14dfcdbe66
* Version Independent ID: d7a1fa1d-c083-9232-2259-4f8b267c7ee3
* Content: [Send and receive messages with a bot - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/bots/bot-conversations/bots-conversations)
* Content Source: [msteams-platform/concepts/bots/bot-conversations/bots-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/bots/bot-conversations/bots-conversations.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by billbliss** [comment]
Can you post some sample code? Hard to diagnose with what you've provided here.

**Comment by tvanh** [comment]
Can we discuss in 
https://gitter.im/azure-399-Message-update-not-working/community#
I can provide screenshot and sample there, since it invokes some private data.

**Comment by Wajeed-msft** [comment]
@tvanh - The [sample code](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/bots/bot-conversations/bots-conversations#net-example-1) to update message works fine Microsoft Teams. Did you try this code in Microsoft Teams? 
Seems like there is some issue in message update part for Bot Emulator.
