### ISSUE TITLE
The entityId documentation is incorrect

### ISSUE THREAD

**Issue by ydogandjiev** [MicrosoftDocs/msteams-docs#3999]
The description for the entityId is incorrect; the entityId should be set to a unique identifier for the content being pinned:
`
entityId: "add unique name here",
`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b94a38e-82f8-45a1-8ccc-b0a96edd0404
* Version Independent ID: 6e077924-9658-cdd2-50de-0f9561d6366b
* Content: [Create a configuration page - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/configuration-page)
* Content Source: [msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by HunaidHanfee-MSFT** [comment]
Assigning to doc team. Thanks for bringing this out.

**Comment by v-sreekesh** [comment]
Hi i have raised a PR and fixed this issue in the documentation https://github.com/MicrosoftDocs/msteams-docs/pull/4018 could you check and review
