### ISSUE TITLE
[Feature Request] Allow custom URL for Action.OpenURL

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#4001]
Copied bug from: https://github.com/microsoft/AdaptiveCards/issues/6221 

**Details from original post:**
# What is the problem you are attempting to solve with this feature?

I'm trying to build an adaptive card with a button (Action.OpenURL) to open a local software while passing some data. Using a browser one can open the software using this custom URL: _mytool://?data=123456_

I tried using this URL on an adaptive card (Action.OpenURL) but when you click the button, nothing happens.

I guess the URL somehow gets validated and if it's not a "valid" URL starting with https:// it gets replaced?

# A description of your proposed solution to the problem

Allow custom URLs for Action.OpenURL

# What alternatives or workarounds have you considered

I couldn't find any workaround since the URL always gets deleted and using HTML is not possible on adaptive cards.---
#### Document Details

⚠ *Do not edit this section.It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Cards reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **surbhigupta12**

**Comment by Meghana-MSFT** [comment]
@alondattner

We are checking this internally. We will get back to you soon.

**Comment by alondattner** [comment]
@Meghana-MSFT

Of course I could. However, I have seen that several similar issues already exist:
https://microsoftteams.uservoice.com/forums/555103-public/suggestions/35967502-custom-url-h
https://microsoftteams.uservoice.com/forums/555103-public/suggestions/17405062-custom-uri-handlers
https://microsoftteams.uservoice.com/forums/555103-public/suggestions/32991553-url-scheme

All together they have almost 600 upvotes.

**Comment by Meghana-MSFT** [comment]
For security reasons, currently custom URLs within Action.OpenURL is not supported.  A validation is performed on the Teams client prior to allowing users to open the URL and only https:// links are supported.

**Comment by Meghana-MSFT** [comment]
@alondattner 

We are closing this issue.
