### ISSUE TITLE
User photos not rendering in Teams on mobile

### ISSUE THREAD

**Issue by jameskleinschnitz** [MicrosoftDocs/msteams-docs#4003]
we are wanting to display the users photo in an adaptive card in teams but it seems that there is no consistency of how to do this between mobile and desktop. we have been using this url:

https://teams.microsoft.com/api/mt/beta/users/{userid | email}/profilepicture?displayName={name}

This works fine in the web and desktop but it does not work on mobile iOS or android.

Then we found if we include the region that the users of the application is from we can get it to work on mobile:

https://teams.microsoft.com/api/mt/{region}/beta/users/{userid | email}/profilepicture?displayName={name}

However this does NOT work on desktop.

Here is some AC json and screenshot to demonstrate, (the person took these screenshots while in the apac region):

`{
    "type": "AdaptiveCard",
    "body": [
        {
            "type": "TextBlock",
            "size": "Medium",
            "weight": "Bolder",
            "text": "No Region - profilepicturev2"
        },
        {
            "type": "Image",
            "url": "https://teams.microsoft.com/api/mt/beta/users/first.last@onmicrosoft.com/profilepicturev2?displayname=first last&voidCache=false",
            "size": "Small",
            "style": "Person"
        },
        {
            "type": "TextBlock",
            "size": "Medium",
            "weight": "Bolder",
            "text": "No Region - profilepicture"
        },
        {
            "type": "Image",
            "url": "https://teams.microsoft.com/api/mt/beta/users/first.last@onmicrosoft.com/profilepicture?displayname=first last&voidCache=false",
            "size": "Small",
            "style": "Person"
        },
        {
            "type": "TextBlock",
            "size": "Medium",
            "weight": "Bolder",
            "text": "EMEA - profilepicturev2"
        },
        {
            "type": "Image",
            "url": "https://teams.microsoft.com/api/mt/emea/beta/users/first.last@onmicrosoft.com/profilepicturev2?displayname=first last&voidCache=false",
            "size": "Small",
            "style": "Person"
        },
        {
            "type": "TextBlock",
            "size": "Medium",
            "weight": "Bolder",
            "text": "EMEA - profilepicture"
        },
        {
            "type": "Image",
            "url": "https://teams.microsoft.com/api/mt/emea/beta/users/first.last@onmicrosoft.com/profilepicture?displayName=first last",
            "size": "Small",
            "style": "Person"
        },
        {
            "type": "TextBlock",
            "size": "Medium",
            "weight": "Bolder",
            "text": "APAC - profilepicturev2"
        },
        {
            "type": "Image",
            "url": "https://teams.microsoft.com/api/mt/part/apac-02/beta/users/first.last@onmicrosoft.com/profilepicturev2?displayName=first last",
            "size": "Small",
            "style": "Person"
        },
        {
            "type": "TextBlock",
            "size": "Medium",
            "weight": "Bolder",
            "text": "APAC - profilepicture"
        },
        {
            "type": "Image",
            "url": "https://teams.microsoft.com/api/mt/part/apac-02/beta/users/first.last@onmicrosoft.com/profilepicture?displayName=first last",
            "size": "Small",
            "style": "Person"
        }
    ],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.2"
}`

![teams-web-result](https://user-images.githubusercontent.com/3209749/130152739-69a60468-ed7d-4040-91f1-690d708edab3.png)

![teams-mobile-result](https://user-images.githubusercontent.com/3209749/130152752-81284b09-e766-4fd0-beb4-7df42a21ba67.PNG)

Any help would be much appreciated.

**Comment by jameskleinschnitz** [comment]
@v-chetsh any ideas?

**Comment by HunaidHanfee-MSFT** [comment]
Hello,
We are looking into this and get back to you soon
Thanks

**Comment by HunaidHanfee-MSFT** [comment]
Could you please share any documentation/ reference where the endpoint is suggestion for getting user profile picture? 
We assume that endpoint you are currently using was obtained by observing the network traffic when Teams app load.

`https://teams.microsoft.com/api/mt/beta/users/{userid | email}/profilepicture` is not the recommended endpoint for retrieving profile picture of a given user. We recommend using **Graph APIs** for the same.

Refer : [Get photo](https://docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-1.0)
`https://graph.microsoft.com/v1.0/users/{id | userPrincipalName}/photo/$value`

**Comment by HunaidHanfee-MSFT** [comment]
Please let us know if you have any query. I am closing this as of now, feel free to re-open the issue.
