### ISSUE TITLE
Documentation is out of date (for bot framework v3 rather than for v4)

### ISSUE THREAD

**Issue by hansmbakker** [MicrosoftDocs/msteams-docs#401]
The sample code embedded on this page seems to target bot framework v3 rather than bot framework v4. A warning to users that it targets the old bot framework version is not provided.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7c810ce-b432-9135-16ee-55f461a10e78
* Version Independent ID: 70c7c1a0-b5b0-599f-a0b2-ea3e343df227
* Content: [Using the OAuthCard for authentication - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/authentication/auth-oauth-card)
* Content Source: [msteams-platform/concepts/authentication/auth-oauth-card.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/authentication/auth-oauth-card.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by clearab** [comment]
A note will be added to this article.

**Comment by hansmbakker** [comment]
Can you then also document how to authenticate in Teams with Bot framework v4?

**Comment by mplwork** [comment]
So why is this closed then? Where is the v4 doc?
