### ISSUE TITLE
Teams on Linux crashes immediately after login

### ISSUE THREAD

**Issue by mzanetti** [MicrosoftDocs/msteams-docs#4013]
It starts, opens, I can login. It shows the content for a second, then crashes and restarts. After 3 crash-loops it asks again for the login and it starts from scratch again.

Probably related to the fact that we don't have a Teams account in our organization but are invited to another organization. So during login it asks where to sign in. I select the other company, it shows the chats and stuff for a second, then the crash loop starts.

**Comment by v-chetsh** [comment]
@mzanetti - This question is not related to Microsoft Teams App development, so changing the label as "teams-product-support".

**Comment by mzanetti** [comment]
So the app exits intentionally is what you're saying?
