### ISSUE TITLE
Updating entityId

### ISSUE THREAD

**Issue by OskarNet** [MicrosoftDocs/msteams-docs#4022]
Hi

I just wonder if this description is valid as it is possible to update the entityId by using the Teams Javascript SDK to update it.
"{entityId}: The ID you supplied for the item in this tab when first configuring the tab."

Regards,
Oskar

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8dfa1a29-bcf4-0cc5-ae3a-b185a00fd7bc
* Version Independent ID: c68181e1-151b-fc78-2671-fe9b397b702e
* Content: [Get context for your tab - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/access-teams-context)
* Content Source: [msteams-platform/tabs/how-to/access-teams-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tabs/how-to/access-teams-context.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by v-chetsh** [comment]
@OskarNet -  Generally we assign the entityId to item in tab while configuring the tab.
We can update the entityId via Graph API or SDK's but we can lost the original context of item which may be saved in storage.
Also in the documentation , it is not mentioned that we can not update the entityId.

Please let me know if you still have any doubt/query.

**Comment by v-chetsh** [comment]
@OskarNet - Could you please let me know if you are still facing any issue on this.
If your issue is already resolved, Could you please close it.

**Comment by OskarNet** [comment]
Well, it would just be clearer to mention that it is possible to modify it. Like it text is now it sounds like that is not the case.

**Comment by v-chetsh** [comment]
Closing this issue for now. Please feel free to reopen this issue if you are still facing the issue.
