### ISSUE TITLE
Stage View - Loading a blank page on deeplink 

### ISSUE THREAD

**Issue by AbhijeetThakur-msft** [MicrosoftDocs/msteams-docs#4023]
Hi Team,

While working on one sample related to [Tabs link unfurling and Stage View](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/tabs-link-unfurling), we observed a blank page while using deeplink in stage view.

We corrected it and it worked in our sample [Link to sample](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/tab-stage-view)

The specific changes link are as follows:
1. csharp solution
- [Using executeDeepLink](https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/main/samples/tab-stage-view/csharp/TabInStageView/Views/Home/SampleTab.cshtml) (Refer function createLink())

   Deep link syntax:
  `"https://teams.microsoft.com/l/stage/{appId}/0?context={\"contentUrl\":\""[contentUrl]"\",\"websiteUrl\":\"" 
   [contentUrl]"\",\"name\":\"Contoso\"}";`

- [Using OpenUrl](https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/main/samples/tab-stage-view/csharp/TabInStageView/Bots/ActivityBot.cs) (Refer method GetDeeplinkForStageView())

  Deep link syntax:
 `"https://teams.microsoft.com/l/stage/{appId}/0?context=" + HttpUtility.UrlEncode("{\"contentUrl\":\"" 
  [contentUrl]"\",\"websiteUrl\":\""[contentUrl]"\",\"name\":\"Contoso\"}");`

   
2. nodejs solution
- [Using executeDeepLink](https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/main/samples/tab-stage-view/nodejs/server/views/sampleTab.ejs) (Refer function createLink())

   Deep link syntax:
   `"https://teams.microsoft.com/l/stage/"+appId+"/0?context={\"contentUrl\":\""[contentUrl]"\",\"websiteUrl\":\"" 
   [contentUrl]"\",\"name\":\"Contoso\"}";`

- [Using OpenUrl](https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/main/samples/tab-stage-view/nodejs/server/models/adaptiveCard.js) (Refer method GetDeeplinkForStageView())

   Deep link syntax:
  `"https://teams.microsoft.com/l/stage/{appId}/0? context=%7B%22contentUrl%22%3A%22[Encoded_Content_Url]"%22%2C%22websiteUrl%22%3A%22[Encoded_Content_Url]%22%2C%22name%22%3A%22Contoso%22%7D"`
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9bfa5c3-8227-c122-c4ff-a80786bc11d3
* Version Independent ID: b8a577f6-be73-14d7-3c6a-32eed5568b51
* Content: [Tabs link unfurling and Stage View - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/tabs-link-unfurling)
* Content Source: [msteams-platform/tabs/tabs-link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tabs/tabs-link-unfurling.md)
* Product: **msteams**
* GitHub Login: @Rajeshwari-v
* Microsoft Alias: **surbhigupta**

**Comment by v-sreekesh** [comment]
Hi @Prasad-MSFT i would like to work on this issue
