### ISSUE TITLE
[Doc-update] Meeting stage is currently in dev preview - But i am able to access when dev preview is off

### ISSUE THREAD

**Issue by SubbaReddi** [MicrosoftDocs/msteams-docs#4027]
Hi team,
I see following note in documentation:
![image](https://user-images.githubusercontent.com/69682598/130581453-803ae6fb-0232-4aa8-a5db-0172419a029a.png)

But i tried following scenario:
Dev preview is enabled in desktop teams client. Added tab to meeting.
Dev preview is disabled. Joined meeting and tried to share side panel tab app. And it is working fine.

So, If it is documentation gap please update the same.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62ce7ca6-3ea8-ccca-5c59-92a638303aea
* Version Independent ID: d9a2d747-41cc-add6-f281-4210e888654e
* Content: [Enable and configure your apps for Teams meetings - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings)
* Content Source: [msteams-platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Prasad-MSFT** [comment]
@SubbaReddi Thanks for bringing this to notice. 
We also tried to repro at our end and were able access the Meeting stage when dev preview is off.
