### ISSUE TITLE
MSTeams - Bot returning NotImplemented

### ISSUE THREAD

**Issue by callenskoen** [MicrosoftDocs/msteams-docs#403]
Hello,

I’m writing a bot in Azure that will be hosted in MS Teams. The bot has two AADv2 connections, one for the Microsoft Graph and one for Sharepoint Online.

When testing the signing to both oauth connection in the bot emulator they are working fine.

However, when deploying the bot in MS teams, authentication to the first oauth connection (Graph) works, the second oauth connection (Sharepoint online) doesn’t work.

I’ve used fiddler to see what is ongoing, and saw the following:

POST https://emea.ng.msg.teams.microsoft.com/v1/agents/28:8e7e6063-94a6-4989-ac8f-bf4892c57981/invoke HTT...

{"errorCode":1008,"message":"<BotError>Bot returned unsuccessful status code NotImplemented"}

Anyone any idea what might be wrong? Or is this scenario not supported ?

Thx
Koen

**Comment by arkiaconsulting** [comment]
Same here, with a Generic OAuth 2 Bot Service connection

**Comment by Wajeed-msft** [comment]
@callenskoen - Could you please share code snippet which show how _signin/verifyState_ is handled? 
Are you using [basic auth sample code](https://github.com/Microsoft/BotBuilder-V3/blob/master/Node/examples/basics-oauth/app.js)?

**Comment by callenskoen** [comment]
Hi @Wajeed-msft ,

I'm using the bot framework v4 - enterprise template 
https://github.com/Microsoft/AI/tree/master/templates/Enterprise-Template/src/typescript/enterprise-bot

For the authentication, I use the provided dialog https://github.com/Microsoft/AI/blob/master/templates/Enterprise-Template/src/typescript/enterprise-bot/src/dialogs/authentication/authenticationDialog.ts.

Regards,
Koen

**Comment by arkiaconsulting** [comment]
@Wajeed-msft  I'm in the exact same version and flow as @callenskoen

**Comment by Wajeed-msft** [comment]
@arkiaconsulting , @callenskoen  - Could you please share complete request/response body? Also, once sign in completed for SharePoint, Is it closing the pop-up? If so, are you getting any invoke action back in your code?

**Comment by arkiaconsulting** [comment]
Request url: https://emea.ng.msg.teams.microsoft.com/v1/agents/28:redacted-81e8-45cc-b691-7e4fecc8f0e0/invoke
Request payload:
`{"value":{"state":"859791"},"conversation":{"id":"19:redacted-28ad-4b18-b096-d58b285e1aee_redacted-81e8-45cc-b691-7e4fecc8f0e0@unq.gbl.spaces"},"name":"signin/verifyState","imdisplayname":"redacted"}`
Response:
`{"errorCode":1008,"message":"<BotError>Bot returned unsuccessful status code NotImplemented"}`

**Comment by Wajeed-msft** [comment]
Based on the request details, seems like signin/verifyState is not Implemented in the code. To confirm this, could you please try this [basic auth sample code](https://github.com/Microsoft/BotBuilder-V3/blob/master/Node/examples/basics-oauth/app.js) which handles signin/VerifySate invoke?

**Comment by arkiaconsulting** [comment]
@Wajeed-msft The sample you mentioned is in v3, but I'm using the botbuilder v4. Anyway, I tryed to have some more info about the requests incoming into my bot. Here is the last incoming request before the error:

> {"name":"signin/verifyState","type":"invoke","timestamp":"2019-02-02T09:04:04.516Z","localTimestamp":"2019-02-02T09:04:04.516Z","id":"f:REDACTED","channelId":"msteams","serviceUrl":"https://smba.trafficmanager.net/emea/","from":{"id":"29:REDACTED","name":"REDACTED","aadObjectId":"REDACTED-28ad-4b18-b096-REDACTED"},"conversation":{"conversationType":"personal","id":"a:REDACTED"},"recipient":{"id":"28:729b4244-81e8-45cc-b691-7e4fecc8f0e0","name":"REDACTED"},"entities":[{"locale":"fr-FR","country":"FR","platform":"Web","type":"clientInfo"}],"channelData":{"tenant":{"id":"REDACTED-3605-469a-bf42-REDACTED"},"source":{"name":"message"}},"value":{"state":"035009"}}

and finally the error i'm getting:

> UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'toString' of undefined
    at BotFrameworkAdapter.<anonymous> (/app/node_modules/botbuilder/lib/botFrameworkAdapter.js:491:95)
    at Generator.next (<anonymous>)
    at fulfilled (/app/node_modules/botbuilder/lib/botFrameworkAdapter.js:11:58)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)

**Comment by arkiaconsulting** [comment]
@callenskoen I found a workaround. I just had to intercept the activity whose name is `signin/verifyState` in my main bot handler, as following:
```ts
if (context.activity.name === 'signin/verifyState') {
   let oAuthDialog: Dialog<{}> = this.dialogs.find(AUTH_DIALOG);
   const dc = await this.dialogs.createContext(context);
   await oAuthDialog.continueDialog(dc);
}
```

**Comment by Wajeed-msft** [comment]
@callenskoen , @arkiaconsulting - signin/verifyState event needs to be handled in the bot code. Here is document on [handle the login complete activity](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/authentication/auth-oauth-card#getting-started-with-oauthcard-in-teams). 

Also, you can raise this issue as an issue on [Enterprise-Template](https://github.com/Microsoft/AI/issues) repo so that it's fixed in template itself.
