### ISSUE TITLE
AdaptiveCards - OpenUrl Action fails to execute when URL host is a short hostname containing numbers

### ISSUE THREAD

**Issue by ig-jb** [MicrosoftDocs/msteams-docs#4033]
```
{
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "type": "AdaptiveCard",
  "version": "1.0",
  "body": [
    {
      "type": "TextBlock",
      "text": "This card's action will open a URL"
    }
  ],
  "actions": [
    {
      "type": "Action.OpenUrl",
      "title": "Action.OpenUrl",
      "url": "https://<<your machine name here>>"
    }
  ]
}
```
AdaptiveCards in Teams are currently failing to execute OpenUrl actions when using your local machine name as the host in the URL. This causes problems testing local development builds of Teams apps. 

The issue can be observed by setting your machine name in the sample above. On clicking the button, nothing happens. An error can be observed in the developer console.

![image](https://user-images.githubusercontent.com/73241590/130805758-1567a2ba-bef9-452c-bd5e-3f7c3e046451.png)

**Comment by Prithvi-MSFT** [comment]
Hi, Seems like the URL you are giving is invalid. We tried with localhost url and some other url's and they worked for us. Could you check with some other valid URL ?

**Comment by ig-jb** [comment]
@Prithvi-MSFT It works fine with localhost, but doesn't work with your machine name. E.g. if my machine name was jackb, https://jackb/ will fail to launch. Please try with your machine name.

**Comment by Prithvi-MSFT** [comment]
Hi, Does the same URL you are trying,  opens in browser manually without adaptive card ?

**Comment by ig-jb** [comment]
@Prithvi-MSFT Yes, the URL is fine when launched manually. It is only when launching via adaptive card that it fails.

**Comment by Prithvi-MSFT** [comment]
Hi, so when trying to open the url from adaptive card with machine name I also faced error in console. However when I try to open same url in browser got the can't connect page. Can you share some screenshot when you open the URL in browser.

**Comment by ig-jb** [comment]
@Prithvi-MSFT If you don't have a webserver running locally you'll get the can't connect page. If you start IIS locally you should get the IIS landing page.

The expected behaviour from an adaptive card in Teams if you don't have a webserver running is indeed the can't connect page in a new tab, instead of an error in the console and no new tab.

**Comment by ig-jb** [comment]
URL direct in browser with IIS running:
![image](https://user-images.githubusercontent.com/73241590/130824954-838a49ea-6cc5-452f-9171-3e1b38399cb8.png)

**Comment by Prithvi-MSFT** [comment]
Hi, we tried with the URL you mentioned above and were able to hit the page on browser
![image](https://user-images.githubusercontent.com/87962396/130830532-12073a7e-df8b-4917-8d9b-92c67457e804.png)

**Comment by ig-jb** [comment]
@Prithvi-MSFT That worked because you used _my_ machine name. If you try again with your own machine name, you'll get the error and the tab won't launch.

**Comment by ig-jb** [comment]
@v-chetsh Thanks for the update. This is a strange design behaviour given hostnames with numbers in them are valid in the relevant RFC's -- but if that's a choice they've made that's fine. I have a workaround, which is to use `<<hostname>>.localdomain` e.g. `jackb11.localdomain` which doesn't have the same issue.

However, I think this limitation should be documented somewhere if it is by design. Could you please advise where I can find this in the documentation?

**Comment by v-chetsh** [comment]
@ig-jb - We have confirmed this with the engineering team but currently it's not documented.
Are you following any specific documentation and want us to add it there?

**Comment by ig-jb** [comment]
@v-chetsh I was following the Teams AdaptiveCards documentation at https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards-and-task-modules

I think it will save someone who also has a machine name ending in a number time if the limitation is documented there.

**Comment by sayali-MSFT** [comment]
@surbhigupta12 -Could you please help us to update the document?
In the below Action type openUrl section Edit the note section and one more note as bullet point

- If you are using a machine names with numbers then it is not supported in URL.

Doc-https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-actions?tabs=json#action-type-openurl
