### ISSUE TITLE
Column Style color not rendering in MSTeams

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#4057]
Copied bug from: https://github.com/microsoft/AdaptiveCards/issues/6240 

**Details from original post:**
### Target Platforms

Other

### SDK Version

1.3

### Application Name

Microsoft Teams

### Problem Description

On changing the style of the column to "accent" or "warning", the background color isn't changing on MS Teams. 
This used to work previously, had been encountering this issue for the past couple of weeks.
Can someone help with this?

### Screenshots

<img width="495" alt="Screen Shot 2021-08-24 at 8 47 22 PM" src="https://user-images.githubusercontent.com/25703065/130644194-84846ea1-77e4-461d-985c-91545a2b2389.png">

### Card JSON

```JSON
{
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "type": "AdaptiveCard",
    "version": "1.2",
    "body": [
        {
            "type": "ColumnSet",
            "columns": [
                {
                    "type": "Column",
                    "items": [
                        {
                            "type": "TextBlock",
                            "text": "Column 1"
                        }
                    ],
                    "width": "stretch",
                    "style": "accent"
                }
            ]
        }
    ]
}
```

### Sample Code

_No response_---
#### Document Details

⚠ *Do not edit this section.It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Cards reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **surbhigupta12**

**Comment by Deepima04** [comment]
Hi, @Meghana-MSFT any update on this issue?

**Comment by Meghana-MSFT** [comment]
@Deepima04 - The engineering team is looking into the issue and we do not have any update on this yet. We will let you know.

**Comment by Meghana-MSFT** [comment]
Closing this thread as the issue has been fixed. Please feel free to reopen if you face this issue again.
