### ISSUE TITLE
Queries on Architecture

### ISSUE THREAD

**Issue by dips23** [MicrosoftDocs/msteams-docs#406]
Hello,

Thank you for making this business scenario available to think about further possible solutions, however I have few queries as follows:

Is PMO app configured with Microsoft teams for Project leader to open in other teams ? Or its a single stand alone app to be accessed from windows/Mobile ?

In third step, what is Microsoft Planner templates - I assume this is not a Planner plan, Can you please clarify this further ? 

In 4th Step, user selects available plan which is backed by O365 group already, and when team would be created further, Will it create  new O365 group, Or use the existing one which was already created by selected plan ?

Looking forward to hearing from you soon !

Thank you in advance.

Best Regards,
Dipti Chhatrapati

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f3c8f31-2b8f-bf1f-6bd8-22b17734dd2e
* Version Independent ID: 27d22bee-8d21-49c7-daf4-f7883c260fc7
* Content: [Microsoft Teams Project Management Organization - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/scenarios/lob-pmo-scenario)
* Content Source: [msteams-platform/scenarios/lob-pmo-scenario.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/scenarios/lob-pmo-scenario.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by brandber** [comment]
Hi Dipti,
 
Thank you for your questions. The intent of the App Scenarios section is to provide real-world examples of what could be done and calling out the Teams platform and infrastructure components needed to do so. The examples themselves are not presently backed w/ code samples (we are looking into adding these in the future).

Today, Microsoft Planner does not currently have templates. To create a template-like approach, it requires using the Microsoft Graph API. An example workflow would be:
 

1. [Create a Microsoft Planner plan](https://docs.microsoft.com/en-us/graph/api/planner-post-plans?view=graph-rest-1.0) within a given team (supply Group Id of the Team in the request)
2. [Add tasks to the existing plan](https://docs.microsoft.com/en-us/graph/api/planner-post-tasks?view=graph-rest-1.0)
3. The last step would be to [pin as a Tab](https://docs.microsoft.com/en-us/graph/api/teamstab-add?view=graph-rest-1.0) within a channel of that Team (as describe in the PMO example)

We will take an action to clarify the terminology used in this article.
 
Thanks again for taking the time to give feedback!
