### ISSUE TITLE
Document limits on the size of the response

### ISSUE THREAD

**Issue by aosolis** [MicrosoftDocs/msteams-docs#4062]
Is there a limit to the size of the JSON that can be returned by the app? The documentation is silent, but there are reports of a 28KB limit.

> Within our logs, we receive the following message: "<BotError>Error when processing invoke response: Tab response size is greater than allowed. TabSize (bytes) - 30459; Limit (bytes) - 28000".

We need to document this, and what the recommended pattern is for dealing with the limit.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a3a4238-5916-eff7-25cf-bff2362ab246
* Version Independent ID: 12048d7d-de6a-43d8-44d5-7ab1be9972a2
* Content: [Build Adaptive Card Tabs - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/build-adaptive-card-tabs)
* Content Source: [msteams-platform/tabs/how-to/build-adaptive-card-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tabs/how-to/build-adaptive-card-tabs.md)
* Product: **msteams**
* GitHub Login: @KirtiPereira
* Microsoft Alias: **surbhigupta**

**Comment by Meghana-MSFT** [comment]
There is a 50kb limit. The document will be updated with the same.

**Comment by Meghana-MSFT** [comment]
Closing this issue as it has been redirected to doc team.
