### ISSUE TITLE
Figma resources

### ISSUE THREAD

**Issue by LouRaul** [MicrosoftDocs/msteams-docs#407]
Is there a way to get the resources you shared in .pdf as a Figma file?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5847d1f2-5fd3-1d76-a126-a8c9e251c74f
* Version Independent ID: c7ee1d92-1481-f642-1114-1db073334324
* Content: [Design Guidelines Resources - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/design/resources)
* Content Source: [msteams-platform/resources/design/resources.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/resources/design/resources.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by clearab** [comment]
That's an interesting program, but we won't be creating Figma files for the resources.
