### ISSUE TITLE
Codesample markdown is broken 

### ISSUE THREAD

**Issue by omonimus1** [MicrosoftDocs/msteams-docs#4072]
The table present in the [code Sample section](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/get-started/code-samples.md) has some syntax error that does not render properly the table. 
![image](https://user-images.githubusercontent.com/23085146/131215374-3b3e0279-6b75-4928-b817-a570786f4949.png)

**Comment by v-chetsh** [comment]
This is related to document bug so redirected to doc-bug team.
