### ISSUE TITLE
Add button does not react when adding connectors to a Teams channel

### ISSUE THREAD

**Issue by TheOnion7** [MicrosoftDocs/msteams-docs#4073]
I'm trying to add a connector to my Teams channel since my last one expired but when I click on the Add button , nothing happens.
![image](https://user-images.githubusercontent.com/26538449/131376358-3e3f3d82-cef8-4381-a902-8f95feed0a8a.png)

**Comment by v-chetsh** [comment]
@TheOnion7 - Could you please try to delete existing one & then add another one.

**Comment by TheOnion7** [comment]
I don't have any collector configured at the moment.

Félix🔒 Privacy as a priority

sent from ProtonMail mobile for security and privacy

-------- Original Message --------

**Comment by v-chetsh** [comment]
@TheOnion7 - I am not able to repro this issue:
![image](https://user-images.githubusercontent.com/59052547/131554395-1c6625f6-5687-4a52-b1d9-c45da3986ed0.png)

![image](https://user-images.githubusercontent.com/59052547/131554447-92e2329f-3fb7-4637-a2bf-ba45c1e4bb91.png)

![image](https://user-images.githubusercontent.com/59052547/131554557-7053ac76-a187-46b1-aa5d-bf84677139f8.png)

![image](https://user-images.githubusercontent.com/59052547/131554622-30ca00c4-468e-45db-af7a-01f1f51be176.png)

Could you please try refreshing your Teams client & then try it again.

**Comment by v-chetsh** [comment]
@TheOnion7 -  Could you please confirm whether this issue is resolved or not ?

**Comment by TheOnion7** [comment]
@v-chetsh No the issue is not resolved. I can't even go further than the page where you see the "Add" button . It just doesn't react at all. 
![image](https://user-images.githubusercontent.com/26538449/131879931-dd830a7f-4650-4703-9056-e272fce33223.png)

**Comment by v-chetsh** [comment]
@TheOnion7 - Could you please try it in different channel in Team & try to add Incoming Webhook.

**Comment by TheOnion7** [comment]
@v-chetsh Yes it does the same thing with all the channels I have.

**Comment by v-chetsh** [comment]
@TheOnion7 - Could you please create another team and then try it again.
Else could you please try updating your Teams Desktop client and test it.

**Comment by TheOnion7** [comment]
@v-chetsh I tried both and both don't work. I will give another try to uninstall and reinstall.

**Comment by v-chetsh** [comment]
@TheOnion7  - Could you please close the issue if it is resolved or let us know if you need any help.

**Comment by TheOnion7** [comment]
Thanks for your time on this issue. The issue was never resolved even after I tried anything possible . My workaround was to finally asked someone else in my organization to add the connector. I made him owner of the channel and he was able on his side to add the connector. 

But the issue still exists, I won't be able to add any connector to any channel. I don't know what to do with that. Is it something specific to my system ( which is the same as the other person that was able to do it ) ,or is it a real bug? I don't really know the answer. What would you like to do with that since it doesn't seem to be reproducible ?

**Comment by v-chetsh** [comment]
@TheOnion7 - We tried it in multiple devices on Teams web client with different users and it's working for us.
Could you please try updating your Teams client and check it once.

**Comment by TheOnion7** [comment]
Yes , I did it already . It must be something on my side. I will continue to investigate. In the meantime , I have someone that can create the connectors for me . Thanks for your time. I think we can close this issue.

**Comment by v-chetsh** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.

**Comment by mapeterson42** [comment]
I'm seeing this same thing.
I had seen this before as well, but it eventually cleared up.  For reference the Add displays a yellow border when clicking but nothing else.  From the lgos`Thu Sep 23 2021 15:50:01 GMT-0500 (Central Daylight Time) <6076> -- info -- Notification with ID = 624dd603-fdf4-4ecc-bf7f-8de1164cc3cf was removed -- Profile Type: AAD 
Thu Sep 23 2021 15:50:01 GMT-0500 (Central Daylight Time) <6076> -- info -- notification manager: action taken for notification 624dd603-fdf4-4ecc-bf7f-8de1164cc3cf -- Profile Type: AAD 
Thu Sep 23 2021 15:50:01 GMT-0500 (Central Daylight Time) <6076> -- info -- Sending notificationActionTaken IPC to 1 
Thu Sep 23 2021 15:50:01 GMT-0500 (Central Daylight Time) <6076> -- info -- Sending notificationActionTaken IPC to 5 
Thu Sep 23 2021 15:50:01 GMT-0500 (Central Daylight Time) <6076> -- event -- eventpdclevel: null, name: desktop_activated_by_notification, profileType: undefined, AppInfo.Language: en-US, complianceEnvironmentType: 0, isDataCategorizationEnabled: true, userpdclevel: 0, processMemory: 19205420, freeMemory: 19001659392, clientType: desktop, AppInfo.ClientType: desktop, batterylevel: 1, pluggedin: true, Window.Focus: foreground, windowIsVisible: true, Window.Status: maximized, UserInfo.TimeZone: -05:00, vdiMode: 0,  
Thu Sep 23 2021 15:50:01 GMT-0500 (Central Daylight Time) <6076> -- info -- [AppStateService] [EnableBlueberry] enableBlueberry is defined as true returning : true 
Thu Sep 23 2021 15:50:01 GMT-0500 (Central Daylight Time) <6076> -- event -- panelaction: eventpdclevel: 1, Action.Gesture: click, Action.Outcome: nav, Action.Scenario: toastclick, Action.ScenarioType: nav, Module.Name: toastitem, Module.Type: toast, Panel.ViewId: 624dd603-fdf4-4ecc-bf7f-8de1164cc3cf, Panel.LaunchMethod: userinitiated, Panel.LaunchSource: toast, Panel.Region: toast, Panel.Type: toast, DataBag.toastType: download, Module.Summary: downloaded, Action.DestinationUri: , DataBag.threadId: , DataBag.messageId: , profileType: AAD, AppInfo.Language: en-US, complianceEnvironmentType: 0, isDataCategorizationEnabled: true, userpdclevel: 0, processMemory: 19243440, freeMemory: 19001331712, clientType: desktop, AppInfo.ClientType: desktop, batterylevel: 1, pluggedin: true, Window.Focus: foreground, windowIsVisible: true, Window.Status: maximized, UserInfo.TimeZone: -05:00, vdiMode: 0, eventType: panelaction, type: panelaction, name: panelaction,  -- Profile Type: AAD 
Thu Sep 23 2021 15:50:01 GMT-0500 (Central Daylight Time) <6076> -- info -- notification action taken, notificationId: 624dd603-fdf4-4ecc-bf7f-8de1164cc3cf, actionType: 1, sourceThreadId: undefined, messageId:undefined -- Profile Type: AAD 
Thu Sep 23 2021 15:50:01 GMT-0500 (Central Daylight Time) <6076> -- event -- eventpdclevel: 2, windowIsDestroyed: false, windowIsFocused: false, windowIsVisible: true, windowIsMinimized: false, windowIsMaximized: true, windowIsFullscreen: false, name: desktop_notification_actionTaken, id: 624dd603-fdf4-4ecc-bf7f-8de1164cc3cf, profileType: AAD, AppInfo.Language: en-US, complianceEnvironmentType: 0, isDataCategorizationEnabled: true, userpdclevel: 0, processMemory: 19320200, freeMemory: 19001212928, clientType: desktop, AppInfo.ClientType: desktop, batterylevel: 1, pluggedin: true, Window.Focus: foreground, Window.Status: maximized, UserInfo.TimeZone: -05:00, vdiMode: 0,  -- Profile Type: AAD 
Thu Sep 23 2021 15:50:01 GMT-0500 (Central Daylight Time) <6076> -- info -- PurpleNotificationService: About to hide toast renderer 
Thu Sep 23 2021 15:50:01 GMT-0500 (Central Daylight Time) <6076> -- info -- PurpleNotificationService: hide toast renderer 
Thu Sep 23 2021 15:50:01 GMT-0500 (Central Daylight Time) <6076> -- event -- eventpdclevel: 2, profileType: AAD, status: success, scenario: ca77e969-0a34-417f-9702-96563029187f, scenarioName: taskbar_set_icon_overlay, name: taskbar_set_icon_overlay, step: start, sequence: 0, delta: 1, scenarioDelta: 1, elapsed: 384201, stepDelta: 0, Scenario.Mode: 1, AppInfo.Language: en-US, complianceEnvironmentType: 0, isDataCategorizationEnabled: true, userpdclevel: 0, processMemory: 19346096, freeMemory: 19000492032, clientType: desktop, AppInfo.ClientType: desktop, batterylevel: 1, pluggedin: true, Window.Focus: foreground, windowIsVisible: true, Window.Status: maximized, UserInfo.TimeZone: -05:00, vdiMode: 0, Scenario.Name: taskbar_set_icon_overlay, Scenario.Step: start, Scenario.Status: success,  -- Profile Type: AAD 
Thu Sep 23 2021 15:50:01 GMT-0500 (Central Daylight Time) <6076> -- info -- Setting the taskbar overlay icon - New activity 
Thu Sep 23 2021 15:50:01 GMT-0500 (Central Daylight Time) <6076> -- event -- eventpdclevel: 2, profileType: AAD, status: success, scenario: ca77e969-0a34-417f-9702-96563029187f, scenarioName: taskbar_set_icon_overlay, name: taskbar_set_icon_overlay, step: stop, sequence: 1, delta: 2, scenarioDelta: 2, elapsed: 384202, stepDelta: 1, Scenario.Mode: 1, AppInfo.Language: en-US, complianceEnvironmentType: 0, isDataCategorizationEnabled: true, userpdclevel: 0, processMemory: 19376900, freeMemory: 19000287232, clientType: desktop, AppInfo.ClientType: desktop, batterylevel: 1, pluggedin: true, Window.Focus: foreground, windowIsVisible: true, Window.Status: maximized, UserInfo.TimeZone: -05:00, vdiMode: 0, Scenario.Name: taskbar_set_icon_overlay, Scenario.Step: stop, Scenario.Status: success,  -- Profile Type: AAD 
Thu Sep 23 2021 15:50:01 GMT-0500 (Central Daylight Time) <6076> -- info -- Focusing window 1 
Thu Sep 23 2021 15:50:01 GMT-0500 (Central Daylight Time) <6076> -- info -- Is foreground set to true 
Thu Sep 23 2021 15:50:01 GMT-0500 (Central Daylight Time) <6076> -- info -- [AppStateService] [EnableBlueberry] enableBlueberry is defined as true returning : true 
Thu Sep 23 2021 15:50:01 GMT-0500 (Central Daylight Time) <6076> -- info -- NotificationsManager Page state change active -> passive 
Thu Sep 23 2021 15:50:01 GMT-0500 (Central Daylight Time) <6076> -- info -- NotificationsManager Page state change passive -> hidden 
Thu Sep 23 2021 15:50:01 GMT-0500 (Central Daylight Time) <6076> -- info -- Blur mainWindow window 
Thu Sep 23 2021 15:50:01 GMT-0500 (Central Daylight Time) <6076> -- info -- Is foreground set to false 
Thu Sep 23 2021 15:50:01 GMT-0500 (Central Daylight Time) <6076> -- event -- eventpdclevel: 2, duration: 0.0970001220703125, name: desktop_foreground_duration, AppInfo.Language: en-US, complianceEnvironmentType: 0, isDataCategorizationEnabled: true, userpdclevel: 0, processMemory: 19424032, freeMemory: 18997919744, clientType: desktop, AppInfo.ClientType: desktop, batterylevel: 1, pluggedin: true, Window.Focus: foreground, windowIsVisible: true, Window.Status: maximized, UserInfo.TimeZone: -05:00, vdiMode: 0,  
Thu Sep 23 2021 15:50:01 GMT-0500 (Central Daylight Time) <6076> -- event -- eventpdclevel: 2, source: WebLogDownload, supportLogVersion: v2, status: success, scenario: 873f61a5-06a5-40e3-9373-af9ce22a89a9, scenarioName: desktop_support_file_processing, name: desktop_support_file_processing, step: stop, sequence: 6, delta: 594, scenarioDelta: 594, elapsed: 382485, stepDelta: 7, Scenario.Mode: 1, AppInfo.Language: en-US, complianceEnvironmentType: 0, isDataCategorizationEnabled: true, userpdclevel: 0, processMemory: 19456508, freeMemory: 18996211712, clientType: desktop, AppInfo.ClientType: desktop, batterylevel: 1, pluggedin: true, Window.Focus: foreground, windowIsVisible: true, Window.Status: maximized, UserInfo.TimeZone: -05:00, vdiMode: 0, Scenario.Name: desktop_support_file_processing, Scenario.Step: stop, Scenario.Status: success,  
Thu Sep 23 2021 15:50:03 GMT-0500 (Central Daylight Time) <6076> -- info -- Notification with ID = 624dd603-fdf4-4ecc-bf7f-8de1164cc3cf was not found. Nothing to remove `

**Comment by mapeterson42** [comment]
FWIW, I got around it by using the web, but even there I initially had office refusing to connect (ironically that looks like the old unhappy Mac Icon)
