### ISSUE TITLE
MS Docs All The Same

### ISSUE THREAD

**Issue by smchargue** [MicrosoftDocs/msteams-docs#4074]
Microsoft Documentation is all the same.  You go from a page that conveys no information, but has a link for more details. When you click on the link you have a page provides information, but assumes you know 1,000 things in order for it to be understood.  

This page is no different, i'm just trying to learn how to style a custom teams app so it it looks like a teams app in default and dark mode, and i go from this page to Figma - which assumes I am a Figma Jedi in order to wrestle out the information i need.  

It's just all so pointless and frustrating. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e13fe9ac-9ae6-4f86-e800-e667ea49cd73
* Version Independent ID: d1034128-eda7-8d57-3d1d-dd862043db17
* Content: [Design your app - Understand the design system - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/design/design-teams-app-fundamentals)
* Content Source: [msteams-platform/concepts/design/design-teams-app-fundamentals.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/design/design-teams-app-fundamentals.md)
* Product: **msteams**
* GitHub Login: @heath-hamilton
* Microsoft Alias: **lajanuar**

**Comment by heath-hamilton** [comment]
@smchargue Very sorry to hear about your experience. This link may have what you need: https://fluentsite.z22.web.core.windows.net/0.57.0/color-schemes#design-token. It does take you to a separate Fluent UI docs site, but it lists all the colors supported for each Teams theme (default, dark, and high contrast).

Does this help? Any other feedback would be greatly appreciated so we can make this better for you and others.

**Comment by Meghana-MSFT** [comment]
@smchargue We are closing this issue for now, Please feel free to reopen it, if required.
