### ISSUE TITLE
No documentation found to add Notification bar outside iframe

### ISSUE THREAD

**Issue by riyasree-accenture** [MicrosoftDocs/msteams-docs#4084]
Under the Anatomy: In-meeting tab section, point 5 shows how we can add a notification bar that's outside the iframe. But it's not clear how we can add it there, as all the alert and notification components present in the Microsoft Teams Docs and Fluent UI docs can only be added inside the iframe. Please update the design with a link to the document which shows how this can be achieved. Or else if it's not possible, please update the Anatomy section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09c05a14-d442-bcd1-f233-1beeddfd4bb1
* Version Independent ID: eb958ded-39dc-c0ab-a7c8-2d5bf334ab16
* Content: [Designing your meeting extension - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/design/designing-apps-in-meetings?tabs=desktop#anatomy-in-meeting-tab)
* Content Source: [msteams-platform/apps-in-teams-meetings/design/designing-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/apps-in-teams-meetings/design/designing-apps-in-meetings.md)
* Product: **msteams**
* GitHub Login: @heath-hamilton
* Microsoft Alias: **lajanuar**

**Comment by HunaidHanfee-MSFT** [comment]
Hello,
We are looking into this. We will get back to you soon after confirming internally.
Thanks

**Comment by HunaidHanfee-MSFT** [comment]
Document shows a design guidelines to the developer. There is no developer API or framework that we offer. It is a guide for developers to design their error experience(notification bar). 
I believe that, it is conveying that a  error banner(notification bar) can be render outside of iframe but notification bar would have to **display within the iframe**. You have to use some package like Fluent UI.

We have connected with internal team and our team has already raised a bug from our side and the information on the document will be updated accordingly.
