### ISSUE TITLE
messageback and deeplinking not working in mobile teams

### ISSUE THREAD

**Issue by DivyaDev1992** [MicrosoftDocs/msteams-docs#4087]
The code for creating a card with messageback is as follows: It works well in desktop, client and iOS teams, But fails in Android teams.
 ```
CardFactory.actions([
                        {
                            type: "messageBack",
                            title: "Yes",
                            displayText: "Yes",
                            text: "Yes",
                            value: "logout-yes"
                        },
                        {
                            type: "messageBack",
                            title: "No",
                            displayText: "No",
                            text: "No",
                            value: "logout-no"
                        }
                    ]));
```

The manifest schema is 1.9
The botbuilder configurations are:
    "botbuilder": "^4.13.6",
    "botbuilder-dialogs": "^4.13.6",
    "botbuilder-teams": "^0.2.9",
    "botframework-connector": "^4.14.0",

All the other bot commands are working well, except messageBack.

Also, deeplinking is not working in mobile. It is working fine in desktop and client mobile. For deeplinking, we use the following: **AUTHURL = "https://teams.microsoft.com/l/entity/28:" + MICROSOFT_APP_ID + "/" + TAB_ID + "?conversationType=chat";**
The mobile throws the following error:
![image](https://user-images.githubusercontent.com/79892178/131662679-0aeaebcd-712b-4883-9898-6b0968921a4d.png)

**Comment by Prasad-MSFT** [comment]
Hi @DivyaDev1992, There is a bug raised regarding messageBack action not working in Android Teams and concerned team is looking into it. Will let you know once we get any update. Thanks!

**Comment by Prasad-MSFT** [comment]
Unlike desktop, mobile does not show error message when call fails thats the reason it does not display anything after "messageback".
