### ISSUE TITLE
[MSTeams][Action.OpenURL] Open URl button is not working with some URls in Teams

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#4094]
Copied bug from: https://github.com/microsoft/AdaptiveCards/issues/4500 

**Details from original post:**
# Platform
* .NET Core

# Host
* Ms Teams

Hello Team,

I have built a bot using MS Bot framework v4 and hosted in MS teams.

I have noticed that the Action.OpenURL button is not working some time in the Adaptive card when URl is containing text with some Local language characters.

I have tried the same in App studio and the button is not clickable.

Please find the sample Adaptive card with Action.OpenURL below:-

```
{"type":"AdaptiveCard","$schema":"http://adaptivecards.io/schemas/adaptive-card.json","version":"1.2","body":[{"type":"TextBlock","wrap":true,"text":"The first open url is not working in MS Teams"}],"actions":[{"type":"Action.OpenUrl","url":"https://DummyHomepage.Com/esc?id=Look&spa=1&t=kb&q=política de carro","title":"OpenUrl not working"},{"type":"Action.Submit","title":"Cancel"}]}
```

Please help us with this as soon as possible.
Thanks.

---
#### Document Details

⚠ *Do not edit this section.It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Cards reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **surbhigupta12**

**Comment by Prasad-MSFT** [comment]
We are able to repro the issue at our end. We  have raised a bug for the same and the concerned team is looking into it. We will update you, once we get any response.

**Comment by Prasad-MSFT** [comment]
It looks like URIs by nature should not include unicode characters. If the accented characters need to be used in the URIs, then they will need to be encoded.
Please refer this [link](https://stackoverflow.com/questions/1386262/should-i-use-accented-characters-in-urls)
Thanks!

**Comment by Prasad-MSFT** [comment]
We are closing the issue for now. Please feel free to reopen if required.
