### ISSUE TITLE
[MsTeams][Rendering] [Data Uri for images not working on MsTeams application]

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#4095]
Copied bug from: https://github.com/microsoft/AdaptiveCards/issues/4487 

**Details from original post:**
# Author or host

I am the author and the host app is Ms Teams (either desktop and web), I am sending the adaptive card using Power Automate as personal chat message.

# Version of SDK

# Details

The data uri encoding worked few months ago and I have today tested directly on the designer, however the image is not displayed anymore on Microsoft Teams:

![image](https://user-images.githubusercontent.com/11196217/88467716-3411de00-ceda-11ea-83cc-18f4289614d0.png)

JSON:

`{"type":"AdaptiveCard","$schema":"http://adaptivecards.io/schemas/adaptive-card.json","version":"1.2","body":[{"type":"TextBlock","size":"Medium","weight":"Bolder","text":"New approval: ai processes and solutions"},{"type":"ColumnSet","columns":[{"type":"Column","items":[{"type":"Image","style":"Person","url":"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAXM[...]","size":"Small"}],"width":"auto"},{"type":"Column","items":[{"type":"TextBlock","weight":"Bolder","text":"User title","wrap":true},{"type":"TextBlock","spacing":"None","text":"Created 25-07-2020","isSubtle":true,"wrap":true}],"width":"stretch"}]},{"type":"TextBlock","text":"Nueva aprobación pendiente","wrap":true},{"type":"ActionSet","actions":[{"type":"Action.Submit","title":"Approve","style":"positive","data":{"ActionTaken":"Approved"}},{"type":"Action.Submit","title":"Reject","data":{"ActionTaken":"Rejected"}}]}]}`

---
#### Document Details

⚠ *Do not edit this section.It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Cards reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **surbhigupta12**

**Comment by Meghana-MSFT** [comment]
We are looking into this issue. We will get back to you.

**Comment by Meghana-MSFT** [comment]
@imari91 - We tried to repro this issue at our end with a dataUri. We were able to see the image in Microsoft Teams. Attaching a screenshot of the same. 
![imageuri](https://user-images.githubusercontent.com/81138249/132198934-c9ad2c04-2214-448f-b137-a939c334c17a.PNG)
Could you please help by providing us with the entire JSON that is failing?

**Comment by Meghana-MSFT** [comment]
@imari91 - Could you please provide us with the JSON that is failing?

**Comment by Meghana-MSFT** [comment]
We are closing this issue due to user inactivity. Please feel free to reopen it if you face the issue again.
