### ISSUE TITLE
How can I implement silent authentication within a Teams Tab with v2?

### ISSUE THREAD

**Issue by harveyconnor** [MicrosoftDocs/msteams-docs#4098]
Hi,
How can I implement silent MS Graph authentication within my Teams Tab application that I'm developing?
Users have already logged into MS Teams so we don't want to prompt the user to sign in again to have access to using the MS Graph api.
This documentation appears to be outdated and uses deprecated libraries.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2e66ffa-ec00-4a84-a43d-d47e3c138b32
* Version Independent ID: 47e9a383-ac6a-dc7d-2d91-a9e09626fdab
* Content: [Silent authentication - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-silent-aad)
* Content Source: [msteams-platform/tabs/how-to/authentication/auth-silent-aad.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tabs/how-to/authentication/auth-silent-aad.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by HunaidHanfee-MSFT** [comment]
We are checking this internally. Will get back to you soon.
Thanks

**Comment by HunaidHanfee-MSFT** [comment]
Hello @harveyconnor,
Please follow this document to migrate from ADAL.js to MSAL.js
https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-compare-msal-js-and-adal-js

We are closing this issue for now, Please feel free to reopen it if required.
Thanks
