### ISSUE TITLE
Send a message JSON payload is incorrect

### ISSUE THREAD

**Issue by clearab** [MicrosoftDocs/msteams-docs#4103]
I believe the send a message payload JSON in this article is incorrect (its actually the payload of a received message)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afbc5b84-5be5-b5c4-30c0-58782a748a03
* Version Independent ID: ef6b8aee-52e7-f5d4-7dfa-8f34a1698330
* Content: [Messages in bot conversations - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-messages?tabs=dotnet)
* Content Source: [msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/bots/how-to/conversations/conversation-messages.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **anclear**

**Comment by HunaidHanfee-MSFT** [comment]
Thanks for pointing this out. It seems like we need to switch JSON payload of send and receive. Assigning it to doc-team.

**Comment by HunaidHanfee-MSFT** [comment]
@clearab We will update the Send a message JSON with these : 
```
{
    "type": "message",
    "from": {
        "id": "28:c9e8c047-2a34-40a1-b28a-b162d5f5327c",
        "name": "Teams TestBot"
    },
    "conversation": {
        "id": "a:17I0kl8EkpE1O9PH5TWrzrLNwnWWcfrU7QZjKR0WSfOpzbfcAg2IaydGElSo10tVr4C7Fc6GtieTJX663WuJCc1uA83n4CSrHSgGBj5XNYLcVlJAs2ZX8DbYBPck201w-",
        "name": "Convo1"
   },
   "recipient": {
        "id": "29:1XJKJMvc5GBtc2JwZq0oj8tHZmzrQgFmB25ATiQWA85gQtHieVkKilBZ9XHoq9j7Zaqt7CZ-NJWi7me2kHTL3Bw",
        "name": "Megan Bowen"
    },
    "text": "My bot's reply",
    "replyToId": "1632474074231"
}
```

Assigning to doc team.
