### ISSUE TITLE
conjeunter2021

### ISSUE THREAD

**Issue by yiuyu2357** [MicrosoftDocs/msteams-docs#4122]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bfad75fb-f88b-1b5a-22ea-5fe2d5c180a6
* Version Independent ID: dbfd046c-79a4-bb81-a185-1fe5af363b7a
* Content: [Get started - Prerequisites - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/get-started/prerequisites?tabs=vscode)
* Content Source: [msteams-platform/get-started/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/get-started/prerequisites.md)
* Product: **msteams**
* GitHub Login: @adrianhall
* Microsoft Alias: **adhal**

**Comment by Meghana-MSFT** [comment]
@yiuyu2357 - Could you please elaborate your issue?

**Comment by Meghana-MSFT** [comment]
@yiuyu2357 - We are closing this issue due to user inactivity. Please feel free to reopen if you are facing the issue again.
