### ISSUE TITLE
Desktop Mobile Parity Gaps

### ISSUE THREAD

**Issue by SupritiBhan** [MicrosoftDocs/msteams-docs#4127]
[Enter feedback here]
It will be good to call out in a section what are the parity gaps bw Meeting extensibility among desktop and Mobile and plan etc. Heres a dump i created, feel free to use it in the right format.

[https://microsoft.sharepoint.com/:p:/r/teams/ExtensibilityandFundamentals/_layouts/15/Doc.aspx?sourcedoc=%7B460580E2-71AE-4CE9-9529-79C5C961DF25%7D&file=Meeting%20Extensibility%20BrownBag%20Session1.pptx&action=edit&mobileredirect=true&share=IQHigAVGrnHpTJUpecXJYd8lAYDQiDSnmo751WF5kHhlWGU](url)
 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82987815-d508-d642-c1f6-b609241d4750
* Version Independent ID: 29e89cc6-c8ca-7d29-7dca-4ac4d06f5c42
* Content: [Apps for Teams meetings - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/teams-apps-in-meetings)
* Content Source: [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by HunaidHanfee-MSFT** [comment]
Sorry but I didn't understand the issue could you please explain it little.
Thanks for understanding.

**Comment by HunaidHanfee-MSFT** [comment]
Hi @SupritiBhan,
We try to open the URL you shared but didn't find any content in it. Could you please check and confirm once?

**Comment by HunaidHanfee-MSFT** [comment]
I am closing this as of now. Please let us know more about this query and feel free to open it.
