### ISSUE TITLE
Message does not appears in multiple participant conversation window

### ISSUE THREAD

**Issue by XL64** [MicrosoftDocs/msteams-docs#413]
Hello,

We are several users using TEAMS on Mac (Total) and messages are not shown in the conversation windows.
Some of us are using web client other native client.
Message also appear in wrong order...

Regards,

XL.

**Comment by Wajeed-msft** [comment]
@XL64 - Could you please share the screenshot & logs (%AppData%\Microsoft\Teams\logs.txt)?
