### ISSUE TITLE
Can't access tabs in the more menu on Android client

### ISSUE THREAD

**Issue by ntt261298** [MicrosoftDocs/msteams-docs#4136]
**Issue**
I have an app using 7 static tabs and 5 of them show up in the more menu dropdown. When I select any item in the dropdown using an Android device, the tab is not opened correctly. Instead, I was redirected to the first tab of the app in a new popup. This behavior only occurs on Android devices, it works fine in the Desktop app, Web app and iOS app. This previously used to work.

**Manifest schema version**
https://developer.microsoft.com/en-us/json-schemas/teams/v1.8/MicrosoftTeams.schema.json

**Android client version**
10 QKQ1.190919.002

**Comment by Meghana-MSFT** [comment]
@ntt261298  - We were able to repro the issue. We have raised a bug and the concerned team is looking into it.

**Comment by v-chetsh** [comment]
@ntt261298 - This issue has fixed and will be available generally next month.

**Comment by v-chetsh** [comment]
@ntt261298 - This issue has fixed and will be available generally next month.

**Comment by v-chetsh** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.

**Comment by bartlomiejzuber** [comment]
@v-chetsh May I ask for assumed date when it will be deployed to google store please ?
