### ISSUE TITLE
Should document the ability to use Markdown and cards with outgoing webhooks

### ISSUE THREAD

**Issue by billbliss** [MicrosoftDocs/msteams-docs#414]
It's possible to use any card and markdown in the response to an outgoing webhook responses, but we never say that anywhere. It undersells the feature significantly. We should document this (perhaps in a separate article under "App scenarios") and update the samples to show simple examples.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06c224ae-1484-408c-d17a-e7e1ba07e78a
* Version Independent ID: fac8ff1e-a127-c12a-5304-9de39b1a15c6
* Content: [Outgoing webhooks - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/outgoingwebhook)
* Content Source: [msteams-platform/concepts/outgoingwebhook.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/outgoingwebhook.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by friedhelmensch** [comment]
I am really looking forward to this documentation. Until you are officially releasing it, can you give some preview or hints how to return a response that contains a card / displays a card in the teams channel? Just something to get started. Would be awesome!
