### ISSUE TITLE
Teams SSO + Personal Sharepoint tab

### ISSUE THREAD

**Issue by kushalbhabra** [MicrosoftDocs/msteams-docs#4142]
**Background:**
I'm able to use this documentation to configure SSO for our bot on teams. 

The SSO configuration uses AAD App ID of the user authentication AAD app.

**Problem:**
I'd also like to show a SharePoint online page as an tab within my teams bot app.
But for that I'd need to set AAD App Id as that of SharePoint online, which is 00000003-0000-0ff1-ce00-000000000000.
[Reference article](https://www.sharepointeurope.com/building-microsoft-teams-apps-with-sharepoint-pages-part-2-build-your-own/)

**Ask:**
Need information on how can I have both, i.e. SSO with Bot and SSO with SharePoint online page as tab?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9549caa9-99a2-2568-19a5-f21a79292e2f
* Version Independent ID: f2100d03-b88a-34b2-44a2-935231e89db0
* Content: [Single sign-on support for bots - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/authentication/auth-aad-sso-bots)
* Content Source: [msteams-platform/bots/how-to/authentication/auth-aad-sso-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/bots/how-to/authentication/auth-aad-sso-bots.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by HunaidHanfee-MSFT** [comment]
I have checked internally and came to know that this is not possible, as of now [_webApplicationInfo_](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema#webapplicationinfo) accepts only single resource detail.

I will get back to you if I find any workaround for this.

Please feel free to open this issue, I am closing this as of now.
Thanks, 
Hunaid Hanfee

**Comment by kushalbhabra** [comment]
Hi, would like to open this issue to know possible workaround.

**Comment by HunaidHanfee-MSFT** [comment]
@kushalbhabra Sorry I checked internally but there's in no workaround.

**Comment by kushalbhabra** [comment]
Alright, thanks for prompt response.
