### ISSUE TITLE
How to get error description if webhook returns 200?

### ISSUE THREAD

**Issue by maiermic** [MicrosoftDocs/msteams-docs#4145]
This is a follow up question to #402. As the author of the ticket wrote, you get something like this

> Webhook message delivery failed with error: Microsoft Teams endpoint returned HTTP error 400 with ContextId tcid=385194272617051900,server=BL2PEPF000001C8,cv=wUmM9kBhpkiOZnT3ZEwhdg.0..

How are you supposed to know, what causes the error? Which part of the sent data is invalid?

> This is a known code design. We basically return 200 OK as soon as we get the webhook post request. Processing the request is done asynchronously and that's where we figure out if the request is invalid.
There is no plans to change this behaviour anytime soon.

@Wajeed-msft Do you also figure out, why the request is invalid? Could you encode the response as JSON, e.g.

```json
{
    "status": 400,
    "body": "Invalid type daptiveCard"
}
```

**Comment by Prasad-MSFT** [comment]
Hi @maiermic , We tried to repro the issue and we can confirm that we are also getting the same as you are getting. We are basically getting 200 OK although Webhook message delivery failed with error: Microsoft Teams endpoint returned HTTP error 400.
There is no plan to change this behaviour in near future. We are checking this issue with concerned team. Thanks!

**Comment by maiermic** [comment]
> We are checking this issue with concerned team.

@PramodValavala-MSFT Thanks for checking. Does this mean that you plan to answer my questions?

**Comment by Prasad-MSFT** [comment]
We have raised the concern. The team will look into that and and will try to fix . There is no such ETA to share.

**Comment by PramodValavala-MSFT** [comment]
> > We are checking this issue with concerned team.
> 
> @PramodValavala-MSFT Thanks for checking. Does this mean that you plan to answer my questions?

I suppose you didn't mean to mention me here 😅

**Comment by maiermic** [comment]
> I suppose you didn't mean to mention me here 😅

No 😅  But I appreciate the respone 😉

**Comment by Prasad-MSFT** [comment]
@maiermic , Unfortunately there is no plan to change this behaviour anytime soon. This logic exists since inception on Exchange backend to mitigate issue that many of 3p apps consider error response as connector removed and doesn't send further posts. However, you should get 410 if connector is removed, but Teams errors are hidden in 200 as Exchange is not able to distinguish valid errors.
Thanks for understanding.

**Comment by maiermic** [comment]
@Prasad-MSFT Thanks for your response. I have some follow up questions:

> but Teams errors are hidden in 200

What are Teams errors?

> Exchange is not able to distinguish valid errors

What are valid errors?

> Unfortunately there is no plan to change this behaviour anytime soon.

Is there a workaround to at least validate that the data or adaptive card is valid (e.g. to find typos in types or to check if maximum content length is exceeded)? It would be better than nothing if I have to log the data, copy it manually and use a different tool to validate. At the moment, I still have to guess, why the data is invalid.

**Comment by Prasad-MSFT** [comment]
@maiermic Usually the valid errors like HTTP error 400 ( Teams channel which is no longer configured or Wrong adaptive card input) or  Error 410 (connector is removed) are hidden in 200. There is no exact response from which we can get the error details.
![image](https://user-images.githubusercontent.com/62237649/134502670-a45ff122-5520-4b9a-920f-0c961c2393b9.png)

**Comment by Prasad-MSFT** [comment]
We will get HTTP error 400 when the JSON is invalid or Teams channel which is no longer configured. But ww won't get the exact reason of the error.
Currently message size limit is 28 kb.
https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams#teams-and-channels

**Comment by maiermic** [comment]
Thanks for your help.
