### ISSUE TITLE
cannot use video on macos mojave

### ISSUE THREAD

**Issue by aykutucar** [MicrosoftDocs/msteams-docs#415]
Hi,
I am using Teams on a Macbook Pro 2015 model with macos Mojave.
When try to use my video, I get this.
I already tried restarting and uninstalling Skype for Business (which was working fine) but nothing changed.
Thanks for your help.

![image](https://user-images.githubusercontent.com/2928431/51843933-499c4c80-22d1-11e9-8c5c-5509c6ebaed6.png)

![image](https://user-images.githubusercontent.com/2928431/51843963-5a4cc280-22d1-11e9-930b-9029485267ed.png)

**Comment by billbliss** [comment]
At any point in the past, did Microsoft Teams request access to your camera, and you declined?

**Comment by clearab** [comment]
If you're still experiencing this issue, please see this forum conversation about allowing access to your camera. If that doesn't work for you, please feel free to re-open the issue.

https://forums.macrumors.com/threads/camera-mic-fix-for-skype-etc-mojave.2144319/
