### ISSUE TITLE
Teams - Bot SSO + SharePoint page tab SSO

### ISSUE THREAD

**Issue by kushalbhabra** [MicrosoftDocs/msteams-docs#4151]
**Background:**
I'm able to use this documentation to configure SSO for our bot on teams.
The SSO configuration uses AAD App ID of the user authentication AAD app.

**Problem:**
I'd also like to show a SharePoint online page as an tab within my teams bot app.
But for that I'd need to set AAD App Id as that of SharePoint online, which is 00000003-0000-0ff1-ce00-000000000000.
Reference article

**Ask:**
Need workaround or alternate solutions on how can I have both, i.e. SSO with Bot and SSO with SharePoint online page as tab?
Would like to open this issue to know possible workaround. 

_Originally posted by @kushalbhabra in https://github.com/MicrosoftDocs/msteams-docs/issues/4142#issuecomment-918656569_

**Comment by HunaidHanfee-MSFT** [comment]
Hello @kushalbhabra,
I have looked internally, there's no way around. Manfest's webApplicationInfo only accepts one object, you cannot do both in single application.
