### ISSUE TITLE
Rate limiting for connectors

### ISSUE THREAD

**Issue by bagdenia** [MicrosoftDocs/msteams-docs#4155]
Hi, guys!
  
For integration purposes I've been testing incoming webhooks behaviour. After exceeding Maximum allowed requests per 30 seconds the ability to send requests was blocked for more than 3 hours. Could you provide some details about the politics of locking? In 429 response body we couldn't find any details about time when request would become available.

Thanks in advance, Evgenia.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28316a67-22fa-8a05-1ae0-fbe1c5720ef9
* Version Independent ID: 8a250e46-2a30-af86-839d-9f83a8b48041
* Content: [Create and send messages - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-using?tabs=cURL)
* Content Source: [msteams-platform/webhooks-and-connectors/how-to/connectors-using.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/webhooks-and-connectors/how-to/connectors-using.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by HunaidHanfee-MSFT** [comment]
I am looking into this, I will update you soon, on if there is a document available or not .
Thanks

**Comment by bagdenia** [comment]
> I am looking into this, I will update you soon, on if there is a document available or not .
> Thanks

Hi, any updates? )

**Comment by HunaidHanfee-MSFT** [comment]
Yes, We have got some update- 
The rate limit mention in doc follows the same industry standard of sliding window algorithm for rate limiting. For example, if Cx hit the 1 hour rate limit window, they will be throttled for the next 1 hour from the time the last request exceeded the limit, in the 1 hour window. If they hit multiple rate limit windows, all will apply and follow the same behavior.

This is same for Bots as well.

**Comment by bagdenia** [comment]
Got it, thanks!
