### ISSUE TITLE
"What Can I Do?" bot menu layout is obstructed at certain widths

### ISSUE THREAD

**Issue by wdoyle-lifesize** [MicrosoftDocs/msteams-docs#416]
Using the desktop client on mac, when the window width is around 947 (right before the minimizing breakpoint), the layout of the "What Can I Do?" bot menu is obstructed. It is overlapped by the Team/Chat list panel on the left, so that the user can not see the list of available commands.

**Comment by Wajeed-msft** [comment]
@wdoyle-lifesize - Could you please provide screenshot for this?

**Comment by Wajeed-msft** [comment]
@wdoyle-lifesize - Please provide screenshots and re-open this if you are still facing this issue.
