### ISSUE TITLE
MS Teams does not clear OOO reply from Outlook

### ISSUE THREAD

**Issue by lokeshb31** [MicrosoftDocs/msteams-docs#4167]
Hi,

I setup Out Of office reply for 5 hours yesterday IST evening in Outlook which was immediately reflecting in MS Teams. However outlook was not showing OOO after 5 hours but it is still showing in MS Teams, it did not clear status. I tried reset status too but did not help.

Looks like this is a BUG.

**Comment by lokeshb31** [comment]
It disappeared just now.. i.e. after 12 hours, not sure how does it work.

**Comment by Prasad-MSFT** [comment]
Hi @lokeshb31 , We tried to repro this issue and can confirm that it worked fine at our end. The Microsoft Teams and Outlook OOF status is getting set at desired time and automatically getting removed after desired time. 
We are closing this issue as its resolved from your end as well. please feel free to re-open the issue if you need further help.
Thanks!
