### ISSUE TITLE
HTML being parsed and executed on message reply

### ISSUE THREAD

**Issue by alonbudker-vayyar** [MicrosoftDocs/msteams-docs#4171]
Hey guys,
It looks like replying to messages that contain HTML tags executes them.

[**edit**] This happens when using the mobile app's reply function on a message between people in a chat. Tested on an android device as the one replying, and on a Windows 10 PC running Teams version 1.4.00.22472

For instance, if I write:
> `<b>some text</b>`

It will show up exactly like that for me, but if someone **replies** to the message then in the quoted text it would show (for me) as:

> **some text**

To the replying party, it seems like it would just show up empty.
It works with styling but also with links and img tags.

I have not been able to gauge the scope of the issue, I assume that if it's just HTML then it's probably fine - but maybe an `<href>` tag with javascript could be more interesting to look at...

I have not seen this 'bug' posted earlier, but maybe I missed it - sorry if it's a duplicate.

**Comment by HunaidHanfee-MSFT** [comment]
Hello,
Is it related to replying with bot or doing from Teams Desktop client?
Please confirm.
Thanks

**Comment by alonbudker-vayyar** [comment]
Hey!
It happened in a chat between two people, one (sending the HTML) from desktop, and the other was replying from Android, using the reply function that is only available on mobile as far as I know.

**Comment by HunaidHanfee-MSFT** [comment]
Thanks for the reply. It seems like it is product related question so I am adding a teams-product  tag.
