### ISSUE TITLE
Teams stuck when changing from one account to another and back again

### ISSUE THREAD

**Issue by AmittaiShapira** [MicrosoftDocs/msteams-docs#4172]
I have 2 Teams account: one for my work, and one for school (a guest account with my work e-mail).
I used to be able to switch between those 2 accounts without an issue, but in the last couple of days when I switch from my work account to my school account and back to my work account, I see the following error:
![image](https://user-images.githubusercontent.com/59568557/133457882-c7c4b475-6422-44df-b701-238d771b5018.png)

Logging out of Teams and logging in back fixes this issue
Teams version is:
You have Microsoft Teams Version 1.4.00.22472 (64-bit). It was last updated on 8/30/2021.

**Comment by HunaidHanfee-MSFT** [comment]
This is product related issue. Please follow one of these link:

For Microsoft Teams product issues/failures your tenant Admin can reach out to [Microsoft 365 Product Support](https://docs.microsoft.com/en-us/microsoft-365/admin/contact-support-for-business-products?view=o365-worldwide&tabs=online).
For general questions about Microsoft Teams please post your question on [Microsoft Teams Community](https://answers.microsoft.com/en-us/msteams/forum).
