### ISSUE TITLE
This statement needs clarification

### ISSUE THREAD

**Issue by aosolis** [MicrosoftDocs/msteams-docs#4173]
![image](https://user-images.githubusercontent.com/767208/133532373-6f45df2a-71ba-4d51-8bc6-39594c834fbb.png)

> Your app manifest specifies the places in which you want the apps to appear. The context field is used for this purpose. It is also the part of a share-tray experience, subject to specified design guidelines.

What does this mean? "It is also the part of a share-tray experience, subject to specified design guidelines"
Does "it" refer to "app manifest" or "context field"? Either option doesn't quite make sense-- what does it mean for app manifest or context field to be "part of a share-tray experience", much less to be subject to design guidelines?
I suggest we rephrase this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33fae5e3-2d98-381c-1b16-82c0acc6f716
* Version Independent ID: 6124f090-bdb7-c575-2614-60ec85a947b9
* Content: [Unified meetings apps - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/meeting-app-extensibility?tabs=desktop)
* Content Source: [msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by v-chetsh** [comment]
@aosolis - Thanks for your feedback.
We will check on it and redirect it to documentation team accordingly..
