### ISSUE TITLE
Auth flow hangs on Teams desktop app

### ISSUE THREAD

**Issue by BradP99** [MicrosoftDocs/msteams-docs#4177]
On some users systems our app hangs in the auth popup when using the desktop app on windows. It works find in the browsers as well as the mobile apps. Also if you popup our app in the desktop app it works fine. See our code snippets below.

The getContext call in AuthStart never returns when called. Note this is a page opened in a popup when called via the code below. This all works fine when run in the browser but fails in the desktop app.

Opens auth popup:
function getToken() {
  return new Promise((resolve, reject) => {
    microsoftTeams.authentication.authenticate({
      url: window.location.origin + '/Auth/Start',
      width: 600,
      height: 535,
      successCallback: (result) => {
        resolve(result);
      },
      failureCallback: (reason) => {
        $('#loginBtn').show();
        console.log('Auth/Start failed for ' + reason);
        reject(reason);
      },
    });
  });
}

Code in AuthStart:
            microsoftTeams.initialize();
            // Get the tab context, and use the information to navigate to Azure AD login page
            microsoftTeams.getContext(function (context) {
                // Generate random state string and store it, so we can verify it in the callback
                const state = '@ViewBag.State';
                localStorage.setItem("simple.state", state);
                localStorage.removeItem("simple.error");
                // See https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-v2-protocols-implicit
                // for documentation on these query parameters
                let queryParams = {
                    client_id: clientId,
                    response_type: "id_token token",
                    response_mode: "fragment",
                    scope: '@ViewBag.GraphApiScopes',
                    redirect_uri: window.location.origin + "/Auth/End",
                    nonce: '@ViewBag.Nonce',
                    state: state,
                    // login_hint pre-fills the username/email address field of the sign in page for the user,
                    // if you know their username ahead of time.
                    login_hint: context.upn
                };
                // Go to the AzureAD authorization endpoint
                let authorizeEndpoint = "https://login.microsoftonline.com/" + context.tid + "/oauth2/v2.0/authorize?" + toQueryString(queryParams);
                window.location.assign(authorizeEndpoint);
            });

**Comment by Prasad-MSFT** [comment]
Hi @BradP99, Could you please confirm if you are using the latest version? If the issue is happening with latest version please try to downgrade your Teams version.
https://microsoft-teams.en.uptodown.com/windows/versions
That's one place that has an archive of older versions, install one of them & check

**Comment by pdl5p** [comment]
I've experienced this issue as well starting with the most recent desktop update 1.4.00.22976. It appears that the popup window is blocked from loading the auth start url, as it just displays a blank popup window. 

Previous version that I have access to in a VM (v1.4.00.22472) works ok.

Affects custom teams apps that auth using implicit flow. Apps that I've updated to use SSO work ok.

Sample app can be used to reproduce issue
https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/app-complete-sample/nodejs

**Comment by Prasad-MSFT** [comment]
@pdl5p ,We have raised an internal bug for it and engineering team is looking into it.
We do not have exact ETA to share but we are tracking it closely.

**Comment by pdl5p** [comment]
Issue still persists with my latest update 1.4.00.26376 updated on Sept 26.

**Comment by BradP99** [comment]
I am still experiencing this issue on the latest Windows 11 release and Teams Desktop release. Desktop app hangs, if you click the arrow to open in a separate window it works fine. Works fine in all browsers too.

**Comment by HunaidHanfee-MSFT** [comment]
Am not sure if this help but can you give it a try by calling microsoftTeams.initialize() before calling authenticate method? 

```
        microsoftTeams.initialize();
        microsoftTeams.authentication.authenticate({....});
```

**Comment by BradP99** [comment]
The first thing I do is call initialize at the top of the js file so adding another initialize won't really do much. Plus it's hanging on the popup called from authenticate not the call to authenticate itself.

**Comment by HunaidHanfee-MSFT** [comment]
So it's just its getting hanged when you click on button that calls authenticate method? 
And it is working when opened from browser, also even when you click ![image](https://user-images.githubusercontent.com/64194049/148216630-1ed4115c-9daf-4a55-8031-6a90d6803be1.png) on this one and calls authenticate. Only issue is with Teams Desktop client right?

**Comment by HunaidHanfee-MSFT** [comment]
Hello @BradP99,
We have deployed an app where we have implemented this functionality. 
When you will add this the tab in Teams team, configure page is having two buttons 
![image](https://user-images.githubusercontent.com/64194049/148371520-88055b4f-c0c7-4388-8411-95ec38d2049b.png)

Please select _Set signin_ then click on save. Now, once the tab is open you will see a button

**Comment by HunaidHanfee-MSFT** [comment]
Hello @BradP99,
We have deployed an app where we have implemented this functionality.
When you will add the tab in Teams team, configure page will see two buttons
![image](https://user-images.githubusercontent.com/64194049/148375332-f5b68e1a-f9db-4d9f-9afb-bda678da0ded.png)


Please select _Set signin_ then click on save. Now, once the tab is open you will see a button
![image](https://user-images.githubusercontent.com/64194049/148371884-0b8492bf-f828-4530-9deb-4992bb0d65f2.png)

here the code that will execute when you click on it-
```
microsoftTeams.initialize();
        console.log("SignIn start")
        microsoftTeams.authentication.authenticate({
            url: window.location.origin + "/signin-simple-start",
            successCallback: () => {
                history.push("/navigateDomain");
            },
            failureCallback: (reason) => {
                alert(reason);
                history.push("/errorpage");
            }
});
```

Once you are succesfully signed in - We have added two button in the last authenticate step, one to `getContext` and alert the current tenant Id and other to call `notifySuccess`
![image](https://user-images.githubusercontent.com/64194049/148372423-9ffc2dcf-8e79-42a5-9db0-17157047a8c2.png)

code that is written at end of the step - 
```
useEffect(() => {
        microsoftTeams.initialize();
        const hashParams: any = getHashParameters();
        if (hashParams["error"]) {
            // Authentication/authorization failed
            alert("notifyFailure gets called -- " + hashParams["error"]);
            microsoftTeams.authentication.notifyFailure(hashParams["error"]);
        } else if (hashParams["id_token"]) {
            // Success
            if (hashParams["access_token"]) {
                localStorage.setItem("auth.result", JSON.stringify({
                    accessToken: hashParams["access_token"]
                }));
            }
            
        } else {
            // Unexpected condition: hash does not contain error or access_token parameter            
            alert("notifyFailure gets called -- Unknown error ");
            microsoftTeams.authentication.notifyFailure("UnexpectedFailure");
        }
    }, [props.location]);

    const callContext = () => {
        microsoftTeams.initialize(() => {
            microsoftTeams.getContext(context => {
                alert(context.tid);
            })
        })
    }

    const callNotifySuccess = () => {
        alert("notifySuccess gets called");
        microsoftTeams.authentication.notifySuccess("TEST");
    }

    return (
        <>
            <div>
                <Text content="Click on it to call getContext and see current tenant Id." />
                <div><Button content="Call getContext" onClick={() => { callContext() }} /></div>
            </div>
            <div>
                <Text content="Call notifySuccess." />
                <div><Button content="Call notifySuccess" onClick={() => { callNotifySuccess() }} /></div>
            </div>
        </>
    );
```

Click on notifySuccess to close the popup and redirect to page.

Please try it your end and let us know if you facing even with our app.

Thanks

**Comment by HunaidHanfee-MSFT** [comment]
@BradP99 we are not having repro for this at our end. Can you try checking if updates available and try to update and see it's still happening?
