### ISSUE TITLE
Link related with setting up a custom web hooks for MS Teams not working

### ISSUE THREAD

**Issue by Daniel-Krzyczkowski** [MicrosoftDocs/msteams-docs#418]
Link:
https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/connectors#setting-up-a-custom-incoming-webhook
displays wrong page - "page not found". 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cbdb8216-60c7-a0a1-7eb6-02d42d783292
* Version Independent ID: 77a75dd2-6f45-bc76-b968-0cf58c427ef5
* Content: [Requested page cannot be found. - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/connectors#setting-up-a-custom-incoming-webhook)
* Content Source: [msteams-platform/404.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/404.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Wajeed-msft** [comment]
@Daniel-Krzyczkowski - Could you please provide link for the documentation page where this is linked from? Link in [Setting up a custom incoming webhook](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/connectors/connectors-using#setting-up-a-custom-incoming-webhook) in [connectors using](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/connectors/connectors-using) section is working. Screenshot would help a lot.

**Comment by Daniel-Krzyczkowski** [comment]
Sure, please see below screenshot. This is from the App Center. In the section for web hooks there is a link under Microsoft Teams that looks like this:
https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/connectors#setting-up-a-custom-incoming-webhook
and it is not redirecting to the correct page.
![webhooks](https://user-images.githubusercontent.com/15244422/51971357-3deb8a00-2479-11e9-90fa-70ba606380b6.PNG)

**Comment by clearab** [comment]
Should be good now, thanks for letting us know.
