### ISSUE TITLE
Lack of very basic functionality that exists in all Chat service APIs

### ISSUE THREAD

**Issue by leonidbelkind** [MicrosoftDocs/msteams-docs#4184]
[Enter feedback here]
Dear writers of this documentation and Microsoft Teams product owners in general. The fact that your messaging solution (and that's what Microsoft Teams, in the context of bots, is) doesn't allow to "find a user by email" and then send them a direct message is absolutely outrageous. This is a very basic functionality in EVERY other messaging solution that supports bots. I appreciate the fact that you are concerned about the well-being of the users (not being spammed), but I suggest leaving this to the Enterprise Teams Administrators to decide.
It seems that your product lacks the basic understanding and support for modern Chat-Ops culture, that is prevalent across engineering-driven organizations worldwide. Wake UP! People receive notifications in chat today about myriads of events (Your build has failed, Your device is non-compliant, Your user account has been suspended, You need to punch in for your day off, You need to order your lunch, Your security certification is up,.... .the list goes on and on). The fact that your API requires the user to contact the bot first (otherwise you need to pull a "roster", that may contain thousands of users), shows a very fundamental misunderstanding of what bots are used for today in the modern organization.
Please pay attention to this comment. I am willing to elaborate more on the point, to show you APIs of the other similar solutions and to prove how fundamental the ability to send a proactive message to a user by a simple ID/email/... is.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b6940fc-c82e-4ef1-c913-976ede8a9d3f
* Version Independent ID: cbec2989-ba19-4046-21a1-72e2dca67f4d
* Content: [Proactive messages - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bot-conversations/bots-conv-proactive#best-practices-for-proactive-messaging)
* Content Source: [msteams-platform/resources/bot-v3/bot-conversations/bots-conv-proactive.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/resources/bot-v3/bot-conversations/bots-conv-proactive.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by v-chetsh** [comment]
@ojasvichoudhary - Could you please share the updates on this issue?

**Comment by ojasvichoudhary** [comment]
Hey @leonidbelkind, could send us an email: microsoftteamsdev@microsoft.com. If you've got some-time I'd like to meet briefly and chat more. You are right that we have restrictions around this scenario (app must be personally installed by user, IT admin or installed in a team/group chat the user is a part of) to prevent spam.

We do have Microsoft Graph API's that let you install your bot and send proactive messages to users inside a tenant. These do require admin approval but require no action on part of the user to engage with the bot: 
https://docs.microsoft.com/en-us/microsoftteams/platform/graph-api/proactive-bots-and-messages/graph-proactive-bots-and-messages?context=graph/context

@v-chetsh - Please route this to me when you get this mail. Thanks!

 fyi @siduppal

**Comment by v-chetsh** [comment]
@ojasvichoudhary - We got a mail from Leonid Belkind, so have forwarded to you.
Could you please check on it.
