### ISSUE TITLE
Sample full manifest has wrong structure.

### ISSUE THREAD

**Issue by gnanasuriyan-gnanaoli** [MicrosoftDocs/msteams-docs#4185]
`composeExtensions` section of the sample manifest has `taskInfo` attribute present in the wrong place. `taskInfo` should be present inside each command

https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema#sample-full-manifest

![image](https://user-images.githubusercontent.com/31096146/133959361-c315258d-a686-4867-a8cb-72909077634c.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f94a488-d636-92b3-21eb-c88744c8f272
* Version Independent ID: 7b3413f4-9ade-accf-5cb2-83fead11a32a
* Content: [Manifest schema reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema#packagename)
* Content Source: [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/resources/schema/manifest-schema.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by gnanasuriyan-gnanaoli** [comment]
Think this is the relevant file which has incorrect structure.

https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/resources/schema/manifest-schema.md

**Comment by Meghana-MSFT** [comment]
Please change the structure of composeExtensions in the documentation.

```
"composeExtensions": [
    {
      "canUpdateConfiguration": true,
      "botId": "%MICROSOFT-APP-ID-REGISTERED-WITH-BOT-FRAMEWORK%",
      "commands": [
        {
          "id": "exampleCmd1",
          "title": "Example Command",
          "type": "query",
          "context": [
            "compose",
            "commandBox"
          ],
          "description": "Command Description; e.g., Search on the web",
          "initialRun": true,
          "fetchTask": false,
          "parameters": [
            {
              "name": "keyword",
              "title": "Search keywords",
              "inputType": "text",
              "description": "Enter the keywords to search for",
              "value": "Initial value for the parameter",
              "choices": [
                {
                  "title": "Title of the choice",
                  "value": "Value of the choice"
                }
              ]
            }
          ],
		  "taskInfo": {
			"title": "Initial dialog title",
			"width": "Dialog width",
			"height": "Dialog height",
			"url": "Initial webview URL"
			}
        },
        {
          "id": "exampleCmd2",
          "title": "Example Command 2",
          "type": "action",
          "context": [
            "message"
          ],
          "description": "Command Description; e.g., Search for a customer",
          "initialRun": true,
          "fetchTask": true,
          "parameters": [
            {
              "name": "custinfo",
              "title": "Customer name",
              "description": "Enter a customer name",
              "inputType": "text"
            }
          ],
		  "taskInfo": {
			"title": "Initial dialog title",
			"width": "Dialog width",
			"height": "Dialog height",
			"url": "Initial webview URL"
			}
        }
      ],
      "messageHandlers": [
        {
          "type": "link",
          "value": {
            "domains": [
              "mysite.someplace.com",
              "othersite.someplace.com"
            ]
          }
        }
      ]
    }
  ],
```
