### ISSUE TITLE
Images are blurry

### ISSUE THREAD

**Issue by gnanasuriyan-gnanaoli** [MicrosoftDocs/msteams-docs#4188]
Hi, The screenshots in this page are blurry. For example.

This screenshot which gives the difference between a Command Box, Compose Message Area, Message is blurry and not clear enough to read.
![image](https://user-images.githubusercontent.com/31096146/134038733-db0a27d8-a0d6-40f5-b4ab-a16234c65997.png)

Thanks
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: efcdf768-1513-2249-b344-bf38ef64c70d
* Version Independent ID: 415b5d57-2d41-9540-55a7-2a33a4315e37
* Content: [Define messaging extension action commands - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/action-commands/define-action-command)
* Content Source: [msteams-platform/messaging-extensions/how-to/action-commands/define-action-command.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/messaging-extensions/how-to/action-commands/define-action-command.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **anclear**

**Comment by Prasad-MSFT** [comment]
Redirecting to documentation team

**Comment by v-vidhyarani** [comment]
Hi @gnanasuriyan-gnanaoli,

Can you please provide the clear screenshots to update [Issue 4188](https://github.com/MicrosoftDocs/msteams-docs/issues/4188#) blur screens.

**Comment by gnanasuriyan-gnanaoli** [comment]
Hi @v-vidhyarani I will share in some time.

**Comment by gnanasuriyan-gnanaoli** [comment]
@v-vidhyarani 

![image](https://user-images.githubusercontent.com/31096146/134334569-5ea1a090-5825-4046-b65d-a5f44d1c198a.png)

**Comment by v-vidhyarani** [comment]
@gnanasuriyan-gnanaoli,

Can you share me the screenshot without any highlights.

**Comment by v-vidhyarani** [comment]
@gnanasuriyan-gnanaoli 
The shared image is still blur and more actions tab is missing. Please share the appropriate image.

**Comment by gnanasuriyan-gnanaoli** [comment]
@v-vidhyarani 

If the image attached to the comment is blurry. 

I have uploaded the source file here, which you can download(https://github.com/gnanasuriyan-gnanaoli/gnanasuriyan-gnanaoli.github.io/blob/master/invoke.jpg)


![invoke](https://user-images.githubusercontent.com/31096146/134443046-895924ca-bc04-463e-8944-78f2d98398c0.jpg)

**Comment by v-vidhyarani** [comment]
@gnanasuriyan-gnanaoli,
Even after downloading the image, the screen is still blur. Is there any other way to get a clear screen.
