### ISSUE TITLE
[Rendering] Input.Text missing spell-check options

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#4189]
Copied bug from: https://github.com/microsoft/AdaptiveCards/issues/6364 

**Details from original post:**
### Target Platforms

NodeJS

### SDK Version

1.2

### Application Name

Microsoft Teams

### Problem Description

I'm unsure if this is an adaptive card issue or a Teams issue, but when using an Input.Text element, misspelled text is underlined, though on right-clicking, no spell-check options appear.

### Screenshots

![image](https://user-images.githubusercontent.com/13111149/133686380-8ca7d581-0270-4f18-b967-1eed582e96b0.png)

### Card JSON

```JSON
{
    "type": "Input.Text",
    "style": "text",
    "isMultiline": true,
    "id": "commentVal",
    "value": "{comment}"
}
```

### Sample Code

_No response_---
#### Document Details

⚠ *Do not edit this section.It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Cards reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **surbhigupta12**

**Comment by Prithvi-MSFT** [comment]
Hi @Kitzeller,
We have raised a bug for this and concerned team is looking into it.


Thanks

**Comment by v-chetsh** [comment]
@kitzeller -  This is kind of feature request and engineering team is looking into it.
We do not have exact ETA to share but in coming months it will release based on the features priority.

**Comment by v-chetsh** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.
