### ISSUE TITLE
Errors in Json examples

### ISSUE THREAD

**Issue by Navega** [MicrosoftDocs/msteams-docs#419]
I found some problems while I was developing with this doc:

- The action command for “fecthTask” require one parameter, at least, to have a good manifest. Ref: https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/messaging-extensions/create-extensions#complete-app-manifest-example

- The example response with a responsive card is wrong because into “card” the fields “content” and “contentType” are required before of “body” field.  Ref: https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/messaging-extensions/create-extensions#dynamic-input-using-an-adaptive-card

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aaa0ea75-7363-3ef5-39df-ad07c493c118
* Version Independent ID: ab9a2a6e-e2ca-828f-cd8b-bd9ff98411ab
* Content: [Action-based messaging extensions - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/messaging-extensions/create-extensions#complete-app-manifest-example)
* Content Source: [msteams-platform/concepts/messaging-extensions/create-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/messaging-extensions/create-extensions.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Wajeed-msft** [comment]
Thanks for reporting this. 
1. We are working on updating schema which will have support for actions. All these validation issues will go away.
2. The JSON provide in the sample is correct. You can use [message card playground](https://messagecardplayground.azurewebsites.net) or [Teams App Studio card editor](https://docs.microsoft.com/en-us/microsoftteams/platform/get-started/get-started-app-studio#card-editor) to test the card. Please let us know if you are facing any issue with the JSON.

**Comment by Navega** [comment]
Thanks for the quick answer.

1. Ok, it makes sense.
2. I couldn't make to work with that JSON, the right JSON that I used is:
`
{
    "task": {
        "value": {
            "card": {
                "contentType": "application/vnd.microsoft.card.adaptive",
                "content": {
                    "type": "AdaptiveCard",
                    "body": [
                        {
                            "type": "TextBlock",
                            "text": "Please enter the following information:"
                        },
                        {
                            "type": "TextBlock",
                            "text": "Name"
                        },
                        {
                            "type": "Input.Text",
                            "spacing": "None",
                            "title": "New Input.Toggle",
                            "placeholder": "Placeholder text"
                        },
                        {
                            "type": "TextBlock",
                            "text": "Date of birth"
                        },
                        {
                            "type": "Input.Date",
                            "spacing": "None",
                            "title": "New Input.Toggle"
                        }
                    ],
                    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
                    "version": "1.0"
                 }
            }
        },
        "type": "continue"
    }
}
`

With the fields "content" and "contentType" for the adaptive card.

**Comment by Wajeed-msft** [comment]
@Navega - You are right. The schema given in the docs works only with Tab. We will get it fixed.

**Comment by pablodiazgutierrez** [comment]
We are having trouble loading our manifest using App Studio, as well as submitting it to the store due to manifest validation errors. Despite that, we can side-load the manifest directly into Teams, and it works perfectly, so we think this might be a problem with the validaton parser not accepting these new fields. Could you please advise?

Here is a capture of the error message we get on validation: https://s3.amazonaws.com/prod_pm_files/cf/66/1a/fc/4a/ec/86/90/Screen_Shot_2019-02-12_at_2.09.28_PM.png

...and we're sent to "Learn more" in https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema which indeed does not support the mentioned properties "type", "inputType" and "fetchTask".

**Comment by pablodiazgutierrez** [comment]
Sorry, will open a separate issue :)
