### ISSUE TITLE
accentColor is listed as optional but the manifest has it marked as required

### ISSUE THREAD

**Issue by marcopelegrini** [MicrosoftDocs/msteams-docs#4192]
accentColor is listed as optional but the manifest has it marked as required

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f94a488-d636-92b3-21eb-c88744c8f272
* Version Independent ID: 7b3413f4-9ade-accf-5cb2-83fead11a32a
* Content: [Manifest schema reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema#feedback)
* Content Source: [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/resources/schema/manifest-schema.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Prasad-MSFT** [comment]
Although in documentation , its mentioned as optional and so as in App Studio (Attaching Screenshot).
![image](https://user-images.githubusercontent.com/62237649/134335938-79c78270-9853-4ab9-87f1-f64daf028200.png)
But when you try to add the manifest in App Studio, its giving error
![image](https://user-images.githubusercontent.com/62237649/134336113-0b4e48f7-2fa9-451b-a60c-fcc56238958e.png)
