### ISSUE TITLE
Request size limits in incoming webhooks

### ISSUE THREAD

**Issue by bagdenia** [MicrosoftDocs/msteams-docs#4213]
We want to use events batches to avoid risk of exceeding rate limits, but have some doubts about result request size. Do you have also any limits in sense of request size too? Didn't find information about this yet. Thanks in advance!

**Comment by Prasad-MSFT** [comment]
@bagdenia ,Currently message size limit is 28 kb. 
https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams#teams-and-channels
