### ISSUE TITLE
Explicit JIT install button is not documented here

### ISSUE THREAD

**Issue by aosolis** [MicrosoftDocs/msteams-docs#4214]
"v3" doc has it: https://docs.microsoft.com/en-us/microsoftteams/platform/resources/messaging-extension-v3/create-extensions?tabs=typescript#request-to-install-your-conversational-bot

This needs to be documented here as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fb0c2d8-f880-c260-d0be-6b9467e47f8c
* Version Independent ID: 7820ffc9-5260-c818-f5fb-672801a67d00
* Content: [Respond to the task module submit action - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/action-commands/respond-to-task-module-submit?tabs=dotnet%2Cdotnet-1)
* Content Source: [msteams-platform/messaging-extensions/how-to/action-commands/respond-to-task-module-submit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/messaging-extensions/how-to/action-commands/respond-to-task-module-submit.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **anclear**

**Comment by v-chetsh** [comment]
This issue is related to doc-enhancement so redirecting it.

**Comment by Wajeed-msft** [comment]
@asolis - This is documented in [Respond to the fetchTask](https://docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/action-commands/create-task-module?tabs=dotnet#request-to-install-your-conversational-bot) documentation. Should we move this section to [Respond to the task module submit action](https://docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/action-commands/respond-to-task-module-submit?tabs=dotnet%2Cdotnet-1)?
