### ISSUE TITLE
contentUrl is Mandatory in manifest schema

### ISSUE THREAD

**Issue by PeterGreenSamanage** [MicrosoftDocs/msteams-docs#4223]
In this page, the example manifest is missing the 'contentUrl', which is shown as mandatory in the 'manifest schema'.
It's unclear what needs to be the value 'contentUrl' and where it needs to be pointed if I want to use an Adaptive Card.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a3a4238-5916-eff7-25cf-bff2362ab246
* Version Independent ID: 12048d7d-de6a-43d8-44d5-7ab1be9972a2
* Content: [Build Adaptive Card Tabs - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/build-adaptive-card-tabs#fetch-adaptive-card-to-render-to-a-tab)
* Content Source: [msteams-platform/tabs/how-to/build-adaptive-card-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tabs/how-to/build-adaptive-card-tabs.md)
* Product: **msteams**
* GitHub Login: @KirtiPereira
* Microsoft Alias: **surbhigupta**

**Comment by Prasad-MSFT** [comment]
'contentUrl' is the https:// URL that points to the entity UI to be displayed in the Teams canvas.
In case of building tabs with Adaptive card you can provide the 'contentBotId' property with the botId that the Adaptive Card tab must communicate with.

**Comment by PeterGreenSamanage** [comment]
When I only provide the ‘contentBotId’ (I exclude the contentUrl) - I get an error when installing the Manifest in the Teams App Studio.
“Manifest parsing has failed.”
“staticTabs[1].contentUrl | String "" does not match regex pattern "^[Hh][Tt][Tt][Pp][Ss]?://".”

How can I get around that ?




From: Prasad-MSFT ***@***.***>
Date: Monday, 27 September 2021 at 10:09
To: MicrosoftDocs/msteams-docs ***@***.***>
Cc: Green, Peter (Samanage) ***@***.***>, Author ***@***.***>
Subject: Re: [MicrosoftDocs/msteams-docs] contentUrl is Mandatory in manifest schema (#4223)

'contentUrl' is the https:// URL that points to the entity UI to be displayed in the Teams canvas.
In case of building tabs with Adaptive card you can provide the 'contentBotId' property with the botId that the Adaptive Card tab must communicate with.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fmsteams-docs%2Fissues%2F4223%23issuecomment-927592944&data=04%7C01%7Cpeter.green%40solarwinds.com%7C9df1be5fc78c4029423408d98185c95a%7C83f3a6e104704e13984f16a25372914c%7C0%7C0%7C637683233875627047%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Kic%2BaWX28T2ko1yuYHdDbZAMdE0SKngS4UgKeq3B5D8%3D&reserved=0>, or unsubscribe<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAFAMFLLDYDNRDPFJYN4Y2H3UEAKDPANCNFSM5EYX5EZA&data=04%7C01%7Cpeter.green%40solarwinds.com%7C9df1be5fc78c4029423408d98185c95a%7C83f3a6e104704e13984f16a25372914c%7C0%7C0%7C637683233875637046%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=SV7AFbYeZjeYiQGi0HMbyQpAp5waWzje7jiNPX3FLxY%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cpeter.green%40solarwinds.com%7C9df1be5fc78c4029423408d98185c95a%7C83f3a6e104704e13984f16a25372914c%7C0%7C0%7C637683233875637046%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=fSBSNW4F9%2BvTqe%2BpVP6AeVS1WGs%2BBMwhKjL86agma7o%3D&reserved=0> or Android<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cpeter.green%40solarwinds.com%7C9df1be5fc78c4029423408d98185c95a%7C83f3a6e104704e13984f16a25372914c%7C0%7C0%7C637683233875647038%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=4faUQVENArYJuOUTl6jhzS7gWXSvSUrxiNfHPakBOdg%3D&reserved=0>.

**Comment by Prasad-MSFT** [comment]
Static tab definitions must contain either a 'contentBotId', specifying an Adaptive Card tab or a contentUrl, specifying a typical hosted web content tab experience.

Please check your manifest version as the 'contentBotId' property is currently available in manifest version 1.9 or later.

**Comment by PeterGreenSamanage** [comment]
Is this ok to contact this email for help?
If not, could you point me to the correct place please ?

I’m using version 1.9
I only have the contentBotId in my Manifest, and I’m getting a parse error – “staticTabs[1].contentUrl | String "" does not match regex pattern "^[Hh][Tt][Tt][Pp][Ss]?://".”.
Am I missing something else ?

This is my manifest (only removed id’s):

{
    "$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.9/MicrosoftTeams.schema.json",
    "manifestVersion": "1.9",
    "version": "0.1.0",
    "showLoadingIndicator": true,
    "id": "myRealID",
    "packageName": "com.swsd.dev",
    "developer": {
        "name": "Solarwinds",
        "websiteUrl": "https://www.solarwinds.com/",
        "privacyUrl": "https://www.solarwinds.com/legal/privacy",
        "termsOfUseUrl": "https://www.solarwinds.com/legal/privacy"
    },
    "icons": {
        "color": "color.png",
        "outline": "outline.png"
    },
    "name": {
        "short": "(Local)Solarwinds Service Desk",
        "full": "Solarwinds Service Desk"
    },
    "description": {
        "short": "Microsoft Teams Bot for SWSD users",
        "full": "The SWSD Microsoft Teams Bot allow users to log in to their SWSD account and create incidents"
    },
    "accentColor": "#FFFFFF",
    "staticTabs": [
        {
            "entityId": "conversations",
            "scopes": [
                "personal"
            ]
        },
        {
            "contentBotId": "myBotID",
            "entityId": "serviceDeskTab",
            "name": "Service Desk",
            "scopes": [
                "personal"
            ]
        },
        {
            "entityId": "about",
            "scopes": [
                "personal"
            ]
        }
    ],
    "bots": [
        {
            "botId": "myBotID",
            "scopes": [
                "personal"
            ],
            "commandLists": [
                {
                    "scopes": [
                        "personal"
                    ],
                    "commands": [
                        {
                            "title": "Login",
                            "description": "Login"
                        },
                        {
                            "title": "Logout",
                            "description": "Logout"
                        },
                        {
                            "title": "Help",
                            "description": "Help"
                        },
                        {
                            "title": "Create Incident",
                            "description": "Create Incident"
                        },
                        {
                            "title": "View my open tickets",
                            "description": "View my open tickets"
                        }
                    ]
                }
            ],
            "supportsFiles": false,
            "isNotificationOnly": false
        }
    ],
    "permissions": [
        "identity",
        "messageTeamMembers"
    ],
    "validDomains": [
        "token.botframework.com"
    ]
}

Issue on app studio:
***@***.***
From: Prasad-MSFT ***@***.***>
Date: Monday, 27 September 2021 at 16:08
To: MicrosoftDocs/msteams-docs ***@***.***>
Cc: Green, Peter (Samanage) ***@***.***>, Mention ***@***.***>
Subject: Re: [MicrosoftDocs/msteams-docs] contentUrl is Mandatory in manifest schema (#4223)

Static tab definitions must contain either a 'contentBotId', specifying an Adaptive Card tab or a contentUrl, specifying a typical hosted web content tab experience.

Please check your manifest version as the 'contentBotId' property is currently available in manifest version 1.9 or later.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fmsteams-docs%2Fissues%2F4223%23issuecomment-927857241&data=04%7C01%7Cpeter.green%40solarwinds.com%7C19f8691b4b5c4fb18f1608d981b7d9af%7C83f3a6e104704e13984f16a25372914c%7C0%7C0%7C637683448902515613%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=r0WcLRC8C4otGmFumBcG53Zo5MR%2BiICHDEE6XLEYBU8%3D&reserved=0>, or unsubscribe<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAFAMFLK25M257SX3FQXD3B3UEBUDLANCNFSM5EYX5EZA&data=04%7C01%7Cpeter.green%40solarwinds.com%7C19f8691b4b5c4fb18f1608d981b7d9af%7C83f3a6e104704e13984f16a25372914c%7C0%7C0%7C637683448902525611%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=mT3aUgTnCizyiqgVq9XuY4u%2Bp1R6eVMvxmZneEt%2Bko0%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cpeter.green%40solarwinds.com%7C19f8691b4b5c4fb18f1608d981b7d9af%7C83f3a6e104704e13984f16a25372914c%7C0%7C0%7C637683448902525611%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=us1XPOJaPx1WHpn35Pq%2F13d82HXk9KP7VYM%2FxN7ZK9U%3D&reserved=0> or Android<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cpeter.green%40solarwinds.com%7C19f8691b4b5c4fb18f1608d981b7d9af%7C83f3a6e104704e13984f16a25372914c%7C0%7C0%7C637683448902535603%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Wh86w6yfYZCowJ9xclvfYl9Vwp6Q8z9VujJovZqndUU%3D&reserved=0>.

**Comment by Prasad-MSFT** [comment]
@PeterGreenSamanage 
I tried to validate the manifest which you provided and didn't get any error in App Studio
FYI, at first i got an error saying that manifest version can't be 0.1.0, so i changed it to 1.0.0 and it worked fine
![image](https://user-images.githubusercontent.com/62237649/135453710-f94cdc84-c0c0-4eee-aed3-015cc47a4f03.png)

**Comment by PeterGreenSamanage** [comment]
It also works for me under the Validation tab, the issue is in the Manifest editor tab, when importing and going to 'Test and Distribute', I get a parse error when clicking Install
Please see a video recording of the issue at: https://youtu.be/bBKaGpiKgLw

**Comment by Prasad-MSFT** [comment]
@PeterGreenSamanage , Could you please install the app by navigating to Apps > Upload a custom app. and check if it helps
![image](https://user-images.githubusercontent.com/62237649/135459427-5f2890a5-e5cf-4915-a7c3-2def9161ae5b.png)

**Comment by PeterGreenSamanage** [comment]
Yes, that helps.
Thank you very much
