### ISSUE TITLE
Which permissions are required for microsoftTeams.meeting.getMeetingDetails

### ISSUE THREAD

**Issue by abdulkareemnalband** [MicrosoftDocs/msteams-docs#4237]
`microsoftTeams.meeting.getMeetingDetails` fails with following error

```json
{
  "errorCode": 1000,
  "message": "App doesn't have sufficient permission to use this API"
}
```

What are those permissions and how to configure them.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ebc0e266-46df-3a7a-64c1-7065b73e71f5
* Version Independent ID: 02ead2e7-7a95-00ba-ef3f-1e026f0f96cf
* Content: [meeting module - Teams](https://docs.microsoft.com/en-us/javascript/api/@microsoft/teams-js/microsoftteams.meeting?view=msteams-client-js-latest)
* Content Source: [nodejs/docs-ref-autogen/@microsoft/teams-js/microsoftTeams.meeting.yml](https://github.com/OfficeDev/msteams-client-docs-ref-typescript/blob/live/nodejs/docs-ref-autogen/@microsoft/teams-js/microsoftTeams.meeting.yml)
* Product: **msteams**
* GitHub Login: @charlesprakash
* Microsoft Alias: **o365devx**

**Comment by Prasad-MSFT** [comment]
@abdulkareemnalband ,
One of the following permissions is required to fetch meeting details:
1. OnlineMeetingArtifact.Read.All,
2.  OnlineMeetings.Read.All, 
3. OnlineMeetings.ReadWrite.All
https://docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-1.0&tabs=javascript#request-1
Follow this link for more details:
https://docs.microsoft.com/en-us/graph/use-the-api

**Comment by Prasad-MSFT** [comment]
@abdulkareemnalband ,
This doc describes about meeting details API
https://docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/api-references?tabs=dotnet#meeting-details-api
FYI ,this feature is currently available for developer preview only.

**Comment by v-chetsh** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.
