### ISSUE TITLE
Problem reaching the app - error shown when navigating to bot personal app

### ISSUE THREAD

**Issue by siduppal** [MicrosoftDocs/msteams-docs#4249]
There is an ongoing issue in Teams that is causing some users to see an error ("There was a problem reaching the app") when navigating to the bot personal app from flyout. The fix has started rolling out to all users and is expected to finish rollout by early next week unless some unforeseen issues are encountered (ETA Oct 11).

Creating and pinning this issue for awareness.

Screenshot of the error:
![image](https://user-images.githubusercontent.com/7799064/135512344-1d217562-4d5c-4198-a229-e3abd7654277.png)

Note that the compose box is functional and the messages can be sent and received.

**Comment by embailie** [comment]
Suggested workarounds for this issue: utilizing the app in web browser or in mobile Teams client.

**Comment by mark3grahams** [comment]
same.

**Comment by amansani15** [comment]
Same here. Looking for the solution soon. Thank you

**Comment by dhamijac** [comment]
> There is an ongoing issue in Teams that is causing some users to see an error ("There was a problem reaching the app") when navigating to the bot personal app from flyout. The fix is expected to begin rolling out on October 4th and reach 100% by October 8th.
> 
> Creating and pinning this issue for awareness.
> 
> Screenshot of the error: ![image](https://user-images.githubusercontent.com/7799064/135512344-1d217562-4d5c-4198-a229-e3abd7654277.png)
> 
> Note that the compose box is functional and the messages can be sent and received.

Hello, is there any official Microsoft document or statement regarding this? There is no confirmation available anywhere about when the fix is available?

**Comment by dhamijac** [comment]
> Same here. Looking for the solution soon. Thank you

Do you know if there is any official Microsoft update on this? I don't think the correct updates are provided on this page

**Comment by mark3grahams** [comment]
I just opened a ticket.

**Comment by dhamijac** [comment]
> I just opened a ticket.

Do you have the ticket number from Microsoft

**Comment by mark3grahams** [comment]
I've only gotten to the part where they make me do all the work and do not read my ticket.

> Hi Mark, Hope you are doing well. My name is Chirag Dhamija and I am the support engineer from Microsoft 365 Support. I have assumed ownership of the case: **27776213**
> As per the description in the ticket, you are unable to connect to Teams and getting 'Unable to reach this app' error. If that is correct can you please provide the following details so I can get more information and better assist you on this ticket.
> 
> - When was the issue first reported?
> - How many users are affected or experiencing the issue?
> - Is this on a cloud environment or hybrid environment?
> - Are any other office apps giving the same error too?
> - Are you able to access Teams online and if it is just the desktop app having issues?
> - Has any troubleshooting been done so far?
> - At what point does the error come up, after signing or right after starting the app?

**Comment by AndreyS1** [comment]
Bug still here

**Comment by johnbyro** [comment]
> I've only gotten to the part where they make me do all the work and do not read my ticket.
> 
> > Hi Mark, Hope you are doing well. My name is Chirag Dhamija and I am the support engineer from Microsoft 365 Support. I have assumed ownership of the case: **27776213**
> > As per the description in the ticket, you are unable to connect to Teams and getting 'Unable to reach this app' error. If that is correct can you please provide the following details so I can get more information and better assist you on this ticket.
> > 
> > * When was the issue first reported?
> > * How many users are affected or experiencing the issue?
> > * Is this on a cloud environment or hybrid environment?
> > * Are any other office apps giving the same error too?
> > * Are you able to access Teams online and if it is just the desktop app having issues?
> > * Has any troubleshooting been done so far?
> > * At what point does the error come up, after signing or right after starting the app?

I dont blame them. The agents are doing their job and the best they can. They are providing us the information they have and can't do anything more. And as far these questions are concerned i don't see anything wrong with it, its their job to ask the questions to determine the root cause and if we submit a ticket we should be also ready to help them in order to receive the assistance.

**Comment by theogumilang** [comment]
I think we still got the problem, I already restarted my Teams Dekstop. but it just won't get away. Maybe in our country, the update is still not rolled up?  We are in SEA Region Indonesia.
![image](https://user-images.githubusercontent.com/29269601/136730687-6558907d-9d88-4f8a-a0d1-32b52bffcbde.png)

**Comment by v-chetsh** [comment]
@Bizjes - Thanks a lot for confirmation.

**Comment by vitaliishandra** [comment]
What should be the users actions after the fix will be applied? Update Teams client / Restart Teams or relogin? Or the issue should be gone without any extra actions?

**Comment by siduppal** [comment]
The fix has just finished rolling to 100% of production. Teams desktop client will automatically pull the latest build after a period of inactivity, but you can also try doing _Check for updates_.

Please do not hesitate to reach out to us here on GitHub if you encounter any other issues while developing and running your apps.

**Comment by rchardin** [comment]
Yeah, still not working.  Again, the error message is gone but the rendering is still messed up.  The two  happened at the same time so I assumed that they were related.   Do you have another tracker that we can follow the rendering fix?

**Comment by siduppal** [comment]
@rchardin , @mboywang can you please open new issues on GitHub with the behavior you are observing? If possible, please provide a sample JSON to speed up the investigation.

**Comment by Bizjes** [comment]
> @Bizjes - Microsoft Teams platform engineering team confirmed that fix is rolled out 100%. Could you please update your desktop client using "Check for updates" option? If you are still facing this issue please share your Teams client version.

We got confirmation that the fix was deployed. Our customer also confirmed this.
