### ISSUE TITLE
Request's header HMAC signature for testing with code example

### ISSUE THREAD

**Issue by Azothblader** [MicrosoftDocs/msteams-docs#425]
I think it will be clearer for the learner if the document/example provides the full request header and body for example testing.
 
e.g.  by using Example inbound message
 and id : "contoso" of 
SigningKeyDictionary 
of {"contoso", "vqF0En+Z0ucuRTM/01o2GuhMH3hKKk/N2bOmlM31zaA=" }.
you need to use value "HMAC 03TCao0i55H1eVKUusZOTZRjtvYTs+mO41mPL+R1e1U=" in the Authorization of request header.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06c224ae-1484-408c-d17a-e7e1ba07e78a
* Version Independent ID: fac8ff1e-a127-c12a-5304-9de39b1a15c6
* Content: [Outgoing webhooks - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/outgoingwebhook)
* Content Source: [msteams-platform/concepts/outgoingwebhook.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/outgoingwebhook.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Mahesh2516** [comment]
Content Source path given above is incorrect. Correct path to content source - **msteams-docs/msteams-platform/webhooks-and-connectors/how-to/add-outgoing-webhook.md**. This issue is updated and resolved.
