### ISSUE TITLE
[Rendering] Teams adaptative cards 1.4 can't display

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#4250]
Copied bug from: https://github.com/microsoft/AdaptiveCards/issues/6413 

**Details from original post:**
### Target Platforms

Other

### SDK Version

Latest

### Application Name

Microsoft Teams

### Problem Description

Microsoft updated documentation to state that Adaptive Card version 1.4 is now supported by Teams when sent via a bot.

When I attempt to send a sample JSON adaptive card via Power Automate to "Send an adaptative card via flow bot" the end user gets a message from flow bot, but the card simple says "We're sorry, this card couldn't be displayed".

Are adaptive cards 1.4 not supported by Flow Bot? 
Would be nice to be able to update a card after submission, which is why I am looking at version 1.4 

Any help understanding what is going on is greatly appreciated. :)

### Card JSON

```JSON
{
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "type": "AdaptiveCard",
  "version": "1.4",
  "body": [
    {
      "type": "TextBlock",
      "text": "Select from food options"
    },
    { 
      "type": "ActionSet",
      "actions": [
        {
          "type": "Action.Execute",
          "title": "Chicken",
          "verb": "food",
          "data": {
              "item": "chicken"
          }
        },
        {
          "type": "Action.Execute",
          "title": "Beef",
          "verb": "food",
          "data": {
              "item": "beef"
          }
        },
        {
          "type": "Action.Execute",
          "title": "Vegan",
          "verb": "food",
          "data": {
              "item": "vegan"
          }
        }
      ]
    }
  ]
}
```

### Sample Code

_No response_---
#### Document Details

⚠ *Do not edit this section.It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Cards reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **surbhigupta12**

**Comment by Prithvi-MSFT** [comment]
Hi @CDSFounder,
We are able to repro this issue. We have raised a bug for this and concerned team is looking into it.

Thanks

**Comment by CDSFounder** [comment]
Thank you @Prithvi-MSFT . Can you provide any expected ETA?

**Comment by Prithvi-MSFT** [comment]
Hi @CDSFounder ,
We do not have any ETA to share. We will update you on this thread.

Thanks

**Comment by CDSFounder** [comment]
Any update on this?

**Comment by Nivedipa-MSFT** [comment]
@CDSFounder - Concerned team is looking into it.Right now we don't have any ETA to share.If there is any update we will share you.

**Comment by jonathanbarton** [comment]
@Nivedipa-MSFT Same. ETA?

**Comment by Wajeed-msft** [comment]
@jonathanbarton - could you please try this using [Developer Portal](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/teams-developer-portal#use-tools-to-create-app-features) once and let me know if you still see this issue?

I just tried with 1.4 schema card and it's getting rendered fine.
<img width="296" alt="image" src="https://user-images.githubusercontent.com/31851992/147034741-cec90b08-7a9e-45a9-a747-7a11df7dc691.png">

**Comment by CDSFounder** [comment]
Is there any update on this? This has been an issue for a very long time now without any update. Thanks

**Comment by v-chetsh** [comment]
@CDSFounder - This bug has fixed internally but we do not have exact ETA to share for publicly release.
We will update you once we get any updates.

**Comment by Nivedipa-MSFT** [comment]
@CDSFounder - This bug has fixed now. Could you please check it once.

**Comment by gimpexe** [comment]
just tested AC v1.2, v1.3 and v1.4; sending from Power Automate to Teams using the Teams 'Post adaptive card and wait for a response' action.

appears to be working as expected.
thank you very much for fixing :)

**Comment by v-chetsh** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.

**Comment by CDSFounder** [comment]
It does render now, but it seems that the Universal Actions are not working? For example: How can you update a card via Power Automate? Or perhaps this can / should be done with an Azure function?

Are Universal Actions working for you @gimpexe or @v-chetsh ?

**Comment by v-chetsh** [comment]
@CDSFounder - I think, once the Card is posted in Teams & is user is trying to update or refresh it then it will work fine.
As per my knowledge, we can not directly update/refresh the card from Power Automate/Azure function.

Reference docs:
https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/work-with-universal-actions-for-adaptive-cards#code-samples

https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/work-with-universal-actions-for-adaptive-cards#code-samples
