### ISSUE TITLE
[Rendering][Teams][iOS] The markdown is not handled in the adaptive card when the card includes mention

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#4253]
Copied bug from: https://github.com/microsoft/AdaptiveCards/issues/6458 

**Details from original post:**
### Target Platforms

iOS

### SDK Version

1.0

### Application Name

Microsoft Teams

### Problem Description

The markdown is not handled in the adaptive card when the card includes mention.

But when the mention part is not in card JSON, markdown is processed appropriately.

### Screenshots

Adaptive card with mention within:
![Screenshot 2021-09-30 at 17 01 36](https://user-images.githubusercontent.com/9514958/135471657-2df16167-8920-410c-81a6-dfc56c84761c.png)

Adaptive card without mention within:
![Screenshot 2021-09-30 at 17 02 08](https://user-images.githubusercontent.com/9514958/135471666-29fc8871-ee80-4577-947d-7edd5d6b5490.png)

### Card JSON

```JSON
{
    "type": "AdaptiveCard",
    "body": [
        {
            "type": "Container",
            "items": [
                {
                    "type": "TextBlock",
                    "text": "Hello <at>Username</at>",
                    "wrap": true
                },
                {
                    "type": "TextBlock",
                    "text": "This is some text that includes markdown. **This part should be bold.** [This is a link](https://www.example.com)",
                    "wrap": true
                }
            ]
        }
    ],
    "msteams": {
        "entities": [
            {
                "type": "mention",
                "text": "<at>Username</at>",
                "mentioned": {
                    "id": "<userId>",
                    "name": "Username"
                }
            }
        ]
    },
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.0"
}
```

### Sample Code

_No response_---
#### Document Details

⚠ *Do not edit this section.It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Cards reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **surbhigupta12**

**Comment by Meghana-MSFT** [comment]
We are trying to repro this issue locally. We will get back to you.

**Comment by Meghana-MSFT** [comment]
@mpelekh - We are able to repro this issue. We have raised a bug and the concerned team is looking into it.

**Comment by Meghana-MSFT** [comment]
@mpelekh - This fix has been rolled out publicly. We have tested the fix and it is working fine.

**Comment by mpelekh** [comment]
@Meghana-MSFT  Thank you! It's working fine. The markdown is handled appropriately in the adaptive card on iOS devices when the card includes mention.

**Comment by Meghana-MSFT** [comment]
Thank you. We are closing this issue for now.
