### ISSUE TITLE
Taskmodule Error: Failed to load webview

### ISSUE THREAD

**Issue by aklaw09** [MicrosoftDocs/msteams-docs#4254]
### Sample information
teams-task-module
Node JS
Bot Framework

###Describe the bug
I am trying to use task module to display some website content from url. Works from desktop version, fails on mobile (android) with the above message.

###Error Screenshot
![image](https://user-images.githubusercontent.com/80107133/135572952-8b199299-0b23-435c-9c18-95da7dd48c75.png)

### Sample code

`response = <TaskModuleResponse>{ task: { type: "continue", value: <TaskModuleTaskInfo>{ title: "Title", url: "someUrl", fallbackUrl: "someUrl", }, }, }; return Promise.resolve(response);`

**Comment by HunaidHanfee-MSFT** [comment]
We are looking into this, I will get back to you soon
Thanks

**Comment by HunaidHanfee-MSFT** [comment]
Is the page you trying to open is public? If yes please share.

Also After you encounter issue goto Settings > Help and feedback > Send feedback - That should have logs in the attachment
Else please follow this link and let us know if you see any errors -[Dev tools for mobile](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/developer-tools)

**Comment by HunaidHanfee-MSFT** [comment]
Could you please try accessing it form Teams web client also?

**Comment by aklaw09** [comment]
I was trying to open google.com as a test but was unable to do it even after adding it to permissible domains. Was able to view the iframe earlier when I accessed from desktop app for an earlier version, but got a blank canvas now. Got the above screen for mobile app. 

Will update you after trying the dev tools in a while.

**Comment by aklaw09** [comment]
![Screenshot from 2021-10-04 10-52-47](https://user-images.githubusercontent.com/80107133/135798320-c4fd06ff-28cc-4406-812f-0c1857fa21d6.png)

Logs from Teams web client

**Comment by HunaidHanfee-MSFT** [comment]
Google is not iFramable, the website that you use must be iFramable. Please go through this [Prerequisite](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/tab-requirements).

Check the other YouTube(embed link) task module from sample if it is opening.

**Comment by aklaw09** [comment]
Hi, that was the issue. Adding the header resolved the issue, thanks. Closing the issue

**Comment by xerosanyam** [comment]
@aklaw09 adding the headers didn't fix it for me. i tried a bunch of things but still facing the same error. do let me know if you remember something.
thanks

cc @HunaidHanfee-MSFT

**Comment by ChetanSharma-msft** [comment]
Hello @xerosanyam - Thanks for reporting the issue.
Make sure you are using iFramable websites/domain while rendering those.

Also, Can you please share the repro steps/headers that you have tried so that we can investigate further on your issue?

**Comment by xerosanyam** [comment]
Hi @ChetanSharma-msft!
the website I am working with is `https://offers-in-india.web.app/tab`

Things I have tried:
1. I used the `iframeable` node package to test whether my website is iframeable - it said yes.
2. > Please follow this link and let us know if you see any errors -[Dev tools for mobile](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/developer-tools)

tried this, but got no message.
3. added the headers 
```
"headers": 
[
      {
        "key": "Content-Security-Policy",
        "value": "frame-ancestors teams.microsoft.com *.teams.microsoft.com *.skype.com"
      },
      {
        "key": "X-Frame-Options",
        "value": "ALLOW-FROM https://teams.microsoft.com/"
      }
]
```

**Comment by ChetanSharma-msft** [comment]
Hello @xerosanyam - Thanks for sharing the details.
We will check on it from our end and get back to you.

**Comment by xerosanyam** [comment]
sure @ChetanSharma-msft
awaiting reply. thanks!

**Comment by ChetanSharma-msft** [comment]
Hello @xerosanyam -  Have you configured your website domain in manifest?
Also, please share the console log or error, if any?

**Comment by xerosanyam** [comment]
> Have you configured your website domain in manifest?

@ChetanSharma-msft yes, I configured this domain.
Don't see any console logs/errors.

**Comment by ChetanSharma-msft** [comment]
We have tried your website URL and getting below error:

Refused to frame '[https://offers-in-india.web.app/'](https://offers-in-india.web.app/%27) because an ancestor violates the following Content Security Policy directive: "frame-ancestors teams.microsoft.com *.teams.microsoft.com *.skype.com".

Please go through this [Prerequisite](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/tab-requirements) and configure it accordingly.

Please let us know the updates once done.

**Comment by xerosanyam** [comment]
@ChetanSharma-msft can you please share the steps to reproduce this error? would be a great help, thanks

**Comment by ChetanSharma-msft** [comment]
**Here are the steps:**

1) Created a app with Task Module & added the Website URL as a  iframe inside Task Module like below:
<div id="embed-container">
        <iframe width="1000" height="700" src="[https://offers-in-india.web.app/tab"](https://offers-in-india.web.app/tab%22) frameborder="0" allow="autoplay; encrypted-media" allowfullscreen="allowfullscreen"></iframe>
    </div>
    
2) Open the Teams application with Task Module in Teams Web client (Browser client - teams.microsoft.com).
3) Open DevTools in Teams Web browser client via pressing F12 and open console.
4) Try to open Task Module and check in the Browser console for error

**Comment by xerosanyam** [comment]
The [Prerequisites](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/tab-requirements) asks us to add these 2 headers; which we have added.. 
<img width="1029" alt="image" src="https://user-images.githubusercontent.com/3167278/181227718-df157cfc-8131-413e-bfb7-3872645e7aeb.png">

**Comment by ChetanSharma-msft** [comment]
Can you please check and share your console error logs?

**Comment by ChetanSharma-msft** [comment]
> The [Prerequisites](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/tab-requirements) asks us to add these 2 headers; which we have added.. <img alt="image" width="1029" src="https://user-images.githubusercontent.com/3167278/181227718-df157cfc-8131-413e-bfb7-3872645e7aeb.png">

@xerosanyam - Please let us know the steps for adding these headers & where exactly you are adding these ?
Also, can you please share your manifest validDomains section or full manifest via hiding PII data , just to re-verify it ?

**Comment by xerosanyam** [comment]
@ChetanSharma-msft I am using firebase hosting to host my webapp, the steps to add headers are present here - https://firebase.google.com/docs/hosting/full-config#headers

the headers can be checked by `curl --head -i https://offers-in-india.web.app/tab`

> Also, can you please share your manifest validDomains section or full manifest via hiding PII data , just to re-verify it ?

sure, I'l reverify/ share in a while.

**Comment by xerosanyam** [comment]
@ChetanSharma-msft meanwhile, do you know a url that works fine inside ms teams? I would like to compare headers and try to figure out what I missed.

**Comment by xerosanyam** [comment]
>can you please share your manifest validDomains section
@ChetanSharma-msft 
```
"validDomains": [
    "*.web.app"
  ],
```

**Comment by ChetanSharma-msft** [comment]
> @ChetanSharma-msft meanwhile, do you know a url that works fine inside ms teams? I would like to compare headers and try to figure out what I missed.

@xerosanyam - We don't have any custom developed app handy & we have tested it using public URL's which is iframable like below:
https://www.youtube.com/

**Comment by ChetanSharma-msft** [comment]
@xerosanyam - Please let us know if your issue has resolved or need any help here?

**Comment by xerosanyam** [comment]
@ChetanSharma-msft I feel lost, since I still do not understand problem with my web app.

Things I am planning to try:
- updating my headers to include more domains
- reverting to manifest version 1.3 (as used by task module sample)

Thanks for your help.

**Comment by ChetanSharma-msft** [comment]
Hello @xerosanyam - Hope you are doing well !!
Can you please confirm whether you issue has resolved or still facing the same issue ?

**Comment by xerosanyam** [comment]
@ChetanSharma-msft still facing the issue :(

**Comment by ChetanSharma-msft** [comment]
Hello @xerosanyam - Your website it actually not iframable.
If you use a normal HTML <iframe> tag itself, it's failing:

Working with iframable websites like bing:
![image](https://user-images.githubusercontent.com/59052547/184819754-e33a3ece-dcab-417f-82ae-23686d4f7331.png)


But it's not working with your website tab like below:
![image](https://user-images.githubusercontent.com/59052547/184820060-fa5d816f-13b2-43e0-96a4-a14692a92a15.png)

So, looks like it's the issue with your website which is not iframable or not configured properly.

**Comment by xerosanyam** [comment]
if you can check the console 
<img width="1232" alt="image" src="https://user-images.githubusercontent.com/3167278/184832306-da0d7690-e169-4361-a23e-863fef2d3b2d.png">

this is expected right? we do not want our page to be iframeable anywhere.

**Comment by ChetanSharma-msft** [comment]
@xerosanyam - Is it working for your in Teams Desktop/Web clients ?

**Comment by xerosanyam** [comment]
@ChetanSharma-msft yes.

**Comment by ChetanSharma-msft** [comment]
@xerosanyam - Can you please share the error logs [Dev tools for mobile](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/developer-tools)

We will check and share the details with engineering team.

**Comment by xerosanyam** [comment]
@ChetanSharma-msft hey I couldn't see the logs for ms teams mobile app. I can see logs for chrome/edge browsers
I have enabled "developer preview" by going to about section in android teams app.

Does it work for you correctly?

**Comment by ChetanSharma-msft** [comment]
Hello @xerosanyam - Hope you have followed all the steps and please confirm whether you are able to see the checkboxes for Teams like below: 
![image](https://user-images.githubusercontent.com/59052547/186080872-ddc92499-7165-4534-8427-f62cc3d42b35.png)

**Comment by xerosanyam** [comment]
@ChetanSharma-msft yes, I proactively followed all the steps. Last time when I tried I didn't see any tab from teams I could see chrome/edge tabs. Will try this once again

**Comment by sayali-MSFT** [comment]
@xerosanyam -Did you get chance to check?
