### ISSUE TITLE
Notification-only bot turns into bidirectional bot after bot sends a proactive message

### ISSUE THREAD

**Issue by GauravES** [MicrosoftDocs/msteams-docs#4256]
[Enter feedback here]
A bot with the proper manifest file setting to convert it to notification only starts off with the input box disabled on the Teams client. Bot is in personal scope. 

However, the moment the bot sends a proactive message to the Teams's user, the input box becomes available again on the user client and user can type messages and send to the bot.

Is this expected behavior?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4abeb028-952d-f6f3-3775-d74da0e5cc12
* Version Independent ID: e7764a56-c0a1-11e0-fb02-bc0724ee6f7b
* Content: [Notification-only bots - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bots-notification-only)
* Content Source: [msteams-platform/resources/bot-v3/bots-notification-only.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/resources/bot-v3/bots-notification-only.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Prasad-MSFT** [comment]
Could you please share screenshots for this issue? so that we can repro from our end
