### ISSUE TITLE
"Task modules" link is broken

### ISSUE THREAD

**Issue by Grovespaz** [MicrosoftDocs/msteams-docs#426]
As the title says, Task modules gives a 404.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38f8810b-ac90-1258-a025-0fb37dc7f48d
* Version Independent ID: 807f4d11-6331-17db-ee65-a9f9ccca65da
* Content: [Concepts - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/concepts-overview)
* Content Source: [msteams-platform/concepts/concepts-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/concepts-overview.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by clearab** [comment]
Thanks for letting us know, I've correct this and it will go live with our next publish.
