### ISSUE TITLE
Use cases of a voice calling enabled bot #4120 #4183

### ISSUE THREAD

**Issue by sanketdixit2013** [MicrosoftDocs/msteams-docs#4263]
Hi @HunaidHanfee-MSFT ,

Thanks for your reply.

I would like to know if there is any way other than using App hosted media that we can achieve the voice calling for our scenario?

If yes can you please share detailed steps and samples on how to achieve it. If it's not possible can you please give a confirmation and tell us by when we can expect support for .Net Core bot applications?

Thanks!

_Originally posted by @sanketdixit2013 in https://github.com/MicrosoftDocs/msteams-docs/issues/4183#issuecomment-933150638_

**Comment by HunaidHanfee-MSFT** [comment]
Sorry, I don't have an ETA to share. As per your scenario .NET core samples are not available for that.

You can have look at this. It record and playback user voice: https://github.com/microsoftgraph/microsoft-graph-comms-samples/tree/master/Samples/V1.0Samples/StatelessSamples/VoiceRecorderAndPlaybackBot

**Comment by sanketdixit2013** [comment]
Thanks @HunaidHanfee-MSFT ! 
I am going through the link you shared and will comeback if I have any queries.

**Comment by HunaidHanfee-MSFT** [comment]
Calling endpoint and message endpoint are two different endpoint. Have you tried the endpoint of both deployed service. Are you facing any issue?

**Comment by sanketdixit2013** [comment]
Hi @HunaidHanfee-MSFT ,

Can you please help me on this as I'm stuck here.

Thanks

**Comment by sanketdixit2013** [comment]
Hi @HunaidHanfee-MSFT ,

Can you please help me on this as I'm stuck here.

Thanks

**Comment by HunaidHanfee-MSFT** [comment]
Sorry for the delay. I was on leave. 

Can you confirm you are getting request when calling the endpoint?

**Comment by sanketdixit2013** [comment]
Hi @HunaidHanfee-MSFT ,

Didn't get you what do I need to confirm? when I'm doing the POST call after deploying the solution on local cluster and setting up a meeting and then the next step is to do a POST call to the endpoint https://{Mybotbaseurl}:9441/joinCall? for which I get Request timed out. I have registered a calling bot and I'm using its endpoint in the the postman call with my teams meeting join url in the body.

**Comment by HunaidHanfee-MSFT** [comment]
It looks correct to me. Have you followed the steps from [Readme.md](https://github.com/microsoftgraph/microsoft-graph-comms-samples/blob/a4c6c6c8ae96cbd0125851dcc64278f9d02328cb/Samples/V1.0Samples/LocalMediaSamples/HueBot/README.md#prerequisites)

When you do POST call to joinCall, you should get the a request on ngrok window? Can you confirm that you are getting it? 

Could you try adding debugger at this point if you are getting the request or not?
https://github.com/microsoftgraph/microsoft-graph-comms-samples/blob/157b1cfced0c1dfe186d7fa4c42ab5695b68f7b5/Samples/V1.0Samples/LocalMediaSamples/HueBot/HueBot/Controllers/JoinCallController.cs#L44-L61

**Comment by sanketdixit2013** [comment]
Hi @HunaidHanfee-MSFT ,

No, I'm not getting the request in ngrok. Yes I have followed the steps but think I might be doing something wrong in this step "Set up a DNS CNAME entry for %replace_with_ngrok_media_prefix%.contoso.com pointing to %replace_with_ngrok_media_prefix%.tcp.ngrok.io. Example: 0.contoso.com to 0.tcp.ngrok.io." 
Can you please tell how exactly I need to do this? I have taken the pro subscription of ngrok and added the DNS Cname entry with the ngrok media prefix which I got when I ran the ngrok.yml file.

Can you please explain this step clearly? Or is there something else that might be wrong?

**Comment by HunaidHanfee-MSFT** [comment]
Have you added like this 0.tcp.ngrok.io?

**Comment by sanketdixit2013** [comment]
I have added like this PFA. I added a domain with %replace_with_ngrok_media_prefix%.MyDomain
![image](https://user-images.githubusercontent.com/62757731/140757687-a467da3a-a750-4408-a433-955a7b7e7b3f.png)

**Comment by HunaidHanfee-MSFT** [comment]
As mentioned in the steps,

1. You need to create a YML file.
2. Start ngrok: ngrok.exe start -all -config %replace_with_path_to_your_ngrok.yml%. You will see an output like this:
![image](https://user-images.githubusercontent.com/64194049/140759878-24796808-78f4-43c7-9786-93aa54853527.png)

From your output, note the 3 values in the places marked in red above. From now on, we will call them by these names:


3. `9add54fe` - ngrok signaling prefix
`0` - ngrok media prefix
`18134` - ngrok media port
4. Set up a DNS CNAME entry for %replace_with_ngrok_media_prefix%.contoso.com pointing to %replace_with_ngrok_media_prefix%.tcp.ngrok.io. Example: 0.contoso.com to 0.tcp.ngrok.io.

You are doing it using ngrok, but I can see azurewebsites? Am I missing something?

**Comment by sanketdixit2013** [comment]
Okay so in the 4th step we need to create a DNS Cname entry for  "%replace_with_ngrok_media_prefix%.contoso.com" here in place of contoso.com I have added my domain.

So do you mean we need to create a domain from ngrok dashboard and add it as "%replace_with_ngrok_media_prefix%.tcp.ngrok.io" this ? Am I correct? The above steps of creating a .yml file is fine but I'm just confused about the step 4.

**Comment by HunaidHanfee-MSFT** [comment]
Ngrok's public TCP endpoints have fixed URLs. They are 0.tcp.ngrok.io, 1.tcp.ngrok.io, and so on. You must have a DNS CNAME entry for your service that points to these URLs. For example, let's say 0.bot.contoso.com refers to 0.tcp.ngrok.io, 1.bot.contoso.com refers to 1.tcp.ngrok.io, and so on

Please have a look at this -
Ref: https://docs.microsoft.com/en-us/microsoftteams/platform/bots/calls-and-meetings/debugging-local-testing-calling-meeting-bots#set-up-local-media
