### ISSUE TITLE
Classes

### ISSUE THREAD

**Issue by Diro92** [MicrosoftDocs/msteams-docs#427]
Hello I would like to know how you define the following classes:
FileConsentCard 
FileDownloadInfo 

Are these metaclasses?

Thanks

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ vinculación de problemas de GitHub.*

* ID: 5307fe5c-a6f0-59e2-d125-69051ab58595
* Version Independent ID: ca3f41d9-1c2a-6cde-b780-61fec8f0fcb6
* Content: [Sending and receiving files from a bot - Teams](https://docs.microsoft.com/es-mx/microsoftteams/platform/concepts/bots/bots-files)
* Content Source: [msteams-platform/concepts/bots/bots-files.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/bots/bots-files.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by clearab** [comment]
You can find the implementation of both classes here: https://github.com/OfficeDev/BotBuilder-MicrosoftTeams/tree/master/Node/src/models

Let us know if you have any specific questions after that and we'll be happy to assist further.

**Comment by Diro92** [comment]
Sorry I forgot to ask for the implementation in C# Visual Studio.

Thanks In advance.!

**Comment by Wajeed-msft** [comment]
@Diro92 - Here are C# classes: https://github.com/OfficeDev/BotBuilder-MicrosoftTeams/tree/master/CSharp/Library/Microsoft.Bot.Connector.Teams.Shared/TeamsAPI/Models

These are available as Nuget package _Microsoft.Bot.Connector.Teams_:
![image](https://user-images.githubusercontent.com/31851992/52290810-f1331200-2996-11e9-893c-793135c72974.png)

**Comment by clearab** [comment]
Please note that the v4.x version of that Nuget package supports Bot Builder v4, and the v0.9.x versions support Bot Builder v3.

**Comment by Diro92** [comment]
there is a way to get the file from pc as an attachment from OpenDialogFile in node js in the bot?

**Comment by Wajeed-msft** [comment]
@Diro92 - You should be able to [configure your bot to support files](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/bots/bots-files#configure-your-bot-to-support-files) upload. Then user could upload files using attachment button available in UI. 
![image](https://user-images.githubusercontent.com/31851992/52851291-bd48b100-313b-11e9-84f1-43c5ca8994a9.png)

Are you looking for something else?
