### ISSUE TITLE
Can't send files after chatting with an App/Bot

### ISSUE THREAD

**Issue by JordyGit** [MicrosoftDocs/msteams-docs#4276]
Hi,

We are working on a Teams app/bot and I noticed that after going to the app/bot chat the 'files' icon disapears.
When going back to a normal chat with a real person, the 'files' icon doesn't appear back. Also drag & dropping files doesn't reenable again.

Workaround: Quit teams by right clicking the teams icon in the taskbar and restarting it.

**Comment by v-chetsh** [comment]
@JordyGit - Could you please share few screenshots along with repro steps so that it will be easy for us to investigate the issue.

**Comment by JordyGit** [comment]
1) open a new Teams window, validate you can send files in a normal chat: 
![image](https://user-images.githubusercontent.com/33500507/135970561-77d0b0dc-2478-4f33-8cc7-ce1210655f72.png)

2) open a chat with a bot/app (it does not happen with all bots), the button goes away:
![image](https://user-images.githubusercontent.com/33500507/135970681-edda90be-dcfb-4567-a0cd-48d14ff91272.png)

3) go back to a normal chat, button doesn't appear any more:
![image](https://user-images.githubusercontent.com/33500507/135970735-a46822b0-8f0c-40dd-9f6f-6828c6bd7e16.png)

It's the same for drag & dropping files, it doesn't work either if the button is gone.

**Comment by Prithvi-MSFT** [comment]
Hi @JordyGit ,
Can you confirm if supportsFiles is true in bot's section of your app manifest ? If not can you set it true and then check. Also if the changes are not reflected immediately try deleting the old app and add updated manifest and check once.

Refer below link
https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema#bots

Thanks

**Comment by JordyGit** [comment]
Hi,

The issue is _not the bot not supporting files_, **it's teams not putting the files button back** in normal chats with real users.

At the moment our both does nothing with files so the value is false in the manifest.

Kind Regards

**Comment by Prithvi-MSFT** [comment]
Hi @JordyGit ,
Does the files icon is not visible for user's also or its not visible for  bots only ?

Thanks

**Comment by JordyGit** [comment]
Hi,

It's visible for chats with other users, **until** I open the chat to the bot. Then the icon disappears in the chat with the bot, and **doesn't come back** in other chats with users as wel until I restart teams completely.

**Comment by Prithvi-MSFT** [comment]
Hi @JordyGit ,
We are able to repro this issue. A bug has been raised for this and concerned team is looking into it

**Comment by JordyGit** [comment]
The bug seems to be fixed correctly in the Microsoft Teams Desktop Client _v1.4.00.35564_, so I'll close this issue. Thanks!
