### ISSUE TITLE
Getting notifications even if false? 

### ISSUE THREAD

**Issue by liangchr** [MicrosoftDocs/msteams-docs#428]
when I do: 
 "channelData": {
        "notification": {
            "alert": false
        }
    }

it still shows the notification? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd0d8d78-1ad5-5a99-3ef9-b03124476ebf
* Version Independent ID: 64505c8a-4f08-0454-2602-8821ca29c218
* Content: [Activity feed - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/activity-feed)
* Content Source: [msteams-platform/concepts/activity-feed.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/activity-feed.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Wajeed-msft** [comment]
If your app posts cards and other messages into a channel, they'll automatically show up in the user's feed if he or she has followed that channel.

This flag controls wheather to show personal chat messages into the feed as preview cards or not.
