### ISSUE TITLE
[JS] Adaptive Card 'Only Show When'

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#4280]
Copied bug from: https://github.com/microsoft/AdaptiveCards/issues/6464 

**Details from original post:**
### Problem Description

I am trying to use "Only Show When" in an Adaptive Card posted to Teams.
"${@{outputs('Post_adaptive_card_and_wait_for_a_response')?['body/data/choiceFRATRating']} = 1}"
The "choiceFRATRating" is either 1,2, or 3.
The card shows the Textblock regardless of value.
Thoughts?

### Card JSON

```JSON
"type": "AdaptiveCard",
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.2",
    "body": [
        {
            "type": "TextBlock",
            "text": "@{outputs('Post_adaptive_card_and_wait_for_a_response')?['body/data/dateFRAT']}",
            "wrap": true,
            "spacing": "Large",
            "height": "stretch",
            "size": "Large",
            "weight": "Bolder",
            "color": "Accent",
            "horizontalAlignment": "Center"
        },
        {
            "type": "TextBlock",
            "text": "Pre EMT FRAT has defined the day as:",
            "wrap": true,
            "horizontalAlignment": "Center",
            "separator": true
        },
        {
            "type": "TextBlock",
            "text": "Green",
            "wrap": true,
            "separator": true,
            "$when": "${@{outputs('Post_adaptive_card_and_wait_for_a_response')?['body/data/choiceFRATRating']} = 1}",
            "height": "stretch",
            "horizontalAlignment": "Center",
            "size": "Medium",
            "weight": "Bolder",
            "color": "Good"
        },
        {
            "type": "TextBlock",
            "text": "Yellow",
            "wrap": true,
            "separator": true,
            "$when": "${@{outputs('Post_adaptive_card_and_wait_for_a_response')?['body/data/choiceFRATRating']} = 2}",
            "height": "stretch",
            "horizontalAlignment": "Center",
            "size": "Medium",
            "weight": "Bolder",
            "color": "Warning",
            "isSubtle": true
        },
        {
            "type": "TextBlock",
            "text": "Green",
            "wrap": true,
            "separator": true,
            "$when": "${@{outputs('Post_adaptive_card_and_wait_for_a_response')?['body/data/choiceFRATRating']} = 3}",
            "height": "stretch",
            "horizontalAlignment": "Center",
            "size": "Medium",
            "weight": "Bolder",
            "color": "Attention"
        }
    ]
}
```

### Screenshot

_No response_---
#### Document Details

⚠ *Do not edit this section.It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Cards reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **surbhigupta12**

**Comment by RebeccaAnne** [comment]
This one should not have been ported over from the Adaptive Cards repo and can be closed. Sorry!
