### ISSUE TITLE
[Android] Invoke action at adaptive card doesn't work

### ISSUE THREAD

**Issue by WhiteCyClop** [MicrosoftDocs/msteams-docs#4284]
About a week ago invoke actions from adaptive card stopped working for my bot at Android. I didn't make any changes to it, but now OnTeamsCardActionInvokeAsync doesn't fire at click on button of adaptive card on Android. At the same time for the desktop/web everything works as before fine. This is part of adaptive card with button:

```
{
  "type": "AdaptiveCard",
  "body": [
    ...
    {
      "type": "ActionSet",
      "actions": [
        {
          "type": "Action.Submit",
          "title": "Templates",
          "data": {
            "msteams": {
              "type": "invoke"
            },
            "dialogId": "ApplicationTemplatesDialog"
          }
        }
      ]
    }
  ],
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "version": "1.3"
}
```

When I click this button on Android there are two calls of ActivityHandler.OnTurnAsync, but not TeamsActivityHandler.OnTeamsCardActionInvokeAsync. What could be the problem?

**Comment by HunaidHanfee-MSFT** [comment]
We are looking into this, can you share the version of Teams Mobile Client?
Thanks

**Comment by WhiteCyClop** [comment]
My version is 1416/1.0.0.2021143402/0919

**Comment by HunaidHanfee-MSFT** [comment]
I have the repro at our end, we are also facing same in 1416/1.0.0.2021143402. I am checking with internal team and get back to you soon with updates.

Thanks

**Comment by HunaidHanfee-MSFT** [comment]
If this is blocking your application you can use `onInvokeActivityAsync`, I checked and it is working on Android too. Meanwhile I am checking `OnTeamsCardActionInvokeAsync`.

**Comment by koaskas** [comment]
My problem is solved, thanks

**Comment by WhiteCyClop** [comment]
Yes, now it works fine. Thank you!

**Comment by HunaidHanfee-MSFT** [comment]
Thanks for the updates!
