### ISSUE TITLE
Notification title doesn't show properly

### ISSUE THREAD

**Issue by liangchr** [MicrosoftDocs/msteams-docs#429]
Even when I specify: 
message.text = "Bananas Delivered"
message.summary = "The supermarket has delivered your bananas."

the activity feed doesn't show the proper title/text 

instead it shows: "Christina-Bot sent a message. TestTeam -&gt; General."

Here is an example payload: 
{
    "type": "message",
    "recipient": {
        "id": "numbersandletters",
        "email": "something@gmail.com",
        "aadObjectId": "numbersandletters"
    },
    "conversation": {
        "id": "numbersandletters"
    },
    "channelData": {
        "notification": {
            "alert": true
        }
    },
    "text": "Bananas Delivered",
    "summary": "The supermarket has delivered your bananas."
}  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd0d8d78-1ad5-5a99-3ef9-b03124476ebf
* Version Independent ID: 64505c8a-4f08-0454-2602-8821ca29c218
* Content: [Activity feed - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/activity-feed)
* Content Source: [msteams-platform/concepts/activity-feed.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/activity-feed.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Gousia-MSFT** [comment]
@liangchr - We are working on updating the docs to reflect the current behavior.

**Comment by davidlinhares** [comment]
Any update on this issue?

**Comment by aosolis** [comment]
The activity feed customization only applies to 1:1 messages between a bot and a user, as called out in the [page](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/activity-feed):

Note
This applies to one-to-one messages between a bot and a user. Messages inserted into a channel generate a notification in the activity feed based on the user's notification settings for that channel.

In the case of a post to a channel, the fields in the activity feed notification are standard (action, location, text).
