### ISSUE TITLE
[Rendering] Action.Submit in combination with Input.Number under Action.Showcard does not work

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#4299]
Copied bug from: https://github.com/microsoft/AdaptiveCards/issues/6503 

**Details from original post:**
### Target Platforms

iOS, Android, Other

### SDK Version

1.2

### Application Name

Microsoft Teams

### Problem Description

Tested on Teams for iOS, Android, Windows client and Teams web client and they all experience the same issue.

I have a flow in power automate that uses the "Post adaptive card and wait for a response" action.

The Action.Submit button under Action.ShowCard does not work if the input type is Input.Text in the "sub-adaptive card".

If i change the input to Input.Text everything works as expected.

### Card JSON

```JSON
{
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "type": "AdaptiveCard",
    "version": "1.2",
    "body": [
        {
            "type": "TextBlock",
            "text": "Status",
        },
        {
            "type": "Input.Text",
            "placeholder": "Status",
            "id": "txtStatus",
        }
    ],            
    "actions": [
        {
            "type": "Action.Submit",
            "title": "Submit status"
        },
        {
            "type": "Action.ShowCard",
            "title": "Submit something else",
            "card": {
                "type": "AdaptiveCard",
                "body": [
                    {
                        "type": "TextBlock",
                        "text": "Something:",
                        "wrap": true
                    },
                    {
                        "type": "Input.Number",
                        "id": "NumberOfDays"
                    }
                ],
                "actions": [
                    {
                        "type": "Action.Submit",
                        "title": "Set number",
                        "value": 3
                    }
                ]
            }
        }
    ]
}
```

### Sample Code

_No response_---
#### Document Details

⚠ *Do not edit this section.It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Cards reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **surbhigupta12**

**Comment by thewindev** [comment]
In case you need help reproducing the bug, I added a comment in the original issue with a smaller json and a screen recording, you can find them here:

https://github.com/microsoft/AdaptiveCards/issues/6503#issuecomment-934614840

**Comment by bogdanbujdea** [comment]
I can confirm the issue is fixed. Thank you!
