### ISSUE TITLE
Cannot download sample app TalentMgmt-Azure.zip

### ISSUE THREAD

**Issue by panjkov** [MicrosoftDocs/msteams-docs#430]
From the "Tabs in SharePoint" tutorial page
https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/tabs/tabs-in-sharepoint#step-1-testing-the-sample-app
, it is not possible to download sample app
https://docs.microsoft.com/en-us/microsoftteams/platform/assets/downloads/TalentMgmt-Azure.zip 
(Page not found error).

File TalentMgmt-Azure.zip exists on both master and live branches.

**Comment by clearab** [comment]
Thanks for letting us know, the link will be fixed in the next few days.
