### ISSUE TITLE
Issue retrieving AuthToken in Task Module in desktop client

### ISSUE THREAD

**Issue by dbenitez23** [MicrosoftDocs/msteams-docs#4315]
For context, I´m developing a Bot that answers to activity messages with a Task Module, and I´m having an issue while trying to get the AuthToken under certain circumstances.
```
microsoftTeams.getContext((context) => {

            var authTokenRequest = {
                successCallback: function (token) {
                    myfunction(token);
                },
                failureCallback: function (error) { 
                    alert("Failure: " + error);
                },
            };
            microsoftTeams.authentication.getAuthToken(authTokenRequest);
        });
```
This js code was working for me for a long time, but about a week ago it stopped working for a certain case. When I Invoke the Task Module from a Card or Compose button, it works perfectly fine, but it does not when I invoke the Task Module from a deep link. 
In the deep link case, when I open the Task Module from Teams Web and Teams for Mobile it still works, but when I try it from Desktop Client I get the failure callback. Error says: "definition not found".

As I say, this code stopped working without any changes on it, so I´m pretty sure it has something to be with the lastests updates on Teams client. If you guys can help me out I would really aprecciate.

Regards.

**Comment by Prasad-MSFT** [comment]
@knoppanthony . There is no ETA as of now to share. We will inform you once we get any update

**Comment by v-chetsh** [comment]
@knoppanthony - Engineering team is looking into it and once it is fixed and publicly released, we will let you know.

**Comment by are-scenic** [comment]
Hi,

This issue is very problematic for our team. We use Trello and this bug makes it hard to navigate between Teams and Trello. 

What is the ETA? We need to decide whether we stay with Teams or whether we should look for other alternatives.

Thank you,
Arseniy

**Comment by are-scenic** [comment]
> @knoppanthony - Engineering team is looking into it and once it is fixed and publicly released, we will let you know.

@ChetanSharma-msft, are there any updates on this issues?

Thank you,
Arseniy

**Comment by aosolis** [comment]
Let me apologize first for the inactivity on this thread. @ChetanSharma-msft @Wajeed-msft please review our process for communicating status update on issues when we make a commitment to do so.

I checked on the progress of the rollout of the fix to the bug referenced in this thread. It hit 100% availability 1 week ago. 

@are-scenic are you still seeing the error calling getAuthToken on Teams desktop client? If so, could you reach out to us over [email](MicrosoftTeamsDev@microsoft.com) so we can investigate further? Thank you.

**Comment by Prasad-MSFT** [comment]
We are closing this issue for now. Please feel free to reopen if required. Thanks!
