### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by dmvtech** [MicrosoftDocs/msteams-docs#433]
This version string must follow the semver standard (MAJOR.MINOR.PATH).

Should be:

This version string must follow the semver standard (MAJOR.MINOR.PATCH).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f94a488-d636-92b3-21eb-c88744c8f272
* Version Independent ID: 7b3413f4-9ade-accf-5cb2-83fead11a32a
* Content: [Manifest schema reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema#bots)
* Content Source: [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/resources/schema/manifest-schema.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by clearab** [comment]
Thanks for letting us know; this will be fixed shortly.
