### ISSUE TITLE
Submit Button Not Working With Input.Number 

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#4357]
Copied bug from: https://github.com/microsoft/AdaptiveCards/issues/6568 

**Details from original post:**
### Target Platforms

NodeJS

### SDK Version

1.0 & 1.1 & 1.2

### Application Name

Teams Bot 

### Problem Description

We have created a bot app on teams. It's working in previously on production.
But In the last few days ago we are getting issue with submit button.
I have checked on teams as well as bot emulator.
bot emulator working fine.
but on teams now,
submit button not working with Input.Number Field(Action Not Happen).
I have try it with Input.Text(replace Input.Number) then working fine.

### Screenshots

![image](https://user-images.githubusercontent.com/17414613/136671157-75a5220a-46ba-46d0-9b8f-aabd7a7b94db.png)

### Card JSON

```JSON
{
            "type": "AdaptiveCard",
            "version": "1.2",
            "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
            "body": [
                {
                    "type": "Input.Number",
                    "placeholder": "Placeholder text",
                    "id": "amount"
                },
                {
                    "type": "ActionSet",
                    "actions": [
                        {
                            "type": "Action.Submit",
                            "title": "Action.Submit"
                        }
                    ]
                }
            ]
        }
```

### Sample Code Language

Node JS

### Sample Code

await step.context.sendActivity({attachments: [CardFactory.adaptiveCard({
            "type": "AdaptiveCard",
            "version": "1.2",
            "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
            "body": [
                {
                    "type": "Input.Number",
                    "placeholder": "Placeholder text",
                    "id": "amount"
                },
                {
                    "type": "ActionSet",
                    "actions": [
                        {
                            "type": "Action.Submit",
                            "title": "Action.Submit"
                        }
                    ]
                }
            ]
        })]})---
#### Document Details

⚠ *Do not edit this section.It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Cards reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **surbhigupta12**

**Comment by niteshjain1987** [comment]
Issue No. 3
Icon overlapping when popup out chat window on teams app.
![image](https://user-images.githubusercontent.com/17414613/136931731-2fa0c305-0c14-4a3c-b1ec-f0936a9fa917.png)

**Comment by HunaidHanfee-MSFT** [comment]
I tried to repro Input.Number issue but it is working totally fine for me. When clicking on submit button I am getting a request in OnMessageActivityAsync.

I tested on Teams Desktop 1.4.00.27614 (64-bit)-E and on browser. Could you please check on browser and share your Teams desktop version?

**Comment by HunaidHanfee-MSFT** [comment]
Let me know if you facing issue after adding min/max. 
We have raised a bug for this behavior that is internal and concerned team is looking into it. 
For issue 3 as well we have raised a bug. 

Thanks for sharing this.
