### ISSUE TITLE
Problems Rendering HeroCards after issue #4249

### ISSUE THREAD

**Issue by rchardin** [MicrosoftDocs/msteams-docs#4362]
Ever since receiving the error described in issue #4249, tables that were rendering fine and continue to render fine on the web based client are seeing the first column become squished.
Good:
![image](https://user-images.githubusercontent.com/6289950/136849703-1cc28dfa-d4ac-48fd-b95d-b69622e971db.png)
Bad:
![image](https://user-images.githubusercontent.com/6289950/136849760-e753cf6d-a8bb-48e7-b43e-bafc62a2087c.png)
Code:

```
`            var rcard = new HeroCard();
            rcard.Title = $"Welcome {turnContext.Activity.From.Name}";
            rcard.Text = $"<table table-layout: \"auto\">" +
                $"<tr>" +
                $"<th style=\"text-align:center\">Command</th>" +
                $"<th style=\"text-align:center\">Function</th>" +
                $"</tr>" +
                $"<tr><td>!r</td><td>Make a new lab request</td></tr>" +
                $"<tr><td><br/></td></tr>" +
                $"<tr><td>!</td><td>List of previous requests</td></tr>" +
                $"<tr><td><br/></td></tr>" +
                $"<tr><td>| Text |</td><td>If you are not in conversation, type your question and it will be logged in as a free form request and answered on a first come first served basis.</td></tr>" +
                $"<tr><td><br/></td></tr></table>" +
                $"<hr><table table-layout: \"auto\">" +
                $"<tr>" +
                $"<th style=\"text-align:center\">Command</th>" +
                $"<th style=\"text-align:center\">Function</th>" +
                $"</tr>" +
                $"<tr><td>!who</td><td>List of current conversations and the person with whom you are conversing. Allows user to select another conversation. (Used by Techs)</td></tr>" +
                $"<tr><td><br/></td></tr>" +
                $"<tr><td>!punt</td><td>Return an accepted job to the queue, preferably to @mention another tech to continue request. (Used by Techs)</td></tr>" +
                $"<tr><td><br/></td></tr>" +
                $"<tr><td>!group</td><td>Move this request to the web based group queue.  This effectively closes the job within this tool but transfers all information to group tool.(Used by Techs)</td></tr>" +
                $"<tr><td><br/></td></tr>" +
                $"<tr><td>!greet:</td><td>Everything following the colon (:) will become your new greeting when you accept a job. (Used by Techs) </td></tr>" +
                $"<tr><td><br/></td></tr>" +
                $"<tr><td>!exit</td><td>Exit the current conversation.  If you have other conversations open, the next will be made active. (Used by Techs)</td></tr></table>";
            rcard.Buttons = new List<CardAction>() { };

            rcard.Buttons.Add(new CardAction
            {
                Type = ActionTypes.OpenUrl,
                Title = "Watch Video",
                Value = "https://bobscupofsoup.com/Help.mp4?csf=1&web=1&e=U3dbqf"
            });`
```

**Comment by rchardin** [comment]
Workaround found:

`rcard.Text = $"<table style=\"width: 100 % \">" +
                $" <colgroup>" +
                $"<col span = \"1\" style = \"width: 22%;\">" +
                $"<col span = \"1\" style = \"width: 78%;\">" +
                $"</colgroup>" +
                $"<tbody>" +
                $"<tr>" +
                $"<th style=\"text-align:center\">Command</th>" +
                $"<th style=\"text-align:center\">Function</th>" +
                $"</tr>" +
                $"<tr><td>!r</td><td>Make a new lab request</td></tr>" +
                $"<tr><td><br/></td></tr>" +
                $"<tr><td>!</td><td>List of previous requests</td></tr>" +
                $"<tr><td><br/></td></tr>" +
                $"<tr><td>| Text |</td><td>If you are not in conversation, type your question and it will be logged in as a free form request and answered on a first come first served basis.</td></tr>" +
                $"<tr><td><br/></td></tr>" +
                $"<tr><td>!cancel</td><td>Cancel current request.</td></tr>" +
                $"</tbody></table>" +
                $"<hr><table>" +
                $"<colgroup>" +
                $"<col span = \"1\" style = \"width: 22%;\">" +
                $"<col span = \"1\" style = \"width: 78%;\">" +
                $"</colgroup>" +
                $"<tbody>" +
                $"<tr>" +
                $"<th style=\"text-align:center\">Command</th>" +
                $"<th style=\"text-align:center\">Function</th>" +
                $"</tr>" +
                $"<tr><td>!who</td><td>List of current conversations and the person with whom you are conversing. Allows user to select another conversation. (Used by Techs)</td></tr>" +
                $"<tr><td><br/></td></tr>" +
                $"<tr><td>!punt</td><td>Return an accepted job to the queue, preferably to @mention another tech to continue request. (Used by Techs)</td></tr>" +
                $"<tr><td><br/></td></tr>" +
                $"<tr><td>!group</td><td>Move this request to the web based group queue.  This effectively closes the job within this tool but transfers all information to group tool.(Used by Techs)</td></tr>" +
                $"<tr><td><br/></td></tr>" +
                $"<tr><td>!greet:</td><td>Everything following the colon (:) will become your new greeting when you accept a job. (Used by Techs) </td></tr>" +
                $"<tr><td><br/></td></tr>" +
                $"<tr><td>!exit</td><td>Exit the current conversation.  If you have other conversations open, the next will be made active. (Used by Techs)</td></tr></tbody></table>";`

**Comment by v-chetsh** [comment]
@rchardin - Looks like your issue has resolved, shall we close the bug?
