### ISSUE TITLE
Bot command menu very jittery on Android

### ISSUE THREAD

**Issue by matthiasdilger** [MicrosoftDocs/msteams-docs#4368]
When chatting with a bot on Android the bot command menu is way too "eager" and pops up too often.
Once it's clear that the first few characters of user input are not part of a command the command menu should stay hidden and not pop up again on every press of the space button.

Version: 1416/1.0.0.2021143402/0919
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a982542-ae03-2ada-cf71-4d586272e0c3
* Version Independent ID: 9e1fd82b-79e4-1b8d-5367-a8de3d04b3aa
* Content: [Create a command menu for your bot - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/create-a-bot-commands-menu?tabs=desktop%2Cdotnet)
* Content Source: [msteams-platform/bots/how-to/create-a-bot-commands-menu.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/bots/how-to/create-a-bot-commands-menu.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **anclear**

**Comment by Prasad-MSFT** [comment]
@matthiasdilger ,
We tried to repro the issue and can confirm that we are also facing the same. We have raised a bug for this and Engineering Team is looking into it.
Thanks!

**Comment by matthiasdilger** [comment]
The current version of the Android app is not showing the bot command menu anymore, so this bug is no longer applicable. Closing.

**Comment by matthiasdilger** [comment]
Hi @Prasad-MSFT this issue is back. Can the command menu please not pop up on every pressing of the space key? For example a bot for booking flights supports the command "book" but the user types "please help me buy tickets to delhi". The command menu pops up on every word even though it's clear the user does not intend to use the command.

**Comment by Prasad-MSFT** [comment]
@matthiasdilger , Could you please confirm which MS Teams app version you are using?

**Comment by matthiasdilger** [comment]
Hi @Prasad-MSFT the Teams app version is 1417/1.0.0.2021173701/1103

**Comment by matthiasdilger** [comment]
Hi @Prasad-MSFT any updates? I get constant user feedback that I should remove the bot command menu on Android (which I can't do)

**Comment by Prasad-MSFT** [comment]
@matthiasdilger , We have an internal bug raised for this and have informed the concerned team about the issue. We will inform you once we get any update. Thanks

**Comment by Prasad-MSFT** [comment]
@matthiasdilger - This issue is fixed. Please do verify.

**Comment by matthiasdilger** [comment]
This has been much improved, thanks. Closing
