### ISSUE TITLE
Complete app manifest sample needs correction

### ISSUE THREAD

**Issue by TheBluLion** [MicrosoftDocs/msteams-docs#4378]
Parameters are not used if fetchtask is set to true. 
Also, parameters don't include type which means manifest as written will not work. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5319949f-7a29-1d17-0090-5f423ae8174e
* Version Independent ID: 2d45f040-a391-ac0b-17e8-fa99e880fcf1
* Content: [Initiate actions with messaging extensions - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/messaging-extension-v3/create-extensions?tabs=typescript#feedback)
* Content Source: [msteams-platform/resources/messaging-extension-v3/create-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/resources/messaging-extension-v3/create-extensions.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by v-chetsh** [comment]
@TheBluLion -  We have multiple scenarios using fetchTask.
Also **"fetchTask"** is a optional parameter but **"parameters"** is a required once.

In documentation, we have a note like below:
**"Note that if you set fetchTask to true any static parameters defined for the command will be ignored."**

Could you please elaborate your ask & point us to the exact location where we need docs improvement.

**Comment by TheBluLion** [comment]
![image](https://user-images.githubusercontent.com/41968802/140081894-82971bf7-7abd-4fc7-a25c-8bcae0939216.png)

The complete app manifest in the sample does not make sense
fetchtask is set to true and parameters are defined with no type attribute. 

Additional commenting or notes should be added to how a functional app manifest should be constructed from this example.

**Comment by v-chetsh** [comment]
Redirecting it to doc team.
