### ISSUE TITLE
Bot not responding on Teams & can't click & enlarge image

### ISSUE THREAD

**Issue by s209395** [MicrosoftDocs/msteams-docs#4379]
MS Teams Chatbot (Images can't click and enlarge).
MS teams Chatbot (if you chat the chatbot has no response) also in MS Teams Web

**Comment by s209395** [comment]
- [x] Here's the image![image](https://user-images.githubusercontent.com/92497731/137286433-eac9583e-33b3-4fd2-ba58-bc3ac2177516.jpeg)

**Comment by s209395** [comment]
![image](https://user-images.githubusercontent.com/92497731/137287669-9fab7edf-3b1b-4618-be06-59e67b27e97b.jpeg)

**Comment by v-chetsh** [comment]
@s209395 - Could you please let me know the steps you are trying it here.
Also which image you are trying to upload or clicking.

**Comment by s209395** [comment]
There's no error pop-up after sending the message.

**Comment by v-chetsh** [comment]
Are you using ngrok or any tunnel for it?

**Comment by s209395** [comment]
after we published it works fine then several days bot suddenly not responding until now.

**Comment by v-chetsh** [comment]
Could you please check your Bot channel registration and your app service plan?

**Comment by s209395** [comment]
Ok, I will get back to you, I will ask our System administrator to check the AppInsights.

**Comment by s209395** [comment]
Hi v-chetsh

we already solved our first issue that was Bot not responding on Teams, our bot is now working.
The only problem we have is that the image still can't be clicked and enlarged.
can you provide solutions here?

Thank you,

**Comment by HunaidHanfee-MSFT** [comment]
Thanks for updating, we have received the similar issue when doing this with Bot. We are looking into this.

**Comment by HunaidHanfee-MSFT** [comment]
Could you please share the steps how you are sending the image? It will help us to provide repro steps to Internal Engineering team.

**Comment by s209395** [comment]
Hi HunaidHanfee-MSFT

Thank you so much.

I will wait for your next update. 

Have a great day ahead!

**Comment by HunaidHanfee-MSFT** [comment]
Teams is working on it and it in progress. Sorry don't have an ETA to share, but I will update you once it is fixed.

Thanks

**Comment by s209395** [comment]
Hi Wajeed-msft, v-chetsh

Good day!

We would like to know if there’s any update regarding the MS Teams fixed update.

Thank you and have a great day ahead!

**Comment by v-chetsh** [comment]
@s209395 - Could you please try updating your Teams desktop client on windows and check it once.
We will check the status of bug again and let you know.

**Comment by s209395** [comment]
Hi @v-chetsh 

I have already tried to update my Teams Desktop Client,  but I didn't get an update, and still can't click and enlarge the image.

It says "You've got the latest updates. Enjoy!"

Here's the Teams desktop client version:
Microsoft Teams Version 1.4.00.26376 (64-bit)

Thank you and have a great day ahead!

**Comment by s209395** [comment]
Hi @v-chetsh 

Good day,

Is there any update?

Thank you and have a great day ahead!

**Comment by HunaidHanfee-MSFT** [comment]
Hello @s209395,
Bug is being tested. Right now I don't have an exact ETA to share for when it is pushed for public.

Thanks

**Comment by s209395** [comment]
Hi @HunaidHanfee-MSFT 

Thank you for your response.

I tried to update my Teams Desktop Client installed on my workstation and I already get the update but still can't click and enlarge the image from our Chatbot.

Here's the Teams desktop client version:
Microsoft Teams Version 1.4.00.29469 (64-bit).

Thank you and have a great day ahead!

**Comment by HunaidHanfee-MSFT** [comment]
Thanks for the update. Teams is testing the fix internally. I can't share ETA as there are multiple builds there to be tested in. I will update you once it is fixed for all. 

Thanks

**Comment by s209395** [comment]
Hi @HunaidHanfee-MSFT 

Thanks for the update. Noted on the information you provided.

I will wait for your next update.

Have a great day ahead!

**Comment by s209395** [comment]
Hi @HunaidHanfee-MSFT 

Good day,

We would like to share our experience in Web-based MS teams we can't click the image and enlarge it from our Chatbot. but the last few days it has been working fine.

hope to hear from you soon!

Thank you

**Comment by HunaidHanfee-MSFT** [comment]
Thanks for telling us I will check again about the status and let you know if it's out in public.

**Comment by s209395** [comment]
Hi @HunaidHanfee-MSFT 

Hope you could get back to us as soon as there's an update from your end.

Thank you!

**Comment by s209395** [comment]
Hi @HunaidHanfee-MSFT 

Good day,

Is there any update?

Thank you!

**Comment by HunaidHanfee-MSFT** [comment]
Hello @s209395,
It's still in the pipeline and I can't give a specific date when it will be rolled out. I will update you once it is fixed 
Thanks

**Comment by s209395** [comment]
Hi @HunaidHanfee-MSFT

Good day,

Is there any update?

Thank you!

**Comment by HunaidHanfee-MSFT** [comment]
We are expecting fix to be out in January. I will update you once it is out. 

Thanks

**Comment by s209395** [comment]
Hi @HunaidHanfee-MSFT

Thanks for the update. Noted on the information you provided.

hope to hear from you soon!

Thank you

**Comment by s209395** [comment]
Hi @HunaidHanfee-MSFT

Good day!

We would like to know if the fix update has already been roll-out.

hope to hear from you soon!

Thank you

**Comment by HunaidHanfee-MSFT** [comment]
We are checking the update with engineering team and we will let you know. 

Thanks

**Comment by HunaidHanfee-MSFT** [comment]
@s209395 - Hello,
Confirmed with internal team, it still in pipeline. I will let you know once it is rollout publicly.

Thanks

**Comment by s209395** [comment]
Hi @HunaidHanfee-MSFT

Good day,

Is there any update?

Thank you!

**Comment by v-chetsh** [comment]
@s209395 - Just wanted to inform you that the engineering team has worked on it but we do not have exact ETA to share for public release.
We will inform you once it is rollout publicly.

**Comment by s209395** [comment]
Hi @HunaidHanfee-MSFT

Good day,

Is there any update?

Thank you!

**Comment by v-chetsh** [comment]
@s209395 - We are checking  the status of bug internally and let you know the updates.

**Comment by s209395** [comment]
Hi @Prasad-MSFT @v-chetsh @HunaidHanfee-MSFT 

Good day,

Thank you so much.

Appreciate your assistance in attending to our concerns/inquiries.
