### ISSUE TITLE
[Android] Summary ignored in notifications

### ISSUE THREAD

**Issue by matthiasdilger** [MicrosoftDocs/msteams-docs#4390]
The activity interface allows for a summary property to bet set. This is shown in the notification on desktop, web and iOS but not on Android. Please also implement it on Android, thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ad9f167-7d29-f933-7b47-60bd744899b1
* Version Independent ID: 8097fcbd-adcc-ce49-a378-426c65af9296
* Content: [Send proactive messages - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/send-proactive-messages?tabs=dotnet)
* Content Source: [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/bots/how-to/conversations/send-proactive-messages.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **anclear**

**Comment by matthiasdilger** [comment]
@HunaidHanfee-MSFT 

When the bot sends an activity to the user like so (node.js):

context.sendActivity({ attachments: [adaptiveCard], summary: "my summary" });

Teams clients on desktop, web and ios show "my summary" in the notification that pops up for the user instead of "<Bot> sent a card". It would be great if Android could also use the summary property in the notification.

**Comment by HunaidHanfee-MSFT** [comment]
@matthiasdilger The fix is being tested internally. It needs to pass multiple stages and because of that we don't have an exact ETA to share. I will update you once it is out in public. 

Thanks

**Comment by matthiasdilger** [comment]
This issue has been fixed, thanks
