### ISSUE TITLE
Teams 'Save message' doesn't work if the content is an adaptive card from a bot

### ISSUE THREAD

**Issue by JordyGit** [MicrosoftDocs/msteams-docs#4391]
Hi,

In teams it possible to save a message so you can find it back easily.

![scr](https://user-images.githubusercontent.com/33500507/137440686-4228eba2-9066-4d06-b5d5-2970b855a4b6.png)

If the message contains normal text this works fine, even with a bot, **but from the moment there is no text but only an adaptive card as an attachment the save message button doesn't work anymore**. 

The button is present and shows a clicked animation but doesn't actually save the message in that case.

Wkr,

**Comment by v-chetsh** [comment]
@JordyGit - We are checking it with engineering team and let you know the updates.

**Comment by Nivedipa-MSFT** [comment]
@JordyGit - We are checking it with engineering team and let you know the updates.

**Comment by Nivedipa-MSFT** [comment]
@JordyGit - Engineering team is working on the bug fix. We will let you know once we have any updates on it.

**Comment by ChetanSharma-msft** [comment]
Hello @JordyGit - We are actively checking the updates with engineering team and let you know once we have any.

**Comment by ChetanSharma-msft** [comment]
Hello @JordyGit - We are actively checking the updates with engineering team and let you know once we have any.

**Comment by Nivedipa-MSFT** [comment]
@JordyGit - We received an update from the engineering team stating that this feature is not supported in T2.1.
