### ISSUE TITLE
What is the Preliminary checklist?

### ISSUE THREAD

**Issue by nastassiar** [MicrosoftDocs/msteams-docs#4392]
Step 3 says:

Go to the Preliminary checklist and review the test cases that are difficult to automate.

But there is nothing in the developer portal called preliminary checklist within the developer portal

![image](https://user-images.githubusercontent.com/2245717/137536530-2529f8fb-e168-4b1f-89c5-f39a06427a96.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3df9a819-4eb0-e650-ef6b-5eeaa265c317
* Version Independent ID: ed71ed64-970d-7820-4229-c1e6896a8896
* Content: [Prepare your store submission - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist)
* Content Source: [msteams-platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist.md)
* Product: **msteams**
* GitHub Login: @heath-hamilton
* Microsoft Alias: **surbhigupta**

**Comment by Nivedipa-MSFT** [comment]
hi @nastassiar, For preliminary checklist go to below link 
https://dev.teams.microsoft.com/appvalidation.html

**Comment by Nivedipa-MSFT** [comment]
@nastassiar - Could you please confirm if the above suggestion helped you in any way or are you still facing the issue?

**Comment by v-chetsh** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.
