### ISSUE TITLE
'Leave call'-sound keeps playing when changing chats

### ISSUE THREAD

**Issue by JordyGit** [MicrosoftDocs/msteams-docs#4396]
I've had the next issue a few times in the Teams client where someone adds me to a call (private call becoming a group call), and I leave the call early (before the initial two persons in the call end the call).

When leaving the call teams makes a 'leaving call'-sound which is normal.
-> The moment I browse to another chat, this sounds plays again, which is not normal. 
I can repeat this sound when I browse again to the chat of the ongoing call (without joining the call) and again browsing to another chat, which again triggers the sound to play.

**Comment by v-chetsh** [comment]
Hello @JordyGit - We will check on it from our end and let you know the updates.

**Comment by JordyGit** [comment]
Thank you!

My desktop client: 1.4.00.35564 (64-bit). It was last updated on 2/02/2022.

**Comment by Nivedipa-MSFT** [comment]
@JordyGit - We are able to repro this issue and we have raised a bug for it. We will let you know once we get updates on it.

**Comment by Nivedipa-MSFT** [comment]
@JordyGit - Engineering team is looking into this bug.
Currently we do not have any ETA to share but we will let you know once we get any update from them.

**Comment by Nivedipa-MSFT** [comment]
@JordyGit - The bug has fixed. Could you please test and confirm on this? Thanks.
