### ISSUE TITLE
[Authoring] InputDate field values will be 1 day off

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#4401]
Copied bug from: https://github.com/microsoft/AdaptiveCards/issues/6587 

**Details from original post:**
### Target Application

Microsoft Teams

### Application Operating System

Windows

### Schema Version

1.4

### Problem Description

We have been using the Input.Date field in a Microsoft Teams Bot in our company. Usually used for people announcing days off or vacations. For some time now, in some cases, we get the values for the dates with 1 day offset backwards. 
For example, if I enter 10/22/2021 then, in my bot implementation I get 10/21/2021. I logged the messages the closest I possibly can in our bot implementation. 
We are using the Java bot implementation from: https://github.com/microsoft/botbuilder-java/
Microsoft Teams version: 1.4.00.26376 (64-bit).

I also want to mention that it doesn't always happen. For example, for some colleagues it works well from their mobile version of Teams. Desktop will fail.

### Expected Outcome

I would expect to get the date that was entered: 10/22/2021.

### Actual Outcome

Instead I god 10/21/2021.

### Card JSON

```JSON
{"showTimeoutWarning":true,"type":"AdaptiveCard","version":"1.4","body":[{"type":"TextBlock","weight":"default","text":"Please enter the date","wrap":false},{"type":"Input.Date","placeholder":"Date","id":"vacationDayDate"},{"type":"Input.Text","placeholder":"Obs./Approved by","id":"vacationDayObservation","isMultiline":"false"},{"type":"Input.ChoiceSet","placeholder":"Select a vacation type","id":"vacationType","value":"DAY_OFF","choices":[{"title":"DAY_OFF","value":"DAY_OFF"},{"title":"MEDICAL","value":"MEDICAL"}]},{"type":"ActionSet","actions":[{"type":"Action.Submit","title":"Take this vacation day","data":{"value":"takeSelectedDay"}},{"type":"Action.Submit","title":"Take today a vacation day","data":{"value":"takeToday"}},{"type":"Action.Submit","title":"Take tomorrow a vacation day","data":{"value":"takeTomorrow"}}]}]}
```

### Repro Steps

_No response_---
#### Document Details

⚠ *Do not edit this section.It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Cards reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **surbhigupta12**

**Comment by Prasad-MSFT** [comment]
@Zet89, The bug is fixed now.Please try to update your Teams version and check. Attaching screenshot below for reference:
Desktop:
![MicrosoftTeams-image](https://user-images.githubusercontent.com/62237649/141606518-af79c283-4b23-4fae-aca4-a3589ff85745.png)
Web:
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/62237649/141606524-f2c8afb9-12be-4f45-8e58-6640118bca5d.png)

**Comment by Prasad-MSFT** [comment]
Closing the issue for now. Please feel free to reopen if needed.
