### ISSUE TITLE
Teams Bot Notification Message for Adaptive Card not showing correctly

### ISSUE THREAD

**Issue by vinoth-berkmons** [MicrosoftDocs/msteams-docs#4405]
Hi, 
When I post card in meeting / personal chat It only show 'Sent a card' in notification. We tried the stackoverflow solution in which we have to modify the summary but its not working now. however it show summary in chat instead of 'Sent a card'.

stackoverflow link https://stackoverflow.com/questions/61229084/how-to-change-notification-text-when-bot-sends-an-adaptive-card-in-microsoft-tea

![image](https://user-images.githubusercontent.com/22914143/137860224-cc7c43a0-df32-4729-aecd-55aeaef15c61.png)

![image](https://user-images.githubusercontent.com/22914143/137860319-ccc71d96-7e4b-4518-9806-1e9f1a10c9c7.png)

**Comment by Nivedipa-MSFT** [comment]
@vinoth-berkmons - You want summary and Sent a card both in notification?

**Comment by Nivedipa-MSFT** [comment]
@matthiasdilger - We have raised the bug for this issue.Concern team is looking into it.We will check the status and update you.

**Comment by Nivedipa-MSFT** [comment]
@matthiasdilger -This bug has fixed.Please check and let us know if you are still facing the issue

**Comment by matthiasdilger** [comment]
Hi @Nivedipa-MSFT I updated to latest dev preview on Mac and restarted the client as well but the issue persists (both for Teams builtin-in and Mac native notifications). Summary is still not shown in notification.

**Comment by Nivedipa-MSFT** [comment]
@matthiasdilger - We got to know that the fix is not pushed publicly. Team is working on it. We will update you once it is out completely.

**Comment by matthiasdilger** [comment]
@Nivedipa-MSFT Confirm that this has been fixed, thank you.

**Comment by vinoth-berkmons** [comment]
Thanks everyone!

**Comment by vinoth-berkmons** [comment]
Still I'm getting same notification **'Sent a card'**. 

And the version I'm using  **1.4.00.29469 (64-bit). It was last updated on 11-11-2021.**

![image](https://user-images.githubusercontent.com/22914143/142361306-918ac7fc-a9d0-44f3-a422-870725adcd53.png)

**Comment by Nivedipa-MSFT** [comment]
@vinoth-berkmons -We got update from engineering team. The fix will be rolled out real soon

**Comment by kasturi15** [comment]
> @vinoth-berkmons -We got update from engineering team. The fix will be rolled out real soon

@Nivedipa-MSFT  Is this rolled out?

**Comment by Nivedipa-MSFT** [comment]
@vinoth-berkmons, @matthiasdilger, @kasturi15 -  This issue has fixed. Could you please check it at once.

**Comment by matthiasdilger** [comment]
@Nivedipa-MSFT It works fine for me on Mac

**Comment by v-chetsh** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.
