### ISSUE TITLE
Not able to attach files in Teams after opening a bot chat window.

### ISSUE THREAD

**Issue by astuj** [MicrosoftDocs/msteams-docs#4414]
Hi, steps to repo the bug. 

1) Chat with a bot that does not have Upload and download files enabled.
2) Open any other chat window

The attachment icon disappears and I am not able to upload/send any files to another user. Once teams is restarted I am again able to upload/send files.

<img width="995" alt="Screenshot 2021-10-20 at 6 45 44 PM" src="https://user-images.githubusercontent.com/20801184/138100095-2d8eb1f6-57d4-41fd-9785-e1589042d8df.png">

**Comment by Prasad-MSFT** [comment]
@astuj - This issue is fixed now. Please update MS Teams desktop version and check.
