### ISSUE TITLE
Add a section: How to send a message or card back to the conversation on a task module submit

### ISSUE THREAD

**Issue by vamboda** [MicrosoftDocs/msteams-docs#4417]
[Enter feedback here]
Hi:
I am part of the Teams Platform Engineering group. I have below feedback to improve the task module or action command documentation:
1.  There is a lot of teams specific jargon on this page. Can we please add some GIFs for the task module examples? 
2. Although the page mentioned proactive messaging to the conversation, some readers are getting lost in details and missing out on the core scenario information, which is to send a message to the chat after the task module submit. Can we add a specific section (on this page instead of a link to refer to), which talks about how to post a `message` or `card` back to the same chat by the bot during the task module submit? It would be great to see some GIFs illustrating this scenario.

Happy to chat for any further details.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fb0c2d8-f880-c260-d0be-6b9467e47f8c
* Version Independent ID: 7820ffc9-5260-c818-f5fb-672801a67d00
* Content: [Respond to the task module submit action - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/action-commands/respond-to-task-module-submit?tabs=dotnet%2Cdotnet-1)
* Content Source: [msteams-platform/messaging-extensions/how-to/action-commands/respond-to-task-module-submit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/messaging-extensions/how-to/action-commands/respond-to-task-module-submit.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **anclear**

**Comment by v-chetsh** [comment]
@vamboda - Thanks for suggesting the feedback.
We will check on it and redirect it to doc team accordingly.
