### ISSUE TITLE
meetingStage is not working for Teams room clients

### ISSUE THREAD

**Issue by SubbaReddi** [MicrosoftDocs/msteams-docs#4431]
Hi Team,
meetingStage renders black for Teams Rooms clients. Isn’t it possible to share and collaborate in a Teams Room device.
If not possible, Adding a note in documentation will help.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62ce7ca6-3ea8-ccca-5c59-92a638303aea
* Version Independent ID: d9a2d747-41cc-add6-f281-4210e888654e
* Content: [Enable and configure your apps for Teams meetings - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings#context-property)
* Content Source: [msteams-platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by SubbaReddi** [comment]
@v-chetsh: Here are the Repro steps:
Create meeting in Teams
Install Miro app and configure tab to meeting.
Join meeting in "Teams room client" and in Desktop client
Click on Miro app in meeting
Click on meeting stage option to share app in meeting
It shows fine in Desktop client
Showing blank screen in Teams room client.

Screenshot from Desktop Teams:
![image](https://user-images.githubusercontent.com/69682598/139527430-be543657-a7a9-49b2-8096-f56204600241.png)

**Comment by Nivedipa-MSFT** [comment]
@SubbaReddi - Meetingstage not supported for Teams Room Client.We are closing this issue now.If you have any issue feel free to reopen.

**Comment by SubbaReddi** [comment]
@Nivedipa-MSFT: As it is not supported i requested to update in documentation. Hope that can be done?

**Comment by v-chetsh** [comment]
Redirecting it to doc-enhancement team.

**Comment by Githamza** [comment]
I would like to know if the meeting Share stage is supported in Teams web client ? if not any vision of releasing this improvement ?

**Comment by SubbaReddi** [comment]
@Githamza: If the app is shared from Desktop teams, web teams client users will be able to see the app. But Web client users cannot see side panel and share the app. As this request was created with separate context, You may need to post new request for feature release information. So that respective team will respond.
