### ISSUE TITLE
Deep linking to the scheduling dialog always set required attendee.

### ISSUE THREAD

**Issue by yuukitakeuchi** [MicrosoftDocs/msteams-docs#4433]
I want to call the scheduling dialog with the required attendees empty.
But, if I set even one parameter, the required attendees will set login user.
　ex link: https://teams.microsoft.com/l/meeting/new?subject=a

If I do not set anything, the required attendees empty, but I want to set other params.
Is there any way?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45541337-ecd7-5cf6-cbe4-3f0d2f39aa79
* Version Independent ID: 6b4203f0-2844-06c9-eaa3-9cc03e6f76c0
* Content: [Create deep links - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links)
* Content Source: [msteams-platform/concepts/build-and-test/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/build-and-test/deep-links.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Meghana-MSFT** [comment]
@yuukitakeuchi - Engineering team has confirmed that this behavior is by design.
