### ISSUE TITLE
Adaptive card date picker date values are reduced by  one day after submitted the form.

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#4438]
Copied bug from: https://github.com/microsoft/AdaptiveCards/issues/6628 

**Details from original post:**
# Platform

What platform is your issue or question related to?

.Net core SDK  3.1 with Chat bot framework 4
Ms teams version is 1.4.00.26376 (64-bit),
Adaptive card version : 1.2

If you're an author, who are you sending cards to?
my user 
![MicrosoftTeams-image](https://user-images.githubusercontent.com/92978625/138446615-2415d29c-a2ef-48b8-bf20-831f0f271b6b.png)

# Version of SDK

3.1.4

# Issue

I am rendering my application in Bot framework now .In which I am using adaptive cards .
In which ,I have two date picker controls .They are start date and end date.
After submitting the form the start date value was changed by one day . Why adaptive card not 
keeping the original values after the submission?

example : 

Startdate : 28/10/2021
End date :28/10/2021

After submission from Ms teams ,the values became changed as 

Startdate : 27/10/2021
End date :28/10/2021

Adaptive card version : 1.2

---
#### Document Details

⚠ *Do not edit this section.It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Cards reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **surbhigupta12**

**Comment by kamarajPasupathi** [comment]
> @kamarajPasupathi - We have repro this issue and already raised the bug for it. Concerned team is looking into it. We will update you on the same.

Any updates on this issue?

**Comment by Nivedipa-MSFT** [comment]
@kamarajPasupathi - Concerned team is looking into it.Right now we don't have any ETA to share.If there is any update we will share you.

**Comment by Nivedipa-MSFT** [comment]
@kamarajPasupathi - This issue has fixed now. Could you please update the Teams version and check again.

**Comment by kamarajPasupathi** [comment]
> kamaraj

Thanks, team. The issues are resolved in the latest version of MS teams. It works fine without any issues:.
