### ISSUE TITLE
Links with ' are wrong formatted / have wrong preview

### ISSUE THREAD

**Issue by mnp-mid** [MicrosoftDocs/msteams-docs#444]
By sending the link
https://en.wikipedia.org/wiki/Don't_repeat_yourself

=> Teams is creating a link and shows a preview to
https://en.wikipedia.org/wiki/Don

![image](https://user-images.githubusercontent.com/33545902/52548901-8b98b880-2dd0-11e9-8caa-64d03738fdb9.png)

**Comment by Wajeed-msft** [comment]
Thanks for reporting this. I have raise UI bug for this.
