### ISSUE TITLE
Since recently Teams on a phone asks for providing password on a daily basis

### ISSUE THREAD

**Issue by marchewek** [MicrosoftDocs/msteams-docs#445]
Issue appears on a mobile device only (Galaxy S7) - on the PC it doesn't appear.
I've cleared the data (producing another issue (#446) so I will see if it helped with this one.

**Comment by Wajeed-msft** [comment]
@marchewek - Could you please use the feature to **share and send** issues which are facing on you mobile device? Once you login, just shake your phone which will give you option to report an issue. This will provide us details required to investigate further.

**Comment by marchewek** [comment]
I'm shaking the phone since 2 minutes and nothing is happening.

**Comment by marchewek** [comment]
Ok, I see the option in Teams' settings as well. I will send the logs once the issue happens again.
As noted in the report - I've cleared app data, so currently the logs do not contain any occurence of the problem.

**Comment by marchewek** [comment]
I've already been asked to re-login. I would have sent the email with logs, however I get the error "You no longer have access to this org in Teams. Try contacting your admin." Though I still have the access to _this org_ in the desktop version.

**Comment by Wajeed-msft** [comment]
@marchewek - This issue has been fixed. Could you please try at your end and confirm it?
