### ISSUE TITLE
Task module with React component doesn't open

### ISSUE THREAD

**Issue by WhiteCyClop** [MicrosoftDocs/msteams-docs#4452]
I have a Teams bot (.Net Core 3.1 + Bot SDK 4.0) and I call task module from it to render my React app. A React app is a SPA located at the same App Service as a bot. It works fine at the local stand and at the developer's stand, but at the customer's test stand, after calling the task module, a problem arises.

At desktop windows app there is happening nothing at first time, after the second click of the button to open the task module, an error appears at the bottom of the adaptive card:

![image](https://user-images.githubusercontent.com/47722281/139003692-af9683c8-be18-4b09-98f8-898706785299.png)

There is an error in the Developer Tools:

![image](https://user-images.githubusercontent.com/47722281/139003721-2eb6c5d2-8daf-4223-a81f-5108e45aef86.png)

I don't know what is app id 80cfe66c-a58c-4d76-a4d2-86a837f9cb22 at console errors, my bot has another app id.

I also tried to open this task module in popup application mode, it returns an error window:

![image](https://user-images.githubusercontent.com/47722281/139003755-3e60213f-9269-4084-bf5c-3e74073c01fb.png)

In the Developer Tools, in this case, I have the following errors:

![image](https://user-images.githubusercontent.com/47722281/139003789-02b41c02-6b9b-42b7-808b-50696f72cea3.png)

When I try to open my React app from the browser or use it as a tab for my bot, it works fine. What should be the problem with opening it as a task module? Maybe I need to do some extra steps in the Microsoft Teams admin center?

**Comment by HunaidHanfee-MSFT** [comment]
This is weird, I didn't get anything in the logs also. Are the customer Teams under VM?

**Comment by HunaidHanfee-MSFT** [comment]
You also don't have repro at your end on Teams desktop?

**Comment by WhiteCyClop** [comment]
Hello!

The customer has not yet tried to work with this functionality, because first we want to make sure that it works as developers. We have implemented the necessary functionality, deployed it to our dev Azure, and everything works fine there. Then we deployed the bot in the customer's Azure to test it with them, but upon initial verification by the developers we ran into the above issues.

So answering your questions: 
- I don't know if the customer's Teams is under VM and what is the version of customers's client yet;
- The error is reproduced at our end on Teams desktop for the bot deployed at customer's Azure;
- We tried to open it in normal chat.

Next week I will try to test this functionality with the customer, but afraid that we will face the same error

**Comment by WhiteCyClop** [comment]
I think that I found a way to solve the problem. I installed the bot through a local upload of the manifest, but then I found out that it was also added to the list of applications for our organization, and apparently there was some kind of collision between them. After I uninstalled the application from my desktop Teams and installed it from the application pool - the error disappeared. For other developers all works fine too. We’ve asked customer to reproduce the same steps, so, if it will also succeed we will close this issue.

**Comment by HunaidHanfee-MSFT** [comment]
@WhiteCyClop, Can you please confirm what is application pool?

**Comment by HunaidHanfee-MSFT** [comment]
Thank you for updating and sharing the solution. Let us know if that solve issue at customer end as well.

**Comment by WhiteCyClop** [comment]
I mean that there is a list of app's enabled to our organization that we can manage at teams admin center, so when I enter the name of our app at "Find an app" field - I can add it:

![image](https://user-images.githubusercontent.com/47722281/140978477-437987ce-638f-436f-8f00-e576b37a2395.png)

I will definitely report the results of the check by the customer

**Comment by WhiteCyClop** [comment]
The checking by customer is delayed, but I think everything will work well. So I close the issue, if there are any difficulties, then will reopened it. Thanks for your help @HunaidHanfee-MSFT!
