### ISSUE TITLE
After cleaning data on phone, Teams does not show team or group chats I belong to

### ISSUE THREAD

**Issue by marchewek** [MicrosoftDocs/msteams-docs#446]
Having been asked for the password already more than a dozen of times I've decided to clear application data on my Galaxy S7. After re-login Team shows neither teams nor group chats that I belong to. Activity is also empty, though I do not use it very often.
It did say "there were trouble getting your data" and 1:1 chats synchronized properly.

**Comment by marchewek** [comment]
I've sent an email with logs regarding this topic.

**Comment by Wajeed-msft** [comment]
@marchewek - Are you still facing this issue?
