### ISSUE TITLE
Open Task module with deep link outside Teams

### ISSUE THREAD

**Issue by SRRepswal** [MicrosoftDocs/msteams-docs#4475]
I have a custom tab and inside tab, it is loading a URL in iframe. Here I am displaying couple of records and each record have some actions. On click on action I am trying to open Task module with deep linking but it is not working.

```
const taskModuleInfo = {
      title: "Test",
      url: 'https://site.leafletcorp.com:890/bl/teams.htm,
      width: 1000,
      height: 700
    };
    microsoftTeams.tasks.startTask(taskModuleInfo);
```

Second Way I tried is:
```
const taskModuleInfo = {
      title: "Test",
      url: 'https://teams.microsoft.com/l/task/bbbe6c58-326e-4c82-a8c2-xxxxxxxxxxx?url=https://site.leafletcorp.com:890/bl/teams.htm&height=700&width=1500&title=Test Document&completionBotId=99d339ee-5417-4f8b-898f-xxxxxxxxxxx',
      width: 1000,
      height: 700
    };
    microsoftTeams.tasks.startTask(taskModuleInfo);
```

It is not working in any case. Can anybody help me here?

**Comment by SRRepswal** [comment]
@Nivedipa-MSFT Any update on this?

**Comment by Nivedipa-MSFT** [comment]
@SRRepswal - Concerned team is working on it.We will update you.

**Comment by SRRepswal** [comment]
> ing team is working on it. We will check and share the updates with you.

Any update on the same?

**Comment by Nivedipa-MSFT** [comment]
@SRRepswal - **The URL to be used in the task module deep link should have a domain available in validDomains array in the app manifest.**

We have tried below deeplink and added *.youtube.com in validdomains in app manifest file. and the deep-link to open an embedded youtube video on a task module is working on web and desktop Teams client as well as in mobile client.

Deeplink : https://teams.microsoft.com/l/task/ca6614d0-7043-42c2-a18f-1122b9b22b07?url=https://www.youtube.com/embed/tgbNymZ7vqY&height=medium&width=medium&title=one

![image](https://user-images.githubusercontent.com/92150070/160329672-a7271620-3cc6-400b-bcb9-0dd6169310b5.png)

**Comment by elenaviter** [comment]
Hi, @SRRepswal 

Confirming that deep-link [to a task module] works as a feature on any client (Web, Desktop MacOS, iOS at least]. Check the information below, you may find it useful while diagnosing what's wrong with your setup. 

We had a similar issue while crafting the deep link to the task module in an attempt to get it working from an adaptive card sent through GraphAPI on behalf of a User [by message extension]. There are a few nuances that might be the reason:

- in the [deep link template](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/task-modules/invoking-task-modules#task-module-deep-link-syntax)

  `https://teams.microsoft.com/l/task/APP_ID?url=<TaskInfo.url>&height=<TaskInfo.height>&width=<TaskInfo.width>&title=. <TaskInfo.title>&completionBotId=BOT_APP_ID`

  for both "BOT_APP_ID" and "APP_ID" you probably need the same app id which is actually your **MS bot app id** is. 
  You also might discover this id through GraphAPI call in [GraphAPI explorer](https://developer.microsoft.com/en-us/graph/graph-explorer) - a handy thing.
  
  **GET** https://graph.microsoft.com/beta/me/teamwork/installedApps?$expand=teamsApp
  **Response** will contain the list of teams App installed for your user, in format 
  ```
  {
            "id": "Y2***********************************",
            "teamsApp": {
                "id": "32******-****-****-****-************",
                "externalId": "7f******-****-****-****-************",
                "displayName": "^^^^^^",
                "distributionMethod": "organization"
            }
        }
  ```
  And the id which made things work for us is BOT_APP_ID=APP_ID="externalId"
  

- Also, the `url` parameter of a deep link should be URL-encoded. E.g. (Python, but just to get the idea)

  ```
  from urllib.parse import quote
  your_task_module_html_url_encoded = quote(your_task_module_html_url, safe='')
  task_module_deep_link = f"https://teams.microsoft.com/l/task/{APP_ID}?url={your_task_module_html_url_encoded}&height=430&width=510&title=Playback&completionBotId={BOT_APP_ID}"

  ```

- Complete message with the attachments for the illustration purpose.
```
{
    "body": {
        "contentType": "html",
        "content": "<attachment id=\"d20139434cfc4b6098a74a61d093585c\"></attachment>"
    },
    "attachments": [
        {
            "id": "d20139434cfc4b6098a74a61d093585c",
            "contentType": "application/vnd.microsoft.card.adaptive",
            "contentUrl": null,
            "content": "{  \"type\": \"AdaptiveCard\",  \"body\": [    {      \"text\": \"https://MY_HOST.ngrok.io/audio_icon\",      \"id\": \"audio_url\",      \"isVisible\": false,      \"type\": \"TextBlock\"    },    {      \"text\": \"Duration: 242\",      \"wrap\": true,      \"type\": \"TextBlock\"    },    {      \"columns\": [        {          \"width\": \"auto\",          \"items\": [            {              \"size\": \"small\",              \"url\": \"https://MY_HOST.ngrok.io/icon_audio\",              \"height\": \"auto\",              \"type\": \"Image\"            }          ],          \"spacing\": \"Small\",          \"separator\": true,          \"type\": \"Column\"        },        {          \"width\": \"auto\",          \"items\": [            {              \"selectAction\": {                \"url\": \"https://teams.microsoft.com/l/task/APP_ID?url=https%3A%2F%2FMY_HOST.ngrok.io%2Fpb_html%3Furl%3Dhttps%3A%2F%2FMY_HOST.ngrok.io%2Faudio_sample&height=430&width=510&title=Playback&completionBotId= BOT_APP_ID\",                \"type\": \"Action.OpenUrl\"              },              \"size\": \"small\",              \"url\": \"https://MY_HOST.ngrok.io/icon_audio_pb\",              \"height\": \"auto\",              \"type\": \"Image\"            }          ],          \"spacing\": \"Small\",          \"type\": \"Column\"        }      ],      \"type\": \"ColumnSet\"    }  ],  \"version\": \"1.3\"}",
            "name": null,
            "thumbnailUrl": null
        }
```

- With web Teams, you can examine some insights on what is exactly wrong with dev-tools console

**Comment by SRRepswal** [comment]
> 

Is it possible to open Task module apart from task module? For eg. I have an Teams custom application and it have tabs and personal application. Inside tab and personal application, I am loading a third party application. I want to open task module from that third party application(loaded inside Teams Personal app or channel custom tab)

**Comment by Nivedipa-MSFT** [comment]
@SRRepswal - Using the Microsoft Teams SDK, you can invoke task modules from buttons, links, or menus on your tab. For more information, see [using task modules in tabs](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/task-modules/task-modules-tabs).

**Comment by SRRepswal** [comment]
@Nivedipa-MSFT - Still it is not working for me. While I am putting the URL in new tab of the browser but in same window, it is not opening Task Module. 
Code: 
`microsoftTeams.initialize();

    const taskModuleInfo = {
      title: "Test",
      url: 'https://teams.microsoft.com/l/task/c10b0dfa-f8c1-4a9f-9a29-8d273091ab7a?url=' + encodeURIComponent('https://site.leafletcorp.com:8904/bl/teams.htm') + '&height=700&width=1500&title=Test Document&completionBotId=41f9d12f-84a9-4d16-8a48-03cf699cab30',
      width: 1000,
      height: 700
    };
    microsoftTeams.tasks.startTask(taskModuleInfo);`
    
    Above is the code executing onClick. It is not opening but while I am opening the Task Module URL in separate tab, it is opening for me. Below is the final task module URL for me:
    
    `https://teams.microsoft.com/l/task/c10b0dfa-f8c1-4a9f-9a29-8d273091ab7a?url=https%3A%2F%2Fsite.leafletcorp.com%3A8904%2Fbl%2Fteams.htm&height=700&width=1500&title=Test`

Can you please check why it is not working on onClick event?

**Comment by Nivedipa-MSFT** [comment]
@SRRepswal  - Have you added the task module deep link URL domain in validDomains array in the app manifest?

**Comment by SRRepswal** [comment]
> link URL domain in va

@Nivedipa-MSFT - Yes. Added

**Comment by Nivedipa-MSFT** [comment]
@SRRepswal - We are checking this internally. We will update you soon.

**Comment by SRRepswal** [comment]
![TeamsOpen](https://user-images.githubusercontent.com/86677097/161100755-ed6ba11d-9c3a-483c-8c60-658fc19b590f.PNG)

@Nivedipa-MSFT 
In Attached screenshot, There are open buttons. I have imported TeamsJS. And creating microsoftTeams object and initializing. On click Open button, I want to open task module.

**Comment by Nivedipa-MSFT** [comment]
@SRRepswal - We are checking this internally. We will update you soon.

**Comment by SRRepswal** [comment]
@Nivedipa-MSFT 
I think I am trying to open deeplink of Task module in tab not in Task module.
I am loading an <iframe>-based widget which I have already done on Bot

**Comment by Nivedipa-MSFT** [comment]
@SRRepswal - If you use any iframeable url in taskmoduleinfo url then it will work. But you are trying to use deeplink url of task module which is not iframeable.

**Comment by SRRepswal** [comment]
@Nivedipa-MSFT 
Can you provide sample JSON.

**Comment by Nivedipa-MSFT** [comment]
@SRRepswal - We have used following code.

      ```
      protected override Task<TaskModuleResponse> OnTeamsTaskModuleFetchAsync(ITurnContext<IInvokeActivity> turnContext, TaskModuleRequest taskModuleRequest, CancellationToken cancellationToken)
        {
            var asJobject = JObject.FromObject(taskModuleRequest.Data);
            var value = asJobject.ToObject<CardTaskFetchValue<string>>()?.Data;

            var taskInfo = new TaskModuleTaskInfo();
            switch (value)
            {
                case TaskModuleIds.Bing:
                    taskInfo.Url = "https://www.bing.com";
                    SetTaskInfo(taskInfo, TaskModuleUIConstants.Bing);
                    break;
            
                default:
                    break;
            }

            return Task.FromResult(taskInfo.ToTaskModuleResponse());
        }

```
![TaskModule](https://user-images.githubusercontent.com/92150070/161692689-bde32c02-0bf3-4f8e-a61b-f5dca7029055.png)



When click on Bing then the iframable url www.bing.com is opened in taskmodule.

![Bing](https://user-images.githubusercontent.com/92150070/161692758-3e78a51b-7634-4998-894a-2894f761c85c.png)

**Comment by SRRepswal** [comment]
> @SRRepswal - We have used following code.
> 
> ```
>   protected override Task<TaskModuleResponse> OnTeamsTaskModuleFetchAsync(ITurnContext<IInvokeActivity> turnContext, TaskModuleRequest taskModuleRequest, CancellationToken cancellationToken)
>     {
>         var asJobject = JObject.FromObject(taskModuleRequest.Data);
>         var value = asJobject.ToObject<CardTaskFetchValue<string>>()?.Data;
> 
>         var taskInfo = new TaskModuleTaskInfo();
>         switch (value)
>         {
>             case TaskModuleIds.Bing:
>                 taskInfo.Url = "https://www.bing.com";
>                 SetTaskInfo(taskInfo, TaskModuleUIConstants.Bing);
>                 break;
>         
>             default:
>                 break;
>         }
> 
>         return Task.FromResult(taskInfo.ToTaskModuleResponse());
>     }
> ```
> 
> ![TaskModule](https://user-images.githubusercontent.com/92150070/161693610-1444d4c1-c183-4c9a-acf9-4439e106ee0e.png)
> 
> When click on Bing then the iframable url [www.bing.com](http://www.bing.com) is opened in taskmodule.
> 
> ![Bing](https://user-images.githubusercontent.com/92150070/161694084-1da8c924-1df5-42ec-8b57-5ec71984054f.png)

I am able to open Task module from Adaptive card but not opening in my scenario

**Comment by Nivedipa-MSFT** [comment]
@SRRepswal - Is your third party application Teams application? You need to add iframable url in validdomains of Third party Teams application?
