### ISSUE TITLE
Need more information along with few sample examples to understand the implementation steps

### ISSUE THREAD

**Issue by SourabhMK** [MicrosoftDocs/msteams-docs#4476]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45541337-ecd7-5cf6-cbe4-3f0d2f39aa79
* Version Independent ID: 6b4203f0-2844-06c9-eaa3-9cc03e6f76c0
* Content: [Create deep links - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links)
* Content Source: [msteams-platform/concepts/build-and-test/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/build-and-test/deep-links.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by v-chetsh** [comment]
@SourabhMK - Could you please confirm if your issue has resolved with above suggestion or still looking for any help?

**Comment by Meghana-MSFT** [comment]
Closing this issue. Feel free to reopen this issue for any more queries.

Thank you

**Comment by SourabhMK** [comment]
Issue has been resolved

Regards,
*Sourabh Kulkarni*

Programmer Analyst | G N Solutions Pvt. Ltd
<http://www.globalnestsolutions.com/>. | ***@***.***
***@***.***?subject=Hello%20Dipal>|  US - O:  (844)
324-5043 | Mob. +91 8495045188

**Comment by SourabhMK** [comment]
Feedback is also positively given

Regards,
*Sourabh Kulkarni*

Programmer Analyst | G N Solutions Pvt. Ltd
<http://www.globalnestsolutions.com/>. | ***@***.***
***@***.***?subject=Hello%20Dipal>|  US - O:  (844)
324-5043 | Mob. +91 8495045188
