### ISSUE TITLE
Add information for supported method for retrieving user MRI

### ISSUE THREAD

**Issue by TheBluLion** [MicrosoftDocs/msteams-docs#4488]
This document references user MRIs for user specific views but provides no instructions or samples on how to retrieve user mri for implementation. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47dee5d9-bd9f-f550-8fc2-c2e3b67bba65
* Version Independent ID: 04264d26-1036-342a-e0ea-5edadebc3352
* Content: [Overview of Universal Actions for Adaptive Cards - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?tabs=mobile)
* Content Source: [msteams-platform/task-modules-and-cards/cards/Universal-actions-for-adaptive-cards/Overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/Universal-actions-for-adaptive-cards/Overview.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by v-chetsh** [comment]
@TheBluLion - I think getting User MRI is the part of SDK and TeamsChannelAccount Class where channel id is the actual MRI value for user.

Reference link:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.bot.schema.teams.teamschannelaccount?view=botbuilder-dotnet-stable#properties

**Comment by v-chetsh** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.
