### ISSUE TITLE
[Rendering] RichTextBlock Date/Time Format is broken

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#4489]
Copied bug from: https://github.com/microsoft/AdaptiveCards/issues/6194 

**Details from original post:**
# Target Platform

Please list the platform(s) that your application is targeting and remove platforms you are not targeting:
- NodeJS
- iOS
- Android
- WPF
- UWP

# Target Application

Teams

# Problem Description

RichTextBlocks do not render dates and times when using TextRun for formatting.  There is a workaround using columns and columnsets, but the alignment of the text is not perfect if the text sizes do not match.  This occurs when viewing the card from within Teams desktop app or the web page.  When viewing from the app studio it renders fine as shown in the screenshots below

# Screenshot

App Studio
![AppStudio](https://user-images.githubusercontent.com/8108397/129049715-74ee45ba-5d16-438d-b7b7-837b8f426a42.png)

Web
![Web](https://user-images.githubusercontent.com/8108397/129049716-61102118-08e9-42c3-8502-b0499daeaa6a.png)

Teams Client
![Teams](https://user-images.githubusercontent.com/8108397/129049717-bb436809-aff9-4536-9547-3b6264f21a00.png)

# Card JSON

```
{
  "type": "AdaptiveCard",
  "version": "1.2",
  "body": [
    {
      "type": "RichTextBlock",
      "inlines": [
        {
          "type": "TextRun",
          "weight": "bolder",
          "text": "RichTextBlock (error)"
        },
        {
          "type": "TextRun",
          "size": "small",
          "weight": "lighter",
          "text": " {{DATE(2021-06-22T17:00:10Z,SHORT)}} at {{TIME(2021-06-22T17:00:10Z)}}"
        }
      ]
    },
    {
      "type": "ColumnSet",
      "columns": [
        {
          "type": "Column",
          "width": "auto",
          "verticalContentAlignment": "bottom",
          
          "items": [
            {
              "type": "TextBlock",
              "text": "ColumnSet Alignment",
              "wrap": true,
              "weight": "bolder"
            }
          ]
        },
        {
          "type": "Column",
          "width": "auto",
          "items": [
            {
              "type": "TextBlock",
              "size": "small",
              "weight": "lighter",
              "text": " {{DATE(2021-06-22T17:00:10Z,SHORT)}} at {{TIME(2021-06-22T17:00:10Z)}}",
              "wrap": true
            }
          ]
        }
      ]
    },
    {
      "type": "ColumnSet",
      "columns": [
        {
          "type": "Column",
          "width": "auto",
          "items": [
            {
              "type": "TextBlock",
              "text": "ColumnSet Workaround",
              "wrap": true,
              "weight": "bolder"
            }
          ]
        },
        {
          "type": "Column",
          "width": "auto",
          "items": [
            {
              "type": "TextBlock",
              "weight": "lighter",
              "text": " {{DATE(2021-06-22T17:00:10Z,SHORT)}} at {{TIME(2021-06-22T17:00:10Z)}}",
              "wrap": true
            }
          ]
        }
      ]
    }
  ]
}
```

---
#### Document Details

⚠ *Do not edit this section.It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Cards reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **surbhigupta12**

**Comment by v-chetsh** [comment]
Could you please confirm if your issue has resolved with above suggestion or still looking for any help?

**Comment by theentropic** [comment]
@v-chetsh I didn't bother trying, as @Prasad-MSFT mentioned they can repro the issue in the Teams web client, which will cause our app to fail submission to the teams app store due to this bug.  Once it's fixed in both places I'd be happy to test.

**Comment by theentropic** [comment]
@v-chetsh @Prasad-MSFT Did get around to checking on my desktop client, can confirm it is working there.

**Comment by Prasad-MSFT** [comment]
@theentropic - The issue now seems to be fixed in Teams web client as well. Please do verify.
![image](https://user-images.githubusercontent.com/62237649/149878951-60d4ae37-6c06-42ba-aa49-d903581277bd.png)
