### ISSUE TITLE
Some Icons in the Planner Tab are broken

### ISSUE THREAD

**Issue by iseries** [MicrosoftDocs/msteams-docs#450]
Some icons are broken when using the Planner. See image:

![image](https://user-images.githubusercontent.com/6272363/52620951-53fc4000-2ea6-11e9-961e-0c3926aab6e5.png)

- Microsoft Windows 10
- Microsoft Teams 1.2.00.1758

**Comment by iseries** [comment]
Please tell me if you need more informations. I like the planner but without the icons it looks very confusion.

**Comment by Wajeed-msft** [comment]
Looking into this.

**Comment by iseries** [comment]
@Wajeed-msft I just want to inform you that the icons are now shown. So, if the problem is solved (?) this ticket can be closed.

**Comment by Wajeed-msft** [comment]
Seems like some intermittent issue which is resolved now. Please re-open if you face this in future.
