### ISSUE TITLE
Fix documentation on preview property

### ISSUE THREAD

**Issue by aosolis** [MicrosoftDocs/msteams-docs#4507]
I think this text is misleading/confusing:
> You can display a preview of an Adaptive Card or Office 365 Connector card in the result list using its preview property. The preview property is not necessary if the results are already Hero or Thumbnail cards. If you use the preview attachment, it must be either a Hero or Thumbnail card. If no preview property is specified, the preview of the card fails and nothing is displayed.

1. There's no result list for link unfurling
2. Need to describe how the preview is used in link unfurling, with screenshots. Not many are aware that the preview card can be expanded (full card)/collapsed (preview card).
3. "If no preview property is specified, the preview of the card fails and nothing is displayed." --> This basically says link unfurling won't work in that case-- let's describe what the developer should do (call to action) instead of a passive description of the failure case.

Perhaps something like
 "If you're sending an adaptive card or O365 connector card, you must include a preview. The preview property must be a hero or thumbnail card." + description of how preview is used in link unfurling

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59bbff2e-4b80-f980-2ade-7c7a7950801e
* Version Independent ID: e837e1fd-ec0c-2d6f-b0db-b76cb2d268a4
* Content: [Link unfurling - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?tabs=dotnet)
* Content Source: [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/messaging-extensions/how-to/link-unfurling.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **anclear**

**Comment by aosolis** [comment]
@surbhigupta12 can we prioritize this doc fix? We've had multiple devs run into this issue.

Let's also add a link to the sample.

**Comment by Nivedipa-MSFT** [comment]
@aosolis - We are looking into this issue. We will update you

**Comment by juna-gupta** [comment]
@surbhigupta12 Preview card information is now moved to a different page, is that intentional?

Respond to search action command seems to include URL unfurling example. We should fix this.

**Comment by surbhigupta12** [comment]
> @surbhigupta12 Preview card information is now moved to a different page, is that intentional?
> 
> Respond to search action command seems to include URL unfurling example. We should fix this.

Hi @juna-gupta,

This is resolved:

**PR link**: [Doc Issue] [Respond to search command] by v-ypalikila · Pull Request #4768 · MicrosoftDocs/msteams-docs (github.com)

**Review site**: Respond to search command - Teams | Microsoft Docs
