### ISSUE TITLE
Connectors Window is blank sometimes

### ISSUE THREAD

**Issue by iseries** [MicrosoftDocs/msteams-docs#451]
Sometimes the Connectors-Window is blank. See image:
![image](https://user-images.githubusercontent.com/6272363/52623049-9aa06900-2eab-11e9-86bd-4d20bfd95aa0.png)

The content loads after 5-8 Seconds. Maybe a internet connection problem?

* Microsoft Windows 10
* Microsoft Teams 1.2.00.1758

**Comment by Wajeed-msft** [comment]
@iseries - This could be a cold start problem on a server right after deploying a new build. Please let us know if you are still facing this issue?

**Comment by iseries** [comment]
@Wajeed-msft I think it was "cold start problem". Now it works.
