### ISSUE TITLE
SSO Messaging Extension - update docs

### ISSUE THREAD

**Issue by SorinMiron** [MicrosoftDocs/msteams-docs#4516]
Please update the code from [Single sign-on support for messaging extensions](https://docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/enable-sso-auth-me) with following code:

```
var userTokenClient = turnContext.TurnState.Get<UserTokenClient>();
tokenExchangeResponse = await userTokenClient.ExchangeTokenAsync(
                 turnContext.Activity.From.Id,
                 _connectionName,
                 turnContext.Activity.ChannelId,
                 new TokenExchangeRequest
                 {
                     Token = tokenExchangeRequest.Token,
                 },
                 cancellationToken).ConfigureAwait(false);
```

instead of

```
 tokenExchangeResponse = await (turnContext.Adapter as IExtendedUserTokenProvider).ExchangeTokenAsync(
              turnContext,
              _connectionName,
              turnContext.Activity.From.Id,
              new TokenExchangeRequest
              {
                  Token = tokenExchangeRequest.Token,
              },
              cancellationToken).ConfigureAwait(false);
```

**(turnContext.Adapter as IExtendedUserTokenProvider) is null**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23057f0b-5f90-b05a-b360-b436282323e8
* Version Independent ID: 71f663ea-f741-5493-3d8c-24406606b8e2
* Content: [SSO support for your messaging extensions - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/enable-sso-auth-me)
* Content Source: [msteams-platform/messaging-extensions/how-to/enable-SSO-auth-me.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/messaging-extensions/how-to/enable-SSO-auth-me.md)
* Product: **msteams**
* GitHub Login: @KirtiPereira
* Microsoft Alias: **surbhigupta**

**Comment by Meghana-MSFT** [comment]
We are looking into this issue, We will update you.

**Comment by Meghana-MSFT** [comment]
current code gives the below exception. So please update the code accordingly.
![image](https://user-images.githubusercontent.com/81138249/142005317-67f38cbe-1adf-41cb-a016-2ad91cbbbf71.png)

Please add 
```
var userTokenClient = turnContext.TurnState.Get<UserTokenClient>();
tokenExchangeResponse = await userTokenClient.ExchangeTokenAsync(
                 turnContext.Activity.From.Id,
                 _connectionName,
                 turnContext.Activity.ChannelId,
                 new TokenExchangeRequest
                 {
                     Token = tokenExchangeRequest.Token,
                 },
                 cancellationToken).ConfigureAwait(false);

```

instead of 
```
 tokenExchangeResponse = await (turnContext.Adapter as IExtendedUserTokenProvider).ExchangeTokenAsync(
              turnContext,
              _connectionName,
              turnContext.Activity.From.Id,
              new TokenExchangeRequest
              {
                  Token = tokenExchangeRequest.Token,
              },
              cancellationToken).ConfigureAwait(false);

```
in [step 4](https://docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/enable-sso-auth-me#enable-sso-for-messaging-extensions-and-link-unfurling), try block of TokenIsExchangeable method
