### ISSUE TITLE
BROKEN AGAIN - AzureBlobStorage-hosted AdaptiveCard image-rendering broken on Teams iOS

### ISSUE THREAD

**Issue by aimskl** [MicrosoftDocs/msteams-docs#4518]
@Wajeed-msft @Nikitha-MSFT @Jagadeesh-MSFT @Prasad-MSFT @v-chetsh @Nivedipa-MSFT @Meghana-MSFT 

Please refer to issue #3124 for all the details. The symptoms are precisely the same!

Team, this issue was originally mentioned by us in April, and fixed by your team in June. The issue has returned.

As of Teams for iOS version 3.17.1 (and including 3.18.0), we are unable to view images hosted in Azure public blob storage that are embedded in AdaptiveCards in Teams for iOS. Prior to this version it has been working fine since the mid-June fix. The images viewed via other Teams clients load fine.

Teams iOS logs indicate the same error as experienced before. Your code has regressed. Please fix!

Please refer to issue #3124 for all the details. The symptoms are precisely the same!

**Comment by Meghana-MSFT** [comment]
@aimskl - We are checking this with the engineering team. We will update you soon.

**Comment by Wajeed-msft** [comment]
@aimskl - do you have image URL which we can use to setup local repro quickly?

**Comment by aimskl** [comment]
@Wajeed-msft 

Please see here:
[https://x75skgszywhjg5xkwlp6isdh.blob.core.windows.net/b1ofzx6lkgaheyyaymuq81e9ukqv5zf5y57q7awb4d/1000.png](url)

**Comment by aimskl** [comment]
Hi @Wajeed-msft @Meghana-MSFT 
Any ETA on when the fix will be pushed out to the app store? 
Thank you

**Comment by Wajeed-msft** [comment]
@aimskl - we are able to repro this issue using image link provided by you. We have shared repro with engineering team who is looking into this. I will share update on this as soon as I hear back.

**Comment by aimskl** [comment]
@Wajeed-msft 
Thank you for your help and follow-up on this. Much appreciated.
Please would it be possible to ask the engineering to add this specific scenario to their automated testing regime. It is both annoying (for customers expecting reliable, documented functionality) and embarrassing (for your engineering team who has already once fixed this problem after a two month follow-up) that this issue continues to crop up, especially considering that everything in the scenario takes place within the Microsoft ecosystem of services.
Thanks

**Comment by Wajeed-msft** [comment]
@aimskl - **Updates:**  We were able to identify that the SDK update caused this regression. I'll keep you updated with the progress and any new insights.

**Comment by Wajeed-msft** [comment]
@aimskl - **Updates:**  Engineering team has raised PR to fix this issue. I'll keep this thread updated with the progress.

**Comment by Wajeed-msft** [comment]
@aimskl - **Updates:** Fix for this issue is merged. We will share updates on this once it is available in public store build.

**Comment by aimskl** [comment]
@Wajeed-msft  Thank you for the updates. Looking forward to the app store build...

**Comment by aimskl** [comment]
@Wajeed-msft 
This message is for the Microsoft Teams-related engineering team,
We are now approaching 1.5mths since this issue was first reported, and nearly one month since the fix was merged for public release.
Do you think it is normal to wait so long for a fix to a customer process that was broken as a result of your not checking thoroughly enough for full integration between your own services? Please do recall this issue was already fixed in mid-2021 after another two month wait.
This should be an easy fix and immediately pushed out to customers in the next available public build. We recognize that each build is a long and complex process, but there should be a way to merge priority fixes into existing scheduled releases.
I think it is pretty unacceptable from a customer experience perspective to have our fully-supported/documented process broken by you, our service provider, and then have to wait an unreasonable multiple months for you to get us the fix.
Please please get this out to us as soon as possible. We are at a standstill on our Teams desktops due to this silly issue. 
Please would you make sure our scenario (which as mentioned before is fully supported as part of your suite of API services) is added to your automated testing routine so that even if such an issue is caused indirectly by a third-party (ie Apple's SDK update in this instance), that YOU will know about first, rather than us having to report it to you and wait for resolution.
Thank you @Wajeed-msft for all your help in reporting this for us to the engineering team.

**Comment by Wajeed-msft** [comment]
@aimskl - A combination of unforeseen disruption in internal release schedule as well as long review cycle of Apple/Google store due to holidays resulted in delayed release of the Teams app in stores. The circumstances were unusual and we are working to make sure this doesn't happen in the future.

**Comment by aimskl** [comment]
Hi @Wajeed-msft - we can confirm now that as of Teams iOS version 3.21.0 (released a few days ago), the issue is now fixed. Thank you again for all your help in getting this to the attention of the devs and for impressing on them the importance of getting it (and keeping it) fixed for clients. Much appreciated indeed.
