### ISSUE TITLE
Teams shows/sends/receives another user's messages

### ISSUE THREAD

**Issue by nickmcleod** [MicrosoftDocs/msteams-docs#452]
Windows 10, desktop client.

I went to work in Teams app today and found that although I was seemingly logged in (my pic and name appeared at top right of Teams window), the messages I saw were not mine but another user's. Before I realized, I sent a message to someone, and it was effectively sent from the other user's account. I also received incoming messages that were not for me but for the other user.

I logged out of Teams and logged in again, and everything was back to normal.

Likely related: A few days ago that other user created an Outlook profile on my machine during a troubleshooting process, and their work account was visible in the "Access work or school" settings area. However, they never logged into Teams (I didn't even log out, although my PC may have restarted since then) and since Teams shows that I was logged in as myself, I should never have seen their messages.

**Comment by Wajeed-msft** [comment]
@nickmcleod - Thanks for reporting this. We have raised bug for this, we will look into this.
