### ISSUE TITLE
SupportedPlatforms missing from manifest.json in 1.11

### ISSUE THREAD

**Issue by kpfeuffer** [MicrosoftDocs/msteams-docs#4521]
When using the Viva Connections Desktop Script, the generated Package contains the following option with manifest version 1.9

You could use the option **supportedPlatform** to hide the app from Teams for Android and iOS by only entereing desktop.

```
{
    [...]
    "staticTabs": [
        {
           [...]
            "scopes": ["personal"],
            "supportedPlatform" : ["desktop"]
        }
    ],
    [...]
}
```

I couldnt find any reference to that point in the Schema of Manifest Version 1.11 [found here](https://developer.microsoft.com/en-us/json-schemas/teams/v1.11/MicrosoftTeams.schema.json)

The removal was not mentioned in the documentation as far as I know.

When uploading the Package in the Teams Developer Portal, the Manifest seems to be updated to the Version 1.11 when checkin in the old Developer Portal's Manifest Previewl.

Has the option to limit Teams Apps to the Desktop been removed?

**Comment by Prasad-MSFT** [comment]
@kpfeuffer 
According to this doc(https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema#statictabs), the property "supportedPlatform" doesn't seems to be supported.

**Comment by kpfeuffer** [comment]
Is there a migration-path for desktop-only apps in Microsoft Teams (so Viva Connection Desktop still works) or is the feature completely deprecated?

**Comment by Prasad-MSFT** [comment]
Its still supported for 1P apps

**Comment by Meghana-MSFT** [comment]
@kpfeuffer - Closing this issue. Please feel free to reopen if you have any queries.

Thank you.
