### ISSUE TITLE
Outgoing web hooks and DLP?

### ISSUE THREAD

**Issue by Petri-X** [MicrosoftDocs/msteams-docs#4524]
Hi there,

While reading these, I wonder do have a risk of date leaking with outgoing web hooks? How we are able to control what content is exchanged using the outgoing web hooks.

What are the security best practices for the outgoing web hooks?
Please, try to avoid answer "channel privacy". 

rgs
Petri

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb9c5bd5-1ac6-dcc8-4ed6-d6aad2432776
* Version Independent ID: 43e90995-bba4-86b6-1f1c-ab749e546a4b
* Content: [Create an Outgoing Webhook - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-outgoing-webhook?tabs=urljsonpayload%2Cdotnet)
* Content Source: [msteams-platform/webhooks-and-connectors/how-to/add-outgoing-webhook.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/webhooks-and-connectors/how-to/add-outgoing-webhook.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by HunaidHanfee-MSFT** [comment]
We are looking into this, I will get back to you soon

Thanks

**Comment by HunaidHanfee-MSFT** [comment]
All Outgoing webhook data (both inbound and outbound) are protected by DLP as the content is present in Teams channels and would be available in audit logs as well. 

Outgoing webhooks behave similar to 1:1 bots where Teams can decide to remove them if needed, and also disable org wide (as 3p app) via Teams admin center.

It is recommended to use the auth provided by the HMAC code to establish request/client trust. 
![image](https://user-images.githubusercontent.com/64194049/142259057-988618f5-fd23-4cbb-9551-55f842888472.png)

Let us know if you have any query, else we will close this issue.
Thanks
