### ISSUE TITLE
Task module not working in web/desktop app

### ISSUE THREAD

**Issue by bogdanbujdea** [MicrosoftDocs/msteams-docs#4527]
I'm using a task module to present additional data from an adaptive card but I can't understand why for some users it works and for others it doesn't. So far I deployed the bot + a Teams app in two organizations and in both of them a small percentage of users can open the task module from the Teams desktop app, a bigger percentage can also open it from the Web app, and all of them can open it from the Android app.

The error I'm receiving is this one (not very helpful):
![image](https://user-images.githubusercontent.com/793611/140700326-77b647f7-2e22-4d3e-8bda-25d2ce0c87e6.png)

In the Network tab I don't see any requests being done, and on the Console tab I see this:
```
0.2-angular-jquery.min-eee9041.js:114 
        
       2021-11-08T07:23:41.012Z TaskModuleLaunchService: launchTaskModuleByInvoke failed: "could not find app definition for app 2a7e93ae-48b1-489e-8bee-448240713c06"
```
The id is not from an existing app so I have no idea where it got it.  I tried deleting the existing Teams app that is associated to the bot and creating it again, but the id remained the same.

This is the code for the button that opens the task module:

```
{
  "type": "ActionSet",
  "actions": [
    {
      "type": "Action.Submit",
      "title": "${details}",
      "data": {
        "msteams": {
          "type": "task/fetch"
        },
        "data": {
          "type": "project",
          "projectShortName": "${projectShortName}",
          "userId": "${userId}"
        }
      }
    }
  ],
  "horizontalAlignment": "Right",
  "spacing": "None"
}
```

I tried clearing the cache, reinstalling Teams, switching browsers/machines, but nothing works. So the problem is related to the account, but only if they try opening the task module in Teams for Web and Desktop. Besides the console log above I don't see other errors so that's all I've got. Can someone tell me in what situation that error appears?

I also added the full stack trace from the console:

```
0.2-angular-jquery.min-eee9041.js:114 
        
       2021-11-08T11:18:17.335Z TaskModuleLaunchService: launchTaskModuleByInvoke failed: "could not find app definition for app 2a7e93ae-48b1-489e-8bee-448240713c06"
(anonymous) @ 0.2-angular-jquery.min-eee9041.js:114
(anonymous) @ 3.2-app.min-6207963.js:1
(anonymous) @ 3.2-app.min-6207963.js:1
(anonymous) @ 3.2-app.min-6207963.js:1
f @ 0.2-angular-jquery.min-eee9041.js:127
(anonymous) @ 0.2-angular-jquery.min-eee9041.js:127
$eval @ 0.2-angular-jquery.min-eee9041.js:142
$digest @ 0.2-angular-jquery.min-eee9041.js:139
(anonymous) @ 3.2-app.min-6207963.js:1
$apply @ 0.2-angular-jquery.min-eee9041.js:142
(anonymous) @ 0.2-angular-jquery.min-eee9041.js:93
x @ 0.2-angular-jquery.min-eee9041.js:97
w.onload @ 0.2-angular-jquery.min-eee9041.js:98
load (async)
(anonymous) @ 0.2-angular-jquery.min-eee9041.js:98
r @ 0.2-angular-jquery.min-eee9041.js:94
g @ 0.2-angular-jquery.min-eee9041.js:91
f @ 0.2-angular-jquery.min-eee9041.js:127
(anonymous) @ 0.2-angular-jquery.min-eee9041.js:127
$eval @ 0.2-angular-jquery.min-eee9041.js:142
$digest @ 0.2-angular-jquery.min-eee9041.js:139
(anonymous) @ 3.2-app.min-6207963.js:1
(anonymous) @ 0.2-angular-jquery.min-eee9041.js:142
e @ 0.2-angular-jquery.min-eee9041.js:41
(anonymous) @ 0.2-angular-jquery.min-eee9041.js:44
setTimeout (async)
Zf.k.defer @ 0.2-angular-jquery.min-eee9041.js:44
$evalAsync @ 0.2-angular-jquery.min-eee9041.js:142
(anonymous) @ 0.2-angular-jquery.min-eee9041.js:126
g @ 0.2-angular-jquery.min-eee9041.js:127
then @ 0.2-angular-jquery.min-eee9041.js:128
(anonymous) @ 3.2-app.min-6207963.js:1
(anonymous) @ 3.2-app.min-6207963.js:1
(anonymous) @ 3.2-app.min-6207963.js:1
(anonymous) @ 3.2-app.min-6207963.js:1
(anonymous) @ 3.2-app.min-6207963.js:1
(anonymous) @ 3.2-app.min-6207963.js:1
(anonymous) @ 3.2-app.min-6207963.js:1
i @ 3.2-app.min-6207963.js:1
(anonymous) @ 3.2-app.min-6207963.js:1
(anonymous) @ 3.2-app.min-6207963.js:1
(anonymous) @ 3.2-app.min-6207963.js:1
(anonymous) @ 3.2-app.min-6207963.js:1
(anonymous) @ 3.2-app.min-6207963.js:1
(anonymous) @ 3.2-app.min-6207963.js:1
(anonymous) @ 3.2-app.min-6207963.js:1
(anonymous) @ 3.2-app.min-6207963.js:1
(anonymous) @ 3.2-app.min-6207963.js:1
(anonymous) @ 3.2-app.min-6207963.js:1
postMessage (async)
(anonymous) @ main-7638612421235844.js:28
next @ main-7638612421235844.js:28
postMessage @ main-7638612421235844.js:28
postMessage @ main-7638612421235844.js:28
reportCommandEvent @ main-7638612421235844.js:23
(anonymous) @ main-7638612421235844.js:28
Vu @ main-7638612421235844.js:28
executeEntityCommand @ main-7638612421235844.js:28
e.withValue @ 56065-7e951a3e5f878fdf.js:1
(anonymous) @ 56065-7e951a3e5f878fdf.js:1
(anonymous) @ 56065-7e951a3e5f878fdf.js:1
(anonymous) @ 56065-7e951a3e5f878fdf.js:1
(anonymous) @ 56065-7e951a3e5f878fdf.js:1
l @ 56065-7e951a3e5f878fdf.js:1
e.resolveField @ 56065-7e951a3e5f878fdf.js:1
(anonymous) @ 56065-7e951a3e5f878fdf.js:1
(anonymous) @ 56065-7e951a3e5f878fdf.js:1
(anonymous) @ 56065-7e951a3e5f878fdf.js:1
(anonymous) @ 56065-7e951a3e5f878fdf.js:1
l @ 56065-7e951a3e5f878fdf.js:1
l @ 56065-7e951a3e5f878fdf.js:1
(anonymous) @ 56065-7e951a3e5f878fdf.js:1
(anonymous) @ 56065-7e951a3e5f878fdf.js:1
(anonymous) @ 56065-7e951a3e5f878fdf.js:1
(anonymous) @ 56065-7e951a3e5f878fdf.js:1
l @ 56065-7e951a3e5f878fdf.js:1
e.resolveSelectionSet @ 56065-7e951a3e5f878fdf.js:1
(anonymous) @ 56065-7e951a3e5f878fdf.js:1
(anonymous) @ 56065-7e951a3e5f878fdf.js:1
(anonymous) @ 56065-7e951a3e5f878fdf.js:1
(anonymous) @ 56065-7e951a3e5f878fdf.js:1
l @ 56065-7e951a3e5f878fdf.js:1
e.resolveDocument @ 56065-7e951a3e5f878fdf.js:1
(anonymous) @ 56065-7e951a3e5f878fdf.js:1
(anonymous) @ 56065-7e951a3e5f878fdf.js:1
(anonymous) @ 56065-7e951a3e5f878fdf.js:1
(anonymous) @ 56065-7e951a3e5f878fdf.js:1
l @ 56065-7e951a3e5f878fdf.js:1
e.runResolvers @ 56065-7e951a3e5f878fdf.js:1
(anonymous) @ 56065-7e951a3e5f878fdf.js:1
(anonymous) @ 56065-7e951a3e5f878fdf.js:1
(anonymous) @ 56065-7e951a3e5f878fdf.js:1
m @ 56065-7e951a3e5f878fdf.js:1
b @ 56065-7e951a3e5f878fdf.js:1
value @ 56065-7e951a3e5f878fdf.js:1
(anonymous) @ 56065-7e951a3e5f878fdf.js:1
oe @ 56065-7e951a3e5f878fdf.js:1
next @ 56065-7e951a3e5f878fdf.js:1
m @ 56065-7e951a3e5f878fdf.js:1
b @ 56065-7e951a3e5f878fdf.js:1
value @ 56065-7e951a3e5f878fdf.js:1
(anonymous) @ 56065-7e951a3e5f878fdf.js:1
(anonymous) @ 56065-7e951a3e5f878fdf.js:1
Promise.then (async)
v @ 56065-7e951a3e5f878fdf.js:1
(anonymous) @ 56065-7e951a3e5f878fdf.js:1
e @ 56065-7e951a3e5f878fdf.js:1
value @ 56065-7e951a3e5f878fdf.js:1
complete @ 56065-7e951a3e5f878fdf.js:1
t.start @ 56065-7e951a3e5f878fdf.js:1
t @ 56065-7e951a3e5f878fdf.js:1
e.getObservableFromLink @ 56065-7e951a3e5f878fdf.js:1
(anonymous) @ 56065-7e951a3e5f878fdf.js:1
(anonymous) @ 56065-7e951a3e5f878fdf.js:1
(anonymous) @ 56065-7e951a3e5f878fdf.js:1
(anonymous) @ 56065-7e951a3e5f878fdf.js:1
(anonymous) @ 56065-7e951a3e5f878fdf.js:1
l @ 56065-7e951a3e5f878fdf.js:1
e.mutate @ 56065-7e951a3e5f878fdf.js:1
e.mutate @ 56065-7e951a3e5f878fdf.js:1
(anonymous) @ main-7638612421235844.js:23
(anonymous) @ 56065-7e951a3e5f878fdf.js:1
l @ 56065-7e951a3e5f878fdf.js:1
mutate @ main-7638612421235844.js:23
v.entityCommand @ main-7638612421235844.js:23
(anonymous) @ main-7638612421235844.js:23
a @ 56065-7e951a3e5f878fdf.js:1
Promise.then (async)
u @ 56065-7e951a3e5f878fdf.js:1
(anonymous) @ 56065-7e951a3e5f878fdf.js:1
l @ 56065-7e951a3e5f878fdf.js:1
yt @ main-7638612421235844.js:23
(anonymous) @ main-7638612421235844.js:23
processRequest @ main-7638612421235844.js:23
executeCommand @ main-7638612421235844.js:23
launchTaskModule @ main-7638612421235844.js:23
(anonymous) @ 15470-ed136e8c84e2acdf.js:1
(anonymous) @ 71217-66bd6d414919cb68.js:1
(anonymous) @ 56065-7e951a3e5f878fdf.js:1
l @ 56065-7e951a3e5f878fdf.js:1
f @ 71217-66bd6d414919cb68.js:1
I @ 71217-66bd6d414919cb68.js:1
K @ 74313-c7f3b9e1bf15c36b.js:1
(anonymous) @ 71217-66bd6d414919cb68.js:1
(anonymous) @ 56065-7e951a3e5f878fdf.js:1
l @ 56065-7e951a3e5f878fdf.js:1
(anonymous) @ 71217-66bd6d414919cb68.js:1
(anonymous) @ 71217-66bd6d414919cb68.js:1
a @ 56065-7e951a3e5f878fdf.js:1
Promise.then (async)
u @ 56065-7e951a3e5f878fdf.js:1
a @ 56065-7e951a3e5f878fdf.js:1
Promise.then (async)
u @ 56065-7e951a3e5f878fdf.js:1
(anonymous) @ 56065-7e951a3e5f878fdf.js:1
l @ 56065-7e951a3e5f878fdf.js:1
se @ 71217-66bd6d414919cb68.js:1
(anonymous) @ 71217-66bd6d414919cb68.js:1
(anonymous) @ adaptivecard-d87eb1b3a9bad282.js:1
(anonymous) @ 56065-7e951a3e5f878fdf.js:1
l @ 56065-7e951a3e5f878fdf.js:1
(anonymous) @ adaptivecard-d87eb1b3a9bad282.js:1
e.raiseExecuteActionEvent @ 35359-b2430d4b15d60de9.js:1
e.execute @ 35359-b2430d4b15d60de9.js:1
h.onClick @ 35359-b2430d4b15d60de9.js:1
t.click @ 35359-b2430d4b15d60de9.js:1
action.renderedElement.action.renderedElement.onclick @ 35359-b2430d4b15d60de9.js:1
onClick @ adaptivecard-d87eb1b3a9bad282.js:1
t.exports @ 2845-17c5ac283e0db11b.js:1
t.exports @ 2845-17c5ac283e0db11b.js:1
t.exports @ 2845-17c5ac283e0db11b.js:1
(anonymous) @ 2845-17c5ac283e0db11b.js:1
t.onClick @ fluentui-9d53c5a8af8090ef.js:1
t.exports @ 2845-17c5ac283e0db11b.js:1
t.exports @ 2845-17c5ac283e0db11b.js:1
t.exports @ 2845-17c5ac283e0db11b.js:1
(anonymous) @ 2845-17c5ac283e0db11b.js:1
Y @ fluentui-9d53c5a8af8090ef.js:1
s @ 56065-7e951a3e5f878fdf.js:1
d @ 56065-7e951a3e5f878fdf.js:1
(anonymous) @ 56065-7e951a3e5f878fdf.js:1
g @ 56065-7e951a3e5f878fdf.js:1
st @ 56065-7e951a3e5f878fdf.js:1
ot @ 56065-7e951a3e5f878fdf.js:1
ut @ 56065-7e951a3e5f878fdf.js:1
ht @ 56065-7e951a3e5f878fdf.js:1
L @ 56065-7e951a3e5f878fdf.js:1
V @ 56065-7e951a3e5f878fdf.js:1
$t @ 56065-7e951a3e5f878fdf.js:1
Jt @ 56065-7e951a3e5f878fdf.js:1
t.unstable_runWithPriority @ 56065-7e951a3e5f878fdf.js:1
Qi @ 56065-7e951a3e5f878fdf.js:1
D @ 56065-7e951a3e5f878fdf.js:1
Yt @ 56065-7e951a3e5f878fdf.js:1
Show 94 more frames
23.1-app.min-ad9fb2e.js:1 
        
       Uncaught (in promise) background blurring is not enabled
(anonymous) @ 3.1-app.min-ad9fb2e.js:1
e.retrieveDeviceBlurringCapability @ 3.1-app.min-ad9fb2e.js:1
e.onDevicesChanged @ 3.1-app.min-ad9fb2e.js:1
(anonymous) @ 3.1-app.min-ad9fb2e.js:1
(anonymous) @ skype-calling-pluginless.bundle-1c6ac7f.js:1
(anonymous) @ skype-calling-pluginless.bundle-1c6ac7f.js:1
e.raiseEvents @ skype-calling-pluginless.bundle-1c6ac7f.js:1
t._raiseEventImpl @ skype-calling-pluginless.bundle-1c6ac7f.js:1
(anonymous) @ skype-calling-pluginless.bundle-1c6ac7f.js:1
(anonymous) @ skype-calling-pluginless.bundle-1c6ac7f.js:1
Promise.then (async)
t._raiseDevicesChanged @ skype-calling-pluginless.bundle-1c6ac7f.js:1
(anonymous) @ skype-calling-pluginless.bundle-1c6ac7f.js:1
(anonymous) @ skype-calling-pluginless.bundle-1c6ac7f.js:1
(anonymous) @ skype-calling-pluginless.bundle-1c6ac7f.js:1
e.raiseEvents @ skype-calling-pluginless.bundle-1c6ac7f.js:1
t._raiseEventImpl @ skype-calling-pluginless.bundle-1c6ac7f.js:1
(anonymous) @ skype-calling-pluginless.bundle-1c6ac7f.js:1
t.onDevicesChanged @ skype-calling-pluginless.bundle-1c6ac7f.js:1
(anonymous) @ skype-calling-pluginless.bundle-1c6ac7f.js:1
(anonymous) @ skype-calling-pluginless.bundle-1c6ac7f.js:1
(anonymous) @ skype-calling-pluginless.bundle-1c6ac7f.js:1
e.raiseEvents @ skype-calling-pluginless.bundle-1c6ac7f.js:1
t._raiseEventImpl @ skype-calling-pluginless.bundle-1c6ac7f.js:1
(anonymous) @ skype-calling-pluginless.bundle-1c6ac7f.js:1
t.updateDevices @ skype-calling-pluginless.bundle-1c6ac7f.js:1
(anonymous) @ skype-calling-pluginless.bundle-1c6ac7f.js:1
Promise.then (async)
e.enumerateDevices @ skype-calling-pluginless.bundle-1c6ac7f.js:1
window.navigator.mediaDevices.window.navigator.mediaDevices.ondevicechange @ skype-calling-pluginless.bundle-1c6ac7f.js:1
```

**Comment by Nivedipa-MSFT** [comment]
@bogdanbujdea - Could you please share sample which you are referring.It helps us to repro the issue.

**Comment by WhiteCyClop** [comment]
Hello!

I am having a similar problem with my bot. Maybe the description from my issue will be useful in some way - https://github.com/MicrosoftDocs/msteams-docs/issues/4452. Unfortunately, I have not yet found a way to solve the problem

**Comment by bogdanbujdea** [comment]
@WhiteCyClop you are right, it might be the same issue.
@Nivedipa-MSFT I reproduced the issue with the sample: https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/54.teams-task-module

Steps:
1. I started ngrok, then I added the id/secret in the appsettings.json
2. I run the project and send a message to the bot

In the desktop app, for my account, it works as expected. I can click on any of the buttons and I see the popup 
![image](https://user-images.githubusercontent.com/793611/140740021-eea6aa18-2e6e-43b1-adfa-d85c7c07a3eb.png)


In the web app I'm using another account which was failing with my initial application as well, and now I see the same issue, so it seems to be account related.

![image](https://user-images.githubusercontent.com/793611/140740109-531f5d0a-4990-417e-82e2-b19e5c6b7e69.png)

Maybe this is related or not, but I tried deleting my apps because I thought the bot is somehow "attached" to an old one, but even after I deleted most of them they still appear in the "Recent" list and I can open the bot when I click them. Maybe the bot is "connected" to another app somehow and it fails because the app doesn't exist anymore? But why would that be only for certain users?
@WhiteCyClop is something similar happening to you too?

![image](https://user-images.githubusercontent.com/793611/140740295-234715bf-1eaf-402b-a188-c9ffe7bc8b39.png)

**Comment by WhiteCyClop** [comment]
As far as I know there are two separate lists for installed apps and apps at App Studio, so the applications themselves must be uninstalled separately like this:

![image](https://user-images.githubusercontent.com/47722281/140747467-0008821c-48f4-42e3-b46a-14d5f5569fdb.png)

But for me reinstalling the application this way does not solve the problem

**Comment by HunaidHanfee-MSFT** [comment]
I will try to check this issue with doing same as you and will see if I can repro.

**Comment by HunaidHanfee-MSFT** [comment]
@bogdanbujdea - Can you share bot Id and timestamps so that we can check and compare logs with @WhiteCyClop 's logs

**Comment by bogdanbujdea** [comment]
@HunaidHanfee-MSFT sure
2021-11-08T22:59:01.572Z and bot id a812be7c-693f-4a73-8327-253f2baf0f29

```
0.2-angular-jquery.min-eee9041.js:114 
        
       2021-11-08T22:59:01.572Z TaskModuleLaunchService: launchTaskModuleByInvoke failed: "could not find app definition for app "
```
for some reason there's no id at the end of the log like before, but it still doesn't work

**Comment by WhiteCyClop** [comment]
I think that I found a way to solve the problem, at least for me. I installed the bot through a local upload of the manifest, but then I found out that it was also added to the list of applications for our organization, and apparently there was some kind of collision between them. After I uninstalled the application from my desktop Teams and installed it from the application pool - the error disappeared for me and other developers. Hope this helps to resolve your problem too.

**Comment by bogdanbujdea** [comment]
@WhiteCyClop  What do you mean by "application pool"? The developer portal?

**Comment by WhiteCyClop** [comment]
No, it's list of app's enabled to your organization that you can find at teams admin center. Screenshot from the web, because I don't have access to our admin center:

![image](https://user-images.githubusercontent.com/47722281/140935014-1a1fb25f-b741-47f8-966c-57d54a9b546d.png)

**Comment by bogdanbujdea** [comment]
I removed the app from Teams and then I created it again from the developer portal. I then had to go to admin center to publish it because it was "Blocked". It said it might take a few hours so I'll wait because I still see the error but the good news is that it now looks for the correct app id.
```
0.2-angular-jquery.min-eee9041.js:114 
        
       2021-11-09T15:20:37.140Z TaskModuleLaunchService: launchTaskModuleByInvoke failed: "could not find app definition for app 1e82ad70-1e98-48d1-af65-3febe81ae1ac"
```

**Comment by HunaidHanfee-MSFT** [comment]
@bogdanbujdea - Please let us know, if that's resolve your issue as well.

**Comment by bogdanbujdea** [comment]
It still didn't work, but I found that if I install the app then it works. Previously I would just add the app to a channel, but it seems that I have to add the app as an user as well. So now I have to tell everyone to click on those 3 dots, find the app, open it and click on "Add". This will redirect them to the bot where they will be able to open the task module.
![image](https://user-images.githubusercontent.com/793611/141129393-8888bc0b-91c9-4909-ad85-dfa59cd33ed5.png)

@WhiteCyClop do you do the same or do you use some policy to install the app for all the users? I would prefer something that an admin could do for everyone instead of asking all the users to follow these steps.

**Comment by WhiteCyClop** [comment]
During testing and development, we install the application in the same way, but for production we use the functionality of the Teams admin center to automatically install the application to all users in the organization. Unfortunately, I cannot give a detailed description of how this is configured, since another employee is engaged in this.

**Comment by bogdanbujdea** [comment]
Thank you @WhiteCyClop! I did some tests for multiple users and it seems that this is the way to make it work, everyone has to manually install the application. @HunaidHanfee-MSFT I guess this can be closed now.
