### ISSUE TITLE
ReplyToId Inconsistency: Desktop vs Mobile

### ISSUE THREAD

**Issue by JordyGit** [MicrosoftDocs/msteams-docs#4530]
Hi,

Today we found a bug in our own Teams Bot using the Bot Framework where we couldn't Replace a previously sent message on mobile clients and an exception was throw (badRequest). (but we could for desktop clients without issues)

The root cause was the **ReplyToId which was the string "0" on mobile clients (IOS & Android) but the value null on the Desktop Teams client**, where we only checked for null in our code to not try to reply the message. So the bug was raised due to the inconsistency which I couldn't found documented somewhere.

I don't think this inconsistency is by design, so made this issue in the hope this could be aligned and bugs could be avoided in the future for other bot developers.

Wkr, 
Jordy

**Comment by Meghana-MSFT** [comment]
@JordyGit - Could you please share the repro steps so that we can try it locally?

**Comment by JordyGit** [comment]
It occurred in the next case for us:

1. Execute 'login' command to a bot, which prompts the OauthPrompt built in in the Bot Framework.
2. If the user logs in, we receive the token and we send the message 'you were logged in successfully'.
3. Instead of sending that message we tried to Replace the OauthPrompt message (which is not possible, see [Stackoverflow](https://stackoverflow.com/questions/60749382/replace-oauthprompt-card-after-the-user-has-logged-in/69899670#69899670)). But the ReplyToId which is set at that moment in our turnContext is the string "0" if it's a mobile teams client, and value null if it's a desktop teams client. 

The difference in value of ReplyToId from different clients looked odd to me so that is why I report it here. Hope this helps you to reproduce this issue.

**Comment by JordyGit** [comment]
There is no sample, it's just a login command triggering the OAuthPrompt from the Bot Framework (built in). We wrapped that one in our own dialog to be able to do things in front and after the built in prompt. We have a turnContext with a ReplyToId in the context activity.

**Comment by HunaidHanfee-MSFT** [comment]
We have tried multiple things from our side but unable to repro this issue. Could you please share minimal code snippet?

Thanks

**Comment by JordyGit** [comment]
Here is some code, just trigger/start the AuthenticateDialog from your bot.

File 1:
`public class OAuthPromptDialog : OAuthPrompt
    {
        public const string Id = "OAuthPromptDialog";

        public OAuthPromptDialog(IAuthenticationOptions options)
            : base(Id, new OAuthPromptSettings
            {
                ConnectionName = options.ConnectionName,
                Text = "To continue, you must first log in.",
                Title = "Log In",
                Timeout = 300000, // User has 5 minutes to login (1000 * 60 * 5)
                EndOnInvalidMessage = true,
            })
        {
        }
    }`

File 2:
`public class AuthenticateDialog : ComponentDialog
    {
        public const string Id = "AuthenticateDialog";
        private const string AuthenticationId = "AutenticationPromptId";
 
        public AuthenticateDialog() 
            : base(Id)
        {
            AddDialog(new WaterfallDialog(AuthenticationId, new List<WaterfallStep>()
            {
	            PromptSignInCardAsync,
	            ReplaceSignInCardAsync,
            }));
        }

        private async Task<DialogTurnResult> PromptSignInCardAsync(WaterfallStepContext stepContext, CancellationToken cancellationToken)
        {
           return await stepContext.BeginDialogAsync(OAuthPromptDialog.Id, cancellationToken: cancellationToken);
        }

        private async Task<DialogTurnResult> ReplaceSignInCardAsync(WaterfallStepContext stepContext, CancellationToken cancellationToken)
        {
	        if (!(stepContext.Result is TokenResponse token))
            {
                throw new Exception();
            }

            await stepContext.Context.ReplaceActivityAsync(new Activity(text:"logged in successfully"), cancellationToken);
    }`

File 3 (**Here we have the issue where we had to do 2 if checks because the desktop and mobile client returns a different response for ReplyToId**):
`public static class DialogHelper
    {
        /// <summary>
        /// Replaces the initiating activity with this activity (for example replaces an adaptive card in a sequential flow) if possible
        /// otherwise the activity will be send as a new message
        /// </summary>
        public static async Task ReplaceActivityAsync(this ITurnContext context, Activity activity, CancellationToken cancellationToken)
        {
            try
            {
                // Mobile Teams client will return "0" instead of null (like in desktop Teams client)
                if (context.Activity.ReplyToId != null && context.Activity.ReplyToId != "0")
                {
                    activity.Id = context.Activity.ReplyToId;
                    await context.UpdateActivityAsync(activity, cancellationToken);
                    return;
                }
            }
            catch (ErrorResponseException)
            {
                // If the request fails, it will still send the activity like normal
            }

            await context.SendActivityAsync(activity, cancellationToken);
        }
    }`

**Comment by HunaidHanfee-MSFT** [comment]
We have the repro, I am checking this with internal team. I will let you know the updates.

Thanks

**Comment by JordyGit** [comment]
Just an update, but today I noticed the **ReplyToId is now filled in from the Teams Desktop Client OAuthPrompt**, meaning it is possible to replace the login card with a notification the user was logged in in successfully. ReplyToId is not filled in yet on IOS or Android.

**Comment by Meghana-MSFT** [comment]
Thanks for the update, we are checking with the engineering team on the bug status, we will update you.

**Comment by JordyGit** [comment]
Just to keep this post up to date, the same behaviour as described in my message above applies up on today.

**Comment by cagrimunyas** [comment]
The issue still persists. This kills the experience on my bot as well.

**Comment by ArtiomRegino** [comment]
It's still reproduces. Any update from the engineering team ?

**Comment by Meghana-MSFT** [comment]
We have the following suggestion from engineering team. Could you please use version 4.19.+ of the bot framework.

Some features were added to help with message edits and deletions. 

4.19.0 release notes: [Release Bot Framework DotNet SDK 4.19.0 · microsoft/botbuilder-dotnet (github.com)](https://github.com/microsoft/botbuilder-dotnet/releases/tag/4.19.0)

[Support Teams message edit, message soft delete and message undelete activities](https://github.com/microsoft/botbuilder-dotnet/pull/6564)

**Comment by ArtiomRegino** [comment]
Hello, we're using version 4.22.9 in our code, and the issue with **ReplyToId** still persists.
We also reviewed the 4.19.0 release notes, and it seems that the changes made there do not address the current issue.
Could you please take another look?
