### ISSUE TITLE
composeExtension/selectItem is not supported in mobile

### ISSUE THREAD

**Issue by shsarda** [MicrosoftDocs/msteams-docs#4538]
In Receive user requests, the request type of name "composeExtension/selectItem" is not supported in mobile.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 469debbc-327b-5c18-126c-dc281513736f
* Version Independent ID: e7f25391-bbb5-9cca-07a8-1ab92bd28dcb
* Content: [Search with messaging extensions - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/messaging-extension-v3/search-extensions)
* Content Source: [msteams-platform/resources/messaging-extension-v3/search-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/resources/messaging-extension-v3/search-extensions.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by HunaidHanfee-MSFT** [comment]
We are looking into this. We will get back to you soon.

Thanks

**Comment by HunaidHanfee-MSFT** [comment]
We have repro of this issue at our end on Android 10, Microsoft Teams 1416/1.0.0.2021173701/1103. Could you please share the your version?

Thanks

**Comment by HunaidHanfee-MSFT** [comment]
We have raised a bug and internal Teams is looking it. I don't have an ETA to share but I will update you as soon I got anything.

Could you please share the your OS and Teams version?

Thanks

**Comment by v-chetsh** [comment]
@shsarda - Just wanted to inform you that composeExtension/selectItem is currently not supported in mobile and this is considered as a feature request.
So, it will get release at later point in time but we do not have exact ETA to share.
