### ISSUE TITLE
Getting 403 when trying to refresh the card using Action.Execute

### ISSUE THREAD

**Issue by Arpita1906** [MicrosoftDocs/msteams-docs#4540]
Hi,
I am getting 403 when trying to refresh card using Action.Execute. It works fine in case of personal chat with bot but in case of group chat and channel , it is returning 403. Let me know if there is any issue or I am missing anything

![Screen Shot 2021-11-10 at 9 57 36 AM](https://user-images.githubusercontent.com/70123502/141168117-cdf6d1a0-543a-4225-8c19-2f2e667f58ef.png)

---
![Screen Shot 2021-11-10 at 9 57 11 AM](https://user-images.githubusercontent.com/70123502/141168151-dbd498eb-076c-466a-9af5-59b6575d2fa0.png)

Attaching the sample manifest as well. groupchat and team is already selected for bot. Please let me know if I am missing anything.
[Archive.zip](https://github.com/MicrosoftDocs/msteams-docs/files/7514962/Archive.zip)

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 136ca1ab-f857-9add-b62e-df5bb14b1a1f
* Version Independent ID: e6530932-60c6-3875-2e07-1a64c6db3e68
* Content: [Work with Universal Actions for Adaptive Cards - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/work-with-universal-actions-for-adaptive-cards)
* Content Source: [msteams-platform/task-modules-and-cards/cards/Universal-actions-for-adaptive-cards/Work-with-Universal-Actions-for-Adaptive-Cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/Universal-actions-for-adaptive-cards/Work-with-Universal-Actions-for-Adaptive-Cards.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Arpita1906** [comment]
Looks like I explicitly need to add bot the teams/group chat to fix this issue . Is this expected ?

**Comment by HunaidHanfee-MSFT** [comment]
We are looking into this. I will get back to you soon.

Thanks

**Comment by HunaidHanfee-MSFT** [comment]
Could you please confirm, how are you sending card/message in channel if bot isn't installed?

**Comment by Arpita1906** [comment]
Thanks @HunaidHanfee-MSFT for looking into this. Bot is installed but it is not added to the group chat or teams explicitly. We are trying link unfurling. As part of composeExtension\queryLink action , we are sending an apaptive card as part of the response. To send this adaptive card we don't need to add bot to the teams or group chat

**Comment by Arpita1906** [comment]
Please let me know if you have more questions

**Comment by HunaidHanfee-MSFT** [comment]
Yes, you will need bot to be install in the chat. You can have a look at the doc to install the bot - 
https://docs.microsoft.com/en-us/microsoftteams/platform/resources/messaging-extension-v3/create-extensions?tabs=typescript#request-to-install-your-conversational-bot

Let us know if you have any query else we will close this issue. 
Thanks

**Comment by Arpita1906** [comment]
@HunaidHanfee-MSFT Can you please elaborate this little more. How justInTimeInstall will work ? Do I need to invoke any Graph API to install the bot or it will automatically install the bot on click of action if action has property justInTimeInstall set to true ?

**Comment by HunaidHanfee-MSFT** [comment]
Yes it will install the bot automatically, 
Have a look at this [sample](https://github.com/microsoft/BotBuilder-Samples/blob/9dac0f01e6063056cb3adc077e70e9a1a14b52f7/samples/csharp_dotnetcore/51.teams-messaging-extensions-action/Bots/TeamsMessagingExtensionsActionBot.cs#L225), here when calling  `TeamsInfo.GetMember` method if the bot is not installed in chat it will throw error as `BotNotInConversationRoster`. Handling that error we are responding with the justintimeinstallation card once you click on button it should get installed and start to work fine.

**Comment by Arpita1906** [comment]
Thanks @HunaidHanfee-MSFT . This works but user needs to click on a button to install the app . In this case "Continue" button. Is there any way we can install the app silently without any human intervention

**Comment by HunaidHanfee-MSFT** [comment]
https://docs.microsoft.com/en-us/graph/api/userteamwork-post-installedapps?view=graph-rest-1.0&tabs=http - Graph API is available to use.

**Comment by HunaidHanfee-MSFT** [comment]
Let us know if you have any query else we will close this issue.
Thanks
