### ISSUE TITLE
Validation fails for messaging extensions that initate actions

### ISSUE THREAD

**Issue by pablodiazgutierrez** [MicrosoftDocs/msteams-docs#455]
We are having trouble loading our manifest using App Studio, as well as submitting it to the store due to manifest validation errors. Our manifest is for a messaging extension that initiates actions, as documented in https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/messaging-extensions/create-extensions. Despite validation failing, we can side-load the manifest directly into Teams, and it works perfectly, so we think this might be a problem with the validaton parser not accepting these new fields. Could you please advise?

Here is a capture of the error message we get on validation:
![](https://s3.amazonaws.com/prod_pm_files/cf/66/1a/fc/4a/ec/86/90/Screen_Shot_2019-02-12_at_2.09.28_PM.png).

...and we're sent to "Learn more" in https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema which indeed does not support the mentioned properties "type", "inputType" and "fetchTask".

**Comment by billbliss** [comment]
We haven't yet formally updated the manifest version, so you have to link to the devPreview version.

Change the value of `$schema` in your manifest.json file to `https://raw.githubusercontent.com/OfficeDev/microsoft-teams-app-schema/preview/DevPreview/MicrosoftTeams.schema.json` and it will work.

**Comment by pablodiazgutierrez** [comment]
Will that allow us to submit the add-on to the store?

**Comment by clearab** [comment]
Yes, if you use the developer preview manifest you should still be able to submit to the store.

**Comment by pablodiazgutierrez** [comment]
@clearab I don't think that's correct. When I upload the manifest to the seller dashboard, I get the same [message about a schema error](https://s3.amazonaws.com/prod_pm_files/73/1e/ff/4c/e5/1b/a3/fe/Screen_Shot_2019-03-21_at_10.22.32_AM.png). I guess we'll have to wait a bit...

> Yes, if you use the developer preview manifest you should still be able to submit to the store.

**Comment by pablodiazgutierrez** [comment]
> Yes, if you use the developer preview manifest you should still be able to submit to the store.

@clearab  I don't think that's right... I updated the manifest schema and I'm getting the same error message. Can I assume the store is validating against their own predefined schema and not the one provided in the manifest?

**Comment by kartikluke** [comment]
> We haven't yet formally updated the manifest version, so you have to link to the devPreview version.
> 
> Change the value of `$schema` in your manifest.json file to `https://raw.githubusercontent.com/OfficeDev/microsoft-teams-app-schema/preview/DevPreview/MicrosoftTeams.schema.json` and it will work.

This doesn't work. Still getting the same errors. I'm unable to even sideload the app. Something I was able to do before.

**Comment by kartikluke** [comment]
> Yes, if you use the developer preview manifest you should still be able to submit to the store.

I'm getting this error when I submit to the store with manifestVersion as `devPreview`.

![Screen Shot 2019-05-05 at 11 06 12 PM](https://user-images.githubusercontent.com/3857139/57208838-760fe500-6ff3-11e9-8ed2-88aa32e1dbb0.png)

@clearab @Wajeed-msft
