### ISSUE TITLE
Input.Date Adaptive card Bug - Choosing year from calendar.

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#4553]
Copied bug from: https://github.com/microsoft/AdaptiveCards/issues/6719 

**Details from original post:**
### Problem Statement

In Input.Date Adaptive card, How to change the year easily?? Should I need to choose different year date by click back button?
<img width="431" alt="Input date Adaptive card Bug" src="https://user-images.githubusercontent.com/24470490/141239088-ba581eb0-479f-4ea6-aca7-6b04ea16ea9e.PNG">

Previously, the Input.Date adpative card used to look like the following:

![IMG_20211110_174043](https://user-images.githubusercontent.com/24470490/141239170-4d88dee5-a253-4ac6-92ae-c6085172ab29.jpg)
![IMG_20211110_174059](https://user-images.githubusercontent.com/24470490/141239147-b66c6138-3ec8-4c5e-829a-b84edcd972ad.jpg)

Is this feature deprecated by https://adaptivecards.io/explorer ??
If so, why they make it complex to choose a date??

Awaiting your reply,
Regards.

### Proposed solution

I am not able to choose the year that is very earlier.

There is no drop down enabled to choose year.

![IMG_20211110_174043](https://user-images.githubusercontent.com/24470490/141239449-46bee3ef-c6f3-4926-937d-5f099e57aa78.jpg)

![IMG_20211110_174059](https://user-images.githubusercontent.com/24470490/141239491-be12bfe9-9aa4-4c1b-895f-13246e140304.jpg)

Awaiting your reply,
Regards.

### Alternatives or Workarounds

_No response_---
#### Document Details

⚠ *Do not edit this section.It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Cards reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **surbhigupta12**

**Comment by HunaidHanfee-MSFT** [comment]
Thanks for informing about this, I will confirm with internal team and get back to you.

**Comment by HunaidHanfee-MSFT** [comment]
I tried few scenario and was not able to change UI look and feel. I will get back to you with update as soon as I hear from the internal team.

Thanks

**Comment by HunaidHanfee-MSFT** [comment]
We have confirmed internally and this is an known issue and team is working on it. It would get fix in upcoming quarter.

Thanks
