### ISSUE TITLE
Faulty time notation in ATOM feed

### ISSUE THREAD

**Issue by MarksPoint** [MicrosoftDocs/msteams-docs#4557]
I stumbled across this issue when I tried to load the RSS (ATOM) feed in my RSS reader.

**Issue:** The `<updated>` field doesn't always have a valid RFC 3339 date-time value.

For instance, the currently returned feed for 
https://docs.microsoft.com/en-us/microsoftteams/platform/feed.atom

has this first entry:

```xml
<entry>
	<title type="html"><![CDATA[Hide apps until Admin approves]]></title>
	<id>https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/design/enable-app-customization#hide-teams-app-until-admin-approves</id>
	<link href="https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/design/enable-app-customization?referrer=whats.new.rssfeed#hide-teams-app-until-admin-approves"/>
	<updated>2021-10-05T012:41:01+05:30</updated>
	<summary type="html"><![CDATA[To enhance Teams app experience, you can hide an app from users by default until admin allows to unhide the app.</br></br>Would you please provide your <a href="https://github.com/MicrosoftDocs/msteams-docs/issues/new?title=&body=%0A%0A%5BEnter%20feedback%20here%5D%0A%0A%0A---%0A%23%23%23%23%20Document%20Details%0A%0A%E2%9A%A0%20*Do%20not%20edit%20this%20section.%20It%20is%20required%20for%20docs.microsoft.com%20%E2%9E%9F%20GitHub%20issue%20linking.*%0A%0A*%20ID%3A%2054a9aab3-9fa7-9870-ea07-fd8504e21874%0A*%20Version%20Independent%20ID%3A%2044cad9f8-b5d8-5e2f-4615-0160b73e89f7%0A*%20Content%3A%20%5BCustomize%20your%20Teams%20app%20-%20Teams%5D(https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fmicrosoftteams%2Fplatform%2Fconcepts%2Fdesign%2Fenable-app-customization%3Freferrer%3Dwhats.new.rssfeed%23hide-teams-app-until-admin-approves)%0A*%20Content%20Source%3A%20%5Bmsteams-platform%2Fconcepts%2Fdesign%2Fenable-app-customization.md%5D(https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fmsteams-docs%2Fblob%2Fmaster%2Fmsteams-platform%2Fconcepts%2Fdesign%2Fenable-app-customization.md)%0A*%20Product%3A%20**msteams**%0A*%20GitHub%20Login%3A%20%40heath-hamilton%0A*%20Microsoft%20Alias%3A%20**surbhigupta**">feedback</a>? It is important to us. ]]></summary>
	<category label="new" term="new"/>
</entry>
```

The value for the `<updated>` node is `2021-10-05T012:41:01+05:30`, and this does not conform to the RFC 3339 standard (there are 3 digits after the T, where there should be at 2).

There are more issues with the feed, according to this validation service by W3C, but the above mentioned issue made my RSS reader break on this feed.

https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fmicrosoftteams%2Fplatform%2Ffeed.atom

Regards,

Mark 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ffc338ca-2f9a-9f79-bc7c-07bbd7534c78
* Version Independent ID: 0c40a2b1-4b71-5ec9-82b5-371dadddf2cc
* Content: [What's new - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/whats-new)
* Content Source: [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/whats-new.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Meghana-MSFT** [comment]
This issue seems to be related Teams product, Hence adding the correct label.

Thanks for understanding.

**Comment by Meghana-MSFT** [comment]
Could you please share more information on this?

**Comment by MarksPoint** [comment]
Hi Meghana,

Not sure what more information you're looking for. I was hoping to be clear in my OP.
Let me know what you're missing.

Mark

**Comment by Wajeed-msft** [comment]
@MarksPoint - I am fixing it.

**Comment by Wajeed-msft** [comment]
@MarksPoint  - I see that few other dates are not valid RFC 3339 date-time. I have raised PR to update it.

**Comment by MarksPoint** [comment]
I want to confirm that the feed is now working correctly! Thanks for the update.
![image](https://user-images.githubusercontent.com/16799069/142849109-42b97e1e-9f23-41eb-a4f1-98551bd6da2c.png)
