### ISSUE TITLE
Something went wrong error

### ISSUE THREAD

**Issue by lafesfat** [MicrosoftDocs/msteams-docs#456]
Whenever I get to the install section I get a "something went wrong, please try again later error".
This persist even when I remove the "Valid domain cannot use tunnel site" and "Full name should not contain keywords like Microsoft or Microsoft Teams" warnings the test and distribute page show via removing the tabs and just editing the name respectively.

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 98cd21c7-e87c-3c5b-7574-998a355f9f08
* Version Independent ID: 5e312707-facc-03fc-af59-90267d0c7b8a
* Content: [Get started with C#/.NET - Teams](https://docs.microsoft.com/nl-nl/microsoftteams/platform/get-started/get-started-dotnet-app-studio#build-and-run-the-sample)
* Content Source: [msteams-platform/get-started/get-started-dotnet-app-studio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/get-started/get-started-dotnet-app-studio.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Gousia-MSFT** [comment]
@lafesfat  - Could you please check if [Allow sideloading of external app](https://docs.microsoft.com/en-us/MicrosoftTeams/enable-features-office-365?redirectSourcePath=%252farticle%252fAdministrator-settings-for-Microsoft-Teams-3966a3f5-7e0f-4ea9-a402-41888f455ba2#external-apps) is enabled for your tenant?

**Comment by lafesfat** [comment]
@Gousia-MSFT as it turns out it wasn't and turning in on fixed it. Thank you for the help

**Comment by EtharAlali** [comment]
> @lafesfat - Could you please check if [Allow sideloading of external app](https://docs.microsoft.com/en-us/MicrosoftTeams/enable-features-office-365?redirectSourcePath=%252farticle%252fAdministrator-settings-for-Microsoft-Teams-3966a3f5-7e0f-4ea9-a402-41888f455ba2#external-apps) is enabled for your tenant?

Right, what is "sideloading of external apps" called now (16/08/2019)? Being new to this incarnation of Teams, the terminology doesn't mean anything in any of the documents any more.  Is it just enable External apps and setting up an external domain?

**Comment by clearab** [comment]
If your tenant has migrated to the new permission model, you will enable sideloading of apps (custom app upload) here: 

https://docs.microsoft.com/en-us/microsoftteams/teams-app-setup-policies#create-a-custom-app-setup-policy
