### ISSUE TITLE
"Creating a channel conversation" posts the message to the private 1to1 dialog

### ISSUE THREAD

**Issue by sguryev** [MicrosoftDocs/msteams-docs#457]
Sample for "Creating a channel conversation" posts the message to the private 1to1 dialog. Which is obviously come from the class name `ProactiveMsgTo1to1Dialog ` and related sample. How I can post message to the channel instead of the private dialog?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba8d3979-14f5-3105-ad89-ce6f98d11df1
* Version Independent ID: e53a7d1e-0e70-ca30-9809-fda7ebe5f4da
* Content: [Proactive messages - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/bots/bot-conversations/bots-conv-proactive#creating-a-channel-conversation)
* Content Source: [msteams-platform/concepts/bots/bot-conversations/bots-conv-proactive.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/bots/bot-conversations/bots-conv-proactive.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by sguryev** [comment]
I tried both samples: https://github.com/OfficeDev/microsoft-teams-sample-complete-csharp/blob/32c39268d60078ef54f21fb3c6f42d122b97da22/template-bot-master-csharp/src/dialogs/examples/teams/ProactiveMsgTo1to1Dialog.cs

And from: https://github.com/OfficeDev/BotBuilder-MicrosoftTeams-dotnet/blob/master/CSharp/Samples/Microsoft.Bot.Builder.Teams.RemindMeBot/Engine/ProactiveMessageManager.cs

Both sample post messages to 1to1 dialog. Using Teams client

**Comment by Wajeed-msft** [comment]
@sgarg4681 - Could you please try following code and let us know if it's working for you?

```
            var mainMessage = Activity.CreateMessageActivity();
            mainMessage.Text = "This is first message.";

            var channelId = "[YourChannelId]";
            var serviceUrl = "[ServiceURL]";

            var connectorClient = new ConnectorClient(new Uri(serviceUrl));
            var parameters = new ConversationParameters
            {
                ChannelData = new TeamsChannelData
                {
                    Channel = new ChannelInfo(channelId),
                },
                IsGroup = true,
                Activity = (Activity)mainMessage
            };

            var conversationResource = await connectorClient.Conversations.CreateConversationAsync(parameters);

```

**Comment by sguryev** [comment]
@Wajeed-msft thank you. I have found this answer on the SO as well. And even have made it work for Bot Framework v4. Do you know what does `IsGroup = true,` mean? It works without it.

Anyway I think that documentation should be fixed because provided sample is not for the Channel but for the Private Dialog

**Comment by Wajeed-msft** [comment]
@sguryev - Tried setting IsGroup value for **channel conversation** and there was no effect, both true & false worked. However, setting it to true for **1:1 conversation** resulted in BadRequest exception.

**Comment by pkaushik23** [comment]
> 
> 
> @Wajeed-msft thank you. I have found this answer on the SO as well. And even have made it work for Bot Framework v4. Do you know what does `IsGroup = true,` mean? It works without it.

@sgurvey i read your comment that your bot can create adhoc channel conversation in v4. Please do you mind helping me how to do that ? i tried following code but it always create a personal 1:1 conversation. 


Thanks,
Prerak
```
ClaimsIdentity claimsIdentity = turnContext.TurnState.Get<ClaimsIdentity>("BotIdentity");
Claim botAppIdClaim = claimsIdentity.Claims?.SingleOrDefault(claim => claim.Type == AuthenticationConstants.AudienceClaim)
                        ??
                        claimsIdentity.Claims?.SingleOrDefault(claim => claim.Type == AuthenticationConstants.AppIdClaim);

string appPassword = await this.credentialProvider.GetAppPasswordAsync(botAppIdClaim.Value).ConfigureAwait(false);
var identity =  new MicrosoftAppCredentials(botAppIdClaim.Value, appPassword);
MicrosoftAppCredentials.TrustServiceUrl(teamConversationData.ServiceUrl);
var connectorClient = new ConnectorClient(new Uri(teamConversationData.ServiceUrl),identity);

var mem2 = new List<ChannelAccount> { teamConversationData.TeamRoster.First().Value };
var parameters = new ConversationParameters
{
       //teamConversationData has my state info. like team roster ,tenant id, ms teams channels for my team etc.
	Bot = new ChannelAccount(teamConversationData.BotID, teamConversationData.BotName),
	Members = mem2,//Cant set to more than one account, if i try result in bad request exception
	IsGroup = false, //if this is set to true then always get an error while creating a conversation.
	TopicName = "Anything ",
	ChannelData = JObject.FromObject(
					new TeamsChannelData
					{
						Tenant = new TenantInfo(teamConversationData.Tenant.Id),
						Team = new TeamInfo(teamConversationData.Team.Id),
						Channel = new ChannelInfo(teamConversationData.Channels.Conversations[0].Id),
					},
					JsonSerializer.Create(new JsonSerializerSettings()
					{
						NullValueHandling = NullValueHandling.Ignore,
					})),

};
                    
var conversationResource = await connectorClient.Conversations.CreateConversationAsync(parameters);
var message = Activity.CreateMessageActivity();
message.From = new ChannelAccount(teamConversationData.BotID, teamConversationData.BotName);
message.Conversation = new ConversationAccount(id: conversationResource.Id.ToString());
var mentions = new List<Entity>();
 var activityText = new StringBuilder($"a notification message, for following users : ");
foreach (var member in members)
{
	var mentionsText = $"<at>@{member.Name}</at>";
	mentions.Add(new Entity()
				{
					Type = "mention",
					Properties = JObject.FromObject(
												new { mentioned = new { id = member.Id, name = member.Name }, text = mentionsText }
												, JsonSerializer.Create(new JsonSerializerSettings() { NullValueHandling = NullValueHandling.Ignore, })),
				});
	activityText.Append(mentionsText);

}                   
message.Entities = mentions;
message.Text = activityText.ToString();

await connectorClient.Conversations.SendToConversationAsync((Activity)message);
```

**Comment by XimenaWang** [comment]
@Wajeed-msft , Hi , the variable "context" in the code you provided " var channelData = context.Activity.GetChannelData<TeamsChannelData>();"   
 ,Where can I get this variable("context") ?

**Comment by Wajeed-msft** [comment]
@XimenaWang- **Context** is IDialogContext and you get it while [using Dialogs](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-manage-conversation-flow?view=azure-bot-service-3.0#invoke-the-new-order-dialog).

**ChannelData** is part of activity/message object. 

![image](https://user-images.githubusercontent.com/31851992/57672695-c52ec900-7636-11e9-879a-0a55d8f0e3c4.png)
