### ISSUE TITLE
Issue in fetching members for direct message and channel conversation in case of link unfurling

### ISSUE THREAD

**Issue by Arpita1906** [MicrosoftDocs/msteams-docs#4579]
Hi,
I am trying link unfurling for group chat, direct chat and channel message. I need to fetch the members of the chat for user specific cards

In case of group chat , I get group ID in request and using that group id I can get the group members which is good

"conversation":{
"tenantId":"5f9b6574-1bca-4e42-a104-53cc20f8dda1",
"isGroup":true,
"id":"**19:99f69a4847584dbdb46704297b9fde48@thread.v2**",
"conversationType":"groupChat"
} 

In case of direct chat, I get id like this (a:1JqQXTz2EPa6ivIM3PamBnBhKIrufHUo69Uicgw51zb_qPszw0FG4I_dTmIXFnxZIR0TApw6TenSQwBA9Dtvy90jbqow3gEqET7MNGVWL8WS3zrrGqJRd4CnEN26IzRFH) in request . This id looks like a Bot Conversation ID. How can I get the members using this id ?  I was expecting chat id (19:98c7ad99-9cc6-498d-9f91-3ea3f00d7d1a_f718a5cb-eaa1-4abe-9f19-54cfd21bb53d@unq.gbl.spaces) in request to get the members. Please let me know if there is any way to get the members here ?

"conversation":{
"tenantId":"5f9b6574-1bca-4e42-a104-53cc20f8dda1",
"id":"**a:1JqQXTz2EPa6ivIM3PamBnBhKIrufHUo69Uicgw51zb_qPszw0FG4I_dTmIXFnxZIR0TApw6TenSQwBA9Dtvy90jbqow3gEqET7MNGVWL8WS3zrrGqJRd4CnEN26IzRFH**",
"conversationType":"personal"
},

In case of channel conversation, we need both team id and channel id to retrieve the members. But the teamid in request is not "Team ID" . It's id of the "General" channel . Is this expected ? Can we get Teams GUID in the request ?

"channelData":{
"tenant":{
"id":"5f9b6574-1bca-4e42-a104-53cc20f8dda1"
},
"source":{
"name":"compose"
},
"channel":{
"id":"**19:f7a50d6207114ca0b6d15ed851a778e7@thread.tacv2**"
},
"team":{
"id":"**19:kqG38tPpgUKPP8YFUfLUccDNio-v7QwAcQSzjN-4ypg1@thread.tacv2**"
}
}

Attaching the requests json we are getting in all the 3 cases

[groupChat.txt](https://github.com/MicrosoftDocs/msteams-docs/files/7530728/groupChat.txt)
---
[Direct.txt](https://github.com/MicrosoftDocs/msteams-docs/files/7530731/Direct.txt)

[Channel.txt](https://github.com/MicrosoftDocs/msteams-docs/files/7530732/Channel.txt)
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59bbff2e-4b80-f980-2ade-7c7a7950801e
* Version Independent ID: e837e1fd-ec0c-2d6f-b0db-b76cb2d268a4
* Content: [Link unfurling - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?tabs=dotnet)
* Content Source: [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/messaging-extensions/how-to/link-unfurling.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **anclear**

**Comment by Nivedipa-MSFT** [comment]
@Aroita1906 - We are looking into this issue.We will update you.

**Comment by Arpita1906** [comment]
@Nivedipa-MSFT I am using Graph API to fetch the members beta/chats/<chatId>/members

**Comment by Prasad-MSFT** [comment]
@Arpita1906 
Is your issue resolved or still looking for any help?

**Comment by Arpita1906** [comment]
@Prasad-MSFT I am still looking for an update on this

**Comment by Nivedipa-MSFT** [comment]
@Arpita1906 
1. In case of direct chat it's by design that 1:1 chat id is encrypted.
2. In case of channel conversation it's also expected because team id is the general channel id.
   The overall approach could run into issues though as the bot may not be part of the roster.

**Comment by v-chetsh** [comment]
@Arpita1906 - Could you please confirm if your issue has resolved or still looking for any help?
