### ISSUE TITLE
Can't login into Teams get error 500

### ISSUE THREAD

**Issue by biozal** [MicrosoftDocs/msteams-docs#458]
Can't use Microsoft Teams.  When launching via the Mac or web browser I get an error 500.  The file that I'm error out on is extra.js.

![screen shot 2019-02-18 at 9 11 59 am](https://user-images.githubusercontent.com/176927/52956495-50acfc80-335d-11e9-97b1-282f52ca7ae9.png)

![screen shot 2019-02-18 at 9 14 00 am](https://user-images.githubusercontent.com/176927/52956588-9073e400-335d-11e9-9c66-3a9c9720f6d2.png)

**Comment by Wajeed-msft** [comment]
Are you still facing issue while logging in?
