### ISSUE TITLE
exactly three buttons in every card in the world?

### ISSUE THREAD

**Issue by mdagit** [MicrosoftDocs/msteams-docs#4580]
"The actionable messages include three visible buttons on the card."

Seriously, "three"? No more and no less?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28316a67-22fa-8a05-1ae0-fbe1c5720ef9
* Version Independent ID: 8a250e46-2a30-af86-839d-9f83a8b48041
* Content: [Create and send messages - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-using?tabs=cURL)
* Content Source: [msteams-platform/webhooks-and-connectors/how-to/connectors-using.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/webhooks-and-connectors/how-to/connectors-using.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Nivedipa-MSFT** [comment]
@mdagit - We can add more than 3 actionable buttons on card.

![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/92150070/141743292-1d4497e6-18b6-4f67-9d6e-e634fef8ba55.png)

**Comment by Nivedipa-MSFT** [comment]
@mdagit - We can add more than 3 actionable buttons on card.Is your issue resolved with our solution?

**Comment by mdagit** [comment]
my feedback was on the documentation -- i actually know how the product works.

-mda

**Comment by v-chetsh** [comment]
It's related to doc enhancement/bug so redirecting it.
