### ISSUE TITLE
can i have some dressing to go with this word salad?

### ISSUE THREAD

**Issue by mdagit** [MicrosoftDocs/msteams-docs#4581]
"an open cross card platform framework."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90ff2a84-a8bc-9259-d37d-622b102df75b
* Version Independent ID: e3b53e27-2946-189c-623b-9df704ea8f12
* Content: [Create an Incoming Webhook - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-incoming-webhook)
* Content Source: [msteams-platform/webhooks-and-connectors/how-to/add-incoming-webhook.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/webhooks-and-connectors/how-to/add-incoming-webhook.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Prasad-MSFT** [comment]
Open cross card platform framework means  it can be used in all platforms such as Windows, Android, iOS etc

**Comment by mdagit** [comment]
i kind of know what the writer was trying to say....
this was feedback on the documentation writing.

-mda

**Comment by Prasad-MSFT** [comment]
Ok Thanks! Redirecting to documentation team to update.
