### ISSUE TITLE
Date is rendering a day before in teams adaptive cards.

### ISSUE THREAD

**Issue by astuj** [MicrosoftDocs/msteams-docs#4585]
Hi, I am passing a value to the date time control of the adaptive card but the date rendered on the card is one day less than the actual passed date. 

Here is the JSON payload:- 

{
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "type": "AdaptiveCard",
  "version": "1.3",
  "body": [
    {
      "type": "ColumnSet",
      "columns": [
        {
          "type": "Column",
          "width": 2,
          "items": [
            {
              "type": "TextBlock",
              "text": "Propose new time for request #10482",
              "weight": "Bolder",
              "size": "ExtraLarge",
              "wrap": true
            },
            {
              "type": "TextBlock",
              "text": "NOTE: Request will be updated and approved to New Time.\n",
              "isSubtle": true,
              "wrap": true
            },
            {
              "type": "Container",
              "items": [
                {
                  "type": "TextBlock",
                  "text": "New Time",
                  "wrap": true,
                  "weight": "Bolder"
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "type": "Input.Date",
      "value": "15-Nov-2021",
      "id": "NewDate",
      "isRequired": true,
      "errorMessage": "Date should not be empty."
    },
    {
      "type": "Input.Time",
      "value": "21:37:00",
      "id": "NewTime",
      "isRequired": true,
      "errorMessage": "New Time should not be empty."
    },
    {
      "type": "TextBlock",
      "text": "Comment",
      "wrap": true,
      "weight": "Bolder"
    },
    {
      "type": "Input.Text",
      "placeholder": "Provide your comments",
      "isMultiline": true,
      "id": "Comment",
      "isRequired": true,
      "errorMessage": "Comments should not be empty"
    }
  ],
  "actions": [
    {
      "type": "Action.Submit",
      "title": "Submit",
      "style": "default",
      "data": {
        "msteams": {
          "type": "messageBack",
          "displayText": "Submit Propose time for request #10482",
          "text": "post-visit-request-propose-time",
          "value": "{\"requestNo\": \"10482\",\"NewTime\": \"21:37:00\",\"NewDate\": \"2021-11-15T00:00:00Z\",\"Comment\": \"${Comment}\",\"DateTime\": \"2021-11-15T21:37:00Z\"}"
        }
      }
    }
  ]
}

<img width="485" alt="Screenshot 2021-11-15 at 3 59 02 PM" src="https://user-images.githubusercontent.com/20801184/141765993-1a6adf5a-f279-4cb0-906e-f0c2eb8edda8.png">

Here, the date passed in the payload is 15-Nov-2021 but the rendered date is 14-Nov-2021 also the value in the time field is missing but passed in the payload.

**Comment by Meghana-MSFT** [comment]
@astuj - This bug has been fixed. The fixed will be rolled out and should be available for everyone soon.

Thanks

**Comment by astuj** [comment]
@Meghana-MSFT  Hi, i have noticed other issues are fixed but this is still persisting. Could you check this again.

**Comment by Meghana-MSFT** [comment]
@astuj - I have verified it before posting my reply here. Attaching the screenshots below :
 
Web : 
![image](https://user-images.githubusercontent.com/81138249/141775092-057a1d42-94b7-4c2d-86bb-914aa9529e4b.png)
Desktop : 
![image](https://user-images.githubusercontent.com/81138249/141775188-d36a96b9-32bc-4a58-9d58-f877931fde0a.png)

**Comment by WhiteCyClop** [comment]
@astuj, try to use "yyyy-MM-dd" format for date value, for me it fixes the same problem

**Comment by astuj** [comment]
Thanks @WhiteCyClop, its working using this format

**Comment by Prasad-MSFT** [comment]
@astuj , Thanks for confirming. We are closing this issue for now. Please feel free to reopen if needed.
