### ISSUE TITLE
Issue with text color of adaptive cards changing by teams theme

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#4590]
Copied bug from: https://github.com/microsoft/AdaptiveCards/issues/3244 

**Details from original post:**
# Platform

What platform is your issue or question related to? (Delete other platforms).
* JavaScript

# Author or host

Are you an author (like sending something to Outlook), or a host that is rendering your own cards?
Author
If you're an author, who are you sending cards to?
Either DMs or group chats on MS teams
# Version of SDK
1.0
What version are you using? Ex: NuGet 1.0.2, or latest master, etc...
Issue happens both the current version of the botbuilder framework with ```CardFactory.adaptiveCard()``` and with the direct importing of the adaptivecards package and declaring the adaptive card as:
```
var companyCard = new AdaptiveCards.AdaptiveCard();
companyCard.parse(card);
```
# Issue
When I set the text of an adaptive card to light (white) it will appear white on the default teams theme and the high contrast but will invert to black on the teams dark theme and therefore not be readable.
The screen shots I posted are of the same card with and without a background image that I'm using as a background color for the cards (#001F3D)
<img width="492" alt="Screen Shot 2019-07-18 at 10 54 38 AM" src="https://user-images.githubusercontent.com/45300745/61473209-950fe900-a94b-11e9-9ad4-dc91ff3d29ac.png">
<img width="488" alt="Screen Shot 2019-07-18 at 10 55 46 AM" src="https://user-images.githubusercontent.com/45300745/61473211-950fe900-a94b-11e9-8936-fad317a9c482.png">
<img width="489" alt="Screen Shot 2019-07-18 at 10 56 00 AM" src="https://user-images.githubusercontent.com/45300745/61473212-950fe900-a94b-11e9-962f-d4aef38f6cd8.png">
<img width="484" alt="Screen Shot 2019-07-18 at 10 56 05 AM" src="https://user-images.githubusercontent.com/45300745/61473213-950fe900-a94b-11e9-9aa3-b1f6563bfac3.png">
<img width="497" alt="Screen Shot 2019-07-18 at 10 56 29 AM" src="https://user-images.githubusercontent.com/45300745/61473214-950fe900-a94b-11e9-9fe0-b63ce3eec9b4.png">
<img width="490" alt="Screen Shot 2019-07-18 at 10 56 34 AM" src="https://user-images.githubusercontent.com/45300745/61473215-950fe900-a94b-11e9-835c-0b8feb12c273.png">

As you can see the default and high contrast themes work as intended, but the dark theme inverts the white to black which is detrimental in this instance. 

 . The JSON is:
```
let card = CardFactory.adaptiveCard(
            {
                "type": "AdaptiveCard",
                "body": [
                    {
                        "type": "Container",
                        "items": [
                            {
                                "type": "TextBlock",
                                "size": "Medium",
                                "weight": "Bolder",
                                "text": "Feature not active",
                                "color": "Light"
                            }
                        ]
                    },
                    {
                        "type": "Container",
                        "items": [
                            {
                                "type": "TextBlock",
                                "text": "This version does not support imperatives.",
                                "wrap": true,
                                "color": "Light"
                            }
                        ]
                    },
                    {
                        "type": "Image",
                        "url": "https://raw.githubusercontent.com/link-works-but-has-repo-names-I-cant-share",
                        "size": "Small",
                        "horizontalAlignment": "Right",
                        "spacing": "None"
                    }
                ],
                "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
                "version": "1.0",
                "backgroundImage": "https://raw.githubusercontent.com/link-works-but-has-repo-names-I-cant-share"
            }
        );
```
---
#### Document Details

⚠ *Do not edit this section.It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Cards reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **surbhigupta12**

**Comment by Nivedipa-MSFT** [comment]
@bgert - Could you please update the latest version of Teams and check again.I have tried it in dark mode but the text color is black.

![image](https://user-images.githubusercontent.com/92150070/141941041-3415e5d4-6dce-4942-bcca-3368469cdcc9.png)

**Comment by Nivedipa-MSFT** [comment]
@bgert - Is your issue resolved by updating Teams version?

**Comment by bgert** [comment]
I no longer have access to that code base so I can't check.

**Comment by v-chetsh** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.
