### ISSUE TITLE
[.NET C#][Input.ChoiceSet] [adaptive card dropdown title with double quotes rendering issue]

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#4591]
Copied bug from: https://github.com/microsoft/AdaptiveCards/issues/3573 

**Details from original post:**
# Platform

What platform is your issue or question related to? (Delete other platforms).

* .NET C#

# Dropdown rendering title value containing double quotes is getting replaced with "&quot"

Are you an author (like sending something to Outlook), or a host that is rendering your own cards? If host, please specify the corresponding host (app) name. : **Microsoft Teams**

# 1.2.0

# Details

We are having dropdown in adaptive card which is having double quotes in title. double quotes on teams channel are getting replaced with "&quot"

Please find example JSON below:
[DropdownExampleJson.txt](https://github.com/microsoft/AdaptiveCards/files/3814266/DropdownExampleJson.txt)

Please suggest a solution.
![MicrosoftTeams-image](https://user-images.githubusercontent.com/32361772/68296260-3321ed80-00ba-11ea-8415-472aa0dc5c25.png)
---
#### Document Details

⚠ *Do not edit this section.It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Cards reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **surbhigupta12**

**Comment by v-chetsh** [comment]
We will check on it and let you know.

**Comment by HunaidHanfee-MSFT** [comment]
I am unable to repro this issue, 
![image](https://user-images.githubusercontent.com/64194049/142205370-53058654-f077-44aa-b66b-31a1b54d696f.png)
It is showing fine to me.

**Comment by HunaidHanfee-MSFT** [comment]
Hello, Could you please share more details on this?

**Comment by HunaidHanfee-MSFT** [comment]
We are unable to repro this issue, we have tested it on web as well as desktop client version - 1.4.00.31569 (64-bit).

Please let us know if you are still facing this issue. We are closing it as of now.
