### ISSUE TITLE
Sample configuration page code would help to understand configuration part

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#460]
Could you please include code snippet for [Connector configuration page](https://github.com/OfficeDev/microsoft-teams-sample-connector-csharp/blob/master/TeamsToDoAppConnector/Views/Connector/Setup.cshtml)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c21a27c1-d01a-6cc7-c991-73af6492aad8
* Version Independent ID: b15d2142-df29-250e-9a0a-b734dcb93162
* Content: [Office 365 Connectors - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/connectors/connectors-creating#integrating-the-configuration-experience)
* Content Source: [msteams-platform/concepts/connectors/connectors-creating.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/connectors/connectors-creating.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Nikitha-MSFT** [comment]
Document is updated: [Integrating the configuration experience](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-creating#integrating-the-configuration-experience).
