### ISSUE TITLE
Deploy bot to Azure button

### ISSUE THREAD

**Issue by JuliaRHT** [MicrosoftDocs/msteams-docs#461]
As the functionality to deploy the bot to Azure is not loading the expected form, would it be possible to provide manual instructions detailing how to get to the point of filling in the form to deploy the bot to Azure?

"Now that you've generated your Application Id and Password, it's time to deploy your bot to Azure. Click on the Deploy to Azure button and fill out the form with the necessary information (the Bot Application Id, Bot Application Password and the Moodle Secret are on the Team Settings page, and the Azure information is on the Setup page). Once you've got the form filled out, click the check box to agree to the terms and conditions then click the Purchase button (all Azure resources are deployed to the free tier)."

Thanks
Julia

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 685f497e-473f-7767-3f4e-5a0d1271a2ec
* Version Independent ID: 79dc20db-c743-8150-a660-abd9ffb03b4d
* Content: [Installing the Moodle integration with Microsoft Teams - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/moodleinstructions#feedback)
* Content Source: [msteams-platform/MoodleInstructions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/MoodleInstructions.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by clearab** [comment]
Hi - My apologies for the late reply. I've been unable to reproduce the behavior you seem to be experiencing; can you please provide some more details? The button appears to be working fine in our test environments.

**Comment by JuliaRHT** [comment]
Hi Andrew

Thanks for getting back to me. It seems the issue may be the user account I was using not having access to our institution’s Azure subscription. I will try with the actual admin account, once I can arrange this.

Kind regards
Julia


[https://secure.bhasvic.ac.uk/images/logo.png]  JULIA HOLGATE TURNER
VLE Coordinator
01273552200 Ext: 4819
Email: j.holgateturner@bhasvic.ac.uk<mailto:j.holgateturner@bhasvic.ac.uk>

[https://secure.bhasvic.ac.uk/images/facebook.png]<https://www.facebook.com/bhasvic.ac.uk>      [https://secure.bhasvic.ac.uk/images/twitter.png] <https://twitter.com/bhasvic>         BHASVIC (Brighton Hove & Sussex Sixth Form College) 205 Dyke Road, Hove, BN3 6EG |      www.bhasvic.ac.uk<https://www.bhasvic.ac.uk/home>

[https://secure.bhasvic.ac.uk/images/eco.png]   Before printing, think about the environment


The content of this message is confidential. It is forbidden to copy, forward, or in any way reveal the contents of this message to anyone. If you have received it by mistake, please inform us by an email reply and then delete the message. The integrity and security of this email cannot be guaranteed over the Internet. Therefore, the sender will not be held liable for any damage caused by the message. Any views or opinions expressed are solely those of the author and do not necessarily represent those of BHASVIC.
