### ISSUE TITLE
toQueryString is not defined

### ISSUE THREAD

**Issue by ejschoen** [MicrosoftDocs/msteams-docs#463]
Implementations are available, e.g., prototype.js, but it might be nice for this sample to know where you're getting it from.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d939a56-d1be-f2a2-3454-0f0c5144bc27
* Version Independent ID: ec4d5574-ddeb-9408-ad82-d86507a5111b
* Content: [Authentication for tabs using Azure Active Directory - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/authentication/auth-tab-AAD)
* Content Source: [msteams-platform/concepts/authentication/auth-tab-AAD.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/authentication/auth-tab-AAD.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Wajeed-msft** [comment]
@ejschoen - You can find complete code in [authentication sample](https://github.com/OfficeDev/microsoft-teams-sample-auth-node/blob/4b7934576ab4c21b119b43d30edbdc6718f83abf/src/views/tab/simple/simple-start-v2.hbs#L56).
Here is the code snippet for reference:
 ```
            // Build query string from map of query parameter
            function toQueryString(queryParams) {
                let encodedQueryParams = [];
                for (let key in queryParams) {
                    encodedQueryParams.push(key + "=" + encodeURIComponent(queryParams[key]));
                }
                return encodedQueryParams.join("&");
            }
```
