### ISSUE TITLE
Deeplink failed to pass the Query Params

### ISSUE THREAD

**Issue by Chang025** [MicrosoftDocs/msteams-docs#4639]
We are invoking the task module **via Adaptive Card's task/fetch as well as via deep_link**.
In the case of task/fetch, things are working as expected, but for the deep-link, we are **not able to get the query params**:

**Url which we are passing:**
`https://c5d3-2405-201-5c0a-a025-3507-9541-abcd-1234.ngrok.io//card-links/1431/web_view.html?sample_data=123&agent_id=8`

**Here is the part of JSON which we are building for deep link:**
```
...
 { 
 "type": "Action.OpenUrl",
 "url":  "https://teams.microsoft.com/l/task/4c4bc977-07b2-4f26-bf74-de6dcfece674?url=https://c5d3-2405-201-5c0a-a025-3507-9541-abcd-1234.ngrok.io/card-links/1431/web_view.html?sample_data=123&agent_id=8&height=500&width=500&title=wer-view-html&agent_id=8" 
 }
 ...
```
**On clicking that button, the task module opens up, but we are not able to see any content, and this is what we got on the server:**
```
Started GET "//card-links/1429/web_view.html?sample_data" for 2405:201:5c0a:a025:91f6:a0ae:a25b:c41a at 2021-11-18 14:23:02 +0530
```

I had tried to bind the URL part with the single quotes as well, but that also didn't worked.
sample JSON:

```
...
 { 
 "type": "Action.OpenUrl",
 "url":  "https://teams.microsoft.com/l/task/4c4bc977-07b2-4f26-bf74-de6dcfece674?url=`https://c5d3-2405-201-5c0a-a025-3507-9541-abcd-1234.ngrok.io/card-links/1431/web_view.html?sample_data=123&agent_id=8`&height=500&width=500&title=wer-view-html&agent_id=8" 
 }
 ...
```

You can see that after sample_data rest of the things got vanished. **Just wanted to know Is there any way we can pass query params with a deep link?**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55c5e4a1-6116-ec92-36e9-b94097bd83c7
* Version Independent ID: fd843eef-73e2-7a7e-9ac4-5c20fcf1fa2f
* Content: [Invoke and dismiss task modules - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/task-modules/invoking-task-modules)
* Content Source: [msteams-platform/task-modules-and-cards/task-modules/invoking-task-modules.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/task-modules/invoking-task-modules.md)
* Product: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **lajanuar**

**Comment by sayali-MSFT** [comment]
@Chang025 - We are looking into this I will get back to you soon.

**Comment by sayali-MSFT** [comment]
@Chang025 - Please have a look at this doc - https://adaptivecards.io/explorer/Action.OpenUrl.html .
https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/task-modules/invoking-task-modules#task-module-deep-link-syntax

Let us know if you have any query.

**Comment by Chang025** [comment]
hey @sayali-MSFT - Thank you for the quick response.
I have gone through the docs, the first doc is more of a general Action.OpenUrl thing and in the second doc, there is no place where it is written that the `TaskInfo.url` property does not support query params for deep_link.

**reference from docs:** `https://teams.microsoft.com/l/task/APP_ID?url=<TaskInfo.url>&height=<TaskInfo.height>&width=<TaskInfo.width>&title=<TaskInfo.title>&completionBotId=BOT_APP_ID` 

I need to send TaskInfo.url along with the query parameters, something like:
`TaskInfo.url:  https://adaptivecards.io?my_custom_param1=abcd&my_custom_param2=123`

Can you please confirm that deep_link's `url` attribute does not support query params?
or just bring my attention to how we can pass the query params which will require later on our server.

**Comment by sayali-MSFT** [comment]
@Chang025 - Deeplink  url attribute is support query params. I tryouts with above syntax. it's working on our end.
Sample Link:-
https://teams.microsoft.com/l/task/bc6fb7f5-5824-44c6-9a08-38c3a211XXXX?url=https://adaptivecards.io?my_custom_param1=abcd&my_custom_param2=123&height=500&width=500&title=wer-view-html&completionBotId=bc6fb7f5-5824-44c6-9a08-38c3a211XXXX

**Comment by Chang025** [comment]
@sayali-MSFT - Thanks for the sample URL, I'll check that again at our side and if needed then I'll re-open this issue again.
