### ISSUE TITLE
[Javascript][Rendering/Templating] Invalid Action.OpenUrl url parameter can break card render on desktop Teams

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#4655]
Copied bug from: https://github.com/microsoft/AdaptiveCards/issues/3538 

**Details from original post:**
# Platform

* JavaScript

# Author or host

Teams

# Version of SDK

1.2.3

# Details

Previously when an invalid URL was passed to the `Action.OpenUrl` action (e.g. because invalid input was passed by a user from previous interaction with the bot) the corresponding action button would render alongside the card. In this case, this button would not do anything upon clicking it.

Since not too long ago some strings completely break the rendering for the entire card. I consistently get this bug when the `url` parameter contains a string that could be interpreted as an integer, like `1`. 

This bug happens on the Microsoft Teams desktop client only (the mobile client still has the correct 'fallback'). The following Angular console error can be spotted:

![image](https://user-images.githubusercontent.com/45333650/67595830-ca587e00-f767-11e9-8e05-4dc52657a2f3.png)

The following snippet can be used to recreate the problem:

```JSON
{
        "type": "Action.OpenUrl",
        "title": "Link",
        "url": "1",
 },
```

---
#### Document Details

⚠ *Do not edit this section.It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Cards reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **surbhigupta12**

**Comment by sayali-MSFT** [comment]
@Wajeed-msft - We are looking into this I will get back to you soon.

**Comment by sayali-MSFT** [comment]
@Zenulous - We are able to repro that issue , We have raised bug for the same and concerned team is looking into it. We will inform you once we get any update.

**Comment by sayali-MSFT** [comment]
@Zenulous - Bug is resolved and publicly rolled out. Could you please check it once and let us know?
 Microsoft Teams Version 1.5.00.13614 (64-bit)-E.
