### ISSUE TITLE
[Doc-enhancement] OnTeamsMessagingExtensionSelectItemAsync details are not explained in documentation

### ISSUE THREAD

**Issue by SubbaReddi** [MicrosoftDocs/msteams-docs#4656]
Documentation don't have details about the purpose and use of OnTeamsMessagingExtensionSelectItemAsync event. So, Can you add details in documentation.

And OnTeamsMessagingExtensionSelectItemAsync does not trigger in mobile. This event is not implemented for mobile. So, Please add note for the same.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4f3b627-c87b-6a19-9c26-7170a99f38ee
* Version Independent ID: a9546115-7c5d-39c9-ca8a-3cf3e02ff621
* Content: [Respond to search command - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/search-commands/respond-to-search?tabs=dotnet)
* Content Source: [msteams-platform/messaging-extensions/how-to/search-commands/respond-to-search.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/messaging-extensions/how-to/search-commands/respond-to-search.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **anclear**

**Comment by Wajeed-msft** [comment]
@HunaidHanfee-MSFT - could you please help to provide code snippets for enabling Tap action and OnTeamsMessagingExtensionSelectItemAsync  handling part?
