### ISSUE TITLE
why blazor page is removed?

### ISSUE THREAD

**Issue by binfouzan** [MicrosoftDocs/msteams-docs#4658]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dac10c25-1625-4f0d-b113-a1fdd7a7a900
* Version Independent ID: dac10c25-1625-4f0d-b113-a1fdd7a7a900
* Content: [Get started - Overview - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/get-started/get-started-overview)
* Content Source: [msteams-platform/get-started/get-started-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/get-started/get-started-overview.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by HunaidHanfee-MSFT** [comment]
I didn't get it, Could you please share more details on the question. What is missing or needs to be corrected?

Thanks

**Comment by binfouzan** [comment]
sure, on this page 
https://docs.microsoft.com/en-us/microsoftteams/platform/get-started/get-started-overview
there was a section under **Get started**, named **build your first app with blazor** 
it is not show now

**Comment by HunaidHanfee-MSFT** [comment]
Thanks for sharing. I will confirm internally and let you know.

**Comment by HunaidHanfee-MSFT** [comment]
We have assigned it to doc team. 

Thanks for posting.

**Comment by surbhigupta12** [comment]
Hi @binfouzan,

There was an update to the toolkit due to which there were issues in the guide. For now we've removed the content. As soon as the toolkit is updated, we'd update the docs and publish them.

Thank you for your patience and understanding.

**Comment by binfouzan** [comment]
Any update?

**Comment by v-chetsh** [comment]
@v-shalinirobinson - Could you please share the updates on this issue.

**Comment by v-chetsh** [comment]
Hello @surbhigupta12 - Could you please share the updates on this issue.

**Comment by binfouzan** [comment]
hi 
I did not get any replay on my question
I need to know is Blazor still supported or not
I need to know, should I invest in Blazer or not. should I drop it and train my team on javascript and React for all of our applications

**Comment by surbhigupta12** [comment]
Hi @binfouzan,

Blazor is supported. Some updates are happening and hence the delay.
The documents will be live as soon as the updates are done.

Appreciate your patience.

**Comment by v-chetsh** [comment]
Hello @surbhigupta12 - Could you please share the updates on this issue?

**Comment by v-chetsh** [comment]
Hello @surbhigupta12 - Could you please share the updates on this issue?

**Comment by v-shalinirobinson** [comment]
The Blazor page is being updated for updated Teams Toolkit version. It will be back online as soon as the updates are completed.

**Comment by v-chetsh** [comment]
@v-shalinirobinson -  Please let us know once the contents are online, so that we can close this issue?

**Comment by v-chetsh** [comment]
@v-shalinirobinson -  Please let us know once the contents are online, so that we can close this issue?

**Comment by v-chetsh** [comment]
@v-shalinirobinson -  Please let us know once the contents are online, so that we can close this issue?

**Comment by v-shalinirobinson** [comment]
The Blazor page is being updated for updated Teams Toolkit version and Visual Studio 2022. It will be back online as soon as the updates are completed.

**Comment by StephenOTT** [comment]
Hi
Is there movement on this? It has been like this since November. 

Thanks

**Comment by v-chetsh** [comment]
@surbhigupta12, @v-shalinirobinson - Could you please let us know whether the contents are updated now or not?

**Comment by v-shalinirobinson** [comment]
The Blazor page is being updated for updated Teams Toolkit version and Visual Studio 2022. It will be back online as soon as the updates are completed.

**Comment by v-abirade** [comment]
Hello, 

The issue has been addressed in https://github.com/MicrosoftDocs/msteams-docs/pull/5415, hence closing the issue.
