### ISSUE TITLE
Horizontal scroll prohibited as per validation guidelines

### ISSUE THREAD

**Issue by serverless-me** [MicrosoftDocs/msteams-docs#4660]
The page contains a screenshot of the tab on the mobile client with horizontal scrollbar.

From [validation guidelines](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/teams-store-validation-guidelines#tabs) you can see: "Tab must not have a horizontal scroll."

Ask: Please remove the design of horizontal scrollbar from the page, because this creates false expectations for partners who are building apps.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3dd35a9c-c868-a7b9-825a-4be9419539d7
* Version Independent ID: 814c8be1-eae8-7316-8553-283ef07ffc09
* Content: [Design tabs for desktop, web, and mobile - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/design/tabs)
* Content Source: [msteams-platform/tabs/design/tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tabs/design/tabs.md)
* Product: **msteams**
* GitHub Login: @heath-hamilton
* Microsoft Alias: **lajanuar**

**Comment by sayali-MSFT** [comment]
@serverless-me - As per validation documentation, it is mention that "Tab must not have a horizontal scroll. Whiteboarding apps and other apps that require a larger canvas to allow users to collaborate without a perceived broken app experience, **can use horizontal scroll depending on their business need**. [Suggested Fix]" .

As per business requirement, If we need a large canvas to use in any app we can use horizontal scrollbar. 
Could you please confirm if we still need to change the documentation?

**Comment by v-chetsh** [comment]
@serverless-me - Could you please confirm on the above shared response.

**Comment by v-chetsh** [comment]
Could you please confirm if your issue has resolved with above suggestion or still looking for any help?
