### ISSUE TITLE
Cannot set `packageName` property in the Developer Portal

### ISSUE THREAD

**Issue by jouhami** [MicrosoftDocs/msteams-docs#4661]
`packageName` has a default value of `com.package.name` in the manifest.json. I don't see where can I change it in the Developer Portal. (I was able to set it in the App Studio)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7da63b6f-15d7-a6dd-82fc-d183afaeb816
* Version Independent ID: 82d1ca83-28dd-220e-ab0c-a4833f8f8143
* Content: [Manage your apps with the Developer Portal - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/teams-developer-portal#configure-your-apps-capabilities-and-other-important-metadata)
* Content Source: [msteams-platform/concepts/build-and-test/teams-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/build-and-test/teams-developer-portal.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **surbhigupta**

**Comment by sayali-MSFT** [comment]
@jouhami - We are looking into this I will get back to you soon.

**Comment by sayali-MSFT** [comment]
@jouhami - You can edit the manifest file using app studio. In developer portal there is no option for adding property package name.

**Comment by v-chetsh** [comment]
@jouhami  - Could you please confirm if your issue has resolved with above suggestion or still looking for any help?

**Comment by jouhami** [comment]
Yes I can change it in App studio or by editing the manifest.json. I was just wondering if it disappears in the Dev Portal does it mean it is not mandatory anymore ?

**Comment by sayali-MSFT** [comment]
@jouhami - as per documentation, packageName property is Optional .
A unique identifier for the app in reverse domain notation.

Reference Doc:-https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema#packagename

**Comment by jouhami** [comment]
OK.

( FWIW it is required in App Studio)

![image](https://user-images.githubusercontent.com/12663150/143266843-506a401e-dc90-464c-a237-4e5098e02a0f.png)

**Comment by sayali-MSFT** [comment]
@jouhami - Could you please confirm if your issue has resolved or still looking for any help?

**Comment by jouhami** [comment]
The issue is resolved
