### ISSUE TITLE
Trigger phone calls from adaptive cards

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#4662]
Copied bug from: https://github.com/microsoft/AdaptiveCards/issues/6761 

**Details from original post:**
Hi! How can we trigger phone calls from adaptive cards?

<img width="546" alt="Screen Shot 2021-11-19 at 3 34 58 PM" src="https://user-images.githubusercontent.com/12118798/142704259-9187dc8a-552b-413e-9317-b631ae607a73.png">

---
#### Document Details

⚠ *Do not edit this section.It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Cards reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **surbhigupta12**

**Comment by HunaidHanfee-MSFT** [comment]
@wujasmine - 
You can use Action.OpenUrl and give a deeplink to call a person by follow this article - 
https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links#deep-linking-to-an-audio-or-audio-video-call

Let us know if you are facing some issue?

**Comment by v-chetsh** [comment]
@wujasmine  - Could you please confirm if your issue has resolved with above suggestion or still looking for any help?
