### ISSUE TITLE
[iOS][Accessibility]Adaptive Card focus on the first element which is image

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#4663]
Copied bug from: https://github.com/microsoft/AdaptiveCards/issues/5942 

**Details from original post:**
# Target Platform
- iOS

# Target Application

Teams

# Problem Description

Accessibility default focus on the first card will finally focus on the first image. Would like to focus on the whole card instead.

# Expected

Focus on the whole card.

# Screenshot
![IMG_0072_1](https://user-images.githubusercontent.com/85100080/120160796-3abf5f00-c229-11eb-8a99-e03a5a538405.png)

# Sample Code

UIAccessibility.post(notification: .layoutChanged, argument: firstcard)

# Version of SDK

2.4.6
---
#### Document Details

⚠ *Do not edit this section.It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Cards reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **surbhigupta12**

**Comment by Nivedipa-MSFT** [comment]
@kaichun-wu - Could you please share your sample code which you are referring?

**Comment by v-chetsh** [comment]
@kaichun-wu - Could you please share the repro steps and your Adaptive card Json or code so that we can check it from our end.

**Comment by kaichun-wu** [comment]
@Nivedipa-MSFT @v-chetsh This is more like a request other than bug. When user first focus on the card, can we focus on the whole card and announce the details of the card other than focus on the first element which in this case is the image? 
Json attached below.

`{
            "type": "AdaptiveCard",
            "version": "1.0",
            "body": [
              {
                "type": "Container",
                "items": [
                  {
                    "type": "ColumnSet",
                    "columns": [
                      {
                        "type": "Column",
                        "width": "auto",
                        "items": [
                          {
                            "type": "Image",
                            "size": "small",
                            "style": "person",
                            "url": "xxx"
                          }
                        ],
                        "verticalContentAlignment": "center"
                      },
                      {
                        "type": "Column",
                        "width": "stretch",
                        "items": [
                          {
                            "type": "TextBlock",
                            "size": "medium",
                            "text": "name"
                          },
                          {
                            "type": "TextBlock",
                            "isSubtle": true,
                            "text": "title",
                            "spacing": "none"
                          }
                        ],
                        "verticalContentAlignment": "center",
                        "spacing": "small"
                      }
                    ]
                  }
                ],
                "style": "default",
                "selectAction": {
                  "type": "Action.Submit",
                  "data": {
                    "ux:position_ref": "1"
                  },
                  "title": ""
                },
                "spacing": "extraLarge",
                "separator": true
              },
              {
                "type": "Container",
                "items": [
                  {
                    "type": "ColumnSet",
                    "columns": [
                      {
                        "type": "Column",
                        "width": "auto",
                        "items": [
                          {
                            "type": "Image",
                            "size": "small",
                            "style": "person",
                            "url": "xxx"
                          }
                        ],
                        "verticalContentAlignment": "center"
                      },
                      {
                        "type": "Column",
                        "width": "stretch",
                        "items": [
                          {
                            "type": "TextBlock",
                            "size": "medium",
                            "text": "name"
                          },
                          {
                            "type": "TextBlock",
                            "isSubtle": true,
                            "text": "title",
                            "spacing": "none"
                          }
                        ],
                        "verticalContentAlignment": "center",
                        "spacing": "small"
                      }
                    ]
                  }
                ],
                "style": "default",
                "selectAction": {
                  "type": "Action.Submit",
                  "data": {
                    "ux:position_ref": "2"
                  },
                  "title": ""
                },
                "spacing": "extraLarge",
                "separator": true
              },
              {
                "type": "Container",
                "items": [
                  {
                    "type": "ColumnSet",
                    "columns": [
                      {
                        "type": "Column",
                        "width": "auto",
                        "items": [
                          {
                            "type": "Image",
                            "size": "small",
                            "style": "person",
                            "url": "xxx"
                          }
                        ],
                        "verticalContentAlignment": "center"
                      },
                      {
                        "type": "Column",
                        "width": "stretch",
                        "items": [
                          {
                            "type": "TextBlock",
                            "size": "medium",
                            "text": "name"
                          },
                          {
                            "type": "TextBlock",
                            "isSubtle": true,
                            "text": "title",
                            "spacing": "none"
                          }
                        ],
                        "verticalContentAlignment": "center",
                        "spacing": "small"
                      }
                    ]
                  }
                ],
                "style": "default",
                "selectAction": {
                  "type": "Action.Submit",
                  "data": {
                    "ux:position_ref": "3"
                  },
                  "title": ""
                },
                "spacing": "extraLarge",
                "separator": true
              },
              {
                "type": "Container",
                "items": [
                  {
                    "type": "ColumnSet",
                    "columns": [
                      {
                        "type": "Column",
                        "width": "auto",
                        "items": [
                          {
                            "type": "Image",
                            "size": "small",
                            "style": "person",
                            "url": "xxx"
                          }
                        ],
                        "verticalContentAlignment": "center"
                      },
                      {
                        "type": "Column",
                        "width": "stretch",
                        "items": [
                          {
                            "type": "TextBlock",
                            "size": "medium",
                            "text": "name"
                          },
                          {
                            "type": "TextBlock",
                            "isSubtle": true,
                            "text": "title",
                            "spacing": "none"
                          }
                        ],
                        "verticalContentAlignment": "center",
                        "spacing": "small"
                      }
                    ]
                  }
                ],
                "style": "default",
                "selectAction": {
                  "type": "Action.Submit",
                  "data": {
                    "ux:position_ref": "4"
                  },
                  "title": ""
                },
                "spacing": "extraLarge",
                "separator": true
              }
            ]
          }`

**Comment by Nivedipa-MSFT** [comment]
@kaichun-wu - please raise user voice for this:
https://microsoftteams.uservoice.com/forums/555103-public/filters/new
