### ISSUE TITLE
[MsTeams][IOS] [adapticard compactibility on iOS devices]

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#4664]
Copied bug from: https://github.com/microsoft/AdaptiveCards/issues/3996 

**Details from original post:**
# Platform

What platform is your issue or question related to? (Delete other platforms).

* iOS

# Author or host

MSTeams

# Details

Hi ,

https://github.com/microsoft/AdaptiveCards/issues/3799
https://github.com/microsoft/AdaptiveCards/issues/3824
https://github.com/microsoft/AdaptiveCards/issues/3888
 
these are few issue we have raised on git and now with teams store update v2.0.9 it is not occurring on iPhone 10 device **but still we are facing same issue on iPhone6** .

**can you please provide me data that which all iPhone and iOS version it will supported??**

 **is Adaptive card V1.2 is available for all iOS device ??**
 

---
#### Document Details

⚠ *Do not edit this section.It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Cards reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **surbhigupta12**

**Comment by HunaidHanfee-MSFT** [comment]
We are looking into this, I will confirm internally and get back to you soon.
Thanks

**Comment by HunaidHanfee-MSFT** [comment]
@Sujit-Gaikwad - 
Could you please confirm about this comment https://github.com/microsoft/AdaptiveCards/issues/3996#issuecomment-651376961 if it is applicable for all three issue?

Thanks

**Comment by HunaidHanfee-MSFT** [comment]
@Sujit-Gaikwad -
Could you please confirm?

Thanks
