### ISSUE TITLE
[MSTeams][AdaptiveCard] Adaptive Cards Carousel not displaying in Teams

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#4667]
Copied bug from: https://github.com/microsoft/AdaptiveCards/issues/3821 

**Details from original post:**
# Platform

* .Net Core
* Bot Framework

# Author or host

* MsTeams

Hi,

I am using Bot framework V4 and I am sending the Adaptive card as a Carousel to Teams but sometimes teams is failing to load the adaptive carousel.

Note:- After waiting some time, the carousel is loading. properly.

Can you please help with the issue.

Please find the screenshot.

 
<img width="663" alt="MainCarousel" src="https://user-images.githubusercontent.com/49824279/75963486-98141580-5eeb-11ea-8470-3aceb67e0893.PNG">

---
#### Document Details

⚠ *Do not edit this section.It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Cards reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **surbhigupta12**

**Comment by HunaidHanfee-MSFT** [comment]
We are looking into this, will get back to you soon.

Thanks

**Comment by HunaidHanfee-MSFT** [comment]
@Chekrii - Are you sending same card in carousel?

**Comment by HunaidHanfee-MSFT** [comment]
@Chekrii - Could you please confirm?
