### ISSUE TITLE
.Net Adaptive card not rendering with large data in Teams

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#4668]
Copied bug from: https://github.com/microsoft/AdaptiveCards/issues/3797 

**Details from original post:**
Hi,

I am using Adaptive cards version v.1.2.4.

When I am trying to post Weather report Today , 24 Hour and 5 Day  in single message using Adaptive card in **Teams** channel using json. But it giving below error

Operation returned an invalid status code '**RequestEntityTooLarge**'   at Microsoft.Bot.Connector.Conversations.ReplyToActivityWithHttpMessagesAsync(String conversationId, String activityId, Activity activity, Dictionary`2 customHeaders, CancellationToken cancellationToken)

Is there any limitation of  size of the data that can be posted in teams using Adaptive card.
Please help me.
---
#### Document Details

⚠ *Do not edit this section.It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Cards reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **surbhigupta12**

**Comment by Nivedipa-MSFT** [comment]
@nagavamsi777
Maximum allowed length of MS Teams message is only 28 KB based on following doc.
https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams#teams-and-channels
The feature for increasing the size limit is currently in dev state and there is no ETA to share

**Comment by v-chetsh** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.
