### ISSUE TITLE
Broken URL:  call using the answer API.

### ISSUE THREAD

**Issue by Josverl** [MicrosoftDocs/msteams-docs#4669]
the link points to a non-existent beta url 

* text :  call using the answer API.
* Link :  https://developer.microsoft.com/graph/docs/api-reference/beta/api/call_answer
* assumed correct URL : https://docs.microsoft.com/en-us/graph/api/call-answer 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63d7dc57-5cd6-e66f-8c98-dac7986487c9
* Version Independent ID: 849659d8-7320-9b27-84b2-b872a772c69a
* Content: [Incoming call notifications - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/calls-and-meetings/call-notifications)
* Content Source: [msteams-platform/bots/calls-and-meetings/call-notifications.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/bots/calls-and-meetings/call-notifications.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Prasad-MSFT** [comment]
Thanks @Josverl  for pointing it out. Redirecting to documentation team to update.
