### ISSUE TITLE
Page does not mention a mechanism to remove bot that is installed with ID

### ISSUE THREAD

**Issue by codeepicure** [MicrosoftDocs/msteams-docs#4680]
As part of the instructions on installing a bot, there is a method where you can use the Bot ID to initiate a 1-1 chat with it. 

However, there is no mechanism to remove the Bot from the users chat once testing is done in this method. How do you remove such a bot after testing is complete?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45ca0926-65fc-66a5-b881-5b99a589f2ec
* Version Independent ID: b9e40da9-1029-f65f-18b5-f450a8ea87d2
* Content: [Test and debug your bot locally - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/debug/locally-with-an-ide)
* Content Source: [msteams-platform/bots/how-to/debug/locally-with-an-ide.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/bots/how-to/debug/locally-with-an-ide.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **anclear**

**Comment by sayali-MSFT** [comment]
@codeepicure - We are looking into this I will get back to you soon.

**Comment by sayali-MSFT** [comment]
@codeepicure - To remove your bot completely from Teams, go to your Bot Dashboard and edit the Microsoft Teams channel. Choose the Delete button at the bottom. This prevents users from discovering, adding, and interacting with your bot. This does not remove the bot from other user's Teams instances, however, it stops functioning for them as well.

Reference doc:-  https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/debug/locally-with-an-ide#remove-a-bot-from-a-team

**Comment by codeepicure** [comment]
@sayali-MSFT : This works well when the Bot was installed into your teams instance. My question is, how do you delete the Bot when you opened it via a direct link. 

![image](https://user-images.githubusercontent.com/39743474/143293046-b58a68af-2701-4f73-ab73-e69fe420c9be.png)

Once installed via the 'Open in Teams' link, for testing purposes, there is no way for me to remove it.

**Comment by sayali-MSFT** [comment]
@codeepicure - There doesn't seem to be any way to remove it.
"Bots in personal context cannot be disabled or removed by users."

**Comment by codeepicure** [comment]
@sayali-MSFT : How do we request such a feature be available? Without this feature we are unable to test out bots locally and remove them at a later point.

**Comment by sayali-MSFT** [comment]
@codeepicure - Could you please raise a user voice here:
https://microsoftteams.uservoice.com/forums/555103-public/filters/new

**Comment by v-chetsh** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.
