### ISSUE TITLE
Click on the expand button and the picture cannot be displayed.

### ISSUE THREAD

**Issue by 298029lkk** [MicrosoftDocs/msteams-docs#4681]
I encountered a problem on the teams desktop. When sending AdaptiveCard, I set AllowExpand=true. If this card is received in my chat window at this time, I click the expand button, and the window will become blank.
The following is what it looks like after clicking to expand:
![image](https://user-images.githubusercontent.com/25260495/143170703-5c71e2e6-5a4c-442f-bced-b383a8cd46f0.png)
 At this time, I need to switch to another chat window first, then return to it, and click the expand button of the picture to view it normally.
Could you give me some help?
My teams version is 1.4.00.31569 and it runs on windows10 x64.

**Comment by sayali-MSFT** [comment]
@298029lkk - We are looking into this I will get back to you soon.

**Comment by sayali-MSFT** [comment]
@298029lkk - We tried to repro this issue from our end, We are able to view Adaptive Card images by simply click the expand button.
you can add following code adaptive card json file :-
"body": [
          {
            "type": "Image",
            "url": "https://picsum.photos/200/200?image=110",
            "msTeams": {
              "allowExpand": true
            }
          },
     ],

Microsoft Teams Version 1.4.00.30066 (64-bit)

Reference Doc:- https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?tabs=adaptive-md%2Cconnector-html

**Comment by 298029lkk** [comment]
@sayali-MSFT  Dear, I made a gif picture, you can take a look.
![image](https://user-images.githubusercontent.com/25260495/143228467-67043adc-51cd-4cee-be71-37c85e3863bc.gif)
If you can’t see the picture above, you can get it in the blob:
[https://htbotlogsdev.blob.core.chinacloudapi.cn/share/image.gif](url)

**Comment by sayali-MSFT** [comment]
@298029lkk - We are able to repro that issue , We have raised bug for the same and concerned team is looking into it. We will inform you once we get any update.

**Comment by shivajipotnuru** [comment]
hi, @sayali-MSFT I am also facing the same exact issue, in both teams app and chrome browser. 

**Note**: We tried in firefox browser then there is no issue.

**Comment by sayali-MSFT** [comment]
@298029lkk ,@shivajipotnuru-This bug has fixed now. Could you please update the Teams version and check again.

**Comment by 298029lkk** [comment]
@sayali-MSFT Hi, thanks for your support, I tested it and it works fine.
