### ISSUE TITLE
meetingSurfaces property not documented

### ISSUE THREAD

**Issue by gscott** [MicrosoftDocs/msteams-docs#4687]
Manifest version 1.11 shows a `meetingSurfaces` property in `configurableTabs` which is not documented, nor shown in the sample manifest, on this page.  

https://github.com/OfficeDev/microsoft-teams-app-schema/blob/58303052063cab02f2e99b0fb3ff49460883a8cf/MicrosoftTeams.schema.json#L188-L198

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f94a488-d636-92b3-21eb-c88744c8f272
* Version Independent ID: 7b3413f4-9ade-accf-5cb2-83fead11a32a
* Content: [Manifest schema reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema#configurableproperties)
* Content Source: [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/resources/schema/manifest-schema.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by v-chetsh** [comment]
@gscott - Thanks for your feedback.
We will check on it and redirect it properly, if required.

**Comment by HunaidHanfee-MSFT** [comment]
Hello,
The `meetingSurfaces` property is not supported to use by developer. If you want to build an app having `meetingSidePanel` and `meetingStage` capabilities, you need add `meetingSidePanel` and `meetingStage` in [configurableTabs](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema#configurabletabs) `context` section. Please refer to this doc to understand more [Shared meeting stage](https://docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings#shared-meeting-stage)

**Comment by HunaidHanfee-MSFT** [comment]
We are closing this issue, please let us know if you any query.
