### ISSUE TITLE
Android Calls dial only showing 1 2 3

### ISSUE THREAD

**Issue by hjorleifurs** [MicrosoftDocs/msteams-docs#469]
It's just an empty space under 1 2 3 in the dial and when clicked it also only puts 1 2 3 in the number field. I have an enterprise account through my work.

**Comment by Wajeed-msft** [comment]
@hjorleifurs - Could you please share sceenshot for this?

**Comment by hjorleifurs** [comment]
![thumbnail_screenshot_20190228-110138_teams](https://user-images.githubusercontent.com/2487473/53562821-515a4580-3b4a-11e9-98b2-f9e8c1c67614.jpg)

My phone is Samsung Galaxy 7s edge and is fully upgraded both from samsung and all apps

**Comment by hjorleifurs** [comment]
also if I press the space under 1 2 3 I also only get 1 2 3 in the dial, so by pressing the invisible column under 1 will just show 1 on the dial and for the invisible column under 2 shows 2 in the dial, so it is not just the display of the numbers that is missing.

**Comment by Wajeed-msft** [comment]
Could you please share your current app version? Please do shake and send to report this as well.

**Comment by hjorleifurs** [comment]
I have filed in a report with a short descriptio, from the app, with a link to this thread for more information. Here is a screenshot from the app with the version number
![screenshot_20190301-083853_teams](https://user-images.githubusercontent.com/2487473/53629655-000f8c00-3c06-11e9-8511-ce763b4e7ce3.jpg)

**Comment by Wajeed-msft** [comment]
@hjorleifurs - Could you please try this in latest build?

**Comment by hjorleifurs** [comment]
sorry about this very late reply but I was just busy in other stuff. But excellent news, this is working as it should and we have just replaced all the phones here at my office with the teams phone :)
