### ISSUE TITLE
Bot daily task reminder

### ISSUE THREAD

**Issue by AbhijeetThakur-msft** [MicrosoftDocs/msteams-docs#4690]
Hi Team,

This sample demos a feature where user can schedule a recurring task and get a reminder on the scheduled time.

Please add the following sample links to the document for further reference:

|    | Sample Name        | Description                                                                                                                | C#    | Nodejs
|:--:|:-------------------|:---------------------------------------------------------------------------------------------------------------------------|:--------|:-------------|
|1|Bot daily task reminder            | This sample demos a feature where user can schedule a recurring task and get a reminder on the scheduled time             |                            [View](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/bot-daily-task-reminder/csharp)     |[View](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/bot-daily-task-reminder/nodejs)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3af8496d-46be-a691-11e1-16734f71f891
* Version Independent ID: be0ff3e1-8bef-5ca7-8d9c-566e89e3fd41
* Content: [Bots in Microsoft Teams - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/what-are-bots)
* Content Source: [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/bots/what-are-bots.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **anclear**

**Comment by v-chetsh** [comment]
@surbhigupta12 - Could you please help us to update the documentation.
