### ISSUE TITLE
How to send proactive message using the v4.0 prerelease nuget package? 

### ISSUE THREAD

**Issue by dpaulino** [MicrosoftDocs/msteams-docs#470]
Using a bot, I am trying to send a proactive message to a private 1:1 chat with a user in Teams. However, my bot project is .net core and it seems to me that this documentation is only for the .net framework-compatible nuget package. The v4.0 prerelease nuget package does support .net core, but it does not seem to have the same functionality as the .net framework nuget package.

 Are there any documents related to creating a proactive message using the v4.0 (prerelease) nuget package?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba8d3979-14f5-3105-ad89-ce6f98d11df1
* Version Independent ID: e53a7d1e-0e70-ca30-9809-fda7ebe5f4da
* Content: [Proactive messages - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/bots/bot-conversations/bots-conv-proactive#starting-personal-conversations)
* Content Source: [msteams-platform/concepts/bots/bot-conversations/bots-conv-proactive.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/bots/bot-conversations/bots-conv-proactive.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by clearab** [comment]
Not currently, no. We will be updating our documentation around the time that the  v4 SDKs go to general availability.

The method that you're looking for is:

> teamsContext.GetConversationParametersForCreateOrGetDirectConversation

You can see a unit test where this method is used here:
https://github.com/OfficeDev/BotBuilder-MicrosoftTeams-dotnet/blob/master/CSharp/UnitTests/Microsoft.Bot.Builder.Teams.Tests/ConnectorExtensionTests.cs
