### ISSUE TITLE
registerOnSaveHandler timeouts after 30 sec

### ISSUE THREAD

**Issue by HunaidHanfee-MSFT** [MicrosoftDocs/msteams-docs#4708]
[Enter feedback here]
We need to add a note in the documentation about registerOnSaveHandler timeout.

The developer has 30 seconds to complete the async save operation (i.e. the callback passed to registerOnSaveHandler). After that it gets timeout and show a generic error to the user.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b94a38e-82f8-45a1-8ccc-b0a96edd0404
* Version Independent ID: 6e077924-9658-cdd2-50de-0f9561d6366b
* Content: [Create a configuration page - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/configuration-page)
* Content Source: [msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by v-chetsh** [comment]
Looks like changes are done.
