### ISSUE TITLE
registerOnRemoveHandler timeouts after 15 sec

### ISSUE THREAD

**Issue by HunaidHanfee-MSFT** [MicrosoftDocs/msteams-docs#4709]
We need to add a note in the documentation about registerOnRemoveHandler  timeout.

The remove flow (i.e. the callback passed to registerOnRemoveHandler) it only get 15 seconds to respond and also automatically light up the "Remove" button after 5 seconds even if the app developer hasn't yet called setValidityState(true)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd464705-49f1-e180-8ef3-a6be50527cd6
* Version Independent ID: 54aca1c7-403d-6da6-0e25-98194da71d65
* Content: [Create a tab removal page - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/removal-page)
* Content Source: [msteams-platform/tabs/how-to/create-tab-pages/removal-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tabs/how-to/create-tab-pages/removal-page.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by v-chetsh** [comment]
Looks like changes are done.
