### ISSUE TITLE
Open DevTools doesn't open dev tools

### ISSUE THREAD

**Issue by mdbollman** [MicrosoftDocs/msteams-docs#471]
In the most recent versions of both the Win10 and Mac installed apps, the dev tools don't open. There is also no feedback as to what is actually happening, just nothing happens.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ed43afa-25da-3e1e-652b-e901264f9983
* Version Independent ID: 7121d23b-5b21-c914-e78e-5daafb273f50
* Content: [Accessing DevTools from the Teams Desktop Client - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/dev-preview/developer-preview-tools)
* Content Source: [msteams-platform/resources/dev-preview/developer-preview-tools.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/resources/dev-preview/developer-preview-tools.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Wajeed-msft** [comment]
@mdbollman - Do you have any tab opened which you want to inspect? You need to have a tab open to inspect or to use the dev tools.

**Comment by mdbollman** [comment]
Confirmed working for a tab I've created. 

So this doesn't work for a chat thread with my bot? I'm having auth issues and want to debug this process.

**Comment by Wajeed-msft** [comment]
DevTools does not work for chat  conversation. If you are facing auth issue for your bot then you could debug it locally using [ngrok](https://docs.microsoft.com/en-us/microsoftteams/platform/get-started/get-started-dotnet-app-studio#tunnel-using-ngrok).
