### ISSUE TITLE
ConversationsService: getChatConversation(): XXX not chat. actual type: Topic

### ISSUE THREAD

**Issue by pamartn** [MicrosoftDocs/msteams-docs#4721]
Hi,

When I try to add my custom test tab to a channel in Microsoft Teams I can't click the save button.

Here is the error if I try to add it to the "General" channel:

`ConversationsService: getChatConversation(): 19:-XXXXXX@thread.tacv2 not chat. actual type: Space`

I created another channel named Test and here is the error I get when I try to add it:

`ConversationsService: getChatConversation(): XXXXXX@thread.tacv2 not chat. actual type: Topic`

The `XXXXXX` are some Ids that are hidden for security purpose (idk if this is useful or not).

I use App Studio to manage app informations and manifest.

I tried adding this code snippet in the web app:
```
document.addEventListener("DOMContentLoaded", function (event) {
        console.log(microsoftTeams);
        microsoftTeams.initialize(() => {
            console.log('Initialize');
        });
        microsoftTeams.getContext(function (context) {
            console.log('Get context');
            microsoftTeams.settings.registerOnSaveHandler(function (saveEvent) {

                microsoftTeams.settings.setSettings({
                    contentUrl: "XXXXXXXXX",
                    suggestedDisplayName: "XXXXXXXXXXX",
                });

                saveEvent.notifySuccess();
            });

            microsoftTeams.settings.setValidityState(true);

            console.log('Success !!!');
        });
    });
    
```
   
   
but nothing is displayed in the console (only microsoftTeams object which is well imported)

**Comment by Nivedipa-MSFT** [comment]
@pamartn - Could you please elaborate on how you are adding tab to channel or share some repro steps.It help us to repro the issue.

**Comment by v-chetsh** [comment]
@pamartn - Could you please refer below sample code.
https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/main/samples/tab-channel-group/mvc-csharp/Views/Tab/Tab.cshtml

Also please let us know if you need any help here.

**Comment by v-chetsh** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.
