### ISSUE TITLE
UI got corrupted, right arrow is shown at left side

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#4722]
Copied bug from: https://github.com/microsoft/AdaptiveCards/issues/6787 

**Details from original post:**
### Target Application

Microsoft Teams

### Application Operating System

Windows

### Schema Version

v1.2

### Problem Description

After coming back to previous slider with Shift+Tab key after navigating to previous slide then UI got corrupted right arrow is shown left side.

### Expected Outcome

UI of the arrow icons should not corrupt after moving back to pervious slide

### Actual Outcome

UI of the arrow icons is corrupting after moving back to pervious slide

### Card JSON

```JSON
<msg><Adaptive>{
  "type": "AdaptiveCard",
  "version": "1.2",
  "body": [
    {
      "type": "Container",
      "style": "emphasis",
      "items": [
        {
          "type": "Container",
          "style": "default",
          "bleed": true,
          "items": [
            {
              "type": "TextBlock",
              "text": "sample text",
              "wrap": true,
              "size": "Medium",
              "weight": "Bolder"
            },
            {
              "type": "TextBlock",
              "text": "sample text",
              "wrap": true,
              "maxLines": 4
            },
            
          ]
        }
      ]
    }
  ],
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json"
}</Adaptive><Adaptive>{
  "type": "AdaptiveCard",
  "version": "1.2",
  "body": [
    {
      "type": "Container",
      "style": "emphasis",
      "items": [
        {
          "type": "Container",
          "style": "default",
          "bleed": true,
          "items": [
            {
              "type": "TextBlock",
              "text": "sample text",
              "wrap": true,
              "size": "Medium",
              "weight": "Bolder"
            },
            {
              "type": "TextBlock",
              "text": "sample text",
              "wrap": true,
              "maxLines": 4
            },
            
          ]
        }
      ]
    }
  ],
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json"
}
```

### Repro Steps

_No response_---
#### Document Details

⚠ *Do not edit this section.It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Cards reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **surbhigupta12**

**Comment by sayali-MSFT** [comment]
@prajwalmanju - We are looking into this I will get back to you soon.

**Comment by sayali-MSFT** [comment]
@prajwalmanju -We tried to repro this issue from our end, We are not able to got corrupted right arrow.
 Could you please share steps you followed so that we can repro it at our end.

**Comment by sayali-MSFT** [comment]
We tried to repro the issue with NVDA and its working fine at our end. The UI is not getting corrupted if we click on 'shift + tab ' key after navigating to previous slide in carousal card. Microsoft Teams Version 1.4.00.32721
Please try to update MS Teams client and check once if it helps.

**Comment by prajwalmanju** [comment]
Hello Team,

I have retested the issue by updating my Teams Desktop Client, I'm still facing this issue.
Please find the screen shot attached.

Thanks!

![image](https://user-images.githubusercontent.com/93922557/145445317-69e62897-3daa-46de-8b6f-f2731458a12c.png)

**Comment by sayali-MSFT** [comment]
@prajwalmanju - We have raised bug for the same and concerned team is looking into it. We will inform you once we get any update.

**Comment by v-chetsh** [comment]
@prajwalmanju - Engineering team is not able to reproduce the issue at their end. Could you please confirm whether the issue is still persist?
