### ISSUE TITLE
Instead of reading new card, screen reader is reading existing card along with new card, when card is updated

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#4723]
Copied bug from: https://github.com/microsoft/AdaptiveCards/issues/6785 

**Details from original post:**
### Target Application

Microsoft Teams

### Application Operating System

Windows

### Schema Version

v1.2

### Problem Description

When any action by user like button click bot is replacing with existing card with a new card. And upon trying to focus new card first the screen reader is reading Existing card and then New card details are pronounced. Eg. Unilever dictionary, Adaptive card cancel response

### Expected Outcome

when any card replacing with existing card with a new card. upon focusing on the updated card screen reader should read only updated card instead of previous card along with updated card.

### Actual Outcome

when any card replacing with existing card with a new card. upon focusing on the updated card screen reader is start reading previous card along with updated card.

### Card JSON

```JSON
NA
```

### Repro Steps

_No response_---
#### Document Details

⚠ *Do not edit this section.It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Cards reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **surbhigupta12**

**Comment by Prasad-MSFT** [comment]
@prajwalmanju   -We are checking the issue. Will get back to you shortly

**Comment by Prasad-MSFT** [comment]
@prajwalmanju - We tried to repro the issue with Narrator and can confirm that the it reads out existing card along with new card when the card is updated. Please let us know if you are using the same tool or not.

**Comment by prajwalmanju** [comment]
Hello Team,

We are using NVDA and JAWS tools to reproduce this issue.

Thanks!

**Comment by Prasad-MSFT** [comment]
@prajwalmanju - We are able to repro the issue and have raised a bug for this. We will inform you once we have any update.
Thanks!

**Comment by prajwalmanju** [comment]
Hello Team,
Any update on this issue ?

**Comment by Prasad-MSFT** [comment]
@prajwalmanju - Engineering team is looking into the issue . We will inform you once we get any update.

**Comment by Prasad-MSFT** [comment]
Engineering team is looking into the issue . We will inform you once we get any update.

**Comment by v-chetsh** [comment]
Engineering team is not able to reproduce the issue using NVDA at their end. Could you please confirm whether the issue is still persisting?
