### ISSUE TITLE
Arrow icons got disappeared in carousal

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#4724]
Copied bug from: https://github.com/microsoft/AdaptiveCards/issues/6786 

**Details from original post:**
### Target Application

Microsoft Teams

### Application Operating System

Windows

### Schema Version

v1.2

### Problem Description

After all buttons are focused with tab key and after last button then on Tab key press right arrow is selected and arrow icons got disappeared

### Expected Outcome

Arrow icons should not disappeared after click on tab key.

### Actual Outcome

Arrow icons are disappearing after click on tab key.

### Card JSON

```JSON
<msg><Adaptive>{
  "type": "AdaptiveCard",
  "version": "1.2",
  "body": [
    {
      "type": "Container",
      "style": "emphasis",
      "items": [
        {
          "type": "Container",
          "style": "default",
          "bleed": true,
          "items": [
            {
              "type": "TextBlock",
              "text": "sample text",
              "wrap": true,
              "size": "Medium",
              "weight": "Bolder"
            },
            {
              "type": "TextBlock",
              "text": "sample text",
              "wrap": true,
              "maxLines": 4
            },
            
          ]
        }
      ]
    }
  ],
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json"
}</Adaptive><Adaptive>{
  "type": "AdaptiveCard",
  "version": "1.2",
  "body": [
    {
      "type": "Container",
      "style": "emphasis",
      "items": [
        {
          "type": "Container",
          "style": "default",
          "bleed": true,
          "items": [
            {
              "type": "TextBlock",
              "text": "sample text",
              "wrap": true,
              "size": "Medium",
              "weight": "Bolder"
            },
            {
              "type": "TextBlock",
              "text": "sample text",
              "wrap": true,
              "maxLines": 4
            },
            
          ]
        }
      ]
    }
  ],
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json"
}
```

### Repro Steps

_No response_---
#### Document Details

⚠ *Do not edit this section.It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Cards reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **surbhigupta12**

**Comment by Meghana-MSFT** [comment]
We are looking into this issue. We will update you.

**Comment by Meghana-MSFT** [comment]
We tried with below carousal cards, but we are unable to move reach Open and Alarms buttons within carousal card. Could you please help by providing repro steps?
![image](https://user-images.githubusercontent.com/81138249/144900409-fd009b86-335c-4c92-bbc7-2636dadb5e70.png)

**Comment by v-chetsh** [comment]
@prajwalmanju - Could you please help by providing repro steps?

**Comment by prajwalmanju** [comment]
Hello Team,

We can easily reproduce this issue if carousel list having buttons response, please find the attachment for sample JSON and sample video.

Please find the repro steps below.

1)Trigger carousal card having button response.
2)click on  "shift+tab" key
3)click on "insert + enter " and then "tab" key to get focus inside the card.
4)click on "tab" key until carousel list changed to next slide and observe arrow icons.

Thanks!

https://user-images.githubusercontent.com/93922557/146116474-b87741f9-b058-489e-a03e-521261356606.mp4
[sample Json carousal button.txt](https://github.com/MicrosoftDocs/msteams-docs/files/7716245/sample.Json.carousal.button.txt)

**Comment by Meghana-MSFT** [comment]
We do not see arrow icons disappearing. Attaching a video of the same. Please note that we are not using NVDA here.

https://user-images.githubusercontent.com/81138249/146393300-505fc29b-8fcf-4532-acaf-51eab438be62.mp4

**Comment by prajwalmanju** [comment]
Hello Meghana,

I have already attached the repro video and sample JSON in my previous comment, we are facing the issue if carousel list having buttons response. Could you please test once by using NVDA screen reader.

Thanks!

**Comment by Meghana-MSFT** [comment]
We are able to repro this issue. We have raised a bug for the same.

**Comment by Meghana-MSFT** [comment]
We are able to repro this issue. We have raised a bug for the same.

**Comment by Meghana-MSFT** [comment]
@prajwalmanju - We are not able to repro this issue, Could you please confirm if you are able to repro this issue?

**Comment by Meghana-MSFT** [comment]
@prajwalmanju - Could you please confirm if you are able to repro this issue?
