### ISSUE TITLE
List card does not have speech support.

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#4733]
Copied bug from: https://github.com/microsoft/AdaptiveCards/issues/6776 

**Details from original post:**
### Target Application

Microsoft Teams

### Application Operating System

Windows

### Schema Version

v1.2

### Problem Description

List card as a new message will be read as “message from Una, undefined.” But if one hovers over the list view, the screen reader will be able to read it.  

### Expected Outcome

Screen reader should read new message card as "message from una bot you received a card message use shift + tab key to read more"

### Actual Outcome

List card as a new message will be read as “message from Una, undefined.”

### Card JSON

```JSON
NA
```

### Repro Steps

_No response_---
#### Document Details

⚠ *Do not edit this section.It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Cards reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **surbhigupta12**

**Comment by Meghana-MSFT** [comment]
We are looking into this issue. We will update you

**Comment by Meghana-MSFT** [comment]
@prajwalmanju - We see that NVDA is reading "message from abc bot. you received a card message"  for list cards. Could you please confirm if this is what you are expecting?

**Comment by v-chetsh** [comment]
@prajwalmanju - Could you please provide your input for above query?

**Comment by prajwalmanju** [comment]
Hello Team,

When we received the card from the the bot it was simply saying "Message from the xyz bot you received a card message" instead of "Message from the bot you received a card message use "Shift + Tab " key to read more " and also once list card got opened their is no information regarding "X of N number items in the list use arrow keys to read next item in the list" .

Thanks!

**Comment by Meghana-MSFT** [comment]
We are able to repro this. We will check this internally if this expected or not?

**Comment by Meghana-MSFT** [comment]
@prajwalmanju - Currently this feature is not supported. Could you please help by raising a feature request on [Microsoft User Voice](https://feedbackportal.microsoft.com/feedback/forum/ad198462-1c1c-ec11-b6e7-0022481f8472).

**Comment by prajwalmanju** [comment]
Hello Team,

As per your input I have raised Microsoft user voice for this issue, please find the link for user voice https://feedbackportal.microsoft.com/feedback/idea/733c35e8-d964-ec11-a819-000d3a058885

Thanks!

**Comment by Meghana-MSFT** [comment]
We are closing this issue. Please feel free to re open for any further help.
