### ISSUE TITLE
[Rendering] Adaptive Card Image Not opening for the First time

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#4736]
Copied bug from: https://github.com/microsoft/AdaptiveCards/issues/6770 

**Details from original post:**
### Target Platforms

Other

### SDK Version

1.2

### Application Name

Microsoft Teams

### Problem Description

I'm Sending an Adaptive Image over the Adaptive Card
- Our Images are stored in Azure Blob Storage(Hot access)
- Image Size is Less than 1 Mb
- Before initializing the Adaptive Card we sent Images using Attachment

The issue is once the user clicks on the enlarge option on the adaptive card bot is not responding, the user has to go to another chat/app again come back and click on the adaptive card.

### Card JSON

```JSON
{
    "type": "AdaptiveCard",
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.2",
    "body": [
        {
            "type": "Image",
            "msTeams": {
                "allowExpand": true
            },
            "horizontalAlignment": "Center",
            "spacing": "Padding",
            "url": ""
        }
    ]
}
```

### Sample Code Language

C#

### Sample Code

 public  static Attachment ImageCard(string pathURL)
        {
            var imageCard = new AdaptiveCard("1.5");

            var msteamsProp = new MsTeamsObject()
            {
                AllowExpand = true
            };
            SerializableDictionary<string, object> msteams = new SerializableDictionary<string, object>();
            msteams.Add("msteams", msteamsProp);

            imageCard.Body.Add(new AdaptiveImage()
            {
                Url = new Uri(pathURL),

                AdditionalProperties = msteams
            });
            return  new Attachment()
            {
                ContentType = AdaptiveCard.ContentType,
                Content = imageCard
            };
        }---
#### Document Details

⚠ *Do not edit this section.It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Cards reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **surbhigupta12**

**Comment by HunaidHanfee-MSFT** [comment]
We are looking into this. We will get back to you soon.

Thanks

**Comment by HunaidHanfee-MSFT** [comment]
We have the repro of this issue and raised a bug. Internal team is looking into it. I will let you know once it is fixed.

Thanks

**Comment by Nivedipa-MSFT** [comment]
@shivajipotnuru -  This bug has fixed now. Could you please update the Teams version and check again.
