### ISSUE TITLE
How to download file in bot?

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#4737]
Copied bug from: https://github.com/microsoft/AdaptiveCards/issues/6767 

**Details from original post:**
When I use bot card, I hope to allow users to download the file by clicking the link provided in bot message.
Could you give me some tips?---
#### Document Details

⚠ *Do not edit this section.It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Cards reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **surbhigupta12**

**Comment by Nivedipa-MSFT** [comment]
@Karl-luyi - Could you please elaborate your issue in more details or share repro steps.

**Comment by Nivedipa-MSFT** [comment]
@Karl-luyi - Could you please go through below sample if its help you in any way.
https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/bot-archive-groupchat-messages/csharp

**Comment by v-chetsh** [comment]
@karl-luyi - Could you please confirm if your issue has resolved with above suggestion or still looking for any help?

**Comment by v-chetsh** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.
