### ISSUE TITLE
[iOS][Adaptive Cards)] [Flow Bot Adaptive Card with button isn't getting displayed in Teams for iOS]

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#4738]
Copied bug from: https://github.com/microsoft/AdaptiveCards/issues/3948 

**Details from original post:**
# Platform

What platform is your issue or question related to? (Delete other platforms).
* iOS

# Author or host

Author, sending cards from Flow to Teams using the "post your own adaptive card as the Flow bot to a channel" step in my flow.

# Version of SDK
Tried formatting my message in adaptive card version 1.0 and 1.2, but that didn't make any difference.

# Details

Please have a look at the attached screenshots. The pictures are of the same message sent by the Flow bot. As you can see, on desktop, the message with the "approve" button looks like you would expect. On iOS, the message isn't displayed at all. You just see the Flow bot icon and the timestamp. 

![Screenshot 2020-04-21 at 08 57 53](https://user-images.githubusercontent.com/43379915/79845216-012ceb00-83bd-11ea-9886-53b8dc422840.png)

Please look into this, as we have people working on iPads who need to interact with these messages. ---
#### Document Details

⚠ *Do not edit this section.It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Cards reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **surbhigupta12**

**Comment by Nivedipa-MSFT** [comment]
@menbren - We are looking into this issue.We will update you.

**Comment by Nivedipa-MSFT** [comment]
@menbren - We tried your adaptive card json in iOS.We get the message on card and also approve button is clickable and going to the mentioned url.

![image](https://user-images.githubusercontent.com/92150070/144380408-53ba524a-0214-4a8e-9290-596530474a80.png)

Could you please try to update your teams version and check again.

**Comment by menbren** [comment]
Thanks for checking. I’m happy to believe that in the 20 months that have passed since I reported this issue it has been fixed already  😄

**Comment by v-chetsh** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.
