### ISSUE TITLE
[MSTeams]Placeholder is not working in Input.Number

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#4739]
Copied bug from: https://github.com/microsoft/AdaptiveCards/issues/3862 

**Details from original post:**
# Platform
* .Net Core
* Botframework v4

# Host

* MsTeams

Hi All,

Placeholder property is not as expected in Input.Number.

Earlier is was showing the placeholder text but from past few days it is displaying "0" as default.

Please find the Json pf my adaptive card and Screenshot.

<img width="380" alt="Input Number" src="https://user-images.githubusercontent.com/49824279/77228415-518e0e80-6bad-11ea-919b-f292dab646a7.PNG">

Json:-
-------
{"type":"AdaptiveCard","version":"1.0","body":[{"type":"TextBlock","text":"Please enter the days","spacing":"Medium","height":"stretch","horizontalAlignment":"Left","size":"Medium","weight":"Bolder","color":"Accent"},{"type":"Input.Number","placeholder":"Number of days","id":"id"}],"minHeight":"69px","$schema":"http://adaptivecards.io/schemas/adaptive-card.json"}

Thanks for the Help.

---
#### Document Details

⚠ *Do not edit this section.It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Cards reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **surbhigupta12**

**Comment by Prasad-MSFT** [comment]
@Chekrii - We tried to repro it but its working fine at our end both in Desktop client`(Microsoft Teams Version 1.4.00.32167)` and web client. 
Please try to update your Teams version and check if it helps. Attaching screenshot below for reference:
Desktop:
![image](https://user-images.githubusercontent.com/62237649/143994799-20962fa9-19c8-4984-8755-3824a63e8330.png)
Web:
![image](https://user-images.githubusercontent.com/62237649/143994854-043732cf-b1d0-4732-a1df-6b72e277c5fa.png)

**Comment by Prasad-MSFT** [comment]
@Chekrii - We tried to repro it but its working fine at our end both in Desktop client`(Microsoft Teams Version 1.4.00.32167)` and web client. 
Please try to update your Teams version and check if it helps. Attaching screenshot below for reference:
Desktop:
![image](https://user-images.githubusercontent.com/62237649/143994799-20962fa9-19c8-4984-8755-3824a63e8330.png)
Web:
![image](https://user-images.githubusercontent.com/62237649/143994854-043732cf-b1d0-4732-a1df-6b72e277c5fa.png)

**Comment by v-chetsh** [comment]
Could you please confirm if your issue has resolved with above suggestion or still looking for any help?

**Comment by Prasad-MSFT** [comment]
We are closing this issue for now. Please feel free to re-open if needed.
