### ISSUE TITLE
on click deep link it taking me to browser every time from Teams desktop App

### ISSUE THREAD

**Issue by nisarhukrani** [MicrosoftDocs/msteams-docs#474]
![image](https://user-images.githubusercontent.com/33654481/53339749-2e9f1580-392d-11e9-9c70-ffa92d529803.png)

**Comment by Wajeed-msft** [comment]
This is the current behaviour for deeplinks within the tabs. We are working on improving this experience.

**Comment by Wajeed-msft** [comment]
Please have a look at [Deep linking from your tab](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/deep-links#deep-linking-from-your-tab) documentation. Please use latest [Microsoft Teams JavaScript client SDK](https://docs.microsoft.com/en-us/javascript/api/overview/msteams-client?view=msteams-client-js-latest).

To trigger a deeplink from your tab you should call:
`microsoftTeams.executeDeepLink(/*deepLink*/);`
