### ISSUE TITLE
MS teams Adaptive Card not opening on Mobile Devices

### ISSUE THREAD

**Issue by Chang025** [MicrosoftDocs/msteams-docs#4741]
The adaptive cards are working perfectly fine at desktop browsers and desktop teams app, but we are not able to open the adaptive cards on iOS and android. It shows a blank tile on the mobile app.

Details:
Request JSON: 
`{
  : type=>"message",
  : version=>"1.5",
  : attachments=>[
    {
      : contentType=>"application/vnd.microsoft.card.adaptive",
      : content=>{
        : type=>"AdaptiveCard",
        : body=>[
          {
            : type=>"TextBlock",
            : text=>"Please select one:",
            : wrap=>true
          },
          {
            : type=>"ColumnSet",
            : columns=>[
              {
                : type=>"Column",
                : width=>"auto",
                : items=>[
                  {
                    : type=>"ActionSet",
                    : actions=>[
                      {
                        : type=>"Action.Submit",
                        : title=>"small",
                        : associatedInputs=>"none",
                        : data=>{
                          : msteams=>{
                            : type=>"messageBack",
                            : displayText=>"small",
                            : text=>"small"
                          }
                        }
                      }
                    ],
                    : horizontalAlignment=>"Center"
                  }
                ]
              },
              {
                : type=>"Column",
                : width=>"auto",
                : items=>[
                  {
                    : type=>"ActionSet",
                    : actions=>[
                      {
                        : type=>"Action.Submit",
                        : title=>"medium",
                        : associatedInputs=>"none",
                        : data=>{
                          : msteams=>{
                            : type=>"messageBack",
                            : displayText=>"medium",
                            : text=>"medium"
                          }
                        }
                      }
                    ],
                    : horizontalAlignment=>"Center"
                  }
                ]
              },
              {
                : type=>"Column",
                : width=>"auto",
                : items=>[
                  {
                    : type=>"ActionSet",
                    : actions=>[
                      {
                        : type=>"Action.Submit",
                        : title=>"large",
                        : associatedInputs=>"none",
                        : data=>{
                          : msteams=>{
                            : type=>"messageBack",
                            : displayText=>"large",
                            : text=>"large"
                          }
                        }
                      }
                    ],
                    : horizontalAlignment=>"Center"
                  }
                ]
              }
            ]
          }
        ]
      }
    }
  ],
  "$schema"=>"http://adaptivecards.io/schemas/adaptive-card.json",
  : from=>{
    "id"=>"****",
    "name"=>"****"
  },
  : conversation=>{
    "conversationType"=>"personal",
    "tenantId"=>"****",
    "id"=>"****"
  },
  : recipient=>{
    "id"=>"****",
    "name"=>"****",
    "aadObjectId"=>"******"
  }
}`

Desktop app:
<img width="1429" alt="Screenshot 2021-11-30 at 12 10 55 PM" src="https://user-images.githubusercontent.com/46022906/143998331-68cfa381-7aeb-431d-b417-a4833b0e344a.png">

Mobile iOS app:
![Skype_Picture_2021_11_30T06_41_22_051Z](https://user-images.githubusercontent.com/46022906/143998405-cbe8eb25-7304-47ff-a148-6322a03cd7b7.jpeg)

Let us know if we are missing anything in the JSON, or it is a bug.

**Comment by sayali-MSFT** [comment]
@Chang025  - We are looking into this I will get back to you soon.

**Comment by Chang025** [comment]
@sayali-MSFT - Any update on this?

**Comment by v-chetsh** [comment]
@Chang025 - We have tried the JSON provided by you and it's working for us in Teams Desktop client and in iOS device as well.
Desktop Teams client UI:
![image](https://user-images.githubusercontent.com/59052547/144409435-028a8e26-6107-4566-b928-ac9194ea86ed.png)

![image](https://user-images.githubusercontent.com/59052547/144409518-bb24a85b-e9d6-498e-91bf-3fec8543f83b.png)


iOS mobile Teams client UI:
![image](https://user-images.githubusercontent.com/59052547/144409874-732af41b-2ed1-4fde-a11e-ea6189d06a05.png)
![image](https://user-images.githubusercontent.com/59052547/144409935-1dc0e075-a356-4b30-a5d4-6b574f8f0add.png)

I have checked it in Teams desktop client version: Microsoft Teams Version 1.4.00.29469 (64-bit)
iOS device version: 15.1
iOS device Teams version: 3.19.0

Could you please try updating it and check it once.

Note: I have tested it in App Studio.

**Comment by Chang025** [comment]
@v-chetsh - We are able to render the adaptive cards for mobile devices now. We were not passing the version and $schema to the correct place that was causing issues.
Closing this issue now, thanks.
