### ISSUE TITLE
Device permissions for the browser - Need help to add sample code links in documentation.

### ISSUE THREAD

**Issue by AbhijeetThakur-msft** [MicrosoftDocs/msteams-docs#4753]
Hi Team,

We implemented sample to show Device permissions for the browser.

Please add the following sample links to the document for further reference:

|    | Sample Name        | Description                                                                                                                | Nodejs   |
|:--:|:-------------------|:---------------------------------------------------------------------------------------------------------------------------|:--------|
|1|Tab device permissions           | The sample shows device permissions for browser.                                   |[View](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/tab-device-permissions/nodejs)     |

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77f59ab2-3b64-db1c-253e-d040e9095050
* Version Independent ID: 77f59ab2-3b64-db1c-253e-d040e9095050
* Content: [Device permissions for the browser - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/browser-device-permissions)
* Content Source: [msteams-platform/concepts/device-capabilities/browser-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/device-capabilities/browser-device-permissions.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by v-chetsh** [comment]
@surbhigupta12 - Could you please help us to update the contents.
