### ISSUE TITLE
Update the blurb on channelData

### ISSUE THREAD

**Issue by siduppal** [MicrosoftDocs/msteams-docs#4754]
ChannelData *is* present even in personal conversations with the bot. It does NOT include team-id and channel-id in that case, but it still includes the tenant-id.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae6b8c5f-dbce-1020-f97d-873c19a097e5
* Version Independent ID: b7906ada-45a3-4fd7-23fa-656ed00550e3
* Content: [Send and receive messages with a bot - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bot-conversations/bots-conversations)
* Content Source: [msteams-platform/resources/bot-v3/bot-conversations/bots-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/resources/bot-v3/bot-conversations/bots-conversations.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Nivedipa-MSFT** [comment]
Hi doc team, It looks like channeldata is present even in personal conversations with the bot. It does not include team-id and channel-id but it still includes the tenant-id. Could you please help us to update the content accordingly.

**Comment by Nivedipa-MSFT** [comment]
@siduppal -  Could you please confirm if this is what you are asking to remove?

"channelData": {
"tenant": {
"id": "72f988bf-86f1-41af-91ab-2d7cd011db47"
}

https://docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bot-conversations/bots-conversations#full-inbound-schema-example

**Comment by HunaidHanfee-MSFT** [comment]
Hello doc team, 
We got a confirmation from engineering team and they said that this statement 
_The channelData object is not included in messages in personal conversations since these take place outside of any channel._ is incorrect and should be removed from the documentation. 

NOTE -  _ChannelData is present in all activities sent from SMBA to bots for Teams scenarios and it always contains TenantId in it._

**Comment by HunaidHanfee-MSFT** [comment]
@surbhigupta12 - Could you please help us to update this document?
