### ISSUE TITLE
Incoming calls from PTSN to Call Queues are silent.

### ISSUE THREAD

**Issue by JoshMajeno** [MicrosoftDocs/msteams-docs#476]
When we receieve phone calls from the PTSN, and we answer it from the Call Queue we will be unable to hear the person on the other end but they can hear us.

We've got a few tickets opened with O365 support at the moment, but I'm pretty sure it's a bug and not a configuration issue as it's happening on Teams Only and Islands.

**Comment by JoshMajeno** [comment]
Quick note, on iOS you can turn speaker off and on as a work around.

This does not work on Android.

**Comment by Wajeed-msft** [comment]
@JoshMajeno - This issue has been fixed. Could you please try this once at your end and confirm?
