### ISSUE TITLE
is it ok to use MSAL.js library to pop up login page in Teams tab app?

### ISSUE THREAD

**Issue by blackchoey** [MicrosoftDocs/msteams-docs#4761]
This document provides a way to use `microsoftTeams.authentication.authenticate()` and a `/tab-auth/simple-start` page to pop up an AAD login page.
We're following this [document](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-spa-acquire-token?tabs=javascript2) to use MSAL.js library in our Teams tab app. Seems we can finish the auth code flow using MSAL.js library without any problem. I want to understand is it supported to not use `microsoftTeams.authentication.authenticate()` and `/tab-auth/simple-start` page (like what we do) to pop up the login page and acquire access token?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b1dcd0d-471b-2d33-54b5-39a93dfba2a8
* Version Independent ID: 5bd44149-777e-b449-bd2e-f20b9bd04038
* Content: [Authentication for tabs using Azure Active Directory - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-tab-aad)
* Content Source: [msteams-platform/tabs/how-to/authentication/auth-tab-aad.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tabs/how-to/authentication/auth-tab-aad.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by sayali-MSFT** [comment]
@blackchoey - We are looking into this I will get back to you soon.

**Comment by blackchoey** [comment]
@sayali-MSFT thank you, we just observed this seems cannot work on Teams Desktop client (though it works on Teams Web client). Can you share a list of MSAL.js features that fully supported by Teams when building tab app? So we can stick on these supported features when building apps,

**Comment by sayali-MSFT** [comment]
@blackchoey  - Please have a look at this doc- https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-browser#msal-basics
Let us know if you have any query.

**Comment by Meghana-MSFT** [comment]
We need to use either microsoft.authentication.autheticate() or getAuthToken() to make authentication work in Teams.

1. [Single sign-on (SSO) support for tabs](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-aad-sso#3-get-an-access-token-from-your-client-side-code)
2. [Microsoft Teams authentication flow for tabs](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-flow-tab)

**Comment by blackchoey** [comment]
Thank you @Meghana-MSFT we will use the way you recommended. I have 2 further questions, can you help on them?
1. When using `microsoftTeams.authentication.authenticate()`, is it required to provide 2 pages (auth-start.html and auth-end.html), or we can just provide 1 page as long as the page can execute `microsoftTeams.authentication.notifySuccess()` correctly?
2. We would like to adopt `ssoSilent()` feature in MSAL ([doc](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/login-user.md#silent-login-with-ssosilent)) to reduce the login requirement as much as possible. Can you share whether Teams has any limitation on using this feature in tab app?

**Comment by Meghana-MSFT** [comment]
1. You need to use auth-start.html and auth-end.html. Giving a [Tab SSO sample](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/v-abt/tab-coversations/samples/tab-sso/csharp/TeamsTabSSO/Views/Auth) for your reference. 
2. Please go through this [Teams authentication flow for tabs](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-flow-tab) for details regarding Tab authentication

**Comment by blackchoey** [comment]
Thank you @Meghana-MSFT
For the second question, seems the [document](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-flow-tab) you shared does not talk about this.
Here're some more details about the scenario we want to improve: if users open the tab app in another machine, they need to explicitly click login button to login again. And we want to adopt `ssoSilent()` feature in MSAL which tries to login current user automatically to reduce the login requirement in this case. Currently `ssoSilent()` sometimes will throw timeout error, so we would like to confirm if Teams has any limitation or it's an issue in MSAL.

**Comment by Meghana-MSFT** [comment]
The above mentioned Teams authentication flow does the same, If you login to Teams app then it does SSO for Tabs without asking for authentication expicitly.

**Comment by blackchoey** [comment]
Thank you very much. Are you able to ping me internally? Sorry that I could not identify which Meghana is you... I would like have a quick chat to share our ideas and seek for your feedbacks if possible.

**Comment by blackchoey** [comment]
@Meghana-MSFT The Teams authentication flow is good, however we're trying to auto login users (and silently) if possible which seems not supported by the flow:
1. The flow should not be triggered automatically per this [document](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-tab-aad#initiate-authentication-flow).
2. The flow will pop up a window for users, though the login can finish automatically.

That's why we're trying to leverage `MSAL.ssoSilent()` to achieve the auto silent login. Of course, if the method failed, we will fallback to `microsoftTeams.authentication.authenticate()` to ask user login explicitly.

What we want to know is: whether there's any known limitations on the use of `MSAL.ssoSilent()` in Teams tab app? Since `MSAL.ssoSilent()` occasionally throw error in Teams desktop client (it may not be a Teams issue), and there's known limitation on the use of `MSAL.loginPopup()` (it cannot work in Teams desktop client), we want to double confirm on `MSAL.ssoSilent()` either.

**Comment by Meghana-MSFT** [comment]
TabSSO authentication uses Single Sign on authentication, where it picks the authentication context from the Microsoft Teams itself and silently authenticate. It does not show the login pop up.

**Comment by blackchoey** [comment]
Sorry for the delayed response. I think there're some gap between us: our goal is acquiring a token for external service (e.g. Microsoft Graph) which is not part of our tab app. TabSSO authentication in Teams can only provide a token for our tab app (the token audience is not Microsoft Graph), which cannot satisfy our requirement when building a Single Page Application as Teams tab app.

The name of `MSAL.ssoSilent()` is indeed misleading in our discussion. The current situation is: we feels `MSAL.ssoSilent()` can help us achieve a better user experience when we need to acquire a Microsoft Graph token. And we want to know if there's any limitation on the use of it.

**Comment by Meghana-MSFT** [comment]
The silent token requests to Azure AD might fail for reasons like a password change or updated conditional access policies, in that case we would have to manage it at our end and provide fallback and proper user experience.

You can refer the document that you are currently referring to see how this is managed -  [Acquire a token to call a web API (single-page apps) - Microsoft identity platform | Microsoft Docs](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-spa-acquire-token?tabs=react)

Also sharing sample link for a scenario where we are using MSAL on-behalf-of flow and calling graph - [Microsoft-Teams-Samples/samples/tab-sso/nodejs at v-nikija/tab-sso-obo-update · OfficeDev/Microsoft-Teams-Samples (github.com)](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/v-nikija/tab-sso-obo-update/samples/tab-sso/nodejs)

**Comment by Meghana-MSFT** [comment]
We are closing this issue. Please feel free to re open if you need any help.
