### ISSUE TITLE
MS Teams Appointment doesn't render images from synced outlook appointment

### ISSUE THREAD

**Issue by vitaliishandra** [MicrosoftDocs/msteams-docs#4763]
MS Teams version: 1.4.00.29469 (64-bit).
OS: Windows
Is reproduced in Web client: yes.

We have the appointment in Outlook that is automatically synced to MS Teams. Unfortunately the MS Teams doesn't render the images in it (the example is below). There is img src=(unknown) in appointment HTML. 
![image](https://user-images.githubusercontent.com/56965286/144203259-c4ec6f84-e96c-4eb2-af4d-31fab5a5c799.png)

There is the following request when I am trying to open the appointment: https://teams.microsoft.com/api/mt/amer/beta/me/calendarEvents/AAMkAGU2MWE0YmI2LWQzZWEtNGM2YS1iZGE3LWU5YmJmNmIwNmQwNgBGAAAAAADxldLYz-5VQqsR3G0YzTV6BwBsTOqnvCqjTpjS2Xq4NMs3AAAAAAENAABsTOqnvCqjTpjS2Xq4NMs3AALdDmcYAAA=?useICalUId=false&eventType=&eventStartDateTime=

The request response contains the appointment HTML with the correct image URL (I copied it to JSON viewer and it correctly renders Images, also direct image urls from the response works). Are there any way to resolve the issue?
![image](https://user-images.githubusercontent.com/56965286/144203342-414f6748-4866-4a4e-8717-913405c596ef.png)

**Comment by sayali-MSFT** [comment]
@vitaliishandra - We are looking into this I will get back to you soon.

**Comment by v-chetsh** [comment]
Looks like this question is related to teams product, so redirecting it.
