### ISSUE TITLE
MS teams: Adaptive Card ColumnSet HorizontalAlignment property is not working

### ISSUE THREAD

**Issue by Chang025** [MicrosoftDocs/msteams-docs#4766]
We are using this JSON to render quick reply card for our usecase:
`{
  "type": "AdaptiveCard",
  "body": [
    {
      "type": "TextBlock",
      "text": "Please select one:",
      "wrap": true
    },
    {
      "type": "ColumnSet",
      "columns": [
        {
          "type": "Column",
          "width": "auto",
          "items": [
            {
              "type": "ActionSet",
              "actions": [
                {
                  "type": "Action.Submit",
                  "title": "Very Small",
                  "associatedInputs": "none",
                  "data": {
                    "msteams": {
                      "type": "messageBack",
                      "displayText": "Very Small",
                      "text": "Very Small"
                    }
                  }
                }
              ],
              "horizontalAlignment": "Center"
            }
          ]
        },
        {
          "type": "Column",
          "width": "auto",
          "items": [
            {
              "type": "ActionSet",
              "actions": [
                {
                  "type": "Action.Submit",
                  "title": "Small",
                  "associatedInputs": "none",
                  "data": {
                    "msteams": {
                      "type": "messageBack",
                      "displayText": "Small",
                      "text": "Small"
                    }
                  }
                }
              ],
              "horizontalAlignment": "Center"
            }
          ]
        },
        {
          "type": "Column",
          "width": "auto",
          "items": [
            {
              "type": "ActionSet",
              "actions": [
                {
                  "type": "Action.Submit",
                  "title": "Medium",
                  "associatedInputs": "none",
                  "data": {
                    "msteams": {
                      "type": "messageBack",
                      "displayText": "Medium",
                      "text": "Medium"
                    }
                  }
                }
              ],
              "horizontalAlignment": "Center"
            }
          ]
        }
      ],
      "horizontalAlignment": "Right"
    },
    {
      "type": "ColumnSet",
      "columns": [
        {
          "type": "Column",
          "width": "auto",
          "items": [
            {
              "type": "ActionSet",
              "actions": [
                {
                  "type": "Action.Submit",
                  "title": "Large",
                  "associatedInputs": "none",
                  "data": {
                    "msteams": {
                      "type": "messageBack",
                      "displayText": "Large",
                      "text": "Large"
                    }
                  }
                }
              ],
              "horizontalAlignment": "Center"
            }
          ]
        },
        {
          "type": "Column",
          "width": "auto",
          "items": [
            {
              "type": "ActionSet",
              "actions": [
                {
                  "type": "Action.Submit",
                  "title": "Extra Large",
                  "associatedInputs": "none",
                  "data": {
                    "msteams": {
                      "type": "messageBack",
                      "displayText": "Extra Large",
                      "text": "Extra Large"
                    }
                  }
                }
              ],
              "horizontalAlignment": "Center"
            }
          ]
        },
        {
          "type": "Column",
          "width": "auto",
          "items": [
            {
              "type": "ActionSet",
              "actions": [
                {
                  "type": "Action.Submit",
                  "title": "Double Extra Large",
                  "associatedInputs": "none",
                  "data": {
                    "msteams": {
                      "type": "messageBack",
                      "displayText": "Double Extra Large",
                      "text": "Double Extra Large"
                    }
                  }
                }
              ],
              "horizontalAlignment": "Center"
            }
          ]
        }
      ],
      "horizontalAlignment": "Right"
    },
    {
      "type": "ColumnSet",
      "columns": [
        {
          "type": "Column",
          "width": "auto",
          "items": [
            {
              "type": "ActionSet",
              "actions": [
                {
                  "type": "Action.Submit",
                  "title": "Triple Extra Large",
                  "associatedInputs": "none",
                  "data": {
                    "msteams": {
                      "type": "messageBack",
                      "displayText": "Triple Extra Large",
                      "text": "Triple Extra Large"
                    }
                  }
                }
              ],
              "horizontalAlignment": "Center"
            }
          ]
        }
      ],
      "horizontalAlignment": "Right"
    }
  ]
}`

In [Designer ](https://adaptivecards.io/designer) it is working as expected.
<img width="845" alt="Screenshot 2021-12-02 at 11 26 29 AM" src="https://user-images.githubusercontent.com/46022906/144366010-35e5b326-57c4-48e2-98af-6042b2f9d28e.png">

Whereas in the teams desktop app, as well as in the online web it is not aligning properly.
<img width="849" alt="Screenshot 2021-12-02 at 11 30 06 AM" src="https://user-images.githubusercontent.com/46022906/144366384-2474e0e8-8004-4e52-a27a-09534c44ba6c.png">

<img width="841" alt="Screenshot 2021-12-02 at 11 27 59 AM" src="https://user-images.githubusercontent.com/46022906/144366150-ecb77a91-c74d-49b6-a788-8da113f31b1b.png">

**Comment by Meghana-MSFT** [comment]
We are looking into this. We will update you.

**Comment by Meghana-MSFT** [comment]
We have a bug raised for this already. We will let you know if there is any update.

**Comment by Chang025** [comment]
@Meghana-MSFT - Thank you for providing an update.

**Comment by Prasad-MSFT** [comment]
The issue seems to be caused by the AdaptiveCard SDK while converting it HTML. Issue will be resolved once the AdaptiveCard SDK version used is updated. Currently there is no ETA to share for the fix.
