### ISSUE TITLE
[Rendering] The size of `Image` is wrong when `selectAction` is specified

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#4770]
Copied bug from: https://github.com/microsoft/AdaptiveCards/issues/6796 

**Details from original post:**
### Target Application

Microsoft Teams

### Application Operating System

Windows

### Schema Version

1.3

### Problem Description

On Microsoft Teams for Windows and Microsoft Teams for Web, when `selectAction` is specified, the `Image` is rendered as a tiny image.

When I check the rendered HTML, I found that the `<img>` is wrapped by a `<button>` in that scenario.

This bug was introduce recently. As of Nov. 15, these image looks fine.

### Expected Outcome

The `Image` should have a consistent size, whether the `selectAction` is set or not.

For test case 1, when the `selectAction` isn't set, it is displayed as:
![image](https://user-images.githubusercontent.com/26323729/144005277-74c3a2d5-5aac-4959-ab12-dab9f1a3f50a.png)
```HTML
<div
    style="display: flex; align-items: flex-start; justify-content: flex-start; box-sizing: border-box; flex: 0 0 auto; padding: 0px; cursor: pointer;">
    <img aria-hidden="true" class="ui-image aq gh uy xs xt" alt=""
        src="https://urlp.asm.skype.com/v1/url/content?url=https%3a%2f%2fadaptivecards.io%2fcontent%2fcats%2f1.png"
        style="min-width: 0px; max-width: 100%; max-height: 100%;"></div>
```

For test case 2, when the `selectAction` isn't set, it is displayed as:
![image](https://user-images.githubusercontent.com/26323729/144001700-551590df-76a9-4610-85a8-7e37e24c78f1.png)
```HTML
<div
    style="display: flex; align-items: flex-start; justify-content: flex-start; box-sizing: border-box; flex: 0 0 auto; padding: 0px; cursor: pointer;">
    <img aria-hidden="true" class="ui-image aq gh uy xs xt" alt=""
        src="https://urlp.asm.skype.com/v1/url/content?url=https%3a%2f%2fadaptivecards.io%2fcontent%2fcats%2f1.png"
        style="min-width: 0px; width: 100px; height: 100px;"></div>
```

### Actual Outcome

When `selectAction` is set, the image size is wrong.

For test case 1, the card is:
![image](https://user-images.githubusercontent.com/26323729/144001617-ccb1638c-b31e-40c9-bed3-ad1a4546e8c3.png)
Its HTML is 
```HTML
<div
    style="display: flex; align-items: flex-start; justify-content: flex-start; box-sizing: border-box; flex: 0 0 auto; padding: 0px; cursor: pointer;">
    <button
        class="ui-button uz vi vk awn xj auz vl br bs av eq fg es qa uy vm vn tg xk xl xm xn xo xp vt vu awr vw xq xr gl gm gn go gp gq gr gs gt gu gv gw aws gy gz ha hb hc hd he hf hg wg wh wi wj hl hm hn ho hp hq hr awt ht hu hv hw hx hy hz ia ib wl wm wn wo wy">
        <div class="ui-box vl bs br ug uh"><img aria-hidden="true" class="ui-image aq gh uy xs" alt=""
                src="https://urlp.asm.skype.com/v1/url/content?url=https%3a%2f%2fadaptivecards.io%2fcontent%2fcats%2f1.png"
                style="min-width: 0px; max-width: 100%; max-height: 100%;"></div>
    </button></div>
```
For test case 2, the card is:
![image](https://user-images.githubusercontent.com/26323729/144001632-d4fcfbaf-262b-4690-b838-1bfb9eef0d63.png)
Its HTML is 
```HTML
<div
    style="display: flex; align-items: flex-start; justify-content: flex-start; box-sizing: border-box; flex: 0 0 auto; padding: 0px; cursor: pointer;">
    <button
        class="ui-button uz vi vk awn xj auz vl br bs av eq fg es qa uy vm vn tg xk xl xm xn xo xp vt vu awr vw xq xr gl gm gn go gp gq gr gs gt gu gv gw aws gy gz ha hb hc hd he hf hg wg wh wi wj hl hm hn ho hp hq hr awt ht hu hv hw hx hy hz ia ib wl wm wn wo wy">
        <div class="ui-box vl bs br ug uh"><img aria-hidden="true" class="ui-image aq gh uy xs" alt=""
                src="https://urlp.asm.skype.com/v1/url/content?url=https%3a%2f%2fadaptivecards.io%2fcontent%2fcats%2f1.png"
                style="min-width: 0px; width: 100px; height: 100px;"></div>
    </button></div>
```

### Card JSON

```JSON
// test case 1, wrong size
{
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "type": "AdaptiveCard",
  "version": "1.3",
  "body": [
    {
      "type": "Image",
      "url": "https://adaptivecards.io/content/cats/1.png",
      "selectAction": {
        "type": "Action.OpenUrl",
        "url": "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
      }
    }
  ]
}
// test case 1, expected size
{
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "type": "AdaptiveCard",
  "version": "1.3",
  "body": [
    {
      "type": "Image",
      "url": "https://adaptivecards.io/content/cats/1.png"
    }
  ]
}
// test case 2, wrong size
{
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "type": "AdaptiveCard",
  "version": "1.3",
  "body": [
    {
      "type": "Image",
      "url": "https://adaptivecards.io/content/cats/1.png",
      "width": "100px",
      "height": "100px",
      "selectAction": {
        "type": "Action.OpenUrl",
        "url": "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
      }
    }
  ]
}
// test case 2, expected size
{
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "type": "AdaptiveCard",
  "version": "1.3",
  "body": [
    {
      "type": "Image",
      "url": "https://adaptivecards.io/content/cats/1.png",
      "width": "100px",
      "height": "100px"
    }
  ]
}
```

### Repro Steps

Push the above cards in Microsoft Teams, and you will find this bug in Microsoft Teams for Windows and Microsoft Teams for Web.---
#### Document Details

⚠ *Do not edit this section.It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Cards reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **surbhigupta12**

**Comment by sayali-MSFT** [comment]
@eggry  - We are looking into this I will get back to you soon.

**Comment by sayali-MSFT** [comment]
@eggry - We have tried the JSON provided by you and it's working for us in Teams Desktop client and  web as well.
Desktop Teams client UI:
![Screenshot 2021-12-03 125057](https://user-images.githubusercontent.com/93527375/144562871-8bb80a35-f75a-4a3c-a76d-4955290c10ad.png)
![Screenshot 2021-12-03 125130](https://user-images.githubusercontent.com/93527375/144562901-0bda5abb-ceb1-4669-b71f-d4a5a0619c35.png)

I have checked it in Teams desktop client version: Microsoft Teams Version 1.4.00.29469 (64-bit)

Could you please try updating it and check it once.

Note: I have tested it in App Studio.

**Comment by eggry** [comment]
Hello, @sayali-MSFT.
Unfortunately, my client still get wrong results.

My desktop client is 1.4.00.32721 (64-bit)-E on Windows 10 21H2. It says `You have Microsoft Teams Version 1.4.00.32721 (64-bit)-E. It was last updated on 12/3/2021.` And I don't get any updates when I check it manually.
![image](https://user-images.githubusercontent.com/26323729/144565988-6d4d9de2-447f-4b8e-8736-25cff18dc9b8.png)

I couldn't check the version of my Web client, but I do cleared all the site data. My browser is Chromium Edge `Version 96.0.1054.41 (Official build) (64-bit)`
![image](https://user-images.githubusercontent.com/26323729/144567470-16abb5b2-a593-4c4d-ab28-0c35aa8aa56f.png)

BTW, thanks for your note. App Studio is very convenient to push test cards :)

**Comment by adamist521** [comment]
Getting same issue here 😢

**Comment by sayali-MSFT** [comment]
@adamist521 -  We are able to repro this issue with the other version , We have raised bug for the same and concerned team is looking into it. We will inform you once we get any update.

**Comment by adamist521** [comment]
@sayali-MSFT 
Already 15 days past... Would this issue be fixed? Is it on the bug list?
Waiting for any updates.
Thanks

**Comment by eggry** [comment]
@adamist521 The cards team said that this bug was fixed, but was not widely avaliable. It may be avaliable to everyone after the New Year. If you need that fix urgently, try to reach them with the affected tenantID.

**Comment by sayali-MSFT** [comment]
@adamist521 - The bug is fixed and will get rolled out publicly real soon

**Comment by adamist521** [comment]
@eggry @sayali-MSFT 
Thanks! Would be nice if you could tell me when it's publicly available!
(Due to that we needs to fix several code and wording on AC...)

**Comment by sayali-MSFT** [comment]
@adamist521 - . It may be available to everyone after the New Year. did not get any particular date confirmation.
 We will inform you once we get any update.

**Comment by sayali-MSFT** [comment]
@adamist521 - The fix is released publicly. Could you please check it once?
Let us know if you have any query.

**Comment by eggry** [comment]
@sayali-MSFT The fix worked for me now, both for PC and Web.
However, for Teams for Web, the fix won't take effect until I clear the browser cache manually.

**Comment by v-chetsh** [comment]
@eggry - Shall we close the issue or do you have any other query related to it?

**Comment by v-chetsh** [comment]
> @sayali-MSFT The fix worked for me now, both for PC and Web. However, for Teams for Web, the fix won't take effect until I clear the browser cache manually.

Hello @eggry - We have tried it but it's working fine at our end.
Could you please confirm once from your end?

**Comment by v-chetsh** [comment]
@eggry - Thanks a lot for confirmation.
We are closing this issue for now, Please feel free to reopen it, if required.
