### ISSUE TITLE
[MS-Teams][Card Area] Max height for a card with scroller enabled

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#4771]
Copied bug from: https://github.com/microsoft/AdaptiveCards/issues/3803 

**Details from original post:**
**What platform is your feature request related to? (Delete other platforms).**

* MS Teams

**Is your feature request related to a problem? Please describe.**
Currently there is no way to set max height of a card or a container, due to which if there is a long list of data then this stretches for pages. Instead a scroller is preferable

**Describe the solution you'd like**
A property like minHeight , maybe maxHeight where we can declare the max height of the card, which comes with scroller when the height of the card exceeds the maxHeight.
---
#### Document Details

⚠ *Do not edit this section.It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Cards reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **surbhigupta12**

**Comment by Nivedipa-MSFT** [comment]
Could you please raise an user voice here:

 https://microsoftteams.uservoice.com/forums/555103-public/filters/new

**Comment by v-chetsh** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.
