### ISSUE TITLE
[Teams][TextBlock] Dates in TextBlock are not localized when Teams is in a different language

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#4772]
Copied bug from: https://github.com/microsoft/AdaptiveCards/issues/3801 

**Details from original post:**
**What platform is your feature request related to? (Delete other platforms).**

* JavaScript

**Is your feature request related to a problem? Please describe.**
The provided date format for TextBlock does not localize to the language of Teams Client - it simply localizes to the local region of the user - i.e. specifically for me, it would only display dates in US format. For instance, consider this section of a sample JSON card payload:

`{
                                            "type": "TextBlock",
                                            "size": "small",
                                            "height": "auto",
                                            "weight": "lighter",
                                            "horizontalAlignment": "right",
                                            "text": "**{{DATE(2019-12-17T15:12:00Z)}}**"
}`

The date renders correctly when the language of the Teams Client is in English, but doesn't render in the localized format when the language is switched to another one - for instance, in many European languages, the month and the day are flipped.  

**Describe the solution you'd like**
It would be great for the SDK to support functionality for Teams to be able to inject its own logic to localize dates to the language of that the Teams client of a specific user. ---
#### Document Details

⚠ *Do not edit this section.It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Cards reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **surbhigupta12**

**Comment by Meghana-MSFT** [comment]
We are looking into this issue. We will update you.

**Comment by Meghana-MSFT** [comment]
@susanshen96 - We tried switching to 4 different languages and we do not see any difference in the way card is displayed. Could you please help us in repro'ing this issue so that we can check it and provide the feedback.

We checked in English, French, Russian, Mexican. We see the below card in all cases.
![image](https://user-images.githubusercontent.com/81138249/144584679-2812e379-9919-4ddc-adb1-1f8bdcfb64a8.png)
