### ISSUE TITLE
[MsTeams]Input.Number is not allowing more than 10 numbers

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#4773]
Copied bug from: https://github.com/microsoft/AdaptiveCards/issues/3957 

**Details from original post:**
# Platform

* .NetCore
* BotFramework V4
# Host
*  MS Teams

Hi All,

I am using Input.Number property to collect the phone number from the user. If the user enters the wrong number then I am pre-populating the same Adaptive card filling the number entered by the user.

If the value of number is more than 10 digits, input.number property is not allowing that number.

Please have a look at the Json:-

` {"type":"AdaptiveCard","version":"1.0","body":[{"type":"TextBlock","text":"My mobile number"},{"type":"Input.Number","placeholder":"","value":"**962213213213213**","id":"asdas"}],"$schema":"http://adaptivecards.io/schemas/adaptive-card.json"}`

This is the error message from Teams App studio:-
<img width="358" alt="InputNumber" src="https://user-images.githubusercontent.com/49824279/80270486-41021400-86d6-11ea-8d72-299421876a08.PNG">

Please help.

Thanks.

 
---
#### Document Details

⚠ *Do not edit this section.It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Cards reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **surbhigupta12**

**Comment by sayali-MSFT** [comment]
@Chekrii - We are looking into this I will get back to you soon.

**Comment by v-chetsh** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.
