### ISSUE TITLE
Adaptive Card and webhook connector (When?)

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#4774]
Copied bug from: https://github.com/microsoft/AdaptiveCards/issues/3907 

**Details from original post:**
**What platform is your feature request related to? (Delete other platforms).**
Provide Adaptive card support to webhook connectors

**Is your feature request related to a problem? Please describe.**
We need webhook to support ActionCard(s). There are so many businesses that need them so badly.
https://microsoftteams.uservoice.com/forums/555103-public/suggestions/35793883-adaptive-cards-webhooks?page=1&per_page=20

**Describe the solution you'd like**
I would like to be able to write Adaptive Cards and POST them to the right channel(s)

**Describe alternatives you've considered**
Changing chat system

**Additional context**
If you see the answer of Bill Bliss it says that it was planned already in 2018. 
https://stackoverflow.com/questions/50753072/microsoft-teams-webhook-generating-400-for-adaptive-card/50753413#50753413

Many companies have a chatbot infrastructure that is easily integrable with webhook-like solutions.  These companies would rather change chat systems than migrate everything towards bot-framework like solution, that is very peculiar---
#### Document Details

⚠ *Do not edit this section.It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Cards reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **surbhigupta12**

**Comment by Nivedipa-MSFT** [comment]
Could you please raise an user voice here:

 https://microsoftteams.uservoice.com/forums/555103-public/filters/new

**Comment by v-chetsh** [comment]
@sgiulianiamius - This feature is not available currently.
Could you please raise an user voice here:
https://microsoftteams.uservoice.com/forums/555103-public/filters/new

Suggested approach is to leverage Power Automate to create these cards.

**Comment by v-chetsh** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.
