### ISSUE TITLE
Action open.Url to message in Teams goes to wrong channel

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#4775]
Copied bug from: https://github.com/microsoft/AdaptiveCards/issues/3338 

**Details from original post:**
# Platform
Microsoft Flow Action - Post an adaptive card to user as Flow Bot

# Author or host
I am adding the JSON for the adaptive card to the flow action to post the message

If you're an author, who are you sending cards to?
The Adaptive Card is sent as a personal message to a specified user in the Flow Action

# Issue
The Flow I created is triggered by a new message in a Team Channel (not the General channel).  The web url of the message is parsed out of the trigger JSON.  
A message alerting a user about the post is sent to the user with the Post an adaptive card to user as Flow Bot.  In the JSON, there is a text block that gives the URL:
```
  {
            "type": "TextBlock",
             "text": "[View Message](@{body('Parse_JSON')?['webUrl']})"
   }

```
I also added an action to open the message url:
```
    "actions": [
        {
            "type": "Action.OpenUrl",
            "title": "View message in channel",
            "url": "@{body('Parse_JSON')?['webUrl']}"
        }

```
The message gets posted successfully in Teams:

<img width="349" alt="AdaptiveCardMessage" src="https://user-images.githubusercontent.com/7673459/63120326-18832100-bf70-11e9-961e-20930952170e.png">

If I click on the "View Message" URL - it tries to open it in a browser which then sends the user back to Teams to the message from the URL.

If I click the "View message in channel" action, the user stays in Teams, but is redirected to the message Team's General channel and most recent message - **not** to the message associated with the URL.

Ideally, I should get a combination of the two behaviors - stay in Teams and go to the right channel/message.  If that is not possible, then the Action Open.URL should be the same as clicking the message URL so that the user ends up at the right place.
---
#### Document Details

⚠ *Do not edit this section.It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Cards reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **surbhigupta12**

**Comment by Meghana-MSFT** [comment]
We are looking into this issue. We will update you.

**Comment by Meghana-MSFT** [comment]
We tried this at our end. We gave a URL of a message in channel to view message text and View message in channel action.  We see in both the cases it is going to correct message. Could you please  share your flow zip package so that we can repro it at our end and provide further feedback.

Note : View message text open a tab in browser.

**Comment by v-chetsh** [comment]
Could you please share your flow zip package so that we can repro it at our end and provide further feedback?

**Comment by Meghana-MSFT** [comment]
We are closing this issue due to user inactivity. Please feel free to re open if the issue still exists.
