### ISSUE TITLE
[Adaptive Expressions][Adaptive Expressions Date prebuilt function][Given a UTC DateTime, formatDateTime does not convert correctly in user timezone]

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#4776]
Copied bug from: https://github.com/microsoft/AdaptiveCards/issues/4903 

**Details from original post:**
[MS Teams][Desktop/Mobile App]
[Adaptive Cards 1.2]

# Platform
*.Net

# Version of SDK
*AdaptiveCards 2.1.0
*AdaptiveCards.Templating 1.1.0
*AdaptiveExpressions 4.10.3
*Microsoft.Bot.Builder 4.10.3

# Details
Using formatDateTime does not display the correct date equivalent in user timezone.

Given this in template:
```
{
      "type": "Input.Date",
      "id": "date",
       "value": "${formatDateTime('2020-11-30T21:00:00Z', 'yyyy-MM-dd')}"
}
```

The datepicker value in GMT+8 renders **11/30/2020** instead of **12/01/2020** in either desktop/mobile MS Teams app
![image](https://user-images.githubusercontent.com/72416404/95599861-38cf4280-0a84-11eb-84ad-a054ee3e09e0.png)

It renders properly when tried on designer though
![image](https://user-images.githubusercontent.com/72416404/95602526-a29d1b80-0a87-11eb-9215-bb8202061aaf.png)
---
#### Document Details

⚠ *Do not edit this section.It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Cards reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **surbhigupta12**

**Comment by sayali-MSFT** [comment]
@ccdev1205 - We are looking into this I will get back to you soon.

**Comment by sayali-MSFT** [comment]
@ccdev1205 -  formatDateTime function return the timestamp for the given locale.
Can you try the below for formatting ?
{{DATE(${string(dueDate)}, COMPACT)}}
where date Input is "dueDate": "2021-12-03T21:00:00Z"

For more adaptive card sample:-
Please have a look at this doc- https://adaptivecards.io/samples/
Let us know if you have any query.

**Comment by sayali-MSFT** [comment]
@ccdev1205 - Could you please confirm if your issue has resolved or still looking for any help?

**Comment by ccdev1205** [comment]
Hi, 
Sorry for the late response. Yes the issue has been resolved. 
Thanks, 
Christine 
 
  On Mon, 6 Dec 2021 at 1:54 pm, ***@***.***> wrote:   


@ccdev1205 - Could you please confirm if your issue has resolved or still looking for any help?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by v-chetsh** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.
