### ISSUE TITLE
Please document details of response to GetMeetingDetails

### ISSUE THREAD

**Issue by aosolis** [MicrosoftDocs/msteams-docs#4778]
For example:
- What are the possible values of meeting.type
- What is the ID in msGraphResourceId-- which Graph APIs can this ID be used for?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 805dc242-7b5a-cc81-ee0e-6acf0078a653
* Version Independent ID: 11c0e023-2514-9639-6052-2cbbbef50663
* Content: [Meeting apps API references - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/api-references?tabs=dotnet#shareappcontenttostage-api)
* Content Source: [msteams-platform/apps-in-teams-meetings/API-references.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/apps-in-teams-meetings/API-references.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by sayali-MSFT** [comment]
@aosolis  - We are looking into this I will get back to you soon.

**Comment by sayali-MSFT** [comment]
@aosolis  - Please have a look at this doc- https://docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-1.0&tabs=http
https://docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-1.0

Let us know if you have any query.

**Comment by sayali-MSFT** [comment]
@aosolis - Could you please confirm if your issue has resolved with above suggestion or still looking for any help?

**Comment by aosolis** [comment]
Thanks for the pointer!
Please update the documentation to make this clear. 
Also, how does one get the ID of the corresponding calendar event?

**Comment by sayali-MSFT** [comment]
@aosolis - for Getting id of calendar  event use the following Graph API:-
1.GET /me/calendar/events  

 Please have a look at this doc-https://docs.microsoft.com/en-us/graph/api/user-list-events?view=graph-rest-1.0&tabs=http

**Comment by sayali-MSFT** [comment]
@aosolis - Could you please confirm if your issue has resolved with above suggestion or still looking for any help?

**Comment by v-chetsh** [comment]
@aosolis - We will check as per suggestions and ask doc team to update it accordingly.

**Comment by sayali-MSFT** [comment]
@aosolis - The possible values of meeting type is "Private Meeting , Channel Meeting".
https://docs.microsoft.com/en-us/MicrosoftTeams/tutorial-meetings-in-teams?tutorial-step=2

for the msGraphResourceId-  we are check it internally ,we will inform you once we get any update.

Will raise a bug to Document Team for the necessary changes to be made in the document.

**Comment by surbhigupta12** [comment]
@v-abirade, please look into this.

**Comment by v-abirade** [comment]
@surbhigupta12 , I will update the doc and keep you posted.
