### ISSUE TITLE
Mention open source tools available to send adaptive notifications

### ISSUE THREAD

**Issue by antoniordz96** [MicrosoftDocs/msteams-docs#4779]
Hey! Recently I had a use case for sending adaptive card messages to a teams channel. They are great but we needed a better solution for replacing values in the adaptive card template (client-side). I leveraged the Microsoft Adaptive Templating SDK to build this tool. Wonder if we could have a section in the documentation regarding open source tools built for sending notifcations? 

ms-notify: https://github.com/antoniordz96/ms-teams-adaptive-notifications 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28316a67-22fa-8a05-1ae0-fbe1c5720ef9
* Version Independent ID: 8a250e46-2a30-af86-839d-9f83a8b48041
* Content: [Create and send messages - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-using?tabs=cURL)
* Content Source: [msteams-platform/webhooks-and-connectors/how-to/connectors-using.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/webhooks-and-connectors/how-to/connectors-using.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by surbhigupta12** [comment]
Hi @antoniordz96,

For now open source details will be outside of Teams documentation and ideally, we suggest communicating this via StackOverflow and/or Github issues as a workaround for future users to leverage.

Hence we are closing this issue.
