### ISSUE TITLE
Get the topic of the post

### ISSUE THREAD

**Issue by luserwu** [MicrosoftDocs/msteams-docs#4787]
The message in the Activity cannot get the topic of the post. Is this a prerequisite behavior for the robot?How can I get the theme?

**Comment by sayali-MSFT** [comment]
@luserwu - Could you please elaborate on your requirement and share the repro steps.

**Comment by luserwu** [comment]
I publish a post with a topic on teams, and I want to get the topic parameters of the post in the robot message activity

**Comment by sayali-MSFT** [comment]
@luserwu - Please have a look at this doc- https://docs.microsoft.com/en-us/power-virtual-agents/teams/authoring-create-edit-topics-teams
Let us know if you have any query.

**Comment by luserwu** [comment]
> @luserwu - Please have a look at this doc- https://docs.microsoft.com/en-us/power-virtual-agents/teams/authoring-create-edit-topics-teams Let us know if you have any query.

![image](https://user-images.githubusercontent.com/34673072/145023225-08e7a93e-fa45-4c19-bc98-926c1530df40.png)
I want to get this parameter in the message activity，Instead of the document you posted.

**Comment by sayali-MSFT** [comment]
@luserwu - if you want to get message subject from chat.you can use Graph API.you have to mention chat id and message id in graph API then you will get the all information related to message.
Get message in a chat:-
GET /chats/{chat-id}/messages/{message-id}
GET /users/{user-id | user-principal-name}/chats/{chat-id}/messages/{message-id}
GET /me/chats/{chat-id}/messages/{message-id}

Ref Doc - https://docs.microsoft.com/en-us/graph/api/chatmessage-get?view=graph-rest-1.0&tabs=http

**Comment by sayali-MSFT** [comment]
@luserwu - Could you please confirm if your issue has resolved with above suggestion or still looking for any help?

**Comment by luserwu** [comment]
Thanks, no need help anymore.

**Comment by v-chetsh** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.
