### ISSUE TITLE
No Examples available for personal apps

### ISSUE THREAD

**Issue by AnthonyPhan** [MicrosoftDocs/msteams-docs#4789]
Hi,

I have read though the documentation and also looked through the VS Code Plugin examples on creating Teams Apps and I am unable to find an example of Personal Apps.
There are plenty of examples of Tab, bots and messaging apps but not personal apps. Is there a reason for this? e.g. Personal apps are some how the same as tab apps?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f57a31a0-e815-faa4-653d-795ae8a8e4d7
* Version Independent ID: 8f48ea3d-231b-2776-41b7-11890ea2d3c0
* Content: [Build apps for the Microsoft Teams platform - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/overview)
* Content Source: [msteams-platform/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/overview.md)
* Product: **msteams**
* GitHub Login: @heath-hamilton
* Microsoft Alias: **lajanuar**

**Comment by v-chetsh** [comment]
@AnthonyPhan - A personal app can be a bot, or tab depending on our requirement.
Personal apps can include a bot for one-on-one conversations and private notifications (for instance, when a colleague posts a comment on artboard). Users interact with the bot in a tab you specify.

Reference link:
https://docs.microsoft.com/en-us/microsoftteams/platform/bots/what-are-bots

Create a personal tab:
https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?tabs=nodejs#create-a-custom-personal-tab

**Comment by v-chetsh** [comment]
@AnthonyPhan - Please let us know if you need any help or shall we close this issue?

**Comment by AnthonyPhan** [comment]
@v-chetsh  thank you for the response. After some time I manged to find this repo provided by Microsoft containing the examples I was expecting. The repo contains far more useful examples that what is available in the Tema VS Code plugin.

https://github.com/OfficeDev/Microsoft-Teams-Samples
