### ISSUE TITLE
Example of retrieving audio from an MS Teams meeting or 1:1

### ISSUE THREAD

**Issue by jiminygreen** [MicrosoftDocs/msteams-docs#4790]
I'm looking to build an app the analyses in real-time what a person is saying on a MS Teams call and returns those insights to the caller. I haven't been able to find an example of how you get access to the audio. Is there an example that shows this?

**Comment by v-chetsh** [comment]
Hello @jiminygreen - We are checking on it internally and let you know.

**Comment by v-chetsh** [comment]
@jiminygreen - Looks like currently we do not have any Graph API to get the real time audio of a Teams meeting or 1:1 call.

**Comment by v-chetsh** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.
