### ISSUE TITLE
Image for title of azure boards bot having info is not keyboard accessible. 

### ISSUE THREAD

**Issue by MayurMundekar** [MicrosoftDocs/msteams-docs#4791]
In Azure Board bot, If user mouseover of Azure Board Icon it show the information but if try to access same thing using keyboard tab access it is not working. Please find the attachment.

**Image 1:- Information showing using mouse hover**
<img width="813" alt="image" src="https://user-images.githubusercontent.com/83640993/144815986-fa5461d3-ec5f-4fdf-b1f0-91022809897b.png">
**Image 2:- Keyboard Tab access is not going to image**
<img width="625" alt="image" src="https://user-images.githubusercontent.com/83640993/144817361-d9ddc84c-9146-47d7-8f21-f43cc4a3637c.png">

**Environment Details:**
Application Name: AzDev-azchatops
#URL: https://teams.microsoft.com/
Windows Version: Win10 
ChromiumEdge Version: 94.0.992.38

**Repro Steps:**

1. Hit the URL "https://teams.microsoft.com".
2. Tab till "Sign in" and login with your teams credentials.
3. Tab to the apps.
4. Download "Azure Boards" app in your project. If already installed skip the step (Download path : Tab till "Team menu" button --> Apps --> then search for Azure Boards and install the app).
5. Tab to teams.
6. Navigate till your project name under "Channels" and press enter.
7. Tab till "Message text field" and type the command "/azboards sign in" and press enter.
8. Tab to each element on reply window.

**Actual:**
When tried to access each element , the keyboard access does not go to the "image of title azure boards" which has information related to it. 

**Expected:**
The image of azure boards accessed through the keyboard.

**User Impact:**
The users can not able to access the information provided with the image.

**Comment by v-chetsh** [comment]
@MayurMundekar - Looks like this issue is not related to Microsoft Teams app development.

For Microsoft Teams product issues/failures your tenant Admin can reach out to [Microsoft 365 Product Support](https://docs.microsoft.com/en-us/microsoft-365/admin/contact-support-for-business-products?view=o365-worldwide&tabs=online). 
For general questions about Microsoft Teams please post your question on [Microsoft Teams Community](https://answers.microsoft.com/en-us/msteams/forum).

**Comment by v-chetsh** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.

**Comment by MayurMundekar** [comment]
Hi @v-chetsh , can you re-open the issue and add tag "product-team-support" because I am not able to resopen.

**Comment by v-chetsh** [comment]
@MayurMundekar - Could you please raise a request here:
For Microsoft Teams product issues/failures your tenant Admin can reach out to [Microsoft 365 Product Support](https://docs.microsoft.com/en-us/microsoft-365/admin/contact-support-for-business-products?view=o365-worldwide&tabs=online). 
For general questions about Microsoft Teams please post your question on [Microsoft Teams Community](https://answers.microsoft.com/en-us/msteams/forum).

**Comment by MayurMundekar** [comment]
ok @v-chetsh , Thanks for the update
