### ISSUE TITLE
After zoom to 200% left side navigation panel get hidden.

### ISSUE THREAD

**Issue by MayurMundekar** [MicrosoftDocs/msteams-docs#4793]
Please find the attachment

![1883090_A11y_AzDev-azchatops_SignIn_Resize](https://user-images.githubusercontent.com/83640993/144822133-9ddd0e94-5272-4276-9802-550c0f74f569.png)

**Repro Steps:**

1. Hit the URL "https://teams.microsoft.com".
2. Tab till "Sign in" and login with your teams credentials.
3. Tab to the apps.
4. Download "Azure Boards" app in your project. If already installed skip the step (Download path : Tab till "Team menu" button --> Apps --> then search for Azure Boards and install the app).
5. Tab to teams.
6. Navigate till your project name under "Channels" and press enter.
7. Resize or apply 200% zoom.
8. Tab to each element. 

**Actual:**
When resized or zoomed  to 200% the channel navigation panel at left side get hidden. 

**Expected:**
When zoomed to 200% the channel navigation panel should be visible.

**User Impact:**
The users may not able to find channel navigation and do not able to navigate to another channel.

**Comment by Meghana-MSFT** [comment]
This team can only help with questions related to [building apps for the Microsoft Teams platform](https://docs.microsoft.com/en-us/microsoftteams/platform/overview). So adding Teams product tag.
