### ISSUE TITLE
In MSTeam, For Azure Board bot Sign-in with different account tab is not accessible via keyboard. 

### ISSUE THREAD

**Issue by MayurMundekar** [MicrosoftDocs/msteams-docs#4794]
**Repro Steps:**
1. Hit the URL "https://teams.microsoft.com".
2. Tab till "Sign in" and login with your teams credentials.
3. Tab to the apps.
4. Download "Azure Boards" app in your project. If already installed skip the step (Download path : Tab till "Team menu" button --> Apps --> then search for Azure Boards and install the app).
5. Tab to teams.
6. Navigate till your project name under "Channels" and press enter.
7. Tab till "Message text field" and type the command "@azure boards Signin" and press enter.
8. Sign-in pop up get displayed. 

**Actual:**
When pop-up for sign in displays it has tab for "sign-in with different account", but via tab it is not accessible. 

Note : 
 This same issue is observed in scenarios of azure repos and azure pipelines.

**Expected:**
In pop-up for sign, the "sign-in with different account",  should be keyboard accessible. 

**User Impact:**
The keyboard users may not able to sign-in with different account to the application .

Please find the attachment
![Signin Tab Issue](https://user-images.githubusercontent.com/83640993/144824435-49c2e920-1c0e-4cab-af12-e4b2a51e3242.gif)

**Comment by sayali-MSFT** [comment]
@MayurMundekar - We are looking into this I will get back to you soon.

**Comment by HunaidHanfee-MSFT** [comment]
We have the repro. We need to confirm this behavior with the concerned team. I will get back to you if I have any updates.

Thanks

**Comment by MayurMundekar** [comment]
Appreciate the updates , Thanks @HunaidHanfee-MSFT

**Comment by HunaidHanfee-MSFT** [comment]
We have the repro but this is not under our scope so I am assigning it to the Teams Product support team.

Thanks for understanding.
