### ISSUE TITLE
I'm unable inspect teams mobile client

### ISSUE THREAD

**Issue by Niegrozny** [MicrosoftDocs/msteams-docs#4795]
I've enabled developer preview, and connected my phone with the remote debugging enabled.
I can inspect mobile chrome browser tabs, but the com.microsoft.skype.teams.dev (Teams/1416/1.0.84.0) doesn't show up.
I'm using SM-G781B

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3df1efbb-c6b2-a495-303d-7abf19c57f72
* Version Independent ID: a5b5782f-7031-a989-5e42-dd3010e18893
* Content: [DevTools for Microsoft Teams tabs - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/developer-tools#accessing-devtools-from-an-android-client)
* Content Source: [msteams-platform/tabs/how-to/developer-tools.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tabs/how-to/developer-tools.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by sayali-MSFT** [comment]
@Niegrozny - We are looking into this I will get back to you soon.

**Comment by HunaidHanfee-MSFT** [comment]
In order debug Teams tab, you need to first open a tab in your Teams mobile client then only it will show you.
![image](https://user-images.githubusercontent.com/64194049/145529883-c28dea78-e852-4cd7-b90d-83cf07a2992a.png)

Could you please try it once and confirm?
Thanks

**Comment by HunaidHanfee-MSFT** [comment]
@Niegrozny - Did you get a chance to check and confirm?

**Comment by Niegrozny** [comment]
@HunaidHanfee-MSFT Yes, that was it! Thanks!

**Comment by HunaidHanfee-MSFT** [comment]
There's clear instruction given in this - [remote debugging](https://developer.chrome.com/docs/devtools/remote-debugging/) Are you facing issue in any of the step?

**Comment by v-chetsh** [comment]
@Niegrozny - Could you please confirm if your issue has resolved with above suggestion or still looking for any help?

**Comment by Niegrozny** [comment]
The original issue is resolved. I was looking for a way serve teams SPFx app from localhost and to debug it on mobile, but I found a solution.

**Comment by HunaidHanfee-MSFT** [comment]
@Niegrozny  we are closing this issue. Please feel free re-open this issue and let us know if you have any query.

Thanks
