### ISSUE TITLE
Can't paste image to chat or channel

### ISSUE THREAD

**Issue by agileelement** [MicrosoftDocs/msteams-docs#480]
If I copy an image to the clipboard, ctrl+v or right click paste does nothing in Teams. I have confirmed the image is in the clipboard as I can paste it elsewhere, office...slack...  If I copy the image from Word, it will paste.

**Comment by billbliss** [comment]
We hope to fix these clipboard problems in the next few months. It's irritating to us too.

**Comment by Wajeed-msft** [comment]
We are tracking this issue internally. Closing this from documentation issues.
