### ISSUE TITLE
After zoom to 200% left side navigation panel get hidden.

### ISSUE THREAD

**Issue by MayurMundekar** [MicrosoftDocs/msteams-docs#4802]
Please find detailed information here #4793

**Comment by Prasad-MSFT** [comment]
@MayurMundekar - We are mainly responsible for Microsoft Teams app development related issues. Your issue seems more of product related. So redirecting you to MS Teams Product support Team to help further. Thanks for understanding.

**Comment by MayurMundekar** [comment]
Hi @Prasad-MSFT , Thanks for moving the ticket but can you re-open the issue as it is closed by bot.

**Comment by Prasad-MSFT** [comment]
@MayurMundekar - Whenever we add Product support tag it get closed and asks you to raise your concern here:
For Microsoft Teams product issues/failures your tenant Admin can reach out to [Microsoft 365 Product Support](https://docs.microsoft.com/en-us/microsoft-365/admin/get-help-support?view=o365-worldwide&tabs=online).
