### ISSUE TITLE
This doc page needs to mention that the Azure Bot resource must have the MsTeams channel enabled.

### ISSUE THREAD

**Issue by kostasvl** [MicrosoftDocs/msteams-docs#4806]
See subject.  It was this particular answer in this issue that helped me: https://github.com/MicrosoftDocs/msteams-docs/issues/3178#, but it took some tracking down. Thanks 👍

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e0acfd2-0965-65f4-2200-ca06424a3976
* Version Independent ID: fd7f72fe-5dba-369a-c436-6140d232ad44
* Content: [Receive all channel messages with RSC - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/channel-messages-with-rsc)
* Content Source: [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md)
* Product: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **lajanuar**

**Comment by v-chetsh** [comment]
@kostasvl - We will check on it and redirect to doc team accordingly.

**Comment by v-chetsh** [comment]
@kostasvl - We are not able to see the Azure Bot related content on the page:
[Azure Bot](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/channel-messages-with-rsc)

Could you please share the content page section where you want to add it?

**Comment by kostasvl** [comment]
Hi @v-chetsh. Hmm, thinking about it some more, this info is probably a better fit for the [readme of the sample app](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/bot-receive-channel-messages-withRSC/csharp), and not the main documentation page that we are discussing here. Devs who are reading the docs may well have an existing Azure Bot which is correctly configured. It's users like me who are trying the sample, and are having to create temporary Azure resources for it, that need this reminder the most. I'll create a separate issue [over there](https://github.com/OfficeDev/Microsoft-Teams-Samples/issues).

Thanks! Feel free to close this.
