### ISSUE TITLE
MsTeams : Issue in Input.Date Component for Adaptive Cards

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#4807]
Copied bug from: https://github.com/microsoft/AdaptiveCards/issues/6816 

**Details from original post:**
# Platform

*  Web (MsTeams Web http://teams.microsoft.com )
* Ms Teams Desktop Client  1.4.00.29478 (Mac OS Big Sur)

# Issue

I have a simple Adaptive card, with a date picker and an action button. When I select a date in date picker and then click on the button, I should be getting the postback date which was selected.

However, when I select a date, and click the action button, i am geting the postback date as (selected date - 1), that is ; **just a day before the actual selected date.**

**Payload used:** 

[payload.txt](https://github.com/microsoft/AdaptiveCards/files/7666723/payload.txt)

My time zone: Indian Standard Time (IST)

I tried in desktop client in my MacOS , version of the app being  1.4.00.29478, issue exists there.

<img width="534" alt="Screenshot 2021-12-07 at 2 01 35 PM" src="https://user-images.githubusercontent.com/69789507/144994193-49097152-f3c5-4c19-b50b-12a571793932.png">

Even though date selected was 29th November 2021, I got the postback as:
{"date":"2021-11-28","action":"clicked"}

I tried in chrome browser , navigating to teams web (teams.microsoft.com ), and again I am able to see the same issue in Date.

Very strangely, issue in teams web client is **not being seen when tested in Firefox  browser** (78.13.0esr) , **although the date  is coming in a different format and appearance of date picker is also different here.**

<img width="567" alt="Screenshot 2021-12-07 at 2 03 15 PM" src="https://user-images.githubusercontent.com/69789507/144994451-8b0f760b-6a79-438b-a0da-f6bec82a8235.png">

Also, the problem is not being seen whe tested in Ms teams Android app (1416/1.0.0.2021183702/1117).

Please help me to know how I can fix this date picker issue, or if this is an ms teams issue .
---
#### Document Details

⚠ *Do not edit this section.It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Cards reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **surbhigupta12**

**Comment by Prasad-MSFT** [comment]
@devtfq - We are able to repro the issue and raised a bug for this. Engineering team is looking into it. We will inform you once we get any update.
 Thanks!

**Comment by devtfq** [comment]
@Prasad-MSFT  Thank you so much for the update.

**Comment by devtfq** [comment]
@Prasad-MSFT , @Wajeed-msft  can we please know if there is any update on this bug ?

**Comment by Prasad-MSFT** [comment]
@devtfq -Engineering team is looking into it. We will inform you once we get any update.

**Comment by prasanthrpadharthi** [comment]
We are also facing the same issue. This is happening for the past 2+ months. Issue happened incrementally started with few users and then now being faced by all the thousands of users using our chatbots. Hoping for a quick resolution.

**Comment by prasanthrpadharthi** [comment]
Just want to highlight that this is not an issue with Adaptive card to my knowledge as the same scenario is working fine when used in MS Teams Mobile APP. 

Issue is happening in Desktop Teams App and web browser Teams version too.

![image](https://user-images.githubusercontent.com/36985649/147950048-8d7df33a-87c0-4702-99f0-bd58e9b94268.png)
![image](https://user-images.githubusercontent.com/36985649/147950079-512a51ac-b910-4770-a0db-1758677d8f37.png)

**Comment by devtfq** [comment]
@v-chetsh  @Prasad-MSFT  it's been almost a month now, can we please kindly get this resolved or could you please help us to escalate this issue ? 

Thanks.

**Comment by v-chetsh** [comment]
@devtfq - We have informed engineering team again.
We will let you know once we get any update from them.

**Comment by devtfq** [comment]
Thank you Chetan for the update..

**Comment by Prasad-MSFT** [comment]
@devtfq - We tested the scenario in `Microsoft Teams Version 1.4.00.35564 (64-bit). It was last updated on 07-01-2022.` and Teams web also and the issue doesn't seem to be persist. Please try to update your MS Teams version and check it once.

**Comment by prasanthrpadharthi** [comment]
Tested myself and checked with few other users as well, working fine now. Thanks much

**Comment by devtfq** [comment]
Thanks a lot @Prasad-MSFT  for the update, I tested it , and it's working perfectly!
Thanks again everyone !

**Comment by Prasad-MSFT** [comment]
Glad to hear that its working fine now. We are closing this issue. Please feel free to reopen if required.
