### ISSUE TITLE
[Teams][Rendering] Markdown formatted text containing images not rendering on Teams

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#4808]
Copied bug from: https://github.com/microsoft/AdaptiveCards/issues/4121 

**Details from original post:**
# Platform

Microsoft Teams

# Version of SDK

1.2

# Details

We have a bot that is sending adaptive card responses on Teams. The bot renders results from QnA Maker answers into a card. The QnA Maker answers are formatted using markdown and some answers contain images. These images are not showing up on Teams, but do show up in the designer and the Bot Emulator.

The issue seems to exist in the [FAQ Plus template](https://github.com/OfficeDev/microsoft-teams-faqplusplus-app) as well.

## QnA Answer (Markdown)

```
Click **Teams**\n\n![Teams button](https://support.content.office.net/en-us/media/20305b5c-df47-4154-a21a-b12712c4224c.png)\n\non the left side of the app, then click **Add team** at the bottom of your teams list. Go to the first tile in the **Suggested teams** view and click **Create a team**. From there, you can invite people or even entire contact groups (aka "distribution lists") to join your team. Now that you have a new team, why not [add some new channels](https://support.office.com/en-us/article/create-a-channel-in-teams-fda0b75e-5b90-4fb8-8857-7e102b014525) for specific conversation topics? Or even [invite guests](https://support.office.com/en-us/article/add-guests-to-a-team-in-teams-fccb4fa6-f864-4508-bdde-256e7384a14f) from outside your organization to help with a project?
```

The content was generated by QnA Maker from the following [Teams FAQ page](https://support.microsoft.com/en-us/office/faq-f4644010-d5fa-4055-b42a-6a5317316e18?ui=en-us&rs=en-us&ad=us)

## JSON

```json
{
    "type": "AdaptiveCard",
    "version": "1.2",
    "body": [
        {
            "type": "TextBlock",
            "size": "Medium",
            "weight": "Bolder",
            "text": "'Click **Teams** ![Teams button](https://support.content.office.net/en-us/media/20305b5c-df47-4154-a21a-b12712c4224c.png) on the left side of the app, then click **Add team** at the bottom of your teams list. Go to the first tile in the **Suggested teams** view and click **Create a team**. From there, you can invite people or even entire contact groups (aka \"distribution lists\") to join your team. Now that you have a new team, why not [add some new channels]([https://support.office.com/en-us/article/create-a-channel-in-teams-fda0b75e-5b90-4fb8-8857-7e102b014525](https://support.office.com/en-us/article/create-a-channel-in-teams-fda0b75e-5b90-4fb8-8857-7e102b014525)) for specific conversation topics? Or even [invite guests]([https://support.office.com/en-us/article/add-guests-to-a-team-in-teams-fccb4fa6-f864-4508-bdde-256e7384a14f](https://support.office.com/en-us/article/add-guests-to-a-team-in-teams-fccb4fa6-f864-4508-bdde-256e7384a14f)) from outside your organization to help with a project?'",
            "wrap": true
        },
        {
            "type": "TextBlock",
            "text": "I think that is the answer (confidence score of 95%)",
            "wrap": true
        }
    ],
    "actions": [
        {
            "type": "Action.Submit",
            "data": {
                "type": "BotHelpful",
                "answer": "Click **Teams** ![Teams button](https://support.content.office.net/en-us/media/20305b5c-df47-4154-a21a-b12712c4224c.png) on the left side of the app, then click **Add team** at the bottom of your teams list. Go to the first tile in the **Suggested teams** view and click **Create a team**. From there, you can invite people or even entire contact groups (aka \"distribution lists\") to join your team. Now that you have a new team, why not [add some new channels](https://support.office.com/en-us/article/create-a-channel-in-teams-fda0b75e-5b90-4fb8-8857-7e102b014525) for specific conversation topics? Or even [invite guests](https://support.office.com/en-us/article/add-guests-to-a-team-in-teams-fccb4fa6-f864-4508-bdde-256e7384a14f) from outside your organization to help with a project?",
                "questionId": 158,
                "qnaId": 104
            },
            "title": "This is helpful"
        },
        {
            "type": "Action.Submit",
            "data": {
                "type": "BotUnhelpful",
                "questionId": 158,
                "qnaId": 0,
                "upn": "user@email.com"
            },
            "title": "Tag Expert"
        }
    ],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json"
}
```

## Web Chat Designer ✅
![image](https://user-images.githubusercontent.com/16281323/83822939-d94bd980-a715-11ea-8a4c-daeb9dc8c24b.png)

## Microsoft Teams Designer ✅
![image](https://user-images.githubusercontent.com/16281323/83823367-35632d80-a717-11ea-93a2-19c5be5885a1.png)

## Microsoft Teams ❌
![image](https://user-images.githubusercontent.com/16281323/83823064-40698e00-a716-11ea-8158-37af0b9b231c.png)

---
#### Document Details

⚠ *Do not edit this section.It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Cards reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **surbhigupta12**

**Comment by Nivedipa-MSFT** [comment]
@YJasonY - We have already raised the bug for this issue. We will update you.

**Comment by v-chetsh** [comment]
@YJasonY - This issue fix is in progress and we will let you know the updates once it is fixed.

**Comment by YJasonY** [comment]
Hi @v-chetsh - just checking if there have been any progress/updates regarding this fix?

**Comment by Nivedipa-MSFT** [comment]
@YJasonY - We have informed Engineering team about the same and they are currently working on the fix. We will inform you once we have further update. Thanks!

**Comment by Prasad-MSFT** [comment]
Hi @YJasonY - We checked with the SDK team. This is not possible in Mobile.
And for Desktop we are checking with engineering team about the fix. We will notify you once we get any update. Thanks!

**Comment by catmanjan** [comment]
Any news on this?

**Comment by Nivedipa-MSFT** [comment]
@catmanjan - We will check the status of the bug with engineering team and update you soon.

**Comment by Nivedipa-MSFT** [comment]
@catmanjan - Engineering team is working on the fix. Currently we don't have any ETA to share. We will keep you posted if there are any updates.

**Comment by Prasad-MSFT** [comment]
@catmanjan - We got update from engineering team that "Currently Markdown images for adaptive card is not supported." Please refer to this doc for the limit set of markdown syntax we support for adaptive card:
https://learn.microsoft.com/en-us/adaptive-cards/authoring-cards/text-features "

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now. Please feel free to reopen if required. Thanks!
