### ISSUE TITLE
[Ms Teams][Adaptive Cards Textbox emojis not working]

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#4809]
Copied bug from: https://github.com/microsoft/AdaptiveCards/issues/4777 

**Details from original post:**
# Platform

What platform is your issue or question related to? (Delete other platforms).
MsTeams

# Author or host
Author

If you're an author, who are you sending cards to?
MsTeams

# Version of SDK
NA

# Details
In Adaptive Cards Textbox, emojis are not working and showing emojis in text format while in Ms Teams , same text is converting into emojis.

: 100 : -> showing plain text and not emoji 💯 
![BugImage](https://user-images.githubusercontent.com/65468026/93201464-dc238500-f76e-11ea-90db-b13c2bc20288.png)

Teams: ":100:" is converting into emojis

![image](https://user-images.githubusercontent.com/65468026/93201620-0ffeaa80-f76f-11ea-9eba-65266dc96bad.png)

---
#### Document Details

⚠ *Do not edit this section.It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Cards reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **surbhigupta12**

**Comment by sayali-MSFT** [comment]
@priyakewlani18 -  Unicode emoji works perfectly well if properly encoded into the JSON. See the image.

![emoji](https://user-images.githubusercontent.com/93527375/145376889-2aeb3a93-fc38-4f36-bb13-26799e9aa550.png)

**Comment by sayali-MSFT** [comment]
@priyakewlani18  -Could you please confirm if your issue has resolved with above suggestion or still looking for any help?

**Comment by v-chetsh** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.

**Comment by sayali-MSFT** [comment]
@priyakewlani18 - This is correct way to add it. Our cards support full range of Unicode points. 
sample:-
{
"type": "TextBlock",
"spacing": "None",
"text": "Hi ABC : 💯:",
"height": "stretch",
"wrap": true
}
![image](https://user-images.githubusercontent.com/93527375/147195566-8199b832-b33f-46b7-9f55-297f45a84736.png)

**Comment by v-chetsh** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.
