### ISSUE TITLE
Prerequisite for Meeting Details API

### ISSUE THREAD

**Issue by Navega** [MicrosoftDocs/msteams-docs#4827]
I would like to mention that we had problems to implement the request to "Meeting Details API", because an important prerequisite which isn't described here is that Bot must request the scope "groupchat". 

My suggestion is to add that in the specific section: https://docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/api-references?tabs=dotnet#prerequisite

Navega,
Software Developer at Appfluence Inc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 805dc242-7b5a-cc81-ee0e-6acf0078a653
* Version Independent ID: 11c0e023-2514-9639-6052-2cbbbef50663
* Content: [Meeting apps API references - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/api-references?tabs=dotnet#real-time-teams-meeting-events)
* Content Source: [msteams-platform/apps-in-teams-meetings/API-references.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/apps-in-teams-meetings/API-references.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Prasad-MSFT** [comment]
@Navega - In the [Prerequisites for apps in Teams meetings](https://docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings) it is already mentioned that `Use your app that supports configurable tabs in the groupchat scope.`  and `Support the groupchat scope to enable your app in pre-meeting and post-meeting chats.`

**Comment by Navega** [comment]
Thanks @Prasad-MSFT, I think when we created the app for Teams meetings the prerequisites were different (1,5 years ago), so we skipped these steps when we checked the "Meeting apps API references".

We solved the problem, but my suggestion is to make clearer that specific prerequisite in the section about "Meeting apps API references". In order to avoid the same blocker for other developers. Does it make sense?

**Comment by Wajeed-msft** [comment]
@Navega - Thanks for the suggestion, we are passing this feedback to documentation team. 

@surbhigupta12 - could you please check if we could [link to main prerequisites](https://docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings) page from [perquisites section of Realtime Meeting APIs](https://docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/api-references?tabs=dotnet#prerequisite-1)?
