### ISSUE TITLE
[Android][Column rendering] [TextBlock inside column inside another column not rendering]

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#4838]
Copied bug from: https://github.com/microsoft/AdaptiveCards/issues/5415 

**Details from original post:**
# Platform

What platform is your issue or question related to? (Delete other platforms).

- [ ] Android

# Author or host

Microsoft Teams 

# Version of SDK

SDK version 2.4.0

# Details

Text Block inside column inside another column does not render. 
Sample JSON - [Link](https://microsoft-my.sharepoint.com/:u:/p/dipja/ETV4S6bd21pDiS4jNwQ321ABP7OQsWii4JnPpi5TPEt1fA?e=mOZz1G) 

**Before**
<img width="279" alt="image" src="https://user-images.githubusercontent.com/61967816/108820158-c77ecf00-75e1-11eb-81e6-05ae667564ed.png">

**After**
<img width="279" alt="image" src="https://user-images.githubusercontent.com/61967816/108820218-e1201680-75e1-11eb-8bb0-f0fbac259bf1.png">
---
#### Document Details

⚠ *Do not edit this section.It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Cards reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **surbhigupta12**

**Comment by sayali-MSFT** [comment]
@dipja  - We are looking into this I will get back to you soon.

**Comment by sayali-MSFT** [comment]
@dipja - Could you please check the alignment (Width , height)  properly in you json file. 
Example:-"items":[
                  {
                     "columns":[
                        {
                           "width":"**120px**",
                           "items":[
                              {
                                 "height":"32px",
                                 "style":"person",
                                 "type":"Image",
                                 "url":"https://urlp.sfbassets.com/urlpcdn/sa1/contentapi1/f16ddd44-5869-47c0-8dd0-81bd8bc578ce",
                                 "width":"32px"
                              }
                           ],
                           "type":"Column"
                        },

**Comment by sayali-MSFT** [comment]
@dipja- Could you please confirm if your issue has resolved with above suggestion or still looking for any help?

**Comment by v-chetsh** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.
