### ISSUE TITLE
We should clarify that Teams-only bots are free

### ISSUE THREAD

**Issue by billbliss** [MicrosoftDocs/msteams-docs#484]
In the "Bots and Microsoft Azure" we should add a bullet that says that Teams only bots are free.

We should also tell people what free tier of Bot Framework to use if they register the bot using Azure.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 087ab52e-fa36-8255-1438-957f895ba583
* Version Independent ID: f19cdd18-9aef-2bb2-6c2f-e0f0f79b9ca0
* Content: [Create a bot - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/bots/bots-create)
* Content Source: [msteams-platform/concepts/bots/bots-create.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/bots/bots-create.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by neoashu** [comment]
Thanks Bill,
Ashish Thakur

**Comment by theCorb1nator** [comment]
Hi,

I found this at the bottom of the microsoft page, what do you mean by Teams-only bots are free? 

how do i set this up please?

**Comment by billbliss** [comment]
Bot Framework supports multiple kinds of "channels" for bots. Teams, web/DirectLine, Skype, Facebook, Kik, Slack, and a few more I'm forgetting. Messages sent/received to/from Teams/Skype bots are free (or rather are included with Teams/Skype).

The others are not.
