### ISSUE TITLE
Nit: Typo in subsection

### ISSUE THREAD

**Issue by MSJohnnyLee** [MicrosoftDocs/msteams-docs#4843]
<img width="713" alt="image" src="https://user-images.githubusercontent.com/83673822/145623203-da394158-557c-4848-97fb-84f2db69c488.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6cf09c2a-3d93-b74b-7a48-6631ed0b6d12
* Version Independent ID: 89fda258-8bca-f55e-ac01-35e92f187a63
* Content: [App development fundamentals overview - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/app-fundamentals-overview)
* Content Source: [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/app-fundamentals-overview.md)
* Product: **msteams**
* GitHub Login: @heath-hamilton
* Microsoft Alias: **lajanuar**

**Comment by v-chetsh** [comment]
@surbhigupta12 - Could you please help us here to update the contents.

**Comment by surbhigupta12** [comment]
Thank you for bringing this to our notice. The content is updated: 

https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/app-fundamentals-overview.md
