### ISSUE TITLE
View in Teams throws error "Unable to find scene's image file .png in archive provicded"

### ISSUE THREAD

**Issue by rpskumar** [MicrosoftDocs/msteams-docs#4845]
[Enter feedback here]
I am trying to create custom theme for together mode.  When I click on View in Teams button, it says "Unable to find scene's image file .png in archive provicded"

![image](https://user-images.githubusercontent.com/26256505/145642317-186481dc-7b50-4db1-a253-16ab7e217486.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7da63b6f-15d7-a6dd-82fc-d183afaeb816
* Version Independent ID: 82d1ca83-28dd-220e-ab0c-a4833f8f8143
* Content: [Manage your apps with the Developer Portal - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/teams-developer-portal)
* Content Source: [msteams-platform/concepts/build-and-test/teams-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/build-and-test/teams-developer-portal.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **surbhigupta**

**Comment by sayali-MSFT** [comment]
@rpskumar - We are looking into this I will get back to you soon.

**Comment by sayali-MSFT** [comment]
@rpskumar - We tried to repro this issue from our end, We are able to create custom theme for together modes.
Please have a look at this doc- https://docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/teams-together-mode

Let us know if you have any query.

**Comment by sayali-MSFT** [comment]
@rpskumar - Could you please confirm if your issue has resolved with above suggestion or still looking for any help?

**Comment by sayali-MSFT** [comment]
@rpskumar  - Could you please confirm if your issue has resolved with above suggestion or still looking for any help?
