### ISSUE TITLE
Links in PopUp Shown by a Teams bot is not keyboard accessible

### ISSUE THREAD

**Issue by sushmita-m** [MicrosoftDocs/msteams-docs#4851]
We own the Azure boards app in teams.

We have a button that opens a popup.
In the popup we have couple of links. They are not accessible through the tab functionality of keyboard.

Find the below attachment
![144824435-49c2e920-1c0e-4cab-af12-e4b2a51e3242](https://user-images.githubusercontent.com/63236940/145855511-33ae96cb-8871-4e1d-b7bb-aacc6de0a04f.gif)

**Comment by Meghana-MSFT** [comment]
We are mainly responsible for Microsoft Teams app development related issues. Hence redirecting this to Teams Product support.

**Comment by sushmita-m** [comment]
@Meghana-MSFT I still think this is a microsoft teams level bug. 
if you look at the gif attached,
We have a popup in teams,  and a link there `signin with different email` which does not get highlighted on pressing tab. Can you please elaborate why this is not teams related bug?

**Comment by Meghana-MSFT** [comment]
We do have a repro for this issue. This issue is related to Teams app only but its more related to Teams product. We are raising a bug for the same.

**Comment by ChetanSharma-msft** [comment]
@v-anvashist - Sorry for the late reply.
We will check with engineering team on the bug status and get back to you.

**Comment by aosolis** [comment]
@sushmita-m this is an iframe task module. Your app controls the contents of the iframe. It appears to have implemented the "Sign in with a different email" not as a link, but as text. It also doesn't have aria properties set.
![image](https://user-images.githubusercontent.com/767208/215894959-2b494c9a-e37b-457f-9aa7-8a012c607d86.png)

This is an issue with your app, not Teams. You can fix it by modifying the markup on your page to be accessible. I'll close this issue.
