### ISSUE TITLE
There is no way to mention Alt text  for bot icon in Microsoft teams

### ISSUE THREAD

**Issue by sushmita-m** [MicrosoftDocs/msteams-docs#4852]
We own the Azure boards app for teams.
In the manifest file, there is no option to mention an alt text for our app icon. As a result a speech tool is not reading the icon out loud.
This is an accessibility bug. 

In the below screenshot, the red exclamation marks are for reference.

<img width="1450" alt="Screenshot 2021-12-13 at 11 21 45 PM" src="https://user-images.githubusercontent.com/63236940/145863062-2c1b3f12-525a-4723-8e93-95e8e3371236.png">

**Comment by sayali-MSFT** [comment]
@sushmita-m - We are looking into this I will get back to you soon.

**Comment by sayali-MSFT** [comment]
@sushmita-m - We are able to repro that issue , We have raised bug for the same and concerned team is looking into it. We will inform you once we get any update.

**Comment by v-anvashist** [comment]
@sayali-MSFT   Do we have any update on the same?

**Comment by sayali-MSFT** [comment]
@v-anvashist-Currently we don’t have ETA or Update on this thread. 
We will update this thread once the bug is fixed.

**Comment by sayali-MSFT** [comment]
@v-anvashist @sushmita-m -Issue is Resolved.
 Microsoft Teams Version 1.6.00.17673 (64-bit). 
 Could you please check and confirm the same.
 

https://github.com/MicrosoftDocs/msteams-docs/assets/93527375/673da22f-cc90-41bb-8ecd-b84d37fb60d8
