### ISSUE TITLE
Action.OpenUrl results in encoding of # to %23 in the URL

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#4853]
Copied bug from: https://github.com/microsoft/AdaptiveCards/issues/6839 

**Details from original post:**
# Platform

What platform is your issue or question related to?

* iOS

# Author 

A bot installed into Microsoft teams, shares an adaptive card into Microsoft Teams channel.

# Version of SDK

1.2

# Issue

The following payload is sent in adaptive card for actions:-  

"actions" : [
&nbsp; {   
&nbsp;&nbsp;"type" : "Action.OpenUrl",  
&nbsp;&nbsp;"title" : "Launch in browser",  
&nbsp;&nbsp;"url" : "https://xyz.com/path?a=b#123"
&nbsp; }  
]

While clicking on "Launch in Browser" button on the adaptive card in the iOS mobile and tab devices , the "#" in URL gets encoded to "%23", as a result of which the website stops working.  The url open as "https://xyz.com/path?a=b%23123". This happens only in iOS and is working correctly in Android, Windows desktop and web version.
---
#### Document Details

⚠ *Do not edit this section.It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Cards reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **surbhigupta12**

**Comment by Meghana-MSFT** [comment]
We are looking into this issue. We will update you.

**Comment by Meghana-MSFT** [comment]
Closing this issue as the same is being discussed in the following thread - https://github.com/MicrosoftDocs/msteams-docs/issues/4839
