### ISSUE TITLE
How to set themeColor with .NET AdaptiveCards SDK

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#4854]
Copied bug from: https://github.com/microsoft/AdaptiveCards/issues/6841 

**Details from original post:**
### Discussed in https://github.com/microsoft/AdaptiveCards/discussions/6382

<div type='discussions-op-text'>

<sup>Originally posted by **soulflyman** September 21, 2021</sup>
When sending the following json to a MS Teams Webhook I can change the color bar above the message with the `themeColor` Option:
```json
{
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "type": "MessageCard",    
    "themeColor": "ff0000",
    "version": "1.2",
    "title": "Alarm!",
    "text": "Test Message" 
}
```

![2021-09-21 17_14_24-Microsoft Teams](https://user-images.githubusercontent.com/379492/134198261-2780dd0a-0a8f-486a-b2bf-67870ae184bb.png)

How is this possible with the .NET AdaptiveCards SDK that ist available via nuget?</div>---
#### Document Details

⚠ *Do not edit this section.It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Cards reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **surbhigupta12**

**Comment by Nivedipa-MSFT** [comment]
@soulflyman - We are checking this issue internally. We will get back to you.

**Comment by Nivedipa-MSFT** [comment]
@soulflyman - To change the color bar is not supported for Adaptive Cards. For O365ConnectorCard you can able to change the color bar.
Reference doc : [https://docs.microsoft.com/en-us/dotnet/api/microsoft.bot.schema.teams.o365connectorcard?view=botbuilder-dotnet-stable](url)

**Comment by v-chetsh** [comment]
@soulflyman - 
Could you please confirm if your issue has resolved with above suggestion or still looking for any help?

**Comment by soulflyman** [comment]
Ok, I'll test in on Jan 3rd, I'm on vacation right now 🙂
