### ISSUE TITLE
Custom Powershell script fails with System.Management.Automation.CmdletInvocationException

### ISSUE THREAD

**Issue by emahama** [MicrosoftDocs/msteams-docs#4856]
Running  **Connect-MicrosoftTeams** command in my custom script fails with System.Management.Automation.CmdletInvocationException

**Detailed error is shown below** 

INFO: Loaded Module 'Microsoft.Teams.ConfigAPI.Cmdlets'

INFO: Loaded Module 'Microsoft.Teams.Config'
**PS>TerminatingError(Import-Module): "A cmdlet named 'Add-TeamUser' already exists. Cmdlets must have unique names."
A cmdlet named 'Add-TeamUser' already exists. Cmdlets must have unique names.**

**System.Management.Automation.CmdletInvocationException**
A cmdlet named 'Add-TeamUser' already exists. Cmdlets must have unique names.

PS>TerminatingError(Add-TeamsAppInstallation): "You must call the Connect-MicrosoftTeams cmdlet before calling any other cmdlets."
The installation was not successful. Please rerun script.
System.UnauthorizedAccessException
You must call the Connect-MicrosoftTeams cmdlet before calling any other cmdlets.

***Find below full script**** 
```
<#
    .SYNOPSIS
    Installs Ava on Teams For an Individual User.
#>
#Requires -Version 5.1

If (-NOT ([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator))
{
  # Relaunch as an elevated process:
  Start-Process powershell.exe "-File",('"{0}"' -f $MyInvocation.MyCommand.Path) -Verb RunAs
  exit
}
Start-Transcript -Path .\transcripts.txt -Append

$Team_Name = Read-Host -Prompt "Enter The Existing Teams Team Name On Which You Are Wanting to Use Ava"
#$User_Email = Read-Host -Prompt "Enter your Microsoft Work Email"
Install-Module -Name PowerShellGet -Force -AllowClobber
Install-Module MicrosoftTeams -AllowPrerelease -RequiredVersion 1.1.3-preview
Install-Module Microsoft.Graph -Scope AllUsers
Connect-MicrosoftTeams
#Connect-MgGraph -Scopes "AppCatalog.ReadWrite.All, ChannelMember.ReadWrite.All, Group.ReadWrite.All, Reports.Read.All, User.Read.All"
$Group = $null
#$User = $null

try {
   $Group = Get-Team -DisplayName $Team_Name
   if ( $Group -eq $null )
   {
    throw "Team Name Exception"
   }
}
catch [Exception]
{
   Write-Warning $Error[0]
   Write-Output "The Team: $Team_Name you entered was not found, or the functon failed to execute. Please rerun script and make sure to enter the Team name as it appears in Teams."
   echo $_.Exception.GetType().FullName, $_.Exception.Message
   exit
}

#try {
#  $User = Get-TeamUser -GroupId $Group.GroupId | Where {$_.User -eq $User_Email}
#   if ( $Group -eq $null )
#   {
#    throw "Email not found Exception"
#   }  
#}
#catch 
#{
#  Write-Output "The Email you entered was not found, please rerun script and make sure to enter your work email correctly."
#   exit
#}

try {
   Remove-TeamsAppInstallation -AppId 070b4a02-c97a-4de5-b4a8-7e31db4cb09d -TeamId $Group.GroupId
   Write-Host "Attempting to unistall Ava from $Team_Name ..." 
}
catch [Exception] 
{
   Write-Host "Ava is not currently installed on $Team_Name . It will now be installed." 
   echo $_.Exception.GetType().FullName, $_.Exception.Message
}

try {
   Write-Host "Installing Ava on $Team_Name" 
   Add-TeamsAppInstallation -AppId 070b4a02-c97a-4de5-b4a8-7e31db4cb09d -TeamId $Group.GroupId
}
catch [Exception] 
{
   Write-Host "The installation was not successful. Please rerun script."
   echo $_.Exception.GetType().FullName, $_.Exception.Message
   Stop-Transcript
   exit
}
Stop-Transcript

#Remove-TeamsAppInstallation -AppId 070b4a02-c97a-4de5-b4a8-7e31db4cb09d -UserId $User.UserId
#Add-TeamsApp
```Installation -AppId 070b4a02-c97a-4de5-b4a8-7e31db4cb09d -UserId $User.UserId

**Comment by Nivedipa-MSFT** [comment]
@emahama - We are looking into this issue. We will update you.

**Comment by Nivedipa-MSFT** [comment]
@emahama - We have executed Connect-MicrosoftTeams command via powershell but its working fine for us. Could you please add userCredential command in your custom script and check again.

```
Import-Module MicrosoftTeams
$userCredential = Get-Credential
Connect-MicrosoftTeams -Credential $userCredential
```

**Comment by emahama** [comment]
To provide some context. The original script without the changes you recommended works for me but fails for one customer. After adding the recommended lines above, it now fails for me with below error. The customer also reported the same errors.


Transcript started, output file is .\log_12-22-2021-08-46.txt
Enter The Existing Teams Team Name On Which You Are Wanting to Use Ava: Edward Ava Test Team
WARNING: The version '1.4.7' of module 'PackageManagement' is currently in use. Retry the operation after closing the
applications.

cmdlet Get-Credential at command pipeline position 1
Supply values for the following parameters:
Credential
Connect-MicrosoftTeams : One or more errors occurred.: unknown_user_type: Unknown User Type
At C:\Users\edwardmahama\Desktop\SelfLearning\PowerShellTutorial\InstallAvaOnTeamv3.ps1:22 char:1
+ Connect-MicrosoftTeams -Credential $userCredential
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : AuthenticationError: (:) [Connect-MicrosoftTeams], AadAuthenticationFailedException
    + FullyQualifiedErrorId : Connect-MicrosoftTeams,Microsoft.Open.Teams.CommonLibrary.ConnectMicrosoftTeams

Connect-MicrosoftTeams : One or more errors occurred.
At C:\Users\edwardmahama\Desktop\SelfLearning\PowerShellTutorial\InstallAvaOnTeamv3.ps1:22 char:1
+ Connect-MicrosoftTeams -Credential $userCredential
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : AuthenticationError: (:) [Connect-MicrosoftTeams], AggregateException
    + FullyQualifiedErrorId : Connect-MicrosoftTeams,Microsoft.Open.Teams.CommonLibrary.ConnectMicrosoftTeams
                                                                                                                        Connect-MicrosoftTeams : unknown_user_type: Unknown User Type                                                           At C:\Users\edwardmahama\Desktop\SelfLearning\PowerShellTutorial\InstallAvaOnTeamv3.ps1:22 char:1                       + Connect-MicrosoftTeams -Credential $userCredential                                                                    + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                        + CategoryInfo          : AuthenticationError: (:) [Connect-MicrosoftTeams], AdalException                              + FullyQualifiedErrorId : Connect-MicrosoftTeams,Microsoft.Open.Teams.CommonLibrary.ConnectMicrosoftTeams                                                                                                                                   Connect-MicrosoftTeams : One or more errors occurred.: unknown_user_type: Unknown User Type                             At C:\Users\edwardmahama\Desktop\SelfLearning\PowerShellTutorial\InstallAvaOnTeamv3.ps1:22 char:1
+ Connect-MicrosoftTeams -Credential $userCredential
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Connect-MicrosoftTeams], AadAuthenticationFailedException
    + FullyQualifiedErrorId : Microsoft.Open.Teams.CommonLibrary.AadAuthenticationFailedException,Microsoft.Open.Teams
   .CommonLibrary.ConnectMicrosoftTeams

**Comment by v-chetsh** [comment]
@emahama - We will check on it and let you know if we find any solution for it.

**Comment by Nivedipa-MSFT** [comment]
@emahama - Could you please try with following command.
**Connect-MicrosoftTeams -AccountId $userEmail -MsAccessToken $token -AadAccessToken $token**

**Comment by emahama** [comment]
I get below error with this command..

PS C:\Users\edwardmahama\Desktop\SelfLearning\PowerShellTutorial> .\InstallAvaOnTeamv3.ps1
Transcript started, output file is .\log_12-28-2021-10-55.txt
Enter The Existing Teams Team Name On Which You Are Wanting to Use Ava: Edward Ava Test Team
WARNING: The version '1.4.7' of module 'PackageManagement' is currently in use. Retry the operation after closing the
applications.
Connect-MicrosoftTeams : Cannot validate argument on parameter 'AccountId'. The argument is null or empty. Provide an
argument that is not null or empty, and then try the command again.
At C:\Users\edwardmahama\Desktop\SelfLearning\PowerShellTutorial\InstallAvaOnTeamv3.ps1:23 char:35
+ Connect-MicrosoftTeams -AccountId $userEmail -MsAccessToken $token -A ...
+                                   ~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Connect-MicrosoftTeams], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.Open.Teams.CommonLibrary.ConnectMicrosoftTeam
   s

WARNING: You must call the Connect-MicrosoftTeams cmdlet before calling any other cmdlets.
The Team: Edward Ava Test Team you entered was not found, or the functon failed to execute. Please rerun script and make sure to enter the Team name as it appears in Teams.
System.UnauthorizedAccessException
You must call the Connect-MicrosoftTeams cmdlet before calling any other cmdlets.
PS C:\Users\edwardmahama\Desktop\SelfLearning\PowerShellTutorial>

**Comment by v-chetsh** [comment]
@emahama - We are mainly responsible for Microsoft Teams app development related issues.  

For questions related to PowerShell  [Microsoft PowerShell Community](https://techcommunity.microsoft.com/t5/powershell/ct-p/WindowsPowerShell) forum

**Comment by emahama** [comment]
The main issue I raised was pointing to Microsoft Teams, see below error.  This was happening for a specific user. I am not sure below error is related to Powershell.

PS>TerminatingError(Import-Module): "A cmdlet named 'Add-TeamUser' already exists. Cmdlets must have unique names."
A cmdlet named 'Add-TeamUser' already exists. Cmdlets must have unique names.

System.Management.Automation.CmdletInvocationException
A cmdlet named 'Add-TeamUser' already exists. Cmdlets must have unique names.

**Comment by v-chetsh** [comment]
@emahama - Sure, we will try to check it from our end and get back to you, if we find any solution.

**Comment by v-chetsh** [comment]
@emahama - Could you please confirm if your issue has resolved with above suggestion or still looking for any help?

**Comment by emahama** [comment]
Your instruction is not clear to me. let me summarize issue here again. I created the script above to install an application on Teams. In the scripts, I don't have  'Add-TeamUser' but the script fails with below error... 

PS>TerminatingError(Import-Module): "A cmdlet named 'Add-TeamUser' already exists. Cmdlets must have unique names."
A cmdlet named 'Add-TeamUser' already exists. Cmdlets must have unique names.

System.Management.Automation.CmdletInvocationException
A cmdlet named 'Add-TeamUser' already exists. Cmdlets must have unique names.


I hope this clarify the issue

**Comment by Nivedipa-MSFT** [comment]
@emahama - We have tried your script and also get same error. We have use upgraded Teams Module version 3.0.1 preview.
In script instead of Install-Module MicrosoftTeams -AllowPrerelease -RequiredVersion 1.1.3-preview command we use
**Install-Module MicrosoftTeams -AllowPrerelease -RequiredVersion 3.0.1-preview**.
And its working fine for us now.

Could you please use Teams Module 3.0.1 preview in script and check again.

**Comment by Nivedipa-MSFT** [comment]
@emahama - Could you please confirm if your issue has resolved with above suggestion or still looking for any help?

**Comment by emahama** [comment]
I am awaiting feedback from customer, I will update by COB today

**Comment by emahama** [comment]
You recommendation resolve the issue, thanks for your help
