### ISSUE TITLE
Chat for meetings says "(no title)" even though meeting has a title

### ISSUE THREAD

**Issue by netjeff** [MicrosoftDocs/msteams-docs#4857]
Beginning this week, on the chat for all my named meetings, the chat entry says "(no title)".    Last week and earlier the meeting chat matched the meeting title.

The symptoms are nearly identical to those described by @jiteshbutala in #3865.   Has this re-appeared?  I haven't yet taken the time to setup test meetings and try different combination the way that @jiteshbutala did.  

Version shows
> You have Microsoft Teams Version 1.4.00.31569 (64-bit). It was last updated on 12/7/21.

I checked for updates and nothing offered.

**Comment by Prasad-MSFT** [comment]
@netjeff - We tried to repro this at our end as mentioned But everything is working fine at our end(tested the scenarios few times). We tried both in Teams desktop and web client. `Microsoft Teams Version 1.4.00.34267 (64-bit). It was last updated on 12/10/2021.`
If any attendee (Other than originator) tried to start a conversation before start of meeting, he/she is able to get the Title.
Please try to update Teams version and check if it helps.

**Comment by netjeff** [comment]
Thanks for checking.  I tried update, but still nothing offered so still on 31569.    My company is on a "government channel" of O365, so sometimes there's a delay until we get the latest updates.  Once my Teams client is up to at least 34267, I'll let you know if symptoms still persist.

**Comment by netjeff** [comment]
Still waiting on my Teams client to update to at least 34267

**Comment by spdavern** [comment]
This started happening at my place of work, last week.  The MS Team About gives this information: You have Microsoft Teams Version 1.4.00.29477. It was last updated on 11/17/21.  That's about when it started happening.

**Comment by Prasad-MSFT** [comment]
We tried to repro this again at our end But everything is working fine at our end(tested the scenarios few times). We tried both in Teams desktop `Microsoft Teams Version 1.4.00.34267 (64-bit)` and web client. Please try to update to Teams latest version and check if it helps.

**Comment by v-chetsh** [comment]
@netjeff - We are not able to repro this scenario, Could you please re-check it once.

**Comment by netjeff** [comment]
Still waiting on my Teams client to update to at least 34267

**Comment by spdavern** [comment]
This issue has been reported to our IT department. It continues to persist. They are scheduled to come back from the holiday break tomorrow.

**Comment by v-chetsh** [comment]
@spdavern - Could you please confirm if your issue has resolved or still looking for any help?

**Comment by netjeff** [comment]
FYI,  Yesterday I had a couple of these "(no title)", still on 1.4.00.31569 (64-bit) on the "government channel" of O365.   I checked with another co-worker, and they are seeing the same thing.

I'll keep my fingers crossed that when my Teams updates to 34267 (or later) that this symptom stops occuring.

**Comment by spdavern** [comment]
My organization updated to 1.4.0.0.29477 yesterday.  I just had a meeting that enabled me to check if the (no meeting) chat issue was fixed.  It was not.  I don't know if a meeting has to be recreated in order for MS Teams to title the chat window properly.  However, given netjeff's comments regarding even newer builds, I suspect that will not be fruitful.

**Comment by spdavern** [comment]
Ok, the report I gave 15 minutes ago involved adding a new comment in a new instance of a recurring meeting.  The new comment appended to the previously created MS Teams "chat" list "recent" instance (channel?) that was mis-titled as "(no title)".  Just now I created a new meeting (not recurring), started it, made a comment in the meeting's chat, and the title of the new MS Teams chat list item (channel) was correct.

**Comment by v-chetsh** [comment]
@spdavern - Please let us know if you need any further help here or shall we close this issue?

**Comment by netjeff** [comment]
Please do not close this, I'm still having these symptoms.   For now I'm waiting on my Teams client to update, hoping that will resolve.

**Comment by Prasad-MSFT** [comment]
@netjeff - Are you still facing the issue or its resolved?

**Comment by netjeff** [comment]
Yes, it happened to me for a couple of meetings last week. Still on 1.4.00.31569 (64-bit) on the "government channel" of O365. I checked with another co-worker, and they are seeing the same thing.

Keeping my fingers crossed that when my Teams updates to 34267 (or later) that this symptom stops occurring.

**Comment by netjeff** [comment]
FYI:  My client updated part way, from 31569 to 32771, but still getting "(no title)".  @Prasad-MSFT can not reproduce on 34627, but my client still not there yet.   Still hoping that once my client updates to 34627 (or later) that this symptom stops occuring.

**Comment by Prasad-MSFT** [comment]
@netjeff - Is your issue resolved or are you still facing the issue?

**Comment by netjeff** [comment]
Client still on 32771 and not yet to 34627.  But it's been a while since I've seen a "no title" meeting.  So I guess it's fixed?  I'm ok for this to be closed.  Thanks.
