### ISSUE TITLE
Page Title is misleading

### ISSUE THREAD

**Issue by karuanag** [MicrosoftDocs/msteams-docs#4866]
[To better clarify the purpose of this page for search it should be titled "Building Microsoft Teams tabs overview"  This page gets confused with end user content on configuring and using Teams tabs.  Thank you.]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62b12649-8660-975a-87f6-2f7486b5dc79
* Version Independent ID: c1b86714-5b2e-79a8-5761-0fb2fd5746c0
* Content: [Microsoft Teams tabs - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs?source=docs#feedback)
* Content Source: [msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tabs/what-are-tabs.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by v-chetsh** [comment]
@surbhigupta12 - Could you please check on this doc update ask.
