### ISSUE TITLE
Flickering & Loading issue with adaptive card while unfurling link in teams channel

### ISSUE THREAD

**Issue by Abhiram219** [MicrosoftDocs/msteams-docs#4868]
**Describe the bug**
While link unfurls in the teams channel and if the response is an adaptive card, the card is not rendering as expected. Please see the video attached for the behavior. At 0.05 sec in the video attached, the card has loaded but it is not displayed, just a new empty line is added. The issue is observed only with adaptive cards, working as expected with hero and thumbnail cards. Also in 1-1 and group chats, this is working as expected.

Above behavior is when the card is loaded for the first time.

If the card is loaded from cache, card flickering is seen. ie, card appears in the compose box and disappears within a snap.

The complete behaviour can be seen in video attached

**To Reproduce**
1. Login to Microsoft teams tenant.
2. Install a custom bot with link-unfurling enabled. 
3. Go to the “teams” menu and open a channel.
4. Now try to paste the link to unfurl as “New conversation”.
5. Observe there is flickering that happens while trying to render the link. 
6. The adaptive card does not show up at all (a new line is being added).
7. But the card loads after the message is sent.

**Expected behavior**
The card is expected to be loaded in the compose box as in group and 1-1 chats. 

**Screenshots**
https://user-images.githubusercontent.com/60126553/146521088-780f1d46-cfb5-4cd3-aff8-0eca83d94277.mov

**Desktop (please complete the following information):**
 - OS: [Mac]
 - Browser [chrome, safari, edge]

**Comment by HunaidHanfee-MSFT** [comment]
We are looking into this. We will try to repro it at our end and let you know the updates.

Thanks

**Comment by HunaidHanfee-MSFT** [comment]
Could you please share the manifest? We are having issue in reproducing it. Please hide the info which are important for you

Thanks

**Comment by Abhiram219** [comment]
It can be reproducible with git links as well. Ex:- https://github.com/MicrosoftDocs/msteams-docs/issues/4868.
Allow previews for GitHub and it has the same behavior. 

If you are still facing issues in reproducing this I can share my manifest.

Adding the video link for the same behavior with the GitHub link.

https://user-images.githubusercontent.com/60126553/147095539-7e5cd177-cc88-4deb-bd55-d318d4056d28.mov

**Comment by HunaidHanfee-MSFT** [comment]
Thanks for sharing I will check and let you know.

**Comment by HunaidHanfee-MSFT** [comment]
Thanks for sharing the resource and repro steps. We have a repro we need to confirm this with internal team. I will soon update you.

**Comment by HunaidHanfee-MSFT** [comment]
We have raised a bug and internal engineering team will look into it. I will keep you updated.
Thanks

**Comment by Abhiram219** [comment]
Thanks

**Comment by ChetanSharma-msft** [comment]
Hello @Abhiram219 - Sorry for delay in response.
This bug has fixed. 
Could you please check it once and let me know (Microsoft Teams Version 1.5.00.15719 (64-bit))
