### ISSUE TITLE
While closing unfurled card in teams, a modal is popping up to uninstall App

### ISSUE THREAD

**Issue by Abhiram219** [MicrosoftDocs/msteams-docs#4869]
**Describe the bug**
While link unfurls in the teams channel and when we want to remove the adaptive card from the message, on clicking the cross button, instead of removing the card from the message, a modal is being popped up to uninstall the app. Also we are observing this issue recently from around 20-25 days.

**To Reproduce**
1. Login into Microsoft teams tenant.
2. Install a custom bot with link-unfurling enabled. 
3. Go to any of the chats and paste the link.
5. Wait until the card unfurls. 
6. Click the cross icon to remove the card.
7. Observe that a modal is popping up to uninstall App.

**Expected behavior**
The card is expected to be closed without the modal being popped up.

**Attachments**
https://user-images.githubusercontent.com/60126553/146527112-6688a973-39b2-46fd-a3ce-0213f2fbd521.mov

**Desktop (please complete the following information):**
 - OS: [Mac]
 - Browser [chrome, safari, edge]

**Comment by sayali-MSFT** [comment]
@Abhiram219 - We are looking into this I will get back to you soon.

**Comment by sayali-MSFT** [comment]
@Abhiram219 - We tried to repro this issue from our end, we are not get the popped up to uninstall the app. could you please check it once.
Please have a look at this doc- https://docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?tabs=dotnet

Let us know if you have any query.

**Comment by Abhiram219** [comment]
@sayali-MSFT Can you verify this on my developer teams instance? Below are the details
I'd:  abhiram.menni@empaabhi1.onmicrosoft.com
Pass: test@1234
Url for unfurling: https://empabhi1.service-now.com/esc?id=kb_article&sys_id=3020c9b1474321009db4b5b08b9a712d
We used the above docs to do link unfurling

**Comment by sayali-MSFT** [comment]
@Abhiram219 - We have raised a bug and internal engineering team will look into it. We will inform you once we get any update.

**Comment by sayali-MSFT** [comment]
@Abhiram219 -For link unfurling only app, the x button will uninstall the app. So, this is by design.
