### ISSUE TITLE
"Edited" text on top of adaptive card after Action.Submit

### ISSUE THREAD

**Issue by poovaiah** [MicrosoftDocs/msteams-docs#4871]
Hi,

I am seeing "Edited" text on top of the adaptive card after Action.Submit. Is this a new change for the adaptive card?

![Screenshot 2021-12-20 at 10 05 40 AM_censored](https://user-images.githubusercontent.com/12322449/146729232-19ca4422-2fd0-45d0-92a0-3d93a8b4034d.jpg)

**Comment by Prasad-MSFT** [comment]
@poovaiah - Yes, this is the new change in adaptive card. Whenever you will click on any Action.Submit button, it will show up this notification message.

**Comment by poovaiah** [comment]
Hi @Prasad-MSFT, I hope you meant the "Edited" message on the top left corner. Not the message which says "Your response was sent to the app".

**Comment by Prasad-MSFT** [comment]
@poovaiah - We have checked it at our end and we didn't get that "Edited" message at all. We checked in` Microsoft Teams Version 1.4.00.34267` .Please try to update your MS Teams version and check if it helps.
![image](https://user-images.githubusercontent.com/62237649/146770877-7ff71489-6e3c-420d-9a7e-e6544bd5ec72.png)
