### ISSUE TITLE
Buttons in a popup are not highlighted properly when navigating through keyboard.

### ISSUE THREAD

**Issue by sushmita-m** [MicrosoftDocs/msteams-docs#4876]
We own the Azure boards app for teams.
This is an accessibility bug. We are using teams application on windows.
We have a popup and on pressing tab, each of the item is getting highlighted to indicate it has been selected.
Buttons in popup are getting selected. **However,they are not visually highlighted to stand out.**

Attaching a video with voice for reference.

https://user-images.githubusercontent.com/63236940/146744566-197614b0-ebd2-4918-a5f1-1a471581f823.mov

**Comment by Nivedipa-MSFT** [comment]
@sushmita-m - We are able to repro this issue. We have raised the bug for it. We will let you know once we have any update.

**Comment by v-chetsh** [comment]
@sushmita-m - We  have informed the engineering team and they are working on it.
We will update you once it is fixed.

**Comment by Nivedipa-MSFT** [comment]
@sushmita-m - We are checking it with engineering team and let you know the updates.

**Comment by v-anvashist** [comment]
Hi Team,

Any update on the same?

Thanks,
Anjali

**Comment by Nivedipa-MSFT** [comment]
@v-anvashist - The issue has fixed now. Could you please update the Teams version and check.
