### ISSUE TITLE
Navigating to buttons in reply is difficult with keyboard tab functionality

### ISSUE THREAD

**Issue by sushmita-m** [MicrosoftDocs/msteams-docs#4880]
👋  Our team owns the Azure boards app in Teams.
We did this exercise as part of accessibility testing.
We are posting a button in one of our replies to bot command.

While navigating the messages through tab function in keyboard, the focus never really goes to the button as expected. I tried both tab and shift + tab.

to reproduce. You can install the azure boards apps in Teams and give the command, `@azure boards signin`. Or you can use any existing chat where a button is posted in the reply of a message.

For reference
<img width="1101" alt="Screenshot 2021-12-20 at 4 50 45 PM" src="https://user-images.githubusercontent.com/63236940/146759604-d0196312-93a8-4f04-9287-474e3eca5078.png">

**Comment by Meghana-MSFT** [comment]
We are able to navigate to the sign in button. Please follow the below steps : 

1. Use Shift+Tab to go to the previous message.
2. Clickt Insert + Enter to select the first message in the thread
3. Use Arrow keys to go to next message
4. Again Clickt Insert + Enter to focus the content in current message 
5. Use Tab to go through contents of the message

Attaching a video of the same :

https://user-images.githubusercontent.com/81138249/146927687-60f0e8ff-17f9-4890-ae2b-90336dbf1f2e.mp4

**Comment by sushmita-m** [comment]
Thanks a lot for verifying. This can be closed.
