### ISSUE TITLE
Teams Task Module - Deserialization Error on Teams mobile app for iOS

### ISSUE THREAD

**Issue by ChetanSharma-msft** [MicrosoftDocs/msteams-docs#4892]
Error when loading Task Module on iOS iOS 14.8.1 / MS Teams v3.20.0
Copying the bug here: https://github.com/microsoft/botbuilder-python/issues/1872

**Comment by HunaidHanfee-MSFT** [comment]
@alinealfa - We are trying to repro it our side. Will update the findings soon.

Thanks

**Comment by HunaidHanfee-MSFT** [comment]
We have the repro of this issue and raised a bug Internal team is working on it. I will let you know once it is fixed and rolled out in public


Thanks

**Comment by v-chetsh** [comment]
@alinealfa - Engineering team is working on this bug and will let you know once this is fixed.

**Comment by Prasad-MSFT** [comment]
We tested this in `iOS 17.4` and this seems to be working now.
Microsoft Teams version:
 
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/62237649/9d969193-c4e9-441c-8be8-7d7a8477d778)
