### ISSUE TITLE
Dont have option to add ARIA Attribute like role or area-lablel for bot in Microsoft Teams.

### ISSUE THREAD

**Issue by MayurMundekar** [MicrosoftDocs/msteams-docs#4894]
We own the Azure Repos app for teams.
In the manifest file, there is no option to add ARIA Attribute like role or area-lablel. As a result while doing accessibility check it is throwing the issue
This is an accessibility bug.

In the below screenshot, the red exclamation marks are for reference.
![1882858_A11y_AzDev-azchatops_Sign In_Sign in_AI4W (1)](https://user-images.githubusercontent.com/83640993/146931064-88adcba6-aace-4b22-a9e9-90cad371e30f.png)

**Comment by Prasad-MSFT** [comment]
@MayurMundekar - We have raised a bug for this and concerned team is looking into it. We will inform you once we get any update. Thanks!

**Comment by Prasad-MSFT** [comment]
@MayurMundekar - Could you please confirm if Azure Repro app for Slack  or Teams ?
