### ISSUE TITLE
Android Teams App can't resolve @mention token from Power Automate

### ISSUE THREAD

**Issue by SergeyGrayman** [MicrosoftDocs/msteams-docs#4913]
Power Automate:

![Capture1](https://user-images.githubusercontent.com/9824156/147240764-7c560711-eabb-4321-ab79-4faa02c173d3.PNG)

Desktop:

![Capture2](https://user-images.githubusercontent.com/9824156/147240789-c6b7381b-7548-4f26-bf99-d9763de83769.PNG)

iOS:

![MicrosoftTeams-image (9)](https://user-images.githubusercontent.com/9824156/147240807-59c5edc6-dbbf-408f-a742-104db9a813a0.png)

Android:

![Capture](https://user-images.githubusercontent.com/9824156/147240830-02bf6ce8-049c-4dc3-8df9-04c751e389b7.PNG)

**Comment by Nivedipa-MSFT** [comment]
@SergeyGrayman - Could you please share your flow zip package for reference. Its help us to repro the  issue.

**Comment by Nivedipa-MSFT** [comment]
@SergeyGrayman - We are able to repro the issue at our end and have raised the bug for it. Concerned team is looking into it and we will inform you once get any update.

**Comment by SergeyGrayman** [comment]
Any news on this bug?

**Comment by Nivedipa-MSFT** [comment]
@SergeyGrayman - Engineering team is working on it. Right now we don't have any ETA to share. We will let you know once we get any update.

**Comment by Snoxfox** [comment]
Any update ?

**Comment by Nivedipa-MSFT** [comment]
@Snoxfox - Engineering team is looking into this issue.
Currently we do not have any ETA to share but we will let you know once we get any update from them.

**Comment by Snoxfox** [comment]
Any update ?

**Comment by Nivedipa-MSFT** [comment]
@SergeyGrayman, @Snoxfox - This bug has fixed now. Could you please update the Teams version and check again.
