### ISSUE TITLE
Min Height not present to scrollbar in teams chats

### ISSUE THREAD

**Issue by bhanuprakashj** [MicrosoftDocs/msteams-docs#4914]
Scrollbar thumb kept on decreasing size till it is looking like an underscrore. I feel there is should be a fixed minimum height to scroll bar thumb.
![e425fb9a-5bf8-4cae-9661-e7545a332cd7](https://user-images.githubusercontent.com/34719759/147247924-c14abdec-86e7-4d8b-979f-c7ae8e39abdd.jpg)

**Comment by v-chetsh** [comment]
@bhanuprakashj - Could you please confirm whether it's related to Teams app development or Teams product issue?
If it's related to Teams app development, could you please share the repro steps?

**Comment by bhanuprakashj** [comment]
The issue I found is in Microsoft Teams Desktop client.
The repro steps: 
During a teams meeting, participants started sharing messages in the meeting chat.
Later after meeting If I wanted to see the first message in that chat, I had scroll to top in the chat with that, the scroll bar size kept on decreasing for every new lazy load. Eventually the scroll thumb became so small as a dot.

Also, can you please help me understand the difference between Teams app development and Teams product issue?

**Comment by v-chetsh** [comment]
@bhanuprakashj - We are mainly responsible for 3rd party apps development for Microsoft Teams like Bots, Tabs, Messaging Extensions etc. related issues.
Microsoft Teams is a 1st party product and developed by Microsoft.

Thanks!
