### ISSUE TITLE
Displaying "&nbsp;" instead of a space

### ISSUE THREAD

**Issue by bhanuprakashj** [MicrosoftDocs/msteams-docs#4915]
Instead of a space character the name is rendered with "& nbsp;" when tagged by other users in teams chats.
![Screenshot 2021-12-23 192708](https://user-images.githubusercontent.com/34719759/147250207-d68dd536-6137-40fa-a02d-d9e2e7bfb9c8.png)

**Comment by Prasad-MSFT** [comment]
@bhanuprakashj - Could you please elaborate your issue ? Please share repro steps.

**Comment by bhanuprakashj** [comment]
This issue is noticed with one particular user, not sure what is the reason.
It is reproducible in following ways:
-  when that particular user replies to any Teams channel then in the notification it is shown as <first-name>&nbsp;<last-name>. Please note this is happening with that particular user
- also when the user is tagged in chats/teams using @<username> (please find the screenshot attached in issue description)

**Comment by Prasad-MSFT** [comment]
@bhanuprakashj - Please update your Microsoft Teams instance to latest version and check if you are still facing the issue.

**Comment by bhanuprakashj** [comment]
I believe am using latest version of Microsoft Teams instance.
![image](https://user-images.githubusercontent.com/34719759/147458731-1e2d20e7-6c03-458c-86bb-f76a8c85e491.png)

**Comment by Meghana-MSFT** [comment]
We have tried this in latest version [1.4.00.34267]. We are not able to repro this issue.

For Microsoft Teams product issues/failures your tenant Admin can reach out to [Microsoft 365 Product Support](https://docs.microsoft.com/en-us/microsoft-365/admin/get-help-support?view=o365-worldwide&tabs=online).

**Comment by bhanuprakashj** [comment]
I just checked for updates in teams, after a while got this message saying:
![image](https://user-images.githubusercontent.com/34719759/147480096-439d87a8-03c1-428b-b0bd-6ac72da1a21c.png)

But when I checked for the version number after updating, It still says last updated on 12/15/2021 also the version is not matching with the one you mentioned.
![image](https://user-images.githubusercontent.com/34719759/147480845-2b04f2eb-e8ed-4a72-9d96-a4121a4d80b9.png)

**Comment by Prasad-MSFT** [comment]
We tried to repro the issue at our end, but everything works for us as well in MS Teams latest version. `Microsoft Teams Version 1.4.00.34267 (64-bit). It was last updated on 12/10/2021.` 
The issue seems more of Teams Product related. For Microsoft Teams product issues/failures your tenant Admin can reach out to [Microsoft 365 Product Support](https://docs.microsoft.com/en-us/microsoft-365/admin/get-help-support?view=o365-worldwide&tabs=online).

**Comment by bhanuprakashj** [comment]
okay thanks!, Wish you a happy new year ahead!

**Comment by v-chetsh** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.
