### ISSUE TITLE
"Microsoft Teams Helper" using 39% CPU even when Teams is not being used - Please fix.

### ISSUE THREAD

**Issue by aj75** [MicrosoftDocs/msteams-docs#492]
Microsoft Teams Helper is running 39% CPU even when Teams is not being used. This usage is consistent all through the day. Please fix it.
I have attached screenshot.
System is MacOS Mojave (ver: 10.14.3)
![image](https://user-images.githubusercontent.com/45766574/53972231-01d4c600-40c4-11e9-9395-4d473370be66.png)

**Comment by Wajeed-msft** [comment]
We are tracking this internally. Closing this from documentation issues.

**Comment by tonypapousek** [comment]
Any update on this? Why close an issue for a known bug? The Helper still users significant energy in macOS, which is just silly for a glorified chat application.

**Comment by gordonkoehn** [comment]
Same here!! - Teams uses insane amount of CPU if on screen. Calls increase the CPU load again. reinstalled and updated, checked settings.
