### ISSUE TITLE
can't see the app show in Office.com

### ISSUE THREAD

**Issue by chenxizhang** [MicrosoftDocs/msteams-docs#4923]
Could you please provide a screenshot if you can see the app in office.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2cf31a5-621a-eeac-26c9-89ada49466c0
* Version Independent ID: b2cf31a5-621a-eeac-26c9-89ada49466c0
* Content: [Extend a Teams personal tab app across Microsoft 365 - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/m365-apps/extend-m365-teams-personal-tab?tabs=manifest-teams-toolkit)
* Content Source: [msteams-platform/m365-apps/extend-m365-teams-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/m365-apps/extend-m365-teams-personal-tab.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by v-chetsh** [comment]
@surbhigupta12 - Could you please help us here to update the contents accordingly.

**Comment by surbhigupta12** [comment]
@erikadoyle, 

please assist @v-ypalikila with this issue.

**Comment by erikadoyle** [comment]
Hi @chenxizhang, office.com preview support is coming but not yet publicly available. We'll announce on [M365 Developer Blog](https://devblogs.microsoft.com/microsoft365dev/) once available. So far, preview support for running Teams apps includes Outlook on Windows desktop (personal tabs), and outlook.com (personal tabs, message extensions):

- https://devblogs.microsoft.com/microsoft365dev/announcing-teams-js-sdk-v2-in-public-preview-extend-teams-apps-across-microsoft-365/
- https://devblogs.microsoft.com/microsoft365dev/teams-js-sdk-v2-public-preview-update-teams-apps-in-outlook-web/

Upon availability, we will include screenshots of office.com. In the meantime, I will revise the docs to better explain current support. Thank you for the feedback, and apologies if the docs caused you any confusion.

**Comment by Wajeed-msft** [comment]
@chenxizhang - please feel free to re-open if you have any further questions.
