### ISSUE TITLE
How to collaborate on a teams app (bot/messaging Extension) on teams

### ISSUE THREAD

**Issue by astuj** [MicrosoftDocs/msteams-docs#4925]
Hi, I as just wondering what is the best solution to collaborate (multiple developers) on a teams bot app. As we need to use ngrok url to develop/debug the app, how can we have multiple developer work on the same app at the same time?

**Comment by sayali-MSFT** [comment]
@astuj - We are looking into this I will get back to you soon.

**Comment by v-chetsh** [comment]
@astuj - There are 2 ways by which developers can contribute to a single app development:

**Solution one:** You can have different Azure bots with ngrok configuration for different developers.
**Solution two:** One developer can run the ngrok and all developers can use the same ngrok configuration but request will come to the same ngrok and network traffic will be more on a single ngrok endpoint.

**Comment by astuj** [comment]
Okay, Thanks @v-chetsh.
