### ISSUE TITLE
Need to add sample link for - Typeahead search control on Adaptive Cards

### ISSUE THREAD

**Issue by AbhijeetThakur-msft** [MicrosoftDocs/msteams-docs#4930]
Hi Team,

This sample demos a feature of type ahead search (static and dynamic) control in Adaptive Cards..

Please add the following sample links to the document for further reference:

|    | Sample Name        | Description                                                                                                                | C#    | Nodejs
|:--:|:-------------------|:---------------------------------------------------------------------------------------------------------------------------|:--------|:-------------|
|1|Type ahead search control on Adaptive Cards            | This sample shows the feature of type ahead search (static and dynamic) control in Adaptive Cards.            |                            [View](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/bot-type-ahead-search-adaptive-cards/csharp)     |[View](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/bot-type-ahead-search-adaptive-cards/nodejs)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 241af5f4-3d0b-5d00-4ecf-94681543159d
* Version Independent ID: 241af5f4-3d0b-5d00-4ecf-94681543159d
* Content: [Typeahead search in Adaptive Cards - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/dynamic-search?tabs=desktop)
* Content Source: [msteams-platform/task-modules-and-cards/cards/dynamic-search.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/dynamic-search.md)
* Product: **msteams**
* GitHub Login: @Rajeshwari-v
* Microsoft Alias: **surbhigupta**

**Comment by v-chetsh** [comment]
@v-abirade, @surbhigupta12 - Could you please help us here to update the sample link?

**Comment by AbhijeetThakur-msft** [comment]
Hello Team,

Request you to add  code snippets for invoke request and response generated:

**Invoke Request:**
```
{
    "name": "application/search",
    "type": "invoke",
    "value": {
        "queryText": "fluentui",
        "queryOptions": {
            "skip": 0,
            "top": 15
        },
        "dataset": "npm"
    },
    "locale": "en-US",
    "localTimezone": "America/Los_Angeles",
    // …. other fields
}
```
Response (nodejs)

```
{
    status: 200,
    body : {
        "type": "application/vnd.microsoft.search.searchResponse",
        "value": {
           "results": [
                {
                    "value": A very extensive set of extension methods...",
                    "title": "FluentAssertions"
                },
                {
                    "value": "item-2",
                    "title": "result item 2"
                }
            ]
        }
    }
}
```
Response - csharp

```
InvokeResponse adaptiveCardResponse;
var packages = 
[
  {
	id: "FluentAssertions",
	description: "A very extensive set of extension methods that allow you to more naturally specify the expected outcome of a TDD..."
  }
]
  
var packageList = packages.Select(item => { var obj = new { title = item.id, value = item.description }; return obj; }).ToList();
  
var searchResponseData = new
{
    type = "application/vnd.microsoft.search.searchResponse",
    value = new
    {
        results = packageList
    }
};
var jsonString = JsonConvert.SerializeObject(searchResponseData);
JObject jsonData = JObject.Parse(jsonString);
adaptiveCardResponse = new InvokeResponse()
{
    Status = 200,
    Body = jsonData
};
```

**Comment by v-abirade** [comment]
Thanks @AbhijeetThakur-msft, I will update the same and add you as reviewer.

**Comment by v-abirade** [comment]
Request to please review: https://github.com/MicrosoftDocs/msteams-docs/pull/4932

**Comment by v-sreenivasv** [comment]
@AbhijeetThakur-msft, request you to review the linked PR: https://github.com/MicrosoftDocs/msteams-docs/pull/4932
