### ISSUE TITLE
Teams app manifest error while creating a messaging extension. 

### ISSUE THREAD

**Issue by astuj** [MicrosoftDocs/msteams-docs#4935]
Hi, I am getting an error while creating a messaging extension with dynamic parameter. 
<img width="745" alt="Screenshot 2022-01-03 at 4 25 42 PM" src="https://user-images.githubusercontent.com/20801184/147923187-d311a4b7-2735-4c30-b2c9-8aa3555e7266.png">

Since I am working with dynamic parameter I do not have an option to add parameter in the app studio.
<img width="1052" alt="Screenshot 2022-01-03 at 4 30 02 PM" src="https://user-images.githubusercontent.com/20801184/147923286-de163e8d-2f8b-41c3-aad0-7183a69e865a.png">

Due to which I am not able to publish the app to teams. Any solution to this would be helpful.

**Comment by v-chetsh** [comment]
@astuj - Could you please add at least one **composeExtensions.commands** to make it work.
Please refer below docs:
https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema#composeextensionscommands

**Comment by astuj** [comment]
@v-chetsh - I have already add a action command with dynamic parameter.
<img width="1071" alt="Screenshot 2022-01-03 at 5 07 20 PM" src="https://user-images.githubusercontent.com/20801184/147926388-6d596dfe-0dea-4c21-a403-975fc07f0aab.png">
 
As you can see it is showing parameter as 0 which is causing the error. And there is no option of adding parameters when dynamic parameter is chosen.

<img width="643" alt="Screenshot 2022-01-03 at 5 09 16 PM" src="https://user-images.githubusercontent.com/20801184/147926453-374d3dce-6002-44a7-9a99-35ef1877e500.png">

**Comment by v-chetsh** [comment]
@astuj - Are you trying it with App Studio or Developer Portal?
Could you please check with App Studio, if not already tried?

**Comment by v-chetsh** [comment]
@astuj - Could you please share your manifest so that we can check it from our end?

**Comment by astuj** [comment]
Here is the manifest: 

{
  "$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.11/MicrosoftTeams.schema.json",
  "manifestVersion": "1.11",
  "version": "1.0.0",
  "id": "Bot-ID",
  "packageName": "com.teams.microsoft.eebot",
  "developer": {
    "name": "Test",
    "websiteUrl": "https://www.test.com/",
    "privacyUrl": "https://www.test.com/privacy-policy",
    "termsOfUseUrl": "https://www.test.com/terms-and-conditions"
  },
  "icons": {
    "color": "color.png",
    "outline": "outline.png"
  },
  "name": {
    "short": "Employee Engagement (dev)",
    "full": "Employee Engagement (Dev)"
  },
  "description": {
    "short": "Teams bot for employee engagement ",
    "full": "Teams bot for employee engagement , Teams bot for employee engagement "
  },
  "accentColor": "#F9F9FA",
  "bots": [
    {
      "botId": "Bot-Id",
      "scopes": [
        "personal"
      ],
      "supportsFiles": false,
      "isNotificationOnly": false
    }
  ],
  "composeExtensions": [
    {
      "botId": "Bot-Id",
      "canUpdateConfiguration": false,
      "commands": [
        {
          "id": "test",
          "type": "action",
          "title": "test",
          "description": "test",
          "initialRun": true,
          "fetchTask": true,
          "context": [
            "commandBox",
            "compose"
          ],
          "parameters": [
            {
              "name": "param",
              "title": "param",
              "description": ""
            }
          ],
          "taskInfo": {
            "title": "test",
            "width": "medium",
            "height": "medium",
            "url": "https://www.test.com"
          }
        }
      ]
    }
  ],
  "permissions": [
    "identity",
    "messageTeamMembers"
  ],
  "validDomains": [
    "token.botframework.com"
  ],
  "webApplicationInfo": {
    "id": "Bot-ID",
    "resource": "api://botid-Bot-ID"
  }
}

Here’s what I get when i try to install it. 

<img width="731" alt="Screenshot 2022-01-03 at 5 48 34 PM" src="https://user-images.githubusercontent.com/20801184/147929562-25b813bb-9479-4d05-8ad4-029347eac4b3.png">

**Comment by v-chetsh** [comment]
@astuj - Thanks for sharing the details.
We will check on it and get back to you.

**Comment by sayali-MSFT** [comment]
@astuj - we are tried to repro the scenario but I did not get the error as you mention above.
 I am attaching the zip file which is working fine. Hopefully it helps you.

[manifest (2).zip](https://github.com/MicrosoftDocs/msteams-docs/files/7802262/manifest.2.zip)

![image](https://user-images.githubusercontent.com/93527375/147938820-e52e3c58-6376-4f0b-938d-36d52d618cbd.png)
![MicrosoftTeams-image](https://user-images.githubusercontent.com/93527375/147938902-96e0bd4c-6104-42ea-9fc1-29d29fe4386b.png)

**Comment by sayali-MSFT** [comment]
@astuj - Could you please confirm if your issue has resolved with above suggestion or still looking for any help?

**Comment by astuj** [comment]
@v-chetsh - I came across something yesterday so it by using the developer portal we are adding a messaging extension ( action command with dynamic parameter ) we are getting the value of parameter as 0 by default which is giving the following error

<img width="1135" alt="Screenshot 2022-01-13 at 10 56 48 AM" src="https://user-images.githubusercontent.com/20801184/149271116-199eb836-a9f8-4a0a-ae99-f822584c36a9.png">

<img width="837" alt="Screenshot 2022-01-13 at 10 58 19 AM" src="https://user-images.githubusercontent.com/20801184/149271214-ef376847-10ca-4bd1-b79e-912f63736956.png">

the manifest is as follows for the extension

"composeExtensions":[
      {
         "botId":"24ea383a-ca3f-4f4d-93a7-3e3ab6edf8dc",
         "commands":[
            {
               "id":"test",
               "type":"action",
               "title":"test",
               "description":"test",
               "initialRun":true,
               "fetchTask":true,
               "context":[
                  "commandBox",
                  "compose"
               ],
               "parameters":[
                  
               ],
               "taskInfo":{
                  "title":"test",
                  "width":"100",
                  "height":"100",
                  "url":"https://www.test.com"
               }
            }
         ],
         "canUpdateConfiguration":false,
         "messageHandlers":[
            
         ]
      }
   ],

the parameter property here is null so thats why we are getting parameter as 0.

On the other hand if we do not pass the parameter property in the manifest by default the developer portal takes the parameter as 1 and not giving the error.

**Comment by v-chetsh** [comment]
@astuj - Thanks a lot for confirmation.
Do you need any further help here or shall we close it internally?
