### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by FrankTheTank314** [MicrosoftDocs/msteams-docs#494]
https://dev.botframework.com/bots/new is broken

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 087ab52e-fa36-8255-1438-957f895ba583
* Version Independent ID: f19cdd18-9aef-2bb2-6c2f-e0f0f79b9ca0
* Content: [Create a bot - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/bots/bots-create)
* Content Source: [msteams-platform/concepts/bots/bots-create.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/bots/bots-create.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by clearab** [comment]
This seems to be working as expected for me. Can you send us more details of your experience when clicking this link?
