### ISSUE TITLE
[MS Teams][IPhone] [Carousal][Weird behavior with Action.Submit  title text]

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#4940]
Copied bug from: https://github.com/microsoft/AdaptiveCards/issues/5016 

**Details from original post:**
# Platform

What platform is your issue or question related to? (Delete other platforms).

- [ ] iOS

# Details
Hi team,

We have seen weird behavior for adaptive card consist of only action button on iPhone teams.

we have seen that for same adaptive card complete text on Action button in adaptive card, But some time we are getting ... (Continuation dots) for same card. please check the screenshot attached below for reference. 

**Please find the sample Adaptive card json**
 [Sample JsonTxt.txt](https://github.com/microsoft/AdaptiveCards/files/5480577/Sample.JsonTxt.txt)

**Screen Shot 1**:
![123](https://user-images.githubusercontent.com/60354515/97964788-54a5da00-1ddf-11eb-8855-accefd5bd219.jpeg)

**ScreenShot 2**:

![1234](https://user-images.githubusercontent.com/60354515/97964793-57083400-1ddf-11eb-8f9b-76441eacc1a4.jpeg)

---
#### Document Details

⚠ *Do not edit this section.It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Cards reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **surbhigupta12**

**Comment by HunaidHanfee-MSFT** [comment]
Thanks for sharing the information, we will try to repro it at our end and let you know soon.

**Comment by HunaidHanfee-MSFT** [comment]
Are you having these two scenario on same device or different?

Thanks

**Comment by HunaidHanfee-MSFT** [comment]
We have tried few times but we are having few buttons without ... and few are showing full name(everytime) and this is expected as per the screen size.  Could please confim if you are this behavior on same device?

**Comment by HunaidHanfee-MSFT** [comment]
Could you please confirm on above question? We have tried but we are having same experience every time, text having more letter are show in form of **...** and short are fully visible. Can you please tell us if you are two different behavior on same device?
