### ISSUE TITLE
[Rendering] [Teams] Image not rendered on Microsoft Teams chat desktop & browser application

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#4941]
Copied bug from: https://github.com/microsoft/AdaptiveCards/issues/6076 

**Details from original post:**
# Target Application

Please provide the name of the application that is rendering the card (ex: Outlook, Teams, etc)
- Microsoft Teams (Browser, Desktop for Mac & Desktop for Windows)

# Problem Description

Image on adative card  rendered well on Mobile Application, but not in Browser & Desktop (mac & windows) Teams application.

# Screenshot

this is mobile application screenshot which is well rendered
![rendering goods](https://user-images.githubusercontent.com/15967833/125248034-cbf01e00-e31d-11eb-9a96-88b512a3b941.jpeg)

and this one is screenshot from teams desktop on windows. teams desktop for mac & teams browser application is same.
![image](https://user-images.githubusercontent.com/15967833/125248171-f80b9f00-e31d-11eb-998a-e6b892123215.png)

# Card JSON

```
{
                    $schema: "http://adaptivecards.io/schemas/adaptive-card.json",
                    type: "AdaptiveCard",
                    version: "1.2",
                    body: [{
                        type: "TextBlock",
                        text: `${contentType} :`,
                        weight: "Bolder",
                        size: "Medium",
                        color: "Accent"
                    },
                    {
                        type: "TextBlock",
                        text: `[${title}](${newsUrl})`,
                        isSubtle: true,
                        wrap: true
                    },
                    {
                        type: "Image",
                        url: image, // "base64 image"
                        horizontalAlignment: "Center"
                    }]
                }
```
---
#### Document Details

⚠ *Do not edit this section.It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Cards reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **surbhigupta12**

**Comment by Meghana-MSFT** [comment]
We are checking this issue. We will update you.

**Comment by Meghana-MSFT** [comment]
We tried the same with a random image url and it is working fine. Could you please share the actual json file of the adaptive card? Image url that you are using?
