### ISSUE TITLE
How can I post to multiple channels at once?

### ISSUE THREAD

**Issue by davidcantrelluk2** [MicrosoftDocs/msteams-docs#495]
I've set up an incoming webhook so that I can post to a Teams channel from a script, and it Just Works, nice and simple. But how can I post to multiple channels at once? The use case is that I want to notify back-end developers, front-end developers, and our QA team that I've deployed a release candidate.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0fd8e4d-f110-36f8-5bd3-db3325b14c01
* Version Independent ID: 717ea854-1d3a-2c15-e495-b6f170fe7aff
* Content: [Using Office 365 Connectors - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/connectors/connectors-using#setting-up-a-custom-incoming-webhook)
* Content Source: [msteams-platform/concepts/connectors/connectors-using.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/connectors/connectors-using.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by billbliss** [comment]
There's no direct way of doing this as every channel has a different endpoint. You must to loop through the incoming webhook URLs that have been configured - and by implication there must be a place to store them. This is what all the systems that support webhooks do: GitHub, VSTS/Azure DevOps, Jenkins, etc.

**Comment by davidcantrelluk2** [comment]
Urgh. Ah well, thanks for letting me know.
