### ISSUE TITLE
Activity Text not rendering Curly Braces and text between them in Teams

### ISSUE THREAD

**Issue by JordyGit** [MicrosoftDocs/msteams-docs#4956]
When sending an Activity from out Teams App/Bot with **Text containing curly braces***, the braces and text between them is **not displayed in Microsoft Teams**.  (Tested in Windows Desktop Client, IOS Mobile client)
_*Curly braces:_ `shown text { hidden text and hidden braces } shown text`
When sending the same text in an Adaptive Card in the Attachments of an Activity there are no issues and the text is displayed correctly.

Example of a message (copy from Bot Framework Emulator, here displayed correctly) not displaying the curly braces and the text between them when opened in Microsoft Teams, as reproduction step:
```
{
  "type": "message",
  "serviceUrl": "https://7505-81-82-247-96.ngrok.io",
  "channelId": "emulator",
  "from": {
    "id": "bdde1c80-68a7-11ec-977e-239e4f47d82a",
    "name": "Bot",
    "role": "bot"
  },
  "conversation": {
    "id": "d48cafb0-6d6f-11ec-977e-239e4f47d82a|livechat"
  },
  "recipient": {
    "id": "8aaa72b4-df3e-4d0f-b11e-cf3aca74f1b9",
    "role": "user"
  },
  "locale": "en-US",
  "text": "I did not find any files in **random folder name {w}ith braces**.",
  "inputHint": "acceptingInput",
  "attachments": [],
  "entities": [],
  "replyToId": "6871a3a0-6d72-11ec-86bc-170dcc4eb344",
  "id": "69790180-6d72-11ec-86bc-170dcc4eb344",
  "localTimestamp": "2022-01-04T16:24:30+01:00",
  "timestamp": "2022-01-04T15:24:30.488Z"
}
```

Acceptance criteria: Just displays the text and curly braces as expected.

Workaround: Replace the curly braces with their Unicode equivalent (`{` with `&#x7B;` and `}` with `&#x7D;`).

**Comment by Nivedipa-MSFT** [comment]
@JordyGit - We are looking into this issue. We will update you.

**Comment by Nivedipa-MSFT** [comment]
@JordyGit - We are able to repro this issue and we have raised a bug for it.

We will let you know once we get updates on it.

**Comment by Nivedipa-MSFT** [comment]
@JordyGit -  We are checking it with engineering team and let you know the updates

**Comment by i-rox** [comment]
any updates?

**Comment by Nivedipa-MSFT** [comment]
@JordyGit, @i-rox - Curly braces {} are special characters in Markdown and have to be escaped for them to render:
[Basic Syntax | Markdown Guide](https://www.markdownguide.org/basic-syntax)

If you change the text to the following it will work:
"I did not find any files in **random folder name \\{w\\}ith braces**."

Please note the backslash itself is special character so it also needs to be escaped.

**Comment by JordyGit** [comment]
Still notable all other special characters work without the need for escaping them except { or }

**Comment by JordyGit** [comment]
I tried escaping them with \ or \\ but teams displays them so still i use my own workaround of replacing them with `&#x7B;` or `&#x7D;`

**Comment by Nivedipa-MSFT** [comment]
@JordyGit - We have tested below text with \\ and we are getting curly braces and text between them.
"I did not find any files in **random folder name \\{w\\}ith braces**."

![image](https://user-images.githubusercontent.com/92150070/204502612-597ed229-76f9-43b5-8fb9-4c0ffe0de510.png)

Could you please check and confirm on this?

**Comment by JordyGit** [comment]
Maybe it has been fixed in the meantime. I can check later when working on the app again. It's ok to close it for now. If not fixed I'll come back to this issue.

**Comment by Nivedipa-MSFT** [comment]
We are closing this issue for now. Please feel free to reopen if required.
