### ISSUE TITLE
Font size mismatch in adaptive cards when url unfurls in teams

### ISSUE THREAD

**Issue by Abhiram219** [MicrosoftDocs/msteams-docs#4959]
**Describe the bug**

When the Url is unfurled in teams by using [link unfurling](https://docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?tabs=dotnet), font size for medium text is exptected to be 18px as per figma link in [design docs](https://docs.microsoft.com/en-gb/microsoftteams/platform/task-modules-and-cards/cards/design-effective-cards?tabs=design) but it is 17px.

**To Reproduce**
1. Go to https://adaptivecards.io/designer/
2. On the prepopulated adaptive card inspect and check the font size.
3. The font size is 17px and the same is reflected in unfurled adaptive card.

**Expected behavior**
 The expected font size is 18px.

**Screenshots** 
Below Image represents behaviour in https://adaptivecards.io/designer/
<img width="592" alt="Screenshot 2022-01-05 at 1 46 19 PM" src="https://user-images.githubusercontent.com/60126553/148183552-c6dec0d1-c373-4793-9e5e-439d1249287e.png">

Below Image represents behaviour in our unfurling implementation
<img width="563" alt="Screenshot 2022-01-05 at 1 47 02 PM" src="https://user-images.githubusercontent.com/60126553/148183644-81556e22-eceb-48ec-9f90-befa5b3a18d7.png">

**Desktop (please complete the following information):**
 - OS: [Mac] ( could be an issue in other OS as well)
 - Browser [ chrome, safari]
 - Version [all]

Also please let us know if we can configure the size manually.

**Comment by sayali-MSFT** [comment]
@Abhiram219 - We are looking into this I will get back to you soon.

**Comment by Nivedipa-MSFT** [comment]
@Abhiram219 - We are able to repro this issue and we have raised a bug for it. We will let you know once we get updates on it.

**Comment by Nivedipa-MSFT** [comment]
@Abhiram219 - This is by design. Teams client has our own designed font size system, not necessarily aligned with Adaptive Card Designer.
