### ISSUE TITLE
Generate a deep link to your app (Tab) added to a meeting

### ISSUE THREAD

**Issue by v-chetsh** [MicrosoftDocs/msteams-docs#4965]
As per current documentation, we do not have a way to "deep-link to your app (Tab) added to a meeting."
However we are able to achieve it using below format:
`https://teams.microsoft.com/l/entity/<meetingId>/<entityId>?context={"chatId": "<meetingId>","contextType":"chat"}`

**Example:** `https://teams.microsoft.com/l/entity/19%3ameeting_NDRmNzUzNjItYTYwNC00OWNhLWI4OTYtODUyNDI2NWY4MmE1%40XXXXXXXXXX.v2/Post-it?context={"chatId": "19%3ameeting_NDRmNzUzNjItYTYwNC00OWNhLWI4OTYtODUyNDI2NWY4MmE1%40XXXXXXXXXX.v2","contextType":"chat"}`

So, could you please help us to update the contents accordingly?
Doc section: https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links#deep-linking-to-your-tab

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45541337-ecd7-5cf6-cbe4-3f0d2f39aa79
* Version Independent ID: 6b4203f0-2844-06c9-eaa3-9cc03e6f76c0
* Content: [Create deep links - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links)
* Content Source: [msteams-platform/concepts/build-and-test/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/build-and-test/deep-links.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by ashishguptaiitb** [comment]
A gentle reminder @v-npaladugu

**Comment by v-npaladugu** [comment]
Hi @ashishguptaiitb, @v-chetsh 

We have received further inputs from Wajeed for the issue and we have incorporated them accordingly. Pending at Wajeed's end for approval
