### ISSUE TITLE
"Valid domain cannot use tunnel site" error

### ISSUE THREAD

**Issue by dafo** [MicrosoftDocs/msteams-docs#497]
Following this guide, I see the following error when trying to install my app in Teams for testing: "Valid domain cannot use tunnel site". I am using ngrok as described in the guide. So, I believe this is the reason for not being able to install the app. When I try to install it for a team, I see "Something went wrong." error and the app is not installed. Any thoughts on that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33cdb816-f2b6-31a4-0e4c-d730435d0a6b
* Version Independent ID: c111eaef-ac66-e245-b2bc-623c1801a7db
* Content: [Get started with App Studio and Node.js - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/get-started/get-started-nodejs-app-studio#feedback)
* Content Source: [msteams-platform/get-started/get-started-nodejs-app-studio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/get-started/get-started-nodejs-app-studio.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Wajeed-msft** [comment]
@dafo - Could you please confirm if [sideloading of external app](https://docs.microsoft.com/en-us/MicrosoftTeams/enable-features-office-365#external-apps) is enabled for your Tenant?

**Comment by dafo** [comment]
@Wajeed-msft - I have just contacted our admins and they confirmed it is disabled. Thank you! I knew it is enabled by default and didn't expect they've disabled it explicitly. Sorry about it!
