### ISSUE TITLE
Typos and error? in doc

### ISSUE THREAD

**Issue by aosolis** [MicrosoftDocs/msteams-docs#4971]
![image](https://user-images.githubusercontent.com/767208/148600608-fd09220f-96f0-4add-99b4-b6f636cd9a81.png)

Some text appears in the previous section, instead of the correct one.

Table says user can't send an emoji to bots, but it's easily verified that the TEams UI lets you send emoticons and emojis to bots.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afbc5b84-5be5-b5c4-30c0-58782a748a03
* Version Independent ID: ef6b8aee-52e7-f5d4-7dfa-8f34a1698330
* Content: [Messages in bot conversations - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-messages?branch=pr-en-us-4693&amp%3Btabs=dotnet&tabs=dotnet#status-code-responses)
* Content Source: [msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/bots/how-to/conversations/conversation-messages.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **anclear**

**Comment by Meghana-MSFT** [comment]
We are checking this issue, we will update you.

**Comment by v-chetsh** [comment]
Hello @surbhigupta12 - Could you please help us to update the contents?
