### ISSUE TITLE
Developer preview enables again if I disable it.

### ISSUE THREAD

**Issue by bplasmeijer** [MicrosoftDocs/msteams-docs#4975]
I did try the developer preview, and now I want to go back to the normal releases cycle.
If I disable (uncheck) the preview, it switches back to normal release.
After x time, preview is enabled again.

You have Microsoft Teams Version 1.4.00.32771 (64-bit). It was last updated on 07/12/2021.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 008da4e2-979e-c396-db28-4acf57deb530
* Version Independent ID: f1413f77-5eb3-e1fd-9235-d322d6e4eb6c
* Content: [Developer Preview - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/dev-preview/developer-preview-intro)
* Content Source: [msteams-platform/resources/dev-preview/developer-preview-intro.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/resources/dev-preview/developer-preview-intro.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Nivedipa-MSFT** [comment]
@bplasmeijer - Could you please share on Teams Web Client or Teams Desktop Client are you facing this issue?

**Comment by bplasmeijer** [comment]
Hello, 

![image](https://user-images.githubusercontent.com/116467/148920987-ffcdc2dc-0094-49a8-b4cc-a691813d7ac3.png)

**Comment by Nivedipa-MSFT** [comment]
@bplasmeijer - We have tried to repro your issue. But its working fine at our end.
Could you please share some repro steps and screenshots to repro the issue?
Also could you please update the Teams version and check again?

**Comment by Nivedipa-MSFT** [comment]
@bplasmeijer - Could you please confirm whether your issue resolved or are you still facing the issue?

**Comment by v-chetsh** [comment]
@bplasmeijer - Could you please share the screenshots for your issue, so that we can check it again from our end.

**Comment by v-chetsh** [comment]
@bplasmeijer - Could you please confirm whether your issue has resolved or still need any help here?

**Comment by bplasmeijer** [comment]
The preview is back. 

You have Microsoft Teams Version 1.5.00.3276 (64-bit). It was last updated on 07/02/2022.

please re-open

**Comment by Nivedipa-MSFT** [comment]
@bplasmeijer - We have tested on Microsoft Desktop Teams Version 1.5.00.3856. We are not able to repro the issue. Could you please share in which Ring your Teams is in?

**Comment by bplasmeijer** [comment]
Hello, where can I find my teams ring?

**Comment by Nivedipa-MSFT** [comment]
@bplasmeijer - Click on 3 dots on upper right corner of Teams. Then in Version you can find Teams Ring.
You can refer below image.

![TeamsRing](https://user-images.githubusercontent.com/92150070/153550500-d21ec7bf-ad11-4955-b708-597cf8f18e9f.png)

**Comment by bplasmeijer** [comment]
The version only opens the grey header and displays the team version.
![image](https://user-images.githubusercontent.com/116467/153551065-3ea03dfa-6c77-42b0-806c-3c952c0bedf6.png)

**Comment by Nivedipa-MSFT** [comment]
@bplasmeijer - Is your Teams update policy is set to be Follow Office Preview?
Please check by following steps.
1.Sign in to the [Microsoft Teams admin center](https://admin.teams.microsoft.com/).
2.Select Teams > Teams Update policies.
3.Select an existing policy to open Update policy.
4.Select the setting for Show preview features.


![image](https://user-images.githubusercontent.com/92150070/153564216-3c15294a-917a-434b-9c52-b489ab1be73c.png)

**Comment by Nivedipa-MSFT** [comment]
@bplasmeijer - Could you please confirm is your issue resolved or still looking for any help?

**Comment by bplasmeijer** [comment]
I need to check with IT. Give me a moment to validate.
