### ISSUE TITLE
Teams iOS app can't call XXX.XXX.XXXX format numbers

### ISSUE THREAD

**Issue by lwolf-sagetechs** [MicrosoftDocs/msteams-docs#498]
In Active Directory, we stored user phone numbers in the format XXX.XXX.XXXX
In the iOS Teams app, when you pull up a contact and try to call a phone number in this format, it asks if you want to call XXX.  It only seems to find the first three digits of the number when you use dots to separate the sections.  If you use dashes to separate like XXX-XXX-XXXX or international format like +1 XXXXXXXXXX, the app can make the call with no problem.

This seems to be a bug to me.

**Comment by Wajeed-msft** [comment]
Thanks for reporting. We have filed a bug for this.

**Comment by nuevocampo** [comment]
I am looking into this. It seems phone numbers formatted with standard periods are detected correctly. Any chance the numbers in this particular case are being separated by some non-standard symbol?

**Comment by lwolf-sagetechs** [comment]
Hello,
See attached screenshots. We are using the standard period character as a separator, ascii 46, in our phone numbers.

As you can see on the first picture, Caleb’s desk phone is 717.653.3399
When you try to call that number from the Teams app with that contact information, it only grabs 717 and not the rest of the number.

Thanks for looking into this!
Leonard

[cid:sage_37818263-3e8f-4deb-acb2-07ec993e385c.png]

Leonard Wolf
IT Helpdesk Coordinator
Sage Technology Solutions, Inc.
1040 West Main Street | Mount Joy, PA 17552
Direct | 717.653.3340
website<https://sagetechs.com/> | email<mailto:lwolf@sagetechs.com> | service<https://sagetechs.com/what-we-do/service-support/service-request-form>  24hr (717) 653-3300


This message is intended only for official business use by the individual or entity to which it is addressed.
This message was sent from my mobile device.

On Mar 19, 2019, at 3:47 PM, Sten Uusvali <notifications@github.com<mailto:notifications@github.com>> wrote:

I am looking into this. It seems phone numbers formatted with standard periods are detected correctly. Any chance the numbers in this particular case are being separated by some non-standard symbol?

**Comment by lwolf-sagetechs** [comment]
I tested this again today and it's still broken on my iPhone in the iOS Teams app.
If there is a Teams contact with a phone number in the xxx.xxx.xxxx format and I try, from the Teams contact, to call the phone number for that contact, it just gets the first three digits of the number.

Apple seems to work around this problem by converting any/every contact phone number from xxx.xxx.xxxx to (xxx) xxx-xxxx. I can paste the xxx.xxx.xxxx number into a contact or even into the number on my iPhone dialer, but it automatically/immediately converts it to (xxx) xxx-xxxx.

Let me know if there's any more progress on this issue from your side.

Thanks!

**Comment by Wajeed-msft** [comment]
The fix will be available in 2nd Week of July.
