### ISSUE TITLE
HTML script tags for CDN and npm show outdated versions

### ISSUE THREAD

**Issue by erinha** [MicrosoftDocs/msteams-docs#4993]
The HTML script tags for CDN and npm show outdated versions. They should match the versions in the [teams-js 2.0 npm README](https://www.npmjs.com/package/@microsoft/teams-js/v/2.0.0-beta.2) (even if not the latest @next release, it should be a `2.0.0-beta.x` version):

```HTML
<!-- Microsoft Teams JavaScript API (via CDN) -->
<script
  src="https://res.cdn.office.net/teams-js/2.0.0-beta.2/js/MicrosoftTeams.min.js"
  integrity="sha384-Q2Z9S56exI6Oz/ThvYaV0SUn8j4HwS8BveGPmuwLXe4CvCUEGlL80qSzHMnvGqee"
  crossorigin="anonymous"
></script>

<!-- Microsoft Teams JavaScript API (via npm) -->
<script src="node_modules/@microsoft/teams-js@2.0.0-beta.2/dist/MicrosoftTeams.min.js"></script>

<!-- Microsoft Teams JavaScript API (via local) -->
<script src="MicrosoftTeams.min.js"></script> 
```

The page currently shows URLs for version 1.5.2.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5560ca3-3e38-c8b0-7e77-98c7dae46b25
* Version Independent ID: d40f7e38-0737-545b-d5bd-59eb1be68d82
* Content: [Microsoft Teams client SDK v2 Preview - Teams](https://docs.microsoft.com/en-us/javascript/api/overview/msteams-client?view=msteams-client-js-beta)
* Content Source: [nodejs/teams-js2/overview/msteams-client.md](https://github.com/OfficeDev/msteams-client-docs-ref-typescript/blob/live/nodejs/teams-js2/overview/msteams-client.md)
* Product: **msteams**
* GitHub Login: @charlesprakash
* Microsoft Alias: **o365devx**

**Comment by Nivedipa-MSFT** [comment]
@erinha - In the below document its already mention here

> **Do not copy/paste these <script src=... URLs from this page; they refer to a specific version of the SDK. To get the <script src=...></script> markup for the latest version, always go to https://www.npmjs.com/package/@microsoft/teams-js.**
> [Microsoft Teams client SDK v2 Preview-Teams](https://docs.microsoft.com/en-us/javascript/api/overview/msteams-client?view=msteams-client-js-beta#using-the-sdk)

![image](https://user-images.githubusercontent.com/92150070/149274665-74a512aa-21a6-4ff3-9fd5-cbbb9ccea048.png)

**Comment by v-chetsh** [comment]
> @erinha - In the below document its already mentioned that
> 
> > **Do not copy/paste these <script src=... URLs from this page; they refer to a specific version of the SDK. To get the <script src=...></script> markup for the latest version, always go to https://www.npmjs.com/package/@microsoft/teams-js.**
> > [Microsoft Teams client SDK v2 Preview-Teams](https://docs.microsoft.com/en-us/javascript/api/overview/msteams-client?view=msteams-client-js-beta#using-the-sdk)
> 
> ![image](https://user-images.githubusercontent.com/92150070/149274665-74a512aa-21a6-4ff3-9fd5-cbbb9ccea048.png)

@erinha - Could you please confirm if above provided comment resolved your query or still need any help?

**Comment by erinha** [comment]
Because the SDK docs are different for Teams JS SDK v1 and v2 (beta), I think it's important that the code snippet here reflect that. Despite that note, I would surmise that developers will copy and paste and at least they'd get a v2 build, even if it's outdated.

I would still like to see the code snippet updated please. Thanks.

**Comment by v-chetsh** [comment]
@erinha - Thanks for your valuable input.
@surbhigupta12 - Could you please help us here to update the content link?

**Comment by erikadoyle** [comment]
> @erinha - Thanks for your valuable input. @surbhigupta12 - Could you please help us here to update the content link?

I'll take care of it--please assign to me. Thanks!

**Comment by v-chetsh** [comment]
@erikadoyle - Thanks for conforming us.
Please let us know once the PR is merged, so that we can close this issue as well?
