### ISSUE TITLE
Can't call from Chrome in web app

### ISSUE THREAD

**Issue by tobmcv** [MicrosoftDocs/msteams-docs#500]
Using Teams in Chrome I cannot call team-members. Here's the error message. 

```
Try a different browser
This feature isn't available yet for your browser. Try the web app with Microsoft Edge or Google Chrome, or switch to the desktop app.
```

Tested in both Chrome version 72 and version 73.0.3683.75 on Mac OSX version 10.14.3.
My user has a guest account on the Teams app. 

Is this a bug or is the feature not available for Chrome yet? Is the issue related to my guest account? 

![Screenshot 2019-03-15 at 09 09 24](https://user-images.githubusercontent.com/8222215/54420629-cf9e1680-470a-11e9-8f24-69d5119494d9.png)

**Comment by billbliss** [comment]
The error message is wrong, but the feature actually isn't yet available in Chrome. It should work in Chrome in the very near future.

**Comment by Wajeed-msft** [comment]
We are tracking this feature. Closing this issue from documentation page.
