### ISSUE TITLE
Different X-Frame-Options and Content-Security-Policy HTTP response headers?

### ISSUE THREAD

**Issue by Benjiiim** [MicrosoftDocs/msteams-docs#5001]
We can read on the page different values for header Content-Security-Policy (for new browsers) and header X-Frame-Options (for old browsers).

The domains required for Content-Security-Policy are teams.microsoft.com *.teams.microsoft.com *.skype.com but the one required for X-Frame-Options is https://teams.microsoft.com/.

Is that expected?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b159fe6e-33d0-6174-f3c3-68aaec79ee1b
* Version Independent ID: 7037e9c7-f501-5b70-8acf-1f004a06289b
* Content: [Prerequisites - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/tab-requirements)
* Content Source: [msteams-platform/tabs/how-to/tab-requirements.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tabs/how-to/tab-requirements.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by v-chetsh** [comment]
Hello @Benjiiim - We will also check on it from our end and let you know.

**Comment by Prasad-MSFT** [comment]
You can see all the origins that our App SDK expects to be run in here:
https://github.com/OfficeDev/microsoft-teams-library-js/blob/d373d057cb7d7cb01f0ba65cdccff5c3ad561f8f/src/internal/constants.ts#L64
If the developer is just targeting Teams then the only origins they need to list in CSP frame-ancestors are:	
teams.microsoft.com --> This is the domain that serves most of our customers today	
gov.teams.microsoft.us --> This is for GCCH customers; if they don't have any then they can skip it	
dod.teams.microsoft.us --> This is for DoD customers; if they don't have any then they can skip it	
local.teams.office.com --> This is what our engineers use during development; it's not required but very helpful if we ever need to investigate issues
Additionally, it is now possible to extend a Teams App to run in other M365 hubs like Outlook and Office.com. If the developer wants to do that, there are some additional frame ancestors they will want to enable as documented here:
https://docs.microsoft.com/en-us/microsoftteams/platform/m365-apps/extend-m365-teams-personal-tab?tabs=manifest-teams-toolkit#configure-content-security-policy-headers
