### ISSUE TITLE
[MS Teams] [Adaptive Cards] Adaptive Card meaning full text sentence are breaking into unreadable format. 

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#5003]
Copied bug from: https://github.com/microsoft/AdaptiveCards/issues/6881 

**Details from original post:**
## Platform
* Web ( MsTeams Web http://teams.microsoft.com )
* Microsoft Teams Version 1.4.00.32771 (64-bit). It was last updated on 12/15/2021.

### Programing Language
* C#
### Channel
* MS Teams
### Adaptive Card Version
1.2
## Issue

The following screenshot breakdown the proper sentence into unreadable format like "Personal" it showing as "Per" in the first line and then remaining words are showing in the next line. Is there any solution for this issue ?

![image](https://user-images.githubusercontent.com/8437883/148897307-e96b1c0b-5e07-4324-8384-fd66d3a3f73b.png)

### C# Code
`
public static Attachment DisplayFAQResponse(string buttonTitleForImage,string FaqMessage, string FaqAnswer, string RequestId = null, List<ImageUrl>ImageUrl= null )
        {
            var faqResponseCard = new AdaptiveCard("1.2");

            var msteamsProp = new MsTeamsObject()
            {
                Width = "Full",
                Wrap = true,
            };
            SerializableDictionary<string, object> msteams = new SerializableDictionary<string, object>();

            msteams.Add("msteams", msteamsProp);

            faqResponseCard.AdditionalProperties = msteams;

            faqResponseCard.Body.Add(new AdaptiveTextBlock()
            {
                AdditionalProperties = msteams,
                Text = FaqMessage,
                Separator = true,
                Spacing = AdaptiveSpacing.ExtraLarge,
                Wrap = true
            });

            faqResponseCard.Body.Add(new AdaptiveTextBlock()
            {
                AdditionalProperties = msteams,
                Text = FaqAnswer,
                Spacing = AdaptiveSpacing.Default,
                Wrap = true,
                Separator = true
            });
            
            

            return new Attachment()
            {
                ContentType = AdaptiveCard.ContentType,
                Content = faqResponseCard
            };
        }`

---
#### Document Details

⚠ *Do not edit this section.It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Cards reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **surbhigupta12**

**Comment by Meghana-MSFT** [comment]
@rajeeshmenoth - Could you please share the adaptive card JSON?

**Comment by rajeeshmenoth** [comment]
@Meghana-MSFT I have posted the similar question in SO as well, here [SO thread](https://stackoverflow.com/questions/70700121/the-adaptive-card-faq-sentence-is-split-into-an-unreadable-format-in-ms-team-cha) I have given the detail explanation.

**Comment by rajeeshmenoth** [comment]
Hi @Meghana-MSFT ,

You are right, Before posting this thread here is the similar approach I have verified in Adaptive Card Designer and it's working as expected. But we are using C# code for our existing application and as of now, we can't change those C# objects to JSON format. So please verify the C# code that I have posted here and add those titles as well then you will get the same issue that I have mentioned in this thread.

**Comment by rajeeshmenoth** [comment]
> We have used the below JSON similar to the template you shared on Stackoverflow. We see it is rendering fine at our end. Attaching JSON and screenshot below.
> 
> ```
> {
>   "type": "AdaptiveCard",
>   "body": [
>     {
>       "type": "TextBlock",
>       "size": "Medium",
>       "wrap": true,
>       "text": "Found an answer for you in **Global BA Systems & Processes ➡️ Personal Data**"
>     },
>     {
>       "type": "TextBlock",
>       "size": "Medium",
>       "wrap": true,
>       "text": "You need to raise a ticket in support@abcdefghi under category Personal Data Change Request, providing new home address"
>     }
>   ],
>     "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
>     "version": "1.0"
>   }
> ```
> 
> ![image](https://user-images.githubusercontent.com/81138249/149552063-0fa66ef5-5213-4ddf-bc39-1a4db98c7463.png)

I have verified this code and it's working because you are using **"Personal Data Change Request"** as a normal text in your solution instead of a **hyperlink**. Also, our text size is `default` instead of a `medium` and Adaptive card version you can consider as **1.2**, So please verify the below JSON then you will get the same result that I have attachment in the screenshot. First, I thought the issue is related to our C# object but JSON format also gave the same result and please have a look at it.
`{
  "type": "AdaptiveCard",
  "body": [
    {
      "type": "TextBlock",
      "size": "Medium",
      "wrap": true,
      "text": "Found an answer for you in **Global BA Systems & Processes ➡️ Personal Data**"
    },
    {
      "type": "TextBlock",
      "size": "Medium",
      "wrap": true,
      "text": "You need to raise a ticket in support@abcdefghi under category [Personal Data Change Request](https://abcdefghi.abcdefg-abc.com/supportxaabcdefghi?id=sc_ball_item&sys_id=ds123ffedbf68300da04fe9b0c13467b), providing new home address."
    }
  ],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.0"
  }`
![image](https://user-images.githubusercontent.com/8437883/149719125-0c15d217-8067-4f2f-a148-322b32335e08.png)

**Comment by HunaidHanfee-MSFT** [comment]
Hello @rajeeshmenoth,
Tried with App studio again by pasting JSON shared by you and find no issue. 
![image](https://user-images.githubusercontent.com/64194049/149727393-3e2182a7-e320-47cb-944f-453b90e4e81d.png)


My Teams Client version is  1.4.00.35514 (64-bit)-E. It was last updated on 06-01-2022. 
You can check for updates as well - By clicking on the three dots **...** on the left of your profile
![image](https://user-images.githubusercontent.com/64194049/149727338-74926105-e778-4b9d-8f2c-607f78a724a1.png)

**Comment by Meghana-MSFT** [comment]
I have updated the JSON as you have mentioned. It is working fine in both Desktop and web client.

![image](https://user-images.githubusercontent.com/81138249/150079142-d1e07f9c-47df-4f70-927a-af6137a6a1a4.png)
