### ISSUE TITLE
[MS Teams] [Adaptive Cards]  MS Teams adaptive cards won’t wrap text in Action Button

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#5004]
Copied bug from: https://github.com/microsoft/AdaptiveCards/issues/6880 

**Details from original post:**
## Platform
* Web ( MsTeams Web http://teams.microsoft.com )
* Microsoft Teams Version 1.4.00.32771 (64-bit). It was last updated on 12/15/2021.
## Programing Language
* C#
## Channel 
* MS Teams
## Adaptive Card Version
* 1.2
## Issue

I’m having an issue where buttons and actions in ms teams adaptive cards won’t wrap text. Adaptive card text are overflow in action button ( Botframework V4). We have tried `"Wrap: true || false"` but still getting the same issue. looking for c# adaptive card code for the following fix.

## Screenshot:

![image](https://user-images.githubusercontent.com/8437883/148896600-e7d8f1df-b92f-4b43-9f40-e90ef6a7c37f.png)

## C# Code

` public static Attachment CreateChoiceMenu(string channelType, string text, List<string> buttons, string subCategory = null)
         {
            var menuCard = new AdaptiveCard("1.2");

            if(!string.IsNullOrEmpty(subCategory))
            {
                menuCard.Body.Add(new AdaptiveTextBlock()
                {
                    Text = subCategory,
                    Size = AdaptiveTextSize.Large,
                    Wrap = true,
                });
            }

            menuCard.Body.Add(new AdaptiveTextBlock()
            {
                Text = text,
                Wrap = true,
            });

            foreach (var button in buttons)
            {
                var columns = new AdaptiveColumnSet();
                menuCard.Body.Add(columns);

                var userCategory = new AdaptiveColumn();
                columns.Columns.Add(userCategory);

                var actionType = new AdaptiveActionSet();
                userCategory.Items.Add(actionType);

                var submitAction = new AdaptiveSubmitAction()
                {
                    Title = button,
                    Id = button
                };

                if (channelType == Channels.Msteams)
                {
                    submitAction.Data = new AdaptiveCardDataObjectForTeams()
                    {
                        MsTeams = new MsTeamsObject()
                        {
                            Type = ActionTypes.MessageBack,
                            DisplayText = button,
                            Text = button
                        }
                    };
                }
                else
                {
                    submitAction.Data = button;
                }

                actionType.Actions.Add(submitAction);
            }

            return new Attachment()
            {
                ContentType = AdaptiveCard.ContentType,
                Content = menuCard
            };
        }
`---
#### Document Details

⚠ *Do not edit this section.It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Cards reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **surbhigupta12**

**Comment by Nivedipa-MSFT** [comment]
@rajeeshmenoth - We are investigating your query. We will get back to you once we have any update.

**Comment by rajeeshmenoth** [comment]
Thank you @Nivedipa-MSFT, I have posted the similar question in SO as well because last 2 days we are not getting any response from github.

**Note:** Adaptive card we are constructing using C# code instead of JSON file. In SO I have given the template title details and here it is [SO thread](https://stackoverflow.com/questions/70699719/adaptive-card-action-button-text-ui-trimmed-inside-the-ms-team-channel/70709185#70709185).

**Comment by Nivedipa-MSFT** [comment]
@rajeeshmenoth - **Cards support formatting in the text property only, not in the title or subtitle properties.**  
Its mentioned in following document : [Format cards in Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?tabs=adaptive-md%2Cconnector-html)
The Action Button text is in title property so we cannot do any formatting for it.
**There is no way to wrap text in Action Button.**

**Comment by rajeeshmenoth** [comment]
@Nivedipa-MSFT Thank you for the confirmation.

**Comment by Prasad-MSFT** [comment]
We are closing this issue for now. Please feel free to reopen if required.
