### ISSUE TITLE
TeamsJs Function for triggering notification bar

### ISSUE THREAD

**Issue by AnthonyPhan** [MicrosoftDocs/msteams-docs#5007]
Naively within teams there is a notification bar that is used to send messages to the user. Is there a function available within TeamsJs to allow my application trigger these notifications with my own custom message? The closest thing I can find in the documentation is the sendMessageToParent function. 

![image](https://user-images.githubusercontent.com/12785492/149461070-e6dcd912-3b46-45fa-b07f-13d7259d8f29.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f629e5c0-0ebe-7beb-8c10-a26fda0b74b2
* Version Independent ID: a1e928cd-ddf1-d134-70f9-34cc236b38db
* Content: [@microsoft/teams-js package - Teams](https://docs.microsoft.com/en-us/javascript/api/@microsoft/teams-js/?view=msteams-client-js-latest)
* Content Source: [nodejs/docs-ref-autogen/@microsoft/teams-js/index.yml](https://github.com/OfficeDev/msteams-client-docs-ref-typescript/blob/live/nodejs/docs-ref-autogen/@microsoft/teams-js/index.yml)
* Product: **msteams**
* GitHub Login: @charlesprakash
* Microsoft Alias: **o365devx**

**Comment by Nivedipa-MSFT** [comment]
@AnthonyPhan - We are investigating your query. We will get back to you once we have any update.

**Comment by Nivedipa-MSFT** [comment]
@AnthonyPhan - Currently there is no TeamsJs Function available for triggering notification bar.

**Comment by v-chetsh** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.
