### ISSUE TITLE
Two identical devices appear in Dashboard/Manage devices. No option to delete.

### ISSUE THREAD

**Issue by MSMITCH** [MicrosoftDocs/msteams-docs#501]
Two exact identical devices appear in Dashboard/Manage devices. It cannot be removed because there is no delete button.

**Comment by Wajeed-msft** [comment]
Could you please share screenshot for this?

**Comment by MSMITCH** [comment]
I was working with a user that had this issue, unfortunately, I do not have a screenshot. We also submitted a uservoice entry where another user was experiencing this issue. 

https://microsoftteams.uservoice.com/forums/555103-public/suggestions/37119724-add-option-to-delete-a-device-in-dashboard-manag

**Comment by Abhijit-MSFT** [comment]
Is it something related to Teams functionality?

**Comment by Wajeed-msft** [comment]
Please re-open with requested details.
