### ISSUE TITLE
Teams Webhooks connector

### ISSUE THREAD

**Issue by robarismail97** [MicrosoftDocs/msteams-docs#5010]
The new design includes tenant-specific domain for webhook so that tenant can inspect SNI (Server Name Indication) during TLS negotiation to prevent connection to other tenant’s webhook within their own perimeter.

The endpoint is updated to -
https://[tenant_name].webhook.office.com/webhook/[external_object_id]@[tenant_id]/[connector_type]/[instance_id]/[owner_object_id]

Webhook service validates [tenant_name] and [tenant_id] are pointing to the same tenant.

Let me know if you have any query, else we will close the issue.
Thanks

_Originally posted by @HunaidHanfee-MSFT in https://github.com/MicrosoftDocs/msteams-docs/issues/4522#issuecomment-967325844_

________________________________________________________________________________________________

How was the old version? How did the request look like?

**Comment by Nivedipa-MSFT** [comment]
@robarismail97 - Could you please elaborate on your ask?

**Comment by robarismail97** [comment]
I would like to know what releases there has been with connectors, incoming and outgoing webhooks. I know that company's usually reject the use of webhooks for teams because lack of security restrictions. Now they have updated the webhooks so they are tenant specific.

NEW REQUEST URL: "https://[tenant_name].webhook.office.com/webhook/[external_object_id]@[tenant_id]/[connector_type]/[instance_id]/[owner_object_id]"

How was the old?

**Comment by v-chetsh** [comment]
@robarismail97 - In previous URL's below highlighted things (tenant_name, tenant_id etc.) was not present.
The endpoint is updated to -
https://**[tenant_name]**.webhook.office.com/webhook/[external_object_id]@**[tenant_id]**/[connector_type]/[instance_id]/[owner_object_id]

**Comment by Nivedipa-MSFT** [comment]
@robarismail97 - Could you please confirm is your issue resolved or still looking for any help?

**Comment by robarismail97** [comment]
I have som more questions on this.

Is it something more that has changed recently with the incoming Webhook app?

The concerns enterprises had with it earlier was mostly related to Governance and the lack of monitoring/control.

A few examples:

- Not being able to see what webhooks that exist in the enterprise environment
- No AV scanning of what is sent over the webhooks.
- No logging of what is sent over the webhooks
- No way to centrally control who can create webhooks
- The possibility to include possible malicious components in the messages (pictures/attachments/links)

Has some of this concerns been overcome with a newer version of webhooks?

**Comment by v-chetsh** [comment]
@robarismail97 -  We are checking on it and let you know the updates.

**Comment by Nivedipa-MSFT** [comment]
@robarismail97 - The following concern will be overcome with a newer version of webhooks.
- The possibility to include possible malicious components in the messages (pictures/attachments/links)
