### ISSUE TITLE
[Teams Developer Portal] Cannot use environment variable as Bot ID

### ISSUE THREAD

**Issue by xelossan** [MicrosoftDocs/msteams-docs#5011]
When creating Teams App manifest using the Developer Portal, when I try to use environment variable as bot ID (so each environment can have a separate bot), it fails with the following error when trying to save changes:
```"Error converting value \"{{variable-name}}\" to type 'System.Nullable`1[System.Guid]'. Path 'botId', line 1, position 31."```

![image](https://user-images.githubusercontent.com/1189969/149497997-43b9f789-e115-4285-8bbb-9875b4b9494f.png)

**Comment by Prasad-MSFT** [comment]
@xelossan -Environment variable is not designed to be used on GUID field. Teams App Developer Portal can not use environment variable as bot ID. This is expected behaviour. You can directly use GUID value instead of environment variable in bot ID field.
