### ISSUE TITLE
Page does not mention how long a security token is valid for.

### ISSUE THREAD

**Issue by DmitriyVdE** [MicrosoftDocs/msteams-docs#5012]
I can't find how long a security token is valid for anywhere within the docs. A good place for this would be here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb9c5bd5-1ac6-dcc8-4ed6-d6aad2432776
* Version Independent ID: 43e90995-bba4-86b6-1f1c-ab749e546a4b
* Content: [Create an Outgoing Webhook - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-outgoing-webhook?tabs=urljsonpayload%2Cdotnet)
* Content Source: [msteams-platform/webhooks-and-connectors/how-to/add-outgoing-webhook.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/webhooks-and-connectors/how-to/add-outgoing-webhook.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Nivedipa-MSFT** [comment]
@DmitriyVdE - We are checking it with engineering team and let you know the updates.

**Comment by Nivedipa-MSFT** [comment]
@DmitriyVdE - HMAC security token does not expire, it is unique per configuration.
Redirecting to documentation team to update the document
@surbhigupta12 - HMAC security token is not mentioned in following document.

**Comment by Nivedipa-MSFT** [comment]
@DmitriyVdE - HMAC security token does not expire, it is unique per configuration.

**Comment by Nivedipa-MSFT** [comment]
Redirecting to documentation team to update the document
@surbhigupta12 - Could you please update the following document as HMAC security token expiration details is not mentioned in following document 
[Create an Outgoing Webhook](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-outgoing-webhook?tabs=urljsonpayload%2Cdotnet) 
Content to Add in doc: **HMAC security token does not expire, it is unique per configuration.**

**Comment by v-chetsh** [comment]
@surbhigupta12 - Could you please update the following document as HMAC security token expiration details is not mentioned in following document 
[Create an Outgoing Webhook](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-outgoing-webhook?tabs=urljsonpayload%2Cdotnet) 

Content to Add in doc: **HMAC security token does not expire, it is unique per configuration.*

**Comment by Wajeed-msft** [comment]
@DmitriyVdE - Thank you so much for taking time to report this. We have [updated docs](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-outgoing-webhook?tabs=urljsonpayload%2Cdotnet#create-outgoing-webhooks)  and it's live right now. 

<img width="484" alt="image" src="https://user-images.githubusercontent.com/31851992/152282828-6ba723cf-364f-4e71-babd-0b5435b153fa.png">

Could you please help to share your feedback around MS Learn module for MS-600? Link to page, images would help.
