### ISSUE TITLE
Grammatical correction in doc

### ISSUE THREAD

**Issue by timcappalli** [MicrosoftDocs/msteams-docs#5014]
Original text from https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-aad-sso#known-limitations (first paragraph)
> "To get the permissions (scopes) needed to make a Graph call, SSO solutions must implement a custom web service to exchange the token got from the Teams JavaScript SDK for a token that includes the needed scopes."

**s/got/received**
or
**s/got/acquired**

proposed new options:
> "To get the permissions (scopes) needed to make a Graph call, SSO solutions must implement a custom web service to exchange the token ( received || acquired ) from the Teams JavaScript SDK for a token that includes the needed scopes."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52221dd3-95ec-96b9-1da8-9478527c2602
* Version Independent ID: 32e9c2d8-733d-0865-2ea3-727d8684a10d
* Content: [Single sign-on support for tabs - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-aad-sso#get-an-access-token-with-graph-permissions)
* Content Source: [msteams-platform/tabs/how-to/authentication/auth-aad-sso.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tabs/how-to/authentication/auth-aad-sso.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Prasad-MSFT** [comment]
Redirecting to doc team to update the page accordingly
