### ISSUE TITLE
How to determine file size of incoming file before downloading?

### ISSUE THREAD

**Issue by GauravES** [MicrosoftDocs/msteams-docs#5028]
[Enter feedback here]

It's not clear from the sample flow how the size of the incoming attachment (that is sought to be downloaded) will come from ?  The provided JSON snippet  does not have this size.  However, when the consent card is sent to the user in the example, the file size is sent?   How will the bot know the size of the file?   

Teams now permits files of up to 250GB. Without a way to determine the file size before downloading,  , this could easily swamp the bot and lead to denial of service.

To clarify, The message activity example does not include the size (while the consent card JSON shows the file size hard coded)

`{
  "attachments": [{
    "contentType": "application/vnd.microsoft.teams.file.download.info",
    "contentUrl": "https://contoso.sharepoint.com/personal/johnadams_contoso_com/Documents/Applications/file_example.txt",
    "name": "file_example.txt",
    "content": {
      "downloadUrl" : "https://download.link",
      "uniqueId": "1150D938-8870-4044-9F2C-5BBDEBA70C9D",
      "fileType": "txt",
      "etag": "123"
    }
  }]
}`
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b69599c-1da4-8689-fd0c-4e4d8a348496
* Version Independent ID: 872fa9a2-0543-4a94-5416-6e6dc389f0d0
* Content: [Sending and receiving files from a bot - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bots-files)
* Content Source: [msteams-platform/resources/bot-v3/bots-files.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/resources/bot-v3/bots-files.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by HunaidHanfee-MSFT** [comment]
Hello @GauravES,
I am looking into it. I will update you soon. 

Thanks

**Comment by Prasad-MSFT** [comment]
@GauravES - When we download the file, we generally get the response having content and size. But before even downloading, there doesn't seem to be any way to get it.

**Comment by GauravES** [comment]
This was tagged as needing Author feedback.  What information can I provide?   This seems to be missing functionality?

**Comment by Prasad-MSFT** [comment]
Removed the tag
