### ISSUE TITLE
how-to for : "The Web App API endpoint notifies the bot.

### ISSUE THREAD

**Issue by pkaushik23** [MicrosoftDocs/msteams-docs#503]
Hello, is there a documentation or example which shows how we can do  "The Web App API endpoint notifies the bot. as mentioned in the step 4 above. 

I am assuming, we need to post something to /api/messages by utilizing the appId and appPassword.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1afe98ca-c7c9-c56c-9085-58408bfde863
* Version Independent ID: 9e0c7810-b154-2d1a-67a9-85a3edc54ac6
* Content: [Microsoft Teams Turn Conversation into Action - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/scenarios/lob-marketing-scenario)
* Content Source: [msteams-platform/scenarios/lob-marketing-scenario.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/scenarios/lob-marketing-scenario.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by billbliss** [comment]
The documentation for how to conduct bot conversations starts here: https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/bots/bot-conversations/bots-conversations

**Comment by pkaushik23** [comment]
Thank you @billbliss for your reply, but it was very generic. I have gone through the documentation but failing to locate which sub section can help me with solve "How to notify a bot from a web app api", As noted earlier in my original question, does it mean doing a POST to /api/messages by utilizing the appId and appPassword.
Thanks,

**Comment by pkaushik23** [comment]
I am using directline api endpoints like following, please tell me if that is not the most efficient way. 
https://directline.botframework.com/v3/directline/tokens/generate
https://directline.botframework.com/v3/directline/conversations
https://directline.botframework.com/v3/directline/conversations/{{conv_id}}/activities

**Comment by Wajeed-msft** [comment]
Please re-open if you still have any queries related to proactive messaging. Please check the sample code for [proactive message](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/bots/bot-conversations/bots-conv-proactive#using-net).
