### ISSUE TITLE
Code snippets for device permissions API

### ISSUE THREAD

**Issue by Prithvi-MSFT** [MicrosoftDocs/msteams-docs#5031]
Hi team,
Please  add code snippets for following device permissions API

1) Capture image (captureImage())

```
        function captureImage() {
            microsoftTeams.media.captureImage((error, files) => {
                // If there's any error, an alert shows the error message/code
                if (error) {
                    if (error.message) {
                        alert(" ErrorCode: " + error.errorCode + error.message);
                    } else {
                        alert(" ErrorCode: " + error.errorCode);
                    }
                } else if (files) {
                    image = files[0].content;
                    // Adding this image string in src attr of image tag will display the image on web page.
                    let imageString = "data:" + item.mimeType + ";base64," + image;
                }
            });
        } 
```
2) Select Media for image (selectMedia())

        function selectMedia() {
            microsoftTeams.media.selectMedia(mediaInput, (error, attachments) => {
                // If there's any error, an alert shows the error message/code
                if (error) {
                    if (error.message) {
                        alert(" ErrorCode: " + error.errorCode + error.message);
                    } else {
                        alert(" ErrorCode: " + error.errorCode);
                    }
                } else if (attachments) {
                    // creating image array which contains image string for all attached images. 
                    const imageArray = attachments.map((item, index) => {
                        return ("data:" + item.mimeType + ";base64," + item.preview)
                    })
                }
            });
        } 

3) Select Media for audio (selectMedia())

        function selectMedia() {
            microsoftTeams.media.selectMedia({ maxMediaCount: 1, mediaType: microsoftTeams.media.MediaType.Audio }, (error: microsoftTeams.SdkError, attachments: microsoftTeams.media.Media[]) => {
                // If there's any error, an alert shows the error message/code
                if (error) {
                    if (error.message) {
                        alert(" ErrorCode: " + error.errorCode + error.message);
                    } else {
                        alert(" ErrorCode: " + error.errorCode);
                    }
                }

                if (attachments) {
                    // taking the first attachment  
                    let audioResult = attachments[0];

                    // setting audio string which can be used in Video tag
                    let audioData = "data:" + audioResult.mimeType + ";base64," + audioResult.preview
                }
            });
        }

4) Get location (getLocation())

        function getLocation() {
            microsoftTeams.location.getLocation({ allowChooseLocation: true, showMap: true }, (error: microsoftTeams.SdkError, location: microsoftTeams.location.Location) => {
                let currentLocation = JSON.stringify(location);
            });
        } 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19804dba-009f-2eb1-cc7f-1e0fabbebb6b
* Version Independent ID: a9373e78-b3c9-7182-d253-5ac8d8988936
* Content: [Request device permissions for your Microsoft Teams app - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?tabs=mobile#code-sample)
* Content Source: [msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/device-capabilities/native-device-permissions.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by sayali-MSFT** [comment]
@surbhigupta12 -  Could you please help us to update the contents?
