### ISSUE TITLE
C# and Nodejs code snippets for proactive messaging

### ISSUE THREAD

**Issue by Prithvi-MSFT** [MicrosoftDocs/msteams-docs#5033]
Hi team,
Please add C# and node js code snippers for sending proactive messages.
Add the code snippets in [this ](https://docs.microsoft.com/en-us/microsoftteams/platform/graph-api/proactive-bots-and-messages/graph-proactive-bots-and-messages?context=graph/context#send-proactive-messages)section of the document

Code snippets

C#

```
public async Task<int> SendNotificationToAllUsersAsync(ITurnContext<IMessageActivity> turnContext, CancellationToken cancellationToken)
        {
            int msgSentCount = 0;
 
            // Send notification to all the members
            foreach (var conversationReference in _conversationReferences.Values)
            {
                await turnContext.Adapter.ContinueConversationAsync(_configuration["MicrosoftAppId"], conversationReference, BotCallback, cancellationToken);
                msgSentCount++;
            }
 
            return msgSentCount;
        }

private async Task BotCallback(ITurnContext turnContext, CancellationToken cancellationToken)
        {
            await turnContext.SendActivityAsync("Proactive hello.");
        }
```
 Node js

    async SendNotificationToAllUsersAsync(context) {
        const TeamMembers = await TeamsInfo.getPagedMembers(context);
        let Sent_msg_Cout = TeamMembers.members.length;
        TeamMembers.members.map(async member => {
            const ref = TurnContext.getConversationReference(context.activity);
            ref.user = member;
            await context.adapter.createConversation(ref, async (context) => {
                const ref = TurnContext.getConversationReference(context.activity);
                await context.adapter.continueConversation(ref, async (context) => {
                    await context.sendActivity("Proactive hello.");
                });
            });
        });
        await context.sendActivity(MessageFactory.text("Message sent:" + Sent_msg_Cout));
    }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 893c2c9e-10e1-dd4e-1eb4-b4e9a46a9f8d
* Version Independent ID: 5f41c382-377c-6c9b-4932-65853675c4ad
* Content: [Use Microsoft Graph to authorize proactive bot installation and messaging in Teams - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/graph-api/proactive-bots-and-messages/graph-proactive-bots-and-messages?context=graph/context#code-sample)
* Content Source: [msteams-platform/graph-api/proactive-bots-and-messages/graph-proactive-bots-and-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/graph-api/proactive-bots-and-messages/graph-proactive-bots-and-messages.md)
* Product: **msteams**
* GitHub Login: @AkJo
* Microsoft Alias: **lajanuar**

**Comment by HunaidHanfee-MSFT** [comment]
@surbhigupta12 - Could you please help us to add the above contents as a separate code snippets section for C# & NodeJS?
