### ISSUE TITLE
MacOS URI Scheme for calling in MS Teams 

### ISSUE THREAD

**Issue by Anilkumar18** [MicrosoftDocs/msteams-docs#5036]
I am looking for the URI Scheme that allows my macOS app to dial a number within MS Teams.

By calling `tel:+14258828080` with urlForApplication on macOS uses facetime or the default app for calling.

How can we launch MS Teams from a 3rd party app? What's the URI scheme? For example, calling `msteams://` will open the MS Teams app, but what are the parameters for triggering a call to be placed?

I also tried with the param `msteams:/l/call/0/0?users=4:+14515422770`. But this one leads to opening the MS Teams but not triggering the call.

**Comment by Anilkumar18** [comment]
@HunaidHanfee-MSFT Thanks for your reply.
The above number I have mentioned is not assigned to any user. This number may either be Outside of Teams or assigned to someone.

I am looking for a URI Scheme like `msteams:` where I can navigate the user from my macOS application to macOS Teams App and place a call to the number. 

If I run the same scheme `msteams:/l/call/0/0?users=4:+14515422770` on any browser, it opens the Teams App and starts initiating the call. When I execute the same scheme from my app, it just opens the Teams app and does nothing. 

Do I miss any parameters here? Do I need to add anything other than this? Do I need to use any other scheme for making a call from the macOS App?

**Comment by Prasad-MSFT** [comment]
Please follow this [deeplink](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links#generate-a-deep-link-to-a-call) documentation and use the format as mentioned here: 
https://teams.microsoft.com/l/call/0/0?users=joe@contoso.com,4:9876543210
Currently, the User ID field supports the Azure AD UserPrincipalName, typically an email address, or in case of a PSTN call, it supports a pstn mri 4:<phonenumber>.
