### ISSUE TITLE
There is no "bot channels registration" service in Azure portal, please check and update the docs

### ISSUE THREAD

**Issue by ZuoXuangn** [MicrosoftDocs/msteams-docs#5039]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63519845-323f-be8f-ce15-d7f39e46b5a7
* Version Independent ID: 70952f91-56e9-ff08-59f6-e237d4aaeca9
* Content: [Add authentication to your Teams bot - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/authentication/add-authentication?tabs=dotnet%2Cdotnet-sample)
* Content Source: [msteams-platform/bots/how-to/authentication/add-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/bots/how-to/authentication/add-authentication.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by HunaidHanfee-MSFT** [comment]
Thanks for calling this out. We will update it.

**Comment by v-chetsh** [comment]
@surbhigupta12 - Could you please help us here to update the contents.

**Comment by surbhigupta12** [comment]
@v-shalinirobinson, please look into this.

**Comment by v-chetsh** [comment]
Document section is updated, so closing this issue.
