### ISSUE TITLE
Typo: ShatePoint instead of SharePoint

### ISSUE THREAD

**Issue by spjpgrd** [MicrosoftDocs/msteams-docs#504]
Just noticed the typo 🙃

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3083b5e-e805-ea10-c74d-479e0b33935f
* Version Independent ID: fb1b7746-4178-e17d-bcf4-e011eafb325f
* Content: [Context interface - Teams](https://docs.microsoft.com/en-us/javascript/api/%40microsoft/teams-js/microsoftteams.context?view=msteams-client-js-latest#feedback)
* Content Source: [nodejs/docs-ref-autogen/@microsoft/teams-js/microsoftTeams.Context.yml](https://github.com/OfficeDev/msteams-client-docs-ref-typescript/blob/live/nodejs/docs-ref-autogen/@microsoft/teams-js/microsoftTeams.Context.yml)
* Product: **msteams**
* GitHub Login: @charlesprakash
* Microsoft Alias: **o365devx**

**Comment by billbliss** [comment]
That reference content is generated automatically from the source, and we haven't updated it in a while - it's been fixed in the source. We'll get going on a refresh, thanks for the sharp eyes!

**Comment by clearab** [comment]
Fixed!
