### ISSUE TITLE
C# and Nodejs code snippets for Teams activity handlers

### ISSUE THREAD

**Issue by Prithvi-MSFT** [MicrosoftDocs/msteams-docs#5042]
Hi team,
Please add C# and Nodejs code snippets for below teams activity handlers mention in the document
Add the code snippets for [this ](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/bot-basics?tabs=csharp#teams-activity-handlers)section

OnTeamsChannelCreatedAsync(C#)
```
protected override Task OnTeamsChannelCreatedAsync(ChannelInfo channelInfo, TeamInfo teamInfo, ITurnContext<IConversationUpdateActivity> turnContext, CancellationToken cancellationToken)
        {
            // Code logic here
        }
```
OnTeamsChannelCreatedAsync(Nodejs)
```
onTeamsChannelCreated(async (channelInfo, teamInfo, context, next) => {
       // code for handling
        await next()
    });
```
OnTeamsChannelDeleted(C#)
```
protected override Task OnTeamsChannelDeletedAsync(ChannelInfo channelInfo, TeamInfo teamInfo, ITurnContext<IConversationUpdateActivity> turnContext, CancellationToken cancellationToken)
        {
            // Code logic here
        }
```
OnTeamsChannelDeleted(Nodejs)
```
onTeamsChannelDeleted(async (channelInfo, teamInfo, context, next) => {
       // code for handling
       await next()
    });
```
OnTeamsChannelRenamed(C#)
```
protected override Task OnTeamsChannelRenamed(ChannelInfo channelInfo, TeamInfo teamInfo, ITurnContext<IConversationUpdateActivity> turnContext, CancellationToken cancellationToken)
		{
			// Code logic here
		}
```
OnTeamsChannelRenamedAsync(Nodejs)
```
onTeamsChannelRenamed(async (channelInfo, teamInfo, context, next) => {
       // code for handling
       await next()
    });
```
OnTeamsTeamRenamedAsync(C#)
```
protected override Task OnTeamsTeamRenamedAsync(TeamInfo teamInfo, ITurnContext<IConversationUpdateActivity> turnContext, CancellationToken cancellationToken)
		{
			// Code logic here
		}
```
OnTeamsTeamRenamedAsync(Nodejs)
```
onTeamsTeamRenamedAsync(async (teamInfo, context, next) => {
       // code for handling
       await next()
    });
```
OnTeamsMembersAddedAsync(C#)
```
 protected override Task OnTeamsMembersAddedAsync(IList<TeamsChannelAccount> teamsMembersAdded, TeamInfo teamInfo, ITurnContext<IConversationUpdateActivity> turnContext, CancellationToken cancellationToken)
		{
			// Code logic here
		}
```
OnTeamsMembersAddedAsync(Nodejs)
```
onTeamsMembersAdded(async (membersAdded, teamInfo, context, next) => {
       // code for handling
	   await next();
    });
```
OnTeamsMembersRemovedAsyn(C#)
```
protected override Task OnTeamsMembersRemovedAsync(IList<TeamsChannelAccount> teamsMembersRemoved, TeamInfo teamInfo, ITurnContext<IConversationUpdateActivity> turnContext, CancellationToken cancellationToken);
		{
			// Code logic here
		}
```
OnTeamsMembersRemovedAsyn(Nodejs)
```
onTeamsMembersRemoved(async (membersRemoved, teamInfo, context, next) => {
       // code for handling
	   await next();
    });
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ec6c2e8-0af6-7984-a780-e5bb6ae113ef
* Version Independent ID: e0c9ab4e-0d6d-a4c5-f705-b78a0f2a87fb
* Content: [Bot activity handlers - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/bot-basics?tabs=csharp#teams-activity-handlers)
* Content Source: [msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/bots/bot-basics.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **anclear**

**Comment by v-chetsh** [comment]
@surbhigupta12 - Could you please help us to add the above contents as a separate code snippets section for C# & NodeJS?
