### ISSUE TITLE
Is there a possibility of adding teams app to 'meet now' / adhoc meeings?

### ISSUE THREAD

**Issue by pooranoayaw** [MicrosoftDocs/msteams-docs#5058]
We do not see '+ add app' button in ad-hoc  meetings /'meet now' meetings

![image](https://user-images.githubusercontent.com/85500568/150077200-ebcdb268-40cf-416a-94fe-b68d7e369583.png)

**Comment by Meghana-MSFT** [comment]
@pooranoayaw - We got an update from the engineering team, Currently it is not supported.

**Comment by v-chetsh** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.
