### ISSUE TITLE
Is there a way we can get list of attendees joined without invite?

### ISSUE THREAD

**Issue by pooranoayaw** [MicrosoftDocs/msteams-docs#5059]
In meetings, we invite people on the fly to join the meeting without inviting them through meeting invite. Is there an API that can give a list of people attending ad-hoc via API/Teams SDK? Current API returns only people who were invited for the meeting.

**Comment by sayali-MSFT** [comment]
@pooranoayaw -We are looking into this I will get back to you soon.

**Comment by sayali-MSFT** [comment]
@pooranoayaw - Currently we do not have API to get the list of attendees joined without invite.
If you want to get the Attendance report to attendees joined without invite.
1.select Show participants  
2.choose Download attendee list.
Ref Doc:-https://support.microsoft.com/en-us/office/view-and-download-meeting-attendance-reports-in-teams-ae7cf170-530c-47d3-84c1-3aedac74d310

For API, Could you please raise a user voice here:
https://microsoftteams.uservoice.com/forums/555103-public/filters/new

Thanks,
Sayali

**Comment by v-chetsh** [comment]
@pooranoayaw - Please let us know if you need any other details or shall we close this issue?

**Comment by pooranoayaw** [comment]
Yes, close this. Adding to UserVoice.

**Comment by pooranoayaw** [comment]
I have raised the issue in uservoice. You can close this ticket.

**Comment by v-chetsh** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.
