### ISSUE TITLE
Deep link to a custom team tab from the personal app not working on iOS

### ISSUE THREAD

**Issue by mlsBlue** [MicrosoftDocs/msteams-docs#5066]
We have two Angular applications where one is the personal app in the and the second one is team tab app. We ran on the issue of deep links to a team tab are not working when linked from the personal app in iOS devices. Deep links are working on Windows, macOS, Android phones and tablets, but not on the iOS devices. For this purpose we are using **microsoftTeams.executeDeepLink()** method for opening deep link. Format of the link is:
`'https://teams.microsoft.com/l/entity/{teamTabAppId}/{teamTabEntityId}?webUrl=' + encodedWebUrl + '&context=' + encodedContext + '&groupId=' + groupId'
`
When trying to execute this link with pure JavaScript (window.open()) link is opened successfully.

Callback **onComplete** method of the **microsoftTeams.executeDeepLink()** is returning state true with no reason of not properly executing the deep link.

Previously there were some issues reported regarding the deep links not working on iOS not sure if this introduced again or something is missing in our implementation.

Additional info:
iOS version - 15.1.1
MS Teams app version - 3.21.1 Build 3.21.77.2021216401/0111 (general)
@microsoft/teams-js version - 1.11.0

**Comment by Nivedipa-MSFT** [comment]
@mlsBlue - We are investigating your query. We will let you know once we have any update.

**Comment by Nivedipa-MSFT** [comment]
@mlsBlue - We tried to repro your issue. We have tested on desktop,web,android and IOS client. But its working fine at our end. We have tested on IOS 15.1.1 and Teams version 3.20.0. 
Could you please check your deeplink in browser first. Its correct or not?

**Comment by mlsBlue** [comment]
@Nivedipa-MSFT Deep link in the browser is working fine, as well as in the Teams app and on Android. Same link is used in all cases.

**Comment by Nivedipa-MSFT** [comment]
@mlsBlue - Could you please share your deeplink to test at our end?

**Comment by mlsBlue** [comment]
@Nivedipa-MSFT here is the one of the deep links that works in the browser, Teams desktop app and Android device but not in iOS.

https://teams.microsoft.com/l/entity/083693d6-7398-405b-b8a6-aab0566b3c5c/askmewhy-seamless-tab?webUrl=%2fteams%2fworkspace&context=%7b%22channelId%22%3a%2219%3a2TTv5mzYEfcV4ndqEeJUoh_JxLZu_w_N1Bjahkx-y581%40thread.tacv2%22%2c%22subEntityId%22%3a%22%22%7d&groupId=5a49bf49-daee-46d0-87bc-c518e369389d

This is the link to one of our own test public rooms in one of our tenants. Not sure will you be able to access the actual room.

**Comment by Nivedipa-MSFT** [comment]
@mlsBlue - Not able to access the deeplink.

**Comment by mlsBlue** [comment]
@Nivedipa-MSFT like I said it's on our environment. Can you send me the format of the deep link you use for iOS, or can you check our format and see if it's the correct one.

**Comment by Nivedipa-MSFT** [comment]
@mlsBlue - We will check your format and will let you know the updates.

**Comment by Nivedipa-MSFT** [comment]
@mlsBlue - We have tried the following deeplink 
https://teams.microsoft.com/l/entity/afe898b5-008c-4daa-82a6-a2a5b06b254d/request?webUrl=https://teams.microsoft.com/l/entity/afe898b5-008c-4daa-82a6-a2a5b06b254d/TestTab&context=channelId:19%25253aWjkrH4gV5JJ5Lq64oued47OVmrCEHzhsNcoINtTiGmw1%252540thread.tacv2&subEntityId:6dc098d0-0b73-4fde-9bf4-be847e9cf05a&groupId=9b3de624-cafd-40dc-9a6f-23a80f79f9e8

We have tested on IOS 15.1.1 with Teams version 3.20 and we get the **You can't opent this link on the mobile app. Please open in the desktop or web app.** and for Teams web client its working.

![MicrosoftTeams-image (13)](https://user-images.githubusercontent.com/92150070/151523609-255582c9-0a92-42ac-bf66-acc1439234ba.png)

We have raised the bug for this issue. We will get back to you once we have any update.

**Comment by Nivedipa-MSFT** [comment]
@mlsBlue - This bug has fixed now. We have tested in IOS 15.3 and Teams version 3.22.0. Could you please update the Teams version and check again.

**Comment by mlsBlue** [comment]
@Nivedipa-MSFT after checking the deep links functionality on earlier iOS version I can confirm that this is fixed with Teams version 3.22.0! Will close this one.
