### ISSUE TITLE
How can I remove the margin within the loaded sidePanel? The page does not explain.

### ISSUE THREAD

**Issue by jackblackCH** [MicrosoftDocs/msteams-docs#5067]
How can I remove the margin, e.g in the sidepanel? The page does not explain. Is it a setting?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9e1dcae-86bf-3546-de37-f746f60ddf63
* Version Independent ID: 2a11fb54-d08d-2e06-14cc-ab3e9a4edaeb
* Content: [Tab margin changes - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/removing-tab-margins)
* Content Source: [msteams-platform/resources/removing-tab-margins.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/resources/removing-tab-margins.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lomeybur**

**Comment by Meghana-MSFT** [comment]
By default whatever margin comes, that will be there.

**Comment by v-chetsh** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.
