### ISSUE TITLE
[Rendering] The value of place holder changes when a button is clicked

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#5074]
Copied bug from: https://github.com/microsoft/AdaptiveCards/issues/6897 

**Details from original post:**
### Target Platforms

NodeJS

### SDK Version

1.3

### Application Name

Microsoft teams

### Problem Description

So, I have a card that has 2 choice sets and 1 Action.Submit (submit button). When I click the button the expected behaviour is the value that I selected should remain in the placeholder section. It works as expected in the bot framework emulator, but in Microsoft teams when I change the value of the choice set and click on the submit button it goes back to the default placeholder. this is the JSON payload for the card.
In this case, When I select a value and click on submit button, it goes back to the default placeholder "Select a value".

### Screenshots

![image](https://user-images.githubusercontent.com/66434327/150371721-408f4c43-09a8-4d76-bc28-1107b940fb30.png)

![image](https://user-images.githubusercontent.com/66434327/150371634-72962df1-959a-481c-b60a-9d645e9d6864.png)

### Card JSON

```JSON
{
                    "type": "AdaptiveCard",
                    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
                    "version": "1.3",
                    "body": [
                        {
                            "type": "Container",
                            "items": [
                                {
                                    "type": "TextBlock",
                                    "wrap": true,
                                    "text": "Select the application name"
                                },
                                {
                                    "type": "Input.ChoiceSet",
                                    "choices": [
                                        {
                                            "title": "API",
                                            "value": "api"
                                        },
                                        {
                                            "title": "UI",
                                            "value": "UI"
                                        },
                                        {
                                            "title": "LE",
                                            "value": "le"
                                        },
                                        {
                                            "title": "Kafka",
                                            "value": "eats Kafka"
                                        }
                                    ],
                                    "placeholder": "Select a value",
                                    "id": "application_value"
                                },
                                {
                                    "type": "ActionSet",
                                    "actions": [
                                        {
                                            "type": "Action.Submit",
                                            "title": "Submit",
                                            "style": "positive",
                                        "data": {
                                            "postback_prop": true,
                                            "postback_activity": "getAppValue"
                                        }
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
```

### Sample Code

_No response_---
#### Document Details

⚠ *Do not edit this section.It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Cards reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **surbhigupta12**

**Comment by Prasad-MSFT** [comment]
We are checking the issue. We will get back to you shortly.

**Comment by Ajaykumar661** [comment]
@Prasad-MSFT Any luck?

**Comment by Prasad-MSFT** [comment]
@Ajaykumar661 -This does seem to be default behaviour of adaptive card that after selecting a particular value in choice set and clicking on submit, it reset back to default state.

**Comment by Ajaykumar661** [comment]
@Prasad-MSFT  That doesn't make sense, what if the user wants to validate the selected value. Are you sure this is a default behaviour?

**Comment by Prasad-MSFT** [comment]
Yes @Ajaykumar661 it is default behaviour of Adaptive card.

**Comment by Ajaykumar661** [comment]
@Prasad-MSFT So it's the default button for any button? Like the button for toggling visibility. Just curious.

**Comment by Prasad-MSFT** [comment]
@Ajaykumar661 - No, toggling visibility button doesn't reset to default after clicking.

**Comment by Ajaykumar661** [comment]
@Prasad-MSFT  I'm seeing that behaviour for the toggle button, Can you look into that?

**Comment by Prasad-MSFT** [comment]
@Ajaykumar661 , Could you please share the card JSON?

**Comment by Ajaykumar661** [comment]
@Prasad-MSFT  Yeah sure, the card I'm constructing is a dynamic one. I'll try to replicate the same in designer and get back to you.

**Comment by Ajaykumar661** [comment]
`{
    "type": "AdaptiveCard",
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.4",
    "body": [
        {
            "type": "Input.ChoiceSet",
            "choices": [
                {
                    "title": "enabled",
                    "value": "enable"
                },
                {
                    "title": "disabled",
                    "value": "disable"
                }
            ],
            "id": "node_id",
            "placeholder": "enabled",
            "label": "node_1"
        },
        {
            "type": "Input.ChoiceSet",
            "choices": [
                {
                    "title": "enabled",
                    "value": "enable"
                },
                {
                    "title": "disabled",
                    "value": "disable"
                }
            ],
            "id": "node_id_2",
            "placeholder": "enabled",
            "label": "node_2"
        },
        {
            "type": "TextBlock",
            "wrap": true,
            "isVisible": false,
            "id": "warningId",
            "text": "Are you sure want to switch traffic ?"
        },
        {
            "type": "ActionSet",
            "actions": [
                {
                    "type": "Action.Submit",
                    "title": "Yes",
                    "associatedInputs": "auto",
                    "data": {
                        "postback_prop": true,
                        "postback_activity": "toggleState"
                    }
                }
            ],
            "isVisible": false,
            "id": "yId"
        },
        {
            "type": "ActionSet",
            "actions": [
                {
                    "type": "Action.ToggleVisibility",
                    "title": "No",
                    "targetElements": [
                        "warningId",
                        "yId",
                        "nId"
                    ]
                }
            ],
            "isVisible": false,
            "id": "nId"
        }
    ],
    "actions": [
        {
            "type": "Action.ToggleVisibility",
            "title": "Submit",
            "targetElements": [
                "warningId",
                "yId",
                "nId"
            ]
        }
    ]
}`

**Comment by Ajaykumar661** [comment]
@Prasad-MSFT  This is the card. I'll try to attach a gif image if possible for this scenario.

**Comment by Prasad-MSFT** [comment]
@Ajaykumar661 - We were using below JSON having toggle visibility but without any submit action or choices type, so it was not reverting back to default. 
`{
  "type": "AdaptiveCard",
  "version": "1.2",
  "body": [
    {
      "type": "TextBlock",
      "text": "Press the buttons to toggle the images!",
      "wrap": true
    },
    {
      "type": "TextBlock",
      "text": "Here are some images:",
      "isVisible": false,
      "id": "textToToggle"
    },
    {
      "type": "ColumnSet",
      "columns": [
        {
          "type": "Column",
          "items": [
            {
              "style": "person",
              "type": "Image",
              "url": "https://picsum.photos/100/100?image=112",
              "isVisible": false,
              "id": "imageToToggle",
              "altText": "sample image 1",
              "size": "medium"
            }
          ]
        },
        {
          "type": "Column",
          "items": [

            {
              "type": "Image",
              "url": "https://picsum.photos/100/100?image=123",
              "isVisible": false,
              "id": "imageToToggle2",
              "altText": "sample image 2",
              "size": "medium"
            }
          ]
        }
      ]
    }
  ],
  "actions": [
    {
      "type": "Action.ToggleVisibility",
      "title": "Toggle!",
      "targetElements": [ "textToToggle", "imageToToggle", "imageToToggle2" ]
    },
    {
      "type": "Action.ToggleVisibility",
      "title": "Show!",
      "targetElements": [
        {
          "elementId": "textToToggle",
          "isVisible": true
        },
        {
          "elementId": "imageToToggle",
          "isVisible": true
        },
        {
          "elementId": "imageToToggle2",
          "isVisible": true
        }
      ]
    },
    {
      "type": "Action.ToggleVisibility",
      "title": "Hide!",
      "targetElements": [
        {
          "elementId": "textToToggle",
          "isVisible": false
        },
        {
          "elementId": "imageToToggle",
          "isVisible": false
        },
        {
          "elementId": "imageToToggle2",
          "isVisible": false
        }
      ]
    }
  ]
}
`
But while checking your provided JSON , we observed that the selected choice value reverts back to default state after submit action.

**Comment by Prasad-MSFT** [comment]
@Ajaykumar661 - We observed that the selected choice value reverts back to default state after submit action.

**Comment by Ajaykumar661** [comment]
@Prasad-MSFT  For your reference

This is the card I got
![git1issue](https://user-images.githubusercontent.com/66434327/150548773-5f31380f-e048-44ba-8b63-bea3907916b0.png)
Changing the value from enabled to disable.
![git2issue](https://user-images.githubusercontent.com/66434327/150548867-eb04645e-5386-4064-a8f8-9d87a4437934.png)
After changing the value
![git3issue](https://user-images.githubusercontent.com/66434327/150549071-e5c3c1bf-d83b-4f2d-b7c2-763b4c711f95.png)
After clicking on the toggle visibility button it went back to default value that is "enabled"
![git4issue](https://user-images.githubusercontent.com/66434327/150549291-dff25dcb-276a-412e-985d-141d3fa7b59e.png)

**Comment by Prasad-MSFT** [comment]
Yes, this seems to be default behaviour of adaptive card for button functionality

**Comment by v-chetsh** [comment]
@Ajaykumar661 - If you want to set the selected values after submitting the Card data, you can prepare the card with latest submitted values and send's back the updated card from the server.

**Comment by Ajaykumar661** [comment]
@v-chetsh  Like sending a whole new card with updated values?

**Comment by Ajaykumar661** [comment]
@Prasad-MSFT  @Wajeed-msft Can you look into this issue? [https://github.com/microsoft/AdaptiveCards/issues/6899](URL). This is more crucial than this...

**Comment by Ajaykumar661** [comment]
@Prasad-MSFT  We are good to close this window, Thanks for the insights.

**Comment by v-chetsh** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.

**Comment by Ajaykumar661** [comment]
@v-chetsh  @Wajeed-msft @Prasad-MSFT  I'm facing another issue pasted the link above, Can you look into this ?

**Comment by Prasad-MSFT** [comment]
@Ajaykumar661 - There is no issue attached with the link which you shared. Please recheck and share the correct url

**Comment by Ajaykumar661** [comment]
https://github.com/microsoft/AdaptiveCards/issues/6899 @Prasad-MSFT

**Comment by Ajaykumar661** [comment]
@Prasad-MSFT You got the right link?

**Comment by Prasad-MSFT** [comment]
@Ajaykumar661 - Yes, we will check
