### ISSUE TITLE
[Rendering] Wrap text not working for Input.ChoiceSet

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#5075]
Copied bug from: https://github.com/microsoft/AdaptiveCards/issues/6892 

**Details from original post:**
### Target Platforms

iOS

### SDK Version

1.4

### Application Name

Microsoft Teams

### Problem Description

The text on `choices` from an `Input.ChoiceSet` is not being properly wrapped on the Microsoft Teams iOS app. The `wrap` is set to `true`, but the text keeps clipping.

### Screenshots

![image](https://user-images.githubusercontent.com/4390163/149628673-4c6e83a7-6fa9-435e-bb7d-01c6b4f5282f.png)

### Card JSON

```JSON
{
    "type": "AdaptiveCard",
    "body": [
        {
            "type": "Container",
            "items": [
                {
                    "type": "TextBlock",
                    "size": "Medium",
                    "weight": "Bolder",
                    "text": "Micro-Review® 🌠"
                },
                {
                    "type": "Input.Text",
                    "placeholder": "",
                    "id": "userName",
                    "value": "John Doe",
                    "isVisible": false
                },
                {
                    "type": "TextBlock",
                    "wrap": true,
                    "text": "Hey **John Doe**, as an active and valued member of the **FOO** team, you are invited to provide feedback on how the team is doing in relation to the success measures of the **BAR** cycle. Thank you for your input! 🙌"
                },
                {
                    "type": "TextBlock",
                    "wrap": true,
                    "text": "**Length:** 30 seconds"
                },
                {
                    "type": "TextBlock",
                    "wrap": true,
                    "text": "**Visibility:** Anonymous"
                },
                {
                    "type": "TextBlock",
                    "wrap": true,
                    "text": "P.S. this Micro-Review expires in 24 hours",
                    "size": "small"
                },
                {
                    "type": "TextBlock",
                    "weight": "Bolder",
                    "text": "Stimulating Work",
                    "wrap": true,
                    "id": "1"
                },
                {
                    "type": "Input.ChoiceSet",
                    "id": "achieved_6bbed545-3de3-4ea3-849a-69a67c7cfca5",
                    "placeholder": "",
                    "isRequired": true,
                    "errorMessage": "Your input on \"Stimulating Work\" is required",
                    "wrap": true,
                    "choices": [
                        {
                            "title": "We're doing well 👍",
                            "value": "1"
                        },
                        {
                            "title": "We could be doing better ☝",
                            "value": "0"
                        }
                    ],
                    "style": "expanded"
                },
                {
                    "type": "TextBlock",
                    "text": "Have a suggestion on how we can improve? (optional)",
                    "wrap": true,
                    "weight": "Bolder"
                },
                {
                    "type": "Input.Text",
                    "placeholder": "Write suggestion here",
                    "id": "comment_6bbed545-3de3-4ea3-849a-69a67c7cfca5"
                }
            ],
            "separator": false
        }
    ],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.4"
}
```

### Sample Code

_No response_---
#### Document Details

⚠ *Do not edit this section.It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Cards reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **surbhigupta12**

**Comment by sayali-MSFT** [comment]
@edsondota - We are looking into this I will get back to you soon.

**Comment by sayali-MSFT** [comment]
@edsondota - We are tried to repro the scenario, It's working fine with our end. Could u please check it once?
`{
    "type": "AdaptiveCard",
    "body": [
        {
            "type": "Container",
            "items": [
                {
                    "type": "TextBlock",
                    "size": "Medium",
                    "weight": "Bolder",
                    "text": "Micro-Review® 🌠"
                },
                {
                    "type": "Input.Text",
                    "placeholder": "",
                    "id": "userName",
                    "value": "John Doe",
                    "isVisible": false
                },
                {
                    "type": "TextBlock",
                    "wrap": true,
                    "text": "Hey **John Doe**, as an active and valued member of the **FOO** team, you are invited to provide feedback on how the team is doing in relation to the success measures of the **BAR** cycle. Thank you for your input! 🙌"
                },
                {
                    "type": "TextBlock",
                    "wrap": true,
                    "text": "**Length:** 30 seconds"
                },
                {
                    "type": "TextBlock",
                    "wrap": true,
                    "text": "**Visibility:** Anonymous"
                },
                {
                    "type": "TextBlock",
                    "wrap": true,
                    "text": "P.S. this Micro-Review expires in 24 hours",
                    "size": "small"
                },
                {
                    "type": "TextBlock",
                    "weight": "Bolder",
                    "text": "Stimulating Work",
                    "wrap": true,
                    "id": "1"
                },
                {
                    "type": "Input.ChoiceSet",
                    "id": "achieved_6bbed545-3de3-4ea3-849a-69a67c7cfca5",
                    "placeholder": "",
                    "isRequired": true,
                    "errorMessage": "Your input on \"Stimulating Work\" is required",
                    "wrap": true,
                    "choices": [
                        {
                            "title": "We're doing well 👍",
                            "value": "1"
                        },
                        {
                            "title": "We could be doing better ☝",
                            "value": "0"
                        }
                    ],
                    "style": "expanded"
                },
                {
                    "type": "TextBlock",
                    "text": "Have a suggestion on how we can improve? (optional)",
                    "wrap": true,
                    "weight": "Bolder"
                },
                {
                    "type": "Input.Text",
                    "placeholder": "Write suggestion here",
                    "id": "comment_6bbed545-3de3-4ea3-849a-69a67c7cfca5"
                }
            ],
            "separator": false
        }
    ],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.4"
}`
![MicrosoftTeams-image](https://user-images.githubusercontent.com/93527375/150481922-3ae772f0-3230-4276-86be-d6703cb07080.png)

**Comment by edsondota** [comment]
@sayali-MSFT , I can say by your screenshot that you've tested on an Android device, it's not working on the teams' app on the iOS.

I also, double-checked it and the issue still.

**Comment by sayali-MSFT** [comment]
@edsondota - We are able to repro that issue , We have raised bug for the same and concerned team is looking into it. We will inform you once we get any update.

**Comment by MajaEffenberg** [comment]
I ran into the same error in our app also on the platform iOS, SDK Version 1.4. The choice text in `Input.Choice` is not properly wrapped, and the `wrap` property is also set to `true`.

![IMG_9009](https://user-images.githubusercontent.com/89073193/163132934-9ece7396-3267-4421-9ce0-1964dfe1b37d.PNG)

Card JSON
```json
{
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "type": "AdaptiveCard",
  "version": "1.4",
  "body": [
    {
      "type": "ColumnSet",
      "columns": [
        {
          "type": "Column",
          "width": "stretch",
          "items": [
            {
              "type": "TextBlock",
              "wrap": true,
              "text": "Lernpaket:",
              "fontType": "Default",
              "size": "small"
            }
          ]
        },
        {
          "type": "Column",
          "width": "auto",
          "items": [
            {
              "type": "TextBlock",
              "fontType": "Default",
              "text": "3/5",
              "size": "small",
              "horizontalAlignment": "right"
            }
          ]
        }
      ]
    },
    {
      "type": "TextBlock",
      "text": "question",
      "height": "stretch",
      "wrap": true
    },
    {
      "type": "Input.ChoiceSet",
      "id": "multipleCardSelection",
      "style": "expanded",
      "choices": [
        {
          "title": "Ich entscheide auf Freischlag für den UHC Benefiz.",
          "value": "A"
        },
        {
          "title": "Ich entscheide auf Bully am nächstgelegenen Bullypunkt.",
          "value": "B"
        },
        {
          "title": "Ich spreche eine Kleine Bankstrafe gegen Spielerin Nr. 21 aus. Anschliessend wird das Spiel mit einem Freischlag für den UHC Benefiz fortgesetzt.",
          "value": "C"
        }
      ],
      "isMultiSelect": true,
      "wrap": true
    },
    {
      "type": "Container",
      "items": [
        {
          "type": "ActionSet",
          "actions": [
            {
              "type": "Action.Submit",
              "title": "send",
              "data": {
                "msteams": {
                  "type": "messageBack",
                  "displayText": "Send",
                  "value": {
                    "action": "answerQuiz",
                    "previousQuizId": "question.id",
                    "previousQuizAnswerId": "answer.id",
                    "previousQuizAnswers": "question.id"
                  }
                }
              }
            }
          ]
        }
      ]
    }
  ]
}

```

**Comment by sueess** [comment]
Same problem here. Only on iOS. Looking forward to a fast fix. Is there a known workaround ?

**Comment by sueess** [comment]
@sayali-MSFT Can you give us an update, it's quite a heavy bug. Many thanks!

**Comment by sueess** [comment]
Works now! Thank you! This issue can be closed.
