### ISSUE TITLE
Unable to use Teams - crashes after about 20 minutes every time. Error caa70004

### ISSUE THREAD

**Issue by ncanderson** [MicrosoftDocs/msteams-docs#508]
When I re-start my computer, Teams will work fine for about 20 minutes. After that, every time, I end up on the 'D'oh, something went wrong!' page, with error message caa70004. 

I've tried reinstalling Teams from scratch and clearing all credentials from Windows Credentials Manager, but once I end up on the 'D'oh' screen, neither of the options there (restart or sign out) can make Teams work again.

**Comment by Wajeed-msft** [comment]
Are you still facing this issue? Could you please share your Teams client log and re-open this issue?
Windows:
 Keyboard shortcut: Ctrl + Alt + Shift + 1
Mac OSX:
 Keyboard shortcut: Option + Command + Shift+1
