### ISSUE TITLE
[iOS] Notifications: Summary string ignored for adaptive cards with small payload

### ISSUE THREAD

**Issue by matthiasdilger** [MicrosoftDocs/msteams-docs#5080]
When a bot sends an adaptive card to the user and sets the summary string, the summary string shows up in the system notification on ios. However, this does not work if the card has a small payload and ios shows an empty notification instead.

The card below results in an empty notification on ios. Bot sends this as a command result in a 1:1 chat with the user:
```
let card = CardFactory.adaptiveCard({
              "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
              "type": "AdaptiveCard",
              "version": "1.2",
              "body": [{
                "type": "TextBlock",
                "wrap": true,
                "text": "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English."
              }]                
            });
            await context.sendActivity({ attachments: [card], summary: "Lorem ipsum"});
```

However sending this large card results in the summary string being shown the ios notification:
```
let card = CardFactory.adaptiveCard({
              "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
              "type": "AdaptiveCard",
              "version": "1.2",
              "body": [{
                "type": "TextBlock",
                "wrap": true,
                "text": "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English."
              },
<REPEAT THE TextBlock 14 TIMES>
             ]                
            });
            await context.sendActivity({ attachments: [card], summary: "Lorem ipsum"});
```

When the bot sends an adaptive card  and the summary string is present, the ios notification should always show the summary string.

**Comment by Nivedipa-MSFT** [comment]
@matthiasdilger - We are investigating your query. We will get back to you once we have any update.

**Comment by matthiasdilger** [comment]
Hi @Nivedipa-MSFT - Were you able to reproduce the issue?

**Comment by Nivedipa-MSFT** [comment]
@matthiasdilger - We have tried your card which has small payload in IOS version 15.1.1 and Teams version 3.20.0 but we are getting summary in notification.
![MicrosoftTeams-image (14)](https://user-images.githubusercontent.com/92150070/151536171-c099ecde-1f38-479c-87ca-9c79ccc65c80.png)


Could you please try to update the Teams version and check again.

**Comment by matthiasdilger** [comment]
@Nivedipa-MSFT The summary in the chat list (your screenshot) works, the issue is the system notification on the physical device

Tested with iphone 6s, ios 15.3 and Teams 3.22

Sending this card:
```
let card = CardFactory.adaptiveCard({
              "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
              "type": "AdaptiveCard",
              "version": "1.2",
              "body": [{
                "type": "TextBlock",
                "wrap": true,
                "text": "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English."
              }]                
            });
            await context.sendActivity({ attachments: [card], summary: "Lorem ipsum"});
```

Results in the following notification (cropped screenshot from physical device):
![image_6483441-4](https://user-images.githubusercontent.com/5625718/151542515-12fb70e3-766c-4a66-bc37-5de8d3daad21.JPG)

But sending this card:
```
let card = CardFactory.adaptiveCard({
      "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
      "type": "AdaptiveCard",
      "version": "1.2",
      "body": [{
        "type": "TextBlock",
        "wrap": true,
        "text": "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English."
      },
      {
        "type": "TextBlock",
        "wrap": true,
        "text": "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English."
      },
      {
        "type": "TextBlock",
        "wrap": true,
        "text": "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English."
      },
    {
        "type": "TextBlock",
        "wrap": true,
        "text": "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English."
      }]                
    });
    await context.sendActivity({ attachments: [card], summary: "Lorem ipsum"});
```

Results in the correct behavior:
![image_6483441-5](https://user-images.githubusercontent.com/5625718/151542668-74380ace-4c3d-4bdb-9a28-5340df75c88e.JPG)

**Comment by Nivedipa-MSFT** [comment]
@matthiasdilger - We are able to repro this issue and we have raised a bug for it. We will let you know once we get updates on it.

**Comment by v-chetsh** [comment]
@matthiasdilger - Engineering team is looking into it and once it is fixed and publicly available, we will let you know.

**Comment by matthiasdilger** [comment]
This issue has been finally fixed, thanks

**Comment by matthiasdilger** [comment]
Spoke too soon, issue still present

**Comment by Nivedipa-MSFT** [comment]
@matthiasdilger - We are checking the status of bug with engineering team. We will let you know once we have any updates on it.

**Comment by ChetanSharma-msft** [comment]
Hello @matthiasdilger - Sorry for delay in response.
We are actively checking the updates on this issue with engineering team and let you know, if we have any.

**Comment by alon85** [comment]
Any updates on this ?

**Comment by Nivedipa-MSFT** [comment]
@alon85 - We are currently in the process of checking the status of the bug fix with our engineering team. Rest assured, we will provide you with an update as soon as we have more information. Thank you for your patience.

**Comment by matthiasdilger** [comment]
@Nivedipa-MSFT Confirming as fixed

**Comment by Nivedipa-MSFT** [comment]
@matthiasdilger - Could you please share your valuable feedback via [Microsoft Teams Developer Feedback](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR7iCOpS5_b9Nqmwx43u5rtZUOThVR081SllSR05aSDQxQ0tUMDVPTVIxTi4u) link.
