### ISSUE TITLE
Teams - Excel documents as tab will not expand fully

### ISSUE THREAD

**Issue by mraskas** [MicrosoftDocs/msteams-docs#509]
If you take an excel document in teams in "Files" and click to "make this a tab", then on the tab click edit, then click to "expand tab" it will not expand fully and has a blank column on the right. If you click to expand first, while it does not expand, then when you click edit it does expand. This is a frustrating bug and should be fixed.

**Comment by Wajeed-msft** [comment]
I just tried mentioned steps, I don't see any blank column. Could you please share the screenshot and highlight the issue?

**Comment by Wajeed-msft** [comment]
Please re-open with screenshot.
