### ISSUE TITLE
Is it possible to temporarily disable a personal tab in my own Microsoft TEAMS app?

### ISSUE THREAD

**Issue by iliosana** [MicrosoftDocs/msteams-docs#5090]
I am building my own teams app and would like to disable or hide certain personal tabs of my app depending on e.g. the role of the signed in user.

Here are two examples in which case I would like to disable certain personal tabs:
- User hasn't signed in yet, so I only want to show one tab, the "sign in" tab. All other tabs are redundant as they show the same information.
- User doesn't have permission to view a certain tab, because access may be restricted to admins only. Instead of showing a "you have no access" banner, we would prefer to simply hide or disable (e.g. greyed-out or unclickable) that particular tab.

I couldn't find any information on whether this is possible. 

Thank you for your help!

**Comment by Meghana-MSFT** [comment]
We have static tabs in personal scope and It is not possible to hide static tabs. You can request this feature on [Microsoft Uservoice](https://feedbackportal.microsoft.com/feedback/forum/ad198462-1c1c-ec11-b6e7-0022481f8472).

**Comment by Meghana-MSFT** [comment]
We are closing this issue, please feel free to reopen if you need any help. Thank you.
