### ISSUE TITLE
The image in `Upload your package into a team using the Apps tab` step 1 is misleading

### ISSUE THREAD

**Issue by GitMje** [MicrosoftDocs/msteams-docs#510]
The image in `Upload your package into a team using the Apps tab` step 1 is misleading.  It shows an arrow to the "Create an Outgoing webhook" link but the point of it is to click the "Apps" tab.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 328c86a9-1384-3f07-0b68-947f5ad9b5ab
* Version Independent ID: 9a8e000a-87ed-1357-0b28-feee59311149
* Content: [Upload your custom app in Microsoft Teams - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/apps/apps-upload#feedback)
* Content Source: [msteams-platform/concepts/apps/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/apps/apps-upload.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by billbliss** [comment]
Good catch. We modified this image to use somewhere else and didn't remember that it was used here too. @clearab we should probably rename ManageTeam.png to be OutgoingWebhook.png or something like that and create a new ManageTeam.png.

**Comment by GitMje** [comment]
Thanks for the quick response, @billbliss.

**Comment by clearab** [comment]
Screenshot was extraneous, and was removed.
