### ISSUE TITLE
supportsCalling experimental feature roadmap

### ISSUE THREAD

**Issue by shivsidhu** [MicrosoftDocs/msteams-docs#5104]
[Enter feedback here]
The Teams Bot calling feature ("supportsCalling") is currently marked as experimental. Could you please provide some insights into the future roadmap or tentative GA for this feature.

Documentation Ref. - https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema#bots

![image](https://user-images.githubusercontent.com/54524358/151289241-e21ab041-798e-41cc-9df3-4dd8527d2213.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f94a488-d636-92b3-21eb-c88744c8f272
* Version Independent ID: 7b3413f4-9ade-accf-5cb2-83fead11a32a
* Content: [Manifest schema reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema#bots)
* Content Source: [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/resources/schema/manifest-schema.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by v-chetsh** [comment]
@shivsidhu - We will check on it from our end and let you know the updates.

**Comment by Prasad-MSFT** [comment]
@shivsidhu - Currently there is no ETA to share. However you can now get latest Teams platform updates by subscribing to the [RSS feed](https://docs.microsoft.com/en-us/microsoftteams/platform/whats-new#get-latest-updates).
[What's new - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/whats-new)

**Comment by v-chetsh** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.
