### ISSUE TITLE
I’d like to be able to switch between my MSA and AAD account without login off

### ISSUE THREAD

**Issue by tegaaa** [MicrosoftDocs/msteams-docs#511]
I need to logoff every time and it take a long time to boot up.  I click on my picture and having a way to switch “tenant”/“user” would be nice

**Comment by billbliss** [comment]
Working on it!

**Comment by billbliss** [comment]
Can't give a date, but you will hopefully not have to wait long. It's been a big initiative for some time.

**Comment by tegaaa** [comment]
Thanks Bill.
