### ISSUE TITLE
'Open Developer Preview' Still Missing 48 Hours After Enabling Custom Apps

### ISSUE THREAD

**Issue by bweitzman** [MicrosoftDocs/msteams-docs#5114]
As others have posted about, we've enabled Custom Apps but the option for Developer Preview (to then turn on DevTools) is still missing from my desktop client after 48 hours. We've tried restarting PCs, closing/reopening the Teams app, etc. All I have in my Settings > About menu are Version, Legal, Privacy and cookies, and the two Third party notice options. 

Side note, the guidance for enabling Developer Preview on [this page](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/dev-preview/developer-preview-intro) is seemingly out of date as it says to click on my profile to get to About, but that button/menu no longer contains About. About is now under the ... menu left of my profile. 

P.S. - I really don't appreciate that you made me sign up for a github account to tell you that your product is broken & the guidance on your published support page is wrong. I have a million other Microsoft accounts already, just let me use one of those when I need support!

**Comment by sayali-MSFT** [comment]
@bweitzman -We are looking into this I will get back to you soon.

**Comment by bweitzman** [comment]
@sayali-MSFT this is a really disappointing response. From other comments this is clearly an issue that others are also having, and forcing us to navigate Product Support via a tenant admin (slower and resource constrained for me, higher cost of responding for Microsoft as it has to be handled individually for every affected customer) is much less effective than acknowledging what is clearly a known issue and sharing the information on how to resolve/work around where anyone can see it so they don't too have to go down the Product Support rabbit hole. 100 times out of 100 I'm going to ask a web search (which inevitably leads to these support forums) before I bother a person directly.

**Comment by v-chetsh** [comment]
@bweitzman - We will check on it from our end and act on it accordingly.

**Comment by sayali-MSFT** [comment]
@bweitzman  - Please have a look at this doc- https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/prepare-your-o365-tenant#enable-teams-for-your-organization
Let us know if you have any query.

**Comment by bweitzman** [comment]
@sayali-MSFT I really appreciate your continuing to attempt to work with me on this. I can confirm that the setting you've linked is the one we enabled three weeks ago and the Developer Preview option is still not appearing for any of our users. This is the "known issue" I have been referring to, having seen several other threads reporting the same when [browsing all feedback ](https://github.com/MicrosoftDocs/msteams-docs/issues?utf8=%E2%9C%93&q=%22f1413f77-5eb3-e1fd-9235-d322d6e4eb6c%22&in=body) from [the page I was originally following the instructions on](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/dev-preview/developer-preview-intro).

**Comment by Wajeed-msft** [comment]
@bweitzman - could you please share screenshots of following? 

**Org-wide app settings:**
<img width="588" alt="image" src="https://user-images.githubusercontent.com/31851992/154889786-bb989ae6-2efd-4529-9806-495355b1cf94.png">



**Setup policies:**
<img width="555" alt="image" src="https://user-images.githubusercontent.com/31851992/154889803-e19b74c8-7383-4b61-a6d1-58cb28731a5f.png">

**Comment by bweitzman** [comment]
Hi Wajeed-msft, thanks again for continuing to work this issue with me! I was hopeful that the first of your two screenshots would be what I was missing--as the documentation to enable Developer Tools only refers to the setting under Setup Policies from screenshot 2--but unfortunately we already had both set to On. Glad this exchange is happening in the comments though, as it may be the step others who stumble across this thread are missing!

Screenshots from our admin center are attached showing these settings enabled. Please let me know if you have any other ideas I can try out, or would like additional details from me.

![screenshot-1](https://user-images.githubusercontent.com/98620104/155035933-871fa7ac-61f6-49d4-b66b-78c0558b0c9d.png)

![screenshot-2](https://user-images.githubusercontent.com/98620104/155035940-ab776c94-aaa3-4b3d-a49c-4c36766295c1.jpg)

**Comment by Wajeed-msft** [comment]
@bweitzman - Thanks for sharing the screenshots. Based on the screenshot I could see that this policy is applied to **Viva Connections Pilot Group**.  Just to isolate the issue could you please try these two options and retry? 

1. Enable the custom apps for **Global** instead of custom group.
**Or**
2. Re-apply "Viva Connections Pilot" policy to specific user.

**Comment by bweitzman** [comment]
Thanks for these ideas. My IT department won't be ok with applying this
policy globally. Everyone I've been working with to test this is in the
pilot group, which we used to target viva connections before rolling it out
broadly. The need for developer tools rose out of that test group as we are
having some glitchy behavior pulling in our home page to Teams, and none of
us on that testing team see developer tools.

I'll ask about reapplying the policy and let you know after 24-48 hours if
that changes anything.

**Comment by bweitzman** [comment]
Back with good news: Removing and reapplying the policy seems to have worked, and I can now access DevTools to troubleshoot my wonky CSS in Viva Connections! Thanks to everyone on the team who helped me step through all of this.

For the sake of leaving some breadcrumbs behind that others experiencing the same issue can follow in the future, here's  everything we stepped through:

1. Verify [these instructions](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/prepare-your-o365-tenant#enable-teams-for-your-organization) were followed to enable uploading of custom apps, in Teams Admin Center under **Teams Apps > Setup Policies**.
2. Verify the additional Teams Admin Center setting at **Teams Apps > Manage Apps > Custom Apps > Interaction With Custom Apps** is set to on, [as shown in this screenshot](https://github.com/MicrosoftDocs/msteams-docs/issues/5114#issuecomment-1046470963). 
3. If still not seeing the option to Enable Developer Preview under **... > About** in the Teams desktop app menu, remove and reapply the settings in Admin Center, wait 24 hours, reboot, and check again. This is what fixed it for us:
![screen-dev-preview-present](https://user-images.githubusercontent.com/98620104/155588427-8455150e-51a5-4ea9-8afc-dae9ab01a51d.png)
![screen-devtools-present](https://user-images.githubusercontent.com/98620104/155588463-9d506448-1a77-4bdf-bfe5-8ab226f03ef7.png)

Adding a couple of suggestions for consideration by the Microsoft team(s) maintaining the support pages that pointed me to this forum, in case they see this comment as well:

1. Add guidance for the 2nd bullet above (Interaction With Custom Apps setting) on either Teams Developer documentation page Test Your App > [Prepare Your Microsoft 365 Tenant](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/prepare-your-o365-tenant) -- if Interaction With Custom Apps is necessary for all custom app scenarios -- or App Manifest > Public Developer Preview > [Overview](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/dev-preview/developer-preview-intro) -- if this additional setting is only pertinent to enabling Developer Preview.
2. Update guidance on the App Manifest > Public Developer Preview > [Overview](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/dev-preview/developer-preview-intro) page to reflect the current location of Developer Preview (under the ... menu in Desktop, not under the profile menu as instructed).
3. It seems from our troubleshooting in this thread that there may be a glitch with non-global policies not taking hold on the first application of these settings. The other threads in this forum detailing the same experience I had trouble with were closed before cause/resolution could be shared, but if this continues to pop up it may be worth further exploration by a QA team. If repeatable, a troubleshooting note on the Developer Preview Overview page would be helpful until the glitch can be patched.

Thanks again for all your help in seeing this through to resolution!
