### ISSUE TITLE
Add a note for "Messaging endpoint" that "You can have only one messaging endpoint for a bot"

### ISSUE THREAD

**Issue by v-chetsh** [MicrosoftDocs/msteams-docs#5116]
We have a Azure bot/Bot channel registration section in this page:
https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/authentication/add-authentication?tabs=dotnet%2Cdotnet-sample#create-the-bot-channels-registration

Could you please add a note for "Messaging endpoint"  in 5th point that **"You can have only one messaging endpoint for a bot"**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63519845-323f-be8f-ce15-d7f39e46b5a7
* Version Independent ID: 70952f91-56e9-ff08-59f6-e237d4aaeca9
* Content: [Add authentication to your Teams bot - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/authentication/add-authentication?tabs=dotnet%2Cdotnet-sample#create-the-bot-channels-registration)
* Content Source: [msteams-platform/bots/how-to/authentication/add-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/bots/how-to/authentication/add-authentication.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by v-chetsh** [comment]
@surbhigupta12 - Please help us here to update the contents.

**Comment by v-habibaumme** [comment]
Hi @v-chetsh 

Added a note as per the requirement, hence closing this PR.

Thanks!
