### ISSUE TITLE
Excel in MS Teams does not respond to "tab" keyboard press correctly

### ISSUE THREAD

**Issue by danieldykim** [MicrosoftDocs/msteams-docs#512]
I'm using windows 10
Installed MS Teams desktop application
> I created an Excel sheet inside the "Files" tab, then created a tab and linked to the file
> I click on the "Edit" button on the right upper corner, so that I'm directly editing the excel sheet inside MS Teams application.
> Put the cursor focus on one of the cells (can start editing the cell)
> Press the "tab" keyboard button

EXPECTED BEHAVIOR: I am expecting the focus to move over to the next cell in the row.  That's what happens if you edit the file in Excel desktop version or Excel Online version.

OBSERVED BEHAVIOR: What I get instead is that MS Teams takes the focus and starts to move the focus onto other buttons inside MS Teams.

**Comment by Wajeed-msft** [comment]
Could you please try this with latest build and let us know if you are still facing this issue?

**Comment by danieldykim** [comment]
Yes, this problem is still happening with the latest build (I assume that I have the latest build if I’m inside the Teams app and then I do the “check for updates” and it tells me that I have the latest)



Sent from Yahoo Mail for iPad


On Wednesday, May 15, 2019, 1:21 AM, Wajeed-msft <notifications@github.com> wrote:


Could you please try this with latest build and let us know if you are still facing this issue?

**Comment by Wajeed-msft** [comment]
We are unable to repro this at our end. Could you please share some screen recording for this issue and re-opne it?
