### ISSUE TITLE
Checked out collaboration document in teams not saving changes when multiple people are working on it. Office 365 Teams

### ISSUE THREAD

**Issue by ByronC2019** [MicrosoftDocs/msteams-docs#513]
Good Afternoon All

Users in my organization have reported a similar issue when modifying documents saved to Teams. We are using office 365 in our environment. Users will modify a document and work on it for a hour for example then save frequently using the desktop apps in either Mac or Windows but the updates dont pull through when checking the versioning. It shows that users work has not be updated and there is no record of the changes made. Could this be related to the issue above.

Kind regards

Byron Coetzee

**Comment by Wajeed-msft** [comment]
> Users will modify a document and work on it for a hour for example then save frequently using the desktop apps in either Mac or Windows.

Are you editing your docs direclty in Microsoft Teams desktop apps?

**Comment by ByronC2019** [comment]
Hi There the users were editing the files directly in teams when they reported the issue.

**Comment by Abhijit-MSFT** [comment]
When multiple users are editing file then conflicts can occur. best way to modify file is to edit it outside the teams (three dots on top right corner of the screen, if it is excel, edit it in excel and vice versa) and keep autosave option on(top left of the screen). This way any number user can update file.
