### ISSUE TITLE
This page does not provide details about how to reply back to outgoing webhook request. 

### ISSUE THREAD

**Issue by supriyasaraogi** [MicrosoftDocs/msteams-docs#5132]
[Enter feedback here]
The documentation covers the details of creating outgoing webhook. But does not provide details about how to send the response back to outgoing webhook request. In my case my service is able to receive the request from outgoing webhook. But I'm struggling to find the documentation to send the response back. This is not helpful for a developer. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb9c5bd5-1ac6-dcc8-4ed6-d6aad2432776
* Version Independent ID: 43e90995-bba4-86b6-1f1c-ab749e546a4b
* Content: [Create an Outgoing Webhook - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-outgoing-webhook?tabs=urljsonpayload%2Cdotnet)
* Content Source: [msteams-platform/webhooks-and-connectors/how-to/add-outgoing-webhook.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/webhooks-and-connectors/how-to/add-outgoing-webhook.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by sayali-MSFT** [comment]
@supriyasaraogi -We are looking into this I will get back to you soon.

**Comment by sayali-MSFT** [comment]
@supriyasaraogi - Could you please try with this [sample](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/outgoing-webhook/csharp) ?
Let us know if you have any query.

**Comment by supriyasaraogi** [comment]
Hi Sayali,

Thanks for your response. I guess the question I'm asking here is. I have
created an outgoing webhook and I'm able to receive messages from teams in
my service.
My question is how do I reply back to the messages from my service to the
teams channel.

Thanks,
Supriya

**Comment by sayali-MSFT** [comment]
@supriyasaraogi - Outgoing Webhook sends notifications to external web services and responds with rich messages, which include cards and images.
 
 Incoming Webhook allows any external apps to share content in Teams channels. These webhooks are used as tracking and notifying tools. They provide a unique URL, to which you send a JSON payload with a message in card format.

So ,you can use the incoming webhook if you want to send message through your service to Teams.
Ref Doc:-https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-incoming-webhook

**Comment by sayali-MSFT** [comment]
@supriyasaraogi - Could you please confirm if your issue has resolved with above suggestion or still looking for any help?

**Comment by supriyasaraogi** [comment]
Hi Sayali,

Thanks for checking. Yes, this query is resolved. Please go ahead and
close this issue.

Thanks,
Supriya
