### ISSUE TITLE
Version of adaptive card supported by Teams

### ISSUE THREAD

**Issue by krishnajaju** [MicrosoftDocs/msteams-docs#514]
Is the latest version 1.1.2 of adaptive cards supported in Teams?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8a3bcf2-332a-8d24-a8d1-7e3816897745
* Version Independent ID: 68fb9551-ce95-0112-2703-721a1af01f23
* Content: [Cards Reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/cards/cards-reference#)
* Content Source: [msteams-platform/concepts/Cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/Cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Wajeed-msft** [comment]
Currently, only v1.0 is supported.

**Comment by clearab** [comment]
I've updated the documentation to reflect this.

**Comment by tposzytek** [comment]
Hi! Do you know when version 1.1 is going to be supported?

**Comment by harshchawda** [comment]
Hi, do anyone knows when version 1.2 of adaptive card will be supported in teams

**Comment by bpflugfelder** [comment]
Hi there, same question. Does everyone know when version 1.2 of adaptive cards will be supported. Thanks

**Comment by daniel0x00** [comment]
+1. This is needed, please. Support for version 1.2 will bring support for Action.ToggleVisibility, a must for us.
