### ISSUE TITLE
The screenshots for "Personal Tabs" and "Messaging Extensions" are the same -- they should be different

### ISSUE THREAD

**Issue by AE-MS** [MicrosoftDocs/msteams-docs#5145]
Presumably the screenshot for Messaging Extensions should show a messaging extension in the UI.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fcea0c3-c249-a292-913b-dc0271e4e810
* Version Independent ID: 6fcea0c3-c249-a292-913b-dc0271e4e810
* Content: [Extend Teams apps across Microsoft 365 (preview) - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/m365-apps/overview)
* Content Source: [msteams-platform/m365-apps/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/m365-apps/overview.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by v-chetsh** [comment]
@surbhigupta12 - Could you please help us here to update the screenshots at below section:
https://docs.microsoft.com/en-us/microsoftteams/platform/m365-apps/overview#teams-messaging-extensions-in-outlook

**Comment by sayali-MSFT** [comment]
> @surbhigupta12 - Could you please help us here to update the screenshots at below section: https://docs.microsoft.com/en-us/microsoftteams/platform/m365-apps/overview#teams-messaging-extensions-in-outlook
Please Update the below image in document.
![image](https://user-images.githubusercontent.com/93527375/152348509-8d4bd1b6-7e3a-43bb-b8e3-a59667e5c691.png)
