### ISSUE TITLE
Has configuration flow of Office365 connector got changed recently?

### ISSUE THREAD

**Issue by piyumi25** [MicrosoftDocs/msteams-docs#5147]
I am developing a MS Teams Connector App. During my previous developments, I was able to create connectors and configured successfully according the documentation guidelines.
But today, I created a connector using connector developer portal and after trying to configure it using MS Teams App, I am getting following UI.
![image](https://user-images.githubusercontent.com/33615108/152315513-aa74fef1-8c5f-48c4-8dc5-bf5f8edd6589.png)
This is not configurable with the existing code. But for the connectors, I have created sometime back are working fine as expected.

**Comment by Meghana-MSFT** [comment]
We are also able to repro this issue. We are checking this internally. We will update you.

**Comment by piyumi25** [comment]
> We are also able to repro this issue. We are checking this internally. We will update you.

@Meghana-MSFT Thanks for your reply and looking for a fix ASAP

**Comment by Meghana-MSFT** [comment]
We have raised a bug for the same. The team is looking into it. We will let you know once the fix is available.

**Comment by piyumi25** [comment]
> We have raised a bug for the same. The team is looking into it. We will let you know once the fix is available.

Thank you very much @Meghana-MSFT

**Comment by piyumi25** [comment]
@Meghana-MSFT Can I have an update regarding the issue?

**Comment by Meghana-MSFT** [comment]
Team is looking into it. We do not have any ETA to share.

**Comment by piyumi25** [comment]
> Team is looking into it. We do not have any ETA to share.

Thanks

**Comment by wammaster** [comment]
Hello, I am also developing an application for Teams using connectors and I am facing the same issue.

Thank you for the support @Meghana-MSFT

**Comment by piyumi25** [comment]
@Meghana-MSFT Do you have any update about the issue?

**Comment by dooriya** [comment]
Got the same issue here:
![image](https://user-images.githubusercontent.com/10163840/154408867-da62e75f-d2ce-446b-b798-67bb78e8eb26.png)

**Comment by Meghana-MSFT** [comment]
We do not have any updates to share. Team is working on the fix.

**Comment by Meghana-MSFT** [comment]
@piyumi25 - Fix has been submitted. Could you please confirm if it is working fine at your end?

**Comment by piyumi25** [comment]
> @piyumi25 - Fix has been submitted. Could you please confirm if it is working fine at your end?

Thank you very much and now connector app is working fine

**Comment by Meghana-MSFT** [comment]
Thank you for confirming, we are closing this issue for now. Please feel free to reach out to us if you face any issue.
