### ISSUE TITLE
Order by date in conversations

### ISSUE THREAD

**Issue by martinezbohorquez** [MicrosoftDocs/msteams-docs#515]
OS: macOS Mojave version 10.14.3
Microsoft Teams: Version 1.0

Bug: not order by date in conversations

![image](https://user-images.githubusercontent.com/2292881/54834338-f66dc700-4c8d-11e9-9828-99efa861cf9d.png)

**Comment by Wajeed-msft** [comment]
@martinezbohorquez - There are replies to each of these conversation threads. Latest reply adds conversation thread to front. Please have a look at reply time (green boxes).   
![image](https://user-images.githubusercontent.com/31851992/54980012-a616a200-4fca-11e9-8dd5-dbedd8d4671a.png)
