### ISSUE TITLE
Sample Code Source

### ISSUE THREAD

**Issue by damienestewart** [MicrosoftDocs/msteams-docs#516]
What's the source for this sample code? How is `this.inTeams()` defined?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed3343e3-d546-7c4e-6e5c-64af6dd79a77
* Version Independent ID: 09a6a83f-f28b-7054-26c7-31dec6cb6367
* Content: [Using the control library - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/get-started/app-studio-component-library)
* Content Source: [msteams-platform/get-started/app-studio-component-library.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/get-started/app-studio-component-library.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by clearab** [comment]
Hi - this.InTeams() checks to see if the tab is loaded from a Teams tab, or if it loaded directly in a browser. It is unnecessary for the sample to function; I'll be removing it shortly.

Let us know if there is anything else we can assist with.
