### ISSUE TITLE
Full width adaptive card not displaying

### ISSUE THREAD

**Issue by pvasnmur** [MicrosoftDocs/msteams-docs#5169]
Adaptive card response via Message extension Submit action is not rendering in Full width.

Same Json play load using App studio Card Editor or Power Automate rendering in Full width without any issues.

Are there any limitations with Message extension Submit action rendering full width Adaptive card?

**Comment by Nivedipa-MSFT** [comment]
@pvasnmur - We are investigating your query. We will get back to you once we have any update.

**Comment by Nivedipa-MSFT** [comment]
@pvasnmur - We have tried Adaptive card response via Message extension Submit action. We have added following property in adaptive card for full width.
 "msTeams": {
    "width": "full"
  }
 Its working fine at our end. The card is renderring in Full width.
 We have tested on Teams web and desktop client version 1.5.00.3154

**Comment by Nivedipa-MSFT** [comment]
@pvasnmur - Could you please confirm is your issue resolved or are you still facing the issue?

**Comment by Nivedipa-MSFT** [comment]
@TheBluLion - Could you please share your sample code and screenshot to try at our end?

**Comment by Nivedipa-MSFT** [comment]
@pvasnmur - We have tried with your given Adaptive card payload. 
Its working fine at our end. The card is renderring in Full width.
We have tested on Teams web client.

Could you please share screenshot?
