### ISSUE TITLE
Adaptive Cards with imBack action doesn't include Input.Choice selected value in the post back

### ISSUE THREAD

**Issue by rebelanger** [MicrosoftDocs/msteams-docs#517]
My bot renders an Adaptive Card with an Action.Submit msteams imBack action as documented here : https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/Cards/cards-actions.md

```
{
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "type": "AdaptiveCard",
  "version": "1.0",
  "body": [
    {
      "type": "TextBlock",
      "text": "Select an item to get more infos"
    },
    {
      "type": "Input.ChoiceSet",
      "id": "CompactSelectVal",
      "style": "compact",
      "value": "1",
      "choices": [
        {
          "title": "Item-1",
          "value": "1"
        },
        {
          "title": "Item-2",
          "value": "2"
        }
      ]
    }
  ],
  "actions": [
    {
      "type": "Action.Submit",
      "title": "OK",
      "data": {
        "msteams": {
            "type": "imBack",
            "value": "Get more infos"
        }                 
      }
    }
  ]
}
```

When the OK button is clicked, the selected value from the Input.ChoiceSet is not part of the post back.

```
{"text":"Get more infos","textFormat":"plain","type":"message","timestamp":"2019-03-22T21:43:00.478Z","localTimestamp":"2019-03-22T21:43:00.478Z","id":"1553290980423","channelId":"msteams","serviceUrl":"https://smba.trafficmanager.net/emea/","from":{"id":"29:1pZuEqSeogjB6P806GywrlShMbW4u-9LqtQKq0plKvflMAAAjElV5mAracyXPBC8iFo8RzK9sPg4YIHy3u0vDzQ","name":"John Doe","aadObjectId":"28b3a689-d669-499d-a071-99eb4db63dd2"},"conversation":{"conversationType":"personal","id":"a:1GEzcMuwobCUMexBwA8no2fUb_5Oe39NJcPvZvMEfwPIw_yXcxJUXpEiRCzpdm_RplvjEDcZjyNkxSsFNmb6jhd7fOq83AAMGgCoOYkIJ_GI22IUZyhaxHTJ82YYnjLkt"},"recipient":{"id":"28:ac9b0c5d-8e62-4645-97cb-e7b58e726d8e","name":"MyBot"},"entities":[{"locale":"fr-CA","country":"CA","platform":"Web","type":"clientInfo"}],"channelData":{"tenant":{"id":"09823185-47c0-4fbb-83b6-532adbffc878"}},"locale":"fr-CA"}
```

Any help would be appreciated.

Thanks.

**Comment by Gousia-MSFT** [comment]
@rebelanger imBack action sends only a message to the bot whereas messageBack sends message and payload to the bot. Could you please try using [messageBack](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/cards/cards-actions#adaptive-card-with-messageback-action) instead of imBack action, that should give the choice selected in postback.
`{
      "type": "Action.Submit",
      "title": "OK",
      "data": {
        "msteams": {
          "type": "messageBack",
          "value": "Get more infos"
        }
      }
    }`

**Comment by rebelanger** [comment]
@Gousia-MSFT Thanks! I wanted to use an imBack action because it doesn't reset the selected value displayed when the button is pressed. With a messageBack, the value that has been selected is replaced with the default value and the user needs to reselect it before pressing another button for instance.
