### ISSUE TITLE
Sample Hello World app does not appear in sideloaded list

### ISSUE THREAD

**Issue by pawoolley** [MicrosoftDocs/msteams-docs#5179]
Step 2 says:

```
Select Manage your apps. Your app is listed in the sideloaded apps.
```

1. Do you mean leave leave Developer Portal, go to Apps and then selected Manage your apps?  This part is not clear.
2. I go to Apps > Manage your apps, but don't see the Hello World app anywhere.  There's no "sideloaded apps" list and searching for the app finds nothing.  I've tried tearing things down and re-doing, but I cant' get this tutorial to work.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1321426-bc5d-1b04-bcf6-5b6ae6100673
* Version Independent ID: b1321426-bc5d-1b04-bcf6-5b6ae6100673
* Content: [Hello World with Node.js - Teams](https://docs.microsoft.com/en-gb/microsoftteams/platform/sbs-gs-nodejs?tutorial-step=4)
* Content Source: [msteams-platform/sbs-gs-nodejs.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/sbs-gs-nodejs.yml)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Nivedipa-MSFT** [comment]
@pawoolley - Have you enabled the sideloading option?
In [prerequisites](https://docs.microsoft.com/en-gb/microsoftteams/platform/sbs-gs-nodejs?tutorial-step=1) its mention to enable the sideloading option.

After clicking on Preview in Teams its redirected to the Teams and shown the popup for Adding App like below image

<img width="565" alt="add-nodejs-app-sideload" src="https://user-images.githubusercontent.com/92150070/152533199-0df1b297-5f06-4e81-a9ac-e6edfbf86852.png">

Could you please try to enable the sideloading option and check again.

**Comment by pawoolley** [comment]
As far as I know, yes, I did follow the steps to enable sideloading.  The screenshots in the docs don't match what I see exactly, but I do see the option to update a customer app.  Under Apps > Manage your apps, I see:

![image](https://user-images.githubusercontent.com/38104239/152538968-5c63d245-3ef8-4315-9e18-c263f242a3e4.png)

**Comment by Nivedipa-MSFT** [comment]
@pawoolley - Could you please check if your application is available in Apps > Build for org.
If it is not available try to publish your application and upload manually vai App > Manage your app > upload custom app.

**Comment by pawoolley** [comment]
> Could you please check if your application is available in Apps > Build for org.

There is no Apps > Build for org.  I only see Apps > Built by your colleagues.

> If it is not available try to publish your application and upload manually vai App > Manage your app > upload custom app.

I tried this.  A dialog pops up asking me to Add the app.  I click on the Add button, then I get a dialog saying "Something went wrong" with no further explanation.

<img width="500" src="https://user-images.githubusercontent.com/38104239/152964260-2a5c026d-9094-4830-83db-b14fa08b23d1.png">

Also, during the import process, I was seeing an error about the incorrect sizing of the icon files.

<img width="500" alt="App package has errors" src="https://user-images.githubusercontent.com/38104239/152964421-1fcc17db-f2fd-4029-8351-fd2e5b94b51f.png">

I fixed this by creating a blank 192x192 png to replace the colour icon and a blank 32x32 png to replace the icon outline.  It made that error box go away, but hasn't fixed the larger issue of not seeing this Hello World app getting loaded.

**Comment by Nivedipa-MSFT** [comment]
@pawoolley - Could you please share your manifest to try at our end?

**Comment by pawoolley** [comment]
Sure.  I'm not sure how useful it will be because it is just the one that comes with the hello world app nodejs sample:

[helloworldapp.zip](https://github.com/MicrosoftDocs/msteams-docs/files/8024365/helloworldapp.zip)

Interestingly, if I try to import/create an app through the developer portal, and then click on Publish > App package, I don't see the app's manifest shown to me.  This happens on both the desktop app (MacOS Monterey) and the browser client (Chrome v97).

![image](https://user-images.githubusercontent.com/38104239/153003372-f2b64f8d-d21a-472b-9395-2fee1773a2c0.png)

**Comment by serv** [comment]
Hi @Nivedipa-MSFT ,
Is there any update to this issue? 
Thanks.

**Comment by Nivedipa-MSFT** [comment]
@serv - We have informed Engineering team about the same and they are currently working on the fix. We will inform you once we have further update. Thanks!

**Comment by breakpoint7** [comment]
Came here to report the same issue.  Doesn't look like this has been fixed.  All of the getting started demos walk through this same scenario to "Preview in Teams" and tell the user to find their app in the sideloaded apps .... which doesn't exist anywhere in the UI.  I get the confirmation it has been sideloaded okay, but can't find it anywhere in the UI or App List.  People go through the entire demo to end up with something that doesn't work in the docs.  Please fix this or update the docs.

**Comment by Nivedipa-MSFT** [comment]
@breakpoint7 - We are checking with the engineering team. We will let you know once we have any update.

**Comment by VladMilyutin** [comment]
Hello, all. I have the same problems.

**Comment by Nivedipa-MSFT** [comment]
@VladMilyutin - We are checking with the engineering team. We will let you know once we have any update.

**Comment by Nivedipa-MSFT** [comment]
@pawoolley - Engineering team is currently working on the fix.  We will inform you once we have any updates.

**Comment by stuport** [comment]
Hi, is there any updates to this please? The walkthrough was working (although the walkthrough does not match the UI most of the time) then about 2 weeks ago it just stopped. If you follow it through (I am following the Microsoft.Teams.Samples.HelloWorld.Web), I cant view the app package under publish (you get a message saying ‘Nothing to see here yet. In order to edit this aspect of the app, it needs to be more complete. Resolve any validation issues shown in the Overview and try again‘ or side load (all you get is the behaviour mentioned in the threads above). If you don’t have a fix, is there a way to workaround this so we can get on with developing our app? It seems to have happened when version 1.13 of the manifest was released… thanks!

**Comment by ChetanSharma-msft** [comment]
Hello @surbhigupta12 - Can you please help us here to update the documentation?

**Comment by surbhigupta12** [comment]
This peer needs to be closed and no further action needed.
