### ISSUE TITLE
Developer Preview link redirects to 404

### ISSUE THREAD

**Issue by DanielLarsenNZ** [MicrosoftDocs/msteams-docs#518]
Developer Preview links to &lt;https://docs.microsoft.com/en-us/microsoftteams/platform/resources/dev-preview/developer-preview&gt; which redirects to &lt;https://docs.microsoft.com/en-us/microsoftteams/platform/resources/dev-preview/developer-preview-intro.md&gt; which is not found. The link should probably redirect to &lt;https://docs.microsoft.com/en-us/microsoftteams/platform/resources/dev-preview/developer-preview-intro&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 328c86a9-1384-3f07-0b68-947f5ad9b5ab
* Version Independent ID: 9a8e000a-87ed-1357-0b28-feee59311149
* Content: [Upload your custom app in Microsoft Teams - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/apps/apps-upload#feedback)
* Content Source: [msteams-platform/concepts/apps/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/apps/apps-upload.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by clearab** [comment]
Thanks for letting us know, it will be fixed shortly.
