### ISSUE TITLE
Need help to add sample code link - People picker control in Adaptive Cards

### ISSUE THREAD

**Issue by AbhijeetThakur-msft** [MicrosoftDocs/msteams-docs#5180]
Hello Team,

We have created a sample to show People picker in Adaptive card in C# and nodejs.
Please help to add the same in document.

|    | Sample Name        | Description                                                                                                                | C#    | Nodejs
|:--:|:-------------------|:---------------------------------------------------------------------------------------------------------------------------|:--------|:-------------|
|1|People picker control in Adaptive Cards           | This sample shows the feature of people picker control in Adaptive Cards.                                     |[View](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/bot-people-picker-adaptive-card/csharp)     |[View](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/bot-people-picker-adaptive-card/nodejs)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8cc6c1f-7946-e074-e2c3-da2d24e0acc6
* Version Independent ID: c8cc6c1f-7946-e074-e2c3-da2d24e0acc6
* Content: [People Picker in Adaptive Cards - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/people-picker?tabs=desktop)
* Content Source: [msteams-platform/task-modules-and-cards/cards/people-picker.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/task-modules-and-cards/cards/people-picker.md)
* Product: **msteams**
* GitHub Login: @Rajeshwari-v
* Microsoft Alias: **surbhigupta**

**Comment by v-chetsh** [comment]
Hello @surbhigupta12 - Could you please help us here to update the contents?
