### ISSUE TITLE
Clarification around Azure requirments for application-hosted media bots

### ISSUE THREAD

**Issue by ring-pete** [MicrosoftDocs/msteams-docs#5183]
The the first section of this documentation it states `The bot must be deployed on a Windows Server machine or Windows Server guest Operating System (OS) in Azure.`  This wording is confusing, does this state that both the Windows Server machine and the guest OS must run in Azure.  Or can the Windows Server machine run on-prem or on another platform?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6be953e-43af-0b42-6a9f-ed7776c595bb
* Version Independent ID: a8b8d285-955f-1f86-1484-6a75aa8ffaf8
* Content: [Requirements and considerations for application-hosted media bots - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/calls-and-meetings/requirements-considerations-application-hosted-media-bots#feedback)
* Content Source: [msteams-platform/bots/calls-and-meetings/requirements-considerations-application-hosted-media-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/bots/calls-and-meetings/requirements-considerations-application-hosted-media-bots.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by v-chetsh** [comment]
@ring-pete - We will check on it and take a action accordingly.

**Comment by Nivedipa-MSFT** [comment]
@ring-pete - It states that **The bot must be deployed on a Windows Server on-prem machine, or Windows Server guest Operating System (OS) in Azure.**

**Comment by Nivedipa-MSFT** [comment]
Redirecting to documentation team to update the document.

@surbhigupta12 - Could you please update the following document it states that `The bot must be deployed on a Windows Server machine or Windows Server guest Operating System (OS) in Azure`. As this wording is confusing,
[Requirements and considerations for application-hosted media bots - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/calls-and-meetings/requirements-considerations-application-hosted-media-bots#feedback)

Content to Add in doc: **The bot must be deployed on a Windows Server on-prem machine, or Windows Server guest Operating System (OS) in Azure.**
