### ISSUE TITLE
Why does the left nav list node and .net but the SDK reference only has JS, and where is the _actual_ API?

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/msteams-docs#519]
The Teams client is more windows convention friendly than slack, but both are still UI kludgy.  Is there a way to correct the layout and some behaviors of the Teams client? If not, where are the services API docs?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f57a31a0-e815-faa4-653d-795ae8a8e4d7
* Version Independent ID: 8f48ea3d-231b-2776-41b7-11890ea2d3c0
* Content: [Developer platform - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/overview)
* Content Source: [msteams-platform/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/overview.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Wajeed-msft** [comment]
Could you please share more details on what layout or behaviour you are looking to modify? 

Here are the SDK references: 
[Microsoft Teams JavaScript client SDK](https://docs.microsoft.com/en-us/javascript/api/overview/msteams-client?view=msteams-client-js-latest)
[Get started with Node.js](https://docs.microsoft.com/en-us/microsoftteams/platform/get-started/get-started-nodejs-app-studio?view=msteams-client-js-latest)
[Get started with C#/.NET](https://docs.microsoft.com/en-us/microsoftteams/platform/get-started/get-started-dotnet-app-studio?view=msteams-client-js-latest)

**Comment by StingyJack** [comment]
hi @Wajeed-msft, which of those have the api information for retrieving channel lists and a channel's conversations, or sending messages, etc.?

which of those would let me alter the ui to do things like make the left column auto hide, or integrate the /commands with the text entry box, or generally make the ui easier to read with less visual noise?

**Comment by Wajeed-msft** [comment]
@StingyJack - Please have a look at [Microsoft Teams Graph APIs](https://docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-1.0) documentation which shows different services exposed for Microsoft Teams.

**Comment by StingyJack** [comment]
Thanks for the API link, I wouldn't have thought to look all the way over there for it. Is there anything for the UI customization specifically? Or a GH issues repo/feedback collector for the teams client?

**Comment by Wajeed-msft** [comment]
@StingyJack - Graph API are referenced in Resources section here: https://docs.microsoft.com/en-us/microsoftteams/platform/resources/microsoft-graph

Here are the feedback channels: https://docs.microsoft.com/en-us/microsoftteams/platform/feedback
