### ISSUE TITLE
[MSTeams] Can we implement same thing using bot framework composer 

### ISSUE THREAD

**Issue by Sujit-Gaikwad** [MicrosoftDocs/msteams-docs#5220]
Hi,
Recently we have tried this feature in our bot at working smoothly but now we are wanted to create bot with composer with the same features though we have OAuth card in composer instead of using that we would like go for SSO.

is there any way to implement the same in composer?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9549caa9-99a2-2568-19a5-f21a79292e2f
* Version Independent ID: f2100d03-b88a-34b2-44a2-935231e89db0
* Content: [Single sign-on support for bots - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/authentication/auth-aad-sso-bots)
* Content Source: [msteams-platform/bots/how-to/authentication/auth-aad-sso-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/bots/how-to/authentication/auth-aad-sso-bots.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by v-chetsh** [comment]
Are you looking for implementing SSO for Messaging Extension?
If yes, you can refer below doc:
https://docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/enable-sso-auth-me

**Comment by Nivedipa-MSFT** [comment]
@Sujit-Gaikwad - Could you please confirm if the above suggestion helped you in any way or are you still looking for any help?

**Comment by Sujit-Gaikwad** [comment]
@Nivedipa-MSFT  thanks for the document. 
I will go through the document and update ASAP

**Comment by Sujit-Gaikwad** [comment]
@Nivedipa-MSFT Sorry this is not the relevant document 
I was looking for SSO in composer bot

**Comment by Nivedipa-MSFT** [comment]
@Sujit-Gaikwad - Using skill you can do SSO in composer bot.
You can go through below doc for more details.
https://docs.microsoft.com/en-us/composer/how-to-single-sign-on-skill

**Comment by Nivedipa-MSFT** [comment]
@Sujit-Gaikwad  - Could you please confirm if the above suggestion helped you in any way or are you still looking for any help?

**Comment by Sujit-Gaikwad** [comment]
hi @Nivedipa-MSFT  I have gone through it but I'm afraid that this is not the one we are looking for
 
We have bot created with virtual agent template in that we have implemented SSO. But as MS has decided not to give further update on the template so they suggest us to move to the composer.

We have referred the below link to implement SSO in our current bot engine : [msteams-platform/bots/how-to/authentication/auth-aad-sso-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/bots/how-to/authentication/auth-aad-sso-bots.md) 

Now our objective is to achieve same behavior in composer bot.
 
we do have option to use oAuth card in composer but it is having some limitation mobile device and that is why we are not thinking of it

If you can help me with repos or similar link to the document which can referred to implement SSO in composer will be great help 

Thanks
Sujit sanjay gaikwad

**Comment by Nivedipa-MSFT** [comment]
@Sujit-Gaikwad - Could you please share which document you are referring for composer bot?

**Comment by Sujit-Gaikwad** [comment]
hi @Nivedipa-MSFT 
PFB ,
**OAuth  in composer** : https://docs.microsoft.com/en-us/composer/how-to-use-oauth?tabs=v2x

**Comment by Nivedipa-MSFT** [comment]
@Sujit-Gaikwad - We have confirm with engineering team that SSO is not supported to implement in composer.

**Comment by Sujit-Gaikwad** [comment]
Hi Team thanks for confirmation
