### ISSUE TITLE
Issue not fixed: Android Teams app overwriting Teams context.EntityId

### ISSUE THREAD

**Issue by nbelyh** [MicrosoftDocs/msteams-docs#5226]
Previous occurrences of the issue with detailed description (regression):

https://github.com/MicrosoftDocs/msteams-docs/issues/1335
https://github.com/MicrosoftDocs/msteams-docs/issues/2690

Tested with the latest version from 1. February 2022, build 1416

Android Teams app is **STILL** overwriting Teams context.EntityId with random guid :frowning_face:
This prevents "deep links" to a custom tab from working on android (the link includes entityid).

Note: this works fine on web, desktop, and iOS (but not on android)

**Comment by Wajeed-msft** [comment]
Thanks @nbelyh for taking time to report this. We will repro this at our end and re-open the bug.

**Comment by nbelyh** [comment]
Thank you. For me, the problem is that this issue is preventing deep links to my tab from working 😢

**Comment by sayali-MSFT** [comment]
@nbelyh -we have tested with android It's working fine, could you please also check and confirm?

**Comment by nbelyh** [comment]
Unfortunately, it is still not working for me. I will create a separate repository to reproduce the issue.
