### ISSUE TITLE
Link Unfurling completely doesn't document requirement to have preview for adaptive cards.

### ISSUE THREAD

**Issue by tomlm** [MicrosoftDocs/msteams-docs#5233]
See this tech community post:
https://techcommunity.microsoft.com/t5/teams-developer/unfurlink-link-adaptive-card-in/m-p/2020064 

Documentation does not document this requirement *anywhere*.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59bbff2e-4b80-f980-2ade-7c7a7950801e
* Version Independent ID: e837e1fd-ec0c-2d6f-b0db-b76cb2d268a4
* Content: [Link unfurling - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?tabs=json)
* Content Source: [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/messaging-extensions/how-to/link-unfurling.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **anclear**
*

**Comment by sayali-MSFT** [comment]
@tomlm -We are looking into this I will get back to you soon.

**Comment by sayali-MSFT** [comment]
@tomlm - In [Link unfurling](https://docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?tabs=json#handle-the-composeextensionquerylink-invoke) document they are provide some link which are redirect to code for [adaptive card](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference#adaptive-card).
Could you please check it once? If Required, then we redirect to concern team for update the document.

**Comment by sayali-MSFT** [comment]
@tomlm -Could you please confirm if your issue has resolved with above suggestion or still looking for any help?

**Comment by v-chetsh** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.
