### ISSUE TITLE
Microsoft Teams "Hello World" messaging extension is not working_Something went wrong with this app

### ISSUE THREAD

**Issue by XimenaWang** [MicrosoftDocs/msteams-docs#524]
Hi team, The Tab and Bot works fine for this sample,just is not working for Messaging extension.
Bot ID:5caeb438-a84a-4e04-be9a-325534a52bf7
can you please take a look for this app ,thanks !

![image](https://user-images.githubusercontent.com/30890958/54978545-e7bd3380-4f5d-11e9-8a7e-0ad9f915da48.png)

**Comment by Wajeed-msft** [comment]
@XimenaWang - Could you please try putting breakpoint in _HandleMessageExtensionQuery()_ in [MessageExtension.cs](https://github.com/OfficeDev/msteams-samples-hello-world-csharp/blob/master/Microsoft.Teams.Samples.HelloWorld.Web/MessageExtension.cs#L12) class? Check if request is hitting this code and if there is any exception.

**Comment by XimenaWang** [comment]
@Wajeed-msft ， Hi Wajeed, it seems the activity.IsComposeExtensionQuery() is always false, so the HandleMessageExtensionQuery() can't be executed.   
![image](https://user-images.githubusercontent.com/30890958/55535054-dd401f80-566a-11e9-8bdf-19b4df53e8de.png)
How can I trigger the Message Extension? Currently I inputted the command "getRandomText" doesn't work .
![image](https://user-images.githubusercontent.com/30890958/55535038-cdc0d680-566a-11e9-9466-7d997b24a1ff.png)

**Comment by Wajeed-msft** [comment]
@XimenaWang - Could you please try it once from Message extension menu?
![image](https://user-images.githubusercontent.com/31851992/55536740-28444c00-56d8-11e9-9c40-57aec84f5fae.png)

**Comment by XimenaWang** [comment]
@Wajeed-msft - it still doesn't work, same issue.
![image](https://user-images.githubusercontent.com/30890958/55695466-8c337280-596d-11e9-801a-6601d92b32df.png)
but I modified my code to only return Ok, and then pushed to Azure, but same issue. Kindly let me know if I miss any configuration.
![image](https://user-images.githubusercontent.com/30890958/55695635-5e9af900-596e-11e9-9bb6-8b90cfd21a48.png)

**Comment by Gousia-MSFT** [comment]
@XimenaWang Could you please try replacing the Image for the card in MessageExtension.cs at line 46 with the following:
![image](https://user-images.githubusercontent.com/45553518/55723186-fe678e00-5a25-11e9-8e9b-42a4bc280cac.png)


If this does not work, please share your manifest file with us.

**Comment by clearab** [comment]
The messaging extension uses a publicly available website to generate random images. Unfortunately, that website isn't 100% reliable, and when it fails the messaging extension does not handle it gracefully. We'll be improving this is a future release. @Gousia-MSFT's solution above should unblock you.

**Comment by billbliss** [comment]
I actually fixed this in the [Node sample](https://github.com/OfficeDev/msteams-samples-hello-world-nodejs/blob/master/src/messaging-extension.js). Lorempixel.com has been down for a long time and the Faker library we use to generate random data hasn't been updated as far as I know.

I haven't tested it, but if you change  

`                Images = { new CardImage("http://lorempixel.com/640/480?rand=" + DateTime.Now.Ticks.ToString()) }`

to 

`                Images = { new CardImage("http://loremflickr.com/200/200?random=" + DateTime.Now.Ticks.ToString()) }`

it should work.

**Comment by XimenaWang** [comment]
@Gousia-MSFT @clearab @billbliss Thanks all of you, I replaced the image url , doesn't work. the new image url: https://emojipedia-us.s3.amazonaws.com/thumbs/120/microsoft/106/face-without-mouth_1f636.png

![image](https://user-images.githubusercontent.com/30890958/55777124-ce36e400-5a53-11e9-88d5-3b549d7068bc.png)
and here is my manifest file:

[helloworldapp.zip](https://github.com/MicrosoftDocs/msteams-docs/files/3057403/helloworldapp.zip)

**Comment by Gousia-MSFT** [comment]
@XimenaWang Could you replace the image with:
``Images = new System.Collections.Generic.List<CardImage>{ new CardImage("http://lorempixel.com/640/480?rand=" + DateTime.Now.Ticks.ToString()) }`` once and check

**Comment by Wajeed-msft** [comment]
Please re-open if you are still facing this issue.
