### ISSUE TITLE
[Rendering] [Android] Adaptive Card in Task Module does not expand to fill available width

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#5250]
Copied bug from: https://github.com/microsoft/AdaptiveCards/issues/7039 

**Details from original post:**
### Target Platforms

Android

### SDK Version

2.7.2

### Application Name

Microsoft Teams

### Problem Description

When rendering an adaptive card in a task module with a column width set to "stretch" the column does _not_ stretch to fill the container. The same card renders fine on web, desktop, and iOS versions of Teams.

### Screenshots

![Screenshot_20220208-160601](https://user-images.githubusercontent.com/6415446/153097487-de3bc9b4-c248-4f5d-9fae-6a1736cc0887.png)

### Card JSON

```JSON
{
	"type": "AdaptiveCard",
	"body": [
        {
            "type": "ColumnSet",
            "columns": [
                {
                    "type": "Column",
                    "items": [
                        {
                            "type": "Image",
                            "style": "default",
                            "url": "https://pbs.twimg.com/profile_images/3647943215/d7f12830b3c17a5a9e4afcc370e3a37e_400x400.jpeg",
                            "size": "Small"
                        }
                    ],
                    "width": "auto"
                },
                {
                    "type": "Column",
                    "width": "stretch",
                    "verticalContentAlignment": "center",
                    "items": [
                        {
                            "type": "TextBlock",
                            "weight": "Bolder",
                            "text": "This column should stretch to fill the available space."
                        }
                    ]
                }
            ]
        }
	],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "msteams": {
        "width": "Full"
    },
    "version": "1.4"
}
```

### Sample Code

_No response_---
#### Document Details

⚠ *Do not edit this section.It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Cards reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **surbhigupta12**

**Comment by sayali-MSFT** [comment]
@jrburek - We are looking into this I will get back to you soon.

**Comment by sayali-MSFT** [comment]
@jrburek -We are unable to repro the issue. with image and text.It's working fine for us. Could you just check it once or share the repro steps so we can tried our end?
![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/93527375/154255775-387d0b98-3abd-408d-8978-590fbfe635ad.png)

**Comment by JordyGit** [comment]
The issue is an adaptive card in a task module, so yes normal adaptive card works just fine.

**Comment by jrburek** [comment]
Correct, I don't see this issue with adaptive cards posted as messages, only when they are used in the full screen task module.

**Comment by matthiasdilger** [comment]
@sayali-MSFT It seems that adaptive cards in task modules on Android need a leading TextBlock to go full width

ie this card works fine in a task module and the Input.Text is full width:
```
{
        "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
        "type": "AdaptiveCard",
        "version": "1.0",
        "body": [
              {
                "type": "TextBlock",
                "text": "Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum",
                "id": "text",
                "wrap": true                
              },              
              {
                "type": "Input.Text",
                "id": "inputText",
                "placeholder": "Some placeholder",
                "maxLength": 2000,
                "isMultiline": true,
                "isVisible": true
              },              
              {
                "type": "ActionSet",
                "id": "actionSet",
                "actions": [
                  {
                    "type": "Action.ToggleVisibility",
                    "title": "Press me",
                    "targetElements": [ "text", "inputText" ]
                  }                
                ]
              }
]}
```
![Screenshot_20220217-124900](https://user-images.githubusercontent.com/5625718/154407887-d6e5207a-8127-42b7-bb13-81e0bdaecb39.png)

But this card is too small and it is difficult to enter text:
```
{
        "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
        "type": "AdaptiveCard",
        "version": "1.0",
        "body": [              
              {
                "type": "Input.Text",
                "id": "inputText",
                "placeholder": "Some placeholder",
                "maxLength": 2000,
                "isMultiline": true,
                "isVisible": true
              },              
              {
                "type": "ActionSet",
                "id": "actionSet",
                "actions": [
                  {
                    "type": "Action.ToggleVisibility",
                    "title": "Press me",
                    "targetElements": [ "inputText" ]
                  }                
                ]
              }
]}
```

![Screenshot_20220217-124822](https://user-images.githubusercontent.com/5625718/154408044-479eadc4-7820-45e0-92ad-73b8741bf193.png)

**Comment by sayali-MSFT** [comment]
@jrburek,@matthiasdilger- We are unable to repro the issue. We are tried with your given Adaptive json. 
Android Teams Version:-1416/1.0.0
Android Version:-8.1.0
![MicrosoftTeams-image (7)](https://user-images.githubusercontent.com/93527375/154469109-8edd37bc-fc4d-4a1c-8d13-bf49669db172.png)
![MicrosoftTeams-image (8)](https://user-images.githubusercontent.com/93527375/154469256-e3561226-7a0a-46e5-97ab-b3128f2353c4.png)

**Comment by matthiasdilger** [comment]
@sayali-MSFT The issue occurs for me on Android 12 (physical device) with Teams Android version 1416/1.0.0.2022223102/0201 
I tried enabling/disabling the developer preview setting but it did no make a difference

**Comment by jrburek** [comment]
I'm seeing similar behavior. The ColumnSet does seem to stretch to fill its container but its container doesn't appear to start full screen. If another element is added that forces a larger width (e.g. a TextBlock with enough text in it) then the ColumnSet stretches to accommodate. If no other element is present, or the additional elements are too small themselves, then the rendering is incorrect.

Is there some additional property on the Attachment or on the TaskModuleInfo that needs to be set to get the desired behavior? Below is the full response I send:
`{
    "task": {
        "value": {
            "title": "Android Test",
            "card": {
                "contentType": "application/vnd.microsoft.card.adaptive",
                "content": {
                    "type": "AdaptiveCard",
                    "version": "1.4",
                    "height": "auto",
                    "body": [
                        {
                            "type": "Container",
                            "items": [
                                {
                                    "type": "ColumnSet",
                                    "columns": [
                                        {
                                            "type": "Column",
                                            "width": "auto",
                                            "items": [
                                                {
                                                    "type": "Image",
                                                    "size": "small",
                                                    "url": "https://pbs.twimg.com/profile_images/3647943215/d7f12830b3c17a5a9e4afcc370e3a37e_400x400.jpeg",
                                                    "height": "auto"
                                                }
                                            ],
                                            "height": "auto"
                                        },
                                        {
                                            "type": "Column",
                                            "width": "stretch",
                                            "items": [
                                                {
                                                    "type": "TextBlock",
                                                    "weight": "bolder",
                                                    "text": "This column should stretch to fill the available space.",
                                                    "height": "auto"
                                                }
                                            ],
                                            "verticalContentAlignment": "center",
                                            "height": "auto"
                                        }
                                    ],
                                    "height": "auto"
                                }
                            ],
                            "height": "auto"
                        }
                    ],
                    "actions": [],
                    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
                    "msteams": {
                        "width": "Full"
                    }
                }
            }
        },
        "type": "continue"
    }
}`

**Comment by sayali-MSFT** [comment]
@matthiasdilger,@jrburek -we are able to repro the issue with android version 11.We have raised bug for the same and concerned team is looking into it. We will inform you once we get any update.

**Comment by matthiasdilger** [comment]
@sayali-MSFT This issue has been fixed for me in the lastest Teams Android release. Thanks!
