### ISSUE TITLE
Suggested updates to the "Single Sign-On Support for Bots" page

### ISSUE THREAD

**Issue by anishprasad01** [MicrosoftDocs/msteams-docs#5252]
After correspondence with Teams folks and personal experience with the documentation, I think the [SSO in bots](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/authentication/auth-aad-sso-bots) page could use a few updates to reflect changes in related menus and content. Of course if any of the suggested changes are incorrect, please feel free to suggest modifications or ignore them.

In [Develop an SSO Teams Bot](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/authentication/auth-aad-sso-bots#develop-an-sso-teams-bot):
- Steps 7 & 8 are out of order. It might make more sense to merge them with Step 22, as they essentially suggest the same things but with hyperlinks.
  - Perhaps a note that the Teams auth sample bot only needs the `User.Read` permission.
- Step 23 should be done in or alongside Step 21. The check boxes are within the pop-up menu used in that step, so it does not make sense to leave that page and then come back to it.

In [Update Azure Portal](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/authentication/auth-aad-sso-bots#update-the-azure-portal-with-the-oauth-connection):
- In Step 4, I found the description of the format for the `Token Exchange URL` to be confusing. Perhaps this could be updated to better specify that this is referring to the `api://botid-<your-app-id>/`.

Lastly, the [Update the auth sample](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/authentication/auth-aad-sso-bots#update-the-auth-sample) section appears way at the bottom of the page, and its possible users who are simply trying to get sample 46 to run might miss it. A note somewhere higher-up on the page might help.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9549caa9-99a2-2568-19a5-f21a79292e2f
* Version Independent ID: f2100d03-b88a-34b2-44a2-935231e89db0
* Content: [Single sign-on support for bots - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/authentication/auth-aad-sso-bots#develop-an-sso-teams-bot)
* Content Source: [msteams-platform/bots/how-to/authentication/auth-aad-sso-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/bots/how-to/authentication/auth-aad-sso-bots.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Meghana-MSFT** [comment]
Thank you for suggesting the modifications. We are looking into it, We will update you.

**Comment by Meghana-MSFT** [comment]
@surbhigupta12 - Can you please make the following changes 

in [Register your app through the Azure AD portal](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/authentication/auth-aad-sso-bots#register-your-app-through-the-azure-ad-portal)

1. Please add step 23 after step 21
2. Please remove step 7 and step 8.
3. Modify step 22 as below

  Add necessary [API Permissions](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-permissions-and-consent)

-   Select API permissions from the left plane.
- Select Add a platform to add any permissions that your app requires to downstream APIs, for example, 
  User.Read.


in [Update the Azure portal with the OAuth connection](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/authentication/auth-aad-sso-bots#update-the-azure-portal-with-the-oauth-connection)

1.  Please add `api://botid-<your-app-id>/` as an example of Token Exchange URL.

**Comment by Meghana-MSFT** [comment]
@anishprasad01 - Generally all the code samples are placed at the end in every document. It is mentioned in the contents list in the top right as Code Sample.

**Comment by v-chetsh** [comment]
@surbhigupta12 - Please help us here to update the contents.
