### ISSUE TITLE
DeepLink for existing Chat

### ISSUE THREAD

**Issue by paz0ok** [MicrosoftDocs/msteams-docs#5255]
Moin moin erveryone,

I am looking for a solution to open a created chat with a deeplink.
We create a chat with the Graph API an store the Chat ID. After the chat is created we want to open the chat in the desktop app.

At the moment we send the following URL:
`https://teams.microsoft.com/_#/conversations/<CHATID>?ctx=chat`

This opens the Chat but not in the App only in the default Browser.
Since the Chat is already created, I dont want to use this link:
`https://teams.microsoft.com/l/chat/0/0?users=<user1>,<user2>,...&topicName=<chat name>&message=<precanned text>`

When I recieve a Mail for a chat from Teams, there is a deeplink that opens the App but I don't know what kind of ID is used. The URL looks like this:
`https://urlshortener.teams.microsoft.com/8D3EFACF34016D1-3-12`

Dose anyone hase a solution?

Kind regard and Thanks :)

**Comment by sayali-MSFT** [comment]
@paz0ok - We are looking into this I will get back to you soon.

**Comment by paz0ok** [comment]
Thanks a lot! I am excited to hear from you!

I have just found a workaround.
I used the protokoll msteams:// and this seams to be working. Only thing why I think this hase more the character of a workaround is that the user has to confirm that my webpage is allowed to open this protokoll and allow MS Teams to be opended with this protokoll.

So the Workaround looks like this:

`msteams://dl/conversations/<CHATID>@thread.v2?ctx=chat`

**Comment by JordyGit** [comment]
I've also was looking for a consistent deep link to a certain conversation (private, group, thread). This was my stackoverflow question if it already existed: https://stackoverflow.com/questions/70892336/microsoft-teams-redirect-url-to-a-thread-or-group-conversation

**Comment by sayali-MSFT** [comment]
@paz0ok - this is for security improvement.
![Chrome](https://user-images.githubusercontent.com/93527375/154456607-3c309f49-f4e0-4b97-8562-1019f260c353.png)

**Comment by paz0ok** [comment]
Thanks for your support. The link I posted workers for us 🙂👍🏼
