### ISSUE TITLE
Some properties are missing

### ISSUE THREAD

**Issue by billbliss** [MicrosoftDocs/msteams-docs#527]
Looking at the latest SDK source, there are some context values missing. I noticed these two:
```
  /**
   * The root SharePoint folder associated with the team.
   */
  teamSiteUrl?: string;

  /**
   * The relative path to the SharePoint folder associated with the channel.
   */
  channelRelativeUrl?: string;
```
Probably need to do an audit of the context properties.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 525acdf7-3f72-b657-63ea-ddb95c4fb247
* Version Independent ID: c5d9575a-ace3-8441-4516-ad2c7adb3d99
* Content: [Get context for your tab - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/tabs/tabs-context)
* Content Source: [msteams-platform/concepts/tabs/tabs-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/tabs/tabs-context.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by clearab** [comment]
Looks like this was resolved with the latest sync of the docs from the package
