### ISSUE TITLE
[Rendering][iOS] Adaptive card as task module does not render if it includes Action.Submit

### ISSUE THREAD

**Issue by matthiasdilger** [MicrosoftDocs/msteams-docs#5271]
User presses Teams message on iOS and swipes to action based message extensions and selects bot
Bot receives composeExtension/fetchTask and returns this card:
```
{
 "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
        "type": "AdaptiveCard",
        "version": "1.0",
        "body": [          
              {
                "type": "TextBlock",
                "text": "Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum",
                "id": "text",
                "wrap": true                
              },              
              {
                "type": "Input.Text",
                "id": "inputText",
                "placeholder": "Some placeholder",
                "maxLength": 2000,
                "isMultiline": true,
                "isVisible": true
              },                            
              {
                "type": "ActionSet",
                "id": "actionSet",
                "actions": [
{
                    "type": "Action.Submit",                    
                    "title": "Submit",                    
                    "data": {
                      "type": 1
                    }
                  }  
                ]
              }
]}
```

iOS then displays a blank task module. It does work if I replace the Action.Submit with a Action.ToggleVisibility

**Comment by Prasad-MSFT** [comment]
@matthiasdilger - Could you please share the sample/repo you are referring to along with repro steps so that we can try it out once from our end?
And please do confirm if the issue is only for iOS? Is it working fine in Teams desktop and web client?

**Comment by matthiasdilger** [comment]
Yes, this issue is specific for iOS only.
I will add some screenshots later.

**Comment by matthiasdilger** [comment]
@Prasad-MSFT 

Steps to reproduce:
User is on Teams iOS app and enters any chat
Presses long on a message to trigger context menu and then selects action based message extension "an action"
![image_6483441-6](https://user-images.githubusercontent.com/5625718/154465201-91524f41-629f-44c4-b6cd-2c01c5777e2a.JPG)
Bot receives composeExtension/fetchTask
Bot creates this card in nodejs:
```
let card = CardFactory.adaptiveCard({
 "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
        "type": "AdaptiveCard",
        "version": "1.0",
        "body": [          
              {
                "type": "TextBlock",
                "text": "Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum",
                "id": "text",
                "wrap": true                
              },              
              {
                "type": "Input.Text",
                "id": "inputText",
                "placeholder": "Some placeholder",
                "maxLength": 2000,
                "isMultiline": true,
                "isVisible": true
              },                            
              {
                "type": "ActionSet",
                "id": "actionSet",
                "actions": [
{
                    "type": "Action.Submit",                    
                    "title": "Submit",                    
                    "data": {
                      "type": 1
                    }
                  }  
                ]
              }
]});
```
Bot returns the task module with card:
```
res.json({
        task: {
          type: 'continue',
          value: {
            card: card,
            height: 400,
            title: 'task module from message action',
            url: null,
            width: 500
          }
        }
      });
```
Teams iOS shows empty task module:
![image_6483441-7](https://user-images.githubusercontent.com/5625718/154467361-0fa702b1-cb60-4659-839f-e44204de4e1a.JPG)

The same card works fine on Android, web and desktop. As mentioned before, removing the Action.Submit makes the card show on iOS.

**Comment by Prasad-MSFT** [comment]
@matthiasdilger - We are able to repro the issue and we have raised a bug for this. We will inform you once we get any update from Engineering Teams. Thanks!

**Comment by matthiasdilger** [comment]
While this particular issue (rendering the submit button) has been fixed, actually then pressing the button does not do anything. Will create a new issue.
