### ISSUE TITLE
[iOS] when triggering action based message extensions the linkToMessage is broken

### ISSUE THREAD

**Issue by matthiasdilger** [MicrosoftDocs/msteams-docs#5272]
User presses Teams message on iOS and swipes to action based message extensions and selects bot
Bot receives composeExtension/fetchTask with the following payload (using nodejs):
```
  name: 'composeExtension/fetchTask',
  type: 'invoke',
<....>
  value: {
    messagePayload: {
      id: 1645075697681,
      replyToId: 1645075697681,
      linkToMessage: 'https://teams.microsoft.com/message/19:3a46e4de-c1ff-47b8-b750-17522bc7e33e_43f42ce3-2829-4fdc-ae94-06b15786804a@unq.gbl.spaces/1645075697681?{\n' +
        '    context =     {\n' +
        '        contextType = chat;\n' +
        '    };\n' +
        '}',
```
Please fix the linkToMessage attribute and remove the newlines, the spaces, the { after ? and the } in the end. It works fine on Android.

**Comment by Prasad-MSFT** [comment]
@matthiasdilger - Could you please elaborate more on your ask?

**Comment by matthiasdilger** [comment]
@Prasad-MSFT 

The issue is an invalid URL in linkToMessage when the action based message extension is triggered in Teams iOS. It looks like formatted code, including newlines and whitespace, has been added to the message URL instead of url encoding it properly. A correct linkToMessage is very helpful so that the bot can later show to the user where the action originated from or for other programs to link into Teams to the specific message.

To reproduce:
User triggers action based message extension on Teams iOS
![154465201-91524f41-629f-44c4-b6cd-2c01c5777e2a](https://user-images.githubusercontent.com/5625718/154590692-8bfabb59-9ad5-482d-ace5-da562d91daf7.JPG)

Bot receives composeExtension/fetchTask with the following payload (using nodejs):
```
  name: 'composeExtension/fetchTask',
  type: 'invoke',
<....>
  value: {
    messagePayload: {
      id: 1645075697681,
      replyToId: 1645075697681,
      linkToMessage: 'https://teams.microsoft.com/message/19:xxx@unq.gbl.spaces/1645075697681?{\n' +
        '    context =     {\n' +
        '        contextType = chat;\n' +
        '    };\n' +
        '}',
```

Even after cleaning the newlines and whitespace from the URL it still is invalid:
```
https://teams.microsoft.com/message/19:xxx@unq.gbl.spaces/1645075697681?{context={contextType=chat;};}
```

Doing the same task in Teams web or desktop sends this linkToMessage to the bot:
```
https://teams.microsoft.com/l/message/19:xxx@thread.v2/1645141670752?context=%7B%22contextType%22:%22chat%22%7D
```
which is the correct way. ✅

**My ask:** Please make Teams iOS send a correct URL in linkToMessage when an action based message extension is triggered, just like Teams does on web and desktop.

**Comment by Prasad-MSFT** [comment]
@matthiasdilger - We are able to repro the issue and we have raised a bug for this. We will inform you once we get any update from Engineering Teams. Thanks!

**Comment by matthiasdilger** [comment]
This issue has been fixed, thanks
