### ISSUE TITLE
The bot is not a part of the conversation roster error in new chat(Chat->New)

### ISSUE THREAD

**Issue by alexnekrasov588** [MicrosoftDocs/msteams-docs#5273]
Hi,

I am using Microsoft Bot Framework to create the message extension. I would like to get the user email of the customer who enters the search query in the bottom search chatbox. The email is getting correctly if we open the extension from the Teams->Chat but if we create a new chat from Chat->New Chat the email id is not getting

**Comment by Prasad-MSFT** [comment]
The issue is being tracked here: https://techcommunity.microsoft.com/t5/teams-developer/the-bot-is-not-a-part-of-the-conversation-roster-error-in-new/m-p/2608302#M3597
