### ISSUE TITLE
Removing a bot from a team

### ISSUE THREAD

**Issue by AlexOugh** [MicrosoftDocs/msteams-docs#528]
I cannot find the trash icon. Can you show where I can find it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac99cf82-194d-eb31-2d29-7368ba895edc
* Version Independent ID: aab61691-1db4-8580-53be-d4665c96e5be
* Content: [Test and debug your bot - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/bots/bots-test#feedback)
* Content Source: [msteams-platform/concepts/bots/bots-test.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/bots/bots-test.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Gousia-MSFT** [comment]
@AlexOugh You can delete your bot from a team by opening apps in team and click on the trash icon beside. 
![MicrosoftTeams-image](https://user-images.githubusercontent.com/45553518/55136727-3123a380-5155-11e9-86d1-7941c76d546c.png)

Whereas in personal scope you can hide your bot by choosing Hide option from the Action Menu. 
![image](https://user-images.githubusercontent.com/45553518/55135378-86f64c80-5151-11e9-9bce-145ea2d9fe90.png)

**Comment by AlexOugh** [comment]
I'm using a company teams and I cannot find that list. Is it only available to the admin?

**Comment by billbliss** [comment]
Depending on the team's settings, it may only be visible to team owners.
