### ISSUE TITLE
[Question] Teams bot messaging endpoint caching

### ISSUE THREAD

**Issue by freedomofkeima** [MicrosoftDocs/msteams-docs#530]
Hi,

Is there any known information on how long do we need to wait until URL change on `Messaging endpoint` reflects? Since I'm utilizing `ngrok` for development, it seems that the new endpoint might work from 30 minutes to hours of waiting. In the meantime, the server still sends update to the old `Messaging endpoint`.

Thanks.

**Comment by Wajeed-msft** [comment]
Hi @freedomofkeima - Messaging endpoint change should reflect immidiately. Could you please share your bot id?

**Comment by freedomofkeima** [comment]
Hi,

My bot ID is `8b230f18-b004-4a76-9a60-505fe6dc5526`. This problem occurred several times too in the past few weeks (not the first occurrence).

Thanks.

**Comment by Wajeed-msft** [comment]
@freedomofkeima - This issue has been fixed. Could you please try again?

**Comment by freedomofkeima** [comment]
I confirmed it's working now, thanks!
