### ISSUE TITLE
People picker support on desktop and web

### ISSUE THREAD

**Issue by matthiasdilger** [MicrosoftDocs/msteams-docs#5302]
Can you please share the timeline on getting the people picker to work on desktop and web? According to the documentation only mobile is currently supported. I tried on desktop anyway and received error code 100 NOT_SUPPORTED_ON_PLATFORM.  
It would be great to have this so that users can be tagged inside tabs, etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2bafb046-4848-f113-8ea4-6ae1865c26fd
* Version Independent ID: bfae5321-cfaf-591e-d5bd-292d9f206462
* Content: [Integrate People Picker - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/people-picker-capability)
* Content Source: [msteams-platform/concepts/device-capabilities/people-picker-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/device-capabilities/people-picker-capability.md)
* Product: **msteams**
* GitHub Login: @Rajeshwari-v
* Microsoft Alias: **surbhigupta**

**Comment by sayali-MSFT** [comment]
@matthiasdilger - We are looking into this I will get back to you soon.

**Comment by matthiasdilger** [comment]
@sayali-MSFT I am currently looking at implementing this functionality for a tab on Teams desktop and web and using the People Picker via the Teams JS SDK would be the easiest solution. Could you please let me know if there is any timeline for implementing this on these platforms? Thank you.

**Comment by sayali-MSFT** [comment]
@matthiasdilger - We are checking it internally and let you know once we get any updates.

**Comment by Wajeed-msft** [comment]
@matthiasdilger - Tentative plan for this feature is sometimes in March 2022. To get notified please [configure RSS feed for Microsoft Teams Platform updates](https://docs.microsoft.com/en-us/microsoftteams/platform/whats-new#get-latest-updates).

Closing this issue from this tracking list. Please feel free to re-open.
