### ISSUE TITLE
Mouse over message on App Icon in  Pop out tab

### ISSUE THREAD

**Issue by Henke-visual** [MicrosoftDocs/msteams-docs#5311]
In Teams Desktop client. 
When having an app in a Pop out tab, a large message appears instantly on every slight Mouse over/hover on the App Icon. 
In any other Teams view, like Expand tab, hover on App Icon or even clicking on it does nothing. 
It's a bit annoying. Why this behavior only on Pop out tabs?
Better to have a delay or on click, if at all. 

To reproduce
In Teams Desktop client.

- In your team, navigate to a tab for an app such as OneNote
- 1. Click the tab , 2. select Pop out tab

![image](https://user-images.githubusercontent.com/63777424/155134201-3c914c9c-8152-468c-a979-2d681c525572.png)

- 3. In the new window/popup, hover mouse on the App Icon

![image](https://user-images.githubusercontent.com/63777424/155134405-6841d1f4-4229-4cfc-ae68-17bd2f67ec20.png)

**Comment by Nivedipa-MSFT** [comment]
@Henke-visual - We are investigating your query. We will get back to you once we have any update.

**Comment by Meghana-MSFT** [comment]
@Henke-visual - Apologies for the delay in response. Engineering team has shared the below response, 
Currently there is no way for us to tune the hover behavior and add some kind of delay on the hover trigger. You can suggest this feature at [Microsoft Feedback portal](https://feedbackportal.microsoft.com/feedback/forum/ad198462-1c1c-ec11-b6e7-0022481f8472). If a temporary side solution would be good enough, please follow https://codesandbox.io/s/fluent-ui-example-forked-icgfsb?file=/example.js
