### ISSUE TITLE
Task Modal Availability for US Government Clouds

### ISSUE THREAD

**Issue by SeCossio** [MicrosoftDocs/msteams-docs#5319]
Are task modals available in O365 GCCH, if so, will the URL syntax for deep links align with this pattern?

https://gov.teams.microsoft.us/l/task/APP_ID?url=<TaskInfo.url>&height=<TaskInfo.height>&width=<TaskInfo.width>&title=<TaskInfo.title>&completionBotId=BOT_APP_ID

Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55c5e4a1-6116-ec92-36e9-b94097bd83c7
* Version Independent ID: fd843eef-73e2-7a7e-9ac4-5c20fcf1fa2f
* Content: [Invoke and dismiss task modules - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/task-modules/invoking-task-modules)
* Content Source: [msteams-platform/task-modules-and-cards/task-modules/invoking-task-modules.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/task-modules-and-cards/task-modules/invoking-task-modules.md)
* Product: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **lajanuar**

**Comment by v-chetsh** [comment]
We will check on it and get back to you.

**Comment by Nivedipa-MSFT** [comment]
We are checking with the engineering team. We will let you know once we have any update.
