### ISSUE TITLE
Unable to click link in chat message as it is overlayed by buttons

### ISSUE THREAD

**Issue by chris31389** [MicrosoftDocs/msteams-docs#532]
Hi,

I found this bug when a colleague sent me a link.  I can't click the link!

![image](https://i.imgur.com/5YoeY0H.gif)

After some investigation, it looks like the thumbs up, bookmark and "..." buttons only overlay messages if it is not the first message in a group from the same person.

If it is the first message, the buttons overlay the time next to the name of the user who sent the messages.

Further to this, you cannot highlight the whole line of text (with the intention of copying it).  It will stop highlighting at the buttons when they appear.

Asked here too: https://techcommunity.microsoft.com/t5/Microsoft-Teams/Unable-to-click-link-in-chat-message-as-it-is-overlayed-by/m-p/389929#M28815

Does anyone have a workaround or fix for this?

**Comment by Wajeed-msft** [comment]
@chris31389 - Thanks for reproting this. We are fixing it.

**Comment by chris31389** [comment]
@Wajeed-msft Any ideas when it will be fixed and released?

**Comment by billbliss** [comment]
Very soon. I'm afraid we can't be specific though.

**Comment by chris31389** [comment]
@billbliss @Wajeed-msft Its been almost a month! It is still really really really really really really annoying.

When is this expected to be available?????

**Comment by Wajeed-msft** [comment]
This is fixed. Please check and let us know if you are still facing this issue.
