### ISSUE TITLE
iOS Planner tab broken within Teams

### ISSUE THREAD

**Issue by DavidL360** [MicrosoftDocs/msteams-docs#533]
Hello,
We have just noticed that on iPads (iOS 12.1.1) within teams, the Planner tab is broken. If you open a Planner tab within a team, everything will be displayed correctly first. However, as soon as you start to swipe through the view, the display hangs and many elements can no longer be used. We have been able to replicate this with different plans and on different iPads. On iPhone it works without problems.

**Comment by Wajeed-msft** [comment]
@DavidL360 - Could you please share screenshots of the broken UI?

**Comment by Wajeed-msft** [comment]
Please re-open with screenshots.
