### ISSUE TITLE
Outgoing Webhook not visible

### ISSUE THREAD

**Issue by tmaheshwar** [MicrosoftDocs/msteams-docs#534]
In Teams , there is a option for Incoming Web hook but there is no option to configure Outgoing Webhook

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06c224ae-1484-408c-d17a-e7e1ba07e78a
* Version Independent ID: fac8ff1e-a127-c12a-5304-9de39b1a15c6
* Content: [Outgoing webhooks - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/outgoingwebhook#samples-for-outgoing-webhook)
* Content Source: [msteams-platform/concepts/outgoingwebhook.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/outgoingwebhook.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by billbliss** [comment]
You mean the option to create outgoing webhooks as described in the documentation isn't there?

**Comment by tmaheshwar** [comment]
Sorry

I was able to find the option; It is there
Thanks!


Best Regards
Maheshwar Tayal

**Comment by dhananjayece244** [comment]
I am also getting the same issue ? Not getting outgoing Webhook option.

**Comment by MarshHawk** [comment]
Same, where is it?

**Comment by Linreg-gmx-net** [comment]
I can not see this Option too. 
I created a new Team, but no Link/Option to create a outgoing webhook is visible.
Incomming Webhook is no Problem
