### ISSUE TITLE
$schema property in additional language files pointing to wrong URL

### ISSUE THREAD

**Issue by jouhami** [MicrosoftDocs/msteams-docs#5342]
Expected value :  
`"$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.12/MicrosoftTeams.Localization.schema.json",`

Actual value in generated app package :  
`"$schema":"https://developer.microsoft.com/en-us/json-schemas/teams/v1.11/MicrosoftTeams.schema.json"`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7da63b6f-15d7-a6dd-82fc-d183afaeb816
* Version Independent ID: 82d1ca83-28dd-220e-ab0c-a4833f8f8143
* Content: [Manage your apps with the Developer Portal - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/teams-developer-portal)
* Content Source: [msteams-platform/concepts/build-and-test/teams-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/build-and-test/teams-developer-portal.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **surbhigupta**

**Comment by Meghana-MSFT** [comment]
We are looking into this. We will update you.

**Comment by Meghana-MSFT** [comment]
We tried this at our end and we see the below schema property :
"$schema":"https://developer.microsoft.com/en-us/json-schemas/teams/v1.12/MicrosoftTeams.schema.json"

As mentioned in [Localize JSON schema reference](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/localization-schema), value generated in app package is correct only. Its mentioned that Your file must conform to the schema hosted at https://developer.microsoft.com/en-us/json-schemas/teams/v1.8/MicrosoftTeams.Localization.schema.json, but that is not the actual schema value.

**Comment by Meghana-MSFT** [comment]
You can still upload the manifest to Teams and it works. To verify it you can validate the manifest in the Developer portal/App studio and you wont see this error.
