### ISSUE TITLE
Sample manifest is coming up as invalid-fetchTask and type attributes on Commands not defined

### ISSUE THREAD

**Issue by chrisbardon** [MicrosoftDocs/msteams-docs#535]
Has the schema changed?  It appears that fetchTask and type attributes on commands aren't validated by the schema, and Teams won't load a manifest that has them. Is there a new format for defining commands that launch task modules?

**Comment by billbliss** [comment]
Task modules are completely independent of the manifest. Can you give more details on what you're trying to do?

**Comment by chrisbardon** [comment]
I was trying to define a command in a compose extension that popped a modal dialog.  The docs [here](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/messaging-extensions/create-extensions) have a sample manifest that has a command formatted like this:
        {
          "id": "reassignTodo",
          "description": "Reassign a todo item",
          "title": "Create To Do",
          "type": "Action",
          "fetchTask": true
        }
Which isn't accepted by the schema.  The expectation is that selecting this command sends a composeExtension/fetchTask back to the bot, which can respond with an adaptive card that can be displayed in a modal window if I'm reading the docs correctly.

**Comment by billbliss** [comment]
OK you are using message actions - what version of the schema are you linking to (at the top of the manifest.json file)?

**Comment by chrisbardon** [comment]
1.3, same as in the docs:
{
  "$schema": " https://developer.microsoft.com/en-us/json-schemas/teams/v1.3/MicrosoftTeams.schema.json",
  "manifestVersion": "1.3",
  "version": "1.0",

**Comment by paul-cheung** [comment]
the same issue here, so what version of the schema should i use?

**Comment by paul-cheung** [comment]
@chrisbardon please refer to [issue#455](https://github.com/MicrosoftDocs/msteams-docs/issues/455)

**Comment by kartikluke** [comment]
@chrisbardon 

It's working for me if I use:

```
{
    "$schema": "https://raw.githubusercontent.com/OfficeDev/microsoft-teams-app-schema/preview/DevPreview/MicrosoftTeams.schema.json",
    "manifestVersion": "devPreview",
    ...
}
```

**Comment by clearab** [comment]
Docs have been updated with correct version in the appManifest
