### ISSUE TITLE
The new page visual design robs the user from the ability to get a glimpse of what the app template looks like/does

### ISSUE THREAD

**Issue by kahopkin** [MicrosoftDocs/msteams-docs#5354]
I Have not been on the App Templates page in a while and when I came back today I noticed that the format of the page has been changed and only the top 5 apps maintained the previous listing format which worked fabuously by the way.  I also noticed that the link list to each apps are no longer on the right side, so can't just quickly get to a specific app template's section. 
The rest of the app templates are now condensed into a 'table' view, all images are stripped out (only the top 5 shows any) and because of the lack of visuals for the rest of the team app templates: doesn't really encourage the reader to want to click through and be redirected to GitHub, than have to go back, try to find where the clicked link was, etc.
Previously, you could glance through the entire page and got an idea of what the app is, what its user interface is from the screen clips, and then you could click the GitHub link which would open a new tab to GitHub.  We also had that great right side list of page links to one-click jump to the app template.

I am not sure why the structure of the old page was changed, but this new one does not really work.  It doesn't promote/encourage the user to explore the various app templates, because it just takes too long to try to open and navigate 50-60 links to GitHub in the blind.

I think it would do all the readers/users/partners a great service if we could bring the old look back and display the same way that only the top 5 is being displayed now.

Please re-consider and please re-instate the old format and the right-navigation.  This current look is not user-friendly, not easy to use, consumes too much time to find inspiring apps, and is discouraging.  Not to mention it is a productivity killer in itself, because it is visually impairing.
When all the images and descriptions were there (as they are for the top 5), the page enticed curiosity, was attractive and it was easy to decide on which app templates I might want to recommend to a partner, because you could see the screen shots of the interface for the app, or what the bot interface looks like, or how the tab is displayed.  
Please do not discourage the developers by robbing them of the visuals.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 100070d1-40f9-b5eb-be0a-6199de26e0e6
* Version Independent ID: 5d1269e3-2775-ebf6-cf9a-8d1ee7038397
* Content: [Microsoft Teams app templates - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/samples/app-templates#attendance-app)
* Content Source: [msteams-platform/samples/app-templates.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/samples/app-templates.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by sayali-MSFT** [comment]
@kahopkin -We are looking into this I will get back to you soon.

**Comment by sayali-MSFT** [comment]
@surbhigupta12 -Could you please help us for update the document?

**Comment by surbhigupta12** [comment]
@kahopkin,

Microsoft is not actively managing the source code. The complete source code is open source, and you can explore, fork, and modify the source code to meet your specific requirements.

Since we are not managing these templates, we'd not be updating the table in the requested format.
