### ISSUE TITLE
Update on published Microsoft Teams App does not seem to be propagated correctly.

### ISSUE THREAD

**Issue by jgdoyon-nexapp** [MicrosoftDocs/msteams-docs#5357]
**Context**:
We published an update for our published Microsoft Teams App (in our organization) with **only** a version bump from 1.0.1 to 1.0.2 in our manifest. It's now a day later and we still can't see the update in the Microsoft Teams app Store. Furthermore, it seems like the app avatar link is broken in the store. 
<img width="904" alt="image" src="https://user-images.githubusercontent.com/90272080/156196434-0be7c83a-b33d-4951-91cc-96c15903953b.png">

**What confuses us**
When we look in the Microsoft Teams Admin center, we can see that the application is correctly updated and that the app avatar is correctly displayed.
<img width="943" alt="image" src="https://user-images.githubusercontent.com/90272080/156196354-bfbda0be-aacd-4db9-a06b-b935375e919e.png">

Additionally the graph api still displays versions 1.0.1 instead of the correct version 1.0.2. `https://graph.microsoft.com/v1.0//appCatalogs/teamsApps?$filter=distributionMethod eq 'organization'&$expand=appDefinitions`
```json
{
    ...
    "id": "....",
    "displayName": "Axify Development",
    "version": "1.0.1",
    "publishingState": "published"
}
```

**NOTE**:
We also tried to upload the manifest with the app icons used for the update in the app studio and it correctly displays the version and the app avatar. So we have strong reasons to believe the manifest is not the issue.
<img width="1483" alt="image" src="https://user-images.githubusercontent.com/90272080/156198442-f70532b1-0837-4f00-91f5-6f748d0e7ea0.png">

**Our question**
How could we expose ourselves to the publish/update lifecycle to know when/if our app was correctly published ? Should that not be possible, how long should we expect to have to wait to assess that the publication/update was successful on the Microsoft Teams app store ?

**Comment by jgdoyon-nexapp** [comment]
If by third party app, you mean it has not been officially certified, then yes it is a third party app.

**Comment by jgdoyon-nexapp** [comment]
Update, after 2 days it seems that the avatar and the version now correctly appears in the store. Is there any reason why it took two days to update completely ?

**Comment by Nivedipa-MSFT** [comment]
@jgdoyon-nexapp - Are you publishing app via Teams partner center or Teams admin center?

**Comment by jgdoyon-nexapp** [comment]
Teams partner center

**Comment by Nivedipa-MSFT** [comment]
@jgdoyon-nexapp - We are mainly responsible for Microsoft Teams app development related issues. As you have submitted app via Teams partner center. Visit the [publishers support page](https://aka.ms/marketplacepublishersupport) to search for your issue. If the guidance isn't helpful, create a [Partner Center support ticket](https://docs.microsoft.com/en-us/azure/marketplace/partner-center-portal/support#how-to-open-a-support-ticket).
