### ISSUE TITLE
So confusing

### ISSUE THREAD

**Issue by joaomoreno** [MicrosoftDocs/msteams-docs#5358]
This page is so confusing. It seems like it should be a concise and clear list of what to do to get an app on a meeting. I've been trying to do just that for 1 hour and I can't seem to get anywhere. Please have a human review the documentation and clean it up.

For example, both these sentences are in separate bullet points and mean the same:

> The Meeting Details API must have a bot registration and bot ID. It requires Bot SDK to get TurnContext.

> Have a bot registration and bot ID in the MeetingDetails API. It requires Bot SDK to get TurnContext.

Or, it's not clear whether a bot is necessary at all.

I wish I could tell you more, but I can't even succeed at getting an app on a meeting, so I don't even have the context to give you constructive feedback.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b60eeacc-a71e-9644-b869-3e0a4f1506d8
* Version Independent ID: 313bf83f-5325-f9f4-5780-9bc81e315c1e
* Content: [Prerequisites for apps in Teams meetings - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings)
* Content Source: [msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by sayali-MSFT** [comment]
@surbhigupta12 -Could you please help us to update the document? Please Remove the second highlighted sentence.
Document:- https://docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings
![d](https://user-images.githubusercontent.com/93527375/156324596-eab6a389-6a8f-40ba-9793-273672193190.png)

**Comment by v-habibaumme** [comment]
Document is updated and closing the issue
