### ISSUE TITLE
No meeting start/end events when using app manifest version 1.12

### ISSUE THREAD

**Issue by xelossan** [MicrosoftDocs/msteams-docs#5360]
There seems to be an issue with MeetingStart and MeetingEnd events. When I'm using app manifest version 1.11, so the required permissions part looks like this:

```json
"webApplicationInfo": {
    "id": "<app id>",
    "resource": "https://RscPermission",
    "applicationPermissions": [
      "OnlineMeeting.ReadBasic.Chat"
    ]
}
```

everything works as expected and my Bot is getting the events. But when I switch to 1.12 manifest version and change the config to:

```json
"webApplicationInfo": {
    "id": "<app id>",
    "resource": "https://RscPermission",
},
"authorization": {
    "permissions": {
        "resourceSpecific": [
            {
                "name": "OnlineMeeting.ReadBasic.Chat",
                "type": "Application"
            }
        ]    
    }
}
```

the events aren't firing anymore. Is there some additional configuration that needs to be done for 1.12? The problem is that even if we manually create v1.11 manifest so the events work correctly, as soon as we make any change using dev.teams.microsoft.com app it switches to 1.12 and after publishing events stop working again.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 805dc242-7b5a-cc81-ee0e-6acf0078a653
* Version Independent ID: 11c0e023-2514-9639-6052-2cbbbef50663
* Content: [Meeting apps API references - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/api-references?tabs=dotnet)
* Content Source: [msteams-platform/apps-in-teams-meetings/API-references.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/apps-in-teams-meetings/API-references.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Meghana-MSFT** [comment]
Yes I have updated the version 1.12 and tested.

**Comment by SubbaReddi** [comment]
@Meghana-MSFT : It seems issue is reproducible with 1.12

**Comment by Meghana-MSFT** [comment]
We are checking this again, We will update you.

**Comment by Meghana-MSFT** [comment]
@SubbaReddi, @xelossan - We checked this issue and it seems to be working fine with 1.12. Could you please check and confirm?

**Comment by AkJo** [comment]
Was this issue resolved?

**Comment by SubbaReddi** [comment]
Observed working fine with 1.12 and 1.16 as well.
