### ISSUE TITLE
type and inputType not supported in schema v1.3 for compose extension command?

### ISSUE THREAD

**Issue by paul-cheung** [MicrosoftDocs/msteams-docs#537]
[composeExtensions.commands](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema#composeextensionscommands)
so when does the schema 1.3 include `type` and `fetchTask` for composed extension command?
![validation failed](https://user-images.githubusercontent.com/4626647/55265413-27b04d80-52b3-11e9-83da-df49e4eddbfd.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f94a488-d636-92b3-21eb-c88744c8f272
* Version Independent ID: 7b3413f4-9ade-accf-5cb2-83fead11a32a
* Content: [Manifest schema reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema)
* Content Source: [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/resources/schema/manifest-schema.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Wajeed-msft** [comment]
It is not supported in manifest version 1.3. Please use developer preview  manifest by Changing the value of $schema in your manifest.json file to https://raw.githubusercontent.com/OfficeDev/microsoft-teams-app-schema/preview/DevPreview/MicrosoftTeams.schema.json and it will work.

**Comment by paul-cheung** [comment]
@Wajeed-msft i have tried it, it does not work too.

**Comment by kartikluke** [comment]
@paul-cheung @Wajeed-msft 

It's working for me if I use:

```
{
    "$schema": "https://raw.githubusercontent.com/OfficeDev/microsoft-teams-app-schema/preview/DevPreview/MicrosoftTeams.schema.json",
    "manifestVersion": "devPreview",
    ...
}
```

**Comment by Wajeed-msft** [comment]
@paul-cheung - Are you trying to submit your app to the [store approval](https://docs.microsoft.com/en-us/microsoftteams/platform/publishing/apps-publish)?

**Comment by paul-cheung** [comment]
@Wajeed-msft not yet, i am just trying the preview schema.
