### ISSUE TITLE
Confusion with new Teams Bot registration

### ISSUE THREAD

**Issue by arambazamba** [MicrosoftDocs/msteams-docs#5370]
Until Oct 2021 I was able to register Teams bots in Azure Portal using the AzureBot ressource type or even scripting with Azure CLI by first creating the app reg and the the bot (az bot create)

When creating these bot registations they are not working anymore - instead I have to use https://dev.teams.microsoft.com/bots and https://dev.botframework.com/bots. Now two questins arise

a) Can I see these objects somewhere in Azure and can I create these object directly in Azure instead of the registrations portals
b) Is there any way of scripting these? Using Azure CLI or CLI for M365?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac64d14f-aec8-9dd6-e987-d2325de46fd6
* Version Independent ID: ba050a58-d98a-68f7-3190-8001d2a9d12c
* Content: [Register calls and meetings bot for Microsoft Teams - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/calls-and-meetings/registering-calling-bot)
* Content Source: [msteams-platform/bots/calls-and-meetings/registering-calling-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/bots/calls-and-meetings/registering-calling-bot.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by v-chetsh** [comment]
We will check on it and get back to you.

**Comment by arambazamba** [comment]
No prob ... Simple Test ... Use this guides -> will not work ... https://docs.microsoft.com/en-us/learn/modules/msteams-conversation-bots/

This will work:

[](https://github.com/arambazamba/ms-600/tree/master/Demos/04-Teams/Demo-06#create-app-registration)[](https://github.com/arambazamba/ms-600/tree/master/Demos/04-Teams/Demo-06#complete-bot-registration)Updated guide for Bot Registration in subsequent Modules and Labs
Create App Registration
Create an App Registration to provide a service principal that can be used with the bot by executing:

rnd=$RANDOM
app=conversationalbot$rnd

id=$(az ad app create --display-name $app --query appId -o tsv)
secret=$(az ad app credential reset --id $id --append --query password -o tsv)

echo "Use id in your bot registration: " $id
echo "Use secret in your bot registration: " $secret
Complete Bot Registration
Navigate to [Microsoft 365 Teams Developer Portal / Tools / Bot Management - https://dev.teams.microsoft.com/bots](https://dev.teams.microsoft.com/bots)[](https://github.com/arambazamba/ms-600/blob/master/Demos/04-Teams/Demo-06/_images/teamsdev-bot.png)[](https://github.com/arambazamba/ms-600/blob/master/Demos/04-Teams/Demo-06/_images/new-bot.png) and create a new bot:

teamsdev-bot.png

Click on your new bot and notice the metadata on the Configure blade

new-bot.png

Navigate to [Bot Framework Registration](https://dev.botframework.com/bots)[](https://github.com/arambazamba/ms-600/blob/master/Demos/04-Teams/Demo-06/_images/teams-channel.png)[](https://github.com/arambazamba/ms-600/blob/master/Demos/04-Teams/Demo-06/_images/bot-metadata.png)[](https://github.com/arambazamba/ms-600/blob/master/Demos/04-Teams/Demo-06/_images/metadata-appid.png)[](https://github.com/arambazamba/ms-600/tree/master/Demos/04-Teams/Demo-06#scaffold-and-test-bot-project-using-yeoman-teams-generator)[](https://github.com/arambazamba/ms-600/blob/master/Demos/04-Teams/Demo-06/_images/npm-global.png)[](https://github.com/arambazamba/ms-600/blob/master/Demos/04-Teams/Demo-06/_images/yo.png)[](https://github.com/arambazamba/ms-600/blob/master/Demos/04-Teams/Demo-06/_images/env.png)[](https://github.com/arambazamba/ms-600/blob/master/Demos/04-Teams/Demo-06/_images/ngrok-url.png)[](https://github.com/arambazamba/ms-600/blob/master/Demos/04-Teams/Demo-06/_images/endpoint.png)[](https://github.com/arambazamba/ms-600/tree/master/Demos/04-Teams/Demo-06#labs) and select your bot

Check if Teams Channel is enabled:

teams-channel.png.png

Complete the bot metadata:

bot-metadata.png

metadata-appid.png

Scaffold and test bot project using yeoman teams generator
Note: Make sure you have the latest production release of the yo team generator installed and use mainfest version 11 for scaffolding

npm-global.png

md FOLDER
cd FOLDER
yo teams
yo.png

Update .env with the secret from the app reg that you have created:

env.png

Execute gulp ngrok-serve and note the ngrok url:

ngrok-url.png

Update the endpoint:

endpoint.png

Labs

**Comment by arambazamba** [comment]
no problem ... try this ... does not work anymore ... https://docs.microsoft.com/en-us/learn/modules/msteams-conversation-bots/

with these links it works https://dev.teams.microsoft.com/bots and https://dev.botframework.com/bots ... if you need additional info feel free to contact me

**Comment by Nivedipa-MSFT** [comment]
@arambazamba - As an alternative you can do app registration in azure portal and use that APP ID and App Secret while creating bot in azure.
You can refer following document for app registration.
https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-register-app
