### ISSUE TITLE
Add note that as user specific view is dependent on universal actions, this only works for cards posted by a bot. 

### ISSUE THREAD

**Issue by TheBluLion** [MicrosoftDocs/msteams-docs#5377]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 148d2ee0-4ac8-03c2-5493-dff7a762fba4
* Version Independent ID: 857f4370-d04b-357f-c7dc-b3449d353ba6
* Content: [User Specific Views - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/user-specific-views?tabs=mobile%2CC#feedback)
* Content Source: [msteams-platform/task-modules-and-cards/cards/Universal-actions-for-adaptive-cards/User-Specific-Views.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/task-modules-and-cards/cards/Universal-actions-for-adaptive-cards/User-Specific-Views.md)
* Product: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **lajanuar**

**Comment by v-chetsh** [comment]
@SurbhiAgarwal12 - Could you please help us here to update the contents.
