### ISSUE TITLE
This issue is already fixed?

### ISSUE THREAD

**Issue by 1411381** [MicrosoftDocs/msteams-docs#5382]
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45541337-ecd7-5cf6-cbe4-3f0d2f39aa79
* Version Independent ID: 6b4203f0-2844-06c9-eaa3-9cc03e6f76c0
* Content: [Create deep links - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links)
* Content Source: [msteams-platform/concepts/build-and-test/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/build-and-test/deep-links.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by 1411381** [comment]
https://github.com/MicrosoftDocs/msteams-docs/issues/3500

After we previously posted this issue.
Mobile device operation is not supported. The information was posted on the homepage.

When I looked this morning, I found that the information had disappeared from the website.

Am I correct in understanding that deep linking to voice and audio/video calls on mobile devices is also supported?

**Comment by sayali-MSFT** [comment]
@1411381 -We are looking into this I will get back to you soon.

**Comment by sayali-MSFT** [comment]
@1411381 -Deep linking to voice and audio/video calls on mobile devices is not supported

**Comment by sayali-MSFT** [comment]
@1411381 - could you please upgrade your Teams and try it again. 
For the calling deep links containing email in users parameter, It is only enabled for Teams with the build version number greater than 2021180000.
