### ISSUE TITLE
Get conversation paged members returns 403

### ISSUE THREAD

**Issue by freedomofkeima** [MicrosoftDocs/msteams-docs#539]
Hi,

I'm not sure if Microsoft Teams bot supports this method or not, but since the other endpoint works, I write the details out here.

Accessing [`GET /v3/conversations/{conversationId}/members`](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-api-reference?view=azure-bot-service-4.0#get-conversation-members) works for me, but the paged members endpoint [`GET /v3/conversations/{conversationId}/pagedmembers`](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-api-reference?view=azure-bot-service-4.0#get-conversation-paged-members) returns `403` error.

Logs:

```
INFO[0001] Sending request to https://smba.trafficmanager.net/apac/v3/conversations/19:c617c3bdea7e4845a4f437db2ca67ae7@thread.skype/members 
INFO[0001] https://smba.trafficmanager.net/apac/v3/conversations/19:c617c3bdea7e4845a4f437db2ca67ae7@thread.skype/members returns 200 
...
INFO[0001] Sending request to https://smba.trafficmanager.net/apac/v3/conversations/19:c617c3bdea7e4845a4f437db2ca67ae7@thread.skype/pagedmembers 
INFO[0002] https://smba.trafficmanager.net/apac/v3/conversations/19:c617c3bdea7e4845a4f437db2ca67ae7@thread.skype/pagedmembers returns 403 
WARN[0002] https://smba.trafficmanager.net/apac/v3/conversations/19:c617c3bdea7e4845a4f437db2ca67ae7@thread.skype/pagedmembers returns error message: {"error":{"code":"ServiceError","message":"Unknown"}} 
```

Is this intended?

**Comment by Wajeed-msft** [comment]
@freedomofkeima - These APIs are not yet available for third party applications.

**Comment by freedomofkeima** [comment]
Hi @Wajeed-msft ,

Thanks for the reply. Is there any plan when these APIs will be available to the public? 

We are currently starting to work on developing Teams Bot as a notification platform for our O365-integrated customers. Since we only know their O365 email address & tenant ID, we need a way to map these email addresses to their Teams' user. With `GET /v3/conversations/{conversationId}/members`, we can retrieve list of Teams' users with their `o365_email`, `o365_tenant_id`, and `teams_user_id`. The problem is, some of our customers are big companies and their admin don't want to bother all employees one by one, therefore we need a pagination feature in retrieving Teams' user list (`/pagedmembers` endpoint).

For other communication platforms (S**ck, etc), our integration has worked well so far. It will be greatly appreciated if there's a solution or recommended way to achieve this goal.

Thank you.

**Comment by Wajeed-msft** [comment]
@freedomofkeima - Are you getting any issue while calling `GET /v3/conversations/{conversationId}/members` API for large teams?

**Comment by freedomofkeima** [comment]
Hi @Wajeed-msft,

Thank you for the response. Currently we haven't tried integrating our bot with real customers yet, it's simply a performance concern so far.

I'll open another ticket in case we're experiencing performance degradation in the future. Meanwhile, it will be greatly appreciated if `pagedmembers` endpoint is available for us.

Thanks for your time.

**Comment by RukaiYu** [comment]
> @freedomofkeima - Are you getting any issue while calling `GET /v3/conversations/{conversationId}/members` API for large teams?

@Wajeed-msft We also have this concern. Is there an upon limit of the large team/group that may have performance issue?
Thanks!

**Comment by clearab** [comment]
Hi - The pages getMembers endpoint is on the backlog, and will be available soon.
