### ISSUE TITLE
Group chat participants info

### ISSUE THREAD

**Issue by ahmadgh7** [MicrosoftDocs/msteams-docs#540]
Is there a way to get info like the above properties for the other participants in the chat?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 525acdf7-3f72-b657-63ea-ddb95c4fb247
* Version Independent ID: c5d9575a-ace3-8441-4516-ad2c7adb3d99
* Content: [Get context for your tab - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/tabs/tabs-context#feedback)
* Content Source: [msteams-platform/concepts/tabs/tabs-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/tabs/tabs-context.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Abhijit-MSFT** [comment]
Can you please elaborate more on this.

**Comment by ahmadgh7** [comment]
All the properties described here are info about the current user.
I would like to my app to receive that same info but for the other participants in the chat.
Is that possible?

**Comment by Abhijit-MSFT** [comment]
This feature is not available. You can not fetch all this information for other participants in the chat.
