### ISSUE TITLE
'Add an app' functionality is not coming in the web version of the meeting

### ISSUE THREAD

**Issue by pooran** [MicrosoftDocs/msteams-docs#5412]
'Add an app' functionality is not coming in the web version of the meeting. Because of this, we are not able to test the functionality of our teams app. Is it by design?

![photo_2022-03-10_10-54-02](https://user-images.githubusercontent.com/116028/157595242-20d98c4e-0743-4c97-8708-877ceca189ce.jpg)

**Comment by sayali-MSFT** [comment]
@pooran - We are looking into this I will get back to you soon.
