### ISSUE TITLE
Adaptive Cards using Incoming Webhook with Data

### ISSUE THREAD

**Issue by pgodwin** [MicrosoftDocs/msteams-docs#5416]
The Adaptive Cards has support for templating (https://docs.microsoft.com/en-us/adaptive-cards/templating/), but it's unclear whether this supported with the Incoming web-hook. 

Is the documentation able to clarify this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28316a67-22fa-8a05-1ae0-fbe1c5720ef9
* Version Independent ID: 8a250e46-2a30-af86-839d-9f83a8b48041
* Content: [Create and send messages - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-using?tabs=cURL#send-adaptive-cards-using-an-incoming-webhook)
* Content Source: [msteams-platform/webhooks-and-connectors/how-to/connectors-using.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/webhooks-and-connectors/how-to/connectors-using.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by sayali-MSFT** [comment]
@pgodwin - We are looking into this I will get back to you soon.

**Comment by sayali-MSFT** [comment]
@pgodwin - Templating we use to edit the card and all in designer only.

**Comment by sayali-MSFT** [comment]
@pgodwin - Could you please confirm if your issue has resolved with above suggestion or still looking for any help?

**Comment by pgodwin** [comment]
Thanks Sayali - so looks like the webhook doesn't support inlined data on templates then? Ie as defined here:
https://docs.microsoft.com/en-us/adaptive-cards/templating/language#option-a-inline-data

**Comment by sayali-MSFT** [comment]
@pgodwin -Yes. Webhook doesn't support inlined data on templates.

**Comment by sayali-MSFT** [comment]
@pgodwin -We are closing this issue for now, Please feel free to reopen it, if required.
