### ISSUE TITLE
TeamsComponentContext is out of date

### ISSUE THREAD

**Issue by aosolis** [MicrosoftDocs/msteams-docs#542]
Based on the GitHub repo, the new way uses TeamsThemeContext.Provider and TeamsThemeContext.Consumer. This documentation page needs to be updated to use the new constructs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed3343e3-d546-7c4e-6e5c-64af6dd79a77
* Version Independent ID: 09a6a83f-f28b-7054-26c7-31dec6cb6367
* Content: [Using the control library - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/get-started/app-studio-component-library#feedback)
* Content Source: [msteams-platform/get-started/app-studio-component-library.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/get-started/app-studio-component-library.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by aasis21** [comment]
@aosolis   Can you please provide an example, on how to use the first example in the documentation using newer components.

**Comment by Mahesh2516** [comment]
The topic is deprecated. Hence, closing this issue as suggested by Allen Snow on 24/02/2021. A new requirement will be raised to address this issue.
