### ISSUE TITLE
Instructions for debugging in MacOS won't work.

### ISSUE THREAD

**Issue by mig82** [MicrosoftDocs/msteams-docs#5431]
The instructions for debugging the app in MacOS do not work.
I know Developer Preview is possible with this account because I can upload custom apps _and_ debug the Teams app on my Android Device. However, for MacOS, the "Developer preview" option does not come up under "Settings>About". In fact, there is no "Settings>About" menu. The "Settings" and "About" menus are separate in the MacOS app. And the option to enable preview doesn't appear to be available anywhere else. So then, clicking the Microsoft Teams icon on the dock does not open Dev Tools. I've tried it with different accounts to no avail.

Versions:
* MacOS Big Sur v11.6.1
* Teams version 1.5.00.4683.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3df1efbb-c6b2-a495-303d-7abf19c57f72
* Version Independent ID: a5b5782f-7031-a989-5e42-dd3010e18893
* Content: [DevTools for Microsoft Teams tabs - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/developer-tools)
* Content Source: [msteams-platform/tabs/how-to/developer-tools.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/tabs/how-to/developer-tools.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Meghana-MSFT** [comment]
Please go through the [Enable developer preview](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/dev-preview/developer-preview-intro#enable-developer-preview) documentation. We were able to see the Developer preview option in the About. Attaching a screenshot for your reference.
![image](https://user-images.githubusercontent.com/81138249/157674123-079e0f2e-b9d2-4c9a-8115-a7836f25cbf2.png)

**Comment by v-chetsh** [comment]
@mig82 - Shall we close this issue?

**Comment by mig82** [comment]
Also, the doc should mention that in MacOS, you have to right-click the Teams icon on the dock to find the DevTools option.
<img width="203" alt="image" src="https://user-images.githubusercontent.com/10434613/159488619-1b491932-8100-4400-b1bb-bf8cf314e46f.png">

And then explain what the expected behaviour is. For example, that it will open Chrome DevTools for each iframe, etc. Otherwise one is left wondering what the effect of steps taken should have been, and whether it actually worked or not.

**Comment by Meghana-MSFT** [comment]
@mig82 - Thank you for your suggestions. We will look into it.

**Comment by Meghana-MSFT** [comment]
@surbhigupta12 - Could you please help by adding the below screenshot in this document just below this point "On MacOS, click on the Microsoft Teams icon in the Dock." - [Access DevTools on the desktop](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/developer-tools?msclkid=44fd0603af4811ec95bd059a00bd2cf6#access-devtools-on-the-desktop)

![image](https://user-images.githubusercontent.com/81138249/160588717-0f8d0c16-88ff-4d86-bc51-716a4d639cef.png)
