### ISSUE TITLE
Add details about Graph Activity Feed Notifications to the Bot conversations 'Notifications to your message' section

### ISSUE THREAD

**Issue by eoinobrien** [MicrosoftDocs/msteams-docs#5432]
Is it possible to include a brief overview and a link to the Graph docs on how to send an activity feed notification using their API.
I spent some time recently trying to understand how to send a notification that links to a tab, but realised it wasn't possible with botframework, but was possible with the API.

I would suggest briefly explaining some limitations of this API, what is possible in the Graph API and then linking to the [Activity feed notifications or bot framework messages](https://docs.microsoft.com/en-us/graph/teams-activity-feed-notifications-best-practices#activity-feed-notifications-or-bot-framework-messages) documentation.

Helping developers understand that other parts of Platform can complete what they are trying to do would be useful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afbc5b84-5be5-b5c4-30c0-58782a748a03
* Version Independent ID: ef6b8aee-52e7-f5d4-7dfa-8f34a1698330
* Content: [Messages in bot conversations - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-messages?tabs=dotnet)
* Content Source: [msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/bots/how-to/conversations/conversation-messages.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **anclear**

**Comment by Meghana-MSFT** [comment]
We are looking into it. We will get back to you.

**Comment by sayali-MSFT** [comment]
@AkJo - Could you please help us to update the document?
