### ISSUE TITLE
Apps works in GCC

### ISSUE THREAD

**Issue by Matt-Mueller-MSFT** [MicrosoftDocs/msteams-docs#5434]
Why does it say this App is not supported in GCC. I have used it in my own Tenant, as well as have seen customers use it. It is just blocked by default as it is listed under 3rd Party Apps. There is a whole slew of MSFT CSMs and CEs helping customers use this app in GCC to pin Pages and other items. I saw in previous tickets about this it was said to be not supported, please explain how it is not supported. If need be reach out to me on Teams for more details.

**Comment by v-chetsh** [comment]
We will check on it from our end and get back to you.

**Comment by Nivedipa-MSFT** [comment]
@Matt-Mueller-MSFT - Could you please share the document where its mentioned that 3rd party apps not supported in GCC.
