### ISSUE TITLE
script tag example issue in Chrome

### ISSUE THREAD

**Issue by dipakboyed** [MicrosoftDocs/msteams-docs#544]
&lt;script async defer src="https://teams.microsoft.com/share/launcher.js" /&gt; doesn't work correctly in Chrome v73.0.3683.86.
But 
&lt;script async defer src="https://teams.microsoft.com/share/launcher.js"&gt; &lt;/script&gt; does work.
I suggest updating the documentation. thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a59a558-f2f0-3390-9c81-bb41d47a5fbe
* Version Independent ID: a4335fae-0b14-c338-0f15-23ee043be278
* Content: [Share to Teams embedded button - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/share-to-teams)
* Content Source: [msteams-platform/share-to-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/share-to-teams.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by clearab** [comment]
Thanks, this will be fixed when this page is re-released.
