### ISSUE TITLE
Adaptive card & task module interaction from meeting apps

### ISSUE THREAD

**Issue by SubbaReddi** [MicrosoftDocs/msteams-docs#5440]
As per the [documentation ](https://docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/meeting-app-extensibility?tabs=desktop#user-types-in-a-meeting), it is mentioned that
For Anonymous user:
1. Bot is not available
2. Interactions in the meeting chat are allowed for adaptive card
3. Interactions in the meeting chat from Adaptive Card are allowed for task modules

For Guest user
1. Bot is not available

But we see ambiguity how user can interact in meeting chat for adaptive card & task module if bot is not available.

We verified with custom bot and observed that
1. For anonymous users meeting app is not accessible in teams(Desktop/ web/ Android) and user is not able to interact with adaptive card as well.
2. For guest users, user is able to find the app and interact with adaptive card from Desktop & web but not from Android.
3. For external users, user is able to find the app and interact with adaptive card from Desktop & web but not from Android.

Could you please update the documentation to clarify this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33fae5e3-2d98-381c-1b16-82c0acc6f716
* Version Independent ID: 6124f090-bdb7-c575-2614-60ec85a947b9
* Content: [Unified meetings apps - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/meeting-app-extensibility?tabs=desktop#user-types-in-a-meeting)
* Content Source: [msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by v-chetsh** [comment]
We will check on it and get back to you.

**Comment by Nivedipa-MSFT** [comment]
@SubbaReddi - Apologies for delay. Could you please share which sample you are using for this so that we can check at our end?

**Comment by Nivedipa-MSFT** [comment]
@SubbaReddi - We checked it from our end. For anonymous users meeting app is not accessible in teams(Desktop/ web/ Android) and user is not able to interact with adaptive card as well as mentioned .

For guest users, user is able to find the app and interact with adaptive card from Desktop & web but not from Android. Noticed that in this [doc](https://docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/meeting-app-extensibility?tabs=desktop#in-meeting-app-experience) its mentioned  "The app won't appear in meetings for the mobile clients".

@surbhigupta12 - Need to update the documentation [here](https://docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/meeting-app-extensibility?tabs=desktop#user-types-in-a-meeting)
![image](https://user-images.githubusercontent.com/92150070/158602817-accb03a3-a7ba-4edb-a57b-cdf572124d85.png)

**Comment by Nivedipa-MSFT** [comment]
@SubbaReddi - Could you please confirm is your issue resolved?
