### ISSUE TITLE
Tip: Make sure stuff works before you publish an article on it

### ISSUE THREAD

**Issue by tabinnorway** [MicrosoftDocs/msteams-docs#546]
Go through every single step in this article, and you'll not get anything that resembles a deployed application. Here's some output from my deployment

09:02:25 BKKTeamsHelloWorld: Command: bash deploy.sh
09:02:25 BKKTeamsHelloWorld: deploy.sh: line 2: $'\r': command not found
09:02:25 BKKTeamsHelloWorld: deploy.sh: line 7: $'\r': command not found
09:02:25 BKKTeamsHelloWorld: deploy.sh: line 10: $'\r': command not found
09:02:25 BKKTeamsHelloWorld: deploy.sh: line 11: syntax error near unexpected token `$'{\r''
09:02:25 BKKTeamsHelloWorld: deploy.sh: line 11: `exitWithMessageOnError () {
09:02:25 BKKTeamsHelloWorld: '
09:02:25 BKKTeamsHelloWorld: deploy.sh: line 2: $'\r': command not found\ndeploy.sh: line 7: $'\r': command not found\ndeploy.sh: line 10: $'\r': command not found\ndeploy.sh: line 11: syntax error near unexpected token `$'{\r''\ndeploy.sh: line 11: `exitWithMessageOnError () {\n'\n/opt/Kudu/Scripts/starter.sh bash deploy.sh

On the other hand, the dialog box says the deployment was successful. So, I browse to the site created, but nothing. So apparently not.

Final step - gotta add app_bot_id and app_bot_password somewhere. Now, since the creation of my app happened through the Azure plugin for VS Code, I have not seen any, so I head over to the Azure portal to find the app_bot_id it presumably has created when creating my app, but there is no such thing anywhere.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c08b13b0-8c05-c6f1-c3fa-a58b67ae0123
* Version Independent ID: 14116a6d-f66b-a81b-9808-cf6db771325f
* Content: [Host your Node based Teams app in Azure - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/get-started/get-started-nodejs-in-azure#feedback)
* Content Source: [msteams-platform/get-started/get-started-nodejs-in-azure.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/get-started/get-started-nodejs-in-azure.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by RayBrindley** [comment]
Agreed very frustrating trying to follow this.

For others getting the above error In the Bottom Right hand corner of VSCode there is  CRLF button. Click this and you'll have the option to change to LF.

After that it should deploy successfully.

https://askubuntu.com/questions/1036322/running-script-made-in-visual-studio-code-on-windows-on-wsl-ubuntu-returns-li
