### ISSUE TITLE
Add a "stop the distribution of the app" paragraph

### ISSUE THREAD

**Issue by Benjiiim** [MicrosoftDocs/msteams-docs#5471]
I'm wondering if that would make sense to add a "Stop the distribution of the app" paragraph to explain what should do the ISV to stop the distribution of the app and what are the consequences for existing users?

For information, Commercial Marketplace has such a paragraph on https://docs.microsoft.com/en-us/azure/marketplace/update-existing-offer#stop-distribution-of-an-offer-or-plan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d29cfd09-9067-d939-960a-b33931707c4d
* Version Independent ID: 6c0b95fa-b5b4-5ace-15e7-55d2b007b792
* Content: [Maintain and support your published app - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/post-publish/overview)
* Content Source: [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/deploy-and-publish/appsource/post-publish/overview.md)
* Product: **msteams**
* GitHub Login: @heath-hamilton
* Microsoft Alias: **surbhigupta**

**Comment by Prasad-MSFT** [comment]
@Benjiiim - We are looking into it. Will get back to you shortly

**Comment by Prasad-MSFT** [comment]
Partner can initiate de-listing the app by following the steps below:
Navigate to Partner Center ->Overview page and click on Stop Selling.
![image](https://user-images.githubusercontent.com/62237649/160591663-fc4d22ed-ab33-45fa-ad33-bf3123cca78a.png)
Please refer to this [documentation](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Fmarketplace%2Fpartner-center-portal%2Fupdate-existing-offer%23stop-selling-an-offer-or-plan&data=04%7C01%7Cteamsubm%40microsoft.com%7C2d1c15e7156f4855a8b308d8b0b50708%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637453638843467863%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=U7ti3JO7X98RyS9xhGXITKxGcT7uaN2ZlSWfD1Reh0A%3D&reserved=0) for more information.


A section for stop sell to be added in overview page under Publish to Teams Store [Overview - Publish your app to the Microsoft Teams store - Teams | Microsoft Docs](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/publish#teams-app-submission)

**Comment by v-chetsh** [comment]
@v-dreddipogu - What is the update on content changes?
