### ISSUE TITLE
Key Features section doesn't describe what the features do

### ISSUE THREAD

**Issue by craigpl** [MicrosoftDocs/msteams-docs#5476]
I don't find the Key Features section to be descriptive. I know nothing about these features. I expected the section "Key Features of an Incoming Webhook" to tell me what the features are. But I'm reading things like _Adaptive Cards ... can be sent through Webhooks_ and _Actionable messaging support ... are supported in all Office 365 groups_, which tell me nothing about what they are or what they provide for me.

I need your help to determine whether that info makes sense here or whether the reader should know what these things mean when they come to this page. Thanks. And great job on this page. I really like a lot of what I see on this page!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90ff2a84-a8bc-9259-d37d-622b102df75b
* Version Independent ID: e3b53e27-2946-189c-623b-9df704ea8f12
* Content: [Create an Incoming Webhook - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-incoming-webhook)
* Content Source: [msteams-platform/webhooks-and-connectors/how-to/add-incoming-webhook.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/webhooks-and-connectors/how-to/add-incoming-webhook.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by craigpl** [comment]
Rereading the page, I missed the description about Cards at the top of the page. I wonder if that might be enough for "Adaptive Cards". I think the "Actionable messaging support" comment still stands. Perhaps "actionable messaging support" is too techy and confusing.

**Comment by v-chetsh** [comment]
We will check and act on it accordingly.

**Comment by Nivedipa-MSFT** [comment]
@craigpl - In this document only features are directly mentioned which is supported by incoming webhook. We already have in detail description document for Adaptive Cards using an Incoming Webhook and Actionable messaging support.
