### ISSUE TITLE
TeamsFx CLI Page should not be part of Teams Toolkit in Visual Studio Code

### ISSUE THREAD

**Issue by MuyangAmigo** [MicrosoftDocs/msteams-docs#5483]
TeamsFx CLI contains almost all the features Teams Toolkit for Visual Studio Code has, it's probably better to be in the same level of Teams Toolkit for VS, Teams Toolkit for VS Code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e572f611-ae28-a06a-a66a-7d15c497496d
* Version Independent ID: e572f611-ae28-a06a-a66a-7d15c497496d
* Content: [TeamsFx Command Line Interface - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-cli)
* Content Source: [msteams-platform/toolkit/TeamsFx-CLI.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-CLI.md)
* Product: **msteams**
* GitHub Login: @MuyangAmigo
* Microsoft Alias: **zhany**

**Comment by Meghana-MSFT** [comment]
@surbhigupta12 - Could you please help to look into this issue and update the document accordingly.

**Comment by surbhigupta12** [comment]
@v-abirade, please look into this
