### ISSUE TITLE
Unable to click Edit and Close buttons when Conversation is open

### ISSUE THREAD

**Issue by mschultz-tls** [MicrosoftDocs/msteams-docs#549]
In Teams for Mac (v1.2.00.6957), when the Teams window is at a width where the Edit (dropdown) button and the Close buttons are above the Conversation pane the Edit and Close buttons are not clickable.  One has to widen the teams window so that the Edit and Close buttons are no longer over the conversation pane before they can be clicked.  It appears the buttons might be behind the conversation pane.

While creating this issue and getting the version, I also noticed that the dark gray ribbon that appears showing the version also shoved the Edit and Close buttons behind the conversation bubbles.   A screen shot is attached. 

It's also possible to narrow the window enough that the Edit and Close buttons are pushed off the right hand side and not visible at all.  The window is still wide enough to fully read the word document that I opened. As you can see from the screen shot the word doc does have a rather long name. 

![teamserror](https://user-images.githubusercontent.com/30450232/55515252-06d35980-561f-11e9-8703-34d7e22e40bf.png)

**Comment by Abhijit-MSFT** [comment]
Are you still facing this issue? Try updating it to newer version if you are still facing this issue.

**Comment by mschultz-tls** [comment]
I am actually. I'm running version 1.2.00.8866 which seems to be the most current version.

**Comment by Abhijit-MSFT** [comment]
This is bug. Thanks for reporting. We have raised bug and working on it.
