### ISSUE TITLE
This page should list breaking changes that are not backwards compatible.

### ISSUE THREAD

**Issue by TheBluLion** [MicrosoftDocs/msteams-docs#5492]
This page should list nodes that are not supported in older versions of the manifest

e.g. 
Manifest version 1.12 adds authorization which is not supported in earlier manifest versions. [Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f94a488-d636-92b3-21eb-c88744c8f272
* Version Independent ID: 7b3413f4-9ade-accf-5cb2-83fead11a32a
* Content: [Manifest schema reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema#authorization)
* Content Source: [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/resources/schema/manifest-schema.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by v-chetsh** [comment]
We will check on it from our end and act on it accordingly.

**Comment by sayali-MSFT** [comment]
@surbhigupta12 - Could you please help us to update the document?
Could please add the Note in Authorization section in below document?
Add Note:- Setting the version property to 1.12  makes your Authorization property incompatible with older manifest version. as they do not support .
Authorization supported to manifest schema version V1.12.

Document:-https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema#authorization

**Comment by surbhigupta12** [comment]
@v-shalinirobinson, please look into this.

**Comment by sayali-MSFT** [comment]
@v-shalinirobinson -Could you please help us to update the document?

**Comment by v-abirade** [comment]
@sayali-MSFT, I am working on it.
