### ISSUE TITLE
[iOS]  Action.Submit button in ActionSet in adaptive card as task module does not do anything

### ISSUE THREAD

**Issue by matthiasdilger** [MicrosoftDocs/msteams-docs#5506]
Teams iOS 4.5.0
User presses long on a message in Teams iOS to trigger context menu and then selects action based message extension "an action"
![154465201-91524f41-629f-44c4-b6cd-2c01c5777e2a](https://user-images.githubusercontent.com/5625718/159405115-478b4b21-3601-4f08-bb3a-ab029b4a9917.JPG)
Bot receives composeExtension/fetchTask
Bot creates this card in nodejs:
```
let card = CardFactory.adaptiveCard({
          "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
                 "type": "AdaptiveCard",
                 "version": "1.0",
                 "body": [          
                       {
                         "type": "TextBlock",
                         "text": "Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum",
                         "id": "text",
                         "wrap": true                
                       },              
                       {
                         "type": "Input.Text",
                         "id": "inputText",
                         "placeholder": "Some placeholder",
                         "maxLength": 2000,
                         "isMultiline": true,
                         "isVisible": true
                       },                            
                       {
                         "type": "ActionSet",
                         "id": "actionSet",
                         "actions": [
         {
                             "type": "Action.Submit",                    
                             "title": "Submit",                    
                             "data": {
                               "type": 1
                             }
                           }  
                         ]
                       }
         ]});
```
Bot returns the task module with card:
```
res.json({
        task: {
          type: 'continue',
          value: {
            card: card,
            height: 400,
            title: 'Test form submit',
            url: null,
            width: 500
          }
        }
      });
```
Teams iOS shows the task module but pressing the submit button does not do anything and nothing is received by the bot
![13241](https://user-images.githubusercontent.com/5625718/159405545-1fa633a7-6491-447b-a085-e473b86eebfc.jpg)

**Comment by Nivedipa-MSFT** [comment]
@matthiasdilger - We are investigating your query. We will get back to you once we have any update.

**Comment by matthiasdilger** [comment]
hi @Nivedipa-MSFT, were you able to reproduce the issue?

**Comment by Nivedipa-MSFT** [comment]
@matthiasdilger - We are still checking this. We will update you soon.

**Comment by Nivedipa-MSFT** [comment]
@matthiasdilger - We have checked this in Teams IOS version 4.4. But we are not getting the adaptive card. Blank popup is coming.

**Comment by matthiasdilger** [comment]
@Nivedipa-MSFT Yes, Teams iOS 4.4 did not display anything because of this issue: #5271 
You need to update to version 4.5.0 to reproduce this issue here.

**Comment by Nivedipa-MSFT** [comment]
@matthiasdilger - Thanks for the updates. We will update the Teams version and check again. We will inform you soon.

**Comment by Nivedipa-MSFT** [comment]
@matthiasdilger - As of now for us the latest version is showing as 4.4.0 and we are not able to update to 4.5.0

**Comment by matthiasdilger** [comment]
@Nivedipa-MSFT Interesting, latest version is 4.5.1 according to [https://apps.apple.com/us/app/microsoft-teams/id1113153706](https://apps.apple.com/us/app/microsoft-teams/id1113153706)

**Comment by v-chetsh** [comment]
@matthiasdilger - Our iOS device is not showing any updates to upgrade it to 4.5.0 .
We will check it in next 1 or 2 days for updates & will try you issue once we get latest version.

**Comment by Nivedipa-MSFT** [comment]
@matthiasdilger - We have raised a bug for it. We will let you know once we get updates on it.

**Comment by matthiasdilger** [comment]
@Nivedipa-MSFT Hi, is there any timeline on when this bug will be fixed? It's still present in Teams iOS 4.7.0 and severely impacts functionality IMO. Thanks

**Comment by Nivedipa-MSFT** [comment]
@matthiasdilger - We have informed Engineering team about the same and they are currently working on the fix. We will inform you once we have further update. Thanks!

**Comment by matthiasdilger** [comment]
Hi @Nivedipa-MSFT This issue still persists in Teams iOS 4.10, do you have any update on when this bug will be fixed? Thanks.

**Comment by Prasad-MSFT** [comment]
@matthiasdilger - We have informed Engineering team about the same and they are currently working on the fix. There is no such ETA to share. We will inform you once we have further update. Thanks!

**Comment by matthiasdilger** [comment]
@Nivedipa-MSFT Thanks for the tip!
