### ISSUE TITLE
Application-Hosted Media Bot Documentation

### ISSUE THREAD

**Issue by damienestewart** [MicrosoftDocs/msteams-docs#551]
Right now it's hard to figure out where to start when building application-hosted media bots. I'm trying to do this using Service Fabric. Are there any tutorials available that guide devs, step-by-step, on how to accomplish this (and most importantly explains the steps)? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d5ed4b3-590b-20d2-4e10-d2fe063ca2bf
* Version Independent ID: 66dd2362-62a7-269a-a049-9e15a4e9e966
* Content: [Requirements and considerations for application-hosted media bots - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/calls-and-meetings/requirements-considerations-application-hosted-media-bots)
* Content Source: [msteams-platform/concepts/calls-and-meetings/requirements-considerations-application-hosted-media-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/calls-and-meetings/requirements-considerations-application-hosted-media-bots.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ksikorsk** [comment]
Hello,

Have you looked at our samples?

Here are a couple application hosted media bots samples:
https://github.com/microsoftgraph/microsoft-graph-comms-samples/tree/master/Samples/LocalMediaSamples

HueBot specifically runs on service fabric:
https://github.com/microsoftgraph/microsoft-graph-comms-samples/tree/master/Samples/LocalMediaSamples/HueBot/HueBot

The repository also contains SDK reference documentation and some additional articles:
https://github.com/microsoftgraph/microsoft-graph-comms-samples
