### ISSUE TITLE
Unable to install App Studio

### ISSUE THREAD

**Issue by hsncrook** [MicrosoftDocs/msteams-docs#552]
I'm unable to install, let alone find, App Studio in Teams. When I search for 'App Studio' or 'Studio' in the Teams Store the result is: We didn't find any matches. Hmm...

Anyone a suggestion?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c181f8cb-871f-09f5-1210-352afeaf0271
* Version Independent ID: 2a62e83d-0dd5-0cff-e45f-73d451f10b63
* Content: [Get started with App Studio for Microsoft Teams - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/get-started/get-started-app-studio#feedback)
* Content Source: [msteams-platform/get-started/get-started-app-studio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/get-started/get-started-app-studio.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by yahiyaiqbal** [comment]
I am having same issue.

**Comment by Wajeed-msft** [comment]
@hsncrook - Could you please check with your tenant admin if [external apps are enabled in your tenant](https://docs.microsoft.com/en-us/MicrosoftTeams/enable-features-office-365#external-apps)?

**Comment by hsncrook** [comment]
@Wajeed-msft, thanks a million. External apps where not enabled.
