### ISSUE TITLE
SAML authentication - Teams tab SSO

### ISSUE THREAD

**Issue by SubbaReddi** [MicrosoftDocs/msteams-docs#5526]
If the application supports SAML SSO, then we could not able to use tab SSO generated JWT token. As it is not supported, Can you add the note for the same.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d5b8b0f-3da3-8642-6edf-dc6608a830cf
* Version Independent ID: f93cdabd-f6ab-29d0-f3c9-78deb21ca521
* Content: [Authentication flow for tabs - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-flow-tab)
* Content Source: [msteams-platform/tabs/how-to/authentication/auth-flow-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/tabs/how-to/authentication/auth-flow-tab.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Nivedipa-MSFT** [comment]
@v-shalinirobinson - Could you please help here to add the note in below doc
[Authentication flow for tabs - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-flow-tab)


Content for addition - If the application supports SAML SSO, then we could not able to use tab SSO generated JWT token. As it is not supported
