### ISSUE TITLE
Information on locale is misplaced here

### ISSUE THREAD

**Issue by aosolis** [MicrosoftDocs/msteams-docs#5528]
Why is this here?
![image](https://user-images.githubusercontent.com/767208/159597393-1eb17711-fdcf-4e3f-a033-ce7b11273a3d.png)

The information in this note does not fit with the content on this page. No one will be going to the page entitled "Upload your custom app" when they are looking for information on getting the locale on installation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54780e5a-ca3a-5277-dc84-37f85d9ea1cb
* Version Independent ID: 5f89865b-a9fd-ada5-72d2-6375357bba8c
* Content: [Upload your custom app - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/apps-upload#upload-your-app)
* Content Source: [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/deploy-and-publish/apps-upload.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **surbhigupta**

**Comment by v-chetsh** [comment]
We will check and act on it accordingly.

**Comment by sayali-MSFT** [comment]
@surbhigupta12 - Could you please help us to update the document?
Move the above [note](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/apps-upload#upload-your-app) to other document which are as below:-
Document:-https://docs.microsoft.com/en-us/microsoftteams/platform/bots/bot-basics?tabs=csharp#bot-logic
