### ISSUE TITLE
New-Team limited templates

### ISSUE THREAD

**Issue by kpinel** [MicrosoftDocs/msteams-docs#5529]
We are in an educational institution so have need to use the EDU templates. The template that is probably second most important is the Staff template. This is available using the Graph API (https://graph.microsoft.com/v1.0/
teamsTemplates('educationStaff')) but not from PowerShell, which I believe uses Graph. Currently, we have to provision these manually. Not an easy feat when you are creating upwards of 100 Teams each semester.

Any idea of when all the templates available to the API will be available to PowerShell?

**Comment by v-chetsh** [comment]
@kpinel - Sorry for the late reply.
Do you still need any help or your issue has resolved?

**Comment by kpinel** [comment]
I have transitioned our automation over to MS Graph but the additional education templates would be beneficial to other institutions

**Comment by sayali-MSFT** [comment]
@kpinel - Could you please elaborate your requirement and share the repro steps, so that we can try it from our end.
