### ISSUE TITLE
Node js example to send message

### ISSUE THREAD

**Issue by awesomefei** [MicrosoftDocs/msteams-docs#553]
I see in the c# example, we can send message "Hello" through bot, but in the Nodejs example, where should I put the message content "Hello"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba8d3979-14f5-3105-ad89-ce6f98d11df1
* Version Independent ID: e53a7d1e-0e70-ca30-9809-fda7ebe5f4da
* Content: [Proactive messages - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/bots/bot-conversations/bots-conv-proactive#using-net)
* Content Source: [msteams-platform/concepts/bots/bot-conversations/bots-conv-proactive.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/bots/bot-conversations/bots-conv-proactive.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Wajeed-msft** [comment]
@awesomefei - You could simply create new message and send to the address you created. Try this:

```
        var msg = new builder.Message().address(address);
        msg.text('Hello, this is a notification');
        bot.send(msg);
```

Here is link to [sample code to send proactive message](https://github.com/OfficeDev/microsoft-teams-sample-complete-node/blob/master/src/dialogs/examples/teams/ProactiveMsgTo1to1Dialog.ts#L16).
