### ISSUE TITLE
Sample code

### ISSUE THREAD

**Issue by tmaheshwar** [MicrosoftDocs/msteams-docs#554]
Can we get Sample code specific to Static Tab which can be imported in App Studio via Github or some other means

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51ca77fe-cc16-a40c-d157-582d51b29d1a
* Version Independent ID: bb36842e-d434-1464-533f-769879c91bdd
* Content: [Static tabs - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/tabs/tabs-static)
* Content Source: [msteams-platform/concepts/tabs/tabs-static.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/tabs/tabs-static.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Wajeed-msft** [comment]
@tmaheshwar - Please have a look at [Get Started](https://docs.microsoft.com/en-us/microsoftteams/platform/samples/code-samples#get-started) sample code. Please follow the [get started guide](https://docs.microsoft.com/en-us/microsoftteams/platform/get-started/get-started-dotnet-app-studio) for these samples.
