### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by DamoBird365** [MicrosoftDocs/msteams-docs#5542]
Hi, there is a deadlink to https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/msteams-platform/concepts/design/understand-use-cases.md -> see also "[Understand Microsoft Teams app capabilities]"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 100070d1-40f9-b5eb-be0a-6199de26e0e6
* Version Independent ID: 5d1269e3-2775-ebf6-cf9a-8d1ee7038397
* Content: [Microsoft Teams app templates - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/samples/app-templates#see-also)
* Content Source: [msteams-platform/samples/app-templates.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/samples/app-templates.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Prasad-MSFT** [comment]
@surbhigupta12 - Could you please help here to update this [doc](https://docs.microsoft.com/en-us/microsoftteams/platform/samples/app-templates#see-also) as its showing _404- Not found_ for [Understand Microsoft Teams app capabilities](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/capabilities-overview) section.

**Comment by ashishguptaiitb** [comment]
Seems to be caused by #5408 
If yes, then #4636 may also lead to another bug. Please check once @surbhigupta12
