### ISSUE TITLE
Clarify where personal tabs can be surfaced

### ISSUE THREAD

**Issue by Rick-Kirkham** [MicrosoftDocs/msteams-docs#5549]
I don't seem to have permissions to create a PR, so I'll create an issue. 

"When you upgrade your Teams personal tab and sideload it in Teams, it will also run in Outlook desktop and web clients and Office on the web (office.com). Here's how to preview it from those Microsoft 365 experiences."

The preceding paragraph has these problems: 

1. There is a 4th place not mentioned in the paragraph: Office on Windows, and it has a subsection below this paragraph parallel to the three places mentioned in the paragraph.
2. The term "desktop" is ambiguous. It includes Outlook and Office on Mac and perpetual license Office and Outlook, but neither of these support personal tabs at this time.

I recommend changing the paragraph to this:

"When you upgrade your Teams personal tab and sideload it in Teams, it will also run in Outlook on Windows and on the web and Office on Windows and on the web (office.com). Here's how to preview it from those Microsoft 365 experiences."

Also, the subsections below this paragraph labelled "Outlook" and "Office" should be renamed "Outlook on Windows" and "Office on Windows" to avoid being misleading. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2cf31a5-621a-eeac-26c9-89ada49466c0
* Version Independent ID: b2cf31a5-621a-eeac-26c9-89ada49466c0
* Content: [Extend a Teams personal tab app across Microsoft 365 - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/m365-apps/extend-m365-teams-personal-tab?tabs=manifest-teams-toolkit)
* Content Source: [msteams-platform/m365-apps/extend-m365-teams-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/m365-apps/extend-m365-teams-personal-tab.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Nivedipa-MSFT** [comment]
@Rick-Kirkham - We are investigating your query. We will get back to you once we have any update.
