### ISSUE TITLE
Buttons for invoking a task module from adaptive cards are broken in conversations.

### ISSUE THREAD

**Issue by Navega** [MicrosoftDocs/msteams-docs#556]
The buttons in adaptive cards to invoke a task module don't work in personal conversations, just in channels, from 2-3 days ago. We didn't change anything in our system, but they don't work now.

Ref: https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/task-modules/task-modules-bots#bot-framework-card-actions-vs-adaptive-card-actionsubmit-actions

We use this action:

```
"actions": [ { "type": "Action.Submit",
                    "title": "Open Item",
                    "data": {
                        "msteams": {
                            "type": "task/fetch"
                        }
                    }
                } ]
```

We get this JS error in Teams when we click the button in card: 

> postInvokeMessage failed: "Couldn't find team and channel for the channel"

Any recent update could break this?

Update: this problem just happens with cards generated by message extension, not by bot.

Navega, Software developer at Appfluence Inc.

**Comment by Gousia-MSFT** [comment]
@Navega we have tried opening task module from the json you shared and it works fine for us.Could you please try the [Task Module Sample C#](https://github.com/OfficeDev/microsoft-teams-sample-task-module-csharp).Please share your manifest if that does not help.

**Comment by Navega** [comment]
Thanks for your answer @Gousia-MSFT , I am trying it but I don't get success.

Was the card that you use generated by a messaging extension or bot conversation? I have that problem when I injected the adaptive card from Messaging Extension in any conversation.

**Comment by Gousia-MSFT** [comment]
@Navega I tried it from Bot Conversation. Invoking it from Message Extension does not work. We have filed bug for this. We are working on fixing this.

**Comment by pablodiazgutierrez** [comment]
If we can help test any patches, please ask.

**Comment by Navega** [comment]
Now, this was broken also for cards generated by bot...

Ref: [https://github.com/MicrosoftDocs/msteams-docs/issues/608](https://github.com/MicrosoftDocs/msteams-docs/issues/608)

**Comment by Wajeed-msft** [comment]
This has been fixed. Please re-open if you are still facing this issue.

**Comment by Navega** [comment]
Re-opening because this is happening again for cards in Messaging extension, for conversations and channgels.

![issue](https://user-images.githubusercontent.com/16117077/61613348-65215800-ac61-11e9-8512-0226b5d01fa5.JPG)
