### ISSUE TITLE
[Doc-Update] If the domain value having Upper case letters, Tab SSO is not working in Android

### ISSUE THREAD

**Issue by SubbaReddi** [MicrosoftDocs/msteams-docs#5565]
Hi Team,
If the domain value having upper case letters then developers keeping same upper case letters in webApplicationInfo, tab url, expose an API section. And then Tab SSO is not working in Android. But working fine in other clients. Either this needs to be documented or need bug fix.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52221dd3-95ec-96b9-1da8-9478527c2602
* Version Independent ID: 32e9c2d8-733d-0865-2ea3-727d8684a10d
* Content: [Single sign-on support for tabs - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-aad-sso?tabs=dotnet)
* Content Source: [msteams-platform/tabs/how-to/authentication/auth-aad-sso.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/tabs/how-to/authentication/auth-aad-sso.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Prasad-MSFT** [comment]
Thanks for your notice. We will check it and will take appropriate measures.

**Comment by Wajeed-msft** [comment]
@Prasad-MSFT - could you please check and confirm this behaviour?
