### ISSUE TITLE
statement

### ISSUE THREAD

**Issue by tmaheshwar** [MicrosoftDocs/msteams-docs#557]
If you register your bot using Microsoft Azure, it does not need to be hosted on Microsoft Azure.

This line is confusing, can you please provide details

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 087ab52e-fa36-8255-1438-957f895ba583
* Version Independent ID: f19cdd18-9aef-2bb2-6c2f-e0f0f79b9ca0
* Content: [Create a bot - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/bots/bots-create)
* Content Source: [msteams-platform/concepts/bots/bots-create.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/bots/bots-create.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Wajeed-msft** [comment]
@tmaheshwar - In Azure, you get an option to have **Bot Channel Registration**. Your own Bot hosted where you want can be registered with the Azure Bot Service. It's not mandatory for you to host bot code in Azure.

![image](https://user-images.githubusercontent.com/31851992/56042987-ef504b00-5d59-11e9-9223-16b25b9198be.png)
