### ISSUE TITLE
Compose extension task module does not work on chat not initiated peoples

### ISSUE THREAD

**Issue by kumaresanraven** [MicrosoftDocs/msteams-docs#5584]
We have a app with compose extension,, compose extension to open a task module it working as expected with the already started conversation users, but throws an error for the people whom i did not have started the conversation.. error - errorMessage: 'Invoke failed due to internal error: Invoke failed: something went wrong in ProcessInvoke' while opening task module it says something went wrong please try again..

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e04556b-f4b1-316e-bac1-ca77c6ab287f
* Version Independent ID: 2ee29289-b250-4ba3-e957-7a42122a266e
* Content: [Create and send the task module - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/action-commands/create-task-module?tabs=dotnet)
* Content Source: [msteams-platform/messaging-extensions/how-to/action-commands/create-task-module.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/messaging-extensions/how-to/action-commands/create-task-module.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **anclear**

**Comment by Nivedipa-MSFT** [comment]
@kumaresanraven - We are able to repro this issue and we have raised a bug for it. We will let you know once we get updates on it.

**Comment by Nivedipa-MSFT** [comment]
@kumaresanraven - We got an update from engineering team that this is by design behaviour.
Compose extension task module does not work on chat not initiated peoples.
