### ISSUE TITLE
Unable to use the `composeExtensions[0].commands[0].context` with just `commandBox`

### ISSUE THREAD

**Issue by kartikluke** [MicrosoftDocs/msteams-docs#564]
With the schema: https://raw.githubusercontent.com/OfficeDev/microsoft-teams-app-schema/preview/DevPreview/MicrosoftTeams.schema.json

When using `"context": ["compose","commandBox"]`, I get the error:

```
Error: An error occurred while parsing the manifest.json file; Value "commandBox" is not defined in enum. Path 'composeExtensions[0].commands[0].context[1]', line 61, position 52.
```

The weird thing is that if you check the schema it is there in the enum:

```
"context": {
    "type": "array",
    "maxItems": 3,
    "items": {
        "enum": [
            "compose",
            "commandBox",
            "message"
        ]
    },
    "description": "Context where the command would apply",
    "default": ["compose","commandBox"]
},
```

**Comment by kartikluke** [comment]
`"context": ["compose","message"]` works however. Not entirely sure what `commandBox` means. I assumed it was the button at the bottom of the message menu but that's not the case.

**Comment by clearab** [comment]
Compose is the buttons at the bottom of the screen where you make a new message, commandBox is the box at the top where you search and use "/" commands.

Can you try using "commandbox"?

**Comment by clearab** [comment]
@MattSFT

**Comment by clearab** [comment]
I'm fairly certain lowercase will work for now, which is actually a bug. On or around 4/22 the change to move that to camel case will be published, which will unfortunately mean you'll have to change this again then. I'll get the documentation updated to reflect this.
