### ISSUE TITLE
Closing task module from Bot (back-end, nodeJS)

### ISSUE THREAD

**Issue by atymic** [MicrosoftDocs/msteams-docs#5641]
See; https://github.com/MicrosoftDocs/msteams-docs/issues/832

Hi,
It doesn't look like the docs have been updated, and the .net example uses inputs which are not in the node framework. How can i close the task model in nodejs?

**Comment by sayali-MSFT** [comment]
@atymic -We are looking into this I will get back to you soon.

**Comment by sayali-MSFT** [comment]
@atymic -Please have a look at this doc-
Here is sample in Node JS Teams Task module-https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/javascript_nodejs/54.teams-task-module

Could you please elaborate the requirement which needs to be change in document?

**Comment by atymic** [comment]
@sayali-MSFT 

As per the previous document, how can we close a task module submit without sending a card in the response?
The example you linked send a message which is displayed in the dialog

https://github.com/microsoft/BotBuilder-Samples/blob/main/samples/javascript_nodejs/54.teams-task-module/bots/teamsTaskModuleBot.js#L71-L77

This is the same issue as this ticket, just I am using node
https://github.com/MicrosoftDocs/msteams-docs/issues/832

**Comment by sayali-MSFT** [comment]
@atymic -You can refer this -https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/c173c0e7a316df7425db1d795713e46c00594632/samples/bot-sharepoint-file-viewer/nodejs/bots/dialogBot.js#L64
As per my understanding, If you wants to close task module without returning any response. I don't think it may be possible.

**Comment by sayali-MSFT** [comment]
@atymic -Could you please confirm if your issue has resolved with above suggestion or still looking for any help?

**Comment by atymic** [comment]
@sayali-MSFT it appears it is possible, see this comment:
https://github.com/MicrosoftDocs/msteams-docs/issues/832#issuecomment-538038949

cc @vman @Wajeed-msft

**Comment by sayali-MSFT** [comment]
@atymic -We are try it from our end and let you know.

**Comment by sayali-MSFT** [comment]
@atymic - Could you please refer this sample  -https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/c173c0e7a316df7425db1d795713e46c00594632/samples/bot-sharepoint-file-viewer/nodejs/bots/dialogBot.js#L64

**Comment by atymic** [comment]
Returning null causes the error in the original post.

**Comment by v-chetsh** [comment]
@atymic - Please confirm whether your issue has resolved or still need any help?

**Comment by atymic** [comment]
No it's not resolved. See my comment above, we get an error if null is returned (as is the issue in the original post)

**Comment by sayali-MSFT** [comment]
Hello @atymic ,@rajeshbal-We are tried with the below code and It's working fine from our end.Task module close without getting any error.
Microsoft Teams Version 1.5.00.30306 (64-bit)-E.
also If your issue is not resolved using below code ,please share short video or screenshots so that we can investigate from our end.
```
    async handleTeamsTaskModuleSubmit(context, taskModuleRequest) {
  
        await context.sendActivity(MessageFactory.text('handleTeamsTaskModuleSubmit: ' + JSON.stringify(taskModuleRequest.data)));       
        return null;
    }
```


https://user-images.githubusercontent.com/93527375/200259830-bd42cb4c-0917-4caa-93cf-96934887353f.mp4
