### ISSUE TITLE
chatMessage subscription validated and created but never fired

### ISSUE THREAD

**Issue by tianalemesle** [MicrosoftDocs/msteams-docs#5648]
Hello,

A `POST https://graph.microsoft.com/v1.0/subscriptions` request containing `resource` = `/me/chats/{threadId}/messages` returns `201` and validates `notificationUrl` using `Validation: Testing client application reachability for subscription` successfully.

But, when sending messages, creating and ending recordings, in the above-mentioned thread, before `expirationDateTime` is reached, no notification is ever fired.

In the meantime, manually requesting `GET https://graph.microsoft.com/v1.0/me/chats/{threadId}/messages` works.

Thanks

**Comment by sayali-MSFT** [comment]
@tianalemesle - We are looking into this I will get back to you soon.

**Comment by sayali-MSFT** [comment]
@tianalemesle -We are unable to repro the scenario. Could you please share the repro steps or error log.so we can try it from our end?
Did you get any error while creating subscription?

**Comment by tianalemesle** [comment]
> Could you please share the repro steps

As mentioned in my original message :
1. Send `POST` request to `https://graph.microsoft.com/v1.0/subscriptions` with body containing
    - `changeType` = `created`
    - `notificationUrl` being an URL
    - `resource` like `/me/chats/{threadId}/messages`
    - `expirationDateTime` like `YYYY-MM-DDTHH:MM:SS.sssZ`
2. Receive `POST` request to specified `notificationUrl`
3. Reply to request received at step 2 with
    - body strictly equal to the received query string parameter `validationToken` starting with `Validation: Testing client application reachability for subscription`
    - `200` HTTP code
    -  `Content-Type` header set with `text/plain`
4. Receive reply from request sent at step 1 with `201` HTTP code and body containing
    - `@odata.context` = `https://graph.microsoft.com/v1.0/$metadata#subscriptions/$entity`
    - `id` being a UUID
    - `resource` being the same as sent at step 1
    - `applicationId` being a UUID
    - `changeType` being the same as sent at step 1
    - the following keys being `null`
        - `clientState`
        - `notificationQueryOptions`
        - `lifecycleNotificationUrl`
        - `includeResourceData`
        - `encryptionCertificate`
        - `encryptionCertificateId`
        - `notificationUrlAppId`
    - `notificationUrl` being the same as sent at step 1
    - `expirationDateTime` being the same as sent as step 1 *(except format ending with `ssZ` instead of `sssZ`)*
    - `creatorId` being a UUID
    - `latestSupportedTlsVersion` = `v1_2`

> error log

There is no error at all.

> Did you get any error while creating subscription?

None. As mentioned in my original message and just above, I receive a `201` HTTP code, which indicates success.

**Comment by sayali-MSFT** [comment]
@tianalemesle -Sorry for delay, We are check it from our end and let you know.

**Comment by RamjotSingh** [comment]
Can you share a client-request-ID (it is in response headers) for the initial subscription creation request? Also the expiration time you sent.

**Comment by tianalemesle** [comment]
> client-request-ID

Unfortunately, my logs don't include headers...
> expiration time

`2022-03-25T12:49:28.370Z`

**Comment by RamjotSingh** [comment]
Can you share tenantId and AADAppId? Timestamp when the request was made?

**Comment by tianalemesle** [comment]
> tenantId

`2bed746b-118b-4413-a24c-26250d510dbe`
> Timestamp

`2022-03-25T11:49:28.371Z`

Thanks !

**Comment by tianalemesle** [comment]
Done ! I logged headers this time.

`client-request-id`: `8d2fdf36-d4ad-445e-a72d-4348f0152ed7`

Thanks

**Comment by RamjotSingh** [comment]
Thanks, we will investigate and get back.

**Comment by RamjotSingh** [comment]
Can you use `/chats/id/messages` as path instead of `/users/id/chats/id/messages` as path? `/users/id/chats/id/messages` isn't a supported path.

**Comment by tianalemesle** [comment]
It works !

I would like to suggest adding some documentation warning and input validation for this.
(Or add support for this path)

Indeed, [List messages in a chat](https://docs.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-1.0&tabs=http) shows both `/me/chats/{chat-id}/messages` and `/chats/{chat-id}/messages`, while [Use the Microsoft Graph API to get change notifications](https://docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0) & [Get change notifications for messages in Teams channels and chats using Microsoft Graph](https://docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage#subscribe-to-messages-in-a-chat) only shows `/chats/{id}/messages`, but this distinction is very subtle so I lost a lot of time on it.

Thanks !
