### ISSUE TITLE
chatMessageHostedContent expiration ?

### ISSUE THREAD

**Issue by tianalemesle** [MicrosoftDocs/msteams-docs#5649]
Hello,

Requesting `GET https://graph.microsoft.com/v1.0/chats/{threadId}/messages/{messageId}/hostedContents/{hostedContentId}/$value` seems to work up to 24-48 hours after the chatMessage creation, but returns `404` after that.

Does the link expire, if yes, what is the actual duration of the link, and can it be delayed or can the link be renewed ?

Thanks

**Comment by Nivedipa-MSFT** [comment]
@tianalemesle - We are investigating your query. We will get back to you once we have any update.

**Comment by Nivedipa-MSFT** [comment]
@tianalemesle - Could you please share the document which you are referring for this?

**Comment by tianalemesle** [comment]
Yet the request works, just not up to more than 24-48 hours.

**Comment by Nivedipa-MSFT** [comment]
@tianalemesle - we are checking this with engineering team. We will update you soon.

**Comment by Nivedipa-MSFT** [comment]
@tianalemesle - We have to check if there is a policy for expiration. Can you please give request ID for further investigation?

**Comment by tianalemesle** [comment]
Here's an example of a request which returns 404 for content that used to be available : `5eba76f3-3129-444c-a708-5f456df9be49`

Thanks

**Comment by Nivedipa-MSFT** [comment]
@tianalemesle - Could you please check your hostedcontent available in Onedrive?
We have checked using this request id. The hostedcontent include a video.
File attachments which include image/png, audio/wav, and video/mp4 are stored in SharePoint or OneDrive.
Firstly its hosted in chat thats why its working before but after exporting to onedrive then it will delete from there thats why its returning 404.
There will be separate APIs to access these which is still work in progress

**Comment by tianalemesle** [comment]
> Could you please check your hostedcontent available in Onedrive?

Unfortunately I can't be sure because I don't remember which file it was, because I generated a lot of those.
I would be able to tell for sure if you could find the file's name.
Anyway, the file is most likely still available, yes.

> Firstly its hosted in chat thats why its working before but after exporting to onedrive then it will delete from there thats why its returning 404.

How much time after ?
Here's a new example :
```
Transfer-Encoding: chunked
Content-Type: video/mp4
Strict-Transport-Security: max-age=31536000
request-id: 6b26e95d-3593-4cda-9c22-cf05684a00d1
client-request-id: 6b26e95d-3593-4cda-9c22-cf05684a00d1
x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"North Europe","Slice":"E","Ring":"4","ScaleUnit":"005","RoleInstance":"DU6PEPF00002DF4"}}
Date: Thu, 07 Apr 2022 16:08:05 GMT
```
This file, named `bxfbdfbdxdrxhrxhd-20220407_092537-Enregistrement%20de%20la%20r%C3%A9union.mp4` is currently available in both chat and at `my.sharepoint.com`.
It was generated yesterday.
The `GET` request to it still currently works :
```
Transfer-Encoding: chunked
Content-Type: video/mp4
Strict-Transport-Security: max-age=31536000
request-id: 1adaded6-0aee-485f-94d2-92ab401f8eb3
client-request-id: 1adaded6-0aee-485f-94d2-92ab401f8eb3
x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"France Central","Slice":"E","Ring":"5","ScaleUnit":"001","RoleInstance":"PA2PEPF00002714"}}
Date: Fri, 08 Apr 2022 12:44:12 GMT
```
I would like to be able to know for how much more time.
Based on my previous experiences, I'd say it will be unavailable by monday at last.
> There will be separate APIs to access these which is still work in progress

Would it be possible to get notified on this issue right here as soon as it's done ?
Thanks

**Comment by tianalemesle** [comment]
> Based on my previous experiences, I'd say it will be unavailable by monday at last.

Confirmed :
```json
{
    "error": {
        "code": "NotFound",
        "innerError": {
            "client-request-id": "01736674-0496-4502-99de-fb45111d2dcb",
            "date": "2022-04-11T08:39:39",
            "request-id": "01736674-0496-4502-99de-fb45111d2dcb"
        },
        "message": "UnknownError"
    }
}
```
The file is still available at `my.sharepoint.com`.

**Comment by Nivedipa-MSFT** [comment]
@tianalemesle - We are checking this with engineering team. we will get back to you soon.

**Comment by tianalemesle** [comment]
So, which factors actually affects this duration ? Thanks

**Comment by Nivedipa-MSFT** [comment]
@tianalemesle - We are checking this with engineering team. We will inform you once we have any update.

**Comment by v-chetsh** [comment]
@tianalemesle - We are closing this issue for now, Please feel free to reopen it, if required.
