### ISSUE TITLE
Allow empty selection in people picker

### ISSUE THREAD

**Issue by matthiasdilger** [MicrosoftDocs/msteams-docs#5658]
Scenario: A Teams tab with a list of projects, each project can be assigned to multiple coworkers
Each project is assigned by using a people picker that allows selecting multiple users (default)
After assigning a project to multiple users using the people picker and submitting the picker, the user notices that the wrong project has been selected and needs to un-assign their coworkers from the project.
This is currently not possible using just the people picker. When the picker is launched with `setSelected`, it's not possible to clear out the list and submit the picker. The UI needs to have a separate "Unassign project" button that removes all users from the project.

Suggestion: If people picker has been launched with a new property `allowEmptySelection` set to `true`, allow the user to remove all entries and submit an empty list.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2bafb046-4848-f113-8ea4-6ae1865c26fd
* Version Independent ID: bfae5321-cfaf-591e-d5bd-292d9f206462
* Content: [Integrate People Picker - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/people-picker-capability?tabs=Samplemobileapp#selectpeople-api)
* Content Source: [msteams-platform/concepts/device-capabilities/people-picker-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/device-capabilities/people-picker-capability.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **surbhigupta**

**Comment by Meghana-MSFT** [comment]
Thank you for the suggestion. We will take a look at it and take necessary action.

**Comment by Meghana-MSFT** [comment]
We have raised a bug for the same. We will keep you posted on the updates.

**Comment by Meghana-MSFT** [comment]
@matthiasdilger - Apologies for the delay, team has considered this as a feature request. Could you please help submit this on [Microsoft Teams feedback portal](https://feedbackportal.microsoft.com/feedback/forum/ad198462-1c1c-ec11-b6e7-0022481f8472).

**Comment by matthiasdilger** [comment]
@Meghana-MSFT Done: https://feedbackportal.microsoft.com/feedback/idea/a942a014-e35c-ee11-a81c-0022484e5453
