### ISSUE TITLE
Duplicate message after adaptive card submit action. 

### ISSUE THREAD

**Issue by astuj** [MicrosoftDocs/msteams-docs#5668]
I've noticed a bug on teams regarding adaptive cards submit button. We get duplicate message/cards back if any API call take time to complete. The turn is executed twice in this case.
<img width="997" alt="Screenshot 2022-04-05 at 12 21 09 PM" src="https://user-images.githubusercontent.com/20801184/161696023-d71a9629-1d99-4bba-9713-95124c35ff55.png">

When we get the message Unable to reach app on an adaptive card submit action the turn in the bot is executed twice and we get duplicate messages back. 

Steps to repo in your local: 

1) Place a debugger
2) Click on the submit action on the adaptive card 
3) Wait for 5 -10 sec on the debugger 
4) Remove the debugger and continue 

Actual : We get the same message/card twice
Expected : The message should only appear once

**Comment by sayali-MSFT** [comment]
@astuj -We are looking into this I will get back to you soon.

**Comment by sayali-MSFT** [comment]
@astuj -It looks like bot is re-sending the same REST call multiple times for long running rest calls.

Could you please refer the following document to Manage long-running operation:
[Manage a long-running operation using the Bot Framework SDK - Bot Service | Microsoft Docs](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-long-operations-guidance?view=azure-bot-service-4.0)

Let us know if you have any query.

**Comment by sayali-MSFT** [comment]
@astuj -Could you please confirm if your issue has resolved with above suggestion or still looking for any help?

**Comment by astuj** [comment]
I was able to resolve it thanks
