### ISSUE TITLE
Error: “Received error from connectors” when testing connector sample

### ISSUE THREAD

**Issue by XimenaWang** [MicrosoftDocs/msteams-docs#568]
Hi team,
I received error after clicking "save" button, I am not sure what thing I'm missing. can you take a look for me , thanks!
connector simple:
![image](https://user-images.githubusercontent.com/30890958/56192547-7a904180-5fe3-11e9-9f3b-3c814240bf01.png)
error info:
![image](https://user-images.githubusercontent.com/30890958/56192399-18cfd780-5fe3-11e9-8736-d526b28d1296.png)

**error info**:
2019-04-16T07:54:56.841Z Received error from connectors {"seq":1555315024097,"timestamp":1555401296717,"flightSettings":{"Name":"ConnectorFrontEndSettings","AriaSDKToken":"d127f72a3abd41c9b9dd94faca947689-d58285e6-3a68-4cab-a458-37b9d9761d35-7033","SPAEnabled":true,"ClassificationFilterEnabled":true,"ClientRoutingEnabled":true,"EnableYammerGroupOption":true,"EnableFadeMessage":false,"EnableDomainBasedOwaConnectorList":false,"EnableDomainBasedTeamsConnectorList":false,"DevPortalSPAEnabled":true,"ShowHomeNavigationButtonOnConfigurationPage":false},"status":500,"clientType":"SkypeSpaces","connectorType":"75273d70-b2de-47c1-a582-3e2ca26cf3b4","name":"handleMessageError"}

HTTP500: SERVER ERROR - The server encountered an unexpected condition that prevented it from fulfilling the request.
(XHR)POST - https://binglseteamsicmconnectorapp.azurewebsites.net/Connector/Save

**Comment by Wajeed-msft** [comment]
@XimenaWang - Did you add https://bingicmconnector.azurewebsites.net in your valid domains section in [Connectors Developer Dashboard](https://outlook.office.com/connectors/publish)? If it's still not working, could you please share your app manifest?

**Comment by XimenaWang** [comment]
@Wajeed-msft - thanks! I still got some errors,  
![image](https://user-images.githubusercontent.com/30890958/56258742-7caadc80-6085-11e9-9505-7a7f5b5f7b30.png)

but the strange thing is that Teams shows this test connector was added successfully to my channel.
![image](https://user-images.githubusercontent.com/30890958/56258912-0fe41200-6086-11e9-9e65-9d38fe96d0eb.png)
I am not sure whether this is successful~~

**Comment by Wajeed-msft** [comment]
@XimenaWang - Are you able to send [Connector card message](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/connectors/connectors-using#example-connector-message) to the webhook you received?

**Comment by vbarrier** [comment]
I got the same error @Wajeed-msft can you help me?

**Comment by priyankurs** [comment]
Hey @vbarrier did you resolve the issue...I'm facing the same issue.....wanted help in this...

**Comment by vbarrier** [comment]
It was related to the account, one account doesn't have rights on
connectors the others yes... Weird but it was that.

Regards;


<http://t.sidekickopen24.com/e1t/c/5/f18dQhb0S7lM8dDMPbW2n0x6l2B9nMJN7t5X-FdSD1CN4XyTvPS9PXKM1B0c-DNmkq103?t=https%3A%2F%2Fwww.linkedin.com%2Fcompany%2Ficescrum-technologies%2F&si=7000000000191787&pi=661ba681-68ca-40ce-a203-c086ab46a21a>

<http://t.sidekickopen24.com/e1t/c/5/f18dQhb0S7lM8dDMPbW2n0x6l2B9nMJN7t5X-FdSD1CN4XyTvPS9PXKM1B0c-DNmkq103?t=https%3A%2F%2Fwww.facebook.com%2Ficescrum&si=7000000000191787&pi=661ba681-68ca-40ce-a203-c086ab46a21a>

<http://t.sidekickopen24.com/e1t/c/5/f18dQhb0S7lM8dDMPbW2n0x6l2B9nMJN7t5X-FdSD1CN4XyTvPS9PXKM1B0c-DNmkq103?t=https%3A%2F%2Ftwitter.com%2Ficescrum&si=7000000000191787&pi=661ba681-68ca-40ce-a203-c086ab46a21a>
*Vincent
BARRIER*
CEO - Product Owner
+33 (0)9 52 91 10 10 <+33952911010>
+33 (0)6 49 88 39 78 <+33649883978>
www.icescrum.com - Get a demo!
<http://t.sidekickopen24.com/e1t/c/5/f18dQhb0S7lM8dDMPbW2n0x6l2B9nMJN7t5X-FdSD1CN4XyTvPS9PXKM1B0c-DNmkq103?t=https%3A%2F%2Fapp.hubspot.com%2Fmeetings%2Fvbarrier&si=7000000000191787&pi=661ba681-68ca-40ce-a203-c086ab46a21a>


Le sam. 20 juin 2020 à 08:12, Priyank Sharma <notifications@github.com> a
écrit :
