### ISSUE TITLE
Example of setting the size of the popup doesn't show setting the size of the popup

### ISSUE THREAD

**Issue by aosolis** [MicrosoftDocs/msteams-docs#5681]
<img width="555" alt="image" src="https://user-images.githubusercontent.com/767208/162033862-35fe2f7a-c836-402d-9387-923e12325c2f.png">

the snippet shown doesn't set width and height properties

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 503e124f-2b80-d6ae-581a-ca77f0a1999f
* Version Independent ID: 66d2bd8a-536b-1a45-f71c-eb2a0199de46
* Content: [Add authentication to your messaging extension - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/add-authentication)
* Content Source: [msteams-platform/messaging-extensions/how-to/add-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/messaging-extensions/how-to/add-authentication.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **anclear**

**Comment by Meghana-MSFT** [comment]
Thank you for the feedback. We will check it and take necessary actions.

**Comment by Meghana-MSFT** [comment]
@surbhigupta12 - Please replace `Value = $"{_siteUrl}/searchSettings.html?settings={escapedSettings}"` with `Value = $"{_siteUrl}/searchSettings.html?settings={escapedSettings}&height=600&width=600"` in the Note mentioned above this section https://docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/add-authentication#start-the-sign-in-flow.

![image](https://user-images.githubusercontent.com/81138249/164943184-8950cdb8-9f21-4620-b093-149092ed60de.png)
