### ISSUE TITLE
Document auth in link unfurling

### ISSUE THREAD

**Issue by aosolis** [MicrosoftDocs/msteams-docs#5682]
Please add documentation on how link unfurlers can add an authentication/authorization step.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59bbff2e-4b80-f980-2ade-7c7a7950801e
* Version Independent ID: e837e1fd-ec0c-2d6f-b0db-b76cb2d268a4
* Content: [Link unfurling - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?msclkid=8e1dcfc2b5ce11eca86c2673a2669244&tabs=dotnet)
* Content Source: [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/messaging-extensions/how-to/link-unfurling.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **anclear**

**Comment by sayali-MSFT** [comment]
@aosolis - We are looking into this I will get back to you soon.

**Comment by sayali-MSFT** [comment]
@aosolis -   Could you please confirm shall we add as note for authentication steps like below? Or need to add separate steps for this?
If authentication added through Azure AD, [Unfurl links in Teams using bot - Teams | Microsoft Docs](https://docs.microsoft.com/en-us/microsoftteams/platform/sbs-botbuilder-linkunfurling?tabs=vs&tutorial-step=4)

**Comment by sayali-MSFT** [comment]
@surbhigupta12 -Could you please help us to update the document?
Add it as note-
If authentication added through Azure AD, [Unfurl links in Teams using bot - Teams | Microsoft Docs](https://docs.microsoft.com/en-us/microsoftteams/platform/sbs-botbuilder-linkunfurling?tabs=vs&tutorial-step=4)

Document-https://docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?msclkid=8e1dcfc2b5ce11eca86c2673a2669244&tabs=dotnet#add-link-unfurling-manually
