### ISSUE TITLE
provide the format of the webhook URL

### ISSUE THREAD

**Issue by Michal-Ziemba** [MicrosoftDocs/msteams-docs#5688]
Please provide the format of the created webhook for better understanding. 

The format of the webhook in MS Teams is 
https://{tenant_domain}.webhook.office.com/webhookb2/{groupId}@{tenantId}/IncomingWebhook/{connectorId}/{webHookId}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90ff2a84-a8bc-9259-d37d-622b102df75b
* Version Independent ID: e3b53e27-2946-189c-623b-9df704ea8f12
* Content: [Create an Incoming Webhook - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-incoming-webhook)
* Content Source: [msteams-platform/webhooks-and-connectors/how-to/add-incoming-webhook.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/webhooks-and-connectors/how-to/add-incoming-webhook.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Meghana-MSFT** [comment]
Could you please elaborate a little on your issue?

**Comment by v-chetsh** [comment]
@Michal-Ziemba - Do you want us to update the contents?
Can you please elaborate more on your ask?
