### ISSUE TITLE
Deep link for Meetings Attendees not working.

### ISSUE THREAD

**Issue by hehe13** [MicrosoftDocs/msteams-docs#5691]
Deep link for Meetings Attendees not working.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45541337-ecd7-5cf6-cbe4-3f0d2f39aa79
* Version Independent ID: 6b4203f0-2844-06c9-eaa3-9cc03e6f76c0
* Content: [Create deep links - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links)
* Content Source: [msteams-platform/concepts/build-and-test/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/build-and-test/deep-links.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by hehe13** [comment]
Hello,

This link suppose to add joe as attendee but it doesn't:

***@***.******@***.***

***@***.******@***.***

Regards,



AJ

e: ***@***.***

p: +63 998 595 5820
________________________________

**Comment by sayali-MSFT** [comment]
@hehe13 -We are tested this from our end it's working fine for us.Could you please check it once with the below deeplink.modify attendees and dateTime as per requirment.
Microsoft Teams Version 1.5.00.9463 (64-bit)
Deeplink:-
`https://teams.microsoft.com/l/meeting/new?subject=test subject&attendees=joe@contoso.com,bob@contoso.com&startTime=04/11/2022 11:45:00&endTime=04/11/2022 11:30:00&content=​​​​​​​test:content​​​​​​​​​​​​​​`

https://user-images.githubusercontent.com/93527375/162676516-9c057fdd-6eaf-4806-bd4c-d6e5ff2f9740.mp4

**Comment by hehe13** [comment]
Please see my recording. Using the link only keeps myself as the attendee and does not add joe and bob.

![new](https://user-images.githubusercontent.com/7450264/162744167-d823a0ef-3346-4f17-ad35-d2ab8f2165d1.gif)

**Comment by hehe13** [comment]
> 

Sorry, I don't follow. What do you mean add then in chat?

**Comment by hehe13** [comment]
I think I understand now, if the contact is not part of our company contact list it will not work?
