### ISSUE TITLE
Bot how to send important/urgent message to one person

### ISSUE THREAD

**Issue by ShalinShah84** [MicrosoftDocs/msteams-docs#5695]
Can we mark message as Urgent same as Team does under the Bot framework. Is it possible ?
![Urgent](https://user-images.githubusercontent.com/103025523/162429262-76563e62-4052-4e6d-8de7-1eb51cfdf0cb.png)

Using ActivityImportance.High does not mark the message as Urgent. Are there any other class which does Urgent notifications

**Comment by Prasad-MSFT** [comment]
@ShalinShah84 - We are checking if there is any other class to send urgent notification in Bot framework. We will inform you if we get any update. Thanks!

**Comment by ShalinShah84** [comment]
Hi Prasad,

It does not mark the message as Urgent and it only displays the text on the adaptive cards
![Importance](https://user-images.githubusercontent.com/103025523/162477898-cc9187c9-20b1-4c6e-ac09-fccb39301d31.png)

**Comment by ShalinShah84** [comment]
Hello @Prasad-MSFT, any update on this?

**Comment by Prasad-MSFT** [comment]
Hi @ShalinShah84 , we are checking with engineering team if there is any other class which does Urgent notifications. We will inform you once we get any update. Thanks!

**Comment by Prasad-MSFT** [comment]
Hi @ShalinShah84 - we got confirmation from engineering team saying currently we do not support sending important messages with bots. 
To achieve your requirements, we recommend you give your feedback in Teams [UserVoice](https://microsoftteams.uservoice.com/forums/555103-public/filters/new).
Microsoft will always focus on customer’s feedback and experience. Some new features would be added to the services based on customers' feedback in the future, and your good ideas will be very helpful for them to improve the service.
