### ISSUE TITLE
Functional Notif only bot

### ISSUE THREAD

**Issue by prkosh** [MicrosoftDocs/msteams-docs#5698]
[Enter feedback here]
Please add the detail that a good quality Notification Only bot notifies the user regularly on certain event completions, example workflow completions, alerts etc. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff84fba8-b412-4c4a-3259-ae161d3523fd
* Version Independent ID: dba5c88d-5bd4-b66c-921b-2670fe8cfa66
* Content: [Microsoft Teams store validation guidelines - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/teams-store-validation-guidelines#notification-only-bots)
* Content Source: [msteams-platform/concepts/deploy-and-publish/appsource/prepare/teams-store-validation-guidelines.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/deploy-and-publish/appsource/prepare/teams-store-validation-guidelines.md)
* Product: **msteams**
* GitHub Login: @heath-hamilton
* Microsoft Alias: **surbhigupta**

**Comment by sayali-MSFT** [comment]
@prkosh -We are looking into this I will get back to you soon.

**Comment by sayali-MSFT** [comment]
@surbhigupta12 -Could you please help us to update the document?
Add the below line in attached document in Notification only Bots section.

> a good quality Notification Only bot notifies the user regularly on certain event completions, example workflow completions, alerts etc.

Document-https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/teams-store-validation-guidelines#notification-only-bots
