### ISSUE TITLE
Failed to upload custom app: Error code: UnknownTeamsAppManifestExceptionType

### ISSUE THREAD

**Issue by kafka-yu** [MicrosoftDocs/msteams-docs#5702]
Failed to upload custom app, It returns below info:

<img width="597" alt="image" src="https://user-images.githubusercontent.com/3942409/162758518-bf194eca-647f-4999-85e6-1ed389155ad2.png">
<img width="746" alt="image" src="https://user-images.githubusercontent.com/3942409/162758548-cfc677ec-5d4d-4fb9-bd14-fdd4241a8e68.png">

Pls help check, it is blocking our MS Teams app testing process.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54780e5a-ca3a-5277-dc84-37f85d9ea1cb
* Version Independent ID: 5f89865b-a9fd-ada5-72d2-6375357bba8c
* Content: [Upload your custom app - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/apps-upload)
* Content Source: [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/deploy-and-publish/apps-upload.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **surbhigupta**

**Comment by Meghana-MSFT** [comment]
We are able to repro this issue. A bug has been raised for the same. We will keep you posted on the updates.

**Comment by corelema** [comment]
Thank you for reporting the issue. There was a recent rollout that introduced the issue and has now been rolled back. If you continue to see the issue, please share diagnostic information with us so we can drill into it

**Comment by kafka-yu** [comment]
thanks! @corelema @aelbialyTR
