### ISSUE TITLE
Desired translation of content not loaded on install page from "Upload custom app" way

### ISSUE THREAD

**Issue by kafka-yu** [MicrosoftDocs/msteams-docs#5703]
See as below screenshots, I've switched to zh-CN in the settings of MS Teams, and the zh-CN is enabled in Manifest. The page open from "Upload custom app" won't display "zh-CN (or other locales) content. Is it by design? Will it only load when the app is published to store?

<img width="856" alt="image" src="https://user-images.githubusercontent.com/3942409/162760006-7a406b70-38a4-49ec-8806-eee9f75ab570.png">

<img width="786" alt="image" src="https://user-images.githubusercontent.com/3942409/162760060-9ca12db3-03f6-49fc-8989-7e11929b0315.png">

**Comment by sayali-MSFT** [comment]
@kafka-yu -Could you please share your manifest json, So we can try it from our end?

**Comment by kafka-yu** [comment]
> @kafka-yu -Could you please share your manifest json, So we can try it from our end?

Hi Can I send it via email or other way?

**Comment by sayali-MSFT** [comment]
@kafka-yu -You can share here only. only hide details like appid.

**Comment by kafka-yu** [comment]
Archive.zip
[Archive.zip](https://github.com/MicrosoftDocs/msteams-docs/files/8478513/Archive.zip)
You may need to update <id>.

**Comment by sayali-MSFT** [comment]
@kafka-yu -We are tried it our end. You need to enter a short description of the app in zh-CN,
Enter the long description of the app in zh-CN.
https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/apps-localization#configure-localization

**Comment by kafka-yu** [comment]
hmmm, I added in `zh-CN.json`, I can see it is loaded in the "About" page of the app. Can you share the manifest you updated? @sayali-MSFT

**Comment by sayali-MSFT** [comment]
@kafka-yu -Here is manifest which I have tried. Could you please try it once?
[manifest.zip](https://github.com/MicrosoftDocs/msteams-docs/files/8503686/manifest.zip)

**Comment by kafka-yu** [comment]
thanks, I'll check it today

**Comment by kafka-yu** [comment]
> @kafka-yu -Here is manifest which I have tried. Could you please try it once? [manifest.zip](https://github.com/MicrosoftDocs/msteams-docs/files/8503686/manifest.zip)

I saw the changes you made. it seems like you directly put the zh-CN content in the manifest.json. While in the app, we can only have one manifest.json file, right? We cannot generate manifest files for all languages with their translated content.

**Comment by sayali-MSFT** [comment]
@kafka-yu - yes, but as per document to configure an additional language,
1.Enter the app name.
2.Enter a short description of the app in English.
3.Enter the long description of the app in English.
4.In the long description, enter: This app is available in French.
5.Upload the images of your app UI (in English).
https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/apps-localization#configure-localization

**This is Bydesign behaviour.**

**Comment by sayali-MSFT** [comment]
@kafka-yu - shall we close the issue if youe issue is resolved?

**Comment by kafka-yu** [comment]
> @kafka-yu - Yes, but as per document to configure an additional language, 1.Enter the app name. 2.Enter a short description of the app in English. 3.Enter the long description of the app in English. 4.In the long description, enter: This app is available in French. 5.Upload the images of your app UI (in English). https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/apps-localization#configure-localization
> 
> **This is Bydesign behaviour.**

Got it, so you mean the part about localization on the install page should be configured in the Partner Center right?

**Comment by sayali-MSFT** [comment]
@kafka-yu -Yes. The part about localization on the install page should be configured in the Partner Center right

**Comment by kafka-yu** [comment]
ok thx
