### ISSUE TITLE
Typo notifysuccsss vs notifysuccess

### ISSUE THREAD

**Issue by beauzeaux** [MicrosoftDocs/msteams-docs#5705]
Very nitpicky but ran across a [typo on line 112](https://github.com/MicrosoftDocs/msteams-docs/blob/1f5d1b27990b630ca297d5d232d8f49f56a5db17/msteams-platform/tabs/how-to/authentication/auth-oauth-provider.md?plain=1#L112). `notifysuccsss` should be `notifysuccess`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b608448b-3dd7-d5be-128c-da2859067140
* Version Independent ID: b608448b-3dd7-d5be-128c-da2859067140
* Content: [Use external OAuth providers - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-oauth-provider)
* Content Source: [msteams-platform/tabs/how-to/authentication/auth-oauth-provider.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/tabs/how-to/authentication/auth-oauth-provider.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Meghana-MSFT** [comment]
@surbhigupta12 - Can you please help in updating the below content in 6th Step in https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-oauth-provider.

Please change notifySuccsss() to notifySuccess().
