### ISSUE TITLE
So Confused - I thought Message Cards were Deprecated!

### ISSUE THREAD

**Issue by JimGorman17** [MicrosoftDocs/msteams-docs#5706]
Why does this documentation example show a message card if message cards are [deprecated](https://docs.microsoft.com/en-us/outlook/actionable-messages/message-card-reference)?

![image](https://user-images.githubusercontent.com/1767483/162841610-96a68a6e-5dfc-46de-b789-3051a60f0b38.png)

![image](https://user-images.githubusercontent.com/1767483/162841795-3c15d4e3-40b0-478f-8af1-ea0fb466d820.png)

![image](https://user-images.githubusercontent.com/1767483/162841522-dd2d9fcc-a8fe-4d0f-bb47-df099ac4ea91.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28316a67-22fa-8a05-1ae0-fbe1c5720ef9
* Version Independent ID: 8a250e46-2a30-af86-839d-9f83a8b48041
* Content: [Create and send messages - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-using?tabs=cURL)
* Content Source: [msteams-platform/webhooks-and-connectors/how-to/connectors-using.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/webhooks-and-connectors/how-to/connectors-using.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by sayali-MSFT** [comment]
@JimGorman17 -We are looking into this I will get back to you soon.

**Comment by JimGorman17** [comment]
> @JimGorman17 -Could you please elaborate your requirement?

![image](https://user-images.githubusercontent.com/1767483/163004011-06955596-7934-470f-b3a6-982b291b1d82.png)

Emphasis: I don't want to use a deprecated format. Should we use Message Cards? Or should we use **only** Adaptive Cards?

**Comment by sayali-MSFT** [comment]
@JimGorman17 -As Per Document,
The Adaptive Card format is required to support Outlook on iOS and Android. However, if you are **sending actionable messages via an Office connector, or to a Microsoft Teams connector**, you must continue to use the message card format.

You can create actionable messages and send it through Incoming Webhook or Office 365 Connector.
If you use Office 365 Connector that time you need to use the message card format.
