### ISSUE TITLE
Illogical Description

### ISSUE THREAD

**Issue by surbhigupta12** [MicrosoftDocs/msteams-docs#5707]
[Enter feedback here]

In the opening, it goes as follows: When building your conversational bots for Microsoft Teams, you can work with conversation events. Teams sends notifications to your bot for conversation events that happen in scopes where your bot is active. You can capture these events in your code and take the following actions:

Trigger a welcome message when your bot is added to a team.
Trigger a welcome message when a new team member is added or removed.
Trigger a notification when a channel is created, renamed, or deleted.
When a bot message is liked by a user.
It says “You can capture these events in your code and take the following actions:” and the first three sentences make sense, which explain the actions to be done to users.

But the last one just refers to the details of an event and lacks the explanation on what action is done, so the sentence itself is not appropriate.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a6d00a4-dd28-33c4-002e-2e8e7c653ce2
* Version Independent ID: 0856927a-25f4-b1e0-5f1b-d55dc61796f3
* Content: [Conversation events - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/subscribe-to-conversation-events?tabs=dotnet)
* Content Source: [msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md)
* Product: **msteams**
* GitHub Login: @WashingtonKayaker
* Microsoft Alias: **anclear**

**Comment by Prasad-MSFT** [comment]
@surbhigupta12 -Please let us know once contents are updated. Thanks!
