### ISSUE TITLE
How can I get the data posted to my webhookurl?

### ISSUE THREAD

**Issue by XimenaWang** [MicrosoftDocs/msteams-docs#571]
This is my connector,I want to edit the message, such as adding a button, how can I get this data posted to my webhookurl?
![image](https://user-images.githubusercontent.com/30890958/56268835-2babe000-60a7-11e9-82f1-cda08154fc48.png)

**Comment by Wajeed-msft** [comment]
@XimenaWang - You cannot edit the message which is already send by Connector. Only way to [refresh a card](https://docs.microsoft.com/en-us/outlook/actionable-messages/message-card-reference#refresh-cards) when user clicks on actionable button. ([Sample code](https://github.com/OfficeDev/microsoft-teams-sample-connector-csharp/blob/master/TeamsToDoAppConnector/Controllers/TaskController.cs#L58))

Please have a look at JSON the [Connector card sample](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/connectors/connectors-using#example-connector-message) if you want to implement actions on your card. For this you need to enable actions for your Connector from  [Connector portal](https://outlook.office.com/connectors/publish).
![image](https://user-images.githubusercontent.com/31851992/56270199-3603c380-6113-11e9-87c3-9108335ffc5a.png)


Please let us know if you are looking for something else.

**Comment by XimenaWang** [comment]
@Wajeed-msft - Thanks, yes, this card above has been sent by Connector. I may not express what I want.

Current logic:   configured my webhookUrl in **ICM**, so if there is new incident, **ICM** will post the new one to  my webhookUrl. and then Connector will send the new incident in my channel. 

 I want to insert one step before it was sent to my channel : **caught the new incident details which posted to my webhook**, and make some changes , create one new card to channel.

I just want to rewrite the message before it sent to channel, can this be realized? Looking forward to your reply~

**Comment by XimenaWang** [comment]
Thanks for your advice, it works!
