### ISSUE TITLE
Creating a New Team but not being able to leave the loading screen

### ISSUE THREAD

**Issue by BigCatTony** [MicrosoftDocs/msteams-docs#572]
When creating a new team, I get stuck in a loop.
It says "Feel free to close this window and go do other things. We'll let you know when it's ready."
I press "Close window" and then it asks "Are you sure you want to discard this team?"
If I select NO it continues to loop.
![teams bug 2](https://user-images.githubusercontent.com/49724375/56297023-90922500-60fd-11e9-84b5-9216e35afc72.png)
![Teams bug 1](https://user-images.githubusercontent.com/49724375/56297024-90922500-60fd-11e9-897f-380e85f4f3d3.png)

**Comment by Wajeed-msft** [comment]
Are you still facing this issue? Could you please share the logs (%appdata%\Microsoft\Teams\logs.txt)?

**Comment by BigCatTony** [comment]
I am on a MAC. No idea how to find the logs.

**Comment by BigCatTony** [comment]
Yes I am still having the issue. 
1. Create New team
2. Select Create From
3. Select a Team to Copy
4. Rename and select all checkboxes of things to copy
5. Loading circle appears.
6. Message appears "Feel free to close and we will let you know when it is finished."
7. Click close
8. Get stuck in loop.

Logs attached


[MSTeams Diagnostics Log 4_30_2019__10_08_10_AM_calling.txt](https://github.com/MicrosoftDocs/msteams-docs/files/3131594/MSTeams.Diagnostics.Log.4_30_2019__10_08_10_AM_calling.txt)
[MSTeams Diagnostics Log 4_30_2019__10_08_10_AM_sync.txt](https://github.com/MicrosoftDocs/msteams-docs/files/3131595/MSTeams.Diagnostics.Log.4_30_2019__10_08_10_AM_sync.txt)
[MSTeams Diagnostics Log 4_30_2019__10_08_10_AM.txt](https://github.com/MicrosoftDocs/msteams-docs/files/3131596/MSTeams.Diagnostics.Log.4_30_2019__10_08_10_AM.txt)

**Comment by Abhijit-MSFT** [comment]
I tried it couple of time with the steps mentioned in your comments. It looks to be working fine for me. moreover there is nothing much in the provided logs.

**Comment by Gousia-MSFT** [comment]
@BigCatTony We are trying to investigate this but unfortunately cannot find anything useful from the logs. Could you please help us with the following :
1. Login to teams on browser and try the same steps there and see the behavior.
2. Do you have any other teams created or this is the first time you are trying to create a team?
3. Send proper logs captured during the repro along with a Fiddler trace.

**Comment by Wajeed-msft** [comment]
Please re-open with requested details, if you are still facing this issue.
