### ISSUE TITLE
Newest icon is not shown on some parts of the UI

### ISSUE THREAD

**Issue by freedomofkeima** [MicrosoftDocs/msteams-docs#573]
Hi again,

Currently I'm trying to upload a bot icon, however, it seems my icon is not shown in some parts of the UI.

<img width="1385" alt="Screen Shot 2019-04-18 at 17 21 20" src="https://user-images.githubusercontent.com/2115470/56348504-88bba900-6201-11e9-8ba2-c62ceb3dbe35.png">

---

<img width="1043" alt="Screen Shot 2019-04-18 at 17 21 49" src="https://user-images.githubusercontent.com/2115470/56348506-8a856c80-6201-11e9-9c2a-98155c0dec71.png">

---

<img width="372" alt="Screen Shot 2019-04-18 at 17 21 58" src="https://user-images.githubusercontent.com/2115470/56348512-8bb69980-6201-11e9-991b-0ee7f5370114.png">

---

Did I miss something here?

Thanks.

**Comment by pschaeflein** [comment]
You need to upload your custom icon in the Azure Bot Registration page in addition to the Teams manifest.

**Comment by freedomofkeima** [comment]
Hi,

Thanks for the reply. After changing it on "Azure Bot Registration", how long will it take until the changes are applied? I've waited for 15 minutes but it doesn't seem anything is updated on Teams side.

<img width="1228" alt="Screen Shot 2019-04-19 at 11 33 15" src="https://user-images.githubusercontent.com/2115470/56402114-0251a680-6297-11e9-8665-f83f367e30f6.png">

Thanks.

**Comment by Wajeed-msft** [comment]
Bot information is cached at user level. Could you please sign out and sign in to see the updated icon for existing user? New user will always see latest icon.

**Comment by freedomofkeima** [comment]
Oh, I see. Now it's fixed, thanks for pointing it out.
