### ISSUE TITLE
Please document response of APIs, and add links to the corresponding SDK reference documentation

### ISSUE THREAD

**Issue by aosolis** [MicrosoftDocs/msteams-docs#5730]
Please add links to the corresponding SDK reference docs for each of the APIs, request and response types.

For example, the docs for Get meeting details looks like this:
<img width="548" alt="image" src="https://user-images.githubusercontent.com/767208/163031699-c872b31a-c766-4427-adfa-93c4835e11e8.png">
It's difficult to know where GetMeetingInfo is defined, and what the MeetingInfo object looks like.

The shape of the response is described (through an example) in the JSON tab, but there's nothing that points you to that space:
<img width="358" alt="image" src="https://user-images.githubusercontent.com/767208/163032267-45f4c640-2f98-47fe-b498-c562a93eb821.png">

The semantics of the response is not documented. For example:
- what are the values of type
- how does scheduled star/end time work for recurring meetings?
- which Graph APIs can use the value returned by msGraphResourceId

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 805dc242-7b5a-cc81-ee0e-6acf0078a653
* Version Independent ID: 11c0e023-2514-9639-6052-2cbbbef50663
* Content: [Meeting apps API references - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/api-references?tabs=dotnet)
* Content Source: [msteams-platform/apps-in-teams-meetings/API-references.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/apps-in-teams-meetings/API-references.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by sayali-MSFT** [comment]
@aosolis -We are looking into this I will get back to you soon.

**Comment by Prasad-MSFT** [comment]
<html>
<body>


Method | Description | Source
-- | -- | --
Get user context | Get contextual information to display relevant content in a Teams tab. | [MSTC SDK](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/access-teams-context#get-context-by-using-the-microsoft-teams-javascript-library)
Share app content to stage | Share specific parts of the app to meeting stage from the app side panel in a meeting. | MSTC SDK
Get app content stage sharing state | Fetch information about app's sharing state on the meeting stage. | [MSTC SDK](https://docs.microsoft.com/en-us/javascript/api/@microsoft/teams-js/microsoftteams.meeting.iappcontentstagesharingstate?view=msteams-client-js-latest)
Get app content stage sharing capabilities | Fetch the app's capabilities for sharing to the meeting stage. | [MSTC SDK](https://docs.microsoft.com/en-us/javascript/api/@microsoft/teams-js/microsoftteams.meeting.iappcontentstagesharingcapabilities?view=msteams-client-js-latest)



@aosolis - Could you please confirm if it needs to be updated in above way?

**Comment by aosolis** [comment]
@Prasad-MSFT I described what needs to be done in the issue. Please assign this to the docs team.

**Comment by v-chetsh** [comment]
@surbhigupta12 - Please help us here to update the contents.
