### ISSUE TITLE
Action handlers on the Adaptive Card

### ISSUE THREAD

**Issue by shabbir-dhangot** [MicrosoftDocs/msteams-docs#5749]
### Problem Statement

We are building a react app which sends Adaptive Card to User/Channel with certain actions as attachment as shown below. 

    const adaptativeCardContent = {
        "type": "AdaptiveCard",
        "body": [
            {
                "type": "TextBlock",
                "size": "Medium",
                "weight": "Bolder",
                "text": "Publish Adaptive Card Schema"
            },
            {
                "type": "TextBlock",
                "text": "Now that we have defined the main rules and features of the format, we need to produce a schema and publish it to GitHub. The schema will be the starting point of our reference documentation.",
                "wrap": true
            }
        ],
        "actions": [
            {
                "type": "Action.OpenUrl",
                "title": "View",
                "url": "${viewUrl}"
            },
            {
                "type": "Action.Submit",
                "title": "Open in Tab"
            }
        ],
        "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
        "version": "1.3"
    }

    return {
        subject,
        attachments: [{
            id,
            contentType: 'application/vnd.microsoft.card.adaptive',
            contentUrl: null,
            content: JSON.stringify(card),
            name: null,
            thumbnailUrl: null
        }],
        body: { contentType: 'html', content, }
    };

It is sending card to user and we are able to see below card rendered at user's end. 

<img width="520" alt="Screenshot 2022-04-19 at 10 50 10 AM" src="https://user-images.githubusercontent.com/8267282/163925341-81e633df-2b79-4ed8-ae1f-201e0c28dcce.png">

In adaptive card we are able to see Action.OpenUrl which is opening url in browser. But we are not sure how to detect if user has clicked on the submit button. 

We read documents but did not find any related article/example for same. How can we detect when user is clicking on the Action.Submit button. Also is there any alternate way where we (as a React App) can take interpret a submit action performed by user in adaptive card?

**Comment by sayali-MSFT** [comment]
@shabbir-dhangot -We are looking into this I will get back to you soon.

**Comment by sayali-MSFT** [comment]
@shabbir-dhangot -Please have a look at this sample-https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/javascript_nodejs/54.teams-task-module
hope it's helpful for you.

**Comment by sayali-MSFT** [comment]
@shabbir-dhangot - Could you please confirm if your issue has resolved with above suggestion or still looking for any help?

**Comment by shabbir-dhangot** [comment]
Hi Sayali, 

We are looking for approach which doesn't involve bot. For example, we are sending message in personal chat or group. Now we are sending an adaptive card with above attachment, how can we control submit click that done by that user?

Meanwhile I am checking what you suggested,

**Comment by sayali-MSFT** [comment]
@shabbir-dhangot - If you want to send message or card in 1:1 chat or teams channel then you can refer the following sample:-
https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/bot-receive-channel-messages-withRSC/csharp

For group chat it is not possible to do without involve bot send card or message.

**Comment by shabbir-dhangot** [comment]
@sayali-MSFT 

I think we misrouted from actual problem. We are not looking for sending message 1:1 or in channel, that is we are already done. We are able to send adaptive card to user/channel. 

Main problem statement is that we have Open in Tab button where we want to add click listener and perform some activity there  itself. 

For instance, if user clicks on the button we want to add another tab in user and open website in it. 

I hope it's clear now.

**Comment by sayali-MSFT** [comment]
@shabbir-dhangot -On adaptive card buttons we can't handle custom events as only limited actions are supported by teams sdk.

**Comment by shabbir-dhangot** [comment]
@sayali-MSFT can you please share supported actions document link so we can see what we can utilize at our end.

**Comment by sayali-MSFT** [comment]
@shabbir-dhangot -Please have a look at this docs-https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-actions?tabs=json

**Comment by sayali-MSFT** [comment]
@shabbir-dhangot - Could you please confirm if your issue has resolved with above suggestion or still looking for any help?

**Comment by LavanyaPrasad** [comment]
We have built an MS teams app using Tab capability. We have the possibility to share an adaptive card as a chat message to a person or channel. 
Now if the adaptive card has an Action. Submit, we are unable to interpret the click action, the app is built using Tab Capability and not on Bot framework.

Could you please suggest to us how an existing MS teams app was built using Tab capability, we will be able to interpret the click action on the adaptive card(eg Action.Submit) to perform further steps.

**Comment by sayali-MSFT** [comment]
Here is sample tab with adaptive card. Please have look into this-https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/tab-adaptive-cards/nodejs

**Comment by LavanyaPrasad** [comment]
@sayali-MSFT  I will have a look in the upcoming days.
The example describes showing an adaptive card in a Tab.

I am rather looking for, sending an adaptive card to another person as a chat message, with Actions. However, as the app is built using Team's tab capability(tab module) we don't see the possibility to interpret the click on these Actions.

**Comment by sayali-MSFT** [comment]
@LavanyaPrasad - We will check it and let you know.
