### ISSUE TITLE
Some questions I have on the "Generate a deep link to your tab" docs

### ISSUE THREAD

**Issue by eoinobrien** [MicrosoftDocs/msteams-docs#5768]
Hi,

I've been working on deep links recently and I have been finding the docs around it confusing.

* `webUrl` is called out as a parameter in a number of the examples (e.g.: https://teams.microsoft.com/l/entity/fe4a8eba-2a31-4737-8e33-e5fae6fee194/tasklist123?webUrl=https://tasklist.example.com/123/456&label=Task 456&context={"subEntityId": "task456"}) but it is not explained what it means. 
  * I would guess it's equivalent to `entityWebUrl` which is documented but it's not clear. 
  * If I have both what happens? 
  * Is one of `webUrl` or `entityWebUrl` deprecated?
* Similarly for `label` and `entityLabel`
* Also for labels
  * What do they do?
  * Where is the label shown?
  * Why would I provide a label? Is there a benefit?
* How does deep linking to tabs entity/subentity in sideloaded apps work?
  * I tested the sample tab-deeplink app (https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/tab-deeplink/csharp) and after some work to get it going (https://github.com/OfficeDev/Microsoft-Teams-Samples/310) it was set up.
  * However, the card returned by the bot is unable to deep link to the tab or subentity
  * Video here https://user-images.githubusercontent.com/6508687/164506527-4939bfdb-5e3a-48ec-8055-2fa64d89342b.mp4
  * The app uses the MicrosoftAppId as the appId.
  * Is there a specific Id that I should use instead for sideloaded apps?
  * This might be related to #3193, but that issue was marked as stale.

Can you help answer the above/improve the documentation, so these are clearer for everyone else.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45541337-ecd7-5cf6-cbe4-3f0d2f39aa79
* Version Independent ID: 6b4203f0-2844-06c9-eaa3-9cc03e6f76c0
* Content: [Create deep links - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links#feedback)
* Content Source: [msteams-platform/concepts/build-and-test/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/build-and-test/deep-links.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Meghana-MSFT** [comment]
We are looking into this, we will get back to you.

**Comment by Meghana-MSFT** [comment]
Weburl and entityWebUrl are same, and it is an optional field. The url given for this field will be used if the client doesn't support rendering the tab. 

A label for the item in your tab, to use when displaying the deep link. Below are the label
![MicrosoftTeams-image (25)](https://user-images.githubusercontent.com/81138249/165583521-27892cf1-541a-42e4-996f-455bb3660915.png)

Could you please use MicrosoftAppId as the manifest id and try again, meanwhile team is also looking into this issue.

**Comment by eoinobrien** [comment]
Hi @Meghana-MSFT,

Thanks for replying.

Is it possible to improve the documentation so that similarities between webUrl and entityWebUrl are called out. At the moment, we explain what an entityWebUrl is in query parameters table, but then use webUrl in the examples. is it possible to be consistent, or at least explain that they are identical.

Ah the labels makes sense, can we call out this documentation also. Especially, that the label is only used if you are using `executeDeepLink` to deeplink from a tab. And that if you are using a deep link in an Adaptive Card or similar, it is not used. Or am I wrong and is it used in Adaptive Cards too? Can we also explain what happens if the label is not provided but `executeDeepLink` is used?

**Comment by Meghana-MSFT** [comment]
We will check this internally and get back to you.
