### ISSUE TITLE
"Teams session" definition is missing

### ISSUE THREAD

**Issue by sushruth** [MicrosoftDocs/msteams-docs#5769]
Please explain what time interval exactly is considered "**Teams session"** when explaining `appSessionId` and `sessionId` properties in the MS Teams context object.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8dfa1a29-bcf4-0cc5-ae3a-b185a00fd7bc
* Version Independent ID: c68181e1-151b-fc78-2671-fe9b397b702e
* Content: [Get context for your tab - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/access-teams-context)
* Content Source: [msteams-platform/tabs/how-to/access-teams-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/tabs/how-to/access-teams-context.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by sayali-MSFT** [comment]
@sushruth - We are looking into this I will get back to you soon.

**Comment by sayali-MSFT** [comment]
@sushruth -The Teams session tracks the lifetime of the Teams client. If the customer restarts the Teams Desktop Client or reloads the Teams Web Client we generate a new sessionId.
 
The App session tracks the lifetime of the platform app. If the customer navigates away from the app and comes back or refreshes it via the reload button we generate a new appSessionId.

**Comment by sayali-MSFT** [comment]
@sushruth - Could you please confirm if your issue has resolved with above suggestion or still looking for any help?

**Comment by sushruth** [comment]
@sayali-MSFT - yes it does. Thank you. Please find a way to add this to the documentation. Thanks.

**Comment by sayali-MSFT** [comment]
@surbhigupta12 -Could you please help us to update the document?
Please add as Note -
"The Teams session tracks the lifetime of the Teams client. If the customer restarts the Teams Desktop Client or reloads the Teams Web Client we generate a new sessionId.
The App session tracks the lifetime of the platform app. If the customer navigates away from the app and comes back or refreshes it via the reload button we generate a new appSessionId."
Document-https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/access-teams-context#get-context-by-using-the-microsoft-teams-javascript-library
