### ISSUE TITLE
Is this available in the bot builder SDK?

### ISSUE THREAD

**Issue by LongBeachHXC** [MicrosoftDocs/msteams-docs#577]
I don't seen any reference to this in the botbuilder SDK and am wondering if this functionality is available there? Does the MS Teams SDK need to be imported to be able to use this feature?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5307fe5c-a6f0-59e2-d125-69051ab58595
* Version Independent ID: ca3f41d9-1c2a-6cde-b780-61fec8f0fcb6
* Content: [Sending and receiving files from a bot - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/bots/bots-files?view=msteams-client-js-latest#using-the-teams-bot-apis)
* Content Source: [msteams-platform/concepts/bots/bots-files.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/bots/bots-files.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by clearab** [comment]
Hi - The code from the C# sample requires the Teams Bot Builder SDKs, which extend the core Bot Builder SDKs with Teams-specific functionality. You can find the package here: https://www.nuget.org/packages/Microsoft.Bot.Connector.Teams

**Comment by LongBeachHXC** [comment]
I just read (https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/bots/bots-create?view=msteams-client-js-latest) that msteams SDK isn't available for integration with botbuilder SDK v4 and the project is dependent on v4. Thanks for your help.

**Comment by clearab** [comment]
The v4 version of the Teams Bot Builder SDK is currently in beta. You can find it here: https://www.nuget.org/packages/Microsoft.Bot.Builder.Teams
