### ISSUE TITLE
Third party SSO login doesn't close popup

### ISSUE THREAD

**Issue by wheelie33** [MicrosoftDocs/msteams-docs#5778]
We're building a task module app that calls a 3rd party SSO url.  we call microsoftteams.authentication.authenticate and pass the client's SSO url (which is in the valid urls in the manifest).  that correctly pops up a teams window and we can login.

the clients SSO server has a hardcoded URL that it replies back to which is the same app that popped up the window to begin with (react app).

We see the token in code but calling microsoftTeams.authentication.notifysuccess doesn't close the auth window nor return the token back to the original page.

We're using teams desktop.

**Comment by v-chetsh** [comment]
@wheelie33 - Can you please share the code snippet and steps, so that we can investigate it from our end?

**Comment by sayali-MSFT** [comment]
@wheelie33 -Are you facing same issue like in this thread?
https://github.com/OfficeDev/microsoft-teams-library-js/issues/629

**Comment by wheelie33** [comment]
We solved the problem.  

The documentation is just not keeping up with the SDK changes and we missed that you should originate the authentication popup with a page owned by the app THEN redirect out to the SSO URL.  THAT's what made the change work.  Thanks for looking.
