### ISSUE TITLE
Deep link to a custom team tab from the personal app not working on iOS

### ISSUE THREAD

**Issue by theguiro** [MicrosoftDocs/msteams-docs#5785]
We have two Angular applications where one is the personal app in the and the second one is team tab app. We ran on the issue of deep links to a team tab are not working when linked from the personal app in iOS devices. Deep links are working on Windows, macOS, Android phones and tablets, but not on the iOS devices. For this purpose we are using microsoftTeams.executeDeepLink() method for opening deep link. Format of the link is:
'https://teams.microsoft.com/l/entity/{teamTabAppId}/{teamTabEntityId}?webUrl=' + encodedWebUrl + '&context=' + encodedContext + '&groupId=' + groupId'
When trying to execute this link with pure JavaScript (window.open()) link is opened successfully.

Callback onComplete method of the microsoftTeams.executeDeepLink() is returning state true with no reason of not properly executing the deep link.

Previously there were some issues reported regarding the deep links not working on iOS not sure if this introduced again or something is missing in our implementation.

Additional info:
iOS version - 15.4.1
MS Teams app version - 4.6.1 Build 4.6.77.2022063103/0407 (general)
@microsoft/teams-js version - 1.11.0

**NOTE**: This exact issue was raised and resolved in the past (view https://github.com/MicrosoftDocs/msteams-docs/issues/5066). We have tested on a device with MS Teams app version 4.1.0 and Deep-links are working properly.

**Comment by Prasad-MSFT** [comment]
We are checking the issue. We will get back to you shortly

**Comment by Prasad-MSFT** [comment]
@theguiro - We used below format to navigate to channel tab from personal tab app and it worked fine in Teams Desktop client as well as in iOS devices.

```
microsoftTeams.getContext(function (context) {
                microsoftTeams.executeDeepLink("https://teams.microsoft.com/l/entity/b6fa50ae-6a60-4c23-b3fe-b8f2feb77282/_djb2_msteams_prefix_4215212359?context=%7B%22subEntityId%22%3Anull%2C%22channelId%22%3A%2219%3A787993ede7dd48718a049acd303b05a7%40thread.tacv2%22%7D&groupId=fa9a3f1e-67fa-44ae-ad92-bc57331cecb9&tenantId=36a708ef-700d-4d60-9de0-0a5f7b7693df");
            })
```
MS Teams iOS Version:
![image](https://user-images.githubusercontent.com/62237649/165143506-02fa293a-5195-41fc-90fc-3871f3ad1bee.png)

**Comment by theguiro** [comment]
Hi @Prasad-MSFT , 
Thank you for your response. I can see your tests were executed on MS Teams app version 4.5.1. Unfortunately we don't have a device with that particular version. We have tested in versions 4.1.0 and 4.0.0 and in those Deep links work correctly in iOS. 

It is the latest version (4.6.1) that we are having the issue:

![ios-screen-4 6 1-lg](https://user-images.githubusercontent.com/1269824/165270011-d599a153-c3eb-4b2e-baab-2d73c5105880.jpeg)

**Comment by Prasad-MSFT** [comment]
Ok, we will try to update the MS Teams version and check again

**Comment by Prasad-MSFT** [comment]
@theguiro - We are also repro the issue when updated MS Teams version to 4.6.1
![image](https://user-images.githubusercontent.com/62237649/165520040-b2f2d6a7-f18b-4212-865c-567ec9318053.png)
We have re-opened the bug and informed engineering team about the re-occurrence. We will inform you once we get any update. Thanks!

**Comment by theguiro** [comment]
Thank you @Prasad-MSFT

**Comment by plamber** [comment]
Hello @Prasad-MSFT,
we have a similar issue when sending a Teams notification to the activity feed (iOS Teams Version 4.7). It works without problems for all other platforms.

/users/0bcdb476-5d30-4b53-b79c-c332ea122a51/teamwork/sendActivityNotification
```
{
    "topic": {
        "source": "text",
        "value": " My Text",
        "webUrl": "https://teams.microsoft.com/l/entity/{{teamsAppId}}/entity.id?context=%7B%22subEntityId%22%3A%20%22/groups/5e80f7dc-8fb1-45c2-a12f-8f391a081de9%22%7D"
    },
    "activityType": "myactivityType",
    "previewText": {
        "content": "New Task Created"
    },
    "templateParameters": [
        {
            "name": "group",
            "value": "Patrick Lamber"
        }
    ]
}
```

It used to work a couple of months ago when we submitted our Teams app in the store. I can't tell you for sure when it stopped working.

I can share with you the exact calls and Teams manifest if it helps.

Thank you

**Comment by theguiro** [comment]
I can confirm the issue is still happening on MS Teams app version 4.7.0

**Comment by Prasad-MSFT** [comment]
@theguiro - Engineering team is looking into the issue. We will inform you once we get further update. thanks!

**Comment by plamber** [comment]
Hi @Prasad-MSFT,
By chance, do you have an update on this? We are experiencing the issue on the latest version, 4.10.1.

Thank you for your feedback,
Patrick

**Comment by Prasad-MSFT** [comment]
@plamber - We are checking with engineering team regarding the status. We will update you accordingly

**Comment by xu1718191411** [comment]
> Hello @Prasad-MSFT, we have a similar issue when sending a Teams notification to the activity feed (iOS Teams Version 4.7). It works without problems for all other platforms.
> 
> /users/0bcdb476-5d30-4b53-b79c-c332ea122a51/teamwork/sendActivityNotification
> 
> ```
> {
>     "topic": {
>         "source": "text",
>         "value": " My Text",
>         "webUrl": "https://teams.microsoft.com/l/entity/{{teamsAppId}}/entity.id?context=%7B%22subEntityId%22%3A%20%22/groups/5e80f7dc-8fb1-45c2-a12f-8f391a081de9%22%7D"
>     },
>     "activityType": "myactivityType",
>     "previewText": {
>         "content": "New Task Created"
>     },
>     "templateParameters": [
>         {
>             "name": "group",
>             "value": "Patrick Lamber"
>         }
>     ]
> }
> ```
> 
> It used to work a couple of months ago when we submitted our Teams app in the store. I can't tell you for sure when it stopped working.
> 
> I can share with you the exact calls and Teams manifest if it helps.
> 
> Thank you

We have the same problem, IOS Teams can not open feed notification currently

**Comment by Prasad-MSFT** [comment]
@deltamod3 , @xu1718191411 -We are checking with engineering team regarding the status. We will update you accordingly. Thanks!

**Comment by Prasad-MSFT** [comment]
@deltamod3, @xu1718191411 - We got update from engineering team that the fix has been released publicly.
Please do verify and update.

**Comment by Prasad-MSFT** [comment]
We are closing this issue for now. Please feel free to reopen if required. 
Thanks!
