### ISSUE TITLE
"groupId" property not available in the current context in a private channel tab

### ISSUE THREAD

**Issue by jouhami** [MicrosoftDocs/msteams-docs#5798]
When installing a configurable tab in a private channel the current context does not contain the `gourpId` property.

Here is how I get the frame context : 

```
 microsoftTeams.getContext(context => {
    const { groupId } = context;
    ...
});
```

I'm getting exactly the same context properties for standard and private channels except the `groupId` which is missing in private channels context.

The [required permission is declared in the manifest](https://docs.microsoft.com/en-us/javascript/api/@microsoft/teams-js/microsoftteams.context?view=msteams-client-js-latest&preserve-view=true#@microsoft-teams-js-microsoftteams-context-groupid) :   `"permissions": ["identity"]`

Teams SDK version :  @microsoft/teams-js : 1.11.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8dfa1a29-bcf4-0cc5-ae3a-b185a00fd7bc
* Version Independent ID: c68181e1-151b-fc78-2671-fe9b397b702e
* Content: [Get context for your tab - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/access-teams-context)
* Content Source: [msteams-platform/tabs/how-to/access-teams-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/tabs/how-to/access-teams-context.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Meghana-MSFT** [comment]
We are checking this issue, we will update you.

**Comment by Meghana-MSFT** [comment]
@jouhami - As per the [Retrieve context in private channels](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/access-teams-context#retrieve-context-in-private-channels) documentation, groupId is undefined for private channels.

![image](https://user-images.githubusercontent.com/81138249/165451498-d7f77cc8-ee76-4e83-8599-482cf8dbc904.png)

**Comment by v-chetsh** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.
