### ISSUE TITLE
How can I get the user alias who click the button in Teams Card

### ISSUE THREAD

**Issue by XimenaWang** [MicrosoftDocs/msteams-docs#582]

**Comment by Gousia-MSFT** [comment]
@XimenaWang You could fetch the users alias by using [Bot context](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/bots/bots-context). Please let us know if you need more help.

**Comment by XimenaWang** [comment]
@Gousia-MSFT - Hi, I am using the "Office 365 Connector Card" not Bot, Is there a way to get user information directly from Card ?
