### ISSUE TITLE
Authorising another AD app with the SSO token (teams bot)

### ISSUE THREAD

**Issue by astuj** [MicrosoftDocs/msteams-docs#5849]
Hi, 

I am trying to access my api using the same sso token which is generated for teams. I’ve added the permission in the bot AD app. 
<img width="1205" alt="Screenshot 2022-05-04 at 7 02 39 PM" src="https://user-images.githubusercontent.com/20801184/166691824-868a22d3-2a78-4480-b372-be2fcae40371.png">
 
Also I’m currently using Azure AD Directory v2 for the SSO. login. 
<img width="351" alt="Screenshot 2022-05-04 at 7 03 27 PM" src="https://user-images.githubusercontent.com/20801184/166691990-e29ef80f-0594-4426-81dc-12f15601adc3.png">

After all this I’m still getting 401 Unauthorised error. 

Can you help me what I’m doing wrong

**Comment by Prasad-MSFT** [comment]
Could you please share what console error/log you are getting?

**Comment by astuj** [comment]
@Prasad-MSFT - 
`{
   "error":{
      "code":"ServiceError",
      "message":"Missing required query string parameter: code. Url = https://token.botframework.com/.auth/web/redirect?error=invalid_client&error_description=AADSTS650053%3a+The+application+%27enterprise-bot-dev%27+asked+for+scope+%27user_impersonation%27+that+doesn%27t+exist+on+the+resource+%2700000003-0000-0000-c000-000000000000%27.+Contact+the+app+vendor.%0d%0aTrace+ID%3a+0b2829ae-6e48-4592-b364-cd7368b3f900%0d%0aCorrelation+ID%3a+bc8e3051-3f15-4978-897b-9e53bc88ea4f%0d%0aTimestamp%3a+2022-05-05+05%3a50%3a05Z&state=6873936194984be99c03049a13465ebf"
   }
}`

**Comment by astuj** [comment]
<img width="326" alt="Screenshot 2022-05-05 at 11 45 40 AM" src="https://user-images.githubusercontent.com/20801184/166871344-587cdf0f-bc64-4ba1-bd0c-14ffe9d253f4.png">

I believe i need the user_impersonation scope to access the api app but after adding that scope i get the above error

**Comment by Prasad-MSFT** [comment]
@astuj - The error says "The application 'enterprise-bot-dev' asked for scope 'user_impersonation' that doesn't exist on the resource '00000003-0000-0000-c000-000000000000"
Please refer this [link](https://github.com/MicrosoftDocs/azure-docs/issues/68540) which illustrates about similar issue.
