### ISSUE TITLE
CreateOrGetDirectConversation missing

### ISSUE THREAD

**Issue by damienestewart** [MicrosoftDocs/msteams-docs#585]
I installed the nuget package for Microsoft.Bot.Connector.Teams, and I'm on asp.net core. But intellisense is showing me that CreateOrGetDirectConversation doesn't exist as a method of ConnectorClient.Conversations. Did I install the wrong thing?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba8d3979-14f5-3105-ad89-ce6f98d11df1
* Version Independent ID: e53a7d1e-0e70-ca30-9809-fda7ebe5f4da
* Content: [Proactive messages - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/bots/bot-conversations/bots-conv-proactive#feedback)
* Content Source: [msteams-platform/concepts/bots/bot-conversations/bots-conv-proactive.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/bots/bot-conversations/bots-conv-proactive.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Wajeed-msft** [comment]
Which version of SDK are you using?

**Comment by damienestewart** [comment]
Hey @Wajeed-msft, I'm using version 4.0.0-beta1.

**Comment by Wajeed-msft** [comment]
@damienestewart - You can use _CreateConversationAsync()_ method with conversation paramerts to send proactive message. Please try this sample code:
```
                var userId = turnContext.Activity.From.Id;
                var tenantId = teamConversationData.Tenant.Id;
                var parameters = new ConversationParameters
                {
                    Members = new[] { new ChannelAccount(userId) },
                    ChannelData = new TeamsChannelData
                    {
                        Tenant = new TenantInfo(tenantId),
                    },
                };

                var conversationResource = await connectorClient.Conversations.CreateConversationAsync(parameters);
                var message = Activity.CreateMessageActivity();
                message.Text = "This is a proactive message.";
                await connectorClient.Conversations.SendToConversationAsync(conversationResource.Id, (Activity)message);
```

CreateOrGetDirectConversation() is an extension method in v3.* SDK.
