### ISSUE TITLE
Unable to see Personal Tab in Mobile Device

### ISSUE THREAD

**Issue by DivyaDev1992** [MicrosoftDocs/msteams-docs#5859]
My Local applications are appearing fine in Mobile, and Desktop devices.
However, my production application stopped appearing in Mobile Devices, a week ago. 

Kindly help me understand, why a production app would be removed only from a mobile device.

**Comment by sayali-MSFT** [comment]
@DivyaDev1992 - Could you please share the Repro steps or sample/manifest json, So that we can try it from our end? 
Thanks!

**Comment by sayali-MSFT** [comment]
@DivyaDev1992 -Apps [distributed through the Teams store](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/publish) have a separate approval process for mobile clients. Have you done approval process for mobile clients?

Ref Doc-https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/design/tabs-mobile?msclkid=98ec8f7ccd2a11ecbd2333c9dc90708e

**Comment by sayali-MSFT** [comment]
@DivyaDev1992 - Could you please confirm if your issue has resolved with above suggestion or still looking for any help?
