### ISSUE TITLE
Updated code snippet to include configuration parameters for people picker

### ISSUE THREAD

**Issue by Prithvi-MSFT** [MicrosoftDocs/msteams-docs#5863]
Hi team,
Existing code snippet does not include information on how to pass additional parameters to configure people picker. We can use the below updated code snippet.

```
microsoftTeams.people.selectPeople((error: microsoftTeams.SdkError, people: microsoftTeams.people.PeoplePickerResult[]) => 
 {
    if (error) 
    {
        if (error.message) 
           {
             alert(" ErrorCode: " + error.errorCode + error.message);
           }
            else 
            {
              alert(" ErrorCode: " + error.errorCode);
            }
      }
    if (people)
     {
            output(" People length: " + people.length + " " + JSON.stringify(people));
      }
  },{ setSelected: ["aad id"], openOrgWideSearchInChatOrChannel: true, singleSelect: false});
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2bafb046-4848-f113-8ea4-6ae1865c26fd
* Version Independent ID: bfae5321-cfaf-591e-d5bd-292d9f206462
* Content: [Integrate People Picker - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/people-picker-capability?tabs=Samplemobileapp)
* Content Source: [msteams-platform/concepts/device-capabilities/people-picker-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/device-capabilities/people-picker-capability.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **surbhigupta**

**Comment by Prasad-MSFT** [comment]
@surbhigupta12 - Could you please help here to update the code snippet as mentioned?
