### ISSUE TITLE
App description URL text not readable when installing the app because of dark blue color in dark or high-contrast themes

### ISSUE THREAD

**Issue by JordyGit** [MicrosoftDocs/msteams-docs#5869]
The manifest description of apps that appears on the about tab renders fine in all themes, but **when looking for an app to install in teams, the same description will have unreadable URLs because the URL color is not changing with the set theme**. 

It **sticks to a dark blue color.**

Its readable in that dark blue in the standard theme, but should be more like a purple color like on other places.

**Its not readable in dark or high-contrast themes**. 

See screenshot below:
![image](https://user-images.githubusercontent.com/33500507/167355122-ac9841ee-fdc6-4a83-8f0d-b314ccf45a9f.png)

MS Teams Desktop Version 1.5.00.11163 (64-bit). It was last updated on 6/05/2022.

**Comment by Nivedipa-MSFT** [comment]
@JordyGit - We are investigating your query. We will inform you once we have any update.

**Comment by Nivedipa-MSFT** [comment]
@JordyGit - We are able to repro this issue and we have raised a bug for it.

We will let you know once we get updates on it.

**Comment by JordyGit** [comment]
An update on this issue. 

Default & Dark mode show the urls now in the readable purple color. So the issue doesn't exist for these anymore.

(changed behaviour) High contrast mode shows the urls in the same color as normal text so it's not clear it's an url anymore. Teams version 1.5.00.14473 (64-bit). It was last updated on 10/06/2022. See screenshot below:

![image](https://user-images.githubusercontent.com/33500507/174247217-958daf24-47dd-443a-b572-ca2ffce2c591.png)

**Comment by Nivedipa-MSFT** [comment]
@JordyGit - We also checked this and able to repro for high contrast mode. We have informed same to the engineering team. We will let you know once we have any updates.

**Comment by Nivedipa-MSFT** [comment]
@JordyGit - We have tested for high contrast mode.
![image](https://user-images.githubusercontent.com/92150070/212895706-d30d7122-f818-481b-ba1e-f8612f27f0b6.png)

The bug has fixed, could you please check and confirm?

**Comment by JordyGit** [comment]
Confirmed! Thanks

**Comment by Nivedipa-MSFT** [comment]
@JordyGit - Could you please share your valuable [feedback ](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR7iCOpS5_b9Nqmwx43u5rtZUOThVR081SllSR05aSDQxQ0tUMDVPTVIxTi4u)here.
