### ISSUE TITLE
Two spaces automatically entered when pasting images in Chat/Conversations

### ISSUE THREAD

**Issue by SnazzySnail8** [MicrosoftDocs/msteams-docs#587]
![image](https://user-images.githubusercontent.com/44416747/56626842-3b23af80-65f8-11e9-9db6-bf62f030d220.png)

**Comment by Gousia-MSFT** [comment]
@SnazzySnail8 Thanks for reporting this. We are fixing it.

**Comment by Wajeed-msft** [comment]
This is fixed. Please try at your end and re-open if you still face this issue.
