### ISSUE TITLE
Is there any way to track Action.Submit button clicks within the bot framework?

### ISSUE THREAD

**Issue by ShalinShah84** [MicrosoftDocs/msteams-docs#5871]
Hi,

Can we track the button clicks on the Action.Submit event within the Adaptive Card ? I'm able to track the clicks on Action.OpenUrl but not with Submit.

**Comment by Prasad-MSFT** [comment]
We can get the value that user submit from adaptive card via Activity.Value property.

```
if(turnContext.Activity.Value!= null)
{

    reply.Text = $"submit data: {turnContext.Activity.Value}";

}
```
Also please refer: https://docs.microsoft.com/en-us/adaptive-cards/sdk/rendering-cards/javascript/actions?msclkid=b2ebb2bfcf6811ecaea3c52d9969cb53#handling-actions-when-users-click-action-buttons

**Comment by ShalinShah84** [comment]
I don't require the values, but is there any way I can track how many times user clicked the submit button on the bot.

**Comment by Prasad-MSFT** [comment]
You need to write custom logic for it. Every time user clicks on button, you need to maintain a counter at server side or in Card payload after refreshing the card. You can make use of local variable, but demerit is that it will get refreshed whenever you stop and start again.
