### ISSUE TITLE
Can we hide or disable button in bot framework once the user has clicked the button

### ISSUE THREAD

**Issue by ShalinShah84** [MicrosoftDocs/msteams-docs#5872]
Hi,

Can we hide or disable button in bot framework once the user has clicked the button within the adaptive card ?

**Comment by sayali-MSFT** [comment]
@ShalinShah84 -Here is related thread regarding disable adaptive card button-https://github.com/microsoft/botframework-sdk/issues/5472?msclkid=a862ff1bcf7f11ec902d3509636c1324

**Comment by sayali-MSFT** [comment]
@ShalinShah84 -Did you get chance to check above thread?
