### ISSUE TITLE
[Doc-enhancement] Iframe within Teams Tab might not work

### ISSUE THREAD

**Issue by SubbaReddi** [MicrosoftDocs/msteams-docs#5882]
Tab apps will be loaded as iframe in Teams. If there is any iframe within tab app, then it might not load properly in Teams. Because Teams will be unaware about sub iframes.

For example, Site1 added as Personal tab app. And in Site 1 page, iframe tag added as following: 
<iframe src="site2url" title="description"></iframe>.
It could be same domain or other domain. But site2url might fail to load content or passing token/session/cookies information. 

I see this as expected behavior. But adding note to indicate same will help.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b159fe6e-33d0-6174-f3c3-68aaec79ee1b
* Version Independent ID: 7037e9c7-f501-5b70-8acf-1f004a06289b
* Content: [Prerequisites - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/tab-requirements?msclkid=6107dae0cfd311ecbf003daa5b806246)
* Content Source: [msteams-platform/tabs/how-to/tab-requirements.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/tabs/how-to/tab-requirements.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Nivedipa-MSFT** [comment]
@SubbaReddi - We are investigating your query. We will update you.
