### ISSUE TITLE
MS Teams SDK Location API disambiguation needed

### ISSUE THREAD

**Issue by sushruth** [MicrosoftDocs/msteams-docs#5890]
Disambiguate what "current user coordinates" means in this page. Does it mean "current user's coordinates same as usageLocation of the user"? or does it mean "current user's current location"?

Please help. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a444c05e-51e3-0877-45ac-c45a914f6e50
* Version Independent ID: 04c36b67-a595-7670-27b5-e6b2155dbb6f
* Content: [location module - Teams](https://docs.microsoft.com/en-us/javascript/api/@microsoft/teams-js/microsoftteams.location?view=msteams-client-js-latest)
* Content Source: [nodejs/docs-ref-autogen/@microsoft/teams-js/microsoftTeams.location.yml](https://github.com/OfficeDev/msteams-client-docs-ref-typescript/blob/live/nodejs/docs-ref-autogen/@microsoft/teams-js/microsoftTeams.location.yml)
* Product: **msteams**
* GitHub Login: @charlesprakash
* Microsoft Alias: **o365devx**

**Comment by Nivedipa-MSFT** [comment]
@sushruth - "current user coordinates" means latitude and longitude details of user's current location.

**Comment by sushruth** [comment]
@Nivedipa-MSFT - can you modify the language in documentation to clearly represent what you just mentioned here? Thanks.

**Comment by Nivedipa-MSFT** [comment]
@surbhigupta12 - Could you please help here to update the document.
Content need to be updated: current user coordinates(latitude,longitude)
Document Link - https://docs.microsoft.com/en-us/javascript/api/@microsoft/teams-js/microsoftteams.location?view=msteams-client-js-latest

**Comment by surbhigupta12** [comment]
Hi @Nivedipa-MSFT,

This is out of doc team's scope. We do not update SDK content. Need to reach out to the engineering team. Removing the doc-enhancement label.

**Comment by Nivedipa-MSFT** [comment]
Hi @sushruth,
The return type of the API is clearly documented and location coordinates always include lat/long.
https://docs.microsoft.com/en-us/javascript/api/@microsoft/teams-js/microsoftteams.location.location?view=msteams-client-js-1.12.1

**Comment by sushruth** [comment]
@Nivedipa-MSFT - For a given user, location may mean "user data location", "current geological location", "tenant location", etc. So Specifying exactly what location this refers to will disambiguate the explanations. For example - instead of "current user coordinates", if it says "current geological location of the user as provided by the user's device" or something of that sort, it will be more explanatory. That is my ask here - to explain in detail.

**Comment by v-chetsh** [comment]
@surbhigupta12 - Can you please help us here to update the documentation?

**Comment by Nivedipa-MSFT** [comment]
@surbhigupta12  - Can you please help us here to update the documentation?

Content need to be updated : **"current geological location of the user as provided by the user's device"**
instead of **"current user coordinates"**

Content need to be updated here : https://docs.microsoft.com/en-us/javascript/api/@microsoft/teams-js/microsoftteams.location?view=msteams-client-js-1.12.1#@microsoft-teams-js-microsoftteams-location-getlocation

**Comment by surbhigupta12** [comment]
@Nivedipa-MSFT, this is out of our scope. Please reach out to the engineering team.
