### ISSUE TITLE
[Context] Clarify the full set of values any context object property can take.

### ISSUE THREAD

**Issue by sushruth** [MicrosoftDocs/msteams-docs#5895]
We specifically need to know what values `userLicenseType` and `tenantSKU` can take but in general it feels like many properties there (which are not of a generic type like `string`) must be defined fully in the documentation.

Please update. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8dfa1a29-bcf4-0cc5-ae3a-b185a00fd7bc
* Version Independent ID: c68181e1-151b-fc78-2671-fe9b397b702e
* Content: [Get context for your tab - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/access-teams-context?view=msteams-client-js-latest#get-context-by-inserting-url-placeholder-values)
* Content Source: [msteams-platform/tabs/how-to/access-teams-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/tabs/how-to/access-teams-context.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Nivedipa-MSFT** [comment]
@sushruth - We are investigating your query. We will get back to you once we have any update.

**Comment by sushruth** [comment]
@Nivedipa-MSFT Can you clarify exact string values? is it "E1", "E3", and "E5" or "E1 enterprise plan", "E3 enterprise plan" and "E5 enterprise plan" ?

Please clarify with quotes and full text.

Similar question on `tenantSKU` as well. Please clarify all exact values possible. Thanks.

I would also request the same for other potential fields in context that can be finite set of strings. This is the exhaustive list - 

```
locale
theme
teamType
userTeamRole - if it is deterministic
hostClientType
tenantSKU
userLicenseType
ringId
```

**Comment by sushruth** [comment]
@v-silakshmi - can you please clarify the description text with quotes around each possible value to specify exact values?

**Comment by Nivedipa-MSFT** [comment]
@sushruth - Possible values are like below:
**locale** - en-MY,en-NZ,en-PH,en-SG,en-TT,en-US,en-ZA,en-ZW...etc(upto 228 values)
**theme** - default, dark, or contrast.
**teamType** - Standard = 0, Edu = 1 , Class = 2,  Plc = 3, Staff = 4
**userTeamRole** - Admin = 0, User = 1 ,Guest = 2
**hostClientType** - android, ios, web, desktop, surfaceHub, teamsRoomsAndroid, teamsPhones, teamsDisplays rigel (deprecated, use teamsRoomsWindows instead)
**tenantSKU** - Possible values are enterprise, free, edu, unknown"
**userLicenseType** - Possible values are enterprise, free, edu, unknown"
**ringId** - ring0,ring0_s,ring1,ring1_5,ring1_6,ring2,ring3,ring3_6,ring3_9,general,general_gcc

**Comment by Nivedipa-MSFT** [comment]
@sushruth - The document has newly updated with properties of the [Context interface](https://docs.microsoft.com/en-us/javascript/api/@microsoft/teams-js/app.context?view=msteams-client-js-latest&preserve-view=true).

![image](https://user-images.githubusercontent.com/92150070/170489870-bd464e8c-2348-4124-bc77-67158f3e7f06.png)

Context property has all the information of properties.
![image](https://user-images.githubusercontent.com/92150070/170490792-ef91c6b5-6e2b-46f4-9567-59fddac4c955.png)
