### ISSUE TITLE
Poorly documented Start Call functionality

### ISSUE THREAD

**Issue by TxtSync** [MicrosoftDocs/msteams-docs#5917]
The call overview for the Teams SDK is not documented from the original source.

See example below direct from source:
```  
export enum CallModalities {
    Unknown = 'unknown',
    Audio = 'audio',
    Video = 'video',
    VideoBasedScreenSharing = 'videoBasedScreenSharing',
    Data = 'data',
  }

  export interface StartCallParams {
    // comma-separated list of user IDs representing the participants of the call.
    // Currently the User ID field supports the Azure AD UserPrincipalName,
    // typically an email address, or in case of a PSTN call, it supports a pstn
    // mri 4:<phonenumber>.
    targets: string[];
    // List of modalities for the call. Defaults to [“audio”].
    requestedModalities?: CallModalities[];
    // An optional parameter that informs about the source of the deep link
    source?: string;
  }
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39ee4b2f-8b19-f411-052d-0100c7510d2f
* Version Independent ID: e91fc1e6-bfc6-7edd-87f4-81467fadd581
* Content: [call module - Teams](https://docs.microsoft.com/en-us/javascript/api/@microsoft/teams-js/call?view=msteams-client-js-beta)
* Content Source: [nodejs/teams-js2/docs-ref-autogen/@microsoft/teams-js/call.yml](https://github.com/OfficeDev/msteams-client-docs-ref-typescript/blob/live/nodejs/teams-js2/docs-ref-autogen/@microsoft/teams-js/call.yml)
* Product: **msteams**
* GitHub Login: @charlesprakash
* Microsoft Alias: **o365devx**

**Comment by Meghana-MSFT** [comment]
We are looking into this, we will update you.

**Comment by Prasad-MSFT** [comment]
The documentation team has fixed the issue and the fix has been merged into main. Thanks!
