### ISSUE TITLE
[MSTeams][AdaptiveCard] Carousel not displaying in Teams on android devices.

### ISSUE THREAD

**Issue by luisleal8912** [MicrosoftDocs/msteams-docs#5922]
**Platform**
.Net Core
Bot Framework

Hi.
When I call a carousel from the teams option on mobile devices on Android, The card information is not displayed.
Happens when the carousel has cards of the type ThumbnailCard or HeroCard.

![image](https://user-images.githubusercontent.com/58193976/169072051-22184220-87ac-49a1-8230-9f91cf58548c.png)
When it is in a one to one chat it does work.

![image](https://user-images.githubusercontent.com/58193976/169073097-7487700b-b8ba-453d-9821-a245ed9cadf4.png)

**Comment by Prasad-MSFT** [comment]
@luisleal8912 - Could you please provide the card JSON which you are using, so that we can try once at our end?

**Comment by luisleal8912** [comment]
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Bot.Builder;
using Microsoft.Bot.Builder.Dialogs;
using Microsoft.Bot.Schema;
using Microsoft.Extensions.Logging;


namespace CardsBot.Dialogs
{
    public class ExampleMainDialog : ComponentDialog
    {
        protected readonly ILogger _logger;

        public ExampleMainDialog(ILogger<ExampleMainDialog> logger)
            : base(nameof(ExampleMainDialog))
        {
            _logger = logger;

            // Define the main dialog and its related components.
            AddDialog(new ChoicePrompt(nameof(ChoicePrompt)));
            AddDialog(new WaterfallDialog(nameof(WaterfallDialog), new WaterfallStep[]
            {
                CardStepAsync
            }));

            // The initial child Dialog to run.
            InitialDialogId = nameof(WaterfallDialog);
        }
        
        private async Task<DialogTurnResult> CardStepAsync(WaterfallStepContext stepContext, CancellationToken cancellationToken)
        {
            var attachments = new List<Attachment>();
            var reply = MessageFactory.Attachment(attachments);
            // Display a carousel of all the rich card types.
            reply.AttachmentLayout = AttachmentLayoutTypes.Carousel;
            reply.Attachments.Add(GetHeroCard().ToAttachment());
            reply.Attachments.Add(GetThumbnailCard().ToAttachment());
            

            await stepContext.Context.SendActivityAsync(reply, cancellationToken);

            // Give the user instructions about what to do next
            await stepContext.Context.SendActivityAsync(MessageFactory.Text("Type anything to see another card."), cancellationToken);

            return await stepContext.EndDialogAsync();
          
        }

        public static ThumbnailCard GetThumbnailCard()
        {
            var thumbnailCard = new ThumbnailCard
            {
                Title = "BotFramework Thumbnail Card",
                Subtitle = "Microsoft Bot Framework",
                Text = "Build and connect intelligent bots to interact with your users naturally wherever they are," +
                       " from text/sms to Skype, Slack, Office 365 mail and other popular services.",
                Images = new List<CardImage> { new CardImage("https://sec.ch9.ms/ch9/7ff5/e07cfef0-aa3b-40bb-9baa-7c9ef8ff7ff5/buildreactionbotframework_960.jpg") },
                Buttons = new List<CardAction> { new CardAction(ActionTypes.OpenUrl, "Get Started", value: "https://docs.microsoft.com/bot-framework") },
            };

            return thumbnailCard;
        }

        public static HeroCard GetHeroCard()
        {
            var heroCard = new HeroCard
            {
                Title = "BotFramework Hero Card",
                Subtitle = "Microsoft Bot Framework",
                Text = "Build and connect intelligent bots to interact with your users naturally wherever they are," +
                       " from text/sms to Skype, Slack, Office 365 mail and other popular services.",
                Images = new List<CardImage> { new CardImage("https://sec.ch9.ms/ch9/7ff5/e07cfef0-aa3b-40bb-9baa-7c9ef8ff7ff5/buildreactionbotframework_960.jpg") },
                Buttons = new List<CardAction> { new CardAction(ActionTypes.OpenUrl, "Get Started", value: "https://docs.microsoft.com/bot-framework") },
            };

            return heroCard;
        }
    }
}

**Comment by Prasad-MSFT** [comment]
@luisleal8912 - We are able to repro the issue and have raised a bug for the same. Engineering team is looking into it. We will inform you once we get further update. Thanks!

**Comment by Prasad-MSFT** [comment]
@luisleal8912 - We checked this issue again with latest Teams version on Android device and it seems to be fixed.
Please do verify and let us know the updates.

![image](https://user-images.githubusercontent.com/62237649/194496176-78453482-9ba7-4171-9ed2-71f8b7f2fc54.png)

Teams Version:
![image](https://user-images.githubusercontent.com/62237649/194496417-da067fa1-43e0-4d72-b4ae-2e869a46d6f6.png)

**Comment by Prasad-MSFT** [comment]
We are closing this issue for now. Please feel free to reopen if required. 
Thanks!
