### ISSUE TITLE
Include information about user attribution in the section about *bot messages*

### ISSUE THREAD

**Issue by aosolis** [MicrosoftDocs/msteams-docs#5923]
The information on user attribution (https://docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/action-commands/respond-to-task-module-submit?tabs=dotnet%2Cdotnet-1#user-attribution-for-bots-messages) is applicable to bot messages in general. It's not limited to messages triggered by action commands.

Please include (or link to) this information in the bots section of our docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fb0c2d8-f880-c260-d0be-6b9467e47f8c
* Version Independent ID: 7820ffc9-5260-c818-f5fb-672801a67d00
* Content: [Respond to the task module submit action - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/action-commands/respond-to-task-module-submit?tabs=dotnet%2Cdotnet-1)
* Content Source: [msteams-platform/messaging-extensions/how-to/action-commands/respond-to-task-module-submit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/messaging-extensions/how-to/action-commands/respond-to-task-module-submit.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **anclear**

**Comment by Prasad-MSFT** [comment]
Need to add this info(https://docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/action-commands/respond-to-task-module-submit?tabs=dotnet%2Cdotnet-1#user-attribution-for-bots-messages) under this below doc section: https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-messages?tabs=dotnet
FYI @surbhigupta12 Redirecting to doc team for enhancement
