### ISSUE TITLE
[Source translatability] ["{1}Purely local{2}: For bots, you can test your experience in the Bot Emulator."]

### ISSUE THREAD

**Issue by cdowling1971** [MicrosoftDocs/msteams-docs#5932]
For our Global markets please clarify if "**Purely local**" is translatable in this string, or in general: "{1}Purely local{2}: For bots, you can test your experience in the Bot Emulator."

The same applies to options **Locally hosted in Teams** and **Cloud-hosted in Teams**. These seem to be debugging options. Are they possibly options in Bot Framework Emulator? Or are they just general name for the three different debugging scenarios and do not exist as such anywhere and are therefore translatable?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ba912c7-3f70-3406-ad5c-06b6a0fc3875
* Version Independent ID: d3717482-cd3c-32ec-c7e0-28612bf13c37
* Content: [Choosing a setup to test and debug your app - Teams](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/debug)
* Content Source: [msteams-platform/concepts/build-and-test/debug.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/build-and-test/debug.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by sayali-MSFT** [comment]
@cdowling1971 - We are looking into this I will get back to you soon.

**Comment by clearab** [comment]
"Purely" here is used as a synonym for "completely". It indicates that the web service is running on the local machine, with emulator (also running on the local machine) connecting to it directly w/o any external calls.

**Comment by clearab** [comment]
"Locally hosted in Teams" is a bit of a shorthand - more precisely the app's web service is locally hosted, then a tunneling service is used to connect the locally running app to Teams.

**Comment by sayali-MSFT** [comment]
@cdowling1971 - Could you please confirm if your issue has resolved with above suggestion or still looking for any help?

**Comment by cdowling1971** [comment]
Looks like our partners queries are resolved thankyou both @sayali-MSFT @clearab
