### ISSUE TITLE
Update App Studio to be Developer Portal

### ISSUE THREAD

**Issue by joshmalik** [MicrosoftDocs/msteams-docs#5948]
App Studio that is referenced in this page appears to have been rebranded to Developer Portal, the page would benefit from being updated to reflect this. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Types of cards - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Nivedipa-MSFT** [comment]
@joshmalik - Thanks for reporting. We will take this into consideration and will update the doc accordingly whenever necessary.
