### ISSUE TITLE
ERROR: ChatConnector: receive - invalid token. Check bot's app ID & Password.

### ISSUE THREAD

**Issue by ashishrastogi18** [MicrosoftDocs/msteams-docs#596]
My conversation works fine. When i use message extesnion I get "ERROR: ChatConnector: receive - invalid token. Check bot's app ID & Password." in my vscode terminal and "POST /api/messages             403 Forbidden" in ngrok. Please advise.
I have set up bot id and password in vscode configuration

![Untitled](https://user-images.githubusercontent.com/28653281/56764629-2f102d00-6773-11e9-936b-6fb58c530b15.png)

**Comment by Abhijit-MSFT** [comment]
this worked for me. can you please share manifest.

**Comment by ashishrastogi18** [comment]
> This worked for me. Can you please share manifest?

Hi Abhijit, I believe I solved the issue. In my Vscode I had a terminal running by using "npm start" . This was not taking my botid and password into consideration. I killed the terminal.
I just started the debug from vscode and it started to authenticate. 
Thanks
