### ISSUE TITLE
502 Error when Posting Proactive Message

### ISSUE THREAD

**Issue by isaacdchan** [MicrosoftDocs/msteams-docs#598]
URL:  https://smba.trafficmanager.net/amer/v3/conversations
Data:  
{  
  "bot":{  
    "id":"28:80cebec0-a1c8-4d32-8c91-0b14bad9bae5",
    "name":"TMO_Surveybot"
  },
  "channelData":{  
    "tenant":{  
      "id":"6cfbaeae-c989-4c19-91eb-3a922a5c050d"
    }
  },
  "members":[  
    {  
      "id":"29:1RCsDogZNrMKm44GrGxJYRAjVpergc6LPTuwcS9Y4mt4hxUEfB3p0_2qb4J5WeGwx8JwONKiB2SmSW01o-shBMw"
    }
  ],
  "text":"How can I help you22222?",
  "textFormat":"markdown",
  "type":"message"
}

Am I missing something obvious? Works for non-proactive messages. 
If this helps, it becomes a 405 error when attempting from Azure Web Chat.

**Comment by Gousia-MSFT** [comment]
@isaacdchan Are you using Microsoft Bot Framework SDK to send the proactive message?
Could you please try creating a conversation first and then post a messageto the conversation? Please refer to the [proactive message example](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/bots/bot-conversations/bots-conv-proactive#example).

**Comment by isaacdchan** [comment]
Hi @Gousia-MSFT .

Sorry should have clarified. I am building the requests manually and then POST-ing using the Python requests library. Does it have to be through the SDK?

**Comment by Wajeed-msft** [comment]
@isaacdchan- SDK internally calls the same REST APIs. Could you please try the payload given in the [sample from documentation](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/bots/bot-conversations/bots-conv-proactive#example)?

**Comment by isaacdchan** [comment]
Now getting a 400 error.

1) My typical POST URL and data
![1](https://user-images.githubusercontent.com/33741008/56918798-d0e59180-6a73-11e9-9cf1-11d671a81466.png)
- Returns 201

2) Attempted proactive POST using sample URL and data
![2](https://user-images.githubusercontent.com/33741008/56918845-f2df1400-6a73-11e9-917f-4ece540f457c.png)
- Returns 400

3) Not included: attempted proactive POST using sample URL but proprietary data
- Returns 502

**Comment by isaacdchan** [comment]
@Wajeed-msft @Gousia-MSFT any insights?

**Comment by Wajeed-msft** [comment]
Sorry for delay in response, lost track of this. You should be using **/v3/conversations** to create a new reply chain. 

Ex:  Create New Conversation:
Request POST https://smba.trafficmanager.net/amer/v3/conversations
```
{
  "isGroup": true,
  "activity": {
    "type": "message",
    "text": "This is first message.",
    "attachments": [],
    "entities": []
  },
  "channelData": {
    "channel": {
      "id": "19:1842ec2df6764baeac2cf887247fe247@thread.skype"
    }
  }
}
```

Response:  `{"id":"19:1842ec2df6764baeac2cf887247fe247@thread.skype;messageid=1555420451879","activityId":"1:1sG_SL2Iu1L7zglxUUzOhG2A4xCMV-5LccgqAP336ivk"}`

-----------------------------------------------------------------------------------------------

Reply to Existing  conversation: 

Request: POST https://smba.trafficmanager.net/amer/v3/conversations/19%3A1842ec2df6764baeac2cf887247fe247%40thread.skype%3Bmessageid%3D1555420451879/activities
```
{
  "type": "message",
  "conversation": {
    "id": "19:1842ec2df6764baeac2cf887247fe247@thread.skype"
  },
  "text": "This is reply to existing message",
  "attachments": [],
  "entities": []
}
```
Response: {"id":"1:1oY3ErkU64_-K-Pxx8PcEzncVnBeayXr4WljhQuhP6SY"}

-----------------------------------------------------------------------------------------------

Please reopen if you are still facing this issue.
