### ISSUE TITLE
Chat deep link from outside Teams

### ISSUE THREAD

**Issue by mrik23** [MicrosoftDocs/msteams-docs#600]
Is it possible to use the deeplink to chat from outside Teams itself?

If I click the link in Teams it's working but not from SharePoint.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a891841a-a110-d18e-25c1-fc29e7d4a5e3
* Version Independent ID: c1a11eb8-00d1-e1d2-1e9d-71d059a6478a
* Content: [Create deep links - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/deep-links#feedback)
* Content Source: [msteams-platform/concepts/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/deep-links.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by 01** [comment]
@mrik23  deeplink is just a url. Should work just the same outside of teams. The teams website should ask if you want to open the desktop or web app. What behavior are you seeing when clicking the deeplink in sharepoint?

**Comment by mrik23** [comment]
It seems to work if I choose to open in the app, but if I want stay in the web app, it's going to the chat part but doesn't seem to resolve the user.

**Comment by clearab** [comment]
Can you provide the deeplink URL you're experiencing issues with? (with placeholders for privacy if necessary)

**Comment by mrik23** [comment]
Problem seems to be only if we force to access Teams with the webapp.

The link I use is as below:

`https://teams.microsoft.com/l/chat/0/0?users=<UserEmail>`

Once forcing to go to the webapp the URL is as below:

`https://teams.microsoft.com/_#/l/chat/0/0?users=<EmailAdress>&deeplinkId=<guid>`

Which brings me to a screen like that:

![image](https://user-images.githubusercontent.com/13704404/57122245-98f98980-6da6-11e9-8dc2-adb7d3edcaaf.png)

**Comment by 01** [comment]
I was able to recreate this problem. I am not getting the same blank page but when I make sure desktop app is not running and click use webapp it just takes me to my conversations ctx page

 the redirect is the same format https://teams.microsoft.com/_#/l/chat/0/0?users=<EmailAdress>&deeplinkId=<guid> but resolves to https://teams.microsoft.com/_#/conversations/?ctx=chat

**Comment by Wajeed-msft** [comment]
This looks like a bug. We are looking into this.

**Comment by skindog** [comment]
I also was experiencing the above bug when trying to create a link.  Essentially, what I'm looking to do is have a link in my email signature for my org to be able to click on and open up a chat conversation with me.  I'm using a test account to try to link to my real account (just to see if it's actually working).  It seemed to work if I already had a conversation with the individual, but I'm hoping a deep link will work to create a new conversation (or a draft of a new conversation).

**Comment by 01** [comment]
@skindog the exact scenario thats happening. It should still work if user is using the desktop app, but wont for web.

**Comment by Bryand13** [comment]
Hello,

We are facing the same scenario here . We are using the next deeplink "https://teams.microsoft.com/l/chat/0/0?users=28:xxxxx-xxxx-xxxx-xxxxxx" because we want implement an icon for a chatbot in the Chat tab for MSTeams.
![image](https://user-images.githubusercontent.com/50946094/58240051-71189880-7d4a-11e9-8cb7-3130bd9c626a.png)


ID chatbot: "28:xxxxx-xxxx-xxxx-xxxxxx"

App Desktop:
![image](https://user-images.githubusercontent.com/50946094/58239854-2860df80-7d4a-11e9-9508-6921040983ad.png)


Web:
![image](https://user-images.githubusercontent.com/50946094/58239975-47f80800-7d4a-11e9-8669-721e4716997c.png)

Appreciate any suggestion.

Have a nice day.

**Comment by Wajeed-msft** [comment]
@Bryand13 - Deeplink should work fine is all other scenarios excpt the one reported for browser scenario. 

Are you trying [Deep linking from your tab](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/deep-links#deep-linking-from-your-tab)?

**Comment by Bryand13** [comment]
Hi Wajeed, 

No. Im trying "Deep linking to a chat".

**Comment by mrik23** [comment]
Any update on that? Still not working in the web client.

**Comment by AliLoUuU** [comment]
Hello,

I need one simple thing : launch teams desktop application and chat with someone.

When i call https://teams... /chat/0/0?users=<mail> it opens a webpage that opens teams on desktop BUT the webpage is still here, I don't want that page, how to close it automatically or ignore that?!

I think that passing from https://teams is useless...so I checked process execution after redirecting from https://teams.. and I found that teams.exe is launched with "msteams://l/chat ..." :
=>  URL is quite the same, but, the argument "deepLinkId" looks like mandatory.
Is it possible to launch directly the desktop app with : msteams://l/chat/0/0?users=<mail> and open the good chat page ? 

Thank you for your help

**Comment by pmeripe** [comment]
Even I am looking for open a teams new chat window from a SharePoint page, I don't want to provide any users in deep link.

**Comment by Wajeed-msft** [comment]
Please use [microsoftTeams.executeDeepLink(/*deepLink*/)](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links#deep-linking-from-your-tab) to trigger deeplink opening without opening intermediate page.
