### ISSUE TITLE
Getting ServiceURL for proactive messaging

### ISSUE THREAD

**Issue by rajnemani** [MicrosoftDocs/msteams-docs#601]
How can one get access to service URL and continue to use it in case when the conversation is initiated by the bot with a user using REST API (example from an Azure function)?  This document should have this aspect clarified.

**Comment by 01** [comment]
@rajnemani it should be in the activity context from the initial message for REST API like any of the other protocols. 

https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-api-reference?view=azure-bot-service-4.0#base-uri

if you mean Direct Line API there isnt a "serviceurl" you will need to keep track of the watermark in the activityset/message set
