### ISSUE TITLE
UserVoice link is broken

### ISSUE THREAD

**Issue by wwejason** [MicrosoftDocs/msteams-docs#6016]
In the "Feature request and general help" section, the UserVoice link goes to a nonexistent page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19ddf42e-0a47-7717-52d4-e549155480a2
* Version Independent ID: 4bbe9beb-233f-cfd5-097b-f280aab5fde8
* Content: [Microsoft Teams developer community help and feedback - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/feedback)
* Content Source: [msteams-platform/feedback.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/feedback.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Prasad-MSFT** [comment]
This marked link is non-functional. Please do update
![image](https://user-images.githubusercontent.com/62237649/170183636-cb567e3b-1e73-47e5-b779-e1b0122d7db2.png)
https://docs.microsoft.com/en-us/microsoftteams/platform/feedback#feature-request-and-general-help
@surbhigupta12 -Please help here to update the link.
