### ISSUE TITLE
Can't go back to Teams in a deep linked personal tab on iOS 15.2.1

### ISSUE THREAD

**Issue by plamber** [MicrosoftDocs/msteams-docs#6033]
Hello,
Our users receive an activity feed notification with a deep link to our application.
Once redirected to our app, we use react-router to show the appropriate page to the user. 

The back button on the upper left corner to Teams is no more redirecting the user back to the MS Teams app. Our users are stuck on our app and have to stop the Teams app and re-open it. This happens in iOS 15.2.1 and the Teams App 4.8.1.

The expected behavior is that users clicking on the back button in the upper left corner are always redirected to the Teams overview page and leave our app.
We do not experience this problem on the Android app.

Let me know if you require more information.

Cheers,
Patrick

**Comment by v-chetsh** [comment]
@plamber - Can you please share your code snippets and reference doc that you are following?

**Comment by plamber** [comment]
Hi @v-chetsh,
the team's manifest has the following elements.

An activity feed type similar to this one.
```
"activities": {
        "activityTypes": [{
            "type": "myFeedType",
            "description": "My description",
            "templateText": "Action required for {item}"
        }]
}
```

A personal tab similar to this one
```
"staticTabs": [{
        "entityId": "myEntityId",
        "name": "Home",
        "contentUrl": "https://{yourDomain}/?lng={locale}&theme={theme}&tid={tid}&userPrincipalName={userPrincipalName}&userObjectId={userObjectId}&userLicenseType={userLicenseType}&tenantSKU={tenantSKU}",
        "scopes": ["personal"]
    }]
```

We are using Graph to send an activity feed with a deep link to the personal tab (https://docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications). The deep Link is generated in C# with such a format:
```
https://teams.microsoft.com/l/entity/{teamsAppId}/myEntityId?context={HttpUtility.UrlEncode(context)}
```
In the context variable, we pass some application parameters that are not relevant to the issue.

When clicking on the Teams Notification on iOS 15.2.1 you are being redirected to your personal tab. The iOS app does then not provide any way to go back to teams. Older iOS versions do not have this issue.

Let me know if you require additional information.

Cheers,
Patrick

**Comment by Nivedipa-MSFT** [comment]
@plamber - We are checking this internally. We will update you soon.

**Comment by ChetanSharma-msft** [comment]
@plamber - Can you please try to update your Teams client & iOS version and check it once?

**Comment by plamber** [comment]
Hi @ChetanSharma-msft,
unfortunately, we have still the same behavior. We are not able to go back to the Teams client. We tested it with this version:

![image](https://user-images.githubusercontent.com/18241305/178423260-5cfe7023-38dc-447a-8531-1083807b27de.png)

Cheers

**Comment by ChetanSharma-msft** [comment]
@plamber - Thanks for sharing the details.
We will check on it from our end and let you know the updates.

**Comment by Nivedipa-MSFT** [comment]
@plamber - Apologies for delay response. We have tested this scenario and it was working fine at our end. We have tested this in 4.12 version. Could you please share the screen recording

**Comment by plamber** [comment]
Hi @Nivedipa-MSFT,
should I share the video over a different channel? What is your preference?

Thank you,
Patrick

**Comment by Nivedipa-MSFT** [comment]
@plamber - You can send the video link here or you can send it on mail to microsoftteamsdev@microsoft.com

**Comment by plamber** [comment]
Hi @Nivedipa-MSFT,
I just send the video to the email.

Cheers

**Comment by Nivedipa-MSFT** [comment]
@plamber - We will check and let you know the updates.

**Comment by plamber** [comment]
Hello,
I just wanted to inform you that with the latest Teams version we are no more able to reproduce this error. 

I am going to close this issue.

Thank you
