### ISSUE TITLE
Need to describe what the timeout/retry behavior is and how apps should handle timeout/retry

### ISSUE THREAD

**Issue by aosolis** [MicrosoftDocs/msteams-docs#604]
The page is missing information on:
- how much time apps have to respond to the invoke
- what happens if the request hits an error/timeout-- does Teams retry
- how should apps handle the retry so as not to end up with multiple invocations?
- how should apps handle long-running actions that can't complete within the timeout?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aaa0ea75-7363-3ef5-39df-ad07c493c118
* Version Independent ID: ab9a2a6e-e2ca-828f-cd8b-bd9ff98411ab
* Content: [Initiate actions with messaging extensions - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/messaging-extensions/create-extensions#feedback)
* Content Source: [msteams-platform/concepts/messaging-extensions/create-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/messaging-extensions/create-extensions.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by aosolis** [comment]
@surbhigupta12 this is a long-standing doc enhancement request, can we add it to the backlog?

**Comment by aosolis** [comment]
@surbhigupta12 do we have any updates?

**Comment by v-chetsh** [comment]
@surbhigupta12 - Can you please check on this issue.

**Comment by ChetanSharma-msft** [comment]
Hello @surbhigupta12, @v-shalinirobinson  - Can you please look into this issue?

**Comment by surbhigupta12** [comment]
Resolved.
