### ISSUE TITLE
Change in Context Response: Microsoft Bot

### ISSUE THREAD

**Issue by DivyaDev1992** [MicrosoftDocs/msteams-docs#6040]
I have been building A Microsoft Bot, for a considerable amount of time. Until a couple of days back, the following response was never true when the control comes from the Personal Bot:
` if (context.activity.attachments && context.activity.attachments.length > 0) {
      if (context.activity.attachments[0].contentType === "text/html") {
          return;
      }
  }`
  However, something has changed recently that this `context.activity.attachments[0].contentType === "text/html"` condition becomes true all the time, for any message from the bot.
  
  This is breaking my application, since I was unaware of the change. 
  
  Kindly provide insight around such changes, and how do we best keep up with the changes in data returned by the context.

**Comment by v-chetsh** [comment]
@DivyaDev1992 - We will check on it and get back to you.

**Comment by Meghana-MSFT** [comment]
You can go through this [What's new for developers in Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/whats-new)  document to discover Microsoft Teams platform features that are generally available (GA) and in developer preview.  Additionally could you please share  the repro steps to test out the above issue? Are you sending attachments using the bot?
