### ISSUE TITLE
Document limit on size of messaging extension result

### ISSUE THREAD

**Issue by aosolis** [MicrosoftDocs/msteams-docs#605]
If the card result is too large, then if you add it to a message the message cannot be sent. 
What's the maximum size of a ME result card?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88ff3777-49c4-8cdc-089e-8612a8774ffb
* Version Independent ID: 0d927000-0b55-2129-cbbb-6630c1ec481e
* Content: [Search with messaging extensions - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/messaging-extensions/search-extensions)
* Content Source: [msteams-platform/concepts/messaging-extensions/search-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/messaging-extensions/search-extensions.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by unt1tled** [comment]
I don't see it documented anywhere but I've noticed that it restricts me from sending a message when the card height is over 750px.

**Comment by clearab** [comment]
There is a limit for card sizes, but it is context and client dependent and can be quite difficult to calculate accurately. We are debating on how best to document the limit, given the complexity.

**Comment by mayureshjaiswal** [comment]
As per the below URL sending adaptive card is not possible in messaging extension can anyone please confirm this.
Url: https://github.com/OfficeDev/BotBuilder-MicrosoftTeams-dotnet/issues/15
