### ISSUE TITLE
Teams Dev Portal - App with no owners

### ISSUE THREAD

**Issue by YJasonY** [MicrosoftDocs/msteams-docs#6050]
Hi,

Given that App Studio is deprecating, we are in the process of moving to use the Teams Dev Portal.

However, we are having issues with an app - the app appears to be using an old version of the manifest, but we cannot update it or delete as it appears it doesn't have any owners.

![image](https://user-images.githubusercontent.com/16281323/170604684-3d744743-4e7d-4acc-9ef1-2647ba8ba057.png)

There appears to be a blank owner. I cannot leave the app as it gives the error at the top (which contrarily suggests I am the owner). I also cannot delete the app nor can I add anyone else.

Trying to upload a newer version of the manifest gives the following:
![image](https://user-images.githubusercontent.com/16281323/170604941-f02674ec-a66b-4d62-95e4-6b0d719cb945.png)

This is an issue because we have this app deployed in a few Tenants and we cannot update them if we use a different App ID. 

Is there a way this app can be fixed/deleted from the backend? 

App ID: ff579744-57b5-4a05-a8a5-05cb0ee7b9ec
Teams App ID (Internal): 80eb8e30-f6a5-4fea-92ee-bd29b65155cf

**Comment by Meghana-MSFT** [comment]
We are looking into this, we will update you.

**Comment by Meghana-MSFT** [comment]
Can you please try uploading/Deleting the app from the Teams admin center -

Update App : 
![image](https://user-images.githubusercontent.com/81138249/170760871-d024c81a-9910-456a-8b56-e8f8f3fa0eed.png)

Delete App : 
![image](https://user-images.githubusercontent.com/81138249/170760979-6b1c0d45-f3e6-49fa-a4d2-f99da6212bad.png)

**Comment by YJasonY** [comment]
Hi @Meghana-MSFT 

When I try to upload this app in the Teams Admin Centre, I get the following error:

![image](https://user-images.githubusercontent.com/16281323/170910316-a5e8555d-86fb-4f26-b060-bee2b98a89f4.png)

I noted that within the dev portal, I can see this manifest file has errors:

![image](https://user-images.githubusercontent.com/16281323/170910427-f961c794-e8a0-44b5-99e8-6cdf4c9e02c2.png)

but I cannot update it as it does not recognise any user as an owner.

**Comment by Meghana-MSFT** [comment]
Could you Please check the below points?

1. Please check if you are mentioning the correct version of manifest - https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema#manifestversion
2. Please check if this thread helps you - https://stackoverflow.com/questions/62383644/failed-to-load-the-package-the-add-in-package-provided-was-not-understood-verif

**Comment by YJasonY** [comment]
Hi @Meghana-MSFT,

I am able to 'fix' the manifest, and upload it via Teams admin centre, then remove it again per your initial suggestions, but this has no effect on the app in the Dev Portal.

The issue is that, within the Dev Portal, we have this app with no owners, that I cannot update (the prompt asks if I want to duplicate, which creates it under a new app Id) nor can I delete the app (no option for delete and cannot leave, as it throws the error above).

Note that this app also is NOT present in App Studio.

**Comment by Meghana-MSFT** [comment]
The engineering team has few queries, could you please help answer them - 
The app owner field is not populated/empty because the person who has been the primary owner has left the organization. 

1. Can you please confirm if this is the case with you? 
2. What exactly are you looking for? Do you want to delete the app or fix this issue (meaning you want to assign an owner for this app?) 

Team said that we can explore any workaround if we can understand what the exact ask is.

**Comment by YJasonY** [comment]
Hi @Meghana-MSFT - thanks for reaching out to the engineering team. In response to the queries:

1. I was pretty sure I was the owner of this application but it is possible - I honestly cannot recall
2. I want to be able to upload a new version of the manifest under the same app id (ff57...) 
If it is possible to assign me as the owner, that would be preferred (let me know the best way for me to provide the email/UPN of the account) 
otherwise, deleting it so it frees up the app Id and I can reupload a new version under the same app Id also works.

**Comment by v-chetsh** [comment]
@YJasonY - Thanks for sharing the details.
We have already shared it with engineering team and they are looking into it.
We will get back to you once we get any update from engineering team.

**Comment by Meghana-MSFT** [comment]
Could you please confirm if the user is a Microsoft tenant user or external? Are you logged in as a user of a M365 tenant? Or are you logged in using personal MSA account?

**Comment by YJasonY** [comment]
Yup it's a user within the tenant, not a personal account.

**Comment by Meghana-MSFT** [comment]
Could you please try this suggestion and confirm if it helps?

Tenant admin can import an app with the exact same app id and overwrite the existing app and making the Tenant admin the owner of the app.

**Comment by Meghana-MSFT** [comment]
Could you please confirm if the above solution solved your issue?

**Comment by YJasonY** [comment]
Hi, unfortunately this didn't work and I am still getting the same error when I try to upload:

![image](https://user-images.githubusercontent.com/16281323/175836427-85cfbeba-d141-4fb3-8fc6-610e12cbf733.png)

Confirming I was given the role of "Global Administrator" for the tenant.

**Comment by Meghana-MSFT** [comment]
Could you please share the network trace when this import fails?

**Comment by Meghana-MSFT** [comment]
Thanks for the details.

**Comment by ronwang01** [comment]
> Hi @Meghana-MSFT - please see network trace and console at the time of upload:
> 
> ![image](https://user-images.githubusercontent.com/16281323/177879922-03a7305c-77cb-4fcc-9601-41475040e792.png)
> 
> ![image](https://user-images.githubusercontent.com/16281323/177879949-fae04ceb-5446-4fa6-9b9e-fd438fac5061.png)

Will you mind sharing the header of the request and response? There should be a correlation id.

**Comment by YJasonY** [comment]
Sure thing:

Request:
x-correlation-id: 69d4f234-1d03-4cca-9fb6-9d12e843d768_27

Full Request Header:
`:authority: dev.teams.microsoft.com
:method: POST
:path: /apac/api/appdefinitions/v2/import?overwriteIfAppAlreadyExists=false
:scheme: https
accept: application/json, text/plain, */*
accept-encoding: gzip, deflate, br
accept-language: en-GB,en-US;q=0.9,en;q=0.8
authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IjJaUXBKM1VwYmpBWVhZR2FYRUpsOGxWMFRPSSIsImtpZCI6IjJaUXBKM1VwYmpBWVhZR2FYRUpsOGxWMFRPSSJ9.eyJhdWQiOiJodHRwczovL2Rldi50ZWFtcy5taWNyb3NvZnQuY29tIiwiaXNzIjoiaHR0cHM6Ly9zdHMud2luZG93cy5uZXQvYTE1YmQ0OWUtMjE2Ny00NjdiLWIyYWMtNzhkY2Y1N2NlNWNlLyIsImlhdCI6MTY1NzQ5MzY0MiwibmJmIjoxNjU3NDkzNjQyLCJleHAiOjE2NTc0OTkxNjAsImFjciI6IjEiLCJhaW8iOiJBVlFBcS84VEFBQUF1Wk9zd3k4cG1BL0psTGs1WnU5S1QxRGZ6Qkc2b2djN2pNSmFmSW4zSTFOcFJxY21nZTFpREVXNlErVVZGTHpsQ1dFZTVlNnEvdWxnNXBvZGFrbktob1FSeDZVSnpxUGRvTGlaeFlUYXkwST0iLCJhbXIiOlsicHdkIiwibWZhIl0sImFwcGlkIjoiZTE5NzljMjItOGI3My00YWVkLWE0ZGEtNTcyY2M0ZDBiODMyIiwiYXBwaWRhY3IiOiIwIiwiZmFtaWx5X25hbWUiOiJZYW5nIiwiZ2l2ZW5fbmFtZSI6Ikphc29uIiwiaXBhZGRyIjoiMTU5LjE5Ni4xNzAuMzMiLCJuYW1lIjoiSmFzb24gWWFuZyIsIm9pZCI6IjJkNDkwMDQ4LTkzMjItNGNmOS05NTFjLTdmMWU0NWM1OGRjYiIsInB1aWQiOiIxMDAzQkZGRDk1MDcxQzg3IiwicmgiOiIwLkFVRUFudFJib1djaGUwYXlySGpjOVh6bHppS2NsLUZ6aS0xS3BOcFhMTVRRdURKQkFFQS4iLCJzY3AiOiJBcHBEZWZpbml0aW9ucy5SZWFkV3JpdGUgQ2FyZHMuUmVhZFdyaXRlIiwic3ViIjoibC1WTnJsTzE1blRKUm9FX1FIbjhKdHQ4Y3lHa2FNUm9QeGFwWmNGX2NZTSIsInRpZCI6ImExNWJkNDllLTIxNjctNDY3Yi1iMmFjLTc4ZGNmNTdjZTVjZSIsInVuaXF1ZV9uYW1lIjoiamFzb255QGFudGFyZXNzb2x1dGlvbnMuY29tLmF1IiwidXBuIjoiamFzb255QGFudGFyZXNzb2x1dGlvbnMuY29tLmF1IiwidXRpIjoiQ2RkODhxRENTMGU2VkFmREFmZG5BQSIsInZlciI6IjEuMCJ9.ZPsGscYTCp-lEdDynX_QD6Z6TSFzQoF3DiVLoYltWl5ulbd4mlS65s5W-EKwSGXoA63FA4PXpBBd3zHHN79SspMesgBByQhEaaVgyLzSz-RuIsb2CpbPof1YCwRRsybttKZRDxYb8HjBTpgmXsZy8qg0UTxWmcWCy4VHgzfvyJOkRiCQulNDi6Vkjpe6Q2h_ABwm3_DWHhDUP2cXImNJWnYVLz12Aaxvj11ZTLv5H2QErUPamcVS5Fn0hSAErZ0fpPysBxG30ljCBLpdq8n5pAf8KDjHpa-xJK5nE9ZcMo_KvKMvTO8kWteZiv2UshsMcGRjpWihBgyYTbaDkZRrWw
client-source: DeveloperPortal
content-length: 3616
content-type: application/zip
cookie: MC1=GUID=4aacd37d0fcc4f408dad8dbf6ea4a19d&HASH=4aac&LV=202111&V=4&LU=1636674049695; _ga=GA1.2.1991749888.1636674050; MUID=1B6A2D766D9C6E820D793D9A699C68D2; _cs_c=0; _uetvid=edd40760434a11ec8ab66d4035224499; __CT_Data=gpv=1&ckp=tld&dm=microsoft.com&apv_1067_www32=1&cpv_1067_www32=1; _cs_id=cbef4096-e7cb-a9b0-d46b-9c76e7f061f7.1636674973.3.1636684807.1636684807.1613561419.1670838973606; LPVID=MxNDM1MWE0ZjM1MTU1MjFl; clienttype=web; tenantId=a15bd49e-2167-467b-b2ac-78dcf57ce5ce; msresearch=%7B%22state%22%3A%7B%22name%22%3A%22IDLE%22%7D%2C%22userid%22%3A%2216533456346904638230904895246%22%7D; MicrosoftApplicationsTelemetryDeviceId=50b8f89d-db51-4b50-9725-a0ec1440ce55; AMCV_EA76ADE95776D2EC7F000101%40AdobeOrg=1176715910%7CMCIDTS%7C19181%7CMCMID%7C76357277441433707943092935066729226895%7CMCAAMLH-1655184517%7C8%7CMCAAMB-1657162912%7C6G1ynYcLPuiQxYZrsz_pkqfLG9yMXBpb2zX5dvJdYQJzPXImdj0y%7CMCOPTOUT-1657170113s%7CNONE%7CMCSYNCSOP%7C411-18950%7CvVersion%7C5.4.0%7CMCAID%7CNONE; mbox=PC#b0ed3943bfe04a0983c0c0f6fbdcef63.36_0#1691349612|session#b33c3b62944f43bfb2a749dddc2574fe#1657164774; MSFPC=GUID=4aacd37d0fcc4f408dad8dbf6ea4a19d&HASH=4aac&LV=202111&V=4&LU=1636674049695; MS0=3da6bf58088346cbabcc20db5d00c3af; ai_session=udJY85gxACbZv5SsofictZ|1657493941798|1657493943382
origin: https://dev.teams.microsoft.com
referer: https://dev.teams.microsoft.com/apps
sec-ch-ua: ".Not/A)Brand";v="99", "Google Chrome";v="103", "Chromium";v="103"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: same-origin
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
x-correlation-id: 69d4f234-1d03-4cca-9fb6-9d12e843d768_27`


Response:
x-correlation-id: 69d4f234-1d03-4cca-9fb6-9d12e843d768_27

Full Response Header:
`access-control-allow-origin: https://dev.teams.microsoft.com
access-control-expose-headers: x-correlation-id,date
cache-control: no-cache, no-store
content-type: application/json; charset=utf-8
date: Sun, 10 Jul 2022 23:02:05 GMT
expires: 0
pragma: no-cache
request-context: appId=
strict-transport-security: max-age=31536000; includeSubDomains=31536000
vary: Origin
x-cache: CONFIG_NOCACHE
x-content-type-options: nosniff
x-correlation-id: 69d4f234-1d03-4cca-9fb6-9d12e843d768_27
x-msedge-ref: Ref A: 2EC9AA074A224CAC982D94ECF0B5F411 Ref B: SYD03EDGE1316 Ref C: 2022-07-10T23:02:05Z
x-xss-protection: 1; mode=block`

**Comment by YJasonY** [comment]
Hi @ronwang01, @Meghana-MSFT - any updates on this or any additional information you need from me?

Thanks.

**Comment by Meghana-MSFT** [comment]
@YJasonY - Engineering team has created a bug for this issue. Team is working on the issue. We currently do not have any ETA to share. We will keep you posted on the updates.

**Comment by ChetanSharma-msft** [comment]
Hello @YJasonY - Sorry for delay in response.
We are actively checking the updates on this issue with engineering team and let know the updates, if any.

**Comment by Meghana-MSFT** [comment]
@YJasonY - Tenant admin can now take over the app via Take ownership option in https://dev.teams.microsoft.com/apps. 
![image](https://user-images.githubusercontent.com/81138249/214322374-af849f91-3c33-4496-844f-0523e5540fd7.png)

**Comment by YJasonY** [comment]
Hi @Meghana-MSFT, this still isn't working. 

I tried to use the "Take Ownership" function, but nothing seems to happen despite the success response. 

![image](https://user-images.githubusercontent.com/16281323/215362690-a1e9a137-2688-450b-88aa-c0be3e9e391e.png)

![image](https://user-images.githubusercontent.com/16281323/215362912-a7d520b5-f391-4af7-a828-033dc28f9806.png)


`{"teamsAppId":"b53c0d6f-[OMITTED]","tenantId":"a15bd49e-[OMITTED]","ownerAadId":"2d490048-[OMITTED]","userList":[{"tenantId":"a15bd49e-[OMITTED]","aadId":"2d490048-[OMITTED]","displayName":"jasony@[OMITTED]","userPrincipalName":"jasony@[OMITTED]","isAdministrator":false}] ... }`


The "Take Ownership" doesn't appear to actually assign me as the owner. 
There is no way for me to delete or even leave the app:

![image](https://user-images.githubusercontent.com/16281323/215363071-3105261c-6241-4362-8b4b-210382d85ed5.png)

![image](https://user-images.githubusercontent.com/16281323/215363139-1c0f9599-a002-4450-a59b-23055f00eb57.png)

Happy to organise a screenshare session if there is any additional info you need. 

At this point, we just want the environment completely clean (delete/remove everything) so we can start over - is there anyway the engineering team can manually do this from the backend?

**Comment by Meghana-MSFT** [comment]
@YJasonY - We have shared this with engineering team, I will keep you posted once I get any update from the team.

**Comment by ronwang01** [comment]
@YJasonY Sorry for the delay, the issue here is you are already a contributor to the app, and takeover ownership will basically be a no-op. A simple workaround is to have another Global admin or Teams tenant admin take over the app and elevate your rights from contributor to admin. 

Meanwhile, we will be working on fixing this issue.

**Comment by YJasonY** [comment]
thanks @ronwang01 - we managed to resolve the issue with the help of another Global admin and have now successfully removed all the apps.
