### ISSUE TITLE
Does that mean that we can use teams with Botframework 4.0 sdK?

### ISSUE THREAD

**Issue by vivekjainAco** [MicrosoftDocs/msteams-docs#606]
The very first note on this page:

"These steps require Bot Framework version 3. The Bot Framework documentation has been updated to version 4, which does not work with Teams."

So if I am using bot framework 4.0 to build my bot, does that mean I can deploy my bot to teams? 

Thanks,
Vivek

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 087ab52e-fa36-8255-1438-957f895ba583
* Version Independent ID: f19cdd18-9aef-2bb2-6c2f-e0f0f79b9ca0
* Content: [Create a bot - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/bots/bots-create#feedback)
* Content Source: [msteams-platform/concepts/bots/bots-create.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/bots/bots-create.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by clearab** [comment]
Hi - Yes, you can build a bot using Bot Framework 4 and deploy it to Teams. Our Teams Bot Builder SDKs (which are referenced in the documentation) do not work with Bot Framework 4. We do have versions of our Node and C# SDKs currently in beta that work with Bot Framework 4, but they do not have extensive documentation yet. You can find links to those here: https://aka.ms/teamsdev#pivot=sdk-tools

You'll need to look at the samples in those beta SDK repositories for guidance on how they work. The structure of the SDKs for Bot Framework 4 (both the Teams wrapper SDK and the core Bot Framework SDK) are quite different. The existing documentation will apply conceptually but in all likelihood the code examples will not align.

If you do use the beta SDKs, please feel raise any issues you encounter and we'll be happy to assist.

**Comment by kaushalgautam** [comment]
@clearab any timeline on when the documentation will be in sync with v4 for Teams integration on Node JS? This is a poor example of maintaining products. When MS has officially asked us to build bots on v4 or migrate existing bots to v4, how do we do so without proper documentation? We are stuck on how to integrate multiple channel functionalities for a bot that will work on multiple channels.
