### ISSUE TITLE
Samples for graphConnector notificationUrl 

### ISSUE THREAD

**Issue by formulahendry** [MicrosoftDocs/msteams-docs#6065]
Is there any code sample or tutorial for the graphConnector notificationUrl (https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema#graphconnector)?

I could not find a way how to to add graphConnector notificationUrl in App Studio:
![image](https://user-images.githubusercontent.com/1050213/170959045-1c2aa408-b557-4ca7-b6f2-7fa9fdbe7d03.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f94a488-d636-92b3-21eb-c88744c8f272
* Version Independent ID: 7b3413f4-9ade-accf-5cb2-83fead11a32a
* Content: [Manifest schema reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema?source=docs)
* Content Source: [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/resources/schema/manifest-schema.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Nivedipa-MSFT** [comment]
formulahendry - Could you please refer below sample for graph connector
https://github.com/OfficeDev/TeamsFx-Samples/tree/ga/graph-connector-app

**Comment by formulahendry** [comment]
Hi @Nivedipa-MSFT , sorry, https://github.com/OfficeDev/TeamsFx-Samples/tree/ga/graph-connector-app is written by me. And this sample does not include any code sample of graphConnector notificationUrl.

Actually, I want to find code sample of graphConnector notificationUrl. In the end, I want to see if there is possibility to include code sample of graphConnector notificationUrl into https://github.com/OfficeDev/TeamsFx-Samples/tree/ga/graph-connector-app

**Comment by Nivedipa-MSFT** [comment]
@formulahendry - We have checked this. But there is no any code sample available for graphConnector notificationUrl.

**Comment by formulahendry** [comment]
Any plan for the sample about graphConnector notificationUrl?

**Comment by Nivedipa-MSFT** [comment]
@formulahendry - We are still checking this with engineering team. We will inform you once we have any updates.

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.
