### ISSUE TITLE
The settings properties mentioned in the Connectors do not match Settings interface definition in the Teams SDK

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#607]
Please help to update the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c21a27c1-d01a-6cc7-c991-73af6492aad8
* Version Independent ID: b15d2142-df29-250e-9a0a-b734dcb93162
* Content: [Office 365 Connectors - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/connectors/connectors-creating)
* Content Source: [msteams-platform/concepts/connectors/connectors-creating.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/connectors/connectors-creating.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by clearab** [comment]
docs updated
