### ISSUE TITLE
Add note related to permissions in the manifest schema

### ISSUE THREAD

**Issue by Meghana-MSFT** [MicrosoftDocs/msteams-docs#6078]
[Enter feedback here]
Permissions are deprecated and do absolutely nothing. Please add below note in the manifest schema document.

Note : permissions are deprecated now.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f94a488-d636-92b3-21eb-c88744c8f272
* Version Independent ID: 7b3413f4-9ade-accf-5cb2-83fead11a32a
* Content: [Manifest schema reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema#permissions)
* Content Source: [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/resources/schema/manifest-schema.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Prasad-MSFT** [comment]
@surbhigupta12 - Could you please help here to update the documentation accordingly?
