### ISSUE TITLE
web page in task module can not be loaded?

### ISSUE THREAD

**Issue by paul-cheung** [MicrosoftDocs/msteams-docs#608]
i am playing teams task module, my api response like below(via network tab in browser F12):
```json
{
  "task": {
    "value": {
      "url": "https://dc223076.ngrok.io/UpdateItem/9270bf7e-9512-4508-81e7-9c88d3a42962",
      "height": 510,
      "width": 800,
      "title": "Update Item",
      "fallbackUrl": "https://dc223076.ngrok.io/UpdateItem/9270bf7e-9512-4508-81e7-9c88d3a42962"
    },
    "type": "continue"
  },
  "responseType": "task"
}
```
BTW, it was ok about two weeks ago, any official updates?

**Comment by paul-cheung** [comment]
another issue: the app icon was not displayed properly.
![image](https://user-images.githubusercontent.com/4626647/57070543-5d10e680-6d0a-11e9-85cd-b7ca3009472f.png)

**Comment by 01** [comment]
@paul-cheung  from what ive seen the task module functionality is completely broken for url based modules. Even all the Microsoft example projects the functionality is not working. Deep links works fine though. 


Use this function and just add a Action.OpenUrl card action with the taskmodule link and skip the manual invoke "continue". Should work for you. Task module links are essentially the task continue in link form 


`// Helper function to generate task module deep links
export function taskModuleLink(
    appId: string,
    // tslint:disable:no-inferrable-types
    title: string = "",
    height: string | number = "medium",
    width: string | number = "medium",
    url: string,
    card: any = null,
    fallbackUrl?: string,
    completionBotId?: string): string {
        if ((url === null) && (card === null)) {
            return("Error generating deep link: you must specify either a card or URL.");
        }
        else {
            let cardOrUrl = (card === null) ? `url=${url}` : `card=${JSON.stringify(card)}`;
            let fallBack = (fallbackUrl === undefined) ? "" : `&fallbackUrl=${fallbackUrl}`;
            let completionBot = (completionBotId === undefined) ? "" : `&completionBotId=${completionBotId}`;
            return(encodeURI(`https://teams.microsoft.com/l/task/${appId}?${cardOrUrl}&height=${height}&width=${width}&title=${title}${fallBack}${completionBot}`));
        }
}`

**Comment by Navega** [comment]
> i am playing teams task module, my api response like below(via network tab in browser F12):
> 
> ```json
> {
>   "task": {
>     "value": {
>       "url": "https://dc223076.ngrok.io/UpdateItem/9270bf7e-9512-4508-81e7-9c88d3a42962",
>       "height": 510,
>       "width": 800,
>       "title": "Update Item",
>       "fallbackUrl": "https://dc223076.ngrok.io/UpdateItem/9270bf7e-9512-4508-81e7-9c88d3a42962"
>     },
>     "type": "continue"
>   },
>   "responseType": "task"
> }
> ```
> 
> BTW, it was ok about two weeks ago, any official updates?

I am sharing the same problem, this was ok a few days ago, but now is broken.

Any update?

**Comment by 01** [comment]
@Navega the task module for using invoke continue is completely broken suddenly. I recommend switching to using deeplinks as they are working as expected.

**Comment by Navega** [comment]
> @Navega the task module for using invoke continue is completely broken suddenly. I recommend switching to using deeplinks as they are working as expected for task modules
> 
> Simply have adaptive card have action Action.OpenUrl with the task module link url

Hey Andres, thanks for your suggestion.

But, do you know if it will be fixed soon?

I will research about the deeplinks, thanks again.

**Comment by 01** [comment]
@Navega I have no idea but honestly after switching I wouldnt go back. Deeplinks are useful for more than just the task module and its a much simpler usage.

Essentially all you need is this method to create the url

**Comment by Wajeed-msft** [comment]
This has been fixed. Please re-open if you are still facing this issue.
