### ISSUE TITLE
MS Teams - Cards inserted in compose message area are visible in other chats

### ISSUE THREAD

**Issue by tomqmr** [MicrosoftDocs/msteams-docs#6091]
I'm working on a Teams messaging extension that can send cards by inserting them in the compose message area, then the user can send it manually in the chat.

I used this code sample from the microsoft documentation :

```
class TeamsMessagingExtensionsActionPreview extends TeamsActivityHandler {
  handleTeamsMessagingExtensionSubmitAction(context, action) {
    const data = action.data;
    const heroCard = CardFactory.heroCard(data.title, data.text);
    heroCard.content.subtitle = data.subTitle;
    const attachment = { contentType: heroCard.contentType, content: heroCard.content, preview: heroCard };
    return {
      composeExtension: {
        type: 'result',
        attachmentLayout: 'list',
        attachments: [
          attachment
        ]
      }
    }
  }
}
```
It works well but the issue is that when the card is in the compose box, if I switch to another chat, the card is visible aswell, thus I only wanted the card in my current chat.

Is it a known bug or is there a way to insert the card in the compose box only in the current chat ?

**Comment by Nivedipa-MSFT** [comment]
@tomqmr - We are investigating your query. We will get back to you once we have any update.

**Comment by Nivedipa-MSFT** [comment]
@tomqmr - Engineering team is currently working on the fix. We will inform you once we have further update. Thanks!

**Comment by ChetanSharma-msft** [comment]
@tomqmr - We are following with the engineering team for the updates.
Once the issue has fixed, we will let you know.

**Comment by isimarcbon** [comment]
> @tomqmr - We are following with the engineering team for the updates. Once the issue has fixed, we will let you know.

Any news ? It's critical in our project.

**Comment by Nivedipa-MSFT** [comment]
@isimarcbon - We are checking the status of the bug with engineering team. We will get back to you.

**Comment by ChiluM** [comment]
Hello, 

I have the same issue with my project, 
 Every Teams conversations get the card in the compose area and it comes back almost all the time.

I can't deploy my bot with this bug ! ;-(

Have you got a deadline for us to work on it ?

Have you got an alternate solution or an alternate way of posting the card with an action directly on the channel ? 

Thanks

**Comment by Nivedipa-MSFT** [comment]
@ChiluM - We are checking the status of the bug with the engineering team. We will get back to you.

**Comment by Wajeed-msft** [comment]
> Have you got an alternate solution or an alternate way of posting the card with an action directly on the channel?

@ChiluM - Yes, you can respond to botMessagePreview [send a card directly to the conversation](https://docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/action-commands/respond-to-task-module-submit?tabs=dotnet%2Cdotnet-1#respond-to-botmessagepreview-send).

**Comment by tomqmr** [comment]
Hello, still waiting for the fix, I tried your alternative solution by using botMessagePreview, but it doesn't work really well for what we wanted ... 
First the preview popin has a fixed height so the design isn't really esthetic, plus it seems to not be customable so there is a message and 2 actions that we don't really need/want. 
But the real issue is that we need to send some cards that contains html content (which does not work in adaptive cards, only in hero card) but when I try to send hero card in preview popin, it only displays an empty rectangle so i'm stuck with an adaptive card (yet when reading this : https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference hero cards seems to work with Message extension previews so maybe I missed something) ... then I can get the content from the preview and create an hero card with it and ok it's working but the steps before don't fit our needs.

Do you have any other solutions, or maybe a sample that works with hero card, or even better a date for the fix release ? because this issue is really blocking our project's delivery ...

Thanks.

**Comment by MLEGIsilog** [comment]
Hi,
This issue is still in "Needs triage" step in the dashboard. Our customers cannot use the plugin this way.
When the code will be fixed and in which release please ?

**Comment by Nivedipa-MSFT** [comment]
@tomqmr, @MLEGIsilog - We are checking the status of the fix release with engineering team. We will update you soon.

**Comment by Nivedipa-MSFT** [comment]
@tomqmr - This issue has been fixed internally; we will let you know once it is released publicly.

**Comment by MLEGIsilog** [comment]
The issue has been opened on June, 2022. Could you give mix a public fix version release date please ?

**Comment by Nivedipa-MSFT** [comment]
@MLEGIsilog - We will check the status of public fix with engineering team and inform you once we get any updates from them.

**Comment by ChetanSharma-msft** [comment]
We have checked the status of bug and it will take some more time to be available publicly.
We don't have exact ETA to share but will let you know once it's available publicly.

**Comment by Nivedipa-MSFT** [comment]
@tomqmr - Could you please share your tenant id so that engineering team can enable this feature for this tenant and ultimately it will get rolled out? Thanks

**Comment by tomqmr** [comment]
@Nivedipa-MSFT - Hello, here is our tenant id : a939e833-f06f-4ecd-9c14-b6b5b87085e8

**Comment by MLEGIsilog** [comment]
Hi,

Don’t hesitate to give us a GO to do some internal tests so as to give you a feedback.

Regards

[ISILOG]



LEGER Michaël

[ISILOG]

Responsable Conception & Qualification

***@***.******@***.***>
www.isilog.fr<https://www.isilog.fr>
ZAC de la LORIE - 8 rue Sacco et Vanzetti - 44813 Saint-Herblain

[ISILOG]

     Accueil

: +33 (0)2 40 92 09 72

Support Client

: +33 (0)2 40 92 33 99


[ISILOG]<https://twitter.com/isilog_iws>   [ISILOG] <http://fr.linkedin.com/company/isilog>    [ISILOG] <https://www.youtube.com/user/ISILOG44>




De : tomqmr ***@***.***>
Envoyé : vendredi 10 février 2023 13:56
À : MicrosoftDocs/msteams-docs ***@***.***>
Cc : Michaël LEGER ***@***.***>; Mention ***@***.***>
Objet : Re: [MicrosoftDocs/msteams-docs] MS Teams - Cards inserted in compose message area are visible in other chats (Issue #6091)


@Nivedipa-MSFT<https://github.com/Nivedipa-MSFT> - Hello, here is our tenant id : a939e833-f06f-4ecd-9c14-b6b5b87085e8

**Comment by tomqmr** [comment]
Hi, any update on the activation of the fix for our tenant ?

**Comment by Nivedipa-MSFT** [comment]
@tomqmr - We are checking the status of the activation of the fix for your tenant. We will let you know once we get any updates from them.

**Comment by MLEGIsilog** [comment]
Hi,

We didn’t have any feedback about your fix activation for our tenant.
Is it done ? How could we check ? (with a specific version in the « About » menu …) ?

Could we have some information please ?

Regards

De : Michaël LEGER <>
Envoyé : vendredi 10 février 2023 13:58
À : 'MicrosoftDocs/msteams-docs' ***@***.***>; MicrosoftDocs/msteams-docs ***@***.***>
Cc : Mention ***@***.***>
Objet : RE: [MicrosoftDocs/msteams-docs] MS Teams - Cards inserted in compose message area are visible in other chats (Issue #6091)

Hi,

Don’t hesitate to give us a GO to do some internal tests so as to give you a feedback.

Regards

[ISILOG]



LEGER Michaël

[ISILOG]

Responsable Conception & Qualification

***@***.******@***.***>
www.isilog.fr<https://www.isilog.fr>
ZAC de la LORIE - 8 rue Sacco et Vanzetti - 44813 Saint-Herblain

[ISILOG]

     Accueil

: +33 (0)2 40 92 09 72

Support Client

: +33 (0)2 40 92 33 99


[ISILOG]<https://twitter.com/isilog_iws>   [ISILOG] <http://fr.linkedin.com/company/isilog>    [ISILOG] <https://www.youtube.com/user/ISILOG44>




De : tomqmr ***@***.******@***.***>>
Envoyé : vendredi 10 février 2023 13:56
À : MicrosoftDocs/msteams-docs ***@***.******@***.***>>
Cc : Michaël LEGER ***@***.******@***.***>>; Mention ***@***.******@***.***>>
Objet : Re: [MicrosoftDocs/msteams-docs] MS Teams - Cards inserted in compose message area are visible in other chats (Issue #6091)


@Nivedipa-MSFT<https://github.com/Nivedipa-MSFT> - Hello, here is our tenant id : a939e833-f06f-4ecd-9c14-b6b5b87085e8

**Comment by Nivedipa-MSFT** [comment]
@MLEGIsilog - We got an update from engineering team saying that the feature has enabled for this tenant. Could you please test this and confirm on this? Thanks.

**Comment by MLEGIsilog** [comment]
Hi,

I confirm it does work, the result card is only displayed in the relevant chat conversation.

However, we have some regressions with popin (buttons are not displayed correctly anymore)
For instance :
***@***.***

Have you got some documentation that may give us the origin of this regression ?

Regards

[ISILOG]



LEGER Michaël

[ISILOG]

Responsable Conception & Qualification

***@***.******@***.***>
www.isilog.fr<https://www.isilog.fr>
ZAC de la LORIE - 8 rue Sacco et Vanzetti - 44813 Saint-Herblain

[ISILOG]

     Accueil

: +33 (0)2 40 92 09 72

Support Client

: +33 (0)2 40 92 33 99


[ISILOG]<https://twitter.com/isilog_iws>   [ISILOG] <http://fr.linkedin.com/company/isilog>    [ISILOG] <https://www.youtube.com/user/ISILOG44>




De : Nivedipa-MSFT ***@***.***>
Envoyé : vendredi 17 mars 2023 11:57
À : MicrosoftDocs/msteams-docs ***@***.***>
Cc : Michaël LEGER ***@***.***>; Mention ***@***.***>
Objet : Re: [MicrosoftDocs/msteams-docs] MS Teams - Cards inserted in compose message area are visible in other chats (Issue #6091)


@MLEGIsilog<https://github.com/MLEGIsilog> - We got an update from engineering team saying that the feature has enabled for this tenant. Could you please test this and confirm on this? Thanks.

**Comment by MLEGIsilog** [comment]
It is OK for our tenant.
We have a customer who bought our plugin, could you confirm to me that the fix is now enabled for all the tenant ? (public fix) ?

**Comment by Nivedipa-MSFT** [comment]
@MLEGIsilog - This is not yet released publicly. We will let you know once it is publicly released.

**Comment by MLEGIsilog** [comment]
Any news for this fix public release date (almost one year left) ?

**Comment by Nivedipa-MSFT** [comment]
@MLEGIsilog - We will check the bug status with engineering team and update you soon.

**Comment by Nivedipa-MSFT** [comment]
@tomqmr - We are actively checking the bug status with engineering team. We will let you know once we get any updates on it?

**Comment by MLEGIsilog** [comment]
Hi,
When this fix will be public and definitely closed ? We tested the fix in our tenant ID, it's working BUT ...

We face this regression #8317 : my question is simple : what is the end date for  #6091 and #8317 ?

Delay is being mesured using **years** unit, what is your action plan to close this issue ?
Can you give me the contact of your manager or dev team leader please ???

**Comment by Nivedipa-MSFT** [comment]
@tomqmr - The bug has been fixed. We tested it on the Teams web version. Can you please confirm the fix by testing it once?

**Comment by MLEGIsilog** [comment]
Yes I confirm it is fixed !

[ISILOG]



LEGER Michaël

[ISILOG]

Responsable Conception & Qualification

***@***.******@***.***>
www.isilog.fr<https://www.isilog.fr>
ZAC de la LORIE - 8 rue Sacco et Vanzetti - 44813 Saint-Herblain

[ISILOG]

     Accueil

: +33 (0)2 40 92 09 72

Support Client

: +33 (0)2 40 92 33 99


[ISILOG]<https://twitter.com/isilog_iws>   [ISILOG] <http://fr.linkedin.com/company/isilog>    [ISILOG] <https://www.youtube.com/user/ISILOG44>




De : Nivedipa-MSFT ***@***.***>
Envoyé : vendredi 27 octobre 2023 11:53
À : MicrosoftDocs/msteams-docs ***@***.***>
Cc : Michaël LEGER ***@***.***>; Mention ***@***.***>
Objet : Re: [MicrosoftDocs/msteams-docs] MS Teams - Cards inserted in compose message area are visible in other chats (Issue #6091)


@tomqmr<https://github.com/tomqmr> - The bug has been fixed. We tested it on the Teams web version. Can you please confirm the fix by testing it once?

**Comment by Nivedipa-MSFT** [comment]
@MLEGIsilog - Thanks for confirmation. Could you please share your valuable feedback via [Microsoft Teams Developer Feedback](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR7iCOpS5_b9Nqmwx43u5rtZUOThVR081SllSR05aSDQxQ0tUMDVPTVIxTi4u) link.

**Comment by Nivedipa-MSFT** [comment]
@tomqmr, @MLEGIsilog - We are closing this issue for now. Please feel free to reopen if required.
