### ISSUE TITLE
Docs on start/close conversation event are incorrect

### ISSUE THREAD

**Issue by eoinobrien** [MicrosoftDocs/msteams-docs#6103]
The docs on onCloseConversation and onStartConversation are incorrect. The suggest the function is a parameter on conversations.

```js
microsoftTeams.conversations.onCloseConversation = (conversationResponse) => {
    // console.log(conversationResponse)
};
```

when instead it should be set as parameter of `OpenConversationRequest` on `openConversation`
```js 
microsoftTeams.conversations.openConversation({
    entityId: <<entityId>>,
    subEntityId: <<subEntityId>>,
    channelId: <<channelId>>,
    title: <<title>>,
    conversationId: <<conversationId>>,
    onCloseConversation: (_) => {
        ...
    },
});
```
https://github.com/OfficeDev/microsoft-teams-library-js/blob/main/packages/teams-js/src/private/conversations.ts

Can this be fixed.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 999588a9-9467-501a-e869-14afbed2cbcc
* Version Independent ID: 19f5dc12-eabf-1243-b047-e14d401d2153
* Content: [Create conversational tabs - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/conversational-tabs)
* Content Source: [msteams-platform/tabs/how-to/conversational-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/tabs/how-to/conversational-tabs.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lomeybur**

**Comment by sayali-MSFT** [comment]
@eoinobrien- We are looking into this I will get back to you soon.

**Comment by sayali-MSFT** [comment]
@eoinobrien -We are tried it from our end. Could please tell us what is exact issue the parameters. which things need to be change. When I tried it both I did not find any difference from this.
Could you please share the details which need to be changed?

**Comment by eoinobrien** [comment]
@sayali-MSFT Apologies for the confusion, the issue is more that in the SDK there is no function `onCloseConversation` under the namespace `microsoftTeams.conversations` as suggested by the docs. Instead, it is called is under the `openConversation` function parameters

You can see that onCloseConversation is a member of `OpenConversationRequest` in [the code here](https://github.com/OfficeDev/microsoft-teams-library-js/blob/efa36bf35f295b4ee557ee91f457c302bdf3eae8/packages/teams-js/src/private/conversations.ts#L60).

If one was to follow the docs and paste the code to listen to the on close event into their app they would get syntax errors.

**Comment by sayali-MSFT** [comment]
@surbhigupta12 -Could you please help here to update the document?
In the below Close a conversation section need to replace with the below snippest
Doc-https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/tabs/how-to/conversational-tabs.md#close-a-conversation
instead of below snippest-
```
microsoftTeams.conversations.onCloseConversation = (conversationResponse) => {
    // console.log(conversationResponse)
};
```
Replace this code
```
⁠microsoftTeams.conversations.openConversation({
    ...,
    onCloseConversation: (_) => {
        ⁠// console.log(conversationResponse)
    },
});
```

**Comment by Wajeed-msft** [comment]
@eoinobrien - here is PR for this: https://github.com/MicrosoftDocs/msteams-docs/pull/6233
