### ISSUE TITLE
Lê Kim Quang 

### ISSUE THREAD

**Issue by quanglekim021223** [MicrosoftDocs/msteams-docs#6104]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16fc6b2b-88c3-a68c-80dd-3aaa5ebf9295
* Version Independent ID: 7e29b777-35e7-5682-eb69-ac7aa92b5ad1
* Content: [Overview - Distribute your app - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/apps-publish-overview)
* Content Source: [msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md)
* Service: **msteams**
* GitHub Login: @v-rpatkur
* Microsoft Alias: **surbhigupta**

**Comment by Meghana-MSFT** [comment]
@quanglekim021223 - Could you please share more details about the issue?
