### ISSUE TITLE
Expanding images in adaptive cards doesn't work in teams when the card also has buttons 

### ISSUE THREAD

**Issue by cristianoag** [MicrosoftDocs/msteams-docs#6108]
Following the docs and using "msteams": { "allowExpand": true } for my images in adaptive cards. Everything works as expected if the card doesn't have actions. If you include a simple actions section with a button, then the image expansion icon is not presented anymore. 

This one works ok (we get the expansion icon for the image):

{
    "type": "AdaptiveCard",
    "version": "1.0",
    "body": [
        {
            "type": "Image",
            "url": "https://images/image.jpg"
        },
        {
            "type": "TextBlock",
            "text": "US Sales and Marketing Department",
            "wrap": true
        },
        {
            "type": "TextBlock",
            "size": "extraLarge",
            "weight": "bolder",
            "text": "Test no button",
            "wrap": true,
            "separator": true
        },
        {
            "type": "Image",
            "size": "stretch",
            "url": "https://5anlipyfo26tu.blob.core.windows.net/imageupload/30c711db-2288-4421-8d0d-e342580e1ccc.jpg",
            "altText": "",
            "msteams": {
                "allowExpand": true
            }
        },
        {
            "type": "Image",
            "size": "small",
            "url": "https://m365x257948-cc.azurewebsites.net/api/sentNotifications/tracking/?id=[ID]&key=[KEY]",
            "altText": "",
            "spacing": "small",
            "isVisible": false
        }
    ]
}

This one doesn't work ok, no expansion icon:

{
    "type": "AdaptiveCard",
    "version": "1.0",
    "body": [
        {
            "type": "Image",
            "url": "https://images/image.jpg"
        },
        {
            "type": "TextBlock",
            "text": "US Sales and Marketing Department",
            "wrap": true
        },
        {
            "type": "TextBlock",
            "size": "extraLarge",
            "weight": "bolder",
            "text": "Test with button",
            "wrap": true,
            "separator": true
        },
        {
            "type": "Image",
            "size": "stretch",
            "url": "https://5anlipyfo26tu.blob.core.windows.net/imageupload/799bc6f7-e315-4c4e-a0d0-55d8c6934ca0.jpg",
            "altText": "",
            "msteams": {
                "allowExpand": true
            }
        },
        {
            "type": "Image",
            "size": "small",
            "url": "https://m365x257948-cc.azurewebsites.net/api/sentNotifications/tracking/?id=[ID]&key=[KEY]",
            "altText": "",
            "spacing": "small",
            "isVisible": false
        }
    ],
    "actions": [
        {
            "type": "Action.OpenUrl",
            "url": "https://www.microsoft.com",
            "title": "Btn1"
        }
    ]
}

**Comment by Meghana-MSFT** [comment]
@cristianoag - Could you please confirm if this issue is resolved?
