### ISSUE TITLE
Update the note about App Studio

### ISSUE THREAD

**Issue by ashishguptaiitb** [MicrosoftDocs/msteams-docs#6109]
The note and the warning should not both co-exist in this article. Please merge and edit the contents in the favor only 1 action - either we promote App Studio or we don't promote it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a982542-ae03-2ada-cf71-4d586272e0c3
* Version Independent ID: 9e1fd82b-79e4-1b8d-5367-a8de3d04b3aa
* Content: [Create a command menu for your bot - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/create-a-bot-commands-menu?tabs=desktop%2Cdotnet)
* Content Source: [msteams-platform/bots/how-to/create-a-bot-commands-menu.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/bots/how-to/create-a-bot-commands-menu.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **anclear**

**Comment by sayali-MSFT** [comment]
@ashishguptaiitb-We are looking into this I will get back to you soon.

**Comment by sayali-MSFT** [comment]
@surbhigupta12 - Could you please help us to update the document?
As APP Studio is deprecated so Remove **Note** from the below document section-
https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/create-a-bot-commands-menu?tabs=desktop%2Cdotnet#create-a-command-menu-for-your-bot-using-app-studio

**Comment by v-chetsh** [comment]
@surbhigupta12 - Please help us here to update the contents.

**Comment by v-dreddipogu** [comment]
The issue was already addressed in the following PR.

https://github.com/MicrosoftDocs/msteams-docs/pull/5910

**Comment by surbhigupta12** [comment]
Closing this issue as it is resolved.
