### ISSUE TITLE
[Rendering] Cards overlap on IPad

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#6110]
Copied bug from: https://github.com/microsoft/AdaptiveCards/issues/7483 

**Details from original post:**
### Target Platforms

iOS

### SDK Version

Adpative Card 1.4

### Application Name

Microsoft Teams

### Problem Description

Sometimes cards are not displayed right on iPad. On the screenshot you see how on card cuts the other and hides some of the content.

**IPad**
Version: 15.4.1
Model: IPad Air (4. Generation)

### Screenshots

![unnamed](https://user-images.githubusercontent.com/6587992/170236444-821b3b5e-c362-4846-8d37-a40dda6577bc.png)

### Card JSON

```JSON
Not related to the card.json
```

### Sample Code

_No response_---
#### Document Details

⚠ *Do not edit this section.It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Cards reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **surbhigupta12**

**Comment by Meghana-MSFT** [comment]
Could you please share the JSON of the card?

**Comment by MajaEffenberg** [comment]
The problem is not with one card, but with the presentation of the entire conversation:

- As we know the conversation, we can say that the order of the cards is not right
- The third card also overlaps a little bit with the card above
- The user message are not visible (because the user continued the conversation by sending a message)

**Comment by Meghana-MSFT** [comment]
Thanks for the details. We will check this with sending some cards and see if have a repro.

**Comment by Meghana-MSFT** [comment]
We tried this at our end by sending adaptive cards with lots of data, they are rendering fine on iPad. Could you please update the Teams version and check once again? Please share the Teams version and iPad version you are using.

**Comment by sueess** [comment]
**IPad**
Version: 15.4.1
Model: IPad Air (4. Generation)
Teams Version (when Problem appeared): 4.8.1

We will let you know if the problem is solved as soon our client replies.

**Comment by sueess** [comment]
Our client still has that problem, but we cannot test it ourself. He says, that he can click again on the Chatbot, to remove overlapping. It's annoying but not a breaking bug.

**Comment by Meghana-MSFT** [comment]
Click again means moving the focus away from the bot and then opening that bot?

**Comment by sueess** [comment]
No, just clicking again on the chat contact / chatbot

**Comment by Meghana-MSFT** [comment]
Thanks for confirming. We are checking this with the engineering team. We will get back to you.

**Comment by Meghana-MSFT** [comment]
@sueess - Engineering team has checked with multiple cards with large texts on iPAd but can't reproduce the issue. Could you please provide a user/password that is currently having this issue?

**Comment by sueess** [comment]
@Meghana-MSFT This issue is more then a year old. I love to help you to make your tool better, but then you have to speed up your investigation in the bugs a little bit. I don't know if the bug is still there.
