### ISSUE TITLE
[Feature Request] Using teams actions into Adaptive Cards

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#6116]
Copied bug from: https://github.com/microsoft/AdaptiveCards/issues/7212 

**Details from original post:**
### Problem Statement

I am raising this as feature request as I am unsure this feature is already exists or not.

I wanted to add Let's Meet button into adaptive card where I wanted to open Schedule an event between sender and current user. I have tried giving Action.OpenUrl by giving [Link to schedule meeting](https://teams.microsoft.com/_#/scheduling-form/?isGroup=false&navCtx=multi-window-new-meeting-schedule) . This works fine but its opening in new tab in browser as well as application.  Code sample is given below.

    {
        "type": "Action.OpenUrl",
        "title": "Let's Meet",
        "Url": "https://teams.microsoft.com/_#/scheduling-form/?isGroup=false&navCtx=multi-window-new-meeting-schedule"
    }

What I am looking for is to invoke similar to button given below chat. Is there anyway I can simulate click of that button?

### Proposed solution

As general while we send adaptive card people having doubts or need clarification, they are not scheduling meetings to clarify it. We wanted to give that option in card itself so user can utilize it. 

### Alternatives or Workarounds

_No response_---
#### Document Details

⚠ *Do not edit this section.It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Cards reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **surbhigupta12**

**Comment by Prasad-MSFT** [comment]
@shabbir-dhangot - Thanks for your feedback. We will bring this to notice of appropriate team and act accordingly.
