### ISSUE TITLE
Personal App Reloads during tabs switching

### ISSUE THREAD

**Issue by artsiomrusak** [MicrosoftDocs/msteams-docs#6117]
Hello!

I'm developing Microsoft Teams personal app. I did run into serious issue with it.
I do have a websocket in my Teams personal app which is considered to be working constantly (since user opened an app), unfortunately, once I'm switching to Calendar, Chats or any other tab and returning back to my personal app - it simply reloads losing all state (global js objects, dynamically rendered html, etc).

Could you please tell me is there any way to prevent personal app from loading every time?

Thanks!

**Comment by sayali-MSFT** [comment]
We are looking into this I will get back to you soon.

**Comment by sayali-MSFT** [comment]
@artsiomrusak-Could you please share the refer sample ,So that we can try it from our end?

**Comment by artsiomrusak** [comment]
Hello, @sayali-MSFT 
Unfortunately, there is no way to share the real code with you.

Anyway, the sample is very simple.
_**I've prepared Azure Static App**_ ([Application Link](https://gray-cliff-0700b2e03.1.azurestaticapps.net)) ([Github Repo Link](https://github.com/artsiomrusak/ms-teams-example)) which simply alert you that html page is loaded.
Could you please add this static URL as a Personal App for Microsoft Teams?

_Once you switch from Personal App to Calendar and back, you'll always see the alert notifying that the page is loaded._

The goal is pretty simple - just prevent reload of the application.

Thanks a lot for you help!

**Comment by sayali-MSFT** [comment]
@artsiomrusak - It's a Bydefault behaviour. There is no any programmatically way to prevent from reloading .
