### ISSUE TITLE
[Localize your app - Teams] Manifest version needs to be the same as global manifest version

### ISSUE THREAD

**Issue by svrooij** [MicrosoftDocs/msteams-docs#6122]
Today our application did not pass validation and one of the reasons was that the manifest version for a language did not match the version of the main manifest.

On this page should be a note saying just that!

And all sample code should be updated to the latest version of the manifest, since that is required to be used anyway.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f55e52a-5fc4-7fcb-0e1e-946bff5aaee4
* Version Independent ID: b6c559fb-8512-575b-4fed-ebe1457e890e
* Content: [Localize your app - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/apps-localization)
* Content Source: [msteams-platform/concepts/build-and-test/apps-localization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/build-and-test/apps-localization.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Wajeed-msft** [comment]
@svrooij - Thank you for taking time to report this issue. We will add a note in the documentation to reflect this. 

@surbhigupta12  - could you please help here with doc change? 
@AbhijeetThakur-msft - could you please help to check sample code where latest manifest versions are not updated?
