### ISSUE TITLE
clearly separate topics - split to two pages 

### ISSUE THREAD

**Issue by Josverl** [MicrosoftDocs/msteams-docs#6141]
The current structure is confusing as it intermingles two different features: 
- tab removal 
- tab reconfiguration 

current structure: ...
 1. Create a removal page
 2. Enable your tab to be reconfigured after installation
 3. Create a tab removal page for your application
 ...  more detail about the tab removal 

I would suggest to move `2. Enable your tab to be reconfigured after installation` to a separate page ,  
or to clearly set it apart and mention both in the page title 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd464705-49f1-e180-8ef3-a6be50527cd6
* Version Independent ID: 54aca1c7-403d-6da6-0e25-98194da71d65
* Content: [Create a tab removal page - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/removal-page?tabs=teamsjs-v2)
* Content Source: [msteams-platform/tabs/how-to/create-tab-pages/removal-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/tabs/how-to/create-tab-pages/removal-page.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Prasad-MSFT** [comment]
@surbhigupta12 - Could you please help here to update the doc accordingly if required?
