### ISSUE TITLE
Meeting request deeplink cannot set StartTime and EndTime on iOS Teams App

### ISSUE THREAD

**Issue by yuukitakeuchi** [MicrosoftDocs/msteams-docs#6148]
I'm trying to open meeting request using Microsoft Javascirpt SDK: microsoftTeams.executeDeepLink().
When on iOS Teams app the meeting screen opens, but the StartTime and EndTime of the meeting specified by the deeplink are not set.
It works on android devices.

DeepLink URL
https://teams.microsoft.com/l/meeting/new?subject=&startTime=2022-06-09T16%3A30%3A00%2B09%3A00&endTime=2022-06-09T17%3A30%3A00%2B09%3A00&attendees=%27
Repro when via javascript sdk. If just open the link, it works fine.

iOS version 15.5
Teams App version 4.10.0 build 4.10.77.2022102807/0606 (general)
teams-js version 1.11.0

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: cf973de1-6c01-82b3-8dfc-2efbd5e65e77
* Version Independent ID: 732d3289-2775-0eaf-fca7-43eca2ccc03e
* Content: [microsoftTeams module - Teams](https://docs.microsoft.com/ja-jp/javascript/api/@microsoft/teams-js/microsoftteams?view=msteams-client-js-1.12.1#@microsoft-teams-js-microsoftteams-executedeeplink)
* Content Source: [nodejs/teams-1121/docs-ref-autogen/@microsoft/teams-js/microsoftTeams.yml](https://github.com/OfficeDev/msteams-client-docs-ref-typescript/blob/live/nodejs/teams-1121/docs-ref-autogen/@microsoft/teams-js/microsoftTeams.yml)
* Product: **msteams**
* GitHub Login: @charlesprakash
* Microsoft Alias: **o365devx**

**Comment by v-chetsh** [comment]
@yuukitakeuchi - We will investigate on it and get back to you.

**Comment by sayali-MSFT** [comment]
@yuukitakeuchi -We got the related tread here -https://github.com/OfficeDev/microsoft-teams-library-js/issues/1050
please have look into this.

Could you please share the sample you are referring?

**Comment by sayali-MSFT** [comment]
@yuukitakeuchi - We will check it our end and let you know.

**Comment by sayali-MSFT** [comment]
@yuukitakeuchi - We are checking the scenario on IOS device. It's working fine from our end. Could you please update the teams version and check it once?
![MicrosoftTeams-image (50)](https://user-images.githubusercontent.com/93527375/175349386-46f0b994-e73c-426b-8cd9-809787a9a9fe.png)
![MicrosoftTeams-image (49)](https://user-images.githubusercontent.com/93527375/175349397-f36e022d-84ad-4ef2-a88b-977a5bf4b343.png)

**Comment by sayali-MSFT** [comment]
@yuukitakeuchi -Did you get chance to check?

**Comment by yuukitakeuchi** [comment]
@sayali-MSFT  Thank you for your information.
I have confirmed that the latest Teams version does not reproduce this behavior!!
And now checking with some others who were reproducing it.

It seems that the version of the Teams app has been upgraded, was this fixed in the upgrade?

**Comment by yuukitakeuchi** [comment]
I have confirmed that all users who were reproducing the problem are no longer reproducing it.
