### ISSUE TITLE
Add guidance for handling errors in conversation events-- do not reply to the conversation directly

### ISSUE THREAD

**Issue by aosolis** [MicrosoftDocs/msteams-docs#6152]
Add guidance to this page that when the bot encounters an error while handling these activities, it should not post messages directly to the conversation, because the errors look like random messages with no context.

<img width="630" alt="image" src="https://user-images.githubusercontent.com/767208/172960843-7a337b50-f4d0-4415-b16c-1f7d18f7d392.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a6d00a4-dd28-33c4-002e-2e8e7c653ce2
* Version Independent ID: 0856927a-25f4-b1e0-5f1b-d55dc61796f3
* Content: [Conversation events - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/subscribe-to-conversation-events?tabs=dotnet)
* Content Source: [msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md)
* Service: **msteams**
* GitHub Login: @WashingtonKayaker
* Microsoft Alias: **anclear**

**Comment by v-chetsh** [comment]
@surbhigupta12 - Can you please help us here to update the documentation?

**Comment by ChetanSharma-msft** [comment]
Raised a PR for the code changes here: https://github.com/OfficeDev/Microsoft-Teams-Samples/pull/661

**Comment by ChetanSharma-msft** [comment]
Hello @v-sdhakshina - Could you please help us here to update the doc like below:

While in development phase, it's always helpful to send the meaningful messages in conversations which provide more details about specific error for better debugging. However In production environment, you should consider logging this to Azure Application Insights. Visit https://aka.ms/bottelemetry to see how to add telemetry capture to your bot.
