### ISSUE TITLE
Describe how to handle status codes from bot APIs

### ISSUE THREAD

**Issue by aosolis** [MicrosoftDocs/msteams-docs#6153]
This page talks about 429 status code specifically. We need documentation on all the status codes that can be returned, and how bots should handle them.

We have a partial list of status codes here. It is missing some codes that we return in practice, like 502.
https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-messages?tabs=dotnet#status-code-responses

It's also missing:
1. Troubleshooting -- for example, what are possible reasons for 401+BotNotRegistered?
2. Our recommendation for how to handle the error-- retry, or is this a permanent condition? if retry, how often?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a6d00a4-dd28-33c4-002e-2e8e7c653ce2
* Version Independent ID: 0856927a-25f4-b1e0-5f1b-d55dc61796f3
* Content: [Conversation events - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/subscribe-to-conversation-events?tabs=dotnet)
* Content Source: [msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md)
* Service: **msteams**
* GitHub Login: @WashingtonKayaker
* Microsoft Alias: **anclear**

**Comment by v-chetsh** [comment]
@surbhigupta12 - Can you please help us here to update the documentation?
