### ISSUE TITLE
How to pass custom query parameters to the tab using deep link?

### ISSUE THREAD

**Issue by bangndnguyen** [MicrosoftDocs/msteams-docs#616]
I want to pass in some extra information to the content tab. Could it be done? If so, how?
For example: my content website is expecting some thing like `www.mywebsite.com/hello?myName=john`

**Comment by Wajeed-msft** [comment]
You can pass addional information to your tab in a [deep link](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/deep-links#generating-a-deep-link-to-your-tab) assigned in _subEntityId_ which is part of context object. This context can be retrieved by using the [Microsoft Teams JavaScript library](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/deep-links#consuming-a-deep-link-from-a-tab).

Ex: `https://teams.microsoft.com/l/entity/fe4a8eba-2a31-4737-8e33-e5fae6fee194/tasklist123?webUrl=https://tasklist.example.com/123/456&label=Task 456&context={"subEntityId": "task456"}`

**Comment by bangndnguyen** [comment]
Hi @Wajeed-msft,
Thanks for the feedback. So it means that I can pass anything into this context object, not limited to predefined properties?

**Comment by Wajeed-msft** [comment]
Only predefined properties can be retrieved using [microsoftTeams.getContext()](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/tabs/tabs-context#getting-context-by-using-the-microsoft-teams-javascript-library). Please use _subEntityId_ which is specifically added to pass additional information to tab. The _subEntityId_ is a string and you are free to pass json string if needed.

Note: Ensure that all your parameters are properly URI encoded.

**Comment by bangndnguyen** [comment]
When I used this deeplink from the docs:

`https://teams.microsoft.com/l/entity/fe4a8eba-2a31-4737-8e33-e5fae6fee194/tasklist123?webUrl=https://tasklist.example.com/123/456&label=Task 456&context={"subEntityId": "task456"}`

I got 'Bad Request' and `https://teams.microsoft.com/null` in the browser
