### ISSUE TITLE
Unable to send proactive personal chat messages to existing chats

### ISSUE THREAD

**Issue by bandtank** [MicrosoftDocs/msteams-docs#6161]
This page does not describe how to send a personal chat message to an existing chat. It doesn't really explain how to send the first one with any amount of discernible detail, but the high-level explanation is admittedly present. I have no idea after reading the documentation how to continue conversations in personal, group, or channel chats. After hours of attempting to do it through Postman, I am receiving 2xx responses, but nothing appears in Teams in any of the available contexts. The examples that rely on the bot framework abstract every relevant detail, which is what the documentation needs to fully enumerate.

<img width="706" alt="image" src="https://user-images.githubusercontent.com/1170415/173067936-6d035125-caf5-49c3-ab5d-d5ab4f18055e.png">
<img width="456" alt="image" src="https://user-images.githubusercontent.com/1170415/173068008-448b9823-b647-4159-9706-6fe69ef6754b.png">

How do I send a chat message to an existing personal chat using the configuration shown above?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ad9f167-7d29-f933-7b47-60bd744899b1
* Version Independent ID: 8097fcbd-adcc-ce49-a378-426c65af9296
* Content: [Send proactive messages - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/send-proactive-messages?tabs=dotnet)
* Content Source: [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/bots/how-to/conversations/send-proactive-messages.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **anclear**

**Comment by bandtank** [comment]
Good lord. After tons of hours of reading stackoverflow answers from non-Microsoft employees to this exact same question, I finally made some progress, but I still need answers to my questions because I can't figure out how to reply directly to a person in a 1:1 chat.

For anyone else who is confused by the terrible documentation, start [here](https://github.com/microsoft/botframework-sdk/blob/main/specs/botframework-activity/botframework-activity.md). CLEARLY that should be plastered all over the place because it is critical to how the framework's protocol actually works. It's actually wrong in several places, but it's a good start. The [proactive message documentation](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/send-proactive-messages?tabs=json#samples) conveniently says everything about the protocol is out of scope, but it fails to, you know, explain where to go if you need that level of detail.

Then visit [this](https://stackoverflow.com/questions/65479866/microsoft-teams-bot-replytoid-seems-to-be-ignored) thread to read about how the `replyToId` is ignored. Wonderful. You still need it, but it has to be inserted into the URL. Surprise! That is mentioned exactly nowhere in the Microsoft documentation, at least in an obvious way. Stackoverflow users come to the [rescue](https://stackoverflow.com/questions/61970671/reply-to-message-as-threaded-response-in-ms-teams-using-azure-bot-sevices) again. In short, put it in the URL after the `conversationId`. See below for more details. NOTE TO MICROSOFT: You could have created this tiny amount of clear and concise documentation for your users in 10 minutes. Instead, you've let hundreds (or probably thousands) of us beat our heads against the wall for hours to piece together the requirements. Thanks.

Get an access token after registering your bot in Azure:
* The URL is `https://login.microsoftonline.com/botframework.com/oauth2/v2.0/token`
* No headers are necessary beyond what Postman inserts by default
* The scope defines the audience of the access token. This is important if you need to query things like Graph because the scope would be different. The scope shown in the following image is specific to Teams.
<img width="742" alt="image" src="https://user-images.githubusercontent.com/1170415/173191329-0dd2b8ea-13fe-48e6-b8f4-95c7dbeffbf2.png">
The response will look like this:
<img width="496" alt="image" src="https://user-images.githubusercontent.com/1170415/173191630-1101fe6d-51e7-4fca-b5f2-5c648a7a9a3b.png">

Create a new thread in channel:
* You need two headers: `Content-Type: application/json` and `Authorization: Bearer <token>`.
* The request data should look like this:
```
{
  "type": "message",
  "bot": {
    "id": "28:{{bot_id}}",
    "name": "{{bot_name}}"
  },
  "conversation": {
    "conversationType": "channel",
    "id": "19:{{channel_id_it}}"
  },
  "text": "New Conversation {{request_counter}}"
}
```
* The URL is `https://smba.trafficmanager.net/in/v3/conversations/19:{{channel_id_it}}/activities`. See below for the value of the channel ID, which I stored in a variable called `channel_id_it` because my channels' name is `IT`. I have no idea why you need to add `activities` at the end of the URL because the URL is not explained as far as I can tell. Trial and error!
* `bot.id` begins with `28:` for some unknown reason and the rest is the Azure application ID. it will look something like this: `d3fe362a-xxxx-xxxx-xxxx-1fa9a2e902cc`
* `bot.name` is not required, but you should populate it for other programs that may need the information.
* `conversation.id`, which is actually the channel's ID in this case, begins with `19:` for some unknown reason. I don't know where to find the channel ID other than inspecting an incoming request from Teams to the bot. I started a new conversation with my bot by mentioning it. The channel ID will look something like this: `iVS6WwdGbSRTnVcr61nriK9Aw6d0fWOg0jOUV-2l-vU1@thread.tacv2`. I store the channel's ID in `channel_id_it`.
* `text` is required and `textFormat` is not if you are sending a plain message.
<img width="750" alt="image" src="https://user-images.githubusercontent.com/1170415/173191354-5df23a44-179c-4fef-8cfa-b4f3510e1ebf.png">
The response will look like this:
<img width="438" alt="image" src="https://user-images.githubusercontent.com/1170415/173191609-35a55c58-bee3-4e61-981d-b4dec6f9ddb7.png">

Here's the juice. Replying to the conversation requires you to do the following:
* The URL is `https://smba.trafficmanager.net/in/v3/conversations/19:{{channel_id_it}};messageid={{replyToId}}/activities` where `channel_id_it` has not changed and `replyToId` is the value of the `id` field in the response from the previous request.
* The documentation says to add the `replyToId` field in the body. Knock yourself out, but it is ignored because Microsoft. It must appear in the URL as seen above and below.
* This request returns an `id`, but I don't know why or what to do with it.
<img width="842" alt="image" src="https://user-images.githubusercontent.com/1170415/173191825-032a7188-2b78-44da-b7eb-f47c4f14a214.png">

**Comment by bandtank** [comment]
Alright, through no help from the Microsoft documentation, I figured it out how to send a personal chat. Group chat remains elusive, but that's not something I care to solve because I don't need it.

The trick is figuring out the `conversationId` for the user. There is one per user as explained in the documentation, but getting it is not as simple as it should be. The easiest way I've found is to pretend like you are creating the conversation even if it already exists. If it doesn't already exist, then you'll make a new one, so either way it works.

Before you can send a personal chat, you need two things:
* The unique user ID associated with the bot. It's not the azure object ID or anything else; it's specific to each bot in each tenant, which is annoying, but you have to deal with it. The `bot_user_id` in my examples is the unique user ID, which will look like this: `29:1oMztUmXDLcAm7WwesEO8-CArhQoB-8AbrjzCDTbwWBE_C8ktWyoZkMQWXBJRhdwo5U5sWtv3sJHRkPnwRlmKdw`. You can also get it by inspecting incoming requests from the bot (see my original post and search for `29:...`.
* The unique conversation ID. That, too, can be found in incoming requests in `coversation.id`. It is in the form of `a:1o8WSkl...`. You can also get this by creating a conversation if one does not exist or pretending like you are creating one if it does exist. The former will make a new chat and return the conversation ID while the latter will simply return the existing conversation ID.

If you want to retrieve the `bot_user_id` for every member of a team, here is one way to do it:
<img width="747" alt="image" src="https://user-images.githubusercontent.com/1170415/173197333-c5fdc914-243e-40b4-bc0b-59abe6e9d1f5.png">

To create or retrieve the conversation ID for a personal chat with a user, send a request like this:
* Notice the URL does not have any parameters.
* The other values are in my prior posts.
<img width="559" alt="image" src="https://user-images.githubusercontent.com/1170415/173197271-db7e8d57-534c-474f-aeef-647278e49295.png">
Upon success, a new personal chat will be created or the ID of the existing personal chat will be returned. Either way, the response looks like this:
<img width="419" alt="image" src="https://user-images.githubusercontent.com/1170415/173197508-877bdf7c-7ee7-43c6-a8e4-655e01ed2b86.png">

The magic lies, again, in the cryptic URL which is never described anywhere because Microsoft documentation is the worst thing humanity has ever created. Put the conversation ID (`a:1o8WSkl...`) in the URL and fill in the other fields. It's much easier than the documentation suggests.
<img width="678" alt="image" src="https://user-images.githubusercontent.com/1170415/173197532-5dd72774-2a2f-4660-8a52-d32e34db7668.png">

**Comment by Prasad-MSFT** [comment]
Glad that you found workaround and it's really informative and helpful. Thanks!
