### ISSUE TITLE
Action Command documentation doesn't agree with app manifest example

### ISSUE THREAD

**Issue by TrevorJoelHarris** [MicrosoftDocs/msteams-docs#6164]
The documentation for the parameters property clearly says "This property describes the static list of parameters for the command. Only use when fetchTask is false." The App Manifest example at the bottom of the page includes a snippet that sets fetchTask to true but also defines the parameters property.

I would *guess* that the first command in the app manifest example just needs to have fetchTask set to false but honestly I don't know. The main app manifest schema page (https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema) also includes similarly incorrect examples.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: efcdf768-1513-2249-b344-bf38ef64c70d
* Version Independent ID: 415b5d57-2d41-9540-55a7-2a33a4315e37
* Content: [Define message extension action commands - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/action-commands/define-action-command?tabs=AS#create-an-action-command-manually)
* Content Source: [msteams-platform/messaging-extensions/how-to/action-commands/define-action-command.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/messaging-extensions/how-to/action-commands/define-action-command.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **anclear**

**Comment by v-chetsh** [comment]
@TrevorJoelHarris - We will investigate on it and get back to you.

**Comment by sayali-MSFT** [comment]
@surbhigupta12 - Could you please help here to update the document?
In the Code snippets section please replace **"fetchTask": false**  where  "fetchTask": true 
Doc-https://docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/action-commands/define-action-command?tabs=AS#app-manifest-example

Also in manifest schema code snippest  please replace **"fetchTask": false**  where  "fetchTask": true
Doc-https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema#sample-full-manifest
