### ISSUE TITLE
[Android] month name not rendering correctly in date function 

### ISSUE THREAD

**Issue by matthiasdilger** [MicrosoftDocs/msteams-docs#6168]
Bot sends this card:

```
{
        "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
        "type": "AdaptiveCard",
        "version": "1.2",
        "msTeams": {
          "width": "Full"
        },
        "body": [
          {              
            "type": "TextBlock",
            "size": "Medium",
            "weight": "Bolder",
            "text": "Lorem ipsum"
          },
          { 
            "type": "TextBlock",
            "text": "Lorem ipsum",
            "wrap": true
          }              
        ],
        actions: [{
        "type": "Action.ShowCard",
        "title": "Details",
        "card": {
          "type": "AdaptiveCard",
          "body": [{
            "type": "FactSet",
            "facts": [
              {
                "title": "Fact1:",
                "value": "Fact1"
              },
              {
                "title": "Fact2:",
                "value": "{{DATE(2017-02-14T06:00:00Z, SHORT)}}"
              }
            ]
          }]
        }
      }]
}
```

User receives card and presses Details button. Android app does not render the month correctly, displays M02 instead of Feb:
![Screenshot_20220611-162553](https://user-images.githubusercontent.com/5625718/173180257-5e722b56-ab0a-4a56-b1a0-008153a614ff.png)

Edit: Works fine on desktop, web and iOS

**Comment by Nivedipa-MSFT** [comment]
@matthiasdilger - We are able to repro this issue and we have raised a bug for it. We will let you know once we get updates on it.

**Comment by Nivedipa-MSFT** [comment]
@matthiasdilger - We are checking this with engineering team. We will let you know the updates.

**Comment by Nivedipa-MSFT** [comment]
@matthiasdilger - We are actively checking the status of the bug fix with engineering team. We will let you know once we get an update from them.

**Comment by matthiasdilger** [comment]
This issue has been fixed, thanks!
