### ISSUE TITLE
[iOS] app shows empty notification instead of card summary

### ISSUE THREAD

**Issue by matthiasdilger** [MicrosoftDocs/msteams-docs#6169]
Bot receives a command in a group chat and sends the following card (node js):

```
let card = {
        "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
        "type": "AdaptiveCard",
        "version": "1.2",
        "msTeams": {
          "width": "Full"
        },
        "body": [
          {            
            "type": "TextBlock",
            "wrap": true,
            "text": "Lorem ipsum lorem ipsum"
          },
          {            
            "type": "TextBlock",
            "wrap": true,
            "text": "Lorem ipsum lorem ipsum"
          }
        ]
      };

card = CardFactory.adaptiveCard(card);
await context.sendActivity({ attachments: [card], summary: "👋 Hello hello!"});
```

iOS app shows an empty system notification:
![99900](https://user-images.githubusercontent.com/5625718/173181405-682ba7b8-9b63-4915-8859-cda88be958e7.jpg)

Expected result: The summary "👋 Hello hello!" should be shown in the notification. Works fine on desktop, web and Android.

**Comment by v-chetsh** [comment]
@matthiasdilger - We will investigate on it and get back to you.

**Comment by Nivedipa-MSFT** [comment]
@matthiasdilger - We have already raised a bug for it. We will let you know once we get updates on it.

**Comment by matthiasdilger** [comment]
This issue has been fixed, thanks

**Comment by matthiasdilger** [comment]
Sorry, issue still present. Sorry, got too excited.

**Comment by Nivedipa-MSFT** [comment]
@matthiasdilger - We are checking the status of the buf with the engineering team. We will let you know once we have any updates on it.

**Comment by ChetanSharma-msft** [comment]
Hello @matthiasdilger - Sorry for delay in response.
We are actively checking the updates on this issue with engineering team and let you know, if we have any.

**Comment by matthiasdilger** [comment]
@Nivedipa-MSFT Confirming as fixed, thanks

**Comment by Nivedipa-MSFT** [comment]
@matthiasdilger - Could you please share your valuable feedback via [Microsoft Teams Developer Feedback](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR7iCOpS5_b9Nqmwx43u5rtZUOThVR081SllSR05aSDQxQ0tUMDVPTVIxTi4u) link.
