### ISSUE TITLE
The bot does not display a popup message box responding to submitAction

### ISSUE THREAD

**Issue by maxon-adc** [MicrosoftDocs/msteams-docs#617]
When I receive a submitAction request, my bot responds with:

{
  "task": {
    "value": "Hello there",
    "type": "message"
  },
  "responseType": "task"
}

However, instead of displaying a popup message box, task module displays an error: "Something went wrong, please try again later.".

**Comment by Gousia-MSFT** [comment]
@maxon-adc Could you please try [Task Module Sample](https://github.com/OfficeDev/microsoft-teams-sample-task-module-csharp) and share a screenshot of the issue you are facing?

**Comment by Wajeed-msft** [comment]
Please re-open with repro steps and screenshots.
