### ISSUE TITLE
[Designer] Bug Adpative card values disappears when switch between tabs in MS Teams

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#6174]
Copied bug from: https://github.com/microsoft/AdaptiveCards/issues/7492 

**Details from original post:**
### Problem Description

when user types somthing and before clicking submit button if he changes the chat Adpative card values disappears in MS Teams when he comes back to the chat

### Card JSON

```JSON
{
"$schema": "http://adaptivecards.io/schemas/adpative-card.json",
"type": "AdpativeCard",
"version":"1.3",
"body":[
{
"type": "Input.text",
"lable": "Comments"
}
],
"actions":[
"type": "Action.Submit",
"tittle": "Submit",
"data" :{
   "id":"Test"
}
]
}
```

### Screenshot

_No response_---
#### Document Details

⚠ *Do not edit this section.It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Cards reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **surbhigupta12**

**Comment by v-chetsh** [comment]
@midhunkumar22 - We will investigate on it and get back to you.

**Comment by sayali-MSFT** [comment]
@midhunkumar22 - We are able to repro that issue , We have raised bug for the same and concerned team is looking into it. We will inform you once we get any update.

**Comment by sayali-MSFT** [comment]
@midhunkumar22 -Currently, App Studio is deprecated. As such this use-case is no longer supported, since its successor Teams Developer Portal is not embeddable in a Teams tab.
