### ISSUE TITLE
connect-microsoftteams by Certificate based authentication is supported?

### ISSUE THREAD

**Issue by Ananda-Gedela** [MicrosoftDocs/msteams-docs#6180]
Details:
Powershell module: MicrosoftTeamsPowerShell
Cmdlet: Connect-MicrosoftTeams
Description:
Is Certbased authentication is supported for teams? If yes how to connect-microsoftteams with certbased authentication.

**Comment by v-chetsh** [comment]
@Ananda-Gedela - We will investigate on it and get back to you.

**Comment by Meghana-MSFT** [comment]
@Ananda-Gedela - It's not supported currently. You can suggest this feature at [Microsoft Uservoice](https://feedbackportal.microsoft.com/feedback/forum/ad198462-1c1c-ec11-b6e7-0022481f8472).

**Comment by Ananda-Gedela** [comment]
@Meghana-MSFT 
ok thanks

**Comment by Meghana-MSFT** [comment]
We are closing this issue for now, please feel free to reopen if you face any issues again.

Thanks
