### ISSUE TITLE
Accurate manifest change for adding device permissions?

### ISSUE THREAD

**Issue by JuAn-Kang** [MicrosoftDocs/msteams-docs#6190]
[Enter feedback here]

Adding camera access did not work with `media`, but trying to add permissions via the checkboxes in the developer portal adds a `Media` in the array instead. Is this field case sensitive? 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8890a6bd-1ca5-ac41-b5af-7087dba699e5
* Version Independent ID: c35acbcc-b3b3-ff59-6623-96ff0c691bf6
* Content: [Integrate media capabilities - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/mobile-camera-image-permissions)
* Content Source: [msteams-platform/concepts/device-capabilities/mobile-camera-image-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/device-capabilities/mobile-camera-image-permissions.md)
* Service: **msteams**
* GitHub Login: @Rajeshwari-v
* Microsoft Alias: **lajanuar**

**Comment by Nivedipa-MSFT** [comment]
@JuAn-Kang - We are investigating your query. We will get back to you once we have any update.
