### ISSUE TITLE
[Mobile] [Doc-Bug]Scan barcode capability not working in side panel app

### ISSUE THREAD

**Issue by SubbaReddi** [MicrosoftDocs/msteams-docs#6204]
Hi Team,
Scan barcode capability is not working in side panel app in mobile. It is working fine in Premeeting scope.
I see following error: This call is not allowed in the "sidepanel" context

If it is not supported, please add note to the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19804dba-009f-2eb1-cc7f-1e0fabbebb6b
* Version Independent ID: a9373e78-b3c9-7182-d253-5ac8d8988936
* Content: [Request device permissions for your Microsoft Teams app - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?tabs=mobile)
* Content Source: [msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/device-capabilities/native-device-permissions.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Prasad-MSFT** [comment]
@surbhigupta12 - Could you please help here to update the doc accordingly?

**Comment by Prasad-MSFT** [comment]
@SubbaReddi - Its mentioned in doc:
Currently, Teams doesn't support device permissions for multi-window apps, tabs, and the meeting side panel.
Ref: https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?tabs=mobile#native-device-permissions

**Comment by SubbaReddi** [comment]
Thank you Prasad. As it is already part of documentation, we can close this request.
