### ISSUE TITLE
Inconsistent app studio / developer portal behavior

### ISSUE THREAD

**Issue by suz7777** [MicrosoftDocs/msteams-docs#6205]
When publishing a new Teams application using the manifest editor, the pending approval message appears and the teams admin will be asked to approve the new version of the application.

When I am in the developer portal, if I make a change to the app tabs and/or bot, I submit the application for approval - but it doesn't appear in the teams admin for approval.  What happens is the "publish to your org" tab shows 'published'.  

when you go to https://admin.teams.microsoft.com/policies/manage-apps it shows 1 updated custom app but when you drill to the newly updated app, the new version appears and shows published.

I would prefer the original behavior if possible.

**Comment by ChetanSharma-msft** [comment]
Hello @suz7777 - Thanks for reporting your issue.
We will look into your issue and get back to you.

**Comment by Meghana-MSFT** [comment]
@suz7777 - Apologies for delays in response. Could you please let us know if you are still facing the issue so that we can share this feedback with the engineering team.
