### ISSUE TITLE
Steps to deploy TeamsFx sample to Azure web app

### ISSUE THREAD

**Issue by SubbaReddi** [MicrosoftDocs/msteams-docs#6210]
Once TeamsFx tab is created, we can deploy to azure storage account using Teams toolkit default provided options like Provision in the cloud-> Deploy to cloud -> Publish to Teams

But if the requirement is to deploy to azure web app manually, don't see steps to follow the same.
Observed working fine by following below steps in high level. So, Can you add the documentation to include the same:

> Create a SSO-enable tab
> Provision
> Run npm install and npm run build:teamsfx:dev in tabs/ folder
> Create a windows app service (same OS with your machine)
> Run $ az webapp up --name <appServiceName> --html --subscription <subscription> in tabs/build/ folder
> Modify templates/azure/provision/frontendHosting.bicep
>  Provision again. Teams Toolkit will update AAD and manifest for you.
Find your appPackage.dev.zip in build/appPacakge folder and add to Teams

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e572f611-ae28-a06a-a66a-7d15c497496d
* Version Independent ID: e572f611-ae28-a06a-a66a-7d15c497496d
* Content: [TeamsFx Command Line Interface - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-cli)
* Content Source: [msteams-platform/toolkit/TeamsFx-CLI.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-CLI.md)
* Service: **msteams**
* GitHub Login: @MuyangAmigo
* Microsoft Alias: **zhany**

**Comment by Prasad-MSFT** [comment]
@surbhigupta12 - Could you please help here to add contents to the doc accordingly?
