### ISSUE TITLE
[Question] If SSO bots in group chat possible?

### ISSUE THREAD

**Issue by qianwenyuan** [MicrosoftDocs/msteams-docs#6211]
[Enter feedback here]
Hi, I try SSO bots recently. Now I want to add a SSO bot into a group chat or a team, which can send OAuthCards to every person in the group chat to get their tokens. I wonder if it is possible?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9549caa9-99a2-2568-19a5-f21a79292e2f
* Version Independent ID: f2100d03-b88a-34b2-44a2-935231e89db0
* Content: [Single sign-on support for bots - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/authentication/auth-aad-sso-bots#step-by-step-guide)
* Content Source: [msteams-platform/bots/how-to/authentication/auth-aad-sso-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/bots/how-to/authentication/auth-aad-sso-bots.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by sayali-MSFT** [comment]
@qianwenyuan - We are looking into this I will get back to you soon.

**Comment by sayali-MSFT** [comment]
@qianwenyuan -As per document "**The app must be installed in personal scope for SSO support**."
It is not support to group chat.
Ref Doc-https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/authentication/auth-aad-sso-bots#bot-sso-at-runtime

**Comment by ChetanSharma-msft** [comment]
@qianwenyuan - Can you please check and confirm?
