### ISSUE TITLE
Can't find teams or group using GRAPH

### ISSUE THREAD

**Issue by isaacdchan** [MicrosoftDocs/msteams-docs#622]
Happy Friday. End goal is to fetch all members of a team.

`/v1.0/me/joinedTeams` - returns a resource does not exist

`/v1.0/me` - returns a suspiciously sparse user profile

<img width="484" alt="Capture" src="https://user-images.githubusercontent.com/33741008/57172632-6025d880-6dd7-11e9-8600-c87550622de9.PNG">

I then manually extracted the team_id from the team's shareable link and tried

`/v3/conversations/fc5b01dd-15e1-4102-8b18-12863e77022f/members` - returns 'Authorization has been denied'

I used the same email for the requests and Teams. Is it possible it's being treated as two emails hence the disconnect? I could be making an obvious mistake and appreciate any help.

**Comment by Wajeed-msft** [comment]
@isaacdchan - Seems like you are using Microsoft Teams Free account (isaac.d.chan_gmail.com). It appears you are calling the graph with a Microsoft Account (aka MSA) versus an Azure Active Directory (Azure AD) account. Microsoft Graph APIs for Teams do not support MSA accounts, only Azure AD accounts.

Could you please use `https://login.microsoftonline.com/TENANT_ID/oauth2/authorize?...` and not `https://login.microsoftonline.com/common/oauth2/authorize?...` as documented in [FAQ](https://docs.microsoft.com/en-us/microsoftteams/platform/troubleshoot/faq#teams-apps-and-authentication-with-guest-users-and-microsoft-teams-free)? 
For this you could follow the steps provided in [Get access on behalf of a user](https://docs.microsoft.com/en-us/graph/auth-v2-user?toc=.%2Fref%2Ftoc.json&view=graph-rest-1.0) documentation. 

I am not sure if [Freemium](https://products.office.com/en-us/microsoft-teams/free) is requirement for you. If not then you can sign up for the [Office 365 Developer program](https://dev.office.com/devprogram) to get a free one-year Office 365 Developer Tenant. This account can only be used for testing purposes.

**Comment by isaacdchan** [comment]
@Wajeed-msft Thanks for the help. Created an Azure AD account (isaac@isaacdchangmail.onmicrosoft.com) and joined team. The request from `/v1.0/me/joinedTeams` returned 200, so authorization worked and the account is not forbidden. But the list of teams is empty despite being in a team.


<img width="607" alt="Capture" src="https://user-images.githubusercontent.com/33741008/57265127-ee45cd00-702a-11e9-8e6d-ee074cb1f124.PNG">

<img width="480" alt="Capture2" src="https://user-images.githubusercontent.com/33741008/57265125-eab24600-702a-11e9-80a7-a8528ea3e322.PNG">

Appreciate the patience.

**Comment by Wajeed-msft** [comment]
Could you please check if [/groups/{id}/members](https://docs.microsoft.com/en-us/graph/api/group-list-members?view=graph-rest-1.0&tabs=cs) shows all the members? You can [get a list of groups that have teams](https://docs.microsoft.com/en-us/graph/teams-list-all-teams?toc=.%2Fref%2Ftoc.json&view=graph-rest-1.0#get-a-list-of-groups-using-beta-apis) using beta APIs.

**Comment by isaacdchan** [comment]
`/groups` returns the group "test group" that I created. id: c947a221-4422-41be-8f95-e837638311f5
`/groups/c947a221-4422-41be-8f95-e837638311f5/members` returns an empty list

Is this normal behavior?

MS account isaac.d.chan@gmail.com is the main tenant of this Azure, created the org and the team. Could that possibly be affecting the results?

**Comment by Wajeed-msft** [comment]
If you still facing this issue, please re-open with latest request/response details.
