### ISSUE TITLE
Difficulty understanding "AAD SSO for tabs and message extension" tutorial

### ISSUE THREAD

**Issue by catmanjan** [MicrosoftDocs/msteams-docs#6226]
We have a web app which already allows users to log in with AzureAD via OAuth2

I am now following the tutorial here which involves creating an app registration for a Teams bot 

https://docs.microsoft.com/en-us/microsoftteams/platform/sbs-tabs-and-messaging-extensions-with-sso?tabs=vs2019&tutorial-step=4

What I don't understand is why do we have to "Add OAuth Connection Settings" to connect to the bots own Microsoft App ID? 
If we already have an app do we still need to do this? 
In what scenario would a Teams bot not be able to oauth with its own Microsoft App ID?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90fe7a88-a703-1d13-f945-2a15f335721a
* Version Independent ID: 90fe7a88-a703-1d13-f945-2a15f335721a
* Content: [Overview to authentication for tabs using SSO in Teams with Azure AD - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/tab-sso-overview)
* Content Source: [msteams-platform/tabs/how-to/authentication/tab-sso-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/tabs/how-to/authentication/tab-sso-overview.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Nivedipa-MSFT** [comment]
@catmanjan - We are investigating your query. We will inform you once we have any update.
