### ISSUE TITLE
Documentation clarification - Bots retrieving UPN property for members of a team

### ISSUE THREAD

**Issue by YJasonY** [MicrosoftDocs/msteams-docs#6227]
Hi, regarding this statement towards the end of the [page](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/team-chat-member-api-changes#api-changes):

`By late 2022, bots can't proactively retrieve the userPrincipalName or email properties for members of a chat or team.`

are there any updates on exactly when this feature might be removed or what the process would be (e.g. throttled requests for a period before complete removal)?

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c780d605-b1b2-716f-5888-503608769b5a
* Version Independent ID: 53c724f8-d9a2-4af6-6d75-ddeaef084137
* Content: [Bot API changes for team and chat members - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/team-chat-member-api-changes)
* Content Source: [msteams-platform/resources/team-chat-member-api-changes.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/resources/team-chat-member-api-changes.md)
* Service: **msteams**
* GitHub Login: @ojasvichoudhary
* Microsoft Alias: **ojchoudh**

**Comment by sayali-MSFT** [comment]
@YJasonY - We are looking into this I will get back to you soon.

**Comment by sayali-MSFT** [comment]
@YJasonY --We are checking the method ,We are able to get the userPrincipalName /email using the GetConversationPagedMembers API.
We are update the document accordingly.
![userpr](https://user-images.githubusercontent.com/93527375/175298652-72a81606-a56a-471b-8a81-de9e87ccad45.png)

**Comment by sayali-MSFT** [comment]
@YJasonY - We are closing this issue for now, Please feel free to reopen it, if required.
