### ISSUE TITLE
Steps to set up CICD pipeline is out of date

### ISSUE THREAD

**Issue by MuyangAmigo** [MicrosoftDocs/msteams-docs#6232]
The steps mentioned here is out of date when using Teams Toolkit latest version (v4.0); need to select "Add features" and the select "Add CICD Workflows" now.

![image](https://user-images.githubusercontent.com/11220663/174536109-ac135a0e-75ef-4c77-8fa5-fa5035eabe6b.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d56615f7-9333-d20c-8c83-0effb602995a
* Version Independent ID: d56615f7-9333-d20c-8c83-0effb602995a
* Content: [CI/CD templates - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/toolkit/use-cicd-template)
* Content Source: [msteams-platform/toolkit/use-CICD-template.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/use-CICD-template.md)
* Service: **msteams**
* GitHub Login: @MuyangAmigo
* Microsoft Alias: **ruhe**

**Comment by zyxiaoyuer** [comment]
@surbhigupta12  Can we add some screenshot here? like: 
![image](https://user-images.githubusercontent.com/25972542/174539227-da2b0a8a-cba5-4368-b358-a2679c77ee9b.png)
![image](https://user-images.githubusercontent.com/25972542/174539289-012e19bb-b169-4801-9fba-c4b21a0df325.png)
