### ISSUE TITLE
Deeplink to a tab does not work in mobile

### ISSUE THREAD

**Issue by NicolasHumann** [MicrosoftDocs/msteams-docs#6264]
Hello,

As mentioned in the documentation, we create a deep link with this format
 https://teams.microsoft.com/l/entity/fa4a82bb-2a31-4737-8e33-e5fae6fee194/123?webUrl=https://gantt.witivio.com?=ganttId=123&context={"channelId": "19:cbe3683f25094106b826c9cada3afbe0@thread.skype"}

We activate the deep link in a tumbnailcard shared via a messaging extension. The code is 

```
var card = new MessagingExtensionAttachment
            {
                ContentType = ThumbnailCard.ContentType,
                Content = new ThumbnailCard
                {
                    Title = task.Name,
                    Text = notes,
                    Tap = new CardAction
                        {
                            Type = "openUrl",
                            Title = "Open",
                            Value = MakeDeepLink()
                        },
                    Images = new List<CardImage>() { new CardImage(imagePath, "Image") }
                }
            };
```
The deep link works fine in Teams desktop and in the browser. In android device, the deep link is not executed.

The documentation does not mentioned that the deep link is not supported in mobile. Is it a Teams platform bug?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45541337-ecd7-5cf6-cbe4-3f0d2f39aa79
* Version Independent ID: 6b4203f0-2844-06c9-eaa3-9cc03e6f76c0
* Content: [Create deep links - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links?tabs=teamsjs-v2)
* Content Source: [msteams-platform/concepts/build-and-test/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/build-and-test/deep-links.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by sayali-MSFT** [comment]
@NicolasHumann -We are looking into this I will get back to you soon.

**Comment by sayali-MSFT** [comment]
@NicolasHumann -We are able to repro that issue , We have raised bug for the same and concerned team is looking into it. We will inform you once we get any update.

**Comment by sayali-MSFT** [comment]
@NicolasHumann -Got the reply from engineering team," The appId in the deep link doesn't match with any apps id which are already added in the thread tab list(definitely not the appId of the tab(Conversational Tab2) in the thread."

**How is it working on desktop** - desktop must be falling back to the 1st tab from the tab list as the specific tab doesn't have the matching appId as in the deep link, mobile on the other hand doesn't fallback to any tab rather it lands to the channel/chat conversation page where it's landing right now.

**Comment by dieonar** [comment]
Hello, we succeeded to make it work on android use the app id generated by Microsoft once the app is side loaded, but unfortunately we couldn't make it work on iOS. 

Could you be able to provide the same demonstration video, but with an iOS device?

**Comment by sayali-MSFT** [comment]
@dieonar -We have tried with IOS version 16.1. It's working fine.
IOS Teams version- 4.21.4

https://user-images.githubusercontent.com/93527375/208437330-530f55f2-f946-4a91-b438-2a306b2be258.mp4

**Comment by dieonar** [comment]
Hello,

Thank you for your quick answer, please find further more details.

A direct link in a message works fine on iOS. It's when clicking when on a button in an adaptive card that it potentially doesn't work correctly, instead of opening the link in Microsoft Teams, the link opens a window in the default browser of the iOS phone and it doesn't work. Would you be able to try with an Adaptive Card?

![image](https://user-images.githubusercontent.com/5982866/208478109-f74c1f88-24cd-4cba-8c08-69a8072af405.png)

**Comment by sayali-MSFT** [comment]
@dieonar -We are tried the above scenario,
creating the button on the card with deep link ,after click on that button deep link is executed.
 IOS version 16.1.
 IOS Teams version- 4.21.4
 

https://user-images.githubusercontent.com/93527375/208636725-e03b8122-3b29-4e8d-86ab-89db59308beb.mp4

**Comment by dieonar** [comment]
Hello, thanks for your assistance, we succeeded to make it work by removing the webUrl query parameter like in your link example.

**Comment by dieonar** [comment]
Hello, thanks for your assistance, by following the construction of the link shown above, we succeeded by removing the webUrl query params in the construction of the deeplink.

**Comment by sayali-MSFT** [comment]
@dieonar - We are closing this issue for now, Please feel free to reopen it, if required.

Could you please share your valuable feedback via Microsoft Teams Developer [Feedback](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Furldefense.proofpoint.com%2Fv2%2Furl%3Fu%3Dhttps-3A__nam06.safelinks.protection.outlook.com_-3Furl-3Dhttps-253A-252F-252Furldefense.proofpoint.com-252Fv2-252Furl-253Fu-253Dhttps-2D3A-5F-5Fnam06.safelinks.protection.outlook.com-5F-2D3Furl-2D3Dhttps-2D253A-2D252F-2D252Faka.ms-2D252FDevSupportFeedback-2D26data-2D3D05-2D257C01-2D257Cv-2D2Dsdange-2D2540microsoft.com-2D257C277bc2af02f8468aca7408da5b1fc1e1-2D257C72f988bf86f141af91ab2d7cd011db47-2D257C1-2D257C0-2D257C637922489293358532-2D257CUnknown-2D257CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0-2D253D-2D257C3000-2D257C-2D257C-2D257C-2D26sdata-2D3DUpbhrrikjmwQukP083LYzk4V5Uzx9HvfF1CgaKVft8I-2D253D-2D26reserved-2D3D0-2526d-253DDwMF-2Dg-2526c-253DeIGjsITfXP-5Fy-2DDLLX0uEHXJvU8nOHrUK8IrwNKOtkVU-2526r-253DiTBYfqzH1nQGfEzDml7bhI5MScJay2M9s4VELlUrMFw-2526m-253DyDgwt9c-2Ds96X7Yoq46vtQooog3vMn3ufdZ5mgFw3m77aAxIQxQ6F02jN76ZZKQ31-2526s-253DYbPIqey-2DNqtqsMf6x1yzt6JdJIb9M-5FnLwMPPyvlAPec-2526e-253D-26data-3D05-257C01-257Cv-2Dsdange-2540microsoft.com-257C4be0adb3d1f24e5811de08da5d58c11d-257C72f988bf86f141af91ab2d7cd011db47-257C1-257C0-257C637924933069153329-257CUnknown-257CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0-253D-257C3000-257C-257C-257C-26sdata-3DDwIJlGcXPRoqLy3EpKLX07G6pUxvmfbo7J9fufsttKk-253D-26reserved-3D0%26d%3DDwMFJg%26c%3DeIGjsITfXP_y-DLLX0uEHXJvU8nOHrUK8IrwNKOtkVU%26r%3D64aI-eGOuiiiwZK8b451udVu49hsuMatrzKD-VSTqy8%26m%3DzrWpJPDaJekQn72hWrCTFsbglANF6_Ew_zHoVrumypo0EOgiE3TE6rntrvws7vDh%26s%3DceT2tapCooPSwUXOLgFrSuIjVDTjpdvrkcKt6mQZRww%26e%3D&data=05%7C01%7Cv-sadange%40microsoft.com%7Cf76e6d51b1784ad5c3d008dadc26d279%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638064356685690597%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=fczSX8coVFs8mtMrIM%2FF%2BbSxW75CIAnUXR7UPsb34Ss%3D&reserved=0) link.
