### ISSUE TITLE
Add support for custom URI schemes

### ISSUE THREAD

**Issue by catmanjan** [MicrosoftDocs/msteams-docs#6277]
This has been asked for many times over the years, last time it was rejected "for security reasons", but given its supported by all the browsers now days I don't think that is factual.

Users and developers should be able to insert links of the form "ms-word:ofe|u|https://myurl/document.docx" wherever/whenever they want and have Teams launch the associated application on the user's PC as browsers allow.

**Comment by Prasad-MSFT** [comment]
Thanks for bringing this up. We will redirect to respective team and act accordingly

**Comment by catmanjan** [comment]
I'm happy to do so, I actually did log it in the old user voice system, but then Microsoft shut that down?

**Comment by Prasad-MSFT** [comment]
Please raise your feedback here: https://feedbackportal.microsoft.com/feedback/forum/ad198462-1c1c-ec11-b6e7-0022481f8472

**Comment by Prasad-MSFT** [comment]
We are closing the issue for now. Please feel free to reopen if required.
