### ISSUE TITLE
How can I get user information who clicked the button in "Office 365 Connector Card"

### ISSUE THREAD

**Issue by XimenaWang** [MicrosoftDocs/msteams-docs#628]
For instance, suppose Lisa clicked this button, How can I post her name to my target API ?
**Json payload:**
![image](https://user-images.githubusercontent.com/30890958/57266470-e557fa00-7030-11e9-91a7-abe7b53a450d.png)

**Teams UI:**
![image](https://user-images.githubusercontent.com/30890958/57266364-77133780-7030-11e9-82e4-902863cce8af.png)

**Comment by XimenaWang** [comment]
Hope to get help

**Comment by Wajeed-msft** [comment]
@XimenaWang - Currently, when you receive httpPost request to end point you can check the bearer token which contains AAD Id (sub). You can check your token using [jwt debugger](https://jwt.io/#debugger-io).
![image](https://user-images.githubusercontent.com/31851992/57442008-b4faa080-7268-11e9-8426-9e5e18d84d8f.png)

There is no other sender infromation sent along with the request. This is something we are looking into.

**Comment by XimenaWang** [comment]
Thanks~ I got the sub now. and are you currently developing this features to get more sender information?
can we get the other sender information later?

**Comment by Wajeed-msft** [comment]
As of now we are working on including email Id/ UPN of the user who performed the action.

**Comment by XimenaWang** [comment]
Thanks, waiting for the “coming soon” feature
