### ISSUE TITLE
Document says limitation for Guest Token for /users API but the token works

### ISSUE THREAD

**Issue by raguravindran** [MicrosoftDocs/msteams-docs#6285]
**Describe the bug**
Recently discovered that the delegated permission `User.Read.All` is working for Guest users, microsoft graph document mentions that guest token will not be able to access `/users` API

**To Reproduce**
Steps to reproduce the behaviour:

- Go to graph explorer https://developer.microsoft.com/en-us/graph/graph-explorer?tenant=<tenant_id>
- Make sure the logged in user is guest user of tenant that is passed in the above URL.
- Make sure User.Read.All is consented for with the guest user.
- Once proper guest logs in verify the token from access token tab, check `tid` and `scp` for scopes (permissions).
- Fire the API from graph explorer `https://graph.microsoft.com/v1.0/users?$select=mail,userPrincipalName,userType&$filter=mail eq 'adelev@nowdomain.onmicrosoft.com'` filter to have host tenant user (member of the tenant)
- Try without filter as well `https://graph.microsoft.com/v1.0/users?$select=mail,userPrincipalName,userType`
- In both the cases observe the API returns users, which is not expected as per the docs.

Previously there was an error `Insufficient Privileges to perform this action` when using `/users` API with Guest Token
**document link**
https://docs.microsoft.com/en-us/graph/permissions-reference#user-and-group-search-limitations-for-guest-users-in-organizations

**Attachments**
None

**Desktop (please complete the following information):**

OS: [Mac]
Browser [chrome, safari, edge]

**Comment by Prasad-MSFT** [comment]
We are checking the issue. We will get back to you shortly

**Comment by Prasad-MSFT** [comment]
We tried to repro the issue. We added a guest user to the tenant and got user token which has following permissions/scopes:
![image](https://user-images.githubusercontent.com/62237649/175762470-580e1c20-1369-485d-ac9d-c1691736c23e.png)

On running below query
`https://graph.microsoft.com/v1.0/users?$select=mail,userPrincipalName,userType&$filter=mail eq 'adelev@nowdomain.onmicrosoft.com'`
 we are getting this success result
 
![image](https://user-images.githubusercontent.com/62237649/175762562-16961871-915e-4ab9-8a5b-5229951c5644.png)

However for this query
`https://graph.microsoft.com/v1.0/users?$select=mail,userPrincipalName,userType`
 its giving "Insufficient Privileges to perform this action" as mentioned in this [doc](https://docs.microsoft.com/en-us/graph/permissions-reference#user-and-group-search-limitations-for-guest-users-in-organizations).
![image](https://user-images.githubusercontent.com/62237649/175762619-3edab973-82fe-4058-91e0-54ff7d35e638.png)

**Comment by raguravindran** [comment]
@Prasad-MSFT 
I tried a different tenant and I see it is working (failing) as expected.

When I checked the difference between the tenants. Here is what I found.
In azure portal of host tenant (**nowdomain.onmicrosoft.com**) in my case. I had chosen
**_Guest users have the same access as members (most inclusive)_** option from 
`External Identities` > `External Collaboration Settings` > `Guest user access` (see screenshot below)

<img width="723" alt="Screenshot 2022-06-26 at 11 14 07 AM" src="https://user-images.githubusercontent.com/36010645/175801145-03ed4630-cabc-4019-837a-6ae5f74217d4.png">

Whereas, the default option that is selected in the tenant is,
**Guest users have limited access to properties and memberships of directory objects**

can you please confirm if this is what causing unexpected results in my tenant? I have flipped the option back to oob settings to verify once again. I will post it once I retry after.

**Comment by Prasad-MSFT** [comment]
We had this below option enabled for the Guest user in our tenant:
**Guest users have limited access to properties and memberships of directory objects**

**Comment by raguravindran** [comment]
@Prasad-MSFT 
Okay. But is this behaviour of `/users` API driven by `External Collaboration Settings`? We are building a solution around this, we want to make sure we are surfacing the right content to the users who will consume these features. 

If this is the case is the understanding below correct?
having option **Guest users have the same access as members (most inclusive)** enabled, /users API will work with Guest token as well

Based on the understanding, we would like to recommend our consumers with appropriate Guest access settings.

**Comment by Prasad-MSFT** [comment]
Yes, that could be the case, because on enabling **Guest users have the same access as members (most inclusive)**, we are getting success result on firing this query: `https://graph.microsoft.com/v1.0/users?$select=mail,userPrincipalName,userType`

![image](https://user-images.githubusercontent.com/62237649/175812123-0fa503be-448e-44e6-9b3d-c61669aa875b.png)

**Comment by raguravindran** [comment]
@Prasad-MSFT Appreciate your prompt reply. Can we get this information added to Microsoft Documents?

**Comment by Prasad-MSFT** [comment]
Thanks! We will redirect it to appropriate team to update accordingly.

**Comment by Prasad-MSFT** [comment]
Hi @surbhigupta12 , it would be better if we add a note to this doc(https://docs.microsoft.com/en-us/graph/permissions-reference#user-and-group-search-limitations-for-guest-users-in-organizations) saying,

Having option **Guest users have the same access as members (most inclusive)** enabled under
**External Identities > External Collaboration Settings > Guest user access**, /users API will work with Guest token as well
