### ISSUE TITLE
More resources PDF downloads

### ISSUE THREAD

**Issue by JadyM** [MicrosoftDocs/msteams-docs#630]
Hi, thanks for providing excellent information on designing Teams apps, but the Basic Elements & Dark Theme PDF downloads contain images and not editable text and elements, making them much less useful to us. 
Editable text and elements allow easy conversion into Adobe Illustrator format, then import into Adobe XD for quick prototyping. 
Images, while a reasonable guide, provide no vector elements and therefore require significant additional hours of work to make into an Adobe XD template for designing apps for Microsoft Teams.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5847d1f2-5fd3-1d76-a126-a8c9e251c74f
* Version Independent ID: c7ee1d92-1481-f642-1114-1db073334324
* Content: [Design Guidelines Resources - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/design/resources#feedback)
* Content Source: [msteams-platform/resources/design/resources.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/resources/design/resources.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by JadyM** [comment]
Actually, two PDFs do contain vector elements: Bot Cards & Color Swatches... thanks. 
But the other PDFs, especially Basic Elements and Screens, would be much more useful if in an RGB vector format inside the PDF file.

**Comment by clearab** [comment]
We're actually about to update the design guidance pretty significantly shortly. I will take this feedback into consideration as we create the update.
