### ISSUE TITLE
The capability support table incorrectly lists Teams as supporting calendar

### ISSUE THREAD

**Issue by AE-MS** [MicrosoftDocs/msteams-docs#6302]
The capability support table lists Teams as supporting the `calendar` capability when it does not.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89e79849-bf25-dd0a-4680-c1074966051b
* Version Independent ID: fee94efc-fe9c-6460-1df8-f9bc97abf526
* Content: [Building tabs and other hosted experiences with the Microsoft Teams JavaScript client SDK - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/using-teams-client-sdk?tabs=javascript%2Cmanifest-teams-toolkit#microsoft-365-support-running-teams-apps-in-office-and-outlook)
* Content Source: [msteams-platform/tabs/how-to/using-teams-client-sdk.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/tabs/how-to/using-teams-client-sdk.md)
* Service: **msteams**
* GitHub Login: @heath-hamilton
* Microsoft Alias: **surbhigupta**

**Comment by ChetanSharma-msft** [comment]
@marcinjuraszek - Please let us know once the PR is merged, so that we can inform community developer accordingly and will close this issue as well.

**Comment by ChetanSharma-msft** [comment]
@AE-MS - Changes are merged.
We are closing this issue, please feel free to reopen it, if required.
