### ISSUE TITLE
Deeplink to 1:1 bot chat has suddenly stopped working

### ISSUE THREAD

**Issue by bangndnguyen** [MicrosoftDocs/msteams-docs#631]
I was using this deeplink to navigate from a tab back to bot conversation: 

`microsoftTeams.executeDeepLink('https://teams.microsoft.com/l/chat/0/0?users=28:6ba80233-b318-4a25-8f4c-c08821b97445')`

It was working fine, but suddenly stop this morning.

**Comment by Gousia-MSFT** [comment]
@bangndnguyen I tried opening a deeplink to bot conversation from a tab and it works as expected for me. Could you please try this in a browser and share the console information?

**Comment by bangndnguyen** [comment]
If I open it in a browser, it works fine. It doesn't when I execute it inside a Teams tab, no errors, no messages.

**Comment by Gousia-MSFT** [comment]
@bangndnguyen Did you try opening the deeplink from Teams web client? Are you facing this issue both in desktop and web client?

**Comment by bangndnguyen** [comment]
@Gousia-MSFT Yes, I have this issue both on desktop and web client.

**Comment by Gousia-MSFT** [comment]
In that case, could you please try opening deeplink from teams web client and share the console errors, if any?

**Comment by bangndnguyen** [comment]
@Gousia-MSFT Unfortunately, there is no console errors. You can check it here: https://codesandbox.io/s/rj6z4q93k4

**Comment by bangndnguyen** [comment]
Never mind, I think the issue is caused by some domain crossing problem because the tab first load _domain1.com_, then it's been redirected to _domain2.com_. If the deeplink is executed while in _domain1.com_, then it works, but not in _domain2.com_
