### ISSUE TITLE
Documentation does not contain information required to use this feature in code

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#6311]
Currently no information is provided on following topics:
1. Which event to handle to use this feature?
2. What type of event is sent to Bot? 
3. Payload information of Read Receipt event is not provided.
4. Guidance on handling scenarios where user has disabled the Read receipt which might lead to spammy behavior as Bot never gets the read receipt. 

PR: https://github.com/MicrosoftDocs/msteams-docs/pull/6182
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afbc5b84-5be5-b5c4-30c0-58782a748a03
* Version Independent ID: ef6b8aee-52e7-f5d4-7dfa-8f34a1698330
* Content: [Messages in bot conversations - Teams](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-messages?branch=pr-en-us-6182&tabs=dotnet)
* Content Source: [msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/bots/how-to/conversations/conversation-messages.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **anclear**

**Comment by ChetanSharma-msft** [comment]
Hello @surbhigupta12 - Can you please help us here to update the documentation?
