### ISSUE TITLE
REQUEST_SEND_ERROR when sending Activity

### ISSUE THREAD

**Issue by MajaEffenberg** [MicrosoftDocs/msteams-docs#6313]
Hi there,

For some users we get request send error when we sending `TurnContext.sendActivity(activity)` with AdaptiveCard. In this case TurnContext.sendActivity throw an exception with the error `REQUEST_SEND_ERROR`.

The exact same call works for hunderds of users, it only fails for a couple. So it has nothing to do with the activity itself. It must be a problem of the users.

When is such an exception occurring?

**Comment by sayali-MSFT** [comment]
@MajaEffenberg - We are looking into this , we will get back to you soon.

**Comment by sayali-MSFT** [comment]
@MajaEffenberg -We are not able to repro the scenario ,It's working fine from our end.
Could you please share the Bot Id.Timestamp , Do that we can investigate on it. Thanks

**Comment by MajaEffenberg** [comment]
@sayali-MSFT 

Request information:
- timestamp in UTC: `28.6.2022 - 11:54:10`
- method: `POST`
- url: `https://smba.trafficmanager.net/ch/v3/conversations/a%3A1AzqErVK4MZPBpjDtTdJrOGmiEpOsQaxyQrYRrQrGEh6I04Hr1d9moW72PHJTJ1Ikj2ujR98w-RtpJl8wMPgFkqlz-5PGoAuYk_MTX0j4fHdSfR39Jl_uiCP67vn0OqXF/activities/f%3Ac7a25351-8b9b-5c10-267c-0f352e86f5b8`
- conversationId: `a:1AzqErVK4MZPBpjDtTdJrOGmiEpOsQaxyQrYRrQrGEh6I04Hr1d9moW72PHJTJ1Ikj2ujR98w-RtpJl8wMPgFkqlz-5PGoAuYk_MTX0j4fHdSfR39Jl_uiCP67vn0OqXF`
- activityId: `f:c7a25351-8b9b-5c10-267c-0f352e86f5b8`

Our botId: `4112cc9a-d683-4ffd-b0bc-2013af7c7497`

**Comment by MajaEffenberg** [comment]
Is there any update on this issue?

**Comment by sayali-MSFT** [comment]
@MajaEffenberg - Currently we don’t have ETA or Update on this thread.
let you know once we get any updates.

**Comment by MajaEffenberg** [comment]
Any news on this issue?

**Comment by sayali-MSFT** [comment]
@MajaEffenberg -Have you send multiple request in same/particular time?
Unable to read feature value from ECS error occur only when you send the request at same time.
