### ISSUE TITLE
Improvement/Features request on messaging extension

### ISSUE THREAD

**Issue by tomqmr** [MicrosoftDocs/msteams-docs#6316]
During the development of our messaging extension, we found diverses things that works in certain context and not in others, or that can be improved so here is the list :

- Click on openURL actions in card in compose area (working in chats but not in channels)
![image](https://user-images.githubusercontent.com/106740199/176149246-3d2c511f-a22f-4432-bd5c-e805b8783699.png)

In chats we can click on the openURL button without sending the card in the conversation, but it is not working on channels.

- Card fields in Dark mode : 
![image](https://user-images.githubusercontent.com/106740199/176147673-512bee18-b911-4bc7-b46b-54e197152615.png)
![image](https://user-images.githubusercontent.com/106740199/176147782-b23224ff-6f43-46f6-8558-ab26afc0ed21.png)

In dark mode, the fields are not really visible compared to light, maybe it could be more delimited.

- Enter shortcut to submit forms

It could be really useful to tap Enter on keyboard to submit forms (like the ones on top of this).

**Comment by ChetanSharma-msft** [comment]
@tomqmr - Thanks for reporting this issue.

You mean, it's working in 1:1 personal chat but not working in Teams Channels in Compose Area ?
Are you facing this issue in Teams Desktop Client or in Web?

**Comment by ChetanSharma-msft** [comment]
@tomqmr - Thanks for sharing the details.
Is there any specific URL that you are using for openURL actions or any public URL?

I hope you are using Adaptive Card?

We will try it from our end and get back to you.

**Comment by tomqmr** [comment]
@ChetanSharma-msft No i can reproduce it with any other URL.

And for these ones I'm using "heroCard" from CardFactory, maybe the issue is proper to this type ?

**Comment by ChetanSharma-msft** [comment]
@tomqmr - We will try it using HeroCard/Adaptive Card.
Meanwhile, can you please try it using Adaptive Card once ?

**Comment by sayali-MSFT** [comment]
@tomqmr -We are tried this scenario with the hero card in Teams channel. It's working fine from our end.
Microsoft Teams Version 1.5.00.19202 (64-bit)-E

https://user-images.githubusercontent.com/93527375/178490518-d8bc8329-be82-400a-b229-ad286acf0d28.mp4

**Comment by sayali-MSFT** [comment]
@tomqmr -Could you please share the manifest json,So that we can try it from our end?

**Comment by tomqmr** [comment]
@sayali-MSFT
[manifest.zip](https://github.com/MicrosoftDocs/msteams-docs/files/9129919/manifest.zip)

**Comment by Nivedipa-MSFT** [comment]
@tomqmr - We have tried your scenario and able to repro your issue.
First we have added `context : ["message"]` and also fetchTask = true.
On opening popup on submit action we have return hero card on compose area.
We are also facing same issue. OpenURL is not working.

We have raised a bug for this. We will keep you posted if there are any updates.

**Comment by Nivedipa-MSFT** [comment]
@tomqmr - Engineering team has confirmed that openUrl in card won't work in compose box, it's meant to show a preview to the user.

**Comment by tomqmr** [comment]
> @tomqmr - Engineering team has confirmed that openUrl in card won't work in compose box, it's meant to show a preview to the user.

Ok i can understand that but it does work on personal chat and in channel, just not in my case with action on messages, so was it supposed to work at first or is it a bug that this is working when it should not ?

Thanks

**Comment by Nivedipa-MSFT** [comment]
@tomqmr - Do you mean it used to work in personal chat and in channel in compose box while previewing?

**Comment by tomqmr** [comment]
@Nivedipa-MSFT Yes, and it is still working (as you can see on the gif), so I don't really understand your message "Engineering team has confirmed that openUrl in card won't work in compose box" because it actually works, just not in a specific case ...
![openUrlComposeBox](https://user-images.githubusercontent.com/106740199/189830828-4bc2ad42-03e8-467d-873c-575c7ee60ec9.gif)

**Comment by Nivedipa-MSFT** [comment]
@tomqmr - Yes, you are right. Only for this specific scenario it's not working. We are checking this with engineering team. We will update you soon.
