### ISSUE TITLE
This page now includes all updates, not limited to new GA features, the Title of the article should reflect that

### ISSUE THREAD

**Issue by cdowling1971** [MicrosoftDocs/msteams-docs#6318]
A Japanese Microsoft customer reported an issue with the Title of this this article 
"This page now includes all updates, not limited to new GA features, the Title of the article should reflect that."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ffc338ca-2f9a-9f79-bc7c-07bbd7534c78
* Version Independent ID: 0c40a2b1-4b71-5ec9-82b5-371dadddf2cc
* Content: [What is new for developers in Teams - Teams](https://review.docs.microsoft.com/en-us/microsoftteams/platform/whats-new?branch=main)
* Content Source: [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/whats-new.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Nivedipa-MSFT** [comment]
@cdowling1971 - Could you please share what exactly you want to update in Title here?

**Comment by cdowling1971** [comment]
So instead of What is new for developers in Teams might be changed to possible titles below (as suggestions)

What is new or updated for developers in Teams
What is new and updated for developers in Teams

**Comment by Nivedipa-MSFT** [comment]
@surbhigupta12 - Could you please help here to update the Title for below document:
https://review.docs.microsoft.com/en-us/microsoftteams/platform/whats-new?branch=main

Content need to be updated: What's new and updated for developers in Microsoft Teams

**Comment by surbhigupta12** [comment]
Updated.

**Comment by surbhigupta12** [comment]
Working on this request.

**Comment by surbhigupta12** [comment]
What's new is a generic term used across different documentation sets. What's new does consist of new features + updates to existing one.

We've also verified Japanese translation quality.

We'd retain our page title as What's new.
