### ISSUE TITLE
openAppInstallDialog V2 has the wrong input parameter

### ISSUE THREAD

**Issue by jadahiya-MSFT** [MicrosoftDocs/msteams-docs#6327]
The correct parameter for openAppInstallDialog should be `appId` and not `appID`. This can lead to confusion and errors with partners when they are viewing the docs.

https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links?tabs=teamsjs-v2#open-an-app-install-dialog
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45541337-ecd7-5cf6-cbe4-3f0d2f39aa79
* Version Independent ID: 6b4203f0-2844-06c9-eaa3-9cc03e6f76c0
* Content: [Create deep links - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links?tabs=teamsjs-v2#open-an-app-install-dialog)
* Content Source: [msteams-platform/concepts/build-and-test/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/build-and-test/deep-links.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by sayali-MSFT** [comment]
@surbhigupta12 -Could you please help us to update the content?
Need to change parameter for openAppInstallDialog should be appId instead of appID
Doc-https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links?tabs=teamsjs-v2#open-an-app-install-dialog
