### ISSUE TITLE
SDK version is outdated. Current version is 1.4.2

### ISSUE THREAD

**Issue by Tyrcheg** [MicrosoftDocs/msteams-docs#633]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aadca17b-de5c-0d06-caa6-d7bafd04f99b
* Version Independent ID: 91035790-5d36-067e-4400-04bb51cb03e3
* Content: [Microsoft Teams client SDK - Teams](https://docs.microsoft.com/en-us/javascript/api/overview/msteams-client?view=msteams-client-js-latest)
* Content Source: [nodejs/overview/msteams-client.md](https://github.com/OfficeDev/msteams-client-docs-ref-typescript/blob/live/nodejs/overview/msteams-client.md)
* Product: **msteams**
* GitHub Login: @charlesprakash
* Microsoft Alias: **o365devx**

**Comment by Wajeed-msft** [comment]
Docs are updated.
