### ISSUE TITLE
Failure when opening Tab

### ISSUE THREAD

**Issue by sueess** [MicrosoftDocs/msteams-docs#6349]
Our Chatbot comes with multiple tabs. Some user have problems opening this tabs. The same tabs are working for hundreds of other users. For this reason it is hard to say why the bugs appear. Different problems appear:

![tab-problem-1](https://user-images.githubusercontent.com/6587992/176443986-2bf5d7ce-c864-41f0-91e5-a46424b8da64.jpg)

![tab-problem-2](https://user-images.githubusercontent.com/6587992/176444214-76765688-8983-4351-93f8-6193fa1a193f.jpg)

**Comment by sayali-MSFT** [comment]
@sueess - We are looking into this I will get back to you soon.

**Comment by sayali-MSFT** [comment]
@sueess - Could you please share BotID and Timestamp so that we can investigate from our end?

**Comment by sueess** [comment]
We get ever day multiple mails from our users, that the tabs are not working. We try to gather more information from them. Two things are for sure:
* There are tab issues on MS Teams
* The bugs do not occur for everyone (or in every scenario)

Since we are not able to look in the MS Teams source you have to tell me, how we can support you by solving that issue?

**Comment by MajaEffenberg** [comment]
This is not reported bug. This comes from HTTP request to our app. We already corrected this error and fix will be published in next days.

The reported problem occurs before any requests are sent from Tabs.

**Comment by sayali-MSFT** [comment]
@MajaEffenberg -Could you please provide a Fiddler trace by any chance?

**Comment by ChetanSharma-msft** [comment]
@MajaEffenberg - We are not able to investigation on it further due to unavailability of network traces.
If you are not able to repro, shall we close it?

If you will face this issue again, feel free to re-open or raise another issue.

**Comment by sayali-MSFT** [comment]
@MajaEffenberg -We will wait for your response.

**Comment by ChetanSharma-msft** [comment]
Hello @sueess , @MajaEffenberg - Hope you are doing well !!
How everything going on ?
Did you face the error by any chance ?
Are you able to capture the network traces/logs ?
