### ISSUE TITLE
Teams Attachment browser showing hidden files that Windows Explorer does not.

### ISSUE THREAD

**Issue by jbaum888** [MicrosoftDocs/msteams-docs#635]
Teams attachment browser is showing some hidden files that do not show up in File Explorer with hidden files enabled.

These files are cryptolocker bait used by Palo Alto Traps Endpoint Protection. Teams attachment browser is the only place that these show up. I am unsure what method Palo Alto uses to hide these files.

![image](https://user-images.githubusercontent.com/50420895/57396619-6548a600-7190-11e9-994c-85f98e08fc06.png)

![image](https://user-images.githubusercontent.com/50420895/57396781-c96b6a00-7190-11e9-85c5-aa5332e0448b.png)

**Comment by Abhijit-MSFT** [comment]
These are temporary files which will get created when you open any document on the disk. In teams sometime these files shows up but in file explorer it shows up for a sec and goes off. As soon as you close the document, windows will delete that file. You can ignore these files.
