### ISSUE TITLE
Example of messaging extension with bot framework sdk 4 will be help full.

### ISSUE THREAD

**Issue by joicepj11** [MicrosoftDocs/msteams-docs#636]

**Comment by clearab** [comment]
Hi - Our v4 SDKs are currently in Beta. You can find samples for them in their respective GitHub repositories. We will add samples and examples to our documentation once they come out of beta.

Node: https://github.com/OfficeDev/BotBuilder-MicrosoftTeams-node/tree/master/samples/message-extension-bot

C#: https://github.com/OfficeDev/BotBuilder-MicrosoftTeams-dotnet/tree/master/CSharp/Samples/Microsoft.Bot.Builder.Teams.MessagingExtensionBot

**Comment by joicepj11** [comment]
Thanks for the reply.
