### ISSUE TITLE
[Help]Sideloading is disabled in your Microsoft 365 account.

### ISSUE THREAD

**Issue by huabin** [MicrosoftDocs/msteams-docs#6365]
I logged into Teams Toolkit(extension) on VS Code, but I always get the error.

```
Sideloading is disabled in your Microsoft 365 account. Contact your Teams administrator to resolve this issue or get a testing tenant.
```

![Screen Shot 2022-07-03 at 19 52 41](https://user-images.githubusercontent.com/535675/177038333-f56dc7a1-a129-42fe-a08f-a457d88f4094.png)

### What I had done

I checked all according to this article, https://docs.microsoft.com/en-us/microsoftteams/platform/m365-apps/prerequisites

### More information

- VS Code version: 

    Version: 1.68.1
    Commit: 30d9c6cd9483b2cc586687151bcbcd635f373630
    Date: 2022-06-14T12:52:13.188Z
    Electron: 17.4.7
    Chromium: 98.0.4758.141
    Node.js: 16.13.0
    V8: 9.8.177.13-electron.0
    OS: Darwin x64 21.5.0

- Teams Toolkit version: v4.0.1

**Comment by ChetanSharma-msft** [comment]
@huabin - Thanks for reporting this issue.
Looks like sideloading is not enabled in your tenant and it should be enabled from Teams admin center by tenant administrator.
Reference like:
https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/prepare-your-o365-tenant#enable-custom-teams-apps-and-turn-on-custom-app-uploading

Supporting doc to upload a custom app:
https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/apps-upload

Manage apps doc link:
https://docs.microsoft.com/en-us/MicrosoftTeams/manage-apps

**Comment by huabin** [comment]
Hello @ChetanSharma-msft,

Thank you for the reply. Actually, it just needs time to activate, and it is fixed.

Thank you all the same.
