### ISSUE TITLE
How to "authenticate and have a bearer token" ?

### ISSUE THREAD

**Issue by XimenaWang** [MicrosoftDocs/msteams-docs#637]
when I call the code **"**  var members = await connector.Conversations.GetConversationMembersAsync(activity.Conversation.Id); **"**

and get the error "Microsoft.Bot.Connector.MicrosoftAppCredentials+OAuthException: Unauthorized ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized)."

Is it that I don't have permission to access it? looking forward to reply, Thanks!

**Comment by Wajeed-msft** [comment]
@XimenaWang - Are you trying to [fetch the team roster](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/bots/bots-context#net-example)? Could you please confirm if your App Id and App Secret are correct? Please share the code snippet of how you are creating ConnectorClient.

![image](https://user-images.githubusercontent.com/31851992/57442848-70700480-726a-11e9-9055-9dbd9071f4d8.png)

**Comment by XimenaWang** [comment]
@Wajeed-msft Hi,  App Id and App Secret means Bot Id and Bot Password? ok, my code below:
![image](https://user-images.githubusercontent.com/30890958/57523600-3e968680-72da-11e9-9a4b-7f4c828762e5.png)

**Comment by Wajeed-msft** [comment]
Yes, Bot Id and Bot Password.

Is your bot responding back with when you don't fetch conversation members? If yes, then could you please fetch members right after your replies?
![image](https://user-images.githubusercontent.com/31851992/57611345-4c753180-7590-11e9-9e0b-370889b6fba6.png)


Are you trying to fetch conversation members from Message Extension?

**Comment by XimenaWang** [comment]
NO, I just want to create one Proactive message by Bot. Actually, any operation I did using the ConnectorClient all report the "Unauthorized" error. so I tried the code "Message Extension", " fetch the team roster" and "proactive message".
![image](https://user-images.githubusercontent.com/30890958/57673482-042a3380-75d1-11e9-948e-63b1ddc75bef.png)


I have confirmed that I do not have permission to use the ConnectorClient to do anything, my full code follows. Where should I use Bot Id and Bot password?
![image](https://user-images.githubusercontent.com/30890958/57673313-57e84d00-75d0-11e9-9c44-b36ff81565d5.png)

**Comment by Wajeed-msft** [comment]
@XimenaWang - Could you please uncomment _[BotAuthentication]_ attribute and try again? 
![image](https://user-images.githubusercontent.com/31851992/57677270-13969480-7644-11e9-82e9-ba580cb05164.png)

**Comment by XimenaWang** [comment]
Same issue, I comment it as this issue, but this issue still exists after I commented on it.

**Comment by XimenaWang** [comment]
@Wajeed-msft Hi, I added the credential in ConnectorClient, and the App Id and App Secret are correct, but it still reported 401. Can  you help take a look? Any insight you have would be greatly appreciated.  Thanks in advance for your help.
![image](https://user-images.githubusercontent.com/30890958/58158491-64535200-7c2f-11e9-80e0-8c64b45ac02f.png)

**Comment by Wajeed-msft** [comment]
@XimenaWang - Could you please try adding `MicrosoftAppCredentials.TrustServiceUrl(serviceUrl, DateTime.MaxValue);` to your code as given in [sample code snippet](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/bots/bot-conversations/bots-conv-proactive#net-example-from-this-sample)?

**Comment by XimenaWang** [comment]
@Wajeed-msft - No, I have studied this sample before, but  it needs the parameter: **context**. I'm not sure where this parameter comes from?  My code references this GitHub: https://github.com/microsoft/botframework-sdk/issues/2258
