### ISSUE TITLE
Linking to Validation guidelines for SaaS offers

### ISSUE THREAD

**Issue by prkosh** [MicrosoftDocs/msteams-docs#6370]
[Enter feedback here]
hi - can you please include the link to the Top Fails for Monetized Teams apps ? Maybe a See More or as a Recommended Content? - https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/teams-store-validation-guidelines#apps-linked-to-saas-offer

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd29bf73-3680-24a6-5c05-76d06c1e40c1
* Version Independent ID: 45035997-0a41-8f4b-575d-ea5ae8ef4bab
* Content: [Include a SaaS offer with your app - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer)
* Content Source: [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md)
* Service: **msteams**
* GitHub Login: @heath-hamilton
* Microsoft Alias: **surbhigupta**

**Comment by Prasad-MSFT** [comment]
Hi @surbhigupta12 
It would be better if we add this [page link](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/teams-store-validation-guidelines#apps-linked-to-saas-offer) as [See More] or as [Recommended Content] in [this page](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer).
