### ISSUE TITLE
Sample schema is 1.0.0

### ISSUE THREAD

**Issue by billbliss** [MicrosoftDocs/msteams-docs#638]
Ironic given the purpose of this page!

Can we update it to at least 1.4 or ideally to the real devPreview?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b449c9ba-a94c-4012-4721-cee5f87eeb8a
* Version Independent ID: b2536bbc-eb27-547d-d7f5-bab3ded3bedf
* Content: [Developer Preview Manifest schema reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema-dev-preview#feedback)
* Content Source: [msteams-platform/resources/schema/manifest-schema-dev-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/resources/schema/manifest-schema-dev-preview.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by clearab** [comment]
App version is 1.0, manifestVersion is devPreview:

`"$schema": "https://raw.githubusercontent.com/OfficeDev/microsoft-teams-app-schema/preview/DevPreview/MicrosoftTeams.schema.json",
  "manifestVersion": "devPreview",
  "version": "1.0.0",`
