### ISSUE TITLE
Docs say to use manifestVersion 1.12, or 1.13 but neither are supported by AppStudio

### ISSUE THREAD

**Issue by AndrewCraswell** [MicrosoftDocs/msteams-docs#6380]
Our team was attempting to migrate from manifest version `1.11` to `1.13` to experiment with MetaOS. However, after updating the manifest with either `1.12` or `1.13` as mentioned in the docs, App Studio now gives an error when trying to create an app using out manifest. The error message says that only versions <=1.11 are recognized, and therefore our version is invalid.

Is this documented somewhere? Is the validation process in App Studio wrong? And since version `1.11` is no longer mentioned in the docs, is it still supported??

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f94a488-d636-92b3-21eb-c88744c8f272
* Version Independent ID: 7b3413f4-9ade-accf-5cb2-83fead11a32a
* Content: [Manifest schema reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema)
* Content Source: [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/resources/schema/manifest-schema.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by sayali-MSFT** [comment]
@AndrewCraswell -We are looking into this I will get back to you soon.

**Comment by ChetanSharma-msft** [comment]
@AndrewCraswell - Please check and let us know whether you are still facing the issues?

**Comment by AndrewCraswell** [comment]
Thanks for the clarification. I think this resolves the issue.
