### ISSUE TITLE
Document values for userRole

### ISSUE THREAD

**Issue by aosolis** [MicrosoftDocs/msteams-docs#6381]
Please document the possible values for userRole property returned by getConversationMembers

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca47e045-6669-e130-c75a-df31ab2fa3e8
* Version Independent ID: de5e719f-c97a-0fee-c83d-f6ca176191b2
* Content: [Get Teams specific context for your bot - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/get-teams-context?tabs=dotnet)
* Content Source: [msteams-platform/bots/how-to/get-teams-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/bots/how-to/get-teams-context.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by sayali-MSFT** [comment]
We are looking into this I will get back to you soon.

**Comment by ChetanSharma-msft** [comment]
We have tried it using Guest user as well but getting the sample userRole as "user".
So, we will check with the engineering team, for other possible values and update the document accordingly.

**Comment by v-spharish** [comment]
Waiting for Chetan's input on the documentation upgradation.
