### ISSUE TITLE
I'm unable inspect teams mobile client

### ISSUE THREAD

**Issue by Niegrozny** [MicrosoftDocs/msteams-docs#6386]
Much more like last time (https://github.com/MicrosoftDocs/msteams-docs/issues/4795#issue-1072079632), I'm unable to inspect teams mobile app. 

I've got dev preview enabled, and I can successfully view all the tabs from chrome, but I don't see any (com.microsoft.skype.teams.dev) from the teams app (my tab app is open while I'm checking)

Teams version I've got is 1416/1.0.0.2022331702/0623
Device SM-G781B

**Comment by sayali-MSFT** [comment]
@Niegrozny - We are looking into this I will get back to you soon.

**Comment by Niegrozny** [comment]
I've done that already (I've stated this in the OP). It was working before but now (maybe teams update) it doesn't

**Comment by sayali-MSFT** [comment]
@Niegrozny -We are checking this. Are you getting same as given below?
![image](https://user-images.githubusercontent.com/93527375/178234244-2d67d3cb-65a7-494f-99c2-3b64b0d14a37.png)

**Comment by sayali-MSFT** [comment]
@Niegrozny -Could you please confirm if your issue has resolved or still looking for any help?

**Comment by ChetanSharma-msft** [comment]
@Niegrozny - Could you please confirm whether you are getting same result as share above ?

**Comment by Niegrozny** [comment]
Yes, only difference is that I can see also my tabs from chrome for mobile

**Comment by sayali-MSFT** [comment]
Ok. We are checking it internally and let you know if we get any updates.

**Comment by ChetanSharma-msft** [comment]
Hello @Niegrozny - Are you facing the same issue in Teams Desktop Client?
Also, are you trying to display the contents from this domain **"com.microsoft.skype.teams.dev"** in your tab ?

Because Teams Tab uses IFrame, while showing the content, so it blocks the sites or domain which are not Iframable or not configured in the manifest file.

Please check & let me know if you need any further assistance.

**Comment by ChetanSharma-msft** [comment]
@Niegrozny - Are you able to see the tab in mobile client & not able to see it in inspect window ?

**Comment by sayali-MSFT** [comment]
@Niegrozny -Could you please share the screenshots if possible?

**Comment by Niegrozny** [comment]
![chrome_XzyrGzvzdT](https://user-images.githubusercontent.com/35895713/179170184-8d754ed0-a9c5-40f4-99ae-b3b3e1351c01.png)

**Comment by sayali-MSFT** [comment]
@Niegrozny - We are able to repro that issue , We have raised bug for the same and concerned team is looking into it. We will inform you once we get any update.

**Comment by sayali-MSFT** [comment]
@Niegrozny -Issue is Resolved with  Latest Canary 2nd September Build (Version 1416/1.0.84.2022381101 (2022381111)
Could you please check it once and confirm?

**Comment by Niegrozny** [comment]
I confirm. Working fine :)

**Comment by sayali-MSFT** [comment]
@Niegrozny - Could you please share your valuable feedback via [Microsoft Teams Developer Feedback](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR7iCOpS5_b9Nqmwx43u5rtZUOThVR081SllSR05aSDQxQ0tUMDVPTVIxTi4u) link.
