### ISSUE TITLE
Teams SPFx app keeping the SharePoint Context of the previously logged user in web client

### ISSUE THREAD

**Issue by Niegrozny** [MicrosoftDocs/msteams-docs#6387]
Steps to reproduce:

1. Login as User1 to the Teams web client and go to custom SPFx app that pulls some data from SPO list
2. Logout form Teams web client and login as User2 who do not have the access to the items on the SPO list and go to same custom SPFx 

Expected result:
1. User2 doesn't get back the list items (as she has no permissions)

Actual result:
1. User2 gets the items, because the request for the items is done with the context of the User1

**Comment by sayali-MSFT** [comment]
@Niegrozny - We are not able to repro the scenario. Could you please share the sample or any refer document.so that we can investigate from our end?

**Comment by sayali-MSFT** [comment]
@Niegrozny - Could you please confirm if your issue has resolved or still looking for any help? 
Thanks!

**Comment by ChetanSharma-msft** [comment]
Hello @Niegrozny - Please confirm whether you need any further assistance or your issue has already resolved ?

**Comment by Niegrozny** [comment]
Than clearly you tested the wrong thing.

It really is just as stated in the OP, and happens everytime. I believe you have not checked it properly, or misunderstood the steps to reproduce this error.

Two different accounts, Teams tabs app written using SPFx and with SharePoint as backend for data.

When you are first logged to Teams web client with account no.1 than logout from teams and login as user no.2 -  Teams tab app will still be using account no.1 to connect to SharePoint.

Teams app was created using https://docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?tabs=vscode%2Cviscode&tutorial-step=4

Users are facing this problem, when they are using the app with their regular account, and relog with their admin account to do the additional tasks - the rest api requests to SharePoint still uses authorization token from their regular account.

**Comment by sayali-MSFT** [comment]
@Niegrozny -Thanks for more details. We are trying to setup code as per instruction and let you know.

**Comment by sayali-MSFT** [comment]
@Niegrozny -We tried to setup the code but got the error. We are checking this internally and let you know.

**Comment by sayali-MSFT** [comment]
@Niegrozny - We are unable to repro the issue, After publishing the app it is showing the app for both users.
Please find attached video and also please confirm is it right scenario as you mention above.

https://user-images.githubusercontent.com/93527375/183397565-7e2ff5e2-a232-46f4-be58-506fc834cd8f.mp4

**Comment by ChetanSharma-msft** [comment]
@Niegrozny - Can you please confirm if above is the right scenario as you mention above ?

**Comment by Niegrozny** [comment]
It's not covering the right scenario. 
Second user should login in the same browser (not in private mode)

https://user-images.githubusercontent.com/35895713/183608906-0743bd21-1cdf-4213-b8c9-daf4737ff679.mp4

**Comment by sayali-MSFT** [comment]
We are able to repro that issue , We have raised bug for the same and concerned team is looking into it. We will inform you once we get any update. Thanks!

**Comment by ChetanSharma-msft** [comment]
Hello @Niegrozny - We have raised a new issue on SharePoint side.
Please track your issue here: https://github.com/SharePoint/sp-dev-docs/issues/8634
