### ISSUE TITLE
Suggestion: Add a TeamsFx SDK scenario - Use TeamsFx as auth provider with Microsoft Graph Toolkit

### ISSUE THREAD

**Issue by MuyangAmigo** [MicrosoftDocs/msteams-docs#6388]
The [Microsoft Graph Toolkit (mgt)](https://aka.ms/mgt) library is a collection of authentication providers and UI components powered by Microsoft Graph. 

The `@microsoft/mgt-teamsfx-provider` package exposes the `TeamsFxProvider` class which uses `TeamsFx` class to sign in users and acquire tokens to use with Microsoft Graph.

Suggestion:
Can we add some documentation for this scenario? It will greatly help developers who are using Microsoft Graph Toolkit and want to use TeamsFx SDK as an authentication provider.

Reference content can be found here: https://github.com/SLdragon/msteams-docs/pull/1/files

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40d33c5e-5f61-f2e4-d619-170fa263c626
* Version Independent ID: 40d33c5e-5f61-f2e4-d619-170fa263c626
* Content: [TeamsFx SDK - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-sdk)
* Content Source: [msteams-platform/toolkit/TeamsFx-SDK.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-SDK.md)
* Service: **msteams**
* GitHub Login: @MuyangAmigo
* Microsoft Alias: **nintan**

**Comment by Meghana-MSFT** [comment]
@MuyangAmigo - Thank you for the suggestion. We are looking into it. We will update you.

**Comment by SLdragon** [comment]
@Meghana-MSFT , I also create a PR in msteams-docs repo, you can review this PR directly, thanks!
https://github.com/MicrosoftDocs/msteams-docs/pull/6395

**Comment by MuyangAmigo** [comment]
@Meghana-MSFT Do you think it makes sense to also add some thing in Teams Platform doc on TeamsFx SDK page: https://docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-sdk

@SLdragon proposed a change and shared above.

Let us know, thanks!

**Comment by Meghana-MSFT** [comment]
The document is updated.

**Comment by SLdragon** [comment]
Thanks, my PR has been merged and the document is also updated!

**Comment by Meghana-MSFT** [comment]
We are closing this issue. Please feel to reopen the issue again if you have any queries. Thank you.
