### ISSUE TITLE
Video not working properly - The only thing I can see is a white page in the video

### ISSUE THREAD

**Issue by Talhasen** [MicrosoftDocs/msteams-docs#6393]
[Enter feedback here]
Video not working properly - The only thing I can see is a white page in the video

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90ff2a84-a8bc-9259-d37d-622b102df75b
* Version Independent ID: e3b53e27-2946-189c-623b-9df704ea8f12
* Content: [Create an Incoming Webhook - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-incoming-webhook)
* Content Source: [msteams-platform/webhooks-and-connectors/how-to/add-incoming-webhook.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/webhooks-and-connectors/how-to/add-incoming-webhook.md)
* Service: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Prasad-MSFT** [comment]
Hi @Talhasen - Could you please provide any repro steps or the card you are using so that we can try once from our end?

**Comment by ChetanSharma-msft** [comment]
Hello @Talhasen - Are you talking about below section video ?
**"See the following video to learn how to create an Incoming Webhooks:"**

If yes, we have played the video and it's working fine.

If not, please elaborate your requirements so that we can further investigate your issue?
