### ISSUE TITLE
Are the instructions to enable sideloading correct?

### ISSUE THREAD

**Issue by aosolis** [MicrosoftDocs/msteams-docs#6396]
The instructions refer to turning on the "Enable interaction with custom apps" policy, which allows users to use sideloaded apps. But it doesn't mention the app setup policy to allow "Upload custom apps",which is what actually allows sideloading the app to begin with.

https://docs.microsoft.com/en-us/microsoftteams/app-policies#app-setup-policies

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e17314b-09a2-197f-da9e-3a50697c182e
* Version Independent ID: 5e17314b-09a2-197f-da9e-3a50697c182e
* Content: [Set up your dev environment for extending Teams apps across Microsoft 365 - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/m365-apps/prerequisites)
* Content Source: [msteams-platform/m365-apps/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/m365-apps/prerequisites.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by sayali-MSFT** [comment]
We will look into it and get back to you.

**Comment by sayali-MSFT** [comment]
@surbhigupta12 - Could you please help us to update the document-
In the below document section add as 4 point
4. Also the[ app setup policy](https://docs.microsoft.com/en-us/microsoftteams/app-policies#app-setup-policies) to allow Upload custom apps to enable sideloading.

Document-https://docs.microsoft.com/en-us/microsoftteams/platform/m365-apps/prerequisites#prepare-a-developer-tenant-for-testing
