### ISSUE TITLE
Bot not receiving all channel messages as described in the document

### ISSUE THREAD

**Issue by blackchoey** [MicrosoftDocs/msteams-docs#6397]
Creating this issue on behalf of @tcorvazier, who found that bot is not receiving all channel messages (unless it's explicity mentioned) despite having the ChannelMessage.Read.Group RSC permission.

Based on the document, with the ChannelMessage.Read.Group RSC permission, bot is expected to receive all messages even when not mentioned.

Please help with this issue. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e0acfd2-0965-65f4-2200-ca06424a3976
* Version Independent ID: fd7f72fe-5dba-369a-c436-6140d232ad44
* Content: [Receive all channel messages with RSC - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/channel-messages-with-rsc?tabs=dotnet)
* Content Source: [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md)
* Service: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **lajanuar**

**Comment by ChetanSharma-msft** [comment]
@blackchoey - Please let us know if you still need any help here or shall we close it, if you issue has already resolved?

**Comment by blackchoey** [comment]
@tcorvazier please enable Public Developer Preview as suggested above and let us know whether you still need any help here

**Comment by Nivedipa-MSFT** [comment]
@blackchoey, @tcorvazier - Have you checked this in Public Developer Preview?

**Comment by dooriya** [comment]
The RSC bot is still not working after changing the Teams Client to Developer Preview. I still need to @botname to invoke the command

**Comment by ChetanSharma-msft** [comment]
@dooriya - Thanks for reporting the issue.
We will investigate on it and get back to you.

**Comment by Nivedipa-MSFT** [comment]
@dooriya - Could you please share the screen recording of your issue?

**Comment by Nivedipa-MSFT** [comment]
@dooriya - Could you please test this sample once at your end and let us know that its working or not?

**Comment by ChetanSharma-msft** [comment]
@dooriya - Did you get chance to try on the above shared code base ?
