### ISSUE TITLE
Either fully document isFullScreen=true, or mark it as reserved and not for use by 3P/LOB apps

### ISSUE THREAD

**Issue by aosolis** [MicrosoftDocs/msteams-docs#6407]
isFullScreen=true and has effects other than what is documented here:
<img width="617" alt="image" src="https://user-images.githubusercontent.com/767208/177921545-46d9bee4-3295-47a3-a51b-eba43d240458.png">

For example, for LOB apps it removes the title from task modules.

Please either fully document this, or recommend that apps not use it at all (that is, it's only for internal apps). Otherwise we get incidents when developers mistakenly set this to true, and encounter one of these side effects.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f94a488-d636-92b3-21eb-c88744c8f272
* Version Independent ID: 7b3413f4-9ade-accf-5cb2-83fead11a32a
* Content: [Manifest schema reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema#isfullscreen)
* Content Source: [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/resources/schema/manifest-schema.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Prasad-MSFT** [comment]
We are checking this. We will redirect it to appropriate team accordingly.

**Comment by Prasad-MSFT** [comment]
@surbhigupta12 - It would be better to add a note saying:
For LOB apps `isFullScreen=true` removes the title from task modules. So its recommend that apps should not use it at all (that is, it's only for internal apps)
