### ISSUE TITLE
Switching from one team to another doesn't always update the member list when in fullscreen

### ISSUE THREAD

**Issue by hibbie** [MicrosoftDocs/msteams-docs#641]
This problem occurs when I have the team member list open and the Teams application window is maximized.  When I switch from one team to another the member list does always update.  It will randomly keep the same member list from team to team.  Closing the member list and opening it again will update with the proper current team member list.

**Comment by Wajeed-msft** [comment]
@hibbie - Could you please share some screenshots of this issue to help repro at our end?

**Comment by hibbie** [comment]
Sure thing, let me know if you need more info.

Here's my team's group with 9 members as I would expect.

![1](https://user-images.githubusercontent.com/201506/57729952-fcb06c00-765c-11e9-91f7-a1778e8610ce.jpg)

When I click into the company's general group which should have 35 users it still shows my 9 members from the Python team.

![2](https://user-images.githubusercontent.com/201506/57730000-1d78c180-765d-11e9-82f7-c9713ac4d05c.jpg)

When I close the window and open it again it shows the correct number of people.  

![3](https://user-images.githubusercontent.com/201506/57730024-29648380-765d-11e9-9a95-a676a9652cb2.jpg)

**Comment by Abhijit-MSFT** [comment]
In case if you are not on the latest version of Teams, can you please try on latest version. we bunch of people tried it and this works fine for all of us.

**Comment by hibbie** [comment]
Hi there,  I just checked it and still works the same as it did before.  I'm on Windows 10 1903 / 18362.145 and MS Teams 1.2.00.13765 (64-bit)

**Comment by Wajeed-msft** [comment]
Could you please share your Teams logs (by pressing ctrl+alt+shift+1)?

**Comment by hibbie** [comment]
Actually the issue seems to have stopped.  The People pane now closes when I switch to a different team.  The issue I had is no longer present.  I am still on Teams 1.2.00.13765 and Win10 1903 18922.100.  I'd share my logs but I don't think our IT dept would be cool with that.
