### ISSUE TITLE
Suggestions for documentation

### ISSUE THREAD

**Issue by t-nainaseth** [MicrosoftDocs/msteams-docs#6418]
1. Running the extended app in Office took at least 5 days - can be called out in documentation
2. Please add npm downloading step to documentation, step is missing. Seems only npm version 14 is supported, will be good to call out.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2cf31a5-621a-eeac-26c9-89ada49466c0
* Version Independent ID: b2cf31a5-621a-eeac-26c9-89ada49466c0
* Content: [Extend a Teams personal tab app across Microsoft 365 - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/m365-apps/extend-m365-teams-personal-tab?tabs=manifest-teams-toolkit)
* Content Source: [msteams-platform/m365-apps/extend-m365-teams-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/m365-apps/extend-m365-teams-personal-tab.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by sayali-MSFT** [comment]
@t-nainaseth - We are looking into this I will get back to you soon.

**Comment by sayali-MSFT** [comment]
@t-nainaseth - For npm downloading steps we have separate document for this.
https://docs.microsoft.com/en-us/javascript/api/overview/msteams-client?view=msteams-client-js-latest

Could you please share the steps you followed for extended App in Office took at least 5 days?

**Comment by ChetanSharma-msft** [comment]
@t-nainaseth - Can you please share the steps that you have followed and took 5 days for you ?

npm downloading steps are mentioned in below documentation:

Reference document link: https://docs.microsoft.com/en-us/javascript/api/overview/msteams-client?view=msteams-client-js-latest

**Comment by t-nainaseth** [comment]
Thanks - I followed the steps here Extend Teams apps across Microsoft 365 (preview) - Teams | Microsoft Docs<https://docs.microsoft.com/en-us/microsoftteams/platform/m365-apps/overview?view=msteams-client-js-latest>

Best,
Naina

**Comment by sayali-MSFT** [comment]
@t-nainaseth - We will check it from our end and update it accordingly.

**Comment by sayali-MSFT** [comment]
@t-nainaseth -What are the challenges facing while Running the extended app in Office?
Ideally it will take 1 day to Run the extended app in office.
Could you share feedback on document so we will update it accordingly, If required.

**Comment by t-nainaseth** [comment]
Hi Sayali,

The challenge I faced was that after following the full documentation, my extended app showed up in office sidebar only after 5+ days. There were no issues with the steps, but we should highlight the fact that it may take a few days for the app to show up on Office sidebar as that was the case with me.

Otherwise, gives a wrong impression to developer that they might have made a mistake or that the SDK may not be working properly.

Best,
Naina

**Comment by sayali-MSFT** [comment]
@t-nainaseth -We are followed the steps to add Teams Extended app in office and the App will shown in same day.
Meanwhile we will check this with engineering team , why it will take 5 days and let you know.

**Comment by sbtron** [comment]
FYI the pre-requisites page calls this out. If you are just creating a new dev tenant and enrolling for targeted releases then it may take up-to 5 days for the targeted releases to be available on that tenant. This delay is expected to go away once app support is available outside of Targeted Releases.
https://docs.microsoft.com/en-us/microsoftteams/platform/m365-apps/prerequisites?view=msteams-client-js-latest#enroll-your-developer-tenant-for-office-365-targeted-releases

![image](https://user-images.githubusercontent.com/967499/180306857-a546061f-a27a-4f2f-99b9-6f9a7b24f8eb.png)

**Comment by t-nainaseth** [comment]
Thanks for sharing - good to know!

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.
