### ISSUE TITLE
[Doc-Bug] Message extension - Download/Read attachments

### ISSUE THREAD

**Issue by SubbaReddi** [MicrosoftDocs/msteams-docs#6419]
Implemented message action to create ticket based channel post. Channel post contains message with attachment. When we trigger message action, attachment details are not sending as part of turncontext invoke activity. I see it as expected behavior. Adding note in documentation will help.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: efcdf768-1513-2249-b344-bf38ef64c70d
* Version Independent ID: 415b5d57-2d41-9540-55a7-2a33a4315e37
* Content: [Define message extension action commands - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/action-commands/define-action-command?tabs=AS)
* Content Source: [msteams-platform/messaging-extensions/how-to/action-commands/define-action-command.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/messaging-extensions/how-to/action-commands/define-action-command.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **anclear**

**Comment by Meghana-MSFT** [comment]
We are looking into this we will update you.
