### ISSUE TITLE
Most page spent on Analytics

### ISSUE THREAD

**Issue by crtjr64** [MicrosoftDocs/msteams-docs#6423]
Half of the documentation is on the analytics and not the details of the portal and how each sections works and what's required and what is not. For example, the examples of Microsoft professionals on Youtube first say you don't need a configuration page when adding an app then another one says you can use https://dev.azure.com/tab but this hasn't worked. Also, a Microsoft professional on a Microsoft Community website claims you can save changes in the portal and it would automatically apply to currently published projects in a Channel but  I made the above change and it still reacts the same way.

Once again, you show little concern for your development community with all of these incorrect or dated examples wasting people's time. How is it that when you developed the portal and step by step instruction on each item on each section wasn't required. Its like we got to learn by trial and error which is a huge waste of time.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7da63b6f-15d7-a6dd-82fc-d183afaeb816
* Version Independent ID: 82d1ca83-28dd-220e-ab0c-a4833f8f8143
* Content: [Manage your apps with the Developer Portal - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/teams-developer-portal)
* Content Source: [msteams-platform/concepts/build-and-test/teams-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/build-and-test/teams-developer-portal.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **surbhigupta**

**Comment by crtjr64** [comment]
One more problem. My custom app has been published to Teams with a very simple configuration but it continues to get the error "We couldn't save your tab settings. Please try again." and thus it doesn't run in the Team channel. In the personal tab it runs fine, but not in the Group Team. It is using my developer  tenant and I removed myself as team owner and added myself as a member and all members with access to this channel can update the tab. In fact all options are turned on. When this runs, the alert box pops up, but then I get the error message stated above.

This is the configuration code:

```
function initializeTeams() {
     microsoftTeams.app.initialize().then(() => {
        microsoftTeams.pages.config.registerOnSaveHandler((saveEvent) => {
            microsoftTeams.pages.config.setConfig({
                "suggestedDisplayName": "My Tab"
            });
            alert("Save Event");
            saveEvent.notifySuccess();
        });
        microsoftTeams.pages.config.setValidityState(true);
    });
}

initializeTeams();
```

**Comment by sayali-MSFT** [comment]
@crtjr64 - We are looking into this I will get back to you soon.

**Comment by sayali-MSFT** [comment]
> One more problem. My custom app has been published to Teams with a very simple configuration but it continues to get the error "We couldn't save your tab settings. Please try again." and thus it doesn't run in the Team channel. In the personal tab it runs fine, but not in the Group Team. It is using my developer tenant and I removed myself as team owner and added myself as a member and all members with access to this channel can update the tab. In fact all options are turned on. When this runs, the alert box pops up, but then I get the error message stated above.
> 
> This is the configuration code:
> 
> ```
> function initializeTeams() {
>      microsoftTeams.app.initialize().then(() => {
>         microsoftTeams.pages.config.registerOnSaveHandler((saveEvent) => {
>             microsoftTeams.pages.config.setConfig({
>                 "suggestedDisplayName": "My Tab"
>             });
>             alert("Save Event");
>             saveEvent.notifySuccess();
>         });
>         microsoftTeams.pages.config.setValidityState(true);
>     });
> }
> 
> initializeTeams();
> ```

@crtjr64 - Could you please share the manifest file so that we can try it from end? 
Thanks!

**Comment by sayali-MSFT** [comment]
@surbhigupta12 -Could you please help us for the update the document?
here as User suggest there is lots of thing related to analytics and report .User want Developer portal section wise information in this document. So need to update the document section wise.
Let us know if you have any help from our end.

**Comment by sayali-MSFT** [comment]
Have you added Resource URL? If not , Could you please add and try it once?

"webApplicationInfo": {
"id": "433dc88a-1657-470d-9999-998b61807530",
"resource": ""
},

Ref Doc- https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema#webapplicationinfo

**Comment by crtjr64** [comment]
Ok but mind you I built this with Developer Portal. If it isn't there it's because the Developer Portal was not intuitive enough for me to ensure its there in the manner the directions stated on this page. Also, should the documentation be updated considering the App portal has been replaced by Developer Portal?

**Comment by sayali-MSFT** [comment]
Check Tab Settings
Ensure that team members can add, edit and delete tabs. If this setting is disabled, that might explain why Teams couldn’t save your tab settings.

1. Navigate to Manage team, go to Settings, and then expand Member Permissions.
2. Locate Allow member to create, update and remove tabs.Allow member to create, update and remove tabs.

![image](https://user-images.githubusercontent.com/93527375/178973611-b241b273-97f9-4ca1-92af-01f6099e4807.png)

3. If the option is disabled, enable it, save the changes and check if the error is gone.

Here Documentation update for the App portal has been replaced by Developer Portal.-
https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/app-studio-overview

**Comment by crtjr64** [comment]
Thanks, but this is one of the first options set
![image](https://user-images.githubusercontent.com/3522358/179060537-1c085259-5323-4c08-8f0b-792e4aa32ae0.png)

**Comment by crtjr64** [comment]
Note that the above is clicked and after I added a fake address (as per instructions) to the webApplicationInfo resource even though I'm not using SSO.

![image](https://user-images.githubusercontent.com/3522358/179129482-7dfacc8c-572f-4b21-aff3-201ec6ab284d.png)

**Comment by sayali-MSFT** [comment]
@crtjr64 -Clear the App Cache.
If the app cache is causing this issue, clearing it should immediately solve the problem.

1. Right-click on the Teams icon in your taskbar and select Quit.
2. Then type %AppData%\Microsoft\teams in the Windows Search bar to open the Teams folder.
3. Next, delete all the files stored in the following folders:

%AppData%\Microsoft\teams\application cache\cache
%AppData%\Microsoft\teams\blob_storage
%AppData%\Microsoft\teams\databases
%AppData%\Microsoft\teams\cache
%AppData%\Microsoft\teams\gpucache
%AppData%\Microsoft\teams\Indexeddb
%AppData%\Microsoft\teams\Local Storage
%AppData%\Microsoft\teams\tmpdelete teams cache files
![image](https://user-images.githubusercontent.com/93527375/179207639-88614cbe-2e76-4f2c-b47b-3f5685c0232d.png)

4. Restart Teams and check if you can add a new tab now.

If you can’t add a new tab to Microsoft Teams, ensure the option to add, edit and remove tabs is active. Then, change the user account permissions, use Teams for Web, update the desktop app and clear the cache.

**Comment by crtjr64** [comment]
I didn't say anything about cache, and I have been using the web version the entire time. None of the communication I presented was while using the desktop version.

**Comment by sayali-MSFT** [comment]
@crtjr64 -We are unable to repro the scenario, We are checking it internally and let you know once we get any updates.

**Comment by sayali-MSFT** [comment]
You need to specify a `contentUrl` for your tab. That is pretty much the one required property:
https://docs.microsoft.com/en-us/javascript/api/@microsoft/teams-js/pages.instanceconfig?view=msteams-client-js-latest#@microsoft-teams-js-pages-instanceconfig-contenturl
 
Ideally, you are also specifying a `suggestedDisplayName` (based on the content being pinned) and an `entityId` (used for deep linking). Here are the full set of tab config properties:
![MicrosoftTeams-image (83)](https://user-images.githubusercontent.com/93527375/180381817-27d3f8da-4588-46a4-b375-cffa496f7ed8.png)

**Comment by ChetanSharma-msft** [comment]
Hello @crtjr64 - Please let us know if you need any further details or shall we close this issue?
