### ISSUE TITLE
More wasting of developers time

### ISSUE THREAD

**Issue by crtjr64** [MicrosoftDocs/msteams-docs#6424]
I followed your instructions line by line and the first surprise was again, this is a React template (I should have known) and when I tried to build it, first got a alert box saying "Do you want to save the changes you made to launch.json" and the second after it completed, I received the error:

**Uncaught SyntaxError SyntaxError: Invalid or unexpected token
    at (program) (https://statics.teams.cdn.office.net/hashedjs-launcher/launcher.83a2bdf97607d16ed719.js:1:1)**
    
 I have done no coding. Now do I debug your app or do I start all over... the time spent thus far was simply wasted. Where's just a plain example of how to build these applications instead of the influencer and sell jobs? This is why you need a "code of conduct" reminder for these developers because your work is frustrating us. I've already attempted to strip code out of here and add to another application, and right now I'm busy debugging that. So in the meantime, I try to start all over with this and I';m right back  in the same place. Its been 3 days of nothing but getting an app published on Teams and still it hasn't happened and I've followed every video and doc I could find, wasting hours watching videos where 90% of the instruction has nothing to do with what I'm trying to resolve and I remain in the same position. My company is very interested in integrating with Teams, but you're making it very difficult to recommend it as a viable solution for any developers except your partners.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e473e1f3-69f5-bcfa-bcab-54b098b59c80
* Version Independent ID: e473e1f3-69f5-bcfa-bcab-54b098b59c80
* Content: [Hello World with JavaScript - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-javascript?tabs=vscode%2Cvsc%2Cviscode)
* Content Source: [msteams-platform/sbs-gs-javascript.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/sbs-gs-javascript.yml)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Nivedipa-MSFT** [comment]
@crtjr64 - We will try to setup this sample and let you know the updates.

**Comment by Nivedipa-MSFT** [comment]
@crtjr64 - We have tried this. Followed the steps in document. It was working fine at our end.

**Comment by crtjr64** [comment]
I'm well past this. It did not work for me until I made some changes to the Manifest file and the code to use Teams SDK 2.0. That's why it failed for me. I'm dealing with another error. Is it possible that I cannot publish to teams with this website? https://tunstallsoftwarellc.azurewebsites.net because it's domain is azurewebsites.net?

**Comment by Nivedipa-MSFT** [comment]
@crtjr64 - Have you added domain of website in validomain list in manifest?
FYI Browsers same-origin policy restriction prevents webpages from making requests to different domains than the served web page. So, you can redirect the configuration or content page to another domain or subdomain. Your cross-domain navigation logic needs to allow the Teams client to validate the origin against a static validDomains list in the app manifest when loading or communicating with the tab.

**Comment by ChetanSharma-msft** [comment]
@crtjr64 - Hope you are doing well !!
Please let us know whether your issue has resolved or still need any help here ?
