### ISSUE TITLE
Our users report crashes of Teams on Windows 7

### ISSUE THREAD

**Issue by pablodiazgutierrez** [MicrosoftDocs/msteams-docs#643]
Random crashes occur for one of our users when running our add-on (WA104382005). The same setup works just fine via Teams for web, or Teams on Windows 10/Mac. What other information can we provide to facilitate reproduction on your end?

**Comment by billbliss** [comment]
Ask your users to press Ctrl-Shift-Alt-1 (Cmd-Shift-Alt-1 on Mac). This will save three logs in the Downloads folder. Look at those and see if you find anything unusual. Without a good repro scenario I'm not sure what else to suggest.

Any reason to suspect memory issues? Desktop client typically runs longer than browser clients and thus uses more memory. It's not common but it does happen.

**Comment by pablodiazgutierrez** [comment]
Thanks @billbliss, we'll ask for those logs. I don't think this should be a memory issue due to the app running a long time: They say it happens pretty quickly once they open any of our tabs, within seconds to minutes.

Will report with more.

**Comment by Wajeed-msft** [comment]
Please re-open with logs.
