### ISSUE TITLE
App publication failed because the consent pop-up window is getting blocked by the browser

### ISSUE THREAD

**Issue by jouhami** [MicrosoftDocs/msteams-docs#6430]
Our Teams app validation has failed because the consent pop-up is getting blocked by the browser. The validation team reported this issue according to [this certification policy 1100.5](https://docs.microsoft.com/en-us/legal/marketplace/certification-policies#11005-customer-control).

We were inspired by the sample [here](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/tab-channel-group-sso-quickstart/js) to add SSO authentication to our apps.

I was able to reproduce this by cloning and running the sample above.

I think the consent pop-up must be excluded from other pop-ups that may block the app validation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 410609cf-c930-72de-319d-351212f71b8c
* Version Independent ID: 410609cf-c930-72de-319d-351212f71b8c
* Content: [Code configuration for enabling SSO for tabs - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/tab-sso-code)
* Content Source: [msteams-platform/tabs/how-to/authentication/tab-sso-code.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/tabs/how-to/authentication/tab-sso-code.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by ChetanSharma-msft** [comment]
@jouhami - Thanks for reporting this issue.
We will check it from our end and redirect to doc team accordingly.

**Comment by ChetanSharma-msft** [comment]
@jouhami - How are you validating the app?
Can you please share the repro steps or reference doc?

**Comment by jouhami** [comment]
We submitted the app in the Partner Center and the validation Team reported the issue

**Comment by ChetanSharma-msft** [comment]
@jouhami - Regarding "**consent pop-up is getting blocked by the browser**"
Can you please share the screenshots for this error ?

Meanwhile, we will also try to setup the code and check on it.

**Comment by Prasad-MSFT** [comment]
Hi @jouhami - We tried with the below [sample](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/tab-sso/csharp), and it worked as expected without blocking the consent popup as follows:
![image](https://user-images.githubusercontent.com/62237649/178702509-13ddcb6f-b9e3-4b7d-aed3-3ea2512f8a62.png)

![image](https://user-images.githubusercontent.com/62237649/178702575-c9d020a6-b96d-429e-a7b5-791bdf7dde99.png)

**Comment by jouhami** [comment]
Here is a screenshot of the error : 

![image](https://user-images.githubusercontent.com/12663150/178705268-93baf4d7-df4e-4d18-aae8-37ea8ba8f0c2.png)

I see you tested with the csharp sample while I am testing with [the nodejs sample](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/tab-channel-group-sso-quickstart/js).

Please make sure your browser is not already allowing the pop-ups from the domain `teams.microsoft.com`.

Here is my browser settings for **Pop-ups and redirects** :

![image](https://user-images.githubusercontent.com/12663150/178706124-ffd8f9db-1ac8-4e2d-8d2e-b9688028a86a.png)

**Comment by Prasad-MSFT** [comment]
@jouhami -To avoid triggering the browser's popup blocker, app developers need to ensure that they only call authenticate API from the call stack of a user input handler (e.g. click, key press, etc.). That's discussed here:
https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-tab-aad#initiate-authentication-flow
 
The way this is typically achieved is by putting a "Sign in" button in the page when an auth popup needs to be shown and then calling the authenticate API only when the user clicks on the button.

**Comment by Prasad-MSFT** [comment]
@jouhami - We tried to repro the issue by following [this](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/tab-channel-group-sso-quickstart/js) sample as mentioned and we are getting same error. 
![image](https://user-images.githubusercontent.com/62237649/179904183-e5b64144-842e-40bf-9688-f63e57b9a230.png)
![image](https://user-images.githubusercontent.com/62237649/179904247-68a99145-949b-465d-92ca-cb9903b96933.png)
We are checking this internally and will update accordingly.

However this [sample](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/tab-channel-group-sso-quickstart/csharp_dotnetcore) works fine.
![image](https://user-images.githubusercontent.com/62237649/179904448-0712b137-086c-46a7-bf1c-0dab97efe3e1.png)

**Comment by jouhami** [comment]
Does this mean that there is some actions we have to do from our end ?

**Comment by Benjiiim** [comment]
Hi Prasad, can you please give us a link to this PR?

**Comment by Prasad-MSFT** [comment]
Hi @Benjiiim - PFB the PR Link
https://github.com/OfficeDev/Microsoft-Teams-Samples/pull/403

**Comment by jouhami** [comment]
I don't understand how the changes in the PR should fix the problem. I always had the `HTTPS=false` during dev and we still have the issue.

**Comment by ChetanSharma-msft** [comment]
Hello @jouhami - It's not only related to Https =  false but there are couple of more changes that we have added like we need to start one more server to make the application work.

**Comment by ChetanSharma-msft** [comment]
@jouhami - Changes are merged, please verify once and let us know.

**Comment by jouhami** [comment]
I just tried with [the nodejs sample](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/tab-channel-group-sso-quickstart/js) and still getting the error  with consent pop-up window blocked.

**Comment by Prasad-MSFT** [comment]
Hi @jouhami - We checked again at our end, and it worked as expected. Attaching the snapshot below:
![image](https://user-images.githubusercontent.com/62237649/182842260-7313f997-c0f5-4a38-a90b-b769c2573d1b.png)

Could you please make sure you have correctly configured the Application ID URI and scopes as mentioned in recently updated READ ME file? Please do re-verify.
https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/tab-channel-group-sso-quickstart/js#register-your-application-with-azure-ad

**Comment by jouhami** [comment]
I just restarted from the beginning. Followed the instructions in the README to create the Azure application. Cloned the repo, updated the manifest with the Azure app Id and zipped the package. Still have the issue. 

![image](https://user-images.githubusercontent.com/12663150/182883273-dac43668-6adc-4895-8a3f-ff851fccfbdd.png)

If I allow the pop-up in the browser settings the tab is working properly.

The main issue here is that we do not see the "Almost there pop-up" as chown in [the comment above](https://github.com/MicrosoftDocs/msteams-docs/issues/6430#issuecomment-1187643715)

**Comment by jouhami** [comment]
I am facing the issue in Web client only. In Desktop/mobile I am getting the consent popo-up directly but the "Almost there" pop-up is never shown.

**Comment by Prasad-MSFT** [comment]
"Almost there" pop up shows up first time while signing it. It won't show next time onwards while using the tab.

**Comment by jouhami** [comment]
> "Almost there" pop up shows up first time while signing it. It won't show next time onwards while using the tab. It uses SSO to sign-in the user.

I agree. The user/admin has not consented yet so my understanding is that the "Almost there" pop-up should keep showing unless the user/admin consents to the requested permissions. Am I wrong ?

**Comment by Prasad-MSFT** [comment]
We tried without user/admin consent, but didn't get the "Almost there" pop-up.

**Comment by jouhami** [comment]
Is it the expected behavior ? According to this [comment](https://github.com/MicrosoftDocs/msteams-docs/issues/1898#issuecomment-662403549) the pop-up should show if we revoke consent.
Could you please share a link to the documentation about this pop-up if any ?

**Comment by Prasad-MSFT** [comment]
Please refer this doc: https://docs.microsoft.com/en-us/microsoftteams/app-permissions

**Comment by jouhami** [comment]
Any updates about this issue ?

**Comment by Prasad-MSFT** [comment]
We checked at our end, and it worked as expected. 
![image](https://user-images.githubusercontent.com/62237649/184889381-cc7fb9c3-bf7d-4a53-991a-8f9ad0cdd6a5.png)

Is there any other update you want?

**Comment by jouhami** [comment]
Yes please. I didn't get an answer for my question in [this comment](https://github.com/MicrosoftDocs/msteams-docs/issues/6430#issuecomment-1210409141). You said that you don't see the "Almost there" pop-up even if the user/admin has not consented. **Is it normal** ? I checked other apps already published in the store and they are having the same issue ([this application for example](https://teams.microsoft.com/l/app/1d041f16-ab49-4627-bfda-6b60ad2cab6a?source=app-details-dialog)) : consent-pop up blocked by the browsers (Chrome, Edge and Firefox) and no "Almost there" pop-up is shown.

**Comment by Prasad-MSFT** [comment]
We will check with engineering team if this is expected or not and will get back to you.

**Comment by jouhami** [comment]
Any updates ?

**Comment by Prasad-MSFT** [comment]
We are following up with engineering team. We will inform you once we have any update.
 Thanks!

**Comment by Prasad-MSFT** [comment]
@jouhami - We got update from engineering team that " If the getAuthToken API returning a token, then the app must already have the necessary consent and AAD is issuing a token". This happens when your app is registered in the same tenant that it's being used in. Cross-tenant apps will always show a prompt unless the user or admin have already consented.

**Comment by Prasad-MSFT** [comment]
We are closing this issue for now. Please feel free to reopen if required. Thanks!
