### ISSUE TITLE
Custom App (Messaging Extension) icon not responsive on mobile

### ISSUE THREAD

**Issue by someonelikeTIM** [MicrosoftDocs/msteams-docs#6431]
I have a messaging extension app published to the org catalog that is functional on desktop/web client but does not work on the mobile client. Tapping the icon does nothing when it should launch a task module (pop-up modal)

I cannot find any documentation referencing mobile-specific schema or requirements and google results come up empty.

![image](https://user-images.githubusercontent.com/40400490/178352827-6c5712d5-d28a-49ba-a0c8-c957f37120ed.png)

I am happy to share code and screenshots upon request

**Comment by ChetanSharma-msft** [comment]
@someonelikeTIM - Thanks for reporting this issue.
Can you please share your minimal manifest.json configuration for Messaging Extension?

We will also investigate on it and get back to you.

**Comment by Prasad-MSFT** [comment]
Hi @someonelikeTIM - We tried to repro this issue using the manifest shared and we are able to repro it. We have raised a bug for the same and engineering team is looking into it. We will inform you once we get any further update. Thanks!

**Comment by Prasad-MSFT** [comment]
Hi @someonelikeTIM - We tried again by updating MS Teams version and the ME started responding in Mobile devices. Engineering team is unable to repro it as well. PFB the attached video and MS Teams version details for reference.
MS Teams version:
![image](https://user-images.githubusercontent.com/62237649/179456628-bc593861-0720-46e3-add5-3b479dcffed8.png)

Repro video:

https://user-images.githubusercontent.com/62237649/179456680-506b2983-e810-45c5-a954-fea28477e73d.mp4

**Comment by someonelikeTIM** [comment]
@Prasad-MSFT I updated to the latest version and the issue persists. The version number does not match your screenshot. See below: 

![MicrosoftTeams-image](https://user-images.githubusercontent.com/40400490/180453472-edfa452a-19be-459a-ac07-e879ec36716f.png)

**Comment by Prasad-MSFT** [comment]
@someonelikeTIM - Is your mobile client iOS/Android? Is your Teams in Public ring or any internal ring?

**Comment by someonelikeTIM** [comment]
@Prasad-MSFT iOS and this is a custom app deployed to my org.

**Comment by Prasad-MSFT** [comment]
We checked it using iOS 15.5 and its working there as well. Please try to update MS Teams version and check if that helps.
Attaching the recording for reference:

https://user-images.githubusercontent.com/62237649/180958698-4176efaa-2627-42a0-ad4a-19e4a21fa6db.mp4

MS Teams version used:
![image](https://user-images.githubusercontent.com/62237649/180958812-e25a8da1-1fb0-425a-822a-740238b2e964.png)

**Comment by someonelikeTIM** [comment]
@Prasad-MSFT I have verified that I am on the same version of the mobile client, however, tapping the Bravo app icon still has no effect. I am not presented with this screen shown in your video:

![image](https://user-images.githubusercontent.com/40400490/181783241-0f93dae6-82c6-4e60-90d0-3b3667148a12.png)

Can you think of anything that would be preventing the app from launching, i.e. an azure policy configuration in our environment?

**Comment by Prasad-MSFT** [comment]
@someonelikeTIM - Could you please provide any console log/error you are getting?

**Comment by Prasad-MSFT** [comment]
@someonelikeTIM - Could you please try by removing your existing app and adding new app having different id and check if its responsive?

**Comment by Prasad-MSFT** [comment]
@someonelikeTIM - This issue is fixed. Please do verify.
Thanks!
