### ISSUE TITLE
Closing task module

### ISSUE THREAD

**Issue by aosolis** [MicrosoftDocs/msteams-docs#6432]
Please note that in the cases described below, the bot MUST return a 200 OK. "ignore the task/submit" message is merely shorthand for returning 200 OK with no body.

<img width="624" alt="image" src="https://user-images.githubusercontent.com/767208/178355328-0e94b94d-692f-4354-88ea-94b3d0e56c73.png">

We had a support request from a developer who thought the way to close a task module is to respond with  JSON with type "message" and value "".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 800b748d-fb81-8f4d-adc2-3ee610394346
* Version Independent ID: b1ebd031-c5cd-ffeb-d9b2-d752511900db
* Content: [Use Task Modules in Microsoft Teams bots - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/task-modules/task-modules-bots?tabs=nodejs#the-flexibility-of-tasksubmit)
* Content Source: [msteams-platform/task-modules-and-cards/task-modules/task-modules-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/task-modules-and-cards/task-modules/task-modules-bots.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Meghana-MSFT** [comment]
We are looking into this, we will update you.

**Comment by Meghana-MSFT** [comment]
@aosolis - We will ask the documentation team to update the document as below - 

None ignore the task/submit message(the bot MUST return a 200 OK).

Could you please confirm if this looks ok?

**Comment by Meghana-MSFT** [comment]
@aosolis - Could you please confirm if the above doc update content looks ok?
