### ISSUE TITLE
[Doc-enhancement] Content bubble notification URL - App id information missing in documentation

### ISSUE THREAD

**Issue by SubbaReddi** [MicrosoftDocs/msteams-docs#6433]
This is related to https://docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/api-references?tabs=dotnet#send-an-in-meeting-notification.

Following code was given in documentation to send meeting dialog(content bubble).
Activity activity = MessageFactory.Text("This is a meeting signal test");
activity.TeamsNotifyUser(true, "https://teams.microsoft.com/l/bubble/APP_ID?url=<url>&height=<height>&width=<width>&title=<title>&completionBotId=BOT_APP_ID");
await turnContext.SendActivityAsync(activity).ConfigureAwait(false);

But what we need to use for APP_ID. Is it Bot id or manifest id or from Teams admin center. Please mention the same in documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 805dc242-7b5a-cc81-ee0e-6acf0078a653
* Version Independent ID: 11c0e023-2514-9639-6052-2cbbbef50663
* Content: [Meeting apps API references - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/api-references?tabs=dotnet#send-an-in-meeting-notification)
* Content Source: [msteams-platform/apps-in-teams-meetings/API-references.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/apps-in-teams-meetings/API-references.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Prasad-MSFT** [comment]
Hi @surbhigupta12 , In this [document](https://docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/api-references?tabs=dotnet#examples), we should add another property name 'APP_ID' mentioning it refers to Bot Id that is declared in the manifest.
<html>
<body>


Property name | Purpose
-- | --
APP_ID | Bot Id declared in manifest.


</body>
</html>
