### ISSUE TITLE
Task Module not working in ios teams bot

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#6435]
Copied from: https://github.com/microsoft/BotBuilder-Samples/issues/3778

Copied this to Microsoft Teams repo for tacking. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 800b748d-fb81-8f4d-adc2-3ee610394346
* Version Independent ID: b1ebd031-c5cd-ffeb-d9b2-d752511900db
* Content: [Use Task Modules in Microsoft Teams bots - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/task-modules/task-modules-bots?tabs=nodejs)
* Content Source: [msteams-platform/task-modules-and-cards/task-modules/task-modules-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/task-modules-and-cards/task-modules/task-modules-bots.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by sayali-MSFT** [comment]
@Rajkumar235216 - We are looking into this we will get back to you soon.

**Comment by Rajkumar235216** [comment]
Hi @sayali-MSFT 
Thanks for the update.
Has this issue been taken by MS Development team to fix?

**Comment by sayali-MSFT** [comment]
@Rajkumar235216 - Could you please try with C# Sample once?
https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/54.teams-task-module

**Comment by Rajkumar235216** [comment]
Hi @sayali-MSFT 
This issue happens with python repo: https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/python/54.teams-task-module
Please try to replicate in same.
I am not familiar to C# or dotnet, so unable to try above sample at this moment.

**Comment by sayali-MSFT** [comment]
@Rajkumar235216 -We are setup it from our end and let you know.

**Comment by sayali-MSFT** [comment]
@Rajkumar235216 - We are able to repro that issue , We have raised bug for the same and concerned team is looking into it. We will inform you once we get any update.
Thanks!

**Comment by Rajkumar235216** [comment]
Hi @sayali-MSFT , Thanks for this wonderful update.
I am hoping that this issue will be fixed soon.
Is it possible for you to share an estimated ETA on this fix?

**Comment by sayali-MSFT** [comment]
@Rajkumar235216 - Currently we don’t have ETA or Update on this thread.

**Comment by Rajkumar235216** [comment]
Hi @sayali-MSFT 
Is there any update on this issue?

**Comment by sayali-MSFT** [comment]
@Rajkumar235216 - Sorry for the delay. Engineering team working on this issue. Currently we don’t have ETA or Update on this thread. 
We will update this thread once the bug is fixed.

**Comment by Prasad-MSFT** [comment]
@Rajkumar235216 We tested this in iOS 17.4 and this seems to be working now.
Microsoft Teams version:
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/62237649/207eb7a7-be11-4471-a80b-aef3913a9fe8)
