### ISSUE TITLE
Rejecting incoming calls when on already on call to mobile causes ongoing call to disconnect

### ISSUE THREAD

**Issue by simonhoward2** [MicrosoftDocs/msteams-docs#644]
Issue occurs when on the phone from teams to an external mobile number. Another call will come in and ring on the main speaker. If you reject the incoming call (and in this case it is transferred to operator) the call with the mobile that you are on is disconnected.

The second incoming call can be either someone ringing directly or through a call queue. This issue is intensified as currently you cannot mute or change the volume of incoming calls when already on a call. This means we have to let the call ring out to not disconnect the existing call, but the incoming ring tone is very loud and distracting.

**Comment by Wajeed-msft** [comment]
Could you please share Microsoft Teams app version details screenshot?

**Comment by simonhoward2** [comment]
![image](https://user-images.githubusercontent.com/50643592/60059095-73e22100-972e-11e9-8608-0b06bcc304a3.png)

**Comment by Wajeed-msft** [comment]
Could you please share your mobile app version details?

**Comment by simonhoward2** [comment]
Sorry, we are not using mobile app. This was when using Calls to a mobile number
