### ISSUE TITLE
'See app scenarios' link is broken

### ISSUE THREAD

**Issue by antefix-consulting** [MicrosoftDocs/msteams-docs#6449]
In 'The Teams solution' page, the 'See app scenarios' link leads to 'We are sorry, the page you requested cannot be found'.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3657d472-adc0-6d22-ab88-2af5b2d82869
* Version Independent ID: 3657d472-adc0-6d22-ab88-2af5b2d82869
* Content: [Teams solution for building apps - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/overview-solution)
* Content Source: [msteams-platform/overview-solution.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/overview-solution.md)
* Service: **msteams**
* GitHub Login: @heath-hamilton
* Microsoft Alias: **lajanuar**

**Comment by Prasad-MSFT** [comment]
Thanks for reporting @antefix-consulting .
Hi @surbhigupta12 , When we click on this marked 'See app scenarios' link, it leads to 'We are sorry, the page you requested cannot be found'.
![image](https://user-images.githubusercontent.com/62237649/178652686-3cfa9a08-89c5-431d-9c26-bef058553ada.png)
Please help here to update the doc.
