### ISSUE TITLE
Teams does not honour Windows 10 Quiet Hours

### ISSUE THREAD

**Issue by supermistag** [MicrosoftDocs/msteams-docs#645]
Microsoft Teams Version 1.2.00.8864 (64-bit). It was last updated on 4/11/19.

Reproduction steps
1. Set Windows Quiet Hours to on
2. Teams indicates Quiet hours is on by the text in the app - "Windows Quiet Hours is enabled, so you won't get notifications for calls and messages in Teams"
3. Someone sends you a message when teams is in the background, a popup still appears.

**Comment by Gousia-MSFT** [comment]
@supermistag Thanks for reporting it. We are looking into this!!

**Comment by Gousia-MSFT** [comment]
@supermistag  Could you please share a screenshot of the issue and the logs? You could get the logs by pressing Ctrl+Alt+Shift+1 with Teams app in Focus.

**Comment by supermistag** [comment]
@Gousia-MSFT - certainly. Do you have a support portal that I can upload the logs to? Otherwise, I will have to sanitize them.

**Comment by Gousia-MSFT** [comment]
@supermistag  Please send the logs and the screenshot to microsoftteamsdev@microsoft.com

**Comment by Wajeed-msft** [comment]
Please re-open this with the logs.

**Comment by supermistag** [comment]
Logs were sent to the address provided above on 6/6

**Comment by supermistag** [comment]
> Please re-open this with the logs.

@Wajeed-msft  Logs were sent to the address provided above on 6/6

**Comment by Wajeed-msft** [comment]
Thanks I just checked the status for this issue. Currently, This is by Design that "Purple toasts don't honour quite hours settings" Hence we are closing this.

**Comment by supermistag** [comment]
Wow. By design? Every other app honors this setting except for teams. Outlook too.

So the purple toasts are not considered notifications? What exactly are they then?

Then the solution would be to change the displayed text "Windows Quiet Hours is enabled, so you won't get notifications for calls and messages in Teams. You will get toast popups, which by design is not a notification"

**Comment by clearab** [comment]
You can vote/follow the feature request on User Voice here: https://microsoftteams.uservoice.com/forums/555103-public/suggestions/31395529-teams-notification-follow-windows-10-quiet-hours

**Comment by supermistag** [comment]
Thanks for pointing out that page. Off I go to vote for a feature request to fix a bug. Which no other app does.

I'll add that point to the slew of other MS Teams complaints from within our organization.
