### ISSUE TITLE
Deeplink to sidepanel not working

### ISSUE THREAD

**Issue by HunaidHanfee-MSFT** [MicrosoftDocs/msteams-docs#6459]
We have tried deep link to open meeting side panel from meeting stage view or content bubble but it's not redirecting to side panel instead opening the normal pre-meeting and post-meeting tab only.

 
![image](https://user-images.githubusercontent.com/64194049/178947640-e8c9986c-eec7-484e-b655-2039b42d6112.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45541337-ecd7-5cf6-cbe4-3f0d2f39aa79
* Version Independent ID: 6b4203f0-2844-06c9-eaa3-9cc03e6f76c0
* Content: [Create deep links - Teams](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links?branch=pr-en-us-5715#deep-linking-to-your-tab)
* Content Source: [msteams-platform/concepts/build-and-test/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/build-and-test/deep-links.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Prasad-MSFT** [comment]
@HunaidHanfee-MSFT - thanks for reporting. We have raised a bug for the same and engineering team is looking into it. We will inform you once we get any further update. Thanks!

**Comment by marekcis** [comment]
Please any update on this issue? It is still there.
