### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by viatoswelz** [MicrosoftDocs/msteams-docs#646]
Affaird to say, following this article does not yield the desired result.  Going into Teams -&gt; Profile Button -&gt; About has no "developer preview" Button. 

You have Microsoft Teams Version 1.2.00.8864 (64-bit). It was last updated on 5/7/19.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 008da4e2-979e-c396-db28-4acf57deb530
* Version Independent ID: f1413f77-5eb3-e1fd-9235-d322d6e4eb6c
* Content: [Developer Preview - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/dev-preview/developer-preview-intro#feedback)
* Content Source: [msteams-platform/resources/dev-preview/developer-preview-intro.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/resources/dev-preview/developer-preview-intro.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Wajeed-msft** [comment]
Could you please check with your tenant admin if [sideloading is enabled](https://docs.microsoft.com/en-us/MicrosoftTeams/enable-features-office-365?#external-apps) in your organization?

**Comment by Wajeed-msft** [comment]
Please re-open if you are still facing this issue.

**Comment by pkostelnik** [comment]
On my tenant even as on my customer there is no ponit for developer mode(s). Independent of the clientarchitecture (x86/x64) and yes, sideloading is enabled OrgWide, on Team and even for (specific)User.
So please reopen and clarify a solution.
