### ISSUE TITLE
Adaptive card submit action shows 'Unable to reach app’ error, but the action is completed

### ISSUE THREAD

**Issue by r-vijayalakshmi** [MicrosoftDocs/msteams-docs#6461]
Hi,
In Teams, on click of adaptive card submit action, the action gets completed (makes an API call) and bot responds but the adaptive card also shows 'Unable to reach app. Please try again' error. This is affecting the user experience in our production bot.
Help us to resolve this.

![image](https://user-images.githubusercontent.com/109290827/179002105-fd22feba-1166-4939-925f-98bad7012ca0.png)

Thanks.

**Comment by Nivedipa-MSFT** [comment]
@r-vijayalakshmi - We are investigating your query. We will let you know the updates.

**Comment by r-vijayalakshmi** [comment]
We are facing this issue when the bot connects to any API.

**Comment by Nivedipa-MSFT** [comment]
@r-vijayalakshmi - If the bot doesn't complete the operation within 10 to 15 seconds, depending on the channel, the Azure Bot Service will time out and report back to the client a 504:GatewayTimeout, as described in [How bots work](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-basics?view=azure-bot-service-4.0).

**Comment by r-vijayalakshmi** [comment]
Is there any way to suppress/hide this messages?

**Comment by robinmalik** [comment]
@r-vijayalakshmi It seems that Action.Submit is the older method. I had better luck with Action.Execute (as mentioned in https://github.com/MicrosoftDocs/msteams-docs/issues/6529). Maybe this will work better for you?

**Comment by samthrusha123** [comment]
I'm facing the same issue while. Is there any way to overcome this?

**Comment by robinmalik** [comment]
@samthrusha123 are you using ngrok by any chance?

**Comment by samthrusha123** [comment]
> @samthrusha123 are you using ngrok by any chance?

No. But in  both the cases this issue is occuring. In deployed application and while using ngrok as well.

**Comment by robinmalik** [comment]
This is not stale. We're waiting on MS advice, I believe?

**Comment by ChetanSharma-msft** [comment]
@robinmalik, @samthrusha123
If the bot doesn't complete the operation within 10 to 15 seconds, depending on the channel, the Azure Bot Service will time out and report back to the client a 504:GatewayTimeout, as described in [How bots work](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-basics?view=azure-bot-service-4.0).

For proper handling of managing long running operation please refer below doc.
https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-long-operations-guidance?view=azure-bot-service-4.0

Please let us know if you need any further help here?

**Comment by robinmalik** [comment]
@ChetanSharma-msft I'll reopen my original case #6529 as the bot responds with 1 or 2 seconds.

**Comment by ChetanSharma-msft** [comment]
@robinmalik, @samthrusha123, @r-vijayalakshmi - Shall we close this issue and track it here: https://github.com/MicrosoftDocs/msteams-docs/issues/6529

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.
Please track it here: https://github.com/MicrosoftDocs/msteams-docs/issues/6529
