### ISSUE TITLE
Steps not working for Teams Mobile

### ISSUE THREAD

**Issue by sugupta427** [MicrosoftDocs/msteams-docs#6467]
[Enter feedback here]
I followed the steps mentioned in the page, but i am not able to see the webview opened inside Teams mobile on the inspect-devices browser page. Although the other pages opened in my mobile browser are visible here for debugging.
![MicrosoftTeams-image](https://user-images.githubusercontent.com/64141775/179207586-2b761aa1-f154-469b-9f07-89ce8f8b0ba8.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3df1efbb-c6b2-a495-303d-7abf19c57f72
* Version Independent ID: a5b5782f-7031-a989-5e42-dd3010e18893
* Content: [DevTools for Microsoft Teams tabs - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/developer-tools#access-devtools-from-an-android-device)
* Content Source: [msteams-platform/tabs/how-to/developer-tools.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/tabs/how-to/developer-tools.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by sugupta427** [comment]
Yes it's the same.

Regards,
Surya Gupta

**Comment by sayali-MSFT** [comment]
@sugupta427 -We are checking it internally and let you know if we get any updates.

**Comment by devszr** [comment]
I have the same problem on both an Android SDK Emulator and a physical device connected to my development workstation.

**Comment by sayali-MSFT** [comment]
@devszr -We are able to repro that issue , We have raised bug for the same and concerned team is looking into it. We will inform you once we get any update. thanks!

**Comment by sayali-MSFT** [comment]
@sugupta427,@devszr -Issue is Resolved with Latest Canary 2nd September Build (Version 1416/1.0.84.2022381101 (2022381111)
Could you please check it once and confirm?
