### ISSUE TITLE
Hello World tutorial page for Teams has no working feedback links

### ISSUE THREAD

**Issue by AE-MS** [MicrosoftDocs/msteams-docs#6469]
I know that these GitHub issues usually have a bunch of boilerplate properties in them that get populated when you report feedback on a docs page, but in this case the issue I'm reporting is that a docs page has no way to provide feedback.

This page:
https://docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-javascript?tabs=vscode%2Cvsc%2Cviscode&tutorial-step=1

...does not have the usual "Feedback" section at the bottom and the tiny little feedback icon in the upper right corner doesn't do anything (although it does appear to be _trying_ to do something because the URL changes when I click on it, but it seems to be trying to navigate to a non-existent anchor).

This page should have a way to report feedback.

**Comment by Nivedipa-MSFT** [comment]
@AE-MS - As this a complete tutorial, at the end of this tutorial there is Feedback section, you can raise feedback from there.

@surbhigupta12 - For this tutorial on every page( except last page ) the Feedback icon on top right corner is not navigating to Feedback section of tutorial.
Could you please help here to update the link for navigation?

**Comment by Nivedipa-MSFT** [comment]
@AE-MS - Feedback icon on top right corner of every page of tutorial has removed and for whole tutorial at the end there is one feedback section available to raise feedback.

**Comment by Nivedipa-MSFT** [comment]
We are closing this issue for now. Please feel free to reopen if required. Thanks.
