### ISSUE TITLE
Prerequisites list on step 1 of tutorial lists required installations out of order

### ISSUE THREAD

**Issue by AE-MS** [MicrosoftDocs/msteams-docs#6478]
On step 1 of this tutorial where the prerequisites are listed, it lists "Teams Toolkit" as the first required installation. However, it doesn't list Visual Studio Code until the last of the required installations. Since Teams Toolkit is an extension to Visual Studio Code, it would not be possible to install the prerequisites in the order listed.

Please consider reordering the required prerequisites based on the order in which they need to be installed (i.e. putting Visual Studio Code least before Teams Toolkit).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e473e1f3-69f5-bcfa-bcab-54b098b59c80
* Version Independent ID: e473e1f3-69f5-bcfa-bcab-54b098b59c80
* Content: [Hello World with JavaScript - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-javascript?tabs=vscode%2Cvsc%2Cviscode&tutorial-step=1)
* Content Source: [msteams-platform/sbs-gs-javascript.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/sbs-gs-javascript.yml)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Nivedipa-MSFT** [comment]
@surbhigupta12 - Could you please reorder the required prerequisites like below.
Visual Studio Code
Node.js
Teams Toolkit
Microsoft Teams
Microsoft Edge (recommended) or Google Chrome

Content link: https://docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-javascript?tabs=vscode%2Cvsc%2Cviscode&tutorial-step=1
