### ISSUE TITLE
Inconsistent behaviour with channel message deeplink

### ISSUE THREAD

**Issue by YJasonY** [MicrosoftDocs/msteams-docs#6489]
We generate deep links using the following template:

`https://teams.microsoft.com/l/message/<channelId>/<parentMessageId>?tenantId=<tenantId>&groupId=<groupId>&parentMessageId=<parentMessageId>&teamName=<teamName>&channelName=<channelName>&createdTime=<createdTime>`

as detailed here: https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links?tabs=teamsjs-v2#generate-deep-links-to-channel-conversation

However, we are seeing inconsistent behaviour between different tenants, as well as an error message:

Scenario 1 - Link navigates directly to channel conversation, post is highlighted. This is the expected behaviour.

![image](https://user-images.githubusercontent.com/16281323/179872729-5d9b24bf-99cb-47c1-b544-96eb1692d49a.png)

Scenario 2 - Link navigates to a thread summary view, alongside error message. The thread summary view seems new and it is not clear what causes the link to go to this view instead of channel view.
The error message also doesn't make any sense because both the Team and the channel definitely exist.

![image](https://user-images.githubusercontent.com/16281323/179872836-8949adde-15af-45c2-8a4e-5280f07a879a.png)

Both scenarios are via the Web version of Teams.

Any ideas what could explain this inconsistency/error?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45541337-ecd7-5cf6-cbe4-3f0d2f39aa79
* Version Independent ID: 6b4203f0-2844-06c9-eaa3-9cc03e6f76c0
* Content: [Create deep links - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links?tabs=teamsjs-v2)
* Content Source: [msteams-platform/concepts/build-and-test/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/build-and-test/deep-links.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Meghana-MSFT** [comment]
Could you please share recording of the deeplink navigation to summary view?

**Comment by Meghana-MSFT** [comment]
We are also able to repro this issue. We raised a bug for the same. We will keep you posted on the updates. Thanks.

**Comment by Keshav-MSFT** [comment]
Hi @YJasonY  Could you please confirm if you are facing this issue intermittently or is it continuous? Also please confirm if your issue is same as this one?

**Comment by Meghana-MSFT** [comment]
@YJasonY - We tested this issue today in browser and it is working fine. Could you please let us know if you are still able to reproduce this issue?

**Comment by YJasonY** [comment]
Hi @Meghana-MSFT - 

With testing this, we're noticing the following:

1. Upon first interaction, the link navigates to the conversation thread in the channel (Scenario 1)
2. Subsequent interactions, the link navigates to the conversation thread summary view (Scenario 2) without the error - this appears fixed
3. Upon refreshing the page and navigating again, step 1 happens.

Can I ask what is the intended and expected interaction? Is it scenario 1 or scenario 2

**Comment by Meghana-MSFT** [comment]
@YJasonY - It should go to the particular message as shown below.

![image](https://user-images.githubusercontent.com/81138249/229155956-f64f76fc-6208-426f-88fc-9b27b9468f25.png)
