### ISSUE TITLE
Adaptive card submit action shows error message

### ISSUE THREAD

**Issue by r-vijayalakshmi** [MicrosoftDocs/msteams-docs#6497]
Hi,

In Teams, adaptive card on submit action shows 'Unable to reach app' error message but the action gets completed . Is there any way to suppress/hide this messages?

Thanks

**Comment by Nivedipa-MSFT** [comment]
@r-vijayalakshmi - We are tracking the issue in [this](https://github.com/MicrosoftDocs/msteams-docs/issues/6461) thread.
Please follow that thread for further updates.

**Comment by ChetanSharma-msft** [comment]
We are closing this as a duplicate issue of this: https://github.com/MicrosoftDocs/msteams-docs/issues/6461
