### ISSUE TITLE
Multiple messaging extensions and configuration

### ISSUE THREAD

**Issue by wictorwilen** [MicrosoftDocs/msteams-docs#650]
When using multiple messaging extensions in the manifest there is no way to configure anyone but the first of the messaging extensions registered in the manifest file.

Is the only solution to deploy multiple Teams Apps just to have multiple different configurations?

**Comment by Gousia-MSFT** [comment]
@wictorwilen Currently, only 1 message extension per app is supported. You can have multiple [commands ](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/messaging-extensions/create-extensions#complete-app-manifest-example)within the same messaging extension.

**Comment by wictorwilen** [comment]
True! The setting is on a message extension level rather than command level. Thankss
