### ISSUE TITLE
[Doc Bash] Missing Hyperlinks

### ISSUE THREAD

**Issue by smol-elak** [MicrosoftDocs/msteams-docs#6504]
1. App Permission - Device Permission link not available
![image](https://user-images.githubusercontent.com/79516068/179970352-9518c77a-7b11-4dab-bc5e-977305d4feba.png)
2. App Studio - Character ">" appearence.
![image](https://user-images.githubusercontent.com/79516068/179970692-5331a6ba-dfb8-4561-9899-7460d2e4f715.png)
3. Azure Active Directory - "It helps authenticated users access internal and external Azure resources." I think the access extends beyond Azure resources. 
4. Authentication Flow - This is redundant. Also, "flow" term is incorrectly used. It should be types of Authentications.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff9690f5-fa8b-98bb-d3b4-ad4ed1030114
* Version Independent ID: ff9690f5-fa8b-98bb-d3b4-ad4ed1030114
* Content: [Microsoft Teams developer documentation - Glossary - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary)
* Content Source: [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/get-started/glossary.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Prasad-MSFT** [comment]
Hi @surbhigupta12 - Could you please help here to update the doc accordingly?

In this [doc](https://docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary),
1.**App Permission** - Device Permission link not available
![image](https://user-images.githubusercontent.com/62237649/179974692-1f0539d0-c7b5-4a3c-aa69-bd8a286e0598.png)
2.**App Studio** - Character ">" appearence.
![image](https://user-images.githubusercontent.com/62237649/179974866-8b5875f0-ce3a-40e0-98b7-82fd90af6173.png)
3.**Authentication Flow** - Also, "flow" term is incorrectly used. It should be Authentication flow types.

**Comment by ashishguptaiitb** [comment]
@Prasad-MSFT , I don't think this is a doc-enhancement? This is clearly a miss in the docs and should be categorized as a doc-bug, unless I am missing the definition of our labels.
