### ISSUE TITLE
[Doc Bash] The screenshots still refer to App Studio. Please update or add section for Developer Portal.

### ISSUE THREAD

**Issue by smol-elak** [MicrosoftDocs/msteams-docs#6506]
Update documentation on how to add Bot commands in menu using Developer Portal.
---
#### Document Details
Developer Portal is the new tool which is being used for developing Teams App. Please update the documentation on how to add Bot commands using developer portal.
![image](https://user-images.githubusercontent.com/79516068/179999466-3d017e29-d407-41d2-a61b-76e1eaae2b2b.png)

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a982542-ae03-2ada-cf71-4d586272e0c3
* Version Independent ID: 9e1fd82b-79e4-1b8d-5367-a8de3d04b3aa
* Content: [Create a command menu for your bot - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/create-a-bot-commands-menu?tabs=desktop%2Cdotnet)
* Content Source: [msteams-platform/bots/how-to/create-a-bot-commands-menu.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/bots/how-to/create-a-bot-commands-menu.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **anclear**

**Comment by sayali-MSFT** [comment]
@surbhigupta12 -Could you please help us to update document?

**Comment by LapinskasL** [comment]
Is there even a button to add bot commands in Developer Portal? I can't find it.

**Comment by sayali-MSFT** [comment]
@LapinskasL - Yes there is button available for Add Command.
Goto App->Import/Add App->App Features->Bot->Save->Add a command.

https://user-images.githubusercontent.com/93527375/183595405-3641fc4c-00bc-421e-bade-fac0145e00da.mp4

**Comment by v-sdhakshina** [comment]
This issue is addressed in Developer Portal revamp task.

PR: https://github.com/MicrosoftDocs/msteams-docs/pull/6501

**Comment by v-habibaumme** [comment]
This issue is already in the Developer Portal revamp tasks and here is the PR: https://github.com/MicrosoftDocs/msteams-docs/pull/6501. Hence closing this PR
