### ISSUE TITLE
[Doc Bash] Suggestion - Addition of few more terms consistently found across other docs.

### ISSUE THREAD

**Issue by smol-elak** [MicrosoftDocs/msteams-docs#6507]
Addition of new terms
---
#### Document Details
![image](https://user-images.githubusercontent.com/79516068/180010987-ee035282-7773-4237-9669-bef82043da03.png)

Can we add terms GCC, GCC High and DoD in the glossary.

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff9690f5-fa8b-98bb-d3b4-ad4ed1030114
* Version Independent ID: ff9690f5-fa8b-98bb-d3b4-ad4ed1030114
* Content: [Microsoft Teams developer documentation - Glossary - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary)
* Content Source: [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/get-started/glossary.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by ChetanSharma-msft** [comment]
Hello @surbhigupta12 - Please help us here to update the contents.
