### ISSUE TITLE
launcher.js is throwing 404

### ISSUE THREAD

**Issue by JagsInd** [MicrosoftDocs/msteams-docs#651]
https://teams.microsoft.com/share/launcher.js is not loading. It says "The resource you are looking for has been removed, had its name changed, or is temporarily unavailable."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a59a558-f2f0-3390-9c81-bb41d47a5fbe
* Version Independent ID: a4335fae-0b14-c338-0f15-23ee043be278
* Content: [Share to Teams embedded button - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/share-to-teams#feedback)
* Content Source: [msteams-platform/share-to-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/share-to-teams.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by clearab** [comment]
Please ensure that you have changed your Teams web client to Developer Preview, and authenticated the browser sessions you're trying to launch the Share-to-Teams functionality from. See the Note at the beginning of this article for more information.
