### ISSUE TITLE
[Doc Bash] Need documentation on how to add an Azure Bot on Teams

### ISSUE THREAD

**Issue by smol-elak** [MicrosoftDocs/msteams-docs#6510]
[Enter feedback here]

---
#### Document Details
https://docs.microsoft.com/en-us/azure/bot-service/channel-connect-teams?view=azure-bot-service-4.0 currently this is the only documentation available from Azure. But if I want to import an Azure Bot into team via Developer portal, then that is not documented anywhere.

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dac10c25-1625-4f0d-b113-a1fdd7a7a900
* Version Independent ID: dac10c25-1625-4f0d-b113-a1fdd7a7a900
* Content: [Get started - Overview - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/get-started/get-started-overview)
* Content Source: [msteams-platform/get-started/get-started-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/get-started/get-started-overview.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Nivedipa-MSFT** [comment]
@smol-elak - We have steps mentioned in below tutorial for how to configure bot using Developer Portal.
https://docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-csharp?tutorial-step=3#configure-bot

**Comment by smol-elak** [comment]
The documentation you shared does not tell me how to add an existing Bot which I might have created from other portals say Azure.

**Comment by Nivedipa-MSFT** [comment]
@surbhigupta12 - Could you please help here to add the below content.

To add existing azure bot to app

1. Open the App features pane, and select the Bot card.

![image](https://user-images.githubusercontent.com/92150070/180205749-2bdd4dee-1c40-470d-a580-a6103cf97fef.png)


The Bot pane appears.

2. Enter bot ID of your existing azure bot app in Enter a bot ID section

![image](https://user-images.githubusercontent.com/92150070/180205853-84830c4a-8a0e-4edf-a27f-f3a7d63e4832.png)

3. The existing bot is added to your app with its own app ID.

![image](https://user-images.githubusercontent.com/92150070/180206407-fd2597b6-8960-4ee5-afb6-cea13016f247.png)

**Comment by v-habibaumme** [comment]
Closing this PR as the details are addressed in this PR: https://github.com/MicrosoftDocs/msteams-docs/pull/6602
