### ISSUE TITLE
Add links to relevant docs for each part of app lifecycle

### ISSUE THREAD

**Issue by ashishguptaiitb** [MicrosoftDocs/msteams-docs#6518]
For the various stages of app development, add links to the relevant docs for devs.
Eg. to be able to use new features, point the reader to the What is new article; in the onboarding experience mention how devs can benefit from SBS guides and link to those; and so on.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27c35889-c7c9-4b7a-3462-267aea5371d9
* Version Independent ID: 27c35889-c7c9-4b7a-3462-267aea5371d9
* Content: [Questions to help plan Teams app development - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/design/planning-checklist)
* Content Source: [msteams-platform/concepts/design/planning-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/design/planning-checklist.md)
* Service: **msteams**
* GitHub Login: @heath-hamilton
* Microsoft Alias: **surbhigupta**

**Comment by Prasad-MSFT** [comment]
Hi @surbhigupta12 - Could you please help here to update the doc accordingly?
It would be better if we add few more references in [this](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/design/planning-checklist#plan-beyond-app-building) doc.

 e. g. For new features refer: [What's New](https://docs.microsoft.com/en-us/microsoftteams/platform/whats-new)

**Comment by v-habibaumme** [comment]
This is merged and can be closed the PR
