### ISSUE TITLE
Mention canUpdateConfigurationUrl manifest property

### ISSUE THREAD

**Issue by benpolinsky** [MicrosoftDocs/msteams-docs#652]
There's no mention of the `canUpdateConfigurationUrl` property that's needed to enable updating settings. I had to find it here: https://docs.microsoft.com/en-us/microsoftteams/platform/get-started/obsolete-get-started-dotnet

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88ff3777-49c4-8cdc-089e-8612a8774ffb
* Version Independent ID: 0d927000-0b55-2129-cbbb-6630c1ec481e
* Content: [Search with messaging extensions - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/messaging-extensions/search-extensions)
* Content Source: [msteams-platform/concepts/messaging-extensions/search-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/messaging-extensions/search-extensions.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by clearab** [comment]
Hi - I think you mean canUpdateConfiguration, and if so it is discussed in [this section](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/messaging-extensions/search-extensions#add-event-handlers), and is also listed in the table in [this section](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/messaging-extensions/search-extensions#declare-your-messaging-extension).
