### ISSUE TITLE
Emojis only displayed as '??' in plain text messages and adaptive cards

### ISSUE THREAD

**Issue by robinmalik** [MicrosoftDocs/msteams-docs#6528]
Hi,

I'm trying to use emojis in plain text messages and adaptive cards within Microsoft Teams.

Adaptive Card:

<img width="352" alt="image" src="https://user-images.githubusercontent.com/8790561/180665390-00281240-5bd6-4928-802d-355d91ef2a62.png">

Plain text with emoji rendered correctly in VSCode:

<img width="303" alt="image" src="https://user-images.githubusercontent.com/8790561/180665424-88d080b7-d2b9-4ea6-9197-74ff4f372ee9.png">

Output in Teams:

<img width="200" alt="image" src="https://user-images.githubusercontent.com/8790561/180665406-d38fd723-f17a-4f5a-bf23-ebc8b2c6042a.png">

I'm using PowerShell, and currently can only get this to work using the hex code value for the emoji, like so:

<img width="316" alt="image" src="https://user-images.githubusercontent.com/8790561/180665590-cec3d216-77f6-4b89-bc45-2d68118c58da.png">

Any thoughts on why this might be happening?

Thanks.

**Comment by sayali-MSFT** [comment]
@robinmalik -Could you please share the adaptive card json, So that we can try it from our end and let you know. 
Thanks!

**Comment by robinmalik** [comment]
Sure.

```
{
    "type": "message",
    "from": {
        "id": "REMOVED",
        "name": "ITSBot"
    },
    "conversation": {
        "id": "REMOVED"
    },
    "attachments": [
        {
            "contentType": "application/vnd.microsoft.card.adaptive",
            "content": {
                "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
                "type": "AdaptiveCard",
                "version": "1.4",
                "body": [
                    {
                        "type": "Container",
                        "items": [
                            {
                                "type": "TextBlock",
                                "text": "Publish Adaptive Card with emojis 😁 💯",
                                "weight": "bolder",
                                "size": "medium"
                            }
                        ]
                    }
                ]
            }
        }
    ]
}
```

<img width="603" alt="image" src="https://user-images.githubusercontent.com/8790561/180776545-2d255f9a-60de-448e-92cd-d36e5f8ef4cf.png">

but:

<img width="424" alt="image" src="https://user-images.githubusercontent.com/8790561/180776617-f37899af-9593-4ff2-99f6-198f39ff2360.png">

**Comment by robinmalik** [comment]
I found the solution: `charset=utf-8` needs to be set in the headers (either manually, or via `-ContentType "charset=UTF-8"`)
