### ISSUE TITLE
Manifest parsing for app fails

### ISSUE THREAD

**Issue by RaiAmanRai** [MicrosoftDocs/msteams-docs#6531]
On uploading a custom built, I get hit with "manifest parsing failed" while another manifest with just a different app name passes manifest parsing.

Even the failed manifest passes after a couple of 100 tries.

Not juat this, when I try to create my own app through teams, it fails the auto-generated manifest!!

I don't understrand, if I am doing something worng or is there a bug in teams

**Comment by Prasad-MSFT** [comment]
@RaiAmanRai - Could you please share your manifest so that we can try once from our end?

**Comment by RaiAmanRai** [comment]
Hi @Prasad-MSFT , have a look at the file. The bot id have intentionally been omitted.

[manifest.zip](https://github.com/MicrosoftDocs/msteams-docs/files/9187037/manifest.zip)

**Comment by Prasad-MSFT** [comment]
We tried to repro the issue by uploading the manifest shared only changing app-id/bot-id and it got added successfully. Please try to update your MS Teams verson and check if it helps.

![image](https://user-images.githubusercontent.com/62237649/180959191-7078dbc8-ef4b-4e08-9a56-4b0a8ced7b87.png)

` Microsoft Teams Version 1.5.00.19563`

**Comment by RaiAmanRai** [comment]
Thanks @Prasad-MSFT , I will check it out again.

Again thanks for the qiuck response.

**Comment by RaiAmanRai** [comment]
Hi, this works fine for me for now, so going ahead and closing this. 

Will comeback if the problem arises again. Thanks
