### ISSUE TITLE
Need Doc/Tutorial For Customizing the "Feedback Banner" for Adaptive Cards

### ISSUE THREAD

**Issue by johnmiroki** [MicrosoftDocs/msteams-docs#6535]
Please first refer to the screenshot:
<img width="1049" alt="image" src="https://user-images.githubusercontent.com/1551376/181066526-65390dcb-8145-4091-aaf6-62f04ac17f71.png">
On the bottom, you can see a banner/strip showing feedback information / errors for the button click result. However:
1. No document has given it a proper name, making it very difficult to google about it
2. No document has shown the developers how to make a bot response / json so that MS Teams will show the banner/strip with proper icon, text and color.

Would you please consider adding the doc? Appreciate it!

**Comment by Nivedipa-MSFT** [comment]
@johnmiroki - Could you please refer below doc which has Form completion feedback section.
https://domoreexp.visualstudio.com/MSTeams/_queries/edit/2542361/?triage=true

Please let us know if you still want to add new doc.

**Comment by johnmiroki** [comment]
@Nivedipa-MSFT Sorry but it seems I don't have access to the first link.

**Comment by Nivedipa-MSFT** [comment]
@johnmiroki - Could you please check now.

**Comment by johnmiroki** [comment]
@Nivedipa-MSFT Yes, it works now. And it's the right doc. Thank you very much! A follow-up question: is there anyway to customize the message? Like when user clicks submit, we can send the customized text/icon/color to show as a completion feedback?

**Comment by Nivedipa-MSFT** [comment]
@johnmiroki - We cannot customized text/icon/color to show as a completion feedback.
We can only hide the success message. To hide the message, set the attribute hide to true in the msTeams feedback property.

**Comment by johnmiroki** [comment]
@Nivedipa-MSFT Thanks for the confirmation! BTW, the msteams property is very mysterious. Do you happen to have full doc of all of its properties, such as type (task/fetch), feedback and etc?

**Comment by Nivedipa-MSFT** [comment]
johnmiroki - Use of msteams in task/fetch and in feedback is different. In task/fetch the msteams property in in data section and in feedback its in action section.

For task/fetch the payload is
```
{
  "type": "Action.Submit",
  "id": "btnBuy",
  "title": "Buy",
  "data": {
    <...>,
    "msteams": {
      "type": "task/fetch"
    }
  }
}
```

For Form completion feedback the payload is

```
"content": {
       "type": "AdaptiveCard",
       "title": "Card with hidden footer messages",
       "version": "1.0",
       "actions": [
       {
           "type": "Action.Submit",
           "title": "Submit",
           "msTeams": {
               "feedback": {
               "hide": true
               }
           }
       }
       ]
   }

```
Please refer below document for reference:
1. https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/task-modules/task-modules-bots?tabs=nodejs#bot-framework-card-actions-vs-adaptive-card-actionsubmit-actions
2. https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-messages?tabs=dotnet#form-completion-feedback

**Comment by johnmiroki** [comment]
@Nivedipa-MSFT Ah, thanks for pointing out the differences. TBH, msteams, msTeams both look so casually designed and poorly documented. (Is there any other sub property under msteams or msTeams? what would they do?).

**Comment by Nivedipa-MSFT** [comment]
@johnmiroki - msteams is used for mention support in adaptive cards also.
```
 "msteams": {
      "entities": [
        {
          "type": "mention",
          "text": "<at>John Doe</at>",
          "mentioned": {
            "id": "29:123124124124",
            "name": "John Doe"
          }
        }
      ]
```
You can refer below document: 
https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?tabs=adaptive-md%2Cconnector-html#mention-support-within-adaptive-cards

**Comment by johnmiroki** [comment]
@Nivedipa-MSFT Thank you for answering all my questions. Very helpful!
