### ISSUE TITLE
[Doc-Bug] justInTimeInstall not working with side loaded app

### ISSUE THREAD

**Issue by SubbaReddi** [MicrosoftDocs/msteams-docs#6537]
We have a message-extension-only app that initiates a sequence of Task Modules during a Teams Meeting. The app manifest is side-loaded for user. During the meeting, the host of the meeting (also the Tenant Administrator) chooses the message extension from the chat entry field and executes the command. The first step in the sequence is to add our bot to the meeting chat so that our app can be a full participant in the meeting. Our server gets the event to invoke our message extension and returns a response that has an action for 'justInTimeInstall'. When the host clicks on the button to execute the justInTimeInstall, we get an error message that fills the body of the task module that says : Unable to reach app.

When you upload app to app catalogue, I see justInTimeInstall is working fine. But it is not working with side loaded version. I see it as known behavior. As app definition does not exists in app catalogue, user cannot install app to other meeting using justInTimeInstall. So, adding note to documentation will help.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5319949f-7a29-1d17-0090-5f423ae8174e
* Version Independent ID: 2d45f040-a391-ac0b-17e8-fa99e880fcf1
* Content: [Initiate actions with message extensions - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/messaging-extension-v3/create-extensions?tabs=typescript)
* Content Source: [msteams-platform/resources/messaging-extension-v3/create-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/resources/messaging-extension-v3/create-extensions.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Prasad-MSFT** [comment]
We are checking the issue. We will redirect to doc team if required.

**Comment by Prasad-MSFT** [comment]
Hi @surbhigupta12, the PR has been merged, but we could not see the changes in the documentation page. Is there any reason it has been removed/ not added?
