### ISSUE TITLE
What's the difference between a message extension auth or config response?

### ISSUE THREAD

**Issue by wictorwilen** [MicrosoftDocs/msteams-docs#654]
When using the `auth` or `config` response for a messaging result. What is the difference, part from a small title difference (sign in vs configure)?
![image](https://user-images.githubusercontent.com/5854279/57914042-2ef4e000-788e-11e9-927c-7c661c7bb706.png)

They are managed in the same way and the response from the dialog is treated in the same way. Wouldn't it be better to just have one of them, remove your standard text and use the `suggestedActions[0].title`?

**Comment by maoyu-dev** [comment]
You are correct that there isn't a difference technically. We want to control the UX of auth and config this way.

**Comment by wictorwilen** [comment]
Ok. Got it!
