### ISSUE TITLE
Adaptive card submit action shows 'Unable to reach app. Please try again’ error, even the action is completed

### ISSUE THREAD

**Issue by samthrusha123** [MicrosoftDocs/msteams-docs#6544]
![image](https://user-images.githubusercontent.com/44087954/181246199-2de74986-6b3d-41db-bbdd-27efdaaa16bb.png)

**Comment by Prasad-MSFT** [comment]
@samthrusha123 - Could you please provide more details on your issue? Are you using bot framework to post adaptive card in Teams? Please share the card JSON as well.

**Comment by samthrusha123** [comment]
> @samthrusha123 - Could you please provide more details on your issue? Are you using bot framework to post adaptive card in Teams? Please share the card JSON as well.


I'm making an api call when use click that button. some times it is givnig the unable to reach error. 
Yes, I'm using microsoft bot framework in c# to post adaptive card


`{
  "type": "AdaptiveCard",
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "version": "1.3",
  "body": [
    {
      "type": "TextBlock",
      "text": "Please take a moment to fill out the survey below",
      "wrap": true,
      "size": "Medium",
      "weight": "Bolder",
      "color": "Accent"
    },
    {
      "type": "ColumnSet",
      "columns": [
        {
          "type": "Column",
          "width": 50,
          "items": [
            {
              "type": "TextBlock",
              "text": "Title",
              "wrap": true,
              "weight": "Bolder"
            }
          ]
        },
        {
          "type": "Column",
          "width": 100,
          "items": [
            {
              "type": "TextBlock",
              "text": "test2",
              "wrap": true
            }
          ]
        }
      ]
    },
    {
      "type": "ColumnSet",
      "columns": [
        {
          "type": "Column",
          "width": 50,
          "items": [
            {
              "type": "TextBlock",
              "text": "Description",
              "wrap": true,
              "weight": "Bolder"
            }
          ]
        },
        {
          "type": "Column",
          "width": 100,
          "items": [
            {
              "type": "TextBlock",
              "text": "",
              "wrap": true
            }
          ]
        }
      ]
    },
    {
      "type": "ColumnSet",
      "columns": [
        {
          "type": "Column",
          "width": 50,
          "items": [
            {
              "type": "TextBlock",
              "text": "Ends On",
              "wrap": true,
              "weight": "Bolder"
            }
          ]
        },
        {
          "type": "Column",
          "width": 100,
          "items": [
            {
              "type": "TextBlock",
              "text": "Jul 28, 2022 10:26:00 am (UTC)",
              "wrap": true
            }
          ]
        }
      ]
    },
    {
      "type": "ColumnSet",
      "columns": [
        {
          "type": "Column",
          "width": 50,
          "items": [
            {
              "type": "TextBlock",
              "text": "Total Questions",
              "wrap": true,
              "weight": "Bolder"
            }
          ]
        },
        {
          "type": "Column",
          "width": 100,
          "items": [
            {
              "type": "TextBlock",
              "text": 1,
              "wrap": true
            }
          ]
        }
      ]
    }
  ],
  "actions": [
    {
      "type": "Action.ShowCard",
      "card": {
        "type": "AdaptiveCard",
        "body": [
          {
            "type": "TextBlock",
            "text": "I consent to the usage and processing of my data.",
            "wrap": true,
            "fontType": "Default",
            "size": "Medium",
            "weight": "Bolder",
            "color": "Accent",
            "isSubtle": true
          }
        ],
        "actions": [
          {
            "type": "Action.Submit",
            "title": "Continue",
            "associatedInputs": "auto",
            "data": {
              "msteams": {
                "type": "messageBack",
                "displayText": "Starttest2",
                "associatedInputs": "auto",
                "text": "survey-start",
                "value": "{}"
              }
            }
          }
        ]
      },
      "title": "Start Survey"
    }
  ]
}`


when we click on continue sometimes it is showing that error message.

**Comment by Prasad-MSFT** [comment]
There is a 10 or 15 second timeout that can occur, and if it does then I think that would cause what you're seeing.
See more at https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-long-operations-guidance?view=azure-bot-service-4.0

**Comment by johnmiroki** [comment]
Sumbit will send a "message" Activity to Bot, which Bot should immediately respond with a HTTP 202 response, and the actual message should be sent with the turnContext.sendActivity(), which is to send msg to the client by calling Bot server.

**Comment by ChetanSharma-msft** [comment]
@samthrusha123 - Please let us know if you need any further help or shall we close this issue?
