### ISSUE TITLE
How to format HTML code  as a display text on Action.Submit 

### ISSUE THREAD

**Issue by samthrusha123** [MicrosoftDocs/msteams-docs#6546]
When we click the submit button It has to display the display text property which we're mentioning in the message back. But It is not displaying the whole text when we're adding any HTML code in the display text property. Added the screenshot & Json of the adaptive card.

![image](https://user-images.githubusercontent.com/44087954/181415909-eaf0e15e-31ee-4585-8b14-a69ee6010408.png)

`{
    "type": "AdaptiveCard",
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.3",
    "actions": [
        {
            "type": "Action.Submit",
            "title": "Action.Submit",
             "data": {
        "msteams": {
          "type": "messageBack",
          "displayText": "Hello <img src=\">\" onerror=\"alert(\'title\')\">-Clone",
          "text": "start-survey",
          "value": "{\"surveyBroadcastId\": \"${SurveyBroadcastId}\", \"languageId\": \"${languageId}\"}"
        }
      }
        }
    ]
}`

**Comment by Nivedipa-MSFT** [comment]
@samthrusha123 - We are investigating your query. We will get back to you once we have any update.

**Comment by Nivedipa-MSFT** [comment]
@samthrusha123 - HTML is not supported in Adaptive Cards.

![image](https://user-images.githubusercontent.com/92150070/181461094-8f764879-bd2c-4a75-b0f9-67380e2d9394.png)

 Its already mentioned in below document:
https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?tabs=adaptive-md%2Cconnector-html#format-cards-with-markdown

**Comment by samthrusha123** [comment]
> 

Is there any other way that we can use HTML text in the display text property?

**Comment by samthrusha123** [comment]
> @samthrusha123 - HTML is not supported in Adaptive Cards.
> 
> ![image](https://user-images.githubusercontent.com/92150070/181461094-8f764879-bd2c-4a75-b0f9-67380e2d9394.png)
> 
> Its already mentioned in below document: https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?tabs=adaptive-md%2Cconnector-html#format-cards-with-markdown




Can we display something like this when we click an action button? 

![image](https://user-images.githubusercontent.com/44087954/181489030-36dc6cca-0b85-4d84-ab77-cbbd0f845533.png)

**Comment by Nivedipa-MSFT** [comment]
@samthrusha123 - This is not supported. We cannot display content using HTML code.

**Comment by ChetanSharma-msft** [comment]
@samthrusha123 - Please let us know if you need any further help or shall we close this issue?
