### ISSUE TITLE
Dialog size of the message extension auth/config is to small

### ISSUE THREAD

**Issue by wictorwilen** [MicrosoftDocs/msteams-docs#655]
When using either `auth` or `config` responses in messaging extensions the initial dialog is to small (and to be honest, it's also redundant - why do I need this extra click) if you have a smaller window - but there is plenty of space to use...

![image](https://user-images.githubusercontent.com/5854279/57914427-e7228880-788e-11e9-8519-54c93657d349.png)

**Comment by Wajeed-msft** [comment]
@wictorwilen - Are you getting this when you click on set up link?
![image](https://user-images.githubusercontent.com/31851992/58112062-4e826480-7c10-11e9-96b9-f96a4ef26060.png)

**Comment by wictorwilen** [comment]
@Wajeed-msft no this comes from a messaging extension response, 

``` json
{
    type: "config",
    suggestedActions: {
        actions: [
            {
                type: "openUrl",
                value: "https://yoteamsdev.eu.ngrok.io",
                title: "Configure this app"
            }
        ]
    }
}

```

**Comment by maoyu-dev** [comment]
The auth/config window size being too small is a bug - we will work on a fix.

**Comment by Gousia-MSFT** [comment]
@wictorwilen This has been fixed. Could you please try it now?
