### ISSUE TITLE
Readonly Mode for People Picker in Adaptive Card

### ISSUE THREAD

**Issue by johnmiroki** [MicrosoftDocs/msteams-docs#6556]
We have a use case where we need to display people's avatar and name on Adaptive Card by providing their AAD Object IDs. It's basically the same as pre-populated People Picker, only read-only. Is this viable? Appreciate it!

<img width="498" alt="image" src="https://user-images.githubusercontent.com/1551376/181484742-7cf63f78-01d4-4cba-964c-4124d1f630d6.png">

**Comment by Prasad-MSFT** [comment]
@johnmiroki - Will it be ok if we use Power automate to send adaptive card having user image in MS Teams?

**Comment by johnmiroki** [comment]
@Prasad-MSFT Thanks for answering my questions. Our backend is an Azure Bot (using Java SDK). The requested functionality should be easy to implement, I mean, the infrastructuer is there: People Picker can already show people's avatar and name, the only extra thing is to make the People Picker read-only (and of course, prepopulated with provided user ids).

**Comment by Prasad-MSFT** [comment]
@johnmiroki - `setSelected` property must be passed which is Microsoft Azure Active Directory (Azure AD) IDs of the people to be preselected. This parameter preselects people while launching the People Picker input control. 
or get user profile details using graph API and you can use custom code to show the name & profile picture in UI.

**Comment by johnmiroki** [comment]
@Prasad-MSFT Thank you. Unfortunately, we use pure Adaptive Card and there's no js involved.

**Comment by Prasad-MSFT** [comment]
@johnmiroki - Then only way would be getting user profile details using graph API and using custom code to show the name & profile picture in UI.

**Comment by johnmiroki** [comment]
@Prasad-MSFT Thank you. It looks what you said is the only way for now. TBH, it's such a waste. A small tweak to the exisiting People Picker would make showing avatar and name such a trivial effort.

**Comment by ChetanSharma-msft** [comment]
@johnmiroki - Please let us know if you need any further help or shall we close this issue?
