### ISSUE TITLE
Unable to reach app. Please try again issue during submit action in adaptive cards

### ISSUE THREAD

**Issue by samthrusha123** [MicrosoftDocs/msteams-docs#6559]
**Platform**  : Teams
**SDK Version**: Microsoft Azure BOT Framework v4

**Problem Description** : 
While making a submit action in the adaptive card from MS Teams App, the card is throwing with an error "Unable to reach app. Please try again".
I understand this might be due to a delay in BOT's response. This is creating a bad user experience, as it misleads the bot users because our bot would respond after 15 secs.

Is there a way to fix this error or an option to suppress this message?

**Screenshot**

![image](https://user-images.githubusercontent.com/44087954/181523742-71cb5315-51c0-43b6-9bd2-ca3851884d39.png)

`{
   "type":"AdaptiveCard",
   "$schema":"http://adaptivecards.io/schemas/adaptive-card.json",
   "version":"1.3",
   "body":[
      {
         "type":"TextBlock",
         "text":"Please take a moment to fill out the survey below",
         "wrap":true,
         "size":"Medium",
         "weight":"Bolder",
         "color":"Accent"
      },
      {
         "type":"ColumnSet",
         "columns":[
            {
               "type":"Column",
               "width":50,
               "items":[
                  {
                     "type":"TextBlock",
                     "text":"Title",
                     "wrap":true,
                     "weight":"Bolder"
                  }
               ]
            },
            {
               "type":"Column",
               "width":100,
               "items":[
                  {
                     "type":"TextBlock",
                     "text":"Survey with branching questions ",
                     "wrap":true
                  }
               ]
            }
         ]
      },
      {
         "type":"ColumnSet",
         "columns":[
            {
               "type":"Column",
               "width":50,
               "items":[
                  {
                     "type":"TextBlock",
                     "text":"Description",
                     "wrap":true,
                     "weight":"Bolder"
                  }
               ]
            },
            {
               "type":"Column",
               "width":100,
               "items":[
                  {
                     "type":"TextBlock",
                     "text":"",
                     "wrap":true
                  }
               ]
            }
         ]
      },
      {
         "type":"ColumnSet",
         "columns":[
            {
               "type":"Column",
               "width":50,
               "items":[
                  {
                     "type":"TextBlock",
                     "text":"Ends On",
                     "wrap":true,
                     "weight":"Bolder"
                  }
               ]
            },
            {
               "type":"Column",
               "width":100,
               "items":[
                  {
                     "type":"TextBlock",
                     "text":"Jul 29, 2022 14:53:00 pm (UTC)",
                     "wrap":true
                  }
               ]
            }
         ]
      }
   ],
   "actions":[
      {
         "type":"Action.ShowCard",
         "card":{
            "type":"AdaptiveCard",
            "body":[
               {
                  "type":"TextBlock",
                  "wrap":true,
                  "text":"Please select a language to continue:",
                  "size":"Medium",
                  "weight":"Default",
                  "color":"Accent",
                  "isSubtle":true
               },
               {
                  "type":"Input.ChoiceSet",
                  "choices":[
                     {
                        "title":"English",
                        "value":1
                     }
                  ],
                  "wrap":true,
                  "separator":true,
                  "placeholder":"Choose a language",
                  "id":"languageId",
                  "isRequired":true,
                  "errorMessage":"Please select one to continue.",
                  "value":"${languageId}"
               },
               {
                  "type":"TextBlock",
                  "text":"I consent to the usage and processing of my data.",
                  "wrap":true,
                  "fontType":"Default",
                  "size":"Medium",
                  "weight":"Bolder",
                  "color":"Accent",
                  "isSubtle":true
               }
            ],
            "actions":[
               {
                  "type":"Action.Submit",
                  "title":"Continue",
                  "url":"${url}",
                  "associatedInputs":"auto",
                  "data":{
                     "msteams":{
                        "type":"messageBack",
                        "displayText":"StartSurvey with branching questions ",
                        "associatedInputs":"auto",
                        "text":"survey-start",
                        "value":"{\"surveyBroadcastId\": \"5a2b503b-e62a-4666-209a-08da70a93825\"}"
                     }
                  }
               },
               {
                  "type":"Action.Submit",
                  "title":"Cancel",
                  "url":"${url}",
                  "associatedInputs":"none",
                  "data":{
                     "msteams":{
                        "type":"messageBack",
                        "displayText":"Cancel Survey with branching questions ",
                        "associatedInputs":"none",
                        "text":"survey-cancel",
                        "value":"{\"surveyBroadcastId\": \"5a2b503b-e62a-4666-209a-08da70a93825\"}"
                     }
                  }
               }
            ]
         },
         "title":"Start Survey"
      }
   ]
}`

**Comment by ChetanSharma-msft** [comment]
@samthrusha123 - Thanks for reporting this issue.
We will look into it and get back to you.

**Comment by Nivedipa-MSFT** [comment]
@samthrusha123 - To fix the error message Unable to reach app. Please try again. You have to handle the long running operations.
Suppress of error message is not supported. Could you please raise an user voice here:
[Microsoft Teams Community](https://feedbackportal.microsoft.com/feedback/forum/ad198462-1c1c-ec11-b6e7-0022481f8472)
