### ISSUE TITLE
What determines when a card will be displayed as a card and when will it be listed?

### ISSUE THREAD

**Issue by baruchiro** [MicrosoftDocs/msteams-docs#656]
I see that when the title is a certain length, the cards cease to be buttons, and they are displayed as a numbered list within the message itself.

What sets it up?

And why?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28d1cbcc-9670-6eb3-d65a-5c30d307784a
* Version Independent ID: 243e29b8-afbc-7d21-1d24-18f58619af60
* Content: [Add card actions in a bot - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/cards/cards-actions)
* Content Source: [msteams-platform/concepts/Cards/cards-actions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/Cards/cards-actions.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Gousia-MSFT** [comment]
@baruchiro Can you please share a screenshot of the query you have?

**Comment by baruchiro** [comment]
Sure. I remember this from V4.3, but I can't find the code right now.

![image](https://user-images.githubusercontent.com/17686879/57921862-104f1300-78a7-11e9-87c1-61cd937bb062.png)

![image](https://user-images.githubusercontent.com/17686879/57921963-47252900-78a7-11e9-9ffd-a2b00b4a56e0.png)

I used "very very" because a one "very" is still a card.

**Comment by baruchiro** [comment]
It need a more research. I see it shown differently in Facebook and Telegram

**Comment by billbliss** [comment]
Can you give us the JSON for the message you are sending?

**Comment by baruchiro** [comment]
JSON for the short message:

``` json
{
  "attachments": [],
  "channelId": "emulator",
  "conversation": {
    "id": "3e91a080-7a59-11e9-b27e-b7f2dc2a2f8f|livechat"
  },
  "entities": [],
  "from": {
    "id": "2",
    "name": "Bot",
    "role": "bot"
  },
  "id": "4279fe40-7a59-11e9-99a0-d9c48d8a8fbc",
  "inputHint": "acceptingInput",
  "localTimestamp": "2019-05-19T20:12:19+03:00",
  "locale": "",
  "recipient": {
    "id": "d1ff7fc6-7de6-4208-bed8-0dd025aaaa26",
    "role": "user"
  },
  "replyToId": "4240ece0-7a59-11e9-99a0-d9c48d8a8fbc",
  "serviceUrl": "https://a943a825.ngrok.io",
  "suggestedActions": {
    "actions": [
      {
        "title": "short title",
        "type": "imBack",
        "value": "recommendations"
      }
    ]
  },
  "text": "Hi, select what you want",
  "timestamp": "2019-05-19T17:12:19.748Z",
  "type": "message"
}
```

JSON for the long title:
``` json
{
  "attachments": [],
  "channelId": "emulator",
  "conversation": {
    "id": "9476c340-7a59-11e9-b916-434698c80b5d|livechat"
  },
  "entities": [],
  "from": {
    "id": "2",
    "name": "Bot",
    "role": "bot"
  },
  "id": "9a384dd0-7a59-11e9-a6cb-c56ac337ce96",
  "inputHint": "acceptingInput",
  "localTimestamp": "2019-05-19T20:14:46+03:00",
  "locale": "",
  "recipient": {
    "id": "d1ff7fc6-7de6-4208-bed8-0dd025aaaa26",
    "role": "user"
  },
  "replyToId": "99fea030-7a59-11e9-a6cb-c56ac337ce96",
  "serviceUrl": "https://8b80b63c.ngrok.io",
  "text": "Hi, select what you want\n\n   1. A very very long title",
  "timestamp": "2019-05-19T17:14:46.956Z",
  "type": "message"
}
```

And this is how I create the `PromptOptions` dialog:

``` csharp
internal PromptOptions CreateChoicesPromptOptions(string text, IDictionary<string, string> keyToTitle)
{
    return new PromptOptions
    {
        Prompt = MessageFactory.Text(text),
        Choices = keyToTitle.Select(v =>
            new Choice(v.Key)
            {
                Action = new CardAction(ActionTypes.ImBack, v.Value, value: v.Key)
            })
            .ToList()
    };
}
```

**Comment by Gousia-MSFT** [comment]
@baruchiro 
![image](https://user-images.githubusercontent.com/45553518/57997834-64970480-7aec-11e9-80c3-8cb87ed45fd0.png)
Suggested actions is not supported in Microsoft Teams. Could you please try using [Cards and buttons](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/cards/cards)?

**Comment by baruchiro** [comment]
1. I didn't talk about Microsoft Teams. But maybe you mean a Bot Emulator is based on Microsoft Teams?
2. I'm working with Bot Framework C# libraries. So the [link](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/cards/cards) that you have mentioned, just describe the JSON for Microsoft Teams, but the only documentation for C# and BotFramework 4 still used [`CardAction`](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-add-suggested-actions?view=azure-bot-service-4.0&tabs=csharp).

**Comment by billbliss** [comment]
I'm confused about your question. Is your question about how messages are rendered in the bot emulator? The documentation in this repository is for Microsoft Teams specifically. If you want to ask questions about the bot emulator, I'd suggest here: https://github.com/Microsoft/BotFramework-Emulator/issues

**Comment by baruchiro** [comment]
Oh sorry!

I didn't notice that this was a **Microsoft Teams** documentation, I thought I was in the **BotFramework** documentation.

Anyway, thanks for the help, I think you helped me understand that the question focuses on `promptOption` with `ActionCards`.
