### ISSUE TITLE
[Doc Bash] Glossary Issues Part II

### ISSUE THREAD

**Issue by smol-elak** [MicrosoftDocs/msteams-docs#6561]
[Enter feedback here]

---
![image](https://user-images.githubusercontent.com/79516068/181580083-170a6895-b36d-4194-a820-5d09a26f6eee.png)
1. Client Secret definition can be improved. Also, reference to Bot is irrelevant.
1. Can we add FRE - First Run Experience into the glossary because CMO policies and design guidelines often refer to that.
⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff9690f5-fa8b-98bb-d3b4-ad4ed1030114
* Version Independent ID: ff9690f5-fa8b-98bb-d3b4-ad4ed1030114
* Content: [Microsoft Teams developer documentation - Glossary - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary#c)
* Content Source: [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/get-started/glossary.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by ChetanSharma-msft** [comment]
@surbhigupta12 - Please help us here to update the documentation.
