### ISSUE TITLE
Card Boarder Color in Chat

### ISSUE THREAD

**Issue by johnmiroki** [MicrosoftDocs/msteams-docs#6568]
Hi, I'd like my card (adaptive card) to have a top border color, much like the screenshot in below. What could be done? Thanks!

<img width="806" alt="image" src="https://user-images.githubusercontent.com/1551376/181672051-e2b9463a-7dbf-44e0-a163-97f1ca6110cf.png">

**Comment by ChetanSharma-msft** [comment]
@johnmiroki - Thanks for reporting this issue.
We will check and get back to you.

**Comment by Nivedipa-MSFT** [comment]
@johnmiroki - Using accentColor you can give the color to background for your outline icons. You have to add accentColor property in manifest file.
`  "accentColor": "A valid HTML color code.",`

Ref Doc: https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema#accentcolor

**Comment by johnmiroki** [comment]
@Nivedipa-MSFT Thank you. However, this doesn't work for me. I tried value "#fda402", update the version number, repackaged it and sideloaded it again, but color doesn't take effect. Any idea?

**Comment by johnmiroki** [comment]
Resolved
