### ISSUE TITLE
Deep Link to another app not working.

### ISSUE THREAD

**Issue by at-pi** [MicrosoftDocs/msteams-docs#6570]
Hello,

The deep link provided in the adaptive card button is not working, which was working previously. 
Adaptive card JSON for reference-

{
    body: keyMessageDetails,
    actions: [
      {
        type: "Action.OpenUrl",
        title: "Link Testing",
        url: "tact://assistant",
      }
    ],
    type: "AdaptiveCard",
    version: "1.4",
    msTeams: { width: "full" },
 }

<img width="643" alt="Screenshot 2022-07-29 at 1 40 52 PM" src="https://user-images.githubusercontent.com/31739160/181714990-4c598b3e-6fdd-4861-a5b0-c64d8b7574f0.png">

clicking on button received was redirecting to the external app, but now it is not doing anything.

**Comment by Prasad-MSFT** [comment]
@at-pi - To create a link to launch app in Teams, append the app ID to the following URL: `https://teams.microsoft.com/l/app/<your-app-id>`.
Could you please try in this way?

**Comment by at-pi** [comment]
@Prasad-MSFT - as mentioned earlier I am trying to open an external app outside teams, I want to redirect to this external app by clicking on the deep link provided in the adaptive card. This was working with the sample code pasted on the thread, but now it has stopped working.

**Comment by Prasad-MSFT** [comment]
@at-pi - Could you please try to update your MS Teams app version and check if it helps?

**Comment by at-pi** [comment]
> @at-pi - Could you please try to update your MS Teams app version and check if it helps?

@Prasad-MSFT - I updated the app but the problem is still not resolved.

**Comment by ChetanSharma-msft** [comment]
@at-pi - Thanks for the confirmation.
We will investigate on your issue and get back to you.

**Comment by Prasad-MSFT** [comment]
Seems like it is currently not supported. Here is the deep-link format as mentioned in official doc:
https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links?tabs=teamsjs-v2#deep-linking-to-an-app

**Comment by Prasad-MSFT** [comment]
We are closing this issue for now. Please feel free to reopen if required. Thanks!
