### ISSUE TITLE
Teams App SSO and SharePoint SSO

### ISSUE THREAD

**Issue by asith-w** [MicrosoftDocs/msteams-docs#6571]
I created Teams  Tab App that configured SSO as below Microsoft documentations and App work as expected
[tab-sso-register-aad](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/tab-sso-register-aad)  
[tab-sso-manifest](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/tab-sso-manifest )  

now I need to redirect user to their SharePoint site URL using teamslogon.aspx .
https://{tenant}.sharepoint.com/_layouts/15/teamslogon.aspx?spfx=true&dest=/sites/{mysite}  

but according to the current Teams app manifest _webApplicationInfo_ settings,  SharePoint redirection is not working.  It gives following error while redirecting to the SharePoint site
![image](https://user-images.githubusercontent.com/5784846/181720535-1916a72e-eeb4-4f58-83a5-1bac32098320.png)

is there possible configuration/way to solve this SharePoint authentication issue ?
### some  manifest data  
 ```  
{
...
...

    "staticTabs": [
        {
            "entityId": "d1117518-2222-1111-bbbb-56c7eaaaaaaa",
            "name": "Home",
            "contentUrl": "https://my-teams-app-my.azurewebsites.net/Tabs/Tab?loginHint={loginHint}&userObjectId={userObjectId}&userPrincipalName={userPrincipalName}&tenantId={tid}&locale={locale}&theme={theme}&userPrincipalName={userPrincipalName}",
            "scopes": [
                "personal"
            ]
        }
    ],
    "permissions": [
        "identity",
        "messageTeamMembers"
    ],
    "validDomains": [
        "{teamSiteDomain}",
        "my-teams-app-my.azurewebsites.net",
        "*.login.microsoftonline.com",
        "*.sharepoint.com",
        "resourceseng.blob.core.windows.net"
    ],
    "webApplicationInfo": {
        "resource": "api://my-teams-app-my.azurewebsites.net/123d3381-5e04-1234-1234-12350bef0123",
        "id": "123d3381-5e04-1234-1234-12350bef0123"
    },
    "isFullScreen": true
}
```
 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39428da3-d8be-43eb-80df-2b1f26ef6524
* Version Independent ID: 39428da3-d8be-43eb-80df-2b1f26ef6524
* Content: [Update manifest for enabling SSO for tabs - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/tab-sso-manifest)
* Content Source: [msteams-platform/tabs/how-to/authentication/tab-sso-manifest.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/tabs/how-to/authentication/tab-sso-manifest.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Nivedipa-MSFT** [comment]
@asith-w - Please verify the contents of webApplicationInfo section:

```
"webApplicationInfo": {
    "id": "{AAD App client id}",
    "resource": "api://{Your tab app domain}/{AAD App client id}"
  }
```
Please make sure the domain in webApplicationInfo is same as your tab app's domain, otherwise Teams will return error.

**Comment by asith-w** [comment]
@Nivedipa-MSFT  It is same. as in above manifest , _staticTabs.contentUrl_ and _webApplicationInfo.resource domain are same.

**Comment by asith-w** [comment]
@ChetanSharma-msft here is manifest( some urls & names are changed to avoid real names)
```
{
    "$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.8/MicrosoftTeams.schema.json",
    "manifestVersion": "1.8",
    "version": "1.0.0",
    "id": "52fdc0ca-8aa9-4522-a17e-8725fe614aba",
    "packageName": "APP_NAME",
    "developer": {
        "name": "COMPANY_NAME GmbH",
        "websiteUrl": "https://www.COMPANY_NAME.com",
        "privacyUrl": "https://www.COMPANY_NAME.com/privacy-policy-services",
        "termsOfUseUrl": "https://www.COMPANY_NAME.com/terms-and-conditions-services",
        "mpnId": ""
    },
    "icons": {
        "color": "color.png",
        "outline": "outline.png"
    },
    "name": {
        "short": "APP_NAME",
        "full": "APP_NAME by COMPANY_NAME"
    },
    "description": {
        "short": "APP_NAME - description",
        "full": "APP_NAME - full description."
    },
    "accentColor": "#d03808",
    "configurableTabs": [
        {
            "configurationUrl": "https://my-teams-app-my.azurewebsites.net/TeamTabs/TabConfiguration?loginHint={loginHint}&userObjectId={userObjectId}&userPrincipalName={userPrincipalName}&tenantId={tid}&locale={locale}&theme={theme}&userPrincipalName={userPrincipalName}",
            "canUpdateConfiguration": false,
            "scopes": [
                "team"
            ]
        }
    ],
    "staticTabs": [
        {
            "entityId": "d12c7518-3b2a-4a1f-a39b-56c7edad4a3a",
            "name": "Home",
            "contentUrl": "https://my-teams-app-my.azurewebsites.net/StaticTabs/MainTab?loginHint={loginHint}&userObjectId={userObjectId}&userPrincipalName={userPrincipalName}&tenantId={tid}&locale={locale}&theme={theme}&userPrincipalName={userPrincipalName}",
            "scopes": [
                "personal"
            ]
        }
    ],
    "permissions": [
        "identity",
        "messageTeamMembers"
    ],
    "validDomains": [
	    "{teamSiteDomain}",
        "my-teams-app-my.azurewebsites.net",
        "*.login.microsoftonline.com",
        "*.sharepoint.com",
        "*.sharepoint-df.com",
        "spoppe-a.akamaihd.net",
        "spoprod-a.akamaihd.net",
        "resourceseng.blob.core.windows.net",
        "msft.spoppe.com"
    ],
    "webApplicationInfo": {
		"id": "25a08858-151f-477d-8fff-e72c9254ac95",
        "resource": "api://my-teams-app-my.azurewebsites.net/25a08858-151f-477d-8fff-e72c9254ac95" 
        
    },
    "isFullScreen": true
}
```

**Comment by Nivedipa-MSFT** [comment]
@asith-w - We are checking this internally. We will update you soon.

**Comment by asith-w** [comment]
@Nivedipa-MSFT this is  redirection to a SharePoint site from the app as below

```
 const { hostname, pathname } = new URL(siteUrl);
 const url = `https://${hostname}/_layouts/15/teamslogon.aspx?spfx=true&dest=${pathname}`;
 window.location.assign(url);
```

URL will be like '**https://{tenant}.sharepoint.com/_layouts/15/teamslogon.aspx?spfx=true&dest=/sites/{mysite}**'

**Comment by Nivedipa-MSFT** [comment]
@asith-w - We are checking this internally. We will update you soon.

**Comment by asith-w** [comment]
@Nivedipa-MSFT it can be either static or configurable tab, 
for example, when this Team tab app is loading, app get valid SharePoint url from a DB for the current user and tenant  based on some logic
after that,  it  redirects to SP site.  

Tap page do something similar to below functionality 
 ```js
const siteUrl = getSPSiteUrlForUser( userId, tenantId ) //custom api call 
 redirectToSharePoint( siteUrl )
```

**Comment by Nivedipa-MSFT** [comment]
@asith-w - Are you displaying Sign In form in that SharePoint URL?

**Comment by Nivedipa-MSFT** [comment]
@asith-w - Could you please add the URL in validDomains section which you are getting in siteUrl?
Could you please confirm is this a same tenant sharepoint Url where your app is uploaded?
