### ISSUE TITLE
Customze Feed Notification Sent by Proactive Message + activity.teamsNotifyUser()

### ISSUE THREAD

**Issue by johnmiroki** [MicrosoftDocs/msteams-docs#6572]
When sending a proactive message (the content is Adaptive Card) to users, activity.teamsNotifyUser() is invoked, and users get a Feed notification. However, the Feed's content is a mere "Card", not very helpful. Is there any way to customize the content making it more user-friendly? Thanks!

```java
        public CompletableFuture<Void> invoke(TurnContext turnContext) {
          activity.teamsNotifyUser();
          return turnContext.sendActivity(activity).thenApply(resourceResponse -> null);
        }
```

<img width="450" alt="image" src="https://user-images.githubusercontent.com/1551376/181740393-87803e8e-4832-4c03-aea5-620783b19f8c.png">

**Comment by Nivedipa-MSFT** [comment]
@johnmiroki - We are investigating your query. We will get back to you once we have any update.

**Comment by johnmiroki** [comment]
@Prasad-MSFT Thank you so much!

**Comment by johnmiroki** [comment]
@Nivedipa-MSFT Hi Nivedipa, in this diagram of [Feed](https://docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications) (See below), there are many different parts, eg avatar, actor + reason, and etc. Now activity.summary is responsible for only one part of that (text), is there any way to control the other parts? appreciate it!

<img width="1045" alt="image" src="https://user-images.githubusercontent.com/1551376/183819084-26fd67bd-9234-453e-8fa5-a7706cd87d50.png">

**Comment by Nivedipa-MSFT** [comment]
@johnmiroki - We are investigating your query. We will update you soon.
