### ISSUE TITLE
[Doc feedback] - Update existing code snippet

### ISSUE THREAD

**Issue by Prithvi-MSFT** [MicrosoftDocs/msteams-docs#6573]
The provided code snippet will give errors for typescript files as it assigns value of different type to variable e. We can use below code snippet instead

```
<body> 
<div> 
<div class="sectionTitle">openPurchaseExperience</div> 
<button onclick="openPurchaseExperience()">openPurchaseExperience</button> 
</div> 
</body> 
<script> 
   function openPurchaseExperience() {
      microsoftTeams.initialize();
      let callbackcalled = false;
      microsoftTeams.monetization.openPurchaseExperience((e) => {
            console.log("callback is being called");
            console.log(e);
            if (!!e && typeof e !== "string") {
                  alert(JSON.stringify(e));
              }
              return;
            });
      console.log("after callback: ",callbackcalled);
    } 
</script> 
```

Also the provided code snippet works for teams sdk v11 and before. We can add additional code snippet for v2. Here is the code snippet

```
<body> 
<div> 
<div class="sectionTitle">openPurchaseExperience</div> 
<button onclick="openPurchaseExperience()">openPurchaseExperience</button> 
</div> 
</body> 
<script> 
   function openPurchaseExperience() {
      app.initialize();
	   var planInfo = {
        planId: "<Plan id>", // Plan Id of the published SAAS Offer
        term: "<Plan Term>" // Term of the plan.
    }
      monetization.openPurchaseExperience(planInfo);
    } 
</script> 
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dab418db-0c5b-7ec5-aaa5-7bd109d5ae1d
* Version Independent ID: dab418db-0c5b-7ec5-aaa5-7bd109d5ae1d
* Content: [In-app purchase flow for the monetization of apps - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow)
* Content Source: [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md)
* Service: **msteams**
* GitHub Login: @v-npaladugu
* Microsoft Alias: **surbhigupta**

**Comment by ChetanSharma-msft** [comment]
Hello @surbhigupta12 - Please help us here to update the documentation.
