### ISSUE TITLE
State clearly that bot SSO is supported only in 1:1 chat

### ISSUE THREAD

**Issue by aosolis** [MicrosoftDocs/msteams-docs#6574]
This critical information is buried in a comment in the code sample:
<img width="447" alt="image" src="https://user-images.githubusercontent.com/767208/181829112-b7f7a769-3017-4cef-81e2-74b303e5c810.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9549caa9-99a2-2568-19a5-f21a79292e2f
* Version Independent ID: f2100d03-b88a-34b2-44a2-935231e89db0
* Content: [Single sign-on support for bots - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/authentication/auth-aad-sso-bots)
* Content Source: [msteams-platform/bots/how-to/authentication/auth-aad-sso-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/bots/how-to/authentication/auth-aad-sso-bots.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by sayali-MSFT** [comment]
We are looking into this we will get back to you soon.
