### ISSUE TITLE
[Doc Bash] Need documentation on how to provision using a new resource group

### ISSUE THREAD

**Issue by spandana-12** [MicrosoftDocs/msteams-docs#6576]
Provisioning the app in Azure by creating a new resource group throws an error (attaching the screenshot). Need documentation on how to create a new resource group and the roles/permissions needed to do so. Azure subscription used by me for this is msteams.nonprod.pub.msft.aplt
<img width="914" alt="image" src="https://user-images.githubusercontent.com/109669530/182161086-b640c55e-5a0b-45bb-82d3-bf4c29a936b6.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e473e1f3-69f5-bcfa-bcab-54b098b59c80
* Version Independent ID: e473e1f3-69f5-bcfa-bcab-54b098b59c80
* Content: [Hello World with JavaScript - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-javascript?tabs=vscode%2Cvsc%2Cviscode&tutorial-step=1)
* Content Source: [msteams-platform/sbs-gs-javascript.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/sbs-gs-javascript.yml)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by ChetanSharma-msft** [comment]
@surbhigupta12 - Please help us here to update the documentation.
