### ISSUE TITLE
Google auth on Microsft Teams mobile app returns 403: disallowed_useragent 

### ISSUE THREAD

**Issue by stijndeschuymer** [MicrosoftDocs/msteams-docs#6577]
I'm facing similar a similar issue as described in the following issue:
https://github.com/MicrosoftDocs/msteams-docs/issues/1607

We've created a teams app that opens a popup using:
```
import { authentication } from '@microsoft/teams-js';
authentication.authenticate({ url: ... }); // open popup with google authentication
```
On Android, the google auth flow redirects to an error page:
![1659363330789](https://user-images.githubusercontent.com/4083920/182168142-8d50a605-dde8-4bf6-be1d-1004199685d3.jpg)

**Comment by Nivedipa-MSFT** [comment]
@stijndeschuymer - Could you please share which sample are you referring for this?

**Comment by Nivedipa-MSFT** [comment]
@stijndeschuymer - Could you please confirm is your issue resolved with above suggestion or are you still facing this issue?

**Comment by Nivedipa-MSFT** [comment]
@stijndeschuymer - Could you please confirm is your issue resolved with above suggestion or are you still facing this issue?
