### ISSUE TITLE
Deeplink to another apps in MS Teams is not working on mobile

### ISSUE THREAD

**Issue by AccammaGeo** [MicrosoftDocs/msteams-docs#6595]
I need to add deeplinks to different MS template applications in MS Teams. In mobile it is not working, getting different error messages in IOS and android. In IOS it is showing as "Link not supported" and in android it is showing as "Not supported on mobile"
"

**Comment by ChetanSharma-msft** [comment]
@AccammaGeo - Thanks for reporting the issue.
We will look into it and get back to you.

**Comment by ChetanSharma-msft** [comment]
@AccammaGeo - Are you following below format?
**https://teams.microsoft.com/l/app/<your-app-id>**

https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links?tabs=teamsjs-v2#deep-linking-to-an-app

**Comment by AccammaGeo** [comment]
> @AccammaGeo - Are you following below format? **https://teams.microsoft.com/l/app/**
> 
> https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links?tabs=teamsjs-v2#deep-linking-to-an-app

@ChetanSharma-msft Yeah, we are following this format

**Comment by ChetanSharma-msft** [comment]
Hello @AccammaGeo - Currently **`https://teams.microsoft.com/l/app/<your-app-id>`** links are not supported on Mobile platform.

We will raise a document issue to add the note in the documentation.

**Comment by ghazzalj** [comment]
Hello @ChetanSharma-msft, it is actually working for vendor applications (FreshDesk) on Android, but it does not work on IOS, and other deeplinks for other custom apps does not work on both Android and IOS as @AccammaGeo mentioned.  So do you think it is a different issue since the deep link to FreshDesk works on Android?

**Comment by sayali-MSFT** [comment]
@AccammaGeo @ghazzalj -The /l/app deeplink will not work on iOS unless the target app (in the deeplink) has updated the Apple App Store Connect Team ID on the Partner Center and republished the app. 
Process to update the Apple Team ID is documented here: https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/create-partner-center-dev-account#update-apple-app-store-connect-team-id-on-partner-center
