### ISSUE TITLE
Update the screenshot in what are bots article

### ISSUE THREAD

**Issue by ashishguptaiitb** [MicrosoftDocs/msteams-docs#6599]
Have a trimmed version of `task-module-example.png` image, along with the highres version.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3af8496d-46be-a691-11e1-16734f71f891
* Version Independent ID: be0ff3e1-8bef-5ca7-8d9c-566e89e3fd41
* Content: [Bots in Microsoft Teams - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/what-are-bots)
* Content Source: [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/bots/what-are-bots.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **anclear**

**Comment by Prasad-MSFT** [comment]
@ashishguptaiitb - Task Module generally pops out which has been shown in the below picture. So, if we will trim, it won't be much explanatory.
![image](https://user-images.githubusercontent.com/62237649/182820748-bb84086f-9d56-48c8-be7f-11e4ce51d5a4.png)

**Comment by ashishguptaiitb** [comment]
> @ashishguptaiitb - Task Module generally pops out which has been shown in the below picture. So, if we will trim, it won't be much explanatory. ![image](https://user-images.githubusercontent.com/62237649/182820748-bb84086f-9d56-48c8-be7f-11e4ce51d5a4.png)

@Prasad-MSFT , there's a lightbox route to do both -- show a small one but enlarge when required. Right now the screenshot occupies the entire monitor when reading the doc. Such large ones only obstruct the reading. Poor UX.

**Comment by Prasad-MSFT** [comment]
@surbhigupta12 - Please help here to update the task module image as described with higher resolution.
