### ISSUE TITLE
Message Extensions `message` result only works when in the `message` context

### ISSUE THREAD

**Issue by wictorwilen** [MicrosoftDocs/msteams-docs#660]
When using message extensions that returns simple `message` results, it only works if the message extension is using the `message` context and it gives a JavaScript error when in `compose` or `commandBox`.

Compose extension result used:
``` JSON
{
    "composeExtension": {
        "type": "message",
        "text": "Some text...."
    }
}
```

JavaScript error:
```
TypeError: Cannot read property 'attachments' of undefined
```

Is this by design? Is this documented?

**Comment by maoyu-dev** [comment]
Can you clarify in what scenario you are returning this result?

**Comment by wictorwilen** [comment]
If I return that message from a message extension command that is executed from the compose box or the command box I get that error, but not when it's an action on a message

**Comment by maoyu-dev** [comment]
Thanks @wictorwilen! The exception is definitely not expected, we will have a bug to fix it on our side. However, it may or may not achieve what you are planning to do.
Do you intend to drop a text into compose box, or show a message as the search result?

**Comment by Wajeed-msft** [comment]
We are tracking this internally. Closing this from documentation issues.
