### ISSUE TITLE
Typing Indicator for bot framework restful API

### ISSUE THREAD

**Issue by Chang025** [MicrosoftDocs/msteams-docs#6608]
Hi,
Is there any way to enable the typing indicator for bot framework restful conversation APIs?

**Background:**
We are consuming MS Teams restful api for our conversation AI bot. We want the typing indicator to be displayed just after the user send any message.
restful API reference: https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-api-reference?view=azure-bot-service-4.0#get-conversation-member

**Note:**
We are not using bot framework SDK.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55c5e4a1-6116-ec92-36e9-b94097bd83c7
* Version Independent ID: fd843eef-73e2-7a7e-9ac4-5c20fcf1fa2f
* Content: [Invoke and dismiss task modules - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/task-modules/invoking-task-modules)
* Content Source: [msteams-platform/task-modules-and-cards/task-modules/invoking-task-modules.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/task-modules/invoking-task-modules.md)
* Product: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **lajanuar**

**Comment by sayali-MSFT** [comment]
@Chang025 - We are looking into this we will get back to you soon.

**Comment by Chang025** [comment]
@sayali-MSFT - Thank you for the response. I am able to achieve the typing indicator by passing this request body:
`{
  "type": "typing",
  "from": {
    "id": "28:fXXXXXXXXX",
    "name": "DemoDevPortalTest2"
  },
  "conversation": {
    "conversationType": "personal",
    "tenantId": "aXXXXXX",
    "id": "a:XXXXXXX"
  },
  "recipient": {
    "id": "29XXXXXXXXX",
    "name": "Test XXXX",
    "aadObjectId": "2XXXXXXXXX"
  }
}`
but the problem with this is, that it keeps on showing it in teams for 20 seconds, we want a way to limit it to 5 seconds.
Is there any parameter we can pass in the req body to limit the typing indicator duration?

**Comment by sayali-MSFT** [comment]
@Chang025 -Could you please share the repro steps to achieve the typing indicator, So that we can investigate from our end. Thanks!
