### ISSUE TITLE
Branding details are not reflecting immediately

### ISSUE THREAD

**Issue by Chang025** [MicrosoftDocs/msteams-docs#6609]
We have updated the branding detail of our app inside the developer portal and published it across the network, but the branding details are not reflected immediately.

Updated logo:
<img width="1792" alt="Screenshot 2022-08-05 at 1 34 09 PM" src="https://user-images.githubusercontent.com/46022906/183039820-47088033-ed85-457a-b7ff-57e1f3e55cdb.png">

Chat window of end user[Not refecting]:
<img width="368" alt="Screenshot 2022-08-05 at 1 34 33 PM" src="https://user-images.githubusercontent.com/46022906/183039889-2bbebcd4-0e1d-4059-93f6-5000160a49ec.png">

How long does it take to replicate the branding details to the end users after publishing the changes?

**Comment by Prasad-MSFT** [comment]
@Chang025 - It takes few minutes to few hours to update the icon. There is no specific timeline.
