### ISSUE TITLE
Update TOC location of bots v3 SDK docs

### ISSUE THREAD

**Issue by ashishguptaiitb** [MicrosoftDocs/msteams-docs#6610]
Article mentions, " see the [bots - v3 SDK](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bots-overview) section in the Resources folder of the documentation. "
The v3 SDK docs exist in `Legacy SDK` location in the docs and not under `Resources`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ad9f167-7d29-f933-7b47-60bd744899b1
* Version Independent ID: 8097fcbd-adcc-ce49-a378-426c65af9296
* Content: [Send proactive messages - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/send-proactive-messages?tabs=dotnet)
* Content Source: [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/bots/how-to/conversations/send-proactive-messages.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **anclear**

**Comment by Meghana-MSFT** [comment]
Thank you for reporting this, we will check and act accordingly. Thank you.

**Comment by Meghana-MSFT** [comment]
@surbhigupta12 - Can you please change the sentence  "see the [bots - v3 SDK](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bots-overview) section in the Resources folder of the documentation." to  "see the [bots - v3 SDK](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bots-overview) section in the Legacy SDKs folder of the documentation." in [Proactive messages](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/send-proactive-messages?tabs=dotnet).
