### ISSUE TITLE
Incorrect permission for adding members to teams when migrating data

### ISSUE THREAD

**Issue by cabadam** [MicrosoftDocs/msteams-docs#6611]
When executing "Step five: Add team members", an error is returned:
Missing role permissions on the request. API requires one of 'TeamMember.ReadWriteNonOwnerRole.All, TeamMember.ReadWrite.All, Group.ReadWrite.All'. Roles on the request 'TeamMember.Read.All, Teamwork.Migrate.All, Group.Read.All, Team.Create, Group.Create, Directory.Read.All, User.Read.All, Team.ReadBasic.All'.

Either the system is wrong and this operation should be allowed when you have Teamwork.Migrate.All, or the documentation page is incorrect and the "Permission" table under Step 1 should be updated appropriately.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5687f17-f3c7-39be-5487-f24f2155191a
* Version Independent ID: ce77e760-90cf-e6b1-3cec-ae55ee50c33e
* Content: [Use Microsoft Graph to import external platform messages to Teams - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/graph-api/import-messages/import-external-messages-to-teams#step-2-create-a-channel)
* Content Source: [msteams-platform/graph-api/import-messages/import-external-messages-to-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/graph-api/import-messages/import-external-messages-to-teams.md)
* Service: **msteams**
* GitHub Login: @AkJo
* Microsoft Alias: **lajanuar**

**Comment by Prasad-MSFT** [comment]
We are checking the issue. We will get back to you shortly.
