### ISSUE TITLE
Edits required in customize your Teams app article

### ISSUE THREAD

**Issue by ashishguptaiitb** [MicrosoftDocs/msteams-docs#6612]
Headings can be better. 
No content between title and first heading?
Update screenshots.
Note can be better or consider removing it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54a9aab3-9fa7-9870-ea07-fd8504e21874
* Version Independent ID: 44cad9f8-b5d8-5e2f-4615-0160b73e89f7
* Content: [Customize your Teams app - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/design/enable-app-customization)
* Content Source: [msteams-platform/concepts/design/enable-app-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/design/enable-app-customization.md)
* Service: **msteams**
* GitHub Login: @heath-hamilton
* Microsoft Alias: **surbhigupta**

**Comment by ChetanSharma-msft** [comment]
Hello @surbhigupta12 - Please help us here to update the documentation.

**Comment by ashishguptaiitb** [comment]
@ChetanSharma-msft , do you think the label to this issue is incorrect? Shouldn't it be doc-enhancement or a doc-bug?
