### ISSUE TITLE
Clarification of how to set the app id URI for tab SSO

### ISSUE THREAD

**Issue by BrendanAndrade** [MicrosoftDocs/msteams-docs#6613]
It the section "To expose an API" in the important block (https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/tab-sso-register-aad#to-expose-an-api), it states to "enter the application ID URI as api://fully-qualified-domain-name.com/BotId-{YourClientId}, where the BotID is your bot app ID."

In the URI, BotId should be in brackets {} to signify that it needs to be substituted and the "Your Client Id" should be explained that it needs to be the client ID of the Azure app. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52cb5b2e-e1e9-1993-04a0-6925d1453f20
* Version Independent ID: 52cb5b2e-e1e9-1993-04a0-6925d1453f20
* Content: [Register your tab app with Azure AD - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/tab-sso-register-aad)
* Content Source: [msteams-platform/tabs/how-to/authentication/tab-sso-register-aad.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/tabs/how-to/authentication/tab-sso-register-aad.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Prasad-MSFT** [comment]
@BrendanAndrade - The documentation seems to be correct only. Application ID URI for app with multiple capabilities should be in below format:
`api://fully-qualified-domain-name.com/BotId-{YourClientId}`, where the BotID is your bot app ID.

e.g. `api://fully-qualified-domain-name.com/BotId-a246b078-394d-4858-84f1-aa6fdb84b80b`
