### ISSUE TITLE
Incorrect alignment in code snippet on "Receive all channel messages with RSC"

### ISSUE THREAD

**Issue by sfritz** [MicrosoftDocs/msteams-docs#6614]
The alignment is incorrect in this code snippet:

```
"webApplicationInfo": {
"id": "XXxxXXXXX-XxXX-xXXX-XXxx-XXXXXXXxxxXX",
"resource": "https://AnyString",
"applicationPermissions": [
"ChannelMessage.Read.Group"
    ]
  }
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e0acfd2-0965-65f4-2200-ca06424a3976
* Version Independent ID: fd7f72fe-5dba-369a-c436-6140d232ad44
* Content: [Receive all channel messages with RSC - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/channel-messages-with-rsc?tabs=dotnet)
* Content Source: [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md)
* Service: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **lajanuar**

**Comment by ChetanSharma-msft** [comment]
Hello @surbhigupta12 - Please help here to update the documentation.

**Comment by sfritz** [comment]
> Hello @surbhigupta12 - Please help here to update the documentation.

FYI there's a PR ready here: https://github.com/MicrosoftDocs/msteams-docs/pull/6615
