### ISSUE TITLE
Generating avatar for number of attendees in an adaptive card

### ISSUE THREAD

**Issue by tsalex1992** [MicrosoftDocs/msteams-docs#6616]
Hello, I'm trying to develop an adaptive card in Teams which will be able to generate an avatar which displays the number of attendees in the meeting.
For instance 10+ for more than 10 attendees - is there an endpoint for the teams service to retrieve such avatar?

Thanks ahead,
Alex.

**Comment by Prasad-MSFT** [comment]
@tsalex1992 - There doesn't seem to be any API available to retrieve such avatar.

**Comment by Prasad-MSFT** [comment]
We are closing the issue for now. Please feel free to reopen if required.
