### ISSUE TITLE
Doc Bash][]

### ISSUE THREAD

**Issue by harsha2290** [MicrosoftDocs/msteams-docs#6617]
[1. Additional dialogue just before bot creation. Pop window that says do you trust authors of the files in folder?
2. .fx/states folder is not visible in the bot directory picture that is added. (also not visible in Visual studio code)]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50ff9656-96f9-9a62-0c9a-da20986eeb13
* Version Independent ID: 50ff9656-96f9-9a62-0c9a-da20986eeb13
* Content: [Hello World with JavaScript - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-bot?tabs=vscode%2Cviscode&tutorial-step=5#install-the-teams-toolkit)
* Content Source: [msteams-platform/sbs-gs-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/sbs-gs-bot.yml)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Nivedipa-MSFT** [comment]
@harsha2290 - Could you please elaborate your issue?

**Comment by Nivedipa-MSFT** [comment]
@surbhigupta12 - Could you please add below point after 8th point in [this](https://docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-bot?tabs=vscode%2Cviscode&tutorial-step=2#install-the-teams-toolkit) document.
9. You will get additional dialogue just before bot creation. Pop window that says do you trust authors of the files in folder?

![image](https://user-images.githubusercontent.com/92150070/184340391-539a9e05-6a58-4dfb-8650-c55fe3d55dcf.png)

Could you please remove below .fx/states related row from table/

![image](https://user-images.githubusercontent.com/92150070/184340807-ec72f30d-44f8-4837-b092-3fafa4c5bc77.png)
