### ISSUE TITLE
Sending approval requests to Teams approvals app , using azure logic app without using power automate.

### ISSUE THREAD

**Issue by yamanivamsi55** [MicrosoftDocs/msteams-docs#6620]
I couldn't find the appropriate solution for the above mentioned requirement. Please assist...

**Comment by ChetanSharma-msft** [comment]
@yamanivamsi55 - Are you developing 3rd party app or trying to use 1st party Microsoft build app ?

**Comment by yamanivamsi55** [comment]
> @yamanivamsi55 - Are you developing 3rd party app or trying to use 1st party Microsoft build app ?

i am using first party microsoft buid app

**Comment by Nivedipa-MSFT** [comment]
We are mainly responsible for Microsoft Teams 3rd party app development related issues.  

For Microsoft Teams product issues/failures your tenant Admin can reach out to [Microsoft 365 Product Support](https://docs.microsoft.com/en-us/microsoft-365/admin/get-help-support?view=o365-worldwide&tabs=online).  

For general questions about Microsoft Teams please post your question on [Microsoft Teams Community](https://answers.microsoft.com/en-us/msteams/forum?sort=LastReplyDate&dir=Desc&tab=All&status=all&mod=&modAge=&advFil=&postedAfter=&postedBefore=&threadType=All&isFilterExpanded=false&page=1).
