### ISSUE TITLE
Documentation section needs to be updated for "Toggle incoming audio"

### ISSUE THREAD

**Issue by Mohammed-MSFT** [MicrosoftDocs/msteams-docs#6621]
Kindly help us here to update the below documentation section:
https://docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/api-references?tabs=dotnet#toggle-incoming-audio

1) highlighted "Example" text is actually a Syntax of method, so it should be renamed as "Syntax":
![image](https://user-images.githubusercontent.com/109147706/183411174-9d45aeec-f72e-4383-80bd-8e43c24ce24a.png)

2) Please add another section for "Example" and add the code snippets  like below:
```
callback = (error, result) => {
        if (error) {
            // Handle error code
        }
        else {
            // Handle success code
        }
    }

microsoftTeams.meeting.toggleIncomingClientAudio(this.callback)
```
3) Add one more section for manifest like below:
```
"authorization": {
    "permissions": {
      "resourceSpecific": [
        {
          "name": "OnlineMeetingParticipant.ToggleIncomingAudio.Chat",
          "type": "Delegated"
        }
      ]
    }
  }
```

4) Also, add a note like below (May be before the manifest section or at the suitable place):
**"RSC has been enabled post 1.11 hence this feature will not work below 1.12"**

5) Please change the heading "Get incoming audio speaker" to "Get incoming audio state", The result can either contain true or false value when the audio fetch is successful.
![image](https://user-images.githubusercontent.com/109147706/184804368-60c50951-c21a-4b54-ac88-97a47579e67b.png).

**Section to be updated:** https://docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/api-references?tabs=dotnet#get-incoming-audio-speaker

6) "Example" section should be removed because it is actually a Syntax.
**Section to be updated:** https://docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/api-references?tabs=dotnet#example-7

7) Please add another section for **"Example"** and add the code snippets  like below:
```
callback = (errcode, result) => {
        if (errcode) {
            // Handle error code
        }
        else {
            // Handle success code
        }
    }

microsoftTeams.meeting.getIncomingClientAudioState(this.callback)
```
**Section to be updated:** https://docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/api-references?tabs=dotnet#get-incoming-audio-speaker

8) Add one more section for manifest like below:
```
"authorization": {
    "permissions": {
      "resourceSpecific": [
        {
          "name": "OnlineMeetingParticipant.ToggleIncomingAudio.Chat",
          "type": "Delegated"
        }
      ]
    }
  }
```

**Section to be updated:** https://docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/api-references?tabs=dotnet#get-incoming-audio-speaker

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 805dc242-7b5a-cc81-ee0e-6acf0078a653
* Version Independent ID: 11c0e023-2514-9639-6052-2cbbbef50663
* Content: [Meeting apps API references - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/api-references?tabs=dotnet#get-incoming-audio-speaker)
* Content Source: [msteams-platform/apps-in-teams-meetings/API-references.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/apps-in-teams-meetings/API-references.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by ChetanSharma-msft** [comment]
Hello @surbhigupta12 - Please help us here to update the documentation.
