### ISSUE TITLE
[Feature Request] Rich Text Editor for Input.Text

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#6624]
Copied bug from: https://github.com/microsoft/AdaptiveCards/issues/7739 

**Details from original post:**
### Problem Statement

We are working on the Github app for MS Teams and would like to implement a rich text editor in the task module for Input.Text.

This is our current experience. 
<img width="932" alt="image" src="https://user-images.githubusercontent.com/46958410/182646990-29d18732-5983-40a4-8d6f-ac1538a86d4b.png">

For our Description field, we would like to have a rich text editor like what is present in the JIRA app for MS Teams.
<img width="279" alt="image" src="https://user-images.githubusercontent.com/46958410/182647278-eb4aea3d-f4ab-4242-9201-f083c7e911cc.png">

### Proposed solution

Please let us know how this can be made possible or and workaround that we can use to achieve this experience.

### Alternatives or Workarounds

_No response_---
#### Document Details

⚠ *Do not edit this section.It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Cards reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **surbhigupta12**

**Comment by Meghana-MSFT** [comment]
We are looking into this issue, we will get back to you.

**Comment by Meghana-MSFT** [comment]
Currently this is not supported. To achieve your requirements, we recommend you give your feedback in [Microsoft Teams feedbackportal](https://feedbackportal.microsoft.com/feedback/forum/ad198462-1c1c-ec11-b6e7-0022481f8472).
Microsoft will always focus on customer’s feedback and experience. Some new features would be added to the services based on customers' feedback in the future, and your good ideas will be very helpful for them to improve the service.

**Comment by Meghana-MSFT** [comment]
We are closing this issue, please feel free to reopen if required. Thank you.
