### ISSUE TITLE
update "validDomains" after adding authentication to message extension

### ISSUE THREAD

**Issue by moira2k** [MicrosoftDocs/msteams-docs#6625]
[Enter feedback here]
Could you remind the user to add the "token.botframework.com" to "validDomains" after adding authentication to the message extension?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 503e124f-2b80-d6ae-581a-ca77f0a1999f
* Version Independent ID: 66d2bd8a-536b-1a45-f71c-eb2a0199de46
* Content: [Add authentication to your message extension - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/add-authentication)
* Content Source: [msteams-platform/messaging-extensions/how-to/add-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/messaging-extensions/how-to/add-authentication.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **anclear**

**Comment by Prasad-MSFT** [comment]
Thanks @moira2k for your feedback.
@surbhigupta12 - It would be better if we add a note in this [doc](https://docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/add-authentication) saying the user to add the "token.botframework.com" to "validDomains" section in manifest after adding authentication to message extension
