### ISSUE TITLE
the created team could not be displayed on teams client

### ISSUE THREAD

**Issue by shiyaojun-pactera** [MicrosoftDocs/msteams-docs#6649]
After I followed the step1-4
when I tried to see the created teams by my teams client, it didn't show the created teams on my teams client.
Do you know the reason?
And to the step 5, it always showed 
You do not have permission to perform this operation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5687f17-f3c7-39be-5487-f24f2155191a
* Version Independent ID: ce77e760-90cf-e6b1-3cec-ae55ee50c33e
* Content: [Use Microsoft Graph to import external platform messages to Teams - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/graph-api/import-messages/import-external-messages-to-teams)
* Content Source: [msteams-platform/graph-api/import-messages/import-external-messages-to-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/graph-api/import-messages/import-external-messages-to-teams.md)
* Service: **msteams**
* GitHub Login: @AkJo
* Microsoft Alias: **lajanuar**

**Comment by Meghana-MSFT** [comment]
We are looking into this, we will get back to you.

**Comment by Meghana-MSFT** [comment]
We are also not able to see the team, we are checking this internally. For step 5 could you please try adding member using Graph explorer(delegated permissions)

**Comment by shiyaojun-pactera** [comment]
@Meghana-MSFT  yes.I tried to call the API to add some users to my teams but also the error message showed ""You do not have permission to perform this operation"

**Comment by Meghana-MSFT** [comment]
ok, we are checking with the engineering team and get back to you.

**Comment by Meghana-MSFT** [comment]
@shiyaojun-pactera - In [Step 4: Complete migration mode](https://docs.microsoft.com/en-us/microsoftteams/platform/graph-api/import-messages/import-external-messages-to-teams#step-4-complete-migration-mode), we need to end channel migration for general channel as well. 

Use [List channels](https://docs.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-1.0&tabs=http) to get the channel id for general channel. And complete migration for this general channel as well.

Please complete the migration step before adding members.

**Comment by Meghana-MSFT** [comment]
@shiyaojun-pactera - Please try the above suggestion and try again.

**Comment by shiyaojun-pactera** [comment]
@Meghana-MSFT  sorry for the late reply.Yes I can see my teams on my client now ! Thanks for the support!
