### ISSUE TITLE
SSO- Token is not being generated for Users in AAD.

### ISSUE THREAD

**Issue by Manasa-acuvate** [MicrosoftDocs/msteams-docs#6654]
Hi,
We observed that for users, SSO Token is not getting generated in Azure AD.
This is not happening for all users. For some users SSO Token is being generated and for few users Token is not getting generated.
We would like to know the root cause/exact reason related to this behavior.
Thank-you!

**Comment by Nivedipa-MSFT** [comment]
@Manasa-acuvate - Could you please share the repro steps to try at our end.

**Comment by PuspanjaliMuduli** [comment]
-This is related to Una chatbot application.
-The channel used by Una bot is MS Teams.
-The application is registered through azure active directory for SSO.
- Whenever user enters the Una Chat Bot token should be automatically generated, but 
for some user it is not happening.
- So please check from your side what is the reason for this issue. Can't give any exact repro steps for this.
Thank you!

**Comment by Nivedipa-MSFT** [comment]
@PuspanjaliMuduli - We are checking this internally. We will update you soon.

**Comment by Nivedipa-MSFT** [comment]
@PuspanjaliMuduli - Could you please confirm is your issue resolved or are you still facing this issue?

**Comment by PuspanjaliMuduli** [comment]
Hi @Nivedipa-MSFT , FYI Still we are facing the SSO Issue.

**Comment by Nivedipa-MSFT** [comment]
@PuspanjaliMuduli - Have you updated the Teams version and check?
