### ISSUE TITLE
[Feature Request] Increase message size limit of 28KB

### ISSUE THREAD

**Issue by johnkm516** [MicrosoftDocs/msteams-docs#6659]
This has been an ongoing issue for a very long time, and still has not been addressed.
The first mentions of this issue date way back to 2017, and the most recently tracked issue on this is here, dating back to 2020 : 
https://github.com/microsoft/BotFramework-Services/issues/228

28KB message limit is ridiculously low for the intended capabilities of MS Teams, when messages now include images, and cards of all varieties sent by bots. This limit severely impacts chatbots / Power Virtual Agents / Power Automate, where any attempt to send an even mildly complex adaptive card will hit the size limit and return an error. Not to mention, carousel cards become useless for a lot of use cases because the size of each adaptive card in a carousel card must be shared within the 28KB limit. 

At the very least, attachments must be treated differently than plaintext messages rather than imposing this 28KB limit globally. 

There already exists a feedback portal ticket here : 
https://feedbackportal.microsoft.com/feedback/idea/731d5aa0-272e-ec11-b6e6-00224827b493

as well as several dozens of duplicates over the years relating to message size limits. 

Is there any plan at all for increasing this limit or making any exceptions for this limit for attachments?

**Comment by Meghana-MSFT** [comment]
We are looking into this issue, we will get back to you.

**Comment by cschear** [comment]
Would love to see this increased as well. Really limits the type of data we can send to teams as it is.

**Comment by Meghana-MSFT** [comment]
The limit of 28 KB is still there but there is a change in the way size is being calculated. The size limit is checked after the adaptive card is processed. It is different now as it's applied after content of the message is transformed into internal message model. It now allows base64 images there as those would be deployed to AMS and URL would be used instead. 

We will keep you posted if the size limit is increased in the future.

**Comment by johnkm516** [comment]
@Meghana-MSFT 

Thank you for the response. 
While the base64 images being uploaded and used as a URL is a great step, my issue was more on the size limit for the adaptive card JSON itself. Please consider increasing the size limit for attachments; as cards are different from normal text messages I believe they can be separated from this limit similar to how copy and pasting images work on MS Teams currently.

**Comment by Meghana-MSFT** [comment]
We will share the feedback with the engineering team. As this request already exists in the feedback portal, Microsoft will always focus on customer’s feedback and experience. Some new features would be added to the services based on customer's feedback in the future. 
We will keep you posted if the size limit is increased in the future.

**Comment by Meghana-MSFT** [comment]
We are closing this issue, please feel free to reopen if you need any help. Thank you.
