### ISSUE TITLE
how about i don't want to return any message from the outgoing webhook

### ISSUE THREAD

**Issue by quantrpeter** [MicrosoftDocs/msteams-docs#666]
Hello
   how about i don't want to return any message from the outgoing webhook? what json i should return then?

**Comment by Wajeed-msft** [comment]
@quantrpeter - Could you please help to understand in which scenario you wouldn't want to return a message?

**Comment by quantrpeter** [comment]
i have a webhock which written in php. Everytime it is called, i need to return a json like below. The problem is: it is a message. If i don't want to return any message to teams, what json should be return?

{ "type": "message", "text": "The message is successfully sent." }

If i make it like, it doesn't work:

{ "type": "message", "text": "" }

thanks

**Comment by Gousia-MSFT** [comment]
@quantrpeter It is mandatory to send a message from the outgoing webhook. You cannot have an empty Text message.
