### ISSUE TITLE
RSS Feed URL invalid

### ISSUE THREAD

**Issue by Alesia2022** [MicrosoftDocs/msteams-docs#6666]
[Enter feedback here]

Hi the URL is invalid. Could you please let us know the right URL

![image](https://user-images.githubusercontent.com/95370599/184130641-57c6a5d1-b2c2-425b-a59b-ff9bd098bb95.png)
![invalidrssfeed](https://user-images.githubusercontent.com/95370599/184130742-77f8b6d2-725e-4e25-9a26-07883dca4b2f.jpg)
https://docs.microsoft.com/en-us/microsoftteams/platform/whats-new#to-configure-rss-feed
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ffc338ca-2f9a-9f79-bc7c-07bbd7534c78
* Version Independent ID: 0c40a2b1-4b71-5ec9-82b5-371dadddf2cc
* Content: [What is new and updated for developers in Teams - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/whats-new#to-configure-rss-feed)
* Content Source: [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/whats-new.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Prasad-MSFT** [comment]
@Alesia2022 - We tried to repro the issue as mentioned and the RSS feed got configured successfully without any error.
![image](https://user-images.githubusercontent.com/62237649/184133580-5bf7cdef-00bc-41de-85bf-1c7259e525ec.png)
![image](https://user-images.githubusercontent.com/62237649/184133631-7ce88f8f-6dae-4e51-a229-0e3daf8cdc30.png)

**Comment by Alesia2022** [comment]
![error143419](https://user-images.githubusercontent.com/95370599/184134344-3b7dc094-78b8-4a73-92f1-abda360c3ffb.jpg)
thanks for your quick answer, when i validate, i have this error

**Comment by Alesia2022** [comment]
what should i do?

**Comment by Alesia2022** [comment]
both devices web and desktop

**Comment by Prasad-MSFT** [comment]
@Alesia2022 - Could you please try to update MS Teams version and check if it helps?

**Comment by Alesia2022** [comment]
Hi it works now! thank you :)

**Comment by Prasad-MSFT** [comment]
@Alesia2022 - Glad to hear that your issue is resolved.
We are closing this issue for now. Please feel free to reopen if required.
