### ISSUE TITLE
Issue importing teams custom app

### ISSUE THREAD

**Issue by paulcloudmsg** [MicrosoftDocs/msteams-docs#6668]
Hello,

We're having issues importing an app on Teams. If we export the zip and immediately re-import, it works (and validates). If we export the zip, unzip it on a Mac or Windows computer, then re-zip and re-import, it doesn't work. One guy has been able to at least do that by unzipping/zipping with WinZip.

We are trying to add "applicationPermissions":["User.Read", "profile", "openid", "email"] for a conversational AI bot.

Paul

**Comment by Nivedipa-MSFT** [comment]
@paulcloudmsg - Could you please share what error you are getting after re-import?

**Comment by paulcloudmsg** [comment]
<img width="575" alt="image" src="https://user-images.githubusercontent.com/111093248/184418932-febe8e92-80d5-4b52-8778-404f617a64f9.png">

**Comment by paulcloudmsg** [comment]
This is just after unzipping, zipping, and re-importing.

**Comment by Nivedipa-MSFT** [comment]
@paulcloudmsg - Could you please share from where you are uploading the app in Teams like via sideloading, from developer portal or Teams admin center?

**Comment by Nivedipa-MSFT** [comment]
@paulcloudmsg - Have you checked this?

**Comment by Nivedipa-MSFT** [comment]
@paulcloudmsg - Could you please confirm is your issue resolved or are you still facing this issue?

**Comment by paulcloudmsg** [comment]
Yes, sorry. We were zipping the folder that contained the manifest and
images instead of selecting those three files and zipping. So the files
were buried in a folder and the dev portal was not expecting that.

Thanks.

**Comment by Nivedipa-MSFT** [comment]
@paulcloudmsg - We are closing this issue for now. Please feel free to reopen if required.
