### ISSUE TITLE
Add example with manifest schema v1.13 using authorization section

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#6673]
Include example of v1.13 similar to this:
![image](https://user-images.githubusercontent.com/31851992/184296786-18024e47-c43b-4870-9ead-fbae9ebc512e.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e0acfd2-0965-65f4-2200-ca06424a3976
* Version Independent ID: fd7f72fe-5dba-369a-c436-6140d232ad44
* Content: [Receive all channel messages with RSC - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/channel-messages-with-rsc)
* Content Source: [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md)
* Service: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **lajanuar**

**Comment by Nivedipa-MSFT** [comment]
@Wajeed-msft - Do we need to add the example for v1.13 in [this](https://docs.microsoft.com/en-us/microsoftteams/platform/graph-api/rsc/resource-specific-consent#manifest-changes-for-resource-specific-consent) document.
![image](https://user-images.githubusercontent.com/92150070/184306812-dee0018e-2e96-43fb-96c2-6ff32f411288.png)

**Comment by Nivedipa-MSFT** [comment]
@Wajeed-msft - Given screenshot is different from the Content document.
Could you please share in which document the example needs to be added?
