### ISSUE TITLE
Link manifest property names to their respective section

### ISSUE THREAD

**Issue by ashishguptaiitb** [MicrosoftDocs/msteams-docs#6678]
A few property names are listed at https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema#configurableproperties 
Link each of these names to the specific anchor/section of the help article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f94a488-d636-92b3-21eb-c88744c8f272
* Version Independent ID: 7b3413f4-9ade-accf-5cb2-83fead11a32a
* Content: [Manifest schema reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema#configurableproperties)
* Content Source: [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/resources/schema/manifest-schema.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Prasad-MSFT** [comment]
We are checking this. We will redirect to appropriate team to update the documentation.

**Comment by Prasad-MSFT** [comment]
Hi @surbhigupta12 - It would be better if we link each property to specific section for better understanding of user as below:

Section to be updated:
https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema#configurableproperties

You can define any of the following properties:

[name](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema#name): The app's display name.
[shortDescription](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema#description): The app's short description.
[longDescription](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema#description): The app's long description.
[smallImageUrl](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema#icons): The app's outline icon.
[largeImageUrl](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema#icons): The app's color icon.
[accentColor](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema#accentcolor): The color to use and a background for your outline icons.
[developerUrl](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema#developer): The HTTPS URL of the developer's website.
[privacyUrl](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema#developer): The HTTPS URL of the developer's privacy policy.
[termsOfUseUrl](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema#developer): The HTTPS URL of the developer's terms of use.
