### ISSUE TITLE
getChatMembers() not working

### ISSUE THREAD

**Issue by simiczhang** [MicrosoftDocs/msteams-docs#668]
I am trying to get chat members , I happen to notice this private undocumented method "getChatMembers()", but the callback never get called, I understand this is a private method but it would be better if it could be working, any suggestion?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f629e5c0-0ebe-7beb-8c10-a26fda0b74b2
* Version Independent ID: a1e928cd-ddf1-d134-70f9-34cc236b38db
* Content: [@microsoft/teams-js package - Teams](https://docs.microsoft.com/en-us/javascript/api/%40microsoft/teams-js/?view=msteams-client-js-latest)
* Content Source: [nodejs/docs-ref-autogen/@microsoft/teams-js/index.yml](https://github.com/OfficeDev/msteams-client-docs-ref-typescript/blob/live/nodejs/docs-ref-autogen/@microsoft/teams-js/index.yml)
* Product: **msteams**
* GitHub Login: @charlesprakash
* Microsoft Alias: **o365devx**

**Comment by Gousia-MSFT** [comment]
@simiczhang _getChatMembers_ is not yet available for 3P apps. We are working on it.

**Comment by simiczhang** [comment]
Ok, thanks for update. Any brief date when this API would be available for 3P apps? It is very important for some app to know the members in chat so as to provide some additional functions .

**Comment by billbliss** [comment]
When we do this, we will do it via Microsoft Graph APIs. These APIs do exist in preview but they require elevated permissions (`Chat.Read.All`). What we also need is a more granular permission model and we have no timeframe for that. We have a similar problem for all the Graph APIs that require `Group.Read.All`/`Group.ReadWrite.All` and that is a higher priority.

**Comment by simiczhang** [comment]
Ok, just wonder which preview Graph API would be used to get chat members, I only find list chat messages and get chat info but no Graph chat related API is for chat members.

**Comment by Wajeed-msft** [comment]
@simiczhang - Here is link to [Graph APIs to fetch chat members](https://docs.microsoft.com/en-us/graph/api/conversationmember-list?view=graph-rest-beta).

**Comment by simiczhang** [comment]
Thanks, it really helps.. interesting thing is I remembered I have tried this API some days ago but got unknown error,   it could be working now..

**Comment by simiczhang** [comment]
@Wajeed-msft  any idea when "/beta/chats/{chatId}/members" would become public API (instead of preview API) ?

**Comment by Wajeed-msft** [comment]
Currently, we do not have a timeline to share for chats APIs publicly.
