### ISSUE TITLE
Looks like "side panel" is not supported in the browser version of Teams during a meeting?

### ISSUE THREAD

**Issue by JohanKlijn** [MicrosoftDocs/msteams-docs#6683]
Looks like "side panel" is not supported in the browser version of Teams during during a meeting? I can open my custom made side panel in the Deskotp and Mobile version of Teams, but it look's like there is no option to open a side panel (app) from the browser version during a meeting.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62ce7ca6-3ea8-ccca-5c59-92a638303aea
* Version Independent ID: d9a2d747-41cc-add6-f281-4210e888654e
* Content: [Enable and configure your apps for Teams meetings - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings)
* Content Source: [msteams-platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **surbhigupta**

**Comment by Meghana-MSFT** [comment]
We are looking into this, we will get back to you.

**Comment by Meghana-MSFT** [comment]
@JohanKlijn - Yes, currently side panel is not supported in web client. To achieve your requirements, we recommend you give your feedback in [Microsoft Teams feedback portal](https://feedbackportal.microsoft.com/feedback/forum/ad198462-1c1c-ec11-b6e7-0022481f8472).
 Microsoft will always focus on customer’s feedback and experience. Some new features would be added to the services based on customers' feedback in the future, and your good ideas will be very helpful for them to improve the service.

**Comment by Meghana-MSFT** [comment]
We are closing this issue, please feel free to reopen if you face any issue again. Thank you.
