### ISSUE TITLE
Popup window is not resizing after client reissuing the query after sign-in

### ISSUE THREAD

**Issue by simiczhang** [MicrosoftDocs/msteams-docs#669]
As "Complete the sign-in flow" section said "The client now can reissue the original user query", but I notice after client reissuing the user query the window would still take the size of the sign-in window which is with 150px height , but ignore the height value in query JSON, this makes the UI looks strange .. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88ff3777-49c4-8cdc-089e-8612a8774ffb
* Version Independent ID: 0d927000-0b55-2129-cbbb-6630c1ec481e
* Content: [Search with messaging extensions - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/messaging-extensions/search-extensions)
* Content Source: [msteams-platform/concepts/messaging-extensions/search-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/messaging-extensions/search-extensions.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Gousia-MSFT** [comment]
@simiczhang Could you please share some screenshots of this issue?

**Comment by simiczhang** [comment]
This recorded video shows what this issue looks like. https://github.com/simiczhang/test/blob/master/size-issue.mov

**Comment by simiczhang** [comment]
@Gousia-MSFT

**Comment by Gousia-MSFT** [comment]
@simiczhang This is a bug and we are looking into this.

**Comment by simiczhang** [comment]
@simiczhang  thanks, one question, I notice MSFT teams update frequently , could I expect the fix to this simple bug could be applied very soon like next week?

**Comment by simiczhang** [comment]
@Gousia-MSFT

**Comment by Gousia-MSFT** [comment]
@simiczhang We have raised a bug for this. But we don't have an ETA to share.

**Comment by Gousia-MSFT** [comment]
This is fixed now. Please re-open if you still face any issues.
