### ISSUE TITLE
MPC developer account doc needs a better title

### ISSUE THREAD

**Issue by ashishguptaiitb** [MicrosoftDocs/msteams-docs#6703]
The article talks about not just creating a new account but also FAQs for managing account + getting support + the new requirement for Apple IDs. 

Also, for app acquisition on mobile, the second H2 is important and should surface somewhere more prominently.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06aa6b37-0f57-a6a0-5150-fdcb302161f7
* Version Independent ID: 088b47fa-e27c-6d4c-733d-359b9dae39c0
* Content: [Create your Partner Center developer account - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/create-partner-center-dev-account#update-apple-app-store-connect-team-id-on-partner-center)
* Content Source: [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-partner-center-dev-account.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-partner-center-dev-account.md)
* Service: **msteams**
* GitHub Login: @heath-hamilton
* Microsoft Alias: **surbhigupta**

**Comment by Keshav-MSFT** [comment]
Hi @ashishguptaiitb could you please provide more details what exactly you want update here

**Comment by ashishguptaiitb** [comment]
Hi @v-ajiths , would you know if this issue this addressed?

**Comment by v-ajiths** [comment]
> Hi @v-ajiths , would you know if this issue this addressed?

Hi Ashish, I've got a suggestion for this issue. I've created a draft and shared it with you. I need your confirmation or suggestions on the draft.

**Comment by surbhigupta12** [comment]
This issue is resolved. Discussed with Rajarshi, moving the Apple ID info to another page. The title for the [Create your Partner Center developer account - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/create-partner-center-dev-account#update-apple-app-store-connect-team-id-on-partner-center) is correct.
