### ISSUE TITLE
regression in people picker: SelectPeople setSelected argument max limit validation failed

### ISSUE THREAD

**Issue by matthiasdilger** [MicrosoftDocs/msteams-docs#6705]
When opening a people picker (using Teams JS v2.2.0) with a setSelected array of more than 5 users, Teams returns an error with code 4000 and debug message (in web console): "SelectPeople setSelected argument max limit validation failed"

This limit seems to be part of Teams itself, it is not caught in the JS lib.

To reproduce, call 
```
people.selectPeople({title: 'some title', openOrgWideSearchInChatOrChannel:true}).then((people) => {...});
```
and select 10 people from your org, which works fine. Then open it again and pass the previously selected users in setSelected:
```
people.selectPeople({title: 'Some title',openOrgWideSearchInChatOrChannel:true,setSelected:['id1','id2',...]}).then((people) => {...});
```

The above error occurs. The limit for setSelected seems to be 5.

Please consider removing this limit. If it's a performance issue, please consider loading the list of users in batches after the people picker has been opened.

Edit: Tested with Teams version 1.5.00.21551 on MacOS
Edit #2: The same error occurs when using Teams JS v1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2bafb046-4848-f113-8ea4-6ae1865c26fd
* Version Independent ID: bfae5321-cfaf-591e-d5bd-292d9f206462
* Content: [Integrate People Picker - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/people-picker-capability?tabs=Samplemobileapp%2Cteamsjs-v2#selectpeople-api)
* Content Source: [msteams-platform/concepts/device-capabilities/people-picker-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/device-capabilities/people-picker-capability.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **surbhigupta**

**Comment by Meghana-MSFT** [comment]
We are looking into this, we will get back to you.

**Comment by matthiasdilger** [comment]
Thanks @Meghana-MSFT I believe this is a regression, I remember it was previously possible to select more than 5 users at a time. Removing this limit altogether would be best. I have a use case where 50 selected users would be needed.

**Comment by Meghana-MSFT** [comment]
@matthiasdilger - We are also seeing the error code 4000 when more than 5 users are selected at a time for People picker with default selected member option in https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/tab-people-picker/csharp. We will check internally on the limit and get back to you. Thanks.

**Comment by Meghana-MSFT** [comment]
We have raised a bug for the same, we will keep you posted on the updates.

**Comment by matthiasdilger** [comment]
Hi @Meghana-MSFT is there any update on this? It would be great if this could get fixed. Thanks.

**Comment by Meghana-MSFT** [comment]
@matthiasdilger - The new limit 50 is rolled out. The fix is GA across all clients.

**Comment by matthiasdilger** [comment]
@Meghana-MSFT Thanks, it seems my test platform (Teams on Mac Os Intel) is a bit behind, it works on other platforms. Closing.
