### ISSUE TITLE
Permission Management [RSC VS AAD]

### ISSUE THREAD

**Issue by osheenkhare** [MicrosoftDocs/msteams-docs#6709]
[Enter feedback here]

Regarding permission management for AAD based App registration vs Teams Specific RSC, it would be good to have the explanation of what should be added to manifest, what should not be added to manifest.

What all can be controlled from where. The current documentation is scattered all over the page. It would be helpful if the context can be provided upfront in the following way

<img width="1349" alt="image" src="https://user-images.githubusercontent.com/97466440/185360803-6678a028-5ceb-496f-9a50-31ee4d2aa1e2.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11c68c28-b6d6-ef7e-f8f9-ebebe487378b
* Version Independent ID: c5985867-3795-4280-ef0d-1d66ee30da6e
* Content: [Enable resource-specific consent in Teams - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/graph-api/rsc/resource-specific-consent)
* Content Source: [msteams-platform/graph-api/rsc/resource-specific-consent.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/graph-api/rsc/resource-specific-consent.md)
* Service: **msteams**
* GitHub Login: @AkJo
* Microsoft Alias: **lajanuar**

**Comment by sayali-MSFT** [comment]
@osheenkhare - Thanks for reporting your issue.
We will investigation this issue and get back to you.

**Comment by sayali-MSFT** [comment]
@surbhigupta12 - Could you please help us to update the document?
