### ISSUE TITLE
Teams App AAD Dependencies Getting Created

### ISSUE THREAD

**Issue by osheengithub** [MicrosoftDocs/msteams-docs#6710]
[Enter feedback here]

Using Teams Toolkit to create an app/bot will provision following backend AAD apps are created, it would be helpful if this can be notified to devs.

<img width="1423" alt="image" src="https://user-images.githubusercontent.com/47814799/185366468-02082243-d1d8-45d5-9a90-51a9c3a043f4.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63519845-323f-be8f-ce15-d7f39e46b5a7
* Version Independent ID: 70952f91-56e9-ff08-59f6-e237d4aaeca9
* Content: [Add authentication to your Teams bot - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/authentication/add-authentication?tabs=dotnet%2Cdotnet-sample)
* Content Source: [msteams-platform/bots/how-to/authentication/add-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/bots/how-to/authentication/add-authentication.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Prasad-MSFT** [comment]
@osheengithub - Could you please provide more details on your issue? Please provide repro steps so that we can check from our end. Thanks!

**Comment by osheenkhare** [comment]
Following this doc https://docs.microsoft.com/en-us/microsoftteams/platform/toolkit/create-new-teams-app-for-visual-studio to create a basic command bot creates 2 App registration in AAD, it would be helpful if this is highlighted as part of Documentation

**Comment by Prasad-MSFT** [comment]
Hi @surbhigupta12 - Could you please help here to update the doc?

**Comment by v-habibaumme** [comment]
Ajith started testing this, but he doesn't have resource group. He's in the process of getting the resource group and meanwhile assigned this to another writer.
