### ISSUE TITLE
Different Places Teams App Permissions are managed 

### ISSUE THREAD

**Issue by osheengithub** [MicrosoftDocs/msteams-docs#6711]
[Enter feedback here]

Depending on the feature, teams app permission can be managed at several different places, it will be good to highlight it upfront before deep dive into how to manage permissions 

<img width="1354" alt="image" src="https://user-images.githubusercontent.com/47814799/185367156-45aff37d-a689-4c95-bf48-d8e2bd56d754.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11c68c28-b6d6-ef7e-f8f9-ebebe487378b
* Version Independent ID: c5985867-3795-4280-ef0d-1d66ee30da6e
* Content: [Enable resource-specific consent in Teams - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/graph-api/rsc/resource-specific-consent)
* Content Source: [msteams-platform/graph-api/rsc/resource-specific-consent.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/graph-api/rsc/resource-specific-consent.md)
* Service: **msteams**
* GitHub Login: @AkJo
* Microsoft Alias: **lajanuar**

**Comment by Prasad-MSFT** [comment]
@osheengithub - Could you please share the specific doc link where you want the content to updated and share the details what exactly needs to be updated?

**Comment by osheenkhare** [comment]
Hi there is no existing docs for this but it should be under App Development/ Management

**Comment by v-ajiths** [comment]
I had a discussion with Osheen.
Meeting highlights: 
We need to add the app permissions as a separate section and include app permissions such as RSC, AAD, and Connectors for O365 and let the developers know that they can manage the app permissions and how to manage them.

I need to go through the developer portals and collect inputs to include them in the doc.

**Comment by v-ajiths** [comment]
I had a discussion with Osheen.
Meeting highlights: 
We need to add the app permissions as a separate section and include app permissions such as RSC, AAD, and Connectors for O365 and let the developers know that they can manage the app permissions and how to manage them.
