### ISSUE TITLE
Where to Register BOT and Microsoft recommended approach

### ISSUE THREAD

**Issue by osheengithub** [MicrosoftDocs/msteams-docs#6712]
[Enter feedback here]

A bot can be registered at 3 different places today, it would be good to have it as a separate page for bot registrations, explaining the possible methods and differences, also the Microsoft Recommended approach for prod. ready bots (Azure AD registrations preferred over bot / developer portal bots)

<img width="1428" alt="image" src="https://user-images.githubusercontent.com/47814799/185367941-8b6c255b-3f2e-4ab6-b62b-f524e8ea4a6a.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11c68c28-b6d6-ef7e-f8f9-ebebe487378b
* Version Independent ID: c5985867-3795-4280-ef0d-1d66ee30da6e
* Content: [Enable resource-specific consent in Teams - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/graph-api/rsc/resource-specific-consent)
* Content Source: [msteams-platform/graph-api/rsc/resource-specific-consent.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/graph-api/rsc/resource-specific-consent.md)
* Service: **msteams**
* GitHub Login: @AkJo
* Microsoft Alias: **lajanuar**

**Comment by Meghana-MSFT** [comment]
Thank you for the feedback and suggestions. We will check these and update the documentation wherever required.
