### ISSUE TITLE
Different Samples using different Ways for SSO

### ISSUE THREAD

**Issue by osheengithub** [MicrosoftDocs/msteams-docs#6717]
[Enter feedback here]

There are 2 different samples provided for SSO for the same .Net implementation

https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/46.teams-auth

AND

https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/bot-conversation-sso-quickstart/csharp_dotnetcore/BotConversationSsoQuickstart

The 1st sample uses TeamsSSOTokenExchangeMiddleware, which is out of the box Service to handle tokens compared to 2nd sample where a manual class TokenExchangeHelper is created to handle tokens.

Under which scenario should which implementation to be used. Also if OOB abstraction is provided, isn't the recommended way should be to use TeamsSSOTokenExchangeMiddleware

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11c68c28-b6d6-ef7e-f8f9-ebebe487378b
* Version Independent ID: c5985867-3795-4280-ef0d-1d66ee30da6e
* Content: [Enable resource-specific consent in Teams - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/graph-api/rsc/resource-specific-consent)
* Content Source: [msteams-platform/graph-api/rsc/resource-specific-consent.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/graph-api/rsc/resource-specific-consent.md)
* Service: **msteams**
* GitHub Login: @AkJo
* Microsoft Alias: **lajanuar**

**Comment by sayali-MSFT** [comment]
@osheengithub -Thanks for reporting your issue.
We will investigation this issue and get back to you.

**Comment by sayali-MSFT** [comment]
@osheengithub -Currently, We are working on it. We will be soon migrating the existing sample to use token exchange middleware.

**Comment by ChetanSharma-msft** [comment]
@osheengithub - Sorry for delay in response.
We will check the status and will share the updates with you.

**Comment by sayali-MSFT** [comment]
@osheengithub - Migration for the existing Teams sample to use token exchange middleware has been completed.

Updated sample link- https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/bot-conversation-sso-quickstart/csharp_dotnetcore

Please let us know if you have any further query on this.
