### ISSUE TITLE
iOS URI for calling within MSTeams

### ISSUE THREAD

**Issue by adamup928** [MicrosoftDocs/msteams-docs#672]
With the upcoming transition from **Skype for Business** to **MS Teams**, we're implementing functionality that allows our users to tap on a phone number within our application and have the call made through their MS Team's account.

This functionality is available in Skype for Business with the following URI format:

`ms-sfb://call?id={phoneNumberHere}`

which opens the Skype for Business app and dials the provided number.

Is there equivalent functionality for the MS Teams iOS app? Currently, calling `msteams://` opens the Teams app but the parameter format doesn't seem to be documented anywhere.

Thanks!

**Comment by billbliss** [comment]
The tel: and sip: URIs work. For example tel:+14258828080 calls Microsoft corporate headquarters.

**Comment by Wajeed-msft** [comment]
We are tracking this feature request internally. Closing this issue from documentation page.
