### ISSUE TITLE
is it possible the update a current team to migration mode?

### ISSUE THREAD

**Issue by shiyaojun-pactera** [MicrosoftDocs/msteams-docs#6726]
Hi,I folllowed your guide and import the message successfully.
I have a doubt that is it support to change an existing channel to migration mode.
Then import some contents into it ?
If has could you share the guide doc?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5687f17-f3c7-39be-5487-f24f2155191a
* Version Independent ID: ce77e760-90cf-e6b1-3cec-ae55ee50c33e
* Content: [Use Microsoft Graph to import external platform messages to Teams - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/graph-api/import-messages/import-external-messages-to-teams)
* Content Source: [msteams-platform/graph-api/import-messages/import-external-messages-to-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/graph-api/import-messages/import-external-messages-to-teams.md)
* Service: **msteams**
* GitHub Login: @AkJo
* Microsoft Alias: **lajanuar**

**Comment by Meghana-MSFT** [comment]
@shiyaojun-pactera - It is not possible to update an existing team/channel to migration mode. As we set them in migration mode while creating itself.

**Comment by shiyaojun-pactera** [comment]
@Meghana-MSFT  really thanks for the reply.Close the ticket.
