### ISSUE TITLE
Need for shortcut in run 

### ISSUE THREAD

**Issue by R-LIBIN** [MicrosoftDocs/msteams-docs#6728]
Hello Team , 

Kindly provide a shortcut for teams in run dialog. 

Please work    on it. 

As we see, at times start doesn't work. It becomes handy. Thank you. 

Thank you. 

Regards , 
Libin

**Comment by Prasad-MSFT** [comment]
@R-LIBIN - Could you please provide more details on your issue?

**Comment by R-LIBIN** [comment]
The aws vm install-patches failed which is the first reason and second, the
data latency too high.

**Comment by Prasad-MSFT** [comment]
We are mainly responsible for Microsoft Teams app development related issues.  
For general questions about Microsoft Teams please post your question on [Microsoft Teams Community](https://answers.microsoft.com/en-us/msteams/forum?sort=LastReplyDate&dir=Desc&tab=All&status=all&mod=&modAge=&advFil=&postedAfter=&postedBefore=&threadType=All&isFilterExpanded=false&page=1).

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.
