### ISSUE TITLE
Is it possible to enable single sign-on (SSO) for Adaptive Card tab?

### ISSUE THREAD

**Issue by moira2k** [MicrosoftDocs/msteams-docs#6729]
[Enter feedback here]
Is it possible to enable single sign-on (SSO) for Adaptive Card tab?
If available, does the SSO workflow for Adaptive Card tab follow the authentication pattern for message extensions？
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a3a4238-5916-eff7-25cf-bff2362ab246
* Version Independent ID: 12048d7d-de6a-43d8-44d5-7ab1be9972a2
* Content: [Build Adaptive Card Tabs - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/build-adaptive-card-tabs)
* Content Source: [msteams-platform/tabs/how-to/build-adaptive-card-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/tabs/how-to/build-adaptive-card-tabs.md)
* Service: **msteams**
* GitHub Login: @KirtiPereira
* Microsoft Alias: **surbhigupta**

**Comment by Nivedipa-MSFT** [comment]
@moira2k - We are investigating your query. We will update you soon.

**Comment by moira2k** [comment]
Thanks, but it is authentication for Adaptive Cards Tab. Refer the document: https://docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/add-authentication.

**Comment by Nivedipa-MSFT** [comment]
@moira2k - We are checking this internally. We will update you soon.
