### ISSUE TITLE
[Rendering] Cannot display hyperlink inside choice title with markdown syntax

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#6732]
Copied bug from: https://github.com/microsoft/AdaptiveCards/issues/7769 

**Details from original post:**
### Target Platforms

Other

### SDK Version

Bot Framework 4.12.2

### Application Name

Testing Application

### Problem Description

I used markdown syntax to display hyperlink inside choice title.
For the textbox MS teams can display but for the Input.ChoiceSet.Choices **CANNOT**.
Can display on https://adaptivecards.io/designer/ and Bot Framework Emulator but MS Teams cannot.
Please take a look in the Card JSON

### Screenshots

![image](https://user-images.githubusercontent.com/37342171/185896948-0b5bfb88-0157-4254-a734-25a57e00556c.png)

### Card JSON

```JSON
{
    "type": "AdaptiveCard",
    "body": [
        {
            "type": "Input.ChoiceSet",
            "placeholder": "Placeholder text",
            "choices": [
                {
                    "title": "ABC. [URL Title](https://www.google.com/).",
                    "value": "AAA"
                },
                {
                    "title": "XYZ. [Here's what will happen](https://www.microsoft.com/).",
                    "value": "BBB"
                }
            ],
            "id": "choiceset",
            "style": "expanded",
            "isRequired": true,
            "wrap": true,
            "errorMessage": "please choose one option at least!",
            "label": "Label text here"
        }
    ],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.3"
}
```

### Sample Code Language

C#

### Sample Code

_No response_---
#### Document Details

⚠ *Do not edit this section.It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Cards reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **surbhigupta12**

**Comment by thanhnt210793** [comment]
I'm using MS Teams version: You have Microsoft Teams Version 1.5.00.21463 (64-bit). It was last updated on 8/5/2022.

**Comment by Nivedipa-MSFT** [comment]
@thanhnt210793 - We are investigating your query. We will update you soon.

**Comment by thanhnt210793** [comment]
Yes. If it doesn't support inside choice title. I think this issue can close.

**Comment by Nivedipa-MSFT** [comment]
We are closing this issue now. Please feel free to reopen if required.
