### ISSUE TITLE
Two sections on getting context with shared channels-- duplicate, or missing context?

### ISSUE THREAD

**Issue by aosolis** [MicrosoftDocs/msteams-docs#6733]
THis page has 2 sections related to getting context from a tab in shared channels:
https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/access-teams-context?tabs=teamsjs-v2#retrieve-context-in-microsoft-teams-connect-shared-channels
and
https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/access-teams-context?tabs=teamsjs-v2#get-context-in-shared-channels

What's the difference between the two? Are they duplicates? Or is there missing context that distinguishes the two scenarios? This is confusing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8dfa1a29-bcf4-0cc5-ae3a-b185a00fd7bc
* Version Independent ID: c68181e1-151b-fc78-2671-fe9b397b702e
* Content: [Get context for your tab - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/access-teams-context?tabs=teamsjs-v2#retrieve-context-in-microsoft-teams-connect-shared-channels)
* Content Source: [msteams-platform/tabs/how-to/access-teams-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/tabs/how-to/access-teams-context.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Meghana-MSFT** [comment]
Thank you for mentioning this issue, we will check this and update the document accordingly.
