### ISSUE TITLE
Teams App/Bot takes a long time to appear in a created team (if it even appears) and then keeps removing/adding itself from the team when signing out and in

### ISSUE THREAD

**Issue by RobbertVH** [MicrosoftDocs/msteams-docs#6738]
We have issues with Microsoft Teams when using the Graph API. We are testing Teams with a Microsoft 365 Developer Program account. 

 
- When creating a Team and adding an App/Bot to it with the Graph API within the create call, sometimes the Bot isn't added to the Team, and it isn't displayed in the Apps section and therefore the App/Bot is not mentionable. 

- When waiting for ten minutes or so, sometimes the App/Bot shows up in the Team and sometimes it never shows up. 

- Signing out/in into Team sometimes helps to make the App/Bot show up. Hard refreshing and clearing the cache doesn't help to make the Bot show up in a Team. 

- After creating a new team (with an App/Bot added by the create team Graph API call) and signing out/in into Teams, the App/Bot in most cases does show up for this Team. 

- Sometimes the App/Bot gets removed from a random Team (where it was present before), when signing out and in.

**GIF showcasing the issues:**
![Animation2 (1)](https://user-images.githubusercontent.com/109528797/186145995-9f5a00f2-d257-4cdf-bc5a-e946d53c5724.gif)

The screenshots below shows that when a team is created, the Bot isn't added to the team. But after signing out and in, the bot sometimes shows up immediately.
![Screenshot 2022-08-23 120220](https://user-images.githubusercontent.com/109528797/186131064-a0b79eaf-16af-4f5f-a51d-91c9fc904074.png)
![Screenshot 2022-08-23 120241](https://user-images.githubusercontent.com/109528797/186131081-7f840dbb-1dce-42b5-abac-f912adb78fd6.png)

**Comment by Prasad-MSFT** [comment]
We are checking the issue. We will get back to you shortly.

**Comment by JordyGit** [comment]
This is the C# Graph code to create the Team and add the App:
```
GraphServiceClient graphClient; // Construct & authenticate towards your tenant here first
string teamOwner = "Fill in a user email address from the tenant (case sensitive)";

var team = new Microsoft.Graph.Team()
{
    DisplayName = teamName,
    Members = new TeamMembersCollectionPage()
    {
        new AadUserConversationMember()
        {
            Roles = new List<string>()
            {
                "owner"
            },
            AdditionalData = new Dictionary<string, object>()
            {
                { "user@odata.bind", $"https://graph.microsoft.com/v1.0/users('{teamOwner}')" }
            }
        }
    },
    AdditionalData = new Dictionary<string, object>()
    {
        { "template@odata.bind", "https://graph.microsoft.com/v1.0/teamsTemplates('standard')" }
    }
};

var createdTeamResponse = await graphClient.Teams.Request().AddResponseAsync(team);
```

**Comment by RobbertVH** [comment]
When Creating a new Team (with an App/Bot added by the create team Graph API call) and signing out/in, there seems to be a bug that causes the App/Bot to alternate between showing and not showing in the existing Teams. 
So the Teams that had the bot/app before, do not anymore after this scenario. 
Those that didn't have the bot/app, do have it after this scenario.

When only signing out/in, this alternating behaviour doesn't happen.

**Comment by JordyGit** [comment]
To provide an update, even if our App/Bot doesn't appear as installed and the users can't mention it (to talk to it), the App/Bot is still able to send a proactive message to the conversation, and **from that moment** it immediately appears in the list of Apps and the users can mention it.

**Comment by Prasad-MSFT** [comment]
Thanks for the update @JordyGit .

**Comment by JordyGit** [comment]
Any updates on this? It's still affecting our use case in a bad way. We can't release our feature this way... 
We need our app/bot being added to the Team without issues, because now the Team gets created and no app/bot appears. It's very annoying and there is no workaround or logic on how to avoid or bypass the issue.

**Comment by Prasad-MSFT** [comment]
@JordyGit - We are checking the status of the bug with engineering team. We will inform you once we have any update. Thanks!

**Comment by Prasad-MSFT** [comment]
@JordyGit - Engineering team need the following details to investigate. Could you please provide those?
1. Client request Id and timestamp of the app installation request.
2. Client request Id and timestamp of the GET app installation request which shows that app wasn't installed. 
    If the inconsistency is between Teams client and graph API, please clarify that.

**Comment by JordyGit** [comment]
The inconsistency is between Teams client and graph API.

We create a Team with the Bot added to it with this piece of code: https://github.com/MicrosoftDocs/msteams-docs/issues/6738#issuecomment-1224022747

From then the Team behaves like in these screenshots/GIF in Teams: https://github.com/MicrosoftDocs/msteams-docs/issues/6738#issue-1347683781

We didn't try the GET app installation request as we shouldn't need it, it should just be installed from our first Create Team call.

In application insights I can see a few create team & channel Graph calls that our service did for someone having the issue. I can see the next ids, but I can't be sure the issue happening in this exact call and not sure if those ids help you? Local time is Belgium UTC +1.
![image](https://user-images.githubusercontent.com/33500507/203732244-f49d357f-528d-4f27-83a9-f028e34b6d59.png)
![image](https://user-images.githubusercontent.com/33500507/203732346-f62502a9-0de9-4140-b85e-52fb0f8bce7a.png)

I can only give that piece of code, by using that you should be able to reproduce the issue: https://github.com/MicrosoftDocs/msteams-docs/issues/6738#issuecomment-1224022747

**Comment by Prasad-MSFT** [comment]
@JordyGit - We are checking the status of the bug with engineering team. We will inform you once we have any update.

**Comment by Prasad-MSFT** [comment]
Its been long and keeping in mind that multiple updates has happened for MS Teams, please let us know if you are still encountering this issue or not? Thanks!
