### ISSUE TITLE
Getting 403 forbidden error when trying to do an HttpPOST request via a message card, delivered via a Custom Connector

### ISSUE THREAD

**Issue by baluvijay** [MicrosoftDocs/msteams-docs#6739]
Hi,
So I am trying to create a custom connector for my application in Teams, so after getting a webhook url, I am able to post message cards by using PostMan.
But when I try to post a message card with an Action (here HttpPOST) , and tries to execute it on the click of the button, I am getting a message
```
   Failed to send
   Could not complete the requested action. Please try again later.
```

Which on further inspection was found that an API called Execute Action is returning a 403 forbidden error.(Screenshot attached).
![image](https://user-images.githubusercontent.com/33159016/186136949-7714db6c-ee67-4fbe-9820-a5e2df76b900.png)

The action URL is a URL in webhook.site and has been added as an Action URL in connector developer dashboard.
The same URL is also added as a valid domain in the connector manifest.json.

The action part of my message card
```
{
                    "@type": "ActionCard",
                    "name": "Add Comment",
                    "inputs": [
                        {
                            "@type": "TextInput",
                            "id": "comment",
                            "isMultiline": true,
                            "title": "Reason (optional)"
                        }
                    ],
                    "actions": [
                        {
                            "@type": "HttpPOST",
                            "name": "Submit",
                            "target": "https://webhook.site/75159a3c-666b-415f-845d-0c8d38312ff6",
                            "body": "comment={{comment.value}}"

                        }
                    ]
        }

```

Is there any other permission I have to give on my level or organisational level for this to work ?

**Comment by Nivedipa-MSFT** [comment]
@baluvijay - We will try this at our end and let you know the updates.
