### ISSUE TITLE
Responding with `type: "message"` to `task/fetch`activity result in empty task module

### ISSUE THREAD

**Issue by shubham-betterworks** [MicrosoftDocs/msteams-docs#6740]
<img width="397" alt="Screenshot 2022-08-23 at 5 10 30 PM" src="https://user-images.githubusercontent.com/80667102/186148928-9b683c18-6b58-40ab-800e-92694381b0ad.png">

Response for /invoke API with activity type "task/fetch" 
<img width="549" alt="Screenshot 2022-08-23 at 5 10 26 PM" src="https://user-images.githubusercontent.com/80667102/186148998-43ee491a-78cc-4f18-b362-7c9517192fa8.png">

https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/task-modules/task-modules-bots?tabs=nodejs

**Comment by ChetanSharma-msft** [comment]
Hello @shubham-betterworks - Hope you are preparing and returning proper Task Module response like below:
![image](https://user-images.githubusercontent.com/59052547/186186228-ef6cdf70-c972-4c64-bf78-97ccd8bb4c1c.png)


Please refer below sample code:

**Comment by shubham-betterworks** [comment]
Hi @ChetanSharma-msft, yes I'm returning a proper TaskModule response

To reproduce the issue you can just change the [return statement](https://github.com/Microsoft/botbuilder-samples/blob/423b9aab8ff55eef6a16780649272feee2ae7ff8/samples/javascript_nodejs/54.teams-task-module/bots/teamsTaskModuleBot.js#L60) in `handleTeamsTaskModuleFetch` to `return TaskModuleResponseFactory.toTaskModuleResponse('invoke message');` and try invoking the TaskModule from the bot. It will result in an empty Task Module.
<img width="659" alt="Screenshot 2022-08-24 at 10 46 29 AM" src="https://user-images.githubusercontent.com/80667102/186334828-f6f0526e-07ac-4e6b-b451-c409206b3a7c.png">

**Comment by ChetanSharma-msft** [comment]
Hello @shubham-betterworks - Task modules permit you to create modal pop-up experiences in your Teams application. 
In the pop-up, you can:

1. Run your own custom HTML or JavaScript code.
2. Show an <iframe>-based widget such as a YouTube or Microsoft Stream video.
3. Display an [Adaptive Card](https://docs.microsoft.com/en-us/adaptive-cards/).

We don't have any direct way to send just a test message.

Reference doc: 
https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/what-are-task-modules

**Comment by shubham-betterworks** [comment]
@ChetanSharma-msft just to clarify we can send `{type: "message", value: "String message"}` kind of TaskModule response to `task/submit` but not to `task/fetch` activity type?

**Comment by ChetanSharma-msft** [comment]
@shubham-betterworks - Yes correct, it is mentioned in the documentation: https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/task-modules/task-modules-bots?tabs=nodejs#the-flexibility-of-tasksubmit

**Comment by ChetanSharma-msft** [comment]
@shubham-betterworks - Please let us know if you have any other query or shall we close this issue ?
