### ISSUE TITLE
The category mapping no longer exists

### ISSUE THREAD

**Issue by prkosh** [MicrosoftDocs/msteams-docs#6742]
[Enter feedback here]
Now every category thats selected by ISV on Partner Center will be displayed as is on Teams app store. Please check with Manav on details. I would say its best to remove this table

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3df9a819-4eb0-e650-ef6b-5eeaa265c317
* Version Independent ID: ed71ed64-970d-7820-4229-c1e6896a8896
* Content: [Prepare your store submission - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist)
* Content Source: [msteams-platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist.md)
* Service: **msteams**
* GitHub Login: @heath-hamilton
* Microsoft Alias: **surbhigupta**

**Comment by Nivedipa-MSFT** [comment]
@prkosh - We will investigate this and remove the content accordingly.

**Comment by Nivedipa-MSFT** [comment]
@prkosh - Could you please share alias name for manav on github to connect with him more details?
