### ISSUE TITLE
Issue while importing an existing app to developer portal.

### ISSUE THREAD

**Issue by samthrusha123** [MicrosoftDocs/msteams-docs#6743]
Getting the below error 

**Package Loading Failure
Provided add-in package was not understood. Please, make sure that the file being submitted is a valid Office add-in package.**

![image](https://user-images.githubusercontent.com/44087954/186203991-8642e66c-9c83-4c16-b665-b34e08647191.png)

Can you guide how to import an existing app from the developer portal, like we used to do in app studio?

**Comment by ChetanSharma-msft** [comment]
Hello @samthrusha123 - Thanks for reporting the issue.
Please make sure that you have have created a zip folder that does not have any subfolder.
So, please select the manifest.json, color.png, outline.png and create a zip folder directly.

**Comment by samthrusha123** [comment]
I tried that still I'm getting same issue.

**Comment by ChetanSharma-msft** [comment]
@samthrusha123 - Can you please share your zip folder via hiding PII data, so that we can try it from our end ?
