### ISSUE TITLE
task/submit tab response type unmatching TaskModuleResponse (botbuilder)

### ISSUE THREAD

**Issue by moira2k** [MicrosoftDocs/msteams-docs#6750]
[Enter feedback here]
In the document, **Invoke task/submit** -> task/submit tab response type is not match TaskModuleResponse.
![image](https://user-images.githubusercontent.com/74166031/186340332-84ad6d70-b8d9-4601-b75c-ca5a3f50a56d.png)

In botbuilder sdk, the define:
https://github.com/microsoft/botbuilder-js/blob/c692c81df7fa3db2766388fffb688def508f8e7d/libraries/botbuilder/src/teamsActivityHandler.ts#L339

![image](https://user-images.githubusercontent.com/74166031/186342695-e3d1cb7f-8b25-419b-bd67-b7a5a9cc1375.png)

https://github.com/microsoft/botbuilder-js/blob/c692c81df7fa3db2766388fffb688def508f8e7d/libraries/botframework-schema/src/teams/index.ts#L1505
![image](https://user-images.githubusercontent.com/74166031/186340892-aa808fc0-e4c0-44ed-97e6-bc6e6a18f311.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a3a4238-5916-eff7-25cf-bff2362ab246
* Version Independent ID: 12048d7d-de6a-43d8-44d5-7ab1be9972a2
* Content: [Build Adaptive Card Tabs - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/build-adaptive-card-tabs)
* Content Source: [msteams-platform/tabs/how-to/build-adaptive-card-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/tabs/how-to/build-adaptive-card-tabs.md)
* Service: **msteams**
* GitHub Login: @KirtiPereira
* Microsoft Alias: **surbhigupta**

**Comment by ChetanSharma-msft** [comment]
@moira2k - Thanks for reporting the issue.
We will look into it and get back to you.

**Comment by sayali-MSFT** [comment]
@moira2k -Could you please elaborate your requirement and share the repro steps, so that we can try it from our end.
