### ISSUE TITLE
 agree terms & privacy

### ISSUE THREAD

**Issue by ch60234** [MicrosoftDocs/msteams-docs#676]
I want add my custom bot, but it show "By using my_bot, You agree to the Terms of use and Privacy statement."
how can I fix it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69a9e1df-9152-d396-cd87-f84ba5772bfd
* Version Independent ID: e234d4e3-21d3-9a10-49b2-78b864ef723a
* Content: [Add bots to Microsoft Teams apps - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/bots/bots-overview#feedback)
* Content Source: [msteams-platform/concepts/bots/bots-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/bots/bots-overview.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Wajeed-msft** [comment]
@ch60234 - What part of the sting you are looking to change? Could you please share some screenshots with more details?

**Comment by ch60234** [comment]
![2019-05-24_14h20_27](https://user-images.githubusercontent.com/3918300/58306749-21f86380-7e2f-11e9-98ea-084078ecbc6f.png)

like that,is my setting wrong?
I can't chat with my bot

**Comment by Wajeed-msft** [comment]
@ch60234 - After installation you should be able to see your App in personal scope.
![image](https://user-images.githubusercontent.com/31851992/58317287-16a73700-7e33-11e9-9d7a-b14f8fe6697a.png)

If you are still not able to chat with bot then could you please check if you created [Notification Only Bot](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/bots/bots-notification-only)?

**App Studio:**
![image](https://user-images.githubusercontent.com/31851992/58317853-49056400-7e34-11e9-92ee-7df4a069bcf4.png)
