### ISSUE TITLE
[iOS] Adaptive cards not rendering in Teams iOS app but show up on the desktop client.

### ISSUE THREAD

**Issue by freemangl** [MicrosoftDocs/msteams-docs#6760]
iOS Teams Version: 4.15.0 (newest)
PC:
![pic](https://user-images.githubusercontent.com/1797118/186624618-8fef1faf-6491-418b-8f41-51c7907e3540.png)

iOS:

![pic2](https://user-images.githubusercontent.com/1797118/186624895-0670ffa4-76e4-4ac7-92e8-143bb9227373.png)

**Comment by Meghana-MSFT** [comment]
@freemangl - Are you sending this card using webhook? Could you please share the adaptive card JSON? Also, could you please confirm if dark mode is turned on in iOS mobile?

**Comment by freemangl** [comment]
> @freemangl - Are you sending this card using webhook?  
Yes.

> Could you please share the adaptive card JSON?
JSON: 
```
{"themeColor":"000000","summary":"{ALERT.SUBJECT}","sections":[{"markdown":"false","activityTitle":"{ALERT.SUBJECT}","activitySubtitle":"On {HOST.NAME} [{HOST.IP}]","text":"{ALERT.MESSAGE}"}],"potentialAction":[{"@type":"OpenUri","name":"Zabbix Home","targets":[{"os":"default","uri":"{$ZABBIX.URL}"}]}]}
```

> Also, could you please confirm if dark mode is turned on in iOS mobile?

Yes, dark mode is turned on. And I tried to switch to light mode, still cannot render the card.

**Comment by Meghana-MSFT** [comment]
Thanks for the confirmation, we will check it and get back to you.

**Comment by Meghana-MSFT** [comment]
We tried sending this card through Postman and it is rendering fine on iOS. 
![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/81138249/186890001-01507e47-cd90-4ef6-b6f7-5bcd843d5e3c.png)

iOS version : 15.6.1
Teams version : 4.14.1

Could you please let us know if we are missing something here.

**Comment by freemangl** [comment]
I tried with postman, still the same:
The only difference is My Team version: 4.15.0

![图片](https://user-images.githubusercontent.com/1797118/186912901-477fd573-1882-47c3-9f74-d6bf53604eee.png)
![图片](https://user-images.githubusercontent.com/1797118/186912921-87678d74-5958-473c-9625-41a43edefc2d.png)
![图片](https://user-images.githubusercontent.com/1797118/186913020-e175cb8a-8cf9-493c-895b-6fe7af639580.png)

**Comment by Meghana-MSFT** [comment]
Could you please confirm if you are facing this issue in Android and any other iOS device as well? Its working in Android as well for us.

**Comment by freemangl** [comment]
I tried another iOS device (the model iphone 12 pro Max as mine) Still the same.

And I tried an Android, works fine:

![图片](https://user-images.githubusercontent.com/1797118/186928887-f9c53006-25ab-4f2c-95d3-c266c86c366d.png)

**Comment by Meghana-MSFT** [comment]
Could you please try updating the Teams version and iOS version and check again? It is working fine at our end.

**Comment by Meghana-MSFT** [comment]
We are checking internally we will get back to you.

@tonywang0122 - Could you please share the image again? Seems like the image is not uploaded properly.

**Comment by tonywang0122** [comment]
![C3DB3880-CFCC-4D28-9DDE-A93F9DA3B2D8](https://user-images.githubusercontent.com/63811/187485340-12fde9ad-7a6f-45cc-888c-96aad4ececc1.png)

**Comment by Meghana-MSFT** [comment]
We have raised a bug for the same, we will keep you posted on the updates. Thanks.

**Comment by jacksonngoo** [comment]
It seems like they fixed the issue in version 4.16.0.

**Comment by Meghana-MSFT** [comment]
@tonywang0122 , @freemangl - Can you please check and confirm once if it is resolved?

**Comment by adecaes** [comment]
it is resolved on 4.16, however when using a dark theme the link is not visible since it's in black color on a dark background.

**Comment by Meghana-MSFT** [comment]
@adecaes - can you please raise it as a separate issue as it is related to theme.

**Comment by binderaxel** [comment]
@Meghana-MSFT the original rendering issue is apparently back in version 4.17.0

**Comment by aelmore77** [comment]
> @Meghana-MSFT the original rendering issue is apparently back in version 4.17.0

Agreed. I am experiencing the same issues as 4.15/4.15.1 covered on this issue, and which I had duplicated on #6884

**Comment by Meghana-MSFT** [comment]
Engineering team is working on the fix. We currently do not have an ETA to share. We will keep you posted on the updates. Thanks.

**Comment by ram-govi** [comment]
I am also facing the same issue

**Comment by binderaxel** [comment]
> Engineering team is working on the fix. We currently do not have an ETA to share. We will keep you posted on the updates. Thanks.

@Meghana-MSFT the issue seems to be solved in 4.17.1 👍

**Comment by Meghana-MSFT** [comment]
@freemangl - can you please confirm if the card is rendering fine for you now?

**Comment by aelmore77** [comment]
Working in 4.17.1 for me

**Comment by Meghana-MSFT** [comment]
Yes, we are closing this issue. Please feel free to reach out to us if you face any problem.
