### ISSUE TITLE
[teams voicemail] Is there support of graph API to get Users Voice Email from teams?

### ISSUE THREAD

**Issue by raguravindran** [MicrosoftDocs/msteams-docs#6763]
**Description:**
Looking to find out if there is a support for voicemail in graph APIs

**To Reproduce**
Make sure voicemail is setup for the tenant
Login as Adele Vance, try to call Alex Wilber who should be offline, make sure you hit voicemail.
Login as Alex Wilber and check Calls module, you will notice a voicemail record. The user can plan the voice mail.

Document reference below
https://support.microsoft.com/en-us/office/check-your-voicemail-in-teams-f8d568ce-7329-4fe2-a6a2-325ec2e2b419

**Attachments**
NA

Desktop (please complete the following information):
OS: [Mac]
Browser [chrome, safari, edge]

**Comment by Prasad-MSFT** [comment]
We are checking the issue. We will respond back shortly.

**Comment by Prasad-MSFT** [comment]
@raguravindran - There doesn't seem to be any API available to get user voice email from Teams using Graph API.
To achieve your requirements, we recommend you give your feedback in [Teams Feedback Portal](https://feedbackportal.microsoft.com/feedback/forum/ad198462-1c1c-ec11-b6e7-0022481f8472).
