### ISSUE TITLE
Does Graph API take the 29:xxx ID?

### ISSUE THREAD

**Issue by aosolis** [MicrosoftDocs/msteams-docs#6767]
This example shows
<img width="611" alt="image" src="https://user-images.githubusercontent.com/767208/186768125-ad7c80e8-22c6-4f6e-af90-be028ebe0adb.png">

and says the organizer ID is 29:xxx.

But in the API doc that consumes this info, it looks like it's actually expecting the AAD ID.
Does Graph understand hte 29:xxx ID? I thought that was only for SMBA.

Please confirm or fix.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d22ab715-65ae-1f44-00a4-4f37c3a81d36
* Version Independent ID: d22ab715-65ae-1f44-00a4-4f37c3a81d36
* Content: [Obtain meeting ID and organizer ID for fetching meeting transcripts - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/graph-api/meeting-transcripts/fetch-id)
* Content Source: [msteams-platform/graph-api/meeting-transcripts/fetch-id.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/graph-api/meeting-transcripts/fetch-id.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Nivedipa-MSFT** [comment]
@aosolis - We are investigating your query. We will update you soon.

**Comment by Nivedipa-MSFT** [comment]
@aosolis - Apologies for the delay. We are checking this with engineering team. We will update you.

**Comment by Nivedipa-MSFT** [comment]
@aosolis -  Document has been updated.
![image](https://user-images.githubusercontent.com/92150070/193513655-72302833-f2f1-4ea1-b59c-dc7ee37d9e56.png)

We are closing this issue for now. Please feel free to reopen if required.
