### ISSUE TITLE
MacOS graphic artifact when switching between virtual desktops

### ISSUE THREAD

**Issue by bondsua** [MicrosoftDocs/msteams-docs#677]
There is problem with notifications. After I have got notification by Microsoft teams application on MacOS 10.4+ appear graphic issue when switching between virtual desktops
https://youtu.be/U4lqas3RZlo
After close the application this problem disappears

**Comment by Gousia-MSFT** [comment]
@bondsua Thanks for reporting this. We are looking into it.

**Comment by Gousia-MSFT** [comment]
@bondsua We have raised a bug for this and we are tracking it internally. Thanks!!
