### ISSUE TITLE
Bot not receiving all channel messages as described in the document unless it's mentioned.

### ISSUE THREAD

**Issue by Chloe959** [MicrosoftDocs/msteams-docs#6771]
I found that bot is not receiving all channel messages (unless it's explicity mentioned) despite having the ChannelMessage.Read.Group RSC permission.

Besides, according to the update of app studio, we can't have the same structure of "webApplicationInfo" in Manifest.json. The example in doc is that
image

but now, it should be like
image

The ""permissions": [ "identity", "messageTeamMembers" ]," also posts an error when uploading the manifest.json.

Based on the document, with the ChannelMessage.Read.Group RSC permission, bot is expected to receive all messages even when not mentioned.

I turn my teams to Developer Preview but it still doesn't work.

Please help with this issue. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e0acfd2-0965-65f4-2200-ca06424a3976
* Version Independent ID: fd7f72fe-5dba-369a-c436-6140d232ad44
* Content: [Receive all channel messages with RSC - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/channel-messages-with-rsc?tabs=dotnet)
* Content Source: [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md)
* Service: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **lajanuar**

**Comment by Chloe959** [comment]
webApplicationInfo" in Manifest.json in doc
![image](https://user-images.githubusercontent.com/110153200/186858148-a507bdea-d5d2-444a-ade4-1d2ab1903a48.png)

but now, it should be like
![image](https://user-images.githubusercontent.com/110153200/186858327-970197ea-116e-4326-ae6c-9d4706cd7e2e.png)

**Comment by Nivedipa-MSFT** [comment]
@Chloe959 - We are test this and update you soon.

**Comment by ChetanSharma-msft** [comment]
Hello @Chloe959 - Please make sure that you have used manifest version v1.12 or above.

**Comment by Chloe959** [comment]
Of course

{
    "$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.14/MicrosoftTeams.schema.json",
    "version": "1.0.0",
    "manifestVersion": "1.14",
    "id": "83e160c7-f00d-44e5-a2ba-392a393fe791",
    "packageName": "",
    "name": {
        "short": "ECCBot",
        "full": "ECCBot"
    },
    "developer": {
        "name": "Microsoft",
        "mpnId": "",
        "websiteUrl": "https://www.microsoft.com",
        "privacyUrl": "https://privacy.microsoft.com/en-us/privacystatement",
        "termsOfUseUrl": "https://www.microsoft.com/en-us/legal/terms-of-use"
    },
    "description": {
        "short": "Send notifications on missed chat happened in (future) SRE Teams channel.",
        "full": "It will send notifications on missed chat happened in (future) SRE Teams channel"
    },
    "icons": {
        "outline": "outline.png",
        "color": "color.png"
    },
    "accentColor": "#FFFFFF",
    "staticTabs": [
        {
            "entityId": "conversations",
            "scopes": [
                "personal"
            ]
        },
        {
            "entityId": "about",
            "scopes": [
                "personal"
            ]
        }
    ],
    "bots": [
        {
            "botId": "df4b7cdd-291e-4ef9-9867-5142b143ccda",
            "scopes": [
                "team",
                "personal",
                "groupchat"
            ],
            "isNotificationOnly": false,
            "supportsCalling": false,
            "supportsVideo": false,
            "supportsFiles": false
        }
    ],
    "permissions": [ "identity", "messageTeamMembers" ],
    "validDomains": [],
    "webApplicationInfo": {
        "id": "df4b7cdd-291e-4ef9-9867-5142b143ccda",
        "resource": "https://AnyString"
    },
    "devicePermissions": [
        "Notifications"
    ],
    "authorization": {
        "permissions": {
            "orgWide": [],
            "resourceSpecific": [
                {
                    "name": "ChannelMessage.Read.Group",
                    "type": "Application"
                }
            ]
        }
    }
}

**Comment by Nivedipa-MSFT** [comment]
@Chloe959 - Apologies for the delay response. We are checking this internally. We will update you soon.

**Comment by Chloe959** [comment]
I deleted “orgWide": [], “ locally and uploaded it, and found that it would automatically fill in the format.
This line" "permissions": [ "identity", "messageTeamMembers" ]," also couldn't be seen in the Manifest, but found in App Definition.
Also, when I try to preview in Teams, it always come out the error "The webApplicationInfo.Id is already in use by another app installed in the team." . I'm pretty sure I remove all the testing app and bot from my channel but still got this error. I'm wondering is there any other things that I miss to consider? I'm now applying the  webApplicationInfo.Id the same as my bot id. I saw your last comment filling in " "webApplicationInfo": {   "id": "220497f7-b16b-4206-ad42-e7f22dede95a","  Where is this id coming from?

**Comment by Nivedipa-MSFT** [comment]
@Chloe959 - You have to give bot-id in the "webapplicationInfo" section.
Could you please refer below sample and follow the steps and check again.
https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/bot-receive-channel-messages-withRSC/csharp
