### ISSUE TITLE
Doc Issue 1 -Use of registerForVideoFrame  method use not clearly mentioned

### ISSUE THREAD

**Issue by Prithvi-MSFT** [MicrosoftDocs/msteams-docs#6774]
The code snippet for registerForVideoFrame just gives an outline on the function structure. However, there are no steps, or any note is mentioned on how the video frames can be processed or modified. We can add an example or redirect the user to use to use custom logic.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62dc58bf-69e5-8c4c-90f2-9148ee03b30f
* Version Independent ID: 62dc58bf-69e5-8c4c-90f2-9148ee03b30f
* Content: [Video filters for meeting apps - Teams](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/video-filters-for-meeting-apps?branch=pr-en-us-6618&tabs=meeting-lobby-experience%2Capp-validator)
* Content Source: [msteams-platform/apps-in-teams-meetings/video-filters-for-meeting-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/apps-in-teams-meetings/video-filters-for-meeting-apps.md)
* Service: **msteams**
* GitHub Login: @v-ypalikila
* Microsoft Alias: **v-ypalikila**

**Comment by ChetanSharma-msft** [comment]
@surbhigupta12 - Could you please help here to update the documentation?

**Comment by v-ypalikila** [comment]
Hi @ChetanSharma-msft @Prithvi-MSFT ,

We have updated the documentation for the issue. Sharing the following screenshot of the updated docs for your reference:
![image](https://user-images.githubusercontent.com/93579821/192852156-588b63ac-3df4-4ec2-905a-dd45e47b5141.png)

Request you to confirm if we can close the git Issue.

Thanks,
Yash

**Comment by surbhigupta12** [comment]
Closing this issue as it is resolved.
