### ISSUE TITLE
Doc issue 2 - Manfiest json provied does not contain clear information.

### ISSUE THREAD

**Issue by Prithvi-MSFT** [MicrosoftDocs/msteams-docs#6775]
The manifest json provided does not contain clear defination for videoAppContentUrl and validDomains. We can add generic placeholders instead of adding microsoft url's. The url's create confusion for being the default url's to be used.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62dc58bf-69e5-8c4c-90f2-9148ee03b30f
* Version Independent ID: 62dc58bf-69e5-8c4c-90f2-9148ee03b30f
* Content: [Video filters for meeting apps - Teams](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/video-filters-for-meeting-apps?branch=pr-en-us-6618&tabs=meeting-lobby-experience%2Capp-validator)
* Content Source: [msteams-platform/apps-in-teams-meetings/video-filters-for-meeting-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/apps-in-teams-meetings/video-filters-for-meeting-apps.md)
* Service: **msteams**
* GitHub Login: @v-ypalikila
* Microsoft Alias: **v-ypalikila**

**Comment by Prasad-MSFT** [comment]
@surbhigupta12 - Could you please help here to update the documentation?

**Comment by v-ypalikila** [comment]
Hi @ChetanSharma-msft @Prithvi-MSFT ,

We have updated the manifest with additional information in the docs for the issue request. Request you to confirm if we can close the git Issue.


Sharing the following screenshot and link for your reference:

Link: https://review.learn.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/video-filters-for-meeting-apps?branch=pr-en-us-6618&tabs=meeting-lobby-experience%2Capp-validator%2Ccategory-1#update-app-manifest

Screenshot:

![image](https://user-images.githubusercontent.com/93579821/192852638-09a5cf74-1154-471e-87db-67ff4fc03561.png)

Thanks,
Yash

**Comment by Prithvi-MSFT** [comment]
@v-ypalikila  - Changes look good. We can close this issue.
