### ISSUE TITLE
Doc issue 3 - Code snippet does not contain sufficient information

### ISSUE THREAD

**Issue by Prithvi-MSFT** [MicrosoftDocs/msteams-docs#6776]
The code snippet for notifySelectedVideoEffectChanged

`notifySelectedVideoEffectChanged(effectChangeType: EffectChangeType, effectId: string | undefined)`

This code snippet does not contain information for what will be the effectChangeType and what will be the effectId. We can add note or comments which will define from where to use these values. For eg effectId will the the id for the applied effect which is also available in manifest.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62dc58bf-69e5-8c4c-90f2-9148ee03b30f
* Version Independent ID: 62dc58bf-69e5-8c4c-90f2-9148ee03b30f
* Content: [Video filters for meeting apps - Teams](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/video-filters-for-meeting-apps?branch=pr-en-us-6618&tabs=meeting-lobby-experience%2Capp-validator)
* Content Source: [msteams-platform/apps-in-teams-meetings/video-filters-for-meeting-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/apps-in-teams-meetings/video-filters-for-meeting-apps.md)
* Service: **msteams**
* GitHub Login: @v-ypalikila
* Microsoft Alias: **v-ypalikila**

**Comment by ChetanSharma-msft** [comment]
@surbhigupta12 - Could you please help here to update the documentation?

**Comment by v-ypalikila** [comment]
Hi @ChetanSharma-msft @Prithvi-MSFT ,

We have updated the manifest with additional information in the docs for the issue request. Request you to confirm if we can close the git Issue.

Sharing the following screenshot and link for your reference:

Link: https://review.learn.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/video-filters-for-meeting-apps?branch=pr-en-us-6618&tabs=meeting-lobby-experience%2Capp-validator%2Ccategory-1#video-extensibility-api-reference

Screenshot:

![image](https://user-images.githubusercontent.com/93579821/192954353-208561c3-8256-48d4-a908-f12c2bfe2dec.png)
![image](https://user-images.githubusercontent.com/93579821/192954391-cfa2f812-90a4-4454-bf5a-534b4499eff9.png)

Thanks,
Yash

**Comment by surbhigupta12** [comment]
Closing this issue as it is resolved.
