### ISSUE TITLE
Doc issue 4 - Spelling mistakes inside manifest json

### ISSUE THREAD

**Issue by Prithvi-MSFT** [MicrosoftDocs/msteams-docs#6777]
The manifest json contains spelling mistake for `getting` which is mentined as `gating`. Also the spelling for customization is given as ustomization  on last comment of json. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62dc58bf-69e5-8c4c-90f2-9148ee03b30f
* Version Independent ID: 62dc58bf-69e5-8c4c-90f2-9148ee03b30f
* Content: [Video filters for meeting apps - Teams](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/video-filters-for-meeting-apps?branch=pr-en-us-6618&tabs=meeting-lobby-experience%2Capp-validator)
* Content Source: [msteams-platform/apps-in-teams-meetings/video-filters-for-meeting-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/apps-in-teams-meetings/video-filters-for-meeting-apps.md)
* Service: **msteams**
* GitHub Login: @v-ypalikila
* Microsoft Alias: **v-ypalikila**

**Comment by Prasad-MSFT** [comment]
Thanks @Prithvi-MSFT  for reporting this. We will get it updated with help of doc team.

@surbhigupta12 - Please help here to update the documentation.
In this [section](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/video-filters-for-meeting-apps?branch=pr-en-us-6618&tabs=meeting-lobby-experience%2Capp-validator#update-app-manifest) of the doc, in Manifest example there are few spellings mistake. 
![image](https://user-images.githubusercontent.com/62237649/186881299-c1e26b3b-2e46-4f77-af9b-79c0ea12cdd3.png)

**Comment by surbhigupta12** [comment]
HI @srinidyMSFT, could you please help us get this fixed?

**Comment by v-ypalikila** [comment]
Fixed the spelling mistakes in the example manifest. Hence, closing the issue after updating the changes.

![image](https://user-images.githubusercontent.com/93579821/189331230-aaf8c95e-4faa-4cd7-a1a2-5fa54cc8047c.png)
