### ISSUE TITLE
Doc issue 5 - Code not linked in MS-Teams sample codes repo

### ISSUE THREAD

**Issue by Prithvi-MSFT** [MicrosoftDocs/msteams-docs#6778]
The sample code provided inside the document is not present in msteams-sample code repo. 
Current repo - https://github.com/microsoft/teams-videoapp-sample
Sample code repo - https://github.com/OfficeDev/Microsoft-Teams-Samples
It needs to be moved there.
Lets us know, we can help in migrating the code to sample-code repository.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62dc58bf-69e5-8c4c-90f2-9148ee03b30f
* Version Independent ID: 62dc58bf-69e5-8c4c-90f2-9148ee03b30f
* Content: [Video filters for meeting apps - Teams](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/video-filters-for-meeting-apps?branch=pr-en-us-6618&tabs=meeting-lobby-experience%2Capp-validator)
* Content Source: [msteams-platform/apps-in-teams-meetings/video-filters-for-meeting-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/apps-in-teams-meetings/video-filters-for-meeting-apps.md)
* Service: **msteams**
* GitHub Login: @v-ypalikila
* Microsoft Alias: **v-ypalikila**

**Comment by ChetanSharma-msft** [comment]
Hello @surbhigupta12 - Please help us here to update it.

**Comment by v-ypalikila** [comment]
Hi @Prithvi-MSFT @ChetanSharma-msft ,

The video filter sample information at https://github.com/microsoft/teams-videoapp-sample. 

From the chat history in GC we found that a new sample for Csharp was created at https://github.com/Prithvi-MSFT/SampleCode/tree/master/meeting-av-filters/csharp.

Can we consider this sample and add it to the docs. Also, please let us know if there are any other samples to be added to the documentation.

Kindly confirm, we will update the docs and share it with you to close the issue.

Thanks,
Yash

**Comment by Prithvi-MSFT** [comment]
Hi @v-ypalikila 

Yes We have created the sample and one more sample is in progress. However, the samples branch will change once  they are merged into main. Once the feature is public, we will merge them.

**Comment by surbhigupta12** [comment]
We've added this to the feature ADO and also have a placeholder in docs. Closing this issue.
