### ISSUE TITLE
Clarification required in proactive message article

### ISSUE THREAD

**Issue by ashishguptaiitb** [MicrosoftDocs/msteams-docs#6779]
What does "Every activity your bot receives must contain the required information." mean?
How does it help to receive or retrieve the ID as mentioned before it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ad9f167-7d29-f933-7b47-60bd744899b1
* Version Independent ID: 8097fcbd-adcc-ce49-a378-426c65af9296
* Content: [Send proactive messages - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/send-proactive-messages?tabs=dotnet)
* Content Source: [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/bots/how-to/conversations/send-proactive-messages.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **anclear**

**Comment by Meghana-MSFT** [comment]
Thank you for mentioning this, we will check this and take necessary action.

**Comment by Meghana-MSFT** [comment]
@surbhigupta12 - Can you please add the below sentence as 3rd point and remove the last point "Every activity your bot receives must contain the required information." in https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/send-proactive-messages?tabs=dotnet#get-the-user-id-team-id-or-channel-id

> Every event that bot receives, contains the required information which you can get from the bot context (TurnContext object).
