### ISSUE TITLE
cannot add incoming webhook 

### ISSUE THREAD

**Issue by amoeg100** [MicrosoftDocs/msteams-docs#6815]
I can't add the incoming webhook
I can't check the url of the webbook that has already been added.
Is it a matter of authority?

The Add button does not run for the channel you want to add
The url of the webbook that has already been added (previously) cannot be checked.

![image](https://user-images.githubusercontent.com/112532063/187584210-0f51dca5-7fcb-498a-91d8-2f2406761cb7.png)

**Comment by ChetanSharma-msft** [comment]
Hello @amoeg100 - Can you please also confirm whether you are getting any error or it's just disabled for you ?
Please share the error logs, if any ?

**Comment by ChetanSharma-msft** [comment]
Hello @amoeg100 - Please confirm whether your issue has resolved or still need any help here ?
