### ISSUE TITLE
List of possible authorized client applications only lists AAD ID for Teams

### ISSUE THREAD

**Issue by AE-MS** [MicrosoftDocs/msteams-docs#6817]
SSO is supported across more hosts than just Teams (e.g. Outlook, Office.com, etc.) but the client IDs listed on this page are only for Teams.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52cb5b2e-e1e9-1993-04a0-6925d1453f20
* Version Independent ID: 52cb5b2e-e1e9-1993-04a0-6925d1453f20
* Content: [Register your tab app with Azure AD - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/tab-sso-register-aad)
* Content Source: [msteams-platform/tabs/how-to/authentication/tab-sso-register-aad.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/tabs/how-to/authentication/tab-sso-register-aad.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Prasad-MSFT** [comment]
@AE-MS - This is addressed in this section(https://docs.microsoft.com/en-us/microsoftteams/platform/m365-apps/extend-m365-teams-personal-tab?view=msteams-client-js-latest&tabs=manifest-teams-toolkit#update-azure-ad-app-registration-for-sso) of documentation.

Do you want it to be updated [here](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/tab-sso-register-aad#to-configure-authorized-client-application) as well?

**Comment by AE-MS** [comment]
I can't think of any reason to have an incomplete list of AAD IDs listed on that page (or two have two different lists depending on what page you are looking at).

**Comment by ChetanSharma-msft** [comment]
Hello @surbhigupta12 - Can you please help us here to update the list of all possible AAD Id's in below documentation:

https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/tab-sso-register-aad#to-configure-authorized-client-application
