### ISSUE TITLE
Forbidden Error when using TeamsAppInstallation.ReadWriteSelfForUser.All to manage Teams App

### ISSUE THREAD

**Issue by alex-latham** [MicrosoftDocs/msteams-docs#6820]
I have an Azure app registration currently using the application permission `TeamsAppInstallation.ReadWriteForUser.All` to install my associated Teams app in the personal scope of a tenant's Microsoft Teams users. This is working well, but I would like to switch it out for the more conservative `TeamsAppInstallation.ReadWriteSelfForUser.All` permission.

I followed the instructions in the linked article to add the "webApplicationInfo" key to the Teams app manifest. I am using the "Application (client) ID" from the Azure app registration for the "id" key value and "https://notapplicable" for the "resource" key value [as specified here](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema#webapplicationinfo). I then uploaded the updated app to my organization's app catalog to make it available to our tenant's users and verified it is the updated version currently available in the catalog.

However, when I make an API call to manage the updated Teams app (e.g., install the Teams app for a user) with the new permission in place and admin-consented, I get the following response from Graph:
```
"error"=>
      {"code"=>"Forbidden",
       "message"=>"AAD App Id '{my Azure app's ID}' is not allowed to manage the Teams App '{my teamsApp ID}'."
       ...
```

Switching the permission back to the more broad `TeamsAppInstallation.ReadWriteForUser.All` returns management functionality back to expected. I have tried removing and re-adding the new permission, waiting overnight, and adding/consenting to the broader permission alongside the conservative permission with no luck.

I am not sure where to go from here, as the documentation only mentions the new manifest key as the change needed to make this permission work. Any clarification or insight on this matter is greatly appreciated, thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 893c2c9e-10e1-dd4e-1eb4-b4e9a46a9f8d
* Version Independent ID: 5f41c382-377c-6c9b-4932-65853675c4ad
* Content: [Use Microsoft Graph to authorize proactive bot installation and messaging in Teams - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/graph-api/proactive-bots-and-messages/graph-proactive-bots-and-messages?tabs=dotnet)
* Content Source: [msteams-platform/graph-api/proactive-bots-and-messages/graph-proactive-bots-and-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/graph-api/proactive-bots-and-messages/graph-proactive-bots-and-messages.md)
* Service: **msteams**
* GitHub Login: @AkJo
* Microsoft Alias: **lajanuar**

**Comment by sayali-MSFT** [comment]
@alex-latham - We are looking into this we will get back to you soon.

**Comment by sayali-MSFT** [comment]
@alex-latham -Looks like issue with App Id. Could you please try with another App or check the AAP Id?
Are you trying the below Graph API-
`POST https://graph.microsoft.com/v1.0/users/5b649834-7412-4cce-9e69-176e95a3XXXX/teamwork/installedApps`
Content-type: application/json

Body-
```
{
   "teamsApp@odata.bind":"https://graph.microsoft.com/v1.0/appCatalogs/teamsApps/12345678-9abc-def0-123456789a"
}
```

Permission-TeamsAppInstallation.ReadWriteSelfForUser, TeamsAppInstallation.ReadWriteForUser

**Comment by sayali-MSFT** [comment]
@alex-latham - Did you get chance to check?

**Comment by AkJo** [comment]
To use the TeamsAppInstallation.ReadWriteSelfForUser.All permission, the AzureAD app being used to invoke the Graph API must be declared in the targetted TeamsApp's manifest as well. That is how the 'self' relationship is established between a TeamsApp and an AzureAD App.
