### ISSUE TITLE
Feedback on Customizable apps

### ISSUE THREAD

**Issue by prkosh** [MicrosoftDocs/msteams-docs#6824]
[Enter feedback here]
- Please link to What a Teams admin center is ?
- Can a Image be shown here on what a Customized app look like when changed by an IT admin?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54a9aab3-9fa7-9870-ea07-fd8504e21874
* Version Independent ID: 44cad9f8-b5d8-5e2f-4615-0160b73e89f7
* Content: [Customize your Teams app - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/design/enable-app-customization)
* Content Source: [msteams-platform/concepts/design/enable-app-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/design/enable-app-customization.md)
* Service: **msteams**
* GitHub Login: @heath-hamilton
* Microsoft Alias: **surbhigupta**

**Comment by ChetanSharma-msft** [comment]
Hello @prkosh - Thanks for sharing your feedback.
We will check on it and redirect to document team accordingly.

**Comment by sayali-MSFT** [comment]
@prkosh -Here is separate documentation for Teams admin center-
https://docs.microsoft.com/en-us/microsoft-365/admin/admin-overview/admin-center-overview?view=o365-worldwide 

For[ Customized applications](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/design/enable-app-customization) link are as below as mentioned in screenshot, You will get the screenshot for customize app-
![CS](https://user-images.githubusercontent.com/93527375/189112845-d5660d28-87b6-4350-b145-84faedae1b0a.png)

Ref Document-https://docs.microsoft.com/en-us/MicrosoftTeams/customize-apps#customize-details-of-an-app
