### ISSUE TITLE
fix validation errors

### ISSUE THREAD

**Issue by paul-cheung** [MicrosoftDocs/msteams-docs#683]
i am using same exactly sample JSON from [Initiate actions with messaging extensions](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/messaging-extensions/create-extensions#complete-app-manifest-example)

And playing this feature on [teams.microsoft.com](https://teams.microsoft.com) with Developer preview checked. when i import zip file including menifest via AppStudio, error occurs like below:

![action-msg-extension-validation-error](https://user-images.githubusercontent.com/4626647/58405167-6dae4580-8099-11e9-9cf0-317cc6f3030c.png)

The docs says that 1.5 was required, but error says that it should be 1.0~1.3. so what should i do? maybe someone will recommend me that i should refer to #455 , but even kartikluke's anwser is not worked for me. Any ideas will be appreciated.

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aaa0ea75-7363-3ef5-39df-ad07c493c118
* Version Independent ID: ab9a2a6e-e2ca-828f-cd8b-bd9ff98411ab
* Content: [Initiate actions with messaging extensions - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/messaging-extensions/create-extensions)
* Content Source: [msteams-platform/concepts/messaging-extensions/create-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/messaging-extensions/create-extensions.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by paul-cheung** [comment]
i also tested it in my Desktop Teams with Developer preview checked, it says the same error message.

**Comment by clearab** [comment]
Can you try sideloading the package from outside of App Studio? Apps > Upload a custom app. I believe that should get you unblocked

**Comment by paul-cheung** [comment]
@clearab you helped. thanks. maybe we can update the docs accordingly for this issue?

**Comment by clearab** [comment]
App Studio should be updated shortly to resolve this issue.

**Comment by paul-cheung** [comment]
@clearab okay, thanks!!!

**Comment by clearab** [comment]
App Studio has been updated with a fix to this issue.
