### ISSUE TITLE
Getmeetingdetails API 

### ISSUE THREAD

**Issue by SupritiBhan** [MicrosoftDocs/msteams-docs#6830]
[Enter feedback here]

Get meeting details API is not yet supported on sch channel meetings on mobile
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 805dc242-7b5a-cc81-ee0e-6acf0078a653
* Version Independent ID: 11c0e023-2514-9639-6052-2cbbbef50663
* Content: [Meeting apps API references - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/api-references?tabs=dotnet#get-meeting-details-api)
* Content Source: [msteams-platform/apps-in-teams-meetings/API-references.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/apps-in-teams-meetings/API-references.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Prasad-MSFT** [comment]
@SupritiBhan - Could you please provide more details on your issue? What do you mean by **sch** channel?
