### ISSUE TITLE
Remove note

### ISSUE THREAD

**Issue by SupritiBhan** [MicrosoftDocs/msteams-docs#6831]
[Enter feedback here]

Currently, mobile users can't share app content to the meeting stage. They can see content shared from desktop, though.

This note should be removed now

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09c05a14-d442-bcd1-f233-1beeddfd4bb1
* Version Independent ID: eb958ded-39dc-c0ab-a7c8-2d5bf334ab16
* Content: [Designing your meeting extension - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/design/designing-apps-in-meetings)
* Content Source: [msteams-platform/apps-in-teams-meetings/design/designing-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/apps-in-teams-meetings/design/designing-apps-in-meetings.md)
* Service: **msteams**
* GitHub Login: @heath-hamilton
* Microsoft Alias: **lajanuar**

**Comment by Prasad-MSFT** [comment]
Hi @surbhigupta12 - Could you please help here to update the doc accordingly?
