### ISSUE TITLE
Teams Tab App - Configurable Taberror "We couldn't save your tab settings. Please try again."

### ISSUE THREAD

**Issue by asith-w** [MicrosoftDocs/msteams-docs#6832]
In Teams Tab app , Tab Configuration code doesn't work as expected .

 it gives below error.

> "We couldn't save your tab settings. Please try again.".

**however** if i click  Save button second time it works without issue.   

![image](https://user-images.githubusercontent.com/5784846/187942443-11ad2663-16ca-4c4f-bb4b-b644d9848a3b.png)

```js
export const TabConfiguration = () => {

    const teamsRegisterOnSaveHandler = (saveEvent) => {

        microsoftTeams.settings.setSettings({
            entityId: "aaaa",
            contentUrl: window.location.origin + "/Tabs/MainTab",//?loginHint={loginHint}&userObjectId={userObjectId}&userPrincipalName={userPrincipalName}&tenantId={tid}&locale={locale}&theme={theme}&entityId=Main",
            websiteUrl: window.location.origin + "/Tabs/MainTab",//?loginHint={loginHint}&userObjectId={userObjectId}&userPrincipalName={userPrincipalName}&tenantId={tid}&locale={locale}&theme={theme}&entityId=Main",
            suggestedDisplayName: 'bbbb' 
        });
        saveEvent.notifySuccess();
    };

    const onClick = () => {
        microsoftTeams.settings.setValidityState(true);
    };

    useEffect(() => {
        microsoftTeams.initialize();
        microsoftTeams.settings.registerOnSaveHandler(teamsRegisterOnSaveHandler);
    });

    return (<div> <label onClick={onClick}> ClickMe </label>   </div>);

}
```

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b94a38e-82f8-45a1-8ccc-b0a96edd0404
* Version Independent ID: 6e077924-9658-cdd2-50de-0f9561d6366b
* Content: [Create a configuration page - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/configuration-page?tabs=teamsjs-v2)
* Content Source: [msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by ChetanSharma-msft** [comment]
Hello @asith-w - Can you please share the error logs, so that we can investigate on your issue.
Please refer this document: https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/developer-tools

**Comment by asith-w** [comment]
@ChetanSharma-msft  it says 
`2022-09-02T07:27:03.695Z Invalid tab settings provided: url;`
![image](https://user-images.githubusercontent.com/5784846/188082791-daf5f2bd-8ad8-4dae-b1ea-5719741d935f.png)  

(  however URL is correct in my case )
