### ISSUE TITLE
Download image using contentURL in SDK Python

### ISSUE THREAD

**Issue by yashna-shravani** [MicrosoftDocs/msteams-docs#6835]
@joshamil ,

MS teams framework treat attachment object and clipboard image differently. 

- When user paste an image in MS teams chat, it does not treat it as an usual attachment. Rather it receives as an image type and stores it in MS Teams internal storage and sends the Image URL in Activity.Attachment[0].
- you need to download the image content from that URL and upload to your blob storage.
- MS Teams attachment URLs are secured by a JWT Token, so we need to pass the token from our bot to access it.

Here is a sample c# code to get the image form MS Teams URL and save it to solution file. You can add this logic in ActivityHandler method.

```
if (turnContext.Activity.Attachments != null && turnContext.Activity.Attachments.Count > 1
            && turnContext.Activity.Attachments[0].ContentType=="image/*")
        {
            var attachment = turnContext.Activity.Attachments[0];
            using (HttpClient httpClient = new HttpClient())
            {
                // MS Teams attachment URLs are secured by a JwtToken, so we need to pass the token from our bot.
                var token = await new MicrosoftAppCredentials("appId", "password").GetTokenAsync();
                httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
                var responseMessage = await httpClient.GetAsync(attachment.ContentUrl);
                var contentLenghtBytes = responseMessage.Content.Headers.ContentLength;
                // You could not use this response message to fetch the image for further processing.
                if (responseMessage.StatusCode == System.Net.HttpStatusCode.OK)
                {
                    Stream attachmentStream = await responseMessage.Content.ReadAsStreamAsync();
                    attachmentStream.Position = 0;
                    var image = System.Drawing.Image.FromStream(attachmentStream);
                    image.Save(@"ImageFromUser.png");
                    await turnContext.SendActivityAsync($"Attachment of {attachment.ContentType} type and size of {contentLenghtBytes} bytes received.");
                }
            }
        }
```

_Originally posted by @Subhasish-msft in https://github.com/MicrosoftDocs/msteams-docs/issues/1561#issuecomment-615186022_

**Comment by yashna-shravani** [comment]
Need above solution in Python. Facing similar issue

**Comment by ChetanSharma-msft** [comment]
Hello @yashna-shravani - Thanks for reporting your issue.
We will look into it and get back to you.

**Comment by yashna-shravani** [comment]
Any update here? How can I authenticate using _appID_ and _password_ to download content from _contentUrl_ using Python? @ChetanSharma-msft

**Comment by Meghana-MSFT** [comment]
If you are implementing your own authentication, then please follow this document - https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-authentication?view=azure-bot-service-4.0

If you are using Bot builder Python SDK, you need to use MicrosoftAppCredentials Class and call the get_access_token() method to fetch the token. Please refer - https://github.com/microsoft/botbuilder-python/blob/d02f0c40ccd505927c56ad6a434ccab2e6a13a0c/libraries/botframework-connector/botframework/connector/auth/microsoft_app_credentials.py#L12

Then you can pass the above token to fetch the contentUrl.

**Comment by yashna-shravani** [comment]
Thanks!

**Comment by Meghana-MSFT** [comment]
we are closing this issue, please feel free to reach out to us if you have any questions.
