### ISSUE TITLE
For isNotificationOnly bots how do we get the serviceURL?

### ISSUE THREAD

**Issue by butchmarshall** [MicrosoftDocs/msteams-docs#685]
All the docs I've read (such as [here](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-api-reference?view=azure-bot-service-4.0#base-uri) indicate that a bots serviceURL is only discovered by receiving previous conversation messages

> The serviceUrl property within the user's message indicates that the bot should send its response to the endpoint https://smba.trafficmanager.net/apis; this will be the base URI for any subsequent requests that the bot issues in the context of this conversation. If your bot will need to send a proactive message to the user, be sure to save the value of serviceUrl

If we want to make a proactive bot that only sends out notifications how do we discover the serviceUrl?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f3dfdc7-7136-2d85-be50-647a4a2eae13
* Version Independent ID: 58f44a51-ae08-3297-b409-76e393adaf43
* Content: [Notification only bots - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/bots/bots-notification-only)
* Content Source: [msteams-platform/concepts/bots/bots-notification-only.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/bots/bots-notification-only.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Wajeed-msft** [comment]
Please have a look at [Conversation Update](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/bots/bots-notifications#team-member-or-bot-addition) event which is triggered when your Bot is installed. 
Please note that this event is triggered only once for personal scope.
