### ISSUE TITLE
ngrok, error 6022, and Teams scaffolding

### ISSUE THREAD

**Issue by elthombre** [MicrosoftDocs/msteams-docs#6855]
I have been trying to run some samples. Localhost shows in the browser OK as does the default URL that ngrok provides when started on the cmd.

In VS Code, the solution starts & runs. When the URL provided is browsed, it throws the ERR_NGROK_6022 exception.

Initially, I noted an ngrok.yml discrepancy in the utils.js: join(homedir(), ".ngrok2", "ngrok.yml") vs. "C:\Users\[username]\AppData\Local/ngrok/ngrok.yml" - the latter being my ngrok location.

I then hardcoded the local path in the function and I've also updated ngrok, node, npm, etc. to latest stable versions. I continue to receive that exception.

In the dashboard, there was a 404 Not Found exception associated with GET /favicon.ico. I updated the index.html files as follows:

https://stackoverflow.com/questions/31075893/im-getting-favicon-ico-error/

https://stackoverflow.com/questions/1321878/how-to-prevent-favicon-ico-requests#

the ERR_NGROK_6022 exception persists. I have found the following:

https://stackoverflow.com/questions/71900716/im-getting-ngrok-error-6022-after-doing-everything-properly

It was my initial understanding that ngrok could not find the .yml file & associated authtoken. 

Please advise.

Thanks

**Comment by ChetanSharma-msft** [comment]
Hello @elthombre - Can you please the repro steps and sample code link if any ?
We will further investigate your issue accordingly.

**Comment by elthombre** [comment]
Try the chapter 3 source:

https://github.com/Apress/pro-microsoft-teams-dev

and when I see the following:

https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?pivots=node-java-script

it doesn't appear to reference any installation or versioning of 3rd party tools such as node, ngrok, etc. How might this affect the scaffolding created by the Yeoman generator?

Are there versioning considerations?

**Comment by elthombre** [comment]
Looking a bit further, in the top-level folder, there is .env file with configuration settings:

# NGROK configuration for development
# NGROK authentication token (leave empty for anonymous)
NGROK_AUTH=
# NGROK sub domain. ex "myapp" or (leave empty for random)
NGROK_SUBDOMAIN=
# NGROK region. (us, eu, au, ap - default is us)
NGROK_REGION=

**Comment by elthombre** [comment]
I did not create or set these.

**Comment by sayali-MSFT** [comment]
@elthombre - Please have look into this-https://docs.microsoft.com/en-us/azure/bot-service/bot-service-debug-channel-ngrok?view=azure-bot-service-4.0#run-ngrok

**Comment by elthombre** [comment]
@sayali-MSFT , and if Azure is not in play?

**Comment by elthombre** [comment]
Trying the Developer Portal, it still bounces you to Teams on the web which gives the same error that you saw: “There was a problem reaching this app”

**Comment by sayali-MSFT** [comment]
> @sayali-MSFT , and if Azure is not in play?

@elthombre -Could you please elaborate more on your requirement?

**Comment by elthombre** [comment]
https://github.com/MicrosoftDocs/msteams-docs/issues/4249

And note the above is locked for further commentary even though it is not clear if the issue is fixed. Apparently not as I am experiencing this.

Then there are the issues as described above with ngrok along with the Microsoft tutorial referenced. There was an Azure-related article cited but it isn't clear how that fits into the documentation previously listed and the URLs shown in the article are not those as offered up from within Visual Studio code.

**Comment by sayali-MSFT** [comment]
@elthombre - If you want to get the ngrok Authtoken you need to run the below command-
ngrok authtoken BDZIXnhJt2HNWLXyQ5PM_qCaBq0W2sNFcCa0rXXXX

The default location of the ngrok agent's configuration file varies based on your operating system. The easiest way to find the configuration file location is to run:

`ngrok config check`

which will validate and print the location of the configuration file.
![ngrokcmd](https://user-images.githubusercontent.com/93527375/195301724-7fb6217d-7d98-4587-897c-f668bb7df830.png)


Reference document- https://ngrok.com/docs/ngrok-agent/config

**Comment by ChetanSharma-msft** [comment]
Hello @elthombre - As per my understanding, you are following the Readme for below samples and trying to run it and getting the scaffolding error?
https://github.com/Apress/pro-microsoft-teams-dev/tree/main/Chapter%203/nodejs/firstTeamsAppTeamsGenerator

We will test it from our end and get back to you.

If you have any other specific steps, please do share.

**Comment by elthombre** [comment]
Hi @ChetanSharma-msft ,

There are more details here:

https://github.com/pnp/generator-teams/issues/335

also, working through the following and getting to Step 3:

https://learn.microsoft.com/en-us/microsoftteams/platform/sbs-gs-javascript?tabs=vscode%2Cvsc%2Cviscode&tutorial-step=3

and it fails with:

× Development certificate for localhost
   Command failed: powershell.exe -NoProfile -ExecutionPolicy unrestricted -Command "(Import-Certificate -FilePath 'C:/Users/Owner/.fx/certificate/localhost.crt' -CertStoreLocation Cert:\CurrentUser\Root)[0].Thumbprint"
Import-Certificate : Cannot find object or property. (Exception from HRESULT: 0x80092004)
At line:1 char:2
+ (Import-Certificate -FilePath 'C:/Users/Owner/.fx/certificate/localho ...
+  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Certificate], COMException
    + FullyQualifiedErrorId : System.Runtime.InteropServices.COMException,Microsoft.CertificateServices.Commands.Impor 
   tCertificateCommand


Visit https://aka.ms/teamsfx-check-prerequisites-task to learn more about 'Validate & install prerequisites' task.

[2022-11-02T14:29:35.816Z] [Error] - code:Ext.PrerequisitesValidationError, message: Validate & install prerequisites failed. Please check the output panel to see the details.

Note in the above link:

https://aka.ms/teamsfx-check-prerequisites-task

That ngrok is, yet again, referenced. However, apparently, when installed separately / globally outside of Yo Teams, it can create conflict. Issue #335 from the above link offers more details.

Meanwhile, in other Microsoft documentation, it appears that ngrok is *not* required.

I will add that the above exception is on my personal machine wherein ngrok was not installed and has other tools that are not installed (i.e. just as the tutorial suggests: VS Code, the Teams extension, etc.)

The book:

https://link.springer.com/book/10.1007/978-1-4842-6364-8

https://github.com/Apress/pro-microsoft-teams-dev

and on pg. 14 it suggests installing ngrok. If one installs ngrok, it installs globally, if you will.

Hope the above helps. 

Perhaps the cert error should be a new & separate incident? Nonetheless, there are issues with these simple samples...

Thanks

**Comment by elthombre** [comment]
@ChetanSharma-msft , I got this running on my machine that does not have ngrok. I manually imported the cert via the Control Panel management tool. I placed the cert in the 'Trusted Root Certification Authorities'.

Then the solution ran.

**Comment by sayali-MSFT** [comment]
@elthombre -We also tried the [sample ](https://learn.microsoft.com/en-us/microsoftteams/platform/sbs-gs-javascript?tabs=vscode%2Cvsc%2Cviscode&tutorial-step=3)from our end and it's working properly.
Have you check the [Prerequisites](https://learn.microsoft.com/en-us/microsoftteams/platform/sbs-gs-javascript?tabs=vscode%2Cvsc%2Cviscode&tutorial-step=1)?
If required we will update the document accordingly?

https://user-images.githubusercontent.com/93527375/199925589-b5a06e91-f29f-4b38-90b7-28a75d0d32df.mp4

**Comment by elthombre** [comment]
@sayali-MSFT  The problem was that clicking the 'Install' button failed with the message that I provided. It should be added to the documentation how to use the cert manager to install the cert manually should the automatic method fail.

**Comment by elthombre** [comment]
@sayali-MSFT - I have opened the following ticket specifically related to the cert installation:

https://github.com/MicrosoftDocs/msteams-docs/issues/7412

**Comment by sayali-MSFT** [comment]
@elthombre - Thanks for your feedback. We will look into this [issue ](https://github.com/MicrosoftDocs/msteams-docs/issues/7412) as well and resolve it quickly. Thank you for your patience.

We are closing this issue for now, Please feel free to reopen it, if required.
