### ISSUE TITLE
Unable to find Password window in Remote debugging mode 7070 when trying to login to MS Teams

### ISSUE THREAD

**Issue by PTejaswiniReddy** [MicrosoftDocs/msteams-docs#6860]
Hi Team,

We opened Teams application in a remote debugging mode and i can see all the windows of Teams application in the chrome debugger. 
Please find the screenshot.
<img width="269" alt="Screenshot 2022-09-06 at 12 23 02 PM" src="https://user-images.githubusercontent.com/84141914/188566744-4651885b-54e2-4602-8bb9-5902acd66b1d.png">

I want to automate password window to enter password.
But there is no window in order to switch to it and work on.
Can someone please help me on this.

Thanks in Advance.

**Comment by sayali-MSFT** [comment]
We are mainly responsible for Microsoft Teams app development related issues. 

For Microsoft Teams product issues/failures your tenant Admin can reach out to [Microsoft 365 Product Support](https://docs.microsoft.com/en-us/microsoft-365/admin/contact-support-for-business-products?view=o365-worldwide&tabs=online). 

For general questions about Microsoft Teams please post your question on [Microsoft Teams Community](https://answers.microsoft.com/en-us/msteams/forum).
