### ISSUE TITLE
Out of date documentation on TaskModuleTaskInfo entity

### ISSUE THREAD

**Issue by cagrimunyas** [MicrosoftDocs/msteams-docs#6864]
TaskModuleTaskInfo object doesn't have a method "ToTaskModuleResponse()" . 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 800b748d-fb81-8f4d-adc2-3ee610394346
* Version Independent ID: b1ebd031-c5cd-ffeb-d9b2-d752511900db
* Content: [Use Task Modules in Microsoft Teams bots - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/task-modules/task-modules-bots?tabs=csharp)
* Content Source: [msteams-platform/task-modules-and-cards/task-modules/task-modules-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/task-modules-and-cards/task-modules/task-modules-bots.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Wajeed-msft** [comment]
@cagrimunyas - This is part of extension method defined as part of complete sample here: https://github.com/microsoft/BotBuilder-Samples/blob/main/samples/csharp_dotnetcore/54.teams-task-module/Models/TaskModuleResponseFactory.cs#L32

We will look to update the code snippet/add note to avoid other members facing the same issue.

**Comment by sayali-MSFT** [comment]
@cagrimunyas - Could you please confirm if your issue has resolved with above suggestion or still looking for any help?
