### ISSUE TITLE
How to update adaptive cards added to conversations through messaging extensions

### ISSUE THREAD

**Issue by wictorwilen** [MicrosoftDocs/msteams-docs#687]
When an adaptive card with actionable buttons has been added to a message/conversation through a messaging extension (query). How can that card/message be updated? 

I found no support through the Microsoft Graph to update a message (PATCH?) and the bot builder (v4) `updateActivity()` does not seem to work. It gives an error of `Error: Unknown activity type` when executing the `updateActivity` in an incoming `composeExtension/onCardButtonClicked` activity

**Comment by Gousia-MSFT** [comment]
@wictorwilen Bot cannot update an adaptive card sent through Message extension because it is sent by a user and not Bot.

**Comment by clearab** [comment]
@wictorwilen The work-around for this would be to use the action-based flow with the message preview, that way the message in the channel comes from a bot, and not the user. See: https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/messaging-extensions/create-extensions#respond-with-an-adaptive-card-message-sent-from-a-bot

**Comment by el** [comment]
@clearab the link you point to is no longer valid. How can we achieve this?

**Comment by clearab** [comment]
That link redirects to the correct page. I'm not sure what you mean by invalid?

https://docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/action-commands/define-action-command#respond-with-an-adaptive-card-message-sent-from-a-bot
