### ISSUE TITLE
[iOS] MessageCard received via webhook connector fails to render on iOS app

### ISSUE THREAD

**Issue by aelmore77** [MicrosoftDocs/msteams-docs#6884]
From what I've been able to observe, this is only occurring on cards with the "title" attribute. By omitting title, the card renders fine. Windows/MacOS/Android do not appear affected.

`{
    "text":  "Peer: [IPADDRESS] [(PEERNAME)] is **[STATUS]**",
    "@context":  "https://schema.org/extensions",
    "potentialAction":  [
                            {
                                "name":  "Node Detail",
                                "@type":  "OpenUri",
                                "targets":  [
                                                {
                                                    "os":  "default",
                                                    "uri":  "[DETAILURL]"
                                                }
                                            ]
                            }
                        ],
    "summary":  "[NODENAME] - [PROTOCOL] Route Peer [STATUS]",
    "@type":  "MessageCard",
    "title":  "[NODENAME] - [PROTOCOL] Route Peer Status Change"
}`

**Comment by aelmore77** [comment]
This appears to be corrected with version 4.16.0
Thank you

**Comment by binderaxel** [comment]
pls. re-open the issue as it is apparently back with version 4.17.0 @Prasad-MSFT

**Comment by ram-govi** [comment]
I am experiencing the issue in latest version 4.17.0

**Comment by Prasad-MSFT** [comment]
@binderaxel , @ram-govi - We are checking the status of the fix release with engineering team. We will update once we have an ETA to share.

**Comment by binderaxel** [comment]
@Prasad-MSFT yes, this issue is fixed- thx a lot!

**Comment by Prasad-MSFT** [comment]
@binderaxel - Thanks for informing.
We are closing this issue. Please feel free to reopen if required.
