### ISSUE TITLE
[Doc-Enhancement] Details about incremental consent

### ISSUE THREAD

**Issue by SubbaReddi** [MicrosoftDocs/msteams-docs#6902]
Hi Team,
Documentation don't have details about handling incremental consent for tab app. It would be something like permissions should not be added to app registration in the case of incremental consent and how to handle incremental consent in tab app. 

We can check this information bits and pieces from multiple references, but adding details all together will help to understand for teams developer :
https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-permissions-and-consent#incremental-and-dynamic-user-consent

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a44ac17f-15cd-8809-e885-bcc8e48b4749
* Version Independent ID: a44ac17f-15cd-8809-e885-bcc8e48b4749
* Content: [Extend tab app with Microsoft Graph permissions - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/tab-sso-graph-api?tabs=nodejs)
* Content Source: [msteams-platform/tabs/how-to/authentication/tab-sso-graph-api.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/tabs/how-to/authentication/tab-sso-graph-api.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Nivedipa-MSFT** [comment]
@surbhigupta12 - Could you please help here to add the details in below link about incremental consent.
https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-permissions-and-consent#incremental-and-dynamic-user-consent

Content needs to be added here: https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/tab-sso-graph-api?tabs=nodejs
