### ISSUE TITLE
Status of "Late 2022" API Changes

### ISSUE THREAD

**Issue by vayusphere** [MicrosoftDocs/msteams-docs#6906]
[Enter feedback here]

> By late 2022, bots can't proactively retrieve the userPrincipalName or email properties for members of a chat or team. Bots must use the Graph APIs to retrieve the required information. The new GetConversationPagedMembers API can't return the userPrincipalName and email properties from late 2022. Bots must use Graph API with an access token to retrieve information.

1. Is there a firm date identified for this change in "late 2022"?  We are in late 2022 now.
2. Although the change note below does not specifically mention this method, we suspect that if the restriction  applies to GetConversationPagedMembers it will also apply to TeamsInfo.GetMemberAsync?
3. Is there documentation available on what exactly this method  TeamsInfo.GetMemberAsync single user API will return after the change if it will not have the UPN and Email after the change?  
4. Somewhat related to this change, Will the BotFramework still continue to transmit the Azure AD ID  (id, aadObjectID) in the incoming message JSON as described in  https://docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bot-conversations/bots-conversations#full-inbound-schema-example.   The Graph hit to retrieve User Profile (which has email address) needs either UPN or aadObjectID so at the least the aadObjectID should be made available to the bot for the subsequent Graph hit?

![image](https://user-images.githubusercontent.com/6201462/189239609-672e6e1f-ae52-4b52-9c16-ad599e18757a.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c780d605-b1b2-716f-5888-503608769b5a
* Version Independent ID: 53c724f8-d9a2-4af6-6d75-ddeaef084137
* Content: [Bot API changes for team and chat members - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/team-chat-member-api-changes)
* Content Source: [msteams-platform/resources/team-chat-member-api-changes.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/resources/team-chat-member-api-changes.md)
* Service: **msteams**
* GitHub Login: @ojasvichoudhary
* Microsoft Alias: **ojchoudh**

**Comment by sayali-MSFT** [comment]
@vayusphere - We are looking into this we will get back to you soon.

**Comment by sayali-MSFT** [comment]
@vayusphere -The removal of the UPN/user name has been delayed. We are trying to figure out a path that will have minimum impact on developers/users before removing these properties. Once we have clear guidance we will publish another update. We do not plan to remove the properties in 2022.

**Comment by vayusphere** [comment]
Thanks for the update.  Could you please also update the docs pages to remove the warning about the "late 2022" changes.

**Comment by sayali-MSFT** [comment]
@vayusphere - Currently there is no plan to remove it from the website. We do not plan to remove the properties in 2022.

**Comment by tfischer2** [comment]
If the feature is not going to be removed in late 2022, shouldn't we remove the paragraph saying the feature will be removed from the documentation?  It is confusing for people who read it and conclude the feature will be removed in late 2022, when in fact, it won't.

**Comment by sayali-MSFT** [comment]
@tfischer2 - We are checking with the internal team and update the document accordingly.

**Comment by tfischer2** [comment]
Bump for pending action.

**Comment by sayali-MSFT** [comment]
@tfischer2 -We raised the bug to update the document.

**Comment by sayali-MSFT** [comment]
PR link here https://github.com/MicrosoftDocs/msteams-docs/issues/7130

**Comment by ChetanSharma-msft** [comment]
@tfischer2 - Document has updated, please check on it once and confirm.

**Comment by vayusphere** [comment]
Has the change been rolled out as this still appears on bottom of the page

![image](https://user-images.githubusercontent.com/6201462/196096207-e8a035b9-caab-49c8-9def-2643f41485b6.png)
