### ISSUE TITLE
Missing Schema in V4 corresponding to full-inbound-schema-example

### ISSUE THREAD

**Issue by GauravES** [MicrosoftDocs/msteams-docs#6907]
[Enter feedback here]

Although this page asks to check V4.6 or later docs, this schema mentioned on this page
https://docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bot-conversations/bots-conversations#full-inbound-schema-example   can not be found on the page that is linked here for V4 (i.e  can not be located on the docs starting on on https://docs.microsoft.com/en-us/microsoftteams/platform/bots/what-are-bots   or on https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-messages?tabs=dotnet )

Can you please provide a URL to the current full-inbound-schema-example for V4.6 and later?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae6b8c5f-dbce-1020-f97d-873c19a097e5
* Version Independent ID: b7906ada-45a3-4fd7-23fa-656ed00550e3
* Content: [Send and receive messages with a bot - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bot-conversations/bots-conversations#full-inbound-schema-example)
* Content Source: [msteams-platform/resources/bot-v3/bot-conversations/bots-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/resources/bot-v3/bot-conversations/bots-conversations.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by sayali-MSFT** [comment]
@GauravES - We are looking into this we will get back to you soon.

**Comment by ChetanSharma-msft** [comment]
This is a duplicate issue.
Please track it here: https://github.com/MicrosoftDocs/msteams-docs/issues/6908
