### ISSUE TITLE
Missing Full Schema Documentation for Teams message

### ISSUE THREAD

**Issue by GauravES** [MicrosoftDocs/msteams-docs#6908]
[Enter feedback here]

The schema mentioned on this page for V3 docs, 
https://docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bot-conversations/bots-conversations#full-inbound-schema-example can not be found on the page that is linked here for V4 (i.e can not be located on the docs starting on on https://docs.microsoft.com/en-us/microsoftteams/platform/bots/what-are-bots or on this page for which feedback is being provided https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-messages?tabs=dotnet )

Can you please provide a URL to the current full-inbound-schema-example for V4.6 and later? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afbc5b84-5be5-b5c4-30c0-58782a748a03
* Version Independent ID: ef6b8aee-52e7-f5d4-7dfa-8f34a1698330
* Content: [Messages in bot conversations - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-messages?tabs=dotnet)
* Content Source: [msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/bots/how-to/conversations/conversation-messages.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **anclear**

**Comment by sayali-MSFT** [comment]
@GauravES - We are looking into this we will get back to you soon.

**Comment by sayali-MSFT** [comment]
@GauravES -Please have look into this document -https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-messages?tabs=json#receive-a-message
