### ISSUE TITLE
Cannot set packageName property in the Developer Portal without App Studio

### ISSUE THREAD

**Issue by dangneos** [MicrosoftDocs/msteams-docs#6909]
From 2022 August, According to Microsoft's policy, I can not use App studio for
creating Teams App.
Therefore, I must use [Developer Portal] -> [Apps] for creating app.
But in  [Developer Portal] -> [Apps] there has not item for setting packageName property.
reference issue: https://github.com/MicrosoftDocs/msteams-docs/issues/4661
Could you like to confirm?
![teams app develop2022-09-09 103022](https://user-images.githubusercontent.com/99714311/189254510-dea2c4d0-3253-4bb2-8aad-693aabd31435.png)

**Comment by Meghana-MSFT** [comment]
We are looking into this issue, we will get back to you.

**Comment by Meghana-MSFT** [comment]
Package name is a deprecated value. Hence the developer portal does not have UX to update that value anymore.

@surbhigupta12 - Could you please help to remove the occurrences of packageName from https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema#packagename.
