### ISSUE TITLE
Is fetchTask from URL supported/working in mobile?

### ISSUE THREAD

**Issue by butchmarshall** [MicrosoftDocs/msteams-docs#691]
I'm currently developing a [Messaging Extension](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/messaging-extensions/messaging-extensions-overview) that uses fetchTask to launch a [Task Module](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/task-modules/task-modules-overview).

Short version: mobile doesn't seem to load URL fetchTasks for me.  The [Microsoft Praise App](https://www.microsoft.com/en-us/microsoft-365/blog/2019/01/09/3-new-ways-microsoft-teams-empowers-firstline-workers-to-achieve-more/) however does seem to load a properly in mobile/web via https://kudos.teams.microsoft.com/KudosWeb/compose/badgepicker

Are mobile/desktop views something only Microsoft apps support via URL?  Or is something missing from the docs to make this happen?

URL only works in desktop (but mobile does make a request to the server!):

```
{  
   "task":{  
      "type":"continue",
      "value":{  
         "title":"Task module title here",
         "url":"[...]/api/v1/microsoft_bots/recognition/compose.html"
      }
   }
}
```
![Screenshot from 2019-05-28 17-39-04](https://user-images.githubusercontent.com/339763/58514379-cd772000-816f-11e9-8b3c-2d32d1568712.png)
![Screenshot_20190528-173842_Teams](https://user-images.githubusercontent.com/339763/58514441-f992a100-816f-11e9-8cc0-ff0af57b0930.jpg)

AdaptiveCard works in mobile/desktop:

```
{  
   "task":{  
      "type":"continue",
      "value":{  
         "title":"Submit Data",
         "width":"large",
         "height":"large",
         "card":{  
            "contentType":"application/vnd.microsoft.card.adaptive",
            "content":{  
               "body":[  
                  {  
                     "text":"Line 1",
                     "type":"TextBlock"
                  },
                  {  
                     "id":"0",
                     "isMultiline":true,
                     "maxLength":5000,
                     "placeholder":"Enter text",
                     "type":"Input.Text"
                  },
                  {  
                     "text":"Line 2",
                     "type":"TextBlock"
                  },
                  {  
                     "id":"1",
                     "isMultiline":true,
                     "maxLength":5000,
                     "placeholder":"Enter text",
                     "type":"Input.Text"
                  },
                  {  
                     "text":"Line 3",
                     "type":"TextBlock"
                  },
                  {  
                     "id":"2",
                     "isMultiline":true,
                     "maxLength":5000,
                     "placeholder":"Enter text",
                     "type":"Input.Text"
                  }
               ],
               "type":"AdaptiveCard",
               "version":"1.0",
               "$schema":"http://adaptivecards.io/schemas/adaptive-card.json"
            }
         }
      }
   }
}
```
![Screenshot from 2019-05-28 17-39-31](https://user-images.githubusercontent.com/339763/58514390-d8ca4b80-816f-11e9-9443-0f9466c4eab5.png)
![Screenshot_20190528-173719_Teams](https://user-images.githubusercontent.com/339763/58514415-ec75b200-816f-11e9-9e65-e4273e5e85d8.jpg)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86441a60-584c-73d1-d678-1c3a2c38a872
* Version Independent ID: 35ca31ef-620b-7ff4-d91c-e4aa9eacf5a1
* Content: [Overview of Microsoft Teams Task Modules - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/task-modules/task-modules-overview)
* Content Source: [msteams-platform/concepts/task-modules/task-modules-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/task-modules/task-modules-overview.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by billbliss** [comment]
It’s not quite working yet but very close to release on mobile.

**Comment by butchmarshall** [comment]
Thanks for the quick response @billbliss!

We're aiming for a Q4 2019 release.  Would I be safe in suggesting to the higher ups we go ahead with a iFrame solution knowing it will be mobile supported by then?

**Comment by butchmarshall** [comment]
Just checking back on this one - any update?
