### ISSUE TITLE
Erratic Developer Preview behavior in macOS

### ISSUE THREAD

**Issue by walker-ken** [MicrosoftDocs/msteams-docs#6923]
Turning off Developer Preview is in the macOS client — version 1.5.00.24264 running on a MacBook Air (Retina, 13-inch, 2018) with macOS 11.6.8 (20G730) installed — isn't a persistent setting; even when this setting is unchecked, the application will eventually restart itself with Developer Preview enabled. (Sometimes this application restart happens even while presenting, which is distressing to the user). 

Also, the Developer Preview setting is sometimes unavailable — Developer Preview is enabled, but there is no option in the About menu to disable it, as illustrated in the following screen shot:

<img width="453" alt="image" src="https://user-images.githubusercontent.com/56447310/189368110-d229a8e8-724b-4794-b021-688459ec26e6.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 008da4e2-979e-c396-db28-4acf57deb530
* Version Independent ID: f1413f77-5eb3-e1fd-9235-d322d6e4eb6c
* Content: [Public developer preview for Microsoft Teams - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/dev-preview/developer-preview-intro)
* Content Source: [msteams-platform/resources/dev-preview/developer-preview-intro.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/resources/dev-preview/developer-preview-intro.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Prasad-MSFT** [comment]
We are mainly responsible for Microsoft Teams app development related issues.  

For Microsoft Teams product issues/failures your tenant Admin can reach out to [Microsoft 365 Product Support](https://docs.microsoft.com/en-us/microsoft-365/admin/get-help-support?view=o365-worldwide&tabs=online).  

For general questions about Microsoft Teams please post your question on [Microsoft Teams Community](https://answers.microsoft.com/en-us/msteams/forum?sort=LastReplyDate&dir=Desc&tab=All&status=all&mod=&modAge=&advFil=&postedAfter=&postedBefore=&threadType=All&isFilterExpanded=false&page=1).

**Comment by walker-ken** [comment]
I was hoping issues with Developer Perview would be considered development-related. 

At any rate, our IT department is in transition right now, and I’m not sure who’s handling tenant admin responsibilities. Could you please pass this to product support for us? A web search will turn up many instances of users discussing this issue. 

 Thanks for your help.

**Comment by Prasad-MSFT** [comment]
Added required tag.
