### ISSUE TITLE
Webhook initially responds with "Sorry, there was a problem encountered with your request" - warm up problem?

### ISSUE THREAD

**Issue by roalexan** [MicrosoftDocs/msteams-docs#693]
I deployed a simple Python AzureFunction using an HTTP trigger, e.g.:

```import json
import azure.functions as func

def main(req: func.HttpRequest) -> func.HttpResponse:    
    data = {
        "type": "message",
        "text": "hello from server"
    }
    
    return func.HttpResponse(
        body=json.dumps(data),
        status_code=200
    )
```
Next, I created an app using an outgoing webhook for a Teams channel with the Callback URL pointing to my function endpoint. Referencing my named app, I get the expected response ("hello from server"), but not initially if it hasn't been used for a while. In this case, I get an error: "Sorry, there was a problem encountered with your request".

I'm guessing I'm hitting a function "warm up" problem. Can I increase the amount of time before the webhook times out (I think it's set to 5 seconds)? Several people say using an app service plan, as opposed to a consumption plan, would side step this issue - I'm already using an app service plan, so not quite good enough. I might try using C#, instead of Python, for the function. Any other suggestions on how to work around this?

**Comment by wictorwilen** [comment]
This 5 second timeout is how the service is designed (same thing goes for messaging extensions). There's no configuration or workaround, except building a service that ensures that you don't hit that 5 second load time and is "hot" all the time.
