### ISSUE TITLE
[Authoring] Action URL with double quotes is not opening

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#6934]
Copied bug from: https://github.com/microsoft/AdaptiveCards/issues/7780 

**Details from original post:**
### Target Application

Microsoft Teams

### Application Operating System

iOS

### Schema Version

1.3

### Problem Description

When I use logic apps to generate Actions and pass the below URL to post in MS Teams, it won't open the URL.

Example URL: `https://internaldomain.net/dashboard/share/134590h9?overrides=[{"query":"dataSources","key":"account","replacement":"accountName"}]&globalStartTime=1591552800000&globalEndTime=1592460000000&pinGlobalTimeRange=true`

### Expected Outcome

Microsoft Teams should open this URL.

### Actual Outcome

It won't do anything when I try to open it.

### Card JSON

```JSON
{
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "type": "AdaptiveCard",
    "version": "1.3",
    "body": [
        {
            "type": "TextBlock",
            "text": "Publish Adaptive Card Schema",
            "weight": "Bolder",
            "size": "Medium",
            "wrap": true
        },
        {
            "type": "ColumnSet",
            "columns": [
                {
                    "type": "Column",
                    "width": "auto",
                    "items": [
                        {
                            "type": "Image",
                            "url": "https://pbs.twimg.com/profile_images/3647943215/d7f12830b3c17a5a9e4afcc370e3a37e_400x400.jpeg",
                            "altText": "Matt Hidinger",
                            "size": "Small",
                            "style": "Person"
                        }
                    ]
                },
                {
                    "type": "Column",
                    "width": "stretch",
                    "items": [
                        {
                            "type": "TextBlock",
                            "text": "Matt Hidinger",
                            "weight": "Bolder",
                            "wrap": true
                        },
                        {
                            "type": "TextBlock",
                            "spacing": "None",
                            "text": "Created {{DATE(2017-02-14T06:08:39Z, SHORT)}}",
                            "isSubtle": true,
                            "wrap": true
                        }
                    ]
                }
            ]
        },
        {
            "type": "TextBlock",
            "text": "Now that we have defined the main rules and features of the format, we need to produce a schema and publish it to GitHub. The schema will be the starting point of our reference documentation.",
            "wrap": true
        },
        {
            "type": "FactSet",
            "facts": [
                {
                    "title": "Board:",
                    "value": "Adaptive Cards"
                },
                {
                    "title": "List:",
                    "value": "Backlog"
                },
                {
                    "title": "Assigned to:",
                    "value": "Matt Hidinger"
                },
                {
                    "title": "Due date:",
                    "value": "Not set"
                }
            ]
        }
    ],
    "actions": [
        {
            "type": "Action.OpenUrl",
            "title": "View",
            "url": "https://internaldomain.net/dashboard/share/134590h9?overrides=[{\"query\":\"dataSources\",\"key\":\"account\",\"replacement\":\"accountName\"}]&globalStartTime=1591552800000&globalEndTime=1592460000000&pinGlobalTimeRange=true"
        }
    ]
}
```

### Repro Steps

1. Send the adaptive card to Teams and click on the view button.
2. It does nothing---
#### Document Details

⚠ *Do not edit this section.It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Cards reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **surbhigupta12**

**Comment by Nivedipa-MSFT** [comment]
@rangeranger  - We will try this at our end and update you soon.

**Comment by ChetanSharma-msft** [comment]
@rangeranger - Please confirm whether your issue has resolved or need any further help?

**Comment by rangeranger** [comment]
@ChetanSharma-msft / @Nivedipa-MSFT , That is not the gist of the problem. The issue happens only when you have double quotes in the URL. Can you try with the URL in my example?

**Comment by Nivedipa-MSFT** [comment]
@rangeranger - We have tested with using the URL below.
[https://internaldomain.net/dashboard/share/134590h9?overrides=[{\"query\":\"dataSources\",\"key\":\"account\",\"replacement\":\"accountName\"}]&globalStartTime=1591552800000&globalEndTime=1592460000000&pinGlobalTimeRange=true](https://internaldomain.net/dashboard/share/134590h9?overrides=%5B%7B%5C%22query%5C%22:%5C%22dataSources%5C%22,%5C%22key%5C%22:%5C%22account%5C%22,%5C%22replacement%5C%22:%5C%22accountName%5C%22%7D%5D&globalStartTime=1591552800000&globalEndTime=1592460000000&pinGlobalTimeRange=true)

But its redirecting to the URL.
Please refer below screenshots:


![image](https://user-images.githubusercontent.com/92150070/191479106-1c06cfff-2f25-46da-94cc-8a670ff435e1.png)

![image](https://user-images.githubusercontent.com/92150070/191479419-17c723b0-9c16-48b2-8014-e5a6ea146d41.png)

On Teams desktop and web client its not opening URL.
