### ISSUE TITLE
This page is missing from Teams Toolkit ToC

### ISSUE THREAD

**Issue by MuyangAmigo** [MicrosoftDocs/msteams-docs#6936]
Somehow this page is missing from Teams Toolkit doc ToC? I couldn't find it anywhere other than directly open the link.

![image](https://user-images.githubusercontent.com/11220663/189820751-29e1a8f8-ed12-4c5c-9fa4-daec3e366add.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5555cc27-dbfc-72da-e12d-f73dec786c5d
* Version Independent ID: 5555cc27-dbfc-72da-e12d-f73dec786c5d
* Content: [Add single sign-on to your Teams apps - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/toolkit/add-single-sign-on?tabs=typescript)
* Content Source: [msteams-platform/toolkit/add-single-sign-on.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/add-single-sign-on.md)
* Service: **msteams**
* GitHub Login: @zyxiaoyuer
* Microsoft Alias: **surbhigupta**

**Comment by Meghana-MSFT** [comment]
Edit Azure AD Manifest is already added in the table of contents under Customize manifest. Can you please confirm if this is what you are looking for?

**Comment by MuyangAmigo** [comment]
@Meghana-MSFT I was referring to "Add single sign on" page, but I saw ToC is updated to include this page, so never mind and we can close.

**Comment by Meghana-MSFT** [comment]
Thank you for confirming, we are closing this issue. Please feel free to reach out to us if you face any issue.
