### ISSUE TITLE
This seems to be missing

### ISSUE THREAD

**Issue by alexlimi** [MicrosoftDocs/msteams-docs#695]
This doesn’t exist in the current Teams app. Is it an omission (i.e. it never got implemented), or was it removed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e2d2912-9c5f-e49b-449b-db537ab28c49
* Version Independent ID: 7124bc05-6651-cda8-8e97-cf8f737a07bf
* Content: [registerBeforeUnloadHandler((readyToUnload: () =&gt; void) =&gt; boolean) function - Teams](https://docs.microsoft.com/en-us/javascript/api/@microsoft/teams-js/registerbeforeunloadhandler?view=msteams-client-js-latest#feedback)
* Content Source: [nodejs/docs-ref-autogen/@microsoft/teams-js/registerBeforeUnloadHandler.yml](https://github.com/OfficeDev/msteams-client-docs-ref-typescript/blob/live/nodejs/docs-ref-autogen/@microsoft/teams-js/registerBeforeUnloadHandler.yml)
* Product: **msteams**
* GitHub Login: @charlesprakash
* Microsoft Alias: **o365devx**

**Comment by asnow003** [comment]
This method is currently experimental and in the process of being tested out to a few beta users.  This should have been marked as private so it doesn't show in the documentation.  Will make sure that is updated correctly so the documentation is not generated yet.

**Comment by clearab** [comment]
@asnow003 This method still shows in the newly generated documentation. Should this be available? https://docs.microsoft.com/en-us/javascript/api/@microsoft/teams-js/?view=msteams-client-js-latest#registerbeforeunloadhandler--readytounload--------void-----boolean-

**Comment by kafka-yu** [comment]
+1

Also hope we can use this method. We want to show notification case user is going to leave the tab.

**Comment by KirtiPereira** [comment]
Closed as per inputs received from SME.
