### ISSUE TITLE
[Doc-enhancement] Link unfurling not required Action/Search commands but manifest has limitation

### ISSUE THREAD

**Issue by SubbaReddi** [MicrosoftDocs/msteams-docs#6952]
To implement link unfurling, there is no requirement of adding Action/Search commands in manifest. But "commands" property is mandatory for messaging extension section. So, Link unfurling can't be implemented without adding messaging extension commands. Adding note in documentation will help.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59bbff2e-4b80-f980-2ade-7c7a7950801e
* Version Independent ID: e837e1fd-ec0c-2d6f-b0db-b76cb2d268a4
* Content: [Link unfurling - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?tabs=dotnet)
* Content Source: [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/messaging-extensions/how-to/link-unfurling.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **anclear**

**Comment by Nivedipa-MSFT** [comment]
@SubbaReddi - We will check this and update it accordingly.
