### ISSUE TITLE
Documentation refers to non-existent context property - userDisplayName

### ISSUE THREAD

**Issue by ydogandjiev** [MicrosoftDocs/msteams-docs#6953]
The migration table shows a non-existent context property:
<img width="893" alt="image" src="https://user-images.githubusercontent.com/3357245/189945408-08ecd7a6-9379-45a7-bc13-9cf62a13046e.png">

Please delete it. This property does not and has never existed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89e79849-bf25-dd0a-4680-c1074966051b
* Version Independent ID: fee94efc-fe9c-6460-1df8-f9bc97abf526
* Content: [Teams JavaScript client SDK - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/using-teams-client-sdk?tabs=javascript%2Cmanifest-teams-toolkit#updates-to-the-context-interface)
* Content Source: [msteams-platform/tabs/how-to/using-teams-client-sdk.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/tabs/how-to/using-teams-client-sdk.md)
* Service: **msteams**
* GitHub Login: @heath-hamilton
* Microsoft Alias: **surbhigupta**

**Comment by Meghana-MSFT** [comment]
@surbhigupta12 - Can you please remove userDisplayName entry from https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/using-teams-client-sdk?tabs=javascript%2Cmanifest-teams-toolkit#updates-to-the-context-interface
![image](https://user-images.githubusercontent.com/81138249/190209193-b64f813d-3ef4-4e69-9481-38e327299254.png)
