### ISSUE TITLE
Complete Sample App not working

### ISSUE THREAD

**Issue by hdg97** [MicrosoftDocs/msteams-docs#696]
The complete sample app at https://github.com/OfficeDev/microsoft-teams-sample-complete-csharp much of the instructions on even running the app appears very outdated.

The README is using the wrong link to create a bot, because of the migration. Following the instructions, it says: Bot registration is here (open in a new browser tab): https://dev.botframework.com/bots, but using this will not allow us to create our own message endpoint and use ngrok, thereby rendering the instructions in the README virtually useless. Instead we are supposed to use https://dev.botframework.com/bots/new, but while we use this, it will have a warning that we should be migrating to the new bot service.

The manifest file cannot be parsed with the current Teams "upload custom app". The error I get while following the instructions is as follows.

    Error: An error occurred while parsing the manifest.json file; Property 'scopes' has not been defined and the schema does not allow additional properties. Path 'composeExtensions[0].scopes', line 150, position 15. 
I am yet to be sure as to why this is occurring, and am trying to debug this problem. I don't believe I did anything to change the manifest except for following the instructions and changing the values in <<___>>.

EDIT: Remove the "scopes" parameter in composeExtensions and it will successfully upload. Guess something was updated in parsing the manifest and they removed scopes parsing.

**Comment by clearab** [comment]
Thanks for letting us know, I've submitted a PR to correct the app manifest and update the link. Yes, the /new link for creating bots is the correct link to create a bot w/o using the Azure portal. You can safely ignore that warning, it doesn't apply to Teams-only bots. You can however migrate your bot to Azure if you choose, or use the Azure portal to create it.
