### ISSUE TITLE
Can't Acquire  Access Token In Basic Authentication And Bearer Authentication 

### ISSUE THREAD

**Issue by SURYASARAVANAN** [MicrosoftDocs/msteams-docs#6964]
Integrating our api with teams notification bot using the teamsfxsdk in auth provider the token is undefined.  
Basic Authentication:
 after setting username & password in  teamsfxsdk provider and created api client but while calling api get method it return 200 status but data field with sign-in in to  your account same for bearer authentication

response data :
'\r\n\r\n\r\n<!DOCTYPE html>\r\n<html dir="ltr" class="" lang="en">\r\n<head>\r\n    <title>Sign in to your account</title>\r\n    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">\r\n    <meta http-equiv="X-UA-Compatible" content="IE=edge">\r\n    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=2.0, user-scalable=yes">\r\n    <meta http-equiv="Pragma" content="no-cache">\r\n    <meta http-equiv="Ex….path||{})}t.prefetchPltMode=o}if(n&&n.fetch&&0!==n.fetch.length){var x=e.$Debug||{},X=0,H=6e4,P=new Date(2019),k=n.maxHistory||4,C=n.maxAge||20160,D=n.ageRes||1440,L=n.delay||5e3,R=n.rfPre||!1,J=void 0!==(e._phantom||e.callPhantom),N=!1;JSON&&JSON.parse&&(n.clearCookie=function(){document.cookie=n.name+"=; expires=Thu, 01 Jan 1970 00:00:01 GMT;"},e.$Do.when("doc.load",function(){\nsetTimeout(M,L),setTimeout(S,0)}))}}(window,document,$Prefetch);\r\n\r\n;\r\n})();\r\n//]]>\r\n</script>\r\n\r\n</bo...

**Comment by sayali-MSFT** [comment]
@SURYASARAVANAN -You have acquired the necessary authorization for your application, proceed with acquiring access tokens for APIs. To get a token by using the client credentials grant, send a POST request to the /token Microsoft identity platform.
Please refer to the below sample call for client_credentials flow, where client_id is the application ID of the app registered in Azure AD and Scope is the API that will be consuming the token:

**Call**:  `POST https://login.microsoftonline.com/your_tenant.onmicrosoft.com/oauth2/v2.0/token`

**Body**: (in form-data or x-www-form-urlencoded format):


- client_id: Application ID copied earlier

- scope: profile-search (May vary based on the scopes exposed in the resource API)

- client_assertion_type: urn:ietf:params:oauth:client-assertion-type:jwt-bearer (Must be same)

- client_assertion: Read about [certificate credentials](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-certificate-credentials) to learn how to register your certificate and [Signed assertions](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-net-client-assertions#signed-assertions) for encoded assertion to be used here.

- grant_type: client_credentials (to acquire token in application context where no human interaction is needed)


Notice that there are no user credentials specified in the request. The token will be acquired in the Application/servicePrincipal context.

Reference document-https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-client-creds-grant-flow

Also  This sample demonstrates authentication in Microsoft Teams apps-https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/app-auth/nodejs

**Comment by SURYASARAVANAN** [comment]
'\r\n\r\n\r\n\r\n\r\n\r\n <title>Sign in to your account</title>\r\n \r\n \r\n \r\n \r\n <meta http-equiv="Ex….path||{})}t.prefetchPltMode=o}if(n&&n.fetch&&0!==n.fetch.length){var x=e.$Debug||{},X=0,H=6e4,P=new Date(2019),k=n.maxHistory||4,C=n.maxAge||20160,D=n.ageRes||1440,L=n.delay||5e3,R=n.rfPre||!1,J=void 0!==(e._phantom||e.callPhantom),N=!1;JSON&&JSON.parse&&(n.clearCookie=function(){document.cookie=n.name+"=; expires=Thu, 01 Jan 1970 00:00:01 GMT;"},e.$Do.when("doc.load",function(){\nsetTimeout(M,L),setTimeout(S,0)}))}}(window,document,$Prefetch);\r\n\r\n;\r\n})();\r\n//]]>\r\n</script>\r\n\r\n</bo...


i am getting this in response data but status 200

**Comment by sayali-MSFT** [comment]
@SURYASARAVANAN -Could you please share the refer document/sample so that we can investigate from our end?

**Comment by SURYASARAVANAN** [comment]
@sayali-MSFT i have find that above response sign in html page returns because our mvc .net web app contain open id authentication with cookie based so controller in that with authorize header are all returns the sign page while http call, but allow anonymous method work perfectly, sorry for the wrong info. can you help on this to solve open id authentication web app endpoints need hit from other service  using the web app client credentials with bearer token

**Comment by sayali-MSFT** [comment]
@SURYASARAVANAN -Please have look into this sample-https://learn.microsoft.com/en-us/azure/active-directory-b2c/configure-authentication-sample-web-app-with-api?tabs=visual-studio

Hope it's helpful.

**Comment by SURYASARAVANAN** [comment]
Thanks @sayali-MSFT  it helps
