### ISSUE TITLE
Powershell script for creating test-data contains typo error not referencing foreach field

### ISSUE THREAD

**Issue by ferrarirosso** [MicrosoftDocs/msteams-docs#6980]
Referencing [Add test data to your environment](https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/test-data)
In the following foreach, in the line beginning with $group..., the -Description is wrong as it does not reference the field from the foreach.
foreach ($team in $XmlDocument.Teams.Team ) {
            try {
                $group = New-Team -DisplayName $team.Name -Description $teams.description -visibility public
                Write-Host "Successfully created team: " $group.DisplayName
            }
            catch {
                Write-Host "Unable to create team: $_"
            }

Actual
$group = New-Team -DisplayName $team.Name -Description $teams.description -visibility public
Correct
$group = New-Team -DisplayName $team.Name -Description $team.description -visibility public

**Comment by Prasad-MSFT** [comment]
@ferrarirosso - Thanks for pointing out. We will redirect to documentation team to update accordingly.
Hi @surbhigupta12 - Could you please help here to update [this](https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/test-data#:~:text=Save%20the%20following%20snippet%20as%20a%20PowerShell%20script%20(.ps1)%20and%20note%20where%20you%27ve%20saved%20it.%20This%20script%20executes%20the%20steps%20to%20create%20the%20team%20and%20channel%2C%20and%20add%20members%20to%20them%3A) section of doc from 
`$group = New-Team -DisplayName $team.Name -Description $teams.description -visibility public`  to 
`$group = New-Team -DisplayName $team.Name -Description $team.description -visibility public`
