### ISSUE TITLE
How to send likert scale question types to ms teams bot 

### ISSUE THREAD

**Issue by samthrusha123** [MicrosoftDocs/msteams-docs#6998]
Like below

![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/44087954/191242686-b4e2afa4-dc1c-443b-82bf-2b16c8e1a2f2.png)

Can you provide any sample. And how can we get the answers back to the bot. (Using adaptive cards)

**Comment by Nivedipa-MSFT** [comment]
@samthrusha123 - We are investigating your query. We will update you soon.
