### ISSUE TITLE
This function is not working

### ISSUE THREAD

**Issue by simiczhang** [MicrosoftDocs/msteams-docs#701]
The callback is not called.

microsoftTeams.initialize();
    microsoftTeams.getTabInstances( function(tabInstances) {
        alert(tabInstances);
    });

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5f73e23-b669-a8c8-2a03-c96da3ac3ee6
* Version Independent ID: 31f89aec-b7d0-1f95-eea0-c04c1f7f7f1e
* Content: [getTabInstances((tabInfo: TabInformation) =&gt; void, TabInstanceParameters) function - Teams](https://docs.microsoft.com/en-us/javascript/api/@microsoft/teams-js/gettabinstances?view=msteams-client-js-latest)
* Content Source: [nodejs/docs-ref-autogen/@microsoft/teams-js/getTabInstances.yml](https://github.com/OfficeDev/msteams-client-docs-ref-typescript/blob/live/nodejs/docs-ref-autogen/@microsoft/teams-js/getTabInstances.yml)
* Product: **msteams**
* GitHub Login: @charlesprakash
* Microsoft Alias: **o365devx**

**Comment by Gousia-MSFT** [comment]
@simiczhang
1. Could you please try this in a browser and check if there are any console errors?
2. Could you please try using this code snippet and see if it helps.
```
<script src="https://unpkg.com/@microsoft/teams-js@1.4.2/dist/MicrosoftTeams.min.js"></script>
    <script>
        microsoftTeams.initialize();
        microsoftTeams.getTabInstances(function (tabInstances) {
            alert(JSON.stringify(tabInstances));
        });
    </script>
```

**Comment by simiczhang** [comment]
@Gousia-MSFT  I am using "Open DevTools" so even in native client I could confirm there is no JS error ( and I could confirm the code after the "microsoftTeams.getTabInstances" is executed so I could presume this function is executed but somehow callback never come)

**Comment by simiczhang** [comment]
More background , this is a JS inside message extension which follows instruction of https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/messaging-extensions/create-extensions#dynamic-input-using-a-web-view

**Comment by Wajeed-msft** [comment]
Could you please share your app manifest?

**Comment by simiczhang** [comment]
{
    "$schema": "https://raw.githubusercontent.com/OfficeDev/microsoft-teams-app-schema/preview/DevPreview/MicrosoftTeams.schema.json",
    "manifestVersion": "devPreview",
    "version": "1.0.5",
    "id": "3c09c020-e969-4f2c-a137-414a0fe8ad96",
    "packageName": "xx.yy.zz",
    "developer": {
        "name": "Developer",
        "websiteUrl": "https://www.xxx.com/c/en/us/products/unified-communications/xxx/index.html",
        "privacyUrl": "https://www.xxx.com/c/en/us/about/legal/privacy.html",
        "termsOfUseUrl": "https://www.xxx.com/c/en/us/products/universal-cloud-agreement.html"
    },
    "icons": {
        "color": "color.png",
        "outline": "outline.png"
    },
    "name": {
        "short": "Test App Local",
        "full": "Test App Bot (Dev)"
    },
    "description": {
        "short": "Any.",
        "full": "Any."
    },
    "accentColor": "#F9F9FA",
    "composeExtensions": [
        {
            "botId": "3c09c020-e969-4f2c-a137-414a0fe8ad96",
            "canUpdateConfiguration": false,
            "commands": [
                {
                    "id": "call",
                    "title": " ",
                    "description": "",
                    "fetchTask": true,
                    "type": "action",
                    "context": [ "message", "compose" ],
                    "parameters": [
                        {
                            "name": "id",
                            "title": "ID",
                            "description": "call address"
                        }
                    ]
                }
            ]
        }
    ],
    "permissions": [
        "identity",
        "messageTeamMembers"
    ],
    "validDomains": [
        "*.ngrok.io",
        "*.microsoftonline.com"
    ]
}

**Comment by Wajeed-msft** [comment]
@simiczhang - This function works fine even inside task module which is opened by messaging extension. Could you please confirm if getTabInstances() function is working fine in personal tab for you? Use [the code](https://github.com/MicrosoftDocs/msteams-docs/issues/701#issuecomment-500713940) shared by @Gousia-MSFT and create simple tab which just displays tab instances.

**Comment by simiczhang** [comment]
@Wajeed-msft  , it would trigger callback now but somehow it just didn't find any tabInstances , e.g. the static tab from app.

**Comment by Gousia-MSFT** [comment]
@simiczhang Do you have tabs for this app configured in any of the teams?

**Comment by simiczhang** [comment]
Yes, I have configured a tab in the manifest of this app and install this app for my team in Teams (by "upload custom app")

**Comment by Gousia-MSFT** [comment]
@simiczhang Sorry, I could not get that. Could you please confirm if you have added that [configurable tab](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/tabs/tabs-configuration)(which you have listed in the manifest) as a tab in the team by clicking on the + icon you see in the team?

![image](https://user-images.githubusercontent.com/45553518/61508927-c7801b80-aa09-11e9-846e-36aac7d63298.png)

**Comment by simiczhang** [comment]
@Gousia-MSFT  Ok, I see the gap , I didn't add the tab to team or channel, but I hope the getTabInstance would tell me the tab in the App view itself (sidebar click "myapp" would navigate me to the conversation to this app and there I would find the tab I configured in the manifest). So is there anyway to get tab instance information in App conversation ?

**Comment by Gousia-MSFT** [comment]
@simiczhang `getTabInstances `only fetches the configured tabs for your app. Once you [configure a tab](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/tabs/tabs-configuration) in team you could call it from a [static tab](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/tabs/tabs-static) or a [message extension](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/tabs/tabs-static). Can you please configure a tab in Teams and call getTabInstances from Message Extension like you said you were trying earlier and let us know if you are facing any issues.

**Comment by simiczhang** [comment]
That should be working .
