### ISSUE TITLE
[iOS] triggering action based message extension returns invalid linkToMessage in group chats

### ISSUE THREAD

**Issue by matthiasdilger** [MicrosoftDocs/msteams-docs#7012]
This is a followup to #5272

User triggers action based message extension on Teams iOS 4.16.1 in any **chat** (not channel)

![154590692-8bfabb59-9ad5-482d-ace5-da562d91daf7](https://user-images.githubusercontent.com/5625718/191447999-6cc71153-e940-49ef-acb8-12eddc9cf363.JPG)

Bot receives composeExtension/fetchTask with the following payload (using nodejs): 
```
  name: 'composeExtension/fetchTask',
  type: 'invoke'
<...>
  value: {
    commandContext: 'message',
    requestId: '346d8e50-b3bb-4cc0-9200-c011f7960d60',
    messagePayload: {
      linkToMessage: 'https://teams.microsoft.com/message/19:227e3f15fa6b42d4a711b57355b49960@thread.v2/1661405264568?context=%7B%22contextType%22:%22chat%22%7D'
```

The linkToMessage URL looks fine on first sight but opening it on web for example returns a HTTP 400. It is missing the **/l** path, the correct linkToMessage URL would be 
```
https://teams.microsoft.com/l/message/19:227e3f15fa6b42d4a711b57355b49960@thread.v2/1661405264568?context=%7B%22contextType%22:%22chat%22%7D
```

**Comment by Prasad-MSFT** [comment]
We are checking the issue.

**Comment by Prasad-MSFT** [comment]
@matthiasdilger - We are able to repro the issue and bug is raised for this. We have informed engineering team about it. We will update you once we get further info from engineering team. Thanks!

**Comment by Prasad-MSFT** [comment]
@matthiasdilger - We are checking the status of the bug with engineering team. We will inform you once we have any update. Thanks!

**Comment by Prasad-MSFT** [comment]
@matthiasdilger - The issue seems to be fixed now. We tested in iOS 16.5.1
Microsoft Teams version:
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/62237649/387bbff7-7d81-48c6-9e51-d851ee8e6d15)

Please do verify. Thanks!

**Comment by Prasad-MSFT** [comment]
@matthiasdilger - The issue seems to be fixed now. Please do verify.
Tested in iOS `16.5.1`
MS Teams version:
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/62237649/29ab333a-e2b1-4452-bf38-2445eddbeec8)

**Comment by matthiasdilger** [comment]
@Prasad-MSFT Confirming as fixed, thanks
