### ISSUE TITLE
Bot is not working with deployed service url

### ISSUE THREAD

**Issue by samthrusha123** [MicrosoftDocs/msteams-docs#7047]
Teams bot is not responding while using app service url as messaging endpoint. When I try using it with ngrok it is working fine. What might be the issue? Can't able to figure it out!!

**Comment by Meghana-MSFT** [comment]
We are looking into this, we will get back to you.

**Comment by Prasad-MSFT** [comment]
@samthrusha123 - Could you please add the domain details where your app is deployed under `validDomains `section of manifest and check if it works?

**Comment by samthrusha123** [comment]
> validDomains

Still the same after updation.

**Comment by Prasad-MSFT** [comment]
@samthrusha123 - Aren't you getting any event at your messaging endpoint? What error does it give? 
Could you please share any console error?

**Comment by samthrusha123** [comment]
> @samthrusha123 - Aren't you getting any request at your messaging endpoint? What error does it give? Could you please share any console error?
> 
> Also If you aren't using SSO, ensure that you enter a dummy string value in `resource` field of `webApplicationInfo `section of your app manifest, for example, `https://notapplicable` to avoid an error response.

We're using SSO authentication only. I think it's not even calling the app service. Only local ngrok is working. With app service we're facing this issue. Before it was working fine. From the past 2-3 weeks it's not working with app service url.

**Comment by samthrusha123** [comment]
tried that as well. Nothing worked.

**Comment by samthrusha123** [comment]
> tried that as well. Nothing worked.

@Prasad-MSFT tried that as well. Nothing worked.

**Comment by samthrusha123** [comment]
Getting this 405 error. 

![image](https://user-images.githubusercontent.com/44087954/192992078-ede69d3a-e2f6-4bc5-aef6-e2af14843cec.png)

**Comment by samthrusha123** [comment]
Getting this 405 error. 

![image](https://user-images.githubusercontent.com/44087954/192992078-ede69d3a-e2f6-4bc5-aef6-e2af14843cec.png)

**Comment by samthrusha123** [comment]
This is the call where I'm calling the bot.

![image](https://user-images.githubusercontent.com/44087954/192995506-7d7ba886-66b7-4b99-8e6a-b81aedb2a3f7.png)

**Comment by samthrusha123** [comment]
It's resolved now. some policy was blocking the request from Teams to App service.
