### ISSUE TITLE
Background image for containers/columns

### ISSUE THREAD

**Issue by 01** [MicrosoftDocs/msteams-docs#705]
Does Teams not support setting a background image for column or container? Quite confusing because the adaptivecards.io page renders it for teams

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8a3bcf2-332a-8d24-a8d1-7e3816897745
* Version Independent ID: 68fb9551-ce95-0112-2703-721a1af01f23
* Content: [Cards Reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/cards/cards-reference#adaptive-card)
* Content Source: [msteams-platform/concepts/Cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/Cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by billbliss** [comment]
Where do you see this? Just checked with the team and it doesn't appear in the schema for columns or containers, unless we are missing something.

**Comment by 01** [comment]
@billbliss you are correct. I just looked at schema its no where to be found. I was utilizing the adaptivecards.io designer which allows containers and columns to have background images while rendering for Microsoft teams without any errors. Since the schema version in the json being fed into designer.

Its a bit confusing since JSON examples ive seen state version 1.0 schema but utilize the backgroundImage for containers and columns such as this one

https://github.com/microsoft/botframework-solutions/blob/master/skills/src/csharp/calendarskill/calendarskill/Content/CalendarOverview.json
