### ISSUE TITLE
Please document deep links for SharePoint Framework tabs

### ISSUE THREAD

**Issue by BobGerman** [MicrosoftDocs/msteams-docs#706]
This is great and very helpful; SharePoint Framework appears to be a configurable tab which uses only its entity ID, leaving the subentity ID for use by the SPFx developer. Can you please verify and document that? Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a891841a-a110-d18e-25c1-fc29e7d4a5e3
* Version Independent ID: c1a11eb8-00d1-e1d2-1e9d-71d059a6478a
* Content: [Create deep links - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/deep-links#feedback)
* Content Source: [msteams-platform/concepts/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/deep-links.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by clearab** [comment]
@lokimeyburg Can you deep link to sub-entities in SharePoint as described here?
