### ISSUE TITLE
Clarify that Action.Execute is not a replacement for Action.Submit

### ISSUE THREAD

**Issue by aosolis** [MicrosoftDocs/msteams-docs#7063]
Several partners have been confused by this page, thinking that Action.Execute can replace all usages of Action.Submit, which is decidedly not the case. We need to clarify this.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 47dee5d9-bd9f-f550-8fc2-c2e3b67bba65
* Version Independent ID: 04264d26-1036-342a-e0ea-5edadebc3352
* Content: [Overview of Universal Actions for Adaptive Cards - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?tabs=mobile)
* Content Source: [msteams-platform/task-modules-and-cards/cards/Universal-actions-for-adaptive-cards/Overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/task-modules-and-cards/cards/Universal-actions-for-adaptive-cards/Overview.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by ChetanSharma-msft** [comment]
We will look into it and redirect to doc team accordingly.

**Comment by sayali-MSFT** [comment]
@surbhigupta12 - Could you please help us for update the document?
Please add the below point in the document in Universal Actions section-


- Action.Execute works across hubs including Teams and Outlook But it is not replacement of Action.Submit.
 However in few cases such as If you want some external system to do an action and the result of the action to be sent back to your conversation which use [Messaging Extension](https://learn.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/what-are-messaging-extensions?tabs=dotnet#scenarios-where-message-extensions-are-used) is not supported with Action.Execute. For [link unfurling cards](https://learn.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?tabs=dotnet) like Hero Card,Thumbnail Card, you need to call Action.Submit.


Reference Document-https://learn.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?tabs=mobile#universal-actions

**Comment by sayali-MSFT** [comment]
@aosolis - Could you please confirm if this is what we need to update in this doc? Or is there anything else you want us to add?
