### ISSUE TITLE
Msteam app schema validation.

### ISSUE THREAD

**Issue by vidya091209** [MicrosoftDocs/msteams-docs#708]
we are are are facing the issue with Manifest Validation Tool(https://manifestvalidator.azurewebsites.net/) 
we have created a app using studio in team app. which has below info. 
 "$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.4/MicrosoftTeams.schema.json",
    "manifestVersion": "1.5",
But we we are validating the manifest file using tool  https://manifestvalidator.azurewebsites.net/

 we are getting this error **Provided manifest does not have valid URL for schema.**
let me know how we can proceed.
Note: it was working with scheama version 1.4

**Comment by clearab** [comment]
Please update the URL to use v1.5 if you are using manifest version 1.5.

Alternatively (probably preferably), you can use App Studio to validate your schema by uploading it there.
