### ISSUE TITLE
Teams disappeared in application. Can find it in the web application.

### ISSUE THREAD

**Issue by wilhelmssonjens** [MicrosoftDocs/msteams-docs#7080]
One of my Teams has disappeared from the Teams app. 
It started with the Teams channel disappeared, when I look at my notifications related to the channel, I could press them but nothing happened. Now also the notifications related to the channel are gone.

I can open and see the Team in the web application of Teams. When I try to click my way through sharepoint and "Open in Teams app", I get the following:
"we can't find that channel due to connectivity issues. please try again later"

**Comment by ChetanSharma-msft** [comment]
We are mainly responsible for Microsoft Teams app development related issues.

For Microsoft Teams product issues/failures your tenant Admin can reach out to [Microsoft 365 Product Support](https://docs.microsoft.com/en-us/microsoft-365/admin/contact-support-for-business-products?view=o365-worldwide&tabs=online).

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.
