### ISSUE TITLE
Create conversation from ASP.NET Core 2 Controller

### ISSUE THREAD

**Issue by araqieldev** [MicrosoftDocs/msteams-docs#709]
It's possible to have a example to create a conversation in Teams channel ?
I'm stuck in my controller with this code example :

``` csharp
foreach (var conversationReference in _conversationReferences.Values)
{
 await ((BotAdapter)_adapter).ContinueConversationAsync(_appId, conversationReference, BotCallback, default);
}
```
But not work if nobody start a personnal conversation.
I would like my bot send message automatically to a channel.
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba8d3979-14f5-3105-ad89-ce6f98d11df1
* Version Independent ID: e53a7d1e-0e70-ca30-9809-fda7ebe5f4da
* Content: [Proactive messages - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/bots/bot-conversations/bots-conv-proactive#feedback)
* Content Source: [msteams-platform/concepts/bots/bot-conversations/bots-conv-proactive.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/bots/bot-conversations/bots-conv-proactive.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Wajeed-msft** [comment]
Could you please try sample code provided here: [C#](https://github.com/MicrosoftDocs/msteams-docs/issues/612#issuecomment-489064697) or [Node](https://github.com/MicrosoftDocs/msteams-docs/issues/612#issuecomment-488845813)?
