### ISSUE TITLE
Cannot find the menu item in VS2022 Prev 17.4.0 Prev 2.1

### ISSUE THREAD

**Issue by giobb** [MicrosoftDocs/msteams-docs#7091]
Hi. This seems to be inaccurate already. I installed the Teams Toolkit as instructed and still I don't see the menu item

<img width="350" alt="image" src="https://user-images.githubusercontent.com/15137038/192906688-257f40e4-e85d-4a01-a9d3-03f25b10a96b.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 529f4de5-77fe-1001-b2a4-2ef2b3138ab6
* Version Independent ID: 529f4de5-77fe-1001-b2a4-2ef2b3138ab6
* Content: [Debug your Teams app locally - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-local?tabs=Windows&pivots=visual-studio)
* Content Source: [msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/debug-local.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **v-amprasad**

**Comment by Prasad-MSFT** [comment]
@giobb - We checked in below version of VS2022 and the menu items are showing properly.
![image](https://user-images.githubusercontent.com/62237649/192950392-a4e1d384-89bb-4f93-bc86-884c823076b7.png)

![image](https://user-images.githubusercontent.com/62237649/192950476-040a1465-3264-4ead-a77b-cfd1528c3e5a.png)
![image](https://user-images.githubusercontent.com/62237649/192950521-8792719c-1cdd-4e17-812d-ec5960767497.png)

**Comment by giobb** [comment]
Hi @Prasad-MSFT , I might not have been clear about the issue. I'm referring to the menu time **Teams Toolkit** -> **Prepare Teams App Dependencies** which should have been there according to the documentation if I followed the steps. I don't see that in your screenshots.

**Comment by Prasad-MSFT** [comment]
@giobb - We have followed below steps and it worked:

1.Install Teams Toolkit following below doc:
    https://learn.microsoft.com/en-us/microsoftteams/platform/toolkit/install-teams-toolkit?tabs=vscode&pivots=visual-studio   
2.Follow this doc to create Teams Project/App:
  https://learn.microsoft.com/en-us/microsoftteams/platform/toolkit/create-new-project?pivots=visual-studio#create-a-new-teams-app-1
3. Now right click on the created project.
![image](https://user-images.githubusercontent.com/62237649/193305316-c55e14c5-5dd0-4d06-85d7-ef494b10782f.png)
