### ISSUE TITLE
Callback converted to promises example should use app.Context

### ISSUE THREAD

**Issue by JKirkYuan** [MicrosoftDocs/msteams-docs#7092]
For the code example

```typescript
import { app, Context } from "@microsoft/teams-js";

app.getContext().then((context: Context) => {
    /*...*/
});
```

The context from `app.getContext()` doesn't have the type `Context`. Instead it references `app.Context`. Correct example should modify to

```typescript
import { app, Context } from "@microsoft/teams-js";

app.getContext().then((context: app.Context) => {
    /*...*/
});
```

It also says the above when trying to import `Context`

<img width="548" alt="CleanShot 2022-09-28 at 16 37 10@2x" src="https://user-images.githubusercontent.com/18089817/192906852-b2f26449-2a19-467d-b217-1f2cc965cc63.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 89e79849-bf25-dd0a-4680-c1074966051b
* Version Independent ID: fee94efc-fe9c-6460-1df8-f9bc97abf526
* Content: [Teams JavaScript client SDK - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/using-teams-client-sdk?source=recommendations&tabs=javascript%2Cmanifest-teams-toolkit)
* Content Source: [msteams-platform/tabs/how-to/using-teams-client-sdk.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/tabs/how-to/using-teams-client-sdk.md)
* Service: **msteams**
* GitHub Login: @heath-hamilton
* Microsoft Alias: **surbhigupta**

**Comment by Meghana-MSFT** [comment]
Thank you for reporting this, we will check this and update the document accordingly.

**Comment by Meghana-MSFT** [comment]
@surbhigupta12 - Could you please help to update the examples mentioned here https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/using-teams-client-sdk?source=recommendations&tabs=typescript%2Cmanifest-teams-toolkit#callbacks-converted-to-promises as below -

1. 

```
import * as microsoftTeams from "@microsoft/teams-js";

microsoftTeams.getContext((context: microsoftTeams.Context) => {
  /* ... */
});
```

to 

```
import * as microsoftTeams from "@microsoft/teams-js";
microsoftTeams.app.getContext().then((context:  microsoftTeams.app.Context) => { 
/* ... */ 
});
```

2.
```
import { app, Context } from "@microsoft/teams-js";

app.getContext().then((context: Context) => {
    /*...*/
});
```

to

```
import { app, Context } from "@microsoft/teams-js"; 

app.getContext().then((context: app.Context) => { 
/*...*/
});
```

3.
```
import { app, Context } from "@microsoft/teams-js";

async function example() {
  const context: Context = await app.getContext();
  /*...*/
}
```

to

```
import { app, Context } from "@microsoft/teams-js"; 

async function example() {
            const context: app.Context = await app.getContext();
            /*...*/
          }
```
