### ISSUE TITLE
Unable to Invoke with a ReplyToId

### ISSUE THREAD

**Issue by ding-harrison** [MicrosoftDocs/msteams-docs#710]
I created a card with a button of type "invoke", and the activity that is reaching my controller when the button is pressed does not contain a "ReplyToId" value. How do I make it so that the ReplyToId property is filled?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28d1cbcc-9670-6eb3-d65a-5c30d307784a
* Version Independent ID: 243e29b8-afbc-7d21-1d24-18f58619af60
* Content: [Add card actions in a bot - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/cards/cards-actions#feedback)
* Content Source: [msteams-platform/concepts/Cards/cards-actions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/Cards/cards-actions.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by hdg97** [comment]
Fixed it. Turns out, the card while still in the chat box, will not have a "reply to id". It should be documented that to have this function, it requires the user to first submit the message into the chat
