### ISSUE TITLE
[Doc-enhancement] Meeting apps in web client is not supported yet, Works only when dev preview is enabled

### ISSUE THREAD

**Issue by SubbaReddi** [MicrosoftDocs/msteams-docs#7116]
Meeting apps (Side panel, meeting stage) is supported in desktop teams. But it is not supported in web teams client. It will work only when dev preview is enabled. Adding note in documentation will help.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 82987815-d508-d642-c1f6-b609241d4750
* Version Independent ID: 29e89cc6-c8ca-7d29-7dca-4ac4d06f5c42
* Content: [Apps for Teams meetings - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/teams-apps-in-meetings)
* Content Source: [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Prasad-MSFT** [comment]
Hi @surbhigupta12 - Could you please help here to add a note in this [doc](https://learn.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/teams-apps-in-meetings) saying:
"Meeting apps (Side panel, meeting stage) is supported in desktop teams. But it is not supported in web teams client. It will work only when dev preview is enabled."
