### ISSUE TITLE
ALL MY NOTES ON ONE NOTE ARE LOST

### ISSUE THREAD

**Issue by tico321** [MicrosoftDocs/msteams-docs#712]
I was editing a page on Onenote. And suddenly the application closed and I lost everything that was in there. Now I can only see this message

![image](https://user-images.githubusercontent.com/4684698/59076741-8f7fa780-88a5-11e9-8d08-d49b026797ca.png)

Some additional Info:
I am working on a macbook pro with Mojave 10.14.5

**Comment by Gousia-MSFT** [comment]
@tico321 Are you doing this inside Microsoft Teams?

**Comment by Wajeed-msft** [comment]
Please re-open with requested informatino.
