### ISSUE TITLE
Missing information SSO and Link broken

### ISSUE THREAD

**Issue by brunoslam** [MicrosoftDocs/msteams-docs#713]
![image](https://user-images.githubusercontent.com/7435715/59140767-26189b00-8970-11e9-8e93-8e2b7eedb09e.png)

More information about this please and the link Learn more is broken

**Comment by clearab** [comment]
We'll get that link updated, you can find more about this here: https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/authentication/auth-silent-aad
