### ISSUE TITLE
Please Add Note for Graph API with an access token to retrieve information.

### ISSUE THREAD

**Issue by sayali-MSFT** [MicrosoftDocs/msteams-docs#7130]
Hi Team,
Documentation don't have details about Graph API with an access token to retrieve information.
The new GetConversationPagedMembers API can't return the userPrincipalName and email properties By late 2022.

So please add the below note-
Here is recommended way to use the [Graph API](https://learn.microsoft.com/en-us/graph/api/user-get?view=graph-rest-1.0&tabs=http#examples) with an access token to retrieve the user information which includes userPrincipalName and email properties.

Document-https://learn.microsoft.com/en-us/microsoftteams/platform/resources/team-chat-member-api-changes#api-changes

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c780d605-b1b2-716f-5888-503608769b5a
* Version Independent ID: 53c724f8-d9a2-4af6-6d75-ddeaef084137
* Content: [Bot API changes for team and chat members - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/resources/team-chat-member-api-changes)
* Content Source: [msteams-platform/resources/team-chat-member-api-changes.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/resources/team-chat-member-api-changes.md)
* Service: **msteams**
* GitHub Login: @ojasvichoudhary
* Microsoft Alias: **ojchoudh**

**Comment by sayali-MSFT** [comment]
@surbhigupta12 -Could you please help us to update the document?

**Comment by ChetanSharma-msft** [comment]
Hello @surbhigupta12, @v-habibaumme, @v-spharish - 
Looks like this document hasn't updated properly.

1) Alignment is not correct:
![image](https://user-images.githubusercontent.com/59052547/196100974-8a369626-98bf-4429-a9bf-41c0530afae4.png)


2) If we are clicking on "Graph API" link, it's redirecting wrongly:
![image](https://user-images.githubusercontent.com/59052547/196101131-2ed32653-629a-4219-8600-0bbde3174a99.png)


Expected: It should redirect to below page:
https://learn.microsoft.com/en-us/graph/api/user-get?view=graph-rest-1.0&tabs=http#examples

Please help us updating the document correctly.
