### ISSUE TITLE
https://dev.botframework.com/bots doesn't show any bot

### ISSUE THREAD

**Issue by dluc** [MicrosoftDocs/msteams-docs#7144]
Bots created from https://dev.botframework.com/bots do not show in the dashboard, and there is no way to find a bot ID.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 45ca0926-65fc-66a5-b881-5b99a589f2ec
* Version Independent ID: b9e40da9-1029-f65f-18b5-f450a8ea87d2
* Content: [Test and debug your bot locally - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/debug/locally-with-an-ide)
* Content Source: [msteams-platform/bots/how-to/debug/locally-with-an-ide.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/bots/how-to/debug/locally-with-an-ide.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **anclear**

**Comment by Prasad-MSFT** [comment]
We are checking this. We will get back to you shortly.

**Comment by Prasad-MSFT** [comment]
@dluc - We tried to repro the issue by following below steps and we are able to repro the issue. The bot created doesn't show up.
1. Navigated to https://dev.botframework.com/bots
2. Clicked on "Create" to create a new bot
![image](https://user-images.githubusercontent.com/62237649/193525745-77242e32-c93c-4ee8-bf82-aa55b336c58d.png)
3. Bot got created successfully. But it doesn't show up in "My bots" section.
![image](https://user-images.githubusercontent.com/62237649/193525984-32cc985f-0809-4268-82e9-1d12a067cc8a.png)
4. You can get an overview of your created bot here in azure portal.
![image](https://user-images.githubusercontent.com/62237649/193526555-9071fa17-efe4-48ea-a5ef-8b4a02877cc7.png)

We have raised a bug for the same and engineering team is looking into it. We will inform you once we get any further update. Thanks!

**Comment by matthiasdilger** [comment]
Hi @Prasad-MSFT I have the issue that all bots created with https://dev.botframework.com/bots/new seem to be missing now from the list of bots, which means I can't modify any settings. They are not visible in the Azure portal. Is there any timeline for a fix?

**Comment by Prasad-MSFT** [comment]
@matthiasdilger - Currently there is no ETA to share. We will check with engineering team and will inform you if there is any update. Thanks!

**Comment by matthiasdilger** [comment]
@Prasad-MSFT Just fyi, I got my issue fixed through Azure support. Apparently the owner information for my old bots was missing and they patched the data.
