### ISSUE TITLE
How to create a new Node.js project for MS Teams?

### ISSUE THREAD

**Issue by nanddeepn** [MicrosoftDocs/msteams-docs#715]
The MSDN page [here](https://docs.microsoft.com/en-us/microsoftteams/platform/get-started/get-started-nodejs-app-studio) mentions to download the pre-created Node.js project.
But, can we please have some guidance on how to create a new Node.js project for MS Teams?
Thanks

**Comment by pschaeflein** [comment]
I would suggest https://github.com/officedev/generator-teams

**Comment by nanddeepn** [comment]
Thank you @pschaeflein
