### ISSUE TITLE
Persistent New Chat notification

### ISSUE THREAD

**Issue by evevista** [MicrosoftDocs/msteams-docs#716]
I have a persistent "new chat" notification even though I have no new chats.
I believe this occurred when a user sent me a message while I was away (my computer was shut down as it was over the weekend). They then deleted the message before I could read it.

![teams](https://user-images.githubusercontent.com/51723095/59306449-59e91d00-8cf0-11e9-802a-884fb4bd1057.png)

**Comment by Gousia-MSFT** [comment]
@evevista Thanks for reporting this. We are looking into it.

**Comment by Gousia-MSFT** [comment]
@evevista Could you please check if there is an unread chat somewhere far down the chat list. If the issue still persists, Could you please share the logs which can be obtained by pressing Ctrl+Alt+Shift+1 from Teams client?

**Comment by Wajeed-msft** [comment]
Please re-open this with requested logs.
