### ISSUE TITLE
Tutorial inconsistent data type 

### ISSUE THREAD

**Issue by cagrimunyas** [MicrosoftDocs/msteams-docs#7161]
On section  **C# code to handle the invoke activity** of the docs from https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/authentication/auth-aad-sso-bots#c-code-to-handle-the-invoke-activity 

The following code piece has parameter mismatch with the method 
` await OnTokenResponseEventAsync(turnContext, cancellationToken);`

The `turnContext` object passed to the method above is of type `ITurnContext<IInvokeActivity>`  while `OnTokenResponseEventAsync` method expects the type `ITurnContext<IEventActivity>`

Also  on the **Token exchange failure** section, To handle the error the bot must respond to `TokenExchangeInvokeRequest` with proper `TokenExchangeInvokeResponse` (See 5th. step on the section) however `TokenExchangeInvokeRequest` is handled by `OnInvokeActivityAsync` method which returns an object of type `InvokeResponse `. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9549caa9-99a2-2568-19a5-f21a79292e2f
* Version Independent ID: f2100d03-b88a-34b2-44a2-935231e89db0
* Content: [Single sign-on support for bots - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/authentication/auth-aad-sso-bots)
* Content Source: [msteams-platform/bots/how-to/authentication/auth-aad-sso-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/bots/how-to/authentication/auth-aad-sso-bots.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Nivedipa-MSFT** [comment]
@cagrimunyas - We will check and update this accordingly.
