### ISSUE TITLE
RSC permissions needed to enable Meeting Stage sharing

### ISSUE THREAD

**Issue by Benjiiim** [MicrosoftDocs/msteams-docs#7163]
According to https://learn.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema#resource-specific-delegated-permissions, the following delegated RSC permissions are required in the manifest to enable meeting stage sharing:
- MeetingStage.Write.Chat
- ChannelMeetingStage.Write.Group

That might be useful to document this prerequisite on the "Enable and configure your apps for Teams meetings" doc.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 62ce7ca6-3ea8-ccca-5c59-92a638303aea
* Version Independent ID: d9a2d747-41cc-add6-f281-4210e888654e
* Content: [Enable and configure your apps for Teams meetings - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings)
* Content Source: [msteams-platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **surbhigupta**

**Comment by Prasad-MSFT** [comment]
Thanks @Benjiiim for pointing it out.
@surbhigupta12 - Could you please help here to get it updated?
Please add a note in this [doc ](https://learn.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings)saying : 
The following delegated RSC permissions are required in the manifest to enable meeting stage sharing:

```
MeetingStage.Write.Chat
ChannelMeetingStage.Write.Group
```
