### ISSUE TITLE
Adaptive Card show text input block based on choice set value

### ISSUE THREAD

**Issue by samthrusha123** [MicrosoftDocs/msteams-docs#7164]
I have a card with input choice set of options a,b,others. 

If users selects option as "others" then an extra input text block should come below the choice set. 

How can we achieve this in microsoft teams bot framework using adaptive cards?

**Comment by Prasad-MSFT** [comment]
@samthrusha123 - Please refer [this](https://stackoverflow.com/questions/63393706/adaptive-card-show-text-input-block-based-on-choice-set-value) thread which addresses similar issue.

**Comment by samthrusha123** [comment]
> @samthrusha123 - Please refer [this](https://stackoverflow.com/questions/63393706/adaptive-card-show-text-input-block-based-on-choice-set-value) thread which addresses similar issue.

That is in webchat. How to implement same in teams using adaptive cards templating?

**Comment by Prasad-MSFT** [comment]
Cascading dropdown list doesn't seem to be feasible at the moment. Alternative you can use Action.ToggleVisibility (action that toggles the visibility of associated card elements). Ref: [adaptivecards.io/explorer/Action.ToggleVisibility.html](https://adaptivecards.io/explorer/Action.ToggleVisibility.html)
