### ISSUE TITLE
Notifications on iOS not persisting

### ISSUE THREAD

**Issue by chrislewisdev2** [MicrosoftDocs/msteams-docs#717]
Teams 1.0.75 on iOS seems to have an issue with notifications not persisting.

I get a notifications appear with a sound then within a second they disappear so they don't persist onto the lock screen, notification centre or as banners - all of which I've enabled in the iOS settings page, as well as ensuring the banner style is set to persistent.

**Comment by Gousia-MSFT** [comment]
@chrislewisdev2 Thanks for reporting it. We are looking into this.

**Comment by zzStone** [comment]
@chrislewisdev2 Hi, I'm Jizhou from Teams iOS.  This issue looks like a burn notification.  If push notifications have been seen in another Teams client, the iOS notifications will be burned and disappear.  Were you using other clients at that time?  If that's not the case, feel free to shake within the app and file a bug to us.  In that way, we can have logs and deviceInfo.

**Comment by Wajeed-msft** [comment]
As @zzStone mentioned please file a bug. Closing this issue.
