### ISSUE TITLE
iOS Teams not showing card if in card we have ampersand in hyperlink 

### ISSUE THREAD

**Issue by Reder137** [MicrosoftDocs/msteams-docs#7170]
iOS show only "Sent a card" if i have link with ampersand for ex: `https://www.google.com/search?q=hyperlink&rlz=1C1SQJL_ruUA927UA927&oq=hyperlink&aqs=chrome..69i57j69i59j69i60l3.4804j0j15&sourceid=chrome&ie=UTF-8`
![image](https://user-images.githubusercontent.com/42004786/194336976-e853a727-e6b9-4b61-b75b-c216d62192fa.png)
Windows or Android app show all.

Why it's happen ? 
How i can fix that ?

**Comment by Nivedipa-MSFT** [comment]
@Reder137 - Thanks for reporting this issue. We will test this and update you soon.

**Comment by Reder137** [comment]
@Nivedipa-MSFT  thank a lot for the answer ! 
But on my side still reproduce. 
I tested with 2 device. 
Updated teams and IOS. 

And to be sure on your example you use url with ampersand ?

![image](https://user-images.githubusercontent.com/42004786/194867183-b8e79df8-ade6-4cec-b515-3da4d2183652.png)
![image](https://user-images.githubusercontent.com/42004786/194867341-c027e191-2141-4948-aa31-aec3d6981cc9.png)
![image](https://user-images.githubusercontent.com/42004786/194867435-3e87bf24-6d0f-4f14-83a9-32687abe9a51.png)

**Comment by Reder137** [comment]
Also in your test add some text and 3-4 button with link, maybe it can help you reproduce 
![image](https://user-images.githubusercontent.com/42004786/194873347-fd04e34e-b166-4c94-bdf7-eb5b459caa81.png)

**Comment by Nivedipa-MSFT** [comment]
@Reder137 - Could you please share your card Json to test at our end?

**Comment by Nivedipa-MSFT** [comment]
@Reder137 - At our end we are not getting sent a card message only. Could you please share your json to test at our end?
