### ISSUE TITLE
Page no longer accurate

### ISSUE THREAD

**Issue by Andreuha** [MicrosoftDocs/msteams-docs#7171]
Option to disable developer preview no longer exists in the stated menu.

![image](https://user-images.githubusercontent.com/33904686/194350716-97c82e7c-1f23-4b19-8e0d-289fb72f1f06.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 008da4e2-979e-c396-db28-4acf57deb530
* Version Independent ID: f1413f77-5eb3-e1fd-9235-d322d6e4eb6c
* Content: [Public developer preview for Microsoft Teams - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/resources/dev-preview/developer-preview-intro)
* Content Source: [msteams-platform/resources/dev-preview/developer-preview-intro.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/resources/dev-preview/developer-preview-intro.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Nivedipa-MSFT** [comment]
@Andreuha - Could you please update the Teams version and check again.

**Comment by Nivedipa-MSFT** [comment]
@Andreuha - Could you please update the policy as Not Enabled and check again.
Please refer below document for updating policy.
https://learn.microsoft.com/en-us/microsoftteams/public-preview-doc-updates#set-the-update-policy

**Comment by Andreuha** [comment]
> 

I am not the admin for the company's O365 policy. I am a regular user, who enabled this on their own, and have been unable to disable it since.

**Comment by Nivedipa-MSFT** [comment]
@Andreuha - Could you please connect with your tenant admin to disable the policy?

**Comment by Andreuha** [comment]
> @Andreuha - Could you please connect with your tenant admin to disable the policy?

Due to an issue w/ Excel, I had to uninstall and reinstall all office apps on my PC, including Teams, and Teams no longer shows the preview icon. It seems it may have already been disabled but there's a bug which prevented that disabling from that propagating to machines of people in Preview mode?

**Comment by Nivedipa-MSFT** [comment]
@Andreuha - We are mainly responsible for Microsoft Teams app development related issues. 

For Microsoft Teams product issues you can reach out to [Microsoft 365 Product Support](https://docs.microsoft.com/en-us/microsoft-365/admin/contact-support-for-business-products?view=o365-worldwide&tabs=online).

**Comment by Andreuha** [comment]
> @Andreuha - We are mainly responsible for Microsoft Teams app development related issues.
> 
> For Microsoft Teams product issues you can reach out to [Microsoft 365 Product Support](https://docs.microsoft.com/en-us/microsoft-365/admin/contact-support-for-business-products?view=o365-worldwide&tabs=online).
> 
> Please let us know if you need any other help here.

It does appear that there is still a bug in Teams, it was just different from the issue as I had initially reported it.

**Comment by Nivedipa-MSFT** [comment]
@Andreuha - Could you please share what exact issue you are facing right now?

**Comment by Andreuha** [comment]
> 

I have no issue, but I assumed you might want to keep this open in order to fix a bug to prevent this from happening to other users/companies when they change the setting in their environments.

**Comment by Andreuha** [comment]
> @Andreuha - Could you please share what exact issue you are facing right now?

I have no issue, but I assumed you might want to keep this open in order to fix a bug to prevent this from happening to other users/companies when they change the setting in their environments.

**Comment by erikadoyle** [comment]
The docs are now updated per suggestion. #please-close

**Comment by Nivedipa-MSFT** [comment]
@Andreuha - Document has updated. Could you please check and confirm?
![image](https://user-images.githubusercontent.com/92150070/217511876-16abd036-1881-4238-9ae7-87bee1fdb803.png)

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, please feel free to reopen it, if required.
