### ISSUE TITLE
SSO fails at Invoke signin/verifyState

### ISSUE THREAD

**Issue by DavidVollmers** [MicrosoftDocs/msteams-docs#718]
Following scenario: I have a *working* bot with an AAD v2 OAuth connection. Now i have created a new bot which is just for staging (DEV/PROD). This new bot works the same with one exception: SSO in MS Teams. Magic Code authentication works in both MS Teams and Emulator. SSO only works in Emulator. The error is the following:

`Invoke failed due to internal error: Invoke failed: something went wrong in ProcessInvoke`

This error occures when MS Teams sends the signin/verifyState Invoke Message to https://emea.ng.msg.teams.microsoft.com/v1/agents and results in a HTTP 500...

Since the SSO directly to my new bot *does work* in the Bot Framework Emulator i am sure this problem is on the site https://emea.ng.msg.teams.microsoft.com.

Both bots are configured in the same way. The only difference is the MS App ID and Password. This issue is a showbreaker for us, since we cannot use MS Teams if there is no SSO supported.

BR
David Vollmers

**Comment by Wajeed-msft** [comment]
Fix for this has been rolled out. Could you please try it one more time and let us know if you are still facing this issue?

**Comment by DavidVollmers** [comment]
The SSO now works perfectly **but** we now can't configure the OAuth Connection anymore, since the blade is missing in portal.azure.com .

**Comment by Wajeed-msft** [comment]
Could you please check it now? I could see OAuth Connection setting.

**Comment by DavidVollmers** [comment]
Yeah now they are visible again but not testable. Trying to test it results in a 404 Not Found...

**Comment by Wajeed-msft** [comment]
Is auth working fine in bot?

**Comment by DavidVollmers** [comment]
The authentication works. But we cannot configure it anymore:
![image](https://user-images.githubusercontent.com/11387266/59759595-bc15c500-9290-11e9-9251-9debb6c89576.png)
![image](https://user-images.githubusercontent.com/11387266/59759669-e798af80-9290-11e9-9663-265981d6d213.png)
![image](https://user-images.githubusercontent.com/11387266/59759699-f1221780-9290-11e9-8dd2-df03912da988.png)

**Comment by Wajeed-msft** [comment]
Can you try adding a new Oauth connection setting?

**Comment by DavidVollmers** [comment]
I can create a new connection but cant edit it afterwards. The problem seems to only exist for Saving/Deleting and Testing of connections.

**Comment by DavidVollmers** [comment]
The configuration and implementation of the OAuth connection works again.
