### ISSUE TITLE
MSTeams: Dynamic configuration bot tab

### ISSUE THREAD

**Issue by KaratLee** [MicrosoftDocs/msteams-docs#7188]
We know that static tabs can be configured statically through manifest's staticTabs, but we don't see the entry for dynamically configuring tabs: for example, user group 1 can only use the functions of tab1, user group 2 can only use the functions of tab2, and user group 3 can use tab1 and The function of tab2, in this scenario, we need to dynamically display tabs according to the user's situation, instead of all users seeing the same tab1, tab2.

May I ask if the function of dynamic configuration tab is supported and how to use this function, I look forward to your reply.Thank you very much.

**Comment by sayali-MSFT** [comment]
@KaratLee - Thanks for reporting your issue.
We will investigation this issue and get back to you.

**Comment by sayali-MSFT** [comment]
@KaratLee -We do not have any provision to define our own custom logic to hide/display tab.
 
Could you please help by suggesting this feature on - Microsoft Teams · Community[https://feedbackportal.microsoft.com/feedback/forum/ad198462-1c1c-ec11-b6e7-0022481f8472]

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.
