### ISSUE TITLE
Not able to control Hyper-V VM via screen sharing

### ISSUE THREAD

**Issue by AurisB** [MicrosoftDocs/msteams-docs#719]
Not able to control Hyper-V VM via screen sharing session. 
When remote user trying to click somewhere inside HyperV during screen sharing , his mouse pointer hangs and then he is not able to click anywhere outside the VM screen.

**Comment by Wajeed-msft** [comment]
@AurisB - Could you please share the logs which can be obtained by pressing Ctrl+Alt+Shift+1 from Teams client? Please re-open this issue by attaching the logs.

**Comment by AurisB** [comment]
[MSTeams Diagnostics Log 6_27_2019__3_17_22_PM.txt](https://github.com/MicrosoftDocs/msteams-docs/files/3334649/MSTeams.Diagnostics.Log.6_27_2019__3_17_22_PM.txt)
[MSTeams Diagnostics Log 6_27_2019__3_17_22_PM_sync.txt](https://github.com/MicrosoftDocs/msteams-docs/files/3334650/MSTeams.Diagnostics.Log.6_27_2019__3_17_22_PM_sync.txt)
[MSTeams Diagnostics Log 6_27_2019__3_17_22_PM_calling.txt](https://github.com/MicrosoftDocs/msteams-docs/files/3334651/MSTeams.Diagnostics.Log.6_27_2019__3_17_22_PM_calling.txt)
[MSTeams Diagnostics Log 6_27_2019__3_17_33_PM.txt](https://github.com/MicrosoftDocs/msteams-docs/files/3334652/MSTeams.Diagnostics.Log.6_27_2019__3_17_33_PM.txt)
[MSTeams Diagnostics Log 6_27_2019__3_17_33_PM_sync.txt](https://github.com/MicrosoftDocs/msteams-docs/files/3334653/MSTeams.Diagnostics.Log.6_27_2019__3_17_33_PM_sync.txt)
[MSTeams Diagnostics Log 6_27_2019__3_17_33_PM_calling.txt](https://github.com/MicrosoftDocs/msteams-docs/files/3334654/MSTeams.Diagnostics.Log.6_27_2019__3_17_33_PM_calling.txt)
[MSTeams Diagnostics Log 6_27_2019__3_17_16_PM.txt](https://github.com/MicrosoftDocs/msteams-docs/files/3334655/MSTeams.Diagnostics.Log.6_27_2019__3_17_16_PM.txt)
[MSTeams Diagnostics Log 6_27_2019__3_17_16_PM_sync.txt](https://github.com/MicrosoftDocs/msteams-docs/files/3334656/MSTeams.Diagnostics.Log.6_27_2019__3_17_16_PM_sync.txt)
[MSTeams Diagnostics Log 6_27_2019__3_17_16_PM_calling.txt](https://github.com/MicrosoftDocs/msteams-docs/files/3334657/MSTeams.Diagnostics.Log.6_27_2019__3_17_16_PM_calling.txt)

**Comment by Gousia-MSFT** [comment]
@AurisB Could you please provide the following details:
1. Number of users affected.
2. Tenant Id and Name.
3. Name and details of the user.

**Comment by AurisB** [comment]
1. All our organization users as I aware (more than 20)
2. Tenant id 204df618-7087-4fc1-96a9-9ea1a16cef45, Hyarchis
3. One user example: Modestas Kairys, m.kairys@hyarchis.com

2019-07-03, tr, 11:18 Gousia-MSFT <notifications@github.com> rašė:

**Comment by Gousia-MSFT** [comment]
@AurisB This is currently by design. We are working on improving the experience.
