### ISSUE TITLE
Live surveys to teams during meetings using bot framework

### ISSUE THREAD

**Issue by samthrusha123** [MicrosoftDocs/msteams-docs#7191]
We have a survey application, where we can create different types of questions. Currently we're creating survey in web application and broadcasting it to teams, Where they can fill surveys. Is there any way to implement live surveys using bot framework in teams during the meetings. Like admin can send the questions to the participants. And getting results at the same time. Something like this?

![image](https://user-images.githubusercontent.com/44087954/194868677-5e98593d-1194-4f92-ab79-b173cc03f777.png)

This I tested with microsoft forms. But instead of microsoft forms, we want to achieve this with some other survey application.

**Comment by Meghana-MSFT** [comment]
Please check this sample if that helps - https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/meetings-content-bubble/csharp

**Comment by samthrusha123** [comment]
> Please check this sample if that helps - https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/meetings-content-bubble/csharp

How to add this teams app to meetings?

**Comment by Meghana-MSFT** [comment]
Please upload the app package to Teams. Then you can add it to any meeting as shown here - 
![image](https://user-images.githubusercontent.com/81138249/195096455-a6b0fe28-8918-4a84-936a-c74d824f172b.png)

"Provided add-in package was not understood. Please, make sure that the file being submitted is a valid Office add-in package." error comes if your app package has more than 3 files. App package should contain only manifest.json, outline and color files. Please check if you are adding anything extra in the app package.

**Comment by samthrusha123** [comment]
![image](https://user-images.githubusercontent.com/44087954/195314869-0ccdf936-c6a3-4ada-b4d1-69db409d518d.png)




Comming like this while adding to meeting

**Comment by Meghana-MSFT** [comment]
Could you please confirm if you have made any changes to the code, we have setup the sample as it is and were able to add it to meeting successfully.

**Comment by samthrusha123** [comment]
> Could you please confirm if you have made any changes to the code, we have setup the sample as it is and were able to add it to meeting successfully.

I just added my bot client id's in the manifest. and Added that manifest file to developer portal. Then I'm trying to add it to teams. I'm getting that. I haven't change any code

**Comment by samthrusha123** [comment]
![image](https://user-images.githubusercontent.com/44087954/195316973-c4236ac1-ca6f-4fdf-b975-f3c0ab5c7636.png)

In which scenarios we'll get this error?

**Comment by ChetanSharma-msft** [comment]
Hello @samthrusha123 - Have you tried to sideloading your app?
Please refer this document: https://learn.microsoft.com/en-us/microsoftteams/custom-app-overview

Meanwhile we will also try it using Developer Portal and let you know the updates.

**Comment by samthrusha123** [comment]
When we click on preview in teams It got side loaded

![image](https://user-images.githubusercontent.com/44087954/195338308-c19ba281-c23c-490d-8d00-5c6b946f645b.png)


After this I tried from the developer portal [https://dev.teams.microsoft.com/](url) to preview in teams. I got that error. 

I tried to add it through teams(Apps->Manage your Apps->Upload app (manaifest.zip)) and selected Add to a meeting from the dropdown still it's showing the same error

![image](https://user-images.githubusercontent.com/44087954/195339239-7ab95158-3751-46d2-9caf-41e883beafd5.png)

**Comment by samthrusha123** [comment]
1. I cloned your git hub repository
2. I created a test bot service in azure
3. Updated bot id in the app manifest and in app settings as well
4. Then I made a zip file using manifest, color, outline
5. Imported this to developer portal
6. After importing in the basic information added bot id in the Application (client) ID field
7. Then I clicked on preview teams.
8. I got the below screen later, selected **Add to a meeting** 
![image](https://user-images.githubusercontent.com/44087954/195404175-b624e593-d8e6-4f1e-bd88-f9ed771919fb.png)
9. Then It asked to select meeting name
![image](https://user-images.githubusercontent.com/44087954/195404334-9111b9f1-3459-42d0-93ce-6f8725060b48.png)

10. After selecting the meeting showing the below screen
![image](https://user-images.githubusercontent.com/44087954/195404600-7c9c398b-9ec4-493f-be01-ec54ae4d39cd.png)


I'm not sure whether do we need to add anything in the azure portal like configurations to add to a meeting?

**Comment by Meghana-MSFT** [comment]
Can you please check if you have added Teams in channels while doing bot registration? 
![image](https://user-images.githubusercontent.com/81138249/195514666-f90b6599-f840-4ec6-9aba-9334b97846e0.png)

**Comment by samthrusha123** [comment]
My bad, I missed that.

**Comment by Meghana-MSFT** [comment]
Thank you for confirming, can we close this issue?
