### ISSUE TITLE
bot menu in Microsoft Teams are Not support on mobile app

### ISSUE THREAD

**Issue by best0032001** [MicrosoftDocs/msteams-docs#720]
This is very bad user experience for mobile

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f73ba47e-c894-2751-cb58-0b6d8d1c59f2
* Version Independent ID: 4b88ea6f-86fa-c99f-4c6f-3dddb2bf5739
* Content: [Add a bot menu - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/bots/bots-menus#feedback)
* Content Source: [msteams-platform/concepts/bots/bots-menus.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/bots/bots-menus.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Gousia-MSFT** [comment]
@best0032001 This is something we are working on but do not have a timeline to share.
