### ISSUE TITLE
New Message Reactions Not Loading Properly

### ISSUE THREAD

**Issue by SnazzySnail8** [MicrosoftDocs/msteams-docs#721]
There seems to be a bug with the release of the reactions feature. I no longer see the '...' menu in the upper right hand corner of a message and there doesn't seem to be any indication of available actions. However, when I scroll over that corner a menu appears but the menu is blank until I mouse over the menu and even then only some of the icons show upon mousing over.

![Teams_Reactions_Bug_2](https://user-images.githubusercontent.com/44416747/59459982-e1a75800-8dd2-11e9-85a4-30efcfdc28e1.png)

**Comment by Wajeed-msft** [comment]
We are not able to repro this at our end. Are you still facing this issue? Is someone from your team also facing the same issue?
