### ISSUE TITLE
How to wrap choice set text &  it's placeholders text

### ISSUE THREAD

**Issue by samthrusha123** [MicrosoftDocs/msteams-docs#7211]
Placeholder is getting truncated. Options are occupying large space. Is there any way to wrap option text and placeholder text

![image](https://user-images.githubusercontent.com/44087954/195397029-5b731e3a-7181-4f4a-91b8-3d4a31cb4a93.png)

`{
    "type": "AdaptiveCard",
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.4",
    "body": [
        {
            "type": "ColumnSet",
            "columns": [
                {
                    "type": "Column",
                    "width": "stretch",
                    "items": [
                        {
                            "type": "TextBlock",
                            "text": "Online Text Generator is a website built for users to quickly and easily create custom text graphics in your favorite text font themes. We have 13 online text generator themes available for custom text creation. You can create custom text in",
                            "wrap": true
                        }
                    ]
                },
                {
                    "type": "Column",
                    "width": "stretch",
                    "items": [
                        {
                            "type": "Input.ChoiceSet",
                            "id":"ChoiceSet1",
                            "choices": [
                                {
                                    "wrap":true,
                                    "title": "Online Text Generator is a website built for users to quickly and easily create custom text graphics in your favorite text font themes. We have 13 online text generator themes available for custom text creation. You can creat",
                                    "value": "Choice 1"
                                },
                                {
                                    "title": "Choice 2",
                                    "value": "Choice 2"
                                }
                            ],
                            "placeholder": "Online Text Generator is a web"
                        }
                    ]
                },
                {
                    "type": "Column",
                    "width": "stretch"
                }
            ]
        }
    ]
}`

**Comment by Meghana-MSFT** [comment]
We are looking into this issue, we will update you.

**Comment by samthrusha123** [comment]
> We are looking into this issue, we will update you.

Did you find anything?
