### ISSUE TITLE
This page recommends calling getAuthToken "from inside microsoftTeams.initialize()" which is not possible

### ISSUE THREAD

**Issue by AE-MS** [MicrosoftDocs/msteams-docs#7216]
The `initialize()` method is implemented in the teams-js library, not the app code. The app developer cannot do anything from "inside microsoftTeams.initialize()" because that's not part of their app code.

Separately but related: the `initialize` function is either just a function with no namespace ([here](https://learn.microsoft.com/en-us/javascript/api/@microsoft/teams-js/?view=msteams-client-js-latest#@microsoft-teams-js-initialize)) or inside the `app` namespace ([here](https://learn.microsoft.com/en-us/javascript/api/@microsoft/teams-js/app?view=msteams-client-js-latest#@microsoft-teams-js-app-initialize)). There is no `**microsoftTeams**.initialize()` function because the app developer can prepend any prefix they want when they import the teams-js library; they don't need to call it `microsoftTeams` -- it may not even have any prepended name.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 410609cf-c930-72de-319d-351212f71b8c
* Version Independent ID: 410609cf-c930-72de-319d-351212f71b8c
* Content: [Code configuration for enabling SSO for tabs - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/tab-sso-code)
* Content Source: [msteams-platform/tabs/how-to/authentication/tab-sso-code.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/tabs/how-to/authentication/tab-sso-code.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Nivedipa-MSFT** [comment]
@AE-MS - We will check and update this accordingly.
