### ISSUE TITLE
Not found when image shared from camera on mobile

### ISSUE THREAD

**Issue by ogarules** [MicrosoftDocs/msteams-docs#722]
I'm using Bot Builder SDK v4, C#

When I attach an image from the desktop application I can get the attached file using the "downloadUrl" inside "Content". My problem comes when a user takes a photo from the mobile App, "Content" comes empty and if I use "ContentUrl" of the attachment object, I receive 404 Not found. Is there a workaround for downloding files shared from mobile this way?

**Comment by Wajeed-msft** [comment]
What value are you getting in _ContentUrl_? There is an [issue with inline image's content URL](https://github.com/Microsoft/botbuilder-dotnet/issues/1834). We are working on it.

**Comment by ogarules** [comment]
> What value are you getting in _ContentUrl_? There is an [issue with inline image's content URL](https://github.com/Microsoft/botbuilder-dotnet/issues/1834). We are working on it.

Thank you for your answer, that is precisely my issue. Replacing "imgo" for "original" con the ContentURL solved my issue.

The following is an example of the url I'm getting on the ContentUrl: 

https://smba.trafficmanager.net/amer/v3/attachments/0-cus-d10-2f3d647752092b4dca809dbb30d96414/views/imgo

Thank you, I was able to make a workaround that works in my scenario, I'm sending the image to 
 Custom Vision to make some evaluation... it would be nice to have the name of the file as well, I guess I'll have to wait for the fix

**Comment by Wajeed-msft** [comment]
This issue has been fixed. Please re-open if you are still facing it.
