### ISSUE TITLE
OnTeamsMeetingStartAsync() and OnTeamsMeetingEndAsync() method not calling in one of my tenant but its working locally in Demo tenant

### ISSUE THREAD

**Issue by Sunaina-30** [MicrosoftDocs/msteams-docs#7226]
OnTeamsMeetingStartAsync() and OnTeamsMeetingEndAsync() method not calling in one of my tenant but its working locally in Demo tenant.

Is there any configuration or license changes need to do in my tenant for Microsoft Teams client so that it can work?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 805dc242-7b5a-cc81-ee0e-6acf0078a653
* Version Independent ID: 11c0e023-2514-9639-6052-2cbbbef50663
* Content: [Meeting apps API references - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/api-references?tabs=dotnet)
* Content Source: [msteams-platform/apps-in-teams-meetings/API-references.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/apps-in-teams-meetings/API-references.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Sunaina-30** [comment]
Hello Nivedipa,
Without developer preview also, its hitting the methods locally but not in
the production.

**Comment by Nivedipa-MSFT** [comment]
@Sunaina-30 - Could you please confirm that you have added "OnlineMeeting.ReadBasic.Chat" permission?

**Comment by Sunaina-30** [comment]
Yes I have added OnlineMeeting.ReadBasic.chat

**Comment by Sunaina-30** [comment]
OnlineMeeting.ReadBasic.chat This permission is already added in the manifest still its not working. Is there anything else I can do?

**Comment by Nivedipa-MSFT** [comment]
@Sunaina-30 - We are checking this with the engineering team. We will let you know once we have any update on it.

**Comment by Nivedipa-MSFT** [comment]
@Sunaina-30 - Could you please confirm that is your issue resolved or are you still facing this issue?
