### ISSUE TITLE
Is there any way to retrieve JWT token with defined scopes via restful api

### ISSUE THREAD

**Issue by Chang025** [MicrosoftDocs/msteams-docs#7227]
Summary:
We wanted to enable AAD SSO login with the team's application. With bot framework SDK, I can see the methods like exchangeToken and signOutUser.
Is there any way we can get the same thing done with bot build restful APIs?

reference: 
On clicking on the below test connection, it will open up a sign-in dialog followed by a permission dialog which contains all the things listed in the scopes. After a successful connection it generate a JWT token(see second attachment)
<img width="440" alt="Screenshot 2022-10-14 at 6 25 49 PM" src="https://user-images.githubusercontent.com/46022906/195852403-fca616ec-0d90-40fd-9110-c3a718d4924a.png">
<img width="987" alt="Screenshot 2022-10-14 at 6 29 41 PM" src="https://user-images.githubusercontent.com/46022906/195852997-bc20a951-9ced-4039-b36b-b1e3a131df62.png">

We have implemented ms teams with restful api(https://learn.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-quickstart?view=azure-bot-service-4.0).

- Our requirement is to get the above-mentioned JWT token via restAPI so that we can access the user details mentioned in the scopes defined in the Oauth Connection (first screenshot).
- We need to find a way to re-generate the JWT token if it expires.

**Comment by sayali-MSFT** [comment]
@Chang025 - Thanks for reporting your issue.
We will investigation this issue and get back to you.

**Comment by Chang025** [comment]
any update on this @sayali-MSFT  ?
Our goal is to get the access_token so that we can call the graph APIs.
Do you have any API to silently get the access_token?
Also, we have implemented [OAuth 2.0 authentication](https://learn.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-authentication?view=azure-bot-service-4.0&tabs=multitenant) for sending and receiving messages between bot and end-user.

**Comment by sayali-MSFT** [comment]
@Chang025 -You can get the access token silently but not at the first time, First a user must authorize your app by going through Microsoft's Login flow and for your subsequent calls to Microsoft, you can get the access token without the intervention of user.

1. Register your app with Azure AD.
2. Get authorization.
3. Get an access token.
4. Grab that Authorization Code and exchange it for an Access Token using `/oauth2/{version}/token` api.
You will receive a response from above call which will contain an Access Token along with a **Refresh Token**. You need to store the refresh token somewhere for future use.
5. Using the **refresh token**, you can renew the access token when it expires without user's intervention. You can use `oauth2/v2.0/token` api with parameters:

`client_id={your_client_id}&scope={your_scopes}&refresh_token={refresh_token_obtained}&grant_type=refresh_token&client_secret={your_client_secret}`

The resultant response would look something like this:

```
{
    "access_token": "new access token",
    "token_type": "Bearer",
    "expires_in": 3599,
    "scope": "your scopes",
    "refresh_token": "refresh token",
}
```

Reference Document- https://learn.microsoft.com/en-us/graph/auth-v2-user#authorization-request

**Comment by Chang025** [comment]
@sayali-MSFT -  The user who is interacting with the Teams app is already part of our organization. The user can only see our bot when he is logged-in in the Teams app.
 
The process listed above will not make a good UX for the end user, since we have to ask the user to login again and get consent.

I was wondering if we can utilize the service-to-service token which is mentioned in the below document.
https://learn.microsoft.com/en-us/azure/active-directory-b2c/client-credentials-grant-flow?pivots=b2c-user-flow
Can you provide some details on how as an administrator I can grant the graph APIs permission for my app(as mentioned in the above doc)?

**Comment by sayali-MSFT** [comment]
@Chang025 - We will investigate on it and get back to you.

**Comment by ChetanSharma-msft** [comment]
Hello @Chang025 - Please let us know whether your query has resolved or still looking for any further help here?

**Comment by Chang025** [comment]
Hi @ChetanSharma-msft 
We are good for now, closing this ticket.
