### ISSUE TITLE
Wrong order of displaying messages

### ISSUE THREAD

**Issue by MajaEffenberg** [MicrosoftDocs/msteams-docs#7228]
The order of the displayed chat messages is incorrect. The message sent by the user is sometimes displayed in the chat in wrong place, not in the place where it was sent, but after the reply to it.

Flow of messages:
1. Bot sent an adaptive card with question and answers (A, B, C as action buttons)
2. The user clicked on answer B on the adaptive tab which sent a response with the text `B` to the bot
3. Bot, after receiving a response from user, sent messages:  
    - adaptive card 'Correct, well done'
    - text message 'Cool...'

![grafik](https://user-images.githubusercontent.com/89073193/195879675-8d4dd637-46ed-454b-9081-2e71023b52a4.png)

Based on this flow and the posted picture of the conversation you can see that the user's message `B` is displayed in the wrong place. It should be displayed between the adaptive card with the question and the adaptive card with the text 'Correct, well done'.

I think it is very important that all messages are displayed in the correct order as it is confusing for a conversation if the order is messed up and causes problems with following and having a conversation.

**Comment by sayali-MSFT** [comment]
@MajaEffenberg - Thanks for reporting your issue.
We will investigation this issue and get back to you.

**Comment by sayali-MSFT** [comment]
@MajaEffenberg -An extensive dialog between your bot and the user is a slow and complex way to get a task completed. due to this causes the issue.
also could you please provide the sample which you refer?
Reference doc-https://learn.microsoft.com/en-us/microsoftteams/platform/bots/bot-features?tabs=dotnet#disadvantages-of-bots

**Comment by ChetanSharma-msft** [comment]
Hello @MajaEffenberg - Sorry for delay in response.
Please confirm whether you are testing this app in Teams?
Also, could you please share the doc that you have followed to implement it?

We will try this scenario and let you know the updates.

**Comment by MajaEffenberg** [comment]
Yes, the error appears in a conversation in Microsoft Teams. However, most of the messages displayed are in the right order in our bot, only sometimes the user message is in the wrong position.

To build our bot we based on [Microsoft Bot Framework](https://learn.microsoft.com/en-us/microsoftteams/platform/bots/bot-features?tabs=dotnet) documentation and when it comes to messages, we relied on [Messages in bot conversations](https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-messages?tabs=dotnet).

**Comment by sayali-MSFT** [comment]
@MajaEffenberg -Thank you for providing the information. We are trying it from our end get back to u.

**Comment by sayali-MSFT** [comment]
@MajaEffenberg -We are not able to repro the scenario. Could you please share the console log, so that we can investigate from our end?
