### ISSUE TITLE
Accent color description is incorrect[2691778]

### ISSUE THREAD

**Issue by et01267** [MicrosoftDocs/msteams-docs#7232]
In several places, the document claims that the Accent color is used as the background for the outline image.  In fact, it seems that the Accent color is used as the background for the Color image.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0f94a488-d636-92b3-21eb-c88744c8f272
* Version Independent ID: 7b3413f4-9ade-accf-5cb2-83fead11a32a
* Content: [Manifest schema reference - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema)
* Content Source: [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/resources/schema/manifest-schema.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Prasad-MSFT** [comment]
@et01267 - Thanks a lot for bringing this up.
Hi @surbhigupta12 - Could you please help here to update the [doc](https://learn.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema#accentcolor) accordingly?

**accentColor**
```
Required—HTML Hex color code
A color to use and as a background for your color icons.
The value must be a valid HTML color code starting with '#', for example #4464ee.
```
