### ISSUE TITLE
How do you call getTabInstances from c#/asp.net/Blazor Server

### ISSUE THREAD

**Issue by bemokraig** [MicrosoftDocs/msteams-docs#7246]
I see the function in the TeamsJsBlazorInterop.js file but it is not exposed.  How are we supposed to get tab info to link to tabs?  Maybe I am missing something?  Are we supposed to use graph?  Just looking for the preferred method.

**Comment by Nivedipa-MSFT** [comment]
@bemokraig - We are checking this internally. We will update you soon.

**Comment by Nivedipa-MSFT** [comment]
@bemokraig - Could you please confirm that is your issue resolved or you have any further query?

**Comment by bemokraig** [comment]
Thanks that answers my question.

**Comment by Nivedipa-MSFT** [comment]
@bemokraig - Thanks for confirmation. Could you please share your feedback [here](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR7iCOpS5_b9Nqmwx43u5rtZUOThVR081SllSR05aSDQxQ0tUMDVPTVIxTi4u).
