### ISSUE TITLE
When will the API changes actually take place?

### ISSUE THREAD

**Issue by johnhelmacy** [MicrosoftDocs/msteams-docs#7253]
This documentation specifies:

"The deprecation process for TeamsInfo.getMembers and TeamsInfo.GetMembersAsync APIs have started."

However, I can't find an actual date for when these changes will take effect. What is this date and/or where can I find it?

Also, on this same page, the doc states:

"By late 2022, bots can't proactively retrieve the userPrincipalName or email properties for members of a chat or team"

What is the date in "late 2022" or where can I find it when this change will take effect?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c780d605-b1b2-716f-5888-503608769b5a
* Version Independent ID: 53c724f8-d9a2-4af6-6d75-ddeaef084137
* Content: [Bot API changes for team and chat members - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/resources/team-chat-member-api-changes)
* Content Source: [msteams-platform/resources/team-chat-member-api-changes.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/resources/team-chat-member-api-changes.md)
* Service: **msteams**
* GitHub Login: @ojasvichoudhary
* Microsoft Alias: **ojchoudh**

**Comment by Meghana-MSFT** [comment]
We are closing this issue, please feel free to reach out to us if you have any questions. Thank you.
