### ISSUE TITLE
Remove the claim that cards support audio and video

### ISSUE THREAD

**Issue by aosolis** [MicrosoftDocs/msteams-docs#7254]
> Message formatting enables you to bring out the best in bot messages. You can format your bot messages to include rich cards as attachments that contain interactive elements, such as buttons, text, images, audio, video, and so on.

audio and video are not supported in cards, nor in bot messages
Please remove this.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4b62aabd-f012-24c9-0edf-e840b20a9dfc
* Version Independent ID: a5c79257-d3a7-c9b5-8a98-7e1495b08a7e
* Content: [Format your bot messages - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/format-your-bot-messages)
* Content Source: [msteams-platform/bots/how-to/format-your-bot-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/bots/how-to/format-your-bot-messages.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **anclear**

**Comment by Nivedipa-MSFT** [comment]
@surbhigupta12 - Could you please remove the audio and video from following content.
Message formatting enables you to bring out the best in bot messages. You can format your bot messages to include rich cards as attachments that contain interactive elements, such as buttons, text, images, audio, video, and so on.

Content link: https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/format-your-bot-messages
