### ISSUE TITLE
Is it still under devPreview?

### ISSUE THREAD

**Issue by abhijeet610** [MicrosoftDocs/msteams-docs#726]
Is the message action feature is available outside devPreview version. I am looking to integrate this feature in one of our app.

**Comment by Wajeed-msft** [comment]
This is released to public ring. You could see developerPreview features in [Features in the Public Developer Preview for Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/dev-preview/developer-preview-features) documentation.
