### ISSUE TITLE
[API] Get conversation member contains only id as response.

### ISSUE THREAD

**Issue by Chang025** [MicrosoftDocs/msteams-docs#7263]
doc reference: https://learn.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-api-reference?view=azure-bot-service-4.0#get-conversation-member

We are using this API to fetch user details associated with the conversation. Recently, it is not providing the proper response.
We are fetching conversationId, memberId  and serviceUrl from the request received by our server.
example: 
`  {"type"=>"conversationUpdate", "id"=>"FmXS***8dr", "timestamp"=>"2022-10-19T09:55:11.6000543Z", "serviceUrl"=>"https://webchat.botframework.com/", "channelId"=>"webchat", "from"=>{"id"=>"2d0f87a3-*****-****-2b8d0d63e195"}, "conversation"=>{"id"=>"*********-us"}, "recipient"=>{"id"=>"**@**", "name"=>"*******"}, "membersAdded"=>[{"id"=>"*******@Ws1BySAScKo", "name"=>"*******"}, {"id"=>"2d0f87a3-******-****-2b8d0d63e195"}], "locale"=>"en-US", "channel_uuid"=>"c5ee942f-**********-fb04f3fb7d16"} `

> serviceUrl = "https://webchat.botframework.com/"
> conversationId = "*********-us"
> memberId = "2d0f87a3-*****-****-2b8d0d63e195"

Calling Get conversation member to get the member detail:
Request: 
`{serviceUrl}/v3/conversations/{conversationId}/members/{memberId}`

Earlier Response:
`
{
  id: {memberId},
  userPrincipalName: <<>>,
  givenName: <<>>,
  surname: <<>>,
...
}
`
Latest response(only memberId) :
`
{
  id: {memberId}
}
`
Can you provide us with why API is giving a different response?
Any additional params we have to pass to get the earlier response back?

**Comment by Meghana-MSFT** [comment]
We are checking this issue, we will get back to you.

**Comment by Meghana-MSFT** [comment]
Engineering team has checked the get-member and get-members APIs, in multiple environments, and they return full user information. 
Could you please share the below details with us to check further

1. Are you facing this issue consistently or is it a onetime issue?
2. Can you please share conversationId, timestamp, userId, tenantid.

**Comment by Chang025** [comment]
@Meghana-MSFT - Now, we are receiving all the details needed in the get members API.
Thanks for the update.
