### ISSUE TITLE
GetTeamsConversationMembersAsync() is obsulete

### ISSUE THREAD

**Issue by tsahi** [MicrosoftDocs/msteams-docs#727]
The `GetTeamsConversationMembersAsync()` method used in the .NET code example is marked with the ObsoleteAttribute, with the message `"Use IConversations.GetConversationMembersAsync method instead. AsTeamsChannelAccount method can then be used to get extended properties."` The code example should be updated accordingly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f16f5795-7015-3a4e-2e64-d08d4a6be78d
* Version Independent ID: 6f8a9a3a-33c9-acc5-83d8-7645373bee3d
* Content: [Get context for your bot - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/bots/bots-context)
* Content Source: [msteams-platform/concepts/bots/bots-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/bots/bots-context.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by clearab** [comment]
@lokimeyburg Can you assist with an updated code sample for this?

**Comment by clearab** [comment]
updated

**Comment by tsahi** [comment]
The code example was fixed, but the line above it still says, "Call `GetTeamsConversationMembersAsync` using `Team.Id` to return a list of user IDs."

**Comment by clearab** [comment]
Thanks for pointing that out, will be fixed in the next publish.
