### ISSUE TITLE
Can I create messaging extensions without the parameters?

### ISSUE THREAD

**Issue by the-Dust** [MicrosoftDocs/msteams-docs#728]
Hi! Can anybody tell, is it possible to create action messaging extension without any parameters and thus without need to submit it? I just want to click on my app in the "More actions" menu like this
![59105294-bb9e3580-8944-11e9-8702-0b80d54aa102](https://user-images.githubusercontent.com/20787804/59674811-14878c80-91d5-11e9-8001-73bf7995cadf.png)
and then see my chat again without any modal windows (while the activity is sending to my bot). And then I want to return a ComposeExtensionAttachment and insert it into a message.
Any help appreciated

**Comment by Wajeed-msft** [comment]
Currently, this is not supported. When you Initiate actions with messaging extensions it always opens up Task Module.

**Comment by Wajeed-msft** [comment]
As long as you make _fetchTask=false_, and provide no parameters, it should execute the action directly without launching task module.

Here is sample command:
```
         {
          "id": "addTodo",
          "description": "Create a To Do item",
          "title": "Create a To Do",
          "fetchTask": false,
          "type": "action",
          "context": [ "message" ]
        }
```
Please let us know if you need any help.

**Comment by the-Dust** [comment]
@Wajeed-msft Thank you, now it works!
