### ISSUE TITLE
Link unfurling docs need to be updated

### ISSUE THREAD

**Issue by lokimeyburg** [MicrosoftDocs/msteams-docs#7286]
Most unfurled links are for Adaptive Cards, yet the link unfurling documentation does a poor job at explaining the requirements and constraints of returning Adaptive Cards when it comes to link unfurling.

👉 https://learn.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?tabs=dotnet

1. Can we add a note that mentions that only Adaptive Cards v1.3 and earlier is supported in link unfurling? This took me half an hour to figure out and was quite painful.
2. Can we mention that the response from the bot should include a "preview" property? This took another half an hour to figure out.
3. Can we update our samples to please use Adaptive Cards and not Hero cards? Seems wrong that we tell our app developers to use Adaptive Cards, but our samples only use Hero cards (which we generally have been trying to move away from)
4. Can we update the image being used in the documentation to show an Adaptive Card? We haven't defaulted to showing the 'preview' card for almost 2 years and yet this is what we're showing in the docs.

```
    handleTeamsAppBasedLinkQuery(context, query) {
        const attachment = CardFactory.adaptiveCard(adaptiveCards.adaptiveCardForTabStageView(query.url));
        attachment.preview = {
            content: {
              title: "{titleString}",
              text: "{textString}",
              images: [
                {
                  url: "{previewImageURL}",
                },
              ],
            },
            contentType: "application/vnd.microsoft.card.thumbnail",
        }

        const result = {
          attachmentLayout: 'list',
          type: 'result',
          attachments: [attachment],
          responseType: "composeExtension"
        };
    
        const response = {
          composeExtension: result
        };

        return response;
    }
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 59bbff2e-4b80-f980-2ade-7c7a7950801e
* Version Independent ID: e837e1fd-ec0c-2d6f-b0db-b76cb2d268a4
* Content: [Link unfurling - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?tabs=dotnet)
* Content Source: [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/messaging-extensions/how-to/link-unfurling.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **anclear**

**Comment by Nivedipa-MSFT** [comment]
@lokimeyburg - We will check and update it accordingly.

**Comment by ChetanSharma-msft** [comment]
Hello @surbhigupta12 - Please help us here to update the documentation.

**Comment by v-npaladugu** [comment]
Hi @Nivedipa-MSFT, request you to please share a new image as the shared image is not according to the standard (Image is blur) also please share the PR of the sample update so we can link it to the doc PR for our reference.

**Comment by Wajeed-msft** [comment]
@Nivedipa-MSFT - could you please share the better resolution image? 

@ChetanSharma-msft - Let's open separate issue to link to sample once we publish it.

**Comment by Nivedipa-MSFT** [comment]
@v-npaladugu - Please check below image.
![image](https://user-images.githubusercontent.com/92150070/203714061-2d27e1d9-dbee-4792-bc79-4db51b7c3819.png)

**Comment by Nivedipa-MSFT** [comment]
@v-npaladugu - C# and Nodejs samples for link unfurling are updated.
https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/msgext-link-unfurling

**Comment by ChetanSharma-msft** [comment]
We are facing issues in Java/Python samples for Adaptive Card in link unfurling.
So, we have informed engineering team and further discussion is going on with them.

**Comment by ChetanSharma-msft** [comment]
Raised a bug for it here: https://github.com/microsoft/BotBuilder-Samples/issues/3861

**Comment by v-npaladugu** [comment]
Hi @Nivedipa-MSFT,

Request you to please provide an Image for this issue as per the following review comments from SME:

"The following image is an example of link unfurling when an Adaptive Card link is pasted into the Teams compose message area, the link unfurls into a card:"... can we please pull a better card to show here? This card only has one image and minimal text. Lets use a richer card as an example here

**Comment by Nivedipa-MSFT** [comment]
@v-npaladugu - Please refer below image.

![image](https://user-images.githubusercontent.com/92150070/229481146-7c13dcf5-4587-455e-bad5-8bf51ae2c1a8.png)
