### ISSUE TITLE
Update TOC For TeamsFx SDK Page

### ISSUE THREAD

**Issue by MuyangAmigo** [MicrosoftDocs/msteams-docs#7289]
Right now TeamsFx SDK is nested under `Tools and SDKs/Teams Toolkit`, it makes more sense to put it under `Tools and SDKs` since it's a SDK and Teams Toolkit is a tool (Extension on Visual Studio and Visual Studio Code)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 40d33c5e-5f61-f2e4-d619-170fa263c626
* Version Independent ID: 40d33c5e-5f61-f2e4-d619-170fa263c626
* Content: [TeamsFx SDK - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-sdk)
* Content Source: [msteams-platform/toolkit/TeamsFx-SDK.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-SDK.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **v-amprasad**

**Comment by sayali-MSFT** [comment]
@surbhigupta12 -Could you please help us update the document?
`TeamsFx SDK` is nested under Tools and SDKs/Teams Toolkit, Could you please put it under `Tools and SDKs`.

Document-https://learn.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-sdk

![Screenshot 2022-10-21 184830](https://user-images.githubusercontent.com/93527375/197205157-5ba44e58-9c71-4a9c-ab64-c0b79cb5ce68.png)
