### ISSUE TITLE
Document how Action.Submit works

### ISSUE THREAD

**Issue by aosolis** [MicrosoftDocs/msteams-docs#7298]
This page describes the Teams-specific variants of Action.Submit (for example https://learn.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-actions?tabs=json#adaptive-cards-with-messageback-action). But it glosses over how a regular Action.Submit works, with only a link to this page: https://adaptivecards.io/explorer/Action.Submit.html.

We need a better explanation of how Action.Submit works:
- how is the data in the card sent to the bot
- what the payload received by the bot looks like
- how is the bot expected to respond (time limits, etc.)

Also, the information in the following section of a different page: https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-messages?tabs=dotnet#form-completion-feedback
should be incorporated into that discussion. It is out of place in its current location.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 672a763d-189b-8ba0-f66e-c07f1dc0a962
* Version Independent ID: 1ac7a9bd-138b-3bf8-60a3-1842d87371fd
* Content: [Add card actions in a bot - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-actions?tabs=json)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-actions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/task-modules-and-cards/cards/cards-actions.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by sayali-MSFT** [comment]
@aosolis - We are looking into this we will get back to you soon.

**Comment by sayali-MSFT** [comment]
@aosolis - Could you please confirm if the below changes look fine or do we need to add more information?

@surbhigupta12 - Could you please help us to update the document?
Document-https://learn.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-actions?tabs=json#adaptive-cards-actions

Add the below title as new point in Adaptive Cards actions section like other action.

Add the Title-**Adaptive Cards with Submit action**

If you look at [Action.Submit](https://adaptivecards.io/explorer/Action.Submit.html) in the schema, you will see that a submit action’s data property can be either a string or an object.A submit action has two possible behaviors that correspond to these two possible data types.
A string submit action automatically sends a message from the user to the bot that shows up in the client application’s conversation history as though the user typed the message and sent it manually. An object submit action automatically sends an invisible message from the user to the bot that contains hidden data. 
The reason behind the name “submit action” becomes clear when an Adaptive Card contains input fields. A submit action is used to “submit” the information provided in the input fields by combining that information with anything already in the data property and sending it to the bot.

When using the Bot Framework, clicking on a submit action will send a Bot Framework message activity to the bot. A string submit action will simply transfer its string data into the activity’s text property. An object submit action has a somewhat more complicated process of populating the activity’s value property while leaving the text property empty. Each input field in the object submit action’s card will be represented as a property of that value object and the properties will be named according to each input field’s ID. Any properties already in the object submit action’s data property will also be present in the value object. 

Here’s what it might look like when you click on a string submit action:
![Bot_Em](https://user-images.githubusercontent.com/93527375/199667601-a3a33fee-7c97-4b18-9ed5-7f3ab73c8a2b.png)
The JSON for that card might look like this (notice the string assigned to the submit action’s data property:
`{
  "$schema": "https://adaptivecards.io/schemas/adaptive-card.json",
  "type": "AdaptiveCard",
  "version": "1.0",
  "actions": [
    {
      "type": "Action.Submit",
      "title": "Click here to say \"Hello\"",
      "data": "Hello"
    }
  ]
}`
