### ISSUE TITLE
notifyFailure doesn’t show the custom message being passed - need doc updates

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#7310]
> If your application doesn't load, you can call app.notifyFailure({reason: app.FailedReason.Timeout, message: "failure message"}); to let Teams know about the failure and, optionally, provide a failure message. An error screen is shown to the user. The following code shows the enumeration that defines the possible reasons you can indicate for the application's failure to load:

notifyFailure doesn't show custom message. Documentation needs to be updated. 

Ref: https://github.com/OfficeDev/microsoft-teams-library-js/issues/1365

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f7398066-a52e-7db2-c65c-9f1cf5796077
* Version Independent ID: 2dd1c170-fd52-0c27-1b9a-3664ca9f83c4
* Content: [Create a content page - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/content-page?tabs=teamsjs-v2)
* Content Source: [msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/tabs/how-to/create-tab-pages/content-page.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Nivedipa-MSFT** [comment]
@surbhigupta12 - Could you please help here to add a note saying that "notifyFailure doesn't show custom message."
Note need to be added here: https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/content-page?tabs=teamsjs-v2#show-a-native-loading-indicator
