### ISSUE TITLE
[Link unfurling] When multiple apps are registered with the same domain in their respective manifest, which app's unfurled result will be returned?

### ISSUE THREAD

**Issue by sugargx** [MicrosoftDocs/msteams-docs#7326]
Hi team,
I am trying to do link unfurling function in an app according to doc. But currently i have a question, when multiple apps are registered with the same domain in their respective manifest (e.g. teams.microsoft.com.) and are added to the current chat, which app will respond to the unfurling result? 

Is there some strategy to ensure the correctness of link unfurling? It seems that the link unfurling response in this case is unpredictable.

The attached image shows the configuration in the manifest file of my app.
![image](https://user-images.githubusercontent.com/33537322/198223511-5b37e1c8-ec0e-4c7c-9d60-a15b8df6d344.png)
FYI. "teams.microsoft.com" domain is very common because it is the domain name specified by Teams' deep link.

Looking forward to your response, thanks!

**Comment by Meghana-MSFT** [comment]
We have tried by this at our end, we also see there is no specific pattern of which app's unfurled result it is. We are checking internally and get back to you.

**Comment by sugargx** [comment]
> We have tried by this at our end, we also see there is no specific pattern of which app's unfurled result it is. We are checking internally and get back to you.

Hi @Meghana-MSFT, is there any more progress on the answer to the question please? Thanks a lot!

**Comment by Meghana-MSFT** [comment]
@sugargx - We are still checking with the team internally, please be assured that I will post here as soon as I have an update. Thanks.

**Comment by Meghana-MSFT** [comment]
@sugargx - Engineering team has confirmed that currently multiple apps registering the same domain is not supported. Two apps registering the same domain is not deterministic with regard to which app will be used. So, we are suggested to avoid that.

**Comment by Meghana-MSFT** [comment]
We are closing this issue, please feel free to reach out to us if you need help. Thank you.
