### ISSUE TITLE
Cannot access to "Try the UI library (playground)" page

### ISSUE THREAD

**Issue by qscn** [MicrosoftDocs/msteams-docs#7328]
I cannot access to [Try the UI library (playground)](https://dev-int.teams.microsoft.com/storybook/main/index.html) page.

![Screenshot_20221027180425](https://user-images.githubusercontent.com/26407239/198256287-3b404112-c4fa-4398-85f0-f6dc1809fef6.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e739fdd6-8835-cfcd-f25c-1b4c7cb42afa
* Version Independent ID: 3bbef1d2-6427-0c7f-bfe2-57bf016629da
* Content: [Designing your app with UI templates - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/design/design-teams-app-ui-templates)
* Content Source: [msteams-platform/concepts/design/design-teams-app-ui-templates.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/design/design-teams-app-ui-templates.md)
* Service: **msteams**
* GitHub Login: @heath-hamilton
* Microsoft Alias: **lajanuar**

**Comment by Prasad-MSFT** [comment]
Hi @qscn - Thanks for reporting this.
Hi @surbhigupta12 - In this [document](https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/design/design-teams-app-ui-templates#microsoft-teams-ui-library) in [Microsoft Teams UI Library](https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/design/design-teams-app-ui-templates#microsoft-teams-ui-library) section the link [Try the UI library (playground)](https://dev-int.teams.microsoft.com/storybook/main/index.html) page is showing this above-mentioned message on clicking.
Could you please help here to update the doc accordingly?

**Comment by v-spharish** [comment]
@Prasad-MSFT The link is broken in the sample itself, and the discussion is on-going. Here is the link of the issue raised. Please refer. Playground link present in Readme is broken #149

**Comment by surbhigupta12** [comment]
> @Prasad-MSFT The link is broken in the sample itself, and the discussion is on-going. Here is the link of the issue raised. Please refer. Playground link present in Readme is broken [OfficeDev/microsoft-teams-ui-component-library#149](https://github.com/OfficeDev/microsoft-teams-ui-component-library/issues/149)

@ydogandjiev, please help resolve this.

**Comment by surbhigupta12** [comment]
This issue is resolved through PR #7730
