### ISSUE TITLE
Adaptive card values not persisting after submit

### ISSUE THREAD

**Issue by roalexan** [MicrosoftDocs/msteams-docs#733]
Say I have a Teams Bot that responds with an adaptive card with an input element, such as Input.Text (although I see this behavior with any of the input elements). When running in Teams, after the user types something and submits, I see that the adaptive card clears out the text. Is there a way to not have the text get cleared out and just leave what the user typed?

```javascript
const { ActivityHandler, CardFactory } = require('botbuilder');
const InputCard = require('../resources/InputCard.json');

class TestBot extends ActivityHandler {
    constructor(userState) {
        super();
        this.userState = userState;
        this.onMembersAdded(async (context, next) => {
            await next();
        });
        this.onMessage(async (context, next) => {
            await context.sendActivity({
                attachments: [CardFactory.adaptiveCard(InputCard)]
            });
            await this.userState.saveChanges(context);
            await next();
        });
    }
}

module.exports.TestBot = TestBot;
```

```javascript
{
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "type": "AdaptiveCard",
  "version": "1.0",
  "body": [
    {
      "type": "Input.Text",
      "id": "message"
    }
  ],
  "actions": [
    {
      "type": "Action.Submit",
      "title": "OK"
    }
  ]
}
```

**Comment by Gousia-MSFT** [comment]
@roalexan Action.Submit submits the details entered by the user in the Text field to the Bot. You can get those values in `activity.Value`. However once the details are submitted the values in the input fields disappear.

**Comment by roalexan** [comment]
Thanks. Yes, I have no problem getting the values. The problem is with the user experience. It does not seem correct to remove the settings after hitting OK. What I need help with is how to either not remove the settings or restore the settings. Attached are a few screenshots showing what I'm talking about.

From Teams (note the settings are gone after hitting ok):

![image](https://user-images.githubusercontent.com/9354835/59931851-e5129300-9413-11e9-98f7-6ccf7f1a7a22.png)

BTW, here's what it looks like from the Bot Emulator (note the setting remain, which is the behavior I'm trying to achieve in Teams):

![image](https://user-images.githubusercontent.com/9354835/59931839-df1cb200-9413-11e9-9f65-d50d3a632950.png)

**Comment by roalexan** [comment]
And here's another view of what I'm talking about, this time using an Input.ChoiceSet.

From Teams:

![image](https://user-images.githubusercontent.com/9354835/59933257-19d41980-9417-11e9-801e-345c3962c69f.png)


From Bot Emulator:

![image](https://user-images.githubusercontent.com/9354835/59933209-fdd07800-9416-11e9-9526-a0229a1f16d6.png)

**Comment by Wajeed-msft** [comment]
Yes that is by design. It's very similar to how HTML forms work. No current plans to change this behaviour.

There is an option to update your card when user click on submit action as explained here https://github.com/OfficeDev/BotBuilder-MicrosoftTeams/issues/192#issuecomment-494316723.
