### ISSUE TITLE
Document how bot icons work

### ISSUE THREAD

**Issue by aosolis** [MicrosoftDocs/msteams-docs#7335]
Please document 
- where the bot icon comes from, for store, LOB and sideloaded apps.
- how to update it
- how long the existing bot icon is cached
Users and developers are confused about this, and we get bug reports that end up being customer error (which suggests we're doing something wrong, but let's start by documenting the current state).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3af8496d-46be-a691-11e1-16734f71f891
* Version Independent ID: be0ff3e1-8bef-5ca7-8d9c-566e89e3fd41
* Content: [Bots in Microsoft Teams - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/bots/what-are-bots)
* Content Source: [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/bots/what-are-bots.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **anclear**

**Comment by sayali-MSFT** [comment]
We are looking into this and update the document accordingly.

**Comment by sayali-MSFT** [comment]
@aosolis - Could you please confirm if the below changes look fine or do we need to add more information?
@surbhigupta12 -Could you please help us to update the document?
Please add the point after the GIF image in below document-
https://learn.microsoft.com/en-us/microsoftteams/platform/bots/what-are-bots
If your app has a bot or message extension, your icons also will be included in your [Microsoft Azure Bot Service registration].(https://learn.microsoft.com/en-us/azure/bot-service/bot-service-manage-overview?view=azure-bot-service-4.0&tabs=userassigned#settings)

**Comment by ChetanSharma-msft** [comment]
Hello @v-ypalikila - We are checking with engineering team for the above points and let you know, so that we can update the documentation accordingly.

**Comment by ChetanSharma-msft** [comment]
Hello @surbhigupta12 - Please help to update the documentation like below:

**1) Where the bot icon comes from, for store, LOB and sideloaded apps and how to update it =>** 

There are three ways by which we can add/update the bot icon and other bot related information:
**A)** From your [bot settings in Azure](https://learn.microsoft.com/en-us/azure/bot-service/bot-service-manage-overview?view=azure-bot-service-4.0&tabs=userassigned#settings)
 
If you update your bot icon from the bot settings in Azure, this updates the conversation bot icon and the bot icon that displays when you send your new message from the Compose Area in Teams where you bot has installed.
 
This does not update the bot's 'profile' and/or app image. These must be updated from a new manifest.
**B)** Using app [manifest ](https://learn.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema#icons)used for loading a custom app.
 
**C)** Once you uploaded the app in Teams Admin Center, you can update the bot icon through the [Teams admin center](https://learn.microsoft.com/en-us/microsoftteams/customize-apps#customize-an-app).
 3) How long the existing bot icon is cached: We are not sure about this, Could you please provide your input for this? Also, could you please review above 2 points and share your thoughts?
 
**2) How long the existing bot icon is cached =>** Bot Icon is cached until user signs out and sign in again.
