### ISSUE TITLE
Configure environment variables - names are wrong

### ISSUE THREAD

**Issue by hi1uo** [MicrosoftDocs/msteams-docs#735]
They should be like the follow:

MICROSOFT_APP_ID
MICROSOFT_APP_PASSWORD

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c08b13b0-8c05-c6f1-c3fa-a58b67ae0123
* Version Independent ID: 14116a6d-f66b-a81b-9808-cf6db771325f
* Content: [Host your Node based Teams app in Azure - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/get-started/get-started-nodejs-in-azure#feedback)
* Content Source: [msteams-platform/get-started/get-started-nodejs-in-azure.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/get-started/get-started-nodejs-in-azure.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by clearab** [comment]
Thanks! This will be fixed with the next release (6/21).
