### ISSUE TITLE
"Task Module from your tab" docs are out of date. Referencing deprecated code.

### ISSUE THREAD

**Issue by lokimeyburg** [MicrosoftDocs/msteams-docs#7358]
The [Use Task Modules from your tab](https://learn.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/task-modules/task-modules-tabs) docs are out of date. They refer to using the `task` module in the SDK, but when you go to the SDK reference docs, it says this is now deprecated and you should be using the `dialog` module instead (as of v2): https://learn.microsoft.com/en-us/javascript/api/@microsoft/teams-js/tasks?view=msteams-client-js-latest#@microsoft-teams-js-tasks-starttask

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f40d5208-a7ae-330a-1365-9b774ca9dcaf
* Version Independent ID: a44e2980-4ed7-636c-0141-8b1e944971bb
* Content: [Use Task Modules in Microsoft Teams tabs - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/task-modules/task-modules-tabs)
* Content Source: [msteams-platform/task-modules-and-cards/task-modules/task-modules-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/task-modules-and-cards/task-modules/task-modules-tabs.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by sayali-MSFT** [comment]
@lokimeyburg - Thanks for reporting your issue.
We will check it and update the document accordingly.

**Comment by sayali-MSFT** [comment]
@surbhigupta12 -Could you please help us to update the document-
Please add the below code in **Use task modules in tabs** like below screen In V2 section add below code and V1 Section add the code which is already present in document-
![Tabs](https://user-images.githubusercontent.com/93527375/199018179-19486f6b-c49b-4429-8068-2bce91ce1f05.png)

```
 microsoftTeams.dialog.open(
   urlDialogInfo: UrlDialogInfo, 
   submitHandler?: DialogSubmitHandler, 
   messageFromChildHandler?: PostMessageChannel
): void])


   microsoftTeams.dialog.submit(
    result?: string | any,
    appIds?: string | string[]
): void;
```

Document-https://learn.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/task-modules/task-modules-tabs

2.In the below section also need to update like above screen.In V2 section add the below code-
```
let taskInfo = {
    title: null,
    height: null,
    width: null,
    url: null,
    card: null,
    fallbackUrl: null,
    completionBotId: null,
};

taskInfo.url = "https://contoso.com/teamsapp/customform";
taskInfo.title = "Custom Form";
taskInfo.height = 510;
taskInfo.width = 430;
dialogResponse = (dialogResponse) => {
        console.log(`Submit handler - err: ${dialogResponse.err}`);
        alert("Result = " + JSON.stringify(dialogResponse.result) + "\nError = " + JSON.stringify(dialogResponse.err));
    };

 microsoftTeams.dialog.open(taskInfo, dialogResponse);
```

Document-https://learn.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/task-modules/task-modules-tabs#example-of-invoking-a-task-module


@lokimeyburg -We are adding V2 code in the document.

**Comment by sayali-MSFT** [comment]
@surbhigupta12 -Could you please help us to update the document?
