### ISSUE TITLE
Integrate TeamsFX with AAD B2C - Blazor 

### ISSUE THREAD

**Issue by chulla** [MicrosoftDocs/msteams-docs#7361]
I would like to reopen this problem  ( issues 3143 )

can we also please see if we can offer a detailed write-up on how to integrate TeamsFX with AAD B2C?

I have a blazor server application with the Azure AD B2C identity system... I have followed this manual but it is only compatible with Azure AD!!! 

https://github.com/OfficeDev/TeamsFx/blob/78cdb5899c039dc228e78ce62e6d69731de69051/docs/fx-core/using-existing-aad.md

I need to allow my App (Blazor) to be ported to Teams without changing the B2C system.

The ultimate goal would be to be able to login with my Application registered in Azure with B2C and allow access to the access_token to then query a protected Web API...

right now i have this with errors :

`await teamsUserCredential.LoginAsync(_scopeApi);`

`var token_api = await teamsUserCredential.GetTokenAsync(new TokenRequestContext(new string[] { _scopeApi }), new System.Threading.CancellationToken());`

How would it be possible? Thank you!!

**Comment by sayali-MSFT** [comment]
@chulla - Thanks for reporting your issue.
We will investigation this issue and get back to you . Also update the document accordingly.

**Comment by chulla** [comment]
I have a Blazor Server app that is already integrated with the Azure AD B2C identity system.. ( Web App )

I have successfully created a tab app in teams using TeamsFX ( Toolkit Teams in Visual Studio 2022) ..... my problem is that I want to integrate the Azure AD B2C identity system in my Teams app... to get the access token so I can query an API securely to the data with the token... But I can't do it... 

I've seen that there are a manual on how to integrate the Azure AD identity system... but not Azure AD B2C.. 

Could you help me.. Thanks

**Comment by sayali-MSFT** [comment]
@chulla -Thanks for providing more information, We are checking it from our end and let you know.

**Comment by chulla** [comment]
I think it is a fundamental functionality so that thousands of companies can offer a quality identity system such as Microsoft Azure AD B2C in their  Microsoft team applications.

**Comment by sayali-MSFT** [comment]
@chulla -We are checking on TeamsFX with AAD B2C documentation internally. We will raise bug to update it accordingly if there is no documentation available. 
Thanks!
