### ISSUE TITLE
Adaptive Card TaskInfo.card section is incoherent

### ISSUE THREAD

**Issue by tomlm** [MicrosoftDocs/msteams-docs#7365]
Please rewrite this section and describe the actual payload the is sent and expected in reply.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f40d5208-a7ae-330a-1365-9b774ca9dcaf
* Version Independent ID: a44e2980-4ed7-636c-0141-8b1e944971bb
* Content: [Use Task Modules in Microsoft Teams tabs - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/task-modules/task-modules-tabs)
* Content Source: [msteams-platform/task-modules-and-cards/task-modules/task-modules-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/task-modules-and-cards/task-modules/task-modules-tabs.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Nivedipa-MSFT** [comment]
@tomlm - We will check and update it accordingly.
