### ISSUE TITLE
Link returns 404

### ISSUE THREAD

**Issue by matthiasdilger** [MicrosoftDocs/msteams-docs#7366]
Section "Build a landing page for subscription management" contains broken link to "first party license management"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fd29bf73-3680-24a6-5c05-76d06c1e40c1
* Version Independent ID: 45035997-0a41-8f4b-575d-ea5ae8ef4bab
* Content: [Include a SaaS offer with your app - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer#build-a-landing-page-for-subscription-management)
* Content Source: [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md)
* Service: **msteams**
* GitHub Login: @heath-hamilton
* Microsoft Alias: **surbhigupta**

**Comment by Prasad-MSFT** [comment]
Hi @surbhigupta12 - We could see in this [doc](https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer#build-a-landing-page-for-subscription-management) the link [first party license management](https://learn.microsoft.com/en-us/platform/concepts/deploy-and-publish/appsource/prepare/first-party-license-management) is broken and we could not find proper link.
Could you please help here to update?
