### ISSUE TITLE
Unable to sign in Azure deployment in VS Code

### ISSUE THREAD

**Issue by azzurolilc** [MicrosoftDocs/msteams-docs#737]
Using Mac with Chrome.
After clicking on the account I want to sign in with from the Sign in to Azure page, I was redirected to a page:
"The resource you are looking for has been removed, had its name changed, or is temporarily unavailable."
And Azure deployment get stuck in "Waiting for azure sign-in"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c08b13b0-8c05-c6f1-c3fa-a58b67ae0123
* Version Independent ID: 14116a6d-f66b-a81b-9808-cf6db771325f
* Content: [Host your Node based Teams app in Azure - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/get-started/get-started-nodejs-in-azure)
* Content Source: [msteams-platform/get-started/get-started-nodejs-in-azure.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/get-started/get-started-nodejs-in-azure.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by azzurolilc** [comment]
When I do not choose an already "signed-in" account it won't redirect, but when I had to re-enter user login info it works.

**Comment by billbliss** [comment]
This sounds like an Azure single-sign-on issue. I think this is the correct place to post the question - I opened an issue for you. As the Teams team we have no idea why this doesn't work.

https://github.com/microsoft/vscode-azure-account/issues/144
