### ISSUE TITLE
The link to "Try the UI Library" is broken or the toolkit is down on the Designing your Microsoft Teams app with UI templates page

### ISSUE THREAD

**Issue by BrendanAndrade** [MicrosoftDocs/msteams-docs#7382]
On the page https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/design/design-teams-app-ui-templates, the link to "Try the UI Library" is broken or the toolkit is down. The link currently directs to https://dev-int.teams.microsoft.com/storybook/main/index.html which gives the error 

`This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>PublicAccessNotPermitted</Code>
<Message>Public access is not permitted on this storage account. RequestId:9b8f656e-f01e-000b-5880-ed1dbb000000 Time:2022-10-31T23:26:34.8620162Z</Message>
</Error>`
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e739fdd6-8835-cfcd-f25c-1b4c7cb42afa
* Version Independent ID: 3bbef1d2-6427-0c7f-bfe2-57bf016629da
* Content: [Designing your app with UI templates - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/design/design-teams-app-ui-templates)
* Content Source: [msteams-platform/concepts/design/design-teams-app-ui-templates.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/design/design-teams-app-ui-templates.md)
* Service: **msteams**
* GitHub Login: @heath-hamilton
* Microsoft Alias: **lajanuar**

**Comment by Prasad-MSFT** [comment]
Thanks @BrendanAndrade  for bringing this up. There is already a doc enhancement request raised for this issue, where we mentioned documentation team to update it. Please refer [this](https://github.com/MicrosoftDocs/msteams-docs/issues/7328) thread for further updates.
Thanks!
