### ISSUE TITLE
Simple POST to teams incoming webhook url is not working

### ISSUE THREAD

**Issue by dineshba** [MicrosoftDocs/msteams-docs#7383]
We have a below go code to send notifications to teams channel. It was working fine for sometime. For the past 4 weeks, if we send 10 message, only 3-5 are getting delivered. That is also random.

And to make things worse, the `response.StatusCode` is always 200. And no code change for past 3 months. Could someone help to understand how to fix this issue ?

 
```go
postBody := Message{
    Title:      "title",
    TextFormat: "markdown",
    Text:       "summary",
}

jsonValue, err := json.Marshal(postBody)
if err != nil {
    return fmt.Errorf("error on making request to teams webhook: %s", err)
}

req, err := http.NewRequest("POST", "teamsUrl-incoming-webhook-url", bytes.NewBuffer(jsonValue))
if err != nil {
    return fmt.Errorf("error on creating post request to teams: %s", err.Error())
}
req.Header.Set("Content-Type", "application/json")

resp, err := http.DefaultClient.Do(req)
if err != nil {
    return fmt.Errorf("error on making request to teams webhook for message %s: %s", title, err)
}
defer resp.Body.Close()

if resp.StatusCode == 200 {
    fmt.Printf("Sucessfully sent '%s' message to teams\n", title)
}	
```

I tried to print the response body and response headers
```go
v, _ := json.Marshal(resp.Body)
fmt.Printf("Response body: %s\n", string(v))
fmt.Printf("Response Header: %+v\n", resp.Header)
```

Response body is empty and response headers doesn't indicate any failures

## Below is the screenshot of the incoming webhook we are using

![image](https://user-images.githubusercontent.com/13361187/199219700-b10fb09f-7ca3-4f20-823a-a53f1684825e.png)

Please let me know if need any details from me to debug this issue.

**Comment by sayali-MSFT** [comment]
@dineshba - Thanks for reporting your issue.
We will investigation this issue and get back to you. 
Meanwhile if you get any error log please share with us.

**Comment by dineshba** [comment]
There is no error. Response from the api is 200 and response body is empty.

Response header contains request-id. See if this request ids are useful to debug the issue
```
Request-Id:[60cf0e31-1e56-b36e-f4cc-075e365d6e74]
Request-Id:[d589550c-ddb2-1b91-ed1c-19099f662a19]
```

**Comment by Yuqing-cat** [comment]
Blocked by the same issue. 
We implemented a scheduler to call webhook url and send simple text message daily to Team Channel last week. The response is always 200, but the message doesn't show up yesterday(Thursday)  and Tuesday.
No code change at all.

**Comment by sayali-MSFT** [comment]
@dineshba ,@Yuqing-cat - We are checking this with engineering team and get back to you

**Comment by sayali-MSFT** [comment]
@dineshba - We have raised the ICM for this issue, We will inform you once issue is resolved.

**Comment by sayali-MSFT** [comment]
@dineshba -Are you seeing the notifications on team's web or getting issue on both Web and Desktop?

**Comment by dineshba** [comment]
I am able to see the issue happening again after I created this issue. Closing for now.
