### ISSUE TITLE
Issue while importing an existing/creating app to developer portal

### ISSUE THREAD

**Issue by amoyalan20** [MicrosoftDocs/msteams-docs#7384]
Getting the below error,
**Package Loading Failure
Provided add-in package was not understood. Please, make sure that the file being submitted is a valid Office add-in package.**

![image](https://user-images.githubusercontent.com/73281779/199252184-684ed191-4ae1-4e2d-afea-db95000a32b9.png)

and while creating a new app also have this same issue on loading the packages. "Failed to download app "error message is displaying under the "App Package" tab .please find the below screenshot for reference.

![image](https://user-images.githubusercontent.com/73281779/199428815-9e1775c1-a9b9-45e6-88b4-c6c736e42b54.png)

Can you guide how to import an existing app / create a new app from the developer portal?

**Comment by k96payne** [comment]
We are also experiencing this issue

**Comment by Meghana-MSFT** [comment]
@amoyalan20 - 

1. "Provided add-in package was not understood. Please, make sure that the file being submitted is a valid Office add-in package." error comes if your app package has more than 3 files. App package should contain only manifest.json, outline and color files. Please check if you are adding anything extra in the app package. If you still get the error in developer portal, please share your manifest with us and remove any PII.
2. We are also getting same issue while trying to create an app. We are checking this internally and get back to you.

**Comment by k96payne** [comment]
This error is showing up for us on app exporting as well. When uploading it to the validator, it fails validation. 

<img width="592" alt="image" src="https://user-images.githubusercontent.com/26599888/199278505-88445b7a-e4d7-4756-8511-df977bf062b4.png">

<img width="1781" alt="image" src="https://user-images.githubusercontent.com/26599888/199278795-01cea440-5c31-4932-9abc-1e5661d55a37.png">

**Comment by Meghana-MSFT** [comment]
1. Yes, we are also able to repro this issue. Engineering team has confirmed that this error comes from the latest manifest version 1.15.  They are working on updating the service, the error should be gone after that.
2.   Team is looking into it, I will get back to you once we have an update from the team.

**Comment by amoyalan20** [comment]
@Meghana-MSFT 
1. I checked app package and validated the files, Now the manifest import works for me. Thanks @Meghana-MSFT .
But noticed few findings:

- App package still shows error

![image](https://user-images.githubusercontent.com/73281779/199479406-f67d5b3c-21d5-4622-9339-28f54c53a81d.png)

- Preview in teams not working, getting a error message below.

![image](https://user-images.githubusercontent.com/73281779/199479575-35791c9a-b481-4b30-9984-3a5d5d0fb45c.png)

2. Still have issue with create a App.

Can you guide to resolve the issues mentioned above?

**Comment by Meghana-MSFT** [comment]
1. Team is looking into app package - failed to download issue.
2. Can you please validate your app package through [developer portal](https://dev.teams.microsoft.com/tools) to understand why manifest parsing has failed
![image](https://user-images.githubusercontent.com/81138249/199481421-0dde4208-cefe-4d6b-94e2-ba0383f68fb5.png)

**Comment by amoyalan20** [comment]
@Meghana-MSFT 
By using the given link([developer portal](https://dev.teams.microsoft.com/tools)), it is showing the below screenshot and there are no any errors.

im getting the "Manifest parsing has failed" only while i click the "Preview in teams". Could you assist on this?



![image](https://user-images.githubusercontent.com/73281779/200247190-cf36d786-b297-48d2-ab88-994b9a3f6482.png)

**Comment by Meghana-MSFT** [comment]
Can you please share your manifest with us to check what the issue is?

**Comment by KarpMac** [comment]
We have the same issue in Developer Portal, need to update an application created via App Studio but are not able to publish an update, I get the same error
![image](https://user-images.githubusercontent.com/56383766/201911457-def5987b-f30a-4b21-af0a-93437fbb1f7f.png)

**Comment by Meghana-MSFT** [comment]
> > * Yes, we are also able to repro this issue. Engineering team has confirmed that this error comes from the latest manifest version 1.15.  They are working on updating the service, the error should be gone after that.
> > * Team is looking into it, I will get back to you once we have an update from the team.
> 
> 1. This has been fixed, Manifest 1.15 is supported now.
> 2. We have raised a bug for the same, we will keep you posted on the updates.

Issue 2 has been fixed. We have verified the fix in developer portal. Could you please check and confirm.
