### ISSUE TITLE
Adding a subject to a new conversation requires switching channels after entering some text on macOS

### ISSUE THREAD

**Issue by robrothwell** [MicrosoftDocs/msteams-docs#7387]
on macOS Teams 1.5.00.27260, this is how I have to add a subject to a new message:

1.  Start entering a new conversation as usual:

![Screen Shot 2022-11-01 at 5 00 56 PM](https://user-images.githubusercontent.com/116014924/199340798-7bd217c2-90b0-4973-8c96-2cac025638bd.png)

2.  Enter some text; there is still not option to enter a subject:

![Screen Shot 2022-11-01 at 5 01 08 PM](https://user-images.githubusercontent.com/116014924/199340852-0fb31076-4521-4cb0-9ffd-114f7d55a1ca.png)

3.  Switch to another channel and back again; now the option is there:

![Screen Shot 2022-11-01 at 5 01 49 PM](https://user-images.githubusercontent.com/116014924/199341009-99845735-320c-4053-bb84-f846720471d0.png)

**Comment by sayali-MSFT** [comment]
Hello @robrothwell, We are mainly responsible for Microsoft Teams app development related issues. 

For Microsoft Teams product issues/failures your tenant Admin can reach out to [Microsoft 365 Product Support](https://docs.microsoft.com/en-us/microsoft-365/admin/contact-support-for-business-products?view=o365-worldwide&tabs=online). 

For general questions about Microsoft Teams please post your question on [Microsoft Teams Community](https://answers.microsoft.com/en-us/msteams/forum).

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, please feel free to reopen it, if required.
