### ISSUE TITLE
Why adaptive card can't adapt to the width of message?

### ISSUE THREAD

**Issue by XimenaWang** [MicrosoftDocs/msteams-docs#739]
Hi team, why the adaptive can't adjust its width? I sent the card using the Bot, and it looks like this:
![image](https://user-images.githubusercontent.com/30890958/59999658-5ec69e80-9617-11e9-9ed9-aa9c530473d6.png)

How do I adjust the adaptive card so that it can fill the blank space of the message likes the Hero Card?
![image](https://user-images.githubusercontent.com/30890958/59999451-db0cb200-9616-11e9-83a6-44be7d31b2cc.png)

**Comment by Gousia-MSFT** [comment]
@XimenaWang Adaptive card width is managed by Microsoft Teams channel so that it renders well on all the device including mobile. Currently, there is no option to set the custom width to adaptive card.

**Comment by XimenaWang** [comment]
@Gousia-MSFT - Hi , so how can I adjust the width to be wider? I tried it in [Adaptive card Designer](https://messagecardplayground.azurewebsites.net/) , it works online , but failed in my .NET service of Bot.
can you give me some suggestions? thanks in advance!
![image](https://user-images.githubusercontent.com/30890958/60067497-af91d200-96bf-11e9-85aa-2f425ab16119.png)

**Comment by Gousia-MSFT** [comment]
@XimenaWang Adaptive cards width is managed by the Microsoft Teams channel and the user has no control on it. Currently, there is no option to set the custom width for an adaptive card in Microsoft Teams.

**Comment by stpeteparadox** [comment]
This is really a terrible restriction. Surely developers as Microsoft used Slack internally prior to the release of Teams? Please would you hire some of Slack's user experience specialists, because I have yet to see anyone from Microsoft provide their customers a reasonable explanation for this restriction. If Slack can do it, why on earth has Microsoft not been able to?

**Comment by XimenaWang** [comment]
@stpeteparadox Hi stpeteparadox , it seems that the adaptive card still can't adapt the width, you can take a try with O365ConnectorCard(https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference#office-365-connector-card ), it works well for me ^_^

**Comment by stpeteparadox** [comment]
Thanks @XimenaWang . That's good to know. 

My understanding is that O365ConnectorCard uses the legacy MessageCard format, but that Teams doesn't support the Hero Image property of that format. So in our use-case that won't work for us. 

Also, we don't want to go down the road of using something that the Teams team doesn't appear to be paying much attention to, whereas AdaptiveCards seem to have active, if separate, development--though it's really essential the Teams team keeps AdaptiveCard implementation across Teams up-to-date with the latest standard!

Maybe Microsoft could just acquire Slack and Dropbox and we could all truly move on with our lives :)
