### ISSUE TITLE
Information not consistent with Partner Center

### ISSUE THREAD

**Issue by matthiasdilger** [MicrosoftDocs/msteams-docs#7391]
Section "Manage license for third party apps in Teams" includes reference to license management inside Teams " Yes, I would like Microsoft to manage customer licenses on my behalf." and shows this screenshot:

<img width="600" alt="saas-isvpilot" src="https://user-images.githubusercontent.com/5625718/199408092-e2504b67-f1d5-47b9-ab1c-9426bd9a4101.png">

The current partner center does not include this setting. When will this be available? If I release a transactable Saas solution now, will  I be able to turn this setting on later, so I don't have to wait for it?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fd29bf73-3680-24a6-5c05-76d06c1e40c1
* Version Independent ID: 45035997-0a41-8f4b-575d-ea5ae8ef4bab
* Content: [Include a SaaS offer with your app - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer#manage-license-for-third-party-apps-in-teams)
* Content Source: [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md)
* Service: **msteams**
* GitHub Login: @heath-hamilton
* Microsoft Alias: **surbhigupta**

**Comment by Prasad-MSFT** [comment]
Hi @matthiasdilger - Thanks for reporting this. We will check with engineering team and will get back to you.

**Comment by ChetanSharma-msft** [comment]
Hello @surbhigupta12 - Could you please check and help us here to update the documentation?

**Comment by surbhigupta12** [comment]
Issue resolved
