### ISSUE TITLE
Linebreaks

### ISSUE THREAD

**Issue by th0ger** [MicrosoftDocs/msteams-docs#740]
Linebreaks (\r\n) with markdown  are not implemented consistently across channels.

1 linebreak gives 1 linebreak in Emulator/Web, but ignored in Teams.
2 linebreaks gives 1 paragraph in Emulator/Web, but 1 linebreaks in Teams.

I believe the typical markdown practice is:
1 linebreak is ignored, and 2 linebreaks gives paragraph.
Here documented for DevOps:
https://docs.microsoft.com/en-us/azure/devops/project/wiki/markdown-guidance?view=azure-devops#paragraphs-and-line-breaks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83bc8e1b-8c2c-4640-4cf0-9f15d0d036ee
* Version Independent ID: ceae0ed1-6d77-2985-4910-b4ea229f7444
* Content: [Supported text formatting in conversations - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/bots/bots-text-formats#feedback)
* Content Source: [msteams-platform/concepts/bots/bots-text-formats.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/bots/bots-text-formats.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by billbliss** [comment]
Yes, it's an unfortunate result of the markdown -> HTML libraries used in the various implementations.
