### ISSUE TITLE
What Does "Intimate" Mean Here

### ISSUE THREAD

**Issue by jcburley** [MicrosoftDocs/msteams-docs#7404]
I don't understand what the word "intimate" means in the context of this page/paragraph/sentence.

> Apps must always intimate the user before downloading any file or executable on the user’s environment. Any call to action (CTA), either text based or otherwise, that makes it clear to the user that a file or executable is downloaded on user action is allowed in the app. [Mandatory Fix]

Did the author mean to use some other term?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ff84fba8-b412-4c4a-3259-ae161d3523fd
* Version Independent ID: dba5c88d-5bd4-b66c-921b-2670fe8cfa66
* Content: [Microsoft Teams store validation guidelines - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/teams-store-validation-guidelines)
* Content Source: [msteams-platform/concepts/deploy-and-publish/appsource/prepare/teams-store-validation-guidelines.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/deploy-and-publish/appsource/prepare/teams-store-validation-guidelines.md)
* Service: **msteams**
* GitHub Login: @heath-hamilton
* Microsoft Alias: **surbhigupta**

**Comment by Meghana-MSFT** [comment]
@surbhigupta12 - This question is more related to Teams Store validation guidelines document. Can you please help to check and update the documentation? Thanks.
