### ISSUE TITLE
token.botframework.com in validDomains

### ISSUE THREAD

**Issue by v-kydela** [MicrosoftDocs/msteams-docs#741]
The documentation for [`validDomains`](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema#validdomains) says:

&gt; It is **not** necessary to include the domains of identity providers you want to support in your app, however. For example, to authenticate using a Google ID, it's necessary to redirect to accounts.google.com, but you should not include accounts.google.com in `validDomains[]`.

Has this changed? When using OAuth cards in a bot, don't we need to include token.botframework.com as a valid domain?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f94a488-d636-92b3-21eb-c88744c8f272
* Version Independent ID: 7b3413f4-9ade-accf-5cb2-83fead11a32a
* Content: [Manifest schema reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema#validdomains)
* Content Source: [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/resources/schema/manifest-schema.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Wajeed-msft** [comment]
token.botframework.com is not an identity provider. Actual authenticatio happens on https://login.microsoftonline.com for AD authentication. It is similar to Start Page from the [sample code](https://github.com/OfficeDev/microsoft-teams-sample-auth-node/blob/master/src/views/tab/simple/simple-start.hbs) which is a landing page which internally navigates to identity provider (See [simple-start.hbs)](https://github.com/OfficeDev/microsoft-teams-sample-auth-node/blob/master/src/views/tab/simple/simple-start.hbs#L52).

**Comment by v-kydela** [comment]
@Wajeed-msft - Thank you for the explanation! Should the documentation explain that or should we leave it alone?

**Comment by Wajeed-msft** [comment]
We allow all domains except identity provider so documenting specific case for _token.botframework.com_ won't be needed. @clearab - What are your views here?

**Comment by v-kydela** [comment]
Reading the documentation, it's unclear to me what needs to be included in `validDomains`. We don't need any valid domains to use an "open URL" action, so why do we need one for a "sign in" action? The only definition it gives is:

> A list of valid domains from which the app expects to load any content.

As a developer, I wouldn't know whether or why that applies to token.botframework.com in OAuth cards

**Comment by clearab** [comment]
fixed by #810
