### ISSUE TITLE
'Hello World' Sample and Cert Installation

### ISSUE THREAD

**Issue by elthombre** [MicrosoftDocs/msteams-docs#7412]
In the following, it offers screen shots detailing an auto-installation of a local certificate:

https://learn.microsoft.com/en-us/microsoftteams/platform/sbs-gs-javascript?tabs=vscode%2Cvsc%2Cviscode&tutorial-step=3#feedback

In my case, this failed. 

On my Windows 10 machine, I had to manually install the cert via import to the Trusted Root Certification Authorities using the cert manager from the Control Panel. 

On my Windows 11 machine, I noted some errors during the build process, chose to sign into my 365 account first, rebuild, and I wasn't prompted at all. Further, the local cert isn't in the Trusted Root Certification Authorities as required on my Windows 10 machine.

Perhaps some detail could be added to the documentation?

**Comment by sayali-MSFT** [comment]
@elthombre - Thanks for reporting your issue.
We will check it from our end and update the document accordingly.

**Comment by sayali-MSFT** [comment]
@elthombre - Could you please confirm once, If you are you following the same-
1.https://learn.microsoft.com/en-us/hololens/certificate-manager#to-install-a-certificate
2.https://learn.microsoft.com/en-us/windows-hardware/drivers/install/local-machine-and-current-user-certificate-stores
So that we can add it in documentation.

**Comment by elthombre** [comment]
@sayali-MSFT - I was using the Microsoft Management Console (MMC) as attached.

![Microsoft Management Console (MMC)](https://user-images.githubusercontent.com/8588122/200758014-007bf747-1ae3-4726-856b-a19e0c9c45d8.jpg)

**Comment by elthombre** [comment]
@sayali-MSFT , I would add to this sample project a way the way to run the solution within the Teams desktop version vs. only launching in the browser.

**Comment by sayali-MSFT** [comment]
@surbhigupta12 -Could you please help us to update the document?

In below document Add the Note in the Build and run your app locally in Visual Studio Code section after 2nd point-

If automatic method fails to install certificate, then you need to add certificate [manually](https://learn.microsoft.com/en-us/skype-sdk/sdn/articles/installing-the-trusted-root-certificate#adding-certificate-snap-ins).


Doucument-https://learn.microsoft.com/en-us/microsoftteams/platform/sbs-gs-javascript?tabs=vscode%2Cvsc%2Cviscode&tutorial-step=3#feedback
