### ISSUE TITLE
manifest file not updating

### ISSUE THREAD

**Issue by roalexan** [MicrosoftDocs/msteams-docs#742]
I got the [sample](https://docs.microsoft.com/en-us/microsoftteams/platform/get-started/get-started-app-studio) working, but now don't understand why deploying updates to my manifest file aren't showing up. If I make a change, say to messaging-extension.js, and use the code Azure plugin to redeploy, I can see the change (like changing the text in a thumbnail response). However, if I make a change to manifest.json, like add a new messaging extension command, and redeploy, it doesn't show up. I have been using the app studio to modify the manifest as well - maybe deploying from code only selectively overwrites the remote app (just a theory)?

**Comment by roalexan** [comment]
Seems like a can work around this by explicitly clicking **Welcome** > **Import an existing app** and browsing for my updated manifest file, rather than clicking **Welcome** and clicking on my recently created app. I guess the web server gets updated, but not the manifest, via the deploy script?

**Comment by billbliss** [comment]
After changing the manifest you need to re-import it each time when/if you change any of the app metadata. App Studio does nothing to your remote app.

**Comment by roalexan** [comment]
Got it. I'll go ahead and close this issue.
