### ISSUE TITLE
Failed to decrypt pairwise id when attempting to create a conversation between bot and user in Teams

### ISSUE THREAD

**Issue by k96payne** [MicrosoftDocs/msteams-docs#7424]
Hi Team, I'm getting an error of "Failed to decrypt pairwise id" when I attempt to create a conversation in Teams between a user and a bot. I don't understand the error response and can't find any documentation on it. I am referencing https://learn.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bot-conversations/bots-conv-proactive. I'm assuming it's not a bug and probably an issue with my request or a missing permission? Any help would be appreciated. 

Request:

(POST) https://smba.trafficmanager.net/amer/v3/conversations
Json Body:
```
{
  "bot": {
    "id": "..."
  },
  "members": [
    {
      "id": "..."
    }
  ],
  "channelData": {
    "tenant": {
      "id": "..."
    }
  }
}
```

Response:

`{
    "error": {
        "code": "BadArgument",
        "message": "Failed to decrypt pairwise id"
    }
}`

**Comment by Nivedipa-MSFT** [comment]
@k96payne - Thanks for reporting your issue. We will test the below API and update you soon. 
https://smba.trafficmanager.net/amer/v3/conversations

**Comment by k96payne** [comment]
Executing this same request this morning completed successfully. Not sure why. We can close this out.
