### ISSUE TITLE
Incoming Webhooks: Rate Limit and HTTP Status Code

### ISSUE THREAD

**Issue by mrwunderbar666** [MicrosoftDocs/msteams-docs#7425]
My webhook suddendly returns the following error:

```
Webhook message delivery failed with error: Microsoft Teams endpoint returned HTTP error 429 with ContextId tcid=0,server=msgapi-production-cse-azsc7-2-35,cv=blablba.0,MS-CV=blababl.0..
```

There are two major issues here. First the *HTTP Status Code* in the response header is still 200! It should be 429 instead.

The documentation does not mention any rate limits for incoming webhooks. I think it would also be better to include the rate limit in the response header somehow.

Response headers:
```
{'Alt-Svc': 'h3=":443",h3-29=":443"',
 'Cache-Control': 'no-cache',
 'Content-Encoding': 'gzip',
 'Content-Type': 'text/plain; charset=utf-8',
 'Expires': '-1',
 'MS-CV': 'blabalb.1.1',
 'Pragma': 'no-cache',
 'Server': 'Microsoft-IIS/10.0',
 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains; preload',
 'Transfer-Encoding': 'chunked',
 'Vary': 'Accept-Encoding',
 'X-AspNet-Version': '4.0.30319',
 'X-BEPartition': 'CLEURPRD08DUB08',
 'X-BEServer': 'DB9PR08MB7651',
 'X-BackEndHttpStatus': '200, 200',
 'X-CafeServer': 'DUZPR01CA0075.EURPRD01.PROD.EXCHANGELABS.COM',
 'X-CalculatedBETarget': 'DB9PR08MB7651.EURPRD08.PROD.OUTLOOK.COM',
 'X-CalculatedFETarget': 'DUZPR01CU005.internal.outlook.com',
 'X-FEEFZInfo': 'VIE',
 'X-FEProxyInfo': 'VI1P189CA0004.EURP189.PROD.OUTLOOK.COM',
 'X-FEServer': 'DUZPR01CA0075, VI1P189CA0004',
 'X-FirstHopCafeEFZ': 'VIE',
 'X-Powered-By': 'ASP.NET',
 'X-PreferredRoutingKeyDiagnostics': '1',
 'X-Proxy-BackendServerStatus': '200',
 'X-Proxy-RoutingCorrectness': '1',
 'X-RUM-Validated': '1',
 'request-id': 'cde5fd76-78d8-0d48-77ab-0f1627df51dd'}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 90ff2a84-a8bc-9259-d37d-622b102df75b
* Version Independent ID: e3b53e27-2946-189c-623b-9df704ea8f12
* Content: [Create an Incoming Webhook - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-incoming-webhook)
* Content Source: [msteams-platform/webhooks-and-connectors/how-to/add-incoming-webhook.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/webhooks-and-connectors/how-to/add-incoming-webhook.md)
* Service: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Prasad-MSFT** [comment]
@mrwunderbar666 - Currently message size limit is 28 kb. When the size exceeds 28 kb, you will receive an error.
https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams#teams-and-channels

The reason Connectors Webhook is sending 200 OK even for a failed delivery of a message, with the error message/reason in the response body, is that several 3rd party Connector apps/services treat failures with error status code as permanent issue and stop sending notifications further, considering it as Connector deletion scenario incorrectly.
So, the Connectors team has chosen to send success status code for certain valid/known errors occurring during Message delivery.

**Comment by mrwunderbar666** [comment]
Thanks for your explanation, I think this is very interesting.

> Currently message size limit is 28 kb. When the size exceeds 28 kb, you will receive an error.

The messages sent are actually smaller than 28kb and therefore, I don't think it applies to my problem. I think the documentation could be improved though, by mentioning the message size limits for webhooks.

Are there are any other restraints and limits that can cause a 429 error?

> The reason Connectors Webhook is sending 200 OK even for a failed delivery of a message, with the error message/reason in the response body, is that several 3rd party Connector apps/services treat failures with error status code as permanent issue and stop sending notifications further, considering it as Connector deletion scenario incorrectly.

Furthermore, I think it would be better to mention in the documentation that the response headers give non-standard responses.

**Comment by Prasad-MSFT** [comment]
If more than four requests are made in a second, the client connection is throttled until the window refreshes for the duration of the fixed rate. A [retry logic with exponential back-off](https://learn.microsoft.com/en-us/azure/architecture/patterns/retry) can mitigate rate limiting for cases where requests are exceeding the limits within a second. Refer [HTTP 429 responses](https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/rate-limit#handle-http-429-responses) to avoid hitting the rate limits.
Doc Reference: https://learn.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-using?tabs=cURL#rate-limiting-for-connectors

**Comment by mrwunderbar666** [comment]
thanks for the clarifications. I think the documentation could be improved by directly linking these articles to the main tutorial for webhooks. Also please consider mentioning that the response headers have non-standard response condes and the message body should be parsed to identify 429 errors.

**Comment by Prasad-MSFT** [comment]
@mrwunderbar666 - Thanks for your feedback. We will redirect it to doc team to update accordingly.

@surbhigupta12 - Could you please help here to add these links in this [Incoming Webhooks](https://learn.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-incoming-webhook) document ?

It would be better to add a note saying:
Currently message size limit is 28 kb. When the size exceeds 28 kb, you will receive an error.
https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams#teams-and-channels

Also,
"If more than four requests are made in a second, the client connection is throttled until the window refreshes for the duration of the fixed rate. A [retry logic with exponential back-off](https://learn.microsoft.com/en-us/azure/architecture/patterns/retry) can mitigate rate limiting for cases where requests are exceeding the limits within a second. Refer [HTTP 429 responses](https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/rate-limit#handle-http-429-responses) to avoid hitting the rate limits.
Doc Reference: https://learn.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-using?tabs=cURL#rate-limiting-for-connectors"
