### ISSUE TITLE
Member of a conversation not allow to write messages

### ISSUE THREAD

**Issue by PaulineCOI** [MicrosoftDocs/msteams-docs#744]
Hi, 

I was in a group conversation then I've left. Since, I still receive messages and my account is noted as a member of the conversation. But I can't write messages, I can't leave the conversation or mute it. Also noone can eject my account from the conversation. 

What can I try ? 

Thanks in advance

**Comment by Gousia-MSFT** [comment]
@PaulineCOI Could you please share the logs which can be obtained by pressing Ctrl+Alt+Shift+1 from Teams client?
