### ISSUE TITLE
how do i get the timezone of the user , who is using chatbot in teams?

### ISSUE THREAD

**Issue by vishmonne** [MicrosoftDocs/msteams-docs#745]

**Comment by Wajeed-msft** [comment]
Message payload which you received has timezone information. Please have a look at [full inbound schema example](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/bots/bot-conversations/bots-conversations#full-inbound-schema-example).
```
"entities": [
      { 
        "locale": "en-US",
        "country": "US",
        "platform": "Windows",
        "timezone": "America/Los_Angeles",
        "type": "clientInfo"
      }
    ]
```
