### ISSUE TITLE
UI bug when creating an overflow menu

### ISSUE THREAD

**Issue by swarajchavan98** [MicrosoftDocs/msteams-docs#7451]
When creating an overflow menu in an adaptive card, an empty box shows up before each item as follows:

![image](https://user-images.githubusercontent.com/62349078/202083262-56bfda09-69fb-4a42-8aac-715779c95407.png)

This is the code for creating the adaptive card:
```
{
    $schema: "http://adaptivecards.io/schemas/adaptive-card.json",
    type: "AdaptiveCard",
    version: "1.5",
    msTeams: { width: "full" },
    body: [
      {
        type: "TextBlock",
        text: "Hello from John Doe!",
        wrap: true,
        isSubtle: true,
        size: "default",
      },
      {
        type: "TextBlock",
        text: "How are you?",
        wrap: true,
        size: "Large",
        weight: "Bolder",
      },
    ],
    actions: [
      {
        type: "Action.Execute",
        title: "✏️ Edit data",
        tooltip: "Edit data",
        mode: "secondary",
      },
      {
        type: "Action.Execute",
        title: "🗑️ Delete data",
        tooltip: "Delete data?",
        mode: "secondary",
      },
    ],
  };
```

I tried using both Action.Execute and Action.Submit action types, but got the same issue. Also tried adding "iconUrl" property set to "null" or to some other url value, but the issue still persists. I followed articles from the following link:
[https://adaptivecards.io/explorer/Action.Submit.html](url)

**Comment by Meghana-MSFT** [comment]
we tried this at our end in Desktop and Web client. It is working fine at out end, we do not see any empty boxes. 
![image](https://user-images.githubusercontent.com/81138249/202180629-2db0f494-614b-415a-8de4-7f30b4093a46.png)

Microsoft Teams Version 1.5.00.31705 (64-bit)-E.

Can you please help us in getting the repro.

**Comment by swarajchavan98** [comment]
Hi,
Did you do it in personal chat? If so, try posting the same above adaptive card code in a group channel.

**Comment by Meghana-MSFT** [comment]
We are able to repro this issue in channel scope. It works fine in personal scope. We have raised a bug for the same, we will keep you posted on the updates.

**Comment by Meghana-MSFT** [comment]
@swarajchavan98 - Rectangle box issue beside secondary option in channel scope is fixed now. We have tested and verified the fix in MS Teams desktop (Microsoft Teams Version 1.6.00.23458) and web client.

**Comment by swarajchavan98** [comment]
I too can confirm that the issue is fixed, thank you very much.

**Comment by Meghana-MSFT** [comment]
Thank you for confirming, we are closing this issue. Please feel free to reach out to us if you need further help.
