### ISSUE TITLE
CSRF Issues with Referer Header in Outgoing Webhooks

### ISSUE THREAD

**Issue by AlexanderFillbrunn** [MicrosoftDocs/msteams-docs#7458]
Hi,
I am currently investigating deploying an outgoing webhook for MS Teams on an Apache Tomcat that has some CSRF protection measures enabled. These for instance check the Referer header against the actual host name of the server and if they do not match, the request is denied with a 403. I could probably selectively disable CSRF protection for some paths on the server, but I am wondering why the Referer header is used here at all, given that the Webhook is not really coming from a website (at least in the case of the MS Teams app). In any case, I think it might be a good idea to document the headers that are sent in the docs.

**Comment by sayali-MSFT** [comment]
@AlexanderFillbrunn - Thanks for reporting your issue.
We are checking it internally, If there is any documentation available for this and get back to you.

**Comment by sayali-MSFT** [comment]
@AlexanderFillbrunn -Currently, "https://teams.microsoft.com/" was added as referrer header.
Could you please share document link which you want to update the headers?

**Comment by AlexanderFillbrunn** [comment]
Hi,
I would suggest adding this information [here](https://learn.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-outgoing-webhook) or [here](https://learn.microsoft.com/en-us/microsoftteams/platform/sbs-outgoing-webhooks).

What is the reason for this referrer header, given that no referring is really going on?

**Comment by sayali-MSFT** [comment]
We are checking it with engineering team and let you know once we get any updates.

**Comment by sayali-MSFT** [comment]
@AlexanderFillbrunn -As there some customer requested to add Referrer header in Outgoing Webhook.
to monitor the traffic and this can be done with unique referrer.

**Comment by AlexanderFillbrunn** [comment]
Hi,
Thanks for the information. It's probably too late to change it to something not so widely used now, so I will close the ticket. Please consider documenting this, though.
