### ISSUE TITLE
Create MS Team from Moodle course group

### ISSUE THREAD

**Issue by JuliaRHT** [MicrosoftDocs/msteams-docs#746]
Hi
It would be really helpful for my institution (16-19 sixth form college) if there would be the option for the plugin to create Teams based on the groups on the Moodle course. We have many groups, each can be taught by one or more teacher,  enrolled on one Moodle course. It makes sense for the Team to be at Moodle group level for us.

I  have spoken to colleagues in higher education (universities) and they have said that this feature could be a deal breaker for them.

Thank you for producing such a great plugin, it is much appreciated.

Kind regards
Julia

**Comment by clearab** [comment]
Hi - thank you for your feedback. We are considering adding this to a future release.
