### ISSUE TITLE
Response is not sent to teams from python

### ISSUE THREAD

**Issue by bavugisainath** [MicrosoftDocs/msteams-docs#747]
My response is not sent to teams and only reply I see is "sorry, there was a problem encountered with your request." How do I find the issue? I am using below code to send the reponse using django rest framework and I am sure the respone is sent within 5 seconds. 
`elif request.method == 'POST':`
        `send_text = {"type": "message", "text": "This is a test message"}
        return Response(data=json.dumps(send_text))`

**Comment by Wajeed-msft** [comment]
Are you trying to update [Connector card](https://docs.microsoft.com/en-us/outlook/actionable-messages/message-card-reference#refresh-cards) on certain action? Could you please explain your issue? Screenshot of what you see in Microsoft Teams would also be helpful.

**Comment by bavugisainath** [comment]
I am just performing some action when the request.method=post and send the response saying the task is completed. Above code posted is a sample code. Below is the screenshot. Output I am expecting is to print "This is a test message"

![image](https://user-images.githubusercontent.com/33839471/60087203-747db600-9734-11e9-99cb-e2d8b67ef85e.png)

Am I doing something wrong here?

**Comment by Wajeed-msft** [comment]
Could you please have a look at [samples-outgoing-webhook-nodejs](https://github.com/OfficeDev/msteams-samples-outgoing-webhook-nodejs/blob/master/app.js) which sends simple text message as reply?

**Comment by bavugisainath** [comment]
I have tried running the node.js code on my machine and same issue. I have printed the hmac and they are different. I did not change anything in code. 

![image](https://user-images.githubusercontent.com/33839471/60094776-e52cce80-9744-11e9-9dfc-c2a31c959ead.png)

**Comment by bavugisainath** [comment]
I checked it but not familiar with node.js. I will take a look at the script and fix it. I will try to use HttpResponse instead of django Response. Thanks for your help.
