### ISSUE TITLE
Getting message "unable to reach app" after submit

### ISSUE THREAD

**Issue by roalexan** [MicrosoftDocs/msteams-docs#748]
I have a "composeExtensions" section in my manifest with the bot id and a command with type action, fetch task false, and static parameters. From the app the message extension will invoke a modal dialog with input elements in an adaptive card. When I submit, however, I’m getting the error "Unable to reach app. Please try again.". From what I've read [here](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/messaging-extensions/create-extensions) the bot needs to handle a composeExtension/submitAction message; however, it looks to me like the submit isn't finding the bot at all, let alone is it implementing the right protocol. I notice that if I type "@myapp hello" it will get a response from the bot (I have the context being echoed back and also logged to Azure Storage). However, if I type "@myapp", select the message extension, edit the input elements, and click submit, that's when I get the error. What am I doing wrong? Something misconfigured in the manifest.json? bot?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aaa0ea75-7363-3ef5-39df-ad07c493c118
* Version Independent ID: ab9a2a6e-e2ca-828f-cd8b-bd9ff98411ab
* Content: [Initiate actions with messaging extensions - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/messaging-extensions/create-extensions#responding-to-submit)
* Content Source: [msteams-platform/concepts/messaging-extensions/create-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/messaging-extensions/create-extensions.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by clearab** [comment]
That error message doesn't mean the bot didn't receive the message, just that the bot didn't respond in a timely fashion. Can you confirm that your bot never receives the composeExtension/submitAction invoke message? The relevant section of the page you linked to is here:

https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/messaging-extensions/create-extensions#responding-to-submit

**Comment by roalexan** [comment]
Pretty sure the bot is not being called. I turned on "app service logs" for my web app and added some JS debugging into bot.js and messaging-extension.js.

For an extension of type "query" (I used [this](https://docs.microsoft.com/en-us/microsoftteams/platform/get-started/get-started-nodejs-app-studio) sample), if I type "@appname test" I see "test" echoed back and the logging message in bot.js. If I type "@appname", click "What can I do?", select the "query" command, and type in a cardTitle, I can select one of the five cats. I also see the logging message in messaging-extension.js. So far so good.

However, for an extension of type "action" (I added a new command to the existing manifest and updated messaging-extension.js to handle the new command id), if I type "@appname test", click "What can I do", and select the "action" command, enter some text for an Input.Text, and click "Submit", I see the message **Unable to reach app**. I don't see any logging message, but I do see an exception (at the bottom).

What's going on? Is my bot or message extension code wrong in some way? Should I be using different versions of the "botbuilder" and "botbuilder-teams" modules - using the above demo, I am currently using:

    "botbuilder": "^3.11.0",
    "botbuilder-teams": "^0.2.6",

Why this exception?

`2019-06-26T22:32:04.215815634Z TypeError: this.onInvokeHandler is not a function
2019-06-26T22:32:04.215856634Z     at TeamsChatConnector.ChatConnector.onDispatchEvents (/home/site/wwwroot/node_modules/botbuilder-teams/node_modules/botbuilder/lib/bots/ChatConnector.js:570:22)
2019-06-26T22:32:04.215863834Z     at TeamsChatConnector.dispatchEventOrQuery (/home/site/wwwroot/node_modules/botbuilder-teams/lib/TeamsChatConnector.js:347:47)
2019-06-26T22:32:04.215868934Z     at TeamsChatConnector.onDispatchEvents (/home/site/wwwroot/node_modules/botbuilder-teams/lib/TeamsChatConnector.js:255:18)
2019-06-26T22:32:04.215873834Z     at TeamsChatConnector.ChatConnector.dispatch (/home/site/wwwroot/node_modules/botbuilder-teams/node_modules/botbuilder/lib/bots/ChatConnector.js:582:18)
2019-06-26T22:32:04.215878634Z     at /home/site/wwwroot/node_modules/botbuilder-teams/node_modules/botbuilder/lib/bots/ChatConnector.js:150:27
2019-06-26T22:32:04.215891034Z     at OpenIdMetadata.getKey (/home/site/wwwroot/node_modules/botbuilder-teams/node_modules/botbuilder/lib/bots/OpenIdMetadata.js:26:13)
2019-06-26T22:32:04.215895834Z     at TeamsChatConnector.ChatConnector.verifyBotFramework (/home/site/wwwroot/node_modules/botbuilder-teams/node_modules/botbuilder/lib/bots/ChatConnector.js:124:28)
2019-06-26T22:32:04.215900134Z     at IncomingMessage.<anonymous> (/home/site/wwwroot/node_modules/botbuilder-teams/node_modules/botbuilder/lib/bots/ChatConnector.js:63:27)
2019-06-26T22:32:04.215905034Z     at IncomingMessage.emit (events.js:182:13)
2019-06-26T22:32:04.215909234Z     at endReadableNT (_stream_readable.js:1094:12)`

**Comment by billbliss** [comment]
For the exception to occur, your bot is being called by the back-end service that your bot talks to. Otherwise there's nothing that would cause the exception to be thrown. When your bot returns a 500 error, which it will when an exception is thrown, Teams will show "Unable to reach app" in the UI.

Are you using ngrok? By running the ngrok debugger at http://localhost:4040 you should be able to see what's being sent to your bot. Furthermore you should be able to set a breakpoint in your bot code, specifically in your callback specified in teamChatConnector.onComposeExtensionSubmitAction() mentioned on the page @clearab mentioned.

**Comment by roalexan** [comment]
If you have a JavaScript sample (equivalent to the TypeScript sample, I suppose - https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/messaging-extensions/create-extensions#responding-to-submit) showing an implementation of onComposeExtensionSubmitAction, that would be very helpful.

**Comment by roalexan** [comment]
it would also be great if there were a version supporting Bot Framework SDK 4.x.

**Comment by Trinetra-MSFT** [comment]
@roalexan - [Try this sample code](https://github.com/OfficeDev/BotBuilder-MicrosoftTeams-dotnet/tree/master/CSharp/Samples/Microsoft.Bot.Builder.Teams.MessagingExtensionBot)

**Comment by Wajeed-msft** [comment]
We are working on SDK v4 sample. You can check the avialble sample [here](https://github.com/OfficeDev/BotBuilder-MicrosoftTeams-node/tree/master/samples).
