### ISSUE TITLE
[Doc-Bug] Note for installationUpdate event

### ISSUE THREAD

**Issue by SubbaReddi** [MicrosoftDocs/msteams-docs#7489]
I see the following note in documentation:
When you upgrade an application, and then add or remove a bot, the action also triggers the installationUpdate event. The action field is set to add-upgrade if you add a bot or remove-upgrade if you remove a bot.

Can you explicit mention the following case:
Bot will receive installationUpdate event only for adding or removing bot from manifest. For all other cases, installationUpdate event will not trigger.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0a6d00a4-dd28-33c4-002e-2e8e7c653ce2
* Version Independent ID: 0856927a-25f4-b1e0-5f1b-d55dc61796f3
* Content: [Conversation events - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/subscribe-to-conversation-events?tabs=dotnet#installation-update-event)
* Content Source: [msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md)
* Service: **msteams**
* GitHub Login: @WashingtonKayaker
* Microsoft Alias: **anclear**

**Comment by Meghana-MSFT** [comment]
@surbhigupta12 - Can you update the [existing note](https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/subscribe-to-conversation-events?tabs=dotnet#installation-update-event) as below - 

When you upgrade an application, Bot will receive installationUpdate event only for adding or removing bot from manifest. For all other cases, installationUpdate event will not trigger. The action field is set to add-upgrade if you add a bot or remove-upgrade if you remove a bot.

@SubbaReddi - Can you please confirm if this looks ok?

**Comment by SubbaReddi** [comment]
@Meghana-MSFT : Looks fine to me.

**Comment by Meghana-MSFT** [comment]
@surbhigupta12 - Can you please help to update above note.
