### ISSUE TITLE
Additional reactions

### ISSUE THREAD

**Issue by elipstein** [MicrosoftDocs/msteams-docs#749]
What about additional <redacted>? Saving and un-saving?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55c04f55-28de-978f-8733-0a83453172f7
* Version Independent ID: 4f25cfc6-6ac0-db44-4078-a8ba592ceeba
* Content: [Handle bot events - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/bots/bots-notifications#feedback)
* Content Source: [msteams-platform/concepts/bots/bots-notifications.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/bots/bots-notifications.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by clearab** [comment]
For the reactions, they are reactionsAdded/Removed events with a different type (i.e. happy, sad, angry etc).

I'm not sure what you mean by saving and un-saving?

**Comment by clearab** [comment]
The messageReaction JSON objects are typed, if there are ever additional types they would be available as new types.

I'm not sure what you mean by saving/un-saving...?

**Comment by elipstein** [comment]
By saving/unsaving I mean adding a new "type" when the user saves or unsaves a message. I would calling a saving a reaction, but could understand classifying in a different way. Still I think there should be a way to get notifications when a message is saved or unsaved as it's a useful metric for engagement

For ex:
"reactionsRemoved": [
        {
            "type": "save"
        }
    ],

**Comment by Gousia-MSFT** [comment]
@elipstein We have a feature request for this. We are tracking this internally.
