### ISSUE TITLE
The important note about parameter encoding is incorrect

### ISSUE THREAD

**Issue by ydogandjiev** [MicrosoftDocs/msteams-docs#7490]
The important note that starts with "Ensure that all query parameters are properly URI encoded." is not correct. The `encodeURI` API should only be used when encoding a complete URL. Any query string parameters (QSPs) should be encoded by calling `encodeURIComponent` instead (even if they are URLs).

You can find more details here:
https://stackoverflow.com/questions/4540753/should-i-use-encodeuri-or-encodeuricomponent-for-encoding-urls

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 45541337-ecd7-5cf6-cbe4-3f0d2f39aa79
* Version Independent ID: 6b4203f0-2844-06c9-eaa3-9cc03e6f76c0
* Content: [Create deep links - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links?tabs=teamsjs-v2)
* Content Source: [msteams-platform/concepts/build-and-test/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/build-and-test/deep-links.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Nivedipa-MSFT** [comment]
@surbhigupta12 - Could you please help here to update below note?
![image](https://user-images.githubusercontent.com/92150070/203234353-e6a8e767-92fc-4933-8357-62476d1745b0.png)
Contents need to be updated here: https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links?tabs=teamsjs-v2#generate-a-deep-link-to-your-tab

Need to add below note:
Ensure that URL is properly URI encoded. You must follow the preceding examples using the last example:
```
JavaScript
var encodedWebUrl = encodeURI('https://tasklist.example.com/123/456&label=Task 456');
var encodedContext = encodeURI('{"subEntityId": "task456"}');
var taskItemUrl = 'https://teams.microsoft.com/l/entity/fe4a8eba-2a31-4737
```

@ydogandjiev - Could you please confirm if this is ok or is there anything we need to add here?

**Comment by Nivedipa-MSFT** [comment]
@v-ypalikila - I have updated few things in this one. Could you please reverify and update it accordingly.

**Comment by surbhigupta12** [comment]
> @surbhigupta12 - Could you please help here to update below note? ![image](https://user-images.githubusercontent.com/92150070/203234353-e6a8e767-92fc-4933-8357-62476d1745b0.png) Contents need to be updated here: https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links?tabs=teamsjs-v2#generate-a-deep-link-to-your-tab
> 
> Need to add below note: Ensure that all query parameters are properly URI encoded. You must follow the preceding examples using the last example:
> 
> ```
> JavaScript
> var encodedWebUrl = encodeURIComponent('https://tasklist.example.com/123/456&label=Task 456');
> var encodedContext = encodeURIComponent('{"subEntityId": "task456"}');
> var taskItemUrl = 'https://teams.microsoft.com/l/entity/fe4a8eba-2a31-4737-8e33-e5fae6fee194/tasklist123?webUrl=' + encodedWebUrl + '&context=' + encodedContext;
> ```

@ydogandjiev, could you please verify and approve this.

**Comment by ydogandjiev** [comment]
@surbhigupta12, the proposed changes look good to me. The only other thing that might be worth calling out is that the context should be generated by calling JSON.stringify on an actual object. Directly hardcoding it as a string, like shown in the snippet, can cause issues with special characters or incorrect formatting.

**Comment by Nivedipa-MSFT** [comment]
@surbhigupta12 - Could you please help us here to update the documentation as suggested. Thanks
