### ISSUE TITLE
Please don't translate the tools' name

### ISSUE THREAD

**Issue by huabin** [MicrosoftDocs/msteams-docs#7495]
Hello there,

Sorry to trouble you, I find a mistake on microsoft teams document page, please check [here](https://learn.microsoft.com/zh-cn/microsoftteams/platform/sbs-gs-nodejs?tutorial-step=1)

![Screenshot 2022-11-22 at 17 04 52](https://user-images.githubusercontent.com/535675/203272399-27971d8e-18b6-4447-b847-28a62d2db573.png)

I don't think it is necessary to translate the name of the tool into Chinese. Thank you.

**Comment by huabin** [comment]
@Wajeed-msft You're welcome, I tried to fix it, but I can't find a way, so I submitted this issue, hope can help.

**Comment by surbhigupta12** [comment]
Removing doc-bug tag as this issue is related to translation. Have shared the same with Soran.

**Comment by surbhigupta12** [comment]
The localization team has resolved the issue at their end. Please verify and mark this issue as closed.

**Comment by huabin** [comment]
@surbhigupta12 Actually, it is not.


https://user-images.githubusercontent.com/535675/206829835-c8c8517c-66eb-498a-93fa-b66d8c4bd610.mov

**Comment by huabin** [comment]
Seriously?

This 'typo' which takes only a few seconds to fix, has not been solved for a month now.

Do you guys really care about your job? @Wajeed-msft @surbhigupta12 @Nivedipa-MSFT

**Comment by Nivedipa-MSFT** [comment]
@huabin - Apologies for the delay. We will check the ETA with localization team and get back to you soon.

**Comment by Nivedipa-MSFT** [comment]
@huabin - Document has updated. Could you please check and confirm? Thanks.

**Comment by huabin** [comment]
@Nivedipa-MSFT Cool, thank you.
