### ISSUE TITLE
Teams Update Now Requiring High Perf GPU

### ISSUE THREAD

**Issue by carlowahlstedt** [MicrosoftDocs/msteams-docs#750]
![image](https://user-images.githubusercontent.com/2687687/60184974-11a12300-97f7-11e9-996e-d3a201041fcb.png)

![image](https://user-images.githubusercontent.com/2687687/60184847-d1da3b80-97f6-11e9-861b-36e8c28ab444.png)

![image](https://user-images.githubusercontent.com/2687687/60184908-f3d3be00-97f6-11e9-80b5-bf692540b83a.png)

**Comment by Gousia-MSFT** [comment]
@carlowahlstedt Thanks for reporting it. We have raised a bug for this.

**Comment by Wajeed-msft** [comment]
We are tracking this internally. Closing this from documentation issues.
