### ISSUE TITLE
Carousel card is not rendered properly in IOS teams app and Adaptive card is rendering slow and overlapping in IOS

### ISSUE THREAD

**Issue by vishmonne** [MicrosoftDocs/msteams-docs#751]
Hi Team,

When i tested my Chatbot in IOS Teams , these are the following issues i faced

- Card is rendered very slowly in IOS and it sometimes gets overlapped (screenshot 1)
![Screenshot 1](https://user-images.githubusercontent.com/10339913/60263914-88c1de80-98ff-11e9-9d25-7db71e1cfad5.jpg)
![Screensot 1](https://user-images.githubusercontent.com/10339913/60263929-8f505600-98ff-11e9-8042-d2a62d3165f7.jpg)

- In Carousel card, the text  formatting is not getting wrapped properly though we have given the wrap=true in the code( screenshot 2)

![Screenshot 2](https://user-images.githubusercontent.com/10339913/60263938-94150a00-98ff-11e9-9677-ee2393b0007c.jpg)

- Somtimes when the button is clicked, the text border 
sometimes is shown very large ( screenshot 3)

![Screenshot 3](https://user-images.githubusercontent.com/10339913/60263947-9bd4ae80-98ff-11e9-8887-72a7e462fd71.jpg)

We notice that , these issues are working perfectly in the android app and the desktop app of Microsoft Teams , but in IOS we are facing this issues.

Would be really helpful if someone could give idea on this

**Comment by vishmonne** [comment]
HI Team,

Will be really helpful if any of u can give us an update on this as early as possible?

Thanks,
Raahul C

**Comment by Wajeed-msft** [comment]
@vishmonne - Could you please provide Adaptive card JSON for this?

**Comment by vishmonne** [comment]
Hi @Wajeed-msft , thanks for replying. 

These are the Bot details :
SDK V3 , C# Bot Framework
Chatbot is deployed in Azure with teams channel enabled.
Adaptive Card version : 1.0

We are using the app id for testing the Teams in Desktop as well as in Mobile. We dont have any Manifest json file.

We face this issue only in IOS Mobile app and the same code is working perfectly fine in Android team app , Desktop Teams app as well as the Mac Book Teams app.

We are creating the Adaptive CARD dynamically using C# code and we dont have adaptive card json as such.

**Comment by Wajeed-msft** [comment]
Could you please share the bot id?

**Comment by vishmonne** [comment]
HI @Wajeed-msft . The app id is ce5386db-0bf3-4bd1-beea-8276502bf912

**Comment by Wajeed-msft** [comment]
Seems like your app needs few other APIs to work internally. 
![image](https://user-images.githubusercontent.com/31851992/60347559-4372df00-99db-11e9-9f0c-eded20bbebff.png)
Could you please [serialize your Attachment](https://www.newtonsoft.com/json/help/html/SerializingJSON.htm) object and send it?

**Comment by droidriz** [comment]
@Wajeed-msft 
here's the serialized attachment.
[json1.txt](https://github.com/MicrosoftDocs/msteams-docs/files/3342985/json1.txt)

**Comment by vishmonne** [comment]
hi @Wajeed-msft  , my colleague have serialized the attachment and commented. Any other info needed?

**Comment by Wajeed-msft** [comment]
I have raised bug for this. We are looking into this.

**Comment by vishmonne** [comment]
Sure @Wajeed-msft  . Thanks

**Comment by vishmonne** [comment]
hi @Wajeed-msft . Any updates on the issues ?

**Comment by vishmonne** [comment]
hi @Wajeed-msft  . One more update on this issue

I did a lot of testing in IOS teams app regarding the **first** and **third** issue (overlapping  , i found out that in latest Teams version 1.0.78 and 1.0.77 i am getting this issue, whereas in Teams version 1.0.74 i am not getting this issue.

**Comment by vishmonne** [comment]
hi @Wajeed-msft , the above mentioned teams version issue where should i report?

**Comment by Gousia-MSFT** [comment]
@vishmonne Thanks for reporting this. We have created a bug and we are working on getting this fixed.
