### ISSUE TITLE
[Doc-enhancement] Package loading failure because of nested folders

### ISSUE THREAD

**Issue by SubbaReddi** [MicrosoftDocs/msteams-docs#7519]
Hi Team,
When we try to import app package, we see following error: 
Provided add-in package was not understood. Please, make sure that the file being submitted is a valid Office add-in package.

![image](https://user-images.githubusercontent.com/69682598/203655496-b28a6a43-3b14-48ce-89e1-959d59b97fea.png)

The reason for the above error is nested folders. So, please add note about the same.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7da63b6f-15d7-a6dd-82fc-d183afaeb816
* Version Independent ID: 82d1ca83-28dd-220e-ab0c-a4833f8f8143
* Content: [Developer Portal for Teams - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/teams-developer-portal)
* Content Source: [msteams-platform/concepts/build-and-test/teams-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/build-and-test/teams-developer-portal.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **surbhigupta**

**Comment by Nivedipa-MSFT** [comment]
@surbhigupta12 - Could you please help here to add a note saying that
When we try to import app package, we see following error:
Provided add-in package was not understood. Please, make sure that the file being submitted is a valid Office add-in package.

![image](https://user-images.githubusercontent.com/92150070/203695412-fdf10b5e-b4d7-44b1-a3d2-62184dd8064e.png)


The reason for the above error is nested folders.
