### ISSUE TITLE
No SP Site Or Channel Email Address(es) Bound when Provisioning from API

### ISSUE THREAD

**Issue by pdemro** [MicrosoftDocs/msteams-docs#752]
## Category

- [X] Question
- [x] Bug
- [ ] Enhancement

## Expected or Desired Behavior

Per the [Teams Clone documentation](https://docs.microsoft.com/en-us/graph/api/team-clone?view=graph-rest-1.0): 
> If successful, this method will return a 202 Accepted response code with a Location: header pointing to the operation resource. When the operation is complete, the operation resource will tell you the id of the created team.

## Observed Behavior

Observations indicate once a status of "succeeded" is returned from the teamsAsyncOperation, the Team is not fully provisioned.  Documents cannot be stored on the team, and email address(es) are not generated for contained channels.

## Steps to Reproduce

1. Clone a microsoft team using the API reference: https://docs.microsoft.com/en-us/graph/api/team-clone?view=graph-rest-1.0.  This may also apply to the base Team provisioning
2. Wait for the teamsAsyncOperation to return a status of "Success" (per documented guidance https://docs.microsoft.com/en-us/graph/api/resources/teamsasyncoperation?view=graph-rest-1.0)
3. Navigate to the provisioned team and attempt to upload a file or generate an email for a channel
4. Get prompted with the messages below.  These messages appear for observed hours/days/weeks until the Team's underlying data storage has been fully provisioned.  Observations indicate that attempting to access these via the User Interface may speed up the background provisioning processes

> We are setting up your file directory.  Try refreshing the page after a few minutes or check back later.  

>We're still setting up your team.  Please try again later.

**Comment by pdemro** [comment]
Additional Questions are: 
1. Is there any documentation which describes this behavior?

2. Are there APIs available to kick-off provisioning of these background services?  

My clients are frustrated that they are forced to wait hours or days for the Team to be fully provisioned when created via the Graph API.

**Comment by Wajeed-msft** [comment]
This is not guaranteed to be provisioned in real time but will eventually. Not different from when created in the Microsoft Teams client. 

Currently, there is no way to know when SharePoint provisioning is completed. We have raised request to update documentation for this on https://github.com/microsoftgraph/microsoft-graph-docs/issues/4970.

**Comment by pdemro** [comment]
I appreciate the response @Wajeed-msft, although I wish the answer was different!

Thank you!

**Comment by Wajeed-msft** [comment]
Channel email can now be created programmatically using Graph API (`/teams/{team-id}/channels/{channel-id}/provisionEmail`). More details here: https://docs.microsoft.com/en-us/graph/api/channel-provisionemail?view=graph-rest-beta&tabs=http
