### ISSUE TITLE
Facing issue while adding @general via incoming webhook

### ISSUE THREAD

**Issue by Yashkothari9** [MicrosoftDocs/msteams-docs#7526]
Like I am facing issue in adding @general in the adaptive card via incoming webhook.
I only able to mention some people not the whole channel when I am sending a card via incoming hook..
Is this a feature that hasn't been taken or Is not supported

**Comment by Meghana-MSFT** [comment]
Currently only user mention is supported in Incoming webhook. In general, mentioning a channel via payload is not supported yet in both Incoming Webhook and Bot.
![image](https://user-images.githubusercontent.com/81138249/203799304-8d581425-7356-4ffa-9310-c850fa4467e9.png)

A feature request for the same is raised here at https://feedbackportal.microsoft.com/feedback/idea/23c1bd25-39c1-ec11-a81b-000d3a00c008. You can upvote the request.

**Comment by ChetanSharma-msft** [comment]
Hello @Yashkothari9 - Please let us know if you need any further help here?

**Comment by Meghana-MSFT** [comment]
We are closing this issue at our end. Please feel free to reach out to us if you have any questions. Thank you.
