### ISSUE TITLE
Bot is not replying in Teams channel after posting command message.

### ISSUE THREAD

**Issue by sagar-malpure** [MicrosoftDocs/msteams-docs#7527]
In Teams channel if you are selecting and posting command message then it should listen by installed bot and respond accordingly. 
If your Teams channel has no owner assigned then bot will not respond to the command, So make sure your Teams channel has owner assigned. (It happens if the teams channel is created using graph API) 

Adding note to indicate same will help.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3a982542-ae03-2ada-cf71-4d586272e0c3
* Version Independent ID: 9e1fd82b-79e4-1b8d-5367-a8de3d04b3aa
* Content: [Create a command menu for your bot - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/create-a-bot-commands-menu?tabs=desktop%2Cdotnet)
* Content Source: [msteams-platform/bots/how-to/create-a-bot-commands-menu.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/bots/how-to/create-a-bot-commands-menu.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **anclear**

**Comment by Prasad-MSFT** [comment]
@sagar-malpure - We are checking the issue. We will get back to you shortly.

**Comment by sagar-malpure** [comment]
Hello Team,
Yeah right when we create a standard channel, the team owner becomes channel's owner.
it happens intermittently having no channel/team owner.

**Comment by Prasad-MSFT** [comment]
@sagar-malpure - Ok, but how is it possible to have a team with no owner? At least one owner has to be there.

**Comment by sagar-malpure** [comment]
it was happening intermittently but currently, not reproducible using Graph API.

**Comment by Prasad-MSFT** [comment]
@sagar-malpure - Thanks for the info. Please let us know if you face this issue again.

**Comment by sagar-malpure** [comment]
Sure, Thank you !

**Comment by Prasad-MSFT** [comment]
We are closing this issue for now. Please feel free to reopen if required. Thanks!
