### ISSUE TITLE
Conditional Access Policies

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/msteams-docs#7528]
Please add some information about how to configure conditional access policies to work with Teams Apps. I can't find any mention of what a dev should do to support CA policies or for what a CA Policy admin should do so that a Teams App can be evaluated in a CA policy

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a6416300-1ddf-3ffd-10d2-99ed1f4eb08c
* Version Independent ID: 335d9588-866d-bdde-f1de-6a093a091e2a
* Content: [Authenticating app users - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/authentication/authentication)
* Content Source: [msteams-platform/concepts/authentication/authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/authentication/authentication.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Prasad-MSFT** [comment]
@DeanGross - We are checking this internally and will take appropriate action on this. Thanks!

**Comment by Prasad-MSFT** [comment]
@DeanGross - CA policies should be automatically supported for any apps that implement SSO:
https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/tab-sso-overview

Please refer below doc to understand how CA policies work and how to test them:
https://learn.microsoft.com/en-us/azure/active-directory/conditional-access/
