### ISSUE TITLE
Missing step indicator

### ISSUE THREAD

**Issue by dennisvintherjensen** [MicrosoftDocs/msteams-docs#753]
In the section "Enable developer preview" step 2 has a notice regarding step 1, but only mentions "step" instead of "step 1".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 008da4e2-979e-c396-db28-4acf57deb530
* Version Independent ID: f1413f77-5eb3-e1fd-9235-d322d6e4eb6c
* Content: [Developer Preview - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/dev-preview/developer-preview-intro#feedback)
* Content Source: [msteams-platform/resources/dev-preview/developer-preview-intro.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/resources/dev-preview/developer-preview-intro.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by dennisvintherjensen** [comment]
How do I fix this myself?

**Comment by clearab** [comment]
fixed in #810
