### ISSUE TITLE
Clarification of how to set the app id URI for tab SSO

### ISSUE THREAD

**Issue by xelossan** [MicrosoftDocs/msteams-docs#7539]
I know there's already the same issue reported, but for me it did not clarify the issue and I cannot be reopened, so I have to create a new one.

It the section "To expose an API" in the important block (https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/tab-sso-register-aad#to-expose-an-api), it states to "enter the application ID URI as api://fully-qualified-domain-name.com/BotId-{YourClientId}, where the BotID is your bot app ID."

So let's assume I have an Azure AD app registered with Application ID **application-client-id** and this application ID is entered in Teams App's manifest. I want to have properly configure SSO, and my Teams app offers both Tab App and Bot.

My questions are:
1. Should I register a separate Azure AD application for the bot, or can I use the same app registration for both Teams app and Bot?
I tried using the same app id for both, but it seems that Teams doesn't like it, and even though the bot works when tested from Azure Portal, Teams shows error when trying to add the app to the teams meeting.
2. Assuming I have a separate bot app registration with Application ID **bot-client-id**, how should the app uri look like?
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 52cb5b2e-e1e9-1993-04a0-6925d1453f20
* Version Independent ID: 52cb5b2e-e1e9-1993-04a0-6925d1453f20
* Content: [Register your tab app with Azure AD - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/tab-sso-register-aad)
* Content Source: [msteams-platform/tabs/how-to/authentication/tab-sso-register-aad.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/tabs/how-to/authentication/tab-sso-register-aad.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Prasad-MSFT** [comment]
@xelossan - 
1. No, you don't need to register a separate Azure AD application for the bot. You can use the same app registration for both Teams app and Bot.
Regarding the issue that your app is not working in MS Teams, please verify you have enabled Teams Channel for your App registration in Azure Portal.
2. You don't need separate registration. 
Application ID URI for app with multiple capabilities should be in below format:
 `api://fully-qualified-domain-name.com/BotId-a246b078-394d-4858-84f1-aa6fdb84b80b`

**Comment by xelossan** [comment]
Thanks for your answers.

1. I did enable Teams Channel. The problem occurred only when adding the app to the Teams meeting, and only when both Teams app and Bot app shared Azure AD app registration. When they have separate IDs, everything works as expected. Do you have any thoughts what may be the issue?
2. Is BotId part case-sensitive and should be exactly BotId, or can be botid?

**Comment by Prasad-MSFT** [comment]
@xelossan - 
1. Could you please make sure you have configured the manifest settings for Tabs in meeting properly as mentioned in this [doc](https://learn.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/build-tabs-for-meeting?tabs=desktop#app-manifest-settings-for-tabs-in-meeting)?
2. It can be botid. It's not case sensitive.

**Comment by ChetanSharma-msft** [comment]
Hello @xelossan - Hope you are doing well!!
Please let us know whether your issue has resolved or need any further help here?
