### ISSUE TITLE
ReplyToId is comming null while testing in emulator

### ISSUE THREAD

**Issue by samthrusha123** [MicrosoftDocs/msteams-docs#7540]
I have an adaptive card with yes or no action items. When a user clicks on yes/no I want to update that card with thank you message. But to update we need replyToId. That is coming null when the user performs any action(yes/no).

this is the adaptive card I'm using
`{
  "type": "AdaptiveCard",
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "version": "1.3",
  "body": [
    {
      "type": "TextBlock",
      "text": "Is this answer helpful?",
      "wrap": true
    },
    {
      "type": "ColumnSet",
      "columns": [
        {
          "type": "Column",
          "width": "stretch",
          "items": [
            {
              "type": "ActionSet",
              "actions": [
                {
                  "type": "Action.Submit",
                  "title": "Yes",
                  "data": {
                    "question": "${question}",
                    "answer": "${answer}",
                    "text": "submit-feedback",
                    "IsAnswerHelpFul": true
                  }
                }
              ]
            }
          ]
        },
        {
          "type": "Column",
          "width": "stretch",
          "items": [
            {
              "type": "ActionSet",
              "actions": [
                {
                  "type": "Action.Submit",
                  "title": "No",
                  "data": {
                    "question": "${question}",
                    "answer": "${answer}",
                    "text": "submit-feedback",
                    "IsAnswerHelpFul": false
                  }
                }
              ]
            }
          ]
        }
      ]
    }
  ]
}`

**Comment by Nivedipa-MSFT** [comment]
@samthrusha123 - We will test this in emulator and update you soon.

**Comment by samthrusha123** [comment]
> 

okay

**Comment by samthrusha123** [comment]
@Nivedipa-MSFT Do we have any updates?

**Comment by Nivedipa-MSFT** [comment]
@samthrusha123 - We have tested this in Bot framework emulator but we are getting the value of replyTold.
Please refer below screenshot:

![image](https://user-images.githubusercontent.com/92150070/204579211-b1b93241-989d-488c-8bb5-43322bf9fb8b.png)

**Comment by samthrusha123** [comment]
after clicking on yes/no are you getting reply id??

**Comment by Nivedipa-MSFT** [comment]
@samthrusha123 - Yes, after clicking on yes/no we are getting the value of replyTold property.

![image](https://user-images.githubusercontent.com/92150070/204710441-1d1b0739-bfbc-4042-a658-b7623df048aa.png).

Could you please share your screen recording with us to investigate further on this?

**Comment by Nivedipa-MSFT** [comment]
@samthrusha123 - Could you please confirm is your issue resolved or are you still facing this issue?

**Comment by Nivedipa-MSFT** [comment]
@samthrusha123 - Could you please confirm is your issue resolved or are you still facing this issue?

**Comment by samthrusha123** [comment]
> @samthrusha123 - Could you please confirm is your issue resolved or are you still facing this issue?

Yes I'm still having this issue, are you doing any code changes or any settings?

**Comment by Nivedipa-MSFT** [comment]
@samthrusha123 - Which bot framework emulator version you are using. We are using V4. Could you please use V4 version and check again?
Could you please share your screen recording so we can verify that we are doing in same way or not?

**Comment by Nivedipa-MSFT** [comment]
@samthrusha123 - Did you checked this with bot framework emulator V4 version?

**Comment by Nivedipa-MSFT** [comment]
@samthrusha123 - Could you please confirm is your issue resolved or are you still facing this issue?
