### ISSUE TITLE
Update the C# and Node.js links for App complete authentication sample

### ISSUE THREAD

**Issue by Nivedipa-MSFT** [MicrosoftDocs/msteams-docs#7549]
In below document the sample links for C# and Node.js redirecting to the same page.
https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-flow-tab

Please update below links to the sample link:
C# - https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/app-complete-auth/csharp
Node.js - https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/app-complete-auth/nodejs

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6d5b8b0f-3da3-8642-6edf-dc6608a830cf
* Version Independent ID: f93cdabd-f6ab-29d0-f3c9-78deb21ca521
* Content: [Enable authentication using third-party OAuth provider - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-flow-tab)
* Content Source: [msteams-platform/tabs/how-to/authentication/auth-flow-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/tabs/how-to/authentication/auth-flow-tab.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Nivedipa-MSFT** [comment]
@surbhigupta12 - Could you please help here to update the links for samples?

**Comment by surbhigupta12** [comment]
This issue is already resolved. The docs point to the right sample:

https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-flow-tab#code-sample
