### ISSUE TITLE
Precondition Failed when trying to remove side loaded application from Team installation via Graph API

### ISSUE THREAD

**Issue by k96payne** [MicrosoftDocs/msteams-docs#7550]
Hi Team, I'm getting a 412 Precondition Failed when attempting to remove an application that has been side-loaded onto a Team. Is removing a side-loaded app via the Graph API possible? If so, could someone check out this error for me?

I'm using the permissions mentioned here: https://learn.microsoft.com/en-us/graph/api/team-delete-installedapps?view=graph-rest-1.0

Request:

(DELETE) https://graph.microsoft.com/v1.0/teams/theTeamId/installedApps/theAppInstallationId

Response:

`{
    "error": {
        "code": "PreconditionFailed",
        "message": "Failed to execute TeamsGraphService backend request RevokeGroupResourceSpecificPermissionsRequest. Workload Unknown. Request Url: https://teamsgraph.teams.microsoft.com/v1.0/groups/.../revokeResourceSpecificPermissions, Request Method: POST, Response Status Code: PreconditionFailed, Response Headers: Date: Mon, 28 Nov 2022 13:19:42 GMT\r\nServer: Kestrel\r\n, Reason Phrase: Precondition Failed",
        "innerError": {
            "message": "Failed to execute TeamsGraphService backend request RevokeGroupResourceSpecificPermissionsRequest. Workload Unknown. Request Url: https://teamsgraph.teams.microsoft.com/v1.0/groups/.../revokeResourceSpecificPermissions, Request Method: POST, Response Status Code: PreconditionFailed, Response Headers: Date: Mon, 28 Nov 2022 13:19:42 GMT\r\nServer: Kestrel\r\n, Reason Phrase: Precondition Failed",
            "code": "PreconditionFailed",
            "innerError": {},
            "date": "2022-11-28T13:19:42",
            "request-id": "e7105034-a195-40ec-bce8-c2ab160a1436",
            "client-request-id": "e7105034-a195-40ec-bce8-c2ab160a1436"
        }
    }
}`

**Comment by Meghana-MSFT** [comment]
we are looking into this, we will get back to you.

**Comment by Meghana-MSFT** [comment]
We tried this at our end by following the below steps. It has worked successfully.

1. We sideloaded an app to team using Upload a custom app
![image](https://user-images.githubusercontent.com/81138249/204461383-c6babbf3-5cd7-426b-928a-bccbd052df5b.png)
2. Deleted the above installed app using Graph API
![image](https://user-images.githubusercontent.com/81138249/204461175-299e4e7e-e367-4196-9674-67ce996726d6.png)

Can you please let us know if you are doing it differently, so that we will try to repro locally?

**Comment by k96payne** [comment]
Yes, that is how I am doing it. 

1. Add bot to team via upload on the Teams Desktop App

<img width="890" alt="Screen Shot 2022-11-29 at 7 48 09 AM" src="https://user-images.githubusercontent.com/26599888/204533620-214bd36a-d155-4f6c-ac6b-0325b5c6ddb1.png">

2. Get access token via (GET) https://login.microsoftonline.com/tenantID/oauth2/v2.0/token

3. (GET) https://graph.microsoft.com/v1.0/groups?$filter=displayName eq 'myTeamName' to get the team id

4. (GET) https://graph.microsoft.com/v1.0/teams/teamId/installedApps?$expand=teamsAppDefinition to get the ID of the app installed

5. (DELETE) https://graph.microsoft.com/v1.0/teams/teamId/installedApps/appId but it responds with the error I posted above

Of course I shouldn't need all of these permissions based on the documentation, but I've tried adding all four of the permissions here and still no luck. 
<img width="673" alt="image" src="https://user-images.githubusercontent.com/26599888/204534705-e1632e83-c648-4997-82cd-1c37b8f1a9ab.png">

**Comment by Meghana-MSFT** [comment]
We tried with the exact steps provided by you. It is working fine at our end. We will check internally and get back to you.

**Comment by k96payne** [comment]
Thank you!

**Comment by Meghana-MSFT** [comment]
Engineering team has replied saying - 
Your Teams app has RSC permissions. Installation/Removal of apps with RSC permissions is not supported in app-only context.

**Comment by k96payne** [comment]
Thanks for following up! Are RSC permissions _**any**_ of the permissions listed under **Team Permissions**, **Chat/Meeting Permissions**, and **User Permissions** here (within the Developer Portal App)? 
<img width="967" alt="image" src="https://user-images.githubusercontent.com/26599888/205297513-70f50e13-3585-4d9c-bd2f-7d7a8224b891.png">


What is an _**app-only context**_?

If I want a bot to be able to read members of a Team and direct message users in a Team, do I _have_ to use RCS permissions to accomplish this or is there a different set of permissions I can enable that are not RCS permissions?

**Comment by Meghana-MSFT** [comment]
Please read these docs to find for RSC permissions of an app - https://learn.microsoft.com/en-us/microsoftteams/platform/graph-api/rsc/resource-specific-consent,   https://learn.microsoft.com/en-us/microsoftteams/app-permissions-admin-center#view-resource-specific-consent-permissions-of-an-app.

RSC permissions are not required to get members of a Team using bot. Please see these docs and sample that returns members - 
https://learn.microsoft.com/en-us/microsoftteams/platform/resources/team-chat-member-api-changes,
https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/get-teams-context?tabs=dotnet#fetch-the-roster-or-user-profile,
https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/2a23c4c8ae827fcc54ab95ec58c8565e22cb969f/samples/app-complete-sample/csharp

**Comment by Wajeed-msft** [comment]
@k96payne:  [Permissions property](https://learn.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema#permissions) of manifest is deprecated. 
![image](https://user-images.githubusercontent.com/31851992/209388846-6a4dae77-eba3-4963-a612-0b0513c614ba.png)

Bots do not need any additional permissions to [Fetch the team member](https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/get-teams-context?tabs=dotnet#fetch-the-roster-or-user-profile)  and [send 1:1 personal chat message](https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-messages?tabs=dotnet#send-a-message) in Teams. 

If you are looking to notify these users based on external event/schedule, then please take a look at [Send proactive messages](https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/send-proactive-messages?tabs=dotnet#send-the-message) documentation. 

Please take a look at [Permissions in Teams app](https://learn.microsoft.com/en-us/microsoftteams/platform/graph-api/app-permissions/teams-app-permissions) to know more about different permissions.

**Comment by Meghana-MSFT** [comment]
@k96payne - Can you please confirm if your issue is resolved?

**Comment by k96payne** [comment]
Thank you for all of the information. We will need some time on our end to look into this and will get back with you.

**Comment by k96payne** [comment]
We have removed resource-specific permissions from our Bot and are now able to uninstall via the graph api. Thanks for the assistance.

**Comment by Meghana-MSFT** [comment]
Thank you for confirming back. We are closing this issue, please feel free to reach out to us if you have any questions. Thanks.

**Comment by ChetanSharma-msft** [comment]
Hello @k96payne - Good to hear that your issue has resolved.
Could you please share your valuable feedback here: [feedback link](https://aka.ms/DevSupportFeedback).
