### ISSUE TITLE
Latest teams update does not accept manifest without localized name in localization file

### ISSUE THREAD

**Issue by nbelyh** [MicrosoftDocs/msteams-docs#7551]
I have a teams app, and a **localization** for the manifest, like this:

manifest.json
```
  "name": {
    "short": "My Cool App",
  },
  .....
  "localizationInfo": {
    "defaultLanguageTag": "en-us",
    "additionalLanguages": [
      {
        "languageTag": "sv-se",
        "file": "sv-se.json"
      }]
```
sv-se.json
```
{
    "$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.9/MicrosoftTeams.Localization.schema.json",
    "description.short": "...",
    "description.full": "..."
}
```
This week, when trying to upload the manifest, teams started complaining that manifest is invalid:
```
Error while reading manifest.json: root | Required properties are missing from object: ["name.short","name.full"].
```
![image](https://user-images.githubusercontent.com/528366/204394693-887fc31d-33ef-4280-8cc5-5bc6e399cade.png)
It wants me to add "name.short" and "name.full" to the **localizaiont file**. meaning, if I change the sv-se.json like this, then it works:
```
{
    "$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.9/MicrosoftTeams.Localization.schema.json",
    "name.short": "My Cool App",
    "name.full": "My Cool App",
    "description.short": "...",
    "description.full": "..."
}
```

Looks like a bug to me? Why should teams care that some strings are missing in the localization? Especially full name? The name of my applicaiton is not localizable.

The same package was working fine less than a month ago.

**Comment by Prasad-MSFT** [comment]
@nbelyh - Could you please let us know in which Teams version are you facing this issue? If possible, please share your manifest zip as well?

**Comment by nbelyh** [comment]
I have Microsoft Teams Version 1.5.00.32108 (64-bit)-E. It was last updated on 18.11.2022.
It is also not working in the current online (Web) version.

The zip file is attached below:
[mycollapp.zip](https://github.com/MicrosoftDocs/msteams-docs/files/10112179/mycollapp.zip)

The workaround: add "name.short" and "name.full" to the localization file.

**Comment by Prasad-MSFT** [comment]
@nbelyh - We tried to repro this issue using Teams Desktop client `Microsoft Teams Version 1.5.00.32474 (64-bit)` and Web client as well.
If we don't enter any value under properties `"name.short"` and `"name.full"` in localization file, the app is not getting installed throwing the same error as you encountered.
[manifest.zip](https://github.com/MicrosoftDocs/msteams-docs/files/10113253/manifest.zip)

It seems like, these fields are required. We are checking with engineering team if this behavior is expected or not.
We will update you if we get any further info. Thanks!

**Comment by nbelyh** [comment]
@Prasad-MSFT 
This seems to be exactly the bug: these fields were not required **in the localization file** one month ago :)

The point is, you normally don't want to translate the **name** of your application to all languages, it's a brand. Consider "Microsoft Teams" for example - should it be required to be translated? The name will most probably be just duplicated in the localization file, so isn't it logical to not require it there, since it's already specified in the manifest? And it was like that just one month ago, so maybe it's a bug? 

Anyway, it's a minor thing, just in case somebody will face the same thing when trying to upload a manifest that was working one month ago just wonder why validation is failing now 😄

**Comment by walidaslam7** [comment]
**Manifest parsing has failed**

The same issue we are getting for our application we tried to rename our application **name.short** in different localization files.

**Comment by Prasad-MSFT** [comment]
We are checking with engineering team if there is any latest update and if it's expected to throw this error.
After confirmation, we will update this [doc](https://learn.microsoft.com/en-us/microsoftteams/platform/resources/schema/localization-schema#example) mentioning `"name.short"` and `"name.full"` are required properties in localization file, so that next time onwards it will be much clearer to developer trying this.

**Comment by ShimSooChang** [comment]
My manifest was also working one month ago and I start to get the same erro, is there any work arround to solve this?

**Comment by nbelyh** [comment]
@ShimSooChang just add the "name.short" and "name.full" to the localization file (same as in your "main" manifest)

**Comment by Prasad-MSFT** [comment]
@nbelyh , @ShimSooChang - We have raised a documentation bug to highlight these points.
PFB the issue link: https://github.com/MicrosoftDocs/msteams-docs/issues/7633

**Comment by Genesys-AlexW** [comment]
@Prasad-MSFT The https://dev.teams.microsoft.com/appvalidation.html app validator should be updated to look for the new properties. Currently, the app package validator passes if you do not have the localization for `name.short` and `name.full`.

**Comment by Prasad-MSFT** [comment]
@Genesys-AlexW - Thanks for the information. We will pass this info to engineering team to update accordingly.
