### ISSUE TITLE
App Cache Doc Update Request

### ISSUE THREAD

**Issue by Mohammed-MSFT** [MicrosoftDocs/msteams-docs#7559]
🚨 Looks like you arrived from the internal review site 
🚨 Do not enter Microsoft confidential information here

1. Under [**Enable App Caching**](https://review.learn.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/build-tabs-for-meeting?branch=pr-en-us-7013&tabs=desktop#enable-app-caching) section, second point were using contentUrl and entityid, please follow given links to update **contentUrl** and **entityid** as given below.
  - [**contentUrl**](https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/configuration-page?tabs=teamsjs-v2#modify-or-remove-a-tab): "add content page URL here" 
  - [**entityId**](https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/configuration-page?tabs=teamsjs-v2#modify-or-remove-a-tab): "add a unique identifier here"

2. Under **Code example** section please replace the code example with below code.
```
// Using readyToUnload callback function
const beforeUnloadHandler = (readyToUnload: () => void) => {
  readyToUnload();
  return true;
};
```

```
    microsoftTeams.app.initialize().then(() => {

        microsoftTeams.teamsCore.registerBeforeUnloadHandler((readyToUnload) => {
        const result = beforeUnloadHandler(readyToUnload);
        // dispose resources and then invoke readyToUnload
        console.log("got beforeunload from TEAMS"); 
        return result;
        });

        microsoftTeams.teamsCore.registerOnLoadHandler((data) => {
        console.log("got load from TEAMS", data.contentUrl, data.entityId); 
        // use contentUrl to route to correct page 
        // invoke notifySuccess when ready  
        app.notifySuccess();
        });
      });
```
 
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e44c95e7-3258-df7e-224d-d60ea1cac46c
* Version Independent ID: e44c95e7-3258-df7e-224d-d60ea1cac46c
* Content: [Build tabs for meeting - Teams](https://review.learn.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/build-tabs-for-meeting?branch=pr-en-us-7013&tabs=desktop#app-caching)
* Content Source: [msteams-platform/apps-in-teams-meetings/build-tabs-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/apps-in-teams-meetings/build-tabs-for-meeting.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **surbhigupta**

**Comment by v-sdhakshina** [comment]
Code example and step updated as per this git issue requirements:

<img width="679" alt="image" src="https://user-images.githubusercontent.com/95284144/204712793-c8cca9fd-f01c-4f64-8123-b0bab128dc3d.png">

<img width="423" alt="image" src="https://user-images.githubusercontent.com/95284144/204713190-6ff335d2-3b18-4525-92ea-40296699f59a.png">

**Comment by surbhigupta12** [comment]
Docs are updated. The PR will be merged once the feature is released.
