### ISSUE TITLE
Webhook with no body

### ISSUE THREAD

**Issue by phixxo** [MicrosoftDocs/msteams-docs#7575]
Hey, what if a webhook notification does not contain a body? In such a case Teams does not show anything. In particular I have a webhook set for Intercom and I want to get this webhook being triggered when a conversation in Intercom is tagged. Testing the webhook outside of Teams works. However, in Teams if there is no body, there is no notification :-( Do you have any solution for this? 
Thank you! 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 90ff2a84-a8bc-9259-d37d-622b102df75b
* Version Independent ID: e3b53e27-2946-189c-623b-9df704ea8f12
* Content: [Create an Incoming Webhook - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-incoming-webhook)
* Content Source: [msteams-platform/webhooks-and-connectors/how-to/add-incoming-webhook.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/webhooks-and-connectors/how-to/add-incoming-webhook.md)
* Service: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by phixxo** [comment]
I was using the Intercom connector available. In your screen shot, based on the image, it looks like you are using "Incoming webhook", could you please confirm? And by notification I mean a new item in the channel. E.g. this one works: 
![image](https://user-images.githubusercontent.com/17883073/204757901-1eb8da01-37a9-45fa-9b27-8d9caa537641.png)
But if there is no body in the webhook. I am attaching the JSON data which are not getting through....and I am going to test the incoming webhook connector. 
[json.txt](https://github.com/MicrosoftDocs/msteams-docs/files/10121724/json.txt)

**Comment by phixxo** [comment]
So, just tried the Incoming webhook connector and it seems it does not work together with Intercom - I am getting errors when testing the webhook :-(

**Comment by Meghana-MSFT** [comment]
Can you please let us know how you are creating intercom and triggering the webhook to send message without body. Repro steps would be really appreciated.

We tried above json at our end with incoming webhook and we see below message.
![image](https://user-images.githubusercontent.com/81138249/204811107-aaf5019b-ce4b-4ccf-bdd8-ce1e4d1222f8.png)

**Comment by phixxo** [comment]
Thanks, I tried using Intercom connector - but it is not available today as I wanted to create screen shots. It was there for sure yesterday! I then copied the webhook URL from Teams and added it on Intercom side. While the "conversation.user.created" event from Intercom works fine and I saw a post in the channel - see the screen shot in my previous post. The "conversation_part.tag.created" notification event did not get to the Teams channel. I posted the JSON in my previous message. When testing the web hooks on https://webhook.site/ - they both work fine. It is just the second one is not getting to MS Teams. But now, it seems that the Intercom connector was removed from the list...
So, now I tried using the Incoming webhook connector and when I use the URL in Intercom, I am getting error when sending a test ping request: 
![image](https://user-images.githubusercontent.com/17883073/204986673-4f85f7dd-af30-4c8f-855e-9f4adcaad382.png)
Do I need to set anything else in the incoming webhook?

**Comment by Wajeed-msft** [comment]
@phixxo - Incoming Webhook accepts JSON in connector message format mentioned in here: [Example of connector message](https://learn.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-using?tabs=cURL#example-of-connector-message). If payload sent by Intercom is not in the same format, then card won't be recognized and would be dropped.  One possible solution would be to create intermediate service which listens to incoming payload from Intercom and then constructs a new payload using Connector Message card format and then post it to Incoming Webhook. 

Here is [sample code](https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/main/samples/connector-todo-notification/csharp/TeamsToDoAppConnector/Utils/TaskHelper.cs#L55) in which we show how to construct Connector Message card payload.

Please let me know if you need any further help.

**Comment by Meghana-MSFT** [comment]
Thank you for confirming, we will close this issue for now. please feel free to reach out to us if you have further questions.
