### ISSUE TITLE
Rate Limiting Issue in Webhook URL

### ISSUE THREAD

**Issue by Yashkothari9** [MicrosoftDocs/msteams-docs#7576]
The Rate Limiting For Incoming webHook URL is very very less, like it's almost 250 times lesser than what is provided by Slack, Isn't there a way that we can increase that.
Please let me know If there is a way to do so

**Comment by Prasad-MSFT** [comment]
@Yashkothari9 - 
A [retry logic with exponential back-off](https://learn.microsoft.com/en-us/azure/architecture/patterns/retry) can mitigate rate limiting for cases where requests are exceeding the limits within a second. Refer [HTTP 429 responses](https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/rate-limit#handle-http-429-responses) to avoid hitting the rate limits.

**Comment by Yashkothari9** [comment]
@Prasad-MSFT so how much time shall we wait to check

**Comment by Yashkothari9** [comment]
@Prasad-MSFT so how much time shall we wait to check

**Comment by Prasad-MSFT** [comment]
@Yashkothari9 - Nearly 10-15 seconds.

**Comment by Yashkothari9** [comment]
@Prasad-MSFT had one more question that how many webhook url can be made in a channel?

**Comment by Prasad-MSFT** [comment]
@Yashkothari9 - We will check this with engineering team and will get back to you. Thanks!

**Comment by Prasad-MSFT** [comment]
@Yashkothari9 - The message size limit is 28 KB. When the size exceeds 28 KB, you receive an error. For more information, see [limits and specifications for Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/limits-specifications-teams).

**Comment by Prasad-MSFT** [comment]
We are closing this issue for now. Please feel free to reopen if required. Thanks!
