### ISSUE TITLE
The Typescript link to the code sample is broken

### ISSUE THREAD

**Issue by theshumanator** [MicrosoftDocs/msteams-docs#7578]
Perhaps it should point to the NodeJs one: https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/incoming-webhook/nodejs

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 90ff2a84-a8bc-9259-d37d-622b102df75b
* Version Independent ID: e3b53e27-2946-189c-623b-9df704ea8f12
* Content: [Create an Incoming Webhook - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-incoming-webhook)
* Content Source: [msteams-platform/webhooks-and-connectors/how-to/add-incoming-webhook.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/webhooks-and-connectors/how-to/add-incoming-webhook.md)
* Service: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Meghana-MSFT** [comment]
@theshumanator - Thank you for reporting this, we will get the doc updated.

@surbhigupta12 - Can you please help to update the code sample details in the following doc - https://learn.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-incoming-webhook#code-sample

Please update the highlighted areas below - ![image](https://user-images.githubusercontent.com/81138249/204732907-1e6ea3cc-426d-4b48-af6a-b41f322223d3.png)

Change the title from TypeScript to NodeJs.
Update the sample link to - https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/incoming-webhook/nodejs
