### ISSUE TITLE
Can we create a deeplink from tab to bot

### ISSUE THREAD

**Issue by searlin** [MicrosoftDocs/msteams-docs#759]
We want to create a deeplink from a static tab to bot, this url https://teams.microsoft.com/l/entity/28:" + BotId + "/" + TabEntityID + "?conversationType=chat can redirect to the bot, but how to attach the message to the bot?

**Comment by Wajeed-msft** [comment]
If you are looking for deeplink to bot with message text then you can use [deeplink to chat](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/deep-links#deep-linking-to-a-chat) for bot as well. 

` https://teams.microsoft.com/l/chat/0/0?users=<28:BotId>&topicName=<chat name>&message=<precanned text> `

**Comment by searlin** [comment]
thanks @Wajeed-msft this issue can be closed
