### ISSUE TITLE
Manifest parsing has failed

### ISSUE THREAD

**Issue by walidaslam7** [MicrosoftDocs/msteams-docs#7593]
Hello guys!

We have a team extension-based commercial application and for the past 2 days we are getting issues whenever we try to upload manifest files
Kind of stuck and waiting for MS team engineers for an alternative solution. Please check this issue on high Priority if possible.

![image](https://user-images.githubusercontent.com/84803958/204794406-f9963874-9aa7-4680-8f1c-afb3a1ea5e2c.png)

**Comment by Meghana-MSFT** [comment]
Can you please help with the below questions?

1. What error do you see when you copy error details?
2. Please check if you see any error by validating the app package in developer portal
![image](https://user-images.githubusercontent.com/81138249/204806865-31d9f7c3-7c2a-40db-87bf-de050059b4aa.png)

3. Please share manifest file with us so that we can check locally.

**Comment by walidaslam7** [comment]
Thank you for your response @Meghana-MSFT. 
After spending a couple of hours on this issue I found an actual error and fix it for me at least :)

**Steps:**

- I go to https://admin.teams.microsoft.com/ and tried to upload the manifest but this time my developer mode was opened and I found this error in the network call: `**Error while reading manifest.json: root | Required properties are missing from object: ["description.short","description.full"].**`

-  I checked for my localization files and in one of the file **"description.short","description.full"** were not available so I updated the file and re-upload the manifest zip from Teams App > Manage Apps and find out it worked for me after updating the required attributes.

**Comment by Meghana-MSFT** [comment]
Glad that your issue is resolved, you can also check errors if any in app package by the points 1 and 2 I mentioned above.

We are closing this issue for now, please feel free to reach out to us if you have any issues.
