### ISSUE TITLE
 Property 'executeDeepLink' does not exist on type 'typeof microsoftTeams'

### ISSUE THREAD

**Issue by anusm14** [MicrosoftDocs/msteams-docs#760]
Trying to use executeDeepLink() api on microsoftTeams sdk, but get the below error saying no such api is there.
microsoftTeams.executeDeepLink("deeplink");
 Property 'executeDeepLink' does not exist on type 'typeof microsoftTeams'

Is there any other import required?

**Comment by Wajeed-msft** [comment]
Which version of Microsoft Teams client SDK are you using? Could you please try it with [latest version](https://docs.microsoft.com/en-us/javascript/api/overview/msteams-client?view=msteams-client-js-latest) (1.4.2)?
