### ISSUE TITLE
Broken Link - Try the UI Library(playground)

### ISSUE THREAD

**Issue by jamescussen** [MicrosoftDocs/msteams-docs#7609]
There is a broken link on this page when clicking the "Try the UI Library(playground)" button. It currently goes to:

<Error>
<Code>PublicAccessNotPermitted</Code>
<Message>Public access is not permitted on this storage account. RequestId:d4e1a3f0-001e-006d-072e-06529b000000 Time:2022-12-02T09:12:23.0705362Z</Message>
</Error>

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e739fdd6-8835-cfcd-f25c-1b4c7cb42afa
* Version Independent ID: 3bbef1d2-6427-0c7f-bfe2-57bf016629da
* Content: [Designing your app with UI templates - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/design/design-teams-app-ui-templates?tabs=desktop)
* Content Source: [msteams-platform/concepts/design/design-teams-app-ui-templates.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/design/design-teams-app-ui-templates.md)
* Service: **msteams**
* GitHub Login: @heath-hamilton
* Microsoft Alias: **lajanuar**

**Comment by Meghana-MSFT** [comment]
The same issue is being tracked here - https://github.com/MicrosoftDocs/msteams-docs/issues/7328. Please follow this thread for further updates.
