### ISSUE TITLE
ChatBot Conversation Log

### ISSUE THREAD

**Issue by Bryand13** [MicrosoftDocs/msteams-docs#761]
Hello there,

We have implemented a bot in our enviroment. But it seems like the way talking with the bot is not registered for the user who does it. The way to identify it is only via web.

 
The url ID https://chatbotiddxxxxxxx.dispatcher.hana.ondemand.com

We need to associate that URL with our bot.

Anyone knows if there is any way to implement the url in the chatbot? Or if there is a way to do it with the app "AppStudio" in MS Teams?

 
Appreciatte any information.

**Comment by Wajeed-msft** [comment]
> But it seems like the way talking with the bot is not registered for the user who does it. The way to identify it is only via web.

Could you please clarify this?

**Comment by Bryand13** [comment]
Hi @Wajeed-msft ,

What I meant es, if im talking with the chatbot am not be able to see any log in the background, for exemple, who or whom were the users that interacted with the bot.

**Comment by Wajeed-msft** [comment]
You will get user details from the [inboud request](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/bots/bot-conversations/bots-conversations#full-inbound-schema-example) (_message.from_). You can do addional loggin in your code if you want.
