### ISSUE TITLE
Unknown ServiceError error when sending message 

### ISSUE THREAD

**Issue by MajaEffenberg** [MicrosoftDocs/msteams-docs#7613]
Hi there, 

We sometimes get a unknown error when we try to send a message to MS Teams.  

For some users, when sending AdaptiveCard using `TurnContext.sendActivity()` or updating AdaptiveCard using `TurnContext.updateActivity()`, we get this error:
```
{
    "error": {
        "code": "ServiceError",
        "message": "Unknown"
    }
}
```

We've reported this bug before, but haven't been able to reproduce it.
Link to previous bug report - [Unknown error when sending message ](https://github.com/MicrosoftDocs/msteams-docs/issues/6140)

Now this error is reappearing again for several users causing problems with having a consistent conversation with our bot. In addition, one particular user receives this error every few messages sent to him.

Recently observed errors for this user:

- our botId: `4112cc9a-d683-4ffd-b0bc-2013af7c7497`
- request url: `https://smba.trafficmanager.net/chv3/conversations/{conversationId}/activities/{activityId}`
- conversationId: `a:1gpPUwta7rT6pB8yDvgb02-PCwjAfhPmB_qjvMAPyd3lpjFs_k-l-wRPwYz-cYR3OmSnAGZZJVevgkRNC26fXhEHbTOSjzM66hh5Y9lBmHmT546Hfmv4BRooP0dqHI9bI`
- statusCode: `403`
- list of errors for this user (method `PUT ` - updating AdaptiveCard, method `POST ` - sending AdaptiveCard):

| Timestamps  | Method  | 
|---|---|
| 30.11.2022 - 08:23:19   | PUT  |
| 30.11.2022 - 08:23:19  | POST |
| 30.11.2022 - 08:23:01  | POST |
| 30.11.2022 - 08:22:49  | POST |
| 30.11.2022 - 08:23:01  | PUT |
| 30.11.2022 - 08:22:48  | PUT |
| 30.11.2022 - 08:22:41  | PUT |
| 30.11.2022 - 08:21:39  | POST |
| 30.11.2022 - 08:21:06  | PUT |
| 30.11.2022 - 08:20:58  | PUT |
| 30.11.2022 - 08:20:37  | POST |
| 30.11.2022 - 08:20:02  | POST |
| 30.11.2022 - 08:18:35  | POST |
| 30.11.2022 - 08:18:18  | PUT |
| 30.11.2022 - 08:18:01  | POST |
| 30.11.2022 - 08:14:18  | POST |
| 30.11.2022 - 08:14:12  | PUT |
| 30.11.2022 - 08:13:43  | POST |

Some of this errors we can see in Azure Portal in Bot Channel Issues, but not all of them:
![image](https://user-images.githubusercontent.com/89073193/205339521-2ae1721c-4afc-4d6e-8ae7-8c3853dff4d9.png)

**Comment by Meghana-MSFT** [comment]
@MajaEffenberg - We will reopen the bug and provide all the above shared details with the engineering team. We will keep you posted if there are any updates. Thanks.

**Comment by MajaEffenberg** [comment]
@Meghana-MSFT Thank you for update

**Comment by Meghana-MSFT** [comment]
@MajaEffenberg - An ICM has been raised for this issue and engineering team is working on it. We will keep you posted on the updates. Thanks!

**Comment by Meghana-MSFT** [comment]
@MajaEffenberg - Can you please let us know if users are still facing this issue?

**Comment by MajaEffenberg** [comment]
Currently, this user is not facing this problem any more. 
However, this error has occurred in the past at different times for different users. So it would be good if it was resolved to avoid its reappearance in the future.

**Comment by Meghana-MSFT** [comment]
@MajaEffenberg - Thanks for confirming. We have shared the above feedback with engineering team.

**Comment by rgfretes** [comment]
Hello, 
We have experienced this issue as well. 
This is a different bot, different tenant, and different users. 

Is there anything that can be done to avoid this? Is the only way to resolve this to raise a ticket and fix users individually?

**Comment by Meghana-MSFT** [comment]
We have shared this with engineering team, we will get back to you.

**Comment by Meghana-MSFT** [comment]
Engineering team has the following observations - 

URL is not correct [https://smba.trafficmanager.net/chv3/conversations/{conversationId}/activities/{activityId}](https://smba.trafficmanager.net/chv3/conversations/%7BconversationId%7D/activities/%7BactivityId%7D). It should be /ch/v3/ instead of /chv3/.

Could you please share the incoming request payload (especially the serviceUrl property) so engineering team can confirm whether that's the root cause.
