### ISSUE TITLE
Deep link - No response when we call an user with a personal teams licence with deep link. 

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/msteams-docs#7618]
When I used a deep link to call an user with a personal licence, nothing happened.

I work on an unity application and use the method UnityEngine.Application.OpenURL with the System.Uri as parameter
I use the link "msteams:/l/call/0/0?users=<users email>", I also tried with "https://teams.microsoft.com/l/call/0/0?users=<users email>"

`        Uri systemuri = new Uri(msteamslink, UriKind.Absolute);`
`        Application.OpenURL(systemuri .AbsoluteUri);`

With a professional account connected at Teams. When I use a random email, a reel email or no email; the method redirect me to the Teams app.
When a personnal account is connected. When I use a no email the method redirect me to the Teams app, and with a random or reel email, nothing happen. I get stuck in my app.

Environment :
Unity 2021.3.9f1
Microsoft Teams Version 1.5.00.31168 (64-bit)

**Comment by sayali-MSFT** [comment]
@AlanM-SE - We are looking into this we will get back to you soon.

**Comment by sayali-MSFT** [comment]
@AlanM-SE - We are tried to repro the scenario with personal account with the random email, a reel email or no email. It's working fine from our end.
Could you please confirm as you also trying the same or any other way to repro this?
Microsoft Teams Version 1.5.00.32970 (64-bit)

https://user-images.githubusercontent.com/93527375/206434151-e262f01a-71c6-4d62-a013-4f11409b0515.mp4

**Comment by sayali-MSFT** [comment]
@AlanM-SE - We are able to repro that issue on android device, we have raised bug for the same and concerned team is looking into it. We will inform you once we get any update.

**Comment by sayali-MSFT** [comment]
@AlanM-SE - Sorry for the delay. Engineering team working on this issue. Currently we don’t have ETA or Update on this thread.

**Comment by sayali-MSFT** [comment]
@AlanM-PersoSE - This does not currently supported in mobile scenarios. Apologies for the inconvenience. We will notify the community once we have support for mobile.
