### ISSUE TITLE
Issue On Returning Error of Exponential backoff

### ISSUE THREAD

**Issue by Yashkothari9** [MicrosoftDocs/msteams-docs#7635]
I am getting a status code of 200 even if the rate limiting issue is reached for a webhook url, It is not even sending a status code 429 rather than that it is giving 200, and even it is not returning any body, it is just returning a text, how shall we get to know in code that this error has come, like it is just returning a text, So in that case shall we parse the message each time to check whether the error has come or not this will be a wrong logic I guess, please check it out(url)
this is the message that too in text-
`Webhook message delivery failed with error: Microsoft Teams endpoint returned HTTP error 429 with ContextId MS-CV=.....`

And the Status Code is 200

please look into this

**Comment by Nivedipa-MSFT** [comment]
@Yashkothari9 - Thanks for reporting your issue. We will test this and update you soon.
