### ISSUE TITLE
There is no DevTools in the tray icon

### ISSUE THREAD

**Issue by kingma-sbw** [MicrosoftDocs/msteams-docs#764]
The tray icon does not have Devtools menu

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ed43afa-25da-3e1e-652b-e901264f9983
* Version Independent ID: 7121d23b-5b21-c914-e78e-5daafb273f50
* Content: [Accessing DevTools from the Teams Desktop Client - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/dev-preview/developer-preview-tools#feedback)
* Content Source: [msteams-platform/resources/dev-preview/developer-preview-tools.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/resources/dev-preview/developer-preview-tools.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by clearab** [comment]
Can you please confirm that you have enabled developer preview?

**Comment by Wajeed-msft** [comment]
If you are still facing this after enabling developer preview, please quit Microsoft Teams and see if it's visible when you launch it again. Please re-reopen this issue if you are still facing issue even after closing the app.

**Comment by narulasrinivas** [comment]
I'm experiencing same. Any help would be appreciated.
