### ISSUE TITLE
How to pass parameters from webchat to bot onmemberAddedAsync()

### ISSUE THREAD

**Issue by samthrusha123** [MicrosoftDocs/msteams-docs#7673]
` window.WebChat.renderWebChat(
      {
        directLine: window.WebChat.createDirectLine({ token }),
        store,
        userID: getUserName()+","+currentPoint
      },
      document.getElementById("webchatBot")
    );
    document.querySelector("#webchatBot > *").focus();`

how to pass any other parameters apart from userid?

**Comment by Nivedipa-MSFT** [comment]
@samthrusha123 - You can pass parameters from webchat to OnEventActivityAsync() not for onmemberAddedAsync().
However, the accepted method for sending data between the Web Chat client / user and the bot is to use the Web Chat store and the dispatch() function. The store broadcasts a variety of [actions](https://github.com/microsoft/BotFramework-WebChat/tree/master/packages/core/src/actions), such as DIRECT_LINE/CONNECT_FULFILLED and DIRECT_LINE/INCOMING_ACTIVITY (among others), that allows you to perform functions when triggered.

You may want to send the values as an event after Web Chat loads. The code would look something like this:

```
<script>
  (async function () {
    const store = window.WebChat.createStore( {}, ( { dispatch } ) => next => async action => {
      if (action.type === 'DIRECT_LINE/CONNECT_FULFILLED') {
        console.log('Event dispatched');
        dispatch( {
          type: 'WEB_CHAT/SEND_EVENT',
          payload: {
            name: 'CUSTOM_PARAMETERS',
            value: { q1: 'abc', q2: 'xyz' }
          }
        } )
      }

      return next(action);
    });

    [...]

    window.WebChat.renderWebChat(
       directLine: window.WebChat.createDirectLine({ token }),
      store: store
      />,
    document.getElementById( 'webchat' );
    )
  })
</script>
```
In your bot, you would utilize the onEvent() activity handler to capture the dispatched event:

```
this.onEvent = async (context, next) => {
  console.log('Event activity detected');

  const { activity } = context;

  if (activity && activity.name === 'CUSTOM_PARAMETERS') {
    await context.sendActivity('Custom parameters received!');
  }

  await next();
};
```
If you have your bot backend on C# you will receive your custom parameters on the OnEventActivityAsync method

```
protected override async Task OnEventActivityAsync(ITurnContext<IEventActivity> turnContext, CancellationToken cancellationToken)
{
     if(turnContext.Activity.Name == "CUSTOM_PARAMETERS")
       {
          await turnContext.SendActivityAsync($" Your custom parameters are: {turnContext.Activity.Value}", cancellationToken: cancellationToken);
       }
}
```

**Comment by samthrusha123** [comment]
Okay thanks

**Comment by Nivedipa-MSFT** [comment]
@samthrusha123 - If the above suggestion helped you in any way, could you please share your valuable feedback via [Microsoft Teams Developer Feedback](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR7iCOpS5_b9Nqmwx43u5rtZUOThVR081SllSR05aSDQxQ0tUMDVPTVIxTi4u) link.
