### ISSUE TITLE
Teams custom bot app is not asking the user concent everytime

### ISSUE THREAD

**Issue by samthrusha123** [MicrosoftDocs/msteams-docs#7675]
I didn't give my consent to my custom app, and when I try to login again it's not asking the consent. What might be the issue? 
Sometimes for other users, it is asking sometimes it's not asking. 

![MicrosoftTeams-image](https://user-images.githubusercontent.com/44087954/206731386-8a66d7cf-e20f-42b8-849f-9b7d65a7666d.png)

**Comment by sayali-MSFT** [comment]
@samthrusha123 - Thanks for reporting your issue.
We will investigate this issue and get back to you.

**Comment by samthrusha123** [comment]
When the user installs any teams bot, for SSO authentication it'll ask for user consent right, at that time if the user refuses to give consent it should ask again when user tries to have a conversation with the bot.

Repro Steps:
1. Create a simple teams bot with authentication, and when we installs it click on cancel when it asks for user consent. 
2. And send 'Hi' again it should ask user consent again but it's not asking.

**Comment by ChetanSharma-msft** [comment]
@samthrusha123 - Thanks for sharing the steps.
We will try it from our end and will let you know the updates.

**Comment by sayali-MSFT** [comment]
@samthrusha123 - Sorry for the delay. Engineering team working on this issue. Currently we don’t have ETA or Update on this thread.

**Comment by sayali-MSFT** [comment]
@samthrusha123 - Issue is Resolved. Could you please check and confirm once?
Microsoft Teams Version 1.6.00.9278 (64-bit)

https://user-images.githubusercontent.com/93527375/230036081-6d6af43b-d527-40af-99d9-1cb24cbfb438.mp4

**Comment by samthrusha123** [comment]
Do we need to do any code changes?
