### ISSUE TITLE
Video added to app listing not being displayed in Teams

### ISSUE THREAD

**Issue by matthiasdilger** [MicrosoftDocs/msteams-docs#7706]
When adding a Youtube video to the app listing in Partner Center it does not display in the app listing in Teams:

<img width="872" alt="polly" src="https://user-images.githubusercontent.com/5625718/207761720-59bdfbcd-e41a-4e4b-b0b7-41973937173b.png">

This issue does not affect all apps/videos, some can be played.
Reproduced on Microsoft Teams Version 1.5.00.34153 on Mac OS with Apple Silicon and version 1.5.00.31156 on Mac OS with Intel. It works fine on web (Chrome & Edge), so it might be a Teams Mac specific issue.

**Comment by Meghana-MSFT** [comment]
we will check this issue and get back to you with an update.

**Comment by matthiasdilger** [comment]
@Meghana-MSFT Thanks, I was now also able to reproduce the issue on Windows with Teams Version 1.5.00.33362 (64-bit)

**Comment by Meghana-MSFT** [comment]
@matthiasdilger - We did try this at our end on Windows with Teams Version 1.5.00.33362 (64-bit). We are not able to repro this issue. It is working fine at our end. We will check internally and get back to you. 

https://user-images.githubusercontent.com/81138249/207801835-048f6e52-d7a2-4e2f-b10f-19c4647fe005.mp4

**Comment by matthiasdilger** [comment]
@Meghana-MSFT Thanks, I have done some digging and figured out that this only affects videos with "copyrighted" music added to them. So it might depend on your location whether or not you can play the video in embedded mode.

From the Polly video at https://www.youtube.com/watch?v=7PK05mlvKTg

<img width="936" alt="Screen Shot 2022-12-15 at 15 53 31" src="https://user-images.githubusercontent.com/5625718/207803808-82bef918-676f-42d6-9239-54c0c36f16c6.png">

I don't quite understand why it works for browsers though from the same machine.

**Comment by Meghana-MSFT** [comment]
@matthiasdilger - We are checking this internally. We will get back to you with an update within 48 hours. Thank you.

**Comment by Meghana-MSFT** [comment]
@matthiasdilger - Engineering team has looked into this and said this looks like an issue with the specific Youtube video, and not Teams side as the error message is coming from Youtube embed itself.

**Comment by matthiasdilger** [comment]
@Meghana-MSFT I have tried this again from a different country and it works fine there. The issue seems related to the copyrighted music, whether or not Youtube allows the embedded video. Closing this, as it does not seem easily fixable from the Teams side.
