### ISSUE TITLE
Sign in Loop

### ISSUE THREAD

**Issue by lucidqdreams** [MicrosoftDocs/msteams-docs#771]
I changed my corporate password while teams was signed in.  eventually, it kicked me out with a helpful screen telling me to sign in.  It then signs me automatically in, and out asking me to sign in again.

https://1drv.ms/v/s!An4snZT1mSRu1zUIw77DBiLAIiXs

#groundhogday

**Comment by Gousia-MSFT** [comment]
@lucidqdreams This issue should have been resolved in some time. Are you still facing this issue? If yes, Could you please share logs from:
> %appdata%\Microsoft\Teams\logs.txt

**Comment by lucidqdreams** [comment]
The issue was resolved simply by starting the windowsazureguestagent
manually after each reboot.
