### ISSUE TITLE
Adaptive Card "Something Went Wrong" with Toggle.Visibility action

### ISSUE THREAD

**Issue by anirban-celebal** [MicrosoftDocs/msteams-docs#7718]
I am getting this issue when using an adaptive card with Toggle.Visibility action with Bot framework in MS Teams Channel. The toggle is working and data is being updated as expected but MS Teams keep giving "Something Went Wrong" whenever I use the toggle. 

This is the payload of the adaptive card - 
[AdaptiveCardPayload.txt](https://github.com/MicrosoftDocs/msteams-docs/files/10243775/AdaptiveCardPayload.txt)

I am using botbuilder version 4.18.0 and Adaptive card target version 1.4.

![image](https://user-images.githubusercontent.com/92198341/208044306-1fc7dcff-ca70-474f-b54f-62e9733745e9.png)

**Comment by Prasad-MSFT** [comment]
Hi @anirban-celebal - We have already raised a bug for this issue and engineering team has fixed it internally. We currently don't have an ETA when the fix will be available publicly. It might take couple of weeks to be GA.
Please follow [this](https://github.com/MicrosoftDocs/msteams-docs/issues/7626) thread for further updates.

Thanks!

**Comment by ChetanSharma-msft** [comment]
Engineering team has mentioned that as per latest updates the fix is expected to reach public rings by end of January.

**Comment by AlexanderPBrown** [comment]
THis was fixed very recently.

**Comment by Toleikis** [comment]
We see this issue happening again since 2023-02-13. We are using Power Automate to send adaptive cards on behalf of Power Virtual Agents bot in Teams. Teams client version is 1.6.00.1381 (64-bit). Card target version 1.4.

**Comment by Prasad-MSFT** [comment]
@Toleikis - We tried again to repro this issue by sending card with Toggle.Visibility action via Power Automate. However, its working fine at our end both in MS Teams desktop `(Microsoft Teams Version 1.6.00.4378)` and web client.

![image](https://user-images.githubusercontent.com/62237649/218745644-834a0022-9832-47ba-a31b-c09ccb389275.png)
![image](https://user-images.githubusercontent.com/62237649/218745696-3d0434b1-2243-4020-94d6-dc13b86dccad.png)

Card JSON:

```
{
        "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
        "type": "AdaptiveCard",
        "version": "1.4",
        "body": [
          {
            "type": "TextBlock",
            "text": "**Action.ToggleVisibility example**: click the button to show or hide a welcome message"
          },
          {
            "type": "TextBlock",
            "id": "helloWorld",
            "isVisible": false,
            "text": "**Hello World!**",
            "size": "ExtraLarge"
          }
        ],
        "actions": [
          {
            "type": "Action.ToggleVisibility",
            "title": "Click me!",
            "targetElements": [
              "helloWorld"
            ]
          }
        ]
      }
```

**Comment by michaelslz23** [comment]
My test result is: Adaptive Card Toggle.Visibility action does not work anymore.   No "Something went wrong" message is shown, but just Toggle.Visibility does not work.

**Comment by Prasad-MSFT** [comment]
@michaelslz23 - Your issue is being tracked [here](https://github.com/MicrosoftDocs/msteams-docs/issues/8157). Please follow that thread for further updates. 
Thanks!
