### ISSUE TITLE
Distributing the MS bot to users in other tenant without publishing it to store

### ISSUE THREAD

**Issue by mahavarkarshweta** [MicrosoftDocs/msteams-docs#7722]
Hello Team,

I have a question related to the publishing process and distribution of app.
I have developed a bot in Microsoft teams using developer portal. I would like to make this app available for the beta customers or for testing purpose in some other tenant/ organization. As of now I can see only two options:
1. Publish to org
2. Publish to store
Is there any way I can make it available to the users in other tenant for testing purposes. I want to myself test the bot in some other tenant without publishing it to the store.

If yes, can you please tell me the solution?

And if I go for publish to store, I need to give test accounts as mentioned in your documentation. But the app will be available only to the organization where I have created the app. "you will be needing test accounts" can you elaborate on this, like where should the test accounts be created and what if I am not able to give the test accounts where I have developed the bot.

Please correct me If I have understood it wrong and let me know if you have any further questions.

Thanks,
Shweta

**Comment by Meghana-MSFT** [comment]
@mahavarkarshweta - You can use [Sideload your app in Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/apps-upload) if you want to test and debug an app locally yourself or with other developers. 
You can also sideload your app package in different tenant provided that your app registration is of type multitenant.

**Comment by mahavarkarshweta** [comment]
Thanks Meghana.
I had sideloaded the app. But since many days I was getting app does not exist error when I was uploading the app to other tenants.
But yesterday I tried I was able to.
