### ISSUE TITLE
We couldn't save your tab settings. Please try again. "Invalid tab settings provided: url; "

### ISSUE THREAD

**Issue by prince17dec** [MicrosoftDocs/msteams-docs#7727]
Hi there,

I got an error while trying to save configurable tab. when I click on the save button then I got the error  "We couldn't save your tab settings. Please try again." But on the same, if I click again on the save button then the tab is working.  I got an error in the console as well "Invalid tab settings provided: url;" I tried almost everything adding valid domains and URL and all but nothing is working. 

![Skärmbild 2022-12-19 134820](https://user-images.githubusercontent.com/20600513/208430395-b35c36b5-faf1-4eb9-9a43-3f70c3b4a82b.png)

![Skärmbild 2022-12-19 134840](https://user-images.githubusercontent.com/20600513/208429797-6f7fa563-093e-4516-83b9-9c2428d60a5b.png)

// Manifest
{
    "$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.7/MicrosoftTeams.schema.json",
    "manifestVersion": "1.7",
    "version": "1.2.1",
    "id": "54dg3445-34d4-dfg456-sdfsdfsd-sadfsdf",
    "packageName": "com.test.app",
    "developer": {
        "name": "test",
        "websiteUrl": "https://test.se",
        "privacyUrl": "https://test.se/test1/gdpr/",
        "termsOfUseUrl": "https://test.se"
    },
    "icons": {
        "color": "color.png",
        "outline": "outline.png"
    },
    "name": {
        "short": "Test Name",
        "full": "Test Name"
    },
    "description": {
        "short": "Handle your",
        "full": "Test NameTest NameTest NameTest NameTest NameTest NameTest NameTest NameTest NameTest Name."
    },
    "accentColor": "#EA5B0C",
    "configurableTabs": [
        {
            "configurationUrl": "https://test.se/check/config",
            "canUpdateConfiguration": true,
            "scopes": [
                "team"
            ]
        }
    ],
    "permissions": [
        "identity",
        "messageTeamMembers"
    ],
    "validDomains": [
        "test.se",
    ]
}

//Config
app.getContext().then(async (context) => {
                await (window as any).microsoftTeams.app.initialize();
saveQueue = (id: any) => {
                    (window as any).microsoftTeams.pages.config.registerOnSaveHandler((saveEvent: any) => {
                        const configPromise = (window as any).microsoftTeams.pages.config.setConfig({
                            websiteUrl: 'https://test.se',
                            contentUrl: `https://test.se/collaborative/${id}`,
                            entityId: "grayIconTab",
                            suggestedDisplayName: "test"
                        });
                        configPromise.
                            then((result: any) => {saveEvent.notifySuccess()}).
                            catch((error: any) => {saveEvent.notifyFailure("failure message")});
                    });
                }
})

**Comment by sayali-MSFT** [comment]
@prince17dec - Thanks for reporting your issue.
We will check this at our end and will get back to you.

**Comment by sayali-MSFT** [comment]
@prince17dec - Do you have any more owner in your team? If yes, please ask them to remove you and add as a member, try if you can add app with member permission. once done, ask your team owner to provide you owner permission again.

**Comment by prince17dec** [comment]
Yes, already did this above step still getting the same error.

**Comment by sayali-MSFT** [comment]
@prince17dec -We are not able to repro the scenario. It's working fine from our end.
Microsoft Teams Version 1.5.00.35276 (64-bit).

Could you please try it once?

Refer Sample link -https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/main/samples/meetings-details-tab/csharp/DetailsTab/Views/Home/ConfigureTab.cshtml

```
  microsoftTeams.app.initialize().then(() => {
        microsoftTeams.pages.config.registerOnSaveHandler(function (saveEvent) {
            microsoftTeams.pages.config.setConfig({
                entityId: 'DetailsTabDemo',
                contentUrl: window.location.origin + "/Index",
                configName: 'DetailsTabDemo'
            });
            saveEvent.notifySuccess();
        });
        microsoftTeams.pages.config.setValidityState(true);
    });
```

**Comment by prince17dec** [comment]
Thank you for your reply. It was already fixed. It was a problem with your CDN. I just replace it with NPM package and it is working now.

**Comment by sayali-MSFT** [comment]
@prince17dec - We are closing this issue for now, Please feel free to reopen it, if required.
