### ISSUE TITLE
What is Chat for me url??

### ISSUE THREAD

**Issue by jintae123** [MicrosoftDocs/msteams-docs#7731]
[Enter feedback here]
I can use chat url with "https://teams.microsoft.com/l/chat/0/0?users=useremail".
But If I use my email address, that link can't open "chat for me" chat room.
What is Chat for me url??

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 45541337-ecd7-5cf6-cbe4-3f0d2f39aa79
* Version Independent ID: 6b4203f0-2844-06c9-eaa3-9cc03e6f76c0
* Content: [Create deep links - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links?tabs=teamsjs-v2#generate-a-deep-link-to-a-chat)
* Content Source: [msteams-platform/concepts/build-and-test/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/build-and-test/deep-links.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Meghana-MSFT** [comment]
Can you please check if https://teams.microsoft.com/l/chat/48:notes/messages works?

**Comment by Meghana-MSFT** [comment]
We are checking this with the engineering team, we will get back to you.

**Comment by Meghana-MSFT** [comment]
@jintae123 - Apologies for the delay in response.

Engineering team has confirmed that currently using own email in deeplink to chat ("https://teams.microsoft.com/l/chat/0/0?users=useremail") is not supported. Could you please help by suggesting this feature at [Microsoft feedback portal](https://feedbackportal.microsoft.com/feedback/forum/ad198462-1c1c-ec11-b6e7-0022481f8472).

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, please feel free to reopen it, if required.
