### ISSUE TITLE
[Doc-enhancement] Tab app shows following error: "There was a problem reaching this app"

### ISSUE THREAD

**Issue by SubbaReddi** [MicrosoftDocs/msteams-docs#7745]
Hi Team,
If ShowLoadingIndicatory property set as True in Manifest, it must be handled in web application code. If it is not handled, tab app will not load and shows following error: "**There was a problem reaching this app**"

![image](https://user-images.githubusercontent.com/69682598/208694168-a4882d49-7e39-4c6f-95d8-4dffae3aeb9b.png)

Please add note in the documentation for the same.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f7398066-a52e-7db2-c65c-9f1cf5796077
* Version Independent ID: 2dd1c170-fd52-0c27-1b9a-3664ca9f83c4
* Content: [Create a content page - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/content-page?tabs=teamsjs-v2#show-a-native-loading-indicator)
* Content Source: [msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/tabs/how-to/create-tab-pages/content-page.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Prasad-MSFT** [comment]
Hi @SubbaReddi - This is already documented [here](https://learn.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema#showloadingindicator).
![image](https://user-images.githubusercontent.com/62237649/208839252-d12dfe22-1728-4248-90be-e975f395080d.png)

**Comment by SubbaReddi** [comment]
Hi @Prasad-MSFT,
Agree. If the note mentioned in above documentation along with error or create FAQ, it helps for developer to resolve issue on their own.

**Comment by Prasad-MSFT** [comment]
Hi @surbhigupta12 - Please help here to add more info in the note section mentioning about error details.

In this [note](https://learn.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema#showloadingindicator) section, add an extra line saying "If it's not handled in content pages of your tabs, tab app will not load and will show following error: `There was a problem reaching this app`"
![image](https://user-images.githubusercontent.com/62237649/209077687-f45e2fdf-3f85-4914-b892-73ff70404c32.png)
