### ISSUE TITLE
Carousel pagination does not show

### ISSUE THREAD

**Issue by bangndnguyen** [MicrosoftDocs/msteams-docs#775]
Followed instructions from this docs: https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/cards/cards-reference#card-collections
When run on latest desktop Microsoft Teams app, the pagination does not show.
<img width="549" alt="carousel" src="https://user-images.githubusercontent.com/32898327/60788875-e9ff7280-a187-11e9-98de-600fe0b0f56d.png">

**Comment by bangndnguyen** [comment]
Hello, could anyone from MSFT give me some help with this? I would appreciate it very much.

**Comment by Wajeed-msft** [comment]
We are working on updating the documentation to reflect current behaviour. @clearab - Could you please help here?

**Comment by Gousia-MSFT** [comment]
@bangndnguyen The docs are updated. Thanks!!
