### ISSUE TITLE
Add teams published app to AAD users via API

### ISSUE THREAD

**Issue by Chang025** [MicrosoftDocs/msteams-docs#7753]
We have created an azure bot and linked it with the team's app. Later on, we published this app to our internal organization.

Is there any way we can automatically add the published app to our AAD users via **API**?
Any doc reference would be highly appreciated.

**Comment by sayali-MSFT** [comment]
@Chang025 - Thanks for reporting your issue.
We will check this at our end and will get back to you.

**Comment by sayali-MSFT** [comment]
@Chang025 -There is no API available to automatically add the published app to AAD users.

However to proactively install app in Teams you can follow below doc:
[Use Microsoft Graph to authorize proactive bot installation and messaging in Teams - Teams | Microsoft Learn](https://learn.microsoft.com/en-us/microsoftteams/platform/graph-api/proactive-bots-and-messages/graph-proactive-bots-and-messages?tabs=dotnet#proactive-app-installation-in-teams)

**Comment by Chang025** [comment]
hi @sayali-MSFT 
Thank you for sharing the documentation reference. We have gone through this, until collecting user information there is a detailed API provided, but to trigger sms there is no API mentioned.
Is there any restful API to trigger the message after collecting all the related user information?

The doc reference only provided a way via framework SDK.
reference: https://learn.microsoft.com/en-us/microsoftteams/platform/graph-api/proactive-bots-and-messages/graph-proactive-bots-and-messages?tabs=dotnet#code-snippets

**Comment by sayali-MSFT** [comment]
@Chang025 - We are checking with the engineering team, if there is any API available for this or not and get back to you.
 Thanks!!

**Comment by ChetanSharma-msft** [comment]
Hello @Chang025 - Sorry for delay in response.
We are checking this with engineering team and let you know the updates.

**Comment by ChetanSharma-msft** [comment]
Hello @Chang025 - Sorry for delay in response.
You can use Graph API to install a Teams App for AAD users: https://learn.microsoft.com/en-us/graph/api/userteamwork-post-installedapps?view=graph-rest-1.0&tabs=http&preserve-view=true#example-1-install-an-app-for-a-user

**Comment by Chang025** [comment]
thanks @ChetanSharma-msft for the response, yes we have added it via the same approach as suggested above.
