### ISSUE TITLE
Height for iframe in task module response is decreasing for Teams app in Windows

### ISSUE THREAD

**Issue by Navega** [MicrosoftDocs/msteams-docs#776]
Related to [Dynamic input using a web view](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/messaging-extensions/create-extensions#dynamic-input-using-a-web-view) section.

The height for task modules with an iframe as response is right in Teams web app but not for Windows app.

This is our response:

```return {
      "task": {
        "type": "continue",
        "value": {
          "title": title,
          "height": "large",
          "width": "large",
          "url": link,
          "fallbackUrl": fallback_link,
        }
      }
    }
```

And this is the result:

![thin](https://user-images.githubusercontent.com/16117077/60789672-ef48c700-a15f-11e9-8a25-260bd107dceb.JPG)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aaa0ea75-7363-3ef5-39df-ad07c493c118
* Version Independent ID: ab9a2a6e-e2ca-828f-cd8b-bd9ff98411ab
* Content: [Initiate actions with messaging extensions - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/messaging-extensions/create-extensions#dynamic-input-using-a-web-view)
* Content Source: [msteams-platform/concepts/messaging-extensions/create-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/messaging-extensions/create-extensions.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Trinetra-MSFT** [comment]
We tried your code in both web and windows Teams app. This works fine in both. Can you please provide the repo steps so that we can try it that way. Can you please share BOT id as well.

**Comment by Navega** [comment]
I see the problem for any BOT, but the key that I use is "c8772eea-1f82-4611-aefd-752c76658239".

The steps are:

1. Fetch task from messaging extension, then we return a form.
2. Submit the form to create a task.
3. Offer 2 action buttons to:
a. Inject new task in chat.
b. Open new task in iframe.
4. Click "Open the new task" button.
5. We see the screenshot that I attached in my initial comment.

**Comment by Gousia-MSFT** [comment]
@Navega Are you trying to open one task module from another task module? I tried the steps you have mentioned but I could not repro it. Could you please share your manifest with us?

**Comment by Gousia-MSFT** [comment]
@Navega Please reopen with the requested info if you are still facing issue.
