### ISSUE TITLE
mode.ed

### ISSUE THREAD

**Issue by modearsd** [MicrosoftDocs/msteams-docs#7769]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dac10c25-1625-4f0d-b113-a1fdd7a7a900
* Version Independent ID: dac10c25-1625-4f0d-b113-a1fdd7a7a900
* Content: [Get started - Overview - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/get-started/get-started-overview#app-capabilities-and-development-tools)
* Content Source: [msteams-platform/get-started/get-started-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/get-started/get-started-overview.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by sayali-MSFT** [comment]
@modearsd - Could you please elaborate your requirement, so that we can investigate it from our end.
