### ISSUE TITLE
Capture selection element from adaptive card response in bot framework composer

### ISSUE THREAD

**Issue by azure1github** [MicrosoftDocs/msteams-docs#7778]
How to show another adaptive card according to response of selection of  last adaptive card in bot framework composer.

**Comment by Prasad-MSFT** [comment]
@azure1github - Could you please check if this is what you are looking for?
https://learn.microsoft.com/en-us/power-virtual-agents/advanced-bot-framework-composer-example2#display-a-multi-select-options-list

**Comment by azure1github** [comment]
> @azure1github - Could you please check if this is what you are looking for? https://learn.microsoft.com/en-us/power-virtual-agents/advanced-bot-framework-composer-example2#display-a-multi-select-options-list

No, when attach a adaptive card and select something from it. it will jump to unknown intent and at that time i am unable to  display captured selection of adaptive card

**Comment by Prasad-MSFT** [comment]
@azure1github - Please refer: https://learn.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/sequential-workflows
