### ISSUE TITLE
Deep Links for Files

### ISSUE THREAD

**Issue by icelandgrecian** [MicrosoftDocs/msteams-docs#779]
It is possible to create deep links for editing/viewing files within Teams? Is it possible to deep link using the urls that begin with https://teams.microsoft.com/_#/docx/viewer, though it´s not clear how we would build up the urls

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a891841a-a110-d18e-25c1-fc29e7d4a5e3
* Version Independent ID: c1a11eb8-00d1-e1d2-1e9d-71d059a6478a
* Content: [Create deep links - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/deep-links#feedback)
* Content Source: [msteams-platform/concepts/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/deep-links.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Trinetra-MSFT** [comment]
Are you trying to deep link a file to Bot or Tab ?

**Comment by icelandgrecian** [comment]
We are trying to deep link from a custom tab. We´ve found out that we can use the executeDeepLink JavaScript SDK method and send in a url with the following structure. But have had to figure this out from what is happening on the files tab. This seems to work, but we´d prefer to be using something that is documented.

https://teams.microsoft.com/_#/{docxExtenstion}/viewer/teams/{encodedSharepointFileUrl}/?threadId={channelId}&baseUrl={encodedSharepointBaseUrl}&fileId={sharepointFileId}&ctx={files|new_file}&viewerAction=edit
