### ISSUE TITLE
Property "subscriptionOffer" is not allowed

### ISSUE THREAD

**Issue by v-nikhilsoma** [MicrosoftDocs/msteams-docs#7792]
When we upload the manifest with the version <=1.9, we get the following error: 
"Property "subscriptionOffer" has not been defined and the schema does not allow additional properties".
So, property "subscriptionOffer" is supported only for the manifest versions that are greater than 1.9. So, please mention the same in the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5a3c7a65-c0e1-ac5b-1027-d11edf172092
* Version Independent ID: 5a3c7a65-c0e1-ac5b-1027-d11edf172092
* Content: [Test preview for monetized apps - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/test-preview-for-monetized-apps)
* Content Source: [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md)
* Service: **msteams**
* GitHub Login: @v-ypalikila
* Microsoft Alias: **v-ypalikila**

**Comment by Nivedipa-MSFT** [comment]
@v-nikhilsoma - Thanks for reporting your issue. We will test this and update it accordingly in document.

**Comment by Nivedipa-MSFT** [comment]
@v-nikhilsoma - We have tested this and able to repro it with the version <=1.9, we get the following error:
"Property "subscriptionOffer" has not been defined and the schema does not allow additional properties".

@surbhigupta12 - Could you please help here to add below note:
Property "subscriptionOffer" is supported only for the manifest versions that are greater than 1.9.

Note can be added here: https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/test-preview-for-monetized-apps
