### ISSUE TITLE
Error: "Invalid teamId and/or appId specified" after submit action from Messaging Extension adaptive card 

### ISSUE THREAD

**Issue by Leks12lk** [MicrosoftDocs/msteams-docs#780]
Description:
I have  manifest.json file which contains info about my ME, bot and tab apps. I load the sideload from "Upload custom app" link as a zip file.

I have an adaptive card to be returned from Messaging Extension. This card contains buttons with "Action.Submit" type. In a team chat when User A sends this card from ME, User B clicks action button on that card and get the error "AppsService: getInstalledAppForTeam - Invalid teamId and/or appId specified". The request is not going to the server side. This issue is reproduced for User B only (not for the user which sent the card). 
This issue is not reproduced when uploading app and selecting a Team this app to be added to, and click "Messaging Setup", but it's reproduced when the user invokes ME by himself/herself.

I'm assuming that teamId is lost and the app does't know to what Team the message from ME was sent.

**Comment by Gousia-MSFT** [comment]
@Leks12lk When you send a card from a message extension from a sideloaded app, there is a  different id created for the receiver of the card when he clicks on Submit button. Could you please try sideloading the app to your [private app store](https://docs.microsoft.com/en-us/microsoftteams/tenant-apps-catalog-teams) and install the bot from there? This uses the same id for both the sender and receiver of the card.

**Comment by Leks12lk** [comment]
@Gousia-MSFT it works for me. Thanks for your help.
