### ISSUE TITLE
Office UI Fabric

### ISSUE THREAD

**Issue by damienestewart** [MicrosoftDocs/msteams-docs#781]
Does the full Teams control library work well with office ui fabric or do their styles conflict?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed3343e3-d546-7c4e-6e5c-64af6dd79a77
* Version Independent ID: 09a6a83f-f28b-7054-26c7-31dec6cb6367
* Content: [Using the control library - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/get-started/app-studio-component-library)
* Content Source: [msteams-platform/get-started/app-studio-component-library.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/get-started/app-studio-component-library.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Abhijit-MSFT** [comment]
@damienestewart - Those two styles are designed separately with different visual styles. We looked at few class names and don't see any conflict
