### ISSUE TITLE
Information: ngrok changes, etc.

### ISSUE THREAD

**Issue by elthombre** [MicrosoftDocs/msteams-docs#7829]
I wanted to share the following:

Some information that may be helpful. Please see the following:

https://github.com/pnp/generator-teams/issues/335

and

https://github.com/pnp/generator-teams/issues/337

Should this be cross-referenced here:

https://github.com/OfficeDev/Microsoft-Teams-Samples/issues

**Comment by ChetanSharma-msft** [comment]
Hello @elthombre - Hope you are doing well!!
Could you please elaborate and share the steps that we need to perform here?

**Comment by elthombre** [comment]
@ChetanSharma-msft @Meghana-MSFT , I only wanted to share this information. ngrok is suggested for tunneling with some samples. Global installation with singular auth key installation may not work as described in the one thread.
