### ISSUE TITLE
Is there any workaround for silent auth for bots?

### ISSUE THREAD

**Issue by angie4u** [MicrosoftDocs/msteams-docs#783]
Hi team, is there any workaround for silent auth flow for bots?
I would like to know this is impossible by design or sample code is not ready. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be314181-4800-4d02-cf62-fb276dc7cdd2
* Version Independent ID: 259e41a3-0607-c3f8-f635-f6bce767ad2b
* Content: [Silent authentication and SSO - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/authentication/auth-silent-aad)
* Content Source: [msteams-platform/concepts/authentication/auth-silent-AAD.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/authentication/auth-silent-AAD.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Wajeed-msft** [comment]
Currently, SSO is not available for Bots.

**Comment by angie4u** [comment]
Thanks for the answer! :)

**Comment by billbliss** [comment]
While it's true that SSO isn't available for bots, it's not exactly true that silent auth doesn't work for bots. It's not "as silent" as it is for tabs - you always have to log in at least once - but if your bot stores the refresh token and uses it to get a new token, it will be silent thereafter. The docs could be more clear on this point. @clearab
