### ISSUE TITLE
Some javascript method names are incorrect 

### ISSUE THREAD

**Issue by singhk97** [MicrosoftDocs/msteams-docs#7832]
Errors under the following section:

### Teams Activity Handler > Javascript

<img width="433" alt="image" src="https://user-images.githubusercontent.com/115390646/210622648-7f9ad69c-85a4-417d-8115-e2cb17e4d0e9.png">

- `OnTeamsChannelCreatedAsync` is supposed to be `onTeamsChannelCreated`.
- `OnTeamsChannelDeletedAsync` is supposed to be `onTeamsChannelDeleted`.

The former is the method name in the C# SDK while the latter is the method name in the Javascript SDK. The code snippet section is `Javascript` so the method names should be in line with the Javascript SDK. 

Usually the main difference between C# SDK method names and Javascript SDK names are that:
1. It's `On` in C# and `on` in Javascript.
2. Most if not all method names in C# are suffixed with `Async` while Javascript doesn't have that.

Other method names in this section have also been written incorrectly with the C# method name instead of the Javascript method name. You can take a look at this file to see what the method names are in the Javascript SDK: https://github.com/microsoft/botbuilder-js/blob/main/libraries/botbuilder/src/teamsActivityHandler.ts.

### Bot Logic > Javascript

Same kind of typos in this section as well. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6ec6c2e8-0af6-7984-a780-e5bb6ae113ef
* Version Independent ID: e0c9ab4e-0d6d-a4c5-f705-b78a0f2a87fb
* Content: [Bot activity handlers - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/bots/bot-basics?tabs=csharp)
* Content Source: [msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/bots/bot-basics.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **anclear**

**Comment by ChetanSharma-msft** [comment]
Hello @singhk97 - Sorry for delay in response.
We will investigate on your query and take an action accordingly.

**Comment by Meghana-MSFT** [comment]
@surbhigupta12 - Can you please help to update the following method names in [Teams Activity Handler > Javascript](https://learn.microsoft.com/en-us/microsoftteams/platform/bots/bot-basics?tabs=javascript#tabpanel_1_javascript) Section 

OnTeamsChannelCreatedAsync --> onTeamsChannelCreated
OnTeamsChannelDeletedAsync --> onTeamsChannelDeleted
OnTeamsChannelRenamedAsync --> onTeamsChannelRenamed
OnTeamsTeamRenamedAsync --> onTeamsTeamRenamed
OnTeamsMembersAddedAsync --> onTeamsMembersAdded
OnTeamsMembersRemovedAsync --> onTeamsMembersRemoved
