### ISSUE TITLE
Is Teams bot SSO still only supported in 1:1 chat?

### ISSUE THREAD

**Issue by a1exwang** [MicrosoftDocs/msteams-docs#7834]
Previously on Docs, this is stated clearly [here](https://github.com/MicrosoftDocs/msteams-docs/blob/90215d641026e72cf66d61e4e35401c5b9f7e66e/msteams-platform/bots/how-to/authentication/auth-aad-sso-bots.md#use-sso-authentication-for-bots)

<img width="814" alt="image" src="https://user-images.githubusercontent.com/9698542/210748038-0aa18915-18af-443b-acf3-5edd54d86fff.png">

But currently I cannot find it. If I add my SSO bot to a team and trigger an SSO command, the bot builder SDK (v4.18) reports:
```
 [onTurnError] unhandled error: DialogContextError: SSO only supported in 1:1 conversations
```

So could you please state this clearly on Docs whether this is supported or not?

**Comment by ChetanSharma-msft** [comment]
Hello @a1exwang - Sorry for delay in response.

@surbhigupta12 - Could you please help us here to add the note in the documentation?

**Comment by surbhigupta12** [comment]
Since the Authentication module has been revamped. This page does not exists. However, we have added this note to the relevant page.
