### ISSUE TITLE
Tab Context contains information for teamsjs v1, when it explicitly says it's for v2

### ISSUE THREAD

**Issue by eoinobrien** [MicrosoftDocs/msteams-docs#7839]
Was going back through old bugs to see how they turned out and noticed that while #6286 had been fixed by @erikadoyle with #6448, the main issue I had was reverted two weeks later with #6502. Can we remove the context details that are related to v1?

Thanks

---
#### Document details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8dfa1a29-bcf4-0cc5-ae3a-b185a00fd7bc
* Version Independent ID: c68181e1-151b-fc78-2671-fe9b397b702e
* Content: [Get context for your tab - Teams](https://learn.microsoft.com/en-gb/microsoftteams/platform/tabs/how-to/access-teams-context?tabs=teamsjs-v2)
* Content Source: [msteams-platform/tabs/how-to/access-teams-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/tabs/how-to/access-teams-context.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by ChetanSharma-msft** [comment]
Hello @eoinobrien - Sorry for delay in response.
We will further investigate on your query and will take an action accordingly.

**Comment by Meghana-MSFT** [comment]
@eoinobrien - we have informed the doc team about the changes that have been reverted. Document will be updated.
