### ISSUE TITLE
Creating duplicating Extension Command in what can i do ribbon

### ISSUE THREAD

**Issue by pashu1234** [MicrosoftDocs/msteams-docs#784]
Manifest Structure :-

"bots": [
    {
      "botId": "#####",
     "needsChannelSelector": false,
      "isNotificationOnly": false,
      "scopes": [ "personal","team"],
     "commandLists": [
        {
         "scopes": ["personal","team"],
          "commands": [
            {"title": "Help", "description": "How to use BravoNow ?"}
          ]
        }
      ]
    }
  ],

  "composeExtensions": [
    {
      "botId": "#####",
      "canUpdateConfiguration": true,
      "commands": [
        {
          "id": "BravoNow",
          "description": "Bravo recognition platform",
          "title": "BravoNow",
          "type": "action",
          "fetchTask": true,
          "initialRun": true,
          "parameters": [
            {"name": "Name","title": "Title"  }
          ]
        }
      ]
    }
  ],

My Manifest Structure is for Bot And Extension, after installing Bot I am Observing below Issues.

Why It is duplicating the Extension Command (in What can i do ribbon)? Am I missing anything in manifest ? I didn’t found any key/setting in manifest schema to control the behavior.  

![Issues](https://user-images.githubusercontent.com/52487102/60947930-6ec8c880-a30f-11e9-8ce6-30077839667e.png)

**Comment by Gousia-MSFT** [comment]
@pashu1234 Could you please try sideloading the app to your [private app store](https://docs.microsoft.com/en-us/microsoftteams/tenant-apps-catalog-teams) and install the bot from there? This will prevent creating different id's when app is added to personal scope and teams scope.

**Comment by pashu1234** [comment]
@Gousia-MSFT  we have already enabled the sideloading and we are adding the app through the private app store, still we are facing this issue.

**Comment by Gousia-MSFT** [comment]
@pashu1234 Could you please check if there are multiple instances of your app in different teams, delete them and install again?

**Comment by pashu1234** [comment]
@Gousia-MSFT  we have tries (uninstalling the all  app from other Teams).
 we have even tried with the New Tenant where App Is never configured.
 Issue is appearing when i will install the BOT and Extension in the Same Team.

**Comment by Gousia-MSFT** [comment]
@pashu1234 Could you please share your complete manifest?

**Comment by Wajeed-msft** [comment]
Please re-open with your app manifest which can be used to repro this.

**Comment by pashu1234** [comment]
Thank you
@Gousia-MSFT  @Wajeed-msft  

Issue Resolved..

issue was appearing because of the multiple instances of your app.

Get the **BravoNow** App from store to use.
