### ISSUE TITLE
Cannot log into Teams - "Failed to start the trial" error

### ISSUE THREAD

**Issue by aabuhijleh** [MicrosoftDocs/msteams-docs#785]
I'm trying to follow this [article](https://docs.microsoft.com/en-us/microsoftteams/platform/get-started/get-started-nodejs-app-studio)

I've signed up for the Office 365 Developer program and got a new test account and followed [this article to prepare the tenant](https://docs.microsoft.com/en-us/microsoftteams/platform/get-started/get-started-tenant)

Cannot get passed this screen below. I've tried both the web and the desktop version.

**Error screen + console errors:**
![start_trial](https://user-images.githubusercontent.com/42934634/60953748-72a41d00-a306-11e9-92b3-bb45c8133761.PNG)

What am I doing wrong?

**Comment by Trinetra-MSFT** [comment]
Microsoft Teams with office365 tenant id works with different license and Roles, Please try to set the License and Roles as per required.  There are different roles to be set for Teams , Please check your tenant id have specified roles set or not :

![Roles](https://user-images.githubusercontent.com/50989436/61051021-ef69f080-a405-11e9-8ed3-958f39541fd2.png)

We also do check the License provided for o365Developer 

![License](https://user-images.githubusercontent.com/50989436/61051189-23451600-a406-11e9-8918-87d336966d1e.png)

**Comment by aabuhijleh** [comment]
Thanks @Trinetra-MSFT. I'm able to login now.
