### ISSUE TITLE
Response to submitted webhook messages has changed

### ISSUE THREAD

**Issue by MichaelUrman** [MicrosoftDocs/msteams-docs#7852]
The section "Send messages using cURL and PowerShell" documents that if the POST succeeds, it will return a body of `1`. That's not what I see today; instead I see a JSON blob:

```json
{"version":"1.1","content":{"headers":[{"key":"Content-Type","value":["text/plain; charset=utf-8"]}]},"statusCode":200,"reasonPhrase":"OK","headers":[],"trailingHeaders":[],"requestMessage":null,"isSuccessStatusCode":true}
```

Assuming this change is not a bug, it would be good to clarify the new response format. The change appears to cause errors elsewhere such as reported on atc0005/go-teams-notify#197. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 28316a67-22fa-8a05-1ae0-fbe1c5720ef9
* Version Independent ID: 8a250e46-2a30-af86-839d-9f83a8b48041
* Content: [Create and send messages - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-using?tabs=cURL#post-a-message-to-the-webhook-using-curl)
* Content Source: [msteams-platform/webhooks-and-connectors/how-to/connectors-using.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/webhooks-and-connectors/how-to/connectors-using.md)
* Service: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by yashaswinoonela** [comment]
@MichaelUrman Issue Relates to: https://github.com/MicrosoftDocs/msteams-docs/issues/7830

**Comment by ChetanSharma-msft** [comment]
Hello @MichaelUrman - We will check the updates with engineering team and let you know.

**Comment by Meghana-MSFT** [comment]
@MichaelUrman - The same issue is being tracked here at https://github.com/MicrosoftDocs/msteams-docs/issues/7830. Please follow the above thread for further updates. Thanks.

**Comment by MichaelUrman** [comment]
Confirmed per update on #7830 I now see the documented response body of `1`.
