### ISSUE TITLE
Valid domain cannot use tunnel site

### ISSUE THREAD

**Issue by stepro71** [MicrosoftDocs/msteams-docs#786]
I get this error and then "something went wrong" when trying to distribute the app.
Sideloading is enabled for the tennant

**Comment by Gousia-MSFT** [comment]
@stepro71 Could you please share a screenshot of youe valid domains? Please list out your valid domains like specified [here](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema#validdomains).

**Comment by stepro71** [comment]
I am using a domain in the form of https://yourteamsapp.ngrok.io/ and Ngrok to tunnel to my development pc

**Comment by stepro71** [comment]
Sorry, closing was in error

**Comment by laujan** [comment]
Hi, you can use ngrok to test your app in Teams, but it must be on a hosted site prior to submission to the Teams store. Have you tried using the Teams web-based version -- https://teams.microsoft.com --while testing? If so, when the “something went wrong” message appeared, did the dev tools console return any errors?

**Comment by stepro71** [comment]
This is solved. The reason for my error  had nothing to do with the valid domains. I loaded the .manifest - file instead of the -zip file.  Deleted App and reconfigured with uploading the zip file - everything ok.
Thank you for your help.
