### ISSUE TITLE
People Picker in Adaptive Card no longer working in Teams

### ISSUE THREAD

**Issue by StevieBleeds** [MicrosoftDocs/msteams-docs#7879]
We have a number of Teams Bots in our organisation, some of which are using the People Picker in an Adaptive Card.

However, we have noticed from this afternoon that the People Picker is no longer working in either the Web version of Teams nor the Client version (tested on Preview v1.5.00.33362) either.

Instead of being able to type in the field, it is now just a drop-down choice field and users are not able to type in the field. This has been working absolutely fine up until this afternoon.  Can you advise please?

<img width="343" alt="people_picker" src="https://user-images.githubusercontent.com/39305886/211609253-4232ea02-e0df-4a93-904a-f9eb643562af.PNG">

{
    "type": "AdaptiveCard",
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.4",
    "body": [
        {
            "type": "TextBlock",
            "text": "Step 2 of 5",
            "size": "Large",
            "horizontalAlignment": "Left",
            "weight": "Bolder",
            "wrap": true
        },
        {
            "type": "TextBlock",
            "text": "Please provide a suitable and descriptive name for your team, site or plan",
            "weight": "Bolder",
            "separator": true,
            "wrap": true
        },
        {
            "type": "Input.Text",
            "placeholder": "You can use up to 35 letters including numbers and dashes",
            "id": "NameInput",
            "isRequired": true,
            "errorMessage": "Please provide a suitable name for your team.",
            "maxLength": 35,
            "regex": "^[A-Za-z0-9 -]*[A-Za-z0-9][A-Za-z0-9 -]*$"
        },
        {
            "type": "TextBlock",
            "text": "Please provide the names or email addresses of three owners for this team, site or plan. *Please include yourself if you require access*",
            "weight": "Bolder",
            "wrap": true
        },
        {
            "type": "Input.ChoiceSet",
            "choices.data": {
                "type": "Data.Query",
                "dataset": "graph.microsoft.com/users"
            },
            "placeholder": "Enter a name or email address",
            "id": "Owner1",
            "isRequired": true,
            "errorMessage": "Please provide a name or email address for the first owner."
        },
        {
            "type": "Input.ChoiceSet",
            "choices.data": {
                "type": "Data.Query",
                "dataset": "graph.microsoft.com/users"
            },
            "placeholder": "Enter a name or email address",
            "id": "Owner2",
            "isRequired": true,
            "errorMessage": "Please provide a name or email address for the second owner."
        },
        {
            "type": "Input.ChoiceSet",
            "choices.data": {
                "type": "Data.Query",
                "dataset": "graph.microsoft.com/users"
            },
            "placeholder": "Enter a name or email address",
            "id": "Owner3",
            "isRequired": true,
            "errorMessage": "Please provide a name or email address for the third owner."
        },
        {
            "type": "ActionSet",
            "actions": [
                {
                    "type": "Action.Submit",
                    "title": "Next"
                },
                {
                    "type": "Action.Submit",
                    "title": "Cancel",
                    "data": {
                        "msteams": {
                            "type": "messageBack",
                            "value": "Cancel"
                        },
                        "id": "Cancel"
                    },
                    "associatedInputs": "none"
                }
            ]
        }
    ]
}

**Comment by ChetanSharma-msft** [comment]
Hello @StevieBleeds - Thanks for raising your issue.
We will investigate on it and let you know the updates.

**Comment by Meghana-MSFT** [comment]
@StevieBleeds - We tried this at our end, and we are able to search for user and select them, sharing a video of the same.
We checked in both Teams web client and Desktop(1.6.00.869) client.

https://user-images.githubusercontent.com/81138249/211826406-d0de8b43-a93c-4ac7-be39-662845c0f704.mp4

Can you please let us know if you are doing it differently, so that it will help us with having a local repro?

**Comment by StevieBleeds** [comment]
It's working for me now as well. Thank you for testing.

**Comment by Meghana-MSFT** [comment]
Thank you for confirming. We are closing this issue. Please feel free to reach out to us if you have any questions. Thanks.
