### ISSUE TITLE
Conversations started that reference two files removes each of their unique conversations

### ISSUE THREAD

**Issue by drewling390** [MicrosoftDocs/msteams-docs#788]
If you start a new conversation with two files and when you already have unique conversations for each of those files, you will no longer be able to access those unique conversations in the File view.

**Comment by drewling390** [comment]
To recreate:

1. Post File 1 to Teams and start a new conversation and post "File 1"
2. Post a File 2 to Teams and start a new conversation and post "File 2"
3. Start a new conversation and attached those two files to the conversation and post "Both files"
4. Open File 1 in File view and open the conversation. Only the "Both file" conversation will remain and the "File 1" item is now lost.

**Comment by Gousia-MSFT** [comment]
@drewling390 Thanks for reporting this. We have raised a bug for this and we are looking into it.
