### ISSUE TITLE
Acquire access token section is incorrect 

### ISSUE THREAD

**Issue by svrooij** [MicrosoftDocs/msteams-docs#7888]
the [acquire access token](https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/tab-sso-graph-api?tabs=dotnet#acquire-access-token-for-ms-graph) section mixes getting a token with the OBO flow (recommended) and getting a token client side.

> You can use Microsoft Authentication Library (MSAL) for fetching the token from the client side.

Suggests that the first code that follows will be code to get a token in the client side.

The link "Configure your client-side code to fetch access token using msal" also suggests that there will be client side code. That link links to the next section with clearly shows backend code (`ConfidentialClientApplicationBuilder` should **NEVER** be used in client-side code).

My suggestion (apart from implementing SSO to use MSAL with PKCE in teams):
Provide the developers with an actual sample on how you currently can utilize MSAL in the client-side to get a token for graph. And rewrite the initial section to not mix the two flows. This makes it really confusing and you're bound to get questions like: "How do I use the `msal.ConfidentialClientApplication` in the client, it tells me it cannot be used in the browser."

![image](https://user-images.githubusercontent.com/1292510/211803547-9d64c21d-6d86-4998-ab34-18b2244cb8b7.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a44ac17f-15cd-8809-e885-bcc8e48b4749
* Version Independent ID: a44ac17f-15cd-8809-e885-bcc8e48b4749
* Content: [Extend tab app with Microsoft Graph permissions - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/tab-sso-graph-api?tabs=dotnet)
* Content Source: [msteams-platform/tabs/how-to/authentication/tab-sso-graph-api.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/tabs/how-to/authentication/tab-sso-graph-api.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Prasad-MSFT** [comment]
Hi @surbhigupta12 - Could you please help here to update the [doc section](https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/tab-sso-graph-api?tabs=nodejs#acquire-access-token-for-ms-graph:~:text=After%20you%27ve%20configured%20Graph%20permissions%20in%20Azure%20AD%3A) as below:

After you've configured Graph permissions in Azure AD:

- Get id token from Teams client
- Exchange the id token with server-side token

**Get id token from Teams client:**
```
microsoftTeams.authentication.getAuthToken().then((result) => {
    //result contains the id token
            console.log(result);
        })
```
**Exchange the id token with server-side token:**
The following code provides an example of OBO flow to fetch access token from the Teams client using MSAL.
**C# :**
```
IConfidentialClientApplication app = ConfidentialClientApplicationBuilder.Create(<"Client id">)
                                                .WithClientSecret(<"Client secret">)
                                                .WithAuthority($"https://login.microsoftonline.com/<"Tenant id">")
                                                .Build();
            try
            {
                var idToken = <"Client side token">;
                UserAssertion assert = new UserAssertion(idToken);
                List<string> scopes = new List<string>();
                scopes.Add("https://graph.microsoft.com/User.Read");
                // Acquires an access token for this application (usually a Web API) from the authority configured in the application.
                var responseToken = await app.AcquireTokenOnBehalfOf(scopes, assert).ExecuteAsync();
                return responseToken.AccessToken.ToString();
            }
            catch (Exception ex)
            {
                return ex.Message;
            }
        }
```
**Node.js:**
[SDK reference](https://learn.microsoft.com/en-us/javascript/api/@azure/msal-node/confidentialclientapplication?view=azure-node-latest#@azure-msal-node-confidentialclientapplication-acquiretokenonbehalfof&preserve-view=true)

[sample code reference](https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/main/samples/tab-sso/nodejs/src/server/tabs.js#L51-L94)

```
// Exchange client Id side token with server token
  app.post('/getProfileOnBehalfOf', function(req, res) {
        var tid = < "Tenant id" >
    var token = < "Client side token" >
    var scopes = ["https://graph.microsoft.com/User.Read"];

        // Creating MSAL client
        const msalClient = new msal.ConfidentialClientApplication({
            auth: {
                clientId: < "Client ID" >,
                clientSecret: < "Client Secret" >
      }
        });

        var oboPromise = new Promise((resolve, reject) => {
            msalClient.acquireTokenOnBehalfOf({
                authority: `https://login.microsoftonline.com/${tid}`,
                oboAssertion: token,
                scopes: scopes,
                skipCache: true
            }).then(result => {
                console.log("Token is: " + result.accessToken);
            }).catch(error => {
                reject({ "error": error.errorCode });
            });
        });
```

If you need to access Microsoft Graph data, configure your server-side code to:


1. Validate the access token. For more information, see [Validate the access token](https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/tab-sso-code#validate-the-access-token).
2. Initiate the OAuth 2.0 OBO flow with a call to the Microsoft identity platform that includes the access token, some metadata about the user, and the credentials of the tab app (its app ID and client secret). The Microsoft identity platform will return a new access token that can be used to access Microsoft Graph.
3. Get data from Microsoft Graph by using the new token.
4. Use token cache serialization in MSAL.NET to cache the new access token for multiple, if required.


Additionally, it would be good to add below sample references at the end of this page.
https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/69c76fded29d7ae0fde49841d4ec9af7597ceedd/samples/tab-sso
