### ISSUE TITLE
Meetings are only showing in my outlook if i accept the meetings or i have to restart my outlook

### ISSUE THREAD

**Issue by NaveenAttri** [MicrosoftDocs/msteams-docs#789]
Meetings are only showing in my outlook if i accept the meetings or i have to restart my outlook

**Comment by NaveenAttri** [comment]
As i received the meeting invite , its not showing up in calender in outlook untill i accept the meeting or if i restart the outlook, calender shows the meetings.

**Comment by Gousia-MSFT** [comment]
@NaveenAttri Is this related to Microsoft Teams meetings?

**Comment by NaveenAttri** [comment]
yes, Its regarding Microsoft Teams meetings.

**Comment by Gousia-MSFT** [comment]
@NaveenAttri Could you please check if you are able to see the meetings in outlook web?

**Comment by Gousia-MSFT** [comment]
Please re-open if you are still facing the issue.
