### ISSUE TITLE
Missing commands scopes in commandList

### ISSUE THREAD

**Issue by joarobles** [MicrosoftDocs/msteams-docs#7900]
When editing `manifest.template.json` to add commands, the `scopes` property is missing, which causes TeamsFX to fail with the following error when uploading the app to Developers Portal:

```
× DeveloperPortalAPIFailed: API call to Developer Portal failed: Error, Request failed with status code 422, API name: create-app, X-Correlation-ID: 74be206a-2142-4e1c-b94b-f07ff6093fcf. This may come from some intermittent service error. Please wait for a few minutes and retry the current step. data: "Error mapping types.\r\n\r\nMapping types:\r\nApplicationManifest -> AppDefinition\r\nAppStudio.API.Models.ApplicationManifest -> AppStudio.API.Models.AppDefinition\r\n\r\nType Map configuration:\r\nApplicationManifest -> AppDefinition\r\nAppStudio.API.Models.ApplicationManifest -> AppStudio.API.Models.AppDefinition\r\n\r\nDestination Member:\r\nBots\r\n"
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7d34d2c7-700e-f579-b7b2-0549ace809fd
* Version Independent ID: 7d34d2c7-700e-f579-b7b2-0549ace809fd
* Content: [Command bot in Teams - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/command-bot-in-teams)
* Content Source: [msteams-platform/bots/how-to/conversations/command-bot-in-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/bots/how-to/conversations/command-bot-in-teams.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **v-amprasad**

**Comment by ChetanSharma-msft** [comment]
Hello @joarobles - Thanks for reporting your issue.
We will investigate and let you know the updates.

**Comment by Nivedipa-MSFT** [comment]
@joarobles - The scopes property in commandLists is required.
![image](https://user-images.githubusercontent.com/92150070/212260187-b5b54762-55cd-4ae6-976e-ee22fd3f5d64.png)

When we upload the manifest via sideloading or developer portal without scopes property, we get following error.
bots[0].commandLists[0] Required properties are missing from object: ["scopes"].

![image](https://user-images.githubusercontent.com/92150070/212260606-5239f7a9-2e02-47da-9b60-ac33fb62f114.png)

@surbhigupta12 - Could you please update the below code:

"commandLists": [
      {
         "scopes": [
            "team",
            "groupchat"
          ],
        "commands": [
            {
                "title": "helloWorld",
                "description": "A helloworld command to send a welcome message"
            },
            {
                "title": "doSomething",
                "description": "A sample do something command"
            }
        ]
      }
    ]
    
Code needs to be updated here: https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/command-bot-in-teams#add-command-and-response

**Comment by joarobles** [comment]
Hi there!
Thanks for your reply, I'm aware that `scopes` is required in `commandList`, the reported issue is that the `scopes` property is missing in the docs examples in https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/bots/how-to/conversations/command-bot-in-teams.md#add-command-and-response, step 1.

**Comment by Nivedipa-MSFT** [comment]
@joarobles - Thanks for reporting your issue. We will update the changes accordingly in document and inform you once its updated.

@surbhigupta12 - Could you please help here to update the document here.
