### ISSUE TITLE
Provided sample code snippet are not available in the sample code linked to this page.

### ISSUE THREAD

**Issue by Pawan-MSFT** [MicrosoftDocs/msteams-docs#7910]
[Enter feedback here]
1. In the C# code snippet we can see below two lines which are not available in .Net 6.0.

string content = await this.Request.Content.ReadAsStringAsync();
Activity incomingActivity = JsonConvert.DeserializeObject<Activity>(content);

Could you please help us to update these lines with below 
```
  // This method is to read the request body content
  string content;
  using (var reader = new StreamReader(Request.Body))
  {
      content = await reader.ReadToEndAsync();
  }
```
2. Also could you please help us to add the references like below 
![image](https://user-images.githubusercontent.com/117965661/212904964-2c207174-f20e-4d0d-b1f7-b76de746605d.png)

Sample code reference: https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/main/samples/outgoing-webhook/csharp/Controllers/SampleController.cs#L20

3. For Nodejs code snippet section could you please help us to add the references like below 
![image](https://user-images.githubusercontent.com/117965661/212906722-8789a092-4064-4adf-9a55-e31b8a2e7f86.png)

Sample code reference: 
https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/main/samples/outgoing-webhook/nodejs/app.js#L30 
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bb9c5bd5-1ac6-dcc8-4ed6-d6aad2432776
* Version Independent ID: 43e90995-bba4-86b6-1f1c-ab749e546a4b
* Content: [Create an Outgoing Webhook - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-outgoing-webhook?tabs=urljsonpayload%2Cdotnet)
* Content Source: [msteams-platform/webhooks-and-connectors/how-to/add-outgoing-webhook.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/webhooks-and-connectors/how-to/add-outgoing-webhook.md)
* Service: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Meghana-MSFT** [comment]
@surbhigupta12 - Can you please help here to update the document with above mentioned changes.

**Comment by v-npaladugu** [comment]
@Meghana-MSFT, the links provided to update the meeting APIs article sample references (#2 and #3) through this issue are rendering to outgoing webhooks. Request you to please update us on the above said sample references.

**Comment by Meghana-MSFT** [comment]
@v-npaladugu - We need to add links to sample code references for [C#](https://learn.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-outgoing-webhook?tabs=urljsonpayload%2Cdotnet#tabpanel_2_dotnet) and [Javascript/NodeJs](https://learn.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-outgoing-webhook?tabs=urljsonpayload%2Cjavascript#tabpanel_2_javascript) in Outgoing webhook doc. Meetings apps API screenshot was shared as a reference. 

@Pawan-MSFT - Can you please confirm here?

**Comment by v-npaladugu** [comment]
Sure @Meghana-MSFT we will update the docs
