### ISSUE TITLE
New doc

### ISSUE THREAD

**Issue by 16CentAstrology** [MicrosoftDocs/msteams-docs#7911]
[new software)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1c9cc6be-8ff3-de89-fa46-6bc355249626
* Version Independent ID: 1c9cc6be-8ff3-de89-fa46-6bc355249626
* Content: [Create Teams conversation bot - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/sbs-teams-conversation-bot?tutorial-step=6)
* Content Source: [msteams-platform/sbs-teams-conversation-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/sbs-teams-conversation-bot.yml)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Prasad-MSFT** [comment]
@16CentAstrology - Could you please provide more details on your issue?

**Comment by ChetanSharma-msft** [comment]
Hello @16CentAstrology - Looks like it is an invalid issue.
We are closing this issue for now, please feel free to reopen it, if required.
