### ISSUE TITLE
Alignment issue with bot framework web chat adaptive cards

### ISSUE THREAD

**Issue by samthrusha123** [MicrosoftDocs/msteams-docs#7917]
I want to have two action button one is submit another is show card type. When user clicks on show card type button I want to ask user to enter some comments.

![image](https://user-images.githubusercontent.com/44087954/213164393-084be85d-a16a-4bdb-bd83-998126f4fbce.png)

Comments are coming only on the right side. How can we have it all over? like full width?

**Code**

`{
    "type": "AdaptiveCard",
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.3",
    "body": [
        {
            "type": "TextBlock",
            "text": "Did that answer your question?",
            "wrap": true
        },
        {
            "type": "ColumnSet",
            "columns": [
                {
                    "type": "Column",
                    "width": "stretch",
                    "items": [
                        {
                            "type": "ActionSet",
                            "actions": [
                                {
                                    "type": "Action.Submit",
                                    "title": "Yes",
                                    "data": {
                                        "question": "ceo",
                                        "answer": "test",
                                        "text": "submit-feedback",
                                        "IsAnswerHelpFul": true
                                    }
                                }
                            ]
                        }
                    ]
                },
                {
                    "type": "Column",

                    "items": [
                        {
                            "type": "ActionSet",
                            "actions": [
                                {
                                    "type": "Action.ShowCard",
                                    "title": "Action.ShowCard",
                                    "card": {
                                        "type": "AdaptiveCard",
                                        "width":"full",
                                        "body": [
                                            {
                                                "type": "Input.Text",
                                                "placeholder": "Please enter comments",
                                                "id": "comments",
                                                "label": "Comments",
                                                "value": "",
                                                "isRequired": true,
                                                "errorMessage": "Please fill comments"
                                            }
                                        ],
                                        "actions": [
                                            {
                                                "type": "Action.Submit",
                                                "title": "Yes",
                                                "data": {
                                                    "question": "ceo",
                                                    "answer": "test",
                                                    "text": "submit-feedback",
                                                    "IsAnswerHelpFul": true
                                                }
                                            }
                                        ]
                                    }
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]
}`

**Comment by ChetanSharma-msft** [comment]
Hello @samthrusha123 - Thanks for raising your issue.
We will investigate on this and let you know the updates.

**Comment by Meghana-MSFT** [comment]
@samthrusha123 - Can you please try below JSON and let us know if that helps. Attaching a screenshot as for your reference.

![image](https://user-images.githubusercontent.com/81138249/213421999-389e50c4-ac13-421c-bd6f-d1dfa48b75dd.png)


```
{
  "type": "AdaptiveCard",
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "version": "1.3",
  "body": [
    {
      "type": "TextBlock",
      "text": "Did that answer your question?",
      "wrap": true
    },
    {
      "type": "ColumnSet",
      "columns": [
        {
          "type": "Column",
          "width": "stretch",
          "items": [
            {
              "type": "ActionSet",
              "actions": [
                {
                  "type": "Action.Submit",
                  "title": "Yes",
                  "data": {
                    "question": "ceo",
                    "answer": "test",
                    "text": "submit-feedback",
                    "IsAnswerHelpFul": true
                  }
                },
                {
                  "type": "Action.ShowCard",
                  "title": "Action.ShowCard",
                  "card": {
                    "type": "AdaptiveCard",
                    "width": "full",
                    "body": [
                      {
                        "type": "Input.Text",
                        "placeholder": "Please enter comments",
                        "id": "comments",
                        "label": "Comments",
                        "value": "",
                        "isRequired": true,
                        "errorMessage": "Please fill comments"
                      }
                    ],
                    "actions": [
                      {
                        "type": "Action.Submit",
                        "title": "Yes",
                        "data": {
                          "question": "ceo",
                          "answer": "test",
                          "text": "submit-feedback",
                          "IsAnswerHelpFul": true
                        }
                      }
                    ]
                  }
                }

              ]
            }
          ]
        }
      ]
    }
  ]
}
```

Here we are adding the action buttons in one column. If we add 2 different columns then show card and comments will take width of the second column only.

**Comment by samthrusha123** [comment]
> @samthrusha123 - Can you please try below JSON and let us know if that helps. Attaching a screenshot as for your reference.
> 
> ![image](https://user-images.githubusercontent.com/81138249/213421999-389e50c4-ac13-421c-bd6f-d1dfa48b75dd.png)
> 
> ```
> {
>   "type": "AdaptiveCard",
>   "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
>   "version": "1.3",
>   "body": [
>     {
>       "type": "TextBlock",
>       "text": "Did that answer your question?",
>       "wrap": true
>     },
>     {
>       "type": "ColumnSet",
>       "columns": [
>         {
>           "type": "Column",
>           "width": "stretch",
>           "items": [
>             {
>               "type": "ActionSet",
>               "actions": [
>                 {
>                   "type": "Action.Submit",
>                   "title": "Yes",
>                   "data": {
>                     "question": "ceo",
>                     "answer": "test",
>                     "text": "submit-feedback",
>                     "IsAnswerHelpFul": true
>                   }
>                 },
>                 {
>                   "type": "Action.ShowCard",
>                   "title": "Action.ShowCard",
>                   "card": {
>                     "type": "AdaptiveCard",
>                     "width": "full",
>                     "body": [
>                       {
>                         "type": "Input.Text",
>                         "placeholder": "Please enter comments",
>                         "id": "comments",
>                         "label": "Comments",
>                         "value": "",
>                         "isRequired": true,
>                         "errorMessage": "Please fill comments"
>                       }
>                     ],
>                     "actions": [
>                       {
>                         "type": "Action.Submit",
>                         "title": "Yes",
>                         "data": {
>                           "question": "ceo",
>                           "answer": "test",
>                           "text": "submit-feedback",
>                           "IsAnswerHelpFul": true
>                         }
>                       }
>                     ]
>                   }
>                 }
> 
>               ]
>             }
>           ]
>         }
>       ]
>     }
>   ]
> }
> ```
> 
> Here we are adding the action buttons in one column. If we add 2 different columns then show card and comments will take width of the second column only.

In teams channel it's coming fine can you try same JSON in bot framework web chat?

**Comment by ChetanSharma-msft** [comment]
Hello @samthrusha123 - Do you mean bot framework emulator?
If not, could you please share the repro steps, so that we can try it?

**Comment by samthrusha123** [comment]
> Hello @samthrusha123 - Do you mean bot framework emulator? If not, could you please share the repro steps, so that we can try it?

No In adaptive card designer, when I select bot framework webchat button are coming one by one

![image](https://user-images.githubusercontent.com/44087954/213663646-dcff2a8a-854e-4bc6-a1a9-8094d37d52e3.png)

For teams it's coming side by side

![image](https://user-images.githubusercontent.com/44087954/213663882-0d068f44-2205-4875-bc76-8dbf776e4c65.png)

**Comment by Meghana-MSFT** [comment]
We are able to repro this issue using bot framework web chat. We will check internally and get back to you.

**Comment by Meghana-MSFT** [comment]
We have raised a bug for the same, we will keep you posted on the updates. Thanks.

**Comment by stevkan** [comment]
@samthrusha123 - I believe passing in a custom Adaptive Cards [Host Config](https://learn.microsoft.com/en-us/adaptive-cards/rendering-cards/host-config) (which Web Chat fully supports) may solve your problem. In particular, changing the `actions.actionsOrientation` property to `horizontal`.

As you can see, Web Chat has a default [host config](https://github.com/microsoft/BotFramework-WebChat/blob/main/packages/bundle/src/adaptiveCards/Styles/adaptiveCardHostConfig.ts#L103) that it loads where the `actionsOrientation` property is set to `vertical`. However, when I override the default using the below implementation alongside the card provided by @Meghana-MSFT, the card's buttons are displayed side-by-side.

My recommendation would be to copy the values from the default host config and pass those into your custom host config and then change the `actionsOrientation` value (and any others you may want). Just be aware that, as far as I'm aware, this change applies to all circumstances where there are multiple buttons.

One other note: The Adaptive Cards Designer is a great resource for testing cards in different clients like Web Chat, Teams, and others. However, it has a static host config that I don't believe can be altered. So, the only way to test Web Chat with a custom host config is to spin up an instance of Web Chat and test in your own development environment.

```js
const hostConfig= {
    containerStyles: {
      default: {
        foregroundColors: {
          default: {
            default: bubbleTextColor,
            subtle
          },
          accent: {
            default: accent,
            subtle: '#0078D4'
          },
          attention: {
            default: '#D13438',
            subtle: '#A4262C'
          },
          dark: {
            default: '#000000',
            subtle: '#646464'
          },
          good: {
            default: '#0B6A0B',
            subtle: '#028A02'
          },
          light: {
            default: '#FFFFFF',
            subtle
          },
          warning: {
            default: '#B75C00',
            subtle: '#986F0B'
          }
        }
      },
      emphasis: {
        backgroundColor: cardEmphasisBackgroundColor,
        foregroundColors: {
          default: {
            default: '#000000',
            subtle: '#484644'
          }
        }
      },
      accent: {
        backgroundColor: '#C7DEF9',
        foregroundColors: {
          default: {
            default: '#333333',
            subtle: '#484644'
          }
        }
      },
      good: {
        backgroundColor: '#CCFFCC',
        foregroundColors: {
          default: {
            default: '#333333',
            subtle: '#484644'
          }
        }
      },
      attention: {
        backgroundColor: '#FFC5B2',
        foregroundColors: {
          default: {
            default: '#333333',
            subtle: '#484644'
          }
        }
      },
      warning: {
        backgroundColor: '#FFE2B2',
        foregroundColors: {
          default: {
            default: '#333333',
            subtle: '#484644'
          }
        }
      }
    },
    supportsInteractivity: true,
    fontFamily: primaryFont,
    imageSizes: {
      small: 40,
      medium: 80,
      large: 160
    },
    actions: {
      actionAlignment: 'stretch',
      actionsOrientation: 'horizontal',
      buttonSpacing: 8,
      maxActions: 100,
      showCard: {
        actionMode: 'inline',
        inlineTopMargin: 8
      },
      spacing: 'default'
    },
    adaptiveCard: {
      allowCustomStyle: false
    },
    imageSet: {
      imageSize: 'medium',
      maxImageHeight: 100
    },
    factSet: {
      title: {
        color: 'default',
        size: 'default',
        isSubtle: false,
        weight: 'bolder',
        wrap: true,
        maxWidth: 150
      },
      value: {
        color: 'default',
        size: 'default',
        isSubtle: false,
        weight: 'default',
        wrap: true
      },
      spacing: 8
    },
    textBlock: {
      headingLevel: 1
    }
  };

window.WebChat.renderWebChat(
  {
    directLine: directLine,
    adaptiveCardsHostConfig: hostConfig
  }
)
```

![image](https://user-images.githubusercontent.com/18403946/235527279-eefe8c9c-9d15-49a6-bcaf-8fcd31fded2a.png)

**Comment by samthrusha123** [comment]
Thanks @stevkan
