### ISSUE TITLE
[iOS] Adaptive card not rendering in mobile

### ISSUE THREAD

**Issue by SubbaReddi** [MicrosoftDocs/msteams-docs#7929]
Even If the adaptive card JSON is missing mandatory fields, card is rendering fine in Desktop, Web teams. But showing empty card in iOS mobile. 

For example. below card with image is missing URL property. If we send this card using bot, card displays blank in iOS mobile.
So, please add note in documentation to indicate issue is with card JSON.

{
    "type": "AdaptiveCard",
    "body": [
        {
            "type": "ColumnSet",
            "columns": [
                {
                    "type": "Column",
                    "items": [
                        {
                            "type": "Image",
                            "style": "default",
                            "size": "Small"
                        }
                    ],
                    "widh": "auto",
                    "width": "stretch"
                }
            ]
        }
    ]
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.4"
}

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Types of cards - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by ChetanSharma-msft** [comment]
Hello @SubbaReddi -  Thanks for raising the issue.
We will check on it and redirect to doc team accordingly.

**Comment by Prasad-MSFT** [comment]
@SubbaReddi - We tried to repro this issue using Teams Desktop, Web and Mobile clients. Nowhere the card is rendering.
**Teams Desktop/Web:**
![image](https://user-images.githubusercontent.com/62237649/213638136-6a66c6c0-d1b9-4854-a989-4a463bf2ce3f.png)
Teams Version:
`Microsoft Teams Version 1.6.00.1579`
**Android:**
![image](https://user-images.githubusercontent.com/62237649/213638365-5f9fe247-0218-4e50-a7ff-23dc64a6ed1f.png)
Teams Version:
![image](https://user-images.githubusercontent.com/62237649/213638448-67273c78-8eb4-42e7-bbfa-765c0cd1c129.png)

**Comment by SubbaReddi** [comment]
@Prasad-MSFT : It was not the case earlier.
In that case, documentation should indicate as follows:  "If the adaptive card JSON is missing required properties, card will show blank". Applies all teams clients.

**Comment by Prasad-MSFT** [comment]
@SubbaReddi - But in iOS, the card is not showing at all right?

**Comment by SubbaReddi** [comment]
@Prasad-MSFT : Our observation is card showing blank in iOS mobile. But card is rendering fine in other clients.

**Comment by Prasad-MSFT** [comment]
But @SubbaReddi - Will it be good if we update doc saying ""If the adaptive card JSON is missing required properties, card will show blank". Applies all Teams clients."? Because it shows blank only in iOS, not in all Teams client.

**Comment by SubbaReddi** [comment]
Agree. It is showing blank only in iOS.

**Comment by Prasad-MSFT** [comment]
Thanks @SubbaReddi  for confirming. So, i would suggest to not document this as it doesn't apply for all Teams clients.

**Comment by ChetanSharma-msft** [comment]
Hello @SubbaReddi, @Prasad-MSFT - As per my understanding, it's a bug in iOS device because sample card is showing properly in Desktop and other clients.

We will and raise a bug accordingly, if needed.

**Comment by Prasad-MSFT** [comment]
@SubbaReddi - Tested the issue again using below JSON
```
{
  "type": "AdaptiveCard",
  "body": [
    {
      "type": "TextBlock",
      "text": "For Samples and Templates, see [https://adaptivecards.io/samples](https://adaptivecards.io/samples)"
    },
    {
      "type": "ColumnSet",
      "columns": [
        {
          "type": "Column",
          "items": [
            {
              "type": "Image",
              "style": "default",
              "size": "Small"
            }
          ],
          "widh": "auto",
          "width": "stretch"
        }
      ]
    }
  ],
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "version": "1.4"
}
```
and observed that in MS Teams Desktop `(Microsoft Teams Version 1.6.00.2979)` and Web client, the card renders even with missing properties.
![image](https://user-images.githubusercontent.com/62237649/216618117-53316ab2-6efc-44c0-b9f4-bfa6e3adc073.png)

However, card displays blank in Android devices and doesn't render at all in iOS devices.

**Android:**
![image](https://user-images.githubusercontent.com/62237649/216619986-cb1e29b9-999d-486f-b538-66c61610eb4d.png)
Version:
![image](https://user-images.githubusercontent.com/62237649/216620532-37a37894-73d2-481e-96c0-d5a3f986af13.png)

iOS:
![image](https://user-images.githubusercontent.com/62237649/216623638-394c3f78-9b8c-4f44-8d7a-b79555e6433f.png)

Version:
![image](https://user-images.githubusercontent.com/62237649/216624829-731f9d57-12b6-44db-8c8e-d9ba7ac361d3.png)

**Comment by Prasad-MSFT** [comment]
We have raised a bug for the same and engineering team is looking into it. We will inform you once we get any further update. 

Thanks!

**Comment by Prasad-MSFT** [comment]
The adaptive card json is malformed with several bugs, including a mispelled 'width': 'auto' field. The offending element that is causing the rendering to break on android/iOS is the lack of a 'url' field for the image item. 
Web handles this by including an 'empty' image block in place of where the image should be, but this piece of faulty data causes the entire card to not render appropriately on mobile.

Using below JSON, the card renders fine.
```
{
  "type": "AdaptiveCard",
  "body": [
    {
      "type": "TextBlock",
      "text": "For Samples and Templates, see [https://adaptivecards.io/samples](https://adaptivecards.io/samples)"
    },
    {
      "type": "ColumnSet",
      "columns": [
        {
          "type": "Column",
          "items": [
            {
              "type": "Image",
              "url": "https://pbs.twimg.com/profile_images/3647943215/d7f12830b3c17a5a9e4afcc370e3a37e_400x400.jpeg",
              "style": "default",
              "size": "Small"
            }
          ],
          "width": "stretch"
        }
      ]
    }
  ],
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "version": "1.4"
}
```

![image](https://github.com/user-attachments/assets/d14e7956-91f1-44e4-b7a7-da943a06a169)
