### ISSUE TITLE
How to "calling us to fetch tokens"?

### ISSUE THREAD

**Issue by compulim** [MicrosoftDocs/msteams-docs#793]
In the [How do tabs in Teams differ from a browser viewing the same content URL?](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/tabs/tabs-overview?view=msteams-client-js-latest#how-do-tabs-in-teams-differ-from-a-browser-viewing-the-same-content-url) section, it mentioned "either via a popup or calling us to fetch tokens".

After reading a few articles around this topic, I still couldn't find any information related to "calling us to fetch tokens".

Could anyone point me to articles related to this feature?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c8cce1c-c091-090d-82de-13a57834e240
* Version Independent ID: 13f73468-3c62-d612-dd69-82b43ec31e95
* Content: [Add tabs to Microsoft Teams apps - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/tabs/tabs-overview?view=msteams-client-js-latest#how-do-tabs-in-teams-differ-from-a-browser-viewing-the-same-content-url)
* Content Source: [msteams-platform/concepts/tabs/tabs-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/tabs/tabs-overview.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by clearab** [comment]
Hi - you can read about authentication in tabs here: https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/authentication/auth-flow-tab
