### ISSUE TITLE
Device permissions for multi-window apps, and the meeting side panel.

### ISSUE THREAD

**Issue by v-nikhilsoma** [MicrosoftDocs/msteams-docs#7931]
Hi Team,
  We see the document note that "Teams doesn't support device permissions for multi-window apps, tabs, and the meeting side panel".
It actually supports now as per an announcement made by the engineering team (see below), and it is already in production.
Post reference: https://teams.microsoft.com/l/message/19:814416796bf34cfb82c9a15b0c63becf@thread.skype/1670262180686?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=32e3b156-66b2-4135-9aeb-73295a35a55b&parentMessageId=1670262180686&teamName=Teams%20Platform&channelName=Announcements&createdTime=1670262180686&allowXTenantAccess=false
![image](https://user-images.githubusercontent.com/118903153/213612372-1ca027f3-6983-4398-aa08-2107e31ea870.png)

So, could you please change the note in the documentation.
![image](https://user-images.githubusercontent.com/118903153/213612671-7ef93611-aecd-476f-a8dc-60a5bf82fa44.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 19804dba-009f-2eb1-cc7f-1e0fabbebb6b
* Version Independent ID: a9373e78-b3c9-7182-d253-5ac8d8988936
* Content: [Request device permissions for your Microsoft Teams app - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?tabs=desktop%2Cteamsjs-v2%2Cmobile1#native-device-permissions)
* Content Source: [msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/device-capabilities/native-device-permissions.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **surbhigupta**

**Comment by ChetanSharma-msft** [comment]
Hello @surbhigupta12 - Could you please help us here to update/delete the note in the documentation?

**Comment by surbhigupta12** [comment]
Closing this issue as docs are updated.
