### ISSUE TITLE
App invisible on Outlook and Office store when using manifest v1.15

### ISSUE THREAD

**Issue by ktcodebite** [MicrosoftDocs/msteams-docs#7941]
Repro steps:

1. Create and upload an app that uses manifest v1.15
2. Check whether the app shows on Outlook or Office.com
Expected that the app shows in the app store
Actual: no app

**Comment by Meghana-MSFT** [comment]
We are looking into this, we will get back to you.

**Comment by Meghana-MSFT** [comment]
We are checking this at our end, meanwhile can you please confirm if the prerequisites for extending Teams apps across Microsoft 365 are met - [extending Teams apps across Microsoft 365](https://learn.microsoft.com/en-us/microsoftteams/platform/m365-apps/prerequisites)?

**Comment by Meghana-MSFT** [comment]
@ktcodebite - We are also able to repro this issue with both v1.14 and v1.15. We will check internally and get back to you.

**Comment by Meghana-MSFT** [comment]
Bug has been raised for the same, Team is looking into it.

**Comment by nwojod-MSFT** [comment]
@ktcodebite thanks for confirming through internal channel that this issue has been resolved. I will be closing this bug.
