### ISSUE TITLE
Please add missing c# and NodeJS code snippet in the documentation

### ISSUE THREAD

**Issue by Pawan-MSFT** [MicrosoftDocs/msteams-docs#7943]
[Enter feedback here]
1. Could you please add below code snippets for c# and nodeJs

**C# :**

url = {{Webhook_URL}};
HttpClient client = new HttpClient();
client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
var content = new StringContent({{formatted_Card_Payload}}(Adaptive_Card_Json), System.Text.Encoding.UTF8, "application/json");
var response = await client.PostAsync({{WebhookUrl}}, content);

**NodeJs:**

    axios.post({{WebhookUrl}}, {{formatted_Card_Payload}})
        .then(res => {
            console.log(`statusCode: ${res.status}`)
            console.log(res)
        })
        .catch(error => {
            console.error(error)
        })

```
2. Also could you please help us to add the references like below in C# code section
![image](https://user-images.githubusercontent.com/117965661/212904964-2c207174-f20e-4d0d-b1f7-b76de746605d.png)

Sample code reference: https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/main/samples/incoming-webhook/csharp/IncomingWebhook/Controllers/CardController.cs#L28

```
3. Also could you please help us to add the references like below  in Node JS code section
![image](https://user-images.githubusercontent.com/117965661/212904964-2c207174-f20e-4d0d-b1f7-b76de746605d.png)

Sample code reference: https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/main/samples/incoming-webhook/nodejs/api/server/index.js#L16

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 90ff2a84-a8bc-9259-d37d-622b102df75b
* Version Independent ID: e3b53e27-2946-189c-623b-9df704ea8f12
* Content: [Create an Incoming Webhook - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-incoming-webhook)
* Content Source: [msteams-platform/webhooks-and-connectors/how-to/add-incoming-webhook.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/webhooks-and-connectors/how-to/add-incoming-webhook.md)
* Service: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by ChetanSharma-msft** [comment]
Hello @surbhigupta12 - Could you please help us here to update the documentation?
