### ISSUE TITLE
Teams Live Share tutorial: link in development section is broken

### ISSUE THREAD

**Issue by corinagum** [MicrosoftDocs/msteams-docs#7945]
https://learn.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/teams-live-share-tutorial#deployment 

Toolkit link under development section is broken

Fix: 

> After you're ready to deploy your code, you can use [Teams Toolkit](../toolkit/provision.md#provision-using-teams-toolkit-in-visual-studio) or the [Teams Developer Portal](https://dev.teams.microsoft.com/apps) to provision and upload your app's zip file.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c4095988-9b54-4919-411d-4db9b081af57
* Version Independent ID: c4095988-9b54-4919-411d-4db9b081af57
* Content: [Live Share code tutorial - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/teams-live-share-tutorial#deployment)
* Content Source: [msteams-platform/apps-in-teams-meetings/teams-live-share-tutorial.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/apps-in-teams-meetings/teams-live-share-tutorial.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **stevenic**

**Comment by ChetanSharma-msft** [comment]
Hello @corinagum - Thanks for raising this issue.

@surbhigupta12 - Please help us here to fix the broken link.
