### ISSUE TITLE
using href="#" prevents onlick when in a Teams app

### ISSUE THREAD

**Issue by MagtheRag** [MicrosoftDocs/msteams-docs#7948]
We have an app that is both a personal app and included as a Teams tab. The app itselfs "lives" in SharePoint and is included through the TeamsLogon page. 
In both places we have experienced that everywhere where we have an anchor tag with the href="#" the onclick events have stopped working. It works if we open the app directly in SharePoint and also if we iframe the app through an embed webpart in sharepoint. This solution has this issue in many places and environments.

**Comment by ChetanSharma-msft** [comment]
Hello @MagtheRag - Thanks for raising your issue:

Could you please share a minimal code snippets so that we can try to repro it from our end?

**Comment by MagtheRag** [comment]
<a href="#" onclick="alert('Hello')">Click me</a> ====> Will not work
<a href="javascript:void(0)" onclick="alert('Hello')">Click me</a> ====> Will work

**Comment by Nivedipa-MSFT** [comment]
@MagtheRag - We have tested your scenario.  We have created static tab and added below code in it.

   ```
<a href="#" onclick="alert('Hello')">Click me</a> ====> Will not work
<a href="javascript:void(0)" onclick="alert('Hello')">Click me</a> ====> Will work
```
    
   We have tested this on Teams web client and Teams desktop version 1.6.00.2359.
   For href="#" the onclick is working.
   
   
[href # issue.webm](https://user-images.githubusercontent.com/92150070/214543017-c189d05b-8f23-4364-b71e-a54977146276.webm)


   
   Could you please update the Teams version and check again?
   Please let us know if you face the same issue here.

**Comment by Nivedipa-MSFT** [comment]
@MagtheRag - Could you please confirm is your issue resolved or are you still facing this issue?

**Comment by MagtheRag** [comment]
It is still an issue.. it's when you iframe SHAREPOINT in and run your code.  Simular issue here https://github.com/SharePoint/sp-dev-docs/issues/8647

**Comment by Nivedipa-MSFT** [comment]
@MagtheRag - We will test this and update you soon.
