### ISSUE TITLE
How to force the Teams app to launch with chat/conversation pane open when the user launches the app from the mobile client for the first time?

### ISSUE THREAD

**Issue by GauravES** [MicrosoftDocs/msteams-docs#7949]
[Enter feedback here]
Tab order is not honored for Teams Apps on mobile clients.  Unlike the desktop/web client when a Teams app is launched , it defaults to the Chat pane. However  on mobile client the Teams App defaults to the About tab, and the user has to switch to the Chat pane to begin chatting with the app.  This is confusing to the user besides being inconsistent behaviour on the desktop/web vs. mobile. 

Is there a way to force the Teams app to launch with chat/conversation pane open when the user launches the app from the mobile client for the first time?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 61f5ca59-ab3e-b7ef-d3bc-55a88a362abf
* Version Independent ID: 6d43a761-19e0-541e-ba06-170099411ac1
* Content: [Create a personal tab - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?tabs=nodejs#reorder-static-personal-tabs)
* Content Source: [msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/tabs/how-to/create-personal-tab.md)
* Service: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by ChetanSharma-msft** [comment]
Hello @GauravES - Thanks for raising your issue.
We will investigate on your query and let you know the updates.

**Comment by Prasad-MSFT** [comment]
@GauravES - Could you please share repro steps or screen recording of the issue? Because as we have observed once we install any tab app after adding the app it goes to the home page of the tab instead of navigating to 'About' tab.
