### ISSUE TITLE
Is it possible to get answers from custom questions answering in local language?

### ISSUE THREAD

**Issue by samthrusha123** [MicrosoftDocs/msteams-docs#7950]

**Comment by ChetanSharma-msft** [comment]
Hello @samthrusha123 - Could you please share the more information and steps for your query?

**Comment by Nivedipa-MSFT** [comment]
@samthrusha123 - Could you please share the more information and steps for your query?

**Comment by samthrusha123** [comment]
In bot we're having Custom Question Answering right? We will maintain kb's t

> @samthrusha123 - Could you please share the more information and steps for your query?

can we translate the QnA KB answers to another language instead of english?

**Comment by Nivedipa-MSFT** [comment]
@samthrusha123 - If you need to support a knowledge base system, which includes several languages, you can:

Use the [Translator service](https://learn.microsoft.com/en-us/azure/cognitive-services/translator/translator-info-overview) to translate a question into a single language before sending the question to your knowledge base. This allows you to focus on the quality of a single language and the quality of the alternate questions and answers.
Create a custom question answering enabled language resource, and a knowledge base inside that resource, for every language. This allows you to manage separate alternate questions and answer text that is more nuanced for each language. This gives you much more flexibility but requires a much higher maintenance cost when the questions or answers change across all languages.

Ref Doc: https://learn.microsoft.com/en-us/azure/cognitive-services/language-service/question-answering/language-support#supporting-multiple-languages-in-one-knowledge-base
