### ISSUE TITLE
Collapsable Item makes it harder to search and navigate

### ISSUE THREAD

**Issue by MuyangAmigo** [MicrosoftDocs/msteams-docs#7968]
![image](https://user-images.githubusercontent.com/11220663/215241859-92d921b7-5799-40a8-a564-e31236b18283.png)
Some contents are hidden under a collapsable section, which makes it harder for the audience to search and navigate. Shall we consider to make it a sub heading?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 82fb7241-2342-61b4-b5eb-3d25ad391262
* Version Independent ID: 82fb7241-2342-61b4-b5eb-3d25ad391262
* Content: [Notification bot in Teams - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/notification-bot-in-teams?tabs=ts%2Cjsts%2Cts4)
* Content Source: [msteams-platform/bots/how-to/conversations/notification-bot-in-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/bots/how-to/conversations/notification-bot-in-teams.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **surbhigupta**

**Comment by Meghana-MSFT** [comment]
@MuyangAmigo - Thanks for reporting, we will discuss with doc team and update the doc accordingly.

**Comment by Meghana-MSFT** [comment]
@surbhigupta12 - Can you please share your views on this?

**Comment by Meghana-MSFT** [comment]
@surbhigupta12 - Can you please share your views on this?

**Comment by surbhigupta12** [comment]
Will speak to @MuyangAmigo and update here.

**Comment by Meghana-MSFT** [comment]
Hi @surbhigupta12 - Could you please share updates on this issue?

**Comment by Meghana-MSFT** [comment]
Hi @surbhigupta12 - Could you please share updates on this issue?
