### ISSUE TITLE
URL markdown breaks on mobile with parentheses 

### ISSUE THREAD

**Issue by unt1tled** [MicrosoftDocs/msteams-docs#797]
Rendering the following card works as expected in the desktop app, but not the mobile app.
`{
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "type": "AdaptiveCard",
    "version": "1.0",
    "body": [
        {
            "type": "TextBlock",
            "text": "Check out [(555) 194-9393](tel://5551949393)"
        }
    ]
}`

It seems that the markdown breaks if the URL text contains parentheses  

Tested on Android version 1416/1.0.0.2019061803

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40f35d71-c372-14ab-17d3-f4fc2a241a62
* Version Independent ID: f94dbfa0-9e4f-31cc-26ab-48dc3dda993a
* Content: [Text formatting in cards - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/cards/cards-format#feedback)
* Content Source: [msteams-platform/concepts/Cards/cards-format.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/Cards/cards-format.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Gousia-MSFT** [comment]
@unt1tled Thanks for reporting this. We have raised a bug for this.
