### ISSUE TITLE
Missing a customization scenario for using existing bot when debugging Teams app

### ISSUE THREAD

**Issue by MuyangAmigo** [MicrosoftDocs/msteams-docs#7970]
![image](https://user-images.githubusercontent.com/11220663/215394155-ffd8dd5e-6d85-4bdd-8a34-9f42d97fc1f5.png)

It's often asked scenario from developers that they might have an existing bot app created and which to use that when debugging Teams app using Teams Toolkit. Can we include this in the section here?

The relevant information is here:
* https://github.com/OfficeDev/TeamsFx/wiki/%7BDebug%7D-Teams-Toolkit-VS-Code-Tasks#how-to-use-the-existing-bot
* https://github.com/OfficeDev/TeamsFx/wiki/%7BDebug%7D-Teams-Toolkit-VS-Code-Tasks#set-up-bot

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ade7805f-ba79-1de6-1a0d-7cc3e221c5d8
* Version Independent ID: ade7805f-ba79-1de6-1a0d-7cc3e221c5d8
* Content: [Debug your Teams app - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview)
* Content Source: [msteams-platform/toolkit/debug-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/debug-overview.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **v-amprasad**

**Comment by Meghana-MSFT** [comment]
@MuyangAmigo - Thanks for reporting, we will discuss with doc team and update the doc accordingly.

**Comment by Meghana-MSFT** [comment]
@surbhigupta12 - Can you please share your views on this?

**Comment by Meghana-MSFT** [comment]
@surbhigupta12 - Can you please share your views on this?
