### ISSUE TITLE
Make a note to remind customers not to use `config.local.json` anymore for customizing existing bot AAD in local debug

### ISSUE THREAD

**Issue by IvanJobs** [MicrosoftDocs/msteams-docs#7971]
Hi,
See the section below in doc: https://learn.microsoft.com/en-us/microsoftteams/platform/toolkit/provision?pivots=visual-studio-code#use-an-existing-azure-ad-app-for-your-bot. 
![image](https://user-images.githubusercontent.com/1803943/215397123-0804ee4a-81df-4b94-bc08-98a763fdd2b4.png)

Some TTK customer was trying to reuse existing Bot AAD app in local debug by updating fields in `config.local.json`, and failed because the customizable fileds were moved into `.vscode/tasks.json`.  Check more details by clicking https://github.com/OfficeDev/TeamsFx/issues/7487, and https://github.com/OfficeDev/TeamsFx/wiki/%7BDebug%7D-Teams-Toolkit-VS-Code-Tasks#sample-5.
![image](https://user-images.githubusercontent.com/1803943/215398227-08d6df89-6c69-4497-89c2-6ece42c303bf.png)

It's better to give a note in https://learn.microsoft.com/en-us/microsoftteams/platform/toolkit/provision?pivots=visual-studio-code#use-an-existing-azure-ad-app-for-your-bot to remind customers about our newest changes of local debug's customizations.

**Comment by sayali-MSFT** [comment]
@IvanJobs -Thanks for reporting, we will discuss with doc team and update the doc accordingly.

**Comment by sayali-MSFT** [comment]
@IvanJobs - Could you please confirm if the below changes look fine or do we need to add more information?

@surbhigupta12 -Could you please help us to update the document?
Need to add the Note in below section. -
https://learn.microsoft.com/en-us/microsoftteams/platform/toolkit/provision?pivots=visual-studio-code#use-an-existing-azure-ad-app-for-your-bot

Note- A Teams Toolkit generated project has pre-defined a set of VS Code tasks in its .vscode/tasks.json. These tasks are for debugging. These tasks are generated by Teams Toolkit (>= 4.1.0) So, you can add configuration in `.vscode/tasks.json`.

**Comment by IvanJobs** [comment]
> d the Note in below section. -

@sayali-MSFT looks good to me, thanks.
