### ISSUE TITLE
Bad code snippets in TeamsFx-SDK

### ISSUE THREAD

**Issue by frankqianms** [MicrosoftDocs/msteams-docs#7972]
[Enter feedback here]
In this section: https://learn.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-sdk#microsoft-graph-scenarios:~:text=Use%20TeamsUserCredential)-,Use%20graph%20API%20in%20tab%20app,-Integration%20with%20Microsoft
In step 2, line 2 and line 3 should be changed as:
  clientId: process.env.REACT_APP_CLIENT_ID!,
  initiateLoginEndpoint: process.env.REACT_APP_START_LOGIN_PAGE_URL!,

In step 4, should change "User. Read" to "User.Read"(delete the space) in line 1.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 40d33c5e-5f61-f2e4-d619-170fa263c626
* Version Independent ID: 40d33c5e-5f61-f2e4-d619-170fa263c626
* Content: [TeamsFx SDK - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-sdk#microsoft-graph-scenarios)
* Content Source: [msteams-platform/toolkit/TeamsFx-SDK.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-SDK.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **v-amprasad**

**Comment by Nivedipa-MSFT** [comment]
@surbhigupta12 - Could you please help here to update the document here.
