### ISSUE TITLE
Deep link to open a meeting scheduling dialog not working for web version of Teams

### ISSUE THREAD

**Issue by karantrehan3** [MicrosoftDocs/msteams-docs#7988]
Problem: The deep link to open a meeting scheduling dialog box is not working as expected as per the documentation [here](https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-link-workflow?tabs=teamsjs-v1#deep-link-to-open-a-meeting-scheduling-dialog).
Use Case: Embedding the deep link in an `openUrl` action type inside an adaptive card. The deep link contains the following:
- `attendees`
- `subject`
- `content`

- The issue is that when the `openUrl` button is interacted with, it opens the meeting scheduling dialog box but it does not pre-populate the `attendees` and the `content`. It only pre-populates the `subject` in the case of the **web version of Teams.**
- It works well with Desktop and Mobile versions though

Example Deep Link: 
https://teams.microsoft.com/l/meeting/new?subject=test%20subject&attendees=joe@contoso.com,bob@contoso.com&content=test%3Acontent

Screenshots:

#### Web
![image](https://user-images.githubusercontent.com/41701337/215737941-a8fa444d-4070-4a87-b35e-22fb05148453.png)

#### Desktop
![image](https://user-images.githubusercontent.com/41701337/215737782-1ba6c58e-31ad-4331-981b-64c12a4da301.png)

Need help here!

**Comment by Meghana-MSFT** [comment]
We will test this at our end and get back to you.

**Comment by Meghana-MSFT** [comment]
@karantrehan3 - A bug has been raised for the same, engineering team is working on the fix. We currently do not have an ETA to share. We will keep you posted on the updates. Thanks.
