### ISSUE TITLE
Unclear on what to do when oauthRedirectMethod is web

### ISSUE THREAD

**Issue by mscherotter** [MicrosoftDocs/msteams-docs#7996]
I am testing external OAuth provider Adobe ID and I'm getting to step 6 and the oauthRedirectMethod is "web".  How do I proceed using this method, not deeplink?
Here are more details about my problem: https://stackoverflow.com/questions/75304660/why-isnt-app-initailzation-working-in-my-teams-add-in-oauth-flow
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b608448b-3dd7-d5be-128c-da2859067140
* Version Independent ID: b608448b-3dd7-d5be-128c-da2859067140
* Content: [Use external OAuth providers - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-oauth-provider)
* Content Source: [msteams-platform/tabs/how-to/authentication/auth-oauth-provider.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/tabs/how-to/authentication/auth-oauth-provider.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Prasad-MSFT** [comment]
@mscherotter - As mentioned in Step-8, Teams calls the success callback and sends the result (auth code) to the 3P app. The 3P app receives the code in the success callback and use the code to retrieve the token, then the user information and update the user interface.

Please refer this: https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/9256085cd1ddea0f9234b3409143b2b7e340ad96/samples/account-linking/csharp/Source/wwwroot/authEnd.js#L16

**Comment by mscherotter** [comment]
Do you have a full sample that shows how to authenticate when oauthRedirectMethod is web?
the problem that I am having is that the app.initialize() function times out without connecting to teams so I cannot notify of success.

**Comment by Prasad-MSFT** [comment]
@mscherotter - For now this is what's available. 
https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/9256085cd1ddea0f9234b3409143b2b7e340ad96/samples/account-linking

**Comment by mscherotter** [comment]
When I use Teams on the web via team.microsoft.com,
I use the app.authenticate() to authenticate against my site at /teams/login.
I find that the {oauthRedirectMethod} is replaces with "web" when I get the request on my server but the {authId} is not replaced it stays "{authId}"
When I use the Windows Teams desktop app for the same add-in neither the {oauthRedirectMethod} or {authId} are replaced.
Please advise.  Here is my exact code
Thanks,
Michael

`
        const parameters: authentication.AuthenticatePopUpParameters = {
            url: `${window.location.origin}/teams/login?oauthRedirectMethod={oauthRedirectMethod}&authId={authId}`,
            isExternal: true
        };

        const result = await authentication.authenticate(parameters);
`

**Comment by Prasad-MSFT** [comment]
@mscherotter - Could you please share the sample you are referring to?
