### ISSUE TITLE
Full Sample Please for web oauthRedirectMethod

### ISSUE THREAD

**Issue by mscherotter** [MicrosoftDocs/msteams-docs#7997]
Please provide a full sample that demonstrates the web oauthRedirectMethod.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b608448b-3dd7-d5be-128c-da2859067140
* Version Independent ID: b608448b-3dd7-d5be-128c-da2859067140
* Content: [Use external OAuth providers - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-oauth-provider)
* Content Source: [msteams-platform/tabs/how-to/authentication/auth-oauth-provider.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/tabs/how-to/authentication/auth-oauth-provider.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Nivedipa-MSFT** [comment]
@mscherotter - Thanks for reporting your issue.
Could you please refer below sample for oauthRedirectMethod.
https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/9256085cd1ddea0f9234b3409143b2b7e340ad96/samples/account-linking/csharp/Source/wwwroot/tab.js#L10

Please let us know if you have any further query here.

**Comment by Nivedipa-MSFT** [comment]
@mscherotter - Could you please confirm that suggested sample helped you in any way or are you still looking for any help?

**Comment by mscherotter** [comment]
I'm trying to figure out the sample

**Comment by mscherotter** [comment]
This sample is using AD- I am looking for a sample in JS that shows how to authenticate with a third party OAuth provider using the microsoftTeams.authentication.authenticate() API.
Michael

**Comment by Nivedipa-MSFT** [comment]
@mscherotter - Could you please refer below sample. In this sample Facebook authentication is done via microsoftTeams.authentication.authenticate().
https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/b5415c197d5a0aa03ec428d77d515368b6e23cc1/samples/app-complete-auth/csharp/AppCompleteAuth/Pages/tab.cshtml#L179

Please let us know if you have any further query here.

**Comment by ChetanSharma-msft** [comment]
Hello @mscherotter - Could you please confirm whether your issue has resolved or need any further assistance?
