### ISSUE TITLE
Private channels not appearing for vendors for the desktop Mac OS client

### ISSUE THREAD

**Issue by AustinTByrd** [MicrosoftDocs/msteams-docs#800]
Private channels not appearing for vendors for the desktop Mac OS client. Only appears on the web application.

**Comment by Gousia-MSFT** [comment]
@AustinTByrd Could you please share a screenshot of the issue you are facing.

**Comment by Gousia-MSFT** [comment]
Please reopen with screenshots if you are still facing issues.
