### ISSUE TITLE
MS Teams - Leave Button on Touch Bar not working 

### ISSUE THREAD

**Issue by reeboorn** [MicrosoftDocs/msteams-docs#8007]
Hi , there is already a same issue reported #3155 - MS Teams - Leave Button on MacBook Pro M2 2022 Touch Bar not working. 

Can you please share with me how is this resolved ? Can’t see the answer/solution in the existing thread.

**Comment by Meghana-MSFT** [comment]
We are mainly responsible for Microsoft Teams app development related issues.
For Microsoft Teams product issues/failures your tenant Admin can reach out to [Microsoft 365 Product Support](https://docs.microsoft.com/en-us/microsoft-365/admin/contact-support-for-business-products?view=o365-worldwide&tabs=online).
For general questions about Microsoft Teams please post your question on [Microsoft Teams Community](https://answers.microsoft.com/en-us/msteams/forum).
