### ISSUE TITLE
OAuth cards

### ISSUE THREAD

**Issue by v-kydela** [MicrosoftDocs/msteams-docs#801]
Are OAuth cards supported in Teams? They're not in the supported list but they're not in the unsupported list either.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8a3bcf2-332a-8d24-a8d1-7e3816897745
* Version Independent ID: 68fb9551-ce95-0112-2703-721a1af01f23
* Content: [Cards Reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/cards/cards-reference)
* Content Source: [msteams-platform/concepts/Cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/Cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Gousia-MSFT** [comment]
@v-kydela Yes, OAuth cards are supported inside Teams. They are mainly used for Authentication. Please refer to the [docs ](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/authentication/auth-oauth-card)to understand how to use this. Please let us know if you are facing any issues.

**Comment by v-kydela** [comment]
@Gousia-MSFT - Can the document be updated to include OAuth cards instead of just sign-in cards?
