### ISSUE TITLE
Instructions for Switching to Developer Preview are incorrect

### ISSUE THREAD

**Issue by mscherotter** [MicrosoftDocs/msteams-docs#8018]
You have Microsoft Teams Version 1.6.00.1381 (64-bit). It was last updated on 1/31/2023.

I don't see any option to switch to the Developer Preview
![image](https://user-images.githubusercontent.com/641702/216509588-21767577-c31a-4178-8297-17951640752b.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 008da4e2-979e-c396-db28-4acf57deb530
* Version Independent ID: f1413f77-5eb3-e1fd-9235-d322d6e4eb6c
* Content: [Public developer preview for Microsoft Teams - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/resources/dev-preview/developer-preview-intro)
* Content Source: [msteams-platform/resources/dev-preview/developer-preview-intro.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/resources/dev-preview/developer-preview-intro.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Meghana-MSFT** [comment]
@mscherotter - Can you please confirm if follow office preview is enabled or not in admin portal? Can you please try flipping it to just "Enabled" and restart the client (this might take a few minutes for the new policy to be downloaded). 

![image](https://user-images.githubusercontent.com/81138249/216536864-ef404469-895a-4444-8832-531bb2ee52a1.png)

Can you please try above suggestion and let us know if you are now able to see dev preview in About section.
