### ISSUE TITLE
Chat history is persists in Teams ?

### ISSUE THREAD

**Issue by vishmonne** [MicrosoftDocs/msteams-docs#802]
Hi Team,

IN Teams desktop app , i am chatting with the chatbot using the app id from Azure . what i see is that the chat history is always visible in Teams even after i log out and log in to the same chat. 

So i wanted to know if there is any way to clear the chat through code , or why is it like that in teams .

**Comment by Gousia-MSFT** [comment]
@vishmonne Teams chat is a persistent chat. There is no way to clear chat history with a bot.
