### ISSUE TITLE
[Doc-Enhancement] Deploy teams app resources to other cloud platforms

### ISSUE THREAD

**Issue by SubbaReddi** [MicrosoftDocs/msteams-docs#8023]
Hi Team,
Developers are looking for option to deploy Teams toolkit created app to other cloud platforms than Azure. For example, to deploy in AWS. As toolkit is not supported, recommending mentioning the note explicitly.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 21407e37-6d61-5499-e833-71285372bea3
* Version Independent ID: 21407e37-6d61-5499-e833-71285372bea3
* Content: [Use Teams Toolkit to provision cloud resources - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/toolkit/provision)
* Content Source: [msteams-platform/toolkit/provision.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/provision.md)
* Service: **msteams**
* GitHub Login: @MuyangAmigo
* Microsoft Alias: **shenwe**

**Comment by ChetanSharma-msft** [comment]
Hello @surbhigupta12 - Could you please help us here to add the note in the documentation?
