### ISSUE TITLE
How to distribute your app from a website in development environment ?

### ISSUE THREAD

**Issue by TheUncharted** [MicrosoftDocs/msteams-docs#8025]
Hello 
I would like to distribute my app from my web site like Slack with their button "Add To Slack" in a development environment . A good example is : https://www.polly.ai/ where they propose to install the app on slack / ms teams with  an html button + link

I tried with two methods using those two links but without success, it seems only possible when the app is in production and approved right ? How can I do it ?

- https://teams.microsoft.com/l/app/[APP_ID] : I'm redirected to the ms teams app and get this error "This app cannot be found.
"

- https://teams.microsoft.com/dl/launcher/launcher.html?url=[YOUR_APP_URL] : where url is a link to the package file (downloaded from the developer portal_ and get this error :  "We couldn't find what you're looking for"

**Comment by ChetanSharma-msft** [comment]
Hello @TheUncharted - Thanks for reporting your issue.
We will look into it and let you know the updates.

**Comment by Meghana-MSFT** [comment]
As you correctly said you can [create a deep link for the app](https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-link-application?tabs=teamsjs-v2) only after the app is listed in the Teams store. Polly is already published to Teams app store hence deeplink to Polly works.

You can check this doc to [Publish your app to the Microsoft Teams store](https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/publish).

Please note that [https://teams.microsoft.com/dl/launcher/launcher.html?url=[YOUR_APP_URL]](https://teams.microsoft.com/dl/launcher/launcher.html?url=%5BYOUR_APP_URL%5D) Should not be used.
