### ISSUE TITLE
Connection timeout

### ISSUE THREAD

**Issue by einue** [MicrosoftDocs/msteams-docs#803]
When I try to test the bot, nothing is loaded and I receive the message in the debug console 

 `ERROR: Error retrieving OpenId metadata at https://login.botframework.com/v1/.well-known/openidconfiguration, error: Error: connect ETIMEDOUT 52.232.26.228:443`

Do you have any idea what's going wrong? I use the ngrok-variant for testing the hello world app

**Comment by Gousia-MSFT** [comment]
Duplicate of [connection timeout](https://github.com/MicrosoftDocs/msteams-docs/issues/804).
