### ISSUE TITLE
Updating Documents - Anonymous Users feature

### ISSUE THREAD

**Issue by Harikrishnan-MSFT** [MicrosoftDocs/msteams-docs#8037]
Hi Teams,

Currently, we are implementing the anonymous user feature. 
**Document Link** -  [https://learn.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/build-apps-for-anonymous-user](url).

### Step 1 :
 1. Remove the C# session 
```
 "userObjectId": "8:anon:<GUID1>",
"userLicenseType": "Unknown",
"loginHint": "8:teamsvisitor:<ID>",
"userPrincipalName": "8:teamsvisitor:<ID>",
"tid": "<meeting organizer tenant ID>"
```

 2. Add JSON format and Javascript Code to the session.

![image](https://user-images.githubusercontent.com/117716554/217188922-599b32af-98d9-442d-9295-a0b53536e870.png)

Javascript Code - 
```
microsoftTeams.app.getContext().then((context) => {
if (context.user.licenseType === "Anonymous")
    {
            // Your code
    }
});
```

### Step 2 :
1. Remove C# sessions - 
```
{ 
  "membersAdded": [ 
    { 
      "id": "<GUID1>" 
    } 
  ], 
  "type": "conversationUpdate", 
  "timestamp": "<timestamp>", 
  "id": "<event unique identifier>", 
  "channelId": "msteams", 
  "serviceUrl": "<serviceURL>", 
  "from": { 
    "id": "<GUID2>" 
  }, 
```
 2. Add C# code to the session - 
 
 **MembersAdded** 
ITurnContext<IConversationUpdateActivity> turnContext return the TurnContext.Activity
```
protected override async Task OnTeamsMembersAddedAsync(IList<TeamsChannelAccount> membersAdded, TeamInfo teamInfo, ITurnContext<IConversationUpdateActivity> turnContext, CancellationToken cancellationToken)
        {
               if (teamMember.UserRole == "anonymous" )
                          {
                               // Your  code
                          }
          }
```
**MembersRemoved**

```
protected override async Task OnTeamsMembersRemovedAsync(IList<TeamsChannelAccount> membersRemoved, TeamInfo teamInfo, ITurnContext<IConversationUpdateActivity> turnContext, CancellationToken cancellationToken)
        {
          // Your  code
        }
```
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Types of cards - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference#receipt-card)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Nivedipa-MSFT** [comment]
@Harikrishnan-MSFT - Could you please share your query here?

**Comment by Harikrishnan-MSFT** [comment]
Duplicate issues of  - https://github.com/MicrosoftDocs/msteams-docs/issues/8038
