### ISSUE TITLE
Clear Cache

### ISSUE THREAD

**Issue by damienestewart** [MicrosoftDocs/msteams-docs#805]
Hi Team,

Is there a way to keep MS Teams from caching the content pages during development?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51ca77fe-cc16-a40c-d157-582d51b29d1a
* Version Independent ID: bb36842e-d434-1464-533f-769879c91bdd
* Content: [Static tabs - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/tabs/tabs-static)
* Content Source: [msteams-platform/concepts/tabs/tabs-static.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/tabs/tabs-static.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Gousia-MSFT** [comment]
@damienestewart Could you please elaborate on this? Are you saying that the Static tabs content pages are cached and you cannot reload them?

**Comment by damienestewart** [comment]
Hi @Gousia-MSFT! Yes, that was exactly the problem. Visiting the static tab's content page from my browser always showed the most recent version of the page, but the tab itself would always load the same older version of the content (even when I uninstalled/reinstalled the app or restarted Teams).

Eventually, I changed the url for the tab by appending '?', and that seemed to force it to load the most recent version of the content page. However, the tab still wouldn't reflect subsequent changes to the content page, even though my browser always reflected the most recent changes.

**Comment by Ky7m** [comment]
You can try to sign out and sign in back to Teams. I know it is not the easiest way to perform cache clean

**Comment by damienestewart** [comment]
@Ky7m I'm thinking you were right about that. I signed out, quit, restarted my machine, and now it seems to work. Strange! Thanks.

**Comment by aosolis** [comment]
@damienestewart Another way is to go to your tab, and bring up the dev tools using this technique: https://docs.microsoft.com/en-us/microsoftteams/platform/resources/dev-preview/developer-preview-tools

Then you can either clear your storage, or disable the cache using the Network tab then reload your tab by running window.location.reload() in the Console tab.

**Comment by damienestewart** [comment]
I didn't know about this @aosolis - thanks a lot!
