### ISSUE TITLE
Doc update suggestions:

### ISSUE THREAD

**Issue by ChetanSharma-msft** [MicrosoftDocs/msteams-docs#8058]
1. Please add a not in below section that manifest version 1.16 is required to support anonymous users.

![image](https://user-images.githubusercontent.com/59052547/217820864-45965b1f-3c7a-4e52-a1e0-b864c54a0f73.png)

1. Comment should be like:

![image](https://user-images.githubusercontent.com/59052547/217821090-5d985fc6-d186-4e90-bd8e-6fc67208c8ce.png)

// Write your custom logic here

1. Add a note here like: **Note: Live Share SDK is currently not supported for anonymous users.**

![image](https://user-images.githubusercontent.com/59052547/217821181-dcc2c921-a895-40ed-80d0-0a3b8ee81393.png)

1. Add comment like: // Write your custom logic here

Also add else block
![image](https://user-images.githubusercontent.com/59052547/217821400-8102aec6-4bee-47a2-8eac-4ac8a3c77e79.png)

1. Add comment properly like: // Write your custom logic here

![image](https://user-images.githubusercontent.com/59052547/217821585-5498b86a-70cd-4817-b8f4-0aef7e2a2932.png)

Also, in above if condition add comment like below:
// If AadObjectId is null, it indicates an Anonymous user.
if (member.AadObjectId == null)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2c5bc94a-3c95-aecc-a34d-d9771dc5e9bb
* Version Independent ID: 2c5bc94a-3c95-aecc-a34d-d9771dc5e9bb
* Content: [Build apps for anonymous user - Teams](https://review.learn.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/build-apps-for-anonymous-user?branch=pr-en-us-7318&tabs=javascript#tabpanel_1_json)
* Content Source: [msteams-platform/apps-in-teams-meetings/build-apps-for-anonymous-user.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/apps-in-teams-meetings/build-apps-for-anonymous-user.md)
* Service: **msteams**
* GitHub Login: @v-sdhakshina
* Microsoft Alias: **v-sdhakshina**

**Comment by Nivedipa-MSFT** [comment]
@surbhigupta12 - Could you please help here to update the document?

**Comment by surbhigupta12** [comment]
Docs are updated.
