### ISSUE TITLE
Doc update suggestion

### ISSUE THREAD

**Issue by ChetanSharma-msft** [MicrosoftDocs/msteams-docs#8059]
Please update `groupchat` as `groupChat` at all the places as we are getting warnings in manifest version 1.16.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0f94a488-d636-92b3-21eb-c88744c8f272
* Version Independent ID: 7b3413f4-9ade-accf-5cb2-83fead11a32a
* Content: [Manifest schema reference - Teams](https://review.learn.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema?branch=pr-en-us-7318#meetingextensiondefinition)
* Content Source: [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/resources/schema/manifest-schema.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Meghana-MSFT** [comment]
@surbhigupta12 - Can you please help to update the manifest schema document.
