### ISSUE TITLE
Doc update request

### ISSUE THREAD

**Issue by ChetanSharma-msft** [MicrosoftDocs/msteams-docs#8060]
Please add a note in below section of page like: **Note: Live Share SDK is currently not supported for anonymous users.**
https://learn.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/teams-live-share-capabilities?tabs=javascript#install-the-javascript-sdk

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f34dfdc6-abdc-a251-e415-231df48bf9cb
* Version Independent ID: f34dfdc6-abdc-a251-e415-231df48bf9cb
* Content: [Live Share getting started - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/teams-live-share-capabilities?tabs=javascript)
* Content Source: [msteams-platform/apps-in-teams-meetings/teams-live-share-capabilities.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/apps-in-teams-meetings/teams-live-share-capabilities.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **v-ypalikila**

**Comment by Nivedipa-MSFT** [comment]
@surbhigupta12 - Please add a note in below section of page like: Note: Live Share SDK is currently not supported for anonymous users.
https://learn.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/teams-live-share-capabilities?tabs=javascript#install-the-javascript-sdk
