### ISSUE TITLE
Developer preview option not showing on desktop client

### ISSUE THREAD

**Issue by karlrez** [MicrosoftDocs/msteams-docs#8066]
I currently have permissions for sideloading and uploading custom apps, and I was able to enable the developer preview setting on mobile. 

On desktop client I am not showing any option for developer preview:

![image](https://user-images.githubusercontent.com/47090434/217866932-fe7ea3cd-80d7-4912-a495-59568f02fdd6.png)

**Comment by Meghana-MSFT** [comment]
Can you please confirm if follow office preview is enabled or not in admin portal? Can you please try flipping it to just "Enabled" and restart the client (this might take a few minutes for the new policy to be downloaded).
![image](https://user-images.githubusercontent.com/81138249/218012322-cffcbdb4-9de9-448c-8dec-8dcea8400177.png)
Can you please try above suggestion and let us know if you are now able to see dev preview in About section.

**Comment by karlrez** [comment]
@Meghana-MSFT that worked, thank you!
