### ISSUE TITLE
New "premium" GPT features from a developer perspective

### ISSUE THREAD

**Issue by ja-onereach** [MicrosoftDocs/msteams-docs#8069]
Is there any documentation describing the recently announced AI/GPT/premium features from a developer perspective? We're looking to understand whether and how to support those features through our integrations with Teams but so far all of the information we can find on this topic is marketing stuff.

Also, do you expect to make these features accessible via API? If so, can you disclose a roadmap or timeline for that?

Thank you!

**Comment by Prasad-MSFT** [comment]
@ja-onereach - The new premium tier of Microsoft Teams includes an intelligent recap feature that automatically generates notes, tasks, and highlights of meetings thanks to GPT-3.5, alongside branded meetings, custom meeting templates, and features like watermarking to better protect meeting contents.
Please refer [this blog](https://www.microsoft.com/en-us/microsoft-365/blog/2023/02/01/microsoft-teams-premium-cut-costs-and-add-ai-powered-productivity/?ranMID=24542&ranEAID=nOD/rLJHOac&ranSiteID=nOD_rLJHOac-TImS89uLQOz9I3RvlPhmkQ&epi=nOD_rLJHOac-TImS89uLQOz9I3RvlPhmkQ&irgwc=1&OCID=AID2200057_aff_7593_1243925&tduid=%28ir__qltmja1h0ckfblh21io9timcu22xceayat9a2lem00%29%287593%29%281243925%29%28nOD_rLJHOac-TImS89uLQOz9I3RvlPhmkQ%29%28%29&irclickid=_qltmja1h0ckfblh21io9timcu22xceayat9a2lem00) which explains about this.

You can now get latest Teams platform updates by subscribing to the RSS feed 
[What's new - Teams | Microsoft Docs](https://learn.microsoft.com/en-us/microsoftteams/platform/whats-new?pivots=ga-feature)

**Comment by Prasad-MSFT** [comment]
We are closing this issue for now. Please feel free to reopen if required. Thanks!
