### ISSUE TITLE
Action after incoming call..

### ISSUE THREAD

**Issue by einue** [MicrosoftDocs/msteams-docs#807]
Is there a possibility to include an action, when a call is incoming or after end of call like export the callers data to another program? Therefore I want to use the RESt-API of the other program. But I can't find a possibility to listen on such a call event in teams. How can I "listen" on such an incoming event?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33cdb816-f2b6-31a4-0e4c-d730435d0a6b
* Version Independent ID: c111eaef-ac66-e245-b2bc-623c1801a7db
* Content: [Get started with App Studio and Node.js - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/get-started/get-started-nodejs-app-studio)
* Content Source: [msteams-platform/get-started/get-started-nodejs-app-studio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/get-started/get-started-nodejs-app-studio.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Wajeed-msft** [comment]
Currently there is no such event available. I will check internally about the plans.
