### ISSUE TITLE
Edit Teams calendar window to propose open time slots to the meeting organizer for cross geo collaboration

### ISSUE THREAD

**Issue by shefalik** [MicrosoftDocs/msteams-docs#8070]
I am reaching out to get an understanding if there is a way to enable the following experience within the Teams Calendar window - 
Our Nudging Teams App allows users to book/edit time on their calendars for group meetings (recurring/new). However, in the case of recurring cross-geo meetings/collaboration, we also propose times to the meeting organizer to be mindful of other people's preferences. This proposed feature currently exists in our Teams app as a separate feature on another surface. Thus, I am looking to see if there is a way where we can let the organizer know within the calendar experience window inside of Teams about the suggested times (either pre-populate the time block with the first available suggestion or provide them the suggested times underneath the time block on Calendar window in Teams, so the user has a more streamlined experience and doesn't have to switch surfaces to get to the proposed timeslots. Please let me know if this makes sense.

One of my devs was exploring this link - https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-link-workflow?tabs=teamsjs-v2. It only provides info about new meetings and not the recurring ones.

Would you have any expert advice on how can we go forward to enable this?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 98d88f26-f11f-4810-162a-40ca552be3e3
* Version Independent ID: 98d88f26-f11f-4810-162a-40ca552be3e3
* Content: [Deep link to a workflow in Teams - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-link-workflow?tabs=teamsjs-v2)
* Content Source: [msteams-platform/concepts/build-and-test/deep-link-workflow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/build-and-test/deep-link-workflow.md)
* Service: **msteams**
* GitHub Login: @v-npaladugu
* Microsoft Alias: **surbhigupta**

**Comment by Wajeed-msft** [comment]
> if there is a way where we can let the organizer know within the calendar experience window inside of Teams about the suggested times

@shefalik - Teams meeting scheduling experience is not customizable. Only option we have currently is to [Deep link to open a meeting scheduling dialog](https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-link-workflow?tabs=teamsjs-v2#deep-link-to-open-a-meeting-scheduling-dialog) and pass `startTime` and `endTime`. User can then edit the meeting details. 

One option would be to allow users to choose available timeslot beforehand and then pass selected dates to scheduling dialog. 

Please let us know if that helps.
