### ISSUE TITLE
Authentication when using "url" option in Task Module

### ISSUE THREAD

**Issue by guillewu** [MicrosoftDocs/msteams-docs#8077]
Does anybody know how to authenticate a user when using the "url" option in a task module? I'm planning to open a url that is a react application, but how can I know which user opened that url? Does teams send some kind of jwt when opening the url in the iframe?

Thanks

**Comment by sayali-MSFT** [comment]
@guillewu - Could you please elaborate your requirement and share the repro steps, so that we can try it from our end.

**Comment by guillewu** [comment]
@sayali-MSFT yes, basically I want to open a Task Module and passing it an iframe. For example:
```
{
  "task": {
    "type": "continue",
    "value": {
      "title": "Task module title",
      "height": 500,
      "width": "medium",
      "url": "https://contoso.com/msteams/taskmodules/newcustomer",
      "fallbackUrl": "https://contoso.com/msteams/taskmodules/newcustomer"
    }
  }
}
```
How can `https://contoso.com/msteams/taskmodules/newcustomer` know who is requesting the page? Does ms-teams pass some kind of context to the contoso page?

Thanks!
