### ISSUE TITLE
Increase incoming webhook rate limit for a channel?

### ISSUE THREAD

**Issue by omarshal** [MicrosoftDocs/msteams-docs#8078]
Hi!

I'm looking into migrating notifications from one message platform to MS Teams. The users in the channel react to the notification to acknowledge who will take action but also add comments to ask for help or other remarks.

During certain moments I expect [the rate limit described in the documentation](https://learn.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-using?tabs=cURL#rate-limiting-for-connectors) will be reached.

Is there a way to increase the rate limit for a specific webhook, channel or Team?

**Comment by Meghana-MSFT** [comment]
@omarshal - Unfortunately it is not possible to increase the Rate limiting for connectors. Thanks!

**Comment by omarshal** [comment]
OK, I was hoping for some business plan that allow higher limits. I hope you look into it!

**Comment by Meghana-MSFT** [comment]
You can share this feedback at [Microsoft Teams Feedback Portal](https://feedbackportal.microsoft.com/feedback/forum/ad198462-1c1c-ec11-b6e7-0022481f8472).

**Comment by omarshal** [comment]
As an alternative: Is there a rate limit for emails sent to the channel?

**Comment by Meghana-MSFT** [comment]
Please check this doc which talks about the [rate limit for Emailing a channel](https://learn.microsoft.com/en-us/microsoftteams/limits-specifications-teams#emailing-a-channel).

**Comment by omarshal** [comment]
Thanks! All clear now

**Comment by Meghana-MSFT** [comment]
Glad your issue has been answered. Please share your valuable feedback at [Microsoft Teams Developer Feedback](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR7iCOpS5_b9Nqmwx43u5rtZUOThVR081SllSR05aSDQxQ0tUMDVPTVIxTi4u). We are closing this issue please feel free to reach out to us incase if you have any questions.

**Comment by Meghana-MSFT** [comment]
Could you please let us know if you are facing the same issue or has any feedback.
