### ISSUE TITLE
Emoji Inconsistency in MS Teams Windows Client

### ISSUE THREAD

**Issue by DanielKapica** [MicrosoftDocs/msteams-docs#808]
The emoji in the last sent/received message preview in the chat list is different to the actual emoji send in the chat. I have sent a smiley emoji, but the preview shows a laughing/open mouth emoji.

![EmojiChat](https://user-images.githubusercontent.com/43884407/61461738-36f1fe80-a969-11e9-9da4-fef274c81cd8.png)

**Comment by Gousia-MSFT** [comment]
@DanielKapica 
![image](https://user-images.githubusercontent.com/45553518/61510914-8d674780-aa12-11e9-8d86-58f559a2486b.png)
These are reactions to the message you send/receive. This is not the preview of the emoji.
You could see the preview of the emojis from the bottom rail:
![image](https://user-images.githubusercontent.com/45553518/61510992-da4b1e00-aa12-11e9-8fdd-de6eb95aa6cd.png)
And these emojis are the same when they are sent.
![image](https://user-images.githubusercontent.com/45553518/61511043-09fa2600-aa13-11e9-90ba-8f4fbeb7aed1.png)
Please let me know if you have any more queries.

**Comment by clearab** [comment]
@Gousia-MSFT I can repro this behavior. If you send someone a smiley face from the emoji window, the chat preview message on the left shows a slightly different emoji. Send you a Teams message.

**Comment by Gousia-MSFT** [comment]
@DanielKapica Thanks for reporting this. We have raised a bug for this and we will look into it.

**Comment by Wajeed-msft** [comment]
We are tracking this bug internally. Closing this from documentation issues page.
