### ISSUE TITLE
Can't go back to Teams in a deep linked personal tab on iOS 16.2

### ISSUE THREAD

**Issue by plamber** [MicrosoftDocs/msteams-docs#8080]
Hello,
with the Teams Version 5.2. and the iOS Version 16.2 when being redirected from the activity feed to a personal app I am no more able to go back to Teams.

This is a regression of the fix that was already implemented and described in #6033.

Thank you
Patrick

**Comment by plamber** [comment]
@Nivedipa-MSFT fyi since you alreday handled #6033

**Comment by sayali-MSFT** [comment]
@plamber - Thanks for reporting your issue.
We will check this at our end and will get back to you.

**Comment by sayali-MSFT** [comment]
@plamber - We are reopening the bug and inform the engineering team.
We will inform you once we get any update.

**Comment by jpawlowski** [comment]
We are facing the same issue here.
Will this be resolved anytime soon?

**Comment by sayali-MSFT** [comment]
@jpawlowski,@plamber - Sorry for delay in response!!
We are actively checking the status of bug with engineering team and let you know the updates, if we have any.

**Comment by sayali-MSFT** [comment]
@plamber ,@jpawlowski -We have checked the scenario with "EasyLife 365" App and we are able to repro the scenario as "When you go to Page1 and again go to page2 and once you click on back button it is go to page1" but when again click back it is not going back.

It is happen with Web as well. 

However, we have checked the same scenario with "Stream" App as well, it is working fine with the Stream App. 

So, it looks like the issue with app but not with the Microsoft Team side.
 

Could you please check with the Stream app once?

**Comment by plamber** [comment]
Hello @sayali-MSFT,
can I reach you out over mail/ticket? We are not experiencing this issue with Android apps

Best regards,
Patrick

**Comment by sayali-MSFT** [comment]
@plamber - Sure, you can send it on mail to [microsoftteamsdev@microsoft.com](mailto:microsoftteamsdev@microsoft.com)
We have informed the engineering team as we are also tested the scenario on android it is working fine.

Did you get chance to check with the stream app?

**Comment by plamber** [comment]
Hi @sayali-MSFT 
could you let me know what steps you are following in the Streams app?

Thank you

**Comment by sayali-MSFT** [comment]
@plamber -Just change the deep link instead of using Easylife 365 App use the stream app deeplink.
If you try with the normal deeplink without using in personal tab that time also facing same issue.

https://user-images.githubusercontent.com/93527375/235411842-4671389d-dbf7-42af-939b-245344a9d9b5.mov

**Comment by sayali-MSFT** [comment]
@plamber -Got the reply from engineering team that ,"Android has a bug where back button is directly taking you out of the app, whereas ideally, we should first go back on the app if the app can go back, if not we should then close the app,
for eg, you you went to a L2 on the app from L1, then the back button should take you to L1 on first click and then close the app on second click.

Also now when the license has expired page comes up the back button works, so the problem is with there homepage which redirects"

**Comment by plamber** [comment]
Thank you for the feedback. Indeed, it is a single-page application that happens to get a couple of redirects using the react-router component. In some situations, it does not come to that point since the processing of the site does not require it.

How does a mobile app handle such SPA application redirects? Is there a way for me as an app to recognize that this back button was pressed?

**Comment by sayali-MSFT** [comment]
@plamber -Checking with the engineering team and get back to you once we get any update.

**Comment by plamber** [comment]
Hi @sayali-MSFT,
thank you for the code.

Just to understand you correctly. You are using a deep link to navigate to the page. You click around on the page and navigate in different directions using the react-router. Then you start to click the back button until you reach the last page. On that specific moment, the code snippet you shared should trigger.

Is this valid for iOS and Android?

Thank you,
Patrick

**Comment by sayali-MSFT** [comment]
@plamber -yes, it is valid to android and IOS.

**Comment by plamber** [comment]
Hello @sayali-MSFT,

Apologies for the extended delay. I have tested the provided code on an iPhone 11 running iOS 16.4.1 and the latest version of the Teams app. Unfortunately, it did not function as expected.

Upon further investigation, I believe I have identified the root cause. It appears that the issue is related to the BrowserRouter object utilized by the react-router-dom in combination with the way you integrate the apps in the Teams mobile client. To address this, I made a modification to our code by substituting the BrowserRouter with the MemoryRouter. However, if the application is accessed through a web browser, we will continue using the BrowserRouter.

Following this adjustment, the behavior seems to be functioning correctly on both iOS and Android devices.

Hence, I can confirm that this issue can now be closed.

Thank you for your help.

Best regards,
Patrick

**Comment by sayali-MSFT** [comment]
@plamber - Could you please share your valuable feedback via[ Microsoft Teams Developer Feedback](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR7iCOpS5_b9Nqmwx43u5rtZUOThVR081SllSR05aSDQxQ0tUMDVPTVIxTi4u) link.
