### ISSUE TITLE
button color is always purple in task module using adaptive cards 

### ISSUE THREAD

**Issue by guillewu** [MicrosoftDocs/msteams-docs#8081]
In the UI kit there's this screen capture:
![Screenshot 2023-02-13 at 5 59 53 PM](https://user-images.githubusercontent.com/1770464/218573394-c085fffc-41e7-4fb4-a9dd-4dd00b520fbd.png)

However, when using adaptive cards in task module I'm only able to show one color: purple. How can I display a white button?

**Comment by Meghana-MSFT** [comment]
Can you please confirm if you are having more than 1 button in your task module? 
Please note that modal dialog has a primary button defined, which has a different background color(purple). In modal dialog, the last button is treated as primary button(purple).
