### ISSUE TITLE
[Rendering] Suggestion and autocorrect text renders upside down

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#8082]
Copied bug from: https://github.com/microsoft/AdaptiveCards/issues/8305 

**Details from original post:**
### Target Platforms

iOS

### SDK Version

N/A

### Application Name

Teams

### Problem Description

I am sending an adaptive card to Teams to get input from a user. The autocorrect/suggestion text is upside down. I have no idea why this would be occurring, but I was able to reproduce it on four different iPhones. I do not have access to an Android phone, so I'm not sure if it is Teams or iOS.

### Screenshots

![image](https://user-images.githubusercontent.com/1170415/218346664-386b062b-96ba-493f-a355-711839658736.png)

### Card JSON

```JSON
{
   "attachments":[
      {
         "contentType":"application/vnd.microsoft.card.adaptive",
         "content":{
            "$schema":"http://adaptivecards.io/schemas/adaptive-card.json",
            "type":"AdaptiveCard",
            "version":"1.4",
            "body":[
               {
                  "type":"TextBlock",
                  "size":"Medium",
                  "weight":"Bolder",
                  "text":"Weather Request",
                  "horizontalAlignment":"Center",
                  "wrap":true,
                  "style":"heading"
               },
               {
                  "type":"Input.Text",
                  "label":"Location",
                  "style":"text",
                  "id":"location",
                  "isRequired":true,
                  "errorMessage":"Location is required"
               },
               {
                  "type":"Input.Date",
                  "label":"Start",
                  "isRequired":true,
                  "id":"start",
                  "value":"2023-02-12"
               },
               {
                  "type":"Input.Date",
                  "label":"End",
                  "id":"end"
               },
               {
                  "type":"Input.ChoiceSet",
                  "choices":[
                     {
                        "title":"U.S.",
                        "value":"us"
                     },
                     {
                        "title":"Metric",
                        "value":"metric"
                     }
                  ],
                  "id":"units",
                  "label":"Units",
                  "isRequired":true,
                  "value":"us"
               },
               {
                  "type":"TextBlock",
                  "text":"Include:",
                  "wrap":true,
                  "spacing":"Large"
               }
            ],
            "actions":[
               {
                  "type":"Action.Submit",
                  "title":"Submit",
                  "data":{
                     "id":"weather"
                  }
               }
            ]
         }
      }
   ]
}
```

### Sample Code

_No response_---
#### Document Details

⚠ *Do not edit this section.It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Cards reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **surbhigupta12**

**Comment by Prasad-MSFT** [comment]
@bandtank - Thanks for reporting the issue. We will check this from our end and revert back with updates.

**Comment by Prasad-MSFT** [comment]
@bandtank - We tried with the Json provided, however we are not getting any autocorrect/suggestions while typing anything in the input field.
![image](https://user-images.githubusercontent.com/62237649/218729000-c891e563-091d-4040-89ee-b14e15b40a67.png)

**Comment by Prasad-MSFT** [comment]
@bandtank , @TFesmire - Could you please share the json which you used to send the card via postman having autocorrect/suggestion?

**Comment by bandtank** [comment]
```
{
  "attachments": [
    {
      "contentType": "application/vnd.microsoft.card.adaptive",
      "content": {
        "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
        "type": "AdaptiveCard",
        "version": "1.5",
        "body": [
          {
            "type": "TextBlock",
            "size": "Medium",
            "weight": "Bolder",
            "text": "Weather Request",
            "horizontalAlignment": "Center",
            "wrap": true,
            "style": "heading"
          },
          {
            "type": "Input.Text",
            "label": "Location",
            "style": "text",
            "id": "location",
            "isRequired": true,
            "errorMessage": "Location is required"
          }
        ],
        "actions": [
          {
            "type": "Action.Submit",
            "title": "Submit",
            "data": {
              "id": "weather"
            }
          }
        ]
      }
    }
  ]
}
```

**Comment by Prasad-MSFT** [comment]
@bandtank , @TFesmire - Although we are still not able to repro this issue (auto-correction/suggestion is not showing), we have raised a bug for the same and engineering team is looking into it. We will inform you once we get any further update. Thanks!

**Comment by Prasad-MSFT** [comment]
@bandtank , @TFesmire - Engineering team is also not able to repro this issue? Could you please verify it on latest build and confirm if it is still reproable?

**Comment by bandtank** [comment]
I have confirmed this issue on three iPhones and two iPads. All devices have the latest version of iOS and Teams.

**Comment by Prasad-MSFT** [comment]
@bandtank - Could you please share the recording of the issue along with deployed manifest if possible, so that we can pass this to engineering team to investigate further?
