### ISSUE TITLE
[Rendering] Multiple TextBlock spacing issue when first block contains mention

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#8084]
Copied bug from: https://github.com/microsoft/AdaptiveCards/issues/8278 

**Details from original post:**
### Target Platforms

Other

### SDK Version

1.5

### Application Name

Microsoft Teams

### Problem Description

The 'none' spacing option appears to not be taking effect when used on a TextBlock element immediately proceeding another TextBlock element containing a mention in MS Teams for Mac. This is from an adaptive card sent by a teams bot to a channel only. Adaptive cards sent by the bot in chat are unaffected.

### Screenshots

Example 1: Teams channel adaptive card

<img width="621" alt="Screen Shot 2023-02-03 at 10 13 52 am" src="https://user-images.githubusercontent.com/351076/216473935-6b12d822-a50c-4ece-b03b-bff69469b6e9.png">

Example 2: Teams chat adaptive card

<img width="631" alt="Screen Shot 2023-02-03 at 10 14 29 am" src="https://user-images.githubusercontent.com/351076/216473991-8acb0dce-fad0-4ce5-bd7f-b4b9281841c1.png">

Example 3: Teams channel adaptive card no mention

<img width="618" alt="Screen Shot 2023-02-03 at 10 15 42 am" src="https://user-images.githubusercontent.com/351076/216474020-1e6d18c2-7d8e-46b6-a732-7bbe0b482209.png">

### Card JSON

```JSON
JSON for examples 1 and 2:

{
  "contentType": "application/vnd.microsoft.card.adaptive",
  "content": {
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "type": "AdaptiveCard",
    "version": "1.5",
    "msteams": {
      "entities": [
        {
          "type": "mention",
          "text": "<at>Steve Bell</at>",
          "mentioned": {
            "id": "<snipped>",
            "name": "Steve Bell"
          }
        }
      ],
      "width": "full"
    },
    "body": [
      {
        "type": "TextBlock",
        "text": "<at>Steve Bell</at>",
        "weight": "Bolder",
        "wrap": true
      },
      {
        "type": "TextBlock",
        "isSubtle": true,
        "spacing": "none",
        "text": "Business Owner",
        "wrap": true
      }
    ],
    "actions": []
  }
}

JSON for example 3:

{
  "contentType": "application/vnd.microsoft.card.adaptive",
  "content": {
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "type": "AdaptiveCard",
    "version": "1.5",
    "msteams": {
      "entities": [

      ],
      "width": "full"
    },
    "body": [
      {
        "type": "TextBlock",
        "text": "Steve Bell",
        "weight": "Bolder",
        "wrap": true
      },
      {
        "type": "TextBlock",
        "isSubtle": true,
        "spacing": "none",
        "text": "Business Owner",
        "wrap": true
      }
    ],
    "actions": []
  }
}
```

### Sample Code

_No response_---
#### Document Details

⚠ *Do not edit this section.It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Cards reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **surbhigupta12**

**Comment by Meghana-MSFT** [comment]
We are looking into this, we will get back to you.

**Comment by Meghana-MSFT** [comment]
We tested this issue in Windows and we are also able to repro this issue. We will check internally and update you.

**Comment by Meghana-MSFT** [comment]
We have raised a bug for the same we will keep you posted on the updates. Thanks!

**Comment by Meghana-MSFT** [comment]
This issue is fixed in new Teams T2.1. We have verified the fix and there is no spacing issue in new Teams 2.1.
Could you please check.

![image](https://github.com/MicrosoftDocs/msteams-docs/assets/81138249/2891363d-bdc1-4ea0-bd25-820b839304ee)
