### ISSUE TITLE
Deep links from Teams app not working in Outlook and Microsoft 365

### ISSUE THREAD

**Issue by MAPDesign** [MicrosoftDocs/msteams-docs#8103]
Right now all our deep links is are working in Outlook and Microsoft 365.
We use in Teams this code:
const deepLink = `[https://teams.microsoft.com/l/entity/${process.env.REACT_APP_APPLICATION_ID}/index](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fteams.microsoft.com%2Fl%2Fentity%2F%24%257Bprocess.env.REACT_APP_APPLICATION_ID%257D%2Findex&data=05%7C01%7CKiran.Thomas%40microsoft.com%7C8f12ce2065e044554a7f08db0f856044%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638120837780377018%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=hGdwzFWrDxDzv7eOfAZwcMCATD6TBM20hOdFqgaUHz0%3D&reserved=0);
microsoftTeams.app.openLink(deepLink)
 
This means that even tho our app is opening and displaying some functionality all the functionality that is dependent on those links is broken.

**Comment by Prasad-MSFT** [comment]
@MAPDesign - Could you please share more details on your issue adding repro steps?
Do you mean to say this deep link works within Outlook and M365, but not within MS Teams?

**Comment by MAPDesign** [comment]
the deep links work within our Teams app, but not in our Meta OS (Office + Outlook) integration-
so while all the Tabs form our Teams app appear in Outlook- some of the playable functions do not work- any button that relies on a deep link fails.

Right now, all deep links are not working in Outlook and Microsoft 365.
We use in our Teams app this code:
const deepLink = `https://teams.microsoft.com/l/entity/${process.env.REACT_APP_APPLICATION_ID}/index <https://teams.microsoft.com/l/entity/$%7Bprocess.env.REACT_APP_APPLICATION_ID%7D/index>;
microsoftTeams.app.openLink(deepLink)


Melissa Painter | Creative Director, Innovation Strategist | MAP Design Lab| 310.922.3263

**Comment by MAPDesign** [comment]
+ Taras + AnnaTaras can you please answer the below and share video as well thank you.Sent from my iPhoneOn Feb 16, 2023, at 12:58 AM, Prasad-MSFT ***@***.***> wrote:﻿
@MAPDesign - Could you please share the sample code reference which you are following or your sample code along with manifest file? Any repro video/attachment would be really helpful.

**Comment by MAPDesign** [comment]
Hi Prasad,
Here is the build: Breakthru Manifest <https://mapdesignlab-my.sharepoint.com/:f:/g/personal/melissa_mapdesignlab_onmicrosoft_com/EtGZpBB-sV5KgfR2zlNq7rgB10JbYfbB0imrrOoNungJ-Q?e=W8uvhk>
Here are videos that show expected deep link behavior working in Teams, and not working in Outlook/Office

file:///Users/MelissaPainter/Downloads/Breakthru_in_%20office.webm <file:///Users/MelissaPainter/Downloads/Breakthru_in_%20office.webm>
file:///Users/MelissaPainter/Downloads/Breakthru%20in%20Teams.webm <file:///Users/MelissaPainter/Downloads/Breakthru%20in%20Teams.webm>

Melissa Painter | Creative Director, Innovation Strategist | MAP Design Lab| 310.922.3263

**Comment by Prasad-MSFT** [comment]
@MAPDesign - The video/repro step files are not accessible. Could you please check and reshare? Without those we won't be able to get context of the issue.
![image](https://user-images.githubusercontent.com/62237649/219575468-451783f2-a1d9-4fa4-a5c1-6fbac21c63f0.png)

**Comment by MAPDesign** [comment]
https://vimeo.com/799848965/1e98cedff8

**Comment by MAPDesign** [comment]
video’s are here:
in Outlook: https://vimeo.com/799848965/1e98cedff8 <https://vimeo.com/799848965/1e98cedff8>
In Teams: https://vimeo.com/799850024/f6be6d6a9a <https://vimeo.com/799850024/f6be6d6a9a>

and the manifest:Breakthru Manifest <https://mapdesignlab-my.sharepoint.com/:f:/g/personal/melissa_mapdesignlab_onmicrosoft_com/EtGZpBB-sV5KgfR2zlNq7rgByBKqbH0h4I4ex9Et5UOqzw?e=O4IYhC>

Melissa Painter | Creative Director, Innovation Strategist | MAP Design Lab| 310.922.3263

**Comment by Prasad-MSFT** [comment]
@MAPDesign - Thanks for providing these. We will check this from our end and get back to you if there is any update.

**Comment by Prasad-MSFT** [comment]
Hi @MAPDesign - Could you please try once changing the domain? Here it seems that the deep-links are hard-coded with "teams.microsoft.com" but for example when engineering team created a deep-link inside of the Store (which is a MetaOS app) they got the domain from the context and replaced it in the deep-link before executing it.
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/62237649/d8addb59-c817-415d-975a-2540c106624d)

**Comment by VaibhaviKM** [comment]
Is this issue fixed? I can still see this issue happening.
@MAPDesign @Prasad-MSFT
