### ISSUE TITLE
Why "Local Debug" after delloying to cloud ?

### ISSUE THREAD

**Issue by kenhutaiwan** [MicrosoftDocs/msteams-docs#8104]
[Enter feedback here]

In step  "Deploy your first Teams app" , there is a section named "Deploy your app to Azure".
In that section, step 1-8 describe how to provision and deploy app to Azure cloud, but step 9 is "Local Debug".
I don't get it, why should I "Local Debug" after the app is deployed to the cloud ?
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4680d8ea-8210-67e0-7a1f-f24e94d58985
* Version Independent ID: 4680d8ea-8210-67e0-7a1f-f24e94d58985
* Content: [Build notification bot with JavaScript - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/sbs-gs-notificationbot?tutorial-step=6&tabs=vscode)
* Content Source: [msteams-platform/sbs-gs-notificationbot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/sbs-gs-notificationbot.yml)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Meghana-MSFT** [comment]
@kenhutaiwan - We are checking this and we will get the doc updated if required. Thanks!

**Comment by Meghana-MSFT** [comment]
@kenhutaiwan - Thank you for taking time the to report it.

@surbhigupta12 - Could you please help to update the doc by removing all the steps starting from step 9 - [Deploy your app to Azure](https://learn.microsoft.com/en-us/microsoftteams/platform/sbs-gs-notificationbot?tutorial-step=4&tabs=vscode#:~:text=app%20to%20Azure!-,Deploy%20your%20app%20to%20Azure,-Under%20DEPLOYMENT%2C%20you)

**Comment by kenhutaiwan** [comment]
Great ! You guys are truly willing to help to give us better study experience, really appreciate that.

**Comment by Meghana-MSFT** [comment]
Glad we were able to help you. Could you please share your valuable [feedback on your experience with our support team and Platform](https://aka.ms/DevSupportFeedback).
