### ISSUE TITLE
It says here on the note that the adaptive cards v1.5 is supported by teams but upon checking, the adaptive cards sent was not showing

### ISSUE THREAD

**Issue by ipadkid-sketchy** [MicrosoftDocs/msteams-docs#8105]
It says here on the note that the adaptive cards v1.5 is supported by teams but upon checking, the adaptive cards sent was not showing

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Types of cards - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference#adaptive-card)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Meghana-MSFT** [comment]
@amrix08 - Can you please share the JSON that you are using? Below is a simple card using v1.5 and it is being rendered in Teams.
` {
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "type": "AdaptiveCard",
    "version": "1.5",
    "body": [
      {
        "type": "TextBlock",
        "text": "Test block ",
        "weight": "Bolder",
        "wrap": true
      },
      {
        "type": "TextBlock",
        "isSubtle": true,
        "spacing": "none",
        "text": "Business Owner",
        "wrap": true
      }
    ]
  }`

![image](https://user-images.githubusercontent.com/81138249/219333458-6ba77483-7800-4c41-b66e-d65a78d2e1a9.png)

**Comment by amrix08** [comment]
This is the sample card

`{
    "type": "AdaptiveCard",
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.5",
    "msTeams": {
        "width": "full"
    },
    "body": [
        {
            "type": "Container",
            "spacing": "Large",
            "items": [
                {
                    "type": "Container",
                    "style": "emphasis",
                    "items": [
                        {
                            "type": "Table",
                            "columns": [
                                {
                                    "width": 100
                                },
                                {
                                    "width": 15
                                },
                                {
                                    "width": 15
                                }
                            ],
                            "rows": [
                                {
                                    "type": "TableRow",
                                    "cells": [
                                        {
                                            "type": "TableCell",
                                            "items": [
                                                {
                                                    "type": "TextBlock",
                                                    "text": "Companies",
                                                    "wrap": true,
                                                    "horizontalAlignment": "Center"
                                                }
                                            ]
                                        },
                                        {
                                            "type": "TableCell",
                                            "items": [
                                                {
                                                    "type": "TextBlock",
                                                    "weight": "Bolder",
                                                    "wrap": true,
                                                    "horizontalAlignment": "Center",
                                                    "text": "EC"
                                                }
                                            ]
                                        },
                                        {
                                            "type": "TableCell",
                                            "items": [
                                                {
                                                    "type": "TextBlock",
                                                    "wrap": true,
                                                    "weight": "Bolder",
                                                    "horizontalAlignment": "Center",
                                                    "text": "SEC"
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    "type": "TableRow",
                                    "$data": "${companies}",
                                    "cells": [
                                        {
                                            "type": "TableCell",
                                            "items": [
                                                {
                                                    "id": "REMOVE|${Id}",
                                                    "type": "Input.Toggle",
                                                    "wrap": true,
                                                    "title": "Test only"
                                                }
                                            ],
                                            "horizontalAlignment": "Left"
                                        },
                                        {
                                            "type": "TableCell",
                                            "items": [
                                                {
                                                    "type": "TextBlock",
                                                    "color": "Good",
                                                    "wrap": true,
                                                    "horizontalAlignment": "Center",
                                                    "text": "✖"
                                                }
                                            ]
                                        },
                                        {
                                            "type": "TableCell",
                                            "items": [
                                                {
                                                    "type": "TextBlock",
                                                    "color": "Good",
                                                    "wrap": true,
                                                    "horizontalAlignment": "Center",
                                                    "text": "🗸"
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ],
                            "showGridLines": false
                        }
                    ]
                }
            ]
        }
    ]
}`

And it shows an error upon testing on developer teams portal
![image](https://user-images.githubusercontent.com/62284865/219340225-6940e866-9fdf-4b7c-96a9-420c0c88d154.png)

**Comment by Meghana-MSFT** [comment]
Earlier we tried sending card through bot, now we have sent the card using Developer portal. We selected the target version as 1.5 and we also see the same behavior. Card is displayed properly in preview but in Teams its showing We're sorry, this card couldn't be displayed. We will check internally and get back to you.
![image](https://user-images.githubusercontent.com/81138249/219345206-c1973a00-ce82-4d95-ba83-e9da49747a3a.png)

**Comment by Meghana-MSFT** [comment]
@ipadkid-sketchy - We did try by changing the host app to Microsoft Teams Light and we also see the same behavior. In Teams its showing We're sorry, this card couldn't be displayed. We have raised a bug for the same. We will keep you posted on the updates.

**Comment by Meghana-MSFT** [comment]
Apologies, currently we do not have any update/ETA to share. We will keep you posted if we get any updates from engineering team.

**Comment by Meghana-MSFT** [comment]
@ipadkid-sketchy - The issue has been fixed, we have verified the fix. It works fine now. Could you please check once?
