### ISSUE TITLE
Remove link unfurling cache is not very clear

### ISSUE THREAD

**Issue by SLdragon** [MicrosoftDocs/msteams-docs#8108]
Remove link unfurling cache section is not very clear, after I read the docs, I don't know where to add suggestedActions property for the bot project.

Any insights about how can I remove link unfurling cache in the Teams Bot project?

![image](https://user-images.githubusercontent.com/5545529/219545128-272e3915-4712-4997-9004-65abc671dedd.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 59bbff2e-4b80-f980-2ade-7c7a7950801e
* Version Independent ID: e837e1fd-ec0c-2d6f-b0db-b76cb2d268a4
* Content: [Link unfurling - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?tabs=dotnet%2Cadvantages)
* Content Source: [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/messaging-extensions/how-to/link-unfurling.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **v-ypalikila**

**Comment by Nivedipa-MSFT** [comment]
@SLdragon - Thanks for reporting your issue. We will check and update the document accordingly.

**Comment by SLdragon** [comment]
Thanks, do you know where is the ` suggestedActions` property?

**Comment by Nivedipa-MSFT** [comment]
@SLdragon - We are checking this with engineering team and let you know once we get any updates from them. Thanks.

**Comment by ChetanSharma-msft** [comment]
Hello @SLdragon - Sorry for delay in response.
We are actively checking the status of your query with engineering team and let you know the updates; on we have any.

**Comment by miron4dev** [comment]
Hi @ChetanSharma-msft @Nivedipa-MSFT 
Is there a particular reason why we haven't received a response regarding caching for the past six months? 
The default caching method is making development extremely difficult.

**Comment by Nivedipa-MSFT** [comment]
@miron4dev - Apologies for the delay. We are checking this with engineering team, we will provide updates as soon as we have more information to share.

**Comment by miron4dev** [comment]
Finally, I got it to work.

```json
{
  "composeExtension": {
    "type": "result",
    "attachmentLayout": "list",
    "attachments": [
      {
        "preview": {
          "contentType": "application/vnd.microsoft.card.adaptive",
          "content": previewPayload
        },
        "contentType": "application/vnd.microsoft.card.adaptive",
        "content": cardPayload
      }
    ],
    "suggestedActions": {
      "actions": [
        {
          "type": "setCachePolicy",
          "value": "{\"type\":\"no-cache\"}"
        }
      ]
    }
  }
}
```

Hopefully, it'll save someone hours of development.
