### ISSUE TITLE
Missed `url` in the renamed namespace doc

### ISSUE THREAD

**Issue by kavin-happyfox** [MicrosoftDocs/msteams-docs#8109]
[Here](https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/using-teams-client-library?tabs=javascript%2Cmanifest-teams-toolkit#dialog-namespace), the new namespace for `tasks.startTask` should `dialog.url.open` and for `tasks.submitTasks` should be `dialog.url.submit`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4ae8187e-a7e4-4b5a-6f38-da6bfa30f2d2
* Version Independent ID: 4ae8187e-a7e4-4b5a-6f38-da6bfa30f2d2
* Content: [Teams JavaScript client library SDK - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/using-teams-client-library?tabs=javascript%2Cmanifest-teams-toolkit#updates-to-the-context-interface)
* Content Source: [msteams-platform/tabs/how-to/using-teams-client-library.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/tabs/how-to/using-teams-client-library.md)
* Service: **msteams**
* GitHub Login: @heath-hamilton
* Microsoft Alias: **surbhigupta**

**Comment by Meghana-MSFT** [comment]
We will check this from our end and get the doc updated if required. Thanks!

**Comment by erikadoyle** [comment]
Thanks for reporting @xnivaxhzne! Appreciate it. We actually have an open [PR to address this issue](https://github.com/MicrosoftDocs/msteams-docs/pull/7853/files#diff-26b3157a2497a1fe89adeb2b0d33d4511a6287de73177470fa9e109dea0b6328) (+updates across task module docs), soon to be published.
