### ISSUE TITLE
Incorrect App ID

### ISSUE THREAD

**Issue by HiltonGiesenow** [MicrosoftDocs/msteams-docs#8115]
One of the application IDs (d3590ed6-52b3-4102-aeff-aad2292ab01c) is listed twice - perhaps that's incorrect?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b2cf31a5-621a-eeac-26c9-89ada49466c0
* Version Independent ID: b2cf31a5-621a-eeac-26c9-89ada49466c0
* Content: [Extend a Teams personal tab app for Microsoft 365 - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/m365-apps/extend-m365-teams-personal-tab?tabs=manifest-teams-toolkit)
* Content Source: [msteams-platform/m365-apps/extend-m365-teams-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/m365-apps/extend-m365-teams-personal-tab.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by ChetanSharma-msft** [comment]
Hello @HiltonGiesenow - Thanks for raising your query:
We already have a note in the documentation that **"Some Microsoft 365 client applications share Client IDs."**

![image](https://user-images.githubusercontent.com/59052547/219995610-2c04847b-cd2f-4e81-aaa9-b8e04ac125f9.png)

Could you please let us know if you have any further query here?

**Comment by HiltonGiesenow** [comment]
ah ok, didn't spot that, thanks. How does that tie in with [this link](https://learn.microsoft.com/en-us/troubleshoot/azure/active-directory/verify-first-party-apps-sign-in) though, which lists "Outlook mobile" which lists: Outlook Mobile	27922004-5251-4030-b22d-91ecd9a37ea4"?

**Comment by Meghana-MSFT** [comment]
@HiltonGiesenow - We are checking with engineering team on the discrepancy between both the IDs. We will get back to you. Thanks!

**Comment by Meghana-MSFT** [comment]
@HiltonGiesenow - Thank you for taking the time to report this issue. As you rightly pointed out client ID for Outlook Mobile is 27922004-5251-4030-b22d-91ecd9a37ea4. Doc has been updated to reflect the same. Thank you.

**Comment by HiltonGiesenow** [comment]
great stuff. glad to help
