### ISSUE TITLE
Update references of "Teams client" to "Microsoft 365 host application"

### ISSUE THREAD

**Issue by Rick-Kirkham** [MicrosoftDocs/msteams-docs#8129]
This article will be linked to by documentation for non-Teams types of M365 extensions, such as Outlook Add-ins. The phrase "Teams client" needs to be changed to take this into account. Please replace the first instance of "Teams client" with:

    "Microsoft 365 host application, such as Teams or Outlook,"

Please replace all subsequent uses of "Teams client" with: 

    "Microsoft 365 host application"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3f55e52a-5fc4-7fcb-0e1e-946bff5aaee4
* Version Independent ID: b6c559fb-8512-575b-4fed-ebe1457e890e
* Content: [Localize your app - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/apps-localization)
* Content Source: [msteams-platform/concepts/build-and-test/apps-localization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/build-and-test/apps-localization.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Prasad-MSFT** [comment]
Hi @surbhigupta12 - Could you please help here to update the document as mentioned above?
Please replace the first instance of "Teams client" with:
`"Microsoft 365 host application, such as Teams or Outlook,"`

Please replace all subsequent uses of "Teams client" with:
`"Microsoft 365 host application"`

**Comment by erikadoyle** [comment]
@surbhigupta12 happy to take this if you'd like to assign to me. Thanks!
