### ISSUE TITLE
user.licenseType doesn't talk about Anonymous users

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#8132]
user.licenseType doesn't talk about Anonymous users which is mentioned in [In-Meeting getContext from Teams client library](https://learn.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/build-apps-for-anonymous-user?tabs=javascript#in-meeting-getcontext-from-teams-client-library).

![image](https://user-images.githubusercontent.com/31851992/220328596-f6eefa12-86c6-45e2-882f-8cca6194a1df.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8dfa1a29-bcf4-0cc5-ae3a-b185a00fd7bc
* Version Independent ID: c68181e1-151b-fc78-2671-fe9b397b702e
* Content: [Get context for your tab - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/access-teams-context?tabs=Json-v2%2Cteamsjs-v2#get-context-by-using-the-microsoft-teams-javascript-library)
* Content Source: [msteams-platform/tabs/how-to/access-teams-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/tabs/how-to/access-teams-context.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by ChetanSharma-msft** [comment]
@Nivedipa-MSFT - Please check and suggest the changes that needs to be updated in the documentation.

**Comment by Nivedipa-MSFT** [comment]
@surbhigupta12 - Could you please add the Anonymous value in below user.licenseType value.
![image](https://user-images.githubusercontent.com/92150070/221156649-b83447ff-f605-4432-aed5-6ad4bac1b09c.png)

Document link to update: https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/access-teams-context?tabs=Json-v2%2Cteamsjs-v2#get-context-by-using-the-microsoft-teams-javascript-library
