### ISSUE TITLE
web url with tel:+XXXXXXXX stopped working with ms teams desktop application for macOS

### ISSUE THREAD

**Issue by Chang025** [MicrosoftDocs/msteams-docs#8133]
We are using restful api to render adaptive card inside ms teams. We have linked our teams bot to azure bot.
- We are able to open web url with mailto:some_email link properly
- We are able to open web url with  tel:some_number from teams mobile app
- We are able to open web url with tel:some_number from azure (test in web chat)
- We are **NOT able to open web url with tel:some_number from MS Teams Desktop application for macOS**.

Teams App version: 1.6.00.1159 (last updated on 08/02/23)

Sample Payload:
`{
    "type": "message",
    "attachments": [
        {
            "contentType": "application/vnd.microsoft.card.adaptive",
            "content": {
                "version": "1.5",
                "type": "AdaptiveCard",
                "id": "67ee0aa4-0412-4c4a-8193-c6658c6e52c7",
                "body": [
                    {
                        "type": "TextBlock",
                        "text": "card title",
                        "wrap": true,
                        "size": "Medium",
                        "weight": "Bolder",
                        "style": "heading"
                    },
                    {
                        "type": "TextBlock",
                        "text": "card description",
                        "wrap": true
                    },
                    {
                        "type": "ColumnSet",
                        "columns": [
                            {
                                "type": "Column",
                                "width": "auto",
                                "items": [
                                    {
                                        "type": "ActionSet",
                                        "actions": [
                                            {
                                                "type": "Action.OpenUrl",
                                                "title": "call here",
                                                "url": "tel:+919090909090"
                                            }
                                        ],
                                        "horizontalAlignment": "Center"
                                    },
                                    {
                                        "type": "ActionSet",
                                        "actions": [
                                            {
                                                "type": "Action.OpenUrl",
                                                "title": "email webpage",
                                                "url": "mailto:someemail@gmail.com"
                                            }
                                        ],
                                        "horizontalAlignment": "Center"
                                    }
                                ]
                            }
                        ]
                    }
                ],
                "$schema": "http://adaptivecards.io/schemas/adaptive-card.json"
            }
        }
    ],
    "from": {
        "id": "XXXXXX",
        "name": "XXXXXX"
    },
    "conversation": {
        "conversationType": "personal",
        "tenantId": "XXXXXX",
        "id": "XXXXXX"
    },
    "recipient": {
        "id": "XXXXXX",
        "name": "XXXXXX",
        "aadObjectId": "XXXXX"
    }
}`

NOTE:
For earlier version it used to work properly.

**Comment by Chang025** [comment]
@sayali-MSFT  - any update on this?

**Comment by sayali-MSFT** [comment]
@Chang025 - Thanks for reporting your issue.
We will check this at our end and will get back to you.

**Comment by sayali-MSFT** [comment]
@Chang025 - We are able to repro that issue windows as well, we have raised bug for the same and concerned team is looking into it. We will inform you once we get any update.

**Comment by sayali-MSFT** [comment]
@Chang025 - We got the reply from engineering team that "Verified the behaviour on both Mobile and Desktop. "tel:" is only supported in Mobile and not on Desktop for obvious reasons."
