### ISSUE TITLE
Documentation should contain different versions for different bot framework sdks

### ISSUE THREAD

**Issue by basxib** [MicrosoftDocs/msteams-docs#814]
This documentation is confusing because this is based on SDK V3 of the bot framework and V4 is not backwards compatible,, which makes this doc invalid for V4.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88ff3777-49c4-8cdc-089e-8612a8774ffb
* Version Independent ID: 0d927000-0b55-2129-cbbb-6630c1ec481e
* Content: [Search with messaging extensions - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/messaging-extensions/search-extensions#identify-the-user)
* Content Source: [msteams-platform/concepts/messaging-extensions/search-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/messaging-extensions/search-extensions.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by clearab** [comment]
Yes, documentation and sample support for v4 bots on Teams will be forthcoming over the next few months. There is an authentication sample available here: https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/46.teams-auth
