### ISSUE TITLE
Sample links need to be updated

### ISSUE THREAD

**Issue by Meghana-MSFT** [MicrosoftDocs/msteams-docs#8145]
The sample name for **Meeting content bubble bot** has been changed to **meetings-notification**. Current links are going to 404, please help to update the below highlighted sample links.
![image](https://user-images.githubusercontent.com/81138249/220534082-ff5a62f0-5b1c-493b-8aba-c9c38ac99c72.png)

.NET - https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/meetings-notification/csharp
Node.js - https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/meetings-notification/nodejs

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ac148a35-2743-e16e-2b49-3ead0a1ecebc
* Version Independent ID: ac148a35-2743-e16e-2b49-3ead0a1ecebc
* Content: [Meeting apps APIs - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/meeting-apps-apis?tabs=dotnet#code-sample)
* Content Source: [msteams-platform/apps-in-teams-meetings/meeting-apps-apis.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/apps-in-teams-meetings/meeting-apps-apis.md)
* Service: **msteams**
* GitHub Login: @v-sdhakshina
* Microsoft Alias: **lajanuar**

The sample name for **Meeting content bubbl ot**** has been changed to **meetings-notification**. Current links are going to 404, please help to update with the below sample links.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ac148a35-2743-e16e-2b49-3ead0a1ecebc
* Version Independent ID: ac148a35-2743-e16e-2b49-3ead0a1ecebc
* Content: [Meeting apps APIs - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/meeting-apps-apis?tabs=dotnet#code-sample)
* Content Source: [msteams-platform/apps-in-teams-meetings/meeting-apps-apis.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/apps-in-teams-meetings/meeting-apps-apis.md)
* Service: **msteams**
* GitHub Login: @v-sdhakshina
* Microsoft Alias: **lajanuar**

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ac148a35-2743-e16e-2b49-3ead0a1ecebc
* Version Independent ID: ac148a35-2743-e16e-2b49-3ead0a1ecebc
* Content: [Meeting apps APIs - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/meeting-apps-apis?tabs=dotnet#code-sample)
* Content Source: [msteams-platform/apps-in-teams-meetings/meeting-apps-apis.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/apps-in-teams-meetings/meeting-apps-apis.md)
* Service: **msteams**
* GitHub Login: @v-sdhakshina
* Microsoft Alias: **lajanuar**

**Comment by Meghana-MSFT** [comment]
@surbhigupta12 - Could you please help to update the sample links.

**Comment by surbhigupta12** [comment]
Closing this PR as it is addressed.
