### ISSUE TITLE
Teams Application is suddenly inaccessible in Channel due to permission reasons

### ISSUE THREAD

**Issue by poladiaraj** [MicrosoftDocs/msteams-docs#8147]
[Enter feedback here]
We are able to add application to team's channel. When we try to access the application the behavior is unpredictable. We get"You don't have permission to use this app." when the app is invoked.

![Teams App issue](https://user-images.githubusercontent.com/24682275/220581514-4bc017fa-aceb-44b8-a60b-608efa5e115e.png)

Prior to this we have never witnessed such behavior.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f57a31a0-e815-faa4-653d-795ae8a8e4d7
* Version Independent ID: 8f48ea3d-231b-2776-41b7-11890ea2d3c0
* Content: [Build apps for the Microsoft Teams platform - Teams](https://learn.microsoft.com/en-us/MicrosoftTeams/platform/overview)
* Content Source: [msteams-platform/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/overview.md)
* Service: **msteams**
* GitHub Login: @heath-hamilton
* Microsoft Alias: **lajanuar**

**Comment by Nivedipa-MSFT** [comment]
@poladiaraj - Thanks for reporting your issue. Could you please share the repro steps to try at our end? Thanks.

**Comment by Nivedipa-MSFT** [comment]
@poladiaraj - Could you please share the repro steps to try at our end? Are you trying to add first party application or any custom application?

**Comment by poladiaraj** [comment]
We are facing this issue intermittently. We are trying to reproduce the issue, will post the exact scenario and steps shortly.

**Comment by Nivedipa-MSFT** [comment]
@poladiaraj - Are you able to reproduce this issue?
