### ISSUE TITLE
"Unable to reach app": Buttons for invoking a task module from adaptive cards (injected from Messaging Extension) are broken in the first minutes. 

### ISSUE THREAD

**Issue by Navega** [MicrosoftDocs/msteams-docs#815]
This should be fixed here https://github.com/MicrosoftDocs/msteams-docs/issues/556

But I re-open because it is happening again. The behavior now is that button to invoke a task module is broken with the message "Unable to reach app. Please try again". 

![issue](https://user-images.githubusercontent.com/16117077/61614089-2c827e00-ac63-11e9-885d-c43414f1a070.JPG)

An interesting point is that the same button will work in a few minutes after to inject the card, or when I inject it from Teams web app and then I click on it in Teams native app.

**Comment by Wajeed-msft** [comment]
Could you please put a try-catch in your code and see if there is any failure? Could you please also try [Task Module sample app manifest](https://github.com/OfficeDev/microsoft-teams-sample-task-module-nodejs/blob/master/TaskModule.zip) and see if it is working for you.

**Comment by Navega** [comment]
> Could you please put a try-catch in your code and see if there is any failure? Could you please also try [Task Module sample app manifest](https://github.com/OfficeDev/microsoft-teams-sample-task-module-nodejs/blob/master/TaskModule.zip) and see if it is working for you.

Hey Wajeed, thanks for your quick answer.

The problem is that button isn't connecting to my server when I click on it, so the try-catch is useless in this case.

With that sample app I see cards with buttons to fetch module tasks and it works fine, but they are injected from bot conversation, and these are working fine also for us. The problem is related to injected cards from Messaging Extension, and the cards from messaging extension for that sample don't include that button. Could you try for that case (messaging extension)?

**Comment by Gousia-MSFT** [comment]
@Navega We could not repro this issue. Task Module from Message Extension works as expected for us. Could you please share your app manifest with us?

**Comment by Navega** [comment]
> @Navega We could not repro this issue. Task Module from Message Extension works as expected for us. Could you please share your app manifest with us?

Is it safe to share the manifest with bot ids here or could you share with me a mail address to send it?

The easiest way to reproduce it in web app:
1. Inject card from messaging extension.
2. Click button
3. It fails
4. Refresh the page
5. Click button again
6. It works

Here a link to video: https://recordit.co/Lqj5nl7PMf

**Comment by Gousia-MSFT** [comment]
@Navega I was trying this in personal scope and yes I could repro this inside a team. I have raised a bug for this. We are looking into it.

**Comment by Navega** [comment]
This is working fine now for Web and Native apps. I guess that you fixed the problem, thanks!
