### ISSUE TITLE
Navigation Error with switching from "Teams" to "Chat" after opening a document.

### ISSUE THREAD

**Issue by ParkHost** [MicrosoftDocs/msteams-docs#816]
MS teams crashes when opening a document like word or excel.
After opening the document and going back to the "Chat" section, Teams crashes with an navigation_error code.

We received the error since the last MS Teams update.

![MS-Teams-Crash](https://user-images.githubusercontent.com/26667983/61620424-0b288e80-ac71-11e9-8377-86a1ff99b378.png)

**Comment by Gousia-MSFT** [comment]
@MrHpower How many users are facing this? Could you please share the logs which can be obtained by pressing Ctrl+Alt+Shift+1 with Teams app in focus.

**Comment by MrHpower** [comment]
This is reported by a couple of my colleagues, they are using teams the most in combination with editing office files in the SharePoint environment.

[MSTeams Diagnostics Log 22-7-2019_12_15_32_calling.txt](https://github.com/MicrosoftDocs/msteams-docs/files/3416811/MSTeams.Diagnostics.Log.22-7-2019_12_15_32_calling.txt)
[MSTeams Diagnostics Log 22-7-2019_12_15_32_sync.txt](https://github.com/MicrosoftDocs/msteams-docs/files/3416812/MSTeams.Diagnostics.Log.22-7-2019_12_15_32_sync.txt)
[MSTeams Diagnostics Log 22-7-2019_12_15_32.txt](https://github.com/MicrosoftDocs/msteams-docs/files/3416813/MSTeams.Diagnostics.Log.22-7-2019_12_15_32.txt)

**Comment by Gousia-MSFT** [comment]
@MrHpower Thanks for sharing the logs. We are looking into this.

**Comment by Gousia-MSFT** [comment]
@ParkHost We need some more information to investigate this. Could you please help us with the following:
1. When you say chat section are you referring the chat section within the office document (middle pane) or chat in the left rail?
2. Is this mac or windows?
3. Could you please share the fiddler trace captured during the repro?
4. Can you also share the desktop logs which can be accessed from the below locations?
        %appdata%\Microsoft\Teams (windows)\ logs.txt
       ~/Library/Application Support/Microsoft/Teams (Mac)\log.txt

**Comment by ParkHost** [comment]
i mean the chat tab on the left rail.
this is only reported from windows machines, we don't support MAC's

We cant find out what the exact trigger is that the error message generates.
it only happens some days and on different files.
Several customers complained about the crash error.

**Comment by Gousia-MSFT** [comment]
@ParkHost Could you please share the desktop logs for windows and the Fiddler trace captured during the repro?

**Comment by ParkHost** [comment]
well it isn't easy to repro cause it happens so random.

**Comment by Wajeed-msft** [comment]
Could you please share the logs whenever it happens again?

**Comment by ParkHost** [comment]
yes, as soon as it happens ill post the logging, thank you

**Comment by ahmedsaeed-dev** [comment]
Hi, also getting the same issue. 

![1](https://user-images.githubusercontent.com/45216883/62219854-0ce30800-b37d-11e9-9419-404057b0a123.jpg)

**Comment by Gousia-MSFT** [comment]
@ahmedsaeed-dev Are you seeing this when you try to navigate after opening a document? If so, could you please follow the comments on this issue to share the required logs and fiddler trace with us?

**Comment by ParkHost** [comment]
@Gousia-MSFT finally i got the logging of my colleague, 


Wed Jul 10 2019 16:26:16 GMT+0200 (West-Europa (zomertijd)) <1044> -- info -- Is foreground set to false 
Wed Jul 10 2019 16:26:16 GMT+0200 (West-Europa (zomertijd)) <1044> -- event -- eventpdclevel: 2,  
Wed Jul 10 2019 16:26:35 GMT+0200 (West-Europa (zomertijd)) <1044> -- event -- status: timeout, scenario: 71dd589c-ab1f-4688-b6f4-83257a5de973, scenarioName: window_url_navigation, name: window_url_navigation, step: stop, sequence: 1, delta: 20014, scenarioDelta: 20014, elapsed: 106759162, eventpdclevel: 2, Scenario.Name: window_url_navigation, Scenario.Step: stop, Scenario.Status: timeout,  
Wed Jul 10 2019 16:26:45 GMT+0200 (West-Europa (zomertijd)) <1044> -- event -- name: desktop_navigation_error_recovery_retryexceeded, eventpdclevel: 3,  
Wed Jul 10 2019 16:26:45 GMT+0200 (West-Europa (zomertijd)) <1044> -- event -- panelview: Panel.Type: oopsPage, Panel.Region: main, Panel.LaunchMethod: navigation_error, DataBag.OopsReason: navigation_error, eventpdclevel: 2,  
Wed Jul 10 2019 16:26:45 GMT+0200 (West-Europa (zomertijd)) <1044> -- warning -- Loading oops page with id: 0 due to: navigation_error 
Wed Jul 10 2019 16:26:45 GMT+0200 (West-Europa (zomertijd)) <1044> -- event -- name: desktop_oops_show, reason: navigation_error, errorCode: navigation_error, errorDescription: null, oopsId: 0, eventpdclevel: 3,  
Wed Jul 10 2019 16:26:45 GMT+0200 (West-Europa (zomertijd)) <1044> -- event -- reason: navigation_error, errorCode: navigation_error, errorDescription: null, oopsId: 0, status: success, scenario: 839aa3e9-381d-4533-bc2f-2aba9ca0812e, scenarioName: desktop_oops_show, name: desktop_oops_show, step: start, sequence: 0, delta: 0, scenarioDelta: 0, elapsed: 106769161, eventpdclevel: 3, Scenario.Name: desktop_oops_show, Scenario.Step: start, Scenario.Status: success,  
Wed Jul 10 2019 16:26:45 GMT+0200 (West-Europa (zomertijd)) <1044> -- event -- reason: navigation_error, errorCode: navigation_error, errorDescription: null, oopsId: 0, status: success, scenario: 839aa3e9-381d-4533-bc2f-2aba9ca0812e, scenarioName: desktop_oops_show, name: desktop_oops_show, step: stop, sequence: 1, delta: 1, scenarioDelta: 1, elapsed: 106769162, eventpdclevel: 3, Scenario.Name: desktop_oops_show, Scenario.Step: stop, Scenario.Status: success,  
Wed Jul 10 2019 16:26:45 GMT+0200 (West-Europa (zomertijd)) <1044> -- info -- emit status indicator state change from Busy to GeneralError

**Comment by ParkHost** [comment]
Logfile:
[logs.txt](https://github.com/MicrosoftDocs/msteams-docs/files/3467262/logs.txt)

**Comment by Gousia-MSFT** [comment]
@ParkHost Thanks for sharing the logs. I will keep you posted about this.

**Comment by Gousia-MSFT** [comment]
@ParkHost We have fixed this and will start rolling out the fix. This might take some time to reach public rings, we do not have exact ETA to share as of now.

**Comment by ParkHost** [comment]
@Gousia-MSFT woow thnx, what was the problem?

Will this fix be in a MS teams update or is it something on the backend?

**Comment by Gousia-MSFT** [comment]
@ParkHost This will be part of MS teams updates.

**Comment by larshub** [comment]
Hi there any updates about this fix? Running teams version 1.2.00.22654 and having same issues as above!
