### ISSUE TITLE
Teams apps app not showing in office

### ISSUE THREAD

**Issue by dapowell** [MicrosoftDocs/msteams-docs#8167]
Our Teams personal app (SurveyMonkey) is showing in teams and outlook, but is not showing up in office for our qatest365.onmicrosoft.com test tenant. We were told by Kiran Thomas that this is a bug in multi hub and to post a ticket here to have it rectified. We don’t see any apps outside of MSFT ones and cannot choose our own even when side-loaded.

**Comment by Nivedipa-MSFT** [comment]
@dapowell - Thanks for reporting your issue. We will test this and update you soon.

**Comment by Nivedipa-MSFT** [comment]
@dapowell - We are able to repro your issue. We have raised a bug for the same. We will let you know once we got any updates on it.

**Comment by nwojod-MSFT** [comment]
Closing this issue as it has been fixed. Please re-open this if you are still experiencing the same issue. Thanks
