### ISSUE TITLE
Despite following the instructions the application does not work.

### ISSUE THREAD

**Issue by MatthewRock** [MicrosoftDocs/msteams-docs#817]
When following the steps from https://docs.microsoft.com/en-us/microsoftteams/platform/get-started/get-started-dotnet-app-studio#download-the-sample , the application compiles but does not work - when trying to reach the page with hello world example, an error page is displayed instead. This solution resolved the problem: https://stackoverflow.com/a/34391473

I have included [error_page.txt](https://github.com/MicrosoftDocs/msteams-docs/files/3418622/error_page.txt), which really is .HTM file (but github does not accept this format, hence the rename). The site is what appears after running the instructions. The expected outcome would be seeing the hello world page instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98cd21c7-e87c-3c5b-7574-998a355f9f08
* Version Independent ID: 5e312707-facc-03fc-af59-90267d0c7b8a
* Content: [Get started with C#/.NET - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/get-started/get-started-dotnet-app-studio#feedback)
* Content Source: [msteams-platform/get-started/get-started-dotnet-app-studio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/get-started/get-started-dotnet-app-studio.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by clearab** [comment]
Thanks for letting us know. I've previously added the post-build script that should have made sure the csc.exe file was placed appropriately. I've added a note to the article about force updating the package. We'll consider removing the Roslyn dependency in the future.
