### ISSUE TITLE
How to receive the trigger to bot when user closes the task module with restful API not botframework SDK.

### ISSUE THREAD

**Issue by Chang025** [MicrosoftDocs/msteams-docs#8176]
reference: https://learn.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/task-modules/invoking-task-modules#the-taskinfo-object

We are using restful api to render adaptive cards, and binding `Action.Submit` with ` type: 'task/fetch'` to a button.
After the user clicks on the button we are receiving `{"name"=>"task/fetch", "type"=>"invoke"...` payload.
and returning the below payload to render the content on the task module.
`{:task=>{:type=>"continue", :value=>{:title=>"Hello code", :width=>"large", :height=>"large", :completionBotId=>"XXXXXXXXX", :url=>"https://xxxxxxxx.com/"}}}`

As mentioned in the docs, if we pass `completionBotId` then we will receive `task/submit invoke` json payload, but we are not receiving this payload when the user closes the task module.

- Is there any way to know user closes the task module?
- Any trigger we can get back to our bot when the user performs any action on the task module?

it would be appreciated if you provide an example of it.

**Comment by sayali-MSFT** [comment]
@Chang025 - Thanks for reporting your issue.
We will check this at our end and will get back to you.

**Comment by sayali-MSFT** [comment]
@Chang025 - Could you please have look into this sample- 
https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/090e03227c073efbff7931b79cc36fda49cbfeb9/samples/app-task-module/nodejs/src/utils/DeepLinks.ts

also, could you please share the repro steps so that we can investigate from our end?

**Comment by Chang025** [comment]
@sayali-MSFT - Sorry for the delay.
We are using an adaptive card, sample code:
`{
  "type": "message",
  "attachments": [
    {
      "contentType": "application/vnd.microsoft.card.adaptive",
      "content": {
        "version": "1.5",
        "type": "AdaptiveCard",
        "id": "******************",
        "body": [
          {
            "type": "TextBlock",
            "text": "test",
            "wrap": true,
            "size": "Medium",
            "weight": "Bolder",
            "style": "heading"
          },
          {
            "type": "TextBlock",
            "text": "test",
            "wrap": true
          },
          {
            "type": "ColumnSet",
            "columns": [
              {
                "type": "Column",
                "width": "auto",
                "items": [
                  {
                    "type": "ActionSet",
                    "actions": [
                      {
                        "type": "Action.Submit",
                        "associatedInputs": "none",
                        "title": "Hello code grepper",
                        "data": {
                          "msteams": {
                            "type": "task/fetch"
                          },
                          "inline_card_link_uuid": "************",
                          "associatedInputs": "none"
                        }
                      }
                    ],
                    "horizontalAlignment": "Center"
                  }
                ]
              }
            ]
          }
        ],
        "$schema": "http://adaptivecards.io/schemas/adaptive-card.json"
      }
    }
  ],
  "from": {
    "id": "************",
    "name": "*********"
  },
  "conversation": {
    "conversationType": "personal",
    "tenantId": "************",
    "id": "************"
  },
  "recipient": {
    "id": "************",
    "name": "***********",
    "aadObjectId": "************"
  }
}`

This renders like: 
<img width="641" alt="Screenshot 2023-03-10 at 6 14 07 PM" src="https://user-images.githubusercontent.com/46022906/224319250-6f1a3a19-bf6b-4b90-a7c1-0233ab24c5a4.png">

and then on clicking of the button, we receive the webhook event with this payload:
`{
  "name"=>"task/fetch",
  "type"=>"invoke",
  "timestamp"=>"2023-03-10T12:44:29.587Z",
  "localTimestamp"=>"2023-03-10T18:14:29.587+05:30",
  "id"=>"***********",
  "channelId"=>"msteams",
  "serviceUrl"=>"https://smba.trafficmanager.net/amer/",
  "from"=>{
    "id"=>"***********",
    "name"=>"***********",
    "aadObjectId"=>"***********"
  },
  "conversation"=>{
    "conversationType"=>"personal",
    "tenantId"=>"***********",
    "id"=>"***********"
  },
  "recipient"=>{
    "id"=>"***********",
    "name"=>"***********"
  },
  "channelData"=>{
    "tenant"=>{
      "id"=>"***********"
    },
    "source"=>{
      "name"=>"compose"
    },
    "legacy"=>{
      "replyToId"=>"***********"
    }
  },
  "replyToId"=>"***********",
  "value"=>{
    "data"=>{
      "inline_card_link_uuid"=>"***********",
      "associatedInputs"=>"none",
      "type"=>"task/fetch"
    },
    "context"=>{
      "theme"=>"default"
    }
  },
  "locale"=>"en-US",
  "localTimezone"=>"Asia/Calcutta",
  "channel_uuid"=>"***********",
}`

After receiving the above request we are responding with 
`{
  "task": {
    "type": "continue",
    "value": {
      "title": "Hello code grepper",
      "width": "large",
      "height": "large",
      "url": "https://www.grepper.com/"
    }
  }
}`
We are able to open the website inside the task module, but when the user clicks on the close button, we are not receiving any event from teams.

I tried passing `completionBotId` along with the above payload, but it didn't help.

**Comment by Chang025** [comment]
@sayali-MSFT , @ChetanSharma-msft - can you please look into this?

**Comment by sayali-MSFT** [comment]
@Chang025 -
