### ISSUE TITLE
[iOS/ipadOS] multiple notifications on teams app for the same message

### ISSUE THREAD

**Issue by binderaxel** [MicrosoftDocs/msteams-docs#8183]
various users in our tenant are receiving multiple notifications on the teams app [iOS/ipadOS] for the same message (chat message or channel message). the multiple notifications are displayed instantly or within approx 15min after the initial notification. users with an apple watch are receiving these multiple notifications on the watch as well. the notification settings per user seem fine and there are not iOS accessibility features for notification reminders active. uninstall + reinstall of teams app doesn’t help as all. all affected users are using teams at least on iOS + desktop (Win11 or macOS) + some on iPad/watch in addition. is anyone else having such issues? we are running current iOS/ipadOS/watchOS-versions + teams 5.3.0. thx for your input/support!

**Comment by Meghana-MSFT** [comment]
This seems to be related to Teams Product issue. We are adding the Teams Product tag so that appropriate team can look into this. Thanks!
