### ISSUE TITLE
Input.ChoiceSet in Adaptive Card is sent as empty choice despite the selection

### ISSUE THREAD

**Issue by MajaEffenberg** [MicrosoftDocs/msteams-docs#8197]
Selected choice in Adaptice Card `Input.ChoiceSet` element, after pressing the `Action.Submit` button is not sent. 

In the attached video you can see that when user click the `Senden` button, the selected choice is unchecked. And our application as the value of `Input.ChoiceSet` receive empty string (`''`) instead of the expected value `'c'`.

This bug currently occurs to one user every time he sends a message from an Adaptive Card containing an `Input.ChoiceSet`. The error occurs in Microsoft Teams app on **Apple iPad Pro** with a recent software version.

This is a critical error in our application, because marked choices are not sent correctly and we do not know what the user has marked. It also causes a lot of confusion for users, as their choice is unchecked when sending.

https://user-images.githubusercontent.com/89073193/221627735-84199197-cebb-44ed-bff1-7fe1e256e0a4.mp4

**Comment by MajaEffenberg** [comment]
The device on which the error appears is:

- model name: iPad Pro (12,9 Inch, 3. Generation)
- model number: MTHV2TY/A
- iPadOS-Version: 16.3.1

**Comment by Meghana-MSFT** [comment]
@MajaEffenberg - Thank you for the additional details, we will raise a bug for the same, we will keep you posted on the updates. Thank you.

**Comment by MajaEffenberg** [comment]
Any news about this bug?

**Comment by Meghana-MSFT** [comment]
@MajaEffenberg - Unfortunately we do not have any update to share. We are following up with the engineering team, please be assured that we will keep you posted on the updates. Thank you for your understanding.

**Comment by Meghana-MSFT** [comment]
@MajaEffenberg - Engineering team is able to receive the selected option. Refer the below screenshot where "option3" was sent to Bot from "iPad".
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/81138249/e1a21ff9-680a-4178-83ab-e3036fd098ac)

It would be helpful if we can get the adaptive card payload, could you please share?

**Comment by Meghana-MSFT** [comment]
@MajaEffenberg - Could you please share the above asked details?

**Comment by Meghana-MSFT** [comment]
@qatestolegmig - Could you please share the adaptive card payload and issue repro video with us?
