### ISSUE TITLE
Not supported JSON object in iOS App for invoke action.

### ISSUE THREAD

**Issue by cimadai** [MicrosoftDocs/msteams-docs#823]
https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/cards/cards-actions#invoke
&gt; The invoke action contains three properties: type, title, and value.
&gt; The value property can contain a string, a stringified JSON object, or a JSON object.
It seems support a string, a stringified JSON object, or a JSON object, but actually only a string and a stringified JSON object in iOS App.

I tried in Desktop App, Android App and iOS App, then Desktop App and Android App support three notations.
But iOS support only two notations.

If I used a JSON object notation, my iOS App was freezed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28d1cbcc-9670-6eb3-d65a-5c30d307784a
* Version Independent ID: 243e29b8-afbc-7d21-1d24-18f58619af60
* Content: [Add card actions in a bot - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/cards/cards-actions#invoke)
* Content Source: [msteams-platform/concepts/Cards/cards-actions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/Cards/cards-actions.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Wajeed-msft** [comment]
Could you please share the code snippet for the card which is failing?

**Comment by cimadai** [comment]
@Wajeed-msft Sure.


This is good activity code.

```typescript
static testActivity: Activity = {
    attachments: [
        {
            contentType: "application/vnd.microsoft.card.adaptive",
            content: {
                $schema: "http://adaptivecards.io/schemas/adaptive-card.json",
                type: "AdaptiveCard",
                version: "1.0",
                body: [
                    {
                        type: "Container",
                        items: [
                            {
                                type: "TextBlock",
                                text: `This is good code`,
                                weight: "bolder",
                                size: "Small"
                            },
                        ]
                    }
                ],
                actions: [
                    {
                        type: "Action.Submit",
                        title: "Submit",
                        data: {
                            msteams: {
                                type: "invoke",
                                value: JSON.stringify({
                                    greeting: "hello world."
                                })
                            }
                        }
                    }
                ],
            }
        }
    ]
} as Activity;
```

And this is bad activity code.

```typescript
static testActivity: Activity = {
    attachments: [
        {
            contentType: "application/vnd.microsoft.card.adaptive",
            content: {
                $schema: "http://adaptivecards.io/schemas/adaptive-card.json",
                type: "AdaptiveCard",
                version: "1.0",
                body: [
                    {
                        type: "Container",
                        items: [
                            {
                                type: "TextBlock",
                                text: `This is good code`,
                                weight: "bolder",
                                size: "Small"
                            },
                        ]
                    }
                ],
                actions: [
                    {
                        type: "Action.Submit",
                        title: "Submit",
                        data: {
                            msteams: {
                                type: "invoke",
                                value: {
                                    greeting: "hello world."
                                }
                            }
                        }
                    }
                ],
            }
        }
    ]
} as Activity;
```

The difference is the value data type.
Good one is a stringified JSON object and Bad one is a JSON object.

**Comment by Gousia-MSFT** [comment]
@cimadai Thanks for reporting this. We have raised a bug for this and we are tracking it internally.
