### ISSUE TITLE
Code Sample name and description dont match the linked repo 

### ISSUE THREAD

**Issue by Ryan365Apps** [MicrosoftDocs/msteams-docs#8231]
"Meeting stage view"  
should be 
"App monetization in tab"

"This app helps to enable and configure your apps for Teams meetings. It also demonstrates use of share in meeting feature." 
should be
"This sample shows how to open purchase dialog and trigger purchase flow using teams-js SDK."

[App monetization in tab](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/tab-app-monetization/nodejs)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fd29bf73-3680-24a6-5c05-76d06c1e40c1
* Version Independent ID: 45035997-0a41-8f4b-575d-ea5ae8ef4bab
* Content: [Include a SaaS offer with your app - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer)
* Content Source: [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md)
* Service: **msteams**
* GitHub Login: @heath-hamilton
* Microsoft Alias: **surbhigupta**

**Comment by Meghana-MSFT** [comment]
@Ryan365Apps - Thank you for reporting this issue, we will check and get the doc updated.

**Comment by Meghana-MSFT** [comment]
@surbhigupta12 - Could you please help to update the code sample section in this document - https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer#code-sample

Please update as below -
Sample Name - App monetization in tab
Description - This is an sample tab application which shows how to open purchase dialog and trigger purchase flow using teams-js sdk
