### ISSUE TITLE
Adaptive card supported as message attachment using 'Connectors for Microsoft 365 Groups'

### ISSUE THREAD

**Issue by timeverts** [MicrosoftDocs/msteams-docs#8236]
The table [here](https://learn.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference#features-that-support-different-card-types) states that adaptive cards are not supported for Connectors for Microsoft 365 Groups.

However, using the format documented [here](https://learn.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-using?tabs=cURL#send-adaptive-cards-using-an-incoming-webhook), it _is_ possible to send adaptive cards for these connectors.

Perhaps it's worth adding it to the notes below the table.

You may also want to consider updating the note at the top of [this](https://learn.microsoft.com/en-us/outlook/actionable-messages/message-card-reference) page.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Types of cards - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference#features-that-support-different-card-types)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by sayali-MSFT** [comment]
@timeverts - Thanks for reporting your issue.
We will check this at our end and update the document accordingly.

**Comment by sayali-MSFT** [comment]
@timeverts -We have tried the same but showing the error while tried the adaptive card for Connectors for Microsoft 365 Groups.
Could you please share the repro steps so that we can try it from our end?

**Comment by timeverts** [comment]
@sayali-MSFT, after you have setup a Connector for Microsoft 365 groups, follow the steps [here](https://learn.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-using?tabs=cURL#send-adaptive-cards-using-an-incoming-webhook) to create an adaptive card that can be sent to the connector URL.

A message in that format can be used to send an adaptive card to a Connector for Microsoft 365 groups.

**Comment by sayali-MSFT** [comment]
@timeverts -We ae also trying the same as mentioned above. We are able to send the adaptive card.
We are confirming with the engineering team and update the document accordingly.

**Comment by sayali-MSFT** [comment]
Got the reply from engineering teams, "The table is accurate in that Adaptive cards are only supported for Incoming Webhook type Connectors, not for all other Connectors."

**Comment by timeverts** [comment]
So the table itself might be accurate, but it would be worth informing users there is a way to get it working using a different format of the JSON (as we've both shown it _is._ possible)

As mentioned in my original post, my suggestions are:

> Perhaps it's worth adding it to the notes below the table.

> You may also want to consider updating the note at the top of [this](https://learn.microsoft.com/en-us/outlook/actionable-messages/message-card-reference) page.

**Comment by sayali-MSFT** [comment]
@timeverts -We are confirming with the engineering team and update the document accordingly.

**Comment by sayali-MSFT** [comment]
@surbhigupta12 -Could you please help us to update the document.
Add the note in below document-
Note-Adaptive Card supports only Incoming Webhook O365 Connector type and not any other O365 Connector types. You can send the adaptive cards for these connectors using below JSON format.

Document Link-https://learn.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-using?tabs=cURL#send-adaptive-cards-using-an-incoming-webhook
