### ISSUE TITLE
Commendation

### ISSUE THREAD

**Issue by AndyLKhuu** [MicrosoftDocs/msteams-docs#824]
The Section "Leverage what you've already built" is really useful. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d160926a-58af-cf0a-bc9d-f9490d04be36
* Version Independent ID: e729fb32-86b3-ceca-3a66-639176e515bc
* Content: [Design apps for Microsoft Teams - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/apps/apps-design#feedback)
* Content Source: [msteams-platform/concepts/apps/apps-design.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/apps/apps-design.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Wajeed-msft** [comment]
Thank you for your feedback.
