### ISSUE TITLE
botbuilder v4 support

### ISSUE THREAD

**Issue by azzurolilc** [MicrosoftDocs/msteams-docs#825]
current version runs on botbuilder v3, examples need updating

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ef8b328-5f30-9a29-bd8a-23281ac917c6
* Version Independent ID: de0c7fce-8153-b87d-0392-40dab998e535
* Content: [Authentication for bots using Azure Active Directory - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/authentication/auth-bot-AAD#feedback)
* Content Source: [msteams-platform/concepts/authentication/auth-bot-AAD.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/authentication/auth-bot-AAD.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Wajeed-msft** [comment]
We will be updating our documentation around the time that the v4 SDKs go to general availability. You can start looking at [SDKs & Tools](https://docs.microsoft.com/en-us/microsoftteams/platform/#pivot=sdk-tools) section for available sample code. Here are quick links for SDK v4 sample [C#](https://github.com/OfficeDev/BotBuilder-MicrosoftTeams-dotnet/tree/master/CSharp/Samples) & [Node.js](https://github.com/OfficeDev/BotBuilder-MicrosoftTeams-node/tree/master/samples).
