### ISSUE TITLE
NGROK ISSUES

### ISSUE THREAD

**Issue by mbaxamb3333** [MicrosoftDocs/msteams-docs#8252]
I am trying to go through one of your youtube tutorials about how to create a personal tab. 

[https://www.youtube.com/watch?v=R-oJ55vuwEk&list=PLWZJrkeLOrbY8HkTBBvyx-uyZ3cCdl1VM&index=3](url)
This is the video in cause. 

When I try to run the ngrok server, although I have an account with ngrok, and I have registred my Authentication Token in the ngrok.yml file, I get the following message:

ERR_NGROK_6022

Before you can serve HTML content, you must [sign up for a free ngrok account](https://dashboard.ngrok.com/signup) and install your [authtoken](https://dashboard.ngrok.com/get-started/your-authtoken).

I have an ngrok account and I have installed my authtoken. 

What am I missing? are there any more steps that I need to take?

**Comment by sayali-MSFT** [comment]
@mbaxamb3333 - Thanks for reporting your issue.
We will check this at our end and will get back to you.

**Comment by mbaxamb3333** [comment]
To give you some more context, if I run ngrok separately on port 3007 and in another tab I will just serve the application, things will work fine when trying to open the links in the browser. 
When I upload the package to teams, it shows nothing. No error message, nothing.

**Comment by mbaxamb3333** [comment]
<img width="1179" alt="Screenshot 2023-03-08 at 14 16 51" src="https://user-images.githubusercontent.com/70760023/223736336-1ac8e04d-26cc-4321-aeb9-32b377f1c563.png">

**Comment by sayali-MSFT** [comment]
@mbaxamb3333 - If you sign up for a free ngrok.io account, and then use the following to configure your authtoken:

`./node_modules/.bin/ngrok authtoken 1cYD7J3...XbpC54S`

We are not able to open the URL provided by you.
Here is one sample personal tab-https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/tab-personal/mvc-csharp

Related Thread- https://github.com/pnp/generator-teams/issues/335
