### ISSUE TITLE
Teams Deeplink - email as mandatory value doesn't makes sense for sharing content purposes

### ISSUE THREAD

**Issue by zubintro** [MicrosoftDocs/msteams-docs#8255]
Hi, I believe the name/email of the user should not be mandatory because is super common the option to share a content and use the opened tool (email, social media app, etc) to find the user to who we want to share the content. Make mandatory the email value forces to the user, know or move to the tool to find it and doesn't make easily to use this function for sharing purposes

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 98d88f26-f11f-4810-162a-40ca552be3e3
* Version Independent ID: 98d88f26-f11f-4810-162a-40ca552be3e3
* Content: [Deep link to a workflow in Teams - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-link-workflow?tabs=teamsjs-v2)
* Content Source: [msteams-platform/concepts/build-and-test/deep-link-workflow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/build-and-test/deep-link-workflow.md)
* Service: **msteams**
* GitHub Login: @v-npaladugu
* Microsoft Alias: **surbhigupta**

**Comment by Meghana-MSFT** [comment]
We are looking into this, we will get back to you.

**Comment by zubintro** [comment]
Thanks. Think on this like the common button to share through email, well I have the same intention, I need to use the URL to share content using teams. Doesn't make sense that go and open teams, copy the UPN/ID/email of the user and finally, fill a field in the web with the value to share the content and go again to teams.

In my opinion, the params must be optionals to open a new chat with the prefilled message and after this, find the users

https://teams.microsoft.com/l/chat/0/0?

users=<user1>,<user2>,...        - OPTIONAL (now mandatory)
&
topicName=<chat name>          - OPTIONAL
&
message=<precanned text>     - OPTIONAL

**Comment by Meghana-MSFT** [comment]
Deep link to start a new chat or other deeplinks were making email or usernames required. We will share this feedback with the team.

**Comment by Meghana-MSFT** [comment]
We have shared this feedback on Teams feedback portal - https://feedbackportal.microsoft.com/feedback/idea/e2b70797-92d3-ed11-a81b-6045bd808412.

You can vote the feedback raised.

**Comment by Meghana-MSFT** [comment]
We are closing this issue, please feel free to reach out to us if you have any further questions. Thank you.
