### ISSUE TITLE
Tell developers about under which level in json should they put the customized config node

### ISSUE THREAD

**Issue by IvanJobs** [MicrosoftDocs/msteams-docs#8259]
Hi there,

For this doc [use and existing azure aad app for your bot](https://learn.microsoft.com/en-us/microsoftteams/platform/toolkit/provision?pivots=visual-studio-code#use-an-existing-azure-ad-app-for-your-bot), developers don't know under which level in the json file should the bot config section be put.
![image](https://user-images.githubusercontent.com/1803943/223647747-93182659-2b0a-4277-85f4-671022a9c6d0.png) Developers may mis-place the section into `manifest`, but it should be parallel with the `manifest` node causing unexpected behaviors.

It's better to add more json nodes to show the overall levels like below:
```json
"$schema": "https://aka.ms/teamsfx-env-config-schema",
"description": "...",
"manifest": {
  ...
},
// Add code below. Note you need to replace the placeholders with real values.
"bot": {
    "appId": "<your Azure AD app client id>",
    "appPassword": "{{$env.ENV_NAME_THAT_STORES_YOUR_SECRET}}"
}
```
Another thing is developers may not know where to find the existing values of appId and appPassword, so it's better to add one more sentence like below:
```
If you don't know where to find correct values for appId and appPassword, see [how to use existing Azure AD app in TeamsFx project](https://github.com/OfficeDev/TeamsFx/blob/dev/docs/fx-core/using-existing-aad.md).
```

**Comment by Meghana-MSFT** [comment]
@surbhigupta12 - Could you please help to update the document. 

1) Please update the following [JSON snippet](https://learn.microsoft.com/en-us/microsoftteams/platform/toolkit/provision?pivots=visual-studio-code#use-an-existing-azure-ad-app-for-your-bot) to - 
```
"$schema": "https://aka.ms/teamsfx-env-config-schema",
"description": "...",
"manifest": {
  ...
},
// Add code below. Note you need to replace the placeholders with real values.
"bot": {
    "appId": "<your Azure AD app client id>",
    "appPassword": "{{$env.ENV_NAME_THAT_STORES_YOUR_SECRET}}"
}
```
2) Please add the below statement as a note in the doc

If you don't know where to find correct values for appId and appPassword, see [how to use existing Azure AD app in TeamsFx project](https://github.com/OfficeDev/TeamsFx/blob/dev/docs/fx-core/using-existing-aad.md).
