### ISSUE TITLE
Typo in "understand your user" section

### ISSUE THREAD

**Issue by yadhunandantg** [MicrosoftDocs/msteams-docs#8264]
[Enter feedback here]
_Understand your user section_ says _It's recommended to go through the **lean module** [how to publish your app to Teams app store](https://learn.microsoft.com/en-us/training/modules/microsoft-teams-publish-app-to-store/) to help with your app to pass the Microsoft Teams store submission process._

Is it lean module or **learning module**?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b081ffcd-32a2-03ed-1ca9-1d32bdeff00b
* Version Independent ID: 763faefd-c15e-4d32-78ff-9fc95e7f0c73
* Content: [Understanding your app's use cases and Teams features - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/design/understand-use-cases)
* Content Source: [msteams-platform/concepts/design/understand-use-cases.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/design/understand-use-cases.md)
* Service: **msteams**
* GitHub Login: @heath-hamilton
* Microsoft Alias: **anclear**

**Comment by Nivedipa-MSFT** [comment]
@yadhunandantg - Thanks for reporting your issue. We will update the content as learning instead of lean.

@surbhigupta12 - Could you please update the content learning instead of lean in following document.
https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/design/understand-use-cases
