### ISSUE TITLE
Can we mention a tag via Incoming Webhook Adaptive Card? 

### ISSUE THREAD

**Issue by ShivamSinghal1** [MicrosoftDocs/msteams-docs#8265]
Hi!

I am trying to send an adaptive card with mentioning a tag (custom user group in a team). 

Example Request - 
Url - https://xx.webhook.office.com/webhookb2/xx-xx-xx-xx-xx@xx-xx-xx-xx-xx/IncomingWebhook/xx/xx-xx-xx-xx-xx
```json
{
    "type": "message",
    "attachments": [
        {
        "contentType": "application/vnd.microsoft.card.adaptive",
        "content": {
            "type": "AdaptiveCard",
            "body": [
                {
                    "type": "TextBlock",
                    "text": "Hi <at>TAG NAME</at> Testing Tagging via Incoming Webhook."
                }
            ],
            "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
            "version": "1.0",
            "msteams": {
                "entities": [
                    {
                        "type": "mention",
                        "text": "<at>TAG NAME</at>",
                        "mentioned": {
                          "id": "TAG ID",
                          "name": "TAG NAME"
                        }
                    }
                ]
            }
        }
    }]
}
```
The output of this message -> 

<img width="456" alt="Screenshot 2023-03-09 at 12 52 12 PM" src="https://user-images.githubusercontent.com/44235074/223949640-b0ca0878-a6e3-463d-800e-e3f9ab5959f4.png">

Didn't get any notification of being tagged, also not getting any information related to this tag on hover.

**Comment by Meghana-MSFT** [comment]
Currently only user mention is supported in Incoming webhook. Mentioning tag is not yet supported. You can request this feature using [Microsoft Teams Feedback portal](https://feedbackportal.microsoft.com/feedback/forum/ad198462-1c1c-ec11-b6e7-0022481f8472).

**Comment by ShivamSinghal1** [comment]
Thanks for your response!
