### ISSUE TITLE
Issues with Typescript sample code

### ISSUE THREAD

**Issue by eoinobrien** [MicrosoftDocs/msteams-docs#8282]
Hi,

I'm not sure of the correct answers to some of these questions so the relevant team might need to be asked.

The sample code typescript code has a number of issues.

1. The code doesn't run:
    * `await this.getPagedMembers(context);` doesn't exist, instead I had to use `await TeamsInfo.getPagedMembers(context);` as described in the sample code reference https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/3ebe3984becc8b505f4e696bdecafe6971a8e32b/samples/graph-proactive-installation/nodejs/bots/proactiveBot.js#L53
    * I got the following error `Property createConversation does not exist on type 'BotAdapter'` with the `createConversation` call.
        * The SDK reference also doesn't include this as a function
1. This doesn't look like Typescript code, it is probably valid typescript, but without the types it just looks like javascript. Even the sample code reference is actually JS.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4ad9f167-7d29-f933-7b47-60bd744899b1
* Version Independent ID: 8097fcbd-adcc-ce49-a378-426c65af9296
* Content: [Send proactive messages - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/send-proactive-messages?tabs=json)
* Content Source: [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/bots/how-to/conversations/send-proactive-messages.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **surbhigupta**

**Comment by Nivedipa-MSFT** [comment]
@eoinobrien - Thanks for reporting your issue. We will check this and update you soon.

**Comment by Nivedipa-MSFT** [comment]
@eoinobrien - We will check and update the code accordingly.

**Comment by Nivedipa-MSFT** [comment]
@surbhigupta12 - Could you please update the Title as JavaScript and below code in [this](https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/send-proactive-messages?tabs=typescript#tabpanel_1_typescript) link.

 ```
 async SendNotificationToAllUsersAsync(context) {
        const TeamMembers = await TeamsInfo.getPagedMembers(context);
        let Sent_msg_Cout = TeamMembers.members.length;
        TeamMembers.members.map(async member => {
            const ref = TurnContext.getConversationReference(context.activity);
            ref.user = member;
            await context.adapter.createConversation(ref, async (context) => {
                const ref = TurnContext.getConversationReference(context.activity);
                await context.adapter.continueConversation(ref, async (context) => {
                    await context.sendActivity("Proactive hello.");
                });
            });
        });
        await context.sendActivity(MessageFactory.text("Message sent:" + Sent_msg_Cout));
    }
```
