### ISSUE TITLE
Messageback doesn't work on Teams Mobile again!

### ISSUE THREAD

**Issue by StevenGao77** [MicrosoftDocs/msteams-docs#8290]
Hello team, I noticed Messageback doesn't work on Teams Mobile again! IMback works fine. I am using iOS with Teams Mobile

**Comment by Prasad-MSFT** [comment]
Hi @StevenGao77 - Thanks for raising your issue. We will check this at our end and respond back with our findings.
In the meantime can you please confirm whether you are facing this in Android or iOS along with Teams version details?

**Comment by Prasad-MSFT** [comment]
@StevenGao77 - We tried to repro this issue using `messageBack` action type, however it worked perfectly fine in MS Teams Desktop, Web, Android and iOS clients.
Card used:
```
                Buttons = new List<CardAction>
                {
                    new CardAction()
                    {
                        Type = ActionTypes.MessageBack,
                        Title = "My MessageBack button",
                        DisplayText = "I clicked this button",
                        Text = "User just clicked the MessageBack button",
                        Value = "{\"property\": \"propertyValue\" }"
                    },
                },
```
Attaching screenshot for reference:
![image](https://user-images.githubusercontent.com/62237649/225577366-f4c28fde-e581-4e88-b06c-3c3049768c53.png)
iOS 16.3.1
Teams version:
![image](https://user-images.githubusercontent.com/62237649/225577582-b56f3d30-63a4-49aa-96e2-e27949561c3d.png)

**Comment by StevenGao77** [comment]
@Prasad-MSFT, please kindly check it, Thanks!

**Comment by StevenGao77** [comment]
Thanks, I will check your code and see if I can report the issue or not.

**Comment by StevenGao77** [comment]
@Prasad-MSFT , I tested CardAction and yes it works, however what I used it AdaptiveSubmitAction which isn't working still, Can you test by using AdaptiveSubmitAction? Thanks

**Comment by Prasad-MSFT** [comment]
@StevenGao77 - Does it work in other clients such as Desktop/web?

**Comment by StevenGao77** [comment]
May I know which Adaptive Card version should I use? 1.2 or 1.3?

**Comment by StevenGao77** [comment]
![card](https://user-images.githubusercontent.com/46369364/226322705-a6f897e6-3150-40f2-857f-b1fdf6b10444.png)

and my VS 2019 can't build it

**Comment by Prasad-MSFT** [comment]
![image](https://user-images.githubusercontent.com/62237649/226325542-0085a9cc-413c-451c-8b1a-8a6552de848f.png)
We are using VS 2022

**Comment by Prasad-MSFT** [comment]
@StevenGao77 - It should support AdaptiveSubmitAction .

**Comment by StevenGao77** [comment]
however it doesn't work, I even tried use Power Automate to post an adaptive cared to Teams but it doesn't work from Mobile version, you may test it.

{
    "type": "AdaptiveCard",
    "body": [
        {
            "type": "TextBlock",
            "size": "Medium",
            "weight": "Bolder",
            "text": "Test Adaptive Card schema"
        }
    ],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.4",
    "actions": [
        {
            "type": "Action.Submit",
            "title": "Imback",
            "data": {
                "id": "msgid1",
                "value": "textmsgimback",
                "msteams": {
                    "type": "ImBack",
                    "text": "textmsgimback",
                    "value": "textmsgimback"
                }
            }
        },
        {
            "type": "Action.Submit",
            "title": "MessageBack",
            "data": {
                "id": "msgid1",
                "value": "textmsgimback",
                "msteams": {
                    "type": "MessageBack",
                    "text": "textmsgimback",
                    "value": "textmsgimback"
                }
            }
        }
    ]
}

**Comment by StevenGao77** [comment]
I have reported to Microsoft Support Team, and they can reproduce the issue. I hope they can fix the issue. Thanks for your help anyway.

**Comment by Prasad-MSFT** [comment]
@StevenGao77 - We are also able to repro this issue using the above JSON provided. It doesn't work in mobile devices if we send above card using Power Automate or Bot. 
We also have raised a bug for the same and engineering team is looking into it. We will inform you once we get any further update. Thanks!

**Comment by StevenGao77** [comment]
Thanks @Prasad-MSFT for the confirmation, looking forward to hear the update when we can fix it.

**Comment by StevenGao77** [comment]
@Prasad-MSFT , Do you have any info when the bug will be fixed?

**Comment by Prasad-MSFT** [comment]
@StevenGao77 - Apologies. Currently there is no update from engineering team side. We are following up with them regarding this. We will let you know the updates once we hear from them. Thanks!

**Comment by StevenGao77** [comment]
@Prasad-MSFT, do you have any update?

**Comment by Prasad-MSFT** [comment]
@StevenGao77 - We got update from engineering team saying "We do not support this type because of it being case sensitive."
After changing "MessageBack" to "messageBack" the issue was resolved and Android worked as expected.
Could you please verify doing the same for the Type field?

**Comment by StevenGao77** [comment]
Thanks @Prasad-MSFT, yes this workaround solve the problems but I used same code over 2 years and it works well till recently user reported such issue. Mostly could be some changes happened at the backend.

**Comment by Prasad-MSFT** [comment]
We are closing this issue for now. Please feel free to reopen if required. Thanks!
