### ISSUE TITLE
Where one should get an appId to submit task with parameters?

### ISSUE THREAD

**Issue by crow-ua** [MicrosoftDocs/msteams-docs#830]
`If you do call submitTask() with a result parameter, you must pass an appId or an array of appId strings`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28710a9a-332d-6f67-e4cc-9681a1798e0f
* Version Independent ID: 116d97a4-dabd-036e-630b-7cf080b87099
* Content: [Using Task Modules in Microsoft Teams bots - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/task-modules/task-modules-bots)
* Content Source: [msteams-platform/concepts/task-modules/task-modules-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/task-modules/task-modules-bots.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Trinetra-MSFT** [comment]
you need to pass appID in your taskInfo object from your web.config. Please see the code below 
function submitHandler() {
           let taskInfo = {
                title: null,
                height: null,
                width: null,
                url: null,
                card: null,
                fallbackUrl: null,
                completionBotId: null,
            };
taskInfo.completionBotId = "@(ApplicationSettings.MicrosoftAppId)";
            microsoftTeams.tasks.submitTask(taskInfo,); 
            return true;
        } 
please follow this [doc ](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/task-modules/task-modules-overview#the-taskinfo-object)for more info  and let me know if you face any issue.

**Comment by Raveendra123** [comment]
Hello ,
I am running with issue we are using task module with deep link for upload link in adaptive card .once click that link it will open upload popup in teams bot but it is not opening in web browser teams and desktop teams app.
the below URL used to redirecting on upload link click.
https://teams.microsoft.com/l/task/6132add7-9049-472d-a329-de6290441c00?url=https%3A%2F%2Ficebreaker-y5l22i4ytireq.azurewebsites.net%2FUpload%2FUpload&height=450&width=510&title=Upload&completionBotId=6132add7-9049-472d-a329-de6290441c00
Note : it is working for some of the users but not for all.

can you please help me to get the resolution .Is it issue with users or teams app access related permissions. if you need more details please let me know
Thanks
Raveendra

**Comment by crow-ua** [comment]
@Trinetra-MSFT Good to know, thanks.

**Comment by Raveendra123** [comment]
Can you please help us on the issue. i will create new bug if required.
