### ISSUE TITLE
This tutorial says you need to install the ".NET Core cross-platform development" workload but the installer UI does not have any such workload

### ISSUE THREAD

**Issue by AE-MS** [MicrosoftDocs/msteams-docs#8300]
https://learn.microsoft.com/en-us/microsoftteams/platform/sbs-gs-csharp?tutorial-step=1
This page says to choose the ".NET Core cross-platform development" workload but the Visual Studio installer does not have any such workload listed that I can see.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 868d10d0-97f7-0be0-3cf5-8a26ad6db573
* Version Independent ID: 868d10d0-97f7-0be0-3cf5-8a26ad6db573
* Content: [Hello World with C# - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/sbs-gs-csharp?tutorial-step=1)
* Content Source: [msteams-platform/sbs-gs-csharp.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/sbs-gs-csharp.yml)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Prasad-MSFT** [comment]
Thanks @AE-MS for raising this issue. We also noticed that `.NET Core cross-platform development` workload is no where listed in Visual Studio.

@surbhigupta12 - Requesting your help to remove the mentions of `.NET Core cross-platform development` workload from all the instances from the documentations.

Few other places where we have seen this being mentioned: 
[Create Teams conversation bot - Teams | Microsoft Learn](https://learn.microsoft.com/en-us/microsoftteams/platform/sbs-teams-conversation-bot?tutorial-step=1)
[Prerequisites - Teams | Microsoft Learn](https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/tab-requirements#tools-to-build-tabs)
