### ISSUE TITLE
More ressources / guided steps to use TaskModules

### ISSUE THREAD

**Issue by HN5** [MicrosoftDocs/msteams-docs#831]
Hi, is there any possibility to get more guided step/turorial to be able to use TaskModules and replicate button modal on a static website :(

i don't figure out how to handle this with the documentation or with the source code from TaksModul Sample from @billbliss . maybe i'm missing something :/

Many thx for your time & help

**Comment by Gousia-MSFT** [comment]
@HN5 Are you trying to open Task Module from a tab? Could you please try this sample to open [task module from tabs](https://github.com/OfficeDev/microsoft-teams-sample-task-module-csharp/blob/master/Microsoft.Teams.Samples.TaskModule.Web/Views/Home/Tasks.cshtml)? Please let us know if you are facing any issues.

**Comment by Gousia-MSFT** [comment]
Please re-open if you are still facing any issue.
