### ISSUE TITLE
[Doc-Enhancement] Bot content cannot be changed based on user selected Teams theme 

### ISSUE THREAD

**Issue by SubbaReddi** [MicrosoftDocs/msteams-docs#8324]
Hi Team,
The current user interface (UI) theme such as default, dark, or contrast can be identified using Teams sdk in tab with following reference: https://learn.microsoft.com/en-us/javascript/api/@microsoft/teams-js/app.appinfo?view=msteams-client-js-latest#@microsoft-teams-js-app-appinfo-theme

Based on theme, images or content styles can be changed in tab application. But the same thing cannot be done in Bots. Content styles/images posted using adaptive cards in bots cannot be changed based on theme. So, same thing needs to be considered during the design. Please mention the note related to the same.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3af8496d-46be-a691-11e1-16734f71f891
* Version Independent ID: be0ff3e1-8bef-5ca7-8d9c-566e89e3fd41
* Content: [Bots in Microsoft Teams - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/bots/what-are-bots)
* Content Source: [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/bots/what-are-bots.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **anclear**

**Comment by Meghana-MSFT** [comment]
@surbhigupta12 - Could you please help to add the above note in the doc - https://learn.microsoft.com/en-us/microsoftteams/platform/bots/what-are-bots

Note : Bot content cannot be changed based on user selected Teams theme.
