### ISSUE TITLE
Messaging extensions steps are incorrect

### ISSUE THREAD

**Issue by jthake-msft** [MicrosoftDocs/msteams-docs#833]
https://docs.microsoft.com/en-us/microsoftteams/platform/get-started/get-started-dotnet-app-studio#messaging-extensions

Clicking add command in the Messaging extensions in App Studio gives you two options: "Allow user to query your service for information and insert that into a message" and "Allow users to trigger actions in external services while inside of Teams".
Clicking the first option gets to a similar window of "New Command" in the tutorial But there is a new final option of set type of input required. Which is text..

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98cd21c7-e87c-3c5b-7574-998a355f9f08
* Version Independent ID: 5e312707-facc-03fc-af59-90267d0c7b8a
* Content: [Get started with C#/.NET - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/get-started/get-started-dotnet-app-studio)
* Content Source: [msteams-platform/get-started/get-started-dotnet-app-studio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/get-started/get-started-dotnet-app-studio.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Gousia-MSFT** [comment]
@jthake-msft Thanks for reaching out. We are working on updating the documentation to reflect the current behavior.

**Comment by clearab** [comment]
Thanks Jake, fixed!
