### ISSUE TITLE
Meeting scheduling dialog: content does not support HTML

### ISSUE THREAD

**Issue by rpohomenko** [MicrosoftDocs/msteams-docs#8331]
Deep link to open a meeting scheduling dialog
Parameter: content

https://teams.microsoft.com/l/meeting/new?subject={meeting subject}&content={html content}

It works with Mobile version only

**Comment by Meghana-MSFT** [comment]
Thank you for reporting this issue, we will check this and get back to you.

**Comment by Meghana-MSFT** [comment]
Similar issue was reported here at https://learn.microsoft.com/en-us/answers/questions/1118566/style-content-of-teams-deep-link. We have a bug raised for the same, we will keep you posted on the updates. Thanks.

**Comment by Meghana-MSFT** [comment]
@rpohomenko - Engineering team has confirmed that HTML is currently not supported. Could you please raise this on [Microsoft Teams Feedback Portal](https://feedbackportal.microsoft.com/feedback/forum/ad198462-1c1c-ec11-b6e7-0022481f8472).

**Comment by Meghana-MSFT** [comment]
We are closing this issue for now. please feel free to reach out to us if you have any questions. Thank you!
