### ISSUE TITLE
The default app long name includes Microsoft which throws warning Test and Distribute step

### ISSUE THREAD

**Issue by jthake-msft** [MicrosoftDocs/msteams-docs#834]
When publishing the test app. The manifest set the app long name to include "Microsoft Teams". App Studio throws this error:

"Full name should not contain “Microsoft” or any of the Microsoft product names (e.g. "Excel")."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98cd21c7-e87c-3c5b-7574-998a355f9f08
* Version Independent ID: 5e312707-facc-03fc-af59-90267d0c7b8a
* Content: [Get started with C#/.NET - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/get-started/get-started-dotnet-app-studio)
* Content Source: [msteams-platform/get-started/get-started-dotnet-app-studio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/get-started/get-started-dotnet-app-studio.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Gousia-MSFT** [comment]
@jthake-msft We are working on updating the sample to reflect the expected behavior. Thanks!!

**Comment by clearab** [comment]
Fixed, thanks!
