### ISSUE TITLE
Issue with changing endpoint of an old Teams App and Bot

### ISSUE THREAD

**Issue by rsgupta94** [MicrosoftDocs/msteams-docs#8344]
I created a teams app for sending notifications from my application in 2022. I also had a proper bot handle in the Azure portal which was used to send proper notification messages to my Teams app using an endpoint that I declared in its settings. Recently, we have updated our application's URL and I need to update the endpoint of the bot as well. However, I'm unable to find the bot anywhere. It's neither in the Teams Developer's Portal nor in [https://dev.botframework.com/bots](https://dev.botframework.com/bots). Due to this reason, my Teams App has stopped working. As per this [link](https://learn.microsoft.com/en-us/answers/questions/670277/why-cant-i-see-web-app-bot-in-the-market-place), "Web App Bot and Bot Channels Registration are deprecated but existing resources will continue to work". However, there is no mention of how to update the settings of an old, existing, working bot.

**Comment by Prasad-MSFT** [comment]
Could you please login to [Azure portal](https://portal.azure.com/) and check under **Bot Services** section, you will be able to find your bot and on clicking on the bot, there is **Configuration** pane from where you can change your bot endpoint?
![image](https://user-images.githubusercontent.com/62237649/227225552-71217938-0411-417e-ba30-666ca1196cfe.png)

**Comment by rsgupta94** [comment]
I checked the Azure Portal's Bot Services section, but no bots are listed over there. It's completely empty. I have the testing website and the Teams App + the bot is working fine over there (The production website is not working since we are updating the URL and hence want to update the bot endpoint). Even that is not listed here. So I'm completely unable to update any configuration of the bots of any website.

**Comment by Prasad-MSFT** [comment]
@rsgupta94 - Could you please confirm if you are able to see the app registration as part of your AAD tenant? If not, could you please raise a support ticket so that support team can check the issue with missing bot registration.  

If you have a paid Azure subscription, visit the Azure Admin Center to [open a ticket](https://ms.portal.azure.com/#blade/Microsoft_Azure_Support/HelpAndSupportBlade/newsupportreq)

**Comment by rsgupta94** [comment]
@Prasad-MSFT Yes, all the app registrations are listed properly.

**Comment by Prasad-MSFT** [comment]
@rsgupta94 - Please raise a support ticket so that support team can check the issue with missing bot registration.  

If you have a paid Azure subscription, visit the Azure Admin Center to [open a ticket](https://ms.portal.azure.com/#blade/Microsoft_Azure_Support/HelpAndSupportBlade/newsupportreq)

**Comment by rsgupta94** [comment]
We had created a support ticket earlier and we were redirected to customer support who instructed us to create an issue over here, which we did. It's going back and forth!

**Comment by Prasad-MSFT** [comment]
@rsgupta94 - Could you please send out an email to  [Microsoft Teams Community Help](mailto:microsoftteamsdev@microsoft.com) and schedule a call, so that we can check the issue you are facing?

**Comment by rsgupta94** [comment]
@Prasad-MSFT I have sent a mail to the email id you mentioned

**Comment by Prasad-MSFT** [comment]
Hi @rsgupta94 - We have responded to your mail. Please have a look and let us know about your availability.

**Comment by rsgupta94** [comment]
Hi @Prasad-MSFT - We dropped an email yesterday requesting for a call today at 12 pm IST. However, we didn't get any reply from your end. Please drop me an email regarding your availability. **We'll be available on weekdays, from 12 pm IST onwards.**

**Comment by Prasad-MSFT** [comment]
Hi @rsgupta94 - For some reason we didn't get the mail and missed the instance. Please schedule a call on 17th April 12 PM IST.
Thanks!

**Comment by rsgupta94** [comment]
Hi,

Sounds good! Please call us on 17th April at 12 PM IST.  Please add the following emails for the call - ***@***.***, and ***@***.***


Thanks and Regards,

Rajdeep Sengupta

Tech Lead

CodeIAM (India) Private Limited

M : +91-7980956126

W: www.codeiam.com<http://www.codeiam.com/>

________________________________

**Comment by Prasad-MSFT** [comment]
@rsgupta94 - As discussed in the scheduled call earlier, we are checking this issue with engineering team and will inform you once we get any update.
In the meantime, could you please try raising a support request as below?
![image](https://user-images.githubusercontent.com/62237649/232782174-bf2c05a9-3902-46dd-985f-89ecd311ce15.png)

**Comment by Prasad-MSFT** [comment]
Hello everyone,
We are checking this issue with engineering team. Currently there is no update to share. We will inform you once we hear anything from engineering team.
Thanks!
