### ISSUE TITLE
Availability of Speech to Text Captions via API?

### ISSUE THREAD

**Issue by GauravES** [MicrosoftDocs/msteams-docs#8356]
[Enter feedback here]
Can you clarify if this API will only return the chat transcript of the meeting or will it also include any Speech to Text translated captions?  If not, is there a different API to retrieve the speech to text live captions?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 23fb5403-f29d-1479-0899-83a470f4fa05
* Version Independent ID: 23fb5403-f29d-1479-0899-83a470f4fa05
* Content: [Use Microsoft Graph to fetch transcripts for a Teams meeting - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/graph-api/meeting-transcripts/overview-transcripts)
* Content Source: [msteams-platform/graph-api/meeting-transcripts/overview-transcripts.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/graph-api/meeting-transcripts/overview-transcripts.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Meghana-MSFT** [comment]
@GauravES - To get the meeting transcription shown in below screenshot, you can use Get callTranscript Graph API. 
![image](https://user-images.githubusercontent.com/81138249/227504124-860d7193-5ac6-4687-b5ea-ed0c0d523e11.png)

There is no API to retrieve live captions in meeting.
![image](https://user-images.githubusercontent.com/81138249/227504399-b1cbd9be-870f-409c-be77-8f949508f6ca.png)
