### ISSUE TITLE
Update Take ownership part 

### ISSUE THREAD

**Issue by srinidyMSFT** [MicrosoftDocs/msteams-docs#8357]
In the app import section, 
Please update point 4. 

You can import an existing app which you created on App Studio to Developer Portal. To import an already published app to Developer Portal, the [app owner](https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/manage-your-apps-in-developer-portal#advanced) needs to raise a service request through [admin portal](https://admin.microsoft.com/Adminportal/Home?#/support) to transfer the ownership over the app ID.

Can we remove the service request through admin portal? 

Please include this instead, 

Global tenant admin of the Teams app will now be able to take ownership of any apps on their tenant that is missing owners. 
<img width="528" alt="image" src="https://user-images.githubusercontent.com/109306502/227424948-3dc885e6-5c68-4459-9c88-ec545c74aa83.png">

<img width="447" alt="image" src="https://user-images.githubusercontent.com/109306502/227425000-a4e7ab2f-73f1-4a1e-b742-fe91b0cc4be8.png">

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7da63b6f-15d7-a6dd-82fc-d183afaeb816
* Version Independent ID: 82d1ca83-28dd-220e-ab0c-a4833f8f8143
* Content: [Developer Portal for Teams - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/teams-developer-portal#import-an-existing-app)
* Content Source: [msteams-platform/concepts/build-and-test/teams-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/build-and-test/teams-developer-portal.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **surbhigupta**

**Comment by Prasad-MSFT** [comment]
Hi @srinidyMSFT - Could you please help here to update the document accordingly?
