### ISSUE TITLE
Teams chat integration in iOS and angular 7 app?

### ISSUE THREAD

**Issue by nyghtrocker** [MicrosoftDocs/msteams-docs#837]
We would like to use the chat functionalities in Microsoft Teams, like...
Message chat
Online chat
Video chat (sending video)
Pictures (sending pictures)
Audio (sending audio)
... and get this functionality integrated in our iOS app and in Angular 7
Is it possible to integrated teams chat in iOS app?

**Comment by billbliss** [comment]
This is not possible yet, other than using Microsoft Graph APIs directly, which is a) difficult for what you are talking about here, b) require elevated privileges that most admins will be reluctant to grant.

We plan to support this in the future, but it unfortunately won't be any time soon, and it may be on web/desktop ahead of mobile (although we are working on converging those codebases over time).
