### ISSUE TITLE
direct deeplink to share to teams

### ISSUE THREAD

**Issue by mohitaswal99** [MicrosoftDocs/msteams-docs#8392]
[Enter feedback here]

Is there a direct deeplink to share to teams as it exists for going to channel and chat
Eg
https://teams.microsoft.com/share?href={URL}
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9cb013cb-3a19-2142-5286-692ff9b32ea6
* Version Independent ID: 9cb013cb-3a19-2142-5286-692ff9b32ea6
* Content: [Share to Teams from web apps - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/share-to-teams-from-web-apps)
* Content Source: [msteams-platform/concepts/build-and-test/share-to-teams-from-web-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/build-and-test/share-to-teams-from-web-apps.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Prasad-MSFT** [comment]
There doesn't seem to be any direct deep link available for 'share to teams' as it exists for navigating to channel and chat.
