### ISSUE TITLE
Teams Bot installed through Global policy is blocked for some users and cannot unblock

### ISSUE THREAD

**Issue by phaniyannam** [MicrosoftDocs/msteams-docs#8394]
Hello, 

We have installed a Bot via manifest file in the Microsoft Teams to all the users in the organization. While most of the users have Bot delivering messages but some users have the Bot conversation/Bot blocked automatically. The messages are delivered to the Teams Bot by our application and receiving the following response to only some users: 
`com.microsoft.bot.connector.rest.ErrorResponseException: Status code 403, {"error":{"code":"ConversationBlockedByUser","message":"User blocked the conversation with the bot."}}`

We have tried to unblock manually by hovering over the Bot in the chat section-> clicking on the ... -> click unblock but no change. Also, tried different ways to unblock the bot on Teams app but does no change. The Bot is installed to all the users with the same policy from the Teams Admin center so we are unsure what the issue might be..

**Comment by sayali-MSFT** [comment]
@phaniyannam - Thanks for reporting your issue.
We will check this at our end and will get back to you.

**Comment by sayali-MSFT** [comment]
@phaniyannam - Could you please check it once only those users who is getting the message, the permission policy set for the particular user is blocking the company communicator user bot. Please update the policy to allow the Company communicator user app and try re-sending the message.

**Comment by phaniyannam** [comment]
@sayali-MSFT 
The bot is set to Allowed for all users. The policies applied to the user who has the bot blocked are the default policies like any other user and has the bot set to allowed. Also observed that one of the user received one message from the Bot but it's blocked now and cannot unblocked it.

**Comment by sayali-MSFT** [comment]
@phaniyannam -Can you try to uninstall the app from particular user teams and add it again.

**Comment by phaniyannam** [comment]
The user does not have the privileges to uninstall and reinstall the app. Do you know of any Teams issues which affect the Bots at scale  ? The number of users in our org can range in between 50-100K users.
