### ISSUE TITLE
Unable to load taskmodule popup in teams bot

### ISSUE THREAD

**Issue by Raveendra123** [MicrosoftDocs/msteams-docs#840]
Hello ,
I am running with issue we are using task module with deep link for upload link in adaptive card .once click that link it will open upload popup in teams bot but it is not opening in web browser teams and desktop teams app.
the below URL used to redirecting on upload link click.
https://teams.microsoft.com/l/task/6132add7-9049-472d-a329-de6290441c00?url=https%3A%2F%2Ficebreaker-y5l22i4ytireq.azurewebsites.net%2FUpload%2FUpload&height=450&width=510&title=Upload&completionBotId=6132add7-9049-472d-a329-de6290441c00

Note : it is working for some of the users but not for all.

can you please help me to get the resolution .Is it issue with users or teams app access related permissions. if you need more details please let me know
Thanks
Raveendra

**Comment by Raveendra123** [comment]
could you please us on mentioned issue. currently we are blocked with the issue really appreciate  it if you provide remedy/resolution earliest.

**Comment by Wajeed-msft** [comment]
Could you please share your App Manifest and Adaptive Card JSON? Also, please try [Task Module](https://github.com/OfficeDev/microsoft-teams-sample-task-module-nodejs/blob/master/TaskModule.zip) sample and let us know if it is working for you.

**Comment by Raveendra123** [comment]
Hello Team,

Apologies for the late reply the issue ha been resolved post correct the
manifest app I'd instead of Appid that leads to resolve the issue.

Thanks & Regards
Raveendra

**Comment by Wajeed-msft** [comment]
Thanks for confirmation. Closing this issue. Please raise a new one if you are facing any issues.
