### ISSUE TITLE
The "Note" callout about "Sites.ReadWrite.All" is random and confusing

### ISSUE THREAD

**Issue by AE-MS** [MicrosoftDocs/msteams-docs#8400]
The "Note" callout about how app users can't give permission to scopes like `Sites.ReadWrite.All` in this doc seems oddly-specific, confusing, and lacking any context. While it is not incorrect, it's not specific to Teams apps so having it appear in generalized documentation about how to configure SSO for a Teams apps feels like it just adds cognitive overhead to an already unfortunately complicated concept. Moreover, there's no context in the documentation for why that is specifically being called out here. Finally, SSO tokens that Teams apps get by calling `getAuthToken` can't have permissions like `Sites.ReadWrite.All` anyway (they'd have to exceute an OBO flow to later get a token with that permission, were it even allowed by the admin)

I think this callout should be removed.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 90fe7a88-a703-1d13-f945-2a15f335721a
* Version Independent ID: 90fe7a88-a703-1d13-f945-2a15f335721a
* Content: [Overview to authentication for tabs using SSO in Teams with Azure AD - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/tab-sso-overview#enhance-user-experience-with-sso)
* Content Source: [msteams-platform/tabs/how-to/authentication/tab-sso-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/tabs/how-to/authentication/tab-sso-overview.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Nivedipa-MSFT** [comment]
@AE-MS - Thanks for reporting your issue. We will check this with engineering team and will get this Note section removed/updated accordingly.

**Comment by Nivedipa-MSFT** [comment]
@surbhigupta12 - Could you please help here to remove the below note from [this ](https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/tab-sso-overview#enhance-user-experience-with-sso:~:text=Note,app%20user%27s%20behalf.)documentation.

![image](https://user-images.githubusercontent.com/92150070/229427384-107b51e9-0542-4e8b-811c-44c04c22bf09.png)
