### ISSUE TITLE
Document "canUpdateConfiguration" for messaging extensions

### ISSUE THREAD

**Issue by aosolis** [MicrosoftDocs/msteams-docs#8401]
There's no documentation on how the settings flow works for messaging extensions
- canUpdateConfiguration
- settings-related invokes
v3 docs had this, but this does not.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7fd5f91c-206f-f03c-d82e-3bf1cc81d13e
* Version Independent ID: d5c2d24a-def4-af2e-7983-c73cf7f22934
* Content: [Message extensions - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/what-are-messaging-extensions?tabs=dotnet)
* Content Source: [msteams-platform/messaging-extensions/what-are-messaging-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/messaging-extensions/what-are-messaging-extensions.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **anclear**

**Comment by Prasad-MSFT** [comment]
@aosolis - Could you please let us know if this is what needs to be added in this doc?
https://learn.microsoft.com/en-us/microsoftteams/platform/resources/messaging-extension-v3/search-extensions#handle-onquerysettingsurl-and-onsettingsupdate-events
