### ISSUE TITLE
IOS adaptative card not rendered

### ISSUE THREAD

**Issue by mayku00** [MicrosoftDocs/msteams-docs#8408]
Hi,

its working fine on macos, but just appear the link in the ios app

`card = {
        "type": "message",
        "attachments": [
            {
                "contentType": "application/vnd.microsoft.card.adaptive",
                "contentUrl": None,
                "content": {
                    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
                    "type": "AdaptiveCard",
                    "version": "1.2",
                    "msTeams": {"width": "full"},
                    "body": [
                        {
                            "type": "TextBlock",
                            "text": f"[Grafana Report Status](grafana-link)\r - item 1\t - item 2"
                        }
                    ]
                }
            }
        ]
    } `

**Comment by Prasad-MSFT** [comment]
@mayku00 - Were you able to resolve your issue? Or are you still looking for any help?
