### ISSUE TITLE
Introduce Teams toolkit entry point from TTK 

### ISSUE THREAD

**Issue by srinidyMSFT** [MicrosoftDocs/msteams-docs#8410]
[Enter feedback here]

<img width="235" alt="image" src="https://user-images.githubusercontent.com/109306502/229209364-738c5940-7ffe-4539-a6b4-d201e70e9842.png">

We are updating TDP in the app section to contain and self-host the Teams toolkit. More about this in this loop component will be published separately as a blog post. https://loop.microsoft.com/p/eyJ1IjoiaHR0cHM6Ly9taWNyb3NvZnQuc2hhcmVwb2ludC5jb20vc2l0ZXMvNDcxODc1MGItMDc2Yi00YTc0LWI0OTAtNTQ2MWVkMjczMDIxP25hdj1jejBsTWtaemFYUmxjeVV5UmpRM01UZzNOVEJpTFRBM05tSXROR0UzTkMxaU5Ea3dMVFUwTmpGbFpESTNNekF5TVNaa1BXSWxNakUwUlVsMlVuSk1OSGxWWlY5S2IzbHJWRE10Umxaell6VlhUbU51Y21rNVIzQjNNWFJpU0hKNmIyRklaWFZXZVc1cWFFbEdVV0pQTkVJdFFsTjVlRlJhSm1ZOU1ERlBTa2hEVkVrelNVSmFXbGhVUWtkSU16VkVTbEV6TnpJM1JrWkpRelZWUVNaalBTVXlSaVpoUFV4dmIzQkJjSEFtY0QwbE5EQm1iSFZwWkhnbE1rWnNiMjl3TFhCaFoyVXRZMjl1ZEdGcGJtVnlKbmc5SlRkQ0pUSXlkeVV5TWlVelFTVXlNbFF3VWxSVlNIaDBZVmRPZVdJelRuWmFibEYxWXpKb2FHTnRWbmRpTW14MVpFTTFhbUl5TVRoWmFVVXdVbFZzTWxWdVNrMU9TR3hXV2xZNVMySXpiSEpXUkUxMFVteGFlbGw2VmxoVWJVNTFZMjFyTlZJelFqTk5XRkpwVTBoS05tSXlSa2xhV0ZaWFpWYzFjV0ZGYkVkVlYwcFFUa1ZKZEZGc1RqVmxSbEpoWmtSQmVGUXdjRWxSTVZKS1RYcFpNVTVHV2t0V1JsSlFWRVpDWVZKRmVGQk5hM1JRVVZaTk1GVnNSbE5PYTAwbE0wUWxNaklsTWtNbE1qSnBKVEl5SlROQkpUSXlZekUzTmpJMFlqZ3RaVGRrT0MwME1EYzJMV0l4TlRNdFlqSTBZVFl5TjJZell6QmtKVEl5SlRkRSJ9?ct=1680289761999&or=Teams-HL

Please let me know if this loop component is sufficent or if you are looking for simplied version to include part of this document. 
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c2ab90ad-0989-85f5-6b10-8ef631252e5c
* Version Independent ID: c2ab90ad-0989-85f5-6b10-8ef631252e5c
* Content: [Manage your apps with the Developer Portal - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/manage-your-apps-in-developer-portal)
* Content Source: [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **surbhigupta**

**Comment by Nivedipa-MSFT** [comment]
This has been picked up with the docs team and updates are done, so closing this issue for now. Please free to reopen if required.
