### ISSUE TITLE
Static Tabs in Teams Apps is loading in web view in IOS instead of mobile view

### ISSUE THREAD

**Issue by Abhiram219** [MicrosoftDocs/msteams-docs#8413]
Hi,

We've created an app in teams with a static tab that loads a webpage. The webpage is mobile responsive. The issue is when we load the app in IOS, the static tab loads the page in web view instead of the mobile responsive view. The same is working fine on Android.

Attaching the screenshots of the experience of both Android and IOS. We are using the latest v1.16 manifest schema.
Also attaching the manifest as well for your refernce.

![Android](https://user-images.githubusercontent.com/60126553/229463594-4b9a0437-6026-404b-a385-0b8ddc942722.jpeg)
![IOS](https://user-images.githubusercontent.com/60126553/229463615-67fc761e-03af-4e59-8406-85979cb3e1d2.png)
[Manifest.zip](https://github.com/MicrosoftDocs/msteams-docs/files/11136633/Manifest.zip)

**Comment by sayali-MSFT** [comment]
@Abhiram219 - Thanks for reporting your issue.
We will check this at our end and will get back to you.

**Comment by sayali-MSFT** [comment]
@Abhiram219 -We are unable to repro the scenario as it showing fine on IOS Device.
Could you please check it once with below manifest?
[Manifest.zip](https://github.com/MicrosoftDocs/msteams-docs/files/11147748/Manifest.zip)


![MicrosoftTeams-image (10)](https://user-images.githubusercontent.com/93527375/229772875-97e5d0b1-af7b-49e5-b3b0-2cea449d6b23.png)
![MicrosoftTeams-image (9)](https://user-images.githubusercontent.com/93527375/229773121-a1f820c6-5bfc-4a3d-b2bf-1fc16b53cb03.png)

We have tried with the given manifest but facing issue.
![MicrosoftTeams-image (11)](https://user-images.githubusercontent.com/93527375/229773746-7de3e159-cec5-49df-8f72-e77b6f0210c2.png)

**Comment by ssgrasshopper** [comment]
Hi Team,

I have the same issue listed above as well. I have done some digging also and found that when the URL changes in the contentUrl the mobile version gets messed up and will display the web version on the mobile app.

Working manifest

            "entityId": "com.snc.sn_now_ms_teams.tab",
            "name": "Employee Center",
            "contentUrl": "https://demosite.service-now.com/esc?id=wsd_search",
            "websiteUrl": "https://demosite.service-now.com/esc?id=wsd_search",

This required me to sign in on the mobile teams application and then the mobile site rendered.

Also the one listed above as a test also worked for me as well.

            "entityId": "com.snc.sn_now_ms_teams.tab",
            "name": "Employee Center",
            "contentUrl": "https://alistapart.com/articles/",
            "websiteUrl": "https://alistapart.com/articles/",


When changing to what is required for SSO to work it renders the desktop version

            "entityId": "com.snc.sn_now_ms_teams.tab",
            "name": "Employee Center",
            "contentUrl": "https://teamsproxy.service-now.com/sn_now_azure_proxy_login.do?tenant={tid}&userPrincipalName={upn}",
            "websiteUrl": "https://demosite.service-now.com/esc?id=wsd_search",

**Comment by sayali-MSFT** [comment]
@ssgrasshopper ,@Abhiram219-We are not able to repro the issue, we have tested with the given manifest but getting below error. Could you please share the working manifest so that we can try it from our end.
![229773746-7de3e159-cec5-49df-8f72-e77b6f0210c2](https://user-images.githubusercontent.com/93527375/233402000-891dc2b8-5b18-4f01-9231-33e32b69b9c3.png)
