### ISSUE TITLE
Schema image needs update

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#8417]
Please remove current image and add new one with just the manifest showcasing applicableLicenseCategories property details. 

![image](https://user-images.githubusercontent.com/31851992/229518766-83c6a6c6-ae6a-4e8c-a105-be10968552bb.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 62dc58bf-69e5-8c4c-90f2-9148ee03b30f
* Version Independent ID: 62dc58bf-69e5-8c4c-90f2-9148ee03b30f
* Content: [Video filters for meeting apps - Teams](https://review.learn.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/video-filters-for-meeting-apps?branch=pr-en-us-6618&tabs=meeting-lobby-experience)
* Content Source: [msteams-platform/apps-in-teams-meetings/video-filters-for-meeting-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/apps-in-teams-meetings/video-filters-for-meeting-apps.md)
* Service: **msteams**
* GitHub Login: @v-ypalikila
* Microsoft Alias: **v-ypalikila**

**Comment by Nivedipa-MSFT** [comment]
@Wajeed-msft - Thanks for reporting your issue. We will update the image accordingly.

**Comment by Nivedipa-MSFT** [comment]
@Wajeed-msft - Could you please confirm should we update the below image here:

![image](https://user-images.githubusercontent.com/92150070/229712225-17123f6d-a867-435f-b499-0d8968d01675.png)

**Comment by v-ypalikila** [comment]
Hi @Nivedipa-MSFT,

We have updated the image to show only `applicableLicenseCategories` property details. Request you to review and approve the changes.

Sharing the review site link: https://review.learn.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/video-filters-for-meeting-apps?branch=pr-en-us-6618&tabs=meeting-lobby-experience#validate-your-app-package.

Screenshot:
![image](https://user-images.githubusercontent.com/93579821/229758892-437a8304-95ea-4dfa-81ac-69e88b4dd62e.png)


Thank you,
Yash

**Comment by Namitha-23** [comment]
The issue has been linked to PR https://github.com/MicrosoftDocs/msteams-docs/pull/6618.
