### ISSUE TITLE
[Doc-Bug] OnTeamsMessageEditAsync is not supported in Group chat and teams channel scope

### ISSUE THREAD

**Issue by SubbaReddi** [MicrosoftDocs/msteams-docs#8418]
Hi Team,
I see OnTeamsMessageEditAsync is working fine in 1:1 chat with bot. But not working in group chat and teams channel scope. 
**It is not supported the specific event in group chat and in teams channel scope**, So, please add note in the documentation for the same.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: afbc5b84-5be5-b5c4-30c0-58782a748a03
* Version Independent ID: ef6b8aee-52e7-f5d4-7dfa-8f34a1698330
* Content: [Messages in bot conversations - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-messages?tabs=dotnet1%2Cdotnet2%2Cdotnet3%2Cdotnet4%2Cdotnet5%2Cdotnet#update-message)
* Content Source: [msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/bots/how-to/conversations/conversation-messages.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **anclear**

**Comment by Prasad-MSFT** [comment]
Thanks @SubbaReddi  for raising this. We will check it once from our end and will redirect to doc team accordingly.

**Comment by Prasad-MSFT** [comment]
Hi @SubbaReddi - We also checked at our end and noticed that, OnTeamsMessageEditAsync , OnTeamsMessageSoftDeleteAsync ,  OnTeamsMessageUndeleteAsync is working fine in 1:1 chat with bot. But not working in group chat and teams channel scope.
