### ISSUE TITLE
suggestedDisplayName or suggestedTabName 

### ISSUE THREAD

**Issue by icelandgrecian** [MicrosoftDocs/msteams-docs#842]
The sample JavaScript uses the parameter suggestedDisplayName, but the text describing the parameters has suggestedTabName. Can you clarify what is the correct? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ffb7ac07-169d-860d-d566-e69540df600d
* Version Independent ID: 7863d671-52d9-83e3-7fcc-4eed0f3a62f9
* Content: [Create a configuration page for your tab - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/tabs/tabs-configuration)
* Content Source: [msteams-platform/concepts/tabs/tabs-configuration.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/tabs/tabs-configuration.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Gousia-MSFT** [comment]
@icelandgrecian suggestedDisplayName is the right one. @clearab Could you please help update the documentation here?
