### ISSUE TITLE
Does Tap activity for bot notification supports navigation?

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#8425]
> When the user taps on the notification, the deep link navigates to the tab so that the user can view more details about the activity.

By default, alert triggered by Bots take user to the conversation tab. Please check if it supports deep link navigation scenario.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 45541337-ecd7-5cf6-cbe4-3f0d2f39aa79
* Version Independent ID: 6b4203f0-2844-06c9-eaa3-9cc03e6f76c0
* Content: [Deep links overview - Teams](https://review.learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links?branch=pr-en-us-7913)
* Content Source: [msteams-platform/concepts/build-and-test/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/build-and-test/deep-links.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Meghana-MSFT** [comment]
Thank you for reporting this issue, we will check this and get back to you.

**Comment by Meghana-MSFT** [comment]
@surbhigupta12 - Could you please help to update the following sentence 

> [When the user taps on the notification, the deep link navigates to the tab so that the user can view more details about the activity](https://review.learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links?branch=pr-en-us-7913#:~:text=When%20the%20user%20taps%20on%20the%20notification%2C%20the%20deep%20link%20navigates%20to%20the%20tab%20so%20that%20the%20user%20can%20view%20more%20details%20about%20the%20activity).

 as below -

> When the user taps on the action on adaptive sent by bot, the deep link navigates to the tab so that the user can view more details about the activity.
