### ISSUE TITLE
Privacy Policy and Terms of Use

### ISSUE THREAD

**Issue by icelandgrecian** [MicrosoftDocs/msteams-docs#843]
Is there any thought on making the privacyUrl and termsOfUseUrl translatable as well... we would like to provide these pages in multiple languages and would be nice if we could do this via the manifest file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a8d718e-46c9-d26b-0483-635832903842
* Version Independent ID: 32be5df3-2749-3854-fa01-a03e72e96696
* Content: [Localization file JSON schema reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/localization-schema)
* Content Source: [msteams-platform/resources/schema/localization-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/resources/schema/localization-schema.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by akinolugbade** [comment]
This is a good suggestion. We will consider it during the next rev of our manifest.
