### ISSUE TITLE
Convert docs from ADAL to MSAL

### ISSUE THREAD

**Issue by liiamjones** [MicrosoftDocs/msteams-docs#844]
Hi could the following document be updated from ADAL.js to MSAL.js given it's out of support. 
msteams-platform/concepts/authentication/auth-silent-AAD.md
I've been pointed in the direction of MSAL from this [issue ](https://github.com/AzureAD/azure-activedirectory-library-for-js/issues/659) to use npm with React. ADAL only provided guidance on Angular and neglected the core components on any other framework.

**Comment by billbliss** [comment]
The MSAL.js library does not allow it to be used inside an <iframe> which is why we haven't switched. We are working with the MSAL team to fix this and once it works, we will update our samples.

**Comment by liiamjones** [comment]
But the existing ADAL stuff isn’t in an iframe? That’s the point of teams.js it pops it to a new window with teams context

**Comment by liiamjones** [comment]
Sorry just remembered we’re talking about silent auth. Yep understand now. Cheers

**Comment by liiamjones** [comment]
If you’ve closed this issue can I have a link to the relevant Issue with MSAL so I can track its progress please

**Comment by simoneTheNewBlack** [comment]
hi there, 

just wonder if there is any update for the MSAL auth in Teams?
