### ISSUE TITLE
Why not just delete this page until something changes?

### ISSUE THREAD

**Issue by tinsheep** [MicrosoftDocs/msteams-docs#8458]
This page introduces confusion in my view. We have the base guidance here for meeting apps - https://learn.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/design/designing-apps-in-meetings#spacing  
This page says it applies to all tabs including meeting apps.
Is what was going to happen already complete and there were additional margins in addition to the above/current reference?
Will the 20px margins cited above be removed at some point in the future still and this is a heads-up that has taken several months longer than expected?

Thanks for the clarification. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c9e1dcae-86bf-3546-de37-f746f60ddf63
* Version Independent ID: 2a11fb54-d08d-2e06-14cc-ab3e9a4edaeb
* Content: [Tab margin changes - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/resources/removing-tab-margins)
* Content Source: [msteams-platform/resources/removing-tab-margins.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/resources/removing-tab-margins.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lomeybur**

**Comment by Prasad-MSFT** [comment]
@tinsheep - Thanks for raising your concern. We will check this with engineering team and will update accordingly.
