### ISSUE TITLE
How to get the current user email when the user tags the @bot in a teams conversation?

### ISSUE THREAD

**Issue by basxib** [MicrosoftDocs/msteams-docs#846]
We’re trying to build a Microsoft Teams compose extension so that our Teams users can reference tasks from projects on a third party task management platform.
We need to get the current user email on teams, but we couldn't find any references on how to do that.
We're using Bot Builder SDK V4 for NodeJS (Typescript)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 896e3726-f7fb-8fbd-925d-bb149d6169f2
* Version Independent ID: cea27271-72f4-4832-3d7d-74ff2598913e
* Content: [Develop messaging extensions - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/messaging-extensions/messaging-extensions-overview)
* Content Source: [msteams-platform/concepts/messaging-extensions/messaging-extensions-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/messaging-extensions/messaging-extensions-overview.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Wajeed-msft** [comment]
You can get the email Id by [fetching the team roaster](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/bots/bots-context#fetching-the-team-roster). This documentation has code for SDK v3, please take a look at the samples present on [GitHub for beta SDK v4](https://github.com/OfficeDev/BotBuilder-MicrosoftTeams-node/blob/master/samples/teams-bot/src/bot.ts#L64).

**Comment by Gousia-MSFT** [comment]
Please reopen if you are still facing any issues.
