### ISSUE TITLE
Deep link issue in IOS

### ISSUE THREAD

**Issue by sudoaccessdenied** [MicrosoftDocs/msteams-docs#8469]
[Enter feedback here]

User  unable to  open deep link to personal tab in iOS.
 It is working fine in android and windows.
Here is the error:
![image](https://user-images.githubusercontent.com/30634773/231479872-9f005066-f44b-47ad-9531-e07136be58be.png)

here is the deep link https://teams.microsoft.com/l/entity/d3d1be68-066c-4967-a74b-9edcf902dcfb/teamsDashboard?context=%7B%22subEntityId%22:%22SourceData-,redirected-from=%3EAD_FB_PROSPECTS_Nordics_PLG-Funnel_M365-Interests_Stressed-Employee%22%7D
OS:  iOS 16.2
Teams Version: 5.5.0

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 45541337-ecd7-5cf6-cbe4-3f0d2f39aa79
* Version Independent ID: 6b4203f0-2844-06c9-eaa3-9cc03e6f76c0
* Content: [Deep links overview - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links)
* Content Source: [msteams-platform/concepts/build-and-test/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/build-and-test/deep-links.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by sayali-MSFT** [comment]
@sudoaccessdenied -Thanks for reporting your issue.
We will check this at our end and will get back to you.
