### ISSUE TITLE
Anyone can mention the users in team

### ISSUE THREAD

**Issue by daljeet-singh** [MicrosoftDocs/msteams-docs#847]
BUG: I am currently able to tag any user from the world to my teams chat

<img width="486" alt="Screen Shot 2019-07-30 at 5 25 49 PM" src="https://user-images.githubusercontent.com/2284163/62167309-ed060280-b2f0-11e9-90ce-2d5b0b89242e.png">
<img width="498" alt="Screen Shot 2019-07-30 at 5 26 08 PM" src="https://user-images.githubusercontent.com/2284163/62167310-ed060280-b2f0-11e9-82b8-9e38aa3bd686.png">

**Comment by ShawnC7208** [comment]
I am seeing this as well, jumped on here to add the exact same thing:
![image](https://user-images.githubusercontent.com/8285110/62167979-0b1c3480-b2ea-11e9-8852-a190b8a10dcf.png)

**Comment by billbliss** [comment]
This is a service issue which we are investigating now. Thanks for reporting it.

**Comment by daljeet-singh** [comment]
Thanks, @billbliss is there any bounty for reporting bugs for the platform?

**Comment by billbliss** [comment]
This was mitigated a few hours after this was reported, working fine now.
