### ISSUE TITLE
Interactive bot setup process broken in sbs-gs-notificationbot.yml

### ISSUE THREAD

**Issue by oxwilder** [MicrosoftDocs/msteams-docs#8470]
Process goes well through step 15, but as soon as I attempt to run debugger I get the following message in the console:
```(1/5) Registering the AAD app which is required to create the bot ...

Summary:

× AadCreateAppError: Failed to create an app in Azure Active Directory.

Visit https://aka.ms/teamsfx-debug-set-up-bot-task to learn more about 'Set up bot' task.

[2023-04-12T13:33:58.803Z] [Error] - code:Ext.SetUpBotError, message: Set up bot task failed. Please check the output panel to see the details.
```

Following the steps outlined in https://github.com/OfficeDev/TeamsFx/issues/7184 eventually led to creation of an app (I guess) and a bot (maybe?) but no telling how to proceed from there.

**Comment by Nivedipa-MSFT** [comment]
@oxwilder - Thanks for reporting your issue. We will check and update you soon.

**Comment by Nivedipa-MSFT** [comment]
@oxwilder - Could you please share the document or steps to test at our end?
