### ISSUE TITLE
Troubleshooting - work/school tenant Auth with CA browser policy preventing auth of custom Teams app

### ISSUE THREAD

**Issue by AlexSapple** [MicrosoftDocs/msteams-docs#8476]
Hi guys, 

any chance you can document the browser details that Teams uses for hosting custom apps - I can get the user agent string but I don't know if this will be helpful enough for my use case. 

I've got a customer who has a CA policy that restricts browsers (I don't know the exact details of that policy) only that trying to auth my custom app, the user is presented with a (I think) 53001 and a message about incompatible browsers

![image](https://user-images.githubusercontent.com/30351641/231732183-4d031a32-c525-4834-bfca-bd29be80050f.png)
(note that in this case, the user account is indeed an appropriate work account domain user)

so I guess I'm looking for details of the browser in play but also potentially how these sorts of things should be managed going forward since I suppose it's at the mercy of you guys when the browser engine is updated in Teams.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fb80c6db-320c-52b6-f8c4-fad9d146cb24
* Version Independent ID: 37248d85-8023-dd61-e77b-d8571b8d792e
* Content: [Troubleshoot your app - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/resources/troubleshoot)
* Content Source: [msteams-platform/resources/troubleshoot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/resources/troubleshoot.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Nivedipa-MSFT** [comment]
@AlexSapple - Thanks for reporting your issue. We will check and update the document accordingly.

**Comment by Nivedipa-MSFT** [comment]
@AlexSapple - Conditional Access policy requires a domain joined device, and if the device isn't domain joined then it gives a 53001 error. Have the customer use a domain joined device?

**Comment by AlexSapple** [comment]
thanks @Nivedipa-MSFT - let me confirm that. I may have misunderstood the issue. I was focusing on the part of the error message relating to browser compatibility, but if this is device specific then there is probably no issue and no action needed. I know the user was logging in under the valid domain account - but I will have to confirm device.

**Comment by AlexSapple** [comment]
@Nivedipa-MSFT - my customer seems to have resolved this at their end - which makes it look exactly as you suggested that the device was not domain joined. I will close this ticket now. thanks very much.

**Comment by Nivedipa-MSFT** [comment]
@AlexSapple - Could you please share your valuable feedback via [Microsoft Teams Developer Feedback](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR7iCOpS5_b9Nqmwx43u5rtZUOThVR081SllSR05aSDQxQ0tUMDVPTVIxTi4u) link.
