### ISSUE TITLE
Does the sample code work in Azure DevOps?

### ISSUE THREAD

**Issue by Orso95587018** [MicrosoftDocs/msteams-docs#848]
Can I pull the Git repository from a project in &lt;myusername&gt;.visualstudio.com (Azure DevOps website) and build it from there?

I tried building the project (Build button) and it gave an error about not being able to convert the OriginUrl.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98cd21c7-e87c-3c5b-7574-998a355f9f08
* Version Independent ID: 5e312707-facc-03fc-af59-90267d0c7b8a
* Content: [Get started with C#/.NET - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/get-started/get-started-dotnet-app-studio#feedback)
* Content Source: [msteams-platform/get-started/get-started-dotnet-app-studio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/get-started/get-started-dotnet-app-studio.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Trinetra-MSFT** [comment]
Referring to this #[issue](https://github.com/dotnet/sourcelink/issues/166).
