### ISSUE TITLE
How to add to a team?

### ISSUE THREAD

**Issue by onknight05** [MicrosoftDocs/msteams-docs#8485]
Hi, I'm trying to follow the docs **Hello World with Node.js**, but when adding an app to a team, the save button was disabled. Could anyone let me know what is my mistake or any hint to debug this issue? Thanks!

![image](https://user-images.githubusercontent.com/69107918/232393852-4431a7de-ee9c-4d22-8ba2-bb2a073510dd.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b1321426-bc5d-1b04-bcf6-5b6ae6100673
* Version Independent ID: b1321426-bc5d-1b04-bcf6-5b6ae6100673
* Content: [Hello World with Node.js - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/sbs-gs-nodejs?tutorial-step=4)
* Content Source: [msteams-platform/sbs-gs-nodejs.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/sbs-gs-nodejs.yml)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Nivedipa-MSFT** [comment]
@onknight05 - Thanks for reporting your issue. We will check and update you soon.

**Comment by ChetanSharma-msft** [comment]
Hello @onknight05 - This is a basic sample which just shows basic functionality.
If you want to add Save functionality, please refer this code: https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/main/samples/app-complete-sample/nodejs/server/views/configure.ejs#L21

Reference documentation:

**Comment by onknight05** [comment]
Hi @ChetanSharma-msft, thanks for your help! I could solve my problem. We can close this issue.

**Comment by Nivedipa-MSFT** [comment]
@onknight05 - Could you please share your valuable feedback via [Microsoft Teams Developer Feedback](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR7iCOpS5_b9Nqmwx43u5rtZUOThVR081SllSR05aSDQxQ0tUMDVPTVIxTi4u) link.
