### ISSUE TITLE
Context Different in Mobile Tabs

### ISSUE THREAD

**Issue by icelandgrecian** [MicrosoftDocs/msteams-docs#849]
We've started looking into the mobile (personal) tabs that are in developer preview in the mobile client and we are noticing a difference between what is provided in the context on the mobile device and what is provided on the desktop client.

In an example we have got (an educational user), the following properties are available in the context in the desktop client, but for the same user are missing on the mobile tab:

licenseType
tenantSKU
teamSiteDomain
ringId
loginHint

On the desktop userPrincipalName is set, but is blank in the mobile client

And on the mobile client there is an additional userTeamRole property we don't see on the desktop client.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 525acdf7-3f72-b657-63ea-ddb95c4fb247
* Version Independent ID: c5d9575a-ace3-8441-4516-ad2c7adb3d99
* Content: [Get context for your tab - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/tabs/tabs-context)
* Content Source: [msteams-platform/concepts/tabs/tabs-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/tabs/tabs-context.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Gousia-MSFT** [comment]
@icelandgrecian Thanks for reaching out. This is a known issue. We have a bug for this. We are working on it.
