### ISSUE TITLE
Get the teams-userId to initiate a conversation with a bot

### ISSUE THREAD

**Issue by mr-flannery** [MicrosoftDocs/msteams-docs#8516]
This question is similar to https://github.com/MicrosoftDocs/msteams-docs/issues/2360, but the answers provided there did not help me.

I have a use case where I want my Teams Bot to initiate a conversation with a user with whom the bot may have never had any contact before. I already tried to get the user's ID via Graph, but this returns a UUID, which is not what the `/v3/conversations` endpoint seems to expect.

I also checked this page in the docs: https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/send-proactive-messages?tabs=dotnet#get-the-user-id-team-id-or-channel-id

However, we're currently not using the bot SDK, but only the REST API (for reasons), i.e. non of the methods listed there works for us. And I could not find any documentation on an API where I can get the user's ID for Teams based on their email address.

**Comment by Meghana-MSFT** [comment]
We tried this and we were able to send message from bot - https://learn.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bot-conversations/bots-conv-proactive?tabs=csharp#examples.

Could you please try getting member id using turnContext.Activity.From.Id.

**Comment by mr-flannery** [comment]
Hi @Meghana-MSFT,

thanks for the reponse! Unfortunately, I don't see how this helps me. I forgot to mention it in my initial description, but we're using the `botbuilder` package for Node.js, which I understand to be sdk v4. The docs you linked refer to the legacy v3.

Either way, I'm confused. The examples on the page you linked either assume a channel ID (which we don't have) or that the user ID is already known, but this is exactly our problem – we don't know the user ID.

Here are the things we know:
- the bot is installed to the Teams tenant
- a user exists in that tenant whose mail we know

And that's all.

**Comment by Meghana-MSFT** [comment]
Apologies for the delay, We can use only the id and not email. We will still check internally and get back to you. Thank you for your understanding.

**Comment by Meghana-MSFT** [comment]
Currently there is no feature to allow bot to create a new conversation with user using user's AAD object id. We will keep you posted if this feature becomes available in future. Thank you!

**Comment by mr-flannery** [comment]
Thanks for checking!
