### ISSUE TITLE
Example shows how to add a personal tab and not a channel tab

### ISSUE THREAD

**Issue by mercer2000** [MicrosoftDocs/msteams-docs#8518]
The Blazor code on the Create Channel Tab page shows how to create a Personal Tab and not a Channel Tab.

For the Blazor sample, 

Configure App features 
Set Configuration URL to http://localhost:3007/config   // This is the endpoint to the blazor app that renders the config page. 

The file Page/TabConfig.razor renders the configuration content when the tab is added to a team. After the user adds the app to the team, the config app dialog will be shown. Next, after the user presses Save shown on the config dialog, the tab app will be added and the new channel tab shown.  

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 671f4d1e-2092-1633-cec9-db8deeb0cd79
* Version Independent ID: ee36a237-40e1-cf4e-ebde-229c06854171
* Content: [Create a channel tab or group tab - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?tabs=vs&pivots=blazor-app)
* Content Source: [msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/tabs/how-to/create-channel-group-tab.md)
* Service: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by sayali-MSFT** [comment]
@mercer2000 - Thanks for reporting your issue.
We will check this at our end and will get back to you.

**Comment by sayali-MSFT** [comment]
@surbhigupta12 -Could you please help us to update the document-
In Build and run your first Teams tab app section replace the 5,6 and 8 option-

5.Select **Add to a Teams** when prompted to install the app to Teams.
![Add_Team](https://user-images.githubusercontent.com/93527375/233942763-a42fc488-a25a-4c03-989c-1d00935779f2.png)
Congratulations, your first tab app is running in your local environment!
![channel](https://user-images.githubusercontent.com/93527375/233942880-de3916c8-ae9d-4505-93ce-1afc6d2b1567.png)

6.Move through the page to view the user details.
![AuthButton](https://user-images.githubusercontent.com/93527375/233943149-7bb57ed4-63c8-4d74-bd5e-fbb928066586.png)

8.Select Accept to let your app access user details.

Your photograph and details appear in your **Channel Tab**.
![Final1](https://user-images.githubusercontent.com/93527375/233944738-c4c68514-18c0-4836-9ab6-282957dbe2c3.png)

**In 8th option just replace first 2 lines and image only.**


Document-https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?tabs=vs&pivots=blazor-app#build-and-run-your-first-teams-tab-app
