### ISSUE TITLE
Multitenant message indicator shows read message as unread in other tenant

### ISSUE THREAD

**Issue by TeamStriebigSebastian** [MicrosoftDocs/msteams-docs#853]
Hi I am working for two companies, we use both Teams.
I am logged into company A
When I get a message in the other company B. 
A small one in a red circle appears at the name of the other company on the upper right area of teams.
Great!
 I go there (Company B) and read the message, then I go back to the other company. (Company A)
But the message indicator still shows this message. Even if it is already read.

Please fix. Thx

**Comment by Gousia-MSFT** [comment]
@TeamStriebigSebastian Thanks for reporting this. We are looking into it.

**Comment by Gousia-MSFT** [comment]
@TeamStriebigSebastian This is a known limitation. Cross-tenant pill count is currently updated every 15 minutes. We are working on improving this experience. Could you please check if it updates within 15 mins or takes more than that?

**Comment by TeamStriebigSebastian** [comment]
Lol, it pops up when I log in in the morning and switch to a guest tenant.
Then it shows me that my home tenant has a message for me, I switch back no
message.

So no the 15 minutes thing is not working.
Better built a non-time bound process in a real-time messaging system...

**Comment by Gousia-MSFT** [comment]
This is an unfortunate design gap on how the service works today. We're planning to sunset this service (for this and a variety of other reasons) and move to a new service but we do not have a firm timeline to share.
