### ISSUE TITLE
MS Teams API Rate limit applies falsly on BotFramework Card collections

### ISSUE THREAD

**Issue by DavidVollmers** [MicrosoftDocs/msteams-docs#854]
When sending a large card collection to MS Teams from our Bot, we receive one of the following responses:

400 Bad Request: If the layout of the card collection is `carousel`
429 Too Many Requests: If the layout of the card collection is `list`

In the latter case MS Teams will display 4 Cards and then throw the error. When using `carousel` you only get the error.

This behaviour seems to be connected to the MS Teams API Rate limit described here: https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/bots/rate-limit

Since the same card collections are displayed correctly in every other channel but not in MS Teams I recommend to overthink these Rate limits for Bots. The current behaviour is really frustating to develope against.

I am sending the card collection via `ITurnContext.SendActivityAsync` so the problem might also be solvable in the BotFramework repository...

**Comment by clearab** [comment]
Yes, this is happening because of rate limiting. Carousel is your best bet, as you should be able to use up to 10 cards. We're looking at ways to potentially increase the limits or alter the behavior in the future.

**Comment by gmajian** [comment]
@clearab, what's the rate limit of list of cards?  Are the list of cards be treated as multiple operations regarding the MS Teams API Rate limit?

**Comment by dgancho** [comment]
Are these rate limits documented anywhere?
