### ISSUE TITLE
Can't promisify startReplyChain

### ISSUE THREAD

**Issue by praveendath92** [MicrosoftDocs/msteams-docs#855]
This doesn't works
```typescript        
const startReplyChain = promisify(botSdk.teamsConnector.startReplyChain);
        
// Start a reply chain
 const responsePromise = startReplyChain(team.serviceUrl, channelId, message)
       .then(async (address) => {
            // do something 
        });
```

This works

```typescript
botSdk.teamsConnector.startReplyChain(team.serviceUrl, channelId, message, (error, address) => {
            // do something 
        });
```

**Comment by Gousia-MSFT** [comment]
@praveendath92 Thanks for reporting this. It looks like an issue with the SDK. We are looking into it.

**Comment by robin-liao** [comment]
for the callback function, the first argument is `error`, followed by `address`. However, in the original post the promisify usage seems bind the first argument as address. Please check if it's because of this reason. Thanks!

**Comment by praveendath92** [comment]
I'm only using the `then` clause on the promise - which is expected to deliver only when the promises finishes without an error.

The error will be deliver in the `catch` clause (which I don't use in my example). This is another nice advantage of promisifying things - success and error paths can be seperated nicely
