### ISSUE TITLE
Remove section about talking to a bot directly by ID

### ISSUE THREAD

**Issue by aosolis** [MicrosoftDocs/msteams-docs#856]
Starting a chat with a bot directly by ID is no longer supported, and leads to issues with app policies. Please remove this section, and any references to it.
https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/bots/bots-test#talk-to-your-bot-directly-by-id

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac99cf82-194d-eb31-2d29-7368ba895edc
* Version Independent ID: aab61691-1db4-8580-53be-d4665c96e5be
* Content: [Test and debug your bot - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/bots/bots-test#talk-to-your-bot-directly-by-id)
* Content Source: [msteams-platform/concepts/bots/bots-test.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/bots/bots-test.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by SidU** [comment]
Also need to account for the deeplinks on Bot Framework portal to create a chat with bot. 

Example:
https://teams.microsoft.com/l/chat/0/0?users=28:<bot_id_here>

**Comment by clearab** [comment]
Updated doc to emphasize that this method is for testing purposes. Will leave this open while we work through the other changes discussed.

**Comment by v-chetsh** [comment]
@clearab - Shall we close the issue if doc is already updated?

**Comment by ChetanSharma-msft** [comment]
Hello @clearab - Could you please share the updates on this issue?

**Comment by Nivedipa-MSFT** [comment]
@clearab - Could you please share any updates on this issue?

**Comment by clearab** [comment]
I'm not on this team anymore, and this Issue isn't assigned to me.

**Comment by ChetanSharma-msft** [comment]
Hello @surbhigupta12 - Could you please look into this issue once?
