### ISSUE TITLE
Background-color of .image-container is set as undefined instead of accentColor value

### ISSUE THREAD

**Issue by Leks12lk** [MicrosoftDocs/msteams-docs#857]
The standard header for a card returned by ME does not contain background color for icon placed in sideload. The background color value for image-container is set to undefined instead of accentColor property placed in manifest.json file.

![image](https://user-images.githubusercontent.com/13051974/62378836-5c2c6280-b54e-11e9-8e01-c02f2abd98f8.png)

**Comment by Trinetra-MSFT** [comment]
Could you please share your manifest.json file?

**Comment by Leks12lk** [comment]
> Could you please share your manifest.json file?

Hi,
Please find manifest.json in attached zip. 

[manifest.zip](https://github.com/MicrosoftDocs/msteams-docs/files/3468468/manifest.zip)

**Comment by Trinetra-MSFT** [comment]
Hi @Leks12lk ,
We side loaded your app manifest in Teams, it seems accent color from manifest is rendering properly. Could you please try to side load your app again in teams? Please let me know if you still facing this issue.

![image](https://user-images.githubusercontent.com/50989436/62572193-c7f52f00-b8b0-11e9-8dbc-8f652a5b884d.png)

**Comment by VKAlwaysWin** [comment]
Hi @Trinetra-MSFT I think it is a bit different issue.
Could you please try to do the same with Messaging Extension? In case if you post card (for example adaptive card) from ME to channel (like General) you will be able to see issue mentioned by @Leks12lk .

FYI, before posting card into a channel it has background-color:
![image](https://user-images.githubusercontent.com/14337164/62575684-f8829c00-b8a3-11e9-97f3-f459aabbfcac.png)

But after posting card it looks like that:
![image](https://user-images.githubusercontent.com/14337164/62575733-1b14b500-b8a4-11e9-9872-7dbce1a6da4a.png)

**Comment by Leks12lk** [comment]
Hi @Trinetra-MSFT 
Yes, I'm still facing the problem. Steps to reproduce are correct in a comment above by @VKAlwaysWin

**Comment by VKAlwaysWin** [comment]
Maybe this can be helpful: https://www.youtube.com/watch?v=8q-XeBgXexA link to a video with a bug. Plus my manifest with images.
[TestApp.zip](https://github.com/MicrosoftDocs/msteams-docs/files/3476157/TestApp.zip)

**Comment by Trinetra-MSFT** [comment]
Thanks for reporting this. We are looking into it.

**Comment by Gousia-MSFT** [comment]
@Leks12lk @VKAlwaysWin We have raised a bug on this. This is being tracked internally.
