### ISSUE TITLE
Sample uses old Bot Framework version

### ISSUE THREAD

**Issue by mscaitlina** [MicrosoftDocs/msteams-docs#858]
I wanted to build a Teams app and started with this sample. However, as I tried to understand the code for the Bot and modify it for my scenario, I got confused. It turns out this sample uses v3 of the Bot Framework, but the Bot Framework documentation on their site is for v4. This made it hard to know what the code from this sample does, and how to modify it to achieve what I was trying to do. I gave up.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33cdb816-f2b6-31a4-0e4c-d730435d0a6b
* Version Independent ID: c111eaef-ac66-e245-b2bc-623c1801a7db
* Content: [Get started with App Studio and Node.js - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/get-started/get-started-nodejs-app-studio?view=msteams-client-js-latest)
* Content Source: [msteams-platform/get-started/get-started-nodejs-app-studio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/get-started/get-started-nodejs-app-studio.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by clearab** [comment]
Hi - yes, it is a bit confusing right now. We're planning on full support for v4 soon. In the interim, you can use the Teams bot documentation (https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/bots/bots-overview), and the Bot Framework documentation can also be changed to v3 using the option on the top-left of their documentation repository:

![image](https://user-images.githubusercontent.com/1139814/62395158-4dc95100-b524-11e9-95e8-ce9bbf786210.png)

If you have specific questions that you can't find the answer to please feel free to reach out to us using one of the methods outlined [here](https://docs.microsoft.com/en-us/microsoftteams/platform/feedback) and we'll be happy to help.
