### ISSUE TITLE
registerOnRemoveHandler cannot be called from Config/Settings page or iframeContext

### ISSUE THREAD

**Issue by miketeix** [MicrosoftDocs/msteams-docs#859]
The registerOnRemoveHandler cannot be called from Config/Settings page or iframeContext, I get an error when I try to do so.

I've created a second page for the removal experience where I call registerOnRemoveHandler (basically a call to our backend to clean up), and register the url for that page when I call setSettings - though, the app doesn't redirect there, so what's the point of the `removeUrl` anyhow?

Any help is much appreciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c21a27c1-d01a-6cc7-c991-73af6492aad8
* Version Independent ID: b15d2142-df29-250e-9a0a-b734dcb93162
* Content: [Office 365 Connectors - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/connectors/connectors-creating#feedback)
* Content Source: [msteams-platform/concepts/connectors/connectors-creating.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/connectors/connectors-creating.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Wajeed-msft** [comment]
`removeUrl` is used for Tab removal experience. For Connectros `removeUrl` is not used. Please take a look at [Integrating the configuration experience](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/connectors/connectors-creating#integrating-the-configuration-experience).

For Connectors, Register a `microsoftTeams.settings.registerOnRemoveHandler()` event handler, which gets called when the user removes your connector. Please take a look at [sample Connector code](https://github.com/OfficeDev/microsoft-teams-sample-connector-csharp/blob/master/TeamsToDoAppConnector/Views/Connector/Setup.cshtml#L65) for the same. You can quickly try this using [Connector App manifest](https://github.com/OfficeDev/microsoft-teams-sample-connector-csharp/blob/master/TeamsToDoAppConnector/TeamsAppPackages/manifest-CShar.zip) to check if event is getting fired for you or not.

If you are still facing issue, please share code snippet of what you are trying.
