### ISSUE TITLE
Teams Webhooks with markdown don't work

### ISSUE THREAD

**Issue by danygold** [MicrosoftDocs/msteams-docs#8591]
Hello,

Adaptive cards that contain markdown are not correctly rendered by Microsoft Teams.

In particular, the problem is with the following tags
- Headings (level 1 through 6): ```# Heading through ###### Heading```
- Strike-through: ```~~This text is struck through~~```

Example JSON:
```
{
    "type": "message",
    "summary": "summary",
    "attachments": [
        {
            "contentType": "application/vnd.microsoft.card.adaptive",
            "contentUrl": null,
            "content": {
                "type": "AdaptiveCard",
                "body": [
                    {
                        "type": "TextBlock",
                        "text": "# Heading (not work)\n- list 1\n  - list 1.1\n- *Italics*\n- **Bold**\n- ***Bold + Italics***\n- ~~Strike-through~~ (not work)\n- [Microsoft](http://www.microsoft.com)\n- `inline code` (not work)"
                    }
                ],
                "msteams": {
                    "width": "Full"
                },
                "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
                "version": "1.3"
            }
        }
    ]
}
``` 
Teams output:

![image](https://github.com/MicrosoftDocs/msteams-docs/assets/28807243/a9b3476d-36fe-4387-b5db-ec559dc41f28)

Expected result ([Adaptive cards designer](https://adaptivecards.io/designer/)):

![image](https://github.com/MicrosoftDocs/msteams-docs/assets/28807243/ea2d484f-e574-4216-8f5a-35e4e85cdaac)

**Comment by ChetanSharma-msft** [comment]
Hello @danygold - Thanks for raising your query.
We will look into it and let you know the updates.

**Comment by Meghana-MSFT** [comment]
@danygold -  ~~Strike-through~~, #Heading,  `inline code` are not supported in Adaptive card. 

Please find the list of [markdown supported in adaptive cards](https://learn.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?tabs=adaptive-md%2Cdesktop%2Cconnector-html#format-cards-with-markdown:~:text=The%20following%20table%20provides%20the%20supported%20styles%20for%20Textblock%2C%20Fact.Title%2C%20and%20Fact.Value%3A).
