### ISSUE TITLE
Hani hassan

### ISSUE THREAD

**Issue by hassanhani-44** [MicrosoftDocs/msteams-docs#8593]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dac10c25-1625-4f0d-b113-a1fdd7a7a900
* Version Independent ID: dac10c25-1625-4f0d-b113-a1fdd7a7a900
* Content: [Get started - Overview - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/get-started/get-started-overview)
* Content Source: [msteams-platform/get-started/get-started-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/get-started/get-started-overview.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Meghana-MSFT** [comment]
@hassanhani-44 - Could you please share more details about your issue?

**Comment by ChetanSharma-msft** [comment]
This looks like an invalid issue.
We are closing this issue for now, please feel free to reopen it, if required.
