### ISSUE TITLE
Navigating to a different team collapses the previous team if it has one channel

### ISSUE THREAD

**Issue by dfjones1981** [MicrosoftDocs/msteams-docs#860]
If I am a member of many teams, some with more than one channel and some with just a single "General" channel, I observe the following behaviour.

Clicking on a channel in a team with many channels and then clicking on channel in a different team that also has many channels, both teams remain open and I can see all the channels from each team.

Clicking on a channel in a team with only a General channel and then clicking on a channel in a different team (either with 1 or many channels), the first team collapses and I only see the team name.

Ideally I'd like the teams to remain open unless I specifically collapse them so I can easily see if a meeting is happening in any of them.

Teams Version 1.2.00.19260 (64 bit).

**Comment by Gousia-MSFT** [comment]
@dfjones1981 Thanks for reporting this. We have raised a bug for this and we are tracking it internally.

**Comment by Gousia-MSFT** [comment]
@dfjones1981 This is currently by design.
