### ISSUE TITLE
[Doc-Enhancement] Message action overflow menu is not showing custom app actions by default

### ISSUE THREAD

**Issue by SubbaReddi** [MicrosoftDocs/msteams-docs#8603]
Hi Team,
When the user clicks on the three dots, the overflow menu is displayed. However, LOB/3P related message actions are not displayed by default. Once the user clicks on 'More Actions', they can see the message actions and click on them. The respective message action will then be displayed in the overflow menu by default for next time. In summary, the overflow menu displays the three most recent message actions only, and there is no possibility to pin a message action to be displayed by default. Please add this information to the documentation.

![image](https://github.com/MicrosoftDocs/msteams-docs/assets/69682598/bc2daac5-20d9-4b6e-9f22-89210bc6b615)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: efcdf768-1513-2249-b344-bf38ef64c70d
* Version Independent ID: 415b5d57-2d41-9540-55a7-2a33a4315e37
* Content: [Define message extension action commands - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/action-commands/define-action-command)
* Content Source: [msteams-platform/messaging-extensions/how-to/action-commands/define-action-command.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/messaging-extensions/how-to/action-commands/define-action-command.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **anclear**

**Comment by Prasad-MSFT** [comment]
Hi @surbhigupta12 - Could you please help here to add a note in [this](https://learn.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/action-commands/define-action-command#select-action-command-invoke-locations) doc as mentioned above?
