### ISSUE TITLE
Adaptive cards are not displayed in mobile application

### ISSUE THREAD

**Issue by Leks12lk** [MicrosoftDocs/msteams-docs#861]
Adaptive cards are not displayed in mobile application. 
(AdaptiveSchemaVersion = 1.0)

I suppose the cause is in **SelectAction** property of AdaptiveCollectionElement. When this property exists on the card the card is not displayed, when it's missed - card is displayed ok.

For web version this issue is not reproduced.

**Comment by Wajeed-msft** [comment]
Could you please share your Adaptive card JSON?

**Comment by Leks12lk** [comment]
> Could you please share your Adaptive card JSON?

Please find Adaptive card JSON in attached zip.

[adaptive-card.zip](https://github.com/MicrosoftDocs/msteams-docs/files/3471770/adaptive-card.zip)

**Comment by VKAlwaysWin** [comment]
I can confirm the same behavior as well for IOS 12.4 (IPhone XS Max).
MS Teams app version: 1.0.80, Build: 1.077.2019071802, Calling Version: 2019.20.01.1

Broken JSON:
`{
  "type": "AdaptiveCard",
  "version": "1.0",
  "body": [
    {
      "type": "Container",
      "items": [
        {
          "type": "TextBlock",
          "size": "small",
          "isSubtle": true,
          "text": "Hello",
          "spacing": "none"
        }
      ]
    },
    {
      "type": "ColumnSet",
      "columns": [
        {
          "type": "Column",
          "width": "auto",
          "items": [
            {
              "type": "Image",
              "size": "medium",
              "url": "https://example.com"
            }
          ]
        },
        {
          "type": "Column",
          "width": "stretch",
          "items": [
            {
              "type": "TextBlock",
              "size": "medium",
              "weight": "bolder",
              "text": "Title",
              "wrap": true,
              "maxLines": 2,
              "spacing": "none"
            }
          ],
          "selectAction": {
            "type": "Action.OpenUrl",
            "url": "https://example.com"
          }
        }
      ],
      "spacing": "small"
    },
    {
      "type": "TextBlock",
      "text": "Description",
      "wrap": true
    }
  ]
}`

Working JSON:
`{
  "type": "AdaptiveCard",
  "version": "1.0",
  "body": [
    {
      "type": "Container",
      "items": [
        {
          "type": "TextBlock",
          "size": "small",
          "isSubtle": true,
          "text": "Hello",
          "spacing": "none"
        }
      ]
    },
    {
      "type": "ColumnSet",
      "columns": [
        {
          "type": "Column",
          "width": "auto",
          "items": [
            {
              "type": "Image",
              "size": "medium",
              "url": "https://example.com"
            }
          ]
        },
        {
          "type": "Column",
          "width": "stretch",
          "items": [
            {
              "type": "TextBlock",
              "size": "medium",
              "weight": "bolder",
              "text": "Title",
              "wrap": true,
              "maxLines": 2,
              "spacing": "none"
            }
          ]
        }
      ],
      "spacing": "small"
    },
    {
      "type": "TextBlock",
      "text": "Description",
      "wrap": true
    }
  ]
}`

Please note that only "selectAction" is extra field in Broken JSON. @Wajeed-msft Could you please confirm that you can reproduce it ?
 
Thank you in advance.

**Comment by Gousia-MSFT** [comment]
@Leks12lk This happens when some of the properties for Adaptive card elements are not specified. Could you please try adding title as suggested by @VKAlwaysWin and check if that helps. Please let us know if you are still facing the issue.

**Comment by Leks12lk** [comment]
@Gousia-MSFT adding title property helps me. Thanks. 
Is it by designed to have required Title property for SelectAction in mobile application?

**Comment by Gousia-MSFT** [comment]
@Leks12lk Mobile applications requires properties like Title, Id to be specified for the adaptive card elements to work on mobile.

**Comment by Leks12lk** [comment]
@Gousia-MSFT thanks for your help and reply.
