### ISSUE TITLE
Built-in Classifier SSN is not correct as to Compliance Center default

### ISSUE THREAD

**Issue by J-Bowie** [MicrosoftDocs/msteams-docs#8614]
Microsoft Learn/MSFT technet shows there are additional supporting elements for the built-in Data Classifier "U.S. Social Security Number (SSN)" that do not exist with the built-in classifier in Microsoft Purview as of 05/13/2023.
https://learn.microsoft.com/en-us/exchange/policy-and-compliance/data-loss-prevention/sensitive-information-types?view=exchserver-2019#us-social-security-number-ssn
Microsoft Documentation lists three (3) options as supporting element matches: 
```
<Match idRef="Keyword_ssn" />
<Match idRef="Func_us_date" />
<Match idRef="Func_us_address" />
```

Supporting element as of 05/13/2023 in the Microsoft Purview Compliance Portal is only **Keyword_ssn** for all four (4) confidence levels.
<img width="1486" alt="Screen Shot 2023-05-13 at 9 43 19 AM" src="https://github.com/MicrosoftDocs/msteams-docs/assets/13338150/45a67354-fafe-4843-aa91-2f9d4e1f6540">

Not sure if this needs to be updated on which side; if this was at one point standard for Compliance...I have tested documentation using both the file-tester and applying the Compliance policy with arguments for both Func_us_date and Func_us_address, neither proc the supporting element for pattern classification.

Thanks.

**Comment by J-Bowie** [comment]
Posted in wrong thread. This is not a teams issue - please close. Thanks.

**Comment by Meghana-MSFT** [comment]
Closing as this is not a Team's issue.
