### ISSUE TITLE
[Rendering] SPFx Viva Adaptive Card - Form double submit

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#8618]
Copied bug from: https://github.com/microsoft/AdaptiveCards/issues/8498 

**Details from original post:**
### Target Platforms

NodeJS

### SDK Version

1.15.2

### Application Name

Microsoft Teams - Viva

### Problem Description

We have identified a bug related to Viva adaptive card forms. If you double or triple click the submit button on a form, you will receive multiple form data.

To reproduce the issue, follow these steps: Start the SharePoint Crud example in Viva Connection Toolkit, click on the "Add Item" button, fill out the form, and then double click the save button.

### Screenshots

![image](https://user-images.githubusercontent.com/14911054/235165023-5217aa3d-d846-4fb5-a4dc-d3fc55de1f2d.png)

### Card JSON

```JSON
{
  "schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "type": "AdaptiveCard",
  "version": "1.2",
  "body": [{
    "type": "Container",
    "separator": true,
    "items": [{
        "type": "Input.Text",
        "id": "title",
        "label": "Title",
        "placeholder": "Title",
        "isMultiline": false
      },
      {
        "type": "Input.Text",
        "label": "Multi-Line Text",
        "id": "multilinetext",
        "placeholder": "Multi-Line Text",
        "height": "stretch",
        "isMultiline": true,
        "wrap": true
      },
      {
        "type": "Input.ChoiceSet",
        "label": "Choice Field DDL",
        "id": "choicefieldddl",
        "value": "",
        "choices": [{
          "$data": "${choiceFieldDDLValues}",
          "title": "${choice}",
          "value": "${value}"
        }]
      },
      {
        "type": "Input.Date",
        "label": "Date Time Field",
        "id": "datatimefield"
      },
      {
        "type": "Input.ChoiceSet",
        "label": "Choice Field Radio",
        "id": "choicefieldradio",
        "style": "expanded",
        "value": "",
        "choices": [{
          "$data": "${choiceFieldRadioValues}",
          "title": "${choice}",
          "value": "${value}"
        }]
      }, {
        "type": "Input.ChoiceSet",
        "label": "Choice Field Checkbox",
        "id": "choicefieldcheckbox",
        "isMultiSelect": true,
        "value": "",
        "choices": [{
          "$data": "${choiceFieldCheckboxValues}",
          "title": "${choice}",
          "value": "${value}"
        }]
      },
      {
        "type": "Input.Number",
        "label": "Number Field",
        "id": "numberfield"
      },
      {
        "type": "Input.Number",
        "label": "Currency Field",
        "id": "currencyfield"
      },
      {
        "type": "Input.Toggle",
        "label": "Yes/No Field",
        "title": "Yes/No",
        "id": "yesnofield"
      }, {
        "type": "ActionSet",
        "actions": [{
          "type": "Action.Submit",
          "title": "Save",
          "data": {
            "id": "save",
            "itemId": "${id}"
          }
        }]
      }
    ]
  }]
}
```

### Sample Code

_No response_---
#### Document Details

⚠ *Do not edit this section.It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Cards reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **surbhigupta12**

**Comment by ChetanSharma-msft** [comment]
Hello @lucasm107 - Thanks for raising your query.
We will look into it and let you know the updates.

**Comment by ChetanSharma-msft** [comment]
Hello @lucasm107 - Could you please share the repro steps and reference doc, if any?

**Comment by lucasm107** [comment]
To reproduce the issue, follow these steps: Start the SharePoint Crud example in Viva Connection Toolkit, click on the "Add Item" button, fill out the form, and then double-click the save button.

If you want I can attach the step by step with images

**Comment by Meghana-MSFT** [comment]
@lucasm107 - Apologies for the delay. Could you please raise this question on https://aka.ms/spfx-issues? SharePoint team have engagement with the customers and partners - together with engineering teams - One centralized location for all SPFx issues.

**Comment by Meghana-MSFT** [comment]
We are closing this issue, please feel free to reach out to us if you have any queries related to Teams app development.
