### ISSUE TITLE
[Designer] Microsoft teams selects v1.4 of Adaptive Cards instead of v1.5

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#8619]
Copied bug from: https://github.com/microsoft/AdaptiveCards/issues/8487 

**Details from original post:**
#### Current behavior 

When selecting Microsoft Teams in the [designer dropdown](https://adaptivecards.io/designer/) it automatically selects v1.4 of Adaptive Cards.

Microsoft Teams supports Adaptive Cards v1.5 per https://learn.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference#support-for-adaptive-cards

#### Expected behavior 

Update designer to automatically select Adaptive Cards v1.5 for Microsoft Teams

---

Related: https://github.com/MicrosoftDocs/AdaptiveCards/pull/505

### Card JSON

N/A

### Screenshot

_No response_---
#### Document Details

⚠ *Do not edit this section.It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Cards reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **surbhigupta12**

**Comment by ChetanSharma-msft** [comment]
Hello @Roganik - Thanks for raising your query.
We will look into it and let you know the updates.

**Comment by Prasad-MSFT** [comment]
Hi @Roganik - In [this](https://learn.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference#support-for-adaptive-cards) section it is mentioned that, Microsoft Teams supports Adaptive Cards v1.5 or **earlier**.
