### ISSUE TITLE
Compose Extension Queries not showing more than 100 results

### ISSUE THREAD

**Issue by chilla-lifesize** [MicrosoftDocs/msteams-docs#865]
At most 4 pages (100 elements @ 25 elements per page) are returned when scrolling through the results of the compose extension. After the 4th page is queried, no further queries are made by teams to fetch the next page from the list. This results in incomplete search results.

I have a results list of >2,000 elements and am paginating them at 25 elements per query. I am unable to retrieve more than the 1st 100 matches of the search.

**Comment by Gousia-MSFT** [comment]
@chilla-lifesize We don't support more than 100 results and while that may change, we don't have any plans to do so in the near future.
