### ISSUE TITLE
Stage view through deep link mentions "threadId" but doesn't explain what it does

### ISSUE THREAD

**Issue by eoinobrien** [MicrosoftDocs/msteams-docs#8657]
Under the "Invoke Stage View through deep link" section the docs call out a deep link with and without a `threadId`. 
But there is no information on what the threadId can be (can it be a chat, a meeting, a channel, all three) or why a developer should include a threadId? 

Can we expand the docs to explain what this threadId is used for. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b9bfa5c3-8227-c122-c4ff-a80786bc11d3
* Version Independent ID: b8a577f6-be73-14d7-3c6a-32eed5568b51
* Content: [Tabs link unfurling and Stage View - Teams](https://learn.microsoft.com/en-gb/microsoftteams/platform/tabs/tabs-link-unfurling)
* Content Source: [msteams-platform/tabs/tabs-link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/tabs/tabs-link-unfurling.md)
* Service: **msteams**
* GitHub Login: @Rajeshwari-v
* Microsoft Alias: **surbhigupta**

**Comment by ChetanSharma-msft** [comment]
Thanks for raising your query.
We will look into it and let you know the updates.

**Comment by Prasad-MSFT** [comment]
@eoinobrien - Ideally it should be all three. We are discussing this with concerned team and will get the document updated accordingly after further investigation.

Thanks!

**Comment by Prasad-MSFT** [comment]
The document is updated as below: 
The optional `threadId` parameter only supports chat threads. If a channel threadId is used, the side panel isn't displayed.

Ref: https://learn.microsoft.com/en-gb/microsoftteams/platform/tabs/open-content-in-stageview?tabs=withchat#deep-link-query-parameters
