### ISSUE TITLE
Following linkToMessage in channels fails intermittently

### ISSUE THREAD

**Issue by matthiasdilger** [MicrosoftDocs/msteams-docs#8671]
This issue affects desktop and web, Android still works flawlessly.
When triggering a message extension on a conversation reply in a channel, the bot receives a link to the message like so

```
messagePayload: {
      id: '1673092994074',
      replyToId: '1671891062076',
      createdDateTime: '2023-01-07T12:03:14.074Z',
      deleted: false,
      importance: 'normal',
      locale: 'en-us',
      from: [Object],
      body: [Object],
      attachments: [Array],
      mentions: [],
      reactions: [],
      linkToMessage: 'https://teams.microsoft.com/l/message/19:b72ee83fe6be47578920b77d05874add@thread.skype/1673092994074'
    }
```

Following the link should switch to the channel and highlight the message. After Teams has been updated with the new channel view and faster message loading, following the link does not reliably work anymore. One of the following behaviors can occur for the linkToMessage above, seemingly not reliably reproducible:

- Teams shows "Message can not be found" error OR
- Teams scrolls but does not highlight the message OR
- Teams scrolls and highlights the message

The issue mostly comes up when getting the link for a reply in an old conversation (lots of scrolling needed), then switching to a different team and then using the link to switch back to the previous team and channel.

Another way to trigger this without a bot is to hover over a conversation reply in a channel and select "Copy link". Open the link to see the conversation in Teams, then press "Go to channel" in the top right corner. This intermittently fails in the same way as described above, especially for older messages that require scrolling.
<img width="1060" alt="Screenshot 2023-05-19 at 08 41 33" src="https://github.com/MicrosoftDocs/msteams-docs/assets/5625718/d869658d-6c8f-4253-a9c7-805f2c89f907">

The issue seems to be a kind of race condition between switching to the channel, loading the messages and scrolling to the right message.

**Comment by Prasad-MSFT** [comment]
@matthiasdilger - Thanks for raising this. We will check this issue from our end and will update you shortly with our findings.

**Comment by Prasad-MSFT** [comment]
@matthiasdilger - We tried to repro this issue, however we observed that the using linkToMessage, MS Teams scrolls and highlights the message.
We aren't able to repro the behaviour you are facing. FYI, we are getting the link for a reply in an old conversation, then switching to a different team and then using the link to switch back to the previous team and channel as mentioned.

**Comment by matthiasdilger** [comment]
@Prasad-MSFT I have made a video that shows the problem: https://moonbears-my.sharepoint.com/:v:/g/personal/moonbearapps_moonbears_onmicrosoft_com/Ecb-s1OsTvROs55nMHakFwwBCNFciETQFU-w2vdnlOLXJw?e=mKXtNn

1. I scroll to an old conversation reply and  trigger the message extension, which writes the linkToMessage url to the console in the background
2. I navigate around the channels to simulate other work, notice the scrolling in other channel
3. I navigate to chat
4. I copy the url from step 1 and open the Teams client with it
5. Teams navigates to the right channel but shows error message: "Unable to find message" and Teams does not scroll or highlight the message.

**Comment by Prasad-MSFT** [comment]
@matthiasdilger - I followed the same steps as mentioned above by referring to the video shared. However, it redirects to particular message in our case. We are not able to repro this. 

Attaching the video as zip file for reference:
[LinkToMessageIssue.zip](https://github.com/MicrosoftDocs/msteams-docs/files/11527518/LinkToMessageIssue.zip)

**Comment by matthiasdilger** [comment]
@Prasad-MSFT There are a few differences between our videos: You are not using the new channel experience (new messages on top) and you are triggering the message extension on the conversation start, not on a reply (notice how replyToId is null in your payload). For conversation start messages it works for me too, the issue is with replies.

**Comment by Prasad-MSFT** [comment]
@matthiasdilger - We checked with replies as well, but there also it works at our end.
[LinkToMessageIssue2.zip](https://github.com/MicrosoftDocs/msteams-docs/files/11527859/LinkToMessageIssue2.zip)

But as you said we are not using new channel experience. It is not there in our MS Teams. Is there any way to enable it?

**Comment by Prasad-MSFT** [comment]
@matthiasdilger - Thanks for informing the same. We are closing this issue for now. Please feel free to reopen if required. 

Thanks!
