### ISSUE TITLE
Multi tenant, cannot receive calls from unselected tenant

### ISSUE THREAD

**Issue by TeamStriebigSebastian** [MicrosoftDocs/msteams-docs#870]
Multi company
I am in Company A
Someone in Company B tries to call me.
The call is not shown, nor rings. 
It is then just noted in the activities. 
This is a critical use case for multi-tenant support, that I can be reached within teams from all companies. I have several different customers, with different Teams instances. Teams brings me back to ask people to call my phone since TEAMS is not reliable for urgent direct communication.

**Comment by Trinetra-MSFT** [comment]
Thanks for reporting this. We are looking into it.

**Comment by Trinetra-MSFT** [comment]
Are you trying to make a call with Guest user account? if it is the scenario than it is by design at this time.

**Comment by TeamStriebigSebastian** [comment]
No it is not a guest account, this is my coworker. But it sometimes seems
to think I am a guest account.
Like forgetting my eliviated permissions.

**Comment by TeamStriebigSebastian** [comment]
It is teams. Since I connected another company (over the same email adress)
Teams got really a pain in the ***

**Comment by TeamStriebigSebastian** [comment]
I resolved it by starting the client in the web app. Restarting the desktop
app did not do the trick.

**Comment by TeamStriebigSebastian** [comment]
Or forget it, I mixed up tickets, because of all the problems. But now I am
speechless.
Sorry this is not personal, but is feedback for your PRODUCT Owner:

WHY ON EARTH AM I NOT SUPPOSED TO BE CALLED BY MY CO-WORKERS WHILE BEING
LOCKED IN THE OTHER COMPANY?
Is there any Persona, who has the job consultant? Apparently not.

Did PRODUCT ever talk to a customer while creating user stories about the
behavior of TEAMS?
This thing (TEAMS) is or should be my god damn phone.
Of course you should be able to call me. And I can decline your call with a
short message. Sorry in a meeting, call you back in 5. Even make it a
******* button!
But no I miss all the calls of my coworkers, while they really need my help
and don't see it. And then I go there to see the aftermath.

Your product team should stop trying to imagine user stories and start
talking to the user/customer.
------------------------------------------------------
Verdict: Elfenbeinturmbewohner!
---------------------------------------
Sorry for this outburst but I am seriously disappointed by Microsoft and
your complete team as well as TEAMS as a product.
If it would be my decision, I would rather use anything else but teams if
working in a multi-tenant setup.

**Comment by arielgordon** [comment]
Striebig, Thanks for sending this feedback. We understand your frustration. We're fully aware of the use case and of the current limitation. Unfortunately I don't have an ETA to share at this time. Suggestion: please consider running Teams on your phone as well. This will ensure you remain reachable by your colleagues while you work in another tenant in the desktop app. Thanks again--

**Comment by TeamStriebigSebastian** [comment]
Thanks for your reply. I use teams on my phone..... That sounds like you
already seem to have a lot of technical debt. If the phone apps behave
different then the desktop and web app, then you already going towards a
bad place. Good luck.

Ariel Gordon <notifications@github.com> schrieb am Fr., 9. Aug. 2019, 20:56:

**Comment by FrancoiD** [comment]
The phone app does not behave differently. The suggestion was to be logged as your main tenant identity on the mobile, while you log as a Guest on your desktop app.

Here is another, alternative approach I'd suggest:
Always keep your main desktop app logged in as your main tenant identity.
In addition, open a browser window for teams.microsoft.com and use that one for your Guest account. 
We realize its a workaround while we work on longer term solutions, but that workaround will entirely solve the issue you reported.
