### ISSUE TITLE
Tells us we can, but now how.

### ISSUE THREAD

**Issue by 404UsernameNotFound404** [MicrosoftDocs/msteams-docs#871]
It says "your bot can asynchronously post a message to the channel",  but does not reference a tutorial or docs on how to do this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 375145a1-abf2-b2c0-843d-d03247650f82
* Version Independent ID: ff73df5c-d4e6-150a-f32a-771a46905e18
* Content: [Combine bots with tabs - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/bots/bots-with-tabs#feedback)
* Content Source: [msteams-platform/concepts/bots/bots-with-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/bots/bots-with-tabs.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Wajeed-msft** [comment]
Here is the documentation for [Creating a channel conversation](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/bots/bot-conversations/bots-conv-proactive#creating-a-channel-conversation) using Bot.

**Comment by Gousia-MSFT** [comment]
Please reopen if you still have any doubts.
