### ISSUE TITLE
Should this page still have "(preview)" in the title?

### ISSUE THREAD

**Issue by AE-MS** [MicrosoftDocs/msteams-docs#8722]
I thought the ability to extend your Teams app across M365 is publicly and generally available. Should the title for this page still have "(preview)" in the title?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6fcea0c3-c249-a292-913b-dc0271e4e810
* Version Independent ID: 6fcea0c3-c249-a292-913b-dc0271e4e810
* Content: [Extend Teams apps across Microsoft 365 (preview) - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/m365-apps/overview)
* Content Source: [msteams-platform/m365-apps/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/m365-apps/overview.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Prasad-MSFT** [comment]
Hi @AE-MS - Could you please let us know in which section you have noticed "preview" in title?
In this document's title, we could not see any 'preview' text. 
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/62237649/1a08a963-f7bc-45e6-9c12-31a63167bb80)

It would be really helpful for us if you point this out so that we can update the document accordingly.

Thanks !

**Comment by AE-MS** [comment]
It's literally the title of the page:
<img width="550" alt="image" src="https://github.com/MicrosoftDocs/msteams-docs/assets/36546967/e5691ee1-273f-4eaa-bc2d-8c3c1d434c19">
<img width="229" alt="image" src="https://github.com/MicrosoftDocs/msteams-docs/assets/36546967/26c1f2c3-f6b2-4b2d-91f5-8bc27b5b5e4b">

You can also see it automatically inserted in the initial post that generated this github issue:

<img width="343" alt="image" src="https://github.com/MicrosoftDocs/msteams-docs/assets/36546967/5ef7faa2-f930-49ab-b2b1-be51220e66f9">

**Comment by Wajeed-msft** [comment]
@surbhigupta12 - could you please check this?
