### ISSUE TITLE
Message Extension Bug for 3P Outlook Apps

### ISSUE THREAD

**Issue by leannetoth** [MicrosoftDocs/msteams-docs#8728]
Our partner Breakthru has excluded ME in their Outlook integration. They currently have ME in their Teams integration but opted out of Outlook. Our understanding is that ME should work in Outlook too (without any additional work by the developer).

Considering that it doesn't work, it is likely a bug on the Microsoft side, when I tried it on Outlook web, I can't even get the app menu to open in the new email compose bar.

![breakthru outlook](https://github.com/MicrosoftDocs/msteams-docs/assets/134654404/2a502648-d645-48bb-afe6-5f40856053a5)

**Comment by ChetanSharma-msft** [comment]
Thanks for reporting your issue.
We will look into it and let you know the updates.

**Comment by sayali-MSFT** [comment]
@leannetoth -We have tested the above scenario using this  [sample](https://github.com/OfficeDev/TeamsFx-Samples/tree/v2.1.0/NPM-search-connector-M365), It is working fine from our end.

Could you please refer the sample and check it once?

![MicrosoftTeams-image (31)](https://github.com/MicrosoftDocs/msteams-docs/assets/93527375/dd0aaeaa-7f60-4ce8-98cb-b75a992c6c14)


Reference Document-https://learn.microsoft.com/en-us/microsoftteams/platform/m365-apps/extend-m365-teams-message-extension?tabs=manifest-teams-toolkit

**Comment by leannetoth** [comment]
Thank you can you clarify if the partner, Breakthru needs to build ME to enable this to work and it will not work by default?

**Comment by sayali-MSFT** [comment]
@leannetoth -No, it will not work Bydefault. 
If it is message extension bot. 
If you've connected your message extension bot to an Outlook channel, you must migrate to the Microsoft 365 channel.

**Comment by nwojod-MSFT** [comment]
Closing this issue. @leannetoth please refer this document on migrating to M365 bot channel https://learn.microsoft.com/en-us/microsoftteams/platform/m365-apps/extend-m365-teams-message-extension?tabs=manifest-teams-toolkit.
