### ISSUE TITLE
Muli tenant, company switch trys to send me back imidiatly to other company

### ISSUE THREAD

**Issue by TeamStriebigSebastian** [MicrosoftDocs/msteams-docs#873]
Hi I switch from company A to company B. Then this message appears, asking me if i like to switch back to company A. 
![image](https://user-images.githubusercontent.com/26815666/62604614-bafc2e00-b8f8-11e9-8153-bd131d1b275d.png)
I don't think this is intended behavior.

**Comment by TeamStriebigSebastian** [comment]
If I press abort (Abbrechen) the it just shows me a screen with nothing. :D 
![image](https://user-images.githubusercontent.com/26815666/62604794-12020300-b8f9-11e9-9bfb-4c920e7e7a57.png)
I am now absolutly sure this is not intended behavior. ;)

**Comment by Gousia-MSFT** [comment]
@TeamStriebigSebastian We could not repro this. Are you facing it on Desktop or on Web client?

**Comment by TeamStriebigSebastian** [comment]
Desktop client on windows 10

Gousia-MSFT <notifications@github.com> schrieb am Mi., 7. Aug. 2019, 09:58:

**Comment by Gousia-MSFT** [comment]
@TeamStriebigSebastian We are looking into this.

**Comment by Gousia-MSFT** [comment]
@TeamStriebigSebistian We have raised a bug for this. This is being tracked internally.
