### ISSUE TITLE
Mention of limit on how many typeahead items can be shown

### ISSUE THREAD

**Issue by BabaSwagDev** [MicrosoftDocs/msteams-docs#8732]
Hi there!

I am currently working on sending an adaptive card via Cognigy to the MS teams channel via Azure bot services registration. 
I learnt that we can use typehead search in the adaptive card as per this page. However, there is no mention anywhere on the page about the limit of dropdown items or search that can be shown with this feature in the adaptive card.
Please could you add this important information.

Thanks & Regards,
Sagar

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 19ddf42e-0a47-7717-52d4-e549155480a2
* Version Independent ID: 4bbe9beb-233f-cfd5-097b-f280aab5fde8
* Content: [Microsoft Teams developer community support and feedback - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/feedback)
* Content Source: [msteams-platform/feedback.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/feedback.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by BabaSwagDev** [comment]
Adding more details to this:: 

when I use a low number of choices in a choiceset and send it to MS teams, it works without issues. However, when I send a card with 2000 items it simply doesn't show the adaptive card. However, when I sent it to WEBCHAT in Cognigy, it works without any issue.

**Comment by ChetanSharma-msft** [comment]
Hello @BabaSwagDev - Thanks for raising your query.
We will look into it and let you know the updates.

**Comment by sayali-MSFT** [comment]
@BabaSwagDev -We are checking with the engineering team and let you know once we get any update.

**Comment by sayali-MSFT** [comment]
We have received a response from the engineering team, stating that the maximum limit for items shown in the dropdown is 15.
We will update the document accordingly.

**Comment by BabaSwagDev** [comment]
Hi @sayali-MSFT 

Thanks for reverting.
My questions is not about 'How many items can be seen at a time in the dropdown', instead I meant what is the maximum allowed items within the typeahead search JSON.

**Comment by BabaSwagDev** [comment]
Hi @Wajeed-msft 
Looking forward for an update on this.

**Comment by sayali-MSFT** [comment]
@BabaSwagDev - We are actively checking the updates, with engineering team and let you know, if we have any.
