### ISSUE TITLE
Key error in adaptive card example for opening link in stage view

### ISSUE THREAD

**Issue by alex-zwingli** [MicrosoftDocs/msteams-docs#8734]
[Enter feedback here]
In the adaptive card example, the `name` key should be `title`. It is `title` that determines what string is displayed in the action button, not `name`.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b9bfa5c3-8227-c122-c4ff-a80786bc11d3
* Version Independent ID: b8a577f6-be73-14d7-3c6a-32eed5568b51
* Content: [Tabs link unfurling and Stage View - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/tabs-link-unfurling)
* Content Source: [msteams-platform/tabs/tabs-link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/tabs/tabs-link-unfurling.md)
* Service: **msteams**
* GitHub Login: @Rajeshwari-v
* Microsoft Alias: **surbhigupta**

**Comment by ChetanSharma-msft** [comment]
Hello @alex-zwingli - Thanks for raising your query.
We will look into it and let you know the updates.

**Comment by Nivedipa-MSFT** [comment]
@surbhigupta12 - Could you please update the below code [here](https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/tabs-link-unfurling#example).

```
{
    type: "Action.Submit",
    title: "View",
    data: {
          msteams: {
            type: "invoke",
            value: {
                type: "tab/tabInfoAction",
                tabInfo: {
                    contentUrl: contentUrl,
                    websiteUrl: websiteUrl,
                    name: "Tasks",
                    entityId: "entityId"
                 }
                }
            }
        }
}

```
