### ISSUE TITLE
SharePoint URLs are not properly encoded for mobile resulting in broken 404 links.

### ISSUE THREAD

**Issue by unt1tled** [MicrosoftDocs/msteams-docs#874]
In my tests, accessing any SharePoint file URL that contains a # before the last segment will result in a 404 File not found on iPad & iPhone. 

SharePoint supports the use of # in the filename. So if we use a video file as an example, where a # is before the file extension, like "video #1.mp4":
- The video will play in the desktop Teams video player
- The video URL will successfully navigate to the file in the browser in desktop Teams
- The video will **not** play in mobile Teams video player (results in "Something went wrong") 
- The video URL will result in **404** in Safari on mobile devices.

In the above example, # should be encoded as %23 for the link to work correctly: video%20%26.mp4

**Comment by Abhijit-MSFT** [comment]
@unt1tled - Are you following any particular steps when you are facing this. I tested file with the name EC4#.mp4 and it worked on Desktop/Web, Android/iPad/iPhone, Chrome/Safari. No where i received 404 or something went wrong. 
Can you please share repro steps. Please check the screen below, it is properly getting encoded at "#".

![image](https://user-images.githubusercontent.com/48427340/63163336-be06c500-c042-11e9-906f-f1bdf6418dd3.png)

**Comment by unt1tled** [comment]
@Abhijit-MSFT  I should clarify. After testing, it seems this issue presents itself for non-office files (like mp4 files in the example above). 

To reproduce: 

1. Download a test mp4 file (I used this [1mb sample video](https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4))
2. Rename to "test #1.mp4" and upload it to a folder on SharePoint.
3. From Teams, Navigate to the folder via the Files tab.
4. Right Click > Get Link.  (Mine looks like https://domain.sharepoint.com/sites/Team/Shared%20Documents/General/test%20#1.mp4)
5. Paste copied link into browser and navigate.

Link in Chrome:
![image](https://user-images.githubusercontent.com/5357052/63227605-13171800-c1b6-11e9-8378-5dd337f38042.png)

Link in Edge:
![image](https://user-images.githubusercontent.com/5357052/63227624-6db07400-c1b6-11e9-9a57-4b8150052b7a.png)


Using Microsoft Teams Version 1.2.00.19260 (64-bit)

Also, as a side note: The file is accepted when uploading the file via SharePoint in the browser. However, the file is not accepted when uploading the file via Teams: 
![image](https://user-images.githubusercontent.com/5357052/63227664-dbf53680-c1b6-11e9-9352-9cb7b931e49c.png)
This is despite the # character being allowed Windows and SharePoint filenames.

**Comment by billbliss** [comment]
@Abhijit-MSFT likely an artifact of the new SharePoint-based implementation (or an interaction between the client and it). 

Please file a bug and assign to the Files team. (I'll post in Files channel and @mention you; they may want to file this themselves.)

**Comment by Abhijit-MSFT** [comment]
@billbliss - Bug is filed for this issue. @unt1tled - Thanks for your findings

**Comment by Gousia-MSFT** [comment]
@unt1tled Thanks for reaching out. We are tracking this bug internally.
