### ISSUE TITLE
HeroImage Suppot in Teams

### ISSUE THREAD

**Issue by boredom2** [MicrosoftDocs/msteams-docs#875]
Hi there,

Is it possible, that section.heroImage is not supported in Teams?
If I define it, the Call is sent successfully, but the Image dies not show.
It does show though, if i add the same Image in the images Array. But for our Needs, its displayed too small then.
Is there a way to show an HeroImage?

Thanks!
Christoph

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0fd8e4d-f110-36f8-5bd3-db3325b14c01
* Version Independent ID: 717ea854-1d3a-2c15-e495-b6f170fe7aff
* Content: [Using Office 365 Connectors - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/connectors/connectors-using#feedback)
* Content Source: [msteams-platform/concepts/connectors/connectors-using.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/connectors/connectors-using.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Gousia-MSFT** [comment]
@boredom2 We were able to repro this. We have raised a bug for this. We are looking into it.

**Comment by boredom2** [comment]
Thanks,
