### ISSUE TITLE
Multi Tenant - cannot chat with one of my coworkers anymore...

### ISSUE THREAD

**Issue by TeamStriebigSebastian** [MicrosoftDocs/msteams-docs#876]
...because I don't am a member of the chat. ???
![image](https://user-images.githubusercontent.com/26815666/62775763-e02f9e80-baa8-11e9-888f-26a8ffb22961.png)
I can chat with anybody else, but this guy.

**Comment by TeamStriebigSebastian** [comment]
I also don't see any phone or video buttons on the right upper area

**Comment by TeamStriebigSebastian** [comment]
Desktop app. Restarted it already twice

**Comment by FrancoiD** [comment]
Hello, I cannot determine whether you are trying to chat in-tenant or whether you are cross tenant (either federated or using a Guest identity). Can you please confirm? Thanks

**Comment by TeamStriebigSebastian** [comment]
It was in-tenant.

Francois Doremieux (Microsoft) <notifications@github.com> schrieb am Mo.,
12. Aug. 2019, 15:31:

**Comment by Gousia-MSFT** [comment]
Please re-open if you are still facing the issue.
