### ISSUE TITLE
Adaptive card Tabs not working on iOS but working on Desktop

### ISSUE THREAD

**Issue by jl0zano** [MicrosoftDocs/msteams-docs#8772]
Hi, we're running into an issue where adaptive card tabs are not being displayed on the Teams app in iOS. We have a bot serving these adaptive cards tabs contents.

This is the doc we followed to create the tabs: https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/build-adaptive-card-tabs

This is what the desktop version looks like:
<img width="550" alt="image" src="https://github.com/MicrosoftDocs/msteams-docs/assets/13248317/8fd0f27e-eac3-4afa-adcc-1b875fdcb247">

But when you open the same tab on the iOS app:
<img width="250" height="350" alt="image" src="https://github.com/MicrosoftDocs/msteams-docs/assets/13248317/120d8c09-f9a0-4b65-bde3-6f816edc6ebe">

When you first open the app on mobile, it does not make a request to our bot on the /api/messages endpoint which handles the requests and generates the tab's content that is passed back.

Then if you tap on try again, it now makes the request to our bot, which returns a 200 with the tab's content but the tab just stays blank:
<img width="250" height="350" alt="image" src="https://github.com/MicrosoftDocs/msteams-docs/assets/13248317/638a0d63-ea61-4407-a5de-4608bfa64c82">

This is the bot's response, which is the same for the desktop and mobile client:

`{
  "tab": {
    "type": "continue",
    "value": {
      "cards": [
        {
          "card": {
            "type": "AdaptiveCard",
            "body": [
              {
                "type": "Container",
                "items": [{ "type": "TextBlock", "text": " " }],
                "minHeight": "1px"
              },
              {
                "type": "TextBlock",
                "text": "Hi Jaime, welcome to Tribute",
                "weight": "Bolder",
                "size": "Large"
              }
            ]
          }
        },
        {
          "card": {
            "type": "AdaptiveCard",
            "body": [
              {
                "type": "ColumnSet",
                "columns": [
                  {
                    "type": "Column",
                    "items": [
                      { "type": "TextBlock", "text": "Your Goal" },
                      {
                        "type": "TextBlock",
                        "text": "This is my life advice goal",
                        "separator": true,
                        "spacing": "Large"
                      },
                      {
                        "type": "TextBlock",
                        "text": "🟡 You aren’t in a mentorship for this goal yet."
                      }
                    ]
                  }
                ]
              }
            ],
            "actions": [
              {
                "type": "Action.Submit",
                "title": "Edit Goal",
                "spacing": "Large",
                "data": {
                  "id": "editGoal",
                  "msteams": { "type": "task/fetch" }
                }
              },
              {
                "type": "Action.Submit",
                "title": "Set New Goal",
                "data": {
                  "id": "setNewGoal",
                  "msteams": { "type": "task/fetch" }
                }
              }
            ]
          }
        }
      ]
    }
  }
}
`

Are we doing something wrong? I also made sure the static tabs include a websiteUrl on the app manifest (version 1.9) Note: I updated this bit to hide our bot guid but the guid is there.

`
"staticTabs": [
    {
      "entityId": "homeTab",
      "name": "Home",
      "contentBotId": "[our-bot's-guid]",
      "scopes": ["personal"],
      "websiteUrl": "https://my-bot-instance.ngrok.io/mobile"
    },
    {
      "entityId": "profileTab",
      "name": "Profile",
      "contentBotId": "[our-bot's-guid]",
      "scopes": ["personal"],
      "websiteUrl": "https://my-bot-instance.ngrok.io/mobile"
    },
  ],
`

**Comment by Nivedipa-MSFT** [comment]
@jl0zano - Thanks for reporting your issue. We will test this and update you soon.

**Comment by Nivedipa-MSFT** [comment]
@jl0zano - We have tested this using below sample
https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/tab-adaptive-cards/csharp

We have tested this on IOS 16.4.1(a) and below Teams version
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/92150070/6685178e-658a-40a9-b55f-4195843f4b09)

At the first time we are getting 'Try Again' message and clicking on 'Try Again' the tab is loading correctly.
Please refer below video:

https://github.com/MicrosoftDocs/msteams-docs/assets/92150070/e99c2b05-76e5-4b19-b058-b179d7c99740

**Comment by jl0zano** [comment]
@Nivedipa-MSFT I figured out the issue as to why I was getting a blank page after clicking "Try Again".

I tried using a simpler payload and it worked on iOS after clicking "Try Again". I compared this working payload to the one I provided and I noticed these 3 properties were missing in the adaptive cards that were not working:

`
"msteams": { "width": "Full" },
"$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
"version": "1.4"
`

After I added them to each of the cards they are now being displayed correctly!

I also tried this out on Android and the app seems to work fine with no "Try Again" button.

We're currently submitting this app to production and the testers told us that we need to get the app to work on mobile, but if its a Teams App issue, how we can leverage this with the testers? We're trying to deploy our app as soon as possible but don't know how much time this would take to be fixed and deployed... Btw I'm using the same app version as you.

Thanks!

**Comment by Nivedipa-MSFT** [comment]
@jl0zano - We need to add the below properties in adaptive card to get working in Teams.
`"msteams": { "width": "Full" }, "$schema": "http://adaptivecards.io/schemas/adaptive-card.json", "version": "1.4"`
Ref Doc: https://learn.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference#adaptive-card

As its mentioned in [this](https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/build-adaptive-card-tabs) document Adaptive Card tabs will be deprecated in the new Microsoft Teams. If your app is using Adaptive Card tabs, it's recommended to rebuild the tab as a web-based tab. For more information, see [Build tabs for Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs).

**Comment by ChetanSharma-msft** [comment]
Hello @jl0zano - Could you please confirm if your issue has resolved with above suggestion or still looking for any help?

**Comment by jl0zano** [comment]
We're going to rewrite our app in react. Even when adaptive cards tabs are deprecated its a shame they still wouldn't work, its only been 5 days since the official deprecation lol. Thank you both for your replies anyhow. Cheers.
