### ISSUE TITLE
Apps for anonymous users is supported in Teams mobile iOS client only

### ISSUE THREAD

**Issue by Harikrishnan-MSFT** [MicrosoftDocs/msteams-docs#8775]
Hi Team,

Please update the note in the documentation "Apps for anonymous users is supported in Teams mobile iOS client only and isn't supported in channel meetings."   

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2c5bc94a-3c95-aecc-a34d-d9771dc5e9bb
* Version Independent ID: 2c5bc94a-3c95-aecc-a34d-d9771dc5e9bb
* Content: [Build apps for anonymous user - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/build-apps-for-anonymous-user?branch=pr-en-us-8543&tabs=javascript)
* Content Source: [msteams-platform/apps-in-teams-meetings/build-apps-for-anonymous-user.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/apps-in-teams-meetings/build-apps-for-anonymous-user.md)
* Service: **msteams**
* GitHub Login: @v-sdhakshina
* Microsoft Alias: **v-sdhakshina**

**Comment by Nivedipa-MSFT** [comment]
@surbhigupta12 - Could you please update the below note [here](https://learn.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/build-apps-for-anonymous-user?branch=pr-en-us-8543&tabs=javascript).
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/92150070/b2713ed3-56c9-4839-8296-8b276ca1db42)

Note need to be updated: Apps for anonymous users is supported in Teams mobile iOS client only.

**Comment by ashishguptaiitb** [comment]
@surbhigupta12 , is this validated by the PM and engg team? I ask so that I can also make necessary updates in the admin docs.

**Comment by surbhigupta12** [comment]
@ashishguptaiitb, yes, it is validated by PM and engr. team
