### ISSUE TITLE
Sideloading is disbaled

### ISSUE THREAD

**Issue by PragashVenu** [MicrosoftDocs/msteams-docs#8780]
Hi,
I am trying to login to my MS tenant from VS Code for Teams development. I am getting error saying sideloading disabled. My demo tenant meeting all the prerequisite. Please refer below screenshot. Kindly anyone help to solve this issue.

![image](https://github.com/MicrosoftDocs/msteams-docs/assets/117729955/8fb0588f-e400-43d2-bff8-918031335077)
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/117729955/b44e4a26-9c9c-421f-9250-5810f94d094b)
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/117729955/67392f3e-6a29-4f65-9032-3fdbd2a8bddb)
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/117729955/e82a7aab-fc52-4b5f-b602-f6f1e30003f7)

**Comment by sayali-MSFT** [comment]
@PragashVenu - Thanks for reporting your issue.
We will check this at our end and will get back to you.

**Comment by PragashVenu** [comment]
Hi Sayali

I just checked and it is connected now.

![image](https://github.com/MicrosoftDocs/msteams-docs/assets/117729955/761ddb70-c4df-4c7c-86cf-bc4ef5cba080)

But I did not do any changes on my end.

Kind regards
Pragash

**Comment by sayali-MSFT** [comment]
@PragashVenu -May be changes are not reflected, so that it will showing the disabled.

Shall we close this issue?

**Comment by PragashVenu** [comment]
Hi Sayali

Thank you for your reply, yes you could close this case. I configured this on last Thursday and until yesterday it was disabled, but now I can see it.
