### ISSUE TITLE
Navigation bar not displayed when accessing tab app via deep link on mobile app

### ISSUE THREAD

**Issue by yuji-naito** [MicrosoftDocs/msteams-docs#8784]
Hi, We are currently developing a bot and tab app for the Teams.
We have implemented a feature where the bot sends a deep link to the tab, and users can click on the link to navigate to the tab.

This works as expected on the desktop version of Teams, with the navigation bar being displayed correctly in the tab.
However, when we try the same on the Teams mobile app, the navigation bar does not appear in the tab after navigating via the deep link.

We have confirmed that the navigation bar does appear when We navigate to the tab normally (not via the deep link) on the mobile app.
This issue only occurs when I navigate via the deep link.

Is there a specification that the navigation bar is not displayed when navigating from a deep link to a tab in a mobile app?

The deep link is following.
`https://teams.microsoft.com/l/entity/{appId}/{entityId}`

The navigation bar is the image in following.
<img width="500" src="https://github.com/MicrosoftDocs/msteams-docs/assets/38898144/34ed7b86-db56-4e55-b1ab-eea4123e9d76">

Mofile version (Android): 1416/1.0.0.2023092901/0516
Desktop version: 1.0

Thank you.

**Comment by Meghana-MSFT** [comment]
Thank you for reporting this issue, we will check this issue and get back to you.

**Comment by Meghana-MSFT** [comment]
We checked this at our end.

Opening tab directly, bottom navigation bar is visible -

https://github.com/MicrosoftDocs/msteams-docs/assets/81138249/b83391bc-81a3-4754-aba1-6c8eb9ed23ca


Opening deeplink to a configurable tab from bot in Channel - 

https://github.com/MicrosoftDocs/msteams-docs/assets/81138249/cce640aa-b1ac-4fe6-96ae-e39f8fda8058

Could you please let us know if you are also seeing the same behavior?

**Comment by Meghana-MSFT** [comment]
@yuji-naito - We checked this issue internally, This is by design. When we open an app from deep link, we don't show bottom bar or navigation panel, thus users can't see it.

There's no immediate plan to change this behaviour.
