### ISSUE TITLE
No option for creation outgoing webhook

### ISSUE THREAD

**Issue by viksakshum** [MicrosoftDocs/msteams-docs#879]
my ms teams app on mac do not show option to create a outgoing webhook, see the screenshot
https://www.dropbox.com/s/awb6h5h3kkmgbzq/Screenshot%202019-08-10%2000.54.31.png?dl=0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06c224ae-1484-408c-d17a-e7e1ba07e78a
* Version Independent ID: fac8ff1e-a127-c12a-5304-9de39b1a15c6
* Content: [Outgoing webhooks - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/outgoingwebhook#feedback)
* Content Source: [msteams-platform/concepts/outgoingwebhook.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/outgoingwebhook.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Trinetra-MSFT** [comment]
@viksakshum, Could you please confirm if [sideloading is enabled](https://docs.microsoft.com/en-us/MicrosoftTeams/teams-app-permission-policies#can-i-use-app-permission-policies-to-restrict-uploading-custom-apps-also-known-as-sideloading) by your tenant admin?

**Comment by viksakshum** [comment]
i have no idea what was the problem it appears now so closing

**Comment by agladboy** [comment]
@Wajeed-msft I have the same issue and I checked with Mac and Windows version, the option of creating the Outgoing webhooks is not there, I can side-loading third-party apps.
