### ISSUE TITLE
Emails with cards not being sent to receipient

### ISSUE THREAD

**Issue by ktcodebite** [MicrosoftDocs/msteams-docs#8795]
reporting on behalf of developer Smartsheet: "Sending an email with unfurl details does not surface within the recipient's inbox. Please see attached screenshot"

<img width="1474" alt="Screenshot #2 - Unfurl link does not surface within recipients inbox" src="https://github.com/MicrosoftDocs/msteams-docs/assets/16550774/8c851cc1-d089-408b-b296-302b43d5a818">

**Comment by ChetanSharma-msft** [comment]
Hello @ktcodebite - Thanks for raising your query.
We will look into it and let you know the updates.

**Comment by ktcodebite** [comment]
Ok will check and get back here with more details.

**Comment by ktcodebite** [comment]
Partner got back to me, looks like it is not repro'ing on their end anymore either, we can close this.

**Comment by Nivedipa-MSFT** [comment]
@ktcodebite - Thanks for confirmation. Could you please share your valuable feedback via [Microsoft Teams Developer Feedback](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR7iCOpS5_b9Nqmwx43u5rtZUOThVR081SllSR05aSDQxQ0tUMDVPTVIxTi4u) link.
