### ISSUE TITLE
Add Note Clarifying Which Cloud Environments Are Supported for Teams Toolkit

### ISSUE THREAD

**Issue by marianocalero** [MicrosoftDocs/msteams-docs#8796]
As the Teams Toolkit currently only supports general clouds, can you add a note clarifying whether this is available in GCC or GCC-H?
We are seeing some customers in GCC trying to use the Toolkit but getting errors. Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b743e43d-95cc-3d1e-b142-31a16369f97e
* Version Independent ID: b743e43d-95cc-3d1e-b142-31a16369f97e
* Content: [Teams Toolkit Overview - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/toolkit/teams-toolkit-fundamentals?pivots=visual-studio-code)
* Content Source: [msteams-platform/toolkit/teams-toolkit-fundamentals.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/teams-toolkit-fundamentals.md)
* Service: **msteams**
* GitHub Login: @zyxiaoyuer
* Microsoft Alias: **zhany**

**Comment by Meghana-MSFT** [comment]
Thank you for reporting this, we will check internally ang get the doc updated.

**Comment by Meghana-MSFT** [comment]
@surbhigupta12 - Could you please add below note in the doc [Teams Toolkit Overview - Teams | Microsoft Learn](https://learn.microsoft.com/en-us/microsoftteams/platform/toolkit/teams-toolkit-fundamentals?pivots=visual-studio-code)

 

Note : "Teams Toolkit is currently not supported in GCC and GCCH clouds"
