### ISSUE TITLE
The list of domains for the Content-Security-Policy header is incomplete

### ISSUE THREAD

**Issue by AE-MS** [MicrosoftDocs/msteams-docs#8805]
The list of domains referenced on this page for Content-Security-Policy is incomplete. It only lists Teams domains, for example, and none of the other domains in M365 for hosting apps (e.g., outlook and office.com and microsoft365.com, etc.)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b159fe6e-33d0-6174-f3c3-68aaec79ee1b
* Version Independent ID: 7037e9c7-f501-5b70-8acf-1f004a06289b
* Content: [Prerequisites - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/tab-requirements)
* Content Source: [msteams-platform/tabs/how-to/tab-requirements.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/tabs/how-to/tab-requirements.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Prasad-MSFT** [comment]
Hi @AE-MS - Thanks for raising this. The Other domains along with MS Teams for the CSP header is mentioned in this section of the document from Extend a Teams personal tab across Microsoft 365 page.
https://learn.microsoft.com/en-us/microsoftteams/platform/m365-apps/extend-m365-teams-personal-tab?tabs=manifest-teams-toolkit#configure-content-security-policy-headers

Do you want these details to be reflected here as well? Please do confirm, accordingly we will redirect this to documentation team to update.

**Comment by AE-MS** [comment]
My thinking is: Any app built with a recent version of the manifest will automatically show up in all hosts. Therefore, our documentation should ensure that the guidance we give fully enables that scenario. It would be weird for a developer to create a new Teams app using a recent version of the manifest, have their app show up in hosts like Outlook and microsoft365.com, but then not work because this particular corner of the documentation didn't give a complete list of CSP header domains.

To be clear: I am not the right person to judge what the right overall docs strategy is here. You are correct that the documentation on "extending your app across M365" does list all hosts. But I can't think of a reason why some other parts of our docs shouldn't also list all the domains. I want to avoid putting developers in the situation I described above. Someone on docs can perhaps provide more input on how we want to approach this documentation comprehensively (@erikadoyle maybe can help?) -- or why we even have to maintain the list in two separate places.

**Comment by Prasad-MSFT** [comment]
@surbhigupta12 - Could you please also have a look here?

**Comment by erikadoyle** [comment]
@AE-MS, is [something like this](https://review.learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/tab-requirements?branch=pr-en-us-8820) (PR #8820) what you had in mind? We can move the CSP list into an include and reference from both articles.

@surbhigupta12 what are your thoughts about fully incorporating cross-hub prereqs and instructions into core Teams articles?

**Comment by AE-MS** [comment]
@erikadoyle yes, something like that. Boy that list is going to get hard to manage if and when more hosts come online.
