### ISSUE TITLE
Bot menus incorrectly displayed

### ISSUE THREAD

**Issue by w-piotr** [MicrosoftDocs/msteams-docs#881]
Hi I have developed chatbot for MS Teams with bot menu but as the menu is displayed every time user clicks input text box it covers up the last message send by the bot.
I have checked some other bots available in app store and it looks like the issue occurs for all bots.

Check the MindMeiser example:
![image](https://user-images.githubusercontent.com/49780873/62869242-c0ea7880-bd17-11e9-951f-7044215530c7.png)

I think it would be a good idea to make extra space between last message and input text box in case bot is designed to use menu (only for the "What can I do?" label).
It could look like that:
![image](https://user-images.githubusercontent.com/49780873/62869684-98af4980-bd18-11e9-86c8-5a553622bc06.png)

**Comment by Gousia-MSFT** [comment]
@w-piotr Thanks for reporting this. We are looking into it.

**Comment by Gousia-MSFT** [comment]
@w-piotr We have a bug for it and we are tracking it internally. Thanks!
