### ISSUE TITLE
The requirements neglected YARN

### ISSUE THREAD

**Issue by Ofer-Gal** [MicrosoftDocs/msteams-docs#8811]
The requirements neglected to say we need YARN

So I had lots of errors until I installed it.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a62dfd27-eee3-bfc7-55d6-ff325b74ef31
* Version Independent ID: a62dfd27-eee3-bfc7-55d6-ff325b74ef31
* Content: [Teams AI library quick start guide - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/teams%20conversational%20ai/conversation-ai-quick-start)
* Content Source: [msteams-platform/bots/how-to/Teams conversational AI/conversation-ai-quick-start.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/bots/how-to/Teams conversational AI/conversation-ai-quick-start.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **v-ypalikila**

**Comment by ChetanSharma-msft** [comment]
Hello @Ofer-Gal - Thanks for raising your query.
We will look into it and let you know the updates.

**Comment by Nivedipa-MSFT** [comment]
@surbhigupta12 - In this [section ](https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/teams%20conversational%20ai/conversation-ai-quick-start#set-up-your-development-environment)of the documentation better to mention that we should install [Yarn](https://yarnpkg.com/).

![image](https://github.com/MicrosoftDocs/msteams-docs/assets/92150070/20c0d4f1-33c5-4f95-a599-04282e10f7b4)

**Comment by v-ypalikila** [comment]
@Ofer-Gal 

Thank you for raising this issue. We've updated the [code sample](https://github.com/microsoft/teams-ai/tree/main/js/samples/04.ai.a.teamsChefBot) and tested it. Requested you to please try once more using this sample.

Please let us know in case you face any issues. Sharing the doc for your reference: https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/teams%20conversational%20ai/conversation-ai-quick-start.

**Comment by surbhigupta12** [comment]
@Wajeed-msft, fyi closing this issue.
