### ISSUE TITLE
Connectors

### ISSUE THREAD

**Issue by Randy759** [MicrosoftDocs/msteams-docs#8819]
Obviously your stellar developers updated the program and once again did not update any documentation.  I am trying to create connectors and of course the location shown in all online forums shows connectors under "edit channel"  The only issue is that item is not there.  Possibly you could put the new location in your documents.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 90ff2a84-a8bc-9259-d37d-622b102df75b
* Version Independent ID: e3b53e27-2946-189c-623b-9df704ea8f12
* Content: [Create an Incoming Webhook - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-incoming-webhook?tabs=dotnet)
* Content Source: [msteams-platform/webhooks-and-connectors/how-to/add-incoming-webhook.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/webhooks-and-connectors/how-to/add-incoming-webhook.md)
* Service: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by ChetanSharma-msft** [comment]
Hello @Randy759 - Thanks for raising your query.
We will look into it and let you know the updates.

**Comment by Meghana-MSFT** [comment]
We checked this at our end and as mentioned in the document we can create a connector by opening a channel and clicking on 3 dots at top right corner.

![image](https://github.com/MicrosoftDocs/msteams-docs/assets/81138249/45675d0f-0b9f-4d49-8ea9-6609bf0134a7)

Could you please let us know if you are mentioning the same?
