### ISSUE TITLE
Messages are routed to the mobile device only when signed in from both desktop and iPhone

### ISSUE THREAD

**Issue by ngrigoriev** [MicrosoftDocs/msteams-docs#882]
I am observing the following issue for quite a while:

1. Sign in to Teams using Mac OS client. Use the client to chat, meetings etc.
2. Later sign in to Teams using iOS app
3. Respond to a message using iOS app
4. Put Mac to sleep (usual work cycle, close it in the evening, open in the morning)

From this moment it seems that all incoming messages will be routed only to the mobile application, even if I am not using it at all. I can send messages using the desktop app and they do reach the recipients. However, their replies will be delivered only to the mobile app and won't even show in the desktop app's chat window.

To recover from this condition I have to sign out from the iOS app and restart the desktop app. After that I get all missing messages and everything starts working normally - until next time I sign in to the mobile app.

**Comment by Gousia-MSFT** [comment]
@ngrigoriev Thanks for reaching out. We are looking into this.

**Comment by Gousia-MSFT** [comment]
@ngrigoriev We have a ticket created for this and we are tracking it internally. Thanks!!
