### ISSUE TITLE
Under Best Practices > Tab hierarchy  both `Do` and `Don't` screenshots are identical.

### ISSUE THREAD

**Issue by gauravkeshre** [MicrosoftDocs/msteams-docs#8829]
[Enter feedback here]
Under Best Practices > Tab hierarchy 
Both `Do` and `Don't` screenshots are identical.

Link to section: https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/design/personal-apps#tab-hierarchy

Screenshot
<img width="852" alt="Screenshot 2023-06-13 at 4 30 49 PM" src="https://github.com/MicrosoftDocs/msteams-docs/assets/1673315/a5565785-0585-471c-8870-b962b2ccf651">

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ae27eac6-3289-3945-f3f1-fb9d811ff95c
* Version Independent ID: 720ebdd4-77fa-f0d4-d566-c8fff9afb08d
* Content: [Designing your personal app - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/design/personal-apps)
* Content Source: [msteams-platform/concepts/design/personal-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/design/personal-apps.md)
* Service: **msteams**
* GitHub Login: @heath-hamilton
* Microsoft Alias: **lajanuar**

**Comment by ChetanSharma-msft** [comment]
Hello @gauravkeshre - Thanks for raising your query.
We will look into it and let you know the updates.

**Comment by Nivedipa-MSFT** [comment]
@gauravkeshre - We are closing this issue for now. Please feel free to reopen if required.

**Comment by Nivedipa-MSFT** [comment]
@gauravkeshre - We are closing this issue for now. Please feel free to reopen if required.

**Comment by Nivedipa-MSFT** [comment]
@gauravkeshre - Could you please share your valuable feedback via [Microsoft Teams Developer Feedback](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR7iCOpS5_b9Nqmwx43u5rtZUOThVR081SllSR05aSDQxQ0tUMDVPTVIxTi4u) link.
