### ISSUE TITLE
Teams Desktop App won't load ASP.NET Core + Angular app with windows authentication WebSite Tab

### ISSUE THREAD

**Issue by POFerro** [MicrosoftDocs/msteams-docs#883]
Hi,

I have an ASP.NET Core + Angular App published with windows authentication, and have been trying to load it in a Teams WebSite Tab, when I click it authentication popup appears, my index.html page is loaded and shown but all other scripts included by this file example: <script src="sample.js"> fail to load reporting a 401 on the server logs.

Why is authentication succeeding on the index.html and failing on the remaining site files. My site works well when called standalone in a browser, IE or Edge or Chrome and everything works fine when accessing teams through the Teams webapp, only fails when using the Desktop App.

Can anyone help me?
Thanks and best regards

**Comment by Wajeed-msft** [comment]
Are you [Initiatiating authentication flow](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/authentication/auth-tab-aad#initiate-authentication-flow) using `microsoftTeams.authentication.authenticate()` method? Could you please share your code snippet for authentication?

**Comment by POFerro** [comment]
Hi @Wajeed-msft ,
I found the problem, Microsoft Teams Web Browser is considering script type="module" as being cross site always, regardless of the actual origin of the script being on the same site, because of this all script downloads where sent without the authentication cookies and so they failed to load with 401. 
This happened since I migrated to Angular 8 angular-cli bundling was issuing all scripts as type="module":
https://angular.io/guide/deployment#differential-loading
The solution was to configure angular bundling to issue cross-origin="use-credentials" in angular.json file as described here:
https://github.com/angular/angular-cli/issues/15125
now everything is working fine.

I'm closing this issue, sorry for the inconvenience :)
Thanks and best regards
