### ISSUE TITLE
Authorization and Callback pages question

### ISSUE THREAD

**Issue by bcote** [MicrosoftDocs/msteams-docs#884]
I found that the Authorization page and the Callback page must be the same as the Redirect Url for the Application Registration in Azure AD (Authentication blade). I tried having more than one Redirct Url for the same domain, and this did not work. If I only listed the Callback page url, I would get a blank login page. When I combined the 'simple-start' and 'simple-end' logic on one page I was able to authenticate and obtain an Access Token (which I then used to call a Microsoft Graph API). My app was not in Node.js, it is an Asp.Net MVC with the authentication logic in javascript.

Am I missing something, or is this documentation out of date?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d939a56-d1be-f2a2-3454-0f0c5144bc27
* Version Independent ID: ec4d5574-ddeb-9408-ad82-d86507a5111b
* Content: [Authentication for tabs using Azure Active Directory - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/authentication/auth-tab-aad#feedback)
* Content Source: [msteams-platform/concepts/authentication/auth-tab-AAD.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/authentication/auth-tab-AAD.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Wajeed-msft** [comment]
Multiple redirect URLs are supported for the app. What error are you getting?
![image](https://user-images.githubusercontent.com/31851992/63145613-b4b33380-c015-11e9-831a-9268e4021133.png)

Regarding the blank page, could you please share your app manifest which we could try at our end?

**Comment by bcote** [comment]
[TeamsBluescape.zip](https://github.com/MicrosoftDocs/msteams-docs/files/3517897/TeamsBluescape.zip)

in Views/Home/Index.cshtml, I navigate to /Authentication/simple-start.html
In the simple-start.html, I had to set the redirecUrl to /Authenticate/simple-start, and then handle the callback on that same page. If I changed the redirectUrl to /Authenticate/simple-end, and put both simple-start and simple-end as callback urls the code would not work. If I only put simple-end as the callback url, the Microsoft login dialog would be blank.

Let me know if I can provide any other explanations. I zipped the code up.

**Comment by Trinetra-MSFT** [comment]
@bcote, We tried your sample code and successfully able to get the access token from Azure AD for multiple redirect URI.

**Setting Up multiple redirect URI in Azure AD authentication**
![image](https://user-images.githubusercontent.com/50989436/64014447-c03b4a00-cb3f-11e9-94e7-2752724403f0.png)

**Authentication access token for web view**
![image](https://user-images.githubusercontent.com/50989436/64014608-32139380-cb40-11e9-8515-412bc2d876d3.png)


**Access token for Desktop View** 
![image](https://user-images.githubusercontent.com/50989436/64014659-4fe0f880-cb40-11e9-8b13-493d78dc659f.png)


 Could you please try with [AuthBot.zip](https://github.com/OfficeDev/microsoft-teams-sample-auth-node/blob/master/manifest/AuthBot.zip) manifest and make your you have enabled checkbox Access Token & ID Tokens for implicit grant flow in Azure AD authentication?

**Comment by Gousia-MSFT** [comment]
@bcote Please re-open if you are still facing issues.
