### ISSUE TITLE
SharePoint extension commands for Teams Tab

### ISSUE THREAD

**Issue by v-nikhilsoma** [MicrosoftDocs/msteams-docs#8842]
The point below was missing in the documentation. Could you please add the same accordingly?
SharePoint extension commands are not supported in the Teams files tab. Only we can [add a SharePoint page, list, or document library as a tab in Teams](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2f%2fsupport.microsoft.com%2fen-us%2foffice%2fadd-a-sharepoint-page-list-or-document-library-as-a-tab-in-teams-131edef1-455f-4c67-a8ce-efa2ebf25f0b&data=05%7c01%7cv-sutumm%40microsoft.com%7c3de1c8a46d8f47eea28208da73df293c%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c637949699731514350%7cUnknown%7cTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7c3000%7c%7c%7c&sdata=NzaUtN8Eu6kAbnIyMXp%2B%2Bw%2fEBgra30NBvZmswEpoLnk%3D&reserved=0).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 41c93c1e-c426-148c-a545-f8bd5b3763ff
* Version Independent ID: afcc83c4-12c0-bab6-1cec-61ac463b4f60
* Content: [Add Teams tab to SharePoint - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/tabs-in-sharepoint)
* Content Source: [msteams-platform/tabs/how-to/tabs-in-sharepoint.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/tabs/how-to/tabs-in-sharepoint.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **surbhigupta**

**Comment by Prasad-MSFT** [comment]
Hi @surbhigupta12 - Could you please help here updating the document as mentioned by adding a note?
