### ISSUE TITLE
Supported Schema version for Adaptive card should be declared in Documentation 

### ISSUE THREAD

**Issue by cagrimunyas** [MicrosoftDocs/msteams-docs#8843]
Docs should expicitly show the latest version of the Adaptive card schema Teams support. Otherwise developers had to use Adaptive cards trial and error basis.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1a102a61-02c0-8a7d-d823-06bd894c6639
* Version Independent ID: fcfc4f00-f3c3-1cf0-2a4a-c7fda27be1a1
* Content: [Designing Adaptive Cards for your app - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/design-effective-cards?tabs=design)
* Content Source: [msteams-platform/task-modules-and-cards/cards/design-effective-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/task-modules-and-cards/cards/design-effective-cards.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **surbhigupta**

**Comment by Nivedipa-MSFT** [comment]
@cagrimunyas - Thanks for reporting your issue. We will check this and update the document accordingly.

**Comment by Nivedipa-MSFT** [comment]
@cagrimunyas - Could you please let us know where exactly you want to show the latest supported schema version for adaptive card in this document, so that we can redirect to the documentation team to update?
