### ISSUE TITLE
[Feedback] This appears to be targeting the wrong API.

### ISSUE THREAD

**Issue by v-npaladugu** [MicrosoftDocs/msteams-docs#8850]
This appears to be targeting the wrong API.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4ad9f167-7d29-f933-7b47-60bd744899b1
* Version Independent ID: 8097fcbd-adcc-ce49-a378-426c65af9296
* Content: [Send proactive messages - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/send-proactive-messages?tabs=dotnet)
* Content Source: [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/bots/how-to/conversations/send-proactive-messages.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **surbhigupta**

**Comment by sayali-MSFT** [comment]
@v-npaladugu - Thanks for reporting your issue.
Could you please elaborate more on your requirement?

**Comment by sayali-MSFT** [comment]
@v-npaladugu -We have checked the API in this document but did not find any wrong API.
Looks like document is already updated.

We are closing this issue for now, please feel free to reopen it, if required.
