### ISSUE TITLE
[Feedback] Good example but you're missing the importing which make it confusing

### ISSUE THREAD

**Issue by v-npaladugu** [MicrosoftDocs/msteams-docs#8853]
Good example but you're missing the importing which make it confusing

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4e5ad801-f835-7e94-fe49-fab64930e662
* Version Independent ID: 4e5ad801-f835-7e94-fe49-fab64930e662
* Content: [Build a dashboard tab app - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/build-a-dashboard-tab-app)
* Content Source: [msteams-platform/tabs/how-to/Build-a-dashboard-tab-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/tabs/how-to/Build-a-dashboard-tab-app.md)
* Service: **msteams**
* GitHub Login: @v-silakshmi
* Microsoft Alias: **surbhigupta**

**Comment by Nivedipa-MSFT** [comment]
@v-npaladugu - Could you please share the developer's alias name so that we can ask for the details of the issue here?

**Comment by Prasad-MSFT** [comment]
Hi @v-npaladugu - Could you please let us know what exactly do we need to add in this document page? I am not quite clear on this
