### ISSUE TITLE
[Feedback] You created a channel called 'Incoming webhook' to send messages to, but then you sent one message to the General channel. How do we specify channel?

### ISSUE THREAD

**Issue by v-npaladugu** [MicrosoftDocs/msteams-docs#8854]
1. You created a channel called 'Incoming webhook' to send messages to, but then you sent one message to the General channel. How do we specify channel?

2. The documentation link in the teams app for mac points to a page at outlook.dev

outlook.dev is using a VERY outdated cert

users are unable to access outlook.dev because it uses HSTS which blocks access because of the expired cert

The "feedback" link inside the teams app webhook UI is broken, when trying to submit feedback it produces an error: "The requested user tt**EMAIL ADDRESS REMOVED**tt is invalid"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 90ff2a84-a8bc-9259-d37d-622b102df75b
* Version Independent ID: e3b53e27-2946-189c-623b-9df704ea8f12
* Content: [Create an Incoming Webhook - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-incoming-webhook?tabs=dotnet)
* Content Source: [msteams-platform/webhooks-and-connectors/how-to/add-incoming-webhook.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/webhooks-and-connectors/how-to/add-incoming-webhook.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **surbhigupta**

**Comment by sayali-MSFT** [comment]
@v-npaladugu - Thanks for reporting your issue.
We will check this at our end and will get back to you.

**Comment by sayali-MSFT** [comment]
To send the message to specific channel,
1. Open the channel in which you want to add the webhook and select ••• from the upper-right corner.
2. Select Connectors from the dropdown menu.
3. Search for Incoming Webhook and select Add.
4. Select Configure, provide a name, and upload an image for your webhook if necessary.
5. Copy and save the unique webhook URL present in the dialog. The URL maps to the channel and you can use it to send 
    information to Teams.
7. Select Done.

We are also checking the feedback Link on Incoming webhook page which is working fine.


We are closing this issue for now, Please feel free to reopen it, if required.
