### ISSUE TITLE
[Feedback] format that is mentioned in this (and other) pages is not correct

### ISSUE THREAD

**Issue by v-npaladugu** [MicrosoftDocs/msteams-docs#8856]
After trying for days to make "mentions" work when submitting adaptive card json over graph API, I have discovered that the format that is mentioned in this (and other) pages is not correct.
See: https://poszytek.eu/en/microsoft-en/office-365-en/powerautomate-en/how-to-mention-tags-users-channels-and-teams-using-power-automate/
for a format that works for me.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 001a12ea-30fa-d626-18a9-02a518bfb37f
* Version Independent ID: e5f5f69e-66e9-d1b2-e19a-485d0ffcd6fa
* Content: [Text formatting in cards - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?tabs=adaptive-md%2Cdesktop%2Cconnector-html)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-format.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/task-modules-and-cards/cards/cards-format.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **surbhigupta**

**Comment by sayali-MSFT** [comment]
@v-npaladugu -Thanks for reporting your issue.
We will check this at our end and will get back to you.
