### ISSUE TITLE
[Feedback] update the changelog

### ISSUE THREAD

**Issue by v-npaladugu** [MicrosoftDocs/msteams-docs#8857]
Please update the changelog so we know the differences between 1.16 and 1.15. Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0f94a488-d636-92b3-21eb-c88744c8f272
* Version Independent ID: 7b3413f4-9ade-accf-5cb2-83fead11a32a
* Content: [Manifest schema reference - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema)
* Content Source: [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/resources/schema/manifest-schema.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **surbhigupta**

**Comment by Nivedipa-MSFT** [comment]
@v-npaladugu - Thanks for reporting your issue. We will check and act accordingly.

**Comment by Prasad-MSFT** [comment]
Change log for Schema v1.16 is added now. So, closing the thread.
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/62237649/7dcf028e-69be-4925-91ea-d9ba3030f0a8)
