### ISSUE TITLE
[Feedback] schema validations in JSON file

### ISSUE THREAD

**Issue by v-npaladugu** [MicrosoftDocs/msteams-docs#8858]
Hi, I've activated schema validations on my JSON files, and I got this error:

Invalid regular expression: /^activities.activityTypes\[\b([0-9]|[1-8][0-9]|9[0-9]|1[01][0-9]|12[0-7])\b]\.description$/: Lone quantifier brackets

Indeed, in https://developer.microsoft.com/en-us/json-schemas/teams/v1.16/MicrosoftTeams.Localization.schema.json
the 2 entries for "activities.activityTypes" have an invalid regexp.
There is a "\\" missing before the last "]" in both regexps.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2a8d718e-46c9-d26b-0483-635832903842
* Version Independent ID: 32be5df3-2749-3854-fa01-a03e72e96696
* Content: [Localize JSON schema reference - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/resources/schema/localization-schema)
* Content Source: [msteams-platform/resources/schema/localization-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/resources/schema/localization-schema.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **surbhigupta**

**Comment by sayali-MSFT** [comment]
@v-npaladugu - Thanks for reporting your issue.
We will check this at our end and will get back to you.

**Comment by sayali-MSFT** [comment]
@v-npaladugu -Checked the given JSON file and the document regular expression is correct.
Document is already updated.

We are closing this issue for now, please feel free to reopen it, if required.
