### ISSUE TITLE
[Feedback] results in an error. It's false.

### ISSUE THREAD

**Issue by v-npaladugu** [MicrosoftDocs/msteams-docs#8859]
Following the documentation results in an error. It's false.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 28316a67-22fa-8a05-1ae0-fbe1c5720ef9
* Version Independent ID: 8a250e46-2a30-af86-839d-9f83a8b48041
* Content: [Create and send messages - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-using?tabs=cURL)
* Content Source: [msteams-platform/webhooks-and-connectors/how-to/connectors-using.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/webhooks-and-connectors/how-to/connectors-using.md)
* Service: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **surbhigupta**

**Comment by Meghana-MSFT** [comment]
Thank you for reporting this issue, we will check this and get the doc updated if required.

**Comment by Meghana-MSFT** [comment]
We have sent the messages by following the document, the messages were sent successfully. We are closing this issue for now. Please feel free to reach out to us if you face any issue further.
