### ISSUE TITLE
Can we localization the app that uploaded to the teams by AppStudio

### ISSUE THREAD

**Issue by searlin** [MicrosoftDocs/msteams-docs#886]
So my app is not be published to the app store,  just manually upload the package to the teams, can we use this page's instruction to localization the app, I just did a test, and it doesn't work. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73e76b9c-61a0-55ab-60cd-685d6cf9c1c2
* Version Independent ID: bf7a1892-4468-72da-8f94-12a6f3323f53
* Content: [Localization for Team apps - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/publishing/apps-localization#feedback)
* Content Source: [msteams-platform/publishing/apps-localization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/publishing/apps-localization.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by MattSFT** [comment]
Hi @searlin ,

You cannot currently add localization to your app from within App Studio; we are working on this feature. However, you can export your package from App Studio and add the localization files manually. Then you can sideload your application from the upload a custom app button in the store:
![image](https://user-images.githubusercontent.com/29067893/62988812-8d344f00-bdfa-11e9-963a-7ce626e2c44c.png)

**Comment by searlin** [comment]
Thanks @MattSFT , it works perfect!
