### ISSUE TITLE
[Feedback] out of date

### ISSUE THREAD

**Issue by v-npaladugu** [MicrosoftDocs/msteams-docs#8860]
out of date

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4b62aabd-f012-24c9-0edf-e840b20a9dfc
* Version Independent ID: a5c79257-d3a7-c9b5-8a98-7e1495b08a7e
* Content: [Format your bot messages - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/format-your-bot-messages)
* Content Source: [msteams-platform/bots/how-to/format-your-bot-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/bots/how-to/format-your-bot-messages.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **anclear**

**Comment by sayali-MSFT** [comment]
@v-npaladugu - Could you please elaborate more on your requirement?

**Comment by v-npaladugu** [comment]
Hi @sayali-MSFT, we have received only this as feedback, we don't have more details on this.
