### ISSUE TITLE
Incorrect page for these two deeplink topics?

### ISSUE THREAD

**Issue by vishrutshuklaMSFT** [MicrosoftDocs/msteams-docs#8861]
The below 2 sections on this page make more sense to include on the Deep link to application page in the same TOC. As these are not workflows inside of Teams but app surface areas.

[Generate a deep link to share content to stage in meetings](https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-link-workflow?tabs=teamsjs-v2#generate-a-deep-link-to-share-content-to-stage-in-meetings)

[Deep link to meeting side panel](https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-link-workflow?tabs=teamsjs-v2#deep-link-to-meeting-side-panel)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 98d88f26-f11f-4810-162a-40ca552be3e3
* Version Independent ID: 98d88f26-f11f-4810-162a-40ca552be3e3
* Content: [Deep link to a workflow in Teams - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-link-workflow?tabs=teamsjs-v2)
* Content Source: [msteams-platform/concepts/build-and-test/deep-link-workflow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/build-and-test/deep-link-workflow.md)
* Service: **msteams**
* GitHub Login: @v-npaladugu
* Microsoft Alias: **surbhigupta**
*

**Comment by Nivedipa-MSFT** [comment]
@vishrutshuklaMSFT - Thanks for reporting your issue. We will confirm this with engineering team and will update accordingly.
