### ISSUE TITLE
[Feedback] Teams stop working with the Elgato Stream Deck

### ISSUE THREAD

**Issue by v-npaladugu** [MicrosoftDocs/msteams-docs#8862]
Not much info here. Why did Teams stop working with the Elgato Stream Deck? What port does the websocket connect on? It used to connect on 8124 back when it still worked.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0b255dfb-18c1-ea36-0bf4-a61ce9ddb2ab
* Version Independent ID: 0b255dfb-18c1-ea36-0bf4-a61ce9ddb2ab
* Content: [Integrate existing third-party APIs - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/toolkit/add-api-connection)
* Content Source: [msteams-platform/toolkit/add-API-connection.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/add-API-connection.md)
* Service: **msteams**
* GitHub Login: @MuyangAmigo
* Microsoft Alias: **zhany**

**Comment by Meghana-MSFT** [comment]
Thank you for reporting this issue, we will check this and get the doc updated if required.

**Comment by Meghana-MSFT** [comment]
Could you please share more details on this issue? The above-mentioned doc does not mention anything regarding Elgato Stream Deck and web socket.

**Comment by v-npaladugu** [comment]
Hi @Meghana-MSFT , we don't any more details on this.

**Comment by Meghana-MSFT** [comment]
We are closing this issue for now, please reach out to us if you face any further issue. Thank you.
