### ISSUE TITLE
[Feedback] Not up to date for Teams SDK v2

### ISSUE THREAD

**Issue by v-npaladugu** [MicrosoftDocs/msteams-docs#8866]
Not up to date for Teams SDK v2

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f40d5208-a7ae-330a-1365-9b774ca9dcaf
* Version Independent ID: a44e2980-4ed7-636c-0141-8b1e944971bb
* Content: [Use Task Modules in Microsoft Teams tabs - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/task-modules/task-modules-tabs?tabs=teamsjs1%2Cteamsjs2)
* Content Source: [msteams-platform/task-modules-and-cards/task-modules/task-modules-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/task-modules-and-cards/task-modules/task-modules-tabs.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **surbhigupta**

**Comment by Meghana-MSFT** [comment]
Thank you for reporting this issue, we will check this and get the doc updated if required.

**Comment by Meghana-MSFT** [comment]
The document seems to be properly updated for both V1 and V2. Could you please share more details on which part of the doc is not updated?

**Comment by v-npaladugu** [comment]
Hi @Meghana-MSFT, we don't have any more details at our end.

**Comment by Meghana-MSFT** [comment]
We are closing this issue for now, please feel free to reach out to us if you face any further issue. Thank you.
