### ISSUE TITLE
Navigate from custom tab to Files or/and Conversation Tab

### ISSUE THREAD

**Issue by MagtheRag** [MicrosoftDocs/msteams-docs#887]
Is there a way to target the Conversation or the Files tab ?
We have a custom tab that would like to navigate to the Files tab. 
We can't get the tab through the microsoftTeams.getTabInstances or the graph as it only returns custom tabs. 

I puzzled together a link which can be used with microsoftTeams.executeDeepLink :
https://teams.microsoft.com/_?tenantId=${tenantId}#/files/General?groupId=${groupId}&threadId=${threadId}&ctx=channel but then it will not open the tab in the native client but open it in the browser (web-app) instead. 

Is there a better way to get to these tabs or is it on the way ?

**Comment by Gousia-MSFT** [comment]
@MagtheRag Currently, this is not available. We are working on updating the docs to add Deeplinking to files but we do not have an ETA for this.

**Comment by MagtheRag** [comment]
Is there not a need for navigating between tabs in the native client, not just deep linking to files (without opening a browser from the native client)? 

In order to make the UX unified and understandable we should implement a pattern that make sense to the user and not have islands with functionality that only confuses and do not help the users in their daily tasks. Just being able to navigate to custom tabs does not make sense to me as it breaks a pattern where the user should freely being able to jump to conversations or the files tab with a preferred help from the application.
 
Preventing interactions between tabs is totally understandable for security reasons but being able to guide the user by selecting different tabs, when the user choses from where ever he currently is, is a must. 

Teams is a good platform but needs to open up certain things when it comes to the possibility to guide the user through all the applications. In my opinion this could be a good start.

**Comment by Gousia-MSFT** [comment]
@MagtheRag Thanks for sharing your feedback. We will consider your pointers and are working on improvising the experience of Navigating between tabs.
