### ISSUE TITLE
The parameters property under the composeExtensions.commands section is marked as required but it is not

### ISSUE THREAD

**Issue by AE-MS** [MicrosoftDocs/msteams-docs#8871]
I can make a completely valid and working composeExtensions.commands entry without having to specify a parameters property, e.g.,

```
                {
                    "id": "showDialog",
                    "context": [
                        "compose"
                    ],
                    "description": "Show a dialog",
                    "title": "Show Dialog",
                    "type": "action",
                    "taskInfo": {
                        "title": "Dialog Title",
                        "height": "medium",
                        "width": "medium",
                        "url": "https://blahblah"
                    }
                },
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0f94a488-d636-92b3-21eb-c88744c8f272
* Version Independent ID: 7b3413f4-9ade-accf-5cb2-83fead11a32a
* Content: [Manifest schema reference - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema)
* Content Source: [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/resources/schema/manifest-schema.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **surbhigupta**

**Comment by sayali-MSFT** [comment]
@AE-MS - Thanks for reporting your issue.
We will check this at our end and update the document accordingly.

**Comment by ChetanSharma-msft** [comment]
Hello @surbhigupta12 - Please help to update the documentation that parameter property is not a required property in the App Manifest. Please help to move the required mark from the below: 
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/59052547/cabb11e9-d306-4917-bacb-856a30756a8c)
