### ISSUE TITLE
Config example HTML is missing a closing </head>

### ISSUE THREAD

**Issue by johnnydecimal** [MicrosoftDocs/msteams-docs#8876]
The example code is missing a closing `</head>` tag.

```html
<head>
    <script src="https://res.cdn.office.net/teams-js/2.2.0/js/MicrosoftTeams.min.js" 
      integrity="sha384yBjE++eHeBPzIg+IKl9OHFqMbSdrzY2S/LW3qeitc5vqXewEYRWegByWzBN/chRh" 
      crossorigin="anonymous" >
    </script>
<body>
```

**Comment by sayali-MSFT** [comment]
@johnnydecimal  -Thanks for reporting your issue.
We will check this at our end and will get back to you.

**Comment by johnnydecimal** [comment]
Oh sorry, didn’t see that first message.

Hmm I thought that clicking the feedback button from the document page embedded a link to that document here? I’ll have to remember which page it was on.

**Comment by johnnydecimal** [comment]
Yeah I’m not going to remember, sorry!
