### ISSUE TITLE
How to make bot work in my Custom Microsoft Team App?

### ISSUE THREAD

**Issue by EthanWang90** [MicrosoftDocs/msteams-docs#888]
my bot id: **7367666f-abc2-4c19-91c6-aa1bcad01baa**
my bot pwd: **pcYZBx4H6[z4kqis0jShF.n]NDZlrko-**

I want to create a Custom Microsoft Teams App which, for example, can push message card to channel when there is an update in my server.
I followed the [official tutorial](https://docs.microsoft.com/en-us/microsoftteams/platform/get-started/get-started-dotnet-app-studio#), the tabs functionality works fine, however the bot didn't echo any message cards.

I initially tried C# version tutorial, I was using the ngrok to build a tunnel and run the code locally, I checked every key points in this process:

1. In Manifest editor, I generated and registered a new bot and its password;
2. I set Bot endpoint address to "https://94f87d3e.ngrok.io/messages" (my own tunnel url + "/messages") as instructed in official docs;
3. In Messaging extensions, use the same bot registered in step 1 as instructed;
4. Then I go back to my local app, update credential with newly created bot id and key, also, as instructed.
![host credential](https://docs.microsoft.com/en-us/microsoftteams/platform/assets/images/get-started/get-started-net-azure-add-keys.png)
5. Well, of course, the tabs still work cause it has nothing to do with bots part.
6. However, the bot didn't work, when I @mention my test bot in channel where I install the bot in, and type some random text, it just didn't echo back any message cards. Which should be act like below:
![expected](https://docs.microsoft.com/en-us/microsoftteams/platform/assets/images/samples-hello-world-bot.png)

Also, the app has this error message "Unable to reach app. Please try again."

**Comment by clearab** [comment]
Hi,
Can you please make sure your bot endpoint address is using /api/messages not just /messages?

Thanks,
Andrew
,

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by EthanWang90** [comment]
Thanks Andrew, now I receive the bot reply message, it was my mistake, however I get another error message now "Something went wrong. Please try again." when I run my command defined in manifest.

Is it possible to @mention someone using Team App? I use <at></at> wrap my email, it echos back my email with no mention, I only tried @mention team member using Flow Team Connector. Webhook didn't work, if I can use app to @mention my end users, then they don't need worry to provide their credential in my flow connector, or learn something to set up their own flow.
