### ISSUE TITLE
Issue with deeplink in adaptive card

### ISSUE THREAD

**Issue by Serginyo90** [MicrosoftDocs/msteams-docs#8881]
We have Custom Tab App with Bot (https://learn.microsoft.com/en-us/microsoftteams/apps-in-teams#custom-apps-created-within-an-organization-for-internal-use)
The deeplink worked for a long time (around 5 months), but it stopped functioning a few days ago. I've provided a zip file so that you can attempt to install the app and receive proactive messages.
[dev_2.5.1.zip](https://github.com/MicrosoftDocs/msteams-docs/files/11790001/dev_2.5.1.zip)
Deep link: [link](https://teams.microsoft.com/_#/l/task/c2455d2b-4d4b-42ec-83bc-53c7fdf31b67?url=https:%2F%2Fassets.dev.prohabits.com%2Fmst%2Fhelpers%2FwistiaVideo.html%3Fheight%3D440%26width%3D750%26videoId%3Duqkw3t8txc%26title%3DWelcome%20to%20ProHabits&deeplinkId=4c7b4ced-8e8f-4b10-a9e6-64927bc75c25)

Please attempt to reproduce the issue and let me know if you need any additional information.

P.S. Make sure to grant permission for sending activity after installing the app
![Screenshot 2023-06-19 at 18 49 03](https://github.com/MicrosoftDocs/msteams-docs/assets/20815176/2f529026-aad1-46bc-930c-5e55080dab95)
![Screenshot 2023-06-19 at 18 47 46](https://github.com/MicrosoftDocs/msteams-docs/assets/20815176/f7645f4e-2922-4ffa-8802-2fd99c188f81)

**Comment by Prasad-MSFT** [comment]
@Serginyo90 - Thanks for raising this. We will repro this at our end and revert back to you shortly.

**Comment by Prasad-MSFT** [comment]
@Serginyo90 - On installing the app zip shared, we are able to access the app but we are not getting any proactive message or notification. Is it deployed? Also, as you mentioned 'Make sure to grant permission for sending activity after installing the app' from where can we get this enabled?

**Comment by Prasad-MSFT** [comment]
@Serginyo90 - I followed the mentioned steps and consented the permission. Still after installing the app not getting any notification/message.

**Comment by Serginyo90** [comment]
@Prasad-MSFT is it your user - e8c9468f-7f42-4df0-b2e5-9e50ceb21f1a  and tenant id 72f988bf-86f1-41af-91ab-2d7cd011db47? 
I tried to request information about user using https://graph.microsoft.com/v1.0/users/e8c9468f-7f42-4df0-b2e5-9e50ceb21f1a

And received http error 401
`{
	"error": {
		"code": "Authorization_IdentityNotFound",
		"message": "The identity of the calling application could not be established.",
		"innerError": {
			"date": "2023-06-20T10:30:57",
			"request-id": "86ceb551-0fce-450e-88a2-d9589dae643c",
			"client-request-id": "86ceb551-0fce-450e-88a2-d9589dae643c"
		}
	}
}`

Usually it means that bot doesn't see your user because permission.

**Comment by Prasad-MSFT** [comment]
@Serginyo90 - The user via which i was trying out has id `e652dd92-dd63-4fcc-b5b2-2005681e8e9f` and the tenant id is `aa923623-ae61-49ee-b401-81f414b6ad5a`

**Comment by Serginyo90** [comment]
@Prasad-MSFT I checked and bot has ability to get info about user. 
It is weird but I checked logs and don't receive any "onMembersAdded" events related to `e652dd92-dd63-4fcc-b5b2-2005681e8e9f` but I should. Correct?

Could you uninstall and install the app again please?

**Comment by Serginyo90** [comment]
@Prasad-MSFT I think @sayali-MSFT also faced with current issue and said that " it is showing the card with non-Admin user."
Please look here https://github.com/MicrosoftDocs/msteams-docs/issues/8607#issuecomment-1566968266 . MAybe it can help.

**Comment by Prasad-MSFT** [comment]
@Serginyo90 - I am checking this using Teams web client in windows. As suggested, I uninstalled the app and added it again using admin credentials and allowed the permissions and consent. Then I added the app using non-admin account and got adaptive card message having deeplink. On clicking the link getting below error:
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/62237649/98750520-20b7-4fe2-859e-e65d0c8983e4)
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/62237649/a7032c1a-ceb3-42f3-a9ac-937d2093406c)

**Comment by Serginyo90** [comment]
@Prasad-MSFT yes, this this issue. 
But if you copy the dee-link from Adaptive Card and open in new tab you can see that video is opened in task module correctly.

**Comment by Serginyo90** [comment]
@Prasad-MSFT I shared in first message. Let me duplicate or you can copy from your Adaptive Card 
`https://teams.microsoft.com/_#/l/task/c2455d2b-4d4b-42ec-83bc-53c7fdf31b67?url=https:%2F%2Fassets.dev.prohabits.com%2Fmst%2Fhelpers%2FwistiaVideo.html%3Fheight%3D440%26width%3D750%26videoId%3Duqkw3t8txc%26title%3DWelcome%20to%20ProHabits&deeplinkId=4c7b4ced-8e8f-4b10-a9e6-64927bc75c25`

**Comment by Serginyo90** [comment]
@Prasad-MSFT here is format which we send in Adaptive Card 
`https://teams.microsoft.com/l/task/c2455d2b-4d4b-42ec-83bc-53c7fdf31b67?url=https%3A%2F%2Fassets.dev.prohabits.com%2Fmst%2Fhelpers%2FwistiaVideo.html%3Fheight%3D440%26width%3D750%26videoId%3Duqkw3t8txc%26title%3DWelcome%20to%20ProHabits`

**Comment by Prasad-MSFT** [comment]
We have raised a bug for this issue and assigned to respective engineering team. 
We will inform you once we get any further update from engineering team. Thanks!

**Comment by Serginyo90** [comment]
@Prasad-MSFT Looks like it has started work

**Comment by Serginyo90** [comment]
@Prasad-MSFT  Looks like it has started work
