### ISSUE TITLE
Can't see 'Auto install approved apps'

### ISSUE THREAD

**Issue by KaratLee** [MicrosoftDocs/msteams-docs#8885]
According to this doc: https://learn.microsoft.com/en-us/microsoftteams/auto-install-approved-apps
Enable the Auto install approved apps feature in Teams admin center, but i can't find ''Auto install approved apps'. I am global admin. 
<img width="917" alt="image" src="https://github.com/MicrosoftDocs/msteams-docs/assets/37133480/b8ede35e-fcff-48e3-aff1-203156fc369f">

<img width="1372" alt="image" src="https://github.com/MicrosoftDocs/msteams-docs/assets/37133480/d500441e-f82f-4c4d-8f0e-a8d662bbf7ea">

**Comment by Meghana-MSFT** [comment]
Thank you for reporting this issue, we will check this and get back to you.

**Comment by Meghana-MSFT** [comment]
@KaratLee - The feature is gradually being made Generally Available (GA) to all tenants. That might be the reason for "Auto install approved apps" being invisible.   
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/81138249/6c38fa98-254d-4639-8b7d-1bb1a814c007)

**Comment by KaratLee** [comment]
@Meghana-MSFT Our tenantId is 59a1f10b-8245-45f6-8690-1b7821cc7630, can you help open this new feature for our tenant? Thank you very much.

**Comment by Meghana-MSFT** [comment]
@KaratLee - We will check internally and get back to you. Thank you.

**Comment by Meghana-MSFT** [comment]
@KaratLee - Could you please confirm if you are able to see the 'Auto install approved apps' option?
