### ISSUE TITLE
Unable to preview word documents from search results

### ISSUE THREAD

**Issue by xu-zheng** [MicrosoftDocs/msteams-docs#889]
Starting this week 08/11/2019, our users found that word documents (docx and doc) found using search can't be previewed in both the web and desktop apps. Excel and PowerPoint files, as well as PDF and video files, can still be previewed.

**Comment by xu-zheng** [comment]
Added clarification: Word documents can still be previewed when going to a directory and clicking on the file.

Preview is only unavailable when clicking on Word documents in search results.

**Comment by Abhijit-MSFT** [comment]
@xu-zheng - I see docx/doc are not searchable. I am checking it internally.

**Comment by derkenblosh** [comment]
same issue here ... 8/11/2019 ... no preview of docx files from search available... xlsx files still have preview. (tested with multiple sharepoints/teams, same results)

**Comment by Abhijit-MSFT** [comment]
@xu-zheng, @derkenblosh - Can you please help me with screenshot. My understand of this issue was different.

**Comment by xu-zheng** [comment]
![image](https://user-images.githubusercontent.com/29580364/63535777-14eb1f00-c4c7-11e9-9f05-ab106f679b0a.png)
When you search for a MS Word file, you can't preview the file by clicking on the file in the results. Preview used to work and still works for Excel and PowerPoint files but **NOT** Word files. 

Also, Word files can still be preview by going to the directory and clicking the files directly (w/o searching)
![image](https://user-images.githubusercontent.com/29580364/63536441-7364cd00-c4c8-11e9-8781-438b76297e11.png)

**Comment by Abhijit-MSFT** [comment]
@xu-zheng, @derkenblosh - Thanks for reporting this issue. We have raised a bug and team is looking into it.

**Comment by Abhijit-MSFT** [comment]
we tracking this bug internally.
