### ISSUE TITLE
Teams Toolkit for Visual Studio 2022

### ISSUE THREAD

**Issue by robertstewartnz** [MicrosoftDocs/msteams-docs#8892]
Hi There,

This article refers to Visual Studio Code. I'm using Visual Studio 2022 and have the teams toolkit installed can we use that instead of VS Code?

Cheers
-Rob 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a62dfd27-eee3-bfc7-55d6-ff325b74ef31
* Version Independent ID: a62dfd27-eee3-bfc7-55d6-ff325b74ef31
* Content: [Teams AI library quick start guide - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/teams%20conversational%20ai/conversation-ai-quick-start)
* Content Source: [msteams-platform/bots/how-to/Teams conversational AI/conversation-ai-quick-start.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/bots/how-to/Teams conversational AI/conversation-ai-quick-start.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **v-ypalikila**

**Comment by Nivedipa-MSFT** [comment]
@robertstewartnz - Yes, you can use the Teams Toolkit extension for Visual Studio 2022 instead of Visual Studio Code. The Teams Toolkit is a development extension provided by Microsoft that allows developers to create, debug, and deploy Microsoft Teams apps directly from within Visual Studio.

**Comment by Nivedipa-MSFT** [comment]
@robertstewartnz - We are closing this issue for now. Please feel free to reopen it if necessary.
