### ISSUE TITLE
APP_ID copied from manifest will not work to open task module using deep link approach

### ISSUE THREAD

**Issue by SubbaReddi** [MicrosoftDocs/msteams-docs#8896]
Hi Team,

Following format was given to open task module using deep link approach:
https://teams.microsoft.com/l/task/APP_ID?url=<TaskInfo.url>&height=<TaskInfo.height>&width=<TaskInfo.width>&title=<TaskInfo.title>&completionBotId=BOT_APP_ID

And APP_ID copied from manifest is not working. It must be copied from Teams admin center or Read App id using Graph API. So, the following details mentioned in documentation is incorrect:
The [ID](https://learn.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema#id) of the app invoking the task module.

App id given in manifest and app id from teams admin center is same for Third party apps. So, it would work for Third party apps but not for LOB/Custom apps.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 059b1a94-8235-8801-b9e0-ac6fbc485a7c
* Version Independent ID: 059b1a94-8235-8801-b9e0-ac6fbc485a7c
* Content: [Deep link to an application - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-link-application?tabs=teamsjs-v2#deep-link-to-open-a-task-module)
* Content Source: [msteams-platform/concepts/build-and-test/deep-link-application.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/build-and-test/deep-link-application.md)
* Service: **msteams**
* GitHub Login: @v-npaladugu
* Microsoft Alias: **surbhigupta**

**Comment by ChetanSharma-msft** [comment]
Hello @SubbaReddi - Thanks for raising this issue.
We will look into it and redirect to doc team.

**Comment by Prasad-MSFT** [comment]
Hi @surbhigupta12 - Could you please help here mentioning in the doc that, The **APP_ID** used here is App id given in manifest for Third party apps but for LOB/Custom apps, it must be copied from Teams admin center or read App id using [Graph API](https://learn.microsoft.com/en-us/graph/api/application-list?view=graph-rest-1.0&tabs=http#examples).

Also mention that App id given in manifest and App id from Teams admin center is same for Third party apps. But for LOB/Custom apps, it is different. So, it is recommended to take the id from Teams admin center.

**Comment by v-rmvv** [comment]
Hi @SubbaReddi, 

Request you to please approve the PR. 

Thanks
