### ISSUE TITLE
Adaptive Card - Duplicate choices and rendering bug with filtered Input.ChoiceSet 

### ISSUE THREAD

**Issue by jvrasa** [MicrosoftDocs/msteams-docs#8904]
Hello, I'm using **Adaptive card 1.5** in **Microsoft Teams** and I'm facing an issue with `Input.ChoiceSet` in `Filtered` style. 
I have options with the same titles but different values. When I click and start searching, the options don't disappear when I erase the search or click elsewhere and sometimes they're even duplicated.

[Filter-choiceSet-duplicate.webm](https://github.com/MicrosoftDocs/msteams-docs/assets/100526860/1a02659e-3bf2-474c-80c3-dfa6bcff838d)

### **Steps:**
I tried with the sample code provided in the doc - [here](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/bot-type-ahead-search-adaptive-cards/nodejs)
- In `bots/teamBots.js - line 149` duplicate the option PyCharm
- (optional) In `bots/teamBots.js - line 105` change 1.2 to 1.5 _(I tried with the provided version and the latest - both don't work)_
- Run the bot, type `staticSearch`
- Search `pycharm`
- Erase then search anything else

### **Card JSON**

```
{
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.5",
    "type": "AdaptiveCard",
    "body": [
      {
        "text": "Please search for the IDE from static list.",
        "wrap": true,
        "type": "TextBlock"
      },
      {
        "columns": [
          {
            "width": "auto",
            "items": [
              {
                "text": "IDE: ",
                "wrap": true,
                "height": "stretch",
                "type": "TextBlock"
              }
            ],
            "type": "Column"
          }
        ],
        "type": "ColumnSet"
      },
      {
        "columns": [
          {
            "width": "stretch",
            "items": [
              {
                "choices": [
                  {
                    "title": "Visual studio",
                    "value": "visual_studio"
                  },
                  {
                    "title": "IntelliJ IDEA ",
                    "value": "intelliJ_IDEA "
                  },
                  {
                    "title": "PyCharm",
                    "value": "aptana_studio_3"
                  },
                  {
                    "title": "PyCharm",
                    "value": "pycharm"
                  },
                  {
                    "title": "WebStorm",
                    "value": "webstorm"
                  },
                  {
                    "title": "NetBeans",
                    "value": "netbeans"
                  },
                  {
                    "title": "Eclipse",
                    "value": "eclipse"
                  },
                  {
                    "title": "RubyMine ",
                    "value": "rubymine "
                  },
                  {
                    "title": "Visual studio code",
                    "value": "visual_studio_code"
                  }
                ],
                "style": "filtered",
                "placeholder": "Search for a IDE",
                "id": "choiceselect",
                "type": "Input.ChoiceSet"
              }
            ],
            "type": "Column"
          }
        ],
        "type": "ColumnSet"
      }
    ],
    "actions": [
      {
        "type": "Action.Submit",
        "id": "submit",
        "title": "Submit"
      }
    ]
  }
```

### **Additional info**

Bug is also reported on the Adaptive Card repo - [here](https://github.com/microsoft/AdaptiveCards/issues/7655)

**Comment by Meghana-MSFT** [comment]
We are also able to repro this issue, however it seems the issue is happening only because of using same name for different values. This doesn't seem like a bug. We will check internally and get back to you.

**Comment by Meghana-MSFT** [comment]
Input.ChoiceSet is working fine if we do not give same title for multiple choices. Hence it is recommended to use unique titles for choices. Thank you.
