### ISSUE TITLE
There is no documentation for NodeJS and calling APIs with access token

### ISSUE THREAD

**Issue by textminer** [MicrosoftDocs/msteams-docs#891]
There is no documentation for NodeJS and there is no documentation on how once the access token is obtained how can be used to call external REST APIs. (like SharePoint).

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7c810ce-b432-9135-16ee-55f461a10e78
* Version Independent ID: 70c7c1a0-b5b0-599f-a0b2-ea3e343df227
* Content: [Using the OAuthCard for authentication - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/authentication/auth-oauth-card#feedback)
* Content Source: [msteams-platform/concepts/authentication/auth-oauth-card.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/authentication/auth-oauth-card.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Gousia-MSFT** [comment]
@textminer Please check these docs on [Getting started with NodeJS](https://docs.microsoft.com/en-us/microsoftteams/platform/get-started/get-started-nodejs-app-studio) and a [Auth sample](https://github.com/OfficeDev/microsoft-teams-sample-auth-node) in Node.

**Comment by wictorwilen** [comment]
In this repo you will find plenty f auth samples. The full sample in `teams-dynamics-code` do all sorts of auth and fetching of access tokens (server and client side)
