### ISSUE TITLE
"openExternal" device permission should also allow custom protocol handlers

### ISSUE THREAD

**Issue by divisumma18** [MicrosoftDocs/msteams-docs#8910]
The latest Teams updates appear to have dropped support for custom protocol handlers. We used a custom protocol to implement communication between our Teams tab and a desktop app we developed. This integration worked great for over a year but recently became totally useless as we are now unable to transfer data from Teams to the app.

So can you please restore support for custom protocol handlers?

Or can you suggest an alternative to achieve the same result?

Thank you.

**Comment by Prasad-MSFT** [comment]
Hi @divisumma18 - This issue is being tracked [here](https://github.com/OfficeDev/microsoft-teams-library-js/issues/1816). Please follow that thread for further updates.

Thanks!
