### ISSUE TITLE
Error: "CancelledByUser" at p (https://res.cdn.office.net/teams-js/2.7.1/js/MicrosoftTeams.min.js:23404)

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#8918]
Copied bug from: https://github.com/OfficeDev/TeamsFx/issues/9143 

**Details from original post:**
Copied -https://github.com/OfficeDev/microsoft-teams-library-js/issues/1798

We are currently importing Teams JS in C# project. However the error in step 6 appeared. After testing, the error only appears in Teams on the web, and works fine in Teams Desktop. Also tested with Teams JS 2.11.0, and the error still appeared.

You could reproduce the error by following the steps:

1. Install Visual Studio and Microsoft Teams development tools under individual components
![image](https://github.com/OfficeDev/TeamsFx/assets/93527375/e9a56716-f456-4975-a4ee-37527398599c)

2. Scaffold a new project - Microsoft Teams App - Tab - Configure With SSO.

3. Under Components/Welcome.razor, add await MicrosoftTeams.InitializeAsync() as follows
![image](https://github.com/OfficeDev/TeamsFx/assets/93527375/158d3f7c-5ef1-45f0-bf68-cc68af4204dc)

4. Prepare Teams App Dependencies and Press F5 to start local debug
![image](https://github.com/OfficeDev/TeamsFx/assets/93527375/f0a142a9-5e64-42d4-9459-5e4587579b17)

5. Click Authorize and the Auth page will pop out. Click Accept.
![image](https://github.com/OfficeDev/TeamsFx/assets/93527375/918c0326-9e87-441b-b801-3fb2427bce13)

6. Error appeared instead of the profile card.
![image](https://github.com/OfficeDev/TeamsFx/assets/93527375/04111afa-9053-4b77-8874-db79df48b016)

7.Refresh the page, the profile card appeared.
![image](https://github.com/OfficeDev/TeamsFx/assets/93527375/bbd93cba-e7fa-4603-9e83-c67a4e7eb16f)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b743e43d-95cc-3d1e-b142-31a16369f97e
* Version Independent ID: b743e43d-95cc-3d1e-b142-31a16369f97e
* Content: [Teams Toolkit Overview - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/toolkit/teams-toolkit-fundamentals)
* Content Source: [msteams-platform/toolkit/teams-toolkit-fundamentals.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/teams-toolkit-fundamentals.md)
* Service: **msteams**
* GitHub Login: @zyxiaoyuer
* Microsoft Alias: **zhany**

**Comment by sayali-MSFT** [comment]
Duplicate - https://github.com/OfficeDev/microsoft-teams-library-js/issues/1798
