### ISSUE TITLE
Upload failed due to an invalid BotId in your manifest

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#8919]
Copied bug from: https://github.com/OfficeDev/TeamsFx/issues/9132 

**Details from original post:**
**Describe the bug**
I was trying to create a notification bot using teamstoolkit v5.0.1 extension, on clicking on f5 it starts local debugging and when clicking add button in teams it gives me a pop up saying Upload failed due to an invalid BotId in your manifest.
I'm using developer account for sideloading.

I also tried https://github.com/OfficeDev/TeamsFx/issues/7608#issuecomment-1432603062
but this was already enabled for me you can see in one of the screenshots.

**Screenshots**
<img width="817" alt="Screenshot 2023-06-26 at 5 03 10 PM" src="https://github.com/OfficeDev/TeamsFx/assets/83160894/2dbf76a5-3b0c-4337-95fe-f2274214f7b6">

<img width="960" alt="Screenshot 2023-06-26 at 5 10 43 PM" src="https://github.com/OfficeDev/TeamsFx/assets/83160894/8b0ac302-0a6b-4434-94de-32f8847f0b65">

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b743e43d-95cc-3d1e-b142-31a16369f97e
* Version Independent ID: b743e43d-95cc-3d1e-b142-31a16369f97e
* Content: [Teams Toolkit Overview - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/toolkit/teams-toolkit-fundamentals)
* Content Source: [msteams-platform/toolkit/teams-toolkit-fundamentals.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/teams-toolkit-fundamentals.md)
* Service: **msteams**
* GitHub Login: @zyxiaoyuer
* Microsoft Alias: **zhany**

**Comment by Meghana-MSFT** [comment]
An ICM has been raised for this issue, we will keep you posted on the updates.

**Comment by Meghana-MSFT** [comment]
Closing this issue as per the latest update at https://github.com/OfficeDev/TeamsFx/issues/9132. This issue has been fixed.
