### ISSUE TITLE
Wiki

### ISSUE THREAD

**Issue by croban** [MicrosoftDocs/msteams-docs#892]
Hi, there is no wiki trello connecter and I would like to have it. I am not sure if that is an bug, I would say it is a feature?

And also there is no edit mode for wiki on mobile.

**Comment by Gousia-MSFT** [comment]
@croban Trello connector is already available. Please follow these steps to add Trello connector to your team:
1. Go to the channel and choose "Connectors"
![image](https://user-images.githubusercontent.com/45553518/63259610-8430fb00-c29c-11e9-80f2-b79f7d1659ce.png)
2. Search for Trello and Add
![image](https://user-images.githubusercontent.com/45553518/63259646-9d39ac00-c29c-11e9-840c-c0f315b0ca52.png)

**Comment by croban** [comment]
@Gousia-MSFT thanks for the info, this I have allready done. 
Just what I've meant is, Inside WIKI toolbox there is no action (quick function) to select some trello cards, and of course look&feel inside Wiki of those cards, that would be nice. 

I know that i can put the link of the card inside wiki just, i would like that those kind of links have some look&feel from trello cards inside WIKI, similar to those whick you can see inside Comments

![image](https://user-images.githubusercontent.com/7048578/63261195-217f3580-c283-11e9-8169-f85ed4173728.png)

**Comment by Gousia-MSFT** [comment]
@croban We don't support embeddable 3P objects in Wiki but it's something that we have on our roadmap (leveraging our extensibility framework similar to messaging). Same goes for Edit capabilities on mobile Wiki (in backlog). But I do not have a timeline to share with you.
