### ISSUE TITLE
Not enough information on how to enable developer preview

### ISSUE THREAD

**Issue by Vincent-Payne** [MicrosoftDocs/msteams-docs#8929]
[Enter feedback here]
Ensure you have enabled developer preview – it will lead to page 
https://learn.microsoft.com/en-us/microsoftteams/platform/resources/dev-preview/developer-preview-intro. 
There you must find another link to setting up your tenant that will lead to page
https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/prepare-your-o365-tenant

Additionally, you need to change Update Policy as stated here
https://techpress.net/how-to-enable-developer-preview-and-public-preview-in-microsoft-teams/

Relevant microsoft FAQ(but not up to date)
https://learn.microsoft.com/en-us/MicrosoftTeams/public-preview-doc-updates
Updated screenshot for the policy:
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/119345641/33c92aeb-508f-4f0e-a48b-86251b221b52)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3df1efbb-c6b2-a495-303d-7abf19c57f72
* Version Independent ID: a5b5782f-7031-a989-5e42-dd3010e18893
* Content: [DevTools for Microsoft Teams tabs - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/developer-tools#access-devtools-on-the-desktop)
* Content Source: [msteams-platform/tabs/how-to/developer-tools.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/tabs/how-to/developer-tools.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **surbhigupta**

**Comment by ChetanSharma-msft** [comment]
Hello @Vincent-Payne  - Thanks for raising your query.
We will look into it and let you know the updates.

**Comment by Prasad-MSFT** [comment]
@Vincent-Payne - In [this](https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/developer-tools#access-devtools-on-the-desktop) document 
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/62237649/7ab2aaef-7747-467d-a4c7-f722ae7e74f6)
there is a redirection link to [this](https://learn.microsoft.com/en-us/microsoftteams/platform/resources/dev-preview/developer-preview-intro#enable-developer-preview) page which explains about how to enable developer preview in Desktop/Web and Mobile client. 

Could you please be specific in which page what content needs to be updated?

**Comment by Vincent-Payne** [comment]
> @Vincent-Payne - In [this](https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/developer-tools#access-devtools-on-the-desktop) document ![image](https://user-images.githubusercontent.com/62237649/249441941-7ab2aaef-7747-467d-a4c7-f722ae7e74f6.png) there is a redirection link to [this](https://learn.microsoft.com/en-us/microsoftteams/platform/resources/dev-preview/developer-preview-intro#enable-developer-preview) page which explains about how to enable developer preview in Desktop/Web and Mobile client.
> 
> Could you please be specific in which page what content needs to be updated?

On page which explains about how to enable developer preview we have another  [link](https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/prepare-your-o365-tenant)
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/119345641/a6ad8429-5a19-43db-aa1b-1c6382b81998)


There stated that you need to enable **Upload custom apps**. That is not enough to grant users the ability to switch to Developer Preview and access Dev Tools. You will need also to change Update Policy as stated here
[link](https://techpress.net/how-to-enable-developer-preview-and-public-preview-in-microsoft-teams)

I have tested it myself. If you just enable **Upload custom apps** - you will not have ability to switch to Dev Preview

**Comment by Prasad-MSFT** [comment]
@Vincent-Payne - By enabling custom app uploading or sideloading for our developer tenant only we are able to see the Developer preview option and can use dev tool.
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/62237649/294e5ca1-6d8d-4391-a140-7501daefe847)

**Comment by Vincent-Payne** [comment]
> @Vincent-Payne - By enabling custom app uploading or sideloading for our developer tenant only we are able to see the Developer preview option and can use dev tool. ![image](https://user-images.githubusercontent.com/62237649/249722340-294e5ca1-6d8d-4391-a140-7501daefe847.png)

I have enabled "Upload custom apps" and waited more than 24 hours - nothing happens. Please check your Update Policy and verify. Only after changing Update Policy to «Users can opt in» I'm able to see the Developer preview option and can use dev tool.

**Comment by Vincent-Payne** [comment]
@Prasad-MSFT in addition to prevous comment

User assign to custom updated policy
![User_assign_to_update_policy](https://github.com/MicrosoftDocs/msteams-docs/assets/119345641/3298fdcf-a8b3-40c2-a9c0-2a0a4ba0abe7)

User unassigned from custom update policy(applied global org)
![User_unassign_to_update_policy](https://github.com/MicrosoftDocs/msteams-docs/assets/119345641/de15ec0a-5e7d-4e8d-8ee1-954ff607ac35)

**Comment by Prasad-MSFT** [comment]
@Vincent-Payne - We checked in Teams admin center and we only have this policy assigned
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/62237649/4e96c658-5068-4c36-bd23-4c3056ff60ab)
and still we can see developer preview option in MS Teams
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/62237649/6951f233-b02a-4178-858c-477145065964)

**Comment by Vincent-Payne** [comment]
> @Vincent-Payne - We checked in Teams admin center and we only have this policy assigned ![image](https://user-images.githubusercontent.com/62237649/250054326-4e96c658-5068-4c36-bd23-4c3056ff60ab.png) and still we can see developer preview option in MS Teams ![image](https://user-images.githubusercontent.com/62237649/250054573-6951f233-b02a-4178-858c-477145065964.png)

I don't know why it is not working for our tenant then ¯\_(ツ)_/¯

**Comment by Prasad-MSFT** [comment]
@Vincent-Payne - The version we checked is `Microsoft Teams Version 1.6.00.18375` . 
This is the link to downgrade or upgrade MS Teams
[Older versions of Microsoft Teams (Windows) | Uptodown](https://microsoft-teams.en.uptodown.com/windows/versions)

**Comment by Prasad-MSFT** [comment]
In [this](https://learn.microsoft.com/en-us/microsoftteams/platform/resources/dev-preview/developer-preview-intro#enable-developer-preview) page at the end of [this section](https://learn.microsoft.com/en-us/microsoftteams/platform/resources/dev-preview/developer-preview-intro#enable-developer-preview) (Just before Disable developer preview), we recommend adding a note saying,
"If [Enable custom Teams apps and turn on custom app uploading](https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/prepare-your-o365-tenant#enable-custom-teams-apps-and-turn-on-custom-app-uploading) doesn't enable developer preview features in Microsoft Teams [Set the Update policy](https://learn.microsoft.com/en-us/MicrosoftTeams/public-preview-doc-updates#set-the-update-policy)."
