### ISSUE TITLE
activityImage is broken in Example of connector message

### ISSUE THREAD

**Issue by Meghana-MSFT** [MicrosoftDocs/msteams-docs#8935]
[Enter feedback here]

Sending the card mentioned here works successfully https://learn.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-using?tabs=cURL#example-of-connector-message, but the activityImage is broken in the card.

![image](https://github.com/MicrosoftDocs/msteams-docs/assets/81138249/37c6b91e-3841-44f6-96f3-5643c5c6ad62)
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 28316a67-22fa-8a05-1ae0-fbe1c5720ef9
* Version Independent ID: 8a250e46-2a30-af86-839d-9f83a8b48041
* Content: [Create and send messages - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-using?tabs=cURL)
* Content Source: [msteams-platform/webhooks-and-connectors/how-to/connectors-using.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/webhooks-and-connectors/how-to/connectors-using.md)
* Service: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **surbhigupta**

**Comment by Meghana-MSFT** [comment]
@surbhigupta12 - The activityImage URL [provided in the sample](https://learn.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-using?tabs=cURL#example-of-connector-message) (and the hosting service) is down. Can we get an appropriate image that's hosted on stable platform? Can you please update the activityImage URL.

**Comment by Wajeed-msft** [comment]
@Meghana-MSFT  - could you please use this (https://adaptivecards.io/content/cats/3.png)  image and share the updated screenshot to be added in docs?

**Comment by Meghana-MSFT** [comment]
@surbhigupta12 - Please update the activityImage URL [provided in the sample](https://learn.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-using?tabs=cURL#example-of-connector-message) as "https://adaptivecards.io/content/cats/3.png"

Please update the image with below screenshot - 

![image](https://github.com/MicrosoftDocs/msteams-docs/assets/81138249/6e79ef48-1018-4eb9-ba3c-571a6ea717f1)
