### ISSUE TITLE
Add example on how to read Teams Channel Message with Title

### ISSUE THREAD

**Issue by ebecerramicrosoft** [MicrosoftDocs/msteams-docs#8938]
There is no example on how to get the "Subject"/"Title" of a conversation from a teams channel where the bot is listening to. The only examples show how to get the content of the message.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3e0acfd2-0965-65f4-2200-ca06424a3976
* Version Independent ID: fd7f72fe-5dba-369a-c436-6140d232ad44
* Content: [Receive all conversation messages with RSC - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/channel-messages-with-rsc?tabs=channel%2Cdotnet)
* Content Source: [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md)
* Service: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **surbhigupta**

**Comment by Nivedipa-MSFT** [comment]
@ebecerramicrosoft - Thanks for reporting your issue. We are currently investigating it with engineering team, and we will provide you with an update as soon as possible.
