### ISSUE TITLE
Height for iframe in task module response is decreasing for Teams app in Windows

### ISSUE THREAD

**Issue by Navega** [MicrosoftDocs/msteams-docs#895]
Related to [Dynamic input using a web view](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/messaging-extensions/create-extensions#dynamic-input-using-a-web-view) section.

The height for task modules with an iframe as response is right in Teams web app but not for Windows app.

This is our response:

```return {
      "task": {
        "type": "continue",
        "value": {
          "title": title,
          "height": "large",
          "width": "large",
          "url": link,
          "fallbackUrl": fallback_link,
        }
      }
    }
```

And this is the result:

![thin](https://user-images.githubusercontent.com/16117077/60789672-ef48c700-a15f-11e9-8a25-260bd107dceb.JPG)

Steps to reproduce:

1. Create a task from module extension: [info](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/messaging-extensions/create-extensions?tabs=typescript#dynamic-input-using-an-adaptive-card).
2. Adaptive card as response: [info](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/messaging-extensions/create-extensions?tabs=typescript#respond-with-an-adaptive-card-message-sent-from-a-bot).
3. We offer 2 options in that adaptive card: "inject the card in conversation" or "open a new task module" for a given url. The 1st one is ok, but the new task module has a wrong height. This worked previously and currently it works in Teams Web. So we are opening that link externally until this is fixed.

Related to this [closed issue](https://github.com/MicrosoftDocs/msteams-docs/issues/776).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aaa0ea75-7363-3ef5-39df-ad07c493c118
* Version Independent ID: ab9a2a6e-e2ca-828f-cd8b-bd9ff98411ab
* Content: [Initiate actions with messaging extensions - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/messaging-extensions/create-extensions#dynamic-input-using-a-web-view)
* Content Source: [msteams-platform/concepts/messaging-extensions/create-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/messaging-extensions/create-extensions.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Gousia-MSFT** [comment]
@Navega As mentioned in the [closed issue](https://github.com/MicrosoftDocs/msteams-docs/issues/776), could you please share your app manifest with us?

**Comment by Navega** [comment]
> @Navega As mentioned in the [closed issue](https://github.com/MicrosoftDocs/msteams-docs/issues/776), could you please share your app manifest with us?

Hello @Gousia-MSFT, it isn't a problem, but is it safe to share the Prodution manifest here (maybe in other channel)? or should I share the manifest for Stage?

**Comment by Wajeed-msft** [comment]
@Navega - Please share it on [Microsoft Teams developer support](mailto:microsoftteamsdev@microsoft.com)   mentioned on [Feedback page](https://docs.microsoft.com/en-us/microsoftteams/platform/feedback).

**Comment by Navega** [comment]
> @Navega - Please share it on [Microsoft Teams developer support](mailto:microsoftteamsdev@microsoft.com) mentioned on [Feedback page](https://docs.microsoft.com/en-us/microsoftteams/platform/feedback).

Thanks, I did it.

**Comment by Gousia-MSFT** [comment]
@Navega Thanks for sharing the manifest. We were able to repro the issue. In this  [closed issue](https://github.com/MicrosoftDocs/msteams-docs/issues/776#issuecomment-511697431) you mentioned you could see this in other bots also. Could you please help us with which app you could repro it so that we could check the issue with a better understanding?

**Comment by Navega** [comment]
> @Navega Thanks for sharing the manifest. We were able to repro the issue. In this [closed issue](https://github.com/MicrosoftDocs/msteams-docs/issues/776#issuecomment-511697431) you mentioned you could see this in other bots also. Could you please help us with which app you could repro it so that we could check the issue with a better understanding?

Hey @Gousia-MSFT, when I said that, I meant that problem is consistent for any bot that we created because I shared the bot ID that we use, so is not related to other bot/integrations.

**Comment by Gousia-MSFT** [comment]
@Navega Thanks! We have raised a bug for this and we are looking into it.

**Comment by Navega** [comment]
Hello @Gousia-MSFT , will the fix be deployed in next version? We continue with this problem in MS Teams for Windows.

**Comment by Gousia-MSFT** [comment]
@Navega We have a bug on this which is being tracked internally. I will post it here once it is fixed.

**Comment by Navega** [comment]
> @Navega We have a bug on this which is being tracked internally. I will post it here once it is fixed.

Ok, thanks!
