### ISSUE TITLE
[Rendering] FactSet now renders as a table with visible borders in Teams Desktop

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#8955]
Copied bug from: https://github.com/microsoft/AdaptiveCards/issues/8587 

**Details from original post:**
### Target Platforms

WPF

### SDK Version

1.4

### Application Name

Microsoft Teams

### Problem Description

FactSet now renders as a table with visible borders and white background in Teams Desktop.
Mobile is ok.

### Screenshots

<img width="543" alt="Screenshot 2023-06-28 at 18 21 55" src="https://github.com/microsoft/AdaptiveCards/assets/9824156/52102be7-74c7-46d4-b38d-a65b9e36e52a">

### Card JSON

```JSON
{
    "type": "AdaptiveCard",
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.4",
    "body": [
        {
            "type": "FactSet",
            "facts": [
                {
                    "title": "Fact 1",
                    "value": "Value 1"
                },
                {
                    "title": "Fact 2",
                    "value": "Value 2"
                },
                {
                    "title": "Fact 1",
                    "value": "Value 1"
                },
                {
                    "title": "Fact 1",
                    "value": "Value 1"
                },
                {
                    "title": "Fact 1",
                    "value": "Value 1"
                }
            ]
        }
    ],
    "backgroundImage": {
        "url": "https://htmlcolorcodes.com/assets/images/html-color-codes-color-tutorials-hero.jpg"
    }
}
```

### Sample Code

_No response_---
#### Document Details

⚠ *Do not edit this section.It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Cards reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **surbhigupta12**

**Comment by Prasad-MSFT** [comment]
@SergeyGrayman - Thanks for raising this. We will check it at our end and will get back to you with updates.

**Comment by Prasad-MSFT** [comment]
@SergeyGrayman - We checked in MS teams desktop with version `1.6.00.17673` and are able to repro this issue. 
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/62237649/47378a33-46f5-401e-953b-c27fb9de92d6)

We have raised a bug for the same. We will inform you once we get any further update from engineering team. Thanks!

**Comment by PerryRose** [comment]
My team are experiencing this issue as well in production, unfortunately. Hoping that the engineering team takes priority on a fix.

**Comment by PerryRose** [comment]
@Prasad-MSFT I am still experiencing this issue. Both Teams app and web app.

**Comment by SergeyGrayman** [comment]
@Prasad-MSFT Problem still persist on Mac and Web:
<img width="805" alt="Screenshot 2023-07-06 at 09 46 13" src="https://github.com/MicrosoftDocs/msteams-docs/assets/9824156/c0104fc7-ebd3-4ab2-a61e-089e4fa92f29">
<img width="600" alt="Screenshot 2023-07-06 at 09 49 50" src="https://github.com/MicrosoftDocs/msteams-docs/assets/9824156/742a49ba-f198-488e-bd0b-7c24f5a7cd50">

**Comment by SergeyGrayman** [comment]
@Prasad-MSFT also latest windows public version is:

**You have Microsoft Teams Version 1.6.00.17564 (64-bit). It was last updated on 06/07/2023.**

![Screenshot 2023-07-06 111453](https://github.com/MicrosoftDocs/msteams-docs/assets/9824156/e18ed3b7-93e0-451d-9c29-e93d1f607901)

Another thing is that white background still persists in your screenshot as well. It is a part of the bug. FactSet shouldn't have any background.

**Comment by Prasad-MSFT** [comment]
@SergeyGrayman - We also confirm that with the updated version (Microsoft Teams Version 1.6.00.20269) the grid issue is fixed
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/62237649/6e06a74f-096f-4c6b-be83-bd6d79103d57)

Regarding the white background, we have informed the engineering team. We will update you once we hear from them. Thanks!

**Comment by Prasad-MSFT** [comment]
@z3019494 - Apologies. Currently we are following up with engineering team asking for update on the fix. Once we have any update we will inform in this thread. Thanks!

**Comment by z3019494** [comment]
It now seems to be fixed! Latest screenshot:

<img width="355" alt="image" src="https://github.com/MicrosoftDocs/msteams-docs/assets/60587625/5e5635c0-8069-4e32-bdfd-5503f465564e">
