### ISSUE TITLE
[AdaptiveCards] [Speak attribute details are not clear in documentation]

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#8957]
Copied bug from: https://github.com/microsoft/AdaptiveCards/issues/8582 

**Details from original post:**
We see following note in documentation for speak attribute: https://adaptivecards.io/explorer/
_Specifies what should be spoken for this entire card. This is simple text or SSML fragment_.

If we utilize the same feature in MS Teams bots, it proves beneficial for the immersive reader to read the Speak property value. However, its usefulness remains limited to this specific context and may require explicit mention in the documentation.
---
* URL: https://adaptivecards.io/explorer/---
#### Document Details

⚠ *Do not edit this section.It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Cards reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **surbhigupta12**

**Comment by Prasad-MSFT** [comment]
Hi @SubbaReddi - Could you please let us know what exactly needs to be updated/added in which doc?

**Comment by SubbaReddi** [comment]
Hi @Prasad-MSFT,
I recommend updating in following doc: https://adaptivecards.io/explorer/
If not, add note in following documentation: https://learn.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/design-effective-cards?tabs=design

Note can be something similar as follows:
"In Microsoft teams bots, Speak attribute in adaptive cards will be used for immersive reader only."

**Comment by Prasad-MSFT** [comment]
Hi @surbhigupta12 - Could you please help here to update the doc as suggested?
