### ISSUE TITLE
Get Chats API taking 7-12 seconds time

### ISSUE THREAD

**Issue by kaursimransidhu1** [MicrosoftDocs/msteams-docs#8959]
Hi, 

We are using the below API to get chats of a user

https://graph.microsoft.com/v1.0/me/chats?$expand=members

It is taking anywhere between 7-12 seconds to give a response. Upon hitting multiple times, it starts to give a response in 4-5 seconds. 

We tested from [Graph API explorer](https://developer.microsoft.com/en-us/graph/graph-explorer) as well and it took around 5 seconds for fetching 20 chats. 

<img width="1714" alt="image" src="https://github.com/MicrosoftDocs/msteams-docs/assets/102144967/ba520f5b-d14f-4534-862f-5e1e78b2866d">

We would like to know the reasons and possible solutions to improve the time taken by the APIs.

FYI we are based in Hyderabad, India, if location makes any impact on the response time.

Thanks,
Simran Sidhu,
Software Engineer, 
ServiceNow, India

**Comment by Prasad-MSFT** [comment]
@kaursimransidhu1 - We tried to run this API. However, we noticed that it gives us response in 2-3 seconds.
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/62237649/5e1d38e1-2f35-4853-b16a-502ac5a2e1f5)

**Comment by kaursimransidhu1** [comment]
Hi Prasad, Yes sometimes it takes around 3 seconds and sometimes it takes 4-5 seconds. And sometimes while hitting the very first time it may take up to 7 seconds. But just for fetching 20 chats it shall take less than a second right, it shall be done in milliseconds. If the API call itself takes 3-5 seconds, then if we build functionality on top of it, imagine the load time.

**Comment by kaursimransidhu1** [comment]
Ran again, and got time taken 4.5 seconds. I have more than 100 chats in my team's account, in real use cases users may have even more chats. I see you have only 19 chats in your account. 

<img width="1728" alt="Screenshot 2023-06-30 at 1 23 50 PM" src="https://github.com/MicrosoftDocs/msteams-docs/assets/102144967/bd62da3a-f63a-460f-950c-60246091fedb">

**Comment by Prasad-MSFT** [comment]
Okay @kaursimransidhu1 - We will check with engineering team if there are any possible solutions to improve the time taken by the APIs.

**Comment by Prasad-MSFT** [comment]
Hi @kaursimransidhu1 -Could you please provide the client-request-Id and timestamp when you are fetching the request?

**Comment by s1mran** [comment]
Hi @Prasad-MSFT, I am attaching the response headers below - 

`{
    "client-request-id": "7d351716-3218-1349-7701-8d0d5c6ac558",
    "content-type": "application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8",
    "request-id": "56083e70-fbc7-4fe8-8eed-6838838075c8"
}`

I am unable to get the exact timestamp, but I ran this request around 4:54 PM IST on 10th July. 

Thanks,
Simran Sidhu

**Comment by Prasad-MSFT** [comment]
We have shared the above details and got below info from engineering team "It doesn't look like the user calls the service enough because we had to fetch their license status on live request (we hold on to this info for a long time while background refreshing it to avoid hitting the impact on incoming request)."
