### ISSUE TITLE
missing locale in onMembersAdded event

### ISSUE THREAD

**Issue by searlin** [MicrosoftDocs/msteams-docs#896]
The locale is missing in **onMembersAdded** event, I want to proactively send a **localized** welcome message to a personal chat in the **onMembersAdded** event, but there is **no locale** in the context.activity, it does exist in **onMessage** event

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55c04f55-28de-978f-8733-0a83453172f7
* Version Independent ID: 4f25cfc6-6ac0-db44-4078-a8ba592ceeba
* Content: [Handle bot events - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/bots/bots-notifications)
* Content Source: [msteams-platform/concepts/bots/bots-notifications.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/bots/bots-notifications.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Wajeed-msft** [comment]
This is a known limitation currently. Bot has to wait for user to message. The message activity has clientInfo filled out in channelData with locale information.

**Comment by searlin** [comment]
@Wajeed-msft  thanks for your reply, understood, do we have any timeline to fix it?

**Comment by Wajeed-msft** [comment]
Currently, we do not have any timelines to share. We are tracking this internally so closing this from documentation issues.
