### ISSUE TITLE
MessagingExtensionActionResponse Calls Wrong URL

### ISSUE THREAD

**Issue by StoyanGG** [MicrosoftDocs/msteams-docs#8979]
We create 2 different MessagingExtensionActionResponse one after the other.
First one ("https://\<ngrok\>/api/messages/select"):

`return new MessagingExtensionActionResponse()
            {
                Task = new TaskModuleContinueResponse()
                {
                    Value = new TaskModuleTaskInfo()
                    {
                        Height = 3000,
                        Width = 3000,
                        Title = "Start Module",
                        Url = uriBuilderStart.ToString()
                    }
                }
            };`
Correctly opens up a Teams Messaging Extension module.
We do what we need to do, then 
`microsoftTeams.tasks.submitTask(data);`
The data received by
`protected override async Task<MessagingExtensionActionResponse> OnTeamsMessagingExtensionSubmitActionAsync(ITurnContext<IInvokeActivity> turnContext, MessagingExtensionAction action, CancellationToken cancellationToken)` is all good.

But then, directly after, when attempting a follow up MessagingExtensionActionResponse ("https://\<ngrok\>/api/messages/file"):
`return new MessagingExtensionActionResponse()
            {
                Task = new TaskModuleContinueResponse()
                {
                    Value = new TaskModuleTaskInfo()
                    {
                        Height = 3000,
                        Width = 3000,
                        Title = "Outcome Module",
                        Url = uriBuilderOutcome.ToString()
                    }
                }
            };`

The task module DOES get a title "Outcome Module", but it re-triggers the "/select" route from the previous module instead of the "/file" route from the new one. I have triple checked the URL. This issue currently occurs from a Chat context and it started occurring just recently. When the extension is started from a Channel Conversation context, it works fine. Both use the same code paths.

Microsoft.Bot.Builder and Microsoft.Bot.Connector and Microsoft.Bot.Schema 4.20.0 (but I tested 4.16 and the issue also occurs)
https://statics.teams.cdn.office.net/sdk/v1.5.2/js/MicrosoftTeams.min.js

**Comment by Nivedipa-MSFT** [comment]
@StoyanGG - Thanks for reporting your issue. Could you please share a screen recording of the issue to help us understand it better?

**Comment by StoyanGG** [comment]
> @StoyanGG - We got the recording, we will check this and update you soon.

Hello, would you be able to assess this issue soon? Thanks in advance

**Comment by Nivedipa-MSFT** [comment]
@StoyanGG - Apologies for the delay. We are currently trying to reproduce the issue at our end. However, we are facing some difficulties. To assist us in investigating further, could you please provide a simplified version of your code as a zip file? This will allow us to review the code and test it locally to better understand the problem. Thank you for your cooperation.

**Comment by StoyanGG** [comment]
I have sent you the most simplified version of the solution that triggers the issue every single time I attempt it from a chat message context.
Please try to reproduce it with the code provided and if you can't - as soon as you're available I will demonstrate the issue on a live call.

**Comment by Nivedipa-MSFT** [comment]
@StoyanGG - Thanks for providing the code. We will test it and update you soon.

**Comment by StoyanGG** [comment]
> @StoyanGG - Thanks for providing the code. We will test it and update you soon.

Hello,  I've been asked to check if you were you able to reproduce the issue on this occasion? Can I assist you further?
Kind Regards, Stoyan

**Comment by Nivedipa-MSFT** [comment]
@StoyanGG - Apologies for the delay. We are able to repro your issue and raised the bug for the same. We will let you know once we get any updates on it.

**Comment by StoyanGG** [comment]
As the issue is important for a product development and release, I've been asked to check its status once a week.
Are you able to share the current progress, its priority and estimated timescale? Thanks

**Comment by Nivedipa-MSFT** [comment]
@StoyanGG - We are checking the status of bug with engineering team, we will let you know once we get any updates from them.

**Comment by Nivedipa-MSFT** [comment]
@StoyanGG - Currently, we don't have any ETA to share. The engineering team is actively working on the fix. We will let you know once we receive any updates from them.

**Comment by Nivedipa-MSFT** [comment]
@StoyanGG - The bug has been fixed now. We have tested this on the Teams web client. Could you please test this and confirm once?

**Comment by StoyanGG** [comment]
@Nivedipa-MSFT - Thank you. I've tested this on our main tenant on the Teams desktop client and it appears to be fixed.

**Comment by Nivedipa-MSFT** [comment]
@StoyanGG - Thanks for the confirmation. Could you please share your valuable feedback via [Microsoft Teams Developer Feedback](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR7iCOpS5_b9Nqmwx43u5rtZUOThVR081SllSR05aSDQxQ0tUMDVPTVIxTi4u) link.
