### ISSUE TITLE
Teams settings are moved to Teams and Skype administration center

### ISSUE THREAD

**Issue by PerOve** [MicrosoftDocs/msteams-docs#898]
The content should be updated to show where to do settings in the new Teams and Skype administration center. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a34043ac-ef9b-3e19-3095-3bcf88fef486
* Version Independent ID: c917cf5d-7563-44f4-58c1-3d460652e59c
* Content: [Prepare your Office 365 tenant - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/get-started/get-started-tenant?lc=1033#feedback)
* Content Source: [msteams-platform/get-started/get-started-tenant.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/get-started/get-started-tenant.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Gousia-MSFT** [comment]
@PerOve Thanks for reaching out. We have this on the backlog.
