### ISSUE TITLE
How to create app package

### ISSUE THREAD

**Issue by JMyner** [MicrosoftDocs/msteams-docs#8985]
How do I create an app package and distribute it for an Azure bot service. This guide does not explain it.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 16fc6b2b-88c3-a68c-80dd-3aaa5ebf9295
* Version Independent ID: 7e29b777-35e7-5682-eb69-ac7aa92b5ad1
* Content: [Overview - Distribute your app - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/apps-publish-overview)
* Content Source: [msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md)
* Service: **msteams**
* GitHub Login: @v-rpatkur
* Microsoft Alias: **surbhigupta**

**Comment by Meghana-MSFT** [comment]
@JMyner - Could you please let us know if these documents help you 

1. https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/apps-package
2. https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/apps-upload
3. https://learn.microsoft.com/en-us/microsoftteams/upload-custom-apps
