### ISSUE TITLE
Document all scenarios that cause a retry

### ISSUE THREAD

**Issue by aosolis** [MicrosoftDocs/msteams-docs#8998]
<img width="662" alt="image" src="https://github.com/MicrosoftDocs/msteams-docs/assets/767208/7d579ba3-98ca-4f1d-88a7-bbae9bbdfc22">
This describes the retry on timeout, but we also retry when the bot returns certain failure HTTP status codes. Please document those.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6ec6c2e8-0af6-7984-a780-e5bb6ae113ef
* Version Independent ID: e0c9ab4e-0d6d-a4c5-f705-b78a0f2a87fb
* Content: [Bot activity handlers - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/bots/bot-basics?tabs=csharp)
* Content Source: [msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/bots/bot-basics.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **anclear**

**Comment by Nivedipa-MSFT** [comment]
@aosolis - Thank you for reporting your issue. Could you please confirm if we should add the following status code to the document?
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/92150070/3231525f-a8d1-47d0-b2f5-fa58834b1afa)
