### ISSUE TITLE
Doc for configuring Azure AD for Teams bot is not very clear

### ISSUE THREAD

**Issue by yuezk** [MicrosoftDocs/msteams-docs#9001]
[This](https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/authentication/bot-sso-register-aad?tabs=windows#:~:text=Application%20ID%20URI%20for%20app%20with%20multiple%20capabilities%3A%20If%20you%27re%20building%20an%20app%20with%20a%20bot%2C%20a%20messaging%20extension%2C%20and%20a%20tab%2C%20enter%20the%20application%20ID%20URI%20as%20api%3A//fully%2Dqualified%2Ddomain%2Dname.com/BotId%2D%7BYourClientId%7D%2C%20where%20the%20BotID%20is%20your%20bot%20app%20ID.) isn't very clear. 

<img width="739" alt="image" src="https://github.com/MicrosoftDocs/msteams-docs/assets/3297602/d0f5e018-e241-4505-aaf4-2136d57dcd3e">

Questions:

1. Do `BotId` and `BotID` represent the same thing?
2. What is `YourClientId`?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ac68d7e8-2a35-5208-8724-68bd2fdd79b6
* Version Independent ID: ac68d7e8-2a35-5208-8724-68bd2fdd79b6
* Content: [Configure your app in Azure AD - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/authentication/bot-sso-register-aad?tabs=windows)
* Content Source: [msteams-platform/bots/how-to/authentication/bot-sso-register-aad.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/bots/how-to/authentication/bot-sso-register-aad.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **surbhigupta**

**Comment by Meghana-MSFT** [comment]
@yuezk - Thank you for reporting this issue. Application ID URI for app with multiple capabilities should be of the format api://fully-qualified-domain-name.com/botId-{YourClientId} where YourClientId is your Azure AD application ID.

@surbhigupta12 - Could you please help to update the [highlighted part](https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/authentication/bot-sso-register-aad?tabs=windows#:~:text=api%3A//fully%2Dqualified%2Ddomain%2Dname.com/BotId%2D%7BYourClientId%7D%2C%20where%20the%20BotID%20is%20your%20bot%20app%20ID.) as below
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/81138249/5496a463-9528-4076-bfb3-3c5d23ebc236)


api://fully-qualified-domain-name.com/botId-{YourClientId}, where the {YourClientId} is your bot app ID.
