### ISSUE TITLE
Cannot Open OneDriveFilePicker with Url Module

### ISSUE THREAD

**Issue by barisbikmaz** [MicrosoftDocs/msteams-docs#9004]
I want to open the [OneDriveFilePicker](https://learn.microsoft.com/en-us/onedrive/developer/controls/file-pickers/?view=odsp-graph-online) using the URL module. The user should be able to pick a folder in his Teams channel. It is currently not possible because CSP Headers are blocking the loading of the page.

Refused to frame '<URL>' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'self' teams.microsoft.com *.teams.microsoft.com *.skype.com *.teams.microsoft.us local.teams.office.com teams.microsoftonline.cn *.powerapps.com *.yammer.com *.officeapps.live.com *.office.com *.stream.azure-test.net *.microsoftstream.com *.dynamics.com *.microsoft.com onedrive.live.com *.onedrive.live.com securebroker.sharepointonline.com".

The File Picker sits within the customers tenant https://{tenant}.sharepoint.com/_layouts/15/FilePicker.aspx

Code example for the content of the dialog [filepicker.html](https://gist.github.com/barisbikmaz/7a96e190ea99a60483d42c045823497d). (I removed the messaging with the parent to make the code more readable)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 03885ee0-7775-4887-51ba-21f156e1b340
* Version Independent ID: dd92cc27-a3e6-ed65-2b7f-9d1d0bea4cc7
* Content: [url module - Teams](https://learn.microsoft.com/en-us/javascript/api/@microsoft/teams-js/dialog.url?view=msteams-client-js-latest)
* Content Source: [nodejs/docs-ref-autogen/@microsoft/teams-js/dialog.url.yml](https://github.com/OfficeDev/msteams-client-docs-ref-typescript/blob/live/nodejs/docs-ref-autogen/@microsoft/teams-js/dialog.url.yml)
* Service: **msteams**
* GitHub Login: @charlesprakash
* Microsoft Alias: **o365devx**

**Comment by sayali-MSFT** [comment]
@barisbikmaz - Thanks for reporting your issue.
We will check this at our end and will get back to you.

**Comment by sayali-MSFT** [comment]
@barisbikmaz -As per my understanding, to open the OneDrive file picker using the URL module in Microsoft Teams, you need to ensure that the necessary Content Security Policy (CSP) headers are configured to allow the loading of the page. 

You need to allow the following frame-ancestors in your CSP headers:
teams.microsoft.com for Teams
*.microsoft365.com and *.office.com for Microsoft 365 app
outlook.live.com, outlook.office.com, outlook.office365.com, outlook-sdf.office.com, and outlook-sdf.office365.com for Outlook

By allowing these frame-ancestors, you ensure that the OneDrive file picker can be loaded within the Teams channel.

**Comment by barisbikmaz** [comment]
Yeah thanks. I saw that now. SharePoint Online is restricting the page to be loaded in an iframe outside these domains. Closing the issue.

**Comment by sayali-MSFT** [comment]
@barisbikmaz - Could you please share your valuable feedback via [Microsoft Teams Developer Feedback](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR7iCOpS5_b9Nqmwx43u5rtZUOThVR081SllSR05aSDQxQ0tUMDVPTVIxTi4u) link.
