### ISSUE TITLE
Passing image to outgoing webhook from teams

### ISSUE THREAD

**Issue by viksakshum** [MicrosoftDocs/msteams-docs#901]
i posted @<webhook name> an image attachment. 

this is not coming to the webhook channel.  Passing plain text works fine though.  Are images supported?

**Comment by Trinetra-MSFT** [comment]
Could you please share a screenshot of what you are sending from Microsoft Teams?

**Comment by viksakshum** [comment]
look at the last message where i m attaching the image
https://www.dropbox.com/s/n2ed1x0xjyilfv3/Screenshot%202019-08-21%2019.46.59.png?dl=0

on server side it does not give any data that i can use to extract/download this image

**Comment by Trinetra-MSFT** [comment]
Webhooks are not authenticated, by design. It is not possible to send and access the image with webhook but this works with Bot you can use the bot's token in the http headers for the GET on the image URL.

**Comment by viksakshum** [comment]
The documentation of webhook does not say in limitation of webhook about it.  but sure thanks for responding. at least i know this is not the right path
