### ISSUE TITLE
Custom protocol (URL schema) is not working in MS Teams desktop client (desktop_blocked_insecure_navigation)

### ISSUE THREAD

**Issue by kafka-yu** [MicrosoftDocs/msteams-docs#9010]
Hi team,

we meet an issue that in the latest version of MS Teams desktop client, the custom protocol is not working. The protocol will be invoked in our Teams tab app. It works fine in the past months.

We checked the log file, see some error info as shown below:
```
desktop_blocked_insecure_navigation,

protocol: *our protocol*:, status: failure, scenario: 17c7a787-1ebe-4fa6-9909-d0cb480e799d, scenarioName: security_unsupported_url, name: security_unsupported_url,
```

We dug into the compiled code of the MS Teams electron app, there is a list of supported protocols. The protocol in this list works. **The question** is: How is our protocol (the working one) be listed? How can we support more? (Now it blocks many of our customers to use our Teams app in desktop client.

Thanks.

<img width="450" alt="image" src="https://github.com/MicrosoftDocs/msteams-docs/assets/3942409/83fc9415-75f0-4bfc-a98c-136dc12696a3">

**Comment by Nivedipa-MSFT** [comment]
@kafka-yu - Thank you for reporting the issue. We are currently checking this with engineering team, and we will provide you with an update as soon as possible.

**Comment by Nivedipa-MSFT** [comment]
@kafka-yu - Please provide the entire list of protocols that you would like us to consider adding.

**Comment by kafka-yu** [comment]
@Nivedipa-MSFT 

Here is the list of additional URLs
```
rctelus:
com.ringcentral.vodafonebusiness.app:
com.rainbowoffice.app:
com.bt.cloudwork.app:
officeathand:
unifyoffice:
```
All of the above are for the apps that we already published in the MS Teams app store.

BTW, is there any other way to support this? In case in the future we have another URL?

**Comment by kafka-yu** [comment]
Hi @Nivedipa-MSFT Can you pls check the list I shared? Thanks.

**Comment by Nivedipa-MSFT** [comment]
@kafka-yu - We will share this with engineering team and update you soon.

**Comment by u9520107** [comment]
Is it possible to enhance the manifest to allow us to declare the protocols we need to use?
Since updating the application manifest for releases would need to go through review. Maybe make into a process of:

1. app devs declare the protocols in the manifest
2. devs submit the manifest to be reviewed by Microsoft
3. Teams app can allow the protocols listed in the app manifests once they have pass the review process

I'd imaging this would be more scalable than hardcoding the list of protocols supported by the electron runtime.

**Comment by kafka-yu** [comment]
> @kafka-yu - We will share this with engineering team and update you soon.

Hi @Nivedipa-MSFT

Wanna know, if there is any update?

**Comment by Nivedipa-MSFT** [comment]
@thaiduongpham - We will share this with engineering team and update you soon.

**Comment by thaiduongpham** [comment]
Great, thank you!

**Comment by thaiduongpham** [comment]
Hi @Nivedipa-MSFT

Is there any update from your engineering team?

**Comment by Nivedipa-MSFT** [comment]
@thaiduongpham - We are checking for updates with the engineering team, and we will let you know once we receive any updates from them.

@Yves2019 - We will share the protocol with the engineering team.

**Comment by u9520107** [comment]
Hi @Nivedipa-MSFT,

Is there any updates on this that can be shared with us, our customers are still eager to get this issue resolved.

Thanks,

Jack

**Comment by Nivedipa-MSFT** [comment]
@u9520107 -  We are checking for updates with the engineering team, and we will let you know once we receive any updates from them.

**Comment by Nivedipa-MSFT** [comment]
The engineering team is actively working on adding protocols to the allow list. We will update you soon.

**Comment by YaxinYu** [comment]
Hi @Nivedipa-MSFT Hi Nividipa. May I know if this issue has raised to PG team? If there's update for the team? Thank you

**Comment by YaxinYu** [comment]
Hi @Nivedipa-MSFT, may we know if there's an estimated fix date? Thank you in advance.

**Comment by Yves2019** [comment]
Hi @Nivedipa-MSFT. 
May we have an update about this issue? Thank's in advance

**Comment by Prasad-MSFT** [comment]
Hi @kafka-yu , @thaiduongpham , @YaxinYu , @Yves2019 - We got info from engineering team that this issue is resolved. Could you please check and update us?

**Comment by u9520107** [comment]
@Prasad-MSFT 
On behalf of @kafka-yu, I can verify that our protocols are working.
Thanks!

**Comment by Prasad-MSFT** [comment]
Thanks for confirming. We are closing this issue for now. Please feel free to reopen if required. Thanks!
