### ISSUE TITLE
Extracting email in the webhook from MS teams

### ISSUE THREAD

**Issue by moblizeitllc** [MicrosoftDocs/msteams-docs#902]
I have created a outgoing webhook in MS teams. When i send a message mentioning webhook name like "Hi how are you" 

i can see the payload which mentions the name and id in the from node. how do i get the email as well here of the user who sent it?

**Comment by Gousia-MSFT** [comment]
@viksakshum Currently, the payload only contains the AADobjectID and Name of the user. User EmailId cannot be obtained in the outgoing webhook.

**Comment by viksakshum** [comment]
and there is no way to drive the email in node js using the above id?

**Comment by billbliss** [comment]
Yes you can retrieve UPN and primary email address if you have a Microsoft Graph access token and an AppId with the right privileges (e.g. User.Basic). You must have application privileges or ask the user to login to do that though.

**Comment by viksakshum** [comment]
is there a code sample that i can use on nodejs server to do this. my payload give me below data and i am using below code for integration of my webhook (i have tried two ways to get email but first one does not get invoked somehow and 2nd gives me 401 access denied

`
const builder = require('botbuilder');
const teams = require('botbuilder-teams');

let connector = new teams.TeamsChatConnector({
    // It is a bad idea to store secrets in config files. We try to read the settings from
    // the config file (/config/default.json) OR then environment variables.
    // See node config module (https://www.npmjs.com/package/config) on how to create config files for your Node.js environment.
    appId: '63273382-xxxxxxx-4e9a-bf42-f8c32a765816',
    appPassword: 'xxxxx*V?zoaQ6SF*QgkfgQhHfVW515'
});

exports.ms_bot_webhook = functions.https.onRequest(async (req, res) => {
        console.log("Got the incoming from microsoft:::" + (req))
        console.log("body is::" + JSON.stringify(req.body))

        console.log("member id:" + req.body.from.id)
        console.log("service url:" + req.body.serviceUrl)


       await connector.fetchMembers(
            req.body.serviceUrl,
                req.body.from.id,
            (err:any, result:any) => {
              if (err) {
                console.log("broke with error:" + err)
              }
              else {
                console.log("response is:::" + JSON.stringify(result));
              }
            }
          )


        const teamRsp = await rp(req.body.serviceUrl + 'v3/conversations/' + req.body.from.id + '/members')
        console.log("team roaster is:::" + JSON.stringify(teamRsp))
`


`:{"type":"message","id":"1566441982657","timestamp":"2019-08-22T02:46:22.689Z","localTimestamp":"2019-08-21T19:46:22.689-07:00","serviceUrl":"https://smba.trafficmanager.net/amer/","channelId":"msteams","from":{"id":"29:1l0G4IfbJfjqeRFegb20EX_9iYxcVdPJ1qALzeE9j3acrHxK4yJutnGa2LWzayPx6mufDKBZQ-A9qmahW2hDZ1g","name":"Neeti Sharma","aadObjectId":"37a2516a-baf2-41d8-a406-a067888d676c"},"conversation":{"isGroup":true,"id":"19:acc5f74de5c84d1d9cda18531ff4c92e@thread.skype;messageid=1566441982657","name":null,"conversationType":"channel","tenantId":"9bfb3569-994e-4908-855c-c7f6c1a94100"},"recipient":null,"textFormat":"plain","attachmentLayout":null,"membersAdded":[],"membersRemoved":[],"topicName":null,"historyDisclosed":null,"locale":"en-US","text":"<at>ScanBuddy.ai WebHook</at>&nbsp;\n","speak":null,"inputHint":null,"summary":null,"suggestedActions":null,"attachments":[{"contentType":"text/html","contentUrl":null,"content":"<div><div><span itemscope=\"\" itemtype=\"http://schema.skype.com/Mention\" itemid=\"0\">ScanBuddy.ai WebHook</span>&nbsp;</div>\n</div>","name":null,"thumbnailUrl":null}],"entities":[{"type":"clientInfo","locale":"en-US","country":"US","platform":"Mac"}],"channelData":{"teamsChannelId":"19:acc5f74de5c84d1d9cda18531ff4c92e@thread.skype","teamsTeamId":"19:d4ce49d599e34868863b30bcb2012c0d@thread.skype","channel":{"id":"19:acc5f74de5c84d1d9cda18531ff4c92e@thread.skype"},"team":{"id":"19:d4ce49d599e34868863b30bcb2012c0d@thread.skype"},"tenant":{"id":"9bfb3569-994e-4908-855c-c7f6c1a94100"}},"action":null,"replyToId":null,"value":null,"name":null,"relatesTo":null,"code":null}`

**Comment by Gousia-MSFT** [comment]
@viksakshum The code that you have shared is for bot. Please check this [sample ](https://github.com/microsoftgraph/csharp-teams-sample-graph/tree/master/Node) to fetch the UPN of the user. You could also get the Email address of the user in bots using [Bot Context](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/bots/bots-context).

**Comment by Gousia-MSFT** [comment]
Please re-open if you still face any issues.
