### ISSUE TITLE
Tooltip on Buttons in Adaptive Card displayed poorly

### ISSUE THREAD

**Issue by MajaEffenberg** [MicrosoftDocs/msteams-docs#9028]
Hi there

We've noticed that for some time now when hovering over a button in an adaptive card, a tooltip containing the data for that button is displayed.

Is it possible to remove this tooltip? Because with longer text, it covers the card view and looks bad.
Additionally, in the case of a link, the text does not wrap correctly in the tooltip.

![image](https://github.com/MicrosoftDocs/msteams-docs/assets/89073193/a293d546-2287-4c11-a452-0b89db7ca203)
![image-20230707-141648](https://github.com/MicrosoftDocs/msteams-docs/assets/89073193/bb7dc8be-af96-4448-8120-5f0c01d1347b)

**Comment by Meghana-MSFT** [comment]
1. Currently it is not possible to disable tooltips in Adaptive Card
2. > Additionally, in the case of a link, the text does not wrap correctly in the tooltip.

The same issue has been reported here - https://learn.microsoft.com/en-us/answers/questions/1327542/tooltip-not-working-as-expected-in-microsoft-teams. We have raised a bug for the same. We will keep you posted on the updates.

**Comment by Meghana-MSFT** [comment]
the URL will always be appended to the tooltip even when its value is set by the user. See the following snippet from our conversation
