### ISSUE TITLE
Can we install bot for all users directly in MS Teams? 

### ISSUE THREAD

**Issue by tejasvinishelar** [MicrosoftDocs/msteams-docs#903]
I have uploaded my bot in MS Teams using App Studio.
Now other users of my organization have to install that bot at their side to chat with it.
This is an extra work for them.
How can I make that chat bot as a new chat window without installing it?
Thanks in advance!!

**Comment by Wajeed-msft** [comment]
Please take a look at [Publish apps in the Microsoft Teams Tenant Apps Catalog](https://docs.microsoft.com/en-us/microsoftteams/tenant-apps-catalog-teams) and [Install app for user Graph API](https://docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-beta&tabs=http).

**Comment by tejasvinishelar** [comment]
@Wajeed-msft Thank you for your reply!!
I tried your given link but it is only for installing app for specified user.
How can I install app for all users in my organization?

**Comment by Wajeed-msft** [comment]
@tejasvinishelar - As an admin, you can use app setup policies to customize Microsoft Teams to highlight the apps that are most important for your users. You choose the apps to pin and set the order that they appear. Please take a look at [Manage app setup policies in Microsoft Teams](https://docs.microsoft.com/en-US/microsoftteams/teams-app-setup-policies?WT.mc_id=TeamsAdminCenterCSH) documentation for more details.

**Comment by tejasvinishelar** [comment]
@Wajeed-msft  Thank you!!
