### ISSUE TITLE
pre-made manifest & helloworldapp.zip

### ISSUE THREAD

**Issue by ojasmaru** [MicrosoftDocs/msteams-docs#904]
I don't see any pre-made manifest in the project.

I am using visual studio 2017 to compile the project. I am successfully able to compile the project but I don't see any helloworldapp.zip after compilation.

Am I missing anything?

**Comment by Gousia-MSFT** [comment]
@ojasmaru Which sample are you using? Please have a look at the [HelloWorld sample](https://github.com/OfficeDev/msteams-samples-hello-world-csharp) to get started with.This has a manifest file which you could upload. You could also create the manifest file using the [AppStudio](https://docs.microsoft.com/en-us/microsoftteams/platform/get-started/get-started-app-studio).

**Comment by ojasmaru** [comment]
@Gousia-MSFT,

Thanks for your response. I was able to upload manifest.json file and continue with the rest of the steps. Somehow from the steps, it gave me a feeling that I needed to upload **helloworldapp.zip** to teams app but obviously that was incorrect.

Once again thanks...
