### ISSUE TITLE
A lot of 410 Gone responses from outlook.office.com

### ISSUE THREAD

**Issue by crow-ua** [MicrosoftDocs/msteams-docs#906]
I'm developing one of the most popular Teams integrations, and constantly seeing A LOT (thousands) of 410 Gone responses from `https://outlook.office.com/webhook`  on production. Retries do not help, seems like an unrecoverable error on Office365 side. Recreating connector in Teams sometimes help, but does not look a good workaround in general. Can we gather together and troubleshoot this problem somehow? I'll provide all needed details.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0fd8e4d-f110-36f8-5bd3-db3325b14c01
* Version Independent ID: 717ea854-1d3a-2c15-e495-b6f170fe7aff
* Content: [Using Office 365 Connectors - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/connectors/connectors-using)
* Content Source: [msteams-platform/concepts/connectors/connectors-using.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/connectors/connectors-using.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Wajeed-msft** [comment]
@crow-ua - Are those connectors still configured? If user removes the configuration, you get 410.

**Comment by crow-ua** [comment]
@Wajeed-msft The customer claims that is true, and I myself hit this problem few times too. I will follow-up with them once more to ensure we are not dealing with removed connector.
p.s. Is there any easy way to verify the connector url is still valid other than posting card to it? GET is obviously not implemented and returns 404.

**Comment by Wajeed-msft** [comment]
Currently, only other option would be to post card, check for 410 and cleanup.

We can handle [microsoftTeams.settings.registerOnRemoveHandler()](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/connectors/connectors-creating#handling-removals) and perform cleanup operations such as removing entries from a database.

**Comment by crow-ua** [comment]
@Wajeed-msft We are doing some processing that can be skipped if webhook is dead, but I guess we want to much. Any chance to add GET capability to webhook endpoints that would return 404/410 if the configuration has been removed? `registerOnRemoveHandler` won't help since our integration is stateless and we don't store configurations on our side.

As for originating issue, customer recreated all configurations and I can post cards to his channel just fine. Does not work for him still though.
