### ISSUE TITLE
For outgoing webhook, hmac header is in the Authorization header, not the hmac header

### ISSUE THREAD

**Issue by mooreds** [MicrosoftDocs/msteams-docs#908]
Per the docs here https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/outgoingwebhook : 

"To guarantee the legitimacy of the client (in this case, to guarantee it's Microsoft Teams that's calling you and not someone else, Microsoft Teams provides an HMAC code in the HTTP hmac header."

But I set up a listener and never saw the `hmac` header. Instead, I saw a header like this:

`Authorization:"HMAC 1AIqL6/vQXaAgB+s6+nfsLC9SedJhMed..."`

Docs should be updated to have the correct location of the HMAC value.

(pulled over from https://github.com/MicrosoftDocs/msteams-docs/issues/907 because I wanted it associated with this page)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06c224ae-1484-408c-d17a-e7e1ba07e78a
* Version Independent ID: fac8ff1e-a127-c12a-5304-9de39b1a15c6
* Content: [Outgoing webhooks - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/outgoingwebhook#feedback)
* Content Source: [msteams-platform/concepts/outgoingwebhook.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/outgoingwebhook.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Gousia-MSFT** [comment]
@mooreds Thanks for reaching out. We are working on updating the docs.
