### ISSUE TITLE
Bot doesn't receive any events from Teams for one user 

### ISSUE THREAD

**Issue by Serginyo90** [MicrosoftDocs/msteams-docs#9106]
We have Custom Tab App with Bot (https://learn.microsoft.com/en-us/microsoftteams/apps-in-teams#custom-apps-created-within-an-organization-for-internal-use)
We install our app using policy https://learn.microsoft.com/en-us/microsoftteams/policy-assignment-overview.

User logged in and open the app.

Issue is that bot didn't receive installationUpdate event or any other event for this user.
We also tried to reinstall the app for current user but also don't receive any events.

Expected behavior that bot must receive installationUpdate event for this user.

P.S. We tried 10 another users and bot received the events. So it works for others except one. His aadObjectId - 9f04f209-280e-4fb6-812a-df14c229a74e

**Comment by Nivedipa-MSFT** [comment]
@Serginyo90 - Thanks for reporting your issue. Could you please check the policy configurations for this specific user to see if there are any restrictions or settings that might be affecting the bot's functionality? Compare the policy settings for this user with those of the other users who are using the bot correctly.

**Comment by Serginyo90** [comment]
@Nivedipa-MSFT checked. We don't have some specific policy configurations for this user. So all users have the same policy configurations

**Comment by Nivedipa-MSFT** [comment]
@Serginyo90 - We are checking this internally. We will update you soon.

**Comment by Nivedipa-MSFT** [comment]
@Serginyo90 - Could you please share tenant details to investigate further?

**Comment by Serginyo90** [comment]
@Nivedipa-MSFT Sure. his tenant id is dc7aebbd-65ee-4a5b-963e-bae40cfce25a

**Comment by Nivedipa-MSFT** [comment]
@Serginyo90 - We are checking this with engineering team, we will let you know once we get any updates on it.

**Comment by Serginyo90** [comment]
@Nivedipa-MSFT any updates?

**Comment by Serginyo90** [comment]
I am still waiting update. Why is it marked as requiring author feedback ?

**Comment by Nivedipa-MSFT** [comment]
@Serginyo90 - Apologies for the delay. We are still checking this with engineering team. Currently, we don't have any updates on this. We will keep you informed once we get any updates on it.

**Comment by Serginyo90** [comment]
@Nivedipa-MSFT thank you. Waiting

**Comment by ChetanSharma-msft** [comment]
Hello @Serginyo90 - Sorry for delay in response.
Could you please verify with local debugging if bot receives any event while installing the bot for that particular user.
Alternatively, you can add logs in your application and check if you are getting any error in it.

If you get any error logs, kindly share with us so that we can investigate it further accordingly, if needed.

**Comment by ChetanSharma-msft** [comment]
Hello @Serginyo90 - Could you please try this issue again so that we can check internal logs accordingly?

**Comment by Serginyo90** [comment]
@ChetanSharma-msft @Nivedipa-MSFT We decided to stop using the bot application due to its unpredictable behavior.

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now. Please feel free to reopen if required. Thanks!
