### ISSUE TITLE
https://dev.botframework.com/bots/new is not found

### ISSUE THREAD

**Issue by okulygin** [MicrosoftDocs/msteams-docs#911]
Please update the URL (https://dev.botframework.com/bots/new), it is 404

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 379bdae4-b9d3-bc6e-ecbd-264108d76cd2
* Version Independent ID: b40d773f-d0fd-983f-f063-b3409bdedcef
* Content: [Registering a calling and meeting bot for Microsoft Teams - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/calls-and-meetings/registering-calling-bot#feedback)
* Content Source: [msteams-platform/concepts/calls-and-meetings/registering-calling-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/calls-and-meetings/registering-calling-bot.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by okulygin** [comment]
looks like URL contains '.'

**Comment by clearab** [comment]
Fixed, thanks!
