### ISSUE TITLE
Needs-Triage: MS Teams extension event passed the wrong parameters, resulting in the unavailable zoom extension function

### ISSUE THREAD

**Issue by KaratLee** [MicrosoftDocs/msteams-docs#9117]
<img width="1350" alt="image" src="https://github.com/MicrosoftDocs/msteams-docs/assets/37133480/b21e2a85-c322-4dd4-8b42-19f25c7092ee">
<img width="1429" alt="image" src="https://github.com/MicrosoftDocs/msteams-docs/assets/37133480/8abcb583-a6e2-4c6e-9874-c9f034a3ae71">

The ‘value.data’ passed the string "{}" instead of {} of the object type, which caused our parameter conversion to fail

**Comment by KaratLee** [comment]
There was no such parameter before July 29th, and it suddenly appeared after the 29th, and it was still a wrong parameter. Our service was running well before.

**Comment by KaratLee** [comment]
@Meghana-MSFT Can you help check this issuer,  this impacted us really badly, all of our users couldn't use our product anymore. Thank you very much.

**Comment by ChetanSharma-msft** [comment]
@KaratLee - Thanks for raising your query.
We will look into it and let you know the updates.

**Comment by KaratLee** [comment]
@Meghana-MSFT This field （data:"{}"） should be newly added by Microsoft Teams, because there was no such field before, and our service has not been changed for a long time.

**Comment by Meghana-MSFT** [comment]
@KaratLee - We checked the Zoom extension in both we and Desktop client. It is working fine at our end. We do not see data field in the payload. 
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/81138249/d5f5405b-5d59-4109-a385-c998c350508f)


https://github.com/MicrosoftDocs/msteams-docs/assets/81138249/fa2692b8-3a9f-4007-a5ee-0f4eda8d97c8

Could you please share your Teams version details. Are you facing this issue only on web?

**Comment by KaratLee** [comment]
@Meghana-MSFT Teams client also has problems. Teams client version: 1.6.00.17554

<img width="1727" alt="image" src="https://github.com/MicrosoftDocs/msteams-docs/assets/37133480/495f0129-280d-4945-87c2-691bef0b8a41">

**Comment by Meghana-MSFT** [comment]
We checked it in this version - 1.6.00.20764 (64-bit).

**Comment by KaratLee** [comment]
@Meghana-MSFT This is not a single or occasional problem, almost all of our customers experience this problem

**Comment by KaratLee** [comment]
@Meghana-MSFT Don't use the company intranet, try it with an external network？

**Comment by Meghana-MSFT** [comment]
@KaratLee - I tried this with home network.

**Comment by KaratLee** [comment]
@Meghana-MSFT Can you get someone else to try it, yours is the first one I know that works...

**Comment by KaratLee** [comment]
@Meghana-MSFT Can you help me check why Microsoft Teams sends data: "{}" to us? We will urgently release to remove the data: "{}" in the request data, but this problem has too much impact on our online It’s too big, almost all users are unavailable, can you help check the reason? Thank you very much

**Comment by Meghana-MSFT** [comment]
The fix has reached General ring for Production. Could you please check and confirm once. Thank you.
