### ISSUE TITLE
Browser engine used within Tabs is not stated anywhere

### ISSUE THREAD

**Issue by icatchx22i** [MicrosoftDocs/msteams-docs#912]
Please add what browser is Tabs using to view the data within the iframe. I imagine this is probably IE? or does it just use the default browser on the machine?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c8cce1c-c091-090d-82de-13a57834e240
* Version Independent ID: 13f73468-3c62-d612-dd69-82b43ec31e95
* Content: [Add tabs to Microsoft Teams apps - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/tabs/tabs-overview#feedback)
* Content Source: [msteams-platform/concepts/tabs/tabs-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/tabs/tabs-overview.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by clearab** [comment]
Hi - This is dependent on the client that is used to launch the tab:

For the Teams web app - the iFrame is rendered in the browser that is hosting the Teams app
For Desktop - The iFrame is rendered withing a web view which itself is hosted within the Teams Electron client, hence is Chromium-based.
For iOS - it is rendered within WKWebView (essentially Safari)
For Android - Chromium mobile
