### ISSUE TITLE
Unable to create outgoing webhook

### ISSUE THREAD

**Issue by v-npaladugu** [MicrosoftDocs/msteams-docs#9120]
We have tried creating an outgoing Webhook and we are unable to see this option in demo tenants.

![image](https://github.com/MicrosoftDocs/msteams-docs/assets/91744224/0b3c254c-7436-4010-ad4a-a7c5deef2998)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bb9c5bd5-1ac6-dcc8-4ed6-d6aad2432776
* Version Independent ID: 43e90995-bba4-86b6-1f1c-ab749e546a4b
* Content: [Create an Outgoing Webhook - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-outgoing-webhook?tabs=urljsonpayload%2Cdotnet)
* Content Source: [msteams-platform/webhooks-and-connectors/how-to/add-outgoing-webhook.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/webhooks-and-connectors/how-to/add-outgoing-webhook.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **surbhigupta**

**Comment by Meghana-MSFT** [comment]
We can see the create outgoing webhook option in demo tenants. We checked in both web and Desktop (1.6.00.20764 (64-bit)) Teams clients.
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/81138249/235a0cfb-c881-40a3-94f2-44b395837739)

Could you please confirm if the steps mentioned in this thread are fulfilled?  https://stackoverflow.com/questions/51671071/why-i-cannot-see-create-an-outgoing-webhook-link

**Comment by v-npaladugu** [comment]
Hi @Meghana-MSFT,

I have tried the steps mentioned in this https://stackoverflow.com/questions/51671071/why-i-cannot-see-create-an-outgoing-webhook-link, but still we cant see the option

![image](https://github.com/MicrosoftDocs/msteams-docs/assets/91744224/34325807-0838-4626-be61-b0c0a7712c90)

**Comment by Meghana-MSFT** [comment]
@v-npaladugu - Could you please share the demo credentials with us at microsoftteamsdev@microsoft.com?

**Comment by v-npaladugu** [comment]
Done @Meghana-MSFT, shared credentials with you.

**Comment by Meghana-MSFT** [comment]
@v-npaladugu - We see that user has a policy assigned in which upload custom apps has been disabled. Upload custom apps needs to be enabled so that user can see the option "create an outgoing webhook".

**Comment by v-npaladugu** [comment]
Thanks @Meghana-MSFT, can you add doc label if needed for this feedback

**Comment by Meghana-MSFT** [comment]
@v-npaladugu - There is no update required. Thank you.

**Comment by Meghana-MSFT** [comment]
@v-npaladugu - There is no doc update required. Thank you.

**Comment by Meghana-MSFT** [comment]
We are closing this issue, please feel free to reach out to us if you need further help. Thank you.
