### ISSUE TITLE
smaller window size pushes the thread of the main content panel behind the left-sidebar

### ISSUE THREAD

**Issue by BryantVail** [MicrosoftDocs/msteams-docs#913]
Microsoft Teams 'Responsiveness' needs support, a smaller window size pushes the thread of the main content panel behind the left-sidebar (this is occurring in at least 'Chat', and 'Teams') consistently on the most up to date version of Teams, on Windows & Mac computer machines.

**Comment by Wajeed-msft** [comment]
Could you please share screenshot of the issue?

**Comment by Gousia-MSFT** [comment]
@BryantVail Thanks for sharing the screenshot. We are looking into it.

**Comment by Gousia-MSFT** [comment]
@BryantVail This is the expected behavior. If you scale the window smaller until the left rail collapses and then click on an app in the app bar, the left rail becomes sticky and doesn't go away until you click outside of it. If you scale the window smaller until the left rail collapses and hover on an app in the app bar, the left rail will appear and you can dismiss it by hovering outside of it.

**Comment by BryantVail** [comment]
Thanks for the quick reply. I saw how it was the expected behavior, but its not behavior sufficient to view & interact efficiently when the window is beyond a pre-defined window size. I use Windows Text Editors -among other programs but where text editors probably try to incorporate more apps/functions in a single workspace- and it seems appropriate to not limit the implementation of sidebar re-sizing, or explicit pin/un-pin of the sidebar content. 

I know y'all build apps that have to juggle a lot of features, Microsoft Teams is ambitious- and its already impacting our workflow at WeCareTLC (Lake Mary, FL) in positive ways. As far as utility, I often sacrifice the size of my sidebar in the text editor in favor of the main content panel, but I'm also constantly looking for changes in files, and file structure to jog my memory, or quickly shuffle between tasks; I can determine whether I need to expand the sidebar if absolutely necessary to read titles/teams during normal use- currently, the inflexibility of the sidebar to be more explicitly manipulated is creating an undue burden on users to engage as seamlessly as possible- and essentially trying to embrace the concept of the all-in-one tool like Teams. Its a great product, Its important to us as a company, and I take seriously my own role in trying to advocate for great tools in the market such as this. 

SidebarInterests: [
--"pin and un-pin",
--"drag the edge of the sidebar to change width",
--"max-width"
--"very small minimum-width"
]

![image](https://user-images.githubusercontent.com/13971942/64038791-fe783f80-cb26-11e9-8677-dea89fa87e6b.png)

**Comment by Gousia-MSFT** [comment]
@BryantVail Thanks for reaching out. I will check internally if there are plans to change this behaviour.

**Comment by Gousia-MSFT** [comment]
@BryantVail This might be addressed later next calendar year, but there are no near-term plans to change this.
