### ISSUE TITLE
Creating your assets describes 3 icons. Manifest only uses 2.

### ISSUE THREAD

**Issue by aosolis** [MicrosoftDocs/msteams-docs#9130]
This section describes color, rest and hover icons. https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/design/design-teams-app-icon-store-appbar#creating-your-assets
Manifest only has 2 icons: color and outline.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c4c59da9-c9a3-ac3f-86ca-d40bae04555f
* Version Independent ID: c4c59da9-c9a3-ac3f-86ca-d40bae04555f
* Content: [Design your app - App icon for store and app bar - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/design/design-teams-app-icon-store-appbar)
* Content Source: [msteams-platform/concepts/design/design-teams-app-icon-store-appbar.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/design/design-teams-app-icon-store-appbar.md)
* Service: **msteams**
* GitHub Login: @heath-hamilton
* Microsoft Alias: **lajanuar**

**Comment by Nivedipa-MSFT** [comment]
@aosolis - Thanks for reporting your issue. We will check this and update you soon.

**Comment by ChetanSharma-msft** [comment]
Hello @surbhigupta12 - We generally configure 2 icons in the Manifest like `color.png` and `outline.png`.
Could you please help us to remove the 3rd icon if not needed.

![image](https://github.com/MicrosoftDocs/msteams-docs/assets/59052547/74fef1a4-e724-4a8d-a096-362e2b3ae257)

https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/design/design-teams-app-icon-store-appbar#creating-your-assets
