### ISSUE TITLE
Ensure creating of new Outlook webhook every time new connector is added to channel

### ISSUE THREAD

**Issue by crow-ua** [MicrosoftDocs/msteams-docs#918]
We have following code that creates connector on our configuration page (essentially an excerpt from ToDo connector sample):
```
microsoftTeams.settings.setSettings({
	entityId: "myConnector",
	contentUrl: window.location.href,
	configName: "Connector added by msteams@user"
});
```
It creates the same url every time.
How to ensure resulting webhook url that is generated when we do `getSettings` later is new and unique? Should we add some guid to `entityId` or `configName`? I don't think it's documented anywhere. I've tried Jira Cloud connector, it has such feature, but it uses non-generic webhook url format that is special for Jira Cloud Connector and is handled presumably on the server-side.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c21a27c1-d01a-6cc7-c991-73af6492aad8
* Version Independent ID: b15d2142-df29-250e-9a0a-b734dcb93162
* Content: [Office 365 Connectors - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/connectors/connectors-creating)
* Content Source: [msteams-platform/concepts/connectors/connectors-creating.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/connectors/connectors-creating.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by crow-ua** [comment]
@Wajeed-msft I guess you may have some insight on the above.

**Comment by Wajeed-msft** [comment]
@crow-ua - You get a different Webhook URL every time you configure the Connector. Could you please check it one more time if you are getting same URL? If you have manifest which we can use to repro, please send it to Microsoft Teams developer support alias mention on [Feedback channel](https://docs.microsoft.com/en-us/microsoftteams/platform/feedback).
