### ISSUE TITLE
Switching tenants doesn't work after using web launcher

### ISSUE THREAD

**Issue by Alexees** [MicrosoftDocs/msteams-docs#919]
I'm member of two tenants A, member, and B, guest. 
When I'm on A and open a channel of B through the summary email (web launcher, don't know what to call it), teams opens and asks to switch to tenant B, which works.
But switching back to A shows a popup if I want to switch to B, which I can acknowledge or cancel. Cancel, as the only option to remain on A leaves the tenant blank as if I was in some kind of void state, neither in A nor B.
I have to restart Teams to get back into A.
This only happens when the web launcher triggers a tenant switch.

**Comment by Wajeed-msft** [comment]
@Alexees - Is this what you are referring as void state?
![image](https://user-images.githubusercontent.com/31851992/63939694-7ee66400-ca85-11e9-9d1f-6f4be929586d.png)
Could you please confirm if clicking on Activity or Chat rendering UI fine for you?
![image](https://user-images.githubusercontent.com/31851992/63939740-9887ab80-ca85-11e9-90b3-b0f1253f8a49.png)

**Comment by Alexees** [comment]
@Wajeed-msft yes, that's the state I am talking about. Selecting for example Chat does show the chat, but my status is "Offline" and I am not entirely sure what else is broken in this case.
Manually trying to go online does not work.
Switching tenants back and forth seems to fix that, but the dialogue about switching to the tenant I came from remains.

**Comment by Gousia-MSFT** [comment]
@Alexees Thanks for reporting this. We have raised a bug for this and we are looking into it.

**Comment by Gousia-MSFT** [comment]
This is being tracked internally.
