### ISSUE TITLE
Pinned app in Teams shows never-ending spinning wheel (in absence of SharePoint cookies?)

### ISSUE THREAD

**Issue by GoalinSightAgain** [MicrosoftDocs/msteams-docs#9211]
I am having an issue nearly identical in presentation to that in #3725.

I attempted to follow the fix that proved effective in that thread by
1. Modifying the app manifest to include webApplicationInfo, per the recommendations [here](https://stackoverflow.com/questions/57593508/sharepoint-page-not-loading-in-personal-tab-of-static-app-ms-teams-desktop-clie/57770834#57770834).
2. Uploading an app package to the Teams admin center with the modified app manifest. I then waited to ensure the new version had fully loaded in Teams.

Still, when I access the pinned personal app containing the SharePoint site after clearing my Teams application cache, I get only a spinning wheel, as do any users who haven't previously accessed the SharePoint site within Teams.

I'd welcome any help you can provide! Two files attached:
- [app manifest](https://github.com/MicrosoftDocs/msteams-docs/files/12324848/manifest-srobinson-teams-cookie-issue-pinned-sharepoint-site.txt)
- [console logs](https://github.com/MicrosoftDocs/msteams-docs/files/12323793/teams.microsoft.com-1691772650152.log), which contained some errors

**Comment by sayali-MSFT** [comment]
@GoalinSightAgain -: Thanks for reporting your issue.
We will check this at our end and will get back to you.

**Comment by GoalinSightAgain** [comment]
Ah ha! I have resolved the issue. It seems the culprit was an incorrect AAD application ID in the webApplicationInfo section of the app manifest. Rather than using the ID specific to the personal app, I needed to use the generic AAP app ID for SharePoint:

```
 "webApplicationInfo": {
    "resource": "https://[myTenantName].sharepoint.com/",
    "id": "00000003-0000-0ff1-ce00-000000000000"
  }
```
Thanks for the offer to take a look at this.

**Comment by sayali-MSFT** [comment]
@GoalinSightAgain - Glad to hear that your issue is resolved.
We are closing this issue for now, please feel free to reopen it, if required.
