### ISSUE TITLE
[Mobile] Secondary Button Will NOT Display After Clicking "..."

### ISSUE THREAD

**Issue by zinc0x1E** [MicrosoftDocs/msteams-docs#9212]
# Expected Behavior

Given user is using mobile card with serveral secondry mode action,
When user click the "..." button
Then secondary mode buttons should display

# Actual Behavior

When user click the "..." button
Then nothing happens

# Example Card Json

```json
{
"type": "AdaptiveCard",
"body": [
{
"type": "TextBlock",
"size": "Medium",
"weight": "Bolder",
"text": "title"
},
{
"type": "TextBlock",
"text": "description",
"wrap": true
},
{
"type": "ActionSet",
"actions": [
{
"type": "Action.Submit",
"title": "Action.Submit",
"mode": "secondary"
},
{
"type": "Action.Submit",
"title": "Action.Submit",
"mode": "secondary"
}
]
}
],
"$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
"version": "1.5"
}
```

# Recording

https://github.com/MicrosoftDocs/msteams-docs/assets/34705216/1509531d-3ef8-4127-8006-ce5d1e14307a

**Comment by Nivedipa-MSFT** [comment]
@zinc0x1E - Thanks for reporting your issue. We will test this and update you soon.

**Comment by zinc0x1E** [comment]
Hi @Nivedipa-MSFT , our adaptive card is embaded in task module, so the reproduction steps will be:
1. Open iOS or Android teams app
2. Open a task module with provided example card (hope you have proper tool for that)
3. Click the "..." button
4. [Expected] 2  "Action.Submit" button display
5. [Actual] Nothing happens

**Comment by zinc0x1E** [comment]
hi @Nivedipa-MSFT, any updates on this issue?

**Comment by Nivedipa-MSFT** [comment]
@zinc0x1E - We have conducted the same test you mentioned, and upon clicking the "Action.Submit" button, the call proceeds to the OnMessageActivityAsync() method, and the associated code is executing.

Could you kindly provide a screen recording to help us gain a clearer understanding of the process?

**Comment by Nivedipa-MSFT** [comment]
@zinc0x1E - Could you please confirm whether your issue has been resolved or not? If not, could you kindly provide a screen recording to help us better understand the process?

**Comment by zinc0x1E** [comment]
Hi team, I believe the problem still exists. for the screen recording, please refer to the one I enclosed at the very first of this thread. Before the recording, we just open a task module with given card json through a debug app.

**Comment by zinc0x1E** [comment]
Hi Team, any updates on this issue? I'm not sure the effect of `OnMessageActivityAsync()`, but the behaviour is not the expected.

**Comment by ChetanSharma-msft** [comment]
Hello @zinc0x1E - I have tested it recently via sending the card using Developer Portal from Teams client and it is working for me.
I have used same JSON shared by you:

![image](https://github.com/MicrosoftDocs/msteams-docs/assets/59052547/3da3b448-50ae-40c6-8369-f95cf6f372ee)


Reference doc link: 
https://adaptivecards.io/explorer/Action.Submit.html

Note: Whatever the properties mentioned in the AdaptiveCard.io may not work in Teams client, if we send it using Teams bot etc.
