### ISSUE TITLE
[Adaptive Card- Action.ShowCard] Action.ShowCard didn't work in "mode": "secondary" setting

### ISSUE THREAD

**Issue by sherryzhao11** [MicrosoftDocs/msteams-docs#9223]

**Comment by sherryzhao11** [comment]
'Action.ShowCard' doesn't work in "mode": "secondary".
Used to work.
Old working recording
https://github.com/MicrosoftDocs/msteams-docs/assets/132635147/50c67500-d9c9-402d-9567-5865583d5a53
New doesn't work recording:
https://github.com/MicrosoftDocs/msteams-docs/assets/132635147/09d00f65-1e69-49f0-bb5d-3310631509aa

same card json schema:

{
    "type": "AdaptiveCard",
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.5",
    "body": [
        {
            "type": "TextBlock",
            "text": "Please confirm your data:",
            "wrap": true,
            "style": "heading"
        },
        {
            "type": "FactSet",
            "facts": [
                {
                    "title": "First Name",
                    "value": "John"
                },
                {
                    "title": "Last Name",
                    "value": "Smith"
                },
                {
                    "title": "Phone number ",
                    "value": "(555) 555-5555"
                }
            ]
        }
    ],
    "actions": [
        {
            "type": "Action.Execute",
            "id": "1",
            "title": "Confirm data"
        },
        {
            "type": "Action.ShowCard",
            "title": "Edit data",
            "id": "2",
            "data": "edit",
            "card": {
                "type": "AdaptiveCard",
                "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
                "version": "1.5",
                "body": [
                    {
                        "type": "TextBlock",
                        "text": "New TextBlock",
                        "wrap": true
                    }
                ]
            }
        },
        {
            "type": "Action.ShowCard",
            "title": "Delete data",
            "data": "delete",
            "id": "3",
            "mode": "secondary",
            "card": {
                "type": "AdaptiveCard",
                "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
                "version": "1.5",
                "body": [
                    {
                        "type": "TextBlock",
                        "text": "New TextBlock",
                        "wrap": true
                    }
                ]
            }
        }
    ]
}

**Comment by Prasad-MSFT** [comment]
@sherryzhao11 - Thanks for reporting this. We will check it from our end and will update you with our findings.

**Comment by Prasad-MSFT** [comment]
@sherryzhao11 - We are able to repro this issue. We have raised a bug for the same. We will inform you once we get any further update from engineering team. Thanks!

**Comment by sherryzhao11** [comment]
@Prasad-MSFT Thanks for this.

**Comment by Prasad-MSFT** [comment]
Currently there is no ETA to share. But we will update this thread once we hear any info from engineering team.
Thanks!

**Comment by Prasad-MSFT** [comment]
Hi @sherryzhao11, we got update from engineering team that, this is by design and is not recommended to do add Show card action to secondary mode actions (overflow menus).
