### ISSUE TITLE
Microsoft Teams and Microsoft Outlook log eachother out when logging in on Android

### ISSUE THREAD

**Issue by brokenthorn** [MicrosoftDocs/msteams-docs#923]
With MFA on, on Android, each time one of Teams or Outlook signs in, the other gets signed out, or their session token gets replaced, revoked or deleted. I can reproduce this easily. When I open Teams, if it's signed out, it asks for sign in, after succesful sign in, Outlook shows a notification that I need to sign in again, and vice-versa is similar.

EDIT: It turns out it isn't that easy to reproduce, at least not in sequence, while trying to record the screen to demo the issue.

**Comment by Gousia-MSFT** [comment]
@brokenthorn We could not repro this on our side. Could you please share a video recording of the issue?

**Comment by brokenthorn** [comment]
@Gousia-MSFT I will have to try. My first attempt didn't work although on the recording it is quite evident that the first thing I do is open Outlook and it starts by logging in.

**Comment by Gousia-MSFT** [comment]
@brokenthorn Please capture a video recording the next time you see the issue. It will be helpful for our mobile team to investigate this.
