### ISSUE TITLE
[Feature Request] Set style of adaptive card to Fluent UI style.

### ISSUE THREAD

**Issue by qjkobe** [MicrosoftDocs/msteams-docs#9253]
# Problem Statement
The style of adaptive card is different from that of fluent UI.
For example, here is the input box of fluent UI: https://react.fluentui.dev/?path=/docs/components-input--default
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/16449598/37533c65-c58a-4366-93bc-08225558b405)
It has a white background color. But in adaptive card, the input is like below:
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/16449598/57001bca-5a79-4aae-a110-86e2b18023f2)
Can we make the adaptive card input control's background color also white? Actually the grey color will confuse our customers.

# Proposed solution
There is a property to control the theme of adaptive card. We can change the rendering style of adaptive card by change this proprty.

I raised the same issue in adaptive card side. But no one reply me.https://github.com/microsoft/AdaptiveCards/issues/8643

**Comment by ChetanSharma-msft** [comment]
Hello @qjkobe - Thanks for raising your query.
Could you please confirm whether you are posting and displaying the Adaptive Card in Teams?

**Comment by Nivedipa-MSFT** [comment]
@qjkobe - Thanks for your feedback. You can suggest this feature here: [Microsoft Teams Community](https://feedbackportal.microsoft.com/feedback/forum/ad198462-1c1c-ec11-b6e7-0022481f8472).

**Comment by qjkobe** [comment]
> Hello @qjkobe - Thanks for raising your query. Could you please confirm whether you are posting and displaying the Adaptive Card in Teams?

Hi,
Yes, I'm developing Teams App and posing adaptive card in Teams. But the style is totally different between adaptive card and fluent ui(V9). Someone in Microsoft replied to me that adaptive card used a old fluent style but MS was trying to push fluent v9.
