### ISSUE TITLE
Messages that created by the teams import API got marked as deleted.

### ISSUE THREAD

**Issue by qquiuc** [MicrosoftDocs/msteams-docs#9260]
Hi Team 

We are performing a migration from Microsoft teams,  and we use the API https://learn.microsoft.com/en-us/microsoftteams/platform/graph-api/import-messages/import-external-messages-to-teams to create messages in the destination, but after the complete action, the team is available in the destination, but all the messages are marked as deleted, then I use the graph api explorer to retrieve the messages, seems the  property "deletedDateTime" has same value as the "createdDateTime" it's not normal for a message, please help to find the root cause of this issue.
Messages got from API: https://graph.microsoft.com/v1.0/teams/9313518c-ff63-4ca3-8405-0da67431a8af/channels/19:ccd53c50499e41da8ec800c168e6aac1@thread.tacv2/messages?$top=50

![WXWorkCapture_1692351559406](https://github.com/MicrosoftDocs/msteams-docs/assets/18695819/3494c226-c1d7-4fc8-8c51-a163a989b87a)

![WXWorkCapture_16923513692115](https://github.com/MicrosoftDocs/msteams-docs/assets/18695819/9fa3644e-5b7d-40f6-90b3-4ab768219b95)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e5687f17-f3c7-39be-5487-f24f2155191a
* Version Independent ID: ce77e760-90cf-e6b1-3cec-ae55ee50c33e
* Content: [Use Microsoft Graph to import external platform messages to Teams - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/graph-api/import-messages/import-external-messages-to-teams)
* Content Source: [msteams-platform/graph-api/import-messages/import-external-messages-to-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/graph-api/import-messages/import-external-messages-to-teams.md)
* Service: **msteams**
* GitHub Login: @AkJo
* Microsoft Alias: **surbhigupta**

**Comment by sayali-MSFT** [comment]
@qquiuc - Thanks for reporting your issue.
We will check this at our end and will get back to you.

**Comment by sayali-MSFT** [comment]
@qquiuc -Could you please share few traces? So that we can investigate from our end.

**Comment by qquiuc** [comment]
[developer.microsoft.com.har.zip](https://github.com/MicrosoftDocs/msteams-docs/files/12522260/developer.microsoft.com.har.zip)
The har file is uploaded, please remove the .".zip" then open the file.
Thanks

**Comment by sayali-MSFT** [comment]
@qquiuc -We are not able to open the file. Could you please share it once again?

**Comment by qquiuc** [comment]
It's a HAR record from edge browser, you need to open it with a notepad
[developer.microsoft.com.zip](https://github.com/MicrosoftDocs/msteams-docs/files/12544415/developer.microsoft.com.zip)
un-zip it then open with a notepad

**Comment by sayali-MSFT** [comment]
@qquiuc -Thanks for providing the information. We will inform the engineering team and let you know the update once we have any.

**Comment by Javierif** [comment]
Same issue here, @sayali-MSFT  Do you have any updates regarding this bug?

**Comment by Prasad-MSFT** [comment]
@Javierif - Are these messages visible on Teams client? Could you please record when you are posting the messages not getting them?
