### ISSUE TITLE
Deeplink to open the 'Files' tab of a channel

### ISSUE THREAD

**Issue by PieterVandendriessche** [MicrosoftDocs/msteams-docs#9267]
Hi there. 

I want to achieve the goal to open the 'Files' tab of a channel by using a deeplink url. I was not able to find any documentation that describes this situation, is it missing?

At the moment we have an url to open the files tab, but this opens in the browser, not the native client:
https://teams.microsoft.com/_?#/FileBrowserTabApp/General?groupId=<groupId>&threadId=<threadId>&ctx=channel

In case this is not supported, is this on the planning to support this? 

Thanks in advance for the feedback.

**Comment by Nivedipa-MSFT** [comment]
@PieterVandendriessche - Thanks for reporting your issue. We will check this and update you soon.

**Comment by PieterVandendriessche** [comment]
Hi @Nivedipa-MSFT 

That indeed seems to work. However, when using a deeplink in teams it is almost always prompting the user to either open it in browser or native client.

We want to achieve that when a person is clicking on that link in the browser, the deeplink is executed like other deeplinks and prompts the user to pick a location. When clicking on the link in the native client it should behave like you have shown in the video.

Thanks for your feedback

**Comment by Nivedipa-MSFT** [comment]
@PieterVandendriessche - If the Teams app is running within the host where the deep link is targeted, your app opens directly within the host. However, if the Teams app is running in a different host from where the deep link is targeted, the app will first open in the browser.

Ref Doc: https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-link-application?tabs=teamsjs-v2#:~:text=If%20the%20Teams%20app%20is%20running%20within%20the%20host%20where%20the%20deep%20link%20is%20targeted%2C%20your%20app%20opens%20directly%20within%20the%20host.%20However%2C%20if%20the%20Teams%20app%20is%20running%20in%20a%20different%20host%20from%20where%20the%20deep%20link%20is%20targeted%2C%20the%20app%20will%20first%20open%20in%20the%20browser.

**Comment by PieterVandendriessche** [comment]
Hi @Nivedipa-MSFT 

Thanks, seems indeed to work. Apprarently the url of my deeplink was malformed.
https://teams.microsoft.com/_?#/FileBrowserTabApp/General?groupId=&threadId=&ctx=channel 
should be
https://teams.microsoft.com/_#/FileBrowserTabApp/General?groupId=&threadId=&ctx=channel

I think this issue can be closed

**Comment by Nivedipa-MSFT** [comment]
@PieterVandendriessche - Glad to hear that your issue is resolved. Could you please share your valuable feedback via [Microsoft Teams Developer Community Response Feedback](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR7iCOpS5_b9Nqmwx43u5rtZUOThVR081SllSR05aSDQxQ0tUMDVPTVIxTi4u).

**Comment by Nivedipa-MSFT** [comment]
@PieterVandendriessche - We are closing this issue for now. Please feel free to reopen if required.

**Comment by Nivedipa-MSFT** [comment]
@PieterVandendriessche - We are closing this issue for now. Please feel free to reopen if required.

**Comment by Prasad-MSFT** [comment]
> This isn't working anymore in the new teams: deep links for filebrowsertabapp not working anymore: format : https://teams.microsoft.com/_#/FileBrowserTabApp/General?groupId=&threadId=&ctx=channel
> 
> example: https://teams.microsoft.com/_#/FileBrowserTabApp/General?threadId=19:cd614dd548474436bf4e7acd5dc36286@thread.tacv2&ctx=channel

This is being tracked [here](https://github.com/MicrosoftDocs/msteams-docs/issues/9713). Please follow that thread for further updates.

**Comment by nicoleahmed** [comment]
The support over at that thread doesn't seem to consider this an issue. Is there a new way to deep  link to the files tab in a channel?

**Comment by ChetanSharma-msft** [comment]
Hello @nicoleahmed & Everyone,
Sorry for delay in response.

The entity deep link can be used as documented here:
https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-link-application?tabs=teamsjs-v2#configure-deep-link-to-browse-within-your-app-manually
 
The app ID of the Channel Files Tab is `3ed5b337-c2c9-4d5d-b7b4-84ff09a8fc1c` and the entityId is `FileBrowserTabApp`. 
So, the deep link to it would look something like this:
`https://teams.microsoft.com/l/entity/3ed5b337-c2c9-4d5d-b7b4-84ff09a8fc1c/FileBrowserTabApp?context=%7B%22channelId%22%3A%22CHANNEL_ID%22%7D`
 
The context should contain the CHANNEL_ID of the channel where the Files tab is to be opened, for example:
```
let context = {
  "channelId": "19:cd614dd548474436bf4e7acd5dc36286@thread.tacv2"
};
let deeplink = "https://teams.microsoft.com/l/entity/3ed5b337-c2c9-4d5d-b7b4-84ff09a8fc1c/FileBrowserTabApp?context=" + encodeURIComponent(JSON.stringify(context));
```
 
With the final deeplink looking something like this:
`https://teams.microsoft.com/l/entity/3ed5b337-c2c9-4d5d-b7b4-84ff09a8fc1c/FileBrowserTabApp?context=%7B%22channelId%22%3A%2219%3Acd614dd548474436bf4e7acd5dc36286%40thread.tacv2%22%7D`

We have tried and it is working fine for us as well.

Similar issue: https://github.com/MicrosoftDocs/msteams-docs/issues/9713

**Comment by nicoleahmed** [comment]
Can confirm the deep link format worked for me in old and new tems for Windows / and web app
But there is a big in the msteams URI implementation  similar to what is report here https://github.com/MicrosoftDocs/msteams-docs/issues/9802#issuecomment-1875025956 

clicking on a link formatted like this:
`https://teams.microsoft.com/l/entity/3ed5b337-c2c9-4d5d-b7b4-84ff09a8fc1c/FileBrowserTabApp?context=%7B%22channelId%22%3A%22<CHANNEL_ID>%22%7D`

-opens the channel file tab in teams directly if clicked from within teams app
-opens the browser with a prompt to use desktop app or web app if the link is clicked from outside of the teams app
-with the chrome extension "[Teams and Bluejeans closer](https://chromewebstore.google.com/detail/teams-and-bluejeans-close/dobpbiifmofcdlaagglbchamihcmooff)" installed, browser page is opened then desktop app automatically opened & tab closed, if the link is clicked from outside of the teams app

**If making the links manually put the channel id bit before "@thread.tacv2" here:**
`https://teams.microsoft.com/l/entity/3ed5b337-c2c9-4d5d-b7b4-84ff09a8fc1c/FileBrowserTabApp?context=%7B%22channelId%22%3A%2219%3A<HERE>%40thread.tacv2%22%7D`

**The msteams uri implementation has bugs however - as has been reported here** https://github.com/MicrosoftDocs/msteams-docs/issues/9802#issuecomment-1875025956

In old teams replacing https:// with the msteams:// URI protocol allows for external app links directly to the files tab of a channel:
`msteams://teams.microsoft.com/l/entity/3ed5b337-c2c9-4d5d-b7b4-84ff09a8fc1c/FileBrowserTabApp?context=%7B%22channelId%22%3A%22<CHANNEL_ID>%22%7D`

In new teams there is a bug where only the following URI formatting works for external apps link directly to the files tab of a channel:
`msteams:/l/entity/3ed5b337-c2c9-4d5d-b7b4-84ff09a8fc1c/FileBrowserTabApp?context=%7B%22channelId%22%3A%22<CHANNEL_ID>%22%7D`
