### ISSUE TITLE
Support for Static Tabs in the "NEW" teams client?

### ISSUE THREAD

**Issue by GauravES** [MicrosoftDocs/msteams-docs#9268]
When will Microsoft roll out support for Static Tabs in the NEW teams desktop client?  Currently all our LOB apps that work fine in the current teams client fail to open the static tabs in the new client.   (our tabs are personal scope)

NEW = https://learn.microsoft.com/en-us/microsoftteams/new-teams-desktop-admin
Static Tabs = https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs?tabs=desktop%2Cdesktop1%2Cpersonal

Also, can Microsoft please come up with a better naming convention atleast for ISVs and Devs to report issues with this new client?  Referring to it as new client is ambiguous.  Is there a Major version number we can use?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 62b12649-8660-975a-87f6-2f7486b5dc79
* Version Independent ID: c1b86714-5b2e-79a8-5761-0fb2fd5746c0
* Content: [Microsoft Teams tabs - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs?tabs=desktop%2Cdesktop1%2Cpersonal)
* Content Source: [msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/tabs/what-are-tabs.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **surbhigupta**

**Comment by sayali-MSFT** [comment]
@GauravES - Thanks for reporting your issue.
We will check this at our end and will get back to you.

**Comment by sayali-MSFT** [comment]
@GauravES -We have tested the Static Tab scenario with the new Teams client, and it is displaying properly.
Could you please share the Teams version you have tested?
![new client Tab](https://github.com/MicrosoftDocs/msteams-docs/assets/93527375/145ee6e2-0a3c-4062-9acd-687750f2ff89)
