### ISSUE TITLE
Possible bug in "Get the user context" sample code

### ISSUE THREAD

**Issue by HiltonGiesenow** [MicrosoftDocs/msteams-docs#928]
I think 

if (loginHint) {
    config.extraQueryParameter = "scope=openid+profile&login_hint=" + encodeURIComponent(loginHint);
...

should actually be
if (context.loginHint) {
    config.extraQueryParameter = "scope=openid+profile&login_hint=" + encodeURIComponent(context.loginHint);
...

(note the addition of the "context." in two places)

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be314181-4800-4d02-cf62-fb276dc7cdd2
* Version Independent ID: 259e41a3-0607-c3f8-f635-f6bce767ad2b
* Content: [Silent authentication and SSO - Teams](https://docs.microsoft.com/en-gb/microsoftteams/platform/concepts/authentication/auth-silent-AAD#feedback)
* Content Source: [msteams-platform/concepts/authentication/auth-silent-AAD.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/authentication/auth-silent-AAD.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Wajeed-msft** [comment]
@HiltonGiesenow - These code snippets are copied from the [Microsoft Teams Authentication Sample](https://github.com/OfficeDev/microsoft-teams-sample-auth-node/blob/master/src/views/tab/silent/silent.hbs#L71) which has complete code. In documentation we have kept only relevant snippets for better understanding. 

Similar [issue](https://github.com/MicrosoftDocs/msteams-docs/issues/930).
