### ISSUE TITLE
[Rendering] [Adaptive Card- Action.ShowCard] Action.ShowCard didn't work in "mode": "secondary" setting

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#9287]
Copied bug from: https://github.com/microsoft/AdaptiveCards/issues/8652 

**Details from original post:**
### Target Platforms

NodeJS

### SDK Version

1.5

### Application Name

MS Teams

### Problem Description

Action.ShowCad button doesn't work in "secondary" mode.

https://github.com/microsoft/AdaptiveCards/assets/132635147/0ffd93a4-968a-4d8f-b61e-3b2feaad2292

### Card JSON

```JSON
{
    "type": "AdaptiveCard",
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.5",
    "body": [
        {
            "type": "ActionSet",
            "actions": [
                {
                    "type": "Action.ShowCard",
                    "title": "Action.ShowCard",
                    "card": {
                        "type": "AdaptiveCard"
                    }
                },
                {
                    "type": "Action.ShowCard",
                    "title": "Action.ShowCard",
                    "card": {
                        "type": "AdaptiveCard"
                    },
                    "mode": "secondary"
                },
                {
                    "type": "Action.ShowCard",
                    "title": "Action.ShowCard",
                    "card": {
                        "type": "AdaptiveCard"
                    },
                    "mode": "secondary"
                }
            ]
        }
    ]
}
```

### Sample Code

_No response_---
#### Document Details

⚠ *Do not edit this section.It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Cards reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **surbhigupta12**

**Comment by ChetanSharma-msft** [comment]
Hello @sherryzhao11 - Thanks for raising your query.
We will look into it and let you know the updates.

**Comment by Prasad-MSFT** [comment]
Hi @sherryZhao11 - This issue is being tracked [here](https://github.com/MicrosoftDocs/msteams-docs/issues/9223). Please follow that thread for further updates.

Closing this thread.
