### ISSUE TITLE
[Authoring] We cannot add any style to a button and the align-center property doesn't work

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#9299]
Copied bug from: https://github.com/microsoft/AdaptiveCards/issues/8645 

**Details from original post:**
### Target Application

Microsoft Teams

### Application Operating System

iOS

### Schema Version

1.5

### Problem Description

1. We cannot add any style to adaptive card. The adaptive card has a property called style. It has 2 optional values. One is positive, the other is destructive. If I change the style and render it by Bot Framework Web Chat, it will be like:
![image](https://github.com/microsoft/AdaptiveCards/assets/16449598/98048767-683c-421a-807a-7e2c3d04a52e)
But if I change the render engine to Teams, it will be like: 
![image](https://github.com/microsoft/AdaptiveCards/assets/16449598/d4752522-4a4f-4b6b-b52d-eb3243cb45a8)
2. If we set horizontalAlignment of ActionSet to true, the button inside it will be like:
![image](https://github.com/microsoft/AdaptiveCards/assets/16449598/ae9b56dc-f5ec-4054-8a0b-7260b3242f49)
But it doesn't work in Teams app. The button will be align-right automatically:
![image](https://github.com/microsoft/AdaptiveCards/assets/16449598/5e19afbd-a2f9-49e6-bf01-657a522635bc)

### Expected Outcome

1. We can change style of buttons.
2. We can align buttons to left, right or center.

### Actual Outcome

1. The style of buttons don't change.
2. The button alignment cannot be controlled by us. It will be align-right automatically.

### Card JSON

```JSON
{
    "type": "AdaptiveCard",
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.5",
    "body": [
        {
            "type": "ActionSet",
            "actions": [
                {
                    "type": "Action.Submit",
                    "title": "positive",
                    "style": "positive"
                },
                {
                    "type": "Action.Submit",
                    "title": "destructive",
                    "style": "destructive"
                }
            ],
            "spacing": "None",
            "horizontalAlignment": "Center"
        }
    ],
    "actions": [
        {
            "type": "Action.Submit",
            "title": "default"
        }
    ]
}
```

### Repro Steps

_No response_---
#### Document Details

⚠ *Do not edit this section.It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Cards reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **surbhigupta12**

**Comment by Prasad-MSFT** [comment]
This issue is being tracked [here](https://github.com/MicrosoftDocs/msteams-docs/issues/9254). Please follow that thread for further updates.


Closing this thread.
