### ISSUE TITLE
Remove the section here about adding more parameters

### ISSUE THREAD

**Issue by aosolis** [MicrosoftDocs/msteams-docs#9306]
Search commands don't support multiple parameters. Only 1 text parameter is supported.
Please remove the section here about adding more parameters to a search command.
<img width="623" alt="image" src="https://github.com/MicrosoftDocs/msteams-docs/assets/767208/c0394e28-8d9f-4de2-8d94-4028cfdb413a">

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 06016378-5b30-cc4e-e53a-a9c46a2a3a13
* Version Independent ID: d013f99a-0ee5-67d3-ee79-67bc1a0b4557
* Content: [Define message extension search commands - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/search-commands/define-search-command)
* Content Source: [msteams-platform/messaging-extensions/how-to/search-commands/define-search-command.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/messaging-extensions/how-to/search-commands/define-search-command.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **anclear**

**Comment by ChetanSharma-msft** [comment]
Hello @aosolis - Thanks for raising your query.
We will look into it and redirect to doc team for the updates.

**Comment by Prasad-MSFT** [comment]
Hi @surbhigupta12 - Could you please help here removing the part as suggested above?
