### ISSUE TITLE
Not able to see adaptive card in Teams app on mobile (both IOS and Android).

### ISSUE THREAD

**Issue by wyvern-x0** [MicrosoftDocs/msteams-docs#9308]
While sending the Adaptive Card on teams bot, card is not displaying on mobile device (IOS). The same card is rendering properly on desktop teams. On checking the message with the developer preview option, getting below error: 

Err domain:ACRParseErrorDomain code:5 userInfo:{
   error = "<Scrubbed Error Info>";
}

Adaptive card version- 1.4 and bot framework sdk v4 in .NET.

For some cards only, this is happening. For other cards, this issue is not reciprocating.

**Comment by sayali-MSFT** [comment]
@wyvern-x0 - Thanks for reporting your issue.
Could you please share the repro steps and Adaptive card JSON, so that we can try it from our end.

**Comment by wyvern-x0** [comment]
This is the dummy json generated.
{
    "type": "AdaptiveCard",
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.5",
    "body": [
        {
            "items": [
                {
                    "columns": [
                        {
                            "width": "stretch",
                            "items": [
                                {
                                    "weight": "Bolder",
                                    "color": "Light",
                                    "horizontalAlignment": "Center",
                                    "size": "Large",
                                    "text": "abcdabcd",
                                    "wrap": true,
                                    "type": "TextBlock"
                                }
                            ],
                            "type": "Column"
                        }
                    ],
                    "type": "ColumnSet"
                },
                {
                    "weight": "Bolder",
                    "color": "Light",
                    "height": "stretch",
                    "horizontalAlignment": "Center",
                    "size": "Large",
                    "text": "abcdabcdabcdabcdabcdabcdabcdabcdabcdabcd",
                    "wrap": true,
                    "type": "TextBlock"
                }
            ],
            "backgroundImage": {
                "url": "https://marketingaccesspass.com/wp-content/uploads/2015/10/Podcast-Website-Design-Background-Image.jpg",
                "verticalAlignment": "Center"
            },
            "type": "Container"
        },
        {
            "size": "Small",
            "wrap": true,
            "type": "TextBlock",
            "text": "abcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcd"
        },
        {
            "size": "Small",
            "wrap": true,
            "type": "TextBlock",
            "text": "abcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcd"
        },
        {
            "height": "stretch",
            "style": "default",
            "spacing": "Medium",
            "verticalContentAlignment": "Bottom",
            "minHeight": "15px",
            "type": "Container",
            "items": [
                {
                    "columns": [
                        {
                            "width": 35,
                            "items": [
                                {
                                    "weight": "Lighter",
                                    "isSubtle": true,
                                    "separator": true,
                                    "size": "Small",
                                    "text": "Client",
                                    "wrap": true,
                                    "spacing": "Small",
                                    "type": "TextBlock"
                                }
                            ],
                            "type": "Column"
                        },
                        {
                            "width": 23,
                            "items": [
                                {
                                    "weight": "Lighter",
                                    "isSubtle": true,
                                    "separator": true,
                                    "size": "Small",
                                    "text": "Overdue Total(Count)",
                                    "wrap": true,
                                    "spacing": "Small",
                                    "type": "TextBlock"
                                }
                            ],
                            "type": "Column"
                        },
                        {
                            "width": 10,
                            "items": [
                                {
                                    "weight": "Lighter",
                                    "isSubtle": true,
                                    "separator": true,
                                    "size": "Small",
                                    "text": "Avg. abcd",
                                    "wrap": true,
                                    "spacing": "Small",
                                    "type": "TextBlock"
                                }
                            ],
                            "type": "Column"
                        }
                    ],
                    "separator": true,
                    "type": "ColumnSet"
                }
            ]
        },
        {
            "items": [
                {
                    "columns": [
                        {
                            "width": 35,
                            "items": [
                                {
                                    "size": "Small",
                                    "wrap": true,
                                    "type": "TextBlock",
                                    "text": "AB Inb"
                                }
                            ],
                            "type": "Column"
                        },
                        {
                            "width": 23,
                            "items": [
                                {
                                    "size": "Small",
                                    "wrap": true,
                                    "type": "TextBlock",
                                    "text": "$42.2K(3)"
                                }
                            ],
                            "type": "Column"
                        },
                        {
                            "width": 10,
                            "items": [
                                {
                                    "size": "Small",
                                    "wrap": true,
                                    "type": "TextBlock",
                                    "text": "35d"
                                }
                            ],
                            "type": "Column"
                        }
                    ],
                    "type": "ColumnSet"
                }
            ],
            "separator": true,
            "type": "Container"
        },
        {
            "type": "TextBlock",
            "text": "70009188",
            "isVisible": false
        },
        {
            "items": [
                {
                    "columns": [
                        {
                            "width": "auto",
                            "items": [
                                {
                                    "size": "Small",
                                    "isSubtle": true,
                                    "weight": "Lighter",
                                    "type": "TextBlock",
                                    "text": "comments: "
                                }
                            ],
                            "type": "Column"
                        },
                        {
                            "items": [
                                {
                                    "size": "Small",
                                    "wrap": true,
                                    "height": "stretch",
                                    "type": "TextBlock",
                                    "text": "abcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcd"
                                }
                            ],
                            "type": "Column",
                            "width": "stretch"
                        },
                        {
                            "id": "chevronDown1",
                            "items": [
                                {
                                    "type": "Image",
                                    "url": "https://th.bing.com/th/id/R.24dac1c93712adb0a8499e5f09ace9b6?rik=T9SrZLAzKyTwlg&riu=http%3a%2f%2fcdn.onlinewebfonts.com%2fsvg%2fimg_93114.png&ehk=PRqUVKCN1HdoR2VZJdeyRgTjWkhtWtk0z54f9YWZFIA%3d&risl=&pid=ImgRaw&r=0",
                                    "selectAction": {
                                        "id": "Commentary1",
                                        "targetElements": [
                                            "chevronUp1",
                                            "chevronDown1",
                                            "CommentBox1",
                                            "submitbutton1"
                                        ],
                                        "type": "Action.ToggleVisibility"
                                    },
                                    "width": "20px",
                                    "height": "auto",
                                    "altText": "collapsed"
                                }
                            ],
                            "width": "auto",
                            "type": "Column"
                        },
                        {
                            "id": "chevronUp1",
                            "isVisible": false,
                            "items": [
                                {
                                    "type": "Image",
                                    "url": "https://th.bing.com/th/id/R.24dac1c93712adb0a8499e5f09ace9b6?rik=T9SrZLAzKyTwlg&riu=http%3a%2f%2fcdn.onlinewebfonts.com%2fsvg%2fimg_93114.png&ehk=PRqUVKCN1HdoR2VZJdeyRgTjWkhtWtk0z54f9YWZFIA%3d&risl=&pid=ImgRaw&r=0",
                                    "selectAction": {
                                        "id": "Commentary1",
                                        "targetElements": [
                                            "chevronUp1",
                                            "chevronDown1",
                                            "CommentBox1",
                                            "submitbutton1"
                                        ],
                                        "type": "Action.ToggleVisibility"
                                    },
                                    "width": "20px",
                                    "height": "auto",
                                    "altText": "expanded"
                                }
                            ],
                            "width": "auto",
                            "type": "Column"
                        }
                    ],
                    "spacing": "None",
                    "type": "ColumnSet"
                }
            ],
            "type": "Container"
        },
        {
            "id": "CommentBox1",
            "placeholder": "Please provide your comments here...(300 Character Max)",
            "isVisible": false,
            "type": "Input.Text",
            "isMultiline": true,
            "maxLength": 300
        },
        {
            "color": "Attention",
            "horizontalAlignment": "Right",
            "size": "Small",
            "text": "Please enter your comments",
            "wrap": true,
            "isVisible": false,
            "type": "TextBlock"
        },
        {
            "color": "Attention",
            "horizontalAlignment": "Right",
            "size": "Small",
            "text": "Your comments could not be saved. Please click on submit button again to save the comments",
            "wrap": true,
            "isVisible": false,
            "type": "TextBlock"
        },
        {
            "id": "submitbutton1",
            "isVisible": false,
            "columns": [
                {
                    "width": "stretch",
                    "type": "Column"
                },
                {
                    "width": "auto",
                    "items": [
                        {
                            "actions": [
                                {
                                    "data": {
                                        "ADCDsubmitData": "Commentary1"
                                    },
                                    "title": "Submit",
                                    "style": "positive",
                                    "type": "Action.Submit"
                                }
                            ],
                            "type": "ActionSet"
                        }
                    ],
                    "type": "Column"
                }
            ],
            "type": "ColumnSet"
        },
        {
            "items": [
                {
                    "columns": [
                        {
                            "width": 35,
                            "items": [
                                {
                                    "size": "Small",
                                    "wrap": true,
                                    "type": "TextBlock",
                                    "text": "CATERPILLAR"
                                }
                            ],
                            "type": "Column"
                        },
                        {
                            "width": 23,
                            "items": [
                                {
                                    "size": "Small",
                                    "wrap": true,
                                    "type": "TextBlock",
                                    "text": "$10.5K(1)"
                                }
                            ],
                            "type": "Column"
                        },
                        {
                            "width": 10,
                            "items": [
                                {
                                    "size": "Small",
                                    "wrap": true,
                                    "type": "TextBlock",
                                    "text": "12d"
                                }
                            ],
                            "type": "Column"
                        }
                    ],
                    "type": "ColumnSet"
                }
            ],
            "separator": true,
            "type": "Container"
        },
        {
            "type": "TextBlock",
            "text": "70009188",
            "isVisible": false
        },
        {
            "items": [
                {
                    "columns": [
                        {
                            "width": "auto",
                            "items": [
                                {
                                    "size": "Small",
                                    "isSubtle": true,
                                    "weight": "Lighter",
                                    "type": "TextBlock",
                                    "text": "comments: "
                                }
                            ],
                            "type": "Column"
                        },
                        {
                            "items": [
                                {
                                    "size": "Small",
                                    "wrap": true,
                                    "height": "stretch",
                                    "type": "TextBlock",
                                    "text": "abcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcd"
                                }
                            ],
                            "type": "Column",
                            "width": "stretch"
                        },
                        {
                            "id": "chevronDown2",
                            "items": [
                                {
                                    "type": "Image",
                                    "url": "https://th.bing.com/th/id/R.24dac1c93712adb0a8499e5f09ace9b6?rik=T9SrZLAzKyTwlg&riu=http%3a%2f%2fcdn.onlinewebfonts.com%2fsvg%2fimg_93114.png&ehk=PRqUVKCN1HdoR2VZJdeyRgTjWkhtWtk0z54f9YWZFIA%3d&risl=&pid=ImgRaw&r=0",
                                    "selectAction": {
                                        "id": "Commentary2",
                                        "targetElements": [
                                            "chevronUp2",
                                            "chevronDown2",
                                            "CommentBox2",
                                            "submitbutton2"
                                        ],
                                        "type": "Action.ToggleVisibility"
                                    },
                                    "width": "20px",
                                    "height": "auto",
                                    "altText": "collapsed"
                                }
                            ],
                            "width": "auto",
                            "type": "Column"
                        },
                        {
                            "id": "chevronUp2",
                            "isVisible": false,
                            "items": [
                                {
                                    "type": "Image",
                                    "url": "https://th.bing.com/th/id/R.24dac1c93712adb0a8499e5f09ace9b6?rik=T9SrZLAzKyTwlg&riu=http%3a%2f%2fcdn.onlinewebfonts.com%2fsvg%2fimg_93114.png&ehk=PRqUVKCN1HdoR2VZJdeyRgTjWkhtWtk0z54f9YWZFIA%3d&risl=&pid=ImgRaw&r=0",
                                    "selectAction": {
                                        "id": "Commentary2",
                                        "targetElements": [
                                            "chevronUp2",
                                            "chevronDown2",
                                            "CommentBox2",
                                            "submitbutton2"
                                        ],
                                        "type": "Action.ToggleVisibility"
                                    },
                                    "width": "20px",
                                    "height": "auto",
                                    "altText": "expanded"
                                }
                            ],
                            "width": "auto",
                            "type": "Column"
                        }
                    ],
                    "spacing": "None",
                    "type": "ColumnSet"
                }
            ],
            "type": "Container"
        },
        {
            "id": "CommentBox2",
            "placeholder": "Please provide your comments here...(300 Character Max)",
            "isVisible": false,
            "type": "Input.Text",
            "isMultiline": true,
            "maxLength": 300
        },
        {
            "color": "Attention",
            "horizontalAlignment": "Right",
            "size": "Small",
            "text": "Please enter your comments",
            "wrap": true,
            "isVisible": false,
            "type": "TextBlock"
        },
        {
            "color": "Attention",
            "horizontalAlignment": "Right",
            "size": "Small",
            "text": "Your comments could not be saved. Please click on submit button again to save the comments",
            "wrap": true,
            "isVisible": false,
            "type": "TextBlock"
        },
        {
            "id": "submitbutton2",
            "isVisible": false,
            "columns": [
                {
                    "width": "stretch",
                    "type": "Column"
                },
                {
                    "width": "auto",
                    "items": [
                        {
                            "actions": [
                                {
                                    "data": {
"ABCDsubmitData": "Commentary2"                                    },
                                    "title": "Submit",
                                    "style": "positive",
                                    "type": "Action.Submit"
                                }
                            ],
                            "type": "ActionSet"
                        }
                    ],
                    "type": "Column"
                }
            ],
            "type": "ColumnSet"
        },
        {
            "items": [
                {
                    "columns": [
                        {
                            "width": 35,
                            "items": [
                                {
                                    "size": "Small",
                                    "wrap": true,
                                    "type": "TextBlock",
                                    "text": "abcdabcdabc"
                                }
                            ],
                            "type": "Column"
                        },
                        {
                            "width": 23,
                            "items": [
                                {
                                    "size": "Small",
                                    "wrap": true,
                                    "type": "TextBlock",
                                    "text": "$56.1K(6)"
                                }
                            ],
                            "type": "Column"
                        },
                        {
                            "width": 10,
                            "items": [
                                {
                                    "size": "Small",
                                    "wrap": true,
                                    "type": "TextBlock",
                                    "text": "26d"
                                }
                            ],
                            "type": "Column"
                        }
                    ],
                    "type": "ColumnSet"
                }
            ],
            "separator": true,
            "type": "Container"
        },
        {
            "type": "TextBlock",
            "text": "70009188",
            "isVisible": false
        },
        {
            "items": [
                {
                    "columns": [
                        {
                            "width": "auto",
                            "items": [
                                {
                                    "size": "Small",
                                    "isSubtle": true,
                                    "weight": "Lighter",
                                    "type": "TextBlock",
                                    "text": "comments: "
                                }
                            ],
                            "type": "Column"
                        },
                        {
                            "items": [
                                {
                                    "size": "Small",
                                    "wrap": true,
                                    "height": "stretch",
                                    "type": "TextBlock",
                                    "text": "abcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcd"
                                }
                            ],
                            "type": "Column",
                            "width": "stretch"
                        },
                        {
                            "id": "chevronDown3",
                            "items": [
                                {
                                    "type": "Image",
                                    "url": "https://th.bing.com/th/id/R.24dac1c93712adb0a8499e5f09ace9b6?rik=T9SrZLAzKyTwlg&riu=http%3a%2f%2fcdn.onlinewebfonts.com%2fsvg%2fimg_93114.png&ehk=PRqUVKCN1HdoR2VZJdeyRgTjWkhtWtk0z54f9YWZFIA%3d&risl=&pid=ImgRaw&r=0",
                                    "selectAction": {
                                        "id": "Commentary3",
                                        "targetElements": [
                                            "chevronUp3",
                                            "chevronDown3",
                                            "CommentBox3",
                                            "submitbutton3"
                                        ],
                                        "type": "Action.ToggleVisibility"
                                    },
                                    "width": "20px",
                                    "height": "auto",
                                    "altText": "collapsed"
                                }
                            ],
                            "width": "auto",
                            "type": "Column"
                        },
                        {
                            "id": "chevronUp3",
                            "isVisible": false,
                            "items": [
                                {
                                    "type": "Image",
                                    "url": "https://th.bing.com/th/id/R.24dac1c93712adb0a8499e5f09ace9b6?rik=T9SrZLAzKyTwlg&riu=http%3a%2f%2fcdn.onlinewebfonts.com%2fsvg%2fimg_93114.png&ehk=PRqUVKCN1HdoR2VZJdeyRgTjWkhtWtk0z54f9YWZFIA%3d&risl=&pid=ImgRaw&r=0",
                                    "selectAction": {
                                        "id": "Commentary"3,
                                        "targetElements": [
                                            "chevronUp3",
                                            "chevronDown3",
                                            "CommentBox3",
                                            "submitbutton3"
                                        ],
                                        "type": "Action.ToggleVisibility"
                                    },
                                    "width": "20px",
                                    "height": "auto",
                                    "altText": "expanded"
                                }
                            ],
                            "width": "auto",
                            "type": "Column"
                        }
                    ],
                    "spacing": "None",
                    "type": "ColumnSet"
                }
            ],
            "type": "Container"
        },
        {
            "id": "CommentBox3",
            "placeholder": "Please provide your comments here...(300 Character Max)",
            "isVisible": false,
            "type": "Input.Text",
            "isMultiline": true,
            "maxLength": 300
        },
        {
            "color": "Attention",
            "horizontalAlignment": "Right",
            "size": "Small",
            "text": "Please enter your comments",
            "wrap": true,
            "isVisible": false,
            "type": "TextBlock"
        },
        {
            "color": "Attention",
            "horizontalAlignment": "Right",
            "size": "Small",
            "text": "Your comments could not be saved. Please click on submit button again to save the comments",
            "wrap": true,
            "isVisible": false,
            "type": "TextBlock"
        },
        {
            "id": "submitbutton3",
            "isVisible": false,
            "columns": [
                {
                    "width": "stretch",
                    "type": "Column"
                },
                {
                    "width": "auto",
                    "items": [
                        {
                            "actions": [
                                {
                                    "data": {
                                        "ABCDsubmitData": "Commentary3"
                                    },
                                    "title": "Submit",
                                    "style": "positive",
                                    "type": "Action.Submit"
                                }
                            ],
                            "type": "ActionSet"
                        }
                    ],
                    "type": "Column"
                }
            ],
            "type": "ColumnSet"
        },
        {
            "columns": [
                {
                    "items": [
                        {
                            "size": "Small",
                            "separator": true,
                            "spacing": "Small",
                            "height": "stretch",
                            "type": "TextBlock",
                            "text": "**Support Materials**"
                        }
                    ],
                    "width": "auto",
                    "type": "Column",
                    "spacing": "Small"
                }
            ],
            "separator": true,
            "type": "ColumnSet"
        },
        {
            "columns": [
                {
                    "verticalContentAlignment": "Center",
                    "items": [
                        {
                            "size": "Small",
                            "text": "abcdabcdabcdabcdabcdabcdabcdabcdabcdabcda",
                            "wrap": true,
                            "type": "TextBlock",
                            "spacing": "None"
                        },
                        {
                            "type": "ActionSet"
                        }
                    ],
                    "width": "auto",
                    "type": "Column"
                }
            ],
            "spacing": "Small",
            "type": "ColumnSet"
        }
    ],
    "msTeams": {
        "width": "full"
    }
}

We're sending this through turncontext.sendactivityasync as an attachment.

**Comment by wyvern-x0** [comment]
any update @sayali-MSFT ?

**Comment by sayali-MSFT** [comment]
@wyvern-x0 -We are trying to reproduce it from our end, and we will let you know the update once it's done.

**Comment by sayali-MSFT** [comment]
@wyvern-x0 -We are able to repro that issue on Android device, we have raised bug for the same. We will inform you once we get any update.
Microsoft Teams Version- 1416/1.0.0.2023134402/0802

We have checked the iOS version, and it is working fine. Could you please share the iOS Teams version and iOS version with us so that we can try to reproduce the issue from our end?
IOS Version-16.6
IOS Teams version-5.14.77.2023143702/0809
