### ISSUE TITLE
Example code snippet for  Microsoft.Bot.Connector.Teams SDK (v4)

### ISSUE THREAD

**Issue by s3651907** [MicrosoftDocs/msteams-docs#932]
Can we have a .Net core sample code snippet for SDK 4 as well. If you already have them published somewhere a link to the recourse will be very helpful since I did not have any luck finding any.

**Comment by Ky7m** [comment]
Did you take a look at 
https://github.com/OfficeDev/BotBuilder-MicrosoftTeams-dotnet/tree/master/CSharp/Samples
and experimental branch https://github.com/microsoft/BotBuilder-Samples/tree/teams-samples/samples/csharp_dotnetcore

**Comment by clearab** [comment]
Please keep in mind the samples there a subject to change as we move to incorporate full MS Teams support in the Bot Framework SDK.
