### ISSUE TITLE
Incorrect steps to enable Developer Preview

### ISSUE THREAD

**Issue by aamillerMSFT** [MicrosoftDocs/msteams-docs#9320]
Developer Preview is now part of Early Access Channels (Public Preview).  The information on this page is inaccurate and\or incomplete.  

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 008da4e2-979e-c396-db28-4acf57deb530
* Version Independent ID: f1413f77-5eb3-e1fd-9235-d322d6e4eb6c
* Content: [Public developer preview for Microsoft Teams - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/resources/dev-preview/developer-preview-intro)
* Content Source: [msteams-platform/resources/dev-preview/developer-preview-intro.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/resources/dev-preview/developer-preview-intro.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **surbhigupta**

**Comment by Prasad-MSFT** [comment]
@aamillerMSFT - Could you please provide more details? I mean what exactly you want to add in this page or which section is misleading, could you please specify?

**Comment by PieterVandendriessche** [comment]
@aamillerMSFT @Prasad-MSFT Is my issue #9280 related to this?
