### ISSUE TITLE
Example code snippet for  Microsoft.Bot.Connector.Teams SDK (v4)

### ISSUE THREAD

**Issue by TheCSir** [MicrosoftDocs/msteams-docs#933]
Can we have a .Net core sample code snippet for SDK 4 as well. If you already have them published somewhere a link to the recourse will be very helpful since I did not have any luck finding any.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aaa0ea75-7363-3ef5-39df-ad07c493c118
* Version Independent ID: ab9a2a6e-e2ca-828f-cd8b-bd9ff98411ab
* Content: [Initiate actions with messaging extensions - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/messaging-extensions/create-extensions?tabs=dotnet#feedback)
* Content Source: [msteams-platform/concepts/messaging-extensions/create-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/messaging-extensions/create-extensions.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Wajeed-msft** [comment]
Currently, SDK4 for Microsoft Teams is in beta state. Please take a look at all the available [SDK and Tools](https://docs.microsoft.com/en-us/microsoftteams/platform/#pivot=sdk-tools&panel=sdk-tools-all). Please take a look at currently available [SDK4 samples for Microsoft Teams on GitHub](https://github.com/OfficeDev/BotBuilder-MicrosoftTeams-dotnet/tree/master/CSharp/Samples).

**Comment by TheCSir** [comment]
Thanks for the reply, I'll take a look at the links provided.
