### ISSUE TITLE
Typeface app in Teams 

### ISSUE THREAD

**Issue by shahsaachi** [MicrosoftDocs/msteams-docs#9335]
Typeface app in Teams doesn't have supported capabilities in non-Teams products but the badge saying that it works across Teams, Outlook and Office. Seems like a bug and the badge should be removed
<img width="1722" alt="Screenshot 2023-08-28 at 4 11 13 PM" src="https://github.com/MicrosoftDocs/msteams-docs/assets/143460080/69704580-e263-45e6-b5b4-70db9e080791">

**Comment by Meghana-MSFT** [comment]
Thank you for reporting this issue, we will check this and get back to you.

**Comment by Meghana-MSFT** [comment]
We are checking this internally with engineering team, we will keep you posted on the updates. Thank you.

**Comment by shahsaachi** [comment]
hello, I still see this issue. 
<img width="1425" alt="Screenshot 2023-11-22 at 12 05 21 AM" src="https://github.com/MicrosoftDocs/msteams-docs/assets/143460080/1be41544-86b5-46e2-87eb-82beebcd97b7">

**Comment by ChetanSharma-msft** [comment]
Hello @shahsaachi - We have informed engineering team and let you know the updates if any.

**Comment by ChetanSharma-msft** [comment]
Hello @shahsaachi - Sorry for delay in response.
This issue is fixed and we have checked it in Web browser:
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/59052547/6c656eb5-fdab-4a0e-8049-059fce35c9b1)

Could you please verify and let us know?
