### ISSUE TITLE
Document /teams/{teamId}

### ISSUE THREAD

**Issue by aosolis** [MicrosoftDocs/msteams-docs#935]
Document the API to return information about a team, including the name and AAD object ID. This corresponds to FetchTeamDetailsAsync in the SDKs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f16f5795-7015-3a4e-2e64-d08d4a6be78d
* Version Independent ID: 6f8a9a3a-33c9-acc5-83d8-7645373bee3d
* Content: [Get context for your bot - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/bots/bots-context#rest-api-example-1)
* Content Source: [msteams-platform/concepts/bots/bots-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/bots/bots-context.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by clearab** [comment]
This is now documented
