### ISSUE TITLE
Override OnTeamsReadReceiptAsync - sample code is C#, not Javascript

### ISSUE THREAD

**Issue by Jegadeesh-MSFT** [MicrosoftDocs/msteams-docs#9354]
Under "Override OnTeamsReadReceiptAsync" heading the sample code provided is a C# code but its mentioned as Javascript code.
Please check and change it as C#
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/140516784/adfeb5db-916e-4569-93f4-616e827f9d9b)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: afbc5b84-5be5-b5c4-30c0-58782a748a03
* Version Independent ID: ef6b8aee-52e7-f5d4-7dfa-8f34a1698330
* Content: [Messages in bot conversations - Teams](https://review.learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-messages?branch=pr-en-us-9184&tabs=dotnet1%2Capp-manifest-v112-or-later%2Cdotnet2%2Cdotnet3%2Cdotnet4%2Cdotnet5%2Cdotnet#receive-a-read-receipt)
* Content Source: [msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/bots/how-to/conversations/conversation-messages.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **anclear**

**Comment by Nivedipa-MSFT** [comment]
@surbhigupta12 - Could you please help here to update the content here.

**Comment by surbhigupta12** [comment]
Closing this issue as it is addressed in PR #9184
