### ISSUE TITLE
Ms teams bot card action throw error " Something went wrong. Please try again."

### ISSUE THREAD

**Issue by atabaDev** [MicrosoftDocs/msteams-docs#9359]
We're currently using an ms teams app containing a bot and added some actions to that bot.
Action called "Sign In" .
When we click on button it displays this error " Something went wrong. Please try again." 
The  app is created via dev portal and published to organisation.

Bot is also created from dev portal and is pointing to a messaging endpoint connected to our backend.
Our backend is listening well to ms teams bot via //message/api post() endpoint and whenever there's a reaction performed on a message, our backend received it well. So connection between Ms and our backend is well established.

manifest : 

`{
    "$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.16/MicrosoftTeams.schema.json",
    "version": "1.0.0",
    "manifestVersion": "1.16",
    "id": "27a2dd4d-a18e-460b-84cc-fec0f93bd7d7",
    "packageName": "com.package.name",
    "name": {
        "short": "local-setup",
        "full": ""
    },
    "developer": {
        "name": "COYO GmbH",
        "mpnId": "",
        "websiteUrl": "",
        "privacyUrl": "",
        "termsOfUseUrl": ""
    },
    "description": {
        "short": "Stay up to date with your ",
        "full": "You must provide links to your privacy policy and terms of use. Learn more about best practices for links."
    },
    "icons": {
        "outline": "outline.png",
        "color": "color.png"
    },
    "accentColor": "#FFFFFF",
    "staticTabs": [
        {
            "entityId": "conversations",
            "scopes": [
                "personal"
            ]
        },
        {
            "entityId": "about",
            "scopes": [
                "personal"
            ]
        }
    ],
    "bots": [
        {
            "botId": "bd6326d5-e977-48e9-87cd-4611872db01a",
            "scopes": [
                "personal"
            ],
            "commandLists": [
                {
                    "commands": [
                        {
                            "title": "Sign In",
                            "description": "sing in to haiilo"
                        },
                        {
                            "title": "Sign out",
                            "description": "sign out"
                        }
                    ],
                    "scopes": [
                        "personal"
                    ]
                }
            ],
            "isNotificationOnly": false,
            "supportsCalling": false,
            "supportsVideo": false,
            "supportsFiles": false
        }
    ],
    "validDomains": [
        "token.botframework.com",
        "login.microsoftonline.com"
    ],
    "webApplicationInfo": {
        "id": "6337686f-fc1f-42ec-b68f-5854b5ce0e67",
        "resource": ""
    }
}`

**Comment by Nivedipa-MSFT** [comment]
@atabaDev - Thank you for reporting the issue. Could you please verify if the messaging endpoint of your bot is accurately configured and connected to your backend? You mentioned that your backend is correctly receiving messages from the Teams bot via the /api/messages endpoint, so please ensure that the endpoint URL is accurate in your bot registration settings.

Kindly check for any error logs or exceptions in your backend when the "Sign In" action is triggered. This could help identify any issues with the authentication process or other potential errors.

**Comment by atabaDev** [comment]
Hi Nivedipa, thank you for you reply. 
A little context so we can understand the issue more. 

So we've been running this app for more than 3 years now and using same bot, it was working well until last month we've been receiving this error knowing that we haven't changed anything in our backend codebase nor the teams app config.

Back to you're suggestion, let me briefly describe the scenario : so when user interacts with chat bot and types "Sign in", this command is received well in our backend and we can log the activity and all fine, then our backend using botframework returns a sign in card (herocard) containing an action button that when you click on it a url is opened in a tab, but when we click on this button we receive the error described up and when i check logs there's nothing at all and it seems like the error is on Ms teams side and doesn't even reach our backend and no trace at all.

here is the sign in card creation method : 
```
`async createAuthenticationCard(): Promise<Partial<Activity>> {
        const actions: CardAction[] = [{
            type: 'signin',
            value: "backend url",
            title: "sign in"
        }];
        const card = CardFactory.heroCard(
            '', "sign in", null, actions);
        this.logger.debug(`createAuthenticationCard(${JSON.stringify(card)})`);

        return MessageFactory.attachment(card);
    }`
```


Here you can see the sign in  herocard attatchment logged data: 

````
{
    "contentType": "application/vnd.microsoft.card.hero",
    "content": {
        "text": "sign in",
        "buttons": [
            {
                "type": "signin",
                "value": "backend url",
                "title": "sign in"
            }
        ]
    }
}`
```
And this is the attatchment object 
`{
    "type": "message",
    "attachmentLayout": "list",
    "attachments": [
        {
            "contentType": "application/vnd.microsoft.card.hero",
            "content": {
                "text": "sign in",
                "buttons": [
                    {
                        "type": "signin",
                        "value":"backend url",
                        "title": "sign in"
                    }
                ]
            }
        }
    ],
    "inputHint": "acceptingInput"
}`
Everything seems fine in our backend behaviour but when we click on "sign in" action button the tab is not opened and we receive th error " Something went wrong. Please try again" 
There's no errors even in web console. 

An other hint, i tried to reproduce the problem with a newly created bot and yes am having same issue but when i used a bot that i have created maybe year ago for local dev purposes, it works, the error is not there.

We thought at first that maybe there were some Ms updates that we weren't aware of lately but we couldn't find any changes mentioned. 

Other infos : 
+ botbuilder version : "botbuilder": "4.7.2"
+ we had this issue year ago but it was solved without doing anything. We didn't understand the reasons because we havn't changed or did anything.

We really hope we get support as soon as possible because we have a lot of our ms customers blocked and we informed them that we're communicating the issue with you.
Thank you

**Comment by atabaDev** [comment]
An other update that we have just tried. 
We changed the card action type  from ActionTypes.Signin to ActionTypes.Openurl and we're able to open a new tab in the browser when we click on signIn button but that's not the requirement because we want to stay in ms teams context and open a popup not a new tab.
So clearly there's an Ms  issue with  ActionTypes.Signin cardaction type that we still don't know the reason why

**Comment by Nivedipa-MSFT** [comment]
@atabaDev - Apologies. Somehow, we missed the notification and lost track of it. We will test this issue and we will update you with our findings.

**Comment by aravindss123** [comment]
@atabaDev I've been dealing with the same issues for a week now. Could you share how you managed to resolve them?
