### ISSUE TITLE
Deep Link Scheduling dialog - Group/Channel

### ISSUE THREAD

**Issue by figgsoftware** [MicrosoftDocs/msteams-docs#937]
Deep link to schedule meeting – there certainly should be a parameter to specify what Group/Channel to meet in. If there isn’t already?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a891841a-a110-d18e-25c1-fc29e7d4a5e3
* Version Independent ID: c1a11eb8-00d1-e1d2-1e9d-71d059a6478a
* Content: [Create deep links - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/deep-links#deep-linking-from-your-tab)
* Content Source: [msteams-platform/concepts/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/deep-links.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Gousia-MSFT** [comment]
@figgsoftware Thanks for reaching out!! We have created a feature request for this and it is being tracked internally.

**Comment by figgsoftware** [comment]
So @Gousia-MSFT is it on the long,notgonnahappen backlog or is it realistic to expect that it will be done? :)
