### ISSUE TITLE
Glossary page does not mention "dialogs" or resolve the "dialog" / "task module" ambiguity

### ISSUE THREAD

**Issue by AE-MS** [MicrosoftDocs/msteams-docs#9370]
Title says it all

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ff9690f5-fa8b-98bb-d3b4-ad4ed1030114
* Version Independent ID: ff9690f5-fa8b-98bb-d3b4-ad4ed1030114
* Content: [Microsoft Teams developer documentation- Glossary - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/get-started/glossary)
* Content Source: [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/get-started/glossary.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **surbhigupta**

**Comment by Prasad-MSFT** [comment]
Hi @AE-MS - Could you please let us know what exactly we need to update in this page? Do you want us to add details about [dialog](https://learn.microsoft.com/en-us/javascript/api/@microsoft/teams-js/dialog?view=msteams-client-js-latest) as mentioned [here](https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/using-teams-client-library?tabs=javascript%2Cmanifest-teams-toolkit#dialog-namespace)?

**Comment by surbhigupta12** [comment]
Task module vs. Dialog terminology is still under discussion. The Glossary will be updated when we have an alignment internally.
