### ISSUE TITLE
The definition for "App Manifest" is incomplete

### ISSUE THREAD

**Issue by AE-MS** [MicrosoftDocs/msteams-docs#9372]
It only says it "describes how the app integrates into the Microsoft Teams product." The app manifest is broader than that, describing how it integrates across the M365 extensibility platform.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ff9690f5-fa8b-98bb-d3b4-ad4ed1030114
* Version Independent ID: ff9690f5-fa8b-98bb-d3b4-ad4ed1030114
* Content: [Microsoft Teams developer documentation- Glossary - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/get-started/glossary)
* Content Source: [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/get-started/glossary.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **surbhigupta**

**Comment by Nivedipa-MSFT** [comment]
@surbhigupta12 - Could you please help here to update the document here.
