### ISSUE TITLE
The definition for the "location" capability is incomplete

### ISSUE THREAD

**Issue by AE-MS** [MicrosoftDocs/msteams-docs#9375]
It doesn't mention the newer "geoLocation" capability and it doesn't mention that its supported in other M365 hosts, like microsoft365.com.

Also is it appropriate to set a precedent where every teamsjs capability is listed on this page, rather than just referring to something like https://learn.microsoft.com/en-us/microsoftteams/platform/m365-apps/teamsjs-support-m365 ?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ff9690f5-fa8b-98bb-d3b4-ad4ed1030114
* Version Independent ID: ff9690f5-fa8b-98bb-d3b4-ad4ed1030114
* Content: [Microsoft Teams developer documentation- Glossary - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/get-started/glossary)
* Content Source: [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/get-started/glossary.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **surbhigupta**

**Comment by sayali-MSFT** [comment]
Thanks for reporting your issue.
We will check this at our end and will get back to you.
