### ISSUE TITLE
Which parts of TeamsJS get defined on this list?

### ISSUE THREAD

**Issue by AE-MS** [MicrosoftDocs/msteams-docs#9376]
For instance, this list describes the "location" and "media" capability, and the "TaskInfo" interface. What meets the bar to be on this list?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ff9690f5-fa8b-98bb-d3b4-ad4ed1030114
* Version Independent ID: ff9690f5-fa8b-98bb-d3b4-ad4ed1030114
* Content: [Microsoft Teams developer documentation- Glossary - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/get-started/glossary)
* Content Source: [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/get-started/glossary.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **surbhigupta**

**Comment by Prasad-MSFT** [comment]
Hi @surbhigupta12 , could you please help here responding to the above asked query?

**Comment by surbhigupta12** [comment]
All key and unique concepts from the TeamsJS library will be included in the glossary. We will refrain from including method names, namespace references, and interface names unless there is a notable demand for clarification from developers through various feedback channels.
