### ISSUE TITLE
Readme.md has link to NodeJS sample for Webhook that is a copy paste of the C# sample.

### ISSUE THREAD

**Issue by HerrickSpencer** [MicrosoftDocs/msteams-docs#938]
"Outgoing Webhook for Node.js	Illustrates how to create a simple Outgoing Webhook for Microsoft Teams in ~50 lines of Node.js code."

The link here is https://github.com/OfficeDev/microsoft-teams-sample-outgoing-webhook
This is the C# sample (same as the line above)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2b0e7e8-c51e-5715-308d-43d20ef5349f
* Version Independent ID: 43c28753-a32d-d81b-450c-a13dab27ab0b
* Content: [Microsoft Teams code samples - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/samples/code-samples#feedback)
* Content Source: [msteams-platform/samples/code-samples.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/samples/code-samples.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by clearab** [comment]
Thanks, this will go live with the next publish to production. If you need the link before that it is here:

https://github.com/OfficeDev/msteams-samples-outgoing-webhook-nodejs

**Comment by HerrickSpencer** [comment]
Yup, I found the link… I also made you a Pull Request to update and fix this issue if you wish to just merge it in.

Cheers,


[cid:image001.png@01D4D2A0.FD2F8FE0]
Herrick Spencer| Senior SDE
(631) 327-8345m | (425) 538-7106w
109/1334

Microsoft Partner App Experience
🐱‍👤 App Ninja

[HxS - 18975 - 16.0.11929.20177]

________________________________

**Comment by clearab** [comment]
Oh, hah. That's what I get for working Issues from email. I also made a PR and merged to master. I'll merge yours as well since you took the time to create it. Thanks again!

**Comment by HerrickSpencer** [comment]
Aww, that’s nice man.  Thanks for giving me ‘credit’ for the change.  You are a gent.


[cid:image001.png@01D4D2A0.FD2F8FE0]
Herrick Spencer| Senior SDE
(631) 327-8345m | (425) 538-7106w
109/1334

Microsoft Partner App Experience
🐱‍👤 App Ninja

[HxS - 18975 - 16.0.11929.20177]

________________________________
