### ISSUE TITLE
Document the wire protocol for settings (composeExtension/querySettingUrl, composeExtension/setting)

### ISSUE THREAD

**Issue by aosolis** [MicrosoftDocs/msteams-docs#939]
The current documentation assumes devs are using the Teams Node.js SDK (v3).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88ff3777-49c4-8cdc-089e-8612a8774ffb
* Version Independent ID: 0d927000-0b55-2129-cbbb-6630c1ec481e
* Content: [Search with messaging extensions - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/messaging-extensions/search-extensions#declare-your-messaging-extension)
* Content Source: [msteams-platform/concepts/messaging-extensions/search-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/messaging-extensions/search-extensions.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by aosolis** [comment]
@laujan is this on your radar? The current pages basically say figure it out from the sample :)
https://docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/add-configuration-page

**Comment by laujan** [comment]
Hi @aosolis. I don't have much bandwidth prior to Build, but I will add it to the top of my post-Build backlog. 🙂

**Comment by Rajeshwari-v** [comment]
The required information is available in the content page - Search with messaging extensions - Teams, "Important" section.
![image](https://user-images.githubusercontent.com/70377537/121476593-7ce45f80-c9e4-11eb-8dfc-75ab0812b5b9.png)
Hence closing the issue.
