### ISSUE TITLE
Not able to disable/remove back button in MS Teams App when redirected from Deeplink

### ISSUE THREAD

**Issue by NarenderSingh** [MicrosoftDocs/msteams-docs#9399]
When redirected from Deeplink to MS Teams App mobile device. A back button is visible instead of App Icon. Is there a way to remove it?

https://teams.microsoft.com/l/entity/500e07cc-b1b2-4c70-ae8f-cd8b4507a4cf/Meetings
msteams://teams.microsoft.com/l/entity/500e07cc-b1b2-4c70-ae8f-cd8b4507a4cf/Meetings

![image](https://github.com/MicrosoftDocs/msteams-docs/assets/12576426/990b565f-d51d-465a-9f58-99e39db8a09d)

**Comment by Nivedipa-MSFT** [comment]
@NarenderSingh - Thanks for reporting your issue. We will check this and update you soon.

**Comment by NarenderSingh** [comment]
Thanks @Nivedipa-MSFT !

**Comment by Nivedipa-MSFT** [comment]
@NarenderSingh - Could you please share your valuable feedback via [Microsoft Teams Developer Feedback](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR7iCOpS5_b9Nqmwx43u5rtZUOThVR081SllSR05aSDQxQ0tUMDVPTVIxTi4u) link.

**Comment by NarenderSingh** [comment]
Thanks @Nivedipa-MSFT . Feedback submitted!

**Comment by chumachun** [comment]
please upvote feature request https://feedbackportal.microsoft.com/feedback/idea/56eed1e8-dd9e-f011-aa44-6045bd7f402a
