### ISSUE TITLE
Deep link to direct access excel file in Teams

### ISSUE THREAD

**Issue by Teamsbeginner** [MicrosoftDocs/msteams-docs#9405]
Hello. Im Teams user, and thanks for your elaborated information.

My company use Teams, and I want to make QR code which can open a file in teams through edge using smart phone. But company does not allow direct Teams acesss through edge, I have to make direct link to use Teams App.

My question is that, for example, I get a link of excel file in teams as below.

https://io.sharepoint.com/:x:/r/sites/team_SI_108691/xxxxxxxxxxx/

Then, how can I make address to access above url through smart phone, using Teams App by edge?

I tried below address, but it was not working.

https://teams.microsoft.com/l/entity/<appId>/<EntityId>?webUrl=https://io.sharepoint.com/:x:/r/sites/team_SI_108691/xxxxxxxxxxx/<EntityName>

It would be great help know the solution.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 059b1a94-8235-8801-b9e0-ac6fbc485a7c
* Version Independent ID: 059b1a94-8235-8801-b9e0-ac6fbc485a7c
* Content: [Deep link to an application - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-link-application?tabs=teamsjs-v2)
* Content Source: [msteams-platform/concepts/build-and-test/deep-link-application.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/build-and-test/deep-link-application.md)
* Service: **msteams**
* GitHub Login: @v-npaladugu
* Microsoft Alias: **surbhigupta**

**Comment by Meghana-MSFT** [comment]
We can only create deeplinks to file in a channel. Please refer this document for further details - https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-link-teams#generate-deep-links-to-file-in-a-channel
