### ISSUE TITLE
Document deep links for app installation

### ISSUE THREAD

**Issue by aosolis** [MicrosoftDocs/msteams-docs#941]
We support deeplinking to an app, need to document that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a891841a-a110-d18e-25c1-fc29e7d4a5e3
* Version Independent ID: c1a11eb8-00d1-e1d2-1e9d-71d059a6478a
* Content: [Create deep links - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/deep-links)
* Content Source: [msteams-platform/concepts/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/deep-links.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by cjthompson** [comment]
I want to allow a user to install my bot from my website after they login.  How do I create a deep link they can use to install the bot?  Can I pass some state / info along with the request that the bot can use to know which user / account clicked the link?
