### ISSUE TITLE
SSO flow for the `OnTeamsAppBasedLinkQueryAsync`

### ISSUE THREAD

**Issue by wenytang-ms** [MicrosoftDocs/msteams-docs#9419]
[Enter feedback here]
Hi, while I reading [Add code to enable SSO in your bot app](https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/authentication/bot-sso-code?tabs=cs1%2Ccs2%2Ccs3%2Ccs4%2Ccs5&pivots=mex-app), the second Note says that `OnTeamsMessagingExtensionQueryAsync and OnTeamsAppBasedLinkQueryAsync from the TeamsMessagingExtensionsSearchAuthConfigBot.cs file are the only SSO handlers that are supported. Other SSO handlers aren't supported.`. I found some mismatch in the doc.

First, there are some inconsistencies between dotnet sample and node.js sample.
In [dotnet sample](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/app-sso/csharp), the [`OnTeamsMessagingExtensionQueryAsync`](https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/e41726e93e2fd8d761a6535effe25edcb24cf5c5/samples/app-sso/csharp/App%20SSO%20Sample/Bots/TeamsMessagingExtensionsSearchAuthConfigBot.cs#L131) returns a [`auth card`](https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/e41726e93e2fd8d761a6535effe25edcb24cf5c5/samples/app-sso/csharp/App%20SSO%20Sample/Bots/TeamsMessagingExtensionsSearchAuthConfigBot.cs#L146)
but the [node.js sample](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/msgext-search-sso-config/nodejs), the [`handleTeamsMessagingExtensionQuery`](https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/e41726e93e2fd8d761a6535effe25edcb24cf5c5/samples/msgext-search-sso-config/nodejs/bots/teamsMessagingExtensionsSearchAuthConfigBot.js#L50C11-L50C39) returns a [`silentAuth card`](https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/e41726e93e2fd8d761a6535effe25edcb24cf5c5/samples/msgext-search-sso-config/nodejs/bots/teamsMessagingExtensionsSearchAuthConfigBot.js#L169)
Why are the implementations of these two inconsistent?

Second, I tried the node.js sample, once running query without consent before, the `silentAuth` will trigger two `composeExtension/query` request and response, and the second request will take the `sso token` with 412 status, and show users the login button as following:
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/75360946/6aed0c75-116e-470a-aed9-cc2162df4ecd)
but once switch to the link unfurling, the `auth card` just return one `composeExtension/queryLink` and show a auth card in the input box
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/75360946/13c36167-6a8f-4932-93c1-35cbd9ca69cd)
So I just replace the `auth` card with `silentAuth` card in [`handleTeamsAppBasedLinkQuery`](https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/e41726e93e2fd8d761a6535effe25edcb24cf5c5/samples/msgext-search-sso-config/nodejs/bots/teamsMessagingExtensionsSearchAuthConfigBot.js#L72), and tried again, it seems that the `silentAuth` also trigger two `composeExtension/queryLink` with the seconde 412 request take the sso token, but show nothing to users.
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/75360946/a2d1c2c3-8419-40be-9fca-3c3d1550ae53)

Based on the above statement, can you provide some information about the design differences between auth and silentauth in message extension?

I'm the developer for [TeamsFx](https://github.com/OfficeDev/TeamsFx), and we're going to find some solution to help users doing the consent native without any bot token store. 
It's seems `silentAuth` is a better solution to do the auth flow, so can you share about your consideration? 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 039ff5cc-7243-ce4b-527e-c152755eeb72
* Version Independent ID: 039ff5cc-7243-ce4b-527e-c152755eeb72
* Content: [Code configuration for enabling SSO for bots - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/authentication/bot-sso-code?tabs=cs1%2Ccs2%2Ccs3%2Ccs4%2Ccs5&pivots=mex-app)
* Content Source: [msteams-platform/bots/how-to/authentication/bot-sso-code.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/bots/how-to/authentication/bot-sso-code.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **surbhigupta**

**Comment by Nivedipa-MSFT** [comment]
@wenytang-ms - Thanks for reporting your issue. We will test this and update you soon.

**Comment by wenytang-ms** [comment]
@Nivedipa-MSFT thank you for your response. 
maybe the dotnet and node.js has different framework or others. so let's just take node.js sample, I tried the `silentAuth` and `auth` consent flow in Message Extension query as following 
this is `auth` consent flow
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/75360946/2d69ad8e-463d-412d-b812-cad1064d6617)
this is `silentAuth` consent flow
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/75360946/f1c68c97-fd46-49ed-ab69-836cf0dee5e2)
and I also tried `silentAuth` and `auth` in message extension link unfurling, the link unfurling only support `auth`, `silentAuth` is invalid. 
is there any intuition for such two functions? Or teams support `silentAuth` for query but link unfurling not.  Can developers only confirm these features through debugging?

**Comment by wenytang-ms** [comment]
there is still another inconsistent code snippet in this doc. 
At the [head of this doc](https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/authentication/bot-sso-code?tabs=js1%2Cjs2%2Cjs3%2Cjs4%2Cjs5&pivots=mex-app#add-code-to-request-a-token) to create the `CloudAdapter`
```
    // Create adapter.
    // See https://learn.microsoft.com/en-us/azure/bot-service/bot-builder-basics?view=azure-bot-service-4.0 to learn more about how bots work.
    const adapter = new CloudAdapter(botFrameworkAuthentication);
``` 
but at the [end of this doc](https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/authentication/bot-sso-code?tabs=js1%2Cjs2%2Cjs3%2Cjs4%2Cjs5&pivots=mex-app#add-token-to-bot-framework-token-store) add token to token store, there use adapter to exchangeToken token
```
async tokenIsExchangeable(context) {
    let tokenExchangeResponse = null;
    try {
        const valueObj = context.activity.value;
        const tokenExchangeRequest = valueObj.authentication;
        tokenExchangeResponse = await context.adapter.exchangeToken(context,
        ......
``` 

as far as I know, the `cloudAdapter` does not have any implemetation like `exchangeToken`, so the code sample make me really confusion.

**Comment by Nivedipa-MSFT** [comment]
@wenytang-ms - We will check and update you soon.

**Comment by wenytang-ms** [comment]
@Nivedipa-MSFT 
About the 2. Neither [`BotAdapter`](https://github.com/microsoft/botbuilder-js/blob/main/libraries/botbuilder-core/src/botAdapter.ts) or [`CloudAdapterBase`](https://github.com/microsoft/botbuilder-js/blob/main/libraries/botbuilder-core/src/cloudAdapterBase.ts) has any method called `exchangeToken`, please help verify this, thanks!

**Comment by ChetanSharma-msft** [comment]
Hello @wenytang-ms - We are looking into this issue and let you know the updates.

**Comment by wenytang-ms** [comment]
according to [this comment](https://github.com/microsoft/botbuilder-js/blob/f3db3e98bb139c7aecc921483ea188574de7aada/libraries/botbuilder/src/botFrameworkAdapter.ts#L201C26-L201C26), the `BotFrameworkAdapter` already deprecated and use `cloudAdapter` instead, so please verify such method on `cloudAdapter` class.

**Comment by Nivedipa-MSFT** [comment]
We are closing the issue as the PR with the necessary changes has already been completed for this.
[Change type [auth] to [silentAuth] and Converting [BotFrameworkAdapter] to [CloudAdapter] - msgext-search-sso-config sample by Harikrishnan-MSFT · Pull Request #968 · OfficeDev/Microsoft-Teams-Samples (github.com)](https://github.com/OfficeDev/Microsoft-Teams-Samples/pull/968)
