### ISSUE TITLE
Document how long we cache a user-specific view adaptive card 

### ISSUE THREAD

**Issue by aosolis** [MicrosoftDocs/msteams-docs#9422]
> Refresh timeout: Teams client triggers a refresh in two ways, either through Refresh or by selecting Execute. The refresh triggers only if the card from the last invoke is older than a minute. You can control the refresh behavior by adding a timestamp to the data bag and checking it before sending the refreshed card.

We document that we'll trigger a refresh it after 1 minute, but how long do we keep the data for?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 148d2ee0-4ac8-03c2-5493-dff7a762fba4
* Version Independent ID: 857f4370-d04b-357f-c7dc-b3449d353ba6
* Content: [User Specific Views - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/user-specific-views?tabs=mobile%2CC)
* Content Source: [msteams-platform/task-modules-and-cards/cards/Universal-actions-for-adaptive-cards/User-Specific-Views.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/task-modules-and-cards/cards/Universal-actions-for-adaptive-cards/User-Specific-Views.md)
* Service: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **surbhigupta**

**Comment by Meghana-MSFT** [comment]
Thank you for reporting this, we will check this and get the doc updated.
