### ISSUE TITLE
Duplicate sentence in Message formatting section

### ISSUE THREAD

**Issue by alexespencer** [MicrosoftDocs/msteams-docs#943]
"You can set the optional TextFormat property to control how your message's text content is rendered." can be removed

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d266eb0-2a29-db56-aeaf-dd14dfcdbe66
* Version Independent ID: d7a1fa1d-c083-9232-2259-4f8b267c7ee3
* Content: [Send and receive messages with a bot - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/bots/bot-conversations/bots-conversations#feedback)
* Content Source: [msteams-platform/concepts/bots/bot-conversations/bots-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/bots/bot-conversations/bots-conversations.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by clearab** [comment]
This article has been refactored, thanks for letting us know.
