### ISSUE TITLE
Bot application - chat - After the 'Chat' tab, Additional tab navigation provided with speech

### ISSUE THREAD

**Issue by sherryzhao11** [MicrosoftDocs/msteams-docs#9432]
Test Environment:
URL: https://teams.microsoft.com/
User: jtrott@sfsfeas.onmicrosoft.com Password: PI0FHS6GteIB7s5z
Environment: Windows 10/Chrome 106/JAWS 2023
Steps:
Login https://teams.microsoft.com/ User: lilly.sun@sfsfeas.onmicrosoft.com Password: PI0FHS6GteIB7s5z
Go "QA SAP SuccessFactors" app chat window.
Navigate to 'Activities' card.
Turn ON screen reader.
Actual Results:
After the 'Chat' tab, Additional tab navigation provided with speech as "Toolbar to move through items press left or right arrow, to activate press spacebar". Focus is also missing on the screen.
Record:
[After the 'Chat' tab, Additional tab navigation provided with speech.mp4]

https://github.com/MicrosoftDocs/msteams-docs/assets/132635147/817c6328-39fe-426b-ae9a-bff5ae5f2ae2

Expected:
Additional tab navigation and speech should not be provided.
If some UI on the page is read out, then focus should be provided for that element if it is interactive.
Only interactive elements should be part of tab navigation and should have focus and read out correctly.

**Comment by Meghana-MSFT** [comment]
@sherryzhao11 - Thank you for reporting this issue, we will check this and get back to you. Could you please re share the video attached in the question. We are not able to play the video. Thank you.

**Comment by sherryzhao11** [comment]
Hi sure, updated the video.

**Comment by Meghana-MSFT** [comment]
@sherryzhao11 - We checked this at our end, it is working fine at our end. JAWS does not announce "Toolbar to move through items press left or right arrow, to activate press spacebar". It just reads out "Chat tab selected 1-1, to activate press enter" and stops.

**Comment by Wajeed-msft** [comment]
@sherryzhao11 - could you please rotate the password for these two accounts?

jtrott@sfsfeas.onmicrosoft.com
lilly.sun@sfsfeas.onmicrosoft.com
