### ISSUE TITLE
[Error when testing the SBS guide to generate meeting side panel]

### ISSUE THREAD

**Issue by v-vanv** [MicrosoftDocs/msteams-docs#9433]
Meeting side panel

While testing the SBS guide for [Meeting Side Panel - Teams | Microsoft Learn](https://learn.microsoft.com/en-us/microsoftteams/platform/sbs-meetings-sidepanel?tabs=vs), we identified the following errors:

•	In SBS guide, the mentioned ngrok to setup is local host 3001, whereas the read me file (Microsoft-Teams-Samples/samples/meetings-sidepanel/csharp at main · OfficeDev/Microsoft-Teams-Samples (github.com)) suggests to setup local host 3978. 

•	The launchsettings.json, host is given as "applicationUrl": "http://localhost:3001",. Sharing the screenshot for your reference.
SBS guide:

![image](https://github.com/MicrosoftDocs/msteams-docs/assets/125454231/403f5cd0-7c11-4e0e-aae9-22288fe6dce1)

 Read me file:
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/125454231/ea37e99e-5ece-41d7-8953-d5821f1e4bfc)

When testing the SBS guide with both locahosts 3001 and 3978, we received the following ngrok error:

![image](https://github.com/MicrosoftDocs/msteams-docs/assets/125454231/55872d46-7087-46cf-9b1f-657a13dd0fc9)
 
When testing with dev tunnel, we got the following error:

![image](https://github.com/MicrosoftDocs/msteams-docs/assets/125454231/2db33f0c-0dd7-4e5f-b57e-55c4deff5417)
 

•	As per SBS guide and read me file, we should execute the following npx step after running the project solution in visual studio:
 
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/125454231/136ccd73-df04-443b-a8f2-4c138ca356a9)

After executing the step 8 from the above given image, we have added the app meeting side panel to Teams meeting, we received the following error:

![image](https://github.com/MicrosoftDocs/msteams-docs/assets/125454231/b442bb67-e892-484e-889d-e6caad2618ef)

Request you to look into the issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c1a955d5-85bc-7efd-c991-c705cf18d0b0
* Version Independent ID: c1a955d5-85bc-7efd-c991-c705cf18d0b0
* Content: [Meeting Side Panel - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/sbs-meetings-sidepanel?tabs=vs)
* Content Source: [msteams-platform/sbs-meetings-sidepanel.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/sbs-meetings-sidepanel.yml)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **surbhigupta**

**Comment by Meghana-MSFT** [comment]
Thank you for reporting this issue. We will test this and update you.

**Comment by v-ganr** [comment]
@Meghana-MSFT Could you please update on the issue?
Thanks.

**Comment by Meghana-MSFT** [comment]
Apologies for the delay, we are checking with the sample dev team. I will get back to you with an update.

**Comment by v-vanv** [comment]
Hi @Meghana-MSFT Could you please share an update on this issue?

**Comment by ChetanSharma-msft** [comment]
Hello @v-vanv - Sorry for delay in response.
We are looking into it and let you know the updates.

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, please feel free to reopen it, if required.

**Comment by v-vanv** [comment]
We've tested the [Meeting Side Panel](https://review.learn.microsoft.com/en-us/microsoftteams/platform/sbs-meetings-sidepanel?branch=pr-en-us-9323&tabs=dev%2Cvs&tutorial-step=8) SBS guide as per the response received [here](https://github.com/MicrosoftDocs/msteams-docs/issues/9433#issuecomment-1786683119)

During the first test, we observed the following:
 
1. While executing F5 in the project file, Bot is ready page appears without executing the following npm step.
         
2. Received the following error:

![image](https://github.com/MicrosoftDocs/msteams-docs/assets/125454231/37174ab3-f60b-4279-8eb3-0dc8905f725d)

 
 
While testing for the second time, we have executed the npm step first and then the execution of F5 for project file in VS.
We got the results: 

![image](https://github.com/MicrosoftDocs/msteams-docs/assets/125454231/d15d62dd-d4ea-4b1d-b00d-e46968264466)

 
However, we are not getting the final output as no response when selecting publish agenda.

**Comment by Meghana-MSFT** [comment]
PR has been https://github.com/OfficeDev/Microsoft-Teams-Samples/pull/1058 raised.

**Comment by Meghana-MSFT** [comment]
@v-vanv - PR has been merged now.
