### ISSUE TITLE
[Error when testing the SBS guide to build in-meeting document signing]

### ISSUE THREAD

**Issue by v-vanv** [MicrosoftDocs/msteams-docs#9435]
When testing the SBS guide for [Build in-meeting document signing app - Teams | Microsoft Learn](https://learn.microsoft.com/en-us/microsoftteams/platform/sbs-inmeeting-document-signing), we have faced the following error:

We’ve implemented all the steps given in the guide and created the Meeting Signing app. After adding the Meeting Signing app to a Teams meeting, we are getting the following error:

![image](https://github.com/MicrosoftDocs/msteams-docs/assets/125454231/745c7546-ee5e-40bc-b30f-63cf990cd307)

Please look into the issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3a692774-83a3-eccd-a5c2-7a5f43207399
* Version Independent ID: 3a692774-83a3-eccd-a5c2-7a5f43207399
* Content: [Build in-meeting document signing app - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/sbs-inmeeting-document-signing)
* Content Source: [msteams-platform/sbs-inmeeting-document-signing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/sbs-inmeeting-document-signing.yml)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **surbhigupta**

**Comment by Nivedipa-MSFT** [comment]
@v-vanv - Thanks for reporting your issue. We will test this and update you soon.

**Comment by v-ganr** [comment]
@Nivedipa-MSFT Could you please update on the issue?
Thanks.

**Comment by Nivedipa-MSFT** [comment]
@v-vanv, @v-ganr - We have tested [Build in-meeting document signing app - Teams | Microsoft Learn](https://learn.microsoft.com/en-us/microsoftteams/platform/sbs-inmeeting-document-signing) sample and it was working fine at our end.
The error message you're encountering suggests a mismatch between the app resource defined in your app's manifest and the origin of the iframe. This is a common issue when the app's domain isn't correctly configured in the app manifest.



1. Could you please check the validDomains section in your app manifest. The validDomains section in your app manifest should include all the domains used in your app. This includes the domain where your app is hosted and any additional domains your app might interact with. For example, if your app is hosted at "https://myapp.com", then "myapp.com" should be listed in the validDomains section.

2. Could you pleasecCheck the websiteUrl, contentUrl, and websiteUrl properties: The websiteUrl, contentUrl, and websiteUrl properties in your app manifest should match the domain where your app is hosted. For example, if your app is hosted at "https://myapp.com", then these properties should be set to URLs that are based on "https://myapp.com".

3. Could you please check the iframe origin. The origin of the iframe where your app is loaded should match the domain where your app is hosted. You can check the iframe origin by inspecting the Teams web client using your browser's developer tools.

**Comment by Nivedipa-MSFT** [comment]
@v-vanv, @v-ganr - Have you verified the above checkpoints and tested again? Are you able to resolve the issue?

**Comment by v-ganr** [comment]
@Nivedipa-MSFT We tested but blocked with a tunnel error and while uploading got the below error. Please let me know when we can connect and fix in a call.

![error](https://github.com/MicrosoftDocs/msteams-docs/assets/128352672/579ea13f-fe3b-45f2-bd95-d6c89c3afaa3)

**Comment by Nivedipa-MSFT** [comment]
@v-ganr - Could you please share your console error or log files to investigate further?

**Comment by v-ganr** [comment]
@Nivedipa-MSFT - Please find the console error, when tested with localhost 44326.

![Screenshot 2023-09-05 111304](https://github.com/MicrosoftDocs/msteams-docs/assets/128352672/90cc40bf-3501-4b26-b194-9b6716259491)

And when tested with localhost 5000, we got the below error.
![Screenshot 2023-09-05 191158](https://github.com/MicrosoftDocs/msteams-docs/assets/128352672/509fab1c-663f-4ccc-afcd-4ab580e10636)

**Comment by Nivedipa-MSFT** [comment]
@v-ganr - Could you please try deleting the 'obj' folder in your project source code, reinstall all dependencies, and check if it's working for you or not?

**Comment by v-ganr** [comment]
@Nivedipa-MSFT - We made changes in the sample as suggested and didn't get the output.

**Comment by ChetanSharma-msft** [comment]
Hello @v-ganr - We have fixed the sample and merged the PR as well.
Please do verify once again from your end.

Please share your valuable feedback for us: [Microsoft Teams Developer Community Response Feedback](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR7iCOpS5_b9Nqmwx43u5rtZUOThVR081SllSR05aSDQxQ0tUMDVPTVIxTi4u)

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, please feel free to reopen it, if required.

**Comment by v-ganr** [comment]
Hi @ChetanSharma-msft , @Mohammed-MSFT ,

Thanks for updating the sample.

We have tested the https://learn.microsoft.com/en-us/microsoftteams/platform/sbs-inmeeting-document-signing SBS guide as per feedback when we cross checked the tunnel is requested to run in 44326(both ngrok & devtunnel) and launch settings is updated to 3978. Please confirm even the tunnel has to be run in 3978.

![image](https://github.com/MicrosoftDocs/msteams-docs/assets/128352672/05688029-2d11-4d93-8317-be2423955358)

![image](https://github.com/MicrosoftDocs/msteams-docs/assets/128352672/2ed3a130-f0cf-48a8-b7c5-e5299d5ebfa7)

The below error is pop-up:

![image](https://github.com/MicrosoftDocs/msteams-docs/assets/128352672/d67fb53b-d58f-4c0e-8579-c634029216e2)
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/128352672/67803998-4c45-4d46-a916-d683e1287a78)

Please look into the issue.

Thanks.

**Comment by ChetanSharma-msft** [comment]
Hello @v-ganr - Thanks for the information.
We will update the Readme file as well and raise another PR for it.
