### ISSUE TITLE
Interface method IsTransient is marked as static incorrectly

### ISSUE THREAD

**Issue by vamsitp** [MicrosoftDocs/msteams-docs#9438]
`IsTransient` is an interface method that needs to be implemented. It cannot be `static` (and hence has compilation errors).  
`transientErrorStatusCodes` can be marked `static readonly`.

```cs
// List of error codes to retry on
List<int> transientErrorStatusCodes = new List<int>() { 429 };
public static bool IsTransient(Exception ex)
{
    ...
}
```

should be:

```cs
// List of error codes to retry on
private static readonly List<int> transientErrorStatusCodes = new List<int>() { 429 };
public bool IsTransient(Exception ex) 
{
    ...
}
```
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a57254c9-963d-ea1d-ecaf-dd0e7913526c
* Version Independent ID: 610c8514-bd72-46cc-75f1-991e2242019b
* Content: [Rate limiting for bots - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/rate-limit)
* Content Source: [msteams-platform/bots/how-to/rate-limit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/bots/how-to/rate-limit.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **surbhigupta**

**Comment by Prasad-MSFT** [comment]
@vamsitp - Thanks for raising this. We will check it and will make necessary changes accordingly.

**Comment by ChetanSharma-msft** [comment]
Hello @vamsitp - Could you please try below code and let me know if it's working for you:

`      // List of error codes to retry on
        private static List<int> transientErrorStatusCodes = new List<int>() { 429 };

        public static bool IsTransient(Exception ex)`

**Comment by ChetanSharma-msft** [comment]
Looks like a bug in the documentation:

@surbhigupta12  - Please help us to remove the `static` keywork from the below:
https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/rate-limit#detect-transient-exceptions-example

![image](https://github.com/MicrosoftDocs/msteams-docs/assets/59052547/95bb445e-4731-47ac-8a90-fe441210905c)

**Comment by vamsitp** [comment]
> Hello @vamsitp - Could you please try below code and let me know if it's working for you:
> 
> ```
> // List of error codes to retry on
> private static List<int> transientErrorStatusCodes = new List<int>() { 429 };
> public static bool IsTransient(Exception ex) {...........}
> ```
> Or
> 
> ```
> // List of error codes to retry on
> List<int> transientErrorStatusCodes = new List<int>() { 429 };
> public bool IsTransient(Exception ex) {...........}
> ```
> 
> You can use it with static and without static as well but in both the cases transientErrorStatusCodes  should also be static/non-static accordingly.
> 
> 

Do I need to try? I believe static on the interface method won't work.

**Comment by ChetanSharma-msft** [comment]
Hello @vamsitp -  Could you please share your valuable feedback via [Microsoft Teams Developer Community Response Feedback ](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR7iCOpS5_b9Nqmwx43u5rtZUOThVR081SllSR05aSDQxQ0tUMDVPTVIxTi4u)link?

**Comment by ChetanSharma-msft** [comment]
Yes correct @vamsitp - that's why I asked doc team to remove the `static` keywork from the documentation.
So, doc team will update it.

Do you have any other query?

If not, please share your valuable feedback here [Microsoft Teams Developer Community Response Feedback ](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR7iCOpS5_b9Nqmwx43u5rtZUOThVR081SllSR05aSDQxQ0tUMDVPTVIxTi4u)
