### ISSUE TITLE
Input.Date is not rendering the way it does in Designer

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#9439]
Copied bug from: https://github.com/microsoft/AdaptiveCards/issues/8657 

**Details from original post:**
### Problem Description

I am using Input.Date to get date range from the user in a Bot. Adaptive Card function is fine, however, the UI is not matching the one which comes in designer

### Card JSON

```JSON
{
            "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
            "type": "AdaptiveCard",
            "version": "1.5",
            "body": [
                 {   "id":"date",
                 "type": "Input.Date"
                }
            ],
            "actions": [
                {
                    "type": "Action.Submit",
                    "title": "Submit",
                    "data": {
                        "id": "updateUserInformation"
                    }
                }
            ]
        }
```

### Screenshot

![Designer_format](https://github.com/microsoft/AdaptiveCards/assets/87968298/f1392ecc-1254-43d2-a7fe-8396e351c863)
![myBot](https://github.com/microsoft/AdaptiveCards/assets/87968298/327d78ac-e7cd-47d3-b33d-5a12101eea6c)
---
#### Document Details

⚠ *Do not edit this section.It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Cards reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **surbhigupta12**

**Comment by sayali-MSFT** [comment]
@[AmitBa-Kore](https://github.com/AmitBa-Kore)-Thanks for reporting your issue.
We will check this at our end and will get back to you.

**Comment by sayali-MSFT** [comment]
@[AmitBa-Kore](https://github.com/AmitBa-Kore)-We were able to reproduce the scenario. We are currently checking with the engineering team to determine whether it is ByDesign behavior or a bug, and we will let you know once we have an update.

**Comment by VKZycus** [comment]
Can you please provide any update on this. we are still facing the issue.

**Comment by ChetanSharma-msft** [comment]
Hello @VKZycus - Sorry for delay in response.
**AdaptiveCard.io** site is for general usage and UI may be different on different platforms like in Teams/Outlook etc.

**Comment by sayali-MSFT** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.
