### ISSUE TITLE
Dynamic loading of adaptive card in teams

### ISSUE THREAD

**Issue by qjkobe** [MicrosoftDocs/msteams-docs#9442]
When the data are huge amount, we cannot show the data in one page. such as:
<img width="500" alt="image" src="https://github.com/MicrosoftDocs/msteams-docs/assets/16449598/90faab4f-2fd5-4733-863a-6cd0f68e015a">
We want having dynamic rendering function so that we can enable dynamic rendering by "view more".

**Comment by ChetanSharma-msft** [comment]
Hello @qjkobe - As per my understanding, we don't have any event/method related to capturing this event and dynamically bind the data.
Still, we will look into it and let you know the updates.

**Comment by Meghana-MSFT** [comment]
@qjkobe - Currently there is no function to dynamically render data using "view more".
