### ISSUE TITLE
Cant able to migrate app from App Studio to Developer Portal

### ISSUE THREAD

**Issue by Rashid-Cal4care** [MicrosoftDocs/msteams-docs#9444]
Hi Team,

I have tried to update my App Package to version 1.16 and its showing the error below
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/76432449/8b5313bc-68d6-46d6-92a7-4bbab7f10e37)

Also when I try to publish the app to store it show like 'Provided add-in package was not understood. Please, make sure that the file being submitted is a valid Office add-in package.' 
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/76432449/447089d3-690c-4783-b148-eefbc5b28511)

**Comment by Meghana-MSFT** [comment]
Thank you for reporting this issue, we will check this at our end and get back to you.

**Comment by Meghana-MSFT** [comment]
We tried upgrading App Package to version 1.16, it has worked fine. We got "app failed to upgrade to latest version" error only when the original manifest itself is not valid. 

To solve your issue, try the following before upgrading - 

1. **Provided add-in package was not understood. Please, make sure that the file being submitted is a valid Office add-in package**. - error comes if your app package has more than 3 files. App package should contain only manifest.json, outline and color files. Please check if you are adding anything extra in the app package. 
2. Please make sure that you have have created a zip folder that does not have any subfolder.

After making these changes, please validate your manifest using https://dev.teams.microsoft.com/validation. If the app package is valid, then try upgrading to version 1.16.

If you still get the error in developer portal, please share your manifest with us and remove any PII. Please share manifest at microsoftteamsdev@microsoft.com.

**Comment by Rashid-Cal4care** [comment]
Hi @Meghana-MSFT, 
Thanks for the response, I have tested this, but it's still not working and shows the same. I have only 3 files in the .zip file.

**Comment by Meghana-MSFT** [comment]
If you still get the error in developer portal, please share your manifest with us and remove any PII. Please share manifest at [microsoftteamsdev@microsoft.com](mailto:microsoftteamsdev@microsoft.com).

**Comment by Meghana-MSFT** [comment]
We checked this at our end. Please make the below chnages to your manifest

1. Add manifestVersion, there is no value added for it - 
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/81138249/5610e078-1e0a-435f-8498-0f7c41694158)

2. Add version in the $schema as well - 
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/81138249/a6226a74-f9f9-4698-838b-0e97f9daac1a)

3. Either remove or add values to groupchat & meetings in defaultGroupCapability property - 
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/81138249/3b4188e5-b5e0-4c47-b71c-e68e0817c896)

**Comment by Rashid-Cal4care** [comment]
Hi @Meghana-MSFT,

After changing the details that you have mentioned, its now validated, thanks for the support

**Comment by Meghana-MSFT** [comment]
@Rashid-Cal4care - Glad your issue has been resolved. We are closing this issue for now, please feel free to reach out to us if you have any further questions. 

Kindly share your valuable [feedback on your experience with our support team and Platform](https://aka.ms/DevSupportFeedback).

**Comment by Rashid-Cal4care** [comment]
The manifest is now validated, but there is no option to upload manifest to update the app in admin.teams.microsoft.com, now can you help me to update our old app in admin.teams.microsoft.com,

**Comment by Meghana-MSFT** [comment]
@Rashid-Cal4care - Could you please confirm if you are not able to see below option?
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/81138249/40cc99b1-37cf-4d24-944c-d2a84783b1f5)

**Comment by Rashid-Cal4care** [comment]
Hi,
No, i cant able to see this option. its just shows the version number only.

**Comment by Meghana-MSFT** [comment]
We will check this and get back to you.

**Comment by Rashid-Cal4care** [comment]
Hi,
We have published through Admin Portal, Do you want app credentials or admin portal login credentials?

**Comment by Meghana-MSFT** [comment]
Please share both.

**Comment by Rashid-Cal4care** [comment]
I don't have permission to provide the login details, can we have a remote session instead..?

**Comment by Meghana-MSFT** [comment]
@Rashid-Cal4care - Apologies for the delay. Could you please share the original app manifest and the updated app manifest?

**Comment by Rashid-Cal4care** [comment]
@Meghana-MSFT sorry for the delay, I will send both.

**Comment by Meghana-MSFT** [comment]
We received your app packages, we will check and get back to you.

**Comment by Meghana-MSFT** [comment]
@Rashid-Cal4care - Apologies for the delay, could you please let us know if you are still facing this issue?
