### ISSUE TITLE
teamsJS clipboard missing documentation

### ISSUE THREAD

**Issue by MichaMican** [MicrosoftDocs/msteams-docs#9446]
With teamsJS 2.15 the clipboard api was introduced - I believe the documentation for this is missing completely

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: aadca17b-de5c-0d06-caa6-d7bafd04f99b
* Version Independent ID: 91035790-5d36-067e-4400-04bb51cb03e3
* Content: [Microsoft Teams SDK reference - Teams](https://learn.microsoft.com/en-us/javascript/api/overview/msteams-client?view=msteams-client-js-latest&tabs=npm)
* Content Source: [nodejs/overview/msteams-client.md](https://github.com/OfficeDev/msteams-client-docs-ref-typescript/blob/live/nodejs/overview/msteams-client.md)
* Service: **msteams**
* GitHub Login: @charlesprakash
* Microsoft Alias: **o365devx**

**Comment by ChetanSharma-msft** [comment]
Hello @MichaMican - Looks like it is a duplicate issue, so closing it.
Please track it here: https://github.com/OfficeDev/microsoft-teams-library-js/issues/1921
