### ISSUE TITLE
Unable to get the output for Send Proactive Messages SBS

### ISSUE THREAD

**Issue by v-preethah** [MicrosoftDocs/msteams-docs#9449]
1. The sample folder doesn't have the manifest file, hence not getting the expected output.
    Bot sample cloned as per the instruction in the readme file -  https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/16.proactive-messages
Not getting the **Bot is ready** screen in web browser after Debugging.

2. Getting ngrok error.
<img width="660" alt="ngrok error" src="https://github.com/MicrosoftDocs/msteams-docs/assets/117343020/a304a080-6257-435e-bdd9-b2e580046213">

3. Getting error on localhost. Verified the localhost in launchsettings and it's 3978, still not getting the output.
<img width="578" alt="localhost error" src="https://github.com/MicrosoftDocs/msteams-docs/assets/117343020/647f225d-65d5-4211-a138-03a771276acb">

Request you to please check and let us know, if there's anything missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 254baa71-bf79-048a-3dd9-c9ee025f5de2
* Version Independent ID: d7374135-ac5f-b2f3-0340-d1585d4cb3be
* Content: [Send Proactive Messages - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/sbs-send-proactive)
* Content Source: [msteams-platform/sbs-send-proactive.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/sbs-send-proactive.yml)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **surbhigupta**

**Comment by sayali-MSFT** [comment]
@v-preethah - Thanks for reporting your issue.
We will check this at our end and will get back to you.

**Comment by sayali-MSFT** [comment]
@v-preethah -Have you followed these steps-
**Connect to the bot using Bot Framework Emulator**
1. Launch Bot Framework Emulator
2. File -> Open Bot
3. Enter a Bot URL of http://localhost:3978/api/messages

With the Bot Framework Emulator connected to your running bot, the sample will not respond to an HTTP GET that will trigger a proactive message. The proactive message can be triggered from the command line using curl or similar tooling, or can be triggered by opening a browser window and navigating to http://localhost:3978/api/notify.

We have tried the same sample, and it is working fine from our end-
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/93527375/380a16d0-b00c-42b8-9a8b-889a1d144d01)

**Comment by v-preethah** [comment]
Hi @sayali-MSFT 

I have followed the steps using Bot Framework Emulator, and getting the following error. Can you please help resolve?

![image](https://github.com/MicrosoftDocs/msteams-docs/assets/117343020/0c69d144-913f-42b8-a89e-38a02ec87682)
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/117343020/1142ccf8-3e4f-4bf6-9f5e-e9144d88d2fe)
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/117343020/362f88ba-9f67-4a13-8155-f50f2eaa7d70)

**Comment by sayali-MSFT** [comment]
@v-preethah -Have you change the [app setting value](https://github.com/microsoft/BotBuilder-Samples/blob/main/samples/csharp_dotnetcore/16.proactive-messages/appsettings.json) in the sample?
Just change those value and run the sample.

and triggered by opening a browser windows and navigating to http://localhost:3978/api/notify.

**Comment by v-preethah** [comment]
Hi @sayali-MSFT 

I have tried testing as suggested, still I'm not able to get the expected output. I'm getting the following error. Attaching screens for your reference. Please help.

- ngrok was active while testing.
- appsettings was updated.
- bot was updated with the updated ngrok.

<img width="960" alt="Screenshot (68)" src="https://github.com/MicrosoftDocs/msteams-docs/assets/117343020/0fcb7fbf-67f4-41e8-b6f8-6eb0746db085">
<img width="960" alt="Screenshot (69)" src="https://github.com/MicrosoftDocs/msteams-docs/assets/117343020/b3f554f5-66e9-4537-9392-96949454840f">
<img width="960" alt="Screenshot (70)" src="https://github.com/MicrosoftDocs/msteams-docs/assets/117343020/cccb072f-5217-446e-ac39-ad9127fa5fb5">
<img width="960" alt="Screenshot (65)" src="https://github.com/MicrosoftDocs/msteams-docs/assets/117343020/1ccbeda1-3230-445a-b58a-d6b2a0cee06c">

**Comment by sayali-MSFT** [comment]
@v-preethah -Change the PORT 3978 to 3979 n try it once.
Could you please look into this troubleshoot the ngrok error-
https://ngrok.com/docs/errors/err_ngrok_8012/#troubleshooting

**Comment by ChetanSharma-msft** [comment]
Hello @v-preethah - Please check and let us know whether you are still facing the issue.

**Comment by v-preethah** [comment]
Hi @ChetanSharma-msft 

Tested as suggested by Sayali, and we also tested with the help of another writer. We are facing the same issue.
- We tested with port 3979.
- We also tested in a different account.

Please help resolve.

**Comment by v-preethah** [comment]
Hi @sayali-MSFT,

The bot is working, but when we run it in Bot Framework Emulator we are getting error. And we don't have manifest file to upload and check the same in Teams. 

Please help resolve.

Adding screenshot for reference:
<img width="960" alt="Screenshot (73)" src="https://github.com/MicrosoftDocs/msteams-docs/assets/117343020/977cfd69-b947-4629-af8c-896d4a5edba3">
<img width="960" alt="Screenshot (74)" src="https://github.com/MicrosoftDocs/msteams-docs/assets/117343020/fd75d145-93e2-43c5-b37f-69b57d99aeb0">

**Comment by sayali-MSFT** [comment]
@v-preethah -Did you get chance to check add the app and team as our internal discussion?

**Comment by v-preethah** [comment]
As per the discussion, unable to add the app to Teams. 
Updating the SBS per Teams Toolkit sample in Visual Studio Code, hence no dependency on this for now.

**Comment by v-preethah** [comment]
Hi @sayali-MSFT,

I'm still facing difficulties to upload the app.

**Comment by sayali-MSFT** [comment]
@v-preethah -Did you getting the same issue?

**Comment by v-preethah** [comment]
SBS to be updated with Visual Studio Code TTK sample for Proactive messaging bot.

Tested the sample and not able to provision.

**Comment by v-preethah** [comment]
Tested with Teams Toolkit sample and updated the SBS as per TTK procedure.

**Comment by v-preethah** [comment]
The SBS guide is updated via PR: https://github.com/MicrosoftDocs/msteams-docs/pull/9351. 
Review site: https://learn.microsoft.com/en-us/microsoftteams/platform/sbs-send-proactive?tabs=vscode

**Comment by v-deabira** [comment]
Closing the issue and it has been resolved and addressed in PR 9351.
