### ISSUE TITLE
[Accessibility] Focus is missing on the card when navigated using tab key from actions buttons

### ISSUE THREAD

**Issue by AmyLi0728** [MicrosoftDocs/msteams-docs#9454]
# Description
When we navigated using tab key from action toolbar like below picture, focus is missing on the card:
Please see this requirement - https://wiki.one.int.sap/wiki/display/Acc/ACC-271+Details#ACC271Details-acc2711

# Excepted Behavior
When navigated to card contents from action buttons (Like, laugh, More reactions, More actions) focus should be provided for the UI that is being announced.
Please see this requirement - https://wiki.one.int.sap/wiki/display/Acc/ACC-271+Details#ACC271Details-acc2711

# Card Json
{
    "type": "AdaptiveCard",
    "$schema": "[http://adaptivecards.io/schemas/adaptive-card.json"](http://adaptivecards.io/schemas/adaptive-card.json%22),
    "version": "1.5",
    "msteams": {
        "width": "Full"
    },
    "body": [
        {
            "type": "ColumnSet",
            "columns": [
                {
                    "type": "Column",
                    "width": "stretch",
                    "items": [
                        {
                            "type": "TextBlock",
                            "text": "Complete 360 Evaluation",
                            "wrap": true,
                            "weight": "Bolder",
                            "size": "Large",
                            "fontType": "Default",
                            "style": "heading"
                        }
                    ]
                }
            ]
        },
        {
            "type": "ColumnSet",
            "columns": [
                {
                    "type": "Column",
                    "width": "stretch",
                    "items": [
                        {
                            "type": "TextBlock",
                            "text": "Manager approves raters",
                            "wrap": true,
                            "weight": "Bolder",
                            "size": "Medium",
                            "fontType": "Default",
                            "spacing": "Small"
                        },
                        {
                            "type": "TextBlock",
                            "text": "360 Multi-Rater Form",
                            "wrap": true,
                            "weight": "Lighter",
                            "isSubtle": true,
                            "size": "Medium",
                            "spacing": "Small"
                        },
                        {
                            "type": "Container",
                            "spacing": "Large",
                            "items": [
                                {
                                    "type": "ColumnSet",
                                    "columns": [
                                        {
                                            "type": "Column",
                                            "width": "auto",
                                            "items": [
                                                {
                                                    "type": "Image",
                                                    "url": "data:image/jpeg;base64,/9j/4AAQSkZJRgABAgAAAQABAAD/2wBDAAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEB\r\nAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQH/2wBDAQEBAQEBAQEBAQEBAQEBAQEBAQEB\r\nAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQH/wAARCAA8ADwDASIA\r\nAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQA\r\nAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3\r\nODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWm\r\np6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEA\r\nAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSEx\r\nBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElK\r\nU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3\r\nuLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD+/iii\r\nigClqOo6fpGn32ratfWemaVplnc6hqWpahcw2dhp9hZwvcXd7e3dw8dva2lrbxyT3FxPIkMMKPJI\r\n6orMPyg+P/8AwWn/AGJPgNrF14fPirW/idqlvYG8Wf4cWuk6loE06SIsunw+IdU1nSrG6uYIZEuZ\r\n5NPF9aRwsF+0mfMI/nk/4OKf+Cp3xm0H4yeLP2PPhp408PaN8EPDGm6HZ/EeLw3fS2vibxh4ru9N\r\nTVtT8NeKdRuIkxouizz2Vu+gaTLFa31xCw1a4vAzWln/AB7eG9f+JvxB1LW7eyudYvNLuru3stLv\r\n11O4nnsbadLiKeG0jnkZkgjd0kEsjh4Z0OZHihjI6YUoRi6lZ8sEuZtvlio2vduy+6/XrsedUxdS\r\nVZUcPDnnzKO3M22+iX5/5H+mb4c/4L+/sPa7daWt7bfE7w9p2r29zJaX+paDod1IbqARSR2Mljo/\r\niPUpluLqA3MsKK7OrWU0E0cU8ltHP+sHwQ/aA+D37R3gqz+IPwX8eaH468M3axebPpVyPt+l3Eye\r\nYtjrukTiLVND1AIC/wBi1S0tbho8Sxo8TK5/yjdf/Yr+NPh620LxT4U+Jkfiiy1W61S6hsLbUdl9\r\nb3Gk25a1txYGaKTyReIjPOytbTLDfraM7AzJ9p/sT/tr/tDfsN/Gjw/4o0rXJtO8URxaZD4z8LW0\r\nl9c+GfH3h9Lq1k1TQvEsUEcsV0hVpPsE3l3r6Zevb6rYXyzIIbjmpYjAYttYTE06k0ruMZNtapNS\r\nTV4tO/3bHZOhmmE5XjcJOnSlypVHFpaqLTvs3Z3sne1762P9QKivFP2c/jl4T/aU+CHwz+Ofghwf\r\nDfxK8LWPiOxh84XD2E8pktdU0i4mWOLdeaLq1tfaTehoYXW6s5Q0MZ+Ue102mm09GtGaJppNdUn8\r\nnsBIHJqreTC2tppmljgSGMySzynKQQpgyzMCRu8uMO4BOGKgHOSKskgYz36da8S/aR+IGu/Cr4Ff\r\nE74ieGNDh8R6/wCEPC17rOlaTdRTTWcl5btF5V1fw2zxTy6dpe7+09Rjhlikexs7hUljYiRcq1aG\r\nHpVK9Xm9nRhKrPli5y5IJylaEU3J2WkUm29EjWjSnXrUaFPldStUhSpqUlGLnUkoxUpSaUVdq8m0\r\nkrts/wAj79vvx54o+Jv7RHxc8Xahe6hca940+K/xAvI7GZ7nUJZdR1Txvq91/of27clxDCJzC1zd\r\nWi3BCQwCGCNo4a/oz/4JIf8ABNLTvAfw08PfFf446FdanrutW0V/onhLWAzTRWl1E7R6nrUVz5Zj\r\nyrMLW1mRroBxchYo8Cvyk/Zr+AGp/Ff9vDUluodF8Wj4SavrOra5exxalc+F4tbvfE97qltqE322\r\nAajLZgS+bHDdRJfbUZJj56mQfvDD+3Z4n8GfEy1+HPgPx7qHje7TTPGfiFbHUv2crM/DbVPD3wwv\r\nDp3xJ1Hw14r03xrJ4xmtvBE0V0muyLPO9tDZ391BY3EFhchPiuK8zxuZwllGU1fZw9jHE4ypGFWU\r\n3RnGMoU17OnJ0o8jTlKTj2dtb/ecD5JgMvqxzjN6XtJ/WPq2DpuVGMI1oS5JVG6tSPtZ86lGKhzb\r\nOW7R+zWnfsL/ALOmv6Dd+KdA8HaRp91JhNWsBajZdLHGkkqWVzHH5umXEQnSW2mtdsZQqHRF2sP5\r\nJv8AgrD+ynqXwQ8V6h8TvA+m3p+F18x0qa4aB5LrwRfMn2dVv2tY0C2LSxx3MOpQJts51jljaL5n\r\nk/q50v8Aa6n0L9nG5+J2nT6VZ2c9ss0kFlpuparol1qhjZBZ+UCupyQjZNcjYTJLbssSz/LGT+Uv\r\nhz9o/wAN/ts6n4g+GPxH8XJpFt4l8YeMfg3dafqXwB07w78N28eaTZXl5qvgCbWE8WXPiex8WWen\r\nQXF1CNRu7iKaGKe7ihuHtZbdPlssxdTCTwuMylQU8AoQzaEoVZUq1ObjFuVSkqkae/NGVVQs3q7X\r\nPvc8y/D42hicHmXNKOO55ZTOMqUatCpCHPZQqOm6naUaTm2knvovu3/g2D+N/iXxp+yN8R/g3401\r\nAXOs/Cj4gRavoMa3NveWtx4S8caf9oGp6VeQ83Fhe+INL1e7njLOtjqV5d2m2J0ZB/TQQc8Nj2wD\r\nX8ln/BvN8EfEXwJ/aS/a08I21pe2fgXSbPXvA6wXV9PLDF4m+H/jvTrLba2jYiRZNH1eCdrgqkjx\r\nSW4IeQzFf61K/YY1adeFOtSd6dWnCpF3vpOKdvle2uvc/AXTqUJVKNRe/RqTpSWzvCTV3dq17dO6\r\naCvnr9qbwfB8Q/gd498A3ZmSx8b6FqPhHUbiG4uoG07S/EVlPpWs6wFs7i2mvJdF0W61LVbPTzI0\r\nN7f2lpBPDNCzofoWvFv2iL3VtK+CvxF1jQ4bG41bRvDWoalaDUriS1sE+zRE3M13NDa3siW0Fk1z\r\nNOFt33xxtGdquXWkk2k1dPRp63T0f4FRbjJSTaaaaa3VnfQ/jR/4JCfAK4+F9v8AtDeFfFXhXV9B\r\n1678fQ38tz4l0p7TU9T0y0fVNBtnS4nMv2yyKWdteh4biWA3N9dFtspbP6zz/se/BbStW1X4uNpu\r\nl6Pq0GjaxFqV/aqlvJcaZdRIdXsnkQIEtNQihT+0rYlrW7jQLdQyEAD8JP8Agn5+3ZqPjj9vH46+\r\nHPH62+hW/wC0r4atde+D+kxX5l0i28T+DzqXiMeCdBkmmBW81rwjq15elHgtZrzxBpEluYkkuraA\r\nftJ8Sfid8U9Fg0q78I+A9O+KHg/Ul+weK9K1bxinhNrDRr4z2uo3ltDc6LqNrrTQQyQLcaXdXejx\r\nJE8/m3wk2V+EZ/h8Rh86xcfb4iMqtVqnJVJUfbUZxjKKfvWap2lCzvpFd2j+keCK2HzLJMJGnQoK\r\npQkouk4wm1VU1quaOjqOSmmlduVrs+nPCngTR5fhvqfhVfCSx+HodQswuieXbtc7TayiJvKEhZWk\r\niXzY33hiWAeRXZVbhfB/7G/wZ0jXo/GfhXfLrWoaobiGwv5I55rHVtQeJLy6aSW3+0S3cwVIprm7\r\nuJrmWFEjkl2Iqrw/gXwFaaB4E1/xzo+l+AdNufEdxpHii18G6pq3xL1WxfxBG0NrpcEGiPob2Efi\r\nSW6htNPTVNN1i5sS1ul1HI0aiRsrX/i9rH7OWg/FX9pL42T6VoGk+EfCuk6k3g3w9f313pGp+Pbu\r\nGSw8NeFvD8+qMbnVvE2v6xd6Xo0j2tnZwyJaz6tLp0NpYX9xFx0MvxMalDDx9ry42VOnUjGupNwc\r\n1abVJ20Sfx+XWyPpMzSy/DYnE4+McO8FGrKmq1CVNutCEbxSrxi5JuSi50bpSum9df1D/YM+Ecfg\r\nbVf2pPHFxpC2M/xO/aL8W+I9BuHjRJpfC8WgeEtBSeOPHm28Gr6x4f1LVgHKG8juLe8EZieGRv0P\r\nr8/P+Canxmm+O37Mnh7xxqc5n8QR6ld6HrczMrNeTWUNteaZqxaMeWz6xompaZqFyIy8cF/Ne2gc\r\nNatFF+gdfvODoRw2Fw9CLclSo04Xe7agk297Xd3pofynjq8sTi8RiHGzrVpz5dNE27LdbKyv13Cu\r\nV8b6dDrPhDxLo11os3iOz1jRNU0m+0S3vILC41Oy1Kzms7qzhvLme1gt5JoJnjSZ7q38osJFmRlD\r\nDqqK6k7NPs7nKf5Tvg/9m743/s9/8FdfgZo3jfwV4/8Ahh4X0T42TXngfQviH9luNb074cSaHq8v\r\nwjt/7Z0vGhane3XhXSrW3NzpF1du82j63O7ibR9SNv8A1+eD/i9oUv8Aas3iCzt5tOhuwdWtkG1I\r\n5ZkC3FyqRjfavcbjLL5AMUjKzou1ty+W/wDBczQ7O/8AHv7BXxMke6i8UeFv2xvGPh7Qnt7h49O0\r\n/Rn+GHjmwksbfTiGgiilWBrqVogkkt7dXdxI7Gbavheg2v2vxHrEctxcCO7hW3uI0dPLliLNlXja\r\nN0Y4ONzKW4DZ3fNX4h4nYiphs8wkaDUUsBCpNSSanKdWpJJpNbK3vaNXcVorv968KcLzZLiq05XU\r\nsfKMEnJSgo06HXTW706LTsfenhn4n/sg6T4ksV8OW7XPjfUX26bpmnaxrWsajPdqSCtloHmXK2pU\r\nyDzZisFtCW/ezRoSw/ED/guP8UvFMXxm+AXgxUml8OeFPhh4u+NPiz4ewTTT/wBlaUfF9h4G/wCE\r\n9u4t8Nje3nh6PUI7DXdQt/t154f0zWGvIraHQ4dc1VP3Q/Z++DHw78J2/wDwlekaDCPEdxauz6zd\r\nsLu/XcWfbFPKpaJA+HVY9u1gCMEV88+OfgH8LPi5/wAFWf2N7b4ieGbfxRZeKfgZ+158LvEmn6ix\r\nlstb8E+LvCPhfRda0e/gK4kSWy8SawLeZDHNazXbSwurAVz8F5jUr57gMPiYQdOrGrTXs42amqMn\r\nCUuZ6pa6LrZu7St63iFQqV8ixtdV6sp4VUZXrVJzbpqtTUoRu3ZtP3b+6mrWSbPqv/ghr40h0T4Q\r\nXngNr63n0S/vU1fSGjURyWlzqVlb3otL6J28+G5hlXU7W4klDRSKmlXUMgt9Tt4of6Aq/kd/4Ir2\r\n138Pfid8X/hFpus6vq/hj4UftDfEf4YeFLvxFcQ6jrw8I+DNe+NHgLSbPU9ShtrNL+aTQ/hv4Vkv\r\nZ2tY/N1C0muoUt1uGhX+t6EloomPVo0J+pUE/rX71OmqcYW2s42/wWV/uf8ATP5wk25Nve7uf//Z\r\n",
                                                    "size": "Small",
                                                    "style": "Person"
                                                }
                                            ]
                                        },
                                        {
                                            "type": "Column",
                                            "width": "stretch",
                                            "verticalContentAlignment": "Center",
                                            "items": [
                                                {
                                                    "type": "TextBlock",
                                                    "text": "Annie Singh",
                                                    "weight": "Bolder",
                                                    "wrap": true
                                                },
                                                {
                                                    "type": "TextBlock",
                                                    "spacing": "None",
                                                    "isSubtle": true,
                                                    "wrap": true
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            "type": "TextBlock",
                            "wrap": true,
                            "weight": "Lighter",
                            "isSubtle": true,
                            "size": "Medium",
                            "spacing": "Small"
                        },
                        {
                            "type": "TextBlock",
                            "text": "35 days overdue",
                            "wrap": true,
                            "weight": "Lighter",
                            "isSubtle": true,
                            "size": "Medium",
                            "spacing": "Small",
                            "color": "Attention"
                        }
                    ]
                }
            ],
            "spacing": "Large"
        },
        {
            "type": "ColumnSet",
            "spacing": "Large",
            "columns": [
                {
                    "type": "Column",
                    "items": [
                        {
                            "type": "TextBlock",
                            "text": "Go to Form",
                            "color": "Accent",
                            "spacing": "Large"
                        }
                    ],
                    "width": "stretch"
                }
            ],
            "selectAction": {
                "type": "Action.OpenUrl",
                "url": "[https://qacand.hcm.ondemand.com/sf/pmreview?fid=28832&company=AFTTeamsDev&username=sfadmin&reqOrig=todoList&stxid=341915&formtype=360&&companyId=AFTTeamsDev"](https://qacand.hcm.ondemand.com/sf/pmreview?fid=28832&company=AFTTeamsDev&username=sfadmin&reqOrig=todoList&stxid=341915&formtype=360&&companyId=AFTTeamsDev%22)
            }
        }
    ]
}

**Comment by Meghana-MSFT** [comment]
> Please see this requirement - https://wiki.one.int.sap/wiki/display/Acc/ACC-271+Details#ACC271Details-acc2711

This is asking for login, could you please add screenshot/video recording of the issue to the question directly.

**Comment by AmyLi0728** [comment]
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/144102521/13c76207-5bc9-4cfb-b448-4fc8adb4fc6d)

**Comment by Meghana-MSFT** [comment]
We checked this navigating the tab, arrow keys and it is working fine at our end. 

https://github.com/MicrosoftDocs/msteams-docs/assets/81138249/4bbcae00-3f40-4315-919e-647a0484490f

If your issue is different, could you please explain/share video of the above test cases. Are you using keyboard only or screen reader as well for accessibility?
