### ISSUE TITLE
Please add the table border properly.

### ISSUE THREAD

**Issue by sayali-MSFT** [MicrosoftDocs/msteams-docs#9455]
Please add the table border properly in compose extension section-

<html>
<body>

Name | Type | Maximum Size | Required | Description
-- | -- | -- | -- | --
botId | String |   | ✔️ | The unique Microsoft app ID for the bot that backs the message extension, as registered with the Bot Framework. The ID can be the same as the overall App ID.
commands | Array of objects | 10 | ✔️ | Array of commands the message extension supports.
canUpdateConfiguration | Boolean |   |   | A value indicating whether the configuration of a message extension can be updated by the user. Default: false.
messageHandlers | Array of objects | 5 |   | A list of handlers that allow apps to be invoked when certain conditions are met.
messageHandlers.type | String |   |   | The type of message handler. Must be "link".
messageHandlers.value.domains | Array of strings | 2048 characters |   | Array of domains that the link message handler can register for.
messageHandlers.value.supportsAnonymizedPayloads | Boolean |   |   | A boolean value that indicates whether the app's link message handler supports anonymous invoke flow. Default is false.

</body>
</html>

Document Link-https://learn.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema#composeextensions

Currently it is showing like below-
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/93527375/5a802935-51a7-41f5-a3a9-b87c97c1e284)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0f94a488-d636-92b3-21eb-c88744c8f272
* Version Independent ID: 7b3413f4-9ade-accf-5cb2-83fead11a32a
* Content: [Manifest schema reference - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema#composeextension)
* Content Source: [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/resources/schema/manifest-schema.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **surbhigupta**

**Comment by sayali-MSFT** [comment]
@surbhigupta12 -Could you please help us to update the document.

**Comment by v-rmvv** [comment]
The ask for creating a table is not possible.
