### ISSUE TITLE
"Back" action in Adaptive Card

### ISSUE THREAD

**Issue by qjkobe** [MicrosoftDocs/msteams-docs#9460]
Sometimes we use Adaptive Card with Task Module to show a work flow with many steps.
For example:
Step1: Input login name.
<img width="363" alt="image" src="https://github.com/MicrosoftDocs/msteams-docs/assets/16449598/539f7429-3846-4695-9d62-c14c46b72b40">

Step2: Input more detail information.
<img width="358" alt="image" src="https://github.com/MicrosoftDocs/msteams-docs/assets/16449598/55d65cde-10ee-4299-b3e0-9030218ec817">

If someone want to go back to Step 1 from Step 2. He just click "Back". But adaptive card doesn't have a "back" function. To implement this function, we can only use `Action.Submit` to mock a "Back" function. Then there will be a dilemma: `Action.Submit` will check the `required` fields. But user just want to go back.
So we want that Adaptive Card in Task Module has a function just like `Action.Back`. It will be rendered as a button or other interactive controls. If user click this, it will go back to the previous step with context which user has inputted.

**Comment by sayali-MSFT** [comment]
@qjkobe -Thanks for reporting your issue.
We will check this at our end and will get back to you.

**Comment by sayali-MSFT** [comment]
@qjkobe -The Adaptive Cards framework supports various types of actions that can be triggered when a user interacts with an Adaptive Card. However, there is no specific "Back" action type in Adaptive Cards.

- **Action.OpenUrl** - open the specified url.
- Action.Submit - take the result of the submit and send it to the source. How you send it to the source of the card is entirely up to you.
- **Action.ShowCard** - invokes a dialog and renders the sub-card into that dialog. Note that you only need to handle this if ShowCardActionMode is set to popup.
- **Action.ToggleVisibility** - shows or hides one or more elements in the card.
- **Action.Execute** - gathers input fields, merges with optional data field, and sends an event to the client. Learn more about Action.Execute in our [Universal Action Model](https://learn.microsoft.com/en-us/adaptive-cards/authoring-cards/universal-action-model) section.

As you mentioned above, this is a kind of new feature request.

Could you please help by suggesting this feature on - [Microsoft Teams · Community](https://feedbackportal.microsoft.com/feedback/forum/ad198462-1c1c-ec11-b6e7-0022481f8472)

**Comment by sayali-MSFT** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.
