### ISSUE TITLE
Change app studio to Developer Portal

### ISSUE THREAD

**Issue by Meghana-MSFT** [MicrosoftDocs/msteams-docs#9466]
app studio is deprecated, and we have Developer Portal now. Please change the term app studio to Developer Portal. 
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/81138249/c6a97656-db03-4d26-8489-abe568c610c3)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 893c2c9e-10e1-dd4e-1eb4-b4e9a46a9f8d
* Version Independent ID: 5f41c382-377c-6c9b-4932-65853675c4ad
* Content: [Use Microsoft Graph to authorize proactive bot installation and messaging in Teams - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/graph-api/proactive-bots-and-messages/graph-proactive-bots-and-messages?context=graph%2Fcontext&tabs=dotnet)
* Content Source: [msteams-platform/graph-api/proactive-bots-and-messages/graph-proactive-bots-and-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/graph-api/proactive-bots-and-messages/graph-proactive-bots-and-messages.md)
* Service: **msteams**
* GitHub Login: @AkJo
* Microsoft Alias: **surbhigupta**

**Comment by Meghana-MSFT** [comment]
@surbhigupta12 - Could you please help to update this.

**Comment by surbhigupta12** [comment]
This is a bug in graph repo. We're updating the same there.

**Comment by surbhigupta12** [comment]
Graph repo issue.
