### ISSUE TITLE
External App ID no longer working with deep links MS Teams Beta

### ISSUE THREAD

**Issue by shootex20** [MicrosoftDocs/msteams-docs#9470]
Hello,

I'm currently running into an issue where MS Teams Beta Preview Version: 
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/19786531/66618c9d-2c58-427a-966c-d2b221febbc9)
We currently have deep links which use an external app id's in order for our deep links to work universally. This is what our deep links usually look like https://teams.microsoft.com/l/entity/<Ext_App_Id>/<Tab_id>?context=%7B%22subEntityId%22%3Anull%7D
Each time we click the link in the preview beta version we now get this error 
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/19786531/18698da8-6e85-415f-a74f-5593bb2251a0)

However when using our normal links in Team Classic version: 
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/19786531/3e081289-2bab-499c-a1bd-fdca373385a0)
This is the result we receive with the teams classic which works perfectly fine 
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/19786531/18fb8d83-426e-48aa-9ae4-559321dd6ef7)
Is this a bug with the new teams preview beta? Or is the external app id being depreciated from the teams beta? 

Thanks in advance, please let me know if there is any other information I can provide.

**Comment by Prasad-MSFT** [comment]
@shootex20 , thanks for raising this issue. We will check it from our end and will get back to you with updates.

**Comment by shootex20** [comment]
> @shootex20, thanks for raising this issue. We will check it from our end and will get back to you with updates. Just to be on same page, by mentioning MS Teams beta you mean to say Teams T2.1 right? ![image](https://user-images.githubusercontent.com/62237649/268278335-8624e53b-275f-4928-b479-5cf64de1197b.png)
> 
> Also please make sure you are using the correct app id. Following are the different app IDs that are used for deep links:
> 
> **Side loaded apps:** Manifest ID **Apps submitted to org catalog:** Org catalog ID **Apps submitted to Teams app store:** Store ID

Yes, the Teams 2.1 is the version where I'm having the issue.

I have double checked the external app id and it looks good, double checked the tab id as well and it looks perfect as well when I checked it.

Just to reiterate, this does with fine with Teams 1.6, swapping to teams 2.1 it is completely broken. If I use the internal app id it works fine with teams 2.1 but this is not the ideal solution for scaling out deep links with our apps.

Thank you for the quick reply.

**Comment by Prasad-MSFT** [comment]
@shootex20 - Is your app submitted to org catalog? If that's the case then as mentioned in the [documentation](https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-link-application?tabs=teamsjs-v2#app-id-used-for-different-apps), we need to use `Org catalog ID` not `External App ID/ Manifest ID`.
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/62237649/2fed77fb-5ab6-4f25-b57f-a79773364695)

**Comment by Prasad-MSFT** [comment]
@shootex20 - You are right. We tried to repro this issue using below sample 
https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/tab-deeplink/csharp
and observed that although it works in Teams classic, it doesn't work in Teams T2.1
We have raised a bug for the same. We will inform you once we get any further update from engineering team. Thanks!

**Comment by shootex20** [comment]
> @shootex20 - You are right. We tried to repro this issue using below sample https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/tab-deeplink/csharp and observed that although it works in Teams classic, it doesn't work in Teams T2.1 We have raised a bug for the same. We will inform you once we get any further update from engineering team. Thanks!

Thanks for the reply and the update. Appreciate it!

**Comment by Doctor-Scott** [comment]
Yeah this is still a problem for us, is there any update on a fix?

**Comment by jdominguez81** [comment]
Any news on this topic?
It's been two months

**Comment by Doctor-Scott** [comment]
Still broken for us in new teams. If Microsoft is going to push all users to use new teams, this should really be fixed first

**Comment by manuelsidler** [comment]
We faced a similiar issue with external ids. But instead of "This app cannot be found" we get a weird state of the app #10662

**Comment by Doctor-Scott** [comment]
This has now started working for us in new teams. Now correctly redirecting with no error message

**Comment by Prasad-MSFT** [comment]
Hi @manuelsidler , @jdominguez81 , @shootex20 - Could you please let us know whether the issue still persists at your end?

**Comment by manuelsidler** [comment]
> Also please make sure you are using the correct app id. Following are the different app IDs that are used for deep links:
> 
> **Side loaded apps:** Manifest ID **Apps submitted to org catalog:** Org catalog ID **Apps submitted to Teams app store:** Store ID

Is that still the case or can we use the manifest id for org catalog and store as well?

**Comment by Prasad-MSFT** [comment]
> > Also please make sure you are using the correct app id. Following are the different app IDs that are used for deep links:
> > **Side loaded apps:** Manifest ID **Apps submitted to org catalog:** Org catalog ID **Apps submitted to Teams app store:** Store ID
> 
> Is that still the case or can we use the manifest id for org catalog and store as well?

The documentation suggests that we should use `Org catalog ID` for Apps submitted to org catalog and `Store ID` for Apps submitted to Teams app store

**Comment by shootex20** [comment]
> Hi @manuelsidler , @jdominguez81 , @shootex20 - Could you please let us know whether the issue still persists at your end?

This seems to be working for me, thank you

**Comment by jdominguez81** [comment]
Now it seem to be working fine for us too.

**Comment by Jocelynncanzoneri** [comment]
I have an over load of messages and email that serve no purpose filling up
my storage accounts.
Do you see?

My purpose is working.  What is yalls out of being team?  One,,  I have not
benifited or made money.  Two, my access has to send doesn't work.  And
three,  my storage is full.

Can you tell me how we work ?
