### ISSUE TITLE
Glossary: "Connector for Microsoft 365 Groups" should be in 'C' section (not 'O')

### ISSUE THREAD

**Issue by erikadoyle** [MicrosoftDocs/msteams-docs#9471]
https://learn.microsoft.com/en-us/microsoftteams/platform/get-started/glossary#o

**Comment by Nivedipa-MSFT** [comment]
@surbhigupta12 - Can you please here in adding 'Connector for Microsoft 365 Groups' to the 'C' section of the Glossary and removing it from the 'O' section?
