### ISSUE TITLE
Remove YoTeams term from glossary

### ISSUE THREAD

**Issue by jeroen-ms** [MicrosoftDocs/msteams-docs#9476]
Please remove **YoTeam** term from glossary. It is unused and not found in the rest of the docs.

Searching for **YoTeams** in docs only finds the one glossary entry: https://learn.microsoft.com/en-us/search/?terms=YoTeams

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ff9690f5-fa8b-98bb-d3b4-ad4ed1030114
* Version Independent ID: ff9690f5-fa8b-98bb-d3b4-ad4ed1030114
* Content: [Microsoft Teams developer documentation- Glossary - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/get-started/glossary#y)
* Content Source: [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/get-started/glossary.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **surbhigupta**

**Comment by Meghana-MSFT** [comment]
Thank you for reporting this, we will check internally and get the doc updated.

**Comment by Meghana-MSFT** [comment]
The same issue is being tracked here - https://github.com/MicrosoftDocs/msteams-docs/issues/9477. Hence closing this issue, please follow the above issue for further updates. Thank you.
