### ISSUE TITLE
ValidDomains applies to more than just Teams client.

### ISSUE THREAD

**Issue by jeroen-ms** [MicrosoftDocs/msteams-docs#9477]
Please remove **YoTeam** term from glossary. It is unused and not found in the rest of the docs.

Searching for **YoTeams** in docs only finds the one glossary entry: https://learn.microsoft.com/en-us/search/?terms=YoTeams

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ff9690f5-fa8b-98bb-d3b4-ad4ed1030114
* Version Independent ID: ff9690f5-fa8b-98bb-d3b4-ad4ed1030114
* Content: [Microsoft Teams developer documentation- Glossary - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/get-started/glossary#y)
* Content Source: [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/get-started/glossary.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **surbhigupta**

**Comment by Nivedipa-MSFT** [comment]
@jeroen-ms - Could you please help here to remove **YoTeams** from Glossary.
Content link: https://learn.microsoft.com/en-us/microsoftteams/platform/get-started/glossary#y
