### ISSUE TITLE
Valid Domains applies to more than just the Teams client

### ISSUE THREAD

**Issue by jeroen-ms** [MicrosoftDocs/msteams-docs#9478]
**Valid Domains** applies to all clients where the app manifest is used, not just the Teams client.

...A list of valid domains for websites the app expects to load within the **Teams client**... 

Please consider removing the term 'Teams' or replacing with 'supported client'

...A list of valid domains for websites the app expects to load within the **supported client**... 
...A list of valid domains for websites the app expects to load within the **client**... 

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ff9690f5-fa8b-98bb-d3b4-ad4ed1030114
* Version Independent ID: ff9690f5-fa8b-98bb-d3b4-ad4ed1030114
* Content: [Microsoft Teams developer documentation- Glossary - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/get-started/glossary#y)
* Content Source: [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/get-started/glossary.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **surbhigupta**

**Comment by Meghana-MSFT** [comment]
Thank you for reporting this, we will check internally and get the doc updated.

**Comment by Meghana-MSFT** [comment]
@surbhigupta12 - Could you please help to replace Teams client with 'supported client' in valid domains definition.

![image](https://github.com/MicrosoftDocs/msteams-docs/assets/81138249/7ada37c4-f6dc-4ee4-982d-9d504bc2133c)
