### ISSUE TITLE
Tabs should be updated to reflect they are embedded in clients outside of Teams

### ISSUE THREAD

**Issue by jeroen-ms** [MicrosoftDocs/msteams-docs#9480]
**Tabs** entry should be updated to reflect that personal tabs can be embedded in clients outside of Teams. Current definition:

Tabs are Teams-aware webpages embedded in Microsoft Teams that point to domains declared in manifest. You can add it inside a team, group chat, or personal.

Can we update the definition to reflect that tabs are available outside of Teams client:

Tabs are **client-aware** webpages embedded in Microsoft Teams, **Outlook and M365** that point to domains declared in manifest. You can add it inside a team, group chat, or personal.

Thanks!
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ff9690f5-fa8b-98bb-d3b4-ad4ed1030114
* Version Independent ID: ff9690f5-fa8b-98bb-d3b4-ad4ed1030114
* Content: [Microsoft Teams developer documentation- Glossary - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/get-started/glossary#y)
* Content Source: [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/get-started/glossary.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **surbhigupta**

**Comment by Meghana-MSFT** [comment]
Thank you for reporting this, we will check internally and get the doc updated.

**Comment by Meghana-MSFT** [comment]
@surbhigupta12 - Could you please help to update the [tab definition](https://learn.microsoft.com/en-us/microsoftteams/platform/get-started/glossary#y:~:text=Tabs%20are%20Teams%2Daware%20webpages%20embedded%20in%20Microsoft%20Teams%20that%20point%20to%20domains%20declared%20in%20manifest.%20You%20can%20add%20it%20inside%20a%20team%2C%20group%20chat%2C%20or%20personal.) to below one - 

"Tabs are client-aware webpages embedded in Microsoft Teams, Outlook and M365 that point to domains declared in manifest. You can add it inside a team, group chat, or personal."
