### ISSUE TITLE
Store Validation Guidelines - remove Teams-specific reference

### ISSUE THREAD

**Issue by jeroen-ms** [MicrosoftDocs/msteams-docs#9481]
**Store Validation Guidelines** should be updated to reflect that the guidelines are for apps that work across Teams, Outlook and M365 (they are not Teams-specific). Also be updated to not use the term in the definition (e..g remove guidelines from the definition itself) Current definition:

A set of **Teams-specific guidelines** for validating an app before it can be submitted to Teams store.

Can we update the definition to reflect that the guidelines apply to apps beyond Teams?

A set of **standards and principles** for validating an app before it can be submitted to Teams store.

Thanks!
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ff9690f5-fa8b-98bb-d3b4-ad4ed1030114
* Version Independent ID: ff9690f5-fa8b-98bb-d3b4-ad4ed1030114
* Content: [Microsoft Teams developer documentation- Glossary - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/get-started/glossary#y)
* Content Source: [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/get-started/glossary.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **surbhigupta**

**Comment by Prasad-MSFT** [comment]
Hi @surbhigupta12 - Could you please help here to update the current definition of **Store Validation Guidelines** as suggested above?
