### ISSUE TITLE
Standalone app - Clarify definition and provide example

### ISSUE THREAD

**Issue by jeroen-ms** [MicrosoftDocs/msteams-docs#9482]
For the term **Standalone app** the definition is not clear as to what this is referring to. Current definition:

A single-page or large, and complex app. The user can use some aspects of it in Teams.
See also: [Collaboration app](https://learn.microsoft.com/en-us/microsoftteams/platform/get-started/glossary#c)

Can we update the definition to clarify/answer these questions:
- Do standalone apps only exist in Teams, or do they also exist in Outlook and M365?
- Are standalone apps built by a developer, or are they provided by Microsoft? If developers build these, how are they built?
- Providing 2-3 examples may help clarify the definition without expanding too much further.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ff9690f5-fa8b-98bb-d3b4-ad4ed1030114
* Version Independent ID: ff9690f5-fa8b-98bb-d3b4-ad4ed1030114
* Content: [Microsoft Teams developer documentation- Glossary - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/get-started/glossary)
* Content Source: [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/get-started/glossary.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **surbhigupta**

**Comment by sayali-MSFT** [comment]
@jeroen-ms - Thanks for reporting your issue.
We will check this at our end and will get back to you.

**Comment by v-kushals** [comment]
Hi @jeroen-ms, can you please review and approve the https://github.com/MicrosoftDocs/msteams-docs/pull/10127.
