### ISSUE TITLE
Can't see any "Developer Preview" menu item.

### ISSUE THREAD

**Issue by pcolby** [MicrosoftDocs/msteams-docs#951]
Following the steps for the **web client**, I've done steps 1 and 2, that is, I can side load apps now.  However, when I try step 3, there is no "Developer preview" option under the About menu.

![screen-2019-09-16-10-49-54](https://user-images.githubusercontent.com/5195222/64930021-fda61400-d86f-11e9-9c41-2234fd6f35c1.png)

Is there a step missing, or the developer preview option moved to somewhere else?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 008da4e2-979e-c396-db28-4acf57deb530
* Version Independent ID: f1413f77-5eb3-e1fd-9235-d322d6e4eb6c
* Content: [Developer Preview - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/dev-preview/developer-preview-intro)
* Content Source: [msteams-platform/resources/dev-preview/developer-preview-intro.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/resources/dev-preview/developer-preview-intro.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Gousia-MSFT** [comment]
@pcolby Could you please check if [sideloading is enabled](https://docs.microsoft.com/en-us/microsoftteams/platform/get-started/get-started-tenant) for your tenant?

**Comment by pcolby** [comment]
Hi @Gousia-MSFT, yes, as mentioned in OP, I have sideloading enabled:

![image](https://user-images.githubusercontent.com/5195222/64936065-72d90f80-d897-11e9-9cfe-ca43dfdd6293.png)

![image](https://user-images.githubusercontent.com/5195222/64936006-36a5af00-d897-11e9-920f-43b162bc568f.png)

![image](https://user-images.githubusercontent.com/5195222/64936034-550baa80-d897-11e9-9e55-dd0e802962eb.png)

I already have installed at least one custom app by sideloading, eg this link works as expected:

![image](https://user-images.githubusercontent.com/5195222/64936138-d82d0080-d897-11e9-9d41-30643c174b11.png)

Thanks.

(BTW, is the page you linked is out of date - see https://github.com/MicrosoftDocs/msteams-docs/issues/898).

**Comment by hwangzhiming** [comment]
Any updates? I need this to debug my custom app, I updated a app and it works perfectly in the Teams web client, but the desktop client can not load the UI.

**Comment by Gousia-MSFT** [comment]
@hwangzhiming We have raised a bug for this and we are tracking it internally.

**Comment by pcolby** [comment]
@Gousia-MSFT, why close this? Is the bug resolved?

**Comment by innovationhub-asia** [comment]
We are seeing the same issue, followed all required steps but the Development preview option is not available, even though we are able to upload custom apps.

**Comment by hwangzhiming** [comment]
Try quit and reopen your Team client, it came back unexpectedly/

![dev](https://user-images.githubusercontent.com/1012374/66447018-5c316d00-ea7f-11e9-96e3-a7c535390bfd.png)

**Comment by Gousia-MSFT** [comment]
@pcolby @innovationhub-asia This has been fixed now. Could you please check and confirm once?

**Comment by pcolby** [comment]
Hi @Gousia-MSFT, yes, the menu option is there now, thanks! :)

**Comment by jfranch** [comment]
Hi @Gousia-MSFT, don't work for me. Developer preview option is missing.

**Comment by jfranch** [comment]
@Gousia-MSFT it's ok for 32bits version, but don't work on 64bit.

**Comment by pkostelnik** [comment]
On my tenant even as on my customer there is no ponit for developer mode(s). Independent of the clientarchitecture (x86/x64) and yes, sideloading is enabled OrgWide, on Team and even for (specific)User.
So please reopen and clarify a solution.
