### ISSUE TITLE
Add a C# code sample link in the Adaptive Card-based Loop Components document

### ISSUE THREAD

**Issue by Harikrishnan-MSFT** [MicrosoftDocs/msteams-docs#9511]
Hi Teams,

We have done the C# sample implementation. Could you please add the link in the Adaptive Card-based Loop Components document?

**[C# sample link]( https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/msgext-unfurling-ac-loop-components/csharp)**

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a614d296-7303-d8b1-4b1a-af422a244dc8
* Version Independent ID: a614d296-7303-d8b1-4b1a-af422a244dc8
* Content: [Build Adaptive Card-based Loop component - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/m365-apps/cards-loop-component?branch=pr-en-us-9230)
* Content Source: [msteams-platform/m365-apps/cards-loop-component.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/m365-apps/cards-loop-component.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **surbhigupta**

**Comment by Nivedipa-MSFT** [comment]
@surbhigupta12 - Could you please help here to add the below sample link in document?
[C# sample link](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/msgext-unfurling-ac-loop-components/csharp)
