### ISSUE TITLE
notification is not coming up

### ISSUE THREAD

**Issue by nikez-az** [MicrosoftDocs/msteams-docs#9513]
[Enter feedback here]
Post F5 issuing curl but notification is not getting displayed, all other steps are completed. Update needful debug steps. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 304a8eff-597c-cf72-c49f-f3938021d4aa
* Version Independent ID: 304a8eff-597c-cf72-c49f-f3938021d4aa
* Content: [Build notification bot - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/get-started/build-notification-bot?tabs=teamstoolkitcodespaces)
* Content Source: [msteams-platform/get-started/build-notification-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/get-started/build-notification-bot.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **surbhigupta**

**Comment by Prasad-MSFT** [comment]
@niketanjain-azilen - Could you please provide more details on your issue along with proper repro steps and the exact error/issue details?

**Comment by Prasad-MSFT** [comment]
@niketanjain-azilen - We tried to repro this issue and were also observing the same behaviour. Post F5 issuing curl, but notifications are not getting sent in MS Teams app.
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/62237649/90049179-ffb3-49a1-9cd0-9533b9788d81)

**Comment by niketanjain-azilen** [comment]
Thanks for looking into it. Looks like the end issue is resolved for me, while curl being same.

On 22-Sep-2023 14:08, Prasad-MSFT ***@***.***> wrote:

@niketanjain-azilen<https://github.com/niketanjain-azilen> - We tried to repro this issue and were also observing the same behaviour. Post F5 issuing curl, but notifications are not getting sent in MS Teams app.
[image]<https://user-images.githubusercontent.com/62237649/269881880-90049179-ffb3-49a1-9cd0-9533b9788d81.png>

**Comment by Prasad-MSFT** [comment]
@nikez-az - Could you please let us know whether this issue still exists for you or not?
