### ISSUE TITLE
Can't create new app in App Studio

### ISSUE THREAD

**Issue by treyco** [MicrosoftDocs/msteams-docs#952]
Whenever I go and create a new app from scratch, I get the error "Failed to create app." I've seen some of the issues raised here before but I don't know how they were fixed.

**Comment by Gousia-MSFT** [comment]
@treyco Are you getting the error when you try to install the app? Can you please share a screenshot for a better understanding?

**Comment by treyco** [comment]
This is the error I get when I create a new app.

![image](https://user-images.githubusercontent.com/8473380/64939895-0826d480-d895-11e9-8a20-ec24e4e4f8a6.png)

**Comment by Gousia-MSFT** [comment]
@treyco  Thanks for sharing the screenshot. We are looking into it.

**Comment by Gousia-MSFT** [comment]
Duplicate of [#955](https://github.com/MicrosoftDocs/msteams-docs/issues/955). Please refer this issue for the solution.

**Comment by Gousia-MSFT** [comment]
Please re-open if you still face an issue.
