### ISSUE TITLE
Downloaded zip not working

### ISSUE THREAD

**Issue by Prasad-MSFT** [MicrosoftDocs/msteams-docs#9523]
In [this](https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/tabs-in-sharepoint#test-the-sample-app) section, its mentioned to download the sample app manifest and upload the app in Teams. However, while uploading the app it gives below error:
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/62237649/cbb64d49-38f1-431b-a6b5-6db63aa623f7)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 41c93c1e-c426-148c-a545-f8bd5b3763ff
* Version Independent ID: afcc83c4-12c0-bab6-1cec-61ac463b4f60
* Content: [Add Teams tab to SharePoint - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/tabs-in-sharepoint)
* Content Source: [msteams-platform/tabs/how-to/tabs-in-sharepoint.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/tabs/how-to/tabs-in-sharepoint.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **surbhigupta**

**Comment by Prasad-MSFT** [comment]
Hi @surbhigupta12 - Could you please help here updating the correct zip package?

**Comment by v-preethah** [comment]
This issue is being tracked via [Pull Request #10317](https://github.com/MicrosoftDocs/msteams-docs/pull/10317)
