### ISSUE TITLE
User profile picture not rendered in adaptive card on Teams client app

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#9529]
Copied bug from: https://github.com/microsoft/AdaptiveCards/issues/8687 

**Details from original post:**
### Target Platforms

Other

### SDK Version

Adaptive Cards 1.3

### Application Name

Microsoft Teams

### Problem Description

When adding the user profile picture with url "/_layouts/15/userphoto.aspx" to an adaptive card, it renders in Teams via browser but not in the client app, which returns a 401 Unauthorised.

URL for the image: https://TENANT.sharepoint.com/_layouts/15/userphoto.aspx?size=S&accountname=USER_EMAIL@TENANT.onmicrosoft.com

### Screenshots

Teams in browser:
![Screenshot 2023-09-22 154948](https://github.com/microsoft/AdaptiveCards/assets/7807026/a07490a5-052e-44a1-bf8c-257eb066a6cd)
Teams app:
![Screenshot 2023-09-22 154959](https://github.com/microsoft/AdaptiveCards/assets/7807026/ef0e436c-ff28-46d4-b3f1-1880e5692af0)

### Card JSON

```JSON
{
      "type": "AdaptiveCard",
      "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
      "version": "1.3",
      "body": [
        {
          "type": "Container",
          "items": [
            {
              "type": "ColumnSet",
              "spacing": "extraLarge",
              "columns": [
                {
                  "type": "Column",
                  "width": "36px",
                  "items": [
                    {
                      "type": "Image",
                      "url": "https://TENANT.sharepoint.com/_layouts/15/userphoto.aspx?size=S&accountname=USER_EMAIL@TENANT.onmicrosoft.com",
                      "width": "36px",
                      "style": "person"
                    }
                  ]
                }
              ]
            }
          ]
        }
      ]
    }
```

### Sample Code

_No response_---
#### Document Details

⚠ *Do not edit this section.It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Cards reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **surbhigupta12**

**Comment by Meghana-MSFT** [comment]
We will check this at our end, and it is rendering fine on both Teams Web and Teams desktop. 

Could you please try with this URL once and let us know if you the same issue - https://connectorsdemo.azurewebsites.net/images/MSC12_Oscar_002.jpg?

![image](https://github.com/MicrosoftDocs/msteams-docs/assets/81138249/0603e07e-e15d-4e8e-b77e-ab1930da02ab)

**Comment by z3019494** [comment]
This is still the case on my end in Teams 2.1

**Comment by Meghana-MSFT** [comment]
@z3019494 - Could you please let us know if you are facing the issue with the URL I shared in above comment? 

> Could you please try with this URL once and let us know if you the same issue - https://connectorsdemo.azurewebsites.net/images/MSC12_Oscar_002.jpg?

**Comment by Ismael-Cruz** [comment]
I opened this issue in another section and it was moved here. This issue happens when using URLs from SharePoint, like the profile picture (userphoto.aspx), I've seen it as well with images from the SiteAssets library. If you use a picture hosted in any public CDN it will work.

The picture appears in Teams browser only because of cached content, once refreshing clearing cache the image does not appear. There must be something when trying to access the image in SharePoint being in Teams context.

If it helps for anyone having this issue, as a workaround we download the image in base64 dynamically and send it in our adaptive card using the hostedContents property.

**Comment by Meghana-MSFT** [comment]
As you rightly said, when you try to load an image within Adaptive Card using sharepoint url in the browser, the user has a signed-in session to SharePoint, but perhaps that's not respected in the Teams client. 

Please note that the URL should be a public image link.
