### ISSUE TITLE
No underline on links

### ISSUE THREAD

**Issue by jkshapiro** [MicrosoftDocs/msteams-docs#953]
Steps to reproduce, in the Teams desktop app on Windows 10:
1. Type some text in Teams, e.g. in Conversations or Wiki
2. Highlight the text and press Ctrl-K. The "Insert link" dialog comes up.
3. Enter a URL in the "Address" field and click "Insert".

Expected: The text is turned into a clearly visible URL, with the standard blue colour and underline.

Observed: The text is turned into a URL and marked with a dark, desaturated blue colour and no underline.

**Comment by Gousia-MSFT** [comment]
@jkshapiro Thanks for reaching out!! We are looking into this.

**Comment by Gousia-MSFT** [comment]
@jkshapiro We have raised a bug for this which is being tracked internally. Thanks!!
