### ISSUE TITLE
This page gives a warning that it only applies to TTK v4 but doesn't give a link to the v5 version of the page

### ISSUE THREAD

**Issue by AE-MS** [MicrosoftDocs/msteams-docs#9530]
This page says:

_Teams Toolkit v4 extension will soon be deprecated._

_This article is applicable only to Teams Toolkit version 4._

But there's no obvious way to find the corresponding article that applies to TTK v5.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cb9d921a-a779-86b6-5647-8b95bcf649f2
* Version Independent ID: cb9d921a-a779-86b6-5647-8b95bcf649f2
* Content: [Add Capabilities of Teams Toolkit to Your Teams apps - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/toolkit/toolkit-v4/add-capability-v4)
* Content Source: [msteams-platform/toolkit/toolkit-v4/add-capability-v4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/toolkit-v4/add-capability-v4.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **surbhigupta**

**Comment by ChetanSharma-msft** [comment]
Hello @AE-MS - We have also raised a similar issue: https://github.com/MicrosoftDocs/msteams-docs/issues/9535

We will check internally and redirect to doc team accordingly.

**Comment by ChetanSharma-msft** [comment]
Doc is updated as a part of this issue: https://github.com/MicrosoftDocs/msteams-docs/issues/9535
We are closing this issue for now, please feel free to reopen it, if required.
