### ISSUE TITLE
Wrong redirection link added for "Sideload permission"

### ISSUE THREAD

**Issue by ChetanSharma-msft** [MicrosoftDocs/msteams-docs#9533]
Below highlighted hyperlink is wrong:
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/59052547/80ad7642-92b9-4cd8-8b68-bc850b639fe8)

Please update the link as below section:
https://learn.microsoft.com/en-us/microsoftteams/platform/toolkit/tools-prerequisites#verify-sideloading-permission

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 657f1dc5-5346-f4cd-f788-004bd7369468
* Version Independent ID: 657f1dc5-5346-f4cd-f788-004bd7369468
* Content: [Prerequisites for creating your Teams app using Visual Studio Code - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/toolkit/tools-prerequisites)
* Content Source: [msteams-platform/toolkit/tools-prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/tools-prerequisites.md)
* Service: **msteams**
* GitHub Login: @zyxiaoyuer
* Microsoft Alias: **surbhigupta**

**Comment by Nivedipa-MSFT** [comment]
@surbhigupta12 - Could you please help here to update the link in given document.
