### ISSUE TITLE
Directory Structure files mentioned in the doc are not available in project folder.

### ISSUE THREAD

**Issue by ChetanSharma-msft** [MicrosoftDocs/msteams-docs#9534]
Below highlighted files are not present in the folder path once we create a new project as mentioned in the documentation:
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/59052547/344812da-4b73-4368-a6f3-d0f108daa244)

https://learn.microsoft.com/en-us/microsoftteams/platform/toolkit/create-new-project?pivots=visual-studio-code-v5#directory-structure-for-different-app-types

Tried below steps to create a new project:
https://learn.microsoft.com/en-us/microsoftteams/platform/toolkit/create-new-project?pivots=visual-studio-code-v5#create-a-new-teams-app-1

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 13410ab8-6255-e478-9a1d-4b3b348f1d16
* Version Independent ID: 13410ab8-6255-e478-9a1d-4b3b348f1d16
* Content: [Create a new Teams app - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/toolkit/create-new-project?pivots=visual-studio-code-v5)
* Content Source: [msteams-platform/toolkit/create-new-project.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/create-new-project.md)
* Service: **msteams**
* GitHub Login: @zyxiaoyuer
* Microsoft Alias: **surbhigupta**

**Comment by sayali-MSFT** [comment]
@surbhigupta12 -Could you please help us to update the document?
