### ISSUE TITLE
Steps looks wrong for "To add cloud resources by using Command Palette"

### ISSUE THREAD

**Issue by ChetanSharma-msft** [MicrosoftDocs/msteams-docs#9536]
Steps to add cloud resources using command palette looks wrong and mentioned same as "To add cloud resources by using Teams Toolkit in Microsoft Visual Studio Code" 

Steps looks wrong here:
https://learn.microsoft.com/en-us/microsoftteams/platform/toolkit/add-resource#to-add-cloud-resources-by-using-command-palette

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 866a395a-7512-e595-07ac-64d229db8e9f
* Version Independent ID: 866a395a-7512-e595-07ac-64d229db8e9f
* Content: [Add Resources to Teams apps - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/toolkit/add-resource#to-add-cloud-resources-by-using-command-palette)
* Content Source: [msteams-platform/toolkit/add-resource.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/add-resource.md)
* Service: **msteams**
* GitHub Login: @MuyangAmigo
* Microsoft Alias: **zhany**

**Comment by Nivedipa-MSFT** [comment]
@surbhigupta12 - Could you please help here to update the document.
