### ISSUE TITLE
test

### ISSUE THREAD

**Issue by Nihaan512** [MicrosoftDocs/msteams-docs#9540]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7871c074-0ad6-a802-53d7-0e8da1d2b503
* Version Independent ID: 7871c074-0ad6-a802-53d7-0e8da1d2b503
* Content: [Build your basic tab app - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/get-started/build-basic-tab-app?tabs=teamstoolkitcodespaces)
* Content Source: [msteams-platform/get-started/build-basic-tab-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/get-started/build-basic-tab-app.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **surbhigupta**

**Comment by ChetanSharma-msft** [comment]
Invalid issue. Closing it.
