### ISSUE TITLE
Outgoing Webhook not visible Reopen #534 

### ISSUE THREAD

**Issue by Linreg-gmx-net** [MicrosoftDocs/msteams-docs#956]
Hello,
In Teams , there is a option for Incoming Web hook, but there is no option to configure Outgoing Webhook. 

I mean the option to create outgoing webhooks as described in the documentation isn't there!
I use german locale. 
![Screenshot_20190917_150514](https://user-images.githubusercontent.com/7877755/65044394-1a6c4580-d95d-11e9-9ad2-9566221d2bac.png)

**Comment by Trinetra-MSFT** [comment]
@Linreg-gmx-net, Could you please confirm if [sideloading ](https://docs.microsoft.com/en-us/MicrosoftTeams/teams-app-permission-policies#can-i-use-app-permission-policies-to-restrict-uploading-custom-apps-also-known-as-sideloading)is enabled in your tenant?
![image](https://user-images.githubusercontent.com/50989436/65117213-56f47b80-da07-11e9-9768-5d9466f38f1e.png)

**Comment by Linreg-gmx-net** [comment]
Am Mittwoch, 18. September 2019, 08:00:37 CEST schrieb Trinetra-
MSFT:
> @Linreg-gmx-net, Could you please confirm if sideloading is enabled
in your tenant?

Hello,

thats is it. Sideloading is now enabled. I can now see that option.

Thank you.

**Comment by Trinetra-MSFT** [comment]
@Linreg-gmx-net, Thanks for confirming. FYI, This issue is resolved so closing it.
