### ISSUE TITLE
Deep Links cause Splash Screen for each use asking user to download teams or continue in the browser.

### ISSUE THREAD

**Issue by Orta373** [MicrosoftDocs/msteams-docs#9564]
The issue with the deep links are that when you use them from another webpage or past the deep link directly into the browser, Teams.microsoft.com will open up but it stops the user at the "Splash Screen" that forces the user to select if they want to stay in the browser or download teams to their device.  

Support says this is by design and the behavior cannot be changed, but this does not make sense as once a user has logged into teams.microsoft.com for the first time and selected to stay in the web browser, the user does not get that 'Splash Screen' on each subsequent login.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b6687ceb-6d67-b0b7-0797-b16d14e4bd97
* Version Independent ID: b6687ceb-6d67-b0b7-0797-b16d14e4bd97
* Content: [Deep link to a Teams chat - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-link-teams)
* Content Source: [msteams-platform/concepts/build-and-test/deep-link-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/build-and-test/deep-link-teams.md)
* Service: **msteams**
* GitHub Login: @v-npaladugu
* Microsoft Alias: **surbhigupta**

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, please feel free to reopen it, if required.
