### ISSUE TITLE
Linux or Windows?

### ISSUE THREAD

**Issue by alexespencer** [MicrosoftDocs/msteams-docs#957]
After clicked "new" and entering a globally unique name, I do not get asked which version on Node.JS I want to run, instead I am asked "Linux" or "Windows"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c08b13b0-8c05-c6f1-c3fa-a58b67ae0123
* Version Independent ID: 14116a6d-f66b-a81b-9808-cf6db771325f
* Content: [Host your Node based Teams app in Azure - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/get-started/get-started-nodejs-in-azure)
* Content Source: [msteams-platform/get-started/get-started-nodejs-in-azure.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/get-started/get-started-nodejs-in-azure.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Gousia-MSFT** [comment]
@alexespencer Could you please share a screenshot of the issue you are facing?

**Comment by Gousia-MSFT** [comment]
Please re-open with screenshot if you are still facing an issue.
