### ISSUE TITLE
What types of cards are supported in connectors?

### ISSUE THREAD

**Issue by xantari** [MicrosoftDocs/msteams-docs#958]
The example here shows MessageCards are a valid type. What about adaptive cards?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0fd8e4d-f110-36f8-5bd3-db3325b14c01
* Version Independent ID: 717ea854-1d3a-2c15-e495-b6f170fe7aff
* Content: [Using Office 365 Connectors - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/connectors/connectors-using#feedback)
* Content Source: [msteams-platform/concepts/connectors/connectors-using.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/connectors/connectors-using.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Gousia-MSFT** [comment]
@xantari Please check this [document ](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/cards/cards)to see the cards supported. Adaptive cards are not supported in connectors.

**Comment by xantari** [comment]
Thanks, really hope adaptive cards will be supported soon. It appears only "legacy" MessageCard type is supported :(
