### ISSUE TITLE
Safari and Firefox anonymous user support 

### ISSUE THREAD

**Issue by Hans-Zietsman** [MicrosoftDocs/msteams-docs#9585]
Currently, if an anonymous user joins on Safari or Firefox browser, meeting apps are still not supported.  Can we please send those users a more accurate and useful error message advising them to use a supported browser?

![image (2)](https://github.com/MicrosoftDocs/msteams-docs/assets/146948876/dd290823-5b88-4232-a9d8-e0032a7da570)

Any updates on when Safari and Firefox will be supported

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2c5bc94a-3c95-aecc-a34d-d9771dc5e9bb
* Version Independent ID: 2c5bc94a-3c95-aecc-a34d-d9771dc5e9bb
* Content: [Build apps for anonymous user - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/build-apps-for-anonymous-user?tabs=javascript)
* Content Source: [msteams-platform/apps-in-teams-meetings/build-apps-for-anonymous-user.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/apps-in-teams-meetings/build-apps-for-anonymous-user.md)
* Service: **msteams**
* GitHub Login: @v-sdhakshina
* Microsoft Alias: **v-sdhakshina**

**Comment by Prasad-MSFT** [comment]
Thanks for raising this. We will check this with engineering team and will update you accordingly.

**Comment by Hans-Zietsman** [comment]
Hi

Any updates on When firefox and Safari will be supported?

From: microsoft-github-policy-service[bot] ***@***.***>
Date: Wednesday, 04 October 2023 at 14:19
To: MicrosoftDocs/msteams-docs ***@***.***>
Cc: Hans Zietsman ***@***.***>, Author ***@***.***>
Subject: Re: [MicrosoftDocs/msteams-docs] Safari and Firefox anonymous user support (Issue #9585)

Hi Hans-Zietsman! Thank you for bringing this issue to our attention. We will investigate and if we require further information we will reach out in one business day. Please use this link<https://aka.ms/DevCommunityEscalationForm> to escalate if you don't get replies.

Best regards, Teams Platform

**Comment by Prasad-MSFT** [comment]
@Hans-Zietsman - Apologies. Currently we do not have any update to share. We are following up with engineering team, once we have any update, will share over this thread.
Thanks!
