### ISSUE TITLE
Could not save the new tab

### ISSUE THREAD

**Issue by lre871** [MicrosoftDocs/msteams-docs#959]
I have followed all the steps of this page but at step "Configure the app tab" I had installed the app and if I klick on the "+" to add the new tab the save button is disabled. I have developed a few test apps for teams with tabs, too, and there also the save button is disabled. I have checked all configurations in the admin center and there is no error at the pop up or in the console, but the save button is not enabled and so i could not klick it. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33cdb816-f2b6-31a4-0e4c-d730435d0a6b
* Version Independent ID: c111eaef-ac66-e245-b2bc-623c1801a7db
* Content: [Get started with App Studio and Node.js - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/get-started/get-started-nodejs-app-studio#feedback)
* Content Source: [msteams-platform/get-started/get-started-nodejs-app-studio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/get-started/get-started-nodejs-app-studio.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Trinetra-MSFT** [comment]
Could you please check `microsoftTeams.settings.setValidityState(true)` is set to enable the save button and `websiteUrl`, `contentUrl`, `removeUrl `is added in validDomains List in your app manifest?  Please take a look at documentation for [Configuration page](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/tabs/tabs-configuration#configuration-page-example) example.

**Comment by lre871** [comment]
Thanks for your answer. I have changed the microsoftTeams.settings.setValidityState(true), it was set to another value. But could you tell me where to find the three urls? I took a look at the Configuration page but this does not help me, because there are two objects but i have to give an array of urls as strings and i dont know where to find them.

**Comment by Trinetra-MSFT** [comment]
What appears in a tab on desktop/web is defined by the value of `contentUrl`: Teams displays the contents of `contentUrl `in the tab. ([See Determine the content to display in the tab](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/tabs/tabs-configuration#determine-the-content-to-display-in-the-tab)). If the tab has a value for `websiteUrl`, another icon appears with the others at the upper right of the tab: Go to website. When the user clicks on this icon, `websiteUrl `is opened in a new browser tab. The optional `removeUrl `parameter sets the URL for your [removal options page](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/tabs/tabs-update-remove#removing-a-tab).

You can configure these URL inside` microsoftTeams.settings.setSettings`.
```
 microsoftTeams.settings.setSettings({
         entityId: "google",
         contentUrl: "https://www.google.com/maps/embed",
         suggestedDisplayName: "Google Map",
         websiteUrl: "https://www.google.com/maps",
         removeUrl: "https://teams-get-started-sample.azurewebsites.net/tabremove.html",
      });
```

**Comment by Gousia-MSFT** [comment]
@lre871 Please re-open if you are still facing an issue.
