### ISSUE TITLE
Docs refer to "acv2" doesn't explain what that is

### ISSUE THREAD

**Issue by andrewconnell** [MicrosoftDocs/msteams-docs#9590]
Searching the MSFT docs & Google for "acv2" doesn't answer what this is.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 59bbff2e-4b80-f980-2ade-7c7a7950801e
* Version Independent ID: e837e1fd-ec0c-2d6f-b0db-b76cb2d268a4
* Content: [Link unfurling - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?tabs=desktop%2Cjavascript%2Climitations#zero-install-for-link-unfurling)
* Content Source: [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/messaging-extensions/how-to/link-unfurling.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **v-ypalikila**

**Comment by Nivedipa-MSFT** [comment]
@andrewconnell - Thanks for reporting your issue. We will check this and update you soon.

**Comment by Wajeed-msft** [comment]
@surbhigupta12 - could you please help to replace acv2 with [Adaptive Cards with Universal Actions](https://learn.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview)?
