### ISSUE TITLE
Limitations section contains dupes & contradictions

### ISSUE THREAD

**Issue by andrewconnell** [MicrosoftDocs/msteams-docs#9591]
In the section [Enable zero install link unfurling](https://learn.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?tabs=desktop%2Cjavascript%2Climitations#enable-zero-install-link-unfurling), at the end, the **limitations** section is confusing.

- the 3rd & 5th bullet points are dupes of each other
- the term `acv2` is mentioned twice, but never defined see #9590 
- the 1st bullet says "The bot can only send back a response as `result` or `auth` as the value for the `type` property in response to the composeExtensions/anonymousQueryLink invoke request", but 3rd bullet says the bot can elect to respond with `type=auth`... which is is?

Also, no examples of how to handle / implement the scenarios where bot responds with `type=auth`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 59bbff2e-4b80-f980-2ade-7c7a7950801e
* Version Independent ID: e837e1fd-ec0c-2d6f-b0db-b76cb2d268a4
* Content: [Link unfurling - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?tabs=desktop%2Cjavascript%2Climitations#zero-install-for-link-unfurling)
* Content Source: [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/messaging-extensions/how-to/link-unfurling.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **v-ypalikila**

**Comment by sayali-MSFT** [comment]
@andrewconnell - Thanks for reporting your issue.
We will check this at our end and will get back to you.

**Comment by sayali-MSFT** [comment]
@surbhigupta12 -Could you please help us for update the document-
In 5 steps Advantages and limitations: - Limitation section please remove 4 & 5 Bullet points as it is duplicate.

**Document Link**-https://learn.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?tabs=desktop%2Cjavascript%2Climitations#enable-zero-install-link-unfurling

![Screenshot 2023-10-05 171047](https://github.com/MicrosoftDocs/msteams-docs/assets/93527375/2e2b88c5-abe8-4fbf-a396-176af48d2b9d)

**Comment by andrewconnell** [comment]
@sayali-MSFT & @surbhigupta12 As you can see above, submitted PR to fix this as it seems like that's been confirmed.

But, this PR only addresses the 1st bullet in my OP... not the other two.

**Comment by sayali-MSFT** [comment]
@andrewconnell -For other points, we will check with the internal team and update the document accordingly.
