### ISSUE TITLE
Message getting wiped out in teams

### ISSUE THREAD

**Issue by chouav10** [MicrosoftDocs/msteams-docs#960]
This bug is related to teams chatting window. While chatting with someone if you are fast in typing you may face this issue. This is how the issue happens.
Type something in chat window. Hit Enter.
As soon as you hit enter you quickly start typing the next chat and you will see the message getting wiped out.

**Comment by Gousia-MSFT** [comment]
@chouav10 Could you please share a screenshot of the issue for our better understanding?

**Comment by Gousia-MSFT** [comment]
Please re-open with screenshot if you are still facing an issue.
