### ISSUE TITLE
Anonymous user joins meeting after content has been shared to stage bug

### ISSUE THREAD

**Issue by Hans-Zietsman** [MicrosoftDocs/msteams-docs#9601]
When an anonymous user joins a meeting where a meeting app has already been shared to stage (e.g. a latecomer), that anonymous user receives an error message "Can't show this content, something went wrong". 

The presenter has to re-share the app to stage for the late anonymous user to view the content. This is disruptive for all the rest of the attendees as the stage content has to reload for all. See screenshot:
![CleanShot 2023-10-05 at 09 58 47@2x](https://github.com/MicrosoftDocs/msteams-docs/assets/146948876/85a73971-8a02-4043-881a-f954e649d799)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2c5bc94a-3c95-aecc-a34d-d9771dc5e9bb
* Version Independent ID: 2c5bc94a-3c95-aecc-a34d-d9771dc5e9bb
* Content: [Build apps for anonymous user - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/build-apps-for-anonymous-user?tabs=javascript)
* Content Source: [msteams-platform/apps-in-teams-meetings/build-apps-for-anonymous-user.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/apps-in-teams-meetings/build-apps-for-anonymous-user.md)
* Service: **msteams**
* GitHub Login: @v-sdhakshina
* Microsoft Alias: **v-sdhakshina**

**Comment by Prasad-MSFT** [comment]
Hi @Hans-Zietsman - The issues seem to be fixed. Please do verify. 
Thanks!

**Comment by Hans-Zietsman** [comment]
Hi @Prasad-MSFT 

Yes, thanks, it did work in my test now
