### ISSUE TITLE
no user status bubbles now when addressing an email in Outlook with the new teams

### ISSUE THREAD

**Issue by ITKLisa** [MicrosoftDocs/msteams-docs#9614]
[New Teams for user Alisa Nishimoto.docx](https://github.com/MicrosoftDocs/msteams-docs/files/12824935/New.Teams.for.user.Alisa.Nishimoto.docx)
I've attached the issue this user has encountered in the new teams.  From no notices of new messages coming in or phone calls but that has now been resolved with the newer updates.  But this issue attached is what she is seeing.  I do not have this issue.

Thanks,

Lisa

**Comment by Nivedipa-MSFT** [comment]
@ITKLisa - Thanks for reporting your issue. We will check this and update you soon.

**Comment by ChetanSharma-msft** [comment]
We are mainly responsible for Microsoft Teams app development related issues. 

For Microsoft Teams product issues/failures your tenant Admin can reach out to [Microsoft 365 Product Support](https://docs.microsoft.com/en-us/microsoft-365/admin/contact-support-for-business-products?view=o365-worldwide&tabs=online). 

For general questions about Microsoft Teams please post your question on [Microsoft Teams Community](https://answers.microsoft.com/en-us/msteams/forum).

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, please feel free to reopen it, if required.
