### ISSUE TITLE
Tabs not visible in new teams

### ISSUE THREAD

**Issue by sschoeb** [MicrosoftDocs/msteams-docs#9630]
We have an app which has multiple tabs:
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/2493698/b1e106de-f6a5-457e-9d37-6b739c81dd91)

In the new teams, the same app does not show any tabs:
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/2493698/211b7707-c821-4078-9bd7-4ca212e6817a)

This is only the case when opening the contact in the "chat". Seems to work fine when opening the from the sidebar. 

This looks like a serious bug to me. Is there anything we have to update to show the tabs in the new teams?

**Comment by Meghana-MSFT** [comment]
@sschoeb - Currently personal tabs are not added to 1:1 bot chat in new Teams, this is considered as a feature request. Please note that the tabs are available in the personal app view which is the main entry point for app interactions. 
Currently it is suggested to access the tabs from Apps menu or from the ... menu in the navigation rail. 

Similar issue - https://stackoverflow.com/questions/77039493/how-to-enable-support-for-teams-apps-with-static-tabs-in-the-new-teams-desktop

**Comment by DKlaper** [comment]
I noticed the same thing. The main problem is that it is very confusing for the user as he might still have it open from the previous time he used it which might be either from the personal app or the chat window. So unless you know about it it is very unintuitive. So I guess this is my upvote for this feature request.

**Comment by sschoeb** [comment]
@Meghana-MSFT As also mentioned by @DKlaper, this is a breaking change from the old teams to the new one which is very confusign for the user and has a strong impact on app-developers!

Tabs are an essential part of an app which do support the user to have a better oveall understanding when having a conversation with a Bot. Very often it is not the best option to present something within the conversation, in this case a user needs fast access to the tabs. With this change you added at least 2 additional clicks for the user which is definitely a UX-degradation. 

Additionally most of the user do not properly understand what the difference should be between opening a Bot "as an app" or "from the chat".. this is just confusing. We (and obviously others as seenin the SO-post...) would be very happy if you would reconsider this decision!

**Comment by Meghana-MSFT** [comment]
@sschoeb - This option will be added in new Teams as well. However, we do not have any ETA as of now.

**Comment by Wajeed-msft** [comment]
FYI - To help other developers facing similar issue, we have documented this in [known issues](https://learn.microsoft.com/en-us/microsoftteams/platform/resources/teams-updates#known-issues) section. 
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/31851992/2c7bdda2-7d82-4c9b-9088-a7b2b8d9a4c3)

**Comment by ChetanSharma-msft** [comment]
Hello @sschoeb - This issue is fixed and released.
Kindly verify and let us know if you are still facing this issue.

**Comment by sschoeb** [comment]
@ChetanSharma-msft I can confirm, that tabs are visible now. Thanks.
