### ISSUE TITLE
The "Request the user to provide additional configuration" link does not go to the right place

### ISSUE THREAD

**Issue by AE-MS** [MicrosoftDocs/msteams-docs#9632]
Under the "You have the following options to respond" heading, one of the options is "Request the user to provide additional configuration." However, the link for that text directs to https://learn.microsoft.com/en-us/microsoftteams/platform/get-started/first-message-extension, which appears to be invalid because it then redirects to https://learn.microsoft.com/en-us/microsoftteams/platform//sbs-gs-javascript?tabs=vscode%2Cvsc%2Cviscode, which doesn't appear to have any information about Message Extensions or ways for the user to provide additional configuration.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8fb0c2d8-f880-c260-d0be-6b9467e47f8c
* Version Independent ID: 7820ffc9-5260-c818-f5fb-672801a67d00
* Content: [Respond to the task module submit action - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/action-commands/respond-to-task-module-submit?tabs=dotnet%2Cdotnet-1)
* Content Source: [msteams-platform/messaging-extensions/how-to/action-commands/respond-to-task-module-submit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/messaging-extensions/how-to/action-commands/respond-to-task-module-submit.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **anclear**

**Comment by sayali-MSFT** [comment]
@AE-MS -Thanks for reporting your issue.
We will check this at our end and update the document accordingly.

**Comment by ChetanSharma-msft** [comment]
Hello @surbhigupta12 - Please help to update the links with relevant link..
