### ISSUE TITLE
This page does not include any information or links to application API permissions

### ISSUE THREAD

**Issue by andrewfrankcare** [MicrosoftDocs/msteams-docs#9633]
The documentation talks about delegated permissions only, and completely ignores application permissions. It should address application permissions or link to the page that does, or alternatively there should be a new page in this section that talks about application permissions.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f98a4432-cea4-c6a1-15db-d6d95c05912b
* Version Independent ID: f98a4432-cea4-c6a1-15db-d6d95c05912b
* Content: [Extend your app with Microsoft Graph permissions - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/authentication/bot-sso-graph-api)
* Content Source: [msteams-platform/bots/how-to/authentication/bot-sso-graph-api.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/bots/how-to/authentication/bot-sso-graph-api.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **surbhigupta**

**Comment by Prasad-MSFT** [comment]
@andrewfrankcare - Thanks for raising this. We will check it internally and if required, will redirect to appropriate team to update the content.

**Comment by Prasad-MSFT** [comment]
Hi @surbhigupta12 - Could you please help adding this page/ give reference link at the end of the documentation page?
https://learn.microsoft.com/en-us/azure/active-directory/develop/permissions-consent-overview

**Comment by andrewfrankcare** [comment]
Thanks for adding a link to documenting application vs. delegated permissions. That is an improvement.

I don't think my issue was worded very well. The point I was making is that this page discusses how to extend your App to acquire delegated permissions, but does not describe how to acquire application permissions. The new link simply talks about delegated vs. application permissions; however there is still no documentation about how to extend your App to acquire application permissions.
