### ISSUE TITLE
[team-js]Open Deeplink channels webUrl I need directly open in the app which did open a new tab.

### ISSUE THREAD

**Issue by cuongngoht** [MicrosoftDocs/msteams-docs#9634]
Reproduce: In graph-explorer get channels weburl: https://graph.microsoft.com/v1.0/groups/1f85fc70-xxxx-xxxx-a21f-84acef7a9147/team/channels
We got:
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/40376533/858d5034-41ca-4311-bd2c-c391998e93e1)
Get anything weburl of any channels.

Old behavior: In classic team (old team) :
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/40376533/30ea0b64-774d-4a7f-8b36-45146fe77139)

New behavior: 
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/40376533/ce9c433e-cc96-4b59-8fdd-9ffec2a0b0e2)

I don't want configuration in settings: I need support deep link for to do it.
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/40376533/c3784314-8289-4590-9171-accb2c2f246b)

**Comment by ChetanSharma-msft** [comment]
Hello @cuongngoht - Thanks for raising your query.
We will check on it and let you know the updates.

**Comment by Nivedipa-MSFT** [comment]
@cuongngoht - We have tested this in New Teams version 23283.1600.2439.5518 but at our end its working fine. It's not opening in new tab.

Please refer below video and test this again.

https://github.com/MicrosoftDocs/msteams-docs/assets/92150070/5d5ba102-a0dd-45fe-8c89-4bd6b708773b

Please let us know if you are facing same.

**Comment by cuongngoht** [comment]
@Nivedipa-MSFT : Could you change the setting open content in teams windows to new windows? It's the default when my customer update  new ms teams. And after that you could saw.
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/40376533/b0e5e993-ff92-4122-a19f-09bd4ade798f)

**Comment by SaiPratap-MSFT** [comment]
@cuongngoht - We have set up new teams on our end, and the main window is the default option. Could you please verify from your end which option is set as the default?

**Comment by cuongngoht** [comment]
@SaiPratap-MSFT  My option set default is new windows. But could you provide some thing like deeplink only open main windows. Because my software need feature like that. And some time we open new tab.
