### ISSUE TITLE
Empty content in custom MS Teams tab

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#9636]
Copied bug from: https://github.com/OfficeDev/TeamsFx/issues/10080 

**Details from original post:**
**Describe the bug**
The tab content is only visible in Debug Mode

**To Reproduce**

I've created a custom Ms Teams tab using the Visual Studio Code extension. The content is very simple, it's only showing an iframe with a url.

hello.html:

```
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="icon" href="/favicon.ico" />
    <link rel="stylesheet" type="text/css" href="/static/styles/custom.css" />
    <script
      src="https://res.cdn.office.net/teams-js/2.9.1/js/MicrosoftTeams.min.js"
      integrity="sha384-xnsUQ1tUqsrutBJl0vuf4/hufzLFWW8ZhGnhItfpQ0/BtWgM2uw6YT6BQ5YaKBSM"
      crossorigin="anonymous"
    ></script>
    <script src="/static/scripts/teamsapp.js"></script>
    <title>Microsoft Teams Tab</title>
  </head>

  <body>
    <noscript>You need to enable JavaScript to run this app.</noscript>
    <div>
      <div style="position:relative;padding-top:60%;">
        <iframe src="https://www.youtube.com/embed/S93nYy-Bxzo" frameborder="0" allowfullscreen
          style="position:absolute;top:0;left:0;width:100%;height:100%;"></iframe>
      </div>
    </div>
    <script type="text/javascript">
      microsoftTeams.appInitialization.notifySuccess();
    </script>
  </body>
</html>
```

This is working ok when I debug the custom app (running on web), but doesn't work when I zip and load the app into Teams Desktop.

My manifest is:

```
{
    "$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.16/MicrosoftTeams.schema.json",
    "manifestVersion": "1.16",
    "version": "1.0.0",
    "id": "${{TEAMS_APP_ID}}",
    "packageName": "com.microsoft.teams.extension",
    "developer": {
        "name": "Company, Inc.",
        "websiteUrl": "www.google.com",
        "privacyUrl": "www.google.com",,
        "termsOfUseUrl": "www.google.com",
    },
    "icons": {
        "color": "color.png",
        "outline": "outline.png"
    },
    "name": {
        "short": "The Grid",
        "full": "The Grid"
    },
    "description": {
        "short": "short desc",
        "full": "full desc"
    },
    "accentColor": "#FFFFFF",
    "bots": [],
    "composeExtensions": [],
    "staticTabs": [
        {
            "entityId": "index0",
            "name": "Homepage",
            "contentUrl": "${{TAB_ENDPOINT}}/tab",
            "websiteUrl": "${{TAB_ENDPOINT}}/tab",
            "scopes": [
                "team",
                "personal",
                "groupChat"
            ]
        }
    ],
    "permissions": [
        "identity",
        "messageTeamMembers"
    ],
    "validDomains": [
        "${{TAB_DOMAIN}}"
    ]
}
```
And the domain and endpoint are:

```
TAB_DOMAIN=localhost:53000
TAB_ENDPOINT=https://localhost:53000
```

**Expected behavior**
The expected behavior is to show the content when I zip and load the app in Teams Desktop

**Screenshots**

**VS Code Extension Information (please complete the following information):**
 - OS: Mac OS
 - Version: 5.2.0

**CLI Information (please complete the following information):**
 - OS: Mac OS
 - Version: zsh
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b743e43d-95cc-3d1e-b142-31a16369f97e
* Version Independent ID: b743e43d-95cc-3d1e-b142-31a16369f97e
* Content: [Teams Toolkit Overview - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/toolkit/teams-toolkit-fundamentals)
* Content Source: [msteams-platform/toolkit/teams-toolkit-fundamentals.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/teams-toolkit-fundamentals.md)
* Service: **msteams**
* GitHub Login: @zyxiaoyuer
* Microsoft Alias: **zhany**

**Comment by ChetanSharma-msft** [comment]
Hello @efdiloreto - Thanks for raising your query.
We will look into it and let you know the updates.

**Comment by efdiloreto** [comment]
@Prasad-MSFT I've tried what you told me it didn't worked. I also tried doing a simple html with one header (without and iframe) and didn't work either.

**Comment by Prasad-MSFT** [comment]
> @Prasad-MSFT I've tried what you told me it didn't worked. I also tried doing a simple html with one header (without and iframe) and didn't work either.

@efdiloreto - Is there any console error/log you encountered with?

**Comment by Prasad-MSFT** [comment]
@efdiloreto - We tried to repro this issue at our end both in Teams Desktop client (Microsoft Teams Version 1.6.00.27969) and web client using the code provided following this(https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/app-hello-world/nodejs) sample and observed that the tab renders properly.
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/62237649/657776b1-be11-4d1f-ba39-586e484f6232)
