### ISSUE TITLE
Channel tab not refreshed when settings change via setConfig()

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#9637]
Copied bug from: https://github.com/OfficeDev/TeamsFx/issues/10077 

**Details from original post:**
**Describe the bug**
When changing the settings of a tab from the tab's settings page & calling the `setConfig()` method, the Teams client does not reload the tab to update based on the new changes. However, navigating off & back to the tab does pick up the saved changes, proving the changes were saved.

**To Reproduce**
1. create a new tab project with a new channel tab
1. add a tab that displays the current 
1. add a configuration page that changes the `entityId` when the settings dialog's SAVE button is clicked
1. observe the tab does not refresh and shows the old value
1. navigate away from the tab and come back, observe the `entityId` value has changed, proving the save settings page worked correctly

**Expected behavior**
Channel tab is refreshed by the Teams client when the settings are saved on the tab.

**Screenshots**
See the following video that demonstrates the issue:
<div>
    <a href="https://www.loom.com/share/3f59b31125954479a2a7e5bcf38c15ea">
      <p>GH - OfficeDev/TeamsFx Issue#10077 - Watch Video</p>
    </a>
    <a href="https://www.loom.com/share/3f59b31125954479a2a7e5bcf38c15ea">
      <img style="max-width:300px;" src="https://cdn.loom.com/sessions/thumbnails/3f59b31125954479a2a7e5bcf38c15ea-with-play.gif">
    </a>
  </div>

**VS Code Extension Information (please complete the following information):**
 - OS: macOS
 - Version v5.2

n/a---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b743e43d-95cc-3d1e-b142-31a16369f97e
* Version Independent ID: b743e43d-95cc-3d1e-b142-31a16369f97e
* Content: [Teams Toolkit Overview - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/toolkit/teams-toolkit-fundamentals)
* Content Source: [msteams-platform/toolkit/teams-toolkit-fundamentals.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/teams-toolkit-fundamentals.md)
* Service: **msteams**
* GitHub Login: @zyxiaoyuer
* Microsoft Alias: **zhany**

**Comment by sayali-MSFT** [comment]
Please Track the question from here-https://github.com/OfficeDev/microsoft-teams-library-js/issues/1963

**Comment by LeonYasoon** [comment]
This is still happening with teams-js 2.17.0

**Comment by sayali-MSFT** [comment]
@LeonYasoon -We have already raised the bug for the same. We will inform the engineering team that issue happens with 2.17.0 as well.
Could you please track this issue from here for updates-https://github.com/OfficeDev/microsoft-teams-library-js/issues/1963
