### ISSUE TITLE
This page says you can @ mention your app (Action ME) but a different page says that's not supported. Which is it?

### ISSUE THREAD

**Issue by AE-MS** [MicrosoftDocs/msteams-docs#9645]
[This page](https://learn.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/action-commands/define-action-command#select-action-command-invoke-locations) says your command can be invoked like this:

_Command box: By @mentioning your app in the command box._

...but [the overview page](https://learn.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/what-are-messaging-extensions?tabs=dotnet) says this:

 **Note
@mentioning message extensions is no longer supported in the compose box.**

Which is correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: efcdf768-1513-2249-b344-bf38ef64c70d
* Version Independent ID: 415b5d57-2d41-9540-55a7-2a33a4315e37
* Content: [Define message extension action commands - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/action-commands/define-action-command)
* Content Source: [msteams-platform/messaging-extensions/how-to/action-commands/define-action-command.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/messaging-extensions/how-to/action-commands/define-action-command.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **anclear**

**Comment by Nivedipa-MSFT** [comment]
@AE-MS - Thanks for reporting your issue. We will check this and update you soon.

**Comment by AE-MS** [comment]
Ah, I see. That isn't at all confusing lol.  :)
