### ISSUE TITLE
When is the full name of a custom Teams app used?

### ISSUE THREAD

**Issue by dabaker6** [MicrosoftDocs/msteams-docs#9646]
I have a requirement to have the name for a custom Teams app to be greater than 30 characters. Under the name section in the [manifest schema docs](https://learn.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema#name) for the full name it states 'full name of the app, used if the full app name exceeds 30 characters.'

However if I include an app manifest with these names:
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/23143918/862edc7d-55df-4224-84df-9c893c41e73b)

I only ever see the short name, in the app bar, fly-out, app dialog etc... Is the full name ever used? And if so where and how can I get it to display?

**Comment by Meghana-MSFT** [comment]
There is no place where the full name is used, and it is going to be deprecated.

**Comment by dabaker6** [comment]
That's great, thank you very much for the info.
