### ISSUE TITLE
The JavaScript examples on this page call the class MainDailog instead of MainDialog

### ISSUE THREAD

**Issue by AE-MS** [MicrosoftDocs/msteams-docs#9650]
Seems like a typo in the word Dialog

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 039ff5cc-7243-ce4b-527e-c152755eeb72
* Version Independent ID: 039ff5cc-7243-ce4b-527e-c152755eeb72
* Content: [Code configuration for enabling SSO for bots - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/authentication/bot-sso-code?tabs=cs1%2Ccs2%2Ccs3%2Ccs4%2Ccs5)
* Content Source: [msteams-platform/bots/how-to/authentication/bot-sso-code.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/bots/how-to/authentication/bot-sso-code.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **surbhigupta**

**Comment by ChetanSharma-msft** [comment]
Hello @surbhigupta12 - Please help us to update the documentation.
