### ISSUE TITLE
Call is freezing when pinning video

### ISSUE THREAD

**Issue by tzsolti** [MicrosoftDocs/msteams-docs#9651]
In the New Teams, in the middle of any meeting, the call window freezes when:
- I pin any of the videos
- anyone starts a screen sharing

Stopping and starting videos or screen sharing does not change anything. Really annoying. 
It is still possible to pop out the screen sharing, but the video won't work anymore unless we restart the call.

**Comment by Meghana-MSFT** [comment]
This question is related to Teams product, and we are mainly responsible for Teams app development related queries. Hence adding Teams product tag. Thank you for your understanding.

**Comment by ChetanSharma-msft** [comment]
We are mainly responsible for Microsoft Teams app development related issues. 

For Microsoft Teams product issues/failures your tenant Admin can reach out to [Microsoft 365 Product Support](https://docs.microsoft.com/en-us/microsoft-365/admin/contact-support-for-business-products?view=o365-worldwide&tabs=online). 

For general questions about Microsoft Teams please post your question on [Microsoft Teams Community](https://answers.microsoft.com/en-us/msteams/forum).

**Comment by tzsolti** [comment]
For anyone experiencing the same problems, it was caused by a service called "NahimicService". I have disabled it and since then I don't have any issues.
