### ISSUE TITLE
The OneDrive button Add new doesn't show Document Set

### ISSUE THREAD

**Issue by AlbertvanGrondelle** [MicrosoftDocs/msteams-docs#9659]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 19ddf42e-0a47-7717-52d4-e549155480a2
* Version Independent ID: 4bbe9beb-233f-cfd5-097b-f280aab5fde8
* Content: [Microsoft Teams developer community support and feedback - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/feedback)
* Content Source: [msteams-platform/feedback.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/feedback.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Prasad-MSFT** [comment]
@AlbertvanGrondelle - Could you please provide more details on your issue? Which one drive button doesn't show?
