### ISSUE TITLE
Add note that ActionCard ActionSet is not supported

### ISSUE THREAD

**Issue by sguryev** [MicrosoftDocs/msteams-docs#966]
I was trying make ActionSet working in Teams. But I was not able even to see it. I guess that `ActionSet` is not supported yet. I have updated `ActionCards` package to version 1.2.2 but `ActionSet` is not showing.

Reprosteps:
1. Open https://adaptivecards.io/designer/ with `Flight Details` sample (contains `ActionSet`)
2. Make sure to update `AdaptiveCard` package to version 1.2.2 (otherwise it will not be even deserialized)
3. Copy JSON from browser to file and deserialize using `ActionCard.FromJson()` method.

Expected:
![image](https://user-images.githubusercontent.com/6978458/65390115-ecc03b80-dd64-11e9-9879-e39721c660ff.png)

Actual:
![image](https://user-images.githubusercontent.com/6978458/65390123-fa75c100-dd64-11e9-84cc-f430c6f45b71.png)

**Comment by clearab** [comment]
Hi - Teams only supports v1.0 of Adaptive Cards. Support for 1.2 is coming soon.
