### ISSUE TITLE
TeamsJS - `toggleIncomingClientAudio` API does not work as expected

### ISSUE THREAD

**Issue by julianraj** [MicrosoftDocs/msteams-docs#9666]
`toggleIncomingClientAudio` to mute incoming audio does not work if the microphone is not muted by the user beforehand.

**API ref:** https://learn.microsoft.com/en-us/javascript/api/@microsoft/teams-js/meeting?view=msteams-client-js-latest#@microsoft-teams-js-meeting-toggleincomingclientaudio

##### Expected Behaviour
`toggleIncomingClientAudio` should toggle the incoming audio speaker irrespective of the mic status of the end user.

##### Current Behaviour
* `toggleIncomingClientAudio` works only if the mic is already muted by the user.
* in case the mic is on, this API has no effect on the incoming audio, however, the API response shows that the toggle was a success.

**Comment by Prasad-MSFT** [comment]
@julianraj - Thanks for raising this issue. We will check this from our end and will share updates

**Comment by Prasad-MSFT** [comment]
@julianraj - We tried to repro this issue at our and observed below behaviour:
1. When Both User A (Organizer/Presenter) and User B joined the meeting with their Microphone in **Unmute** state.
    `toggleIncomingClientAudio` works fine i.e. User A can mute/unmute User B's incoming audio. (Expected behaviour)

2. When User B joined the meeting with Microphone in **Mute** state.
    User A can't unmute/mute User B's incoming audio, as it can't override manual mute. (Expected behaviour)

**Comment by julianraj** [comment]
@Prasad-MSFT 

We use this API to mute the incoming audio of the users' own device. User A mutes/unmutes his/her own device.

It was never the expectation to mute other users' incoming audio in the past as opposed to what you mentioned in your test where userA mutes/unmutes userB's device.

Can you let me know when this change was implemented?

**Comment by Prasad-MSFT** [comment]
@julianraj - We will check this with engineering team once and will update you accordingly what should be the expected behaviour.

**Comment by julianraj** [comment]
thanks, @Prasad-MSFT 
This is affecting our end users in production. Can you please escalate this as soon as possible?

**Comment by ChetanSharma-msft** [comment]
Hello @julianraj - Sorry for delay in response.
We will check the latest updates and let you know.

**Comment by Prasad-MSFT** [comment]
Hi @julianraj - We got below update from engineering team: 
`toggleIncomingClientAudio` API does not mute anyone, it simply stops incoming audio. 
When this API is called from a specific Teams client, any incoming audio from all users in that meeting are muted/unmuted. When toggled on from User A, the User A will not be able to hear anyone speak in the meeting. User A can see other users highlighted in meeting when they speak but no audio. Now, this toggling will be only for user client calling API. User B in this case will be able to hear all other users in meeting speaking just fine. Hope this makes sense. Also, this API cannot override manual mute.

**Comment by julianraj** [comment]
Hi @Prasad-MSFT, thanks for the detailed explanation. That's the same behavior we want as well. 
I did some tests and found that this API works on the old version of MSTeams and only has issues on MS Teams `v2.x`.

Can you please confirm if it's also the case on your end? thanks!

**Comment by Prasad-MSFT** [comment]
@julianraj - Okay, we have tested this in Teams classic, and it was working fine there. We will test it again in New Teams (Teams T 2.1) and will update you accordingly.

**Comment by Prasad-MSFT** [comment]
> Hi @Prasad-MSFT, thanks for the detailed explanation. That's the same behavior we want as well. I did some tests and found that this API works on the old version of MSTeams and only has issues on MS Teams `v2.x`.
> 
> Can you please confirm if it's also the case on your end? thanks!

@julianraj - We checked this using New Teams (T2.1) and observed that this API doesn't work in New Teams. We have raised a bug for the same. We will inform you once we get any further update from engineering team. 
Thanks!

**Comment by Prasad-MSFT** [comment]
Hi @julianraj - We got update from engineering team that "`toggleIncomingClientAudio` API is not supported in T2.X yet". Engineering team is actively working on enabling the API support in T2.X. We will provide ETA as soon as available, thanks!

**Comment by julianraj** [comment]
hi @Prasad-MSFT ,  during our tests we found that the API was working on v2.x as well. 
Can you please confirm if this API is now officially supported on `v2.x` web and desktop both? thanks!

**Comment by julianraj** [comment]
@Prasad-MSFT  any updates ?

**Comment by Prasad-MSFT** [comment]
Hi @julianraj - We got confirmation from engineering team that, "`toggleIncomingClientAudio` API is now supported in T2.x"

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, please feel free to reopen it, if required.
