### ISSUE TITLE
[Designer] markdown not consistent

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#9669]
Copied bug from: https://github.com/microsoft/AdaptiveCards/issues/8685 

**Details from original post:**
the designer renders markdown correct, but in teams it doesnt work.
things I tried:
\>
\`\`\`
best regards nicolas
---
#### Document Details

⚠ *Do not edit this section.It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Cards reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **surbhigupta12**

**Comment by Prasad-MSFT** [comment]
@moreamazingnick - Could you please provide more context on your issue? Please do share the card JSON which you used along with the screenshot showing how it is getting rendered in Designer vs Teams.
