### ISSUE TITLE
Teams bug reporting

### ISSUE THREAD

**Issue by dbalabka** [MicrosoftDocs/msteams-docs#968]
Unfortunately, I didn't found in the documentation where I can report the Teams bugs with the possibility to track the bug status and in which release it would be fixed.
Could you please provide a link to the bug tracker (e.g. Github)?

**Comment by Trinetra-MSFT** [comment]
@dbalabka , Thanks for reaching out to us. You can report a bug at [Microsoft Teams UserVoice!](https://microsoftteams.uservoice.com/forums/908686-bug-reports.).

**Comment by dbalabka** [comment]
@TravisCragg-MSFT thank you! I'm already aware of this resource that mostly looks like a forum rather than regular bug tracker. Also, there no any information about in what expected version it will be fixed. There are a lot (hundred) of posts with status "working on it" sitting there for months.
Тhere are about ~600 bugs reported and only one (!) is with status "completed" and another one (!) with status "working on it".

Above described, is the reason why I'm curious exists any public bug tracker that represents a real situation.

**Comment by dbalabka** [comment]
@Trinetra-MSFT now UserVoice service returns 404. Are you experience any technical issue? or you are going to migrate to a new service (e.g. Github 😄)?
![image](https://user-images.githubusercontent.com/1269372/65964893-6becf800-e466-11e9-9f33-2813c971a602.png)

**Comment by Gousia-MSFT** [comment]
@dbalabka Currently we do not have any publicly available bug tracker. We don't have any plans for this as of now. Please raise an issue on GitHub if you want to report a bug and we will track it internally.
