### ISSUE TITLE
[Feedback] This doesn't work, like everything in your documentation.

### ISSUE THREAD

**Issue by v-npaladugu** [MicrosoftDocs/msteams-docs#9683]
Feedback

This doesn't work, like everything in your documentation. Every feature, function, and option in your entire software stack seems to require a troubleshooting and workaround project.

What exactly do you think people do for a living? Are they supposed to be using your software as a tool or is administering your user software their job?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b6687ceb-6d67-b0b7-0797-b16d14e4bd97
* Version Independent ID: b6687ceb-6d67-b0b7-0797-b16d14e4bd97
* Content: [Deep link to a Teams chat - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-link-teams)
* Content Source: [msteams-platform/concepts/build-and-test/deep-link-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/build-and-test/deep-link-teams.md)
* Service: **msteams**
* GitHub Login: @v-npaladugu
* Microsoft Alias: **surbhigupta**

**Comment by Nivedipa-MSFT** [comment]
@v-npaladugu - Could you please share the specific issue you are currently facing and the updates you need?

**Comment by v-npaladugu** [comment]
Hi @Nivedipa-MSFT, we have received this as feedback on docs, request you to kindly test the article and let us know if there is any doc update required.

**Comment by ChetanSharma-msft** [comment]
Hello @v-npaladugu - Sorry for delay in response. We will look into the documentation and let you know the updates.

**Comment by v-npaladugu** [comment]
Thank you @ChetanSharma-msft

**Comment by Nivedipa-MSFT** [comment]
@v-npaladugu - We tested the deep link formats given in the document and the provided samples, and they worked fine on our end. No document updates are required for this.

**Comment by nicoleahmed** [comment]
deep links for filebrowsertabapp not working anymore:
format : 
     https://teams.microsoft.com/_#/FileBrowserTabApp/General?groupId=&threadId=&ctx=channel


example:
      https://teams.microsoft.com/_#/FileBrowserTabApp/General?threadId=19:cd614dd548474436bf4e7acd5dc36286@thread.tacv2&ctx=channel

**Comment by ChetanSharma-msft** [comment]
Hello @nicoleahmed - Could you please share the official documentation you have referred for your below format?
format :
https://teams.microsoft.com/_#/FileBrowserTabApp/General?groupId=&threadId=&ctx=channel

**Comment by nicoleahmed** [comment]
It's not working in new reams desktop client.

Its in the guidance and in Microsoft answers

**Comment by Wajeed-msft** [comment]
@nicoleahmed - Regarding the deep link to Files tabs, deep link seems to be a copy pasted from browser and not the[Platform supported one](https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links). We  Could you please raise it as a feature ask here: [Microsoft Teams feedback portal](https://feedbackportal.microsoft.com/feedback/forum/ad198462-1c1c-ec11-b6e7-0022481f8472)

**Comment by nicoleahmed** [comment]
What is the platform supported deep link to the files tab? Is this not it?

**Comment by Prasad-MSFT** [comment]
@nicoleahmed - The entity deep link can be used as documented here:
https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-link-application?tabs=teamsjs-v2#configure-deep-link-to-browse-within-your-app-manually
 
The app ID of the Channel Files Tab is `3ed5b337-c2c9-4d5d-b7b4-84ff09a8fc1c` and the entityId is `FileBrowserTabApp`. 
So, the deep link to it would look something like this:
`https://teams.microsoft.com/l/entity/3ed5b337-c2c9-4d5d-b7b4-84ff09a8fc1c/FileBrowserTabApp?context=%7B%22channelId%22%3A%22CHANNEL_ID%22%7D`
 
The context should contain the CHANNEL_ID of the channel where the Files tab is to be opened, for example:
```
let context = {
  "channelId": "19:cd614dd548474436bf4e7acd5dc36286@thread.tacv2"
};
let deeplink = "https://teams.microsoft.com/l/entity/3ed5b337-c2c9-4d5d-b7b4-84ff09a8fc1c/FileBrowserTabApp?context=" + encodeURIComponent(JSON.stringify(context));
```
 
With the final deeplink looking something like this:
`https://teams.microsoft.com/l/entity/3ed5b337-c2c9-4d5d-b7b4-84ff09a8fc1c/FileBrowserTabApp?context=%7B%22channelId%22%3A%2219%3Acd614dd548474436bf4e7acd5dc36286%40thread.tacv2%22%7D`
