### ISSUE TITLE
[Doc-Bug] Teams app in M365 portal - SDK initialization timed out

### ISSUE THREAD

**Issue by SubbaReddi** [MicrosoftDocs/msteams-docs#9685]
Hi Team,
Support for apps running on the microsoft365.com domain was not added to teams-js until v2.5.0. So, we see SDK initialization time out error with using older versions. Documentation is only mentioned to use >=2.0.0. So, please add note for the same.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6fcea0c3-c249-a292-913b-dc0271e4e810
* Version Independent ID: 6fcea0c3-c249-a292-913b-dc0271e4e810
* Content: [Extend Teams apps across Microsoft 365 - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/m365-apps/overview?tabs=Android)
* Content Source: [msteams-platform/m365-apps/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/m365-apps/overview.md)
* Service: **msteams**
* Sub-service: **m365apps**
* GitHub Login: @erikadoyle
* Microsoft Alias: **mosdevdocs**

**Comment by Nivedipa-MSFT** [comment]
@surbhigupta12 - Could you please help here to add the note in the document.
