### ISSUE TITLE
New Teams desktop client NOT signing out

### ISSUE THREAD

**Issue by ferrariwes** [MicrosoftDocs/msteams-docs#9686]
The new Teams client on both non-domain-joined Win 10 and Win 11 will not sign-out an account.   This is posing a huge problem and security issue in situations where users share a PC (like in an ad-hoc meeting room).   Users login, they're prompted to enter credentials (with MFA) -  but signing out does not clear or reprompt for credentials.  Seems to be retaining a cache of all previous logins.  Any new user launching the new client sees the "Pick an Account" screen - and by selecting a previous user is able to bring up a previous users Teams session.   We have confirmed that there are no user entries in either User Accounts (work or school) or Credential Manager for any of the previously logged in user.  Is this a known bug?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 19ddf42e-0a47-7717-52d4-e549155480a2
* Version Independent ID: 4bbe9beb-233f-cfd5-097b-f280aab5fde8
* Content: [Microsoft Teams developer community support and feedback - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/feedback)
* Content Source: [msteams-platform/feedback.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/feedback.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Wajeed-msft** [comment]
Thank you for submitting feedback.

Given that is not related to Teams App development, best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. 

Please follow this link to contact support for business products: https://docs.microsoft.com/office365/admin/contact-support-for-business-products

**Comment by Teknophobia** [comment]
Have the exact same issue where I work.  Did you manage to find a solution or log as a bug with Microsoft @ferrariwes ?

Thanks.

**Comment by ferrariwes** [comment]
@Teknophobia I did submit a bug report with Teams Dev group.  The solution for us (and I think the only one available) is to revert to Teams classic for the affected computers.  In addition, we followed this advice from support
Resolution from Teams Support: With the new Teams we are also experiencing the issue, for now we would need to switch back to old teams and disable the new team org wide. To disable new teams from policy in Teams admin center, you need to:
-Sign into the Microsoft Teams admin center.
-In the left navigation, go to Teams > Teams policies.
-Select the Teams update policy and Global.
-Show teams preview feature> On for everyone.
-Select Use New teams client > Not enabled.
