### ISSUE TITLE
[Doc-enhancement] Third party authentication in tab prompting for authentication repeatedly

### ISSUE THREAD

**Issue by SubbaReddi** [MicrosoftDocs/msteams-docs#9687]
If the below storage partitioning settings are enabled in browser(chrome://flags/#third-party-storage-partitioning), then third party authentication will not work. After authentication, values will not be saved to local storage. So, app will prompt for authentication repeatedly.

![image](https://github.com/MicrosoftDocs/msteams-docs/assets/69682598/11c629ab-ea6b-43d4-8282-6e88b21a0c8b)

![image](https://github.com/MicrosoftDocs/msteams-docs/assets/69682598/d98b817a-234b-47f7-bc0e-7d03d595c903)

It would be good to add note for the same in documentation.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3b1dcd0d-471b-2d33-54b5-39a93dfba2a8
* Version Independent ID: 5bd44149-777e-b449-bd2e-f20b9bd04038
* Content: [Configure third party OAuth authentication - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-tab-aad?tabs=teamsjs-v2)
* Content Source: [msteams-platform/tabs/how-to/authentication/auth-tab-aad.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/tabs/how-to/authentication/auth-tab-aad.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **surbhigupta**

**Comment by ChetanSharma-msft** [comment]
Hello @surbhigupta12 - Please help to update the documentation.
