### ISSUE TITLE
[Questions] Can we create an adaptive card in teams with upload module

### ISSUE THREAD

**Issue by qjkobe** [MicrosoftDocs/msteams-docs#9688]
like this: 
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/16449598/90b64197-d8a0-4e62-acc0-f97f1c500f54)

**Comment by Prasad-MSFT** [comment]
@qjkobe - Adaptive Cards in Teams support various types of inputs and actions, including text inputs, date inputs, choice sets, and actions like opening a URL, sending messages to the bot, and initiating OAuth flow. However, there's no direct mention of a file or image upload capability within an Adaptive Card. You can include an inline image with any Teams card. Supported image formats are .png, .jpg, or .gif formats.

**Comment by qjkobe** [comment]
Thanks for your response.
