### ISSUE TITLE
how action.submit works in messaging extension of teams 

### ISSUE THREAD

**Issue by catchmeifyou** [MicrosoftDocs/msteams-docs#969]
Adaptive card Action.Submit in ME result sends an "invoke" activity to the bot w/ a value. Note that this is different from the way Action.Submit works in a conversation, where it sends a "message" activity w/ a value. The docs should describe this difference in behavior.

**Comment by catchmeifyou** [comment]
@Gousia-MSFT, I'm stucked with the issue while implementing message extension actions in my teams app , There is no documentation or sample code for how to invoke actions in messaging extension. any help will be greatly appreciated.

**Comment by Gousia-MSFT** [comment]
@catchmeifyou Please go through [Initiate actions with Message extension.](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/messaging-extensions/create-extensions?tabs=typescript) Please let us know if you face any issues.

**Comment by Trinetra-MSFT** [comment]
Please feel free to reopen if you still facing this issue.
