### ISSUE TITLE
[Accessibility]Need a way to set the arial label of task module

### ISSUE THREAD

**Issue by qjkobe** [MicrosoftDocs/msteams-docs#9694]
As task module is a dialog. It need accessible name.
Or it will cause a11y issue:
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/16449598/2d071a66-bc96-4d54-be3a-819710f524ff)

**Comment by sayali-MSFT** [comment]
@qjkobe -Could you please elaborate more on this?
