### ISSUE TITLE
[Accessibility]  Focus is provided for non interactive section of dialog, tabbing further from button focus in iframe does not go to 'Close' button

### ISSUE THREAD

**Issue by qjkobe** [MicrosoftDocs/msteams-docs#9696]
Take jira cloud app as example as it has a similar UI with our app.
1. Focus is provided for non interactive section of dialog. That is the DOM of whole iframe content:
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/16449598/767373c1-d944-45a5-9bd2-415e1289617a)
2. Tab order:
Expected: 
1.Focus on the "Review Permission Button".
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/16449598/cb9b3f0d-31e5-444f-8a51-1b935992e198)
2.Press Tab. Then the focus should be provided for close button.
Actual: 
1.Focus on the "Review Permission Button".
2.Press shift tab twice. Then the focus is provided for close button.

**Comment by sayali-MSFT** [comment]
@qjkobe -Thanks for reporting your issue.
We will check this at our end and will get back to you.
