### ISSUE TITLE
Error 500 or 503 sending message via Webhook

### ISSUE THREAD

**Issue by thespeed94** [MicrosoftDocs/msteams-docs#9700]
Hello,

Since yesterday we are getting a webhook error 500 and 503 via API.

<img width="1278" alt="Captura de pantalla 2023-10-17 a la(s) 10 12 59" src="https://github.com/MicrosoftDocs/msteams-docs/assets/48035024/234df48a-983a-4d52-bbdc-77109fb8fa8d">
<img width="1268" alt="Captura de pantalla 2023-10-16 a la(s) 13 44 22" src="https://github.com/MicrosoftDocs/msteams-docs/assets/48035024/0e7deacb-85b0-437d-bdc5-6400163a2c4e">

We are using this url

https://[organization].webhook.office.com/webhookb2/

We are using this body:
`{
    "@type": "MessageCard",
    "@context": "http://schema.org/extensions",
    "themeColor": "D81126",
    "summary": "Tipo de cambio actualizado",
    "sections": [
        {
            "activityTitle": "Tipo de cambio actualizado",
            "activitySubtitle": ""
        },
        {
            "facts": [
                {
                    "name": "Base Currency",
                    "value": "USD"
                },
                {
                    "name": "Base Rate",
                    "value": "1"
                },
                {
                    "name": "Currency",
                    "value": "PEN"
                },
                {
                    "name": "Rate",
                    "value": "3.8595"
                },
                {
                    "name": "Fixed",
                    "value": "true"
                },
                {
                    "name": "Email",
                    "value": "m.m@example.com"
                },
                {
                    "name": "UserName",
                    "value": "m.m"
                },
                {
                    "name": "UserId",
                    "value": "111"
                }
            ]
        }
    ],
    "potentialAction": []
}`

**Comment by ChetanSharma-msft** [comment]
Hello @thespeed94 - Thanks for raising your query.
We will look into it and let you know the updates.

**Comment by Meghana-MSFT** [comment]
@thespeed94 - We checked this at our end and it is working fine. We use the below webhook URL - https://[organization].webhook.office.com/webhookb2/4175c299-8aa8-4c65-819b-e7ee0aac5270@4ad59956-0f88-4b88-a9d0-570b6eb4e66b/IncomingWebhook/a7f16f049b9e4042ade39d50e073d9c5/ce9def33-d7fc-444c-8728-be1f95e6b6f2

![image](https://github.com/MicrosoftDocs/msteams-docs/assets/81138249/b15c2f98-a99a-4bc5-9fdf-2d73cadee1b1)

![image](https://github.com/MicrosoftDocs/msteams-docs/assets/81138249/f61f7df7-9ba1-499e-9c56-130cdd7df443)


Could you please confirm if you are still facing this issue? Could you please let us know if you are getting any this similar error " unauthorized, the public key XXXXXXXXXXXXXXXXX = is not found for ring WW, cannot validate signature" like mentioned here https://github.com/MicrosoftDocs/msteams-docs/issues/9698

**Comment by thespeed94** [comment]
> @thespeed94 - We checked this at our end and it is working fine. We use the below webhook URL - https://[organization].webhook.office.com/webhookb2/4175c299-8aa8-4c65-819b-e7ee0aac5270@4ad59956-0f88-4b88-a9d0-570b6eb4e66b/IncomingWebhook/a7f16f049b9e4042ade39d50e073d9c5/ce9def33-d7fc-444c-8728-be1f95e6b6f2
> 
> ![image](https://user-images.githubusercontent.com/81138249/276119692-b15c2f98-a99a-4bc5-9fdf-2d73cadee1b1.png)
> 
> ![image](https://user-images.githubusercontent.com/81138249/276119959-f61f7df7-9ba1-499e-9c56-130cdd7df443.png)
> 
> Could you please confirm if you are still facing this issue? Could you please let us know if you are getting any this similar error " unauthorized, the public key XXXXXXXXXXXXXXXXX = is not found for ring WW, cannot validate signature" like mentioned here #9698

Hi, I tried sending the API request again, and it worked!
Thank you so much!
