### ISSUE TITLE
Machine names with numbers aren't supported in URL

### ISSUE THREAD

**Issue by JamesHorsley** [MicrosoftDocs/msteams-docs#9709]
There is a note next to OpenUrl action saying "Machine names with numbers aren't supported in URL" - that seems to be a very important restriction and I am sure the author knew what they meant but this is as clear as mud really.  What exactly is a machine name in this context? Maybe an example of what is not allowed would make it clearer.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 672a763d-189b-8ba0-f66e-c07f1dc0a962
* Version Independent ID: 1ac7a9bd-138b-3bf8-60a3-1842d87371fd
* Content: [Add card actions in a bot - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-actions?tabs=json)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-actions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/task-modules-and-cards/cards/cards-actions.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **surbhigupta**

**Comment by Meghana-MSFT** [comment]
Thank you for reporting this issue, we will check this and get the doc updated.

**Comment by Meghana-MSFT** [comment]
@surbhigupta12 - Could you please help to update the below example for the following note in the doc "Machine names with numbers aren't supported in URL."

E.g. If the hostname includes numbers as well like "userhostname123".
