### ISSUE TITLE
Different Notification Banners

### ISSUE THREAD

**Issue by mmalcangio** [MicrosoftDocs/msteams-docs#9714]
It was observed that we received two types of separate notification banners for one team's call with the sequence as pasted below.NOTE: The first notification banner just pops up and stays for a few seconds. After that second notification banner pops up along with ringing.Scenario: Click on "Join" Button.Observation: You receive the second notification banner with the "Accept" and "Decline" buttons.Scenario: Click on the "Send message" Button.Observation: You receive the second notification banner with the "Accept" and "Decline" buttons.What is the purpose of the second notification banner?Will there be any changes in the call back going forward related to these actions?

<img width="327" alt="image" src="https://github.com/MicrosoftDocs/msteams-docs/assets/3903521/e29492ee-8b45-49e4-a446-7a1555c501a5">
<img width="327" alt="image" src="https://github.com/MicrosoftDocs/msteams-docs/assets/3903521/4f4a2e3a-f805-4812-9953-8d06c26d38a1">

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 19ddf42e-0a47-7717-52d4-e549155480a2
* Version Independent ID: 4bbe9beb-233f-cfd5-097b-f280aab5fde8
* Content: [Microsoft Teams developer community support and feedback - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/feedback)
* Content Source: [msteams-platform/feedback.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/feedback.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by ChetanSharma-msft** [comment]
Hello @mmalcangio - Thanks for raising your query.
Could you please share the repro steps along with the supported docs, if any?.
