### ISSUE TITLE
Manifest Json : Formatting of Text Support?

### ISSUE THREAD

**Issue by moirf** [MicrosoftDocs/msteams-docs#972]
Can we use custom formatting while providing the manifest.json into Teams Application?

For example : In App full description I want to add some highlight feature as bold, italics, bullet points etc.

**Comment by Trinetra-MSFT** [comment]
Currently manifest schema do not have text-format property defined for description. Please take a look at [Reference: Manifest schema for Microsoft Teams](https://developer.microsoft.com/en-us/json-schemas/teams/v1.5/MicrosoftTeams.schema.json).
