### ISSUE TITLE
Teams Messaging Ext SSO documentation vs Samples

### ISSUE THREAD

**Issue by ericsche** [MicrosoftDocs/msteams-docs#9724]
https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/bots/how-to/authentication/bot-sso-code.md
The current page reference code that does not exist in any of our samples. This makes it very hard for dev not familiar with Bot Framework auth to get started.

Referencing our code samples today : 
https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/app-sso/csharp/App%20SSO%20Sample
https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/msgext-search-auth-config/csharp

**Comment by ChetanSharma-msft** [comment]
Hello @ericsche - Thanks for raising your query.
We will look into it and let you know the updates.

**Comment by sayali-MSFT** [comment]
@Pawan-MSFT -Could you please help here?

**Comment by ChetanSharma-msft** [comment]
Hello @ericsche - We have merged the changes for "app-sso" sample as a part of below PR: 
https://github.com/OfficeDev/Microsoft-Teams-Samples/pull/1003
 
We will also do changes for [msgext-search-auth-config/csharp](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/msgext-search-auth-config/csharp) and let you know the updates soon.

**Comment by ChetanSharma-msft** [comment]
We have raised another PR for it: https://github.com/OfficeDev/Microsoft-Teams-Samples/pull/1005
