### ISSUE TITLE
[Rendering] MS Teams Adaptive Card not rendering full width

### ISSUE THREAD

**Issue by Elkhad** [MicrosoftDocs/msteams-docs#9728]
Hello, exactly same issue as  https://github.com/MicrosoftDocs/msteams-docs/issues/7638 occured again this morning in my company Ms Teams version 1.6.00.27573 updated on 12/10/2023…. Adaptative card are not displaying full width! How do you manage regression Test at Microsoft?

**Comment by Prasad-MSFT** [comment]
@Elkhad - Thanks for raising this issue. Could you please let us know if its happening in Teams classic or Teams T2.1?
Also please let us know how you are sending the card to MS Teams (Using bot or webhook or Power Automate) along with the card JSON?

**Comment by Elkhad** [comment]
Hello @Prasad-MSFT,

thank you for your quick answer.
I am using Ms Teams Classic, adaptative card are sent with a webhook and it was working fine since your solved it in the other ticket I mentionned! But since this week and new Ms Teams update, it’s failing again…

**Comment by Prasad-MSFT** [comment]
@Elkhad - We tried to repro this issue in both MS Teams desktop client `(Microsoft Teams Version 1.6.00.28967)` and web client and observed that the card is rendering properly.

Card JSON:
```
{
    "type": "message",
    "attachments": [
        {
            "contentType": "application/vnd.microsoft.card.adaptive",
            "content": {
                "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
                "type": "AdaptiveCard",
                "version": "1.2",
                "body": [
                    {
            "type": "TextBlock",
            "weight": "Bolder",
            "text": "KWNO 100904 ADMSDM",
            "wrap": true,
            "horizontalAlignment": "Center"
        },
        {
            "type": "ColumnSet",
            "separator": true,
            "columns": [
                {
                    "type": "Column",
                    "items": [
                        {
                            "type": "Image",
                            "style": "Person",
                            "url": "https://images.stormvistawxmodels.com/emoji/logos/noaa.png",
                            "size": "Large"
                        }
                    ],
                    "width": "auto"
                },
                {
                    "type": "Column",
                    "items": [
                        {
                            "type": "TextBlock",
                            "spacing": "None",
                            "text": "SENIOR DUTY METEOROLOGIST NWS ADMINISTRATIVE MESSAGE\n\nNWS NCEP CENTRAL OPERATIONS COLLEGE PARK MD\n\n0903Z TUE OCT 10 2023",
                            "isSubtle": true,
                            "size": "Small",
                            "wrap": true
                        }
                    ],
                    "width": "stretch",
                    "verticalContentAlignment": "Center"
                }
            ]
        },
        {
            "type": "TextBlock",
            "text": "\n\nCRITICAL WEATHER DAY STATUS...\nCritical Weather Day continues until 10/18Z for Pacific Region in\nsupport of tropical cyclone ops over Guam, Rota, Tinian, Saipan.\n\nCRITICAL WEATHER OUTLOOK...\nTuesday - Critical until 18Z...Tropical Cyclone.\nWednesday - None.\nThursday - None.\n\n\n",
            "wrap": true,
            "separator": true
        },
        {
            "type": "TextBlock",
            "text": "Ready/SDM/NCO/NCEP",
            "wrap": true,
            "separator": true,
            "fontType": "Monospace",
            "size": "Small",
            "isSubtle": true
        }
                ],
                "msteams": {
                    "width": "Full"
                }
            }
        }
    ]
}
```
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/62237649/5b52fb52-6f70-421a-9969-53e4d7cc07c3)

**Comment by Elkhad** [comment]
Besides, i also notice a new look for user avatar icon in this new version that don’t display webhook custom icon now:

Before update:
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/120216392/9728b1a1-4783-4fd5-836d-67d7b6b6d722)

**Comment by Prasad-MSFT** [comment]
> Hello @Prasad-MSFT
> 
> thank you for your actions,
> 
> I have just tried exactly same code you provide as an example and the issue with full width is still here:
> 
> ![image](https://user-images.githubusercontent.com/120216392/276916959-034a3335-4132-48a1-afa9-e397727532eb.png)
> 
> regards

This card screenshot which you shared, is it in personal scope or channel scope?
The one i tested is in channel scope.

**Comment by Elkhad** [comment]
This is a private Channel given as example, and i have same issue in General Channel also

**Comment by Prasad-MSFT** [comment]
> This is a private Channel given as example, and i have same issue in General Channel also

Could you please try to update your MS teams and check if this issue occurs in updated versions as well or not?
The version I tested is Microsoft Teams Version 1.6.00.28967 (where issues is not repro-able) is higher than the version you tested.

**Comment by Elkhad** [comment]
Ok, so I need to wait because I cannot update Teams manually (I can just click on the « Check for updates » menu but it gives me nothing)… Teams release are probably planned by an internal administrator in my company

**Comment by Elkhad** [comment]
But I also don’t understand why you have decided to put webhook icon inside the message, at the top, knowing that it leaves now less space for message content and simply truncate the content with the « show less/ show more » button. I have designed all my picture before so that they were fitting the space left with the old template I show you in my previous message (with webhook icon on the left side)

**Comment by Prasad-MSFT** [comment]
> But I also don’t understand why you have decided to put webhook icon inside the message, at the top, knowing that it leaves now less space for message content and simply truncate the content with the « show less/ show more » button. I have designed all my picture before so that they were fitting the space left with the old template I show you in my previous message (with webhook icon on the left side)

@Elkhad - I have not intentionally kept the icon inside message. It automatically renders like that after recent updates. Earlier it used to render similar to you mentioned in your case. And did you get chance to upgrade your Teams and check?
This is the link to downgrade or upgrade. (Windows only)
[Older versions of Microsoft Teams (Windows) | Uptodown](https://microsoft-teams.en.uptodown.com/windows/versions)

**Comment by Elkhad** [comment]
Hello @Prasad-MSFT 

thank you for your detailed answer.
Adaptative card are correctly displayed since yersteday morning. But the strange point is, even if my MS Teams have been successfully updated (i see the yellow banner with a message a the top), I am still under the same version 1.6.00.27573 with the same date 12/10/2023!  Also, during the update, i need to close Teams and open it again (but the trick of closing/opening Teams to solve card rendering did not work all the week before).

so don’t know where is the issue but it’s ok now 

for the icon displaying, I was asking you because I thought you were working on it/ you are close to the feature team working on it

sorry for the disturb

**Comment by Prasad-MSFT** [comment]
@Elkhad - Glad to hear that your issue is resolved. Thanks again!

We are closing this issue for now. Please feel free to reopen if required.
