### ISSUE TITLE
Receiving notifications after being logged out

### ISSUE THREAD

**Issue by ArjunMahesh97** [MicrosoftDocs/msteams-docs#973]
I have already left my previous company and have been logged out from my company mail(outlook) and from teams. 
The issue is that I am able to see the messages in teams through notifications, but on opening the app it says I've been logged out.

**Comment by Gousia-MSFT** [comment]
@ArjunMahesh97 Could you please share a screenshot of the issue you are facing?

**Comment by ArjunMahesh97** [comment]
> @ArjunMahesh97 Could you please share a screenshot of the issue you are facing?

I actually found another issue here. As soon as I open the app I can see the messages for a second before it asks me to sign in. I have attached screenshot for the notifications issue. I have a screenrecording for the second issue but not able to upload here.
![InkedScreenshot_20190926-105725_LI](https://user-images.githubusercontent.com/20819465/65675496-e46d4680-e06b-11e9-9b93-7a211e3d5b96.jpg)

**Comment by ArjunMahesh97** [comment]
The compressed screen recording.
[Inked19-09-26-14-34-42.zip](https://github.com/MicrosoftDocs/msteams-docs/files/3657007/Inked19-09-26-14-34-42.zip)

**Comment by Gousia-MSFT** [comment]
@ArjunMahesh97 Thanks for sharing the video. We are looking into this.

**Comment by Gousia-MSFT** [comment]
@ArjunMahesh97 After you pressed the signout button, did you wait for the signout to complete or you killed it and reopened the app?

**Comment by ArjunMahesh97** [comment]
As I mentioned earlier, I have logged out of my company mail(The mail attached to this Teams account). I have not directly logged out using teams.

**Comment by Gousia-MSFT** [comment]
@ArjunMahesh97 Thanks for reporting this. We have raised a bug for this and we are tracking it internally.

**Comment by Gousia-MSFT** [comment]
This is resolved now. Please check.
