### ISSUE TITLE
ReplyToId present when NOT a reply

### ISSUE THREAD

**Issue by StoyanGG** [MicrosoftDocs/msteams-docs#9733]
Recently (sometime this week), a change was made that caused **MessagingExtensionAction action.MessagePayload.ReplyToId** to behave differently.
It now contains a ReplyToId value, when started from the initial Conversation message and that value is the same as the conversation Id (**action.MessagePayload.Id**). Previously, the first conversation message did NOT have a **action.MessagePayload.ReplyToId** value, as it is not actually a reply. This is how I differentiated whether our Teams Messaging extension was started from the initial conversation message or from a reply.

Could you please confirm:
1. Is this a bug? Will the change be reverted to have an empty action.MessagePayload.ReplyToId when it's an initial conversation message and NOT a reply?
2. Should I implement a workaround comparing the values of action.MessagePayload.ReplyToId and action.MessagePayload.Id whether they are the same, to establish that it's the initial conversation message?

**Comment by sayali-MSFT** [comment]
@StoyanGG -Thanks for reporting your issue.
We will check this at our end and will get back to you.

**Comment by Prasad-MSFT** [comment]
Hi @StoyanGG, we checked this and could not be able to repro. Please let us know if this issue still persists at your end or not.
