### ISSUE TITLE
Icon in Activity Feeds in Ms Teams when use graph api send notification

### ISSUE THREAD

**Issue by cuongngoht** [MicrosoftDocs/msteams-docs#9736]
Old behavior:
In **Classical teams**: Send notification and configuration in the manifest file using application permission:
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/40376533/caae54c2-cb3e-4de1-86c5-253c7a0c4cae)
It will be working to show Icon in a manifest zip file.

New behavior:
In **new teams**: Send notification and configuration in the manifest file using application permission to show only icons like that.
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/40376533/1a6a64df-a9d2-4193-9324-91a26affdb30)

Show the question:
How to show icon look like old behavior

**Comment by ChetanSharma-msft** [comment]
Hello @cuongngoht - Thanks for raising your query.
Please confirm whether you are trying it in classic teams or new Teams?

**Comment by ChetanSharma-msft** [comment]
Hello @cuongngoht - Thanks for sharing the information.
We will look into it and let you know the updates.

**Comment by Meghana-MSFT** [comment]
Apologies for the delay, we checked this at our end and it is working fine. We checked with following sample [Microsoft-Teams-Samples/samples/graph-activity-feed-broadcast/nodejs at main · OfficeDev/Microsoft-Teams-Samples (github.com)](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/graph-activity-feed-broadcast/nodejs)

It shows icon given in the manifest. Could you please confirm if it is working for you?
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/81138249/37cf5906-26f3-4b65-be71-b3b511e06aa9)
