### ISSUE TITLE
Feedback - HMAC Validation example

### ISSUE THREAD

**Issue by v-npaladugu** [MicrosoftDocs/msteams-docs#9738]
HMAC validation is not explained well and should include sample code like the rest

Example HMAC for https://learn.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-outgoing-webhook?tabs=verifyhmactoken%2Cdotnet#:~:text=Create%20a%20method%20to%20verify%20the%20Outgoing%20Webhook%20HMAC%20token
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bb9c5bd5-1ac6-dcc8-4ed6-d6aad2432776
* Version Independent ID: 43e90995-bba4-86b6-1f1c-ab749e546a4b
* Content: [Create an Outgoing Webhook - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-outgoing-webhook?tabs=urljsonpayload%2Cdotnet)
* Content Source: [msteams-platform/webhooks-and-connectors/how-to/add-outgoing-webhook.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/webhooks-and-connectors/how-to/add-outgoing-webhook.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **surbhigupta**

**Comment by Meghana-MSFT** [comment]
@v-npaladugu - HMAC is a security token used to authenticate calls between Teams and the designated outside service. It is displayed once you create an outgoing webhook - https://learn.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-outgoing-webhook?tabs=verifyhmactoken%2Cdotnet#:~:text=A%20Hash%2Dbased%20Message%20Authentication%20Code%20(HMAC)%20dialogue%20appears.%20It%27s%20a%20security%20token%20used%20to%20authenticate%20calls%20between%20Teams%20and%20the%20designated%20outside%20service.%20The%20HMAC%20security%20token%20doesn%27t%20expire%20and%20is%20unique%20for%20each%20configuration.

HMAC is used in this sample as well - https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/outgoing-webhook/csharp.

Please share more details if this does not help.

**Comment by v-npaladugu** [comment]
@Meghana-MSFT, can you provide an example like the following

{
    "type": "message",
    "text": "This is a reply!"
}

**Comment by Meghana-MSFT** [comment]
@v-npaladugu - It is not a JSON obj to share an example as you have mentioned. Please check these lines of code for HMAC validation - https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/b0edf727c1e77f62107533b716ece64697cb9291/samples/outgoing-webhook/csharp/Models/AuthProvider.cs#L63
