### ISSUE TITLE
Feedback - expose the onclick method.

### ISSUE THREAD

**Issue by v-npaladugu** [MicrosoftDocs/msteams-docs#9739]
It would be nicer if you exposed the onclick method rather than the button itself so it would be easier to integrate into things like Fluent Menu's, etc

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9acac5e2-58cc-c9be-1dad-95f2f0323142
* Version Independent ID: 9acac5e2-58cc-c9be-1dad-95f2f0323142
* Content: [Share to Teams overview - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/share-to-teams-overview)
* Content Source: [msteams-platform/concepts/build-and-test/share-to-teams-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/build-and-test/share-to-teams-overview.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **surbhigupta**

**Comment by SaiPratap-MSFT** [comment]
@v-npaladugu - Thanks for reporting this. We will check this and update you soon.

**Comment by SaiPratap-MSFT** [comment]
@v-npaladugu  -  Could you please provide more information about this for better understanding

**Comment by v-npaladugu** [comment]
@SaiPratap-MSFT, we have received this as anonymous feedback, and we don't have more information on this feedback.

**Comment by ChetanSharma-msft** [comment]
Raised a feature request on behalf of the anonymous user: https://feedbackportal.microsoft.com/feedback/idea/d2ae4115-27aa-ee11-92bd-0022484eb945

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, please feel free to reopen it, if required.
