### ISSUE TITLE
Typo in Enable SSO for tab app Doc.

### ISSUE THREAD

**Issue by sayali-MSFT** [MicrosoftDocs/msteams-docs#9741]
Doc Link- https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/tab-sso-overview#third-party-cookies-on-ios
- The word **confirm** has a typo, please correct it.
![Screenshot 2023-10-23 181918](https://github.com/MicrosoftDocs/msteams-docs/assets/93527375/7c8fb214-1dc2-45cf-a8ad-d4df88e718f3)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 90fe7a88-a703-1d13-f945-2a15f335721a
* Version Independent ID: 90fe7a88-a703-1d13-f945-2a15f335721a
* Content: [Overview to authentication for tabs using SSO in Teams with Azure AD - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/tab-sso-overview)
* Content Source: [msteams-platform/tabs/how-to/authentication/tab-sso-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/tabs/how-to/authentication/tab-sso-overview.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **surbhigupta**

**Comment by sayali-MSFT** [comment]
@surbhigupta12 -Could you please help us to update the document?

**Comment by v-deabira** [comment]
Hi @sayali-MSFT, it is not a typo. The word is 'conform' as it specifically talks on Privacy and Security. Request you to please remove the doc- enhancement label.
For your ref please: https://www.ahdictionary.com/word/search.html?q=conform
