### ISSUE TITLE
External auth now works in General ring, kindly remove it as a know issue from this page.

### ISSUE THREAD

**Issue by parthiiita** [MicrosoftDocs/msteams-docs#9744]
<img width="546" alt="image" src="https://github.com/MicrosoftDocs/msteams-docs/assets/24573328/6b79dff5-406f-48e5-af50-e82724f769fa">

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4c405ed3-f304-ff58-d32d-108fc725bb6a
* Version Independent ID: 4c405ed3-f304-ff58-d32d-108fc725bb6a
* Content: [Introducing the new Microsoft Teams client - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/resources/teams-updates#known-issues)
* Content Source: [msteams-platform/resources/teams-updates.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/resources/teams-updates.md)
* Service: **msteams**
* GitHub Login: @v-ypalikila
* Microsoft Alias: **lajanuar**

**Comment by sayali-MSFT** [comment]
@parthiiita -Thanks for reporting your issue.
We will check this at our end and update the document accordingly.
