### ISSUE TITLE
[Doc-Enhancement] Environment variable can't be used for Bot id in Teams dev portal

### ISSUE THREAD

**Issue by SubbaReddi** [MicrosoftDocs/msteams-docs#9745]
Hi Team,
if environment variable is used for Bot ids, app save is failing and showing error message as "App failed to update" status code 400. It is not supported to use environment variable for Bot id. So, please add note for the same.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c2ab90ad-0989-85f5-6b10-8ef631252e5c
* Version Independent ID: c2ab90ad-0989-85f5-6b10-8ef631252e5c
* Content: [Manage your apps with the Developer Portal - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/manage-your-apps-in-developer-portal)
* Content Source: [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **surbhigupta**

**Comment by Meghana-MSFT** [comment]
@surbhigupta12 - Could you please help to add above note in the doc.

Note :  It is not supported to use environment variable for Bot id.
