### ISSUE TITLE
Keep selections of ChoiceSet

### ISSUE THREAD

**Issue by jepeal85** [MicrosoftDocs/msteams-docs#975]
1) 
I am sending a ChoiceSet from my bot to an MS teams channel:
![image](https://user-images.githubusercontent.com/54553419/65684049-fa283f00-e05e-11e9-9319-0e4dd6623c8e.png)

2)
The user makes his selection (e.g. selects Car and Train) and clicks the Send button.

3) 
The bot receives the selected values and replies with the message "... You selected Car, Train."_
![image](https://user-images.githubusercontent.com/54553419/65684258-7b7fd180-e05f-11e9-9736-e8a2a19d64ef.png)

4) 
As soon as the channel receives the answer from the bot, the selected values of the Choiceset are deleted (can be seen in the above screenshot).

Is there a way to keep the selections of the Choiceset even after the bot replied?

Thanks

**Comment by Gousia-MSFT** [comment]
@jepeal85 Once you fill the values and submit them all the values filled in the card will be sent to the bot in the activity payload in `activity.value`. However, after submit, all the values are reset. This is the current behavior of cards. It is not possible to show the selected values after sending response.

**Comment by jepeal85** [comment]
Thanks for the quick answer!
