### ISSUE TITLE
Miro integration not working with New Teams client.

### ISSUE THREAD

**Issue by ashishMiro** [MicrosoftDocs/msteams-docs#9768]
Hello Team,

I am Ashish working with Miro and our team is responsible for MsTeams Miro App. With the roll out of the new Teams client we noticed in the new version of Microsoft Teams, we unable to start sharing a Miro board in a Teams meeting although this still woks fine in the "classic" version of Teams. Please find attached screen recording of the issue.

Another question on similar lines - I am aware that Devtools is not supported for new version, is there a way to our application going forward?

https://github.com/MicrosoftDocs/msteams-docs/assets/109524181/0cba2a49-3ac6-44ff-b576-cf60f72d7d35

Kind regards
Ashish

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 19ddf42e-0a47-7717-52d4-e549155480a2
* Version Independent ID: 4bbe9beb-233f-cfd5-097b-f280aab5fde8
* Content: [Microsoft Teams developer community support and feedback - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/feedback)
* Content Source: [msteams-platform/feedback.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/feedback.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by SaiPratap-MSFT** [comment]
Thanks for reporting your issue. We will test this and update you soon.

**Comment by SaiPratap-MSFT** [comment]
@ashishMiro - We are able to repro that issue, we have raised bug for the same. We will inform you once we get any update.

**Comment by ChetanSharma-msft** [comment]
Hello @ashishMiro - Sorry for delay in response.
We have tested the Micro app in both Classic and New teams and it is working fine.

Could you please check and confirm?
