### ISSUE TITLE
Microsoft New Teams is causing Explorer.exe to Crash

### ISSUE THREAD

**Issue by seema313** [MicrosoftDocs/msteams-docs#9773]
[
Dear Support,

Kindly Connect on Microsoft Teams and access my screens and then see the Issue:

****My Question****

Is this Microsoft New Teams Related Issue occurring over Multiple Tenants? If yes, then should we Disable New Teams Feature for the Time being?

****Here are Answers to some of Questions that You might have: -****

- May I know How many Users are having same Issues? 

Answer: This is Across Multiple Sites in our Tenant and many users are facing this Problem now. 

- Is the Issue also happening when you use the Teams on the Web? 

Answer: It’s not Happening on Microsoft Teams Web but it’s only happening on Teams Application

-  I attached the Logs and all the detail of this Issue in below link

]
(https://crescentpk-my.sharepoint.com/:f:/g/personal/seema_kanwal_crescent_com_pk/EoNWO0tyJZBHsmGHaEzOCboB0gUBO1Wi-4hBKJuY8IfG9A?e=UKj4rI)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 19ddf42e-0a47-7717-52d4-e549155480a2
* Version Independent ID: 4bbe9beb-233f-cfd5-097b-f280aab5fde8
* Content: [Microsoft Teams developer community support and feedback - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/feedback)
* Content Source: [msteams-platform/feedback.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/feedback.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by seema313** [comment]
Note:

These are two errors that happen randomly when I check Event Viewer: -

Product: Microsoft Teams Meeting Add-in for Microsoft Office -- Error 1321. The Installer has insufficient privileges to modify this file: C:\Windows\system32\vccorlib140.dll. System Error 5.

Product: Microsoft Teams Meeting Add-in for Microsoft Office -- Error 1321. The Installer has insufficient privileges to modify this file: C:\Windows\SysWOW64\vcruntime140.dll. System Error 5. Event ID:      11321

**Comment by Nivedipa-MSFT** [comment]
@seema313 - We are mainly responsible for Microsoft Teams app development related issues. 

For Microsoft Teams product issues/failures your tenant Admin can reach out to [Microsoft 365 Product Support](https://docs.microsoft.com/en-us/microsoft-365/admin/contact-support-for-business-products?view=o365-worldwide&tabs=online).
