### ISSUE TITLE
Vtiger CRM app not working in new teams client

### ISSUE THREAD

**Issue by vikassaklecha** [MicrosoftDocs/msteams-docs#9776]
Hi team,

Vtiger CRM app on teams is not working, we are not able to see the content when loading inside the tab view.

![image001](https://github.com/MicrosoftDocs/msteams-docs/assets/2158262/71fe33a0-4378-4cea-849a-ad699a074830)

In the tab view the app is loading but the data is not showing up.
![new_teams_client_vtiger_crm_app_issue](https://github.com/MicrosoftDocs/msteams-docs/assets/2158262/93c8e823-2159-4bf2-8a9b-235a69e76aa6)

These are working in Classic and web client.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 19ddf42e-0a47-7717-52d4-e549155480a2
* Version Independent ID: 4bbe9beb-233f-cfd5-097b-f280aab5fde8
* Content: [Microsoft Teams developer community support and feedback - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/feedback)
* Content Source: [msteams-platform/feedback.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/feedback.md)
* Service: **msteams**

**Comment by Meghana-MSFT** [comment]
Thank you for reporting this, we will check this and get back to you.

**Comment by Meghana-MSFT** [comment]
@vikassaklecha - Bug has been raised for this issue, we will keep you posted on the updates. Thank you.

**Comment by vikassaklecha** [comment]
@Meghana-MSFT any ETA on when this will be fixed, our customers are waiting for it

**Comment by Meghana-MSFT** [comment]
Unfortunately, we do not have an ETA to share. We will keep you posted on the updates.

**Comment by author-spirit** [comment]
@Meghana-MSFT It is happening same in our teams extension app.

**Comment by Meghana-MSFT** [comment]
This issue has been resolved, could you please check and confirm once?
