### ISSUE TITLE
Developer Preview missing in latest Teams?

### ISSUE THREAD

**Issue by crrobinson14** [MicrosoftDocs/msteams-docs#9779]
We are trying to debug problem with a Teams Tab app using the instructions at https://learn.microsoft.com/en-us/microsoftteams/platform/resources/dev-preview/developer-preview-intro#enable-developer-preview. However, this feature appears to have been removed from the latest Teams. Is there a way to still access it, and/or download the previous Teams version?

**Comment by Prasad-MSFT** [comment]
@crrobinson14 - Do you mean to say you are not able to get Developer Preview option in Teams T2.1 (New Teams)? 
Were you able to get the option in Teams Classic?
Also, could you please let us know if you have enabled custom app uploading or sideloading for your developer tenant as shown here?
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/62237649/394fbf48-7fd6-41b1-956b-2447ae06ad65)

**Comment by crrobinson14** [comment]
@Prasad-MSFT Yes, this option is not available for me in both Classic and New Teams. I have confirmed the Upload Custom Apps option is enabled (we are writing a custom app so it was required anyway).

**Comment by Prasad-MSFT** [comment]
> @Prasad-MSFT Yes, this option is not available for me in both Classic and New Teams. I have confirmed the Upload Custom Apps option is enabled (we are writing a custom app so it was required anyway).

We have 'Upload Custom App' option enabled and we can see the Developer Preview option in Teams Classic.
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/62237649/954d6d22-919a-40f6-80c7-86faeabb9acc)

However, in New Teams, the option is not available for us as well. We are checking this with engineering team. We will update you once we hear from them. Thanks!

**Comment by crrobinson14** [comment]
@Prasad-MSFT Thank you, it would be very helpful. But can I also report that even in Classic it is not working for me. I have included a screenshot with my version number and my admin panel behind it showing the proper setting enabled.

![image](https://github.com/MicrosoftDocs/msteams-docs/assets/1675563/5e138f9e-193b-4f75-9334-5dcdf00159d2)

**Comment by Prasad-MSFT** [comment]
Thanks @crrobinson14 - We will check with engineering team and will update you accordingly.

**Comment by crrobinson14** [comment]
@Prasad-MSFT Any news on this?

**Comment by Prasad-MSFT** [comment]
Hi @crrobinson14 - Now we are able to see the developer preview option in New Teams. Please do verify at your end and confirm.
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/62237649/3be0d95b-3bfd-42fe-b658-d571274ce6a7)

**Comment by Prasad-MSFT** [comment]
We are closing this issue for now. Please feel free to reopen if required. Thanks!
