### ISSUE TITLE
Task Module not rendering on teams webapp and application

### ISSUE THREAD

**Issue by hellovishal10** [MicrosoftDocs/msteams-docs#9785]
Hi, I am trying to invoke task modules from my bit but it is not rendering . Upon inspecting I am getting following error in console
![Screenshot 2023-10-26 152246](https://github.com/MicrosoftDocs/msteams-docs/assets/149349394/50af3570-9147-4e50-96ac-8c749043f08a)
Unrecognized Content-Security-Policy directive 'prefetch-src'.

**Comment by ChetanSharma-msft** [comment]
Hello @hellovishal10 - Thanks for raising your query.
Could you please verify whether your code has added proper configuration for Content Security Policy (CSP).
Please refer this documentation: https://learn.microsoft.com/en-us/microsoft-edge/extensions-chromium/store-policies/csp?tabs=v2

Please let us know if you need any further help here.

**Comment by hellovishal10** [comment]
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/149349394/3fc5cab1-d37e-4ed2-8091-7eed76750ef0)

**Comment by hellovishal10** [comment]
what should i do in this case?

**Comment by sayali-MSFT** [comment]
@hellovishal10 -Here is related thread, Could you please refer this-https://stackoverflow.com/questions/31211359/refused-to-load-the-script-because-it-violates-the-following-content-security-po

**Comment by sayali-MSFT** [comment]
> ![image](https://user-images.githubusercontent.com/149349394/278998129-3fc5cab1-d37e-4ed2-8091-7eed76750ef0.png)

Here is related thread, could you please refer this-https://stackoverflow.com/questions/31211359/refused-to-load-the-script-because-it-violates-the-following-content-security-po
