### ISSUE TITLE
Task Module not invoking from bot

### ISSUE THREAD

**Issue by hellovishal10** [MicrosoftDocs/msteams-docs#9793]
Hi, I have been trying to invoke task modules from my bot. I have used the nodejs sample of task modules and I am getting the following error.
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/149349394/59dec1cf-689d-4c5c-920c-89dfbc8601e4)

**Comment by ChetanSharma-msft** [comment]
Hello @hellovishal10 - Thanks for raising your query.
Kindly share the code snippets and Teams client on which you are trying.

**Comment by hellovishal10** [comment]
[nodejs (7).zip](https://github.com/MicrosoftDocs/msteams-docs/files/13212244/nodejs.7.zip)
I am using this sample , I had replaced Microsoft AppId and Password and in the field of base url I am just using localhost

**Comment by hellovishal10** [comment]
Need follow up answer and solution for the same. Thanks!!

**Comment by sayali-MSFT** [comment]
@hellovishal10 -We are looking into it.

However, if you have any business-critical issue which need immediate attention, please raise a support request here:  
[https://docs.microsoft.com/en-us/microsoft-365/admin/get-help-support?view=o365-worldwide&tabs=online](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fmicrosoft-365%2Fadmin%2Fget-help-support%3Fview%3Do365-worldwide%26tabs%3Donline&data=05%7C01%7Cv-sadange%40microsoft.com%7C9c58c533cd9243fb839808da9b8c25bd%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637993323623713188%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=DHgm%2B3SHoY2N%2FtxtDdUh1Avao301NA7dqfoyuECgieQ%3D&reserved=0)

**Comment by SaiPratap-MSFT** [comment]
@hellovishal10 -  We tried to repro this issue in classic teams on web. We did'nt find any issue . We are able to get responses for the adaptive cards . Here is the attachment video.

https://github.com/MicrosoftDocs/msteams-docs/assets/146196379/fac98f39-7c80-486e-8196-7b715e2b4d31

**Comment by hellovishal10** [comment]
https://drive.google.com/file/d/1Rku0fEp8LU4aNmY6sO3f4xhvi3AH55VW/view?usp=sharing
Here is my implementation video in web. Could u please guide me where am i doing wrong? Thanks .

**Comment by SaiPratap-MSFT** [comment]
Hello @hellovishal10   Could you please go through this teams sample  [https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/bot-task-module/nodejs](url)   , where you will find how to set up your code and the way to implement it. Please keep keen attention to Readme section
