### ISSUE TITLE
how to disable tab conversation?

### ISSUE THREAD

**Issue by imdat1guy** [MicrosoftDocs/msteams-docs#981]
I would to disable/remove the conversation/chat in my tabs in my Microsoft Teams app. This is very crucial for my use case.

**Comment by clearab** [comment]
If your app contains both a bot and a tab that have the personal scope, they personal app will contain a conversation tab. The only way to remove it would be to remove the bot from your app (you could still have a messaging extension).

**Comment by imdat1guy** [comment]
I am referring to this:
![image](https://user-images.githubusercontent.com/49979350/65908713-0d793880-e3d8-11e9-9101-856e0f9a6484.png)

and not the conversations tab. My app does not contain a bot.

**Comment by clearab** [comment]
Oh, my apologies. That is also not an extensible/configurable part of the platform.

**Comment by imdat1guy** [comment]
No worries. Is there any plans to have this configurable in the future?

**Comment by clearab** [comment]
Not currently. If you're interested in seeing it added to the platform, please add it to our User Voice page: https://microsoftteams.uservoice.com/forums/555103-public (use the Apps, Connectors, Messaging Extensions category).
