### ISSUE TITLE
[Feedback] How to add @mention to the text message without using any sorts of cards

### ISSUE THREAD

**Issue by v-preethah** [MicrosoftDocs/msteams-docs#9812]
@Wajeed-msft 

Received feedback from where user wanted to add @mention on plain text sent, without using any card.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 90ff2a84-a8bc-9259-d37d-622b102df75b
* Version Independent ID: e3b53e27-2946-189c-623b-9df704ea8f12
* Content: [Create an Incoming Webhook - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-incoming-webhook?tabs=dotnet)
* Content Source: [msteams-platform/webhooks-and-connectors/how-to/add-incoming-webhook.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/webhooks-and-connectors/how-to/add-incoming-webhook.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **surbhigupta**

**Comment by Meghana-MSFT** [comment]
@v-preethah - If the user is using incoming webhook then messages will be sent as cards only. 

If the user wants to add @mention on plain text, without using any card they can follow the below approaches -

1. Using Bot - https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/channel-and-group-conversations?tabs=dotnet#user-mention
2. Using Graph - https://learn.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-1.0&tabs=http#example-2--a-user-in-a-channel-message
