### ISSUE TITLE
German Translation in New Teams Client is not correct

### ISSUE THREAD

**Issue by nicuberger** [MicrosoftDocs/msteams-docs#9819]
Free at "time" is translate with Kostenlos von "time". Kostenlos means for free. It should be "Frei" or "Verfügbar".
Please correct that asap

**Comment by Meghana-MSFT** [comment]
We are mainly responsible for Microsoft Teams app development related issues.
For Microsoft Teams product issues/failures your tenant Admin can reach out to [Microsoft 365 Product Support](https://docs.microsoft.com/en-us/microsoft-365/admin/contact-support-for-business-products?view=o365-worldwide&tabs=online).
For general questions about Microsoft Teams please post your question on [Microsoft Teams Community](https://answers.microsoft.com/en-us/msteams/forum).

**Comment by jme107** [comment]
Unfortunately, this is not a Tenant setting and cannot be rectified by Teams Support. This is an incorrect translation within the Teams app and leads to misunderstandings for many companies, as some already think that they will have to pay for teams and calls in the future. It would be good if the translation in Teams, which is used by several million people, was correct.

I have already received requests from several companies that users are unsure and that there will be an increase in inquiries. There seems to be a lack of understanding of the impact this has on the German-speaking market.  So please fix this incorrect translation as soon as possible. 

![image](https://github.com/MicrosoftDocs/msteams-docs/assets/55663282/405c0891-09d7-459a-a2c1-fda930b5be84)

**Comment by Meghana-MSFT** [comment]
We have raised this question on Microsoft QnA and added required tags. https://learn.microsoft.com/en-us/answers/questions/1419799/german-translation-in-new-teams-client-is-not-corr

**Comment by ChetanSharma-msft** [comment]
Please track the issue in Microsoft QnA forum.

We are closing this issue for now, please feel free to reopen it, if required.
