### ISSUE TITLE
How to change tab name with reconfiguration?

### ISSUE THREAD

**Issue by imdat1guy** [MicrosoftDocs/msteams-docs#982]
I would like to automatically have the tab name change when a user reconfigures that tab and not have him manually renaming it.

**Comment by Gousia-MSFT** [comment]
@imdat1guy Could you please try [updating an existing tab instance](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/tabs/tabs-update-remove#updating-an-existing-tab-instance) and let us know if you face any issues
