### ISSUE TITLE
Wrong dialling (without +)

### ISSUE THREAD

**Issue by cmarguth** [MicrosoftDocs/msteams-docs#9822]
When I dial a telephone number from contacts in international format +41 12 345 67 89, only 41 12 345 67 89 (without +) is dialled.

**Comment by Meghana-MSFT** [comment]
We are mainly responsible for Microsoft Teams app development related issues.
For Microsoft Teams product issues/failures your tenant Admin can reach out to [Microsoft 365 Product Support](https://docs.microsoft.com/en-us/microsoft-365/admin/contact-support-for-business-products?view=o365-worldwide&tabs=online).
For general questions about Microsoft Teams please post your question on [Microsoft Teams Community](https://answers.microsoft.com/en-us/msteams/forum).

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, please feel free to reopen it, if required.
