### ISSUE TITLE
"Problem Reaching this app" error (similar to closed issue #4249)

### ISSUE THREAD

**Issue by tgainey** [MicrosoftDocs/msteams-docs#9823]
Published version 5.3.1.

I'm using the app via Teams online.  We were able to use the app a week ago, and now receiving the following page:

![CC error 11323](https://github.com/MicrosoftDocs/msteams-docs/assets/143223810/65a6f4a7-610a-4b22-9a21-4c7a40556cb2)

Cleared browser history and no change.

**Comment by Meghana-MSFT** [comment]
Are you referring to this https://github.com/MicrosoftDocs/msteams-docs/issues/4249? Could you please let us know if you are seeing any console errors? We could not find this app in app store. Is this a custom app developed by you?

**Comment by tgainey** [comment]
please close.  I posted in the wrong project.  thank you

**Comment by Meghana-MSFT** [comment]
Thank you for confirmation.
