### ISSUE TITLE
Teams Bot unable to connect

### ISSUE THREAD

**Issue by gykung** [MicrosoftDocs/msteams-docs#9824]
I run an internal chatbot, created using bot framework and delivered via ngrok. It is unable to be used on the New Teams app on Windows.  Is there any setting I need to change on Azure? I couldn’t find any documentation on this, including the list of known issues (https://learn.microsoft.com/en-us/microsoftteams/new-teams-known-issues and https://learn.microsoft.com/en-us/microsoftteams/platform/resources/teams-updates#known-issues).

**Comment by sayali-MSFT** [comment]
@gykung- Thanks for reporting your issue.
We will check this at our end and will get back to you.

**Comment by sayali-MSFT** [comment]
@gykung -We are checking this with the internal team, if it is supported to new teams or not and update the document accordingly.

**Comment by gykung** [comment]
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/70024742/0ff586a9-ca0c-423a-ae67-fc3bc532f53f) I don't have a particular repro for this as it is not a coding issue. The same bot built on bot framework, Python, delivered via ngrok, works perfectly on Teams Classic, but does not work on New Teams (see screenshot).

**Comment by sayali-MSFT** [comment]
@gykung -Here is related thread-https://github.com/MicrosoftDocs/msteams-docs/issues/9743
We have already raised bug for the same, we will let you know once we have any update on this.

**Comment by sayali-MSFT** [comment]
@gykung - Could you please confirm, are sideloading enabled in your tenant?

 If not, then this is the default behavior.

**Comment by gykung** [comment]
Resolved, see solution at https://github.com/MicrosoftDocs/msteams-docs/issues/9743

I suggest that the following documentation to be updated: https://learn.microsoft.com/en-us/azure/bot-service/channel-connect-teams?view=azure-bot-service-4.0#test-your-bot-in-teams
