### ISSUE TITLE
Defined manifest parameters in documentation table are wrong

### ISSUE THREAD

**Issue by ChetanSharma-msft** [MicrosoftDocs/msteams-docs#9826]
Defined manifest parameters in table are wrong:
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/59052547/f59f7de3-7cd8-4f49-904b-3f53eba97c5a)

composeExtension.type => composeExtensionType
composeExtension.apiSpecificationFile => composeExtensions.apiSpecificationFile 
composeExtension.command.ID => composeExtensions.commands.id
composeExtension.command.context => composeExtensions.commands.context
composeExtension.command.parameters => composeExtensions.commands.parameters
composeExtension.command.apiResponseRenderingTemplateFile => composeExtensions.commands.apiResponseRenderingTemplateFile

Kindly check and update the parameters.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f1e3d44d-9e64-8332-dff8-26595726898c
* Version Independent ID: f1e3d44d-9e64-8332-dff8-26595726898c
* Content: [Build message extensions using API - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/api-based-overview#update-app-manifest)
* Content Source: [msteams-platform/messaging-extensions/api-based-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/messaging-extensions/api-based-overview.md)
* Service: **msteams**
* GitHub Login: @v-ypalikila
* Microsoft Alias: **anclear**

**Comment by surbhigupta12** [comment]
Addressed in PR #9838
