### ISSUE TITLE
The deom（Contoso Talent）  app  not save apge

### ISSUE THREAD

**Issue by luozewei** [MicrosoftDocs/msteams-docs#9827]
[Enter feedback here]

![image](https://github.com/MicrosoftDocs/msteams-docs/assets/20294939/b1c1890a-c637-4d27-a6b0-df18351e7688)
 The demo provided on the page cannot be used normally, and we cannot configure it ourselves and use it frequently.
Where can I get the latest documents or demo examples?
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 41c93c1e-c426-148c-a545-f8bd5b3763ff
* Version Independent ID: afcc83c4-12c0-bab6-1cec-61ac463b4f60
* Content: [Add Teams tab to SharePoint - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/tabs-in-sharepoint)
* Content Source: [msteams-platform/tabs/how-to/tabs-in-sharepoint.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/tabs/how-to/tabs-in-sharepoint.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **surbhigupta**

**Comment by sayali-MSFT** [comment]
@luozewei -Thanks for reporting your issue.
We will check this at our end and will get back to you.

**Comment by sayali-MSFT** [comment]
@luozewei -Could you please look into this sample-https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/tab-channel-group/spfx
