### ISSUE TITLE
How to post an update message in conversation tab after an event occurs in my app tab?

### ISSUE THREAD

**Issue by imdat1guy** [MicrosoftDocs/msteams-docs#983]
Is there a simpler way to post a message other than using the graph API for creating a message? 
Also that API is in beta

**Comment by clearab** [comment]
To post a message to Teams you can either use the Graph endpoint, or proactive messaging with a bot (https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/bots/bot-conversations/bots-conv-proactive)

**Comment by clearab** [comment]
You can also use an Incoming Webhook, which creates an endpoint you can post a card to. They need to be configured for each channel you want to post messages to.
