### ISSUE TITLE
Handle Adaptive card action style in Microsoft Teams

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#9837]
Copied bug from: https://github.com/OfficeDev/TeamsFx/issues/10271 

**Details from original post:**
**Is your feature request related to a problem? Please describe.**
It is currently impossible to use style to visually indicate to the user which button is used to confirm or cancel (for example). 
This would also make the card more visually interesting.

**Describe the solution you'd like**
Handle positive and descructive style in Teams---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b743e43d-95cc-3d1e-b142-31a16369f97e
* Version Independent ID: b743e43d-95cc-3d1e-b142-31a16369f97e
* Content: [Teams Toolkit Overview - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/toolkit/teams-toolkit-fundamentals)
* Content Source: [msteams-platform/toolkit/teams-toolkit-fundamentals.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/teams-toolkit-fundamentals.md)
* Service: **msteams**
* GitHub Login: @zyxiaoyuer
* Microsoft Alias: **zhany**

**Comment by Prasad-MSFT** [comment]
@Wildarth - Currently this feature is not supported. 
To achieve your requirements, we recommend you give your feedback in [Teams Feedback Portal](https://feedbackportal.microsoft.com/feedback/forum/ad198462-1c1c-ec11-b6e7-0022481f8472).
