### ISSUE TITLE
Mobile Clients - Timelines

### ISSUE THREAD

**Issue by icelandgrecian** [MicrosoftDocs/msteams-docs#984]
When you say 'Full support for tabs on mobile clients is coming soon', do you have any more detailed timeline on this, e.g. is it 1 week, 3 months or a year?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f5dd248-ec28-4bc2-32e6-2e6072a5eedf
* Version Independent ID: 4c45b690-0a35-d460-54fb-c0b61a2c5e8c
* Content: [Tabs on mobile - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/design/framework/tabs-mobile)
* Content Source: [msteams-platform/resources/design/framework/tabs-mobile.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/resources/design/framework/tabs-mobile.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Gousia-MSFT** [comment]
@icelandgrecian We are planning to release the support for personal apps and sideloaded, on mobile over the end of October.

**Comment by clearab** [comment]
We don't have a specific timeline to share currently. We want to give developers ample time to add mobile friendly tabs to existing apps before we make this the default behavior.
