### ISSUE TITLE
Getting an error while bulk-adding users

### ISSUE THREAD

**Issue by apachumbre** [MicrosoftDocs/msteams-docs#9843]
Hello,

I am writing to report an issue - Getting an error while bulk-adding users in the new version of Microsoft Teams using the extension- "Refined Microsoft Teams". We have been using this extension for over a year, and since last week, it has stopped working.

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 19ddf42e-0a47-7717-52d4-e549155480a2
* Version Independent ID: 4bbe9beb-233f-cfd5-097b-f280aab5fde8
* Content: [Microsoft Teams developer community support and feedback - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/feedback)
* Content Source: [msteams-platform/feedback.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/feedback.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by ChetanSharma-msft** [comment]
Hello @apachumbre - Could you please elaborate more on your issue and share the steps.
