### ISSUE TITLE
messageBack text property isn't working for the emulator 

### ISSUE THREAD

**Issue by xtianus79** [MicrosoftDocs/msteams-docs#985]
{
  "buttons": [
    {
    "type": "messageBack",
    "title": "My MessageBack button",
    "displayText": "I clicked this button",
    "text": "User just clicked the MessageBack button",
    "value": "{\"property\": \"propertyValue\" }"
    }
  ]
}

text isn't being sent back to the bot

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28d1cbcc-9670-6eb3-d65a-5c30d307784a
* Version Independent ID: 243e29b8-afbc-7d21-1d24-18f58619af60
* Content: [Add card actions in a bot - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/cards/cards-actions#openurl)
* Content Source: [msteams-platform/concepts/Cards/cards-actions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/Cards/cards-actions.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Gousia-MSFT** [comment]
@xtianus79 Does this work in Microsoft Teams? Could you please share a screenshot of the difference you see in Teams vs Emulator?

**Comment by xtianus79** [comment]
@Gousia-MSFT teams, I don't have access to the teams channel
