### ISSUE TITLE
[New Teams on Mac] Not able to get media device list (Permission denied by system, empty label or device id)

### ISSUE THREAD

**Issue by kafka-yu** [MicrosoftDocs/msteams-docs#9852]
Hi team,

We found an issue when developing our MS Teams tab app on new Teams client on macOS. 

Steps to reproduce:
1. Open an Tab app in new Teams client
2. Enable the Media permission
3. Open console, type the following JS script
```js
await navigator.mediaDevices.getUserMedia({audio: true})
```
4. It says: 
> Uncaught DOMException: Permission denied by system

5. Then type the following script:
```js
await navigator.mediaDevices.enumerateDevices()
``` 
No any label or deviceId is returned. 
 

<img width="666" alt="image" src="https://github.com/MicrosoftDocs/msteams-docs/assets/3942409/515e6941-79bf-4a84-a74c-d47a22e076ad">

<img width="935" alt="image" src="https://github.com/MicrosoftDocs/msteams-docs/assets/3942409/653aed9a-f518-4ba8-bcbd-6395052898e1">

<img width="598" alt="image" src="https://github.com/MicrosoftDocs/msteams-docs/assets/3942409/c2888f80-df58-40d5-a704-df4a58721d29">

New Teams version:
Microsoft Teams (work or school)
Version 23272.2708.2452.9689 (23272.2708.2452.9689)

Would anyone help check? Thanks.

**Comment by Prasad-MSFT** [comment]
Hi @kafka-yu - Could you please let us know if this issue is specific to Mac only or does it happen in Windows also?

**Comment by kafka-yu** [comment]
@Prasad-MSFT 
Yes only Mac. Windows is good.
<img width="593" alt="image" src="https://github.com/MicrosoftDocs/msteams-docs/assets/3942409/431e51f2-1a18-4254-b1d5-90dd7771d07f">

**Comment by kafka-yu** [comment]
I think I should forward this issue ticket to "https://github.com/OfficeDev/microsoft-teams-library-js/issues", it is better place?

**Comment by ChetanSharma-msft** [comment]
Hello @kafka-yu - Please confirm which specific Teams JS library version you are using?

**Comment by kafka-yu** [comment]
@ChetanSharma-msft
We're using 2.5.0. But we invoke the browser's API, not from the Teams JS SDK yet.

**Comment by kafka-yu** [comment]
hello team, is there any update?

**Comment by Prasad-MSFT** [comment]
Hi @kafka-yu - We have raised a bug for this issue. We will inform you once we get any further update from engineering team. Thanks!

**Comment by Prasad-MSFT** [comment]
Hi @kafka-yu - We got update from engineering team that, "From the console logs, the machine/OS itself hasn't provided permission to the app. It's apparent with the error "denied by the system"

If our permissions pipeline rejects a request, the error message shown is:
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/62237649/33dfd1ea-2494-4596-a787-b3511b6e1df2)

macOS needs to provide Teams permissions to allow media (camera/microphone)

**Comment by kafka-yu** [comment]
Thanks for reply.

> macOS needs to provide Teams permissions to allow media (camera/microphone)

The only permission setting on macOS is as below. We have same setting for the classic teams client.

<img width="780" alt="image" src="https://github.com/MicrosoftDocs/msteams-docs/assets/3942409/7d71aaf7-e801-4df4-876b-218395c3922c">

Not just my Mac, but my colleagues also meet this situation.  

@Prasad-MSFT

**Comment by Prasad-MSFT** [comment]
Thanks @kafka-yu - We informed the same to engineering team. Once we get further update, we will inform in this thread.
Thanks!

**Comment by Prasad-MSFT** [comment]
Hi @kafka-yu - Engineering team tested on Mac and Windows, the media list returned for them, and it looks fine.
Windows:
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/62237649/5f5124c5-71e8-45e1-a18c-df60c8e6bf3d)

Mac: 
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/62237649/3a647d0b-e193-4ac3-8b30-0d6c09f73d39)

Looks it either denied by the system or specific to the app issue. Is this still repro-able? Which app was used for testing? 
Could you please investigate for any errors within the app? Additionally, ensure that you are using the latest version of Teams.
