### ISSUE TITLE
subEntityId is cashing forever in New Teams version

### ISSUE THREAD

**Issue by AnnaBondar4** [MicrosoftDocs/msteams-docs#9859]
[Enter feedback here]

We're developing the Breakthru app, the third-party app in Teams. We have an issue in the New Teams Beta version. 

On one of the tabs - on Play tab the user can see the experience/video streaming, the user can choose and start playing different moods - sets of experiences/videos, when the video ended or closed the user is redirected to another tab. If the user comes back to Play tab he usually sees the circle where he can choose another mood. And all is working well in the old Classic Teams version. But in the new Teams version when the user comes back to the Play tab from any other tab he sees the previously played mood, he doesn't see the circle with the choice, he always sees the previous mood playing and can't do anything with that, only can close it, but can't choose another mood. 

We tried to fix that on our side, but couldn't do anything. We see that **subEntityId** is cashing forever in Teams.
It happens on MacOS Monterey, Version 12.6.5 and on Windows 10.

Could you please help with that?

This issue is very critical as the proper functioning of the Play tab, choosing the moods and running the videos properly is the key feature of our application.

Thank you! 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 19ddf42e-0a47-7717-52d4-e549155480a2
* Version Independent ID: 4bbe9beb-233f-cfd5-097b-f280aab5fde8
* Content: [Microsoft Teams developer community support and feedback - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/feedback)
* Content Source: [msteams-platform/feedback.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/feedback.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Prasad-MSFT** [comment]
Hi @AnnaBondar4 - Could you please share the deployed sample manifest, so that we can check once from our end?

**Comment by AnnaBondar4** [comment]
Hello, 

Sending the latest build and the manifest as a separate file.

[manifest.json](https://github.com/MicrosoftDocs/msteams-docs/files/13310021/manifest.json)
[breakthru-prod-1.27.1.zip](https://github.com/MicrosoftDocs/msteams-docs/files/13310023/breakthru-prod-1.27.1.zip)

**Comment by Prasad-MSFT** [comment]
Hi @AnnaBondar4 - We are able to repro this issue in Windows. We have raised a bug for the same. We will inform you once we get any further update from engineering team. 

Thanks!

**Comment by AnnaBondar4** [comment]
Hi @Prasad-MSFT 

Thank you! Looking forward to hearing from you.

**Comment by AnnaBondar4** [comment]
Hello @Prasad-MSFT 

Is there any update?

**Comment by Prasad-MSFT** [comment]
Hi @AnnaBondar4 - Are you still facing this issue? Is it in Windows or MacOS?
Because now it's working fine for us on checking with Windows New Teams client with version - 49/23113028718 and could see that it goes back to circle with choice.

**Comment by AnnaBondar4** [comment]
Hi @Prasad-MSFT 
Yes we're still facing this issue both on Windows and MacOS.
MacOS New Teams client version is 50/24011204001
Windows New Teams client version is 49/23113028706

**Comment by Jocelynncanzoneri** [comment]
What do you mean he is cashing forever.  And how can I cash out on anything
I do?  Is there an administer controlling asset.  If there name is not
jocelynn canzoneri report it to me and to authorities or who handles it.

**Comment by Prasad-MSFT** [comment]
Hi @AnnaBondar4 - The issue seems to be fixed now in New Teams. Please do verify.
```
Tested in Microsoft Teams version 24067.2900.2748.830.
The client version is 49/24030714300.
```

**Comment by Jocelynncanzoneri** [comment]
What does this mean.  Who's cash my stuff.

**Comment by Prasad-MSFT** [comment]
We are closing this issue for now. Please feel free to reopen if required. 

Thanks!
