### ISSUE TITLE
Bug in Set-teams cmdlet - GiphyContentRating

### ISSUE THREAD

**Issue by weq** [MicrosoftDocs/msteams-docs#986]
There is a bug with the Set-Team cmdlet.

If I run `get-team -GroupId dbeda73c-c317-42f5-8fe1-9aa3f159c1a4 | select -ExpandProperty GiphyContentRating` it returns "strict".
But if you then wish to alter this to "moderate", set-team fracks things up.
`Set-Team -groupid dbeda73c-c317-42f5-8fe1-9aa3f159c1a4 -GiphyContentRating moderate` doesn't change from strict to moderate, it simply "does" nothing it would seem. However if you try this `Set-Team -groupid dbeda73c-c317-42f5-8fe1-9aa3f159c1a4 -GiphyContentRating strict` it will change the GiphyContentRating to moderate.

I've had others in the PowerShell Community test and verifiy the issue of this bug.
So I recon you have an enumration issue some place in the module. Time to Open source this module?

Stolen screenshot from @brettmillerb , thanks.
![teams_3](https://user-images.githubusercontent.com/16988742/65952538-5b2a8b00-e442-11e9-8d9b-bb2d81c9ecca.png)

**Comment by Wajeed-msft** [comment]
@weq - Just to isolate the problem, could you please try [Update team](https://docs.microsoft.com/en-us/graph/api/team-update?view=graph-rest-1.0&tabs=http) in [Graph Explorer](https://developer.microsoft.com/en-us/graph/graph-explorer) and see if you are getting the same results?

**Comment by weq** [comment]
@Wajeed-msft I'm afraid I can't. It seems I don't have the correct permissions in our tenant for this API I suspect. We use PIM for management so it might be that prevents be from using the API directly?

Including a screenshot in case I've done something wrong and you might notice it.
![image](https://user-images.githubusercontent.com/16988742/66305500-b86d8300-e8ff-11e9-8622-1a83c65798ea.png)

**Comment by Wajeed-msft** [comment]
Could you please try waiting for some time before calling get-Team command? This to confirm if you this is happening due to any cache issue. Also, you should be able to get the request/response details if you use Fiddler.

**Comment by weq** [comment]
@Wajeed-msft It would seem like you are correct yes. So used to everything being in real time sync that I got blinded I guess. This may be closed. It works "faster" in my personal experience now however, so if there was some latency issues on certain APIs might also have caused this.

Guess we close this now.
