### ISSUE TITLE
Add more scopes for User Consent in Teams App

### ISSUE THREAD

**Issue by LALITAMITTAL18** [MicrosoftDocs/msteams-docs#9864]
By default when you use microsoftTeams.authentication.getAuthToken(), User is asked to give consent for Profile, Offline_Access, Email and OpenId. I would like to extend this with more Graph API permissions as My Teams App is multi-tenant and I dont want only admin to grant consent for all permission required but rather user can grant permissions and continue using the app. Can anyone please help me how is it possible? 

Right now I am following this code:

 Get Teams Token using :

```
microsoftTeams.authentication.getAuthToken().then((result) => {
    //result contains the id token
            console.log(result);
        })
```

Exchange the token ID with the server-side token:
```
IConfidentialClientApplication app = ConfidentialClientApplicationBuilder.Create(<"Client id">)
                                                .WithClientSecret(<"Client secret">)
                                                .WithAuthority($"https://login.microsoftonline.com/<"Tenant id">")
                                                .Build();
            try
            {
                var idToken = <"Client side token">;
                UserAssertion assert = new UserAssertion(idToken);
                List<string> scopes = new List<string>();
                scopes.Add("https://graph.microsoft.com/User.Read");
                // Acquires an access token for this application (usually a Web API) from the authority configured in the application.
                var responseToken = await app.AcquireTokenOnBehalfOf(**scopes**, assert).ExecuteAsync();
                return responseToken.AccessToken.ToString();
            }
            catch (Exception ex)
            {
                return ex.Message;
            }
        }
```

If I try to exchange token without admin consent, I get below error : 

AADSTS65001: The user or administrator has not consented to use the application with ID 'XXXX' named 'XXX'. Send an interactive authorization request for this user and resource.

**Comment by Prasad-MSFT** [comment]
@LALITAMITTAL18 - Your app can obtain consent for Graph permissions globally from the tenant administrator, or individually per user. If you want to ask the user for consent for your app to access their data, you must include the `prompt=consent` property in your query-string-parameter to Azure AD. Instead of `?scope={scopes}`, use `?prompt=consent&scope={scopes`}. Ensure that the `{scopes}` property includes all the scopes you're prompting the user for.

**Comment by LALITAMITTAL18** [comment]
See in that case you have to show user consent prompt 2 times to the user. That’s not good user experience. I want to include user consent with additional permission in default consent pop up which appears when user start using the app for the first time. 

My app uses another login provider. Hence I am using silent authentication in tabs , showing again a login prompt and user consent screen is confusing for the customers. And that also you need to redirect user to the new browser leaving team’s chrome. That’s really bad user experience. 

If it’s not possible to include the additional scope in default user consent screen , I would prefer to show consent screen in teams context. I really don’t want user to redirect in new window.

**Comment by Prasad-MSFT** [comment]
@LALITAMITTAL18 - We will check this with engineering team and will update you.

**Comment by Prasad-MSFT** [comment]
Hi @LALITAMITTAL18 - We got update that "it's not possible today for Teams to trigger the consent prompt for downstream Graph scopes on behalf of the app". To achieve your requirements, we recommend you give your feedback in 
[Teams Feedback Portal](https://feedbackportal.microsoft.com/feedback/forum/ad198462-1c1c-ec11-b6e7-0022481f8472).

**Comment by LALITAMITTAL18** [comment]
Yes, that’s eventually the solution I am implementing. I am separating permissions for user and admin consent. Replacing some graph api with api that can be work with user consent. But now I am stuck with Redirect URL restriction.

 ```
try
 {
     UserAssertion assert = new UserAssertion(token);

     var tokenResponse = await app.AcquireTokenOnBehalfOf(_settings.GraphApiPermissions.RequiredDelegatedScopes, assert).ExecuteAsync();
     return tokenResponse.AccessToken;

 }
 catch (Exception exc)
 {
     if (exc is MsalUiRequiredException || exc.InnerException is MsalUiRequiredException)
     {
         string sUrl = await GetAuthenticationUrlForConsent(app, _settings.GraphApiPermissions.UserConsentScopes, tenantId);
         _navigationManager.NavigateTo(sUrl);
     }
     _logger.LogError("Failed [{ServiceName} GetOnBehalfOfUserTokenAsync]. Tenat : {tenant}, User UPN {upn} Reason: {message}", nameof(GraphAuthenticationStateManager), tenantId, JWTHelper.GetUserEmailfromTeamsToken(token), exc.Message);
     return null;
 }
```


I am using Navigation manager to redirect user inside Teams App, but it refused to connect with login.microosft.com in Teams chrome. Sadly I have to try JSInterop for opening the url in new browser.  and do user consent. It is becoming really bad user experience.

![image](https://github.com/MicrosoftDocs/msteams-docs/assets/51710902/f1ded99f-e61d-4f39-8e86-e64799a9b93c)

**Comment by LALITAMITTAL18** [comment]
I also tried with JSInterop and I get this error after granting consent, can you please help what I am doing wrong.:

**AADSTS9002325: Proof Key for Code Exchange is required for cross-origin authorization code redemption.**

I am building the app like this:

```
var app = ConfidentialClientApplicationBuilder.Create(_clientCredentials.ClientId)
                                                   .WithClientSecret(_clientCredentials.ClientSecret)
                                                   .WithAuthority($"https://login.microsoftonline.com/{tenantId}")
                                                   .Build();
```

Getting the url like this:
```
  Uri url = await app.GetAuthorizationRequestUrl(graphScopes)
         .WithPrompt(Prompt.Consent)
          .WithAuthority($"https://login.microsoftonline.com/{tenantId}")
          .WithRedirectUri(_navMagager.BaseUri)
          .ExecuteAsync(CancellationToken.None)
         .ConfigureAwait(false);
```

**Comment by LALITAMITTAL18** [comment]
I am able to redirect user in new browser and get the consent. After consent, the user is redirected to redirect url. 

How can I send an event to Teams App - Static tab that the user has granted consent and reload the page.

**Comment by ydogandjiev** [comment]
@LALITAMITTAL18, you have two options for showing the consent flow to the user:
1. Use the authentication popup as documented here (this will open within Teams):
https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-tab-aad?tabs=teamsjs-v2#initiate-authentication-flow
2. Use the external auth flow (this takes the user to the browser for the login/consent flow and then deep links them back in to Teams once that's complete):
https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-oauth-provider

**Comment by LALITAMITTAL18** [comment]
I can’t use the first one because I have another authentication provider. 

I am using the second one which redirect user to external browser, but there is no way to tell the tab from where the auth flow started, that it’s finished and can reload the page.

**Comment by ydogandjiev** [comment]
From your auth callback page in the external browser, you need to deep link back into Teams which will then invoke the notifySuccess calback you passed to the authenticate API when starting the auth flow. That's described in steps 7 and 8 in [the docs](https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-oauth-provider):
<img width="810" alt="image" src="https://github.com/MicrosoftDocs/msteams-docs/assets/3357245/f568f457-682e-417e-8025-f3dde2124cfd">

**Comment by LALITAMITTAL18** [comment]
I see this in the article - 

You can add authentication to external browsers for tabs in mobile only.
Use the beta version of TeamsJS to leverage the functionality. Beta versions are available through [NPM](https://www.npmjs.com/package/@microsoft/teams-js/v/1.12.0-beta.2)

My app is on production, I can’t use beta version. And also it’s not just mobile.

I am happy that at least in beta version this started coming. I will check this out but whybit is supported only on mobile or did I understand wrong.

**Comment by ydogandjiev** [comment]
That note is stale. I have opened an issue here to track removing it:
https://github.com/MicrosoftDocs/msteams-docs/issues/9923

External auth is supported across all Teams Clients and is available in the latest producition version of the App SDK.

**Comment by LALITAMITTAL18** [comment]
Thanks a lot Yuri. Let me test this tomorrow.

**Comment by LALITAMITTAL18** [comment]
Hi Team, I am able to get the user consent within Team app. Thanks a lot for the help.
