### ISSUE TITLE
Deep link from a Bot to a Channel message?

### ISSUE THREAD

**Issue by vman** [MicrosoftDocs/msteams-docs#987]
Is there a way to create a deep link to a channel message from within a Bot? So I want to show and Adaptive card from the Bot and on it, want to have an OpenUrl action. When the user will click on the action, they should be taken to a particular Teams message in a channel. Is there something in the Teams Bot builder or Bot Framework for this already? I have the `ConversationReference` of the message. Just need a a way to link to the message from it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a891841a-a110-d18e-25c1-fc29e7d4a5e3
* Version Independent ID: c1a11eb8-00d1-e1d2-1e9d-71d059a6478a
* Content: [Create deep links - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/deep-links#deep-linking-to-a-chat)
* Content Source: [msteams-platform/concepts/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/deep-links.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Gousia-MSFT** [comment]
@vman Yes, it is possible to deeplink to a channel message from a bot. But currently we do not have any document to share with you. Could you please try getting the link of a message in the channel using "Copy link" (see the image attached to get link) and use that format to generate your deeplink?
![image](https://user-images.githubusercontent.com/45553518/66118724-bd2af200-e5f4-11e9-89da-f9067e85aede.png)
Please let us know if that does not help you.

**Comment by vman** [comment]
Thanks @Gousia-MSFT, I tried to do that but but the links contains the message id as well. E.g. `https://teams.microsoft.com/l/message/<team_internal_id>/<message_id>?tenantId=<tenant_id>` and I have confirmed it internally that the message id is not yet available from within the Bot Framework as of now.

**Comment by marknettle** [comment]
The element of the URL you have listed as <message_id> is the timestamp (milliseconds past epoch). You can deep link to a reply as

https://teams.microsoft.com/l/message
/<team_id>@thread.skype
/<reply_timestamp>
?tenantId=<tenant_id>
&groupId=<group_id>
&parentMessageId=<parent_timestamp>
&teamName=<team_name>
&channelName=<channel_name>
&createdTime=<reply_timestamp>

Some elements can be left out, and if the timestamps are out by a bit (e.g. you generated them from the Bot), it should at least get you close to where you want to be in the correct channel.
