### ISSUE TITLE
64bit version of new MS Teams breaks screenshare in Azure Cloud PC environment, 32bit version works fine.

### ISSUE THREAD

**Issue by Hotpocketdeath** [MicrosoftDocs/msteams-docs#9874]
Hello,  I'm not sure if this is the right place to report this issue, but it's the closest I could find.

My company recently moved our users from an old Citrix VDI system to a newer Azure Cloud PC environment.  We needed to do this to support AVD workstations on Windows11 and for numerous other reasons.

The New Teams has rolled out to our AVD users and we've been receiving complaints that they lost the option to screenshare in meetings.

We were able to reproduce the issue when using the 64bit client of the new MS Teams.  

x64 version
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/43794044/bfa2d0ae-4721-40cc-8486-3e9f580ebefc)

And it was dumb luck that we tested the 32bit version because Microsoft only had the 32bit version available to download from their website.

x86 version
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/43794044/15953f62-995f-4f2b-84d4-6c420d290e7b)

Notice the icon for screenshare is missing from the 64bit version, but present in the 32bit version. 

And when in a Teams call, the 64bit version does allow you to share your screen, but only at a per window level.  If a user tries to share their full screen, the result is a blank screen on the recipients end.  But when running the 32bit version, screenshare is fully working and the recipient can view the user's entire screen.

However, the next problem we ran into is that even after we install the 32bit version, Teams will self update to the x64 version automatically.  So our temporary fix to install the 32bit version can only be done temporarily.  So now we're having to resort to telling our users to go back to the older MS Teams version in order to get back screenshare.

Since we have hundreds (600+) of users that use the AVD systems amongst many teams they need to collaberate with, this is a fairly significant issue.

**Comment by ChetanSharma-msft** [comment]
We are mainly responsible for Microsoft Teams app development related issues. 

For Microsoft Teams product issues/failures your tenant Admin can reach out to [Microsoft 365 Product Support](https://docs.microsoft.com/en-us/microsoft-365/admin/contact-support-for-business-products?view=o365-worldwide&tabs=online). 

For general questions about Microsoft Teams please post your question on [Microsoft Teams Community](https://answers.microsoft.com/en-us/msteams/forum).
