### ISSUE TITLE
Referenced TeamsJS version (v.1.12) is not supported and contains known security vulnerabilities

### ISSUE THREAD

**Issue by AE-MS** [MicrosoftDocs/msteams-docs#9875]
We should encourage developers to use 1.13.1 if they require staying on the 1.x codebase. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4ae8187e-a7e4-4b5a-6f38-da6bfa30f2d2
* Version Independent ID: 4ae8187e-a7e4-4b5a-6f38-da6bfa30f2d2
* Content: [Teams JavaScript client library SDK - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/using-teams-client-library?tabs=javascript%2Cmanifest-teams-toolkit#teams-only-apps)
* Content Source: [msteams-platform/tabs/how-to/using-teams-client-library.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/tabs/how-to/using-teams-client-library.md)
* Service: **msteams**
* Sub-service: **m365apps**
* GitHub Login: @erikadoyle
* Microsoft Alias: **mosdevdocs**

**Comment by ChetanSharma-msft** [comment]
Hello @surbhigupta12 - Could you please us here to update the documentation to user 1.13.1 version of Teams JS rather than v1.12?

**Comment by sayali-MSFT** [comment]
Hello @surbhigupta12 - Could you please us here to update the documentation to user 1.13.1 version of Teams JS rather than v1.12?
