### ISSUE TITLE
Please add a note with Cross-Origin-Opener-Policy guidance

### ISSUE THREAD

**Issue by ydogandjiev** [MicrosoftDocs/msteams-docs#9895]
We recently discovered that returning the [Cross-Origin-Opener-Policy header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cross-Origin-Opener-Policy) with value "same-origin" or "same-origin-allow-popups" in any of the app's login pages severs the connection to the parent window and causes the authenticate API call to return early with the "CancelledByUser" error. Our recommendation is that app developers do not return a Cross-Origin-Opener-Policy header on their login pages.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3b1dcd0d-471b-2d33-54b5-39a93dfba2a8
* Version Independent ID: 5bd44149-777e-b449-bd2e-f20b9bd04038
* Content: [Configure third party OAuth authentication - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-tab-aad?tabs=teamsjs-v2)
* Content Source: [msteams-platform/tabs/how-to/authentication/auth-tab-aad.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/tabs/how-to/authentication/auth-tab-aad.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **surbhigupta**

**Comment by Prasad-MSFT** [comment]
Hi @surbhigupta12 - Could you please help here to add a note in the [documentation page](https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-tab-aad?tabs=teamsjs-v2) as suggested?
