### ISSUE TITLE
On Mac machine not able to switch the tenant

### ISSUE THREAD

**Issue by Vikrant2585** [MicrosoftDocs/msteams-docs#990]
Hi Team, 

I have been part of more than one tenant as a guest and now not able to switch between the tenant from TEAMS apps installed on my mac book. 

When i try to switch back it will keep brining me to my organization tenant.

**Comment by Gousia-MSFT** [comment]
@Vikrant2585 Thanks for reporting it. We are looking into this.

**Comment by Gousia-MSFT** [comment]
@Vikrant2585 Could you please provide the following information which would help us to investigate this better:
1. Desktop logs (They can be found at ~/Library/Application Support/Microsoft/Teams/logs.txt).
2. Web logs(Press Option+Command+Shift+1 with Teams app running, go to Downloads).
3. A video recording of the issue.

**Comment by Gousia-MSFT** [comment]
Please re-open with requested information.
