### ISSUE TITLE
Teams App tab showing blank screen on Android

### ISSUE THREAD

**Issue by LALITAMITTAL18** [MicrosoftDocs/msteams-docs#9920]
My app started showing blank screen on android. I debug but coudnt find any issue. So i created Teams App from scratch using Microsoft Teams app template from Visual Studio and just changed the Authentication property in appsettings.json file. The app worked everywhere but not in android.

Attched is the sample code.

[SampleTeamsAppToCheckOnAndroid.zip](https://github.com/MicrosoftDocs/msteams-docs/files/13378511/SampleTeamsAppToCheckOnAndroid.zip)

**Comment by SaiPratap-MSFT** [comment]
@LALITAMITTAL18  -  Thanks for reporting your issue. We will test this and update you soon.

**Comment by SaiPratap-MSFT** [comment]
@LALITAMITTAL18  -  Could please share more details like what does this app do and deployed app package  for better investigating the issue

**Comment by LALITAMITTAL18** [comment]
The app is basic app, created from Teams Toolkit template without no change. It has Static and configure tab as capability. Attached is the app package.

When on Static tab - it shows details from Graph API to the user like user name, profile pic etc.

When on Configure Tab - it just set the Static tab as pinned tab onAfterRenderAsync.

As I said, it is created from scratch from Visual Studio and there is no change except change of ids. The teamplate used is from Microsoft.

![image](https://github.com/MicrosoftDocs/msteams-docs/assets/51710902/071a5ab1-e46f-4741-a951-232a7163c8f2)

[SampleTeamsAppToCheckOnAndroid.zip](https://github.com/MicrosoftDocs/msteams-docs/files/13408169/SampleTeamsAppToCheckOnAndroid.zip)

**Comment by LALITAMITTAL18** [comment]
Here it is:

Microsoft Visual Studio Professional 2022
Version 17.7.6
VisualStudio.17.Release/17.7.6+34221.43
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Professional

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools   17.7.274.37181
ASP.NET and Web Tools

Azure App Service Tools v3.0.0   17.7.274.37181
Azure App Service Tools v3.0.0

Azure Data Lake Tools for Visual Studio   2.6.5000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   17.7.274.37181
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.6.5000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   4.7.0-3.23517.17+9d4cc0304792762c34f41cbbec67a1fcd2dc764f
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Chutzpah Context Menu   4.4.12
Enables you to run JavaScript unit tests via Chutzpah from the context menu

Chutzpah Test Adapter for Visual Studio 2012   4.4.12
Chutzpah adapter for the Visual Studio 2012 Unit Test Explorer. Chutzpah is an open source JavaScript test runner which enables you to run JavaScript unit tests from the command line and from inside of Visual Studio.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.4.34 (main@d5ab18b)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Microsoft Azure Hive Query Language Service   2.6.5000.0
Language service for Hive query

Microsoft Azure Stream Analytics Language Service   2.6.5000.0
Language service for Azure Stream Analytics

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Mono Debugging for Visual Studio   17.7.27 (547ea6f)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   6.7.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Razor (ASP.NET Core)   17.7.3.2333001+0ab18affdf2a37647768d0e25f5f021bee6257a1
Provides languages services for ASP.NET Core Razor.

SQL Server Data Tools   17.7.12.0
Microsoft SQL Server Data Tools

Syntax Visualizer   1.0
An extension for visualizing Roslyn SyntaxTrees.

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   17.0.20829.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.7.0-3.23517.17+9d4cc0304792762c34f41cbbec67a1fcd2dc764f
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.7.0-beta.23314.10+e612cf93b989503c89e3a5830090062b7ab5e143
Microsoft Visual F# Tools

Visual Studio Extension for SpecFlow   1.0
Visual Studio extension for working with SpecFlow projects and Gherkin feature files.

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

VSPackage Extension   1.0
VSPackage Visual Studio Extension Detailed Info

Xamarin   17.7.0.223 (d17-7@c374b3e)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   17.7.3.9 (remotes/origin/d17-7@796d191def)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin.Android SDK   13.2.1.2 (d17-5/a8a26c7)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: d9a6e87
    Java.Interop: xamarin/java.interop/d17-5@149d70fe
    SQLite: xamarin/sqlite/3.40.1@68c69d8
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d17-5@ca1552d


![image](https://github.com/MicrosoftDocs/msteams-docs/assets/51710902/fe8ace11-e473-47be-a377-3d88efcd681b)

![image](https://github.com/MicrosoftDocs/msteams-docs/assets/51710902/f7c69a0f-f22d-44ae-b541-b87f4c44b594)

![image](https://github.com/MicrosoftDocs/msteams-docs/assets/51710902/30b49250-c70b-4581-a4b0-69db333bd556)

**Comment by ChetanSharma-msft** [comment]
Hello @LALITAMITTAL18 - We have investigated your issue and please find below updates.
1) Whenever you run the application locally, it's pointing to localhost, and which is accessible from your device on which you are testing the application.
2) Since you are using localhost URL, it is not accessible from other devices like mobile etc., so you need to configure Ngrok or dev-tunnel for exposing your URL to publicly and configure the application and app package with that public URL and test the application.

Reference doc link: 
https://learn.microsoft.com/en-us/azure/developer/dev-tunnels/get-started?tabs=windows
https://ngrok.com/docs/getting-started/

Hopefully you will be able to test the app in other devices.

Thanks,

**Comment by LALITAMITTAL18** [comment]
Oh no, I understand it completely wrong. I deployed my code on a app server. I can’t give you a app package pointing to my app server. You asked me to provide app package , I gave you only a sample app package. Please change urls to your app server.

**Comment by ChetanSharma-msft** [comment]
Hello @LALITAMITTAL18 - I thought you are running your app locally.
Now, It very difficult to investigate your issue without logs.

Could you please share the error logs, so that we can further investigate your issue?
Reference link:
https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/developer-tools#access-devtools-from-an-android-device

**Comment by LALITAMITTAL18** [comment]
Can we set up a call and I can make you understand the issue. I can then share app package with you personally.

**Comment by ChetanSharma-msft** [comment]
> Oh no, you understand it completely wrong. I deployed my code on a app server. I can’t give you a app package pointing to my app server. You asked me to provide app package , I gave you only a sample app package. Please change urls to your app server.

Hello @LALITAMITTAL18 - Did you deploy code to App service or ?

**Comment by ChetanSharma-msft** [comment]
> Did you try to reproduce the issue at your end??
> 
> I think you can easily reproduce the issue at your end. As I said, I did "No Change" from default template project, just the Ids in Appsettings.json file. Deployed code works everywhere, except android. And it was working and suddnely stopped working(I dont know when). I dont see anything in Application logs/Application Insight Logs. Please let me know what you see at your end.
> 
> If not, can we set up a call and I can make you understand the issue. I can then share app package with you personally.

@LALITAMITTAL18 - We have tested the app locally and will try via deploying the code to Azure app service and let you know the updates.

**Comment by LALITAMITTAL18** [comment]
Just wanted to add, the app url itself works on browser of android phone. But when render in teams app, it shows blank screen.

**Comment by ChetanSharma-msft** [comment]
Hello @LALITAMITTAL18 - We have tried the application and getting the same issue i.e. Tab is showing blank in Android device but working fine in iOS.

Could you please enable the DevTools in Android device and debug it locally once?
https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/developer-tools#access-devtools-from-an-android-device

**Comment by LALITAMITTAL18** [comment]
I am trying multiple time, I am not able to understand anything. Localhost does not connect. I tried to load an app, but the page is always blank. I dont see the site, that is supposed to render in webview.

![image](https://github.com/MicrosoftDocs/msteams-docs/assets/51710902/a0947986-dabb-4714-b6a7-942f92533a5e)

**Comment by LALITAMITTAL18** [comment]
The code and steps are already shared above. I haven’t done anything different.

**Comment by ChetanSharma-msft** [comment]
We will try to deploy to azure app service and test it and let you know the updates.

**Comment by ChetanSharma-msft** [comment]
⁠Hello @LALITAMITTAL18,
Sorry for delay in response. ⁠

We have checked this issue with engineering team, and they mentioned that this issue is because of certificate for https://teams.exactonline.app/tab?culture=en-us. If you try to load this page in FireFox you get the below error. 

Similar issue is reported on Android Webview as well and it's related to website configuration, so we won't be able to investigate and fix this issue.

![image](https://github.com/MicrosoftDocs/msteams-docs/assets/59052547/cef1746b-bc30-4aa9-8c8f-cb077e9581ea)

Please check your website configuration and fix it accordingly.

**Comment by LALITAMITTAL18** [comment]
Thanks a lot Chetan. Let me check this with our infrastructure team.

**Comment by LALITAMITTAL18** [comment]
The issue is resolved after fixing the Certificate chain. Thanks a lot Chetan!
