### ISSUE TITLE
Remove note about mobile-only support and beta SDK requirement

### ISSUE THREAD

**Issue by ydogandjiev** [MicrosoftDocs/msteams-docs#9923]
External auth is now supported across all Teams Clients and no longer requires using a beta version of the App SDK. We need to remove the following note from this docs page:
> Note
You can add authentication to external browsers for tabs in mobile only.
Use the beta version of TeamsJS to leverage the functionality. Beta versions are available through [NPM](https://www.npmjs.com/package/@microsoft/teams-js/v/1.12.0-beta.2).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b608448b-3dd7-d5be-128c-da2859067140
* Version Independent ID: b608448b-3dd7-d5be-128c-da2859067140
* Content: [Use external OAuth providers - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-oauth-provider)
* Content Source: [msteams-platform/tabs/how-to/authentication/auth-oauth-provider.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/tabs/how-to/authentication/auth-oauth-provider.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **surbhigupta**

**Comment by Meghana-MSFT** [comment]
@surbhigupta12 - Could you please help removing the above-mentioned note from the doc section - https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-oauth-provider#add-authentication-to-external-browsers
