### ISSUE TITLE
User Specific Views changes not working in Share to Teams Dialog

### ISSUE THREAD

**Issue by Naina-G** [MicrosoftDocs/msteams-docs#9924]
We have integrated "Share to Teams" (https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/share-to-teams-from-web-apps) button in our web application. And we are showing the Share to Teams Dialog on click of the button.
Here we are showing the card unfurling in the Share to Teams Dialog which is working fine.

Now we have applied the User specific views to the card by adding the refresh clause as shown in this article(https://learn.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/up-to-date-views).
Here we can see that when we paste a link the share dialog, card unfurling works fine but refresh does not trigger in share to teams dialog.
But when the same card is shared to selected recipient and when we go to Teams App for the selected recipient or sender, there we can see that base card comes up and later refresh is also triggered and we get a user specific card.

Is there any additional configuration needed for the User specific views (refresh action) to work in Share to Teams Dialog.
(https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/share-to-teams-from-web-apps)

**Comment by sayali-MSFT** [comment]
@Naina-G - Thanks for reporting your issue.
We will check this at our end and will get back to you.
