### ISSUE TITLE
Deeplink to app install dialog is not correct

### ISSUE THREAD

**Issue by aosolis** [MicrosoftDocs/msteams-docs#9950]
<img width="654" alt="image" src="https://github.com/MicrosoftDocs/msteams-docs/assets/767208/8722d6af-4a62-4d7e-a10d-686b7e4fd5e8">

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 059b1a94-8235-8801-b9e0-ac6fbc485a7c
* Version Independent ID: 059b1a94-8235-8801-b9e0-ac6fbc485a7c
* Content: [Deep link to an application - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-link-application?tabs=teamsjs-v2)
* Content Source: [msteams-platform/concepts/build-and-test/deep-link-application.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/build-and-test/deep-link-application.md)
* Service: **msteams**
* GitHub Login: @v-npaladugu
* Microsoft Alias: **surbhigupta**

**Comment by Meghana-MSFT** [comment]
Thank you for reporting this, we will check this and get the doc updated. Thank you.

**Comment by Meghana-MSFT** [comment]
@surbhigupta12 - Could you please help to update the deeplink in this section https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-link-application?tabs=teamsjs-v2#configure-deep-link-manually-using-your-app-id as below - 

the URL in the docs should be:
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/81138249/a9d6b00b-02d7-4a10-bb0e-bfa9195071f0)
