### ISSUE TITLE
Opening a group chat using "chat.openGroupChat" is not working in outlook and working in teams. 

### ISSUE THREAD

**Issue by Pawank-MSFT** [MicrosoftDocs/msteams-docs#9955]
I'm using below code snnipet for use "chat.openGroupChat", it is working in Microsoft teams but not working in outlook.

if (chat.isSupported()) {
            const chatPromise = chat.openGroupChat({ users: [user] });
            chatPromise.
                then((result) => { console.log(result) }).
                catch((error) => { console.log(error) });
        }
        else {
            console.log("openGroupChat isn't supported");
        }

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 04055ade-1644-4a28-b7b0-39291c24f177
* Version Independent ID: d6d23a19-0fa8-e0aa-15eb-fa5ec4a3008f
* Content: [chat module - Teams](https://learn.microsoft.com/en-us/javascript/api/@microsoft/teams-js/chat?view=msteams-client-js-latest)
* Content Source: [nodejs/docs-ref-autogen/@microsoft/teams-js/chat.yml](https://github.com/OfficeDev/msteams-client-docs-ref-typescript/blob/live/nodejs/docs-ref-autogen/@microsoft/teams-js/chat.yml)
* Service: **msteams**
* GitHub Login: @charlesprakash
* Microsoft Alias: **o365devx**

**Comment by Meghana-MSFT** [comment]
Thank you for reporting this, we will check this and update you.

**Comment by Meghana-MSFT** [comment]
This issue has been fixed, closing the issue.

**Comment by mateoromero-crypto** [comment]
hola
