### ISSUE TITLE
calendar.composeMeeting not working in teams and outlook

### ISSUE THREAD

**Issue by Pawank-MSFT** [MicrosoftDocs/msteams-docs#9956]
"calendar.composeMeeting" is failing in teams and outlook it is working properly. please find the below code snippet for this.

"attendeeInput", "contentInput", "endTimeInput","startTimeInput","subjectInput" are the local variables.

const calendarPromise = calendar.composeMeeting({
                attendees: attendeeInput.value,
                content: contentInput.value.trim(),
                endTime: endTimeInput.value,
                startTime: startTimeInput.value,
                subject: subjectInput.value.trim()});
             calendarPromise.
                then((result) => {/*Successful operation*/}).
                catch((error) => {/*Unsuccessful operation*/});

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 98d88f26-f11f-4810-162a-40ca552be3e3
* Version Independent ID: 98d88f26-f11f-4810-162a-40ca552be3e3
* Content: [Deep link to a workflow in Teams - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-link-workflow?tabs=teamsjs-v1#deep-link-to-open-a-meeting-scheduling-dialog)
* Content Source: [msteams-platform/concepts/build-and-test/deep-link-workflow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/build-and-test/deep-link-workflow.md)
* Service: **msteams**
* GitHub Login: @v-npaladugu
* Microsoft Alias: **surbhigupta**

**Comment by Prasad-MSFT** [comment]
Thanks @Pawank-MSFT for raising this issue. A bug has been raised from our end for this. Once we have any update from engineering team, we will update the thread.
