### ISSUE TITLE
microsoftTeams.appInstallDialog.isSupported not supported to outlook.

### ISSUE THREAD

**Issue by Pawank-MSFT** [MicrosoftDocs/msteams-docs#9957]
microsoftTeams.appInstallDialog.isSupported is supporting in Teams but not supported to outlook. 
Below is the sample code snippet

  if(microsoftTeams.appInstallDialog.isSupported()) {
        const dialogPromise = microsoftTeams.appInstallDialog.openAppInstallDialog({ appId: "APPID" });
        dialogPromise.
        then((result) => {/*Successful operation*/}).
        catch((error) => {/*Unsuccessful operation*/});
    }
    else { 
        alert("Isn't supported");
     }  
     

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 059b1a94-8235-8801-b9e0-ac6fbc485a7c
* Version Independent ID: 059b1a94-8235-8801-b9e0-ac6fbc485a7c
* Content: [Deep link to an application - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-link-application?tabs=teamsjs-v2#deep-link-to-open-application-install-dialog)
* Content Source: [msteams-platform/concepts/build-and-test/deep-link-application.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/build-and-test/deep-link-application.md)
* Service: **msteams**
* GitHub Login: @v-npaladugu
* Microsoft Alias: **surbhigupta**

**Comment by Meghana-MSFT** [comment]
Thank you for reporting this, we will check this and update you.
