### ISSUE TITLE
Unable to debug spfx tab app in different tenant than the one where it is built. 

### ISSUE THREAD

**Issue by erikjvanderveen** [MicrosoftDocs/msteams-docs#9964]
After building the app en succesfully testing it in one tenant, I want to switch debugging to another tenant. Logged out of tenant and logged in to the other. Also created  the new tenant as environment. But when starting debug, the opened webbrowser asks to login to the other tenant but after giving password an error is shown that the account I logged in with doesn't exist and it there states the original tenant name where I did the original development. 
It seems somehow it is sticking to the original tenant.
did a full search in the repo searching if the original tenant name or ID is configured  somewhere to no avail. 
Anyone knows what could be the cause?

**Comment by ChetanSharma-msft** [comment]
Hello @erikjvanderveen - Kindly try with different browser or clear the browser cache and test it again.
Also, make sure that you have added all required configurations properly while debugging it in a different tenant.
