### ISSUE TITLE
C# Examples Context missing

### ISSUE THREAD

**Issue by MichaMican** [MicrosoftDocs/msteams-docs#9976]
There is missing crutial context for the C# Examples.
There is a link to an example repository where there is a typescript implementation. However a C# implementation could not be found.
I can't find the package where `ConversationBot` is from in the C# examples. A full C# Example repo would help a lot

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 82fb7241-2342-61b4-b5eb-3d25ad391262
* Version Independent ID: 82fb7241-2342-61b4-b5eb-3d25ad391262
* Content: [Notification bot in Teams - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/notification-bot-in-teams?tabs=ts1%2Cts2%2Cts3%2Cts4%2Cjsts%2Cts5)
* Content Source: [msteams-platform/bots/how-to/conversations/notification-bot-in-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/bots/how-to/conversations/notification-bot-in-teams.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **surbhigupta**

**Comment by sayali-MSFT** [comment]
@MichaMican - Thanks for reporting your issue.
We will check this at our end and will get back to you.

**Comment by ChetanSharma-msft** [comment]
@MichaMican - Please refer this sample for bot conversation: https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/bot-conversation/csharp

**Comment by MichaMican** [comment]
@ChetanSharma-msft
I wasn't able to find any references on the examples  using conversation.Notification.GetInstallationsAsync()

**Comment by ChetanSharma-msft** [comment]
Hello @MichaMican - Kindly elaborate more on what all the methods you are looking to refer in the sample and also share the respective doc links.

**Comment by MichaMican** [comment]
Yes awesome! I have overlooked that - I think it would be great if a c# sample would be linked in the documentation (similarly to the node/typescript sample _unless I missed that one too_)

**Comment by sayali-MSFT** [comment]
@surbhigupta12 -Could you please help us to update the document?

Please add the below point in See also section-
[Build a Teams app with C# or .NET](https://learn.microsoft.com/en-us/microsoftteams/platform/sbs-gs-csharp)

Document Link- https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/notification-bot-in-teams?tabs=ts1%2Cts2%2Cts3%2Cts4%2Cjsts%2Cts5#see-also

![MicrosoftTeams-image (6)](https://github.com/MicrosoftDocs/msteams-docs/assets/93527375/a9ae772e-b894-434a-8c29-70d6f0d4e5e6)
