### ISSUE TITLE
Define terms or provide descriptions

### ISSUE THREAD

**Issue by aosolis** [MicrosoftDocs/msteams-docs#9983]
For example:

> Prompt injections: Ensure that the text doesn't lead to prompt injections. Additionally, the description mustn't contain symbols or text that indicate that it can be used as code for prompt injection. Avoid using phrases, functions, and code that call an app recurrently.

If the reader isn't already familiar with prompt injection, they wouldn't know what this mean, and how to "ensure that the text doesn't lead to prompt injections". A link to a site that describes the issue and potential mitigations would be helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1d9e7d3e-f334-2862-3e44-e4db9d1a4fb3
* Version Independent ID: 1d9e7d3e-f334-2862-3e44-e4db9d1a4fb3
* Content: [Bot-based message extension plugin guidelines - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/high-quality-message-extension?tabs=tasks)
* Content Source: [msteams-platform/messaging-extensions/high-quality-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/messaging-extensions/high-quality-message-extension.md)
* Service: **msteams**
* GitHub Login: @v-preethah
* Microsoft Alias: **surbhigupta**

**Comment by sayali-MSFT** [comment]
Thanks for reporting your issue.
We will check this at our end and update the document accordingly.

**Comment by sayali-MSFT** [comment]
@v-ypalikila -Could you please help us to update the document?
