### ISSUE TITLE
Stage view not displaying in new MS Teams Client

### ISSUE THREAD

**Issue by aschmois-thrive** [MicrosoftDocs/msteams-docs#9985]
When loading a video player through stage view using the new Teams client, audio plays but the page itself does not load.

Attempted:
- Teams on the browser (old and new toggled) loads stage view, video appears and sound works as expected
- Old Teams client on MacOS and Windows loads stage view, video appears and sound works as expected
- New Teams client on MacOS and Windows loads stage view, video does not appear (just a blank screen, no html displayed) but sound is played.

I was advised not to upload screenshots here but can email them to showcase behavior.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 19ddf42e-0a47-7717-52d4-e549155480a2
* Version Independent ID: 4bbe9beb-233f-cfd5-097b-f280aab5fde8
* Content: [Microsoft Teams developer community support and feedback - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/feedback)
* Content Source: [msteams-platform/feedback.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/feedback.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by SaiPratap-MSFT** [comment]
@aschmois-thrive  - Thanks for reporting your issue. We will test this and update you soon.

**Comment by SaiPratap-MSFT** [comment]
@aschmois-thrive  -  Could you please share the code snippet of  video player through stage view   or deployed app package(manifest) and repro steps that would be help for better investigating
