### ISSUE TITLE
"Share To Teams" feature is not working inside stage view in web client but works fine in desktop client

### ISSUE THREAD

**Issue by SubbaReddi** [MicrosoftDocs/msteams-docs#9986]
"Share To Teams" feature is not working inside stage view in web client but works fine in desktop client. This scenario is unsupported. we cannot open a modal on top of another modal. it works on desktop because its a pop out window. Please mention note in the documentation for the same.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6c97644a-1a55-0e81-20f5-ea56a8137c7d
* Version Independent ID: 6c97644a-1a55-0e81-20f5-ea56a8137c7d
* Content: [Share to Teams from personal app or tab - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/share-to-teams-from-personal-app-or-tab)
* Content Source: [msteams-platform/concepts/build-and-test/share-to-teams-from-personal-app-or-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/build-and-test/share-to-teams-from-personal-app-or-tab.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **surbhigupta**

**Comment by sayali-MSFT** [comment]
@surbhigupta12 -Could you please help us to update the document?
